### ISSUE TITLE
Installer hangs when installing over previous, unencrypted installation

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#1007]
When installing over previous system, using the same partition layout but recreating partitions, installer hangs. On anaconda console you can see (AFAIR) `lvcreate` asking for confirmation because it detects already existing LVM header.

This problem does not exists when you enable disk encryption (which is default). So it affects mainly some test installations.

**Comment by unman** [comment]
@andrewdavidwong I believe this issue is resolved in 3.2, and can be closed
