### ISSUE TITLE
AppVM's settings dialog raises AttributeError when there is no ProxyVM

### ISSUE THREAD

**Issue by nihilifer** [QubesOS/qubes-issues#1008]
The "default NetVM" is usually the first created ProxyVM which is set by qubes-core during its creation.
https://github.com/QubesOS/qubes-core-admin/blob/master/core/qubes.py#L355

If there is no ProxyVM, there is no "default NetVM". Therefore, creating an AppVM and launching its settings dialog raised AttributeError, because get_default_netvm method returned None. The exception is raised here:
https://github.com/QubesOS/qubes-manager/blob/master/qubesmanager/settings.py#L263

This can be reproduced by installing QubesOS without creating VMs by installer.

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-manager-2.0.41-1` has been pushed to the `r2` stable repository for dom0.
To install this update, please use the standard update command:
```
sudo qubes-dom0-update
```
Or update dom0 via Qubes Manager.

[builder-github]: https://github.com/QubesOS/qubes-builder-github
