### ISSUE TITLE
Prettify list of VMs which will not be backed up

### ISSUE THREAD

**Issue by axon-qubes** [QubesOS/qubes-issues#1023]
When using `qvm-backup`, the list of VMs which will **not** be backed up is just a string of space-separated VM names. It would be nice if this list were easier to read.

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-dom0-3.1.15-1.fc20` has been pushed to the `r3.1` testing repository for dom0.
To test this update, please install it with the following command:
```
sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-admin/compare/9ac0cf85779ba9a469f70fd92634979c055db59f...c0d2d58fbfabead8f4e2fe64ea3e44467b9c9ecb

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-dom0-3.1.16-1.fc20` has been pushed to the `r3.1` stable repository for dom0.
To install this update, please use the standard update command:
```
sudo qubes-dom0-update
```
Or update dom0 via Qubes Manager.

[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-admin/compare/9ac0cf85779ba9a469f70fd92634979c055db59f...1e29d7fa396a1469541a6d64e48f398396f79780

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-dom0-3.0.29-1.fc20` has been pushed to the `r3.0` testing repository for dom0.
To test this update, please install it with the following command:
```
sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-admin/compare/d29c2889b0744d57c51ce9b14d87a411c3d84dfa...7a62c2e8a1c4eaeb934bcd56fb540b3063e98d4d
