### ISSUE TITLE
[Request] Add apparmor to kernel config

### ISSUE THREAD

**Issue by 2d1** [QubesOS/qubes-issues#1025]
While Fedora uses selinux, debian and its derivatives use apparmor. Compared to selinux, it's somewhat lacking (no roles, no sensitivities, not really mandatory). But it's *really* easy to use. Just drop in a profile.

Considering that debian is an official template now, and @Whonix* has funding, enabling apparmor in Qubes' stock kernels is a good idea.

Further, seeing as Qubes doesn't actually seem to use selinux(?), adding apparmor=1 security=apparmor by default should be considered. If there aren't any profiles, afaics nothing breaks.

----
\* For Whonix/Tails/similar in particular, limiting permissions to those necessary for expected behavior decreases the probability of (pseudo)anonymity leaks. For instance, imagine a man-in-the-not-at-all-sandboxed torbrowser exfiltrating fingerprints of a user's customized template.

**Comment by marmarek** [comment]
Done here: qubesos/qubes-linux-kernel@3d25e698129a245d5b033757d1529be056b18b66
The package kernel-qubes-vm-3.18.16-3, currently in current-testing repository
