### ISSUE TITLE
Make it possible to use Debian VM as UpdateVM for downloading dom0 updates

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#1029]

**Comment by marmarek** [comment]
Improvements made here: qubesos/qubes-core-agent-linux@3fdb67ac2b6d1f576bd3f18ac208670547761ce4
Needs more testing.

**Comment by mig5** [comment]
I updated by Debian template to use the new version of the script as per above commit, and ensured yum-utils was installed.

But my qubes-dom0-update fails with attached errors. This actually happens prior to execution of the script in question: it seems to be at the step where the yum repo stuff is tar'ed up on the dom0 and extracted in the guest via pipe to qvm-run. It looks like it missing a / slash in the extraction, maybe a distro-specific issue in use of tar on Debian compared to Fedora.

Maybe I am missing a corresponding update to the qubes-dom0-update script for dom0?

**Comment by mig5** [comment]
I found the issue: /var/lib/qubes/dom0-updates is chown root:root and chmod 755 on the Debian image.

In the Fedora image it is chown user:user and chmod 775. 

I had to make it chown user:user and chmod 775 before the tar command (and qubes-dom0-update in general) would work successfully.

Have you already accounted for this perm fix in the Debian template/qubes-core-agent package? Or perhaps the script could force the perms before the tar execution, after starting the UpdateVM, just to be on the safe side. Happy to supply a patch if I know the right place!

Thanks

**Comment by marmarek** [comment]
Apparently file permissions set in "install" stage of package build are
not preserved. According to [debian policy
manual](http://www.debian.org/doc/debian-policy/ch-files.html#s10.9.1)
this should be done in postinst script.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by adrelanos** [comment]
Is it ensured, that user `user` and group `user` exists at the time of run of `qubes-core-agent-linux`'s postinst script? Otherwise the postinst script could fail.

For reference/comparison you could look how `/var/lib/dpkg/info/tor.postinst` handles user account creation and folder permissions.

**Comment by marmarek** [comment]
On Sun, Jul 19, 2015 at 05:00:14AM -0700, Patrick Schleizer wrote:
> Is it ensured, that user `user` and group `user` exists at the time of run of `qubes-core-agent-linux`'s postinst script? Otherwise the postinst script could fail.

Yes, it is created by qubes-core-agent-linux's preinst script.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by rootkovska** [comment]
It's too late for adding any new features to 3.0, moving to 3.1 for further considerations.

**Comment by marmarek** [comment]
Actually it's not about adding - its already implemented for some time. It's about testing and deciding whether we want to include it in release notes and documentation as supported option.

**Comment by mig5** [comment]
It's been working well for me since July.
