### ISSUE TITLE
qvm-clone does not preserve firewall rules

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#1032]
https://groups.google.com/d/msgid/qubes-users/5586EE60.7010402%40hackingthe.net
> 1) Cloning an AppVM does not appear to clone all settings; in particular the
firewall rules are set to "allow all" for the clone by default. I'm not sure
whether this one already existed in R2.

**Comment by 3hhh** [comment]
Calling

qvm-block -A [VM_A] dom0:/var/lib/qubes/appvms/[VM_B]/private.img
Traceback (most recent call last):
  File "/usr/bin/qvm-block", line 151, in <module>
    main()
  File "/usr/bin/qvm-block", line 105, in main
    block_attach(qvm_collection, vm, dev, **kwargs)
  File "/usr/lib64/python2.7/site-packages/qubes/qubesutils.py", line 408,
in block_attach
    block_detach(attached_vm['vm'], attached_vm['frontend'])
  File "/usr/lib64/python2.7/site-packages/qubes/qubesutils.py", line 446,
in block_detach
    vm.libvirt_domain.detachDevice(etree.tostring(disk, encoding='utf-8'))
  File "/usr/lib64/python2.7/site-packages/libvirt.py", line 1095, in
detachDevice
    if ret == -1: raise libvirtError ('virDomainDetachDevice() failed',
dom=self)
libvirt.libvirtError: Requested operation is not valid: Domain is not
running

will result in the error above, if VM_A is running, but VM_B is not. In R2
it worked. In R3 it only works, if both VM_A and VM_B are running - which is
kind of strange as that ensures that the same file is attached to two VMs.

**Comment by 3hhh** [comment]
Just noticed one more similar issue: I created a dvm from within a VM with limited firewall rules - all rules were set to allowed all for the dvm instead of being cloned from the original VM.
The netvm settings were taken over now though (not as in R2).

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-dom0-doc-2.1.74-1` has been pushed to the `r2` stable repository for dom0.
To install this update, please use the standard update command:
```
sudo qubes-dom0-update
```
Or update dom0 via Qubes Manager.

[builder-github]: https://github.com/QubesOS/qubes-builder-github
