### ISSUE TITLE
qvm-block: Attaching dom0 files to VMs may fail in R3

### ISSUE THREAD

**Issue by 3hhh** [QubesOS/qubes-issues#1034]
Calling

qvm-block -A [VM_A] dom0:/var/lib/qubes/appvms/[VM_B]/private.img
Traceback (most recent call last):
  File "/usr/bin/qvm-block", line 151, in <module>
    main()
  File "/usr/bin/qvm-block", line 105, in main
    block_attach(qvm_collection, vm, dev, **kwargs)
  File "/usr/lib64/python2.7/site-packages/qubes/qubesutils.py", line 408,
in block_attach
    block_detach(attached_vm['vm'], attached_vm['frontend'])
  File "/usr/lib64/python2.7/site-packages/qubes/qubesutils.py", line 446,
in block_detach
    vm.libvirt_domain.detachDevice(etree.tostring(disk, encoding='utf-8'))
  File "/usr/lib64/python2.7/site-packages/libvirt.py", line 1095, in
detachDevice
    if ret == -1: raise libvirtError ('virDomainDetachDevice() failed',
dom=self)
libvirt.libvirtError: Requested operation is not valid: Domain is not
running

will result in the error above, if VM_A is running, but VM_B is not. In R2
it worked. In R3 it only works, if both VM_A and VM_B are running - which is
kind of strange as that ensures that the same file is attached to two VMs.

**Comment by 3hhh** [comment]
Funny thing:

ln -s /var/lib/qubes/appvms/[VM_B]/private.img /home/user/bla.img
qvm-block -A [VM_A] dom0:/home/user/bla.img

works as expected.

All in all qvm-block just shouldn't check the VM_B part in the path.

**Comment by 3hhh** [comment]
Funny thing:

If you create a symlink to /var/lib/qubes/appvms/[VM_B]/private.img in your home directory and use that one instead of the direct path, it will work. If you do the same in /tmp, it won't work (different error then though). This is a strange one.

**Comment by marmarek** [comment]
Fixed here: qubesos/qubes-core-admin@310ba9f1dfd0e70eeda01e6dcf740403bd722a13
