### ISSUE TITLE
Qubes Manager: starts twice in case of net-vm issues (no longer existing devices attached)

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#1037]
Sometimes, after boot, Qubes VM Manager starts twice. I.e. there will be two windows and two tray icons of Qubes VM Manager.

(Qubes Q3 RC1)

**Comment by adrelanos** [comment]
This happened in context of [no longer existing device was attached to net-vm](https://groups.google.com/d/msg/qubes-users/lPr_kndwKtQ/IheoF8gQVOkJ).

**Comment by marmarek** [comment]
Does it still happen? I believe it's already fixed. If no, please reopen.
