### ISSUE TITLE
documentation hierarchy heading sizes h1 = h2 are confusing

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#1039]
I was confused by the documentation layout. (Not addressing content here.)

Example:
https://www.qubes-os.org/doc/InstallNvidiaDriver/

The current hierarchy is:

-> Nvidia proprietary driver installation
-> RpmFusion packages
--> Download packages
--> Build kernel package
-> Manual installation
--> Userspace components
--> Kernel module
--> Configure Xorg

Legend:
* `->` stands for heading `h1`
* `-->` stands for heading `h2`

Issue:
* The headings `h1` and `h2` have (almost?) the same size.
* Therefore it's non-obvious, that one is supposed to either follow `RpmFusion packages` or `Manual installation`. Not the whole page.

Possible solutions:
* Can the size of `h1` be increased and/or the size of `h2` be decreased?
* Put `Nvidia proprietary driver installation` highest in the hierarchy. For example `Download packages` would get `h3`. Is this possible?
* Write a small introduction, that it's an either this or this, not both thing.
* Add a or an automatic table of contents. That would make the hierarchy visible. Would [jekyll-toc-generator](https://github.com/dafi/jekyll-toc-generator) work or do you already use some table of contents solution?

**Comment by unman** [comment]
From the style sheet there's a 2px diff h1,h2 (and then in steps down to h6). It isnt clear.
I'd suggest making this difference,(and that between h2 and h3), larger, and keep the 2px drops down to h6.

**Comment by unman** [comment]
Rewritten the NVidia page for clarity: included in pull request QubesOS/qubes-doc#30
Still looking at the style sheet : seems to me that 4px difference will do h1/h2/h3 and makes for a somewhat clearer layout. Does anyone actually go down to h6?
