### ISSUE TITLE
Add documentation about SOCKS connections and NetVMs

### ISSUE THREAD

**Issue by bnvk** [QubesOS/qubes-issues#1041]
There's an increasing number of apps that make opportune use of Tor by using a SOCKS connection if a user is running TorBrowser bundle. Of course, with Qubes + TorVM this is not needed. However, apps like the [Pond](https://pond.imperialviolet.org) messaging client require Tor to work. I could install and run Tor from within the Pond AppVM, but that is undesirable since i already have a Tor NetVM. 

The issue i'm having is Pond is still unaware that traffic is being routed through Tor and says "Looking for a SOCKS proxy on port 9050 or 9150"

I have read over all the docs more than once, but either i'm missing something, or perhaps some other slight documentation about this sort of thing would be helpful :)

**Comment by adrelanos** [comment]
Whonix could help here? For example in Whonix-Workstation, TBB works out of the box without Tor over Tor. So does torchat. In Whonix-Workstation, by default there are listeners as if TBB was running and forwarding those SocksPort / ControlPort connections to the appropriate ports on Whonix-Gateway. Like to try if that works for you?

**Comment by bnvk** [comment]
@adrelanos thanks for the suggestion. I found a work around with my Pond config (and will add documentation). However, Whonix very well might have helped, I'm honestly a bit confused with how to use Whonix inside of Qubes and as to what end. I hope to better understand it at some point, but currently find their docs a bit cryptic.

**Comment by adrelanos** [comment]
Yes, this all needs improvement.

FYI:
`Qubes OS Project gets OTF funding to integrate Whonix, improve usability`:
http://blog.invisiblethings.org/2015/06/04/otf-funding-announcement.html

**Comment by bnvk** [comment]
@adrelanos yah, i've heard, and it is very exciting :) I'm definitely up for better understanding / helping improve Whonix + Qubes integration and UX. If you ever want to ping me on IRC or Jabber feel free!

**Comment by marmarek** [comment]
Does it still apply since #1201 ?

**Comment by bnvk** [comment]
Probably not needed! Closing as such :-)
