### ISSUE TITLE
Windows: file-receiver doesn't send EOF properly?

### ISSUE THREAD

**Issue by omeg** [QubesOS/qubes-issues#1048]
(This might actually be a bug in Linux file sender)
When sending files from a Linux VM to a Windows VM the transfer runs correctly and files are received without errors. However, the Linux sender window seems blocked and never exits. Windows file receiver exits properly.

**Comment by omeg** [comment]
qrexec-agent didn't send EOF to data vchan when local client exited.

**Comment by marmarek** [comment]
Apparently EOF is sent after exit code. It should be sent before.

**Comment by omeg** [comment]
Fixed.
