### ISSUE TITLE
kernel 3.19 for Qubes Q3 RC2

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#1050]
Is it too much too ask to have a third kernel, Linux 3.19 installed by default for Qubes Q3 RC2?

My argument? Both work better for me out of the box on two very computers. Difference: As drastic as a working desktop environment vs just unusable flickering.

**Comment by marmarek** [comment]
Are you talking about the one from Fedora, or from qubes-dom0-unstable?

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by adrelanos** [comment]
dom0 for Qubes Q3 RC2.

**Comment by marmarek** [comment]
I was asking about kernel version. Do you have 'fc20' or 'qubes' in
kernel package release number?

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by adrelanos** [comment]
Marek Marczykowski-Górecki:
> I was asking about kernel version. Do you have 'fc20' or 'qubes' in
> kernel package release number?
> 

fc20

Chapter 'Kernel Upgrade' on
https://www.qubes-os.org/doc/SoftwareUpdateDom0/ are the instructions I
used to install that kernel.

**Comment by marmarek** [comment]
Done.
qubesos/qubes-installer-qubes-os@f7ab7b217ca3257e759a6b48c8a57e82933633f2
qubesos/qubes-installer-qubes-os@57887fd90aee44e1bbbea0ddf3a1592ac91e958c
