### ISSUE TITLE
Split GPG  wrapper cannot do --import

### ISSUE THREAD

**Issue by bnvk** [QubesOS/qubes-issues#1057]
Upon trying to use the "Import from Clipboard" feature in Enigmail and the following

`qubes-gpg-client: unrecognized option '--import'`

**Comment by marmarek** [comment]
There is a separate service (qubes.GpgImportKey), with its own wrapper
(qubes-gpg-import-key). This is to enable you to configure separately
permission to "use" the key(s) and import them.
But indeed it would be useful to have it integrated into one wrapper,
which will choose the right service automatically.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-gpg-split_2.0.22-1+deb8u1` has been pushed to the `r3.2` testing repository for the Debian `jessie` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `jessie-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-split-gpg/compare/79489349dc6029679a52d7f524b5c8de9bc5d1c6...eba027bc390d760fe018b645bb431eb6e9c6fb9f

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-gpg-split_2.0.22-1+deb9u1` has been pushed to the `r3.2` testing repository for the Debian `stretch` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `stretch-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-split-gpg/compare/79489349dc6029679a52d7f524b5c8de9bc5d1c6...eba027bc390d760fe018b645bb431eb6e9c6fb9f

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-gpg-split_2.0.22-1+deb7u1` has been pushed to the `r3.2` testing repository for the Debian `wheezy` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `wheezy-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-split-gpg/compare/79489349dc6029679a52d7f524b5c8de9bc5d1c6...eba027bc390d760fe018b645bb431eb6e9c6fb9f

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-gpg-split-2.0.22-1.fc23` has been pushed to the `r3.2` testing repository for the Fedora `fc23` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.2-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-split-gpg/compare/79489349dc6029679a52d7f524b5c8de9bc5d1c6...eba027bc390d760fe018b645bb431eb6e9c6fb9f

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-gpg-split-2.0.22-1.fc24` has been pushed to the `r3.2` testing repository for the Fedora `fc24` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.2-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-split-gpg/compare/79489349dc6029679a52d7f524b5c8de9bc5d1c6...eba027bc390d760fe018b645bb431eb6e9c6fb9f

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-gpg-split-dom0-2.0.22-1.fc23` has been pushed to the `r3.2` testing repository for dom0.
To test this update, please install it with the following command:
```
sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-split-gpg/compare/79489349dc6029679a52d7f524b5c8de9bc5d1c6...eba027bc390d760fe018b645bb431eb6e9c6fb9f

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-gpg-split_2.0.22-1+deb8u1` has been pushed to the `r3.1` testing repository for the Debian `jessie` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `jessie-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-split-gpg/compare/79489349dc6029679a52d7f524b5c8de9bc5d1c6...eba027bc390d760fe018b645bb431eb6e9c6fb9f

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-gpg-split_2.0.22-1+deb9u1` has been pushed to the `r3.1` testing repository for the Debian `stretch` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `stretch-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-split-gpg/compare/79489349dc6029679a52d7f524b5c8de9bc5d1c6...eba027bc390d760fe018b645bb431eb6e9c6fb9f

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-gpg-split_2.0.22-1+deb7u1` has been pushed to the `r3.1` testing repository for the Debian `wheezy` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `wheezy-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-split-gpg/compare/79489349dc6029679a52d7f524b5c8de9bc5d1c6...eba027bc390d760fe018b645bb431eb6e9c6fb9f

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-gpg-split-2.0.22-1.fc21` has been pushed to the `r3.1` testing repository for the Fedora `fc21` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.1-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-split-gpg/compare/79489349dc6029679a52d7f524b5c8de9bc5d1c6...eba027bc390d760fe018b645bb431eb6e9c6fb9f

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-gpg-split-2.0.22-1.fc22` has been pushed to the `r3.1` testing repository for the Fedora `fc22` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.1-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-split-gpg/compare/79489349dc6029679a52d7f524b5c8de9bc5d1c6...eba027bc390d760fe018b645bb431eb6e9c6fb9f

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-gpg-split-2.0.22-1.fc23` has been pushed to the `r3.1` testing repository for the Fedora `fc23` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.1-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-split-gpg/compare/79489349dc6029679a52d7f524b5c8de9bc5d1c6...eba027bc390d760fe018b645bb431eb6e9c6fb9f

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-gpg-split-dom0-2.0.22-1.fc20` has been pushed to the `r3.1` testing repository for dom0.
To test this update, please install it with the following command:
```
sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-split-gpg/compare/79489349dc6029679a52d7f524b5c8de9bc5d1c6...eba027bc390d760fe018b645bb431eb6e9c6fb9f

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-gpg-split_2.0.22-1+deb8u1` has been pushed to the `r3.1` stable repository for the Debian `jessie` template.
To install this update, please use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-split-gpg/compare/533fdf86589f56bbdad8bd7a73e5e2ee02ec2680...eba027bc390d760fe018b645bb431eb6e9c6fb9f

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-gpg-split_2.0.22-1+deb9u1` has been pushed to the `r3.1` stable repository for the Debian `stretch` template.
To install this update, please use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-split-gpg/compare/533fdf86589f56bbdad8bd7a73e5e2ee02ec2680...eba027bc390d760fe018b645bb431eb6e9c6fb9f

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-gpg-split_2.0.22-1+deb7u1` has been pushed to the `r3.1` stable repository for the Debian `wheezy` template.
To install this update, please use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-split-gpg/compare/533fdf86589f56bbdad8bd7a73e5e2ee02ec2680...eba027bc390d760fe018b645bb431eb6e9c6fb9f

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-gpg-split-2.0.23-1.fc23` has been pushed to the `r3.2` stable repository for the Fedora `fc23` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-split-gpg/compare/ae742d8b34394c01bee4a940fe2bcf1ac812101f...18afb385cc6f2c791f6f8c0c8c4335aca668b17f

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-gpg-split-2.0.23-1.fc24` has been pushed to the `r3.2` stable repository for the Fedora `fc24` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-split-gpg/compare/ae742d8b34394c01bee4a940fe2bcf1ac812101f...18afb385cc6f2c791f6f8c0c8c4335aca668b17f

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-gpg-split-dom0-2.0.23-1.fc23` has been pushed to the `r3.2` stable repository for dom0.
To install this update, please use the standard update command:
```
sudo qubes-dom0-update
```
Or update dom0 via Qubes Manager.

[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-split-gpg/compare/ae742d8b34394c01bee4a940fe2bcf1ac812101f...18afb385cc6f2c791f6f8c0c8c4335aca668b17f

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-gpg-split_2.0.23-1+deb8u1` has been pushed to the `r3.2` stable repository for the Debian `jessie` template.
To install this update, please use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-split-gpg/compare/ae742d8b34394c01bee4a940fe2bcf1ac812101f...18afb385cc6f2c791f6f8c0c8c4335aca668b17f

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-gpg-split-2.0.23-1.fc21` has been pushed to the `r3.1` stable repository for the Fedora `fc21` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-split-gpg/compare/ae742d8b34394c01bee4a940fe2bcf1ac812101f...18afb385cc6f2c791f6f8c0c8c4335aca668b17f

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-gpg-split-2.0.23-1.fc22` has been pushed to the `r3.1` stable repository for the Fedora `fc22` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-split-gpg/compare/ae742d8b34394c01bee4a940fe2bcf1ac812101f...18afb385cc6f2c791f6f8c0c8c4335aca668b17f

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-gpg-split-2.0.23-1.fc23` has been pushed to the `r3.1` stable repository for the Fedora `fc23` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-split-gpg/compare/ae742d8b34394c01bee4a940fe2bcf1ac812101f...18afb385cc6f2c791f6f8c0c8c4335aca668b17f

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-gpg-split-dom0-2.0.23-1.fc20` has been pushed to the `r3.1` stable repository for dom0.
To install this update, please use the standard update command:
```
sudo qubes-dom0-update
```
Or update dom0 via Qubes Manager.

[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-split-gpg/compare/ae742d8b34394c01bee4a940fe2bcf1ac812101f...18afb385cc6f2c791f6f8c0c8c4335aca668b17f
