### ISSUE TITLE
Qubes-R3-rc1-x86_64-DVD graphic card driver issue

### ISSUE THREAD

**Issue by mclrhn** [QubesOS/qubes-issues#1060]
After an uneventful instal; the  following run time problem occurs,
on first boot:
" on both screens (dual head card with  dual monitors; so before driver enters dual monitor mode);
  white square (1/5 x 1/5 screen area) top left corner, the rest repetitive rubbish" ;
Hardware details:
1/ videocard : Sapphire Radeon HD5450 !GB (DVi + VGA outputs)
2/ M/B: Asus M4A79XTD_EVO with AMD Phenom-II 965 CPU (4 core)
Returning to Qubes-R2-rc2 which has no such issue

**Comment by aberja** [comment]
I experienced the exact same issue.  Installation worked perfectly but on first boot there were big white and black squares across the screen.

After removing the video card and using the HDMI on the motherboard,  I was able to complete the install and everything seems to work properly.

I then put the video card back in and restarted Qubes and found the following:
 1. It works well up to and including the signing in screen.  The screen goes "wonky" after I sign in and the desktop appears.

 2. Sometimes I am able to see the desktop, including the mouse cursor and move it around the screens.  Other times the screen is just a garble mess of pixels (but the mouse cursor could always be seen and moved around the screen).

  3. I cannot use the program with the video card, for example:
      a. when I click on a window it turns black;

      b. If I click on an icon (like the Desktop icon) the screen becomes even more unusable...sometimes it goes fuzzy, other times it fills up with a checker board pattern while at other times it shows a menu but nothing works if I try to click on a menu item (like Leave or Lock Screen);

      c. sometimes if I double click or right click on the monitor everything clears and just shows me the desktop photo.

I have tried using just the HDMI, DisplayPort and DVI Outputs individually and none of them would work properly.

If anyone has any suggestions that I can try to see if I can rectify this, please let me know.

Hardware details:
1. Videocard: XFX Radeon HD6950
2. Motherboard: ASUS Sabertooth Z77

**Comment by aberja** [comment]
After additional testing I have narrowed down the issue to be the KDE Plasma Workspace.

Both the KDE Plasma Workspace (failsafe session) and the Xfce Session work without any issue if I switch to them on the login screen.
.

**Comment by mclrhn** [comment]
aberja; you don't mention it but do you also notice the whole problem goes away,
if you return to 'Qubes-R2-rc2-x86_64 ' ?

                      regards mclrhn

**Comment by marmarek** [comment]
Try disabling desktop effects in KDE settings - this also should help if
fail safe mode works.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by mclrhn** [comment]
Marek;
 I am assuming the above advice is to aberja;
after instal Qubes-R3-rc1-x86_64 booted into a completely scrambled screen;
no diagnostics are possible;
 (my money would be on the installer not correctly recognising the card !);
which is why I uninstalled and reinstalled Qubes-R2-rc2-x86_64;
which boots and runs flawlessly !

                                        regards mclrhn

**Comment by marmarek** [comment]
If that's a driver problem, maybe it will work for you on other kernel
version - you can select it in grub.
Also it is possible to use kernel from Fedora, which have a lot of
patches especially to fix some hardware problems, but first you need a
running system to install it...

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by aberja** [comment]
I now have video working properly under the KDE Plasma Workspace.  

As suggested by Marek I disabled the desktop effects in the KDE settings.  I did this in a KDE Plasma Workspace (fail safe session) and the settings then flowed through to the regular KDE Plasma Workspace.  

I have also tested and can advise that you can turn off the desktop effects when the screen is a mess by pressing Alt-Shift-F12.  This will return your screen to normal, allowing you to go to System Settings -> Desktop Effects and permanently disable the desktop effects at startup.
  
mclrhn, Qubes R3 is the first install I have done of Qubes, therefore I had nothing to return to.

**Comment by mclrhn** [comment]
aberja;
just out of curiosity, I reinstalled Qubes-R3-rc1-x86_64 on an old
sata drive I found in my junk box; result on boot (using F8 BIOS drive
selection)
- both srcreens scrambled with identical rubbish on both;
this suggests to me a single screen VGA driver or driver in single screen mode
-Alt-Shift-F12 had no effect as did Ctrl-Alt-Del
Any way I can now leave Qubes-R3-rc1-x86_64 on it's drive;
whilst continuing to play with Qubes-R2-rc2-x86_64.
My current Qubes project is creating, installing and running disk
images on VM's.;
specifically an ancient XP-PRO x64 version of windblows (don't ask !);
 so there is no pressing need for an upgrade

                            regards mclrhn





9:
-

**Comment by unman** [comment]
@andrewdavidwong I Have not been able to test this - please change milestone to 3.2 updates

**Comment by andrewdavidwong** [comment]
Closing for now for the reasons @esote gave and due to the prolonged lack of activity. If anyone would like this issue to remain open, please leave a comment, and we'll be happy to reopen this. Thank you.
