### ISSUE TITLE
menu drawing broken

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#1061]
Please have a look at this screenshot.

![20150714_160203](https://cloud.githubusercontent.com/assets/1985040/8675075/1d3742a2-2a42-11e5-82ba-bfaac7dd71b0.jpg)

Qubes Q3 RC1
kernel 3.19
nvidia
nouveau

Known issue? Want more info?

**Comment by adrelanos** [comment]
Happening in a Debian based AppVM. Maybe duplicate of #1051?

**Comment by marmarek** [comment]
Yes, duplicate of #1051
