### ISSUE TITLE
Media self-check fails for Qubes R3.0 rc1

### ISSUE THREAD

**Issue by 107cwk** [QubesOS/qubes-issues#1069]
Hi,

I've downloaded an ISO from http://ufpr.dl.sourceforge.net/project/qubesos/Qubes-R3.0-rc1-x86_64-DVD.iso on 2015-07-18. The MD5 is 11d3085370e8d1a752f8490952249938. The .asc file verified the ISO as signed by key 03FA5082. The fingerprint of the key used to sign the iso is C522 61BE 0A82 3221 D94C A1D1 CB11 CA1D 03FA 5082.

I've dd'd the ISO on two different USB sticks. When booting the Qubes installer I chose "test this media and install qubes OS" but the media check failed for both USB sticks. 

I've re-downloaded the ISO from http://downloads.sourceforge.net/project/qubesos/Qubes-R3.0-rc1-x86_64-DVD.iso?r=&ts=1437228394&use_mirror=garr with identical results.

The output of the media test does not show any useful output except telling me to go meddle with systemd for details - except the system is halted and I do not have a command prompt to do what it says. 
Here's the output, typed by hand so apologies for the typos:

        Starting Media check on /de/sdb...
    /dev/sdb: c5fbcb9735fa69071d93bb2b8932ca02
    Fragment Sums: 2bed... [omit] ... 8c
    Fragment Count: 20
    Press [Esc] to abort check.
    Checking: 100.0%
    
    The media check is complete, the result is: FAIL.
    
    It is not recommended to use this media.
    [FAILED] Failed to start Media check on /dev/sdb.
    See 'systemctl status checkisomd5@-dev-sdb.service' for details.
    [timestamp..] dracut-initqueue[608]: ob for checkisomd5@-dev-sdb.service failed. See 'systemctl status checkisomd5@-dev-sdb.service' and 'journalctl -xn' for detauls.
    [timestamp..] dracut: FATAL: CD check failed!
    [timestamp..] dracut: Refusing to continue
    Could not unmount /run/install/repo: Device or Resource Busy
    [timestamp..] reboot: System halted.

Please note that I've dd'd from a OSX OS using `dd if=Qubes... of=/dev/rdisk2 bs=1m`. I've also transferred the ISO to a second Linux OS, dd'd onto another USB stick but got the same results.

**Comment by marmarek** [comment]
Probably related to 4GB usb stick - our iso is slightly bigger...
