### ISSUE TITLE
Qubes-R3.0-rc1-x86_64-DVD.iso is too big for 4GB USB stick

### ISSUE THREAD

**Issue by cranderson** [QubesOS/qubes-issues#1070]
Ideally, the Qubes ISO should fit on a 4GB USB stick.  Many such USB sticks are sized based on base-10, so 4GB would be 4*1000*1000*1000 bytes.  It would be nice if Qubes could target these types of devices, and stick to a max of 4,000,000,000 bytes (3.7GiB) for the ISO images.   Currently, Qubes-R3.0-rc1 is about 25MiB (36MB) too big:

-rw-r--r--. 1 cra share 4035969024 Apr 22 11:05 Qubes-R3.0-rc1-x86_64-DVD.iso

**Comment by marmarek** [comment]
Last full test build of R3.0 is even bigger: 4057989120
@rootkovska, do we want to make it smaller? This would probably mean cutting some small package(s) out of default template(s).

**Comment by adrelanos** [comment]
Not sure it's useful to go in circles to support limited hardware. On one hand Qubes has huge hardware requirements, but on the other hand it's unreasonable for a user to spend money for a 16 GB USB stick? Not a strong opinion. @bnvk what's your view?

**Comment by bnvk** [comment]
While setting the file size limit at 4GB may be a obtuse, there
is a tradeoff for sure, as there is also the issue in terms of
download size over the net- people on less than ideal internet
connections appreciate smaller images.

As per chatting with @rootkovska yesterday, we are thinking we
will ideally want to create a "recommended list" of hardware that
Qubes can runs on for most / ideal security scenarios. Perhaps at
that point in time, we could minimize the size of the basic
install image (so it will fit on a 4GB USB stick, as well as easy
to download). And other hardware could need to be downloaded
during setup process.

That said, I don't know enough about bundling OS installers so it
will bootup / if this sort of thing is possible.

**Comment by marmarek** [comment]
@rootkovska do we want to do anything about it? The easiest way would be probably review dom0 package list and remove few of them. Or maybe simply drop debian-7 template from the ISO (keep only debian-8)?

**Comment by rootkovska** [comment]
For the 3.0 milestone it's too late, let's reconsider this in 3.1.

**Comment by marmarek** [comment]
It is quite common problem at qubes-users mailing list. Especially that the installer doesn't fail (if you choose option without verifying media), the installed system is broken (missing files).
Maybe we should consider dropping debian-7 package from installation ISO also for upcoming 3.0 release?

**Comment by marmarek** [comment]
Or qubes-dom0-debug group. But not sure if that would be enough.

**Comment by adrelanos** [comment]
If you ask me, it's fine to completely drop Debian 7 wheezy oldstable
everywhere. Oldstable gets little attention by upstream and anyone. See
how little funding / manpower they have:
https://www.freexian.com/services/debian-lts.html
