### ISSUE TITLE
qvm-block -d <device-vm-name>:<device> should be more informative if device is not attached anywhere

### ISSUE THREAD

**Issue by fowlslegs** [QubesOS/qubes-issues#1073]
qvm-block -d \<device-vm-name\>:\<device\>

If you run the command above in dom0 CL and the device is not attached anywhere, the qvm-block output should say so instead of returning a traceback.

Edit: R3-rc1

**Comment by marmarek** [comment]
Fixed here: qubesos/qubes-core-admin@6df309351dc17695864cb36da450096938c964c0
