### ISSUE TITLE
Provide (optional) helper menu to open clicked links in different VM

### ISSUE THREAD

**Issue by bnvk** [QubesOS/qubes-issues#1080]
As per some threat models / corresponding configuration of Qubes, it is fairly common to do email in one VM, chat in a different VM, and differing types of web browsing in multiple different VMs. If a user routes through a Tor-ified NetVM, in order to gain the benefit of multiple different circuits 

Since this is my threat model / configuration, I find one of the most time intensive consuming aspects of using Qubes is copying + pasting URLs via the secure clipboard to differing VMs (it's time consuming not because the process itself, but the aggregate # of times I do this in a day). 

I'm not 100% sure what the ideal UX is, but here are some ideas:
- A configuration flag in the AppVM Settings to specify "Open clicked links in [ select a vm ]"
- A dialogue when first clicking a link (similar to the "Select Nautilus as a file manager") dialogue

What happens after that setting is chosen for a given VM, I'm unsure what is feasible to do securely, but again, here are some ideas:
- The URL is validated (as a URL) and copied to the global clipboard automatically
- The "web browser VM" window is brought into focus
- The URL is copied from global clipboard into the "browser VM"

At which point it would be one simple "paste" operation to paste it into the browser bar. This would save users with configurations like this a significant amount of time!

**Comment by marmarek** [comment]
Looks related to #441.
Definitely a good idea, currently scheduled for R3.2.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by bnvk** [comment]
@marmarek cool, thanks for bumping this into the next RC :-) couple questions:

1. Will this be editable from the VM Settings panel in some way, perhaps a dropdown menu?
2. Joanna showed me a way to set this from the CLI, is that in the docs somewhere? I couldn't find it.

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
