### ISSUE TITLE
Prevent multiple VMs from simultaneously writing to same USB block device physical addresses 

### ISSUE THREAD

**Issue by fowlslegs** [QubesOS/qubes-issues#1081]
Referencing #1072, it would be nice at some point to implement a feature to the block device framework to prevent multiple VMs from simultaneously being able to write to the same physical addresses on a USB block device.

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `xen-4.6.1-15.fc21` has been pushed to the `r3.1` testing repository for the Fedora `fc21` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.1-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-vmm-xen/compare/2d284fc593110a18843574ac0c61d52cfa2a4ce9...c1f91549346b5b85dea688b9e095dd52457fa20c

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `xen-4.6.1-15.fc22` has been pushed to the `r3.1` testing repository for the Fedora `fc22` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.1-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-vmm-xen/compare/2d284fc593110a18843574ac0c61d52cfa2a4ce9...c1f91549346b5b85dea688b9e095dd52457fa20c

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `xen-4.6.1-15.fc23` has been pushed to the `r3.1` testing repository for the Fedora `fc23` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.1-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-vmm-xen/compare/2d284fc593110a18843574ac0c61d52cfa2a4ce9...c1f91549346b5b85dea688b9e095dd52457fa20c

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `xen-4.6.1-15.fc20` has been pushed to the `r3.1` testing repository for dom0.
To test this update, please install it with the following command:
```
sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-vmm-xen/compare/2d284fc593110a18843574ac0c61d52cfa2a4ce9...c1f91549346b5b85dea688b9e095dd52457fa20c

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-utils-3.1.9-1.fc21` has been pushed to the `r3.1` testing repository for the Fedora `fc21` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.1-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-linux-utils/compare/29cf44233a8b36d2aabec92947b95e6a9afb2de8...0ff9e5a78546a7e3b48df35e91305459a4e48572

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-utils-3.1.9-1.fc22` has been pushed to the `r3.1` testing repository for the Fedora `fc22` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.1-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-linux-utils/compare/29cf44233a8b36d2aabec92947b95e6a9afb2de8...0ff9e5a78546a7e3b48df35e91305459a4e48572

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-utils-3.1.9-1.fc23` has been pushed to the `r3.1` testing repository for the Fedora `fc23` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.1-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-linux-utils/compare/29cf44233a8b36d2aabec92947b95e6a9afb2de8...0ff9e5a78546a7e3b48df35e91305459a4e48572

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-utils-3.1.9-1.fc20` has been pushed to the `r3.1` testing repository for dom0.
To test this update, please install it with the following command:
```
sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-linux-utils/compare/29cf44233a8b36d2aabec92947b95e6a9afb2de8...0ff9e5a78546a7e3b48df35e91305459a4e48572

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `xen_4.6.1-17+deb8u1` has been pushed to the `r3.1` testing repository for the Debian `jessie` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `jessie-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-vmm-xen/compare/2d284fc593110a18843574ac0c61d52cfa2a4ce9...a95d5db154ca4bec8c8e6fe392fdd027afb984cc

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-utils_3.1.9+deb8u1` has been pushed to the `r3.1` testing repository for the Debian `jessie` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `jessie-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-linux-utils/compare/29cf44233a8b36d2aabec92947b95e6a9afb2de8...0ff9e5a78546a7e3b48df35e91305459a4e48572

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `xen_4.6.1-17+deb9u1` has been pushed to the `r3.1` testing repository for the Debian `stretch` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `stretch-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-vmm-xen/compare/2d284fc593110a18843574ac0c61d52cfa2a4ce9...a95d5db154ca4bec8c8e6fe392fdd027afb984cc

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-utils_3.1.9+deb9u1` has been pushed to the `r3.1` testing repository for the Debian `stretch` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `stretch-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-linux-utils/compare/29cf44233a8b36d2aabec92947b95e6a9afb2de8...0ff9e5a78546a7e3b48df35e91305459a4e48572

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `xen_4.6.1-17+deb7u1` has been pushed to the `r3.1` testing repository for the Debian `wheezy` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `wheezy-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-vmm-xen/compare/2d284fc593110a18843574ac0c61d52cfa2a4ce9...a95d5db154ca4bec8c8e6fe392fdd027afb984cc

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-utils_3.1.9+deb7u1` has been pushed to the `r3.1` testing repository for the Debian `wheezy` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `wheezy-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-linux-utils/compare/29cf44233a8b36d2aabec92947b95e6a9afb2de8...0ff9e5a78546a7e3b48df35e91305459a4e48572

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-utils-3.1.9-1.fc21` has been pushed to the `r3.1` stable repository for the Fedora `fc21` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-linux-utils/compare/29cf44233a8b36d2aabec92947b95e6a9afb2de8...0ff9e5a78546a7e3b48df35e91305459a4e48572

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-utils-3.1.9-1.fc22` has been pushed to the `r3.1` stable repository for the Fedora `fc22` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-linux-utils/compare/29cf44233a8b36d2aabec92947b95e6a9afb2de8...0ff9e5a78546a7e3b48df35e91305459a4e48572

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-utils-3.1.9-1.fc23` has been pushed to the `r3.1` stable repository for the Fedora `fc23` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-linux-utils/compare/29cf44233a8b36d2aabec92947b95e6a9afb2de8...0ff9e5a78546a7e3b48df35e91305459a4e48572

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-utils-3.1.9-1.fc20` has been pushed to the `r3.1` stable repository for dom0.
To install this update, please use the standard update command:
```
sudo qubes-dom0-update
```
Or update dom0 via Qubes Manager.

[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-linux-utils/compare/29cf44233a8b36d2aabec92947b95e6a9afb2de8...0ff9e5a78546a7e3b48df35e91305459a4e48572

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-utils_3.1.9+deb8u1` has been pushed to the `r3.1` stable repository for the Debian `jessie` template.
To install this update, please use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-linux-utils/compare/29cf44233a8b36d2aabec92947b95e6a9afb2de8...0ff9e5a78546a7e3b48df35e91305459a4e48572

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-utils_3.1.9+deb9u1` has been pushed to the `r3.1` stable repository for the Debian `stretch` template.
To install this update, please use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-linux-utils/compare/29cf44233a8b36d2aabec92947b95e6a9afb2de8...0ff9e5a78546a7e3b48df35e91305459a4e48572

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-utils_3.1.9+deb7u1` has been pushed to the `r3.1` stable repository for the Debian `wheezy` template.
To install this update, please use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-linux-utils/compare/29cf44233a8b36d2aabec92947b95e6a9afb2de8...0ff9e5a78546a7e3b48df35e91305459a4e48572

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `xen-4.6.1-20.fc20` has been pushed to the `r3.1` stable repository for dom0.
To install this update, please use the standard update command:
```
sudo qubes-dom0-update
```
Or update dom0 via Qubes Manager.

[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-vmm-xen/compare/2d284fc593110a18843574ac0c61d52cfa2a4ce9...7644813eaa6a77d1106dcda932edbda93c042cce

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `xen-4.6.1-20.fc21` has been pushed to the `r3.1` stable repository for the Fedora `fc21` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-vmm-xen/compare/2d284fc593110a18843574ac0c61d52cfa2a4ce9...7644813eaa6a77d1106dcda932edbda93c042cce

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `xen-4.6.1-20.fc22` has been pushed to the `r3.1` stable repository for the Fedora `fc22` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-vmm-xen/compare/2d284fc593110a18843574ac0c61d52cfa2a4ce9...7644813eaa6a77d1106dcda932edbda93c042cce

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `xen-4.6.1-20.fc23` has been pushed to the `r3.1` stable repository for the Fedora `fc23` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-vmm-xen/compare/2d284fc593110a18843574ac0c61d52cfa2a4ce9...7644813eaa6a77d1106dcda932edbda93c042cce

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `xen_2001:4.6.1-20+deb8u1` has been pushed to the `r3.1` stable repository for the Debian `jessie` template.
To install this update, please use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-vmm-xen/compare/2d284fc593110a18843574ac0c61d52cfa2a4ce9...7644813eaa6a77d1106dcda932edbda93c042cce

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `xen_2001:4.6.1-20+deb9u1` has been pushed to the `r3.1` stable repository for the Debian `stretch` template.
To install this update, please use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-vmm-xen/compare/2d284fc593110a18843574ac0c61d52cfa2a4ce9...7644813eaa6a77d1106dcda932edbda93c042cce

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `xen_2001:4.6.1-17+deb7u1` has been pushed to the `r3.1` stable repository for the Debian `wheezy` template.
To install this update, please use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-vmm-xen/compare/2d284fc593110a18843574ac0c61d52cfa2a4ce9...7644813eaa6a77d1106dcda932edbda93c042cce
