### ISSUE TITLE
qubesdb-read /qubes-template-type -> StandaloneVM / TemplateBasedVM

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#1084]
Feature request. For Whonix usability ([ticket](https://phabricator.whonix.org/T372)), a new `qubesdb-read` keyword would be useful. One that reveals if being run within a StandaloneVM vs TemplateBasedVM. Example:

* `qubesdb-read /qubes-template-type` -> `StandaloneVM`
* `qubesdb-read /qubes-template-type` -> `TemplateBasedVM`

Trivia:

* What I do not mean:
 * `qubesdb-read /qubes-vm-type` ->`TemplateVM`
 * `qubesdb-read /qubes-vm-type` -> `ProxyVM`
* Testing from inside a Standalone ProxyVM:
 * `qubesdb-read /qubes-vm-type` -> `ProxyVM` (no way to find out if a Standalone ProxyVM or TemplateBased ProxyVM)

**Comment by bnvk** [comment]
@adrelanos I notice you keep using the term `TemplateBasedVM` in cases where I would use `AppVM` is the term you're using the preferred term? Upon getting familiarized with Qubes & the Docs, it seem AppVM was the term used most often. Perhaps we should synchronize and use just one term so as to not confuse new commers?

**Comment by adrelanos** [comment]
@bnvk: answered this on qubes-devel mailing list:
https://groups.google.com/forum/#!topic/qubes-devel/BhSrzDdB5To

**Comment by adrelanos** [comment]
Marek [explained](https://phabricator.whonix.org/T371#6039) to me that this is already possible.
