### ISSUE TITLE
Feature: optionally shut down UpdateVM after applying updates

### ISSUE THREAD

**Issue by mig5** [QubesOS/qubes-issues#1085]
I added a feature to optionally shut down the UpdateVM after running qubes-dom0-update. Since I have a dedicated UpdateVM for this purpose, it is useful for me (I never need the VM to keep running after applying updates).

There is a pull request at https://github.com/QubesOS/qubes-core-admin-linux/pull/1, feel free to merge or close if it's not needed, no worries :)

Thanks

**Comment by marmarek** [comment]
What about simply calling something like:

    qubes-dom0-update ... ; qvm-shutdown `qubes-prefs updatevm`

**Comment by marmarek** [comment]
Alternatively, if you still think that automatic shutdown is useful, perhaps do it when the VM wasn't running before (i.e. when it was started by `qubes-dom0-update`)?

**Comment by adrelanos** [comment]
Or `qubes-dom0-update ... && qvm-shutdown 'qubes-prefs updatevm'`. Perhaps write a small wrapper script to automate this.

I wonder how common this use case is.

**Comment by mig5** [comment]
Cool - of course I can just write a wrapper script. So it is an unwanted/unnecessary feature - what a much more succinct way to say it :)

No worries.
