### ISSUE TITLE
bug, not using errtrace when using VERBOSE

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#1088]
I find the following quite strange.

Example:
https://github.com/marmarek/qubes-linux-template-builder/blob/fe6b1be0dbc1621256b33110e7511e29c6cd789d/qubeize_image

```
if [ "$VERBOSE" -ge 2 -o "$DEBUG" == "1" ]; then
    set -x
else
    set -e
fi
```

Yes, I want verbose output, but if I want this, why would I want to skip `set -e`?

Also, if I want to use verbose, then from start. Not after a few lines already have been run.

**Comment by adrelanos** [comment]
Example pull request:
https://github.com/marmarek/qubes-linux-template-builder/pull/5

(Similar cases need to be fixed. Can provide pull requests, after agreeing on the principle.)

Current implementation:
https://github.com/marmarek/qubes-linux-template-builder/blob/fe6b1be0dbc1621256b33110e7511e29c6cd789d/qubeize_image

Proposed implementation:
https://github.com/adrelanos/qubes-linux-template-builder/blob/995c98e512725e280ad2093eaf2a3cbe236da55e/qubeize_image

(As an orthogonal issue, `set -e` happens very late. Probably should be done after the if verbose with `set -x`. But if that makes sense is a different topic. Haven't changed this yet, because that would likely be a more risky change.)

**Comment by marmarek** [comment]
Is it all, or somewhere this bug is still present?

**Comment by adrelanos** [comment]
That's all.
