### ISSUE TITLE
bash's local keyword misconception

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#1092]
There is a common misconception about bash's `local` keyword. I think in https://github.com/QubesOS/qubes-issues/issues/1089#issuecomment-126108660 it's at work.
```
    #local code=$(declare -p "$array")  # Original line; now replaced with line below
    local code=$(declare -p "$array" 2> /dev/null || true)  # This was line causing error
```

`local` will always return `0`. Yes. That's it. Code talks...

script:

```
#!/bin/bash
set -x
set -e
test_function() {
   local somevar=$(this-fails)
   true "does not matter, script goes on"
}
test_function
```

output:

```
+ set -e
+ test_function
++ this-fails
./a: line 5: this-fails: command not found
+ local somevar=
+ true 'does not matter, script goes on'
```

If you preferred it fail, you could not write local and the command in question int the same line.
```
local somevar
somevar=$(this-fails)
```

In the example above it probably doesn't matter either way. My point is, if you are using `local` elsewhere, where non-zero exit codes matter, consider fixing this. That's all. Once agreed on this, this is closeable, unless you think this needs further work.

@nrgaway

**Comment by unman** [comment]
I've reviewed all bash files under marmarek  - I don't see one where this is an issue.
Suggest close.

**Comment by nrgaway** [comment]
Interesting.  I was wondering why that statement did not fail; that's the reason I mentioned it.  In that case I would not want it to fail anyway.

Thanks for the heads up!
