### ISSUE TITLE
Website: restore search widget

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#1093]
I guess simply partially revert qubesos/qubesos.github.io@938ba3779defd2a85cbaefd74460461cdffc81c2

**Comment by axon-qubes** [comment]
Would [this](https://github.com/PascalW/jekyll_indextank) be a better way to make the website searchable? (If so, would it be enough of an improvement to merit re-opening this issue?)

**Comment by marmarek** [comment]
On Fri, Oct 23, 2015 at 11:12:03PM -0700, Axon wrote:
> Would [this](https://github.com/PascalW/jekyll_indextank) be a better way to make the website searchable? (If so, would it be enough of an improvement to merit re-opening this issue?)

```
How to use:

 - Place jekyll_indextank.rb inside the _plugins folder in the root of
your jekyll site.
```

Will not work on github...

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?
