### ISSUE TITLE
Qubes Manager should allow to pass `--ignore-missing` on backup restores

### ISSUE THREAD

**Issue by rootkovska** [QubesOS/qubes-issues#1096]
... or otherwise it is annoying for users who migrate from Qubes R2 to R3 to get around the templates mismatches (effectively we're forcing them to use cmdline qvm-backup-restore)

**Comment by marmarek** [comment]
But there is already an option 'ignore missing'. Isn't it enough?

**Comment by rootkovska** [comment]
Actually it is, indeed :)
