### ISSUE TITLE
qubes-linux-template-builder verbosity disabling bug

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#1100]
There is a problem with [setVerboseMode](https://github.com/QubesOS/qubes-linux-template-builder/blob/5a2b7a40003f839bcd67dd26011cda6828caaae7/functions.sh#L17-L27).

When xtrace is already set, then setVerboseMode actually disabled xtrace. (Because it's not cached in variable `XTRACE`.) This could be reproduced by `source`ing `functions.sh` while `set -x` is already set.

`setVerboseMode` is only used in two places:

* https://github.com/QubesOS/qubes-builder-debian/blob/master/template_debian/distribution.sh
* https://github.com/QubesOS/qubes-builder-fedora/blob/master/template_scripts/distribution.sh

`getXtrace` and `setXtrace` is just used once in function `umount_kill`. Would it really be that verbose to justify going in circles just for temporarily disabling xtrace?

Can we remove whole `setVerboseMode`, `getXtrace` and `setXtrace`? I could provide a pull request for it. Or can you fix it?

**Comment by marmarek** [comment]
Feel free to remove `setVerboseMode`, IMO we have better things to do than thinking
how to fix it. Regarding `getXtrace` and `setXtrace` in umount_kill - I
think it's a good idea to keep them (maybe just an inline if you want) -
umount_kill is called also after failed build and is pretty verbose -
will make much harder to find the actual error message.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by adrelanos** [comment]
Pull requests are attached above.

**Comment by adrelanos** [comment]
https://github.com/adrelanos/qubes-linux-template-builder/commit/e84645e5972d5a38f6273fb36398760660db5cfb#commitcomment-12529288
> Actual disabling xtrace got lost here...

Indeed. If it's otherwise mergeable, could you please merge it and add the missing `set +x`?

**Comment by marmarek** [comment]
On Tue, Aug 04, 2015 at 04:24:09PM -0700, Patrick Schleizer wrote:
> https://github.com/adrelanos/qubes-linux-template-builder/commit/e84645e5972d5a38f6273fb36398760660db5cfb#commitcomment-12529288
> > Actual disabling xtrace got lost here...
> 
> Indeed. If it's otherwise mergeable, could you please merge it and add the missing `set +x`?

Sure.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by adrelanos** [comment]
Since my pull request was merged. And thanks to marek for adding the missing `set +x`:
https://github.com/marmarek/qubes-linux-template-builder/commit/0b8d27c1fb6c3609dcd293faeabb8a15b229c4a1

Done.
