### ISSUE TITLE
Add template-related info to qubesdb

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#1101]
Two new keys:

1. `/qubes-vm-persistence`:
   * `full` - standalone / template
   * `rw-only` - template based (it's reference to /rw, since it isn't only /home)
   * `none` - DispVM

2. `/qubes-base-template`, which would contain name of template on which the VM is based (in case of TemplateBasedVMs), or empty string in case of standalone VM/template. After some consideration, VM already has ability to get the template name (for example from logs), so this will not pose additional
data leak.

Discussion and reasoning here:
https://groups.google.com/d/msgid/qubes-devel/20150802204109.GK3332%40mail-itl

**Comment by adrelanos** [comment]
Looks like there is a bug or derivation from the above plan? Just now checked. Running `qubesdb-read /qubes-vm-persistence` in a DispVM returns `rw-only` rather than `none` as suggested above.

**Comment by marmarek** [comment]
On Thu, Sep 03, 2015 at 10:56:04AM -0700, Patrick Schleizer wrote:
> Looks like there is a bug or derivation from the above plan? Just now checked. Running `qubesdb-read /qubes-vm-persistence` in a DispVM returns `rw-only` rather than `none` as suggested above.

Oops, indeed. Fixed.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?
