### ISSUE TITLE
Mouse sized incorrectly and a white box follows

### ISSUE THREAD

**Issue by Tsangares** [QubesOS/qubes-issues#1104]
After installing the latest version of qubes, the cursor looks smooshed vertically, not horizontally, and there is a 1in x 1/2 in white box that follows the cursor around the screen. I have no idea what would cause this, any suggestions?

Update: The white box now appears to be colourful static rather than a white box.

**Comment by marmarek** [comment]
Can't reproduce. Maybe ask on qubes-users mailing list.
