### ISSUE TITLE
Do no restore (some of) the Dom0 home dir on backup restore

### ISSUE THREAD

**Issue by rootkovska** [QubesOS/qubes-issues#1106]
When the user wants to restore only a subset of his or her VMs, but decides to restore also the Dom0 home dir (the default option suggested by the Qubes Manager and qvm-backup-restore), then this will also bring `~/.local/share/{applications,desktop-directories}` content, which itself contains _all_ the appmenus the user had while making the backup. This will result in creation of extra appmenus, not backed up by real AppVMs. Very annoying to remove them manually later on, which should be done using:

```
xdg-desktop-menu uninstall ~/.local/share/desktop-directories/xyz.directory ~/.local/share/applications/xyz*
```

**Comment by marmarek** [comment]
One problem with excluding those directories completely - it will also exclude user-created menu entries. For example I have additional entries for DispVMs (other browsers mostly). Some people create entries for applications without proper `desktop` file, etc.
Maybe it should be some smart exclude to still include user-created entries? Or simply optional feature (enabled by default) to exclude those entries during restore (but keep then in the backup). Then if user want to restore any custom entries, he/she would also need to possibly delete unwanted ones manually (as you've done).

**Comment by rootkovska** [comment]
Given how the appmenu restore process has *always* left me with broken appmenus, I would consider this a big advantage, actually. Seriously.

**Comment by rootkovska** [comment]
I vote for just excluding the .local/share/{applications,desktop-directories} by default. Given that majority of users would not make custom menu entries, this seems like a reasonable decision, to make sure that the _majority_ of the users would not get screwed appmenus after restore.

**Comment by andrewdavidwong** [comment]
Related: #2271

**Comment by marmarek** [comment]
Since #2271 is implemented, this is fixed too.
