### ISSUE TITLE
Qubes VM Manager: crash

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#1110]
Since I upgraded from the testers repository, Qubes VM Manger is sometimes crashing. Was starting net-vm. Window closes. Gone. Version `3.0.7-1`.

I have an `strace -f qubes-manager`. Should I attach? Would that help? Or would you like any other means of debugging?

**Comment by marmarek** [comment]
Backtrace would be better. If there wasn't error message window, check
on stderr (`~/.xsession-errors`).
-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by adrelanos** [comment]
I was confused. `strace -f qubes-manager` doesn't even show up a window.

There wasn't an error in the terminal.

~/.xsession-errors:
http://justpaste.it/mx1j

I failed to empty the file and to reproduce so you could read a smaller ~/.xsession-errors.

**Comment by adrelanos** [comment]
Quote @marmarek from https://groups.google.com/d/msg/qubes-users/y8ChV2zh4gY/Ol095qqnLAAJ

> I think I've found a fix, just want to confirm that fixes the problem in
your case. Open /usr/lib64/python2.7/site-packages/qubes/qubesutils.py,
go to line 826 and change VIR_DOMAIN_EVENT_STARTED to
VIR_DOMAIN_EVENT_RESUMED. Then restart qubes-manager.

I've applied this fix and since then, Qubes Manger never crashed for me again. No longer able to reproduce this issue. Before it crashed quite often. Therefore closing this one.

**Comment by marmarek** [comment]
Wait a sec, for fix being pushed to the repo :)

**Comment by adrelanos** [comment]
Got another Qubes VM Manager crash. Before I did `qvm-run --all "sudo poweroff'`. From then I was unable to start sys-net again. Qubes VM Manager kept crashing. I try gathering the debug info as explained in https://groups.google.com/forum/#!msg/qubes-users/y8ChV2zh4gY/Ol095qqnLAAJ.
