### ISSUE TITLE
Use SHA256 or SHA512 for all PGP signatures

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#1116]
SHA256 or SHA512 should be used as the digest algorithm for PGP signatures on all of the following:
- [x] ISOs (switched to SHA256)
- [x] Developer emails (switched to SHA256)
- [ ] QSBs (partial: Marek switched to SHA256; Joanna is still using SHA1)
- [ ] Warrant canaries (partial: Marek switched to SHA256; Joanna is still using SHA1)

**Comment by axon-qubes** [comment]
Does anyone know if there's any reason to prefer SHA512 over SHA256 (either in general or for specific purposes)? For example, the Tor Project signs their TBB archives with SHA512, but I'm not sure whether that's because it's more secure or faster[1] or both.

[1] http://crypto.stackexchange.com/q/26336

**Comment by axon-qubes** [comment]
[SHA-1 Freestart Collision](https://www.schneier.com/blog/archives/2015/10/sha-1_freestart.html)

> **Abstract:** We present in this article a freestart collision example for SHA-1, i.e., a collision for its internal compression function. This is the first practical break of the full SHA-1, reaching all 80 out of 80 steps, while only 10 days of computation on a 64 GPU cluster were necessary to perform the attack. [...]

**Comment by andrewdavidwong** [comment]
@rootkovska, would you be willing to switch to SHA256 or SHA512 for signing QSBs and canaries? Your signatures on those are the only two things left.

**Comment by marmarek** [comment]
@rootkovska you can simply add `digest-algo SHA256` to `~/.gnupg/gpg.conf` in your qubes-secpack accessing VM (or appropriate split-gpg backend).

**Comment by rootkovska** [comment]
Sure, I shall switch for the next secpack canary.

**Comment by rootkovska** [comment]
Done, see my sig on the QSB 25.
