### ISSUE TITLE
info disconnect between xentop and Qubes VM Manager

### ISSUE THREAD

**Issue by mfc** [QubesOS/qubes-issues#1120]
Running xentop in dom0 one can see that dom0 uses a bunch of CPU sometimes.

This is not reflected in the Qubes VM Manager at all (CPU stays at 0).

Expected behavior: xentop info should be accurately reflected on in Qubes VM Manager.

Reported at CCCamp! 

Qubes 3.0RC2, both installed and live USB.

**Comment by marmarek** [comment]
Yup, dom0 CPU stats are not implemented there... Maybe we should just hide that bar (for dom0) for now?

**Comment by mfc** [comment]
yes this should be hidden by default, and replaced with the [NetVM info column](https://github.com/QubesOS/qubes-issues/issues/2605).

**Comment by jpouellet** [comment]
OTOH, this is useful to diagnose "why are my fans running?" when some VM has gone rogue and is hanging at 100% CPU

@mfc how do you recommend people know which VM to kill without the cpu column?

**Comment by mfc** [comment]
so are you proposing having "n/a" for dom0 listing in CPU instead? how do we communicate to users to trust some of the information provided in the CPU column but not all of it?

anyway it is still available to users, just not visible by default. I think this is the appropriate choice for the time being.

obviously we are interested in an accurate display CPU usage for all VMs, I am deferring to Marek re: time & prioritization of this functionality (which I feel is low). this ticket will follow such implementation.

**Comment by unman** [comment]
@andrewdavidwong Confirmed this issue still arises in 3.2 milestone

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
