### ISSUE TITLE
Application Launcher show all dispVM apps

### ISSUE THREAD

**Issue by dncohen** [QubesOS/qubes-issues#1123]
Qubes R3.0 rc2

I've noticed when a disposable vm is running, it appears in the application launcher (lower left of screen).  While most vms show only a select few launchable programs, the dispvm shows closer to a hundred.  As I mouse over each vm, the dispvm app list basically fills my entire screen.

Not sure how to capture a screen shot, or I would include it.

**Comment by unman** [comment]
Interesting. I havent seen this, and wonder what those 100 entries are.
Do you have a menu entry for the disposableVM-template? Does a new entry appear for each dispVM that you open?
Can you check with qvm-prefs if your dispVM template has Internal = False?

In kde, PrintScreen should be mapped to KSnapshot, so you can take a screen shot, and then copy it from dom0 to a VM:
cat fname | qvm-run --pass-io targetVM 'cat > /home/user/fname'
