### ISSUE TITLE
ProxyVM not working all the time

### ISSUE THREAD

**Issue by Scinawa** [QubesOS/qubes-issues#1126]
Hi, 
I have experienced a issue with a ProxyVM I use for openvpn. 
My appvm is attached to the proxyvm (both with a fedora21 template). Inside the proxyvm i run openvpn in command line. 
Sometimes my appvm just ignore the proxyvm, resulting in a direct access to the internet, withouth passing through the vpn. 
Perhaps is something related to a networking problem 

When I experience the issue again I would be able to run some tests: tcpdump in proxyvm 
A patch could be write some iptables line to drop all non vpn connection in netvm

Thank you

**Comment by unman** [comment]
@Scinawa 
There have been quite a few posts on qubes-users on setting up and using openvpn. How are you directing traffic to the openvpn tunnel?
It's simple to add rules in /rw/config/qubes-firewall-user-script to capture dns, redirect traffic down the tunnel, and restrict output from the proxyVM to openvpn tunnel. (If you do this then you neednt worry about leaks and you have the option of switching the appVM to another proxyVM/netVM without reconfiguration if you choose.)

**Comment by mfc** [comment]
hi @Scinawa, I don't know if you saw the [recent post](https://groups.google.com/d/msg/qubes-users/tC6SBAD_yr4/GnUVHeu8JAAJ) in qubes-users, the poster had more success with setting up OpenVPN on Debian template. Could be worth testing out to see if it's better at dropping non-VPN traffic.

**Comment by axon-qubes** [comment]
I'm assuming this issue has been resolved based on the lack of recent activity. If not, please feel free to re-open it.
