### ISSUE TITLE
Qubes doesn't allow you to create non-Qubes Xen VMs

### ISSUE THREAD

**Issue by qubesuser** [QubesOS/qubes-issues#1134]
Currently attempting to create Xen VMs using the normal Xen tools, virsh and virt-manager doesn't work.

It should work since being able to use the same Qubes Xen instance for deploying normal server VMs is useful for developers spinning up test VMs, home server usage and for VM configurations that aren't otherwise supported by Qubes.

The first problem is that the Qubes memory manager will override any memory limits on dom0, which means that VMs cannot be created due to lack of memory.

Sending SIGSTOP to qmemman_daemon and using xl mem-max dom0 and mem-set dom0 to reduce dom0 memory works around that issue.

The next issue is that apparently Qubes VM manager or maybe something else destroys any Xen VM not created by Qubes, and also crashes claiming that the domain UUIDs are unrecognized.

Both of these issues should be fixed: there should be a way to limit dom0 memory in Qubes, and non Qubes Xen VMs should be left alone and ignored.

**Comment by marmarek** [comment]
You can start a VM using custom (libvirt) config with `qvm-start --custom-config=... ...`.
