### ISSUE TITLE
Qubes Whonix-Gateway should have persistent /var/lib/tor to make entry guards persistent like non-Qubes Whonix Gateway

### ISSUE THREAD

**Issue by qubesuser** [QubesOS/qubes-issues#1137]
Currently Whonix-Gateway VMs have volatile /var/lib/tor, which means that entry guards are not saved across reboots, which is potentially dangerous since persisting them mitigates against attackers who set up malicious entry guards.

This behavior also differs from the non-Qubes Whonix Gateway, which is surprising for users who move to Qubes.

Actually, having the whole /var being persistent on all Qubes VMs seems the most reasonable approach, since being persistent, mutable and per-machine is pretty much the whole point of /var, but that's a separate consideration and there might be reasons I'm missing to do it like Qubes does now.

**Comment by adrelanos** [comment]
> Currently Whonix-Gateway VMs have volatile /var/lib/tor, which means that entry guards are not saved across reboots, which is potentially dangerous since persisting them mitigates against attackers who set up malicious entry guards.

> This behavior also differs from the non-Qubes Whonix Gateway, which is surprising for users who move to Qubes.

Confirmed. Agreed.

> Actually, having the whole /var being persistent on all Qubes VMs seems the most reasonable approach, since being persistent, mutable and per-machine is pretty much the whole point of /var, but that's a separate consideration and there might be reasons I'm missing to do it like Qubes does now.

That should be discussed elsewhere.

**Comment by adrelanos** [comment]
Fixed with the above commit. Will appear in Whonix 12.
