### ISSUE TITLE
D-Bus Error

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#1138]
Sometimes I get a popup when I try to open a text file using dolphin.

```
KLauncher could not be reached via D-Bus. Error when calling start_service_by_desktop_path:
The name org.kde.klauncher was not provided by any .service files
```

The workaround is to close dolphin and to start it again.

Qubes Q3 RC1

**Comment by marmarek** [comment]
Does it still happen? I guess fixing D-Bus activation (#1031) should have fixed this.

**Comment by adrelanos** [comment]
(Somehow I missed an e-mail notification.)

I haven't seen this popup for a long time.
