### ISSUE TITLE
Web Browser alternate cursors not respected

### ISSUE THREAD

**Issue by bnvk** [QubesOS/qubes-issues#1146]
Is it just my machine + install of Qubes or are others noticing the same issue- neither Chromium or Firefox (on Fedora) nor Chromium or IceDove (on Debian) ever displays the normal pointer, drag, enlarge, cursors never change when a mouse activity (hover, drag, etc...) would dictate as such!

**Comment by mfc** [comment]
Did you change the cursor theme from the default? (default = adwaita)

Also try changing the Window Decorations back to default, see what is breaking it.

I've never had success with alternative cursors because AppVMs don't respect the cursor selection, might be the same issue?

**Comment by bnvk** [comment]
@mfc yah, i'm still using the Adwaita cursor, good thinking though. I'll try again on a fresh install on my dev machine to confirm this!

**Comment by marmarek** [comment]
It wont work, VM have no control over cursor shape. Sorry.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by bnvk** [comment]
@marmarek are you saying due to the design of Qubes and VMs, it is (and will always be) impossible for the cursor to change within an AppVM in say a web browser? If so, that is too bad, but I suppose you should close this issue!

**Comment by marmarek** [comment]
Yup, exactly...

**Comment by mfc** [comment]
this is now discussed here: https://github.com/QubesOS/qubes-issues/issues/1551
