### ISSUE TITLE
Whonix template: /etc owned by user:user

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#1156]

**Comment by marmarek** [comment]
@nrgaway

**Comment by nrgaway** [comment]
It appears that this is only in Whonix for some reason; not Debian the
standard templates

**Comment by marmarek** [comment]
@adrelanos any idea?

**Comment by adrelanos** [comment]
No, it's a mystery. I find the cause neither in the code nor in the
build log.

**Comment by unman** [comment]
This is whonix specific, if indeed it is still open.
Can someone remove Debian label, and update to Whonix

**Comment by adrelanos** [comment]
- Not happening in Non-Qubes-Whonix 13.
- Not happening in Debian-8 template.
- Still happening in Qubes-Whonix 13.

Even though the build process has changed between Whonix 12 and Whonix 13.

**Comment by adrelanos** [comment]
This could be actually more than a minor bug. In rare cases /var/lib/tor was owned by the wrong user which can lead to Tor no longer starting. Or when using sshfs in Whonix-Workstation, the remote folder got the wrong group (neither user nor root).

Do linux distributions, adduser / useradd have something like a default user or default group that could be set wrong somewhere?

**Comment by marmarek** [comment]
On Sun, Nov 13, 2016 at 04:28:14PM -0800, Patrick Schleizer wrote:
> This could be actually more than a minor bug. In rare cases /var/lib/tor was owned by the wrong user which can lead to Tor no longer starting. Or when using sshfs in Whonix-Workstation, the remote folder got the wrong group (neither user nor root).

sshfs from Whonix-Workstation, or to Whonix-Workstation? In the former
case it shouldn't have anything to do with Whonix-Workstation, as
non-root user have no power of changing file owner (I assume you've
connected to non-root account, right?).

> Do linux distributions, adduser / useradd have something like a default user or default group that could be set wrong somewhere?

There is /etc/login.defs, but I doubt if anything wrong there would
result in changing ownership of /etc...

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by unman** [comment]
Am I missing something here? I'm working on a vanilla 3.2. I didn't create whonix VMs on set-up.
In the templates root.img everything looks as expected.
I've just created appVMs and proxyVM based on the templates and neither have /etc owned by user.
Is there another issue - the "rare cases" - or is it an intermittent build failure, or what?

**Comment by adrelanos** [comment]
/etc/login.defs looks same on my systems, but I currently have no more
VMs with this bug.

Does anyone still have a Whonix VM where /etc is owned by user:user?

If so, could you please diff Whonix /etc/login.defs and Debian
/etc/login.defs?

Marek Marczykowski-Górecki:
> sshfs from Whonix-Workstation, or to Whonix-Workstation?

From Whonix-Workstation to a server.

> I assume you've connected to non-root account, right?

Was using root login.

unman:
> Is there another issue - the "rare cases" - or is it an intermittent
build failure, or what?

I wish I knew.

**Comment by marmarek** [comment]
> Does anyone still have a Whonix VM where /etc is owned by user:user?

Yes, I have. But this one was built some time ago (qubes-template-whonix-ws-3.0.4-201601110428.noarch). I don't have build log of it unfortunately.

**Comment by unman** [comment]
@adrelanos  Is this still an open issue in 3.2?

**Comment by adrelanos** [comment]
Yes.

**Comment by adrelanos** [comment]
No longer an issue in Qubes R4 / Qubes-Whonix 14.

Closeable.

**Comment by adrelanos** [comment]
I now figured out a general bug on Debian which can cause similar issues. This is what I did.

Installed apt-cacher-ng in TemplateVM.

    sudo apt install apt-cacher-ng

Folder `/var/cache/apt-cacher-ng` will be owned by `apt-cacher-ng:apt-cacher-ng` i.e. by user `apt-cacher-ng` and by group `apt-cacher-ng`.

Then in AppVM I added folder `/var/cache/apt-cacher-ng` to bind-dirs. File `/rw/config/qubes-bind-dirs.d/50_user.conf` contents: `binds+=( '/var/cache/apt-cacher-ng' )`

I then changed the underlying TemplateVM to a different Debian based TemplateVM which does not have apt-cacher-ng installed.

I wondered why apt-cacher-ng would fail to start after installed in AppVM and noticed that folder `/var/cache/apt-cacher-ng` is now owned by an unrelated "random" non-root user/group other than apt-cacher-ng.

Qubes mount-dirs seems to keep care about user ID changes when underlying TemplateVM changes but this is only for the /home folder.

This issue /etc being owned by a some (not so) "random" user `user` might have been caused by the same mechanism that can mess up owner/group?

Possibly related? I wonder if we should port from

* useradd, groupadd and usermod

to

* adduser and addgroup

Quoted from Debian adduser manpage:

> They are friendlier front ends to the low level tools like useradd, groupadd and usermod programs, by default choosing Debian policy conformant UID and GID values,  creating a home directory with skeletal configuration, running a custom script, and other features.

**Comment by marmarek** [comment]
This could explain some weird non-root users ownership, but `/etc` should be owned by `root`, which is present everywhere and always with UID 0. Something explicitly had changed ownership of `/etc`. Anyway, it doesn't happen anymore for `/etc`.
As for bind-dirs and changing templates, do you think it's worth fixing it at all? Or leave it up to the user to manually adjust permissions? Fixing this automatically should be possible, but not necessary will be easy (you need to record desired owners, update that info when ownership is changed, handle missing users etc).

**Comment by adrelanos** [comment]
Agreed.

Speculation:

* users / groups are being referred to on the file systemd by their UID / GID, not by their name.
* users / group IDs are not being deterministic generated and depend on the order in which packages are (un)installed
* Debian adduser manpage mentions `choosing Debian policy conformant UID and GID values` which might refer to

https://www.debian.org/doc/debian-policy/ch-opersys.html

> 9.2. Users and groups
> 9.2.1. Introduction

> The Debian system can be configured to use either plain or shadow passwords.

> Some user ids (UIDs) and group ids (GIDs) are reserved globally for use by certain packages. Because some packages need to include files which are owned by these users or groups, or need the ids compiled into binaries, these ids must be used on any Debian system only for the purpose for which they are allocated. This is a serious restriction, and we should avoid getting in the way of local administration policies. In particular, many sites allocate users and/or local system groups starting at 100.

> Apart from this we should have dynamically allocated ids, which should by default be arranged in some sensible order, but the behavior should be configurable.

> Packages other than base-passwd must not modify /etc/passwd, /etc/shadow, /etc/group or /etc/gshadow.

Therefore Debian might (partially) fix this issue.

So by using adduser, addgroup and avoiding useradd, groupadd (and perhaps usermod) we might avoid some bugs.

> As for bind-dirs and changing templates, do you think it's worth fixing it at all?

If it it's possible in a way that's not too complex and doesn't make more bugs likely, yes. However, I didn't suggest fixing it since I did not have any idea how to fix that from within a script in an automated way.

> but not necessary will be easy (you need to record desired owners, update that info when ownership is changed, handle missing users etc).

Sound quite complex.

**Comment by marmarek** [comment]
> So by using adduser, addgroup and avoiding useradd, groupadd (and perhaps usermod) we might avoid some bugs.

What exactly do you mean by "we" here? From what I understand from your `apt-cacher-ng` description, it was package installation that created the user, not any qubes script nor you.

**Comment by adrelanos** [comment]
Indeed. I meant reviewing the following mentions of useradd / groupadd / usermod in any source files by Ques, and porting to adduser / addgroup wherever sensible.

```
qubes-installer-qubes-os/conf/liveusb.ks:# we won't do `useradd qubes`, since his creation depends of persistent home
qubes-installer-qubes-os/live/livesys:action "Adding live user" useradd $USERADDARGS -c "Live System User" liveuser
qubes-core-agent-linux/rpm_spec/core-agent.spec.in:  useradd --user-group --create-home --shell /bin/bash user
qubes-core-agent-linux/debian/qubes-core-agent.preinst:        useradd --user-group --create-home --shell /bin/bash user
qubes-core-agent-linux/debian/qubes-core-agent.preinst:        useradd --user-group --system -M --home /run/tinyproxy --shell /bin/false tinyproxy
qubes-core-agent-linux/archlinux/PKGBUILD.install:        useradd --user-group --create-home --shell /bin/bash user
qubes-core-libvirt/libvirt.spec.in:    useradd -r -u 107 -g qemu -G kvm -d / -s /sbin/nologin -c "qemu user" qemu
qubes-core-libvirt/libvirt.spec.in:    useradd -r -g qemu -G kvm -d / -s /sbin/nologin -c "qemu user" qem
```

```
qubes-core-agent-linux/rpm_spec/core-agent.spec.in:groupadd --force --system --gid 98 qubes
qubes-core-agent-linux/debian/qubes-core-agent.preinst:    groupadd --force --system qubes
qubes-core-agent-linux/debian/qubes-core-agent.preinst:    groupadd --force --system sudo
qubes-core-agent-linux/archlinux/PKGBUILD.install:    groupadd --force --system --gid 98 qubes
qubes-core-libvirt/libvirt.spec.in:getent group libvirt >/dev/null || groupadd -r libvirt
qubes-core-libvirt/libvirt.spec.in:getent group kvm >/dev/null || groupadd -f -g 36 -r kvm
qubes-core-libvirt/libvirt.spec.in:getent group qemu >/dev/null || groupadd -f -g 107 -r qemu
qubes-core-libvirt/libvirt.spec.in:getent group virtlogin >/dev/null || groupadd -r virtlogin
qubes-core-admin/rpm_spec/core-dom0.spec.in:            groupadd qubes
qubes-core-admin-linux/rpm_spec/core-dom0-linux.spec.in:                groupadd qubes
qubes-builder/scripts/travis-build:    sudo groupadd mock
```

```
qubes-installer-qubes-os/live/livesys:usermod -aG wheel liveuser > /dev/null
qubes-installer-qubes-os/live/livesys:usermod -aG qubes liveuser > /dev/null
qubes-linux-yum/r2/comps.xml:    <ignoredep requires="util-linux" package="usermode"/>
qubes-linux-yum/r3.2/comps-dom0.xml:    <ignoredep requires="util-linux" package="usermode"/>
qubes-core-agent-linux/rpm_spec/core-agent.spec.in:usermod -a --groups qubes user
qubes-core-agent-linux/rpm_spec/core-agent.spec.in:usermod -L user
qubes-core-agent-linux/rpm_spec/core-agent.spec.in:usermod -p '' root
qubes-core-agent-linux/rpm_spec/core-agent.spec.in:    usermod -p '*' root
qubes-core-agent-linux/debian/qubes-core-agent-passwordless-root.preinst:    usermod -p '' root
qubes-core-agent-linux/debian/qubes-core-agent.preinst:    usermod -L -a --groups qubes user
qubes-core-agent-linux/archlinux/PKGBUILD.install:    usermod -a --groups qubes user
qubes-core-agent-linux/archlinux/PKGBUILD.install:    usermod -p '' root
qubes-core-agent-linux/archlinux/PKGBUILD.install:    usermod -L user
```

Just now finished avoiding user useradd / groupadd in any source files by Whonix and ported to use adduser / addgroup.

* https://forums.whonix.org/t/port-from-useradd-groupadd-and-usermod-to-adduser-and-addgroup/7977
* https://github.com/Whonix/Whonix/commit/626de6c98c36eeea07a7b4f014a7e13b70d9a1e2

**Comment by unman** [comment]
> Speculation:
> 
>     users / groups are being referred to on the file systemd by their UID / GID, not by their name.
>     users / group IDs are not being deterministic generated and depend on the order in which packages are (un)installed

Not speculation. Internally file ownership always uses uid not name.

```
# adduser new1
# deluser new1
# adduser new2
# ls -l /home
drwxr-cr-c  2 new2 new2 4096 Aug 30 12:52 new1
drwxr-cr-c  2 new2 new2 4096 Aug 30 12:52 new2
```
