### ISSUE TITLE
Live USB R3.0-rc2 (alpha) -- Fatal Error: Could not boot

### ISSUE THREAD

**Issue by textvenux** [QubesOS/qubes-issues#1162]
Fatal Error: Could not boot
R3.0-rc2 LIVE (alpha)
The non-live installed version of R3.0-rc2 works fine.
This fatal error just happens for the LIVE version during boot.
Running on a Thinkpad.

Boot error messages:

[    6.731160] mce: Unable to init device /dev/mce/log (rc: -16)
[    9.741696] [drm:cpt_set_fifo_underrun_reporting] *ERROR* uncleared pch fifo underrun on pch transcoder A
[    9.741698] [drm:cpt_serr_int_handler] *ERROR* PCH transcoder A FIFO underrun
         Mounting Configuration File System...
[  OK  ] Mounted Configuration File System.
[  OK  ] Started Show Plymouth Boot Screen.
[  OK  ] Reached target Paths.
[  OK  ] Reached target Basic System.
[  197.305982] dracut-initqueue[382]: Warning: Could not boot.
[  197.460994] dracut-initqueue[382]: Warning: /dev/disk/by-label/Qubes-R3.0-rc2-x86_64-LIVE does not exist
[  197.464352] dracut-initqueue[382]: Warning: /dev/mapper/live-rw does not exist
         Starting Dracut Emergency Shell...
Warning: /dev/disk/by-label/Qubes-R3.0-rc2-x86_64-LIVE does not exist
Warning: /dev/mapper/live-rw does not exist

Generating "/run/initramfs/rdsosreport.txt"

Entering emergency mode. Exit the shell to continue.
Type "journalctl" to view system logs.
You might want to save "/run/initramfs/rdsosreport.txt" to a USB stick or /boot
after mounting them and attach it to a bug report.

dracut:/#

And here is a snippet from the end of /run/initramfs/rdsosreport.txt:

[  197.307130] localhost dracut-initqueue[382]: Warning: Could not boot.
[  197.455099] localhost systemd[1]: Received SIGRTMIN+20 from PID 390 (plymouthd).
[  197.464190] localhost dracut-initqueue[382]: Warning: /dev/disk/by-label/Qubes-R3.0-rc2-x86_64-LIVE does not exist
[  197.466769] localhost dracut-initqueue[382]: Warning: /dev/mapper/live-rw does not exist
[  197.483196] localhost systemd[1]: Starting Dracut Emergency Shell...
[  197.516868] localhost systemd[1]: Received SIGRTMIN+21 from PID 390 (plymouthd).

**Comment by marmarek** [comment]
Did you written the image to the USB as in instruction - using dd, or
some other "smart" tool? In case of the later one, they are often doing
that wrong (messes with device label, removes Xen etc).
Do you use USB3.0 or 2.0?

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by textvenux** [comment]
Used dd. No other smart tools.

Used USB 2.0 drive and ports.

Verified Qubes image. Burned to USB multiple times and failed same way each time. Normal installable Qubes ISO works fine using same method on this same Thinkpad machine.
