### ISSUE TITLE
tests: assertNotRaises raises AttributeError: __exit__

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#1163]
```
ERROR: basic/TC_01_Properties/test_000_rename
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/qubes/tests/basic.py", line 101, in test_000_rename
    with self.assertNotRaises(QubesException, OSError):
AttributeError: __exit__
```

**Comment by woju** [comment]
Which version of python did you use?

**Comment by marmarek** [comment]
2.7 

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by woju** [comment]
Oh, I see. `assertNotRaises` does not support multiple exceptions passed to it.

There are two ways to use it. First, as context manager, like that:

    with self.assertNotRaises(Exception):
        foo(arg1, kwarg=123)

The second one:

    self.assertNotRaises(Exception, foo, arg1, kwarg=123)

If you'd like to check two exceptions, nest the context, or reopen as feature request.

**Comment by marmarek** [comment]
It does support multiple exceptions. Just needs to pass them as a tuple.
