### ISSUE TITLE
Disable Xen MCE driver in dom0 kernel config

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#1164]
The option is `CONFIG_XEN_MCE_LOG`.
The question here is whether do we want to still build the kernel ourself, as 3.19 from Fedora repo works pretty well. If we decide to drop our kernel, move this feature request to Fedora.

**Comment by marmarek** [comment]
Some details: [mce: Unable to init device /dev/mcelog (rc: -16)](https://groups.google.com/d/msgid/qubes-users/33d15ba6-366a-4b2b-b5ff-3c04a4ce0f60%40googlegroups.com)

**Comment by Jeeppler** [comment]
For my experience Kernel 3.19 from Fedora works a lot better, than Kernel 3.18 from Qubes OS. I would prefer to drop the Qubes OS 3.18 kernel. 
Especially because the Fedora team has a lot more resources than the Qubes OS team.

**Comment by marmarek** [comment]
Some details, why it isn't working:
http://xen.markmail.org/thread/7m6qgkoss5jb3ocr

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `kernel-devel-4.1.13-8.pvops.qubes` has been pushed to the `r3.1` testing repository for the Fedora `fc21` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.1-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-linux-kernel/compare/5b042abd396906781d6ca135ace37763d291d18b...f4eb52befda8fb638c5c6c560fc64f2b9ea08741

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `kernel-devel-4.1.13-8.pvops.qubes` has been pushed to the `r3.1` testing repository for the Fedora `fc22` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.1-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-linux-kernel/compare/5b042abd396906781d6ca135ace37763d291d18b...f4eb52befda8fb638c5c6c560fc64f2b9ea08741

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `kernel-devel-4.1.13-8.pvops.qubes` has been pushed to the `r3.1` testing repository for the Fedora `fc23` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.1-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-linux-kernel/compare/5b042abd396906781d6ca135ace37763d291d18b...f4eb52befda8fb638c5c6c560fc64f2b9ea08741

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `kernel-4.1.13-8.pvops.qubes` has been pushed to the `r3.1` testing repository for dom0.
To test this update, please install it with the following command:
```
sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-linux-kernel/compare/5b042abd396906781d6ca135ace37763d291d18b...f4eb52befda8fb638c5c6c560fc64f2b9ea08741

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `kernel-devel-4.1.13-8.pvops.qubes` has been pushed to the `r3.1` stable repository for the Fedora `fc21` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-linux-kernel/compare/5b042abd396906781d6ca135ace37763d291d18b...f4eb52befda8fb638c5c6c560fc64f2b9ea08741

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `kernel-devel-4.1.13-8.pvops.qubes` has been pushed to the `r3.1` stable repository for the Fedora `fc22` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-linux-kernel/compare/5b042abd396906781d6ca135ace37763d291d18b...f4eb52befda8fb638c5c6c560fc64f2b9ea08741

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `kernel-devel-4.1.13-8.pvops.qubes` has been pushed to the `r3.1` stable repository for the Fedora `fc23` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-linux-kernel/compare/5b042abd396906781d6ca135ace37763d291d18b...f4eb52befda8fb638c5c6c560fc64f2b9ea08741

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `kernel-4.1.13-8.pvops.qubes` has been pushed to the `r3.1` stable repository for dom0.
To install this update, please use the standard update command:
```
sudo qubes-dom0-update
```
Or update dom0 via Qubes Manager.

[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-linux-kernel/compare/5b042abd396906781d6ca135ace37763d291d18b...f4eb52befda8fb638c5c6c560fc64f2b9ea08741
