### ISSUE TITLE
Documentation bug: command line options

### ISSUE THREAD

**Issue by conpage21** [QubesOS/qubes-issues#1169]
All pages listed at https://www.qubes-os.org/doc/DomZeroTools/ show double dashes "--" as "–"
Markdown issue?

**Comment by unman** [comment]
Yes, and because kramdown is used, I think the best way is to mark each use as code.
I'll do this today

**Comment by unman** [comment]
@andrewdavidwong Confirmed this issue still arises in 3.2 milestone

**Comment by andrewdavidwong** [comment]
This has been fixed.
