### ISSUE TITLE
Missing support for SVG app icons

### ISSUE THREAD

**Issue by qubesuser** [QubesOS/qubes-issues#1170]
qubes.GetImageRGBA doesn't support SVG icons, and rsvg-convert that would be required for them is not installed in templates.

This means that applications that only provide SVG icons or reference SVG files explictly in desktop files will have broken icons.

**Comment by marmarek** [comment]
Thanks for providing the fix.
According to our [release schedule](https://www.qubes-os.org/doc/VersionScheme/) only critical fixes can be accepted now, so this will probably go as an update after final release.
