### ISSUE TITLE
App icon selection algorithm is incorrect, results in black-and-white Ubuntu icons

### ISSUE THREAD

**Issue by qubesuser** [QubesOS/qubes-issues#1171]
qubes.GetImageRGBA chooses application icons in a very suboptimal way.

It first looks in /usr/share/icons/hicolor and then in /usr/share/icons and takes the PNG icon with the biggest filesize.

This is wrong: it should instead prioritize default themes like gnome and Humanity for Ubuntu and then hicolor and then the rest, it should also support SVG and XPM files and it should pick the biggest icon by the directory name (16x16, 32x32, and so on) rather than by file size.

The correct algorithm is described at http://standards.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html

Should probably use an existing implementation like this one: https://pyxdg.readthedocs.org/en/latest/_modules/xdg/IconTheme.html

**Comment by marmarek** [comment]
Thanks for providing the fix.
According to our [release schedule](https://www.qubes-os.org/doc/VersionScheme/) only critical fixes can be accepted now, so this will probably go as an update after final release.

**Comment by qubesuser** [comment]
Sure, the impact of the issue is minimal and while the code is simplye it's not a trivial fix and could cause regressions.

**Comment by marmarek** [comment]
https://groups.google.com/d/msg/qubes-users/CR5X4CqhwbI/1clqfabRAQAJ
Additionally "/usr/share/pixmap" is missing from search path.

**Comment by marmarek** [comment]
Fixed since that pull request is merged.
