### ISSUE TITLE
rename function chroot to chroot_cmd or similar

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#1174]
Rename function `chroot` to `chroot_cmd` or similar.

Code in question:
https://github.com/marmarek/qubes-linux-template-builder/blob/5897b1a88245bdcb8f0f2d454d1eb54098d0df4a/functions.sh#L67-L92

Then elsewhere ([example](https://github.com/marmarek/qubes-template-whonix/blob/be0c1f53cc10a3ccb8628d132da35006225bdff6/whonix-gateway/02_install_groups_pre.sh#L192)) you are using `chroot`. One would wonder which one it is. Function `chroot` or binary `/usr/sbin/chroot`? [In this example, it's the latter.]

This is very confusing. Generally, please don't assign the very same name to a function as an existing binary.

**Comment by marmarek** [comment]
This is API change, if using updated linux-template-builder, builder plugins also needs to be updated.
