### ISSUE TITLE
Networking stops working in Windows AppVMs after a few minutes

### ISSUE THREAD

**Issue by rootkovska** [QubesOS/qubes-issues#1180]
At first the networking work, but after a few minutes it's no more.

**Comment by omeg** [comment]
Seems to be caused by an active DHCP client (not sure why it wasn't a problem before). Disabling the DHCP service fixes it for now. I'll add disabling that to the installer as a part of "system tune-up" along with other not needed services.

**Comment by omeg** [comment]
service-policy utility now disables the DHCP client service during tools installation.
