### ISSUE TITLE
Fix sorting of VMs in backup selection dialogs

### ISSUE THREAD

**Issue by rootkovska** [QubesOS/qubes-issues#1181]
They should be sorted alphabetically. In fact they are, if one move (>>) them to another window, and back (<<).

**Comment by axon-qubes** [comment]
Related: #1022

**Comment by rootkovska** [comment]
It would be nice to have this for 3.2...

**Comment by andrewdavidwong** [comment]
IMHO, this should also apply to the text-based backup interface (in addition to the GUI backup interface). Currently, the list of VMs to be backed up is not sorted alphabetically there either.
