### ISSUE TITLE
Debian 8 apt.config.d misconfiguration

### ISSUE THREAD

**Issue by Scinawa** [QubesOS/qubes-issues#1186]
Hi guys! :)

Just want you  to know that I found /etc/apt/apt.conf.d/01qubes-proxy at least two dozen of the following lines:

Acquire::http::Proxy "http://10.137.255.254:8082/"

I don't think it causes any problem, but it looks like a small issue.

I'm on a debian8 template.

**Comment by adrelanos** [comment]
Confirmed in a Debian 8 TemplateVM.

**Comment by adrelanos** [comment]
Fixed in above pull request.
