### ISSUE TITLE
remove broken Debian [and Whonix] TemplateVM default Qubes start menu entries

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#1189]
* Help (`yelp.desktop`): Starts the Gnome help. Is that helpful in Qubes? Specifically since Qubes is based on KDE. Remove?

* Package Log (`gpk-log.desktop`): Doesn't work for me. What functionality is it supposed to provide? Remove?

* Package Sources (`gpk-prefs.desktop`): Apparently only handles /etc/apt/sources.list file. Not /etc/apt/sources.list.d folder. Confusing. Generating more trouble than benefit? Therefore, remove?

* Package Updater (`gpk-update-viewer.desktop`): Starts Apper. But it's broken. Report: `Qubes templates: graphical updater (Apper) broken` - https://phabricator.whonix.org/T373 (@nrgaway). No idea how to proceed on that ticket. I guess it will take at least three to six more months until progress will be made? Therefore, should we remove that Qubes start menu default entry?

**Comment by mfc** [comment]
I agree that removing Help, Package Log, and Package Sources makes sense, especially if they are default menu entries (if they are not then it is not so important).

I strongly disagree with removing Package Updater. As I have mentioned in the phabricator ticket and in https://github.com/QubesOS/qubes-issues/issues/1197, whatever is causing Apper to be broken needs to be fixed or there needs to be a menu item called Software Update that just runs the equivalent of 'yum update' from a terminal.

Having no button for a user to update software is not an option unfortunately.

**Comment by adrelanos** [comment]
Package Updater / Apper can now also be removed from default Qubes start menu entries, because of:

* https://github.com/QubesOS/qubes-issues/issues/1197#issuecomment-141966940
* https://github.com/marmarek/qubes-manager/pull/2

**Comment by adrelanos** [comment]
https://github.com/marmarek/qubes-builder-debian/pull/26
