### ISSUE TITLE
kernel-devel missing arch/x86/include/generated making it impossible to build modules

### ISSUE THREAD

**Issue by qubesuser** [QubesOS/qubes-issues#1192]
Somehow the kernel-devel packages for the pvops kernels are missing the arch/x86/include/generated directory, which makes building external modules fail, while the Fedora packages have it.

**Comment by unman** [comment]
@andrewdavidwong I believe this issue is resolved in 3.2, and can be closed. Installing kernel-devel on Fedora-24 provides this directory.
