### ISSUE TITLE
USB keyboard doesn't work during disk decryption password prompt with kernel 3.18.17-6

### ISSUE THREAD

**Issue by Mstes** [QubesOS/qubes-issues#1194]
Critical Problem: USB keyboard becomes non-responsive during the password prompt for HDD decryption (built-in LUKS/dm-crypt) wit Kernel  3.18.17.-6

It works fine during the bootloader sequence when selecting Xen and Kernel version.

This problem only occurs when selecting Kernel version 3.18.17.-6. I cannot test Kernel version 3.18.17-5 as this one produces errors and results in eternal reboot limbo. Only Kernel version that works fine is 3.18.10-2.

Tried unplugging and re-plugging. Also keyboards from different manufacturers. At no point did I re-assign the USB controller.

**Comment by marmarek** [comment]
Do you have USB3.0 controller? In that case it would be the same problem as #1517

**Comment by Mstes** [comment]
Yes, I do. #1517 sounds just like what I am experiencing. Thank you for taking care of this!

**Comment by marmarek** [comment]
Closing this one, because the other one has more details and already linked fix.

**Comment by marmarek** [comment]
(the fix needs to be backported to R3.0)
