### ISSUE TITLE
Create new information architecture for website

### ISSUE THREAD

**Issue by bnvk** [QubesOS/qubes-issues#1200]
As per discussion and points @rootkovska brings up in #1175 (re: documentation / organization) I believe a re-thinking of the overall sites "information architecture" is in order!

I'm spending some time digesting the current website and will create some wireframes to illustrate what I am thinking will be an improvement! This can work in conjunction with the overall branding re-design I am working on!

**Comment by axon-qubes** [comment]
Hi @bnvk... I've already done significant work on this. I think you should take a look at the site in its current state before we discuss this.

**Comment by bnvk** [comment]
@axon-qubes I have seen your work and just thanked you for it. I'm referring to the entire site, not just the documentation!

**Comment by axon-qubes** [comment]
> I'm referring to the entire site, not just the documentation!

As am I!

**Comment by bnvk** [comment]
@axon-qubes nothing I am going to propose is major and will be building on top of & with the great stuff you just did :) I'm approaching this from the very first page and where a new user goes from there!

**Comment by axon-qubes** [comment]
Sounds good. I just wanted to make sure there was no unintentional duplication of effort.

**Comment by rootkovska** [comment]
FWFW, I think we should leave screenshots menu entry names screenshots, not media, because "media" really suggests press articles, not the screenshots :P

**Comment by axon-qubes** [comment]
I renamed it to "media" because we may add things like videos in addition to screenshots. Usually, projects have a page called "Press" for press articles and other publicity, and they reserve "Media" for videos, podcasts, screenshots, streams, etc. However, it's up to you.

**Comment by bnvk** [comment]
@axon-qubes I see your point, and @rootkovska and I discussed making some videos so that would make a lot of sense to have those on the same page as screenshots. In my information architecture (IA) ideas was a "tour" page, which I think accounts for all media types, but might disambiguate from "press"

**Comment by bnvk** [comment]
Perhaps merging screenshots + media with the "Introduction" page would be fortuitous + spice it up a bit :)

**Comment by marmarek** [comment]
While at it - IMO it's good idea to merge attachments repository into
doc. Or at least place there files used in /doc/. This would make much
easier to make offline copy of the whole documentation:
https://github.com/QubesOS/qubes-issues/issues/1019

Regarding the screenshots menu - I like the idea of "tour". "media" is
IMHO misleading.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by axon-qubes** [comment]
Ok, "media" renamed back to "screenshots." :)

**Comment by bnvk** [comment]
@axon-qubes yeah very similar to /doc/GettingStarted :) except, I think the two big differences between a "tour" and the getting started page is the former "sells" the idea of using Qubes to a new user with minimal reading / deep technical understanding, while the later says "here is how you start doing so" 

IMHO, sitting square in the middle of those two things is stuff like the HCL.
To further illustrate the user's flow of clicks + train of thought I am aiming for, might be something like:

1. What is this Qubes thing all about anyway... I hear it's "super secure" *Google / click*
2. Oh... hrm... some of these features look pretty awesome...
3. Hrm... I wonder how easy it for me to try this out?
4. Oh, awesome, my computer is supported!
5. Starts downloading software and flashing a USB key.

In fact, if we were a creepy spyware type company we would use google analytics to track this exact sort of click flow... PHEW, thank the number 42 that we are not :D

**Comment by axon-qubes** [comment]
@bnvk Sounds great! I would love to see something like that on the site.

Funny you mention Google Analytics... I was thinking earlier that it would be nice to have it on the site in order to get an idea of traffic and bounce rates, but then I quickly realized that the value of *not* having any trackers on the site is actually far greater, given Qubes' audience. :)

**Comment by bnvk** [comment]
A significant amount of progress and most of my ideas here have been implemented as per #1460 so closing this issues!
