### ISSUE TITLE
Improve the Hardware Compatibility List (HCL) usability

### ISSUE THREAD

**Issue by bnvk** [QubesOS/qubes-issues#1203]
It's great to see that the HCL has been moved over to Github and .yml files, with this change it makes it much more possible to do nice usability things to improve it. Some ideas at shortly perusing it are:

- Condensing items under "manufacturer" headings
- Structuring the information to be slightly more pleasing / easier to read than a big ole <table>
- Making it searchable / filterable with [list.js](http://www.listjs.com) or [dataTables](http://datatables.net)
- Offer tooltips for some of the details

**Comment by woju** [comment]
On Tue, Sep 22, 2015 at 12:29:54PM -0700, Brennan Novak wrote:
> It's great to see that the HCL has been moved over to Github and .yml files, with this change it makes it much more possible to do nice usability things to improve it. Some ideas at shortly perusing it are:
> 
> - Condensing items under "manufacturer" headings
> - Structuring the information to be slightly more pleasing / easier to read than a big ole <table>
> - Making it searchable / filterable with [list.js](http://www.listjs.com) or [dataTables](http://datatables.net)
> - Offer tooltips for some of the details

- Fix colours. Really that should come first.

I admit I chose these hastily, in hope someone will fix them soon, but
that did not happen.

**Comment by bnvk** [comment]
@woju thanks for the feedback, that will fall under #1207 which I'm working on as well!

**Comment by marmarek** [comment]
@bnvk do you plan anything more in this ticket, or it is completed? 
FWIW IMO HCL looks great.

**Comment by axon-qubes** [comment]
I'd still like to discuss the name change, if possible (see the comments on this [commit](https://github.com/QubesOS/qubesos.github.io/commit/e3eb3c609c44c0b850ef7a8bd73721cb2f98fa2f#diff-29709b93ebdabc6581fe39d8ad83c4b2)).

**Comment by bnvk** [comment]
@marmarek i'm closing this. I have other ideas incorporating "Certified laptops" into the page, but I will revisit it at that at a later time!

@axon-qubes if I understand correctly, the value to be gained changing back to "HCL" is appeasing people who have been reading / writing Qubes docs in the past as well as people reading through the Google Groups archives. My reasoning for changing from "Hardware Compatibility List" to "Compatible Hardware" is 

1. As you say "avoid confusing non-technical users" I think what I have better in this respect.
2. It's shorter, thus easier to read / say / work into designs
3. It's good to avoid acronyms in general, HCL is what said cause "hardware compatibility list" is cumbersome
4. The URL is more SEO friendly

That said, i'm not going to block / nit pick about this. If you and others are really attached to "HCL" change it back!

> start referring to it as the "the compatible hardware list" instead of "the HCL," and "the compatible hardware tool" instead of "the HCL tool,"

As per this question, I think when writing about this page / list, my instinct as a native English speaker would be to say `list of compatible hardware` or `on the compatible hardware page`
