### ISSUE TITLE
'Files' entry missing in default appmenus for Fedora 21 template

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#1206]
Nautilus was renamed from `nautilus.desktop` to `org.gnome.Nautilus.desktop`, our default whitelist doesn't reflect that change.

**Comment by marmarek** [comment]
@rootkovska @mfc  should we include the fix in final R3.0? This isn't exactly allowed at this stage by our [release process policy](http://www.qubes-os.org/doc/VersionScheme/#release-schedule), but this is one of few changes that can't be fixed using standard update. And IMO regression risk is small here.

**Comment by mfc** [comment]
if the current outcome/issue is that Files is not listed/available on the appmenu, then yes a fix should be included for R3.0. 

As I mentioned re: #1197, if there is regression of features/usability from R2.0 --> R3.0 I don't think that is good.
