### ISSUE TITLE
rewrite qvm-service

### ISSUE THREAD

**Issue by woju** [QubesOS/qubes-issues#1227]

**Comment by woju** [comment]
services were rewritten as features, #1637

**Comment by Rudd-O** [comment]
Any details on this change?  I see no commits associated with it.

**Comment by marmarek** [comment]
Take a look at referenced ticket (and commits linked there if you like).

**Comment by Rudd-O** [comment]
Yay!

**Comment by marmarek** [comment]
There will be qvm-service tool as a compatibility layer for qvm-features.
