### ISSUE TITLE
Make file copying errors (in GUI) less technical & cryptic 

### ISSUE THREAD

**Issue by bnvk** [QubesOS/qubes-issues#1240]
Currently if a user tries to copy a file from one VM to another using the GUI commands and the file already exists in the destination, they are presented with:

```
qfile-agent: Fata error: Fire copy: not overwriting existing file. Clean QubesIncoming dir, and retry copy; Last file: name-of-file (error type: File exists)
```

And this message shows a forboding red circle icon. This should be simplified to be less scary, technical, and cryptic. The only piece of this relevant & which makes sense to a GUI user is "File exists" thus I propose:
- A more "warning" icon like a yellow or orange exclamation triangle
- A message like "A file with the same name already exists where you trying to copy to"

**Comment by marmarek** [comment]
Shouldn't that message include also name of the place where the file already exists (`QubesIncoming`)? And a file name? ...
Why this should be displayed as a warning? The copy operation aborts if any file exists in the destination location, so in my understanding this **is** an error.
