### ISSUE TITLE
Screenshots on the website load extremely slowly

### ISSUE THREAD

**Issue by rootkovska** [QubesOS/qubes-issues#1243]

**Comment by marmarek** [comment]
Can't reproduce. Are you using Tor?
Anyway complain to cloudflare/github, it's not our bug ;)

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by marmarek** [comment]
Or complain to your ISP.
The first image is almost 1MB, so may take some time on slow
connection.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by axon-qubes** [comment]
These images can (and should) be losslessly compressed. I took [the first one](https://github.com/QubesOS/qubes-attachment/blob/master/wiki/QubesScreenshots/r2b2-kde-start-menu.png) and ran it through [Kraken's] (https://kraken.io/) lossless compressor (free). [Here](https://github.com/QubesOS/qubes-attachment/blob/master/wiki/QubesScreenshots/r2b2-kde-start-menu-compressed.png) is the result.

    Original size:   962.75 KB
    Compressed size: 719.90 KB
    Savings:         242.84 KB (25.22%)

Doing this will all the images should help a fair bit. Beyond that, I agree with Marek that it's up to Cloudflare, GitHub, and the user's connection speed. (The bottleneck will almost always be the last one, IMO.)

**Comment by andrewdavidwong** [comment]
@PeterDaveHello generously optimized the images on our website (https://github.com/QubesOS/qubes-attachment/commit/c3c043b78969adaa63c5d0b8584892765b9e88cb, https://github.com/QubesOS/qubes-attachment/commit/c1bf0407d47d7c1e223edf18164cca9c1b1c3882), so loading times should be greatly improved now.
