### ISSUE TITLE
add bittorrent download for ISOs on website

### ISSUE THREAD

**Issue by mfc** [QubesOS/qubes-issues#1245]
In order to provide more download options for users, as well as allow users to download ISOs faster, in low/intermittent bandwidth environments, with light verification, and reduce strain on our servers, we should provide bittorrent options for users to download the ISOs (and whatever else we think should be included in the torrent, like signed checksums #1077).

open trackers to use:
udp://tracker.torrent.eu.org:451 (used by Tails)
udp://tracker.coppersurfer.tk:6969 (used by Tails)
udp://tracker.openbittorrent.com:80 (used by burnbit)

references:
Tails: https://tails.boum.org/download/index.en.html
Whonix: https://www.whonix.org/wiki/VirtualBox#Download_Whonix

**Comment by marmarek** [comment]
There is already burnbit link at the bottom of downloads page. Not an
ideal, but at least something :)

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by mfc** [comment]
looking at the burnbit .torrent file, they are just using the openbittorrent.com tracker:

udp://tracker.openbittorrent.com:80

There is no need for the .torrent file itself to be hosted on a third-party site like burnbit, it should be hosted on ftp.qubes-os.org and kernel.org, downloaded over HTTPS etc. 

We just make the torrent with a couple of open bittorrent trackers (since we have no need to host our own), and make sure there is at least one dedicated seed. We've already found three open bittorrent trackers that seem dependable so we can go with those for redundancy purposes.

**Comment by axon-qubes** [comment]
> reduce strain on our servers

This is less of a concern now that our ISOs are mirrored on `mirrors.kernel.org`, but of course it's also nice to have torrents available.

**Comment by mfc** [comment]
sure agreed. It is mostly for the other reasons that I think it is important from a usability point of view (for users with low/intermittent connections, want faster downloads, & light verification)

**Comment by axon-qubes** [comment]
So, what needs to be done to complete this ticket? @mfc, do you have links that I can add to the Downloads page? Or is the real issue that we want someone to create and seed the torrents? (If so, I think the `doc` label is inaccurate.)

**Comment by mfc** [comment]
> Or is the real issue that we want someone to create and seed the torrents?

yes, this. ideally during the process of uploading a new ISO to ftp and kernel, we would create a torrent with the ISO and signature file, including the following open trackers for redundancy:
- udp://tracker.torrent.eu.org:451
- udp://tracker.coppersurfer.tk:6969 
- udp://tracker.openbittorrent.com:80 

and host that torrent file on ftp and kernel.

**Comment by marmarek** [comment]
Regarding seeding - burnbit.com uses HTTP for seeding, so as long as the
file is hosted somewhere, the torrent is also seeded. At least they
claims so :)

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by marmarek** [comment]
Done

**Comment by mfc** [comment]
you are a hero Marek.
