### ISSUE TITLE
draft/create new page for Qubes Partners

### ISSUE THREAD

**Issue by mfc** [QubesOS/qubes-issues#1247]
similar to Debian: https://www.debian.org/partners/

program details: https://www.debian.org/partners/partners

something to highlight orgs, companies, individuals who contribute greatly to Qubes. Also as a way to encourage others to contribute.

**Comment by axon-qubes** [comment]
Nice idea. Initial version is up here: https://www.qubes-os.org/partners/

However, it's not linked anywhere yet. I want to see what @rootkovska thinks before linking it anywhere.

**Comment by rootkovska** [comment]
I worry that if we wanted to recognize all the upstream projects whose code we use this might easily become a way too long a list, and I see problems where to draw a line (e.g. shall we just say: Xen, Linux kernel, and all the rest of the GNU, or start mentioning each and every package's owning project we ever use in any of the templates or Dom0?)

I think Michael's intention was more to recognize organizations and individuals who have _specifically_ supported Qubes OS by either:

1. Investing own time and energy to contribute  (sending patches, writing docs, doing evangelism, testing, etc),
2. Donating funds to the project in one way or another (e.g. OTF by signing contracts, organizations that declared to provide monthly payments -- there are already a few such orgs interested!, etc).

**Comment by axon-qubes** [comment]
> I worry that if we wanted to recognize all the upstream projects whose code we use this might easily become a way too long a list, and I see problems where to draw a line (e.g. shall we just say: Xen, Linux kernel, and all the rest of the GNU, or start mentioning each and every package's owning project we ever use in any of the templates or Dom0?)

Good point.

> I think Michael's intention was more to recognize organizations and individuals who have specifically supported Qubes OS by either:
>
> 1. Investing own time and energy to contribute (sending patches, writing docs, doing evangelism, testing, etc),
>
> 2. Donating funds to the project in one way or another (e.g. OTF by signing contracts, organizations that declared to provide monthly payments -- there are already a few such orgs interested!, etc).

But then we already have [a page for that](https://www.qubes-os.org/people/), don't we? (Unless the point is that we should include not just *people* but also *orgs*, which sounds reasonable to me.)

**Comment by mfc** [comment]
Yes I was meaning more in terms of organizations, like the Debian partners page. Basically as a way to encourage such institutional support, and provide a location where we can provide thanks to them.

Initially, it would maybe have Open Technology Fund.

**Comment by axon-qubes** [comment]
So, should we just change the **People** page into **People and Organizations**? Does anyone have a pithy term we can use to replace `/people/`?

**Comment by axon-qubes** [comment]
Maybe `/contributors/`?

**Comment by mfc** [comment]
I think they are two different things -- one is the folks who are working on Qubes, the other is organizations (and people) who donate money, hardware, bandwidth to the Qubes effort.

> Does anyone have a pithy term we can use to replace `/people/`?

Yes we should use `/team/` instead. This was @bvnk's suggestion re: improving how we communicate Qubes and I think it's a good one.

**Comment by axon-qubes** [comment]
But would it really be accurate to say, "The Open Technology Fund is part of the Qubes team"?

**Comment by mfc** [comment]
this is two unrelated topics:
* renaming People --> Team
* creating a Partners page following https://www.debian.org/partners/ and https://www.debian.org/partners/partners

**Comment by axon-qubes** [comment]
Based on our comments above, I thought the rationale for renaming `/people/` to `/team/` was because we were going to list both people *and* organizations on the same page, and continuing to call that page `/people/` would therefore be inaccurate (since it would also include organizations, which aren't people).

Now you're saying that these two topics are unrelated. If that's the case, then what's the rationale for renaming `/people/` to `/team/`?

**Comment by mfc** [comment]
Given that we are a distributed FOSS project, it is nice to publicly project and identify ourselves as a team working for a collective purpose rather than a random collection of people/contributors. we're all interacting remotely so we get enough of that feeling already :)

if you want we can wait for @bnvk's redesign/branding of the website, I just figured it would be an easy tweak to implement.

**Comment by rootkovska** [comment]
Also: let's not discriminate others than humans from contributing to the project, shall we? ;)

**Comment by axon-qubes** [comment]
Ah, but I would never assume that only humans can be people! :)

**Comment by axon-qubes** [comment]
The page has now been updated according to the comments in this thread. Since the original ticket title is just to "draft/create" such a page, I've closed this ticket. However, I don't claim that the page, as it currently stands, contains all the content we might desire. Edits and improvements to the page are very much welcome.
