### ISSUE TITLE
Sys-net and firewall stay 'yellow' after bootup; No systray or notifications

### ISSUE THREAD

**Issue by ttasket** [QubesOS/qubes-issues#1250]
When booting into Qubes 3rc3 the initially started VMs (usually sys-net and sys-firewall) stay in a state that is disconnected from the UI. As a result, the user is blocked from the systray apps and status messages from these VMs.

It is conceivable that VMs which are chosen to start at boot time may attempt to present critical messages or functions for the user.

A workaround is to use 'Run command in VM' context menu function to manually run some program in each of the semi-disconnected VMs to bring them to the 'green' state.

**Comment by marmarek** [comment]
Do you have `sys-firewall` set as a default netvm? Or have you changed that default? By default login prompt is displayed only after default netvm (and its "parent" VMs) are fully operational.

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-dom0-3.1.8-1.fc20` has been pushed to the `r3.1` testing repository for dom0.
To test this update, please install it with the following command:
```
sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-admin/compare/ff63c5030daa025809d4d0dd82596d9f58a16111...ba0d60595eab2e348d296d20840e6d366c160d3b

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-dom0-3.1.10-1.fc20` has been pushed to the `r3.1` stable repository for dom0.
To install this update, please use the standard update command:
```
sudo qubes-dom0-update
```
Or update dom0 via Qubes Manager.

[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-admin/compare/36134c8c43c0ff8dd45d9cd29d0f4b0539352c18...46a338d0879410debda8e3e073024fefe87a4704

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-dom0-3.0.27-1.fc20` has been pushed to the `r3.0` testing repository for dom0.
To test this update, please install it with the following command:
```
sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-admin/compare/444d602d88cc7e079a550ff8da18901fac472781...b25c3f05c7c93e397cd2639e533c089bf5e140fb

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-dom0-3.0.28-1.fc20` has been pushed to the `r3.0` stable repository for dom0.
To install this update, please use the standard update command:
```
sudo qubes-dom0-update
```
Or update dom0 via Qubes Manager.

[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-admin/compare/444d602d88cc7e079a550ff8da18901fac472781...d29c2889b0744d57c51ce9b14d87a411c3d84dfa
