### ISSUE TITLE
R3 higher CPU/power usage at idle

### ISSUE THREAD

**Issue by tasket** [QubesOS/qubes-issues#1253]
The system appears to be using significantly more CPU cycles at idle under Qubes R3rc3 than it did under R2. In R3, xentop reports about 15% dom0 CPU usage at system idle with 7 domUs loaded, and about 8% CPU with zero domUs. This activity does not show up in Qubes Manager CPU meter for dom0.

In R2, xentop does not report dom0 cpu usage. However, top run under both R3 and R2 does show a difference (IIRC) about 5-8% less under R2.

The system fan also runs more and the laptop itself is noticeably warmer than it usually was when running R2.

**Comment by marmarek** [comment]
Try close qubes manager window - updating CPU and memory graphs uses
non-negligible CPU power...

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by ttasket** [comment]
I will try. However, that would indicate a change for the worse in Qubes Manager: It was running and open on both R2 and R3.

I also have a test installation of R2 still available. If you prefer, I can collect data for comparisons or diagnostics (so far I've just got some screenshots of xentop and top). If there is a way to make xentop report dom0 stats in R2 that could help.

**Comment by marmarek** [comment]
As for dom0 in R2 `xentop`, try this:
```
UUID=c6c60319-2338-499f-bd60-39e55d6deebb
xenstore-write /vm/$UUID/name dom0
xenstore-write /local/domain/0/vm /vm/$UUID
```
(UUID is arbitrary, you can generate new one)

**Comment by marmarek** [comment]
Also take a look at [this comment](https://github.com/QubesOS/qubes-issues/issues/1288#issuecomment-146708986)

**Comment by marmarek** [comment]
One more thing - currently in R3 Qubes Manager doesn't report CPU stats for dom0 at all. #1302

**Comment by andrewdavidwong** [comment]
@tasket: Are you still experiencing this problem?

**Comment by tasket** [comment]
@andrewdavidwong In a general way, no.. it appears to be gone. However, there is a high idle issue with pulse audio when I've had firefox or rhythmbox using audio recently (even while audio is not playing). If I exit the firefox or rhythmbox that was playing audio, the CPU usage subsides. BTW I have not enabled low-latency audio mode.

Also, Manager is using about 2.5% CPU--not much--while pulse in dom0 uses 7-12% at idle.

I don't know if my earlier impression that led me to create this issue had anything to do with audio, but I think its possible.

**Comment by andrewdavidwong** [comment]
Ok, I think that merits closing this one, then.
