### ISSUE TITLE
Copying files taking insanely long between VMs and/or USB devices

### ISSUE THREAD

**Issue by bnvk** [QubesOS/qubes-issues#1257]
I'm noticing that copying files is taking sometimes insanely long periods. Like 30+ mins to copy 7 MB from my `usbdata` VM to a USB device. The status bar says it's copying at  `1.7kB / sec` which seems quite odd for a plugged in device. This seems to happens more when the data is a large number of small files. In this case, the 7 MB is made up of 2000+ files.

Any thoughts on why this is happening @marmarek ? Is this a bug or something I can offer more info about / help to debug?

**Comment by marmarek** [comment]
On Thu, Oct 01, 2015 at 03:44:35AM -0700, Brennan Novak wrote:
> I'm noticing that copying files is taking sometimes insanely long periods. Like 30+ mins to copy 7 MB from my `usbdata` VM to a USB device. The status bar says it's copying at  `1.7kB / sec` which seems quite odd for a plugged in device. This seems to happens more when the data is a large number of small files. In this case, the 7 MB is made up of 2000+ files.
> 
> Any thoughts on why this is happening @marmarek ? Is this a bug or something I can offer more info about / help to debug?

Try first copy the files off the USB device to some directory in the
same VM. I guess it's more about USB performance, not the file copy
mechanism. Maybe this particular USB stick is dying?

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by bnvk** [comment]
Sorry. I miscommunicated. The case above, the data was actually
copying files to the USB device not from, so data was at AppVM
usbdata and moving to ---> USB Media.

I've also noticed significantly slow transfer times (not as bad
as 1.7kB, but still quite) when copying data between two AppVMs
when there are lots of small files which are not quite large in
size!

**Comment by marmarek** [comment]
Receiving VM [calls `fdatasync` for each file](https://github.com/QubesOS/qubes-linux-utils/blob/master/qrexec-lib/unpack.c#L140), this takes some time...

**Comment by bnvk** [comment]
Interesting. Yah, it seemed to be highly correlate when copying
lots of small files! I wonder if we'd get any noticeable
performance increase by doing something like zipping or rarring
the files before peforming the fdatasync operation if the number
of files being moved is over a certain threshold. What do you
think @marmarek?

**Comment by marmarek** [comment]
I'm considering removing that line at all. Just need to evaluate if
there would be no downsides.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?
