### ISSUE TITLE
qmemman: rework dbus interaction

### ISSUE THREAD

**Issue by woju** [QubesOS/qubes-issues#1263]
When domain refuses to give back memory, qmemman marks that domain as
insubordinate and sends dbus notification to qubes-manager. This should be done
the other way: qmemman should send broadcast and anyone should be able to listen
to them.

**Comment by woju** [comment]
This issue is abandoned, so I'm going to close it. If that's a mistake, feel free to reopen.
@marmarek @andrewdavidwong

**Comment by marmarek** [comment]
I'd add an explanation - dbus in qmemman is gone, and should stay this way.
