### ISSUE TITLE
Typos on the Homepage and in Google Group

### ISSUE THREAD

**Issue by ShalokShalom** [QubesOS/qubes-issues#1265]
Hi there :)

This is an awesome project, just discovered it right now, love it already :D 

There are two little typos: https://www.qubes-os.org/intro/
crtl + f for "seaparation"

https://groups.google.com/forum/#!msg/qubes-users/IQdCEpkooto/iyMh3LuzCAAJ
crtl + f for "sitck"

**Comment by axon-qubes** [comment]
Got the the one in `intro.md`. Thanks!

**Comment by axon-qubes** [comment]
The Google Groups messages are actually emails, so they can't really be edited after the fact. (Editing the message in Google Groups won't change the local copy I have in my inbox, for example.) So it's not really worth worrying about those, IMO.
