### ISSUE TITLE
Support more VM types in qvm-grow-root

### ISSUE THREAD

**Issue by nihilifer** [QubesOS/qubes-issues#1268]
Currently qvm-grow-root can resize root.img for:
- template HVM-s
- HVM-s with are not template-based

And it's done by truncating of root.img. [1]

It's possible to support more VM types:
- template VM-s
- standalone VM-s

by truncating (on Dom0) and running resize2fs (on template/standalone VM).

The things above are described in documentation, but it would be nice to do them automatically in qvm-grow-root.

[1] https://github.com/QubesOS/qubes-core-admin/blob/master/core-modules/01QubesHVm.py#L252

**Comment by nihilifer** [comment]
I cannot assign myself, but I would like to work on it.

**Comment by marmarek** [comment]
On Sun, Oct 04, 2015 at 07:41:11AM -0700, Michal Rostecki wrote:
> I cannot assign myself, but I would like to work on it.

Great! I'd be happy to accept a patch here :)

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by marmarek** [comment]
Additionally I think it worth making it clear that VM would be started - this may be unexpected. Something like qvm-grow-root --allow-start, and without that option, it would refuse operation when VM startup is required. Or some other interface, but I would rather avoid interactive prompt.

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-dom0-3.1.8-1.fc20` has been pushed to the `r3.1` testing repository for dom0.
To test this update, please install it with the following command:
```
sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-admin/compare/ff63c5030daa025809d4d0dd82596d9f58a16111...ba0d60595eab2e348d296d20840e6d366c160d3b

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-dom0-3.1.10-1.fc20` has been pushed to the `r3.1` stable repository for dom0.
To install this update, please use the standard update command:
```
sudo qubes-dom0-update
```
Or update dom0 via Qubes Manager.

[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-admin/compare/36134c8c43c0ff8dd45d9cd29d0f4b0539352c18...46a338d0879410debda8e3e073024fefe87a4704
