### ISSUE TITLE
Qubes OS Project

### ISSUE THREAD

**Issue by lizsisteryy** [QubesOS/qubes-issues#1275]
Is Qubes OS Project compatible with Windows 10  or more for Windows 7?

**Comment by woju** [comment]
On Mon, Oct 05, 2015 at 07:19:43AM -0700, lizsisteryy wrote:
> Is Qubes OS Project compatible with Windows 10  or more for Windows 7?

Hi and welcome,

This kind of questions should be asked at our mailing list:
qubes-users@googlegroups.com.

BTW, the answer is „yes” for windows 7 and „not yet” for windows 10.
