### ISSUE TITLE
Create exception hierarchy

### ISSUE THREAD

**Issue by woju** [QubesOS/qubes-issues#1279]
There are two kinds of errors: programmer's errors and user/API errors. Current
`QubesException` is the second kind. Programming errors should not result in
raising `QubesException`, but standard python exceptions and end in tool's crash
and possibly log message.

Children of `QubesException` may also inherit from children of `StandardError`
(that is, from vanilla python exceptions like `KeyError`, `ValueError` etc.), so
we can write readable `try`/`except` statements. In this case we should inherit
from QubesException first.

The `AssertionError` standard exception is tricky, because when this error is
catched by testsuite the test result is `FAIL` instead of `ERROR`. Perhaps
`QubesVMError` can inherit from it.

Proposed hierarchy:

- `QubesException` (root; has nice description to display to user)
  - `QubesVMNotFoundError` (+`LookupError` or `KeyError`; vm cannot be found
    when looking up by qid, uuid or name)
  - `QubesVMError` (+`AssertionError`?; some problem with machine or its state;
    first param is the domain in question)
    - `QubesVMNotRunningError` (not active)
    - `QubesVMNotStartedError`
    - `QubesVMNotHaltedError`
    - `QubesVMNotPausedError`
    - `QubesVMNotSuspendedError`
  - `QubesValueError` (+`ValueError`; wrong value while setting property)
  - `QubesNotImplementedError` (+`NotImplementedError`)
  - `BackupCancelledError`
  - `QubesMemoryError` (+`MemoryError`; cannot start domain)
  - `QubesNoTemplateError` (template not found, like after incomplete backup)
  - `QubesStoreError` (problem with `qubes.xml`: not found, syntax error, etc.)

**Comment by marmarek** [comment]
On Tue, Oct 06, 2015 at 03:53:54AM -0700, Wojtek Porczyk wrote:
> - `QubesException` (root; has nice description to display to user)
>   - `QubesVMNotFoundError` (+`LookupError` or `KeyError`; vm cannot be found
>     when looking up by qid, uuid or name)
>   - `QubesVMError` (+`AssertionError`?; some problem with machine or its state;
>     first param is the domain in question)
>     - `QubesVMNotRunningError` (not active)
>     - `QubesVMNotStartedError`

What is the difference?

>     - `QubesVMNotHaltedError`
>     - `QubesVMNotPausedError`
>     - `QubesVMNotSuspendedError`
>   - `QubesValueError` (+`ValueError`; wrong value while setting property)

`QubesPropertyValueError` ?

>   - `QubesNotImplementedError` (+`NotImplementedError`)
>   - `BackupCancelledError`
>   - `QubesMemoryError` (+`MemoryError`; cannot start domain)
>   - `QubesNoTemplateError` (template not found, like after incomplete backup)

May also cover incompatible template case (for example trying to create
HVM based on PV template). Or should it be `QubesPropertyValueError`?

>   - `QubesStoreError` (problem with `qubes.xml`: not found, syntax error, etc.)

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by woju** [comment]
On Tue, Oct 06, 2015 at 04:18:07AM -0700, Marek Marczykowski-Górecki wrote:
> >     - `QubesVMNotRunningError` (not active)
> >     - `QubesVMNotStartedError`
> 
> What is the difference?

Paused state. For example `.force_shutdown()` should work when machine
is started but paused, but `.run()` requires machine that is running and
not paused. Both should fail when domain is powered off.

Perhaps `QubesVMNotRunningError` may be a child of
`QubesVMNotStartedError`.

> >     - `QubesVMNotHaltedError`
> >     - `QubesVMNotPausedError`
> >     - `QubesVMNotSuspendedError`
> >   - `QubesValueError` (+`ValueError`; wrong value while setting property)
> 
> `QubesPropertyValueError` ?

Dunno. Do we have other places, where we check values?

> >   - `QubesNoTemplateError` (template not found, like after incomplete backup)
> 
> May also cover incompatible template case (for example trying to create
> HVM based on PV template). Or should it be `QubesPropertyValueError`?

`*ValueError`. `QubesNoTemplateError` will be raised when attempting to
start the domain.


-- 
regards,                        _.-._
Wojtek Porczyk               .-^'   '^-.
Invisible Things Lab         |'-.-^-.-'|
                             |  |   |  |
 I do not fear computers,    |  '-.-'  |
 I fear lack of them.        '-._ :  ,-'
    -- Isaac Asimov             `^-^-_>

**Comment by woju** [comment]
Or even `TypeError`.

**Comment by marmarek** [comment]
On Tue, Oct 06, 2015 at 04:43:38AM -0700, Wojtek Porczyk wrote:
> On Tue, Oct 06, 2015 at 04:18:07AM -0700, Marek Marczykowski-Górecki wrote:
> > >     - `QubesVMNotRunningError` (not active)
> > >     - `QubesVMNotStartedError`
> > 
> > What is the difference?
> 
> Paused state. For example `.force_shutdown()` should work when machine
> is started but paused, but `.run()` requires machine that is running and
> not paused. Both should fail when domain is powered off.
> 
> Perhaps `QubesVMNotRunningError` may be a child of
> `QubesVMNotStartedError`.

+1

> > >     - `QubesVMNotHaltedError`
> > >     - `QubesVMNotPausedError`
> > >     - `QubesVMNotSuspendedError`
> > >   - `QubesValueError` (+`ValueError`; wrong value while setting property)
> > 
> > `QubesPropertyValueError` ?
> 
> Dunno. Do we have other places, where we check values?

Not sure. Maybe better keep `QubesValueError` and ensure appropriate
message (containing word "property").

> Or even `TypeError`.

`QubesTypeError`? Child of `QubesValueError`?

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?
