### ISSUE TITLE
SplitGPG fails if VM containing the key is not running

### ISSUE THREAD

**Issue by qjoo** [QubesOS/qubes-issues#1283]
Expected behavior: GPG key containing VM is started on demand (R2 behavior)

If the VM is already running everything works fine.

This is on R3.0 with the default F21 template.

Traceback ("manual" copy paste :)

```
Rpc allowed: mail gpg-key qubes.Gpg
Traceback
 File /usr/lib/qubes/qrexec-policy, line 226
 File /usr/lib/qubes/qrexec-policy, line 221
  do_execute(domain, target, user, service_name, process_ident)
 File /usr/lib/qubes/qrexec-policy, line 123, in do_execute
  spawn_target_if_necessary(target)>
 File /usr/lib/qubes/qrexec-policy, line 109, in spawn_target_if_necessary
  if is_domain_running(target):
 File /usr/lib/qubes/qrexec-policy, line 88, in is_domain_running
    libvirt_dom = vmm.libvirt_conn.lookupByName(target)
 File /usr/lib64/python2.7/site-packages/libvirt.py line 3964 in lookupByName
   if ret is None:raise libvirtError('virDomainLookupByName() failed', conn=self)
libvirt.libvirtError: Domain not found 
```

**Comment by axon-qubes** [comment]
I'm experiencing this too.

**Comment by axon-qubes** [comment]
Actually, I think this is some kind of "first-run" issue, because now my GPG backend VMs are autostarting on-demand.

**Comment by marmarek** [comment]
On Wed, Oct 07, 2015 at 03:13:11AM -0700, Axon wrote:
> Actually, I think this is some kind of "first-run" issue, because now my GPG backend VMs are autostarting on-demand.

Yes, looks like it. But still it is a bug.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?
