### ISSUE TITLE
R3.0: xterm doesn't launch from the menu in minimal VMs

### ISSUE THREAD

**Issue by axon-qubes** [QubesOS/qubes-issues#1285]
Attempting to launch `xterm` in `fedora-21-minimal` (or any AppVM based on it) from the KDE menu results in the cursor animating for a while and nothing else happening. This is the command the menu is trying to use:

    qvm-run -q --tray -a fedora-21-minimal -- 'qubes-desktop-run /usr/share/applications/xterm.desktop'

Substituting this command works instantly:

    qvm-run -q --tray -a fedora-21minimal -- 'xterm'

Users might try to fix this themselves but substituting the non-working command for the working command, but the menu commands get regenerated quite often, overwriting user changes.

(Note: The same problem has happened [before](https://groups.google.com/forum/#!topic/qubes-users/cApLwBh2UE0/discussion), but in *that* case the cause was the missing `pygobject3-base` package. That package is now included in `fedora-21-minimal` by default, so something else must be the culprit this time. Same problem; different cause.)

**Comment by marmarek** [comment]
Would I surprise you that this is also fixed in current-testing
repository?

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?
