### ISSUE TITLE
R3.0: TorVM: Set up private data directory correctly

### ISSUE THREAD

**Issue by axon-qubes** [QubesOS/qubes-issues#1287]
Following the documentation to set up a TorVM in R3.0 does not work, because the private data directory is missing. The user also has to do this (or something with an equivalent effect):

    [user@torvm] $ sudo mkdir /rw/usrlocal/lib/qubes-tor
    [user@torvm] $ sudo chown user:user /rw/usrlocal/lib/qubes-tor

I've already [added](https://github.com/QubesOS/qubes-doc/commit/d4e41ddace71e4f61f24ffd41bef5f4ea434a1c0) [this](https://github.com/QubesOS/qubes-doc/commit/70d3037c8c12718adbbe33331d51c5617a47f90a) to the documentation, but ISTM that this should be done automatically by the scripts, if possible. (I recall seeing some error messages suggesting that there were permissions issues.)

**Comment by marmarek** [comment]
I can't reproduce it. Just installed `qubes-tor` package in fresh R3.0 install, in default `fedora-21` template and it simply works.
And indeed the [directory is created](https://github.com/QubesOS/qubes-app-linux-tor/blob/master/start_tor_proxy.sh#L137-L140).
What version of `qubes-tor` package do you have? Have you called `start_tor_proxy.sh` script manually instead of `qubes-tor` service? Some other template? (but I can't think of any case where `mkdir` doesn't work on some template...)

**Comment by unman** [comment]
Also confirmed working in debian templates without need for manual intervention.
As side note, should permissions not be that of TOR_USER rather than user?

**Comment by axon-qubes** [comment]
> I can't reproduce it. Just installed qubes-tor package in fresh R3.0 install, in default fedora-21 template and it simply works. And indeed the directory is created.

This was in a clone of `fedora-21-minimal`. Maybe that's why.

> What version of qubes-tor package do you have?

```
bash-4.3# yum info qubes-tor
Loaded plugins: post-transaction-actions, yum-qubes-hooks
Installed Packages
Name        : qubes-tor
Arch        : x86_64
Version     : 0.1.11
Release     : 1.fc21
Size        : 16 k
Repo        : installed
From repo   : qubes-vm-r3.0-current
Summary     : The Qubes package for running a TorVM
URL         : http://www.qubes-os.org
License     : GPL
Description : A tor distribution for Qubes OS
```
Is this the version I should have?

> Have you called start_tor_proxy.sh script manually instead of qubes-tor service?

Nope. Just followed the instructions in `/doc/TorVM/`.

> Some other template? (but I can't think of any case where mkdir doesn't work on some template...)

Yes. As mentioned above, `fedora-21-minimal` instead of `fedora-21`.

**Comment by axon-qubes** [comment]
> As side note, should permissions not be that of TOR_USER rather than user?

I noticed that if I `chown user:user`, then the directory automatically gets `chown`ed to `toranon:toranon` the next time the VM is restarted. That's why I added the parenthetical note "(or something with an equivalent effect)."

**Comment by marmarek** [comment]
I can confirm the issue on fedora-21-minimal template. Trying to find
out why...

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by marmarek** [comment]
Ok, on fedora-21-minimal template `qubes-tor` service is started before
`/rw` is mounted.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by marmarek** [comment]
Fix uploaded to current-testing repository
