### ISSUE TITLE
R3.0: qubes-tor requires frequent restarts

### ISSUE THREAD

**Issue by axon-qubes** [QubesOS/qubes-issues#1298]
I'm not exactly sure what the problem is, but I've noticed that, compared to R2, torvm in R3.0 is rather unreliable. Even if the torvm is already running and `sudo service qubes-tor restart` shows that everything is fine, starting a new AppVM which uses the torvm as its netvm will result in that AppVM having no Tor access. After manually restarting `qubes-tor` (`sudo service qubes-tor restart` in the torvm), the AppVM has Tor access.

**Comment by marmarek** [comment]
Are you using standard or minimal template here?

**Comment by marmarek** [comment]
I can't reproduce it with fedora-21-minmal template. There is a bug in [udev rule](https://github.com/QubesOS/qubes-app-linux-tor/blob/master/99-qubes-tor-hook.rules#L1) - missing `restart` word, but this only means that the service will not be automatically restarted when new AppVM is connected. 
Do you remember why it was there? As said before - even without that restart (the broken one), newly connected AppVMs are working fine for me.

Can you compare iptables (`filter` and `nat` tables) and routing table when such access is broken and after `qubes-tor` service restart?

**Comment by axon-qubes** [comment]
Hm, I haven't been able to reproduce it anymore either. Feel free to close. I'll comment here again if I can find some useful info to share.
