### ISSUE TITLE
Dom0 loop devices sometimes fail to detach when AppVM is shut down

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#1301]
If you follow the instructions [here](https://www.qubes-os.org/doc/SecondaryStorage/) for storing some AppVMs on a secondary drive, then some loop devices will get attached to dom0 (displayed in `qvm-block`) when the AppVM is started. They're supposed to automatically be detached when the AppVM is shut down, but sometimes they don't, and this can cause problems such as the AppVM not being able to be started again. (Attempting to manually detach them using `qvm-block -d` usually doesn't work either.)

**Comment by marmarek** [comment]
Check if you have any errors about it in `/var/log/xen/xen-hotplug.log`

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by axon-qubes** [comment]
The log is empty, but I'll check again if/when it happens again.

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
