### ISSUE TITLE
DispVMs not starting from AppVMs

### ISSUE THREAD

**Issue by axon-qubes** [QubesOS/qubes-issues#1303]
Starting a DispVM directly (from KDE menu) works fine.

Trying to start a DispVM from another AppVM (e.g., right click file -> open in DispVM) results in a dom0 notification ("Starting new DispVM..."), but one never appears.

Already tried: checked RPC rules and regenerated DVM template.

**Comment by marmarek** [comment]
Check `/var/log/qubes/qrexec.VMNAME.log` of calling VM.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by axon-qubes** [comment]
```
Rpc allowed: untrusted dom0 qubes.NotifyUpdates
eintr
Rpc allowed: untrusted $dispvm qubes.OpenInVM
time=1444346638.28, qfile-daemon-dvm init
time=1444346638.28, creating DispVM
time=1444346638.32, collection loaded
time=1444346638.32, VM created
time=1444346639.03, VM starting
time=1444346639.03, creating config file
time=1444346639.03, getting 419430400 memory
time=1444346639.38, calling restore
time=1444346640.86, done
time=1444346640.88, done qubesdb
time=1444346640.88, resumed
time=1444346641.79, qrexec done
time=1444346642.6, guid done
Traceback (most recent call last):
  File "/usr/lib/qubes/qfile-daemon-dvm", line 182, in <module>
    main()
  File "/usr/lib/qubes/qfile-daemon-dvm", line 173, in main
    dispvm = qfile.get_dvm()
  File "/usr/lib/qubes/qfile-daemon-dvm", line 145, in get_dvm
    return self.do_get_dvm()
  File "/usr/lib/qubes/qfile-daemon-dvm", line 106, in do_get_dvm
    dispvm.netvm = vm.dispvm_netvm
  File "/usr/lib64/python2.7/site-packages/qubes/modules/000QubesVm.py", line 428, in netvm
    self._set_netvm(new_netvm)
  File "/usr/lib64/python2.7/site-packages/qubes/modules/000QubesVm.py", line 443, in _set_netvm
    self.detach_network()
  File "/usr/lib64/python2.7/site-packages/qubes/modules/000QubesVm.py", line 1651, in detach_network
    self.mac, self.netvm.name))
  File "/usr/lib64/python2.7/site-packages/libvirt.py", line 1095, in detachDevice
    if ret == -1: raise libvirtError ('virDomainDetachDevice() failed', dom=self)
libvirt.libvirtError: internal error: libxenlight failed to detach network device
eintr

```

**Comment by marmarek** [comment]
Ouch, #975. Try setting netvm to none on DispVM template.
But that would probably affect DispVMs started from the menu...

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by axon-qubes** [comment]
> Ouch, #975. Try setting netvm to none on DispVM template.

Yep, that fixed it.

> But that would probably affect DispVMs started from the menu...

Yes, looks like I'll have to decide which functionality I want more for now. :)

**Comment by marmarek** [comment]
Ok, so this is (another) issue caused by #975 . I've already raised its priority.
