### ISSUE TITLE
[doc] passwordless sudo

### ISSUE THREAD

**Issue by iuriguilherme** [QubesOS/qubes-issues#1304]
On the [page](https://www.qubes-os.org/doc/VMSudo/) which explains why there is no sudo password, at first there is an explanation in the format of question and answer, made in a theoretical sudoers file's comments.

I think it would be clearer to the reader which paragraphs are questions and which are answers if they are distinctive by introducing two hashes (\#) instead of one on the beginning of a line with question.

**Comment by axon-qubes** [comment]
> On the page which explains why there is no sudo password, at first there is an explanation in the format of question and answer, made in a theoretical sudoers file's comments.

Not theoretical, but [actual](https://github.com/QubesOS/qubes-core-agent-linux/blob/master/misc/qubes.sudoers).

But I'm not sure I see the problem. Isn't it only the first line which is a (rather obviously rhetorical) question?

Perhaps you could provide a version of the text with extra #'s where you'd put them?

**Comment by axon-qubes** [comment]
Also, note that this is not just a doc issue, because presumably we would want any clarificatory edits to appear in the actual sudoers file, as well.

**Comment by iuriguilherme** [comment]
> Isn't it only the first line which is a (rather obviously rhetorical) question?

Indeed, after re-reading the text twice, I've came to the same conclusion.

It just *looks like* one of my own texts, but after a couple of reads it seems to get the point across and should stay untouched.

The original topic is misleading.
