### ISSUE TITLE
Re:Wrong screen resolution (64x64) set for AppVM X server when xrandr unavailable on Dom0 side

### ISSUE THREAD

**Issue by plushambush** [QubesOS/qubes-issues#1305]
It turns out that Issue #998 is not solved (tested on R3.0)
The fix assumes that AppVM gets proper initial screen size upon start and doesn't need further layout updates. But this assumption is wrong because `QubesVM.start_guid()` method used for initial screen size setup calls the same `get_monitor_layout()` function which misbehaves (returns nothing) when XrandR is unavailable:
See file /usr/lib64/python2.7/site-packages/qubes/modules/000QubesVm.py line 1680 (in `start_guid()` method:
```
            monitor_layout = qubes.monitorlayoutnotify.get_monitor_layout()
            qubes.monitorlayoutnotify.notify_vm(self,monitor_layout)
```
As a result:
After AppVM started on a host with XrandR unavailable its screen dimensions are initially set wrong (64x64):
```
user@Work:~$ xrandr -q
Screen 0: minimum 64 x 64, current 64 x 64, maximum 32767 x 32767
DUMMY0 connected
   QB4240x1050   47.45 +
DUMMY1 disconnected
DUMMY2 disconnected
DUMMY3 disconnected
```
One has to issue a manual screen setup command inside AppVM  to fix this:
```
user@Work:~$ echo "4240 1050 0 0" | sh /etc/qubes-rpc/qubes.SetMonitorLayout
```
After that screen resolution becomes OK
```
user@Work:~$ xrandr -q
Screen 0: minimum 64 x 64, current 4240 x 1050, maximum 32767 x 32767
DUMMY0 connected 4240x1050+0+0 0mm x 0mm
   QB4240x1050   47.45*+
DUMMY1 disconnected
DUMMY2 disconnected
DUMMY3 disconnected
```

**Comment by marmarek** [comment]
Do you know any way to disable xrandr in dom0, preferably without X server restart? I'd like add a test for such case...

**Comment by plushambush** [comment]
I don't know and I don't think it's possible without restarting X server.
May be a stub script returning "RandR extension missing" instead of proper data can help in this?

**Comment by plushambush** [comment]
BTW `qubes-guid` in `send_xconf()` uses `XGetWindowAttributes()` to get root screen resolution and it works ok.

**Comment by plushambush** [comment]
Ok found a way to fix it. Making a patch
