### ISSUE TITLE
Limit dom0 memory to 4GB

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#1313]
Apparently Linux kernel reserves some internal memory structures based on maximum memory, not the actual one. This is waste of resources, especially on big systems, because normally most of memory is assigned to AppVMs.
This is also along the lines of [Xen best practices](http://wiki.xen.org/wiki/Xen_Best_Practices).

Related to #1136

**Comment by qubesuser** [comment]
Sounds good, although in addition to 4GB, 8GB and 16GB also seem reasonable candidates for the value to use.

Longer term, it would be nice to get memory hotplugging working for both dom0 and VMs in a way that results in not wasting memory for page structures for unassigned RAM and ballooning instantly, and then maybe remove the dom0 limit again, but I'm not sure if that's feasible.

**Comment by marmarek** [comment]
On Sat, Oct 10, 2015 at 02:30:08PM -0700, qubesuser wrote:
> Sounds good, although in addition to 4GB, 8GB and 16GB also seem reasonable candidates for the value to use.

The point is you don't need too much memory in dom0 - all the user
applications are running in VMs. Dom0 is only for running X server,
window manager and some management scripts. In the future we'll split
even that (X server) to a separate GUI domain, so dom0 will be even
smaller.

> Longer term, it would be nice to get memory hotplugging working for both dom0 and VMs in a way that results in not wasting memory for page structures for unassigned RAM and ballooning instantly, and then maybe remove the dom0 limit again, but I'm not sure if that's feasible.

I think this would be mostly useful for VMs. BTW currently because of
this overhead maxmem cannot be bigger than initial mem (aka "memory")
times 10:
https://github.com/QubesOS/qubes-core-admin/commit/bf2173073bc7b9d9212c42f06424f415fea2882f

So if we get the memory hot plugging working, we probably could get rid
of that limit.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by Atrate** [comment]
On this topic, in 2024: does `dom0` support memory balancing/hotplugging/balooning/whatever? That is, if I set the dom0 max mem to e.g. 32G to improve IO latency through better caching, if AppVMs need it would memory be taken from dom0?

**Comment by marmarek** [comment]
Yes, but there is a cost to that - while actual memory pages can get reallocated, metadata about them cannot. It's about 4KiB per 1MiB of memory. So, with 32GiB maxmem, that is ballooned down to 4GiB you effectively lose over 100MiB.

**Comment by Atrate** [comment]
In that case, on high-memory systems (32+GiB) would it not make sense to set dom0 usage to 100% system memory by default? 100MiB per 32GiB seems like a small price to pay with a large memory budget and I feel like there would be enormous gains from such a significant increase in buffer/cache sizes, as a lot of Qubes functionality, epsecially DVM-related, is I/O bound.

I may be misunderstanding something, though, related issue:  #9610

**Comment by marmarek** [comment]
Not really, ballooning down takes time, so setting high maxmem for dom0 will slow down VM startup quite a bit. But there is even worse side effect - frequent ballooning result in memory fragmentation, which has very real impact on performance (basically makes CPU cache much less effective, some people report fragmentation makes _everything_ slower by factor of 2 or more). In fact, the latter is the reason why some recommend setting dom0 to a completely static size. It isn't done in qubes to support also smaller systems, but maybe installer should do that if there is enough memory...

**Comment by Atrate** [comment]
Yeah, that makes sense. I also *just* tested setting dom0 maxmem to unrestricted and I've run into performance issues where `xen-balloon` just runs between 50-100% core usage constantly, sizing dom0 up and down by a couple hundred MiB at a time.
