### ISSUE TITLE
Since a few days ago, ~/bin is no longer in $PATH on my VMs (#3)​

### ISSUE THREAD

**Issue by Rudd-O** [QubesOS/qubes-issues#1316]
For some reason after R3.0 upgrade, this begun to happen.  The bug was deleted so I don't remember the text I had written (I'm refiling the bug).

**Comment by marmarek** [comment]
Original bug report:
```
I updated a few days ago, to R3.0, and my VMs are no longer loading
~/.bash_profile within their "graphical session", which causes the
gnome-terminal windows not to have ~/bin in their PATH variable.
```

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?
