### ISSUE TITLE
qvm-shutdown poorly handles large numbers of VMs

### ISSUE THREAD

**Issue by axon-qubes** [QubesOS/qubes-issues#1320]
Attempting to use `qvm-shutdown` on a large number of VMs  (~40) results in many VMs being unnecessarily killed.

I can think of two options:
1. Increase the time before killing when `qvm-shutdown` is invoked on a large number of VMs.
2. Divide the total number of VMs-to-be-shutdown into smaller batches, then serially `qvm-shutdown` each batch.

**Comment by axon-qubes** [comment]
If the above options would be too much, how about a `--wait-time` option that lets the user specify the amount of time to wait in seconds?

So, if I know I'm shutting down an unusually large number of VMs, I could just do this:

    qvm-shutdown --all --wait --wait-time=300

Then go drink a cup of tea.

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-dom0-3.1.8-1.fc20` has been pushed to the `r3.1` testing repository for dom0.
To test this update, please install it with the following command:
```
sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-admin/compare/ff63c5030daa025809d4d0dd82596d9f58a16111...ba0d60595eab2e348d296d20840e6d366c160d3b

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-dom0-3.1.10-1.fc20` has been pushed to the `r3.1` stable repository for dom0.
To install this update, please use the standard update command:
```
sudo qubes-dom0-update
```
Or update dom0 via Qubes Manager.

[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-admin/compare/36134c8c43c0ff8dd45d9cd29d0f4b0539352c18...46a338d0879410debda8e3e073024fefe87a4704

**Comment by axon-qubes** [comment]
The new option works great, but thankfully it's not even necessary anymore, since VMs shut down much faster now. Thanks, @marmarek! :)
