### ISSUE TITLE
mechanism to hide Qubes VM Manager 'Firewall rules' tab

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#1323]
As discussed in [Qubes VM Manger Firewall tab settings design](https://groups.google.com/forum/#!topic/qubes-devel/uzgN42uEJpE).

In some VMs (Whonix, any others?) the '[Firewall rules' tab](https://www.qubes-os.org/attachment/wiki/QubesFirewall/r2b1-manager-firewall.png) in Qubes VM Manager should not be shown, because it's unimplemented / unnecessary / dysfunctional.

Quote @marmarek:

> Maybe we should introduce some mechanism which will disable firewall tab
> when it has no effect (= used ProxyVM have no `qubes-firewall` service
> enabled). If we disable `qubes-firewall` service using Services tab in
> Whonix Gw (probably in addition to that drop-in), this could be detected
> by Qubes Manager. Perhaps worth doing it as part of idea in "Timezone and
> other deanonymizing data in QubesDB"[1] thread (service called from
> template to set configure template properties). Need some more though
> how to do this right.
> 
> [1] https://groups.google.com/d/msgid/qubes-devel/20150923202203.GY2791%40mail-itl

**Comment by marmarta** [comment]
Enabled in 4.0 - "Firewall" tab in VM Settings emits a warning when qubes-firewall service in the appropriate net VM is not enabled.
