### ISSUE TITLE
[doc] Git repository not present on Arch Linux page

### ISSUE THREAD

**Issue by desci** [QubesOS/qubes-issues#1330]
This [page](https://www.qubes-os.org/en/doc/building-archlinux-template/) yells *"Prefer marmarek git repository as it is the most recent one"*, although it does not provide the URL to the github repository aforementioned.

**Comment by axon-qubes** [comment]
@marmarek, can you provide the correct URI for that repo?

**Comment by marmarek** [comment]
Sure: https://github.com/marmarek/qubes-builder-archlinux

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?
