### ISSUE TITLE
Decide how to handle doc/website language translations

### ISSUE THREAD

**Issue by axon-qubes** [QubesOS/qubes-issues#1333]
This issue continues the conversation from comments on #1205. There are two main places where languages might be represented:

 * URLs
 * Source files

Given that the website is currently in English, there are several available approaches to differentiating pages/sites in other languages in URLs:

 * Use subdomains for any new site translations (i.e., all non-English languages):
    * `https://www.qubes-os.org/` (unchanged canonical English version)
    * `https://pl.qubes-os.org/` (new Polish translation)
    * `https://de.qubes-os.org/` (new German translation)
 * Use subdomains for **all** languages:
    * `https://www.qubes-os.org/` --> `https://en.qubes-os.org/`
    * `https://pl.qubes-os.org/`
    * `https://de.qubes-os.org/`
 * Use subdirectories for any new page translations:
    * `https://www.qubes-os.org/intro/` (unchanged canonical English version)
    * `https://www.qubes-os.org/pl/intro/` (new Polish translation)
    * `https://www.qubes-os.org/de/intro/` (new German translation)
 * Use subdirectories for **all** languages:
    * `https://www.qubes-os.org/intro/` --> `https://www.qubes-os.org/en/intro/`
    * `https://www.qubes-os.org/pl/intro/`
    * `https://www.qubes-os.org/de/intro/`

Likewise, there are several possible ways to differentiate source files in different languages:

 * Use subdirectories for any new source file translations:
    * `_doc/basics/intro.md` (unchanged canonical English version)
    * `_doc/pl/basics/intro.md` (new Polish translation)
    * `_doc/de/basics/intro.md` (new German translation)
      * (Sorry, I don't know the Polish or German words for "basics" and "intro" :P )
 * Use subdirectories for **all** languages:
    * `_doc/basics/intro.md` --> `_doc/en/basics/intro.md`
    * `_doc/pl/basics/intro.md`
    * `_doc/de/basics/intro.md`
 * Use filename language codes for any new source file translations:
    * `_doc/basics/intro.md` (unchanged canonical English version)
    * `_doc/basics/intro.pl.md` (new Polish translation)
    * `_doc/basics/intro.de.md` (new German translation)
 * Use filename language coes for **all** languages:
    * `_doc/basics/intro.md` --> `_doc/basics/intro.en.md`
    * `_doc/basics/intro.pl.md`
    * `_doc/basics/intro.de.md`

Factors which might influence the decision:

 * The number of other languages likely to see translations
 * The types of content likely to be translated
 * The amount of content likely to be translated
 * The likelihood of translations being kept up-to-date or falling out of sync with the canonical English versions
 * The risk of (inadvertant or intentional) misinformation via faulty translation (and subsequent likelihood of detection by the community)
 * The number of actual and potential users for given languages

**Comment by axon-qubes** [comment]
If no one voices any objections in the next week, I'll default to the following scheme:

 * Use subdirectories for any new page translations:
   *  `https://www.qubes-os.org/intro/` (unchanged canonical English version)
   *  `https://www.qubes-os.org/pl/intro/` (new Polish translation)
   *  `https://www.qubes-os.org/de/intro/` (new German translation)
 * Use filename language codes for any new source file translations:
   *  `_doc/basics/intro.md` (unchanged canonical English version)
   *  `_doc/basics/intro.pl.md` (new Polish translation)
   *  `_doc/basics/intro.de.md` (new German translation)

**Comment by mfc** [comment]
can we explore implementing this? there are a couple of full translations for spanish now: 
https://www.transifex.com/otf/qubes/language/es/

this is less a priority than changing the markdown conventions in #1452.

**Comment by andrewdavidwong** [comment]
> can we explore implementing this? there are a couple of full translations for spanish now:
https://www.transifex.com/otf/qubes/language/es/
> 
> this is less a priority than changing the markdown conventions in #1452.

@mfc: I've created #2652 for this.

**Comment by andrewdavidwong** [comment]
> If no one voices any objections in the next week, I'll default to the following scheme:
> - Use subdirectories for any new page translations:
>   -  `https://www.qubes-os.org/intro/` (unchanged canonical English version)
>   -  `https://www.qubes-os.org/pl/intro/` (new Polish translation)
>   -  `https://www.qubes-os.org/de/intro/` (new German translation)
> - Use filename language codes for any new source file translations:
>   -  `_doc/basics/intro.md` (unchanged canonical English version)
>   -  `_doc/basics/intro.pl.md` (new Polish translation)
>   -  `_doc/basics/intro.de.md` (new German translation)
> 

Based on internal discussions, we've decided to put all translated files in a separate, untrusted repo (i.e., no signed commits or tags). The main reason is that we can't evaluate content in languages that we can't read, and we don't want to sign content that we haven't evaluated (also see #2652).

This won't affect the URL/subdirectory scheme outlined above, but it may affect the naming scheme for source files. For example, we may just want to retain the same (canonical English) source file name for every language.
