### ISSUE TITLE
manual DispVM startup fails if its configured ProxyVM is not yet started

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#1334]
Qubes Q3.

DispVM was set to whonix-ws. Its proxyvm was sys-whonix. When sys-whonix is running the following command just works normal. But when sys-whonix is shut down while running the following commend, the attached error message will be shown.

```
echo konsole | /usr/lib/qubes/qfile-daemon-dvm qubes.VMShell dom0 DEFAULT red
```
```
time=1444637075.0, qfile-daemon-dvm init
time=1444637075.0, creating DispVM
time=1444637075.02, collection loaded
time=1444637075.08, VM created
time=1444637075.08, VM starting
time=1444637075.08, creating config file
time=1444637075.08, getting 445644800 memory
time=1444637075.18, calling restore
Traceback (most recent call last):
  File "/usr/lib/qubes/qfile-daemon-dvm", line 182, in <module>
    main()
  File "/usr/lib/qubes/qfile-daemon-dvm", line 173, in main
    dispvm = qfile.get_dvm()
  File "/usr/lib/qubes/qfile-daemon-dvm", line 145, in get_dvm
    return self.do_get_dvm()
  File "/usr/lib/qubes/qfile-daemon-dvm", line 102, in do_get_dvm
    dispvm.start()
  File "/usr/lib64/python2.7/site-packages/qubes/modules/01QubesDisposableVm.py", line 193, in start
    domain_config, libvirt.VIR_DOMAIN_SAVE_PAUSED)
  File "/usr/lib64/python2.7/site-packages/libvirt.py", line 4302, in restoreFlags
    if ret == -1: raise libvirtError ('virDomainRestoreFlags() failed', conn=self)
libvirt.libvirtError: internal error: libxenlight failed to restore domain 'disp21'
```

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-dom0-3.1.8-1.fc20` has been pushed to the `r3.1` testing repository for dom0.
To test this update, please install it with the following command:
```
sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-admin/compare/ff63c5030daa025809d4d0dd82596d9f58a16111...ba0d60595eab2e348d296d20840e6d366c160d3b

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-dom0-3.1.10-1.fc20` has been pushed to the `r3.1` stable repository for dom0.
To install this update, please use the standard update command:
```
sudo qubes-dom0-update
```
Or update dom0 via Qubes Manager.

[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-admin/compare/36134c8c43c0ff8dd45d9cd29d0f4b0539352c18...46a338d0879410debda8e3e073024fefe87a4704

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-dom0-3.0.27-1.fc20` has been pushed to the `r3.0` testing repository for dom0.
To test this update, please install it with the following command:
```
sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-admin/compare/444d602d88cc7e079a550ff8da18901fac472781...b25c3f05c7c93e397cd2639e533c089bf5e140fb

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-dom0-3.0.28-1.fc20` has been pushed to the `r3.0` stable repository for dom0.
To install this update, please use the standard update command:
```
sudo qubes-dom0-update
```
Or update dom0 via Qubes Manager.

[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-admin/compare/444d602d88cc7e079a550ff8da18901fac472781...d29c2889b0744d57c51ce9b14d87a411c3d84dfa
