### ISSUE TITLE
Restore VMs despite their NetVM 

### ISSUE THREAD

**Issue by anon11221** [QubesOS/qubes-issues#1337]
While attempting to restore my VMs,
I was unable to continue to restore VMs because their respected NetVMs weren't located on the system the VMs were being restored on.

On my Desktop, I'll keep my Whonix-gw and call them one thing,
and on my laptop, I'll call them something else.

It's a real hassle to choose (none) on every VM I want to back, every single time.
If there can be a bypass option, that'd be awesome!
Another feature that would be nice, is if we were able to use qvm-backup and exclude multiple VMs. I'd love to make my own script that backups all my VMs upon insertion of a USB.
Thank you!

**Comment by marmarek** [comment]
There is such option. If you use Qubes Manager to restore, it is called "ignore missing". In command line tool - `qvm-backup-restore --ignore-missing`.
This option will allow you to restore VMs even if its original netvm and/or template is missing. The VM will use default setting for missing entry.
