### ISSUE TITLE
document TemplateBasedHVM domains

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#1341]
https://www.qubes-os.org/doc/hvm-create/#tocAnchor-1-1-5

> Using Template-based HVM domains
> 
> TODO (Coming in Qubes R2 beta 3).

**Comment by axon-qubes** [comment]
I don't have much experience with using TemplateBasedHVM domains, so it would be best if someone else contributed this documentation.

**Comment by adrelanos** [comment]
I don't think there is anything special to know about TemplateBasedHVM. They're similar to other TemplateVMs. Just for HVM.

It's already documented here:
https://www.qubes-os.org/doc/windows-appvms/#tocAnchor-1-1-5

**Comment by axon-qubes** [comment]
So, we just need to generalize that section (i.e., make it not Windows-specific)?

**Comment by adrelanos** [comment]
Yes.

**Comment by axon-qubes** [comment]
Are you willing to do that, then?

**Comment by Jeeppler** [comment]
I used Winodws 7 HVM template domains for some time to save disk space (each windows takes between 20-50 GB of disk space). The problem is, they are relatively unstable. In addition it takes more time to boot up a Windows HVM template based VM, than a normal standalone VM.
