### ISSUE TITLE
Tails does not boot in Qubes HVM

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#1343]
I've downloaded Tails 1.6. Stored in my iso-download (debian-8 based) AppVM. Then followed the https://www.qubes-os.org/en/doc/hvm-create/ instructions.

Initially Tails boots. You can see the Tails boot menu. Whatever you choose, the default option or failsafe, same result. Where it hangs is a black screen only showing `_`.

It doesn't bother me personally too much. It's very low on my wishlist. So is this worth of being reported? I am just wondering if there could be a more general underlying issue that would be worth fixing.

**Comment by marmarek** [comment]
I *guess* it's about ancient qemu we have in stub domain. Unfortunately
newer version (aka "qemu upstream") requires major stub domain rework,
which hadn't been done yet (but was planned since AFAIR Xen 4.4). Eric
Shelton tried to encourage Xen people to work on it, also providing some
help there. But as for today, Xen 4.6 still doesn't support qemu
upstream in stub domain.

Anyway this problem probably can be fixed by Tails by some Xorg
configuration (or adding another driver). Not sure if worth reporting,
what is the Tails statement about using it in VM?

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by adrelanos** [comment]
> what is the Tails statement about using it in VM?

https://tails.boum.org/doc/advanced_topics/virtualization/index.de.html

**Comment by unman** [comment]
@adrelanos 
Explicitly setting vga mode at boot should fix this.
Try appending vga=792

**Comment by adrelanos** [comment]
That workaround works.

**Comment by adrelanos** [comment]
Booted with smaller resolution, `vga=788`. But that workaround still leaves one with an unusable Tails. It boots up until the graphical target just fine. The problem is, that the bottom side of the window reaches below dom0's taskbar. So for example the "ok" button in Tails launcher outside the visible monitor area.

**Comment by adrelanos** [comment]
Existing general Qubes OS ticket at Tails redmine tracker,
`Try running Tails inside of Qubes OS`:
https://labs.riseup.net/code/issues/8607

Reported this issue on the tails-dev mailing list,
`[Tails-dev] Tails fails to run inside Qubes OS`:
https://mailman.boum.org/pipermail/tails-dev/2015-October/009628.html

**Comment by marmarek** [comment]
Not sure how to classify this? Should we have some documentation "how to run Tails in Qubes HVM"?

**Comment by DrWhax** [comment]
I was just trying this out! What a coincidence! On my R3.0 with the vga=788 option, I just get a blank screen and nothing happens. This was with a Tails 1.8.1 release.

Ideally, we should test out the 2.0 beta release that is next on my list of things to do. Hopefully things have improved on Debian Jessie's side, it's slightly more positive from what I understand from the tails-dev mailinglist.

But yes, if we figure out what works with what version, we should create documentation for it!

**Comment by adrelanos** [comment]
Documenting it isn't possible as no one has figured out yet how to get
it into a usable state.

As per what you wrote in
https://github.com/QubesOS/qubes-issues/issues/1343#issuecomment-148958062
it's a Xen issue. One you probably won't have priority/time to fix. Not
sure what's best to do with such kind of tickets. It's an outstanding
issue, good to know, not really fixed, good if found through search
engines. I would leave it open with "patches welcome". Or close it if
that works better with your issue tracker customs.

**Comment by adrelanos** [comment]
Seems like @DrWhax and me posted in the exact same minute. This somewhat obsoletes my previous post. Since someone is working on it, perhaps best to leave it open.

**Comment by DrWhax** [comment]
Well, both the beta of 2.0 and a latest stable release (1.8.1) both don't load, all I get is a black screen. Fiddling with the vga line doesn't do anything to circumvent the issue. I guess we should document that it doesn't work? :)

**Comment by austin987** [comment]
@marmarek / @adrelanos what Xen issue? What Xorg driver is needed? Tails is based on Debian, if it's only a missing driver this should be trivial to fix on Tails' end.

**Comment by adrelanos** [comment]
https://github.com/QubesOS/qubes-issues/issues/1343#issuecomment-148958062

**Comment by austin987** [comment]
Yes, I saw that. I was hoping for a Xen bug # or link, and/or the name of the missing Xorg driver, if known.

**Comment by DrWhax** [comment]
Indeed, this would allow us to build an iso and test again. Any pointer is welcome.

**Comment by marmarek** [comment]
Does Tails use "quiet" kernel boot option? If so, remove and see kernel
messages. Or maybe it fails at X server load time? Having some way to
extract X server log would be useful...

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by DrWhax** [comment]
I just did this with an Tails 2.0~beta1 iso and I get this:

"Probing EDD (edd=off to disable) OK" and then it just hangs.

**Comment by austin987** [comment]
@marmarek, yes, it's quiet by default.

I've never used Qubes myself (on my list of things to try soon), is https://www.qubes-os.org/doc/live-usb/ still valid? That would make testing easier for me.

**Comment by adrelanos** [comment]
Austin English:
> I've never used Qubes myself (on my list of things to try soon), is https://www.qubes-os.org/doc/live-usb/ still valid? That would make testing easier for me.

Please don't hijack random tickets for unrelated discussion. No offense
intended. Just trying to keep the overview.

**Comment by mfc** [comment]
just to keep this thread updated, there is online documentation on running Tails in Qubes HVM now: https://garlicgambit.wordpress.com/2016/04/22/how-to-run-tails-from-a-qubes-live-cd and #1969.

**Comment by andrewdavidwong** [comment]
@unman (https://github.com/QubesOS/qubes-issues/issues/1969#issuecomment-218177725):
> I'm amazed #1343 is still open: it was only ever a display problem, for which I gave solution. It's not an issue now.

@adrelanos, @marmarek: Can we close this?

**Comment by adrelanos** [comment]
@DrWhax can you test and confirm please?

**Comment by mfc** [comment]
this ticket should shift towards documenting how to do it -- running Tails within an installed instance of Qubes will have slightly different (and shorter) documentation than garlicgambit's documentation, and is vastly more useful since Qubes Live USB is not maintained.

**Comment by adrelanos** [comment]
Since https://github.com/QubesOS/qubes-doc/pull/154 by @unman was merged, I guess this ticket can be closed.

(For the record: this does not give us amnesic / anti-forensics / Tails-like functionality in Qubes. That is #2024.)

**Comment by mfc** [comment]
great, closed.
