### ISSUE TITLE
Qrexec deadlock on large transfers in both directions simultaneusly

### ISSUE THREAD

**Issue by rootkovska** [QubesOS/qubes-issues#1347]
On a my mutt + Split GPG setup I can't seem to be able to send an encrypted email with any larger attachment (say ~2MB). I suspect some race condition problem in SplitGPG (or, less likely in qrexec).

To reproduce:

1. Create an uncompressable large file: `dd if=/dev/urandom of=blob.bin bs=1k count=2k`
2. Compose an email with the above file as an attachment.
3. Actually try to send the email. The send operation will not succeed.

FWIW, this is the relevant fragment of my mutt's SplitGPG config:
````
set pgp_encrypt_sign_command="pgpewrap qubes-gpg-client-wrapper --batch --textmode --armor --always-trust %?a?--encrypt-to %a? --encrypt --sign %?a?-u %a? -- -r %r -- %f | sed -e '2iCharset: UTF-8'"
````

**Comment by marmarek** [comment]
I guess it's qrexec fault:
https://github.com/QubesOS/qubes-core-agent-linux/blob/master/qrexec/qrexec-agent-data.c#L224:
```
 /* FIXME: use buffered write here to prevent deadlock */
```
I can reproduce it using Split GPG, but failed to write artificial test for it (at least for now).

**Comment by marmarek** [comment]
> but failed to write artificial test for it (at least for now).

Never mind, it was a typo...

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-vm-3.0.19-1.fc20` has been pushed to the `r3.0` testing repository for the Fedora `fc20` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.0-current-testing
```

[builder-github]: https://github.com/QubesOS/qubes-builder-github

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-vm-3.0.19-1.fc21` has been pushed to the `r3.0` testing repository for the Fedora `fc21` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.0-current-testing
```

[builder-github]: https://github.com/QubesOS/qubes-builder-github

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-agent_3.0.19-1+deb8u1` has been pushed to the `r3.0` testing repository for the Debian `jessie` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `jessie-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```

[builder-github]: https://github.com/QubesOS/qubes-builder-github

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-agent_3.0.19-1+deb7u1` has been pushed to the `r3.0` testing repository for the Debian `wheezy` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `wheezy-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```

[builder-github]: https://github.com/QubesOS/qubes-builder-github

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-vm-3.0.19-1.fc20` has been pushed to the `r3.0` stable repository for the Fedora `fc20` template.
To install this update, please use the standard update command:
```
sudo yum update
```

[builder-github]: https://github.com/QubesOS/qubes-builder-github

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-vm-3.0.19-1.fc21` has been pushed to the `r3.0` stable repository for the Fedora `fc21` template.
To install this update, please use the standard update command:
```
sudo yum update
```

[builder-github]: https://github.com/QubesOS/qubes-builder-github

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-agent_3.0.19-1+deb8u1` has been pushed to the `r3.0` stable repository for the Debian `jessie` template.
To install this update, please use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/f7fa61e0b34ec36b689c4b8fb1e157e96c8cce37...45d9f78ebc885dd4095cfa66a43637a9d0726d68

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-agent_3.0.19-1+deb7u1` has been pushed to the `r3.0` stable repository for the Debian `wheezy` template.
To install this update, please use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/f7fa61e0b34ec36b689c4b8fb1e157e96c8cce37...45d9f78ebc885dd4095cfa66a43637a9d0726d68
