### ISSUE TITLE
Adding AppMenu for installed template (via RPM) in KDE

### ISSUE THREAD

**Issue by maxzinkus** [QubesOS/qubes-issues#1349]
There may be some related issues (in both Open and Closed) but I failed to find a duplicate.

When I run `sudo qubes-dom0-update qubes-template-debian-8` to install the Debian 8 template, the install goes off without a hitch and I can spawn AppVMs off of the template.

However, no AppMenu is created for debian-8 and as such I'd have to `qvm-run -a` every time I want to edit something. This isn't a big deal, but it's less sugary than most of the Dom0 interfaces.

One workaround is to make the AppMenu by hand. This works just fine, but again the enhancement would be awesome.

Thanks!

**Comment by marmarek** [comment]
Did you get any error during package installation?
You can also manually trigger appmenus regeneration:
```
qvm-start debian-8
qvm-sync-appmenus debian-8
```

**Comment by DeltaHeavy** [comment]
No errors, the install seemed to go just fine.

I have used both of those to interface with debian-8 however syncing the
appmenus didn't generate a KDE application launcher menu item (possibly due
to old KDE files in dom0 from other attempts?).

Note: it all works normally through the qubes installer for a fresh install.

Thanks!

**Comment by DeltaHeavy** [comment]
As an addition to this (although I can open it in a separate issue if it's more helpful)
`sudo yum remove qubes-template-debian-8` should also have AppMenu hooks to delete the AppMenu and relevant files in dom0. Currently, doing so leaves the template's AppMenu untouched.

**Comment by marmarek** [comment]
Did you get any errors while removing the template package?

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by DeltaHeavy** [comment]
I did not, it went smoothly.

**Comment by DeltaHeavy** [comment]
Any updates on this issue?

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
