### ISSUE TITLE
Substitute mentions of "ITL" in documentation 

### ISSUE THREAD

**Issue by bnvk** [QubesOS/qubes-issues#1358]
There are places in the Docs that reference ITL such as the [Templates plage](https://www.qubes-os.org/en/doc/templates/).

I think we should substitute these mentions with "Qubes" as Qubes is the piece of software users know they are interacting with + trusting, whereas ITL is an acronym and a bit confusing unless you know what it represents!

**Comment by bnvk** [comment]
Best to do this after #1202 is complete!

**Comment by andrewdavidwong** [comment]
This appear to be complete.
