### ISSUE TITLE
Backup should notice write errors in the AppVM

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#1359]
> I assumed the backup process would do an auto-split for usability on FAT filesystems; whichever process was actually writing the file didn't notice that write() was returning EFBIG. The backup process should do an initial sanity check for disk space and file-size limits, and of course it should notice all write errors.

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-dom0-3.0.27-1.fc20` has been pushed to the `r3.0` testing repository for dom0.
To test this update, please install it with the following command:
```
sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-admin/compare/444d602d88cc7e079a550ff8da18901fac472781...b25c3f05c7c93e397cd2639e533c089bf5e140fb

**Comment by unixninja92** [comment]
Still had issues with this in 3.0.

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-dom0-3.0.28-1.fc20` has been pushed to the `r3.0` stable repository for dom0.
To install this update, please use the standard update command:
```
sudo qubes-dom0-update
```
Or update dom0 via Qubes Manager.

[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-admin/compare/444d602d88cc7e079a550ff8da18901fac472781...d29c2889b0744d57c51ce9b14d87a411c3d84dfa
