### ISSUE TITLE
Qubes Manager crashes after permission error on icons

### ISSUE THREAD

**Issue by Scinawa** [QubesOS/qubes-issues#1360]
Hi,
I'll had persistent crashes of qubes-manager due to a permission denied error on a firefox icon.
Specifically, the path was /var/lib/qubes/appvms/fedora-21-dvm/apps.icons/something_firefox.ico

Maybe qubes manager does not have enough executable permission to stat the file, since I remember an ls -la gave me question mark for file permission (but listed all the icons flawlessly). I can't check anymore cause I removed the appvm.

Fix:
rm -rf /var/lib/qubes/appvms/fedora-21-dvm/apps.icons/*
without pity :)

**Comment by bnvk** [comment]
Hey @Scinawa this sounds quite similar to what I encountered in #1152 which was indeed permissions errors but was resolvable. However, there was a fix applied to what caused my permissions to get wonky.
Are you running Qubes 3.0 official release?

**Comment by Scinawa** [comment]
Yes I am. 
Indeed was the same bug, firefox icon on disposable-vm.
I didn't bother to fix permission cause i wanted to erase that vm. 
:)
