### ISSUE TITLE
make qubes-vm build error - /bin/bash: line 11: cd: qubes-src/linux-yum/current-release/..: No such file or directory

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#1365]
Building from `QubesOS/qubes-   Stable - Default Repo.`

`make qubes-vm`

```
/bin/bash: line 11: cd: qubes-src/linux-yum/current-release/..: No such file or directory
Makefile:712: recipe for target 'post-update-repo-template' failed
make[1]: *** [post-update-repo-template] Error 1
Makefile:279: recipe for target 'template-local-jessie+whonix-gateway+minimal+no-recommends' failed
make: *** [template-local-jessie+whonix-gateway+minimal+no-recommends] Error 1
```

**Comment by adrelanos** [comment]
Analysis needed or do you already know what this is?

Do you know a workaround for this one? (It's the last blocker before I am asking to create a Whonix 12 RC release.)

**Comment by marmarek** [comment]
Oops, sorry, forgot to push the fix.

**Comment by adrelanos** [comment]
The fix is in https://github.com/marmarek/qubes-builder but not in https://github.com/QubesOS/qubes-builder. Can you push to @QubesOS please or should I build from @marmarek?

**Comment by marmarek** [comment]
Pushed to @QubesOS.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by adrelanos** [comment]
Works for me. Thanks!
