### ISSUE TITLE
Grey-out "Add/remove app shortcuts for this VM" when hovering over dom0 in QVMM

### ISSUE THREAD

**Issue by DeltaHeavy** [QubesOS/qubes-issues#1367]
In the VM Manager, when you have a VM selected, certain toolbar options are "clickable" and colorized, for example if a VM has a firewallvm, the "Edit VM firewall rules" button is available.

When a dispvm is selected in the manager, the "Add/remove app shortcuts for this VM" greys out and becomes un-clickable.

This behaviour should occur when dom0 is selected as clicking it simply results in a directory not found exception popup window.

**Comment by DeltaHeavy** [comment]
Thanks Marek! You're the best.
On Dec 17, 2015 2:13 PM, "Marek Marczykowski-Górecki" <
notifications@github.com> wrote:

Closed #1367 <https://github.com/QubesOS/qubes-issues/issues/1367> via
marmarek/qubes-manager@1021d71
<https://github.com/marmarek/qubes-manager/commit/1021d718a720bb51da21a00ae44333ca730d13f0>
.

—
Reply to this email directly or view it on GitHub
<https://github.com/QubesOS/qubes-issues/issues/1367#event-495226947>.

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-manager-3.1.3-1.fc20` has been pushed to the `r3.1` testing repository for dom0.
To test this update, please install it with the following command:
```
sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-manager/compare/59d9a5326d1714b8c78b9ef6a003fdc9b76345cb...2547f3a6e2f1f5c7707fa83d654c912007842820

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-manager-3.0.13-1` has been pushed to the `r3.0` testing repository for dom0.
To test this update, please install it with the following command:
```
sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-manager/compare/582e8163bd1f93885a3cc8d4ed42aead4d99e3bb...05c9fc2041fcf42c395bfce76bf317ded0c63069

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-manager-3.0.13-1` has been pushed to the `r3.0` stable repository for dom0.
To install this update, please use the standard update command:
```
sudo qubes-dom0-update
```
Or update dom0 via Qubes Manager.

[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-manager/compare/582e8163bd1f93885a3cc8d4ed42aead4d99e3bb...05c9fc2041fcf42c395bfce76bf317ded0c63069

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-manager-3.1.3-1.fc20` has been pushed to the `r3.1` stable repository for dom0.
To install this update, please use the standard update command:
```
sudo qubes-dom0-update
```
Or update dom0 via Qubes Manager.

[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-manager/compare/59d9a5326d1714b8c78b9ef6a003fdc9b76345cb...2547f3a6e2f1f5c7707fa83d654c912007842820
