### ISSUE TITLE
Get rid of reboot prompt in Windows AppVMs with tools installed

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#1369]
[fteste](https://groups.google.com/d/msgid/qubes-users/K22gSNS----0%40tutamail.com):
> I have just instaled a win7template and created an appvm "win7apps". I am able to run in seamless mode but in the appvm windows always tell me that "in order to apply some changes I need to reboot" and then ask me if I want to reboot now or later.

> If I run the templatevm windows don't ask to reboot, is normal?

**Comment by ileyd** [comment]
Is this still an issue?

**Comment by omeg** [comment]
Not an issue anymore from what I can see. Such messages might result from creating a child AppVM before the template is ready (needs two reboots after QWT installation).
