### ISSUE TITLE
USB connected android phone does not show up as USB block device

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#1375]
Android has two settings:

* connected as camera
* connected as media device

-----

__connected as camera__

dom0 journalctl
```
Nov 04 12:55:34 dom0 kernel: usb 1-2: USB disconnect, device number 11
Nov 04 12:55:34 dom0 kernel: usb 1-2: new high-speed USB device number 12 using xhci_hcd
Nov 04 12:55:34 dom0 kernel: usb 1-2: New USB device found, idVendor=04e8, idProduct=6865
Nov 04 12:55:34 dom0 kernel: usb 1-2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
Nov 04 12:55:34 dom0 kernel: usb 1-2: Product: SAMSUNG_Android
Nov 04 12:55:34 dom0 kernel: usb 1-2: Manufacturer: SAMSUNG
Nov 04 12:55:34 dom0 kernel: usb 1-2: SerialNumber: 3ed09617
Nov 04 12:55:59 dom0 logger[16500]: /etc/xen/scripts/block-snapshot: remove XENBUS_PATH=backend/vbd/30/51712
Nov 04 12:55:59 dom0 logger[16521]: /etc/xen/scripts/block-snapshot: Device /dev/mapper/snapshot-fd02:29100454-fd02:29101166 still in use - not removing
Nov 04 12:56:25 dom0 PackageKit[15553]: daemon quit
```

dom0 `lsusb`
```
Bus 004 Device 002: ID 8087:8000 Intel Corp. 
Bus 004 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 003 Device 002: ID 8087:8008 Intel Corp. 
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 005: ID 8087:07dc Intel Corp. 
Bus 001 Device 008: ID 046d:c01e Logitech, Inc. MX518 Optical Mouse
Bus 001 Device 014: ID 04e8:6865 Samsung Electronics Co., Ltd GT-I9300 Phone [Galaxy S III] (PTP mode)
Bus 001 Device 006: ID 05e3:0608 Genesys Logic, Inc. Hub
Bus 001 Device 004: ID 046d:c31d Logitech, Inc. Media Keyboard K200
Bus 001 Device 002: ID 05e3:0608 Genesys Logic, Inc. Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```

-----

__connected as media device__

dom0 journalctl
```
Nov 04 12:57:15 dom0 kernel: usb 1-2: USB disconnect, device number 12
Nov 04 12:57:15 dom0 kernel: usb 1-2: new high-speed USB device number 13 using xhci_hcd
Nov 04 12:57:15 dom0 kernel: usb 1-2: New USB device found, idVendor=04e8, idProduct=6860
Nov 04 12:57:15 dom0 kernel: usb 1-2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
Nov 04 12:57:15 dom0 kernel: usb 1-2: Product: SAMSUNG_Android
Nov 04 12:57:15 dom0 kernel: usb 1-2: Manufacturer: SAMSUNG
Nov 04 12:57:15 dom0 kernel: usb 1-2: SerialNumber: 3ed09617
```

dom0 `lsusb`
```
Bus 004 Device 002: ID 8087:8000 Intel Corp. 
Bus 004 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 003 Device 002: ID 8087:8008 Intel Corp. 
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 005: ID 8087:07dc Intel Corp. 
Bus 001 Device 008: ID 046d:c01e Logitech, Inc. MX518 Optical Mouse
Bus 001 Device 013: ID 04e8:6860 Samsung Electronics Co., Ltd GT-I9100 Phone [Galaxy S II], GT-I9300 Phone [Galaxy S III], GT-P7500 [Galaxy Tab 10.1] , GT-I9500 [Galaxy S 4]
Bus 001 Device 006: ID 05e3:0608 Genesys Logic, Inc. Hub
Bus 001 Device 004: ID 046d:c31d Logitech, Inc. Media Keyboard K200
Bus 001 Device 002: ID 05e3:0608 Genesys Logic, Inc. Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub                                                                                               
```

-----

Either way, the USB connected android phone does not show up as USB block device in Qubes VM Manager (QVMM). (Therefore cannot be attached to AppVMs, therefore the phone storage cannot be accessed using Qubes.)

The device also shows not up in `gparted`. (Restarted between changing modes.)

**Comment by adrelanos** [comment]
`qvm-block -l` output is also empty.

**Comment by marmarek** [comment]
Maybe... it isn't a block device at all, but expose some fancy media
transfer interface like PTP? Check lsusb -v to see what interfaces are
there.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by unman** [comment]
Google switched to use MTP some time ago - you'll need simple-mtpfs installed and mtp libs.
My droid comes with a separate app for connecting media storage: much easier.
Not a Qubes issue.

**Comment by adrelanos** [comment]
Yes, only fancy.

- media device (MTP)
- camera (PTP)

-----

`lspci -v`
```
00:00.0 Host bridge: Intel Corporation Crystal Well DRAM Controller (rev 08)
        Subsystem: CLEVO/KAPOK Computer Device 7410
        Flags: bus master, fast devsel, latency 0
        Capabilities: <access denied>

00:02.0 VGA compatible controller: Intel Corporation Crystal Well Integrated Graphics Controller (rev 08) (prog-if 00 [VGA controller])
        Subsystem: CLEVO/KAPOK Computer Device 7410
        Flags: bus master, fast devsel, latency 0, IRQ 77
        Memory at f7800000 (64-bit, non-prefetchable) [size=4M]
        Memory at e0000000 (64-bit, prefetchable) [size=256M]
        I/O ports at f000 [size=64]
        Expansion ROM at <unassigned> [disabled]
        Capabilities: <access denied>
        Kernel driver in use: i915
        Kernel modules: i915

00:03.0 Audio device: Intel Corporation Crystal Well HD Audio Controller (rev 08)
        Subsystem: CLEVO/KAPOK Computer Device 7410
        Flags: bus master, fast devsel, latency 0, IRQ 80
        Memory at f7e34000 (64-bit, non-prefetchable) [size=16K]
        Capabilities: <access denied>
        Kernel driver in use: snd_hda_intel
        Kernel modules: snd_hda_intel

00:14.0 USB controller: Intel Corporation 8 Series/C220 Series Chipset Family USB xHCI (rev 05) (prog-if 30 [XHCI])
        Subsystem: CLEVO/KAPOK Computer Device 7410
        Flags: bus master, medium devsel, latency 0, IRQ 76
        Memory at f7e20000 (64-bit, non-prefetchable) [size=64K]
        Capabilities: <access denied>
        Kernel driver in use: xhci_hcd

00:16.0 Communication controller: Intel Corporation 8 Series/C220 Series Chipset Family MEI Controller #1 (rev 04)
        Subsystem: CLEVO/KAPOK Computer Device 7410
        Flags: bus master, fast devsel, latency 0, IRQ 78
        Memory at f7e3f000 (64-bit, non-prefetchable) [size=16]
        Capabilities: <access denied>
        Kernel driver in use: mei_me
        Kernel modules: mei_me

00:19.0 Ethernet controller: Intel Corporation Ethernet Connection I217-V (rev 05)
        Subsystem: CLEVO/KAPOK Computer Device 7410
        Flags: bus master, fast devsel, latency 0, IRQ 93
        Memory at f7e00000 (32-bit, non-prefetchable) [size=128K]
        Memory at f7e3d000 (32-bit, non-prefetchable) [size=4K]
        I/O ports at f080 [size=32]
        Capabilities: <access denied>
        Kernel driver in use: pciback
        Kernel modules: e1000e

00:1a.0 USB controller: Intel Corporation 8 Series/C220 Series Chipset Family USB EHCI #2 (rev 05) (prog-if 20 [EHCI])
        Subsystem: CLEVO/KAPOK Computer Device 7410
        Flags: bus master, medium devsel, latency 0, IRQ 16
        Memory at f7e3c000 (32-bit, non-prefetchable) [size=1K]
        Capabilities: <access denied>
        Kernel driver in use: ehci-pci

00:1b.0 Audio device: Intel Corporation 8 Series/C220 Series Chipset High Definition Audio Controller (rev 05)
        Subsystem: CLEVO/KAPOK Computer Device 7410
        Flags: bus master, fast devsel, latency 0, IRQ 81
        Memory at f7e30000 (64-bit, non-prefetchable) [size=16K]
        Capabilities: <access denied>
        Kernel driver in use: snd_hda_intel
        Kernel modules: snd_hda_intel

00:1c.0 PCI bridge: Intel Corporation 8 Series/C220 Series Chipset Family PCI Express Root Port #1 (rev d5) (prog-if 00 [Normal decode])
        Flags: bus master, fast devsel, latency 0, IRQ 16
        Bus: primary=00, secondary=01, subordinate=01, sec-latency=0
        Capabilities: <access denied>
        Kernel driver in use: pcieport
        Kernel modules: shpchp

00:1c.1 PCI bridge: Intel Corporation 8 Series/C220 Series Chipset Family PCI Express Root Port #2 (rev d5) (prog-if 00 [Normal decode])
        Flags: bus master, fast devsel, latency 0, IRQ 17
        Bus: primary=00, secondary=02, subordinate=02, sec-latency=0
        Memory behind bridge: f7d00000-f7dfffff
        Capabilities: <access denied>
        Kernel driver in use: pcieport
        Kernel modules: shpchp

00:1c.3 PCI bridge: Intel Corporation 8 Series/C220 Series Chipset Family PCI Express Root Port #4 (rev d5) (prog-if 00 [Normal decode])
        Flags: bus master, fast devsel, latency 0, IRQ 19
        Bus: primary=00, secondary=03, subordinate=03, sec-latency=0
        Memory behind bridge: f7c00000-f7cfffff
        Capabilities: <access denied>
        Kernel driver in use: pcieport
        Kernel modules: shpchp

00:1d.0 USB controller: Intel Corporation 8 Series/C220 Series Chipset Family USB EHCI #1 (rev 05) (prog-if 20 [EHCI])
        Subsystem: CLEVO/KAPOK Computer Device 7410
        Flags: bus master, medium devsel, latency 0, IRQ 23
        Memory at f7e3b000 (32-bit, non-prefetchable) [size=1K]
        Capabilities: <access denied>
        Kernel driver in use: ehci-pci

00:1f.0 ISA bridge: Intel Corporation HM87 Express LPC Controller (rev 05)
        Subsystem: CLEVO/KAPOK Computer Device 7410
        Flags: bus master, medium devsel, latency 0
        Capabilities: <access denied>
        Kernel driver in use: lpc_ich
        Kernel modules: lpc_ich

00:1f.2 SATA controller: Intel Corporation 8 Series/C220 Series Chipset Family 6-port SATA Controller 1 [AHCI mode] (rev 05) (prog-if 01 [AHCI 1.0])
        Subsystem: CLEVO/KAPOK Computer Device 7410
        Flags: bus master, 66MHz, medium devsel, latency 0, IRQ 75
        I/O ports at f0d0 [size=8]
        I/O ports at f0c0 [size=4]
        I/O ports at f0b0 [size=8]
        I/O ports at f0a0 [size=4]
        I/O ports at f060 [size=32]
        Memory at f7e3a000 (32-bit, non-prefetchable) [size=2K]
        Capabilities: <access denied>
        Kernel driver in use: ahci

00:1f.3 SMBus: Intel Corporation 8 Series/C220 Series Chipset Family SMBus Controller (rev 05)
        Subsystem: CLEVO/KAPOK Computer Device 7410
        Flags: medium devsel, IRQ 18
        Memory at f7e39000 (64-bit, non-prefetchable) [size=256]
        I/O ports at f040 [size=32]
        Kernel modules: i2c_i801

02:00.0 Unassigned class [ff00]: Realtek Semiconductor Co., Ltd. RTS5229 PCI Express Card Reader (rev 01)
        Subsystem: CLEVO/KAPOK Computer Device 7410
        Flags: bus master, fast devsel, latency 0, IRQ 79
        Memory at f7d00000 (32-bit, non-prefetchable) [size=4K]
        Capabilities: <access denied>
        Kernel driver in use: rtsx_pci
        Kernel modules: rtsx_pci

03:00.0 Network controller: Intel Corporation Wireless 3160 (rev 83)
        Subsystem: Intel Corporation Dual Band Wireless-AC 3160
        Flags: bus master, fast devsel, latency 0, IRQ 94
        Memory at f7c00000 (64-bit, non-prefetchable) [size=8K]
        Capabilities: <access denied>
        Kernel driver in use: pciback
        Kernel modules: iwlwifi
```

**Comment by adrelanos** [comment]
> Not a Qubes issue.

I think it is. On Debian systems last time I tried, the very same device worked out of the box. Not so on Qubes. So I think it's s usability issue.

> Google switched to use MTP some time ago - you'll need simple-mtpfs installed and mtp libs.

These would have to be installed in dom0? This might work as a workaround, but is this a good, secure solution, long term? If it was (rather unlikely, I guess...), then we should install these packages by default, no?

Perhaps #531 + #704 would be the proper fix for this ticket?

**Comment by unman** [comment]
>>    Not a Qubes issue.

> I think it is. On Debian systems last time I tried, the very same device worked out of the box. Not so on Qubes. So I think it's s usability issue.

It's a Linux issue, if anything.

Whether MTP would work on Debian would depend on what you had installed - I don't think a vanilla install includes those tools. Certainly a vanilla fedora doesn't.
Yes at the moment I believe that would have to be installed in dom0. I wouldnt favour installing by default, but there should be guidance for anyone who needs it until those other issues are done.

**Comment by marmarek** [comment]
In dom0 or USB VM if you have one. Anyway there is nothing Qubes
specific in accessing those devices.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by adrelanos** [comment]
What is the status of this? Should be closed as duplicate of #531 / #704? "invalid"? "needs research"? "needs documentation"?

**Comment by marmarek** [comment]
If you want to use the device in the AppVM, then yes - dup of #531. Otherwise (use the device in dom0 or USB VM directly), I don't see anything Qubes-specific here (even needing documentation) - standard usage of Android device.

**Comment by mfc** [comment]
> Whether MTP would work on Debian would depend on what you had installed - I don't think a vanilla install includes those tools. Certainly a vanilla fedora doesn't.
> Yes at the moment I believe that would have to be installed in dom0. I wouldnt favour installing by default, but there should be guidance for anyone who needs it until those other issues are done.

so it sounds like this needs to be documented since it is a common user issue, and that also MTP tools should be installed by default, since most users will think Qubes is breaking it vs just lacking packages?

**Comment by marmarek** [comment]
> MTP tools should be installed by default, since most users will think Qubes is breaking it vs just lacking packages?

We can't install everything by default. We already have problem with too big installation image.

**Comment by mfc** [comment]
I agree everything can't be installed by default. talking to phones is pretty basic tho, and because of usbvm etc 90% of users will think it is because Qubes is "too secure" or something.

maybe we can do a read-through of default installed apps with Patrick and find some that aren't required by default. if there is an easy link to that list I can check it out.

**Comment by marmarek** [comment]
Debian:
https://github.com/QubesOS/qubes-builder-debian/tree/master/template_debian (`packages_*.list` files)
in addition to Debian default list: https://github.com/QubesOS/qubes-builder-debian/blob/master/template_debian/02_install_groups.sh#L39-L48

Fedora:
https://github.com/QubesOS/qubes-builder-fedora/blob/master/template_scripts/packages_fc23.list
Also - most of the packages are just from Fedora default (`@workstation-product-environment` group)

**Comment by adrelanos** [comment]
Could we create standard Debian templates with Qubes-Builder flavor `no-recommends`? That would give tighter control about what packages get installed.

Dunno if that would save more than marginal space. Has also potential to introduce new issues. Method to minimize:

1) store the installed packages list of a recent Debian template
2) create a new Debian template with Qubes-Builder flavor `no-recommends`
3) create a installed packages list of that new template
4) compare these package lists

**Comment by Rudd-O** [comment]
Android phones stopped appearing as USB mass storage devices a LONG TIME AGO.  This was a policy decision at the Android project, as far as I am aware of.

**Comment by marmarek** [comment]
Original issue is unrelated to Qubes as Android phone is not a block device - closing

**Comment by nicoCalvo** [comment]
This issue is affecting anyone who wants to develop with react-native and using phone as testing devices. Please help me to know if there's a workaround or I should switch distro. Thank you.

**Comment by andrewdavidwong** [comment]
@nicoCalvo:
> This issue is affecting anyone who wants to develop with react-native and using phone as testing devices. Please help me to know if there's a workaround or I should switch distro. Thank you.

My understanding is that this issue is specifically about interacting with Android devices as _block_ devices, which turns out to be impossible because the Android project decided to stop presenting Android devices as block devices a long time ago. We have no control over this.

It's not clear that this particular issue (being specifically about block devices) is actually affecting the type of work you describe. For that, you might consider the workaround described here: https://github.com/QubesOS/qubes-issues/issues/2202#issuecomment-235937670

**Comment by nicoCalvo** [comment]
Thanks for your help. I realized that after mounting the phone with` qvm-usb `in dom0, I can see it if I run `adb devices`. The rest was problems with node but I got it running.
