### ISSUE TITLE
build Qubes-Whonix 12.0.0.3.0 RC templates

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#1376]
@marmarek can you try to build Qubes-Whonix please?

(both, gw and ws)

RC: If no grave bugs are released, after testing, that version can be blessed stable.

-----

PR:
https://github.com/marmarek/qubes-template-whonix/pull/4

----

For reference only:
https://github.com/QubesOS/qubes-issues/issues/1321

**Comment by adrelanos** [comment]
No need. Some more bugs to fix. Will reopen / or open a new issue.

**Comment by adrelanos** [comment]
Updated. Please build.

**Comment by marmarek** [comment]
Is it ok to have `DEBIAN_MIRRORS=http://ftp.pl.debian.org/debian/`, or should I change to something more generic?

**Comment by adrelanos** [comment]
Marek Marczykowski-Górecki:
> Is it ok to have `DEBIAN_MIRRORS=http://ftp.pl.debian.org/debian/`, or should I change to something more generic?

I don't think it matters.

**Comment by marmarek** [comment]
Build logs:
* [gateway](https://gist.github.com/e3457f97aaada37fa147)
* [workstation](https://gist.github.com/01a8ceaead9aeebe8e59)

Packages:
* qubes-template-whonix-gw-3.0.3-201511080152.noarch.rpm
* qubes-template-whonix-ws-3.0.3-201511080607.noarch.rpm

Now uploading to `qubes-dom0-unstable` repo. ETA 30min.

**Comment by adrelanos** [comment]
(If you want to test, you need to remove eventually installed Whonix templates first.)

```
sudo qubes-dom0-update --enablerepo=qubes-dom0-unstable qubes-template-whonix-gw qubes-template-whonix-ws
```

**Comment by adrelanos** [comment]
Thanks!
