### ISSUE TITLE
Window decorations intermittent

### ISSUE THREAD

**Issue by unman** [QubesOS/qubes-issues#1377]
Since the last update, I have noticed that window decorations no longer work properly all the time.
Symptoms are Name block appearing black, or remainder of title bar being black. Bringing window to front restores full coloured title bar.
This does not appear to affect all VMs, but where a VM is affected it seems that all child windows are affected.

**Comment by marmarek** [comment]
Does it looks like this: #1071  ?

**Comment by marmarek** [comment]
Also please specify what "last update" means. At least Qubes version...

**Comment by axon-qubes** [comment]
I'm assuming this issue has been resolved based on the lack of recent activity. If not, please feel free to re-open it.
