### ISSUE TITLE
Launch dom0 updates as qubes-dom0-update in terminal emulator

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#1378]
https://groups.google.com/d/msgid/qubes-users/8d6e68c0-5c25-42eb-a6c9-1627a08bb524%40googlegroups.com

> Since the GUI doesn't work as expected, could I respectfully recommend you
> eliminate the Apper all together.  It seems like it would be better to open
> a terminal running qubes-dom0-update, since users are used to this -- other
> VM updates are all done in a terminal window.

**Comment by axon-qubes** [comment]
FWIW, I use this in my own simple update script:

```
konsole --hold -e 'sudo qubes-dom0-update -y'
```

**Comment by unman** [comment]
@andrewdavidwong I believe this issue has not yet been resolved - please change milestone to 3.2 updates
