### ISSUE TITLE
nm-applet should not ask for WiFi passphrases all the time!

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#138]
**Reported by joanna on 25 Mar 2011 14:32 UTC**
And similarly it should not ask for the paraphrase to the user's keychain (or whatever it's called) each time. This is stupid, annoying, and has nothing to do with increasing security! The security theatre, as they call it. 

Migrated-From: https://wiki.qubes-os.org/ticket/138

**Comment by jbwells** [comment]
I'm not sure why this bug was closed because with R3.2-rc2 (with all updates) I get this inane dialog window popping up frequently to ask for a WPA key it already has.  Has it become unsolved since R1?
