### ISSUE TITLE
Follow symlinks when creating a backup 

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#1384]
https://groups.google.com/d/msgid/qubes-users/084d6750-bd02-426c-a966-60096ca53f17%40googlegroups.com
> One additional thing is that the restore does not follow symbolic links, so
.img files that were actually on different storage devices were not
included in the backup.  A warning message during the backup process, or
just following the link and backing up the file by following the symbolic
link would be nice.

**Comment by axon-qubes** [comment]
https://www.qubes-os.org/doc/secondary-storage/
