### ISSUE TITLE
qrexec docs look like a big mess

### ISSUE THREAD

**Issue by rootkovska** [QubesOS/qubes-issues#1392]
https://www.qubes-os.org/doc/qrexec3-implementation/
https://www.qubes-os.org/doc/qrexec2-implementation/
https://www.qubes-os.org/doc/qrexec3/
https://www.qubes-os.org/doc/qrexec/

Please fix. Also deprecate qrexec2 docs (potentially don't list in the main Content, only link from the qrexec3 docs pages). We really only need two qrexec-documenting pages: one for developers of qrexec-based services, and one for qrexec internals.

Also, please, please, make the pages look less ugly.

**Comment by axon-qubes** [comment]
@rootkovska, let me know what you think. (IMHO, it's cleaner just to have a single page for each one.)

**Comment by marmarek** [comment]
I'm not sure about having a single page with both qrexec app writers and qrexec-internals, but it may work with some clear separation of those parts.

Anyway the qrexec3 internals documentation sucks. At very least we need a similar diagram as in qrexec2 internals (of course updated to qrexec3 protocol). But the protocol description itself could use some rework. This is something I have in my TODO list for some time...

**Comment by axon-qubes** [comment]
I've made the separation of the internals section even more pronounced (by adjusting the heading levels), but it can easily be split off into a separate page if you prefer.

**Comment by axon-qubes** [comment]
@rootkovska, did you mean to leave this assigned to me when you reopened it? If so, what else would you like me to do?

**Comment by marmarek** [comment]
While at it: add info about #1876

**Comment by sstt011** [comment]
@marmarek You're assigned, what more needs to be done on this?

**Comment by andrewdavidwong** [comment]
@marmarek wrote in https://github.com/QubesOS/qubes-issues/issues/4583#issuecomment-445505561:
> But to fix #1392, I really need to create proper qrexec protocol specification, not only description of selected specific cases.

**Comment by marmarek** [comment]
This is now fixed thanks to @pierwill
