### ISSUE TITLE
Simplify "Houston we have a problem..." error popup

### ISSUE THREAD

**Issue by bnvk** [QubesOS/qubes-issues#1394]
I'm not sure if all the messages that show up in the modal with the title "Houston we have a problem" but the current one I experienced is just `VM already stopped` in this modal there is significant bit of uneeded / overwhelming text

![qubes-houston-problem-msg](https://cloud.githubusercontent.com/assets/48677/11023352/9be4a01e-8676-11e5-83e4-4b671dcb1009.png)

I prefer more simplified text like:

Title: **Houston we have a problem**

Main Message: **VM Already Stopped Running!**

Detail Message: *This is most likely a bug in Qubes Manager* 

Reasoning for this is: the main message is really what this is about. Currently a user has read a title + a whole sentence, then know how to mentally parse out the cryptic `QubesException:` preface, to read what the message is really about `VM Already stopped!` and the details of that message are already in the "Show Details" expand window.

I'd be happy to edit the file where this exists myself and submit a pull req if someone can point me to where it is :)

**Comment by marmarek** [comment]
It's here:
https://github.com/QubesOS/qubes-manager/blob/master/qubesmanager/main.py#L1982-L2016
