### ISSUE TITLE
whonix-ws testing template missing gtk2-engines-pixbuf package

### ISSUE THREAD

**Issue by qubesuser** [QubesOS/qubes-issues#1410]
The gtk2-engines-pixbuf package is not installed, which results in Tor Browser and Iceweasel looking bad at least for AppVMs created with the previous version of the template, since GTK2 attempts to and fails to load the pixmap engine and thus uses an ugly grey default theme.

**Comment by adrelanos** [comment]
I looked at it with and without the package.

How can I see the difference?

**Comment by qubesuser** [comment]
Running "iceweasel" from the terminal should result in complaints about being unable to load the pixmap module. Also, the scrollbar should be rendered differently, as well as input elements in some dialogs and unstyled HTML pages.

There's actually some chance this might be due to some configuration changes of my own (either having somehow changed the default GTK2 theme, or having somehow installed gtk2-engines-pixbuf in the old version of my whonix-ws template), but it seems like it shouldn't be the case.

**Comment by adrelanos** [comment]
(Technical background: This may be happening because Whonix is build using Qubes build options 'minimal' and 'no-recommends'.)

This is fixed. See above referenced commits.

Please close.
