### ISSUE TITLE
Updating qubes-utils breaks Debian TemplateVM

### ISSUE THREAD

**Issue by qnrq** [QubesOS/qubes-issues#1414]
Updating qubes-utils from 3.0.10+deb8u1 to 3.0.12+deb8u1 fails and breaks booting Debian TemplateVMs with "Error starting VM: Cannot execute qrexec-daemon!" due to an incorrect usage of /usr/lib/libqrexec-utils.so.1 After upgrading only libqrexec-utils.so and libqrexec-utils.so.2 exists.

Creating the following symlink on the TemplateVM works around the problem: /usr/lib/libqrexec-utils.so.1 -> /usr/lib/libqrexec-utils.so

**Comment by unman** [comment]
Works for me. I don't see this problem with any of my Debian templates.

**Comment by qnrq** [comment]
Interesting. I was able to reproduce it with a fresh qubes-template-debian-8-3.0.3-201509140135.

**Comment by marmarek** [comment]
What version of qubes-core-agent do you have? Maybe you've updated only
qubes-utils, but not qubes-core-agent?

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by qnrq** [comment]
3.0.16-1+deb8u1 -> 3.0.19-1+deb8u1 in same upgrade

**Comment by marmarek** [comment]
Can you point which binary requires libqrexec-utils.so.1? qrexec-agent
in qubes-core-agent_3.0.19-1+deb8u1 is linked against
libqrexec-utils.so.2...

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by marmarek** [comment]
Fixed here:
https://github.com/QubesOS/qubes-linux-utils/commit/b625704edd8c7f8863455c30f2a76893452f8f99
And for R3.0 here:
https://github.com/QubesOS/qubes-linux-utils/commit/f0cfd2c080498c99c2983e37d4f9387a292b3a30
