### ISSUE TITLE
Create catchy (and accurate) taglines for Qubes

### ISSUE THREAD

**Issue by bnvk** [QubesOS/qubes-issues#1418]
*Here is a a little experiment with the Qubes community- one which I had much success in Mailpile with...*

I'm working on the major branding / website refresh as per #1207 and the aspect of a "tagline" is something I'm working on. In branding, taglines are succinct ways to describe a product, media, company, or service in a memorable and snappy way.Given the security nature, we want to be accurate as well as catchy, obviously :-)

Here is my first pass at a tagline for Qubes:

- Perhaps The Most Secure Operating System In The World
- A Seriously Secure Operating System
- When You & Your Data Seriously Matter
- Endpoint Security Done Right

Please leave comments with your suggestions & ideas...

**Comment by woju** [comment]
„Resonably secure desktop operating system”

I'm not the autor, I saw this in some of @rootkovska writing, but
I can't remember where.

**Comment by rootkovska** [comment]
Yeah, I think Qubes is pretty much well known now as a "reasonably secure" OS. I think we should keep that tagline. E.g.: http://motherboard.vice.com/read/finally-a-reasonably-secure-operating-system-qubes-r3

**Comment by bnvk** [comment]
Ah. I had read that before in Joanna's writing as well. I love it. `"A reasonably secure OS"` it is!

**Comment by rootkovska** [comment]
You are welcome.
Joanna R., Chief Catchy-tagline Officer
