### ISSUE TITLE
USBVM Blocks S3 sleep

### ISSUE THREAD

**Issue by DeltaHeavy** [QubesOS/qubes-issues#1419]
When I have the USB controllers under dom0 (no USBVM) dropping to S3 sleep takes just under a second.

However, when a USBVM has been assigned PCI devices (The two USB2.0 controllers, in my case), dropping to S3 sleep takes upward of 15 seconds.

I'm not entirely sure the nature of the bug - it may have something to do with the fact that detaching block devices from VMs with qvm-block has reported LibVirt errors ("failed to detach").

I'm sorry this is unspecific, let me know what output (dom0 / usbvm dmesg?) will help in diagnostics.

Thanks!

**Comment by marmarek** [comment]
Do you have block devices (qvm-block) attached when going to sleep? This
might be a problem.
Anyway check logs in dom0 and USB VM (journalctl) to see what takes that
much time.

Also some USB 3.0 controllers makes problems with S3 sleep. If you
happen to have some of them, simply add xhci_pci module to
/rw/config/suspend-module-blacklist

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by DeltaHeavy** [comment]
No devices attached on sleep, I haven't tried sleeping with devices
attached although I assume that will go similarly or worse.

I was having pci reset issues with my usbvm so I disabled USB3 in the BIOS
a while ago.

I'll let you know what the logs look like, thanks as always.

Max

**Comment by DeltaHeavy** [comment]
The only journalctl entries that seems to stand out:

**Dom0**
* the suspension of the netvm (although this doesn't affect time when sys-usb has been deleted)
* clock syncing (I don't have a clockVM set..?) although the time elapsed is a fraction of a second
* libvirtd[867] EOF while reading data I/O error

**sys-usb (usbvm)**
* nothing out of the ordinary

**Comment by marmarek** [comment]
You can still try with blacklisting module - in case of USB 2.0, it would be ehci_pci. Write it to `/rw/config/suspend-module-blacklist`

**Comment by DeltaHeavy** [comment]
I couldn't seem the glean a full answer from some cursory googling, what
does the blacklisting actually do?

Thanks!

**Comment by marmarek** [comment]
> I couldn't seem the glean a full answer from some cursory googling, what does the blacklisting actually do?

It will unload the module before suspend and load it back after resume (if was loaded at suspend time). Described here: https://www.qubes-os.org/doc/config-files/

**Comment by DeltaHeavy** [comment]
Duly noted, thanks as always.

That said, it doesn't seem to have solved the issue. From lsusb.py I
noticed the device referred to as ehci_hcd, but trying that in the
blacklist didn't work either. Is there a way to list those IDs of hub
devices to tell what exactly to put in the blacklist?

Thanks!


>
> I couldn't seem the glean a full answer from some cursory googling, what
does the blacklisting actually do?

It will unload the module before suspend and load it back after resume (if
was loaded at suspend time). Described here:
https://www.qubes-os.org/doc/config-files/

—
Reply to this email directly or view it on GitHub
<https://github.com/QubesOS/qubes-issues/issues/1419#issuecomment-167269335>
.

**Comment by marmarek** [comment]
In latest kernels, ehci_hcd was split into ehci_hcd and ehci_pci - the later one is actually bound to the device (and depends on ehci_hcd), so this is the one to blacklist.

Anyway, I have similar issue on one laptop, will look into that closer.

**Comment by DeltaHeavy** [comment]
Thanks. I'll try some configurations as well and let you know if anything
comes of it.

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `python2-dnf-plugins-qubes-hooks-3.1.12-1.fc21` has been pushed to the `r3.1` testing repository for the Fedora `fc21` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.1-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/b36146961fc2542f3a5140aabb3057f4f334e30b...5570c899b8537619c17b81775bd9f3f4d5c8e8d4

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `python2-dnf-plugins-qubes-hooks-3.1.12-1.fc22` has been pushed to the `r3.1` testing repository for the Fedora `fc22` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.1-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/b36146961fc2542f3a5140aabb3057f4f334e30b...5570c899b8537619c17b81775bd9f3f4d5c8e8d4

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `python2-dnf-plugins-qubes-hooks-3.1.12-1.fc23` has been pushed to the `r3.1` testing repository for the Fedora `fc23` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.1-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/b36146961fc2542f3a5140aabb3057f4f334e30b...5570c899b8537619c17b81775bd9f3f4d5c8e8d4

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `python2-dnf-plugins-qubes-hooks-3.1.12-1.fc21` has been pushed to the `r3.1` stable repository for the Fedora `fc21` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/8064682e9e759717fbadfd072349944db749d57f...5570c899b8537619c17b81775bd9f3f4d5c8e8d4

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `python2-dnf-plugins-qubes-hooks-3.1.12-1.fc22` has been pushed to the `r3.1` stable repository for the Fedora `fc22` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/8064682e9e759717fbadfd072349944db749d57f...5570c899b8537619c17b81775bd9f3f4d5c8e8d4

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `python2-dnf-plugins-qubes-hooks-3.1.12-1.fc23` has been pushed to the `r3.1` stable repository for the Fedora `fc23` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/8064682e9e759717fbadfd072349944db749d57f...5570c899b8537619c17b81775bd9f3f4d5c8e8d4

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-agent_3.1.12-1+deb8u1` has been pushed to the `r3.1` testing repository for the Debian `jessie` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `jessie-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/b36146961fc2542f3a5140aabb3057f4f334e30b...5570c899b8537619c17b81775bd9f3f4d5c8e8d4

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-agent_3.1.12-1+deb9u1` has been pushed to the `r3.1` testing repository for the Debian `stretch` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `stretch-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/b36146961fc2542f3a5140aabb3057f4f334e30b...5570c899b8537619c17b81775bd9f3f4d5c8e8d4

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-agent_3.1.12-1+deb7u1` has been pushed to the `r3.1` testing repository for the Debian `wheezy` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `wheezy-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/b36146961fc2542f3a5140aabb3057f4f334e30b...5570c899b8537619c17b81775bd9f3f4d5c8e8d4

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-agent_3.1.12-1+deb8u1` has been pushed to the `r3.1` stable repository for the Debian `jessie` template.
To install this update, please use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/8064682e9e759717fbadfd072349944db749d57f...5570c899b8537619c17b81775bd9f3f4d5c8e8d4

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-agent_3.1.12-1+deb7u1` has been pushed to the `r3.1` stable repository for the Debian `wheezy` template.
To install this update, please use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/R3.1-rc1...5570c899b8537619c17b81775bd9f3f4d5c8e8d4

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `python2-dnf-plugins-qubes-hooks-3.0.24-1.fc20` has been pushed to the `r3.0` testing repository for the Fedora `fc20` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/a3a2130fe4393398039d196741ebd84952641aa4...5d7ad5383cdd085e008e9eeb5cca6f3437d171fd

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `python2-dnf-plugins-qubes-hooks-3.0.24-1.fc21` has been pushed to the `r3.0` testing repository for the Fedora `fc21` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/a3a2130fe4393398039d196741ebd84952641aa4...5d7ad5383cdd085e008e9eeb5cca6f3437d171fd

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `python2-dnf-plugins-qubes-hooks-3.0.24-1.fc22` has been pushed to the `r3.0` testing repository for the Fedora `fc22` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/a3a2130fe4393398039d196741ebd84952641aa4...5d7ad5383cdd085e008e9eeb5cca6f3437d171fd

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `python2-dnf-plugins-qubes-hooks-3.0.24-1.fc23` has been pushed to the `r3.0` testing repository for the Fedora `fc23` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/a3a2130fe4393398039d196741ebd84952641aa4...5d7ad5383cdd085e008e9eeb5cca6f3437d171fd

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-agent_3.0.24-1+deb8u1` has been pushed to the `r3.0` testing repository for the Debian `jessie` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `jessie-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/a3a2130fe4393398039d196741ebd84952641aa4...5d7ad5383cdd085e008e9eeb5cca6f3437d171fd

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-agent_3.0.24-1+deb7u1` has been pushed to the `r3.0` testing repository for the Debian `wheezy` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `wheezy-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/a3a2130fe4393398039d196741ebd84952641aa4...5d7ad5383cdd085e008e9eeb5cca6f3437d171fd

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `python2-dnf-plugins-qubes-hooks-3.0.25-1.fc20` has been pushed to the `r3.0` stable repository for the Fedora `fc20` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/a3a2130fe4393398039d196741ebd84952641aa4...a2b29a3ad20e16fb98f15a247a1e675c97852c2a

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `python2-dnf-plugins-qubes-hooks-3.0.25-1.fc21` has been pushed to the `r3.0` stable repository for the Fedora `fc21` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/a3a2130fe4393398039d196741ebd84952641aa4...a2b29a3ad20e16fb98f15a247a1e675c97852c2a

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `python2-dnf-plugins-qubes-hooks-3.0.25-1.fc22` has been pushed to the `r3.0` stable repository for the Fedora `fc22` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/a3a2130fe4393398039d196741ebd84952641aa4...a2b29a3ad20e16fb98f15a247a1e675c97852c2a

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `python2-dnf-plugins-qubes-hooks-3.0.25-1.fc23` has been pushed to the `r3.0` stable repository for the Fedora `fc23` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/a3a2130fe4393398039d196741ebd84952641aa4...a2b29a3ad20e16fb98f15a247a1e675c97852c2a

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-agent_3.0.25-1+deb8u1` has been pushed to the `r3.0` stable repository for the Debian `jessie` template.
To install this update, please use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/348a56fa6e18391cb626497eaebf822394380353...a2b29a3ad20e16fb98f15a247a1e675c97852c2a

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-agent_3.0.25-1+deb7u1` has been pushed to the `r3.0` stable repository for the Debian `wheezy` template.
To install this update, please use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/348a56fa6e18391cb626497eaebf822394380353...a2b29a3ad20e16fb98f15a247a1e675c97852c2a
