### ISSUE TITLE
qubes-updates-proxy: Proxying refused on filtered url "http://security.debian.org/dists/jessie/updates/InRelease"

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#1422]
In `sys-net` or `sys-whonix`.
```
sudo journalctl -f -u qubes-updates-proxy
```
Then run `sudo apt-get update` in connected TemplateVM.
```
Nov 14 00:09:03 sys-net tinyproxy[491]: Proxying refused on filtered url "http://security.debian.org/dists/jessie/updates/InRelease"
```

**Comment by marmarek** [comment]
Interesting, it should be allowed by [this line](https://github.com/QubesOS/qubes-core-agent-linux/blob/master/network/filter-updates#L16):
```
/dists/[a-z-]*/\(InRelease\|Release\|Release.gpg\)\(\|\|/\|\/download\|\?.*\)$
```
Do you see what is wrong with it? Or maybe you have some other rule there?

**Comment by adrelanos** [comment]
Marek Marczykowski-Górecki:
> Do you see what is wrong with it?

Unfortunately not, I am not good at regex.

> Or maybe you have some other rule there?

I never modified that config file. Just now `diff`ed them to make sure.
No difference.

**Comment by marmarek** [comment]
I see the problem: `jessie/updates` doesn't match to `[a-z-]*`. Interesting that other lines there are already fixed in https://github.com/QubesOS/qubes-core-agent-linux/commit/5bd308052156265ed78d2beb0e7b8236309f5223

**Comment by marmarek** [comment]
While at it - maybe fix #1188 ?

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-agent_3.0.21-1+deb8u1` has been pushed to the `r3.0` testing repository for the Debian `jessie` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `jessie-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/45d9f78ebc885dd4095cfa66a43637a9d0726d68...d957149c1bd1f0d0e3a0aab79298d2954f259a62

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-agent_3.0.21-1+deb7u1` has been pushed to the `r3.0` testing repository for the Debian `wheezy` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `wheezy-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/45d9f78ebc885dd4095cfa66a43637a9d0726d68...d957149c1bd1f0d0e3a0aab79298d2954f259a62

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-vm-3.0.21-1.fc20` has been pushed to the `r3.0` testing repository for the Fedora `fc20` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/45d9f78ebc885dd4095cfa66a43637a9d0726d68...d957149c1bd1f0d0e3a0aab79298d2954f259a62

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-vm-3.0.21-1.fc21` has been pushed to the `r3.0` testing repository for the Fedora `fc21` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/45d9f78ebc885dd4095cfa66a43637a9d0726d68...d957149c1bd1f0d0e3a0aab79298d2954f259a62

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-vm-3.0.21-1.fc22` has been pushed to the `r3.0` testing repository for the Fedora `fc22` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/1e2e9706b70e9ffaf75e73772bedcb564d66b51c...d957149c1bd1f0d0e3a0aab79298d2954f259a62

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-vm-3.0.21-1.fc23` has been pushed to the `r3.0` testing repository for the Fedora `fc23` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/1e2e9706b70e9ffaf75e73772bedcb564d66b51c...d957149c1bd1f0d0e3a0aab79298d2954f259a62

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-vm-3.0.21-1.fc20` has been pushed to the `r3.0` stable repository for the Fedora `fc20` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/45d9f78ebc885dd4095cfa66a43637a9d0726d68...d957149c1bd1f0d0e3a0aab79298d2954f259a62

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-vm-3.0.21-1.fc21` has been pushed to the `r3.0` stable repository for the Fedora `fc21` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/45d9f78ebc885dd4095cfa66a43637a9d0726d68...d957149c1bd1f0d0e3a0aab79298d2954f259a62

**Comment by axon-qubes** [comment]
On a Fedora 23 template with `qubes-core-vm-3.0.21-1.fc23`, using an `https` URL for a non-Fedora repo still fails. Changing the `https` to `http` allows it to go through.

**Comment by axon-qubes** [comment]
> On a Fedora 23 template with qubes-core-vm-3.0.21-1.fc23, using an https URL for a non-Fedora repo still fails. Changing the https to http allows it to go through.

Am I confused, or is this actually relevant?

**Comment by marmarek** [comment]
This one is about debian security updates. HTTPS is handled in separate ticket #1188 and it probably won't be backported to R3.0.

**Comment by axon-qubes** [comment]
Oh, ok. `builder-github` posted a bunch of messages about Fedora templates, so I thought it was supposed to apply to Fedora as well.

**Comment by marmarek** [comment]
Yes - netvm based on Fedora (with an updates proxy) can be used also to proxy Debian updates :)

**Comment by axon-qubes** [comment]
Ah, I understand now, thank you. My mistake!

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-agent_3.0.21-1+deb8u1` has been pushed to the `r3.0` stable repository for the Debian `jessie` template.
To install this update, please use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/45d9f78ebc885dd4095cfa66a43637a9d0726d68...348a56fa6e18391cb626497eaebf822394380353

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-agent_3.0.21-1+deb7u1` has been pushed to the `r3.0` stable repository for the Debian `wheezy` template.
To install this update, please use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/45d9f78ebc885dd4095cfa66a43637a9d0726d68...348a56fa6e18391cb626497eaebf822394380353
