### ISSUE TITLE
build Qubes-Whonix 12.0.0.3.2 RC templates

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#1423]
@marmarek can you try to build Qubes-Whonix please?

(both, gw and ws)

RC: If no grave bugs are released, after testing, that version can be blessed stable.

-----

PR:
https://github.com/marmarek/qubes-template-whonix/pull/5

----

For reference only:
https://github.com/QubesOS/qubes-issues/issues/1321

-----

Before building, please manually check `Whonix` version. (Because of #1420.)
```
cd ~/qubes-builder/qubes-src/Whonix
```
```
git describe
```

expected result:
`12.0.0.3.2-developers-only`

**Comment by marmarek** [comment]
I'm building in DispVM, so no way to have old version - it starts from clean directory :)

**Comment by marmarek** [comment]
Build logs:
* gw: https://gist.github.com/4e6180fac6e419ee2282
* ws: https://gist.github.com/cb926cd3defbd26803ef

Package versions:
* qubes-template-whonix-gw-3.0.3-201511140317.noarch.rpm
* qubes-template-whonix-ws-3.0.3-201511141406.noarch.rpm

Will be soon in unstable repo (ETA 1h).
