### ISSUE TITLE
Extend "About Qubes OS" informations

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#1431]
It would be really helpful to see  some kind of extended version
information about Qubes...
(Qubes manager -> About)
- xen version
- current kernel version (uname -r)
- qubes packages in Dom0 (extracted from: yum list qubes*)

**Comment by unman** [comment]
@andrewdavidwong This issue may be closed. Issue is resolved in r3.2 by QubesManager 3.2.10-1
