### ISSUE TITLE
find a better default name for Whonix-Workstatation AppVM than 'whonix'

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#1433]
As per [Qubes-Whonix installation documentation](https://www.whonix.org/wiki/Qubes/Install) (and in other places), we currently have the following default names:
* whonix-gw (Whonix-Gateway TemplateVM)
* whonix-ws (Whonix-Gateway TemplateVM)
* sys-whonix (Whonix-Gateway TemplateBased ProxyVM)
* whonix (Whonix-Workstation TemplateBased AppVM)

(By default names I mean, that the documentation suggests to use the name 'whonix' for the first user created Whonix-Workstation TemplateBased AppVM.)

'whonix' was a terrible choice. It's ambiguous. When users refer to "whonix", to what are they referring? Whonix generally? Gateway? Workstation? Template?

'whonix' should be renamed to something else. Such as 'whonix-work' or so. (Cannot be "whonix-ws" - because the TemplateVM is already called that way.)

Please suggest a better name so I can improve this in documentation.

**Comment by marmarek** [comment]
Maybe "anon"? Or "whonix-anon"?

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by adrelanos** [comment]
Yes. Something like this.

@bnvk also any idea?

**Comment by adrelanos** [comment]
> @bnvk also any idea?

Got answer here:
https://github.com/QubesOS/qubes-attachment/pull/1#issuecomment-158451562

**Comment by adrelanos** [comment]
Since we have `sys-whonix` already or in other words `something-whonix`, i.e. trailing `-whonix`, I think `anon-whonix` is slightly more consistent.

**Comment by adrelanos** [comment]
Done.

**Comment by mfc** [comment]
some people don't use Tor for anonymity, but as a free VPN or for security (i.e. they log into the FB .onion site). Most folks who know Tor don't know Whonix, so I feel like it further abstracts the use from the user. 

Also, we need to stop using abbreviations, nobody not intimately familiar with the documentation will know what they mean, and it makes it much more difficult to translate/localize.

I would argue for:
whonix-gw (Whonix-Gateway TemplateVM) --> `whonix-gateway`
whonix-ws (Whonix-Gateway TemplateVM) --> `whonix-workstation`
sys-whonix (Whonix-Gateway TemplateBased ProxyVM) --> `sys-tor` or `system-tor` or `network-tor` or `proxy-tor`
whonix (Whonix-Workstation TemplateBased AppVM) --> `tor-workstation` or `tor-untrusted` or `tor-personal` or `tor-work` , append `-whonix` if desired

**Comment by adrelanos** [comment]
Using `tor` in project names generates issues as soon as the project is getting popular.

Whonix is called Whonix and no longer TorBOX, and Whonix-Gateway is called Whonix-Gateway and no longer Tor-Gateway as it was called the early days due to trademark issues.

https://www.whonix.org/wiki/Dev/TPO_Trademark

I really disliked changing these names.

To be on the safe side, don't use project names* that include `tor`, or to be on the safe side, make a deal with The Tor Project. [How realistic that is...] [And even if they wouldn't win a legal case, I would urge to prevent the complaints and tension.]

[*A VM name is not a project, but from the user's perspective the same.]

**Comment by adrelanos** [comment]
Do you think there are also users who know Qubes, but not Tor or Whonix? In these cases, neither the name Tor nor Whonix makes sense to them. Perhaps both should be avoided.

**Comment by mfc** [comment]
> Using `tor` in project names generates issues as soon as the project is getting popular.
> [*A VM name is not a project, but from the user's perspective the same.]

I'm pretty sure this would not be an issue, as you mention it is not its own project or tool. It would not confusing to users because it is a totally accurate description: "this VM comes with Tor". I am happy to reach out to Roger to run it by him.

> Do you think there are also users who know Qubes, but not `Tor` or `Whonix`? In these cases, neither the name `Tor` nor `Whonix` makes sense to them. Perhaps both should be avoided.

Yes, for sure there may be users who know of Qubes but not Tor or Whonix. The difference is that the user needs to understand what Tor is at some point since whonix-gw and whonix-ws  and derived Proxy/AppVMs run over Tor. In order to understand what Whonix is, they still must first understand what Tor is.

Maybe what we need is descriptions in the firstboot of what things like Tor and Whonix mean... and make it clear that Whonix templates allow the easy creation of qubes that use Tor for networking.

**Comment by adrelanos** [comment]
Michael Carbone:
> I am happy to reach out to Roger to run it by him.

Please try to a written permission that is bulletproof in future too,
i.e. when TPO gets a new executive director, that might see this more
restrictive.
