### ISSUE TITLE
create and provide additional ways of donating

### ISSUE THREAD

**Issue by mfc** [QubesOS/qubes-issues#1434]
https://www.qubes-os.org/donate/

there should be a way to donate using a credit card, bank transfer, etc. This could be a service that converts immediately into bitcoin, or we have a paypal, worldpay, stripe, or something else account (research needed).

for future reference: https://github.com/QubesOS/qubesos.github.io/blob/master/pages/donate.md

split from the separate ticket: https://github.com/QubesOS/qubes-issues/issues/1246

**Comment by mfc** [comment]
~~stripe~~: https://support.stripe.com/questions/what-countries-does-stripe-support

**Comment by mfc** [comment]
research on auto-converting CC transactions to bitcoin 
--
relevant stackexchange question: https://bitcoin.stackexchange.com/questions/41191/i-need-fiat-btc-merchant-service
* ~~coinvoice~~ closed down
* (bitpagos)[https://www.bitpagos.com/en/]
  - https://www.bitpagos.com/en/terms/virtual_currency_use/
  - https://www.bitpagos.com/en/terms/prices/ - charges 5% on CC transactions

**Comment by mfc** [comment]
@rootkovska @mroowka what's the verdict on this? this would be really good to implement prior to new site launch, more traffic, etc

**Comment by rootkovska** [comment]
Sorry, I don't have time to research this (and won't in Dec). Generally -- anything that can terminate at our BTC address, and not require ITL bank account, should be fine.

**Comment by mfc** [comment]
Okay, shall we try to create a Bitpagos account?

**Comment by rootkovska** [comment]
Discuss via email, pls.

**Comment by mfc** [comment]
just to update this ticket, bitpagos is a no-go due to their country coverage. however in general I don't think such solutions will succeed because they will likely fold under fraud claims at some point. 

currently asking partners if they could receive donations (cc, bank transfers) in Qubes' name.

**Comment by mfc** [comment]
https://www.tibit.com has reached out, they are like flattr but for bitcoin. user pays with credit card, we would receive bitcoin.

some existing implementations include:

1. SVG buttons, these react to tibs and can have counters:
  * MuseScore - https://musescore.org/en/donate
2. CSS Buttons, can react to tibs and have counters:
  * Caesium - https://saerasoft.com/caesium/
3. Basic PNG button, these are "dumb" buttons:
  * NotePad++ https://notepad-plus-plus.org/donate/donate-action.html
  * PyDev - http://www.pydev.org/

**Comment by mfc** [comment]
this seems to be the current (and only) way to enable users to use CC to pay us in bitcoin. are we comfortable putting this on the donation page? we would want one of the "dumb" buttons. @bnvk

**Comment by mfc** [comment]
Stripe created a smooth process to create US company to receive CC charges (and bank transfers), called Stripe Atlas: https://stripe.com/atlas/faq

**Comment by mfc** [comment]
I have received an invite to Stripe Atlas, let's discuss whether this is the direction we want to go.

**Comment by mfc** [comment]
also talking with https://opencollective.com

**Comment by andrewdavidwong** [comment]
> let's discuss whether this is the direction we want to go.

Do you want that discussion to take place here or in private emails?

**Comment by mfc** [comment]
>> let's discuss whether this is the direction we want to go.

> Do you want that discussion to take place here or in private emails?

private email for now, just trying to publicly track progress.

**Comment by mfc** [comment]
just a brief summary of the fiscal sponsorship overheads and threads:
* Software in the Public Interest 
  - [5% overhead](http://spi-inc.org/projects/associated-project-howto/) 
  - no ability to provide what we want (use donations to pay developers to develop Qubes)
  - tax-deductible donations for US residents
* SF Conservancy 
  - [10% overhead](https://sfconservancy.org/members/apply/)
  - unconfirmed ability to provide what we want
  - not automated/easy process for developers
  - tax-deductible donations for US residents
* OpenCollective 
  - [10% overhead](https://opencollective.com/faq)
  - can provide what we want
  - FOSS backend for easy invoicing and payments
  - doesn't yet have tax-deductible donations for US residents but is in the process to enable
* Center for the Cultivation of Technology 
  - [not yet operational](https://techcultivation.org/)
  - aims to have FOSS backend for easy invoicing and payments
  - aims to have tax-deductible donations for EU residents
  - details to be confirmed

**Comment by andrewdavidwong** [comment]
OpenCollective sounds like the best fit so far.

**Comment by mfc** [comment]
I should add:
* Stripe Atlas
  - [0% overhead](https://stripe.com/atlas/faq#what-does-atlas-cost) (besides regular CC fees)
  - pay US income tax on donations (which are non-tax-deductible)
  - [pay account maintenance fees](https://stripe.com/atlas/faq#what-does-atlas-cost)
  - non-FOSS backend for money transfer (SV Bank)

**Comment by mfc** [comment]
team can log into https://opencollective.com/qubes-os and edit page. background image, changing donations amounts etc needs to be done manually by OC team. FYI logging in through tor is currently broken (I have notified the OC team).

**Comment by andrewdavidwong** [comment]
@mfc: Their login system seems to be on the fritz (requested an email in order to log in but never received one). I'll keep trying, though.
