### ISSUE TITLE
Bugzilla – Bug 1069652 is blocking my boot-up in Qubes

### ISSUE THREAD

**Issue by flipefr** [QubesOS/qubes-issues#1439]
The bug  1069652  in bugzilla: 

https://bugzilla.redhat.com/show_bug.cgi?id=1069652

is stopping my qubes system in the boot-up, I just updated yesterday to kernel 4.1.fc20 using qubes-dom0-update command (my only repository in yum is the default cached), my laptop is an HP Pavillion g6 2004ss with Intel i7 proccessor and hybrid AMD graphic card, I already reported this issue in the bugzilla, but please consider to help them to fix if it is in your hands, or at least increase the priority there, it is in Severity level but should be High, I definitely cannot start Qubes with the last fedora kernel and if nobody does anything (as it seems to happen because the bug had been bouncing between open and close for more than a year) I will be force to forget about Qubes.

Also consider changing base code to Debian stable or at least a distribution with DEB packages, I think it is most trustful than any Fedora or RHEL system.

Thanks
Felipe

**Comment by marmarek** [comment]
I don't follow - is the issue also happen on 4.1 kernel? Or only default 3.19?

**Comment by flipefr** [comment]
Sorry it was an error of my kernel configuration, I close the issue
