### ISSUE TITLE
`lost+found` directory conflict with VMs

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#1440]
When any of `/var/lib/qubes/appvms`, `/var/lib/qubes/vm-templates`, `/var/lib/qubes/servicevms` is on separate partition, `lost+found` would conflict with VM name of the same name.
Proposed solution: forbid VM name `lost+found`.

Other possible problems: tools listing `/var/lib/qubes/vm-templates` for a list of templates (firstboot?).

**Comment by axon-qubes** [comment]
> Proposed solution: forbid VM name `lost+found`.

This sounds reasonable to me.

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-dom0-3.1.8-1.fc20` has been pushed to the `r3.1` testing repository for dom0.
To test this update, please install it with the following command:
```
sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-admin/compare/ff63c5030daa025809d4d0dd82596d9f58a16111...ba0d60595eab2e348d296d20840e6d366c160d3b

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-dom0-3.1.10-1.fc20` has been pushed to the `r3.1` stable repository for dom0.
To install this update, please use the standard update command:
```
sudo qubes-dom0-update
```
Or update dom0 via Qubes Manager.

[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-admin/compare/36134c8c43c0ff8dd45d9cd29d0f4b0539352c18...46a338d0879410debda8e3e073024fefe87a4704
