### ISSUE TITLE
needrestart reports 'Failed to retrieve available kernel versions.'

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#1442]
(To install needrestart: `sudo apt-get install needrestart`)

`sudo needrestart` contains the output.

```
Failed to retrieve available kernel versions.
```

This is because no kernel is installed within Qubes templates.

That could be fixed. `/etc/needrestart/conf.d/50_qubes.conf`

```
$nrconf{kernelhints} = '0';
```

This alone is not an ideal solution. It would cause less confusion for most users, but falsely inform users that are installing custom kernels inside their templates, that no new kernel is available if there is.

An ideal solution would be some if/else code within the config file. I guess it should be possible. As I understand, needrestart config files are essentially perl files being evaluated. So "if using custom kernel, do nothing, otherwise `$nrconf{kernelhints} = '0';` could do.

@marmarek do you or anyone speak perl?

@liske (needrestart developer) any idea?

**Comment by marmarek** [comment]
On R3.1, the VM may have a control over its kernel (PV GRUB #1354 ), so a standard way to check the kernel may work in this case.
I know some perl basics, can look at it. In a few days...

**Comment by adrelanos** [comment]
Okay.

Please consider merging https://github.com/marmarek/qubes-core-agent-linux/pull/51 before you start working on this, because then you could append to [`misc/50_qubes.conf`](https://github.com/adrelanos/qubes-core-agent-linux/blob/needrestart/misc/50_qubes.conf) (`/etc/needrestart/conf.d/50_qubes.conf`).

**Comment by unman** [comment]
@andrewdavidwong No longer an issue in Qubes 4.0 - there's a warning about kernel versions (Currently running version is not the expected) but that is of no significance. 
Tested with stretch and buster - all good.
Please close.
