### ISSUE TITLE
Add documentation re: improve Librem 13 compatibility with Qubes 3.0 

### ISSUE THREAD

**Issue by mfc** [QubesOS/qubes-issues#1444]
Document the update procedure to improve Librem 13 compatibility with Qubes 3.0. This should be linked from the future Qubes-certified laptops page. 

from @marmarek:

upgrade X drivers (including X server...)
--------------------------------------
1.  remove not supported drivers:
`sudo yum remove
xorg-x11-drv-{trident,i740,apm,i128,cirrus,tdfx,qxl,rendition,sis,glint,siliconmotion,r128,s3virge,mga,mach64,savage}`
2. update:
`sudo qubes-dom0-update --releasever=3.1 --enablerepo=qubes-dom0-current-testing --action=update 'xorg-x11-drv-*'`

enable newer kernel
---------
`sudo qubes-dom0-update --enablerepo=qubes-dom0-unstable kernel`

**Comment by mfc** [comment]
incorporated into: https://github.com/QubesOS/qubes-doc/pull/61

**Comment by marmarek** [comment]
I have an simpler version, just need to test it out. Will do somehow at the end of the week...

**Comment by mfc** [comment]
we're hoping to push/publicize this sooner than end of week. can @rootkovska test for you?

**Comment by mfc** [comment]
@marmarek any luck with simpler instructions?

**Comment by marmarek** [comment]
Yes:
sudo qubes-dom0-update --releasever=3.1 xorg-x11-drivers
xorg-x11-drv-intel

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by mfc** [comment]
replacing all previous steps?

**Comment by marmarek** [comment]
Yes, replacing both yum remove and qubes-dom0-update (also no need for testing repo - packages are in stable).
For the kernel - it shouldn't be strictly required - I've briefly tested with original 3.19 and it worked fine. But 4.1 was tested more thoroughly. So maybe mark it as an optional step?

**Comment by mfc** [comment]
created new pull request with updated, simplified instructions: https://github.com/QubesOS/qubes-doc/issues/64
