### ISSUE TITLE
Copy / Move files between VMs fails silently if no memory exists

### ISSUE THREAD

**Issue by bnvk** [QubesOS/qubes-issues#1446]
Upon trying to move files to a new VM, if the desired VM a user is moving files to is not running and the VM tries to bootup but there is not enough memory- then the operation fails with no notification to the user except placing the yellow warning triangle in Qubes VM Manager

We should trigger either a passive notification in the tray (like starting a normal App in VM does when it fails), or a more active dialogue. My preference is for the former.

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-dom0-linux-3.1.5-1.fc20` has been pushed to the `r3.1` testing repository for dom0.
To test this update, please install it with the following command:
```
sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-admin-linux/compare/55f67d602e472c4d8a36f728792c3143d805c8ef...ae0cad589e9ddc9489ebc35194234af4235dd6ab

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-dom0-linux-3.1.6-1.fc20` has been pushed to the `r3.1` testing repository for dom0.
To test this update, please install it with the following command:
```
sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-admin-linux/compare/ae0cad589e9ddc9489ebc35194234af4235dd6ab...74afb8a7cc62b982c3bf1393e4121cbf92fd3f5c

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-dom0-linux-3.1.6-1.fc20` has been pushed to the `r3.1` stable repository for dom0.
To install this update, please use the standard update command:
```
sudo qubes-dom0-update
```
Or update dom0 via Qubes Manager.

[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-admin-linux/compare/55f67d602e472c4d8a36f728792c3143d805c8ef...74afb8a7cc62b982c3bf1393e4121cbf92fd3f5c

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-dom0-linux-3.0.18-1.fc20` has been pushed to the `r3.0` testing repository for dom0.
To test this update, please install it with the following command:
```
sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-admin-linux/compare/d2f5e0a97ff4dda5087f5f58fdfeef962895f18d...85b848393d02483a87d094354f7bff0c71946646

**Comment by bnvk** [comment]
@marmarek is enabling these testing repos something I should do with my daily work / Qubes machine? Should be ok, right?!

**Comment by marmarek** [comment]
@bnvk If you have Qubes on your main machine, better not do that there, unless you are prepared to debug some unexpected issues. If you have some testing machine, or generally not your main system (where problems would disrupt your work), then yes - enable testing repository (and report bugs) - the more testers the better :)

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-dom0-linux-3.0.19-1.fc20` has been pushed to the `r3.0` stable repository for dom0.
To install this update, please use the standard update command:
```
sudo qubes-dom0-update
```
Or update dom0 via Qubes Manager.

[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-admin-linux/compare/d2f5e0a97ff4dda5087f5f58fdfeef962895f18d...af1a352343b1028cac7d649cb9e4f2bd731a68b3
