### ISSUE TITLE
building-non-fedora-template HOWTO is out of sync

### ISSUE THREAD

**Issue by andrey-utkin** [QubesOS/qubes-issues#1450]
https://www.qubes-os.org/doc/building-non-fedora-template/ doesn't describe contents of your template-builter git repo.

```
The scripts you will be interested in will be inside the qubes-src/linux-template-builder project:

scripts_fedora
scripts_archlinux
scripts_yourOSname
```

What I see in real:

```
02:07j@acer /usr/local/src/qubes-linux-template-builder
 $ ls -1
appmenus_generic
appvm.buildlog
builder_fix_filenames
builder_setup
build_template_rpm
cleanup_image
create_template_list.sh
functions-name.sh
functions.sh
Makefile
mount_root.sh
prepared_images
prepare_image
qubeized_images
qubeize_image
README
rpm
rpmbuild
templates.spec
tests
umount_kill.sh
version
```

No intersections.

```
00_prepare.sh
```

```
02:07j@acer /usr/local/src/qubes-linux-template-builder
 $ find * | grep 00_prepare.sh
[ERR]
02:08j@acer /usr/local/src/qubes-linux-template-builder
 $ find * | grep prepare
prepared_images
prepared_images/.gitignore
prepare_image
[OK]
02:12j@acer /usr/local/src/qubes-linux-template-builder
 $ 
```

And so on. I appreciate this deeply detailed article, but it is totally useless because it doesn't match with reality.

P. S. Actually I want Gentoo Template VM because I want GnuPG 2.1.9 and Skype, both are absent in Debian and Fedora.

**Comment by marmarek** [comment]
The actual distribution-specific scripts are now in separate repositories (builder plugins). Yes, above page needs updating, but for now you can find some documentation about plugins API here:
https://github.com/QubesOS/qubes-builder/blob/master/doc/BuilderPluginAPI.md

This, connected with the [building-non-fedora-template/](https://www.qubes-os.org/doc/building-non-fedora-template/) and looking at existing plugin - for example [builder-debian](https://github.com/qubesos/qubes-builder-debian) should help with writing new plugin.

**Comment by andrewdavidwong** [comment]
More generally, I think we need to decide how automatically-generated docs will be handled separately from human-written ones (#1931).

**Comment by andrewdavidwong** [comment]
Is this still a problem?

**Comment by unman** [comment]
@andrewdavidwong I have completely rewritten https://www.qubes-os.org/doc/building-non-fedora-template/ to make it more general and to match current directory structures.
This could now be closed.
