### ISSUE TITLE
[UX] Soft windows not always fully rendered

### ISSUE THREAD

**Issue by bnvk** [QubesOS/qubes-issues#1451]
I would take a screenshot (if I could) but the issue goes away as soon as I click on the start menu to access the screenshot tool. It happens the majority of the time when launching what I call a `soft window` such as: 
- Right clicking in a Nautilus window and selecting `Properties`
- Many of the `palates` opened by using Inkscape or GIMP when designing

The effect is that usually the whole launched window is slightly transparent, title bar / colored bordered is often missing, as are other parts of the image. Clicking on it or elsewhere almost always resolve the issue

**Comment by rustybird** [comment]
The venerable xwd (sudo qubes-dom0-update xwd) should be able to get a screenshot:

    $ sleep 20; xwd -root -out screenshot.xwd

**Comment by marmarek** [comment]
Confirmed - seen this few times. Also for standard windows (in my case it was Whonix initial configuration wizard). Interesting part is that also borders were affected, so maybe window manager bug, not our GUI virtualization.

**Comment by rustybird** [comment]
A window with semi-transparent chunks:

![](https://cloud.githubusercontent.com/assets/6682340/12536380/d7850dd8-c29a-11e5-8eaf-d231349d8056.png)

Another window with fully transparent chunks:

![](https://cloud.githubusercontent.com/assets/6682340/12536379/d74ec9bc-c29a-11e5-95ca-79e57b7664d1.png)

Disabling "System Settings" -> "Desktop Effects" -> "All Effects" -> "Translucency" seems to fix it for me, but only after rebooting.

**Comment by adrelanos** [comment]
I've also seen this before. But exclusively inside Qubes.

**Comment by marmarek** [comment]
I've seen them too, also on Xfce (so, without desktop effects). No idea what is the cause.

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
