### ISSUE TITLE
Implement new website interface

### ISSUE THREAD

**Issue by bnvk** [QubesOS/qubes-issues#1460]
As per the goal of better branding for Qubes, I'm implementing the designs I proposed in #1207 it will basically be a custom Bootstrap theme on top on the exiting Jekyll site. 

I'm just opening this issue to track the progress of it!

**Comment by bnvk** [comment]
@mfc @adrelanos responses to your points in #1207

> I advice to check if using the Tor logo below the Whonix logo is safe. Perhaps asking for permission

I just asked Moritz from Tor Project and he gave me the thumbs up! I purposefully didn't write the blurb about Xen as they have [very specific terms](http://www.xenproject.org/style-guide.html) of wording they like used. I looked through the Debian & Fedora pages and our use is OK.

> Instead of "use the OS you prefer" maybe it should highlight "use all your favorite apps" or similar?

That's a good point. I'm not sure what's best here. That was in response to numerous Debian people in the community not wanting to try Qubes because they think it doesn't support Debian.

I'm hesitant (at this stage) to market Qubes from the "install whatever 'apps'" angle, as currently installing anything not in Yum / Apt is one of the biggest user experience painpoints, IMO. To my UX brain "Install apps" means, a simple GUI browsable app store which we're a bit far from having!

> I would make sure that you implement the things that already have content, so that you don't have to create new content.

Definitely I just put `Videos` as a place holder / brainstorm / documenting a path forward. There's a few things that won't be implemented by Tues as well, like "Newsletter" which need to be decided if the project even wants that.

> re: Awards & Grants, OTF dislikes being described as providing grants...

Okie doke!

**Comment by adrelanos** [comment]
Brennan Novak:
>> > I advice to check if using the Tor logo below the Whonix logo is safe. Perhaps asking for permission
> I just asked Moritz from Tor Project and he gave me the thumbs up! I purposefully didn't write the blurb about Xen as they have [very specific terms](http://www.xenproject.org/style-guide.html) of wording they like used. I looked through the Debian & Fedora pages and our use is OK.

I advice going for a legally binding letter. We don't know what the new
executive director will say on this.

But perhaps it doesn't matter as much. They very most likely won't sue
before asking to remove it. And as long they not ask, we're cool.
Removing the logo at a later point will not be that much work. I was a
bit worried about this, because in past changing the names from TorBOX,
Tor-Gateway and Tor-Workstation to something that no longer includes the
string "tor", was a painful, time wasting and time consuming process.
Not a mistake I wish to repeat.

**Comment by mfc** [comment]
@adrelanos as you have previously mentioned and Brennan confirmed with Moritz, using the Tor logo in this way is fine:
https://www.torproject.org/docs/trademark-faq.html.en#onionlogo

The issue you faced was related to incorporating the Tor word into a new name for a different project, which they explicitly say they prefer not to have happen:
https://www.torproject.org/docs/trademark-faq.html.en#combining

As you mention, if they end up having a problem with it, we can cite their language on their website for support/justification. No one is going to get sued.

> I'm hesitant (at this stage) to market Qubes from the "install whatever 'apps'" angle, as currently installing anything not in Yum / Apt is one of the biggest user experience painpoints, IMO.

Yeah this is two different things. What it would highlight is that any application that is in the repos of Fedora or Debian are available to Qubes users, and that any Windows 7 applications can be installed as well. 

So the angle is, as an existing Debian user (or Windows 7 user, or Fedora user): "all those applications that you already use for your workflow exist in Qubes as well".  This is the actual impact of the statement "Qubes supports Debian".

Only advanced users need to install programs not in the repos, that is not something ever we should focus on.

>  To my UX brain "Install apps" means, a simple GUI browsable app store which we're a bit far from having!

 That exists, it's the package managers. But again the focus is saying that someone can import their existing workflow of applications they use into Qubes a-ok.

**Comment by bnvk** [comment]
Here is a collection of to-do items (that I'm aware of) and working on today. They are ordered in how I think priority is:

- [ ] Create a more proper "blog" at the `/news/` section of the site
- [ ] Fix RSS/atom feeds for the blog, currently [master.atom](https://www.qubes-os.org/commits/master.atom) and [feed.xml](https://www.qubes-os.org/feed.xml) are broken
- [ ] Make news on homepage use proper news section
- [ ] Make the "normal blue links" display a `:hover` state
- [ ] Improve and make h2, h3, h4s on sub pages uniform and nice looking
- [ ] Make code snippets / terminal commands styled nicely
- [ ] Properly center the `LOGO - Qubes OS` section on the homepage
- [ ]  Make the "Search with DuckDuckGo" box more polished
- [ ] Fill out the `Help & Support` and `Follow & Contact` sections on homepage better
- [ ] Make blue links & buttons use the Open Sans font

@rootkovska @marmarek @mfc @adrelanos @axon-qubes please add things you come across looking at the dev URL I sent you in email. Some of these already take into account Joanna's feedback!

**Comment by adrelanos** [comment]
Minor, on /donate there is a `,` to much in the headline.

https://github.com/QubesOS/qubes-doc/pull/62#issuecomment-161467387

**Comment by axon-qubes** [comment]
Looks very nice so far; great work!

 * I agree about the search box. I think you should feel at liberty to reimagine the search function more broadly. (IOW: It doesn't have to just be polishing the box. Maybe there's a completely different but better way to do it.)
 * I wonder if "Get Started" is the right way to link to the documentation. When I saw "Get Started," I thought it was going to be something different. Not sure if most users will make the connection either.

**Comment by rootkovska** [comment]
I think my articles on Intel SGX should not be listed under "our research". Potentially also the "Intel x86 harmful" paper? Also would be nice to get some other papers there, i.e. authored by others?

**Comment by mfc** [comment]
> I think my articles on Intel SGX should not be listed under "our research". Potentially also the "Intel x86 harmful" paper? Also would be nice to get some other papers there, i.e. authored by others?

Should or should not be listed? If not listed, maybe not have the section? What are examples of other papers that should be listed instead? I think you would need to provide this content since it's outside Brennan's scope.

**Comment by axon-qubes** [comment]
Perhaps the idea is that papers like the Intel SGX one are not accurately described as "Qubes research" but rather "Rutkowska's rsearch" or "ITL's research." Or perhaps the idea is that the section should not just be limited to research produced by the Qubes/ITL team, but rather that it should include papers which are relevant to Qubes (e.g., about desktop security topics) even if authored by others.

**Comment by mfc** [comment]
here is the existing "qubes research" page: https://www.qubes-os.org/doc/qubes-research/

**Comment by marmarek** [comment]
Donation links are wrong - currently we don't have paypal. And '#' is in wrong place.

**Comment by mfc** [comment]
just submitted a couple pull requests to improve language. Agree with Marek for now we should remove Direct Donation and Paypal in the footer, can add again once we have those options available to users.

**Comment by bnvk** [comment]
@marmarek @mfc definitely, I just pushed updates to nav & the Donate page itself. My PageKite will be down for an hour or so now!

**Comment by marmarek** [comment]
@axon-qubes @Nukama, we're going to switch the website in about an hour! :)

**Comment by adrelanos** [comment]
On https://www.qubes-os.org/doc/privacy/install-whonix/ the link to https://www.qubes-os.org/en/doc/troubleshooting/debian-and-whonix/ is broken.

Is there a general problem with `/en/`?

Perhaps https://github.com/QubesOS/qubes-doc/pull/65 fixing a similar issue is superfluous.

**Comment by bnvk** [comment]
@adrelanos sorry about that! When I first started working on porting the Whonix stuff, all the pages had the `/en/` then at some point it changed to without before I sent a pull request and that one slipped through!

**Comment by adrelanos** [comment]
Apparently there are quite a few more broken `/en/` links.

```
grep --exclude-dir=.git --exclude-dir=chroot-jessie -r '(/en/'
```
```
managing-os/templates/whonix.md:To learn more and for installation instructions, read our privacy guide: [Whonix for privacy & anonymization](/en/doc/privacy/whonix/)
troubleshooting/updating-debian-and-whonix.md:Despite Qubes shipping with [Debian Templates](/en/doc/templates/debian/), most of Qubes core components run on Fedora and thus our documentation has better coverage for Fedora. However, Qubes has been working closely with the [Whonix](https://whonix.org) project which is based on Debian.
configuration/network-printer.md:In order to mitigate this risk, one might consider creating a custom template (i.e. clone the original template) and then install the 3rd party, unverified drivers there. Such template might then be made the default template for [Disposable VM creation](/en/doc/disposable-vms/), which should allow one to print any document by right-clicking on it, choosing "Open in Disposable VM" and print from there. This would allow to print documents from more trusted AppVMs (based on a trusted default template, that is not poisoned by 3rd party printer drivers).
privacy/install-whonix.md:You can learn more about [customizing Whonix here](/en/doc/privacy/customizing-whonix/)
privacy/updating-whonix.md:  However, if what you see is different or you see the word `WARNING:` you should look at our troubleshooting documentation for [Debian and Whonix](/en/doc/troubleshooting/debian-and-whonix/).
privacy/whonix.md:To improve your privacy & anonymity on the internet, you can install the [Whonix Template](/en/doc/templates/whonix/) on your Qubes machine.
privacy/whonix.md:*  [Install Whonix in Qubes](/en/doc/privacy/install-whonix/)
privacy/whonix.md:*  [Updating Whonix in Qubes](/en/doc/privacy/updating-whonix/)
privacy/whonix.md:*  [Customizing Whonix](/en/doc/privacy/customizing-whonix/)
privacy/whonix.md:*  [Uninstall Whonix from Qubes](/en/doc/privacy/uninstall-whonix/)
privacy/whonix.md:You can also use [Qubes support](/en/help/), but not all Qubes users run Whonix.
```

**Comment by adrelanos** [comment]
Perhaps the following multi fix up would sort this out.

```
one='(/en/'
two='(/'

for file_name in $(grep -r -l --exclude-dir=.git '(/en/') ; do
   sed -i "s#$one#$two#g" "$file_name"
done
```

**Comment by adrelanos** [comment]
See https://github.com/QubesOS/qubes-doc/pull/71.

**Comment by axon-qubes** [comment]
The new per-page ToCs are absolutely beautiful, @bnvk. Fantastic job there.

One small thing: I noticed that they responsively move to the bottom of the content containers on narrow screens. I wonder if it might be better to have them at the top somehow, since most page visitors on narrow screens probably won't see them until they've already read through the whole page.
