### ISSUE TITLE
Upstream Tor packages for Fedora 21 have disappeared

### ISSUE THREAD

**Issue by daveewart** [QubesOS/qubes-issues#1463]
(Originally raised this issue against qubes-app-linux-tor but I presume it's actually supposed to be here instead.)

When setting up a Tor VM, the recommendation is to install the packages qubes-tor-repo and qubes-tor in a template.  However I note that as of a few days ago, the Fedora 21 packages have disappeared.  Inside such a template with those packages already installed, 'yum update' returns:

    http://deb.torproject.org/torproject.org/rpm/fc/21/x86_64/repodata/repomd.xml: 
    [Errno 14] HTTP Error 404 - Not Found
    Trying other mirror.
    http://deb.torproject.org/torproject.org/rpm/fc/21/SRPMS/repodata/repomd.xml: 
    [Errno 14] HTTP Error 404 - Not Found
    Trying other mirror.

The directory `http://deb.torproject.org/torproject.org/rpm/fc/21` no longer exists, only the 22 and 23 equivalents.

**Comment by axon-qubes** [comment]
This is presumably because Fedora 21 reaches EOL on 2015-12-01, right?

We can update our documentation, but obviously we have no control over what the Tor project provides.

**Comment by mfc** [comment]
@daveewart don't forget you can use [whonix-gateway](https://www.whonix.org/wiki/Qubes/Install), it is a more robust implementation of torvm. It is whonix/debian-based and does not face this issue. We probably need to highlight this more in the [torvm documentation](https://www.qubes-os.org/doc/torvm/).

**Comment by marmarek** [comment]
Also we have Fedora 23 template available.
