### ISSUE TITLE
Qubes VM Manager Settings Dialog - list boxes don't resize

### ISSUE THREAD

**Issue by Thomas-Fleming** [QubesOS/qubes-issues#1467]
Bug in Qubes R3

How to replicate:

* Open Qubes VM Manager
* Select any VM
* Open the Settings dialog
* Select either the "Devices" or "Applications" tab. They both exhibit the same bug.
* Resize the Settings dialog.
* The "Available" and "Selected" list boxes haven't resized to fill the extra space.

This bug makes reading the full text in the list boxes cumbersome. One has to use a scroll bar at the bottom of the list box.

**Comment by marmarek** [comment]
Above PR fixed this.

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-manager-3.0.13-1` has been pushed to the `r3.0` testing repository for dom0.
To test this update, please install it with the following command:
```
sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-manager/compare/582e8163bd1f93885a3cc8d4ed42aead4d99e3bb...05c9fc2041fcf42c395bfce76bf317ded0c63069

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-manager-3.0.13-1` has been pushed to the `r3.0` stable repository for dom0.
To install this update, please use the standard update command:
```
sudo qubes-dom0-update
```
Or update dom0 via Qubes Manager.

[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-manager/compare/582e8163bd1f93885a3cc8d4ed42aead4d99e3bb...05c9fc2041fcf42c395bfce76bf317ded0c63069
