### ISSUE TITLE
Login screen - unintuitive mouse behaviour

### ISSUE THREAD

**Issue by Thomas-Fleming** [QubesOS/qubes-issues#1469]
Qubes R3

When booting Qubes the user is presented with a login screen. In the upper right corner there are a series of buttons for choosing the preferred desktop, language, accessibility options etc. Right or left clicking any of these buttons displays a menu. In my case, clicking the desktop button presents three options:

* KDE Plasma Workspace
* KDE Plasma Workspace (failsafe session)
* Xfce Sessions

In order to select one of the options, the user must click the **same** mouse button they used to display the menu i.e. if they right clicked to display the menu, they **must** right click to select the menu item. The same is true for using the left click to display the menu. This is quite unintuitive. Unless the user has deliberately reversed their mouse buttons (left handed), the left mouse button should always be used for selecting a menu item.

**Comment by axon-qubes** [comment]
This sounds like it might be a Fedora issue.
