### ISSUE TITLE
Update references to Fedora 21 (to 23)

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#1473]
The references to Fedora 21 are already causing confusion (#1463).

Two options:
1. Recursively find-and-replace all instances of `fedora-21` with `fedora-23` in qubes-doc. This would preserve source readability, but it might include some false positives.
2. Implement variables a la #1016. This would probably be more labor-intensive in the short run but less so in the long run. It might also end up being more accurate. However, it would sacrifice some degree of source readability.

**Comment by unman** [comment]
@andrewdavidwong I've made some changes to the Fedora minimal pages, and checked other outdated references: I think this can be closed now.
I'd be reluctant to move to implement QubesOS/qubes-issues#1016 because of the effect on readability, but that's an argument for elsewhere.
