### ISSUE TITLE
Building current core-libvirt fails

### ISSUE THREAD

**Issue by kalkin** [QubesOS/qubes-issues#1474]
The package `qubes-core-dom0-3.1.4.1` is pulling in the dependency `libvirt-daemon-xen >= 1.2.20-4` when you try to install it. There is no up to date `libvirt-daemon-xen` package on *current-testing* or *unstable* repositories (I checked the 3.1 and 3.0). 

I tried to build the RPM package using the current HEAD of `core-libvirt`, but this fails during compilation with the following error:
```
  CC       libxl/libvirt_driver_libxl_impl_la-libxl_driver.lo
libxl/libxl_conf.c: In function 'libxlMakePCI':
libxl/libxl_conf.c:1684:15: error: 'libxl_device_pci' has no member named 'rdm_policy'
         pcidev->rdm_policy = LIBXL_RDM_RESERVE_POLICY_RELAXED;
               ^
libxl/libxl_conf.c:1684:30: error: 'LIBXL_RDM_RESERVE_POLICY_RELAXED' undeclared (first use in this function)
         pcidev->rdm_policy = LIBXL_RDM_RESERVE_POLICY_RELAXED;
                              ^
libxl/libxl_conf.c:1684:30: note: each undeclared identifier is reported only once for each function it appears in
  CC       libxl/libvirt_driver_libxl_impl_la-libxl_migration.lo
Makefile:8004: recipe for target 'libxl/libvirt_driver_libxl_impl_la-libxl_conf.lo' failed
make[3]: *** [libxl/libvirt_driver_libxl_impl_la-libxl_conf.lo] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: *** wait: No child processes.  Stop.
Makefile:5108: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/home/user/rpmbuild/BUILD/libvirt-1.2.20/src'
Makefile:1989: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/user/rpmbuild/BUILD/libvirt-1.2.20'
Makefile:1885: recipe for target 'all' failed
make: *** [all] Error 2
error: Bad exit status from /var/tmp/rpm-tmp.39MS7X (%build)
```

Building version `1.20-3` works without errors.

**Comment by marmarek** [comment]
On Mon, Nov 30, 2015 at 09:33:12AM -0800, kalkin wrote:
> The package `qubes-core-dom0-3.1.4.1` is pulling in the dependency `libvirt-daemon-xen >= 1.2.20-4` when you try to install it. There is no up to date `libvirt-daemon-xen` package on *current-testing* or *unstable* repositories (I checked the 3.1 and 3.0). 

It's here:
http://yum.qubes-os.org/r3.1/current-testing/dom0/fc20/rpm/libvirt-daemon-xen-1.2.20-4.fc20.x86_64.rpm

> I tried to build the RPM package using the current HEAD of `core-libvirt`, but this fails during compilation with the following error:
> ```
>   CC       libxl/libvirt_driver_libxl_impl_la-libxl_driver.lo
> libxl/libxl_conf.c: In function 'libxlMakePCI':
> libxl/libxl_conf.c:1684:15: error: 'libxl_device_pci' has no member named 'rdm_policy'
>          pcidev->rdm_policy = LIBXL_RDM_RESERVE_POLICY_RELAXED;
>                ^
> libxl/libxl_conf.c:1684:30: error: 'LIBXL_RDM_RESERVE_POLICY_RELAXED' undeclared (first use in this function)
>          pcidev->rdm_policy = LIBXL_RDM_RESERVE_POLICY_RELAXED;
>                               ^
> libxl/libxl_conf.c:1684:30: note: each undeclared identifier is reported only once for each function it appears in
>   CC       libxl/libvirt_driver_libxl_impl_la-libxl_migration.lo

You need Xen 4.6 for that... So yes, missing BuildRequires.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by kalkin** [comment]
Ohh looks like i missed it. Thank you and sorry for disturbance.
