### ISSUE TITLE
qubes-dom0-update: report when there are no updates available

### ISSUE THREAD

**Issue by axon-qubes** [QubesOS/qubes-issues#1475]
Currently, when `sys-firewall` is based on `fedora-23-minimal`, there is no feedback indicating whether `qubes-dom0-updates` simply found no updates or whether it completely failed for some other reason:

```
[user@dom0 ~]$ sudo qubes-dom0-update
Using sys-firewall as UpdateVM to download updates for Dom0; this may take some time...
Running command on VM: 'sys-firewall'...
Checking for dom0 updates...
Yum command has been deprecated, use dnf instead.
See 'man dnf' and 'man yum2dnf' for more information.

[user@dom0 ~]$
```

(Or maybe `qubes-dom0-update` really is failing here because it's trying to use `yum` instead of `dnf`, in which case this ticket is really about that.)

**Comment by v6ak** [comment]
My experience suggests that the update script works, although it complains about this. But I agree that this is somewhat more than just a cosmetic issue, as it makes some confusion.

**Comment by marmarek** [comment]
This (text about deprecated yum) is quite hard to solve, because yum in F23 unconditionally prints that text, but dnf have some  missing features/bugs making it hardly useful for dom0 updates:
https://bugzilla.redhat.com/show_bug.cgi?id=1279001
https://bugzilla.redhat.com/show_bug.cgi?id=1227014

**Comment by axon-qubes** [comment]
IMHO, the text about yum/dnf is not the problem. You can just leave it there.  The problem, rather, is that there is no text *after* that to tell the user "No updates found." Instead, the user is just left to wonder whether there was some error preventing the system from even checking for updates in the first place (or downloading them, or installing them, etc.).

**Comment by marmarek** [comment]
Ah, I see. Will look into that.

**Comment by v6ak** [comment]
Maybe some hack like the following would be good enough:

    … | grep -vE '^(Yum command has been deprecated, use dnf instead\.|See \'man dnf\' and \'man yum2dnf\' for more information\.)$'

**Comment by marmarek** [comment]
On Sat, Dec 05, 2015 at 03:16:01AM -0800, Vít Šesták wrote:
> Maybe some hack like the following would be good enough:
> 
>     … | grep -vE '^(Yum command has been deprecated, use dnf instead\.|See \'man dnf\' and \'man yum2dnf\' for more information\.)$'

Do you know how to do it, without merging stdout and stderr?

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by v6ak** [comment]
Hmm, without merging stderr+stdout, it is not so easy, but still doable: https://gist.github.com/v6ak/58097ef190157d573646

But I understand it is not so simple hack now.

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `python2-dnf-plugins-qubes-hooks-3.1.9-1.fc21` has been pushed to the `r3.1` testing repository for the Fedora `fc21` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.1-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/ba5041579ac3d8496318f5aab130e73be0df3fc7...7835f4da2bc4ec0697302316ead8d315fb3ec811

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `python2-dnf-plugins-qubes-hooks-3.1.9-1.fc22` has been pushed to the `r3.1` testing repository for the Fedora `fc22` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.1-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/ba5041579ac3d8496318f5aab130e73be0df3fc7...7835f4da2bc4ec0697302316ead8d315fb3ec811

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `python2-dnf-plugins-qubes-hooks-3.1.9-1.fc23` has been pushed to the `r3.1` testing repository for the Fedora `fc23` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.1-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/ba5041579ac3d8496318f5aab130e73be0df3fc7...7835f4da2bc4ec0697302316ead8d315fb3ec811

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-agent_3.1.9-1+deb8u1` has been pushed to the `r3.1` testing repository for the Debian `jessie` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `jessie-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/ba5041579ac3d8496318f5aab130e73be0df3fc7...7835f4da2bc4ec0697302316ead8d315fb3ec811

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-agent_3.1.9-1+deb9u1` has been pushed to the `r3.1` testing repository for the Debian `stretch` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `stretch-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/ba5041579ac3d8496318f5aab130e73be0df3fc7...7835f4da2bc4ec0697302316ead8d315fb3ec811

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-agent_3.1.9-1+deb7u1` has been pushed to the `r3.1` testing repository for the Debian `wheezy` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `wheezy-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/ba5041579ac3d8496318f5aab130e73be0df3fc7...7835f4da2bc4ec0697302316ead8d315fb3ec811

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `python2-dnf-plugins-qubes-hooks-3.1.12-1.fc21` has been pushed to the `r3.1` stable repository for the Fedora `fc21` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/8064682e9e759717fbadfd072349944db749d57f...5570c899b8537619c17b81775bd9f3f4d5c8e8d4

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `python2-dnf-plugins-qubes-hooks-3.1.12-1.fc22` has been pushed to the `r3.1` stable repository for the Fedora `fc22` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/8064682e9e759717fbadfd072349944db749d57f...5570c899b8537619c17b81775bd9f3f4d5c8e8d4

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `python2-dnf-plugins-qubes-hooks-3.1.12-1.fc23` has been pushed to the `r3.1` stable repository for the Fedora `fc23` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/8064682e9e759717fbadfd072349944db749d57f...5570c899b8537619c17b81775bd9f3f4d5c8e8d4

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-agent_3.1.12-1+deb8u1` has been pushed to the `r3.1` stable repository for the Debian `jessie` template.
To install this update, please use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/8064682e9e759717fbadfd072349944db749d57f...5570c899b8537619c17b81775bd9f3f4d5c8e8d4

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-agent_3.1.12-1+deb7u1` has been pushed to the `r3.1` stable repository for the Debian `wheezy` template.
To install this update, please use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/R3.1-rc1...5570c899b8537619c17b81775bd9f3f4d5c8e8d4

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-agent_3.0.25-1+deb8u1` has been pushed to the `r3.0` testing repository for the Debian `jessie` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `jessie-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/5d7ad5383cdd085e008e9eeb5cca6f3437d171fd...a2b29a3ad20e16fb98f15a247a1e675c97852c2a

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-agent_3.0.25-1+deb7u1` has been pushed to the `r3.0` testing repository for the Debian `wheezy` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `wheezy-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/5d7ad5383cdd085e008e9eeb5cca6f3437d171fd...a2b29a3ad20e16fb98f15a247a1e675c97852c2a

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `python2-dnf-plugins-qubes-hooks-3.0.25-1.fc20` has been pushed to the `r3.0` testing repository for the Fedora `fc20` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/5d7ad5383cdd085e008e9eeb5cca6f3437d171fd...a2b29a3ad20e16fb98f15a247a1e675c97852c2a

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `python2-dnf-plugins-qubes-hooks-3.0.25-1.fc21` has been pushed to the `r3.0` testing repository for the Fedora `fc21` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/5d7ad5383cdd085e008e9eeb5cca6f3437d171fd...a2b29a3ad20e16fb98f15a247a1e675c97852c2a

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `python2-dnf-plugins-qubes-hooks-3.0.25-1.fc22` has been pushed to the `r3.0` testing repository for the Fedora `fc22` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/5d7ad5383cdd085e008e9eeb5cca6f3437d171fd...a2b29a3ad20e16fb98f15a247a1e675c97852c2a

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `python2-dnf-plugins-qubes-hooks-3.0.25-1.fc23` has been pushed to the `r3.0` testing repository for the Fedora `fc23` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/5d7ad5383cdd085e008e9eeb5cca6f3437d171fd...a2b29a3ad20e16fb98f15a247a1e675c97852c2a

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `python2-dnf-plugins-qubes-hooks-3.0.25-1.fc20` has been pushed to the `r3.0` stable repository for the Fedora `fc20` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/a3a2130fe4393398039d196741ebd84952641aa4...a2b29a3ad20e16fb98f15a247a1e675c97852c2a

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `python2-dnf-plugins-qubes-hooks-3.0.25-1.fc21` has been pushed to the `r3.0` stable repository for the Fedora `fc21` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/a3a2130fe4393398039d196741ebd84952641aa4...a2b29a3ad20e16fb98f15a247a1e675c97852c2a

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `python2-dnf-plugins-qubes-hooks-3.0.25-1.fc22` has been pushed to the `r3.0` stable repository for the Fedora `fc22` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/a3a2130fe4393398039d196741ebd84952641aa4...a2b29a3ad20e16fb98f15a247a1e675c97852c2a

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `python2-dnf-plugins-qubes-hooks-3.0.25-1.fc23` has been pushed to the `r3.0` stable repository for the Fedora `fc23` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/a3a2130fe4393398039d196741ebd84952641aa4...a2b29a3ad20e16fb98f15a247a1e675c97852c2a

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-agent_3.0.25-1+deb8u1` has been pushed to the `r3.0` stable repository for the Debian `jessie` template.
To install this update, please use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/348a56fa6e18391cb626497eaebf822394380353...a2b29a3ad20e16fb98f15a247a1e675c97852c2a

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-agent_3.0.25-1+deb7u1` has been pushed to the `r3.0` stable repository for the Debian `wheezy` template.
To install this update, please use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/348a56fa6e18391cb626497eaebf822394380353...a2b29a3ad20e16fb98f15a247a1e675c97852c2a
