### ISSUE TITLE
Qubes Manager: Fedora 23 TemplateVM update icons incorrectly persist

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#1476]
Since upgrading several TemplateVMs to Fedora 23, I've noticed that the "Updates pending!" icon will sometimes persist even after the TemplateVM has already been updated and rebooted multiple times, and no updates are actually available for it. This even persists across host reboots over many days.

**Comment by v6ak** [comment]
How do you update the VM? I've also seen this issue with F23 (upgraded from F21-minimal), but when I “updated” through the menu in Qubes manager, it AFAIR disappeared.

**Comment by axon-qubes** [comment]
I always update from the command line, so perhaps that's why.

**Comment by marmarek** [comment]
Do you use `dnf` or `yum-deprecated` to update F23 template?

**Comment by axon-qubes** [comment]
> Do you use dnf or yum-deprecated to update F23 template?

`dnf`

**Comment by andrewdavidwong** [comment]
@marmarek: This was fixed quite a while ago (thank you!). OK to close?
