### ISSUE TITLE
Documentation: Windows-based AppVMs

### ISSUE THREAD

**Issue by Thomas-Fleming** [QubesOS/qubes-issues#1480]
There are a few things that I believe would improve the Windows related documentation. 

https://www.qubes-os.org/doc/windows-appvms/ 
- Make it clear that the Windows account created during setup should **not** have a password as it will interfere with Windows Tools 3. This caught me out and resulted in a bunch of wasted time.
- Provide an explanation of how to fix this should the user add a password then install QWT. Simply removing the password is no longer an option once QWT is installed due to defaulting to seamless mode and un-checking seamless mode doesn't seem to work.
- Update the section on installing Windows Tools to make it clear the following command currently doesn't work in Qubes 3: `sudo qubes-dom0-update qubes-windows-tools`. Provide the command for the beta version of QWT. 
- Add troubleshooting section, including info on where to find logs should the Windows VM fail to start. 
- Add info about Windows booting after an error i.e. if the user kills a Windows VM, then starts the VM, Windows will ask the user if they want to boot into safe mode. None of this is visible or obvious if the VM is configured in seamless mode.
- Add info about GPU support (or lack thereof)
- There is a typo in the qubes-windows-tools readme when mounted as a CD. The text says "Vista nd Windows 7". Also, the instructions in the readme could be written as bat file to make life **slightly** simpler.

**Comment by adrelanos** [comment]
Tom:
> * Make it clear that the Windows account created during setup should **not** have a password as it will interfere with Windows Tools 3. This caught me out and resulted in a bunch of wasted time.

This caught me as well.

> * Update the section on installing Windows Tools to make it clear the following command currently doesn't work in Qubes 3: `sudo qubes-dom0-update qubes-windows-tools`. Provide the command for the beta version of QWT. 

This caught me as well.

**Comment by axon-qubes** [comment]
Would you be willing to make these changes and create a pull request?

**Comment by Thomas-Fleming** [comment]
I'd be happy to contribute. That being said, I'm new to Qubes so one of the main devs should review my commits in case there are errors in my documentation. I'll try to make the changes this weekend.

**Comment by omeg** [comment]
I'll be doing doc cleanup regarding windows tools in a day or two once I squish remaining bugs for the new release.
