### ISSUE TITLE
Its just a name. 

### ISSUE THREAD

**Issue by miguelspaw** [QubesOS/qubes-issues#1481]
How can it be any easier. You'll have similar issues going from say arch to ubuntu to suse.

**Comment by miguelspaw** [comment]
Leave as is so its distinctive. Don't try to blend in. Just take a minute to think of why you use cubes...cause its different etc.

**Comment by axon-qubes** [comment]
Uh... what is this in reference to?

**Comment by miguelspaw** [comment]
Its about the discussion of changing dom to something more common.

**Comment by mfc** [comment]
this is duplicate of: https://github.com/QubesOS/qubes-issues/issues/1015, please contribute there if you are interested.

dom0 is actually the generic Xen term, it is not a Qubes-specific term. So changing it from dom0 to something else is about making more specific, relevant, and understandable to Qubes users.

**Comment by miguelspaw** [comment]
Sorry
