### ISSUE TITLE
tinyproxy may return empty output (instead of error page) when asked for invalid address

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#1482]
Whonix Gw/Ws template script does this:
```
curl http://10.137.255.254:8082/
```
And search for magic string in the error page, to check if that is really (properly torified) tinyproxy running on Whonix Gateway. After https://github.com/QubesOS/qubes-core-agent-linux/commit/69bb71bea006220ff17117f5b319cbbc2a87e918 it is no longer blocked by the filtering rules, and the connection is really attempted. And (because of transparent proxy?) succeed. Then it is immediately terminated, but there are two cases:
 * connection was terminated before sending request headers there
 * connection was terminated after sending request and while waiting for response

In the first case, tinyproxy throws an error (including magic string) and that's ok. But in the second case, there is no error message - just empty output (even without response headers). So template scripts does not find its connected to Whonix Gateway.

Possible solutions (I can think of):
 * use some different way to check if tinyproxy is running on Whonix Gw. If still using magic string on wab page, it can use some really invalid url (`curl -x http://10.137.255.254:8082/ http://invalid.invalid`)
 * revert that commit - restore filtering
 * set some light filtering - basically blocking connection directly to 10.137.255.254

**Comment by adrelanos** [comment]
Good catch! It's a problem. Could potentially brick upgrading Whonix
TemplateVMs. Looking into it now.

**Comment by adrelanos** [comment]
```
whonixcheck --verbose --function check_qubes_update_proxy
```

([check_qubes](https://github.com/Whonix/whonixcheck/blob/master/usr/lib/whonixcheck/check_qubes]))

This is the full curl command in `enable-firewall`.
```
UWT_DEV_PASSTHROUGH=1 curl --silent --connect-timeout 3 http://10.137.255.254:8082/
```

**Comment by adrelanos** [comment]
This bricks upgrading indeed.

How much are we mothering our users? Protecting them from shooting their own feet? Is making it difficult to establish clearnet connections (non-torified upgrades) from Whonix TemplateVMs considered an important feature? Or is it a feature that one could easily decide to upgrade over Tor vs over clearnet by switching the TemplateVMs NetVM setting to either sys-firewall or sys-whonix?

**Comment by marmarek** [comment]
> This bricks upgrading indeed.

This is how I've found this...

> Is making it difficult to establish clearnet connections (non-torified upgrades) from Whonix TemplateVMs considered an important feature?

You tell me :)

> Or is it a feature that one could easily decide to upgrade over Tor vs over clearnet by switching the TemplateVMs NetVM setting to either sys-firewall or sys-whonix?

Yes, updates proxy in sys-whonix is to be able easily set updates over tor, even on non-Whonix templates.

**Comment by marmarek** [comment]
Rising priority, because not being able to install updates is a release blocker.

**Comment by adrelanos** [comment]
Let's revert back to filtering for now. Otherwise this breaks the release (and inclusion in the installer) of Whonix 12.

**Comment by adrelanos** [comment]
It would mean to revert the following three commits. (I don't think I missed one, but please recheck.)

* https://github.com/marmarek/qubes-core-agent-linux/commit/7a0286d58fc98cc4aa84b500d74b302cd13731fc
* https://github.com/marmarek/qubes-core-agent-linux/commit/69bb71bea006220ff17117f5b319cbbc2a87e918
* https://github.com/marmarek/qubes-core-agent-linux/commit/15c69f434bb25ea989f6352c8eb0b2ababb93c74

I think it's best to create a branch that squashes/reverts these three commits so they can later be re-applied.

**Comment by adrelanos** [comment]
Perhaps not so quick. Would you know how to implement `set some light filtering - basically blocking connection directly to 10.137.255.254`? Seems the better solution.

Otherwise I cannot think of a way how the gateway could figure out it's connected to a torified rather than non-torified updates proxy.

**Comment by marmarek** [comment]
> Perhaps not so quick. Would you know how to implement set some light filtering - basically blocking connection directly to 10.137.255.254? Seems the better solution.

See referenced commit.

**Comment by adrelanos** [comment]
Awesome! Applied the config file changes. Works for me.

**Comment by marmarek** [comment]
Building Whonix templates for R3.1 again...

**Comment by marmarek** [comment]
Hmm, maybe just whonix-gw is enough? It shouldn't matter in whonix-ws template (the fix there can be applied using standard update). Build takes a lot of time and we want to release R3.1-rc1 ASAP.

**Comment by adrelanos** [comment]
Yes. I could not think of something where this should be a problem.
