### ISSUE TITLE
update dom0 linux-firmware for Skylake and newer Radeons

### ISSUE THREAD

**Issue by esheltone** [QubesOS/qubes-issues#1483]
The Skylake integrated GPU is the first i915 GPU to require firmware blobs (it appears Brookdale may require blobs too).  They should be located in /lib/firmware/i915.  The blobs are present in the Fedora 23 template.

Additionally, while running a Radeon R7 250, the kernel complained that it could not find a binary blob.  It looks like the mid-May linux-firmware does not have blobs for newer AMD cards.

The current version of linux-firmware is from mid-May 2015.  The Skylake blobs were added in June 2015, with the most recent blobs are dated October 10, 2015 (see http://git.kernel.org/cgit/linux/kernel/git/firmware/linux-firmware.git/log/i915).

Additionally, the installer ISO needs to be configured to include the Skylake firmware blobs in its initrd, and the process for regenerating initramfs needs to pick up the Skylake blobs when appropriate.

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `xorg-x11-drivers-7.7-13.fc20` has been pushed to the `r3.1` testing repository for dom0.
To test this update, please install it with the following command:
```
sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-linux-dom0-updates/compare/4e12232523fa76e9fb7c24cb963c39ff0f5d6b59...b90d7eeded604c1003e9d530694830b1dc618951

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `xorg-x11-drivers-7.7-13.fc20` has been pushed to the `r3.1` stable repository for dom0.
To install this update, please use the standard update command:
```
sudo qubes-dom0-update
```
Or update dom0 via Qubes Manager.

[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-linux-dom0-updates/compare/4e12232523fa76e9fb7c24cb963c39ff0f5d6b59...b90d7eeded604c1003e9d530694830b1dc618951
