### ISSUE TITLE
Enigmail sent unencrypted reply

### ISSUE THREAD

**Issue by talex5** [QubesOS/qubes-issues#1485]
I got an encrypted email, so I opened it with Thunderbird. It prompted for my GPG passphrase and decrypted it. I hit Reply, typed a reply and hit Send. It sent the reply unencrypted, including the quoted plaintext of the message I was replying to!

Going through the process again, I see there is a small grey note "Enigmail is disabled for the selected identity" at the top of the window. I think it should refuse to send an unencrypted reply to encrypted email without explicit confirmation.

**Comment by marmarek** [comment]
Isn't that you've explicitly disabled sending encrypted emails to this recipient?
Anyway it looks to be (potential) issue with Enigmail, nothing Qubes specific.

**Comment by adrelanos** [comment]
I think this is an enigmail upstream bug and should be reported against
enigmail upstream if it still happens with the latest upstream version.

As a workaround, use this:
https://www.whonix.org/blog/pgp-inline-vs-mime

**Comment by talex5** [comment]
For reference, the screen looked like this:

![send-unenc](https://cloud.githubusercontent.com/assets/554131/11591667/7bd974d2-9a91-11e5-9d0a-cc0ab542f1d8.png)

The padlock is shown in the locked position and sending sends unencrypted without confirmation.

I think this was the first time I'd used enigmail on Qubes - I don't believe I'd disabled anything explicitly. The solution was to go to OpenPGP options and turn on "Enable OpenPGP support (Enigmail) for this identity". I'll try a newer version once Qubes switches to a newer Fedora.
