### ISSUE TITLE
Process qubes-set-monitor-layout hangs consuming some CPU

### ISSUE THREAD

**Issue by v6ak** [QubesOS/qubes-issues#1488]
I've found a process that constantly consumes several percents of CPU, at least on Debian 8 template. It is qubes-set-monitor-layout and seems to be called by SetMonitorLayout at some stage of VM boot.

The intermediate cause seems to be clear: There is no DISPLAY variable, which makes xrandr to fail, which causes the busy loop to be infinite. There is the environment of the hanging process:

	~% ps aux | grep qubes-set-monitor
	user       573  2.2  0.7  13200  2816 ?        S    19:07   1:54 /bin/bash /usr/bin/qubes-set-monitor-layout
	user     26332  0.0  0.4  12660  1708 pts/0    S+   20:32   0:00 grep qubes-set-monitor
	~% xargs -0 printf "%s\n" < /proc/573/environ
	MAIL=/var/mail/user
	USER=user
	SHLVL=0
	HOME=/home/user
	OLDPWD=/home/user
	LOGNAME=user
	_=/usr/lib/qubes/qubes-rpc-multiplexer
	XDG_SESSION_ID=c1
	PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
	XDG_RUNTIME_DIR=/run/user/1000
	LANG=en_US.UTF-8
	SHELL=/bin/zsh
	LC_ALL=en_US.UTF-8
	PWD=/home/user
	QREXEC_REMOTE_DOMAIN=dom0

There is the loop where the script seems to hang in:

    while ! xrandr -q &>/dev/null; do sleep 0.1; done

I have, however, no clue why there is no DISPLAY variable in the environment.

**Comment by marmarek** [comment]
Probably because it's called before "Waiting for qubes-session" - so may happen before DISPLAY being exported to the environment (saved in /tmp/qubes-session-env).

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-gui-vm-3.1.3-1.fc21` has been pushed to the `r3.1` testing repository for the Fedora `fc21` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.1-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-gui-agent-linux/compare/26587e3c82eb51c0193c7370ba1c933f99ef9364...d2ce71b29ac19610acf1abed4dc7be03e69b4c66

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-gui-vm-3.1.3-1.fc22` has been pushed to the `r3.1` testing repository for the Fedora `fc22` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.1-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-gui-agent-linux/compare/26587e3c82eb51c0193c7370ba1c933f99ef9364...d2ce71b29ac19610acf1abed4dc7be03e69b4c66

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-gui-vm-3.1.3-1.fc23` has been pushed to the `r3.1` testing repository for the Fedora `fc23` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.1-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-gui-agent-linux/compare/26587e3c82eb51c0193c7370ba1c933f99ef9364...d2ce71b29ac19610acf1abed4dc7be03e69b4c66

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-gui-agent_3.1.3+deb8u1` has been pushed to the `r3.1` testing repository for the Debian `jessie` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `jessie-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-gui-agent-linux/compare/R3.1-rc1...d2ce71b29ac19610acf1abed4dc7be03e69b4c66

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-gui-agent_3.1.3+deb9u1` has been pushed to the `r3.1` testing repository for the Debian `stretch` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `stretch-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-gui-agent-linux/compare/26587e3c82eb51c0193c7370ba1c933f99ef9364...d2ce71b29ac19610acf1abed4dc7be03e69b4c66

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-gui-agent_3.1.3+deb7u1` has been pushed to the `r3.1` testing repository for the Debian `wheezy` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `wheezy-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-gui-agent-linux/compare/26587e3c82eb51c0193c7370ba1c933f99ef9364...d2ce71b29ac19610acf1abed4dc7be03e69b4c66

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-gui-vm-3.1.4-1.fc21` has been pushed to the `r3.1` stable repository for the Fedora `fc21` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-gui-agent-linux/compare/26587e3c82eb51c0193c7370ba1c933f99ef9364...f29a7925bbcc8797c480f59d19dca5f7061fab9b

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-gui-vm-3.1.4-1.fc22` has been pushed to the `r3.1` stable repository for the Fedora `fc22` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-gui-agent-linux/compare/26587e3c82eb51c0193c7370ba1c933f99ef9364...f29a7925bbcc8797c480f59d19dca5f7061fab9b

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-gui-vm-3.1.4-1.fc23` has been pushed to the `r3.1` stable repository for the Fedora `fc23` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-gui-agent-linux/compare/26587e3c82eb51c0193c7370ba1c933f99ef9364...f29a7925bbcc8797c480f59d19dca5f7061fab9b

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-gui-agent_3.1.4+deb8u1` has been pushed to the `r3.1` stable repository for the Debian `jessie` template.
To install this update, please use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-gui-agent-linux/compare/R3.1-rc1...f29a7925bbcc8797c480f59d19dca5f7061fab9b

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-gui-agent_3.1.4+deb7u1` has been pushed to the `r3.1` stable repository for the Debian `wheezy` template.
To install this update, please use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-gui-agent-linux/compare/R3.1-rc1...f29a7925bbcc8797c480f59d19dca5f7061fab9b

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-gui-agent_3.0.16+deb8u1` has been pushed to the `r3.0` testing repository for the Debian `jessie` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `jessie-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-gui-agent-linux/compare/9934c6bdf21136eeaae5059a75799cc1faf97845...d9c3fd2017e9e1655cc35a00527c9724a0303cc1

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-gui-agent_3.0.16+deb7u1` has been pushed to the `r3.0` testing repository for the Debian `wheezy` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `wheezy-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-gui-agent-linux/compare/9934c6bdf21136eeaae5059a75799cc1faf97845...d9c3fd2017e9e1655cc35a00527c9724a0303cc1

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-gui-vm-3.0.16-1.fc20` has been pushed to the `r3.0` testing repository for the Fedora `fc20` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-gui-agent-linux/compare/9934c6bdf21136eeaae5059a75799cc1faf97845...d9c3fd2017e9e1655cc35a00527c9724a0303cc1

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-gui-vm-3.0.16-1.fc21` has been pushed to the `r3.0` testing repository for the Fedora `fc21` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-gui-agent-linux/compare/9934c6bdf21136eeaae5059a75799cc1faf97845...d9c3fd2017e9e1655cc35a00527c9724a0303cc1

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-gui-vm-3.0.16-1.fc22` has been pushed to the `r3.0` testing repository for the Fedora `fc22` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-gui-agent-linux/compare/9934c6bdf21136eeaae5059a75799cc1faf97845...d9c3fd2017e9e1655cc35a00527c9724a0303cc1

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-gui-vm-3.0.16-1.fc23` has been pushed to the `r3.0` testing repository for the Fedora `fc23` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-gui-agent-linux/compare/9934c6bdf21136eeaae5059a75799cc1faf97845...d9c3fd2017e9e1655cc35a00527c9724a0303cc1

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-gui-vm-3.0.16-1.fc20` has been pushed to the `r3.0` stable repository for the Fedora `fc20` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-gui-agent-linux/compare/9934c6bdf21136eeaae5059a75799cc1faf97845...d9c3fd2017e9e1655cc35a00527c9724a0303cc1

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-gui-vm-3.0.16-1.fc21` has been pushed to the `r3.0` stable repository for the Fedora `fc21` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-gui-agent-linux/compare/9934c6bdf21136eeaae5059a75799cc1faf97845...d9c3fd2017e9e1655cc35a00527c9724a0303cc1

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-gui-vm-3.0.16-1.fc22` has been pushed to the `r3.0` stable repository for the Fedora `fc22` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-gui-agent-linux/compare/9934c6bdf21136eeaae5059a75799cc1faf97845...d9c3fd2017e9e1655cc35a00527c9724a0303cc1

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-gui-vm-3.0.16-1.fc23` has been pushed to the `r3.0` stable repository for the Fedora `fc23` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-gui-agent-linux/compare/9934c6bdf21136eeaae5059a75799cc1faf97845...d9c3fd2017e9e1655cc35a00527c9724a0303cc1

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-gui-agent_3.0.16+deb8u1` has been pushed to the `r3.0` stable repository for the Debian `jessie` template.
To install this update, please use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-gui-agent-linux/compare/9934c6bdf21136eeaae5059a75799cc1faf97845...d9c3fd2017e9e1655cc35a00527c9724a0303cc1

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-gui-agent_3.0.16+deb7u1` has been pushed to the `r3.0` stable repository for the Debian `wheezy` template.
To install this update, please use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-gui-agent-linux/compare/9934c6bdf21136eeaae5059a75799cc1faf97845...d9c3fd2017e9e1655cc35a00527c9724a0303cc1
