### ISSUE TITLE
Qubes VM Manager - Restart button and multi-select

### ISSUE THREAD

**Issue by Thomas-Fleming** [QubesOS/qubes-issues#1499]
It would be nice to have a "Restart" button on the Qubes VM Manager alongside the "Start", "Pause" and "Shutdown" buttons. This would simulate "Pressing the "Shutdown" and "Start" buttons.

It is also common to have to restart multiple VM's after updating a Template VM. It would be good if we could multi-select VM's. That way we could select a bunch of VM's and just hit restart, which is much more convenient that manually selecting each individual VM, clicking "Shutdown", waiting, then clicking "Start".

Also, shutting down VM's often needs to be done in a specific order due to dependencies i.e. shutdown sys-firewall before sys-net. It would be good if the restart feature was aware of these dependencies and shutdown/restart in a sensible order.

Additionally, the button "Remove an existing VM (must be stopped first)" should offer to stop the VM before removing it, rather than forcing the user to click the stop button first. The text should also read "Remove selected VM" since the current text implies something subtly different. This button should also support multi-select as describer earlier.

Additional additional...

Many of the dialog box's have inconsistent availability of "hotkeys". For example; the "VM Removal Confirmation" dialog has two buttons, "Yes" and "Cancel". "Yes" can he invoked by pressing Alt + Y, "Cancel" requires one to use the mouse. The "Create New VM" dialog has no hotkeys at all. It would be good to be able to utilise the keyboard wherever possible.

**Comment by adrelanos** [comment]
Sounds useful.

**Comment by mfc** [comment]
implemented in https://github.com/QubesOS/qubes-manager/issues/6 by @plushambush (thanks!) so closing.
