### ISSUE TITLE
Documentation: Privacy Guides - Transparent Tor confusion - Whonix vs TorVM

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#1503]
https://www.qubes-os.org/doc/

Under "Privacy Guides" doesn't the part "How to Install a Transparent Tor ProxyVM (TorVM)" indicates, that Whonix-Gateway cannot be used as Transparent Tor ProxyVM. Whonix-Gateway does work as Transparent Tor ProxyVM. If one wants to use TorVM, that's fine. But doing so for getting a Transparent Tor ProxyVM is a bogus reason.

Maybe 
`How to Install a Transparent Tor ProxyVM (TorVM)`
->
`How to Install a Transparent Tor ProxyVM (TorVM) (alternative to Whonix)`
would be enough?

(Please merge https://github.com/QubesOS/qubes-doc/pull/77 first.)

**Comment by adrelanos** [comment]
Or just:
`How to Install TorVM`

**Comment by axon-qubes** [comment]
The title probably just hasn't been changed since the early days when TorVM was the only option available. Changing it to `How to Install TorVM` sounds fine to me.
