### ISSUE TITLE
Management stack fails to apply the configuration if dom0 user is named other than 'user'

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#1504]
There is 'user' username hardcoded here:
https://github.com/QubesOS/qubes-mgmt-salt-base/blob/master/_modules/module_utils.py#L155

**Comment by marmarek** [comment]
Ugly workaround: name your dom0 user 'user'.

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-mgmt-salt-base-3.1.1-1.fc20` has been pushed to the `r3.1` testing repository for dom0.
To test this update, please install it with the following command:
```
sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-mgmt-salt-base/compare/e2329f9d15cdb4a3e8a529acb14bdd48c7229419...fbfcc0adbf6291a2207613505ecfb6005a14bde8

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-mgmt-salt-base-3.1.1-1.fc20` has been pushed to the `r3.1` stable repository for dom0.
To install this update, please use the standard update command:
```
sudo qubes-dom0-update
```
Or update dom0 via Qubes Manager.

[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-mgmt-salt-base/compare/R3.1-rc1...fbfcc0adbf6291a2207613505ecfb6005a14bde8

**Comment by kmpm** [comment]
How do one recover from this on a freshly installed 3.1 rc1?
I can not run qubes-dom0-update because 

    UpdateVM not set, exiting

And there is no good vm to select. If I try to use whonix-gw or debian-8 as UpdateVM I get

    libvirt.libvirtError: internal error: libxenlight failed to create new domain 'debian-9'

or 'whonix-gw' if that was the selected one.
Default netVM is currently dom0
