### ISSUE TITLE
build proper src.rpm packages

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#1508]
Currently building src.rpm packages is broken. Mostly because we're building directly from git checkout, without proper source tarball. But src.rpm packages are needed for #816 .
The work include:
- [x] generate proper (deterministic) source tarball - `git archive` can be useful here
- [x] create static spec file - currently it uses content of `version` file for getting package version - similar problem is already solved in Debian packages

Optional:
- [x] generate proper changelog - similar code is already in Debian packages; additionally PLD Linux have a [script exactly for that](http://git.pld-linux.org/?p=packages/rpm-build-tools.git;a=blob;f=builder.sh;h=3c9a33648d2cb1b1410939c16637c7d9cac3b09d;hb=HEAD#l468)

**Comment by marmarek** [comment]
Work in progress version here: https://github.com/marmarek/qubes-builder-fedora/tree/reprobuild + https://github.com/marmarek/qubes-builder/tree/reprobuild

This require source component to be modified:
1. Rename .spec to .spec.in, use `@VERSION@` instead of `cat version` hack.
2. Make sure that symlink hack in %prep is either under `%if 0%{?qubes_builder}`, or removed.
3. Same for `%define _builddir %(pwd)`.
4. Add `Source0: %{name}-%{version}.tar.gz`
5. If component use BACKEND_VMM variable, set it in spec with `@BACKEND_VMM@`, for example `export BACKEND_VMM=@BACKEND_VMM@`.
5. Set `RPM_USE_MOCKBUILD = 1` in `Makefile.builder` of that component.

Example modified component: https://github.com/marmarek/qubes-linux-utils/tree/srcrpm

Missing parts:
- [ ] replace `git archive` with tar and move it to builder-fedora plugin; to have more explicit format and archive layout, and also to take into account local changes (devel builds) - see reprobuild branch in builder-debian
- [ ] fill changelog in spec (see issue description)
- [ ] handle the case when source tarball is already provided (vmm-xen, linux-kernel, installer-qubes-os)
- [ ] handle multi-package components (installer-qubes-os) - related to replacing `git archive`
- [ ] fix building "new" type packages using "old" code - for fast devel builds (avoid installing build deps every time)
- [ ] verify if "old" code really build all "old" components - for example if all Qubes 3.2 can be built
- [ ] verify if `INCREMENT_DEVEL_VERSIONS=1` still works
- [ ] verify if `sign` and `update-repo`/`check-repo` targets still works

cc @fepitre

**Comment by fepitre** [comment]
Great job! So the starting point here is to handle the missing parts and doing the "repack" of all the components?

**Comment by marmarek** [comment]
> So the starting point here is to handle the missing parts and doing the "repack" of all the components?

Yes. While working on some of them it may turn out some better options for `Makefile.builder` in each component will suit there. Some alternative approach is to specify "builder compatibility version", instead of requested feature. This might ease handling similar changes in the future.

**Comment by fepitre** [comment]
I'm looking at Mock possibilities and I'm testing the --buildsrpm using the spec file. Preliminaries tests of packaging work great but I encounter a problem with folders of patches. Is there a way to include easily folders of patches (e.g. patches.misc) with all the patches inside included? It seems that we have to list explicitly all the patches (like it is done in series.conf) and or Fedora upstream xen.spec. It that case it would rethink the way of applying patches?

**Comment by marmarek** [comment]
> Is there a way to include easily folders of patches (e.g. patches.misc) with all the patches inside included?

No, listing a folder of patches is a bug in rpm packaging. It require explicit patch list. It works for us because of `_builddir` hack. Part of fixing components is about listing patches in spec file... See libvirt.spec for example how to not list them twice (the second one in `%prep`). I was thinking about generating that list (add `@PATCHES@` or such), but finally abandoned that idea, because we don't have that much components with many patches.

**Comment by marmarek** [comment]
@fepitre vmm-xen build fails with `RPM_USE_MOCKBUILD=1`. Because git submodules (Source3[3-6] in spec) are not included in any tarball. I think each of them should have own tarball (created with create-archive in source-copy-in or such). Probably with some artificial version number, for example hash of last commit (or shortened hash), to avoid having same named tarball with different content.

`stubdom-dhcp` isn't a submodule, but there are only 3 files - IMO listing them directly should be ok.

**Comment by fepitre** [comment]
Oh yes. I will solve this problem as top priority.

**Comment by dmoerner** [comment]
Fedora recently modified their packaging guidelines to include a "should" recommendation that packages should verify the GPG signatures of upstream releases when the upstream provides such signatures. https://docs.fedoraproject.org/en-US/packaging-guidelines/#_source_file_verification

I wanted to flag this because this change will eventually propagate into packages that are forked from Fedora, e.g., i3, xfce4, etc., if Qubes is closely tracking Fedora's packaging. It seems like, where possible, observing this guideline would be good practice in Qubes. For packages where Qubes is the upstream, it should probably be ignored.

**Comment by fepitre** [comment]
Oh that's interesting. I will try that but I think we cannot bypass our current makefile targets for checking signature of third-party sources as we package also for Debian but that could be implemented. @marmarek what do you think?

**Comment by marmarek** [comment]
Extra safety check is a good idea. We definitely can do that for
3rd-party software we build, but since we don't release signed tarballs
for qubes components, it won't fly for our stuff.
This will also leave some verification trail in build log which is a
good thing.

**Comment by dmoerner** [comment]
I believe that adding gpg verification will have to wait until dom0 has Fedora 30 or newer, since the `%{gpgverify}` macro needed in the buildroot is only available in `redhat-rpm-config` >= 129-1.

**Comment by marmarek** [comment]
> Fedora recently modified their packaging guidelines to include a "should" recommendation that packages should verify the GPG signatures of upstream releases when the upstream provides such signatures. https://docs.fedoraproject.org/en-US/packaging-guidelines/#_source_file_verification
> 
> I wanted to flag this because this change will eventually propagate into packages that are forked from Fedora, e.g., i3, xfce4, etc., if Qubes is closely tracking Fedora's packaging. It seems like, where possible, observing this guideline would be good practice in Qubes. For packages where Qubes is the upstream, it should probably be ignored.

Branched of to https://github.com/QubesOS/qubes-issues/issues/5457

**Comment by marmarek** [comment]
src.rpm package build is implemented and all VM packages for R4.0 have them. In R4.1 both VM and dom0 packages have them.
