### ISSUE TITLE
[enhancement] giving the option back to default for dom0 Global settings

### ISSUE THREAD

**Issue by TNTBOMBOM** [QubesOS/qubes-issues#1509]
i have messed a little bit with dom0 global settings , but it seems im not getting to know the right default settings. what r the default settings ? and can we have a button for that ? 

thnx

**Comment by adrelanos** [comment]
UpdateVM: sys-firewall
ClockVM: sys-net
Default NetVM: sys-firewall
Default template: Fedora (?)
Default kernel: 3.18.17-7
Minimal VM's memory: 200 MiB
dom0 memory boost: 350 MiB
checked Keep dispVM in memory

**Comment by TNTBOMBOM** [comment]
thnx :)

**Comment by axon-qubes** [comment]
Duplicate of #1363.
