### ISSUE TITLE
update icon in dom0 VM manager persists even when no updates are available

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#1511]
https://groups.google.com/d/msgid/qubes-users/e0e43315-2793-4e82-8e11-af4ba44e0c18%40googlegroups.com
> Usually I do qubes-dom0-update from terminal  instead of using the GUI in
VM Manager, which goes okey.
Today I've tried the GUI update and after it finished updating, the update
icon remains showing in the VM manager and reports the message: Updates
Pending!
I've tried to update from terminal with qubes-dom0-update but after the
"Checking for dom0 updates..." it will just finish the task and won't
report any need to update.
The software updater says There is no network connection available. Please
check your connection settings and try again. The details are: cannot
refresh cache when offline.

> I rebooted the machine and don't know if the updates really got installed,
or not.
any info?

**Comment by adrelanos** [comment]
Does this require analysis or do you already understand what's going on?

**Comment by marmarek** [comment]
I think I've already fixed it, testing now.

**Comment by qubenix** [comment]
I was able to fix it by from dom0 terminal, but only with `-v` flag added. No idea why, I added it to debug the situation.

    sudo qubes-dom0-update -v

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-dom0-linux-3.1.5-1.fc20` has been pushed to the `r3.1` testing repository for dom0.
To test this update, please install it with the following command:
```
sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-admin-linux/compare/55f67d602e472c4d8a36f728792c3143d805c8ef...ae0cad589e9ddc9489ebc35194234af4235dd6ab

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-dom0-linux-3.1.6-1.fc20` has been pushed to the `r3.1` stable repository for dom0.
To install this update, please use the standard update command:
```
sudo qubes-dom0-update
```
Or update dom0 via Qubes Manager.

[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-admin-linux/compare/55f67d602e472c4d8a36f728792c3143d805c8ef...74afb8a7cc62b982c3bf1393e4121cbf92fd3f5c

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-dom0-linux-3.0.18-1.fc20` has been pushed to the `r3.0` testing repository for dom0.
To test this update, please install it with the following command:
```
sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-admin-linux/compare/d2f5e0a97ff4dda5087f5f58fdfeef962895f18d...85b848393d02483a87d094354f7bff0c71946646

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-dom0-linux-3.0.19-1.fc20` has been pushed to the `r3.0` stable repository for dom0.
To install this update, please use the standard update command:
```
sudo qubes-dom0-update
```
Or update dom0 via Qubes Manager.

[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-admin-linux/compare/d2f5e0a97ff4dda5087f5f58fdfeef962895f18d...af1a352343b1028cac7d649cb9e4f2bd731a68b3
