### ISSUE TITLE
input-proxy-receiver failing to set vedor:device id

### ISSUE THREAD

**Issue by o-** [QubesOS/qubes-issues#1513]
According to the documentation the input-proxy-receiver should support --vendor and --device as arguments. As can be seen in 
https://github.com/nrgaway/qubes-app-linux-input-proxy/blob/master/src/input-proxy-receiver.c#L297
this is however not the case.

I hope this configuration will cause the dom0 kernel to use the correct module. E.g. I would hope that this would then cause input to be treated by apple_hid (which fixes some quirks of those keyboards). Is that correct? otherwise that would be another issue....

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-input-proxy-1.0.3-1.fc21` has been pushed to the `r3.1` testing repository for the Fedora `fc21` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.1-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-input-proxy/compare/f3a88242ae32729bd82adf920abcc9b35946b12a...317031e14f761c97ea23553172feae4cfd75a1aa

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-input-proxy-1.0.3-1.fc22` has been pushed to the `r3.1` testing repository for the Fedora `fc22` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.1-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-input-proxy/compare/f3a88242ae32729bd82adf920abcc9b35946b12a...317031e14f761c97ea23553172feae4cfd75a1aa

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-input-proxy-1.0.3-1.fc23` has been pushed to the `r3.1` testing repository for the Fedora `fc23` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.1-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-input-proxy/compare/f3a88242ae32729bd82adf920abcc9b35946b12a...317031e14f761c97ea23553172feae4cfd75a1aa

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-input-proxy-1.0.3-1.fc20` has been pushed to the `r3.1` testing repository for dom0.
To test this update, please install it with the following command:
```
sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-input-proxy/compare/f3a88242ae32729bd82adf920abcc9b35946b12a...317031e14f761c97ea23553172feae4cfd75a1aa

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-input-proxy-1.0.3-1.fc21` has been pushed to the `r3.1` stable repository for the Fedora `fc21` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-input-proxy/compare/f3a88242ae32729bd82adf920abcc9b35946b12a...317031e14f761c97ea23553172feae4cfd75a1aa

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-input-proxy-1.0.3-1.fc22` has been pushed to the `r3.1` stable repository for the Fedora `fc22` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-input-proxy/compare/f3a88242ae32729bd82adf920abcc9b35946b12a...317031e14f761c97ea23553172feae4cfd75a1aa

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-input-proxy-1.0.3-1.fc23` has been pushed to the `r3.1` stable repository for the Fedora `fc23` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-input-proxy/compare/f3a88242ae32729bd82adf920abcc9b35946b12a...317031e14f761c97ea23553172feae4cfd75a1aa

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-input-proxy-1.0.3-1.fc20` has been pushed to the `r3.1` stable repository for dom0.
To install this update, please use the standard update command:
```
sudo qubes-dom0-update
```
Or update dom0 via Qubes Manager.

[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-input-proxy/compare/f3a88242ae32729bd82adf920abcc9b35946b12a...317031e14f761c97ea23553172feae4cfd75a1aa
