### ISSUE TITLE
"qubes-change-keyboard-layout" fails in Debian template (Fedora is working)

### ISSUE THREAD

**Issue by mfc** [QubesOS/qubes-issues#1514]
from: https://groups.google.com/d/msgid/qubes-users/3ceca98f-4879-4b10-8a1e-9f679a0178ba%40googlegroups.com

Hello,

the script qubes-change-keyboard-layout is well functioning in Fedora, but fails in the Debian template with an error (shown in the end of the post).

Before deeper analysis: Does the Qubes OS Team maintain those agent scripts for the Debian template (or only Fedora)?

The following error message occurs in a Debian AppVM (based on Debian Template) after executing 'qubes-change-keyboard-layout' and choosing a keyboard layout - doesn't matter what layout - also 'none':

```
No such schema 'org.gnome.libgnomekbd.keyboard'
Traceback (most recent call last):
  File "/usr/bin/qubes-change-keyboard-layout", line 101, in <module>
    subprocess.check_call(['/etc/X11/xinit/xinitrc.d/qubes-keymap.sh'])
  File "/usr/lib/python2.7/subprocess.py", line 535, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

As the error message indicates, the file 'qubes-keymap.sh' is missing ('locate qubes-keymap.sh' - not found). Therefore I guess the agent scripts are not completely ported to the Debian template.

Can anybody confirm the Debian Template Maintenance status?

Thank you und regards,

Qu

**Comment by mfc** [comment]
fyi patch:

https://groups.google.com/d/msgid/qubes-devel/c3f35dff-325d-422a-b50f-c021c3fc8b1f%40googlegroups.com

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-gui-vm-3.1.5-1.fc21` has been pushed to the `r3.1` testing repository for the Fedora `fc21` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.1-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-gui-agent-linux/compare/f29a7925bbcc8797c480f59d19dca5f7061fab9b...dce8cae700cf2ad47270fc43460e8a975f0df699

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-gui-vm-3.1.5-1.fc22` has been pushed to the `r3.1` testing repository for the Fedora `fc22` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.1-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-gui-agent-linux/compare/f29a7925bbcc8797c480f59d19dca5f7061fab9b...dce8cae700cf2ad47270fc43460e8a975f0df699

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-gui-vm-3.1.5-1.fc23` has been pushed to the `r3.1` testing repository for the Fedora `fc23` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.1-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-gui-agent-linux/compare/f29a7925bbcc8797c480f59d19dca5f7061fab9b...dce8cae700cf2ad47270fc43460e8a975f0df699

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-gui-agent_3.1.5+deb8u1` has been pushed to the `r3.1` testing repository for the Debian `jessie` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `jessie-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-gui-agent-linux/compare/f29a7925bbcc8797c480f59d19dca5f7061fab9b...dce8cae700cf2ad47270fc43460e8a975f0df699

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-gui-agent_3.1.5+deb9u1` has been pushed to the `r3.1` testing repository for the Debian `stretch` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `stretch-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-gui-agent-linux/compare/f29a7925bbcc8797c480f59d19dca5f7061fab9b...dce8cae700cf2ad47270fc43460e8a975f0df699

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-gui-agent_3.1.5+deb7u1` has been pushed to the `r3.1` testing repository for the Debian `wheezy` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `wheezy-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-gui-agent-linux/compare/f29a7925bbcc8797c480f59d19dca5f7061fab9b...dce8cae700cf2ad47270fc43460e8a975f0df699

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-gui-vm-3.1.5-1.fc21` has been pushed to the `r3.1` stable repository for the Fedora `fc21` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-gui-agent-linux/compare/f29a7925bbcc8797c480f59d19dca5f7061fab9b...dce8cae700cf2ad47270fc43460e8a975f0df699

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-gui-vm-3.1.5-1.fc22` has been pushed to the `r3.1` stable repository for the Fedora `fc22` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-gui-agent-linux/compare/f29a7925bbcc8797c480f59d19dca5f7061fab9b...dce8cae700cf2ad47270fc43460e8a975f0df699

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-gui-vm-3.1.5-1.fc23` has been pushed to the `r3.1` stable repository for the Fedora `fc23` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-gui-agent-linux/compare/f29a7925bbcc8797c480f59d19dca5f7061fab9b...dce8cae700cf2ad47270fc43460e8a975f0df699

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-gui-agent_3.1.5+deb8u1` has been pushed to the `r3.1` stable repository for the Debian `jessie` template.
To install this update, please use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-gui-agent-linux/compare/f29a7925bbcc8797c480f59d19dca5f7061fab9b...dce8cae700cf2ad47270fc43460e8a975f0df699

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-gui-agent_3.1.5+deb9u1` has been pushed to the `r3.1` stable repository for the Debian `stretch` template.
To install this update, please use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-gui-agent-linux/compare/f29a7925bbcc8797c480f59d19dca5f7061fab9b...dce8cae700cf2ad47270fc43460e8a975f0df699

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-gui-agent_3.1.5+deb7u1` has been pushed to the `r3.1` stable repository for the Debian `wheezy` template.
To install this update, please use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-gui-agent-linux/compare/f29a7925bbcc8797c480f59d19dca5f7061fab9b...dce8cae700cf2ad47270fc43460e8a975f0df699

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-gui-agent_3.0.16+deb8u1` has been pushed to the `r3.0` testing repository for the Debian `jessie` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `jessie-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-gui-agent-linux/compare/9934c6bdf21136eeaae5059a75799cc1faf97845...d9c3fd2017e9e1655cc35a00527c9724a0303cc1

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-gui-agent_3.0.16+deb7u1` has been pushed to the `r3.0` testing repository for the Debian `wheezy` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `wheezy-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-gui-agent-linux/compare/9934c6bdf21136eeaae5059a75799cc1faf97845...d9c3fd2017e9e1655cc35a00527c9724a0303cc1

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-gui-vm-3.0.16-1.fc20` has been pushed to the `r3.0` testing repository for the Fedora `fc20` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-gui-agent-linux/compare/9934c6bdf21136eeaae5059a75799cc1faf97845...d9c3fd2017e9e1655cc35a00527c9724a0303cc1

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-gui-vm-3.0.16-1.fc21` has been pushed to the `r3.0` testing repository for the Fedora `fc21` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-gui-agent-linux/compare/9934c6bdf21136eeaae5059a75799cc1faf97845...d9c3fd2017e9e1655cc35a00527c9724a0303cc1

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-gui-vm-3.0.16-1.fc22` has been pushed to the `r3.0` testing repository for the Fedora `fc22` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-gui-agent-linux/compare/9934c6bdf21136eeaae5059a75799cc1faf97845...d9c3fd2017e9e1655cc35a00527c9724a0303cc1

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-gui-vm-3.0.16-1.fc23` has been pushed to the `r3.0` testing repository for the Fedora `fc23` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-gui-agent-linux/compare/9934c6bdf21136eeaae5059a75799cc1faf97845...d9c3fd2017e9e1655cc35a00527c9724a0303cc1

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-gui-vm-3.0.16-1.fc20` has been pushed to the `r3.0` stable repository for the Fedora `fc20` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-gui-agent-linux/compare/9934c6bdf21136eeaae5059a75799cc1faf97845...d9c3fd2017e9e1655cc35a00527c9724a0303cc1

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-gui-vm-3.0.16-1.fc21` has been pushed to the `r3.0` stable repository for the Fedora `fc21` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-gui-agent-linux/compare/9934c6bdf21136eeaae5059a75799cc1faf97845...d9c3fd2017e9e1655cc35a00527c9724a0303cc1

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-gui-vm-3.0.16-1.fc22` has been pushed to the `r3.0` stable repository for the Fedora `fc22` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-gui-agent-linux/compare/9934c6bdf21136eeaae5059a75799cc1faf97845...d9c3fd2017e9e1655cc35a00527c9724a0303cc1

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-gui-vm-3.0.16-1.fc23` has been pushed to the `r3.0` stable repository for the Fedora `fc23` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-gui-agent-linux/compare/9934c6bdf21136eeaae5059a75799cc1faf97845...d9c3fd2017e9e1655cc35a00527c9724a0303cc1

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-gui-agent_3.0.16+deb8u1` has been pushed to the `r3.0` stable repository for the Debian `jessie` template.
To install this update, please use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-gui-agent-linux/compare/9934c6bdf21136eeaae5059a75799cc1faf97845...d9c3fd2017e9e1655cc35a00527c9724a0303cc1

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-gui-agent_3.0.16+deb7u1` has been pushed to the `r3.0` stable repository for the Debian `wheezy` template.
To install this update, please use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-gui-agent-linux/compare/9934c6bdf21136eeaae5059a75799cc1faf97845...d9c3fd2017e9e1655cc35a00527c9724a0303cc1
