### ISSUE TITLE
Logitech USB Universal Receiver does not work with 3.14+ kernels in r3.0

### ISSUE THREAD

**Issue by nrgaway** [QubesOS/qubes-issues#1516]
Works with 3.12 and 4.x kernels though.

This happens whenever the kernel modules needed for the Logitech receivers change which now requires the `hid-logitech-hidpp` module.

As a work-around, you can the the kernel module manually:
```
dracut --add-drivers hid-logitech-hidpp --kver 3.19.8-100.fc20.x86_64
dracut -H -f --kver 3.19.8-100.fc20.x86_64
```

**Comment by marmarek** [comment]
I think it depends on the time when initramfs was created - in host-only mode it should include all the currently loaded modules.
Anyway you can simply include that module in your `/etc/dracut.conf`, so it will be automatically included in all further initramfs images.

**Comment by marmarek** [comment]
As for the original issue, host-only `dracut` mode should fix the problem (assuming the driver is loaded when `dracut` is called). Straight after installation, this may be a problem because installation image doesn't contain this module (so it isn't loaded while initrd is generated there). I'm going to hijack this ticket for exactly such problem - not having Logitech USB Universal Receiver driver on installation image.

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `anaconda-20.25.16-12.fc20` has been pushed to the `r3.1` testing repository for dom0.
To test this update, please install it with the following command:
```
sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-installer-qubes-os/compare/a0a616733f739ab50c342e72defce2d16468346b...ab1104fa139e47f5509734d11aad89d87a79781b

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `anaconda-20.25.16-12.fc20` has been pushed to the `r3.1` stable repository for dom0.
To install this update, please use the standard update command:
```
sudo qubes-dom0-update
```
Or update dom0 via Qubes Manager.

[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-installer-qubes-os/compare/a0a616733f739ab50c342e72defce2d16468346b...ab1104fa139e47f5509734d11aad89d87a79781b
