### ISSUE TITLE
USB becomes disabled on boot with 4.x kernel (r3.1)

### ISSUE THREAD

**Issue by nrgaway** [QubesOS/qubes-issues#1517]
When booting the PC, USB ports are active until a kernel version is selected in menu, or automatically selected kernel proceeds at which point USB ports become disabled.  I am experiencing this with Qubes `r3.1`, but also was unable to run 4.x kernels on `r3.0` for the same reason.  The `rd.qubes.hide_all_usb` option is also not set on the kernel command line in grub.

It seems like the existing `dracut` application that shipped with the older `fc20 dom0` is too old and does not have the required configuration scripts to properly build `initramfs`.

Since I only have a USB keyboard and no other option, I have come up with a work-around that works for me:

Make backup copy of current `dracut` configurations
```
cp -rp /usr/lib/dracut /usr/lib/dracut.orig
```

Install dracut from Fedora 23
```
yum install dracut-043-61.git20151120.fc23.x86_64.rpm
```

Restore Qubes specific modules and extra-modules
```
sudo cp -rp /usr/lib/dracut.orig/modules.d/90qubes-pciback /usr/lib/dracut/modules.d
sudo cp -rp /usr/lib/dracut.orig/modules.d/90extra-modules /usr/lib/dracut/modules.d
```

Rebuild initramfs
```
dracut -H -f --kver 4.1.13-6.pvops.qubes.x86_64
```

Reboot and select 4.1 kernel

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-dom0-linux-3.1.5-1.fc20` has been pushed to the `r3.1` testing repository for dom0.
To test this update, please install it with the following command:
```
sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-admin-linux/compare/55f67d602e472c4d8a36f728792c3143d805c8ef...ae0cad589e9ddc9489ebc35194234af4235dd6ab

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-dom0-linux-3.1.6-1.fc20` has been pushed to the `r3.1` stable repository for dom0.
To install this update, please use the standard update command:
```
sudo qubes-dom0-update
```
Or update dom0 via Qubes Manager.

[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-admin-linux/compare/55f67d602e472c4d8a36f728792c3143d805c8ef...74afb8a7cc62b982c3bf1393e4121cbf92fd3f5c

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-dom0-linux-3.0.18-1.fc20` has been pushed to the `r3.0` testing repository for dom0.
To test this update, please install it with the following command:
```
sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-admin-linux/compare/d2f5e0a97ff4dda5087f5f58fdfeef962895f18d...85b848393d02483a87d094354f7bff0c71946646

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-dom0-linux-3.0.19-1.fc20` has been pushed to the `r3.0` stable repository for dom0.
To install this update, please use the standard update command:
```
sudo qubes-dom0-update
```
Or update dom0 via Qubes Manager.

[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-admin-linux/compare/d2f5e0a97ff4dda5087f5f58fdfeef962895f18d...af1a352343b1028cac7d649cb9e4f2bd731a68b3
