### ISSUE TITLE
Changing memory size for running VM

### ISSUE THREAD

**Issue by kirill9000** [QubesOS/qubes-issues#1518]
Since it's possible, shouldn't VM Manager do it when user changes VM settings?

**Comment by marmarek** [comment]
What do you mean? It is exactly what Qubes Manager does.

**Comment by kirill9000** [comment]
I mean, it should give AppVM more (or less) RAM immediately, without the need to restart it. Like `xl mem-set` supposedly does (although it doesn't work for me on Qubes for some reason).

**Comment by marmarek** [comment]
In Qubes OS we have dynamic memory management: https://www.qubes-os.org/doc/qmemman/
It gives memory to the VM when it needs it (according to memory usage in such VM), and of course if it is available. Up to the upper limit set in Qubes Manager.

**Comment by kirill9000** [comment]
STR:
1) Create new VM, max memory = 1 GB.
2) Start It.
3) Change it's max memory to 4 GB.
4) Create tmpfs (size=4GB) and write 1+ GB data to it.
5) There's still just 1 GB of memory allocated to AppVM. Data goes into swap. After swap runs out, VM becomes unresponsive.

Am I missing something?

**Comment by marmarek** [comment]
On Tue, Feb 02, 2016 at 02:59:28PM -0800, kirill9000 wrote:
> STR:
> 1) Create new VM, max memory = 1 GB.
> 2) Start It.
> 3) Change it's max memory to 4 GB.
> 4) Create tmpfs (size=4GB) and write 1+ GB data to it.
> 5) There's still just 1 GB of memory allocated to AppVM. Data goes into swap. After swap runs out, VM becomes unresponsive.
> 
> Am I missing something?

Ah, I see. Yes, max memory is changed only after VM restart. It is Xen
limitation.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by kirill9000** [comment]
OK, thanks for clarification. Are there any downsides in setting max memory for all VMs equal to total physical RAM amount and letting qmemman handle it? Fragmentation maybe?

**Comment by marmarek** [comment]
Yes, Linux kernel allocates some structures at boot time according to the max mem. AFAIR it's about 1% of that size.
