### ISSUE TITLE
No security-testing repo for Debian templates

### ISSUE THREAD

**Issue by rustybird** [QubesOS/qubes-issues#1522]
There doesn't seem to be a Qubes security-testing repository for Debian templates.

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-agent_3.1.8-1+deb8u1` has been pushed to the `r3.1` testing repository for the Debian `jessie` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `jessie-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/8064682e9e759717fbadfd072349944db749d57f...ba5041579ac3d8496318f5aab130e73be0df3fc7

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-agent_3.1.8-1+deb9u1` has been pushed to the `r3.1` testing repository for the Debian `stretch` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `stretch-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/8064682e9e759717fbadfd072349944db749d57f...ba5041579ac3d8496318f5aab130e73be0df3fc7

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-agent_3.1.8-1+deb7u1` has been pushed to the `r3.1` testing repository for the Debian `wheezy` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `wheezy-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/8064682e9e759717fbadfd072349944db749d57f...ba5041579ac3d8496318f5aab130e73be0df3fc7

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-agent_3.0.22-1+deb8u1` has been pushed to the `r3.0` testing repository for the Debian `jessie` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `jessie-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/d957149c1bd1f0d0e3a0aab79298d2954f259a62...12d91a84fa0bb23cafaf92c51a5c9b4564862d0c

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-agent_3.0.22-1+deb7u1` has been pushed to the `r3.0` testing repository for the Debian `wheezy` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `wheezy-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/d957149c1bd1f0d0e3a0aab79298d2954f259a62...12d91a84fa0bb23cafaf92c51a5c9b4564862d0c

**Comment by marmarek** [comment]
Besides putting the updates into new securitytesting repo (which is itself provided by the package in testing repo...), we've also uploaded update xen package into ordinary testing repo.

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-vm-3.0.23-1.fc20` has been pushed to the `r3.0` testing repository for the Fedora `fc20` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/348a56fa6e18391cb626497eaebf822394380353...a3a2130fe4393398039d196741ebd84952641aa4

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-vm-3.0.23-1.fc21` has been pushed to the `r3.0` testing repository for the Fedora `fc21` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/348a56fa6e18391cb626497eaebf822394380353...a3a2130fe4393398039d196741ebd84952641aa4

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-vm-3.0.23-1.fc22` has been pushed to the `r3.0` testing repository for the Fedora `fc22` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/348a56fa6e18391cb626497eaebf822394380353...a3a2130fe4393398039d196741ebd84952641aa4

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-vm-3.0.23-1.fc23` has been pushed to the `r3.0` testing repository for the Fedora `fc23` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/348a56fa6e18391cb626497eaebf822394380353...a3a2130fe4393398039d196741ebd84952641aa4

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-vm-3.1.8-1.fc21` has been pushed to the `r3.1` testing repository for the Fedora `fc21` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.1-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/8064682e9e759717fbadfd072349944db749d57f...ba5041579ac3d8496318f5aab130e73be0df3fc7

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-vm-3.1.8-1.fc22` has been pushed to the `r3.1` testing repository for the Fedora `fc22` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.1-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/8064682e9e759717fbadfd072349944db749d57f...ba5041579ac3d8496318f5aab130e73be0df3fc7

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-vm-3.1.8-1.fc23` has been pushed to the `r3.1` testing repository for the Fedora `fc23` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.1-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/8064682e9e759717fbadfd072349944db749d57f...ba5041579ac3d8496318f5aab130e73be0df3fc7

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-vm-3.0.23-1.fc20` has been pushed to the `r3.0` stable repository for the Fedora `fc20` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/d957149c1bd1f0d0e3a0aab79298d2954f259a62...a3a2130fe4393398039d196741ebd84952641aa4

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-vm-3.0.23-1.fc21` has been pushed to the `r3.0` stable repository for the Fedora `fc21` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/d957149c1bd1f0d0e3a0aab79298d2954f259a62...a3a2130fe4393398039d196741ebd84952641aa4

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-vm-3.0.23-1.fc22` has been pushed to the `r3.0` stable repository for the Fedora `fc22` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/d957149c1bd1f0d0e3a0aab79298d2954f259a62...a3a2130fe4393398039d196741ebd84952641aa4

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-vm-3.0.23-1.fc23` has been pushed to the `r3.0` stable repository for the Fedora `fc23` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/d957149c1bd1f0d0e3a0aab79298d2954f259a62...a3a2130fe4393398039d196741ebd84952641aa4

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `python2-dnf-plugins-qubes-hooks-3.1.12-1.fc21` has been pushed to the `r3.1` stable repository for the Fedora `fc21` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/8064682e9e759717fbadfd072349944db749d57f...5570c899b8537619c17b81775bd9f3f4d5c8e8d4

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `python2-dnf-plugins-qubes-hooks-3.1.12-1.fc22` has been pushed to the `r3.1` stable repository for the Fedora `fc22` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/8064682e9e759717fbadfd072349944db749d57f...5570c899b8537619c17b81775bd9f3f4d5c8e8d4

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `python2-dnf-plugins-qubes-hooks-3.1.12-1.fc23` has been pushed to the `r3.1` stable repository for the Fedora `fc23` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/8064682e9e759717fbadfd072349944db749d57f...5570c899b8537619c17b81775bd9f3f4d5c8e8d4

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-agent_3.1.12-1+deb8u1` has been pushed to the `r3.1` stable repository for the Debian `jessie` template.
To install this update, please use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/8064682e9e759717fbadfd072349944db749d57f...5570c899b8537619c17b81775bd9f3f4d5c8e8d4

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-agent_3.1.12-1+deb7u1` has been pushed to the `r3.1` stable repository for the Debian `wheezy` template.
To install this update, please use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/R3.1-rc1...5570c899b8537619c17b81775bd9f3f4d5c8e8d4

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-agent_3.0.25-1+deb8u1` has been pushed to the `r3.0` stable repository for the Debian `jessie` template.
To install this update, please use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/348a56fa6e18391cb626497eaebf822394380353...a2b29a3ad20e16fb98f15a247a1e675c97852c2a

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-agent_3.0.25-1+deb7u1` has been pushed to the `r3.0` stable repository for the Debian `wheezy` template.
To install this update, please use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/348a56fa6e18391cb626497eaebf822394380353...a2b29a3ad20e16fb98f15a247a1e675c97852c2a
