### ISSUE TITLE
qvm-backup requires an option to specify a password through stdin / cmdline

### ISSUE THREAD

**Issue by Rudd-O** [QubesOS/qubes-issues#1523]
I just spent the better part of two hours trying to automate `qvm-backup` with no success at all.

Please add a command line option `--stdin` that lets `qvm-backup` override `getpass.getpass(...)` and also skip the confirmation `[y/N]` such that the password can be specified through standard input.

It should not be difficult -- you just need a code block that skips the confirmation if `--stdin` is specified, and another code block that skips the `getpass.getpass()` call if the aforementioned parameter has been specified.

All of this can be implemented in `qvm-backup` very easily.

Perhaps, even, there could be a `--file` option, which could have `-` as a parameter, meaning `/dev/stdin`.  That way, it need not be the case that `--stdin` exists, or hardcodes the password input to standard input.  Maybe the input can be a file in `/dev/shm`.  Certainly, this can be used to do integration tests of `qvm-backup`, especially without having to include `pty` cobwebs in the code.

Thanks.

**Comment by marmarek** [comment]
There is `qvm-backup --passphrase-file=-` for it.
