### ISSUE TITLE
Wifi no longer recognised in Debian-based sys-net VM after 3.0 -> 3.1 upgrade

### ISSUE THREAD

**Issue by mig5** [QubesOS/qubes-issues#1526]
I upgraded from Qubes 3.0 to 3.1 using the experimental upgrade documentation. I encountered no issues performing the upgrade on all my VMs (mostly Debian).

After upgrading dom0 and rebooting, my sys-net VM (which is based on Debian 7 template) no longer sees wireless device. This is despite the Wifi controller still allocated to that VM - no other changes were made.

I run 'ifconfig -a' and I don't see any wlan0 device - just eth0 - and lo. I see that wifi module is loaded in the kernel just fine.

I switch the sys-net VM to my Fedora 21 template, and wifi magically works fine there! So although this seems distro-specific, it was working fine on Qubes 3. Very strange. Debian 7 templates had all packages up to date prior to me attempting the 3.1 upgrade.

Everything else seems perfectly fine with the upgrade.

Let me know if I can provide any other info?

Thanks!

**Comment by mig5** [comment]
Hardware details as per original HCL at https://groups.google.com/forum/#!msg/qubes-users/fRxncIsQrGc/J8_truiDD1QJ

I tried booting the Debian sys-net under 3.18.17-7 and 3.18.17-6 kernels, to see if it was kernel specific, but I could not get it to boot at all on those kernels. I can only boot sys-net under 4.1.13-6 on Debian. I am using same kernel for booting under Fedora template, under which wifi is recognised fine.

**Comment by marmarek** [comment]
Check kernel messages - I guess it's about not installed firmware
package.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by mig5** [comment]
Thanks, yes indeed, the version of firmware-iwlwifi in Debian Jessie doesn't work under kernel 4.1 for my Intel wifi card.

Had to install newer version of firmware-iwlwifi from jessie-backports and then it was fine.

I guess it is a separate bug that you can't start VMs under 3.x kernel (switching kernel version in Qubes Manager -> relevantVM -> Settings), you get the 'can't connect to qrexec-agent' error. This occurs for me regardless of Fedora or Debian template. As that would have been a realistic workaround too. Let me know if you want a separate ticket for that.

Thanks again.

**Comment by marmarek** [comment]
Kernel packaging for R3.1 is slightly different. Your 3.x kernel is probably from R3.0 installation. Take a look at [managing VM kernel](https://www.qubes-os.org/doc/managing-vm-kernel/) documentation how to get alternative kernel (in this case probably the easiest way would be to generate VM kernel based on 3.x still installed in dom0).
We can also upload 3.x package to R3.1 repo, but I don't think it is needed.
