### ISSUE TITLE
Fix release schedule table style

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#1534]
Currently the table looks ugly. I've inserted some [ugly workaround](https://github.com/QubesOS/qubes-doc/commit/17072381ef2914a66e83c6de007f6ffc7509d80f), but that needs some real solution.

cc @bnvk

**Comment by andrewdavidwong** [comment]
@marmarek: Is this still a problem?

**Comment by marmarek** [comment]
Yes, take a look for example here: https://www.qubes-os.org/doc/releases/3.2/schedule/

**Comment by andrewdavidwong** [comment]
How's that, @marmarek? If it's still too ugly, feel free to re-open this. :smile:
