### ISSUE TITLE
[Whonix] whonixcheck error xen-domU

### ISSUE THREAD

**Issue by mfc** [QubesOS/qubes-issues#1535]
`ERROR: Virtualizer xen xen-domU unsupported by Whonix developers! Whonixcheck aborted!
Using Virtualizer xen xen-domU together with Whonix is recommended against, because it is rarely tested.`

@adrelanos the error message does not say how to disable xen-domU, if that is what is expected of the user. I have not modified the whonix gateway in any way from the defaults, and have kept it up-to-date.

**Comment by adrelanos** [comment]
How to produce this condition?

How to enable/disable xen-domU? [if this is even a valid question]

This error message is supposed to be shown, when users run whonixcheck
inside unsupported virtualizers. When the output of
'systemd-detect-virt' produces unexpected results.

What is the output of the following two commands?

sudo systemd-detect-virt

sudo virt-what

Expected output of 'systemd-detect-virt' is 'xen'. Any idea why your
system derivatives?

Qubes Q3?

Using any newer version of Xen?

**Comment by mfc** [comment]
running those within my whonix gateway, I get:
`$ sudo systemd-detect-virt`
`xen`
`$ sudo virt-what`
`xen`
`xen-domU`

Seems like that `xen-domU` output from `sudo virt-what` is the issue.

running R3.1-rc1 upgraded from R3.0. Xen release version `4.1.13-6.pvops.qubes.x86_64`

**Comment by adrelanos** [comment]
virt-what isn't used anymore in Whonix 12. It used to be used until
Whonix 11. It's still useful here to gather manually as debug output.
Whonix 12 exclusively uses systemd-detect-virt. By updating to Whonix 12
this should be gone. Just update from the stable repository [or
alternatively get a new template].

[[[

The file in question is:
/usr/lib/whonixcheck/check_virtualizer

I guess you have exactly this file as of Whonix 11:
https://github.com/Whonix/whonixcheck/blob/Whonix11/usr/lib/whonixcheck/check_virtualizer

But you should have this file as of Whonix 12:
https://github.com/Whonix/whonixcheck/blob/Whonix12/usr/lib/whonixcheck/check_virtualizer

]]]

**Comment by mfc** [comment]
okay, I guess I had upgraded to Whonix 12 in the template but hadn't yet rebooted the whonix gateway. After rebooting the whonix gateway again and running `WhonixCheck` I do not get the error anymore. Thanks for the help!
