### ISSUE TITLE
libvirtError: virDomainLookupByName() failed

### ISSUE THREAD

**Issue by hdevalence** [QubesOS/qubes-issues#1537]
While using Qubes, I got a dom0 popup telling me "libvertError: virDomainLookupByName() failed", with the following log data:
```
----
line: if ret is None:raise libvirtError('virDomainLookupByName() failed', conn=self)
func: lookupByName
line no.: 4066
file: /usr/lib64/python2.7/site-packages/libvirt.py
----
line: self._libvirt_domain = vmm.libvirt_conn.lookupByName(self.name)
func: libvirt_domain
line no.: 750
file: /usr/lib64/python2.7/site-packages/qubes/modules/000QubesVm.py
----
line: if self.libvirt_domain.isActive():
func: is_running
line no.: 902
file: /usr/lib64/python2.7/site-packages/qubes/modules/000QubesVm.py
----
line: if not vm.is_running():
func: measure_cpu_usage
line no.: 234
file: /usr/lib64/python2.7/site-packages/qubes/qubes.py
----
line: self.last_measure_time)
func: update_table
line no.: 768
file: /usr/lib64/python2.7/site-packages/qubesmanager/main.py
```

**Comment by marmarek** [comment]
I assume Qubes R3.1-rc1, right?

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by hdevalence** [comment]
Yes, sorry for not specifying.

**Comment by marmarek** [comment]
Do you know any specific steps to reproduce this issue? Was it during starting some VM? Or maybe creating, stopping, launching some application? After restoring backup?

**Comment by hdevalence** [comment]
Nope, unfortunately I've been unable to reproduce it, so I'm afraid it's not a very helpful bug report :(

**Comment by marmarek** [comment]
Above logging finally caught this error. The error code is... `None`. Looks like a bug in libvirt library/python bindings.

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-dom0-3.1.12-1.fc20` has been pushed to the `r3.1` testing repository for dom0.
To test this update, please install it with the following command:
```
sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-admin/compare/04415e13fed0e15539419ec930ae1046e4f2fcd7...ae848d536958b2064ec96f96ad96540162cb4683

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-dom0-3.1.12-1.fc20` has been pushed to the `r3.1` stable repository for dom0.
To install this update, please use the standard update command:
```
sudo qubes-dom0-update
```
Or update dom0 via Qubes Manager.

[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-admin/compare/04415e13fed0e15539419ec930ae1046e4f2fcd7...ae848d536958b2064ec96f96ad96540162cb4683

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-dom0-3.0.28-1.fc20` has been pushed to the `r3.0` testing repository for dom0.
To test this update, please install it with the following command:
```
sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-admin/compare/b25c3f05c7c93e397cd2639e533c089bf5e140fb...d29c2889b0744d57c51ce9b14d87a411c3d84dfa

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-dom0-3.0.28-1.fc20` has been pushed to the `r3.0` stable repository for dom0.
To install this update, please use the standard update command:
```
sudo qubes-dom0-update
```
Or update dom0 via Qubes Manager.

[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-admin/compare/444d602d88cc7e079a550ff8da18901fac472781...d29c2889b0744d57c51ce9b14d87a411c3d84dfa
