### ISSUE TITLE
Lower CloudFlare DDiS settings

### ISSUE THREAD

**Issue by bnvk** [QubesOS/qubes-issues#1543]
Currently, certain non TorBrowser browsers when acessing qubes-os.org over Tor, trigger CloudFlares DDoS protection which requires a user filling out a CAPTCHA. I suggest we lower this setting to the lowest setting, which then never shows the CAPTCHA.

**Comment by marmarek** [comment]
It is set to the lowest possible value, but it doesn't help. For that we have a script which periodically update a whitelist with tor exit nodes (https://github.com/DonnchaC/cloudflare-tor-whitelister). The problem was that the script wasn't running for some time - fixed now.

**Comment by mfc** [comment]
FYI you can now whitelist Tor users entirely within Cloudflare settings:

https://support.cloudflare.com/hc/en-us/articles/203306930-Does-CloudFlare-block-Tor-

**Comment by marmarek** [comment]
Already done #1801 :)

**Comment by mfc** [comment]
niiiiiiice two steps ahead of me :)
