### ISSUE TITLE
Feature request: --include in qubes backup

### ISSUE THREAD

**Issue by Rudd-O** [QubesOS/qubes-issues#1545]
Qubes backup does not have a way to back up just a few handful of VMs exclusively, unless the GUI is engaged.

Please add multi-specifyiable --include parameter.

Thanks.

**Comment by marmarek** [comment]
You can simply pass VM names as the arguments to `qvm-backup` command:
```
qvm-backup -d my-backup-vm /mnt/backup-target vm-to-include1 vm-to-include2
```

**Comment by Rudd-O** [comment]
Wut.

I'm an idiot.  How did I miss that?

Sorry for the extra work.
