### ISSUE TITLE
systemd-modules-load.service failed

### ISSUE THREAD

**Issue by Rudd-O** [QubesOS/qubes-issues#1546]
error:

```
[root@dom0 udev]# systemctl status systemd-modules-load.service           
systemd-modules-load.service - Load Kernel Modules
   Loaded: loaded (/usr/lib/systemd/system/systemd-modules-load.service; static)
   Active: failed (Result: exit-code) since Sat 2015-12-26 07:57:20 UTC; 5h 1min ago
     Docs: man:systemd-modules-load.service(8)
           man:modules-load.d(5)
 Main PID: 1006 (code=exited, status=1/FAILURE)

Dec 26 07:57:20 dom0 systemd-modules-load[1006]: Module 'xen_evtchn' is builtin
Dec 26 07:57:20 dom0 systemd-modules-load[1006]: Module 'xen_gntdev' is builtin
Dec 26 07:57:20 dom0 systemd-modules-load[1006]: Module 'xen_gntalloc' is builtin
Dec 26 07:57:20 dom0 systemd-modules-load[1006]: Failed to find module 'evtchn'
Dec 26 07:57:20 dom0 systemd-modules-load[1006]: Failed to find module 'gntdev'
Dec 26 07:57:20 dom0 systemd-modules-load[1006]: Failed to find module 'netbk'
Dec 26 07:57:20 dom0 systemd[1]: systemd-modules-load.service: main process exited, code=exited, status=1/FAILURE
Dec 26 07:57:20 dom0 systemd[1]: Failed to start Load Kernel Modules.
Dec 26 07:57:20 dom0 systemd[1]: Unit systemd-modules-load.service entered failed state.
```

File where modules are demanded (package xen-runtime-4.6):

```
[root@dom0 udev]# cat /usr/lib/modules-load.d/xen.conf
xen-evtchn
xen-gntdev
xen-gntalloc
xen-blkback
xen-netback
xen-pciback
evtchn
gntdev
netbk
blkbk
xen-scsibk
usbbk
pciback
xen-acpi-processor
blktap2
```

**Comment by Rudd-O** [comment]
Thanks!

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `xen-4.6.1-15.fc21` has been pushed to the `r3.1` testing repository for the Fedora `fc21` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.1-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-vmm-xen/compare/2d284fc593110a18843574ac0c61d52cfa2a4ce9...c1f91549346b5b85dea688b9e095dd52457fa20c

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `xen-4.6.1-15.fc22` has been pushed to the `r3.1` testing repository for the Fedora `fc22` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.1-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-vmm-xen/compare/2d284fc593110a18843574ac0c61d52cfa2a4ce9...c1f91549346b5b85dea688b9e095dd52457fa20c

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `xen-4.6.1-15.fc23` has been pushed to the `r3.1` testing repository for the Fedora `fc23` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.1-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-vmm-xen/compare/2d284fc593110a18843574ac0c61d52cfa2a4ce9...c1f91549346b5b85dea688b9e095dd52457fa20c

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `xen-4.6.1-15.fc20` has been pushed to the `r3.1` testing repository for dom0.
To test this update, please install it with the following command:
```
sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-vmm-xen/compare/2d284fc593110a18843574ac0c61d52cfa2a4ce9...c1f91549346b5b85dea688b9e095dd52457fa20c

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `xen_4.6.1-17+deb8u1` has been pushed to the `r3.1` testing repository for the Debian `jessie` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `jessie-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-vmm-xen/compare/2d284fc593110a18843574ac0c61d52cfa2a4ce9...a95d5db154ca4bec8c8e6fe392fdd027afb984cc

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `xen_4.6.1-17+deb9u1` has been pushed to the `r3.1` testing repository for the Debian `stretch` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `stretch-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-vmm-xen/compare/2d284fc593110a18843574ac0c61d52cfa2a4ce9...a95d5db154ca4bec8c8e6fe392fdd027afb984cc

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `xen_4.6.1-17+deb7u1` has been pushed to the `r3.1` testing repository for the Debian `wheezy` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `wheezy-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-vmm-xen/compare/2d284fc593110a18843574ac0c61d52cfa2a4ce9...a95d5db154ca4bec8c8e6fe392fdd027afb984cc

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `xen-4.6.1-20.fc20` has been pushed to the `r3.1` stable repository for dom0.
To install this update, please use the standard update command:
```
sudo qubes-dom0-update
```
Or update dom0 via Qubes Manager.

[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-vmm-xen/compare/2d284fc593110a18843574ac0c61d52cfa2a4ce9...7644813eaa6a77d1106dcda932edbda93c042cce

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `xen-4.6.1-20.fc21` has been pushed to the `r3.1` stable repository for the Fedora `fc21` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-vmm-xen/compare/2d284fc593110a18843574ac0c61d52cfa2a4ce9...7644813eaa6a77d1106dcda932edbda93c042cce

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `xen-4.6.1-20.fc22` has been pushed to the `r3.1` stable repository for the Fedora `fc22` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-vmm-xen/compare/2d284fc593110a18843574ac0c61d52cfa2a4ce9...7644813eaa6a77d1106dcda932edbda93c042cce

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `xen-4.6.1-20.fc23` has been pushed to the `r3.1` stable repository for the Fedora `fc23` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-vmm-xen/compare/2d284fc593110a18843574ac0c61d52cfa2a4ce9...7644813eaa6a77d1106dcda932edbda93c042cce

**Comment by Sen-Dion** [comment]
For some unknown reason this problem still lurking in Qubes 3.2:
```
$ cat /etc/redhat-release 
Qubes release 3.2 (R3.2)

dom0$ systemctl status systemd-modules-load.service
        systemd-modules-load.service - Load Kernel Modules
         Loaded: loaded (/usr/lib/systemd/system/systemd-modules-load.service; static; vendor preset: disabled)
         Active: failed (Result: exit-code) since Sat 2016-10-29 11:30:18 EDT; 40min ago
           Docs: man:systemd-modules-load.service(8)
                 man:modules-load.d(5)
        Process: 419 ExecStart=/usr/lib/systemd/systemd-modules-load (code=exited, status=1/FAILURE)
       Main PID: 419 (code=exited, status=1/FAILURE)

dom0$ sudo /usr/lib/systemd/systemd-modules-load
        Module 'xen_evtchn' is builtin
        Module 'xen_gntdev' is builtin
        Module 'xen_gntalloc' is builtin
        Failed to insert 'xen_acpi_processor': No such device

dom0$ cat /usr/lib/modules-load.d/xen.conf
      	xen-evtchn
      	xen-gntdev
      	xen-gntalloc
      	xen-blkback
      	xen-pciback
      	xen-acpi-processor
      	# Not used in Qubes dom0
      	#xen-netback
```

Update of the dom0  
```
dom0$ sudo qubes-dom0-update
```
followed by reboot makes no difference: the problem still shows up.

**Comment by marmarek** [comment]
@Sen-Dion Do you have any more details - like kernel messages? `xen-acpi-processor` module load successfully on all of my systems. Maybe it depends on specific hardware?

**Comment by Sen-Dion** [comment]
```
dmesg -l emerg,alert,crit,err,warn -k
[    0.000000] ACPI: RSDP 0x00000000000FB470 000024 (v02 ACPIAM)
[    0.000000] ACPI: XSDT 0x00000000CFF90100 00005C (v01 081810 XSDT1703 20100818 MSFT 00000097)
[    0.000000] ACPI: FACP 0x00000000CFF90290 0000F4 (v03 081810 FACP1703 20100818 MSFT 00000097)
[    0.000000] ACPI BIOS Warning (bug): Optional FADT field Pm2ControlBlock has zero address or length: 0x0000000000000000/0x1 (20150930/tbfadt-654)
[    0.000000] ACPI BIOS Warning (bug): 32/64X length mismatch in FADT/Gpe0Block: 64/32 (20150930/tbfadt-623)
[    0.000000] ACPI: DSDT 0x00000000CFF90450 00D2FB (v01 A1429  A1429001 00000001 INTL 20060113)
[    0.000000] ACPI: FACS 0x00000000CFFA8000 000040
[    0.000000] ACPI: FACS 0x00000000CFFA8000 000040
[    0.000000] ACPI: APIC 0x00000000CFF90390 00007C (v01 081810 APIC1703 20100818 MSFT 00000097)
[    0.000000] ACPI: MCFG 0x00000000CFF90410 00003C (v01 081810 OEMMCFG  20100818 MSFT 00000097)
[    0.000000] ACPI: OEMB 0x00000000CFFA8040 000072 (v01 081810 OEMB1703 20100818 MSFT 00000097)
[    0.000000] ACPI: SRAT 0x00000000CFF9F450 0000B8 (v01 AMD    FAM_F_10 00000002 AMD  00000001)
[    0.000000] ACPI: HPET 0x00000000CFF9F510 000038 (v01 081810 OEMHPET  20100818 MSFT 00000097)
[    0.000000] ACPI: SSDT 0x00000000CFF9F550 000157 (v01 A M I  POWERNOW 00000001 AMD  00000001)
[    0.024549] ACPI: 2 ACPI AML tables successfully acquired and loaded
[    0.074143] cpu 0 spinlock event irq 25
[    0.074151] Could not initialize VPMU for cpu 0, error -95
[    0.074971] NMI watchdog: disabled (cpu0): hardware events not enabled
[    0.080484] Grant table initialized
[    0.086101] ACPI: Executed 3 blocks of module-level executable AML code
[    0.113716] ACPI Exception: AE_NOT_FOUND, While evaluating Sleep State [\_S2_] (20150930/hwxface-580)
[    0.165944] ACPI: Enabled 2 GPEs in block 00 to 1F
[    0.199861] pci 0000:00:01.0: MSI quirk detected; subordinate MSI disabled
[    0.967121] hpet_acpi_add: no address or irqs in _CRS
[    3.465078] Warning! ehci_hcd should always be loaded before uhci_hcd and ohci_hcd, not after
[    3.506776] CRAT table not found
[    6.778681] audit_printk_skb: 75 callbacks suppressed
[    9.560931] parport_pc parport_pc.956: Unable to set coherent dma mask: disabling DMA
[    9.561099] parport_pc parport_pc.888: Unable to set coherent dma mask: disabling DMA
[    9.561210] parport_pc parport_pc.632: Unable to set coherent dma mask: disabling DMA
[    9.728365] ACPI Warning: SystemIO range 0x0000000000000B00-0x0000000000000B07 conflicts with OpRegion 0x0000000000000B00-0x0000000000000B0F (\SOR1) (20150930/utaddress-254)
[    9.728374] ACPI Warning: SystemIO range 0x0000000000000B00-0x0000000000000B07 conflicts with OpRegion 0x0000000000000B00-0x0000000000000B2F (\SMRG) (20150930/utaddress-254)
[    9.728380] ACPI Warning: SystemIO range 0x0000000000000B00-0x0000000000000B07 conflicts with OpRegion 0x0000000000000B00-0x0000000000000B2F (\_SB_.PCI0.SBRG.ASOC.SMRG) (20150930/utaddress-254)
[   10.381412] k8temp 0000:00:18.3: Temperature readouts might be wrong - check erratum #141
[   10.931774] usb 1-3: Warning! Unlikely big volume range (=3072), cval->res is probably wrong.
[   10.931780] usb 1-3: [5] FU [Mic Capture Volume] ch = 1, val = 4608/7680/1
[   14.089301] audit_printk_skb: 30 callbacks suppressed
[   20.533548] audit_printk_skb: 30 callbacks suppressed
[   39.195469] pciback 0000:02:00.0: Driver tried to write to a read-only configuration space field at offset 0x52, size 2. This may be harmless, but if you have problems with your device:
               1) see permissive attribute in sysfs
               2) report problems to the xen-devel mailing list along with details of your device obtained from lspci.
[   61.535051] usb 3-3: Warning! Unlikely big volume range (=3072), cval->res is probably wrong.
[   61.535057] usb 3-3: [5] FU [Mic Capture Volume] ch = 1, val = 4608/7680/1
[   74.210432] pciback 0000:00:13.2: Driver tried to write to a read-only configuration space field at offset 0xa4, size 4. This may be harmless, but if you have problems with your device:
               1) see permissive attribute in sysfs
               2) report problems to the xen-devel mailing list along with details of your device obtained from lspci.
[   74.233820] pciback 0000:00:12.2: Driver tried to write to a read-only configuration space field at offset 0xa4, size 4. This may be harmless, but if you have problems with your device:
               1) see permissive attribute in sysfs
               2) report problems to the xen-devel mailing list along with details of your device obtained from lspci.
[   82.252978] audit_printk_skb: 6 callbacks suppressed
[   90.351075] audit_printk_skb: 27 callbacks suppressed
[  111.739792] audit_printk_skb: 3 callbacks suppressed
[  686.489080] audit_printk_skb: 15 callbacks suppressed
[  930.072916] audit_printk_skb: 15 callbacks suppressed
[ 1407.030192] audit_printk_skb: 27 callbacks suppressed
[ 1766.589102] audit_printk_skb: 15 callbacks suppressed
[ 2126.515046] audit_printk_skb: 27 callbacks suppressed
[ 2487.341145] audit_printk_skb: 15 callbacks suppressed
[ 2846.777177] audit_printk_skb: 27 callbacks suppressed

```

**Comment by userqubes** [comment]
I also have a problem

**Comment by Sen-Dion** [comment]
Xen [note](https://wiki.xen.org/wiki/Xen_power_management#Note_about_AMD_CPUs) says that the Power Management is not supported if CPU family is less than 16.
```
dom0$ lscpu | grep family
CPU family:          15
dom0$ xl info | grep xen_version
xen_version        : 4.6.1
```
Follow up questions:
1. Does the same note apply to Xen 4.6?
2. Is it the reason, why `xen-acpi-processor`  fails to load? How to confirm such assumption?
3. Why `xl dmesg` says nothing about such incompatibility?

**Comment by marmarek** [comment]
This is interesting, because I have one machine with `cpu family` 6 (it is Core2 Duo), and `xen-acpi-processor` module loads just fine.

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `xen_2001:4.6.1-20+deb8u1` has been pushed to the `r3.1` stable repository for the Debian `jessie` template.
To install this update, please use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-vmm-xen/compare/2d284fc593110a18843574ac0c61d52cfa2a4ce9...7644813eaa6a77d1106dcda932edbda93c042cce

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `xen_2001:4.6.1-20+deb9u1` has been pushed to the `r3.1` stable repository for the Debian `stretch` template.
To install this update, please use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-vmm-xen/compare/2d284fc593110a18843574ac0c61d52cfa2a4ce9...7644813eaa6a77d1106dcda932edbda93c042cce

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `xen_2001:4.6.1-17+deb7u1` has been pushed to the `r3.1` stable repository for the Debian `wheezy` template.
To install this update, please use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-vmm-xen/compare/2d284fc593110a18843574ac0c61d52cfa2a4ce9...7644813eaa6a77d1106dcda932edbda93c042cce
