### ISSUE TITLE
debian-8 template does not run /rw/config/rc.local

### ISSUE THREAD

**Issue by wwaites** [QubesOS/qubes-issues#1548]
changing the /etc/rc.local as follows fixes this:

    if test -f /rw/config/rc.local; then
	    . /rw/config/rc.local
    else
	    exit 0
    fi

should this be changed in the template builder or simply documented?

**Comment by marmarek** [comment]
As noted [here](https://www.qubes-os.org/doc/config-files/), you need to make `/rw/config/rc.local` executable (`chmod +x`) to enable it.

**Comment by evilaliv3** [comment]
@marmarek on debian 8 template it sems that /etc/rc.local does simply contain ```exit 0```.

Is this probably a regression?

**Comment by evilaliv3** [comment]
@marmarek i've reinstalled both fedora-26 and debian-9 templates and it seems that the /rc/config/rc.local (which is executable) of the instances that use those templates is not automatically executed; what could be the case?

**Comment by evilaliv3** [comment]
Actually it seems that /etc/rc.local is missing inside the template. Is this possible?
