### ISSUE TITLE
R3.2 live image

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#1552]
The R3.1-alpha1 does not have full R3.1 features, especially it doesn't include:
- [ ] Fedora 23 template (easy)
- [ ] management stack (not really useful on Live system - but see below)
- [ ] Whonix integration (could use mgmt stack for installation - but for that we need "offline mode" support in mgmt stack, otherwise it will not work in chroot during image build)
- [ ] USB VM integration (not so easy when system started out of USB...)

The Live image wasn't released as part of R3.1-rc1, exactly because of those missing parts, we need to get them for R3.1-rc2.

**Comment by marmarek** [comment]
Something already done here:
https://github.com/marmarek/qubes-installer-qubes-os/tree/efi-refind-wip-live

Remaining problems: 
- [ ] uncompressed image is about 16GB!
- [ ] salt doesn't really work with offline mode yet (code not pushed yet, not finished)

**Comment by unman** [comment]
@marmarek I dont know if you want to scotch this and open a new issue for 3.2 - is the GSOC candidate going to work on this? Or update this one for 3.2.

**Comment by marmarek** [comment]
Accepted GSoC projects will be announced May 4-th. In any case, this should be rather about R3.2 Live image, or even R4.0.

**Comment by mfc** [comment]
from [qubes-users mailing list](https://groups.google.com/d/msg/qubes-users/kcB3BTNKny0/3B9UtcfsCgAJ):

```
I had some enforced spare time last week and dusted off some old Live
images for r3.2. They need tidying up but are usable now.

There are two iso images, suitable for burning to DVD or USB.
Both use Debian templates.
The smaller (2GB) is pretty vanilla, with some additional non-free
drivers for wifi adapters.
The larger (2.4GB) has a TorVM, and Tor Browser in an online qube.
There are restrictive iptables on sys-net and TorVM, and MAC spoofing
set on sys-net. The offline qube has libre office and veracrypt
installed.

The menu system is simple, and wont update if you create new qubes.
You'll need to use 'qvm-run -a <new> <program>', or practice working with
the mysteries of xdg menus.

Both images will run(sort of) in 4GB RAM - 8 is better.

If you use DVD then get used to the sound of the disc thrashing. The
faster DVD drive you have the better. (That said they work reasonably well
on an old MacBook with 8GB RAM.) You also need patience - generally it
seems better to start new qubes discretely.

Running from USB is fine. If you have ample RAM you'll forget it's a
live system, unless you hammer the (limited) free disk space.

Both images are available from http://qubes.3isec.org - hashes and
signatures to check included.

I hope to have updated versions ready for 4.0-rc2, along with a tidy build
system, and (maybe) an installer.

Cheers

unman
```

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
