### ISSUE TITLE
Make deb.qubes-os.org accessible over HTTPS

### ISSUE THREAD

**Issue by mig5** [QubesOS/qubes-issues#1553]
Side note to #1539 - is there any chance of getting https://deb.qubes-os.org to work for Debian APT repo (not just plaintext)? I get 404s over HTTPS.

Or alternatively, to mirror the deb repo to mirror.kernel.org as well as the main Qubes repo already is.

Just nice to have if not too difficult to implement.

Thanks!

**Comment by marmarek** [comment]
Will do, @woju just updated the configuration, will be there tomorrow.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?
