### ISSUE TITLE
draw big poster visualising different code paths while creating/loading QubesVM

### ISSUE THREAD

**Issue by woju** [QubesOS/qubes-issues#1560]
Things to include:
- differences between loading from XML and creating out of thin air
- all the loading stages
- what happens, when `xml` is `None`
- `events_enabled` flipping

I did a preliminary version some time ago and probably have draft lying somewhere around my desk, but it is possible it ended up in rubbish bin.

**Comment by marmarek** [comment]
IMO this is still useful thing.
