### ISSUE TITLE
Documentation for dual-boot setup

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#1564]
Currently grub config generation have disabled handling other systems. Mostly because of https://github.com/QubesOS/qubes-secpack/blob/master/QSBs/qsb-020-2015.txt

We need some documentation how to add such entries manually...

**Comment by axon-qubes** [comment]
I'm afraid I really don't know enough about this to write good documentation for it. Adding "Help Wanted" tag.

**Comment by marmarek** [comment]
Just for reference: [related post](https://groups.google.com/d/msgid/qubes-users/20151230110906.GA921%40mail-itl)

**Comment by mfc** [comment]
this is already documented here: https://micahflee.com/2014/04/dual-booting-qubes-and-ubuntu-with-encrypted-disks/

**Comment by axon-qubes** [comment]
Can someone more knowledgeable than me confirm whether that's up-to-date? If so, maybe we can ask Micah for permission to convert it to Markdown and add it to the docs.

**Comment by marmarek** [comment]
Looks up to date. The most important part (the only one specific to Qubes OS rather than any other multi-boot setup) is "Fixing Grub" chapter.

**Comment by unman** [comment]
That isn't a complete answer and it only handles one case where the other OS has boot loader installed on a partition. This wont be the case for most users who want to install qubes and already have another distro installed.
I'm writing up some notes which cover more cases. I'll post them tomorrow when finished.

**Comment by marmarek** [comment]
Thanks for writing that docs!

**Comment by shaaati** [comment]
Not sure if this is the right place to mention this but I am currently considering Qubes OS for personal usage and, while browsing the docs, found that the part about multibooting is not up to date.

From what I understood so far Qubes OS supports UEFI boot since 3.1 and the multiboot doc has been written with 3.0 in mind where a legacy MBR setup was still necessary. The docs should probably be updated to reflect the new situation.

**Comment by andrewdavidwong** [comment]
@shaaati: Thanks for the heads up. I've [removed](https://github.com/QubesOS/qubes-doc/commit/915a1347c843649a971af35f74e27c85b970badc) that section from the doc.
