### ISSUE TITLE
migrate "unofficial" IRC channel to tor-friendly network

### ISSUE THREAD

**Issue by mfc** [QubesOS/qubes-issues#1571]
currently, `#qubes` on `irc.freenode.net` is the unofficial QubesOS IRC channel according to the [Qubes website](https://www.qubes-os.org/help/).

freenode blocks tor connections. given that Qubes recommends users use torified whonix gateway for network traffic, it is weird to point them to a channel that they cannot access.

The Tor Project's [IRC channel](https://www.torproject.org/about/contact.html.en) is on [OTFC](http://www.oftc.net/), as is [Tails](https://tails.boum.org/support/index.en.html) and [Whonix](https://www.whonix.org/wiki/Support#Free_Support). 

It probably makes sense to instead advertise a `#qubes` channel on OTFC, which allows [torified connections](http://www.oftc.net/Tor/).

**Comment by adrelanos** [comment]
We at Whonix have problems with OTFC and blocking Tor users also. Ticket:
[Migrating from IRC OFTC to Tor friendly IRC network](https://phabricator.whonix.org/T361)

**Comment by mfc** [comment]
do Tails and Tor Project face any issues with OTFC? I would find it surprising that they use OTFC if it is blocking users.

**Comment by adrelanos** [comment]
Not really specific to projects. HulaHoop user recently reported this
issue. I've experienced this issue myself not too long ago.

It's very much unlikely a Whonix specific issue. The connection works,
just the server rejects the user with the reason using a blacklisted IP.

I don't know what these project's workarounds are.

**Comment by mfc** [comment]
sounds like it is worth pinging Secure Desktops about it?

**Comment by mfc** [comment]
never mind just saw the new threads on `tor-talk`:

https://lists.torproject.org/pipermail/tor-talk/2016-January/039812.html
https://lists.torproject.org/pipermail/tor-talk/2016-January/039818.html

**Comment by cfcs** [comment]
OFTC on the other hand do not have DHE, so pick your poison.
I think Freenode are working on their Tor support.

**Comment by mfc** [comment]
FYI Tails is moving to Riseup's hosted IRC chatrooms:

https://mailman.boum.org/pipermail/tails-dev/2016-January/010005.html

info here: https://help.riseup.net/en/chat

**Comment by adrelanos** [comment]
There is confirmation now, that OFTC causes issues for other users also:
https://lists.torproject.org/pipermail/tor-talk/2016-January/039823.html

> I think Freenode are working on their Tor support.

They are doing that for years, yet I have not noticed any form of improvement and having greater issues connecting to freenode over Tor than OFTC.

**Comment by adrelanos** [comment]
Michael Carbone:
> FYI Tails is moving to Riseup's hosted IRC chatrooms:
> 
> https://mailman.boum.org/pipermail/tails-dev/2016-January/010005.html
> 
> info here: https://help.riseup.net/en/chat

Riseup only provides Jabber. Not IRC.

**Comment by mfc** [comment]
correct I was mistaken, they host multi-user chatrooms not IRC. Functionality seems equivalent though, the Tails folks seemed to find no problem with it.

**Comment by adrelanos** [comment]
They're using it for developer chat set up by appointment. Not public
chat where people idle and sometimes chat. I think that makes a difference.

The question is if there are any clients that would provide the comfort
of having it run almost all the day. And if the type of IRC user
community would be willing to switch to jabber. In worst case, IRC plus
jabber would exist.

**Comment by mfc** [comment]
not sure what the difference is idling on jabber vs IRC.

however all users would need to have riseup.net jabber accounts I think, which is a much larger issue. so we can scrap that idea.

**Comment by adrelanos** [comment]
> not sure what the difference is idling on jabber vs IRC.

If you actively used IRC clients for years, and then tried to do the same with Jabber clients, you will know. I haven't seen any community public support channel move to Jabber yet. (It's probably not the protocol that lacks something, but the clients.)

**Comment by adrelanos** [comment]
Jabber, as far as I observed it, always needs users to register an account. Accounts on IRC are most times optional. Maybe that's one point why it's less popular for public chat.

**Comment by bnvk** [comment]
@mfc I think what @adrelanos is talking about is how a lot (most?) users in an IRC room, are not actually *there* meaning online, but are rather "in the room" still. This is because a lot of people run screen or tmux from a server so can turn off their laptop but still get messages from people at the IRC identity!

**Comment by mfc** [comment]
OTFC works fine for me, though it has a self-signed cert. Can't even connect to freenode because of Tor blocking. I propose for now promoting using OTFC and go from there.

**Comment by mfc** [comment]
changed on website to *OFTC* -- thanks @axon-qubes for correcting.... >.<

if Tor, Whonix, Tails moves somewhere else we can always change it.
