### ISSUE TITLE
dispvm creation always fails

### ISSUE THREAD

**Issue by greenrd** [QubesOS/qubes-issues#1576]
with the same 2 error popups:

    DVM savefile creation failed

and

    Please wait (up to 120s) while the DispVM savefile is being updated

**Comment by marmarek** [comment]
What Qubes version? What template? 
If you're starting DispVM from other VM (not a menu), check qrexec log of that VM (right click on the VM in Qubes Manager, then logs submenu). If from the menu, check `~/.xsession-errors` in dom0.

**Comment by marmarek** [comment]
Not enough info and no response.
