### ISSUE TITLE
Backup: verification process continues running after failure

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#1578]
In Qubes Manager, attempt to restore a backup tarball with the "verify only" option. It might fail with this error message (related: #1577, #1471):

```
    ERROR: ERROR: invalid hmac for file /var/tmp/restore_[...]:
    [...]
    Is the passphrase correct?
    Partially restored files left in /var/tmp/restore_*, investigate them and/or clean them up
```

The progress bar quickly finishes, the user can then acknowledge the message, and the window will close. However, it seems that the process continues running for some time in the background, as evidenced by high CPU usage and the whole system slowing to a crawl (see #1288). In general, if a status bar visually depicts the progress of some process to the user, it should do so truthfully, and closing the window associated with that process should coincide with that process ending (see #1479).

**Comment by axon-qubes** [comment]
If some sort of cleanup process *must* run when (or after) the verification fails, then it would be good to display an appropriate message and progress bar (if possible) to the user. For example:

    Cleaning up failed restore attempt. Please wait.
    [=================>                           ]

**Comment by marmarek** [comment]
There is a code to kill background tasks when the operation is canceled (https://github.com/QubesOS/qubes-core-admin/blob/master/core/backup.py#L109-L114). Probably the same should be done on failure.

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
