### ISSUE TITLE
Qubes dom0 sees only 50% of RAM on Thinkpad X220

### ISSUE THREAD

**Issue by mig5** [QubesOS/qubes-issues#1584]
I just installed Qubes 3.1 rc1 on a Thinkpad X220. It has 8GB of RAM (as seen in the BIOS, and in the Qubes HCL report). 

However, if I run `free -m` in dom0, or look at memory in Qubes Manager UI, the dom0 only sees 4GB RAM!

What might cause this?

[dom0.free.txt](https://github.com/QubesOS/qubes-issues/files/77878/dom0.free.txt)
[Qubes-HCL-LENOVO-4290CTO-20160105-111822.yml.txt](https://github.com/QubesOS/qubes-issues/files/77879/Qubes-HCL-LENOVO-4290CTO-20160105-111822.yml.txt)

**Comment by marmarek** [comment]
`free -m` only report dom0 memory, not the whole system. It is intended to limit dom0 to 4GB (see #1313 for details).

**Comment by mig5** [comment]
Phew. Thanks :)
