### ISSUE TITLE
insert control-alt-delete

### ISSUE THREAD

**Issue by wayzard** [QubesOS/qubes-issues#1585]
HVM domUs are not responding to the accepted key combination (control-alt-home according to the docs) to receive a control-alt-delete signal while the HVM desktop's window has focus.

Qubes Tools for Windows was not installed. (In some scenarios, they cannot be installed on a system.)

In cases where a system requires control-alt-delete to enter a login screen, this renders a guest system unusable.
As a less important addition, similar considerations may also be needed for other "control-alt-" key combos (like control-alt-F1 on Linux domUs).

Qubes 3.1RC

**Comment by wayzard** [comment]
Not sure why this is "minor" priority. To emphasize, many Windows distros (including almost all Windows Server versions) are inaccessible after installation. 

I tried the following as a workaround (while 6 was DomID of Windows). Not surprisingly, it failed, presumably because qemu is not on these systems:
`#sudo virsh send-key 6 KEY_LEFTCTRL KEY_LEFTALT KEY_DELETE`
`error : this function is not supported by the connection driver: virDomainSendKey`

If there are any other work arounds, it would be good to know in the meantime...

**Comment by marmarek** [comment]
Try ctrl+alt+ins

**Comment by wayzard** [comment]
ctrl+alt+ins does not work.
Actually, various related hotkeys need to be disabled in each Desktop Environment:  ctr+alt+ins in KDE;  ctrl+alt+home in XFCE.
But no, `ctrl+alt+ins` also does not work.

WORKAROUND (not ideal): 
1) disable `/etc/systemd/system/ctrl-alt-del.target` (if it exists)
2) disable any ctrl+alt+del hotkey in the DE
3) type ctrl+alt+del for HVM window with focus

I am not sure where or how the `ctrl+alt+home` (or `ctrl+alt+ins`) implementation was supposed to be. In the DE or closer to raw console input or something else?
Either way, this may need an update: `www.qubes-os.org/doc/windows-tools-3/`

**Comment by marmarek** [comment]
Maybe a better hotkey would be ctrl+alt+win+del (essentially the same as original, but with win)? Or maybe virtualbox approach: right ctrl + del (or "host key" + del)?

The current ctrl+alt+ins is implemented in windows tools, so indeed it will not work without them...

/cc @omeg @woju

**Comment by omeg** [comment]
ctrl-alt-home translation to CAD is performed by the gui agent in Windows Tools. If the tools are not installed in the HVM, keyboard input is not translated. Customization of the shortcut is planned if the time allows, but maybe a better solution would be to synthesize CAD from the gui daemon for cases where guest tools are not present? It's true that server editions require CAD to log in to even install guest tools. Still, special casing such stuff in the gui daemon seems like a bad idea...

**Comment by perkooo** [comment]
Hi,
I have the same problem when I join my active directory.
Stuck at CAD, I tried all keys combination and disabled also hotkey in Qubes.
The solution which worked for me : 
When I am on Windows loggins (asking for CAD)
- Set EN keyboard
- Show visual keyboard
- Click on the virtual keyboard the combination CTRL, ALT and DEL.

Not the best solution but for the moment...

**Comment by perkooo** [comment]
In order to add some informations to my last post : 
I have a french keyboard (AZERTY, not QWERTY), this might be the problem why CTRL + ALT + HOME is not working.

Thanks for the amazing job you are all doing, this is one of the best OS that I tried :)

**Comment by SietsevanderMolen** [comment]
For what it's worth, I need to start my Windows HVM in debug mode, and then press CTRL + ALT + HOME in the debug screen (which only shows the 'Starting Windows') screen to be able to login.

**Comment by MegaTraveller** [comment]
Same Problem here, on a german WIn 7 Pro, after Domain Join it is impossible to login. I tried the tip from @wayzard but it does not work for me :( On-Screen-Keyboard is also no help.

**Comment by MegaTraveller** [comment]
@SietsevanderMolen Thanks for that Tip, that worked like a charm :)

**Comment by faircopy** [comment]
This is my use case:
- Qubes 3.2
- Windows Server 2016 standalone HVM

This is how I enabled passing Ctrl+Alt+Delete to the Windows HVM:
Qubes menu → System Tools → Keyboard → "Application Shortcuts" tab → Select the line "xflock4" - "Ctrl+Alt+Delete" → Click the "Remove" button

After removing the keyboard shortcut, Windows recognizes the Ctrl+Alt+Delete combination just like any other key press when the HVM's window is active.

---

@SietsevanderMolen's suggestion above did not work for me.

I tried:
Qubes menu → Qubes VM Manager → Stop Windows VM if running → Right click on Windows VM → VM Settings → On the "Basic" tab, tick the "Run in debug mode" checkbox → Click the "OK" button → Start Windows VM

No debug window appeared for me, and pressing Ctrl+Alt+Home with the Windows HVM window active resulted in the "Move windows to previous workspace" action which is defined in the XFCE Window Manager settings.

**Comment by TFQOS** [comment]
A trick is to press the Shift key 5 times to activate the Sticky Keys mode (https://en.wikipedia.org/wiki/Sticky_keys).

Thus to send the Ctrl-Alt-Suppr sequence to the VM:
- Press the Shift key 5 times
- Answer "Yes"
- Press (and release) Ctrl
- Press (and release) Alt
- Press (and release) Delete

Worked on Qubes R4.0 and Windows Server 2016 as HVM.

**Comment by brendanhoar** [comment]
As it is now, under R4 current testing, with QWT installed, Windows 7 doesn't accept ctrl-alt-home as ctrl-alt-del. ctrl-alt-windows-del does not work either.

However, sometimes the delete key becomes permantly equivalent to ctrl-alt-delete, so any use of the delete key gives the windows security screen.

It's somewhat maddening and I haven't been able to figure out why.

On screen keyboard doesn't show any stuck keys.

Brendan

**Comment by bowtiediguana** [comment]
@andrewdavidwong I am affected by this issue when installing Windows Server 2019 on Qubes 4.0 using https://github.com/elliotkillick/qvm-create-windows-qube and the i3wm

**Comment by bowtiediguana** [comment]
Remote Desktop is not enabled by default in the answer file so I cannot log in on port 3389 with an rdesktop tool from another qube ether.

**Comment by bowtiediguana** [comment]
`sudo systemctl mask ctrl-alt del` in dom0 worked
