### ISSUE TITLE
UX improvements to bad password in "Restore VMs from backup" tool

### ISSUE THREAD

**Issue by bnvk** [QubesOS/qubes-issues#1589]
Currently, when trying to perform a VM backup, and a user enters an incorrect password, they are given the following pop-up window:

```
Restore error!
Corrupted backup header (hmac verification failed). Is the password correct?
```

This text can be made more user friendly as `Corrupted backup header (hmac verification failed).` is highly confusing to non-crypto engineer users. I propose the following:

```
Error Restoring VM
The password you entered appears to be incorrect!
```

Additionally, if a user enters the incorrect password, the original backup window proceeds to the 2nd step `VMs to restore` except all the columns are blank (due to the password failing). The user must then click on the `< Back` button and manually delete, re-enter a second attempt for the password. This can be improved by simply staying on the original screen, and deleting the wrongly entered password from those input fields!

**Comment by marmarek** [comment]
That error may also mean that backup is corrupted...
