### ISSUE TITLE
qvm-block treats system disks as attachable block devices

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#1600]
`qvm-block` and Qubes Manager both treat the disk(s) on which Qubes is installed as attachable block devices:

```
[user@dom0 ~]$ qvm-block -l
dom0:sda     <name>
dom0:sdb     <name>
```

In Qubes Manager, these disks are available as options to attach to VMs.

`sda` and `sdb` are in a RAID1 configuration, with an encrypted LUKS volume on top, and Qubes installed in that volume.

I have not attempted to attach `sda` or `sdb` to any VM, for obvious reasons.

**Comment by axon-qubes** [comment]
LUKS volumes on secondary internal disks are also treated the same way:

```
[user@dom0 ~]$ qvm-block -l
dom0:dm-2     luks-<UUID>
```

**Comment by axon-qubes** [comment]
Does anything bad happen if a user accidentally clicks on one of these options in the Qubes Manager "attach block devices" list?

If so, then I think this is pretty serious (but mainly a UI issue). It's very easy to slip and misclick something in the Qubes Manager menu, and the user currently has no way to protect themselves from such a mistake, even if they're fully aware that those options are things they never want to click. If there's any simple, easy-to-implement solution that allows users to hide all dom0 devices from this menu, or something like that, it would be a significant improvement.

**Comment by axon-qubes** [comment]
Potentially easier way to take care of this: Add a confirmation box.
```
Are you sure you want to attach <device-name> to <vm-name>?
```

**Comment by marmarek** [comment]
I guess the RAID is /dev/md0 or sth like this, right? Devices used by anything theoretically shouldn't be included. It is checked based on `/sys/block/sda/holders`. But apparently there is a bug in that code...
Check in udev database: `udevadm info -q all -n sda` and look for `QUBES_EXPOSED` variable. If it is `0`, but device is still visible, I think I know where the problem is.

**Comment by axon-qubes** [comment]
> I guess the RAID is /dev/md0 or sth like this, right?

Yes, exactly.

> Check in udev database: `udevadm info -q all -n sda` and look for `QUBES_EXPOSED` variable.

```
$ udevadm info -q all -n sda | grep QUBES_EXPOSED
E: QUBES_EXPOSED=1
```

**Comment by marmarek** [comment]
On Tue, Jan 12, 2016 at 08:41:18PM -0800, Axon wrote:
> ```
> $ udevadm info -q all -n sda | grep QUBES_EXPOSED
> E: QUBES_EXPOSED=1
> ```

Is the array made of all the disk, or just some partition(s)? Check the
same for the partitions. This may be another case of 2nd point of
https://github.com/QubesOS/qubes-issues/issues/1072#issuecomment-124119309

Basically, the whole disk device (`sda` in this case) should not be
listed if any partition is busy, for whatever reason.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by axon-qubes** [comment]
> Is the array made of all the disk, or just some partition(s)?

Just some partitions.

> Check the same for the partitions.

Indeed:
```
$ udevadm info -q all -n sda1 | grep QUBES_EXPOSED
E: QUBES_EXPOSED=0
$ udevadm info -q all -n sda2 | grep QUBES_EXPOSED
E: QUBES_EXPOSED=0
$ udevadm info -q all -n sda3 | grep QUBES_EXPOSED
E: QUBES_EXPOSED=0
$ udevadm info -q all -n sdb1 | grep QUBES_EXPOSED
E: QUBES_EXPOSED=0
$ udevadm info -q all -n sdb2 | grep QUBES_EXPOSED
E: QUBES_EXPOSED=0
$ udevadm info -q all -n sdb3 | grep QUBES_EXPOSED
E: QUBES_EXPOSED=0
```

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-utils-3.1.9-1.fc21` has been pushed to the `r3.1` testing repository for the Fedora `fc21` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.1-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-linux-utils/compare/29cf44233a8b36d2aabec92947b95e6a9afb2de8...0ff9e5a78546a7e3b48df35e91305459a4e48572

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-utils-3.1.9-1.fc22` has been pushed to the `r3.1` testing repository for the Fedora `fc22` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.1-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-linux-utils/compare/29cf44233a8b36d2aabec92947b95e6a9afb2de8...0ff9e5a78546a7e3b48df35e91305459a4e48572

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-utils-3.1.9-1.fc23` has been pushed to the `r3.1` testing repository for the Fedora `fc23` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.1-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-linux-utils/compare/29cf44233a8b36d2aabec92947b95e6a9afb2de8...0ff9e5a78546a7e3b48df35e91305459a4e48572

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-utils-3.1.9-1.fc20` has been pushed to the `r3.1` testing repository for dom0.
To test this update, please install it with the following command:
```
sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-linux-utils/compare/29cf44233a8b36d2aabec92947b95e6a9afb2de8...0ff9e5a78546a7e3b48df35e91305459a4e48572

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-utils_3.1.9+deb8u1` has been pushed to the `r3.1` testing repository for the Debian `jessie` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `jessie-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-linux-utils/compare/29cf44233a8b36d2aabec92947b95e6a9afb2de8...0ff9e5a78546a7e3b48df35e91305459a4e48572

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-utils_3.1.9+deb9u1` has been pushed to the `r3.1` testing repository for the Debian `stretch` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `stretch-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-linux-utils/compare/29cf44233a8b36d2aabec92947b95e6a9afb2de8...0ff9e5a78546a7e3b48df35e91305459a4e48572

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-utils_3.1.9+deb7u1` has been pushed to the `r3.1` testing repository for the Debian `wheezy` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `wheezy-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-linux-utils/compare/29cf44233a8b36d2aabec92947b95e6a9afb2de8...0ff9e5a78546a7e3b48df35e91305459a4e48572

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-utils-3.1.9-1.fc21` has been pushed to the `r3.1` stable repository for the Fedora `fc21` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-linux-utils/compare/29cf44233a8b36d2aabec92947b95e6a9afb2de8...0ff9e5a78546a7e3b48df35e91305459a4e48572

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-utils-3.1.9-1.fc22` has been pushed to the `r3.1` stable repository for the Fedora `fc22` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-linux-utils/compare/29cf44233a8b36d2aabec92947b95e6a9afb2de8...0ff9e5a78546a7e3b48df35e91305459a4e48572

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-utils-3.1.9-1.fc23` has been pushed to the `r3.1` stable repository for the Fedora `fc23` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-linux-utils/compare/29cf44233a8b36d2aabec92947b95e6a9afb2de8...0ff9e5a78546a7e3b48df35e91305459a4e48572

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-utils-3.1.9-1.fc20` has been pushed to the `r3.1` stable repository for dom0.
To install this update, please use the standard update command:
```
sudo qubes-dom0-update
```
Or update dom0 via Qubes Manager.

[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-linux-utils/compare/29cf44233a8b36d2aabec92947b95e6a9afb2de8...0ff9e5a78546a7e3b48df35e91305459a4e48572

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-utils_3.1.9+deb8u1` has been pushed to the `r3.1` stable repository for the Debian `jessie` template.
To install this update, please use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-linux-utils/compare/29cf44233a8b36d2aabec92947b95e6a9afb2de8...0ff9e5a78546a7e3b48df35e91305459a4e48572

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-utils_3.1.9+deb9u1` has been pushed to the `r3.1` stable repository for the Debian `stretch` template.
To install this update, please use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-linux-utils/compare/29cf44233a8b36d2aabec92947b95e6a9afb2de8...0ff9e5a78546a7e3b48df35e91305459a4e48572

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-utils_3.1.9+deb7u1` has been pushed to the `r3.1` stable repository for the Debian `wheezy` template.
To install this update, please use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-linux-utils/compare/29cf44233a8b36d2aabec92947b95e6a9afb2de8...0ff9e5a78546a7e3b48df35e91305459a4e48572
