### ISSUE TITLE
No internet connection on my laptop

### ISSUE THREAD

**Issue by ckvl22** [QubesOS/qubes-issues#1607]
I don't have a internet connection on my laptop, I think the principal reason is my firmware of my wifi card, it's not on qubes os (because it's not open)

it's : iwlwifi-7260-9.ucode and iwlwifi-7260-8.ucode

I can't download it, because my eternet port on qubes os don't working to.

Tank you for your anwser

**Comment by marmarek** [comment]
Which Qubes version? In R3.1 (release candidate) I see those files present in default template (Fedora 23). We will release second release candidate this week (today?) with a lot bug fixed, so I suggest wait for that version and try it.
