### ISSUE TITLE
Add appmenu for starting Terminal in DispVM

### ISSUE THREAD

**Issue by rootkovska** [QubesOS/qubes-issues#1612]
Useful cases include:

1. "wget | bash" workflows (testing/research)
2. semi-trusted gpg keys signing (create dispvm, qvm-copy master and key to sign, sign, qvm-copy the signed key)
3. generation of sensitive output which requires networking (e.g. proof of freshness for canaries)
4. etc

**Comment by marmarek** [comment]
Would `xterm` be enough? It is somehow tricky for `gnome-terminal`, because that process terminates just after sending a message to `gnome-terminal-server`, so DispVM would be terminated just after starting...

**Comment by rootkovska** [comment]
On Wed, Jan 13, 2016 at 05:36:54AM -0800, Marek Marczykowski-Górecki wrote:
> Would `xterm` be enough? It is somehow tricky for `gnome-terminal`, because that process terminates just after sending a message to `gnome-terminal-server`, so DispVM would be terminated just after starting...
> 
Sure.

**Comment by cfcs** [comment]
I would like to have this for `tmux` (so that accidentally clicking the x button doesn't kill the vm).
I realize not everyone might need that, but does anyone know how to configure what gets run by the dispvm? Is there a switch to `qvm-run` or `qvm-start` ? (should there be?)

**Comment by andrewdavidwong** [comment]
@cfcs, try this (from dom0):
```
sh -c 'echo tmux | /usr/lib/qubes/qfile-daemon-dvm qubes.VMShell dom0 DEFAULT red'
```
If that works for you, you can simply create a custom menu shortcut with that as the commend.

**Comment by cfcs** [comment]
Works like a charm! Thanks @andrewdavidwong

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-dom0-linux-3.2.5-1.fc23` has been pushed to the `r3.2` testing repository for dom0.
To test this update, please install it with the following command:
```
sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-admin-linux/compare/db8aa6cf15f4b4f715de14219b2bacd9ee554876...769e70e76a22381727e9f4ab4b8f2a51c24fa228

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-dom0-linux-3.2.5-1.fc23` has been pushed to the `r3.2` stable repository for dom0.
To install this update, please use the standard update command:
```
sudo qubes-dom0-update
```
Or update dom0 via Qubes Manager.

[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-admin-linux/compare/30aac6b6a801ff48c67d32c0baeb75942f44f3c2...769e70e76a22381727e9f4ab4b8f2a51c24fa228
