### ISSUE TITLE
Permission denied on /dev/uinput in qubes.InputMouse

### ISSUE THREAD

**Issue by rootkovska** [QubesOS/qubes-issues#1613]
The command specified in `/etc/qubes-rpc/qubes.InputMouse` should start with a `sudo` or else the forwarded mouse won't work (despite the policy specifying user=root, there is /dev/uinput permission problem). Possible the same problem applies to qubes.InputKeyboard (not tested).

**Comment by marmarek** [comment]
No, it isn't missing `/dev/uinput` should have permissions set to work also from user.
https://github.com/QubesOS/qubes-app-linux-input-proxy/blob/master/qubes-rpc/qubes-uinput.rules

It works on my system, and also on freshly installed R3.1-rc2. I think there was a bug somewhere there previously, ensure you have the latest version.

**Comment by rootkovska** [comment]
On Wed, Jan 13, 2016 at 05:33:06AM -0800, Marek Marczykowski-Górecki wrote:
> No, it isn't missing `/dev/uinput` should have permissions set to work also from user.
> https://github.com/QubesOS/qubes-app-linux-input-proxy/blob/master/qubes-rpc/qubes-uinput.rules
> 
> It works on my system, and also on freshly installed R3.1-rc2. I think there was a bug somewhere there previously, ensure you have the latest version.
> 

I just tested it on a freshly installed 3.1-rc2... It didn't work, I had to add
sudo, and now it works.

**Comment by marmarek** [comment]
Ah, I see. [Known issues](https://www.qubes-os.org/doc/releases/3.1/release-notes/#tocAnchor-1-1-2):
> USB mouse (in case of USB VM) does not work at first system startup (just after completing firstboot). Workaround: restart the system.

**Comment by marmarek** [comment]
Also - check permissions on `/dev/uinput`. Maybe just `sudo udevadm trigger` would be enough to fix it (without system restart)?

**Comment by rootkovska** [comment]
On Wed, Jan 13, 2016 at 05:57:02AM -0800, Marek Marczykowski-Górecki wrote:
> Ah, I see. [Known issues](https://www.qubes-os.org/doc/releases/3.1/release-notes/#tocAnchor-1-1-2):
> > USB mouse (in case of USB VM) does not work at first system startup (just after completing firstboot). Workaround: restart the system.
> 
Nope, it didn't help. I tried connecting the mouse after the 1st reboot.

**Comment by rootkovska** [comment]
With the latest updates on 3.1 this seems to be working without sudo now :)

**Comment by marmarek** [comment]
Apparently this problem [still happens](https://groups.google.com/d/msgid/qubes-users/82584a50-0bb6-6523-90b0-5a4b2883570d%40noses.com). It looks like without `uinput` module loaded `/dev/uinput` is present anyway, but with wrong permissions. Loading `uinput` module fixes the problem.

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-input-proxy-1.0.4-1.fc21` has been pushed to the `r3.1` testing repository for the Fedora `fc21` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.1-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-input-proxy/compare/317031e14f761c97ea23553172feae4cfd75a1aa...cc6fc3a311f0b65b0b6ed66df230e625ee3f18e4

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-input-proxy-1.0.4-1.fc22` has been pushed to the `r3.1` testing repository for the Fedora `fc22` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.1-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-input-proxy/compare/317031e14f761c97ea23553172feae4cfd75a1aa...cc6fc3a311f0b65b0b6ed66df230e625ee3f18e4

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-input-proxy-1.0.4-1.fc23` has been pushed to the `r3.1` testing repository for the Fedora `fc23` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.1-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-input-proxy/compare/317031e14f761c97ea23553172feae4cfd75a1aa...cc6fc3a311f0b65b0b6ed66df230e625ee3f18e4

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-input-proxy-1.0.4-1.fc20` has been pushed to the `r3.1` testing repository for dom0.
To test this update, please install it with the following command:
```
sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-input-proxy/compare/317031e14f761c97ea23553172feae4cfd75a1aa...cc6fc3a311f0b65b0b6ed66df230e625ee3f18e4

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-input-proxy-1.0.5-1.fc21` has been pushed to the `r3.1` stable repository for the Fedora `fc21` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-input-proxy/compare/317031e14f761c97ea23553172feae4cfd75a1aa...920e58e44de25ef98256870187d239dc5f71a7ed

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-input-proxy-1.0.5-1.fc22` has been pushed to the `r3.1` stable repository for the Fedora `fc22` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-input-proxy/compare/317031e14f761c97ea23553172feae4cfd75a1aa...920e58e44de25ef98256870187d239dc5f71a7ed

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-input-proxy-1.0.5-1.fc23` has been pushed to the `r3.1` stable repository for the Fedora `fc23` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-input-proxy/compare/317031e14f761c97ea23553172feae4cfd75a1aa...920e58e44de25ef98256870187d239dc5f71a7ed

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-input-proxy-1.0.5-1.fc20` has been pushed to the `r3.1` stable repository for dom0.
To install this update, please use the standard update command:
```
sudo qubes-dom0-update
```
Or update dom0 via Qubes Manager.

[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-input-proxy/compare/317031e14f761c97ea23553172feae4cfd75a1aa...920e58e44de25ef98256870187d239dc5f71a7ed
