### ISSUE TITLE
Include Qubes Master Key in each template

### ISSUE THREAD

**Issue by rootkovska** [QubesOS/qubes-issues#1614]
Perhaps under `/etc/pki/qubes` or '/usr/share/qubes`? Anyway, it makes whole lot of sense to expose the master key in the templates.

Not sure if we want this also in Dom0?

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `python2-dnf-plugins-qubes-hooks-3.2.8-1.fc23` has been pushed to the `r3.2` testing repository for the Fedora `fc23` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.2-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/8781a5c588f78fbf9577aaa760d914a9f2f035ae...979e2d2bf8a5a697634ce6954247f8fbae5ff438

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `python2-dnf-plugins-qubes-hooks-3.2.8-1.fc24` has been pushed to the `r3.2` testing repository for the Fedora `fc24` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.2-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/8781a5c588f78fbf9577aaa760d914a9f2f035ae...979e2d2bf8a5a697634ce6954247f8fbae5ff438

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-agent_3.2.8-1+deb8u1` has been pushed to the `r3.2` testing repository for the Debian `jessie` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `jessie-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/8781a5c588f78fbf9577aaa760d914a9f2f035ae...979e2d2bf8a5a697634ce6954247f8fbae5ff438

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-agent_3.2.8-1+deb9u1` has been pushed to the `r3.2` testing repository for the Debian `stretch` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `stretch-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/8781a5c588f78fbf9577aaa760d914a9f2f035ae...979e2d2bf8a5a697634ce6954247f8fbae5ff438

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `python2-dnf-plugins-qubes-hooks-3.2.9-1.fc23` has been pushed to the `r3.2` stable repository for the Fedora `fc23` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/d47a89ec76452a4c9efe3b5cbf87157083b3d765...fd8a1167446a8b2e8487d67b9c2888663327a805

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `python2-dnf-plugins-qubes-hooks-3.2.9-1.fc24` has been pushed to the `r3.2` stable repository for the Fedora `fc24` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/d47a89ec76452a4c9efe3b5cbf87157083b3d765...fd8a1167446a8b2e8487d67b9c2888663327a805

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-agent_3.2.10-1+deb8u1` has been pushed to the `r3.2` stable repository for the Debian `jessie` template.
To install this update, please use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/d47a89ec76452a4c9efe3b5cbf87157083b3d765...1a601ddbe9bae11088a78136bfe7cd8a1b3258f1
