### ISSUE TITLE
document that dom0 never updates templates

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#1616]
Templates are intentionally never upgraded on qubes-dom0-update because then all user modifications to the template would be lost. I don't think this is documented somewhere yet? The usual way to update the templates is from within the templates. And if someone wants intentionally get rid of users changes and install a newer template version, the old one has to be uninstalled using yum first.

**Comment by marmarek** [comment]
Wondering where should it be mentioned. Perhaps here: https://www.qubes-os.org/doc/templates/
or maybe here: https://www.qubes-os.org/doc/templates/
Where would you look for such information?

**Comment by adrelanos** [comment]
Both links are the same.

**Comment by adrelanos** [comment]
Anyhow. That page could do.

Not sure if people would find it. But I would primarily use it to direct users to it once the topic comes up somewhere. Better to have a good canonical documentation than investing time to reciting it.

**Comment by marmarek** [comment]
> Both links are the same.

Oops, comment fixed.
