### ISSUE TITLE
Qvm-start Crash

### ISSUE THREAD

**Issue by Truthlighting** [QubesOS/qubes-issues#1617]
I follow the directions in the documentation on creating a windows vm. I then try to run the windows vm and no matter what media I use I get this crash.

The only thing unusual that I can think of is that I just deleted a previous windows vm through the qubes vm manager (a successful installation which did not have this issue).

This is on r3.0 according to qubes vm manager.

**Comment by marmarek** [comment]
You are trying to attach `/dev/cdrom` device, but according to that listing, you don't have such device file. And I don't see any cdrom there...

**Comment by Truthlighting** [comment]
I'm sorry. I saved the entire log of the window and didn't mean to do that. I only meant to save the latest execution. Sorry for the confusion. It won't happen again.

[qvm-start-crash.txt](https://github.com/QubesOS/qubes-issues/files/89484/qvm-start-crash.txt)
Please see this updated log file.

**Comment by marmarek** [comment]
Ah, haven't noticed the last try. There you are using a directory name, not device/image **file** path. You need to use file path there. Take a look at `df` command output to get the device path (first column) mounted there (and preferably unmount it before starting the VM).

**Comment by Truthlighting** [comment]
Thank you so much. 

As you probably are well aware, that's a pretty unfriendly "crash" message and ultimately would be more helpful if your very helpful response was there instead.
