### ISSUE TITLE
/run/media/user missing?

### ISSUE THREAD

**Issue by Truthlighting** [QubesOS/qubes-issues#1620]
As per https://www.qubes-os.org/doc/external-device-mount-point/, /run/media/user should be present in the Fedora VMs when external drives are available.

For example, in dom0 there is a /run/media/truthlighting/storage (among others) but none of the Fedora VMs have a /run/media.

Is this per design?

Qubes R3.0

**Comment by marmarek** [comment]
It will be automatically created, when you mount the volume from some GUI tool (for example by clicking on it in Nautilus file manager).

**Comment by Truthlighting** [comment]
Unfortunately, the volume isn't visible on the left side of the Nautilus pane. I also cannot find /dev/md126p1 in any Fedora vm.

**Comment by Truthlighting** [comment]
Specifically where in Nautilus are you finding it to click on it?

**Comment by marmarek** [comment]
I guess `/dev/md126p1` is a device on your physical disk, right? If so, you need to attach it to a VM first to access it there. Take a look here for example:
https://www.qubes-os.org/doc/stick-mounting/
(it is also possible from Qubes Manager - right click on the target VM and go to "Attach/detach block devices" submenu.
