### ISSUE TITLE
Firstboot: allow to host USB devices in the same VM as NIC devices

### ISSUE THREAD

**Issue by rootkovska** [QubesOS/qubes-issues#1629]
This is a very sensible compromise, I use it on one of my laptop. So, the first boot should include an additional question like this:

-  [ ] Create USB qube holding all USB controllers and devices (sys-usb)
  - [ ] Use the same qubes for both networking and USB devices (sys-devices)

**Comment by marmarek** [comment]
Currently USB ~~VM~~ qube is created as NetVM (type), isn't that enough? For example if you have USB mouse/keyboard IMHO it makes sense to have it separate from `sys-net` (and "normal user" may not be able to make reasonable decision here).

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-mgmt-salt-dom0-virtual-machines-3.1.1-1.fc20` has been pushed to the `r3.1` testing repository for dom0.
To test this update, please install it with the following command:
```
sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-mgmt-salt-dom0-virtual-machines/compare/ba17421e7b131286188c5445aa5bcea57a5e0eaa...616ac0c958c3e75418e3caf758fe1576f0c5b95c

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `anaconda-20.25.16-12.fc20` has been pushed to the `r3.1` testing repository for dom0.
To test this update, please install it with the following command:
```
sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-installer-qubes-os/compare/a0a616733f739ab50c342e72defce2d16468346b...ab1104fa139e47f5509734d11aad89d87a79781b

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-mgmt-salt-dom0-virtual-machines-3.1.1-1.fc20` has been pushed to the `r3.1` stable repository for dom0.
To install this update, please use the standard update command:
```
sudo qubes-dom0-update
```
Or update dom0 via Qubes Manager.

[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-mgmt-salt-dom0-virtual-machines/compare/ba17421e7b131286188c5445aa5bcea57a5e0eaa...616ac0c958c3e75418e3caf758fe1576f0c5b95c

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `anaconda-20.25.16-12.fc20` has been pushed to the `r3.1` stable repository for dom0.
To install this update, please use the standard update command:
```
sudo qubes-dom0-update
```
Or update dom0 via Qubes Manager.

[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-installer-qubes-os/compare/a0a616733f739ab50c342e72defce2d16468346b...ab1104fa139e47f5509734d11aad89d87a79781b
