### ISSUE TITLE
Warn if user has no other keyboard than USB

### ISSUE THREAD

**Issue by rootkovska** [QubesOS/qubes-issues#1630]
Make sure to warn the user that:

1. We cannot properly secure such a system:
  a. either the USB must be in Dom0, which is a total failure of security, generally.
  b. ... or the keyboard must be in USB VM, which provides some security but is far from ideal (e.g. if the USB VM gets compromised from other USB devices, the attacker can sniff and spoof all the keystrokes)

2. If the user decided to use a USB VM for the keyboard (via our qubes.InputKeyboard service), make sure that the user doesn't try to stop the VM, or else will lock themselves out.

**Comment by marmarek** [comment]
Duplicate of #1597 , but this one is much better described, so I'll close the other one.

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `anaconda-20.25.16-12.fc20` has been pushed to the `r3.1` testing repository for dom0.
To test this update, please install it with the following command:
```
sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-installer-qubes-os/compare/a0a616733f739ab50c342e72defce2d16468346b...ab1104fa139e47f5509734d11aad89d87a79781b

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `anaconda-20.25.16-12.fc20` has been pushed to the `r3.1` stable repository for dom0.
To install this update, please use the standard update command:
```
sudo qubes-dom0-update
```
Or update dom0 via Qubes Manager.

[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-installer-qubes-os/compare/a0a616733f739ab50c342e72defce2d16468346b...ab1104fa139e47f5509734d11aad89d87a79781b
