### ISSUE TITLE
Polish letters do not show up correctly in Terminal app on FC23

### ISSUE THREAD

**Issue by rootkovska** [QubesOS/qubes-issues#1631]

**Comment by marmarek** [comment]
Can you paste a screenshot? Or maybe characters do not show at all? In that case, check keyboard layout - by default it is `us` layout and polish letters aren't handled there (obviously).

**Comment by rootkovska** [comment]
![polish-letters-as-junk](https://cloud.githubusercontent.com/assets/10212863/12358437/828950ee-bbad-11e5-9249-e7f87dec0891.png)

I wrote above "źdźbło" :P As you can see the kbd works well, as I could have written these letters here in a Web browser (in the same VM where I tried the Terminal screenshoted above).

**Comment by marmarek** [comment]
Can you show output of `locale`? Is it VM restored from backup, or newly created? The same question for the template for it?

**Comment by rootkovska** [comment]
```
[user@test ~]$ locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

The above is from a new VM created from an original fc23 template.

**Comment by marmarek** [comment]
The same for Debian 8 template

**Comment by rootkovska** [comment]
Additionally: polish letters do no work in Libre Office Writer. Bumping this to Major for this reason...

**Comment by marmarek** [comment]
Really strange - for example on Debian it does work in xterm (properly show UTF-8 encoded polish letters), but not in gnome-terminal in the same VM. On Fedora it doesn't in xterm...

**Comment by marmarek** [comment]
On the other hand - on the system upgraded from R3.0 (including upgrading template from fc21), it works perfectly fine.

**Comment by marmarek** [comment]
Make sure you have polish keyboard layout set in dom0. Then, when VM have polish keyboard layout set (which will be the case by default, because it's copied from dom0) it all works just fine.

Not sure why haven't noticed it earlier...

**Comment by rootkovska** [comment]
Indeed :)
