### ISSUE TITLE
Change the default colors for the Whonix VMs and templates

### ISSUE THREAD

**Issue by rootkovska** [QubesOS/qubes-issues#1633]
By default we use the black color to signalize VMs whose integrity is critical to the user's safety (e.g. templates installed by default), while red to signalize the VMs where the user should remember not to feel too safe. To be consistent with this approach I thus suggest to change the default Whonix coloring (now created by firstboot) to the following:
- black for all the templates
- black for the whonix-gw (protection of the user's identity depends on this being non-compromised)
- ref for the default whonix AppVM based on the whonix-ws template (to warn user not to feel "too safe" while using it).

**Comment by adrelanos** [comment]
Implementing this would be up to @marmarek, I suppose. (I would just
have to update the screenshots in the user documentation accordingly.)

Joanna Rutkowska:
> - black for all the templates

Yes, templates always black sounds like a plan.

> - black for the whonix-gw (protection of the user's identity depends on this being non-compromised)

I guess you meant black for the whonix-gw based ProxyVM. "Overloading" /
re-using the color black for anything other than templates may not be
great. Not a strong opinion. @bnvk what do you think?

> - ref for the default whonix AppVM based on the whonix-ws template (to warn user not to feel "too safe" while using it).

I guess 'ref' is a typo and you meant 'red'. Sounds okay.

**Comment by Aktariel** [comment]
Speaking as a user, the proposed changes make sense to me. I wasn't aware that there was a guideline for color use (documentation opportunity, perhaps?), but thinking of black as "if compromised then screwed" and red as "trust nothing," making the proposed changes to the Whonix VMs sounds good.

Also, y'all need a "Welcome to Qubes here's what things mean!" intro. I realize that this is sort of a specialized OS and most of the people picking it up will have a good sense for Linux distros (hopefully!), but having a high level abstract overview/welcome splash would be great.

**Comment by axon-qubes** [comment]
@Aktariel, is this what you're looking for?
https://www.qubes-os.org/getting-started/

**Comment by marmarek** [comment]
What about using gray for `sys-whonix` Whonix-Gateway ProxyVM? It doesn't overload black templates, but is also some dark color.

**Comment by rootkovska** [comment]
I'd still vote for the black label for the Tor proxyVM -- after all it's a very critical VM and the black color should be saying: "stay away from tinkering with it, deal user!". Like in case of the default templates.

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-mgmt-salt-dom0-virtual-machines-3.1.1-1.fc20` has been pushed to the `r3.1` testing repository for dom0.
To test this update, please install it with the following command:
```
sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-mgmt-salt-dom0-virtual-machines/compare/ba17421e7b131286188c5445aa5bcea57a5e0eaa...616ac0c958c3e75418e3caf758fe1576f0c5b95c

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-mgmt-salt-dom0-virtual-machines-3.1.1-1.fc20` has been pushed to the `r3.1` stable repository for dom0.
To install this update, please use the standard update command:
```
sudo qubes-dom0-update
```
Or update dom0 via Qubes Manager.

[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-mgmt-salt-dom0-virtual-machines/compare/ba17421e7b131286188c5445aa5bcea57a5e0eaa...616ac0c958c3e75418e3caf758fe1576f0c5b95c
