### ISSUE TITLE
Add RSS feed button

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#1638]
The Qubes OS website provides a list of news articles at https://www.qubes-os.org/news/

However, I cannot find any way of subscribing to this list as an RSS feed. As far as I can tell, the only way to be notified that new articles exist is to frequently check that page, which is something that most people (even those very interested in Qubes) are unlikely to do. (Even I wasn't aware of the latest entry until someone else happened to mention it in a GitHub issue.)

@bnvk

**Comment by bnvk** [comment]
@axon-qubes the RSS feed exists, I fixed that in the site re-design. You can [subscribe here](https://www.qubes-os.org/feed.xml) but I should add an easy to discover button- since most browsers don't have "RSS Feed"  buttons anymore, sadly!

**Comment by axon-qubes** [comment]
Oh! My mistake. Thank you for pointing that out to me, @bnvk! Yes, perhaps a button would be good for people like me. :)
