### ISSUE TITLE
printer/printer-settings shortcut missing on new installed 3.1 rc2

### ISSUE THREAD

**Issue by WolfOnGitHub** [QubesOS/qubes-issues#1642]
After new installing 3.1 rc2 or updating 3.0 there are no shortcuts for printing available in templates and VMs. Even the "system-config-printer" command mentioned here https://www.qubes-os.org/doc/network-printer/ seems not existing.

**Comment by axon-qubes** [comment]
The "Printer Settings" now appears to be present in the `fedora-23` template on R3.1. In general, a solution for these sorts of issues is to install any missing programs and either launch them from the command line or create your own custom menu entries. (Note that these are not Qubes-specific tasks.)
