### ISSUE TITLE
Backup: cannot do unencrypted backups

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#1645]
Leaving the password field empty is currently not possible. No matter if the 'encrypt' check box is checked or not. When the password field is empty, the button 'next' is deactivated.

A related issue is, that you can enter a password while the checkbox encrypt is unchecked. That does not make sense and is confusing. That field should ideally disappear then or if that is too hard, at least be deactivated.

Background:
Since I am already using linux cryptsetup/luks, I would like to do unencrypted backups for simplicity. Running into fewer bugs decrypting. Fewer chances for encryption software to mess up making all data unaccessible.

**Comment by marmarek** [comment]
This is intended behavior - even if backup is not encrypted, it is integrity protected, using that password as a key.
