### ISSUE TITLE
sys-net NetworkManager wpa_supplicant

### ISSUE THREAD

**Issue by kestassf** [QubesOS/qubes-issues#1646]
Fresh install of QubesOS 3.1 RC2 doesn't show wifi networks to connect to on network icon (seams to be related to NetworkManager, because iwlist scan works as expected). Wired LAN works ok.
Hardware: Dell Inspiron 17R-5721

On sys-net VM:

    # lspci 
    00:00.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL8101/2/6E PCI Express Fast/Gigabit Ethernet controller (rev 05)
    00:01.0 Network controller: Intel Corporation Centrino Wireless-N 2230 (rev c4)

Starting wpa_supplicant manually (from root) on sys-net fixed the problem for me:

    wpa_supplicant -u -B

**Comment by marmarek** [comment]
Check `journalctl -b -u NetworkManager.service` for any errors.

**Comment by kestassf** [comment]
I've attached command's output (I don't see any errors here):
[journal.txt](https://github.com/QubesOS/qubes-issues/files/93245/journal.txt)
I also checked for for "wpa_supplicant" process, but there is none running (until I start it by hand).

**Comment by axon-qubes** [comment]
I'm assuming this issue has been resolved based on the lack of recent activity. If not, please feel free to re-open it.
