### ISSUE TITLE
qubes-dom0-update needlessly downloads template rpm package(s)

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#1647]
Happened after a fresh installation using a 3.0 RC1 installer DVD. (Original goal was testing the upgrade paths to R3.1.)

It came with a fedora 21 template pre-installed. While running running qubes-dom0-update I noticed, that inside the UpdateVM, the qubes-template-fedora-21 rpm package was being downloaded. Even if it later is not installed over the existing one in dom0, this is still a huge waste of download time, download traffic and disk space.

**Comment by marmarek** [comment]
This was [already fixed](https://github.com/QubesOS/qubes-core-admin-linux/commit/4cab8153174318cb082cb168e030d984326df794) in R3.0-rc2.
