### ISSUE TITLE
USBVM creation / Firstboot: fails when booting from USB HDD

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#1649]
I've installed Qubes R3.1 RC1 to a USB HDD.

(Installed Qubes. Not Live anything.)

(Installer as booted from one USB HDD and installed to another USB HDD.)

During Qubes Firstboot screen, I chose the 'setup USBVM for me' option. After a while, lots of systemd disk I/O errors were spamming my screen.[1] [2] Should be no surprise? When one boots from USB, Qubes has no chance to put the disk it is booted from into the USBVM?

If you can fix it, please fix it. If the fix is too difficult and should be postponed or if this technically cannot be fixed, please do not allow to create an USBVM when booted from USB as a stopgap.

-----

[1] Correlation does not imply causation. I am not 100% sure it was caused by this - since I haven't finished re-installing without choosing that option - but the guess seems plausible, no?
[2] After that, the installation is probably in a not so trivially repairable state.

**Comment by marmarek** [comment]
Related to #1630 (the same about USB keyboard). Generally USB VM option shouldn't be available in such case.

**Comment by adrelanos** [comment]
There is technically no way to someday make this work somehow?

**Comment by marmarek** [comment]
"Someday" = "when we implement storage domain", far in the future...

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `anaconda-20.25.16-12.fc20` has been pushed to the `r3.1` testing repository for dom0.
To test this update, please install it with the following command:
```
sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-installer-qubes-os/compare/a0a616733f739ab50c342e72defce2d16468346b...ab1104fa139e47f5509734d11aad89d87a79781b

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `anaconda-20.25.16-12.fc20` has been pushed to the `r3.1` stable repository for dom0.
To install this update, please use the standard update command:
```
sudo qubes-dom0-update
```
Or update dom0 via Qubes Manager.

[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-installer-qubes-os/compare/a0a616733f739ab50c342e72defce2d16468346b...ab1104fa139e47f5509734d11aad89d87a79781b
