### ISSUE TITLE
Backup should accept a stdin password or a file key

### ISSUE THREAD

**Issue by Rudd-O** [QubesOS/qubes-issues#1653]
Right now there is no way to avoid typing the password in the backup.  This bodes badly for automated backups, where the password is stored in the TCB (dom0) as a keyfile or perhaps piped into the backup program from the calling script.

This feature would make it so easy to do automated backups without having to deal with the cancer that is expect.

Thanks!

**Comment by cfcs** [comment]
Also useful for stuff like this: https://github.com/cfcs/scramlkb

**Comment by Rudd-O** [comment]
Agreed.  No need to use the stupid getpass module.  There's no additional security by demanding reads from a tty.

**Comment by marmarek** [comment]
Take a look at https://github.com/marmarek/qubes-core-admin/pull/11

**Comment by marmarek** [comment]
Fixed in https://github.com/QubesOS/qubes-core-admin/pull/20
