### ISSUE TITLE
qvm-sync-appmenus fails when a shortcut have spaces in the file name

### ISSUE THREAD

**Issue by adrianx64** [QubesOS/qubes-issues#1657]
qvm-sync-appmenus generates an exception when one or more shortcuts in the VM have spaces in its name:
[user@dom0 ~]$ qvm-sync-appmenus fedora-23
Traceback (most recent call last):
  File "/usr/libexec/qubes-appmenus/qubes-receive-appmenus", line 389, in <module>
    main()
  File "/usr/libexec/qubes-appmenus/qubes-receive-appmenus", line 293, in main
    new_appmenus = get_appmenus(vm)
  File "/usr/libexec/qubes-appmenus/qubes-receive-appmenus", line 139, in get_appmenus
    raise QubesException("Error getting application list")
qubes.qubes.QubesException: Error getting application list

The issue can be solved in the script qubes.GetAppmenus, modifying the two first lines and adding the parameter -print0 to "find" command and -0 to "xargs" command like this way:
find /usr/share/applications/ /usr/local/share/applications/ -name '*.desktop' -print0 2>/dev/null | \
         xargs -0 awk '
...

**Comment by marmarek** [comment]
Thanks!

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `python2-dnf-plugins-qubes-hooks-3.1.13-1.fc21` has been pushed to the `r3.1` testing repository for the Fedora `fc21` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.1-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/5570c899b8537619c17b81775bd9f3f4d5c8e8d4...d181cf5cffa8f00cbd899f7c916d9230ddf04b26

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `python2-dnf-plugins-qubes-hooks-3.1.13-1.fc22` has been pushed to the `r3.1` testing repository for the Fedora `fc22` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.1-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/5570c899b8537619c17b81775bd9f3f4d5c8e8d4...d181cf5cffa8f00cbd899f7c916d9230ddf04b26

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `python2-dnf-plugins-qubes-hooks-3.1.13-1.fc23` has been pushed to the `r3.1` testing repository for the Fedora `fc23` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.1-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/5570c899b8537619c17b81775bd9f3f4d5c8e8d4...d181cf5cffa8f00cbd899f7c916d9230ddf04b26

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-agent_3.1.13-1+deb8u1` has been pushed to the `r3.1` testing repository for the Debian `jessie` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `jessie-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/5570c899b8537619c17b81775bd9f3f4d5c8e8d4...d181cf5cffa8f00cbd899f7c916d9230ddf04b26

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-agent_3.1.13-1+deb9u1` has been pushed to the `r3.1` testing repository for the Debian `stretch` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `stretch-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/5570c899b8537619c17b81775bd9f3f4d5c8e8d4...d181cf5cffa8f00cbd899f7c916d9230ddf04b26

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-agent_3.1.13-1+deb7u1` has been pushed to the `r3.1` testing repository for the Debian `wheezy` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `wheezy-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/5570c899b8537619c17b81775bd9f3f4d5c8e8d4...d181cf5cffa8f00cbd899f7c916d9230ddf04b26

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `python2-dnf-plugins-qubes-hooks-3.1.13-1.fc21` has been pushed to the `r3.1` stable repository for the Fedora `fc21` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/5570c899b8537619c17b81775bd9f3f4d5c8e8d4...d181cf5cffa8f00cbd899f7c916d9230ddf04b26

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `python2-dnf-plugins-qubes-hooks-3.1.13-1.fc22` has been pushed to the `r3.1` stable repository for the Fedora `fc22` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/5570c899b8537619c17b81775bd9f3f4d5c8e8d4...d181cf5cffa8f00cbd899f7c916d9230ddf04b26

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `python2-dnf-plugins-qubes-hooks-3.1.13-1.fc23` has been pushed to the `r3.1` stable repository for the Fedora `fc23` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/5570c899b8537619c17b81775bd9f3f4d5c8e8d4...d181cf5cffa8f00cbd899f7c916d9230ddf04b26

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-agent_3.1.13-1+deb8u1` has been pushed to the `r3.1` stable repository for the Debian `jessie` template.
To install this update, please use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/5570c899b8537619c17b81775bd9f3f4d5c8e8d4...d181cf5cffa8f00cbd899f7c916d9230ddf04b26

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-agent_3.1.13-1+deb9u1` has been pushed to the `r3.1` stable repository for the Debian `stretch` template.
To install this update, please use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/5570c899b8537619c17b81775bd9f3f4d5c8e8d4...d181cf5cffa8f00cbd899f7c916d9230ddf04b26

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-agent_3.1.13-1+deb7u1` has been pushed to the `r3.1` stable repository for the Debian `wheezy` template.
To install this update, please use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/5570c899b8537619c17b81775bd9f3f4d5c8e8d4...d181cf5cffa8f00cbd899f7c916d9230ddf04b26
