### ISSUE TITLE
Documentation: merge doc/templates/whonix/ with doc/privacy/whonix/ ?

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#1664]
There are various sub pages in the templates hierarchy ( https://www.qubes-os.org/doc/templates/ ):

* https://www.qubes-os.org/doc/templates/debian/
* https://www.qubes-os.org/doc/templates/whonix/

The Debian template page explains what it's about and how to install it etc.

However, the Whonix template page is not that useful. https://www.qubes-os.org/doc/privacy/whonix/

It primarily links to https://www.qubes-os.org/doc/templates/whonix/. I think it's only existing for historically grown reasons.

Should the contents of https://www.qubes-os.org/doc/templates/whonix/ and https://www.qubes-os.org/doc/privacy/whonix/ be merged?

And then https://www.qubes-os.org/doc/privacy/whonix/ would be abolished. And replaced by https://www.qubes-os.org/doc/templates/whonix/?

/cc @bnvk

**Comment by adrelanos** [comment]
Input required.

/cc @axon-qubes

**Comment by axon-qubes** [comment]
Yes, I think it would make sense to have a central Whonix page (at `/doc/whonix/`), and any subpages could be available from that central page. Currently, we have six different Whonix-related entries in the main table of contents, which could be confusing for users.

@adrelanos: Do you want to do this, or do you want me to do it?

**Comment by adrelanos** [comment]
Please go for it.
