### ISSUE TITLE
Add kernel command line option for Skylake iGPU

### ISSUE THREAD

**Issue by esheltone** [QubesOS/qubes-issues#1668]
We are seeing more and more people on the qubes-users list trying to get their Skylake systems up and running with Qubes.  With pre-4.3 Linux kernels, the following kernel command line option needs to be added to enable the i915 driver for Skylake integrated GPUs (Intel HD Graphics 530, etc):

`i915.preliminary_hw_support=1`

I propose adding this to the default kernel command line for Qubes 3.1 final.  I do not believe it will cause any issues for non-Skylake users, and it will eliminate many problems for, and qubes-users postings from, future Skylake users.

**Comment by marmarek** [comment]
Is is meaningful also on 4.1 kernel? If so, +1 from my side.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by esheltone** [comment]
Yes, it works for 4.1.13, as discussed in this post: https://groups.google.com/d/msg/qubes-users/IllB1PaX5tA/-YA1-h59AwAJ

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `anaconda-20.25.16-12.fc20` has been pushed to the `r3.1` testing repository for dom0.
To test this update, please install it with the following command:
```
sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-installer-qubes-os/compare/a0a616733f739ab50c342e72defce2d16468346b...ab1104fa139e47f5509734d11aad89d87a79781b

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `anaconda-20.25.16-12.fc20` has been pushed to the `r3.1` stable repository for dom0.
To install this update, please use the standard update command:
```
sudo qubes-dom0-update
```
Or update dom0 via Qubes Manager.

[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-installer-qubes-os/compare/a0a616733f739ab50c342e72defce2d16468346b...ab1104fa139e47f5509734d11aad89d87a79781b
