### ISSUE TITLE
Kali linux connection problem

### ISSUE THREAD

**Issue by TNTBOMBOM** [QubesOS/qubes-issues#1674]
i have tried to install kali linux .iso = easy/smooth installation.

but the problem is , how to connect kali linux to the internet?? even tried to connect it with whonix = useless tries. dunno how to make it work , is there instructions on how to make this connection happen ?

also i want to ask if there will be kali template implemented inside qubes which i think its going to be great idea.

**Comment by marmarek** [comment]
On Fri, Jan 22, 2016 at 05:51:31AM -0800, TNT BOM BOM wrote:
> but the problem is , how to connect kali linux to the internet?? even tried to connect it with whonix = useless tries dunno how to make it work , is there instructions on how to make that connection happen ?

Take a look here:
https://www.qubes-os.org/doc/hvm-create/#tocAnchor-1-1-4

> also i want to ask if there there will be kali template implemented inside qubes which i think its going to be great idea

If someone would make one...

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by adrelanos** [comment]
> https://www.qubes-os.org/doc/hvm-create/#tocAnchor-1-1-4

Minor: Your anchor'ed link is broken.

**Comment by axon-qubes** [comment]
Hm, that link seems to be working for me. It takes me to the heading "Setting up networking for HVM domains." Is that not right?

**Comment by marmarek** [comment]
On Sun, Jan 24, 2016 at 02:15:37AM -0800, Axon wrote:
> Hm, that link seems to be working for me. It takes me to the heading "Setting up networking for HVM domains." Is that not right?

It's ok. The link doesn't work with javascript disabled.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by TNTBOMBOM** [comment]
witha instructions on that link i did it to connect to the clearnet = worked good 

but the mistake that i was doing is:- 

i didnt turn-off/on the connection so that IPv4 settings taking its effect. 

if u like i can make a tutorial on how to connect whonix with kali using qubes. (using screenshots).

there have been tutorials on how to connection kail with whonix , but never inside qubes (inside Vbox only).

**Comment by gorgaar** [comment]
TNTBOMBOM, a tutorial of Kali + Whonix + Qubes would be awesome! And a Kali template for Qubes even better!

**Comment by axon-qubes** [comment]
Closing as resolved.

**Comment by curiousgeorge567** [comment]
For the sake of completeness. Would you mind explaining which ipv4 setting you turned off/on? Was it the network connection inside the VM? or was it the Standalone AppVM?

**Comment by TNTBOMBOM** [comment]
Install kali on empty vm through .iso then add vm network info to kali 
manually (ip,netmask,gateway,dns) then after that succeeded connect the 
vm to whonix gateway and should work properly.

Note: be aware that whonix-gateway is not suited for kali applications 
as gateway use hardened firewall which blocks many stuff needed by some 
applications to work properly.

curiousgeorge567:
> For the sake of completeness. Would you mind explaining which ipv4 setting you turned off/on? Was it the network connection inside the VM? or was it the Standalone AppVM?
>
