### ISSUE TITLE
Dolphin file manager not functional in fedora-23-based AppVMs

### ISSUE THREAD

**Issue by mfc** [QubesOS/qubes-issues#1677]
In Fedora 23-based AppVMs, the Dolphin file manager is not listed as an option to be added to the app shortcut menu even when installed (and app menu synced).  

When run from terminal, it provides these errors:

> couldn't create slave: "Cannot talk to klauncher: The name org.kde.klauncher5 was not provided by any .service files"
> "Could not start process Cannot talk to klauncher: The name org.kde.klauncher5 was not provided by any .service files."
> QPixmap::scaled: Pixmap is a null pixmap

and the Dolphin file manager appears displaying these errors ("cannot talk to klauncher...") and is not usable.

Qubes 3.1-rc1

**Comment by marmarek** [comment]
Probably dolphin requires installing a lot of KDE stuff in the template. For example it looks better when additionally installed `plasma-workspace`.

**Comment by adrelanos** [comment]
So this could boil down to an Fedora upstream issue, namely missing
dependencies.

**Comment by andrewdavidwong** [comment]
Is this issue resolved in 3.2? (Would be nice if we could close this since we've moved to Xfce, but since we still officially support KDE, I suppose we can't, unless it's actually been resolved.)

**Comment by marmarek** [comment]
Is it still an issue in Fedora 24?

**Comment by mfc** [comment]
dolphin runs now in fedora-23 and fedora-24, but it still has errors like some missing icons for folder. I don't use it anymore and it doesn't seem to be a problem for others, so I will close this.
