### ISSUE TITLE
xinput: use meaningful names for input proxy devices instead of generic "Forwarded input device"

### ISSUE THREAD

**Issue by taradiddles** [QubesOS/qubes-issues#1679]
Proxied input devices all show up as "Forwarded input device", so the only way to use xinput to list/set props is to use an id number.
Problem: it cana be really cumbersome to find out the corresponding id of a given device (requires comparing outputs of xinput list-props or plugging/unplugging the device).

Example of the virtual core pointer section of "xinput list" in dom0 with an external USB mouse and an external thinkpad keyboard (keyboard + trackpoint):

[...]
Forwarded input device id=14 [slave pointer (2)]
Forwarded input device id=15 [slave pointer (2)]
[...]

I always enable wheel emulation on the trackpoints so that I can quickly scroll vertically (a huge productivity boost btw). For that I need to issue a few "xinput set-props id ..." commands and thus need to find the trackpoint's id. But the output of "xinput list-props 14" and "xinput list-props 15" show almost the same stuff and doesn't show the devices' names.
The trackpoint exhibits a few values different than the mouse so that's a way to identify it and script xinput commands, but I guess there might be identical outputs with other devices and thus no way to find the id other than plugging/unplugging the device and see what id it gets( another problem then is that the ids are not consistent after a reboot).

**Comment by marmarek** [comment]
This requires protocol change in input proxy. There is partial support for protocol extensions, but unfortunately it wasn't completed... This means it will be probably deferred to some further Qubes release.

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-input-proxy-1.0.5-1.fc21` has been pushed to the `r3.1` testing repository for the Fedora `fc21` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.1-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-input-proxy/compare/cc6fc3a311f0b65b0b6ed66df230e625ee3f18e4...920e58e44de25ef98256870187d239dc5f71a7ed

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-input-proxy-1.0.5-1.fc22` has been pushed to the `r3.1` testing repository for the Fedora `fc22` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.1-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-input-proxy/compare/cc6fc3a311f0b65b0b6ed66df230e625ee3f18e4...920e58e44de25ef98256870187d239dc5f71a7ed

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-input-proxy-1.0.5-1.fc23` has been pushed to the `r3.1` testing repository for the Fedora `fc23` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.1-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-input-proxy/compare/cc6fc3a311f0b65b0b6ed66df230e625ee3f18e4...920e58e44de25ef98256870187d239dc5f71a7ed

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-input-proxy-1.0.5-1.fc20` has been pushed to the `r3.1` testing repository for dom0.
To test this update, please install it with the following command:
```
sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-input-proxy/compare/cc6fc3a311f0b65b0b6ed66df230e625ee3f18e4...920e58e44de25ef98256870187d239dc5f71a7ed

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-input-proxy-1.0.5-1.fc21` has been pushed to the `r3.1` stable repository for the Fedora `fc21` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-input-proxy/compare/317031e14f761c97ea23553172feae4cfd75a1aa...920e58e44de25ef98256870187d239dc5f71a7ed

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-input-proxy-1.0.5-1.fc22` has been pushed to the `r3.1` stable repository for the Fedora `fc22` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-input-proxy/compare/317031e14f761c97ea23553172feae4cfd75a1aa...920e58e44de25ef98256870187d239dc5f71a7ed

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-input-proxy-1.0.5-1.fc23` has been pushed to the `r3.1` stable repository for the Fedora `fc23` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-input-proxy/compare/317031e14f761c97ea23553172feae4cfd75a1aa...920e58e44de25ef98256870187d239dc5f71a7ed

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-input-proxy-1.0.5-1.fc20` has been pushed to the `r3.1` stable repository for dom0.
To install this update, please use the standard update command:
```
sudo qubes-dom0-update
```
Or update dom0 via Qubes Manager.

[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-input-proxy/compare/317031e14f761c97ea23553172feae4cfd75a1aa...920e58e44de25ef98256870187d239dc5f71a7ed
