### ISSUE TITLE
Qubes Manager crash if I want to detach a device from a non-existing domain.

### ISSUE THREAD

**Issue by Zrubi** [QubesOS/qubes-issues#1686]
Qubes Manager crash if I want to detach a device from a non-existing domain.
This happened in case of a stopped DVM instance.

**Comment by unman** [comment]
@andrewdavidwong  I believe this issue is resolved in 3.2, and can be closed. (The device is freed from the qube when it closes, and qvm-block generates a warning message if the qube does not exist.)
