### ISSUE TITLE
Create USB VM configuration guide

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#1690]
It should include:
 - how to create USB VM (using management stack): https://groups.google.com/d/msgid/qubes-users/20160125195056.GE1089%40mail-itl
 - what devices are supported and how: https://groups.google.com/d/msgid/qubes-users/20160125012019.GR6251%40mail-itl

**Comment by axon-qubes** [comment]
Should this be replaced or incorporated?
https://www.qubes-os.org/doc/security-guidelines/#tocAnchor-1-1-9

**Comment by marmarek** [comment]
Oh, I didn't know we have this already :) Anyway I think it would be good to have "all about USB" in one place as noted in ticket description. Probably as a separate page (and then link to it from security guidelines)

**Comment by axon-qubes** [comment]
@marmarek: How's that? Anything else we need?

**Comment by marmarek** [comment]
Thanks, looks good :)
