### ISSUE TITLE
Implement vm.shutdown(wait=True)

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#1696]
And replace all loops waiting for VM shutdown with it.

**Comment by marmarek** [comment]
Additionally there should be some timeout, after which VM gets killed.

**Comment by tasket** [comment]
This would really be nice. Putting 'sleep' timers after vm.shutdown == :(

Maybe Qubes API could be more mindful of whether methods are/aren't synchronous and provide parameters to make them sync/async. Actually.... Qubes API could use ref doc, too.

**Comment by marmarek** [comment]
As for API docs, it exists for Qubes 4.0: http://qubes-core-admin.readthedocs.io/en/latest/
`wait` parameter is exactly for this sync/async distinction here. In Qubes 4.0 most (all?) actions results in an event, so it can be used for async calls - initiate a call and instead of waiting for it to finish, react later on an event.
