### ISSUE TITLE
Using  snapshot enabled filesystem to create clones and AppVMs from templates (ZFS, btrfs)

### ISSUE THREAD

**Issue by stumbaumr** [QubesOS/qubes-issues#1699]
Hi,
just started out on using QubesOS. Trying to extensively using templates and cloned templates and basing AppVMs on them (Windows and Linux).
From my experience at my workplace (using Diskless root NFS servers booting from ZFS snapshots) I would like to propose following improvements:
- Use ZFS for the file system
- On template shutdown create automatically a snapshot (using a volume per template)
- Use snapshot clone to create new templates
- Use snapshot to start AppVM from template

Benefits
- Rollback to a working template is very easy, just use the previous working snapshot
- Saving space and cloning in the blink of an eye
- Snapshots are per definition readonly
- and all the other benefits of ZFS

**Comment by indolering** [comment]
This would [violate the terms of the GPL](https://sfconservancy.org/blog/2016/feb/25/zfs-and-linux/).

**Comment by marmarek** [comment]
We plan to have something very similar in Qubes 4.0, done with LVM thin snapshots.

**Comment by ileyd** [comment]
btrfs would probably be a better candidate than ZFS, if this were to be done with the FS rather than LVM

**Comment by rustybird** [comment]
@stumbaumr:

If you use the btrfs installation layout, clones are already done instantly using reflink copies.

There are some additional btrfs specific improvements that would be pretty easy, e.g. allowing _running_ VMs to be cloned or backed up.

@marmarek:

> We plan to have something very similar in Qubes 4.0, done with LVM thin snapshots.

Interesting. Is LVM going to become the preferred or even mandatory layout?

**Comment by kalkin** [comment]
@andrewdavidwong I think we can close this, because we already have a snapshot enabled filesystem for VMs now.

**Comment by andrewdavidwong** [comment]
Great, thanks!
