### ISSUE TITLE
Consider project funding transparency

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#1701]
Some members of the community are understandably curious about how Qubes is funded (see example below). There have been some informal discussions on the MLs in the past, but things change over time, and it might be worth having a periodically-updated page on the website about this topic, depending on how transparent ITL wants to be about how The Qubes Project is funded.

[Example of funding-related questions from Qubes community member:](https://groups.google.com/d/msg/qubes-devel/tU0Op1E1UsM/wYivw-r4AwAJ)

```
To my understanding, and as was alluded to in the post, this signals a
shift in business strategy.  That is, that instead of having some sort
of paid "premium" Qubes distribution, the Qubes team now has a different
model for supporting itself.

Is this actually untrue?  In either case, this brings up the question:
exactly how will ITL fund Qubes development?  What is the long-term
plan?  Is there a long-term plan?

On a related note, I know ITL has received a few recent grants.  How
does the Qubes team envision such grants playing a part in the future
funding of the project?  Are there guidelines for whose and what kind of
support to accept?  For example, should ITL seek grant funding from
various arms of the US government?
```

CC @rootkovska

**Comment by axon-qubes** [comment]
Not sure if the `C:website` label or the `Documentation/website` milestone is most appropriate for this. It might be worth having a `Project` or `Meta` label/milestone.

(BTW, @marmarek, what's the difference between the `C:website` label and the `Documentation/website` milestone?)

**Comment by marmarek** [comment]
> (BTW, @marmarek, what's the difference between the C:website label and the Documentation/website milestone?)

Very little if at all - there are C:website and C:doc. But generally this is to have every ticket assigned both milestone and category - to ease filtering (by either of them).

**Comment by bnvk** [comment]
I really like this idea of a transparent funding page. IMHO, ethics focused FOSS projects / products almost *require* this sort of thing in order for the community to understand dynamics, as well as grow trust once money is involved. Some on topic links:

- Buffer, a VC backed startup has a really well done [transparency section](https://buffer.com/transparency) on their site, even [publishing salaries](https://open.buffer.com/transparent-salaries/)
- unMonastary, a community of hackers / artists have an interesting idea called [Deep Time Bank](http://discourse.unmonastery.org/t/examining-the-unmonastery-deep-time-bank/107) as a means for tracking & valuing community contributions over time

> (BTW, @marmarek, what's the difference between the C:wesite label and the Documentation/website milestone?)

I'd assume that `C:doc` label would mean that that content exists in the `Offline Documentation` that will ship with Qubes.

**Comment by mfc** [comment]
the funding is already transparent so it should be pretty easy to make a page about it:

- bitcoins: https://www.qubes-os.org/donate/
  * https://blockexplorer.com/address/14zockMSKKp5MK6X2cHJ3mQwm9MwYsJ39j 
  * https://blockchain.info/address/14zockMSKKp5MK6X2cHJ3mQwm9MwYsJ39j
- OTF funding: https://www.opentech.fund/project/qubes-os

please see my response to that post: https://groups.google.com/d/msg/qubes-devel/tU0Op1E1UsM/L9YHGTukAAAJ

```
> To my understanding, and as was alluded to in the post, this signals a 
> shift in business strategy.  That is, that instead of having some sort 
> of paid "premium" Qubes distribution, the Qubes team now has a different 
> model for supporting itself. 

The idea was not a "premium" distribution, just that businesses would be 
more interested in supporting integrated Windows functionality. That 
value proposition still exists I hope, incorporating the Windows Tools 
(rather than treating it as a proprietary addon) is a way to enable 
users to have the same trust in it as in the rest of Qubes. 

There are obviously other communities besides businesses that also find 
the Windows Tools valuable (really anyone trying to transition their 
workflows from Windows into Qubes), so this should make using the 
Windows Tools an easier decision and enable better adoption of Qubes 
more generally. 

> Is this actually untrue?  In either case, this brings up the question: 
> exactly how will ITL fund Qubes development?   
> What is the long-term plan? Is there a long-term plan? 

Ideally through a diverse mix of funding, both in terms of entities 
providing funding and timelines of the funding. 

The long-term plan is to continue to try to find ways of funding Qubes 
development. 

> On a related note, I know ITL has received a few recent grants.  How 
> does the Qubes team envision such grants playing a part in the future 
> funding of the project?  Are there guidelines for whose and what kind of 
> support to accept?  For example, should ITL seek grant funding from 
> various arms of the US government? 

We are always looking for more support for Qubes development. Grants (as 
a style of funding) don't need to come from the US government, they can 
also come from public or private foundations, non-US governments, 
non-governmental organizations, etc. 

Joanna discussed guidelines in the context of the OTF grant we received 
last year: 

http://blog.invisiblethings.org/2015/06/04/otf-funding-announcement.html 

As Joanna mentioned in the blogpost, if you (or others reading) have 
relevant knowledge, experience, leads, free time etc and would like to 
help out in these efforts let us know. 
```

everything I said then is still true now.

**Comment by axon-qubes** [comment]
@mfc, @bnvk: We should consider the pros and cons of combining all or some of these pages:
 * Funding
 * Partners
 * Donate

**Comment by mfc** [comment]
@bnvk created https://www.qubes-os.org/funding/ so i'm closing.

**Comment by mfc** [comment]
> @mfc, @bnvk: We should consider the pros and cons of combining all or some of these pages:
>
> * Funding
> * Partners
> * Donate

sorry missed this. I think separate is fine but they should have contextual links / references between them.

**Comment by andrewdavidwong** [comment]
Reopening this since we need links between [Funding](https://www.qubes-os.org/funding/) and [Partners](https://www.qubes-os.org/partners/). Personally, I think these two pages are starting to look like duplicates and that we should *consider* merging them.

**Comment by andrewdavidwong** [comment]
CC @rootkovska

**Comment by andrewdavidwong** [comment]
Added the interconnecting links.

**Comment by rootkovska** [comment]
Yup, I agree I'm too confused about why we have two different pages listing orgs that sponsor the project. IMHO there should be just one.

And with a proper disclaimer that these are organizations that has given us money: no more, no less than that. And that we happily accept the money without running any extensive due diligence process on them. Pretty much like any shop which sells goods to the public does in the free world.

Specifically we should be very careful that our listing of them on our website should not be interpreted as an endorsement for anything other than their foresight and acuity with regards to evaluating of our project's importance for safety of personal computing. But not an endorsement of any potential products or services these sponsors might be otherwise offering.

**Comment by andrewdavidwong** [comment]
@mfc: Any comment before I start merging the pages?

**Comment by rootkovska** [comment]
So, BTW, for the reasons I gave above, we should avoid the name "Partners" which has connotations which I guess we would like to avoid. "Sponsors" perhaps?

**Comment by rtiangha** [comment]
If the funding truly is no-strings-attached, you could call those people patrons or supporters of the Qubes OS project. That might be more appropriate.

**Comment by mfc** [comment]
I think part of the idea is that some organizations do *not* give us money, but rather hardware or other non-monetary support. I think that was part of the original idea around the Partners page being distinct from the Funding ($) page. Also it allowed us to provide context for the funding, while the Funding page was just a list.

> So, BTW, for the reasons I gave above, we should avoid the name "Partners" which has connotations which I guess we would like to avoid. "Sponsors" perhaps?

It sounds like you want to rename Partners to Supporters, I think that's fine. That can be done independent of merging the pages. 

In terms of merging the pages, I'd be interested to know which format you are proposing for this merged Sponsors page -- the current Partners page or the current Funding page? One is focused on presenting the "Sponsors", the other on chronology of Qubes OS funding.

**Comment by mfc** [comment]
we can save the "Partners" terminology for if/when there is ever a "Qubes Partners" program, similar to:

https://www.docker.com/partners/partner-program
https://goto.docker.com/partners

where we try to build an ecosystem of consulting, OEM, reseller,training, technology, etc services.

**Comment by rootkovska** [comment]
I'm find with listing supporters in chronological order, thus focusing more on transparency rather than just logo displaying.

**Comment by andrewdavidwong** [comment]
Ok, so one option is just to remove the Partners page and keep the Funding page (until we have a Partners program). Would that satisfy everyone?

**Comment by andrewdavidwong** [comment]
This was done a long time ago; just forgot to close this issue. We now just have a [Partners page](https://www.qubes-os.org/partners/) (`/funding/` now redirects to `/partners/`).
