### ISSUE TITLE
Implement qrexec service for installing template images

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#1705]
Currently the only way to install new template is to use `qubes-dom0-update` tool. This means the package needs to be built and signed by ITL.
It would be good to provide a tool (qrexec service) to create new templates from 3rd party sources. The template image itself (`root.img`) is not trusted by dom0 in any way, so it would not compromise whole system security (contrary to rpm installed in dom0, which can do anything).
AppVMs based on some template do trust its `root.img`, but it's up to the user which VMs will use such template.

Then, having such service, it will be possible to write a tool (running in some VM), which would download the image, verify its checksum/signature and transfer to dom0. Optionally first converting the image to "raw" format from something else (vmdk, vdi, qcow2 etc).

Such template should have PVGrub set as a kernel by default, so the template will be able to use whatever kernel it want. Including non-Linux one: MirageOS, FreeBSD etc.

In R4.0, we will have tags for VMs, so such template should be tagged as `imported` and `imported-from-VMNAME` (where `VMNAME` is a name of VM which sent that image). Related to #1637

**Comment by jpouellet** [comment]
Is this resolved by https://github.com/QubesOS/qubes-doc/commit/7ec63f53956b76efca4554e7d5988eab728e0aa3?

Also, XREF https://github.com/QubesOS/qubes-issues/issues/2634 since I hadn't noticed this before.

**Comment by marmarek** [comment]
Admin API covers all of this. It is already possible to install qubes-template-* rpm package from a VM (having appropriate Admin API access). Some nicer UI could be useful, but that's #2534
