### ISSUE TITLE
Make it easier to install new qrexec policy

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#1706]
Currently when one want to install some VM-VM qrexec service, he/she still needs to create at least one file in dom0: qrexec policy. If there is no such policy, service call will be denied (after a message that policy is missing).
It may be good idea to ask in such a case whether some default policy should be created (default: ask for every call). Such question should be hard to accept by default - at least having "No" as default, but better having non-standard action (like "draw a cat here" ;) ).
This should ease implementing new qrexec services.

@bnvk any idea for such hard to accept by mistake window?

**Comment by unman** [comment]
@andrewdavidwong Close please
