### ISSUE TITLE
Cannot install v3.1 rc2 in Lenovo w520 using UEFI

### ISSUE THREAD

**Issue by qubesuser2** [QubesOS/qubes-issues#1708]

**Comment by qubesuser2** [comment]
I think this is a bug.  I have a Lenovo w520 with bios/uefi version 1.36.  The screen is a 1920 x 1080 screen which so far as I know is original to this machine.    

I dd qubes v3.1 rc2 to a usb stick and it works for installation just fine when installed in legacy boot mode.  

The same stick will boot in uefi mode, and can be verified, but when it gets to the screen with 14 penguins, it locks up.  The penguins are evenly spaced except for a bit of extra space between penguin 7 & 8.  They seem a little squashed for height, but I am not sure.  Waiting a prolonged period of time does not result in any change of the screen.  There is no blinking cursor or other screen actions available.  This happens if I select install or install with verification.  (my memory of the choices)  If I select rescue mode, then I get two columns of white text which extend about 1/3 of the  way down the screen below the penguins, which are very obviously compressed for height, with word legibility severely compromised.  

My guess is the issue is a display adapter problem.

**Comment by qubesuser2** [comment]
This computer has multiple display options.  I am using the screen native to the laptop, not an external monitor.  The native display has three bios/uefi boot options.  

1.  Integrated -- I am using discreet display option currently, and it is what I installed Qubes under.  This is the energy saving display option.
2.  Discreet -- I presume this is the higher quality graphics option, but uses more energy.  I tried this just now with Qubes v3.1 rc2 installer in both legacy (bios) and uefi modes.  In both cases it only went a little way before hanging up.  With discreet / bios install it hung with a blinking cursor after the grub like screen with install options.  With discreet / uefi install it hung at the penguins again.  An install of Qubes v3.1 rc2 which boots fine in legacy (bios) / integrated graphics mode did not boot in discreet mode, and hung after grub at a blinking cursor.  
3.  Nvidia Optimus is a combination of integrated / discreet graphics, and I did not try it at all.  It switches back and forth based on a decision by the OS.

**Comment by marmarek** [comment]
I'm afraid it means buggy UEFI firmware or bug in Xen UEFI handling. Some details are in this comment: https://github.com/QubesOS/qubes-issues/issues/794#issuecomment-142757959
Generally it means that you're stuck with legacy mode...
In any case, please continue discussion on qubes-users mailing list, or in #794 ticket.
