### ISSUE TITLE
Automatically generate informative heading links

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#1713]
The auto-generated ToC on each page creates links like this:

https://www.qubes-os.org/intro/#tocAnchor-1-1-1

These work fine, but they aren't informative to humans. The above link points to the same target as this (human-informative) one:

https://www.qubes-os.org/intro/#what-is-qubes

It would be nice to find some way of automatically generating the second type of link (and providing it as the target of a link icon next to each heading) so that people can paste them in emails and elsewhere on the web.

@bnvk, do you know if there's any way to do this?

**Comment by bnvk** [comment]
@axon-qubes yah, I noticed that when I was doing the site re-working. I actually had to patch the JS library a little bit to even be able to customize it the way I did. I suppose I could dig into again with the improvement you suggest, at some point in time :)

**Comment by axon-qubes** [comment]
That would be great, thanks!

**Comment by andrewdavidwong** [comment]
Somewhat serious issue with the current state:

Updating the page by inserting a new heading can shift the heading numbers so that existing links will point to the wrong heading. For example, if I insert a new section with a heading at the top of the Intro page, this link will point to the "wrong" section: https://www.qubes-os.org/intro/#tocAnchor-1-1-1

**Comment by andrewdavidwong** [comment]
Thanks for fixing this, @marmarek!
