### ISSUE TITLE
Diagnose documentation discovery problems

### ISSUE THREAD

**Issue by axon-qubes** [QubesOS/qubes-issues#1714]
I see messages to the MLs and posts on `qubes-issues` constantly asking for documentation which already exists ([latest example](https://github.com/QubesOS/qubes-issues/issues/1633#issuecomment-177777484)). Clearly, users are having trouble finding the documentation pages they're looking for. We should try to determine (as scientifically as reasonably possible) the cause(s) of this.

**Comment by marmarek** [comment]
cc @bnvk

**Comment by axon-qubes** [comment]
I wonder if it would help to restore the direct link to the documentation from the top navbar. Burying the documentation link under "Help" with 5-6 other things, as we currently do, might be making it less likely that users read it. (Perhaps there's some way to test this.)

**Comment by axon-qubes** [comment]
I haven't noticed any documentation discovery issues in a while, so I'll close this for now and re-open it the problem recurs.
