### ISSUE TITLE
getting-started.md code blocks are white-on-white

### ISSUE THREAD

**Issue by axon-qubes** [QubesOS/qubes-issues#1715]
Here's a screenshot:
![1](https://cloud.githubusercontent.com/assets/10417133/12763646/6ac2974c-c9ed-11e5-8662-64cda245842c.png)

(I highlighted the first four lines of the first code block to show that there's actually text there.)

CC @bnvk

**Comment by marmarek** [comment]
I've reverted change suggested by github docs, but it didn't fixed anything. @bnvk any idea? Maybe some github pages change? I don't remember having github page build warning before, so maybe it have something to do here. The warning:
```
Subject: [QubesOS/qubesos.github.io] Page build warning

The page build completed successfully, but returned the following warning:

You are attempting to use the 'pygments' highlighter, which is currently unsupported on GitHub
Pages. Your site will use 'rouge' for highlighting instead. To suppress this warning, change the
'highlighter' value to 'rouge' in your '_config.yml'. For more information, see
https://help.github.com/articles/page-build-failed-config-file-error/#fixing-highlighting-errors
.

GitHub Pages was recently upgraded to Jekyll 3.0. It may help to confirm you're using the
correct dependencies:

  https://github.com/blog/2100-github-pages-now-faster-and-simpler-with-jekyll-3-0

For information on troubleshooting Jekyll see:

  https://help.github.com/articles/using-jekyll-with-pages#troubleshooting

If you have any questions you can contact us by replying to this email.
```

**Comment by marmarek** [comment]
And reverted the revert... Github pages really force `rouge` highlighting, and indeed this (together with jekyll update?) breaks code blocks. It is described in blog post linked in the warning message.

**Comment by bnvk** [comment]
Yah, definitely caused the change to `rouge` instead of `pygments` seems to be something with how the differing highlighters generate the CSS. Anywho I just submitted a pull request to fix this!

**Comment by axon-qubes** [comment]
Oops, looks like you and I were working on this at the same time, @bnvk. I hope you don't mind. I adjusted the font size, padding, and colors of code appearance overall.

**Comment by axon-qubes** [comment]
Do you think it's ok? We can revert my commit and use yours instead, if you want.

**Comment by bnvk** [comment]
@axon-qubes ah, damn it, wasted time! I don't know. Joanna and others had asked explicitly for a dark background, but met, whatever. This is closer to what Github does, except it looks a little off (to my eye) as the font font-size, but that can be adjusted later!

**Comment by marmarek** [comment]
FWIW I like the current colors, previous version white-on-almost-black was too much contrast, especially in inline text.

**Comment by axon-qubes** [comment]
Ok, sounds like this issue is resolved for now. Feel free to re-open if necessary.
