### ISSUE TITLE
Clicking the "Back" button during setup / configuration gets user stuck

### ISSUE THREAD

**Issue by bnvk** [QubesOS/qubes-issues#1719]
During the "Create VMs" setup stage that allows user to automatically create things, I noticed that if a user clicks the "Back" button during this stage, the installer will go to the previous step, but it is unclear what's happening and the user is unable to go back "Forward" as that button is disabled! Here are some thoughts:

If the installer actually is stopped and the VM configuring is indeed cancelled:"

- The "Forward" button should be re-enabled upon going backwards

However, if the process underneath is not stopped, the "Back" button should either say"

- The "Back" button should either say "Cancel" which stops the process
- The "Back" button should be disabled once the configuration steps actually starts

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `anaconda-20.25.16-12.fc20` has been pushed to the `r3.1` testing repository for dom0.
To test this update, please install it with the following command:
```
sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-installer-qubes-os/compare/a0a616733f739ab50c342e72defce2d16468346b...ab1104fa139e47f5509734d11aad89d87a79781b

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `anaconda-20.25.16-12.fc20` has been pushed to the `r3.1` stable repository for dom0.
To install this update, please use the standard update command:
```
sudo qubes-dom0-update
```
Or update dom0 via Qubes Manager.

[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-installer-qubes-os/compare/a0a616733f739ab50c342e72defce2d16468346b...ab1104fa139e47f5509734d11aad89d87a79781b
