### ISSUE TITLE
sys-net , Error starting VM: Cannot exeCute qrexec-daemon! 

### ISSUE THREAD

**Issue by TNTBOMBOM** [QubesOS/qubes-issues#1724]
(qubes manually upgradable to 3.1) , if i want to switch my sys-net from fedora-21 to fedora-23 = clicking start on sys-net wont make it start and it will give a yellow sign with this error

`Error starting VM: Cannot exeCute qrexec-daemon! ` 

![sys-net11111111111111](https://cloud.githubusercontent.com/assets/11895339/12870381/c6555e06-cd39-11e5-8962-308a16f0bfe1.png)

maybe related 

https://github.com/QubesOS/qubes-issues/issues/1675

**Comment by marmarek** [comment]
Most likely the same problem, focus on #1675 first.

**Comment by TNTBOMBOM** [comment]
yep correct and solved witha same command as well :- `qvm-start sys-firewall`

comparison between the output of `qvm-start sys-firewall` & `qvm-prefs sys-firewall` from fedora-21 & fedora-23

- distro:- fedora-21
- command:- `qvm-start sys-net`

> [me@dom0 ~]$ qvm-start sys-net      
--> Creating volatile image: /var/lib/qubes/servicevms/sys-net/volatile.img...
--> Loading the VM (type = NetVM)...
--> Starting Qubes DB...
--> Setting Qubes DB info for the VM...
--> Updating firewall rules...
--> Starting the VM...
--> Starting the qrexec daemon...
Waiting for VM's qrexec agent......connected
--> Starting Qubes GUId...
Connecting to VM's GUI agent: .connected
--> Sending monitor layout...
--> Waiting for qubes-session...

- command:- `qvm-prefs sys-net`

> [me@dom0 ~]$ qvm-prefs sys-net     
name               : sys-net
label              : red
type               : NetVM
template           : fedora-21
dispvm_netvm       : none (default)
updateable         : False
autostart          : False
installed_by_rpm   : False
include_in_backups : True
last_backup        : None
dir                : /var/lib/qubes/servicevms/sys-net
config             : /var/lib/qubes/servicevms/sys-net/sys-net.conf
pcidevs            : ['04:00.0']
pci_strictreset    : True
root_img           : /var/lib/qubes/vm-templates/fedora-21/root.img
root_volatile_img  : /var/lib/qubes/servicevms/sys-net/volatile.img
private_img        : /var/lib/qubes/servicevms/sys-net/private.img
vcpus              : 8
memory             : 300
maxmem             : 3000
MAC                : 00:16:3E:5E:6C:02 (auto)
kernel             : 4.1.13-8 (default)
kernelopts         : nopat iommu=soft swiotlb=8192 (default)
debug              : off
default_user       : user
qrexec_timeout     : 60
internal           : False

- distro:- fedora-23
- command:- `qvm-start sys-net`

> [me@dom0 ~]$ qvm-start sys-net
--> Creating volatile image: /var/lib/qubes/servicevms/sys-net/volatile.img...
--> Loading the VM (type = NetVM)...
--> Starting Qubes DB...
--> Setting Qubes DB info for the VM...
--> Updating firewall rules...
--> Starting the VM...
--> Starting the qrexec daemon...
Waiting for VM's qrexec agent......connected
--> Starting Qubes GUId...
Connecting to VM's GUI agent: .connected
--> Sending monitor layout...
--> Waiting for qubes-session...

- command:- `qvm-prefs sys-net`

>[me@dom0 ~]$ qvm-prefs sys-net
name               : sys-net
label              : red
type               : NetVM
template           : fedora-23
dispvm_netvm       : none (default)
updateable         : False
autostart          : False
installed_by_rpm   : False
include_in_backups : True
last_backup        : None
dir                : /var/lib/qubes/servicevms/sys-net
config             : /var/lib/qubes/servicevms/sys-net/sys-net.conf
pcidevs            : ['04:00.0']
pci_strictreset    : True
root_img           : /var/lib/qubes/vm-templates/fedora-23/root.img
root_volatile_img  : /var/lib/qubes/servicevms/sys-net/volatile.img
private_img        : /var/lib/qubes/servicevms/sys-net/private.img
vcpus              : 8
memory             : 300
maxmem             : 3000
MAC                : 00:16:3E:5E:6C:02 (auto)
kernel             : 4.1.13-8 (default)
kernelopts         : nopat iommu=soft swiotlb=8192 (default)
debug              : off
default_user       : user
qrexec_timeout     : 60
internal           : False

**Comment by ThierryIT** [comment]
Same pb : #3459
