### ISSUE TITLE
Qubes Guest-Additions (suggestion)

### ISSUE THREAD

**Issue by TNTBOMBOM** [QubesOS/qubes-issues#1725]
how can we make an HVM distro to get function with Qubes functionality or properties ? 

for example if someone wanted to maximize the window of an HVM let say for e.g Kali or Ubuntu...etc = not possible. 

so i wonder why dont we have something like VirtualBox  Guest-Additions ? 

we can have it from virtualbox itself like this:- 

![8b9521279f421362f5b2e987009d4979de41749a](https://cloud.githubusercontent.com/assets/11895339/12870735/72dd4854-cd4a-11e5-9654-d132175294d8.jpg)

then it will be inside the OS , once u run it = all Vbox properties is functional.

or even it is downloadable/installable from Ubuntu/Debian/Kali...etc packages by running this command

`sudo apt-get install virtualbox-guest-x11`

or maybe there is a way of making any  HVM fully functioning with Qubes which i dont know ?

**Comment by marmarek** [comment]
There is already a thread on mailing list about this: https://groups.google.com/d/msgid/qubes-devel/56B369E1.2030202%40zrubi.hu
Please do not duplicate stuff. Also use mailing list for broad ideas/discussion - there is a lot more people looking there. And keep only specific result of such discussion in here ("things to implement", not "things to design and discuss").
