### ISSUE TITLE
can't qvm-copy-to-vm files mounted as gvfs/mtp (qfile-agent: Operation not supported)

### ISSUE THREAD

**Issue by taradiddles** [QubesOS/qubes-issues#1726]
summary: trying to copy files from a gvfs/mtp mountpoint to a vm with qvm-copy-to-vm throws a "qfile-agent [...] Operation not supported" error.

environment: 3.1rc2 ; sys-usb vm.

steps to reproduce:
1- plug in a usb mtp device (in my case a samsung tablet)
2- open nautilus in sys-usb, click on the "android" device to mount the device. It's now mounted in /run/user/1000/gvfs/mtp:host=[...]/Tablet
3a - in nautilus, browse to some folder on the tablet, select and copy to vm (for instance "untrusted")
3b- or, in a terminal, qvm-copy-to-vm untrusted some_folder_on_that_tablet
4- if the folder is large, it takes a bit of time then there's the usual "do you allow domain sys-usb to execute[...]", click yes, it takes a bit of time again, and I get the following error:

"qfile-agent: Fatal error: open DCIM/Camera/20110603_060631.jpg (error type: Operation not supported)"

maybe it's specific only to MTP devices, or to gvfs or even fuse as a whole. Let me know if I you need more tests (eg. I could enable networking in sys-usb and try a ssh gvfs mount).

**Comment by taradiddles** [comment]
(forgot to add that copy between the private fs and the device is working. So the workaround is to copy files from the mtp device to sys-usb's rw/..., then qvm-copy-to-vm from there.)

**Comment by marmarek** [comment]
Interesting. Even more interesting that a simple `cp` on such files also fails, with the same message. So it looks to be specific to mpt/gvfs, not exactly `qvm-copy-to-vm` only.
When copying the file using Nautilus, it makes some D-Bus calls to gvfs daemon to do that.

**Comment by taradiddles** [comment]
Sorry, I should have tested that. I used nautilus to do the mount magic but couldn't imagine that copying files would be different than regular cp. 
When time permits I'll try to test that behavior on a f23 standalone install.

**Comment by taradiddles** [comment]
So - tested with stock f23, and same weird behavior there. Closing, not a Qubes issue.
