### ISSUE TITLE
qubes-core-vm - missing dependencies

### ISSUE THREAD

**Issue by Zrubi** [QubesOS/qubes-issues#1732]
it seems qubes-core-vm has some missing dependencies.

If you try to use a fedora-minimal as an update VM the dom0 updates will fail because of missing packeges:
- yum
- yum-dnf
- and probably some more - because dom-update is still hanging.

**Comment by Zrubi** [comment]
more precisely those scripts are trying to use yum:
/usr/lib/qubes/qubes-download-dom0-updates.sh
/usr/lib/qubes/upgrades-installed-check

they are from package:
qubes-core-vm

But that package do not pull the any packages providing yum.

**Comment by Zrubi** [comment]
and of course  the affected distro is: fedora 23

**Comment by marmarek** [comment]
Ok, the question here is: do we want to support dom0 updates download in minimal template out of the box? Or rather add this to a list of "optional" features and document "if you want to use minimal-based VM to download dom0 updates, install X, Y and Z"?

**Comment by Zrubi** [comment]
Well, because that script is part of a package that is already installed in the minimal package - I would expect that it will works without adding more **dependencies** manually.

But for me it is acceptable if we only document the fact that more packages are needed for some feature to work. - Just like It was the case with tinyproxy, however that was a completly independent package.

Because I see that minimal packeges should be really minimal - I would chose a package without correct dependencies instead of bloated template. - If you accept this too, I will find out what else is needed for a working UpdateVM, and will make a separate section for this in the Documentation

**Comment by marmarek** [comment]
On Tue, Feb 09, 2016 at 05:22:00AM -0800, Zrubi wrote:
> Well, because that script is part of a package that is already installed in the minimal package - I would expect that it will works without adding more **dependencies** manually.

This is how minimal template is done... To do it right, we probably
should split qubes-core-vm package into several smaller ones and install only
some of them. But in practice probably we will not have time for this :(

> Because I see that minimal packeges should be really minimal - I would chose a package without correct dependencies instead of bloated template. - If you accept this too, I will find out what else is needed for a working UpdateVM, and will make a separate section for this in the Documentation

Yes, I think this is the way to go, at least for now. If required
packages turns out to be really small, we can consider including them by
default.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by adrelanos** [comment]
Marek Marczykowski-Górecki:
> do we want to support dom0 updates download in minimal template out of the box?

No. Anyhow. Make minimal templates cause minimal time effort since it's
a geeky feature.

**Comment by axon-qubes** [comment]
Strange. My `UpdateVM` is `sys-firewall`, based on `fedora-23-minimal`, and everything works fine. This is on R3.0.

**Comment by Zrubi** [comment]
@axon-qubes Are you created that template from the rpm? or upgraded it from f22?
also please check if yum and/or dnf-yum packege is installed.

**Comment by axon-qubes** [comment]
@Zrubi Ah, good point. It must have been upgraded from F22.

**Comment by Zrubi** [comment]
It seems the only missing packages needed for qubes-dom-update is:
yum
dnf-yum

I will update the documentation with this info soon.
