### ISSUE TITLE
Domain Debian qrexec not connected

### ISSUE THREAD

**Issue by TNTBOMBOM** [QubesOS/qubes-issues#1735]
i wanted to remove okular from my standaloneVM , but when i typed:- 

`sudo apt-get remove imagemagick`

then pressed on y

the entire standealoneVM-debian shut down as well , and left in yellow freezing mark , image:- 

![imagemagic](https://cloud.githubusercontent.com/assets/11895339/12938155/d1f3d402-cfa7-11e5-968a-6013fe8dc828.png)

**Comment by marmarek** [comment]
You should read what `apt-get` told you, before blindly accepting it. You've removed `qubes-core-agent` and `qubes-gui-agent` this way.

**Comment by TNTBOMBOM** [comment]
> You should read what apt-get told you, before blindly accepting it.

so how do i remove image Magic inside debian-qubes? 

> You've removed qubes-core-agent and qubes-gui-agent this way.

yeah here:- 

![imagemagic1](https://cloud.githubusercontent.com/assets/11895339/12938330/2e36b5b6-cfaa-11e5-93dd-4f6b5e807f28.png)

also , isnt this a bad sign to make an entire OS collapse inside Qubes OS just by removing image magic ? i think the dependencies of Qubes on that should be changed. 

do u have solutions to re-back the lost debian or i should made a new one?

**Comment by marmarek** [comment]
> so how do i remove image Magic inside debian-qubes? 

As you've probably guessed already - you can't.

> do u have solutions to re-back the lost debian or i should make a new one? 

You can try to access VM console using `sudo xl console VMNAME`, but most likely you'll need a new one (or restore from backup).

**Comment by TNTBOMBOM** [comment]
yeah i c , at least this should be an alarm message or wrtten under "Known issues" 

https://www.qubes-os.org/doc/templates/debian/#tocAnchor-1-1-2

i can add it if u want , but i dont know if this is the right place inside qubes website to add it.

**Comment by TNTBOMBOM** [comment]
just to add something maybe interesting:- 

even when i created a new standaloneVM but witha same old standaloneVM name (after deleting the old one) = the same message will appear directly after creating it , but when u click on start VM button the message will disappear and the VM will work normally.
