### ISSUE TITLE
apper no updater... excuse me if I repeat something already solved

### ISSUE THREAD

**Issue by andreasvlc** [QubesOS/qubes-issues#1739]
![img_0676](https://cloud.githubusercontent.com/assets/17161860/12966011/fbffa1f0-d05a-11e5-9157-06ed43552be9.JPG)
![img_0677](https://cloud.githubusercontent.com/assets/17161860/12966013/fc028ee2-d05a-11e5-8e14-d9cc99dd6122.JPG)
![img_0678](https://cloud.githubusercontent.com/assets/17161860/12966012/fc02821c-d05a-11e5-8302-2e3b1a2c0ed6.JPG)

greetings

**Comment by mfc** [comment]
try running dom0 update from command line:

1. open System Tools > Konsole (Terminal) in dom0
2. type `sudo qubes-dom0-update`

https://www.qubes-os.org/doc/software-update-dom0/

If it says you are offline then in Qubes VM Manager go to System > Global settings and make sure that your UpdateVM is `sys-whonix` or `sys-firewall` or some other networkVM or proxyVM you know has a connection to the internet.

**Comment by axon-qubes** [comment]
I'm assuming this issue has been resolved based on the lack of recent activity. If not, please feel free to re-open it.
