### ISSUE TITLE
fedora-23 as standalone-VM sending application list and icons to dom0

### ISSUE THREAD

**Issue by TNTBOMBOM** [QubesOS/qubes-issues#1744]
when i click on the update button it shows this

![fedora](https://cloud.githubusercontent.com/assets/11895339/13005976/ac7638be-d17d-11e5-8fce-64d941c6f7b6.png)

i think (if im not mistaken) only fedora-23-template should has this ability no?

**Comment by marmarek** [comment]
No, every VM in which you can install application should send its list to dom0. Otherwise you wouldn't be able to add them to the menu.
