### ISSUE TITLE
Error starting VM 'sys-net': Failed to kill old QubesDB instance (PID 1793 )

### ISSUE THREAD

**Issue by TNTBOMBOM** [QubesOS/qubes-issues#1745]
qubes 3.1 , sys-net fedora-23 

message/notification pupped up while i wanted to start new appVM (just clicked on the start button then the message appeared)

> Error starting VM 'sys-net': Failed to kill old QubesDB instance (PID 1793
). Terminate it manually and retry. If that isn't QubesDB process, remove the pidfile: /var/run/qubes/qubesdb.sys-net.pid

image (firstly the message appeared in the notification section down right corner , then i shutdowned firewall then sysnet):- 

![firewallprob](https://cloud.githubusercontent.com/assets/11895339/13006271/b3174e7c-d17f-11e5-9568-fa07b856c77a.png)

**Comment by TNTBOMBOM** [comment]
happened again with different PID number:-

> Error starting VM 'sys-net': Failed to kill old QubesDB instance (PID 1800
). Terminate it manually and retry. If that isn't QubesDB process, remove the pidfile: /var/run/qubes/qubesdb.sys-net.pid

**Comment by andrewdavidwong** [comment]
This question is too localized for `qubes-issues`. Please consider posting this to the `qubes-users` mailing list instead. (You can read more about our mailing lists [here](https://www.qubes-os.org/mailing-lists/).)

`qubes-users` is intended for these sorts of questions and receives much more traffic, which means that your question is more likely to receive a response there.

**Comment by marmarek** [comment]
The message was to explain "rare problem", but apparently it isn't such rare and deserve a proper fix.

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-dom0-3.1.17-1.fc20` has been pushed to the `r3.1` testing repository for dom0.
To test this update, please install it with the following command:
```
sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-admin/compare/1e29d7fa396a1469541a6d64e48f398396f79780...d8093f38c428e4a9e7be421f2dc57e0a45a19477

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-dom0-3.1.17-1.fc20` has been pushed to the `r3.1` stable repository for dom0.
To install this update, please use the standard update command:
```
sudo qubes-dom0-update
```
Or update dom0 via Qubes Manager.

[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-admin/compare/1e29d7fa396a1469541a6d64e48f398396f79780...d8093f38c428e4a9e7be421f2dc57e0a45a19477
