### ISSUE TITLE
include quotes from non-white-male experts in "What the experts are saying" front page section

### ISSUE THREAD

**Issue by mfc** [QubesOS/qubes-issues#1746]
Would be nice to project a more diverse userbase or expertbase. If the propaganda committee finds such quotes from twitter it may be worth considering rotating them onto the front page.

**Comment by comradekingu** [comment]
Maybe you could ask someone known to be a non-white-male expert if they have something to say?

**Comment by bnvk** [comment]
I know @isislovecruft is a Qubes fan, so I reached out to her, this is what she said:

![Picture of Isis](https://avatars2.githubusercontent.com/u/907241?v=3&s=100)
`"With QubesOS, I feel more comfortable accessing Tor Project infrastructure from the same laptop as I use to execute random GameBoy ROMs that I downloaded from the internet."`
*-- Isis Agora Lovecruft, Cypherpunk, Core Developer, Tor Project*

**Comment by mfc** [comment]
excellent, thanks! I cut out a `that` and `as` to shorten it slightly. Looks good enough to post, maybe we don't need to cut any existing out but just rearrange (like maybe have the "Why do the experts like Qubes?" as a centered third row). I'll let you figure that all out.

once added I dunno if we should close vs. keep it open for proposals of other folks from the community over time.

**Comment by mfc** [comment]
let's close this for now but use this to propose others in the future.
