### ISSUE TITLE
After upgrading to 3.1, VMs fail to boot whenever HW devices are assigned to them.

### ISSUE THREAD

**Issue by uiadraem** [QubesOS/qubes-issues#1750]
Hi,
I normally use custom VMs based on debian-8 template with some HW devices assigned to them (mostly USB ports). Everything was all right until I upgraded to 3.1. Since then, I get this error:

Error starting VM <xyz>: internal error: libxenlight failed to create new domain <xyz>

I tried both 3.19.x and 4.1.x kernels with no success. I also tried fedora-23 default template with no success either. On the other hand, the same VMs used to work normally before the upgrade, and they still do if I don't assign to them any HW devices.

My machine is a MSI GP60 Leopard laptop. Any idea...?

**Comment by andrewdavidwong** [comment]
This question is too localized for `qubes-issues`. Please consider posting this to the `qubes-users` mailing list instead. (You can read more about our mailing lists [here](https://www.qubes-os.org/mailing-lists/).)

`qubes-users` is intended for these sorts of questions and receives much more traffic, which means that your question is more likely to receive a response there.
