### ISSUE TITLE
package awesome tiling manager for easy install from dom0

### ISSUE THREAD

**Issue by mfc** [QubesOS/qubes-issues#1756]
for tech-savvy users who like tiling managers, would be nice to have the existing awesome desktop environment @woju uses packaged for easy installation from dom0: 

https://github.com/woju/qubes-desktop-linux-awesome

This should not be an option on first install / firstboot (ISO is already too big and tech-savvy folks can have an extra hurdle), just from qubes repos from dom0. If it is a bunch of effort or not maintained anymore then we can scrap the idea.

**Comment by bnvk** [comment]
:+1: to this suggestion- the number of tech-savvy people who have cited "no tiling window manager" as a reason to NOT try Qubes is quite high by my count. While not our largest target user base, pleasing these users seems a smart strategy!

**Comment by petertodd** [comment]
+1

I personally held off getting Qubes for ages because of this reason, and not having a tiling WM is still a big downside for me. I tried installing awesome myself from that package but haven't yet figured it out - I've never dealt with the RPM package system before using Qubes.

**Comment by minad** [comment]
I just installed qubes with i3. @SietsevanderMolen made some patches, see https://github.com/SietsevanderMolen/i3-qubes. The patches are simple and it works really well.

What are the requirements to get an additional wm into qubes?

**Comment by marmarek** [comment]
If that really works, I think that's all. Next steps (on our side):
 - review and test it out
 - include in official repository

Thanks @SietsevanderMolen!

**Comment by minad** [comment]
Hi,

Sounds good! There was one thing I was wondering about - the qubes dom0 login/logout procedure and session management in KDE.

Is it documented somewhere which qubes specific tasks have to be executed at startup and logout in dom0?

Currently when I logout and login again with i3 the VMs are still running but marked as transient. Then I have to execute 'qvm-rum --all true' to get them to the running state again. So what would be the right way to avoid this hack?

Am 13. Mai 2016 12:19:59 MESZ, schrieb "Marek Marczykowski-Górecki" <notifications@github.com>:

**Comment by marmarek** [comment]
Handle freedesktop standard of autostart applications
(/etc/xdg/autostart etc) - that's all. There should be no DE-specific in
that matter.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by minad** [comment]
Perfect. Thx. I will try that.

Am 13. Mai 2016 17:15:45 MESZ, schrieb "Marek Marczykowski-Górecki" <notifications@github.com>:
>Handle freedesktop standard of autostart applications
>(/etc/xdg/autostart etc) - that's all. There should be no DE-specific
>in
>that matter.

**Comment by marmarek** [comment]
awesome fails with:
```
/usr/share/awesome/lib/qubes.lua:100: bad argument #2 to 'format' (number has no integer representation)
```
@woju

**Comment by marmarek** [comment]
@woju it still doesn't support xdg autostart, which is mandatory - for example to start gui daemons.

**Comment by adrelanos** [comment]
Marek Marczykowski-Górecki:
> @woju it still doesn't support xdg autostart, which is mandatory - for example to start gui daemons. 

With newer systemd (from stretch) you might be able to port from xdg
autostart to systemd --user services.

**Comment by marmarek** [comment]
> With newer systemd (from stretch) you might be able to port from xdg autostart to systemd --user services.

It's about dom0, so stretch doesn't apply (at least for now). But `systemd --user` does.
I've been reluctant to use it anywhere, to not introduce another requirement (making it even harder to migrate to some other distribution in the future for example). But if we consider `systemd --user` widespread enough, this may indeed solve the problem. @woju what do you think?

**Comment by marmarek** [comment]
unrelated: @woju build fails on travis: https://travis-ci.org/QubesOS/qubes-desktop-linux-awesome/builds/141500900 any idea why? it works on my system...

**Comment by kulinacs** [comment]
What are the current roadblocks on getting this packaged? Just the travis build? Or is the xdg autostart problem still a problem?

**Comment by andrewdavidwong** [comment]
[Update from Mark Walters on qubes-devel](https://groups.google.com/d/msgid/qubes-devel/87twdm4x68.fsf%40qmul.ac.uk)

**Comment by marmarek** [comment]
It's done.
