### ISSUE TITLE
libvirtError: Requested operation is not valid: Domain is not running (whonix-ws)

### ISSUE THREAD

**Issue by TNTBOMBOM** [QubesOS/qubes-issues#1767]
wanted to shutdown whonix workstation so i pressed on the shutdown button then waited for a while because the VM didnt shutdown (kept in yellow mark) , then another message appeared asking me if i want to kill the VM , so pressed on kill process and also didnt shutdown immediately then this message appeared:- 

![ws-laggo](https://cloud.githubusercontent.com/assets/11895339/13201457/1a38d6ac-d86a-11e5-86bc-9ab20765e4c0.png)

- Details

> ----
line: if ret == -1: raise libvirtError ('virDomainDestroy() failed', dom=self)
func: destroy
line no.: 1103
file: /usr/lib64/python2.7/site-packages/libvirt.py
----
line: self.libvirt_domain.destroy()
func: force_shutdown
line no.: 1989
file: /usr/lib64/python2.7/site-packages/qubes/modules/000QubesVm.py
----
line: vm.force_shutdown()
func: check_if_vm_has_shutdown
line no.: 268
file: /usr/lib64/python2.7/site-packages/qubesmanager/main.py

**Comment by marmarek** [comment]
Did you get any other error before that (even related to totally different VM)?

**Comment by TNTBOMBOM** [comment]
nope , just from whonix workstation. 

shutdown button (didnt work) -> kill the vm ? (didnt worked directly) -> then that message appeared (and ws-whonix closed).

**Comment by adrelanos** [comment]
What's next in this ticket?

@TNTBOMBOM have you ever experienced this again?

**Comment by TNTBOMBOM** [comment]
just that time for once only. never happened again

**Comment by andrewdavidwong** [comment]
In that case, we'll close this for now. If the error recurs (for anyone), feel free to reopen this.
