### ISSUE TITLE
VM started via qubes.VMShell has qubes-guid running as root, breaks Qubes clipboard

### ISSUE THREAD

**Issue by mattmccutchen** [QubesOS/qubes-issues#1768]
From my `main` AppVM, I ran a command with `qvm-run research ...`, which automatically started the `research` AppVM and left its `qubes-guid` in dom0 running as root.  Then I tried to copy and paste some text from `research` to `main`, but nothing happened when I pressed the secure paste key.  Looks like the problem was that the `/var/run/qubes/qubes-clipboard*` files were created with root as owner and couldn't be read by `qubes-guid` for the `main` AppVM.  Something should change so that this sequence of operations works correctly.

(I don't want to hear heckling about my usage of qubes.VMShell; it's consistent with my current security model, and I presume the same problem would affect restricted inter-AppVM RPC services.)

**Comment by marmarek** [comment]
How do you start your `main` VM? Is it set to autostart? Does it happen
too if you start it manually (for example from Qubes Manager)?

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by mattmccutchen** [comment]
Indeed, my `main` VM is set to autostart.  If I restart `main` using Qubes Manager, stop `research` and start it again via qubes.VMShell, then the clipboard works (after I delete the existing root-owned `/var/run/qubes/qubes-clipboard*` files).  Perhaps the difference is that `qrexec-daemon` appears to run as root for autostarted VMs but as the dom0 user for VMs started with Qubes Manager.

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-gui-dom0-3.1.4-1.fc20` has been pushed to the `r3.1` testing repository for dom0.
To test this update, please install it with the following command:
```
sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-gui-daemon/compare/5c472ab3040ec936ca515131e343908673d5ff52...ee32d723ff454e47ddb06261055749882a6edb6f

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-gui-dom0-3.1.4-1.fc20` has been pushed to the `r3.1` stable repository for dom0.
To install this update, please use the standard update command:
```
sudo qubes-dom0-update
```
Or update dom0 via Qubes Manager.

[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-gui-daemon/compare/5c472ab3040ec936ca515131e343908673d5ff52...ee32d723ff454e47ddb06261055749882a6edb6f
