### ISSUE TITLE
qvm-kill'ing a DispVM leaves a spurious entry in qubes.xml

### ISSUE THREAD

**Issue by kbrn** [QubesOS/qubes-issues#1769]
I think I finally found the cause of the spurious entries...

Also, last time I removed such a spurious entry with Qubes Manager, it removed the DispVM template, obliterating all my customizations.  This time I won't try it ;).

**Comment by marmarek** [comment]
I assume Qubes 3.0, right? Because both bugs (#1660, #1662) are already fixed in 3.1 and will be backported soon to 3.0.

**Comment by kbrn** [comment]
Yep.  OK, sorry, didn't take the time to look through issues for similar entries.
