### ISSUE TITLE
change default proxy-vm: sys-whonix -> system-tor

### ISSUE THREAD

**Issue by mfc** [QubesOS/qubes-issues#1777]
"whonix" is a less familiar term for users than "tor", and "tor" accurately describes the network being used by the proxyvm while "whonix" does not.

`sys-whonix` -> `system-tor`

whonix should stay as the name for the templates.

**Comment by marmarek** [comment]
I think there was some trademark issues with that. @adrelanos does it
apply also to VM names? Or only to project names?

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by mfc** [comment]
the problem patrick faced was re: project name ("TorBox"), which is mentioned in the [Trademark FAQ](https://www.torproject.org/docs/trademark-faq.html.en), section "Can I use the word "Tor" as part of the name of my product or my domain name?". This should not be a problem.

**Comment by adrelanos** [comment]
The ones to responsible would be ITL. So it's not up to me. And @mfc
said they are fine with it.

#1175 suggests rather than using anon-whonix to use anonymous-web.

#1176 suggests a lot sys-... -> system-... changes.

Therefore I am wondering if it would not be best to avoid calling it
'tor' for other reasons than legal reasons. Perhaps call it
system-anonymizer?

**Comment by axon-qubes** [comment]
One problem with using the word "anonymous" (and its variants) is that Tor is often used for things other than anonymity, such as pseudonymity or mere IP address obfuscation. (Consider uses like logging into your Facebook account via a hidden service, or checking a business competitor's website to see how it looks from an IP outside your own corporate network.) Using the word "anonymous" in the name would be inaccurate if the VM ends up being used for these other purposes, but "Tor" will always be accurate as long as the traffic is going through the Tor network, regardless of the purpose.

**Comment by adrelanos** [comment]
Axon:
> One problem with using the word "anonymous" (and its variants) is
> that Tor is often used for things other than anonymity, such as
> pseudonymity or mere IP address obfuscation. (Consider uses like
> logging into your Facebook account via a hidden service, or checking
> a business competitor's website to see how it looks from an IP
> outside your own corporate network.) Using the word "anonymous" in
> the name would be inaccurate if the VM ends up being used for these
> other purposes, but "Tor" will always be accurate as long as the
> traffic is going through the Tor network, regardless of the purpose.

Very good points. And be rest assured, users will do get this wrong.

Quote: "am i completely anonymized if i log onto my facebook account?"

https://www.whonix.org/wiki/DoNot#Login_into_your_real_life_Facebook_account_and_think_you_are_anonymous

**Comment by adrelanos** [comment]
Related to #1775. More discussion:
https://github.com/QubesOS/qubes-issues/issues/1775#issuecomment-198338329

**Comment by axon-qubes** [comment]
Just to clarify, I meant that there actually **can** be legitimate use-cases for logging into your (real identity) Facebook account over Tor (using Facebook's own hidden service). See [here](https://blog.torproject.org/blog/facebook-hidden-services-and-https-certs) for an explanation. This is why I think it's inaccurate to conflate Tor with *nymity.

**Comment by andrewdavidwong** [comment]
It appears that the debate on this matter is settled (as in #1775). Closing as `notanissue`.
