### ISSUE TITLE
Qubes won't boot on NVMe hard drives

### ISSUE THREAD

**Issue by thomwiggers** [QubesOS/qubes-issues#1782]
The GRUB shipped by Fedora 20 is too old and doesn't support NVMe PCIe ssds.

This was at least the case on 3.1-rc2, I forgot to report this.

(I was able to get GRUB working by bringing in an rpm from the fedora 23 libs but other stuff prevented booting)

**Comment by marmarek** [comment]
What is that other stuff?

**Comment by thomwiggers** [comment]
Boot just hung after entering my password. I also had issues with i915, Skylake graphics generally suck before kernel 4.3, and there were some other things. The installer also crashed into non-graphic mode half the time.

Unfortunately I was unable to get logs as after fixing the issues it was late at night and I needed my laptop in the morning...

I was already using the 4.1.something kernel.

**Comment by jacobrichard** [comment]
I'm also interested in this -- I'm on a skylake thinkpad, and I'm reading through various docs and makefiles to try to work out if i can build a kernel package for dom0 based on the latest stable kernel from kernel.org (4.5.3 as of this posting).

**Comment by andrewdavidwong** [comment]
Take a look at this thread for using a 4.4.8+ kernel:

https://groups.google.com/d/topic/qubes-users/-xXKdAkIjxU/discussion

Closing this in favor of #1807.
