### ISSUE TITLE
RAM sharing problematic (lag 1 = lag all)

### ISSUE THREAD

**Issue by TNTBOMBOM** [QubesOS/qubes-issues#1785]
1- the real problem am facing atm:- 

the problem is . any VM (appVM or HVM ...etc) which is lagging or taking more load-ability time/resources it will effect on all the rest of VMs that im also using and cause them to lag as well. 

for e.g to clarify it:- 

i have windows 7 HVM and when i install things inside it = sometime it lag or hang for few minutes. 

also while im working on windows 7 HVM , im also working on Debian and here is the problem = Debian is also lagging on the same time as windows 7 lagging ???!! 

and i think (not sure) this problem because of the RAM is shareable between windows and debian (and all Qubes VMs) , tho the RAM amount for each VM is not the same in size but it is the same in dealing with issues.

2- theoretical problem:- 

if my guess is true regarding RAM share ability witha VMs then:- 

if one of the VMs having heartbleed vulnerability then it will not share or give the information of RAM which is used just to run it. for example:- 

if i have debian server with 8 GB ram and my pc contain 32 GB ram and let us assume this debian has heartbleed vulnerability then it will not just share the 8 ram information (which is related to debian itself). instead it will share the 32 GB ram, in other word someone may know the info of Whonix VM from the infected Debian VM through a heartbleed attack. 

(i know heatbleed is not a major or dangerous anymore like before , but im talking theoretically)

**Comment by marmarek** [comment]
Please use mailing list for broad discussions, keep only very specific things here.
