### ISSUE TITLE
Trusted PDF Converter doesn't appear in Debian 8

### ISSUE THREAD

**Issue by mfc** [QubesOS/qubes-issues#1791]
Trusted PDF converter should be available and appear in the right-click context menu in Debian 8 in addition to Fedora 23.

**Comment by marmarek** [comment]
It is there, in nautilus. If you mean dolphin, it isn't there in neither Fedora nor Debian.

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-pdf-converter-2.0.5-1.fc23` has been pushed to the `r3.2` testing repository for the Fedora `fc23` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.2-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-pdf-converter/compare/55f0a6420cc19ddb9a5d271cc70e89c1e97281e3...193d70377e2597cbbad061a5380a04204d674b49

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-pdf-converter-2.0.5-1.fc24` has been pushed to the `r3.2` testing repository for the Fedora `fc24` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.2-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-pdf-converter/compare/55f0a6420cc19ddb9a5d271cc70e89c1e97281e3...193d70377e2597cbbad061a5380a04204d674b49

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-pdf-converter-dom0-2.0.5-1.fc23` has been pushed to the `r3.2` testing repository for dom0.
To test this update, please install it with the following command:
```
sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-pdf-converter/compare/55f0a6420cc19ddb9a5d271cc70e89c1e97281e3...193d70377e2597cbbad061a5380a04204d674b49

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-pdf-converter_2.0.5-1+deb8u1` has been pushed to the `r3.2` testing repository for the Debian `jessie` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `jessie-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-pdf-converter/compare/55f0a6420cc19ddb9a5d271cc70e89c1e97281e3...193d70377e2597cbbad061a5380a04204d674b49

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-pdf-converter_2.0.5-1+deb9u1` has been pushed to the `r3.2` testing repository for the Debian `stretch` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `stretch-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-pdf-converter/compare/55f0a6420cc19ddb9a5d271cc70e89c1e97281e3...193d70377e2597cbbad061a5380a04204d674b49

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-pdf-converter-2.0.5-1.fc21` has been pushed to the `r3.1` testing repository for the Fedora `fc21` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.1-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-pdf-converter/compare/55f0a6420cc19ddb9a5d271cc70e89c1e97281e3...193d70377e2597cbbad061a5380a04204d674b49

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-pdf-converter-2.0.5-1.fc22` has been pushed to the `r3.1` testing repository for the Fedora `fc22` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.1-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-pdf-converter/compare/55f0a6420cc19ddb9a5d271cc70e89c1e97281e3...193d70377e2597cbbad061a5380a04204d674b49

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-pdf-converter-2.0.5-1.fc23` has been pushed to the `r3.1` testing repository for the Fedora `fc23` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.1-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-pdf-converter/compare/55f0a6420cc19ddb9a5d271cc70e89c1e97281e3...193d70377e2597cbbad061a5380a04204d674b49

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-pdf-converter-dom0-2.0.5-1.fc20` has been pushed to the `r3.1` testing repository for dom0.
To test this update, please install it with the following command:
```
sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-pdf-converter/compare/55f0a6420cc19ddb9a5d271cc70e89c1e97281e3...193d70377e2597cbbad061a5380a04204d674b49

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-pdf-converter-2.0.5-1.fc23` has been pushed to the `r3.2` stable repository for the Fedora `fc23` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-pdf-converter/compare/55f0a6420cc19ddb9a5d271cc70e89c1e97281e3...193d70377e2597cbbad061a5380a04204d674b49

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-pdf-converter-2.0.5-1.fc24` has been pushed to the `r3.2` stable repository for the Fedora `fc24` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-pdf-converter/compare/55f0a6420cc19ddb9a5d271cc70e89c1e97281e3...193d70377e2597cbbad061a5380a04204d674b49

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-pdf-converter-dom0-2.0.5-1.fc23` has been pushed to the `r3.2` stable repository for dom0.
To install this update, please use the standard update command:
```
sudo qubes-dom0-update
```
Or update dom0 via Qubes Manager.

[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-pdf-converter/compare/55f0a6420cc19ddb9a5d271cc70e89c1e97281e3...193d70377e2597cbbad061a5380a04204d674b49

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-pdf-converter_2.0.5-1+deb8u1` has been pushed to the `r3.2` stable repository for the Debian `jessie` template.
To install this update, please use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-pdf-converter/compare/55f0a6420cc19ddb9a5d271cc70e89c1e97281e3...193d70377e2597cbbad061a5380a04204d674b49

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-pdf-converter_2.0.5-1+deb8u1` has been pushed to the `r3.1` testing repository for the Debian `jessie` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `jessie-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-pdf-converter/compare/55f0a6420cc19ddb9a5d271cc70e89c1e97281e3...193d70377e2597cbbad061a5380a04204d674b49

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-pdf-converter_2.0.5-1+deb9u1` has been pushed to the `r3.1` testing repository for the Debian `stretch` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `stretch-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-pdf-converter/compare/55f0a6420cc19ddb9a5d271cc70e89c1e97281e3...193d70377e2597cbbad061a5380a04204d674b49

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-pdf-converter_2.0.5-1+deb7u1` has been pushed to the `r3.1` testing repository for the Debian `wheezy` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `wheezy-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-pdf-converter/compare/55f0a6420cc19ddb9a5d271cc70e89c1e97281e3...193d70377e2597cbbad061a5380a04204d674b49

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-pdf-converter-2.0.5-1.fc21` has been pushed to the `r3.1` stable repository for the Fedora `fc21` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-pdf-converter/compare/55f0a6420cc19ddb9a5d271cc70e89c1e97281e3...193d70377e2597cbbad061a5380a04204d674b49

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-pdf-converter-2.0.5-1.fc22` has been pushed to the `r3.1` stable repository for the Fedora `fc22` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-pdf-converter/compare/55f0a6420cc19ddb9a5d271cc70e89c1e97281e3...193d70377e2597cbbad061a5380a04204d674b49

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-pdf-converter-2.0.5-1.fc23` has been pushed to the `r3.1` stable repository for the Fedora `fc23` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-pdf-converter/compare/55f0a6420cc19ddb9a5d271cc70e89c1e97281e3...193d70377e2597cbbad061a5380a04204d674b49

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-pdf-converter-dom0-2.0.5-1.fc20` has been pushed to the `r3.1` stable repository for dom0.
To install this update, please use the standard update command:
```
sudo qubes-dom0-update
```
Or update dom0 via Qubes Manager.

[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-pdf-converter/compare/55f0a6420cc19ddb9a5d271cc70e89c1e97281e3...193d70377e2597cbbad061a5380a04204d674b49

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-pdf-converter_2.0.5-1+deb8u1` has been pushed to the `r3.1` stable repository for the Debian `jessie` template.
To install this update, please use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-pdf-converter/compare/55f0a6420cc19ddb9a5d271cc70e89c1e97281e3...193d70377e2597cbbad061a5380a04204d674b49

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-pdf-converter_2.0.5-1+deb9u1` has been pushed to the `r3.1` stable repository for the Debian `stretch` template.
To install this update, please use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-pdf-converter/compare/55f0a6420cc19ddb9a5d271cc70e89c1e97281e3...193d70377e2597cbbad061a5380a04204d674b49

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-pdf-converter_2.0.5-1+deb7u1` has been pushed to the `r3.1` stable repository for the Debian `wheezy` template.
To install this update, please use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-pdf-converter/compare/55f0a6420cc19ddb9a5d271cc70e89c1e97281e3...193d70377e2597cbbad061a5380a04204d674b49
