### ISSUE TITLE
Screen flickers and goes blank in HP Elitebook 820

### ISSUE THREAD

**Issue by ikar40** [QubesOS/qubes-issues#1794]
After a fresh install of Qubes 3.1, the screen on my HP Elitebook 820 has started flickering (alternating rapidly between bright and dark tones) and occasionally going completely blank. When the screen goes blank, I can recover my work by closing the lid (i.e. suspending) and then resuming the session, although this does not resolve the flickering. This problem did not happen on Qubes 3.

**Comment by marmarek** [comment]
Do you have any errors from kernel (`dmesg`) or X server (`/var/log/Xorg.0.log`)?

A couple ideas:
 - ensure you have `i915.preliminary_hw_support=1` kernel command line option (it should be there  in 3.1 clean install)
 - try adding `iommu=no-igfx` option to Xen (`multiboot` line in Grub)

Also, you may receive better support for hardware-related problems on qubes-users mailing list.

**Comment by ikar40** [comment]
There doesn't seem to be anything fishy in Xorg.0.log.
dmesg does shows plenty of lines with the following error message:

i915 0000:00:02.0: BAR 6: [??? 0x00000000 flags 0x2] has bogus alignment

but <a href="http://www.monperrus.net/martin/Linux-on-a-HP-Elitebook-820">some googling </a> seems to suggest that that's a different matter (related to PCI scanning).

**Comment by axon-qubes** [comment]
I'm assuming this issue has been resolved based on the lack of recent activity. If not, please feel free to re-open it.
