### ISSUE TITLE
Qubes 3.1 rc3 - HP Pavilion with Mediatek Adapter MT7630e - WiFi disabled

### ISSUE THREAD

**Issue by appleisit** [QubesOS/qubes-issues#1797]
The WiFi adapter is recognized and is attached to sys-net, but shows as "device not managed" and hence, I am unable to use WiFi.

Please let me know how to get WiFi to work (even a workaround is great :) ) -

Thanks,
Srini

**Comment by marmarek** [comment]
Generally it's better to write to [qubes-users](https://www.qubes-os.org/doc/mailing-lists/) with hardware-related questions.
Check kernel messages in sys-net (`dmesg` command in terminal). probably some missing firmware, or driver.
