### ISSUE TITLE
Design libvirt xml template search paths

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#1798]
Allow overriding default template (`xen.xml`) with user-provided one (`/etc/qubes/templates`?). Also allow override it per-VM.

**Comment by marmarek** [comment]
AFAIR there was a reason why VM directory (`/var/lib/qubes/appvms/some-name`) cannot be used. @woju can you post it here for reference?

**Comment by woju** [comment]
On Thu, Oct 06, 2016 at 10:37:02AM -0700, Marek Marczykowski-Górecki wrote:
> AFAIR there was a reason why VM directory (`/var/lib/qubes/appvms/some-name`)
> cannot be used. @woju can you post it here for reference?

I don't recall why you can't use `/var/lib/qubes`. But there is a reason for
using `/etc`: if you have single override file [1], you can write some logic
like `{% if vm.<property> = '<value>' %}` that applies to more than 1 domain.
It can't be done with per-vm templates.

So I did per-vm templates also in `/etc` mainly for consistency.

[1] (currently `/etc/qubes/templates/libvirt/xen-user.xml`, though I'm not
attached to it)

-- 
pozdrawiam / best regards       _.-._
Wojtek Porczyk               .-^'   '^-.
Invisible Things Lab         |'-.-^-.-'|
                             |  |   |  |
 I do not fear computers,    |  '-.-'  |
 I fear lack of them.        '-._ :  ,-'
    -- Isaac Asimov             `^-^-_>
