### ISSUE TITLE
File copy/move error not given window focus

### ISSUE THREAD

**Issue by bnvk** [QubesOS/qubes-issues#1802]
I accidentally misspelled the name of a VM I was moving a file to and I didn't notice that it failed for a while, because the dom0 window titled `Error` was hidden behind everything else. Thus the message:

```
Domain 'non-existent` does't exist (service qubes.Filecopy called by domain originating).
```

Was not seen. Interestingly, when I tried the action with the correct name, the alert window did grab focus on the top of the screen!

**Comment by marmarek** [comment]
This may be related to focus stealing prevention setting. What you have there?

**Comment by unman** [comment]
@andrewdavidwong We have been unable to reproduce this issue in 3.2
