### ISSUE TITLE
Qubes Manager crash, R3.1-rc3: 'AttributeError'

### ISSUE THREAD

**Issue by pugege** [QubesOS/qubes-issues#1804]
New intermittent Qubes Manager R3.1-rc3 crash:
AttributeError: 'module' object has no attribute 'VIR_
INTERNAL_ERROR'

----
line: elif e.get_error_code() == libvirt.VIR_INTERNAL_ERROR:
func: is_running
line no.: 935
file: /usr/lib64/python2.7/site-packages/qubes/modules/000QubesVm.py
----
line: if not vm.is_running():
func: measure_cpu_usage
line no.: 234
file: /usr/lib64/python2.7/site-packages/qubes/qubes.py
----
line: self.last_measure_time)
func: update_table
line no.: 768
file: /usr/lib64/python2.7/site-packages/qubesmanager/main.py

pugege

**Comment by marmarek** [comment]
I think I have it already fixed, but it isn't included in any released package yet. Anyway thanks for the report!

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-dom0-3.1.14-1.fc20` has been pushed to the `r3.1` testing repository for dom0.
To test this update, please install it with the following command:
```
sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-admin/compare/fa66fec684f823bfefe5355813342426ce8a20e1...9ac0cf85779ba9a469f70fd92634979c055db59f

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-dom0-3.1.14-1.fc20` has been pushed to the `r3.1` stable repository for dom0.
To install this update, please use the standard update command:
```
sudo qubes-dom0-update
```
Or update dom0 via Qubes Manager.

[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-admin/compare/fa66fec684f823bfefe5355813342426ce8a20e1...9ac0cf85779ba9a469f70fd92634979c055db59f
