### ISSUE TITLE
mce: Unable to init device /dev/mcelog (rc:-16) , (Qubes crushed down)

### ISSUE THREAD

**Issue by TNTBOMBOM** [QubesOS/qubes-issues#1805]
i have updated fedora just like any normal distro updating then restarted my pc and found that it wont log me in to Qubes but instead it shows black page (kinda like a console or ui page) saying this:- 

>mce: Unable to init device /dev/mcelog (rc:-16)
nouveau E[ PIBUS][00000:01:00.0] HUB0: 0x10ecc0 0xffffffff (0x1a50822c)
nouveau E[ PGRAPH][00000:01:00.0] failed to load fuc409c
nouveau E[ DEVICE][00000:01:00.0] failed to create 0x18000718, -22 
nouveau E[ DRM] failed to create 0x00000080, -22
irq 16: nobody cared (try booting with the "irqpoll" option)
handlers:
`[<ffffffff81521910>] usb_hcd_irq`

>Generating "/run/initramfs/rdsosreport.txt"

>Entering emergency mode. Exit the shell to continue.
Type "journalctl" to view system logs.
You might want to save "/run/initramfs/rdsosreport.txt" to a USB stick or /boot
after mounting them and attach it to a bug report.

well there r three requests as i can c:- 

1- try booting with the "irqpoll" option?
2- Exit the shell to continue?
3-  save "/run/initramfs/rdsosreport.txt" to a USB stick or /boot?

how to do any of those things ???

**Comment by TNTBOMBOM** [comment]
any help over here ? i dont think there is more critical bug than killing Qubes from booting up?

im not using my own pc since 4 days , waiting for a solution...

**Comment by marmarek** [comment]
I think this issue is mistitled. It appears to be either noveau problem or that irq 16 (USB?). MCE is irrelevant here.

Anyway - have you tried adding `irqpoll` option to kernel command line (press 'e' in Grub, add it to the line with `vmlinuz` and boot with ctrl-x)

**Comment by TNTBOMBOM** [comment]
> I think this issue is mistitled. It appears to be either noveau problem or that irq 16 (USB?). MCE is irrelevant here.

i dont know what to name this issue , u can change the title to what u c it fits the content. 

> Anyway - have you tried adding irqpoll option to kernel command line (press 'e' in Grub, add it to the line with vmlinuz and boot with ctrl-x)?

nope i dont do these things without instructions , to avoid further missing up the machine. 

i have added irqpo11 as u have suggested , these messages disappeared:- 

`mce: Unable to init device /dev/mcelog (rc:-16)`

and

`irq 16: nobody cared (try booting with the "irqpoll" option)
handlers:`
`[<ffffffff81521910>] usb_hcd_irq`

but nouveau list even increased.

**Comment by TNTBOMBOM** [comment]
(btw i have re-installed Qubes entirely because not even Qubes rescue option solved my issue)

**Comment by axon-qubes** [comment]
> (btw i have re-installed Qubes entirely because not even Qubes rescue option solved my issue)

Does this mean that this issue should now be closed?

**Comment by TNTBOMBOM** [comment]
the issue did not fixed , but nor there will be any other information i can provide about it. 

so u can close it , unless there will be further similar reports regarding it.
