### ISSUE TITLE
Skylake laptop won't resume from sleep

### ISSUE THREAD

**Issue by brokenjacobs** [QubesOS/qubes-issues#1810]
I have QUBES 3.1-rc3 running on a Dell Latitude E7270 with an Intel i5-6300U cpu. Whenever the system goes to sleep I am unable to wake it properly and have to force power cycle the system. Sometimes there is graphics corruption (rainbow stripes down the screen), but usually the screen is just blank. I have disabled Screen Energy Saving in the KDE System settings utility, but that does not seem to make any difference.

I can cause the problem by closing the laptop lid, or by waiting for the system to go to sleep.

Is there any sort of diagnostics information I can gather to help find the root cause of this issue? Everything else on this laptop seems to be working fine.

**Comment by brokenjacobs** [comment]
A little googling and pm tracing seems to turn up some power management changes in Linux 4.3 related to Skylake CPU's. Of course I don't know how to confirm that any of this is the issue, since its seemingly a graphics issue that I am having.

http://permalink.gmane.org/gmane.linux.kernel.pci/44792
intel_pstate driver updates including Skylake-S support, support
   for enabling HW P-states per CPU and an additional vendor bypass
   list entry (Kristen Carlson Accardi, Chen Yu, Ethan Zhao).

 - intel_idle driver updates including Skylake Client support and
   support for freeze-mode-specific idle states (Len Brown).

 - Power capping RAPL driver update including support for Skylake H/S
   and Broadwell-H (Radivoje Jovanovic, Seiichi Ikarashi).

**Comment by marmarek** [comment]
Please discuss hardware related problems on [qubes-users](https://www.qubes-os.org/doc/mailing-lists/) mailing list.

**Comment by marmarek** [comment]
You may experiment with `xenpm` tool, if that's really about power management. Try for example setting max-cstate to 0.
