### ISSUE TITLE
(R4.0) Feature parity with R3.1

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#1825]
This is tracking list of major things to (re-)implement in core3/Qubes 4.0:
- [x] DispVM #2253
- [x] backups
- [x] qubes-manager
- [x] qvm-\* tools
- [x] migration tool (`qubes.xml` conversion)
- [x] HVM
- [x] tests
- [x] storage
- [x] "qvm-block"
- [x] Salt mgmt stack
- [x] appmenus handling #1897
- [x] devices handling: qvm-pci, qvm-usb etc (and underlying API) #2257

**Comment by Jeeppler** [comment]
What is the goal in rewriting the qvm-* tools? Performance? Python 3 compatibility? Code structure?

**Comment by marmarek** [comment]
Adjust to work with rewritten core. And better code structure.

**Comment by kalkin** [comment]
woju/qubes-core-admin#24 qvm-shutdown fixes
woju/qubes-core-admin#25 qvm-remove fixes

Need to be synced with this repo core3-devel ones merged

**Comment by kalkin** [comment]
Also `qvm-block(1)` is already implemented in the current [core3-devel](https://github.com/QubesOS/qubes-core-admin/tree/core3-devel) branch.

**Comment by marmarek** [comment]
For migration tool: it needs further tests restoring file-based volumes into LVM-based volumes.

**Comment by kalkin** [comment]
Salt-stack current prs:
QubesOS/qubes-mgmt-salt/pull/2
QubesOS/qubes-mgmt-salt-base/pull/2
QubesOS/qubes-mgmt-salt-base-overrides/pull/2
/QubesOS/qubes-mgmt-salt-dom0-virtual-machines/pull/4
