### ISSUE TITLE
nm-applet systray needlessly automatically started in non-networked VMs usability issue

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#1827]
My work-gpg VM that has its NetVM set to `none` automatically starts `nm-applet`. (Found in `ps aux`.) It gets visible in systray. The tooltip says `NetworkManager is not running...`.

It's confusing. Usability issue.

https://github.com/QubesOS/qubes-core-agent-linux/blob/master/autostart-dropins/nm-applet.desktop

**Comment by marmarek** [comment]
nm-applet is automatically hidden if network-manager isn't running: https://github.com/QubesOS/qubes-core-agent-linux/blob/master/network/show-hide-nm-applet.sh
Which template? Do you have this script referenced in `/etc/xdg/autostart/00-qubes-show-hide-nm-applet.desktop`? What happens when you call it manually?

**Comment by adrelanos** [comment]
> Which template?

Debian template.

> Do you have this script referenced in /etc/xdg/autostart/00-qubes-show-hide-nm-applet.desktop?

Yes.

> What happens when you call it manually?

```
sh -x /usr/lib/qubes/show-hide-nm-applet.sh
```
```
+ type nm-applet
+ nm_enabled=false
+ [ -f /var/run/qubes-service/network-manager ]
+ gsettings set org.gnome.nm-applet show-applet false

(process:1911): dconf-WARNING **: failed to commit changes to dconf: GDBus.Error:org.gtk.GDBus.UnmappedGError.Quark._g_2dfile_2derror_2dquark.Code1: Cannot open dconf database: Error reading file '/home/user/.config/dconf/user': Is a directory
```

**Comment by marmarek** [comment]
> `(process:1911): dconf-WARNING **: failed to commit changes to dconf: GDBus.Error:org.gtk.GDBus.UnmappedGError.Quark._g_2dfile_2derror_2dquark.Code1: Cannot open dconf database: Error reading file '/home/user/.config/dconf/user': Is a directory`

Interesting. In my (Debian) VM it is a file. Any idea what created a directory there?

**Comment by adrelanos** [comment]
There is just one file there.

/home/user/.config/dconf/user/a

Which is a gpg key that I imported ages ago. No idea how it ended up there.

Executed `rm -r /home/user/.config/dconf/user`. Which made the
unnecessary nm-applet system go away after reboot!
