### ISSUE TITLE
Upgrading R3.0 -> R3.1 in-place: dom0 error messages

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#1829]
I tried using the "experimental" upgrade procedure again to upgrade a vanilla R3.0 installation to R3.1. It seemed to go smoothly, but I noticed a few error/warning messages in dom0 along the way. I went back through my logs and cataloged them all. Here they are:

```
[...]
  Updating    : qubes-core-dom0-3.1.13-1.fc20.x86_64
Redirecting to /bin/systemctl start xenstored.service
A dependency job for xenstored.service failed. See 'journalctl -xn' for details.
[...]
```

```
[...]
  Cleanup    : 2001:xen-runtime-4.4.3-11.fc20.x86_64
warning: /etc/udev/rules.d/xen-backend.rules saved as /etc/udev/rules.d/xen-backend.rules.rpmsave
[...]
```

```
[...]
Generating grub.cfg ...
[...]
done
awk: fatal: cannot open file `/boot/efi/EFI/qubes/xen.fg` for reading (No such file or directory)
error: %preun(kernel-1000:3.18.17-7.pvops.qubes.x86_64) scriptlet failed, exit status 2
Error in PREUN scriptlet in rpm package 1000:kernel-3.18.17-7.pvops.qubes.x86_64
  Cleanup     : libvirt-python-1.2.12-1.fc20.x86_64
error: kernel-1000:3.18.17-7.pvops.qubes.x86_64: erase failed
[...]
```

Are any of these serious?

Either way, I hope this datapoint is helpful for determining whether in-place upgrades should remain an experimental feature or not.

**Comment by marmarek** [comment]
It looks like none of those is serious, but still it would be better to not have any errors/warnings like this...
The one with kernel is somehow concerning - probably a missing check for touching EFI files on non-EFI system. Did you get something similar for installing new kernel package too?

I'd add to the list:
- [ ] describe how to create sys-usb in upgrade instruction (or simply link to https://www.qubes-os.org/doc/usb/#tocAnchor-1-1-2)

**Comment by axon-qubes** [comment]
> The one with kernel is somehow concerning - probably a missing check for touching EFI files on non-EFI system. Did you get something similar for installing new kernel package too?

I didn't have any error/warning messages about installing the new kernel package, only the one posted above about attempting to erase `kernel-1000:3.18.17-7.pvops.qubes.x86_64`.

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-dom0-linux-3.1.11-1.fc20` has been pushed to the `r3.1` testing repository for dom0.
To test this update, please install it with the following command:
```
sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-admin-linux/compare/f44b268299957463172109081351d753f53c930b...58c3f2221fb55b4471192c6199c571c920035f97

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-dom0-linux-3.1.12-1.fc20` has been pushed to the `r3.1` stable repository for dom0.
To install this update, please use the standard update command:
```
sudo qubes-dom0-update
```
Or update dom0 via Qubes Manager.

[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-admin-linux/compare/f44b268299957463172109081351d753f53c930b...f5ad47b73fc0169fbeb51d1a96efc6d5ef5afc61
