### ISSUE TITLE
UpdateVM system defaults should only list NetVMs and ProxyVMs

### ISSUE THREAD

**Issue by mfc** [QubesOS/qubes-issues#1831]
Currently in Qubes VM Manager > System > System defaults > UpdateVM, it lists all VMs as possibilities for `UpdateVM`. It should only list netvms and proxyvms. Probably the same should be done for `ClockVM`.

**Comment by marmarek** [comment]
Why? It is perfectly fine to have any AppVM set there. For example a VM behind Tor, or VPN, to be sure that yumdownloader/ntpdate will not see real IP.

**Comment by mfc** [comment]
> For example a VM behind Tor, or VPN, to be sure that yumdownloader/ntpdate will not see real IP.

those VMs are ProxyVMs, no?

**Comment by mfc** [comment]
> Why?

I can't think of a single use-case where a user should be putting their network traffic through a "qube" (AppVM) or a template, rather than a ProxyVM.

**Comment by marmarek** [comment]
> those VMs are ProxyVMs, no?

But those ProxyVMs itself see the real IP. Only VMs behind are are really isolated. I think Whonix gateway is some exception here - it also torify traffic originating directly from it.

(I agree templates are useless on that list)

**Comment by adrelanos** [comment]
Marek Marczykowski-Górecki:
> I think Whonix gateway is some exception here - it also torify traffic originating directly from it.

Yes.

**Comment by bnvk** [comment]
> But those ProxyVMs itself see the real IP. Only VMs behind are are really isolated. I think Whonix gateway is some exception here - it also torify traffic originating directly from it.

So, then perhaps the solution I think @mfc is after (making this selection process more simple + safe for users) is to *only* show AppVMs, or Whonix gateway so as to not allow users to accidentally leak their real IP

**Comment by axon-qubes** [comment]
> Probably the same should be done for `ClockVM`.

IIUC, this part is much more complicated. See:

 * https://www.whonix.org/wiki/Dev/Qubes#Time_Sync
 * https://www.whonix.org/wiki/Dev/TimeSync
 * https://groups.google.com/forum/#!msg/qubes-devel/YHK_rAUm0s0/ARrBPHrf0fkJ
 * https://groups.google.com/d/msg/qubes-users/AqZV65yZLuU/Lh8T7ZL6tdIJ
 * https://groups.google.com/d/msg/qubes-devel/XN6JrEXVOVA/c1S07O8VpfMJ
 * https://groups.google.com/d/topic/qubes-users/3QNzrcoRyMI/discussion
