### ISSUE TITLE
Debian templates: get added to Derivatives Census

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#1834]
What this is about:
https://wiki.debian.org/Derivatives/Census

Why is it useful to be on this list:
- From time to time, issues are pointed out. Example...
- https://lists.debian.org/debian-derivatives/2016/03/msg00005.html
- https://lists.debian.org/debian-derivatives/2016/03/msg00008.html

Example census page, Whonix:
https://wiki.debian.org/Derivatives/Census/Whonix

TODO:
- sign up for the https://lists.debian.org/debian-derivatives/
- fill out the template - https://wiki.debian.org/Derivatives/CensusTemplate
- add to https://wiki.debian.org/Derivatives/Census/Qubes ?

Whom:
I can do most of the TODO items. But $someone (in reality mostly @marmarek) would sign up on debian-derivatives mailing list. (With a secondary account.) Someone who may speak officially for Qubes. Maybe not required. Since I am signed up for that mostly-low traffic list anyhow, I could also function as a proxy. Then this wiki page would be no more burden than "yet another wiki page about Qubes on a third party page (debian.org)".

question:
Use e-mail addresses encoded `security at qubes-os dot org` or with `@`?

Since outreach is related, //cc @mfc.

**Comment by mfc** [comment]
this sounds like a good idea. @marmarek what would you prefer? patrick to sign up? @unman as debian template maintainer?

**Comment by unman** [comment]
@rootkovska @marmarek @mfc @adrelanos @andrewdavidwong 
I've added Qubes as a derivative and populated the page with some information. 
https://wiki.debian.org/Derivatives/Census/Qubes
If you want any changes/additions please let me know here.

**Comment by marmarek** [comment]
Thanks @unman !
I'd add:
 - Blog: https://www.qubes-os.org/news/
 - Corporate sponsor: Invisible Things Lab
 - Research publications: https://www.qubes-os.org/research/
 - Build status: https://github.com/QubesOS/qubes-issues/blob/master/travis_status.md

**Comment by andrewdavidwong** [comment]
Would it make sense to link to the HCL for "hardware supported"?

And perhaps it would make sense to link to @rootkovska's [blog](https://blog.invisiblethings.org/) under "developer blogs"?

**Comment by unman** [comment]
I wondered about the HCL - I'll do that for sure.
On the blog link, if Joanna is happy with that, no problem. Let me know @rootkovska 
anything else?

**Comment by rootkovska** [comment]
No problem with adding a link to my blog. Although: 1) my blog is somehow more generic than just about Qubes dev, and 2) any Qubes-specific posts are also cross-posted on the Qubes blog or at least linked from the Qubes Research section. So, perhaps this might be a bit redundant?

**Comment by unman** [comment]
@andrewdavidwong I've added the HCL, but not Joanna's blog in light of her comments.
I think this can be closed now, unless @mfc has any comment?

**Comment by andrewdavidwong** [comment]
Thanks, @unman. Closing.

(@mfc: Feel free to reopen/comment if needed.)
