### ISSUE TITLE
Fix heading spacing

### ISSUE THREAD

**Issue by bnvk** [QubesOS/qubes-issues#1837]
A change introduced to the SASS this morning now causes this

![qubes-site-whitepsace-error](https://cloud.githubusercontent.com/assets/48677/13783991/da984746-eacd-11e5-8f1a-f1c0756f2594.png)

I've figured out the issue, it was specifically, [this commit](https://github.com/QubesOS/qubesos.github.io/blob/3bb63362c0bf16d7c5fd28957027d2bde19cfe33/_sass/_layout.scss#L58-L60) made earlier today. What were you trying to achieve @axon-qubes ?

**Comment by axon-qubes** [comment]
Thank you to you and @mfc for spotting this and pointing it out. I've just reverted that commit.

I mentioned in my commit message what I was trying to achieve. To quote:
>  Fix heading spacing
> 
> Makes it so that each paragraph heading is closer to its own paragraph than to the previous paragraph.

Here's a screenshot of what I mean:

![1](https://cloud.githubusercontent.com/assets/10417133/13789133/96ef994c-eada-11e5-82fc-73ec191bdee7.png)

See how each paragraph heading is noticeably closer to the previous paragraph than to its own paragraph? (Might be easier to see on text-only pages, but it's evident on any page with headings and paragraphs.) I was just trying to fix that. I checked every type of page except the front page, and they all looked better, but it was my fault for not checking the front page.

Evidently my approach will not work, so would you mind taking a stab at it, @bnvk?

**Comment by bnvk** [comment]
> Fix heading spacing
> 
> Makes it so that each paragraph heading is closer to its own paragraph than to the previous paragraph.

Yah, I saw that commit message, but the `.white-boxe` class is something that creates the large white "background" boxes for the whole site, hence why it broke the layouts!

Yah, those margins between the titles was something that got screwed up in the merge, as there is supposed to be `<hr class="more-top more-bottom">` anywho, I just sent a pull-req for that!

**Comment by axon-qubes** [comment]
> Yah, I saw that commit message, but the .white-boxe class is something that creates the large white "background" boxes for the whole site, hence why it broke the layouts!

I know, but we need some way to create proper spacing between sections without pushing the very first heading down (hence the negative margin).

> Yah, those margins between the titles was something that got screwed up in the merge, as there is supposed to be <hr class="more-top more-bottom"> anywho, I just sent a pull-req for that!

Actually, the problem was there before that merge, and it's back again now. Another screenshot to illustrate:

![2](https://cloud.githubusercontent.com/assets/10417133/13790437/56a17db4-eae0-11e5-8791-37ab7b91a2e3.png)

**Comment by axon-qubes** [comment]
As @mfc has pointed out in #1869, the problem is even more pronounced when viewing certain pages on "narrow" screens (even ones which aren't that narrow). Example:

![7](https://cloud.githubusercontent.com/assets/10417133/13971367/a5ccb7b2-f087-11e5-936d-abbde0f942a1.png)

**Comment by bnvk** [comment]
Fxed this with recent commit. @axon-qubes feel free to verify if ya dig!

**Comment by axon-qubes** [comment]
The spacing of regular text headings look better, but the heading issue from [this](https://cloud.githubusercontent.com/assets/10417133/13971367/a5ccb7b2-f087-11e5-936d-abbde0f942a1.png) screenshot looks unchanged.

**Comment by bnvk** [comment]
@axon-qubes yah that's an issue with [Bootstraps CSS grid](http://getbootstrap.com/css/#grid) and making it properly responsive. This is being tracked in #1869 thanks ;)
