### ISSUE TITLE
Already assigned devices should not be listed as "available" under VM Settings > Devices of other VMs

### ISSUE THREAD

**Issue by mfc** [QubesOS/qubes-issues#1838]
reproduce by assigning devices to a VM (say the USB devices to the default `sys-usb`). Go to VM Settings > Devices of another VM. Those controllers should not be assignable to other VMs.

Reported at the [Internet Freedom Festival](https://internetfreedomfestival.org).

**Comment by marmarek** [comment]
I agree those devices shouldn't be listed in Qubes Manager. Also it would be good idea to exclude system critical components (host bridge, PCI bridge, primary SATA controller etc).
But there are some cases when assigning the same device to multiple VMs makes sense - for example you may have alternative USB VM used only for video chats (as it isn't currently possible to attach single USB device to another VM). Of course you can't run both of them at the same time, but still should be possible. IMHO leaving this option only from `qvm-pci` command line tool is good enough.

**Comment by bnvk** [comment]
The case @mfc brings up here, I have run into and it failed in a confusing and less than ideal way. Ironically, this case came up, because I was trying to do what @marmarek mentions

> But there are some cases when assigning the same device to multiple VMs makes sense

I'll think about if there is a better way to handle this in the new Qubes Manager I'm working on!

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.

**Comment by mfc** [comment]
this is still an issue so i am re-opening and putting "Far in the Future" milestone.

**Comment by andrewdavidwong** [comment]
It doesn't make sense for a bug to be "far in the future." Either the bug exists in a supported release, or it does not. We don't plan to implement bugs in the future, though we know some will show up anyway. :)

I'm guessing that the bug must be present in 4.0, then.

**Comment by mfc** [comment]
makes sense, i will do the same for the other bugs that are still present.

**Comment by marmarta** [comment]
I don't think it makes sense anymore; Qube Manager does not have devices, the device widget is device-first, and in Settings it can make sens to assign a device to two VMs (they will not be able to be running at the same time, but this is an imagineable situation). Closing this, unless someone wants to correct me?
