### ISSUE TITLE
License GPL, BSD?

### ISSUE THREAD

**Issue by jirib** [QubesOS/qubes-issues#1840]
Hi,
could you consider BSD license for your code? It could make spread of part of your great work to BSD world.

OpenBSD has recently developed its own hypervisor and it would be awesome to see your agents for gui, file sharing work with OpenBSD vmm. They support some Virt-IO devices thus it could not be hard to make virtio-channel as replacement for Xen's vchannel.

**Comment by marmarek** [comment]
Currently we do not consider changing license to BSD. That would allow anyone to take our code and release it as closed-source product - we don't want that, at least not without our explicit permission.
