### ISSUE TITLE
Website navigation bar

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#1841]
Some thoughts and questions about the top nav bar. Here's a current screenshot, in case you can't go to the page right now:

![3](https://cloud.githubusercontent.com/assets/10417133/13810895/369b290e-eb6a-11e5-8ab3-ab0f79878573.png)

 * I feel like a direct link to the **Downloads** page is missing from the top navigation bar. Should there be a link there, or is it fine just to have it on the front page and inside the **Getting Started** page?

 * I wonder if the **Help** page is somewhat redundant. Everything on that page is already linked directly from the **Docs** page except the StackExchange and IRC links. Maybe those last two should just be moved to the front page, where we already have a **Follow & Contact** section (and perhaps duplicated elsewhere)?

 * There seems to be an issue where **Getting Started** hangs below that horizontal line on narrower screens (see screenshot below). @bnvk, how should we fix that? Maybe getting rid of **Help** would free up enough space? Or, if we don't want to do that, maybe changing that name to something shorter? "Getting Started" is definitely the longest title in that list. Maybe **Tour** and **Getting Started** should somehow be combined. It may not be clear to visitors what exactly the difference is.

![4](https://cloud.githubusercontent.com/assets/10417133/13810930/581ee9da-eb6a-11e5-9d15-6146f526e130.png)

 * I've noticed that a lot of websites incorporate their "search" function into the top nav bar. Should we do that too? Currently, we have a search bar at the bottom of each page, but it takes up kind of a lot of space, and users might miss it since it's at the bottom.

![5](https://cloud.githubusercontent.com/assets/10417133/13810933/5cdfd39e-eb6a-11e5-93ab-615a6048b18f.png)

 * On mobile devices, the navigation bar seems to disappear (see screenshot below). At first, I thought it was just collapsing into the **Q** icon, where it would be accessible from a pop-out menu of some sort (as is common in responsive designs), but no menu shows up when I click the **Q** icon. (I'm just testing this on Firefox using "responsive view" mode, so maybe it functions differently on actual mobile devices?) It might also be nice to have "Qubes OS" in the center of that bar, rather than just the logo on the left, and empty space everywhere else.

![6](https://cloud.githubusercontent.com/assets/10417133/13811162/e1174af6-eb6b-11e5-883e-e5f56b80b62f.png)

**Comment by mfc** [comment]
hmmm re: "getting/get started", sounds like we need to just have one word then. "start"? adding @bnvk to this more general thread.

**Comment by bnvk** [comment]
@axon-qubes @mfc the `Getting Started` wrapping issue, as well as showing the click to view "responsive menu" on mobile devices should be fixed now. Please verify (be sure to Ctrl+R hard refresh for caching).

**Comment by axon-qubes** [comment]
@bnvk: Looks good! Thanks for doing that! :)

**Comment by bnvk** [comment]
You could probably close this issue then. I'd do it, but I don't have access on this repo. There seems to be a trend with `C:website` issues that they just stay open. We should have a policy of something like: *"once a fix for something has been reviewed by @axon-qubes @mfc @marmarek or myelf it should be closed"*

**Comment by marmarek** [comment]
> I'd do it, but I don't have access on this repo.

Try now.

**Comment by axon-qubes** [comment]
Agree that @bnvk should have the ability to close issues in this repo.

However, this particular issue should not be closed yet, IMHO, because it points out several issues which have not been addressed, whether that means fixing them or declaring them wontfix, notabug, etc.

**Comment by axon-qubes** [comment]
@bnvk: If you want, I can turn it into a list of tasks, then mark off the one which has been completed.

**Comment by bnvk** [comment]
@axon-qubes as far as I can tell, the points not implemented yet are:

- [ ] Combine "Docs & Help"
- [ ] Move "Search Box" to topbar
- [ ] Combine "Tour & Getting Started"

I can see 1 and 2 working well, but i'm unsure about 3. See #1833 for more details. In anycase, i'll knock these out soon!
