### ISSUE TITLE
Populate "Qubes Release Notes"

### ISSUE THREAD

**Issue by axon-qubes** [QubesOS/qubes-issues#1843]
There is now a working "Release Notes" button (#1259). However, when I click it (on R3.1), it says:

```
README.Qubes-Release-Notes
=====================================

This is a placeholder. There are no useful release notes in here.

Sorry about that.
```

I checked the `qubes-manager` code and saw that it pulls this text from `/usr/share/doc/qubes-release-notes/README.Qubes-Release`, and this is indeed the case on my system.

Since we already have actual release notes for R3.1 (`/doc/releases/3.1/release-notes/`), I would like to help replace the placeholder text with the actual release notes, but I'm not sure where to put them so that they'll end up in `/usr/share/doc/qubes-release-notes/README.Qubes-Release`.

**Comment by marmarek** [comment]
The properly filled release notes file is already a part of
qubes-release-3.1-1 package.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by axon-qubes** [comment]
Oh, ok. Already done, then! :)
