### ISSUE TITLE
Add filename= parameter to Qubes.save()

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#1846]

**Comment by bnvk** [comment]
@marmarek what will the `filename=` parameter allow or be used for?

**Comment by marmarek** [comment]
To save VMs information to alternative file. Useful for migration etc.
It will be optional and in fact rarely used.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?
