### ISSUE TITLE
Graphically separate system-oriented vm from other appvm in qubes-manager

### ISSUE THREAD

**Issue by Scinawa** [QubesOS/qubes-issues#1853]
Hi
What do you think of creating a different graphical icon/style for AppVM such as 
1. netvm
2. sys-firewall
3. disp-vm
3. backup-vm
4. usb-vm

They are equivalent to other appvm but they should be treated "graphically differently" in qubes-manager, as it is already the case for template machines. Moreover, none of this vm needs backups (assuming that you use an external usb for your backups)

Any thoughts?

**Comment by andrewdavidwong** [comment]
Possible duplicate of #1870.

**Comment by andrewdavidwong** [comment]
This issue is now a duplicate of (more precisely, has been superseded by) #2132. Part of the reason is that #2132 will attempt to hide these types of VMs (i.e., "the Qubes infrastructure") from the user.
