### ISSUE TITLE
Remove "pause VM" button from Qubes Manager

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#1855]
Currently this is [not](https://github.com/QubesOS/qubes-issues/issues/1663#issuecomment-198596160) the case. #1663 implemented running suspend / resume scripts on host suspend / resume, but not on VM pause / resume in QVMM.

I think this has a good chance of causing some confusion for example for #1764. Users might pause their sys-whonix using QVMM for various reasons. (make more RAM available, travel with Tor disabled, etc.) Then when they resume sys-whonix, they will be confused. (Just as #1663 caused confusion.)

Please implement running suspend / resume scripts also on VM pause / resume.

**Comment by marmarek** [comment]
I think this is bad idea, especially `qubes.SuspendPreAll` there. Pausing a VM may be used also if you spot some misbehaving of a VM and want to collect some evidences (memory dump etc). Then letting the VM know it will be paused in a moment is the worst thing to do...

> make more RAM available

Pausing VM doesn't release RAM.

Also if you want to simply cut `sys-whonix` out of network access, do exactly that by setting its netvm to none, not use a side effect of pausing VM. It will cause more problems than just that clock synchronization. For example if you start another `sys-whonix` connected VM, it will fail because backend driver will not initialize.
I think in the "pause" button in Qubes Manger in its current shape (without description what it really does) makes more confusion than good. Maybe it should be removed from there?

**Comment by adrelanos** [comment]
Marek Marczykowski-Górecki:
> I think this is bad idea, especially `qubes.SuspendPreAll` there.
> Pausing a VM may be used also if you spot some misbehaving of a VM
> and want to collect some evidences (memory dump etc). Then letting
> the VM know it will be paused in a moment is the worst thing to
> do...

I see.

>> make more RAM available
> 
> Pausing VM doesn't release RAM.
> 
> Also if you want to simply cut `sys-whonix` out of network access, do
> exactly that by setting its netvm to none, not use a side effect of
> pausing VM. It will cause more problems than just that clock
> synchronization. For example if you start another `sys-whonix`
> connected VM, it will fail because backend driver will not
> initialize. I think in the "pause" button in Qubes Manger in its
> current shape (without description what it really does) makes more
> confusion than good. Maybe it should be removed from there?

I think so, because it is confusing.

But maybe this is something very advanced people such as you (with
skills to analyze a memory dump) depend on? Then we need it as some
advancement option because we don't want to make your debugging harder.

And perhaps replaced by a VM freeze to disk feature [comparable to what
we are used to like other virtualizers] that gets the hooks dispatched?

**Comment by marmarek** [comment]
> I think so, because it is confusing. 
> But maybe this is something very advanced people such as you (with skills to analyze a memory dump) depend on? Then we need it as some advancement option because we don't want to make your debugging harder.

Maybe simply remove the button, but leave it in the context menu? Maybe also name it differently? But IMO "pause" is exactly what it does (not "suspend"). Or maybe remove it completely from Qubes Manager and leave only as command line option (I'm ok with that)?
 /cc @bnvk 

> And perhaps replaced by a VM freeze to disk feature [comparable to what we are used to like other virtualizers] that gets the hooks dispatched?

That's good idea, but we don't have support for it just now.

**Comment by bnvk** [comment]
> Maybe simply remove the button, but leave it in the context menu? Maybe also name it differently? But IMO "pause" is exactly what it does (not "suspend"). Or maybe remove it completely from Qubes Manager and leave only as command line option (I'm ok with that)?

Yep! I've never once pressed the `Pause` button. I have no idea what it does and no notifications have ever instructed me to use it. Hiding it in the existing GUI (and new Qubes Manager) sounds right choice to me!

**Comment by Rudd-O** [comment]
I use pause substantially.

Better document the appropriate use of the pause button on the tooltip, than to remove it.

**Comment by marmarek** [comment]
There are multiple issues with pause functionality:
 - #1611 (Explicitly paused VMs get started on system suspend/resume.)
 - VM clock gets desynchronized
 - some tools will hang on communication with paused VM

I think it is't mature enough to be exposed in Qubes Manager. But still should be available from command line interface. What do you think?

**Comment by Rudd-O** [comment]
Note these issues in the docs and in the tooltip, and then remove the
notes once the issues get fixed.  In my humble opinion.

You can also demote the pausing functionality to an advanced mode, if
you so choose.

The problems with communicating with paused VMs (in my view the most
grave problem) should be solved by either notifying the user that the
communication tool is going to hang, or by making the tool fail
explicitly and notify the user.

Usually if you pause a VM there is a reason why you want to pause it,
and relegating it to a multicharacter command line type session is
probably not a good idea.

-- 
    Rudd-O
    http://rudd-o.com/

**Comment by ttasket** [comment]
Pause can be very useful to the right people. But I think the key issues here are getting proper feedback in the UI, and distinguishing the user's intent in pausing the vm (versus some automatic trigger of pause, like sleep, which implies automatic un-pause).

I think pause should be indicated in the titlebars of each window of a paused vm. Perhaps also add a dom0 mouseover tooltip for them. Not sure if that needs a new issue.

**Comment by andrewdavidwong** [comment]
> I think pause should be indicated in the titlebars of each window of a paused vm. Perhaps also add a dom0 mouseover tooltip for them. Not sure if that needs a new issue.

I like that idea. As for whether it should be filed under a separate issue, that depends on the outcome of this issue. If this issue turns out to be a UX redesign of the pause functionality, your comment belongs here (IMHO). If this issue remains about removing/demoting access to the pause function from/in Qubes Manager, then your idea should probably be filed as a separate issue.

**Comment by Rudd-O** [comment]
On 06/13/2016 11:03 PM, Andrew David Wong wrote:
>
>     I think pause should be indicated in the titlebars of each window
>     of a paused vm. Perhaps also add a dom0 mouseover tooltip for
>     them. Not sure if that needs a new issue.
>
> I like that idea. As for whether it should be filed under a separate
> issue, that depends on the outcome of this issue. If this issue turns
> out to be a UX redesign of the pause functionality, your comment
> belongs here (IMHO). If this issue remains about removing/demoting
> access to the pause function from/in Qubes Manager, then your idea
> should probably be filed as a separate issue.
>

An icon "pause" ( || ) in the titlebar with a tooltip saying "This VM is
paused.  Check the Qubes manager to unpause it." or something of the sort?



-- 

    Rudd-O
    http://rudd-o.com/

**Comment by andrewdavidwong** [comment]
There are many possibilities. Could be something simple like:

Unpaused title bar:

```
[untrusted] Some Website - Mozilla Firefox
```

Paused title bar:

```
[untrusted | *PAUSED*] Some Website - Mozilla Firefox
```

I also like your tooltip suggestion above, @Rudd-O. Created #2211 for it.

**Comment by marmarta** [comment]
I've added a tooltip with explanation and warning (according to @andrewdavidwong's wording in https://github.com/QubesOS/qubes-issues/issues/2211 ) - I think this one can be closed.
