### ISSUE TITLE
UEFI install hangs on HP ProBook 4730s

### ISSUE THREAD

**Issue by Slazer** [QubesOS/qubes-issues#1857]
When entering the EFI install mode of Qubes 3.1 from a recently bought Kingston's DataTraveler® Elite 3.0 USB Flash drive, the installer hangs some 10-15 seconds in the boot process on [this screen](https://goo.gl/photos/QdTvz8csU9UwrUT49).

The installation has been created with dd, the consistency checks (using non-EFI boot) PASS and the OS can be installed using the legacy BIOS boot.

I experienced the very same problem with Fedora 23 Workstation Final Release 64-bit, but the problem has been resolved shortly with a respin. Now I can do an EFI install with the Fedora respin. Could such a respin be created for Qubes?

**Comment by marmarek** [comment]
See here:
https://www.qubes-os.org/doc/uefi-troubleshooting/

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by Slazer** [comment]
Hello. I have already tried this method. At the end of chainloader line I added /mapbs /noexitboot, but the boot still hangs on the very same page. Could this be re-opened? I am researching the Qubes OS (thesis) and EFI boot is kind of important for me.

**Comment by marmarek** [comment]
You can review this thread: https://github.com/QubesOS/qubes-issues/issues/794
If that still doesn't help, you're probably stuck with legacy mode. Generally this is BIOS bug, you may try getting your BIOS vendor to fix it, or asking Xen people to add yet another workaround (they are not very keen to do that).
