### ISSUE TITLE
set NetVM of TemplateVMs to none by default / make TemplateVMs non-networked by default

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#1858]
Once `implement qrexec based updates proxy` (#1854) has been implemented... TODO:
- set NetVM for newly created TemplateVMs to `none`
- set NetVM for existing TemplateVMs to `none`

(This ticket has been [confirmed](https://groups.google.com/d/msg/qubes-devel/0O1qT6xH604/qxrcGfBHCAAJ) by @marmarek.)

**Comment by adrelanos** [comment]
I saw some commits below here https://github.com/QubesOS/qubes-issues/issues/1854#issuecomment-304536463 for this by you @marmarek. Can this be closed?

**Comment by marmarek** [comment]
Technically, it isn't merged yet. But once merged - yes.

**Comment by marmarek** [comment]
Done.
