### ISSUE TITLE
Attach USB smartcard reader to VMs

### ISSUE THREAD

**Issue by caschulz88** [QubesOS/qubes-issues#1862]
Hi,

currently only input events from USB mouse (and USB keyboard) + block devices/usb drives are supported by usb-vm and the USB forward implementations, such as input-proxy, etc. What I'm really missing at the moment is the support to forward a connected USB smartcard reader to another VM. I would like to use my smartcard reader for file encryption, encrypting mails, online banking, signing git commits, etc.

Is there already anything planned for this? I would also like to support the development or could start to develop it on my own if we specify how to solve this issue the best way.

**Comment by marmarek** [comment]
There is generic idea of PV USB (#531). Lets move discussion there.
