### ISSUE TITLE
random hardware resets, almost daily,

### ISSUE THREAD

**Issue by rock04** [QubesOS/qubes-issues#1867]
Thanks for your help.  Qubes is a great project, but I am having some serious issues.  I have not been able to isolate a probable link or cause.

Problem:  random hardware resets, almost daily, 3.1 rc1 (updated)

System:
   CPU: vendor_id       : GenuineIntel
        model           : 44
        model name      : Intel(R) Core(TM) i7 CPU         970  @ 3.20GHz
  ram: 16G; SSD HD; 3 monitors
  Qubes 3.1, rc1 (fresh install) updates applied as available

Description:
   random hard reset (complete, instant hardware reset; no shutdown sequence)
   almost always once per day (a few days it will happen more than once; a few days not at all)  [this is strange, but fairly consistent]

Other:
   1. Does not seem to be hardware related.  PC is dual boot with win 8.1 (on separate HD).  Issue is not present when using win.
   2. does not seem to be affected by
      a. amount of time PC or OS is active 
         1. sometimes PC is shutdown at night and restarted next day, but not always.
         2. restarts occur at different times during the day
      b. which VMs are active
      c. whether PC is in active use (whether I am working or away)

Any ideas on how to solve/ troubleshoot this?

my Linux proficiency: low-medium

**Comment by marmarek** [comment]
I assume you've excluded obvious things like overheating?

For hardware related problems you may get better answers on qubes-users mailing list.

**Comment by rock04** [comment]
Thanks for the reply.
I have excluded the things that seem obvious to me (see original post).  Regarding overheating: I am running the temperature widget -- no problems; the bios reports core temps from 28C - 34C; running "sensors" (from command line) shows the same temperature range that is reported in the bios.  [In fact, with Qubes, the CPU temps are lower than when running the PC with Win 8.1]
Any ideas on best way to troubleshoot this??  I am running out of ideas.
I really like what you have done here with Qubes and hope to be able to use it in a work 
environment, if I can just get it (Qubes or HW) stablized.
Thanks again.

**Comment by axon-qubes** [comment]
This problem may be a bit too localized for `qubes-issues`. `qubes-users` is generally more suitable for personalized troubleshooting discussions.
