### ISSUE TITLE
test/fix website layout for smaller screens

### ISSUE THREAD

**Issue by mfc** [QubesOS/qubes-issues#1869]
Some webpages currently looks pretty bad on smaller-sized screens.

Specifically:
- https://www.qubes-os.org/help/

Troubleshooting, FAQs, and Mailing Lists don't stack properly, I think the issue may be the flavor text of Troubleshooting. This issue is noticeable when you make your browser the size of a 9-13" screen.
- https://www.qubes-os.org/tour/

The title sections bleed into the previous content, rather than there being some buffer space. This issue is noticeable all the way down to mobile-size screens. For all pages with that type of section this issue pops up (also help page).

**Comment by axon-qubes** [comment]
Related: #1837, #1841.

**Comment by andrewdavidwong** [comment]
The website is now very readable on mobile devices, so I'm closing this as complete. However, if anyone notices examples of pages where it's bad, please leave a comment, and we'll be happy to reopen this.
