### ISSUE TITLE
Error when changing system storage size on a StandaloneVM

### ISSUE THREAD

**Issue by jaspertron** [QubesOS/qubes-issues#1875]
Using the Qubes Manager, if I try to change the "System storage max. size" on any StandaloneVM, it will always show an error message.

If the VM is running:

> ERROR: Basic tab:
> Cannot resize root.img of running VM

If the VM is not running:

> ERROR: Basic tab:
> VM start required to complete the operation, but not allowed. Either run the operation again allowing VM start this time, or run resize2fs in the VM manually.

I'm not sure what "run the operation again allowing VM start" means, but running resize2fs in the VM manually works (`sudo resize2fs /dev/mapper/dmroot`).

**Comment by fsteinel** [comment]
This also happens on AppVMs but for "Private storage max. size"
I'm only able to **grow** the storage, if i'm following the steps in https://www.qubes-os.org/doc/resize-disk-image/ for shrinking.

Debug:
- Make sure that the AppVM is shutdown
- grow the "Private storage max. size" via the GUI (Qubes VM Manager) or via qvm-grow-private to 35GB  (35840MB)
- start the AppVM
- start terminal in the AppVM
- run `df -h`
- run `dd if=/dev/zero of=/home/user/growtest bs=30000000 count=1000` 
- In Dom0 the filesize of private.img is of the desired size.
- In DomU the Partion is not grown and stuck at the 2GB default.
- shutdown AppVM
- follow the manuell steps linked above
- start AppVm
- the "Private storage max. size" is now at the desired size

**Comment by marmarek** [comment]
@fsteinel what Qubes version do you use? On which template that AppVM is based?
