### ISSUE TITLE
sell merchandise

### ISSUE THREAD

**Issue by mfc** [QubesOS/qubes-issues#1879]
potential propaganda here: https://github.com/bnvk/Designs/tree/master/QubesOS/propaganda

there are different online stores that will print and ship merchandise on demand, so that we don't have to manage it.
- http://www.cafepress.com
- http://portmerch.com (only for bands/artists I think)
- http://www.galloree.com
- http://www.zazzle.com

What we'd want is one that:
- [ ] ships internationally
- [ ] prints stickers and tshirts/hoodies (not sure if there are other things in demand)
- [ ] can have a dedicated "Qubes" store that we link to from the Qubes website

**Comment by axon-qubes** [comment]
@marmarek: Should we have a new label and/or milestone for these sorts of issues? Perhaps something like "Media & Marketing"?

**Comment by axon-qubes** [comment]
@marmarek: I realized I can create new labels, so I made a `business` label (which is more general, so it can also apply to issues like #1701). As always, feel free to delete it if you think it undesirable. :)

**Comment by marmarek** [comment]
:+1:

**Comment by mfc** [comment]
FYI there is also: https://www.unixstickers.com

**Comment by andrewdavidwong** [comment]
What ever happened to [this one](https://twitter.com/QubesOS/status/681435167433580544)?

**Comment by mfc** [comment]
brennan did a printing run at a local printer in berlin, which we want to avoid.

**Comment by jpouellet** [comment]
> prints stickers and tshirts/hoodies (not sure if there are other things in demand)

I'd totally buy a Qubes mug! Ideally a dishwasher safe one not painted with lead ;)

**Comment by andrewdavidwong** [comment]
Whenever this topic has come up in internal discussions over the past couple of years, it's been decided against, so I'm closing this as a "won't do" for now.
