### ISSUE TITLE
Upgrading qubes-core-agent in debian-8 template error due to running two apt-gets simultaneously

### ISSUE THREAD

**Issue by isislovecruft** [QubesOS/qubes-issues#1889]
When I do:

```
sudo apt-get install qubes-core-agent
```
in my debian-8 template, it eventually somewhere calls an apt hook to restart the `/etc/systemd/system/qubes-check-update.service` systemd service. That service file has:

```
ExecStart=/bin/sh -c if [ -e /etc/debian_version ]; then apt-get -q update; fi 
```

...which will obviously fail if called from an apt hook, due to two simultaneous apt sessions being open (i.e. it can't get the dpkg lock). It fails and displays the following output:
```
Setting up qubes-core-agent (3.1.14-1+deb8u1) ...
Installing new version of config file /etc/NetworkManager/dispatcher.d/qubes-nmhook ...
Installing new version of config file /etc/apt/sources.list.d/qubes-r3.list ...
Installing new version of config file /etc/qubes-rpc/qubes.GetAppmenus ...
Installing new version of config file /etc/qubes-rpc/qubes.InstallUpdatesGUI ...
Installing new version of config file /etc/qubes-rpc/qubes.SetDateTime ...
Installing new version of config file /etc/qubes/iptables.rules ...
Leaving 'diversion of /etc/init/plymouth-shutdown.conf to /etc/init/plymouth-shutdown.conf.qubes-disabled by qubes-core-agent'
Leaving 'diversion of /etc/init/prefdm.conf to /etc/init/prefdm.conf.qubes-disabled by qubes-core-agent'
Leaving 'diversion of /etc/init/splash-manager.conf to /etc/init/splash-manager.conf.qubes-disabled by qubes-core-agent'
Leaving 'diversion of /etc/init/start-ttys.conf to /etc/init/start-ttys.conf.qubes-disabled by qubes-core-agent'
Leaving 'diversion of /etc/init/tty.conf to /etc/init/tty.conf.qubes-disabled by qubes-core-agent'
Leaving 'diversion of /etc/init/serial.conf to /etc/init/serial.conf.qubes-orig by qubes-core-agent'
Job for qubes-update-check.service failed. See 'systemctl status qubes-update-check.service' and 'journalctl -xn' for details.
```
Running `systemctl status qubes-update-check.service` shows:
```
user@debian-8:~  sudo systemctl status qubes-update-check.service
● qubes-update-check.service - Qubes check for VM updates and notify dom0
   Loaded: loaded (/lib/systemd/system/qubes-update-check.service; static)
   Active: failed (Result: exit-code) since Sat 2016-04-02 11:48:21 UTC; 41s ago
  Process: 2208 ExecStart=/bin/sh -c if [ -e /etc/debian_version ]; then apt-get -q update; fi (code=exited, status=100)
 Main PID: 2208 (code=exited, status=100)

Apr 02 11:48:20 debian-8 sh[2208]: Hit http://deb.qubes-os.org jessie...ges
Apr 02 11:48:20 debian-8 sh[2208]: Hit http://deb.qubes-os.org jessie/main...-en
Apr 02 11:48:21 debian-8 sh[2208]: Fetched 157 kB in 13s (12.0 kB/s)
Apr 02 11:48:21 debian-8 sh[2208]: E: Could not get lock /var/lib/dpkg/lock - op...le)
Apr 02 11:48:21 debian-8 sh[2208]: E: Unable to lock the administration director...it?
Apr 02 11:48:21 debian-8 systemd[1]: qubes-update-check.service: main process exi.../a
Apr 02 11:48:21 debian-8 systemd[1]: Failed to start Qubes check for VM updates a...0.
Apr 02 11:48:21 debian-8 systemd[1]: Unit qubes-update-check.service entered fail...e.
Hint: Some lines were ellipsized, use -l to show in full.
```

**Comment by adrelanos** [comment]
Sounds very plausible. I'll be working on this.

**Comment by adrelanos** [comment]
Please check this out when convenient.

https://github.com/marmarek/qubes-core-agent-linux/pull/66

**Comment by adrelanos** [comment]
https://github.com/marmarek/qubes-core-agent-linux/pull/66#issuecomment-209089524

Not sure where discussion is best. In the ticket or in the pull request? I can imagine a number of people as subscribed to whole qubes-issues but not necessarily to all packages. So I guess discussion here is getting noticed by more people.

I think https://github.com/marmarek/qubes-core-agent-linux/pull/66 goes into the right direction, refactoring wise. But it does not actually solve this issue.

qubes-update-check.service -> upgrades-status-notify -> upgrades-installed-check -> apt-get update -> fail -> exit non-zero -> systemd recognized failed state.

The design of upgrades-status-notify and upgrades-installed-check make sense as is.

What about...
```
ExecStart=/usr/lib/qubes/upgrades-status-notify
```
--->
```
ExecStart=/usr/lib/qubes/upgrades-status-notify || true
```
?

**Comment by marmarek** [comment]
Better `ExecStart=-/usr/lib/qubes/upgrades-status-notify`
Or maybe even instead of https://github.com/marmarek/qubes-core-agent-linux/pull/66, do
`ExecStart=-/bin/sh -c 'if [ -e /etc/debian_version ]; then apt-get -q update; fi'` ?
So the failure of `apt-get update` will not mark the service as failed.

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `python2-dnf-plugins-qubes-hooks-3.2.7-1.fc23` has been pushed to the `r3.2` testing repository for the Fedora `fc23` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.2-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/e7b1711e2176bcf030d8c6c9698688aaf7639aee...8781a5c588f78fbf9577aaa760d914a9f2f035ae

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `python2-dnf-plugins-qubes-hooks-3.2.7-1.fc24` has been pushed to the `r3.2` testing repository for the Fedora `fc24` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.2-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/e7b1711e2176bcf030d8c6c9698688aaf7639aee...8781a5c588f78fbf9577aaa760d914a9f2f035ae

**Comment by adrelanos** [comment]
I don't think this is fixed. https://github.com/QubesOS/qubes-issues/issues/1889#issuecomment-209524361 still applies. Please reopen.

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-agent_3.2.7-1+deb8u1` has been pushed to the `r3.2` testing repository for the Debian `jessie` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `jessie-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/e7b1711e2176bcf030d8c6c9698688aaf7639aee...8781a5c588f78fbf9577aaa760d914a9f2f035ae

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-agent_3.2.7-1+deb9u1` has been pushed to the `r3.2` testing repository for the Debian `stretch` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `stretch-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/e7b1711e2176bcf030d8c6c9698688aaf7639aee...8781a5c588f78fbf9577aaa760d914a9f2f035ae

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-agent_3.2.7-1+deb7u1` has been pushed to the `r3.2` testing repository for the Debian `wheezy` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `wheezy-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/e7b1711e2176bcf030d8c6c9698688aaf7639aee...8781a5c588f78fbf9577aaa760d914a9f2f035ae

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `python2-dnf-plugins-qubes-hooks-3.2.8-1.fc23` has been pushed to the `r3.2` testing repository for the Fedora `fc23` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.2-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/8781a5c588f78fbf9577aaa760d914a9f2f035ae...979e2d2bf8a5a697634ce6954247f8fbae5ff438

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `python2-dnf-plugins-qubes-hooks-3.2.8-1.fc24` has been pushed to the `r3.2` testing repository for the Fedora `fc24` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.2-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/8781a5c588f78fbf9577aaa760d914a9f2f035ae...979e2d2bf8a5a697634ce6954247f8fbae5ff438

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-agent_3.2.8-1+deb8u1` has been pushed to the `r3.2` testing repository for the Debian `jessie` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `jessie-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/8781a5c588f78fbf9577aaa760d914a9f2f035ae...979e2d2bf8a5a697634ce6954247f8fbae5ff438

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-agent_3.2.8-1+deb9u1` has been pushed to the `r3.2` testing repository for the Debian `stretch` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `stretch-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/8781a5c588f78fbf9577aaa760d914a9f2f035ae...979e2d2bf8a5a697634ce6954247f8fbae5ff438

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `python2-dnf-plugins-qubes-hooks-3.2.9-1.fc23` has been pushed to the `r3.2` stable repository for the Fedora `fc23` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/d47a89ec76452a4c9efe3b5cbf87157083b3d765...fd8a1167446a8b2e8487d67b9c2888663327a805

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `python2-dnf-plugins-qubes-hooks-3.2.9-1.fc24` has been pushed to the `r3.2` stable repository for the Fedora `fc24` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/d47a89ec76452a4c9efe3b5cbf87157083b3d765...fd8a1167446a8b2e8487d67b9c2888663327a805

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-agent_3.2.10-1+deb8u1` has been pushed to the `r3.2` stable repository for the Debian `jessie` template.
To install this update, please use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/d47a89ec76452a4c9efe3b5cbf87157083b3d765...1a601ddbe9bae11088a78136bfe7cd8a1b3258f1
