### ISSUE TITLE
fonts sometimes render as black squares in applications launched from TorBrowser

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#1892]
https://groups.google.com/d/topic/qubes-users/Yy6iX0-D7RI/discussion

> > More information: it seems to be limited to when the file explorer (dolphin) is started from within the privacy browser.
> > 
> > When I go to the same folder from a Dolphin that was started from the Qubes menu, the characters in the dialog display properly.
> > 
> > See: https://i.imgur.com/1ItY3jR.png
> 
> Yes, I've noticed this as well. It seems to affect at least a couple of different programs (Dolphin, Gwenview). The problem also goes away after restarting the VM.

**Comment by adrelanos** [comment]
The application in question is not been developed by Whonix. The same one is being used in any Qubes template. Could be a missing dependency?

@marmarek any idea?

**Comment by marmarek** [comment]
Since the same application does work when started from outside of Tor Browser, I would exclude missing dependency. Maybe some missing environment variable?

**Comment by adrelanos** [comment]
Marek Marczykowski-Górecki:
> Since the same application does work when started from outside of Tor Browser, I would exclude missing dependency. Maybe some missing environment variable?
> 
> ---
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/QubesOS/qubes-issues/issues/1892#issuecomment-207819779
> 

Just now verified. Tor Browser does not flush environment variables.

"sudo -u user" cleans environment variables, but kdiaglog does not seem
to have any issues with this.

I could reproduce this issue in a Qubes Debian TemplateBased AppVM,
using Tor Browser and Dolphin.

**Comment by marmarek** [comment]
Ok, it looks to be the opposite problem: TorBrowser adds few additional environment variables which breaks `kdialog`:
```
FONTCONFIG_PATH=/home/user/tor-browser_en-US/Browser/TorBrowser/Data/fontconfig
LD_LIBRARY_PATH=/home/user/tor-browser_en-US/Browser/TorBrowser/Tor/
```
When added `unset FONTCONFIG_PATH` to `/usr/lib/qubes/qvm-copy-to-vm.kde`, it works. I would say it's TorBrowser bug.

**Comment by adrelanos** [comment]
`Tor Browser breaks rendering of fonts in applications launched from Tor Browser`:
https://trac.torproject.org/projects/tor/ticket/18813

**Comment by ninavizz** [comment]
This should be closed on the Qubes end, @andrewdavidwong. It's a known problem with Tor's whitelisting of fonts for security, and only happens when security settings are very high. Unless I'm missing something.

**Comment by andrewdavidwong** [comment]
Closing as "not our bug." If you believe this is a mistake, please leave a comment, and we'll be happy to take another look. Thank you.
