### ISSUE TITLE
Meta: consider Whonix label

### ISSUE THREAD

**Issue by axon-qubes** [QubesOS/qubes-issues#1895]
@adrelanos, @marmarek: Should there be a `C: Whonix` label in `qubes-issues` (e.g., for issues like #1892)?

Meta-meta: Should there also be a `meta` label? ;)

**Comment by marmarek** [comment]
:+1: 
As for meta, not sure about that. There is not much such issues (or maybe I'm wrong about that?).

**Comment by axon-qubes** [comment]
Ok, creating a `C: Whonix` label.

> As for meta, not sure about that. There is not much such issues (or maybe I'm wrong about that?).

Agreed. Not much need for a `meta` label right now.
