### ISSUE TITLE
Make "Research" page on site data driven

### ISSUE THREAD

**Issue by bnvk** [QubesOS/qubes-issues#1905]
Currently, the [Research page](https://www.qubes-os.org/research/) is hard-coded into the file `pages/research.md` while the `Research` widget on the homepage uses `_data/research.yml` we should  combine the two things

Can you knock this out @axon-qubes or shall I?

**Comment by axon-qubes** [comment]
Yeah, I can take care of this one.

**Comment by axon-qubes** [comment]
We might want to list only a few entries in the Home page widget. (Currently, it lists all of them, so it's quite long.)

Another minor issue: Some entries don't have known dates, so there's just a hanging comma at the end, after the authors' names.

**Comment by bnvk** [comment]
> We might want to list only a few entries in the Home page widget. (Currently, it lists all of them, so it's quite long.)

@axon-qubes yah exactly. Thanks for helping :)
