### ISSUE TITLE
News redirects hide target URLs from users

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#1913]
Links in the [news](https://www.qubes-os.org/news/) section are blind redirects. They _look_ like they're links to pages on the qubes-os.org domain, but many of them redirect users to external websites. Those links are marked by the "external link" icon, which is good. But users still can't tell exactly where they're going to be redirected before actually clicking (and almost instantly being redirected). This seems somewhat unfriendly and unsafe to our website visitors.

(The interstitial redirect page also has some bugs, e.g., literal `<!DOCTYPE html>` is displayed.)

**Comment by axon-qubes** [comment]
Two (out of many) possible solutions:

* Instead of redirecting, just link directly to those external sites (in the case of YouTube videos, magazine articles, etc.)
* Prompt the user to decide whether she consents to being redirected to the external site.

**Comment by bnvk** [comment]
> Instead of redirecting, just link directly to those external sites (in the case of YouTube videos, magazine articles, etc.)

IIRC, this is tricky to do with how Jekyll's "blog post" sorting and rendering works. Maybe there is a hack around, but unsure.

> Prompt the user to decide whether she consents to being redirected to the external site.

I really don't like this as it breaks the UX of simply "browsing the web" as it stops a user forcing them to read intermediary text- which reminds of my wifi captive portals, or what Fbook does to manipulate users into staying on Fbook.

Admittedly, our userbase is more security & privacy conscious than average, and blind redirects are not ideal, but seeing as that our site does not have user-generated content and every link has been vetted by one of use- is it too much to ask users to *trust* us that we won't redirect them somewhere malicious?

> (The interstitial redirect page also has some bugs, e.g., literal <!DOCTYPE html> is displayed.)

This should be investigated and fixed!

**Comment by axon-qubes** [comment]
> Admittedly, our userbase is more security & privacy conscious than average, and blind redirects are not ideal, but seeing as that our site does not have user-generated content and every link has been vetted by one of use- is it too much to ask users to *trust* us that we won't redirect them somewhere malicious?

Yeah, that's a fair point. If no users are actually bothered by it, then I suppose it's a non-issue.

**Comment by andrewdavidwong** [comment]
Our practice for quite a long time now has been to write News posts in such a way that they are not blind redirects. Rather, they typically include a description of the content and the external link, so that the reader can decide whether to navigate away from the Qubes website or not.
