### ISSUE TITLE
XFCE window decoration colors don't match Qubes VM Manager labels

### ISSUE THREAD

**Issue by mfc** [QubesOS/qubes-issues#1915]
#### Qubes OS version (e.g., `R3.1`): R3.1

---

### Expected behavior: 

colors match labels

### Actual behavior: 

decoration border colors are different color values than in Qubes VM Manager. for example, the purple window decoration is almost a pink color, however the purple in the Qubes VM Manager is still purple (much darker). the same is true with the black, which is a light grey in window decorations.

### Steps to reproduce the behavior:

log in to XFCE, open some applications with different colored labels assigned to them.

**Comment by marmarek** [comment]
Implemented here: https://github.com/marmarek/qubes-desktop-linux-xfce4/commit/6914f173e278f61852f4e5971d34e78985523498

**Comment by mfc** [comment]
on R3.2rc2 and only seeing this partly implemented. Purple is still the same (pink in actual window decoration), the black now matches but with the issue that it is now impossible to see the window buttons (minimize, expand, close) as there is no contrast between the window border color and the buttons.

**Comment by andrewdavidwong** [comment]
> the issue that it is now impossible to see the window buttons (minimize, expand, close) as there is no contrast between the window border color and the buttons.

For reference, this issue is described in #2120.
