### ISSUE TITLE
Redirect old /trac/wiki/ links

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#1922]
It looks like old `/trac/wiki/` links are not being redirected properly.

For example, Joanna's [original post](https://groups.google.com/d/msg/qubes-users/u3wAzm1dB5Y/I4Zd12-yT5cJ) about accepting Bitcoin donations includes this link from the old Qubes site:

http://wiki.qubes-os.org/trac/wiki/Donations

If you try to visit that page, you get a 404 (from our new site). However, in the `redirect_from` list of the *new* Donations page, we *already* have `/wiki/Donations/`.

When I try adding `/trac/wiki/Donations` to the list (with and without a trailing slash), it doesn't work from my local `jekyll serve`. Instead of getting redirected to the page (as I do with other redirected pages), I get prompted to download a BIN file.

So, is there a way to get these old `/trac/wiki/` links properly redirected (preferably site-wide)?

**Comment by axon-qubes** [comment]
(Ah, of course the subdomain is now different.)

**Comment by marmarek** [comment]
I see two related redirections at cloudflare:
*wiki.qubes-os.org/*
Forwarding to https://www.qubes-os.org/$2

www.qubes-os.org/wiki/*
Forwarding to https://www.qubes-os.org/doc/$1/

Adjusted the later to match also wiki.qubes-os.org. Will see if that
help.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by axon-qubes** [comment]
Hm, still getting a 404 on that link.

**Comment by andrewdavidwong** [comment]
Since it's been a long time since we were on the old TracWiki site, and we now have a 404 page that shows the helpful nav bar at the top, I think it's fine to close this.

**Comment by andrewdavidwong** [comment]
Reopening because now even the 404 page doesn't show up. IMHO, the bare minimum should be redirecting to the home page (https://www.qubes-os.org/), though the specific new page would be best.

Another example of a non-working link is http://wiki.qubes-os.org/trac/wiki/GUIdocs (from https://blog.invisiblethings.org/2011/04/23/linux-security-circus-on-gui-isolation.html).
