### ISSUE TITLE
Remove dom0 key mappings for multimedia keyboard buttons

### ISSUE THREAD

**Issue by kbrn** [QubesOS/qubes-issues#1925]
See: https://groups.google.com/forum/#!topic/qubes-users/dKZxdkr-E8g/discussion (Failed to launch shortcut "XF86AudioPrev")

and

https://groups.google.com/forum/#!topic/qubes-users/267F1J8u5s0 (Multimedia keys)

> By not binding the keys in Dom0, they go from "not working at all, and
> giving an ugly error message" to "working, so long as the relevant
> domain is in focus".  I think the latter is also predictable to
> someone (getting) used to the Qubes model.

**Comment by marmarek** [comment]
Done in https://github.com/QubesOS/qubes-desktop-linux-xfce4/pull/3 by @jpouellet
