### ISSUE TITLE
Use Travis-CI for build testing

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#1926]
As Qubes builder now works on Debian host, we can setup Travis-CI for all the Qubes components.
This is continuation of work done in #1907

**Comment by marmarek** [comment]
Created status page: https://github.com/QubesOS/qubes-issues/blob/master/travis_status.md

**Comment by marmarek** [comment]
Ok, every component included (with an exception for Linux kernel, which doesn't fit in 50 minutes build time limit). Build status monitored on above mentioned website. But most importantly - all pull requests against master branch are automatically checked!

**Comment by timcollinsal1** [comment]
I hope I dient jump gun or overstep bounds, but I took your .ISO link from another issue and modified it to find the download for your image made on 20160606 to test it out. My builder has been giving errors on vmm-xen and workaround were not dong the job.

3.2 Pre/release test image after install ran spot on. I can followup with specifics if you need clarity on ANYTHING (Im sorry Im new to this process) but I kept sayng the words "buttery smooth" in my head as I installed and used it. Like night and day difference. I have been fighting uphill battle debugging 3.0 and 3.1 from install to use, and this (PRE-RELEASE) has been the single best experience with Qubes Iv had so far. EXCELLECNT work sir! I am usng UEFI based i7 with Optimus NVIDIA, 16gb Ram, SSD, Killer e2200, MS16F3 - 16F3IMS518 BIOS Laptop. - My bggest errors were getting DOM0 Kernel to run , I couldent run solid on ANYTHING other than 3.12 - 4.4 and 4.5 kernels are awesomely good. The 4.4 on this build worked like a dream.

**Comment by marmarek** [comment]
@timcollinsal1 please don't hijack random issues for unrelated questions. Better ask on qubes-users (usage questions, bug reports) / qubes-devel (design/develop discussions)  list.

**Comment by timcollinsal1** [comment]
I am incredibly sorry and embarrassed that this occurred and promise it
will not re-occur! I hold your work in such high regard and to have taken
your time with a misplaced question in an important thread, Im truly sorry!
No intent to do was existed and I appreciate your redirection. Best wishes
and thanks for all you do!
