### ISSUE TITLE
sound failure debian-9 (stretch) template

### ISSUE THREAD

**Issue by pugege** [QubesOS/qubes-issues#1927]
#### Qubes OS version (e.g., `R3.1`):

R3.1
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):

debian-9 (stretch)

---
### Expected behavior:

appvm playback device attachment; normal sound
### Actual behavior:

no appvm playback device attachment; no sound
### Steps to reproduce the behavior:

playback device attachment with debian-8, normal sound
### General notes:

stretch-testing repository enabled; current update; all dom0
audio testing normal both speaker & headphones; no muting re: alsamixer; normal
sound function with sys-usb (fedora 23 template) vlc

---

**Comment by axon-qubes** [comment]
Do I understand correctly that this is a localized hardware incompatibility issue between your audio hardware and your debian-9 template? If so, these sorts of localized hardware troubleshooting issues are best discussed and handled on the `qubes-users` mailing list. (More people are likely to see it there, and there is a higher chance that someone else may have experienced the issue and be able to help.)

**Comment by pugege** [comment]
Yes, my system is stable with no sound issues with debian-8 and fedora 23 templates.
The problem is only with debian-9 template. I filed a report here with reference to issue
#1683, "Support Pulseaudio 8,0" and qubes-gui-vm 3.1.5+deb9u1 which has been uploaded to the stretch-testing repository. Perhaps that program, a dependency of
pulseaudio 8.0.2 is not yet compatible in debian-9 to allow program function?

**Comment by axon-qubes** [comment]
Ok, thanks for the report.

As noted [here](https://www.qubes-os.org/doc/supported-versions/), the Debian 9 template has been published for R3.1 but has not yet undergone extensive testing.

**Comment by hawaiikasper** [comment]
I used to have the same problem some time ago. After some testing I found out that the file "module-vchan-sink.so" couldn't be found. I think the cause is an upgrade from pulse-7.1 to pulse-8.0.

Try this as a workaround in your Debian (stretch) template:
`sudo ln -s /usr/lib/pulse-7.1/modules/module-vchan-sink.so /usr/lib/pulse-8.0/modules/module-vchan-sink.so`

**Comment by pugege** [comment]
Thank you kindly, hawaiikasper for your helpful post. The simlink solved the sound problem.
Works great now! Thanks also axon & marmarek for your attention.

**Comment by kulinacs** [comment]
This issue should be closed, adding the qubes testing repositories should fix the issue.
https://groups.google.com/forum/#!topic/qubes-users/JddCE54GFiU

**Comment by hawaiikasper** [comment]
This bug strikes again after pulseaudio got upgraded to version 9.0.

Again, one can use this as a workaround in the Debian (stretch) template:
`sudo ln -s /usr/lib/pulse-8.0/modules/module-vchan-sink.so /usr/lib/pulse-9.0/modules/module-vchan-sink.so`

**Comment by kbrn** [comment]
@marmarek Can you give this 3 minutes of attention?  I think it's a super easy fix, no?

Thanks,
Andrew

**Comment by marmarek** [comment]
There is already recently built gui-agent-linux 3.2.6 in testing repository.

**Comment by pdinoto** [comment]
In a recent update to Debian 9 template, `pulseaudio` was again not working, as it has been bumped to version `10.0-1` and now it expects modules to be at `/usr/lib/pulse-10.0/modules`. 

Same workaround works: on the template simply do:
```shell
# cd /usr/lib/pulse-10.0/modules
# ln -s ../../pulse-9.0/modules/module-vchan-sink.so .
```
then shutdown the template and restart AppVMs based on it.

**Comment by tasket** [comment]
@pdinoto Thanks, this fix worked for me too.

**Comment by marmarek** [comment]
Just uploaded new package (qubes-gui-agent 3.2.14), should be linked with latest pulseaudio.

**Comment by 9jobsworth** [comment]
yes and i suspect that it happened again as part of the latest update to raspbian stretch.
haven't tried it yet and so can't prove it. all i know is that the sound has gone.
i have code like that and eventually i got so fed up with it that i created a variable
which of course changed with the version number. - voila prolem solved.

**Comment by archpaladin1** [comment]
Problem strikes again with pulseaudio 11.1.  Currently the latest qubes-gui-agent in the testing repository isn't linked against the latest version.  The typical workaround doesn't work for me.

**Comment by unman** [comment]
@andrewdavidwong This is fixed for 11.1 in qubes-gui-agent  3.2.19, Can you close please?

**Comment by 9jobsworth** [comment]
my sound on audacious and youtube is now working great. thank you to whoever fixed it.

**Comment by AhmedAA** [comment]
The fix does not work for debian sid (unstable)

I have no sound in my debian appvm's.

Qubes 4RC3
Installed debian 9 template through qubes-dom0-update
Changed repos in template to debian unstable (sid)
Made dist-upgrade as according to debian documentation (apt-get -u dist-upgrade)

Pulseaudio version 11.1.
Attempted with symlink of module-vchan-sink.so into the pulseaudio-11.1/modules/ folder and also tried with making a hard copy (cp) into the dir from pulseaudio-10.0/modules/

Any suggestions appreciated (also suggestions which help further debugging)!

Thanks!

**Comment by andrewdavidwong** [comment]
@AhmedAA: Hm, looks like it might be best to file a new issue, since it's a different version of Debian.
