### ISSUE TITLE
Debian Templates: get rid of redundant (systemd) services

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#1928]
https://groups.google.com/d/msg/qubes-devel/GMHLGQ-YDmc/mPl2mZpaBQAJ

**Comment by andrewdavidwong** [comment]
[On 2016-08-22 08:37, johnyjukya@[...].org wrote:](https://groups.google.com/d/msgid/qubes-users/b9f04934f4dc333b3afc24e995a77fc3.webmail%40localhost)
> I notice in the debian-8 template that network time synchronization seems
> to be on by default in systemd.
> 
> systemd-timesyncd.service  loaded active running   Network Time
> Synchronization
> time-sync.target           loaded active active    System Time Synchronized
> 
> It's disabled in fedora-23 by default, and rightly so, as I believe it's
> unnecessary given the dom0 driven /etc/qubes-rpc/qubes.SetDateTime
> mechanism, and it's kind of "leaky" sending requests unnecessarily to the
> Internet.
> 
> Paranoidly yours,
> 
> JJ
>

**Comment by adrelanos** [comment]
https://github.com/QubesOS/qubes-issues/issues/1928#issuecomment-242538710 --> `systemd-timesyncd` -> `Debian templates: disable systemd-timesyncd [regression]`-> #2188

**Comment by unman** [comment]
A default Debian install brings with it rpcbind, exim4 and avahi.
I see little sense in having these running in all TemplaeBasedVMs, so it seems natural to disable them in the default Template. 
@marmarek Would there be any objection to including constraints for all these in core-agent-linux? That seems a natural place.
afaik these services aren't installed (or perhaps just aren't started) in Fedora templates.
