### ISSUE TITLE
Deleting a VM with autostart enabled does not delete the autostart Symlink

### ISSUE THREAD

**Issue by MarioGeckler** [QubesOS/qubes-issues#1929]
#### Qubes OS version:
R3.1

### Expected behavior:
Deleting a AppVM with autostart enabled should delete the Symlink
/etc/systemd/system/multi-user.target.wants/qubes-vm@VMNAME.service
### Actual behavior:
The Symlink isn't deleted so on each Boot Qubes tries to start a non existent VM and fails
### Steps to reproduce the behavior:
Create a VM with autostart enabled and delete it. The Symlink for starting the VM is not deleted
### General notes:

---

**Comment by marmarek** [comment]
A side effect of this bug: if you create later a VM with the same name, it will have autostart enabled.

**Comment by marmarek** [comment]
Fixed in https://github.com/QubesOS/qubes-core-admin/pull/29

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-dom0-3.1.17-1.fc20` has been pushed to the `r3.1` testing repository for dom0.
To test this update, please install it with the following command:
```
sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-admin/compare/1e29d7fa396a1469541a6d64e48f398396f79780...d8093f38c428e4a9e7be421f2dc57e0a45a19477

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-dom0-3.1.17-1.fc20` has been pushed to the `r3.1` stable repository for dom0.
To install this update, please use the standard update command:
```
sudo qubes-dom0-update
```
Or update dom0 via Qubes Manager.

[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-admin/compare/1e29d7fa396a1469541a6d64e48f398396f79780...d8093f38c428e4a9e7be421f2dc57e0a45a19477

**Comment by SaswatPadhi** [comment]
My system is up to date (Qubes R4.0+), but I still notice this.

I am also not sure how to manually remove the symlink now. I tried doing:
```
$ systemctl status qubes-vm@personal.service
```
and I see the unit file `/usr/lib/systemd/qubes-vm@.service` but this just looks like a template that is called from some other script.
