### ISSUE TITLE
sys-usb doesn't recognize keyboard/mouse plugged in before system boot

### ISSUE THREAD

**Issue by MarioGeckler** [QubesOS/qubes-issues#1930]
#### Qubes OS version:
R3.1
#### Affected TemplateVMs:
fedora23?
---

### Expected behavior:
Dom0 should ask if InputMouse/InputKeyboard should be allowed even if the devices was connected before the system boots
### Actual behavior:
Devices which are plugged in before the System starts must be reconnected to get the confirmation dialog
### Steps to reproduce the behavior:
Setup working USBVM
Connect Keyboard/Mouse to the System before boot
Boot Qubes
reconnect the devices

**Comment by marmarek** [comment]
This is because it isn't possible to show qrexec policy dialog (confirmation that user really want to allow that mouse control over dom0)  before user login. This also means no way to use that mouse in login screen. Which may be even bigger problem for keyboards (which aren't enabled by default anyway).

I think the easiest solution is to change "ask" policy to "allow" for `qubes.InputMouse` service. @rootkovska do we want that by default when user enable USB VM? This may be risky step. But on the other hand, those confirmations are not as effective as we want: #1166

**Comment by MarioGeckler** [comment]
Is it possible to automatically Show These dialogs After login?

For #1166 : is it possible to get how long the Dialog was shown and Show it again if it was for example less then 1 second?

**Comment by marmarek** [comment]
> Is it possible to automatically Show These dialogs After login?

It may be possible, but not easily. I think of some script to restart failed input proxy services in `sys-usb` after user login. But there is a lot of corner cases...

**Comment by MarioGeckler** [comment]
The following Script just triggers the udev "add" event for all Keyboard and Mouse devices.
Could this be integrated in usb-vm to start after user login?

```python
import subprocess
import os
import sys
from stat import *

eventFiles = os.listdir("/dev/input")
for file in eventFiles:
    if 'event' in file: # if filename contains 'event'
        eventDir = os.path.join("/dev/input", file)
        if S_ISCHR(os.stat(eventDir).st_mode) != 0: # is character device?
            udevreturn = subprocess.check_output(["udevadm","info","--query=property","--name=" + eventDir])
            if 'ID_INPUT_MOUSE' in udevreturn:
                subprocess.call(["sudo","/usr/bin/udevadm","trigger","--action=add","--sysname-match=" + file])
            if 'ID_INPUT_KEYBOARD' in udevreturn:
                subprocess.call(["sudo","/usr/bin/udevadm","trigger","--action=add","--sysname-match=" + file])
```

**Comment by marmarek** [comment]
Yes, create launcher in ~/.config/autostart/something.desktop
Hmm, maybe simply `systemctl restart-failed qubes-input*` will do?

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-input-proxy-1.0.4-1.fc21` has been pushed to the `r3.1` testing repository for the Fedora `fc21` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.1-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-input-proxy/compare/317031e14f761c97ea23553172feae4cfd75a1aa...cc6fc3a311f0b65b0b6ed66df230e625ee3f18e4

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-input-proxy-1.0.4-1.fc22` has been pushed to the `r3.1` testing repository for the Fedora `fc22` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.1-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-input-proxy/compare/317031e14f761c97ea23553172feae4cfd75a1aa...cc6fc3a311f0b65b0b6ed66df230e625ee3f18e4

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-input-proxy-1.0.4-1.fc23` has been pushed to the `r3.1` testing repository for the Fedora `fc23` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.1-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-input-proxy/compare/317031e14f761c97ea23553172feae4cfd75a1aa...cc6fc3a311f0b65b0b6ed66df230e625ee3f18e4

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-input-proxy-1.0.4-1.fc20` has been pushed to the `r3.1` testing repository for dom0.
To test this update, please install it with the following command:
```
sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-input-proxy/compare/317031e14f761c97ea23553172feae4cfd75a1aa...cc6fc3a311f0b65b0b6ed66df230e625ee3f18e4

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-input-proxy-1.0.5-1.fc21` has been pushed to the `r3.1` stable repository for the Fedora `fc21` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-input-proxy/compare/317031e14f761c97ea23553172feae4cfd75a1aa...920e58e44de25ef98256870187d239dc5f71a7ed

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-input-proxy-1.0.5-1.fc22` has been pushed to the `r3.1` stable repository for the Fedora `fc22` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-input-proxy/compare/317031e14f761c97ea23553172feae4cfd75a1aa...920e58e44de25ef98256870187d239dc5f71a7ed

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-input-proxy-1.0.5-1.fc23` has been pushed to the `r3.1` stable repository for the Fedora `fc23` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-input-proxy/compare/317031e14f761c97ea23553172feae4cfd75a1aa...920e58e44de25ef98256870187d239dc5f71a7ed

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-input-proxy-1.0.5-1.fc20` has been pushed to the `r3.1` stable repository for dom0.
To install this update, please use the standard update command:
```
sudo qubes-dom0-update
```
Or update dom0 via Qubes Manager.

[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-input-proxy/compare/317031e14f761c97ea23553172feae4cfd75a1aa...920e58e44de25ef98256870187d239dc5f71a7ed

**Comment by MarioGeckler** [comment]
@marmarek could you add this script in R3,2 also ?

**Comment by marmarek** [comment]
@MarioGeckler it is there.

**Comment by MarioGeckler** [comment]
The script isn´t working in a debian USB-VM because udevadm is not in /usr/bin
I edited the script to dynamically search for udevadm:

#!/usr/bin/python
#
# Trigger "add" udev even for all input mouse/keyboard devices.
# Used to retry qrexec confirmation dialogs after user login

import subprocess
import os
import sys
from stat import *

eventFiles = os.listdir("/dev/input")
for input_dev in eventFiles:
    if 'event' in input_dev:  # if filename contains 'event'
        eventFile = os.path.join("/dev/input", input_dev)
        if S_ISCHR(os.stat(eventFile).st_mode) != 0:  # is character device?
            udevreturn = subprocess.check_output([
                "udevadm", "info", "--query=property", "--name=" + eventFile])
            if 'ID_INPUT_MOUSE' in udevreturn or \
                    'ID_INPUT_KEYBOARD' in udevreturn:
                udevadm = subprocess.check_output([
                "sudo", "which", "udevadm"])
                udevadm = udevadm.rstrip('\n')
                subprocess.call([
                    "sudo", udevadm, "trigger",
                    "--action=add", "--sysname-match=" + input_dev])
