### ISSUE TITLE
Autolink URLs

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#1932]
It would be a nice to have raw URLs on our website automatically converted into hyperlinks.

**Comment by andrewdavidwong** [comment]
This is important for the Join page: https://www.qubes-os.org/join/

**Comment by marmarek** [comment]
Since this doesn't look to be simple, I think it would be better to manually convert links, at least on join page.

**Comment by andrewdavidwong** [comment]
Ok, but there already exist an uncounted number of other pages affected by this, and there are sure to be more in the future.

**Comment by andrewdavidwong** [comment]
The Join page is done.

**Comment by marmarek** [comment]
> The Join page is done.

Thanks!

**Comment by andrewdavidwong** [comment]
It turns out that you can autolink URLs in Markdown simply by enclosing them in angled brackets:

    <https://www.qubes-os.org/>

My local testing with Jekyll shows that this does indeed render as a clickable hyperlink.
