### ISSUE TITLE
qubes-builder doesn't get beyond dependency check: python-yaml

### ISSUE THREAD

**Issue by ttasket** [QubesOS/qubes-issues#1934]
#### Qubes OS version (e.g., `R3.1`):
R3.1
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):
fedora-23

---

### Expected behavior:
'make qubes' compiles according to qubes-builder instructions

### Actual behavior:
Currently installed dependencies:
git-2.5.5-1.fc23.x86_64
rpmdevtools-8.6-2.fc23.noarch
rpm-build-4.13.0-0.rc1.12.fc23.x86_64
createrepo-0.10.3-3.fc21.noarch
python-sh-1.11-1.fc23.noarch
package python-yaml is not installed
Makefile:191: recipe for target 'check-depend.2' failed
make: *** [check-depend.2] Error 1 

### Steps to reproduce the behavior:
The steps outlined at https://www.qubes-os.org/doc/qubes-builder/

### General notes:
See discussion at https://groups.google.com/d/msgid/qubes-devel/20160423203318.GB25979%40mail-itl

The build script may thrown off by the naming used for python-yaml package(?)

---

**Comment by marmarek** [comment]
Try again, the fix for it was just pushed to https://github.com/qubesos/qubes-builder repository

**Comment by ttasket** [comment]
Still not working. I'm using the default branch. Is that correct?

**Comment by marmarek** [comment]
Ah, sorry, pushed only one repo, now should be better.

**Comment by marmarek** [comment]
(the other one is qubes-mgmt-salt)

**Comment by ttasket** [comment]
Seems to work now, though I'm not 100% sure: gnome-terminal went a little berserk during the build process.

**Comment by axon-qubes** [comment]
> Seems to work now, though I'm not 100% sure

Since it seems to be working, I'll close this issue for now. Please feel free to re-open it later if it turns out things aren't working.
