### ISSUE TITLE
pvgrub2: fedora 23 does not boot with default fedora kernel package (dkms/dracut not run)

### ISSUE THREAD

**Issue by qjoo** [QubesOS/qubes-issues#1936]
#### Qubes OS version

R3.1
#### Affected TemplateVMs

fedora-23
### General notes:

Today I wanted to try R3.1 new pvgrub2 support, but it didn't work as expected with the default fedora kernel package. 
The template VM did no longer boot completely after switching to pvgrub2, my guess was that the qubes kernel module is not loaded. Turnes out this was the case.
### Expected behavior:

dkms and initramfs should work out of the box for fedora kernel packages (like it says in the documentation)
### Actual behavior:

dkms for u2mfn is not handled out of the box for default fedora packages
### Steps to reproduce the behavior:

follow the steps in section "Installing kernel in Fedora VM"  on
https://www.qubes-os.org/doc/managing-vm-kernel/
(how does one link to specific sections on these pages?)
### workaround

Here is how I got it to work:
- temporarily disable the qubes repo (otherwise it wouldn't install the qubes-devel for the fedora kernel)
- installed package 'kernel-devel'
  manually took care of dkms and initramfs:
- `dkms install u2mfn/3.1.8 -k 4.4.7-300.fc23.x86_64`
- `dracut  --kver 4.4.7-300.fc23.x86_64 --force`

**Comment by axon-qubes** [comment]
> https://www.qubes-os.org/doc/managing-vm-kernel/
> (how does one link to specific sections on these pages?)

Ordinarily, you would have two options:

1. Use the auto-generated ToC on the sidebar.

    This option isn't available on that page due to the problem described in #1914. In other words: Whoever wrote that page used `h1` headings for body sections instead of smaller headings, so no ToC links have been automatically generated.

2. Add `#name-of-the-section` to the end of the URL (standard Markdown convention).

    For example:
    https://www.qubes-os.org/doc/managing-vm-kernel/#using-kernel-installed-in-the-vm
    (Note that this method works despite the #1914 problem.)

**Comment by marmarek** [comment]
It looks it's all about `kernel-devel` package version. When the right version is installed, it just works. Probably installing it before any of packages mentioned in documentation should be the way to go.

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
