### ISSUE TITLE
Document pci_strictreset on USB page

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#1946]
https://groups.google.com/d/msg/qubes-users/LH7zs-lBARg/iXp99ypCJwAJ

**Comment by esote** [comment]
@andrewdavidwong Would you say additional documentation is still needed on this? Now in the device settings there's a button for configuring strict reset for PCI devices, which contains usage instructions.

**Comment by andrewdavidwong** [comment]
> Would you say additional documentation is still needed on this? Now in the device settings there's a button for configuring strict reset for PCI devices, which contains usage instructions.

We can close this for now and reopen if anyone reports that further documentation is needed.
