### ISSUE TITLE
Document Torified update checking

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#1948]
https://forums.whonix.org/t/does-dom0-check-update-go-over-tor/2334/2

**Comment by unman** [comment]
I've pushed some changes to qubes-doc adding more information on update checking etc in 3.2 and 4.0.
[dom0](https://www.qubes-os.org/doc/software-update-dom0/), and in [qubes](https://www.qubes-os.org/doc/software-update-vm/)
Can you review please @adrelanos and @andrewdavidwong ?
If you're happy, close this.

**Comment by andrewdavidwong** [comment]
Thank you, @unman. I gather that you're referring to https://github.com/QubesOS/qubes-doc/commit/03668786c4936f9e108cafb82b4ab8adb72eed3e. Correct?

1. Would you mind separating the 3.2 and 4.0 content as prescribed in our [Documentation Guidelines](https://www.qubes-os.org/doc/doc-guidelines/#version-specific-documentation)?
2. I don't think this is an accurate description of how the UpdateVM works in 3.2. The UpdateVM is the VM in which dom0 updates are downloaded, not the VM that TemplateVMs use as their NetVM. Setting the UpdateVM to `sys-whonix` will not result in TemplateVMs downloading updates over Tor if those TemplateVMs still have `sys-firewall` as their NetVM. In fact, it will probably not even result in dom0's updates being downloaded over Tor, since traffic from `sys-whonix` *itself* is not Torified.

In the future, if you'd like to have a doc contribution reviewed, please consider submitting it as a PR so that we can leverage our established doc contribution workflow.

**Comment by andrewdavidwong** [comment]
I've reverted https://github.com/QubesOS/qubes-doc/commit/03668786c4936f9e108cafb82b4ab8adb72eed3e for now, since the risk of deanonymization from following these instructions has the potential to be dangerous for some users. Perhaps we could take this opportunity to have the revised content submitted as a PR for further review?

**Comment by unman** [comment]
@andrewdavidwong I wasn't actually expecting that to hit the site - in the past when I've pushed changes to qubes-docs they haven't automatically been applied. Apologies.

You're quite right, of course for 3.2 Templates, but not, I think, for dom0 - the _existing_ page says that setting UpdateVM to sys-whonix will torify dom0 updates, so I think the addition to that section should be fine.

**Comment by andrewdavidwong** [comment]
> You're quite right, of course for 3.2 Templates, but not, I think, for dom0 - the *existing* page says that setting UpdateVM to sys-whonix will torify dom0 updates, so I think the addition to that section should be fine.

I see that portion was added over two years ago in https://github.com/QubesOS/qubes-doc/commit/6b8b0ecc3a65dee123520371c553cffaf7b92ed1. However, given that traffic from sys-whonix *itself* is usually not Torified, I'd love to get confirmation from @marmarek that it actually works as described.

**Comment by marmarek** [comment]
> However, given that traffic from sys-whonix itself is usually not Torified, I'd love to get confirmation from @marmarek that it actually works as described.

That was true about old TorVM. Whonix Gateway have appropriate handling to route dom0 updates through tor (uwt wrapper), when it's set as updatevm.

**Comment by andrewdavidwong** [comment]
Ok, great! Thanks, @marmarek!

**Comment by adrelanos** [comment]
Andrew David Wong:
> However, given that traffic from sys-whonix *itself* is usually not Torified

It it, always was and will be. :)

What we're away from Qubes being 100% torified is sys-whonix being
capable to act as a ClockVM. (Ticket exists on Whonix tracker.)

**Comment by andrewdavidwong** [comment]
>> However, given that traffic from sys-whonix *itself* is usually not Torified
>>
> It it, always was and will be. :)

My mistake! I was confusing `sys-whonix` with `TorVM`. Thank you for the correction!

**Comment by adrelanos** [comment]
Anything left to do here?

**Comment by DemiMarie** [comment]
Nope.
