### ISSUE TITLE
Create documentation about Awesome window manager

### ISSUE THREAD

**Issue by bnvk** [QubesOS/qubes-issues#1949]
Numerous people I talk to are hesitant to try using Qubes because they can't live without a "tiling window manager" I know @woju did some initial work on [Awesome window manager](https://github.com/woju/qubes-desktop-linux-awesome) and recently @isislovecruft forked that and did some additional things to get it working.

I'm opening this issue to track / follow this pursuit, as it worthwhile to have available for a certain userbase!

**Comment by andrewdavidwong** [comment]
Users have been making progress in this thread: https://groups.google.com/d/topic/qubes-devel/cnbRLmnOUds/discussion

In particular: https://gitlab.com/markwalters1009/qubes-awesome-git

**Comment by marmarek** [comment]
@woju please package it, to have at least something.

**Comment by debunge** [comment]
How is status with i3wm window manager? How much work needs to be done?

**Comment by kalkin** [comment]
@debunge I'm using this https://github.com/SietsevanderMolen/i3-qubes.git It's not the latest version of i3 but works fine.

**Comment by gigavinyl** [comment]
Are there any plans to support bspwm?

**Comment by andrewdavidwong** [comment]
> Are there any plans to support bspwm?

No plans on our end, but contributions are always welcome.

**Comment by 3hhh** [comment]
Can be closed?

awesome & i3 are supported, both documented.

+ this originally wasn't about bspwm.
