### ISSUE TITLE
Showcase LinuxCon2014 slides more prominently on website

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#1950]
Current location:

https://www.qubes-os.org/news/2014/08/19/linuxcon-eu-2014-slides/

CC @bnvk

**Comment by bnvk** [comment]
I just read the email thread. I'm not quite sure I understand the importance / relevance of this particular document and why it should be more prominent. It could make sense to just have a collection of **Talks**  displayed somewhere like [qubes-os.org/talks/](https://qubes-os.org/talks/)

**Comment by andrewdavidwong** [comment]
Well, that would be something to ask @rootkovska about, but my guess is that having a **Talks** section and putting the slides there would achieve the desired result.

**Comment by marmarek** [comment]
Or simply have such section on https://qubes-os.org/doc/ ? Between "Reference" and "For developers". That slides from LinuxCon have a lot of useful, practical information.

**Comment by andrewdavidwong** [comment]
Ok, let's do it that way.

**Comment by andrewdavidwong** [comment]
@rootkovska, @marmarek: How's that?

**Comment by andrewdavidwong** [comment]
Assuming it's fine. If not, please re-open.
