### ISSUE TITLE
Fix qubes.storage.get_disk_usage(self.volumes[...]) in QubesVM

### ISSUE THREAD

**Issue by woju** [QubesOS/qubes-issues#1961]
There are three issues:
1. `get_disk_usage` is in `qubes.storage.file`
  1.1. @marmarek is not sure if this is right place, because it may be used in other places. I (@woju) am however quite sure that yes, this is the right place, but it should be documented.
2. There is no `self.volumes` anymore
3. Maybe those functions should be removed, because they are already marked as deprecated.

```
vm/qubesvm.py-    def get_root_img_sz(self):
vm/qubesvm.py-        '''Get the size of the :py:attr:`volumes['root']`.
vm/qubesvm.py-
vm/qubesvm.py-        This is a temporary wrapper for backwards compatibility. You should
vm/qubesvm.py-        call directly :py:attr:`volumes[name].size`
vm/qubesvm.py-        :returns: domain's virtual disk size [FIXME unit]
vm/qubesvm.py-        :rtype: FIXME
vm/qubesvm.py-
vm/qubesvm.py-        .. seealso:: :py:meth:`get_disk_utilization_root_img`
vm/qubesvm.py-        '''
vm/qubesvm.py-
vm/qubesvm.py-        warnings.warn(
vm/qubesvm.py-            "get_disk_root_img_sz is deprecated, use volumes['root'].size",
vm/qubesvm.py-            DeprecationWarning)
vm/qubesvm.py:        return qubes.storage.get_disk_usage(self.volumes['root'].size)
vm/qubesvm.py-
```

**Comment by kalkin** [comment]
My idea was that in future if qubes-manager or anything else want to to know the disk size/usage it should just iterate over `vm.volumes` and call the appropriate fields for size and usage. 

I would do the following:

- [ ] remove old functions
- [ ] document that each own implementation of volume needs size and usage properties.
- [ ] Maybe remove the all the `QubesVM` utilization and size methods?

**Comment by marmarek** [comment]
> - [ ] Maybe remove the all the `QubesVM` utilization and size methods?

I'd leave them there. Or simply one method - `get_disk_usage` - overall disk usage of this VM. This method should summarize all the VM own volumes (but not for example root volume for AppVM). Detailed information can be get from `vm.storage`. 

As for "own" definition - I'd use volume type here - exclude read-only and snapshot volumes .

**Comment by woju** [comment]
Not sure about read-only volumes, but it probably should exclude root volume from AppVM, externally attached (from `qvm-block`) etc. The reason is that it will be used not only by qubes-manager, but also by `qvm-ls`.

**Comment by kalkin** [comment]
I think this can be closed, it's an very old issue.
