### ISSUE TITLE
document "split-bitcoin" (watching / cold wallet) implementation

### ISSUE THREAD

**Issue by mfc** [QubesOS/qubes-issues#1966]
it is a lot simpler than this qubes-users thread:

https://groups.google.com/d/msg/qubes-users/AkZo8xOxi18/-pgvSV6FDwAJ

first section of page would introduce the concept, maybe highlight which clients have the cold wallet / watching wallet capability. second section would go through how one would set it up with one example client. I [set it up with electrum](http://docs.electrum.org/en/latest/coldstorage.html) and it was quite easy, just had to install jessie-backports.

very low priority but something that is likely of interest to Qubes users (or potential users). There may already be documentation out there on it, just not in the google group.

-------------------

How to set up offline "cold storage" bitcoin wallet and an online watching-only bitcoin wallet:

1. Create a Debian 8 backports template using the Qubes VM Manager or running
   `qvm-clone debian-8 debian-8-backports` in dom0.

2. Add backports to the sources for the new template by opening a terminal in
   the new template, run `sudo vi /etc/apt/sources.list` and add
   `deb http://http.debian.net/debian jessie-backports main`.

   (If you are new to `vi` text editing, type `i` to be able to edit, and when
   done editing press `ESC` then type `:x` and press `ENTER`.)

3. Update source list: `sudo apt-get update`.

4. Install `electrum` from backports:
   `sudo apt-get -t jessie-backports install electrum`.

5. shut down your `debian-8-backports` template

6. create an `offline-bitcoin` qube based on `debian-8-backports` using the Qubes VM Manager or running `qvm-create -t debian-8-backports -l black offline-bitcoin` and `qvm-prefs -s offline-bitcoin netvm none` in dom0.

7. follow the [electrum documentation in creating an offline wallet](http://docs.electrum.org/en/latest/coldstorage.html#create-an-offline-wallet)

8. create a `watching-bitcoin` qubes based on `debian-8-backports` connecting to the internet how ever you prefer using the Qubes VM Manager or running for example `qvm-create -t debian-8-backports -l green watching-bitcoin` and `qvm-prefs -s watching-bitcoin netvm sys-whonix` in dom0.

9. follow the [electrum documentation in creating an online watching-only wallet](http://docs.electrum.org/en/latest/coldstorage.html#create-a-watching-only-version-of-your-wallet)

**Comment by bnvk** [comment]
This is really nifty, perhaps we should add **Bticoin** or **cryptocurrency enthusiast** as a persona type in #1906

**Comment by mfc** [comment]
@andrewdavidwong when you have the chance could you super-briefly frame this guide like you did for Martus and put it up (I guess in the privacy section)? you did a great job with that one.

**Comment by andrewdavidwong** [comment]
Sure thing. It's available [here](https://github.com/QubesOS/qubes-doc/edit/master/security/split-bitcoin.md). (I decided to put it in `/security` because I think it'll be a slightly better fit for that section.)

**Comment by mfc** [comment]
added content to that, would be great to push it up if it looks good.

**Comment by andrewdavidwong** [comment]
@mfc: Looks good; merged. :)

Does anything else need to be done for this issue?

**Comment by mfc** [comment]
all good :)

**Comment by adrelanos** [comment]
This still needs to be added to documentation index https://www.qubes-os.org/doc/?

**Comment by andrewdavidwong** [comment]
Ah, of course. [Added](https://github.com/QubesOS/qubes-doc/commit/176d9394df62e2c5c49aeda4b667c620f6c4c8f4). Thanks, Patrick.

**Comment by thomaskey** [comment]
electrum 2.7.9 has a offline transaction signing bug and the qubes documented repository only has this version.  Is there a recommended way to update the template electrum to  2.7.11 with bug fix? 

Some references to mention of bug links:

https://github.com/spesmilo/electrum/issues/2146

https://labs.riseup.net/code/issues/12323

**Comment by marmarek** [comment]
Any more information on this bug? I do use the above setup without any problem...
Anyway, you can use Fedora template - Fedora 25 have electrum 2.8.3.

**Comment by thomaskey** [comment]
It is bug in electrum only specific to version 2.7.9.  When signing transactions the offline mode electrum still will try to connect to network and you get timeout error.  Downgrading would fix problem also.  

I used the template documented in qubes-os docs.  So I think the qubes docs should change the template in the instructions, or upgrade or downgrade electrum package in the template.
