### ISSUE TITLE
Emergency backup recovery instructions should warn user about passwords in shell history and process list

### ISSUE THREAD

**Issue by defuse** [QubesOS/qubes-issues#1967]
The [Emergency Backup Recovery](https://www.qubes-os.org/doc/backup-emergency-restore-v3/) documentation instructs the reader to type their password into command-line arguments without mentioning that it'll be saved in their shell history and will be visible in the process list while the commands are running. Add those warnings, or switch to different tools that don't have these vulnerabilities (#971).

**Comment by mutablescutoid** [comment]
Would putting instructions for users to put the passphrase into an environmental variable and using that place of the passphrase solve the issue? Only the name of the environmental variable will be present in shell history and process list.

**Comment by rustybird** [comment]
> Would putting instructions for users to put the passphrase into an environmental variable and using that place of the passphrase solve the issue?

That's how the [v4 instructions](https://www.qubes-os.org/doc/backup-emergency-restore-v4/) do it.

**Comment by andrewdavidwong** [comment]
> > Would putting instructions for users to put the passphrase into an environmental variable and using that place of the passphrase solve the issue?
> 
> That's how the [emergency restore instructions for backup format v4](https://www.qubes-os.org/doc/backup-emergency-restore-v4/) do it.

Does that mean this is already done, then?

**Comment by rustybird** [comment]
> Does that mean this has already been resolved, then?

Only in the format v4 instructions so far, but https://github.com/QubesOS/qubes-doc/pull/1222 would resolve it for v2 and v3.
