### ISSUE TITLE
No Qubes-Windows-Tools Misleading Error Message

### ISSUE THREAD

**Issue by Jeeppler** [QubesOS/qubes-issues#1977]
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):
- Windows VM

---

### Expected behavior: 

Error message: Qubes-Windows-Tools are not installed on the system. Please install....

### Actual behavior: 

Misleading error message: libxenlight failed to create VM

### Steps to reproduce the behavior:

Preconditions: 
Qubes OS system, which does not have Qubes-Windows-Tools installed

1. Install or import Windows VM
  1. If running-> shutdown Windows VM
2. Select in Qubes Manager context menu: Start VM for Windows Tools installation

### General notes:

It should not be possible to select: Start VM for Windows Tools installation in the Qubes Manager context menu. The context menu should be disabled and not clickable.

---

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-dom0-3.2.4-1.fc23` has been pushed to the `r3.2` testing repository for dom0.
To test this update, please install it with the following command:
```
sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-admin/compare/7f86782e1470a8076bb6ab6684bb6e3907dbc7aa...376dc43b907afa41a9d94c02431a5bc7f14756dc

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-dom0-3.1.17-1.fc20` has been pushed to the `r3.1` testing repository for dom0.
To test this update, please install it with the following command:
```
sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-admin/compare/1e29d7fa396a1469541a6d64e48f398396f79780...d8093f38c428e4a9e7be421f2dc57e0a45a19477

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-dom0-3.1.17-1.fc20` has been pushed to the `r3.1` stable repository for dom0.
To install this update, please use the standard update command:
```
sudo qubes-dom0-update
```
Or update dom0 via Qubes Manager.

[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-admin/compare/1e29d7fa396a1469541a6d64e48f398396f79780...d8093f38c428e4a9e7be421f2dc57e0a45a19477

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-dom0-3.2.7-1.fc23` has been pushed to the `r3.2` stable repository for dom0.
To install this update, please use the standard update command:
```
sudo qubes-dom0-update
```
Or update dom0 via Qubes Manager.

[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-admin/compare/7f86782e1470a8076bb6ab6684bb6e3907dbc7aa...f0489a3d5cb5455eb6e658cfa2350b8a86c2442c
