### ISSUE TITLE
Document Kali Linux VM creation

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#1981]
@Jeeppler [wrote](https://groups.google.com/d/msgid/qubes-users/a73998cb-396b-4d32-b27e-42a173b763f3%40googlegroups.com):

> Katooline allows you to install Kalilinux tools in Debian. With other words 
> is allows you to turn a existing Debian VM into a Kalilinux VM. 
> 
> The steps for Qubes OS are:
> 1. Create a new AppVM and set the mark on standalone option in the GUI 
>    dialog
> 2. Follow the installation instructions for Katoolin:
>    
>    http://www.tecmint.com/install-kali-linux-tools-using-katoolin-on-ubuntu-debian/
> 3. Install the packages you want to have
> 
> The advantage of this approach is, that the Qubes OS developers or any 
> community member does not have to maintain an extra distribution for Qubes OS.

If this works and turns out to be a good way to create Kali Linux VMs in Qubes, it should be documented.

**Comment by andrewdavidwong** [comment]
Related thread: https://groups.google.com/d/topic/qubes-users/abycwxvHYSM/discussion

**Comment by andrewdavidwong** [comment]
[Achim Patzner](https://groups.google.com/d/msgid/qubes-users/63FDBCE6-7C4F-495B-9CDA-26C8757DCEF5%40noses.com):
> You might add that there are other options besides this (e. g. using PTF) which might not be as devastating to /usr (i. e. don’t necessarily require their own template).

**Comment by Vfreeze31** [comment]
Added some content to the starting page for the Kali Guide. Not sure how good it is but hopefully it can be the start for something.

**Comment by Jeeppler** [comment]
Do you have a link?

**Comment by andrewdavidwong** [comment]
Thanks, @Vfreeze31! It looks like a good start. Merged: https://github.com/QubesOS/qubes-doc/commit/bc433f4eb798c2cf6490d2a328708c4d89d718fa

**Comment by andrewdavidwong** [comment]
@Jeeppler, here's the link: https://www.qubes-os.org/doc/kali/

**Comment by crypt0beard** [comment]
Andrew, 

Has anyone tested these instructions? If not, I can do so as well as document it.

**Comment by andrewdavidwong** [comment]
@crypt0beard: That would be great, thanks! I don't know whether anyone else has tested them yet. (@Jeeppler, @Vfreeze31?)

**Comment by Jeeppler** [comment]
I tested the Kalilinux installation with Katoolin. I also took some screenshots. 

I run into some issues with some packages https://github.com/LionSec/katoolin/issues/21, but overall it was successful. 

I was not using the instructions from qubes-doc Kali. There are some steps missing. I will update the documentation this weekend.

@crypt0beard I would be happy if you could test the updated instructions.

**Comment by crypt0beard** [comment]
@Jeeppler Sure thing, I will keep an eye out for the updated instructions.

**Comment by Vfreeze31** [comment]
Thank you for your work @Jeeppler, we appriciate all you can do to assist.

I am sorry as I did not test as currently I do not have a qubes system to test them on and these kinds of instructions do need to be tested.

**Comment by Jeeppler** [comment]
@andrewdavidwong where shall I put screenshots or other images in qubes-doc?

**Comment by andrewdavidwong** [comment]
Please submit a pull request to add them (in a directory named "Kali") [here](https://github.com/QubesOS/qubes-attachment/tree/master/wiki).

**Comment by Jeeppler** [comment]
how shall I link them?

**Comment by crypt0beard** [comment]
If you want to send them directly to me for testing I can take a look at them, as far as putting up online I would talk to the Qubes guys. 
On Jun 10, 2016 19:18, Jeppler <notifications@github.com> wrote:how shall I link them?

**Comment by andrewdavidwong** [comment]
@Jeeppler:
> how shall I link them?

Using standard Markdown notation. Take a look at the way it's done on [this page](https://raw.githubusercontent.com/QubesOS/qubes-doc/master/developers/doc-guidelines.md), for example:

```
![fork](/attachment/wiki/doc-edit/05-fork.png)
```

**Comment by Jeeppler** [comment]
@andrewdavidwong thanks

**Comment by lorenzog** [comment]
Hi all,

I've cleaned up the instructions and added my own notes. I have a repo forked here: https://github.com/lorenzog/qubes-doc/blob/master/managing-os/kali.md

Please note that it's not yet stable - while I can safely add tools to my Kali template, I cannot add e.g. `kali-linux-full` because it requires desktop components that depend on a newer X server which will break qubes-agent because it wasn't compiled for it.

Any feedback more than welcome.

**Comment by Jeeppler** [comment]
@lorenzog what package produces the issue?

**Comment by lorenzog** [comment]
@Jeeppler if I pin xserver-xorg* and xorg* to debian jessie, then that's what happens:

 * Trying to install kali-linux-web fails because it depends on kali-linux
 * Trying to install kali-linux failes because it depends on kali-desktop-common
 * Trying to install kali-desktop-common fails because it depends on xserver-xorg-legacy
 * Trying to install xserver-xorg-legacy fails because it would remove qubes-core-agent, xserver-xorg-core, xserver-xorg-input-all

At that point I stopped as qubes-core-agent is important.

I think the next step would be to try to recompile it as a debian package against the xorg provided by kali, and see what happens.

**Comment by cyrinux** [comment]
Hi, @lorenzog I have follow and do a merge request on your guide for add apt-get update && apt-get dist-upgrade, after this all works

**Comment by Jeeppler** [comment]
I actually created a guide for Kalilinux with and without Katoolin as well as for PTF and BlackArch. I will create a pull request as soon as I finish the documentation for #911 too.

Installing the `kali-linux` package is a problem for me too, but it does not want to remove all the qubes-packages. Kali seems to reconfigure some Xorg settings.

**Comment by Jeeppler** [comment]
I created a pull request in qubes-doc and qubes-attachment for the documentation.

**Comment by lorenzog** [comment]
@cyrinux so after the apt-get update and dist-upgrade, can you install kali-linux-all and run the appVM normally i.e. launching terminals from Qubes?

**Comment by cyrinux** [comment]
No lorenzo your are right but I can install the package. Without this I
can't install it. For the moment only access via xl console work. There is
yet xorg problem?

**Comment by andrewdavidwong** [comment]
User "NewbieG" has [reported](https://groups.google.com/d/msgid/qubes-users/4e750d6f-9497-43e6-89e4-673b619fda2f%40googlegroups.com) a couple of problems when attempting to follow the existing instructions:

> First one, works ok if you run kali from DVD without installing it. If I try
> to install it, login window flickers and once logged on, the desktop shows up
> 'misplaced' (see attach).
> 
> Second one, as someone already pointed out in the list, introduces conflicts
> between X packages from kali and X packages from the debian-9 template.

**Comment by desmond-decker** [comment]
Confirmed neither installation method works. Installing as a HVM from an ISO or installing the packages into a debian-8 template as directed both result in unusable Kali VMs.

**Comment by Jeeppler** [comment]
@desmond-decker how did you install the packages into your debian-8 template? What is a usable "Kali VM" for you?

**Comment by andrewdavidwong** [comment]
[On 2016-10-07 00:37, petorian wrote:](https://groups.google.com/d/msgid/qubes-users/2cfc8134-6621-4297-823a-9e996cf16ba8%40googlegroups.com)
> I was wondering if anyone else is experiencing problems with installing Kali on a HVM in Qubes. When I boot the fresh installed Kali HVM i see the logon screen fine, but after that I see the top op the screen in the lower 10% of the window

**Comment by yilmi** [comment]
@lorenzog @cyrinux : 

The package breaking _qubes-gui_ is pulled by _kali-linux_ meta-packages (_xserver-xorg-legacy_).

_xserver-xorg-legacy_ installs the Xorg suid wrapper meant to keep compatibility with some video drivers (see https://lists.x.org/archives/xorg-devel/2014-March/040874.html)

When we run _/usr/bin/Xorg_ (shell script) it will check if Xorg.wrap exists, if the wrapper is available it will always run it. 


You have to change the default wrapper configuration in _/etc/X11/Xwrapper.conf_:

> allowed_users = anybody
> needs_root_rights = no

Reboot your VM and test gui

After some checks, I found that : 
- Xwrapper configuration is already set for fedora templates 
- In debian jessie _/usr/bin/Xorg_ is a binary, In stretch they have changed it to the shell script version (check for wrapper and run it)

@andrewdavidwong : Shall I open a new issue to push this configuration on debian stretch ?

**Comment by lorenzog** [comment]
Hi all,

I was able to generate a fully working Kali linux template on Qubes OS 3.2. No conflicts with xorg and the like.

Instructions: https://github.com/lorenzog/qubes-doc/blob/master/managing-os/kali.md

**Comment by andrewdavidwong** [comment]
@lorenzog: Have you considered submitting a PR for those?

**Comment by lorenzog** [comment]
@andrewdavidwong I will, but I thought to get some feedback in case I missed something first. Let me know if you think I can go ahead and submit it right away

**Comment by andrewdavidwong** [comment]
@lorenzog Getting feedback first is a good idea. :)

**Comment by Jeeppler** [comment]
@lorenzog 

1. You decribe only how to create a template, therefor your title is missleading. You also forget to mention that people are able to create a standalone vm with the help of your guide.
2. Instead of getting the GPG Key at the beginning I highly recommend you do insert the section between step 4 and 5 where you actually need the key.
3. "Ideally, verify the fingerprint through other channels" -> name other possible channels or don't mention it.
4. Your Debian installation link does not work
5. Your link to the Reddit page is maybe funny, but unecessary and people do not always get irony 
6. Alternative Options -> There is already a guide for [PTF](https://www.qubes-os.org/doc/pentesting/ptf/) and [BlackArch](https://www.qubes-os.org/doc/pentesting/blackarch/)

**Comment by lorenzog** [comment]
Hi @Jeeppler, thanks for the comments.

I've incorporated a few of them and ignored others I don't agree with. 

>     You decribe only how to create a template, therefor your title is missleading. You also forget to mention that people are able to create a standalone vm with the help of your guide.

I've added a [subsection](https://github.com/lorenzog/qubes-doc/blob/master/managing-os/kali.md#use-the-template) at the bottom, but item 4 of the [first section](https://github.com/lorenzog/qubes-doc/blob/master/managing-os/kali.md#how-to-create-a-kali-linux-vm) clearly says "use the template to build AppVMS". Do you think it's clearer now?

>     Instead of getting the GPG Key at the beginning I highly recommend you do insert the section between step 4 and 5 where you actually need the key.

I disagree, the GPG key should be fetched once and its step is a prerequisite, doesn't belong in the main flow.

>     "Ideally, verify the fingerprint through other channels" -> name other possible channels or don't mention it.

The [Kali installation page](http://docs.kali.org/introduction/download-official-kali-linux-images) suggests this step and I think it's extremely important. However this howto is not the right place to tell people how to do it, so I've added a sentence to my text telling the user to "verify the fingerprint through other channels as recommended on that link."

>     Your Debian installation link does not work

Thanks, fixed.

>     Your link to the Reddit page is maybe funny, but unecessary and people do not always get irony

Meh :) You're right, I've removed it.

>     Alternative Options -> There is already a guide for PTF and BlackArch

Updated, but I don't think it's necessary here.

**Comment by andrewdavidwong** [comment]
People are still reporting problems with only the bottom 10% of the Kali HVM window showing:

- #2761
- https://groups.google.com/d/topic/qubes-users/L-CKlk7auMQ/discussion

I find this puzzling, since I thought this was supposed to have been fixed in #2370 or #260 (or the combination of the two). What's going on? Are people just not following the working instructions that were merged in #260, or is something still broken?

CC @marmarek, @lorenzog, @Jeeppler

**Comment by lorenzog** [comment]
@andrewdavidwong this used to happen to me too so instead of fighting with Linux display drivers like it's 1995 again I went on and made the Kali template instead :) I haven't used Kali in a HVM since.

**Comment by Jeeppler** [comment]
@andrewdavidwong I had the same reason as @lorenzog to create a Kali template and because I wanted to be able to use the qubes tools (qvm-copy..., qvm-move... etc.)

However, I can understand that people would like to have the well sorted menu from Kali's Gnome Desktop. Adding dozens of tools via "add/remove app shortcut" will take a long time.

**Comment by andrewdavidwong** [comment]
@lorenzog, @Jeeppler: Ok, thanks for that info. In that case, it looks like this issue is completed, so I'll close it. I'll also reopen #2761 to track that problem separately.

**Comment by ppiotr3k** [comment]
@andrewdavidwong, @lorenzog, @Jeeppler: I've added some polishing to the contributions you've already made on creating a Kali TemplateVM, see https://github.com/QubesOS/qubes-doc/pull/431

For me, one of the essential needed improvements has been adding TemplateVM trimming/compacting in the instructions. In the TemplateVM instructions, a clone/upgrade is performed twice, thus a trimming saves several GB of disk space.
