### ISSUE TITLE
Create missing Debian packages

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#1984]
Create Debian packages for:
 - input proxy
 - image converter
(anything else?)

**Comment by unman** [comment]
I already have deb for image converter, but I'll need to test it on fedora. I'll do this at end of week.
These packages will need to be integrated into qubes-builder.
Are there other missing packages?

**Comment by marmarek** [comment]
Thanks!
Yes: usb-proxy: https://github.com/QubesOS/qubes-app-linux-usb-proxy
It isn't available in Qubes 3.1, will be part of 3.2.
And while at it - there is one more packaging problem: https://github.com/QubesOS/qubes-issues/issues/1974 (libxen needs more subpackages).

**Comment by marmarek** [comment]
Input proxy Debian package uploaded to testing repository for 3.1 :)

**Comment by unman** [comment]
@andrewdavidwong This could be closed: the missing packages are all built now as @marmarek has completed usb-proxy. The only open issue from here is at #1974
