### ISSUE TITLE
Qubes website needs link check function for broken links

### ISSUE THREAD

**Issue by beffenc** [QubesOS/qubes-issues#1989]
Applicable to website pages (noticeable on wiki and doc pages)

Broken links on wiki and doc pages have been prevalent for quite some time.

 **  It would be a great use of a script to check the website for broken links 
 **  either on a regular basis or on change /update submission

Example:
https://www.qubes-os.org/doc/dom0-tools/qvm-create-default-dvm/
Contains a broken link to: 
https://wiki.qubes-os.org/wiki/UserDoc/DispVMCustomization

SUGGESTION: 
Script to link check page activated on web page change or submission

**Comment by marmarek** [comment]
Actually such script exists: https://github.com/QubesOS/qubesos.github.io/blob/master/_utils/find_broken_links.sh
It simply isn't used...

**Comment by andrewdavidwong** [comment]
@bnvk, do you want to handle this?

**Comment by beffenc** [comment]
Would it be possible to add a hook, triggering the script on update or addition/change?
Then one large scan and manual fix would be necessary. After that, changes that break links (script nonzero exit) blocks submission or update until fixed. Incorporation would require hooking the git core functions here, correct?

**Comment by marmarek** [comment]
On Thu, May 12, 2016 at 08:26:51PM -0700, beffenc wrote:
> Would it be possible to add a hook, triggering the script on update or addition/change?
> Then one large scan and manual fix would be necessary. After that, changes that break links (script nonzero exit) blocks submission or update until fixed. Incorporation would require hooking the git core functions here, correct?

I think we can use Travis for that. Then every pull request will
automatically have info whether it breaks something or not.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by marmarek** [comment]
https://jekyllrb.com/docs/continuous-integration/

It uses `html-proofer`. But before we enable it, we need to fix current errors...
I've created `travis` branch in `qubesos.github.io` repository. And enabled travis usage there. Build log:
https://travis-ci.org/QubesOS/qubesos.github.io/builds/131024644
Most of those errors are broken links in page footer, so repeated on every page. After commenting them out, it's down to 45 errors, so no that bad...
I think the most sense would be to run html-proofer locally when working on that errors. But then feel free to push to that branch whenever you want.

**Comment by marmarek** [comment]
Progress:
https://travis-ci.org/QubesOS/qubesos.github.io/builds/162500972
https://github.com/QubesOS/qubesos.github.io/pull/55

If changing ToC links is not a problem, I think it can be merged and this ticket can be resolved.
/cc @andrewdavidwong

Possible next step would be to attach it also to qubes-doc repo (to see results directly in pull requests there), but it is slightly more complex, as qubes-doc is only a submodule. Probably not worth the effort.

**Comment by andrewdavidwong** [comment]
Thank you, @marmarek!

I think changing ToC links is OK, since at least old links will still link to the base page.
