### ISSUE TITLE
Failure to attach vif to netvm

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#199]
**Reported by rafal on 6 Apr 2011 10:25 UTC**
After many create/destroy domain cycles, xen is unable to do network-attach to netvm. In Netvm logs, there is:
[~](root@netvm1)# udevadm monitor
monitor will print the received events for:
UDEV - the event which udev sends out after rule processing
KERNEL - the kernel uevent

KERNEL[add      /devices/xen-backend/vif-76-0
(xen-backend)
Apr  6 06:08:00 localhost kernel: [ 2516.786792](1302084480.843334]) vif vif-76-0: 2 writing
feature-sg
Apr  6 06:08:00 localhost kernel: [ 2516.787018] vif vif-76-0: xenbus:
failed to write error node for backend/vif/76/0 (2 writing feature-sg)
Apr  6 06:08:00 localhost kernel: [ 2516.787532] vif vif-76-0: 2
xenbus_dev_probe on backend/vif/76/0
Apr  6 06:08:00 localhost kernel: [ 2516.787719] vif vif-76-0: xenbus:
failed to write error node for backend/vif/76/0 (2 xenbus_dev_probe on
backend/vif/76/0)
UDEV  [1302084480.848507] add      /devices/xen-backend/vif-76-0
(xen-backend)

the hotplug script is not called, the vif76.0 device is not present.
Nothing in xen logs, not dom0 logs.

Migrated-From: https://wiki.qubes-os.org/ticket/199

**Comment by whohoho** [comment]
Do you have a copy of the commit that fixes this issue? git.qubes-os.org is not there anymore.

Thanks

**Comment by marmarek** [comment]
https://github.com/marmarek/qubes-vmm-xen/commit/898fee18c1de8cc13db7c6143310f92449dc5a1d
