### ISSUE TITLE
Race condition at NetVM startup

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#1990]
In xen 4.6 in driver domain (like NetVM) backend devices are configured by `xl devd` daemon, instead of udev (like in previous versions). When this daemon is started after creating backend device, it will not be configured.

Racy situation:
1. `sys-net` is started
2. `sys-firewall` is started
3. `sys-firewall` is connected to `sys-net` (backend device is created in `sys-net` and frontend device in `sys-firewall`)
4. `xl devd` is started in `sys-net`

End result is that backend device in `sys-net` is not configured, so `sys-firewall` has no network access.

When starting netvm automatically during startup of other VM (like: starting `sys-net` as part of `sys-firewall` startup), the later one will be started only after full startup of the former one. But since the bug just happened on my machine, something is wrong:
 - either above mechanism is broken and  "after full startup" does not include "after starting `xl devd`", or
 - there is some other case when second domain (`sys-firewall`) is started during `sys-net` startup

**Comment by TNTBOMBOM** [comment]
i have this since long time , i have fixed it manually everytime i open Qubes:- 

opent quebs OS 
press on sleep
press Enter or any key (to get out from sleep)
shutdown sys-firewall , sys-net
open them again

then the internet going to work.

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `python2-dnf-plugins-qubes-hooks-3.2.6-1.fc23` has been pushed to the `r3.2` testing repository for the Fedora `fc23` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.2-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/d47a89ec76452a4c9efe3b5cbf87157083b3d765...e7b1711e2176bcf030d8c6c9698688aaf7639aee

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `python2-dnf-plugins-qubes-hooks-3.2.6-1.fc24` has been pushed to the `r3.2` testing repository for the Fedora `fc24` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.2-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/d47a89ec76452a4c9efe3b5cbf87157083b3d765...e7b1711e2176bcf030d8c6c9698688aaf7639aee

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `xen-4.6.1-18.fc23` has been pushed to the `r3.2` testing repository for the Fedora `fc23` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.2-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-vmm-xen/compare/a95d5db154ca4bec8c8e6fe392fdd027afb984cc...a6039bdb015596c8c36a1ff71280aec7360ef652

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `xen-4.6.1-18.fc24` has been pushed to the `r3.2` testing repository for the Fedora `fc24` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.2-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-vmm-xen/compare/a95d5db154ca4bec8c8e6fe392fdd027afb984cc...a6039bdb015596c8c36a1ff71280aec7360ef652

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `xen-4.6.1-18.fc23` has been pushed to the `r3.2` testing repository for dom0.
To test this update, please install it with the following command:
```
sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-vmm-xen/compare/a95d5db154ca4bec8c8e6fe392fdd027afb984cc...a6039bdb015596c8c36a1ff71280aec7360ef652

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-agent_3.2.6-1+deb8u1` has been pushed to the `r3.2` testing repository for the Debian `jessie` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `jessie-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/d47a89ec76452a4c9efe3b5cbf87157083b3d765...e7b1711e2176bcf030d8c6c9698688aaf7639aee

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `xen_4.6.1-18+deb8u1` has been pushed to the `r3.2` testing repository for the Debian `jessie` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `jessie-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-vmm-xen/compare/a95d5db154ca4bec8c8e6fe392fdd027afb984cc...c7afac2bf0ac792518b148efad750e9f24046534

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-agent_3.2.6-1+deb9u1` has been pushed to the `r3.2` testing repository for the Debian `stretch` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `stretch-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/d47a89ec76452a4c9efe3b5cbf87157083b3d765...e7b1711e2176bcf030d8c6c9698688aaf7639aee

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `xen_4.6.1-18+deb9u1` has been pushed to the `r3.2` testing repository for the Debian `stretch` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `stretch-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-vmm-xen/compare/a95d5db154ca4bec8c8e6fe392fdd027afb984cc...c7afac2bf0ac792518b148efad750e9f24046534

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-agent_3.2.6-1+deb7u1` has been pushed to the `r3.2` testing repository for the Debian `wheezy` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `wheezy-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/d47a89ec76452a4c9efe3b5cbf87157083b3d765...e7b1711e2176bcf030d8c6c9698688aaf7639aee

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `xen_4.6.1-18+deb7u1` has been pushed to the `r3.2` testing repository for the Debian `wheezy` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `wheezy-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-vmm-xen/compare/a95d5db154ca4bec8c8e6fe392fdd027afb984cc...c7afac2bf0ac792518b148efad750e9f24046534

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `xen-4.6.1-19.fc21` has been pushed to the `r3.1` testing repository for the Fedora `fc21` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.1-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-vmm-xen/compare/a95d5db154ca4bec8c8e6fe392fdd027afb984cc...e8d9b83e428130a168b056791c3ee4f558ec83c2

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `xen-4.6.1-19.fc22` has been pushed to the `r3.1` testing repository for the Fedora `fc22` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.1-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-vmm-xen/compare/a95d5db154ca4bec8c8e6fe392fdd027afb984cc...e8d9b83e428130a168b056791c3ee4f558ec83c2

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `xen-4.6.1-19.fc23` has been pushed to the `r3.1` testing repository for the Fedora `fc23` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.1-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-vmm-xen/compare/a95d5db154ca4bec8c8e6fe392fdd027afb984cc...e8d9b83e428130a168b056791c3ee4f558ec83c2

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `xen-4.6.1-19.fc20` has been pushed to the `r3.1` testing repository for dom0.
To test this update, please install it with the following command:
```
sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-vmm-xen/compare/a95d5db154ca4bec8c8e6fe392fdd027afb984cc...e8d9b83e428130a168b056791c3ee4f558ec83c2

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `xen-4.6.1-20.fc23` has been pushed to the `r3.2` stable repository for dom0.
To install this update, please use the standard update command:
```
sudo qubes-dom0-update
```
Or update dom0 via Qubes Manager.

[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-vmm-xen/compare/a95d5db154ca4bec8c8e6fe392fdd027afb984cc...7644813eaa6a77d1106dcda932edbda93c042cce

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `xen-4.6.1-20.fc20` has been pushed to the `r3.1` stable repository for dom0.
To install this update, please use the standard update command:
```
sudo qubes-dom0-update
```
Or update dom0 via Qubes Manager.

[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-vmm-xen/compare/2d284fc593110a18843574ac0c61d52cfa2a4ce9...7644813eaa6a77d1106dcda932edbda93c042cce

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `xen_4.6.1-20+deb8u1` has been pushed to the `r3.1` testing repository for the Debian `jessie` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `jessie-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-vmm-xen/compare/a95d5db154ca4bec8c8e6fe392fdd027afb984cc...7644813eaa6a77d1106dcda932edbda93c042cce

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `xen_4.6.1-20+deb9u1` has been pushed to the `r3.1` testing repository for the Debian `stretch` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `stretch-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-vmm-xen/compare/a95d5db154ca4bec8c8e6fe392fdd027afb984cc...7644813eaa6a77d1106dcda932edbda93c042cce

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `python2-dnf-plugins-qubes-hooks-3.2.9-1.fc23` has been pushed to the `r3.2` stable repository for the Fedora `fc23` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/d47a89ec76452a4c9efe3b5cbf87157083b3d765...fd8a1167446a8b2e8487d67b9c2888663327a805

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `python2-dnf-plugins-qubes-hooks-3.2.9-1.fc24` has been pushed to the `r3.2` stable repository for the Fedora `fc24` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/d47a89ec76452a4c9efe3b5cbf87157083b3d765...fd8a1167446a8b2e8487d67b9c2888663327a805

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `xen-4.6.1-20.fc23` has been pushed to the `r3.2` stable repository for the Fedora `fc23` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-vmm-xen/compare/a95d5db154ca4bec8c8e6fe392fdd027afb984cc...7644813eaa6a77d1106dcda932edbda93c042cce

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `xen-4.6.1-20.fc24` has been pushed to the `r3.2` stable repository for the Fedora `fc24` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-vmm-xen/compare/a95d5db154ca4bec8c8e6fe392fdd027afb984cc...7644813eaa6a77d1106dcda932edbda93c042cce

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `xen_2001:4.6.1-20+deb8u1` has been pushed to the `r3.2` stable repository for the Debian `jessie` template.
To install this update, please use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-vmm-xen/compare/a95d5db154ca4bec8c8e6fe392fdd027afb984cc...7644813eaa6a77d1106dcda932edbda93c042cce

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-agent_3.2.10-1+deb8u1` has been pushed to the `r3.2` stable repository for the Debian `jessie` template.
To install this update, please use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/d47a89ec76452a4c9efe3b5cbf87157083b3d765...1a601ddbe9bae11088a78136bfe7cd8a1b3258f1

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `xen-4.6.1-20.fc21` has been pushed to the `r3.1` stable repository for the Fedora `fc21` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-vmm-xen/compare/2d284fc593110a18843574ac0c61d52cfa2a4ce9...7644813eaa6a77d1106dcda932edbda93c042cce

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `xen-4.6.1-20.fc22` has been pushed to the `r3.1` stable repository for the Fedora `fc22` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-vmm-xen/compare/2d284fc593110a18843574ac0c61d52cfa2a4ce9...7644813eaa6a77d1106dcda932edbda93c042cce

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `xen-4.6.1-20.fc23` has been pushed to the `r3.1` stable repository for the Fedora `fc23` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-vmm-xen/compare/2d284fc593110a18843574ac0c61d52cfa2a4ce9...7644813eaa6a77d1106dcda932edbda93c042cce

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `python2-dnf-plugins-qubes-hooks-3.1.19-1.fc21` has been pushed to the `r3.1` testing repository for the Fedora `fc21` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.1-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/193eb55330f79a4c20bd695ee25b27adf27e2a96...1d74a449676cf31f41a17a6dff21be6246529740

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `python2-dnf-plugins-qubes-hooks-3.1.19-1.fc22` has been pushed to the `r3.1` testing repository for the Fedora `fc22` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.1-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/193eb55330f79a4c20bd695ee25b27adf27e2a96...1d74a449676cf31f41a17a6dff21be6246529740

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `python2-dnf-plugins-qubes-hooks-3.1.19-1.fc23` has been pushed to the `r3.1` testing repository for the Fedora `fc23` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.1-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/193eb55330f79a4c20bd695ee25b27adf27e2a96...1d74a449676cf31f41a17a6dff21be6246529740

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-agent_3.1.19-1+deb8u1` has been pushed to the `r3.1` testing repository for the Debian `jessie` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `jessie-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/193eb55330f79a4c20bd695ee25b27adf27e2a96...1d74a449676cf31f41a17a6dff21be6246529740

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-agent_3.1.19-1+deb9u1` has been pushed to the `r3.1` testing repository for the Debian `stretch` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `stretch-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/193eb55330f79a4c20bd695ee25b27adf27e2a96...1d74a449676cf31f41a17a6dff21be6246529740

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-agent_3.1.19-1+deb7u1` has been pushed to the `r3.1` testing repository for the Debian `wheezy` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `wheezy-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/193eb55330f79a4c20bd695ee25b27adf27e2a96...1d74a449676cf31f41a17a6dff21be6246529740

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `python2-dnf-plugins-qubes-hooks-3.1.19-1.fc21` has been pushed to the `r3.1` stable repository for the Fedora `fc21` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/193eb55330f79a4c20bd695ee25b27adf27e2a96...1d74a449676cf31f41a17a6dff21be6246529740

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `python2-dnf-plugins-qubes-hooks-3.1.19-1.fc22` has been pushed to the `r3.1` stable repository for the Fedora `fc22` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/193eb55330f79a4c20bd695ee25b27adf27e2a96...1d74a449676cf31f41a17a6dff21be6246529740

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `python2-dnf-plugins-qubes-hooks-3.1.19-1.fc23` has been pushed to the `r3.1` stable repository for the Fedora `fc23` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/193eb55330f79a4c20bd695ee25b27adf27e2a96...1d74a449676cf31f41a17a6dff21be6246529740

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-agent_3.1.19-1+deb8u1` has been pushed to the `r3.1` stable repository for the Debian `jessie` template.
To install this update, please use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/193eb55330f79a4c20bd695ee25b27adf27e2a96...1d74a449676cf31f41a17a6dff21be6246529740

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-agent_3.1.19-1+deb9u1` has been pushed to the `r3.1` stable repository for the Debian `stretch` template.
To install this update, please use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/193eb55330f79a4c20bd695ee25b27adf27e2a96...1d74a449676cf31f41a17a6dff21be6246529740

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-agent_3.1.19-1+deb7u1` has been pushed to the `r3.1` stable repository for the Debian `wheezy` template.
To install this update, please use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/193eb55330f79a4c20bd695ee25b27adf27e2a96...1d74a449676cf31f41a17a6dff21be6246529740

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `xen_2001:4.6.1-20+deb8u1` has been pushed to the `r3.1` stable repository for the Debian `jessie` template.
To install this update, please use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-vmm-xen/compare/2d284fc593110a18843574ac0c61d52cfa2a4ce9...7644813eaa6a77d1106dcda932edbda93c042cce

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `xen_2001:4.6.1-20+deb9u1` has been pushed to the `r3.1` stable repository for the Debian `stretch` template.
To install this update, please use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-vmm-xen/compare/2d284fc593110a18843574ac0c61d52cfa2a4ce9...7644813eaa6a77d1106dcda932edbda93c042cce

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `xen_2001:4.6.1-17+deb7u1` has been pushed to the `r3.1` stable repository for the Debian `wheezy` template.
To install this update, please use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-vmm-xen/compare/2d284fc593110a18843574ac0c61d52cfa2a4ce9...7644813eaa6a77d1106dcda932edbda93c042cce

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `xen_4.6.3-24+deb7u1` has been pushed to the `r3.1` testing repository for the Debian `wheezy` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `wheezy-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-vmm-xen/compare/a95d5db154ca4bec8c8e6fe392fdd027afb984cc...32b1442ab291db9b952cd737cf0ad402db56cd3d
