### ISSUE TITLE
Add direct links to sections

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#1991]
Currently it is quite cumbersome to get a link to specific section in documentation. When that's top level section it isn't that bad, because ToC can be used, but for some inner sections it isn't that easy. Personally I click "inspect element" on given section title and manually copy element id to the link. Not the most user friendly way ;)
Example link:
https://www.qubes-os.org/doc/qrexec3/#service-argument-in-policy
Ideally section headers should have link to itself somewhere handy (either the title itself, or somewhere near it).

**Comment by andrewdavidwong** [comment]
Duplicate of #1713?

**Comment by marmarek** [comment]
Yes...
