### ISSUE TITLE
qubes-hcl-report doesn't properly escape spaces in machine name

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#1994]
There is expression meant to replace non-alphanumeric characters with underscore, but apparently it doesn't work:
https://github.com/QubesOS/qubes-core-admin/blob/master/qvm-tools/qubes-hcl-report#L106
```bash
FILENAME="Qubes-HCL-${BRAND//+([^[:alnum:]])/_}-${PRODUCT//+([^[:alnum:]])/_}-$DATE"
```
According to bash manual it should be ok. And it works on bash 4.3.42, but not on 4.2.53 which we have in dom0. Some bash bug?

[Reported by picard](https://groups.google.com/d/msgid/qubes-users/59827caf-4131-47a8-8b41-8baa7db6a1e9%40googlegroups.com)

**Comment by unman** [comment]
What about this?
`FILENAME="Qubes-HCL-${BRAND//[^[:alnum:]]/_}-${PRODUCT//[^[:alnum:]]/_}-$DATE"`

**Comment by marmarek** [comment]
Yes, I have exactly this already committed, just not pushed yet.

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-dom0-3.1.17-1.fc20` has been pushed to the `r3.1` testing repository for dom0.
To test this update, please install it with the following command:
```
sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-admin/compare/1e29d7fa396a1469541a6d64e48f398396f79780...d8093f38c428e4a9e7be421f2dc57e0a45a19477

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-dom0-3.1.17-1.fc20` has been pushed to the `r3.1` stable repository for dom0.
To install this update, please use the standard update command:
```
sudo qubes-dom0-update
```
Or update dom0 via Qubes Manager.

[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-admin/compare/1e29d7fa396a1469541a6d64e48f398396f79780...d8093f38c428e4a9e7be421f2dc57e0a45a19477
