### ISSUE TITLE
qubes-img-converter broken

### ISSUE THREAD

**Issue by unman** [QubesOS/qubes-issues#1995]
#### Qubes OS version (e.g., `R3.1`):
R3.0, R3.1
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):
fedora-21, fedora-23

---

### Expected behavior:
Should generate trusted image.
### Actual behavior:
No action.
### Steps to reproduce the behavior:
install qubes-img-converter 
Attempt to generate trusted file from nautilus.

### General notes:
qubes-img-converter  is not well documented and not installed by default.
Error arises because of missing file qvm-convert-img.gnome

I have packaged for Debian, and can fix, but wonder if it is intended to keep this utility.
Why is it not installed by default?
Should it not be documented or referred to?

---

**Comment by andrewdavidwong** [comment]
For reference: https://github.com/QubesOS/qubes-app-linux-img-converter

Last commit was a year ago. I'm not sure what its current status is. @marmarek?

**Comment by marmarek** [comment]
This tool was never fully finished, but there is really not much missing. Mostly integration with file manager and documentation.

**Comment by andrewdavidwong** [comment]
Ok, I'll leave this issue open and label it `help wanted` in case anyone from the community wants to finish it.

**Comment by unman** [comment]
I'm in process of finishing this off.
@andrewdavidwong Is there documentation on the pdf converter? Do you want a new page on these utilities?

**Comment by andrewdavidwong** [comment]
@unman: None that I'm aware of, but having one would be great!

**Comment by marmarek** [comment]
The only one I'm aware of is http://blog.invisiblethings.org/2013/02/21/converting-untrusted-pdfs-into-trusted.html

**Comment by rootkovska** [comment]
Can we have this tool installed by default in 3.2, pls?

**Comment by marmarek** [comment]
Sure, shouldn't be a problem.
