### ISSUE TITLE
Only show AppVMs by default

### ISSUE THREAD

**Issue by dumbl3d0re** [QubesOS/qubes-issues#1997]
I think that we have much to gain by simplifying Qubes' interface. One thing to do is to remove "unnecessary" objects that is displayed by default. A cleaner interface make it more aesthetically pleasing. 

I propose that TemplateVMs and NetVMs should be hidden (not shown) by default, and only show AppVMs. This regards interfaces like `qubes-manager` and the application launcher.

- A option in the menu bar under "[v]iew" could toggle display of the "hidden" VMs.
- Have the "system VMs" in a special "group" in the application launcher under the title "System VMs". It's not very hidden, but something the name of the group should "scare away" any normal user.

I would guess that the risk of a normal user doing something unsafe in a TemplateVM or change some setting in the NetVMs is bigger than some potential gain by having these VMs easily accessible. Our users shouldn't need to be sysadmins or developers to use Qubes.

**Comment by marmarek** [comment]
This is already handled in new Qubes Manager (under development, see #1870).
