### ISSUE TITLE
Qubes Start Menu - add an "all shortcuts" sub menu

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#2000]
Qubes Start menu currently:

```
Add more shortcuts...
default shortcut 1
another default shortcut 2
...
```

Qubes Start feature request:

```
Add more shortcuts...
default shortcut 1
another default shortcut 2
...
all shortcuts...
```

Upon hovering over `all shortcuts...`, all available shortcuts should be shown.

This seems useful to me in cases where clicking `Add more shortcuts...` is too cumbersome. If users just want to try various applications (to learn more or to see if it fits their needs), they do not want to add them to their favorites just at this moment before having had the chance to just quickly try them.

//cc @bnvk

**Comment by marmarek** [comment]
Not sure if/how is possible to have more nested menu.
But anyway, it is possible to have all applications listed: remove `whitelisted-appmenus.list` file from VM directory and regenerate appmenus (start template and call `qvm-sync-appmenus` in dom0).

**Comment by marmarta** [comment]
This is covered by favorites menu in the new app menu ( https://github.com/QubesOS/qubes-desktop-linux-menu )
