### ISSUE TITLE
Error message "qrexec not connected" when quickly opening several applications in powered off AppVM

### ISSUE THREAD

**Issue by dumbl3d0re** [QubesOS/qubes-issues#2001]
#### Qubes OS version (e.g., `R3.1`):

R3.1
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):

Probably all (tested with debian-8 and whonix-ws AppVMs)

---
### Expected behavior:

Both applications start after the AppVM is powered up.
### Actual behavior:

Only the first application is started and the error message "[d]omain [domain]: qrexec not connected" can be read if hovering above the error triangle.
### Steps to reproduce the behavior:

Try to quickly start two, or more, applications in a currently powered off AppVM.
### General notes:

---
#### Relevant labels:
- Bug

**Comment by andrewdavidwong** [comment]
I'm unable to reproduce this on `whonix-ws`-based VMs. It sounds like it may be a more general VM startup issue.

**Comment by adrelanos** [comment]
It happens when clicking two applications to start them in one VM currently powered off VM too quickly. The bug description gets clearer when translating it into cli terms. How to reproduce:

```
qvm-run -q --tray -a pdf -- 'qubes-desktop-run /usr/share/applications/kde4/konsole.desktop' &
```

```
qvm-run -q --tray -a pdf -- 'qubes-desktop-run /usr/share/applications/gnome-terminal.desktop'
```

`ERROR(pdf): Domain 'pdf': qrexec not connected.`

**Comment by andrewdavidwong** [comment]
Ah, thank you. I can reproduce it now.
