### ISSUE TITLE
bug when trying to start a vm multiple times.

### ISSUE THREAD

**Issue by john-david-r-smith** [QubesOS/qubes-issues#2004]
#### Qubes OS version

R3.1
#### Affected

any vm

---
### Steps to reproduce the behavior:

select any stopped vm.
press on start multiple times
### Expected behavior:

one click is registered
the vm is started
further clicks are ignored.
### Actual behavior:

the vm is started.
further clicks generate a multitude of things:
errors in the notification area:
- connection reset by peer
- libxenlight failed to create new domain 
- domain already running
- not enough memory

error popups:

![snapshot1](https://cloud.githubusercontent.com/assets/19386140/15388385/06bdff98-1db2-11e6-8806-6431538964ac.png)
### General notes:

i think some atomic bool with swap(true) in the slot should be enough to ignore further signals. (i can't fix it since i don't know python)

**Comment by andrewdavidwong** [comment]
Thanks. Should be fixed in the coming Qubes Manager rework (#1870).

**Comment by marmarta** [comment]
It is fixed in this rework - I just checked, multiple clicks on Start VM just start the VM once without any errors..
