### ISSUE TITLE
Single bright pixel in upper-left corner of screen

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#2005]
Qubes creates a single bright pixel in the upper-left corner of the screen (on the leftmost monitor, if there are multiple monitors). This can be very noticeable (and distracting) when using fullscreen AppVMs with dark contents (e.g., watching movies, graphic design work). Possibly an artifact of the colored window decorations system.

More details and discussion: https://groups.google.com/d/topic/qubes-users/k3fEBJ2E3ig/discussion

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-gui-dom0-3.2.2-1.fc23` has been pushed to the `r3.2` testing repository for dom0.
To test this update, please install it with the following command:
```
sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-gui-daemon/compare/8e36881ceeeff19a7c04ae7341e213b0ef1a9f3b...50715fa1aba2e6f44d9328bea00084c626082b7b

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-gui-dom0-3.1.4-1.fc20` has been pushed to the `r3.1` testing repository for dom0.
To test this update, please install it with the following command:
```
sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-gui-daemon/compare/5c472ab3040ec936ca515131e343908673d5ff52...ee32d723ff454e47ddb06261055749882a6edb6f

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-gui-dom0-3.1.4-1.fc20` has been pushed to the `r3.1` stable repository for dom0.
To install this update, please use the standard update command:
```
sudo qubes-dom0-update
```
Or update dom0 via Qubes Manager.

[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-gui-daemon/compare/5c472ab3040ec936ca515131e343908673d5ff52...ee32d723ff454e47ddb06261055749882a6edb6f

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-gui-dom0-3.2.3-1.fc23` has been pushed to the `r3.2` stable repository for dom0.
To install this update, please use the standard update command:
```
sudo qubes-dom0-update
```
Or update dom0 via Qubes Manager.

[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-gui-daemon/compare/8e36881ceeeff19a7c04ae7341e213b0ef1a9f3b...7f6809f06f88404bceecfc6656af99e7abf8f8e9
