### ISSUE TITLE
Frozen at "setting up networking" during install

### ISSUE THREAD

**Issue by Truthlighting** [QubesOS/qubes-issues#2007]
#### Qubes OS version (e.g., `R3.1`):
latest version downloaded today. R3.1 stable

---

### General notes:
running on Dell laptop

---

**Comment by Truthlighting** [comment]
If nothing else, this problem is causing confusion due to inability to see the error. Making an error dialog trigger vs. a hard freeze would be better.

**Comment by andrewdavidwong** [comment]
This question is too localized for `qubes-issues`. Please consider posting this to the `qubes-users` mailing list instead. (You can read more about our mailing lists [here](https://www.qubes-os.org/mailing-lists/).)

`qubes-users` is intended for these sorts of questions and receives much more traffic, which means that your question is more likely to receive a response there.
