### ISSUE TITLE
Implement "offline mode" in R4.0

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#2008]
The idea of "offline mode" is to only manipulate `qubes.xml`, without talking to `libvirt` or other system components. This is useful for:
 - tests
 - installation
 - recovery situations

Of course things like starting VM should fail. But listing or setting some properties should work.

**Comment by woju** [comment]
There is something, but it currently raises exception almost instantly.
https://github.com/woju/qubes-core-admin/blob/core3-devel/qubes/app.py#L135-146⎋

-- 
pozdrawiam / best regards       _.-._
Wojtek Porczyk               .-^'   '^-.
Invisible Things Lab         |'-.-^-.-'|
                             |  |   |  |
 I do not fear computers,    |  '-.-'  |
 I fear lack of them.        '-._ :  ,-'
    -- Isaac Asimov             `^-^-_>

**Comment by marmarek** [comment]
Take a look at linked commit (https://github.com/marmarek/qubes-core-admin/commit/7de2e646f0d525d5c1a2ffac69cd4afc13d7ea74)

**Comment by woju** [comment]
On Sat, May 21, 2016 at 02:37:03PM -0700, Marek Marczykowski-Górecki wrote:
> Take a look at linked commit (https://github.com/marmarek/qubes-core-admin/commit/7de2e646f0d525d5c1a2ffac69cd4afc13d7ea74)

Won't hurt, but I can't tell from a glance if it is enough for some
weird cases. OK for patching through VMMConnection.__init__ and
Qubes.__init__.

Will probably need some --argument for various cli tools as it is in
core2. Possibly even for all tools, though likely not supported in all
combinations, especially with some weird interactions of events.
For example QubesVM.name property disallows changing name if domain is
running. If done naively, qvm-prefs --offline-mode would be unsafe.

-- 
pozdrawiam / best regards       _.-._
Wojtek Porczyk               .-^'   '^-.
Invisible Things Lab         |'-.-^-.-'|
                             |  |   |  |
 I do not fear computers,    |  '-.-'  |
 I fear lack of them.        '-._ :  ,-'
    -- Isaac Asimov             `^-^-_>
