### ISSUE TITLE
Krita doesn't start

### ISSUE THREAD

**Issue by dumbl3d0re** [QubesOS/qubes-issues#2010]
#### Qubes OS version (e.g., `R3.1`):
R3.1

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):
`debian-8` and `fedora-23`

---

### Expected behavior:
Krita starts without problems.

### Actual behavior:
The AppVM is started, Krita's icon begin to bounce and Krita shows up in the window panel. But nothing happens, and after some time the icon and entry in the window panel disappears.

### Steps to reproduce the behavior:
1. Install Krita (debian-8: `krita`, fedora-23: `calligra-krita`)
2. Try to start Krita from an AppVM.

### General notes:

---

**Comment by andrewdavidwong** [comment]
"Krita is a raster graphics editor based on the KDE Platform."

 - https://en.wikipedia.org/wiki/Krita
 - http://krita.org/

**Comment by mfc** [comment]
I was not able to confirm in debian-8, I have no problem running it (didn't try fedora-23). 

maybe try running it from the command line and see what errors come out? you can also send the run command from dom0 if you think there may be Qubes-specific errors.

**Comment by marmarek** [comment]
Same for me, on fedora-23. But: started in from terminal, not menu entry. Because unrelated bug in my testing environment prevented creating menu entries at all...

**Comment by andrewdavidwong** [comment]
@dumbl3d0re: Please try starting from the command line, and let us know.

**Comment by dumbl3d0re** [comment]
It works now apparently, both by starting it from terminal and the menu. Seems that I'd to reboot Qubes to get it to work.
