### ISSUE TITLE
Prevent (ana)cron output from going to /root/dead.letter

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#2012]
By default, in Qubes R3.1, a fair amount of `cron` and `anacron` output ends up in `/root/dead.letter` in dom0. This should probably be sent to `/dev/null` instead.

**Comment by unman** [comment]
@andrewdavidwong  I believe this issue is resolved in 3.2, and can be closed. I dont see any output in dead.letter on default install.
