### ISSUE TITLE
Create dom0 API to detect global disk space available

### ISSUE THREAD

**Issue by bnvk** [QubesOS/qubes-issues#2016]
Currently it is possible to create new app and networking qubes with an allowed disk space (that when added to existing qubes disk space) is more than that of the physical disk that Qubes OS is installed on. 

If the amount of used space ever goes over physically available space, bad things happen. 

The GUI should provide feedback (and limiters) that stop this from happening, thus an API should exist to easily get this `available_disk_space` value!

**Comment by marmarek** [comment]
The API and command line tool for that already exists (`qvm-pool -i lvm`). There is still no GUI.

**Comment by andrewdavidwong** [comment]
Ok, great! We already have a separate issue for the GUI, #1872, so I'll close this one.
