### ISSUE TITLE
 strange network speed problem

### ISSUE THREAD

**Issue by hansholt** [QubesOS/qubes-issues#2017]
#### Qubes OS version:

R3.1

#### Affected TemplateVMs:

`fedora-23`

### Expected behavior:

full network download speed 2mbit

### Actual behavior:

only get half or less from time to time unless i reconnect my wired connection with the networkmanager app. after successful reconnect i got the full speed. this affects only internet speed not the local network speed.

### Steps to reproduce the behavior:

i have no idea how.

### General notes:

it's a wired connection between the router and my qubes pc. i install qubes with gui and let qubes create the sys-net and sys-firewall. i don't change anything and only use fedora-23 with domains. all domains go through sys-firewall.
But if i want to view/edit firewall rules in sys-firewall this msg popup 

"The 'sys-firewall' AppVM is not network connected to a FirewallVM! You may edit the 'sys-firewall' VM Firewall rules, but these will not take any effect until you connect it to a working Firewall VM." 

Thats little strange. The fendora-23 template is of course up2date

**Comment by andrewdavidwong** [comment]
> But if i want to view/edit firewall rules in sys-firewall this msg popup
> 
> "The 'sys-firewall' AppVM is not network connected to a FirewallVM! You may edit the 'sys-firewall' VM Firewall rules, but these will not take any effect until you connect it to a working Firewall VM." 

This is normal. `sys-firewall` is itself a FirewallVM, and it is not connected to another FirewallVM, so it's meaningless to assign firewall rules in its Qubes Manager settings.

In general, this question is too localized for `qubes-issues`. Please consider posting this to the `qubes-users` mailing list instead. (You can read more about our mailing lists [here](https://www.qubes-os.org/mailing-lists/).)

`qubes-users` is intended for these sorts of questions and receives much more traffic, which means that your question is more likely to receive a response there.
