### ISSUE TITLE
USBVMs based on fedora-23-minimal do not properly pass block devices

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#2018]
#### Qubes OS version (e.g., `R3.1`):

R3.1
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):

`fedora-23-minimal`

---
### Steps to reproduce the behavior:
1. Create USBVM based on `fedora-23-minimal`.
2. Create `testvm` based on `fedora-23`.
3. Physically plug in USB drive.
4. Use Qubes Manager to attach it to `testvm`.
5. `qvm-block -l` claims it's attached to `testvm` as `xvdi`.
6. Check `testvm`. There is no `/dev/xvdi`.
### General notes:

Changing the USBVM from `fedora-23-minimal` to `fedora-23` avoids the problem.

Thread: https://groups.google.com/d/msgid/qubes-users/5743431F.2060607%40vfemail.net

**Comment by 3n7r0p1** [comment]
Is it proper form to cross-post with qubes-users? or is one preferred over the other?

Marek Marczykowski-Górecki:
>
> Check for other xvd* device (for example xvdj). Also you may try `xl
> block-list`, especially look at "state" column - should be "4". Normal
> AppVM has 4 disks, so 5th should be your usb stick.
>
>
>

`xl block-list` shows it as state "3"! No sign of it using fdisk (no abnormal xvd*'s)

```
#Before attaching...
[user@dom0 ~]$ xl block-list appVM 
Vdev  BE  handle state evt-ch ring-ref BE-path                       
51712 0   7      4     17     8        /local/domain/0/backend/vbd/7/51712
51728 0   7      4     18     9        /local/domain/0/backend/vbd/7/51728
51744 0   7      4     19     10       /local/domain/0/backend/vbd/7/51744
51760 0   7      4     20     11       /local/domain/0/backend/vbd/7/51760

# After attaching...
[user@dom0 ~]$ xl block-list appVM
Vdev  BE  handle state evt-ch ring-ref BE-path                       
51712 0   7      4     17     8        /local/domain/0/backend/vbd/7/51712
51728 0   7      4     18     9        /local/domain/0/backend/vbd/7/51728
51744 0   7      4     19     10       /local/domain/0/backend/vbd/7/51744
51760 0   7      4     20     11       /local/domain/0/backend/vbd/7/51760
51840 3   7      3     25     868      /local/domain/3/backend/vbd/7/51840
```

**Comment by andrewdavidwong** [comment]
> Is it proper form to cross-post with qubes-users? or is one preferred over the other?

I think it's fine in this case. It depends on the situation.

**Comment by 3n7r0p1** [comment]
`XenbusStateInitialised  = 3,  /* Initialised and waiting for a connection from the peer. */`

So I've been trying to troubleshoot this issue rather blindly... by comparing fedora-23 template to fedora-23-minimal template:

1. checked qvm-prefs & *.conf files
2. `lsmod` shows the same modules running on both systems
3. Kernel configs (from /proc/config.gz) have identical checksums.
4. `dnf list installed *guess*` in both systems to see which packages are missing. Installing missing packages in the minimal template and rebooting have not resolved. "guess" includes, xen, qubes, qvm, bus, virt, virsh, usb, blk, block, qxl, qemu, whatever else I could think of... `qubes-template-minimal-stub.spec` complicates this but don't see any obvious candidates in there that might resolve this.

Can anyone point me in some kind of direction? Thanks!

**Comment by marmarek** [comment]
Take a look at `/var/log/xen/xen-hotplug.log` - maybe there you'll find something helpful.

**Comment by 3n7r0p1** [comment]
Thank you!

SOLVED! fedora-23-minimal template requires `perl` to be installed in order to function as a usbVM.

sigh... could live another lifetime with all the hours wasted from not knowing where to look :)

**Comment by andrewdavidwong** [comment]
@marmarek, do you want to include `perl` in `fedora-*-minimal` templates by default, or instead note in the documentation that the user must install `perl` in order to use a `fedora-*-minimal`-based VM as a USB VM?

**Comment by marmarek** [comment]
If possible, I'd like to not depend on `perl` for USBVM. But if not, add a documentation about this requirement. It looks like the only `perl` usage there is in [locking mechanism](https://github.com/xen-project/xen/blob/staging/tools/hotplug/Linux/locking.sh#L48-L59).
I think the whole locking in this script isn't really needed in USBVM (but it is in dom0, and it is the same script). Will think of something...

**Comment by ptitdoc** [comment]
I will also take a look at it in order to add it as a (optional?) dependency in archlinux.

**Comment by unman** [comment]
@andrewdavidwong  Fedora 23 is eol, and the issue doesn't arise with Fedora24-minimal on r3.2, so I believe this can now be closed.
