### ISSUE TITLE
Create qubes.AppendLog service

### ISSUE THREAD

**Issue by rootkovska** [QubesOS/qubes-issues#2023]
Very useful to e.g. gather build logs in a reliable way, i.e. even if the build VM gets compromised during the build process (e.g due to curl|bash in a Makefile), the log can still be meaningful. Also for many other uses. Related to #830.

**Comment by andrewdavidwong** [comment]
[HW42 has generously submitted a patch for this](https://groups.google.com/d/msgid/qubes-devel/491be700-6772-5db6-4b7f-1571df969e9f%40ipsumj.de) based on the proposal in the post [Security challenges for the Qubes build process](https://www.qubes-os.org/news/2016/05/30/build-security/).

**Comment by marmarek** [comment]
@HW42 implementation is already integrated and enabled: #1818 , https://github.com/QubesOS/build-logs
