### ISSUE TITLE
Qubes tools not working on Windows when joining Active Directory

### ISSUE THREAD

**Issue by perkooo** [QubesOS/qubes-issues#2025]
#### Affected HVMs : Windows

Hi,

I had some problems using Qubes Tools when I joined my Active Directory.

I did the following steps to install Qubes Tools : 
- Installing Windows 7 ISO on HVM (Standalone)
- Joining Active Directory (working at this point)
- Installing Qubes Tools (with UAC activated, or I cannot press CTRL ALT DEL on startup).

Then after reboot, Windows is running in seamless mode (but seamless gui is disabled) and I can't start any shortcuts, I have the message : qrexec is not running.
I also have an error when I start the VM : 
- coercing to Unicode: need string or buffer, int found

If i start in debug mode, I have this in dom0 terminal : 
![error_starting_windows7](https://cloud.githubusercontent.com/assets/17830838/15509075/7387435e-21d2-11e6-89da-16f94a65c87f.png)

Qubes Tools works perfectly if I don't join Active Directory (I also tried to install Qubes Tools before joining Active Directory, it does not work).

**Comment by andrewdavidwong** [comment]
> Installing Qubes Tools (with UAC activated, or I cannot press CTRL ALT DEL on startup).

With Windows Tools installed, you should be able to press `ctrl + alt + home` instead of `ctrl + alt + del`.

**Comment by perkooo** [comment]
This is not the main problem here ("_ctrl + alt + home_" already referenced in issue #1585 )

I found another thing that might interest you, there is a problem when I start a sysprep when Windows Tools are installed : HVM won't start anymore when I reboot it. I have to start sysprep first then install Windows Tools to work.

**Comment by andrewdavidwong** [comment]
> This is not the main problem here ("ctrl + alt + home" already referenced in issue #1585 )

I know, but it's the only part that I can help with, and I figured it would be better to provide *some* help than *no* help.

**Comment by perkooo** [comment]
Yes thanks :)

**Comment by ikea90** [comment]
Hey there!
I have the same problem.
Is there already a solution existing?

**Comment by MegaTraveller** [comment]
Hi, how do you guys get it working to pass the login screen, what ever I do I get no response pressing the right keystrokes :(

**Comment by reg0l** [comment]
One of the solution is to use accessibility keyboard on the landing windows screen. That's ugly workaround but he did work for me .
