### ISSUE TITLE
Table of Content links are unintuitive

### ISSUE THREAD

**Issue by kulinacs** [QubesOS/qubes-issues#2029]
When using the Table of Contents to browse the Documentation, clicking a link results in jumping to a link like [https://www.qubes-os.org/doc/split-gpg/#tocAnchor-1-1-3](https://www.qubes-os.org/doc/split-gpg/#tocAnchor-1-1-3) instead of something intuitive like [https://www.qubes-os.org/doc/split-gpg/#thunderbird](https://www.qubes-os.org/doc/split-gpg/#thunderbird)

**Comment by andrewdavidwong** [comment]
Duplicate of #1713.
