### ISSUE TITLE
Multiboot does not work

### ISSUE THREAD

**Issue by NantaNakamoto** [QubesOS/qubes-issues#2030]
https://www.qubes-os.org/doc/multiboot/
`sudo grub2-mkconfig -o /boot/grub2/grub.cfg`

_So what we see:_
`command not found`

**Comment by andrewdavidwong** [comment]
You issued this command in dom0, correct?

**Comment by marmarek** [comment]
All this is needed only in case of legacy boot. In case of UEFI, multiboot is supported at UEFI firmware level naively. @NantaNakamoto which mode do you use?

**Comment by NantaNakamoto** [comment]
I do not want to always use the key to enter the menu.

**Comment by NantaNakamoto** [comment]
I just opened konsole from the "Strart" button and entered this command. And it not work.

**Comment by unman** [comment]
@NantaNakamoto 

Did you open konsole from dom0?
> So what we see:
> command not found

That isnt what you saw: post the full error message. It will tell you (and us)  what command was not found.

**Comment by andrewdavidwong** [comment]
Closing this since @NantaNakamoto isn't being responsive to questions.
