### ISSUE TITLE
Qubes Manager renders poorly at forced DPI of 144

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#2033]
> On qubes 3.0, If force font dpi (in `system settings->application appearance->fonts`) is set to 144, then parts of text in window "create new vm" disappears. Still usable, but looks ugly.

https://groups.google.com/d/msgid/qubes-users/3a6b1008-9291-4f5c-b4f5-9b808ea4496e%40googlegroups.com

This may be taken care of by #1870.

**Comment by andrewdavidwong** [comment]
[Screenshot](https://13366229192823780453.googlegroups.com/attach/3bb6183edbb90a/create-new-vm.png?part=0.1&view=1&vt=ANaJVrGqaR564i8IejSPnbdYVkeC-6o67ycKswuqt55eYkHWbMrt0xzMIDXvIwbAcxkSKLuaIEPCCG1mfEsch116ZrMfNHG0v3sHJE4BV7eYysVTZbKMpp4)

**Comment by marmarek** [comment]
Related (duplicate?): #2095

**Comment by andrewdavidwong** [comment]
Closing as (retroactive) duplicate of #2095.
