### ISSUE TITLE
Dom0 time not updated from ClockVM

### ISSUE THREAD

**Issue by JasperWeiss** [QubesOS/qubes-issues#2036]
#### Qubes OS version: 

R3.1

#### Affected TemplateVMs: 

N/A

---

### Expected behavior: 

Time displayed in Dom0 should match that of the ClockVM  (And thus regularly check the ClockVM for the correct time settings)

### Actual behavior: 

Dom0 displays UTC time only, doesn't seem to copy the correct time settings from ClockVM

### Steps to reproduce the behavior: 

Fresh install, Sony Vaio

### General notes:

I tried switching the ClockVM to sys-firewall hoping it would trigger a sync with the ClockVM. Changing the time settings inside the ClockVM doesn't do anything either.

**Comment by andrewdavidwong** [comment]
> Dom0 displays UTC time only, doesn't seem to copy the correct time settings from ClockVM

1. You should be able to change your time zone settings in dom0. If you're using KDE, try right-clicking the clock widget, then clicking "Adjust Date and Time...". Leave "Set date and time automatically" unchecked, then, in the second "Time Zone" tab, choose your desired time zone.

2. It's not clear from your description whether this is *only* a time zone issue or whether the time is wrong *in addition* to being an undesired time zone. If it's *only* a time zone issue, point 1 above should be sufficient.

   If the time is *also* incorrect, check `/var/log/cron` in dom0 to make sure `qvm-sync-clock` is running. Also check the actual script in `/etc/cron.d/qubes-sync-clock.cron`.

**Comment by JasperWeiss** [comment]
Hmm, I figured it out. 
the time is correct, it's just that the clock widget was set to UTC.
It can be solved easily by right clicking the time widget, digital clock settings, time zone and then change 'clock defaults to' to the desired time zone. 
I still think it's a bug though. The clockVM is supposed to figure out the time zone automatically for Dom0.

**Comment by andrewdavidwong** [comment]
> I still think it's a bug though. The clockVM is supposed to figure out the time zone automatically for Dom0.

That setting is set by the user during the installation.
