### ISSUE TITLE
Anaconda crashes: No such file or directory "/dev/md"

### ISSUE THREAD

**Issue by neoCrimeLabs** [QubesOS/qubes-issues#2037]
#### Anaconda (fresh install)

---

### Expected behavior:

Expected to install Qubes onto a system with a pre-existing MD-RAID10 raid-array.

### Actual behavior:

Anaconda crashes at language selection screen.

Root cause in debugging messages is *No such file or directory: '/dev/md'*

![img_20160528_120806](https://cloud.githubusercontent.com/assets/2514632/15629485/b46655a0-24ce-11e6-9551-1e5f40ef4ba1.jpg)

### Steps to reproduce the behavior:

Boot Qubes install media on a system with a preexisting software raid using linux MD which is configured to be autodetected.

### General notes:

It appears this would be easily fixed by simply creating the directory /dev/dm on the install media

I've installed Qubes on several other machines without pre-existing raid array without issues.

Dropped to shell (TTY-2) and confirmed via dmesg that the kernel was autodetecting my raid array properly, so this is expected functionality.

---

### Other troubleshooting for workaround:

Tried booting with various kernel options to disable raid autodetection without success (at time of this writing):

* raid=noautodetect
* nodmraid
* noraid
* sd${X}=noprobe (for each drive)

Due to how my machine is physically placed, it's somewhat inconvenient for me to unplug the drives, and bios won't let me disable individual drives without disabling the entire controller (which has the disk I want to install on)  :-p

Any advice for workaround is welcome.  :-)

Thanks for creating Qubes!

**Comment by andrewdavidwong** [comment]
Can you check whether this problem also exists on baremetal Fedora (20+)?

**Comment by neoCrimeLabs** [comment]
That's a good question.  Downloading F23 now.

**Comment by neoCrimeLabs** [comment]
Fedora 23 successfully installed to /dev/sdb.  Anaconda provided no error messages.

**Comment by andrewdavidwong** [comment]
Ok, thanks for checking that.

**Comment by neoCrimeLabs** [comment]
After gaining physical access to the machine and disconnecting the drives in the array, I successfully install Qubes R3.1.  Once installed reconnecting the array worked fine, so it appears the issue was limited to the installer.

**Comment by marmarek** [comment]
Take a look at test images in https://github.com/QubesOS/qubes-issues/issues/1807#issuecomment-220207374 - this is based on Fedora 23. Just boot the installer and see if the error is sill present there.

**Comment by marmarek** [comment]
Since it works on Fedora 23, I assume it will also work in Qubes 3.2, where installer is from Fedora 23.
