### ISSUE TITLE
Xen 4.6.1 breaks PCI attachment

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#2038]
HW42 ([thread](https://groups.google.com/d/topic/qubes-users/PQQt9SGbJwc/discussion)):
> with Xen `4.6.1-15.fc20` (which got recently uploaded to the testing repo) 
VMs with attached PCI devices don't boot anymore (at least on my 
machine). 
> 
> When I try to boot a VM with attached PCI devices it crashes 
immediately. Attached the xen `dmesg` log of a crash. 
> 
> Both dom0 and the VM are running the `4.1.24-9.pvops.qubes kernel`. 

`xen-4.6.1-vm-crash.log`:
```
(XEN) d6v0: unhandled page fault (ec=0000)
(XEN) Pagetable walk from ffff880040211ff0:
(XEN)  L4[0x110] = 000000004020f067 0000000000001c0f
(XEN)  L3[0x001] = 0000000000000000 ffffffffffffffff
(XEN) domain_crash_sync called from entry.S: fault at ffff82d080228283 create_bounce_frame+0x12b/0x13a
(XEN) Domain 6 (vcpu#0) crashed on cpu#3:
(XEN) ----[ Xen-4.6.1  x86_64  debug=n  Not tainted ]----
(XEN) CPU:    3
(XEN) RIP:    e033:[<ffffffff81068dcc>]
(XEN) RFLAGS: 0000000000000296   EM: 1   CONTEXT: pv guest (d6v0)
(XEN) rax: 0000000000000ff0   rbx: ffff880040211ff0   rcx: ffffffff827df000
(XEN) rdx: 00000000402eb063   rsi: ffffffff81df8000   rdi: ffff880040211ff0
(XEN) rbp: ffffffff81c03cb8   rsp: ffffffff81c03c40   r8:  4000000000001cea
(XEN) r9:  4000000000000000   r10: 0000000000007ff0   r11: 0000000000100000
(XEN) r12: 00000000402eb063   r13: ffffffff81df8000   r14: 00000000000402eb
(XEN) r15: 0000000000018100   cr0: 0000000080050033   cr4: 00000000000426e0
(XEN) cr3: 000000004020e000   cr2: ffff880040211ff0
(XEN) ds: 0000   es: 0000   fs: 0000   gs: 0000   ss: e02b   cs: e033
(XEN) Guest stack trace from rsp=ffffffff81c03c40:
(XEN)    ffffffff827df000 0000000000100000 0000000000000000 ffffffff81068dcc
(XEN)    000000010000e030 0000000000010096 ffffffff81c03c88 000000000000e02b
(XEN)    ffffffff81c03c90 ffffffff8100aa39 ffffffff81df8000 00000000402eb063
(XEN)    0000000000001ceb 00000000000402eb 0000000000018100 ffffffff81c03cd8
(XEN)    ffffffff81069316 ffffffff81df8000 00000000402eb063 ffffffff81c03cf8
(XEN)    ffffffff810693a3 00000000000001fd 0000000000100deb ffffffff81c03d08
(XEN)    ffffffff8100a729 ffffffff81c03e28 ffffffff81d506ee 0000000000000010
(XEN)    00000000000ff100 000001fd00000000 00000000000403f8 0000000000019000
(XEN)    00000000000ff100 000000000000000f ffffffff0000000f 0000000000100000
(XEN)    0000000118100000 ffffffff81df6b2c 0000000000000000 0000000000000f00
(XEN)    0000000000017315 0000000000100000 0000000019000000 0000000007ce7000
(XEN)    0000000000000000 0000000000000000 0000000000019000 0000000000000000
(XEN)    0000000000000010 ffffffff81df6a00 ffffffff810f7ff0 ffffffff81c03e38
(XEN)    ffffffff8175d297 0000000000000008 89636f149a6abc67 ffffffff81c03e08
(XEN)    0000000002047000 ffffffff81df3900 0000000001000000 0000000000000000
(XEN)    0000000000000000 ffffffff81c03e48 ffffffff81d56ca7 0000000fffffffff
(XEN)    0000000002047000 ffffffff81c03ed8 ffffffff81d54473 0000000000000000
(XEN)    0000000000000000 ffffffff81c03e78 ffffffff81c03ef8 ffffffff81c03ed8
(XEN)    ffffffff8175d297 0000000000000010 ffffffff81c03ee8 ffffffff81c03ea8
(XEN)    89636f149a6abc67 ffffffff81f0defe ffffffffffffffff ffffffff81df3900
```

HW42 ([post](https://groups.google.com/d/msg/qubes-users/PQQt9SGbJwc/I3qR6Mj5PQAJ)):

> This is not really related [to #1659]. My problem is PV related (didn't tested 
HVM). And most notably this is a direct regression of the update to `xen 
4.6.1-15.fc20`. `xen 4.6.0-13.fc20` works fine.

**Comment by andrewdavidwong** [comment]
Closing this since the discussion is taking place in the original thread.

**Comment by marmarek** [comment]
Reopening for tracking purposes

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `xen-4.6.1-16.fc21` has been pushed to the `r3.1` testing repository for the Fedora `fc21` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.1-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-vmm-xen/compare/c1f91549346b5b85dea688b9e095dd52457fa20c...fddc0f139332c11f0f157b4ccd0323fc8a5451b2

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `xen-4.6.1-16.fc22` has been pushed to the `r3.1` testing repository for the Fedora `fc22` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.1-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-vmm-xen/compare/c1f91549346b5b85dea688b9e095dd52457fa20c...fddc0f139332c11f0f157b4ccd0323fc8a5451b2

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `xen-4.6.1-16.fc23` has been pushed to the `r3.1` testing repository for the Fedora `fc23` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.1-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-vmm-xen/compare/c1f91549346b5b85dea688b9e095dd52457fa20c...fddc0f139332c11f0f157b4ccd0323fc8a5451b2

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `xen-4.6.1-16.fc20` has been pushed to the `r3.1` testing repository for dom0.
To test this update, please install it with the following command:
```
sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-vmm-xen/compare/c1f91549346b5b85dea688b9e095dd52457fa20c...fddc0f139332c11f0f157b4ccd0323fc8a5451b2

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `xen_4.6.1-17+deb8u1` has been pushed to the `r3.1` testing repository for the Debian `jessie` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `jessie-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-vmm-xen/compare/2d284fc593110a18843574ac0c61d52cfa2a4ce9...a95d5db154ca4bec8c8e6fe392fdd027afb984cc

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `xen_4.6.1-17+deb9u1` has been pushed to the `r3.1` testing repository for the Debian `stretch` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `stretch-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-vmm-xen/compare/2d284fc593110a18843574ac0c61d52cfa2a4ce9...a95d5db154ca4bec8c8e6fe392fdd027afb984cc

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `xen_4.6.1-17+deb7u1` has been pushed to the `r3.1` testing repository for the Debian `wheezy` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `wheezy-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-vmm-xen/compare/2d284fc593110a18843574ac0c61d52cfa2a4ce9...a95d5db154ca4bec8c8e6fe392fdd027afb984cc

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `xen-4.6.1-20.fc20` has been pushed to the `r3.1` stable repository for dom0.
To install this update, please use the standard update command:
```
sudo qubes-dom0-update
```
Or update dom0 via Qubes Manager.

[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-vmm-xen/compare/2d284fc593110a18843574ac0c61d52cfa2a4ce9...7644813eaa6a77d1106dcda932edbda93c042cce

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `xen-4.6.1-20.fc21` has been pushed to the `r3.1` stable repository for the Fedora `fc21` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-vmm-xen/compare/2d284fc593110a18843574ac0c61d52cfa2a4ce9...7644813eaa6a77d1106dcda932edbda93c042cce

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `xen-4.6.1-20.fc22` has been pushed to the `r3.1` stable repository for the Fedora `fc22` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-vmm-xen/compare/2d284fc593110a18843574ac0c61d52cfa2a4ce9...7644813eaa6a77d1106dcda932edbda93c042cce

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `xen-4.6.1-20.fc23` has been pushed to the `r3.1` stable repository for the Fedora `fc23` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-vmm-xen/compare/2d284fc593110a18843574ac0c61d52cfa2a4ce9...7644813eaa6a77d1106dcda932edbda93c042cce

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `xen_2001:4.6.1-20+deb8u1` has been pushed to the `r3.1` stable repository for the Debian `jessie` template.
To install this update, please use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-vmm-xen/compare/2d284fc593110a18843574ac0c61d52cfa2a4ce9...7644813eaa6a77d1106dcda932edbda93c042cce

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `xen_2001:4.6.1-20+deb9u1` has been pushed to the `r3.1` stable repository for the Debian `stretch` template.
To install this update, please use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-vmm-xen/compare/2d284fc593110a18843574ac0c61d52cfa2a4ce9...7644813eaa6a77d1106dcda932edbda93c042cce

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `xen_2001:4.6.1-17+deb7u1` has been pushed to the `r3.1` stable repository for the Debian `wheezy` template.
To install this update, please use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-vmm-xen/compare/2d284fc593110a18843574ac0c61d52cfa2a4ce9...7644813eaa6a77d1106dcda932edbda93c042cce
