### ISSUE TITLE
qubes-manager: UnicodeEncodeError if there are cyrillic letters in "Run command in VM" query.

### ISSUE THREAD

**Issue by rashchedrin** [QubesOS/qubes-issues#2040]
#### Qubes OS version:
R3.0
#### Affected: Qubes VM Manager 

If in Qubes Manager use item "Run command in VM"  then enter anything with Cyrillic letters and hit enter, appears message that says "Whoops. A critical error has occured...".

---

### Expected behavior:

Send command to VM with Cyrillic letters, or warn with something not as scary as critical error.

### Actual behavior:

Appears message with text

>Whoops. A critical error has occured. 
>This is most likely a bug in Qubes Manager.

>**UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)**
>at line **1418**
>of file main.py

### Steps to reproduce the behavior:

Right click on any vm in Qubes Manager, click "run command in VM", type привет , hit enter.

**Comment by andrewdavidwong** [comment]
Should be taken into account in #1870.

**Comment by andrewdavidwong** [comment]
Another user report:

[On 2016-10-01 12:13, ( - wrote:](https://groups.google.com/d/msgid/qubes-devel/57820970-c420-412c-9482-21c44fb08284%40googlegroups.com)
> Hello !
> 
> When using "Run command in VM" I found this little bug with unicode chars.
> 
```
> UnicodeEncodeError: 'ascii' codec can't encode characters in position 
> 27-30: ordinal not in range(128)
> 
> This is most likely a bug in the Qubes Manager
```
> 
> ----
```
> line: vm, str(command_to_run), thread_monitor))
> func: action_run_command_in_vm_triggered
> line no.: 1407
> file: /usr/lib64/python2.7/site-packages/qubesmanager/main.py
> 
> So I try to make a one-line patch and test it with non-ascii string.
> 
> xterm -hold -e 'echo "test-тест"'
> 
> I guess this behavior exist in ver. 3.2 too.
> 
> See attached diff and screenshots.
> 
> -            vm, str(command_to_run), thread_monitor))
> +            vm, unicode(command_to_run), thread_monitor))
> 
```

**Comment by igilik** [comment]
--- /usr/lib64/python2.7/site-packages/qubesmanager/main.py.orig        2016-09-29 23:18:15.732999994 +0600
+++ /usr/lib64/python2.7/site-packages/qubesmanager/main.py     2016-10-01 21:06:54.464999973 +0600
@@ -1404,7 +1404,7 @@
             return
         thread_monitor = ThreadMonitor()
         thread = threading.Thread(target=self.do_run_command_in_vm, args=(
-            vm, str(command_to_run), thread_monitor))
+            vm, unicode(command_to_run), thread_monitor))
         thread.daemon = True
         thread.start()

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-manager-3.2.4-1.fc23` has been pushed to the `r3.2` testing repository for dom0.
To test this update, please install it with the following command:
```
sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-manager/compare/98cada9f07ec870b02e5f72cc3ae2e105c45a715...a6c25b7604cc52aae42b6cb60648822fa0f6e7bb

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-manager-3.2.4-1.fc23` has been pushed to the `r3.2` stable repository for dom0.
To install this update, please use the standard update command:
```
sudo qubes-dom0-update
```
Or update dom0 via Qubes Manager.

[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-manager/compare/98cada9f07ec870b02e5f72cc3ae2e105c45a715...a6c25b7604cc52aae42b6cb60648822fa0f6e7bb
