### ISSUE TITLE
Split GPG + Thunderbird + Enigmail produces empty attachments

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#2041]
Conditions:
* Split GPG (`qubes-gpg-split`) 2.0.19
* Thunderbird 45.1.0 (probably also other versions)
* Enigmail 1.8.2 (probably also other versions)
* Inline PGP
* One or more attachments

Results:
* If signing only, a 0 byte detached `.sig` file is attached to the message along with the original attachment. (This should be a proper PGP detached signature file.)
* If signing and encrypting, the attachment is converted into a 0 byte `.pgp` file. (This should be a proper PGP encrypted message.)
* In both cases, there is no warning or error message.
* In both cases, the message body is still properly signed/encrypted.

**Comment by andrewdavidwong** [comment]
A workaround is to manually sign/encrypt all attachments from the command-line, attach them, then tell Enigmail not to sign/encrypt any of the attachments.

**Comment by marmarek** [comment]
Cannot reproduce:
 - when selected PGP/MIME, attachment is properly encrypted without any message, 
 - when selected inline PGP, TB asks what to do, with default to "Encrypt and sign each attachment separately and send the message using inline PGP"; after confirming, attachment is properly signed and encrypted

Tested on:
 - Fedora 23 VM
 - Thunderbird 45.1.1, 
 - Enigmail 1.9.4
 - Split GPG 2.0.21

Maybe it was fixed as a side effect from other change? I'd guess adding support for `--output` option.
@andrewdavidwong can you confirm/deny?

**Comment by andrewdavidwong** [comment]
Indeed, it looks like it's been fixed as a byproduct of something else. :+1:
