### ISSUE TITLE
Tray icon in KDE5 doesn't have colorful border

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#2042]
In KDE5, tray icon (especially NetworkManger Applet) doesn't have colorful border. It looks like KDE is trying to blend the icon into panel.
It is critical to have a way to distinguish icons from VMs.

**Comment by marmarek** [comment]
Screenshot:
![nm-applet-no-border](https://cloud.githubusercontent.com/assets/726704/15656267/be82aad8-26a5-11e6-8bf2-4a310b4763b0.png)

**Comment by marmarek** [comment]
One idea is to abandon borders and color the whole icon, similar to icons used in the menu. Algorithm used for this coloring requires converting RGB to HSL, which [seems to be not an easy task in C](https://en.wikipedia.org/wiki/HSL_color_space), but much easier in python (as it's done with app icons). And it looks to be quite easy to [call python function from C](https://www.daniweb.com/programming/software-development/threads/31682/calling-python-function-from-cc-).

**Comment by marmarek** [comment]
After hours of debugging with @woju finally got it working :) IMHO looks nice, much better than unnoticeable border:
![colorful-nm](https://cloud.githubusercontent.com/assets/726704/15837192/82d1c472-2c38-11e6-8ace-1563641b01c8.png) ![colorful-nm-connecting](https://cloud.githubusercontent.com/assets/726704/15837200/883ee8fe-2c38-11e6-8710-6d9b44b75f45.png)

Transparency is introduced by KDE - this is probably the same mechanism that stripped the border...
Should we enable it by default for every WM? Or only KDE? @rootkovska

**Comment by rootkovska** [comment]
Can you disable it for KDE and paste here a screenshot?

**Comment by marmarek** [comment]
Take a look above - there is nm-applet icon from sys-net (yes, should have red border, but it's stripped by KDE).

**Comment by rootkovska** [comment]
No, I would like to see the icon with a white bg.

**Comment by marmarek** [comment]
There is no white bg in KDE5 - it strips it out. Yes, what is actually visible in the tray in KDE5 is something preprocessed by KDE, not directly mapped VM icon.

**Comment by marmarek** [comment]
And I can't see any configuration to disable this feature. Actually there is even no configuration for icon size (which is really annoying on HiDPI...)

**Comment by rootkovska** [comment]
What if our magic HSL-based color converter also converted any of the white pixels into... sightly less white pixels, say RGB(254,254,254)?

**Comment by rootkovska** [comment]
Currently it looks pretty ugly IMHO...

**Comment by marmarek** [comment]
RGB(254, 254, 254) trick worked: 
![colorful-nm-white-bg](https://cloud.githubusercontent.com/assets/726704/15838510/a8daf0ca-2c3e-11e6-83a6-6df262838f91.png)

**Comment by rootkovska** [comment]
... and if we also add back the frame in the VM color? :)

**Comment by rootkovska** [comment]
Also adding @bnvk to get his opinion.

**Comment by marmarek** [comment]
KDE strips the border, even if I made it thicker (2px).

**Comment by rootkovska** [comment]
I see... Ok, let's try this:
1. Revert back to the transparent bg,
2. Tone down the Saturation (the S in HSL) at least by 50% (S /=2)
?

**Comment by marmarek** [comment]
But when I made the frame separated 1px from actual border, it worked:
![colorful-nm-white-bg-border](https://cloud.githubusercontent.com/assets/726704/15838779/3217779a-2c40-11e6-847d-9abf21121fa4.png)
Now we've lost 2px from each side - one removed by KDE, the other one overwritten by our border.

**Comment by rootkovska** [comment]
Looks better though :)

**Comment by marmarek** [comment]
Transparent BG, reduced saturation: 
![colorful-nm-reduced-stauration1](https://cloud.githubusercontent.com/assets/726704/15839028/637be7d4-2c41-11e6-9e7a-a91cea042c05.png)

**Comment by rootkovska** [comment]
Not bad either :) IMHO

**Comment by rootkovska** [comment]
And can you paste the screen with the nm-appet in a "connecting" state -- that looked worst on the screens above...

**Comment by marmarek** [comment]
No idea why, but when I've restarted nm-applet, KDE cut off another pixel or two from each side of the icon... Maybe something about icon size - now icon window (somewhere hidden by KDE) is 16x16, but embedded in 32x32 KDE container. After restarting gui daemon, icon is back at the right size (32x32), but is not updating anymore... Anyway probably unrelated to the whole coloring stuff.
Here is a screenshot you've requested:
![colorful-nm-connecting-reduced-stauration1](https://cloud.githubusercontent.com/assets/726704/15839296/e00db5e2-2c42-11e6-8600-1a6dabfef4e3.png)
And the one in disconnected state (the red one is in problematic state of 16x16 size):
![colorful-nm-reduced-stauration2](https://cloud.githubusercontent.com/assets/726704/15839315/0401139a-2c43-11e6-9b09-d676a2aecffd.png)

**Comment by rootkovska** [comment]
I'm inclined towards the reduced-sat-on-transparent-bg version. Can you show how other icons would look this way? E.g. Electrum?

**Comment by marmarek** [comment]
Electrum in blue VM: 
![colorful-electrum-blue](https://cloud.githubusercontent.com/assets/726704/15839728/4c36635c-2c45-11e6-9d1c-8a3dac6036f5.png)
And red: 
![colorful-electrum-red](https://cloud.githubusercontent.com/assets/726704/15839739/55422c4c-2c45-11e6-8d9a-4fc0e1fd4c0c.png)

And the same with restored original saturation (and also added keepassx):
![colorful-electrum-keepassx](https://cloud.githubusercontent.com/assets/726704/15839837/244181a0-2c46-11e6-9f92-4dfeaca55638.png)
Still - I see Electrum being indistinguishable.

**Comment by rootkovska** [comment]
Not so good :/
And the version with "white-1" bg and frame around?

**Comment by marmarek** [comment]
![colorful-electrum-keepassx-white frame](https://cloud.githubusercontent.com/assets/726704/15840016/44f7dc86-2c47-11e6-9062-406266ecdfcf.png)
Would you like reduced saturation too? IMHO this makes some icons harder to distinguish.

**Comment by marmarek** [comment]
Cutting 2px from each side is especially visible on keepassx.

**Comment by rootkovska** [comment]
palmface

@bnvk, help?

**Comment by marmarek** [comment]
I've already introduced configuration parameter for this. We can make it all configurable and decide on the final version later.

There is still an option for bordered but not colored icon (useful for other WMs).

**Comment by timcollinsal1** [comment]
Might be just dumb newbie uestion here (ill be that idiot guy who cant read documentation) - Using 3.2 test iso, after launch I have no border or tray or anything outside of top left hidden icon for network config. Im sure theres a command to open the GUI, but what might that be? Im running everything through terminal now ( I know the version Im using is test/pre=release) just curious how I might activate to ease user expereince visually and for thos of us not as familiar with console.

**Comment by zander** [comment]
For what its worth;
the icon size *is* configurable and it is an "enum" to avoid HiDPI displays showing a 16 pixels icon.

The default is 16-pixels, scaled (looks just fine on a 230DPI screen I own, def not actually 16px).

You can change the default in a package quite trivially by patching (in dom0);
 `/usr/share/plasma/plasmoids/org.kde.plasma.private.systemtray/contents/config/main.xml`
under `iconSize` change the default to 2, for instance.


About the border, the simplest solution is to work with the KDE team, or at least the sources.  KDEs plasma is mostly implemented using javascript (in qml style) which means you have the sources in dom0. Many useful things can be done without recompiling.

For instance the actual icon behaviour etc is defined in;
 `/usr/share/plasma/plasmoids/org.kde.plasma.private.systemtray/contents/ui/items/StatusNotifierItem.qml`

Either way, I'd be interested in reopening the investigation towards a coloured outline as the current solution of colourising is not my favourite, I got the impression you guys didn't prefer that either ;)

**Comment by zander** [comment]
Interesting observation;

Adding a border to my applications icon, and showing it in my kde5 desktop had the following effect;

a) when running the app in dom0. This shows the border just fine.

b) When running in an appVM, this shows the colored image, without border.

I conclude that KDE does not remove any border added by Qubes, I don't know the full pipeline from appVM to kde-systemtray, would it be possible that the issue lies in one of the other components?

**Comment by marmarek** [comment]
Icon handling is configured in `/etc/qubes/guid.conf`. Default is to color it, instead of adding border. Available options are in `man qubes-guid`, for reference:

```
   Available trayicon modes:
       bg:    color full icon background to the VM color

       border1:
              add 1px border at the icon edges

       border2:
              add 1px border 1px from the icon edges

       tint : tint icon to the VM color,

              can be used with additional modifiers (you can enable multiple of them)

       tint+border1,tint+border2:
              same as tint, but also add a border

       tint+saturation50:
              same as tint, but reduce icon saturation by 50%

       tint+whitehack:
              same as tint, but change white pixels (0xffffff) to almost-white (0xfefefe)

```

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.

**Comment by ninavizz** [comment]
@marmarek I love that clipboard icon, in the screenshot towards the top. Why was it moved-away from?

**Comment by marmarek** [comment]
It was completely different thing - a built-in KDE widget (we use Xfce now) managing I think local clipboard only (in case of qubes: dom0, which doesn't really have any content).
