### ISSUE TITLE
3.1 default kernel, missing amdgpu module

### ISSUE THREAD

**Issue by falcon15500** [QubesOS/qubes-issues#2043]
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):
Dom0

---

### Expected behavior:
Expect my recent AMD GPU to be detected and used.
### Actual behavior:
Defaults to low resolution (1024x768).
### Steps to reproduce the behavior:
Install on system with newer AMD GPU (in my case R9 380 (TONGA Pro)).
### General notes:
No amdgpu kernel module could be found with the default kernel.  I updated to a newer kernel from unstable repo and the amdgpu kernel module is included.  Everything worked fine after that.  GPU was detected and I got higher res and independent displays.

---

**Comment by marmarek** [comment]
`amdgpu` is available starting with kernel 4.2, R3.1 uses 4.1 by default.
R3.2 will have 4.4 kernel by default.
