### ISSUE TITLE
Boot-able USB not seen

### ISSUE THREAD

**Issue by benzmuircroft** [QubesOS/qubes-issues#2050]
#### Qubes OS version: 

latest stable 3.1

### Expected behavior:

the boot-able usb should show qubes.os as an option in grub after f12 is pressed

### Actual behavior:

no option to try qubes.os (nothing seen in grub)

### Steps to reproduce the behavior:

root@box:/media/benz# dd if=/home/benz/Desktop/Qubes-R3.1-x86_64.iso of=/dev/sdb1
9736192+0 records in
9736192+0 records out
4984930304 bytes (5,0 GB) copied, 166,389 s, 30,0 MB/s

then start computer with f12 pressed

grub menu comes up but no option of usb with qubes is to be seen

### General notes:

tried formatting the usb as NFST, Fat32 and ext4 using Gparted on xubuntu

Grub does not see the usb on:

 - iMac currently running xubuntu
 - Samsung Notebook RV520 currently running xubuntu
 - iMac running OSX

**Comment by andrewdavidwong** [comment]
Instead of this:

    dd if=/home/benz/Desktop/Qubes-R3.1-x86_64.iso of=/dev/sdb1

Please try this:

    dd if=/home/benz/Desktop/Qubes-R3.1-x86_64.iso of=/dev/sdb

(In other words, write to the entire device, not just a partition on that device.)

**Comment by benzmuircroft** [comment]
It has not made a difference unfortunately, grub does not see qubes.

**Comment by marmarek** [comment]
What do you mean by **grub** does not see Qubes? Do you see Grub from
installation media?

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by benzmuircroft** [comment]
![20160607_163755](https://cloud.githubusercontent.com/assets/4244518/15862060/5a166b76-2cc6-11e6-9068-a95637d09e9d.jpg)

What do you mean by installation media?

**Comment by marmarek** [comment]
Ok, I see. Grub menu of *Ubuntu* will not list Qubes OS, it isn't meant to. You need to boot from USB drive, not your disk. For this check BIOS settings, you can also probably select one time USB boot through BIOS boot menu (in most cases by pressing F12 at startup).
Anyway, qubes-issues isn't a place for this type of support, please move to [qubes-users mailing list](https://www.qubes-os.org/mailing-lists/).
