### ISSUE TITLE
Renaming VMs doesn't change qubes-manager entry

### ISSUE THREAD

**Issue by ghost** [QubesOS/qubes-issues#2054]
#### Qubes OS version (e.g., `R3.1`):

R3.1
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):

All

---
### Expected behavior:

Renaming an VM modify and moves all relevant files, and no problems with finding relevant files.
### Actual behavior:

The files and directory change (`/var/lib/qubes/appvms`) but the entry in the Qubes manager doesn't. This make it impossible to start the VM, both from the application launcher and via command-line.

When I'm trying to start an application in the qube from the application launcher results in the icons just jumping (indicating loading) and then dissaprears. Nothing else happens.

Starting the qube from the command-line (`qvm-start [vm]`) results in the output `A VM with the name '[VM-name]' does not exist in the system`.
### Steps to reproduce the behavior:

NOTE: I can't reliable reproduce this bug, but is has occurred several times for me.
1. Rename VM.
### General notes:

It has occurred for both standalone VMs and appVMs. This happens on a seemly random basis.

---

**Comment by andrewdavidwong** [comment]
> Starting the qube from the command-line (qvm-start [vm]) results in the output A VM with the name 'untrusted-2' does not exist in the system.

Sounds like it's not just a Qubes Manager issue, but rather than `qubes.xml` isn't getting updated.

**Comment by marmarek** [comment]
Did you get any error while renaming the VM? Have you tried renaming using `qvm-prefs`?

**Comment by dumbl3d0re** [comment]
Marek Marczykowski-Górecki:
> 
> Did you get any error while renaming the VM? Have you tried renaming using `qvm-prefs`?
> 
> ---
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/QubesOS/qubes-issues/issues/2054#issuecomment-224754516
> 

No, I didn't get any errors when renaming the VM. I used the manager for
renaming, and haven't tested with `qvm-prefs`. Reporting back soon.

**Comment by dumbl3d0re** [comment]
Marek Marczykowski-Górecki:
> Have you tried renaming using `qvm-prefs`?

I've now tested renaming a StandaloneVM with `qvm-prefs`. No problems,
but at the same time no problems occurred using Qubes manager. It's just
sometimes that this problem occur. The files from the VM with problems
still exist, something from there (logs, etc.) that can help you? Can't
start the VM, but I assume that it's possible to access the files
another way, or possible to manually add the VM?

**Comment by pstansell** [comment]
Hello,

I just wanted to say that I had a similar problem with R3.1.  I
recently installed Quabes and during the course of exploring it's
behaviour I renamed a template VM using the VM Manager.  It didn't
report any errors, but the name displayed by the VM Manager was not
updated.

Now both

  qvm-prefs old-vm-name

and 

  qvm-prefs new-vm-name

report that the VM "does not exist in the system", but I still to
still have 3.5G of files in /var/lib/qubes/vm-templates/new-vm-name.

After this I can no longer start the VM from the Manager or from the
command line.  In the Manager I deleted the VM (which still had the
old name).  That worked in that the name has gone from the Manager,
but the files are still present on my system (under the new name).

Is there any way I can edit a config file by hand so that the VM Manager
can see the VM in /var/lib/qubes/vm-templates/new-vm-name?

Thanks

**Comment by andrewdavidwong** [comment]
@pstansell, check `/var/lib/qubes/qubes.xml` for the old and new VM names, but be very careful if editing this file.

**Comment by pstansell** [comment]
Thanks for the advice.  I managed to break my installation other ways too (eg. "qvm-trim-template fedora-23" stopped working with error "File exists: /var/lib/gubes/appvms/fedora-23-fstrim"), so I reinstalled the whole system and started again.  It's all part of the learning experience!

**Comment by xloem** [comment]
Just to confirm, I had this issue, and editing `/var/lib/qubes/qubes.xml` worked for me.  I changed the name three times: the path, the conf file, and the name itself.  Then the vm launched fine.

**Comment by tntdynamight** [comment]
Same here on Qubes R3.1. xloem's workaround worked for me nicely, thanks!

**Comment by jpouellet** [comment]
It looks like this ABA problem may be addressed generally in core3 as result of https://github.com/QubesOS/qubes-core-admin/commit/0141e1ac73fb8bb66d70564c101c20af9330d962

**Comment by marmarek** [comment]
@jpouellet I don't think this is the problem - API in 3.x explicitly allow this already, and it is used by [Qubes Manager](https://github.com/QubesOS/qubes-manager/blob/master/qubesmanager/settings.py#L142-L164).

**Comment by jpouellet** [comment]
Another report: https://groups.google.com/d/topic/qubes-users/8lk9v7awLnY/discussion

**Comment by marmarta** [comment]
3.1 is no longer supported, and I can't seem to reproduce it on 3.2; I think this one is safe to close.
