### ISSUE TITLE
MSI issue

### ISSUE THREAD

**Issue by msisucks** [QubesOS/qubes-issues#2058]
Qubes R3.1

"ACPI : EC: Fail in evaluating the _REG object of EC device. Broken bios is suspected."

after that error message will still keep going but then freezes at starting qubes installer. I have tried both legacy and UEFI mode, disable secure boot, fast boot, but still nothing. This is not just a qubes issue I cant install any linux distro due to the same error so not sure if you guys can help me or point me some where for support on this issue.

#### Related issues:

https://bugzilla.kernel.org/show_bug.cgi?id=112261
https://bugzilla.kernel.org/show_bug.cgi?id=109081

**Comment by andrewdavidwong** [comment]
This is not appropriate for `qubes-issues`. Please send this to the `qubes-users` [mailing list](https://www.qubes-os.org/mailing-lists/) instead.
