### ISSUE TITLE
Don't require scp installed in the VM to be manageable through salt

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#2059]
Currently when managing VM through `qubesctl` (so, wrapped `salt-ssh`), it checks for `scp` binary presence in the target VM. In our case it doesn't make sense, since our wrapper uses `qubes.Filecopy` qrexec service instead - so `scp` isn't required at all.

This check is hardcoded in salt thin minion wrapper, so probably not easy to disable. But maybe it is possible to somehow simulate `scp` binary presence, for example by adding additional directory to  `PATH` with a dummy `scp` file.

Related code files:
https://github.com/QubesOS/qubes-mgmt-salt/blob/master/qubes.SaltLinuxVM
https://github.com/QubesOS/qubes-mgmt-salt/blob/master/ssh-wrapper

**Comment by marmarek** [comment]
Related check in salt shim is here:
https://github.com/saltstack/salt/blob/develop/salt/client/ssh/ssh_py_shim.py#L142-L144

**Comment by marmarek** [comment]
@woju take a look at linked patch here. Do you think the hack is too ugly (and instead require scp being installed in every template, even minimal), or is it acceptable?

**Comment by woju** [comment]
Another alternative would be to prepare proper package with this dummy binary. If you think it would be worth it (and to include it conditionally in the template builder), I would go this way. But if not, I would definitely use this hack as the only another option is to require all the template developers to include `scp` binary for no apparent reason.

And:
- put some explanation in comment (copy-paste this issue?)
- put quotes around `$PATH`.

**Comment by marmarek** [comment]
> (and to include it conditionally in the template builder)

How to do that?

And generally I'd like to modify target template as little as possible. Currently (besides this issue), it is enough to have just qrexec + qubes.VMShell service there. Thanks to `salt-ssh` nothing else is needed to manage any template.

**Comment by woju** [comment]
>> (and to include it conditionally in the template builder)
>How to do that?
I dunno, you know how templates are built.

Anyway, if you don't want to modify templates, that's fine. Just comment that hack and be done. 

Maybe let know the salt people we had to hack around their tool, but since we are repurposing it in some creative ways, I don't think they'll care.

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-mgmt-salt_3.2.2-1+deb8u1` has been pushed to the `r3.2` testing repository for the Debian `jessie` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `jessie-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-mgmt-salt/compare/28bf6d4f0a32a59ac0d83ae6e3d7b298a2dc03d9...6af87b9619b09bc7368a50c0d7c4613fe6ddf972

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-mgmt-salt_3.2.2-1+deb9u1` has been pushed to the `r3.2` testing repository for the Debian `stretch` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `stretch-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-mgmt-salt/compare/28bf6d4f0a32a59ac0d83ae6e3d7b298a2dc03d9...6af87b9619b09bc7368a50c0d7c4613fe6ddf972

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-mgmt-salt_3.2.2-1+deb7u1` has been pushed to the `r3.2` testing repository for the Debian `wheezy` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `wheezy-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-mgmt-salt/compare/28bf6d4f0a32a59ac0d83ae6e3d7b298a2dc03d9...6af87b9619b09bc7368a50c0d7c4613fe6ddf972

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-mgmt-salt-3.2.2-1.fc23` has been pushed to the `r3.2` testing repository for the Fedora `fc23` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.2-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-mgmt-salt/compare/28bf6d4f0a32a59ac0d83ae6e3d7b298a2dc03d9...6af87b9619b09bc7368a50c0d7c4613fe6ddf972

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-mgmt-salt-3.2.2-1.fc24` has been pushed to the `r3.2` testing repository for the Fedora `fc24` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.2-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-mgmt-salt/compare/28bf6d4f0a32a59ac0d83ae6e3d7b298a2dc03d9...6af87b9619b09bc7368a50c0d7c4613fe6ddf972

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-mgmt-salt-3.2.2-1.fc23` has been pushed to the `r3.2` testing repository for dom0.
To test this update, please install it with the following command:
```
sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-mgmt-salt/compare/28bf6d4f0a32a59ac0d83ae6e3d7b298a2dc03d9...6af87b9619b09bc7368a50c0d7c4613fe6ddf972

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-mgmt-salt-3.2.3-1.fc23` has been pushed to the `r3.2` stable repository for the Fedora `fc23` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-mgmt-salt/compare/28bf6d4f0a32a59ac0d83ae6e3d7b298a2dc03d9...efa87307a5fd0e0f67f6d81255a7963c01013753

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-mgmt-salt-3.2.3-1.fc24` has been pushed to the `r3.2` stable repository for the Fedora `fc24` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-mgmt-salt/compare/28bf6d4f0a32a59ac0d83ae6e3d7b298a2dc03d9...efa87307a5fd0e0f67f6d81255a7963c01013753

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-mgmt-salt-3.2.3-1.fc23` has been pushed to the `r3.2` stable repository for dom0.
To install this update, please use the standard update command:
```
sudo qubes-dom0-update
```
Or update dom0 via Qubes Manager.

[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-mgmt-salt/compare/28bf6d4f0a32a59ac0d83ae6e3d7b298a2dc03d9...efa87307a5fd0e0f67f6d81255a7963c01013753

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-mgmt-salt_3.2.4-1+deb8u1` has been pushed to the `r3.2` stable repository for the Debian `jessie` template.
To install this update, please use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-mgmt-salt/compare/28bf6d4f0a32a59ac0d83ae6e3d7b298a2dc03d9...9bf856ce74a24262c2a7323a8b31549b928a486f
