### ISSUE TITLE
option to set the TemplateVM setting for TemplateBasedVMs to none

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#2062]
Setting the template to an arbitrary different temporary template during template reinstallation is a bit dangerous. Easily forgotten. Lets say oneyou would not want boot some my-whonix-ws AppVM in a debian-8 template.

This makes [template reinstallation instructions](https://www.qubes-os.org/doc/whonix/reinstall/) more difficult than possible.

Feature request:
Please have an option for `qvm-prefs` as well as in QVMM to allow setting the template to `none`.

Related mailing list discussion:
[Is there a standard procedure to reinstall whonix?](https://groups.google.com/forum/#!topic/qubes-users/JAurx9KJnqk)

Since this touches usability, I am looping in @bnvk.

**Comment by marmarek** [comment]
Having template set to "none" means it is Standalone VM (with own `root.img` etc). So not that simple. But maybe we should [ship `dummy` template](https://groups.google.com/d/msgid/qubes-users/20160610221433.GM1593%40mail-itl)?

**Comment by andrewdavidwong** [comment]
> This makes [template reinstallation instructions](https://www.qubes-os.org/doc/whonix/reinstall/) more difficult than possible.

I started to rewrite that page to generalize it so that the procedure could be used for any TemplateVM (not just Whonix). However, I stopped when the discussion turned toward creating special tools for the job (rather than having the user manually create the dummy template). [Here](https://gist.github.com/andrewdavidwong/e00fc21a61b58f53656ac04b5c1c46cb) is the latest draft. If you think it's worth finishing and adding to the docs, let me know. If not (e.g., because we don't want users trying to do that, or it's going to be deprecated soon by this option), then that's ok.

**Comment by adrelanos** [comment]
I think it's worth being documented because until the improved solution
gets available, users updated, old versions are deprecated and so forth
will probably still take quite some time.

**Comment by andrewdavidwong** [comment]
> I think it's worth being documented because until the improved solution gets available, users updated, old versions are deprecated and so forth will probably still take quite some time.

Done: https://github.com/QubesOS/qubes-doc/commit/652409c5818b42eba802ab73210523403adc8239

**Comment by marmarek** [comment]
In Qubes 4.0, it's simple to create "dummy" template for this purpose:
```
qvm-create --class TemplateVM --label red dummy
```

**Comment by marmarta** [comment]
What GUI part did you mean here, @marmarek ? You can create an "empty"/dummy templateVM easily with current 4.0/4.1 Create Qubes VM tool.

**Comment by andrewdavidwong** [comment]
>"empty"/dummy template

I don't even see this mentioned in the [documentation](https://www.qubes-os.org/doc/how-to-reinstall-a-template/) anymore. Is it only used internally and no longer user-facing or something?

**Comment by marmarta** [comment]
This is just a template with no contents, I think. I think this can be safely closed because 1. can be done easily with gui now 2. we have tools now to easily create/remove/switch templates (`qvm-template` and associated GUI).

**Comment by andrewdavidwong** [comment]
> This is just a template with no contents, I think. I think this can be safely closed because 1. can be done easily with gui now 2. we have tools now to easily create/remove/switch templates (`qvm-template` and associated GUI).

Regarding this issue's labels and milestone: These reasons for closing the issue sound like this is a "won't do" (as in, we no longer need the thing originally requested). But they could also mean that this was already implemented before and that the milestone was never updated and the issue was left open.

**Comment by marmarta** [comment]
Oh, I get it! I think I expressed myself badly; you don't need to make a dummy template anymore (qvm-template does what it needs to do by itself), and if you wanted for some strange reason, you can do it using GUI. So both parts of this issue are actually done.

**Comment by andrewdavidwong** [comment]
> Oh, I get it! I think I expressed myself badly; you don't need to make a dummy template anymore (qvm-template does what it needs to do by itself), and if you wanted for some strange reason, you can do it using GUI. So both parts of this issue are actually done.

Ok, sounds good. Based on https://github.com/QubesOS/qubes-issues/issues/2062#issuecomment-915627363, it sounds like this was actually done in "4.0 updates," so I'll change the milestone to that.
