### ISSUE TITLE
Better way of packaging templates than RPM

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#2063]
Follow up from #2061:

> We need some better way of shipping templates... Or a consistent workflow how to handle RPM templates.

Problems with templates as RPM packages:
- can't be renamed #839
- poor RPM handling of large files #1326 
- can be accidentally updated (overriding user changes / updates) #996 #1647 
- but sometimes it is desirable to update/reinstall them #2061 
- complete backup restore is tricky because of above #1385 
- rpm-managed vs non-rpm-managed templates difference is confusing #1403 

/cc @adrelanos

**Comment by ttasket** [comment]
Templates are very compressible, so perhaps the rpms could be cached in a special folder and re/installed as needed. That would allow the user to delete any deployed template at will and could solve #1403 #1385 (most of) #2061 and probably the rest.

Another option could be to keep snapshots of the initial deployed templates, if the filesystem supports it. Actually.... Supporting per-vm snapshots would solve a lot of problems.

**Comment by marmarek** [comment]
Fedora-23 template RPM is about 1.2GB. While much smaller than installed template, still not nothing...

**Comment by iamahuman** [comment]
Related: #5948, #5509

**Comment by DemiMarie** [comment]
Done.
