### ISSUE TITLE
qubes-template-manager (QTM) cli tool

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#2064]
Quote @marmarek https://github.com/QubesOS/qubes-issues/issues/2061#issuecomment-225429732:

> Generally this is just another problem with packaging templates as RPMs. Package manager want to have newest available version, but updating template at template package level will rollback all the changes / updates installed already there. This is why templates are excluded.
> But as you've pointed out, there are cases when it would be useful to update/reinstall template package.
> We need some better way of shipping templates... Or a consistent workflow how to handle RPM templates.

I think there is no reason to use something other than RPM (or APT, if dom0 will be one day Debian based). The template update exclusion mechanism is fine, just needs fine tuning for some rough edges. I very much recommend inventing a new package manager, that is a project in it self, a super comprehensive, difficult task. (Look into TUF.)

A qubes-template-manager (QTM) cli tool could do.

`qubes-dom0-update template reinstallation option` (https://github.com/QubesOS/qubes-issues/issues/2061) is part of the solution, should implement a `--no-exclude` option for `qubes-dom0-update`. QTM would use that.

qtm features:
- `qtm install qubes-template-whonix-gw` -> `qubes-dom0-update qubes-template-whonix-gw`
- `qtm reinstall qubes-template-whonix-gw` -> `qubes-dom0-update --no-exclude qubes-template-whonix-gw`
- `qtm purge qubes-template-whonix-gw` -> iterate through all TemplateBasedVMs based on qubes-template-whonix-gw, `qvm-kill` and `qvm-remove` them, -> `yum remove qubes-template-whonix-gw`
- `qtm remove qubes-template-whonix-gw` -> iterate through all TemplateBasedVMs based on qubes-template-whonix-gw, set them to template `none` (#2062) -> `yum remove qubes-template-whonix-gw`

**Comment by marmarek** [comment]
Take a look at #2063 - there are more problems with RPM templates (like inability to rename).
But such a tool looks like a good idea, for now can use `qubes-dom0-update`, and later switch to new mechanism when invented.

`qtm purge` requires very careful handling, triple user confirmation etc. Otherwise can really easily lead to data loss.

**Comment by marmarta** [comment]
Fixed by https://github.com/QubesOS/qubes-core-admin-client/commit/9d9ee6a4b7fac1a6175bae44a27f4681f679bfa6 and future commits.
