### ISSUE TITLE
Installer in UEFI mode does not replace XEN.EFI with current version when previous a one exists.

### ISSUE THREAD

**Issue by MMihelic** [QubesOS/qubes-issues#2068]
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):

---
### Expected behavior:

I have installed a preview build over the existing UEFI installation on a disk with multiple OSes. I've deleted existing Qubes partitions but have left EFI partition untouched.
The installer has completed and installed the new xen.efi version onto the EFI partition, however, it has just copied the versioned file ("xen-4.6.1.efi") to the qubes folder without replacing also the existing "xen.efi" file.
### General notes:

One can argue that such behavior is logical as the installer could otherwise destroy/overwrite a loader of an existing and still working installation but, at the same time, it also rewrites the existing xen.cfg file and efi boot entry in expectation that the new install will be the default OS.

As a side note: When the installer rewrote the xen.cfg,  "new" mapbs and noexitboot settings, that existed on my system, were lost. This might also become an issue in future versions of the Qubes but, not for the R3.2.

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `xen-4.6.3-23.fc23` has been pushed to the `r3.2` testing repository for dom0.
To test this update, please install it with the following command:
```
sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-vmm-xen/compare/1eff534c5ae50ac9a45a554204f9197dee15621f...fea6a921bd7cdef0a947bf5d2c1c8a2277ef0bdd

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `xen-4.6.3-24.fc23` has been pushed to the `r3.2` testing repository for dom0.
To test this update, please install it with the following command:
```
sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-vmm-xen/compare/fea6a921bd7cdef0a947bf5d2c1c8a2277ef0bdd...32b1442ab291db9b952cd737cf0ad402db56cd3d

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `xen-4.6.3-24.fc21` has been pushed to the `r3.1` testing repository for the Fedora `fc21` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.1-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-vmm-xen/compare/1eff534c5ae50ac9a45a554204f9197dee15621f...32b1442ab291db9b952cd737cf0ad402db56cd3d

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `xen-4.6.3-24.fc22` has been pushed to the `r3.1` testing repository for the Fedora `fc22` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.1-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-vmm-xen/compare/1eff534c5ae50ac9a45a554204f9197dee15621f...32b1442ab291db9b952cd737cf0ad402db56cd3d

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `xen-4.6.3-24.fc23` has been pushed to the `r3.1` testing repository for the Fedora `fc23` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.1-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-vmm-xen/compare/1eff534c5ae50ac9a45a554204f9197dee15621f...32b1442ab291db9b952cd737cf0ad402db56cd3d

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `xen-4.6.3-24.fc24` has been pushed to the `r3.1` testing repository for the Fedora `fc24` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.1-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-vmm-xen/compare/1eff534c5ae50ac9a45a554204f9197dee15621f...32b1442ab291db9b952cd737cf0ad402db56cd3d

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `xen-4.6.3-24.fc20` has been pushed to the `r3.1` testing repository for dom0.
To test this update, please install it with the following command:
```
sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-vmm-xen/compare/1eff534c5ae50ac9a45a554204f9197dee15621f...32b1442ab291db9b952cd737cf0ad402db56cd3d

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `xen-4.6.3-24.fc23` has been pushed to the `r3.2` testing repository for the Fedora `fc23` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.2-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-vmm-xen/compare/1eff534c5ae50ac9a45a554204f9197dee15621f...32b1442ab291db9b952cd737cf0ad402db56cd3d

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `xen-4.6.3-24.fc24` has been pushed to the `r3.2` testing repository for the Fedora `fc24` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.2-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-vmm-xen/compare/1eff534c5ae50ac9a45a554204f9197dee15621f...32b1442ab291db9b952cd737cf0ad402db56cd3d

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `xen_4.6.3-24+deb8u1` has been pushed to the `r3.2` testing repository for the Debian `jessie` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `jessie-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-vmm-xen/compare/7644813eaa6a77d1106dcda932edbda93c042cce...32b1442ab291db9b952cd737cf0ad402db56cd3d

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `xen_4.6.3-24+deb9u1` has been pushed to the `r3.2` testing repository for the Debian `stretch` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `stretch-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-vmm-xen/compare/7644813eaa6a77d1106dcda932edbda93c042cce...32b1442ab291db9b952cd737cf0ad402db56cd3d

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `xen-4.6.3-24.fc23` has been pushed to the `r3.2` stable repository for dom0.
To install this update, please use the standard update command:
```
sudo qubes-dom0-update
```
Or update dom0 via Qubes Manager.

[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-vmm-xen/compare/f1de224b45a937083c460f25359b414119cd151d...32b1442ab291db9b952cd737cf0ad402db56cd3d

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `xen-4.6.3-24.fc20` has been pushed to the `r3.1` stable repository for dom0.
To install this update, please use the standard update command:
```
sudo qubes-dom0-update
```
Or update dom0 via Qubes Manager.

[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-vmm-xen/compare/7644813eaa6a77d1106dcda932edbda93c042cce...32b1442ab291db9b952cd737cf0ad402db56cd3d

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `xen-4.6.3-24.fc21` has been pushed to the `r3.1` stable repository for the Fedora `fc21` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-vmm-xen/compare/7644813eaa6a77d1106dcda932edbda93c042cce...32b1442ab291db9b952cd737cf0ad402db56cd3d

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `xen_2001:4.6.3-24+deb8u1` has been pushed to the `r3.2` stable repository for the Debian `jessie` template.
To install this update, please use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-vmm-xen/compare/7644813eaa6a77d1106dcda932edbda93c042cce...32b1442ab291db9b952cd737cf0ad402db56cd3d

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `xen-4.6.3-24.fc22` has been pushed to the `r3.1` stable repository for the Fedora `fc22` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-vmm-xen/compare/7644813eaa6a77d1106dcda932edbda93c042cce...32b1442ab291db9b952cd737cf0ad402db56cd3d

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `xen-4.6.3-24.fc23` has been pushed to the `r3.1` stable repository for the Fedora `fc23` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-vmm-xen/compare/7644813eaa6a77d1106dcda932edbda93c042cce...32b1442ab291db9b952cd737cf0ad402db56cd3d

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `xen-4.6.3-24.fc23` has been pushed to the `r3.2` stable repository for the Fedora `fc23` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-vmm-xen/compare/f1de224b45a937083c460f25359b414119cd151d...32b1442ab291db9b952cd737cf0ad402db56cd3d

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `xen-4.6.3-24.fc24` has been pushed to the `r3.2` stable repository for the Fedora `fc24` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-vmm-xen/compare/f1de224b45a937083c460f25359b414119cd151d...32b1442ab291db9b952cd737cf0ad402db56cd3d

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `xen_4.6.3-24+deb8u1` has been pushed to the `r3.1` testing repository for the Debian `jessie` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `jessie-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-vmm-xen/compare/7644813eaa6a77d1106dcda932edbda93c042cce...32b1442ab291db9b952cd737cf0ad402db56cd3d

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `xen_4.6.3-24+deb9u1` has been pushed to the `r3.1` testing repository for the Debian `stretch` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `stretch-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-vmm-xen/compare/7644813eaa6a77d1106dcda932edbda93c042cce...32b1442ab291db9b952cd737cf0ad402db56cd3d

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `xen_4.6.3-24+deb7u1` has been pushed to the `r3.1` testing repository for the Debian `wheezy` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `wheezy-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-vmm-xen/compare/a95d5db154ca4bec8c8e6fe392fdd027afb984cc...32b1442ab291db9b952cd737cf0ad402db56cd3d
