### ISSUE TITLE
Missing dependencies for Thunderbird Qubes Attachments?

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#2071]
#### Qubes OS version (e.g., `R3.1`):

R3.1
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):

fedora-23-minimal

---

My email VMs are based on a modified clone of `fedora-23-minimal` with Thunderbird and a few other packages installed. Recently, I've noticed that certain Qubes Attachments functions, such as "send all [attachments] to VM" have stopped working in these VMs. (Clicking the button does nothing.) Basing the VM on `fedora-23` instead causes it to work, so I'm guessing that there's some kind of missing dependency.

**Comment by marmarek** [comment]
Start Thunderbird from xterm and check what error will you get there.

**Comment by andrewdavidwong** [comment]
Here's the traceback when clicking the "send all to VM" button:

```
Traceback (most recent call last):
  File "/usr/bin/qvm-mru-entry", line 24, in <module>
    import gtk
  File "/usr/lib64/python2.7/site-packages/gtk-2.0/gtk/__init__.py", line 40, in <module>
    from gtk import _gtk
ImportError: No module named cairo
```

**Comment by marmarek** [comment]
It looks like `pycairo` is excluded from minimal template (even though it is dependency of `pygtk2` which is installed). Try installing `pycairo` package and see how much data will it put into the minimal template. If not much, probably worth including.

**Comment by andrewdavidwong** [comment]
Not bad at all, and it fixes the issue:

```
bash-4.3# dnf install pycairo
Last metadata expiration check: 1:34:07 ago on Wed Jun 15 00:46:12 2016.
Dependencies resolved.
================================================================================
 Package          Arch            Version                 Repository       Size
================================================================================
Installing:
 pycairo          x86_64          1.10.0-2.fc23           fedora          515 k

Transaction Summary
================================================================================
Install  1 Package

Total download size: 515 k
Installed size: 1.0 M
Is this ok [y/N]:
```

**Comment by adrelanos** [comment]
Andrew David Wong:
> Here's the traceback when clicking the "send all to VM" button:
> 
> ```
> Traceback (most recent call last):
>   File "/usr/bin/qvm-mru-entry", line 24, in <module>
>     import gtk
>   File "/usr/lib64/python2.7/site-packages/gtk-2.0/gtk/__init__.py", line 40, in <module>
>     from gtk import _gtk
> ImportError: No module named cairo
> ```

Wild guess. Try this.

sudo apt-get install python-cairo

Or.

sudo apt-get install python-gtk2

**Comment by unman** [comment]
@marmarek Is there any reason why you haven't merged your commits to the Qubes repo? It seems odd this issue is still open, when the solution is there.

**Comment by marmarek** [comment]
`qubes-template-minimal-stub` is not included in any repository (and shouldn't be), so just merging this will affect only newly built templates. This is one more thing requiring #2572

**Comment by marmarek** [comment]
This isn't an issue in R3.2

**Comment by andrewdavidwong** [comment]
This is now resolved by installing `qubes-core-agent-nautilus`.
