### ISSUE TITLE
Port qubes core to Python 3

### ISSUE THREAD

**Issue by woju** [QubesOS/qubes-issues#2074]

**Comment by jpouellet** [comment]
Just curious... What is the specific motivation for this?

**Comment by woju** [comment]
On Mon, Nov 14, 2016 at 12:41:54AM -0800, Jean-Philippe Ouellet wrote:
> Just curious... What is the specific motivation for this?

Expected py2 deprecation in 2020, some new language features. Until 2020 this
is nice-to-have, low priority. In 2020 it will suddenly turn urgent. :)

-- 
pozdrawiam / best regards       _.-._
Wojtek Porczyk               .-^'   '^-.
Invisible Things Lab         |'-.-^-.-'|
                             |  |   |  |
 I do not fear computers,    |  '-.-'  |
 I fear lack of them.        '-._ :  ,-'
    -- Isaac Asimov             `^-^-_>
