### ISSUE TITLE
Fix transient build failures caused non-deterministic lorax dependency resolving

### ISSUE THREAD

**Issue by woju** [QubesOS/qubes-issues#2076]
For the branding reasons, lorax automatically pulls some `*-logos` package. What is in `*`, depends on the name of the package which provides `/etc/system-release`. Both `qubes-release` and `fedora-release` provide that file, so the first package is taken into account. The `fedora-logos` package is obsoleted and provided by `qubes-artwork`, so it cannot be installed. This causes dependency problems.

Because it takes the first package, this is non-deterministic and causes failure sometimes.

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `pykickstart-2.13-3.fc23` has been pushed to the `r3.2` testing repository for dom0.
To test this update, please install it with the following command:
```
sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-installer-qubes-os/compare/92571659940c314ffe2b3f1f7e17c4244bffb998...6be5ff7e559c9e683731078662761270d7fa53a0

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `pykickstart-2.13-3.fc23` has been pushed to the `r3.2` stable repository for dom0.
To install this update, please use the standard update command:
```
sudo qubes-dom0-update
```
Or update dom0 via Qubes Manager.

[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-installer-qubes-os/compare/92571659940c314ffe2b3f1f7e17c4244bffb998...d2988a86431beabea1a59760d5cae1f70b5d0b1b
