### ISSUE TITLE
Windows 7: Provide a way to disable seamless mode without having to change registry

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#2077]
> It appears that once the tools are installed one can't easily disable seamless mode without entering into the Windows 7 registry and performing the action.

Thread: https://groups.google.com/d/topic/qubes-users/wW0Y42g0HKM/discussion

**Comment by omeg** [comment]
Qubes Manager is used to toggle seamless mode for a Windows VM.
