### ISSUE TITLE
add mention of small NLNet Foundation grant

### ISSUE THREAD

**Issue by mfc** [QubesOS/qubes-issues#2080]
- [ ] add NLNet logo to home page: https://github.com/QubesOS/qubesos.github.io/blob/master/pages/home.html

- [x] add NLNet to funders page:
https://github.com/QubesOS/qubesos.github.io/blob/master/pages/funding.md

- [x] add NLNet to partners page:
https://github.com/QubesOS/qubesos.github.io/blob/master/pages/partners.md

- [x] write short blogpost - not going to do a blogpost for now

NLNet logo: https://nlnet.nl/image/logo.gif

**Comment by mfc** [comment]
@bnvk @andrewdavidwong can one of you put the NLnet logo (and other logos) on the partners and funders pages, and the NLnet logo the home page? I know I'll screw up the layouts....

**Comment by andrewdavidwong** [comment]
Done.

**Comment by mfc** [comment]
awesome, thanks so much!
