### ISSUE TITLE
Featured release on downloads page is easy to miss

### ISSUE THREAD

**Issue by mfc** [QubesOS/qubes-issues#2081]
With the release of 3.2rc1, R3.1 just disappeared from the Downloads webpage.

https://www.qubes-os.org/downloads/

**Comment by marmarek** [comment]
It is still there, at the top, the biggest entry...

**Comment by mfc** [comment]
my bad :/

**Comment by andrewdavidwong** [comment]
Since more than one member of the core Qubes team had the same reaction, I think that's a good sign that the design of the Downloads page can be improved.
