### ISSUE TITLE
HTTPS versions of yum.qubes-os.org and deb.qubes-os.org broken

### ISSUE THREAD

**Issue by rustybird** [QubesOS/qubes-issues#2082]
https://ftp.qubes-os.org works, but it looks like https://yum.qubes-os.org and https://deb.qubes-os.org point to the wrong directory.

It would be nice to have all of them work, for the last feature of https://github.com/QubesOS/qubes-issues/issues/1957#issuecomment-226991485 -- but if it's not possible, I could also add another more specific regex.

**Comment by marmarek** [comment]
Done.
cc @woju
