### ISSUE TITLE
No multimonitor support

### ISSUE THREAD

**Issue by ghost** [QubesOS/qubes-issues#2084]
#### Qubes OS version (e.g., `R3.1`):

R3.2
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):

N/A

---
### Expected behavior:

Under `Application Launcher/System Tools/System Settings/Display and Monitor` there should be options for multiple monitors.
### Actual behavior:

Just settings for the compositor is available.

**Comment by andrewdavidwong** [comment]
Discussion thread: https://groups.google.com/d/topic/qubes-users/2GNCpyZy2tk/discussion

Micah Lee wrote:
> It appears that there are some missing packages in dom0. I solved this 
by installing kscreen: 
> 
> `$ sudo qubes-dom0-update kscreen`
> 
> This made KDE recognize my external monitor, but I still couldn't find 
the configuration tool in System Settings. However I figured out that I 
could open it like this: 
> 
> `$ kcmshell5 kscreen`

**Comment by andrewdavidwong** [comment]
[Several users](https://groups.google.com/d/msgid/qubes-users/cade96c6-ea13-02c7-3fed-94d80b39f839%40qubes-os.org) have run into this problem.

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `pykickstart-2.13-3.fc23` has been pushed to the `r3.2` testing repository for dom0.
To test this update, please install it with the following command:
```
sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-installer-qubes-os/compare/92571659940c314ffe2b3f1f7e17c4244bffb998...6be5ff7e559c9e683731078662761270d7fa53a0

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `pykickstart-2.13-3.fc23` has been pushed to the `r3.2` stable repository for dom0.
To install this update, please use the standard update command:
```
sudo qubes-dom0-update
```
Or update dom0 via Qubes Manager.

[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-installer-qubes-os/compare/92571659940c314ffe2b3f1f7e17c4244bffb998...d2988a86431beabea1a59760d5cae1f70b5d0b1b

**Comment by TheBubblePopped** [comment]
It would be nice if it could recognize the settings in the end after the restart ( kscreen) or if the problem would be solved after 2 years

**Comment by andrewdavidwong** [comment]
@TheBubblePopped: It looks like this bug *was* resolved back in Jun-Jul 2016 (which is why it's been closed since then). I'm guessing that you're experiencing a regression, so I'm reopening this.

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
