### ISSUE TITLE
Passthrough for USB keyboards isn't enabled by default

### ISSUE THREAD

**Issue by dumbl3d0re** [QubesOS/qubes-issues#2088]
#### Qubes OS version (e.g., `R3.1`):
R3.2

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):
N/A

---

### Expected behavior:
When connecting a USB keyboard for the first time it should ask if you want to allow the keyboard to passthrough to the rest of the system.

### Actual behavior:
Nothing happens.

### Steps to reproduce the behavior:
1. Connect your USB keyboard.

### General notes:
The solution to the problem is to add `sys-usb dom0 ask` on the top of the file `/etc/qubes-rpc/policy/qubes.InputKeyboard`. Passthrough for USB mouses is already enabled using this method.

**Comment by marmarek** [comment]
This is design decision. Having control over the keyboard gives in practice control over the whole system, so it should be really consistent decision to allow `sys-usb` to control keyboard. Just one-click confirmation is too little barrier. More details: https://www.qubes-os.org/doc/usb/#tocAnchor-1-1-4
