### ISSUE TITLE
Resize Root Disk Image is a difficult process and has usability issues - root-image-resize cli tool - QVMM

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#2090]
#### Qubes OS version (e.g., `R3.1`):

R3.1
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):

any
### Steps to reproduce the behavior:

QVMM -> any TemplateVM -> settings -> increase system storage - ok
### Expected behavior:

When increasing the size in QVMM should just work out of the box.
### Actual behavior:

Cryptic contradictory error messages.

If the TemplateVM is not running...

```
ERROR: Basic tab:
VM start required to complete the operation, but not allowed. Either run the operation again allowing VM start this time, or run resize2fs in the VM manually.
```

If the TemplateVM is running...

```
ERROR: Basic tab:
Cannot resize root.img of running VM
```

Size of the TemplateVM will not be increased. One has to find the documentation https://www.qubes-os.org/doc/resize-root-disk-image/ and act according to it. The documentation is correct in principle but difficult to apply to lets someone trying to increase whonix-gw TemplateVM. (Lots of manual conversions have to be done in ones mind such as shutting down sys-whonix, setting whonix-gw NetVM to none so sys-whonix will not be automatically started.)
### General notes:
- The QVMM gui implies that increasing the root image size is a simple process while it is not.
  - If it is not possible to increase the root disk image while the TemplateVM is running and/or any TemplateBasedVMs based on that TemplateVM are running, then the field to increase the root disk image should be grayed out or so. Or perhaps offer some click-through / wizard to automate all of what is required.
  - shut down any TemplateBasedVM based on that TemplateVM
  - shut down the TemplateVM
  - set the NetVM of that TemplateVM to none
  - `truncate -s XXXG /var/lib/qubes/vm-templates/YYY/root.img`
  - boot that TemplateVM
    - `sudo resize2fs /dev/mapper/dmroot`
    - shutdown that TemplateVM
  - set the NetVM of that TemplateVM back to last setting
  - Maybe the resize root image process should be automated in a separate cli tool that gets called from QVMM.
- The documentation https://www.qubes-os.org/doc/resize-root-disk-image/ should primarily refer to how to increase the root image size using the gui, using QVMM. Command line instructions should be made secondary. Further down on that page on a separate documentation page.

**Comment by desmond-decker** [comment]
I can confirm that increasing the root disk size in the QVMM GUI not only causes weird error dialogs, but can also render a TemplateVM completely unusable. I think the suggestion to grey it out is a good one.

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
