### ISSUE TITLE
Can't rename AppVMs using Qubes manager

### ISSUE THREAD

**Issue by dumbl3d0re** [QubesOS/qubes-issues#2092]
#### Qubes OS version (e.g., `R3.1`):
R3.2

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):
All

---

### Expected behavior:
When renaming using the Qubes manager the AppVM should be renamed in the Qubes manager, application launcher and changed directory in `/var/lib/qubes/appvms`.

### Actual behavior:
When renaming a AppVM using the qubes manager it changes the directory in `/var/lib/qubes/appvms` and the changes propagates to the application launcher. The entry in the manager *doesn't* change. This make the AppVM unusable because I can no longer start the VM.

### Steps to reproduce the behavior:
1. Create a new AppVM. Which TemplateVM doesn't matter.
2. Rename the new AppVM using the Qubes manager.

### General notes:
Using the `qvm-prefs` CLI tool works without a problem.

---

#### Related issues:
#2054

**Comment by andrewdavidwong** [comment]
Why is this not a duplicate of #2054?

**Comment by dumbl3d0re** [comment]
It could be the same problem, but now it happens everytime and also effect AppVMs.

**Comment by marmarek** [comment]
Can't reproduce. Anything special about those names? Maybe the VM is running or something?

**Comment by dumbl3d0re** [comment]
It's the same issue as #2054, but with AppVMs.
