### ISSUE TITLE
Add more informative error message when user enters empty firewall rule service

### ISSUE THREAD

**Issue by dumbl3d0re** [QubesOS/qubes-issues#2093]
#### Qubes OS version (e.g., `R3.1`):
R3.2

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):
All

---

### Expected behavior:
When trying to set more specific settings for firewall rules for protocols (TCP, UDP) for AppVMs everything works and the new rules is added.

### Actual behavior:
When adding a new firewall rule it only works to add a rule with a domain name and to allow all traffic to that domain. If you try to set more specific rules for the protocols an error message with the text "Service ' is unknown" pops up.

### Steps to reproduce the behavior:
1. Try to add firewall rule with specific protocol specified in an AppVM via the "[f]irewall rules" tab in Qubes manager.

### General notes:
I haven't tested adding the rules using CLI.

---

**Comment by andrewdavidwong** [comment]
Which service did you try adding the "Service" box? Did this work for you in R3.1?

> I haven't tested adding the rules using CLI.

Since we're not sure whether this is just a Qubes Manager issue or a Core issue, I've tagged both.

**Comment by dumbl3d0re** [comment]
I've tested with both TCP and UDP, no port specific settings is needed to trigger the error. It worked without any problems in 3.1.

**Comment by marmarek** [comment]
When you select TCP or UDP you need to fill service field. The error message says empty service isn't valid. You can use port number, or even port range (for any port, simply use `1-65535`).
So this bug is rather about misleading error message.

**Comment by dumbl3d0re** [comment]
@marmarek Ok! I thought that it defaulted to `any' service if unspecified.
