### ISSUE TITLE
Installer fails to create partitions on Crucial CT250MX200SSD1

### ISSUE THREAD

**Issue by n1441** [QubesOS/qubes-issues#2099]
#### Qubes OS version (e.g., `R3.1`):
R3.1

After selecting automatic partitioning and beginning the installation an unrecoverable error occurres. 

It seems, that it's an anaconda related issue: the size of the volume is supplied to lvcreate as amount of space in megabytes, not as amount of actually available extents. By tuning sizes of volumes in semi-automatic mode I was able to deduce the right size for /root, but had no luck with /swap and after 10 or 12 reboots did resign.

### Actual behavior:
`Volume group "qubes_dom0" has insufficient free space (57516 extents): 57524 required.`

![foo](https://cloud.githubusercontent.com/assets/6661319/16212495/ba0ce552-3750-11e6-8333-213c0659ab19.jpg)
![bar](https://cloud.githubusercontent.com/assets/6661319/16212507/cbf71f94-3750-11e6-8937-460c93b21581.jpg)

**Comment by n1441** [comment]
Not reproducible with R3.2-RC1

**Comment by andrewdavidwong** [comment]
> Not reproducible with R3.2-RC1

Well, that's good news. Perhaps a byproduct of upgrading dom0 to Fedora 23?

**Comment by n1441** [comment]
> Perhaps a byproduct of upgrading dom0 to Fedora 23?
Most likely.

**Comment by andrewdavidwong** [comment]
@marmarek, since this is apparently fixed as a byproduct of upgrading dom0 to Fedora 23, should we close this?
