### ISSUE TITLE
qvm-prefs says 'no attribute' for some existing attributes

### ISSUE THREAD

**Issue by tasket** [QubesOS/qubes-issues#2102]
#### Qubes OS version (e.g., `R3.1`):

R3.1
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):

(dom0)

---
### Expected behavior:

$ `qvm-prefs vmname attribute` returns value
### Actual behavior:

$ `qvm-prefs vmname`

```
name               : fedora-23
label              : black
type               : TemplateVM
netvm              : sys-firewall
dispvm_netvm       : sys-firewall (default)
updateable         : True
autostart          : False
installed_by_rpm   : True
include_in_backups : False
last_backup        : None
dir                : /var/lib/qubes/vm-templates/fedora-23
config             : /var/lib/qubes/vm-templates/fedora-23/fedora-23.conf
pcidevs            : []
pci_strictreset    : True
root_img           : /var/lib/qubes/vm-templates/fedora-23/root.img
root_cow_img       : /var/lib/qubes/vm-templates/fedora-23/root-cow.img
root_volatile_img  : /var/lib/qubes/vm-templates/fedora-23/volatile.img
private_img        : /var/lib/qubes/vm-templates/fedora-23/private.img
vcpus              : 2
memory             : 150
maxmem             : 1500
MAC                : 00:16:3E:5E:6C:1F (auto)
kernel             : 4.1.13-9 (default)
kernelopts         : nopat (default)
debug              : off
default_user       : user
qrexec_timeout     : 60
internal           : False
```

yet...
$ `qvm-prefs fedora-23 MAC`
VM 'fedora-23' has no attribute 'MAC'
$ `qvm-prefs fedora-23 root_cow_img`
VM 'fedora-23' has no attribute 'root_cow_img'
$ `qvm-prefs fedora-23 root_volatile_img`
VM 'fedora-23' has no attribute 'root_volatile_img'
### Steps to reproduce the behavior:

Type above commands into dom0 CLI.
### General notes:

---

**Comment by unman** [comment]
This already referenced here for MAC: https://github.com/QubesOS/qubes-doc/pull/166

> Ah ok, it needs qvm-prefs -s mac blah.

`qvm-prefs <name> volatile_img` works for root_volatile_img

`root_cow_image `is just borked

PR on way
