### ISSUE TITLE
Need easy way to check if VM is running

### ISSUE THREAD

**Issue by ttasket** [QubesOS/qubes-issues#2103]
#### Qubes OS version (e.g., `R3.1`):
R3.1
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):
(dom0)

---

### Expected behavior:
Something like:
$ `qvm-check --isrunning vmname`
VM vmname is running
(returns 0)

### Actual behavior:
I guess `qvm-ls` can support this, but its cumbersome.

### General notes:
Maybe fold this into `qvm-check` as an option?

---

**Comment by marmarek** [comment]
Yes, good idea. Should be trivial (`vm.is_running()`). Do you care to send a pull request (qubes-core-admin repo)?

**Comment by ttasket** [comment]
Yes, I'll implement it.

**Comment by ttasket** [comment]
PR here https://github.com/QubesOS/qubes-core-admin/pull/32

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-dom0-3.2.4-1.fc23` has been pushed to the `r3.2` testing repository for dom0.
To test this update, please install it with the following command:
```
sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-admin/compare/7f86782e1470a8076bb6ab6684bb6e3907dbc7aa...376dc43b907afa41a9d94c02431a5bc7f14756dc

**Comment by marmarek** [comment]
@ttasket if you reference ticket from PR with full path (QubesOS/qubes-issues#ticket-no, or full ticket URL), it will be linked here automatically.

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-dom0-3.1.17-1.fc20` has been pushed to the `r3.1` testing repository for dom0.
To test this update, please install it with the following command:
```
sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-admin/compare/1e29d7fa396a1469541a6d64e48f398396f79780...d8093f38c428e4a9e7be421f2dc57e0a45a19477

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-dom0-3.1.17-1.fc20` has been pushed to the `r3.1` stable repository for dom0.
To install this update, please use the standard update command:
```
sudo qubes-dom0-update
```
Or update dom0 via Qubes Manager.

[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-admin/compare/1e29d7fa396a1469541a6d64e48f398396f79780...d8093f38c428e4a9e7be421f2dc57e0a45a19477

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-dom0-3.2.7-1.fc23` has been pushed to the `r3.2` stable repository for dom0.
To install this update, please use the standard update command:
```
sudo qubes-dom0-update
```
Or update dom0 via Qubes Manager.

[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-admin/compare/7f86782e1470a8076bb6ab6684bb6e3907dbc7aa...f0489a3d5cb5455eb6e658cfa2350b8a86c2442c
