### ISSUE TITLE
Uninstalling all RPM templates also uninstalls kernel-qubes-vm

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#2107]
#### Qubes OS version (e.g., `R3.1`):

`R3.2-rc1` (and possibly earlier)

#### Problem description:

When the user uninstalls all RPM templates in preparation to restore their own backed up templates, uninstalling the last RPM template also uninstalls `kernel-qubes-vm`. It is not clear whether this is required or what the user should do in this situation. We may need clearer communication about this.

> reinstalled `kernel-qubes-vm` that was automatically uninstalled when
> removing the last template RPM but I think it's needed
> [...]
> Removing all RPM templates removes an unrelated
> package that I think should be kept (`kernel-qubes-vm`).

[Full message](https://groups.google.com/d/msgid/qubes-users/5b7fd4a0-d7a1-e24f-e8ff-d3cd96b8db8d%40gmx.com)

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `pykickstart-2.13-3.fc23` has been pushed to the `r3.2` testing repository for dom0.
To test this update, please install it with the following command:
```
sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-installer-qubes-os/compare/6be5ff7e559c9e683731078662761270d7fa53a0...d2988a86431beabea1a59760d5cae1f70b5d0b1b

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `pykickstart-2.13-3.fc23` has been pushed to the `r3.2` stable repository for dom0.
To install this update, please use the standard update command:
```
sudo qubes-dom0-update
```
Or update dom0 via Qubes Manager.

[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-installer-qubes-os/compare/92571659940c314ffe2b3f1f7e17c4244bffb998...d2988a86431beabea1a59760d5cae1f70b5d0b1b
