### ISSUE TITLE
(qubes-builder) make linux-kernel: "Building packages for fc20 not supported by any of configured plugins."

### ISSUE THREAD

**Issue by rustybird** [QubesOS/qubes-issues#2114]
_Copied from [qubes-devel](https://groups.google.com/forum/#!topic/qubes-devel/d-FPNoPFNhY):_

I'm trying to build the Linux kernel for R3.1.

Cloned qubes-builder, copied example-configs/qubes-os-r3.1.conf to
builder.conf, `make COMPONENTS=linux-kernel get-sources` succeeded, but
then:

```
$ make linux-kernel
Currently installed dependencies:
git-2.5.5-1.fc23.x86_64
rpmdevtools-8.6-2.fc23.noarch
rpm-build-4.13.0-0.rc1.13.fc23.x86_64
createrepo-0.10.3-3.fc21.noarch
python-sh-1.11-1.fc23.noarch
make[1]: Entering directory '/home/user/devel/qubes-builder'
Makefile.generic:20: *** Building packages for fc20 not supported by any
of configured plugins.  Stop.
make[1]: Leaving directory '/home/user/devel/qubes-builder'
Makefile:220: recipe for target 'linux-kernel-dom0' failed
make: *** [linux-kernel-dom0] Error 1
```

**Comment by marmarek** [comment]
You first need to download builder plugins. The easiest way is to simply call `make get-sources` (without `COMPONENTS` overridden).

**Comment by rustybird** [comment]
Thanks! By the way, ftp.qubes-os.org seems to be down.

**Comment by marmarek** [comment]
> Thanks! By the way, ftp.qubes-os.org seems to be down.

Yes, we know.
