### ISSUE TITLE
Installer boot error '/dev/root' does not exist

### ISSUE THREAD

**Issue by ttasket** [QubesOS/qubes-issues#2115]
#### Qubes OS version (e.g., `R3.1`):
R3.2rc1

### Expected behavior:
Installer iso on USB stick boots up with access to attached USB drives.

### Actual behavior:
Boot process stops at '/dev/root does not exist' and drops to rescue CLI.
The boot drive exists as /dev/sdb, but no partitions recognized... `partx /dev/sdb` says its unreadable.
Connecting other USB sticks results in similar behavior: /dev/sdc is enumerated as sdc1, etc. but those partitions are unreadable.

From dmesg:
```
scsi 6:0:0:0: Direct-Access    Samsung Flash Drive    1100 PQ: 0 ANSI: 6
sd 6:0:0:0: alua: supports implicit and explicit TPGS
sd 6:0:0:0: alua: No target port descriptors found
sd 6:0:0:0: alua: Attach  failed (-22)
sd 6:0:0:0: Failed to add device handler: -22
sd 6:0:0:0: [sdb] ...several lines with drive size and flags...
(trace dump occurs)
```

Installer can be booted from DVD, but still cannot access USB sticks.

Fedora 23 installer does not have this issue!

### Steps to reproduce the behavior:
Boot from Qubes R3.2rc1 iso on USB stick

### General notes:
Probably caused by 'alua' module. See thread in qubes-users...
https://groups.google.com/d/msgid/qubes-users/857c13c6-f335-5e02-0758-e2b6c4904d9a%40openmailbox.org

---

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `kernel-devel-4.4.14-10.pvops.qubes` has been pushed to the `r3.2` testing repository for the Fedora `fc23` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.2-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-linux-kernel/compare/9af39fa59ec985ee87d36869960c310443123b83...762d41e99b007e1e9a61a6b71af1c7b722c7b84b

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `kernel-devel-4.4.14-10.pvops.qubes` has been pushed to the `r3.2` testing repository for the Fedora `fc24` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.2-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-linux-kernel/compare/9af39fa59ec985ee87d36869960c310443123b83...762d41e99b007e1e9a61a6b71af1c7b722c7b84b

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `kernel-4.4.14-10.pvops.qubes` has been pushed to the `r3.2` testing repository for dom0.
To test this update, please install it with the following command:
```
sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-linux-kernel/compare/9af39fa59ec985ee87d36869960c310443123b83...762d41e99b007e1e9a61a6b71af1c7b722c7b84b

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `kernel-devel-4.4.14-11.pvops.qubes` has been pushed to the `r3.2` stable repository for the Fedora `fc23` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-linux-kernel/compare/9af39fa59ec985ee87d36869960c310443123b83...ec697d5db041a2e404599fc7d4ac4346b4fdf6c9

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `kernel-devel-4.4.14-11.pvops.qubes` has been pushed to the `r3.2` stable repository for the Fedora `fc24` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-linux-kernel/compare/9af39fa59ec985ee87d36869960c310443123b83...ec697d5db041a2e404599fc7d4ac4346b4fdf6c9

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `kernel-4.4.14-11.pvops.qubes` has been pushed to the `r3.2` stable repository for dom0.
To install this update, please use the standard update command:
```
sudo qubes-dom0-update
```
Or update dom0 via Qubes Manager.

[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-linux-kernel/compare/9af39fa59ec985ee87d36869960c310443123b83...ec697d5db041a2e404599fc7d4ac4346b4fdf6c9
