### ISSUE TITLE
No graphical firstboot when installing 3.2-rc1 with "Xfce-only" option

### ISSUE THREAD

**Issue by rootkovska** [QubesOS/qubes-issues#2121]
... and one needs to perform text-based firstboot instead, which however doesn't offer options such as e.g. creation of usbVM. As a result USB mouse doesn't work, and requires manual policy edit.

**Comment by marmarek** [comment]
Can you check if you have `initial-setup-gui` package installed? If not, it's probably already fixed by https://github.com/marmarek/qubes-installer-qubes-os/commit/59acc12b942e42496820d63d6b1becd4e8b43002

**Comment by rootkovska** [comment]
On Mon, Jun 27, 2016 at 06:35:56PM -0700, Marek Marczykowski-Górecki wrote:
> Can you check if you have `initial-setup-gui` package installed? If not, it's probably already fixed by https://github.com/marmarek/qubes-installer-qubes-os/commit/59acc12b942e42496820d63d6b1becd4e8b43002
> 

Yes, that pkg is missing when installing 3.2-rc1 without KDE.

j.

**Comment by marmarek** [comment]
Ok, so fixed before your report :)
