### ISSUE TITLE
Attaching block devices *from* dispVM broken

### ISSUE THREAD

**Issue by rustybird** [QubesOS/qubes-issues#2126]
#### Qubes OS version (e.g., `R3.1`):

R3.1

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):

Tested with fedora-23 and fedora-23-minimal dispVMs:

```
# start a new dispVM:
[dom0] $ echo xterm | /usr/lib/qubes/qfile-daemon-dvm qubes.VMShell dom0 DEFAULT gray

# create a loop device there:
[disp8] $ truncate -s 1G foo
[disp8] # losetup /dev/loop0 foo

# attach it to another vm:
[dom0] $ qvm-block | grep loop0
disp8:loop0	/home/user/foo 1024 MiB
[dom0] $ qvm-block -a testvm disp8:loop0
[dom0] $ qvm-block | grep loop0
disp8:loop0	/home/user/foo 1024 MiB (attached to 'testvm' as 'xvdi')

#####################################################
# But it doesn't show up in testvm's dmesg or /dev. #
#####################################################

# try to detach it:
[dom0] $ qvm-block -d disp8:loop0
Traceback (most recent call last):
  File "/usr/bin/qvm-block", line 151, in <module>
    main()
  File "/usr/bin/qvm-block", line 133, in main
    block_detach(attached_to['vm'], attached_to['frontend'])
  File "/usr/lib64/python2.7/site-packages/qubes/qubesutils.py", line 447, in block_detach
    vm.libvirt_domain.detachDevice(etree.tostring(disk, encoding='utf-8'))
  File "/usr/lib64/python2.7/site-packages/libvirt.py", line 1146, in detachDevice
    if ret == -1: raise libvirtError ('virDomainDetachDevice() failed', dom=self)
libvirt.libvirtError: internal error: libxenlight failed to detach disk 'xvdi'
[dom0] $ journalctl -b -o short-monotonic
...
[ 8745.585064] dom0 block-cleaner-daemon.py[1481]: libxl: error: libxl_device.c:301:libxl__device_disk_set_backend: no suitable backend for disk xvdi
[ 8745.587866] dom0 block-cleaner-daemon.py[1481]: libxl_device_disk_remove failed.
[ 8755.072768] dom0 libvirtd[1351]: internal error: libxenlight failed to detach disk 'xvdi'
[ 8755.135839] dom0 libvirtd[1351]: End of file while reading data: Input/output error
...
```

**Comment by rustybird** [comment]
Using `xl block-attach` instead of `qvm-block --attach` has the same problem:

```
# before attaching:
dom0 $ xl block-list testvm2
Vdev  BE  handle state evt-ch ring-ref BE-path                       
51712 0   56     4     31     8        /local/domain/0/backend/vbd/56/51712
51728 0   56     4     32     9        /local/domain/0/backend/vbd/56/51728
51744 0   56     4     33     10       /local/domain/0/backend/vbd/56/51744
51760 0   56     4     34     11       /local/domain/0/backend/vbd/56/51760


dom0 $ sudo xl block-attach testvm2 phy:/dev/loop0 backend=disp20 xvdi w
dom0 $ echo $?
0

dom0 $ xl list disp20
Name                                        ID   Mem VCPUs	State	Time(s)
disp20                                      57   315     1     -b----       9.2

dom0 $ xl block-list testvm2
Vdev  BE  handle state evt-ch ring-ref BE-path                       
51712 0   56     4     31     8        /local/domain/0/backend/vbd/56/51712
51728 0   56     4     32     9        /local/domain/0/backend/vbd/56/51728
51744 0   56     4     33     10       /local/domain/0/backend/vbd/56/51744
51760 0   56     4     34     11       /local/domain/0/backend/vbd/56/51760
51840 57  56     3     47     2638     /local/domain/57/backend/vbd/56/51840

######################################################
# But it doesn't show up in testvm2's dmesg or /dev. #
######################################################

dom0 $ sudo xl block-detach testvm2 51840
libxl: error: libxl_device.c:301:libxl__device_disk_set_backend: no suitable backend for disk xvdi
libxl_device_disk_remove failed.
```

**Comment by rustybird** [comment]
The last line from block-list looks interesting: It appears that the disk does not transition from XenbusStateInitialised (= 3) to to XenBusStateConnected (= 4).

**Comment by marmarek** [comment]
Do you see anything interesting in kernel messages of either VM? Or maybe in `/var/log/xen/xen-hotplug.log` of dispvm?

**Comment by rustybird** [comment]
> Do you see anything interesting in kernel messages of either VM?

In the destination testvm, nothing at all. But there's something kind of interesting about a disposable source VM vs. a normal (non-disposable, successful) source VM -- using `sudo journald` here to show both kernel and userspace logs.

disposable source:

```
[  309.965670] fedora-23-clone-1-dvm kernel: xen-blkback: event-channel 46
[  309.967128] fedora-23-clone-1-dvm kernel: xen-blkback: /local/domain/75/device/vbd/51840:using single page: ring-ref 2946
[  309.968078] fedora-23-clone-1-dvm kernel: xen-blkback: ring-pages:1, event-channel 46, protocol 1 (x86_64-abi) persistent grants
```

normal source:

```
[ 7309.744756] normalvm kernel: xen-blkback: event-channel 50
[ 7309.747492] normalvm kernel: xen-blkback: /local/domain/75/device/vbd/51856:using single page: ring-ref 2947
[ 7309.748369] normalvm kernel: xen-blkback: ring-pages:1, event-channel 50, protocol 1 (x86_64-abi) persistent grants
[ 7309.754343] normalvm kernel: xen-blkback: event-channel 50
[ 7309.761667] normalvm kernel: xen-blkback: /local/domain/75/device/vbd/51856:using single page: ring-ref 2947
[ 7309.764652] normalvm kernel: xen-blkback: ring-pages:1, event-channel 50, protocol 1 (x86_64-abi) persistent grants
[ 7309.912848] normalvm root[2435]: /etc/xen/scripts/block: add XENBUS_PATH=backend/vbd/75/51856
[ 7310.371945] normalvm root[2484]: /etc/xen/scripts/block: Writing backend/vbd/75/51856/physical-device 7:0 to xenstore.
[ 7310.424383] normalvm root[2486]: /etc/xen/scripts/block: Writing backend/vbd/75/51856/hotplug-status connected to xenstore.
```

So, in a disposable VM, there's three kernel lines. Whereas in the successful case of a non-disposable VM, there's three kernel lines, then the same three lines repeated, then /etc/xen/scripts/block runs.

> Or maybe in /var/log/xen/xen-hotplug.log of dispvm?

Doesn't exist, only empty /var/log/xen/xldev.log* files.

**Comment by rustybird** [comment]
Woo! `systemctl restart xendriverdomain` in the dispvm fixes it!

**Comment by marmarek** [comment]
Interesting (but not surprising). Probably should be restarted automatically after DispVM startup (= restore from savefile). Or maybe even ordered to start at that time?

**Comment by rustybird** [comment]
Reordering seems best. Part of https://github.com/QubesOS/qubes-core-agent-linux/pull/18

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `python2-dnf-plugins-qubes-hooks-3.2.6-1.fc23` has been pushed to the `r3.2` testing repository for the Fedora `fc23` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.2-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/d47a89ec76452a4c9efe3b5cbf87157083b3d765...e7b1711e2176bcf030d8c6c9698688aaf7639aee

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `python2-dnf-plugins-qubes-hooks-3.2.6-1.fc24` has been pushed to the `r3.2` testing repository for the Fedora `fc24` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.2-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/d47a89ec76452a4c9efe3b5cbf87157083b3d765...e7b1711e2176bcf030d8c6c9698688aaf7639aee

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-agent_3.2.6-1+deb8u1` has been pushed to the `r3.2` testing repository for the Debian `jessie` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `jessie-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/d47a89ec76452a4c9efe3b5cbf87157083b3d765...e7b1711e2176bcf030d8c6c9698688aaf7639aee

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-agent_3.2.6-1+deb9u1` has been pushed to the `r3.2` testing repository for the Debian `stretch` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `stretch-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/d47a89ec76452a4c9efe3b5cbf87157083b3d765...e7b1711e2176bcf030d8c6c9698688aaf7639aee

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-agent_3.2.6-1+deb7u1` has been pushed to the `r3.2` testing repository for the Debian `wheezy` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `wheezy-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/d47a89ec76452a4c9efe3b5cbf87157083b3d765...e7b1711e2176bcf030d8c6c9698688aaf7639aee

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `python2-dnf-plugins-qubes-hooks-3.2.9-1.fc23` has been pushed to the `r3.2` stable repository for the Fedora `fc23` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/d47a89ec76452a4c9efe3b5cbf87157083b3d765...fd8a1167446a8b2e8487d67b9c2888663327a805

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `python2-dnf-plugins-qubes-hooks-3.2.9-1.fc24` has been pushed to the `r3.2` stable repository for the Fedora `fc24` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/d47a89ec76452a4c9efe3b5cbf87157083b3d765...fd8a1167446a8b2e8487d67b9c2888663327a805

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-agent_3.2.10-1+deb8u1` has been pushed to the `r3.2` stable repository for the Debian `jessie` template.
To install this update, please use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/d47a89ec76452a4c9efe3b5cbf87157083b3d765...1a601ddbe9bae11088a78136bfe7cd8a1b3258f1

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `python2-dnf-plugins-qubes-hooks-3.1.19-1.fc21` has been pushed to the `r3.1` testing repository for the Fedora `fc21` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.1-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/193eb55330f79a4c20bd695ee25b27adf27e2a96...1d74a449676cf31f41a17a6dff21be6246529740

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `python2-dnf-plugins-qubes-hooks-3.1.19-1.fc22` has been pushed to the `r3.1` testing repository for the Fedora `fc22` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.1-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/193eb55330f79a4c20bd695ee25b27adf27e2a96...1d74a449676cf31f41a17a6dff21be6246529740

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `python2-dnf-plugins-qubes-hooks-3.1.19-1.fc23` has been pushed to the `r3.1` testing repository for the Fedora `fc23` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.1-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/193eb55330f79a4c20bd695ee25b27adf27e2a96...1d74a449676cf31f41a17a6dff21be6246529740

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-agent_3.1.19-1+deb8u1` has been pushed to the `r3.1` testing repository for the Debian `jessie` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `jessie-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/193eb55330f79a4c20bd695ee25b27adf27e2a96...1d74a449676cf31f41a17a6dff21be6246529740

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-agent_3.1.19-1+deb9u1` has been pushed to the `r3.1` testing repository for the Debian `stretch` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `stretch-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/193eb55330f79a4c20bd695ee25b27adf27e2a96...1d74a449676cf31f41a17a6dff21be6246529740

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-agent_3.1.19-1+deb7u1` has been pushed to the `r3.1` testing repository for the Debian `wheezy` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `wheezy-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/193eb55330f79a4c20bd695ee25b27adf27e2a96...1d74a449676cf31f41a17a6dff21be6246529740

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `python2-dnf-plugins-qubes-hooks-3.1.19-1.fc21` has been pushed to the `r3.1` stable repository for the Fedora `fc21` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/193eb55330f79a4c20bd695ee25b27adf27e2a96...1d74a449676cf31f41a17a6dff21be6246529740

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `python2-dnf-plugins-qubes-hooks-3.1.19-1.fc22` has been pushed to the `r3.1` stable repository for the Fedora `fc22` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/193eb55330f79a4c20bd695ee25b27adf27e2a96...1d74a449676cf31f41a17a6dff21be6246529740

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `python2-dnf-plugins-qubes-hooks-3.1.19-1.fc23` has been pushed to the `r3.1` stable repository for the Fedora `fc23` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/193eb55330f79a4c20bd695ee25b27adf27e2a96...1d74a449676cf31f41a17a6dff21be6246529740

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-agent_3.1.19-1+deb8u1` has been pushed to the `r3.1` stable repository for the Debian `jessie` template.
To install this update, please use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/193eb55330f79a4c20bd695ee25b27adf27e2a96...1d74a449676cf31f41a17a6dff21be6246529740

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-agent_3.1.19-1+deb9u1` has been pushed to the `r3.1` stable repository for the Debian `stretch` template.
To install this update, please use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/193eb55330f79a4c20bd695ee25b27adf27e2a96...1d74a449676cf31f41a17a6dff21be6246529740

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-agent_3.1.19-1+deb7u1` has been pushed to the `r3.1` stable repository for the Debian `wheezy` template.
To install this update, please use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/193eb55330f79a4c20bd695ee25b27adf27e2a96...1d74a449676cf31f41a17a6dff21be6246529740
