### ISSUE TITLE
Xfce4's panel's "System Tools" menu disappears after appmenus updates

### ISSUE THREAD

**Issue by rootkovska** [QubesOS/qubes-issues#2129]
The "System Tools" menu which is part of the Applications menu displayed by default in our Xfce4 disappears reliably after each appmenu update. Logging out of Xfce4 and loging back again fixes the problem. Until the next appmenu update. Looks like a Xfce4 bug?

This is annoying becuase System Setting is accessible through this menu normally...

**Comment by marmarek** [comment]
Same here...

**Comment by andrewdavidwong** [comment]
@evadogstar [wrote](https://groups.google.com/d/msgid/qubes-users/ffabf9d0-9657-43e5-e097-75c905f65019%40openmailbox.org):
> About issue with losing "System Tools" links at Application menu
> you are already noticed?
> https://i.imgur.com/rCMiymX.png
> It's also not available under right click of the mouse.

**Comment by rootkovska** [comment]
Can we ask somebody from Xfce4 project for help?

**Comment by marmarek** [comment]
It looks to be somehow related to `<OnlyUnallocated/>` tag in `/etc/xdg/menus/xfce-applications.menu`. When I remove it, the menu is back, when I add it back, "System Tools" disappear again - until session restart.
But without `<OnlyUnallocated/>` tag, "System Tools" contain all the entries - also those from VMs.

I have an idea for a workaround using categories, but better get it fixed properly. 
Xfce4 bug report: https://bugzilla.xfce.org/show_bug.cgi?id=12700

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-dom0-linux-3.2.5-1.fc23` has been pushed to the `r3.2` testing repository for dom0.
To test this update, please install it with the following command:
```
sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-admin-linux/compare/db8aa6cf15f4b4f715de14219b2bacd9ee554876...769e70e76a22381727e9f4ab4b8f2a51c24fa228

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `garcon-0.4.0-4.fc23` has been pushed to the `r3.2` testing repository for dom0.
To test this update, please install it with the following command:
```
sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-desktop-linux-xfce4/compare/5e466c4f97ac0fc18e398baa6433bc8da1057ab6...e55a55f9c5068aec5b13ee36f3ef8fd7712b6209

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-dom0-linux-3.2.5-1.fc23` has been pushed to the `r3.2` stable repository for dom0.
To install this update, please use the standard update command:
```
sudo qubes-dom0-update
```
Or update dom0 via Qubes Manager.

[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-admin-linux/compare/30aac6b6a801ff48c67d32c0baeb75942f44f3c2...769e70e76a22381727e9f4ab4b8f2a51c24fa228

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `garcon-0.4.0-4.fc23` has been pushed to the `r3.2` stable repository for dom0.
To install this update, please use the standard update command:
```
sudo qubes-dom0-update
```
Or update dom0 via Qubes Manager.

[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-desktop-linux-xfce4/compare/5e466c4f97ac0fc18e398baa6433bc8da1057ab6...e55a55f9c5068aec5b13ee36f3ef8fd7712b6209
