### ISSUE TITLE
Add Purism-touchpad support package to ISO

### ISSUE THREAD

**Issue by rootkovska** [QubesOS/qubes-issues#2131]

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `kernel-devel-4.4.14-10.pvops.qubes` has been pushed to the `r3.2` testing repository for the Fedora `fc23` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.2-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-linux-kernel/compare/9af39fa59ec985ee87d36869960c310443123b83...762d41e99b007e1e9a61a6b71af1c7b722c7b84b

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `kernel-devel-4.4.14-10.pvops.qubes` has been pushed to the `r3.2` testing repository for the Fedora `fc24` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.2-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-linux-kernel/compare/9af39fa59ec985ee87d36869960c310443123b83...762d41e99b007e1e9a61a6b71af1c7b722c7b84b

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `kernel-4.4.14-10.pvops.qubes` has been pushed to the `r3.2` testing repository for dom0.
To test this update, please install it with the following command:
```
sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-linux-kernel/compare/9af39fa59ec985ee87d36869960c310443123b83...762d41e99b007e1e9a61a6b71af1c7b722c7b84b

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `kernel-devel-4.1.28-10.pvops.qubes` has been pushed to the `r3.1` testing repository for the Fedora `fc21` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.1-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-linux-kernel/compare/4216250e9b66c09f13055497da62c89229de4dd8...d04785a80b630b1899c5a856990ffd899f1c9738

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `kernel-devel-4.1.28-10.pvops.qubes` has been pushed to the `r3.1` testing repository for the Fedora `fc22` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.1-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-linux-kernel/compare/4216250e9b66c09f13055497da62c89229de4dd8...d04785a80b630b1899c5a856990ffd899f1c9738

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `kernel-devel-4.1.28-10.pvops.qubes` has been pushed to the `r3.1` testing repository for the Fedora `fc23` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.1-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-linux-kernel/compare/4216250e9b66c09f13055497da62c89229de4dd8...d04785a80b630b1899c5a856990ffd899f1c9738

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `kernel-4.1.28-10.pvops.qubes` has been pushed to the `r3.1` testing repository for dom0.
To test this update, please install it with the following command:
```
sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-linux-kernel/compare/4216250e9b66c09f13055497da62c89229de4dd8...d04785a80b630b1899c5a856990ffd899f1c9738

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `kernel-devel-4.4.14-11.pvops.qubes` has been pushed to the `r3.2` stable repository for the Fedora `fc23` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-linux-kernel/compare/9af39fa59ec985ee87d36869960c310443123b83...ec697d5db041a2e404599fc7d4ac4346b4fdf6c9

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `kernel-devel-4.4.14-11.pvops.qubes` has been pushed to the `r3.2` stable repository for the Fedora `fc24` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-linux-kernel/compare/9af39fa59ec985ee87d36869960c310443123b83...ec697d5db041a2e404599fc7d4ac4346b4fdf6c9

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `kernel-4.4.14-11.pvops.qubes` has been pushed to the `r3.2` stable repository for dom0.
To install this update, please use the standard update command:
```
sudo qubes-dom0-update
```
Or update dom0 via Qubes Manager.

[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-linux-kernel/compare/9af39fa59ec985ee87d36869960c310443123b83...ec697d5db041a2e404599fc7d4ac4346b4fdf6c9

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `kernel-devel-4.1.24-10.pvops.qubes` has been pushed to the `r3.1` stable repository for the Fedora `fc21` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-linux-kernel/compare/dab8297835e557fecfd6766155dbb1da0c343a3d...c652a088be97b483713905ccefa7ba57e6b50964

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `kernel-devel-4.1.24-10.pvops.qubes` has been pushed to the `r3.1` stable repository for the Fedora `fc22` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-linux-kernel/compare/dab8297835e557fecfd6766155dbb1da0c343a3d...c652a088be97b483713905ccefa7ba57e6b50964

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `kernel-devel-4.1.24-10.pvops.qubes` has been pushed to the `r3.1` stable repository for the Fedora `fc23` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-linux-kernel/compare/dab8297835e557fecfd6766155dbb1da0c343a3d...c652a088be97b483713905ccefa7ba57e6b50964

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `kernel-4.1.24-10.pvops.qubes` has been pushed to the `r3.1` stable repository for dom0.
To install this update, please use the standard update command:
```
sudo qubes-dom0-update
```
Or update dom0 via Qubes Manager.

[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-linux-kernel/compare/dab8297835e557fecfd6766155dbb1da0c343a3d...c652a088be97b483713905ccefa7ba57e6b50964
