### ISSUE TITLE
Installer attempts to run commands on ServiceVMs even if user opted not to create them

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#2142]
#### Qubes OS version (e.g., `R3.1`):

`R3.2-rc1`

#### Problem Description:

> During initial configuration, if you don't create the NetVMs because you 
> want to set everything yourself, it has error running a command because no 
> matter what, it will try to run the command on the sys-net and sys-firewall.

[Full message](https://groups.google.com/d/msgid/qubes-users/0c7e44c6-ff3e-4b2a-97c4-1b49c11c9677%40googlegroups.com)

**Comment by marmarek** [comment]
Cannot reproduce.

**Comment by marmarek** [comment]
Ok, clarification: it isn't about selecting "do not configure anything". It's about not selecting any option at all - which still makes sense to get templates configured.

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `pykickstart-2.13-3.fc23` has been pushed to the `r3.2` testing repository for dom0.
To test this update, please install it with the following command:
```
sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-installer-qubes-os/compare/6be5ff7e559c9e683731078662761270d7fa53a0...d2988a86431beabea1a59760d5cae1f70b5d0b1b

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `pykickstart-2.13-3.fc23` has been pushed to the `r3.2` stable repository for dom0.
To install this update, please use the standard update command:
```
sudo qubes-dom0-update
```
Or update dom0 via Qubes Manager.

[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-installer-qubes-os/compare/92571659940c314ffe2b3f1f7e17c4244bffb998...d2988a86431beabea1a59760d5cae1f70b5d0b1b
