### ISSUE TITLE
PV USB documentation needs to be updated for Qubes R3.2

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#2144]
Now, that #531 is done in R3.2... I think PVUSB documentation needs to be updated.
- https://www.qubes-os.org/doc/pvusb/
- https://www.qubes-os.org/doc/security-guidelines/#tocAnchor-1-1-8
- https://www.qubes-os.org/doc/user-faq/#i-created-a-usbvm-and-assigned-usb-controllers-to-it-now-the-usbvm-wont-boot

Suggested contents:
- What is PVUSB?
- Why should I use it?
- Is PVUSB stable or experimental?
- How do I get (setup) it if I install Qubes R3.2?
- How do I get (setup) it if I upgraded Qubes to R3.2?
- Perhaps document what to do if one can only connect only USB input devices... And worse so, if these are internally connected to the same USB controller as all other USB devices... (Such as in my case.) If that is still an issue?
  - How to recover from situations where my keyboard and mice stops working?
- document #1630 - if that still applies?
- document #1649
- Anything else?

**Comment by adrelanos** [comment]
Updated original report. (Will delete this comment.)

**Comment by Sen-Dion** [comment]
Correct the policy in [How to use a USB keyboard](https://www.qubes-os.org/doc/usb/#how-to-use-a-usb-keyboard) manual.  It should be:
`sys-usb dom0 ask,user=root`

**Comment by andrewdavidwong** [comment]
@Sen-Dion: Updated.

**Comment by DemiMarie** [comment]
Is this issue obsolete right now?  I think it falls under the overall device system.
