### ISSUE TITLE
RuntimeError: maximum recursion depth exceeded

### ISSUE THREAD

**Issue by ajense** [QubesOS/qubes-issues#2146]
#### Qubes OS version : 

3.18.17-8

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable): 

dom0, all app VM except recently created ones.

---

### Expected behavior:  

Successfuly open or updates the app VM or dom0

### Actual behavior:  

RuntimeError: maximum recursion depth exceeded

### General notes:

---

**Comment by andrewdavidwong** [comment]
You probably have a NetVM loop. Make sure your VMs are connected like 
this: 

    AppVM --> sys-firewall --> sys-net

And, if you're using Whonix:

    TemplateVM --> sys-whonix --> sys-firewall --> sys-net 
    whonix-ws --> sys-whonix --> sys-firewall --> sys-net 
    whonix-gw --> sys-whonix --> sys-firewall --> sys-net 

In the future, please search the mailing lists first. Then, if you still can't find the answer, and it's this sort of question, ask on the mailing lists.
