### ISSUE TITLE
Test and document hooking TCP connection into qrexec using socat

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#2148]
[On 2016-07-03 11:29, Marek Marczykowski-Górecki wrote:](https://groups.google.com/d/msgid/qubes-users/20160703182905.GY1323%40mail-itl)

> It should be easy to hook any TCP connection into qrexec using socat. 
> 
> Something like this (untested):
> 
> source VM: launch this somewhere (`/rw/config/rc.local`?)
> 
> ```
> socat TCP-LISTEN:4444,fork EXEC:"qrexec-client-vm target-vm my-tcp-service"
> ```
> 
> target VM: `/usr/local/etc/qubes-rpc/my-tcp-service` (this is stored in `/rw`):
> 
> ```
> socat STDIO TCP:localhost:4444
> ```
> 
> dom0: `/etc/qubes-rpc/policy/my-tcp-service`
> 
> ```
> source-vm target-vm allow
> ```

**Comment by andrewdavidwong** [comment]
(This could become a tool instead of just documentation steps.)

**Comment by Joeviocoe** [comment]
https://gist.github.com/Joeviocoe/90ec9fd9a0769b4671a8ae9c87584187

**Comment by andrewdavidwong** [comment]
@Joeviocoe: Please consider submitting this as a PR to the appropriate repo. I'm afraid it'll be overlooked as just a comment with a link to a gist.

**Comment by marmarek** [comment]
Documented at https://www.qubes-os.org/doc/firewall/#opening-a-single-tcp-port-to-other-network-isolated-qube already
