### ISSUE TITLE
Document creation of custom entries for qvm-sync-appmenus

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#2149]
On 2016-07-03 17:45, Marek Marczykowski-Górecki wrote:

> On Mon, Jul 04, 2016 at 03:24:09AM +0300, Eva Star wrote:
> 
> > > Those links are generated from standard location: /usr/share/applications
> > > You need to put .desktop file for your application. Take a look at
> > > existing files there for examples.
> > > 
> > > After you create new file there, execute `qvm-sync-appmenus` in dom0
> > > (with template VM name as an argument).
> > 
> > Thanks for the information :) Seems its works only for TemplateVM?
> > Is it possible to somehow add custom links from AppVM to Start menu ->
> > AppVM(domain) &
> 
> Currently no - this works only for TemplateVMs, and StandaloneVMs - i.e.
> only where /usr/share/applications persists.

[Original message](https://groups.google.com/d/msgid/qubes-users/20160704004515.GK1323%40mail-itl)

**Comment by strugee** [comment]
> Currently no - this works only for TemplateVMs, and StandaloneVMs - i.e.
> only where /usr/share/applications persists.

This isn't true anymore. Desktop files in `~/.local/share/applications` are also picked up.

**Comment by rapenne-s** [comment]
Is there still a need to document this? This is somehow documented here https://www.qubes-os.org/doc/app-menu-shortcut-troubleshooting/

**Comment by andrewdavidwong** [comment]
Ah, perhaps no one remembered to close this issue when it was documented. Thanks!
