### ISSUE TITLE
qubes-manager: TypeError: cannot concatenate 'str' and 'QubesAppVM' objects.

### ISSUE THREAD

**Issue by dingensundso** [QubesOS/qubes-issues#2156]
#### Qubes OS version (e.g., `R3.1`): 
R3.1

When trying to shutdown a VM which serves block-devices to other VMs, qubes-manager throws the following error:

```
  ----
  line: msg += ', '.join(["<b>"+v+"</b>("+d+")" for (d,v) in serves_for ])
  func: check_if_serves_as_backend
  line no.: 157
  file: /usr/lib64/python2.7/site-packages/qubesmanager/block.py
  ----
  line: self.blk_manager.check_if_serves_as_backend(vm)
  func: action_shutdownvm_triggered
  line no.: 1227
  file: /usr/lib64/python2.7/site-packages/qubesmanager/main.py
```

---

### Expected behavior:
Get a normal error message.

### Actual behavior:
See above.

### Steps to reproduce the behavior:
1. Pass usb- or other storage controller to appvm1.
2. `qvm-block -a appvm2 appvm1:md-42` (or whatever your storage device is named)
3. in qubes-manager shutdown appvm1

### General notes:

Couldn't find any reference to this error, so I hope this issue is not a duplicate :)
I think this would be fixed by changing v to v.name in  `/usr/lib64/python2.7/site-packages/qubesmanager/block.py:157`

```
< msg += ', '.join(["<b>"+v+"</b>("+d+")" for (d,v) in serves_for ])
> msg += ', '.join(["<b>"+v.name+"</b>("+d+")" for (d,v) in serves_for ])
```

**Comment by dingensundso** [comment]
Tested my proposed fix locally and it works. Now I get a warning dialog and after that a confimation dialog.

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-manager-3.2.3-1.fc23` has been pushed to the `r3.2` testing repository for dom0.
To test this update, please install it with the following command:
```
sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-manager/compare/ff7207767437d26a0d97d56e938bd3bc6e21cb9e...98cada9f07ec870b02e5f72cc3ae2e105c45a715

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-manager-3.2.3-1.fc23` has been pushed to the `r3.2` stable repository for dom0.
To install this update, please use the standard update command:
```
sudo qubes-dom0-update
```
Or update dom0 via Qubes Manager.

[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-manager/compare/76d4c2dcd9482af277c93e5e1fba4a7c5977d4d2...98cada9f07ec870b02e5f72cc3ae2e105c45a715
