### ISSUE TITLE
Non-NetVM NetworkManager applet (nm-applet) sometimes appears in system tray

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#2159]
The NetworkManager applet (`nm-applet`) is normally supposed to appear only in `sys-net` (in the system tray, excluding intentional cases like a VPN VM). However, some users have reported that an extra one sometimes appears in other VMs:
- [Applet appears in GPG VM](https://groups.google.com/d/topic/qubes-users/DMqWMAi8EP0/discussion)
- [Applet appears in FirewallVM](https://groups.google.com/d/topic/qubes-users/f82NuTkorbE/discussion)

**Comment by jbwells** [comment]
I saw this yesterday in R3.2-rc2.  There were two nm-applet windows in the notification area.  I think the extra one might have been for a disposable VM because it has disappeared now.  While it was there it indicated no connectivity.

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
