### ISSUE TITLE
Unable to restore backup from R3.1 to R3.1 & R3.2

### ISSUE THREAD

**Issue by Chilinot** [QubesOS/qubes-issues#2168]
#### Qubes OS version (e.g., `R3.1`):
R3.1 & R3.2-rc
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):
Unknown

---

### Expected behavior:
List the names of the backup VM's in the backup file.

### Actual behavior:
Popup window with error message:
Title: "Houston, we have a problem..."
Content:
>AttributeError: 'NoneType' object has no attribute 'name'
>This is most likely a bug in the Qubes Manager

Details:
``` 
 ----
 line: vm_info['netvm'] = host_collection \
 func: restore_info_verify
 line no.: 1729
 file: /usr/lib64/python2.7/site-packages/qubes/backup.py
 ----
 line: vms_to_restore = restore_info_verify(vms_to_restore, host_collection)
 func: backup_restore_prepare
 line no.: 1906
 file: /usr/lib64/python2.7/site-packages/qubes/backup.py
 ----
 line: appvm=self.target_appvm)
 func: __fill_vms_list__
 line no.: 140
 file: /usr/lib64/python2.7/site-packages/qubesmanager/restore.py
 ----
 line: self.__fill_vms_list__()
 func: current_page_changed
 line no.: 220
 file: /usr/lib64/python2.7/site-packages/qubesmanager/restore.py
```

### Steps to reproduce the behavior:
1. Back up VM's in R3.1
2. Attempt to restore the VM's on fresh install of either R3.1 or R3.2-rc.
3. Check the "ignore missing" tick-box.
4. Press next.
5. Error.

The same happens when used in the terminal with the "--ignore-missing" option.

### General notes:
When the restoration program attempts to list all VM's in the backup file so that I will be able to select which ones to restore it fails with the above error.

I created the backup in order to reinstall my system.
I selected all VM's except the firewall and net-vm.
The backup is encrypted.
First I installed R3.2-rc, failed with the same message.
Then I tried R3.1 since that was the stable release and the one I had installed previously.
Still failed with the above error.

---

#### Related issues:
#1124

**Comment by Chilinot** [comment]
I forgot to add that this issue only happens if the "Ignore missing" is checked.

**Comment by Chilinot** [comment]
Full output when run in terminal with debug mode:
```
[lucas@dom0 ~]$ qvm-backup-restore --ignore-missing --encrypted --debug /run/media/lucas/Lillextern/Backup/Laptop/Qubes/qubes-backup-2016-07-12T101504 
Please enter the pass phrase that will be used to decrypt/verify the backup: 
Checking backup content...
Working in temporary dir:/var/tmp/restore_K0mWC6
Extracting data: 1.0 MiB to restore
Run command[u'tar', u'-ixvf', '/run/media/lucas/Lillextern/Backup/Laptop/Qubes/qubes-backup-2016-07-12T101504', u'-C', u'/var/tmp/restore_K0mWC6', u'backup-header', u'backup-header.hmac', u'qubes.xml.000', u'qubes.xml.000.hmac']
Got backup header and hmac: backup-header, backup-header.hmac
Verifying file /var/tmp/restore_K0mWC6/backup-header
Loading hmac for file /var/tmp/restore_K0mWC6/backup-header
File verification OK -> Sending file /var/tmp/restore_K0mWC6/backup-header
Creating pipe in: /var/tmp/restore_K0mWC6/restore_pipe
Getting new file:qubes.xml.000
Getting hmac:qubes.xml.000.hmac
Verifying file /var/tmp/restore_K0mWC6/qubes.xml.000
Started sending thread
Moving to dir /var/tmp/restore_K0mWC6
Loading hmac for file /var/tmp/restore_K0mWC6/qubes.xml.000
File verification OK -> Sending file /var/tmp/restore_K0mWC6/qubes.xml.000
Getting new file:
Waiting for the extraction process to finish...Extracting file /var/tmp/restore_K0mWC6/qubes.xml.000

Running command [u'tar', u'-xkv', u'qubes.xml']
Removing file /var/tmp/restore_K0mWC6/qubes.xml.000
qubes.xml
Finished extracting thread
Extraction process finished with code:0
Loading file /var/tmp/restore_K0mWC6/qubes.xml
debian-8 is included in backup
whonix-ws is included in backup
whonix-gw is included in backup
fedora-23 is included in backup
anon-whonix is included in backup
vault is included in backup
personal is included in backup
web is included in backup
mail is included in backup
dev is included in backup
spotify is included in backup
encore is included in backup
Traceback (most recent call last):
  File "/usr/bin/qvm-backup-restore", line 266, in <module>
    main()
  File "/usr/bin/qvm-backup-restore", line 151, in main
    error_callback=error_callback)
  File "/usr/lib64/python2.7/site-packages/qubes/backup.py", line 1906, in backup_restore_prepare
    vms_to_restore = restore_info_verify(vms_to_restore, host_collection)
  File "/usr/lib64/python2.7/site-packages/qubes/backup.py", line 1720, in restore_info_verify
    vm_info['netvm'] = host_collection \
AttributeError: 'NoneType' object has no attribute 'name'
```

**Comment by marmarek** [comment]
What did you choose during installation in firstboot dialog? I guess "do nothing", right?

**Comment by marmarek** [comment]
It looks to be caused by missing default netvm. As a workaround create any netvm (may be not functional at all) and set as default one. Then after restore change default netvm to the restored one (as you probably want).

**Comment by Chilinot** [comment]
@marmarek yes, precisely. When I performed the fresh install I selected "don't configure anything".

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-dom0-3.2.7-1.fc23` has been pushed to the `r3.2` testing repository for dom0.
To test this update, please install it with the following command:
```
sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-admin/compare/4072914b401debba0b8a2ee4341e0d0591454920...f0489a3d5cb5455eb6e658cfa2350b8a86c2442c

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-dom0-3.2.7-1.fc23` has been pushed to the `r3.2` stable repository for dom0.
To install this update, please use the standard update command:
```
sudo qubes-dom0-update
```
Or update dom0 via Qubes Manager.

[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-admin/compare/7f86782e1470a8076bb6ab6684bb6e3907dbc7aa...f0489a3d5cb5455eb6e658cfa2350b8a86c2442c

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-dom0-3.1.18-1.fc20` has been pushed to the `r3.1` testing repository for dom0.
To test this update, please install it with the following command:
```
sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-admin/compare/d8093f38c428e4a9e7be421f2dc57e0a45a19477...d315daf86a97b8ec899df237fcd8af76e223b91e

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-dom0-3.1.18-1.fc20` has been pushed to the `r3.1` stable repository for dom0.
To install this update, please use the standard update command:
```
sudo qubes-dom0-update
```
Or update dom0 via Qubes Manager.

[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-admin/compare/d8093f38c428e4a9e7be421f2dc57e0a45a19477...d315daf86a97b8ec899df237fcd8af76e223b91e
