### ISSUE TITLE
VMs stay yellow in Qubes VM Manger (QVMM) / qrexec not connected error when trying to start applications from QVMM

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#2178]
#### Qubes OS version (e.g., `R3.1`):

R3.2 with testing repository

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):

Debian, Fedora (also with R3.2 testing repository)

---

### Expected behavior:

///

### Actual behavior:

Both, Fedora and Debian based browser VMs stay yellow in QVMM. Running konsole from QVMM keeps failing (tried 3 times each). QVMM reported qrexec not connected. Strangely however running `qvm-run brwser konsole` instantly worked.

(sys-net and sys-firewall are green.)

### Steps to reproduce the behavior:

1) boot Qubes
2) as per "actual behavior"

### General notes:

It is probably not the `xendriverdomain systemd service not enabled in Fedora` (#2141) issue since that is now sorted out.

**Comment by marmarek** [comment]
What is the status of those VMs in `qvm-ls` output?
After failed attempt, check VM related logs in /var/log/qubes and in the
VM itself (journalctl, if you can't access VM terminal window, try `sudo
xl console`).

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-dom0-3.2.7-1.fc23` has been pushed to the `r3.2` testing repository for dom0.
To test this update, please install it with the following command:
```
sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-admin/compare/4072914b401debba0b8a2ee4341e0d0591454920...f0489a3d5cb5455eb6e658cfa2350b8a86c2442c

**Comment by adrelanos** [comment]
This update fixed it for me.

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-dom0-3.2.7-1.fc23` has been pushed to the `r3.2` stable repository for dom0.
To install this update, please use the standard update command:
```
sudo qubes-dom0-update
```
Or update dom0 via Qubes Manager.

[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-admin/compare/7f86782e1470a8076bb6ab6684bb6e3907dbc7aa...f0489a3d5cb5455eb6e658cfa2350b8a86c2442c

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-dom0-3.1.18-1.fc20` has been pushed to the `r3.1` testing repository for dom0.
To test this update, please install it with the following command:
```
sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-admin/compare/d8093f38c428e4a9e7be421f2dc57e0a45a19477...d315daf86a97b8ec899df237fcd8af76e223b91e

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-dom0-3.1.18-1.fc20` has been pushed to the `r3.1` stable repository for dom0.
To install this update, please use the standard update command:
```
sudo qubes-dom0-update
```
Or update dom0 via Qubes Manager.

[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-admin/compare/d8093f38c428e4a9e7be421f2dc57e0a45a19477...d315daf86a97b8ec899df237fcd8af76e223b91e
