### ISSUE TITLE
use ExecStartPost rather than ExecStart for qubes-random-seed.sh

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#2179]
Context:

* https://github.com/QubesOS/qubes-issues/issues/1761
* https://github.com/marmarek/qubes-core-agent-linux/pull/79

Edit suggested for file:

* https://github.com/marmarek/qubes-core-agent-linux/blob/master/vm-systemd/systemd-random-seed.service.d/30_qubes.conf

@marmarek 
> Do I understand correctly that you want to replace ExecStart in systemd-random-seed?

No. (Although that may not be that bad.)

What about rather than using `ExecStart`...

```
ExecStart=/usr/lib/qubes/init/qubes-random-seed.sh
```

Using `ExecStartPost`...?

```
ExecStartPost=/usr/lib/qubes/init/qubes-random-seed.sh
```

Then we would not circumvent the default Debian / systemd behavior. Under the assumption "whatever you add to entropy pool it can only improve entropy but never worsen entropy", it should not hurt.

-----

Related:
`persist random seed files [entropy] in TemplateBasedVMs` (#1752)

//cc @v6ak @cfcs @ag4ve

**Comment by marmarek** [comment]
Placing additional ExecStart do not replace existing one, so both are executed. 
```
[user@testvm ~]$ systemctl status systemd-random-seed
● systemd-random-seed.service - Load/Save Random Seed
   Loaded: loaded (/usr/lib/systemd/system/systemd-random-seed.service; static; vendor preset: disabled)
  Drop-In: /usr/lib/systemd/system/systemd-random-seed.service.d
           └─30_qubes.conf
   Active: active (exited) since Sun 2016-07-17 16:46:28 CEST; 3h 2min ago
     Docs: man:systemd-random-seed.service(8)
           man:random(4)
  Process: 369 ExecStart=/usr/lib/qubes/init/qubes-random-seed.sh (code=exited, status=0/SUCCESS)
  Process: 362 ExecStart=/usr/lib/systemd/systemd-random-seed load (code=exited, status=0/SUCCESS)
 Main PID: 369 (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/systemd-random-seed.service
```

So, it doesn't matter, closing.

**Comment by adrelanos** [comment]
Indeed. Forgot about that... To disable the original one we would have to use `ExecStart=` before.
