### ISSUE TITLE
Qubes doesn't boot with kernel 4.4.12 and 4.4.14 on skylake notebook

### ISSUE THREAD

**Issue by minad** [QubesOS/qubes-issues#2186]
#### Qubes OS version (e.g., `R3.1`):

R3.2rc1 with 4.4.12 and 4.4.14 from unstable

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):

dom0

---

### Expected behavior:

I would expect the default kernel to work on recent hardware.

### Actual behavior:

R3.2rc1 has the 4.4.12 kernel by default. However with this kernel the notebook doesn't boot. After grub the notebook just restarts. The kernel 4.2.8 works but the system doesn't run very stable. Since Linux starting from 4.4 has proper Skylake support, I guess using a newer kernel would make sense?

### Steps to reproduce the behavior:

Boot 4.4.12 or 4.4.14 on skylake.

### General notes:

It might be that some binary blobs are missing from the initramfs as was suggested on the mailing list (see below).

---

#### Related issues:

* https://groups.google.com/forum/#!topic/qubes-users/UXP8RJffpsY
* https://groups.google.com/forum/#!msg/qubes-users/IllB1PaX5tA/-YA1-h59AwAJ
* https://github.com/QubesOS/qubes-issues/issues/1668

**Comment by thomwiggers** [comment]
Qubes R3.2-rc2 is working for me on an XPS 13 with i5-6200U

**Comment by minad** [comment]
I am using a Lenovo Yoga X1 with i5, for which it didn't work with rc1. I have rc2 installed, but didn't try the new kernel yet. I will do so later.

**Comment by minad** [comment]
I just tried it again with 4.4.14-11 and i915.preliminary_hw_support=0 and i915.preliminary_hw_support=1.

@thomwiggers which kernel version and kernel arguments are you using? Did you do generate your own initial ram disk with some special binary blobs (I think something like this was suggested in the aforementioned mailing list posts).

**Comment by thomwiggers** [comment]
I just used the out-of-the-box image from the website with no special parameters.

**Comment by jpouellet** [comment]
@minad Have you made any progress on this? I'm having the same problem.

**Comment by jpouellet** [comment]
The 4.4 initramfs contains usr/lib/firmware/i915/skl_{dmc_ver1{,_23},guc_ver4{,_3}}.bin, the 4.1 initramfs does not contain any i915 firmware. The issue appears to be elsewhere, idk.

**Comment by thomwiggers** [comment]
Are you perhaps using that Yoga that doesn't support Linux / anything without Intel RST RAID drivers? See [this comment](https://news.ycombinator.com/item?id=12546147) on [this thread](https://news.ycombinator.com/item?id=12545878)

**Comment by jpouellet** [comment]
Nope. 4th gen x1 carbon, runs other OSes just fine (non-qubes linux,
pre-4.4-kernel qubes, OpenBSD, etc.). Just problems with qubes with kernels
> 4.1 (/ >= 4.4, idk. i haven't started bisecting yet. Hoping for an easier
solution.

**Comment by jpouellet** [comment]
See also https://groups.google.com/forum/#!topic/qubes-users/xfWFGZxEqrY

**Comment by minad** [comment]
No progress from my side. I didn't dig deeper. Bisecting is the right thing to do but too time consuming for me right now. I am still using the old 4.2.8 kernel in dom0

**Comment by jpouellet** [comment]
Seems my issue was actually UEFI trouble. @minad see if https://www.qubes-os.org/doc/uefi-troubleshooting/ fixes it for you. It appears to have fixed it for me.

**Comment by minad** [comment]
@jpouellet Could you please post your xen.cfg, mine is empty and the documentation talks about kernel sections? If I understand correctly the changes to the xen.cfg are the only changes necessary since my system is already installed.

**Comment by minad** [comment]
Ah, I guess it is this one:

https://github.com/QubesOS/qubes-installer-qubes-os/blob/master/lorax-templates-qubes/templates/config_files/x86/xen-efi.cfg

modified by the installer script

https://github.com/QubesOS/qubes-installer-qubes-os/blob/master/lorax-templates-qubes/templates/efi.tmpl

**Comment by minad** [comment]
Ok, found the problem. I had a legacy bios installation. Legacy and UEFI were activated and it seems that qubes did a bios install back then. After a reinstall with UEFI in the bios everything works without tweaking. Stability seems to be improved compared to the 4.2.8 kernel.

I guess it is ok to close this. It might be good to mention in the install instructions that UEFI should be preferred?

**Comment by jpouellet** [comment]
That looks more like the config you have in the actual installer image rather than the one installed to your running machine.

Mine looks like:
```
[global]
default=4.4.14-11.pvops.qubes.x86_64

[4.4.14-11.pvops.qubes.x86_64]
options=loglvl=all dom0_mem=min:1024M dom0_mem=max:4096M
kernel=vmlinuz-4.4.14-11.pvops.qubes.x86_64 root=/dev/mapper/qubes_dom0-root rd.luks.uuid=luks-XXX-your-disk-guid-here-XXX rd.lvm.lv=qubes_dom0/root rd.lvm.lv=qubes_dom0/swap i915.preliminary_hw_support=1 rhgb quiet rd.qubes.hide_all_usb
ramdisk=initramfs-4.4.14-11.pvops.qubes.x86_64.img

[4.4.14-11.pvops.qubes.x86_64]
options=loglvl=all dom0_mem=min:1024M dom0_mem=max:4096M
kernel=vmlinuz-4.4.14-11.pvops.qubes.x86_64 root=/dev/mapper/qubes_dom0-root rd.luks.uuid=luks-XXX-your-disk-guid-here-XXX rd.lvm.lv=qubes_dom0/root rd.lvm.lv=qubes_dom0/swap i915.preliminary_hw_support=1 rhgb quiet rd.qubes.hide_all_usb
ramdisk=initramfs-4.4.14-11.pvops.qubes.x86_64.img
```

**Comment by minad** [comment]
@jpouellet Thx! Yes you are right about the installer configuration. I was able to generate a similar configuration that you just posted by using the installer xen.cfg and then reinstalling the kernel. 
Then I tried to convert my installation from bios to uefi, but it proved to be too time consuming. Finally I just did a fresh reinstall.
