### ISSUE TITLE
qvm-run does not always color stderr, even if it is a TTY

### ISSUE THREAD

**Issue by rustybird** [QubesOS/qubes-issues#2190]
#### Qubes OS version:

R3.1, probably also R3.2

---

    qvm-run --pass-io anyvm 'echo untrusted >&2' >/dev/null

is not colored red.

**Comment by marmarek** [comment]
Indeed currently coloring enabled based on stdout being TTY or not. If you redirect it to `/dev/null`, it is no longer TTY...
But even if you force coloring, sequence enabling colors is outputed to stdout - so if redirected to `/dev/null`, it will be useless.

Do you think it both should receive color switch sequence? Probably yes...

Anyway, what is real use case for `--pass-io`, then redirecting stdout to `/dev/null`?

**Comment by rustybird** [comment]
> Do you think it both should receive color switch sequence?

Yes. Maybe it could even be simplified by letting qrexec-client take prologue string and epilogue string arguments (defaulting to `\033[0;31m` and `\033[0m`), which would be written to stdout and stderr if they are terminals. Because qrexec-client already handles something related with `-t` and `-T`.

> Anyway, what is real use case for --pass-io, then redirecting stdout to /dev/null?

Heh, /dev/null was not the best example. My actual use use case is `qvm-run ... | other_command`.

**Comment by rustybird** [comment]
> Maybe it could even be simplified by letting qrexec-client take prologue string and epilogue string arguments

Scratch that: Dealing with signals in C to ensure that the epilogue string is written out would probably be too much trouble.

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-dom0-3.2.8-1.fc23` has been pushed to the `r3.2` testing repository for dom0.
To test this update, please install it with the following command:
```
sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-admin/compare/f0489a3d5cb5455eb6e658cfa2350b8a86c2442c...10c44e87221dfb5431934376648ce05855a63cda

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-dom0-3.2.8-1.fc23` has been pushed to the `r3.2` stable repository for dom0.
To install this update, please use the standard update command:
```
sudo qubes-dom0-update
```
Or update dom0 via Qubes Manager.

[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-admin/compare/f0489a3d5cb5455eb6e658cfa2350b8a86c2442c...10c44e87221dfb5431934376648ce05855a63cda

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-dom0-3.1.18-1.fc20` has been pushed to the `r3.1` testing repository for dom0.
To test this update, please install it with the following command:
```
sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-admin/compare/d8093f38c428e4a9e7be421f2dc57e0a45a19477...d315daf86a97b8ec899df237fcd8af76e223b91e

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-dom0-3.1.18-1.fc20` has been pushed to the `r3.1` stable repository for dom0.
To install this update, please use the standard update command:
```
sudo qubes-dom0-update
```
Or update dom0 via Qubes Manager.

[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-admin/compare/d8093f38c428e4a9e7be421f2dc57e0a45a19477...d315daf86a97b8ec899df237fcd8af76e223b91e
