### ISSUE TITLE
qubes-random-seed systemd service failing - Cannot add dependency job for unit qubes-random-seed.service

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#2192]
#### Qubes OS version (e.g., `R3.1`):

R3.2 with testing repository

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):

debian 8 / fedora 23

---

### Steps to reproduce the behavior:

Nothing special. Just boot the VM.

```
user@debian-8:~$ sudo service qubes-random-seed status
● qubes-random-seed.service
   Loaded: not-found (Reason: No such file or directory)
   Active: inactive (dead)

Jul 22 19:15:17 debian-8 systemd[1]: Cannot add dependency job for unit qubes-random-seed.service, ignoring: Unit qubes-random-seed.service failed to load: No such f...r directory.
Jul 22 19:15:17 debian-8 systemd[1]: Cannot add dependency job for unit qubes-random-seed.service, ignoring: Unit qubes-random-seed.service failed to load: No such f...r directory.
Jul 22 19:15:18 debian-8 systemd[1]: Cannot add dependency job for unit qubes-random-seed.service, ignoring: Unit qubes-random-seed.service failed to load: No such f...r directory.
Jul 22 19:15:18 debian-8 systemd[1]: Cannot add dependency job for unit qubes-random-seed.service, ignoring: Unit qubes-random-seed.service failed to load: No such f...r directory.
Jul 22 19:18:06 debian-8 systemd[1]: Cannot add dependency job for unit qubes-random-seed.service, ignoring: Unit qubes-random-seed.service failed to load: No such f...r directory.
Jul 22 19:20:09 debian-8 systemd[1]: Cannot add dependency job for unit qubes-random-seed.service, ignoring: Unit qubes-random-seed.service failed to load: No such f...r directory.
Jul 22 19:21:50 debian-8 systemd[1]: Cannot add dependency job for unit qubes-random-seed.service, ignoring: Unit qubes-random-seed.service failed to load: No such f...r directory.
Jul 22 19:24:05 debian-8 systemd[1]: Cannot add dependency job for unit qubes-random-seed.service, ignoring: Unit qubes-random-seed.service failed to load: No such f...r directory.
Jul 22 19:25:02 debian-8 systemd[1]: Cannot add dependency job for unit qubes-random-seed.service, ignoring: Unit qubes-random-seed.service failed to load: No such f...r directory.
Jul 22 19:25:02 debian-8 systemd[1]: Cannot add dependency job for unit qubes-random-seed.service, ignoring: Unit qubes-random-seed.service failed to load: No such f...r directory.
Hint: Some lines were ellipsized, use -l to show in full.
```
```
user@debian-8:~$ sudo journalctl -u qubes-random-seed | cat
-- Logs begin at Fri 2016-07-22 19:15:11 CEST, end at Fri 2016-07-22 19:25:22 CEST. --
Jul 22 19:15:15 debian-8 systemd[1]: Cannot add dependency job for unit qubes-random-seed.service, ignoring: Unit qubes-random-seed.service failed to load: No such file or directory.
Jul 22 19:15:16 debian-8 systemd[1]: Cannot add dependency job for unit qubes-random-seed.service, ignoring: Unit qubes-random-seed.service failed to load: No such file or directory.
Jul 22 19:15:17 debian-8 systemd[1]: Cannot add dependency job for unit qubes-random-seed.service, ignoring: Unit qubes-random-seed.service failed to load: No such file or directory.
Jul 22 19:15:17 debian-8 systemd[1]: Cannot add dependency job for unit qubes-random-seed.service, ignoring: Unit qubes-random-seed.service failed to load: No such file or directory.
Jul 22 19:15:18 debian-8 systemd[1]: Cannot add dependency job for unit qubes-random-seed.service, ignoring: Unit qubes-random-seed.service failed to load: No such file or directory.
Jul 22 19:15:18 debian-8 systemd[1]: Cannot add dependency job for unit qubes-random-seed.service, ignoring: Unit qubes-random-seed.service failed to load: No such file or directory.
Jul 22 19:18:06 debian-8 systemd[1]: Cannot add dependency job for unit qubes-random-seed.service, ignoring: Unit qubes-random-seed.service failed to load: No such file or directory.
Jul 22 19:20:09 debian-8 systemd[1]: Cannot add dependency job for unit qubes-random-seed.service, ignoring: Unit qubes-random-seed.service failed to load: No such file or directory.
Jul 22 19:21:50 debian-8 systemd[1]: Cannot add dependency job for unit qubes-random-seed.service, ignoring: Unit qubes-random-seed.service failed to load: No such file or directory.
Jul 22 19:24:05 debian-8 systemd[1]: Cannot add dependency job for unit qubes-random-seed.service, ignoring: Unit qubes-random-seed.service failed to load: No such file or directory.
Jul 22 19:25:02 debian-8 systemd[1]: Cannot add dependency job for unit qubes-random-seed.service, ignoring: Unit qubes-random-seed.service failed to load: No such file or directory.                                                                                                                                                                                  
Jul 22 19:25:02 debian-8 systemd[1]: Cannot add dependency job for unit qubes-random-seed.service, ignoring: Unit qubes-random-seed.service failed to load: No such file or directory.                                                                                                                                                                                  
user@debian-8:~$
```

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-agent_3.2.9-1+deb8u1` has been pushed to the `r3.2` testing repository for the Debian `jessie` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `jessie-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/979e2d2bf8a5a697634ce6954247f8fbae5ff438...fd8a1167446a8b2e8487d67b9c2888663327a805

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-agent_3.2.9-1+deb9u1` has been pushed to the `r3.2` testing repository for the Debian `stretch` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `stretch-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/979e2d2bf8a5a697634ce6954247f8fbae5ff438...fd8a1167446a8b2e8487d67b9c2888663327a805

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `python2-dnf-plugins-qubes-hooks-3.2.9-1.fc23` has been pushed to the `r3.2` testing repository for the Fedora `fc23` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.2-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/979e2d2bf8a5a697634ce6954247f8fbae5ff438...fd8a1167446a8b2e8487d67b9c2888663327a805

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `python2-dnf-plugins-qubes-hooks-3.2.9-1.fc24` has been pushed to the `r3.2` testing repository for the Fedora `fc24` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.2-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/979e2d2bf8a5a697634ce6954247f8fbae5ff438...fd8a1167446a8b2e8487d67b9c2888663327a805

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `python2-dnf-plugins-qubes-hooks-3.2.9-1.fc23` has been pushed to the `r3.2` stable repository for the Fedora `fc23` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/d47a89ec76452a4c9efe3b5cbf87157083b3d765...fd8a1167446a8b2e8487d67b9c2888663327a805

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `python2-dnf-plugins-qubes-hooks-3.2.9-1.fc24` has been pushed to the `r3.2` stable repository for the Fedora `fc24` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/d47a89ec76452a4c9efe3b5cbf87157083b3d765...fd8a1167446a8b2e8487d67b9c2888663327a805

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-agent_3.2.10-1+deb8u1` has been pushed to the `r3.2` stable repository for the Debian `jessie` template.
To install this update, please use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/d47a89ec76452a4c9efe3b5cbf87157083b3d765...1a601ddbe9bae11088a78136bfe7cd8a1b3258f1
