### ISSUE TITLE
VPN ProxyVM's autostart fails when launching linked AppVM

### ISSUE THREAD

**Issue by Kozuno** [QubesOS/qubes-issues#2196]
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable): debian-8

---

### Expected behavior:
VPN connection starting on ProxyVM when launching an AppVM (based on debian-8 template) with its NetVM put on this current ProxyVM

### Actual behavior:
VPN connexion is not starting when launching an AppVM with NetVM based on ProxyVM VPN, but works with an openvpn command line inside the ProxyVM

### Steps to reproduce the behavior:
I followed the guide posts here by cprise https://groups.google.com/forum/#!msg/qubes-users/-9gR1Va3BnY/C20BppgbDe4J
I am at the point where VPN connexion works without problems inside the ProxyVM, I have the pop-ups and IP adress changes when I call this cmd line : "sudo openvpn --writepid /var/run/openvpn/openvpn-client.pid --cd /rw/config/openvpn/ --config openvpn-client.ovpn"

Problem could eventually be solved adding this cmd line into /rw/config/rc.local, but I don't know how to convert a terminal cmd line into a C script, it is too complicated for me atm (I am only running Linux related systems since 1-2 months :v).

### General notes:
I tried 2-3 other guides on the web related to Qubes ProxyVM VPN autostarts, but unfortunately every time I get stuck.
Openvpn is installed on debian-8 templateVM.

---

**Comment by andrewdavidwong** [comment]
The guide you followed is pretty old. Have you tried following our more recent [VPN documentation](https://www.qubes-os.org/doc/vpn/)?

**Comment by Kozuno** [comment]
Hello, thank you for your answer. Yes, I did : ) My VPN refused to connect but I changed tonight the port value in advanced configuration using the network-manager and now I'm happy it works I can use a ProxyVM as a VPN gateway :+1: 
I tried second part of the guide few days ago and it didn't work out but now that I can use a VPN as a gateway, I'm fine. Maybe autostart will work with this new port set up. Otherwise my issues is probably related to this : "You may also need to systemctl disable any openvpn service that comes with the package if you follow the instructions for autostart below."

**Comment by andrewdavidwong** [comment]
I'm glad to hear your issue is resolved.
