### ISSUE TITLE
Window border colors not visible

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#2201]
#### Qubes OS version (e.g., `R3.1`):

`R3.2-rc1`
#### Problem description:

After updating today, [users are reporting](https://groups.google.com/d/topic/qubes-users/Y_v1wcl05iM/discussion) that window border colors are no longer visible.

**Comment by andrewdavidwong** [comment]
As reported in the linked thread, the problem was solved by going to

    System Settings -> Application Style -> Window Decorations

and changing from "Plastik" to "Breeze."

This was probably caused by an unrelated KDE update done by Fedora recently.

**Comment by jpouellet** [comment]
Is this still open because there is an action to be taken? If so, what is it?

**Comment by andrewdavidwong** [comment]
Looks like the new defaults in 3.2 don't cause this to happen anymore, so closing.
