### ISSUE TITLE
qvm-usb: Device attach failed for Android 6 in Debugging mode

### ISSUE THREAD

**Issue by grote** [QubesOS/qubes-issues#2202]
#### Qubes OS version
R3.2
#### Affected TemplateVMs
fedora-23

### Expected behavior:
`qvm-usb -a dev sys-usb:3-2` attaches USB device to AppVM 'dev'.

### Actual behavior:
USB is not attached. This error is shown: `ERROR: Device attach failed`
`stderr` and `stdout` of the call make by `qubesutils.py` is empty and `None`.

### Steps to reproduce the behavior:
1. Attach Android 6.0.1 device with activated ADB mode to USB port
2. Call `qvm-usb` to see where it got attached
3. Call `qvm-usb -a dev sys-usb:3-2` to attach it to running 'dev' AppVM
4. See how attaching fails without any helpful error messages.

### General notes:
This happens with an Android 6.0.1 device running CyanogenMod. Please note that attaching an old LG phone in Android debugging mode works just phone. I don't have other phones here at the moment to do more tests.

If I switch debugging mode off, the device attaches just fine. However, when I activate debugging mode on the device, it gets detached from the VM again. dmesg in `sys-usb` shows this:
```
[ 8525.456374] usbip-host 3-2: usbip-host: register new device (bus 3 dev 45)
[ 8525.466994] usbip-host 3-2: stub up
```
Now I activate Android debugging mode on the device.
```
[ 8539.612454] usbip-host 3-2: USB disconnect, device number 45
[ 8539.612926] usbip-host 3-2: recv a header, 0
[ 8539.612954] usbip-host 3-2: lock for reset
[ 8539.948110] usb 3-2: new high-speed USB device number 46 using xhci_hcd
```

Of course, I also tried rebooting the phone, using other USB cables, etc.
The phone was working just fine before using QubesOS on the same hardware.

Help for debugging this further would be greatly appreciated as I **need** to attach this device for work.

**Comment by andrewdavidwong** [comment]
We closed #1375 on the grounds that Android devices are not block devices and therefore not among the [supported device types](https://www.qubes-os.org/doc/usb/#tocAnchor-1-1-3) for USB attachment.

Does toggling "debugging mode" affect whether the device appears as a USB mass storage device?

**Comment by grote** [comment]
Hi @andrewdavidwong,

thanks for answering so quickly. I read #1375 before opening this one, but it is unrelated. This is not about block devices, mass storage mode, MTP or PTP.

This is about an Android USB device failing to attach to a different AppVM when [USB debugging or the Android Debug Brigde](https://developer.android.com/studio/command-line/adb.html#Enabling) is activated. This is used by Android developers to test their apps on real hardware.

**Comment by marmarek** [comment]
I bet it was already reported some time ago, but can't find it just now. The result of debugging was that Android trigger device disconnect as soon as driver is detached from the device. Which is part of the process of attaching the device using qvm-usb. So, it won't fly, unfortunately.
But you can use ADB over TCP.

**Comment by grote** [comment]
> So, it won't fly, unfortunately.

:(

> But you can use ADB over TCP.

Ok thank you very much, I will look into this then.

**Comment by grote** [comment]
Just in case other people stumble upon this:

ADB over TCP works nicely. To activate, go to Developer Options in Settings -> Debugging - > Activate "ADB over network" and note the `IP:port` (e.g. 192.168.0.1:5555) that shows up below the setting.

In your development AppVM type the following:
```
adb connect IP:port
```
Then your device should show up in Android Studio.

This is not a fix for this issue, but a workaround.

**Comment by rustybird** [comment]
In my experience with Android 6 (CM13 on a Nexus 7), attaching works if at least one of the following conditions is satisified *before* calling `qvm-usb --attach`:

1. ADB is enabled on the device and the screen is unlocked
2. The adb daemon is running (as root) on the target VM
