### ISSUE TITLE
qvm-open-in-vm no longer opens URLs in target VM browser

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#2205]
#### Qubes OS version (e.g., `R3.1`):

`R3.1`

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):

`fedora-23` (probably others)

---

### Expected behavior:

Prior to updating yesterday, the following would work:

1. In SourceVM: `qvm-open-in-vm targetvm https://www.qubes-os.org/`
2. In TargetVM: browser opens to https://www.qubes-os.org/

### Actual behavior:

After the update yesterday:

1. In SourceVM: `qvm-open-in-vm targetvm https://www.qubes-os.org/`
2. In TargetVM: text editor opens file `/tmp/sourcevm/tmp.<stuff>` containing:

```
<meta HTTP-EQUIV="REFRESH" content="0; url=https://www.qubes-os.org/"/></html>
```

**Comment by andrewdavidwong** [comment]
I think I see what's happening. Here's the literal output in the SourceVM terminal:

```
[user@sourcevm ~]$ qvm-open-in-vm targetvm https://www.qubes-os.org/
<html><meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>[user@sourcevm ~]$ 
```

And, again, in the TargetVM, only this shows up:

```
<meta HTTP-EQUIV="REFRESH" content="0; url=https://www.qubes-os.org/"/></html>
```

So, it looks like the first half of the `<html>` block is getting output in the SourceVM's terminal for some reason, while only the second half makes it to the TargetVM.

**Comment by andrewdavidwong** [comment]
Possibly related to changes in this commit: https://github.com/QubesOS/qubes-core-agent-linux/commit/19921274e1d677268c9fbee36bee41a8a3d2fb18

**Comment by marmarek** [comment]
Actually there is a bug in parent of this commit. The one you've pointed out is only in R3.2.

BTW the package was in testing repository for almost a month, do we have anyone using testing repository on R3.1?

**Comment by andrewdavidwong** [comment]
> Actually there is a bug in parent of this commit. The one you've pointed out is only in R3.2.

Ah, my mistake.

> BTW the package was in testing repository for almost a month, do we have anyone using testing repository on R3.1?

Probably not...

**Comment by andrewdavidwong** [comment]
>> BTW the package was in testing repository for almost a month, do we have anyone using testing repository on R3.1?

> Probably not...

I'll enable the testing repo on some daily-use-but-non-critical templates.

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `python2-dnf-plugins-qubes-hooks-3.1.18-1.fc21` has been pushed to the `r3.1` testing repository for the Fedora `fc21` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.1-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/3bff27460e9ee40d229b711d30dd506c8870cc02...193eb55330f79a4c20bd695ee25b27adf27e2a96

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `python2-dnf-plugins-qubes-hooks-3.1.18-1.fc22` has been pushed to the `r3.1` testing repository for the Fedora `fc22` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.1-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/3bff27460e9ee40d229b711d30dd506c8870cc02...193eb55330f79a4c20bd695ee25b27adf27e2a96

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `python2-dnf-plugins-qubes-hooks-3.1.18-1.fc23` has been pushed to the `r3.1` testing repository for the Fedora `fc23` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.1-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/3bff27460e9ee40d229b711d30dd506c8870cc02...193eb55330f79a4c20bd695ee25b27adf27e2a96

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-agent_3.1.18-1+deb8u1` has been pushed to the `r3.1` testing repository for the Debian `jessie` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `jessie-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/5518828c59f13b0eb8b05872f827296061b408a1...193eb55330f79a4c20bd695ee25b27adf27e2a96

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-agent_3.1.18-1+deb9u1` has been pushed to the `r3.1` testing repository for the Debian `stretch` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `stretch-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/5518828c59f13b0eb8b05872f827296061b408a1...193eb55330f79a4c20bd695ee25b27adf27e2a96

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-agent_3.1.18-1+deb7u1` has been pushed to the `r3.1` testing repository for the Debian `wheezy` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `wheezy-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/5518828c59f13b0eb8b05872f827296061b408a1...193eb55330f79a4c20bd695ee25b27adf27e2a96

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `python2-dnf-plugins-qubes-hooks-3.1.18-1.fc21` has been pushed to the `r3.1` stable repository for the Fedora `fc21` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/3bff27460e9ee40d229b711d30dd506c8870cc02...193eb55330f79a4c20bd695ee25b27adf27e2a96

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `python2-dnf-plugins-qubes-hooks-3.1.18-1.fc22` has been pushed to the `r3.1` stable repository for the Fedora `fc22` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/3bff27460e9ee40d229b711d30dd506c8870cc02...193eb55330f79a4c20bd695ee25b27adf27e2a96

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `python2-dnf-plugins-qubes-hooks-3.1.18-1.fc23` has been pushed to the `r3.1` stable repository for the Fedora `fc23` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/3bff27460e9ee40d229b711d30dd506c8870cc02...193eb55330f79a4c20bd695ee25b27adf27e2a96

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-agent_3.1.18-1+deb8u1` has been pushed to the `r3.1` stable repository for the Debian `jessie` template.
To install this update, please use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/5518828c59f13b0eb8b05872f827296061b408a1...193eb55330f79a4c20bd695ee25b27adf27e2a96

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-agent_3.1.18-1+deb9u1` has been pushed to the `r3.1` stable repository for the Debian `stretch` template.
To install this update, please use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/5518828c59f13b0eb8b05872f827296061b408a1...193eb55330f79a4c20bd695ee25b27adf27e2a96

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-agent_3.1.18-1+deb7u1` has been pushed to the `r3.1` stable repository for the Debian `wheezy` template.
To install this update, please use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/5518828c59f13b0eb8b05872f827296061b408a1...193eb55330f79a4c20bd695ee25b27adf27e2a96
