### ISSUE TITLE
[doc] Missing vm-to-vm Firewall Instructions

### ISSUE THREAD

**Issue by xloem** [QubesOS/qubes-issues#2206]
#### Qubes OS version (e.g., `R3.1`):

R3.1
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):

fedora-23

---
### Expected behavior:

Set up communication between two vms.
### Actual behavior:

Vms cannot communicate due to missing instructions.
### Steps to reproduce the behavior:

Visit https://www.qubes-os.org/doc/qubes-firewall/ and follow instructions for "Enabling networking between two VMs".
### General notes:

In addition to the instructions listed, a hole must be poked in the firewall of the service VM itself, not just the network VM.

---

**Comment by andrewdavidwong** [comment]
Please feel free to submit a pull request for this.

**Comment by xloem** [comment]
Okay: https://github.com/QubesOS/qubes-doc/pull/173

**Comment by andrewdavidwong** [comment]
Merged: https://github.com/QubesOS/qubes-doc/commit/8b488234ebe13da95e32b8482d061183e6e403ec
