### ISSUE TITLE
Enhance qubes-hcl-report tool

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#2214]
It would be useful to check for:
- [x] SLAT - see #2185 (`xl dmesg | grep 'Extended Page Tables'`, probably something similar on AMD) 
- [ ] Interrupt remapping (`xl dmesg | grep 'Interrupt remapping enabled'`)
- [ ] number of USB controllers especially when keyboard is USB-connected

**Comment by unman** [comment]
@marmarek - cant this now be closed as tests were merged?
