### ISSUE TITLE
All program shortcuts for all VMs copied to "System Tools" menu

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#2217]
#### Qubes OS version (e.g., `R3.1`):

`R3.2-rc2`

All program shortcuts for all VMs were somehow copied (without subfolders) to the "System Tools" menu: [screenshot (only the beginning of the list)](https://i.imgur.com/3qk2Cl7.png)

[Reported](https://groups.google.com/d/msgid/qubes-users/e29b002c-13d1-b57e-b432-af6a70493d4b%40openmailbox.org) by @evadogstar

**Comment by andrewdavidwong** [comment]
I've also had this happen to me (with only a subset of all my shortcuts) on KDE on an earlier version (either R3.0 or R3.1, I think).

**Comment by JeramyNS** [comment]
Same issue here after upgrading from 3.1 to 3.2

**Comment by evadogstar** [comment]
@andrewdavidwong
bug can be hard fixed by running 
`qvm-receive-appmenus` for EVERY template available (or templates from which icons show at Settings Menu)

**Comment by andrewdavidwong** [comment]
@evadogstar: Did you mean `qvm-sync-appmenus`? The latter command is already run automatically after each TemplateVM is updated. CC @marmarek.

**Comment by evadogstar** [comment]
@andrewdavidwong Yes, but something goes wrong after update. To fix it need to run the command.

**Comment by evadogstar** [comment]
@andrewdavidwong Hmm, but it does not help for Windows 32 bit shortcuts at System Tools menu, because it's not possible to run `qvm-sync-appmenus` for template without windows tools installeted.

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
