### ISSUE TITLE
Error when creating VM with the VM Manager

### ISSUE THREAD

**Issue by kototama** [QubesOS/qubes-issues#2218]
#### Qubes OS version (e.g., `R3.1`):
3.2RC2

### Expected behavior:

I can create a VM in the VM Manager without error.

### Actual behavior:

When creating a VM with the graphical manager I got the following error:

ERROR: 'NoneType' object has no attribute 'qid'

#### Related issues:

Maybe related to  #2213 since the machine is in a state where default VMs were not created.

**Comment by andrewdavidwong** [comment]
Earlier report of the same error message from R3.0 (2015-08-30):
https://groups.google.com/d/topic/qubes-users/Roft9Z_Lh6I/discussion

**Comment by kototama** [comment]
I could not reproduce it after following the instruction from https://github.com/QubesOS/qubes-issues/issues/2213#issuecomment-237666098 or after successful reinstallation. 

Maybe the salt configuration was in a bad state?

**Comment by andrewdavidwong** [comment]
Ok, glad to hear the issue is resolved.
