### ISSUE TITLE
USB local printer passwd error using system-config-printer applet to add drivers

### ISSUE THREAD

**Issue by Kozuno** [QubesOS/qubes-issues#2221]
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable): fedora-23 (TemplateVM)
---
### Expected behavior:
Being able to install local printer drivers using system-config-printer applet

### Actual behavior:
Applet asks for user / password at the end of the config process, but it fails because AppVM doesn't have built-in root passwords

### Steps to reproduce the behavior:
I followed this documentation : https://www.qubes-os.org/doc/fedora-minimal-template-customization/
and entered in terminal "sudo dnf install system-config-printer system-config-printer-applet cups".
Then "lsusb" to list my device then noted the URI of my printer, added it into the system-config-printer applet add menu, then followed steps to my actual problem, where I am blocked

### General notes:
I followed the section "Replacing password-less root access with Dom0 user prompt" on this documentation to be able to have a root password and go through this error (I read somewhere unfortunately cups needs a user or root password in order to be able to install drivers) : https://www.qubes-os.org/doc/vm-sudo/
But because as I am a Qubes fresh nooblet I had then to reinstall Qubes, I didn't pay attention that this cmd makes you loose all dom0 sudo rights, LOL (didn't realized dom0 is also a VM t_t, I thought it wasn't emulated) "[root@dom0 /]# echo -n "$anyvm dom0 ask" >/etc/qubes-rpc/policy/qubes.VMAuth" 

So eventually to avoid mistakes I think it would be better to put the note below just before this latter cmd to warn people otherwise when you apply this procedure you are stuck, you cannot become sudoers in dom0 to go back and allow VMs of your choice to be password-less : "Note: any VMs you would like still to have password-less root access (e.g. TemplateVMs) can be specified in the second file with “<vmname> dom0 allow”)"
As I get this system error I didn't try to add again my drivers but if it is the only solution to my problem, I would appreciate your help a lot to add root or user password to a specific VM in order to make sure cups is working :)

**Comment by andrewdavidwong** [comment]
I think the sudo issue might be a red herring. I, too, recall briefly running into permissions issues when setting up a CUPS printer, but I never had to mess with sudo to get it to work. At the top, you mention `fedora-23`, but in your description, you say you used the minimal template. Have you actually tried with the full standard template?

**Comment by Kozuno** [comment]
Thank you for your answer. Yes I tried with the full standard fedora-23 template (TemplateVM) but also with fedora-23 Standalone TemplateVM or the normal AppVM that removes every file not in /home, /usr/local or /rw/config after rebooting the VM.
I don't really understand what causes my problem, I just got this CUPS user/ password prompt at the end of the configuration, after having selected my drivers, that fails (I got this msg :  "CUPS server error / There was an error during the CUPS operation : 'client-error-not-possible'), but as I said I guess the issue is caused by the fact VM are password-less.
Or maybe when I type "lsusb" this is the wrong hub, hm this is really strange my printer isn't that old, this is a PIXMA Canon that used to be recognized by the past ^^

Eventually I could try to install drivers into another HVM Linux distro img but I don't think problem comes from Fedora. So I went to Canon site, downloaded drivers, and tried to install using the install.sh script, but then I get 3 dependencies needed : libpangox-1.0.so.0() (64bit), libpng12.so.0() (64bit) and libtiff.so.3() (64bit), which is weird because for 2 of them when I type "sudo dnf install libpng libtiff" it says more recent version packages are already installed. Maybe it requires those specific packages to be installed but as I am a beginner on Linux that I discovered only 2 months ago and as I don't really know Fedora well (I started on Debian), if you know a simpler way to have my printer work, that would be great !

**Comment by andrewdavidwong** [comment]
> Maybe it requires those specific packages to be installed

Probably something like that.

> if you know a simpler way to have my printer work, that would be great !

Sorry, I don't. Getting printers to work on Linux is notoriously tricky. I'll leave this issue open, but in the mean time, can you try installing the printer on baremetal Fedora 23 or Debian 8 to see whether this is really a Qubes-specific issue?

**Comment by Kozuno** [comment]
I won't reinstall Qubes once again, but I just installed Debian 8 on a HVM template to make some tests from the documentation's help https://www.qubes-os.org/doc/hvm/ (I followed the "Using Installation ISOs located in other VMs" paragraph). I don't know if that's what you meant by baremetal, but it is close in a way ^^

Indeed, it might not be a Qubes-specific issue considering I have big troubles for my printer to be recognized by VMs for some reason (I can attach without issue let's say a USB key to a VM but I can't do the same with my printer).
But I just realized the URI I noted inside a VM using "lsusb" cmd wasn't the good one. When I type "lsusb" in Dom0 terminal, now I got the good ID, and I can be sure about it because I don't have other Canon hardware listed here. Looks like problem is more that I don't know how to attach this specific hardware to a VM in order to use it, lol.

**Comment by andrewdavidwong** [comment]
> I don't know if that's what you meant by baremetal, but it is close in a way ^^

By "baremetal" I mean installing regular Fedora or Debian directly on the hardware, not in a VM.

> But I just realized the URI I noted inside a VM using "lsusb" cmd wasn't the good one. When I type "lsusb" in Dom0 terminal, now I got the good ID, and I can be sure about it because I don't have other Canon hardware listed here. Looks like problem is more that I don't know how to attach this specific hardware to a VM in order to use it, lol.

Were you able to attach the correct device using the good ID? If not, at which point are you stuck?

**Comment by Kozuno** [comment]
> By "baremetal" I mean installing regular Fedora or Debian directly on the hardware, not in a VM.

Ok. Then I am sorry but the only reason why I would actually choose this option is the very urgent need to print or scan important documents, and even if I actually need to find a solution to this problem asap because I need to be able to scan documents, I will not leave Qubes for security reasons... I left Windows 3 months ago because I got hacked by a very serious threat, a rootkit, I then tried Qubes first but I had some stability issues with my graphics and it was a bit too much complicated for a Linux newcomer, then I tried Debian, then switched to run Linux Mint where I got hacked - probably an infected iso, so it was my bad - and I came back to Qubes recently with a verified iso that hopefully handles way better my graphics and my safety !
I would rather like install Mint very fast offline, scan or print documents, put them on a USB key, then go back on Qubes to use them, even if the procedure is rather long. I don't want to get hacked again and have my data compromised...
But I already know my printer works on Debian directly on the hardware, as I was running Debian 2 months ago with the same printer working (same for Linux Mint). Anyway I am so glad to have discovered Qubes recently, this is the best OS I have ever used, Joanna Rutkowska and all the people working around this project can be really proud of it, this is just awesome :) :+1: :100: 
Documentation is also very well written and clear, it is very interesting and helpful to understand how Qubes OS works. This is such a great project, I talked about it around me and I hope Qubes OS will be really popular in the future, that people realize how important it is to preserve your own digital security.

> Were you able to attach the correct device using the good ID? If not, at which point are you stuck?

No I was not able to attach the correct device using the good ID. My printer was not recognized in VMs, I had no Canon entry in terminal. But dom0 recognize well the printer, as when I type "lsusb" in dom0's terminal, I have then the correct device listed here with the good ID.

**Comment by andrewdavidwong** [comment]
> I'm stuck to the point I can't attach the printer to a VM by right clicking a VM then attach the device, if USB printers work exactly the same as USB keys.

No, you should not expect that to work like that. USB printers are not USB block devices. Please read this: https://www.qubes-os.org/doc/usb/

You should create a USB qube, assign (at least one of) your USB controller(s) to that USB qube, physically plug the USB printer into a USB port owned by that USB controller, then try to check for the existence of the printer in the USB qube. Alternatively, you can try using Wi-Fi, as you mentioned.

Either way, you need to make sure that you're installing all the correct software (drivers, packages) in the correct place. You can try installing the software directly into the USB qube at first just to test printer compatibility.

Also, I'm sorry, but I have to close this issue. This sort of external device troubleshooting (and unrelated chatter) is really not appropriate for qubes-issues. It is more appropriate for qubes-users. If you have an actual Qubes bug to report, then this is the right place, but this is not the right place to get help with setting up your printer.

**Comment by Kozuno** [comment]
Thank you very much for all your explanations. I am really sorry not having posted in the good section. I honestly didn't know about the fact USB printers are not considered as block devices and that you could create USB qubes. I should have checked this part of the documentation first, I really thought it was a password recognition problem on VMs and that the way USB devices work was they were added to dom0 as isolated partitions, not currently visible for users (like some complex built-in implementation from Qubes developpers), then you could assign them safely, but I was completely wrong. Sorry again for taking your time and thanks a lot for your help, now I know what I have to do, create a USB qube, but also mostly think twice before posting here, like be certain about if issue I encounter is related to my ignorance on documentation as a Qubes newcomer or as a real Qubes developpement problem. I think I am gonna read the whole documentation very soon to avoid this kind of disturbance, because with all the security issues I had before joining Qubes OS (rootkits...), I am very thankful to people that made this possible.

**Comment by andrewdavidwong** [comment]
@Kozuno Thanks for understanding. I appreciate your enthusiasm about Qubes. :)

**Comment by Kozuno** [comment]
:) Thank you, I also appreciated your help, even if I am really retarded, almost like an hopeless case...
Because indeed all I had to do was follow "Finding the right USB controller" here https://www.qubes-os.org/doc/assigning-devices/, attach my printer as if it was a PCI card on a TemplateVM... 
Obviously Qubes would not make sense if different hardware parts of your computer were not isolated from VMs. Omg, I am ashamed :S Next time don't waste your time with my pathetic life, just say : RTFM, n00b ! ~¬ ><;
I am confused because I lost my sister few days ago. I wasn't very close to her, but this really sad for my (young) nephews and his husband. Yes I am enthusiastic, this is true, and I think even if I wasn't close to her for complicated reasons, this is clearly one of the personality traits that I shared with her, so I really appreciate you said this. RIP sister. You fighted till the end with courage. I am proud of you wherever you are.

**Comment by andrewdavidwong** [comment]
> :) Thank you, I also appreciated your help, even if I am really retarded, almost like an hopeless case...
Because indeed all I had to do was follow "Finding the right USB controller" here https://www.qubes-os.org/doc/assigning-devices/, attach my printer as if it was a PCI card on a TemplateVM... 

Ok, glad you were able to find what you were looking for.

> Obviously Qubes would not make sense if different hardware parts of your computer were not isolated from VMs. Omg, I am ashamed :S Next time don't waste your time with my pathetic life, just say : RTFM, n00b ! ~¬ ><;

Haha, no, it's ok.

> I am confused because I lost my sister few days ago. I wasn't very close to her, but this really sad for my (young) nephews and her husband. Yes I am enthusiastic, this is true, and I think even if I wasn't close to her for complicated reasons, this is clearly one of the personality traits that I shared with her, so I really appreciate you said this. RIP sister. You fighted till the end with courage. I am proud of you wherever you are.

I'm so sorry for your loss. :(
