### ISSUE TITLE
Massive power usage for trackpad

### ISSUE THREAD

**Issue by thomwiggers** [QubesOS/qubes-issues#2225]
#### Qubes OS version (e.g., `R3.1`):
R3.2rc2

---
When moving the mouse pointer using my trackpad on a Dell XPS 13 9350, powertop notes a massive spike in power usage and increase in interrupts by idma64.1. This results in over 4W extra power usage.

This drops the powertop expected battery life for my laptop from an already bad (compared to Arch Linux) 6 hours to less than 4 hours (while only running the sys-{firewall,net,usb} vms, having terminated qubes-manager  (#1253), otherwise doing nothing).

Otherwise support for this system is massively improved since the last time I tried qubes, kudos.

---

**Comment by andrewdavidwong** [comment]
How does it compare to baremetal Fedora 23?

**Comment by thomwiggers** [comment]
i don't know, I'll try grabbing a liveusb and try it out.

**Comment by thomwiggers** [comment]
The Fedora 24 liveusb reports similar interrupt levels, but not the associated power usage spike...

And now I can't reproduce it when I retry in Qubes. Weird.... The baseline power usage still is a lot higher though.

**Comment by thomwiggers** [comment]
Oh, as a question: is there a way to get kernel 4.6 or 4.7 into Qubes? It's got loads better support for the XPS 13.

**Comment by thomwiggers** [comment]
Oh, I did install libinput into qubes before I rebooted, maybe that was related...

**Comment by andrewdavidwong** [comment]
> Oh, as a question: is there a way to get kernel 4.6 or 4.7 into Qubes?

If either one is available from the repos, then you can follow the procedure [here](https://www.qubes-os.org/doc/software-update-dom0/#tocAnchor-1-1-3) (under "Kernel Upgrade"). If not, then it won't be easy, but you can try the procedure described [here](https://groups.google.com/d/msg/qubes-users/m8sWoyV58_E/HYdReRIYBAAJ)
