### ISSUE TITLE
build Qubes-Whonix 13.0.0.1.0 templates for R3.2 final

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#2228]
Please build Qubes-Whonix 13.0.0.1.0 templates for R3.2 final (or next RC should there be also R3.2r3).

qubes-template-whonix tag 13.0.0.1.0

It's supposed to be a stable upgrade. Containing all upgrades mentioned in https://www.whonix.org/blog/testers-wanted-repo-upgrades and would also come without any #2191 issues.

After it has been build, I need to verify it's working fine before it can become the new latest stable.

**Comment by adrelanos** [comment]
It should be build using R3.2 testing.

**Comment by marmarek** [comment]
Done.
Build logs:

- [template-jessie+whonix-gateway+minimal+no-recommends.log](https://gist.github.com/207cf9dc13504a12304616058fc79e92)
- [template-jessie+whonix-workstation+minimal+no-recommends.log](https://gist.github.com/5c0d9a96a05ab69756d5f5c2ba52ce41)

Packages in R3.2 unstable repo:

- qubes-template-whonix-gw-3.0.6-201608050041.noarch.rpm
- qubes-template-whonix-ws-3.0.6-201608050146.noarch.rpm

**Comment by adrelanos** [comment]
Seems to work well so far.

`Qubes-Whonix 13.0.0.1.0 TemplateVMs - Testers Wanted!`
https://www.whonix.org/blog/qubes-whonix-13-0-0-1-0-testers-wanted

Let's leave this ticket open until testing is done? Sometime, perhaps at the end of next week. Depending on next R3.2 release date also. And let's leave this ticket open until you migrated it into qubes-templates-community?

**Comment by marmarek** [comment]
Ok.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by adrelanos** [comment]
No bug reports.

Please merge into community and close.

**Comment by marmarek** [comment]
Done :)
