### ISSUE TITLE
Add "QubesIncoming" shortcut to left pane of Nautilus "File Chooser"

### ISSUE THREAD

**Issue by kbrn** [QubesOS/qubes-issues#2229]
#### Qubes OS version (e.g., `R3.1`):

Any
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):

fedora-23, debian-8

---
### Expected behavior:

To have "QubesIncoming" shortcuts in Nautilus "File Chooser"'s left pane, along with "user", "Desktop", "File System", etc.
### Actual behavior:

Does not have it.
### General notes:

I find myself always having to clumsily navigate home, then to QubesIncoming.  Seems Nautilus on Qubes should assume frequent navigation to that folder.

---

**Comment by andrewdavidwong** [comment]
I can see how this might be useful, but it seems to depend on personal preference. @bnvk, do you think this would be a good idea?

**Comment by jpouellet** [comment]
Adding `file:///home/user/QubesIncoming` to `~/.config/gtk-3.0/bookmarks` is sufficient to achieve this:
![nautilus-qubesincoming](https://cloud.githubusercontent.com/assets/1231207/24556037/14bb8fc8-1601-11e7-964d-6cccff9ceb1d.png)

Putting it in the upper "permanent" part and giving it a nice little Qubes icon would require patching:
- https://github.com/GNOME/nautilus/blob/bb433582165da10ab07337d707ea448703c3865f/src/nautilus-icon-names.h
- https://github.com/GNOME/nautilus/blob/533f828d4d4dcbd44540a9403b80d793153428e3/src/nautilus-file-utilities.c#L726-L749

**Comment by jpouellet** [comment]
We do not currently patch Nautilus at all, so IMHO I don't think the fancier way is worth the extra maintenance cost.

**Comment by andrewdavidwong** [comment]
I don't think it should be added there by default. At *most*, we could document this so that users can do it on their own.

**Comment by jpouellet** [comment]
> I don't think it should be added there by default. At most, we could document this so that users can do it on their own.

I'm not a UX person, and I'm happy to defer to those who are, but I don't see why not. It's likely regularly accessed by many and I think can be considered a well-known standard dir in Qubes.

We already add Qubes-specific things like menu items for "{Copy,Move} To Other AppVM...", and I think this makes sense as a corresponding receiving-side efficiency/ease-of-use improvement. No?

**Comment by andrewdavidwong** [comment]
> I'm not a UX person, and I'm happy to defer to those who are, but I don't see why not. It's likely regularly accessed by many and I think can be considered a well-known standard dir in Qubes.

I don't see why those should be the deciding criteria. (Maybe they should be, but I don't see why they should be.)

> We already add Qubes-specific things like menu items for "{Copy,Move} To Other AppVM...", and I think this makes sense as a corresponding receiving-side efficiency/ease-of-use improvement. No?

Maybe, but I would find it annoying and immediately remove it. There have been suggestions about auto-deleting the QubesIncoming dir when empty, so clearly there are users who choose not to keep that dir around. It would be strange to have a broken shortcut by default.

**Comment by andrewdavidwong** [comment]
(Note that it would be broken by default for everyone, since QubesIncoming doesn't exist until some file is copied/moved into that VM.)

**Comment by kbrn** [comment]
Why auto-delete QubesIncoming?  To make it more difficult to determine that the system is Qubes?  If so, it seems a pointless gesture when there are lots other infoleaks (e.g. kernel version).

Maybe the default should actually be to assume this directory exists, and to ensure the templates have empty QubesIncoming directories.

Why would you find it annoying?

**Comment by andrewdavidwong** [comment]
> Why auto-delete QubesIncoming? To make it more difficult to determine that the system is Qubes? If so, it seems a pointless gesture when there are lots other infoleaks (e.g. kernel version).

That's a different issue. I'm not arguing in favor of auto-deleting QubesIncoming (at least not here). I'm just pointing out that the suggestion has been made, which shows that at least some users choose not to keep the QubesIncoming dir around.

> Maybe the default should actually be to assume this directory exists, and to ensure the templates have empty QubesIncoming directories.

Maybe, but that would be an additional change from the current default.

> Why would you find it annoying?

Oh, it's just personal preference. I just don't like having any extra or empty directories or shortcuts in most of my VMs.

**Comment by jpouellet** [comment]
FWIW, when you remove the other empty dirs you may not want (Music, Pictures, Videos, etc.) they too still appear in the bookmarks bar. (At least as observed on my system with nautilus-3.20.4-1.)

**Comment by andrewdavidwong** [comment]
> FWIW, when you remove the other empty dirs you may not want (Music, Pictures, Videos, etc.) they too still appear in the bookmarks bar. (At least as observed on my system with nautilus-3.20.4-1.)

You can permanently remove those through Nautilus (and/or editing the relevant files).

> Oh, it's just personal preference. I just don't like having any extra or empty directories or shortcuts in most of my VMs.

BTW, I'm not suggesting here that we should do anything based on *my* preference. In fact, I'm suggesting the opposite: We shouldn't do anything based on *anyone's* mere preferences. Instead, we should act in a more principled, objective way, whether that's deferring to UX experts, keeping the upstream distro's defaults, or just presenting a solid argument one way or the other (that doesn't appeal to preferences).

**Comment by andrewdavidwong** [comment]
(Updated labels and milestone to reflect what actually happened. Looks like it was not implemented merely as a documentation task after all. I had to use the 4.1 updates milestone, since the 4.1 milestone is now closed, but everything else should now be accurate. I had forgotten about this issue and opened #7640, in which Marek pointed me back here.)

**Comment by andrewdavidwong** [comment]
#10079 reports that this is not implemented/working in Qubes 4.3.

**Comment by marmarek** [comment]
TBH, I don't like reopening old feature issues that were already implemented and working correctly. Issue history gets confusing (most comments will be about how to implement it in the first place, not why it stopped working), and the state is confusing too (for example in which version the feature got included initially). Reopening makes sense if initial version (or fix for some bug - in case of "type: bug") didn't in fact worked, was not completed etc. If it stopped working later, it's better to open a new "bug" issue.

**Comment by andrewdavidwong** [comment]
Okay, sounds good. Opened #10081 instead.
