### ISSUE TITLE
Graphic woes / i915 - Intel Graphics 5500 on T450s

### ISSUE THREAD

**Issue by taradiddles** [QubesOS/qubes-issues#2232]
#### Problem:

After upgrading to rc2 I sometimes get screen freezes requiring a hard reboot. Last time it happened a small region of the screen got corrupted and then the laptop froze. At the next boot /sys/.../drm/card0/error was empty and nothing noticeable in the logs.
It happened 3 times since I've upgraded last week but I can't think of any pattern (last time it hapenned I was opening a libreoffice document).

Another thing I see that wasn't present in R3.1 is when starting an app in a vm after a reboot: the app window is "unrolled" from the top to the bottom in 1-2 seconds. Subsequent starts are snappy.  This happens only for the first app started though ; other apps are then starting OK.

The laptop is a Thinkpad T450s with Intel HD graphics 5500.  @andrewdavidwong mentioned he had the same hardware, it would be interesting to know if he encounters the same problems.

Any debugging pointers welcome.

Notes:
- I upgraded to 3.2rc2 with yum upgrade.
- bare fc23 used to work well on that laptop a few months ago, but maybe the problem is with the updated kernel.

**Comment by andrewdavidwong** [comment]
I haven't tried `R3.2-rc2` on that hardware yet. You mentioned that you used `yum upgrade` to upgrade to to `R3.2-rc2`. Do you mean that you did an [in-place upgrade from R3.1](https://www.qubes-os.org/doc/upgrade-to-r3.2/)? If so, you might want to try doing a clean reinstall, just to be sure.

**Comment by taradiddles** [comment]
Yes, I meant I did an in-place upgrade.
OK, I'll try to do a clean install when I have some spare time.

**Comment by taradiddles** [comment]
A little followup after the -rc3 release: since I created that issue I didn't have any screen freezes ; go figure... That said, I still have the "unrolling window" problem after boot, but also noticed that the same thing happens when plugging an external monitor. I could try to do/upload a video if that helps.
No time to do a clean install yet :(

**Comment by andrewdavidwong** [comment]
Sure, a video could be helpful for understanding the problem.

**Comment by taradiddles** [comment]
fyi I don't encounter the problem anymore for some time already - don't remember what solved it though (bios upgrade, qubes update, ...)
-> closing
