### ISSUE TITLE
Use maximized instead of full screen by default for Windows VM with QWT installed

### ISSUE THREAD

**Issue by rootkovska** [QubesOS/qubes-issues#2235]
We have recently decided to ditch the GUI seamless mode for QWT, as there are still multiple problems that we cannot solve. The new default will be to use the full desktop mode. However, for ease of navigation (switching between the Windows HVM and the rest of the system) the default mode should use maximized window (e.g. Dom0's taskbar visible) as opposed to full screen window mode (which is preemtable only by magic Alt-Tab or other Dom0 WM shortcuts, something new users might figure out easily).

Furthermore, in order to assist in any potential problem that might arise during a Windows VM boot up (such as a question asking user to choose Normal vs. Safemode start), we should now always be displaying the screen that previously was only shown when "Run in Debug mode" was selected. But I think we should remove/hide this window once qrexec & gui protocols connect (and might show it again/unhide) when a problem occurs?

**Comment by marmarek** [comment]
What do you mean by "as opposed to full screen window mode" ? Isn't it exactly what is currently implemented? I though windows in non-seamless starts in normal window...
Anyway, I would go a little further - start HVM in normal-sized window - not even maximized. And if the user want to maximize it, can do this using a button on dom0 decoration (or appropriate key combo).

> we should now always be displaying the screen that previously was only shown when "Run in Debug mode" was selected.

Ok. This is currently the case when `guiagent_installed=False`, but it is switched to `True` automatically later.

**Comment by omeg** [comment]
Already implemented in QubesOS/qubes-gui-agent-windows@23378ea
It is maximized, not full-screen (only seamless mode sends "true full-screen" WM hints for windows).

**Comment by rootkovska** [comment]
Indeed, I have got enable_fullscreen set for this VM. Otherwise (which is default) the window is presented fine.
