### ISSUE TITLE
Some system tray icons appear as big-ass blocks onscreen

### ISSUE THREAD

**Issue by Rudd-O** [QubesOS/qubes-issues#2247]
R3.2, latest -current packages, system tray icons either do not show up altogether, or show up as preposterously large blocks.  I do not understand why that happens.

See screenshot of one of those tray icons.  Note there is no window border, or way to resize them.  This is the icon of the app in question, and it has a context menu as you would expect.  NetworkManager icons are not showing in the tray at all.

![ay](https://cloud.githubusercontent.com/assets/346306/17645582/556a7bbe-6199-11e6-8934-af7f617b3d6f.png)

**Comment by marmarek** [comment]
Do you have "Notification area" applet in your panel (I'm assuming Xfce, is it correct?)?

**Comment by Rudd-O** [comment]
I did.

I rebooted and the problem is gone.  Sorry, can't reproduce it anymore.  I think a batch of updates prior to the reboot seems to have solved it.
