### ISSUE TITLE
Append-only build log

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#2251]
[HW42 has generously submitted a patch for this](https://groups.google.com/d/msgid/qubes-devel/491be700-6772-5db6-4b7f-1571df969e9f%40ipsumj.de) based on the proposal in the post [Security challenges for the Qubes build process](https://www.qubes-os.org/news/2016/05/30/build-security/).

This issue is just to allow for [`qubes-builder-github`](https://github.com/QubesOS/qubes-builder-github) to have a way to track the implementation of this feature.

**Comment by marmarek** [comment]
Duplicate of #2023

**Comment by andrewdavidwong** [comment]
Sorry about that, @marmarek. Transferring comment and tracker to the correct issue.
