### ISSUE TITLE
automatically restarting a VM via manager doesn't continue if kill/wait dialog pops up

### ISSUE THREAD

**Issue by 0spinboson** [QubesOS/qubes-issues#2254]
#### Qubes OS version (e.g., `R3.1`):

R3.2rc2; may affect more versions.
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):

involves QVM Manager

---

When restarting a VM, once the kill/wait time-out dialog comes up during shutdown, the Manager stops checking whether a VM has shut down properly. This can be a bit of a nuisance if the VM you are rebooting is sys-usb (while using a usb mouse+keyboard :) ).
### Expected behavior:

QVM Manager to keep checking (once every 20-30s?) whether the VM you've told the manager to restart has fully shut down.
### Actual behavior:

dialog box pops up, automatic checks cease. (It took me about 2 mins to find a keyboard with ps/2 connector, nothing happened in this period.)
### Steps to reproduce the behavior:

restart a VM that has been running for a while already.
### General notes:

I suspect that the main reason why I'm running into this issue is that I am (at least for the moment) running Qubes off an older magnetic drive.

**Comment by marmarta** [comment]
It looks like it should be fixed in R3.2 stable, and in R4.0 is done completely differently with the new qui-domains widget and also should work in the reworked qube manager.
