### ISSUE TITLE
"qvm-block --attach --ro" attaches read-write

### ISSUE THREAD

**Issue by rustybird** [QubesOS/qubes-issues#2255]
#### Qubes OS version:

R3.1

#### Affected TemplateVMs:

fedora-23

---

### Expected behavior:

`qvm-block --attach --ro` attaches readonly.

### Actual behavior:

It attaches read-write.

### Steps to reproduce the behavior:

```
src-vm $ rm -f foo
src-vm $ truncate -s 10M foo
src-vm # losetup /dev/loop0 foo

dom0 $ qvm-block --attach --ro dst-vm src-vm:loop0
dom0 $ qvm-block --list
src-vm:loop0	/home/user/foo 10 MiB (attached to 'dst-vm' as 'xvdi')

dst-vm # echo bar >/dev/xvdi

dom0 $ qvm-block --detach src-vm:loop0

src-vm $ head -c 4 foo
bar
```

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-dom0-3.2.9-1.fc23` has been pushed to the `r3.2` testing repository for dom0.
To test this update, please install it with the following command:
```
sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-admin/compare/10c44e87221dfb5431934376648ce05855a63cda...0e24d803f5cdf563c2e9dd4b7280f9d3771ba45a

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-dom0-3.2.9-1.fc23` has been pushed to the `r3.2` stable repository for dom0.
To install this update, please use the standard update command:
```
sudo qubes-dom0-update
```
Or update dom0 via Qubes Manager.

[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-admin/compare/10c44e87221dfb5431934376648ce05855a63cda...0e24d803f5cdf563c2e9dd4b7280f9d3771ba45a

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-dom0-3.1.18-1.fc20` has been pushed to the `r3.1` testing repository for dom0.
To test this update, please install it with the following command:
```
sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-admin/compare/d8093f38c428e4a9e7be421f2dc57e0a45a19477...d315daf86a97b8ec899df237fcd8af76e223b91e

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-dom0-3.1.18-1.fc20` has been pushed to the `r3.1` stable repository for dom0.
To install this update, please use the standard update command:
```
sudo qubes-dom0-update
```
Or update dom0 via Qubes Manager.

[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-admin/compare/d8093f38c428e4a9e7be421f2dc57e0a45a19477...d315daf86a97b8ec899df237fcd8af76e223b91e
