### ISSUE TITLE
After new partitions created on second hard drive, Qubes VM Manager allows attaching entire drive to VM

### ISSUE THREAD

**Issue by greenrd** [QubesOS/qubes-issues#2260]
#### Qubes OS version (e.g., `R3.1`):

R3.1

---
### Expected behavior:

A new partition (at least, if it is not already mounted on dom0) should be offered as an option for attaching to VMs by Qubes VM Manager
### Actual behavior:

Entire new disk offered as an option for attaching to VMs by Qubes VM Manager. New partitions not offered as options for attaching - even after restarting Qubes VM Manager.
### Steps to reproduce the behavior:
1. Obtain new hard drive
2. Install hard drive into computer alongside existing drives
3. Boot
4. `sudo qubes-dom0-update kde-partionmanager`
5. `partitionmanager`
6. Create GPT partition table on new hard drive
7. Create 2 partitions on new hard drive
8. Apply changes
9. Exit
10. Add first partition to /etc/fstab
11. Mount first partition in dom0
12. Start a VM
13. Attempt to attach second partition to the VM.
### General notes:

After a dom0 reboot, the expected behaviour is seen. I'm guessing the new drive's partition table wasn't rescanned until dom0 was rebooted.

**Comment by andrewdavidwong** [comment]
> After a dom0 reboot, the expected behaviour is seen. I'm guessing the new drive's partition table wasn't rescanned until dom0 was rebooted.

Do I understand correctly that the solution to this issue is simply rebooting dom0? If so, what change are you suggesting?

**Comment by cyrinux** [comment]
Hi,
Maybe simply run 'partprobe' from dom0?

**Comment by greenrd** [comment]
I'm not sure what is causing this. Clearly the dom0 Linux kernel has seen the new partitions, because it can mount them, so I'm not sure why Qubes VM Manager doesn't notice them.

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
