### ISSUE TITLE
Qubes PDF converter fails on page merging for large documents

### ISSUE THREAD

**Issue by rootkovska** [QubesOS/qubes-issues#2261]
This is a limitation of the ImageMagic's convert which apparently is unable to merge a few hundred PDFs into a single document. Note this bug is not a security bug.

**Comment by marmarek** [comment]
@rootkovska do you remember number of pages to trigger this? Or maybe file size (input or output)? 
Or if that PDF is public, maybe you could post a link?

I'm trying to write a regression test for this and I can't reproduce the problem.

**Comment by rootkovska** [comment]
Try one of the Intel SDMs...

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-pdf-converter_2.1.1-1+deb8u1` has been pushed to the `r3.2` testing repository for the Debian `jessie` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `jessie-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-pdf-converter/compare/193d70377e2597cbbad061a5380a04204d674b49...5c147f18c06ebfd74cdb382386427137392960d6

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-pdf-converter_2.1.1-1+deb9u1` has been pushed to the `r3.1` testing repository for the Debian `stretch` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `stretch-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-pdf-converter/compare/193d70377e2597cbbad061a5380a04204d674b49...5c147f18c06ebfd74cdb382386427137392960d6

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-pdf-converter_2.1.1-1+deb9u1` has been pushed to the `r3.2` testing repository for the Debian `stretch` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `stretch-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-pdf-converter/compare/193d70377e2597cbbad061a5380a04204d674b49...5c147f18c06ebfd74cdb382386427137392960d6

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-pdf-converter_2.1.1-1+deb7u1` has been pushed to the `r3.1` testing repository for the Debian `wheezy` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `wheezy-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-pdf-converter/compare/193d70377e2597cbbad061a5380a04204d674b49...5c147f18c06ebfd74cdb382386427137392960d6

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-pdf-converter-2.1.1-1.fc23` has been pushed to the `r3.2` testing repository for the Fedora `fc23` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.2-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-pdf-converter/compare/193d70377e2597cbbad061a5380a04204d674b49...5c147f18c06ebfd74cdb382386427137392960d6

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-pdf-converter-2.1.1-1.fc24` has been pushed to the `r3.2` testing repository for the Fedora `fc24` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.2-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-pdf-converter/compare/193d70377e2597cbbad061a5380a04204d674b49...5c147f18c06ebfd74cdb382386427137392960d6

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-pdf-converter-dom0-2.1.1-1.fc23` has been pushed to the `r3.2` testing repository for dom0.
To test this update, please install it with the following command:
```
sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-pdf-converter/compare/193d70377e2597cbbad061a5380a04204d674b49...5c147f18c06ebfd74cdb382386427137392960d6

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-pdf-converter-2.1.1-1.fc21` has been pushed to the `r3.1` testing repository for the Fedora `fc21` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.1-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-pdf-converter/compare/193d70377e2597cbbad061a5380a04204d674b49...5c147f18c06ebfd74cdb382386427137392960d6

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-pdf-converter-2.1.1-1.fc22` has been pushed to the `r3.1` testing repository for the Fedora `fc22` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.1-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-pdf-converter/compare/193d70377e2597cbbad061a5380a04204d674b49...5c147f18c06ebfd74cdb382386427137392960d6

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-pdf-converter-2.1.1-1.fc23` has been pushed to the `r3.1` testing repository for the Fedora `fc23` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.1-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-pdf-converter/compare/193d70377e2597cbbad061a5380a04204d674b49...5c147f18c06ebfd74cdb382386427137392960d6

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-pdf-converter-dom0-2.1.1-1.fc20` has been pushed to the `r3.1` testing repository for dom0.
To test this update, please install it with the following command:
```
sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-pdf-converter/compare/193d70377e2597cbbad061a5380a04204d674b49...5c147f18c06ebfd74cdb382386427137392960d6

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-pdf-converter-2.1.1-1.fc23` has been pushed to the `r3.2` stable repository for the Fedora `fc23` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-pdf-converter/compare/193d70377e2597cbbad061a5380a04204d674b49...5c147f18c06ebfd74cdb382386427137392960d6

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-pdf-converter-2.1.1-1.fc24` has been pushed to the `r3.2` stable repository for the Fedora `fc24` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-pdf-converter/compare/193d70377e2597cbbad061a5380a04204d674b49...5c147f18c06ebfd74cdb382386427137392960d6

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-pdf-converter-dom0-2.1.1-1.fc23` has been pushed to the `r3.2` stable repository for dom0.
To install this update, please use the standard update command:
```
sudo qubes-dom0-update
```
Or update dom0 via Qubes Manager.

[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-pdf-converter/compare/193d70377e2597cbbad061a5380a04204d674b49...5c147f18c06ebfd74cdb382386427137392960d6

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-pdf-converter-2.1.1-1.fc21` has been pushed to the `r3.1` stable repository for the Fedora `fc21` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-pdf-converter/compare/193d70377e2597cbbad061a5380a04204d674b49...5c147f18c06ebfd74cdb382386427137392960d6

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-pdf-converter-2.1.1-1.fc22` has been pushed to the `r3.1` stable repository for the Fedora `fc22` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-pdf-converter/compare/193d70377e2597cbbad061a5380a04204d674b49...5c147f18c06ebfd74cdb382386427137392960d6

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-pdf-converter_2.1.1-1+deb8u1` has been pushed to the `r3.2` stable repository for the Debian `jessie` template.
To install this update, please use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-pdf-converter/compare/193d70377e2597cbbad061a5380a04204d674b49...5c147f18c06ebfd74cdb382386427137392960d6

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-pdf-converter-2.1.1-1.fc23` has been pushed to the `r3.1` stable repository for the Fedora `fc23` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-pdf-converter/compare/193d70377e2597cbbad061a5380a04204d674b49...5c147f18c06ebfd74cdb382386427137392960d6

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-pdf-converter_2.1.1-1+deb8u1` has been pushed to the `r3.1` stable repository for the Debian `jessie` template.
To install this update, please use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-pdf-converter/compare/193d70377e2597cbbad061a5380a04204d674b49...5c147f18c06ebfd74cdb382386427137392960d6

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-pdf-converter-dom0-2.1.1-1.fc20` has been pushed to the `r3.1` stable repository for dom0.
To install this update, please use the standard update command:
```
sudo qubes-dom0-update
```
Or update dom0 via Qubes Manager.

[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-pdf-converter/compare/193d70377e2597cbbad061a5380a04204d674b49...5c147f18c06ebfd74cdb382386427137392960d6

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-pdf-converter_2.1.1-1+deb9u1` has been pushed to the `r3.2` stable repository for the Debian `stretch` template.
To install this update, please use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-pdf-converter/compare/193d70377e2597cbbad061a5380a04204d674b49...5c147f18c06ebfd74cdb382386427137392960d6

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-pdf-converter_2.1.1-1+deb9u1` has been pushed to the `r3.1` stable repository for the Debian `stretch` template.
To install this update, please use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-pdf-converter/compare/193d70377e2597cbbad061a5380a04204d674b49...5c147f18c06ebfd74cdb382386427137392960d6

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-pdf-converter_2.1.1-1+deb7u1` has been pushed to the `r3.1` stable repository for the Debian `wheezy` template.
To install this update, please use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-app-linux-pdf-converter/compare/193d70377e2597cbbad061a5380a04204d674b49...5c147f18c06ebfd74cdb382386427137392960d6
