### ISSUE TITLE
Consider changing qubes.VMShell DispVM default to "ask"

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#2269]
[On 2016-08-25 03:53, Arqwer wrote:](https://groups.google.com/d/msgid/qubes-users/5e1cb9a7-1cf3-4c8e-9d6c-084e5377ba4e%40googlegroups.com)

> Command qvm-run '$dispvm' xterm if called from an appVM will run xterm in a
> new dispVM. If attacker gained access to an appvm, he possibly can run
> script, that will create thousands of new dispVMs and freeze my computer. I
> don't like this. May be it's better to disable this functionality by default?

Users can already configure this by editing `/etc/qubes-rpc/policy/qubes.VMShell` and changing

```
$anyvm   $dispvm  allow
```

to

```
$anyvm   $dispvm  ask
```

I interpret the suggestion to be that we make "ask" the default (instead of the current "allow").

**Comment by marmarta** [comment]
In 4.1 we have VMExec with more granular settings and less permissive defaults (implemented here: https://github.com/QubesOS/qubes-core-admin/commit/9cc6050e7caaab96079ec9e1fa3b78c2650f3a14 ) Closing this.
