### ISSUE TITLE
XFCE4 Panel disappears after 2nd boot

### ISSUE THREAD

**Issue by JoeThielen** [QubesOS/qubes-issues#2285]
#### Qubes OS version (e.g., `R3.1`): 
R3.2-rc2

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):
dom0 - XFCE4

---

### Expected behavior:
The XFCE panel should not disappear.

### Actual behavior:
On first boot after Qubes install the XFCE panel was there and was functional.  On 2nd boot and thereafter it was not.

### Steps to reproduce the behavior:
NOTE:  I've only installed R3.2-rc2 once and this happened.  I've not since re-installed as I'm awaiting my download for R3.2-rc3 to finish so I can try that.  

1. Install Qubes R3.2-rc2.
(I'm downloading R3.2-rc3 but it's taking a very long time)
2. During install I created a user but unchecked the option for "Require a password to use this account".  I also unchecked the options for the Debian and other templates (Whonix?)
3. During initial setup I unchecked the option for "Create default application qubes".  I have a USB keyboard/mouse so the USB qube was not created.
4. After initial setup the first thing I did was to enable autologin by following these instructions:
https://groups.google.com/forum/#!topic/qubes-users/CTSzbNHSgBU
I set it up to log in as my created user without a password.
5. Reboot

Upon reboot the XFCE panel was gone.  It is not hidden, moving the mouse to the corners or along the edge does not bring it back.

I thought maybe my autologin changes caused it, so I went back and undid those changes, but still no XFCE panel on reboot.

### General notes:
I have updated both dom0 and fedora-23 system templates.

I'm able to start it manually by right-clicking on the desktop -> Applications -> System Tools -> Panel, but it gives me several warnings first:
- "No running instance of xfce4-panel was found", so I click the "Execute" button.
- "Modifying the panel is now allowed", there is only one option, the "Close" button.
The panel does show now after these two warnings are dealt with.

I can also get it to start on startup if I do Applications -> System Tools -> Session and Startup -> Application Autostart and add the XFCE4-panel in there.  I've discovered if I add the "-d" option XFCE4-panel will no longer issue the two warnings above so at least I'm back to a place where the panel is there on reboot without warnings.

---

**Comment by JoeThielen** [comment]
Note:  On the first boot I selected the "use default config" option regarding XFCE4-panel starting the first time.

**Comment by JoeThielen** [comment]
This does **not** appear to be an issue in R3.2-rc3.  I've rebooted it twice after install and the panel is still there now!

**Comment by andrewdavidwong** [comment]
> This does **not** appear to be an issue in R3.2-rc3. I've rebooted it twice after install and the panel is still there now!

Thanks for letting us know! Closing as resolved.
