### ISSUE TITLE
Cannot Download Fedora Minimal Template

### ISSUE THREAD

**Issue by sjug** [QubesOS/qubes-issues#2286]
#### Qubes OS version (e.g., `R3.1`):
3.2 RC 3

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):
fedora-23

---

### Expected behavior:
Run `sudo qubes-dom0-update qubes-template-fedora-23-minimal`
Template is downloaded.

### Actual behavior:
Command runs on 'sys-firewall', gives some output about total download size and installed size.
Final line of output is:
`Downloading packages: `
With a new blank line underneath, and no progress ever occurs after hours of "downloading." There is no speed indicator, no indication of any kind it is actually doing something. It just hangs like this.

### Steps to reproduce the behavior:
Run `sudo qubes-dom0-update qubes-template-fedora-23-minimal`
Wait for it to hang.

### General notes:
I would like to set up a minimal template, but it refuses to download. I have no network connectivity issues of any kind.

---

**Comment by andrewdavidwong** [comment]
It looks like `fedora-23-minimal` is in the repo: http://yum.qubes-os.org/r3.2/templates-itl/rpm/

Are you using the default `sys-firewall` as your UpdateVM? On which TemplateVM is it based? (You can check both in Qubes Manager.)

**Comment by sjug** [comment]
Hey @andrewdavidwong,

I am using the default sys-firewall as my UpdateVM which is based on fedora-23.
However, I have tried again and left it running for the past 8 hours and it actually did work. It just did not show *any* download progress or speed or anything for that time until it completed. Which it did eventually successfully download.

**Comment by andrewdavidwong** [comment]
The lack of a progress/speed indicator is normal. Glad to hear it eventually worked. If you were on a slow connection or the servers were under heavy load (or both), then that's probably why it took so long.

**Comment by sjug** [comment]
Thanks for your quick reply!
