### ISSUE TITLE
power manager "lock screen" on "lid closed" still suspends

### ISSUE THREAD

**Issue by xahare** [QubesOS/qubes-issues#2287]
#### Qubes OS version:

3.2-rc3
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):

N/A

---
### Expected behavior:

setting power manager to just lock the screen, without sleeping when you close the lid still locks the screen. this affects the plugged in setting, not the battery power setting.
### Actual behavior:

as above, but laptop sleeps
### Steps to reproduce the behavior:

in xfce, system tools/power manager/plugged in/ lid closed to "lock screen"
close the lid
### General notes:

setting power management to lock screen in battery mode does prevent sleep, even the system is plugged in. 

laptop is a lenovo x201t

---

**Comment by marmarek** [comment]
In short only battery mode settings are used, even when power supply is connected, right? Is power state properly detected (at least in terms of xfce4-power-manager icon)?

**Comment by adrelanos** [comment]
> Is power state properly detected (at least in terms of xfce4-power-manager icon)?

Correctly detected for me.

**Comment by andrewdavidwong** [comment]
Confirmed on R3.2 stable on a T450s.

**Comment by unman** [comment]
Currently using borrowed old laptop, vanilla 3.2, and I don't see this issue. Pretty sure my normal laptop also performs properly. Battery state properly detected and conforms to Xfce settings.

**Comment by dephekt** [comment]
I have this issue in Qubes 4.0 as described in #4505. To follow-up on @marmarek's question there, the power manager in the notification area shows the correct power status when the laptop is plugged in or on-battery, so I don't believe it's an issue with the status not being detected properly. It shows "Fully charged" when plugged in and "Discharging" when I unplug it.

If you need me to do additional troubleshooting or diagnostics, let me know and I'm happy to do it.

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 has reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.

**Comment by andrewdavidwong** [comment]
Actually, I see that @dephekt reports that this is happening on 4.0, and I'm also experiencing it on 4.0. Reopening.

**Comment by my-little-pseudonym** [comment]
I've encountered this issue with Qubes OS 4.0.4 on a Dell Latitude E6540.

**Comment by walliams** [comment]
For me this issue doesn't have a workaround in the battery settings. The settings just don't do anything. Close the lid and it sleeps like it or not. Qubes 4.0.4 on Lenovo T430.

**Comment by andrewdavidwong** [comment]
This problem has gone away for me on 4.1. Anyone else still experiencing it?

**Comment by 0x303** [comment]
still experiencing in 4.1
