### ISSUE TITLE
feel free to delete

### ISSUE THREAD

**Issue by 0spinboson** [QubesOS/qubes-issues#2289]
Never mind, just me being a nab. :)

**Comment by marmarek** [comment]
Quick check: are you sure you have it unmouted from dom0 (check `mount`
output)?

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by 0spinboson** [comment]
you are correct.
