### ISSUE TITLE
XFCE audio mixer bug - R3.2rc3

### ISSUE THREAD

**Issue by mfc** [QubesOS/qubes-issues#2291]
#### Qubes OS version (e.g., `R3.1`):

R3.2 rc3 (upgraded from R3.3 rc2)

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):

XFCE / dom0 / Fedora-23

---

### Expected behavior:

if you reduce audio mixer volume to 0%, and then increase to some amount (say 25%, 50%, 100%), you will hear audio

### Actual behavior / Steps to reproduce the behavior:

if you reduce audio mixer volume to 0%, and then increase to some amount (say 25%, 50%, 100%), you will not hear audio because the "Speaker" column will stay "muted" even though the other audio columns will go to "unmuted" as soon as the audio mixer goes over 0%.

### General notes:

current solution is to right-click on audio mixer, select `Run audio mixer`, and unmute `Speaker` column.

---

#### Related issues:

mentioned in qubes-users, confirmed locally: https://groups.google.com/d/msgid/qubes-users/1b2fcf0d-1825-4e4e-aa9e-2d67ee08a0a1%40googlegroups.com

**Comment by marmarek** [comment]
Same here. For a long time (3.0 at least). But you don't need to open
mixer app - middle-click on mixer applet is enough.

I think it may not be Qubes specific bug at all, but haven't looked if
upstream report for it exists.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by mfc** [comment]
> But you don't need to open mixer app - middle-click on mixer applet is enough.

not for me, middle-click mutes/unmutes `Master`, but `Speaker` stays muted.

> I think it may not be Qubes specific bug at all, but haven't looked if upstream report for it exists.

yep it is an upstream bug:
https://bugzilla.xfce.org/show_bug.cgi?id=8583
various mentions:
http://xfce.10915.n7.nabble.com/Problem-with-Sound-settings-td45048.html
http://forums.debian.net/viewtopic.php?t=115347
https://superuser.com/questions/388780/ubuntu-and-xfce-unmute-sound/620671

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `garcon-0.4.0-4.fc23` has been pushed to the `r3.2` testing repository for dom0.
To test this update, please install it with the following command:
```
sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-desktop-linux-xfce4/compare/e55a55f9c5068aec5b13ee36f3ef8fd7712b6209...7e95194d8c3332fca93d4f4c4739653d00f090be

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `garcon-0.4.0-4.fc23` has been pushed to the `r3.2` stable repository for dom0.
To install this update, please use the standard update command:
```
sudo qubes-dom0-update
```
Or update dom0 via Qubes Manager.

[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-desktop-linux-xfce4/compare/e55a55f9c5068aec5b13ee36f3ef8fd7712b6209...7e95194d8c3332fca93d4f4c4739653d00f090be
