### ISSUE TITLE
Old debian-8 and fedora-23 templates in R3.2 repo

### ISSUE THREAD

**Issue by rustybird** [QubesOS/qubes-issues#2292]
The R3.2 rc3 .iso has `qubes-template-debian-8-3.0.6-201608090120.noarch.rpm` and `qubes-template-fedora-23-3.0.6-201608081228.noarch.rpm`, but only older versions are up on http://yum.qubes-os.org/r3.2/templates-itl/rpm/.

Also, those two RPMs from the .iso are unsigned for some reason (just saying so you don't upload them as they are).

**Comment by marmarek** [comment]
Uploaded, thanks.
