### ISSUE TITLE
No support for keyboard in installer on Macs

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#230]
**Reported by joanna on 22 Apr 2011 22:17 UTC**
I tired it on a few Mac and on each Mac the installer couldn't support the keyboard. Perhaps this is a more generic problem of not supporting USB keyboard (Macs use USB keyboard)? Or perhaps our initrd for installer doesn't have all the required USB/HID modules? Or perhaps Xen is making problems?

Migrated-From: https://wiki.qubes-os.org/ticket/230

**Comment by BrainyBrian** [comment]
Ubuntu has mac support. Is there any way we can somehow take a patch from them or something?

**Comment by BrainyBrian** [comment]
https://bugs.launchpad.net/ubuntu/+source/linux/+bug/162083

Is how it is in ubuntu

**Comment by hakusaro** [comment]
Somewhat hilariously, this ticket is marked as wontfix despite the [system requirements page asking for patches to solve this](https://www.qubes-os.org/doc/system-requirements/). I'm guessing nobody cares anymore?

**Comment by unman** [comment]
@hakusaro I guess nobody cares because there have been many reports in the last couple of years on the mailing lists of people successfully installing Qubes on Macs, which suggests it should remain closed.
