### ISSUE TITLE
include GUI and audio configuration in Qubes Manager or other GUI interface

### ISSUE THREAD

**Issue by mfc** [QubesOS/qubes-issues#2304]
I couldn't find a ticket tracking this. The options available to the user in [GUI and audio configuration in dom0](https://www.qubes-os.org/doc/config-files/) should be available to the user through a GUI. The options are:
- allow_fullscreen
- allow_utf8_titles 
- secure_copy_sequence
- secure_paste_sequence
- windows_count_limit

**Comment by marmarta** [comment]
related: https://github.com/QubesOS/qubes-issues/issues/1059

**Comment by marmarta** [comment]
I think we should add the following:
- allow_fullscreen
- allow_utf8_titles
- windows_count_limit
to VM Settings/Advanced, and their defaults to Global Settings.

Copy/paste sequence should only be in Global Settings. If someone wants to descend into chaos of having different copy-paste sequences for different VMs, it's their choice, but we should not encourage it.
Also trayicon_mode to Global Settings, not sure if it should be in VM settings (maybe? but I'm tempted to leave it only in Global Settings).

**Comment by marmarta** [comment]
Also, the options added to VM settings should have an asterisk and a "needs VM restart" info if the VM is running.

**Comment by tzwcfq** [comment]
Option allow_fullscreen doesn't seem to work for me on Qubes 4.1. I've allowed fullscreen in Qubes Settings for my HVM and I can see related qvm-feature enabled:
`gui-allow-fullscreen       1`
But when I start HVM the window won't enter fullscreen automatically and I still need to press Alt+F11 to enter fullscreen.

**Comment by marmarek** [comment]
> But when I start HVM the window won't enter fullscreen automatically and I still need to press Alt+F11 to enter fullscreen.

That's a different feature. The "allow fullscreen" option is about allowing a single _application window_ from a qube to switch into fullscreen (like clicking fullscreen in youtube). The size and placement of HVM desktop window is separate and mostly depends on the graphics resolution set within the qube (and if no qubes tools are installed inside, Qubes has very little influence on it).

Having an option to automatically make a HVM desktop window full screen (if its size matches screen resolution) may be useful, but should be tracked separately - please open new issue for it.

**Comment by tzwcfq** [comment]
> That's a different feature

I remember that long time ago I've set allow_fullscreen option in guid.conf and Windows 7 HWM with Qubes Windows Tools installed entered fullscreen mode at start, but it seems that it was Qubes Video Driver from QWT that made it work.

> Having an option to automatically make a HVM desktop window full screen (if its size matches screen resolution) may be useful, but should be tracked separately - please open new issue for it.

I'll create a new issue for this option.
