### ISSUE TITLE
Reduce number of silly emails to the core devs

### ISSUE THREAD

**Issue by rootkovska** [QubesOS/qubes-issues#2305]
I imagine we can put some text immediately next to core team members bios (https://www.qubes-os.org/team/), very close to the "email" buttons, suggesting to mail qubes-users instead of the individual devs.

Or perhaps, better yet, consider not to list email addresses there at all? These addresses are still embedded within the pubkeys which should be enough for those few people doing some sort of verification, etc.

We shall then introduce: press@qubes-os.org and maybe: bussiness@qubes-os.org for business-related discussions?

Some of the team members, I somehow suspect, might -- out of fun or frustration -- occasionally respond with debatable dark humor (or some even more debatable variation) to the innocuous individuals who mistaken them for the 1st-tire technical support. This might clearly not be in the Project's Best Interest.

**Comment by andrewdavidwong** [comment]
Similar/duplicate: #2152

**Comment by mfc** [comment]
we have discussed having press@, business@, etc previously and I think it's a good idea. having text on the team page pointing users to qubes-users@ is also fine. 

I think not listing email addresses is a bad idea. if you don't want your email address listed that is fine, or if you want to list a different address that is fine. but that is your decision about the listing of your email address, and shouldn't impact how others' display their contact info.

**Comment by andrewdavidwong** [comment]
I agree with @mfc. I think it would be perfectly reasonable not to have @rootkovska's email address on that page (as well as not displaying the email addresses of anyone else who doesn't want to be contacted). However, I don't think removing *all* email addresses from the page is the right answer. For some of us, having an email address discoverable on that page is an important way to be reachable for project-related matters. (I occasionally receive helpful emails from community members that wouldn't make sense going through any other communications channel, for example.)

I don't have a strong opinion regarding the press@qubes-os.org and bussiness@qubes-os.org addresses. Having them would be fine and could be useful. Not having them would also be fine and would be fewer addresses and accounts to worry about.

**Comment by marmarek** [comment]
> I don't have a strong opinion regarding the press@qubes-os.org and bussiness@qubes-os.org addresses.

I've created them as aliases (groups):
press: Andrew, Marek
bussiness: Joanna, Michael

We can use them as they are now, modify them, or remove/ignore.

**Comment by mfc** [comment]
thanks for creating these Marek. btw it should be business@

**Comment by marmarek** [comment]
On Thu, Sep 15, 2016 at 07:32:39PM -0700, Michael Carbone wrote:
> thanks for creating these Marek. btw it should be business@

Fixed.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by andrewdavidwong** [comment]
Thanks, Marek. Feel free to add me to the business group too, if you like. I might be able to help with some inquiries.

**Comment by andrewdavidwong** [comment]
Added the new addresses to the Team page.

**Comment by mfc** [comment]
thanks andrew, looks great. I think we can close this? 

fyi marek I am happy to be on press@ as well in case I am able to chip in on any requests.
