### ISSUE TITLE
Simplify and improve the aestahics of the front page

### ISSUE THREAD

**Issue by rootkovska** [QubesOS/qubes-issues#2306]
1. Get rid of the big, blue, "Q" logo. It is redundant, as we already displaying a smaller blue "Q" in the menu/top bar. It also looks bad, b/c introduces unjustified asymmetry. Also it doesn't look good on the subtle (otherwise looking good) tetris-like lightgray background.

2. Move the "Qubes OS A reasonably secure operating system" text to the center.

3. While at it: consider removing the photo of Purism laptop from the main page.

**Comment by andrewdavidwong** [comment]
Related: #1833, #1460

**Comment by andrewdavidwong** [comment]
Related PR: https://github.com/QubesOS/qubesos.github.io/pull/41

**Comment by andrewdavidwong** [comment]
@rootkovska: If we remove the Purism laptop photo, we should just remove the whole section, since it looks bad without a photo, and the information is readily available from several other parts of the website.

**Comment by rootkovska** [comment]
Looks great, thanks!
