### ISSUE TITLE
Live USB MacBookPro8,2

### ISSUE THREAD

**Issue by tabenius** [QubesOS/qubes-issues#2307]
#### Qubes OS version (e.g., `R3.1`):
R3.1
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):

---

### Expected behavior:
boot live qubes
### Actual behavior:
on this MacBookPro8,2 which has refind I can choose to boot xen.efi or the vmlinuz.
if I boot using xen.efi the graphics will be distorted beyond comprehension, possibly incorrect screen width / offset, maybe I see an extremely flat skewed penguin
if I boot using the vmlinuz option I get the errors
  dracut: Scanning for all btrfs devices
  dracut Warning: /dev/root does not exist
I re-ran with the rd.debug option, dropped into a shell and saved the rdsosreport.txt

### Steps to reproduce the behavior:
  use a MacBookPro8,2 from ca 2011
  put qubes on USB-stick using
     dd if=Downloads/Qubes-R3.1-x86_64/Qubes-R3.1-x86_64.iso of=/dev/disk2 bs=50m
  reboot
  in the previously installed refind choose xen.efi or the penguin
### General notes:
[rdsosreport-2.txt](https://github.com/QubesOS/qubes-issues/files/465676/rdsosreport-2.txt)

---

**Comment by andrewdavidwong** [comment]
This question is too localized for `qubes-issues`. Please consider posting this to the `qubes-users` mailing list instead. (You can read more about our mailing lists [here](https://www.qubes-os.org/mailing-lists/).)

`qubes-users` is intended for these sorts of questions and receives much more traffic, which means that your question is more likely to receive a response there.

**Comment by murpyslaw** [comment]
@andrewdavidwong @tabenius I'm having the same issue. I don't think it's that localized. EFI boot not working.
Posted on reddit, will try stackoverflow: https://www.reddit.com/r/Qubes/comments/6lht1q/macbook82queboscanithappen/

**Comment by andrewdavidwong** [comment]
@murpyslaw: General EFI boot is not too localized (see [UEFI Troubleshooting](https://www.qubes-os.org/doc/uefi-troubleshooting/), but an issue specific to "MacBookPro8,2" is.
