### ISSUE TITLE
R3.1 - Fed23 - DisposableVM - Firefox - Web pages time out.

### ISSUE THREAD

**Issue by rowyourboat** [QubesOS/qubes-issues#2312]
Qubes OS version R3.1
Template Fedora 23

---
Disposable VM - Firefox cannot access internet.

### Expected behavior:
Web page to open, eg Facebook.com

### Actual behavior:
Timeouts.

### Steps to reproduce the behavior:
Run DisposableVM-Firefox, try to access any website.

### General notes:
All of my VMs can access the Internet as expected, with the exception of the disposable VM.
I will note here that I am using the mirage-firewall, but before you close this ticket, I want to reiterate that all other VMs function normally. What I would like to determine is what makes disposable VM different from the rest.

The error in the firewall guest.log is:
INF [net] Client 5 (IP: 10.138.4.2) ready
WRN [net] Error connecting client domain 5: "Assert_failure_client_eth.ml:29:2"

It has been noted that dispVMs are assigned to a separate subnet upon creation, in my case 10.138.x.x, while all other VMs are on 10.137.x.x.

Also, what is expected of the firewall to allow dispVMs to reach the internet?

---

#### Related issues:
https://github.com/talex5/qubes-mirage-firewall/issues/9

**Comment by marmarek** [comment]
Replied in talex5/qubes-mirage-firewall#9. Lets keep this issue in one place.
