### ISSUE TITLE
Nouveau crashing boot with Nvidia GPU

### ISSUE THREAD

**Issue by kewde** [QubesOS/qubes-issues#2314]
#### Qubes OS version (e.g., `R3.1`):
R3.1
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):

---

### Expected behavior:
A succesful boot after the GRUB menu
### Actual behavior:
I haven't been able to grab the logs of my drive, but I'm getting these exact errors:
https://bugs.freedesktop.org/show_bug.cgi?id=91722
### Steps to reproduce the behavior:
/
### General notes:
/

---

**Comment by andrewdavidwong** [comment]
This sounds like a problem with your specific hardware configuration. Such problems are too localized for `qubes-issues`. Please consider posting this to the `qubes-users` mailing list instead. (You can read more about our mailing lists [here](https://www.qubes-os.org/mailing-lists/).)

`qubes-users` is intended for these sorts of questions and receives much more traffic, which means that your question is more likely to receive a response there.

**Comment by kewde** [comment]
Don't lock it up just yet, I fixed it. Writing a small guide :+1:

**Comment by andrewdavidwong** [comment]
Ok, thanks! :+1:

**Comment by kewde** [comment]
Okay, so as I thought nouveau was not playing nice with the nvidia card.

ERROR in question (for SEO purposes):
`
nouveau E[  PGRAPH][0000:01:00.0] grctx template channel unload timeout
nouveau E[  PGRAPH][0000:01:00.0] failed to construct context
nouveau E[  PGRAPH][0000:01:00.0] init failed, -16
`

ANSWER:

1) At the grub screen, press the up or down arrow keys to select the grub stanza/entry in question.

2) Press the "E" key.

3) An editor will open up that will allow you to temporarily change the grub options for the next boot.

4) Press the down arrow key and move the cursor to the line after the line with the kernel options. The line with the kernel options might look something like:
`template code for now will reboot and enter real values`

5) Press the left/right arrow keys to position the cursor at the end of kernel options line.

6) Type in "nouveau.modeset=0 video=vesa:off" {without the quotes}

7) Press either the F10 key or Ctrl+X to start the boot process.

Credits: http://forums.debian.net/viewtopic.php?t=79797 updated to work with Qubes

**Then to make this change persistent, so your boot will always work**:
1) Open a terminal ('run command' then type 'terminal' and hit enter)

2) type following commands:
`cd /etc/default/
sudo nano grub`

3) Edit GRUB_CMDLINE_LINUX, add the following to it at the end:
`nouveau.modeset=0 rd.driver.blacklist=nouveau video=vesa:off`

4) ctrl + X and y to save the file

5) Compile the configuration file to something the bootloader can read
`sudo grub2-mkconfig -o /boot/grub2/grub.cfg`

Credits: https://www.qubes-os.org/doc/install-nvidia-driver/

Here is a quick guide to disabling it on-boot so you can change the configuration file on Qubes.

**Comment by kewde** [comment]
@andrewdavidwong you can close it now, finished it.

**Comment by andrewdavidwong** [comment]
@kewde, would you be willing to submit this as a PR against the [Nvidia Troubleshooting](https://github.com/QubesOS/qubes-doc/blob/master/troubleshooting/nvidia-troubleshooting.md) page?

**Comment by kewde** [comment]
@andrewdavidwong
Yes, I'll do that later thuis evening.

**Comment by andrewdavidwong** [comment]
Thanks for your PRs, @kewde! Is there anything else needed for this issue?

**Comment by kewde** [comment]
I don't have anything to add to this specific issue, feel free to close it.

**Comment by hairetdin** [comment]
@kewde thanks, it really helped me and works fine. There was a problem with the CentOS 7 installation.

**Comment by NL-TCH** [comment]
> Okay, so as I thought nouveau was not playing nice with the nvidia card.
> 
> ERROR in question (for SEO purposes):
> `nouveau E[  PGRAPH][0000:01:00.0] grctx template channel unload timeout`
> `nouveau E[  PGRAPH][0000:01:00.0] failed to construct context`
> `nouveau E[  PGRAPH][0000:01:00.0] init failed, -16`
> 
> ANSWER:
> 
> 1) At the grub screen, press the up or down arrow keys to select the grub stanza/entry in question.
> 
> 2) Press the "E" key.
> 
> 3) An editor will open up that will allow you to temporarily change the grub options for the next boot.
> 
> 4) Press the down arrow key and move the cursor to the line after the line with the kernel options. The line with the kernel options might look something like, I didn't type everything as it may differ from system to system:
> `module /vmlinux-4.1.13-9.pvops.qubes.x86_64 placeholder root=/dev/mapper/qubes_dom0-root ro  ... rhgb quiet`
> 
> 5) Press the left/right arrow keys to position the cursor at the end of kernel options line.
> 
> 6) Type in "nouveau.modeset=0 rd.driver.blacklist=nouveau video=vesa:off" {without the quotes}
> 
> 7) Press either the F10 key or Ctrl+X to start the boot process.
> 
> Credits: http://forums.debian.net/viewtopic.php?t=79797 updated to work with Qubes
> 
> **Then to make this change persistent, so your boot will always work**:
> 1) Open a terminal ('run command' then type 'terminal' and hit enter)
> 
> 2) type following commands:
> `cd /etc/default/`
> `sudo nano grub`
> 
> 3) Edit GRUB_CMDLINE_LINUX, add the following to it at the end:
> `nouveau.modeset=0 rd.driver.blacklist=nouveau video=vesa:off`
> 
> 4) ctrl + X and y to save the file
> 
> 5) Compile the configuration file to something the bootloader can read
> `sudo grub2-mkconfig -o /boot/grub2/grub.cfg`
> 
> Credits: https://www.qubes-os.org/doc/install-nvidia-driver/
> 

Mann this is why I love Linux.
You helped me in 2024!
Thanks a lot!

**Comment by kewde** [comment]
@NL-TCH and I'm still here too ❤️
