### ISSUE TITLE
Clarify VPN doc

### ISSUE THREAD

**Issue by tasket** [QubesOS/qubes-issues#2317]
Clarify language to address the issues some people had: Configuring without testing, mixing NM with the scripts, basic troubleshooting.
Also make the language less openvpn-specific so it is only shown as examples.

---

#### Related issues:
#1941

**Comment by ttasket** [comment]
Pull request - https://github.com/ttasket/qubes-doc/pull/1/commits/8b2b5aa3fd5dfcee3171726dc1e0c906685fda81

**Comment by andrewdavidwong** [comment]
Did you mean to submit this as a PR against https://github.com/QubesOS/qubes-doc/blob/master/configuration/vpn.md ?

**Comment by ttasket** [comment]
Yes, sorry. Have new PR.

**Comment by tasket** [comment]
Two formatting problems at https://www.qubes-os.org/doc/vpn/ ...

Step 4 has a multi-line code box that didn't render... lines run together.

The Usage section has an image that isn't displaying.

**Comment by andrewdavidwong** [comment]
@tasket: Fixed.

**Comment by andrewdavidwong** [comment]
@tasket: Anything else needed for this issue?

**Comment by tasket** [comment]
Nope. Thanks!
