### ISSUE TITLE
Consider using pulseaudio instead of volumed and mixer in Xfce4 dom0

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#2321]
[On 2016-09-07 02:54, Connor Page wrote:](https://groups.google.com/d/msgid/qubes-users/b2af979d-b61a-48d6-91e6-7a5fa66fb484%40googlegroups.com)
> volumed and mixer are not maintained by xfce team anymore [1]
> since audio relies on pulseaudio it would make sense to use pulseaudio plugin and key bindings in dom0.
> 
> [1] http://www.xfce.org/about/news/?post=1425081600
>

**Comment by rustybird** [comment]
Replacing xfce4-volumed/xfce4-mixer with xfce4-pulseaudio-plugin (and restarting) also fixes #2291

**Comment by marmarek** [comment]
Just tried, and indeed, it works!
I'll try to adjust default configuration.

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `garcon-0.4.0-4.fc23` has been pushed to the `r3.2` stable repository for dom0.
To install this update, please use the standard update command:
```
sudo qubes-dom0-update
```
Or update dom0 via Qubes Manager.

[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-desktop-linux-xfce4/compare/e55a55f9c5068aec5b13ee36f3ef8fd7712b6209...7e95194d8c3332fca93d4f4c4739653d00f090be
