### ISSUE TITLE
nm-applet runs in sys-net but nothing appears for the user to click on

### ISSUE THREAD

**Issue by jbwells** [QubesOS/qubes-issues#2323]
#### Qubes OS version (e.g., `R3.1`):
R3.2-rc2
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):
sys-net is using the fedora-23 TemplateVM

---

### Expected behavior:
A very small nm-applet window should show up in the panel.  Clicking on this window should bring up a menu showing available and choosing one should cause NetworkManager to try connecting to it.
### Actual behavior:
No such window shows up.  There is nothing to click on.  Running pstree in sys-net reveals nm-applet is running.  Running xlswindows in dom0 reveals a number of top level windows exist for nm-applet.  There are a number of small 10x10 windows supposedly near the top left corner but none are visible.  There is one bigger window whose geometry information claims it is off screen, above and to the left of the top left corner.  None of these windows appear to the user (me).
### Steps to reproduce the behavior:
Reboot.  Log in.
### General notes:
I've been working around the problem by running nmcli and nm-connection-editor in sys-net.

The sys-net nm-applet is not completely non-functional because it can pop up a dialog requesting the password for a particular wireless access point.

The sys-net nm-applet has also crashed (kernel message says a segmentation violation) since my latest reboot, but ran for several days before crashing.

---

#### Related issues:
None of these quite match: #2293, #2283, #2268, #2264

**Comment by andrewdavidwong** [comment]
Are you using Xfce4?

**Comment by jbwells** [comment]
Yes, using whatever the default is.  Not KDE.

**Comment by jbwells** [comment]
Restarting nm-applet by hand from a gnome-terminal in sys-net works.  It's the initial nm-applet's window that doesn't appear.

**Comment by 0keh** [comment]
nm-applet was not available for me too after fresh installation.
One or two reboots and it popped up. But because it was not my first try to install qubes, the nm-applet was never available in any successful installation I made.
The misbehavior was gone after updating dom0. Always.

**Comment by unman** [comment]
@andrewdavidwong  I believe this is fixed in R3.2

**Comment by andrewdavidwong** [comment]
@marmarek, do you want this to remain open for `github-builder` tracking?

**Comment by marmarek** [comment]
I don't remember any specific fix for this one. So probably it is fixed as a side effect of other change (in which case it will not receive `github-builder` notification).

**Comment by biotrox** [comment]
i use qubes R3.2 but still no nm-applet
so i try to lsmod the modules for the NIC and iwlwifi n iwlmvm,
the NIC module are loaded but the iwlwifi n iwlmvm are not
till now i can't use qubes r3.2
