### ISSUE TITLE
Qubes paid services page

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#2324]
A web page detailing paid Qubes services, such as extended support for EOL releases.

**Comment by andrewdavidwong** [comment]
While the Qubes OS Project does not to offer paid services, [Invisible Things Lab](https://invisiblethingslab.com/) does offer such services to enterprise clients.

**Comment by mfc** [comment]
I think the point of this issue was that on the Qubes OS website there is no information that ITL offers such services? and also having such a page is a way to offer other individuals/companies to advertise that they are also available, or point people to the qubes-users list to request paid services (or something)

**Comment by andrewdavidwong** [comment]
> I think the point of this issue was that on the Qubes OS website there is no information that ITL offers such services?

Oh, I see. I think that this is partially taken care of by the existence of the `business@` address. I also think that it would be appropriate to link to the ITL website, but I don't think that the Qubes website should advertise for ITL's enterprise services (that should be on the ITL site, IMHO).

> and also having such a page is a way to offer other individuals/companies to advertise that they are also available, or point people to the qubes-users list to request paid services (or something)

I'm not sure we want to do on the Qubes website any more than our current Partners page does.

Assigning to @rootkovska and @marmarek to join the discussion and decide.

**Comment by andrewdavidwong** [comment]
It appears the current situation has been deemed sufficient.
