### ISSUE TITLE
Outdated article: XFCE installation in dom0

### ISSUE THREAD

**Issue by Jeeppler** [QubesOS/qubes-issues#2325]
The following article is outdated: [XFCE installation in dom0](https://www.qubes-os.org/doc/xfce/)
The article should mention XFCE is fully supported in Dom0 for Qubes R3+ and that XCFE is the standard desktop for Qubes R3.2.

**Comment by kulinacs** [comment]
I do believe this is a duplicate of #1923

**Comment by andrewdavidwong** [comment]
@kulinacs: Good catch. Thanks.
