### ISSUE TITLE
[R4.0] "qvm-create -p netvm= somevm" creates VM with default netvm

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#2330]
#### Qubes OS version (e.g., `R3.1`):

R4.0

---
### Expected behavior:

`netvm` should be none.
### Actual behavior:

`netvm` is set to default value
### Steps to reproduce the behavior:

`qvm-create -p netvm= somevm`
### General notes:

---

**Comment by woju** [comment]
Could not reproduce, this works as advertised.
Closing.
