### ISSUE TITLE
dell xps 15 9550, pcie ssd - installation destination not found

### ISSUE THREAD

**Issue by alexanderzz** [QubesOS/qubes-issues#2332]
#### Qubes OS version (e.g., `R3.1`):
R3.1
### General notes:
I use dell xps 15 9550 with custom samsung 950 pro 256 gb ssd pcie
#### Related issues:
I'm not able to run installer in UEFI mode, it's just loop with black screen and "_" flashing. When I boot in legacy, I succesfully entered to anaconda, but it can't locate my pcie ssd Installation destination not found. I used before ubuntu, debian and no issues like this. I'm not expert in linux and hope you can help me, really want to use qubes,

**Comment by andrewdavidwong** [comment]
This question is too localized for `qubes-issues`. Please consider posting this to the `qubes-users` mailing list instead. (You can read more about our mailing lists [here](https://www.qubes-os.org/mailing-lists/).)

`qubes-users` is intended for these sorts of questions and receives much more traffic, which means that your question is more likely to receive a response there.
