### ISSUE TITLE
Debian-9 template not usable with latest qubes packages

### ISSUE THREAD

**Issue by hawaiikasper** [QubesOS/qubes-issues#2333]
#### Qubes OS version (e.g., `R3.1`):
R3.2

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):
debian-9

---

### Expected behavior:
Template (and appvms) should be usable.

### Actual behavior:
Template is not recognized by Qubes after start.

* Sometimes the light in qubes-manager stays yellow.
* GUI applications cannot be used.
* Network is most of the time disconnected.
* Only able to get a shell by using: `sudo xl console debian-9`

### Steps to reproduce the behavior:
Update debian-9 template to latest version (especially qubes packages) and try to use it.

### General notes:
Version that works for sure: `qubes-core-agent 3.2.5-1+deb9u1`

It is noted, that sometimes (like 1 out of 10 times) the template works fine.

Log:
> [    1.532529] systemd[1]: local-fs.target: Found ordering cycle on local-fs.target/start
> [    1.532538] systemd[1]: local-fs.target: Found dependency on qubes-mount-dirs.service/start
> [    1.532546] systemd[1]: local-fs.target: Found dependency on qubes-sysinit.service/start
> [    1.532553] systemd[1]: local-fs.target: Found dependency on qubes-db.service/start
> [    1.532560] systemd[1]: local-fs.target: Found dependency on local-fs.target/start
> [    1.532567] systemd[1]: local-fs.target: Breaking ordering cycle by deleting job qubes-mount-dirs.service/start
> [    1.532575] systemd[1]: qubes-mount-dirs.service: Job qubes-mount-dirs.service/start deleted to break ordering cycle starting with local-fs.target/start
> [.[0;1;31m SKIP .[0m] Ordering cycle found, skipping Initialize and mount /rw and /home

---

#### Related issues:
https://github.com/QubesOS/qubes-issues/issues/2194

**Comment by marmarek** [comment]
What version of qubesdb package do you have? Should be 3.2.1

**Comment by marmarek** [comment]
(you can access template console from dom0 using `sudo xl console debian-9`)

**Comment by hawaiikasper** [comment]
dpkg -l | grep qubes
> ii  libqubes-rpc-filecopy2               3.2.3+deb9u1                         amd64        Qubes file copy protocol library
> ii  libqubesdb                           3.2.1-1+deb9u1                       amd64        QubesDB libs.
> ii  qubes-core-agent                     3.2.10-1+deb9u1                      amd64        Qubes core agent
> rc  qubes-gpg-split                      2.0.13-1+deb8u1                      amd64        The Qubes service for secure gpg separation
> ii  qubes-gui-agent                      3.2.5+deb9u1                         amd64        Makes X11 windows available to qubes dom0
> ii  qubes-kernel-vm-support              3.2.3+deb9u1                         amd64        Qubes VM kernel and initramfs modules
> ii  qubes-pdf-converter                  2.1.1-1+deb9u1                       amd64        The Qubes service for converting untrusted PDF files into trusted ones
> ii  qubes-tor                            0.1.14-1+deb9u1                      amd64        The Qubes package for running a TorVM
> ii  qubes-utils                          3.2.3+deb9u1                         amd64        Qubes Linux utilities
> ii  qubesdb                              3.2.1-1+deb9u1                       amd64        QubesDB management tools and daemon.
> ii  qubesdb-vm                           3.2.0-1+deb9u1                       amd64        QubesDB VM service.

Btw, I connected the console via `sudo xl console debian-9` and used the command `qvm-copy-to-vm` inside this console to export the file containing the list above.

**Comment by marmarek** [comment]
Hmm, qubesdb-vm is older. Try to upgrade it.

**Comment by hawaiikasper** [comment]
I couldn't upgrade qubesdb-vm, because libxen couldn't be upgraded either. There were dependency problems. I just setup all my debian-9 templates from scratch (they were quite old and went through a lot of upgrade cycles) and now all my packages are up to date and everything works fine.
