### ISSUE TITLE
Whonix-Workstation AppVMs sometimes get stuck at yellow when starting

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#2334]
#### Qubes OS version (e.g., `R3.1`):

`R3.1`
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):

Whonix 13

---

[eujan1 on the Whonix forums:](https://forums.whonix.org/t/whonix-appvm-fails-to-start-after-update/2991)

> This may be Qubes specific but thought to ask here first as the failure to start occurred immediately after updating whonix-ws and -gw.
> 
> System is Qubes 3.1 with Whonix 13.
> 
> When starting the Whonix AppVM, the state remains yellow (sometimes will turn green for a second or so before returning to yellow) and no applications will run.
> This only happens in one specific Whonix AppVM. Other Whonix AppVM's function as expected.
> 
> Some errors in the var/log/console/guest-whonix.log as follows.
> 
> ```
> [ 5.214238] EXT4-fs (xvdb): warning: mounting fs with errors, running e2fsck is recommended
> [ 5.214624] EXT4-fs (xvdb): mounted filesystem with ordered data mode. Opts: discard
> [ 5.221787] EXT4-fs warning (device xvdb): ext4_resize_begin:44: There are errors in the filesystem, so online resizing is not allowed
> [ 5.221787]
> 
> [ 6.930620] EXT4-fs error (device xvdb): ext4_mb_generate_buddy:757: group 1, block bitmap and bg descriptor inconsistent: 10561 vs 10563 free clusters
> 
> [ 7.371456] JBD2: Spotted dirty metadata buffer (dev = xvdb, blocknr = 0). There's a risk of filesystem corruption in case of system crash.
> ```
> 
> I can delete this VM without losing much but am curious as to what caused this?

**Comment by adrelanos** [comment]
Is this still an issue with Qubes-Whonix 14 on Qubes R4?

I am asking, so we can close this ticket.

User asked.

https://forums.whonix.org/t/whonix-appvm-fails-to-start-after-update/2991/7?u=patrick

**Comment by andrewdavidwong** [comment]
Closing since this issue duplicates that thread and due to the prolonged lack of activity. If anyone would like this issue to be reopened, please leave a comment, and we'll be happy to take another look. Thank you.
