### ISSUE TITLE
connect external USB audio interface to Windows HVM: vchan timeout

### ISSUE THREAD

**Issue by nic4123** [QubesOS/qubes-issues#2335]
#### Qubes OS version (e.g., `R3.1`):

R3.2rc3
### Actual behavior:

```
[ndm@dom0 ~]$ qvm-usb
sys-net :2-1.6    04f2:b217 Chicony_Electronics_Co.__Ltd._Integrated_Camera
sys-net:3-1.1     0582:0074 Roland_EDIROL_UA-25
[ndm@dom0 ~]$ qvm-usb -a w7 sys-net:3-1.1
ERROR: Device attach failed: vchan connection timeout (or error)
[ndm@dom0 ~]$
```

**Comment by marmarek** [comment]
This isn't error I'd expect. But anyway qvm-usb does not support Windows
VMs, yet.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by marmarek** [comment]
@omeg it looks like handling non-existing services is broken. In such a case, qrexec-agent should connect back data vchan and just send non-zero exit code (Linux use 127 for non-existing commands).

**Comment by nic4123** [comment]
Can i have audio on working on Windows HVM if i run USB external audio interface through PCI e.g.: "qvm-pci -w7 <vmname> <bdf>"?

**Comment by marmarek** [comment]
In theory yes, in practice, it is broken currently: https://github.com/QubesOS/qubes-issues/issues/1659

**Comment by omeg** [comment]
Fixed by https://github.com/QubesOS/qubes-core-agent-windows/commit/54d8b06d87427e3d8f6a2858f3dcf57ef0a7c946

**Comment by omeg** [comment]
Well, the original problem isn't fixed...

**Comment by tonsimple** [comment]
Just decided to leave a little comment here https://sourceforge.net/p/usbip/discussion/418507/thread/86c5e473/ in case someone specifically needs to pass a printer to a windows VM and is in the process of pulling their hairs out :)

It's doable using USBIP windows client from here and Fedora-24's usbip module

It does not work for webcams and flash drives however (something mysteriously broken in USBIP, either kernel module in fedora or windows client)
Fedora's printer sharing must work, but printer must be bound to usbip driver before printer sharing (cusp) starts up (so it must be called from rc.local early on)
Also, bind first then start usbipd -D

(of course, you'd need to allow networking between your usb-vm and windows vm...)

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
