### ISSUE TITLE
Firewall rules SMTPS unkown

### ISSUE THREAD

**Issue by sjug** [QubesOS/qubes-issues#2337]
#### Qubes OS version (e.g., `R3.1`):
3.2 RC3

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):
All

---

### Expected behavior:
Can add hosts to firewall exclusions list that are a specific type of protocol and service port.

### Actual behavior:
When we try to add 'smtps' TCP host to firewall, it fails.

### Steps to reproduce the behavior:
1. Open Qubes VM Manager
2. Open 'VM Settings' for any VM
3. Select 'Firewall Rules' tab
4. Select 'Deny network access except...' radio button
5. Press '+' icon to add new address to allow
6. Enter any host under 'Address'
7. Select 'TCP' protocol radio button
8. Select 'smtps' from 'Service' dropdown
9. Press 'OK'
10. Error, Invalid Service: Service 'smtps' is unknown

### General notes:
If SMTP is port 25, SMTPS is port 465?
What service is 587 the port typically used for secure SMTP?
Can we add custom services to this dropdown list in firewall settings?

---

#### Related issues:
Unknown

**Comment by marmarek** [comment]
You can simply enter port number.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by andrewdavidwong** [comment]
In addition to entering port 465, as Marek said, you can also enter `urd` (URL Rendesvous Directory for SSM), which is port 465/tcp.
