### ISSUE TITLE
Windows VM migrated from 3.1 to 3.2 cannot be put into windowed mode

### ISSUE THREAD

**Issue by JasF** [QubesOS/qubes-issues#2339]
**\* Migrating from Qubes OS R3.1 to R3.2 rc3 ***
#### Qubes OS version 3.2 rc3

Graphics: Geforce GTX 980
Two 1920x1080 24' monitors. One connected to DVI-D adapter, second to HDMI
CPU: Intel 4790K
Memory: 16G
SSD: Revodrive 3 X2
#### Affected HVM (Template HVM) for Windows 7 64bit

---
### Expected behavior:

After Restoring VM launch and working ok
### Actual behavior:

After launch AppVM with Win 7 64bit & installed Qubes Windows Tools, domain-window is always maximized with width: 3960px. After dragging it always maximized into actual display. Cannot make windowed mode for Windows 7 64bit AppVM. 
### Steps to reproduce the behavior:
- Create on QubesOS R3.1 HVM with Windows 7 64bit
- install Qubes Windows Tools Inside
- backup VM
- Install QubesOS R3.2 rc3
- Restore VM with Windows 7 64bit
### General notes:

Also, in QubesOS R3.2 rc3 missing firefox shortcut on Start menu for fedora-23 AppVMs and TemplateVMs. In R3.1 shortcuts is ok (on KDE environment)

**Comment by andrewdavidwong** [comment]
Possibly related: #2235

**Comment by JasF** [comment]
Simple solution for this issues:
- Make Seamless Mode off, window with Win7 & QWT in fullscreen.
- Just fast drag window from one monitor to far corner of other monitor. 
After few repeating of this gesture, 'RESIZE' action for domain-window are unlocked and size changing for window is available.

**Comment by pdinoto** [comment]
This also happened to a Windows 7 Proffessional just installed on Qubes R3.2` with these versions:
```
qubes-core-dom0-linux:	3.2.10
qubes-db:		3.2.3
qubes-gui-dom0:		3.2.6
qubes-utils-libs:	3.2.3
qubes-windows-tools:	3.2.2 (3.2.2.3 in the .exe on the virtual CD)
```

**Comment by marmarek** [comment]
@omeg what is the current (in QWT 3.2.2) state of seamless mode? Is it disabled by default (but possible to enable), or disabled and blocked?

**Comment by omeg** [comment]
It's disabled by default, but can be enabled.

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
