### ISSUE TITLE
Offer alternative to GPG: Minisign

### ISSUE THREAD

**Issue by rugk** [QubesOS/qubes-issues#2343]
PGP/GPG is old and uses RSA keys. There is a new [signing tool called Minisign](https://jedisct1.github.io/minisign/), which is faster and more secure than RSA keys as it uses the well-known elliptical curve Curve25519 included in Ed25519.

It would be nice if Minisign signatures would be offered as an alternative to traditional signatures on the download page of Qubes OS. Additionally, of course, minisign could also be used by Qubes OS internally, e.g. as a ('n additional) verification of updates or similar things...

**Comment by andrewdavidwong** [comment]
I think this is unlikely to happen for several reasons:

* PGP is a well-known, widely accepted standard.
* We also provide cryptographic digests (hashes) as an alternative verification method.
* GPG is well-tested and trusted software, whereas Minisign is relatively unknown.
* We couldn't possibly support everyone's favorite verification method. There are too many out there. We don't have the resources to evaluate them, and it probably wouldn't be worth our time.
* GPG already supports ECC.

CC: @rootkovska, @marmarek

**Comment by jedisct1** [comment]
If it works, don't fix it.

**Comment by rugk** [comment]
It should be an alternative. That's no fix, that's an enhancement.
