### ISSUE TITLE
(Kernel) hardening: Use PaX or Grsec

### ISSUE THREAD

**Issue by rugk** [QubesOS/qubes-issues#2345]
If you did not know already: You have been featured by Snowden. :tada: 

So this issue is about a response by another user:

> solation is one thing, memory corruption prevention is another. You might need PaX/Grsec-based OS, @subgraph ?

https://twitter.com/citypw/status/781497609298989056

So from quickly searching this issue tracker, it seems you do not use any kernel hardening features. What do you think about adding them?

The user also mentions [another OS](https://subgraph.com/). I think you can certainly get inspiration from the competition. :smile:

**Comment by ag4ve** [comment]
I'll preface my liking this idea by saying I've never run PaX on Xen. There
might also be kernel version issues since they only release long-term
support kernel patches (there's a blog post about why - you pay for the
other versions). If neither of those are blockers - I would love to see
this.

**Comment by mfc** [comment]
thanks for opening this issue. for the past year we have tried convincing the subgraph team to work on this (including getting funding for them to do it) by creating subgraph templates for Qubes but they aren't interested. so I think it's worthwhile to track this effort and look elsewhere for potential implementers.

**Comment by mfc** [comment]
just to update, the coldkernel team is working on this, see their blogpost and progress:

https://coldhak.ca/blog/2016/12/12/coldkernel-qubes-1.html
https://github.com/coldhakca/coldkernel/issues/35

**Comment by marmarek** [comment]
Grsec is dead (at least as an open source project), so it doesn't apply anymore.

**Comment by rugk** [comment]
What about PaX? Is not that at least still possible?

**Comment by fread2281** [comment]
https://github.com/copperhead/linux-hardened

**Comment by jameshilliard** [comment]
Here's their updated stable kernel obtained via GPL request https://github.com/jameshilliard/linux-grsec.
