### ISSUE TITLE
Error when starting VM: "integer division or modulo by zero"

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#2348]
[On 2016-09-29 16:31, katerimmel@sigaint.org wrote:](https://groups.google.com/d/msgid/qubes-users/d8e8d3997222f1268820ec378d902728.webmail%40localhost)
> Hello
> After upgrading to 3.2 I noticed some features that I don't like.
> 
> [...]
> 
> 3)Every time that start a VM shows up this message: Error starting VM
> .....: integer division or modulo by zero (the VM works the same)
>

**Comment by plushambush** [comment]
I confirm the same bug on my 3-head setup since 3.2rc:
One of the monitors is reported by xrandr as having size 0mm x 0mm 
This causes division by zero in lines 64-65 of the monitorlayoutnotify.py
`dpi = (int(output_params['width']) * 254 /
int(output_params['width_mm']) / 10)`

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-gui-dom0-3.2.6-1.fc23` has been pushed to the `r3.2` testing repository for dom0.
To test this update, please install it with the following command:
```
sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-gui-daemon/compare/3b6003874bd6723bb386a4d1d94884ceefa78fca...8f097ec116cd0ac8bc5e11a6b73642349ff8ee26

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-gui-dom0-3.2.6-1.fc23` has been pushed to the `r3.2` stable repository for dom0.
To install this update, please use the standard update command:
```
sudo qubes-dom0-update
```
Or update dom0 via Qubes Manager.

[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-gui-daemon/compare/3b6003874bd6723bb386a4d1d94884ceefa78fca...8f097ec116cd0ac8bc5e11a6b73642349ff8ee26
