### ISSUE TITLE
System Updates applet: connection errors

### ISSUE THREAD

**Issue by desmond-decker** [QubesOS/qubes-issues#2349]
Qubes OS version R3.1

The Software Updater applet and GUI is not working on fresh install of R3.1. When clicked, it shows a large red warning sign with message: "Last check for updates was more than a month ago. It's strongly recommended that you check for updates."

Clicking the "Check for new updates" button brings an error message: "There is no network connection available. Please check your connection settings and try again." Clicking the details button shows the message: "cannot refresh cache when offline."

The other VMs are connected and working fine. Running dom0 update from the terminal works.

**Comment by andrewdavidwong** [comment]
Related: #1378

**Comment by desmond-decker** [comment]
Just discovered the applet is gone in 3.2 with XFCE, so maybe it's not a big deal.
