### ISSUE TITLE
CloudFlare makes website inaccessible for Tor Browser.

### ISSUE THREAD

**Issue by qubenix** [QubesOS/qubes-issues#2352]
Captcha loads blank repeatedly. Please remove captcha for Tor users all together.
![pic](https://cloud.githubusercontent.com/assets/15707061/19014651/5c6790fe-87e2-11e6-8a4b-e86854d08139.png)

**Comment by qubenix** [comment]
Website is working now, closing.

**Comment by andrewdavidwong** [comment]
AFAIK, we've had Tor exit nodes whitelisted in Cloudflare for a long time now.
