### ISSUE TITLE
Cannot restore backed up TemplateVMs

### ISSUE THREAD

**Issue by desmond-decker** [QubesOS/qubes-issues#2353]
When restoring a backed up TemplateVM, the backup manager will not allow restoring VMs that have the same name as an existing VM. For encrypted backups of standard TemplateVMs (eg Fedora-23) this means restoring the backup is impossible, as there is no way to rename existing TemplateVMs that are installed from RPM. 

QVVM displays this message when attempting to rename Fedora-23: "Cannot rename VM installed by RPM -- first clone VM and then use yum to remove package". Cloning the VM and then removing Fedora-23 with yum still doesn't allow restoring of the backed up Fedora-23 VM, and breaks all associated App and System VMs. Renaming the backed-up TemplateVMs in the backup manager is not possible either. 

A mechanism for restoring TemplateVMs with a new name from within the backup manager would fix the issue. Either that or inform users that they need to clone and rename RPM-installed TemplateVMs before backing them up.

**Comment by andrewdavidwong** [comment]
Have you tried the `--rename-conflicting` option?

**Comment by andrewdavidwong** [comment]
Closing due to lack of response. Please comment or re-open if this is still an issue.
