### ISSUE TITLE
external monitor enters screen saving mode even with all power saving settings disabled

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#2360]
#### Qubes OS version (e.g., `R3.1`):

R3.2 XFCE
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):

dom0

---
### Expected behavior:

System should not turn off the screen.
### Actual behavior:

System turns off screen.
### Steps to reproduce the behavior:
- turn off all xfce power saving settings
- turn off xscreensaver
- uninstall xscreensaver
- connect hdmi screen
- leave system unattended for 30 or 60 minutes
- screen will be powered off
- mice movement or keyboard press will not turn on the screen
- switching to a virtual console and restarting lightdm helps to reactivate the screen (but it's not a great workaround, since all windows are now inside the same virtual desktop)
### General notes:

Also xset did not help.

```
   xset s off
   xset -dpms
```

Uninstalled xscrensaver just to exclude it being the cause of this.

Did not happen with KDE previously.
#### Related issues:
#2287

**Comment by JeramyNS** [comment]
I have this issue also however I also get the following bug, after this issue occurs once.

It's a little random when it happens but the basics of it is:
Either:
A) Computer screen goes to screensaver 
B) Screensaver is disabled and I leave unattended for a while

Then when I return the computer will not wake from Wireless Keyboard/Mouse (Logitech K350)
but will wake when using a basic Microsoft USB Keyboard. Then it will show the screensaver lock screen (I don't believe this happened when the screensaver was disabled).

After using the computer normally for a while, I will eventually switch workspaces.
Upon changing workspaces the screensaver lock screen will appear immediately but will vanish as you move your mouse around and click on windows.

For example, the black mask will appear over a window and the background.
Upon clicking on a window, the black mask vanishes from that screen area. 
I then repeat this process by clicking on everything in the workspace until everything is visible. 
Occasionally after doing this process the same black mask bug will immediately happen.
Then if I leave that workplace and immediately return the same thing will happen.

This part of the bug will never affect more than one workspace at a time but can swap affect another workspace if it is left inactive for a period of time.

Haven't tried uninstalling it yet but will attempt that tomorrow.

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
