### ISSUE TITLE
Qubes Manager "restart VM" feature fails periodically

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#2362]
#### Qubes OS version (e.g., `R3.1`):

`R3.2`
#### Problem description:

[On 2016-10-04 04:38, cubit wrote:](https://groups.google.com/d/msgid/qubes-users/KTEUG0N--3-0%40tutanota.com)

> Hello
> 
> I am testing the new "restart" feature in the Qubes VM Manager and noticing that it is a bit buggy.   There is one piece of the puzzle however that I can not figure out allowing me to replicate it consistently or narrow down why it fail some times
> 
> The first time I  select a VM and press "restart"  after an indeterminate time frame the restart will fail with the error below.   If I try and restart any number of other vm immediately after they will all restart ok.
> 
> error: 
> 
> ```
>   ---
>   line: assert not vm.is_running() 
>   func: start_vm
>   line no.: 1158
>   file: /usr/lib64/python2.7/site-packages/qubesmanager/main.py
>   ---
>   line: self.caller.start_vm(vm)
>   func: check_if_vm_has_shutdown
>   line no.: 288
>   file: /usr/lib64/python2.7/site-packages/qubesmanager/main.py
> ```
> 
> cubit

**Comment by cubi7** [comment]
Some unscientific testing.

Trying a restart after 15 minutes of not doing a restart and the function works as expected

Trying a restart after 50 minutes of not doing a restart and the function fails the first time with the error as mentioned previously.
