### ISSUE TITLE
Qubes kernel breaks ecryptfs

### ISSUE THREAD

**Issue by petaramesh** [QubesOS/qubes-issues#2363]
#### Qubes OS version : `R3.2`

Using kernel `4.4.14-11.pvops.qubes.x86_64`
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):

`fedora-23`, and all others relying on same kernel `4.4.14-11.pvops.qubes.x86_64`
### Expected behavior:

I would like to be able to use ecryptfs inside VM.
### Actual behavior:

Trying to use `ecryptfs` inside VM doesn't allow to list contents of mounted directories, with message:
`ls: cannot open directory blah/: Wrong medium type`
### Steps to reproduce the behavior:

Install `ecryptfs` and try to mount existing encrypted dir.
### General notes:

This is a known kernel issue supposedly fixed starting from kernel `4.4.16-1-lts`, see for example : 
https://bbs.archlinux.org/viewtopic.php?id=214258

**Comment by cklin** [comment]
Just hit this problem after restoring to a newly installed (i.e., with 4.4.14 kernel only) Qubes 3.2 system.  I would appreciate if a fix could be expedited, as I am now essentially locked out of my ecryptfs directories in my appvms.

**Comment by marmarek** [comment]
If this is fixed in 4.4.16, should be already ok in Qubes, as we have 4.4.31 already.

**Comment by petaramesh** [comment]
I am happy ton confirm that kernel 4.4.31-11.pvops.qubes.x86_64 fixes 
this bug.
