### ISSUE TITLE
Qubes doesn't refresh app shortcuts

### ISSUE THREAD

**Issue by Sekhmet** [QubesOS/qubes-issues#2364]
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):
`fedora-23`

---

### Expected behavior:
New software should be added to `Add more shortcuts` menu after installing. If it is not
`qvm-sync-appmenus fedora-23` should do it.

### Actual behavior:
New software is not added to `Add more shortcuts` menu after installing nor after forcing sync of app menus.

### Steps to reproduce the behavior:
1. Install new software on VM:
`sudo dnf install gimp`
2. (There is no GIMP on software list in `Add more shortcuts` menu)
3. Start `fedora-23` template VM.
4. Force refresh of app menus on dom0
`qvm-sync-appmenus fedora-23`
4. (Still no new software on list)

### General notes:
Tested on default personal VM. Tried with Telegram, GIMP and OpenTTD.
Disclaimer: I'm not sure if this is not my misunderstanding of process of adding new software and it's just not a bug.

---

**Comment by andrewdavidwong** [comment]
Does it happen only on `fedora-23` and not on other templates, or is that the only template you've tried?

**Comment by Sekhmet** [comment]
I've just tested it on `debian-8`.
1. Created `testing` VM from `debian-8`
2. Installed GIMP: `sudo apt-get install gimp`
3. (No application in Add shortcut item)
4. Started `debian-8` VM
5. `qvm-sync-menus debian-8`
6. (Still no application).

Output from `qvm-sync-menus`

```sh
Warning: ignoring key 'Name' of iceweasel.desktop
Warning: not creating/updating '/var/lib/qubes/vm-templates/debian-8/apps.templates/iceweasel.desktop' because of missing 'Name' key
----> Failed to get icon for display-im6.desktop: No icon received
```

**Comment by marmarek** [comment]
You should install applications in template, not template-based VM.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by Sekhmet** [comment]
I didn't realize that root filesystem is shared across VM's.
Now it works even without refreshing.

Sorry for that.
