### ISSUE TITLE
Attaching USB controller to a USB VM prevents all VMs from starting

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#2367]
#### Qubes OS version (e.g., `R3.1`):

`R3.2`
#### Problem description:

[On 2016-10-05 15:30, boromirsbeard wrote:](https://groups.google.com/d/msgid/qubes-users/9d268a2a0904c318fa75471cb37db4a1.webmail%40localhost)

> Attaching USB controller to a usbVM (running qubes on a sata connected
> disk), renders all vm's unable to start, even after controller is
> detatched. Short-term remedy is to detatch and reboot.

**Comment by JasF** [comment]
But, it occurs only if some cases are filled:
- Keyboard/Mouse are USB and connected into motherboard-USB controller.
- Motherboard USB controller is attached into usbVM
I am right?

If yes, solution is:
- Insert USB (3.x) PCI-Express card into free PCI-Express slot
- Attach USB controller associated with PCI-Express USB card into usbVM
- All works fine.

**Comment by andrewdavidwong** [comment]
> Insert USB (3.x) PCI-Express card into free PCI-Express slot

A major limitation of this solution is that most laptops don't allow for this.

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
