### ISSUE TITLE
Duplicate  dom0 pop-up notifications display whenever a VM is started

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#2368]
#### Qubes OS version (e.g., `R3.1`):

`R3.2`
#### Description:

[On 2016-10-05 15:30, boromirsbeard wrote:](https://groups.google.com/d/msgid/qubes-users/9d268a2a0904c318fa75471cb37db4a1.webmail%40localhost)

> Two [Dom0 monitor configuration] windows pop up everytime a VM is started.

**Comment by ptitdoc** [comment]
I confim this issue. I have two xfce4-display-settings pop-ups each time a VM is started.

Parent process is `xfsettingsd --display :0.0`

**Comment by ptitdoc** [comment]
Bug seems similar than this one:
https://bugs.launchpad.net/ubuntu/+source/xfce4-settings/+bug/1264629

In XFCE4 'Settings Manager->Keyboard->Application Shortcuts' there is a XF86Display shortcut.
This shortcut XF86Display is defined which launches xfce4-display-settings application.

Removing this shortcut fixe this problem.

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
