### ISSUE TITLE
ERROR: Failed to kill old QubesDB instance

### ISSUE THREAD

**Issue by qubenix** [QubesOS/qubes-issues#2369]
#### Qubes OS version (e.g., `R3.1`):
R3.2

qubes-core-dom0-3.2.11-1.fc23.x86_64

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):
All VMs.

---

### Expected behavior:
`/var/run/qubes/qubesdb.{vm-name}.*` should be rm'd when VM is shutdown.
### Actual behavior:
Files persist and prevent future startup of VM.
### Steps to reproduce the behavior:
Start a VM, shutdown VM, attempt to restart VM.

    [user@dom0 ~]$ qvm-start media
    --> Creating volatile image: /var/lib/qubes/appvms/media/volatile.img...
    --> Loading the VM (type = AppVM)...
    --> Starting Qubes DB...
    --> Setting Qubes DB info for the VM...
    --> Updating firewall rules...
    --> Starting the VM...
    --> Starting the qrexec daemon...
    Waiting for VM's qrexec agent......connected
    --> Starting Qubes GUId...
    Connecting to VM's GUI agent: .connected
    --> Sending monitor layout...
    --> Waiting for qubes-session...
    [user@dom0 ~]$ qvm-shutdown media
    Shutting down VM: 'media'...
    [user@dom0 ~]$ ls /var/run/qubes/ | grep media
    qubesdb.media.pid
    qubesdb.media.sock
    [user@dom0 ~]$ qvm-start media
    --> Creating volatile image: /var/lib/qubes/appvms/media/volatile.img...
    --> Loading the VM (type = AppVM)...
    --> Starting Qubes DB...
    ERROR: Failed to kill old QubesDB instance (PID 13079
    ). Terminate it manually and retry. If that isn't QubesDB process, remove the pidfile: /var/run/qubes/qubesdb.media.pid
### General notes:
In `media` vm:

    user@host:~$ sudo dpkg --list | grep qubesdb
    ii  libqubesdb                                     3.2.2-1+deb8u1                       amd64        QubesDB libs.
    ii  qubesdb                                        3.2.2-1+deb8u1                       amd64        QubesDB management tools and daemon.
    ii  qubesdb-vm                                     3.2.2-1+deb8u1                       amd64        QubesDB VM service.

---

#### Related issues:
https://github.com/QubesOS/qubes-issues/issues/1745

**Comment by andrewdavidwong** [comment]
Does this only occur when you rapidly attempt to restart a VM?

**Comment by qubenix** [comment]
No. The files persist until I manually rm them.

**Comment by qubenix** [comment]
Some output from `sudo journalctl -f` in `dom0` during the shutdown of a VM:

    Oct 12 20:19:33 dom0 root[9728]: /etc/xen/scripts/block-snapshot: remove XENBUS_PATH=backend/vbd/13/51712
    Oct 12 20:19:33 dom0 root[9747]: /etc/xen/scripts/block: remove XENBUS_PATH=backend/vbd/13/51728
    Oct 12 20:19:33 dom0 root[9763]: /etc/xen/scripts/block: remove XENBUS_PATH=backend/vbd/13/51744
    Oct 12 20:19:33 dom0 root[9776]: /etc/xen/scripts/block-snapshot: Device /dev/mapper/snapshot-fb01:11667029-fb01:11665979 still in use - not removing
    Oct 12 20:19:33 dom0 root[9823]: /etc/xen/scripts/block: remove XENBUS_PATH=backend/vbd/13/51760

Let me know if there are any other logs that I can give to help.

**Comment by rustybird** [comment]
Had the same problem. Downgrading the qubes-db packages to 3.2.1 (from 3.2.2) fixed it:

    sudo qubes-dom0-update qubes-db{,-dom0,-libs}-3.2.1-1.fc23

Somehow caused by commit [`daemon: remove pidfile and socket only when created by this instance`](https://github.com/QubesOS/qubes-core-qubesdb/commit/73f112aa3387d0efa88bd1f927ac9d0f36c6796f) then?

**Comment by cyrinux** [comment]
I had the same problem, same fix

**Comment by marmarek** [comment]
Yes @rustybird you're right. There is inverted logic in `stat()` error checking...

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-db-3.2.3-1.fc23` has been pushed to the `r3.2` testing repository for the Fedora `fc23` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.2-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-qubesdb/compare/79fa5a805aee26f0c89e3a25dbe30bfef0e73e60...5c881b27523f23ecd5ad6b2ec3dbd576a7bc5870

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-db-3.2.3-1.fc24` has been pushed to the `r3.2` testing repository for the Fedora `fc24` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.2-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-qubesdb/compare/79fa5a805aee26f0c89e3a25dbe30bfef0e73e60...5c881b27523f23ecd5ad6b2ec3dbd576a7bc5870

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-db-3.2.3-1.fc23` has been pushed to the `r3.2` testing repository for dom0.
To test this update, please install it with the following command:
```
sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-qubesdb/compare/79fa5a805aee26f0c89e3a25dbe30bfef0e73e60...5c881b27523f23ecd5ad6b2ec3dbd576a7bc5870

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-db-3.2.3-1.fc23` has been pushed to the `r3.2` stable repository for the Fedora `fc23` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-qubesdb/compare/e06820e6c86e7263164853c6b6be40a10e053a19...5c881b27523f23ecd5ad6b2ec3dbd576a7bc5870

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-db-3.2.3-1.fc24` has been pushed to the `r3.2` stable repository for the Fedora `fc24` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-qubesdb/compare/e06820e6c86e7263164853c6b6be40a10e053a19...5c881b27523f23ecd5ad6b2ec3dbd576a7bc5870

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-db-3.2.3-1.fc23` has been pushed to the `r3.2` stable repository for dom0.
To install this update, please use the standard update command:
```
sudo qubes-dom0-update
```
Or update dom0 via Qubes Manager.

[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-qubesdb/compare/e06820e6c86e7263164853c6b6be40a10e053a19...5c881b27523f23ecd5ad6b2ec3dbd576a7bc5870

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubesdb_3.2.3-1+deb8u1` has been pushed to the `r3.2` testing repository for the Debian `jessie` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `jessie-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-qubesdb/compare/79fa5a805aee26f0c89e3a25dbe30bfef0e73e60...5c881b27523f23ecd5ad6b2ec3dbd576a7bc5870

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubesdb_3.2.3-1+deb9u1` has been pushed to the `r3.2` testing repository for the Debian `stretch` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `stretch-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-qubesdb/compare/79fa5a805aee26f0c89e3a25dbe30bfef0e73e60...5c881b27523f23ecd5ad6b2ec3dbd576a7bc5870

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubesdb_3.2.3-1+deb8u1` has been pushed to the `r3.2` stable repository for the Debian `jessie` template.
To install this update, please use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-qubesdb/compare/e06820e6c86e7263164853c6b6be40a10e053a19...5c881b27523f23ecd5ad6b2ec3dbd576a7bc5870

**Comment by hugoncosta** [comment]
Sorry to dig out this thread, but I'm faced with the error, only on my Win7 machine. Is the fix still rolling back the qubes packages?
