### ISSUE TITLE
Change default Debian Stretch Xwrapper config to prevent breaking qubes-gui

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#2370]
Branched from: https://github.com/QubesOS/qubes-issues/issues/1981#issuecomment-252496499 by @yilmi 

---

In Debian Stretch, the default wrapper configuration in `/etc/X11/Xwrapper.conf` should be:

```
allowed_users = anybody
needs_root_rights = no
```

**Comment by adrelanos** [comment]
Modifications of user configuration files such as `/etc/X11/Xwrapper.conf` is always problematic. (Causes interactive dpkg conflict resolution dialogs.)

Is there something like `/etc/X11/Xwrapper.conf.d`?

Alternatively I guess it would be better to config-package-dev displace `/usr/lib/xorg/Xorg.wrap`.

Relevant `apt-file list xserver-xorg-legacy`:
```
xserver-xorg-legacy: /usr/lib/xorg/Xorg.wrap
```

**Comment by adrelanos** [comment]
The `/etc/X11/Xwrapper.conf` modifications didn't work for me. But `sudo mv /usr/lib/xorg/Xorg.wrap ~/` worked for me.

So let's go with config-package-dev displace `/usr/lib/xorg/Xorg.wrap`?

**Comment by yilmi** [comment]
If `/usr/lib/xorg/Xorg.wrap` is present it will always be used as default Xorg binary, so we'll go again through `/etc/X11/Xwrapper.conf`

It seems that Qubes doesn't need to run Xorg as root (see `qubes-run-xorg.sh`) so in our case the wrapper is useless.

config-package-dev displace on `/usr/lib/xorg/Xorg.wrap` sound safe.

**Comment by adrelanos** [comment]
Doing so in this pull request:
https://github.com/marmarek/qubes-gui-agent-linux/issues/20

**Comment by marmarek** [comment]
What about getting rid of `xserver-xorg-legacy`? `Conflicts: xserver-xorg-legacy`?

**Comment by yilmi** [comment]
In kali templates, we can't remove it without breaking kali-linux dependencies, the `kali-linux` meta-package will install packages that depend on `xserver-xorg-legacy`. (`kali-desktop-common`)

**Comment by adrelanos** [comment]
> What about getting rid of xserver-xorg-legacy? Conflicts: xserver-xorg-legacy?

That would prevent the kali-linux package from being installed at the same time as qubes-gui-agent.

What could work however is qubes-gui-agent using `Provides: xserver-xorg-legacy`. Then the kali-linux package should no longer pull in xserver-xorg-legacy since it already is provided.

**Comment by marmarek** [comment]
> What could work however is qubes-gui-agent using Provides: xserver-xorg-legacy. Then the kali-linux package should no longer pull in xserver-xorg-legacy since it already is provided.

Is this better solution? I feel it should be better than modifying/moving file belonging to other package. But that feeling is mostly based on rpm experience.

**Comment by adrelanos** [comment]
Marek Marczykowski-Górecki:
>> What could work however is qubes-gui-agent using Provides: xserver-xorg-legacy. Then the kali-linux package should no longer pull in xserver-xorg-legacy since it already is provided.
> 
> Is this better solution? I feel it should be better than modifying/moving file belonging to other package. But that feeling is mostly based on rpm experience.
> 

If that works it should be better indeed. Didn't occur to me earlier
when I wrote above PR.

Maybe qubes-gui-agent should use both:
Provides: xserver-xorg-legacy
Conflicts: xserver-xorg-legacy

I guess we'd have to test various cases.

Case one is xserver-xorg-legacy already installed, then installing newer
qubes-gui-agent.

Case two is having newer qubes-gui-agent already installed, then pulling
kali-linux and see if that stops pulling xserver-xorg-legacy and
otherwise complaining.

Case three is having newer qubes-gui-agent already installed and
manually trying to install xserver-xorg-legacy. Ideally nothing would
happen. Though this use case my not apply to our situation here.

**Comment by marmarek** [comment]
# Both `Provides:` and `Conflicts:`

> Case three is having newer qubes-gui-agent already installed and manually trying to install xserver-xorg-legacy. Ideally nothing would happen. Though this use case my not apply to our situation here.

It tries to replace `qubes-gui-agent` with `xserver-xorg-legacy`

> Case one is xserver-xorg-legacy already installed, then installing newer qubes-gui-agent.

Upgrade of `qubes-gui-agent` is prevented, even with `apt-get dist-upgrade`. 

> Case two is having newer qubes-gui-agent already installed, then pulling kali-linux and see if that stops pulling xserver-xorg-legacy and otherwise complaining.

This is the only case when it does the job. `kali-linux` is installed without problem and no longer pulls `xserver-xorg-legacy`.

# Just `Provides:`

> Case one is xserver-xorg-legacy already installed, then installing newer qubes-gui-agent.

qubes-gui-agent is upgraded normally, but `xserver-xorg-legacy` is not removed. Then it can be removed manually, without removing `kali-linux`.

> Case two is having newer qubes-gui-agent already installed, then pulling kali-linux and see if that stops pulling xserver-xorg-legacy and otherwise complaining.

This works fine.

> Case three is having newer qubes-gui-agent already installed and manually trying to install xserver-xorg-legacy. Ideally nothing would happen. Though this use case my not apply to our situation here.

`xserver-xorg-legacy` is installed normally, no other effects.

# `Provides:`, `Conflicts:` and `Replaces:`

This idea is based on https://www.debian.org/doc/debian-policy/ch-relationships.html#s7.6.2

> Case one is xserver-xorg-legacy already installed, then installing newer qubes-gui-agent.

`xserver-xorg-legacy` is not removed, `qubes-gui-agent` upgrade is prevented (both `apt-get upgrade` and `apt-get dist-upgrade`).

> Case two is having newer qubes-gui-agent already installed, then pulling kali-linux and see if that stops pulling xserver-xorg-legacy and otherwise complaining.

`xserver-xorg-legacy` is no longer installed, `kali-linux` is installed correctly.

> Case three is having newer qubes-gui-agent already installed and manually trying to install xserver-xorg-legacy. Ideally nothing would happen. Though this use case my not apply to our situation here.

Installation of `xserver-xorg-legacy` removes `qubes-gui-agent`.

# Conclusion

I think the best option from the above is just `Provides: xserver-xorg-legacy`. For people having Kali already installed, they have already modified `/etc/X11/Xwrapper.conf` manually, so shouldn't be a problem. What do you think @adrelanos @unman ?

**Comment by adrelanos** [comment]
Another options would be Provides: as well as Replaces:. But nevermind.
I guess it's better to keep it simple.

So yes, only using Provides: seems like a fine solution.

**Comment by unman** [comment]
@marmarek  Provides: seems a nice simple solution that solves the problem. I'd go for that.

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-gui-vm-3.2.7-1.fc23` has been pushed to the `r3.2` testing repository for the Fedora `fc23` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.2-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-gui-agent-linux/compare/6a2bcca991b25eb3c94cb108f3da7b2c2d88c1ed...1f04c8df1dff08799ce0b58b6d97c15d3bc161c2

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-gui-vm-3.2.7-1.fc24` has been pushed to the `r3.2` testing repository for the Fedora `fc24` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.2-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-gui-agent-linux/compare/6a2bcca991b25eb3c94cb108f3da7b2c2d88c1ed...1f04c8df1dff08799ce0b58b6d97c15d3bc161c2

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-gui-agent_3.2.7+deb8u1` has been pushed to the `r3.2` testing repository for the Debian `jessie` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `jessie-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-gui-agent-linux/compare/6a2bcca991b25eb3c94cb108f3da7b2c2d88c1ed...1f04c8df1dff08799ce0b58b6d97c15d3bc161c2

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-gui-agent_3.2.7+deb9u1` has been pushed to the `r3.2` testing repository for the Debian `stretch` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `stretch-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-gui-agent-linux/compare/6a2bcca991b25eb3c94cb108f3da7b2c2d88c1ed...1f04c8df1dff08799ce0b58b6d97c15d3bc161c2

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-gui-agent_3.2.8+deb8u1` has been pushed to the `r3.2` stable repository for the Debian `jessie` template.
To install this update, please use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-gui-agent-linux/compare/9d46f9005c60d0c63bb4c23003c7d88afac0dc0e...27e5c20cccb887911100d96685200f3c927abfee

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-gui-vm-3.2.9-1.fc23` has been pushed to the `r3.2` stable repository for the Fedora `fc23` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-gui-agent-linux/compare/6a2bcca991b25eb3c94cb108f3da7b2c2d88c1ed...6027be219c5861188bb8300edf59255516937bb0

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-gui-vm-3.2.9-1.fc24` has been pushed to the `r3.2` stable repository for the Fedora `fc24` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-gui-agent-linux/compare/6a2bcca991b25eb3c94cb108f3da7b2c2d88c1ed...6027be219c5861188bb8300edf59255516937bb0

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-gui-agent_3.2.8+deb9u1` has been pushed to the `r3.2` stable repository for the Debian `stretch` template.
To install this update, please use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-gui-agent-linux/compare/9d46f9005c60d0c63bb4c23003c7d88afac0dc0e...27e5c20cccb887911100d96685200f3c927abfee

**Comment by marmarek** [comment]
The bug resurfaced on fresh stretch template (no Kali involved).
