### ISSUE TITLE
Qubes R3.2 (XFCE) breaks ability to run HVM in fullscreen mode?

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#2371]
#### Qubes OS version (e.g., `R3.1`):

R3.2 with XFCE.

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):

dom0

---

### Expected behavior:

When clicking on the window title of a HVM -> fullscreen, HVM should open in fullscreen. Same should happen for ctrl + f.

### Actual behavior:

Nothing happens.

### Steps to reproduce the behavior:

1. Install some Linux derivative into a HVM.

2. Try to maximize the window.

This was possible in previous versions. Perhaps KDE vs XFCE makes a difference?

**Comment by marmarek** [comment]
Ctrl+f was never default shortcut for this, maybe your custom one? Also the only configuration when resizing HVM window is supported (and ever was), is Windows, with Qubes Windows Tools installed. Otherwise the only thing you can do, is to change screen resolution from inside of HVM.
