### ISSUE TITLE
xscreensaver does not have power management enabled by default

### ISSUE THREAD

**Issue by osresearch** [QubesOS/qubes-issues#2373]
#### Qubes OS version:
R3.2

---

### Expected behavior:

When xscreensaver is invoked it should power down the display in addition to blanking it, to reduce power consumption and backlight lifetime.

### Actual behavior:

Display remains powered, backlight is still on, power consumption is high.

### Steps to reproduce the behavior:

Wait a few minutes.

### General notes:

The correct(?) behaviour can be selected in System Settings - xscreensaver - Advanced - Display Power Management, "Power management enabled" and "Quick Power-off in Blank Only Mode".

---

**Comment by andrewdavidwong** [comment]
This comes down to the user's personal preference. Neither way is "correct."

**Comment by bigdx** [comment]
Well, I was about to file this behavior as issue as I would expect this as default.

**Comment by andrewdavidwong** [comment]
[We just inherit the upstream defaults.](https://www.qubes-os.org/faq/#what-is-qubes-attitude-toward-changing-guest-distros) If you think they should be changed, that request should be filed with the XScreenSaver or Fedora maintainers.
