### ISSUE TITLE
Firefox and Chrome play two frames of video, then stop

### ISSUE THREAD

**Issue by osresearch** [QubesOS/qubes-issues#2374]
#### Qubes OS version:
R3.2

#### Affected TemplateVMs:
fedora-23, anon-whonix

---

### Expected behavior:
Firefox and Chrome will play video and audio on youtube, twitter, etc.

### Actual behavior:
The first frame is displayed, sometimes the second one as well, then the video freezes. On youtube the video seeks fine; I can click elsewhere on the timeline and the new frame will display, but then freeze.  It's not a network buffering issue -- the gray "loaded" progress bar continues to show that the rest of the video has been loaded.

### Steps to reproduce the behavior:
Start Firefox or chrome in an appvm, click on any youtube video.

### General notes:
Reproduced on an x230 and Chromebook, both with integrated i915 graphics.

---

**Comment by andrewdavidwong** [comment]
This is a hardware-specific issue, which is too localized for `qubes-issues`. Please consider posting this to the `qubes-users` mailing list instead. (You can read more about our mailing lists [here](https://www.qubes-os.org/mailing-lists/).)

`qubes-users` is intended for these sorts of questions and receives much more traffic, which means that your question is more likely to receive a response there.
