### ISSUE TITLE
Consider using libinput drivers

### ISSUE THREAD

**Issue by jpouellet** [QubesOS/qubes-issues#2375]
I would like to suggest using `xorg-x11-drv-libinput` due mainly to its significantly improved inertial scrolling handling.

#### Qubes OS version (e.g., `R3.1`):

R3.2, but perhaps all

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):

dom0

---

### Expected behavior:

Under synaptics drivers, scrolling to the bottom of a web page, then pressing control-tab (or control-anything) causes firefox and chrome to zoom the current page because it is still receiving wheel-down events from (unintended) intertial scrolling, which are now combined with the control key, and this is a (not-easily-disableable) shortcut for page zooming in at least firefox and chrome.

### Actual behavior:

Web pages randomly zoom in and out all the time, in greatly maddening fashion.

### Steps to reproduce the behavior:

With active browser window, quickly swipe up or down with two fingers to initiate scrolling, then remove hand from touchpad, and press control key.

If your driver exhibits this issue, you almost certainly already know what I'm talking about.

### General notes:

This behavior keeps getting reported to browsers, but it's not browsers' fault.
- https://bugs.chromium.org/p/chromium/issues/detail?id=253697
- https://bugs.chromium.org/p/chromium/issues/detail?id=178972
- https://bugs.chromium.org/p/chromium/issues/detail?id=254612

The libinput drivers already get installed if you choose to install KDE in the installer.

`xorg-x11-drv-libinput` can safely be installed alongside `xorg-x11-drv-synaptics`, and X11 will prefer libinput. Although, I'm not sure why you'd want to keep the synaptics drivers around...

**Comment by maltfield** [comment]
Can someone please add to this ticket a link to the documentation for how to switch back from libinput to the synaptic drivers in dom0?
