### ISSUE TITLE
qubes-pdf-converter does not require ImageMagick

### ISSUE THREAD

**Issue by thardeck** [QubesOS/qubes-issues#2380]
#### `fedora-23-minimal`

---

### Expected behavior:
If I install qubes-pdf-converter converting a PDF to a trusted one should work.

### Actual behavior:
In Nautilus I get  the following error message:
```
Page 1 conversion failed (RGB->PNG):/usr/lib/qubes/qpdf-convert-client: line 105: convert: command not found
```

### Steps to reproduce the behavior:
Clone the `fedora-23-minimal` template, install the package `qubes-pdf-converter` and `nautilus`, create a vm from it and run `nautilus` and convert a pdf by clicking right mouse button and select "Convert to Trusted PDF".

### General notes:
The package `qubes-img-converter` will most likely be also affected but I did not try it.

Both packages should require ImageMagick if they need it to work properly.

Btw. without the package `ImageMagick` the icons in Dom0 are also broken, only the default one is shown. So maybe it should be even part of the minimal template.

---

#### Related issues:
Issue #2071 might be related. I was unable to copy files with Nautilus inbetween VMs without the package `pycairo` so this might also affect this issue. I just have fixed this before running into this issue.

**Comment by marmarek** [comment]
Minimal template have specifically excluded ImageMagick package (even when present in package requirements - which is the case here), to make template more minimal. You need to install it manually.

**Comment by unman** [comment]
@marmarek Isn't the issue that these packages should have ImageMagick as a dependency?

**Comment by marmarek** [comment]
There is appropriate dependency. But minimal template have a hack (named
`qubes-template-minimal-stub`) to avoid installing selected packages.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?
