### ISSUE TITLE
Improve error reporting when user attempts to remove a VM that is set as "NetVM for DispVM" for another VM

### ISSUE THREAD

**Issue by cyrinux** [QubesOS/qubes-issues#2382]
#### Qubes OS version (e.g., `R3.1`):

3.2
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):

All

---
### Expected behavior:

Clic remove or qvm-remove a vm
### Actual behavior:

Got
Traceback (most recent call last):
  File "/usr/bin/qvm-remove", line 112, in <module>
    main()
  File "/usr/bin/qvm-remove", line 109, in main
    qvm_collection.save()
  File "/usr/lib64/python2.7/site-packages/qubes/qubes.py", line 687, in save
    element = vm.create_xml_element()
  File "/usr/lib64/python2.7/site-packages/qubes/modules/000QubesVm.py", line 2142, in create_xml_element
    attrs = self.get_xml_attrs()
  File "/usr/lib64/python2.7/site-packages/qubes/modules/000QubesVm.py", line 2131, in get_xml_attrs
    value = attr_config['save']()
  File "/usr/lib64/python2.7/site-packages/qubes/modules/000QubesVm.py", line 235, in <lambda>
    if self.dispvm_netvm is not None \
  File "/usr/lib64/python2.7/site-packages/qubes/modules/000QubesVm.py", line 655, in dispvm_netvm
    return self._collection[self._dispvm_netvm]
KeyError: 38
### General notes:

---

**Comment by cyrinux** [comment]
I suspect a xml lint issue in my qubes.xml? But how to be sure of this? I can't say really seens which action this error appears.

**Comment by marmarek** [comment]
VM you're trying to remove is set as "DispVM NetVM" for some other VM.
Change it to other VM first.
Anyway, this should be better reported...

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by cyrinux** [comment]
Hi Marek,

I understand but it seems to not be this case. I don't see where appvm  (no
proxy or netvm) are set as netvm for dispvm.
How to check this without qubes-manager?
With qvm-ls? In which file this info is stored?

And with this error I can't also change template   for a vm. I get same
error.

Thanks you

**Comment by andrewdavidwong** [comment]
@cyrinux: Suppose the VM you want to remove is a ProxyVM called `sys-proxy`. Suppose that you have an AppVM called `untrusted`, and in the Advanced tab of the VM Settings for `untrusted`, you have the following setting:

    NetVM for DispVM: sys-proxy

You must change this from `sys-proxy` to some other entry in that list before you can remove `sys-proxy`.

**Comment by cyrinux** [comment]
Thanks.
I have switch to none all dispvm entries in qubes.xml
After reboot it is ok

**Comment by marmarta** [comment]
It looks like https://github.com/QubesOS/qubes-core-admin/pull/86 is the correct fix - in the case described here instead of an error, the dispvm_netvm is correctly set to None and nothing painful happens. It looks like this one can be closed.
