### ISSUE TITLE
Add support for updates proxy in VPN doc

### ISSUE THREAD

**Issue by tasket** [QubesOS/qubes-issues#2383]
#### Qubes OS version (e.g., `R3.1`):

R3.1, R3.2
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):

fedora-23, debian-8, debian 9 upgrade

---
### Expected behavior:

TemplateVMs connected through a VPN VM described in the doc should receive the benefits of the the qubes updates proxy so updates can proceed as usual.
### Actual behavior:

TemplateVM updates are blocked.
### Steps to reproduce the behavior:

Set TemplateVM to use VPN VM as its 'netvm'. Tell template to update.
### General notes:

https://www.qubes-os.org/doc/vpn/
https://groups.google.com/d/msgid/qubes-users/9091424ebc3fdf63cf1e757d83fcb21c.webmail%40localhost

---

**Comment by unman** [comment]
@andrewdavidwong Can you close this
