### ISSUE TITLE
Electrum in whonix portion severely outdated

### ISSUE THREAD

**Issue by Severance13** [QubesOS/qubes-issues#2384]
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):
debian 8, whonix-ws/gs

---

### Expected behavior:
bitcoin transactions should transfer as expected

### Actual behavior:
transactions rejected by the network because of the outdated package
### Steps to reproduce the behavior:
Update the whonix module (if possible), update debian version used (if possible), route Electrum through fedora 8
### General notes:

---

**Comment by marmarek** [comment]
This is because Debian ships such outdated package. But newer one is available in backports:
https://packages.debian.org/search?keywords=electrum
https://backports.debian.org/Instructions/

**Comment by 3n7r0p1** [comment]
Documented here: https://www.whonix.org/wiki/Money#Electrum
