### ISSUE TITLE
Link to Qubes users counter missing?

### ISSUE THREAD

**Issue by rootkovska** [QubesOS/qubes-issues#2385]
Can't find it anymore...

https://www.qubes-os.org/counter/

**Comment by andrewdavidwong** [comment]
It's still under News -> Statistics in the footer. Would you like additional links in other places too?

**Comment by rootkovska** [comment]
Oh, you're right. For some reason I couldn't find it this morning for a while :)

**Comment by andrewdavidwong** [comment]
Oh, that's probably because I changed the order of those entries (moved it up to third; before it was last).
