### ISSUE TITLE
monitors not waking from DPMS suspend

### ISSUE THREAD

**Issue by esheltone** [QubesOS/qubes-issues#2387]
This is on Qubes R3.2 - I never experienced the issue on previous Qubes versions.

After my displays are put into DPMI suspend/poweroff, they will not turn back on, despite keyboard and mouse use.  On my system, I have two monitors - one connected via DVI, and the other via HDMI.

This problem is easily repeated by executing 'xset dpms force suspend'.  The monitors go blank, and go into power saving mode.  However, I cannot wake them back up.

The problem appears to be discussed at https://bugzilla.xfce.org/show_bug.cgi?id=11627 which suggests the patch at https://bugzilla.xfce.org/show_bug.cgi?id=11107 post #53 fixes the issue.  If so, that patch appears to be included in xfce-settings 4.12.1

**Comment by adrelanos** [comment]
I am also affected by this.

esheltone:
> xfce-settings

You probably mean xfce4-settings.

> If so, that patch appears to be included in xfce-settings 4.12.1

Can I get that single newer package installed somehow?

**Comment by bburky** [comment]
I *think* I had the same issue as this. After disconnecting and reconnecting HDMI, or switching inputs on the display, the screen stayed black and did not reconnect. As I use a desktop computer, this means I had no display at all.

However, running `xrandr --output HDMI2 --auto` will force the HDMI port to work again. This must be run each time the display is reconnected.

Following [more or less these instructions](https://ruedigergad.com/2012/01/28/hotplug-an-external-screen-to-your-laptop-on-linux/) I set up a udev script in dom0 to automatically reconnect the display. As I only have one display, I omitted `--left-of LVDS1`. Also, some reason I had to add a `sleep 1` to the top of the script to make it work.

Anyways, I hope that workaround helps someone. Of course, preferably xcfe4 could be updated to avoid all this.

**Comment by marmarek** [comment]
@bburky I think this is a different problem. Recent versions of either X server, or desktop environments (I'm not sure which one) automatically disable outputs when you physically disconnect it. And do not restore configuration if you reconnect it. This is very annoying behavior. Confirmed also on bare-metal Fedora 24 installation.
The only option about that in Xfce I've found is to detect when you plug some output in and *ask* you what to do about it. Not very helpful if that was your only video output...

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
