### ISSUE TITLE
Make Travis CI great again

### ISSUE THREAD

**Issue by Rudd-O** [QubesOS/qubes-issues#2393]
Just noticed that Travis sometimes fails:

https://travis-ci.org/QubesOS/qubes-core-agent-linux/jobs/169963844

```
I: Retrieving zlib1g 1%3a1.2.8.dfsg-2+b1

I: Validating zlib1g 1%3a1.2.8.dfsg-2+b1

E: Couldn't download packages: debian-keyring

+ echo 'Error in debootstrap'

Error in debootstrap

+ exit 1

make[1]: *** [/home/travis/qubes-builder/chroot-stretch/home/user/.prepared_base] Error 1

make: *** [core-agent-linux-vm] Error 1

The command "~/qubes-builder/scripts/travis-build" exited with 2.

Done. Your build exited with 1.
```

This is a sort of a retryable error.  The driver that calls the build should tee the output/error of the script and  analyze it in realtime.  If there is a failure that is retryable, then the driver should retry the exact same operation.

**Comment by marmarek** [comment]
The same happens with Fedora... Currently I manually click retry button. It isn't such a big deal to spend time on automated solution. But if you have too much free time, feel free to work on this ;)
There is related issue: https://github.com/QubesOS/qubes-issues/issues/1424

**Comment by iamahuman** [comment]
Qubes has replaced Travis with GitLab since then. It may be a good idea to either close or retarget this issue.

**Comment by marmarek** [comment]
Indeed this does not apply to gitlab.
