### ISSUE TITLE
Create "qubes-announce" mailing list

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#2395]
[Discussion thread](https://groups.google.com/d/topic/qubes-users/DyhXNAueNmE/discussion)

Which types of announcements should be included on this list?
- QSBs
- New Qubes releases
- Canaries (?)

**Comment by marmarek** [comment]
List created: qubes-announce@googlegroups.com. Remaining tasks:
 - add it to https://www.qubes-os.org/mailing-lists/
 - send announcement to qubes-users (and qubes-devel?)

@andrewdavidwong can you take care of it?

**Comment by andrewdavidwong** [comment]
@marmarek: Yes, no problem.

**Comment by andrewdavidwong** [comment]
@marmarek: We need to decide which types of announcements will occur in this list first. Canaries: yes or no?

**Comment by marmarek** [comment]
IMO there is no need to announce canaries to majority of users. Rather lack of them if anything, but that is not us who could do that...

**Comment by andrewdavidwong** [comment]
Ok, so only QSBs and new releases, then?

**Comment by marmarek** [comment]
Yes.

**Comment by andrewdavidwong** [comment]
If we plan to have qubes-announce mirrored on Gmane, I can add a section on that once it's up. Otherwise, I think we're done here.

**Comment by marmarek** [comment]
Good idea about Gmane. They are currently under some major rework and I think it isn't possible to add new groups there right now... Details: http://home.gmane.org/

**Comment by andrewdavidwong** [comment]
This list is live, and we needn't wait on Gmane to close this issue.
