### ISSUE TITLE
Add "mirrors" section to download page

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#2401]
Thanks to RWTH Aachen University generosity we've just got one more mirror: http://ftp.halifax.rwth-aachen.de/qubes/

Our current "downloads" page doesn't scale well for multiple mirrors, so I think we need some better layout there. Or just just additional section with mirrors list.

**Comment by andrewdavidwong** [comment]
ISTM that many download pages adopt essentially the same layout -- one row per mirror. Do you really think ours scales worse?

**Comment by marmarek** [comment]
Yes, because we already have multiple rows per mirror - one for each release.

**Comment by andrewdavidwong** [comment]
Yes, but most other download pages do that, too. Anyway, we can improve on what others do rather than following their lead. :) Working on it now.

**Comment by andrewdavidwong** [comment]
@marmarek: Would you prefer one row per release with an additional mirrors section? If so, should the single row link to mirrors.kernel.org?

**Comment by marmarek** [comment]
IMO there should be one row per download type: HTTP, Torrent. Then yes - additional mirrors section, with a link to that section easily visible (near/in "source" column? like: source: mirrors.kernel.org; see other mirrors).
As for the main link - mirrors.kernel.org seems good.

**Comment by andrewdavidwong** [comment]
@marmarek: What do you think of the page now?

**Comment by marmarek** [comment]
There is a typo for digests URL for torrent: `hhttps://`...
Otherwise it looks fine, thanks!
