### ISSUE TITLE
"yes to all" does nothing on qrexec service call with specific argument 

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#2403]
#### Qubes OS version (e.g., `R3.1`):

R3.2
### Expected behavior:

"always allow" permission is saved for this particular service argument
### Actual behavior:

Nothing happens.
### Steps to reproduce the behavior:

Call a service with some argument.
### General notes:

Reported by @Rudd-O

> if I say "yes to all" when there is an argument
> (it's already in the code I just pushed to Github) then nothing actually
> gets saved as "yes to all" anywhere.  In other words: there's a bug as
> "Yes to all" does nothing when an argument is specified.

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-dom0-linux-3.2.8-1.fc23` has been pushed to the `r3.2` testing repository for dom0.
To test this update, please install it with the following command:
```
sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-admin-linux/compare/2768b22494df8d44e4989bcc81420cc0cc9e01f6...c15841c8281e8075ab1f63fcee06ff79089286c4

**Comment by Rudd-O** [comment]
I think this fix is wrong.  I have detailed the fix here: https://github.com/marmarek/qubes-core-admin-linux/commit/1dff6361b7ca1c7b26d52cd00ca0cedceef2ac00#commitcomment-19626640

**Comment by marmarek** [comment]
As discussed below the commit, copying generic policy to the argument specific one, at the time of first "yes to all" isn't the best idea. Better would be including generic one from specific one. But this must be done explicitly to avoid unwanted side effects.

Assumptions and constrains
-----------

1. Behavior of already existing configuration cannot change. Especially, every policy file have implicit "deny all".
2. It should be obvious what and when will be processed, without referring to specification. Explaining things in (reasonably short) comments in the file itself is ok.
3. It should be defensive by design. Better have spurious deny in case of user error, than spurious allow.

Proposal 1
-------------

Add `$include:some-name` syntax, as the only entry in the line. Some name would be a file name in `/etc/qubes-rpc/policy` (or more formally: in directory with qrexec policy). This statement would continue processing policy to the named file. Because of implicit deny at the file end, it makes sense only as the last entry - entries after that would be after "end of included file", so after implicit "deny all". Implementation should throw a warning if any non-comment is found after such statement. When such files are created automatically, should contain a comment "entries after $include:... are ignored".
Maybe better name it somehow else than `$include` to better suggest this behavior?

Proposal 2
-------------

Similar to "Proposal 1", but without implicit deny at the end of _included_ file. On the one hand it will be more flexible, but on the other hand it makes the file have implicit deny and sometime have not, depending on how the file is loaded. This somehow violates requirement no 2. But at the same time, it's better match for keyword `$include:...`.

**Comment by Rudd-O** [comment]
Cool!  I'll take a look at this again when I wake up.

-- 
    Rudd-O
    http://rudd-o.com/

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
