### ISSUE TITLE
failed to start kernel-moduls load((((((((((((((((((((((((

### ISSUE THREAD

**Issue by userqubes** [QubesOS/qubes-issues#2405]
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):
help!!!!!!!!!!!!!!!!!!!!!!!!!

https://drive.google.com/drive/folders/0B2IQWDSFURY1b0s4ZFpLa1A4WGM?usp=sharing

**Comment by andrewdavidwong** [comment]
This is not appropriate for `qubes-issues`. Please send this to the `qubes-users` [mailing list](https://www.qubes-os.org/mailing-lists/) instead.

**Comment by adrelanos** [comment]
Is https://github.com/QubesOS/qubes-issues/issues/1546 a duplicate of this?
