### ISSUE TITLE
Renaming VM works partially

### ISSUE THREAD

**Issue by irr3** [QubesOS/qubes-issues#2407]
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):

When renaming a VM in the manager ("personal" -> "personal-fedora"), it is not shown with the new name in the manager -- however, the new name does show up in the menu.

Afterwards, the VM can no longer be renamed and other stuff fails as well..

---

### General notes:

---

**Comment by andrewdavidwong** [comment]
What kind of "other stuff" fails?

**Comment by andrewdavidwong** [comment]
Check in `/var/lib/qubes/appvms` (in dom0). Has the VM directory been renamed there? You can try renaming it correctly there, but make a backup first.

**Comment by irr3** [comment]
Sorry, I just reinstalled it to fix it. *g*

I do believe it should be fairly easy to reproduce.

Other stuff means the manager and the menu are seriously out of sync, e.g. I can delete the qube in the manager, it stays in the menu ..

**Comment by andrewdavidwong** [comment]
If anyone can reproduce this, please let us know.

**Comment by jpouellet** [comment]
Unfortunately it seems I'm not able to reproduce, but I have definitely hit this before and had to kill qubes-manager and go edit the xml manually to correct.

**Comment by Drubble** [comment]
I may have gotten the same problem as well #2561
