### ISSUE TITLE
qvm-start over ssh error: xprop:  unable to open display ''

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#2408]
#### Qubes OS version (e.g., `R3.1`):

R3.2

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):

Probably any.

---

### Expected behavior:

Should just work.

### Actual behavior:

```
qvm-start whonix-gw
```

```
--> Loading the VM (type = TemplateVM)...
--> Starting Qubes DB...
--> Setting Qubes DB info for the VM...
--> Updating firewall rules...
--> Starting the VM...
--> Starting the qrexec daemon...
Waiting for VM's qrexec agent....connected
--> Starting Qubes GUId...
xprop:  unable to open display ''
Traceback (most recent call last):
  File "/usr/bin/qvm-start", line 136, in <module>
    main()
  File "/usr/bin/qvm-start", line 120, in main
    xid = vm.start(verbose=options.verbose, preparing_dvm=options.preparing_dvm, start_guid=not options.noguid, notify_function=tray_notify_generic if options.tray else None)
  File "/usr/lib64/python2.7/site-packages/qubes/modules/000QubesVm.py", line 2030, in start
    extra_guid_args=extra_guid_args)
  File "/usr/lib64/python2.7/site-packages/qubes/modules/000QubesVm.py", line 1786, in start_guid
    ['xprop', '-root', '-notype', 'KWIN_RUNNING']) == \
  File "/usr/lib64/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['xprop', '-root', '-notype', 'KWIN_RUNNING']' returned non-zero exit status 1
```

### Steps to reproduce the behavior:

1) connect to Qubes dom0 by ssh
2) qvm-start some-template

**Comment by marmarek** [comment]
You need either set `DISPLAY` environment variable, or pass `--no-guid` to skip GUI initialization.

**Comment by adrelanos** [comment]
Glad that exists!

Could that be auto detected? Or fail better than with a traceback?

**Comment by marmarek** [comment]
One is not supposed to access Qubes dom0 via ssh... I see your point, but this is really low prio.

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-dom0-3.2.12-1.fc23` has been pushed to the `r3.2` testing repository for dom0.
To test this update, please install it with the following command:
```
sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-admin/compare/f80e67391e5d83607decc15d612049eca1ee4798...bd35a1061b605b630adf628bc077dc1b098c34a7

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-dom0-3.2.12-1.fc23` has been pushed to the `r3.2` stable repository for dom0.
To install this update, please use the standard update command:
```
sudo qubes-dom0-update
```
Or update dom0 via Qubes Manager.

[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-admin/compare/f80e67391e5d83607decc15d612049eca1ee4798...bd35a1061b605b630adf628bc077dc1b098c34a7
