### ISSUE TITLE
Qubes OS usb management 

### ISSUE THREAD

**Issue by ukn0wwh0** [QubesOS/qubes-issues#2413]
Qubes OS version (R3.2):
Affected TemplateVMs (fedora-23):
Expected behavior:
remove the usb drive and unmount it from VM
Actual behavior:
when removing usb using qvm-block -d dom0:sdb for example, can't use it for another usb till next reboot, or mount it in other VMs.
mount a usb stick than remove it using qvm-block -d ....  and insert another usb stick to the same one.

**Comment by unman** [comment]
@ukn0wwh0 
Works for me using a usbVM.
Can you set up sys-usb and confirm the issue there?
Also can you provide any info re your hardware? Do you see any error messages?

**Comment by andrewdavidwong** [comment]
@ukn0wwh0: Your description is unclear. I can't understand the problem you're describing. Please try rephrasing.

**Comment by andrewdavidwong** [comment]
Closing due to lack of response.
