### ISSUE TITLE
Allow changing default storage pool

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#2415]
In current implementation pool named "default" is special in the sense that `qvm-create` will use it if no other is specified. But it is just normal pool. Especially, it can't be easily renamed, it stays as "default" in VM storage settings etc.

This means there is no easy way for changing default storage pool in the system (for new VMs).

Proposal: add global property `default_pool`, then during VM creation patch volume_config with value pointed there. The same way as `qvm-create -P` is handled.
@kalkin if you have nothing against, I'll implement this.

**Comment by andrewdavidwong** [comment]
@kalkin replied with :+1:
(posting as a comment since GitHub doesn't send notifications for reactions)

**Comment by marmarek** [comment]
Done.
