### ISSUE TITLE
Sleep/resume does not refresh external monitor resolution

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#2420]
#### Qubes OS version (e.g., `R3.1`):

R3.2

---

[On 2016-11-06 14:34, yaqu wrote:](https://groups.google.com/d/msgid/qubes-users/20161106223414.10544103B33%40mail2.openmailbox.org)
> When I work on laptop with lid closed and external monitor connected,
> and when I suspend Qubes, reconnect it to another docking station with
> different monitor, and wake it up, then screen on external monitor has
> old resolution, not matching resolution of currently connected monitor.
> 
> Is it possible to force (or politely convince) xfce4 to autodetect
> resolution after wake up from suspend? Just like it used to work on KDE?
> 
> As a workaround I use custom script in /usr/lib/systemd/system-sleep/
> that executes on wake up:
> 
> xrandr --output HDMI1 --auto --output HDMI2 --auto

**Comment by yaqu** [comment]
I have checked Fedora 24 Xfce Desktop and its behaviour is exactly the same - after resume, resolution of external monitor is not updated.

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
