### ISSUE TITLE
Changing screen resolution makes domU elements in bottom half of screen noninteractive

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#2421]
#### Qubes OS version (e.g., `R3.1`):

R3.2

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):

---

[On 2016-11-06 14:34, yaqu wrote:](https://groups.google.com/d/msgid/qubes-users/20161106223414.10544103B33%40mail2.openmailbox.org)
> When I
> change resolution from lower to higher, some icons in tray at the
> bottom of the screen are not accessible - no tooltip on hoover, no
> response to click. It looks like only icons of appVM apps are affected
> (NetworkManager, Psi, Remmina, KeePass...), and icons of dom0 apps work
> correctly (volume control, power manager, qubes manager). Tray needs to
> be on bottom of screen, of course.
> 
> I have found out that to make these icons work again, I have to switch
> on or off any of connected displays.
> 
> This issue can be reproduced even without external monitors. Assuming
> laptop's LCD is on LVDS1, one needs to switch it to some low resolution
> and then back to default:
> 
> [user@dom0 ~]$ xrandr --output LVDS1 --mode "800x600"; sleep 3; xrandr
> --output LVDS1 --auto
> 
> Now icons are not accessible. To fix it one needs to turn LCD off and
> on:
> 
> [user@dom0 ~]$ xrandr --output LVDS1 --off; xrandr --output LVDS1 --auto
> 
> 
> BTW now as I tested it, it looks that not only tray icons are not
> accessible. The bottom half of the screen is not clickable for appVM
> applications.

---

#### Related issues:

#1599 (might not be closely related)

**Comment by cyrinux** [comment]
Hi, I have similar problem since about 3 weeks. (I update all everyday). I
use two work with 2 screens horizontally. When I two screen, I can't click
anymore on the right screen. I used i3wm.

**Comment by andrewdavidwong** [comment]
@cyrinux: Thanks for reporting. Your issue sounds closer to #1599, though.

**Comment by cyrinux** [comment]
Yes @andrewdavidwong it is that ;)

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-gui-dom0-3.2.7-1.fc23` has been pushed to the `r3.2` testing repository for dom0.
To test this update, please install it with the following command:
```
sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-gui-daemon/compare/8f097ec116cd0ac8bc5e11a6b73642349ff8ee26...53a3b1acf4b426d431024536c5f5dbfa0c2e2dc3
