### ISSUE TITLE
Debian Stretch: Renaming template does not fix /etc/hosts file.

### ISSUE THREAD

**Issue by qubenix** [QubesOS/qubes-issues#2425]
#### Qubes OS version (e.g., `R3.1`):

R3.2

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):

Debian-9 (Stretch)

---

### Expected behavior:

Renaming template will fix `/etc/hosts` file accordingly with the new name.

### Actual behavior:

Old name stays in `/etc/hosts` file and causes hang ups executing commands.

### Steps to reproduce the behavior:

Create a debian-9 template. Shutdown and rename. Start template and check `/etc/hosts` file.

### General notes:

I've tested on a Debian-8 template and the issue does not exist.

---

**Comment by unman** [comment]
Interestingly, I've been building a Xenial template and noticed a similar issue, with the hosts file not being rewritten for template based qubes. I thought it was an error in the template build. Perhaps not?

**Comment by marmarek** [comment]
Can you paste `/etc/hosts` from such system?

**Comment by qubenix** [comment]
`/etc/hosts` contents:

    127.0.0.1localhost
    ::1localhost ip6-localhost ip6-loopback debian-9
    ff02::1ip6-allnodes
    ff02::2ip6-allrouters
    
    127.0.1.1 debian-9

I had to manually change `debian-9` from the old name of `d9`, then restart the template for it to take effect.

**Comment by unman** [comment]
So, I **don't** see this behaviour on a vanilla deb8-deb9 upgraded template. Renaming the upgraded template works just fine, and is reflected in /etc/hosts.
@qubenix  is this the same upgrade where you reported problems with QXcb?

On Xenial this is the root of the problem:

```
root@my-new-vm:/home/user# systemctl status qubes-sysinit
● qubes-sysinit.service - Init Qubes Services settings
   Loaded: loaded (/lib/systemd/system/qubes-sysinit.service; enabled; vendor preset: enabled)
   Active: active (exited) since Thu 2016-11-10 01:18:26 UTC; 4min 0s ago
  Process: 203 ExecStart=/usr/lib/qubes/init/qubes-sysinit.sh (code=exited, status=0/SUCCESS)
 Main PID: 203 (code=exited, status=0/SUCCESS)
    Tasks: 0 (limit: 512)
   CGroup: /system.slice/qubes-sysinit.service

Nov 10 01:18:25 localhost systemd[1]: Starting Init Qubes Services settings...
Nov 10 01:18:26 my-new-vm qubes-sysinit.sh[203]: sed: couldn't open temporary file /etc/sedYfGv5h: Read-only file system
Nov 10 01:18:26 my-new-vm qubes-sysinit.sh[203]: sed: couldn't open temporary file /etc/sedhGdeRi: Read-only file system
Nov 10 01:18:26 my-new-vm qubes-sysinit.sh[203]: ln: cannot remove '/etc/localtime': Read-only file system
Nov 10 01:18:26 my-new-vm qubes-sysinit.sh[203]: /usr/lib/qubes/init/qubes-sysinit.sh: 93: /usr/lib/qubes/init/qubes-sysinit.sh: cannot create /etc/timezone: Read-only file system
Nov 10 01:18:26 my-new-vm systemd[1]: Started Init Qubes Services settings.
```

**Comment by marmarek** [comment]
@unman this is already fixed in master, new package will be "soon". @qubenix check status of `qubes-sysinit.service`, it may be the same issue.

**Comment by unman** [comment]
Cheers

**Comment by qubenix** [comment]
Doesn't show anything here:

    user@debian-9:~$ systemctl status qubes-sysinit.service
    ● qubes-sysinit.service - Init Qubes Services settings
       Loaded: loaded (/lib/systemd/system/qubes-sysinit.service; enabled; vendor pr
       Active: active (exited) since Wed 2016-11-09 20:17:48 MST; 5min ago
     Main PID: 256 (code=exited, status=0/SUCCESS)
        Tasks: 0 (limit: 4915)
       CGroup: /system.slice/qubes-sysinit.service

But here is some stuff:

    sudo cat /var/log/syslog | grep sysinit
    Sep  6 20:00:06 localhost systemd[1]: Found ordering cycle on sysinit.target/stop
    Sep  6 20:00:06 localhost systemd[1]: Found dependency on sysinit.target/stop
    Sep  6 20:00:06 localhost systemd[1]: Job rpcbind.service/stop deleted to break ordering cycle starting with sysinit.target/stop
    Nov  9 10:41:02 debian-9 qubes-sysinit.sh[250]: sed: couldn't open temporary file /etc/sed3CB8I5: Read-only file system
    Nov  9 10:41:02 debian-9 qubes-sysinit.sh[250]: sed: couldn't open temporary file /etc/sedIRjPA5: Read-only file system
    Nov  9 10:41:02 debian-9 qubes-sysinit.sh[250]: ln: cannot remove '/etc/localtime': Read-only file system
    Nov  9 10:41:02 debian-9 qubes-sysinit.sh[250]: /usr/lib/qubes/init/qubes-sysinit.sh: 93: /usr/lib/qubes/init/qubes-sysinit.sh: cannot create /etc/timezone: Read-only file system
    Nov  9 10:46:22 debian-9 qubes-sysinit.sh[255]: sed: couldn't open temporary file /etc/sedf7sjb6: Read-only file system
    Nov  9 10:46:22 debian-9 qubes-sysinit.sh[255]: sed: couldn't open temporary file /etc/sed8kGr15: Read-only file system
    Nov  9 10:46:22 debian-9 qubes-sysinit.sh[255]: ln: cannot remove '/etc/localtime': Read-only file system
    Nov  9 10:46:22 debian-9 qubes-sysinit.sh[255]: /usr/lib/qubes/init/qubes-sysinit.sh: 93: /usr/lib/qubes/init/qubes-sysinit.sh: cannot create /etc/timezone: Read-only file system
    Nov  9 15:06:33 localhost qubes-sysinit.sh[255]: sed: couldn't open temporary file /etc/sedQ4yyvR: Read-only file system
    Nov  9 15:06:33 localhost qubes-sysinit.sh[255]: sed: couldn't open temporary file /etc/sedVVcTaQ: Read-only file system
    Nov  9 15:06:33 localhost qubes-sysinit.sh[255]: ln: cannot remove '/etc/localtime': Read-only file system
    Nov  9 15:06:33 localhost qubes-sysinit.sh[255]: /usr/lib/qubes/init/qubes-sysinit.sh: 93: /usr/lib/qubes/init/qubes-sysinit.sh: cannot create /etc/timezone: Read-only file system
    Nov  9 20:17:49 localhost qubes-sysinit.sh[256]: sed: couldn't open temporary file /etc/sed3polWz: Read-only file system
    Nov  9 20:17:49 localhost qubes-sysinit.sh[256]: sed: couldn't open temporary file /etc/sedJqLIDy: Read-only file system
    Nov  9 20:17:49 localhost qubes-sysinit.sh[256]: ln: cannot remove '/etc/localtime': Read-only file system
    Nov  9 20:17:49 localhost qubes-sysinit.sh[256]: /usr/lib/qubes/init/qubes-sysinit.sh: 93: /usr/lib/qubes/init/qubes-sysinit.sh: cannot create /etc/timezone: Read-only file system

**Comment by unman** [comment]
@qubenix It's the same issue and is, as Marek says, fixed in master.

**Comment by qubenix** [comment]
Closing since already fixed.

**Comment by andrewdavidwong** [comment]
We might need to keep this open for `github-builder` tracking. @marmarek?

**Comment by marmarek** [comment]
It's ok to close it, as I cannot amend already pushed fix.
