### ISSUE TITLE
XDG_DATA_DIRS not set in Xenial desktop

### ISSUE THREAD

**Issue by unman** [QubesOS/qubes-issues#2430]
#### Qubes OS version (e.g., `R3.1`):
R3.2
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):
Xenial-desktop

---

### Expected behavior:
Gnome Applications open.

### Actual behavior:
Applications do not open.
Starting from command line gives error:
> GLib-GIO-ERROR  No GSettings schemas are installed on the system

### General notes:
XDG_DATA_DIRS is set to :/var/lib/snapd/desktop - 
the value should be set in /etc/X11/Xsession.d/55gnome-session_gnomerc
It isn't set because the session isn't set to gnome-session*

---

#### Related issues:
#2065 ?

**Comment by marmarek** [comment]
Why some gnome-specific script should do that? It looks `/etc/X11/Xsession.d/60x11-common_xdg_path` also set it, if `$DESKTOP_SESSION` is set to anything. Is `$DESKTOP_SESSION` set?

**Comment by unman** [comment]
On Fri, Nov 11, 2016 at 05:42:11PM -0800, Marek Marczykowski-Górecki wrote:
> Why some gnome-specific script should do that? It looks `/etc/X11/Xsession.d/60x11-common_xdg_path` also set it, if `$DESKTOP_SESSION` is set to anything. Is `$DESKTOP_SESSION` set?
> 
You're right it should.
No, $DESKTOP_SESSION isn't set.

**Comment by unman** [comment]
It could be set in /etc/X11/Xsession.d/25xdg-qubes-settings.
Any issue with that?

**Comment by andrewdavidwong** [comment]
I'm sure how to categorize this issue, since I don't know what "Xenial-desktop" is. So, I [googled it](https://www.google.com/search?q=%22xenial-desktop%22), and it appears to be a version of Ubuntu. Since we didn't have an Ubuntu label, I created one and applied it to this issue. If any of that is incorrect, please let me know.

**Comment by marmarek** [comment]
I'm trying to find where this variable is set "normally", but could not. Any idea?

**Comment by unman** [comment]
@andrewdavidwong That's a good idea. I'm working on Qubes providing a ubuntu template, so having a separate label makes sense.
@marmarek No: I haven't been able to find that. It doesn't seem to be set in other templates

**Comment by marmarek** [comment]
I meant bare metal Ubuntu installation. Anyway, if we can't find how it should be set, `/etc/X11/Xsession.d/25xdg-qubes-settings` may be fine. But make sure to not override it if already set.

**Comment by unman** [comment]
@andrewdavidwong On reflection it would be better to put Ubuntu and Debian issues together under a Debian tag. I think almost all issues will be common. If there comes a stage where we have substantial Ubuntu specific problems then we could reinstate a separate tag.

**Comment by andrewdavidwong** [comment]
@unman: Done.

**Comment by unman** [comment]
So this could go as a conditional patch in gui-agent-linux or in linux-template-builder: as it's the first release of the template we could put it there to have from the start. Thoughts?

**Comment by marmarek** [comment]
Definitely not linux-template-builder. It should be as minimal as possible - all actual files, modifications etc should be done by some package. Otherwise it will be hard to change that in the future using ordinary update.
