### ISSUE TITLE
Shutdown template after update

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#2431]
[feature request](https://groups.google.com/d/msgid/qubes-users/39d4981f-fc90-2588-9b00-30133c6e1d86%40openmailbox.org) by @evadogstar

> After template updated ask user at the console to shutdown current template.
> "Shutdown current template [Y/n]"

**Comment by andrewdavidwong** [comment]
Please make sure to implement this in a way that does not break automated update scripts like [this one](https://gist.github.com/andrewdavidwong/d0b109186de65835255d467ae103c289).

**Comment by marmarek** [comment]
Sure, it will be done in update script called by Qubes Manager, so shouldn't affect any automated thing.

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `python2-dnf-plugins-qubes-hooks-3.2.13-1.fc23` has been pushed to the `r3.2` testing repository for the Fedora `fc23` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.2-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/3b65f98db832159a14a9cc9489ac0b80b8ddecb0...938d184ef484170b4a1e3e2a4634c54cf684772c

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `python2-dnf-plugins-qubes-hooks-3.2.13-1.fc24` has been pushed to the `r3.2` testing repository for the Fedora `fc24` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.2-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/3b65f98db832159a14a9cc9489ac0b80b8ddecb0...938d184ef484170b4a1e3e2a4634c54cf684772c

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-agent_3.2.13-1+deb8u1` has been pushed to the `r3.2` testing repository for the Debian `jessie` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `jessie-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/dd30d913750481f05160c4bff74545e315bf9f2e...938d184ef484170b4a1e3e2a4634c54cf684772c

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-agent_3.2.13-1+deb9u1` has been pushed to the `r3.2` testing repository for the Debian `stretch` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `stretch-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/dd30d913750481f05160c4bff74545e315bf9f2e...938d184ef484170b4a1e3e2a4634c54cf684772c

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-agent_3.2.13-1+deb8u1` has been pushed to the `r3.2` stable repository for the Debian `jessie` template.
To install this update, please use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/1a601ddbe9bae11088a78136bfe7cd8a1b3258f1...938d184ef484170b4a1e3e2a4634c54cf684772c

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `python2-dnf-plugins-qubes-hooks-3.2.13-1.fc23` has been pushed to the `r3.2` stable repository for the Fedora `fc23` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/3b65f98db832159a14a9cc9489ac0b80b8ddecb0...938d184ef484170b4a1e3e2a4634c54cf684772c

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `python2-dnf-plugins-qubes-hooks-3.2.13-1.fc24` has been pushed to the `r3.2` stable repository for the Fedora `fc24` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/3b65f98db832159a14a9cc9489ac0b80b8ddecb0...938d184ef484170b4a1e3e2a4634c54cf684772c
