### ISSUE TITLE
Installer video not working on Thinkpad X201t

### ISSUE THREAD

**Issue by lorentrogers** [QubesOS/qubes-issues#2432]
#### Qubes OS version (e.g., `R3.1`): 

R3.1

### Expected behavior: 

The installer would boot and video would display normally.

### Actual behavior: 

After choosing to install, it displays a warped display of the load text. (I assume.)

### Steps to reproduce the behavior: 

- Launch Qubes installer, choose install now. (The test and install option simply crashes.)
- Wait for it to launch. It should continue, but instead it sits in this state:

![img_20161113_181122](https://cloud.githubusercontent.com/assets/1090824/20250008/af205da8-a9d4-11e6-9721-256c41ba5ff4.jpg)

**Comment by andrewdavidwong** [comment]
This question is too localized for `qubes-issues`. Please consider posting this to the `qubes-users` mailing list instead. (You can read more about our mailing lists [here](https://www.qubes-os.org/mailing-lists/).)

`qubes-users` is intended for these sorts of questions and receives much more traffic, which means that your question is more likely to receive a response there.

**Comment by lorentrogers** [comment]
Thanks for pointing me in the right direction! I posted this to the list.

**Comment by lorentrogers** [comment]
For those with similar issues, this is the answer I got from the mailing list:

> i also use an X201t. the issue is with vt-d, which you have to temporarily disable. see https://www.qubes-os.org/doc/thinkpad-troubleshooting/
> 
> its mostly usable, but does get slow. even web browsing can get choppy.

Loren

**Comment by andrewdavidwong** [comment]
Thanks, Loren!
