### ISSUE TITLE
Installer repeats configuration steps every time button is pressed

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#2433]
#### Qubes OS version (e.g., `R3.1`):

R3.2

---

In the Installer, on the "Initial Setup" step, the user can click a button under "System." This button has the Qubes logo and the text "QUBES OS". Each time this button is clicked, the installer appears to repeat the configuration steps, even if they have already been performed.

**Comment by diffusae** [comment]
Also exist in R4.0rc5. Templates aren't setup correctly, if you run it twice.
