### ISSUE TITLE
VM restart after update throws dom0 error

### ISSUE THREAD

**Issue by saucemcboss** [QubesOS/qubes-issues#2438]
#### Qubes OS version (e.g., `R3.1`):

R3.2 on a Thinkpad X201 Tablet

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):

Dom0 -- Qubes Manager

---

### Expected behavior:

Updating and restarting a VM should not throw an error

### Actual behavior:

Restarting after installing software gives "Dom0 Houston, we have a problem"

```
----
line: assert not vm.is_running()
func: start_vm
line no.: 1158
file: /usr/lib64/python2.7/site-packages/qubesmanager/main.py
----
line: self.caller.start_vm(vm)
func: check_if_vm_has_shutdown
line no.: 288
file: /usr/lib64/python2.7/site-packages/qubesmanager/main.py
```

### Steps to reproduce the behavior:

I've gotten this a couple times, and I'm not yet able to find a pattern. It seems like it's after I update software within the VM template. Once I finish restarting the app VM, it throws this error.

### General notes:

It may also be worth noting that I'm having a few issues with random & incomplete shutdowns. Once I see a broader pattern I'll report that in another issue, but I felt it may be worth mentioning.

It was quite difficult to report this issue -- there was no way to easily copy the text from the dom0 error pane into my personal VM. A more streamlined process would likely lead to better error reporting.

I'm not entirely sure if this is the right place to report this error. After hunting around, I assume that this is the right place, but as I found in #2432, the email group may be better. It may be worth considering clarifying where issues should go from the dom0 error window itself.

[err.txt](https://github.com/QubesOS/qubes-issues/files/595100/err.txt)

![screenshot_2016-11-16_10-45-02](https://cloud.githubusercontent.com/assets/1090824/20354014/c4d64c8a-abea-11e6-8a60-20f052983306.png)

![screenshot_2016-11-16_10-45-25](https://cloud.githubusercontent.com/assets/1090824/20354015/c4d6e500-abea-11e6-9ce6-c4a544620d89.png)

---

**Comment by lorentrogers** [comment]
It may also be worth noting that my template VM was still running when I restarted the app VM. I realize now that this wouldn't update the software in the template, but I didn't remember that at the time.

**Comment by lorentrogers** [comment]
I posted a note to the form about my shutdown issues here: https://groups.google.com/forum/#!topic/qubes-users/OGWbC6AUnFU

**Comment by andrewdavidwong** [comment]
> It was quite difficult to report this issue -- there was no way to easily copy the text from the dom0 error pane into my personal VM. A more streamlined process would likely lead to better error reporting.

There are a few different options for [copying and pasting text from dom0](https://www.qubes-os.org/doc/copy-paste/#copypaste-between-dom0-and-other-domains), depending on the purpose.
But perhaps all error panes should have an easy button to copy the text to the inter-VM clipboard. What do you think, @marmarek?

> I'm not entirely sure if this is the right place to report this error. After hunting around, I assume that this is the right place, but as I found in #2432, the email group may be better. It may be worth considering clarifying where issues should go from the dom0 error window itself.

This seems like the right place. GitHub should present you with a link to view the [contribution guidelines](https://github.com/QubesOS/qubes-issues/blob/master/CONTRIBUTING.md) each time you open an issue. Error windows in dom0 can appear for many different reasons, and I doubt the system can be programmed to accurately determine what kind of issue it is according to our guidelines. (That would probably require strong AI.) For the most part, though, error messages in dom0 should probably be reported here.

**Comment by lorentrogers** [comment]
Perfect - thanks for the info. Streamlining (or automating) the bug reporting process as much as possible should help collect more bugs. Copying to the Inter-VM clipboard would be a good start. I'd also suggest having some simple text on what to do with the error like "Please report this to the Qubes team either by email at <email?>, or on Github at <url>." I imagine the email lists would be an easy way to report for those not on Github.

**Comment by andrewdavidwong** [comment]
> I'd also suggest having some simple text on what to do with the error like "Please report this to the Qubes team either by email at , or on Github at ." I imagine the email lists would be an easy way to report for those not on Github.

That text is here: https://www.qubes-os.org/doc/reporting-bugs/

**Comment by lorentrogers** [comment]
Sounds good - any direction in the error message on where / how to report would be helpful.
