### ISSUE TITLE
The Video Tutorial interactive ToC is broken

### ISSUE THREAD

**Issue by rootkovska** [QubesOS/qubes-issues#2439]
The ToC on the right side of the main video here:
https://www.qubes-os.org/video-tours/

... no longer makes the player skip to the corresponding parts of the main Video. Instead, it starts playback of the French video below.

**Comment by andrewdavidwong** [comment]
Thanks for spotting that! Fixed.

**Comment by andrewdavidwong** [comment]
(Might need to clear your browser's cache for the CSS.)
