### ISSUE TITLE
qubes-builder leaves unmounted filesystems

### ISSUE THREAD

**Issue by tezeb** [QubesOS/qubes-issues#2440]
When building templates(tested on archlinux, but looking at Makefile it seems that it affects all dists), after build is finished mounts done during dist-prepare-chroot make target are not unmounted. As there are even 3 scripts for handling unmounts(https://github.com/QubesOS/qubes-issues/issues/1157), it would be nice to use them.

The issue is that cleaning repo(ie. rm -Rf) requires using sudo, as there are root owned files inside(chroot-contents), but using it with proc/sys etc mounted is probably not the best idea.

This happens when building Archlinux template for Qubes R3.2.
### Expected behavior:
`make COMPONENT-vm` shall not leave fs mounted
### Actual behavior:
`make COMPONENT-vm` leaves all dist specific directories mounted
### Steps to reproduce the behavior:
in qubes-builder, run
./setup
make qubes-vm

**Comment by marmarek** [comment]
This is intentional behavior, see https://github.com/QubesOS/qubes-builder/commit/74c2d043ef79b145e0f1800464c416abe46820a1 for reasoning.
If you want to cleanup - see `make clean` targets (`make help` can be of use). It will umount what's needed first. Also you can just call `make umount`.
