### ISSUE TITLE
Cannot create Win7 hvm from dom0 on Toshiba laptop L645-S4102

### ISSUE THREAD

**Issue by kingneutron** [QubesOS/qubes-issues#2441]
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable): N/A

---

### Steps to reproduce the behavior: 
`@dom0 ~]$ qvm-create win7 --hvm --label blue`

### General notes:
Dom0 has the latest package updates available as of this writing and the host laptop has been rebooted / tried again, still did not work. ~293GB of free disk space in "/" according to df.

Host info: Toshiba Satellite L645-S4102 with 4GB RAM, dual-core CPU @ 2.13GHz,  500GB HD, X resolution 1366x768
Note: VT-x IS enabled in the BIOS already - have not tried updating BIOS yet

REF: Trying to follow these instructions:
https://www.qubes-os.org/doc/hvm/

```
[dave@dom0 ~]$ qvm-create win7 --hvm --label blue
--> Creating directory: /var/lib/qubes/appvms/win7
--> Creating volatile image: /var/lib/qubes/appvms/win7/volatile.img...
--> Creating icon symlink: /var/lib/qubes/appvms/win7/icon.png -> /usr/share/icons/hicolor/128x128/devices/appvm-blue.png
Traceback (most recent call last):
  File "/usr/bin/qvm-create", line 223, in <module>
    main()
  File "/usr/bin/qvm-create", line 201, in main
    vm.create_on_disk(verbose=options.verbose, source_template=template)
  File "/usr/lib64/python2.7/site-packages/qubes/modules/01QubesHVm.py", line 220, in create_on_disk
    self._update_libvirt_domain()
  File "/usr/lib64/python2.7/site-packages/qubes/modules/000QubesVm.py", line 755, in _update_libvirt_domain
    raise e
libvirt.libvirtError: invalid argument: could not find capabilities for arch=x86_64 
```

---

#### Related issues:
Filing bug report first, then trying BIOS flash to latest-version available and trying again to create --hvm

**Comment by kingneutron** [comment]
Updated laptop BIOS from 1.70 to latest-available 2.70, EC version 2.30 and still getting the same error. However, with the latest BIOS the *option* to enable VT-x has disappeared. (It was verified Enabled before BIOS flash/update.)

 libvirt.libvirtError: invalid argument: could not find capabilities for arch=x86_64

# cat /proc/cpuinfo
processor	: 1
vendor_id	: GenuineIntel
cpu family	: 6
model		: 37
model name	: Intel(R) Pentium(R) CPU        P6200  @ 2.13GHz
stepping	: 5
microcode	: 0x2
cpu MHz		: 2128.044
cache size	: 3072 KB
physical id	: 0
siblings	: 2
core id		: 2
cpu cores	: 2
apicid		: 4
initial apicid	: 4
fpu		: yes
fpu_exception	: yes
cpuid level	: 11
wp		: yes
flags		: fpu de tsc msr pae mce cx8 apic sep mca cmov pat clflush acpi mmx fxsr sse sse2 ss ht syscall nx lm constant_tsc arch_perfmon rep_good nopl nonstop_tsc pni monitor est ssse3 cx16 popcnt hypervisor lahf_lm arat dtherm
bugs		:
bogomips	: 4256.08
clflush size	: 64
cache_alignment	: 64
address sizes	: 36 bits physical, 48 bits virtual
power management:

--It's not completely a showstopper (for me) because I still have a Win7 instance I can natively boot into, but it seems like it (creating an --hvm) should be working from what the cpu flags are saying.  However the actual specs I found seem to indicate that the processor does *not* have VT-x support (so what was it doing in the original BIOS?)

http://ark.intel.com/products/50176/Intel-Pentium-Processor-P6200-3M-Cache-2_13-GHz
Intel® Virtualization Technology (VT-x) ‡ 	No

--If the processor isn't capable, I guess close this as a documentation instead of a bug :-\
Hoping someone with more knowledge of the processor can comment on this.

**Comment by andrewdavidwong** [comment]
I'm afraid it looks like your CPU does *not* support VT-x. (@marmarek, please confirm.)

> If the processor isn't capable, I guess close this as a documentation instead of a bug :-\

I'm not sure what you mean by "a documentation" here. Is there some way our documentation can be improved? It seems like the older version of your BIOS was at fault for misleading by providing the option to enable VT-x, which the BIOS vendor subsequently fixed by removing that option. (Meanwhile, your CPU never supported VT-x all along.)

**Comment by marmarek** [comment]
> I'm afraid it looks like your CPU does not support VT-x. (@marmarek, please confirm.)

If ark.intel.com have "VT-x: no" I think this is the problem.

Anyway I'm surprised in this particular error message - normally lack of VT-x result in much clearer message: `Cannot start HVM without VT-x/AMD-v enabled`. Wait, your message is during creation of the VM, so even before trying to start it.

**Comment by kingneutron** [comment]
@andrewdavidwong , Qubes webpage has a "supported hardware" link ( https://www.qubes-os.org/hcl/ ); while I initially intended to report this laptop as "supported hardware" it turned out not to be, so that should go in the documentation to warn future testers.

> I'm not sure what you mean by "a documentation" here. Is there some way our documentation can be improved?

**Comment by andrewdavidwong** [comment]
@kingneutron: I don't see your laptop model in the HCL. Has it been added yet? If not, please reply to your thread (the one in which you submitted your HCL info), stating that it should not be used.
