### ISSUE TITLE
qvm-ls --raw-data: also remove the []{}=> chars

### ISSUE THREAD

**Issue by rootkovska** [QubesOS/qubes-issues#2444]
Just make it easier to write bash scripts, avoid piping through additional tr -d :)

**Comment by jpouellet** [comment]
I am currently relying on this in one of my scripts, and using `--raw-list` where plain names are desired. I'm more than happy to change my parsing as I think it would actually simplify things anyway, but one question I even had at the time was what Qubes interfaces should be considered stable. This would be nice to have an actual policy on.

As for the specifics of this case, I can easily change it to check `ip back != n/a` and `type = Tpl`.

That leaves only `=>`. What do you suggest is the best way to expose that?

**Comment by jpouellet** [comment]
FWIW, core3 looks like the stable interface I *actually* want.

**Comment by marmarek** [comment]
> That leaves only =>. What do you suggest is the best way to expose that? Additional field hidden from default view?

See `qubes-prefs`.

> FWIW, core3 looks like the stable interface I actually want.

The ugliness of the current interface (and the code behind it) is one of the reason for core3...

@rootkovska does `--raw-list` solve your case? Otherwise I think we may introduce new field like `raw_name` to not break compatibility.

**Comment by jpouellet** [comment]
There is also `<dispN>`
