### ISSUE TITLE
Make it easier to report dom0 errors

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#2450]
Two main tasks:
1. Make an easy button to copy text from dom0 error windows to the inter-VM clipboard.
2. Provide link to https://www.qubes-os.org/doc/reporting-bugs/ so that users can find out how to correctly report their bugs.

For details, see discussion: https://github.com/QubesOS/qubes-issues/issues/2438#issuecomment-261704575

**Comment by jpouellet** [comment]
I propose a general solution to getting error messages out of dom0 here: https://groups.google.com/forum/#!topic/qubes-devel/4_x7Su21i9o

The idea is to facilitate general copying from the dom0 X clipboard to the qubes clipboard (and *not* the other way around). IMO this is a better idea than trying to add "copy to clipboard" buttons everywhere, as such an approach can never be complete (for example errors in a terminal from running e.g. qubes-dom0-update, etc.).

Feedback on that mailing list thread welcome :)

**Comment by andrewdavidwong** [comment]
Whatever the solution, it needs to be easily discoverable by novice users. Our current situation is a UX failure, with large numbers of new Qubes users manually typing long error messages and tracebacks into emails and GitHub issues because they're unaware that it's possible to copy text out of dom0.

**Comment by jpouellet** [comment]
@andrewdavidwong Do you think a "Copy dom0 clipboard to global Qubes clipboard" (but better named... open to suggestions) menu item in the Qubes manager tray icon menu would be discoverable enough?

Ideally I would like a consistent Ctrl+Shit+C to just work in Dom0, but this poses technical challenges as discussed in the above linked mailing list thread.

**Comment by andrewdavidwong** [comment]
> Do you think a "Copy dom0 clipboard to global Qubes clipboard" (but better named... open to suggestions) menu item in the Qubes manager tray icon menu would be discoverable enough?

I'm not sure. I'm not a UX expert. Maybe.

**Comment by marmarek** [comment]
> I'm not sure. I'm not a UX expert. Maybe.

Me neither, but I think it should be ok, if additionally documented at
least here: https://www.qubes-os.org/doc/reporting-bugs/

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by andrewdavidwong** [comment]
Yes, I think it would help.
