### ISSUE TITLE
Skip VMs without states defined in salt top file _only_ when executing operation using that top file

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#2451]
Currently `qubesctl` tool skip VMs for which top file is empty (it checks `state.show_top id=VMNAME`). It is sensible for `state.highstate` which would do nothing, but break usage of other commands, like giving state to apply from command line (`state.single`, `state.apply`, `state.sls`...), or even directly calling some salt module.

**Comment by maertsen** [comment]
I have tested https://github.com/QubesOS/qubes-mgmt-salt/pull/7/commits/5fc8aee09d60e01ec7db372bed5d1efbfe3f8aa5 and can confirm this solves #2718 for me, including using that same method via https://github.com/QubesOS/qubes-desktop-linux-manager/pull/34.

Thanks for fixing this, this really simplifies my update workflow.
