### ISSUE TITLE
Boot fails if /boot was not reformatted during install

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#2457]
#### Qubes OS version (e.g., `R3.1`):

3.2

---

According to  @baffo32 in https://github.com/QubesOS/qubes-issues/issues/2419#issuecomment-261817824:

Boot fails if /boot was not reformatted during install. You cannot re-use an existing /boot partition.

It is unclear whether this is a bug or intended behavior.

---

#### Related issues: 

Split from #2419 along with #2445.

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.

**Comment by xloem** [comment]
hey @andrewdavidwong, I'm still using my systems this way, but haven't upgraded to Qubes 4.  Do you know whether the issue has been fixed in Qubes 4?

**Comment by andrewdavidwong** [comment]
> hey @andrewdavidwong, I'm still using my systems this way, but haven't upgraded to Qubes 4. Do you know whether the issue has been fixed in Qubes 4?

Sorry, I don't know.
