### ISSUE TITLE
Implement regression tests for qrexec-policy

### ISSUE THREAD

**Issue by jpouellet** [QubesOS/qubes-issues#2460]
Having one would catch issues like https://github.com/QubesOS/qubes-gui-daemon/pull/10

**Comment by marmarek** [comment]
There are some:
https://github.com/QubesOS/qubes-core-admin/blob/master/tests/vm_qrexec_gui.py#L532-L639
https://github.com/QubesOS/qubes-core-admin/blob/master/tests/vm_qrexec_gui.py#L1010-L1046
But apparently this case isn't covered.

**Comment by jpouellet** [comment]
Superseded by qubespolicy (not qrexec-policy) for R4: https://github.com/marmarek/qubes-core-admin/commit/2124ecdaec10f93aa4ccc237c91eec847859ab49
