### ISSUE TITLE
Document "copy to dom0 clipboard" tray item functionality for reporting bugs

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#2464]
Branched from #2450:

Once it is available in a stable release, the new "copy to dom0 clipboard" tray item should be documented on this page:

https://www.qubes-os.org/doc/reporting-bugs/

**Comment by jpouellet** [comment]
Or perhaps this page: https://www.qubes-os.org/doc/copy-paste/
and then point to it from https://www.qubes-os.org/doc/reporting-bugs/

**Comment by andrewdavidwong** [comment]
Yes, that would also work.
