### ISSUE TITLE
Stuck on Starting Windows

### ISSUE THREAD

**Issue by blissjoe** [QubesOS/qubes-issues#2467]
#### Qubes OS version (e.g., `R3.1`):

3.2

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):

Windows 7 Pro 64bit - https://www.qubes-os.org/doc/hvm/
---

### Expected behavior:

I expect Windows to start from the ISO and allow me to install.

### Actual behavior:

After creating the HVM and booting it with the ISO, the loading bar finishes and Starting Windows is displayed. The installation never proceeds passed Starting Windows. The Windows logo continues to glow on and off.

### Steps to reproduce the behavior:

Follow the installation guide on a fresh and updated install of Qubes 3.2. I tried booting the ISO from local disk and a USB CD drive. 

My laptop is a x220 with Coreboot. The hard drive is a Samsung 850 Pro 512GB SSD.

All three ISOs were retrieved directly from the Microsoft MSDN program.

Windows 7 Pro 64bit
Windows 7 Pro 64bit w/ SP1
Windows 7 Enterprise 64bit

### General notes:

I was able to install Windows 10 using this method, but it is unusable because my screen resolution is too small. 

Please let me know if any other information will be useful.

**Comment by cyrinux** [comment]
Hi,
- You must copy your config in 
cp /var/lib/qubes/appvms/windows7/windows7.conf ~/

- Then at the bottom change graphic driver xen by cirrus
vim ~/windows7.conf
-> change xen by cirrus at the bottom

Start the vm and install with
qvm-start windows7 --custom-config=~/windows7.conf

All credit to a missing post in the qubes-users mailing

**Comment by blissjoe** [comment]
Fantastic, That did resolve the issue. Thank you.

**Comment by jpouellet** [comment]
for future people: relevant post mentioned above is https://groups.google.com/d/msg/qubes-users/2q19jFeTFGk/DgL6a67_CAAJg

more details at: https://github.com/QubesOS/qubes-issues/issues/2488

**Comment by benkhlifafahmi** [comment]
@cyrinux Thanks for your solution 👍
