### ISSUE TITLE
Dell Inspiron 17 7999 HDMI not working

### ISSUE THREAD

**Issue by jonathannqc** [QubesOS/qubes-issues#2471]
#2468 
Hi guys. I install cube 3.2 on my inpiron and it's working nicely except for the hdmi port. I need to connect a projector to my computer but dom0 do not recognize it. Any idea why? Thanks

**Comment by andrewdavidwong** [comment]
This is not appropriate for `qubes-issues`. Please send this to the `qubes-users` [mailing list](https://www.qubes-os.org/mailing-lists/) instead.
