### ISSUE TITLE
qvm-move-to-vm removes unrelated files

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#2472]
#### Qubes OS version (e.g., `R3.1`):

R3.2

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):

all

---

### Expected behavior:

`qvm-move-to-vm` should send required files to other VM and then (after successful operation) remove them locally.

### Actual behavior:

File/directory named after target VM is removed too.

### Steps to reproduce the behavior:

1. Create directory named after target VM, or have one already with very important files inside. In my case I was in `qubes-builder`, which have `doc` directory.
2. Execute `qvm-move-to-vm`, like this: `qvm-move-to-vm doc some-unrelated-file`
3. Observe that your `doc` directory is gone.

### General notes:

qvm-move-to-vm:
```
. qvm-copy-to-vm "$@" &&
rm -rf -- "$@"
```

`$@` is all arguments, including target VM name.

**Comment by rustybird** [comment]
Shit, will fix this ASAP

**Comment by rustybird** [comment]
The v2 pull requests make `qvm-move-to-vm` a symlink to `qvm-copy-to-vm`, which removes the files (or not) depending on the last component of `$0`. This way, it doesn't matter if `qvm-copy-to-vm` accepts additional arguments, such as `--without-progress`.

Sorry for introducing this bug!

**Comment by marmarek** [comment]
Thanks @rustybird for prompt fix!

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-agent_3.1.20-1+deb8u1` has been pushed to the `r3.1` testing repository for the Debian `jessie` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `jessie-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/1d74a449676cf31f41a17a6dff21be6246529740...550b8f2dcdf33c082a09db872c1d939789a546b9

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-agent_3.1.20-1+deb9u1` has been pushed to the `r3.1` testing repository for the Debian `stretch` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `stretch-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/1d74a449676cf31f41a17a6dff21be6246529740...550b8f2dcdf33c082a09db872c1d939789a546b9

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-agent_3.1.20-1+deb7u1` has been pushed to the `r3.1` testing repository for the Debian `wheezy` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `wheezy-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/1d74a449676cf31f41a17a6dff21be6246529740...550b8f2dcdf33c082a09db872c1d939789a546b9

**Comment by rustybird** [comment]
Please reopen, this was closed prematurely by the vm PR's commit message. The dom0 PR is still pending: https://github.com/QubesOS/qubes-core-admin-linux/pull/16

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-dom0-linux-3.2.11-1.fc23` has been pushed to the `r3.2` testing repository for dom0.
To test this update, please install it with the following command:
```
sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-admin-linux/compare/73ba5f805b38b67c62b0162c8fd407f3f1e0f2a4...4f0878ccbf8a95f8264b54d2b6f4dc433ca0793a

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `python2-dnf-plugins-qubes-hooks-3.2.15-1.fc23` has been pushed to the `r3.2` testing repository for the Fedora `fc23` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.2-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/938d184ef484170b4a1e3e2a4634c54cf684772c...fb8c356216f693eca09665dd03219e83c7bd1c03

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `python2-dnf-plugins-qubes-hooks-3.2.15-1.fc24` has been pushed to the `r3.2` testing repository for the Fedora `fc24` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.2-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/938d184ef484170b4a1e3e2a4634c54cf684772c...fb8c356216f693eca09665dd03219e83c7bd1c03

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `python2-dnf-plugins-qubes-hooks-3.2.15-1.fc25` has been pushed to the `r3.2` testing repository for the Fedora `fc25` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.2-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-agent-linux/compare/938d184ef484170b4a1e3e2a4634c54cf684772c...fb8c356216f693eca09665dd03219e83c7bd1c03
