### ISSUE TITLE
Add "About" page

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#2475]
[On 2016-12-01 15:43, Chris Laprise wrote:](https://groups.google.com/d/msgid/qubes-devel/5575ddf7-f52d-0d1e-a0f4-effa642fa61e%40openmailbox.org)
> One other thing I feel is missing is an 'About' section that could describe Qubes' story as a project that started at ITL and evolved. Its not the same thing as what 'funding' and 'team' describe. 'About' could be its own page or merely a section of 'intro' or 'team'.

**Comment by mfc** [comment]
just a note, this sounds more like "History" than "About". Most folks who are interested in what a project is "about" don't want to read the history of a project's evolution over time, just what the project is currently about.

**Comment by andrewdavidwong** [comment]
True. It could be both, if we have things to say about both.

**Comment by andrewdavidwong** [comment]
I think we ended up deciding against this.

**Comment by mfc** [comment]
here's tor project's "history" page for inspiration: https://www.torproject.org/about/history/ , also debian's: https://www.debian.org/doc/manuals/project-history/

maybe there are some other good examples around.
