### ISSUE TITLE
Mount / with 'discard'?

### ISSUE THREAD

**Issue by jpouellet** [QubesOS/qubes-issues#2479]
I am wondering if there is a reason we do not enable discard for the root filesystem.

I just reclaimed ~10gb of real dom0 disk space by enabling discard on / in a particularly offending StandaloneVM (and dd-ing a bunch of garbage to a file & removing it).

I imagine doing so would afford similar savings for TemplateVMs which accumulate lots of update churn over time.

#### Relevant tickets:
- https://github.com/QubesOS/qubes-issues/issues/2478 (where I did some testing)

**Comment by marmarek** [comment]
For StandaloneVM it indeed may help, but for AppVM unfortunately not - `dm-snapshot` do not pass DISCARD operations to lower level. But if `dm-linear` do, it still may worth enabling it for / too, to have it working in StandaloneVM and TemplateVM. Do I understand correctly that you claim it do work there?

**Comment by jpouellet** [comment]
> Do I understand correctly that you claim it do work there?

Unless I am misinterpreting the below, yes:
```
[user@dom0 ~]$ qvm-ls -d standalone-discard-test
-------------------------+----+---------+-------+------+-------+-----------+----------+-----------+----------+---------+
                    name | on |   state | updbl | type | label | priv-curr | priv-max | root-curr | root-max |    disk |
-------------------------+----+---------+-------+------+-------+-----------+----------+-----------+----------+---------+
 standalone-discard-test |  * | Running |   Yes |      |   red |     65 MB |  2048 MB |   6170 MB | 10240 MB | 6648 MB |
[user@dom0 ~]$ qvm-run -p standalone-discard-test 'sudo dd if=/dev/urandom of=/var/garbage'
dd: writing to ___/var/garbage___: No space left on device
8045185+0 records in
8045184+0 records out
4119134208 bytes (4.1 GB) copied, 46.8408 s, 87.9 MB/s
[user@dom0 ~]$ qvm-ls -d standalone-discard-test
-------------------------+----+---------+-------+------+-------+-----------+----------+-----------+----------+----------+
                    name | on |   state | updbl | type | label | priv-curr | priv-max | root-curr | root-max |     disk |
-------------------------+----+---------+-------+------+-------+-----------+----------+-----------+----------+----------+
 standalone-discard-test |  * | Running |   Yes |      |   red |     65 MB |  2048 MB |  10097 MB | 10240 MB | 10575 MB |
[user@dom0 ~]$ qvm-run -p standalone-discard-test 'sudo rm /var/garbage'
[user@dom0 ~]$ qvm-ls -d standalone-discard-test
-------------------------+----+---------+-------+------+-------+-----------+----------+-----------+----------+---------+
                    name | on |   state | updbl | type | label | priv-curr | priv-max | root-curr | root-max |    disk |
-------------------------+----+---------+-------+------+-------+-----------+----------+-----------+----------+---------+
 standalone-discard-test |  * | Running |   Yes |      |   red |     65 MB |  2048 MB |   6170 MB | 10240 MB | 6647 MB |
[user@dom0 ~]$ qvm-ls -d standalone-discard-test
```

**Comment by tasket** [comment]
Is it worth it to simply add discard for '/' to templates, or will that result in slightly higher CPU usage in appVMs where discard requests are simply generated and forgotten?

I think it may be the former: Adding discard to the '/' entry in the templates is very easy fix that cascades to newly created standalone VMs, and appVMs would be trying to write to '/' only rarely so probably no performance hit.

**Comment by jpouellet** [comment]
If we do this, https://www.qubes-os.org/doc/template/debian/upgrade-8-to-9/#compacting-the-upgraded-template (and others) should be updated.

**Comment by tasket** [comment]
AFAIK, templates still need qvm-trim-template, so that doc would be the same. What the proposed change actually affects is the root fs of certain *standalone* VMs (which inherit /etc/fstab from templates).

If we assume that some users will opt to make moderate-heavy use of standalone VMs (from PVM templates), then this change will be a real benefit to them.

**Comment by tasket** [comment]
Actually, the upgrade docs could have a separate word about using 'fstrim /' internally after upgrading standalone VMs. Otherwise, I think there are very few other docs affected by this. We could put a blurb in doc/templates about standalone VMs generated from Linux/PVM templates: How they do not use COW on root fs and can fstrim it internally.

**Comment by andrewdavidwong** [comment]
@tasket: Added.

**Comment by tasket** [comment]
Oops, I added some also...
https://github.com/QubesOS/qubes-doc/pull/254

**Comment by tasket** [comment]
Since this is flagged as R4.0 I'll go ahead and state how relevant this is to the new release:

1. Templates now seem to easily trim their root volumes... Should be no special cases and no significant performance issues when adding discard to fstab.

2. dom0 root now has a problem where it expands too much, especially when backing up/restoring large amounts of data. Adding discard to root in the fstab should resolve this.

**Comment by tasket** [comment]
Thread:
https://groups.google.com/d/msgid/qubes-users/2a2ca8a8-a01b-5214-e954-96d4c92588dd%40posteo.net

**Comment by tasket** [comment]
Should this be re-opened for dom0? R4.0 disc allocation has dom0 lv on par with domU lvs -- the need to discard is the same. I've personally experienced a space shortage after restoring and also handling disk images and working with template packages in dom0.

Here is another thread:
https://groups.google.com/d/msgid/qubes-users/c4167148-718d-635a-b439-43b28ecedf1b%40riseup.net

**Comment by marmarek** [comment]
For dom0 it is tracked by #3226
