### ISSUE TITLE
The "Kill it" or "Wait 20 secs for VM to shutdown" dialog doesn't automatically exit once the VM shuts down.

### ISSUE THREAD

**Issue by lmffeexd** [QubesOS/qubes-issues#2485]
#### Qubes OS version:

`R3.2`

#### Affected TemplateVMs:

Every template.

---

### Expected behavior:

The "Kill it" or "Wait 20 secs for VM to shutdown" dialog should be automatically exited once the VM shuts down.

### Actual behavior:

The "Kill it" or "Wait 20 secs for VM to shutdown" dialog doesn't automatically exit once the VM shuts down.

### Steps to reproduce the behavior:

Start a TemplateVM, Shut it down, and see if that dialog appears. If it does, then leave it as is until the TemplateVM shuts down.

**Comment by 0spinboson** [comment]
related -> https://github.com/QubesOS/qubes-issues/issues/2254

**Comment by marmarek** [comment]
No longer an issue, since new qui-domains widget.
