### ISSUE TITLE
Windows HVM does not show in dual-head setup with one monitor in portrait mode

### ISSUE THREAD

**Issue by lorenzog** [QubesOS/qubes-issues#2487]
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable): N/A

---

### Steps to reproduce the behavior:

[requires a dual-head setup]
1. Disable the secondary display (System Tools -> Display -> untick 'use this display')
2. Fully install a Windows HVM with only one display enabled (with Qubes Tools)
3. Confirm Windows boots regularly
4. Enable the second display
5. Confirm this resolution
6. In the display layout, drag the second display to the left of the primary one, set the rotation to 'left' and drag again so that they form a top-left corner
7. Apply
8. Start the Windows HVM
9. The Windows HVM will be running, but not showing (e.g. it can be stopped with the VM manager)

To make it work:

1. Disable secondary display
2. Start Windows
3. Enable display
4. The Windows HVM window can now be dragged to either monitor and it shows its full resolution in vertical and horizontal mode

### General notes:

By trial-and-error I think the problem is in the resolution: with a dual monitor layout, and when monitors have different H/V resolutions, it "feels" like Xen is trying to pass the *full* monitor resolution by adding all horizontal and vertical pixels; and Windows refuses to boot.

Same issue happens with i3 (thus excluding XFCE as the main culprit).

Running applications in seamless mode does not change the behaviour: the application does not show up.
---

**Comment by andrewdavidwong** [comment]
Sounds somewhat reminiscent of #1896.

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
