### ISSUE TITLE
add list of which folders persist in TemplateBasedVMs and which do not to documentation

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#2489]
Probably save to add it on this page addressing advanced users:
https://www.qubes-os.org/doc/template-implementation/

But I think would also be useful to be added to some simple user documentation focused page. Is there already one where this fits, where template implementation and which folders are persistent is being explained or should a new one be created for that?

Suggested (part of the) content:

-----

== root image includes ==
* /bin
* /boot
* /dev
* /etc
* /home_volatile
* /home.orig
* /lib
* /lib64
* /lost+found
* /media
* /mnt
* /opt
* /proc
* /root
* /run
* /sbin
* /srv
* /sys
* /tmp
* /usr
* /var

Therefore will be lost after reboot.

== private image by default includes ==
* /home
* /rw
* /usr/local (/usr/local is a symlink to /rw/usrlocal)
* /var/spool/cron (default bind-dirs setting)

Therefore persists after reboot.

**Comment by andrewdavidwong** [comment]
> But I think would also be useful to be added to some simple user documentation focused page. Is there already one where this fits, where template implementation and which folders are persistent is being explained or should a new one be created for that?

Here: https://www.qubes-os.org/doc/templates/#important-notes

**Comment by andrewdavidwong** [comment]
@adrelanos, is this done?

**Comment by adrelanos** [comment]
Andrew David Wong:
> @adrelanos, is this done?
> 

Yes.
