### ISSUE TITLE
Setup Agent not appearing during installation

### ISSUE THREAD

**Issue by solvenus** [QubesOS/qubes-issues#2492]
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable): N/A

---

### General notes:
How do I initialize the setup agent so I can configure default VMs?

---

**Comment by solvenus** [comment]
I got the setup agent VM configuration screen the second time I tried to install Qubes now. But then other issues appeared. I will try to install for a third time.
The first time I installed Qubes OS 3.2 (today), when I didn't get the VM configuration post-install screen, I got into Qubes OS at least. Not this time. 
Third try a charm then. Let us see.

**Comment by solvenus** [comment]
All is well now. The third installation worked.

**Comment by solvenus** [comment]
Oh, please delete this issue thread. It was completely unnecessary. I would appreciate if it got deleted.

**Comment by andrewdavidwong** [comment]
FYI, it's not possible to completely delete a GitHub issue.

**Comment by solvenus** [comment]
Oh, I didn't know. My bad. Thanks for letting me know.
