### ISSUE TITLE
Installing in VM on Macbook Pro 2015 Retina

### ISSUE THREAD

**Issue by Mattel88** [QubesOS/qubes-issues#2493]
#### Qubes OS version (e.g., `R3.2`):
R3.2
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):

I tried to install QubesOS in Virtualbox on my Macbook and get the following error:

http://imgur.com/a/dx9oM

I can't fix it somehow. Is there any way to fix it?

**Comment by andrewdavidwong** [comment]
This question is too localized for `qubes-issues`. Please consider posting this to the `qubes-users` mailing list instead. (You can read more about our mailing lists [here](https://www.qubes-os.org/mailing-lists/).)

`qubes-users` is intended for these sorts of questions and receives much more traffic, which means that your question is more likely to receive a response there.
