### ISSUE TITLE
After having assigned an non-existing TemplateVM to an AppVM, Qubes VM Manager fails and does not allow to assign an existing TemplateVM

### ISSUE THREAD

**Issue by Wikinaut** [QubesOS/qubes-issues#2495]
#### Qubes OS version (e.g., `R3.2`):
R3.2

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):

Affected: Qubes VM-Manager

`Dom0 OSError Errno 2 file not found: /var/lib/qubes/vm-templates/fedora-23/apps.templates`

After having successfully 

* added fedora-24 as explained on https://www.qubes-os.org/news/2016/11/15/fedora-24-template-available/ and 
* removed fedora-23 as explained on https://www.qubes-os.org/doc/templates/

by performing these steps

```
$ sudo qubes-dom0-update qubes-template-fedora-24
(I now manually detached all AppVMs which were based on fedora-23 and assigned fedora-24)
$ sudo yum remove qubes-template-fedora-23
$ sudo rm ~/.local/share/applications/fedora-23-* (pls. fix the wrong number 21 in your example on https://www.qubes-os.org/doc/templates/ !)
```

#### How to reproduce:

I intentionally assigned `fedora-23`(remember: I deleted that intentionally) because this was still selectable in the Qubes VM Manager - to one of my AppVM "TestVM".

Now, of course, I cannot start that "TestVM".

```
Dom0 OSError [Errno 2] file not found: /var/lib/qubes/vm-templates/fedora-23/apps.templates
This is most likely a bug in the Qubes Manager.

line: template_file_list = os.listdir(template_dir)
func: fill_apps_list
line no.: 71
file: /usr/lib64/pythin2.7/site-packages/qubesmanager/appmenu_select.py
---
line: self.fill_apps_list()
func:__init__
line no.: 65
file: /usr/lib64/pythin2.7/site-packages/qubesmanager/appmenu_select.py
---
line: self.AppListManager = AppMenuSelectManager(self.vm, self.app_list)
func: __init__
line no.: 106
file: /usr/lib64/python2.7/site-packages/qubesmanager/settings.py
---
line: "basic")
func: action_settings_triggered
line no.: 1345
file: /usr/lib64/python2.7/site-packages/qubesmanager/main.py
```

#### Problem/Bug
Reassigning an existing template in Qubes VM Manager is **impossible**.

#### Suggested solution
Fix the error message and code behaviour, and let user allow to assign an existing TemplateVM.

**Comment by andrewdavidwong** [comment]
Ok, it sounds like the real problem is that `fedora-23` was still selectable as a TemplateVM in Qubes Manager even after you removed it. AFAIK, that shouldn't be possible.

```
$ sudo rm ~/.local/share/applications/fedora-23-* (pls. fix the wrong number 21 in your example on https://www.qubes-os.org/doc/templates/ !)
```

It's not "wrong." It's just an example. You're not supposed to copy that command verbatim; rather, it's an instance serving to illustrate the command.

**Comment by Wikinaut** [comment]
@andrewdavidwong 
> It's not "wrong." It's just an example. You're not supposed to copy that command verbatim; rather, it's an instance serving to illustrate the command.
This is clear to me, but in your examples on https://www.qubes-os.org/doc/templates/ , in the section directly above, you use "$ sudo yum remove qubes-template-fedora-23 [sic]". The two examples should use the *same* version number (in my view).

**Comment by marmarta** [comment]
It should not be possible in R4.0 (assigning the template will just fail), and the documentation has already been improved. I'm closing this one.
