### ISSUE TITLE
Consider moving qubes-menus to core-admin-linux

### ISSUE THREAD

**Issue by woju** [QubesOS/qubes-issues#2496]
`qubes-menus` RPM package currently lives in `desktop-linux-kde`. KDE is no longer the default DE in Qubes OS and people should be able to build Qubes OS without building KDE. That doesn't work, since Xfce4 package `garcon` depends on `qubes-menus`. Can we move `qubes-menus` RPM to `core-admin-linux`?

To: @marmarek

**Comment by marmarek** [comment]
Maybe we need `desktop-linux-common`?

**Comment by marmarek** [comment]
And maybe appmenus related scripts should be moved there? Reasoning is based on future Admin/GUI split - appmenus belongs to GUI domain.

**Comment by jpouellet** [comment]
I ran into exactly this when doing https://github.com/QubesOS/qubes-desktop-linux-xfce4/pull/6

> Maybe we need desktop-linux-common?

+1, this was my conclusion too.

There is also some deduplication of .desktop and .directory files that could be done, and may be easier within a single shared dependency repo.

**Comment by marmarek** [comment]
Done.
