### ISSUE TITLE
3.1-current-testing repo is missing latest qubes-windows-tools

### ISSUE THREAD

**Issue by 3n7r0p1** [QubesOS/qubes-issues#2499]
qubes-windows-tools-3.2.2-3.x86_64.rpm is latest version in 3.2-current-testing:
http://yum.qubes-os.org/r3.2/current-testing/dom0/fc23/rpm/

missing in 3.1-current-testing:
http://yum.qubes-os.org/r3.1/current-testing/dom0/fc20/rpm/

Seems compatible. Installed manually and no issues so far.

**Comment by andrewdavidwong** [comment]
@omeg, are they supposed to be in there?

**Comment by marmarek** [comment]
Should be there. And now it is.
