### ISSUE TITLE
[Security/Whonix] When updating the whonix-ws and whonix-gw templates, errors are shown

### ISSUE THREAD

**Issue by Wikinaut** [QubesOS/qubes-issues#2501]
[This post may be - then I apologize for it - off-topic w.r.t. Qubes. Please close then.]

I updated the two templates and noticed, that during updating strange error messages or warnings were shown like "server reports different file length"  or GPG key problems.

With respect to security, I feel my duty to inform you about these problems, detected yesterday and today.

**Comment by andrewdavidwong** [comment]
I remember seeing threads about this either on the Whonix Forum or on qubes-users, but now I can't find any of them. @adrelanos, do you remember them?

**Comment by adrelanos** [comment]
https://forums.whonix.org/t/size-of-file-dists-jessie-main-binary-amd64-packages-gz-is-not-what-the-server-reported

**Comment by Wikinaut** [comment]
Thank you for your swift answers. (I also already supported the project with a donation, every user who can should do so.)

**Comment by andrewdavidwong** [comment]
@adrelanos: Link appears to be broken. Temporary server issue?

**Comment by adrelanos** [comment]
Temporary looks like.

**Comment by adrelanos** [comment]
Whonix forum issue:
https://forums.whonix.org/t/whonix-forums-error-while-trying-to-load-something-went-wrong

-----

> W: Size of file  is not what the server reported

This will be fixed after release of Whonix 14 and after Whonix 13 was deprecated.

Please close.

**Comment by adrelanos** [comment]
> This will be fixed after release of Whonix 14 and after Whonix 13 was deprecated.

Correcting myself. This will be fixed right after upgrade to Whonix 14 because then newer apt repository location is in use.

(And can be fixed manually beforehand as per https://forums.whonix.org/t/whonix-forums-error-while-trying-to-load-something-went-wrong/3274)

**Comment by adrelanos** [comment]
Whonix 13 stable upgrade to fix this was uploaded just now.

Package whonix-repository 2.2.2-1 and whonix-legacy 2.9.3-1 were added to Whonix jessie-proposed-updates and testers repository.

**Comment by adrelanos** [comment]
This is now also in Whonix jessie (stable) repository.
