### ISSUE TITLE
[Installation/Improvement] If possible, make German keyboard "DE" layout default (not "DE nodead keys")

### ISSUE THREAD

**Issue by Wikinaut** [QubesOS/qubes-issues#2502]
My issue report refers to those users only, who selected Deutsch / German in the first steps of the installation. Then automatically, German keyboard layout "DE (nodead keys)" is selected. This is not the most-used keyboard layout, it should be "DE" instead.

#### Qubes OS version (e.g., `R3.2`):
R3.2

During the installation process, when selecting German language, only one of several German keyboard layouts is selected by default and visible in the keyboard selection window.

I suggest, if possible, to choose "Deutsch" (without any extras) which is the mostly-used keyboard type in Germany. Austrian and Swiss users may select their special keyboard versions, but "DE (nodead keys)" should not be the default any more, but "DE".

**Comment by andrewdavidwong** [comment]
This is probably an upstream issue that should be reported to Fedora. (Is that right, @marmarek?)

**Comment by marmarek** [comment]
On Thu, Dec 08, 2016 at 03:07:21AM -0800, Andrew David Wong wrote:
> This is probably an upstream issue that should be reported to Fedora. (Is that right, @marmarek?)

Yes.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by Wikinaut** [comment]
Thank you for your swift answers. (I also already supported the project with a donation, every user who can should do so.)

**Comment by andrewdavidwong** [comment]
Thank you, @Wikinaut. Please consider reporting this issue to Fedora.
