### ISSUE TITLE
Uninstalling app in TemplateVM does not remove Application Menu entry for AppVM

### ISSUE THREAD

**Issue by Wikinaut** [QubesOS/qubes-issues#2504]
#### Qubes OS version (e.g., `R3.2`):
R3.2

...because the application is not available anymore or has been relocated, or other reason.

#### Problem

I updated some of my TemplateVMs after a fresh installation (debian 8, fedora-23).

Now I started VM personal (debian-8) > "Firefox" (as listed in the VM Apps list starter) but nothing happens (no window, no error message).

When opening the VM Settings > Application window, you will see, that right window only contains "Files" (and "Firefox" has been removed from there).

Apparently the update process has removed "Firefox" (in the left side) but "Firefox ESR" has been added.

Now I manually added "Firefox ESR" and I can now select and start "Firefox ESR".

#### Suggested solution

Perhaps you can find a way, that - when a TemplateVM is updated - the Applications of the corresponding VMs which use that template are updated, or at least throw an error, when clicked, but when not present anymore (I hope that you understand what I mean.)

**Comment by Wikinaut** [comment]
Perhaps this "problem" cannot be solved. I don't know. Then close the issue pls.

**Comment by andrewdavidwong** [comment]
Are you saying that your Application Menu has an entry for a program that no longer exists? Or is it simply that the program disappears from your Application Menu, and you have to add its replacement?

**Comment by Wikinaut** [comment]
We have to distinguish between the (do you call it?) Quickstarter in the upper left corner and the VM add-or-remove-shortcut settings menu, the one with the two panes. (pls. correct me, when I mistakenly used incorrect names, I have to learn how you coined them.)

@andrewdavidwong wrote
> Are you saying that your Application Menu has an entry for a program that no longer exists? 

Yes. There was only the old (personal debian-7) "Firefox" in the QuickStarter menu, even when in the meantime the Template for personal domain was updated from fedora-23 to to debian-8. 

So I clicked onto "Firefox" in the Quickstarter Menu, and nothing happened. This should not happen, of course - the user should get a warning window "Application (name) could not be started. Please check currently available Applications for the underlying TemplateVM".

> Or is it simply that the program disappears from your Application Menu, 
No, the old name ("Firefox") remained in the Quickstarter Menu

> and you have to add its replacement?
But when I opened the shortcut settings menu with the two panes, in the right pane, there was then only "Files" (no "Firefox" !!), in the left pane was then "Firefox ESR" (which is correct for debian-8), and no "Firefox" any longer.

Then I added "Firefox ESR" as an application to the right pane, and from now on it is visible, and works, in the Quickstarter Menu for personal domain.


Perhaps the whole issue is a "nonbug", but requires a better synchronising, or better "lack-of-synchronising" warning or "synchronising required" warning to the user: when one of the Templates is changed, the(all) dependent application menus should be marked as "dirty", so that they can be refreshed, if this is possible at all.

**Comment by andrewdavidwong** [comment]
> We have to distinguish between the (do you call it?) Quickstarter in the upper left corner

Xfce4 calls this the "Applications Menu," but I know what you mean.

> Perhaps the whole issue is a "nonbug", but requires a better synchronising, or better "lack-of-synchronising" warning or "synchronising required" warning to the user: when one of the Templates is changed, the(all) dependent application menus should be marked as "dirty", so that they can be refreshed, if this is possible at all.

It sounds like maybe you need to issue `qvm-sync-appmenus <template-name>` in dom0. This is supposed to be triggered automatically after an update (and probably package removal).

**Comment by marmarek** [comment]
So, you had a VM based on debian-7 with "Firefox" entry, and after changing it to debian-8 "Firefox" entry didn't worked anymore (because it's "Firefox ESR" in debian-8). Is it the correct description @Wikinaut ?

If so, this is a duplicate of #1651

**Comment by Wikinaut** [comment]
Yep.

**Comment by Wikinaut** [comment]
(I promise from now on to look  c a r e f u l l y , whether a problem as already been filed. I promise.)
