### ISSUE TITLE
missing dependencies on qubesdb-vm

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#2509]
At minimum `qubes-core-agent` deb does not depend on `qubesdb-vm`. It should. Same reason as #2497.

Even if `qubesdb-vm` is installed in any Qubes VM, the explicit `debian/control` `Depends: qubesdb-vm` must still be added to avoid these issues during upgrading.

> Setting up qubes-core-agent (3.2.13-1+deb8u1) ...
> [...]
> Failed connect to local daemon

Other packages that might require a `Depends: qubesdb-vm`:

* qubes-core-agent
* qubes-linux-utils
* qubes-app-linux-tor
* qubes-gui-agent-linux
* any others?

And while at it, are there any other installed packages that yet better should be `Depends:`?

**Comment by marmarek** [comment]
Thanks @unman !
