### ISSUE TITLE
Reinstalling whonix-gw and whonix-ws fails

### ISSUE THREAD

**Issue by Wikinaut** [QubesOS/qubes-issues#2511]
#### Qubes OS version (e.g., `R3.2`):
R3.2

I already reported other issues related to *updating* whonix, and wanted now to reinstall the default whonix templates ( see https://www.qubes-os.org/doc/reinstall-template/ ):

```
$ sudo qubes-dom0-update --action=reinstall qubes-template-whonix-ws
$ sudo qubes-dom0-update --action=reinstall qubes-template-whonix-gw
```

but both fails with messages like

```
Last metadata expoiration check: (current date)
Installed package qubes-template-whonix-ws-3.0.6-291608050146.noarch not available.
Error: Nothing to do
```
respectively 
```
Last metadata expoiration check: (current date)
Installed package qubes-template-whonix-gw-3.0.6-291608050041.noarch not available.
Error: Nothing to do
```

**Comment by andrewdavidwong** [comment]
You have to enable the community templates repo, which is where those packages reside:

    $ sudo qubes-dom0-update --enablerepo=qubes-templates-community --action=reinstall qubes-template-whonix-ws
    $ sudo qubes-dom0-update --enablerepo=qubes-templates-community --action=reinstall qubes-template-whonix-gw

**Comment by andrewdavidwong** [comment]
By the way, that's documented here: https://www.qubes-os.org/doc/whonix/install/

**Comment by Wikinaut** [comment]
@andrewdavidwong perhaps this ( --enablerepo=qubes-templates-community ) should be added on https://www.qubes-os.org/doc/reinstall-template/ ?

**Comment by andrewdavidwong** [comment]
@Wikinaut: Added.
