### ISSUE TITLE
[Debian templates] - [qubes-gui-agent] - Qubes GUI broken because of Xorg ABI Interface update in package xserver-xorg-core 2:1.19.0-2 (debian testing)

### ISSUE THREAD

**Issue by yilmi** [QubesOS/qubes-issues#2514]
#### Affected TemplateVMs : Debian template using testing repositories (Kali templates)

---

### Expected behavior: 
Qubes GUI working as designed

### Actual behavior:
Xorg not starting because of incompatible ABI interface for modules `dummyavs` and `qubes`

### Steps to reproduce the behavior:
Upgrade debian 8 template to testing distribution, Xorg will complain about incompatible ABI versions.

There is an option to ignore ABI versions mismatch but even after ignoring mismatch, Xorg crashes shortly after loading the modules (add section `Server Flags` with option `IgnoreABI` in `/etc/X11/xorg-qubes.conf.template`)

### General notes:

Xorg log output

[     7.040] (II) Module ABI versions:
[     7.040]    X.Org ANSI C Emulation: 0.4
[     7.040]    X.Org Video Driver: 23.0
[     7.040]    X.Org XInput driver : 24.1
[     7.040]    X.Org Server Extension : 10.0
......
[     7.051] (WW) dummyqbs: module ABI major version (20) doesn't match the server's version (23)
[     7.052] 	ABI class: X.Org XInput driver, version 22.1
[     7.052] (WW) qubes: module ABI major version (22) doesn't match the server's version (24)
[     7.056] 	ABI class: X.Org ANSI C Emulation, version 0.4

---
### Workaround:
**This will break packages dependencies**
- Install package from a previous version from `/var/cache/apt/archives/xserver-xorg-core_2%3a1.18.4-2_amd64.deb` 
- Mask xserver-xorg-core package : `sudo apt-mark hold xserver-xorg-core`

**Comment by marmarek** [comment]
Rebuilt package just uploaded to testing repository 
(qubes-gui-agent_3.2.10-2+deb9u1).

But in general, qubes-gui-agent should depend on Xorg ABI interface version. And apparently, it require (among other things) the package with video driver being named `xserver-org-video-(something)`. So video driver needs to be split of the `qubes-gui-agent`. The same applies to input driver.

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-gui-agent_3.2.11-1+deb8u1` has been pushed to the `r3.2` testing repository for the Debian `jessie` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `jessie-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-gui-agent-linux/compare/5bbc7c8a73c5ab3bc969e0c0f111d85dbfd61b45...e210be85ee09ce165b422ce4eb60083d9ef15f4c

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-gui-agent_3.2.11-1+deb9u1` has been pushed to the `r3.2` testing repository for the Debian `stretch` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `stretch-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-gui-agent-linux/compare/5bbc7c8a73c5ab3bc969e0c0f111d85dbfd61b45...e210be85ee09ce165b422ce4eb60083d9ef15f4c

**Comment by yilmi** [comment]
Thanks, I didn't expected it to be fixed that fast ! Upgraded packages on stretch and now it works fine.

**Comment by tasket** [comment]
@yilmi @marmarek The result I got is that most function is restored, but systray (i.e. Network Manager) doesn't work. If I use nmcli to connect, a status popup will appear, but nothing related to the systray.

**Comment by marmarek** [comment]
@tasket I think it is unrelated to ABI change itself. Check if nm-applet is running, try to restart it etc. If nothing helps, open new issue.

**Comment by tasket** [comment]
I think is was a dom0 issue triggered by this issue. DomU/nm-applet restart didn't help, but dom0 restart did.

**Comment by agutl** [comment]
Does this bug affect v3.1, too? I have a debian stretch template on v3.1 which fails to start any apps since that recent update.
I don't get any response from qvm-run when I try to start an app, it just hangs there forever.

**Comment by marmarek** [comment]
On Tue, Dec 13, 2016 at 12:17:18AM -0800, agutl wrote:
> Does this bug affect v3.1, too? I have a debian stretch template on v3.1 which fails to start any apps since that recent update.
> I don't get any response from qvm-run when I try to start an app, it just hangs there forever.

Yes. Update for R3.1 will be tomorrow.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-gui-agent_3.1.10+deb8u1` has been pushed to the `r3.1` testing repository for the Debian `jessie` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `jessie-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-gui-agent-linux/compare/3501e58c93ca43172af9e6bddd8a6f6fdc10dec9...8ab665b59d9501394801cd721602caaf02b1dc9f

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-gui-agent_3.1.10+deb9u1` has been pushed to the `r3.1` testing repository for the Debian `stretch` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `stretch-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-gui-agent-linux/compare/3501e58c93ca43172af9e6bddd8a6f6fdc10dec9...8ab665b59d9501394801cd721602caaf02b1dc9f

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-gui-agent_3.1.10+deb7u1` has been pushed to the `r3.1` testing repository for the Debian `wheezy` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `wheezy-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-gui-agent-linux/compare/3501e58c93ca43172af9e6bddd8a6f6fdc10dec9...8ab665b59d9501394801cd721602caaf02b1dc9f
