### ISSUE TITLE
[OpenSuse Leap 42.2 Template] Trying to build an OpenSuse Leap TemplateVM

### ISSUE THREAD

**Issue by Wikinaut** [QubesOS/qubes-issues#2516]
I studied https://www.qubes-os.org/doc/templates/ubuntu/ . The link to the https://www.qubes-os.org/doc/qubes-builder/ however puzzled me then... it looks to be dedicated to build the Builder, but I don't see how to build a template VM from an iso file.

Perhaps someone of you can give _detailed_ instructions how to build (install) the new OpenSus Leap 42.2 (see https://software.opensuse.org/422/en ) for use as a template VM in Qubes.

**Comment by andrewdavidwong** [comment]
This is not appropriate for `qubes-issues`. Please send this to the `qubes-users` [mailing list](https://www.qubes-os.org/mailing-lists/) instead.
