### ISSUE TITLE
Provide a feedback in pull requests if code signature is missing

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#2517]
Ease enforcing [a policy](https://www.qubes-os.org/doc/code-signing/) of requiring all the contributions to be signed.
This should be automatically mark not signed pull request as failed (but do not close them automatically, as the author may push missing tag later, or even force-push signed commits).

**Comment by jpouellet** [comment]
What is the story with this policy: https://www.qubes-os.org/doc/license/#note-on-rights-to-double-licensing-of-the-qubes-code ? (requiring signed-off-by, or in some way formally delegating a superset of GPL rights).

It is clearly not enforced in practice, and AFAICT it does not appear to ever have been, but it may become more relevant in light of Qubes' [commercialization plans](https://www.qubes-os.org/news/2016/11/30/qubes-commercialization/). Perhaps some sort of CLA should be formalized?

Personally I don't care what ITL (or whoever) does with my contributions, I usually release all my things under a BSD license anyway. I'm certainly deriving more benefit from your work than you are from mine regardless :)

**Comment by marmarek** [comment]
> It is clearly not enforced in practice, and AFAICT it does not appear to ever have been, but it may become more relevant in light of Qubes' [commercialization plans](https://www.qubes-os.org/news/2016/11/30/qubes-commercialization/). Perhaps some sort of CLA should be formalized?

Yeah, we've never enforced it. And in fact we'll drop it.
We're planning to change license of qubes-core-admin for Qubes to LGPL
instead (so extensions importing qubes python modules will not be forced
to be GPL).

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by marmarek** [comment]
@jpouellet could you upload your key to a keyserver? The script currently reject your signatures because of this. https://github.com/QubesOS/qubes-manager/pull/17

**Comment by jpouellet** [comment]
> @jpouellet could you upload your key to a keyserver?
[Done](https://pgp.mit.edu/pks/lookup?op=get&search=0xE7E455013D042EA1), although I'd been meaning to replace it with a longer-term higher-security key first.

> The script currently reject your signatures because of this.
To which script are you referring? qubes-builder/scripts/verify-git-tag? I do not see anywhere it imports from keyservers automatically...

FWIW, my key was previously here: https://github.com/QubesOS/qubes-installer-qubes-os/pull/8#commitcomment-19406400 (one of my first PRs to Qubes) and I intended have already replaced it by now.

**Comment by marmarek** [comment]
> To which script are you referring? qubes-builder/scripts/verify-git-tag? I do not see anywhere it imports from keyservers automatically...

No, the one in commit closing this issue.
