### ISSUE TITLE
How to install mplayer or vlc?

### ISSUE THREAD

**Issue by starius** [QubesOS/qubes-issues#2521]
#### Qubes OS version (e.g., `R3.2`):

R3.2

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):
fedora-23

---

### Expected behavior:

```
$ sudo yum install mplayer
```
Watch videos.

### Actual behavior:

```
$ sudo yum install mplayer
Redirecting to '/usr/bin/dnf install mplayer' (see 'man yum2dnf')

Last metadata expiration check: 0:56:23 ago on Thu Dec 15 21:57:33 2016.
No package mplayer available.
Error: Unable to find a match.
```

The same with vlc.

Totem is preinstalled but I do not like it.

**Comment by andrewdavidwong** [comment]
Enable the RPMFusion repo: https://www.qubes-os.org/doc/software-update-vm/#rpmfusion-for-a-fedora-templatevm

In the future, please direct such queries to the qubes-users mailing list.
