### ISSUE TITLE
PCI passthrough of RX480 into Windows HVM failing

### ISSUE THREAD

**Issue by Aloxis** [QubesOS/qubes-issues#2522]
#### Qubes OS version (e.g., `R3.2`):
R3.2

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):
n/a

---

### Expected behavior:
Card should pass through to HVM.

### Actual behavior:
It fails saying that it failed to start the domain.

### Steps to reproduce the behavior:
1) Create HVM domain
2) Assign RX480 to domain
3) Start domain
4) Wait while GUI freezes for a minute or so
5) VM startup fails

### General notes:
I am making a sweet virtualized gaming rig and have bought all the right hardware / bios needed. At this point it's hanging up at the last step, soooo close!!! :( I'm also using Qubes for CUDA related computing, which is why it makes my life easier to merge the linux CUDA stuff with the Windows gaming stuff all in one unified UI. I also really like the security and compartmentalization and would hate to lose that by going vanilla Xen.

I can supply any needed logs, but at this point I have no idea how to even begin to fix this.

---

**Comment by andrewdavidwong** [comment]
GPU passthrough isn't officially supported, though there are some reports of users on the mailing lists who have managed to make it work.

In addition:

This question is too localized for `qubes-issues`. Please consider posting this to the `qubes-users` mailing list instead. (You can read more about our mailing lists [here](https://www.qubes-os.org/mailing-lists/).)

`qubes-users` is intended for these sorts of questions and receives much more traffic, which means that your question is more likely to receive a response there.
