### ISSUE TITLE
LAN network connection is not re-established when awaking from suspend

### ISSUE THREAD

**Issue by Wikinaut** [QubesOS/qubes-issues#2525]
#### Qubes OS version (e.g., `R3.2`):
* 3.2

#### Hardware
*  INTEL NUC i5 D54250WYKH

#### Problem/bug
When awaking from hibernation, the LAN network connection is not established, even when the connection checkbox (in the settings in the top right-hand corner) is still activated.

I have then to deactivate and reactivate the network checkbox to re-establish the network connection.

#### Suggestion
Add code to check and reconnect when awaking from hibernation.

**Comment by andrewdavidwong** [comment]
I assume you mean "suspend," since Xen doesn't support hibernation.

Appears to be related to #1663.

**Comment by Wikinaut** [comment]
@andrewdavidwong 

In my German Qubes system I (currently) see
* Bildschirm sperren (lock screen)
* Bereitschaft (standby)
* **Ruhezustand**
* shutdown
* restart

I indeed mean `"Ruhezustand"`. German wikipedia translates with `"Hibernation"`, but also `"suspend to...."`

So you are right.

**Comment by Wikinaut** [comment]
Please find a solution. Everytime when my computer is awakening from suspense, I have to close/open the LAN connection in order to get it working. This could be done automagically... please

**Comment by jpouellet** [comment]
Try https://www.qubes-os.org/doc/wireless-troubleshooting/#automatically-reloading-drivers-on-suspendresume

**Comment by Wikinaut** [comment]
note to myself: Try https://www.qubes-os.org/doc/wireless-troubleshooting/#automatically-reloading-drivers-on-suspendresume

**Comment by Wikinaut** [comment]
Your tip was helpful, apparently. However, I think, the setting should be automatically activated (sorry, I cannot help in this core issue, but will help testing new versions, if this is wanted.)

**Comment by Wikinaut** [comment]
(reopened, because the issue was tagged for being solved/handled in the next release.)

**Comment by jpouellet** [comment]
I would just close. This is not qubes' bug, this is a problem with the combination of {hardware, network card driver, kernel version} you use, which is upstream's issue.

Also, I do not think reloading drivers automatically is something we should do by default, because whether or not we should (and which drivers we should - which is not easy to automatically determine) depends on the hw model and version of things, and such lists become quickly unmaintained.

**Comment by Wikinaut** [comment]
@jpouellet I want the decision to close - or to let it open - up to the Qubes Core maintainers.
Thanks for help, I understand the issue, but perhaps more users may have the same problem and you cannot expect everyone to go the hard way ...

**Comment by andrewdavidwong** [comment]
Being either an upstream bug or a hardware-configuration-specific problem would be sufficient by itself to merit closing.
