### ISSUE TITLE
Allow qubes-dom0-update to upgrade, downgrade template packages

### ISSUE THREAD

**Issue by tasket** [QubesOS/qubes-issues#2527]
#### Qubes OS version (e.g., `R3.2`):
R3.2

Feature request to expand on the 'reinstall' capability added to qubes-dom0-update. The dnf actions 'upgrade', 'upgrade-to', and 'downgrade' can also be supported as they are functionally similar to 'reinstall'. This can be useful for changing a template in-place that has a vulnerability in its package manager ( e.g. issue #2520 affecting Debian apt ).

#### Notes

So far I have replaced "reinstall" keyword in qubes-dom0-update with "upgrade" and it is working on the Whonix templates. Need to change code to accommodate multiple keywords:

reinstall
upgrade
upgrade-to
downgrade

Will submit PR soon...

---

#### Related issues:
issue #2061

**Comment by tasket** [comment]
PR submitted

**Comment by jpouellet** [comment]
Close since https://github.com/QubesOS/qubes-core-admin-linux/pull/20 is merged?

**Comment by tasket** [comment]
OK
