### ISSUE TITLE
Dvm template prevents template VM from being removed

### ISSUE THREAD

**Issue by tasket** [QubesOS/qubes-issues#2529]
#### Qubes OS version (e.g., `R3.2`):
R3.2

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):
(any)

---

### Expected behavior:
Command to remove template with no serviceVM or appVM dependants should succeed.

### Actual behavior:
$ qvm-remove my-template
The following AppVMs use 'my-template' as a template:
my-template-dvm

### General notes:
The default template was recently changed from my-template to something else.

Can work around by removing the dvm template, but this should happen automatically.

---

**Comment by marmarek** [comment]
> Can work around by removing the dvm template, but this should happen automatically.

I don't think so. You may have customized it somehow and removing it will also destroy your modifications there. It is intended to be done manually - like with other VMs before you remove the template.
In the current implementation, switching *-dvm to other template doesn't make sense, but in Qubes 4.0 it will be also perfectly fine option.

**Comment by tasket** [comment]
This use case doesn't seem to be well-examined. There is no documentation I've seen that describes deleting a dvm template in order to remove a normal, non-rpm template. Also, switching the default template should cause the existing dvm template to be deprecated or deleted so a new dvm template can be created.

Granted, a user can do some detective work to discover where the dvm template is hiding and then delete it manually. But there is no reason I can see why this can't be automated. I think what this comes down to is that a change in the default template should be handled as an event.

**Comment by marmarek** [comment]
> Also, switching the default template should cause the existing dvm template to be deprecated or deleted so a new dvm template can be created.

No, you don't need to use default template for Disposable VM.
