### ISSUE TITLE
Colored application icons missing on Fedora minimal template

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#2536]
Qubes 3.2:

Colored application icons (#967) work great in the standard (full) templates, but only generic colored lock icons are available if the application is in an AppVM that's based on `fedora-*-minimal`. Missing dependencies?

**Comment by andrewdavidwong** [comment]
Verified that these required dependencies are already installed:

```
Requires:	xorg-x11-drv-dummy
Requires:	xorg-x11-xinit
Requires:	qubes-libvchan-%{backend_vmm}
Requires:	python-xpyb
```

Attempting to execute this command manually in a minimal VM just hangs:

```
/usr/bin/qrexec-client-vm dom0 qubes.WindowIconUpdater /usr/lib/qubes/icon-sender
```

**Comment by marmarek** [comment]
> Attempting to execute this command manually in a minimal VM just hangs:
> 
> ```
> /usr/bin/qrexec-client-vm dom0 qubes.WindowIconUpdater /usr/lib/qubes/icon-sender
> ```

I think it shouldn't output anything when running. The important part is
it's not crashing.

It works for me... Tried with `zenity --question`, xterm doesn't look to
set any icon.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by andrewdavidwong** [comment]
Ah, yes, I have the colored icons on the taskbar, but they're missing in the Applications Menu and in Launchers on the Panel (Xfce4).

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
