### ISSUE TITLE
TOR connection fails when using a VPN

### ISSUE THREAD

**Issue by john6611** [QubesOS/qubes-issues#2541]
#### Qubes OS version (e.g., `R3.2`):
3.2

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):
fedora-23 / debian08

---

Connection = dom0 > sys-net > sys-firewall > VPN (proxyvm) > sys-whonix > anon-whonix

TOR through the TOR browser works fine for aslong as I don't turn on the VPN
As soon as I turn on the VPN I can't connect to TOR anymore (tried restarting TOR & VM's)

Tried both on debian-8 and fedora-23 and proxyVM with both mullvad and airvpn
The VPN connection works fine (testing with firefox in the VPN proxyVM)

Is this is an actual bug or am I overlooking something?

**Comment by andrewdavidwong** [comment]
> Connection = dom0 > sys-net > sys-firewall > VPN (proxyvm) > sys-whonix > anon-whonix

I think you mean this, instead:

    anon-whonix > sys-whonix > VPN (ProxyVM) > sys-firewall > sys-net > local network / internet

For simplicity, I'm going to refer to "VPN (ProxyVM)" as `sys-vpn`.

> TOR through the TOR browser works fine for aslong as I don't turn on the VPN
As soon as I turn on the VPN I can't connect to TOR anymore (tried restarting TOR & VM's)

I presume you mean that if you set the NetVM of `sys-whonix` to `sys-firewall`, then it works.

> Tried both on debian-8 and fedora-23 and proxyVM with both mullvad and airvpn
The VPN connection works fine (testing with firefox in the VPN proxyVM)

That's not the the correct way to test `sys-vpn`. Instead, use a non-Whonix (vanilla Fedora or Debian) AppVM, and set `sys-vpn` as the AppVM's NetVM, then test the connection.

> Is this is an actual bug or am I overlooking something?

Make sure you've thoroughly read the documentation:

https://www.whonix.org/wiki/Tunnels/Connecting_to_a_VPN_before_Tor#Separate_VPN-Gateway

**Comment by andrewdavidwong** [comment]
@john6611: Did my previous message help? Does the issue persist?

**Comment by andrewdavidwong** [comment]
Closing this for now due to the lack of response. If you revisit the matter in the future, or if anyone would like the issue to remain open, please leave a comment, and we'll be happy to reopen this. Thank you.
