### ISSUE TITLE
Asus X99-E motherboard problems

### ISSUE THREAD

**Issue by porander** [QubesOS/qubes-issues#2548]
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):

During installation problems arose on my motherboard Asus X99-E
![img_20161230_130925](https://cloud.githubusercontent.com/assets/24841136/21564534/6831c3fe-ce97-11e6-9c8f-0d10305171d2.jpg)
at this point hangs, and nothing further occurs

but when I try to run without UEFI
I get the installation in text mode idk why
![img_20161230_132254](https://cloud.githubusercontent.com/assets/24841136/21564595/e454a604-ce97-11e6-8a21-62d4f3ce3da0.jpg)

and I can not install in text mode
![img_20161230_132239](https://cloud.githubusercontent.com/assets/24841136/21564622/222a5046-ce98-11e6-879c-937b141c149f.jpg)

please help mb I'm doing wrong
![img_20161230_131311](https://cloud.githubusercontent.com/assets/24841136/21564649/6b1c9188-ce98-11e6-8ba7-9f919c89c98a.jpg)

**Comment by andrewdavidwong** [comment]
This is too localized for `qubes-issues`. Please consider posting this to the `qubes-users` mailing list instead. (You can read more about our mailing lists [here](https://www.qubes-os.org/mailing-lists/).)

`qubes-users` is intended for these sorts of questions and receives much more traffic, which means that your question is more likely to receive a response there.
