### ISSUE TITLE
[PATCH] Restore functionality of disable-default-route and  disable-dns-server.

### ISSUE THREAD

**Issue by gr-g** [QubesOS/qubes-issues#2551]
[0001-Restore-functionality-of-disable-default-route-and-d.txt](https://github.com/QubesOS/qubes-issues/files/683427/0001-Restore-functionality-of-disable-default-route-and-d.txt)
#### Qubes OS version (e.g., `R3.2`): R3.2

Recently (after the R3.2 release) I noticed that the service "disable-dns-server" documented [here](https://www.qubes-os.org/doc/dom0-tools/qvm-service) was not working anymore. Even with the service enabled in a VM configuration, iptables rules for forwarding DNS queries were still created.

I tracked down the issue to this commit in qubes-core-agent-linux: [link](https://github.com/QubesOS/qubes-core-agent-linux/commit/59aec8e5eb447938dc0981100cf9f9accc09475e#diff-3ccff7f6797b18d40242a99f879c67d8).
Apparently the commit replaced some instances of this test
  `if [ "x$disablegw" != "x1" ]"`
with this:
  `if ! qsvc disable-default-route`
(and similarly for dns) but left some references to $disablegw and $disabledns in other places.

The attached patch fixes the problem for me. After applying it, the behaviour of disable-dns-server and disable-default-route is as expected.

**Comment by andrewdavidwong** [comment]
Thanks, @gr-g! If you prefer, you can submit this as a pull request against `qubes-core-agent-linux` instead.

**Comment by gr-g** [comment]
I am not so familiar with the github work flow, so for this very simple patch I went with this route. For the future I will look better into doing proper pull requests.

Thanks for your work!

**Comment by andrewdavidwong** [comment]
@marmarek: Please feel free to merge this (or ask for followup interaction) as you see fit.

**Comment by marmarek** [comment]
Merged and already included in qubes-core-agent 3.2.16.
