### ISSUE TITLE
Cross-domain clicks into LibreOffice windows misregister

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#2552]
#### Qubes OS version (e.g., `R3.2`):

`R3.2`

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):

`fedora-24`

---

### Expected behavior:

Single-clicking in a LibreOffice window should, as with any window, consistently register as a single-click.

### Actual behavior:

When a window from a different domain has focus, single-clicking into a LibreOffice window consistently misregisters as a "click-and-hold-while-dragging-downward," causing unintended manipulation of contents inside the window.

### Steps to reproduce the behavior:

Suppose you have two domains, A and B. In domain A, you have a LibreOffice window (e.g., Calc spreadsheet or Writer text editor). In domain B, you have any window, e.g., a file manager.

#### Example 1

1. Single-click anywhere inside B's file manager window, giving it focus.
2. Single-click on one (assuming multiple) sheet tab in A's LibreOffice Calc spreadsheet.

**Result:** Moving your cursor (without holding down any mouse buttons) causes the whole tab to be moved (and potentially even *re*moved), as if you were holding down the left mouse button while dragging.

#### Example 2

1. Single-click anywhere inside B's file manager window, giving it focus.
2. Single-click on a cell in A's LibreOffice Calc spreadsheet.

**Result:** The cell you clicked on is selected, but multiple cells below it are also selected.

#### Example 3

1. Single-click anywhere inside B's file manager window, giving it focus.
2. Single-click on a location in the text of a Writer text document.

**Result:** Instead of placing your cursor at the position you clicked, multiple lines of text are selected, beginning at the point on which you clicked.

### General notes:

This does not occur with any other windows or programs, as far as I can tell -- only LibreOffice windows. It also does not occur when clicking from a non-LibreOffice window into a LibreOffice window within the same domain -- only cross-domain.

This behavior is mainly an extreme nuisance for anyone who works with LibreOffice, but it also has the potential for data loss if users are not extremely careful to undo any mistakes every time they cross-domain click (which can happen once every few seconds in a normal workflow).

**Comment by marmarek** [comment]
*Very* strange LibreOffice behavior. I can reproduce it as you've described. But no idea why it happens. I've used very scientific tool called `xeyes` to confirm the mouse cursor itself isn't moved, so probably some internal LibreOffice action cause this effect.

BTW It doesn't apply configuration when focus follow mouse (without requiring a click). Probably also switching with alt-tab can mitigate this issue.

**Comment by unman** [comment]
I don't seem to be able to reproduce this using Debian or Ubuntu templates, in writer or calc, so it looks like a Fedora specific issue. I find it surprising that no one else has reported this because it sounds like a killer, as you say. Has it appeared after an update?

**Comment by andrewdavidwong** [comment]
> Probably also switching with alt-tab can mitigate this issue.

Indeed, `alt`+`tab` mitigates.

> Has it appeared after an update?

IIRC, it's been this way ever since I upgraded from 3.1 to 3.2 (clean reinstall).

**Comment by dmoerner** [comment]
I cannot reproduce this in a Fedora 25 template (libreoffice-5.2.3.3-11.fc25). If I have time I'll try a more fine-grained search for the issue.

**Comment by unman** [comment]
I can reproduce this using a Fedora 24 template. LibreOffice v 5.1.6.2.0.
The excess selection I see in Calc is between 2 and 3 cells down.

In Xenial, I have Libre v5.1.2.2, and can't reproduce.

**Comment by jpouellet** [comment]
Confirming that I also can reproduce in fedora-24 based VM with `libreoffice-calc-5.1.6.2-7.fc24.x86_64`.

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
