### ISSUE TITLE
R3.2 not installing on Lenovo L450

### ISSUE THREAD

**Issue by neeraj9** [QubesOS/qubes-issues#2554]
#### Qubes OS version: R3.2

Lenovo L450 Intel® Core™ i5-5200U CPU @ 2.20GHz ×4

---

### Expected behavior:

Install the QubesOS on the hardware.

### Actual behavior:

The system restarts in regular install mode without any error while trying to install. Whereas in Troubleshoot mode with basic display it displays some logs and quickly reboots without time to notice what went wrong. Probably something to do with Xen incompatibility boot.

### Steps to reproduce the behavior:

Try installing the latest QubesOS 3.2 stable on Lenovo L450.

### General notes:

I am eagerly looking forward to try out QubesOS on the hardware but there is no way to capture the error since it goes past very fast.

---

**Comment by andrewdavidwong** [comment]
This is too localized for `qubes-issues`. Please consider posting this to the `qubes-users` mailing list instead. (You can read more about our mailing lists [here](https://www.qubes-os.org/mailing-lists/).)

`qubes-users` is intended for these sorts of questions and receives much more traffic, which means that your question is more likely to receive a response there.
