### ISSUE TITLE
Updating a standalone VM should not shut it down

### ISSUE THREAD

**Issue by lorenzog** [QubesOS/qubes-issues#2555]
#### Qubes OS version (e.g., `R3.2`): 

3.2

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable): 

N/A

---

### Expected behavior:

If a standalone VM was running, updating it from Qubes VM Manager should not offer to shut it down

### Actual behavior:

At the end of a standalone VM update from Qubes VM Manager, the prompt on the terminal window offers to "Press Enter to shut down the template, or Ctrl-C to just close this window"

### Steps to reproduce the behavior:

1. Start a standalone VM and do some work
2. [when an update is available] press the update button on the VM Manager (blue downward arrow)
3. At the end of the update, press Enter
4. The standalone VM shuts down immediately. All applications are irrevocably closed

### General notes:

While the request to shut down a template is appreciated and makes sense, my understanding is that standalone VMs "ping" for updates only when in use. In this case, shutting them down makes little sense (I was Doing Stuff!). 

Perhaps a way forward could be to remove the prompt to shutdown altogether for standalone VMs.

---

**Comment by andrewdavidwong** [comment]
> While the request to shut down a template is appreciated and makes sense, my understanding is that standalone VMs "ping" for updates only when in use.

More specifically, when the StandaloneVM is running (not necessarily in use).

> Perhaps a way forward could be to remove the prompt to shutdown altogether for standalone VMs.

The feature was originally intended for TemplateVMs. It's up to @marmarek to decide whether its application to StandaloneVM is over-broad or intended.

For reference, this is feature #2431.

**Comment by marmarek** [comment]
I'd say it depends - if you started the StandaloneVM just to update it, automatic shutdown would be desired. Maybe the criteria should not be a VM type, but if the VM was just started?

Anyway, for now, you can simply press Ctrl-C, as the message told you.

**Comment by andrewdavidwong** [comment]
> Maybe the criteria should not be a VM type, but if the VM was just started?

I think there would still be users (like @lorenzog?) who intend to:

1. Start the StandaloneVM.
2. Update the StandaloneVM.
3. Continue working in the StandaloneVM (without rebooting it).

**Comment by lorenzog** [comment]
@marmarek I think the VM type would make more sense. As @andrewdavidwong was saying, a StandaloneVM checks for updates only when it's on; so a user would never know it needs to update one unless it was already on, in which case turning it off 'by default' seems counter-productive.

It's a minor issue in the end. If you could kindly point me at the utility that does it I can try to give it a go.

**Comment by marmarek** [comment]
> It's a minor issue in the end. If you could kindly point me at the utility that does it I can try to give it a go.

The script for `/etc/qubes-rpc/qubes.InstallUpdatesGUI` is [here](https://github.com/QubesOS/qubes-core-agent-linux/blob/master/qubes-rpc/qubes.InstallUpdatesGUI).
You can check you're in standalone VM by combining existence of `/var/run/qubes/this-is-appvm` (template vm will have `/var/run/qubes/this-is-templatevm` instead).

**Comment by lorenzog** [comment]
@marmarek It's a one liner, see if you like it :)

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
