### ISSUE TITLE
Audio equalizer in dom0

### ISSUE THREAD

**Issue by porander** [QubesOS/qubes-issues#2556]
### can not be set

Wonders why there is no audio equalizer in assembly?
I tried various options set but it never work.
What do you think about it?
I think everyone loves music :)

**Comment by andrewdavidwong** [comment]
This is not appropriate for `qubes-issues`. Please send this to the `qubes-users` [mailing list](https://www.qubes-os.org/mailing-lists/) instead.

-----

Comment: You can install whatever kind of audio equalizing software you like in dom0 (but make sure you're aware of the security implications of doing so).
