### ISSUE TITLE
provide Linux kernel input device so kloak (anti keystroke deanonymization tool) can be used in Qubes-Whonix

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#2558]
[`kloak`](https://github.com/vmonaco/kloak) (anti keystroke deanonymization tool) currently cannot be used inside Qubes.

[quote](https://phabricator.whonix.org/T583#11254) @marmarek:

> Hmm, I was under impression it expect X server input device, not not Linux kernel input device. Qubes GUI agent do not expose the later. It shouldn't be hard to change that, but still it is some code change. Namely, rewrite [this function](https://github.com/QubesOS/qubes-gui-agent-linux/blob/master/gui-agent/vmside.c#L1323-L1413) (feed `/dev/uinput` instead of X input device).

**Comment by adrelanos** [comment]
The kloak project was recently active with lots of code improvements.

**Comment by DemiMarie** [comment]
@andrewdavidwong agreed, closing.
