### ISSUE TITLE
Fedora 25 Gnome HVM mouse doesn't work, HVM window moves by itself around screen

### ISSUE THREAD

**Issue by dmoerner** [QubesOS/qubes-issues#2559]
This is definitely some sort of bug in the version of GNOME shipped in F25, but it might also have something to do with Xen or Qubes.

#### Qubes OS version (e.g., `R3.2`):

R3.2

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):

HVM started with Fedora-Workstation-Live-x86_64-25-1.3.iso

### Expected behavior:

I start an HVM with the Fedora-Workstation-Live-x86_64-25-1.3.iso. The mouse should seemlessly move around inside the window of the HVM as it's running. This is what happens on Fedora-KDE-Live, on Fedora-Workstation-Live-x86_64-24-1.2.iso, and on any other LiveCD with X. (Other than Korora 25 Gnome, which for obvious reasons seems to be afflicted by the same bug.)

### Actual behavior:

It's a bit hard to explain, but the HVM window jumps around as I move my cursor. It doesn't follow my cursor, as if I were using alt+drag. Instead it jumps diagonally as I move my cursor, and then if I move my cursor back the HVM window jumps back. This makes it impossible to shutdown the HVM from within, since I can't reliably click inside the HVM. I have to kill the HVM from Qubes VM Manager.

### General notes:

This seems like some sort of a bug in the version of GNOME shipped with Fedora 25. Can anyone else reproduce it? (I don't have a non-Qubes Xen to test on right now.)

It's a little bit weird that a bug here can cause the window to move around the screen and interfere with my ability to click on other appVMs. Why should anything but my actions in dom0 move a window around like this? I'm being a bit paranoid here, but I can imagine a kind of Denial of Service attack that tries to take advantage of this behavior. If you could make an entire window progressively move very fast over the entire screen, it would be hard if not impossible to click on or use any other appVMs.

**Comment by marmarek** [comment]
The bug is in Qubes gui-agent running in stubdomain (the thing transfering emulated VGA into dom0 for displaying). It confuses mouse position with window position and when sending new screen size to dom0 (like on resolution change requested by the OS inside) it sends mouse position instead of window position...

Independently interesting is why it sees "resolution change" even though it's still the same (1024x768). But that's another story.

**Comment by dmoerner** [comment]
Great, thanks for the quick diagnosis and patch.

**Comment by dmoerner** [comment]
Thanks, the updated packages in testing fixed the problem for me! (And thanks for auto-building for fc25 as well.)

**Comment by dmoerner** [comment]
Someone in IRC ("grillon") was able to reproduce this with sway on an Arch Linux hvm, so it seems part of the underlying trigger for this bug was wayland.
