### ISSUE TITLE
Arch Linux Template Fails to Compile (app-linux-split-gpg)

### ISSUE THREAD

**Issue by rdhammond** [QubesOS/qubes-issues#2560]
#### Qubes OS version (e.g., `R3.2`):
R3.2

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):
fedora23 building Arch Linux template from qubes-builder

---

### Expected behavior:

Running `make app-linux-split-gpg` succeeds.

### Actual behavior:

Build fails with:
    pandoc -s -f rst -t man qubes-gpg-import-key.rst > qubes-gpg-import-key.1
    /bin/sh: pandoc: command not found
    make[1]: *** [Makefile:16: qubes-gpg-import-key.1] Error 127
    rm qubes-gpg-import-key.1
    make[1]: Leaving directory '/home/user/qubes-src/app-linux-split-gpg/doc'
    make: *** [Makefile:92: install-vm] Error 2
    ==> ERROR: A failure occurred in package().
        Aborting...
    /home/user/qubes-builder/qubes-src/builder-archlinux/Makefile.archlinux:120: recipe for target 'dist-package' failed
    make[2]: *** [dist-package] Error 2
    Makefile.generic:139: recipe for target 'packages' failed
    make[1]: *** [packages] Error 1
    Makefile:209: recipe for target 'app-linux-split-gpg-vm' failed
    make: *** [app-linux-split-gpg-vm] Error 1

### Steps to reproduce the behavior:

Follow the instructions from [here](https://www.qubes-os.org/doc/templates/archlinux/), apply fix for QubesOS\qutes-core-agent-linux#24, then run `make qubes-vm`.

### General notes:

Chrooting manually into the Arch environment and running `pacman -S pandoc` seemed to fix everything up. Not sure if that's something from an earlier step or just a missed script line somewhere.

**Comment by marmarek** [comment]
Have you checked most recent version? This one is also already fixed, here: https://github.com/QubesOS/qubes-app-linux-split-gpg/pull/7

**Comment by rdhammond** [comment]
42 minutes ago, huh? Late to the party as always.

Oh well, at least it's fixed! THanks.
