### ISSUE TITLE
After creation of a new DispVM default template and a restart, the old DispVM template is still listed in VM Manager

### ISSUE THREAD

**Issue by Wikinaut** [QubesOS/qubes-issues#2564]
After following the instructions on https://www.qubes-os.org/doc/dispvm-customization/ and creation of a new default "debian-8-dvm":

Even after a reboot, I see still both the new "debian-8-dvm" and also the old "fedora-23-dvm" listed as "Internal" in the Qubes VM Manager.

Either the non-deletion of the old "fedora-23-dvm" entry is a bug, or it should be mentioned on https://www.qubes-os.org/doc/dispvm-customization/ that the old DispVM is to be deleted manually from the list.

`ll /var/lib/qubes/dvmdata/` only lists the new debian-8-dvm files, as expected.

**Comment by andrewdavidwong** [comment]
What version of Qubes are you running?

Also, does this entry persist beyond a few minutes?

**Comment by Wikinaut** [comment]
@andrewdavidwong yes, it the old "fedora-23-dvm" entry is still present after one reboot.

Running current release of Quebes i.e. 3.2 (R3.2) (I thought it was clear, it wasn't, sorry).

**Comment by marmarek** [comment]
This is intended behavior, thanks for this, you can switch between those using `qvm-create-default-dvm` tool, without need to redo any your customization. In Qubes 4.0, based on this it will be possible to assign different purposes for different DispVMs, so you'll be able to use them simultaneously (#866).

**Comment by Wikinaut** [comment]
@marmarek if it is intended behaviour, then please let me know why the (explained on your page)
`ll /var/lib/qubes/dvmdata/` command only lists the new debian-8-dvm files or links, but not the old fedora-23-dvm files (as in the VM Manager list).

It puzzles me, when a GUI list differs from the command line view list.

**Comment by unman** [comment]
In 3.2 there can only be one dvm active at any one time. The relevant files are linked in /var/lib/qubes/dvmdata/
If you were to change the default template back to fedora-23-dvm you would see the links change to that dvm.

The GUI list exactly matches the command line view - the corresponding command line would be qvm-ls which will show both dvm.

**Comment by Wikinaut** [comment]
(closing this issue now)
