### ISSUE TITLE
Qubes Debian apt sources qubes-r3.list should drop [arch=amd64]?

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#2580]
* https://github.com/QubesOS/qubes-core-agent-linux/blob/master/misc/qubes-r3.list.in
* https://github.com/QubesOS/qubes-core-agent-linux/commits/master/misc/qubes-r3.list.in

I haven't found an explanation in the commit where `[arch=amd64]` was added why it was added. Haven't seen this anywhere else before. Probably not needed? And if it is needed, it is probably to work around some other bug?

**Comment by unman** [comment]
It's standard usage now there's full multiarch support,. Yes, it probably isn't needed in Debian, although it's useful in Ubuntu. I'd leave it: it isn't doing any harm

**Comment by unman** [comment]
It occurs to me that if you do set up a multiarch template, then this would be required for the Qubes repository as it only provides one architecture. So leave it as is.
