### ISSUE TITLE
Add support for starting gnome-terminal in a DispVM

### ISSUE THREAD

**Issue by maxsu** [QubesOS/qubes-issues#2581]
I've come across a curious little issue.

#### Qubes OS version (e.g., `R3.2`): 

R3.2

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable): 

DispVM

---

### Expected behavior: 

The following command should start a DispVM and produce a working gnome-terminal, and allow the creation of a launcher for gnome terminal, similar to `DispVM: xterm` :

> dom0 $ sh -c 'echo gnome-terminal | /usr/lib/qubes/qfile-daemon-dvm qubes.VMShell dom0 DEFAULT red' 

### Actual behavior: 

The DispVM starts up and gnome-terminal may appear momentarily. If the terminal appears, it immediately terminates. After a moment the DispVM shuts down.

Dom0 terminal shows:
> [dom0 ~]$ sh -c 'echo gnome-terminal | /usr/lib/qubes/qfile-daemon-dvm qubes.VMShell dom0 DEFAULT red'
> time=1484435935.8, qfile-daemon-dvm init
> time=1484435935.81, creating DispVM
> time=1484435935.85, collection loaded
> time=1484435935.85, VM created
> time=1484435935.86, VM starting
> time=1484435935.87, creating config file
> time=1484435935.97, calling restore
> time=1484435937.95, done
> time=1484435937.98, done qubesdb
> time=1484435937.98, resumed
> time=1484435938.32, qrexec done
> time=1484435940.26, guid done
> time=1484435940.26, VM started
> time=1484435940.27, reloading firewall
> time=1484435940.28, starting VM process
> [dom0 ~]$

The command finishes approximately 3 seconds after the last entry.

### Steps to reproduce the behavior:

Execute the above command either in a dom0 shell or via a customized version of the 'xfce DispVM: xterm' launcher.

### General notes:

I've used the `qfile-daemon-dvm` command to successfully launch other non-standard apps including the `urxvt` terminal and the `nautilus`, `gedit`, and `gnome-calculator` apps. I can successfully spawn gnome-terminal by using DispVM: xterm, and by using Qubes VM Manager's 'Run command in VM' dialog for an existing dispVM. Another person has been able to replicate the issue in their Qubes R3.2 environment.

---

**Comment by unman** [comment]
This is because gnome-terminal is a stub that calls gnome-terminal-server to open a new window and then exits. Because the command you have called exits, the dispVM closes. It's expected behaviour.

**Comment by marmarek** [comment]
And this is also the reason why in default configuration there is xterm
used, instead of gnome-terminal...

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by maxsu** [comment]
Thanks unman, I've verified that this is indeed what's going on. I found some more details in the second answer (here)[http://unix.stackexchange.com/questions/201900/run-true-multiple-process-instances-of-gnome-terminal], and in the debugging instructions (here)[https://wiki.gnome.org/Apps/Terminal/Debugging].

Despite the technical difficulty, I think a user should reasonably be able to use gnome-terminal from a disp-VM. I've cobbled together a rather ugly solution:

> sh -c 'echo /usr/libexec/gnome-terminal-server --app-id my.qubes.Terminal \& sleep 2 \&\& gnome-terminal --app-id my.qubes.Terminal

I've tested this solution and it works to create a persistent gnome-terminal window. Additionally it correctly shuts down the dispVM once the last visible terminal window is destroyed (similar to the DispVM: Firefox use case), as this causes the gnome-terminal-server process to be destroyed.

I'm not entirely satisfied with this solution:

1. If gnome-terminal-server is slow to start for some reason (or if we remove the `sleep` invocation), we get an `Error creating terminal: The name my.qubes.Terminal was not provided by any .service files`
2.  If a malicious process is able to persist the gnome-terminal-server beyond the point where all visible terminal windows have been closed, this would prevent shutdown of the dispvm, which might escape the attention of the user.

Since the process running in the shell could conceivably create a dummy display and send a terminal window to that display, item 2 seems like a risk that might not happen in the firefox case (where as far as I know firefox cannot simply execute arbitrary code in a privileged shell).

**Comment by jpouellet** [comment]
> If a malicious process is able to persist the gnome-terminal-server beyond the point where all visible terminal windows have been closed, this would prevent shutdown of the dispvm, which might escape the attention of the user.

This is not unique to gnome-terminal-server. For attacker-controlled DispVMs, there is no trusted correlation between all windows being closed and a DispVM being shut down. This is true irrespective of the initial program started.

**Comment by andrewclausen** [comment]
I think I have a systemd solution for this problem:

`qvm-run '$dispvm' "gnome-terminal; systemctl --user start gnome-terminal-server --wait"`

P.S. Sorry for spamming the mailing list.  I should have checked here first.

**Comment by strugee** [comment]
I was able to successfully fix this bug by modifying `/usr/share/applications/org.gnome.Terminal.desktop` such that the `Exec=` line now reads:

    Exec=sh -c "gnome-terminal && systemctl --user start --wait gnome-terminal-server"

Shoutout to @andrewclausen for coming up with something way better than the hacks I came up with (it involved piping `gdbus` to `grep -q`...)

Now the question I'm thinking about is how to ship this. I assume the Qubes team doesn't really want to maintain a fork of GNOME Terminal packaging... I wonder if a semi-decent way to do this is to run a sed script that makes the change on boot as long as the qube is an AppVM and not a TemplateVM. We could also put a replacement in `/usr/local/share/applications`, but of course `/usr/local` is bound to `/rw`.

Another approach: we create `/usr/share/qubes-xdg-override/applications` or something, then set `$XDG_DATA_DIR` to `/usr/local/share:/usr/share/qubes-xdg-override:/usr/share`. Then we could drop a new, fixed override desktop file in our new override directory.

**Comment by Osndok** [comment]
Perhaps I am missing something, but why can't we just add the `--wait` option?

**Comment by andrewdavidwong** [comment]
@marmarek, is this fix intended to be in 4.0, as well? If not, what do you think of hiding the `gnome-terminal` shortcut from DisposableVM menu entries? A user [suggested](https://www.reddit.com/r/Qubes/comments/ir7cqe/dispvm_wont_launch_files_terminal_only_browser/g5ctxb5/) this as a way to avoid frustrating new users who are not aware of this bug.

**Comment by kgadek** [comment]
> Perhaps I am missing something, but why can't we just add the `--wait` option?

Both adding `--wait` and using `… && systemctl …` worked for me (with Fedora 33 template).

Notably, `qubes-run-terminal` did NOT work, as on (fully updated `qubes-template-fedora-33`) I have pretty old version of it.
