### ISSUE TITLE
split-gpg for git broken on Debian stretch

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#2582]
#### Qubes OS version (e.g., `R3.2`):

R3.2 with testing repository

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):

debian-stretch

---

### Expected behavior:

```
git log --show-signature
```

Should just work.

### Actual behavior:

```
qubes-gpg-client: unrecognized option '--keyid-format=long'
```

### Steps to reproduce the behavior:

Change the template of a fronted and backed VM using split-gpg from debian-8 to debian-stretch.

### General notes:

stretch comes with gpg 2.1 only. gpg 1.x is not available. (The gnupg and gnupg2 package are the same.)

**Comment by WillyPillow** [comment]
I just ran into this issue with stretch as the frontend and jessie as the backend, and came up with a quick hack as a temporary solution.

Basically I made the wrapper ignore the --keyid-format option by adding the following lines in the parsing part of /usr/bin/qubes-gpg-client-wrapper:
```
--keyid-format=long)
  shift
  ;;
```

**Comment by tasket** [comment]
Ran into this also with `git tag -v`. A little surprised split-gpg is still tooled for GPG 1.x.

Used @WillyPillow 's workaround.

What should the fix look like? I noticed that Fedora 25 comes with gpg2 by default.

**Comment by marmarek** [comment]
> A little surprised split-gpg is still tooled for GPG 1.x.

That would mean you use really old version (https://github.com/QubesOS/qubes-app-linux-split-gpg/commit/3bb1f8e198501aa2e71ad4b1ae1b5fc6f21f62c2). Maybe you have updated version in `/etc/qubes-rpc/qubes.Gpg.rpmnew` file?

**Comment by tasket** [comment]
There are no *dpkg-new in that folder and the file uses `gpg2`.

But the issue is in qubes-gpg-client-wrapper or gpg-server, I think..?

**Comment by marmarek** [comment]
Hmm, if your `/etc/qubes-rpc/qubes.Gpg` have "gpg2", what part use gpg 1.x? How exactly you come to that conclusion?

**Comment by tasket** [comment]
Re: gpg 1.x, I thought the original issue notes implied there was a version mismatch somewhere. 

Real bug is probably here:
https://github.com/QubesOS/qubes-app-linux-split-gpg/blob/master/src/gpg-common.h

The `keyid-format` is not an included option so `qubes-gpg-client` rejects the call.
