### ISSUE TITLE
xen.cfg is not created during EFI install on MacBookPro11,3

### ISSUE THREAD

**Issue by sneak** [QubesOS/qubes-issues#2588]
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable): n/a

---

### Expected behavior:

xen.cfg written, so `xen-$VER.efi` can find it

### Actual behavior:

xen.cfg not written

### Steps to reproduce the behavior:

1. wipe macbookpro /dev/disk0
1. format entire disk with GPT using diskutil to create EFI system partition
1. install rEFInd boot manager to EFI system partition
1. install qubes from USB stick EFI booted via rEFInd

### General notes:

---

**Comment by andrewdavidwong** [comment]
This is too localized for `qubes-issues`. Please consider posting this to the `qubes-users` mailing list instead. (You can read more about our mailing lists [here](https://www.qubes-os.org/mailing-lists/).)

`qubes-users` is intended for these sorts of questions and receives much more traffic, which means that your question is more likely to receive a response there.
