### ISSUE TITLE
Dual-monitor windows HVM behaves weirdly (no second monitor activity at all, or very glitchy in debug mode)

### ISSUE THREAD

**Issue by tonsimple** [QubesOS/qubes-issues#2589]
#### Qubes OS version (e.g., `R3.2`):
3.2
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):
a windows-7 based HVM with Qubes Tools installed, and seamless GUI disabled

---

### Expected behavior:
When two monitors are available, the HVM is expected to behave as a dual-head windows 7 would (with ultramon one could set up separate wallpapers, could also move windows there, manipulate them, etc.)
Also, ideally, I'd like to be able to make it go "fullscreen on both screens" giving me almost exact experience of working in a windows environment (with no "screen estate" wasted on borders, etc.)

### Actual behavior:

Unless debug mode activated, second screen is never ever being touched by windows HVM no matter what.

If debug mode activated, a second screen shows up as a window and can be forcibly dragged to second monitor, but is unusable (trying to move cursor there causes weird ghostly clicks all over the "main" desktop, and general behavior as if cursor was still manipulating stuff on "main" monitor)

Going fullscreen is always limited to main monitor, second remains un-affected by the HVM and shows qubes wallpaper.

### Steps to reproduce the behavior:

Have a set up windows HVM, have a video card that can do at least two monitors, try running the HVM with two monitors.

### General notes:
Partial workaround:
1. disable second monitor inside windows 7 (ONLY inside windows 7 HVM) by going into "resolutions" settings
2. move the HVM window up the qubes workspace so it is reduced in size (can be tricky, it tries to auto-maximize or slip to another workplace)
3.   drag it by the corner to expand to both screens. Gives almost okay (but not 100% okay) windows 7 working experience)

EDIT: ADDITIONAL INFORMATION:
The system uses intel integrated graphics (Core i7 Skylake + Asus Hero VIII), monitors are both VX239H

---

**Comment by andrewdavidwong** [comment]
Sounds similar (but not identical to) #2487.

See also: #1704 and #1896

**Comment by tonsimple** [comment]
Yeah. 
I've just tried it with a different monitor (with a slightly smaller resolution) just in case it's like [#2487](https://github.com/QubesOS/qubes-issues/issues/2487) in that monitor resolution has something to do with it.
No cigar (issue persists)

Also reproduced it on a slightly different system (also asus hero viii + core i7 skylake, integrated graphics)

Will try out with a radeon card around next week.

**Comment by tonsimple** [comment]
Can not replicate with a Radeon HD 6450

**Comment by tonsimple** [comment]
Replicated on another machine with integrated graphics.
Something to do with Intel's IGFX it seems.

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
