### ISSUE TITLE
[Clarification request] Add to documentation how to set the "(default)" template VM (Qubes VM Manager)

### ISSUE THREAD

**Issue by Wikinaut** [QubesOS/qubes-issues#2591]
#### Qubes OS version (e.g., `R3.2`):
3.2

When editing VM properties in the VM Manager, in the Template dropdown menu, one template is marked as `debian-8 (default)` (in my case).

After successful creation and customization of a new template VM `debian-9` I now want to have this `debian-9` template VM item marked as `debian-9 (default)`, but the current documentation is silent how this can be set.

Please advice.

**Comment by andrewdavidwong** [comment]
Qubes Manager -> System -> Global settings -> Default template

**Comment by Wikinaut** [comment]
@andrewdavidwong uh, yes, thank you.
