### ISSUE TITLE
Bulk AppVM changes: proposal to add a command for "bulk changing" the template VM 

### ISSUE THREAD

**Issue by Wikinaut** [QubesOS/qubes-issues#2595]
#### Qubes OS version (e.g., `R3.2`):
3.2

User story:
I want to change all (or selected) AppVMs based on my debian-8 TemplateVM to debian-9.

Currently, this has to be done one-by-one. It would be nice to have a "bulk change" function.

**Comment by marmarek** [comment]
Can be done by a simple script:
```
for vm in my-vm1 my-vm2 my-vm3 ...; do
   qvm-prefs -s $vm template debian-9
done
```

Not as user friendly as it could be, but realistically we will not have anything better soon. So, I'm closing this issue right now. If someone will come with desire to actually implement it, we may reopen it.

**Comment by Wikinaut** [comment]
@marmarek good solution; Would you mind I add this hint to a suited documentation page, perhaps in the section "Troubleshooting" under https://www.qubes-os.org/doc/remove-vm-manually/ a new entry bulk-changing-vms-manually ?

**Comment by andrewdavidwong** [comment]
@Wikinaut: Please feel free to submit a qubes-doc pull request for that.
