### ISSUE TITLE
PCI "full controller" passthrough for Windows HVM still not working 

### ISSUE THREAD

**Issue by tonsimple** [QubesOS/qubes-issues#2597]
#### Qubes OS version (e.g., `R3.2`):
3.2
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):
dom0?
Windows 7 HVM

---

### Expected behavior:
Assigning full USB controller to win7 VM with pci_strictreset set to false will work and allow using a USB device

### Actual behavior:
Attempt to assign a USB controller fail with various interesting (but useless) results.

First, without pci_strictreset none of the controllers I have could even begin to be assigned.
_(but that is expected, same thing happens for "normal" VMs and pci_strictreset was a sufficient cure.)_

Attempting to assign a NEC USB 3.0 controller:
VM fails to start, libxenlight reports "unable to create domain win7"

ASMedia USB3.0 - same

Intel USB 3.0 controller
the most interesting result
The VM starts and controller is found, but it is found as a "detachable" device.
Installation of Intel drivers does not cause it to be detected properly (the icon changes from windows device warning sign to "normal usb controller" sign but it still remains a "detachable device")

Attempts to connect a USB device to the physical port, however, lead to literally nothing (device is not detected by the windows VM as if no controller was present)

### Steps to reproduce the behavior:

Have a created Windows HVM with Qubes tools installed

Shut it down.

Assign a USB 3.0 pcie controller to it via VM manager

Start VM

### General notes:

Building an elaborate workaround for printing that involves a separate physical fanless PC with windows XP embedded so that I can get a bunch of USB devices forwarded over network to the windows VM (therere's software for forwarding USB ports like that, hope it works)

---

#### Related issues:
I humbly suspect that closed issue #1659 is related

**Comment by marmarek** [comment]
What Xen version do you have (`rpm -q xen`)? There were some more fixes in 4.6.3-25 (and 4.6.4-25) which is still in testing repository.
For non-intel USB controller - check `/var/log/libvirt/libxl/libxl-driver.log` and `/var/log/xen/console/hypervisor.log` after failed startup - maybe some clue will be there.

**Comment by tonsimple** [comment]
xen-4.6.3-24.fc23.x86_64

I'll try re-doing everything and getting those logs around next week (my qubes desktop is current making good use of those usb controllers in other appvms)

**Comment by tonsimple** [comment]
Managed to workaround via fedora-24's usbip module (which appears fairly broken btw) and usbip windows client (also broken)
Workaround works only if printer sharing service is running in usbvm and if usbip is attached to device driver before printer sharing starts up 

Oh, and I needed to enable networking between my USBvm and my windows HVM (not really a biggie since neither is allowed into "the internet at large")

Will probs work like this until PCI passthrough or, perhaps even better, qubes-usb-proxy, start working for windows  HVMs

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
