### ISSUE TITLE
[really minor] mouse wheel tilt (buttons 6 and 7 per xev) not passed to windows HVM correctly

### ISSUE THREAD

**Issue by tonsimple** [QubesOS/qubes-issues#2598]
#### Qubes OS version (e.g., `R3.2`):
3.2
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):
WIndows 7 HVM

---

### Expected behavior:
If tilt works with normal fedora and debian appvms _(tested, it works, tilting Logitech Performance MX wheel works in a qubes linux-based appvm with firefox if xorg.conf is correctly configured to use udev driver and correct event)_ then tilt should also work in Windows HVM

### Actual behavior:
Windows ignores wheel tilt or interprets it as a random button click

Meanwhile, linux appvms are reacting to tilt correctly

### Steps to reproduce the behavior:
Have a mouse with wheel tilt.
Have it configured so tilt events are detected and correctly passed to linux AppVMs
Have a windows 7 HVM with Qubes Tools installed
Start windows HVM 
Try using the tilt feature
### General notes:
I understand it's like, really really small issue :)
But I really like tilt :( and maybe someone knows a clever workaround or a fix will be easy.

---

**Comment by marmarek** [comment]
Slightly offtopic: without Qubes tools it will not work, as gui-agent in qemu does not have it implemented:
https://github.com/QubesOS/qubes-gui-agent-xen-hvm-stubdom/blob/master/gui-agent-qemu/qubes-gui.c#L337-L346

On topic: Windows gui-agent (aka wga) does not have it implemented either:
https://github.com/QubesOS/qubes-gui-agent-windows/blob/release2/gui-agent/vchan-handlers.c#L221-L242

Looking at [documentation](https://msdn.microsoft.com/en-us/library/windows/desktop/ms646260(v=vs.85).aspx), adding Button6 and Button7 as MOUSEEVENTF_HWHEEL should do the trick.
Anyone care to send pull request?

**Comment by marmarek** [comment]
Just to make sure - check [wga logs](https://www.qubes-os.org/doc/windows-tools-3/#configuration) to see if "unknown button pressed/released " messages are logged and button numbers are 6 and 7.

**Comment by tonsimple** [comment]
Hm, found file 
qga-20170122-001659-1372.txt in logs
This is what looks like
http://pastebin.com/fVp1z87q

Is that it?

**Comment by marmarek** [comment]
Yes, exactly. And buttons indeed are 6 and 7.

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
