### ISSUE TITLE
Add support for translations in Qubes Manager

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#2599]

**Comment by pdinoto** [comment]
I will be involved in the actual spanish localization.
Let me know if I can help testing this changes.

**Comment by marmarek** [comment]
@pdinoto See this file: https://github.com/marmarek/qubes-manager/blob/519cacc5ce44ba7a0a553251498a7ff0b77fb8ba/i18n/qubesmanager_es.ts
Does it makes sense? When loaded to transifex probably it will be much more user friendly.
Can you provide few translations to put there to actually test if it works? Then I'd merge this change (currently living in `i18n` branch) into master branch and upload updated package - this would make further testing much easier.

**Comment by marmarek** [comment]
@mfc could you add me to qubes organization on transifex, so I'll be able to upload/download translation files?

**Comment by mfc** [comment]
@marmarek sent you an invitation, let me know if you can get in or we need to ask transifex to manually add you.

**Comment by marmarek** [comment]
@mfc thanks, it works.

**Comment by pdinoto** [comment]
@marmarek: Installed `qubes-manager-3.2.7-1.fc23`. Test `es` translation working as expected.

Noticed that any right-click (like trying to get the contextual menu for a running VM, or even pulling the status bar menu) brings 
![2017-02-05-qubes-manager-right-click-error](https://cloud.githubusercontent.com/assets/3193806/22633072/2c27635e-ebfd-11e6-8e07-d14dee0f317c.png), and Qubes Manager has to be killed and restarted. Cannot click on "More details". Not sure if it is related. Any pointers how to provide more meaninful debug info?

**Comment by marmarek** [comment]
It looks to affect not only right-clicks but many more dialogs - like removing VM, stopping it etc.

**Comment by pdinoto** [comment]
@marmarek:  Installed `qubes-manager-3.2.8-1.fc23`. The error I was experiencing :arrow_up: does not appear anymore. 

Noticed that amongst the changes there is some string processing at  `qubesmanager/main.py` (L105-108) and now I do not longer see the a notification bubble when copy inter-vm copy&paste. I wonder if that could be related.

Other strings modified in 3.2.8 seem to be displaying fine.
The strings for the copy&paste desktop notification were not translated yet.

**Comment by mfc** [comment]
@marmarek can you pull in the recently fully-translated qubes vm manager so we can see what it looks like? thanks!

**Comment by marmarek** [comment]
[Done](https://github.com/QubesOS/updates-status/issues/7)

**Comment by pdinoto** [comment]
Looking good!

Quick question: Where do desktop notification message strings come from? (Like "Attached block device..." and "Detached block device..." when inserting a USB drive and using `sys-usb`)

**Comment by marmarek** [comment]
It's also in manager (https://github.com/QubesOS/qubes-manager/blob/master/qubesmanager/block.py), but it isn't included in automatic translation because of technical difficulties (https://github.com/QubesOS/qubes-issues/issues/2637#issuecomment-280944547)
