### ISSUE TITLE
Security and functional implications of  iommu=no-igfx (helps me with video tearing, oddly)

### ISSUE THREAD

**Issue by tonsimple** [QubesOS/qubes-issues#2601]
#### Qubes OS version (e.g., `R3.2`):
3.2
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):

dom0?
 
---

### Expected behavior:

Option "TearFree" "true" in xorg.conf would remove tearing without  iommu=no-igfx being passed as boot parameter

### Actual behavior:
Tearing only seems to disappear for me after  iommu=no-igfx is passed and that option is on 
Also, seems  iommu=no-igfx generally improves my video's (Integrated graphics, skylake Core i7 + ASUS Hero VIII) perfomance
### Steps to reproduce the behavior:
Have similar hardware (I strongly suspect it's hardware-dependent, have no issues enabling TearFree w/o extra iommu=no-igfx fuss on a laptop)
Try setting Option TearFree to true without passing  iommu=no-igfx as boot parameter 
reboot
Try setting Option TearFree to true WITH passing  iommu=no-igfx as boot parameter
reboot

### General notes:
Not so much an issue (I am almost satisfied with how my video is working for qubes now) but I'd like to understand better what  iommu=no-igfx implies and whether it's worth the (minor, but I think non-placebo) improvement of video behavior.

Do I understand correctly that IOMMU/vt-d is still working okay-dokay for everything that is not the integrated GPU?  

---

**Comment by andrewdavidwong** [comment]
> Not so much an issue (I am almost satisfied with how my video is working for qubes now) but I'd like to understand better what iommu=no-igfx implies and whether it's worth the (minor, but I think non-placebo) improvement of video behavior.

This would be more appropriate for qubes-devel. We try to reserve qubes-issues for things that are actionable.
