### ISSUE TITLE
Enable Torified updates by default in installer and remove "experimental" label

### ISSUE THREAD

**Issue by mfc** [QubesOS/qubes-issues#2604]
The level of adoption of torified system updates is painfully low and not increasing in percentage, according to [the stats](https://www.qubes-os.org/counter/).

This is primarily due to it not being the default. The level of adoption for a USB qube is probably similarly low because it is not the default. This is a real shame because it is one of the main differentiating points for Qubes.

I think these features have been "out" for long enough that we should remove the "experimental" tag from their description in the firstboot screen. In addition, the USB qube and torifying updates should be selected as default, with adequate descriptive text so that users can make an informed decision about whether they want the default or to change it.

**Comment by marmarek** [comment]
Removing "experimental" tag indeed maybe a good idea. But I'm strongly against enabling routing all the traffic through tor (this is what that option is about - it isn't only about updates). While it may make some targeted attacks harder, in majority use cases it will only greatly degrade user experience.

Do we need an option to download updates (only) over tor? Maybe.

**Comment by mfc** [comment]
> routing all the traffic through tor (this is what that option is about - it isn't only about updates)

I don't think that's an accurate representation of what happens. even if you select this option ("route all traffic through tor [experimental]"), the default qubes that get created and their networking are:
* personal: sys-firewall
* banking: sys-firewall
* anon-whonix: sys-whonix
* vault: none
* untrusted: sys-firewall

What is does do is make the default networkvm for a new qube `sys-whonix`, which can be modified in the creation screen they are in.

**Comment by marmarek** [comment]
Indeed. Anyway, it isn't only about updates currently. And actually IMO the current situation is buggy, as it is neither "everything" nor "updates only".

**Comment by mfc** [comment]
yes agreed. So I would say:

Default:
* system and template updates over Tor
* installation of `whonix-gateway` and `whonix-workstation`
* Default [networking](https://github.com/QubesOS/qubes-issues/issues/1763) of new qubes: `sys-firewall`

Option presented to user:
- [x] Enable system updates over the Tor anonymity network

**Comment by andrewdavidwong** [comment]
> with adequate descriptive text so that users can make an informed decision about whether they want the default or to change it

This is a good candidate for an explanatory tooltip (#2211).

> Option presented to user:
> - [x]    Enable system updates over the Tor anonymity network

Perhaps also:

> - [x] Install Whonix TemplateVMs.

For some people, using Tor at all is dangerous, illegal, or simply against corporate policy. For such users, there may be no point in installing the Whonix TemplateVMs at all, since they will never be used; doing so may just be a liability.

**Comment by marmarek** [comment]
> Perhaps also:
> 
>     Install Whonix TemplateVMs.
> 
> For some people, using Tor at all is dangerous, illegal, or simply against corporate policy. For such users, there may be no point in installing the Whonix TemplateVMs at all, since they will never be used; doing so may just be a liability.

This is already possible in software selection before installation. You can opt-out from installing those templates, and then Whonix-related options in firstboot are inactive.

**Comment by andrewdavidwong** [comment]
This issue combines two distinct things, so I'm branching the USB qube issue off into a separate ticket: #2665.

**Comment by mfc** [comment]
@marmarek with [whonix set to be included in 4.0-rc2](https://github.com/QubesOS/qubes-issues/issues/2604), are we in a position to implement this as well? From your previous comment it looks like you have the logic of it already figured out.

**Comment by marmarek** [comment]
Yes, I think we can drop "experimental" label. But I'm still not sure about enabling it by default. For most people disadvantages of this (slow updates, timeouts etc) may be greater than advantages (mitigation against _targeted_ attacks).
@rootkovska @andrewdavidwong ?

**Comment by andrewdavidwong** [comment]
> But I'm still not sure about enabling it by default. For most people disadvantages of this (slow updates, timeouts etc) may be greater than advantages (mitigation against targeted attacks).

I think that's a reasonable assessment. If it's enabled by default, there may be a lot of people who don't realize they're using it, and they may attribute the slowness to something else or simply be unhappy with their user experience as a result. I think we should just explain the trade-off to the user (e.g., in an explanatory tooltip).

**Comment by rootkovska** [comment]
Agree, we should _not_ enable Tor updates by default. This option is useful/attractive only to specific groups of Qubes users, not all.

**Comment by mfc** [comment]
I think *if* the Whonix templates are selected for installation, then torified updated should be enabled by default.

**Comment by rootkovska** [comment]
> I think if the Whonix templates are selected for installation, then torified system updates should be enabled by default.

I don't agree. Lots of people might want to install Whonix just out of curiosity, or because "maybe I will use sometime in the future". We should not automatically force them into Torified updates.

**Comment by h01ger** [comment]
On Wed, Sep 20, 2017 at 12:55:26AM -0700, Joanna Rutkowska wrote:
> I don't agree. Lots of people might want to install Whonix just out of
> curiosity, or because "maybe I will use sometime in the future". We should
> not automatically force them into Torified updates.

agreed. I want my whonix templates updated via tor, but not others.


-- 
cheers,
	Holger

**Comment by mfc** [comment]
> agreed. I want my whonix templates updated via tor, but not others.

we are talking about system updates, not template updates.

I find folks' positions perplexing, given that using Tor for system updates improves the security position of the user which I would have thought a security-focused OS would want to encourage users to adopt, assuming they are interested in using Tor in the first place. 

It also reduces the personal information collected by Qubes servers (and other repo servers) of Qubes users (and the intermediaries who see the HTTP traffic), which I imagine would be a benefit towards reducing how much the user has to trust the Qubes team (and others). This usually is a "theme" of Qubes development practice but I guess not in this case?

But apparently I'm in the minority and not going to belabor this point now.

@marmarek have you changed the wording of the option to be more accurate, as previously discussed in this thread? from: `route all traffic through tor [experimental]` to: ` Enable system updates over the Tor anonymity network using Whonix`. If so, then we can keep this closed.

**Comment by mfc** [comment]
again: if a user is installing whonix templates, it is because they would like to use them. if they have made that decision, then helping them take advantage of that added functionality would seem helpful. 

if it is against workplace policy, if they are going to killed for using it, then they are probably not going to install the whonix templates. yes?

if they are unsure whether or not they want whonix templates and tor functionality, then we can put some language about tor in a tooltip on first boot, as you previously suggested. they can always deselect the option. and they also get additional language about tor via the first start-up of `sys-whonix`.

Qubes system updates are usually quite small, tor's slight slowness is not really noticed on them. again by informing the user through the initial tooltip, they can make an informed decision.

if a user is not interested in Qubes' integrated tor-based privacy solutions, then they should not select the whonix templates for installation. if they are interested in them, then we should help them set them up properly.

**Comment by unman** [comment]
There are people who will want to use Tor for _some_ qubes, while maintaining an apparently clean image the rest of the time. You shouldn't assume that because they want to use Tor _some_ of the time, they want all their system updates to run through Tor. This may or may not be the case, and your assumption is dangerous.

**Comment by mfc** [comment]
again: we are currently talking about dom0 system updates, not "all their system updates".

if a user wants to use tor "*some* of the time", then they have clearly made a decision that using tor is not going to kill them, and that tor is actually useful for their desktop experience. your argument that such a default would be "dangerous" makes no logical sense.

as a reminder:

*if* user installs whonix templates
*then* suggest to user in firstboot: 
- [x] `Enable system updates over the Tor anonymity network using Whonix`

or perhaps

- [x] `Enable Qubes OS updates over the Tor anonymity network using Whonix`

if you want to make even more clear this is not affecting non-whonix template updates.

end result networking-wise is:
* dom0 UpdateVM: `sys-whonix`
* default networking of new qubes: `sys-firewall`
* default networking of non-whonix templates: `sys-firewall`
* default networking of whonix templates: `sys-whonix`

**Comment by h01ger** [comment]
On Sun, Oct 01, 2017 at 09:09:30AM -0700, Michael Carbone wrote:
> again: we are currently talking about dom0 system updates, not "all their system updates".

so what? why should installing $some_templates cause changes how dom0 is
configured? this makes no sense :)

> if a user wants to use tor "*some* of the time", then they have clearly made a 
> decision that using tor is not going to kill them,

so far, I'm with you…

> and that tor is actually useful for their desktop experience. your argument
> that such a default would be "dangerous" makes no logical sense.

ok, let me try another analogy: using Tor is like (not) carrying a gun.
(though I can see how this doesnt work for some. ;) I'll try anyway.)
Clearly it's not *always* useful (not) to carry a gun, sometimes you are more
safe when doing so, but sometimes you are more safe when not doing so.
(This very much depends on the situation… I hope we can agree that not
all situations are the same.)

Some people (of the set of people who have whonix installed) prefer (for
whatever reasons) to update dom0 via tor, some not.

The simple fact that whonix is installed doesnt really say anything
about the situation / people's preferences.

Using tor doesnt magically add "security" to your internet connection.
Depending on "how you see it" (and other factors), it might also make 
your internet connection less secure. (This is like (not) carrying
guns, which also doesn't make *every* sitution more secure.)

Having an easy way to configure whether tor should be used for dom0
updates obviously is great, because sometimes people preferences 
change according to situations.


-- 
cheers,
	Holger

**Comment by mfc** [comment]
> so what? why should installing $some_templates cause changes how dom0 is
configured? this makes no sense :)

because they could not ask Qubes to torify their system updates if they don't have whonix templates installed? and because installing whonix templates is a signal that the user is interested in integrating tor into their desktop?

> The simple fact that whonix is installed doesnt really say anything
about the situation / people's preferences.

yes it says that they have determined they are not going to immediately die as soon as they use tor, that having tor on their system is not going to get them fired, etc.

> Some people (of the set of people who have whonix installed) prefer (for
whatever reasons) to update dom0 via tor, some not.

totally. i am simply trying to push for safer/more-privacy-friendly defaults, since many users will not change them.

**Comment by unman** [comment]
> again: we are currently talking about dom0 system updates, not "all their system updates".

Yes, I understand that, but you should realise that "system updates" are not monolithic. At a minimum there are Fedora updates and Qubes updates, and whether a user updates via Tor or clearnet may change from time to time. 

> if a user wants to use tor "some of the time", then they have clearly made a decision that using tor is not going to kill them, and that tor is actually useful for their desktop experience. your argument that such a default would be "dangerous" makes no logical sense.

No, it's this that doesn't make sense. Someone may want/need the protection of Tor at some times, in some circumstances, while accepting that using Tor may be dangerous. Making updates default to using Tor may expose them and open them to risk. Your flippancy on this is misplaced.

One way of mitigating the risk would be to turn off automatic update checks, with the option to enable it offered as another option to the user.

**Comment by mfc** [comment]
hey all, sorry for the exasperated tone previously, thanks for your patience with it.

i think once the GUI salt recipe "app store" exists i will be able create ways to make it easier for high-risk, less-tech-savvy people to setup Qubes appropriately for their needs. 

instead of arguing for a change of the default in this regard, maybe just have a default-not-selected-option in firstboot that *does* include both template and system updates over Tor:

- [ ] Enable system and template updates over the Tor anonymity network using Whonix

that is only possible if the user has chosen to install Whonix templates.

**Comment by DrCMY** [comment]
Hi, what's the official explanation from Qubes staff about the torified updates?
Thank you

**Comment by marmarek** [comment]
See those three comments: https://github.com/QubesOS/qubes-issues/issues/2604#issuecomment-330270721 https://github.com/QubesOS/qubes-issues/issues/2604#issuecomment-330423579 https://github.com/QubesOS/qubes-issues/issues/2604#issuecomment-330452955
