### ISSUE TITLE
turn on default VM Manager: view NetVM

### ISSUE THREAD

**Issue by mfc** [QubesOS/qubes-issues#2605]
The networking of qubes is an incredibly important component to being able to take advantage of the functionality of Qubes. By default the user cannot easily see the networking of the qubes they have running, or installed.

I would strongly recommend that the default VM Manager view includes view of the NetVM. Currently I must manually advise it to each new Qubes user.

(also as a bonus, View CPU should not be a default, given that [it is not implemented](https://github.com/QubesOS/qubes-issues/issues/1120)).

**Comment by jpouellet** [comment]
> (also as a bonus, View CPU should not be a default, given that it is not implemented).

It **is** implemented, just not for dom0.

Continuing discussion at https://github.com/QubesOS/qubes-issues/issues/1120#issuecomment-275973503
