### ISSUE TITLE
Qubes stub package for Fedora-minimal prevents installing required dependencies

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#2606]
#### Qubes OS version (e.g., `R3.2`):

`R3.2`

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):

`fedora-24-minimal`, possibly others

---

### Expected behavior:

`fedora-24-minimal` either includes required dependencies, such as `pycairo` (which is required for various Qubes tools to work properly), or, at the very least, users are allowed to install such packages themselves via `dnf`.

### Actual behavior:

`pycairo` is not included in `fedora-24-minimal`. Moreover, `qubes-template-minimal-stub` *prevents* users from installing it manually:

```
$ sudo dnf list available pycairo
Last metadata expiration check: 0:08:51 ago on Thu Jan 26 19:47:14 2017.
Available Packages
pycairo.i686                         1.10.0-4.fc24                        fedora
pycairo.x86_64                       1.10.0-4.fc24                        fedora

$ sudo dnf install pycairo
Package qubes-template-minimal-stub-1.1-1.fc23.noarch is already installed, skipping.
Dependencies resolved.
Nothing to do.
Sending application list and icons to dom0
Complete!
```

---

#### Related issues:

#2071, #2566, #2572

**Comment by marmarek** [comment]
This issue should be gone after implementing #2572, as stub package will not be needed anymore. But not sure how to proceed with the current version...

Some workaround may be forcing specific version of a package - like `sudo dnf install pycairo-1.10*`

**Comment by andrewdavidwong** [comment]
> Some workaround may be forcing specific version of a package - like sudo dnf install pycairo-1.10*

Yes, this works.

**Comment by tasket** [comment]
Trying to install tinyproxy in fedora-24-minimal also runs into the same issue. OTOH, the minimal template upgraded to f25 can install tinyproxy.

**Comment by tasket** [comment]
f25 minimal can install pycairo, also.

**Comment by taradiddles** [comment]
> the minimal template upgraded to f25 can install tinyproxy.

I've upgraded a minimal f24 template to f25 but dnf install tinyproxy fails like with f24.

workaround:
sudo dnf download tinyproxy ImageMagick [...]
sudo dnf install tinyproxy-1.8.3-6.fc24.x86_64.rpm ImageMagick-6.9.3.0-6.fc25.x86_64.rpm [...]

(haven't tested what would happen when those packages will be updated though).

**Comment by marmarek** [comment]
I've tried building minimal template with `qubes-template-minimal-stub` dropped. Result was increase of RPM size from 493MB to 673MB and increase of raw `root.img` from 1.5GB to 2GB.
See here: https://travis-ci.org/marmarek/qubes-builder-fedora/branches (min-template branch, compare with master).
This should be much better after finishing #2771 and #2572. But maybe in the meantime (for new/updated temlates for Qubes 3.2) we should drop this hack anyway at the cost of bigger "minimal" template?
@andrewdavidwong any opinion on this?

**Comment by andrewdavidwong** [comment]
> I've tried building minimal template with qubes-template-minimal-stub dropped. Result was increase of RPM size from 493MB to 673MB and increase of raw root.img from 1.5GB to 2GB.
> See here: https://travis-ci.org/marmarek/qubes-builder-fedora/branches (min-template branch, compare with master).
> This should be much better after finishing #2771 and #2572. But maybe in the meantime (for new/updated temlates for Qubes 3.2) we should drop this hack anyway at the cost of bigger "minimal" template?
> @andrewdavidwong any opinion on this?

Since it's just temporary, I have no strong opinion either way. Dropping the hack at the cost of a bigger minimal template sounds fine.

**Comment by marmarek** [comment]
Non-minimal fc25 template is 4.4GB (root.img), so minimal would be still much smaller.
