### ISSUE TITLE
Cannot build Ubuntu template

### ISSUE THREAD

**Issue by SurinameClubcard** [QubesOS/qubes-issues#2608]
#### Qubes OS version (e.g., `R3.2`):
R3.2

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):
ubuntu

---

### Expected behavior:
According to https://www.qubes-os.org/doc/templates/ubuntu/, Ubuntu 14.4 LTS (Trusty) can be built with little effort using Qubes Builder.

### Actual behavior:
Using the latest Qubes Builder, it is impossible to build Ubuntu 14.4 LTS. 

```
E: Unable to locate package libsystemd-dev
E: Unable to locate package libsystemd-dev
/home/user/qb/qubes-builder/qubes-src/builder-debian/Makefile.qubuntu:167: recipe for target 'dist-build-dep' failed
make[2]: *** [dist-build-dep] Error 123
Makefile.generic:139: recipe for target 'packages' failed
make[1]: *** [packages] Error 1
Makefile:209: recipe for target 'vmm-xen-vm' failed
make: *** [vmm-xen-vm] Error 1
```

### Steps to reproduce the behavior:
first make sure all tools are in place as mentioned by the Qubes Builder documentation
install Qubes Builder: 

```
git clone https://github.com/QubesOS/qubes-builder
cd qubes-builder/
./setup
make install-deps
make get-sources
make qubes-vm
```

### General notes:

I have seen several attempts to fix this:
https://groups.google.com/forum/#!topic/qubes-users/w0uZNr8nno8
https://groups.google.com/forum/#!topic/qubes-users/P8cIE3WnNzo
but I wasn't able to extract a real solution from this to fix it myself.

**Comment by unman** [comment]
Well, you're right. I'll update that page to include Xenial.
It is (just about) possible to build Trusty, but only by backporting swathes from Utopic - this is because the Qubes code requires stuff that's not available in Trusty. For example, the systemd support is marginal, so has to come from Utopic.
I'll see if I can rebuild - last time I couldn't get the networking to update automatically on Trusty.
If I cant do it I'll remove references to Trusty altogether.

**Comment by SurinameClubcard** [comment]
Thanks. I do hope it is possible to fix things for 14.04, I really need that older version for some legacy software.

**Comment by unman** [comment]
@SurinameClubcard Everything is fixed now, and Trusty will build. 
I suggest you use RELEASE:=master in builder.conf, and then run `make switch-branch` to get master of the components, before running `qubes-vm`

@andrewdavidwong Please close

**Comment by marmarek** [comment]
I wouldn't recommend switching to `master` branch, as there may be changes incompatible with current _stable_ release. And indeed `qubes-core-qubesdb` repository already contains Qubes 4.0 code in master branch.

**Comment by unman** [comment]
@marmarek Interesting - I have build teh Ubuntu tenmplates on master, and they seem to work fine. (I use one of them as dvm at the moment, but it's true that my usage may differ from the norm.) We'll see if any issues arise.

**Comment by marmarek** [comment]
Packages are slightly different (python bindings are in separate package now), but indeed it may not affect any VM functionality. At least yet ;)
