### ISSUE TITLE
Update cause qubes-mount-dir to not start in R3.2 archlinux template (broken systemd dependency)

### ISSUE THREAD

**Issue by ptitdoc** [QubesOS/qubes-issues#2609]
#### Qubes OS version (e.g., `R3.2`):
R3.2
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):
archlinux

---

### Expected behavior:
Template boot properly with last qubes-agent
### Actual behavior:
Template boots but qubes-mount-dirs does not start. Because of that /home/ is empty and gui-agent fails.

### General notes:
Jan 28 15:57:53 localhost systemd[1]: local-fs.target: Found ordering cycle on local-fs.target/start
Jan 28 15:57:53 localhost systemd[1]: local-fs.target: Found dependency on qubes-mount-dirs.service/start
Jan 28 15:57:53 localhost systemd[1]: local-fs.target: Found dependency on qubes-sysinit.service/start
Jan 28 15:57:53 localhost systemd[1]: local-fs.target: Found dependency on qubes-db.service/start
Jan 28 15:57:53 localhost systemd[1]: local-fs.target: Found dependency on local-fs.target/start
Jan 28 15:57:53 localhost systemd[1]: local-fs.target: Breaking ordering cycle by deleting job qubes-mount-dirs.service/start
Jan 28 15:57:53 localhost systemd[1]: qubes-mount-dirs.service: Job qubes-mount-dirs.service/start deleted to break ordering cycle starting with local-fs.target/start

---

#### Related issues:
https://github.com/QubesOS/qubes-core-agent-linux/pull/21

**Comment by ptitdoc** [comment]
The dependency cycle is apparently:
qubes-db > qubes-sysinit > qubes-mount-dirs > local-fs > qubes-db

We need to break either
local-fs > qubes-db 
or 
qubes-sysinit > qubes-mount-dirs

Any advice ?

**Comment by cryptix** [comment]
I saw this as well (programs wouldn't start because `/home/user` wasn't present) but sometimes it works? Just asking before I create a duplicate issue.

**Comment by ptitdoc** [comment]
I suggest replacing in qubes-db.service:
After=local-fs.target systemd-modules-load.service fedora-loadmodules.service
by
After=proc-xen.mount systemd-modules-load.service fedora-loadmodules.service

**Comment by ptitdoc** [comment]
@cryptix : There are in fact multiple problems in my case. Are you talking about the archlinux template ?

**Comment by cryptix** [comment]
> Are you talking about the archlinux template ?

yes. only having this with the arch template.

**Comment by ptitdoc** [comment]
Since qubes-core-vm 3.2.13, the code related to mounting /rw and /home changed so much that it may have solved some race condition observed before 3.2.13.
(cf https://github.com/QubesOS/qubes-core-agent-linux/pull/21)

**Comment by cryptix** [comment]
my template has qubes-vm-core 3.2.15-9 and I'm still seeing this. 

Granted, it happens sparingly but if it does it usually persists for 5-10 tries of rebooting the appVM.

**Comment by ptitdoc** [comment]
It look like the same symptoms. But I really wonder why it works sometimes.

You can try applying the proposed change to /usr/lib/systemd/system/qubes-db.service manually.

**Comment by ptitdoc** [comment]
Somehow, I'm using an old version of qubes-db... which already fixed this problem...

**Comment by ptitdoc** [comment]
I'm quite surprised that you use qubes-vm-core-3.2.15. Did you modified things to build it properly?

**Comment by marmarek** [comment]
> Somehow, I'm using an old version of qubes-db... and this problem is now fixed...

Yes, this was fixed as part of #2194. And the fix goes even further than you suggest - remove `local-fs.target` from dependencies, as in fact `/proc/xen` is not used anymore (at least by qubes-db).

**Comment by cryptix** [comment]
>  Did you modified things to build it properly?

you mean because of the pulseaudio 10 headers and xorg version? well.. I was lucky to build the template before that update landed in archland.
