### ISSUE TITLE
Pin qubes-issues

### ISSUE THREAD

**Issue by jpouellet** [QubesOS/qubes-issues#2610]
Github repos are sorted by reverse chronological last-commit date. Since qubes-issues does not get many commits, it tends to get hidden somewhere down the list. To someone coming across the github org before reading https://www.qubes-os.org/doc/reporting-bugs/ or equivelant, it is not obvious that much of the discussion happens there (here).

It may perhaps be beneficial to pin it to the top.

![qubes-repos](https://cloud.githubusercontent.com/assets/1231207/22412822/6a7bed78-e680-11e6-9197-2efaed75d0e1.png)

**Comment by marmarek** [comment]
Good idea, done.

**Comment by jpouellet** [comment]
@marmarek https://github.com/QubesOS/updates-status (which didn't exist at the time) is IMO another good candidate for pinning (never gets commits to bump it in repo list, but still has relevant activity).

**Comment by marmarek** [comment]
Added, thanks for suggestion.
