### ISSUE TITLE
(internal Notebook) Keyboard not working

### ISSUE THREAD

**Issue by n1LWeb** [QubesOS/qubes-issues#2611]
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable): dom0

---

### Steps to reproduce the behavior:
Not sure. Did some template updates in fedora-23 and debian-8 installed a windows HVM which doesn't Autostart

### General notes:
The Keyboard is working when entering the disk encryption password. After that the internal Keyboard an the Touchpad aren't working. External mouse and keyboard work. I have no USB VM and didn't tinker with USB/PCI devices.

I started creating a ProxyVM which doesn't autostart, and is not yet used anywhere.

The Keyboard was working until the last full reboot today.

Any ideas?

**Comment by andrewdavidwong** [comment]
This is too localized for `qubes-issues`. Please consider posting this to the `qubes-users` mailing list instead. (You can read more about our mailing lists [here](https://www.qubes-os.org/mailing-lists/).)

`qubes-users` is intended for these sorts of questions and receives much more traffic, which means that your question is more likely to receive a response there.
