### ISSUE TITLE
Generalize GUI daemon's xc_map_foreign_pages()

### ISSUE THREAD

**Issue by rootkovska** [QubesOS/qubes-issues#2619]
A few changes will be needed to allow to run gui-daemon in non-Dom0 VM when used in "true GuiDom" mode.

Some of these changes (especially with regards connection establishing between other AppVMs and GuiDom) should be resolved as part of #833. However, completing of #833 will likely not solve the problem with guid relying on the Xen's `xc_map_foreign_pages` (see https://github.com/QubesOS/qubes-gui-daemon/blob/v3.2.8/shmoverride/shmoverride.c#L76), which we need to solve for use with true GuiDom implementation.

**Comment by rootkovska** [comment]
While touching the GUID and reworking the xc_map_forgein_pages() for work with GUI domain, we should also make an effort to generalize this call to allow for future architectures not based on Xen. Ideally not even based on shared-memory-based hardware architectures.

Here the primary observation is that our GUI protocol already comprises two channels:
1. The metadata channel (e.g. MSG_CONFIGURE, etc) about configuration and positioning of windows, damage notifications, human input.
2. The actual data (i.e. pixels) channel, currently realized by xc_map_foreign_page as zero-copy memory sharing between the AppVM and Dom0, aided by the MSG_MFNDUMP messages flying over the meta channel.

So, the generalized version of the protocol should allow for providing independent implementations of this data channel (e.g. over network).

**Comment by marmarek** [comment]
Can you use full "GUI daemon" name? GUID means "globally unique identifier".

**Comment by marmarek** [comment]
For the record, this is implemented in:
https://github.com/QubesOS/qubes-gui-daemon/pull/21
https://github.com/QubesOS/qubes-gui-common/pull/2
https://github.com/QubesOS/qubes-gui-agent-linux/pull/34
(missing qubes-gui-agent-xen-hvm-stubdom)

**Comment by jpouellet** [comment]
@marmarek can this be closed since https://github.com/QubesOS/qubes-gui-agent-xen-hvm-stubdom/commit/e341ebd238a01b2f57267e907817a5469a2c253a?

**Comment by marmarek** [comment]
In theory there is one more component needed to be ported - gui-agent-windows. But it's kind of unmaintained...
