### ISSUE TITLE
Implement Qubes Management API methods

### ISSUE THREAD

**Issue by woju** [QubesOS/qubes-issues#2622]
* [x] `mgmt.property.List`
* [x] `mgmt.property.Get`
* [x] `mgmt.property.Help`
* [x] `mgmt.property.Reset`
* [x] `mgmt.property.Set`
* [x] `mgmt.property.Set`
* [x] `mgmt.vmclass.List`
* [x] `mgmt.vm.List`
* [x] `mgmt.vm.Create.<class>`
* [x] `mgmt.vm.CreateInPool.<class>`
* [x] `mgmt.vm.property.List`
* [x] `mgmt.vm.property.Get`
* [x] `mgmt.vm.property.Help`
* [x] `mgmt.vm.property.Reset`
* [x] `mgmt.vm.feature.List`
* [x] `mgmt.vm.feature.Get`
* [x] `mgmt.vm.feature.CheckWithTemplate`
* [x] `mgmt.vm.feature.Remove`
* [x] `mgmt.vm.feature.Set`
* [x] `mgmt.vm.tag.List`
* [x] `mgmt.vm.tag.Get`
* [x] `mgmt.vm.tag.Remove`
* [x] `mgmt.vm.tag.Set`
* [x] `mgmt.vm.firewall.Get`
* [x] `mgmt.vm.firewall.Set`
* [x] `mgmt.vm.firewall.Reload`
* [x] `mgmt.vm.device.<class>.Attach`
* [x] `mgmt.vm.device.<class>.Detach`
* [x] `mgmt.vm.device.<class>.List`
* [x] `mgmt.vm.device.<class>.Available`
* [x] `mgmt.pool.ListDrivers`
* [x] `mgmt.pool.List`
* [x] `mgmt.pool.Info`
* [x] `mgmt.pool.Add`
* [x] `mgmt.pool.Remove`
* [ ] `mgmt.pool.volume.List`
* [ ] `mgmt.pool.volume.Info`
* [ ] `mgmt.pool.volume.ListSnapshots`
* [ ] `mgmt.pool.volume.Snapshot`
* [ ] `mgmt.pool.volume.Revert`
* [ ] `mgmt.pool.volume.Resize`
* [x] `mgmt.vm.volume.List`
* [x] `mgmt.vm.volume.Info`
* [x] `mgmt.vm.volume.ListSnapshots`
* [x] `mgmt.vm.volume.Snapshot`
* [x] `mgmt.vm.volume.Revert`
* [x] `mgmt.vm.volume.Resize`
* [x] `mgmt.vm.volume.Import`
* [x] `mgmt.vm.volume.CloneFrom`
* [x] `mgmt.vm.volume.CloneTo`
* [x] `mgmt.vm.Start`
* [x] `mgmt.vm.Shutdown`
* [x] `mgmt.vm.Pause`
* [x] `mgmt.vm.Unpause`
* [x] `mgmt.vm.Kill`
* [x] `mgmt.label.List`
* [x] `mgmt.label.Get`
* [x] `mgmt.label.Create`
* [x] `mgmt.label.Remove`
* [x] `mgmt.backup.Execute`
* [x] `mgmt.backup.Info`
* [x] `mgmt.Events`

**Comment by woju** [comment]
For documentation see https://www.qubes-os.org/doc/mgmt1/.

Cc: @marmarek

**Comment by marmarek** [comment]
I'm going to ignore `admin.pool.volume.*` for Qubes 4.0, since we don't need them now (there are `admin.vm.volume.*` equivalent). But keep it in specification and implement when we will have use case for them.

So, for now, only backup-related calls are missing.
