### ISSUE TITLE
Audio support for Windows

### ISSUE THREAD

**Issue by omeg** [QubesOS/qubes-issues#2624]
Add audio support for Windows HVMs (probably try an already supported emulated audio hardware and use pulseaudio for streaming?)

**Comment by demianrihs** [comment]
Hello, any news on this? I am trying to achieve this using PCI Passthrough of the soundcard. But I am getting following error:

PCI device 0000:00:1f:3: no FLR, PM reset or bus reset available

**Comment by DemiMarie** [comment]
This should be doable by using standard Qubes audio in the stubdomain, and telling qemu to emulate audio hardware that Windows is known to support.

**Comment by SvenSemmler** [comment]
Until then ... this did the trick for me: https://www.amazon.com/gp/product/B07L56C28R

It's a USB Audio dongle and you can plugin in any headphone/mic or speaker you like.

**Comment by marmarek** [comment]
> This should be doable by using standard Qubes audio in the stubdomain, and telling qemu to emulate audio hardware that Windows is known to support.

Yes, it should work this way. A little concern is memory usage in stubdomain if you add pulseaudio there. Probably needs some smart tweaking `./configure` of pulseaudio.

Or integrating frontend part into qemu directly (like we do with gui-agent). More work, but also more effective resources usage.

**Comment by marmarek** [comment]
This actually (either method) looks like a very good task for someone to contribute.

**Comment by Yethal** [comment]
There exists a project on github that provides pretty much exactly what Qubes needs out of the box.
https://github.com/duncanthrax/scream

**Comment by 0rb677** [comment]
also this https://www.audinate.com/products/software/dante-virtual-soundcard

**Comment by elliotkillick** [comment]
Additionally, the RDP method:

1. Install FreeRDP on a Linux machine
2. Connect Windows and Linux via NetVMs or vchan
3. Enable RDP in Windows and connect to it from the FreeRDP client
4. The FreeRDP client supports sound and so it can be received over the RDP connection

**Comment by easydozen** [comment]
> Yes, it should work this way. A little concern is memory usage in stubdomain if you add pulseaudio there. Probably needs some smart tweaking `./configure` of pulseaudio.

The idea was realized [here](https://github.com/tabit-pro/Qway-qubes-repo/tree/26190c9b005b0886312521f0c5d71282bd0312e0/xen-hvm-stubdom-linux).
Beware, it's a highly experimental configuration.

The minimal pulseaudio was built using configuration tools, without deep-diving into the code: basic libraries, pulseaudio binary and two essential modules (vchan-sink and native-protocol-unix) the overall size is about 2MB.

Besides that, configuration of qemu have certain difficulties.
Before version 4.2 it was enough to tweak QEMU_AUDIO_TIMER_PERIOD to get good results in windows and linux VMs for intel-hda emulated sound card.
Nowadays we've got several improvements in qemu' audio subsystem. It seems that in qemu-4.2 the best out of the box result for linux VM could be achieved with es1370 - no need to fine-tune, acceptable sound quality, but there is no windows drivers for this sound card.

At the moment the Intel-hda audio device is used by default. It requires decreased latency on the 
host side to get rid of a choppy sound:

- run pacat-simple-vchan with option -l (low latency);
- run pulseaudio with modified daemon.conf - (default-fragments = 3 and default-fragment-size-msec = 5 should be enough).

If anyone has thoughts how to make this work upstreamable, please let me know.

**Comment by marmarek** [comment]
I assume audio card model can be made controlled from libvirt config, right? In that case, it can be made configurable depending on needs (works out of the box, or better sound quality).
How extra pulseaudio and changed qemu config influence memory usage within stubdomain? Do you need to increase that?

Generally, I think stubdomain part should be upstreamable mostly as is. Just few improvements to be more configurable:
 - make audio card model configurable through libvirt (I assume it's just removing options from stubdomain's init and adding appropriate xml part to libvirt template)
 - start pulseaudio daemon only if libvirt requested audio device

As for the dom0 part, it's slightly less obvious. For example I don't know how best ship daemon.conf modifications. Also, currently pacat-simple-vchan is started for the target vm only - we'd need an option to do that for stubdomain instead (or in addition?). I is done [here](https://github.com/QubesOS/qubes-core-admin-client/blob/master/qubesadmin/tools/qvm_start_daemon.py#L336-L347). Maybe control it with a feature (similar to [forcing stubdomain gui](https://github.com/QubesOS/qubes-core-admin-client/blob/master/qubesadmin/tools/qvm_start_daemon.py#L315-L316))? Or a VM property to choose audio mode (pulseaudio in vm, pulseaudio in stubdomain, both?)?

**Comment by easydozen** [comment]
Regarding the stubdomain part, I haven't spotted any memory related issues. Default _stubdom_mem_ value is ok. Card model, along with codec parameter could be moved to _libvirt_ config - yes, you're right. The trickiest detail is how to provide qemu' audio related tweaks. At the moment the only _timer-period_ option is used, but there are plenty of them.
It would be nice if we could use something like _<qemu:commandline>_ tag.

What do you think about _vchan-sink_ module? It was copied from _qubes-gui-agent-linux_ and built in a _pulseaudio_ tree w/o _qubesdb_ dependency. Should it be moved to _qubes-gui-agent-xen-hvm-stubdom_?

At the dom0 part, let's set aside _pulseaudio_ configuration for a while. We'll be able to find better solution later, I hope so.
In _qvm_start_daemon.py_ I'm using the following code to start _pacat-simple-vchan -l <stubdom_id>_  for a hvm by default:
```python

xid = vm.xid if vm.virt_mode != 'hvm' else vm.stubdom_xid
pacat_cmd = [PACAT_DAEMON_PATH, '-l', xid, vm.name]
```

The way I see it, If low latency (ll) mode replaced with dynamically adjustable latency, then it   would be not necessary to add new features. Please, tell me if you know that it can't be done.

But at the current state there are two features that should be implemented: vm/stubdom and ll      switch.

I'm working on a clean patchset in accordance to your suggestions. Would you prefer to receive PR  in the personal repository?

**Comment by marmarek** [comment]
>  It would be nice if we could use something like qemu:commandline tag.

You can already control qemu cmdline with `<emulator ... cmdline=`, but I'd treat it as a last resort and prefer proper libvirt device options.

> What do you think about _vchan-sink_ module? It was copied from _qubes-gui-agent-linux_ and built in a _pulseaudio_ tree w/o _qubesdb_ dependency. Should it be moved to _qubes-gui-agent-xen-hvm-stubdom_?

I don't like copy. It should be quite easy to get the same file compile without qubesdb dep, just just a few `#ifdef`s. Then, you can pull it in by connecting repository as a git submodule.

This reminds me of another issue: qubesdb is used to get AudioVM XID (which in Qubes 4.1 may be different from dom0). Right now I don't have any better idea than using qemu cmdline for that (see how `-qubes-net:..` is set and then extracted in the init script). That's unfortunate, as it will be static (no dynamic changes of audiovm), but should be fine for now.

> The way I see it, If low latency (ll) mode replaced with dynamically adjustable latency, then it would be not necessary to add new features. Please, tell me if you know that it can't be done.

Lack of `-l` option is actually a regression - we had it enabled by default previously. See QubesOS/qubes-issues#1036. It got lost when moving how `pacat-simple-vchan` is started.

> I'm working on a clean patchset in accordance to your suggestions. Would you prefer to receive PR in the personal repository?

Open it to @QubesOS repositories directly.

**Comment by easydozen** [comment]
> You can already control qemu cmdline with <emulator ... cmdline=, but I'd treat it as a last     resort and prefer proper libvirt device options.

Ok, so on this level of complexity user will choose only sound models. ac97, es1370, ich6 and ich9 worth a try. Actually soundhw options is deprecated in qemu. I think soon or late changes          corresponding to audiodev will be implemented in libvirt/libxl.

> This reminds me of another issue: qubesdb is used to get AudioVM XID (which in Qubes 4.1 may be  different from dom0). Right now I don't have any better idea than using qemu cmdline for that (see how -qubes-net:.. is set and then extracted in the init script). That's unfortunate, as it will be static (no dynamic changes of audiovm), but should be fine for now.

AudioVM XID could be passed as an argument to a vchan-sink module. I haven't tested that, but code is [there](https://github.com/QubesOS/qubes-gui-agent-linux/blob/ddd8a9b59e4d4bb45983ffb2a03aacc28d625df3/pulse/module-vchan-sink.c#L711).

**Comment by marmarek** [comment]
> AudioVM XID could be passed as an argument to a vchan-sink module. I haven't tested that, but code is [there](https://github.com/QubesOS/qubes-gui-agent-linux/blob/ddd8a9b59e4d4bb45983ffb2a03aacc28d625df3/pulse/module-vchan-sink.c#L711).

Yes, that should work. My concern is how to get it into the stubdomain.

**Comment by easydozen** [comment]
> Yes, that should work. My concern is how to get it into the stubdomain.

Got it. If you don't mind I'll look at audiovm xid a bit later. The current task is complex enough for me and I haven't seen sys-audio yet.

To go back to a question about daemon.conf modifications at host side - we could avoid it. I'm not sure that it's a silver bullet, but on my tests the following qemu tweak gives me a good sound     quality with es1370, ich6 and ich9 models:
_timer-period=1000,out.latency=10000,out.buffer-length=4000_

**Comment by easydozen** [comment]
I've closed dubious PR that fixes audio recording issue, but I presume the problem is still in pacat-simple-vchan.

module-vchan-sink reports about two state transitions: INIT->IDLE and IDLE->RUNNING.
pacat-simple-vchan don't process QUBES_PA_SOURCE_START_CMD because [a stream is not ready](https://github.com/QubesOS/qubes-gui-daemon/blob/v4.1.6/pulse/pacat-simple-vchan.c#L320-L328).

I propose a [patch](https://github.com/tabit-pro/Qway-qubes-repo/commit/4984ba9acecfd5c1ce388a8fecda0e035bf719d6) where vchan callbacks registered on PA_STREAM_READY. Would it be possible solution? Please, let me know if I missed something.

**Comment by marmarek** [comment]
Registering event handlers later should be fine. One issue with the patch - don't call `io_free(NULL)` (https://github.com/tabit-pro/Qway-qubes-repo/commit/4984ba9acecfd5c1ce388a8fecda0e035bf719d6#diff-f0385e7ec33936d7b6678f9c6289a26eR58 and few lines below).

**Comment by easydozen** [comment]
At the moment hvm audio tests may fail with "frequency not in range" error. It means that qemu audio tunables should be used. The most meaningful parameters are timer-period and out.buffer-length.

**Comment by easydozen** [comment]
@marmarek, do you think that something else should be done here? If you don't mind I'd like to make a similar effort on USB support.

**Comment by Polygonbugs** [comment]
Can you give help to make Windows USB support? I think it is related to #5802

**Comment by andrewdavidwong** [comment]
> Can you give help to make Windows USB support? I think it is related to #5802

Since qubes-issues isn't intended for help or support requests, you might want to ask on the [qubes-users mailing list or the forum](https://www.qubes-os.org/support/) instead. Thank you for your understanding.
