### ISSUE TITLE
[Arch Linux] qubes-mount-dir not starting start in R3.2 - chgrp on absolute symlinks

### ISSUE THREAD

**Issue by ptitdoc** [QubesOS/qubes-issues#2625]
#### Qubes OS version (e.g., `R3.2`):
R3.2
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):
potentially all templates

---

### Expected behavior:
Template boot properly with last qubes-agent

### Actual behavior:
Template boots but qubes-mount-dirs does not start. Because of that /home/ is empty and gui-agent fails

### Steps to reproduce the behavior:
Create an absolute symlink in the AppVM home pointing to a file in /home (or event an invalid symlink ?) and reboot

### General notes:
```
[root@mybrokenvm ~]# ls -l  /rw/home/user/testing/vmware-vmrc/vmware-vmrc-plugin/src/vmware-*
lrwxrwxrwx 1 user wheel 66  8 sept.  2014 /rw/home/user/testing/vmware-vmrc/vmware-vmrc-plugin/src/vmware-deviceMgr -> /home/user/testing/vmware-vmrc/vmware-vmrc-plugin/vmware-deviceMgr
lrwxrwxrwx 1 user wheel 61  8 sept.  2014 /rw/home/user/testing/vmware-vmrc/vmware-vmrc-plugin/src/vmware-vmrc -> /home/user/testing/vmware-vmrc/vmware-vmrc-plugin/vmware-vmrc
```

```
$ qvm-run mybrokenvm --pass-io 'sudo systemctl -la status qubes-mount-dirs'
su: avertissement: impossible de changer le rpertoire vers /home/user: Aucun fichier ou dossier de ce type
___ qubes-mount-dirs.service - Initialize and mount /rw and /home
   Loaded: loaded (/usr/lib/systemd/system/qubes-mount-dirs.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Fri 2017-02-10 10:32:02 CET; 14min ago
  Process: 308 ExecStart=/usr/lib/qubes/init/mount-dirs.sh (code=exited, status=123)
 Main PID: 308 (code=exited, status=123)

fvr. 10 10:32:01 localhost mount-dirs.sh[308]: chgrp: impossible de drfrencer '/rw/home/user/testing/vmware-vmrc/vmware-vmrc-plugin/pkg/vmware-vmrc-plugin/usr/lib/vmware-vmrc/5.1/bin/vmware-deviceMgr': Aucun fichier ou dossier de ce type
fvr. 10 10:32:01 localhost mount-dirs.sh[308]: chgrp: impossible de drfrencer '/rw/home/user/testing/vmware-vmrc/vmware-vmrc-plugin/pkg/vmware-vmrc-plugin/usr/lib/vmware-vmrc/5.1/bin/vmware-vmrc': Aucun fichier ou dossier de ce type
fvr. 10 10:32:01 localhost mount-dirs.sh[308]: chgrp: impossible de drfrencer '/rw/home/user/testing/vmware-vmrc/vmware-vmrc-plugin/pkg/vmware-vmrc-plugin/usr/lib64/mozilla/plugins/np-vmware-vmrc-5.1.0-781747.so': Aucun fichier ou dossier de ce type
fvr. 10 10:32:01 localhost mount-dirs.sh[308]: chgrp: impossible de drfrencer '/rw/home/user/testing/vmware-vmrc/vmware-vmrc-plugin/src/VMware-VMRC.x86_64.bundle': Aucun fichier ou dossier de ce type
fvr. 10 10:32:01 localhost mount-dirs.sh[308]: chgrp: impossible de drfrencer '/rw/home/user/testing/vmware-vmrc/vmware-vmrc-plugin/src/vmware-deviceMgr': Aucun fichier ou dossier de ce type
fvr. 10 10:32:01 localhost mount-dirs.sh[308]: chgrp: impossible de drfrencer '/rw/home/user/testing/vmware-vmrc/vmware-vmrc-plugin/src/vmware-vmrc': Aucun fichier ou dossier de ce type
f__vr. 10 10:32:02 localhost systemd[1]: qubes-mount-dirs.service: Main process exited, code=exited, status=123/n/a
f__vr. 10 10:32:02 localhost systemd[1]: Failed to start Initialize and mount /rw and /home.
f__vr. 10 10:32:02 localhost systemd[1]: qubes-mount-dirs.service: Unit entered failed state.
f__vr. 10 10:32:02 localhost systemd[1]: qubes-mount-dirs.service: Failed with result 'exit-code'.
```

---

#### Related issues:
https://github.com/QubesOS/qubes-issues/issues/2612
https://github.com/QubesOS/qubes-issues/issues/2609

**Comment by ptitdoc** [comment]
The error is chgrp: cannot unreference '/rw/home/user/testing/vmware-vmrc/vmware-vmrc-plugin/pkg/vmware-vmrc-plugin/usr/lib/vmware-vmrc/5.1/bin/vmware-deviceMgr': no file or folder found

**Comment by unman** [comment]
@ptitdoc What template are you using? Is it Arch?
This seems to work with both Debian and Fedora templates, and I cant reproduce the issue following your instructions.
Please amend title and set labels appropriately

**Comment by ptitdoc** [comment]
Yes this occured on archlinux, however I cleaned up the invalid links before testing with other templates.

Based on the error, I through that the problem would be the same on any linux template. I will check if I can reproduce it on other templates.

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
