### ISSUE TITLE
Fix Xen build for stretch

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#2631]
#### Qubes OS version (e.g., `R3.2`):

R3.2

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):

debian-9

---

Debian stretch build of vmm-xen component fails with:
```
 dpkg-genbuildinfo
Can't use an undefined value as an ARRAY reference at /usr/bin/dpkg-genbuildinfo line 212.
dpkg-buildpackage: error: dpkg-genbuildinfo gave error exit status 255
```

Follow up from: https://github.com/QubesOS/qubes-builder-debian/pull/7#issuecomment-279574024

/cc @unman

**Comment by marmarek** [comment]
It fails at getting info about `libc-dev` package (I guess to include it in buildinfo file). I have no idea from where it got that name, one checked right before is `libc6-dev`.

**Comment by marmarek** [comment]
Already reported upstream: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=849944

**Comment by h01ger** [comment]
#849944 was marked "pending" in the BTS yesterday, with a commit from February 6th 2017, so it shall be included in the next dpkg upload, which AIUI is still aimed at stretch.

**Comment by unman** [comment]
I cant say the commit message inspires confidence

**Comment by unman** [comment]
But it does work. Back in business.

**Comment by unman** [comment]
@marmarek This is fixed upstream and can be closed.
