### ISSUE TITLE
Unable to install template-fedora-23

### ISSUE THREAD

**Issue by Body4** [QubesOS/qubes-issues#2633]
#### Qubes OS version (e.g., `R3.2`):

R3.2 x86_64

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):

fedora-23 and debian-8

### Expected behavior:

On the first install of QubesOS, the template fedora must be correctly installed.

### Actual behavior:

After I installed QubesOS, I have this error while first configuration : 
https://i.imgur.com/iIshAIL.jpg

### Steps to reproduce the behavior:

I have just started a fresh installation of QubesOS.

### General notes:

When I try to install manually the template, I get this error : 

Error unpacking rpm package qubes-template-fedora-23.3.0.6-201608081228.noarch
error: unpacking of archive failed on file /var/lib/qubes/vm-templates/fedora-23/root.img.part.00;58a2f41c : cpio: read

I got the same error with the template debian 8. Just the template whonix is correctly installed.

I have just 2 partitions (swap and root) and there remains 200gb in the root partition.

**Comment by marmarek** [comment]
Looks like broken template package - have you verified installation image?

**Comment by Body4** [comment]
No, I didn't do it. So, I have tried to checking the signature with my current ISO but the check has failed. However, the sha256 sum was correct. I downloaded a new ISO of QubeOS and I checked the signature and the hashsum which are correct now.

Now, I think the part of installation of template was successful but my laptop is stucked on "Setting up networking" for a few minutes... Is that normal behavior?

**Comment by andrewdavidwong** [comment]
This is too localized for `qubes-issues`. Please consider posting this to the `qubes-users` mailing list instead. (You can read more about our mailing lists [here](https://www.qubes-os.org/mailing-lists/).)

`qubes-users` is intended for these sorts of questions and receives much more traffic, which means that your question is more likely to receive a response there.
