### ISSUE TITLE
Qubes onion-service-repos documentation fixes

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#2635]
* Please don't use variables such as $FedoraTemplateVM and $DebianTemplateVM. Users get that wrong. Example:
https://forums.whonix.org/t/few-issues-in-my-qubes-os-r3-2

I even had a case in real life where I failed to explain the concept of a variable. A PHD by that person in another area did not help either.

* Confirmation using `cat` or otherwise is great, but users don't know what to look for.
* Perhaps better to use specific examples?
* Perhaps better to not have the use `sed` but have them do it using editors?

**Comment by andrewdavidwong** [comment]
As I've written elsewhere, this was just quick-and-dirty, minmal, temporary documentation for people who know what they're doing. My reasoning was: Some minimal documentation is better than zero documentation, so I might as well throw something up. Evidently, it's causing more problems than it's solving, so I'm taking it down, which will resolve this issue.
