### ISSUE TITLE
Issue + workaround for intellij disappearing popups

### ISSUE THREAD

**Issue by randomlurker** [QubesOS/qubes-issues#2640]
#### Qubes OS version (e.g., `R3.2`):
R3.2
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):
standalone vm based on debian-8 and upgraded to stretch using qubes doc.

---

### Expected behavior:
Intellij popups (action selection, class search) should open correctly

### Actual behavior:
The popups open, but almost always close instantaneously

### Steps to reproduce the behavior:
- Download the community version of intellij. 
- Create a random project
- try to open the action dialog (ctrl-maj-a), or the class search (ctrl-maj-n)
- sometimes it works several times in a row at launch, but when you start messing with the ui / running a program, then it no longer works.

### Workaround specific to intellij
It's possible to tell intellij to create a different type of popup (that works fine) by using the java option suggested in this thread : 
https://youtrack.jetbrains.com/issue/IDEA-160215
This seems to solve all my problems for now.

### General notes:
I had almost given up when I found the workaround, and the only information I found was this old discussion that didn't seem to be resolved.
https://groups.google.com/forum/#!msg/qubes-users/6_fIA0wm7QU/DDm2s9i2CW0J

Maybe someone could add this in the doc ? A working IDE is a huge deal for devs, and this could easily put them off Qubes.

**Comment by andrewdavidwong** [comment]
> Maybe someone could add this in the doc ?

Would you mind submitting a pull request for this? The instructions are here: https://www.qubes-os.org/doc/doc-guidelines/

**Comment by unman** [comment]
@andrewdavidwong This doesn't seem to be a Qubes issue at all - that is, it manifests on Qubes but it is an upstream application issue: the solution isn't Qubes specific.
If you really want I can put something in the docs, but it does not seem appropriate to me.

**Comment by andrewdavidwong** [comment]
@unman: Thanks. Closing as `notourbug`.

**Comment by mgladdish** [comment]
Update: I had exactly the same issue on Qubes 4 and IntelliJ 2019.1

Seems the search box stuff has all been refactored which means the java option found by the OP is no longer enough on its own.

I needed:

```
-Dallow.dialog.based.popups=false
-Dnew.search.everywhere=false
```
