### ISSUE TITLE
kernel / kernel sources version inconsistencies

### ISSUE THREAD

**Issue by tzelch** [QubesOS/qubes-issues#2641]
#### Qubes OS version (e.g., `R3.2`):
R3.2
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):
fedora-24 / minimal
fedora-23 / minimal

---

### Actual behavior:
current official qubes kernel version is 4.4.38-11
the official kernel sources (package kernel-devel) are only at version 4.4.31-11
in order to use the kernel sources, a link needs to be created manually currently
### General notes:
After fiddling with this for a while i realized the modules for the kernel get mounted automatically in read-only.
Is there any process to add modules in a comfortable way?
Or do i have to do a work around?

---

**Comment by andrewdavidwong** [comment]
@marmarek, is this intentional (i.e., not a bug)?

**Comment by marmarek** [comment]
Generally the most elegant way to have custom modules is to use VM-provided kernel, see here: https://www.qubes-os.org/doc/managing-vm-kernel/#using-kernel-installed-in-the-vm

As for kernel-devel version not matching the kernel - yep, this is a bug, apparently updated kernel-devel was uploaded only to dom0 repository.
