### ISSUE TITLE
/lib/systemd/user/pulseaudio.service.d/30_qubes.conf ignored in Debian stretch

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#2644]
* `/lib/systemd/user/pulseaudio.service.d/30_qubes.conf`
* `/lib/systemd/user/pulseaudio.socket.d/30_qubes.conf`

These files are ignored at least in Debian stretch. Others untested.

As user `user`.
```
systemctl --user cat pulseaudio
```

```
# /usr/lib/systemd/user/pulseaudio.service
[Unit]
Description=Sound Service

[Service]
# Note that notify will only work if --daemonize=no
Type=notify
ExecStart=/usr/bin/pulseaudio --daemonize=no
Restart=on-failure

[Install]
Also=pulseaudio.socket
WantedBy=default.target
```

I don't know what these files are doing or if they are still required. Just randomly noticed, that its current implementation ignored on Debian stretch.

These probably would have to be moved to `/usr/lib/systemd/user/`.

**Comment by unman** [comment]
I don't know if it's just in stretch- I've found it ridiculously hard to stop pulseaudio from starting up, at least in Debian, even following all the advice I've found (autospawn=no, dynamically disabling using alsa, pasuspend etc.). It comes back like Jason.
I'd purge it if I could but it's a dependency of qubes-gui-agent - why is that?

**Comment by adrelanos** [comment]
@unman I speculate the systemd user session keeps starting it.

Perhaps try this. Run as user.

```
systemctl --user mask pulseaudio
```

Would speculate that suffices (if that was the cause). Otherwise you could also try the following, but I would wonder if these are required.

```
systemctl --user mask pulseaudio.service
systemctl --user mask pulseaudio.socket
```
