### ISSUE TITLE
pulseaudio and vlc should not be installed in sys-whonix

### ISSUE THREAD

**Issue by h01ger** [QubesOS/qubes-issues#2650]
#### Qubes OS version (e.g., `R3.2`):

R3.2

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):

whonix-gw

### Expected behavior:

pulseaudio and vlc should not be installed in sys-whonix.

### Actual behavior:

#2648 is the issue suggesting to split out a qubes-gui-agent-pulseaudio package out of qubes-gui-agent.

once this has been done the whonix-workstation package should depend on qubes-gui-agent-pulseaudio
and the whonix-gateway package should not (and then vlc and pulseaudio wouldnt be installed in sys-whonix.)

**Comment by andrewdavidwong** [comment]
@adrelanos: Does it make sense to track this here, or would prefer this sort of ticket on the Whonix tracker?

**Comment by h01ger** [comment]
On Sat, Feb 25, 2017 at 04:49:37PM -0800, Andrew David Wong wrote:
> @adrelanos: Does it make sense to track this here, or would prefer this sort of ticket on the Whonix tracker?

Patrick Schleizer explicitly asked for this ticket here…


-- 
cheers,
	Holger

**Comment by andrewdavidwong** [comment]
> Patrick Schleizer explicitly asked for this ticket here…

Oh, ok. I didn't know that.

**Comment by adrelanos** [comment]
Sorry, I was unclear on this.

Actually I prefer such tickets on phabricator.whonix.org.

Will open a ticket there.

**Comment by h01ger** [comment]
On Sun, Feb 26, 2017 at 09:18:03AM -0800, Patrick Schleizer wrote:
> Sorry, I was unclear on this. 
> Actually I prefer such tickets on phabricator.whonix.org.

ah, I totally missed this.

> Will open a ticket there.

Thanks. Please close this one then as well :)


-- 
cheers,
	Holger

**Comment by adrelanos** [comment]
Created https://phabricator.whonix.org/T641 for it.

I don't mind if we prefer to duplicate (some) Whonix related tickets here for wider publication and attracting contributions. https://github.com/QubesOS/qubes-issues/issues/1938 is an example for that where this might have been useful to have it here. Or just at phabricator.whonix.org to have fewer tickets here. Not a big deal for me to ask closing a ticket here once the phabricator.whonix.org ticket was closed.

This one specifically is rather easy and quickly implemented, I guess, once https://github.com/QubesOS/qubes-issues/issues/2648 is implemented.

**Comment by andrewdavidwong** [comment]
Agreed. We can just leave this one open until implemented, then.

**Comment by adrelanos** [comment]
Now tracked here and please have a look: https://phabricator.whonix.org/T786

**Comment by adrelanos** [comment]
This issue does no longer exist in recent versions of Whonix. Therefore, close please.
