### ISSUE TITLE
Debootstrapping wheezy fails (on jessie and stretch VMs)

### ISSUE THREAD

**Issue by h01ger** [QubesOS/qubes-issues#2655]
#### Qubes OS version (e.g., `R3.2`):

R3.2

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):

debian-8
debian-9

### Expected behavior:

Being able to debootstrap wheezy inside Debian templates.

### Actual behavior:

Bootstrapping wheezy fails, both in a jessie as well as a stretch template. This is the output on stretch:

<pre>
user@stretch:~$ sudo debootstrap wheezy ./wheezy http://deb.debian.org/debian/
I: Retrieving InRelease 
I: Retrieving Release 
I: Retrieving Release.gpg 
I: Checking Release signature
I: Valid Release signature (key id ED6D65271AACF0FF15D123036FB2A1C265FFB764)
I: Retrieving Packages 
I: Validating Packages 
I: Resolving dependencies of required packages...
I: Resolving dependencies of base packages...
I: Found additional required dependencies: insserv libbz2-1.0 libdb5.1 libsemanage-common libsemanage1 libslang2 libustr-1.0-1 
I: Found additional base dependencies: libept1.4.12 libgcrypt11 libgnutls26 libgpg-error0 libidn11 libnfnetlink0 libp11-kit0 libsqlite3-0 libtasn1-3 libxapian22 
I: Checking component main on http://deb.debian.org/debian...
I: Retrieving libacl1 2.2.51-8
I: Validating libacl1 2.2.51-8
I: Retrieving adduser 3.113+nmu3
I: Validating adduser 3.113+nmu3
I: Retrieving apt 0.9.7.9+deb7u7
I: Validating apt 0.9.7.9+deb7u7
I: Retrieving apt-utils 0.9.7.9+deb7u7
I: Validating apt-utils 0.9.7.9+deb7u7
I: Retrieving libapt-inst1.5 0.9.7.9+deb7u7
I: Validating libapt-inst1.5 0.9.7.9+deb7u7
I: Retrieving libapt-pkg4.12 0.9.7.9+deb7u7
I: Validating libapt-pkg4.12 0.9.7.9+deb7u7
I: Retrieving aptitude 0.6.8.2-1
I: Validating aptitude 0.6.8.2-1
I: Retrieving aptitude-common 0.6.8.2-1
I: Validating aptitude-common 0.6.8.2-1
I: Retrieving libattr1 1:2.4.46-8
I: Validating libattr1 1:2.4.46-8
I: Retrieving base-files 7.1wheezy11
I: Validating base-files 7.1wheezy11
I: Retrieving base-passwd 3.5.26
I: Validating base-passwd 3.5.26
I: Retrieving bash 4.2+dfsg-0.1+deb7u3
I: Validating bash 4.2+dfsg-0.1+deb7u3
I: Retrieving libboost-iostreams1.49.0 1.49.0-3.2
I: Validating libboost-iostreams1.49.0 1.49.0-3.2
I: Retrieving bsdmainutils 9.0.3
I: Validating bsdmainutils 9.0.3
I: Retrieving libbz2-1.0 1.0.6-4
I: Validating libbz2-1.0 1.0.6-4
I: Retrieving coreutils 8.13-3.5
I: Validating coreutils 8.13-3.5
I: Retrieving cpio 2.11+dfsg-0.1+deb7u2
I: Validating cpio 2.11+dfsg-0.1+deb7u2
I: Retrieving cron 3.0pl1-124
I: Validating cron 3.0pl1-124
I: Retrieving libcwidget3 0.5.16-3.4
I: Validating libcwidget3 0.5.16-3.4
I: Retrieving dash 0.5.7-3
I: Validating dash 0.5.7-3
I: Retrieving libdb5.1 5.1.29-5
I: Validating libdb5.1 5.1.29-5
I: Retrieving debconf 1.5.49
I: Validating debconf 1.5.49
I: Retrieving debconf-i18n 1.5.49
I: Validating debconf-i18n 1.5.49
I: Retrieving debian-archive-keyring 2014.3~deb7u1
I: Validating debian-archive-keyring 2014.3~deb7u1
I: Retrieving debianutils 4.3.2
I: Validating debianutils 4.3.2
I: Retrieving diffutils 1:3.2-6
I: Validating diffutils 1:3.2-6
I: Retrieving dmidecode 2.11-9
I: Validating dmidecode 2.11-9
I: Retrieving dpkg 1.16.18
I: Validating dpkg 1.16.18
I: Retrieving e2fslibs 1.42.5-1.1+deb7u1
I: Validating e2fslibs 1.42.5-1.1+deb7u1
I: Retrieving e2fsprogs 1.42.5-1.1+deb7u1
I: Validating e2fsprogs 1.42.5-1.1+deb7u1
I: Retrieving libcomerr2 1.42.5-1.1+deb7u1
I: Validating libcomerr2 1.42.5-1.1+deb7u1
I: Retrieving libss2 1.42.5-1.1+deb7u1
I: Validating libss2 1.42.5-1.1+deb7u1
I: Retrieving libc-bin 2.13-38+deb7u10
I: Validating libc-bin 2.13-38+deb7u10
I: Retrieving libc6 2.13-38+deb7u10
I: Validating libc6 2.13-38+deb7u10
I: Retrieving multiarch-support 2.13-38+deb7u10
I: Validating multiarch-support 2.13-38+deb7u10
I: Retrieving findutils 4.4.2-4
I: Validating findutils 4.4.2-4
I: Retrieving gcc-4.7-base 4.7.2-5
I: Validating gcc-4.7-base 4.7.2-5
I: Retrieving libgcc1 1:4.7.2-5
I: Validating libgcc1 1:4.7.2-5
I: Retrieving libstdc++6 4.7.2-5
I: Validating libstdc++6 4.7.2-5
I: Retrieving libgdbm3 1.8.3-11
I: Validating libgdbm3 1.8.3-11
I: Retrieving gnupg 1.4.12-7+deb7u7
I: Validating gnupg 1.4.12-7+deb7u7
I: Retrieving gpgv 1.4.12-7+deb7u7
I: Validating gpgv 1.4.12-7+deb7u7
I: Retrieving libgnutls26 2.12.20-8+deb7u5
I: Validating libgnutls26 2.12.20-8+deb7u5
I: Retrieving grep 2.12-2
I: Validating grep 2.12-2
I: Retrieving groff-base 1.21-9
I: Validating groff-base 1.21-9
I: Retrieving gzip 1.5-1.1
I: Validating gzip 1.5-1.1
I: Retrieving hostname 3.11
I: Validating hostname 3.11
I: Retrieving ifupdown 0.7.8
I: Validating ifupdown 0.7.8
I: Retrieving insserv 1.14.0-5
I: Validating insserv 1.14.0-5
I: Retrieving iproute 20120521-3+b3
I: Validating iproute 20120521-3+b3
I: Retrieving iptables 1.4.14-3.1
I: Validating iptables 1.4.14-3.1
I: Retrieving iputils-ping 3:20101006-1+b1
I: Validating iputils-ping 3:20101006-1+b1
I: Retrieving isc-dhcp-client 4.2.2.dfsg.1-5+deb70u8
I: Validating isc-dhcp-client 4.2.2.dfsg.1-5+deb70u8
I: Retrieving isc-dhcp-common 4.2.2.dfsg.1-5+deb70u8
I: Validating isc-dhcp-common 4.2.2.dfsg.1-5+deb70u8
I: Retrieving kmod 9-3
I: Validating kmod 9-3
I: Retrieving libkmod2 9-3
I: Validating libkmod2 9-3
I: Retrieving libept1.4.12 1.0.9
I: Validating libept1.4.12 1.0.9
I: Retrieving libgcrypt11 1.5.0-5+deb7u4
I: Validating libgcrypt11 1.5.0-5+deb7u4
I: Retrieving libgpg-error0 1.10-3.1
I: Validating libgpg-error0 1.10-3.1
I: Retrieving libidn11 1.25-2
I: Validating libidn11 1.25-2
I: Retrieving liblocale-gettext-perl 1.05-7+b1
I: Validating liblocale-gettext-perl 1.05-7+b1
I: Retrieving libnfnetlink0 1.0.0-1.1
I: Validating libnfnetlink0 1.0.0-1.1
I: Retrieving libpipeline1 1.2.1-1
I: Validating libpipeline1 1.2.1-1
I: Retrieving libselinux1 2.1.9-5
I: Validating libselinux1 2.1.9-5
I: Retrieving libsemanage-common 2.1.6-6
I: Validating libsemanage-common 2.1.6-6
I: Retrieving libsemanage1 2.1.6-6
I: Validating libsemanage1 2.1.6-6
I: Retrieving libsepol1 2.1.4-3
I: Validating libsepol1 2.1.4-3
I: Retrieving libsigc++-2.0-0c2a 2.2.10-0.2
I: Validating libsigc++-2.0-0c2a 2.2.10-0.2
I: Retrieving libtasn1-3 2.13-2+deb7u2
I: Validating libtasn1-3 2.13-2+deb7u2
I: Retrieving libtext-charwidth-perl 0.04-7+b1
I: Validating libtext-charwidth-perl 0.04-7+b1
I: Retrieving libtext-iconv-perl 1.7-5
I: Validating libtext-iconv-perl 1.7-5
I: Retrieving libtext-wrapi18n-perl 0.06-7
I: Validating libtext-wrapi18n-perl 0.06-7
I: Retrieving libusb-0.1-4 2:0.1.12-20+nmu1
I: Validating libusb-0.1-4 2:0.1.12-20+nmu1
I: Retrieving logrotate 3.8.1-4
I: Validating logrotate 3.8.1-4
I: Retrieving lsb-base 4.1+Debian8+deb7u1
I: Validating lsb-base 4.1+Debian8+deb7u1
I: Retrieving man-db 2.6.2-1
I: Validating man-db 2.6.2-1
I: Retrieving manpages 3.44-1
I: Validating manpages 3.44-1
I: Retrieving mawk 1.3.3-17
I: Validating mawk 1.3.3-17
I: Retrieving nano 2.2.6-1+b1
I: Validating nano 2.2.6-1+b1
I: Retrieving libncurses5 5.9-10
I: Validating libncurses5 5.9-10
I: Retrieving libncursesw5 5.9-10
I: Validating libncursesw5 5.9-10
I: Retrieving libtinfo5 5.9-10
I: Validating libtinfo5 5.9-10
I: Retrieving ncurses-base 5.9-10
I: Validating ncurses-base 5.9-10
I: Retrieving ncurses-bin 5.9-10
I: Validating ncurses-bin 5.9-10
I: Retrieving net-tools 1.60-24.2
I: Validating net-tools 1.60-24.2
I: Retrieving netbase 5.0
I: Validating netbase 5.0
I: Retrieving netcat-traditional 1.10-40
I: Validating netcat-traditional 1.10-40
I: Retrieving libnewt0.52 0.52.14-11.1
I: Validating libnewt0.52 0.52.14-11.1
I: Retrieving whiptail 0.52.14-11.1
I: Validating whiptail 0.52.14-11.1
I: Retrieving libssl1.0.0 1.0.1e-2+deb7u20
I: Validating libssl1.0.0 1.0.1e-2+deb7u20
I: Retrieving libp11-kit0 0.12-3
I: Validating libp11-kit0 0.12-3
I: Retrieving libpam-modules 1.1.3-7.1
I: Validating libpam-modules 1.1.3-7.1
I: Retrieving libpam-modules-bin 1.1.3-7.1
I: Validating libpam-modules-bin 1.1.3-7.1
I: Retrieving libpam-runtime 1.1.3-7.1
I: Validating libpam-runtime 1.1.3-7.1
I: Retrieving libpam0g 1.1.3-7.1
I: Validating libpam0g 1.1.3-7.1
I: Retrieving perl-base 5.14.2-21+deb7u3
I: Validating perl-base 5.14.2-21+deb7u3
I: Retrieving libpopt0 1.16-7
I: Validating libpopt0 1.16-7
I: Retrieving libprocps0 1:3.3.3-3
I: Validating libprocps0 1:3.3.3-3
I: Retrieving procps 1:3.3.3-3
I: Validating procps 1:3.3.3-3
I: Retrieving libreadline6 6.2+dfsg-0.1
I: Validating libreadline6 6.2+dfsg-0.1
I: Retrieving readline-common 6.2+dfsg-0.1
I: Validating readline-common 6.2+dfsg-0.1
I: Retrieving rsyslog 5.8.11-3+deb7u2
I: Validating rsyslog 5.8.11-3+deb7u2
I: Retrieving sed 4.2.1-10
I: Validating sed 4.2.1-10
I: Retrieving sensible-utils 0.0.7
I: Validating sensible-utils 0.0.7
I: Retrieving login 1:4.1.5.1-1
I: Validating login 1:4.1.5.1-1
I: Retrieving passwd 1:4.1.5.1-1
I: Validating passwd 1:4.1.5.1-1
I: Retrieving libslang2 2.2.4-15
I: Validating libslang2 2.2.4-15
I: Retrieving libsqlite3-0 3.7.13-1+deb7u2
I: Validating libsqlite3-0 3.7.13-1+deb7u2
I: Retrieving initscripts 2.88dsf-41+deb7u1
I: Validating initscripts 2.88dsf-41+deb7u1
I: Retrieving sysv-rc 2.88dsf-41+deb7u1
I: Validating sysv-rc 2.88dsf-41+deb7u1
I: Retrieving sysvinit 2.88dsf-41+deb7u1
I: Validating sysvinit 2.88dsf-41+deb7u1
I: Retrieving sysvinit-utils 2.88dsf-41+deb7u1
I: Validating sysvinit-utils 2.88dsf-41+deb7u1
I: Retrieving tar 1.26+dfsg-0.1
I: Validating tar 1.26+dfsg-0.1
I: Retrieving tasksel 3.14.1
I: Validating tasksel 3.14.1
I: Retrieving tasksel-data 3.14.1
I: Validating tasksel-data 3.14.1
I: Retrieving info 4.13a.dfsg.1-10
I: Validating info 4.13a.dfsg.1-10
I: Retrieving install-info 4.13a.dfsg.1-10
I: Validating install-info 4.13a.dfsg.1-10
I: Retrieving traceroute 1:2.0.18-3
I: Validating traceroute 1:2.0.18-3
I: Retrieving tzdata 2016d-0+deb7u1
I: Validating tzdata 2016d-0+deb7u1
I: Retrieving libudev0 175-7.2
I: Validating libudev0 175-7.2
I: Retrieving udev 175-7.2
I: Validating udev 175-7.2
I: Retrieving libustr-1.0-1 1.0.4-3
I: Validating libustr-1.0-1 1.0.4-3
I: Retrieving bsdutils 1:2.20.1-5.3
I: Validating bsdutils 1:2.20.1-5.3
I: Retrieving libblkid1 2.20.1-5.3
I: Validating libblkid1 2.20.1-5.3
I: Retrieving libmount1 2.20.1-5.3
I: Validating libmount1 2.20.1-5.3
I: Retrieving libuuid1 2.20.1-5.3
I: Validating libuuid1 2.20.1-5.3
I: Retrieving mount 2.20.1-5.3
I: Validating mount 2.20.1-5.3
I: Retrieving util-linux 2.20.1-5.3
I: Validating util-linux 2.20.1-5.3
I: Retrieving vim-common 2:7.3.547-7
I: Validating vim-common 2:7.3.547-7
I: Retrieving vim-tiny 2:7.3.547-7
I: Validating vim-tiny 2:7.3.547-7
I: Retrieving wget 1.13.4-3+deb7u2
I: Validating wget 1.13.4-3+deb7u2
I: Retrieving libxapian22 1.2.12-2+deb7u1
I: Validating libxapian22 1.2.12-2+deb7u1
I: Retrieving liblzma5 5.1.1alpha+20120614-2
I: Validating liblzma5 5.1.1alpha+20120614-2
I: Retrieving xz-utils 5.1.1alpha+20120614-2
I: Validating xz-utils 5.1.1alpha+20120614-2
I: Retrieving zlib1g 1:1.2.7.dfsg-13
I: Validating zlib1g 1:1.2.7.dfsg-13
I: Chosen extractor for .deb packages: dpkg-deb
I: Extracting libacl1...
I: Extracting libattr1...
I: Extracting base-files...
I: Extracting base-passwd...
I: Extracting bash...
I: Extracting libbz2-1.0...
I: Extracting coreutils...
I: Extracting dash...
I: Extracting libdb5.1...
I: Extracting debconf...
I: Extracting debconf-i18n...
I: Extracting debianutils...
I: Extracting diffutils...
I: Extracting dpkg...
I: Extracting e2fslibs...
I: Extracting e2fsprogs...
I: Extracting libcomerr2...
I: Extracting libss2...
I: Extracting libc-bin...
I: Extracting libc6...
I: Extracting multiarch-support...
I: Extracting findutils...
I: Extracting gcc-4.7-base...
I: Extracting libgcc1...
I: Extracting grep...
I: Extracting gzip...
I: Extracting hostname...
I: Extracting insserv...
I: Extracting liblocale-gettext-perl...
I: Extracting libselinux1...
I: Extracting libsemanage-common...
I: Extracting libsemanage1...
I: Extracting libsepol1...
I: Extracting libtext-charwidth-perl...
I: Extracting libtext-iconv-perl...
I: Extracting libtext-wrapi18n-perl...
I: Extracting lsb-base...
I: Extracting mawk...
I: Extracting libncurses5...
I: Extracting libtinfo5...
I: Extracting ncurses-base...
I: Extracting ncurses-bin...
I: Extracting libpam-modules...
I: Extracting libpam-modules-bin...
I: Extracting libpam-runtime...
I: Extracting libpam0g...
I: Extracting perl-base...
I: Extracting sed...
I: Extracting sensible-utils...
I: Extracting login...
I: Extracting passwd...
I: Extracting libslang2...
I: Extracting initscripts...
I: Extracting sysv-rc...
I: Extracting sysvinit...
I: Extracting sysvinit-utils...
I: Extracting tar...
I: Extracting tzdata...
I: Extracting libustr-1.0-1...
I: Extracting bsdutils...
I: Extracting libblkid1...
I: Extracting libmount1...
I: Extracting libuuid1...
I: Extracting mount...
I: Extracting util-linux...
I: Extracting liblzma5...
I: Extracting xz-utils...
I: Extracting zlib1g...
I: Installing core packages...
W: Failure trying to run: chroot /home/user/wheezy dpkg --force-depends --install /var/cache/apt/archives/base-passwd_3.5.26_amd64.deb
W: See /home/user/wheezy/debootstrap/debootstrap.log for details
user@stretch:~$ less /home/user/wheezy/debootstrap/debootstrap.log
user@stretch:~$ cat /home/user/wheezy/debootstrap/debootstrap.log
gpgv: Signature made Sat Jun  4 13:51:09 2016 CEST
gpgv:                using RSA key 8B48AD6246925553
gpgv: Good signature from "Debian Archive Automatic Signing Key (7.0/wheezy) <ftpmaster@debian.org>"
gpgv: Signature made Sat Jun  4 13:51:09 2016 CEST
gpgv:                using RSA key 7638D0442B90D010
gpgv: Good signature from "Debian Archive Automatic Signing Key (8/jessie) <ftpmaster@debian.org>"
gpgv: Signature made Sat Jun  4 13:56:53 2016 CEST
gpgv:                using RSA key 6FB2A1C265FFB764
gpgv: Good signature from "Wheezy Stable Release Key <debian-release@lists.debian.org>"
dpkg: warning: parsing file '/var/lib/dpkg/status' near line 5 package 'dpkg':
 missing description
dpkg: warning: parsing file '/var/lib/dpkg/status' near line 5 package 'dpkg':
 missing architecture
Segmentation fault
user@stretch:~$ 
</pre>

### Steps to reproduce the behavior:

See above.

### General notes:

I'll file a Debian bug about this issue as well and will reference it here.

**Comment by h01ger** [comment]
In Debian this is https://bugs.debian.org/856214 now…

**Comment by h01ger** [comment]
Happens when trying to bootstrap squeeze and lenny too.

**Comment by h01ger** [comment]
And for the avoidance of doubt, I've just tested bootstrapping jessie and stretch, which both worked fine.

**Comment by marmarek** [comment]
I think I've hit this in the past: https://github.com/QubesOS/qubes-issues/issues/2045#issuecomment-227289726
In short: add `vsyscall=emulate` to kernel cmdline.

**Comment by h01ger** [comment]
So this (#2045) means I need to reboot dom0 with some hardening features disabled?

**Comment by marmarek** [comment]
> So this (#2045) means I need to reboot dom0 with some hardening features disabled?

No, a VM in which you want to debootstrap old Debian versions.

**Comment by h01ger** [comment]
On Mon, Feb 27, 2017 at 10:05:34AM -0800, Marek Marczykowski-Górecki wrote:
> No, a VM in which you want to debootstrap old Debian versions.

ah, thanks! This made me check (and change) this setting with qvm-prefs,
previously I was only checking with the graphical qubes-manager…


-- 
cheers,
	Holger

**Comment by unman** [comment]
@h01ger Cab you confirm that this fixed the issue?

**Comment by h01ger** [comment]
On Wed, Mar 01, 2017 at 03:49:24PM -0800, unman wrote:
> @h01ger Cab you confirm that this fixed the issue?

yes, it did.


-- 
cheers,
	Holger

**Comment by h01ger** [comment]
So I'm wondering what to do with this issue - simple close it? I've also pondered writing a short paragraph for qubes-doc.git but couldnt quickly find where to best add it. Any suggestions?

**Comment by unman** [comment]
I would close it. It isn't a Qubes specific issue and the fix isn't particular to Qubes, so I wouldn't think it warrants an entry in the Qubes docs.
(Any one coming up against it again can always search issues and find this solution.)
