### ISSUE TITLE
fedora-24 skips updating flatpak due to broken dependencies

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#2656]
#### Qubes OS version (e.g., `R3.2`):

`R3.2`

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):

`fedora-24`

---

A completely vanilla (AFAIK) `fedora-24` template has detected an update for the `flatpak` package, but it skips this update due to broken dependencies:

```
[user@fedora-24 ~]$ sudo dnf upgrade
Last metadata expiration check: 0:01:09 ago on Wed Mar  1 02:26:07 2017.
Dependencies resolved.
================================================================================
 Package          Arch            Version                Repository        Size
================================================================================
Skipping packages with broken dependencies:
 flatpak          x86_64          0.8.3-3.fc24           updates          692 k

Transaction Summary
================================================================================
Skip  1 Package

Nothing to do.
Sending application list and icons to dom0
Complete!
```

`yum-deprecated` reveals that the broken dependency is `ostree-libs`:

```
Resolving Dependencies
--> Running transaction check
---> Package flatpak.x86_64 0:0.8.3-1.fc24 will be updated
---> Package flatpak.x86_64 0:0.8.3-3.fc24 will be an update
--> Processing Dependency: ostree-libs(x86-64) >= 2016.14 for package: flatpak-0
--> Finished Dependency Resolution
Error: Package: flatpak-0.8.3-3.fc24.x86_64 (updates)
           Requires: ostree-libs(x86-64) >= 2016.14
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
```

Is this somehow caused by Qubes? Should `ostree-libs` be installed?

**Comment by marmarek** [comment]
On Wed, Mar 01, 2017 at 02:37:23AM -0800, Andrew David Wong wrote:
> #### Qubes OS version (e.g., `R3.2`):
> 
> `R3.2`
> 
> #### Affected TemplateVMs (e.g., `fedora-23`, if applicable):
> 
> `fedora-24`
> 
> ---
> 
> A completely vanilla (AFAIK) `fedora-24` template has detected an update for the `flatpak` package, but it skips this update due to broken dependencies:
> 
> ```
> [user@fedora-24 ~]$ sudo dnf upgrade
> Last metadata expiration check: 0:01:09 ago on Wed Mar  1 02:26:07 2017.
> Dependencies resolved.
> ================================================================================
>  Package          Arch            Version                Repository        Size
> ================================================================================
> Skipping packages with broken dependencies:
>  flatpak          x86_64          0.8.3-3.fc24           updates          692 k
> 
> Transaction Summary
> ================================================================================
> Skip  1 Package
> 
> Nothing to do.
> Sending application list and icons to dom0
> Complete!
> ```
> 
> `yum-deprecated` reveals that the broken dependency is `ostree-libs`:
> 
> ```
> Resolving Dependencies
> --> Running transaction check
> ---> Package flatpak.x86_64 0:0.8.3-1.fc24 will be updated
> ---> Package flatpak.x86_64 0:0.8.3-3.fc24 will be an update
> --> Processing Dependency: ostree-libs(x86-64) >= 2016.14 for package: flatpak-0
> --> Finished Dependency Resolution
> Error: Package: flatpak-0.8.3-3.fc24.x86_64 (updates)
>            Requires: ostree-libs(x86-64) >= 2016.14
>  You could try using --skip-broken to work around the problem
>  You could try running: rpm -Va --nofiles --nodigest
> ```
> 
> Is this somehow caused by Qubes? Should `ostree-libs` be installed?
> 

Looks like upstream issue - there is no ostree-libs package in fedora
"updates" repository, it is only in updates-testing:
Package in "updates" (notice lack of ostree-libs): https://koji.fedoraproject.org/koji/buildinfo?buildID=826047
Package in "updates-testing": https://koji.fedoraproject.org/koji/buildinfo?buildID=861516

Package info page: https://admin.fedoraproject.org/pkgdb/package/rpms/ostree/

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by andrewdavidwong** [comment]
Ok, closing as `notourbug`.
