### ISSUE TITLE
Enable USBVM in installer by default and remove "experimental" label

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#2665]
[Branched from #2604]

Enabling the USBVM (aka "USB qube") by default breaks things like USB keyboards and booting from USB disks. In some cases, this is an intentional part of the Qubes security model. However, we know that some users can't conform to this security model due to hardware limitations (e.g., being forced to use a USB keyboard with a single USB controller). In those cases, we don't want the USBVM to be enabled, since it will make Qubes unusable. The installer detects some cases of this kind, but not all of them.

(It may be useful to have an explanatory tooltip (#2211) that explains the situation to the user.)

**Comment by emdete** [comment]
i like that idea as i struggled when i did not do so. still the installer should check if the chip can issue a reset as with that bug the sys-usb will hang. in case of that bug it should ask the user to set the property to be not as strict (behaviour as in Qubes 2 as i understood) to make the setup work. a warning should be shown to the user what the missing reset means for him and the alternatives described (usb in dom0 (bad) or usb entirely off (bad as well)).

**Comment by rootkovska** [comment]
I think we should have "Use USB qubes" enabled by default, and -- in case of those users who are ready to sacrifice security and want to use USB devices in Dom0 -- let users disable them.

We should definitely remove the "Experimental" label from this option in the installer.

We should also point out somewhere (in the installer?) that users who want to use USB-connected mouse can do so much more safely using Qubes-innovative qubes.InputMouse service, while still enjoying USB isolation. We also provide qubes.InputKeyboard, although not as safe to use as qubes.InputMouse, of course. Still better than not-having USB qube.

I think all this should be a no-brainer for the upcoming 4.0-rc1, but we should also consider doing that for any potential 3.2.1 ISO release if we every decide to have one.
