### ISSUE TITLE
Setting several AppVMs to start on boot causes only one random VM to autostart

### ISSUE THREAD

**Issue by Yethal** [QubesOS/qubes-issues#2666]
#### Qubes OS version (e.g., `R3.2`):
3.2
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):
fedora-24, possibly others
---

### Expected behavior:
All AppVMs set to autostart actually autostart.

### Actual behavior:
Network disconnected AppVM and one random network connected AppVM autostart correctly. The rest needs to be manually started.

### Steps to reproduce the behavior:
1. Create seven AppVMs (that's the number I use but is probably irrelevant)
2. Set all seven AppVMs to autostart on boot
3. Set one AppVM to be network disconnected
4. Reboot physical machine
5. Observe the state of all VMs in Qubes Manager

### General notes:
I can provide whichever logs are needed just tell me which ones.
---

#### Related issues:

**Comment by unman** [comment]
This isn't my experience. I regularly open 9 or 10 qubes on start-up without problems. Almost all of those are based on minimal (or mini) templates, but not all. I dont have huge amounts RAM, but a reasonable processor and SSD. Even on laptop with regularHD I could start 5 or 6
Can you provide some details on your box?
Also, does it make any difference if you set all the VMs with netvm none?
What about changing the template to a minimal template?

**Comment by Yethal** [comment]
I have 32GB of RAM and an nvme SSD so I doubt it's caused by my spec.
I've just checked this, all VMs autostart correctly after setting their NetVM to none.

**Comment by marmarek** [comment]
Does those network connected VMs use default NetVM? Default NetVM is specifically started before other VMs to avoid race condition you are experiencing.

**Comment by Yethal** [comment]
All VMs use the default sys-firewall VM. Although I just checked, under Global settings I had sys-net set as default NetVM and not sys-firewall which was probably the cause of this issue. This however leads me to a question, why is it even possible to set sys-net as default NetVM?

**Comment by marmarek** [comment]
Because it's also valid setting, in some cases.

**Comment by Yethal** [comment]
Fair enough. Is the race condition something that is goung to be worked on or can I close this one out?

**Comment by marmarek** [comment]
There are few very close to this one (#1075, #1990, #1665), but not exactly this one. So lets keep this open.

**Comment by unman** [comment]
@andrewdavidwong Confirmed this issue still arises in 3.2 milestone
