### ISSUE TITLE
"Lock already taken" when restoring backup VMs

### ISSUE THREAD

**Issue by pstansell** [QubesOS/qubes-issues#2672]
I thought I'd report this error because it seems current, even though
it looks similar to the closed report at https://github.com/QubesOS/qubes-issues/issues/986.

When trying to restore a Qubes backup I get the following errors:

```
  [Dom0] Houston, we have a problem

  This is mostly likely a bug in the Qubes Manager

  line: raise QubesException(lock already taken)
  func: lock_db_for_reading
  line no.: 615
  file: /usr/lib64/python2.7/site-packages/qubes/qubes.py
  ----
  line: self.qvm_collection.lock_db_for_reading()
  func: get_vms_list
  line no.: 619
  file: /usr/lib64/python2.7/site-packages/qubesmanager/main.py
  ----
  line: vms_list = self.get_vms_list()
  func: fill_table
  line no.: 654
  file: /usr/lib64/python2.7/site-packages/qubesmanager/main.py
  ----
  line: self.fill_table()
  func: update_table
  line no.: 752
  file: /usr/lib64/python2.7/site-packages/qubesmanager/main.py

  ERROR: [Errno 2] No such file or directory: '/var/tmp/restore_aiIR6p/dom0-home/ps'
  Partially restored files left in /var/tmp/restore_*, investigate them and/or clean them up

```

In more detail, what I did to get these errors is as follows:

1. I was trying to copy a Qubes installation from a source machine to
   another destination machine.

2. On the source machine, running Qubes-3.2, I backed up all the VMs
   to a USB drive.

3. On the destination machine I installed a fresh copy of Qubes from
   Qubes-R3.2-x86_64.iso.

4. I booted the destination machine, deleted all the AppVMs, and tried
   to restore the VMs from the backup of the source machine that's
   stored on a USB drive.

5. It was during the backup restoration process that I encountered the
   above errors.

**Comment by pstansell** [comment]
Just to update this bug report: I went through the process again (ie,
of trying to restore the backup from a source machine on a fresh
installation of Qubes-3.2 on a destination machine).  This time I
tried to recover just dom0 first.  That worked okay.  Then I rebooted
and successfully recovered a small fedora-23 based AppVM.  After that
I tried and failed to recover a 30 GB fedora-23 based AppVM.  At some
point through the long process I got the error:

  systemd quit unexpectedly
  systemd-journald killed by SIGABRT - abrt

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
