### ISSUE TITLE
playing DVDs does not work

### ISSUE THREAD

**Issue by emdete** [QubesOS/qubes-issues#2675]
#### Qubes OS version (e.g., `R3.2`):

3.2

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):

---

### Expected behavior:

vlc, mplayer or mpv can play DVDs

### Actual behavior:

the player fails with error message

libdvdread: Get key for /VIDEO_TS/VIDEO_TS.VOB at 0x00010f60
libdvdread: Error cracking CSS key for /VIDEO_TS/VIDEO_TS.VOB (0x00010f60)

even when libdvdcss is installed properly. same dvd can be played in a pure debian with similar setup (same versions of the libs)

### Steps to reproduce the behavior:

use a video-player to play DVDs with css

**Comment by andrewdavidwong** [comment]
Have you tried in a non-Debian-based VM?

**Comment by emdete** [comment]
haven't tesed as i did not find how to install dvdcss (i am not a fedora expert)...

**Comment by unman** [comment]
On Mon, Mar 06, 2017 at 01:00:29AM -0800, M. Dietrich wrote:
> #### Qubes OS version (e.g., `R3.2`):
> 
> 3.2
> 
> #### Affected TemplateVMs (e.g., `fedora-23`, if applicable):
> 
> ---
> 
> ### Expected behavior:
> 
> vlc, mplayer or mpv can play DVDs
> 
> ### Actual behavior:
> 
> the player fails with error message
> 
> libdvdread: Get key for /VIDEO_TS/VIDEO_TS.VOB at 0x00010f60
> libdvdread: Error cracking CSS key for /VIDEO_TS/VIDEO_TS.VOB (0x00010f60)
> 
> even when libdvdcss is installed properly. same dvd can be played in a pure debian with similar setup (same versions of the libs)
> 
> ### Steps to reproduce the behavior:
> 
> use a video-player to play DVDs with css
> 
> 

Classic "Works for me"
I've seen this with region mismatch errors - what hardware do you have?

**Comment by emdete** [comment]
the testing hardware is a t420s.

when it worked for you: are you sure you have tested with an css dvd (as far as i understand there are DVDs out there without)? did you have to install packages before it worked?

**Comment by andrewdavidwong** [comment]
I had to look this up. Apparently [Content Scramble System (CSS)](https://en.wikipedia.org/wiki/Content_Scramble_System) is an old, obsolete DRM scheme for DVDs. Looking back at your original report, I see that you wrote:

> the player fails with error message
> 
> libdvdread: Get key for /VIDEO_TS/VIDEO_TS.VOB at 0x00010f60
> libdvdread: Error cracking CSS key for /VIDEO_TS/VIDEO_TS.VOB (0x00010f60)

"Error cracking CSS key" sounds like you're trying to use some kind of software to circumvent the DRM scheme, which sounds like it's outside the scope of Qubes. Unless there's something Qubes-specific about this issue, I'm inclined to close it.

**Comment by emdete** [comment]
what do you mean with "you're trying to use some kind of software to circumvent the DRM scheme"? i am not really deep into the topic, only thing i know is that some DVDs use CSS and it works when i install the libdvdcss. same setup does not work in qubes.

so either there is a "new, not obsolete" way to watch such DVDs or my aproach is fine but somehow blocked by qubes. i tried fedora and was not able to watch the given dvd with the installed video player totem.

if you mean that just producing DVD with CSS is obsolete it does not matter as CSS DVDs are still existing and can be played in other systems.

your article says "if the drive detects a disc that has been compiled with CSS, it denies access", and "The player has to execute an authentication handshake" and that operation is not supported by qubes?

**Comment by unman** [comment]
@emdete This isn't a Qubes issue -on the mailing lists are people using DVDs without problem.
A simple search shows other (non-Qubes) users having the same issue - almost invariably solved by setting region correctly, as I suggested. If you try that, (and other solutions proposed online), and nothing works for you, I suggest you ask on the qubes-users mailing list.
In answer to your question. I haven't *tested* this. I use DVDs on Debian - I dont use Fedora qubes - and all are fine. I did standard install vlc and used libdvdcss from the vlc site. Incidentally, I didn't know that CSS is "an old, obsolete DRM scheme" - learn something new every day.

@andrewdavidwong Suggest you close this.

**Comment by andrewdavidwong** [comment]
> what do you mean with "you're trying to use some kind of software to circumvent the DRM scheme"?

I said that the text you provided *sounds like* that's what you're trying to do. CSS is a type of DRM. Cracking a CSS key sounds like a way to circumvent that form of DRM.

> so either there is a "new, not obsolete" way to watch such DVDs

The "old, obsolete" comment is not about the "way to watch." It's about CSS as a DRM scheme.

> if you mean that just producing DVD with CSS is obsolete it does not matter as CSS DVDs are still existing and can be played in other systems.

The "obsolete" comment is not about production. It's about CSS as a DRM scheme. It only matters insofar as you care about that fact (if it is a fact).

> Incidentally, I didn't know that CSS is "an old, obsolete DRM scheme" - learn something new every day.

I said that it *apparently* is after briefly skimming the Wikipedia page.
