### ISSUE TITLE
No dom0 update notification even when updates are available

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#2677]
#### Qubes OS version (e.g., `R3.2`):

`R3.2`

---

This is the opposite of #2086 (which is now fixed for me). No dom0 update notification appears in Qubes Manager even after manually running `sudo qubes-dom0-update --clean --check-only` and seeing that updates are indeed available.

This is arguably much worse than #2086, since users could miss important security updates this way.

**Comment by marmarek** [comment]
Cannot reproduce. Check if you have (empty) file `/var/lib/qubes/updates/dom0-updates-available` and what owner/mode.

**Comment by andrewdavidwong** [comment]
> Cannot reproduce.

Strange. I could reproduce it on two different Qubes machines.

> Check if you have (empty) file /var/lib/qubes/updates/dom0-updates-available and what owner/mode.

I have no such file (but also no available updates right now, FWIW).

**Comment by marmarek** [comment]
What about directory, especially it's mode? Should be owned by group `qubes` and group writable.

**Comment by andrewdavidwong** [comment]
> What about directory, especially it's mode? Should be owned by group qubes and group writable.

```
drwxrwx---  4 root qubes [...] updates/
```

**Comment by marmarek** [comment]
That notification flag is not created by `qubes-dom0-update` itself, but by a cron job started once a day (`/etc/cron.daily/qubes-dom0-updates.cron`). And it can be disabled in Qubes Manager in global settings.

**Comment by andrewdavidwong** [comment]
I have it enabled in QM's global settings. Perhaps the cron job hadn't had a chance to run yet. I'll close this for now.
