### ISSUE TITLE
Please support usb-ether in sys-net

### ISSUE THREAD

**Issue by emdete** [QubesOS/qubes-issues#2680]
#### Qubes OS version (e.g., `R3.2`):

3.2

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):

sys-usb

### Expected behavior:

usb ether can be used as a network device from sys-net

### Actual behavior:

usb ether is grabbed by sys-usb and can't be exported

### Steps to reproduce the behavior:

attach a usb-ether device (for example usb tethering with a mobile capable of usb-ether)

### General notes:

this is probably a feature request.

tethering via cable is good to increase security compared to a wlan for tethering.

**Comment by marmarek** [comment]
sys-usb is specifically created as NetVM to allow this scenario. If you want to use it, go to sys-usb settings, services tab, enable `network-manager` service and restart sys-usb. Then you will be able to switch any VM to use sys-usb instead of sys-firewall. If you want to route all of them, simply switch sys-firewall to use sys-usb as its netvm.

Alternatively qvm-usb could be used to connect such device to sys-net, but as you noted, many devices do not work in this mode.

**Comment by emdete** [comment]
this is not a desirable solution ;) 

if you change networks from cable ether, wifi, usb, bt it's not a solution to change your current net vm each time you change your connection to the internet. you just want that network devices show up in one single net vm. automatically. no click needed.

**Comment by grey-olli** [comment]
On Tue, Mar 7, 2017 at 11:48 AM, M. Dietrich <notifications@github.com>
wrote:

> this is not a desirable solution ;)
>
> if you change networks from cable ether, wifi, usb, bt it's not a solution
> to change your current net vm each time you change your connection to the
> internet. you just want that network devices show up in one single net vm.
> automatically. no click needed.
>
Qubes is about security at 1st. USB devices could attack the qube assigned
as usb one. It is user decision to move USB network device or a USB
controller to the net-vm.
If the user has set USB VM not the same as the net VM at install time - all
Qubes OS should do with this - notice user that her USB device will not
function by default.

My 5 cent -  this bug should be closed as won't FIX - already supported.

-- 
Bye.Olli.
gpg --search-keys grey_olli , use key w/ fingerprint below:
Key fingerprint = 9901 6808 768C 8B89 544C  9BE0 49F9 5A46 2B98 147E
Blog keys (the blog is mostly in Russian):
http://grey-olli.livejournal.com/tag/

**Comment by unman** [comment]
Marek gave an alternative solution - if that doesn't work, you could attach the usb controller you use for usb ether to sys-net, and use udev to restrict use to the ethernet device. Of course, this wont work if you only have 1 controller.

**Comment by andrewdavidwong** [comment]
> My 5 cent -  this bug should be closed as won't FIX - already supported.

It has already been closed as `notanissue`.

**Comment by emdete** [comment]
it seems i have a different view on security and usability than qubes people have... no problem with that.
