### ISSUE TITLE
Cannot execute qrexec-daemon!

### ISSUE THREAD

**Issue by typhonn** [QubesOS/qubes-issues#2682]
#### Affected TemplateVMs debian-8

I remove the fedora template and install the debian template and whonix. My sys-net and sys-firewall use the debian template. After removing ImageMagick in my debian-vm it crashed and doesn't restart anymore. It show me the message "cannot execute qrexec-daemon!".
Now i cann't reinstall the debian template because i cannot start sys-net and sys-firewall.
I can access the console with "xl console debian-8" but without internet access.
Maybe someone can help? :)

**Comment by marmarek** [comment]
Are you sure you've removed only ImageMagick? I guess you removed a bunch of other packages depending on it, including qrexec.

Anyway this looks like a question for qubes-users mailing list. Checking a list archive also would be a good idea: https://groups.google.com/d/topic/qubes-users/PF6iDxYxiMA/discussion

**Comment by typhonn** [comment]
Thanks :)
