### ISSUE TITLE
secpack: use Bitcoin block hash in freshness proof for canaries

### ISSUE THREAD

**Issue by rootkovska** [QubesOS/qubes-issues#2685]
@petertodd suggested we should include Bitcoin block hash as part of the proof-of-freshness for canaries. Advantages:
1. Simple
2. Doesn't trust external organizations
3. Last but not least: doesn't require *working* rss feeds to be verified

We only need to be careful to include a hash of a block which gets enough confirmations to be considered part of the main chain.

Anyone willing to submit a PR for [the freshness generator](https://github.com/QubesOS/qubes-secpack/blob/master/utils/proof_of_freshness_generator.sh)? @petertodd? :)

**Comment by petertodd** [comment]
Ha, I'll get right to that!

**Comment by marmarek** [comment]
Implemented (see PR above)
