### ISSUE TITLE
Update qubes-kernel-vm-support package to include latest u2mfn.c for kernel 4.9 compatability

### ISSUE THREAD

**Issue by rtiangha** [QubesOS/qubes-issues#2691]
#### Qubes OS version (e.g., `R3.2`):
R3.2 (maybe others?)

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):
All current fedora and debian templates.

---

### Expected behavior:

The qubes-kernel-vm-support package should have the latest u2mfn files so that compiling any kernel based on version 4.9 (ex. like the current version of [coldkernel](https://github.com/coldhakca/coldkernel)) will work.

### Actual behavior:

Compilation currently fails due to wrong function definition because the u2mfn.c currently included in qubes-kernel-vm-support is outdated and not compatible with kernel 4.9.

### Steps to reproduce the behavior:

Install qubes-kernel-vm-support in a template and attempt to compile a kernel based on 4.9 (ex. coldkernel) in any Fedora or Debian template; it will fail.

### General notes:

The version of u2mfn.c that is currently included in the qubes-kernel-vm-support package is out-of-date and incompatible with Linux kernels based on 4.9 which means compiling 4.9 kernels like the current version of coldkernel fails. The version in the QubesOS GitHub was [updated back in October 2016](https://github.com/QubesOS/qubes-linux-utils/blob/master/kernel-modules/u2mfn/u2mfn.c) to be compatible with kernels based on 4.9. If one manually copies that file from the repository to /usr/src/u2mfn-3.2.3/ then the kernel successfully compiles and runs with no issues. One has to do this for every template one wishes to compile or install the kernel in (so that dkms can recompile the u2mfn module), which becomes tedious if there are a lot of templates to update. It would be more convenient for users if the qubes-kernel-vm-support package had the latest version of the file included instead since there's already a fix included in the version that's hosted on GitHub.

---

#### Related issues:
https://github.com/coldhakca/coldkernel/issues/55
https://github.com/coldhakca/coldkernel/issues/54

**Comment by kamalmarhubi** [comment]
Is there something relatively straightforward needed to make this work?

**Comment by marmarek** [comment]
Uploaded to testing: https://github.com/QubesOS/updates-status/issues/17
