### ISSUE TITLE
Consider implementing GUI for DisposableVM Applications Menu customization

### ISSUE THREAD

**Issue by Yethal** [QubesOS/qubes-issues#2694]
Currently, in order to add an arbitrary program to the Applications menu of a Disposable VM the user has to create a .desktop file in /usr/local/share/applications and then manually add it to the /etc/xdg/menus/applications-merged/qubes-dispvm.menu file.
Please consider implementing a GUI for DisposableVM Application Menu customization to simplify the process of launching arbitrary programs within DisposableVMs.

**Comment by desci** [comment]
Or at list documenting that it was on `/etc/xdg/menus`. Now I know how to create a menu entry for Tor Browser and arm for a Whonix DispVM without having to edit the xterm entry.

**Comment by Yethal** [comment]
It is documented. I added it myself to the DisposableVM customization doc.

2017-04-17 19:22 GMT+02:00 Desobediente Civil <notifications@github.com>:
