### ISSUE TITLE
Fatal error while loading kernel modules

### ISSUE THREAD

**Issue by programmer444** [QubesOS/qubes-issues#2696]
OS Version R3.2

Hello!

I have a big problem with my qubes OS.
When i Start booting and successfully decrypt the disk it brings me to an fatal error.

When i type: journalctl _PID=222
It tells me:

dom0 systemd-modes-load[222]: 

Failed to find module 'uinput'
Module 'xen_evtchn' is buildin, Mord buildins are following
Failed to find module 'xen-blkback'
Failed to find module 'xen-acpi-processor'

Can someone help me?
I have important files in my work vm which i need fast.
Or is there any other way how i can geht the files in this vm?

Thanks
programmer445

**Comment by andrewdavidwong** [comment]
This is not appropriate for `qubes-issues`. Please send this to the `qubes-users` [mailing list](https://www.qubes-os.org/mailing-lists/) instead.
