### ISSUE TITLE
Missing texts and icons after sleep mode

### ISSUE THREAD

**Issue by mikeSaidHi** [QubesOS/qubes-issues#2700]
#### Qubes OS version (e.g., `R3.2`):

R3.2

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):

dom0 (xfce)
---

### Actual behavior:

![screenshot_2017-03-13_11-47-39](https://cloud.githubusercontent.com/assets/24559297/23842188/151271d2-07e5-11e7-8323-d0723870f2ae.png)

### Steps to reproduce the behavior:

Put it to sleep mode (by closing the laptop) then turn it on..

### General notes:

I'm using Dell Precision M4700.

**Comment by jpouellet** [comment]
Woah. Can you reliably reproduce this?

**Comment by marmarek** [comment]
I've seen very similar thing on non-Qubes machine: XUbuntu 14.04 (or 16.04? don't remember), also on Xfce. When it happened, nothing helped (reboot, removing `.cache` etc). Installing updates fixed it there. It may be something totally different here, as we didn't changed anything recently, and also fc23 do not receive updates anymore.

**Comment by mikeSaidHi** [comment]
@jpouellet @marmarek I updated dom0, and things back to normal. Thanks.

Is it xfce's issue? Btw I'm also experiencing network-manager issue with WPA2-Enterprise (my university to be specific)..

**Comment by osh2ep** [comment]
@mikeSaidHi Same here, nm-applet can't connect to WPA2 enterprise network :iknowhowyoufeelbro:

Below are fields I used but:

```
Security : WPA & WPA2 Enterprise
Authentication : Protected EAP (PEAP)
CA certificate is not needed
PEAP version : Automatic
Inner authentication : MSCHAPv2
Username and Password are correct.

```
Or to be specific

```
[ipv6]
method=auto

[connection]
id=SSID #(e.g.EDUroam)
uuid=9e123fbc-0123-46e3-97b5-f3214e123456 #unique uuid will be created upon creation of this profile
type=802-11-wireless

[802-11-wireless-security]
key-mgmt=wpa-eap
auth-alg=open

[802-11-wireless]
ssid=SSID
mode=infrastructure
mac-address=0A:12:3C:DA:C1:A5
security=802-11-wireless-security

[802-1x]
eap=peap; # this semi-colon might be the reason why it didn't work, but it was there by default
identity=studentid123123
phase2-auth=mschapv2
password=mypass123123

[ipv4]
method=auto

```
References:

[1](http://askubuntu.com/questions/279762/how-to-connect-to-wpa2-peap-mschapv2-enterprise-wifi-networks-that-dont-use-a-c)
[2](https://bugs.launchpad.net/linuxmint/+bug/1418777)

Both didn't work for me... But when I changed to GNOME, it just worked.

**Comment by jpouellet** [comment]
NetworkManager questions belong on qubes-users, not this issue. That said, "CA certificate is not needed" is a terrible option and should not be set, as it allows any rogue AP to steal your university network access credentials and impersonate you (potentially leading to personal liability).

You should really go through the trouble of fetching & verifying the cert chain for your institution.

**Comment by jpouellet** [comment]
Also mschapv2 is weak (read: broken) and you should prefer nearly other authentication mechanism if your institution supports any.

**Comment by andrewdavidwong** [comment]
> I updated dom0, and things back to normal. Thanks.

Glad to hear it. :smiley:
