### ISSUE TITLE
VMs based on Fedora template hang for a long time

### ISSUE THREAD

**Issue by Rudd-O** [QubesOS/qubes-issues#2709]
Qubes OS version `R3.2`

Affected TemplateVMs: at least fedora-24

Console shows hanging at A stop job is running for Session c1 of user user (...1min 30s...)

It does not happen all the time — most of the time this step takes 5  to 10 seconds tops — but when it does, it waits the full 90 seconds, consuming 100% CPU.

One thing that makes this more likely to be reproduced is to run qvm-start -a [VM] vlc (with VLC from rpmfusion installed in the VM) in order to start the VM, then qvm-shutdown [VM] in another terminal.

Pointers to help me break into the VM as it is shutting down will be most welcome.  That way I can provide more debugging info.  systemd in debug mode sadly doesn't provide much more information that is valuable in the console while shutting down — it would be nice if it showed which processes exactly it is trying to kill.  Would be even nicer if I could run a top (as root, obviously) on another HVC during shutdown, without it getting killed.

**Comment by Rudd-O** [comment]
One thing that is obvious to me, is that right after "A stop job is running" finishes (whether in 10 seconds or 90 seconds), the kernel message `[   time ] u2mfn_release, priv=        (null)` appears on the same line (as the kernel prints it out, and the cursor is right to the "A stop job" text).  Always.

**Comment by marmarek** [comment]
`u2mfn_release` happens when gui-agent is terminated. Also, take a look here: https://freedesktop.org/wiki/Software/systemd/Debugging/#index2h1

**Comment by Rudd-O** [comment]
I tried that. None of it worked — I can't break into the system as it shuts down using `xl console`.  Hence my request for help.

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
