### ISSUE TITLE
Can't find pvgrub2 after setting up new kernel image (Debian-9 VM)

### ISSUE THREAD

**Issue by freeasinbear** [QubesOS/qubes-issues#2713]
version: 3.2

Affected VMs: Debian-9

Expected behavior: being able to switch kernel image in the Qubes Manager's VM options to "pvgrub2" as described here: https://www.qubes-os.org/doc/managing-vm-kernel/#installing-kernel-in-debian-vm

Actual behavior: Nothing

Steps to reproduce the behavior: https://www.qubes-os.org/doc/managing-vm-kernel/#installing-kernel-in-debian-vm

General notes: I correctly modified the file u2mfn.c with the new text, as described here: https://www.qubes-os.org/doc/managing-vm-kernel/#installing-kernel-in-debian-vm, and the process went alright, without errors (except for "grub2-probe: error: cannot find a GRUB drive for /dev/mapper/dmroot. Check your device.map", but as explained in the guide, it's nothing to worry about)

---

**Comment by marmarek** [comment]
Have you installed grub2-xen package in dom0?

**Comment by freeasinbear** [comment]
Nope, just did and it works. It was mentioned before the point from which I started following the guide, so I missed it. Thanks!
