### ISSUE TITLE
issues with graphic tablet

### ISSUE THREAD

**Issue by space-potato** [QubesOS/qubes-issues#2715]
Qubes version: 3.2

Affected VMs: dom0, fedora and debian

Expected behavior: Graphic tablet to work after being connected to dom0 or when passed to another VM via qvm-usb 

Actual behavior: The tablet gets recognized and tthe light blinks when writing (like it's recognizing that the tablet is sending input), but the mouse won't move. This happens both if I install the device in dom0 or in any other Template/StandaloneVM

(I add that reboots have been tried for both operations, without success)
On dom0/fedora: 
- install kernel-devel;
- Install the digimend drivers from source (https://github.com/DIGImend/digimend-kernel-drivers);
- Connect the device

On Debian: 
- install latest kernel image (4.9.0-2) with headers and activate it as described here (https://www.qubes-os.org/doc/managing-vm-kernel/#installing-kernel-in-debian-vm); 
- Install digimend drivers from source; 
- Connect the device and pass it to the debian VM with qvm-usb -a

General notes: Everything was working fine in my previous Debian distro (not with qubes), so we are sure there is nothing wrong with the drivers, the kernel image nor my tablet. I also tried giving the tablet mouse input from dom0 as described here (https://www.qubes-os.org/doc/usb/#how-to-use-a-usb-mouse), but it doesn't work.

Maybe this is not a bug, but only an undocumented issue. I hope we can find a solution for other people in my same situation that for now have to rely on less secure distros to use devices like that.

**Comment by marmarek** [comment]
This is a tricky thing. Short answer: probably not implemented feature.

There are few possible ways to approach this:
1. Assign the whole device directly to the target VM, for example using qvm-usb or assigning the whole USB controller. This in theory should work, but in practice there will be few problems:
   - mouse cursor (drawn by dom0) will not follow tablet actions, which may be confusing
   - there may be some weird interactions between table actions and mouse actions - for example clicking not where mouse is visible, but where it's moved by tablet

2. Connecting the device to dom0 (having USB controller in dom0), or using input-proxy to pass it there. This is probably better approach, especially the second option, but it's currently not implemented:
   - input-proxy do not support tablet devices - this in theory should be easy (a matter adding proper metadata - min/max - to the [protocol handshake](https://github.com/QubesOS/qubes-app-linux-input-proxy/blob/master/src/protocol.h#L17-L28), and filtering events based on this info)
    - gui virtualization do not support advanced input data, like pressure force, angle etc; this means even if dom0 will know this data, VM will not be able to use it

From your report, I understand that the first method does not work at all for you, right?

**Comment by freeasinbear** [comment]
Yeah right, and neither with the second method, by connecting the device directly to dom0, that gives me the same result (led turning on while writing something, but no output/mouse movement), which is probably related to:

> - gui virtualization do not support advanced input data, like pressure force, angle etc; this means even if dom0 will know this data, VM will not be able to use it

**Comment by evadogstar** [comment]
When I was on Qubes without `sys-usb` Wacom works for me (only cursor movement and clicks). Hope this functions will be available at input proxy. It's good point to start from (without pressure, angel etc for start is ok and easy to add).

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 has reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.

**Comment by dzwdz** [comment]
> gui virtualization do not support advanced input data, like pressure force, angle etc; this means even if dom0 will know this data, VM will not be able to use it
This is still an issue, pen pressure doesn't work in VMs - I think that this issue should be reopened.

**Comment by DemiMarie** [comment]
> > gui virtualization do not support advanced input data, like pressure force, angle etc; this means even if dom0 will know this data, VM will not be able to use it
> 
> This is still an issue, pen pressure doesn't work in VMs - I think that this issue should be reopened.

This will require changes to the GUI protocol.  It will also likely require a different implementation for an X11-based GUI daemon than it will for a Wayland-based one, and since Wayland is the future I am not sure if implementing this for X11 is worthwhile.  There are also privacy concerns.  @marmarek thoughts?

**Comment by marmarek** [comment]
I'd rather avoid extending the GUI protocol with this kind of feature, with protocol complexity and privacy among the reasons. But using input proxy to connect tablet to a single selected qube should be doable, and theoretically it should support pen pressure etc. Try "manual usage" section from https://github.com/QubesOS/qubes-app-linux-input-proxy#readme

**Comment by DemiMarie** [comment]
Agreed.  My understanding is that tablets are usually USB devices, so exposing them to dom0 or the GUI qube is a bad idea anyway.

**Comment by dzwdz** [comment]
> But using input proxy to connect tablet to a single selected qube should be doable, and theoretically it should support pen pressure etc. Try "manual usage" section from https://github.com/QubesOS/qubes-app-linux-input-proxy#readme

I've just tried this. For reference, the tablet is exposed to dom0 (I don't have a USB qube), and the command I'm using is `qvm-run -u root --pass-io --localcmd="sudo input-proxy-sender /dev/input/event11" krita_vm "input-proxy-receiver --tablet"`. The pen pressure works, but:
* as expected, there's no mouse cursor - Krita draws its own cursor when you're hovering over the canvas, but it's an issue everywhere else.
* xsetwacom doesn't seem to work - it doesn't see any devices in the VM running `input-proxy-receiver`. It sees them fine in dom0, but commands such as MapToOutput don't do anything. It works fine when I kill the input proxy.
