### ISSUE TITLE
[Request] Template: From KeePassX to KeePassXC

### ISSUE THREAD

**Issue by noraj1337** [QubesOS/qubes-issues#2717]
Qubes OS Fedora template ([Administration](https://www.qubes-os.org/doc/fedora-minimal-template-customization/#administration-undocumented)) seems to use `KeePassX` as password manager.

But `KeePassX` development seems to be stoped sinc KeePassX 2.0.2 release (2016-02-02). See website [changelog](https://www.keepassx.org/changelog) or [PR](https://github.com/keepassx/keepassx/pulls).

Hopefully `KeePassXC` takes over. See [website](https://keepassxc.org/project) or [Github](https://github.com/keepassxreboot/keepassxc).

They added some new features : 

> Auto-Type on all three major platforms (Linux, Windows, OS X)
> Stand-alone password generator
> Password strength meter
> YubiKey HMAC-SHA1 authentication for unlocking databases
> Using website favicons as entry icons
> Merging of databases
> Automatic reload when the database was changed externally
> KeePassHTTP support for use with PassIFox in Mozilla Firefox and chromeIPass in Google Chrome and Chromium.
> Many bug fixes
>  For a full list of new features and changes, have a look at the [full KeePassXC changelog](https://github.com/keepassxreboot/keepassxc/wiki/KeePassXC-Changelog).

They also plan to add [support for KDBX4 file format](https://github.com/keepassxreboot/keepassxc/issues/148).

I think it's a good perspective to switch from KeePassX to KeePassXC in the next major QubesOS release.

**Comment by noraj1337** [comment]
> [Why KeePassXC instead of KeePassX?](https://keepassxc.org/docs#faq-keepassx)

**Comment by andrewdavidwong** [comment]
We don't make these kinds of package selection decisions within TemplateVM distros:

https://www.qubes-os.org/doc/devel-faq/#what-is-qubes-attitude-toward-changing-guest-distros

Please feel free to send your request upstream to Fedora.

**Comment by andrewdavidwong** [comment]
(Also, please note that you're always free to replace KeePassX with KeePassXC in all of your own templates.)

**Comment by noraj1337** [comment]
@andrewdavidwong : I opened an issue on fedora bug tracker: https://bugzilla.redhat.com/show_bug.cgi?id=1433765

**Comment by mfc** [comment]
FYI your Fedora request seems to have transitioned from a request to change the default password manager in Fedora to packaging keepassxc in Fedora, which is done. so the first part is still needed -- convincing Fedora to change their default password manager. Not sure how that happens honestly, but I hope it happens.
