### ISSUE TITLE
qvm-prefs claims to be able to modify dom0

### ISSUE THREAD

**Issue by kulinacs** [QubesOS/qubes-issues#2722]
#### Qubes OS version (e.g., `R3.2`):
R3.2 

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):
dom0

---

### Expected behavior:
qvm-prefs should not list dom0, or allow it to be edited

### Actual behavior:
qvm-prefs does list dom0 and allow it to be edited

### Steps to reproduce the behavior:
run `qvm-prefs -l dom0` in dom0

### General notes:

Mailing list thread: https://groups.google.com/forum/#!topic/qubes-devel/pRkDqzK0hzg

**Comment by andrewdavidwong** [comment]
[Copying Marek's response here for anyone who doesn't look at the thread.]
