### ISSUE TITLE
Readme broken

### ISSUE THREAD

**Issue by rugk** [QubesOS/qubes-issues#2723]
The Readme in this repo [is broken](https://github.com/QubesOS/qubes-issues#notable-issues)…

Some spaces too much as it seems or so.

**Comment by andrewdavidwong** [comment]
> The Readme in this repo is broken…

Interesting.

> Some spaces too much as it seems or so.

No, it looks like GitHub broke something. Even if you go all the way back to one of the [earliest commits](https://github.com/QubesOS/qubes-issues/blob/acd5059fa85444f49c9b6a7f4ef3ac1447e9e633/README.md) it now renders the Markdown incorrectly, whereas it did not before.
