### ISSUE TITLE
Build docs need updating

### ISSUE THREAD

**Issue by unman** [QubesOS/qubes-issues#2727]
The [guide to building Qubes](https://www.qubes-os.org/doc/qubes-builder/) refers to copying the config for master - this is currently (March 2017) broken.
Either add an explanation for failure, or explain options for alternative builds.

**Comment by marmarek** [comment]
This is transient state because we're currently moving Qubes 4.0 code into master branch. Most of it is already done, but what left is the most tricky part...

**Comment by marmarek** [comment]
What I mean - IMO it doesn't make sense do add such info now, because it will be outdated (again) very soon.
