### ISSUE TITLE
qvm-trim-template gets stuck on cleaning up

### ISSUE THREAD

**Issue by hyperfekt** [QubesOS/qubes-issues#2728]
#### Qubes OS version (e.g., `R3.2`):
R3.2

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable): 
debian-8, whonix-gw, whonix-ws

---

### Expected behavior:
After performing fstrim the `qvm-trim-template` command cleans up within a few seconds and exits.

### Actual behavior:
`fstrim done, cleaning up...` is shown indefinitely. A keyboard interrupt displays the following:
```
Traceback (most recent call last):
    File "/usr/bin/qvm-trim-template", line 171, in <module>
        main()
    File "/usr/bin/qvm-trim-template", line 148, in main
        time.sleep(1)
```
The directory `/var/lib/qubes/appvms/trim-[templatename]` and the domain `trim-[templatename]` continue to exist.

### Steps to reproduce the behavior:
1. execute `qvm-trim-template [templatevm]`, where `[templatevm]` is one of the affected (see above)

### General notes:
Attempts to perform the cleanup  manually with `rm -r /var/lib/qubes/appvms/trim-[templatename]`, followed by `virsh -c xen:/// undefine trim-[templatename]` (as per https://github.com/QubesOS/qubes-issues/issues/1910#issuecomment-275259229) and `virsh -c xen:/// destroy trim-[templatename]` and then try to reproduce the issue with the same TemplateVM lead to failure to execute the qrexec-daemon:
```
Disk usage before:
2433080 /var/lib/qubes/vm-templates/debian-8/root.img
Creating temporary VM...
--> Creating volatile image: /var/lib/qubes/appvms/trim-debian-8/volatile.img...
--> Loading the VM (type = AppVM)...
--> Starting Qubes DB...
--> Setting Qubes DB info for the VM...
--> Updating firewall rules...
--> Starting the VM...
--> Starting the qrexec daemon...
Waiting for VM's qrexec agent.............................................................Cannot connect to 'trim-debian-8' qrexec agent for 60 seconds, giving up
Traceback (most recent call last):
  File "/usr/bin/qvm-trim-template", line 171, in <module>
    main()
  File "/usr/bin/qvm-trim-template", line 116, in main
    fstrim_vm.start(start_guid=False, verbose=True)
  File "/usr/lib64/python2.7/site-packages/qubes/modules/000QubesVm.py", line 2031, in start
    self.start_qrexec_daemon(verbose=verbose,notify_function=notify_function)
  File "/usr/lib64/python2.7/site-packages/qubes/modules/000QubesVm.py", line 1854, in start_qrexec_daemon
    raise OSError ("Cannot execute qrexec-daemon!")
OSError: Cannot execute qrexec-daemon!
```
A reboot does not change this.

---

**Comment by unman** [comment]
I've never seen this.
Are you using a vanilla 3.2? If not, what modifications have you made?
What are the specs of your Qubes machine?

**Comment by hyperfekt** [comment]
I've made no modifications except manual partitioning to get a bigger swap
(just /boot, swap and root). The only thing I had done on the system at
that point was updating dom0 and the TemplateVMs.
I'm running on a Dell Latitude E5470 with an i5 6440HQ (VT-x and VT-d
capable), 8GB RAM and a 256GB SATA SSD. Any other specs that could be
relevant?
Mind that this did not happen when trimming the Fedora TemplateVMs.

**Comment by andrewdavidwong** [comment]
Just to check: Did the VM have a long name (#1655)?

**Comment by hyperfekt** [comment]
No, these were all the default templates except for `fedora-24`.

**Comment by unman** [comment]
I dont use Whonix, but I do use Debian templates without seeing this behaviour, even on laptop with less than 8GB RAM.
I cant think of an obvious explanation why Debian based templates should behave differently from Fedora ones.
Could you try deleting the existing Debian-8, replacing it with the original taken from your install medium, and then try the trim?

**Comment by hyperfekt** [comment]
How exactly would I go about doing that? I don't appear to be able to find the original VM on the medium.
I presume I would create the VM using the [qvm-create](url) command.
Excuse if I'm a bit slow, I'm relatively new to both Linux and Qubes.
BTW, I stumbled upon another bug while trying to do this. (#2733)

**Comment by hyperfekt** [comment]
I did a complete reinstall, and this time this glitch(?) did not appear. o_o

**Comment by andrewdavidwong** [comment]
Ok, feel free to let us know if the issue recurs.
