### ISSUE TITLE
Integrate WebTorrent download

### ISSUE THREAD

**Issue by rugk** [QubesOS/qubes-issues#2729]
What about using [WebTorrent](https://webtorrent.io/) to download the files directly in the browser?

**Comment by andrewdavidwong** [comment]
This is outside the scope of Qubes.

**Comment by rugk** [comment]
Eh, maybe you misunderstood my request. I suggested to integrate it into the Qubes *website*, so the installation files can be downloaded easily and fastly.

**Comment by andrewdavidwong** [comment]
I don't see any strong reason to do this, but I'm open to being convinced. To elaborate:

* I don't see much, if any, user demand for this.
* WebTorrent bills itself as being useful mainly for streaming media, but that's not useful for Qubes ISOs.
* We already support conventional torrents.

If it's just a matter of including a snippet of JavaScript, and if this doesn't other decrease the security and privacy of the website, we'd probably accept a PR for it.

**Comment by rugk** [comment]
I just see the convenience and the speed it brings by default (I doubt many users user the conventional torrent files). Also users don't need to initial another torrent software.
But good idea to accept PRs, personally is also say this is more a "nice to have" feature. So why not reopen it and tag it with "help wanted" or however you do it? Otherwise contributors are unlikely to find this issue.

**Comment by andrewdavidwong** [comment]
> I just see the convenience and the speed it brings by default (I doubt many users user the conventional torrent files).

But it seems like even fewer users would use this less-known(?) technology.

> So why not reopen it and tag it with "help wanted" or however you do it? Otherwise contributors are unlikely to find this issue.

Oh, I thought *you* would be submitting the PR.

Well, there are other problems I mentioned in my previous comment, which you haven't addressed. Also, I have a feeling that if we reopen this and tag it as "help wanted," it's just going to sit there forever. Then again, the same can probably be said of many other issues, so sure, let's leave it open, at least for the time being.

**Comment by h01ger** [comment]
Hi,

please just keep https://biterrant.io in mind and (provide instructions how to)
validate sha256 sums!


-- 
cheers,
	Holger

**Comment by andrewdavidwong** [comment]
Yes, signatures should always be verified regardless of download method:

https://www.qubes-os.org/security/verifying-signatures/

**Comment by marmarek** [comment]
If someone don't want to install a torrent client, there is already an alternative - traditional HTTPS download (including few mirrors linked there). I really don't see any reason to have javascript torrent client embedded on our website.

**Comment by rugk** [comment]
But HTTPS is slow. So when one does not want to install a client (convenience), but wants to have a fast download, there is WebTorrent. That's what I meant with connecting these two things.

**Comment by andrewdavidwong** [comment]
The question is whether we should include extra JS -- which we will not have time to vet -- on our download page just to accommodate the (probably tiny) subset of people for whom HTTPS is too slow, who are not willing to install a torrent client, and who use WebTorrent. It doesn't seem worth it.

**Comment by Aktariel** [comment]
https://instant.io will take a torrent and turn it into a WebTorrent. I wouldn't recommend putting this on the download page, but it is an option for someone who doesn't want to use HTTPS or a torrent client (0_o).

**Comment by andrewdavidwong** [comment]
Thanks, @Aktariel. Looks like that's a good solution.
