### ISSUE TITLE
u2mfn unbuildable on modern kernels, result: no GUI

### ISSUE THREAD

**Issue by Rudd-O** [QubesOS/qubes-issues#2730]
Followed these instructions on a F25 template:

https://www.qubes-os.org/doc/managing-vm-kernel/

Section

Using kernel installed in the VM.

Then I noticed U2MFN was missing after I logged in via the XL console.

U2MFN is not installable then, using `dkms autoinstall`.

Error follows:

```
-bash-4.3# cat /var/lib/dkms/u2mfn/3.2.3/build/make.log
DKMS make.log for u2mfn-3.2.3 for kernel 4.9.14-200.fc25.x86_64 (x86_64)
Mon Mar 27 05:39:58 UTC 2017
make: Entering directory '/usr/src/kernels/4.9.14-200.fc25.x86_64'
  LD      /var/lib/dkms/u2mfn/3.2.3/build/built-in.o
  CC [M]  /var/lib/dkms/u2mfn/3.2.3/build/u2mfn.o
/var/lib/dkms/u2mfn/3.2.3/build/u2mfn.c: In function ‘u2mfn_ioctl’:
/var/lib/dkms/u2mfn/3.2.3/build/u2mfn.c:80:23: error: passing argument 5 of ‘get_user_pages’ from incompatible pointer type [-Werror=incompatible-pointer-types]
       (data, 1, 1, 0, &user_page, 0);
                       ^
In file included from /var/lib/dkms/u2mfn/3.2.3/build/u2mfn.c:26:0:
./include/linux/mm.h:1280:6: note: expected ‘struct vm_area_struct **’ but argument is of type ‘struct page **’
 long get_user_pages(unsigned long start, unsigned long nr_pages,
      ^~~~~~~~~~~~~~
/var/lib/dkms/u2mfn/3.2.3/build/u2mfn.c:79:9: error: too many arguments to function ‘get_user_pages’
   ret = get_user_pages
         ^~~~~~~~~~~~~~
In file included from /var/lib/dkms/u2mfn/3.2.3/build/u2mfn.c:26:0:
./include/linux/mm.h:1280:6: note: declared here
 long get_user_pages(unsigned long start, unsigned long nr_pages,
      ^~~~~~~~~~~~~~
cc1: some warnings being treated as errors
scripts/Makefile.build:299: recipe for target '/var/lib/dkms/u2mfn/3.2.3/build/u2mfn.o' failed
make[1]: *** [/var/lib/dkms/u2mfn/3.2.3/build/u2mfn.o] Error 1
Makefile:1494: recipe for target '_module_/var/lib/dkms/u2mfn/3.2.3/build' failed
make: *** [_module_/var/lib/dkms/u2mfn/3.2.3/build] Error 2
make: Leaving directory '/usr/src/kernels/4.9.14-200.fc25.x86_64'
```

What gives?

**Comment by Rudd-O** [comment]
(Looks like the U2MFN `configure` step needs to detect what type of arguments to use for certain functions.(

**Comment by Rudd-O** [comment]
Fortunately, `ansible-qubes`  *does* work.  :-)

**Comment by rtiangha** [comment]
The problem is the version of u2mfn.c that's currently available in current is not compatible with kernels 4.9 and higher. There's been a fix in the repository that's been sitting there for the last five months now, but it hasn't been pushed out yet. I've filed a bug report hoping that it will one day:

https://github.com/QubesOS/qubes-issues/issues/2691

In the meantime, just manually copy over the version of u2mfn.c that's in the repository over /usr/src/u2mfn-3.2.3/u2mfn.c and that kernel compilation should continue on:

https://raw.githubusercontent.com/QubesOS/qubes-linux-utils/master/kernel-modules/u2mfn/u2mfn.c

**Comment by rtiangha** [comment]
Edit: Never got the message notification; looks like there's an updated version of linux-utils in current-testing now:

https://github.com/QubesOS/updates-status/issues/17

That should fix it, I think.
