### ISSUE TITLE
Attaching USB block device to dom0 fails & freezes Qubes VM Manager

### ISSUE THREAD

**Issue by hyperfekt** [QubesOS/qubes-issues#2733]
#### Qubes OS version (e.g., `R3.2`):
R3.2
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):

---

### Expected behavior:
After commanding so in the context menu of dom0, the USB flash drive is attached to dom0.
Alternatively, this is either not selectable in the first place, or an explanation as to why this is not possible is provided.

### Actual behavior:
The Qubes VM Manager shows `ValueError: Dom0 do not have libvirt object` and stops responding (which is why I'm not able to provide the further details of the error message), requiring it to be terminated.
Simultaneously, a notification saying
```
Qubes VM Manager
dom0 - attaching sys-usb:sd[a/b/...]
```
is shown.
Afterwards, the block device is not attached.

### Steps to reproduce the behavior:
1. Open Qubes VM Manager.
2. Right-click on dom0.
3. Select `Attach/detach block devices`
4. Select `Attach  sys-usb:sd[a/b/...] [size] [identifier] ([name])`.

### General notes:
Attaching the same device works fine in VMs that are not dom0.
The same issue appears when using a different flash drive with different contents.

---

**Comment by ano42** [comment]
I have the exactly same behavior and tried it in the terminal:

```
[me@dom0 ~]$ qvm-block -a dom0 sys-usb:sda
Traceback (most recent call last):
  File "/usr/bin/qvm-block", line 152, in <module>
    main()
  File "/usr/bin/qvm-block", line 106, in main
    block_attach(qvm_collection, vm, dev, **kwargs)
  File "/usr/lib64/python2.7/site-packages/qubes/qubesutils.py", line 399, in block_attach
    frontend = block_find_unused_frontend(vm)
  File "/usr/lib64/python2.7/site-packages/qubes/qubesutils.py", line 227, in block_find_unused_frontend
    xml = vm.libvirt_domain.XMLDesc()
  File "/usr/lib64/python2.7/site-packages/qubes/modules/006QubesAdminVm.py", line 60, in libvirt_domain
    raise ValueError("Dom0 do not have libvirt object")
ValueError: Dom0 do not have libvirt object
```

**Comment by graffen** [comment]
I just ran into this too. I was going to perform a full backup of my system to transfer to a new laptop but I can't due to this problem. Is there a workaround or solution to it?

**Comment by andrewdavidwong** [comment]
> I just ran into this too. I was going to perform a full backup of my system to transfer to a new laptop but I can't due to this problem. Is there a workaround or solution to it?

One option is to attach your USB drive to a domU instead.
