### ISSUE TITLE
qubes-desktop-linux-common

### ISSUE THREAD

**Issue by jpouellet** [QubesOS/qubes-issues#2735]
It has become clear that there is code shared between desktop environments that does not really belong in qubes-core. Currently it's either dumped in the desktop environment, or in qubes-core-admin-linux, but this is less than ideal.

This issue tracks the creation of a new more suitable repo and package, qubes-desktop-linux-common, to hold such code.

[Here](https://github.com/jpouellet/qubes-desktop-linux-common) is an initial version of the repo (containing so far only qvm-xkill factored out of qubes-core-admin-linux [as suggested by @marmarek](https://github.com/QubesOS/qubes-issues/issues/2706))

If this change is agreed upon, we would need to:
- [x] fork https://github.com/jpouellet/qubes-desktop-linux-common under @QubesOS
- [x] [remove qvm-xkill from qubes-core-admin-linux](https://github.com/QubesOS/qubes-core-admin-linux/pull/22)
- [x] [start building it in qubes-builder](https://github.com/QubesOS/qubes-builder/pull/18)
- [x] start building it in Travis CI (help wanted)
- [x] add desktop-linux-common as a dependency of the other desktop environments:
  - [x] [awesome](https://github.com/QubesOS/qubes-desktop-linux-awesome/pull/2)
  - [x] [i3](https://github.com/QubesOS/qubes-desktop-linux-i3/pull/7)
  - [x] [KDE](https://github.com/QubesOS/qubes-desktop-linux-kde/pull/7)
  - [x] [Xfce4](https://github.com/QubesOS/qubes-desktop-linux-xfce4/pull/8)
- [ ] identify and move other things there
  - [ ] [qvm-terminal](https://github.com/QubesOS/qubes-issues/issues/2706)
  - [x] [qubes-menus](https://github.com/QubesOS/qubes-desktop-linux-kde/tree/master/qubes-menus)
  - [ ] ...

**Comment by woju** [comment]
On Thu, Mar 30, 2017 at 10:24:00PM -0700, Jean-Philippe Ouellet wrote:
> - [ ] identify and move other common components there

qubes-menus

**Comment by marmarek** [comment]
As said in https://github.com/QubesOS/qubes-builder/pull/18#issuecomment-293516880, 👍 from me.
Currently the priority for me is getting Qubes 4.0 code into a shape where broader testing would be possible (for example installable ISO). But in the meantime, I'll review and probably merge the above.

**Comment by marmarek** [comment]
Lets close it now, as package is implemented and deployed. qvm-terminal have its own ticket.
