### ISSUE TITLE
Cannot install Qubes OS 3.2 on Lenovo ??40 notebook

### ISSUE THREAD

**Issue by exander77** [QubesOS/qubes-issues#2744]
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):

---

### Expected behavior:
Installer succeeds.

### Actual behavior:
Installer fails with this message repeated several times:
```
mount: /dev/mapper/live-rw is write-protected, mounting read-only
mount: wrong fs type, bad option, bad superblock on /dev/mapper/live-rw,
missing codepage or helper program, or other error
In some cases useful info is found in syslog - try
dmesg | tail or so.
```
Then:

```
Starting Dracut Emergency Shell...

Generating "/run/initramfs/rdsosreport.txt"

Entering emergency mode. Exit the shell to continue.
Type "journalctl" to view system logs.
You might want to save "/run/initramfs/rdsosreport.txt" to a USB stick or /boot after mounting them and attach it to a bug report."
```

When I try "dmesg | tail" it compains about "tail: command not found" which is funny.

Exiting shell starts it again.

In "/run/initramfs/rdsosreport.txt" there does not seem to be anything interesting.  Just "Starting Initrd File Systems." and then the repeating message about mounting-read only mentioned above. This follows with message "Starting Dracut Emergency Shell...".

### General notes:

---

**Comment by andrewdavidwong** [comment]
This is too localized for `qubes-issues`. Please consider posting this to the `qubes-users` mailing list instead. (You can read more about our mailing lists [here](https://www.qubes-os.org/mailing-lists/).)

`qubes-users` is intended for these sorts of questions and receives much more traffic, which means that your question is more likely to receive a response there.

**Comment by exander77** [comment]
I am not sure what you mean by "too localized"? And how could maling list help me, this is clearly some bug in installer. Also I was there, somebody asked some similar issue a year ago and it went with single response: https://groups.google.com/forum/#!topic/qubes-users/RV8WPBaRZRQ

**Comment by andrewdavidwong** [comment]
> I am not sure what you mean by "too localized"?

"Our GitHub issues tracker is not intended for personal, localized troubleshooting questions, such as problems that affect only a specific laptop model. Those questions are more likely to be answered in qubes-users, which receives much more traffic. Instead, GitHub issues are meant to track more general bugs and enhancements that affect a broad range of Qubes users."

From: https://www.qubes-os.org/doc/reporting-bugs/#where-to-submit-your-report

(Note that you are prompted to read that page before submitting an issue here.)

> And how could maling list help me, this is clearly some bug in installer.

If it is, in fact, a bug in the installer, then we can (and should) reopen this, but so far there's no indication that it's not just a hardware compatibility issue with your particular laptop model. Unfortunately, this sort of thing is very common.

> Also I was there, somebody asked some similar issue a year ago and it went without single response: https://groups.google.com/forum/#!topic/qubes-users/RV8WPBaRZRQ

Then it may simply be the case that no one knows the answer. But for other possibilities, see:

https://www.qubes-os.org/mailing-lists/#discussion-list-guidelines

**Comment by exander77** [comment]
This is neither related to single machine, nor to single model. I personally tested in on T440p, X240 and T540, behavior is the same. I am not sure, but it may even affect all new Lenovo models.

Also this is not a problem with running the system, but with starting the installer. What could be the hardware compatibility issue there? Hardware is fully supported by Linux kernel for some time. I have installed and run many distributions on a variety of ThinkPads. Also no error message is in the log, so even if it were a hardware compatibility issiue, then clearly error reporting during installation is an issue by itself.

I am able to put some time into this. I may test various things, but some basic information what it could be related to would be appreciated.

**Comment by andrewdavidwong** [comment]
> This is neither related to single machine, nor to single model. I personally tested in on T440p, X240 and T540, behavior is the same. I believe it affects whole ??40 line, I am not sure, but it may even affect all new Lenovo models.

Ok, that's a different story.

> Also this is not a problem with running the system, but with starting the installer. What could be the hardware compatibility issue there? Hardware is fully supported by Linux kernel for some time. I have installed and run many distributions on a variety of ThinkPads. Also no error message is in the log, so even if it were a hardware compatibility issiue, then clearly error reporting during installation is an issue by itself.

Linux kernel compatibility doesn't guarantee Qubes compatibility. Qubes has more stringent hardware requirements. In some cases, the problem is with loading Xen.

> I am able to put some time into this. I may test various things, but some basic information what it could be related to would be appreciated.

@marmarek will know better what you should test. But first of all: Which version of Qubes are you trying to install?

**Comment by exander77** [comment]
I am trying to install 3.2. Xen is loaded during installation?

I have T500 avaiable here, so I may test on some older ThinkPad too.

**Comment by Raeon** [comment]
I am experiencing _exactly_ the same behaviour on my MSI laptop, with exact model name `MSI GE62 2QC-232NL`. I am attempting installation from a USB2.0 device on an USB2.0 port.

It may be worth nothing however that when I try to run validation, it consistently fails at 42.9%. I've already validated the ISO file to be correct. So far I've only been able to test this using a single USB drive, as I do not have another available to me at this time. @exander77 Is this also the case for you?

**Comment by marmarek** [comment]
When you land in dracut emergency shell, what are last line of kernel messages related to (failed) mount of live-rw (may be named dm-0 there)? Validation failing at `42.9%` may mean faulty USB drive. What is its size BTW? The installation image is slightly bigger than 4GB.

**Comment by Raeon** [comment]
The installation image `Qubes-R3.2-x86_64.iso` is exactly `4,246,732,800` bytes. dd reported it was 4.2GB or 4.0GiB.

The repeated kernel messages are (timestamps omitted):

> dracut-mount[814]: mount: /dev/mapper/live-rw is write-protected, mounting read-only
> dracut-mount[814]: mount: wrong fs type, bad option, bad superblock on /dev/mapper/live-rw,
> dracut-mount[814]: missing codepage or helper program, or other error
> dracut-mount[814]: In some cases useful info is found in syslog - try
> dracut-mount[814]: dmesg | tail or so.

After this it reports
> Generating "/run/initramfs/rdsosreport.txt"

and drops me into the dracut emergency shell. Here it also reports two additional kernel messages:
> sd 6:0:0:0 [sdd] No Chaching mode page found
> sd 6:0:0:0 [sdd] Assuming drive cache: write through

Although this is definitely not the first time I've seen those. Now I'm at the shell. As the original post mentioned, `tail` indeed does not exist, therefore `dmesg | tail` also does not work.

**Comment by marmarek** [comment]
Try just `dmesg` and see last few messages.

**Comment by Raeon** [comment]
I `dd`-ed the ISO image onto the MicroSD card and tried to install from that instead, this time from an USB3.0 port. Validation again failed at 42.9%, and installation failed in the same way as described above.

I double-checked and verified the ISO image again, but it is _still_ correct.

**Comment by Raeon** [comment]
Last few `dmesg` messages: [https://i.imgur.com/uFWaSIU.jpg](https://i.imgur.com/uFWaSIU.jpg)

**Comment by marmarek** [comment]
That's strange, I don't see anything wrong here. Can you post full `/run/initramfs/rdsosreport.txt`? (note that it will contain very detailed information about your hardware, so if you're not comfortable with publishing it, you send it directly to me via email)

**Comment by Raeon** [comment]
That's fine by me! Interestingly, the first time I tried to open this file (on Windows 10 with Notepad++ I might add), it ended with a lot of NULL bytes. I did the install again, and this time the file still seems to end abruptly, although not with NULL bytes.

rdsosreport.txt: [https://pastebin.com/raw/2gZ0f2eA](https://pastebin.com/raw/2gZ0f2eA)

**Comment by marmarek** [comment]
Ok, I think I've found the problem - you have two copies of installation image:
 - on internal disk (sdb, WDC WDS120G1G0A 120GB)
 - on the MicroSD card

The first one is found first, but it is broken (at 42.9%). The second one is ignored.
I guess you've tried to dd the installation image there first. I hope you didn't overriden anything important on that disk...
Now, to fix this, you can either put whole installation image to sdb, or remove it from there completely - for example (re-)create normal partition table. 

```
/dev/sdb1: UUID="2016-09-20-10-42-46-00" LABEL="Qubes-R3.2-x86_64" TYPE="iso9660" PTUUID="020e6c95" PTTYPE="dos" PARTUUID="020e6c95-01"
/dev/sdb2: SEC_TYPE="msdos" LABEL="ANACONDA" UUID="29A2-A71C" TYPE="vfat" PARTUUID="020e6c95-02"
```

**Comment by Raeon** [comment]
@marmarek Your deduction is correct!

I did `dd` the ISO to the target device at one point. I figured it would not cause me any trouble since I would just overwrite it during the actual installation, but _oh by did I guess wrong._ Validation reaches a 100% now; however the installation seems to hang during `Performing post-installation setup tasks`, but that would be unrelated to this issue.

@marmarek Thanks for the assistance. 👍

**Comment by marmarek** [comment]
That step can take quite some time, on some machines up to 15 minutes...

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
