### ISSUE TITLE
qubes-dom2-update missing --assumeyes option

### ISSUE THREAD

**Issue by r-cheologist** [QubesOS/qubes-issues#2746]
#### Qubes OS version (e.g., `R3.2`):
R3.2
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):
NA

---

### Expected behavior:
For scripted use `qubes-dom0-update` should (as does the underlying package manager) support a `--assumeyes` switch;
### Actual behavior:
Switch doesn't exist and `yes | qubes-dom0-update` also does not work;

**Comment by marmarek** [comment]
Any option supported by underlying package manager should work. At least
`-y` do work, I use it frequently. Maybe `qubes-dom0-update --help`
should also print `dnf --help` output?

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by r-cheologist** [comment]
On Wed, 2017-04-12 at 15:08 -0700, Marek Marczykowski-Górecki wrote:
> Any option supported by underlying package manager should work. At
> least
> `-y` do work, I use it frequently. Maybe `qubes-dom0-update --help`
> should also print `dnf --help` output?
> 
You are right 'qubes-dom0-update --assumeyes' appears to be working.

Documentation is definitely improvable - should find some time to pitch
in. Another example is 'qubes-prefs', which doesn't mention anywhere
that it can be used to set the variables as well ...

Joh

**Comment by marmarek** [comment]
```
[marmarek@dom0 ~]$ qubes-prefs --help
Usage: qubes-prefs [-l]
usage: qubes-prefs [-g] <property>
usage: qubes-prefs [-s] <property> <new-value>
List/set various global properties.

Options:
  -h, --help  show this help message and exit
  -l, --list  
  -s, --set   
  -g, --get
```
But indeed manual page miss this information.
