### ISSUE TITLE
site: broken links on download page

### ISSUE THREAD

**Issue by jpouellet** [QubesOS/qubes-issues#2752]
While working on https://github.com/QubesOS/qubes-issues/issues/2725, I discovered the following:

There are two (invalid) links to https://mirrors.kernel.org%20/ on https://www.qubes-os.org/downloads/ (the links on the right for the torrent entries)

This comes from the way that the data is being templated which is trying to use the mirror names as unique keys, but also wants more than one entry per :
- example 1 (mirrors.kernel.org) [good name](https://github.com/QubesOS/qubesos.github.io/blob/7ae9c7af0aa8974cc35cdbe7677b936b61d19b93/_data/downloads.yml#L14), [same but with space](https://github.com/QubesOS/qubesos.github.io/blob/7ae9c7af0aa8974cc35cdbe7677b936b61d19b93/_data/downloads.yml#L44)
- example 2 (ftp.qubes-os.org) [good name](https://github.com/QubesOS/qubesos.github.io/blob/7ae9c7af0aa8974cc35cdbe7677b936b61d19b93/_data/downloads.yml#L34), [same but with space](https://github.com/QubesOS/qubesos.github.io/blob/7ae9c7af0aa8974cc35cdbe7677b936b61d19b93/_data/downloads.yml#L64)

**Comment by andrewdavidwong** [comment]
Yeah, I'm pretty sure that's an intentional (but admittedly ugly) workaround.

**Comment by andrewdavidwong** [comment]
I saw that we already had some entries like that, and that there was no other obvious, quick, and easy way to add new entries, so I followed that convention. Do you have a better solution, @jpouellet?

**Comment by jpouellet** [comment]
How about https://github.com/QubesOS/qubesos.github.io/pull/94?

**Comment by andrewdavidwong** [comment]
Looks great, thanks!
