### ISSUE TITLE
https://qubes-os.org redirects to an insecure page: http://www.qubes-os.org/ (and potentially enabling HSTS?)

### ISSUE THREAD

**Issue by ghost** [QubesOS/qubes-issues#2754]
https://qubes-os.org redirects to an insecure page: http://www.qubes-os.org/. `http://qubes-os.org` should immediately redirect to `https://qubes-os.org` (and then to https://www.qubes-os.org) Take a look at: https://hstspreload.org/?domain=qubes-os.org

By solving the issues above the Qubes-os.org website will get added to the [HSTS Preload](https://hstspreload.org) list (which is used by the main web browsers, Chrome, Firefox, ...) to force HTTPS.

**Comment by andrewdavidwong** [comment]
@marmarek, can you control this via Cloudflare's settings?

**Comment by andrewdavidwong** [comment]
Also worth noting:

- https://www.qubes-os.org/doc/user-faq/#should-i-trust-this-website
- https://www.qubes-os.org/doc/user-faq/#why-doesnt-this-website-have-security-feature-x

**Comment by marmarek** [comment]
I've added http://qubes-os.org/ -> https://qubes-os.org/ redirect in CF, but now github pages redirect https://qubes-os.org/ -> http://www.qubes-os.org/ ...
Ok, added the second redirect also at CF level. Now the only issue reported by hsts preload is missing includeSubDomains. But for this we need to be sure that really all subdomains use HTTPS.

**Comment by andrewdavidwong** [comment]
> But for this we need to be sure that really all subdomains use HTTPS.

The ones that I'm aware of appear to, but I don't have access to an exhaustive list.

**Comment by marmarek** [comment]
The list isn't that long. Looks like all of them do support https. But not all have redirects http->https. I guess it's irrelevant here (for HSTS preload)?
I'm wondering about yum.qubes-os.org and deb.qubes-os.org. AFAIR there were some problems with https and APT repositories. Does APT (or any non-browser http client) care about HSTS?

**Comment by andrewdavidwong** [comment]
No idea. Maybe @adrelanos knows?

**Comment by adrelanos** [comment]
> Does APT care about HSTS?

No, and I haven't found any discussions about having apt-get do that either. Looks like HSTS makes limited sense for apt-get? Either you add some https or http repositories. If it's https, it should really be used. And if it's http, it should not automagically upgrade to https. I guess?

**Comment by marmarek** [comment]
Ok, enabled includeSubDomains. Lets hope I didn't missed anything...

**Comment by GoodMaid** [comment]
@marmarek @andrewdavidwong This has been implemented https://hstspreload.org/?domain=qubes-os.org

Please close the issue.
