### ISSUE TITLE
DispVM startup fails silently in low-memory conditions after template update

### ISSUE THREAD

**Issue by jpouellet** [QubesOS/qubes-issues#2758]
#### Qubes OS version (e.g., `R3.2`):

R3.2

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):

fedora-24

---

### Expected behavior:

When trying to start a DispVM, it either starts, or provides an error message saying why it failed to start.

### Actual behavior:

Exact error messages below are not literal quotes. I forget the exact phrases and don't have time to reproduce right now.

After updating the DispVM's template, and if there is insufficient memory to start the corresponding *-dvm vm, then you get the "Please wait while qubes regenerates the template (up to 120 seconds)" message, but no messages after that. If you try to start it again, then only at that time do you get a "dispvm generation failed" message and simultaneously another "Please wait while qubes regenerates ... (120 seconds)".

Also the following:
```
[user@dom0 ~]$ qvm-create-default-dvm f24-usable
--> Creating volatile image: /var/lib/qubes/appvms/f24-usable-dvm/volatile.img...
--> Loading the VM (type = AppVM)...
ERROR: ERROR: insufficient memory to start VM 'f24-usable-dvm'
```

### Steps to reproduce the behavior:

- Update the default dispvm's template
- start a bunch of VMs such that there is insufficient memory to start another
- try to start a DispVM

### General notes:

---

#### Related issues:

https://groups.google.com/d/topic/qubes-users/ZhxD-RoqAnY/discussion

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
