### ISSUE TITLE
Configurable GUI daemon startup timeout

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#2759]
https://groups.google.com/d/msgid/qubes-users/od5m01%24j1f%242%40blaine.gmane.org
> Is there any way that I can change the time out the DVM generation
script waits in order to connect to qubes-guid? I think I may need to
double or triple it, but the machine does start up eventually; it's just
the DVM generation script that gives up too soon.

**Comment by rtiangha** [comment]
Thanks; installing this in dom0 and setting startup_timeout in guid.conf to something higher than 45 worked perfectly and I can reliably generate DispVMs again.
