### ISSUE TITLE
Frequent AppVM GUI freezing (Chromium-specific)

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#2765]
#### Qubes OS version (e.g., `R3.2`):

`R3.2`

---

#### Problem description:

I've noticed very frequent Chromium freezing recently. For me, Chromium browser seems to be the only app/window that freezes, and I have to restart the whole AppVM when it does. Others report different apps/windows also freezing. The problem seems to have started right after updating qubes-libvchan-xen to 3.2.1, but this is merely an observed correlation.

Discussion thread:

https://groups.google.com/d/topic/qubes-users/1oL5qyMdFfo/discussion

**Comment by marmarek** [comment]
I don't believe qubes-libvchan-xen update cause this. There is no change touching data-flow code. Much more likely updated gui-agent.

**Comment by rtiangha** [comment]
I actually agree with that, if that's the package that deals with interacting with windows and such.

Even though the App windows is frozen, it still accepts input. For example, with a frozen xterm, you can type commands in it and hit Enter. Launch another xterm from Qubes Manager (assuming *it* isn't frozen, which I've encountered a couple of times too; sometimes I have to run killall qubes-manager to get things to work again), and as soon as that new xterm window launches, the other xterm window becomes responsive again and everything you had typed into it appears on the screen.

So it almost seems like while one thing is not responsive, another thing is. So maybe it's not the VM that's frozen, but whatever software piece that interacts with it.

**Comment by andrewdavidwong** [comment]
> I don't believe qubes-libvchan-xen update cause this. There is no change touching data-flow code. Much more likely updated gui-agent.

Ok, but I observed the problem *before* the recent gui-agent update. The first time was after updating qubes-libvchan-xen and before updating everything else.

**Comment by andrewdavidwong** [comment]
See comments on duplicate issue #2772.

**Comment by andrewdavidwong** [comment]
Update: This issue now refers to a Chromium-specific bug with the same or similar symptoms as #2772.

**Comment by HW42** [comment]
Does this still happens with gui-agent-linux (package qubes-gui-vm in Fedora, xserver-xorg-input-qubes in Debian) 3.2.17?

**Comment by HW42** [comment]
Oh sorry, I missed this comment:

> Ok, but I observed the problem before the recent gui-agent update. The first time was after updating qubes-libvchan-xen and before updating everything else.

If this happened with gui-agent-linux 3.2.14 or earlier it must be another bug.

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
