### ISSUE TITLE
Update Screenshots to make it clear that Xfce4 is the default DE

### ISSUE THREAD

**Issue by rootkovska** [QubesOS/qubes-issues#2767]
I keep meeting/seeing people who think we still use KDE, which isn't true for nearly a year now. But our screenshots indeed suggest that KDE is the default option. I don't have time to make many pretty screenshots ATM, but we can use at leas this one perhaps:
https://cloud.githubusercontent.com/assets/10212863/16384754/7e131672-3c8a-11e6-8fc7-62bf9a1d90bf.png

And place it at the top on the screenshot page?

**Comment by rootkovska** [comment]
ProTip (for prospective screenshots contributors): make sure to include some nice UI things, such as the Mac-style Docker-like menu (which is not created by default during installer, but needs to be click-build by the user) and translucent (also Mac-style) titlebar. And always, always, use some nice wallpaper, and make sure to harmonize its dominant colors with the window decoration colors. :)

**Comment by andrewdavidwong** [comment]
> I don't have time to make many pretty screenshots ATM, but we can use at leas this one perhaps:
> https://cloud.githubusercontent.com/assets/10212863/16384754/7e131672-3c8a-11e6-8fc7-62bf9a1d90bf.png
> 
> And place it at the top on the screenshot page?

Done.

**Comment by andrewdavidwong** [comment]
> What is left to do with this issue?

Add/replace more screenshots until we have "enough" [where "enough" is defined by someone who isn't me ;)].

**Comment by hackerncoder** [comment]
Well, I think what we have today is enough. Time to close this issue?
