### ISSUE TITLE
Switch qubes-core-admin.readthedocs.io to QubesOS github account

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#2769]
Currently it's built from @woju's account - this was because there was no core3-devel branch on @QubesOS. But now there is.

**Comment by woju** [comment]
Updated: https://readthedocs.org/projects/qubes-core-admin/.

However the build currently fails for some pages: https://readthedocs.org/projects/qubes-core-admin/builds/5392119/. Will open new bug and fix.

**Comment by woju** [comment]
There is one more thing: can you put a webhook on QubesOS/qubes-core-admin? Here are the instructions: http://docs.readthedocs.io/en/latest/webhooks.html.

**Comment by marmarek** [comment]
Added.
