### ISSUE TITLE
qvm-open-in-dvm does not read standard input (also qvm-open-in-vm)

### ISSUE THREAD

**Issue by ubestemt** [QubesOS/qubes-issues#2773]
#### Qubes OS version (e.g., `R3.2`):

R3.2

---

### Expected behavior:

`qvm-open-in-dvm` reads from standard input and launches its contents in a DispVM. 

### Actual behavior:

Piping something to `qvm-run-in-dvm` returns `Usage: /usr/bin/qvm-open-in-dvm filename`

### Steps to reproduce the behavior:

Run `echo "test" | qvm-open-in-dvm`

### General notes:

This is may be more of a non-issue, but e.g. in mutt I have not been able to pipe an attachment to `qvm-open-in-dvm`, which would be nice.

(In mutt piping it to `1> tmp.pdf ; qvm-open-in-dvm tmp.pdf` does not work either, but that may be unrelated to this command; it works elsewhere.)

`qvm-open-in-vm $VM` behaves the same way.

**Comment by marmarek** [comment]
The purpose of `qvm-open-in-dvm` (or `-vm`) is to open **a file** there. So, this is expected behavior. 

You may to like at https://www.qubes-os.org/doc/mutt/
