### ISSUE TITLE
Backup: do not pass passphrases on cmd line

### ISSUE THREAD

**Issue by rootkovska** [QubesOS/qubes-issues#2777]
While in theory this isn't much of a security problem (everything in dom0 is isolated and trusted), still if one keeps e.g. (h)top running, then occasionally these will pop up there, and somebody might shoulder-sniff it.

**Comment by marmarek** [comment]
Duplicate of #1582

**Comment by marmarek** [comment]
(and in fact already fixed in 4.0 ;) )
