### ISSUE TITLE
Installing chromium in a Fedora-24-based DVM Template hijacks unrelated MIME types

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#2786]
#### Qubes OS version (e.g., `R3.2`):

`R3.2`

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):

`fedora-24-dvm`

---

### Expected behavior:

Files opened in DispVMs open in appropriate programs.

### Actual behavior:

Files opened in DispVMs open in Chromium, even when Chromium cannot read them.

### Steps to reproduce the behavior:

1. Use a plain fedora-24-based DVM Template.
2. Open, e.g., an "office" file (e.g., ODS, ODF, DOCX, XLS, etc.) file in a new DispVM. (Note: Trigger the opening from a non-DispVM in a DispVM. Do not `qvm-copy` the file then manually open it from the DispVM.)
3. The file opens as expected in some appropriate "office suite" program, if installed.

By contrast:

1. Install Chromium in the same DVM Template.
2. Try to open the same file again in a new DispVM (after regenerating the DVM Template).
3. The file opens in Chromium, but since Chromium can't read it, it just triggers a useless and endless "download file" loop.

### General notes:

Opening the file from, e.g., Nautilus inside the DispVM works as expected.

-----

Somewhat related thread:
https://groups.google.com/d/topic/qubes-users/VcAnMItJkEY/discussion

**Comment by ubestemt** [comment]
Not sure I can help since I don't use that template myself, but does `~/.local/share/applications/mimeapps.list` change? What is the output of `xdg-mime query default application/vnd.oasis.opendocument.text` and what happens when you run `xdg-open filename`?

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
