### ISSUE TITLE
Qubes Manager: can't remove device assignment for nonexistent device

### ISSUE THREAD

**Issue by kbrn** [QubesOS/qubes-issues#2789]
#### Qubes OS version (e.g., `R3.2`):
R3.2

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):
N/A (dom0)

---

### Expected behavior:
After disabling a device in my BIOS menu, I tried to start a VM to which that device had previously been assigned.  That VM failed to start.  I expected to be able to remove the design assignment with Qubes Manager's Settings dialog.

### Actual behavior:
There was no way to remove the now-nonexistent device assignment with Qubes Manager.  I had to close Qubes Manager and edit qubes.xml by hand.

### Steps to reproduce the behavior:
Assign a device on the PCI bus to a VM. Shut down your machine.  Remove or disable the PCI device.  Reboot and try to start that VM. Try to remove the device assignment from the VM using Qubes Manager.

### General notes:
None.

---

**Comment by andrewdavidwong** [comment]
I'm curious whether `qvm-prefs` would have worked. Did you happen to try it?

**Comment by marmarek** [comment]
qvm-pci also should work.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.

**Comment by kbrn** [comment]
Sorry for abandoning this issue; I didn't receive any notifications about issue updates.

This issue should be re-opened.  The buggy behavior persists in Qubes 4.  `qvm-prefs` does not appear to list attached devices any more.  `qvm-pci` was able to list and remove the attached device.  Still, the device does not appear in the device settings dialog GUI, and most users will not know to use `qvm-pci`.
