### ISSUE TITLE
qubes-infrastructure generated update reports (issues) in updates-status have multiple URL flaws

### ISSUE THREAD

**Issue by ij1** [QubesOS/qubes-issues#2790]
### Expected behavior:
https://github.com/QubesOS/qubes-repo... in various URLs.
### Actual behavior:
`a href="GIT_URL_vmm_xen/compare/v4.6.5-26...v4.6.5-27"`
- No substitution performed for GIT_URL
- Underscores instead of dashes in the repo part

`a href="https://github.com/GIT_URL_vmm_xen/updates-status/commit/f783018"`
- Again, same problems as with the previous case
- Extra github prefix that would likely break it after substitution gets fixed

**Comment by marmarek** [comment]
Should be better now.
