### ISSUE TITLE
Qubes OS Automatic Partitioning - Install Breaks Windows 10 UEFI Boot

### ISSUE THREAD

**Issue by MrAndromedus** [QubesOS/qubes-issues#2794]
R3.2

I installed Windows 10 on a small partition of my single disk in UEFI mode with Legacy boot available in BIOS.  This has been running without issue for some time.  In the empty space I used UEFI boot to install Qubes OS and selected the automatic partitioning, thinking that it would partition the remaining unallocated space appropriately and leave the UEFI boot in order.  The install went relatively smoothly, but upon boot Qubes would not startup due to what appeared to be a video driver issue.  

I decided to do a full format to install Qubes OS standalone, but before that wanted to get all of my data out of the Windows 10 install.  Upon trying to boot back into Windows 10 I get the "No Media Present" error.  I attempted to remove the Qubes partitions, repair EFI, rewrite boot, BCD, etc., and followed all of the various articles about fixing UEFI boot issues, but UEFI boot will not see the Windows 10 OS.  

If I use the installation media, it sees the OS but can't repair it.  BOOTSECT /scanos and /rebuildbcd do not see the operating system.  I've deleted the EFI partition, recreated it, copied the appropriate files, rebuilt BCD, and exhausted my understanding.  Windows Boot Manager works fine, but doesn't see the OS.  Please let me know if you have any suggestions for fixing or at a minimum getting the file level information off of my Windows 10 partition.  Even if it means installing another OS just to access the file level data, I'm fine with that.  Thanks for your help!

**Comment by andrewdavidwong** [comment]
Ok, so there are two things here:

1. The fact (assuming it is a fact) that installing Qubes breaks existing Windows 10 UEFI installations.
2. Advice for recovering data from your existing Windows 10 installation.

Regarding the first, this may be an upstream issue from the Fedora installer (`notourbug`), or we may decide that breaking existing installations isn't something that we're concerned about (`notanissue`), in which case a warning in the Installation Guide would be appropriate. Any opinion on this, @marmarek?

Regarding the second,  you should try searching the [mailing list](https://www.qubes-os.org/mailing-lists/) archives, since this question has probably been asked before, or ask on `qubes-users` yourself.

**Comment by MrAndromedus** [comment]
Andrew, thanks for the response.  Before installing Qubes OS I did quite a
bit of research and it seemed like it would work.  My misstep was allowing
the installer to partition the free space and modify the boot sequence,
records, and method.  As someone new to Qubes OS and only a novice in
Linux, a more direct warning or a verified guide for dual booting with
Windows via UEFI would be very welcome.

I was very disappointed to have issues with the install because it all went
so well, up until the restart.  Qubes OS seems to be the new way of not
just securing a computer, but operating one more effectively and
efficiently.  I can't wait to give it another try.

I've read through the mailing lists, GitHub, Reddit, and a few other boards
in an attempt to sort this out and get my data out of the Windows
partition, but the solutions haven't worked.  My installation media sees
the Windows OS install, but the Windows Boot Manager (Newly created EFI
partition) does not.  The installation media  I will attempt to fix the OS
boot but says it cannot.  Boot-Repair also tried and says it succeeded, but
the issue persists.

My only thought is that there is something  written to the drive before the
EFI boot that is interfering, but I'm not sure how to find it.  Does the
Qubes OS installer write anything new that may lock EFI or MBR?  I did
notice a volume prior to all the others labeled \dev\loop0 and it had
SquashFS.  Could that be the culprit?

Anyway, thanks again for your response.  I agree that this is not
necessarily a Qubes OS issue or bug, but as an OS developer community, I
would appreciate any support offered.

My next thought is to delete most of the partitions, with exception to the
Windows OS, then set it as a simple data partition before installing
another OS to then get the data from the Windows partition.  Any thoughts?

On May 6, 2017 12:31 PM, "Andrew David Wong" <notifications@github.com>
wrote:

Ok, so there are two things here:

   1. The fact (assuming it is a fact) that installing Qubes breaks
   existing Windows 10 UEFI installations.
   2. Advice for recovering data from your existing Windows 10 installation.

Regarding the first, this may be an upstream issue from the Fedora
installer (notourbug), or we may decide that breaking existing
installations isn't something that we're concerned about (notanissue), in
which case a warning in the Installation Guide would be appropriate. Any
opinion on this, @marmarek <https://github.com/marmarek>?

Regarding the second, you should try searching the mailing list
<https://www.qubes-os.org/mailing-lists/> archives, since this question has
probably been asked before, or ask on qubes-users yourself.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/QubesOS/qubes-issues/issues/2794#issuecomment-299650980>,
or mute the thread

**Comment by MrAndromedus** [comment]
Another quick comment after getting a few moments to review my system and actually capture some information.  I've noticed that at this point, whether due to my own attempts to correct the problem or an issue with the initial install, I have **two** EFI System Partitions.  One partition seems to be correct, is the appropriate size, type, and attributes.  The other partition with Type = c12a7328-f81f-11d2-ba4b-00a0c93ec93b (EFI System Partition GUID) is my Windows OS Primary Partition.  

As mind boggling as this is, I'm assuming this is why Windows won't boot.  The original EFI System Partition thinks that my Windows OS Partition is another ESP.  I've yet to attempt to set the type on this partition because I cannot find an appropriate paper or discussion telling me how to.  It is simple to create a primary partition for an OS, but if an OS partition thinks it is an ESP, how do I convert it back to a primary partition?

I realize this is a forum for Qubes and that my issue has become more of a Windows / Boot issue.  As such will leave this issue to the mods to close out or move.  Thanks again for your help!

**Comment by andrewdavidwong** [comment]
Closing as "not our bug." If you believe this is a mistake, please leave a comment, and we'll be happy to take another look. Thank you.

**Comment by akomba** [comment]
@MrAndromedus did you manage to recover windows? I ran into the exact same issue.

**Comment by KDragonM** [comment]
I installed Qubes onto a flashdrive using my laptop and now my laptop doesn't boot into windows 10. I cannot access the UEFI menu either. Upon power on, I am greeted with a blank screen.

**Comment by andrewdavidwong** [comment]
@KDragonM 
> I installed Qubes onto a flashdrive using my laptop and now my laptop doesn't boot into windows 10. I cannot access the UEFI menu either. Upon power on, I am greeted with a blank screen.

Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this does not appear to be suitable for `qubes-issues`. We ask that you please send this to the `qubes-users` [mailing list](https://www.qubes-os.org/support/) instead. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a brief comment explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.

**Comment by brosanje** [comment]
qubes sets up a protective mbr that isn't quite normal.  the reserved partition is set as active, bootable.  dell bios refuses to recognize the device for booting after that.  the solution is to flip the bit at offset 0x1be.  that byte is 0x80, set it to 0x00.  the protective mbr is the first 512 byte block on the device.

**Comment by dirt3009** [comment]
fuck your mailing list, literally almost every newbie is experiencing this which's a good enough reason to make a separate section on your documentation, if your shit isn't idiot proof then you're the idiot.
