### ISSUE TITLE
Make it clear on the website that Qubes 3.2 is LTS

### ISSUE THREAD

**Issue by rootkovska** [QubesOS/qubes-issues#2798]
We already announced that 3.2 is going to be a Ling Term Supported (LTS) release [1], but this information is hard-to-find when browsing the website. Specifically we should probably display it somewhere on the Downloads page: https://www.qubes-os.org/downloads/ 
[1] https://www.qubes-os.org/news/2016/09/02/4-0-minimum-requirements-3-2-extended-support/

**Comment by andrewdavidwong** [comment]
Done:

https://github.com/QubesOS/qubes-doc/commit/495ff2a3753b8e8bb816b05b026f356aea6807d8

https://github.com/QubesOS/qubesos.github.io/commit/af65b77f454252413f58c3348b7c2524aed03f17

**Comment by rootkovska** [comment]
Perhaps we can also add "LTS" next to the large "Qubes Release 3.2" on that page, so that it was *immediately* visible by anyone *scrolling* through that page (as opposed to actually reading the page...)?

**Comment by rootkovska** [comment]
Like e.g. here: https://www.ubuntu.com/download/desktop

**Comment by andrewdavidwong** [comment]
Not so sure about that. Ubuntu has a specific definition for LTS, and it repeatedly publishes new LTS releases on a fixed schedule: https://wiki.ubuntu.com/LTS

By contrast, ours is a one-time thing for 3.2. Doesn't make sense to call it "LTS" when there really is no such thing as "Qubes LTS."

**Comment by andrewdavidwong** [comment]
Also, note that Ubuntu LTS is supported for *five* years (an extra 4.5 years). Not sure we really want to encourage a comparison with "Qubes LTS" at a measly one year (an extra 0.5 years).

**Comment by jpouellet** [comment]
I suspect familiarity with the Ubuntu convention and unfamiliarity with Qubes may lead people quickly browsing the page and seeing a choice between:
- Qubes OS 4.0
- Qubes OS 3.2 LTS

to choose the former simply due to the LTS designation, rather than what I believe is the intended "Choose 4.0 unless your hardware forces you to choose 3.2", which needs *some* reading.

**Comment by marmarek** [comment]
I agree we should not market Qubes 3.2 as "LTS" as is. If anything, maybe "Extended Support Release" (as selected versions of Firefox).

**Comment by andrewdavidwong** [comment]
This was already done a long time ago; just forgot to close this issue. The [Qubes Release 3.2 download section](https://www.qubes-os.org/downloads/#qubes-release-3-2) clearly explains the extended release status.
