### ISSUE TITLE
Broadcom BCM43224

### ISSUE THREAD

**Issue by urfey** [QubesOS/qubes-issues#2799]
When I try initial setup,Qubes always freeze at networking setup.
So I didn't coufigure anything. Then I created sys-net and sys-firewall manually.
But when I started the VMs,it freezed again.

I think it happens because of my wireless device.My wireless device is Broadcom BCM43224.

How can I solve this problem?

**Comment by rtiangha** [comment]
Did you install the corresponding Broadcom firmware for that card? I don't have experience with that card, but if your sys-net VM is Debian based, instructions here:
https://wiki.debian.org/brcm80211

If it's Fedora based, it might be a bit harder and you might have to extract that firmware yourself. Try one of the Broadcom packages here first, though:
https://fedoraproject.org/wiki/Firmware

**Comment by urfey** [comment]
NO I didn't install yet. But I want to try.
But sys-net doesn't start at all. If I try to start,Qubes freezes.
Should I install the firmware into dom0?
Is it not dengerous to connect to internet directly from dom0?

**Comment by rtiangha** [comment]
That won't work. If your machine doesn't have an alternative network card, then you could try downloading the firmware package from another computer and copying it over with a USB flash drive or similar.

If you're starting from scratch, I'd suggest making sys-net a Debian-based VM. It looks like getting the proper firmware on that platform might be a little easier than it would be on Fedora.

**Comment by andrewdavidwong** [comment]
This is too localized for `qubes-issues`. Please consider posting this to the `qubes-users` mailing list instead. (You can read more about our mailing lists [here](https://www.qubes-os.org/mailing-lists/).)

`qubes-users` is intended for these sorts of questions and receives much more traffic, which means that your question is more likely to receive a response there.
