### ISSUE TITLE
Update the User FAQ on whether Qubes can run without Vt-x and/or Vt-d

### ISSUE THREAD

**Issue by ghost** [QubesOS/qubes-issues#2800]
To make it clear that Qubes 4.x wont run without them (in addition to the other requirement of SLAT)

https://www.qubes-os.org/doc/user-faq/#can-i-install-qubes-on-a-system-without-vt-x

https://www.qubes-os.org/doc/user-faq/#can-i-install-qubes-on-a-system-without-vt-d

**Comment by andrewdavidwong** [comment]
Done:
https://www.qubes-os.org/faq/#can-i-install-qubes-4x-on-a-system-without-vt-x-or-vt-d
