### ISSUE TITLE
Make it possible to use DispVM as UpdateVM

### ISSUE THREAD

**Issue by mig5** [QubesOS/qubes-issues#2801]
#### Qubes OS version (e.g., `R3.2`):

R3.2

It would be nice to have the ability to make the UpdateVM a Disposable VM. Say, to mitigate the (albeit rare) risk of some existing persistent malware in /rw on the relevant UpdateVM, interfering with handling the dom0 updates before they make their way back to dom0.

Do you think it's possible?

I tried already hacking a solution via piping the tar -C stuff to '/usr/lib/qubes/qfile-daemon-dvm qubes.VMShell dom0 red' but I couldn't get it to work. Maybe it's not possible given how restricted dom0 is in terms of how it can run commands on a dispVM (compared to the easier appVM -> dispVM)

**Comment by mig5** [comment]
In any case there is a simple way to set up a 'quasi'-disposable VM by writing a wrapper script around the main qubes-dom0-update. 

Leaving this here in case the idea is rejected but others still want to do something similar:

https://gist.github.com/mig5/407b2039ee99a5c8e75dc3b2cd524ede

**Comment by marmarek** [comment]
This will be trivial in Qubes 4.0...

**Comment by marmarek** [comment]
You can create semi-persistent DispVM there - the VM stays on the list, together with its name etc, but its state is discarded as soon as it is stopped.

**Comment by marmarek** [comment]
As said before, it is easy in Qubes 4.0:
```
qvm-create --class DispVM -t fedora-25-dvm -l orange disp-updatevm
qubes-prefs updatevm disp-updatevm
```
