### ISSUE TITLE
qvm-remove broken for secondary drive vms

### ISSUE THREAD

**Issue by qubenix** [QubesOS/qubes-issues#2803]
#### Qubes OS version (e.g., `R3.2`):

3.2

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):

Dom0

---

### Expected behavior:

VM will be rm'd from disk.

### Actual behavior:

Receive warning: `Warning: Cannot call rmtree on a symbolic link`. VM folder remains on secondary drive and link remains in folder '/var/lib/qubes/*vms/`

### Steps to reproduce the behavior:

1. Create AppVM.

2. Follow steps from [docs](https://qubes-os.org/doc/secondary-storage/) to move AppVM to secondary drive.

3. Attempt to remove AppVM either via gui or cli.

### General notes:

No mention of this in the docs.

---

**Comment by andrewdavidwong** [comment]
To clean this up, you can remove the symlink with `unlink` and `rm -r` the VM directory.

**Comment by unman** [comment]
Since this is no longer [the canonical way ](https://www.qubes-os.org/doc/secondary-storage/)of moving qubes to a separate pool, the issue does not arise in 4.0. I think this could be closed.
