### ISSUE TITLE
qubes-dom0-update ignores --releasever

### ISSUE THREAD

**Issue by GammaSQ** [QubesOS/qubes-issues#2810]
#### Qubes OS version: R3.2

---

### General notes:
I fixed the issue by replacing any 23 in /etc/yum.repo.d/fedora* with `$releasever` (in dom0), though that requires always passing `--releasever` to the UpdateVM. This could be easily fixed by implementing that in `qubes-dom0-update`, but my setup works for me for now.
Furthermore rpm key-import was required, which was done via a potentially insecure VM, so having a way to securely update the f24-key would be very nice!

It was very hard to figure out this one, since it's not even apparent that `--releasever` is dropped. Maybe annotate documentation to mention only fedora-23 repo is accessible in dom0 by default?

**Comment by marmarek** [comment]
There is no support for alternative dom0 version in given Qubes OS release. See here:
https://www.qubes-os.org/doc/supported-versions/#dom0

**Comment by GammaSQ** [comment]
It may be desirable to install packages for other fedora-versions anyway. E.g.: https://github.com/QubesOS/qubes-issues/issues/1648 (I am trying to emulate different architectures via stubdomains.)

In any case, it was not apparent to me that "supported version is" equals "no packages from other versions can be installed". I would be glad if that could be noted in the documentation.
