### ISSUE TITLE
Support for higher-resolution PDF conversion

### ISSUE THREAD

**Issue by tasket** [QubesOS/qubes-issues#2812]
#### Qubes OS version (e.g., `R3.2`):
R3.2

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):
all

---

### Expected behavior:
Sanitized document that is suitable for presentation in a professional setting. Generally this means around 300 ppi and greater.

### Actual behavior:
Conversion script uses pdftocairo default of 150 ppi, which can imapact readability and leave a poor impression.

### General notes:
Balancing quality with the increase in file size is no doubt important, however given the capacities of modern machines it may be better to use 300 ppi as a default for Qubes and allow the user to specify a different resolution on the command line.

Discussion is here:
https://groups.google.com/d/msgid/qubes-users/20170515224610.GA3920%40Personal-Email

---

**Comment by SamuelHentschel** [comment]
tasket, why did you close this?

**Comment by tasket** [comment]
@SamuelHentschel I must have hit the wrong button. Thanks for mentioning it!

**Comment by alimirjamali** [comment]
PR Submitted

A new `--resolution` option is added to `qvm-convert-pdf` to allow custom resolution. The new default is 600 ppi
