### ISSUE TITLE
Use VM name in error notifications

### ISSUE THREAD

**Issue by anoadragon453** [QubesOS/qubes-issues#2814]
#### Qubes OS version (e.g., `R3.2`):
R3.2

---

Earlier today I was updating to a new Linux Xen Kernel and since a few of my AppVMs were using an older kernel I kept receiving an error message pop up when trying to start them, even after changing their kernels in the Qubes-Manager GUI.

Turns out the issue lay not in the AppVMs I was starting, but starting the Proxy/NetVMs that they required. Typical n00b mistake I know, but if the error notification stating that "VM could not be started: Linux kernel blah blah..." contained the name of the VM that was generating that message instead of just "VM" it would have saved me about 15 min of pointless Googling :)

**Comment by andrewdavidwong** [comment]
The kernel issue sounds like #2757.

I take it that this issue is only about enhancing the text of dom0 notifications to include the name of the VM whenever a VM is mentioned.

**Comment by anoadragon453** [comment]
> I take it that this issue is only about enhancing the text of dom0
> notifications to include the name of the VM whenever a VM is mentioned

That's correct.

**Comment by andrewdavidwong** [comment]
I'm labeling this with `C: qubes-manager` since these notifications could be thought of as part of the "decomposed" Qubes Manager in 4.0 (#2132).

**Comment by jpouellet** [comment]
rename issue to "Use VM name in error messages"?

**Comment by anoadragon453** [comment]
Good idea.

**Comment by marmarta** [comment]
Better notifications for VM start errors have been added here: https://github.com/QubesOS/qubes-desktop-linux-manager/commit/fbc1ec175d53eed1e8864e0c6d32e97c000c26bf
