### ISSUE TITLE
Use createrepo_c instead of createrepo

### ISSUE THREAD

**Issue by cyrinux** [QubesOS/qubes-issues#2815]
#### Qubes OS version (e.g., `R3.2`):
I suggest use createrepo_c instead of createrepo, createrepo_c is faster.

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):
dom0

---

### Expected behavior:
createrepo_cmd = ["/usr/bin/createrepo_c"]

### Actual behavior:
createrepo_cmd = ["/usr/bin/createrepo"]

### Steps to reproduce the behavior:
createrepo_cmd = ["/usr/bin/createrepo_c"] in /usr/libexec/qubes/qubes-receive-update

### General notes:

---

#### Related issues:
https://groups.google.com/forum/#!searchin/qubes-devel/createrepo%7Csort:relevance/qubes-devel/BVyLF-Qsp4E/8U-ivqEmAQAJ

**Comment by jpouellet** [comment]
To check: Are the incoming packages already verified by this point? (Is this untrusted data? Untrusted package file names or such perhaps?)

If not: IMO we should prefer the normal createrepo (which is in written in python).

**Comment by cyrinux** [comment]
@jpouellet I'm not sure to correctly understand what you mean. But createrepo_c package is installed by default and come from default fedora repo.

**Comment by marmarek** [comment]
@jpouellet yes, at this point packages have signatures verified already
