### ISSUE TITLE
Attempt to restore a backup that is larger than free disk space does not yield error

### ISSUE THREAD

**Issue by random-7s31d** [QubesOS/qubes-issues#2817]
#### Qubes OS version (e.g., `R3.2`):
R3.2

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):
the backup is of a standalone HVM (Windows 7 64 bit)

---

### Expected behavior:
The drive that Qubes is installed on has around 80 GB of free disk space.
The backup file is over 200 GB in size.
When selecting the file in the Qubes backup manager to restore it, I expected that
- I would be offered to restore it to a different drive, OR
- the process would stop with an error message

### Actual behavior:
The process went on to restore the >200 GB backup on my primary drive with only 80 GB of free space.
I canceled the process when I noticed my 80 GB disk space decreasing. I do not know what would have happened if I didn't.

### Steps to reproduce the behavior:
1. Create a VM that is larger than the free disk space on the primary drive. To do this, you have to first follow these steps in the docs: https://www.qubes-os.org/doc/secondary-storage/
2. Create a backup of the VM.
3. Now, simply start restoring the backup.

### General notes:

Command line paranoid mode has been tried as well, as described in the ITL blog (https://blog.invisiblethings.org/2017/04/26/qubes-compromise-recovery.html).

It didn't start restoring the backup. Instead, the following error message showed, which I couldn't find on Google yet:

> `ERROR: error setting dependencies for VM vmnamehere: invalid literal for int() with base 10: 'none'`

---

#### Related issues:

none found.
Thank you ITL for descending from heaven to support all free men in the fight for personal IT security.
Anybody who hasn't donated yet, go [donate](https://www.qubes-os.org/donate/)!

**Comment by andrewdavidwong** [comment]
@marmarek may not consider this a problem in light of the decision on #2429.

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 has reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
