### ISSUE TITLE
Qubes Manager issue with concurrent qvm-start

### ISSUE THREAD

**Issue by Freezer94932** [QubesOS/qubes-issues#2819]
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable): dom0

I was trying to start multiple virtual machines at the same time by using qvm-start with the vm-name and an & at the end.
This produces an error-message within Qubes Manager, where you can click "ok". After that, Qubes Manager seems to work, but the gui does not update the state of the machines anymore. (No RAM- and CPU-usage and not even if a vm is running or not)
As far as I can tell (I did only two complete reboots so far), the problem solves itself by a reboot, but is reproducable if you again run multiple qvm-start instances concurrently.

---

### Expected behavior:
Qubes Manager should show the actual state of the vms.
### Actual behavior:
Qubes Manager shows the state the vms were in when it was started but does not update it anymore.
### Steps to reproduce the behavior:
Run the following as a script in dom0:
qvm-start test1 &
qvm-start test2 &
(Assuming that you have two vms called "test1" and "test2" of course.)
### General notes:

---

**Comment by andrewdavidwong** [comment]
I'm not sure what our attitude should be about things like this. I can imagine three different responses. Note that I'm not necessarily endorsing any of these. I'm just imagining them. :)

 * "Well, of course you can break stuff if you monkey around on the command-line."
 * "Qubes Manager and those commands should be more robust."
 * "Well, if doing that breaks things, just don't do it. Why would you even want to? Is there a use case for it?"

**Comment by marmarek** [comment]
I choose "b" :)
@Freezer94932 what exactly was that error message?

**Comment by marmarek** [comment]
Not specifically. Maybe a side effect of some other fix?

**Comment by MarioGeckler** [comment]
I tried to reproduce it with qubes-manager 3.2.5-1.fc23 as well as 3.2.0-1.fc23 but wasnt't ablte to dop so.

**Comment by andrewdavidwong** [comment]
@Freezer94932, are you still experiencing this? If so, what version of Qubes Manager are you using?

**Comment by unman** [comment]
@andrewdavidwong I cant reproduce this. I suggest closing in view of age and lack of response.
