### ISSUE TITLE
Lost new installed packages after restart virtual machine

### ISSUE THREAD

**Issue by adavidoaiei** [QubesOS/qubes-issues#2821]
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable): debian

---

### Expected behavior:
Some new installed packages shouldn't be lost after restart virtual machine
### Actual behavior:
Some new installed packages are lost after restart virtual machine
### Steps to reproduce the behavior:
Install Node.js, .Net Core. Chromium. restart the virtual machine, the installed packages are lost 
### General notes:
In this way is very hard to do software development on yours operating system, it's possible to have a security reason to behave in this way, but I think that you should be able to configure this behavior. 

---

**Comment by cyrinux** [comment]
Hi, You must install them in the template your vm use. Or use a standalone
vm.
Regards

**Comment by adavidoaiei** [comment]
It works.
