### ISSUE TITLE
Show inter-VM clipboard size

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#2825]
Tobias:
> I'd like to request for a feature which shows the exact clipboard size when hitting the magic hotkey Ctrl-Shift-C.

See full thread for details and discussion:
https://groups.google.com/d/topic/qubes-devel/ZVEuOngaII4/discussion

**Comment by itinerarium** [comment]
How is https://github.com/QubesOS/qubes-manager/pull/34?

Shows size in bytes if less than one KiB:
> Copied **40 bytes** to the clipboard.

Shows size in bytes and units (up to GiB), rounded to one decimal place, if more than one KiB:  
> Copied **1904 bytes (1.9 KiB)** to the clipboard.

**Comment by anoadragon453** [comment]
This seems to be implemented now (?) and can thus be closed.

**Comment by andrewdavidwong** [comment]
I expect(ed) it to be closed by qubesos-bot. @marmarek?

**Comment by marmarek** [comment]
There was no "Fixes" (or other [github recognised keyword](https://help.github.com/articles/closing-issues-using-keywords/)) in commit message.
