### ISSUE TITLE
Qubes Manager reports incorrect kernel version for VM

### ISSUE THREAD

**Issue by unman** [QubesOS/qubes-issues#2827]
#### Qubes OS version (e.g., `R3.2`):
R3.2

From qubes-users Fran reports:

> 1. Run qvm-prefs sys-net kernel
>  
> the above command is interesting because it gives 4.4.38-11 while Qubes
> manager gives 4.4.67-12

**Comment by jpouellet** [comment]
source: https://groups.google.com/d/msg/qubes-users/unDqbBa_k_Y/Z5UXSwS8AAAJ

I can't seem to reproduce though.

**Comment by marmarek** [comment]
Fixed in https://github.com/QubesOS/qubes-manager/commit/a2d0b128b734888a9a611d358f5579c87dbbb81e
https://github.com/QubesOS/updates-status/issues/65
