### ISSUE TITLE
Need help desperately....

### ISSUE THREAD

**Issue by tombulkusfatbird** [QubesOS/qubes-issues#2831]
#### Qubes OS version (e.g., `R3.2`):

Hello there,
I'd like to ask a question to this community before taking further action.
I'll buy a Librem 13 with pre installed Qubes if I can't sort this out.
I'll buy one even if i sort it but while i'm in US so it'll be a lifesaver without paying custom taxes.
Anyways,
I'm a long time Tails user and it's so simple but I wanted to switch to Qubes but as you already know it's a lot harder for a GNU/Linux newbie.
I think i'll be able to figure it out if i pass this last installation process.
Can you please look at this post on reddit and tell me what i'm doing wrong if you know the solution for this ?
HUGE THANKS IN ADVANCE,

https://www.reddit.com/r/Qubes/comments/6b484q/having_an_issue_in_the_last_part_of_the/?st=J35Y5Y0X&sh=83624631

Highlights for the ones who doesn't wanna browse reddit ; 
Having an issue in the last part of the installation • r/Qubes

Hi there dear experienced Qubes users, I'm a newbie about Qubes but a long time user of Tails and VMs. Trying to figure it out and to switch to...
I have tried everything for the last 2 months and i have tried this on all of my 3 PCs....
I did verify ISO and test media before the installation, first i have tried without verifying but same error occurred so then i deleted all and start again with verifying also checked the hardware list and i have tried with Dell Inspiron N5010 and Dell Xps15 and Hp Envy Desktop...
Facing with the same issue on every single machine i have tried also using ex SSD as an external HDD. I was thinking if it was related to WIFI cards these machines have....

Also the main issue can be this :

[Failed to start Kernel Modules ](http://imgur.com/a/8xowA) 

Please help me if you can.... I just don't wanna pay 2.600$ + 1.500$ as custom tax without knowing OS i'll use.
I just wanna practice some before getting deep into it.
BEST REGARDS great community.
FatBird.

**Comment by jpouellet** [comment]
You should probably ask this on the qubes-users [mailing list](https://www.qubes-os.org/mailing-lists/) instead.

**Comment by andrewdavidwong** [comment]
This is not appropriate for `qubes-issues`. Please send this to the `qubes-users` [mailing list](https://www.qubes-os.org/mailing-lists/) instead, as @jpouellet suggested.
