### ISSUE TITLE
QubesOS support for Windows

### ISSUE THREAD

**Issue by adavidoaiei** [QubesOS/qubes-issues#2833]
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable): windows

---

### Expected behavior:
sudo qubes-dom0-update qubes-windows-tools
should install qubes-windows-tools
### Actual behavior:
sudo qubes-dom0-update qubes-windows-tools
output
No package qubes-windows-tools available.
Error: unable to find a match.
### Steps to reproduce the behavior:
Run:
sudo qubes-dom0-update qubes-windows-tools
Output:
No package qubes-windows-tools available.
Error: unable to find a match.
### General notes:

I want to run Visual Studio using QubesOS support for Windows

The following documentation I am using:
https://www.qubes-os.org/doc/windows-appvms/

---

**Comment by 0spinboson** [comment]
Try qubes-dom0-update --enablerepo=qubes-dom0-current-testing qubes-windows-tools

**Comment by adavidoaiei** [comment]
This works but I don't have a Windows license, I will try too ReactOS but I don't if it knows to run Visual Studio.
