### ISSUE TITLE
Developer's documentation at readthedocs.io

### ISSUE THREAD

**Issue by woju** [QubesOS/qubes-issues#2834]
- [x] add QubesOS/qubes-core-admin as subproject (https://qubes-os.readthedocs.io/projects/core-admin/en/latest/)
- [x] merge QubesOS/qubes-doc#430
- [x] switch repo at readthedocs.org's admin panel
- [x] check hook at github
- [x] add CNAME or proxy at cloudflare
- [x] link at qubes-os.org/doc/
- [x] fix link to qubes-os.org/doc/ from readthedocs
---
- [x] write table of contents
- [x] adjust theme

**Comment by woju** [comment]
Cc: @andrewdavidwong @marmarek

**Comment by marmarek** [comment]
@woju please add CNAME to dev.qubes-os.org in readthedocs.org admin panel (DNS already done)

**Comment by woju** [comment]
done

**Comment by andrewdavidwong** [comment]
Regarding the item "link at qubes-os.org/doc/," I think we decided (in the email thread about this) to link *from* the main doc index (qubes-os.org/doc/) *to* each component (dev.qubes-os.org/some-component/), but *not* to link from the doc index to the subdomain landing page (dev.qubes-os.org). Since we don't have any component pages yet, there's nothing to link to yet.

**Comment by marmarek** [comment]
https://dev.qubes-os.org/projects/core-admin/en/latest/

**Comment by marmarek** [comment]
@woju please add also core-admin-client sub-project

**Comment by andrewdavidwong** [comment]
Added link from qubes-os.org/doc/ to core-admin documentation.

**Comment by woju** [comment]
> @woju please add also core-admin-client sub-project

Added: https://dev.qubes-os.org/projects/core-admin-client/ https://qubes-core-admin-client.readthedocs.io/

@andrewdavidwong Could you link it from https://qubes-os.org/doc/?

@marmarek: you'll get notifications about failed builds (I'll too).
@andrewdavidwong: Would you like to get e-mail notifications about failed builds of dev.qubes-os.org and/or some of the subrepos from RTD?
And question to you both: do we need single email alias for that? Assuming we'd get more of the repositories linked there, managing those notifications will get trickier.

**Comment by marmarek** [comment]
> And question to you both: do we need single email alias for that? Assuming we'd get more of the repositories linked there, managing those notifications will get trickier.

I'd say: send them to qubes-devel, but 1) I'm not sure if this is a good idea in the first place, 2) may need some tricky subscription setup (qubes-devel is moderated for non-members).
But what I want to say - we may need something like ML - publicly available - for notifications from such automatic services. This will also include mails with automatic tests results etc.

**Comment by andrewdavidwong** [comment]
@woju:
> @andrewdavidwong Could you link it from https://qubes-os.org/doc/?

Done: https://github.com/QubesOS/qubes-doc/commit/066bd62dc7563a105ee1b1b6079a3c2f7c9e3c66

> @andrewdavidwong: Would you like to get e-mail notifications about failed builds of dev.qubes-os.org and/or some of the subrepos from RTD?

If it's not actionable information for me, then no, but thank you for asking. :slightly_smiling_face: 

> And question to you both: do we need single email alias for that? Assuming we'd get more of the repositories linked there, managing those notifications will get trickier.

I think I agree with Marek on this. Something like https://github.com/QubesOS/updates-status/issues for mails?

**Comment by woju** [comment]
The notifications would be sent from `readthedocs@readthedocs.org` (with a Return-Path of `<bounce\+[0-9a-f.]*-qubes-devel=googlegroups.com@readthedocs\.org>`). Could you whitelist that address? If you'd need a message actually sent from this address, I can provoke one. :)

**Comment by marmarek** [comment]
> I think I agree with Marek on this. Something like https://github.com/QubesOS/updates-status/issues for mails?

Yes, something like this. I think this is generic question: do we want automated notifications on qubes-devel, or somewhere else?

**Comment by andrewdavidwong** [comment]
> Yes, something like this. I think this is generic question: do we want automated notifications on qubes-devel, or somewhere else?

Probably better to have it on a separate list so that it's opt-in for people who already subscribe to qubes-devel.

**Comment by andrewdavidwong** [comment]
@woju:

If someone goes to https://dev.qubes-os.org/, there's no useful content. There are three links listed on that page, but they're all either empty or 404. People who go to that page should at least be able to see a list of all the meaningful pages, which I guess are:

 - https://dev.qubes-os.org/projects/core-admin/en/latest/
 - https://dev.qubes-os.org/projects/core-admin-client/en/latest/

**Comment by woju** [comment]
@andrewdavidwong Some time ago I put links there, now I put link back to q-o.org/doc/, and the theme is consistent with all other docs. Should we close?

**Comment by andrewdavidwong** [comment]
:+1:
