### ISSUE TITLE
Intel GPU: Video-related kernel errors, GPU hang (only mouse works)

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#2836]
#### Qubes OS version (e.g., `R3.2`):

R4.0
Xen 4.8.1, linux 4.9.29-17

---

### Expected behavior:

No errors, no hangs

### Actual behavior:

A lot of errors like:
```
[drm:gen8_irq_hander [i915]] *ERROR* Fault errors on pipe A 0x00000100
```
And similarly in Xen messages:
```
[VT-D]DMAR:[DMA Read] Request device [0000:00:02.0] fault addr 29375f2000, iommu reg = ffff82c0009f2000
[VT-D]DMAR: reason 06 - PTE Read access is not set
```

### Steps to reproduce the behavior:

Boot Qubes 4.0 on Broadwell machine - in this case both Librem 13v1 and Librem 15v2.

### General notes:

This appears to be fixed by `iommu=no-igfx` Xen option. Since we don't have GUI VM yet, it doesn't have much security implications. Maybe we should enable it by default?

**Comment by marmarek** [comment]
@rootkovska what do you think about enabling iommu=no-igfx by default?

**Comment by rootkovska** [comment]
I agree it might be justified for 4.0, but we should make sure we won't forget to enable IOMMU for the GPU back in 4.1 when we (hopefully) will get a GPU-passthrough-based GUI domain. Perhaps creating a high-priority ticket for 4.1 milestone should be enough?

**Comment by marmarek** [comment]
Ok. #2841
