### ISSUE TITLE
Cannot install Qubes

### ISSUE THREAD

**Issue by alexschrod** [QubesOS/qubes-issues#2838]
#### Qubes OS version (e.g., `R3.2`): R3.2

---

### General notes: The machine is an MSI GS63VR 7RF Stealth Pro, if that helps. Also, I believe the error comes from [this place](https://fossies.org/linux/xen/xen/common/efi/boot.c#l_338) in the Xen code.

**Comment by marmarek** [comment]
This may be a problem with UEFI implementation on this machine. Have you tried legacy mode?
Anyway, better place to ask such questions is [qubes-users mailing list](https://www.qubes-os.org/mailing-lists/#qubes-users)

**Comment by JanPappert** [comment]
Experiencing exactly the same issue with a MSI B250M Mortar and was wondering if the OP was able to resolve the issue.

**Comment by alexschrod** [comment]
Unfortunately, no. My computer was a work computer, and I did not have time to troubleshoot the issue, I just had to have a working OS. My company allowed me to use QubesOS, but would not allow me to spend time on it past installing it. So now I'm stuck with using Windows at work instead, as it "works" (for some limited definition of "works").

**Comment by zylstra** [comment]
Just wanted to say that legacy mode is called CSM in some BIOSs.

**Comment by lucaszanella** [comment]
This "CSM" tip helped me a lot, had no idea that my firmware actually supported it
