### ISSUE TITLE
Error when copy a file from my virtual machine to dom0

### ISSUE THREAD

**Issue by adavidoaiei** [QubesOS/qubes-issues#2842]
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable): debian

---

### Expected behavior:
Run:

root@adavidoaiei:/home/user/Downloads# sudo qvm-run  --pas-io adavidoaiei  'cat ~/Down*/Win10*' > /home/adavidoaiei

Should copy a file from my virtual machine to dom0

### Actual behavior:
Run:
root@adavidoaiei:/home/user/Downloads# sudo qvm-run  --pas-io adavidoaiei  'cat ~/Down*/Win10*' > /home/adavidoaiei

I receive many errors:
Domain '--pass-io' doesn't exist (service qubes.VMShell called by domain adavidoaiei)
Request refused

### Steps to reproduce the behavior:

Run:
qvm-run --pass-io <src-vm> 'cat /path/to/file_in_src_domain' > /path/to/file_name_in_dom0
Took from:
https://www.qubes-os.org/doc/copy-from-dom0/

### General notes:

---

**Comment by unman** [comment]
You dont need to run this command under sudo.
Also, there are typos in your commands - it isn't clear to me whether these were what you actually typed or just typos in your report.
Also, I dont believe that you can use the command as you have done, to copy files with a wildcard to a directory.
Most importantly, I would guess from the output error that you are running this in a VM, and not in dom0. Can you try running the command in dom0 with a single named file, and report back?

**Comment by adavidoaiei** [comment]
I did what you said and it works, do you know QubesOS supports windows 10 I receive an error at installation:
Windows installation encountered an unexpected error. Verify that the installation sources are accessible, and restart the installation.
Error code: 0xE0000100

**Comment by unman** [comment]
On Fri, Jun 02, 2017 at 09:07:04AM -0700, Adavidoaiei Dumitru-Cornel wrote:
> I did what you said and it works, do you know QubesOS supports windows 10 I receive an error at installation:
> Windows installation encountered an unexpected error. Verify that the installation sources are accessible, and restart the installation.
> Error code: 0xE0000100
> 

I'm sorry I cant help with Windows.
I recall from the mailing lists that 10 CAN be installed as HVM, but I
dont think the Qubes tools are ready, in which case, resizing and
qvm-copy etc wont be available. But I'll defer to someone who actually
knows abut this.

**Comment by adavidoaiei** [comment]
Thanks for yours answer @unman, I am trying to run Visual Studio under QubesOS, it will be awesome to have all tools Linux, Visual Studio which I'd like and know better in one operating system QubesOS.

**Comment by andrewdavidwong** [comment]
@adavidoaiei:

@unman is correct. There are no Qubes Windows Tools for Windows 10 yet.

Since the copying-to-dom0 issue is resolved, I'll close this.
