### ISSUE TITLE
qubes-dom0-update root.img handling bug

### ISSUE THREAD

**Issue by tasket** [QubesOS/qubes-issues#2848]
#### Qubes OS version (e.g., `R3.2`):
R3.1, R3.2

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):
All

---

### Actual behavior:
Attempt to upgrade/reinstall template results in template lacking root.img when `yum` command does not retrieve a package for installation (e.g. user --action results in "Nothing to do").

### Steps to reproduce the behavior:
```
$ sudo qubes-dom0-update qubes-template-fedora-24 --action=upgrade
```

### General notes:
This concerns the specific template reinstall code in qubes-dom0-update.

Condition after `yum` command should take return code and root.img presence into account simultaneously. This should result in the template's original files being restored under the scenario where a user specifies a reinstall-type action for a template but yum retrieves no package.

Will post tested patch shortly.

---

#### Related issues:
#2061
#2527

**Comment by andrewdavidwong** [comment]
I see that https://github.com/QubesOS/qubes-core-admin-linux/pull/27 has already been merged, but I'll leave this open for builder tracking purposes.

CC @marmarek
