### ISSUE TITLE
Mounted drive icon hides the "restart required" icon in Qubes VM Manager

### ISSUE THREAD

**Issue by Shifterovich** [QubesOS/qubes-issues#2854]
#### Qubes OS version (e.g., `R3.2`):

R3.2

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):

dom0

---

### Expected behavior:

Icon saying a restart is required to reflect the recent template's filesystem changes

### Actual behavior:

Icon doesn't show when a "mounted drive" icon is showed.

### Steps to reproduce the behavior:

Update a TemplateVM's applications. Shutdown the TemplateVM. Mount a partition/drive to an AppVM that uses the TemplateVM as the template.

**Comment by andrewdavidwong** [comment]
Let's expand the existing #2226 to include this case.
