### ISSUE TITLE
Deleted Domain Still Appears On List

### ISSUE THREAD

**Issue by TopHatMan440** [QubesOS/qubes-issues#2855]
#### Qubes OS version (e.g., `R3.2`):

R3.2

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):

Whonix-ws

---

### Expected behavior:

To be deleted from the list when clicking on the home button

### Actual behavior:

Still appears

### Steps to reproduce the behavior:

1. Create new whonix-ws domain called "anon"
2. Delete after a couple of days
3. Create new one called "Tor"
4. Anon still appears with Tor when clicking the home button "top left", but it doesn't appear in the Qubes VM manager

### General notes:

Can't open the old domain or interact with it, it's just there doing nothing.
I'm also new to Qubes.

---

**Comment by andrewdavidwong** [comment]
Let's generalize the existing #2689 to cover this.
