### ISSUE TITLE
VM names should not allow keywords

### ISSUE THREAD

**Issue by svenssonaxel** [QubesOS/qubes-issues#2857]
#### Qubes OS version (e.g., `R3.2`):
R3.2

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):
N/A

---

### Steps to reproduce the behavior:
Use the VM Manager to create a new NetVM with the name "default".

### Expected behavior:
The operation fails, similarly to the names "none", "true" and "false".

### Actual behavior:
The NetVM is created. This leads to an ambiguity in the following command:
qvm-prefs -s my-new-vm netvm default

### General notes:
To avoid similar mistakes in the future, maybe keywords should be uniformly distinguished from VM names, e.g. begin with _ or $, similarly to the current policy file format that uses $any and $dispvm. This would also provide backward compatibility with backups if new keywords are introduced in the future.

---

**Comment by marmarek** [comment]
Fixed in https://github.com/QubesOS/updates-status/issues/293
