### ISSUE TITLE
kernel 4.9 vs disposable VM online network change

### ISSUE THREAD

**Issue by Zrubi** [QubesOS/qubes-issues#2859]
#### Qubes OS version (e.g., `R3.2`):
Qubes 3.2
xen: 4.6.5

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):
Fedora 24
VM kernel 4.9.31
---

### Expected behavior:
Able to change the netvm of a running disposable VM

### Actual behavior:
The Qubes manager shows it has been changed, however the VM has no networking. (as the default netvm is none)
I got this error in the VM:

kernel: EXT4-fs error (device xvdd): ext4_lookup:1583: inode #53358: comm systemd-udevd: deleted inode referenced: 59938
kernel: EXT4-fs (xvdd): previous I/O error to superblock detected
kernel: blk_update_request: I/O error, dev xvdd, sector 2
kernel: blk_update_request: I/O error, dev xvdd, sector 2
kernel: Buffer I/O error on dev xvdd, logical block 1, lost sync page write

And no network device appears in the VM.

while the same DVM works if I choose the VM kernel 4.4.x
kernel: xen_netfront: Initialising Xen virtual ethernet driver

And networking is working as expected.

### Steps to reproduce the behavior:
- set the initial netvm to none
- regenerate the DVM template
- set the VM kernel to 4.9.31
- start a new DVM
- try to change the netvm of the new running DVM

### General notes:
the used template is up to date from all testing and security-testing repos are also enabled.

---

**Comment by marmarek** [comment]
Try regenerating DVM template _after_ changing the kernel.

**Comment by Zrubi** [comment]
Issue solved then.

Maybe the template regeneration should be forced after the a kernel change?

**Comment by marmarek** [comment]
Or savefile should also include kernel version (and properly report it). Which one is better?

**Comment by Zrubi** [comment]
While I don't see the background of the real problem here, If we can skip the "slow" template regeneration that would be nice.

**Comment by marmarek** [comment]
The problem is that changing kernel also change disk image mounted as /lib/modules. And when savefile is generated, it is mounted there - so changing the image underneath result in what you see - kernel is confused.

**Comment by Zrubi** [comment]
So this problem not 4.9 related but affecting the "changing VM kernel" feature in general...

**Comment by marmarek** [comment]
Yes, exactly.
