### ISSUE TITLE
maltego is not usable in qubes R3.2

### ISSUE THREAD

**Issue by jonosterman** [QubesOS/qubes-issues#2864]
#### Qubes OS version (e.g., `R3.2`):
R3.2

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):
fedora-23, ubuntu-16.04

---

### Expected behavior:
install and start maltego (Java Application). App should be usable (AppVM).

### Actual behavior:
graphics do redraw when resizing the windows, menu does not work.

### Steps to reproduce the behavior:
* ensure java is installed 
* download and install maltego classic (free) from https://www.paterva.com/web7/downloads.php#tab-2 (deb and rpm available).
* start maltego from terminal

### General notes:
maltego is widely use java app used for security assessments (available on Kali, etc.). works on all other linux / windows I tried so far. I expect some compatibility issues with qubes.

---

**Comment by schnurentwickler** [comment]
Can you provide a screenshot of the redraw? Is this tool using some graphic acceleration?

**Comment by jonosterman** [comment]
Hi schnurentwicker,

Maltego is a Java application so it should not use advanced hardware acceleration afaik. 

I will provide you with a screenshot asap.

Best regards

**Comment by jonosterman** [comment]
![screenshot_2017-07-07_22-52-16](https://user-images.githubusercontent.com/839126/27976535-36e5a9ea-6367-11e7-86fe-9c3e9c451366.png)

**Comment by jonosterman** [comment]
Matlego provide a deb file to install and [test](https://www.paterva.com/malv4/classic/Maltego.v4.0.16.9722.deb)

**Comment by schnurentwickler** [comment]
From what I know about java, you probably have some issues with the graphics driver qubes provide and some special graphics support java needs.
As long as java cannot be used virtualized without a os (like https://www.virtualizationpractice.com/virtualize-java-without-an-operating-system-5639/), it could be a driver or some unwriteable location on the data drive. Try to use an HVM in qubes for your application and java.

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 has reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
