### ISSUE TITLE
Qubes 3.2: No Internet Connection, neither with Wi-Fi, neither with Ethernet.

### ISSUE THREAD

**Issue by helpplshelp** [QubesOS/qubes-issues#2870]
#### Qubes OS version (e.g., `R3.2`):
THIS CONCERNS QUBES 3.2 (latest update, downloaded from the website 3  
days ago). 

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):
sys-net

---

### Expected behavior:
1-Once the ethernet cable is plugged in the proper ethernet port of the computer, it should display "Connection Established" with a notification in top right corner;
2-Once the Wi-fi is "Connected", I should be able to ping google.com with the command "ping google.com -c 5" inside the sys-net terminal.

### Actual behavior:
1-Once the ethernet cable is plugged in, absolutely nothing happens. And on system boot, once the desktop is loading (and if Wi-Fi is disconnected), the notification "Disconnected - the network connection has been disconnected" appears in the top right corner.
2-Once the wi-fi connection is established (without any problems at all), it simply doesn't work, like if it was disconnected. In fact when I go to sys-net terminal and execute the command "ping google.com -c 5" it waits a few seconds before displaying "ping: unknown host google.com".

### Steps to reproduce the behavior:
Simple Installation of the OS, choosing only first 2 options during last Qubes configuration (sys-whonix not installed, and neither torification for updates)

### General notes:
WHAT YOU SHOULD KNOW, AND WHAT I HAVE TRIED:
1-The ethernet cable, Wi-Fi card, Ethernet card, of the computer are all perfectly working;
2-Both Ethernet and Wi-fi cards are attached to sys-net VM, under 'devices' as it should be;
3-Both the Wi-Fi card and the Ethernet card are recognized by Qubes, in fact, heres the output of 2 known commands:

"ifconfig" output below. NOTE: I MODIFIED the inet6 address, and the 		ethernet addresses from "Vif2.0" and "wlp0s1" respectively, I would prefer to keep them private. :

	lo: flags=73 mtu 65536 inet 127.0.0.1 netmask 255.0.0.0 inet6 ::1 prefixlen 		128 scopeid 0x10 loop txqueuelen 1 (Local Loopback) RX packets 36 bytes 	4008 	(3.9 KiB) RX errors 0 dropped 0 overruns 0 frame 0 TX packets 36 	 bytes 4008 	(3.9 KiB) TX errors 0 dropped 0 overruns 0 carrier 0 		collisions 0

	vif2.0: flags=4163 mtu 1500 inet 10.137.1.1 netmask 255.255.255.255 		broadcast 0.0.0.0 inet6 fd72::dasd:sdas:gfgd:gffw prefixlen 64 scopeid 0x20 		ether dt:fd:nb:qw:as:fd txqueuelen 32 (Ethernet) RX packets 130 bytes 6464 		(6.3 KiB) RX errors 0 dropped 0 overruns 0 frame 0 TX packets 44 bytes 2472 		(2.4 KiB) TX errors 0 dropped 0 overruns 0 carrier 0 collisions 0

	wlp0s1: flags=4163 mtu 1500 inet 192.168.178.76 netmask 255.255.255.0 		broadcast 192.168.178.255 inet6 og45::9n32:j7qq:ofk4:pd92 prefixlen 64 		scopeid 0x20 ether x3:p8:l0:b7:po:33 txqueuelen 1000 (Ethernet) RX packets 		238 bytes 56207 (54.8 KiB) RX errors 0 dropped 0 overruns 0 frame 0 TX 		packets 278 bytes 27217 (26.5 KiB) TX errors 0 dropped 0 overruns 0 carrier 		0 collisions 0

"lspci" output below. NOTE: I MODIFIED the Ltd. RTL identification strings, I would prefer to keep them private. :

	00:00.0 Ethernet controller: Realtek Semiconductor Co., Ltd. 			RTL0000/0000/0000 PCI Express Gigabit Ethernet Controller (rev 0c) 		00:01.0 Network controller: Realtek Semiconductor Co., Ltd. RTL000000 		802.11ac PCIe Wireless Network Adapter

4-This problem has been present since the first installation, occured 3 days ago, in the meanwhile I tried to fix it asking on reddit/r/qubes/ and on whonix forum;
5-From the same usb containing Qubes installation, I have installed qubes in another computer of mine(laptop), and on it I did not have such problems (and I used the same ethernet cable).
6-I'm not sure this is as it should be or not: during installation (which I have repeated in the last 3 days literally 8-9 times across different pcs.), at any point, I came across a Network setup configuration like in every other operating system I have ever used (linuxes and windows), and a guy on reddit told me he went through something like that.
7-NOT a very important point, you can skeep this one if you want.
I noticed that during boot on my laptop pc (the one where internet works perfectly) when it asks for the passphrase, it loads a proper window, with background and box to type in the passphrase. In my desktop computer instead (the one with the internet problem), this does not occur, I have to type the passphrase directly in the boot. All of this made me think that Qubes installation is everytime overfitted for the current hardware.

### TELL ME WHAT YOU NEED TO SEE AND I'LL POST.
PLEASE HELP ME FIX THIS, QUBES WITHOUT INTERNET IS POINTLESS, and you'll help me get rid of this powerful headache I have right now.

---
currently I have other threads about this very same problem, written by me, here are the links:
https://groups.google.com/forum/?_escaped_fragment_=topic/qubes-users/sEh2LQFiOxI#!topic/qubes-users/sEh2LQFiOxI
https://www.reddit.com/r/Qubes/comments/6j8vbq/qubes_internet_connection_not_working_neither/
https://forums.whonix.org/t/internet-connection-not-working-on-3-2-qubes-all-network-cards-perfectly-attached-working-and-recognized-i-beg-for-help/4060/2

**Comment by andrewdavidwong** [comment]
This is too localized for `qubes-issues`. Since you have already posted on `qubes-users`, please be patient in waiting for a response. If you haven't already, you should read more about our mailing lists [here](https://www.qubes-os.org/mailing-lists/).

`qubes-users` is intended for these sorts of questions and receives much more traffic, which means that your question is more likely to receive a response there.
