### ISSUE TITLE
building qubes from example r3.2 config fails

### ISSUE THREAD

**Issue by yomimono** [QubesOS/qubes-issues#2875]
#### Qubes OS version (e.g., `R3.2`):

I'm attempting to build r3.2 from Fedora 25.

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):

The failure is in building `vmm-xen-vm` when attempting to refresh the local repository for Fedora 24.

---

### Expected behavior:

`make qubes-os-iso` creates an ISO I can use to install QubesOS.

### Actual behavior:

The build fails:

```
-> Building vmm-xen (xen.spec) for fc24 vm (logfile: build-logs/vmm-xen-vm-fc24.log)
--> build failed!
/home/user/qubes-builder/qubes-src/builder-fedora//update-local-repo.sh fc24
sudo BACKEND_VMM=xen chroot /home/user/qubes-builder/chroot-fc24 sh -c 'cd /home/user/qubes-src/vmm-xen; dnf  --refresh -y update'
Failed to set locale, defaulting to C
Error: Failed to synchronize cache for repo 'fedora'
/home/user/qubes-builder/qubes-src/builder-fedora/Makefile.fedora:102: recipe for target 'refresh-update.dnf' failed
make[2]: *** [refresh-update.dnf] Error 1
Makefile.generic:147: recipe for target 'packages' failed
make[1]: *** [packages] Error 1
Makefile:209: recipe for target 'vmm-xen-vm' failed
make: *** [vmm-xen-vm] Error 1
```

### Steps to reproduce the behavior:

* clone `qubes-builder`
* edit the DEPENDENCIES variable in Makefile to refer to `python2-sh` rather than `python-sh` (likely a Fedora 25-ism)
* `make install-deps`
* copy example-configs/qubes-os-r3.2.conf to builder.conf
* `make qubes-os-iso`

### General notes:

I'm really trying to build a Qubes with a Fedora 25 dom0 with the `qubes-os-master.conf` included in `example-configs`, but I discovered this problem attempting to do so.  It reproduces on the r3.2 build which might be cleaner for troubleshooting.

**Comment by marmarek** [comment]
> Error: Failed to synchronize cache for repo 'fedora'

Looks like a network connection issue, unfortunately common with Fedora mirrors. I'd simply retry.

**Comment by marmarek** [comment]
BTW qubes-os-master.conf is about Qubes 4.0. For Qubes 3.2, get qubes-os-r3.2.conf and start from there (for example change DIST_DOM0).

**Comment by yomimono** [comment]
I've retried several times over the past week and travelled to places with high-quality connections, and the problem persists.  Is there a caching effect somewhere that would cause this to continue after failing once?

**Comment by marmarek** [comment]
I don't know - for me retrying works. You can try removing chroot environment to rebuilt it from scratch - `make clean-chroot`.

**Comment by yomimono** [comment]
`make clean-chroot` resulted in a complete rebuild rather than an immediate failure.  I've been away from computers for a couple of weeks and in the meantime tried the recently-released Qubes 4 preview, which installed successfully, can bring up a GRUB menu, and allows for editing/selection, but once something is chosen displays only a flashing cursor for a few seconds and then reboots hard.  I'm unlikely to pursue building my own Qubes at this point, so I'll close this.
