### ISSUE TITLE
xc: error: linux_gntshr_share_pages: ioctl failed (28 = No space left on device): Internal error

### ISSUE THREAD

**Issue by surveillance401** [QubesOS/qubes-issues#2877]
#### Qubes OS version (e.g., `R3.2`):
R3.2
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):
All TemplateVMs

---
I knew i shouldn't question at github devel issues area..... But i wait 12 hours at google-user group and nobody answer....  

### Actual behavior:
xc: error: linux_gntshr_share_pages: ioctl failed (28 = No space left on device): Internal error
And i check https://github.com/QubesOS/qubes-issues/issues/1191 this issue already.... 
Is not /tmp/ size problem.....

It seem is xc_gntshr_unmap problems....:
https://lists.xen.org/archives/html/xen-devel/2014-08/msg02680.html
https://lists.gt.net/xen/devel/345310

This is my own disk record....

```
Filesystem         1K-blocks    Used Available Use% Mounted on
/dev/mapper/dmroot 480487288 5308996 455511196   2% /
/dev/xvdd             388480  152868    215132  42% /lib/modules/4.4.67-12.pvops.qubes.x86_64
devtmpfs              146352       0    146352   0% /dev
tmpfs                1048576       0   1048576   0% /dev/shm
tmpfs                 153232    2520    150712   2% /run
tmpfs                   5120       0      5120   0% /run/lock
tmpfs                 153232       0    153232   0% /sys/fs/cgroup
tmpfs                1048576      36   1048540   1% /tmp
/dev/xvdb            1998672  105760   1876528   6% /rw
tmpfs                  30648       8     30640   1% /run/user/1000
```

This is df -h record.......
```
Filesystem          Size  Used Avail Use% Mounted on
/dev/mapper/dmroot  367G  3.1G  349G   1% /
/dev/xvdd           380M  150M  211M  42% /lib/modules/4.4.67-12.pvops.qubes.x86_64
devtmpfs            304M     0  304M   0% /dev
tmpfs               1.0G     0  1.0G   0% /dev/shm
tmpfs               311M  4.5M  307M   2% /run
tmpfs               5.0M     0  5.0M   0% /run/lock
tmpfs               311M     0  311M   0% /sys/fs/cgroup
tmpfs               1.0G   36K  1.0G   1% /tmp
/dev/xvdb           2.0G  4.3M  1.9G   1% /rw
tmpfs                63M  8.0K   63M   1% /run/user/1000
```

### Steps to reproduce the behavior:
I try resize root disk size by those steps:
https://www.qubes-os.org/doc/resize-disk-image/
https://www.qubes-os.org/doc/resize-root-disk-image/
but i seem not root disk size problems.....
### General notes:

---

#### Related issues:
https://github.com/QubesOS/qubes-issues/issues/1191

**Comment by rustybird** [comment]
Don't know what is causing the error in your case, but I've seen the exact same message when spawning hundreds of small qrexec connections between two VMs in a short time. In that case, it was fixable by increasing the value of `/sys/module/xen_gntalloc/parameters/limit` (I don't remember in which of the two VMs, maybe both).

**Comment by surveillance401** [comment]
@rustybird 
I tried before ,used echo 10000 > /sys/module/xen-gntalloc/parameters/limit to try resolved this problem....
But did helped my out..... 
And the true problem is i reinstall VMs...  And add disk size only 10GB at once...... And problem resolved.... I added 500GB at once......
https://www.qubes-os.org/doc/resize-root-disk-image/
Make sure changes in the TemplateVM between reboots didn’t exceed 10G.
