### ISSUE TITLE
SMAP cause Linux HVM boot failure

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#2881]
#### Qubes OS version (e.g., `R3.2`): R4.0

The effect is that QubesDB fails to start, `qubesdb-daemon` in dom0 try to connect, immediately fails and try to reconnect. When this happens, QubesDB socket in dom0 for given domain is not available and access to it from qubesd fails with:
```
qubesdb.DisconnectedError: QubesDB disconnected
```
or 
```
qubesdb.Error: (2, 'No such file or directory')
```
At the same time, VM try to start, QubesDB startup time out (1m30s), then every service depending on information retrieved from QubesDB (including `qubes-sysinit.service`) fails too. Pretty much unusable VM.

More details in [upstream report](http://markmail.org/thread/muff45duy6ag4lik). The fix is already [submitted upstream](http://xen.markmail.org/thread/szchdqfg5dx7nptt), but it will take time until the patch will be available in distribution kernel packages (especially Debian).

**Comment by iamahuman** [comment]
Can we reenable this yet?

**Comment by marmarek** [comment]
I guess so, Debian jessie should not be a thing anymore.
