### ISSUE TITLE
Build fails - make get-sources fails on "additional sources for desktop-linux-kde"

### ISSUE THREAD

**Issue by unman** [QubesOS/qubes-issues#2889]
Attempting to run 'make get-sources' in qubes-builder fails - 

> --> Downloading additional sources for desktop-linux-kde...
> warning: Macro expanded in comment on line 86: # %%check
> 
> --> Verifying the sources...
> warning: Macro expanded in comment on line 86: # %%check
> 
> sha512sum: kde-baseapps-15.12.3.tar.xz: No such file or directory
> kde-baseapps-15.12.3.tar.xz: FAILED open or read
> sha512sum: WARNING: 1 listed file could not be read
> ../Makefile.common:65: recipe for target 'verify-sources' failed
> make[2]: *** [verify-sources] Error 1
> Makefile:10: recipe for target 'verify-sources' failed
> make[1]: *** [verify-sources] Error 1
> Makefile:189: recipe for target 'desktop-linux-kde.get-sources-extra' failed
> make: *** [desktop-linux-kde.get-sources-extra] Error 2

**Comment by marmarek** [comment]
What do you have in builder.conf - especially GIT_PREFIX and BRANCH?

**Comment by unman** [comment]
Cloned builder, ran setup.
Selected 3.2 / QubesOS Stable/ Templates only/Debian
builder.conf has:
RELEASE := 3.2
GIT_PREFIX := QubesOS/qubes-

Reliably fails - work round is to delete that package, which I wouldnt use anyway.
Quite prepared to accept this is just for me.

**Comment by marmarek** [comment]
Just tries in a fresh instance and cannot reproduce. Maybe some restrictive firewall (and wget failure not handled earlier)?

**Comment by freddierice** [comment]
I just ran into this issue as well. The file `kde-baseapps-15.12.3.tar.gz` is never downloaded since there is an error in `desktop-linux-kde/Makefile`. The sub-folder `qubes-menu` does not exist. Removing `qubes-menu` from `SUBDIRS` fixes this issue.
