### ISSUE TITLE
Split-GPG notifications do not disappear automatically

### ISSUE THREAD

**Issue by anoadragon453** [QubesOS/qubes-issues#2897]
![2017-07-08-095440](https://user-images.githubusercontent.com/1342360/27987503-82a6d118-63c3-11e7-934a-0aea0e20b707.png)

#### Qubes OS version (e.g., `R3.2`):
R3.2

Using i3 as windowing manager.

---

### Expected behavior:
The notification from Qubes' `split-gpg` daemon, the one that pops up the notification 'Keyring access from domain: xxx' should appear for a couple seconds after notifying the user of GPG key access, then disappear automatically.

### Actual behavior:
The notification seems to be persistent and never disappears, causing the user (me) to have to manually click it to get it to go away. This can get annoying while browsing emails or mailing lists for example as it appears every time the GPG daemon is accessed (i.e. every time a signed/encrypted email is opened).

It's worth noting that if there's more than one instance of the notification, the other instances do go away automatically, but the last instance never disappears.

### Steps to reproduce the behavior:
1. Set up [split-gpg](https://www.qubes-os.org/doc/split-gpg/)
2. Do something in a VM that accesses your GPG keys
3. Notice the notification warning you about this access never disappears automatically

### General notes:
Firefox notifications (and notifications from other applications) do disappear after 1-2s, so I believe this is a problem with Qubes' implementation rather than the notification system itself.

**Comment by andrewdavidwong** [comment]
I know that this has been an issue for a long time. As a workaround, many of us have simply [disabled the notifications entirely](https://groups.google.com/d/topic/qubes-users/ebgXRk5OMEw/discussion).

**Comment by anoadragon453** [comment]
@andrewdavidwong Ah, thanks for the heads up.

What's nice is that after being pointed to that file, I can simply add `--expire-time=1000` to the end of the `notify-send` command to make notifications disappear as expected!

I've created a [pull request](https://github.com/QubesOS/qubes-app-linux-split-gpg/pull/9) in the split-gpg repo to fix this.
