### ISSUE TITLE
AppVMs have max vcpus assigned by default

### ISSUE THREAD

**Issue by Yethal** [QubesOS/qubes-issues#2900]
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable): fedora-25

---

### Expected behavior: 
Each AppVM has 2 vcpus assigned

### Actual behavior: 
Each AppVM has maximum avilable number of vcpus assigned (12 on my machine)

### Steps to reproduce the behavior:
1. Install Qubes 4.0 prerelease
2. Boot into it
3. view qvm-prefs of any AppVM

### General notes:

---

**Comment by marmarek** [comment]
This is intended behavior, to not allow any single AppVM block all the machine. If you need some more computing power in a specific AppVM, you can adjust the setting.

**Comment by Yethal** [comment]
I don't quite understand. How does assigning all vcpus to all AppVMs at once help prevent DoS attack (I assume this is what you meant by blocking the machine) ?

**Comment by marmarek** [comment]
Ah, sorry, I've mixed "actual bevavior" with "expected behavior" in your report. It should be 2 by default.
