### ISSUE TITLE
Gnome-terminal and Nautilus do not start in Fedora 25 template

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#2901]
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable): fedora-25

This applies to test image Qubes-DVD-x86_64-20170706.iso

---

### Expected behavior:

Gnome applications works normally

### Actual behavior:

Gnome-terminal error with:
```
Error constructing proxy for org.gnome.Terminal:/org/gnome/Terminal/Factory0: Error calling StartServiceByName for org.gnome.Terminal: GDBus.Error:org.freedesktop.DBus.Error.TimedOut: Failed to activate service 'org.gnome.Terminal': timed out (service_start_timeout=12000ms)
```
Nautilus produce similar message.

### Steps to reproduce the behavior:

`qvm-run -p fedora-25-based-vm gnome-terminal`

### General notes:

Looks like the problem with default locale being non-UTF-8.

**Comment by 0spinboson** [comment]
Aha, so this was due to a bug -- good to know, the behavior confused me. :)
