### ISSUE TITLE
Setup script in Qubes-builder fails to find dependencies

### ISSUE THREAD

**Issue by anoadragon453** [QubesOS/qubes-issues#2910]
#### Qubes OS version (e.g., `R3.2`):
R3.2

---

### Expected behavior:
* `make install-deps` installs all required dependencies.
* Build continues as normal.

### Actual behavior:
`make install-deps` *does* install all dependencies but the `setup` script **always** fails to find the `python-sh` package. Build fails with the following:

```
package python-sh is not installed
wget-1.18-3.fc25.x86_64
ERROR: call 'make install-deps' to install missing dependencies
Makefile:199: recipe for target 'check-depend.rpm' failed
make: *** [check-depend.rpm] Error 1
```

### Steps to reproduce the behavior:
1. Clone qubes-builder from master.
2. Copy default config for R3.2 to `builder.conf`
3. Run `./setup` and see as it fails to find python-sh, attempts to install, but it's already installed.
4. Hack around until you can get the build started.
5. Watch as it yet again fails about an hour in stating that `python-sh` is not installed.

### General notes:
I believe this may be an issue with Fedora's repos. It seems the setup script uses the following command to check if `python-sh` is installed:

```
rpm -q python-sh
```

Running this on my system I get:

```
[user@personal qubes-builder]$ rpm -q python-sh
package python-sh is not installed
[user@personal qubes-builder]$ 
```

It can't find it even though it is installed, however:

```
[user@personal qubes-builder]$ rpm -q python2-sh
python2-sh-1.12.14-1.fc25.noarch
[user@personal qubes-builder]$
```

It can find the `python2-sh` package, which is what is installed when one requests `python-sh`. 

This is running Fedora 25, so likely a problem with the latest version switching to python3 by default.

Oddly enough just changing `python-sh` to `python2-sh` in the script still reports that it's not installed...

Building on Fedora 25 (maybe only for R3.2?) seems to thus be broken for all templates.

**Comment by paraschetal** [comment]
Changing python-sh to python2-sh in the [Makefile](https://github.com/QubesOS/qubes-builder/blob/master/Makefile#L33) worked for me on Fedora 25.

**Comment by paraschetal** [comment]
@andrewdavidwong this issue should be fixed now

**Comment by anoadragon453** [comment]
Yes it seems like it, thanks!
