### ISSUE TITLE
{yum,deb,ftp}.qubes-os.org certificate expired

### ISSUE THREAD

**Issue by rustybird** [QubesOS/qubes-issues#2920]
Trying to access https://yum.qubes-os.org/:

> The **certificate expired on 07/17/2017 11:59 PM**. The current time is 07/18/2017 08:19 AM.

> This site uses HTTP Strict Transport Security (HSTS) to specify that Tor Browser may only connect to it securely. As a result, it is not possible to add an exception for this certificate.

**Comment by marmarek** [comment]
Thanks for heads up. Fixed.
