### ISSUE TITLE
"sudo qubes-dom0-update @kde-desktop-qubes" yields "Group does not exist"

### ISSUE THREAD

**Issue by BiteMyBucket** [QubesOS/qubes-issues#2921]
#### Qubes OS version (e.g., `R3.2`):
R3.2
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):
dom0

---

### Expected behavior:
Having KDE installed and running in dom0

### Actual behavior:
Error message

### Steps to reproduce the behavior:
1. Run "sudo qubes-dom0-update @kde-desktop-qubes"
2. Be given error message of group not existing and then quitting.

### General notes:
It's a very fresh install, so I haven't mucked about anything and managed to mess something up myself, I think; though, it should be added I've no knowledge of dnf/yum, so it may be something trivial I just don't know about.

---

#### Related issues:
#2889 maybe?

**Comment by andrewdavidwong** [comment]
Possibly related: #2663.

**Comment by marmarek** [comment]
Fixed (there was broken symlink to comps.xml file).

**Comment by andrewdavidwong** [comment]
Reopening due to apparent regression reported in #6202.

**Comment by andrewdavidwong** [comment]
There's a forum thread about this:

https://qubes-os.discourse.group/t/installing-and-running-kde-as-de/1513/

In it, @unman points out that:

> KDE is being refactored for 4.1 and currently is not available.

I think this may be a reference to #5904.

**Comment by th5** [comment]
I'm experiencing this on a fresh install of 4.1.0 rc1.
