### ISSUE TITLE
Consider mounting /rw with "noatime" mount flag

### ISSUE THREAD

**Issue by cfcs** [QubesOS/qubes-issues#2933]
#### Qubes OS version (e.g., `R3.2`):
R3.2

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):
`fedora-23` and `debian-8`, also `/` in `dom0`

---

### Expected behavior:
Unnecessary disk writes are kept to a minimum, ie `/rw` being mounted with `-o noatime`.

### Actual behavior:
Atime for every inode in every vm is updated often because /rw is mounted `relatime`.

### Steps to reproduce the behavior:
```
mount | grep '^/' | fgrep --color time
```
### General notes:
from `man mount`:

```
       relatime
              Update  inode  access  times  relative to modify or change time.
              Access time is only updated if the previous access time was ear‐
              lier  than  the  current  modify  or  change  time.  (Similar to
              noatime, but it doesn't break mutt or  other  applications  that
              need  to know if a file has been read since the last time it was
              modified.)

              Since Linux 2.6.30, the kernel defaults to the behavior provided
              by   this   option  (unless  noatime  was  specified),  and  the
              strictatime option is required to obtain traditional  semantics.
              In  addition, since Linux 2.6.30, the file's last access time is
              always updated if it is more than 1 day old.
```

So this means that every day, `fgrep -r` or `git grep` will update metadata on everything they touch, resulting in a large amount of writes, which in turn means more data to backup every day. I personally believe atime is pretty useless, but if there are arguments for this, please do speak up!

---

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.

**Comment by woju** [comment]
@andrewdavidwong Unless decided otherwise, I think this could remain open.

**Comment by marmarek** [comment]
I think `relatime` is a good compromise between `atime` and `noatime`. It will update access time only if the file was modified after it was accessed last time. According to your example @cfcs, it will update atime only the first time out call `grep` on a given time (unless you modify the file). If you grep frequently on files you don't modify often, most of the time atime will not be adjusted.

So, I think this can stay as it is.

**Comment by cfcs** [comment]
@marmarek For immutable things like templates this is still kind of unclean though, since there the changes don't get written back?

My interpretation of this line `In  addition, since Linux 2.6.30, the file's last access time is always updated if it is more than 1 day old.` is that it will make a new write if the current atime is `> 24h`, which means it will be doing this every day, for every VM, and every dispVM that reads many files when starting (like a browser VM?) -- that seems kind of bad to me?

**Comment by marmarek** [comment]
> @marmarek For immutable things like templates this is still kind of unclean though, since there the changes don't get written back?

For `/` in template-based VMs it indeed makes sense. There is `noatime` already.

As for `/rw`, it may be a good idea for individual setups, when it's conscious decision, but not necessary as a distribution default. This may lead to weird issues with some applications. From what I see, no distribution set `noatime` for /home by default.

**Comment by cfcs** [comment]
Ah, fair enough. :-)

**Comment by andrewdavidwong** [comment]
According to my understanding of this discussion, this issue should remain closed as "won't do." If I've misinterpreted the discussion, or if anyone has a new reason for why this should be done, please leave a comment, and we'll be happy to take another look. Thank you.

**Comment by auroraanon38** [comment]
> I think `relatime` is a good compromise between `atime` and `noatime`. It will update access time only if the file was modified after it was accessed last time. According to your example [@cfcs](https://github.com/cfcs), it will update atime only the first time out call `grep` on a given time (unless you modify the file). If you grep frequently on files you don't modify often, most of the time atime will not be adjusted.
> 
> So, I think this can stay as it is.

I think with Copy-on-Write filesystems [like btrfs](https://btrfs.readthedocs.io/en/latest/btrfs-man5.html#mount-options-generic) the read/write amplification problem is sufficiently impactful that [relatime is nowhere near enough](https://lwn.net/Articles/499293/).

It get significantly worse the more qubes are active at a given time as well. It is very noticeable on systems using HDDs.
