### ISSUE TITLE
qubesos.github.io: travis builds ~/old_site using merge head instead of base

### ISSUE THREAD

**Issue by jpouellet** [QubesOS/qubes-issues#2935]
If the PR is for a submodule, everything goes as expected.

If the PR is for qubesos.github.io itself, then ~/old_site is built using the merge HEAD (newer commit) instead of the merge base (older commit).

This is evident through the diffs, where diffs for PRs against qubesos.github.io itself only ever contain something like:
```
--- /home/travis/old_site/feed.xml	2017-07-22 20:26:33.810322999 +0000
+++ ./_site/feed.xml	2017-07-22 20:27:10.958322999 +0000
@@ -6,8 +6,8 @@
 </description>
     <link>https://www.qubes-os.org/</link>
     <atom:link href="https://www.qubes-os.org/feed.xml" rel="self" type="application/rss+xml"/>
-    <pubDate>Sat, 22 Jul 2017 20:25:59 +0000</pubDate>
-    <lastBuildDate>Sat, 22 Jul 2017 20:25:59 +0000</lastBuildDate>
+    <pubDate>Sat, 22 Jul 2017 20:26:36 +0000</pubDate>
+    <lastBuildDate>Sat, 22 Jul 2017 20:26:36 +0000</lastBuildDate>
     <generator>Jekyll v3.4.5</generator>
```

---

Example of non-empty travis diff against qubes-doc (demonstrating **correct** behavior):
- commit: https://github.com/QubesOS/qubes-doc/pull/447/files
- diff of generated sites: https://travis-ci.org/QubesOS/qubes-doc/builds/254355442#L721

Example of empty travis diff against qubesos.github.io (demonstrating **incorrect** behavior):
- commit: https://github.com/QubesOS/qubesos.github.io/pull/113/files
- diff of generated sites: https://travis-ci.org/QubesOS/qubesos.github.io/builds/255251131#L708

**Comment by jpouellet** [comment]
@marmarek I've attempted various solutions similar to what I'd tried earlier in my initial travis PR & initial spell-checking PR, but everything feels like an ugly hack. Help requested.

[Spell checking has been re-written](https://github.com/jpouellet/qubesos.github.io/commits/spell2-squashed) and is now only blocking on this. It works fine for qubes-doc (baseline [PR](https://github.com/qubesos-bot-jpo/qubes-doc/pull/5) & [log](https://travis-ci.org/qubesos-bot-jpo/qubes-doc/builds/256446011?utm_source=github_status&utm_medium=notification), misspelling [PR](https://github.com/qubesos-bot-jpo/qubes-doc/pull/4) & [log](https://travis-ci.org/qubesos-bot-jpo/qubes-doc/builds/256445279?utm_source=github_status&utm_medium=notification)), but not for qubesos.github.io ([misspelling PR](https://github.com/qubesos-bot-jpo/qubesos.github.io/pull/5/files) & [false-negative log](https://travis-ci.org/qubesos-bot-jpo/qubesos.github.io/builds/256449785?utm_source=github_status&utm_medium=notification)).

**Comment by marmarek** [comment]
The important difference is: in qubes-doc (and others) we have this in .travis.yml:
```
install: git clone https://github.com/${TRAVIS_REPO_SLUG%%/*}/qubesos.github.io ~/qubesos.github.io
script: ~/qubesos.github.io/_utils/travis.sh
```
But on qubesos.github.io we have just:
```
script: ./_utils/travis.sh
```
So, in the later case, we use sources already downloaded by travis, but for qubes-doc we download "old" sources explicitly.
Let me try to fix this asymmetry: https://github.com/QubesOS/qubesos.github.io/pull/114
Example fixed diff: https://travis-ci.org/marmarek/qubesos.github.io#L742
