### ISSUE TITLE
Freezing a running VM

### ISSUE THREAD

**Issue by IPv777** [QubesOS/qubes-issues#2936]
#### Qubes OS version (e.g., `R3.2`):
R3.2
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):
All

---

### Expected behavior:
Please add a feature to freeze a running VM, and restore it later

**Comment by jpouellet** [comment]
From https://github.com/QubesOS/qubes-issues/issues/832#issuecomment-285956463 @marmarek wrote:
> Yes, shutdown is much easier to implement. For suspend/restore you need not only to restore VM internal state (memory etc - handled by Xen tools), but also all related VM connections - networking, GUI, qrexec services running when VM was hibernated etc.
Also, VM suspend support in Xen/Linux historically was quite buggy - this is for example why Disposable VMs have only 1 vCPU assigned, otherwise it crashed frequently. Probably situation have improved since previous tests, but still I suspect it will be less stable.

**Comment by andrewdavidwong** [comment]
Possibly a `wontfix` for the reason @jpouellet cited.

**Comment by captain** [comment]
That's a shame, as this seems like a fantastic feature to have.  These days of runaway web plugins sucking up 100% CPU and massive amounts of memory, the ability to PAUSE the entire thing, to enable other activities, and then resume it, once you're ready to have it continue, is extremely attractive.  Maybe there's some other way to implement similar behavior....

**Comment by jpouellet** [comment]
Ah, suspending and pausing are not the same thing. I thought you meant serializing all VM state to disk and resuming execution at a later time. Just unscheduling it (to not consume CPU, but still reside in memory) is easy, and can be done with the pause button in qubes manager.

**Comment by marmarek** [comment]
Or qvm-pause
