### ISSUE TITLE
qvm-usb/qubesutils not discovering all usb devices

### ISSUE THREAD

**Issue by olim5** [QubesOS/qubes-issues#2938]
#### Qubes OS version (e.g., `R3.2`):
R3.2

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):
All

---

### Expected behavior:
Show all usb devices connected to sys-usb.

### Actual behavior:
Shows only usb devices with usb id format of [0-9]+-[0-9]+.[0-9]+ (sys-usb:2-1.6) Not discovered are devices like sys-usb:2.1.1.3 or even sys-usb:2-1.1.2.1 .

### Steps to reproduce the behavior:
Just connect devices with longer usb id trees:
[user@sys-usb ~]$ usbip list -l
 - busid 2-1.1.1 (0461:4d16)
   Primax Electronics, Ltd : unknown product (0461:4d16)

 - busid 2-1.1.2.1 (0458:004c)
   KYE Systems Corp. (Mouse Systems) : Slimstar Pro Keyboard (0458:004c)

 - busid 2-1.1.3 (0c4b:0300)
   Reiner SCT Kartensysteme GmbH : cyberJack pinpad(a) (0c4b:0300)

 - busid 2-1.3 (147e:2016)
   Upek : Biometric Touchchip/Touchstrip Fingerprint Sensor (147e:2016)

 - busid 2-1.6 (04f2:b217)
   Chicony Electronics Co., Ltd : Lenovo Integrated Camera (0.3MP) (04f2:b217)

### General notes:
Modifying regex "usb_device_re" to  "re.compile(r"^[0-9]+-[0-9]+(_[0-9]+_?[0-9]*)?$")" in 
/usr/lib64/python2.7/site-packages/qubes/qubesutils.py solved the issue at least for sys-usb:2.1.1.3 usb ids.

---

**Comment by andrewdavidwong** [comment]
Is this on Qubes R3.2?

**Comment by olim5** [comment]
Yes, it is R3.2 .

**Comment by marmarek** [comment]
Already [fixed for Qubes 4.0](https://github.com/QubesOS/qubes-app-linux-usb-proxy/commit/5c0306061e8cacbe05726b86a381edd640fd750d) but indeed the fix worth backporting to Qubes 3.2

**Comment by marmarek** [comment]
Oh well, it's already in `release3.2` branch too: https://github.com/QubesOS/qubes-core-admin/pull/106
Updated package was not released.

**Comment by marmarek** [comment]
Done: https://github.com/QubesOS/updates-status/issues/149
