### ISSUE TITLE
Build of 3.2 fails - make get-sources fails on "additional sources for desktop-linux-xfce4"

### ISSUE THREAD

**Issue by unman** [QubesOS/qubes-issues#2942]
Clean system, no firewall restrictions.
Clone qubes-builder
Run ./setup - select 3.2, NO to template-only, builder-debian only

make get-sources fails on "additional sources for desktop-linux-xfce4":
sha256sum: garcon-0.4.0.tar.bz2: No such file or directory

And indeed that file is not present, although I can manually download it from the source given in spec file.

**Comment by marmarek** [comment]
I guess you don't have `spectool` installed (part of rpmdevtools package). We ship a copy of it in builder-rpm (previously builder-fedora), I'll adjust the Makefile to use that copy.

**Comment by marmarek** [comment]
It was already there - if you have builder-fedora/builder-rpm enabled. I think the bug is allowing dom0 build without builder-rpm plugin.
