### ISSUE TITLE
Laggy right-click in Qubes VM Manager

### ISSUE THREAD

**Issue by IPv777** [QubesOS/qubes-issues#2944]
#### Qubes OS version (e.g., `R3.2`):
R3.2

---

### Actual behavior:
When a VM menu in expanded, the right-click on an item is like a left-click, please remove this feature because it make some display bugs like freezes
### Steps to reproduce the behavior:
Spam the right click when moving the mouse

**Comment by andrewdavidwong** [comment]
I can't seem to reproduce this behavior. Can you provide some further details on the display bugs or freezing you're experiencing? It would also help to understand the intended usecase that this interferes with.

**Comment by andrewdavidwong** [comment]
Closing this for now due to the lack of response. If you revisit the matter in the future, or if anyone would like the issue to remain open, please leave a comment, and we'll be happy to reopen this. Thank you.
