### ISSUE TITLE
Cannot update dom0 kernel

### ISSUE THREAD

**Issue by taoeffect** [QubesOS/qubes-issues#2945]
#### Qubes OS version (e.g., `R3.2`):

R3.2

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):

fedora-23

---

While trying to get some other screen resolution other than 800x600 on an ASUS Q325 thin laptop thing by following [these instructions](https://groups.google.com/forum/#!searchin/qubes-users/display$20resolution%7Csort:relevance/qubes-users/BUe4tFfERtA/buazJHIzCQAJ), it all fails.

### Expected behavior:

I follow "Kernel Upgrade" instructions [here](https://www.qubes-os.org/doc/software-update-dom0/#how-to-update-software-in-dom0) by running `sudo qubes-dom0-update --enablerepo=qubes-dom0-unstable kernel kernel-qubes-vm`, and it does whatever it's supposed to.

### Actual behavior:

It runs the command on sys-firewall, there's a red error message that says `xrandr: Failed to get size of gamma for output default`, followed by a Traceback (manually typed out, hope you appreciate the effort I'm going into for this):

```
Traceback (most recent call last):
  File "/bin/qvm-run", line 222, in <module>
    main()
  File "/bin/qvm-run", line 217, in main
    r = vm_run_cmd(vm, cmdstr, options)
  File "/bin/qvm-run", line 66, in vm_run_cmd
    gui = options.gui, filter_esc = options.filter_esc)
  File "/usr/lib64/python2.7/site-packages/qubes/modules/000QubesVm.py", line 1645, in run
     self.start_guid(verbose = verbose, notify_function = notify_function)
  File "/usr/lib64/python2.7/site-packages/qubes/modules000QubesVm.py", line 1821, in start_guid
    monitor_layout = qubes.monitorlayoutnotify.get_monitor_layout()
  File "/usr/lib64/python2.7/site-packages/qubes/monitorlayoutnotify.py", line 65, in get_monitor_layout
    int(output_params['width_mm']) / 10)
ZeroDivisionError: integer division or modulo by zero
```

That part was in white.

On the very next line, in red:

```
sed: can't read /var/lib/qubes/dom0-updates/etc/yum.conf: No such file or directory
Config error: Can not read configuration: /var/lib/qubes/dom0-updates/etc/yum.conf
```

### Steps to reproduce the behavior:

Err, what I said above.

### General notes:

I think I got it to "work" yesterday by opening up a package manager thing in thing in the sys-firewall vm and doing an update check, and then running the update command above again, but it did not seem to update the kernel, and the additional instructions of running `sudo grub2-mkconfig -o /boot/grub2/grub.cfg` are impossible to follow because `grub2-mkconfig` is not a command that exists in dom0.

---

**Comment by taoeffect** [comment]
This is so strange, if I simply run the command a second time it starts doing things and saying: "Package kernel-1000:4.4.14-11.pvops.qubes.x86_64 is already installed, skipping" yada yada,

Then it says a bunch more stuff, then:

```
Install 2 Packages

Total download size: 85 M
Installed size: 85 M
Downloading Packages:
```

And it sits there for a while... too long.

Don't think I've got time to wait for it to finish as I've gotta run, but if I remember correctly the last time it did this it ended with "nothing to be done" or something like that, and after rebooting it still didn't show any other resolution other than 800x600 in the Display prefs, and I don't think it updated the kernel.

`uname -a` currently says `Linux dom0 4.4.14-11.. etc`

If when I get back it does anything different than it did last time I got it to get to this point, then I'll update or close the issue. But I'm pretty sure it won't.

**Comment by taoeffect** [comment]
Oh, it just finished, with error:

```
Error: Error downloading packages:
   Cannot download rpm/kernel-4.8.12-12.pvops.qubes.x86_64.rpm: All mirrros were tried
```

Which doesn't make sense because the machine is connected to the Internet and I can load websites.

**Comment by 0spinboson** [comment]
Try current-testing, contains 4.9 kernel.

**Comment by taoeffect** [comment]
OK, good news, but first: trying `current-testing` didn't help, I just got the same bizarre error about it being unable to download the packages after trying all mirrors.

So I simply tried on a different connection (with the original command to fetch unstable) and magically it worked!

Sorta, it told me that I had to run the command with additional flags that were not mentionedi n the documentation: `--best --allowerasing`

So the final command that worked (on a different connection) was:

```
sudo qubes-dom0-update --enablerepo=qubes-dom0-unstable kernel kernel-qubes-vm --best --allowerasing
```

Upon rebooting the display automatically picked the highest resolution and I breathed a sigh of relief. I updated the template VM to the latest fedora as well and now the command connections to the repositories on even the original connection. Again, bizarre, don't know what's going on with that.


So I'm not going to close this issue because it seems that I ran into various bugs along the way; I'll leave this open so that the various problems that I ran into can be addressed hopefully in a future update, and also just to document all the weirdness I ran into.

**Comment by marmarek** [comment]
Regarding original issue, looks like #2348, which was fixed long time ago. Maybe you haven't installed updates?

**Comment by taoeffect** [comment]
> Regarding original issue, looks like #2348, which was fixed long time ago. Maybe you haven't installed updates?

I think I ran that after I updated dom0, so no, I don't think it's been fixed, and even supposing it were, it still shouldn't happen in the released version that's on the website.

There's also:

- the issue of updating the docs to add `--best --allowerasing`
- the bizarre issue with it failing to download the update from all mirrors

**Comment by PsychicCat** [comment]
had the exact same problem with 3.2, fixed it thanks to you @taoeffect!

**Comment by marmarek** [comment]
> the issue of updating the docs to add --best --allowerasing

No, the correct things is to add `--action=update`.
