### ISSUE TITLE
Feature Request - VM Grouping in Qubes VM Manager.

### ISSUE THREAD

**Issue by awood4929** [QubesOS/qubes-issues#2946]
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable): N/A

---

### General notes:

---

#### Related issues:  A distant related issue - when selecting a NetVM, in VM settings, it would be nice if the list would also be in Alphabetic order as well.  It seems to be in some random order.  As well, if the fields in the VM Manager could be re-sized in the title bar (Name, State, Template, etc.

Love the product ... Thank you for your dedication on our behalf.  Andy

**Comment by andrewdavidwong** [comment]
This has already been suggested here: https://github.com/QubesOS/qubes-issues/issues/2132#issuecomment-238826619

Also see this discussion thread:
https://groups.google.com/d/topic/qubes-users/8ttWCrvx3TQ/discussion

I'll add a link to this issue to the comment above.
