### ISSUE TITLE
qubes-vm-settings fails for restored VMs

### ISSUE THREAD

**Issue by kulinacs** [QubesOS/qubes-issues#2947]
#### Qubes OS version (e.g., `R3.2`):
R4.0-rc1
---

### Expected behavior:
qubes-vm-settings loads for restored VMs

### Actual behavior:
Error causes failure

### Steps to reproduce the behavior:

* Restore VMs from backup (in my case, R3.2)
* Run qubes-vm-settings on a restored vm

#### Fix
**BE CAREFUL EDITING /var/lib/qubes/qubes.xml by hand!**

Replace

    <features>
      <feature name="services.meminfo-writer">1</feature>
    </features>

with:

    <features/>

for all restored VMs in `/var/lib/qubes/qubes.xml` and restart.

#### Error

TypeError: setChecked(self, bool): argument 1 has unexpected type 'str'
at line 9
of file /usr/bin/qubes-vm-settings.

----

line: self.vm.features.get('services.meminfo-writer', True))
func: __init_advanced_tab__
line no.: 454
file: /usr/lib/python3.5/site-packages/qubesmanager/settings.py

----

line: self.__init_advanced_tab__()
func: __init__
line no.: 89
file: /usr/lib/python3.5/site-packages/qubesmanager/settings.py

----

line: settings_window = VMSettingsWindow(vm, qapp, args.tab)
func: main
line no.: 999
file: /usr/lib/python3.5/site-packages/qubesmanager/settings.py

----

line: load_entry_point('qubesmanager==4.0.4', 'console_scripts', 'qubes-vm-settings')()
func: <module>
line no.: 9
file: /usr/bin/qubes-vm-settings

---

**Comment by marmarek** [comment]
About workaround - use qvm-features tool for this.

**Comment by ktmdan** [comment]
Quick workaround for a lot of vms

for qube in `qvm-ls --format simple | cut -f1 -d ' '`; do qvm-features $qube services.meminfo-writer -D; done

**Comment by marmarek** [comment]
On Mon, Oct 02, 2017 at 08:15:30AM -0700, Dan wrote:
> Quick workaround for a lot of vms
> 
> for qube in `qvm-ls --format simple | cut -f1 -d ' '`; do qvm-features $qube services.meminfo-writer -D; done

Pro tip: `qvm-ls -O name` for just VM names (and a "NAME" header...).

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?
