### ISSUE TITLE
Impossible to start a VM with cdrom attached

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#2951]
#### Qubes OS version (e.g., `R3.2`): R4.0

Here are two issues:
1. `qvm-block attach vmname some-vm:loop0 -o devtype=cdrom` fails with `Unsupported option devtype`
2. After fixing above, VM startup fails with `Backend for CD devices on HVM guests must be Qdisk` (in libxl-driver.log)

**Comment by jcholsap** [comment]
That sounds right. You first need to start your vm and then attach /dev/sr0. dom0 manages that block device. also the driver stack only supports reading, no -rw.
