### ISSUE TITLE
Application removed from menu cannot be added back

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#2952]
#### Qubes OS version (e.g., `R3.2`): R4.0

---

### Steps to reproduce the behavior:
1. Open VM settings
2. Remove application from the list, click OK
3. Check if application is really removed from the menu.
4. Open VM settings
5. Add the same application back, click OK
6. Check if application is present in the menu

### Expected behavior:

Application added back

### Actual behavior:

Application still missing.

### General notes:

[Report on qubes-users](https://groups.google.com/d/msgid/qubes-users/f8f9c633-b757-436d-9365-5f403952bcf8%40googlegroups.com)

**Comment by marmarek** [comment]
Also, changing VM color does not update the menu. I belive it is the same bug.
Both issues can be fixed with:
```
xdg-desktop-menu install ~/.local/share/qubes-appmenus/VMNAME/apps/*.{directory,desktop}
```

**Comment by mannp** [comment]
@marmarek Your workaround works to reinstate ALL applications available to that vm, rather than only the ones selected in the applications tab.

Is there a command to update the menus based on that application tab list?

**Comment by mannp** [comment]
Is this fixed as the workaround is a half measure not a solution.

**Comment by marmarek** [comment]
> Is this fixed as the workaround is a half measure not a solution.

What do you mean? With the fix referenced above (https://github.com/marmarek/qubes-desktop-linux-common/commit/e45e760236a3d2c81c1e887d82675ed2b08761b7) application menu is correctly updated when needed.

**Comment by mannp** [comment]
I was looking at the xdg-desktop-menu command and it still creates all menu items regardless of whether the app exists in the selected list.

I did not realise qvm-appmenus --update was the correct command to recreate the menus and not xdg-desktop-menu, as that still has the same effect.

**Comment by jpouellet** [comment]
Somehow my system .desktop files got deleted. The cause was probably just me being an idiot, but in case it's not and someone in the future comes across this issue by searching for that problem symptoms (as I just did), you can restore the system menu items with:
```
sudo qubes-dom0-update --action=reinstall $(rpm -qal | grep /usr/share/applications | xargs rpm -qf | sort -u)
```
