### ISSUE TITLE
Booting 4.0-rc1 fails at Loading initial ramdisk

### ISSUE THREAD

**Issue by JPL1** [QubesOS/qubes-issues#2953]
### General notes:
I have installed Qubes on a 128G USB 3.0 memory stick plugged into an Intel i7 desktop (HP Elitedesk) with UEFI turned off in the BIOS. Verified the download and checked the media integrity before installing. The same setup works fine with R3.2. Not sure why 4.0-rc1 won't boot.

**Comment by marmarek** [comment]
Try removing `iommu=no-igfx` option from xen parameters - you can access it from GRUB menu (press 'e', edit appropriate line, then boot with Ctrl-x).
To make change persistent, edit /etc/default/grub in dom0, then execute `sudo grub2-mkconfig -o /boot/grub2/grub.cfg`

**Comment by JPL1** [comment]
Yes that worked - thanks @marmarek

**Comment by prusnak** [comment]
I see the same issue on Intel i5 machine (UEFI turned off) and that the proposed fix indeed fixes the problem.

**Comment by marmarek** [comment]
TBH, I'm not sure if better remove `iommu=no-igfx` (implement #2841 earlier) , then add instruction how to add it on affected systems, or keep it (which is the option merging QubesOS/qubes-vmm-xen#11).
cc @rustybird

**Comment by rustybird** [comment]
I guess QubesOS/qubes-vmm-xen#11 should be merged either way, for those users experiencing graphics corruption (i.e. who would have to add `iommu=no-igfx` manually if it is removed) on a platform where `force_iommu` is enabled automatically.

**Comment by marmarek** [comment]
QubesOS/qubes-vmm-xen#11 merged.

**Comment by rharmonson** [comment]
I had the same issue on i7 with EFI disabled, due to an infinite reboot with the cubes installer, and the proposed solution of removing `iommu=no-igfx` worked.
