### ISSUE TITLE
whonix doesn't install 4.0-rc1

### ISSUE THREAD

**Issue by SejmL** [QubesOS/qubes-issues#2954]
#### Affected TemplateVMs Whonix

---

**Comment by alexis-** [comment]
I confirm this issue on a Lenovo x series laptop.
To dispel any confusion, this happens when installing from scratch:

- Qubes installer is run, with Whonix option selected (default)
- After reboot, during the configuration phase, the options to set up Whonix are unavailable like so : 
  - [ ] "Whonix not installed"
    - [ ] "Route applications traffix and updates through Tor anonymity network [experimental]"

**Comment by Mayeu** [comment]
I can also confirm that this happens with the Librem 13v2 from Purism.

**Comment by marmarek** [comment]
The issue is tracked here: https://phabricator.whonix.org/T710

**Comment by tlaurion** [comment]
Is there a plan to distribute whonix under http://yum.qubes-os.org/r4.0/templates-community/ soon?

**Comment by marmarek** [comment]
Yes, since that issue linked above is solved, we'll upload the template there soon. We just need some testing whether everything works with 4.0

**Comment by marmarek** [comment]
Status update: after some testing, it looks some more changes are needed.
This PR: https://github.com/Whonix/qubes-whonix/pull/4

**Comment by adrelanos** [comment]
Marek Marczykowski-Górecki:
> Status update: after some testing, it looks some more changes are needed.
> This PR: https://github.com/Whonix/qubes-whonix/pull/4
> 

Status update: that was discussed and done
inhttps://phabricator.whonix.org/T697

**Comment by cartman4** [comment]
It seems to be available at  http://yum.qubes-os.org/r4.0/templates-community/ but when i try to install whonix-gw or whonix-ws i get following error:
warning: /var/lib/qubes/dom0-updates/var/cache/yum/x64_64/4.0/qubes-templates-community-30baa4f451d0ec38/packages/qubes-template-whonix-ws-3.1.0-201709140243.noarch.rpm: header v4 RSA/SHA256 Signature, key ID 4022e393: NOKEY
Curl error(37): couldnt read a file:// file for file:///etc/pki/rpm-gpg/RPM-GPG-KEY-qubes-4.0-templates-community [couldnt open file /etc/pki/rpm-gpg/RPM-GPG-KEY-qubes-4.0-templates-community]

**Comment by marmarek** [comment]
Yes, key is indeed missing there. There will be updated qubes-release package in few hours.

**Comment by tlaurion** [comment]
@marmarek : newer qubes-release not uploaded!

**Comment by marmarek** [comment]
It is there, in testing repository, `qubes-release-4.0-0.2`. There is a problem with automatic key import (#3096), but key file itself is installed.

**Comment by marmarek** [comment]
Whonix templates already in repository, and scheduled to be included with 4.0rc2

**Comment by adrelanos** [comment]
Invitations for Qubes-Whonix 13 testers on Qubes R4 RC1:

https://forums.whonix.org/t/experimental-qubes-whonix-13-in-qubes-r3-rc1-please-test
