### ISSUE TITLE
How to attach a block device in R4.0-rc1?

### ISSUE THREAD

**Issue by JPL1** [QubesOS/qubes-issues#2955]
### Actual behavior: Can't find any equivalent functionality to the old Qubes Manager when it comes to attaching a block device. 

CLI command in docs is wrong `qvm-block -a work dom0:sda3` https://www.qubes-os.org/doc/usb/
should be  `qvm-block a 'work' dom0:sda3`

This works but there should be a GUI function, correct?

**Comment by marmarek** [comment]
> This works but there should be a GUI function, correct?

Yes, there is an applet, next to the one with Q logo.

**Comment by JPL1** [comment]
Ha yes - I'm blind!
