### ISSUE TITLE
How to create a proxyVM or a netVM in R4.0-rc1 ?

### ISSUE THREAD

**Issue by JPL1** [QubesOS/qubes-issues#2956]
### General notes:
I want to create a VPN VM  - in the old days I would use a proxy or NetVM for this, install my VPN client and that would be that. How do I do this in 4.0? Do I need to resort to the CLI?

**Comment by marmarek** [comment]
Select "provides network" in new VM dialog.

**Comment by JPL1** [comment]
Thanks
