### ISSUE TITLE
Qubesd broken after rebooting dom0, updated fedora 25

### ISSUE THREAD

**Issue by 0spinboson** [QubesOS/qubes-issues#2960]
#### Qubes OS version (e.g., `R3.2`):
4.0rc1

![tmp_img_20170803_0939111419151626](https://user-images.githubusercontent.com/21077532/28911639-77f5cf8a-7831-11e7-8a22-6e6a55fa4d01.jpg)

Rebooted machine, got this. No extra repo enabled beyond dom0 current testing. 
First time I updated dom0 since installing 4rc1
### Expected behavior:
Updating dom0 doesn't kill qubes-manager

**Comment by 0spinboson** [comment]
The list of packages available atm
![tmp_img_20170803_110120999613296](https://user-images.githubusercontent.com/21077532/28914228-3d533e94-783b-11e7-977c-ccaa3a937fb8.jpg)

**Comment by marmarek** [comment]
Updates list look normal (upstream Fedora updates). Previous error means something gone wrong with qubesd - see logs: `sudo journalctl -u qubesd`.

**Comment by 0spinboson** [comment]
After reinstalling rc1 a second time, I haven't run into this again (and didn't screenshot log before doing so).

**Comment by 0spinboson** [comment]
Seems I spoke to soon. Here you go. 
![2017-08-03 13 35 59](https://user-images.githubusercontent.com/21077532/28920123-c09ac744-7850-11e7-98ab-c4a9d6357249.jpg)

**Comment by marmarek** [comment]
Is this right after update? What version of qubes-core-dom0 package do you have?

**Comment by 0spinboson** [comment]
4.0.4

**Comment by marmarek** [comment]
Try restarting the service: `systemctl restart qubesd`

**Comment by 0spinboson** [comment]
That works, and I can start sys-net and -firewall now, but can't open a terminal window.

**Comment by marmarek** [comment]
Try `qvm-start-gui --all`

**Comment by 0spinboson** [comment]
That also works

**Comment by marmarek** [comment]
Do you have terminal now?

**Comment by 0spinboson** [comment]
Yes.

**Comment by 0spinboson** [comment]
After playing around a bit, a few remarks:
1. (obviously) this fix isn't persistent across reboots.
2. I have to run the qvm-start-gui every time I run something / start a new VM, to get those GUIs to show up.
3. qvm-start-gui --all also 'fixes' another issue I was running into, namely that GUIs weren't showing up properly, after I'd started/shutdown VMs a number of times. (I also start seeing warnings about thin provisioning assigning more space than this SSD has -- I posted a screenshot with the error in the rc1 thread in qubes-users).

**Comment by marmarek** [comment]
Ah, there is qvm-start-gui --all --watch. Check also `~/.xsession-errors` - maybe there is some hint why it crashed.

**Comment by 0spinboson** [comment]
[xsession-errors.txt](https://github.com/QubesOS/qubes-issues/files/1198345/xsession-errors.txt)
a few errors at the top here, but since they lack timestamps I don't know what they correlate with.

**Comment by 0spinboson** [comment]
small update: even with 'qvm-start-gui --all --watch' running, it still misses updates (I get 1 or more from these messages "Unable to init server: could not connect: connection refused" / "failed to parse arguments: cannot open display" / "Failed to connect to Mir: Failed to connect to server socket"), at which point I have to run 'qvm-start-gui --all manually to get it working again, after which it's fine).

**Comment by marmarek** [comment]
Mir?! From where you've got it?

**Comment by 0spinboson** [comment]
Xenial-based standalone vm.

**Comment by marmarek** [comment]
(continuation of discussion from https://github.com/QubesOS/updates-status/issues/176)
Can you post service start order from both failed and succeed boot? You can get it with:
```
journalctl -b -0 | grep 'systemd.*Start'
```
And use `-b -1` for previous boot, -2 for the boot before etc.

**Comment by 0spinboson** [comment]
[boot1.txt](https://github.com/QubesOS/qubes-issues/files/1217237/boot1.txt) < success
[boot0.txt](https://github.com/QubesOS/qubes-issues/files/1217238/boot0.txt) < fail
here you go

**Comment by marmarek** [comment]
Looks like startup ordering issue with "LVM2 PV scan on device 8:34". I'll add appropriate dependency.

**Comment by seandilda** [comment]
Are packages with this fix available yet?  I updated to current-testing this morning, and I'm still seeing the problem.
