### ISSUE TITLE
R4.0-rc1 - create a new VM but it doesn't appear under the toolbar 'Q' app

### ISSUE THREAD

**Issue by JPL1** [QubesOS/qubes-issues#2961]
#### Qubes OS version (e.g., `R3.2`):
R4.0-rc1

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):

---

### Expected behavior:
Create a VM, it appears in the Q app dropdown

### Actual behavior:
Create a VM, doesn't appear

### Steps to reproduce the behavior:
Cliick Q button, top left
Create Qubes VM
Start VM
Click Q icon, top right
Dropdown does not include newly created VM

**Comment by 0spinboson** [comment]
that only shows running vms. start from start menu or command line, and it should show up there.

**Comment by 0spinboson** [comment]
ah. I've run into that a few times as well now. No idea what triggers it. I take it they are listed as running when you use 'qvm-ls'?

**Comment by JPL1** [comment]
Yes they are.

**Comment by 0spinboson** [comment]
since I can't check this myself, can you see if qvm-start-gui --all --watch fixes this?

**Comment by JPL1** [comment]
>can you see if running 'qvm-start-gui --all --watch &' fixes this?

No it doesn't.

**Comment by marmarek** [comment]
Fix for this is already queued for next version (QubesOS/qubes-dbus#4)

**Comment by marmarta** [comment]
It was fixed by using a completely different approach in https://github.com/QubesOS/qubes-desktop-linux-manager/commit/fbc1ec175d53eed1e8864e0c6d32e97c000c26bf
