### ISSUE TITLE
USB / drive icon is ugly and confusing R4.0-rc1

### ISSUE THREAD

**Issue by JPL1** [QubesOS/qubes-issues#2962]
#### Qubes OS version (e.g., `R3.2`):
R4.0-rc1

I looked at it a few times without realising what it was meant to be.

Why not use industry standard icons?

![usb_png9089](https://user-images.githubusercontent.com/12783198/28939639-d83ab9b6-7889-11e7-934d-1c775b614bdc.png)

**Comment by marmarek** [comment]
Actually this is already merged (QubesOS/qubes-desktop-linux-manager#6), will be in next update.
