### ISSUE TITLE
Boot Loop after installing R 4.0 on Lenovo Ideapad

### ISSUE THREAD

**Issue by cartman4** [QubesOS/qubes-issues#2965]
#### Qubes OS version:
R 4.0-rc1

### Expected behavior:
Booting into Qubes R 4.0.

### Actual behavior:
Boot loop. 

### Steps to reproduce the behavior:
Follow install instructions on a Lenovo Ideadpad 310. 

### General notes:
After Installing R 4.0 i am not able to boot into it. It does not even reach grub. It boots, doing a click sound and reboots.
this problem does not exist in R 3.2.

**Comment by JPL1** [comment]
Sounds like this problem:
https://github.com/QubesOS/qubes-issues/issues/2953

**Comment by sighmon** [comment]
The #2953 fix also works for a Lenovo x230 Tablet experiencing the same boot loop.

**Comment by cartman4** [comment]
Thank you. This fixed the boot loop problem. Sorry for dublicate
