### ISSUE TITLE
Nautilus missing from applications lists R4.0-rc1

### ISSUE THREAD

**Issue by JPL1** [QubesOS/qubes-issues#2967]
#### Qubes OS version (e.g., `R3.2`):
R4.0-rc1

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):
fedora-25, debian-8 and related App VMs

### Expected behavior:
VM Settings | Applications | Select Nautilus or File Mananger or similar

### Actual behavior:
This option not available. Also for Debian 'ImageMagick (display Q16) is listed twice

### Steps to reproduce the behavior:
as above

**Comment by marmarek** [comment]
There is "Files".

**Comment by JPL1** [comment]
Ah yes - not sure how I missed that. Need some new glasses. It is missing from the Debian template though

**Comment by mfc** [comment]
> It is missing from the Debian template though

in a fresh install of R4.0, the debian 9 template still does not have nautilus / files. this should be labeled as a R4.0 bug fix I think.

this is the type of thing that I was hoping #1781 would avoid.
