### ISSUE TITLE
qubes-devices showing random QUEMU stuff

### ISSUE THREAD

**Issue by Zrubi** [QubesOS/qubes-issues#2969]
#### Qubes OS version (e.g., `R3.2`):
4.0-rc1
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):
dom0

---

### Expected behavior:
Show only real USB devices

### Actual behavior:
See the attached screenshot:
![qubes-devices](https://user-images.githubusercontent.com/7664714/28965640-63b150a8-7912-11e7-92f7-2c1f2557d27d.jpg)

### Steps to reproduce the behavior:
The devices are randomly appears and disappears

---

**Comment by kalkin** [comment]
@marmarek  is AFAIK  is working on it.

> [12:20:30 PM] kalkin: There is one more thing: I noticed when I start the vm there is a QEMU_QEMU_USB_Tablet_42 device
[12:20:42 PM] kalkin: What is it and should it be shown at all in device tray?
[12:21:22 PM] marmarek: it should be filtered at VM side, will do
