### ISSUE TITLE
R4.0-rc1 - Improper boot-time LUKS keyboard layout

### ISSUE THREAD

**Issue by alexis-** [QubesOS/qubes-issues#2971]
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable): N/A

---

### Expected behavior:
Keyboard layout during boot-time for LUKS disk encryption should be the one set by default, during the installation procedure.

### Actual behavior:
Keyboard layout is set to qwerty, regardless of default keyboard layout.

### Steps to reproduce the behavior:
- Run Qubes R4.0-rc1 install
- Select US language
- Select a custom keyboard layout
- Proceed with rest of configuration, and install (default options in my case)
- At boot time, described issue occur

### General notes:
Keyboard layout otherwise behaves as expected (after disk de-encryption)

---

**Comment by KuroSaru** [comment]
Can confirm this behaviour.

**Comment by alexis-** [comment]
UEFI here

**Comment by awokd** [comment]
Resolving https://github.com/QubesOS/qubes-issues/issues/3624 might resolve this one too?

**Comment by alexis-** [comment]
I thought it was already solved ? I haven't faced this issue since RC2.

**Comment by andrewdavidwong** [comment]
Closing this as "resolved." If you believe the issue is not yet resolved, or if anyone is still affected by this issue, please leave a comment, and we'll be happy to reopen this. Thank you.

**Comment by awokd** [comment]
@andrewdavidwong Not sure this one is fully resolved yet- https://www.mail-archive.com/qubes-users@googlegroups.com/msg20710.html.

**Comment by marmarek** [comment]
Is it the same as #3234? There were relevant fixes in final 4.0 that didn't managed to get into rc5.

**Comment by awokd** [comment]
Indeed; please disregard my comment!
