### ISSUE TITLE
Non ASCII USB Device names breaks qubesd

### ISSUE THREAD

**Issue by KuroSaru** [QubesOS/qubes-issues#2972]
#### Qubes OS version (e.g., `R3.2`):
4.0 RC1

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):
Qubes Deamon - dom0 (qubesd)

---

### Expected behavior:
Allow user to use a USB Keyboard / Mouse in dom0 or attach to a AppVM

### Actual behavior:
Causes qubesd to stop updating completely. and wont register a input(hid) with dom0 from a sys-usb

### Steps to reproduce the behavior:
Connect a USB device with non-ascii characters in the device name.

### General notes:
Can be fixed by replaceing the qubesusbproxy/core3ext.py linke 94's "errors='strict'" with "errors=replace". This will take the copyright/trademark symbols from Microsoft hardware device names into consideration. and simply remove them as the display name is purely aesthetic anyway.

 - https://github.com/QubesOS/qubes-app-linux-usb-proxy/blob/master/qubesusbproxy/core3ext.py#L94
---

#### Related issues:
/etc/qubes-rpc/qubes.InputKeyboard  ; doesn't get the allow root dom0 from sys-usb for keyboard. while /etc/qubes-rpc/qubes.InputMouse does. can cause USB Issues.

**Comment by marmarek** [comment]
> /etc/qubes-rpc/qubes.InputKeyboard ; doesn't get the allow root dom0 from sys-usb for keyboard. while /etc/qubes-rpc/qubes.InputMouse does. can cause USB Issues.

Not allowing qubes.InputKeyboard by default is intentional, see here: https://www.qubes-os.org/doc/usb/#security-warning-about-usb-input-devices
