### ISSUE TITLE
Check VT-x and VT-d presence in installer

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#2977]
#### Qubes OS version (e.g., `R3.2`): R4.0

Since Qubes 4.0 do require them, check it at installation time and refuse to continue if missing.

**Comment by blacklight447** [comment]
Will this also check the SLAT (EPT) extension for vt-x? This could be important since not all vt-x enabled computers support SLAT.

**Comment by marmarek** [comment]
Yes.

**Comment by JohnnyFGlass** [comment]
What about users who have laptops with some Intel GPUs that don't display graphics correctly during installation if VT-x is on? So during the installation, they have to turn off VT-x in the BIOS and turn it back on afterwards, and add `iommu=no-igfx` to Xen's command line to have VT-d work properly without causing major graphics glitches that render the OS unusable.

Take a look at this issue for more info on this: #2284
