### ISSUE TITLE
Update a (fedora-25-based) VM imported from r3.2 to r4 breaks the VM

### ISSUE THREAD

**Issue by 0spinboson** [QubesOS/qubes-issues#2978]
#### Qubes OS version (e.g., `R3.2`):
R4.0
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):

standalone fedora-25 imported from r3.2

---

### Expected behavior:

can update standalone VM imported from Q3.2 by changing the qubes-repos, adding new signing key, renaming /etc/yum.repos.d/qubes-r3.repo to qubes-r4.repo.

### Actual behavior:

bash-4.3$ sudo dnf update --best --allowerasing
Last metadata expiration check: 0:00:15 ago on Sat Aug  5 08:09:05 2017.

Dependencies resolved.

**Package                          Arch    Version                      Repository                       Size**

**Upgrading:**
 faac                             x86_64  1.29.3-3.fc25                unitedrpms                       97 k
 faad2-libs                       x86_64  1:2.8.1-3.fc25               unitedrpms                      174 k
 ffmpeg                           x86_64  3.3.3-3.fc25                 unitedrpms                      1.5 M
 ffmpeg-libs                      x86_64  3.3.3-3.fc25                 unitedrpms                      6.3 M
 gstreamer1-plugins-bad-nonfree   x86_64  1.12.2-3.fc25                unitedrpms                       46 k
 libavdevice                      x86_64  3.3.3-3.fc25                 unitedrpms                       81 k
 python3-dnf-plugins-qubes-hooks  x86_64  4.0.6-1.fc25                 qubes-vm-r4.0-current-testing   8.8 k
 qubes-db-libs                    x86_64  4.0.3-1.fc25                 qubes-vm-r4.0-current-testing    12 k
 qubes-mgmt-salt-vm-connector     noarch  4.0.2-1.fc25                 qubes-vm-r4.0-current-testing   8.8 k
 qubes-usb-proxy                  noarch  1.0.10-1.fc25                qubes-vm-r4.0-current-testing   9.6 k
 vlc                              x86_64  3.0.0-42.git2b310f3.fc25     unitedrpms                      3.4 M
 vlc-core                         x86_64  3.0.0-42.git2b310f3.fc25     unitedrpms                      8.7 M
 xen-libs                         x86_64  2001:4.8.1-4.fc25            qubes-vm-r4.0-current-testing   615 k
 xen-licenses                     x86_64  2001:4.8.1-4.fc25            qubes-vm-r4.0-current-testing   105 k
 xen-qubes-vm                     x86_64  2001:4.8.1-4.fc25            qubes-vm-r4.0-current-testing   197 k
**Removing**:
 qubes-core-vm                    x86_64  3.2.18-1.fc25                @qubes-vm-r3.2-current-testing  248 k
 qubes-core-vm-systemd            x86_64  3.2.18-1.fc25                @qubes-vm-r3.2-current-testing   10 k
 qubes-db                         x86_64  3.2.4-1.fc25                 @qubes-vm-r3.2-current-testing   43 k
 qubes-db-vm                      x86_64  3.2.4-1.fc25                 @qubes-vm-r3.2-current-testing  310  
 qubes-gui-vm                     x86_64  3.2.17-1.fc25                @qubes-vm-r3.2-current-testing  140 k
 qubes-img-converter              x86_64  1.2.3-1.fc25                 @qubes-vm-r3.2-current-testing  6.5 k
 qubes-libvchan-xen               x86_64  3.2.1-1.fc25                 @qubes-vm-r3.2-current-testing   22 k
 qubes-utils                      x86_64  3.2.4-1.fc25                 @qubes-vm-r3.2-current-testing   44 k
 qubes-utils-libs                 x86_64  3.2.4-1.fc25                 @qubes-vm-r3.2-current-testing   39 k
**Skipping packages with broken dependencies:**
 qubes-db                         x86_64  4.0.3-1.fc25                 qubes-vm-r4.0-current-testing    23 k
 qubes-db-vm                      x86_64  4.0.3-1.fc25                 qubes-vm-r4.0-current-testing   6.6 k
 qubes-utils                      x86_64  4.0.4-1.fc25                 qubes-vm-r4.0-current-testing    17 k
 qubes-utils-libs                 x86_64  4.0.4-1.fc25                 qubes-vm-r4.0-current-testing    21 k

**Transaction Summary**
Upgrade  15 Packages
Remove    9 Packages
Skip      4 Packages

Total download size: 21 M
Is this ok [y/N]: n

### Steps to reproduce the behavior:
When I don't add --best, it doesn't propose to remove qubes-db, qubes-db-vm, but instead proposes to update those to the 4.0.x variants, but when I run dnf autoremove afterwards, it proposes to remove something like 270 packages, including a lot of qubes-related ones.

If I do update, sudo is completely broken, and networking is broken on the next reboot (ifconfig only shows loopback). Manually updating the 'broken dependency' packages and xen-* before reboot doesn't help either, and can break the VM even worse.

### Notes

I haven't been able to test this on fc-25-based template imported from r3.2, because I haven't gotten a pvm template to boot yet, so I don't know (and can't easily test) if this is a freak occurrence.

**Comment by marmarek** [comment]
Try installing `qubes-vm-recommended` first.

**Comment by 0spinboson** [comment]
okay. didn't accept the command at first (had to manually remove qubes-core-vm-systemd). Afterwards, I'm looking at a new situation:
bash-4.3$ **sudo dnf update**
Last metadata expiration check: 0:05:46 ago on Sat Aug  5 10:30:52 2017.
Dependencies resolved.
======================================================================================================================================================
 Package                                      Arch                 Version                                  Repository                           Size
======================================================================================================================================================
**Upgrading**:
 faac                                         x86_64               1.29.3-3.fc25                            unitedrpms                           97 k
 faad2-libs                                   x86_64               1:2.8.1-3.fc25                           unitedrpms                          174 k
 ffmpeg                                       x86_64               3.3.3-3.fc25                             unitedrpms                          1.5 M
 ffmpeg-libs                                  x86_64               3.3.3-3.fc25                             unitedrpms                          6.3 M
 gstreamer1-plugins-bad-nonfree               x86_64               1.12.2-3.fc25                            unitedrpms                           46 k
 libavdevice                                  x86_64               3.3.3-3.fc25                             unitedrpms                           81 k
 qubes-mgmt-salt-vm-connector                 noarch               4.0.2-1.fc25                             qubes-vm-r4.0-current               8.8 k
 vlc                                          x86_64               3.0.0-42.git2b310f3.fc25                 unitedrpms                          3.4 M
 vlc-core                                     x86_64               3.0.0-42.git2b310f3.fc25                 unitedrpms                          8.7 M
 xen-licenses                                 x86_64               2001:4.8.1-4.fc25                        qubes-vm-r4.0-current               105 k
**Skipping packages with conflicts:**
(add '--best --allowerasing' to command line to force their upgrade):
 xen-libs                                     x86_64               2001:4.8.1-4.fc25                        qubes-vm-r4.0-current               615 k
 xen-qubes-vm                                 x86_64               2001:4.8.1-4.fc25                        qubes-vm-r4.0-current               197 k

Transaction Summary
======================================================================================================================================================
Upgrade  10 Packages
Skip      2 Packages

and if i do **dnf update --allowerasing --best**:

**Upgrading**:
 faac                                                 x86_64                     1.29.3-3.fc25                                  unitedrpms                                          97 k
 faad2-libs                                           x86_64                     1:2.8.1-3.fc25                                 unitedrpms                                         174 k
 ffmpeg                                               x86_64                     3.3.3-3.fc25                                   unitedrpms                                         1.5 M
 ffmpeg-libs                                          x86_64                     3.3.3-3.fc25                                   unitedrpms                                         6.3 M
 gstreamer1-plugins-bad-nonfree                       x86_64                     1.12.2-3.fc25                                  unitedrpms                                          46 k
 libavdevice                                          x86_64                     3.3.3-3.fc25                                   unitedrpms                                          81 k
 qubes-mgmt-salt-vm-connector                         noarch                     4.0.2-1.fc25                                   qubes-vm-r4.0-current                              8.8 k
 vlc                                                  x86_64                     3.0.0-42.git2b310f3.fc25                       unitedrpms                                         3.4 M
 vlc-core                                             x86_64                     3.0.0-42.git2b310f3.fc25                       unitedrpms                                         8.7 M
 xen-libs                                             x86_64                     2001:4.8.1-4.fc25                              qubes-vm-r4.0-current                              615 k
 xen-licenses                                         x86_64                     2001:4.8.1-4.fc25                              qubes-vm-r4.0-current                              105 k
 xen-qubes-vm                                         x86_64                     2001:4.8.1-4.fc25                              qubes-vm-r4.0-current                              197 k
**Removing**:
 pulseaudio-qubes                                     x86_64                     4.0.2-1.fc25                                   @qubes-vm-r4.0-current                              28 k
 qubes-core-agent                                     x86_64                     4.0.6-1.fc25                                   @qubes-vm-r4.0-current-testing                     252 k
 qubes-core-agent-dom0-updates                        x86_64                     4.0.6-1.fc25                                   @qubes-vm-r4.0-current-testing                     4.7 k
 qubes-core-agent-nautilus                            x86_64                     4.0.6-1.fc25                                   @qubes-vm-r4.0-current-testing                      11 k
 qubes-core-agent-network-manager                     x86_64                     4.0.6-1.fc25                                   @qubes-vm-r4.0-current-testing                     2.3 k
 qubes-core-agent-networking                          x86_64                     4.0.6-1.fc25                                   @qubes-vm-r4.0-current-testing                      16 k
 qubes-core-agent-qrexec                              x86_64                     4.0.6-1.fc25                                   @qubes-vm-r4.0-current-testing                      71 k
 qubes-db                                             x86_64                     3.2.4-1.fc25                                   @qubes-vm-r3.2-current-testing                      43 k
 qubes-db-vm                                          x86_64                     3.2.4-1.fc25                                   @qubes-vm-r3.2-current-testing                     310  
 qubes-gui-agent                                      x86_64                     4.0.2-1.fc25                                   @qubes-vm-r4.0-current                             111 k
 qubes-img-converter                                  x86_64                     1.2.3-1.fc25                                   @qubes-vm-r3.2-current-testing                     6.5 k
 qubes-libvchan-xen                                   x86_64                     3.2.1-1.fc25                                   @qubes-vm-r3.2-current-testing                      22 k
 qubes-utils                                          x86_64                     3.2.4-1.fc25                                   @qubes-vm-r3.2-current-testing                      44 k
 qubes-utils-libs                                     x86_64                     3.2.4-1.fc25                                   @qubes-vm-r3.2-current-testing                      39 k
 qubes-vm-recommended                                 noarch                     4.0.0-1.fc25                                   @qubes-vm-r4.0-current                               0

**Comment by marmarek** [comment]
It looks its about qubes-libvchan-xen package, which have the same version, but is linked with different Xen version. Try now, I've just uploaded package with bumped version.

**Comment by marmarek** [comment]
Also, make sure to re-install qubes-core-agent-systemd (if isn't pulled by dependencies). And make sure to re-enable required services - at least qubes-qrexec-agent and qubes-gui-agent. Let me know if those were disabled (I had similar problem in early testing).
The easiest way to reset services to desired state is `systemctl preset-all`

**Comment by 0spinboson** [comment]
Thanks, that fixed it. The services were enabled after update, fwiw.
