### ISSUE TITLE
Improvement request regarding /etc/hosts file in Qubes OS R3.2

### ISSUE THREAD

**Issue by MarkRijckenberg** [QubesOS/qubes-issues#2979]
#### Qubes OS version (e.g., `R3.2`):
R3.2
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):
fedora-25
#### Affected AppVMs :
sys-net
### Expected behavior:
Expect to see 1 MB /etc/hosts file in sys-net NetVM and fedora-25 templateVM to block malware sites.
### Actual behavior:
Almost empty /etc/hosts file in sys-net NetVM and fedora-25 templateVM 
### General notes:
I suggest adding the following bash script into the Fedora template builder scripts:

#################################################################
# install new secure /etc/hosts file to block malware websites
#################################################################
LogDay=`date -I`
cd 
sudo rm -rf hosts
sudo cp /etc/hosts /etc/hosts.$LogDay.backup
git clone https://github.com/StevenBlack/hosts.git
cd hosts
sudo python3 updateHostsFile.py -a -r
sudo chmod 444 /etc/hosts

---

#### Related issues:
None

**Comment by marmarek** [comment]
No, unless adopted by upstream (Fedora here). See https://www.qubes-os.org/doc/devel-faq/#what-is-qubes-attitude-toward-changing-guest-distros
