### ISSUE TITLE
Update System Requirements page

### ISSUE THREAD

**Issue by rootkovska** [QubesOS/qubes-issues#2988]
People are apparently misguided by our System Requirements page and think that _any_ system which meets the requirements listed there should run Qubes OS fine. We should explicitly state there they should consult the HCL first.

E.g.: https://twitter.com/mrphs/status/894823211749318656

**Comment by rootkovska** [comment]
Perhaps we should even consider adding an "click-to-accept" page, which appears after clicking on the download link, which would say something like:

> I understand that Qubes OS is picky about hardware. I checked the HCL list to see if my _specific_ system (e.g. the specific _generation_ of X1 Carbon, not mere "X1 Carbon") is considered compatible with Qubes OS. I understand that if my system hasn't been listed on the HCL, chances are high the installation process will be bumpy or unsuccessful. In that case, I promise not to complain all over the social media at whatnot about this, but instead to send reports [link] to qubes-users, contributing to the community-maintained HCL table.

Or something along these line.

**Comment by rootkovska** [comment]
Also, as suggested by a user [1], I think it would make a lot of sense to detect that X failed during installation and display a message along the lines of: "Sorry, you're out of luck with this hardware, go try a different one". This is in order to discourage users from spending hours trying to complete the installation via the text-based installer, a process in most cases leading nowhere.

**Comment by marmarek** [comment]
> Perhaps we should even consider adding an "click-to-accept" page, which appears after clicking on the download link, which would say something like:

Please no. "Click-to-accept" are the most annoying things on the internet.

**Comment by rootkovska** [comment]
> Please no. "Click-to-accept" are the most annoying things on the internet.

Right. Just like people who try Qubes on non-compatible hardware and then bring their disappointment to Twitter and everywhere... :/

**Comment by marmarek** [comment]
Well, there will be always people like this, regardless of how many warnings we'll put there. Lets not waste our time on them, and at the same time not discourage users who actually read what we put there.
One or two additional sentences on "System Requirements" should be enough. This page is already linked at the top of downloads page.

**Comment by tokideveloper** [comment]
Why not just

- add an item "Consult the HCL list" to each of the "System Requirements Minimum" lists [1] and
- add a "See the System Requirements Minimum list before downloading" banner in yellow to the version-dependent download sections [2]?

[1]: https://www.qubes-os.org/doc/system-requirements/
[2]: https://www.qubes-os.org/downloads/

**Comment by marmarek** [comment]
Yes, this should be ok.

**Comment by rootkovska** [comment]
In any case, I think we should change the installer to stop and print a message whenever X failed to run. Perhpas offer some "I really know what I do and I won't complain if things go wrong" button to proceed in text mode, although I'd rather want we don't do that.

**Comment by marmarek** [comment]
Yes, maybe a command line option to enable text mode installer. But do not fallback to it automatically.

**Comment by mrphs** [comment]
You know it's really sad to read "let's not waste our time on people like this". Well, I happen to be the person you don't want to _waste_ your time on, and I have spent quite some time reading the documentations and HCL list. And no of course a "click to accept" page wouldn't be an improvement. The improvement begins when you actually try to have some empathy for how difficult it is to actually find the right hardware and install Qubes.

I happen to have read the "System requirements" page. The title of the page literally says if you meet this criteria, you do have what is required to run Qubes. This page has two sections for each release line. Minimum and Recommended. I tried to go above what's recommended to be sure I can get a good performance with the reasonable security required for my work. Additionally, there are two links that advises looking at "Certified Hardware" list which is basically a deadend since such list doesn't exist and no hardware is certified.

I got a Lenovo X1 5th (current) Generation that meets all the mentioned criteria. And even further down on the same page under "important note" section, you have a line that says:
> Qubes can be installed on systems which do not meet the recommended requirements. Such systems will still offer significant security improvements over traditional operating systems, since things like GUI isolation and kernel protection do not require special hardware.

No where on this page says having an Intel graphic card which is btw _strongly preferred_ is going to be a blocker.

And of course I'd naturally trust the "system requirement" page more than HCL list because the former has been put together by Qubes developers where the latter is just by random users trying different hardware. 

I've been a long supporter of Qubes both in private (when speaking with funders and donors) and public (when speaking at events, giving talks or training) or even on twitter. And it's very discouraging to have such interaction with a team I always have highly spoken of. And this is all because I tweeted that it took me hours to diagnose and understand why the installer wasn't running because you don't have good UX? If you're not trying to be helpful maybe at least have some respect for people's time?

**Comment by rootkovska** [comment]
I agree with all that you're saying, @mrphs. I believe Marek's "lets not waste time on people like this" referred to those people who, despite the _new_ precautions I proposed (confirm HCL match, etc), would still ignore them. I agree the System Requirements page was badly written, which is why I created the ticker in the first place :)

**Comment by rootkovska** [comment]
About solving the hardware problem -- we've been thinking about it for years, but sadly, when it comes to individual users (in contrast to corporations which might easily afford to pick a specific h/w config and pay for making sure Qubes work on it), there is no solution available ATM. Even the most straightforward option to strike a deal with some OEM, such as e.g. Lenovo and ask them to "freeze" some h/w config and offer us for at least a year or so, and maybe have also coreboot flashed there, would take **millions of dollars** of investment. So, right now best-effort HCL is the best we can do. Plus finding a way to force people to use HCL...

**Comment by rootkovska** [comment]
And in case someone find it hard to believe it is so hard to partner with an OEM to offer some reasonable hardware, say with frozen config and maybe coreboot (so nothing fancy like the stateless laptop!), then note that in the last years we have partnered or nearly partnered (or tried to partner) with no less then **thee different OEMs** and in case the result was either v. disappointing or the deal turned to be a no-go :(

**Comment by marmarek** [comment]
Sorry @mrphs, my intention was to avoid plastering warnings all the place, which would make getting to actual download a painful experience. I agree that System Requirements page should be more clear that meeting minimum/recommended requirements do not guarantee compatibility.
OTOH, choosing X1 Carbon (and in fact most of high-end Lenovo machines) should be pretty good choice. Have you tried 4.0rc1, which have updated kernel and xen? There will be also 3.2.1 with the same kernel version.

**Comment by ctrlaltdel** [comment]
Jumping in the conversation as a new Qubes user which happened to own the same laptop model than @mrphs. Version 4.0-rc1 works Well for me me with the following caveats:
- USB Legacy mode and UEFI disabled to get the installer booting
- A few other issues that already have tickets open (#2953, #2960)

I'm planning to submit a new HCL entry for it as soon as possible.

**Comment by andrewdavidwong** [comment]
@rootkovska:
> Also, as suggested by a user [1], I think it would make a lot of sense to detect that X failed during installation and display a message along the lines of: "Sorry, you're out of luck with this hardware, go try a different one". This is in order to discourage users from spending hours trying to complete the installation via the text-based installer, a process in most cases leading nowhere.
[1] https://twitter.com/mrphs/status/894826562855501824
>
> In any case, I think we should change the installer to stop and print a message whenever X failed to run. Perhpas offer some "I really know what I do and I won't complain if things go wrong" button to proceed in text mode, although I'd rather want we don't do that.

@marmarek:
> Yes, maybe a command line option to enable text mode installer. But do not fallback to it automatically.

Branched to #2998.

**Comment by mrphs** [comment]
@andrewdavidwong hm there were two issues here. The other one that is also the title of this ticket, is updating the "System Requirement" page which appears to be more pressing and time sensitive than #2998

**Comment by andrewdavidwong** [comment]
@mrph:
> hm there were two issues here. The other one that is also the title of this ticket, is updating the "System Requirement" page which appears to be more pressing and time sensitive than #2998. I don't think this ticket is ready to be closed just yet.

I closed this ticket from the [commit](https://github.com/QubesOS/qubes-doc/commit/580a0dfcf30dcd1402db4f6f31e876ecf0fbfad4) that updates the System Requirements page.

**Comment by mrphs** [comment]
@andrewdavidwong My bad! I missed it. I guess I'm not used to GH interface :)

**Comment by andrewdavidwong** [comment]
@mrphs: No worries!

**Comment by dhemminger-ars** [comment]
Would it be possible to create a simple diagnostic that could be run on a PC to summarize the Qubes Hardware Compatibility of that machine.  It could quickly diagnose and report on the configuration and compatibility of each major requirement (e.g HVM, IOMMU, TPM 1.2 or 2.0), and indicate possible issues or conflicts.  It would take a lot of the guesswork out of the HCL process.  I'd love to run it on my new Dell Optiplex 3050.

**Comment by marmarek** [comment]
@dhemminger-ars you can boot the installer - it will warn you if your hardware is lacking crucial features. See here for example: https://openqa.qubes-os.org/tests/144#step/install_welcome/4

**Comment by dhemminger-ars** [comment]
That is very helpful.  I just thought that if there was a separate diagnostic that reported what passes and what fails, it would simplify the HCL process and allow anyone to add useful entries to the HCL list, possibly speeding up the adoption of Qubes.

Regards,
Don Hemminger
