### ISSUE TITLE
latest TorBirdy release 0.2.3 breaks split-gpg in Qubes OS

### ISSUE THREAD

**Issue by mfc** [QubesOS/qubes-issues#2989]
I have created an upstream ticket with TorBirdy, this ticket is to track it in case other Qubes users encounter it:

https://trac.torproject.org/projects/tor/ticket/23143

**Comment by andrewdavidwong** [comment]
> I have created an upstream ticket with TorBirdy, this ticket is to track it in case other Qubes users encounter it:
> 
> https://trac.torproject.org/projects/tor/ticket/23143

I interpret this to mean that this should be labeled as `notourbug` and closed (but still available in search results to others who encounter the same issue, as you intended). If I've misinterpreted your intention, let me know.
