### ISSUE TITLE
Wifi Adapter Qualcom Atheros AR9002WB-1NG

### ISSUE THREAD

**Issue by biotrox** [QubesOS/qubes-issues#2992]
#### Affected all:
can't connect to network

---

### General notes:
laptop is Toshiba R835-R94 

---

**Comment by 0spinboson** [comment]
Have you ever used linux before on this laptop, and did it work in that other distro? & What exactly does "can't connect" mean? Does it work, but error out every time you try to connect? Does it not show up?

**Comment by andrewdavidwong** [comment]
This is too localized for `qubes-issues`. Please consider posting this to the `qubes-users` mailing list instead. (You can read more about our mailing lists [here](https://www.qubes-os.org/mailing-lists/).)

`qubes-users` is intended for these sorts of questions and receives much more traffic, which means that your question is more likely to receive a response there.
