### ISSUE TITLE
4.0rc1 _qvm-prefs usbVM -s pci_strictreset false_ doesn't work

### ISSUE THREAD

**Issue by 3hhh** [QubesOS/qubes-issues#2993]
qvm-prefs usbVM -s pci_strictreset false 
results in qvm-prefs reporting an unknown option in 4.0rc1.

This would require a different approach for
https://www.qubes-os.org/doc/user-faq/#i-created-a-usbvm-and-assigned-usb-controllers-to-it-now-the-usbvm-wont-boot

**Comment by marmarek** [comment]
That's right, in 4.0 there is `-o no-strict-reset=True` option to `qvm-pci` while attaching the device. Documentation needs to be updated. And also `qvm-pci` tool to list such option when device is attached with it (currently there is no way to know what options were used).

**Comment by 0spinboson** [comment]
Ah, so that's why I couldn't move host controllers to the usbvm using the gui.

**Comment by 3hhh** [comment]
> That's right, in 4.0 there is -o no-strict-reset=True option to qvm-pci while attaching the device. Documentation needs to be updated. And also qvm-pci tool to list such option when device is attached with it (currently there is no way to know what options were used).

Just checked all of these points and they're all fixed:

- doc: https://www.qubes-os.org/faq/
- `man qvm-pci`
- `qvm-pci` lists the used options as part of the `USED BY` column
