### ISSUE TITLE
Possible feature: Qubes App could show the VM states

### ISSUE THREAD

**Issue by 3hhh** [QubesOS/qubes-issues#2995]
The systray application introduced with Qubes 4.0rc1 instead of the Qubes manager could show the state of all VMs (green = running, red = down or whatever) and allow easy access to the VM settings for all VMs instead of only to the started VMs.

This would remove the need to maintain custom menu bars for the various supported window managers.

**Comment by marmarta** [comment]
There's a new-old variant of Qube Manager that does exactly that now, introduced here: https://github.com/QubesOS/qubes-manager/commit/8b5e2a8d665d3bcdd7fb32cadce038ad15eb6d5c
