### ISSUE TITLE
admin-local-* should include admin-global-* content

### ISSUE THREAD

**Issue by rootkovska** [QubesOS/qubes-issues#2996]
`admin-local-{ro,rwx}` should include `admin-global-{ro,rwx}` respectively -- if something's allowed to read (write) the global state, it should also be allowed to read (write) the per-VM state.

**Comment by rootkovska** [comment]
BTW, we should also make sure that our automatics tests cover all the cases: both positive (calls allowed), but even more importantly negative (e.g. W-calls dropped when test VM given R-rights, etc).

/cc @woju

**Comment by marmarek** [comment]
Are you sure about that inclusion? I think it may be useful to allow `admin-global-rwx` calls (creating VMs, setting up defaults, managing storage etc), but do not allow to manipulate existing VMs (where the data lives).

**Comment by rootkovska** [comment]
I assume we agree about inclusion of global-ro into local-ro, right?
But you would like to keep global-rwx apart from local-rwx, correct?

**Comment by marmarek** [comment]
Generally yes. But if you put it this way, I think such a difference may be confusing. So, I would not include it either for ro or rwx. This may mean some duplication of rules. But also, user (or rather: admin) can add such include when it suits particular use case.

**Comment by woju** [comment]
Out of principle I don't think there should be too many includes, since this would be a risk for maintainers. This would be another thing to remember for example if we wanted to write a new API call. I don't think that gains in terms of administration simplicity are worth the ideological complication, for both us and the administrator.

And as Marek said, if administrators choose to make such an include, they're always free to do so.

**Comment by rootkovska** [comment]
So, you guys say that we include make rwx -> ro inclusions, but not global -> local, correct?

I think I'm generally convinced by the "admin can add the include on her own" argument. Only worry is to make sure to add it in the "right direction". How about adding a commented includes (global -> local) to eliminate this potenotential mistake?

**Comment by marmarek** [comment]
Wrong issue referenced from commit.
