### ISSUE TITLE
System beep/bell does not play

### ISSUE THREAD

**Issue by kumavis** [QubesOS/qubes-issues#2997]
#### Qubes OS version (e.g., `R3.2`):
3.2

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):
all, including dom0

---

### Expected behavior:
beep

### Actual behavior:
no beep

### Steps to reproduce the behavior:
`echo -ne '\007'`

### General notes:
it could be a hardware issue on my side (correctly forwarding to hardware bell, but bell is not attached)

---

**Comment by tlaurion** [comment]
@marmarek : would also know if there is a workaround for system scrits to be able to alert user when task is done!

**Comment by brendanhoar** [comment]
Note that the pcspeaker device in dom0 does not work (Xen 4.8 blocks it in dom0, unsure if current Xen continues to block it). 

So, in dom0 scripts, I simulate it via the following:
```
function create_beep () {
	# create our beep file as xen does not expose the real "bell" device w/in the Qubes configuration and a simple echo "\007" does not work.
	> /tmp/sinewave.wav
	printf "\x52\x49\x46\x46\x64\x1F\x00\x00\x57\x41\x56\x45\x66\x6D\x74\x20\x10\x00\x00\x00\x01\x00\x01\x00\x40\x1F\x00\x00\x40\x1F\x00\x00\x01\x00\x08\x00\x64\x61\x74\x61\x40\x1F\x00\x00" >> /tmp/sinewave.wav
	for n in {0..999}
	do
        	printf "\x80\x26\x00\x26\x7F\xD9\xFF\xD9" >> /tmp/sinewave.wav
	done
}
```

And then, in the scripts, I invoke the function above to create the wav file, then use the following to simulate a beep:
```
aplay -q /tmp/sinewave.wav --duration=1
```
when needed.

(just in case you need a dom0 workaround, does not address core issue)

Brendan
