### ISSUE TITLE
No automatic fallback to text-based installer

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#2998]
[Branched from #2988.]

@rootkovska, beginning in https://github.com/QubesOS/qubes-issues/issues/2988#issuecomment-320878780:
> Also, as suggested by a user [1], I think it would make a lot of sense to detect that X failed during installation and display a message along the lines of: "Sorry, you're out of luck with this hardware, go try a different one". This is in order to discourage users from spending hours trying to complete the installation via the text-based installer, a process in most cases leading nowhere.
[1] https://twitter.com/mrphs/status/894826562855501824
>
> In any case, I think we should change the installer to stop and print a message whenever X failed to run. Perhpas offer some "I really know what I do and I won't complain if things go wrong" button to proceed in text mode, although I'd rather want we don't do that.

@marmarek:
> Yes, maybe a command line option to enable text mode installer. But do not fallback to it automatically.

**Comment by marmarek** [comment]
https://github.com/marmarek/qubes-installer-qubes-os/commit/2d3405de9ac0cc7d94b3b4f64590ad93d5ba7d54
