### ISSUE TITLE
Alt text from Chromium or Firefox is displayed when window is not in focus + when minimized

### ISSUE THREAD

**Issue by aQubesUser** [QubesOS/qubes-issues#3000]
#### Qubes OS version (e.g., `R3.2`):

`R3.2`

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):

`fedora-23` with `KDE`

---

### Expected behavior:

Alt text from webpages in Chromium or Firefox should only be shown when window is not minimized and in focus.

### Actual behavior:

Alt text is seen when Chromium or Firefox window is not in focus, this occurs when window is minimized as well. A screenshot is attached. This happens regularly and prevents smooth workflow.

![qubes-error-pub](https://user-images.githubusercontent.com/25757046/29145226-ccca01e2-7d4b-11e7-9fd9-c1c23f57a45b.png)

### Steps to reproduce the behavior:

I do not have exact steps to reproduce the behavior. A possible way to see this would be to open a webpage with many links which have alt text and to then use the system normally (with KDE). I regularly switch desktops with the (ctrl-alt-`<left>` and `<right>`) shortcuts, I use `yakuake` and `okular` as well. The alt text can be also be seen when on a different desktop altogether than the desktop running the Chromium or Firefox windows.

### General notes:

I did a quick search and did not find any similar issues.

I have 2 monitors and often after turning off one or both monitors (at the end of the day, for example) and turning them back on, VMs will fail to be updated with my monitor configuration and I often have to restart the VM altogether.

---

#### Related issues:

None that I found upon a quick search.

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
