### ISSUE TITLE
Allow to easily create qrexec services hosted on /rw

### ISSUE THREAD

**Issue by rootkovska** [QubesOS/qubes-issues#3003]
Currently, in order to create some service, say `my.SillyService` one needs to either install it in the template or do some copying (to `/etc/qubes-rpc`) of the service file from /rw/config/rc.local. Perhaps it would be useful to allow qrexec service files to be placed in some pre-defined location which is kept on /rw. E.g. `/usr/local/etc/qubes-rpc` or `/rw/qubes-local-rpc/`?

**Comment by woju** [comment]
`/usr/local/etc/qubes-rpc` works since 3.0 (QubesOS/qubes-core-agent-linux@6c0e567929cb9623743181f53808d0c3236a87eb) so closing.
