### ISSUE TITLE
Offline mode in R4.0

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#3004]
Branched from https://github.com/QubesOS/qubes-issues/issues/3002#issuecomment-321565265
@rootkovska :
> We need to bring back the --offline-mode switch, as it was in R3.

**Comment by rootkovska** [comment]
Perhaps just `--offline`?

**Comment by marmarek** [comment]
`--offline-mode` for qvm-* tools makes no sense, because the _only_ thing that those tools do is to connect to qubesd. When you add option to not connect to `qubesd`, you can also use `/bin/true`...
But there is `qubesd --offline-mode`, which should allow you to normally use qvm-tools to manipulate VM settings (qubes.xml), without trying to start any VM.
The missing part is making it actually working - currently it crashes early on qubesd initialization (`VMM operations disabled in offline mode`).

**Comment by rootkovska** [comment]
By `--offline(-mode)` (and only for `qvm-create`) I meant: create VM with no netvm :)
