### ISSUE TITLE
qrexec-policy-graph: --target specification is ignored

### ISSUE THREAD

**Issue by rootkovska** [QubesOS/qubes-issues#3006]

**Comment by marmarek** [comment]
Can you give more details? I've just tried `qrexec-policy-graph --target dom0` and indeed got only edges directed to dom0.

**Comment by rootkovska** [comment]
Try with some VM? :)

**Comment by marmarek** [comment]
Then I get different result. Which means that clearly it is _not_ ignored.
Looks like the target is considered before handling `target=` override from policy. I guess you expect in the graph actual target domain, not what source VM can ask for (which may be later overriden by `target=`), right?

**Comment by rootkovska** [comment]
Correct, and that's an important point you stressed! We want the graph to show the actual call paths that might happen.
