### ISSUE TITLE
Graphical interface to present USB devices to other qubes should refresh each time we click on it

### ISSUE THREAD

**Issue by gmartin42** [QubesOS/qubes-issues#3009]
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable): sys-usb but more the "software to manage USB devices on sys-usb VM"

---

### General notes:

Sorry for my English I am French, I will be hapy to provide more details if you need.

---

**Comment by marmarek** [comment]
This is already fixed [here](https://github.com/QubesOS/qubes-desktop-linux-manager/pull/7), new package will be in testing repository tomorrow (or even today).

**Comment by gmartin42** [comment]
Thank you, sorry for the duplicate issue.
