### ISSUE TITLE
Unknown packages required for sys-net based on fedora-25-minimal

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#3010]
#### Qubes OS version (e.g., `R3.2`):

`R3.2`

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):

`fedora-25`
`fedora-25-minimal`

---

### Expected behavior:

`sys-net` works when based on `fedora-25`.

### Actual behavior:

AppVMs have no network connectivity when `sys-net` is based on `fedora-25`.

### Steps to reproduce the behavior:

Base `sys-net` on `fedora-25`.

### General notes:

Since Fedora 24 reached EOL on 2017-08-08, Fedora 25 is now the only available Fedora template for R3.2.

---

#### Related issues:

#2964 (4.0-rc1, concerns both `fedora-25` and `debian-9`)

**Comment by marmarek** [comment]
I've tried to reproduce this and failed.
I've got fresh qubes-template-fedora-25 from repository, installed updates there (dnf update), then switched sys-net to fedora-25. And everything works just fine...

**Comment by andrewdavidwong** [comment]
@marmarek: You're right. I can no longer reproduce this with vanilla `fedora-25`. The problem only occurs when I try to use the NetVM-specific template I upgraded from Fedora 24 (originally based on `fedora-24-minimal`). This suggests that some packages are missing, which means we should update the Fedora-minimal documentation once we find out what they are.

**Comment by marmarek** [comment]
If that is just about missing package, comparing list of packages should give some hints.

**Comment by 0spinboson** [comment]
I was playing around with debian-8 template a bit, and I noticed that after updating a bunch of packages using jessie-backports, one of which being salt-common-2016.11.2 (from salt-common-2014.1.13), the next time I started sys-net, networking was broken. Networking is also broken using d9 for me. Could this be related? (I had a look at the package lists for f25 and f25m, but none of the differences seem to me to be likely to be the cause, which suggests it's a dependency causing the issue.)

**Comment by andrewdavidwong** [comment]
@marmarek: The original problem recurred again for me. Now that my `sys-net` is based on `fedora-25`, it frequently fails to connect to any network after the system resumes from sleep (reported separately in #3030). When this happens, I have to restart `sys-net`. After restarting it once today, I found find that (as originally described here) AppVMs had no network connectivity even though `sys-net` itself could ping sites and the `qubes-firewall` services was running fine in `sys-firewall`.

**Comment by jpbrown-15** [comment]
This looks similar to the problem listed in the user forum.  I didn't look at the Salt package but I have experienced a failure of all templates other than the originals provided with the 3.2 release to act as a NetVM.  I have been able to do updates to the templates but if they weren't part of the original release, I have never been able to successfully get the network to function.

https://groups.google.com/forum/#!topic/qubes-users/hSTvQEiPxfU

**Comment by andrewdavidwong** [comment]
@jpbrown-15 It's possible that you're experiencing #3008 (of which #3030 turned out to be a duplicate).

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
