### ISSUE TITLE
Unable to create a VM without net from the command line

### ISSUE THREAD

**Issue by Mayeu** [QubesOS/qubes-issues#3011]
#### Qubes OS version (e.g., `R3.2`):

R4.0-rc1

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):

I don't think it is applicable, but the template is the default fedora-25.

---

### Expected behavior:

From the command line (using `qvm-create`), I should be able to create a VM without any network. Also, if I have a VM with network, I should be able to set the domain of the `netvm` to `none`.

### Actual behavior:

When running `qvm-create`:
```
qvm-create --label red --property netvm=none backup
app: Error setting property netvm (but VM created): '"No such domain: \'none\'"'
```

The same exception happen when I use `qvm-prefs` to try to set the netvm to none.

### Steps to reproduce the behavior:

1. Install qubes-os from scratch
2. Try to create a VM from the command line without access to a netvm

### General notes:

If needed, my device is a Librem 13v2 from Purism.

From the man page of `qvm-prefs`, in the section detailling the properties:
```
...
     netvm  Accepted values: netvm name, default, none
...
```

---

#### Related issues:

I did not find any.

**Comment by marmarek** [comment]
See here: https://github.com/QubesOS/qubes-issues/issues/3002#issuecomment-321567109

Looks like a bug in qvm-prefs man page.

**Comment by Mayeu** [comment]
Ha, thanks! Indeed this is a documentation issue then :) Thank you for taking care of it :+1:
