### ISSUE TITLE
qvm-run --dispvm doesn't work when invoked from an AppVM

### ISSUE THREAD

**Issue by rootkovska** [QubesOS/qubes-issues#3013]
#### Qubes OS version (e.g., `R3.2`):

4.0-rc1, core-agent-* 4.0.6.

### Steps to reproduce the behavior:

```
qvm-run --dispvm -- xterm
```

Throws exception in the VM: "filter_esc not implemented for calls from VM"

**Comment by marmarek** [comment]
Add `--no-filter-esc-characters` option, I'll fix default.

**Comment by marmarek** [comment]
(it should be ignored anyway, since you didn't use --pass-io)
