### ISSUE TITLE
fedora-25 - KDE System Settings - Unable to customize Appearance

### ISSUE THREAD

**Issue by aQubesUser** [QubesOS/qubes-issues#3014]
#### Qubes OS version (e.g., `R3.2`):

`R3.2`

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):

`fedora-25`

---

Upon installation of `fedora-25`  TemplateVM and switching a VM to `fedora-25` (from `fedora-23`), KDE System Settings inside the VM shows an error when trying to customize appearance. I had to install the `plasma-systemsettings` package.

### Expected behavior:

KDE System Settings should allow Appearance customization.

### Actual behavior:

System Settings window displays

```
The module Appearance is not a valid configuration module.

The diagnosis is:
The desktop file settings-appearance.desktop does not specify a library
```
![qubes-kde-error2](https://user-images.githubusercontent.com/25757046/29228292-be275df0-7ec8-11e7-9b38-e9e510c4258f.png)

### Steps to reproduce the behavior:

Upgrade TemplateVM `fedora-23` to `fedora-25` using instructions on https://www.qubes-os.org/doc/template/fedora/upgrade-24-to-25/

Install `plasma-systemsettings` package:
`sudo dnf install plasma-systemsettings`

Run `systemsettings5`, switch to 'Classic Tree View', click 'Appearance'

### General notes:

Trying to configure the VM to use a dark theme instead of the default light theme.

---

#### Related issues:

none

**Comment by aQubesUser** [comment]
After installing the `plasma-desktop` package I am able to see the options in the `systemsettings5` menu.

Changing any of the settings doesn't result in any changes to the appearance of my programs, however.

**Comment by aQubesUser** [comment]
How do I force the VM to use KDE for all windows? This seems to be using Gnome to display all windows.

**Comment by aQubesUser** [comment]
By following instructions in https://fedoraproject.org/wiki/KDE I am able to get a full KDE desktop session running, which is certainly not what I am looking for. How do I get my `fedora-25` TemplateVM to use KDE entirely and not use Gnome at all?

**Comment by marmarek** [comment]
If I understand your question, you simply want to install and use KDE applications - so, konsole instead of gnome-terminal, dolphin instead of nautilus etc. After installing them, you can choose what you want to have in menu using VM settings.

**Comment by aQubesUser** [comment]
No, you do not understand my question. I am not trying to simply install and use KDE applications instead of Gnome applications.

My KDE applications are being rendered using Gnome and not KDE, any changes that I make in `systemsettings5` do not affect my KDE applications as they are being rendered with Gnome. Please the following screenshots:

Konsole with KDE in dom0:
![konsole-kde](https://user-images.githubusercontent.com/25757046/29800904-22d54c12-8c5c-11e7-8171-ab3cccbbde48.png)

Konsole with Gnome in a VM that uses the `fedora-25` TemplateVM:
![konsole-gnome](https://user-images.githubusercontent.com/25757046/29800912-37682618-8c5c-11e7-8f2b-7ecc3f0a6dce.png)

When my applications are rendered with Gnome, any changes I make in `systemsettings5` have no effect as the KDE applications aren't being rendered with KDE.

**Comment by aQubesUser** [comment]
A workaround is to install `gnome-tweak-tool` and `breeze-gtk` and set the theme through the tweak tool.

Thank you.

**Comment by aQubesUser** [comment]
An additional comment for anyone who may be trying to achieve consistent themes across VMS: if you have a Fedora VM that was upgraded from an older version of Fedora, you may find that KDE programs do not get themed properly despite having changed settings in `gnome-tweak-tool`. This may be due to some old settings that the VM somehow hasn't stopped using. I don't know which file(s) this could be caused by but creating a new VM, reinstalling the required programs (a list can be generated with `sudo dnf list installed`) and copying files over allowed me to ensure that all of my VMs are consistently themed.

Thanks

**Comment by naith** [comment]
I`m solve this trouble in Mint. Render for KDE app (Krusader, etc.) is Gnome. In my case solve this trouble qt4-qtconfig. System settings for KDE says this same error.

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
