### ISSUE TITLE
4.0rc1 standalone & dispVM templates cannot be created

### ISSUE THREAD

**Issue by 3hhh** [QubesOS/qubes-issues#3017]
I didn't find a method in 4.0rc1 to create either standalone or dispVM templates.

Standalone VMs:

- qubes-vm-create has "Standalone" grayed out.
- There doesn't seem to be a straightforward command-line utility.

DispVM templates:

- qvm-create-default-dvm from https://www.qubes-os.org/doc/dispvm-customization/ was apparently removed.
- There doesn't seem to be a another command-line utility.

If there's methods that I'm not aware of, I guess this could be merged into a general doc update issue for 4.0rc1.

**Comment by marmarek** [comment]
> There doesn't seem to be a straightforward command-line utility.

`qvm-create --class StandaloneVM`
We're working on GUI for this.

> There doesn't seem to be a another command-line utility.

Just set 'dispvm_allowed' property to true on desired AppVM. There is no "DispVM savefile" in Qubes 4.0, so `qvm-create-default-dvm` doesn't make sense.

I'm keeping this open as a documentation issue.

**Comment by 3hhh** [comment]
Thanks for the clarification!

**Comment by 3hhh** [comment]
P.S.: qvm-create --help could list the available classes.

**Comment by marmarek** [comment]
https://www.qubes-os.org/doc/disposablevm-customization/ is updated. There is also `qvm-create --help-classes`. And a GUI.
