### ISSUE TITLE
4.0rc1 - VPN-only VM doesn't show up in widget

### ISSUE THREAD

**Issue by seandilda** [QubesOS/qubes-issues#3019]
#### Qubes OS version (e.g., `R3.2`):
`4.0rc1`

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):
`fedora-25`
---

### Expected behavior:

I should be able to manage VPN settings for a NetVM in the widget.  This VM uses sys-net for its NetVM and some (but not all) of the other AppVMs use this vpn VM for their NetVM.

### Actual behavior:

The VPN settings are only manageable through the widget if I unset the 'NetVM' value on my VpnVM - which means I can't use it for establishing a VPN session.

### Steps to reproduce the behavior:

Create a new VM, select 'Provides network'.  Edit VM to ensure NetVM is set, turn on VM.  See its not shown in the widget.

### General notes:

I know some NetVMs (it sys-firewall) shouldn't show up in the widget.  Maybe another flag would be useful so I could specify 'Provides VPN services' or 'Needs networking UI'

---

**Comment by marmarek** [comment]
Go to 'Services' tab in VM settings and add 'network-manager' entry. This will enable NetworkManager widget in this VM. See [here](https://www.qubes-os.org/doc/dom0-tools/qvm-service/) for other available values.

**Comment by seandilda** [comment]
Thanks!  

I'd already added the network-manager bit. Unfortunately, I'm still seeing the problem.  I've figured out that if I configure my VPN vm with a NetVM of none and start it, it will show up in the widget.  I can then edit it live to use a NetVM of sys-net and it'll then show connected in the widget.  Unfortunately, if I then shutdown and start the VPN VM again, it doesn't show up in the widget after that.

**Comment by marmarek** [comment]
Indeed looks like notifying VM about enabled 'network-manager' service is broken.
