### ISSUE TITLE
qvm-prefs: allow for on the fly netvm switch

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#302]
**Reported by joanna on 18 Jul 2011 13:11 UTC**
When the user types:

```
qvm-prefs -s SomeAppVM netvm SomeNetVM
```

and if the SomeAppVM already is running, qvm-prefs should automatically re-attach the SomeAppVM to the new SomeNetVM (also making sure to reinitialize networking in SomeAppVM). This seems simple, yet would be extremely useful for users that decided to have a separate UsbVM and keep their 3G modem there. Then switching between WiFi and 3G modem would be just a matter of setting a different netvm for the firewallvm.

Migrated-From: https://wiki.qubes-os.org/ticket/302

**Comment by ptitdoc** [comment]
Maybe this should be reopened ?

In my case (using Qubes 3.1 packages), it raises an error:
Error: Basic tab:
internal error: libxenlight failed to detach network device

**Comment by marmarek** [comment]
On Tue, Dec 08, 2015 at 12:06:14AM -0800, ptitdoc wrote:
> Maybe this should be reopened ?
> 
> In my case (using Qubes 3.1 packages), it raises an error:
> Error: Basic tab:
> internal error: libxenlight failed to detach network device

This is #975, already reopened...
And just to be sure - what kernel verion in VM do you have (pleasse
comment in #975)?

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?
