### ISSUE TITLE
VM Occasionally Freezes

### ISSUE THREAD

**Issue by stone212** [QubesOS/qubes-issues#3021]
#### Qubes OS version (e.g., `R3.2`):
R 3.2

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):

Only tested on Debian 8 and 9
---

### Expected behavior:

Keyboard, mouse, etc. respond to your input at all times.

### Actual behavior:

Occasionally, a VM will freeze up for 30 seconds or more.  In rare cases, VM restart is required.  When this happens, the other VMs are just fine

### Steps to reproduce the behavior:

Have 3 VMs open, use them normally (browsing, terminal, email, etc.)  Every now and then, one of the VMs will freeze as described above, meaning that keyboard and mouse no longer can affect applications from that VM.  

### General notes:

Using an i7 with 16GB RAM and an SSD so I don't think the problem is with the computer?
---

**Comment by aQubesUser** [comment]
I have experienced "freezing" VMs as well when using `fedora-23` and running services like an I2P router. Programs like `yakuake` will fail to respond to the configured hotkey and require a full restart of the VM. Other applications such as `firefox` or `chromium` will continue to function if already open but trying to run additional programs will not work. A restart of the VM fixes the issue.

**Comment by stone212** [comment]
I am not running fedora-23, I am not running I2P or anything similar, and I don't know waht yakuake is.  Often all I am running is a terminal and Firefox, and that is when the freeze happens.

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
