### ISSUE TITLE
Missing HVM-Option at qvm-create

### ISSUE THREAD

**Issue by thraab** [QubesOS/qubes-issues#3024]
#### Qubes OS version (e.g., `R3.2`):

4.0 RC1

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):
---

### Expected behavior:
Tried to create a new HVM-VM like it was described in the tutorial (https://www.qubes-os.org/doc/hvm/)

The command _qvm-create win7 --hvm --label green_ should lead to a new vm.

### Actual behavior:
Actually the output of the command above is _qvm-create: error : unrecognized arguments: --hvm_
### Steps to reproduce the behavior:
Type in the command sequence above.

**Comment by marmarek** [comment]
As announced earlier, in Qubes 4.0 every VM is HVM by default.

**Comment by thraab** [comment]
Thanks, didnt knew that :)

**Comment by marmarek** [comment]
Anyway, you're probably looking for --class option, to specify `StandaloneVM` (unless you want template-based VM - which is default).

**Comment by marmarek** [comment]
Keeping open as documentation issue.
