### ISSUE TITLE
qvm-usb (dom0) uninformative error message -- R4.0-rc1

### ISSUE THREAD

**Issue by 0spinboson** [QubesOS/qubes-issues#3026]
#### Qubes OS version (e.g., `R3.2`):
R4.0 rc1
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):
dom0, fedora-25, debian-9

---

### Expected behavior:
USB device is passed through to AppVM (in this case, a printer, usb 2.0 or 1.1)
### Actual behavior:
Aug 14 17:34:04 dom0 qubes.USB+1-3-Writing[17651]: /bin/sh: /etc/qubes-rpc/qubes.USB: No such file or directory
Aug 14 17:34:04 dom0 qubesd[2195]: QubesUSBException('Device attach failed: Invalid speed received',) while calling src=b'dom0' meth=b'admin.vm.device.usb.Attach' dest=b'Writing' arg=b'dom0+1-3' len(untrusted_payload)=0
Aug 14 17:34:12 dom0 qrexec[17668]: qubes.USB+1-3: Writing -> dom0: allowed to dom0
Aug 14 17:34:12 dom0 qubes.USB+1-3-Writing[17685]: /bin/sh: /etc/qubes-rpc/qubes.USB: No such file or directory
Aug 14 17:34:12 dom0 qubesd[2195]: QubesUSBException('Device attach failed: Invalid speed received',) while calling src=b'dom0' meth=b'admin.vm.device.usb.Attach' dest=b'Writing' arg=b'dom0+1-3' len(untrusted_payload)=0

### Steps to reproduce the behavior:
qvm-usb a name dom0:xx:yy
### General notes:
Haven't gotten a USB Qube going yet, and can't test this on short notice.

**Comment by marmarek** [comment]
Currently qvm-usb do not support attaching devices from dom0. While technically it could be implemented, much better idea is to have USB Qube.
Of course, there should be meaningful error message, not the thing you've got.

**Comment by 0spinboson** [comment]
Aha. Okay, I guess I'll have to set that up then. :)

**Comment by 0spinboson** [comment]
ok, that's WAI. I did have to enable pv mode for the usb qube, but I guess that was to be expected. Also got some others related to device resets, will look into those more later (no time now).

**Comment by marmarek** [comment]
@rootkovska what should we do about this? There are two options:
 - improve error message about not supporting dom0 as "USB VM" (or even, not list USB devices in dom0)
 - add support for attaching USB device from dom0 (no separate USB VM)

The former should encourage usage of USB VM, but there are cases incompatible with USB VM - like booting from USB. And there, using qvm-usb to attach device to some VM could still be better than doing things directly in dom0. What do you think?

**Comment by 0spinboson** [comment]
are there also PCs/laptops with only a single USB controller? If not, I'd say 1 is the better option (even if it's probably too much to ask from most people to figure out which controller controls which ports, then only using the dom0 ports for the USB HDD while assigning the other(s) to a USB VM).

**Comment by marmarek** [comment]
Unfortunately there are a lot of systems with a single USB controller. Most of new Intel-based ones.

**Comment by rootkovska** [comment]
I'm voting against making it easy to keep any USB devices in dom0. I don't think LiveUSB booting justifies this.
