### ISSUE TITLE
Add LXQt

### ISSUE THREAD

**Issue by IPv777** [QubesOS/qubes-issues#3027]
Improvement idea : 
Could you add the support of LXQt desktop environment ?
https://github.com/lxde/lxqt

**Comment by alimirjamali** [comment]
Native support for LXQt's `pcmanfm-qt` was added two months ago. But only for Debian:

https://github.com/QubesOS/qubes-core-agent-linux/commit/5a3b7cc13e56ab62452aef002bf50a83bce7d47c

To be consistent, it might be a good idea to add this to Fedora and Archlinux packages as well.

p.s.: The same applies to pdf and image converter plugins
