### ISSUE TITLE
sys-net often fails to reconnect after resuming from sleep on kernel 4.9

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#3030]
#### Qubes OS version (e.g., `R3.2`):

`R3.2`

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):

all

---

### Problem description:

~~When `sys-net` is based on `fedora-25`, `sys-net` frequently fails to connect to any network after the system resumes from sleep. This was not a problem on `fedora-24*` templates.~~ The problem is actually kernel 4.9. See comments below.

When this happens, it is necessary to restart `sys-net` in order to resolve the problem.

**Comment by marmarek** [comment]
Can you confirm it's related to fedora-25, not 4.9 kernel?

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by andrewdavidwong** [comment]
Would switching `sys-net` back to the `fedora-24-minimal`-based template be a good way to test that?

**Comment by andrewdavidwong** [comment]
@marmarek: You're right. The same problem occurs when I switch `sys-net` back to the `fedora-24-minimal`-based template, so the problem must be the 4.9 kernel.

**Comment by andrewdavidwong** [comment]
It looks like this is probably a duplicate of #3008.
