### ISSUE TITLE
 4.0 - Feature Reqest: '--skip-if-halted' for 'qvm-shutdown' 

### ISSUE THREAD

**Issue by r-cheologist** [QubesOS/qubes-issues#3032]
#### Qubes OS version (e.g., `R3.2`):
4.0-rc1
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):
dom0

---

### Expected behavior:
Analogous to the capabilities of 'qvm-start' ('--skip-if-running'), 'qvm-shutdown' is expected to have the option '--skip-if-halted'.

### Actual behavior:
Not implemented.

**Comment by kalkin** [comment]
Why do we have `--skip-if-running` at all? I would expect both just to exit with `0` if the VM is already started or shutdown.

**Comment by r-cheologist** [comment]
On 2017-08-16 22:31, Bahtiar Gadimov wrote:

> Why do we have --skip-if-running at all? I would expect both just to exit with 0 if the VM is already started or shutdown.

Sadly `qvm-start` throws an error insted if the requested vm is running
... as does `qvm-shutdown` if the requested vm is already halted.

**Comment by r-cheologist** [comment]
I agree with @kalkin above, that not having any skipping option at all and just exiting if a vm already exists would be the preferable option for both `qvm-start` and `qvm-shutdown` ... the current error throwing behavior could be retained with an option like `--must-work` ...
