### ISSUE TITLE
 4.0-rc1 - No 'qvm-trim-template'

### ISSUE THREAD

**Issue by r-cheologist** [QubesOS/qubes-issues#3033]
#### Qubes OS version (e.g., `R3.2`):
4.0-rc1
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):
dom0

---

### Expected behavior:
Analogously to 3.2, 4.0(-rc1) should have 'qvm-trim-template'.

### Actual behavior:
Not implemented.

**Comment by esote** [comment]
@marmarta Is this command even needed for R4? Don't they use thin pools now?

**Comment by esote** [comment]
@marmarek Is this command even needed for R4? Don't they use thin pools now?

**Comment by esote** [comment]
@andrewdavidwong This can be closed from the documentation I linked above
