### ISSUE TITLE
Accepting license change to "LGPLv2.1 (or later)"

### ISSUE THREAD

**Issue by qubesuser** [QubesOS/qubes-issues#3034]
I just noticed that a request to relicense all contributions to qubes-core-devel was posted to qubes-devel, which mentioned contributions done with this GitHub account.

I accept the change and thus license any code submitted using this GitHub account under the LGPLv2.1 or later as published by the Free Software Foundation in addition to the previous licenses.

Creating an issue to send this since I don't know of any better way of authenticating a message using a GitHub account; feel free to close it.

**Comment by Jeeppler** [comment]
@andrewdavidwong @marmarek have a look at the comment from @qubesuser.

**Comment by andrewdavidwong** [comment]
Message received. Thank you!

(Assigning this for Marek to close once he records your response.)
