### ISSUE TITLE
Failing to start HVM

### ISSUE THREAD

**Issue by KuroSaru** [QubesOS/qubes-issues#3036]
#### Qubes OS version (e.g., `R3.2`):
4.0

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):
HVMs

---

### Expected behavior:
To boot from the HVM image.

### Actual behavior:
Boots from ROM and loading current Qubes kernel

### Steps to reproduce the behavior:
Try to load standalone HVM that is not based on qubes templates. eg Win7, NetBSD etc..

### General notes:
Within /usr/lib/python3.5/site-packages/qubes/vm/qubesvm.py @ Line 443 we have 

kernel = qubes.property('kernel', type=str,
   setter=_setter_kernel,
   default=(lambda self: self.app.default_kernel),
   doc='Kernel Used by this domain.')

if this is replaced with...

if virt_mode == 'pv':
   kernel = qubes.property('kernel', type=str,
      setter=_setter_kernel,
      default=(lambda self: self.app.default_kernel),
      doc='Kernel Used by this domain.')
else:
   kernel = qubes.property('kernel', type=str,
      setter=_setter_kernel,
      default=(lambda self: self.app.default_kernel),
      doc='Kernel Used by this domain.')

It becoems possible to load the Qubes HVM's that are all set to PV and it also becomes to load a HVM (Windows 7) Image that was restored from 3.2. granted it is very unstable and can get BSODs but networking and disk I/O works for the most part perfectly fine.

---

**Comment by KuroSaru** [comment]
Turns out this can be fixed alot easier and is less of a bug just a gremlin for a lack of documentation about the qubes.xml format.

if you remove the <volume name="kernel" and add a <property name="kernel" instead it will boot from the image and not a ROM image.

**Comment by 0spinboson** [comment]
just for completeness's sake, what exactly do I have to add on that <property name="kernel"></property> line? When I leave it empty like so, I get a complaint about the boot device being missing.

**Comment by marmarek** [comment]
The correct way to boot from VM image (not qubes kernel) is to set "kernel" property to empty string:
```
qvm-prefs vmname kernel ''
```
No qubes.xml or source modifications are needed.

**Comment by marmarek** [comment]
qvm-prefs man page already have updated text.
