### ISSUE TITLE
Setup script in Qubes-builder still fails to find dependencies when building template

### ISSUE THREAD

**Issue by murlengleckeen** [QubesOS/qubes-issues#3038]
Trying to build an Ubuntu-template, I followed the instructions given [here](https://www.qubes-os.org/doc/building-archlinux-template/) except for choosing  builder-debian as builder plugin and zesty+desktop as template.

#### Qubes OS version (e.g., `R3.2`):
R3.2

### Expected behavior:
* resolve dependencies by running `make install-deps`
* run `./setup`
* start building by running `make vmm-xen-vm`
### Actual behavior:
* running `make vmm-xen-vm` fails stating:
```
[user@devel qubes-builder]$ make vmm-xen-vm
Currently installed dependencies:
git-2.9.5-1.fc25.x86_64
rpmdevtools-8.9-1.fc25.noarch
rpm-build-4.13.0.1-1.fc25.x86_64
createrepo-0.10.3-10.fc25.noarch
debootstrap-1.0.87-1.fc25.noarch
dpkg-dev-1.17.27-1.fc25.noarch
package python-sh is not installed
dialog-1.3-5.20160828.fc25.x86_64
dpkg-dev-1.17.27-1.fc25.noarch
debootstrap-1.0.87-1.fc25.noarch
ERROR: call 'make install-deps' to install missing dependencies
Makefile:202: recipe for target 'check-depend.rpm' failed
make: *** [check-depend.rpm] Error 1
```
### Steps to reproduce the behavior:
* see above
### General notes:
a very similar issue has been reported [here](https://github.com/QubesOS/qubes-issues/issues/2910). The problem was that `make install-deps` installs `python2-sh` whereas the Makefile expected `python-sh`.  However the given solution didn't work for me as the Makefile already contained the needed change.

### Solution
On building a template it seems that Qubes-builder uses the `/example-configs/templates.conf` as `builder.conf` which still contains `python-sh` instead of `python2-sh`.
Changing the line `DEPENDENCIES += python-sh dialog` to `DEPENDENCIES += python2-sh dialog` in `builder.conf` solved the problem.

---

#### Related issues:
#2910

**Comment by yitjob** [comment]
Since python2-sh as such, was not installed (neither found to install) when installing dependencies, I had to edit https://github.com/QubesOS/qubes-builder/blob/d85b004e9f375acd8aa104f30e1166ca1c7d2b7b/Makefile#L36 and remove the 2.

**Comment by unman** [comment]
@yitjob You must be using an outdated release of Fedora. Try using a Fedora25 template in your build qube.

@andrewdavidwong After merger of https://github.com/QubesOS/qubes-builder/pull/28 this can be closed.
