### ISSUE TITLE
Add "console type=pty" to HVM domain configuration

### ISSUE THREAD

**Issue by kitambi** [QubesOS/qubes-issues#3039]
#### Qubes OS version (e.g., `R3.2`):
4.0rc1
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):
All HVM

---

### Expected behavior:
"xl console" connects to the VM's console
### Actual behavior:
xenconsole: Could not read tty from store: No such file or directory
### Steps to reproduce the behavior:
Run "sudo xl console <hvm_domain>"
### General notes:

We can avoid the overhead of the "debug mode" virtual VGA console by adding this option, and also setting up HVM templates with serial consoles.  It's also convenient when you're troubleshooting a template that you're hacking on, because a reboot won't be required to get onto the console. 
---

**Comment by marmarek** [comment]
You can use `sudo xl console -t pv <hvm_domain>` for this. Appropriate device is set already. Unfortunately it isn't possible to change default behavior of `xl console` (-t pv option) from domain config.

Bonus: even without debug mode, you can access VGA console with `qvm-start-gui --force-stubdomain VMNAME`
