### ISSUE TITLE
Template & Configuration Manager

### ISSUE THREAD

**Issue by rootkovska** [QubesOS/qubes-issues#3040]
We need an easy to use, GUI-based tool for managing templates and system-wide configuration. This includes:

  - Listing available templates to install (from enabled repositories, i.e. `qubes-templates-*`), AppStore-like way, and letting the user to perform the installation with a click of a button,
  - Similarly offering Salt Configs from enabled repositories,
  - Allowing to easily upgrade templates (e.g. fedora 24 -> fedora 25), while automatically re-installing all the packages that were installed in the original template (see #2477)
  - Allowing to easily update templates and AdminVM with a single click (but honor don't update/check updates for select templates/standalone VMs)
  - Potentially we might want to also merge the backup/restore functionality into this?

**Comment by andrewdavidwong** [comment]
@marmarek, @ninavizz: Many of these things have been suggested, requested, or proposed as separate tools or interfaces more recently. Should this issue be closed as "won't do" if we no longer want to pursue a single interface or tool that encompasses all of this functionality?

**Comment by ninavizz** [comment]
@andrewdavidwong I'm personally ok with that, as long as you 'cc those issues, here, so there can be cross-linking. Many of these older issues have great ideas in them (like this one!) and my only concern is those great ideas not being lost. But, I do love the idea of simplifying the Issues repo and have craved wanting to see this done for some time.

**Comment by andrewdavidwong** [comment]
Closing as "won't do." If anyone has a new reason for why this should be done, please leave a comment, and we'll be happy to take another look. Thank you.

**Comment by andrewdavidwong** [comment]
> my only concern is those great ideas not being lost. 

Nothing is ever lost, because closed issues continue to exist just as much as open issues, and they're just as searchable. Many people think of "closed" as meaning "gone," but it's really implemented more like a label.
