### ISSUE TITLE
Use qubes.StartApp service by default for qvm-run when no --pass-io specified

### ISSUE THREAD

**Issue by rootkovska** [QubesOS/qubes-issues#3043]
As discussed in #3012. While this is strictly not a bug, not fixing this for 4.0 release we can be sure to receive many bug reports for qvm-run not working by default, especially for DispVMs.

**Comment by marmarek** [comment]
Note that the argument to `qubes.StartApp` is not a command name, but application name, as in `/usr/share/applications`. While for `xterm` or `firefox` it is the same, for others may not be: for example Nautilus is `org.gnome.Nautilus`.
This is done to allow "staring application in a VM", without giving arbitrary command execution.
#3012 require different solution, but lets discuss is there. Not in (this) duplicate.
