### ISSUE TITLE
Create default DispVM template at firstboot stage

### ISSUE THREAD

**Issue by rootkovska** [QubesOS/qubes-issues#3046]
Since normal templates cannot be used to start an AppVM from them we should have firstboot create a *-dvm template (name compatibility with 3.2) to serve this purpose.

**Comment by marmarek** [comment]
It is already created there (fedora-25-dvm). For rc2 I've created [salt formula](https://github.com/QubesOS/qubes-mgmt-salt-dom0-virtual-machines/blob/master/qvm/default-dispvm.sls) to create it - to ease the task for those who have skipped it during firstboot, for any reason (including some error during the
process).
