### ISSUE TITLE
Qubes OS added to mirrors.dotsrc.org (Denmark)

### ISSUE THREAD

**Issue by AndersTrier** [QubesOS/qubes-issues#3056]
Hi!

We just added Qubes OS to the mirrors.dotsrc.org server. It is located at Aalborg University, and we have 10gbit uplink. Feel free to send some traffic our way. For contact use staff@dotsrc.org

http://mirrors.dotsrc.org/qubes/
https://mirrors.dotsrc.org/qubes/
ftp://mirrors.dotsrc.org/qubes/
rsync://mirrors.dotsrc.org/qubes/

We currently pull from ftp.qubes-os.org every 6 hours -- is that fine?

**Comment by andrewdavidwong** [comment]
Thank you, @AndersTrier! Yes, I think every 6 hours should be fine. (CCing @marmarek to confirm.)

**Comment by woju** [comment]
@AndersTrier: Yes, that's OK. Thanks for the mirror!

If you like, we're happy to provide rsync access, preferably once per day (as
mirrors.kernel.org does), but 6 hours is OK. If so, please contact me at
woju@invisiblethingslab.com.
