### ISSUE TITLE
qvm-create --class Standalone fails when a template is specified

### ISSUE THREAD

**Issue by yomimono** [QubesOS/qubes-issues#3060]
#### Qubes OS version (e.g., `R3.2`):

4.0 RC1

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):

dom0 (fc25)

---

### Expected behavior:

`qvm-create --class StandaloneVM -l blue --template debian-8 uservm` makes a standalone appVM called uservm based on the debian-8 template.

### Actual behavior:

No appvm is created and the command returns an error message:

```
app: Error creating VM: got empty response from qubesd
```

### Steps to reproduce the behavior:

`qvm-create --class StandaloneVM -l blue --template debian-8 uservm`

### General notes:

`qvm-create --class StandaloneVM -l blue uservm` succeeds, but `qvm-create --class StandaloneVM -l blue --template fedora-25 -v ocaml` also gets an empty response from qubesd.

---

#### Related issues:

https://github.com/QubesOS/qubes-issues/issues/3017 may be related.

**Comment by marmarek** [comment]
This is because StandaloneVM does not have template. To create StandaloneVM with system copied from template, use `qvm-clone --class StandaloneVM`

**Comment by yomimono** [comment]
Ah, thanks, that works fine.

**Comment by unman** [comment]
This is now fixed (definitely in current package qubes-core-admin-client-4.0.25)
Works exactly as expected, creating standalone based on the template.
@andrewdavidwong  Please close.
