### ISSUE TITLE
refresh lag of VM windows with kernel 4.9.x on thinkpad t450s

### ISSUE THREAD

**Issue by taradiddles** [QubesOS/qubes-issues#3061]
Qubes 3.2, fully updated.

With kernel 4.9.x (tested with 4.9.35-20) on a thinkpad t450s, VM windows are randomly refreshed ; for instance:
- pressing a key for a while in a VM (terminal, editor, ...) outputs a few letters as expected, then stops, then outputs a bunch of letters at once, and so on, with random refresh intervals.
- when browsing with firefox, typing or scrolling has no effect, but waiting a random amount of time or pressing alt-tab triggers a refresh and shows the scrolled page or typed text.
- ...

This affects only VMs: dom0 apps are refreshed properly.

There wasn't any problem with 4.4.x kernels ; a quick diff of  /sys/modules/i915/parameters/* shows there were a few changes between 4.4.x and 4.9.x kernels. Reverting enable_fbc to 0 fixed the issue (i915.enable_fbc=0 in grub ; echo 0 > enable_fbc at runtime didn't work).

Given that dom0 apps are properly refreshed with enable_fbc=1, it looks like the issue is specific to Qubes.

(as a side note I helped some guys at Intel debug PSR on that specific laptop a while ago, and they found out that t450s' displays aren't all the same; I don't know if it is related to frame buffer compression though. Given that t450s are popular laptops with qubes users it's strange that nobody else reported it - or maybe I didn't search properly for such issues).

**Comment by marmarek** [comment]
I hit similar problem on a totally different laptop. Disabling IOMMU for GPU (`iommu=no-igfx` to xen cmdline) resolved the issue there. IOMMU misconfiguration for integrated GPU is a known issue on some CPU + BIOS combinations...

**Comment by taradiddles** [comment]
Sorry for the late feedback. Setting iommu=no-igfx didn't help so the problem is probably different from the one you're encountering with your other laptop.

Low prio anyway - the only drawback of i915.enable_fbc=0 is a slight power usage increase.

**Comment by taradiddles** [comment]
upgraded to Qubes 4.0rc3, no problem with enable_fbc=1, something was likely fixed in the kernel upstream.
-> closing.
