### ISSUE TITLE
Qubes-devel mailing list disappeared

### ISSUE THREAD

**Issue by MarioGeckler** [QubesOS/qubes-issues#3065]
#### Qubes OS version (e.g., `R3.2`):
None
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):
None

---

### Expected behavior:
qubes-devel mailing list is shown
### Actual behavior:
qubes-devel mailing list does not exist any more
### Steps to reproduce the behavior:
Go to https://groups.google.com/forum/#!forum/qubes-devel
### General notes:
https://groups.google.com/forum/#!topic/qubes-users/5dlq9-J8QEc

---

**Comment by andrewdavidwong** [comment]
@marmarek: Do you see the option to submit an "appeal" anywhere?

**Comment by andrewdavidwong** [comment]
Correction: Only @rootkovska can submit an appeal, since she is the list owner.

Discussion thread on the qubes-project list:
https://groups.google.com/d/topic/qubes-project/WVh6F2hqGlE/discussion

**Comment by rootkovska** [comment]
I just got back from holidays, logged in to qubes-devel's Google Groups account and requested ban to be removed.

**Comment by marmarek** [comment]
The mailing list is back :)
