### ISSUE TITLE
qvm-backup does not accept a relative path for backup_location

### ISSUE THREAD

**Issue by yomimono** [QubesOS/qubes-issues#3066]
#### Qubes OS version (e.g., `R3.2`):

R4.0 RC1

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):

n/a

---

### Expected behavior:

`qvm-backup my_rad_backup_folder app1 app2` results in app1 and app2 backups in my_rad_backup_folder

### Actual behavior:

qvm-backup fails stating that `my_rad_backup_folder` can't be found; giving `$(pwd)/my_rad_backup_folder` instead succeeds.

### Steps to reproduce the behavior:

Try `qvm-backup` with a relative path.

### General notes:

If this is intended there should probably be clearer documentation; `qvm-backup --help` doesn't say that it needs a full path for this argument, nor does the man page.

---

**Comment by marmarek** [comment]
Yes, absolute path is required. I'll update documentation.
