### ISSUE TITLE
EFI System Pertition misleading error during installation

### ISSUE THREAD

**Issue by cmassera** [QubesOS/qubes-issues#3067]
#### Qubes OS version (e.g., `R3.2`):

R4.0rc1

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):

Installation procedure
---

### Expected behavior:

When a partition /boot/efi is created and assigned Device Type EFI System Partition the installation should continue

### Actual behavior:

An error occurs that there is not EFI Partition for /boot/efi

**Comment by mex20** [comment]
Is there any more information that you can give us? If you are appending the boot parameters to boot the USB with “efi=no-rs” then this error will  occur during install. I received this error when attempting to install with the mentioned modified boot parameters.
