### ISSUE TITLE
qvm-run -p should redirect stdin and stdout separately

### ISSUE THREAD

**Issue by 3hhh** [QubesOS/qubes-issues#3074]
Every call to `qvm-run -p` redirects _both_ stdin and stdout.

Especially stdin is usually not necessary and may lead to unexpected behavior or even unexpected leaks from dom0 code.

Simple example:
```bash
#!/bin/bash

list="super"$'\n'"secret"

while IFS= read -r item ; do
        echo "item: $item"
        qvm-run -p -u root sys-usb "true"
done <<< "$list"
```

This will break after the first run and make qvm-run read the entire list during the first iteration (I'm not sure whether it is actually passed to sys-usb?). It works without -p.

I'd recommend to introduce different flags for stdin and stdout or at least support a flag to disable the stdin redirect (ssh e.g. uses -n).

Similar issue with ssh: https://stackoverflow.com/questions/346445/bash-while-read-loop-breaking-early

Affects both 3.2 and 4.0rc1.

**Comment by marmarek** [comment]
If you don't want either stdin or stdout, use standard shell features: `</dev/null` or `>/dev/null`.

**Comment by 3hhh** [comment]
True, but that makes e.g. bash aliases impossible.

In general I'd also recommend to opt-in to functionality rather than having to opt-out, but well...
