### ISSUE TITLE
this is a question more then a issue

### ISSUE THREAD

**Issue by in1t3r** [QubesOS/qubes-issues#3075]
Why you wouldn't try to move to QEMU/KVM as the virtualization instead of depending on Xen for PV ?
---

**Comment by marmarek** [comment]
https://www.qubes-os.org/doc/user-faq/#why-does-qubes-use-xen-instead-of-kvm-or-some-other-hypervisor

Also, use [mailing lists](https://www.qubes-os.org/mailing-lists/) for such questions.

**Comment by in1t3r** [comment]
thank you for andn basically you want to run Xen which have quite a bit of CVE's because you wouldnt like another monolithic kernel in dom0
