### ISSUE TITLE
Adding a second monitor fails

### ISSUE THREAD

**Issue by ajmeese7** [QubesOS/qubes-issues#3076]
#### Qubes OS version (e.g., `R3.2`):
R3.2
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):

---

### Expected behavior:
When I went into display settings and saw my second monitor, I clicked the "Use this display" button and it should have let me use my second display.

### Actual behavior:
Qubes kicks me out to the sign in screen and won't let me sign back in unless I reinstall the entire operating system.

### Steps to reproduce the behavior:
Go to display settings and click "Use this display" on your second monitor.

### General notes:
I reinstalled Qubes twice and each time it did the same thing. I have 2 MSI GTX 970s running in SLI (at least in Windows. Not sure if it works in Qubes). I am using 1 HDMI port on each card.

---

**Comment by andrewdavidwong** [comment]
This is too localized for `qubes-issues`. Please consider posting this to the `qubes-users` mailing list instead. (You can read more about our mailing lists [here](https://www.qubes-os.org/mailing-lists/).)

`qubes-users` is intended for these sorts of questions and receives much more traffic, which means that your question is more likely to receive a response there.

**Comment by ajmeese7** [comment]
How is a broken feature too localized?

**Comment by andrewdavidwong** [comment]
It's likely that this issue is specific to your hardware configuration, which is what we mean by "too localized." I can't reproduce this on 3.2, and I know that this feature is, and has been, working for many other users on 3.2 too, so it seems very likely that this is a hardware-specific issue.

**Comment by ajmeese7** [comment]
Ok. Thank you for the clarification
