### ISSUE TITLE
qvm-copy-to-vm: Request refused

### ISSUE THREAD

**Issue by h01ger** [QubesOS/qubes-issues#3077]
#### Qubes OS version (e.g., `R3.2`):

R3.2 with 4.9.35-20 kernel

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):

all
---

### Expected behavior:

qvm-copy-to-vm works as it used to work…

### Actual behavior:

since a week or so, qvm-copy-to-vm fails to work with a short "Request refused".

hints how to debug the issue welcome!

**Comment by marmarek** [comment]
See qrexec log of the source vm in dom0.

**Comment by h01ger** [comment]
thanks, just two lines:

Rpc denied: $sourcevm $destvm qubes.Filecopy
eintr

**Comment by h01ger** [comment]
(misclicked)

**Comment by marmarek** [comment]
so, maybe policy indeed denied that call? Check policy in /etc/qubes-rpc/policy/qubes.Filecopy

**Comment by h01ger** [comment]
that file seems incomplete, based on the timing I assume its from me experimenting with salt :(
any hint how to recreate it / what content it should have?

**Comment by h01ger** [comment]
+thanks!

**Comment by marmarek** [comment]
Look for other files there. Default version: https://github.com/QubesOS/qubes-core-admin/blob/master/qubes-rpc-policy/qubes.Filecopy.policy

**Comment by h01ger** [comment]
thanks a lot, closing for real now.
