### ISSUE TITLE
Vaio Z Canvas EFI installation issue - PLEASE HELP!!!

### ISSUE THREAD

**Issue by jack777888** [QubesOS/qubes-issues#3082]
Qubes OS version R4.0 RC1

I am trying to install qubes 4.0 on my vaio canvas z model VJZ12AX0211S:
The specs are:
Display
12.3 in WQXGA+ IPS display touchscreen (2560 x 1704), 10-finger multi-touch support
Processor
Intel Core i7-4770HQ 2.20 GHz with Turbo Boost Technology up to 3.40 GHz
Memory
16GB DDR3L 1600 MHz
Hard drive size
512GB SSD
Intel Iris Pro Graphics 5200 with shared graphics memory
Ports
2 USB 3.0 (1 powered) • HDMI • Mini DisplayPort • Headphone output/Microphone input combo • LAN (10/100/1000)
Wireless
802.11ac/a/b/g/n (Miracast enabled)
Bluetooth
Bluetooth 4.1

I've put the installer on USB,  bios stared, secure boot disabled, etc....It starts but remain stuck after a few seconds. I can chose any install option but doesn't matter what,. it remain stuck after first 3 line of text. I don't have the legacy option in bios. Can you please let me know what should I do to install it? I've been tried the troubleshooting guide from the official page without any result.
I've made the memory stick using DD method under debian.
Please help. I'm new on this

**Comment by andrewdavidwong** [comment]
This is too localized for `qubes-issues`. Please consider posting this to the `qubes-users` mailing list instead. (You can read more about our mailing lists [here](https://www.qubes-os.org/mailing-lists/).)

`qubes-users` is intended for these sorts of questions and receives much more traffic, which means that your question is more likely to receive a response there.
