### ISSUE TITLE
4.0rc1 qvm-block doesn't work with dom0 loop devices

### ISSUE THREAD

**Issue by 3hhh** [QubesOS/qubes-issues#3084]
In 4.0rc1 qvm-block cannot attach loop devices created in dom0 to AppVMs. This did work in 3.2.

This is particularly annoying as the -A option was removed from qvm-block in 4.0rc1.

Example:
Create a loop device in dom0, e.g. /dev/loop55.
```
qvm-block a testVM dom0:loop55
qvm-block: error: backend vm 'dom0' doesn't expose device 'loop55'
```

`qvm-block a testVM dom0:/dev/loop55` results in the same error.

Attaching loop devices created in e.g. sys-usb to other VMs does work.

**Comment by 3hhh** [comment]
(Halfway) working procedure for sys-usb: #3073

**Comment by kushaldas** [comment]
I am also seeing the same error in my 4.0rc1 install. Was trying to attach an image file using a loop device to one domain.

**Comment by 3hhh** [comment]
`xl block-attach` works by the way (can be used as a workaround in the meantime).

**Comment by kushaldas** [comment]
@3hhh Thanks for the tip. I also tried after updating dom0 to current testing, still same error. I will try `xl block-attach` today.

**Comment by taonik** [comment]
I'm in the same situation.
I've tried `xl block-attach`, but it complains `no vdev specified in '/dev/loopX'`

**Comment by 3hhh** [comment]
Then you forgot the vdev...

`xl block-attach testVM phy:loop55 xvdz w`

xvdz is the vdev that will appear in testVM

**Comment by taonik** [comment]
It works, but then it fails to detach the block: `no suitable backend for disk xvdz`.
It seems to be an old problem (`qvm-block -A`).

**Comment by marmarek** [comment]
Generally using `xl block-attach` and `xl block-detach` mixed with libvirt (as used by qvm-block and others) is a bad idea, because libvirt keeps own view of the system internally.

**Comment by jsmaniac** [comment]
Note to people trying to mount their `/var/lib/qubes/xxx/yyy/zzz.img` in another AppVM: loopback devices that point inside `/var/lib/qubes` are excluded by `qvm-block attach`. What you should do then in dom0 is:

```
ln /var/lib/qubes/xxx/yyy/zzz.img xxx-yyy-zzz.img
sudo losetup -r -f xxx-yyy-zzz.img # -r for read-only
losetup --list | grep -F xxx-yyy-zzz.img # This shows e.g. /dev/loop42
qvm-block attach --ro some_vm dom0:loop42
