### ISSUE TITLE
Convert to trusted image not working

### ISSUE THREAD

**Issue by cartman4** [QubesOS/qubes-issues#3085]
#### Qubes OS version (e.g., `R3.2`):
R4.0-RC1

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):
fedora-25, debian-9

---

### Expected behavior:
get a image that is converted to trusted and a untrusted one

### Actual behavior:
only get the untrusted one

### Steps to reproduce the behavior:
make a fedora-25 based appvm and try to convert a .jpg file into a trusted one.
and use the nautilus menu on right-clicking the image. that only created the jpg-untrusted image

### General notes:
Using the terminal tool "qubes-img-converter" returns this error:

Traceback (most recent call last):
  File "/usr/lib/qubes/qimg-convert-client", line 25, in <module>
    import qubes.imgconverter
ImportError: No module named qubes.imgconverter

(Edit:Since i tried converting the image. i have a lot of dispXXX VMs in the nautilus menu for   copying/moving files to other VMs. They stay after restarting Qubes)

**Comment by rabbitear** [comment]
Qubes 4.0rc1

Also, when qvm-get-image is run in dom0, gets a traceback:

[user@dom0 ~]$ qvm-get-image
Traceback (most recent call last):
  File "/usr/bin/qvm-get-image", line 22, in <module>
    import qubes.qubes
ImportError: No module named qubes.qubes
