### ISSUE TITLE
Failed backups don't clean up after themselves

### ISSUE THREAD

**Issue by jpouellet** [QubesOS/qubes-issues#3087]
Failed backups (e.g. due to flaky external USB device disconnecting mid-backup) result in data in dom0's `/tmp/backup_*`. Multiple failed backups eventually result in "error: no space left on device" because of no space in dom0 /tmp, preventing any successful backups until restart (or `rm -rf /tmp/backup_*`).

**Comment by jpouellet** [comment]
Behavior observed on R3.2, haven't tried to confirm on R4.

**Comment by andrewdavidwong** [comment]
This appears to be a duplicate (or regression) of #777.
