### ISSUE TITLE
Typo in qvm-block docs

### ISSUE THREAD

**Issue by starius** [QubesOS/qubes-issues#3088]
[The page](https://www.qubes-os.org/doc/dom0-tools/qvm-block/) says:

> qvm-block - list/set VM PCI devices.

Probably it should be "list/set VM **block** devices."

**Comment by andrewdavidwong** [comment]
@marmarek: I was going to fix this, but it looks like the `qvm-block` man/help source file has been moved (or disappeared). Where does it live now?

**Comment by marmarek** [comment]
For Qubes 4.0 it's moved here: https://github.com/QubesOS/qubes-core-admin-client/tree/master/doc/manpages (qvm-device, a generic tool used as qvm-pci, qvm-block, qvm-usb).
For 3.2, it's still where it was, check release3.2 branch.

**Comment by andrewdavidwong** [comment]
For 3.2, it looks like it already says "List/set VM block devices.":
https://github.com/QubesOS/qubes-core-admin/blob/release3.2/qvm-tools/qvm-block#L38

Maybe the website page hasn't been synced?

For 4.0, it looks like this won't be relevant.
