### ISSUE TITLE
R3.2 HVM Win7 creation - Dom0 VM-Settings GUI issue - easy fix to remove major headaches!

### ISSUE THREAD

**Issue by Jommoner** [QubesOS/qubes-issues#3089]
#### Qubes OS version (e.g., `R3.2`):
QubesOS R3.2 - dom0 updated properly
Win7 64-bit genuine ISO (which has SP1 installed already.........)
 (the SP1 is fine but probably worsened the BSOD issue in my case - see end of my report)

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):
Win7 HVM creation via GUI, and probably any HVM operating systems needing more than 512MB ram.

### Expected behavior:
Following the guidelines for installing Win7, which start here:
https://www.qubes-os.org/doc/windows-appvms/
And then redirect you here for the actual HVM creation for Win7:
https://www.qubes-os.org/doc/hvm/

I can manage to install Windows fine (I had to use the 'cirrus' Win7.conf hack the first time but after deleting after BSOD and recreating VM under a different name, I haven't had to use that hack, which i weird but I am not complaining).

After this it should work, and I should be able to install the Qubes Windows tools etc.

### Actual behavior:
Before the final installation reboot, I cloned the Win7 VM and used that to try to bypass the BSOD...

After the final installation reboot, I get to enter my username, no password, and get into a windows desktop. If I do nothing, or enable automatic login, or anything else, it all works fine, and I can shut down. On rebooting the VM, I get a 'BSOD' quite quickly, saying the registry is corrupt.

Searching through the web, I have found that the issue is often caused when attaching a virtual CD-ROM to install the Qubes Windows tools, but also that some people complain it just happens anyway.

After much experimenting, I found that the problem is due to the VM, as standard, having 512MB ram. 512MB works all the way for the actual installation, but when you enter your username and get the actual Win7 desktop for the first time, for me, 100% of the time it would do the same BSOD (registry corrupt) and be trashed.

### Steps to reproduce the behavior:
Follow the guidelines as per the Qubes website. On the first reboot after the first desktop, without any configuration beyond stopping auto-login, I get a BSOD (registry corrupt) (note : using 512MB ram).

Using Xen or Cirrus video driver in the .conf file, and doing all combinations of auto-login, test-mode for drivers, attaching the tools CD or not (even if not installing the tools) - no matter what, the result is a BSOD.

The issue : 

'Max Memory' is greyed out in a HVM, and it is set at 512MB. 'Initial Memory' is also set at 512MB, and while it can be changed, it seems nonsensical to try to increase initial memory above the 'max memory' which is 'jammed' and greyed out at 512MB

My error : 

Seeing, in the VM settings, 'Max Memory' greyed out stuck at 512MB, I didn't increase the 'initial memory' as increasing the initial memory' beyond the 'Max memory' doesn't make any sense.

My fix:

I increased the initial memory to 1536MB (1024 may also have been fine, I haven't checked to see the lowest possible amount of RAM that works). The VM-Settings program complained, then increased the max memory to 1536MB!. I then used a snapshot that had been installed with 512MB, and saved before the final 'login to Win7 desktop' reboot, and it then worked fine, as opposed to a permanent BSOD / registry corruption.

Suggested 'fixes' for Qubes OS 3.2 (and later if 512MB is standard for a HVM)
1. VM-Settings GUI (R3.2, ??something similar in R4.0rc??)
 -> When making a HVM, change it so rather than initial memory and max memory, it just says 'total memory'. The greyed out 512MB 'max memory' for a HVM is counter-intuitive, and it feels 'silly' to increase the initial memory above the max memory.
 -> If it said 'Total memory:        512   MB' on the VM-Settings 'Advanced' tab, and was not greyed out,it would make sense and less people would have this particular issue with Windows 7.
 -> If it is difficult to redesign the Advanced VM-Settings tab due to using pre-designed window layouts, it could be possible to put a note at the top left after Memory/CPU ('Memory/CPU (note : if creating a HVM, set 'Initial memory' to the total memory of the machine, and the 'Max Memory' will be updated automatically') or something like this.

2. VM-Settings GUI (R3.2, ?applicable to aspects of 4.0 which I am not running yet)
 -> Setting the initial memory to 1024MB as standard would probably fix this issue without users needing to change it, while power-users will just decrease it for Fedora or Debian and probably increase it for Windows)

3. Website documentation : 
On this page:
https://www.qubes-os.org/doc/hvm/
Near the start, where it tells you how to create the HVM (qvm-create win7 --hvm --label green), there should be a major note below it, in bold, saying 'Please use the VM-Settings applet to increase Initial Memory to 1024MB, or there is a high chance of the install failing irreparably during, or even after the install, with a 'Blue Screen' describing registry corruption.

### General notes:
I did loads of testing to find out the above issue. Many people had problems installing the tools, whereas I had a problem trying to reboot after the first time I saw the desktop.

When the desktop first came up, the Windows taskmgr showed I was using about 380MB of RAM...
Once I managed to get it running by setting memory to 1536MB RAM, I found that, on the first reboot after first seeing the Windows destop, it worked fine, but, was using about 750MB RAM. I suspect that, in my case, this was the 'SP1' doing it's thing, and causing total failure with the standard 512MB ram. After shutting down and rebooting, the Windows taskmgr again showed about 380MB of RAM in use, and since then has remained that way.

Conjecture:
In my case, I think that the SP1 needing more than 512MB ram caused the BSOD, and I suspect this has happened to other people too. I also see that some people get the BSOD a while later when adding additional devices (CD for guest tools) or after installing the tools.

Once the install is complete, it is probably safe to lower the RAM to 512MB, using at least 512MB swap inside Windows, but it seems to be 'sensitive' in the early stages.

I would be grateful if this could be fixed, as it took me ages to fix the problem due to there being so many reports, mainly suggesting the problem was due to attaching a CD / virtual CD controller, or the Qubes tools - and in my case, it seems to be about the 512MB of RAM being the 'standard' setting.

#### Related issues:
Nil; I reinstalled the OS a few times while getting to know it, but now have a stable install (and I only tried to get Windows installed once I had a stable install). I am very happy with this OS, and hope to contribute more in the future!

**Comment by andrewdavidwong** [comment]
Thanks for the report. If you're interested in contributing the documentation fix, please see [here](https://www.qubes-os.org/doc/doc-guidelines/) for how to contribute.

**Comment by ucwhatic** [comment]
thank u x1000

**Comment by Jommoner** [comment]
I added an update for the documentation, but it failed to 'compile' and got lost in limbo; I have done my best to remove the update (which hadn't been reviewed due to the failure) and will look into it in a few weeks;

Please feel free to contact me or post here if this helps or if you have problems with Windows 7 HVM and BSOD! :)

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
