### ISSUE TITLE
After changing usb mouse, the new usb mouse only randomly works.

### ISSUE THREAD

**Issue by gdysufgs** [QubesOS/qubes-issues#3090]
#### Qubes OS version (e.g., `R3.2`):
Qubes R3.2
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):
fedora-24 / fedora-25 (sys-usb), dom0

---

### Expected behavior:
Qubes's dom0 + sys-usb accept new usb mouse after removing the old usb mouse.
### Actual behavior:
My old mouse is physically failing, so I wish to replace it with a new one. However when plugging in this new usb mouse it doesn't work most of the time in (i.e. cannot use it to move or click in dom0). I'm using the default sys-usb and the same behavior occurred with fedora-24 and fedora-25 for sys-usb.

The strange thing is occasionally that the new mouse does work by removing + re-entering the usb (+ wait time), restarting sys-usb, login back in after lock-screen time-out, coming out of suspended mode or a complete system reboot. All of this actions seem to have a very low chance (feels like 5%ish) to let the new mouse work in dom0. Some times even after trying a 100+ times the new mouse still doesn't connect, however after a system reboot it some times does. While I tried to find a pattern / causation, I was unable to find it so far expect that all of the above actions have a small chance of the giving the new mouse control over dom0 (5%ish) when mouse didn't had control before and a large chance of losing control over dom0 (95%ish) when the mouse did have control over dom0 before.

It didn't matter if Qubes OS was first booted with the old usb mouse connect, the new usb mouse connect or none usb mouse connect at all.

### Steps to reproduce the behavior:
Explain mostly in actual behavior, but: remove old usb mouse, connect new usb mouse.
### General notes:
Old usb mouse is a Logitech wireless usb mouse.
New mouse I actually tried two: a Trust wireless usb mouse and a Logitech wired usb mouse.

---

#### Related issues:
When left clicking (when the new mouse is in fact connected) occasionally a double/two left click is registered when I only clicked once. I noticed this mostly when opening a new tab in TBB/firefox (result: 2 open tabs) or closing a tab (result: 2 closed tabs).

**Comment by andrewdavidwong** [comment]
Are you sure the problem doesn't lie with the new mouse?

**Comment by gdysufgs** [comment]
I did use two different new mouses, they are both new. And especially that it does occasionally work, I did expect it to be a software problem and not my (new) hardware.

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
