### ISSUE TITLE
i3-dmenu-desktop fails (i3wm on 4.0RC1)

### ISSUE THREAD

**Issue by holiman** [QubesOS/qubes-issues#3091]
#### Qubes OS version (e.g., `R3.2`):

4.0 rc1

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):

---

### Expected behavior:

When launching `i3-dmenu-desktop` (in dom0), the dmenu is launched.

### Actual behavior:

Error message: 
```
Can't locate Data/Dumper.pm in @INC (you may need to install the Data::Dumper module)
[...]
at /usr/bin/i3-dmenu-desktop line 10
```
The   `i3-dmenu-desktop` script says `No dependencies except for perl >= v4.10`. The perl version in qubes is  `5.24.2`. 
If this line is commented, it further complans about a few more `File::Temp`,  `Getopt::Long`, `Pod::Usage` and `open`

### Steps to reproduce the behavior:
Install qubes 4.0 rc1. Then 
```
 sudo qubes-dom0-update i3 i3-settings-qubes
```
Boot in i3 (or not), and run `i3-dmenu-desktop`. 

### General notes:

I don't know if this is an issue that should be filed against i3wm or qubes. 

---

**Comment by holiman** [comment]
Related: 
(Dumper): https://rt.cpan.org/Public/Bug/Display.html?id=97846
(File::Temp) : https://bugs.launchpad.net/ubuntu/+source/update-manager/+bug/862129

**Comment by huntse** [comment]
The fix is to add
```perl-Data-Dumper 
perl-file-Temp 
perl-Getopt-Long 
perl-open```
...to the dependencies of i3-settings-qubes I'm pretty sure.  Installing those packages in dom0 fixed it for me.

**Comment by mannp** [comment]
Thanks @huntse that solved if for me.

perl-file-Temp -> perl-File-Temp though 👍

**Comment by holiman** [comment]
Noob question: How does one install packages (thar aren't in the qubes repo) to dom0?

**Comment by unman** [comment]
On Thu, Sep 21, 2017 at 08:21:57AM +0000, Martin Holst Swende wrote:
> Noob question: How does one install packages (thar aren't in the qubes repo) to dom0?  
> 

This is probably best for the qubes-users mailing list.
Read www.qubes-os.org/doc/software-update-dom0/

Use qubes-dom0-update in dom0.
You should, of course, be wary about what you install in dom0.

**Comment by huntse** [comment]
OK I've submitted a [pull request](https://github.com/QubesOS/qubes-desktop-linux-i3/pull/8) which should fix this issue.

**Comment by anoadragon453** [comment]
I download the `i3` package today and ran into these dependency issues (specifically being unable to locate Data::Dumper). Has the fix been reversed somehow?

**Comment by anadahz** [comment]
>I download the i3 package today and ran into these dependency issues (specifically being unable to locate Data::Dumper). Has the fix been reversed somehow?

@anoadragon453 How did you install i3?
