### ISSUE TITLE
NetworkManager applet enabled in Whonix VMs

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#3094]
#### Qubes OS version (e.g., `R3.2`):

4.0

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):

whonix-gw, whonix-ws

---

### Expected behavior:

NetworkManager applet hidden.

### Actual behavior:

NetworkManager applet visible, but unusable (NetworkManager service not running).

### Steps to reproduce the behavior:

Install default configuration of Whonix VMs, either choose so during installation, or later:
```
sudo qubesctl state.sls qvm.sys-whonix
```

### General notes:

Normally NetworkManager applet is hidden when NetworkManager itself is disabled. This is done by `/usr/lib/qubes/show-hide-nm-applet.sh` script, which is part of `qubes-core-agent-network-manager`. This package is not installed in Whonix VMs.

Possible solutions:
1. Include `qubes-core-agent-network-manager` package (it does not pull any more dependencies).
2. Do not install `network-manager-gnome` package (currently `qubes-whonix-shared-packages-recommended` depends on it). And maybe the same about `network-manger`.
3. Ship a script similar to `/usr/lib/qubes/show-hide-nm-applet.sh` in some Whonix-specific package. Or maybe not a script, but a static file defining default value for `org.gnome.nm-applet show-applet` gsetting.

Option 1 is the easiest one. Option 2 IMO is cleaner (unless there is some usage of NetworkManager in Qubes-Whonix).

Cc: @adrelanos 

---

#### Related issues:

#2954 
#1954

**Comment by adrelanos** [comment]
> 1. Include `qubes-core-agent-network-manager` package (it does not
pull any more dependencies).

Sounds good. We should install that by default in Qubes-Whonix anyhow.
Beginning from Whonix 14. Any reason against it?

> 2. Do not install `network-manager-gnome` package

Yes.

- There is no dependency on network-manager / network-manager-gnome in
Qubes-Whonix 14 development version. However, I wonder why it's
installed there then.

- We can consider this a Whonix 13 bug. - Shall I do a qubes-whonix 13
package stable upgrade to get rid of it?

**Comment by marmarek** [comment]
> 1. Include `qubes-core-agent-network-manager` package (it does not pull any more dependencies).
> 
> Sounds good. We should install that by default in Qubes-Whonix anyhow.
> Beginning from Whonix 14. Any reason against it?

Disk space(*), memory usage. Is NetworkManager used in Whonix 14?

> - There is no dependency on network-manager / network-manager-gnome in Qubes-Whonix 14 development version. However, I wonder why it's installed there then. 

Try to remove and see what depends on it...

> - We can consider this a Whonix 13 bug. - Shall I do a qubes-whonix 13 package stable upgrade to get rid of it?

Since NetworkManager service is disabled anyway, I think yes. Just drop the dependency (should not remove the package for existing users, so risk is low). https://github.com/Whonix/qubes-whonix/pull/6

(*) For example current development built of Qubes 4.0 installation image is 100MB too big for DVD...

**Comment by adrelanos** [comment]
Marek Marczykowski-Górecki:
>> 1. Include `qubes-core-agent-network-manager` package (it does not
>> pull any more dependencies).
>> 
>> Sounds good. We should install that by default in Qubes-Whonix
>> anyhow. Beginning from Whonix 14. Any reason against it?
> 
> Disk space(*), memory usage.

Word.

> Is NetworkManager used in Whonix 14?

No. The only convenience to have it installed by default is to ease VPN
use cases. But since we're on low space (*), let's forget about this
minority use case.

>> - There is no dependency on network-manager / network-manager-gnome
>> in Qubes-Whonix 14 development version. However, I wonder why it's
>> installed there then.
> 
> Try to remove and see what depends on it...

It's already removed. Nothing depends on it.

>> - We can consider this a Whonix 13 bug. - Shall I do a qubes-whonix
>> 13 package stable upgrade to get rid of it?
> 
> Since NetworkManager service is disabled anyway, I think yes. Just
> drop the dependency (should not remove the package for existing
> users, so risk is low).
> https://github.com/Whonix/qubes-whonix/pull/6

Your pull request is merged, updated package uploaded to
jessie-proposed-updates.

> (*) For example current development built of Qubes 4.0 installation
> image is 100MB too big for DVD...
>

**Comment by adrelanos** [comment]
Anything left to do here?

I don't see this happening.
