### ISSUE TITLE
4.0rc1 incorrect DispVM startup notifications

### ISSUE THREAD

**Issue by 3hhh** [QubesOS/qubes-issues#3097]
Minor bug:

In 4.0rc1 (current testing repos pulled) the notifications during a DispVM startup are almost always incorrect: They display e.g. "DispVM777 started" when DispVM565 was started.

**Comment by kalkin** [comment]
@marmarek I would fix this but currently I can't get dispvm to start at all.

**Comment by jpouellet** [comment]
I've seen the wrong VM name for normal VMs too in various UIs (IIRC at least notifications and qui-domains) when they share the same qid as an old VM.

**Comment by 3hhh** [comment]
This one was fixed a while ago I believe.
