### ISSUE TITLE
The new Qubes Widget (domains.py) gets out of sync with reality

### ISSUE THREAD

**Issue by rootkovska** [QubesOS/qubes-issues#3100]
I observe often how the list of VMs it shows does not agree with what is actually running in the system. I think in all observed cases the widget-displayed list omits some of the VMs. This is _not_ caused by VMs having the `internal` feature set.

**Comment by kalkin** [comment]
I think I pinpointed the issue in domains.tray. It doesn't react do DomainAdded/Removed events
