### ISSUE TITLE
qvm-prefs doesn't recognize `$adminvm` keyword

### ISSUE THREAD

**Issue by rootkovska** [QubesOS/qubes-issues#3101]
We want to be able to write (to maintain consistency with qrexec policy)

```qvm-prefs \$adminvm```

**Comment by marmarek** [comment]
No, qvm-prefs do not support $ keywords `$adminvm` is a _keyword_ used to match AdminVM, not a VM name. Keywords exist _only_ in qrexec policy.
Also, I don't want to support complex code for handling qvm-prefs $tag:xxx (I bet that would be the next expectation, "to maintain consistency with qrexec policy").

**Comment by rootkovska** [comment]
I don't agree with your argumentation. If $adminvm could be specified as a valid destination (and well defined) for qrexec-agent, then consistency demands it should also be a valid "destination" for qvm-prefs.

**Comment by rootkovska** [comment]
Otherwise users would be confused why the same entity is named differently in two cases, and would tend to use the name which works in both contexts, effectively not using the (preferred) $adminvm,

**Comment by marmarek** [comment]
No, the argument in qvm-prefs is a **VM name**, not any qrexec target. For example it doesn't make sense to use `qvm-prefs $dispvm`. VM names can be for example listed by `qvm-ls`. Having to use $adminvm when VM is actually named dom0 (as listed by qvm-ls and all other tools) would be much more confusing.
Also, much less users will ever modify qrexec policy, than use qvm tools. So many will not even know from where that $adminvm came.

Also, VM name cannot contain "$". There is no exception. This is why it is a character used for _keywords_ in qrexec syntax. So, "$adminvm" is not a _name of VM_ (and we shouldn't rename it as such).

**Comment by marmarek** [comment]
There is also practical issue: it's much simpler to make a mistake using `qvm-prefs $adminvm` from shell (note lack of `\`), than `qvm-prefs dom0`. This problem does not apply to qrexec policy _file_.
