### ISSUE TITLE
dom0 label discrepancy 

### ISSUE THREAD

**Issue by rootkovska** [QubesOS/qubes-issues#3102]
qvm-prefs reports dom0 label as black. Our Windows Manager plugin displays the gray/silver label.

**Comment by marmarek** [comment]
Window manager do not know what label is set by qvm-prefs, because dom0 windows are not created by gui-daemon (so do not have `_QUBES_*` X properties). I think we should forbid changing dom0 label and set it the same in both qvm-prefs and window managers. What color do you prefer?

**Comment by rootkovska** [comment]
How about some special kind of color, say: "adminvm"?

**Comment by marmarek** [comment]
Why? Would that be a color outside of any color palette? ;)
Alternatively, we may drop 'label' property from dom0 at all.

**Comment by rootkovska** [comment]
Note the property is called "label", not "color" :) So, yeah, the idea is to have something special reserved for this. Also, in the future we will likely introduce another label perhaps: "guidom"?

**Comment by marmarek** [comment]
What would be the purpose of this special labels? Where would it be used? And why would _not_ be it mapped a color? If you think assigning normal label does not make sense for dom0, IMO better drop this property at all, instead of introducing yet another special case.

**Comment by marmarta** [comment]
AdminVM now has a special icon, which is also reported by `qvm-prefs`, so this can I think be safely closed.
