### ISSUE TITLE
qvm-service problems (network-manager case)

### ISSUE THREAD

**Issue by rootkovska** [QubesOS/qubes-issues#3103]
Using qvm-service to enable network-manager service in 4.0-rc1 does not seem to work:

```
qvm-service --enable sys-usb network-manager
```
This results in the service being properly reported as 'on' by the qvm-service. Yet, the NM applet does not start for this VM. Of course I rebooted the VM in question.

**Comment by marmarek** [comment]
I've just tried and it works for me... I need more data:
1. `qubesdb-multiread /` in that VM
2. `ls /var/run/qubes-service` in that VM

**Comment by rootkovska** [comment]
Actually, after I restarted the VM in question, I could not reproduce the error-nous behavior anymore. So, closing.
