### ISSUE TITLE
cannot disable "include in memory balancing"

### ISSUE THREAD

**Issue by julesverhaeren** [QubesOS/qubes-issues#3104]
#### Qubes OS version (e.g., `R3.2`):
 4.0-rc1
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):
fedora-25

---

### Expected behavior:
when unchecking the checkbox next to "include in memory balancing", this vm should no longer be included in memory balancing
### Actual behavior:
vm is still included in memory balancing (as can be seen by reopening the settings)
### Steps to reproduce the behavior:
clean install-> uncheck checkbox in default work vm settings -> press ok -> reopen work vm settings 
### General notes:

---

**Comment by marmarek** [comment]
I can confirm that the setting isn't properly initiated while opening the settings dialog. But when you disable it, it indeed get disabled.

**Comment by 0spinboson** [comment]
you mean disable it via qvm-prefs?

**Comment by marmarek** [comment]
No, via GUI.
