### ISSUE TITLE
No sound in Archlinux AppVMs with pulseaudio 11.1

### ISSUE THREAD

**Issue by Ban3** [QubesOS/qubes-issues#3106]
#### Qubes OS version:
R3.2

#### Affected TemplateVMs:
`archlinux`

---

### Expected behavior:
Sound playback in AppVMs

### Actual behavior:
No sound playback in AppVMs

### Steps to reproduce the behavior:
Having following packages installed:
`pulseaudio-11.1`
`qubes-vm-gui-3.2.17-8`

### General notes:
```
$ pulseaudio -nF /etc/pulse/qubes-default.pa
E: [pulseaudio] ltdl-bind-now.c: Failed to open module module-vchan-sink.so: module-vchan-sink.so: cannot open shared object file: No such file or directory
E: [pulseaudio] module.c: Failed to open module "module-vchan-sink".
E: [pulseaudio] main.c: Module load failed.
E: [pulseaudio] main.c: Failed to initialize daemon.
```

```
$ ls /usr/lib/pulse-11.1/modules/module-vchan-sink.so
ls: cannot access '/usr/lib/pulse-11.1/modules/module-vchan-sink.so': No such file or directory
```
```
$ pacman -Qo /usr/lib/pulse-11.0/modules/module-vchan-sink.so 
/usr/lib/pulse-11.0/modules/module-vchan-sink.so is owned by qubes-vm-gui 3.2.17-8
```

**Temporary workaround**
```
# ln -s /usr/lib/pulse-11.0/modules/module-vchan-sink.so /usr/lib/pulse-11.1/modules/
```

**Comment by na--** [comment]
[This](https://github.com/QubesOS/qubes-gui-agent-linux/commit/c71fb490b5a3100a71f9de2b1a0822d2c07c339b) commit (qubes-vm-gui version [3.2.18](https://github.com/QubesOS/qubes-gui-agent-linux/commit/b87e64cfdafcb61daefdd992b1e2c3f5c4e605d0)) fixes the issue

**Comment by ptitdoc** [comment]
The qubes-vm-gui package is currently linked to major version of pulseaudio.

This should be restricted to minor version of pulseaudio so that the user need to upgrade both pulseaudio and qubes-vm-gui package at the same time.

As a side note, qubes-pulseaudio package is a separate package for other templates. Separating it for archlinux could improve the user update experience.

**Comment by ptitdoc** [comment]
https://github.com/QubesOS/qubes-gui-agent-linux/pull/19

**Comment by ptitdoc** [comment]
https://github.com/QubesOS/qubes-gui-agent-linux/pull/19/commits/1e7717f171b2a19a1c95b2f13d523c55b7b927ac

**Comment by ptitdoc** [comment]
I rebuilt and uploaded the archlinux binary packages with the fix.
