### ISSUE TITLE
UnitedRPMs "Cannot download, all mirrors were tried" to anything on Fedora 25

### ISSUE THREAD

**Issue by samuelporcellis** [QubesOS/qubes-issues#3109]
#### Qubes OS version:
R3.2

#### Affected TemplateVMs:
fedora-25

---

### Expected behavior: 
Install and update programs normally using the UnitedRPMs 25 x86_64 repository.

### Actual behavior: 
Cannot install nor update anything from the repository.

### Steps to reproduce the behavior: 
Just try to download or update anything, I'll be using `opera` as an example

```
[root@fedora-25 user]# dnf install opera
unitedrpms 25 - x86_64                          193 kB/s | 1.0 MB     00:05    
Last metadata expiration check: 0:00:01 ago on Tue Sep 19 18:59:14 2017.
Dependencies resolved.
================================================================================
 Package                        Arch    Version               Repository   Size
================================================================================
Installing:
 chromium-freeworld-libs-media  x86_64  60.0.3112.113-2.fc25  unitedrpms  1.0 M
 chromium-pepper-flash          x86_64  26.0.0.151-1.fc25     unitedrpms  7.8 M
 chromium-widevine              x86_64  1.4.8.1008-1.fc25     unitedrpms  2.0 M
 openssl-spotify                x86_64  1.0.0-5.fc25          unitedrpms  771 k
 opera                          x86_64  47.0.2631.80-1.fc25   unitedrpms   52 M

Transaction Summary
================================================================================
Install  5 Packages

Total download size: 64 M
Installed size: 198 M
Is this ok [y/N]: y
Downloading Packages:
[MIRROR] chromium-freeworld-libs-media-60.0.3112.113-2.fc25.x86_64.rpm: Interrupted by header callback: Server reports Content-Length: 15697 but expected size is: 1028750
[FAILED] chromium-freeworld-libs-media-60.0.3112.113-2.fc25.x86_64.rpm: No more mirrors to try - All mirrors were already tried without success
(2-3/5): opera-47.0.  1% [                    ] 785 MB/s | 1.0 MB     00:00 ETA
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Error: Error downloading packages:
  Cannot download chromium-freeworld-libs-media-60.0.3112.113-2.fc25.x86_64.rpm: All mirrors were tried
```

### General notes:
@kuboosoft on https://github.com/UnitedRPMs/issues/issues/11 said " if the server detect malicious/doubtful ip filtered you obtains the above results" and that he is not sure if the problem is a service constantly changing the ip, proxy, network domain or the AppVM settings. I haven't found anything on Qubes's documentation that could help me with this problem.

**Comment by marmarek** [comment]
Are you using tor (through Whonix for example) to download updates?

**Comment by samuelporcellis** [comment]
@marmarek I didn't activate Whonix while I was trying to download something from UnitedRPMs, although I might've update the system with Tor before that.

**Comment by samuelporcellis** [comment]
Well? Can anyone help me?

**Comment by 0spinboson** [comment]
I intermittently have issues with UnitedRPMs's mirrors, but only because the connection doesn't appear to be very robust. This didn't resolve itself after a few hours or days?

**Comment by Adamo1618** [comment]
Having this exact problem, and no, it doesn't resolve itself.

**Comment by disqotech** [comment]
Getting the same issue. Trying to install VLC, i can install it from rpm fusion but it doesn't actually work, instead the screen just flickers when trying to play anything. Via unitedRPMs i get this issue.

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
