### ISSUE TITLE
sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing fails (4.0RC1)

### ISSUE THREAD

**Issue by mannp** [QubesOS/qubes-issues#3110]
#### Qubes OS version:
4.0RC1
#### Affected TemplateVMs:
dom0
---

### Expected behavior:
Usual access to system tools following an update to current testing and a reboot.
### Actual behavior:
After updating my system to current testing repo all was well until I rebooted. After I rebooted I was unable to use qubes-dom0-update, qvm-ls or see which vm's are actually running.

[http://safe.dsh.re/download/8ab76516-37c7-4e79-afdf-171eefec237d](url)

The system is borked, including the network related system, so I am unable to get a copy of the error directly, so I have attached a screenshot.
### Steps to reproduce the behavior:
Update system to current testing and reboot.

Have reinstalled and repeated, so it is reproducable.
### General notes:

---

**Comment by marmarek** [comment]
That url returns 404. Anyway, check `journalctl -u qubesd` for details.

**Comment by mannp** [comment]
Very odd and this one -> http://safe.dsh.re/download/6ad1ca21-f358-4953-9a95-f9e4bf95b950

**Comment by mannp** [comment]
@marmarek is this something I can recover from without internet access?

Thanks

**Comment by marmarek** [comment]
Looks like there is something wrong with default template. Check `/var/lib/qubes/qubes.xml`, you should have something like this near the top:
```xml
<property name="default_template">fedora-25</property>
```

**Comment by mannp** [comment]
Yes i have that file and the property name is as you have it there and the file is not corrupt or anything.

The second file I uploaded has the detailed logs.

**Comment by marmarek** [comment]
Maybe you have some AppVM without template set? Check `qubes.xml`, each `<domain class="AppVM">` object for `<property name="template">` and if it points to an existing template.
I could write a one-line xpath expression to help with that, but it will be quite long, so it will be faster to check this manually. Unless you have a lot of VMs there.

**Comment by mannp** [comment]
Ok will do.

I also tried to restart the qubesd daemon and qubesd.service says 'Failed with result - start-limit-hit'

**Comment by mannp** [comment]
@marmarek that was it thanks 👍 surprised the system allowed me to save a vm config if it must have a template allocated?

I am back up and running, so that for your time :)

**Comment by marmarek** [comment]
How exactly have you managed to do that? Was it a VM without a template, or with invalid template (like removed one)?

**Comment by mannp** [comment]
It was a VM without a template and I have no idea.

I did not know qubes.xml existed, so haven't edited it before.

Just trying to configure the vms in the gui.

**Comment by marmarek** [comment]
So, it was freshly created VM broken?

**Comment by mannp** [comment]
No, I had made edits in the gui for the vms and must have left one without a template allocated.

**Comment by marmarek** [comment]
Oh, indeed it should not be possible.

**Comment by mannp** [comment]
I have also got myself into a mess (thankfully solved using the knowledge of qubes.xml) allocating the graphics card to my other AppVM's and then being unable to boot the whole qubes distro.

Thanksfully I could edit qubes.xml and remove the offending pci lines to get back up and running.

I would question whether silly moves by me, like that, should also be allowed to happen by the gui?
