### ISSUE TITLE
qubes.OpenInVM fails to remove file

### ISSUE THREAD

**Issue by rootkovska** [QubesOS/qubes-issues#3112]
... and since the file is /tmp/{name_of_vm}/{name_of_file}, this means that if one want to open, say a PDF, in some other, non-DispVM, one would be able to do that just once. After that, all qubes.OpenInVM calls from the same VM and for the same filename would result in an error, due to the file being there already. Of course restarting the VM solves this.

I think we should allow to overwrite the files in /tmp/{name_of_vms}/.

**Comment by marmarek** [comment]
Overriding file would be wrong IMO, because one can have multiple files with the same name, but from different directories (like `attachment.pdf`). BTW what are use cases for qubes.OpenInVM in non-DispVM?

**Comment by rootkovska** [comment]
Maybe randomize the dir name then? I.e. instead of `/tmp/{vmname}/`, use `/tmp/{vmname}-{mktemp}/

> BTW what are use cases for qubes.OpenInVM in non-DispVM?

In my case this was mostly testing ;) But one can imagine valid uses, e.g. for opening select documents in MS Windows AppVM.
