### ISSUE TITLE
4.0rc1 doesn't boot on x1 carbon with coreboot

### ISSUE THREAD

**Issue by h01ger** [QubesOS/qubes-issues#3116]
#### Qubes OS version (e.g., `R3.2`):

4.0rc1

### Expected behavior:

after installation of 4.0rc1 I expect Qubes to boot.

### Actual behavior:

Coreboot loads seabios, seabios starts, the screen turns black, the computer reboots, coreboot loads seabios… and so on :/

### Steps to reproduce the behavior:

The computer (Thinkpad X1 Carbon, 1st) was booted with coreboot and seabios using an usbstick with
9fa6de2cf0431ab615e00d5b5a5fa49fc5a0d84946e062a34e18d7db28e71a6c  Qubes-R4.0-rc1-x86_64.iso (verified with gpg) and then I've just installed rc4.0 with the default partitioning scheme (that is, whole disk and encrypted) and choose to install all templates.

**Comment by marmarek** [comment]
Check #2994

**Comment by h01ger** [comment]
ok, thanks. Sadly I dont even see the grub menu… will test this setting later today and report back here.

**Comment by marmarek** [comment]
If UEFI, you need to boot something else (installer?) and edit xen.cfg on EFI partition (/boot/efi/EFI/qubes/xen,cfg).

**Comment by h01ger** [comment]
indeed a duplicate of #2994, thus closing.

**Comment by pseudobanana** [comment]
Can I ask you about the method you used to coreboot your machine? Also would it work with the X1C gen1 touchscreen version too? Thanks! (I don't really know how to send pm here)

**Comment by pseudobanana** [comment]
Can I ask you about the method you used to coreboot your machine? Also would it work with the X1C gen1 touchscreen version too? Thanks! (I don't really know how to send pm here)

**Comment by h01ger** [comment]
On Wed, Nov 22, 2017 at 10:09:50PM +0000, pseudobanana wrote:
> Can I ask you about the method you used to coreboot your machine? 

using a hardware flasher.

>Also would it work with the X1C gen1 touchscreen version too? Thanks! (I don't really know how to send pm here)

I don't know, but I would guess yes. (for gen1.)


-- 
cheers,
	Holger
