### ISSUE TITLE
Updating WiFi Driver

### ISSUE THREAD

**Issue by flaviosanchez** [QubesOS/qubes-issues#3117]
How do I make changes to this path "/usr/lib/modules/(uname -r)/kernel/drivers/net/wireless"? I would like to place lwfinger's compiled driver (https://github.com/lwfinger/rtl8188eu) in that directory to get my NIC card to work properly.

**Comment by 0spinboson** [comment]
Please ask this question on the user list, this is meant for bugs only. :)
https://groups.google.com/forum/#!forum/qubes-users

**Comment by flaviosanchez** [comment]
Will do! Thanks!
