### ISSUE TITLE
Salt vcpus bug in 4.0 rc 1

### ISSUE THREAD

**Issue by huntse** [QubesOS/qubes-issues#3120]
#### Qubes OS version (e.g., `R3.2`):

`R4.0-rc1`

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):
n/a
---

### Steps to reproduce the behavior:

Create an `x.top` file like this
```
base:
  dom0:
  - x
```
...and an `x.sls` file like this
```
x:
  qvm.present:
   - name: x
   - template: fedora-25
   - label: blue
   - mem: 4096
   - vcpus: 4

```
..and then try to create the vm by doing
```
$ sudo qubesctl top.enable x
$ sudo qubesctl state.highstate
```

### Expected behavior:

It should create a new qube with 4 vcpus (as per the docs and presumably R3.2).

### Actual behavior:

...you get error output something like this, saying that it doesn't understand the `vcpus` option.  

```
[ERROR   ] /usr/bin/qvm-check x 
====== stderr ======
/usr/bin/qvm-create --template fedora-25 --label blue --vcpus 4 x 
usage: qvm-create [-h] [--verbose] [--quiet] [--class CLS]
                  [--property NAME=VALUE] [--pool VOLUME_NAME=POOL_NAME]
                  [-P POOL_NAME] [--template VALUE] [--label VALUE]
                  [--help-classes]
                  [--root-copy-from FILENAME | --root-move-from FILENAME]
                  [VMNAME]
qvm-create: error: unrecognized arguments: --vcpus x
====== stderr ======
/usr/bin/qvm-check x 
usage: qvm-check [-h] [--verbose] [--quiet] [--all] [--exclude EXCLUDE]
                 [--running] [--paused] [--template]
                 [VMNAME [VMNAME ...]]
qvm-check: error: no such domain: 'x'                                                                   
```

### General notes:

It seems that the salt stuff has not been updated to take into account changes to the syntax of qvm-create.  In particular, it no longer accepts a `--vcpus` option, although there may well be other options which are now broken in 4.0.

---

**Comment by huntse** [comment]
OK, so the problem is in https://github.com/QubesOS/qubes-mgmt-salt-dom0-qvm/blob/master/_modules/ext_module_qvm.py where it's adding a lot of options like `--vcpus 4` when they should be `--property vcpus=4` in the new version of `qvm-create`.  It's not completely obvious to me how to change the code over to the new format without a large-scale hack however.

**Comment by marmarek** [comment]
I'm working on it, there are more compatibility problems (like handling proxy/netvm, hvm templates...).

**Comment by huntse** [comment]
Yeah this is what I noticed too. Thanks anyway.
