### ISSUE TITLE
core-admin: separate xml loading

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#3123]
This was done when all objects kept reference to their respective XML object
for saving. This is no longer needed since there is no concurrent access to XML
from different tools anymore.

`PropertyHolder.from_xml()`, to be overloaded in children. Care should be taken
when loading properties wrt loading order.

**Comment by marmarek** [comment]
@woju do we still want this?

**Comment by woju** [comment]
No, I don't think it is important. Currently things work, so don't fix if it ain't broken.

**Comment by woju** [comment]
This issue is abandoned, so I'm going to close it. If that's a mistake, feel free to reopen.
@marmarek @andrewdavidwong
