### ISSUE TITLE
Archlinux application nemo does not start after installation

### ISSUE THREAD

**Issue by schnurentwickler** [QubesOS/qubes-issues#3124]
#### Qubes OS version (e.g., `R3.2`):
R3.2 Testing
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):
archlinux template

---

### Steps to reproduce the behavior:
Install nemo and some of the extensions like nemo-fileroller.
### Expected behavior:
Nemo starts like any other applikation.
### Actual behavior:
Nothing happens when started via menu. Error when started in terminal:
user@Testtemplate:~$ qubes-desktop-run "/usr/share/applications/nemo.desktop" Traceback (most recent call last):
  File "/usr/bin/qubes-desktop-run", line 7, in <module>
    launch(*sys.argv[1:])
  File "/usr/lib/python2.7/site-packages/qubes/xdg.py", line 16, in launch
    bus.start_service_by_name(service_id)
  File "/usr/lib/python2.7/site-packages/dbus/bus.py", line 274, in start_service_by_name
    validate_bus_name(bus_name)
ValueError: Invalid bus name 'nemo': must contain '.'
### General notes:

---

**Comment by marmarek** [comment]
Looks like a bug in nemo application itself. If desktop entry have `DBusActivatable=true` (which is the case for nemo.desktop), then it's name must be a proper d-bus name. Relevant [specification](https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s07.html):

> The application must name its desktop file in accordance with the naming recommendations in the introduction section (e.g. the filename must be like org.example.FooViewer.desktop). The application must have a D-Bus service activatable at the well-known name that is equal to the desktop file name with the .desktop portion removed (for our example, org.example.FooViewer).

**Comment by marmarek** [comment]
Look like it is already [fixed upstream](https://github.com/linuxmint/nemo/commit/66d7aae2ee00a29276cbbf97491e7455a5cba137), but it isn't included in any version yet.
