### ISSUE TITLE
4rc1 - qvm-backup-restore restore borks entire system on one vm restore

### ISSUE THREAD

**Issue by mannp** [QubesOS/qubes-issues#3127]
#### Affected TemplateVMs: fedora-25

---

### Steps to reproduce the behavior:

Have a working system and backup all vms with qvm-backup, encrypted. 

Make sure the backup is good. 

Restore all system including dom0 or just individual vms, with everything else excluded and the result is the same, a borked system.

I have taken photos again as I cannot copy and paste from the machine as nothing works at the moment.

[http://safe.dsh.re/download/91162f31-b9a7-46e2-9a0c-de5e6e8a3ef0](url)

### Expected behavior:

Restoring any and all VM's should not be allowed to bork the system in a way to stop qubesd from starting.

### Actual behavior:

FW and Net VM's as well as qubesd will not start.

### General notes:

It appears to be another erro with qubes.xml but I have wasted a day trying to solve and cannot.

---

**Comment by marmarek** [comment]
This looks like another instance of #3115
