### ISSUE TITLE
qvm-remove may cause unwanted data loss (typos etc.)

### ISSUE THREAD

**Issue by 3hhh** [QubesOS/qubes-issues#3129]
#### Qubes OS version (e.g., `R3.2`):
4.0rc1

### Steps to reproduce the behavior:
`qvm-remove [VM]`

### Actual behavior:
It removes the VM.

### Expected behavior:
It could provide some security check that you didn't mistype or anything. This was available in Qubes Manager in 3.2.
A `-f` flag might force removal without a second question for scripting etc.

**Comment by tasket** [comment]
Seems like a related issue:

qvm-remove will remove a Template that is installed from dnf/rpm. Is that intended?

**Comment by tasket** [comment]
@marmarek - I have a patch I can add to PR#43

**Comment by marmarek** [comment]
> @marmarek - I have a patch I can add to PR#43

Please create separate PR.

**Comment by tasket** [comment]
@marmarek - Should I put a check/exception for `installed_by_rpm` in api/admin.py: `vm_remove()` ?

**Comment by tasket** [comment]
PR https://github.com/QubesOS/qubes-core-admin-client/pull/44

**Comment by tasket** [comment]
PR https://github.com/QubesOS/qubes-core-admin/pull/176

**Comment by tasket** [comment]
@3hhh - You can probably close this now; The above PRs were merged.

**Comment by marmarek** [comment]
Thanks @tasket !
