### ISSUE TITLE
No more qubes-manager after assigned peripherals

### ISSUE THREAD

**Issue by boistordu** [QubesOS/qubes-issues#3131]
#### Qubes OS version (e.g., `R3.2`):
3.2
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):
Hvm of Ubuntu

---

### Steps to reproduce the behavior:
I ve assigned the graphic Intel gpu from the laptop to the hvm
### Expected behavior:
if the peripherals was not supposed to be assigned then why not throw an error message.
### Actual behavior:
Black screen then reboot of the laptop-> no more qvm-manager, I can't launch it anymore
### General notes:
i don't see how to restore the whole os. I can't do a thing because of that right now. 

---

**Comment by boistordu** [comment]
Of someone has a solution for me to restore my system it would be great.

**Comment by marmarek** [comment]
Try qvm-pci tool to detach device from the VM.

**Comment by boistordu** [comment]
Okey give me some time I'm at work and need to finish something.

Obtenez Outlook pour iOS<https://aka.ms/o0ukef>
________________________________

**Comment by boistordu** [comment]
It doesn't work.  I'm going to send a link for a photo about the error

**Comment by boistordu** [comment]
![image](https://user-images.githubusercontent.com/9523075/30965948-717cd7f0-a457-11e7-8ed4-06542cffddc3.jpg)

**Comment by boistordu** [comment]
Would be deleting the vm a good idea? 
It s a basic vm so nothing important in there. But I don't know how to do it exactly?

**Comment by marmarek** [comment]
Looks like `/var/lib/qubes/qubes.xml` file is broken (empty). If that's the case, restore it from latest backup in `/var/lib/qubes/backup`. Then check if all your VMs are there.

**Comment by boistordu** [comment]
In backup the last XML with something in it is from 25 September. There are 3xml file empty from today. So I guess I m screwed

Obtenez Outlook pour iOS<https://aka.ms/o0ukef>
________________________________

**Comment by boistordu** [comment]
Yeah I m screwed everything have been erased. So I guess I need to reinstall everything?

Obtenez Outlook pour iOS<https://aka.ms/o0ukef>
________________________________

**Comment by boistordu** [comment]
So just for more debugging for you. 
The fs I ve partition for /var/lib/qubes was xfs. Since I ve red somewhere that xfs has better performance for vm disk file but could loose maybe small files from time to time, I guess so that's because maybe of that. 

I've installed qubes 4 days ago only. 
So it would be maybe a better idea to put a cron or to backups qubes.xml everytime a modification is made in place of each reboot...

**Comment by marmarek** [comment]
Well, if random filesystem corruption happens, it means that filesystem should be avoided... FWIW I had similar experience with xfs some years ago - it is no use for systems without very stable power supply (big UPS etc).
Making backups is a good thing anyway, we have qvm-backup (or GUI version in Qubes Manager) for that. I hope you didn't have anything unrecoverable there...
Yes, the easiest thing to do now is to reinstall - if one file got corrupted, there may be more affected.

**Comment by boistordu** [comment]
Yes that's what I m learning the hard way. What's best as fs for vm image on a ssd?
I could maybe do different mount point like /var/lib/qubes/app-vms with different fs...

Obtenez Outlook pour iOS<https://aka.ms/o0ukef>
________________________________

**Comment by boistordu** [comment]
No any advice?

By the way, this was not an electrical problem. But the system crashed pure and simple so even if you have no electrical problem, the problem could occur

**Comment by marmarek** [comment]
You can try btrfs. I haven't used it much personally, but people recommend it. In practice ext4 work really good on SSD too. You just need to remember to enable TRIM operation support: https://www.qubes-os.org/doc/disk-trim/

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 has reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
