### ISSUE TITLE
ubuntu 17.04

### ISSUE THREAD

**Issue by boistordu** [QubesOS/qubes-issues#3134]
#### Qubes OS version (e.g., `R3.2`):
3.2

### Steps to reproduce the behavior:
ubuntu 17.04 hvm

I know it's not officially supported but I wanted to discuss the compatibility of the fix shown [here](https://github.com/QubesOS/qubes-issues/issues/256): 
the ubuntu 17.04 normal or bundgie shows a 1680x1050 as max resolution after fixed, none of the other resolution works even the minimal one,

**Comment by boistordu** [comment]
Just for information, windows 10 resolution in hvm are working fine .

**Comment by unman** [comment]
@boistordu I think you have the wrong link, but never mind. Is the issue that you want a larger/different resolution than 1680x1050 or that you want to be able to shift resolution on the fly?

**Comment by unman** [comment]
Note too that this isn't specific to 17.04 - it's also an issue with 16.04, and is a common problem reported with Ubuntu HVMs. Most suggested solutions consist in setting the required resolution at boot, either by editing /etc/default/grub or by setting vga value at boot.
I'm not sure there's much to add to that.

**Comment by unman** [comment]
@andrewdavidwong Can you close this please.
It's an upstream issue , not specific to Qubes, and affects many Ubuntu installations in virtualised contexts. You can find reports for Virtualbox, VMware and KVM. 
Simple to find a workround, setting parameters at boot.
