### ISSUE TITLE
PVGRUB2 does not work in Qubes 4

### ISSUE THREAD

**Issue by dylangerdaly** [QubesOS/qubes-issues#3136]
#### Qubes OS version (e.g., `R3.2`):
4RC1

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):
Any VM with a VM Managed Kernel

---

### Steps to reproduce the behavior:\
Install grub2-xen, set kernel to pvgrub2 and start a VM

### Expected behavior:
VM Should Boot

### Actual behavior:
Missing file: /var/lib/qubes/vm-kernels/pvgrub2/modules.img

### General notes:
Touching modules and copying modules from another kernel does not work (libxenlight error creating domain)

---

#### Related issues:
None

**Comment by marmarek** [comment]
pvgrub2 is works only in PV mode. VMs in Qubes 4.0 are HVM. In practice it means pvgrub2 isn't needed at all and normal grub (or other bootloader) can be used instead. To do that, set `kernel` property to empty value:
```
qvm-prefs VMNAME kernel ''
```
You may want to enable debug mode initially:
```
qvm-prefs VMNAME debug on
```
Yes, we need to update documentation about this.

**Comment by dylangerdaly** [comment]
Thank you! I've added that in however I can't seem to  get my VM to boot, I'm assuming its due to some grub issue, is there anything new with Qubes 4 I need to install on my VM to get it to boot up, the debug shows me the "probing edd (edd=off to disable)... ok" messages but not much else.

**Comment by iamahuman** [comment]
It might be a good idea to close this issue.

**Comment by marmarek** [comment]
For the record - all grub vs virt_mode options are listed in  #5212 - which is about simplifying this mess.
