### ISSUE TITLE
`qrexec-client-vm '$dispvm:<anything>'` always fails with "Request refused"

### ISSUE THREAD

**Issue by joshuathayer** [QubesOS/qubes-issues#3137]
#### Qubes OS version (e.g., `R3.2`):

4.0, up to date with `current-testing` via 

    sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing

---

### Steps to reproduce the behavior:

From an AppVM:

    $ echo "hello world" > hello.txt
    $ qrexec-client-vm '$dispvm:fedora-25-dvm' qubes.OpenInVM "/usr/lib/qubes/qopen-in-vm" ./hello.txt

### Expected behavior:

Since the default policy in `/etc/qubes-rpc/policy/qubes.OpenInVM` is `ask`, I'd expect a confirmation dialog to appear.

Then, I'd expect the same behavior as `qrexec-client-vm '$dispvm' qubes.OpenInVM "/usr/lib/qubes/qopen-in-vm" ./hello.txt`: a new dispVM should start and a `gedit` window should open with the content `hello world`.

### Actual behavior:

An immediate `Request refused` error appears.

Note that this happens regardless of "template" VM- the following exhibits the same behavior:

    $ qrexec-client-vm '$dispvm:work' qubes.OpenInVM "/usr/lib/qubes/qopen-in-vm" ./hello.txt

### General notes:

I spent some time debugging and found that the colon in the target VM name is getting munged into an underscore at some point before `qrexec-policy` is run on `dom0`, which seems to keep any policy from matching the target VM.

Thanks!

**Comment by marmarek** [comment]
Note that by default `ask` action ignore destination you provided to `qrexec-client-vm` command. So, you may also put empty string there and choose `$dispvm:work` from confirmation dialog.
But what you've found is a bug of course...
