### ISSUE TITLE
Qubes OS 4.0rc1 on Macbook Pro 13" fails

### ISSUE THREAD

**Issue by tsjavaloyes** [QubesOS/qubes-issues#3138]
#### Qubes OS version (e.g., `R3.2`): 
4.0rc1

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):
Not applicable

---

### Steps to reproduce the behavior:
1.- Create USB installation using Rufus ('dd' option selected) on Windows 10 Pro without problems
2.- Put USB on MacBook Pro 13" (macbookpro9,2 version with 2.5GHz  Core i5 processor compatible with doc (EPT and VT-d)
3.- Using an external USB SSD disk (I'm using a new Samsung T5 500GB) for destination
4.- Power on Macbook and press "option-key" and select USB "EFI boot"
5.- Boot ANACONDA and wait menu. Select "Test media and install Qubes R4.0-rc1" or "Install Qubes R4.0-rc1" 

### Expected behavior:
The installation should start...

### Actual behavior:
The installation selection menu reappears

### General notes:
I'm a Qubes newbie user. 
---

**Comment by marmarek** [comment]
See here: https://www.qubes-os.org/doc/uefi-troubleshooting/

**Comment by tsjavaloyes** [comment]
Added "/mapbs /noexitboot" at 'grub.cfg' as given in documentation and still does not start the installation and reappears the menu

**Comment by marmarek** [comment]
Do you have an option to boot in legacy mode?

**Comment by tsjavaloyes** [comment]
Hi again...

After searching and reading documentation on the activation of legacy boot the command 'bless' do not work because there is a security system that prevents it (they call it 'System Integrity Protection'). I'm hoping that there is support for Apple's new APFS file system in 'rEFInd' (update already downloadable OS X 'High Sierra') to install it and test Qubes OS to start the installation in 'legacy mode'...

**Comment by n3tw0** [comment]
Not sure if this will work in OS X High Sierra, but might be worth a shot.

How to turn off System Integrity Protection
* Click the  menu.
* Select Restart...
* Hold down command-R to boot into the Recovery System.
* Click the Utilities menu and select Terminal.
* Type csrutil disable and press return.
* Close the Terminal app.
* Click the  menu and select Restart....
