### ISSUE TITLE
Invalid shell used for vm.run() (sometimes)

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#3139]
### Steps to reproduce the behavior:

Call vm.run('echo $SHELL') from inside qubesd.

### Expected behavior:

Shell set for that user (`user`).

### Actual behavior:

Sometimes correct value, sometimes `/bin/sh`.

### General notes:

Looks to be depending on whether GUI is connected before the command is run.

**Comment by marmarek** [comment]
Similar issue applies to qubes.VMShell service. There always `/bin/bash` is used.

**Comment by schnurentwickler** [comment]
Maybe this was the issue what archlinux with zsh set as default in templateVM gave problematic VM shutdowns. (As described in https://github.com/QubesOS/qubes-issues/issues/2888) - Quote from #2888 : 
> The unhealthy shutdown behavior caused by the zsh shell, set as standard for the template user. _sudo chsh -s /bin/zsh user_ Obviosly some qubes(?) scripts are using the standard user shell. For now anyone who is affected should switch to the bash shell: sudo chsh -s /bin/bash user
This seems to be a bug and should not happen. <
