### ISSUE TITLE
UPS-hid is severely dysfunctional on Qubes 3.2

### ISSUE THREAD

**Issue by tonsimple** [QubesOS/qubes-issues#3140]
#### Qubes OS version (e.g., `R3.2`):

R 3.2

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):

Dom0

---

### Steps to reproduce the behavior:

1) Have a UPS that has basic USB-hid functionality to provide linux with basic battery level monitoring features 

//=====//

Tested: two powercom UPS (including SPT 3000)

One APC

One Cyberpower 

//=====//

2) Connect the UPS to a USB port that goes directly to Dom0 (where we would reasonably want all the battery-related actions, such as low power shutdown taking place)

3) Observe some anomalies right away (see below)

4) observe failure of low-battery shutdown if battery indeed is low.

### Expected behavior:

Ups would report battery accurately and Dom0 would trigger a shutdown when a battery level specified in power manager is reached

### Actual behavior:

1) even when not on backup power, the power manager constantly spuriously reports "UPS is empty" followed by "UPS is full" 

(it is full indeed). Frequent "UPS is empty" spam is both suspicious and frankly a bit scary. Spam usually stops after a while.)

2) when on backup power, and power drops below the level specified as "shutdown" level in power manager (say, shutdown level set to 50%, and UPS drops to say, 49% or lower), no shutdown happens

### General notes:

Before reporting, I gathered several UPS units from work and from friends, and tested them.

Same behavior on all of them, though "UPS is empty" message spam behavior seemed to differ between UPS models, being most frequent and persistent on powercoms, and only happening twice on APC.

---

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
