### ISSUE TITLE
qvm-copy-to-vm useless target parameter

### ISSUE THREAD

**Issue by 3hhh** [QubesOS/qubes-issues#3141]
#### Qubes OS version (e.g., `R3.2`):
4.0rc1

### Steps to reproduce the behavior:

1. qvm-copy-to-vm [target VM] [file]

1. Choose a different target VM in the dom0 dialog

### Expected behavior:

No [target VM] parameter needed.

### Actual behavior:

It is needed and has no effect.

**Comment by andrewdavidwong** [comment]
Not sure if this is actually intended (e.g., due to RPC policy interaction). @marmarek?

**Comment by marmarek** [comment]
Yes, this is intended effect. Target parameter is now useless with default policy. But it can be still meaningful with custom policy (containing "allow" action for selected targets). Target parameter in that tool is kept for compatibility reasons. This is especially important for qvm-move-to-vm - it could be fatal if you have a file/directory with the name of the target VM in the same place...
We have considered new tool (a simple wrapper) without that parameter, but haven't got any idea for the name (to not be confusing with existing one). Any idea?

**Comment by andrewdavidwong** [comment]
> This is especially important for qvm-move-to-vm - it could be fatal if you have a file/directory with the name of the target VM in the same place...

Can you provide an example?

> We have considered new tool (a simple wrapper) without that parameter, but haven't got any idea for the name (to not be confusing with existing one). Any idea?

`qvm-copy`
`qvm-move`

Rationale: Drop `-to-vm` from the name of the command, since the target VM is no longer specified as an argument to the command (but rather in a subsequent prompt).

**Comment by marmarek** [comment]
> This is especially important for qvm-move-to-vm - it could be fatal if you have a file/directory with the name of the target VM in the same place...
> 
> Can you provide an example?

Sure: #2472

> qvm-copy
> qvm-move

+1

**Comment by andrewdavidwong** [comment]
> Sure: #2472

Ah, I see!

**Comment by andrewdavidwong** [comment]
Closing as `notanissue` since the reported behavior is intended.
