### ISSUE TITLE
sys-usb freeze after suspend

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#3142]
#### Qubes OS version (e.g., `R3.2`): R4.0

---

### Steps to reproduce the behavior:

Start the system. Suspend it. Wait few seconds. Wake it up.

### Expected behavior:

Working sys-usb after system suspend.

### Actual behavior:

```
[   77.992077] Freezing user space processes ... (elapsed 0.001 seconds) done.
[   77.993575] Freezing remaining freezable tasks ... (elapsed 0.001 seconds) done.
[   77.997918] PM: freeze of devices complete after 3.027 msecs
[   77.998408] PM: late freeze of devices complete after 0.464 msecs
[   78.017709] PM: noirq freeze of devices complete after 19.275 msecs
[   78.018020] xen:events: Xen HVM callback vector for event delivery is enabled
[   78.018020] xen:grant_table: Grant tables using version 1 layout
[   78.018020] Suspended for 249.976 seconds
[   78.021274] PM: noirq thaw of devices complete after 3.450 msecs
[   78.021452] PM: early thaw of devices complete after 0.126 msecs
[   78.021606] rtc_cmos 00:02: System wakeup disabled by ACPI
[   78.067039] xhci_hcd 0000:00:05.0: port 8 resume PLC timeout
[   78.067039] xhci_hcd 0000:00:05.0: port 6 resume PLC timeout
[   78.067039] xhci_hcd 0000:00:05.0: port 5 resume PLC timeout
```
And at this point sys-usb console is not responsive (nor any other application there).

This happens regardless of `virt_mode` property (`pv` or `hvm`).

#### Related issues:

Branched from #2849 

cc @HW42

**Comment by marmarek** [comment]
Unloading `xhci-pci` before suspend "fixes" this.

**Comment by HW42** [comment]
> Unloading xhci-pci before suspend "fixes" this.

So it works if you reload it after suspend?

**Comment by marmarek** [comment]
Yes.

**Comment by marmarek** [comment]
Looks like the xhci-pci is already on the blacklist to automatically unload before suspend. But the scripts is called by non-root, so it fails. Thanks @jpouellet for debugging as part of #3151

**Comment by HW42** [comment]
Do you know if this previously (R3.2) also led to a hanging VM? I.e. is this purely a regression because of the broken blacklist script or are there two problems (blacklist not working and hanging VM after suspend)?

**Comment by marmarek** [comment]
On 3.2 xhci-pci is blacklisted too and there the unloading script works (is properly called as root). I don't remember details, but I'd guess it caused hang there too. Ok, just tested - after disabling module unload, sys-usb with USB3 controller is unusable after suspend. First it is frozen, but few seconds later it panics on `__pci_write_msi_msg`. If you want, I can post a full message.
