### ISSUE TITLE
changing VM system storage max. size via GUI not working (R4.0rc1)

### ISSUE THREAD

**Issue by 0spinboson** [QubesOS/qubes-issues#3143]
#### Qubes OS version (e.g., `R3.2`):
R4.0-rc1, up to date with current-testing
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):
dom0

---

### Steps to reproduce the behavior:
open VM settings GUI for any VM, increase the system max. storage size, click OK.
### Expected behavior:
increases storage size for the root.img
### Actual behavior:
errors out, and appears to be trying to apply the private storage max size to the system storage max size. (E.g. in a VM with 3GB private 10gb system I get an error/warning that I can't decrease the size using this UI, and that I must use truncate if I really want this. In another VM the reported system storage max size has been increased to 68GB (the private max that was already set), though it didn't *actually* increase the system volume storage max size -- inside the VM it's still set at 10.5GB.
[log3.txt](https://github.com/QubesOS/qubes-issues/files/1351896/log3.txt)

**Comment by marmarek** [comment]
Fix already queued:
https://github.com/QubesOS/qubes-core-admin/pull/155/commits/6091bbbe88d9c6c72741e697ecc8a48cf58f0d9f
https://github.com/marmarek/qubes-core-agent-linux/commit/a59ac1b4f958dec263dc605fb8db37e6d915a9b9

**Comment by 0spinboson** [comment]
This doesn't appear to have fixed the issue. When I try to increase a VM's System storage max size, I now get a warning that shrinking of the root is disabled.

**Comment by marmarek** [comment]
Have you installed qubes-core-dom0 4.0.8 (from testing repo)?

**Comment by 0spinboson** [comment]
Yes, I've installed all of last night's updates just now, so I figured I'd test it.

**Comment by 0spinboson** [comment]
Precise error: 
Oct 08 14:23:06 dom0 qubesd[2962]: StoragePoolException('For your own safety, shrinking of root is disabled. If you really know what you are doing, use `truncate` on appvms/w7/root manually.',) while calling src=b'dom0' meth=b'admin.vm.volume.Resize' dest=b'w7' arg=b'root' len(untrusted_payload)=10

**Comment by 0spinboson** [comment]
By the way: is it intentional that size increases no longer apply to running VMs? I seem to recall that in R3.2 you could just grow these while the VM was running, but now it doesn't seem to realize its size has been increased until the next boot.

**Comment by marmarek** [comment]
You mean private storage or system storage? For private it should work immediately. If it doesn't, it's a bug.

**Comment by 0spinboson** [comment]
okay, then it's bugged. :)
