### ISSUE TITLE
qvm-start-gui --watch not terminated on logout (R4.0-rc1)

### ISSUE THREAD

**Issue by 0spinboson** [QubesOS/qubes-issues#3147]
#### Qubes OS version (e.g., `R3.2`):
R4.0-rc1
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):
dom0

----
see discussion here: https://github.com/QubesOS/updates-status/issues/246

**Comment by marmarek** [comment]
The result is that after logout + login, windows of VM's applications are not visible.
Workaround: kill qvm-start-gui process and start it again: `qvm-start-gui --all --watch &`
