### ISSUE TITLE
add Whonix to https://www.qubes-os.org/partners/

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#3150]
Could you add Whonix to https://www.qubes-os.org/partners/ please?

Suggested text (open for suggestions).

> [Whonix](https://www.whonix.org/) is a desktop operating system designed for advanced security and privacy. Whonix mitigates the threat of common attack vectors while maintaining usability. Online anonymity is realized via fail-safe, automatic, and desktop-wide use of the Tor network. A heavily reconfigured Debian base is run inside multiple virtual machines, providing a substantial layer of protection from malware and IP address leaks. Commonly used applications are pre-installed and safely pre-configured for immediate use. The user is not jeopardized by installing additional applications or personalizing the desktop. Whonix is under active development and is the only operating system designed to be run inside a VM and paired with Tor.

> The developers of Qubes and Whonix are cooperating. While Whonix is an independent Linux distribution, it has been integrated into Qubes OS and be run on top of Qubes OS, called [Qubes-Whonix](https://www.qubes-os.org/doc/whonix/).

**Comment by andrewdavidwong** [comment]
Yes, we're happy to! Thank you, @adrelanos and everyone who has contributed to Whonix!

https://www.qubes-os.org/partners/#whonix
