### ISSUE TITLE
template package removal failing - make template package removal code more resilient

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#3155]
#### Qubes OS version (e.g., `R3.2`):

R4 RV1

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):

dom0

---

### Steps to reproduce the behavior:

1) Not sure. Start from a "messed up" state. In my case tmp-tmp-debian-8 existed but debian-8 not (as a follow up issue of #3153). Or force remove (perhaps with illegal developer-only method) the debian-8 template behind qvm tools back.

2)

    sudo dnf remove qubes-template-debian-8

`sudo qubes-dom0-update --action=reinstall qubes-template-debian-8` also fails.

### Expected behavior:

Package should be removed anyhow.

### Actual behavior:

Package not removed because rpm prerun scriptlet fails. It fails because it runs `qvm-shutrun debian-8` which fails since there is no such template.

**Comment by marmarek** [comment]
Just happened to me exactly the same. Workaround: `rpm -e --noscripts qubes-template-debian-8`, then install package with qubes-dom0-update normally.
