### ISSUE TITLE
sys-whonix issue (server rejected connection)

### ISSUE THREAD

**Issue by boistordu** [QubesOS/qubes-issues#3156]
#### Qubes OS version (e.g., `R3.2`):
R3.2
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):
whonix-gw

---

### Steps to reproduce the behavior:
I don't have any specific steps, it's like that from the beginning and just after qubes installation I've put all templates up to date. 
### Expected behavior:
To my understanding, we should be able to connect any appvm or hvm to sys-whonix and have connectivity
### Actual behavior:
I can add any bridges I want if it si a obfs3 it will tells me TTL expiration
if it is an obfs4 (sever rejected conneciton) 
in arm controller and so I got no connectivity and sometimes connectivity magically appear for some minutes and then nothing again
### General notes:
I've created a post on the forum but nobody has any idea about my problem 
my sys-whonix is connected to sys-firewall. 
sys-firewall and sys-net are based on fedora-25-minimal template.
I've tried to create a ticket at the help mail address butthe system answer me that ticket creation failed because no authorization to create in the queue help
I don't think I'm in a dictatorship with any censorship in place for that ^^ 
---

**Comment by adrelanos** [comment]
Was posted also here:

https://forums.whonix.org/t/bootstrap-stucked-at-10-with-sys-whonix

I doubt there is any bug at work here. You could argue a usability issue and it would be true. But we are working on that (anon-connection-wizard...) so a ticket here won't be needed.

I suggest to close this ticket. We are unfortunately not able to help everyone with all issues all the time.

**Comment by boistordu** [comment]
No it's not a bug, definitely not. 
On the forum the last guy pointed to me the tor beta stack website. 
Well I've made the thread [here](https://tor.stackexchange.com/questions/15901/been-tampered-been-filtered-or-just-a-network-settings-messing-around). I'm not actually sure that there is not a filter in place in belgium.... And I need your expertise of you all to know that.
So if there would be a filter in place, would the bridges be pingable? 
If it is not a filter, the only remain possibility is a bad interaction between my own router or at least something on my network and that whonix. 
I have not a clue about how to test that really. If I would have a thousand of euros right here right now I could put me project of a pfsense box in place between the first switch and the router and I would see if there is any return strange interaction or something out of the ordinary but right now I don't have the hardware to put that in place, so any idea is welcomed. 
Anyway there is a clear change of connectivity if I create a wifi access point with my phone through LTE and my wired network and that is beyond normal since it is the same provider. Or they would have put in place the same filter on the whole infrastructure for an unknown reason?

**Comment by andrewdavidwong** [comment]
@boistordu: I recommend posting your question on a Tor-related forum/ML, or perhaps the Whonix forums.

**Comment by boistordu** [comment]
as previously stated is already under way but not making a  lot of progress for the moment
