### ISSUE TITLE
After install 4.0rc1 on Asus Zenbook UX32A "IGD for VT" error

### ISSUE THREAD

**Issue by kramse** [QubesOS/qubes-issues#3159]
#### Qubes OS version (e.g., `R3.2`):
4.0rc1

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):
Xen dom0
Booting after install gave "BIOS did not enable IGD for VT properly" fail
---

### Steps to reproduce the behavior:
Install Qubes 4.0rc1 - no problems observed.
Reboot, coold boot, any boot, starts booting Xen, show a lot of data, then panics.

### Expected behavior:
Running fine, since this specific CPU is on the Intel list, linked from 4.0 requirements.

### Actual behavior:
Boot panic
"BIOS did not enable IGD for VT properly" fail and panics, reboot

### General notes:
BIOS version 214, upgraded to BIOS 216
https://www.asus.com/us/Laptops/ASUS-ZenBook-UX32A/HelpDesk_BIOS/

This laptop has run Qubes before, and is not used currently. Available for further testing if need be. Currently boots Kali from the Built-in SSD, so can do some debugging I guess.

---

**Comment by tonsimple** [comment]
@kramse 
did you try iommu=force  thing ?

**Comment by marmarek** [comment]
Or, the other way around: drop `iommu=no-igfx` from Xen parameters.

**Comment by marmarek** [comment]
Should be fixed by https://github.com/QubesOS/qubes-vmm-xen/pull/11
