### ISSUE TITLE
sys-net ethernet breaks with lenovo dock

### ISSUE THREAD

**Issue by GAhlekzis** [QubesOS/qubes-issues#3160]
#### Qubes OS version (e.g., `R3.2`):
R3.2
#### Affected TemplateVMs (`fedora24`):
fedora24

---

### Steps to reproduce the behavior:
- Connect an ethernet cable to the laptop dock.
- Connect a Lenovo t420 (in my case) to the dock.

### Expected behavior:
- Network Manager just switches to the new connection.

### Actual behavior:
- The ethernet device is listed as 'not managed'.
- There is no ethernet connectivity.
- ifconfig does not list any ethernet interfaces.

### General notes:
I guess this is a problem with the communication between sys-net and everything else?
It's really not viable to use my dock with Qubes at the moment even though I'd love to,
because I need to reboot (with the dock connected) for everything to work properly.
And when i disconnect again, the ethernet breaks again.

---

**Comment by andrewdavidwong** [comment]
Note that this may end up being closed as "too localized" if it turns out to be hardware-specific issue with the dock. Leaving it open for now in case it's an instance of a more general networking problem.

**Comment by GAhlekzis** [comment]
I just hope this (and other little weird things with the dock attached) get resolved with the new Qubes version with the newer version of fedora (so more drivers?).

Right now I'm just not using ethernet with my laptop (and dock) anymore so it doesn't bother me at the moment.

**Comment by GAhlekzis** [comment]
After the my default template became Fedora-26 everything works out of the box.
/close
