### ISSUE TITLE
Qubes R4 qvm-run --all regression (starts all VMs) (blocking rather than non-blocking)

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#3162]
#### Qubes OS version (e.g., `R3.2`):

Qubes R4 RC1 with all stable upgrades

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):

dom0

---

### Steps to reproduce the behavior:

    qvm-run --all "sudo poweroff"

(This was useful in Qubes R2 to work around various reboot/shutdown related hickups. (Shutdown never completing.))

### Expected behavior:

Like in Qubes R3.2. The command only being run in VMs currently being running. Not starting all VMs to run the command.

Non-blocking. Running that command on all VMs at once.

### Actual behavior:

Starts all VMs.

Blocking. Runs the command in first VM, goes on the next one. Very slow process. No longer useful.

**Comment by marmarek** [comment]
This should be fixed in qubes-core-admin-client 4.0.5, what version do you have?

**Comment by 3hhh** [comment]
Related: #3083 #3130

**Comment by adrelanos** [comment]
Marek Marczykowski-Górecki:
> This should be fixed in qubes-core-admin-client 4.0.5, what version do you have?
> 

Yes, the updates from Qubes testing sorted this out, thanks! :)
