### ISSUE TITLE
Expand vm disk in gui and the vm won't start

### ISSUE THREAD

**Issue by mannp** [QubesOS/qubes-issues#3166]
#### Affected TemplateVMs:fed-25

---

### Steps to reproduce the behavior:

Expanded the private storage maximum on a vm as it was running out of space and it worked fine, but did the same to another and now it won't start.

### Expected behavior:

If the vm or dom0 runs out of disk space it should not allow actions that go beyond the available space and should give an error message that it is out of disk space.

### Actual behavior:

Odd error;

> b' Snapshot origin LV vm-personal-private not found in Volume group qubes_dom0.\n'

### General notes:

---

**Comment by marmarek** [comment]
This looks like #3164, so closing as a duplicate.
