### ISSUE TITLE
"No policy definition found for qubes.InputKeyboard action" on resume from suspend

### ISSUE THREAD

**Issue by vincentadultman** [QubesOS/qubes-issues#3168]
#### Qubes OS version: 3.2

---

### Steps to reproduce the behavior:

Suspend laptop, resume laptop.

### Expected behavior:

I am not (knowingly) trying to pass a device, so expect no policy window to appear.

### Actual behavior:

Message box appears in dom0 after resume from suspend with text

Title = "[Dom0] Add a new entry"
Text =  "No policy definition found for qubes.InputKeyboard action. Type YES if you want to create a default policy file"
Buttons =  Cancel & Okay

### General notes:

This occurs on laptop I have been using since 3.0 with internal keyboard and trackpad/point. Perhaps after switching usbvm to fedora25 template from fedora24? In any case there is no keyboard device attached to the usbvm (which has all system usb controllers and devices, inc built in webcam and fingerprint reader).

Having never tried to use the Qubes input proxy, I've not got input-proxy-receiver package installed in dom0, so don't know if this message is expected in some fashion (seems not, as I'm not trying to pass keyboard actions from any vm into dom0...at least intentionally...). System has been upgraded in place from 3.1 and I have tasket's vmauth file in place in /etc/qubes-rpc/policy/ to use with dispvms but have not otherwise touched the default policy files. 

---

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
