### ISSUE TITLE
Documentation on qubes-usb-proxy

### ISSUE THREAD

**Issue by niccokunzmann** [QubesOS/qubes-issues#3171]
#### Affected TemplateVMs: debian-8

---

### Steps to reproduce the behavior:
```
$ qvm-usb -l
$ qvm-usb -a debian-8 sys-usb:4-2
ERROR: qubes-usb-proxy not installed in the VM
```

### Expected behavior:

The usb device is attached to debian-8
OR
I find documentation on how to attach it or install the `qubes-usb-proxy`.

### Actual behavior:

The usb device is not attached.

### General notes:

- I suppose, this is the repository to contain the usb proxy: https://github.com/QubesOS/qubes-app-linux-usb-proxy
- if I [search for `qubes-usb-proxy` in the docs](https://github.com/QubesOS/qubes-doc/search?q=qubes-usb-proxy&type=Code&utf8=%E2%9C%93), I only find one instance which does not declare how to install and where to find it.

### Possible solution:

Add documentation on how to install the qubes-usb-proxy to a debian vm or maybe to a vm in general.

I will try out and see what I find with the https://github.com/QubesOS/qubes-app-linux-usb-proxy

---

**Comment by niccokunzmann** [comment]
Once those pull-requests are merged, this can be closed.

- https://github.com/QubesOS/qubes-app-linux-usb-proxy/pull/3
- https://github.com/QubesOS/qubes-doc/pull/469

**Comment by marmarek** [comment]
Well, the error says you need to install `qubes-usb-proxy`. [Documentation](https://www.qubes-os.org/doc/usb/#attaching-a-single-usb-device-to-a-qube-usb-passthrough) also already include that information:
> To use this feature, you need to install `qubes-usb-proxy` package in the templates used for USB qube and qubes you want to connect USB devices to.

Do you think this is not sufficient? Not sure if duplicating basic distribution usage guides ("how to install package?" `apt-get` usage, `dnf` usage, etc) is needed...

cc @andrewdavidwong

**Comment by niccokunzmann** [comment]
I could not install qubes-usb-proxy in the Template VM.
Now, I see the error was a deactivated network.

However, out of some reasons, I installed it from the tar.gz file. I guess, you do not want this path.
Let's add documentation on how I am supposed to install the qubes-usb-proxy, so others do not do that.

I suppose, I could get another pull-request closed where I put work in so I will ask here: Where do you think this installation should be added?
I think, it should be added here:
- https://github.com/QubesOS/qubes-app-linux-usb-proxy - for people like me who search and stumble upon the repository and forget that their Template VM has no Internet. This can be a reference to the docs. I mean: When I see the repository I would like to know how to properly use it.
- https://www.qubes-os.org/doc/usb/#attaching-a-single-usb-device-to-a-qube-usb-passthrough - Here It was not clear to me how to install it. I propose:

> To use this feature, you need to install the `qubes-usb-proxy` system package in the templates used for the USB qube and qubes you want to connect USB devices to. Under debain, do `sudo apt-get install qubes-usb-proxy` and under Fedora `yum install qubes-usb-proxy`. If you are in a Template VM, also activate your Internet connection.

I think, duplicating the information how to install it, is needed: I did it wrong. I think, I know how to install packages (Thinking you know something is sometimes in the way of seeing the truth). We can also add a subsection on how to securely install it. It can not hurt, I think. Also, I can add a link to the repository for people who would like to know more about how it works and like to contribute.

**Comment by andrewdavidwong** [comment]
> Not sure if duplicating basic distribution usage guides ("how to install package?" apt-get usage, dnf usage, etc) is needed...

> To use this feature, you need to install the qubes-usb-proxy system package in the templates used for the USB qube and qubes you want to connect USB devices to. Under debain, do sudo apt-get install qubes-usb-proxy and under Fedora yum install qubes-usb-proxy.

Yes, I think we should say something like this.

(I would exclude the "activate your internet connection" part, since it shouldn't be necessary to say that. Templates should already be have access to updates proxies. If not, it's a separate bug. Also note that it's `dnf` instead of `yum` under Fedora now.)

**Comment by andrewdavidwong** [comment]
Merged: https://github.com/QubesOS/qubes-doc/commit/8b357626dc90eb99362355cac37320c988f6e045
