### ISSUE TITLE
qvm-block doesn't work with domU loop devices

### ISSUE THREAD

**Issue by 3hhh** [QubesOS/qubes-issues#3172]
#### Qubes OS version (e.g., `R3.2`):
4.0rc1
qubes-core-admin-client.noarch 4.0.7.0.1.fc25 from the current testing repo (it did work with e.g. 4.0.4)

### Steps to reproduce the behavior:

- Create a loop device in e.g. sys-usb.
- Attempt to attach it to a different VM [domU] from dom0 using qvm-block a.

### Expected behavior:
A device appears in [domU].

### Actual behavior:
No device appears. `qvm-block l` however incorrectly shows a non-existing frontend device. In particular no error seems to be logged.

#### Related issues:
pretty identical bug in 3.2: #2126

### General notes:
This is a regression from the current stable repo as it works in version 4.0.4 of the package.

If there's a workaround using e.g. `xl block-attach` or a downgrade method (cf. #3169), I'd be interested. I tried downgrading qubes-core-admin-client.noarch using yum, but that didn't pull the related dependencies.

**Comment by marmarek** [comment]
Check kernel messages in target domain - maybe there was some error while attaching the device.

**Comment by 3hhh** [comment]
dmesg in domU shows absolutely nothing (last entry was something about iptables/netfilter that always comes up last during boot if I recall correctly).

It only happened after an update from 4.0.4 --> 4.0.7, i.e. I'm pretty sure it's a generic issue.

**Comment by 3hhh** [comment]
Just changed the description as I noticed that #2126 is the 100% identical bug in 3.2, which now also pops up in 4.0rc1.

**Comment by 3hhh** [comment]
Ok, did some further testing:

- unfortunately `systemctl restart xendriverdomain` after attaching doesn't fix the issue in domU
- `sudo journalctl -b0` shows absolutely nothing related in domU
- this bug applies to domU AppVMs (I didn't test dispVMs)

**Comment by 3hhh** [comment]
P.S.: I tested with the debian-8 template VM.

**Comment by andrewdavidwong** [comment]
> Just changed the description as I noticed that #2126 is the 100% identical bug in 3.2, which now also pops up in 4.0rc1.

We generally don't maintain duplicate issues for the same bug in different Qubes versions. I think that, in a case like this, we would usually reopen #2126 as a regression (if that's indeed what happened; if not, then that suggests it's not really a duplicate). Do you see any reason not to do this (in the future, anyway)?

**Comment by marmarek** [comment]
Found the problem, it is in xen-libs package, not qubes-core-admin-client.
To confirm, check `/var/log/xen/xldevd.log` - you'll see something about inability to read script.

**Comment by 3hhh** [comment]
@marmarek :

> To confirm, check /var/log/xen/xldevd.log - you'll see something about inability to read script.

`/var/log/xen/xldevd.log` is a 0 bytes file in my AppVM, the archived ones as well. I guess I'll have to wait for the patch to go to the testing repo and check again then.

@andrewdavidwong : The root cause was a different one as the fix didn't work.

**Comment by 3hhh** [comment]
@marmarek Yes, that fixed it, thanks a lot!

I also found the log line you mentioned in dom0 /var/log/qubes.
