### ISSUE TITLE
Hardcoded "VideoRam 65536" in xorg-qubes.conf.template is too low for multiple 4k displays

### ISSUE THREAD

**Issue by tonsilware** [QubesOS/qubes-issues#3174]
### Qubes OS version:

R3.2

---

### General notes:

Yesterday I upgraded two of my displays to 4K (the third is 2560x1400). This resulted in major QubesOS AppVM issues - like AppVMs not registering clicks beyond a certain X/Y co-ordinate and "Run command in VM" frequently just not working at all. 

I thought I'd try investigate: It seems that on each AppVM "qubes-set-monitor-layout" calls "xrandr". I discovered that xrandr was throwing an error when the requested resolution was above a certain level. So I increased the VideoRAM in /etc/X11/xorg-qubes.conf.template on all my templates and that seems to have solved the problem.

---

### Expected behavior:

Perhaps, if possible, rather than having the VideoRAM hardcoded at "65536" it should be dynamically calculated and populated (like the other values in the template) to ensure that there is sufficient VideoRAM for the AppVM when it starts (based upon the resolution at the time of the AppVM starting). e.g. something like:
```
minVideoRAM = (total resolution width) * (total resolution height) * (bytes per pixel) + (some additional head room?)
VideoRAM = max(minVideoRAM, 65536)
```

**Comment by marmarek** [comment]
Created pull request for this (https://github.com/QubesOS/qubes-gui-agent-linux/pull/36). Can you verify if that solve the problem?

cc @TheBubblePopped

**Comment by tonsilware** [comment]
Thanks, I've tested the changes and that solves the problem on my system (4 monitors in total: 2x4k, 1x(2560x1400) and 1xFHD).
