### ISSUE TITLE
Unable to add software to AppVM through TemplateVM update

### ISSUE THREAD

**Issue by pietrushnic** [QubesOS/qubes-issues#3181]
#### Qubes OS version:

`R4.0`

#### Affected TemplateVMs: 

`fedora-25`

---

### Steps to reproduce the behavior:

1. Create AppVM using `fedora-25`
2. Run AppVM - check there is no commad eg. `tmux`
3. Power off AppVM
4. Run `fedora-25` and install `tmux`
5. Poweroff `fedora-25`
6. Run AppVM and check if `tmux` exist

### Expected behavior:

`tmux` exist

### Actual behavior:

`tmux` not found

### General notes:

IIRC this affects other templates.

I found this when trying to add recent ucode file to `sys-net` since I have problem with making my Intel 8260 card working, so persistent file adding also not working.

Question is, if I'm missing some sync feature for Qubes 4.0 ?

---

**Comment by 0spinboson** [comment]
Could you try cloning the template and assigning that as template to the appvm? I ran into this once as well a few weeks ago.

**Comment by marmarek** [comment]
This may be related to #3164. Try starting and stopping template again.

**Comment by pietrushnic** [comment]
@marmarek @0spinboson shutdown and start seem to work:

```
qvm-shutdown fedora-25
qvm-shutdown test-1
qvm-start fedora-25
qvm-shutdown fedora-25
qvm-start fedora-25
qvm-start test-1
```

After above sequence `test-1` were synchronized. Is there any chance that not using `qvm-start` lead to problem ? Will try to observe that if this may be the case.

**Comment by marmarta** [comment]
I'll close this - there were fixes in https://github.com/QubesOS/qubes-issues/issues/3164 that should have helped. If it has happened again after the fixes were introduced, please reopen this issue.
