### ISSUE TITLE
qvm-block attach not working in 4.0?

### ISSUE THREAD

**Issue by joshuathayer** [QubesOS/qubes-issues#3186]
#### Qubes OS version:
Qubes 4.0rc1, with dom0 and templates up to date with `current-testing` as of today.

#### Affected TemplateVMs: 
Not working with fedora-25 or debian-8

### Steps to reproduce the behavior:

Attach a USB drive to a free USB port. It's recognized in the USB VM and I can mount the drive there. `qvm-block l` in dom0 shows the drive as `sda`, as expected:

    sys-usb:sda   My_Passport_0820 ()      
    sys-usb:sda1  My_Passport_0820 (sony)  

`qvm-block a personal sys-usb:sda` in dom0 executes without error. The only thing logged with that command, either on `personal` or in dom0, seems to be two identical lines in dom0 in `/var/log/xen/console/guest-sys-usb.log`:

    xen-blkback: backend/vbd/9/51840: using 1 queues, protocol 1 (x86_64-abi) persistent grants`. 

At this point, `qvm-block l` in dom0 shows the drive attached to `personal`, as expected:

    BACKEND:DEVID  DESCRIPTION              USED BY
    sys-usb:sda    My_Passport_0820 ()      personal (frontend-dev=xvdi, read-only=no)
    sys-usb:sda1   My_Passport_0820 (sony)  

However, nothing is logged in `personal` when the `qvm-block a` command is run, and no new device becomes available. `ls /dev/xvdi*` shows nothing.

Running `xl block-list personal` in dom0 is revealing:

    Vdev  BE  handle state evt-ch ring-ref BE-path                       
    51712 0   9      4     -1     -1       /local/domain/0/backend/vbd/9/51712
    51728 0   9      4     -1     -1       /local/domain/0/backend/vbd/9/51728
    51744 0   9      4     -1     -1       /local/domain/0/backend/vbd/9/51744
    51760 0   9      4     -1     -1       /local/domain/0/backend/vbd/9/51760
    51840 12  9      3     31     4128     /local/domain/12/backend/vbd/9/51840

The new device is in state 3 ("XenbusStateInitialised") rather than state 4 ("XenbusStateConnected"). This seems similar to #2126, which was resolved by running `systemctl restart xendriverdomain` in the target VM (in that case, a disposable VM). That command seemed not to help my problem.

### Expected behavior:
I'd expect running `qvm-block a personal sys-usb:sda` in dom0 to cause a new device to appear in the `personal` VM, and to allow that device to be mounted as normal in that VM.

### Actual behavior:

See above-the device does not appear in the target VM (`personal`). Running `xl block personal` in dom0 shows the device to be in the wrong state: "XenbusStateInitialized" rather than "XenbusStateonnected". 

### General notes:

I'm on a Thinkpad T440s running Qubes 4.0rc1 with dom0 and the domU templates up to date with `current-testing`. The same behavior seems to take place with both debian- and fedora-templated VMs.

#### Related issues:
#2126 seems related- the symptoms match mine closely, but the resolution there did not address my issue.

Thanks!

**Comment by marmarek** [comment]
I think this is a duplicate of #3172. Try installing just [uploaded xen update](https://github.com/QubesOS/updates-status/issues/276) and check if that helps. After the update you need to either reboot, or restart libvrtd + qubesd services (in that order).

**Comment by joshuathayer** [comment]
Awesome, that seemed to fix it for both debian and fedora VMs. Thanks.
