### ISSUE TITLE
Qubes R4 salt error - [ERROR] output: Error: Unknown repo: 'qubes-templates-community' - while trying to install Whonix

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#3188]
#### Qubes OS version:
Qubes R4 with all Qubes testing repositories

#### Affected TemplateVMs: 
Dom0

### Steps to reproduce the behavior:
Install Qubes R4 with all Qubes testing repositories.

Enable Qubes community templates repository in `/etc/yum.repos.d/qubes-templates.repo`.

    sudo qubesctl state.sls qvm.sys-whonix

### Expected behavior:

Ending up with functional sys-whonix.

### Actual behavior:

```
[ERROR] Command '['dnf', --quiet', 'clean', 'expire-cache', '--disablerepo=*', '--enablerepos=qubes-templates-community'']' failed with return code: 1
[ERROR] output: Error: Unknown repo: 'qubes-templates-community'
```

---

#### Related issues:

https://github.com/QubesOS/qubes-issues/issues/2157
https://github.com/QubesOS/qubes-issues/issues/2954

**Comment by marmarek** [comment]
Do you have [this](https://github.com/QubesOS/updates-status/issues/168) update installed?

**Comment by adrelanos** [comment]
Yes, even the newer version, mgmt-salt-dom0-update 4.0.2 is installed in dom0.

**Comment by adrelanos** [comment]
This bug is happening with no Whonix templates installed.

As a workaround I used `sudo qubes-dom0-update qubes-template-whonix-gw qubes-template-whonix-ws`. Then this issue does not happen, because then salt does not attempt to install it since already installed.

**Comment by marmarek** [comment]
I've just tried and indeed got this error. But also the template got installed. Did you get the same?

**Comment by adrelanos** [comment]
I aborted after seeing that error.
