### ISSUE TITLE
default_fw_netvm - wrong default value (set to None) (should be set to sys-net) (was: qubes-vm-settings settings bug - failed to change NetVM of sys-whonix)

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#3190]
failed to change NetVM of `sys-whonix` using `qubes-vm-settings`

#### Qubes OS version:

Qubes R4 with all Qubes testing repositories

#### Affected TemplateVMs: 

Dom0

---

### Steps to reproduce the behavior:

Install Qubes R4 with all Qubes testing repositories.

Enable Qubes community templates repository in /etc/yum.repos.d/qubes-templates.repo.

    sudo qubes-dom0-update qubes-template-whonix-gw qubes-template-whonix-ws

(Did last command because of https://github.com/QubesOS/qubes-issues/issues/3188.)

    sudo qubesctl state.sls qvm.sys-whonix

 start menu -> sys-whonix -> vm settings -> set NetVM to default (sys-firewall).

(Did last action because of https://github.com/QubesOS/qubes-issues/issues/3189.)

### Expected behavior:

sys-whonix's NetVM set to default (sys-firewall).

### Actual behavior:

sys-whonix's NetVM setting gets reset to none.

### General notes:

Might be related to (or even a follow-up issue?) https://github.com/QubesOS/qubes-issues/issues/3188?

Maybe it is because sys-whonix was already running. But even if sys-whonix was running, changing the NetVM using qubes-vm-settings (started from start menu -> sys-whonix -> vm settings) should be possible?

`qvm-shutdown sys-whonix` followed by `qvm-prefs --set sys-whonix netvm sys-firewall` worked for me.

After restarting sys-whonix, to provide further debug output, I set sys-whonix NetVM from default (sys-firewall) to sys-firewall, clicked okay. Restarted qubes-vm-settigns for sys-whonix. Expected: set to sys-friewall. Actual result: set to `(none) (current)`.

Using `qubes-vm-settings sys-whonix` while sys-whonix has been shutdown (and confirmed using `qvm-ls`) doesn't help either. The only way to change sys-whonix NetVM setting for me currently is the command line.

---

#### Related issues:

https://github.com/QubesOS/qubes-issues/issues/2157
https://github.com/QubesOS/qubes-issues/issues/2954

**Comment by marmarek** [comment]
Does `qvm-prefs --default sys-whonix netvm` work?

**Comment by adrelanos** [comment]
Did run `qvm-prefs --default sys-whonix netvm`. Then did run `qvm-prefs sys-whonix netvm`. It did output:

`None`

**Comment by marmarek** [comment]
Maybe you have None as default netvm? Check `qubes-prefs`.

**Comment by adrelanos** [comment]
No, `qubes-prefs` shows `default_netvm` is set to `sys-firewall`. (It's a fresh installation of Qubes R4 RC1 with upgrades from Qubes testing repository. Very few changes otherwise.)

**Comment by marmarek** [comment]
What is value of `default_fw_netvm`?

**Comment by adrelanos** [comment]
`None`

**Comment by marmarek** [comment]
Ok, so here is the problem. When VM itself is a ProxyVM (aka have `provides_network=True`), it use `default_fw_netvm` instead of `default_netvm`. And apparently the former isn't properly set.

**Comment by adrelanos** [comment]
I.e. not a user error? The Qubes default `default_fw_netvm` value is set wrong here? (I swear I didn't change the defaults. :)

**Comment by marmarek** [comment]
Yup. Same problem on my system.
