### ISSUE TITLE
More informative error message for `qvm-pci a` on halted VMs

### ISSUE THREAD

**Issue by 3hhh** [QubesOS/qubes-issues#3195]
#### Qubes OS version:
4.0rc1, current testing repo updates

### Steps to reproduce the behavior:

Shutdown [AppVM]

```
qvm-pci a [AppVM] dom0:[device]
Devices can only be attached  non-persistent to a running vm
```

### Expected behavior:
[device] is permanently attached to [AppVM]

### Actual behavior:
Output of `Devices can only be attached  non-persistent to a running vm` and no action.

### General notes:
Starting the VM and then attaching it tends to work, but only for the runtime of the VM.

Was tested with an AppVM and a DispVM, both were affected.

Using qubes-vm-settings to attach a device works (even though that tends to segfault on exit quite often).

**Comment by marmarek** [comment]
You need `-p` (or `--persistent`) option for that.

**Comment by 3hhh** [comment]
Ok, my bad then, sorry. The error was quite misleading though...

**Comment by andrewdavidwong** [comment]
Reopening as a UX issue for the error message, if it's OK with @marmarek.

**Comment by marmarek** [comment]
What about "VM not running, can only attach device with persistent flag"?

**Comment by andrewdavidwong** [comment]
Sounds good to me.
