### ISSUE TITLE
Appmenus not properly populated

### ISSUE THREAD

**Issue by jpouellet** [QubesOS/qubes-issues#3200]
#### Qubes OS version:
R4-rc1

#### Affected TemplateVMs: 
dom0

---

Under certain circumstances (not sure what yet) .desktop files will not propagate to `~/.local/share/applications`, even though their per-AppVM files exist in `~/.local/share/qubes-appmenus/<appvm>/<appvm>-<app>.desktop`.

My system has also never copied `/usr/share/qubes-appmenus/*` to `~/.local/share/applications` (nor `/usr/share/applications`), leading me to initially believe that DispVMs were not implemented enough to be started by users yet (which does not appear to be true).

### Steps to reproduce the behavior:

Not minimal set of actions to reproduce, but:
- clone fedora-25 to T1
- install google-chrome in template T1
- make appvm A based on T1
- clone fedora-25 to T2
- install google-chrome and google-chrome-unstable in T2
- switch template for A from T1 to T2
- now no new .desktop files selected for A will be propagated to the `~/.local/share/applications` despite `~/.local/share/qubes-appmenus/A/A-google-chrome{-unstable}.desktop` existing (and being well-formed, and cp'ing into `~/.local/share/applications` having the desired effect) and `~/.local/share/qubes-appmenus/A/whitelisted-appmenus.list` listing `google-chrome.desktop\n\ngoogle-chrome-unstable.desktop\n\n...`.

### Expected behavior:

DispVMs startable via Q menu, and updating list of Applications for VM actually changing the desktop files in Q menu.

### Actual behavior:

No DispVM .desktop files ever, sometimes AppVM .desktop files stop updating.

### General notes:

simply invoking qvm-sync-appmenus does not resolve this - will need to dig into source

**Comment by marmarek** [comment]
As for DispVMs, there is a new way for setting menu for it. To get it on rc1 system: install updates and launch `sudo qubesctl state.sls qvm.default-dispvm`.
