### ISSUE TITLE
Firstboot does not offer sys-usb creation if USB mouse connected

### ISSUE THREAD

**Issue by rootkovska** [QubesOS/qubes-issues#3203]
Even if the mouse was actually announcing itself as a keyboard HID (which might be the case here), still we should allow for an easy recovery for the user, e.g.: add text "you must disconnect keyboard to create USB qubes", and detect disconnect even and refresh the screen (or offer Refresh button). Otherwise it would be _very_ difficult for a casual user to create sys-usb manually...

**Comment by marmarek** [comment]
I think you forgot some "not" in the issue title?

**Comment by rootkovska** [comment]
> I think you forgot some "not" in the issue title?

I sure did, corrected.

**Comment by DemiMarie** [comment]
Still an issue in R4.1.

**Comment by andrewdavidwong** [comment]
> Still an issue in R4.1.

Ok, but the milestone change associated with this comment doesn't reflect the general practice of how our milestones work. The milestone is set to the _earliest affected supported release_. Since 4.0 is still supported (for now), it is incorrect to change the milestone from 4.0 to 4.1.
