### ISSUE TITLE
qvm-pci attach options not documented

### ISSUE THREAD

**Issue by rootkovska** [QubesOS/qubes-issues#3204]
It's virtually impossible for the user to figure out what are allowed options to pass to the `qvm-pci attach -o <option>`. This is especially problematic if the user wants to create e.g. sys-usb by herself (e.g. as a result of #3203) but bounces through the "Unable to reset PCI device (...)" and would like to disable PCI strict reset... (Sure enough she can google a bit and find the option is named `no-strict-reset=False`, but... please :/

**Comment by 0spinboson** [comment]
ah, so there is a --persistent flag there as well. Awesome. :p

**Comment by rootkovska** [comment]
> ah, so there is a --persistent flag there as well. Awesome / was wondering how to do that. :p

Heh :)
