### ISSUE TITLE
Make it easier for the user to work around PCI strict reset problems

### ISSUE THREAD

**Issue by rootkovska** [QubesOS/qubes-issues#3205]
On some chipsets it is required to pass `-o no-strict-reset=True` when assigning a device to VMs. Figure out the most friendly way of how to handle this (semi-) automatically.

**Comment by marmarek** [comment]
firstboot/salt already does that for sys-usb. No user action is needed.

**Comment by rootkovska** [comment]
Sure, but some users might want to do that later for other devices.

**Comment by marmarek** [comment]
So, probably you mean GUI VM settings, right? Adjusting issue labels for that.

**Comment by rootkovska** [comment]
Yeah, GUI setting + brief explanation in the same window what this is for. Ideally also the error message (displayed when strict reset is unsuccessful) could be hinting this option should be used, although I realize this might be tricky, since it's not our code that displays the error.

**Comment by adrelanos** [comment]
This was quite complicated indeed to figure out. Meanwhile when someone tries doing this using command line, some hints on the syntax here.

```
qvm-pci
qvm-pci detach sys-usb dom0:00_1d.0
qvm-pci attach --persistent -o no-strict-reset=False sys-usb dom0:00_14.0 
```
