### ISSUE TITLE
Create default "Dock" during firstboot

### ISSUE THREAD

**Issue by rootkovska** [QubesOS/qubes-issues#3206]
Something similar to what is displayed on this screenshot: https://github.com/QubesOS/qubes-issues/issues/2119#issuecomment-228776221

This will make the desktop look more modern and friendly to new users.

We can e.g. create 2 icons for each VM that Firstboot created (Firefox and Files), and have maybe one additional app (Terminal) hidden within the "stack" openable from the File's menu.

**Comment by ninavizz** [comment]
Addressed in Bessie prototype for #5677

**Comment by marmarta** [comment]
Menu has been implemented, and I don't think this will ever happen in the "Dock" format in any case, not unless we do some big changes like changing the window manager. Closing.
