### ISSUE TITLE
meminfo writer service: improve consistency

### ISSUE THREAD

**Issue by rootkovska** [QubesOS/qubes-issues#3207]
Currently there is a somehow inconsistent algorithm used to determine whether to start the meminfo-writer service (Dynamic Memory Balancing) for the VM or not. Typically it is started whenever the `meminfo-writer` service key is present, except if the VM gets PCI devices assigned, when it is not started.

Rather than having this weird logic in the code starting the service, move the logic away to the code which creates/disabled the service key creation. Thanks to this it will be much easier for both (advanced) users as well as other software (e.g. GUI manager) to find out if memory balancing is enabled for the VM or not.

Currently (4.0-rc2), Qubes Manager (i.e. the Settings window) displays wrong information for all device-hosting VMs, which is a direct result of the problem described here.

**Comment by marmarek** [comment]
Technically, HVM with PCI device cannot be started with maxmem > memory. But, when started, balloon driver can be used to take memory out of that VM. And thanks to IOMMU, memory fragmentation is not an issue anymore here (which was initial reason why we disable meminfo-writer in PCI-having VMs). So, we can support VMs with PCI devices and dynamic memory management. But such a VM needs to have all its memory during its early startup (until balloon driver is loaded).
Actually, that last point may not be needed if we use memory hotplug, I've tested it some time ago and it just work. Require one option to be enabled in VM kernel (`CONFIG_XEN_BALLOON_MEMORY_HOTPLUG`). And adjustments to qmemman.

This will in practice allow to use some actual software in a VM with PCI device, not only be a proxy (for network, USB etc).

So, maybe the right thing to do is not move this logic into one place, but remove it entirely? And if someone want to disable dynamic memory management of a VMs, he/she can do it anyway. And salt can do it for sys-net/sys-usb if we think its appropriate.

**Comment by rootkovska** [comment]
Let's not be so fast about removing the option to disable mem balancing: we still offer an (easy) option to run VMs as PV and in the future might offer even more options.

**Comment by marmarek** [comment]
It's not about removing option to disable mem balancing. It's about doing it (or not) automatically depending on various factors (PCI device having here). The later, as you noticed, currently is very non intuitive currently.

**Comment by rootkovska** [comment]
Ok, so you're proposing to have `no-meminfo-writer` service key, instead, and if not present, then always start the service, right?

**Comment by marmarek** [comment]
Something like this - keep `service.meminfo-writer` name and always start the service, unless this feature is present and set to false.
