### ISSUE TITLE
Timezone issues with non UTC

### ISSUE THREAD

**Issue by ERFier** [QubesOS/qubes-issues#3210]
#### Qubes OS version:

4.0 rc2

#### Affected TemplateVMs: 

dom0 and fedora-25 as netVM (ClockVM)

---

### Steps to reproduce the behavior:

Don't know exactly but i think installing with non UTC (e.g. Europe/Berlin) set and a DHCP-Server that advertises a ntp-server for the network. The ntp-server is from a Samba-Domaincontroller.

### Expected behavior:

The Dom0 displays the correct time for the current timezone (throu date and in systray) and log in UTC.

### Actual behavior:

The netVM gets the time and the dom0 gets the time. Dom0 seems to think that the time fetched from ClockVM is UTC and adds 2 hours as i'm in UTC+2. As a result the Logs are in Localtime and the time in systray has a +2 hours offset.

The workaround is to define time in dom0 to be utc. This way everything is localtime and i loose UTC. It may be fine if i never leave my timezone but if i travel i wont my system display the localtime at the place i am.

### General notes:

---

**Comment by marmarek** [comment]
Discussion: https://groups.google.com/d/msgid/qubes-devel/27e1dfaf-469a-4863-8913-da16ebadc2e4%40googlegroups.com

**Comment by ERFier** [comment]
Ok starting the systemd-timesyncd did the trick. But it's not a persistent solution as the service doesn't start automaticaly. So one have to start it manually everytime sys-net is started. The service is enabled as mentioned in the discussion. Is there a way to figure out whats going wrong and fix it?
