### ISSUE TITLE
[R4.0 RC2] Issues with installing KDE in dom0

### ISSUE THREAD

**Issue by na--** [QubesOS/qubes-issues#3212]
#### Qubes OS version:

R4.0 RC2

#### Affected TemplateVMs: 

none (dom0 specific)

---

### Steps to reproduce the behavior:

Follow the steps in the documentation: https://www.qubes-os.org/doc/kde/

### Expected behavior:

Install KDE as a desktop environment in dom0

### Actual behavior:

The following error is shown when executing `sudo qubes-dom0-update @kde-desktop-qubes` in dom0:
```
Error: package plasma-workspace-5.10.5-3.fc25.x86_64 requires kde-settings-plasma, but none of the providers can be installed
[Errno 2] No such file or directory: '/var/lib/qubes/dom0-updates/var/lib/dnf/groups.json'
```

### General notes:

It's strange that the needed package is seemingly available. Executing `sudo qubes-dom0-update --action=search kde-settings` yields:
```

Using sys-firewall as UpdateVM to download updates for Dom0; this may take some time...
Last metadata expiration check: 0:00:37 ago on Thu Oct 26 00:59:31 2017.
========================== N/S Matched: kde-settings ===========================
kde-settings.noarch : Config files for kde
kde-settings-kdm.noarch : Configuration files for kdm
kde-settings-plasma.noarch : Configuration files for plasma
kde-settings-ksplash.noarch : Configuration files for ksplash
kde-settings-minimal.noarch : Minimal configuration files for KDE
kde-settings-pulseaudio.noarch : Enable pulseaudio support in KDE
No packages downloaded
Last metadata expiration check: 0:18:20 ago on Thu Oct 26 00:41:49 2017.
=================================================== Matched: kde-settings ====================================================
qt-settings.noarch : Configuration files for Qt
```

Generally the same error as above is shown even with the `--clean` flag and test repos enabled: `sudo qubes-dom0-update --clean --enablerepo=qubes-dom0-current-testing @kde-desktop-qubes`, though I once got a slightly different error (and could not replicate it again):
```
Error: package kde-settings-pulseaudio-2000:23-11.2.fc25.noarch requires kde-settings = 2000:23-11.2.fc25, but none of the providers can be installed
[Errno 2] No such file or directory: '/var/lib/qubes/dom0-updates/var/lib/dnf/groups.json'
```

Installing `kde-settings-plasma` before trying to install `@kde-desktop-qubes` does not help much, but the error changes to: `Error: package kde-settings-plasma-2000:23-11.2.fc25.noarch requires system-plasma-theme >= 23.0, but none of the providers can be installed`. Trying to run `sudo qubes-dom0-update system-plasma-theme` returns the most useful message yet: `Package f24-kde-theme-24.5-1.fc25.noarch is already installed, skipping.`. I think that means that there is a qubes package for fedora 24, but not for fedora 25, but I'm not sure exactly how the KDE integration is supposed to work.

---

#### Related issues:

Maybe #2968

**Comment by tasket** [comment]
List thread:
https://groups.google.com/d/msgid/qubes-users/CAKYr3zzOQyYSkA_gLZRy7LCEMEUj2thQjSCthfQddNQ6PC4-Ew%40mail.gmail.com

**Comment by zander** [comment]
Just confirming that this is still the case 2 days ago (testing repo).

You can actually boot into plasma, but most of the plasma-widgets are missing or show errors. Even the 'start menu' is just an error screen.

**Comment by rysiekpl** [comment]
Any news on this? Any way to get started with helping to fix this one?

**Comment by marmarek** [comment]
That was the easy part. Now #2968 left...
