### ISSUE TITLE
Installing windows vm help

### ISSUE THREAD

**Issue by luckypatcher00** [QubesOS/qubes-issues#3218]
#### Qubes OS version:

I am trying to install windows 7 from a USB iso file as a VM I can't locate the path of the USB to boot the image from if someone can help me in detail thanks 

#### Affected TemplateVMs: 

---

### General notes:

---

**Comment by andrewdavidwong** [comment]
Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this does not appear to be suitable for `qubes-issues`. We ask that you please send this to the `qubes-users` [mailing list](https://www.qubes-os.org/mailing-lists/) instead. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a comment explaining why. We'll be happen to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.
