### ISSUE TITLE
i3 cannot start any programs with graphical user interface

### ISSUE THREAD

**Issue by loeken** [QubesOS/qubes-issues#3223]
#### Qubes OS version:

R4.0

#### Affected TemplateVMs: 

all

---

### Steps to reproduce the behavior:

launching an application in i3 using dmenu launcher ( ctrl+d )

### Expected behavior:

Window of the application i am starting should show up

### Actual behavior:

Nothing happens

### General notes:

Installed Qubes R4, imported my old vms through the qvm-backup-restore, installed i3 i3-settings, after a reboot I was unable to launch any applications by using the shortcut ctrl+d --> no windows show up

---

**Comment by marmarek** [comment]
Try starting `qvm-start-gui --all --watch`. If that helps, it means i3 there does not handle /etc/xdg/autostart correctly.

**Comment by loeken** [comment]
when i execute this command all i see is

sys-firewall: Starting GUI
sys-net: Starting GUI
sys-firewall: Sending monitor layout
sys-net: Sending monitor layout


then just silence ( waited ~ 10 minutes ). Any suggestions on how i can fix this?

**Comment by marmarek** [comment]
That's ok. It should keep running and monitor further VM startups. You can launch it in background adding `&`.
When it's running, try to launch some application.

**Comment by loeken** [comment]
I dont know what i changed, spent a day on xfce and now i3 magically works :/

**Comment by Deedasmi** [comment]
@marmarek's solution works. You can add it directly to the bottom of your i3 config. 

`exec --no-startup-id qvm-start-gui --all --watch`

**Comment by somehibs** [comment]
When this happened to me, it was because I'd mangled the autostart line.

If you're using Qubes provided i3 config, make sure `exec --no-startup-id qubes-i3-xdg-autostart` is correct in your .config/i3/config file.
