### ISSUE TITLE
qubes-vm-recommended deb should depend on icedove | thunderbird instead of icedove for Ubuntu

### ISSUE THREAD

**Issue by qubesuser** [QubesOS/qubes-issues#3227]
#### Qubes OS version:
R4.0-rc2

#### Affected TemplateVMs: 
debian-9
ubuntu

### Steps to reproduce the behavior:
1. Try to install qubes-vm-recommended from debian-9 repo on an Ubuntu 17.10 template VM

### Expected behavior:
It installs.

### Actual behavior:
It fails because Ubuntu has no icedove package, but has thunderbird.

### General notes:
The Debian 9 packages seem to just work on Ubuntu 17.10 except for this issue, so it would be nice to fix it since it's trivial.

**Comment by unman** [comment]
There's something fundamentally wrong here. Debian packages aren't intended to be installed on Ubuntu, nor vice versa. Just dont do it. The "expected behavior" statement is just wrong.
There isn't Qubes support for 17.10 as yet.
Repurpose this bug for **that** if you must or raise a new one.
