### ISSUE TITLE
qvm-backup-restore --replace-template not working

### ISSUE THREAD

**Issue by qubesuser** [QubesOS/qubes-issues#3228]
#### Qubes OS version:
R4.0-rc2

### Steps to reproduce the behavior:
1. Try to restore a backup with --replace-template

### Expected behavior:
It replaces the template.

### Actual behavior:
It does not replace the template.

### General notes:
It seems backup.options.replace_template gets set, but there is no code that uses it.

**Comment by marmarta** [comment]
The option was removed here: https://github.com/QubesOS/qubes-core-admin-client/commit/a0d63275329683e7a9464717e8f34de398d48525#diff-bf51f4c0154541f3c5e366fbbc48a60d23ac70c635c759b173d79a789f087a29 ; currently you can use `--ignore-missing` and replace template normally (or in batch using the visual template manager).
