### ISSUE TITLE
EFI Qubes 4.0 EFI initrd made by installer does not include default keyboard layout setting (for disk encryption password)

### ISSUE THREAD

**Issue by qubesuser** [QubesOS/qubes-issues#3234]
#### Qubes OS version:
4.0-rc2

### Steps to reproduce the behavior:
1. Start Qubes installation using EFI boot
2. Set a non-US keyboard layout
3. Enable encryption with a passphrase including symbols that are typed differently in that keyboard layout
4. Complete the installation
5. Boot the system and try to decrypt the disk by typing the passphrase assuming the selected keyboard layout

### Expected behavior:
It works.

### Actual behavior:
It doesn't because the keyboard layout is set to us.

### General notes:
It seems that the initrd, at least for EFI installation, gets created with the us keyboard layout as opposed to the user-selected one.

The issue is corrected by manually recreating the initrd with dracut on the newly installed system, but the installer should be doing that.

Not sure if the issue is present for non-EFI GRUB installations.

**Comment by diffusae** [comment]
Yes, the issue is also present for non-EFI GRUB installations.

**Comment by JorgenRask** [comment]
In start of installation I changed keyboard layout (to danish keyboard). I noticed that during the installation process the keyboard changed back to US. I'm pretty sure the keyboard layout was still DK at step 788 of 1019, but at step 793 of 1019 the keyboard was changed to US. So I had to be careful when creating my default user and set the password - I viewed the password in cleartext and could see that some of the special characters in the password were actually typed with US keyboard).

**Comment by marmarek** [comment]
@JorgenRask your issue looks rather like #3352.

**Comment by JorgenRask** [comment]
@marmarek could be :-) I just wanted to add the observation that I could see the keyboard layout change (in the upper right corner of the screen) during the installation process and was not just happening when you tried to create a user. It looks like you have reproduced the problem, so I will not add any more to this ;-)

**Comment by hyperfekt** [comment]
I do not believe this issue is a duplicate, given that after a kernel update and with it a regeneration of initramfs the password is accepted as given in the selected layout.
If the password was incorrectly entered into the installer instead, a kernel update should not have this effect.

**Comment by marmarek** [comment]
According to https://openqa.qubes-os.org/tests/118 it is still an issue.
