### ISSUE TITLE
Manual PCI rescan required after using qvm-pci to attach PCI devices to HVMs

### ISSUE THREAD

**Issue by qubesuser** [QubesOS/qubes-issues#3245]
#### Qubes OS version:
R4.0-rc2

### Steps to reproduce the behavior:
1. Use qvm-pci to attach a PCI devices to a running HVM VM
2. Run sudo lspci in the VM
3. Run echo 1|sudo tee /sys/bus/pci/rescan in the VM
4. Run sudo lspci in the VM

### Expected behavior:
The PCI device is visible immediately after attaching with qvm-pci

### Actual behavior:
The PCI device is only visible after rescanning the PCI bus in the VM.

### General notes:
It looks like the Qemu machine model we are using might not support PCI hotplugging.

One option is to switch to one that does if possible (I guess q35 does?), and the other option is to just use qrexec to trigger a PCI rescan on the guest operating system.

**Comment by marmarek** [comment]
Does it work at all if VM initially had no PCI device at all?

**Comment by qubesuser** [comment]
I think it did for one device, while trying it for another device just triggered #3233 upon PCI rescan (which I now discovered is not related to using two devices apparently).

**Comment by iamahuman** [comment]
Caused by: #1673

QEMU notifies newly `device_add`-ed PCI devices to the VM via ACPI hotplugging mechanism, which is disabled in dom0 kernel. Maybe use in-VM kernel instead, or compile another kernel specifically for VMs -- see #5212.
