### ISSUE TITLE
qvm-sync-appmenus doesn't respect OnlyShowIn and NotShowIn resulting in duplicate entries on Ubuntu

### ISSUE THREAD

**Issue by qubesuser** [QubesOS/qubes-issues#3246]
#### Qubes OS version:
R4.0-rc2

#### Affected TemplateVMs: 
ubuntu 17.10

### Steps to reproduce the behavior:
1. Install an Ubuntu template VM
2. Sync appmenus

### Expected behavior:
There is only one "Files" appmenu.

### Actual behavior:
There are two "Files" appmenus.

### General notes:
Ubuntu has org.gnome.Nautilus.desktop with "OnlyShowIn=Unity;GNOME;" and nautilus.desktop with "NotShowIn=Unity;GNOME;"

Thus, with a proper implementation only one can be shown regardless of what "desktop name" the implementation considers itself to be, while Qubes seems to just ignore those directives resulting in duplication.

I think Qubes might also want to pretend to be "GNOME", although this is not totally clear.

**Comment by marmarek** [comment]
This is semi-intentional - to allow using any application, regardless of its native desktop environment. While this particular application provide both desktop files, there are a lot of them that provide only one (for example with `OnlyShowIn=KDE;`, or `OnlyShowIn=GNOME;`). For example nautilus, or gnome contacts, or baobab in Fedora are such cases.
We may add a tooltip in that window to help distinguishing such corner cases - for example desktop file name.

**Comment by qubesuser** [comment]
I see.

I guess the solution could then be to deduplicate desktop entries that have the same Name= and same Exec= line (after removing %f, %F, %u, %U from the exec line and canonicalizing whitespace).

**Comment by marmarek** [comment]
I guess those do have different Exec= lines... Or at least one have `DBusActivable=true` (which also result in something different being executed in practice)

**Comment by qubesuser** [comment]
Yes, one has %U at the end, but the spec says it should be removed when not opening any files, and thus the Exec= lines are logically equivalent.

If there is already logic to avoid duplicate exec lines, then it looks like it only needs to be updated to do s/\b%[fFuU]\b//g; s/\s+/ /; before comparing (or even better parse it properly with a shell parser, if that's the correct way).

**Comment by marmarta** [comment]
There's a PR waiting for 4.1 that will add more info to application list in VM settings ( https://github.com/QubesOS/qubes-manager/pull/181 ) - I think this is as fr as we should go with this, as more aggresive deduplication may cause losing .desktop entries the user would not rather lose (as it was said above, even different `DBusActivable=true` can cause the result to be different). Closing.
