### ISSUE TITLE
default_fw_netvm results in all "provides_network" VMs bypassing firewall by default

### ISSUE THREAD

**Issue by qubesuser** [QubesOS/qubes-issues#3247]
#### Qubes OS version:
R4.0-rc2

### Steps to reproduce the behavior:
1. Create a VM with provides_network=true

### Expected behavior:
The (default) netvm for the VM should be sys-firewall.

### Actual behavior:
The (default) netvm for the VM is sys-net.

### General notes:
Only sys-firewall should be connected to sys-net (in normal configurations), so it doesn't make sense to attach any VM by default to sys-net. Whether a VM is a proxy VM shouldn't really impact that.

I'd recommend completely removing the default_fw_netvm preference and just setting the sys-firewall netvm explicitly to sys-net when sys-firewall is created.

### Workaround
Set sys-firewall netvm to sys-net explicitly and then set default_fw_netvm to sys-firewall

**Comment by marmarek** [comment]
> I'd recommend completely removing the default_fw_netvm preference and just setting the sys-firewall netvm explicitly to sys-net when sys-firewall is created.

Makes sense

**Comment by marmarek** [comment]
BTW `default_fw_netvm` caused some problems already: #3190
