### ISSUE TITLE
restarting gui-daemon results in broken audio

### ISSUE THREAD

**Issue by qubesuser** [QubesOS/qubes-issues#3249]
#### Qubes OS version:
R4.0-rc2

### Steps to reproduce the behavior:
1. Start some applications in VMs
2. Log off
3. Log in

### Expected behavior:
All applications reappear and audio works in VMs since GUI daemons are restarted.

### Actual behavior:
GUI daemons don't restart automatically.

If restarted manually, by deleting /run/qubes/guid-* and running qvm-start-gui --all, then audio doesn't work since pacat-simple-vchan seems to hang before connecting to PulseAudio.

**Comment by marmarek** [comment]
> If restarted manually, by deleting /run/qubes/guid-* and running qvm-start-gui --all, then audio doesn't work since pacat-simple-vchan seems to hang before connecting to PulseAudio.

This issue is present also on 3.2. Can be workarounded by reloading `module-vchan-sink` in the VM:
```
pacat unload-module module-vchan-sink
pacat load-module module-vchan-sink
```

> GUI daemons don't restart automatically.

This is a duplicate of #3147

**Comment by qubesuser** [comment]
Indeed, reloading module-vchan-sink now seems to work for me.

It's a bit strange because I tried doing exactly that before filing the bug and it didn't seem to work, but maybe I had the system in a somewhat strange state as I was trying a bunch of things (perhaps pacat-simple-vchan not running or no audio devices)

**Comment by tuxether** [comment]
Is there a workaround/fix for Qubes R4?

**Comment by marmarek** [comment]
This is fixed in https://github.com/QubesOS/qubes-gui-agent-linux/pull/89
