### ISSUE TITLE
Installing with usb vm in net-vm fails with 4.0-rc2

### ISSUE THREAD

**Issue by o-** [QubesOS/qubes-issues#3254]
#### Qubes OS version:

4.0-rc2

#### Affected TemplateVMs: 

---

### Steps to reproduce the behavior:

Install Qubes. Select 'use sys-net as usb vm'

### Expected behavior:

Qubes installs

minor point: on a failure, I would expect the installer to handle it more gracefully. When it failed I was not sure if qubes was still fully configured. Even though I managed to resolve the problem I eventually reinstalled, since I fearde the installed did not finish properly. Should I open an issue for this too?

### Actual behavior:

The post-install hook fails, since sys-net does not boot

Starting sys-net says `Unable to reset PCI device [...]  no FLR, PM reset or bus reset available.`

The controller is: `USB controller: Intel Corporation Sunrise Point-LP USB 3.0 xHCI Controller (rev 21)`

`no-stric-reset=TRUE` was set by the installer on that device.

### General notes:

I can't tell if this issue is hardware related, or if this combination is not supported any longer. I was reliably able to boot sys-net when that device was detached and trigger the issue when it was attached. The other devices attached to sys-net are an I219-LM ethernet controller and a 8265 Wireless card.

In my case I just restarted the installer and did not select the option anymore (letting the installer create separate usb and net vm) and then everything worked as expected.

Since I found a workaround I can't provide much more info. I still wanted to open this issue in case other are affected by the same problem, or the configuration is not supported anymore (in which case it should be removed from the installer screen).

---

**Comment by eduncan911** [comment]
I too am constantly having this issue.

R4.0.1-rc2
Thinkpad P1 (aka X1 Extreme)

I only had sys-usb creation checked off; but, I did not select the option to attach networking components to sys-usb - like the OP mentions.

I've been chasing down the Nvidia/Hybrid approach, thinking it was the GPU since I thought that was the only difference between the P1 and the other X1 Yoga and X1 Tablet I have running Qubes.  But after reading this issue, I'm thinking it is a USB device.  Unfortunately, I haven't been able to get a stable Qubes OS loaded on it yet to investigate the post-install log.

![img_20190101_205305](https://user-images.githubusercontent.com/104980/50731318-a459e280-112f-11e9-8d52-86c87d168edf.jpg)

**Comment by o-** [comment]
@andrewdavidwong oh, that's a very old issue. Honestly I am not sure anymore. I think the issue was that a postinstall hook failed, but qubes still just booted the system. And I was not sure if just starting the net-vm failed, or if that error lead to the installer terminating early and other necessary tasks would not have been run. Basically I was not sure if the error was "Your system is successfully installed, but I failed to start sys-net", or if it was "in the middle of running the installer I encountered an error and aborted the rest of the tasks".

**Comment by andrewdavidwong** [comment]
> oh, that's a very old issue. Honestly I am not sure anymore. I think the issue was that a postinstall hook failed, but qubes still just booted the system. And I was not sure if just starting the net-vm failed, or if that error lead to the installer terminating early and other necessary tasks would not have been run. Basically I was not sure if the error was "Your system is successfully installed, but I failed to start sys-net", or if it was "in the middle of running the installer I encountered an error and aborted the rest of the tasks".

Ok. I think that would be a worth a separate issue (UX installer enhancement), if you still remember enough to file one.
