### ISSUE TITLE
Cannot change revisions_to_keep for a storage pool

### ISSUE THREAD

**Issue by na--** [QubesOS/qubes-issues#3256]
#### Qubes OS version:

R4.0 RC2

#### Affected TemplateVMs: 

none (dom0 issue)

---

### Steps to reproduce the behavior:

Try to change the number of `revisions_to_keep` for a storage pool with the `qvm-pool` command

### Expected behavior:

That there is a relatively easy way to modify (or at least increase) the number of revisions kept

### Actual behavior:

None such exists - probably editing `qubes.xml` directly will do the job, but not sure if that won't mess something up.

### General notes:

I am not sure that it's a good idea to mess with storage pool options after a pool is created, too many things can go wrong. The exception I think is increasing `revisions_to_keep`, even decreasing it can be problematic if not handled correctly. So handling such a special case in `qvm-pool` might not be the best way to proceed...
A workaround that I think could be used right now looks like this:
- create a new storage pool that is identical to the last with the last (same folder/volume group&thin pool), but with different  `revisions_to_keep` value
- clone vms from the old pool to the new one (with a slightly changed name)
- delete the original vms
- clone the new vms in the same pool with the origin names
- delete the vms with the slightly changed names

It's a bit of a mess, especially when cloning templates :) Is there an easier way to accomplish this?

---

#### Related issues:

None that I could find

**Comment by marmarek** [comment]
I'm already working on this. Better not change this (or any other) value manually in qubes.xml, because driver may want to apply some constrains, or do some conversion when changing it.

**Comment by tlaurion** [comment]
@marmarek is it supposed to work? In 4.0 rc4, `qvm-pool -i lvm -o revisions_to_keep=3` doesn't have any effect.

**Comment by marmarek** [comment]
`qvm-pool -i` just display information, it isn't supposed to change anything. This ticket is about adding an option for that... For now the backend side (Admin API) is already done.

**Comment by tlaurion** [comment]
I tried to change manually qubes.xml with same result. Any manual operations to make the backend take it in consideration atm? I'm looking into that feature to make some changes to dom0 to update [Qubes Network Server](https://github.com/QubesOS/qubes-issues/issues/3512) internals.

**Comment by rustybird** [comment]
> I tried to change manually qubes.xml (revisions_to_keep=3) with same result.
> 
> Any manual operations to make the backend take it in consideration atm?

Setting `revisions_to_keep` in the individual `<volume>` elements (not just once in `<pool>`) looks like it would work for the `lvm_thin` driver. But I haven't tried it.

**Comment by marmarek** [comment]
You can also use Admin API directly, until proper UI got implemented:
```
echo -n 2 | qubesd-query dom0 admin.vm.volume.Set.revisions_to_keep <VMNAME> <VOLUME>
```
