### ISSUE TITLE
Feature Suggestion: UI Changes For The Domain Tray 

### ISSUE THREAD

**Issue by tharrisone** [QubesOS/qubes-issues#3259]
Qubes OS version:
4.0RC2

Affected TemplateVMs: 
All

General notes:
I have by accident shut down sys-net/sys-firewall/etc because there is no visible indications that you will shut down the desired hvm because the font color and icons are all the same. If there was some sort of ui scroll down and highlighting along with the icons and font text being the same color as the domains then those mistakes would not be easy to make.

**Comment by marmarek** [comment]
You mean it isn't obvious which VM you would shutdown when clicking "Shutdown" option in submenu? 

So, you suggest something like groups here:
![http://www.bogotobogo.com/images/Android/Android7/SmplExpandable.png]
?

I think technically it could be tricky. But we may try. Or some other way to improve readability. Maybe leave selected VM highlighted?

**Comment by tharrisone** [comment]
Yes, something like that or similar would work. When I hover over the domains tray and pick the one I want to shutdown, many times i shutdown the domain directly above it because its not highlighted. Leaving the selected vm highlighted would work as well.

**Comment by qubesuser** [comment]
Hmm, on my system the VM menu entry is highlighted with the standard blue background and white text indicating selection (the same one used for the menu item under the curser) whenever the submenu with "Preferences" and "Shutdown" is open.

I might have a non-default XFCE/GTK theme though (mine is the "Clearlooks" one).

**Comment by marmarta** [comment]
That depends on the selected style (System Tools -> Appearance). Our default (Clearlooks) handles correctly highlighting, backgrounds and so on. Some styles (like Xfce-basic or Xfce) don't, but the problem is on their side (as can be seen with other apps, even xfce's own power manager and volume manager).
