### ISSUE TITLE
Memory balancing stops for some VMs

### ISSUE THREAD

**Issue by tasket** [QubesOS/qubes-issues#3265]
#### Qubes OS version:

R4.0rc2

#### Affected TemplateVMs: 

All

---

### Steps to reproduce the behavior:

Run memory-intensive programs like Firefox in more than one appVM.

### Expected behavior:

VMs re-adjust memory size so neither one is starved of RAM.

### Actual behavior:

Eventually one of the VMs will stop acquiring RAM, even when it is experiencing high demand when the other VMs are no longer running. Not uncommon to see a browsing VM stuck at 700-1100MB and swapping heavily even when other appVMs have exited and only other VMs are sys-net and VPN/sys-firewall.

VM sessions can become unusable due to this problem, and re-starting them is unlikely to work right away because issue #3221 seems related.

### General notes:

Total system memory is 8GB.

---

**Comment by 0spinboson** [comment]
This appears to be quite extensive -- I'm also seeing VMs failing to claim more ram than assigned at boot. New with r4rc2.

**Comment by marmarek** [comment]
I *guess* what is going on there:
When starting a VM, qubesd connects to qmemman to request memory for it. Then, it blocks qmemman until the VM is actually started (to not take its memory out in the meantime). This part "until the VM is actually started" is done by closing the connection to qmemman. If some other process is started there in the meantime, it may inherit the connection and keep it open (potentially forever), blocking qmemman. Solution: set this connection to be not inheritable, or at least O_CLOEXEC.
cc @woju

**Comment by marmarek** [comment]
Hmm, my guess was wrong, at least partially. There [is O_CLOEXEC already](https://github.com/QubesOS/qubes-core-admin/blob/master/qubes/qmemman/client.py#L30).

**Comment by na--** [comment]
I'm hitting this one regularly, though it follows Murphy's law very well - it happens when it does the most damage, but I can't reliably reproduce it on purpose... Running `sudo systemctl restart qubes-qmemman.service` in dom0 temporarily fixes the issue most of the time, but that only works when I notice that the VM I am using is about to run out of RAM.

**Comment by marmarek** [comment]
Can you check logs (from `journalctl`) of qmemman just before restarting it? See if there is anything about the mishandled VM (you can get its id from `xl list`).

**Comment by tasket** [comment]
I have a VM (id=28) right now stuck at 614MB. The log shows dozens of "qmemman.daemon.algo[7972] ... balance_when_enough_memory..."

Prior to that:
```
total_mem_pref=3917275750.4, total_available_memory=861753952.6000001)
Nov 14 17:38:24 dom0 qmemman.daemon.algo[7972]: balance_when_enough_memory(xen_free_memory=5624909, total_mem_pref=3917275750.4, total_available_memory=861753952.6000001)
Nov 14 17:38:25 dom0 qmemman.daemon.algo[7972]: balance_when_enough_memory(xen_free_memory=170938609, total_mem_pref=3917275750.4, total_available_memory=1027067652.6000001)
Nov 14 17:38:25 dom0 qmemman.systemstate[7972]: stat: dom '28' act=643936256 pref=801675264.0
Nov 14 17:38:25 dom0 qmemman.systemstate[7972]: stat: dom '30' act=1540231737 pref=1260465356.8
Nov 14 17:38:25 dom0 qmemman.systemstate[7972]: stat: dom '0' act=2343833722 pref=1900864844.8
Nov 14 17:38:25 dom0 qmemman.systemstate[7972]: stat: dom '7' act=361388683 pref=286000000
Nov 14 17:38:25 dom0 qmemman.systemstate[7972]: stat: dom '31' act=699744256 pref=482229862.40000004
Nov 14 17:38:25 dom0 qmemman.systemstate[7972]: stat: dom '11' act=527950652 pref=469945548.8
Nov 14 17:38:25 dom0 qmemman.systemstate[7972]: stat: xenfree=223367409 memset_reqs=[('7', 360625143), ('30', 1589354897), ('0', 2396851951), ('11', 592567066)]
Nov 14 17:38:25 dom0 qmemman.systemstate[7972]: mem-set domain 7 to 360625143
Nov 14 17:38:25 dom0 qmemman.systemstate[7972]: mem-set domain 30 to 1589354897
Nov 14 17:38:25 dom0 qmemman.systemstate[7972]: mem-set domain 0 to 2396851951
Nov 14 17:38:25 dom0 qmemman.systemstate[7972]: mem-set domain 11 to 592567066
Nov 14 17:38:25 dom0 qmemman.daemon.algo[7972]: balance_when_enough_memory(xen_free_memory=368868182, total_mem_pref=3917275750.4, total_available_memory=1390991488.6000001)
Nov 14 17:38:25 dom0 qmemman.systemstate[7972]: stat: dom '28' act=643936256 pref=801675264.0
Nov 14 17:38:25 dom0 qmemman.systemstate[7972]: stat: dom '30' act=1589354897 pref=1260465356.8
Nov 14 17:38:25 dom0 qmemman.systemstate[7972]: stat: dom '0' act=2396851951 pref=1900864844.8
Nov 14 17:38:25 dom0 qmemman.systemstate[7972]: stat: dom '7' act=360625143 pref=286000000
Nov 14 17:38:25 dom0 qmemman.systemstate[7972]: stat: dom '31' act=699744256 pref=482229862.40000004
Nov 14 17:38:25 dom0 qmemman.systemstate[7972]: stat: dom '11' act=592567066 pref=469945548.8
Nov 14 17:38:25 dom0 qmemman.systemstate[7972]: stat: xenfree=421296982 memset_reqs=[('30', 1706337898), ('7', 387168624), ('0', 2573270028), ('11', 636182419)]
Nov 14 17:38:25 dom0 qmemman.systemstate[7972]: mem-set domain 30 to 1706337898
Nov 14 17:38:25 dom0 qmemman.systemstate[7972]: mem-set domain 7 to 387168624
Nov 14 17:38:25 dom0 qmemman.systemstate[7972]: mem-set domain 0 to 2573270028
Nov 14 17:38:25 dom0 qmemman.systemstate[7972]: mem-set domain 11 to 636182419
```

**Comment by tasket** [comment]
I saved another log from 'stuck' session today, if that is of interest.

**Comment by marmarek** [comment]
Something is clearly wrong with the algorithm deciding to which VM distribute available memory: it divide it across VMs already having more than requested, but not for those with actual need.

**Comment by marmarek** [comment]
Check if restarting `qubes-qmemman.service` helps.

**Comment by dakka2** [comment]
restarting qubes-qmemman.service doesn't seem to help for me.
