### ISSUE TITLE
USB devices shown multiple times in devices popup menu

### ISSUE THREAD

**Issue by qubesuser** [QubesOS/qubes-issues#3266]
#### Qubes OS version:
4.0-rc2

### Steps to reproduce the behavior:
Not sure what exactly triggers it.

### Expected behavior:
USB devices are shown only once in the qubes devices popup menu

### Actual behavior:
USB devices are shown multiple times in the qubes devices popup menu: the entire set of devices is repeated multiple times, as if the output of qvm-usb had been appended there multiple times.

**Comment by marmarek** [comment]
Some way to reproduce:
1. plug in two devices
2. remove both of them quickly

Result: one of them stays in the widget. When you plug it again, it is duplicated.
