### ISSUE TITLE
VMAuth qubes-rpc policy for sudo prompts for target VM

### ISSUE THREAD

**Issue by tasket** [QubesOS/qubes-issues#3270]
#### Qubes OS version:

R4.0rc2

#### Affected TemplateVMs: 

all

---

### Steps to reproduce the behavior:

Configure system for sudo prompting:

https://www.qubes-os.org/doc/vm-sudo/

Then run a 'sudo' command in a guest CLI

### Expected behavior:

User gets a dom0 prompt asking only Yes/No (defaults to Yes so user can hit Enter)

### Actual behavior:

User gets a dom0 prompt for inputting the name of a target VM

### General notes:

This adds a level of potential confusion over auth prompts. There should be a way to specify in the policy whether or not user is prompted for a destination/target.

---

**Comment by marmarek** [comment]
Indeed instruction should be updated, to include
"ask,default_target=dom0" in policy.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by tasket** [comment]
On 11/02/17 12:11, Marek Marczykowski-Górecki wrote:
> Indeed instruction should be updated, to include
> "ask,default_target=dom0" in policy.
>

Would this cause a problem for R3.2, or would it ignore the extra parameter?

-- 

Chris Laprise, tasket@posteo.net
https://github.com/tasket
https://twitter.com/ttaskett
PGP: BEE2 20C5 356E 764A 73EB  4AB3 1DC4 D106 F07F 1886

**Comment by marmarek** [comment]
On Thu, Nov 02, 2017 at 04:23:17PM +0000, tasket wrote:
> On 11/02/17 12:11, Marek Marczykowski-Górecki wrote:
> > Indeed instruction should be updated, to include
> > "ask,default_target=dom0" in policy.
> >
> 
> Would this cause a problem for R3.2, or would it ignore the extra parameter?

It should work (ignore extra parameters).

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by tasket** [comment]
PR https://github.com/QubesOS/qubes-doc/pull/510

**Comment by marmarek** [comment]
Thanks @tasket !
