### ISSUE TITLE
DisposableVM are duplicated in qrexec dialog

### ISSUE THREAD

**Issue by ERFier** [QubesOS/qubes-issues#3271]
#### Qubes OS version:

R4 rc2

#### Affected TemplateVMs: 

dom-0 qrexec dialog

---

### Steps to reproduce the behavior:

open a file using `qvm-open-in-vm '$dispvm:fedora-25-qvm' something.pdf`

The qrexec-dialog pops up and gives a choice for the vm in which I want to open the file.

### Expected behavior:

I would expect to see the Disposible VMs only once as its disposible version.

### Actual behavior:

The disposable vms are shown twice. One time as the disposable version I usually want and another time as the regular AppVM that serves as a template for disposable VMs.

### General notes:

I think it's a security issue as it's very likely that someone accidentally opens a file in the underlaying AppVM instead of the supposed DispVM. The two entries only differentiate in the DispVM logo with the circle inside the lock.

---

**Comment by ERFier** [comment]
I would like to post a screenshot as it makes very clear what I mean with accidentally choose the AppVM but I cant. Are there any constrains for pictures on github?

**Comment by andrewdavidwong** [comment]
> I would like to post a screenshot as it makes very clear what I mean with accidentally choose the AppVM but I cant. Are there any constrains for pictures on github?

No, you should be able to attach files by dragging & dropping, using the selection tool, or pasting it from your clipboard. Alternatively, you can upload the screenshot to an image sharing site and post the link here.

**Comment by marmarta** [comment]
While there are still two entries for a dvm-template, they are now more clearly distinguished by one being listed as just the template name, and the other as Disposable VM (<template name>), which I think is the better solution, as sometimes one might want to use one, and sometimes the other. Closing.
