### ISSUE TITLE
mic is attachable but not removable

### ISSUE THREAD

**Issue by ERFier** [QubesOS/qubes-issues#3275]
#### Qubes OS version:

R4 rc2

#### Affected TemplateVMs: 

Dom0

---

### Steps to reproduce the behavior:

I don't know exactly but I think you should bring the device widget to a non working state e.g. restarting usb-vm. I will investigate this further.

### Expected behavior:

Microphone can be attached and detached to vms at will.

### Actual behavior:

I was able to attach the mic to a DispVM and wasn't able to remove it. The DeviceManager Widget didn't showed that the mic is connected but I was able to use it. I tried to remove the mic with a second click in DeviceManager but the mic was not removed.

### General notes:

I haven't found documentation about how to attach and remove the mic using the commandline tools. I think it should be documented somewhere as its neither a usb nor pci device.

---

#### Related issues:

#3266
#3215

**Comment by na--** [comment]
I think that the command-line way to manage the mic is `qvm-device mic`. Use `qvm-device mic attach <vm-name> dom0:mic` to attach it and `qvm-device mic detach <vm-name> dom0:mic` to detach it. 
And just as a confirmation, I have the same issues (and more) with the system tray device widget.
