### ISSUE TITLE
Archlinux TemplateVM: Dependency of zenity (as part of qubes-vm-gui) changed into a lot more packages

### ISSUE THREAD

**Issue by schnurentwickler** [QubesOS/qubes-issues#3279]
#### Qubes OS version:

`R3.2`

#### Affected TemplateVMs:

archlinux

---

### Steps to reproduce the behavior:

newest upgrade (pacman -Suy)

### Expected behavior:

For a small VM template, only the basics of needed packages should be installed for a working and small "sys-net".

### Actual behavior:

The package qubes-vm-gui depends on zenity which now depends on webkit2gtk with the dependencies: gst-plugins-bad and their full load of decoders. (over 150MB of it!) Unnecessary for a sys-net VM.

### General notes:

Is it possible to avoid the dependency of zenity/webkit2gtk for qubes-vm-gui?

**Comment by schnurentwickler** [comment]
This probably also affects archlinux templates in Qubes 4.0, if qubes-vm-gui also depends on zenity/webkit2gtk there.

**Comment by na--** [comment]
I'm not sure if `zenity` is actually needed by the `qubes-vm-gui` package, but it seems used by [some of the services](https://github.com/QubesOS/qubes-core-agent-linux/search?utf8=%E2%9C%93&q=zenity&type=) in `qubes-vm-core`. I think that most things will still work if you force uninstall it from the template, but I would not want it removed as a package dependency at this point just to save some space.

It seems that the correct solution if to compile zenity with `--disable-webkitgtk` in the [PKGBUILD](https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/zenity), like they do for the [fedora package](https://apps.fedoraproject.org/packages/zenity/sources/spec/). There seems to be a [dead issue](https://bugs.archlinux.org/task/50548) for this in the Archlinux bugtracker, so I doubt it will happen in the original package anytime soon.

For the moment I think your best bet is to build your own `zenity` package. Copy the [original `PKGBUILD`](https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/zenity), add `--disable-webkitgtk` to `./configure`, add [provices](https://wiki.archlinux.org/index.php/PKGBUILD#provides) and [conflicts](https://wiki.archlinux.org/index.php/PKGBUILD#conflicts) relations to `zenity`, run `makepkg` and install your package. This should be [fairly low-maintenance](https://git.archlinux.org/svntogit/packages.git/log/trunk/PKGBUILD?h=packages/zenity) unless gnome decide to suddenly develop a lot of new zenity features :)

**Comment by ptitdoc** [comment]
Or maybe it is possible to make it optional ? (meaning the package is built with `webkit2gtk` as a makedependency but not necessarily installed)

**Comment by schnurentwickler** [comment]
zenity probably needs to stay as a dependency of qubes-vm-gui. (because zenity in fedora stays webkitfree)
And webkit2gtk will not be removed as dependency of zenity in archlinux: https://bugs.archlinux.org/task/50548
So, maybe someone will launch a zenity-webkitfree version in archlinux or we need to build it ourselves.
Not a bug of qubes, but a circumstance with qubes-vm-gui. Closed.
