### ISSUE TITLE
Cannot create debian based standalone vm

### ISSUE THREAD

**Issue by loeken** [QubesOS/qubes-issues#3282]
#### Qubes OS version:

Qubes release 4.0 (R4.0)

#### Affected TemplateVMs: 

Standalone VM

---

### Steps to reproduce the behavior:

qvm-create pxe --class StandaloneVM --label orange
qvm-start pxe --cdrom=/path/to/debian-9.2.1-amd64-netinstall.iso

### Expected behavior:

I expect a new Window for the HVM where i can start installing from the cdrom

### Actual behavior:

The Window appears, i see 4 lines
SeaBIOS (version ...... )
Machine UUID 732.....
Booting from ROM...
Probing EDD(edd=off to disable)... ok

and then just nothing else

### General notes:

updated dom0 today so all should be up to date

---

**Comment by marmarek** [comment]
Set kernel to empty value (`qvm-prefs pxe kernel ''`), to use bootloader from the ISO.

**Comment by loeken** [comment]
thanks that did the trick for standalone vms that are not based on template. I tried to select "Standalone VM based on a template" and then select "debian-8" inside the "Create new Qubes" Cube Gui Window.
Based on qvm-ls it didnt set a template:
pxe Halted StandaloneVM orange - sys-net
Is this supposed to be like this? Does it use qvm-clone to clone the template(debian-8)?

**Comment by marmarek** [comment]
> Is this supposed to be like this? Does it use qvm-clone to clone the template(debian-8)?

Yes. StandaloneVM is detached from the template.

> All I get when trying to start that vm is a:
> 
> Cannot execute qrexec-daemon!

Try enabling debug mode (in VM settings) and see what happens.

**Comment by tasket** [comment]
@marmarek Any tips for getting the netinst installer to see the network?

**Comment by unman** [comment]
@loeken Have you been able to create a standaloneVM and can you close this?
I'd suggest you raise the issue on the users mailing list if you still have problems.

**Comment by loeken** [comment]
Yes all good
