### ISSUE TITLE
qvm-prefs can't set netvm to none.

### ISSUE THREAD

**Issue by Selenog** [QubesOS/qubes-issues#3287]
#### Qubes OS version:

'R4.0-rc2'

#### Affected TemplateVMs: 

Any

---

### Steps to reproduce the behavior:

qvm-prefs --set sys-firewall netvm none

### Expected behavior:

Configure sys-firewall (or any other VM) to have no netvm.

### Actual behavior:

qubesadmin.exc.QubesValueError: VM name cannot be 'none' nor 'default'

### General notes:

Seems like the changes related to #3002 made it impossible to set the netvm property to "none". Maybe add a --clear option or --none to qvm-prefs.

"qvm-prefs --default sys-firewall netvm" sets it to it's default which isn't always none

---

#### Related issues:

#3002

**Comment by marmarek** [comment]
Use empty string (`qvm-prefs sys-firewall netvm ""`). See `man qvm-prefs` for details.
