### ISSUE TITLE
Firewall rules GUI disables itself

### ISSUE THREAD

**Issue by mirrorway** [QubesOS/qubes-issues#3289]
#### Affected TemplateVMs: 

---

### Steps to reproduce the behavior:

1. Create a Fedora VM with netvm := sys-firewall.
2. Open VM settings, click "Limit outgoing internet connections to..."
3. Close VM settings.
4. Re-open VM settings.

### Expected behavior:

Can add/modify rules a la Qubes R3.2

### Actual behavior:

Firewall setting is grayed out with
"Firewall has been modified manually - please use qvm-firewall for any further configuration."

### Other comments

You can make the firewall tab visible again by using qvm-firewall to delete all but the accept-all rule.

**Comment by mannp** [comment]
Hi @marmarek which repo would this change be in, as I have the same bug and am up to date with the testing repo and still have the bug.

Is it only in unstable?

**Comment by marmarek** [comment]
It's not built yet, you'll notification here when it's done.

**Comment by mannp** [comment]
ok cool thanks.
