### ISSUE TITLE
/usr/lib/qubes/udev-block-add-change calling xenstore-ls is way too slow

### ISSUE THREAD

**Issue by qubesuser** [QubesOS/qubes-issues#3291]
#### Qubes OS version:
R4.0-rc2

### Steps to reproduce the behavior:
1. Start 20-50 qubes VMs
2. Keep "top" running
3. Run "sudo udevadm trigger" (or create a new VM with qvm-create, for a lesser effect)

### Expected behavior:
xenstored and xenstore-ls do not appear in "top"

### Actual behavior:
xenstored is at 100% time for several seconds in qvm-create and potentially minutes in udevadm trigger with multiple xenstore-ls running and taking a lot of CPU time.

### General notes:
xenstore-ls is just too inefficient to call from /usr/lib/qubes/udev-block-add-change

It needs to be replaced with a much faster way to tell if a device is attached, or an algorithm change that doesn't require to determine whether devices are attached at this point.

Proposed optimization at QubesOS/qubes-linux-utils#24 . While that pull request should make it much faster, it still requires an O(n) scan, making "udevadm trigger" O(n^2), which is not good.

**Comment by marmarek** [comment]
PR proposed by @qubesuser makes it good enough.
