### ISSUE TITLE
AEM - Make Anti Evil Maid resistant against shoulder surfing and video surveillance

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#3298]
### Make Anti Evil Maid resistant against shoulder surfing and video surveillance

**Project**: Observing the user during early boot should not be sufficient to defeat the protection offered by Anti Evil Maid.

**Brief explanation**:

1. Implement optional support for time-based one-time-password seed secrets. Instead of verifying a static text or picture (which the attacker can record and replay later on a compromised system), the user would verify an ephemeral six-digit code displayed on another device, e.g. a smartphone running any Google Authenticator compatible code generator app.

2. Implement optional support for storing a passphrase-encrypted LUKS disk decryption key on a secondary AEM device. The attacker would then have to seize this device in order to decrypt the user's data; just recording the passphrase as it is entered would no longer be enough.

**Expected results**: AEM package updates implementing both features, with fallback support in case the user does not have their smartphone or secondary AEM device at hand. Good UX and documentation for enrolling or upgrading users.

**Knowledge prerequisite**:

- Bash scripting
- The AEM threat model
- GRUB2, dracut, systemd, LUKS

**Mentor**: [Rusty Bird](mailto:rustybird@openmailbox.org) (@rustybird)

----

Not written by me. Copying this in here so comments can be left.
Source - Qubes Google Sumer of Code (GSoC) page:
https://www.qubes-os.org/gsoc/

**Comment by adrelanos** [comment]
keywords: TPM, TOTP, HOTP

Leaving some stuff here that may be helpful.

* Anti Evil Maid 2 Turbo Edition - https://mjg59.dreamwidth.org/35742.html
* https://github.com/mjg59/tpmtotp
* https://www.privacyidea.org

**Comment by rustybird** [comment]
That's essentially PR https://github.com/QubesOS/qubes-antievilmaid/pull/20, so the `Far in the future` milestone might be a bit too pessimistic - fingers crossed. ;)

**Comment by andrewdavidwong** [comment]
> That's essentially PR QubesOS/qubes-antievilmaid#20, so the Far in the future milestone might be a bit too pessimistic - fingers crossed. ;)

Ah, thanks. Based on [this comment](https://github.com/QubesOS/qubes-antievilmaid/pull/20#issuecomment-342826839), it sounds like the feature would be in 4.1 at the earliest. Changing milestone.

**Comment by adrelanos** [comment]
This has been implemented in https://github.com/QubesOS/qubes-antievilmaid/pull/20 just this ticket not closed yet, right? @rustybird

**Comment by rustybird** [comment]
Right!
