### ISSUE TITLE
Cannot update Firefox to the latest version

### ISSUE THREAD

**Issue by Adamo1618** [QubesOS/qubes-issues#3300]
#### Qubes OS version:

R3.2

#### Affected TemplateVMs: 

fedora-23, fedora-26

---

### Steps to reproduce the behavior:

Install fresh Qubes R3.2, update all templates from GUI.

[user@fedora-26 ~]$ firefox -v
Mozilla Firefox 50.1.0
[user@fedora-26 ~]$ sudo dnf update firefox
Last metadata expiration check: 3:08:49 ago on Thu Nov  9 17:53:08 2017.
Dependencies resolved.
Nothing to do.
Sending application list and icons to dom0
^CTerminated.
[user@fedora-26 ~]$ sudo dnf upgrade firefox
Last metadata expiration check: 3:08:59 ago on Thu Nov  9 17:53:08 2017.
Dependencies resolved.
Nothing to do.
Sending application list and icons to dom0

### Expected behavior:

Update Firefox to the latest version, 56.0.2

### Actual behavior:

Outputs
"
Last metadata expiration check: 3:08:59 ago on Thu Nov  9 17:53:08 2017.
Dependencies resolved.
Nothing to do.
Sending application list and icons to dom0
"

### General notes:

This could be solved by downloading the .tar.bz2 directly but then there is no gpg signature check. Also the program needs to be updated via the same method every time an update is released. I have tried to enable the current-testing and security-testing repos, no effect. I have tried replacing dnf with yum. I have tried the commands
dnf --refresh upgrade
dnf clean metadata

It feels like I'm missing something obvious.

---

**Comment by andrewdavidwong** [comment]
Is this just because the desired version of Firefox isn't available in the Fedora repos (yet)?

**Comment by 3n7r0p1** [comment]
> [user@fedora-26 ~]$ firefox -v
Mozilla Firefox 50.1.0

Do you have multiple firefox installations? Check `which firefox`
Check version in your repos: `dnf list firefox`

> Update Firefox to the latest version, 56.0.2

See Fedora repository versions here: https://apps.fedoraproject.org/packages/firefox

> This could be solved by downloading the .tar.bz2 directly but then there is no gpg signature check. Also the program needs to be updated via the same method every time an update is released.

There are **signed checksums** here: https://ftp.mozilla.org/pub/firefox/releases/56.0.2/
You can update with the internal firefox updater.

I have latest Firefox on Fedora-25 template. Did you upgrade to 26? Missing updates repo?

**Comment by Adamo1618** [comment]
@andrewdavidwong
I considered it but Fedora seems so keen on being up to date and Firefox 50 was released a year ago.

**Comment by Adamo1618** [comment]
@3n7r0p1
> I have latest Firefox on Fedora-25 template. Did you upgrade to 26? Missing updates repo?
This was the problem. Thank you both, going with fedora 25 solved everything. This issue can be closed.
