### ISSUE TITLE
qvm-clone ProxyVM with '_' char in name produces menu & VM Manager error

### ISSUE THREAD

**Issue by qubeling** [QubesOS/qubes-issues#3301]
#### Qubes OS version:
Qubes release 3.2 (R3.2)

#### Affected TemplateVMs: 
ProxyVM built on debian-8 TemplateVM

---

### Steps to reproduce the behavior:
1. Create ProxyVM using debian-8 TemplateVM
2. Open dom0 terminal, use qvm-clone on new ProxyVM
3. Give clone a name with illegal(?) '_' character, (ie vpn_1)
5. Attempt removal

### Expected behavior:
ProxyVM deletes, removing the Applications menu shortcut with it.

### Actual behavior:
ProxyVM persists in Applications menu; is not listed in VM Manager, cannot be removed from command-line (A VM with the name 'vpn_1' does not exist in the system error message) as it is quite obviously already gone.

Trying to open programs in the stuck ProxyVM predictably does nothing.

### General notes:
Was cloning one of my VPN ProxyVMs and in my haste accidentally produced an underscore instead of hyphen. After experiencing related bug below (1), I removed the entire ProxyVM in order to start the cloning again. However post-removal it is still visible in the applications menu, even though it is not present either in qvm or in the GUI VM Manager. Minor, but incredibly annoying.

Could be mitigated entirely by adding a block of the underscore in qvm-clone as it does block it in GUI renaming.

---

#### Related issues:
(1)  Went into VM Manager to rename, would not allow me to make a modification. The field was activated as normal, though trying to backspace did not yield results.

**Comment by andrewdavidwong** [comment]
Related: #2422

**Comment by andrewdavidwong** [comment]
It looks like this was fixed but never closed.
