### ISSUE TITLE
qvm-backup-restore won't verify data when VMs already exist in system

### ISSUE THREAD

**Issue by tasket** [QubesOS/qubes-issues#3303]
#### Qubes OS version:

R4.0-rc2

---

### Steps to reproduce the behavior:

qvm-backup-restore --verify-only -d backups /mnt/path-to-file

### Expected behavior:

The backup file is read and verification results reported.

### Actual behavior:

The following is shown almost instantly (thus no verification performed):
```
app: The above vms will be copied and added to your system.
app: Existing vms will not be removed.
qubesadmin.backup: -> Restoring banking...
qubesadmin.backup: -> Error restoring vm banking, skipping: vm banking already exists
qubesadmin.backup: -> Restoring personal...
qubesadmin.backup: -> Error restoring vm personal, skipping: vm personal already exists
```
etc...

### General notes:

This is with a fresh backup made in R4.

An additional error was shown at the very end:
```
qvm-backup-restore: error: Invalid file extension found in archive: backup-header
```
Also, the messaging in 'app:' lines seems inappropriate given that `verify-only` is used.

---

**Comment by tasket** [comment]
Submitted PR https://github.com/QubesOS/qubes-core-admin-client/pull/42

**Comment by tasket** [comment]
Another bug inherent to this issue:

Spurious new VMs were created during the verify process. For example, if 'personal' VM didn't exist in the live system but you verified an archive containing a 'personal' VM then a new VM by that name would be created.

The submitted PR should prevent this also.

**Comment by tasket** [comment]
PR was merged.

**Comment by andrewdavidwong** [comment]
Keeping this open for `github-builder` (unless we know we don't need it tracked for some reason).

**Comment by andrewdavidwong** [comment]
Never mind, looks like tracking works fine even if it's closed.
