### ISSUE TITLE
Fedora 25 -> Fedora 26 upgrade path

### ISSUE THREAD

**Issue by dmoerner** [QubesOS/qubes-issues#3309]
#### Qubes OS version:
R3.2

#### Affected TemplateVMs: 
fedora-25

With the release of Fedora 27 today, we can expect Fedora 25 to be EOL around December 15, 2017. At present, there seem to be a couple of upgrade path problems. My apologies if there is already an issue about this.

1. pulseaudio. Verified to be a problem upgrading qubes-template-fedora-25-minimal to Fedora 26. I would hope that this can be fixed by just rebuilding qubes-gui-vm.

```
[user@fedora-26 ~]$ sudo dnf upgrade
Last metadata expiration check: 5:05:03 ago on Tue 14 Nov 2017 11:46:40 AM EST.
Dependencies resolved.

 Problem 1: package qubes-gui-vm-3.2.18-1.fc26.x86_64 requires pulseaudio = 10.0, but none of the providers can be installed
  - cannot install both pulseaudio-11.1-2.fc26.x86_64 and pulseaudio-10.0-4.fc26.x86_64
  - cannot install both pulseaudio-10.0-4.fc26.x86_64 and pulseaudio-11.1-2.fc26.x86_64
  - cannot install the best update candidate for package qubes-gui-vm-3.2.18-1.fc26.x86_64
  - cannot install the best update candidate for package pulseaudio-10.0-4.fc26.x86_64
 Problem 2: package qubes-vm-dependencies-3.2.3-1.fc26.noarch requires qubes-gui-vm, but none of the providers can be installed
  - package qubes-gui-vm-3.2.18-1.fc26.x86_64 requires pulseaudio = 10.0, but none of the providers can be installed
  - package pulseaudio-10.0-4.fc26.x86_64 requires libpulsecommon-10.0.so()(64bit), but none of the providers can be installed
  - cannot install both pulseaudio-libs-11.1-2.fc26.x86_64 and pulseaudio-libs-10.0-4.fc26.x86_64
  - cannot install both pulseaudio-libs-10.0-4.fc26.x86_64 and pulseaudio-libs-11.1-2.fc26.x86_64
  - cannot install the best update candidate for package qubes-vm-dependencies-3.2.3-1.fc26.noarch
  - cannot install the best update candidate for package pulseaudio-libs-10.0-4.fc26.x86_64
 Problem 3: problem with installed package qubes-gui-vm-3.2.18-1.fc26.x86_64
  - package qubes-gui-vm-3.2.18-1.fc26.x86_64 requires pulseaudio = 10.0, but none of the providers can be installed
  - cannot install both pulseaudio-11.1-2.fc26.x86_64 and pulseaudio-10.0-4.fc26.x86_64
  - cannot install both pulseaudio-10.0-4.fc26.x86_64 and pulseaudio-11.1-2.fc26.x86_64
  - package pulseaudio-module-bluetooth-11.1-2.fc26.x86_64 requires libpulsecore-11.1.so()(64bit), but none of the providers can be installed
  - cannot install the best update candidate for package pulseaudio-module-bluetooth-10.0-4.fc26.x86_64
 Problem 4: problem with installed package qubes-vm-dependencies-3.2.3-1.fc26.noarch
  - package qubes-vm-dependencies-3.2.3-1.fc26.noarch requires qubes-gui-vm, but none of the providers can be installed
  - package qubes-gui-vm-3.2.18-1.fc26.x86_64 requires pulseaudio = 10.0, but none of the providers can be installed
  - cannot install both pulseaudio-11.1-2.fc26.x86_64 and pulseaudio-10.0-4.fc26.x86_64
  - cannot install both pulseaudio-10.0-4.fc26.x86_64 and pulseaudio-11.1-2.fc26.x86_64
  - package pulseaudio-module-x11-11.1-2.fc26.x86_64 requires libpulsecore-11.1.so()(64bit), but none of the providers can be installed
  - cannot install the best update candidate for package pulseaudio-module-x11-10.0-4.fc26.x86_64
================================================================================
 Package                         Arch       Version           Repository   Size
================================================================================
Skipping packages with conflicts:
(add '--best --allowerasing' to command line to force their upgrade):
 pulseaudio                      x86_64     11.1-2.fc26       updates     942 k
 pulseaudio-libs                 x86_64     11.1-2.fc26       updates     661 k
Skipping packages with broken dependencies:
 pulseaudio-module-bluetooth     x86_64     11.1-2.fc26       updates      76 k
 pulseaudio-module-x11           x86_64     11.1-2.fc26       updates      36 k

Transaction Summary
================================================================================
Skip  4 Packages

Nothing to do.
Complete!
```

2. yum-utils: yum-utils and dnf-utils conflict. This is an upstream bug. The version of dnf-utils in Fedora 26 was somehow uploaded to conflict against yum-utils < 1.1.31-513. This was an error, because yum-utils 1.1.31-513 is the auto-rebuild for Fedora 27. Upstream bug, with no action, here: https://bugzilla.redhat.com/show_bug.cgi?id=1467060

Fortunately, it can be avoided with the flag --allowerasing. However, because of issue (1) above, dnf upgrade --allowerasing will produce a disaster and try to remove Qubes packages.

**Comment by dmoerner** [comment]
I see that the first problem will be fixed by this commit: https://github.com/QubesOS/qubes-gui-agent-linux/commit/4cf2d1181be8ce3207c316124db4a2f92850955a 

Since the second issue has a solution, closing this bug. Sorry for the noise.

**Comment by picard-fr32k** [comment]
Qubes OS version:
R3.2

Affected TemplateVMs:
fedora-26

With the versions switch from Fedora 25 to 26 there seem to be a couple of upgrade path problems.

[user@fedora-26 ~]$ sudo dnf update
Letzte Prüfung auf abgelaufene Metadaten: vor 0:28:42 am Thu 14 Dec 2017 07:23:46 AM CET.
Abhängigkeiten sind aufgelöst.

 Problem 1: package salt-2017.7.2-1.fc26.noarch requires dnf-utils, but none of the providers can be installed
  - package dnf-utils-2.1.5-1.fc26.noarch conflicts with yum-utils < 1.1.31-513 provided by yum-utils-1.1.31-512.fc26.noarch
  - package dnf-utils-2.1.1-1.fc26.noarch conflicts with yum-utils < 1.1.31-513 provided by yum-utils-1.1.31-512.fc26.noarch
  - cannot install the best update candidate for package yum-utils-1.1.31-512.fc26.noarch
  - cannot install the best update candidate for package salt-2016.11.5-3.fc26.noarch
 Problem 2: problem with installed package yum-utils-1.1.31-512.fc26.noarch
  - package dnf-utils-2.1.5-1.fc26.noarch conflicts with yum-utils < 1.1.31-513 provided by yum-utils-1.1.31-512.fc26.noarch
  - package salt-2017.7.2-1.fc26.noarch requires dnf-utils, but none of the providers can be installed
  - package dnf-utils-2.1.1-1.fc26.noarch requires dnf-plugins-core = 2.1.1-1.fc26, but none of the providers can be installed
  - package salt-ssh-2017.7.2-1.fc26.noarch requires salt = 2017.7.2-1.fc26, but none of the providers can be installed
  - cannot install both dnf-plugins-core-2.1.1-1.fc26.noarch and dnf-plugins-core-2.1.5-1.fc26.noarch
  - cannot install the best update candidate for package salt-ssh-2016.11.5-3.fc26.noarch
  - cannot install the best update candidate for package dnf-plugins-core-2.1.5-1.fc26.noarch
================================================================================
 Paket                  Arch         Version                Paketquelle   Größe
================================================================================
Pakete mit Konflikten werden übersprungen:
(fügen Sie »--best --allowerasing« zur Befehlszeile hinzu, um die Aktualisierung zu erzwingen):
 dnf-plugins-core       noarch       2.1.1-1.fc26           fedora         49 k
 dnf-utils              noarch       2.1.1-1.fc26           fedora         39 k
 dnf-utils              noarch       2.1.5-1.fc26           updates        40 k
Skipping packages with broken dependencies:
 salt                   noarch       2017.7.2-1.fc26        updates       7.8 M
 salt-ssh               noarch       2017.7.2-1.fc26        updates        21 k

Transaktionsübersicht
================================================================================
Überspringen  5 Pakete

Nichts zu tun.
Fertig.

Thanks for QubesOS <3

**Comment by marmarek** [comment]
The problem looks to be properly handled with suggested options `--best --allowerasing`. `yum-utils` got removed and `dnf-utils` got installed instead.

**Comment by picard-fr32k** [comment]
ThX
sudo dnf update --best --allowerasing
[...]
Entfernt:
  yum-utils.noarch 1.1.31-512.fc26                                              

Installiert:
  dnf-utils.noarch 2.1.5-1.fc26                                                 

Aktualisiert:
  salt.noarch 2017.7.2-1.fc26          salt-ssh.noarch 2017.7.2-1.fc26         

Fertig.
[user@fedora-26 ~]$ sudo dnf update
Letzte Prüfung auf abgelaufene Metadaten: vor 0:02:25 am Thu 14 Dec 2017 04:37:27 PM CET.
Abhängigkeiten sind aufgelöst.
Nichts zu tun.
Fertig.
<3 many thX
