### ISSUE TITLE
Updating Templates goes over 32GB

### ISSUE THREAD

**Issue by spillinova** [QubesOS/qubes-issues#3312]
#### Qubes OS version:

R3.2

#### Affected TemplateVMs: 

The specifications for Qubes OS 3.2 suggests 32GB of disk space.  On initial installation the entire package takes up about 12GB.  But, after updating the 4 main templates and dom0, all 32GB are used and final updates cannot be completed.

---

### General notes:

---

**Comment by andrewdavidwong** [comment]
@marmarek: If this is normal behavior, should we just update the minimum storage requirement to, e.g., 50GB?

**Comment by unman** [comment]
32GB is the minimum recommended. It's usable provided you trim the templates after updating.(qvm-trim-template in 3.2). If you're working on the edge of what's acceptable then you need to take some care of your system. (Same applies if you are running with 4GB RAM.)

**Comment by andrewdavidwong** [comment]
Closing as "not an issue." If you believe this is a mistake, please leave a comment, and we'll be happy to take another look. Thank you.
