### ISSUE TITLE
Unable to launch any sys-net apps

### ISSUE THREAD

**Issue by smillerd** [QubesOS/qubes-issues#3317]
#### Qubes OS version:

Qubes release 3.2 (R3.2)

#### Affected TemplateVMs: 

fedora-23

---

### Steps to reproduce the behavior:

Updated my template VM, then restart sys-firewall and sys-net to implement updates to fedora-23. Unfortunately I am unable to update fedora-23 again as I do not have internet access.

### Expected behavior:

Open sys-net settings manager, connect to network

### Actual behavior:

Qubes VM Manager GUI shows sys-net is running, however when I attempt to open any apps it fails

### General notes:

I've tried a few things to get this working again -- I've restarted qubes to no avail. I've also shutdown sys-firewall and sys-net for a reboot. Later I Killed sys-net to see if that had any impact on the issue. It did not.

Unfortunately I'm a bit of a N00b, so I may be missing something obvious.

---

**Comment by marmarek** [comment]
Can you be more specific than "attempt to open any apps it fails"? What exactly happens?

**Comment by smillerd** [comment]
Sure. I use the GUI to double-click on, for example, settings or terminal. After waiting several minutes the settings or terminal will not open.

Thanks for you help

**Comment by smillerd** [comment]
Update: I've now tried to change the TemplateVM for sys-net to Debian-8 and to Debian-9. Both have the same issue so I don't think it's a TemplateVM issue. 

Additionally, when I attempt to restore sys-net from a backup (via the GUI), I cannot browse for a backup file within the VM. As a quick test, I found that I could browse for a backup file for sys-usb.

**Comment by smillerd** [comment]
Yes, sys-net is/was running when I encountered the issue.

For additional color, I ran the following command to attempt to replace sys-net:

`qvm-create sys-net-2 --net --red`

and then:
`qvm-pci -l sys-net-2`

and it returned an empty list, suggesting that when I created the new NetVM Qubes was unable to attach networking devices.

Back to your request, I looked in the errors folder and saw a warning:
`Message: Cannot save connection ude to error: Invalid setting Wi-Fi: 802-11-wireless.ssid: property is missing`.
The logs go on to mention that the assertion `GTK_IS_WIDGET '(widget)' failed` and then that there is a `'known incorrect sRBG profile`.

Then a traceback for qvm-run:
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnkown: The name :1.16 was not provided by any .service files

Let me know if that's what you were looking for. Unfortunately I'm on GitHub on a separate computer, so I can't copy and paste the output.

**Comment by marmarek** [comment]
The last one is interesting. There should be some filename reference - what is the last one containing "qubes"?
Does launching applications from console work? Try for example `qvm-run sys-net gnome-terminal`.

**Comment by smillerd** [comment]
Sorry for the delay, I've been AFK for a few hours.

The last filename with "qubes" in that traceback is: "/usr/lib64/python2.7/site-packages/qubes/notify.py"

If I try to launch applications from the console, I get the response `Running command on VM: 'sys-net'...`, however after waiting several minutes the terminal does not launch.

**Comment by marmarek** [comment]
Hmm, maybe your disk is full?

**Comment by smillerd** [comment]
Okay I created a new NetVM to replace the bricked NetVM.

I'm not sure what the old issue is, but I'm no longer unable to use Qubes.

Thanks for the time and support!
