### ISSUE TITLE
whonix-ws-dvm, the created vm (dispXXXX) does not stop and does not delete

### ISSUE THREAD

**Issue by adavida** [QubesOS/qubes-issues#3319]
#### Qubes OS version:
R4 rc2

#### Affected TemplateVMs: 
whonix-ws-dvm

---

### Steps to reproduce the behavior:
start whonix-ws-dvm e

### Expected behavior:
unlike the fedora-25-dvm, if I use whonix-ws-dvm, the created VM continues to work and does not delete itself

### General notes:

---

**Comment by unman** [comment]
I didnt see this behaviour in rc4, and I dont see it in a clean install of rc5.
Can anyone confirm this is no longer an issue? @adrelanos ?

**Comment by mirrorway** [comment]
Not an issue for me for any dispXXX based on whonix-ws-dvm.
