### ISSUE TITLE
Qubes split-gpg incompatible with --list-options / debsign

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#3320]
#### Qubes OS version:
R3.2

#### Affected TemplateVMs: 
debian-stretch but probably any Linux.

---

### Steps to reproduce the behavior:

    debsign -p/usr/bin/qubes-gpg-client-wrapper /home/user/whonix_binary/packages_temp/genmkfile_4.6-1_amd64.changes

### Expected behavior:

Qubes split-gpg functional.

### Actual behavior:

```
qubes-gpg-client: unrecognized option '--list-options'
debsign: /usr/bin/qubes-gpg-client-wrapper error occurred!  Aborting....
```

### General notes:

https://github.com/QubesOS/qubes-app-linux-split-gpg/pull/14 fixes it but I don't know if that is the appropriate way to fix it. Might be better to fix this in `qubes-gpg-client`. But since bigger changes to split-gpg are planned anyhow (https://github.com/QubesOS/qubes-issues/issues/474), I guess this workaround may be acceptable.

**Comment by marmarek** [comment]
What about allowing that option to go through? IMO it should be safe.

**Comment by adrelanos** [comment]
Didn't know that's (easily) possible. Yes, why not.
