### ISSUE TITLE
Add "Apply" button to VM Settings window

### ISSUE THREAD

**Issue by marmarta** [QubesOS/qubes-issues#3321]
#### Qubes OS version:

4.0

### Proposed change:

Add an "Apply" button to VM Settings window (qubes-vm-settings). Currently, it has only OK and Cancel buttons - Apply could be useful to streamline working with the window.

---

**Comment by constantoverride** [comment]
too lazy to create new issue but you should know that pressing the Apply button after some changes and then making other changes and pressing the OK button will just discard this latter changes.

ie. open VM settings, change networking from none to sys-firewall, press Apply, all good. Now change to none and press OK, still has sys-firewall.

**Comment by andrewdavidwong** [comment]
> too lazy to create new issue but you should know that pressing the Apply button after some changes and then making other changes and pressing the OK button will just discard this latter changes.
> 
> ie. open VM settings, change networking from none to sys-firewall, press Apply, all good. Now change to none and press OK, still has sys-firewall.
> 
> edit: unless some new update(s) fixed it (i haven't updated anything for like the past 9 days)

Thanks. Branched to #4833.
