### ISSUE TITLE
Whonix update error caused by expired release file

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#3323]
[On 2017-11-20 10:55, Adrian Rocha wrote:](https://groups.google.com/d/msgid/qubes-users/db4f84a7-487c-4ce2-8f4a-8b102e4b520c%40googlegroups.com)
> Hi,
> 
> When I try to update my Whonix gateway I have the following error:
> ```
> user@host:~$ sudo apt-get update 
> Hit http://deb.whonix.org jessie InRelease                                     
> Hit http://deb.qubes-os.org jessie InRelease                                   
> E: Release file for http://deb.whonix.org/dists/jessie/InRelease is expired (invalid since 4h 5min 45s). Updates for this repository will not be applied.
> user@host:~$
> ```
> I tried to clean the cache, change the URL protocol to https, but the error continues. Any ideas?
> 

Full thread:
https://groups.google.com/d/topic/qubes-users/wbT5XnzJAnM/discussion

CC: @adrelanos

**Comment by adrelanos** [comment]
Fixed.

**Comment by adrelanos** [comment]
I doubt still relevant, please close.

**Comment by TibebeJS** [comment]
having the same issue while updating both whonix-ws or whonix-gw template-vms in Qubes v4

`E: Release file for http://deb.whonix.org/dists/jessie/InRelease is expired (invalid since 202d 1h 55min 26s). Updates for this repository will not be applied.`

**Comment by adrelanos** [comment]
You are a few years too late with updates.
jessie based Whonix was Whonix 13.
stretch based Whonix was Whonix 14.
buster based Whonix is Whonix 15.

https://www.whonix.org/wiki/Stay_Tuned

**Comment by TibebeJS** [comment]
thank will try to update my system.

**Comment by heinrich-ulbricht** [comment]
And here is another one. I did a fresh Qubes OS installation a few days ago and followed the post-installation advice given here: https://www.qubes-os.org/doc/installation-guide/ This means I ran:

```
$ sudo qubes-dom0-update --enablerepo=qubes-templates-community --action=upgrade qubes-template-whonix-gw-14
$ sudo qubes-dom0-update --enablerepo=qubes-templates-community --action=upgrade qubes-template-whonix-ws-14
```
A few days later I try to update _whonix-gw-14_ and _whonix-ws-14_ and get this:

```
Reading package lists...
E: Release file for tor+http://deb.dds6qkxpwdeubwucdiaord2xgbbeyds25rbsgr73tbfpqpt4a6vjwsyd.onion/dists/stretch/InRelease is expired (invalid since 2d 16h 49min 25s). Updates for this repository will not be applied.
E: Release file for http://deb.whonix.org/dists/stretch/InRelease is expired (invalid since 2d 16h 49min 26s). Updates for this repository will not be applied.
```

Did something change 2 days ago? So far I followed along the documentation of getting Qubes OS 4 up and running.

**Comment by adrelanos** [comment]
Whonix 14 is deprecated.

https://forums.whonix.org/t/whonix-15-has-been-released/7616

https://forums.whonix.org/tags/important-news

https://www.whonix.org/wiki/Stay_Tuned

**Comment by heinrich-ulbricht** [comment]
What would you suggest I do? File issues for documentation update? Update to Whonix 15? Looking at issue #5108 it might also be worth waiting for Qubes 4.0.2. Also this issue #5183 indicates there might be problems when updating.

What would you do?

**Comment by andrewdavidwong** [comment]
> What would you suggest I do?

I suggesting installing Whonix 15 afresh:

https://www.whonix.org/wiki/Qubes/Install

> File issues for documentation update?

Sorry about the page being out-of-date. Yes, please do.

> Update to Whonix 15?

Yes, I'd suggest doing it fresh (https://www.whonix.org/wiki/Qubes/Install) rather than trying to upgrade from 14.

> Looking at issue #5108 it might also be worth waiting for Qubes 4.0.2.

Yes, that's another option, but it's not really necessary to wait.

> Furthermore this issue #5183 indicates there might be problems when updating Whonix from 14 to 15.
> 
> What would you do?

Personally, I opted to install Whonix 15 fresh (https://www.whonix.org/wiki/Qubes/Install) rather than attempt an in-place upgrade. I felt that this was simpler and less error-prone, and I didn't have a need to upgrade in-place.

**Comment by brendanhoar** [comment]
I did the same thing (uninstalled 14, installed 15), yesterday, after the most recent TB update failed to work correctly in 14.
