### ISSUE TITLE
Qubes 4.0rc2, 17 Updates today 21/11, no vms are starting (log attached)

### ISSUE THREAD

**Issue by mannp** [QubesOS/qubes-issues#3324]
#### Qubes OS version:

v4rc2

#### Affected TemplateVMs: 

All
---

### Steps to reproduce the behavior:

Install all 17 updates from this morning and reboot the machine.

### Expected behavior:

Vm's start as usual.

### Actual behavior:

Nothing starts and an error is reported in journalctl -> [http://safe.dsh.re/download/e31a0971-9f30-4e9a-b700-1c02c220f5d8](url)

**Edit:** A second reboot has allowed the sys-net and sys-firewall to start and things seem ok, will continue to check and leave this up incase the log flags anything.

### General notes:

Thanks for all the updates to bugs though :)

---

**Comment by marmarek** [comment]
Check if you have some previous error about qubes-qmemman service.

**Comment by mannp** [comment]
I had ;

> 
qubes-qmemman.service: Job qubes-qmemman.service/start deleted to break ordering cycle starting with qubes-core.service/start

 in red text.

**Comment by marmarek** [comment]
Should be fixed here:
https://github.com/QubesOS/updates-status/issues/315

**Comment by mannp** [comment]
Excellent response time :) thank you.

**Comment by marmarek** [comment]
Immediate solution is to start qmemman: `sudo systemctl start qubes-qmemman.service`
