### ISSUE TITLE
Qubes split-gpg - add --set-notation --verify-options --sign-with

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#3325]
Analogous to:

* https://github.com/QubesOS/qubes-issues/issues/3320#issuecomment-345666733
* https://github.com/marmarek/qubes-app-linux-split-gpg/commit/e644739bfec9fceaccf68e3b853870233ec73855

Could you please white list the following gpg options if appropriate?

* `--set-notation`
* `--verify-options` (to check notations)
* `--sign-with`

I am trying to use split-gpg for everything, not just e-mail. These are some issues I am bumping in.

**Comment by marmarek** [comment]
I can't see --sign-with in gpg2 manual. Is it some legacy stuff? Maybe `gpg-client-wrapper` could replace it with `--local-user`, or `--default-key`?

**Comment by iamahuman** [comment]
It would also be useful to alias `--clear-sign` to `--clearsign`.

**Comment by DemiMarie** [comment]
@adrelanos interested in making a PR for `--sign-with`?

> I can't see --sign-with in gpg2 manual. Is it some legacy stuff? Maybe `gpg-client-wrapper` could replace it with `--local-user`, or `--default-key`?

It’s an alias for `--local-user`, as per [the source code](https://github.com/gpg/gnupg/blob/98c52aeb31f4bf2604727aacad982fb51c04063f/g10/gpg.c#L927-L928).  It exists for compatibility with PGP.

**Comment by adrelanos** [comment]
> You can modify the shell script to treat `--sign-with` as an alias for `--local-user`.

Ah. Had no idea. Looking into it.

**Comment by adrelanos** [comment]
Please let me know if these snippets look promising / good enough. (Tested. Working fine.) If so, I'd add a create request soonish.

```
check_alnum_space() {
   re='[^-[:alnum:][:space:]]'
   if [[ "$1" =~ $re ]]; then
        printf 'Unsupported character set %q\n' "$1"
        exit 1
   fi
}
```

```
            # https://github.com/QubesOS/qubes-issues/issues/3325#issuecomment-1039877769
            --sign-with=*)
                check_alnum_space "${1:12}"
                options+=("--local-user=${1:12}")
                shift
                ;;
            --sign-with)
                if (( $# >= 2 )); then
                    check_alnum_space "$2"
                    options+=("--local-user" "$2")
                    shift 2
                else # let qubes-gpg-client error out
                    options+=("--local-user")
                    shift
                fi
                ;;
```

**Comment by DemiMarie** [comment]
Those look fine; you can even replace `"--local-user=${1:12}"` with `-u "${1:12}"` and `--local-user "$2"` with `-u "$2"` to save a few bytes.  split-gpg1 has a command line size limit so this might actually matter in corner cases.

That said, what is the purpose of `check_alnum_space`?  Checks like this should really be in the C code, since that is what actually protects the backend qube from malicious data.  Also, this check won’t run for `--local-user=`.  I suggest removing this line.

**Comment by adrelanos** [comment]
> It would also be useful to alias `--clear-sign` to `--clearsign`.

Works for me already.

> --set-notation
> --verify-options (to check notations)

Must have been implemented meanwhile. Also works for me.

**Comment by adrelanos** [comment]
> Those look fine; you can even replace `"--local-user=${1:12}"` with `-u "${1:12}"` and `--local-user "$2"` with `-u "$2"` to save a few bytes. split-gpg1 has a command line size limit so this might actually matter in corner cases.


> That said, what is the purpose of `check_alnum_space`? Checks like this should really be in the C code, since that is what actually protects the backend qube from malicious data. Also, this check won’t run for `--local-user=`. I suggest removing this line.

Probably a case of... I saw this in the wrapper already...

```
check_charset () {
    if ! [[ "$1" =~ ^[uU][tT][fF]-?8$ ]]; then
        printf 'Unsupported character set %q\n' "$1"
        exit 1
    fi
}
```

And thought, well the culture is the check characters, so I should do that too. Happy to drop it for simplicity.
(But indeed was already thinking about how solid/generalized the character checking is and wondering if that could be improved in the future. Since it gets checked in C, no problem. After all, of course an attacker could circumvent the wrapper.)

> Those look fine; you can even replace `"--local-user=${1:12}"` with `-u "${1:12}"` and `--local-user "$2"` with `-u "$2"` to save a few bytes.

I might have argued pro long parameters. Easier to debug when looking at the bash xtrace, easier to read, easier to guess what it does and easier to find in the man page. (--local-user can be found, few matches, more easily than -u, multiple matches.) But due to... 

> split-gpg1 has a command line size limit so this might actually matter in corner cases.

...OK.

**Comment by DemiMarie** [comment]
> > Those look fine; you can even replace `"--local-user=${1:12}"` with `-u "${1:12}"` and `--local-user "$2"` with `-u "$2"` to save a few bytes. split-gpg1 has a command line size limit so this might actually matter in corner cases.
> 
> > That said, what is the purpose of `check_alnum_space`? Checks like this should really be in the C code, since that is what actually protects the backend qube from malicious data. Also, this check won’t run for `--local-user=`. I suggest removing this line.
> 
> Probably a case of... I saw this in the wrapper already...
> 
> ```
> check_charset () {
>     if ! [[ "$1" =~ ^[uU][tT][fF]-?8$ ]]; then
>         printf 'Unsupported character set %q\n' "$1"
>         exit 1
>     fi
> }
> ```
> 
> And thought, well the culture is the check characters, so I should do that too. Happy to drop it for simplicity. (But indeed was already thinking about how solid/generalized the character checking is and wondering if that could be improved in the future. Since it gets checked in C, no problem. After all, of course an attacker could circumvent the wrapper.)

It doesn’t get checked in C, except to ensure that it is valid UTF-8.  The reason for checking the argument to `--charset` and `--display-charset` is that those are disallowed on the C side and are thus discarded by the wrapper.  A value of `--charset` or `--display-charset` that is not compatible with UTF-8 could therefore cause GPG to interpret its command line in an unexpected way.

**Comment by adrelanos** [comment]
https://github.com/QubesOS/qubes-app-linux-split-gpg/pull/71
