### ISSUE TITLE
make Qubes split-gpg compatible with reprepro / libgpgme

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#3326]
reprepro (which is using libgpgme) is using the following gpg command line options which are currently rejected by Qubes split-gpg.

* `--enable-special-filenames`
* `--no-sk-comments`
* `--exit-on-status-write-error`
* `--ttyname`
* `--ttytype`

[1] [2]

-----

Simply white listing these in `/usr/bin/qubes-gpg-client-wrapper` won't do the trick.

    exec qubes-gpg-client --batch --status-fd 7 --no-tty --charset utf8 --enable-progress-filter --display :0 /dev/pts/2 xterm-256color -- '-&8'
    gpg: WARNING: no command supplied.  Trying to guess what you mean ...

-----

A full example command that reprepro is using.

    gpg --enable-special-filenames --batch --no-sk-comments --status-fd 7 --no-tty --charset utf8 --enable-progress-filter --exit-on-status-write-error --display :0 --ttyname /dev/pts/2 --ttytype xterm-256color --output - -- '-&8

-----

[1] (I learned about these by adding to `/usr/bin/qubes-gpg-client-wrapper`.)

    set -x
    exec 6>&2 2>> "/tmp/output"

[2] I haven't found an option in reprepro to configure which gpg binary to use so I replaced `/usr/bin/gpg` with  `/usr/bin/qubes-gpg-client-wrapper`. (Of course after creating a backup of `/usr/bin/gpg` so I can revert it. - Or no backup - since TemplateBased AppVMs root image is conveniently reset every reboot anyhow. :) Asked the author of reprepro if such a feature exist of if he could kindly add this feature.

----

Related:

* #3320
* #3325

//cc @HW42 (reprepro looks like an excellent stress test for complex uses of gpg for #474.)

**Comment by adrelanos** [comment]
> reprepro uses libgpgme, so it is quite limited in what it can do in that regard. Especially that seems to do some complicated magic like first looking for a gpgconf program and parsing that output. (And from the
comments in the code seems to assume that without that it is gpg1 instead of gpg2). It seems to have some function to change defaults but no real documentation about what it exactly expects there (and if that can even be used to choose a different gpg client).

> As I understand it, everything that should be changed with those settings should also be possible by adding some directory in front of the PATH you call reprepro with that contains a gpgconf binary that outputs the correct things. (Though I have no idea what "correct" means there).

> Bernhard R. Link
>
> F8AC 04D5 0B9B 064B 3383  C3DA AFFC 96D1 151D FFDC

**Comment by marmarek** [comment]
> --enable-special-filenames

This should be possible to handle, but not trivial. Perhaps with a help from `qubes-gpg-client-wrapper`. Like replacing "special filenames" (`-&n` according to manual), with `/proc/self/fd/n`.

>     --no-sk-comments
>     --exit-on-status-write-error

Those can be easily included in the whitelist.

>     --ttyname
>     --ttytype

What those options do? I don't see them in gpg2 manual. If I'm guessing correctly, it would be tricky to correctly implement them - backend (intentionally) have no access to frontend console. But it might work if you ignore those options in `qubes-gpg-client-wrapper`.

**Comment by grote** [comment]
kmail is also using libgpgme and it is trying to call gpg like this:
```
--enable-special-filenames --batch --no-sk-comments --status-fd 52 --no-tty --charset utf8 --enable-progress-filter --exit-on-status-write-error --display :0 --ttyname /dev/pts/0 --ttytype xterm-256color --decrypt --output - -- -&54
```

**Comment by marmarek** [comment]
See https://github.com/QubesOS/qubes-app-linux-split-gpg/pull/16

**Comment by grote** [comment]
kmail now modified their line, changing the end to

`--decrypt --output - --input-size-hint 8248 -- -&101`

and we don't recognize the `input-size-hint`.

**Comment by DemiMarie** [comment]
> Usability is limited though, because the window labeled "[Dom0] Operation execution" pops up many times per mail. If I press cancel there, claws-mail hangs until killed manually.

The hang is #6462, but for claws-mail instead of Thunderbird.

**Comment by grote** [comment]
On fedora 24 kmail is now using this to list keys:

`--disable-dirmngr --batch --no-sk-comments --status-fd 79 --no-tty --charset utf8 --enable-progress-filter --exit-on-status-write-error --display :0 --logger-fd 85 --with-colons --with-secret --with-keygrip --list-keys --`

where `--with-secret` is unknown essentially breaking the possibility to sign/encrypt emails :roll_eyes:

**Comment by adrelanos** [comment]
Installed https://github.com/QubesOS/updates-status/issues/2816 from Qubes R4.1 Debian bullseye-testing repository just now. Not reprepro compatible yet.

    reprepro --basedir /home/user/Whonix/aptrepo_remote --outdir /home/user/whonix_binary/aptrepo_remote --dbdir /home/user/whonix_binary/aptrepo_remote/db --logdir /home/user/whonix_binary/aptrepo_remote/log --export=changed export bullseye

```
Exporting bullseye...
gpgme gave error GnuPG:1:  General error
ERROR: Could not finish exporting 'bullseye'!
There have been errors!
```

[libgpgme](https://github.com/QubesOS/qubes-issues/issues/3326#) port seems done but not yet compatible with reprepro. Better to re-open this ticket or shall I create a new ticket?

**Comment by DemiMarie** [comment]
Reopened.  @adrelanos can you provide the specific command line that failed, perhaps by modifying the wrapper script to log it?

**Comment by adrelanos** [comment]
Here's my modification:

```
if [[ "$localgpg" -eq 1 ]]
then
    echo A: /usr/bin/gpg "${origargs[@]}" >> /tmp/a
    exec /usr/bin/gpg "${origargs[@]}"
    exit $?
fi

. /etc/profile.d/qubes-gpg.sh
# 63 is $fd_for_stdout but bash seems to reject variables here

if ((output)); then
    if [[ "$target" != '-' ]]; then
       echo B: exec '>' "$target" >> /tmp/a
    fi
    echo C: exec qubes-gpg-client "${options[@]}" >> /tmp/a
    exec qubes-gpg-client --output=- "${options[@]}" 63>&1
else
    echo D: exec qubes-gpg-client "${options[@]}" >> /tmp/a
    exec qubes-gpg-client "${options[@]}" 63>&1
fi
```

**Comment by adrelanos** [comment]
test command:

    rm /tmp/a ; reprepro --basedir /home/user/Whonix/aptrepo_remote --outdir /home/user/whonix_binary/aptrepo_remote --dbdir /home/user/whonix_binary/aptrepo_remote/db --logdir /home/user/whonix_binary/aptrepo_remote/log --export=changed export bullseye ; echo "" ; cat /tmp/a

reprepro terminal output:

> Exporting bullseye...
> gpgme gave error GnuPG:1:  General error
> ERROR: Could not finish exporting 'bullseye'!
> There have been errors!

logged commands:

```
D: exec qubes-gpg-client --version
D: exec qubes-gpg-client --batch --status-fd 8 --enable-progress-filter --exit-on-status-write-error --logger-fd 12 --with-colons --with-keygrip --list-secret-keys -- 0x8D66066A2EEACCDA
D: exec qubes-gpg-client --status-fd 8 --enable-progress-filter --exit-on-status-write-error --logger-fd 10 --command-fd 11 --sign --detach-sign --armor -u 8D66066A2EEACCDA -- /proc/self/fd/13
```

Seems like the first two command succeed but the third one is failing. Manual reproduction of the third command seems difficult since it uses streams / redirections.

(I added `A:`- `D:` as prefix to identify the code path in use.)

(Note to self: don't copy `exec` and run in terminal emulator directly - it will close the terminal emulator.)

**Comment by DemiMarie** [comment]
> Seems like the first two command succeed but the third one is failing. Manual reproduction of the third command seems difficult since it uses streams / redirections.

For testing, it is sufficient to redirect input file descriptors (such as `--command-fd`) to read from `/dev/null`, and output file descriptors (such as `--logger-fd`) to point to file descriptor 1.

**Comment by DemiMarie** [comment]
> ```
> D: exec qubes-gpg-client --status-fd 8 --enable-progress-filter --exit-on-status-write-error --logger-fd 10 --command-fd 11 --sign --detach-sign --armor -u 8D66066A2EEACCDA -- /proc/self/fd/13
> ```

This fails with `Bad file descriptor` for the command FD.

**Comment by DemiMarie** [comment]
> > > ```
> > > D: exec qubes-gpg-client --status-fd 8 --enable-progress-filter --exit-on-status-write-error --logger-fd 10 --command-fd 11 --sign --detach-sign --armor -u 8D66066A2EEACCDA -- /proc/self/fd/13
> > > ```
> > 
> > 
> > This fails with `Bad file descriptor` for the command FD.
> 
> I am not surprised. That command I guess likely doesn't make sense on its own, standalone, it probably only makes sense in the bigger context of how reprepro is doing things.

This is true even with when the command FD is redirected to `/dev/null`.  As a workaround, you can modify the wrapper script to strip out `--command-fd` and its argument; I don’t think it will matter in this case.

**Comment by DemiMarie** [comment]
This could very well be a bug in how split-gpg remaps file descriptors.  @marmarek worth tracking down and fixing?

**Comment by DemiMarie** [comment]
The culprit was that file descriptor 11 is closed when closing the read
sides of the output pipes (the ones that gpg will write to).  Fixing the
bug is easy and will make the code much simpler; the entire remap table
can simply be deleted.  I added these changes to
https://github.com/QubesOS/qubes-app-linux-split-gpg/pull/69, not
because I wanted to completely reimplement fd remapping but because it
was the simplest way I know of to fix the bug.  There were also race
conditions in signal handling and file descriptor handling that I have
fixed.  All of these bugs had to be fixed for the command in
QubesOS/qubes-issues#3326 to work reliably, which is why only the last
commit in https://github.com/QubesOS/qubes-app-linux-split-gpg/pull/69
is listed as fixing it.

**Comment by adrelanos** [comment]
Should be tagged component `C: split-gpg1`.
(Seems like tag `C: split-gpg2` was never invented.)

(Please let me know if comments on wrong tags are better as comments (adds noise to the ticket) or better by e-mail or otherwise. For now, I assume it's appropriate to comment in the ticket.)

**Comment by andrewdavidwong** [comment]
> Should be tagged component `C: split-gpg1`. (Seems like tag `C: split-gpg2` was never invented.)

I noticed that too, but wasn't sure if it was intentional, @DemiMarie. Maybe the thought was just to make `C: split-gpg2` when it's needed?

> (Please let me know if comments on wrong tags are better as comments (adds noise to the ticket) or better by e-mail or otherwise. For now, I assume it's appropriate to comment in the ticket.)

Comments are good for this. Thanks!
