### ISSUE TITLE
fedora25->fedora26 following case

### ISSUE THREAD

**Issue by boistordu** [QubesOS/qubes-issues#3328]
#### Qubes OS version:
`R3.2`

I have done the upgrade yesterday. We still have a problem with pulseaudio but less of the previous one. 
Pulseaudio 11.1 is still incompatbile with qubes-gui-vm so we still have a message to add --best --allowerasing at the upgrade command-line. We need to downgrade pulseaudio to 10.0 to still have qubes-vm-gui installed. 

```
Skipping packages with conflicts:
(add '--best --allowerasing' to command line to force their upgrade):
 dnf-utils                       noarch 2.1.5-1.fc26              updates  40 k
 pulseaudio                      x86_64 11.1-6.fc26               updates 944 k
 pulseaudio-libs                 i686   11.1-6.fc26               updates 672 k
 pulseaudio-libs                 x86_64 11.1-6.fc26               updates 662 k
 pulseaudio-libs-glib2           x86_64 11.1-6.fc26               updates  26 k
 pulseaudio-module-bluetooth     x86_64 11.1-6.fc26               updates  76 k
 pulseaudio-module-x11           x86_64 11.1-6.fc26               updates  37 k
 pulseaudio-utils                x86_64 11.1-6.fc26               updates  75 k

```

**Comment by andrewdavidwong** [comment]
Will this be fixed by https://github.com/QubesOS/qubes-gui-agent-linux/commit/4cf2d1181be8ce3207c316124db4a2f92850955a as suggested in https://github.com/QubesOS/qubes-issues/issues/3309#issuecomment-344411796?

**Comment by marmarek** [comment]
The update with this is already in testing repository: https://github.com/QubesOS/updates-status/issues/296

**Comment by boistordu** [comment]
okey then we'll wait for this thing coming to update rep

**Comment by boistordu** [comment]
16 days and still no update ... I have done all the dnf clean all. How much time do you still need for this to happen ?

**Comment by andrewdavidwong** [comment]
@boistordu:
> 16 days and still no update ... I have done all the dnf clean all. How much time do you still need for this to happen ?

You do not have to rely on `dnf clean all` to check whether the package is available in stable. You can see when the package moves from testing to stable here: https://github.com/QubesOS/updates-status/issues/296. For more information, see [Testing New Releases and Updates](https://www.qubes-os.org/doc/testing/).

The amount of time it takes for a package to move from testing to stable varies depending on many factors, including feedback from testers and developer workflow priorities. If you don't want to wait, you can [enable the current-testing repo](https://www.qubes-os.org/doc/software-update-dom0/#testing-repositories).

**Comment by boistordu** [comment]
I know sorry but you can know that's frustrating since fedora version are in my own opinion, very fast to be out of busines, so one month from a 10-12 month timetable is actually a lot. But yeah of course I will wait, but still. Thanks for the answer anyway

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
