### ISSUE TITLE
Qubes 3.2 installation failed

### ISSUE THREAD

**Issue by meo-neo** [QubesOS/qubes-issues#3332]
#### Qubes OS version:

R 3.2

#### Affected TemplateVMs: 

---

### Steps to reproduce the behavior:

Installation

### Expected behavior:

Qubes R3,2 should be up and running

### Actual behavior:

Qubes did not boot

### General notes:

I  was using windows 10 on SSD with two partitions. I tried to install Qubes R3.2 via liveUSB method. During installation i selected D: partition on my SSD to be shrinked via auto method to reclaim the required space. The installation finished without any errors but i did not get any Qubes boot loader in the list. Upon running again the setup, i found out that i was lacking 7 gb of space. I attached another HDD, selected both the previous D: partition and a new partition of the attached HDD so that Qubes could reclaim the required space of 32gb. The setup finished without errors. Again upon rebooting i did not get the Qubes boot loader.

Now problem is that i cannot also get back to the windows boot loader. 

Also on startup i am getting two errors

PXE-E61: media test failure, check cable
PXE-M0F: exiting intel boot agent

after the above errors are displayed system will show me the boot menu with following 3 options:

1) Windows boot loader
2) ATA0 HDD Samsung
3) PCI Lan

clicking any option will do nothing and is stuck at the same window.

I tried different methods by repairing, diskpart, bootrec but they did not work.

All i want for now is to get the windows boot loader back and up running. Any help would be highly appreciated.

PS: I am novice in using linux.

---

**Comment by andrewdavidwong** [comment]
> I tried to install Qubes R3.2 via liveUSB method.

Are you referring to Qubes Live USB (alpha)? If so, please know that it's very old and no longer supported. If you can, please try the standard Qubes Release 3.2 installer instead.

**Comment by meo-neo** [comment]
Hello andrew,
I followed the following mentioned guidelines https://www.qubes-os.org/doc/installation-guide/
with only difference that target device was my harddisk instead of a USB device.

**Comment by meo-neo** [comment]
I burned iso on USB via rufus as mentioned and all later steps are described above.

**Comment by meo-neo** [comment]
i am closing this issue, as i reformatted my drive. so no need to keep it open as issue was not resolved.
