### ISSUE TITLE
sys-net doesn't synchronize time with NTP servers

### ISSUE THREAD

**Issue by bcdev-** [QubesOS/qubes-issues#3333]
#### Qubes OS version:
R4.0-rc2
#### Affected TemplateVMs: 
sys-net on fedora-25

### General notes:
After installing Qubes, sys-net never synchronized time with the internet's NTP servers. > 24h have passed since the instalation, with countless reboots and the clock was still skewed.
`ntpdate` wasn't installed on sys-net, I had to manually install it and synchronize via `ntpdate 0.pl.pool.ntp.org`.
This is not a problem with `qvm-sync-clock`, this is a problem specifically with sys-net's automatic NTP synchronization.

Can someone reproduce the problem, or is it just a problem with my installation? If not, I'll check it on a secondary computer with a fresh installation in about 2 weeks or so.

**Comment by kalkin** [comment]
I can reproduce this error and the fix. The bug is pretty annoying because after installation the clock is wrong and even if you set it via `sudo date -s` in the dom0 it's will still reset clock to some random time, after a few minutes.

**Comment by marmarek** [comment]
Similar issue confirmed in https://github.com/QubesOS/qubes-issues/issues/3469#issuecomment-358215614 - systemd-timesyncd service is not running in sys-net.

**Comment by marmarek** [comment]
Actually, there was `chronyd.service` running instead. In 4.0rc4 templates, it is no longer the case and `systemd-timesyncd.service` is running properly. And apparently it deals better with time sync, across suspends.
Can someone with 4.0rc3 updated installation check logs of `chronyd.service`?

But there is still other problem - VMs do not synchronize clock with. Apparently `qubes-sync-time.timer` is not started.
