### ISSUE TITLE
qvm-create --class DispVM throws exception in qubesd

### ISSUE THREAD

**Issue by zander** [QubesOS/qubes-issues#3341]
#### Qubes OS version:
4RC2, updated to latest 'current'. So likely RC3.

### Steps to reproduce the behavior:

I build my own archlinux template which works great and I have some AppVMs based on it.

As this actually includes KDE, I want it to be the basis of my DispVM.

As such I found that qvm-create has a list of classes, one of them is 'DispVM'.
So I ran;

`qvm-create --class DispVM --template archlinux --label red DispArch`

### Expected behavior:
I expected to get a VM that would be used as a template for disposable VMs.

### Actual behavior:
qvm-create came back with a hint to look in the journal.

The output follows;

```
Nov 27 18:55:48 dom0 qubesd[2760]: unhandled exception while calling src=b'dom0' meth=b'admin.vm.Create.DispVM' dest=b'dom0' arg=b'archlinux' len(untrusted_payload)=23
Nov 27 18:55:48 dom0 qubesd[2760]: Traceback (most recent call last):
Nov 27 18:55:48 dom0 qubesd[2760]:   File "/usr/lib/python3.5/site-packages/qubes/api/__init__.py", line 262, in respond
Nov 27 18:55:48 dom0 qubesd[2760]:     untrusted_payload=untrusted_payload)
Nov 27 18:55:48 dom0 qubesd[2760]:   File "/usr/lib64/python3.5/asyncio/futures.py", line 381, in __iter__
Nov 27 18:55:48 dom0 qubesd[2760]:     yield self  # This tells Task to wait for completion.
Nov 27 18:55:48 dom0 qubesd[2760]:   File "/usr/lib64/python3.5/asyncio/tasks.py", line 310, in _wakeup
Nov 27 18:55:48 dom0 qubesd[2760]:     future.result()
Nov 27 18:55:48 dom0 qubesd[2760]:   File "/usr/lib64/python3.5/asyncio/futures.py", line 294, in result
Nov 27 18:55:48 dom0 qubesd[2760]:     raise self._exception
Nov 27 18:55:48 dom0 qubesd[2760]:   File "/usr/lib64/python3.5/asyncio/tasks.py", line 240, in _step
Nov 27 18:55:48 dom0 qubesd[2760]:     result = coro.send(None)
Nov 27 18:55:48 dom0 qubesd[2760]:   File "/usr/lib64/python3.5/asyncio/coroutines.py", line 213, in coro
Nov 27 18:55:48 dom0 qubesd[2760]:     res = yield from res
Nov 27 18:55:48 dom0 qubesd[2760]:   File "/usr/lib/python3.5/site-packages/qubes/api/admin.py", line 1000, in _vm_create
Nov 27 18:55:48 dom0 qubesd[2760]:     vm = self.app.add_new_vm(vm_class, **kwargs)
Nov 27 18:55:48 dom0 qubesd[2760]:   File "/usr/lib/python3.5/site-packages/qubes/app.py", line 1081, in add_new_vm
Nov 27 18:55:48 dom0 qubesd[2760]:     return self.domains.add(cls(self, None, qid=qid, **kwargs))
Nov 27 18:55:48 dom0 qubesd[2760]:   File "/usr/lib/python3.5/site-packages/qubes/vm/dispvm.py", line 81, in __init__
Nov 27 18:55:48 dom0 qubesd[2760]:     if not template.template_for_dispvms:
Nov 27 18:55:48 dom0 qubesd[2760]: AttributeError: 'TemplateVM' object has no attribute 'template_for_dispvms'
```

#### Related issues:
#3047

**Comment by rustybird** [comment]
> `qvm-create --class DispVM --template archlinux --label red DispArch`

> I expected to get a VM that would be used as a template for disposable VMs.

Use `--property template_for_dispvms=True` instead of `--class DispVM`.

**Comment by arjan-s** [comment]
Creating a VM with that property does work. It also is possible to run for instance `qvm-run --dispvm=arch-dvm --service qubes.StartApp+firefox`.
What doesn't work is registering the new DispVM in the Qubes interface.
The menu options created for the new DispVM start the applications in the AppVM/template, not in a newly created DispVM. I can fix this manually by running `qvm-features arch-dvm appmenus-dispvm true` and then selecting the applications I want in the menu.
Also, it's not possible to choose the new DispVM as default DispVM in the configuration dialog of other AppVM's. I don't know how to fix this yet.
