### ISSUE TITLE
Installing Qubes OS on lenovo yoga 710 

### ISSUE THREAD

**Issue by akshaybhandari95** [QubesOS/qubes-issues#3347]
#### Qubes OS version:

Installation process is stuck during whonix package installation . it;s happening everytime when i am going to install it freshly  

Laptop Model Lenovo yoga 710

#### Affected TemplateVMs: 

---

### General notes:

---

**Comment by andrewdavidwong** [comment]
Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this does not appear to be suitable for `qubes-issues`. We ask that you please send this to the `qubes-users` [mailing list](https://www.qubes-os.org/mailing-lists/) instead. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a brief comment explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.

**Comment by akshaybhandari95** [comment]
My laptop model is not listed in Hardware Compatibility support  list  
 Please check if it is support for this model laptop

Lenovo Yoga 710
 i7 7th generation 
8GB RAM  DDR4 
2 GB NVIDIA Ge-force 940 MX
SSD storage

**Comment by andrewdavidwong** [comment]
@akshaybhandari95: We have no way to check that, since we don't have any units of that model.
