### ISSUE TITLE
core-admin(-client): --quiet & --verbose broken

### ISSUE THREAD

**Issue by jpouellet** [QubesOS/qubes-issues#3357]
As best I can tell, the intended behavior is for objects returned by `qubes(admin).tools.QubesArgumentParser.parse_args()` to only have a `verbose` integer property (defaulting to 1, incremented by --verbose, decremented by --quiet), and for consumers of the API to just compare against the value of the `verbose` property, as if a `quiet` property did not exist.

This seems to be the way things worked until around https://github.com/QubesOS/qubes-core-admin/commit/015b01fe465fce667b9302bcf933dc41d712d607 when some refactoring stopped computing the single verbosity integer by default, leading to `--quiet` for most qvm-* tools having no effect.

Also, there is a bunch of code duplication between qubes and qubesadmin, with slight divergences, and I'd have to fix this in both. Is there a reason to want to maintain both separately? Or should some parts (e.g. the `qubes(admin).tools` utility module) first be factored out and the code deduplicated?

**Comment by jpouellet** [comment]
Well, it does still compute a single verbosity integer, but only privately for use in e.g. setting logging levels, not in the returned namespace - which makes me question if perhaps now tools are expected to handle checking a `quiet` property themselves?

**Comment by iamahuman** [comment]
`qvm-backup` appears affected.
