### ISSUE TITLE
make Debian qubes-kernel-vm-support compatible with dracut

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#3361]
https://github.com/QubesOS/qubes-linux-utils/commit/3cd77e4f70a6e8a92daf13b4851c46d7659d2a34 indicates, that `qubes-kernel-vm-support` is compatible with `dracut`.

However, `qubes-kernel-vm-support` [`Depends:`](https://github.com/QubesOS/qubes-linux-utils/blob/3cd77e4f70a6e8a92daf13b4851c46d7659d2a34/debian/control#L19) on `initramfs-tools`. But  `initramfs-tools` by Debian default, conflicts with `dracut`. So when trying to install `dracut`, `initramfs-tools` and `qubes-kernel-vm-support` gets removed.

Solution? First: Remove the dependency `initramfs-tools` from `qubes-kernel-vm-support`.

But caution. While this might be the correct thing to do, we must make sure that `initramfs-tools` does not get autoremoved since no other package is depending on it anymore. Otherwise this could make Qubes VMs using VM kernel unbootable.

**Comment by marmarek** [comment]
Will moving `initramfs-tools` to `Recommends:` work?

**Comment by marmarek** [comment]
Also, is dracut supported on Debian?

**Comment by adrelanos** [comment]
> Will moving initramfs-tools to Recommends: work?

Yes, that would be good. Would mean initramfs-tools can be removed without having qubes-vm-kernel-support removed. BUT the part "but caution" n my previous post still applies.

> Also, is dracut supported on Debian?

Yes, works as drop-in solution.

**Comment by marmarek** [comment]
> Yes, that would be good. Would mean initramfs-tools can be removed without having qubes-vm-kernel-support removed. BUT the part "but caution" n my previous post still applies.

So, `Recommends:` is ignored by autoremove?

**Comment by adrelanos** [comment]
Ah. That's a good question. Never tried downgrade from `Depends:` to `Recommends:`.

**Comment by adrelanos** [comment]
Just now tested. Moving from `Depends:` to `Recommends:` is a simple and great solution. `qubes-kernel-vm-support` will not be removed when installing `dracut`.
