### ISSUE TITLE
qvm-backup-restore verify-only: archives having dom0 yield NoneType error

### ISSUE THREAD

**Issue by tasket** [QubesOS/qubes-issues#3362]
#### Qubes OS version:

R4.0-rc3

---

### Steps to reproduce the behavior:

```
qvm-backup-restore --verify-only path-to-archive
```
The archive must contain a backup of dom0.

### Expected behavior:

Verify completes without error.

### Actual behavior:

```
app: Checking backup content...
Traceback (most recent call last):
  File "/usr/bin/qvm-backup-restore", line 5, in <module>
    sys.exit(main())
  File "/usr/lib/python3.5/site-packages/qubesadmin/tools/qvm_backup_restore.py", line 245, in main
    restore_info = backup.get_restore_info()
  File "/usr/lib/python3.5/site-packages/qubesadmin/backup/restore.py", line 1536, in get_restore_info
    vms_to_restore['dom0'] = self.Dom0ToRestore(vm)
  File "/usr/lib/python3.5/site-packages/qubesadmin/backup/restore.py", line 795, in __init__
    self.username = os.path.basename(subdir)
  File "/usr/lib64/python3.5/posixpath.py", line 139, in basename
    i = p.rfind(sep) + 1
AttributeError: 'NoneType' object has no attribute 'rfind'
```

### General notes:

Although an archive must contain a dom0 backup to produce the error, omitting dom0 from vm selection (only specifying appvms on the command line) has no effect.

---

#### Related issues:

#3303

**Comment by tasket** [comment]
I'm looking into a fix for this one, also.

**Comment by tasket** [comment]
@marmarek I think I have it fixed. Should I combine it with the other commits in PR#42?

https://github.com/QubesOS/qubes-core-admin-client/pull/42

**Comment by tasket** [comment]
Also, I ran into an anomaly in the VM listing when processing a dom0-bearing archive:
```
The following VMs are included in the backup:

--------+---------+----------+-----------+--------+
   name |    type | template |     netvm |  label |
--------+---------+----------+-----------+--------+
 temp10 |   AppVM |       d9 | wireguard | orange |
   dom0 | AdminVM |      n/a | (default) |  black |
   Dom0 |    Home |          |           |        |
```
Notice the extra entry for dom0. Its from the last code block in `get_restore_summary()` and I'm thinking it should be removed...?

**Comment by tasket** [comment]
PR here:
https://github.com/QubesOS/qubes-core-admin-client/pull/43

**Comment by andrewdavidwong** [comment]
Keeping this open for `github-builder` (unless we know we don't need it tracked for some reason).

**Comment by andrewdavidwong** [comment]
Never mind, looks like tracking works fine even if it's closed.
