### ISSUE TITLE
Update Signal Desktop Documentation

### ISSUE THREAD

**Issue by pierwill** [QubesOS/qubes-issues#3363]
The [documentation for Signal](https://www.qubes-os.org/doc/signal/) is now out of date with the new [non-Chrome Signal Desktop.](https://signal.org/download/) The doc can be condensed and revised.

**Comment by andrewdavidwong** [comment]
Updated: https://github.com/QubesOS/qubes-doc/commit/0a39381dd30a45dd5fd94099aedfec7ab8a6d524
