### ISSUE TITLE
Shut Down does not shut down the computer

### ISSUE THREAD

**Issue by tutaleedoo** [QubesOS/qubes-issues#3371]
#### Qubes OS version:

Qubes release 4.0 (R4.0)

#### Affected TemplateVMs: 

dom0

---

### Steps to reproduce the behaviour:

1. Open the `Applications` menu
2. Click `Log Out`
3. Click `Shut Down`

### Expected behaviour:

- The computer shuts down within seconds or minutes

### Actual behaviour:

- The computer doesn't shut down, even after waiting 8 hours

### General notes:

- After clicking `Shut Down`, a Qubes OS progress bar screen appears
- After about 3.5 minutes, the screen goes black, but the monitor stays on
- After that, nothing changes
- The computer must be shut down by holding its power button for a few seconds

---

**Comment by tutaleedoo** [comment]
This is no longer an issue after doing `sudo qubes-dom0-update` in dom0

**Comment by tutaleedoo** [comment]
Sorry, this is still happening. Reopening

**Comment by andrewdavidwong** [comment]
This appears to be a duplicate of #2957. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.
