### ISSUE TITLE
Cannot use keyboard after cancelling Log Out

### ISSUE THREAD

**Issue by tutaleedoo** [QubesOS/qubes-issues#3372]
#### Qubes OS version:

Qubes release 4.0 (R4.0)

#### Affected TemplateVMs: 

dom0

---

### Steps to reproduce the behaviour:

1. Open the `Applications` menu
2. Click `Log Out`
3. Click `Cancel`

### Expected behaviour:

- The keyboard remains usable (can still type)

### Actual behaviour:

- The keyboard becomes unusable (cannot type)

### General notes:

- To resolve the issue, the user must hold the computer's power button for a few seconds to shut down the computer, and then press the power button to start the computer

---

**Comment by andrewdavidwong** [comment]
Are you using a PS/2 or USB keyboard?

**Comment by tutaleedoo** [comment]
USB keyboard
