### ISSUE TITLE
Installed blueman fine, but it doesn't start.

### ISSUE THREAD

**Issue by NinjaTurtle007** [QubesOS/qubes-issues#3375]
#### Qubes OS version:

4 rc3

#### Affected TemplateVMs: 

dom0

---

### Steps to reproduce the behavior:

type in dom0 terminal:
sudo qubes-dom0-update blueman 

### Expected behavior:

To install blueman and to work when started from settings

### Actual behavior:

It installs blueman fine, but when started in settings, this broken window appears 
https://ibb.co/fkaZUb

### General notes:

---

**Comment by NinjaTurtle007** [comment]
Actually do I need to install something else other than "sudo qubes-dom0-update blueman" to have bluetooth?
Since I suppose the bluetooth stack is not existing at all in dom0?

After searching for days there is no tutorial at all for enabling bluetooth in qubes. And I can imagine that is reasonable compromise for many users.

**Comment by marmarek** [comment]
You should do that in the template on which your sys-usb is based (fedora-25 by default).

**Comment by NinjaTurtle007** [comment]
I was doing it in dom0, ok will try that
by the way, the bluetooth is built-in in the motherboard.

I also have USB bluetooth dongle, is there any difference? Which is easier?

**Comment by marmarek** [comment]
Should be the same - most (all?) built-in bluetooth devices in fact are USB devices (just soldered to the mainboard).

**Comment by esote** [comment]
@andrewdavidwong Unless @NinjaTurtle007 gives an update on running blueman in sys-usb, this issue can probably be closed using @marmarek's advice.

**Comment by esote** [comment]
@andrewdavidwong It's been over a year since a response has been made. From my comment above and the lack of response, should this issue be closed?

**Comment by andrewdavidwong** [comment]
Closing this for now due to the lack of response. If you revisit the matter in the future, or if anyone would like the issue to remain open, please leave a comment, and we'll be happy to reopen this. Thank you.

**Comment by mfp20** [comment]
I installed blueman in sys-net, because my bluetooth silicon is integrated in the wifi chip (Intel 8265 wifi+bt single chip). Sys-net is a fedora-30-mini built using the Builder, plus the qubes packages to make it work as net/firewall/usb templatevm. Then rebooted, and the result is:

```
$ sudo blueman-adapters
blueman-adapters version 2.1.1 starting
blueman-adapters 18.17.38 ERROR    Adapter:53 __init__  : No adapter(s) found
$ sudo hciconfig -a
$
```

I think there might be some firmware files missing from kernel. I'm currently using kernel-latest on dom0 and 4.19.94-1.pvops.qubes in sys.net. Any clue?

**Comment by marmarek** [comment]
Are you absolutely sure the device is present in sys-net? In great majority of cases the bluetooth controller is an usb device even if packaged on the same mPCIe card. Check in sys-usb first.

**Comment by mfp20** [comment]
@marmarek you're right. lsusb shows a bluetooth device in sys-usb.

**Comment by andrewdavidwong** [comment]
> @marmarek you're right. lsusb shows a bluetooth device in sys-usb.

Does this resolve the issue for you?

**Comment by mfp20** [comment]
@andrewdavidwong yep, thank you. I didn't have time to use bluetooth yet, but hciconfig can see the adapter.
