### ISSUE TITLE
(GUI enhancement) Policy question readability

### ISSUE THREAD

**Issue by svenssonaxel** [QubesOS/qubes-issues#3381]
#### Qubes OS version: R3.2

Some questions, e.g. about shutting down a VM, have the VM name in bold. This makes them easy and quick to read, especially for experienced users that recognize the question and only want to check that the VM names are correct.

Policy questions do not have this feature, but maybe they should?
I propose changing the policy question that currently reads for example:

> Do you allow domain "vm1" to execute qubes.Filecopy operation on the domain "vm2"?
> "Yes to All" option will automatically allow this operation in the future.

to be change to the more readable:

> Do you allow this RPC operation?
> Operation: **qubes.Filecopy**
> Executed by: **vm1**
> Target domain: **vm2**
> 
> "Yes to All" option will automatically allow this operation in the future.

**Comment by mirrorway** [comment]
Even better I think would be to drop the "Yes to all..." explanation and simply make the button text self-explanatory. Something like:

> Titlebar: [Dom0] RPC.request
>
> **vm1** wants to run **qubes.Filecopy** on **vm2**.
> 
> [Deny]              [Allow once] [Allow forever]

It seems much easier to parse.

**Comment by marmarek** [comment]
Done in policy dialog in 4.0
