### ISSUE TITLE
Security question - Intel ME / NSA / HAP - how is Qubes-OS targetting IME/HAP

### ISSUE THREAD

**Issue by P4z** [QubesOS/qubes-issues#3391]
I am not sure is this a good place to ask this kind of question but recently I found several articles about relations of Intel Management Engine with NSA and their HAP programme.

see:

- http://www.cs.vu.nl/~ast/intel/

-
 https://hardenedlinux.github.io/firmware/2016/11/17/neutralize_ME_firmware_on_sandybridge_and_ivybridge.html

- http://blog.ptsecurity.com/2017/08/disabling-intel-me.html

- http://fm.csl.sri.com/LAW/2009/dobry-law09-HAP-Challenges.pdf

Is or how is Qubes-OS targetting Intel Management Engine privacy issues?

**Comment by andrewdavidwong** [comment]
Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this does not appear to be suitable for `qubes-issues`. We ask that you please send this to the `qubes-users` [mailing list](https://www.qubes-os.org/mailing-lists/) instead. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a brief comment explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.
