### ISSUE TITLE
Apps installed in template don't always start in AppVM 4.0-rc3

### ISSUE THREAD

**Issue by JPL1** [QubesOS/qubes-issues#3397]
#### Qubes OS version:
4.0-rc3

#### Affected TemplateVMs: 

debian-8

---

### Steps to reproduce the behavior:

In the debian-8 terminal:
`$ nautilus`
nautilus opens

In a debian App-VM
`$ nautilus`

### Expected behavior:

Nautilus opens

### Actual behavior:

`bash: nautilus: command not found`

### General notes:

Reinstalling Nautilus in the template fixes this issue, so it's either a bug with the original debian-8 template or a one-off error with my installation. 

---

**Comment by unman** [comment]
@andrewdavidwong I have never been able to reproduce this, and I dont understand how the template cant be mirrored in the TemplatebasedVM without user intervention.
I dont believe there was a issue with the original template, (although nautilus is now included in the default stretch template), which leaves "a one-off error with my installation."
I suggest closing.
