### ISSUE TITLE
Debian-8 /home not mounted resulting in no display :0

### ISSUE THREAD

**Issue by niccokunzmann** [QubesOS/qubes-issues#3398]
#### Affected TemplateVMs: 

debian-8 but this only affects my app VM and not the corresponding template.

---

### Steps to reproduce the behavior:

I start a debian-8 app vm "personal-3" .
Then, I try to open a program.

    qvm-run --pass personal-3 xterm

Resulting in 

    xterm: Xt error: Can't open display: :0

Also, 

    qvm-run --pass-personal 'ls /home'

shows an empty home directory

### Expected behavior:

- I would like to see the xterm console open as a separate window.
- No error in the vm start log, see below

### Actual behavior:

When I type

    sudo xl console personal-3

I can see

```
[FAILED] Failed to start Initialize and mount /rw and /home
```
I log in as user without password. And run:
```
systemctl status qubes-mount-dirs.service
```
This is the service producing the failure message.

I note that:

1. `/rw` has successfully been mounted. Among other folders, it contains the `/home` folder.
2. `/home` has not been mounted. It is empty.

### General notes:

To fix this problem, I can do two things:

1. Mount `/home` using `sudo mount /home` - it was prepared before and the command works to populate `/home`
2. Restart the gui agent `sudo systemctl restart qubes-gui-agent.service`

Now, `/home` is mounted and I can open programs like firefox and xterm. 

---

#### Related issues:

- https://github.com/QubesOS/qubes-issues/issues/1095 - this issue helped me find the bug

**Comment by unman** [comment]
Interesting, I've not seen this. 
Have you made any changes to the template? If so, if you change back to the vanilla debian-8 template, does the appVM start with mounted /home then?
If you create a new appVM based on the same template does it show the same behaviour?

Is there anything relevant in the logs? Particularly relating to mount-dirs.sh?

**Comment by niccokunzmann** [comment]
> Have you made any changes to the template?

Yes, I have. I installed some software and added new users in the
template vm.

> If so, if you change back to the vanilla debian-8 template, does the
appVM start with mounted /home then?

Yes, it should.

> If you create a new appVM based on the same template does it show the
same behaviour?

If I create a new app vm with a plain private storage, everything seems
to work fine. So, no not the same behavior.

> Is there anything relevant in the logs? Particularly relating to
mount-dirs.sh?

Where can I see the logs?

**Comment by unman** [comment]
>  If so, if you change back to the vanilla debian-8 template, does the
> appVM start with mounted /home then?

> Yes, it should.

Yes, but does it?


> Where can I see the logs?

`journalctl -b`

**Comment by niccokunzmann** [comment]
The **solution** for me is to put these commands in /etc/rc.local, since this is executed after mount:

    mount /home
    systemctl restart qubes-gui-agent.service

So, we can close the issue from my side.

**Comment by niccokunzmann** [comment]
@unman I created a new app vm and it works fine. The problem and difference seems to be with my personal mount point in /rw.
