### ISSUE TITLE
Networlk does not work

### ISSUE THREAD

**Issue by davejones444** [QubesOS/qubes-issues#3400]
#### Qubes OS version:

Qubes 3.2

#### Affected TemplateVMs: 

All.

---

### Steps to reproduce the behavior:

I made a custom install.

### Expected behavior:

Wireless working for all VMs.

### Actual behavior:

No connection.

### General notes:

I wish the documentation was more comprehensive. The Installation guide only covers creating the media. Where's the rest?

---

**Comment by andrewdavidwong** [comment]
Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this does not appear to be suitable for `qubes-issues`. We ask that you please send this to the `qubes-users` [mailing list](https://www.qubes-os.org/mailing-lists/) instead. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a brief comment explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.
