### ISSUE TITLE
fedora-26 TemplateVM does not work with 4.14 kernel.

### ISSUE THREAD

**Issue by dakka2** [QubesOS/qubes-issues#3404]
#### Qubes OS version:
r4.0

#### Affected TemplateVMs: 
fedora-26

### Steps to reproduce the behavior:
upgrade to kernel 4.14

### Expected behavior:
guest boots. 

### Actual behavior:
guest does not boot

### General notes:
it seems like either a 4.14 upstream issue or a u2mfn issue
[https://ptpb.pw/tV7v](https://ptpb.pw/tV7v)

**Comment by 0spinboson** [comment]
just f26?

**Comment by dakka2** [comment]
I assume it would be anything using qubes-kernel-vm-support and 4.14.

**Comment by HW42** [comment]
It's an upstream Linux bug. See https://github.com/HW42/qubes-linux-kernel/blob/hw42/latest/patches.xen/xen-Fix-set-clear-_foreign_p2m_mapping-on-autotransl.patch for a patch.

**Comment by dakka2** [comment]
Will this get upstreamed so fedora will work without a custom compiled kernel?

**Comment by HW42** [comment]
I already [reported](https://lists.xenproject.org/archives/html/xen-devel/2018-01/msg00411.html) it upstream. It might of course take a bit till it lands in a release.

**Comment by andrewdavidwong** [comment]
Closing as `notourbug`. If anyone believes this is a mistake, please leave a comment, and we'll be happy to take another look at this. Thank you.
