### ISSUE TITLE
qubes-dom0-update cumulative rpm size quota

### ISSUE THREAD

**Issue by xaki23** [QubesOS/qubes-issues#3408]
#### Qubes OS version:

R4-RC3

#### Affected TemplateVMs: 

---

### Steps to reproduce the behavior:

install RC3
install fedora-26 template (works)
install fedora-26-minimal template
fails horribly with some quota-exceeded message after downloading

the problem here is the total sum of downloaded-since-last-reboot rpms in the updatevm cache exceeds 2GB (arbitrary limit enforced somewhere in the chain)
the step of pulling the rpms from updatevm to dom0 allway pulls _all_ RPMs in the cache (instead of just the one(s) it cares about), a hardcoded something/*.rpm 
and it seems the cache is not expired after a successful install

### Expected behavior:

being able to install multiple huge rpms (like templates) in dom0

### Actual behavior:

installation failing when reaching a cumulative rpm size limit

### General notes:

workarounds: 
restart updatevm to clean cache
manual cleanup of rpms in updatevm (dont miss the second copy in the tree)
passing --clean to qubes-dom0-update (and downloading all the repo metadata again)

---

**Comment by najamelan** [comment]
Note that the documentation already mentions this:

> Disk Quota Exceeded (When Installing Templates)
> 
> If you install multiple templates you may encounter this error. The solution is to shut down the updateVM between each install:
> 
> install template and shutdown updateVM:
>   cmd.run:
>   - name: sudo qubes-dom0-update -y fedora-24; qvm-shutdown {{ salt.cmd.run(qubes-prefs updateVM) }}

I can confirm this workaround:
Go into the updateVM and delete unneeded rpms in both:
/var/lib/qubes/dom0-updates/packages
/var/lib/qubes/dom0-updates/var/cache/yum/x86_64/4.0/qubes-templates-itl-fd404fe04a5ff777/packages

**Comment by anon8675309** [comment]
I ran into this same problem on 4.0.3rc1.  Using the `--clean` option worked around it.  Just wanted to report that the workaround is still necessary even with the latest release candidate so people are aware of the status.

**Comment by chrissyn** [comment]
I ran into this issue on 4.1 while installing the kali template. Using `--clean` does not work for me.

**Comment by brendanhoar** [comment]
Perhaps when installing Qubes the sys-firewall volume sizes should be adjusted to reduce/eliminate this issue for most users. For the default of LVM this doesn’t really take up more room unless the user utilizes it.
