### ISSUE TITLE
debian-9 template installation errors

### ISSUE THREAD

**Issue by xaki23** [QubesOS/qubes-issues#3409]
#### Qubes OS version:

R4-RC3

#### Affected TemplateVMs: 

debian-9

---

### Steps to reproduce the behavior:

install RC3
install debian-9 template

during "Importing data" step in qvm_template_postprocess i get two tracebacks
first it explodes with a shutdown_timeout
then it gets a "Domain is powered off" when trying to kill the vm

perhaps something with the wait-for-shutdown process?
the machine is reasonably beefy, no idea what may be slow.

### Expected behavior:

less than one screen of python stacktraces during template installation

### Actual behavior:

more than one screen of python stacktraces during template installation

### General notes:

unsure in what condition the installed template is

---

**Comment by tasket** [comment]
This looks like a side-effect of issue #2913 . If so, you could try the workaround there, then go into Settings window / Apps and click Refresh Apps and then the template should be fine.

**Comment by xaki23** [comment]
not sure how i would try a workaround that involves manual removal of files as part of the template-package installation process. 
but i agree, that smells related. 
after reading #2913 i am unsure if there is already a fixed template-package available (and if so, how i would summon it.)

**Comment by tasket** [comment]
@xaki23 - Is the template available via `qvm-run`? Wait 2 minutes after starting the template, then run a terminal and remove the @service link.

**Comment by xaki23** [comment]
hm. 
my report was about errors during the "sudo qubes-dom0-update qubes-template-debian-9" step.
as in, the actual template installation process, not trying to do anything with it yet.

**Comment by tasket** [comment]
Yes, the post install script starts the template and runs scripts within it.

**Comment by marmarek** [comment]
Since #2913 is fixed, this should be gone too. If not, please leave a comment to reopen.
