### ISSUE TITLE
qrexec-agent do not setup process environment correctly

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#3416]
#### Qubes OS version:

R4.0

#### Affected TemplateVMs: 

all

---

### Steps to reproduce the behavior:

From dom0:
```
qvm-run -p -u root personal 'pwd'
qvm-run -p -u root personal 'echo HOME: $HOME'
qvm-run -p -u root personal 'echo USER: $USER'
```

### Expected behavior:

Process started in user home, with appropriate environment set.
```
/root
HOME: /root
USER: root
```

### Actual behavior:

Process started without standard environment variables, with `/` as working directory.
```
/
HOME:
USER:
```

**Comment by najamelan** [comment]
Just for your information. I can't reproduce this entirely. Between:

sys-net     python3-dnf-plugins-qubes-hooks.x86_64  4.0.14-1.fc26
fedora-26 python3-dnf-plugins-qubes-hooks.x86_64  4.0.15-1.fc26

after updating fedora-26 template, but before rebooting sys-net. The pwd in sys-net reacts as reported in this issue, but $HOME and $USER are correct. A simpler way to compare is just to call `env`.

There is another environment bug, but I'll file a new issue in a minute.
