### ISSUE TITLE
Tom Zander's Qubes Controller

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#3417]
This is a [tracking issue](https://www.qubes-os.org/qubes-issues/) for @zander's open-source GUI for Qubes 4. For more information, please see the following:

* [qubes-devel discussion](https://groups.google.com/d/topic/qubes-devel/oMo9YvCFC9I/discussion)
* [qubes-users discussion](https://groups.google.com/d/topic/qubes-users/PGpoN5hrOeE/discussion)

**Comment by zander** [comment]
Github repos created and open source code uploaded;

https://github.com/QubesController/qubes-api-cpp-lib

https://github.com/QubesController/qubes-controller

Some screenshots and new email-thread; https://groups.google.com/forum/#!msg/qubes-devel/dT1JnmzjDWc/RiEawvn_DgAJ

**Comment by zander** [comment]
Please close this task.
