### ISSUE TITLE
Unable to boot/install any StandaloneVM

### ISSUE THREAD

**Issue by msbrudo** [QubesOS/qubes-issues#3419]
#### Qubes OS version:

Qubes release 4.0  (R4.0)

#### Hardware 
Lenovo Thinkpad x220 i7-2620M (with ME stripped from bios)
##### qubes-hcl-report
```
HVM: Active
I/O MMU: Active
HAP/SLAT: Active
TPM: Device present
Remapping: yes
```

---

##### Using CLI
`qvm-create xp --class StandaloneVM --label green`
`qvm-start --cdrom dom0:/home/mydom0user/windows_xp.iso`

The virtual machine console starts but close itslef right after the SeaBIOS message

```
Booting from ROM
Probing EDD
```

The same happens with any other ISO (example: netbsd)

I was unable to find any related error in my journalctl.

### Expected behavior:

The HVM should boot the iso and show the operating system installer.

### Actual behavior:

The HVM console turn off just after the post message.

### General notes:

---

#### Related issues:
The error descripted in the following link happend when i try the same procedure using the GUI.
[https://groups.google.com/forum/#!topic/qubes-users/zOSliFdOQTY](https://groups.google.com/forum/#!topic/qubes-users/zOSliFdOQTY)

**Comment by marmarek** [comment]
Set `kernel` property to none:
```
qvm-prefs xp kernel ''
```
Then, you'll probably hit #3339, which is fixed in qubes-core-dom0-4.0.15, just uploaded to current-testing repository.
