### ISSUE TITLE
Root image file parameter to qvm-create limited to free space in /tmp (2GiB)

### ISSUE THREAD

**Issue by daniel-ayers** [QubesOS/qubes-issues#3422]
#### Qubes OS version:

4.0RC3

#### Affected TemplateVMs: 

dom0

---

### Steps to reproduce the behavior:

in dom0:
```
# qvm-create --label=yellow -C StandaloneVM --root-move-from /var/tmp/root.img newvm
....
OSError: [Errno 28] No space left on device
```

### Expected behavior:

New VM created using given root image file (in my example, 40GiB raw image).

### Actual behavior:

qvm-create pipes root image file to a temp file in /tmp and therefore runs out of space on /tmp if root.img > 2GiB.

Same behaviour regardless for --root-copy-from and --root-move-from

### General notes:

The root.img I am using was converted vdi -> raw using qemu-img -O raw.

Given the semantics implied by both --root-copy-from and --root-move-from it does not appear necessary to write any file to /tmp.

---

**Comment by marmarek** [comment]
The file is not piped to /tmp, but to the target location (LVM volume in default installation). The problem is somewhere else - it does not check its size and by default root volume have 10G. It should resize it first to the size of source file.
