### ISSUE TITLE
qubes-builder / refuse to accept qube gpg master key

### ISSUE THREAD

**Issue by ThierryIT** [QubesOS/qubes-issues#3423]
#### Qubes OS version: 3.2

I am trying to built  an ubuntu template from fedora-26.
When running the command "setup" the system tell me that: Qubes master signing key doesn't exist , do you want to intall it: yes/no ... I say Y, it hang for a moment, and say:

RAN: /usr/bin/gpg --keyserver pgp.mit.edu --recv key xxxxx79494
STOUT:

1) this key has already been installed, I can see it when doing the --list-key
2) even if I do remove it, still the same issue
3) I have changed the keyserver: same issue
4) qubes-builder has been installed with "git" today.

Thx 

---

### Steps to reproduce the behavior:

./setup

### General notes:

---

**Comment by marmarek** [comment]
It uses separate keyring in keyrings/git, check if it is there:
gpg --homedir keyrings/git --list-key

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by ThierryIT** [comment]
Hello,
keyring/git/pubring.gpg file open error
no such file or directory.

**Comment by unman** [comment]
@ThierryIT Have you resolved this?
It works for me on a clean clone with Fedora-26.

How was your build qube connected to net? Were you using Whonix/Tor?
If you manually fetch the key from command line using -v option what is the result?

**Comment by Deedasmi** [comment]
I had this issue. Bad file permissions on qubes-builder/keyrings/git (777). Ran chmod 700 on the folder and manually imported the key to continue the setup process.

**Comment by unman** [comment]
@andrewdavidwong Works for me. I suggest closing as stale given lack of response.
