### ISSUE TITLE
Fedora 25 has reached EOL

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#3429]
Fedora 25 reached EOL on 2017-12-12 and is no longer receiving security updates. We need:
 - [x] A `fedora-26` template available in the Qubes Templates repo
 - [x] Documentation for upgrading from F25 to F26 (like [the previous one for upgrading from F24 to F25](https://www.qubes-os.org/doc/template/fedora/upgrade-24-to-25/))
 - [x] Announcements notifying users F25 has reached EOL and that they should download or upgrade to F26 immediately (see [the previous one about F25](https://www.qubes-os.org/news/2017/07/29/fedora-25-upgrade/))

@marmarek, do you want to handle the second item, then I'll do the third?

**Comment by andrewdavidwong** [comment]
@marmarek: I've submitted F25->F26 upgrade instructions for your review in https://github.com/QubesOS/qubes-doc/pull/505.

**Comment by kirill9000** [comment]
These upgrades are a pain and always late (i.e. significantly after EOL). Seems to me that Fedora's support cycle is way too short for Qubes. Why don't you switch to Debian as default template VM (or at least for sys-VMs)?

**Comment by andrewdavidwong** [comment]
> These upgrades are a pain and always late (i.e. significantly after EOL).

They're a pain, but I think this is the first time we've been late to announce it (at least in a long time). For example, we announce F23->F24 and F24->F25 well before each of those EOLs:

https://www.qubes-os.org/news/2016/11/15/fedora-24-template-available/
https://www.qubes-os.org/news/2017/07/29/fedora-25-upgrade/

> Seems to me that Fedora's support cycle is way too short for Qubes. Why don't you switch to Debian as default template VM (or at least for sys-VMs)?

We'll be addressing this point shortly.

**Comment by andrewdavidwong** [comment]
Announcement created: https://github.com/QubesOS/qubes-posts/commit/bf09db904db85f3c7788bff43bf99df9ec27cfa3

**Comment by kirill9000** [comment]
>I think this is the first time we've been late to announce it (at least in a long time)

Yeah, I guess I was wrong about that. Sorry. But what about the Debian question?

**Comment by andrewdavidwong** [comment]
> Yeah, I guess I was wrong about that. Sorry. But what about the Debian question?

As I said above, we'll be addressing that point shortly.
