### ISSUE TITLE
VMs have no config files / StandaloneVM from ISO (win) shuts down on logo

### ISSUE THREAD

**Issue by OldloratH** [QubesOS/qubes-issues#3432]
#### Qubes OS version:

Qubes release 4.0 (R4.0-rc3) 

#### Affected VMs: 

StandaloneVM from iso (Windows)

### Steps to reproduce the behavior:

qvm-create win --class StandaloneVM --label blue
qvm-prefs win kernel ''
sudo qvm-start win --cdrom=dom0:<path to .iso>

### Expected behavior:

- Windows installation process OR
- Stuck at logo, issue https://github.com/QubesOS/qubes-issues/issues/2488

### Actual behavior:

- VM shuts down
- No config file under var/lib/qubes/apvms/win

### General notes:

- The VM shuts down on win logo
- None of the VMs have config files under var/lib/qubes/appvms, only icon.png files so I cannot change the VM  video driver from 'xen' to 'cirrus'

#### Related issues:

https://github.com/QubesOS/qubes-issues/issues/2488

**Comment by marmarek** [comment]
Try installing updates from current-testing repository, very similar bug is fixed there.

**Comment by OldloratH** [comment]
I did beforehand, 'sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing' finds everything up to date.

**Comment by marmarek** [comment]
Are you sure the path is correct? You should put a full path there, not relative one.
I've just tried on fully updated system, and got windows (10) logo for about half a minute, then VM shuts down. Is is the same, or your shuts down earlier?

As for the config file, see PR linked above, you can apply this modification manually to /usr/share/qubes/templates/libvirt/xen.xml

**Comment by OldloratH** [comment]
Yes, the windows logo stays for about half a minute before shutting down.

/usr/share/qubes/templates/libvirt/xen.xml has a section:
<video>
    <model type="vga"/>
</video>
I tried changing the "vga" to "cirrus" and redoing the steps however no changes.

**Comment by marmarek** [comment]
Try increasing memory, for example to 2048M. For me this fixed the problem.

**Comment by OldloratH** [comment]
Increasing the initial memory fixed the issue, thank you @marmarek.
