### ISSUE TITLE
'installed_by_rpm' is False after template installation

### ISSUE THREAD

**Issue by tasket** [QubesOS/qubes-issues#3435]
#### Qubes OS version:

R4.0-rc3

#### Affected TemplateVMs: 

debian-8, debian-9, fedora-26, fedora-26-minimal, whonix-gw, whonix-ws, more?

---

### Steps to reproduce the behavior:

Use `qubes-dom0-update` to install a template.

### Expected behavior:

```
$ qvm-prefs debian-9 installed_by_rpm
True
```

### Actual behavior:

```
$ qvm-prefs debian-9 installed_by_rpm
False
```

### General notes:

This contributes to a problem where a user can remove an rpm-installed template through CLI/GUI tools.

---

#### Related issues:

#3129

**Comment by tasket** [comment]
PR https://github.com/QubesOS/qubes-core-admin-client/pull/44

**Comment by tasket** [comment]
PR was merged.

**Comment by andrewdavidwong** [comment]
Keeping this open for `github-builder` (unless we know we don't need it tracked for some reason).

**Comment by andrewdavidwong** [comment]
Never mind, looks like tracking works fine even if it's closed.
