### ISSUE TITLE
qvm-backup-restore fails to set netvm and dispvm if those are already installed and in the backup

### ISSUE THREAD

**Issue by o-** [QubesOS/qubes-issues#3439]
#### Qubes OS version:

4.0-rc3

#### Affected TemplateVMs: 

any

---

### Steps to reproduce the behavior:

qvm-prefs --set app-vm netvm sys-vpn
qvm-backup backup-file app-vm sys-vpn
qvm-remove app-vm
qvm-restore-backup backup-file app-vm

### Expected behavior:

app-vm has sys-vpn as the netvm

### Actual behavior:

Error setting app-vm.netvm to sys-vpn1: "No such domain sys-vpn1"

Also, the netvm get's set to the default one.

### General notes:

It seems that the to be restored name of sys-vpn is assumed to be sys-vpn1 (since sys-vpn exists in the backup and on the system) even though it is not being restored.

The exact same issue exists for dispvm.

It's a bit of a nasty corner case, and I am not even sure what the expected behavior is. To be honest it seems to me the auto-renaming feature is not very well thought out. My suggestion would be to remove it, or make it explicit (ie. letting the user choose a new name).

---

**Comment by tasket** [comment]
If the intention is to prevent automatically connecting restored vms outside of the backup set, then it may be expedient and safe to have qvm-backup-restore set the netvm as 'none' and print a notice. This is as an alternative to re-working the renaming code.
