### ISSUE TITLE
Qubes-Whonix 14 build issues

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#3441]
```
DEBIANVERSION="stretch" \
DIST="stretch" \
DISTS_VM="whonix-gateway whonix-workstation" \
COMPONENTS="linux-template-builder builder builder-debian template-whonix" \
BUILDER_PLUGINS="builder-debian template-whonix" \
USE_QUBES_REPO_VERSION=3.2 \
USE_QUBES_REPO_TESTING=1 \
VERBOSE=3 \
DEBUG=1 \
REPO_PROXY=http://127.0.0.1:3142 \
BRANCH_template_whonix=master \
GIT_URL_template_whonix=https://github.com/adrelanos/qubes-template-whonix.git \
make get-sources template --debug=v
```

qubes-builder git `b31f5e2c8de679ab29d7f00d435d6276e83d8c57`

```
Reading makefiles...
Reading makefile 'Makefile.generic'...
Reading makefile 'qubes-src/builder-debian/Makefile.builder' (search path) (don't care) (no ~ expansion)...
Reading makefile 'qubes-src/template-whonix/Makefile.builder' (search path) (don't care) (no ~ expansion)...
Reading makefile 'qubes-src/vmm-xen/Makefile.builder' (search path) (no ~ expansion)...
Reading makefile '/home/user/qubes-builder/qubes-src/builder-debian/Makefile.debian' (search path) (no ~ expansion)...
 DEBUG 
 Repo Variables
───────────────────────────────────────────────────────────────────────────────
 SRC_DIR:             qubes-src
 CHROOT_DIR:          /home/user/qubes-builder/chroot-jessie
 CHROOT_REPO_DIR:     chroot-debian
 CHROOT_DEBIAN_DIR:   /home/user/qubes-builder/chroot-jessie//debian-vm/debian
 BUILDER_REPO_DIR:    /home/user/qubes-builder/qubes-packages-mirror-repo/jessie
───────────────────────────────────────────────────────────────────────────────
 Chroot Variables
───────────────────────────────────────────────────────────────────────────────
 DIST_BUILD_DIR:      /home/user
 DIST_SRC:            
 DIST_SRC_DEBIAN_DIR: /debian-vm/debian
───────────────────────────────────────────────────────────────────────────────
 Build Variables
───────────────────────────────────────────────────────────────────────────────
 DEBIAN_PARSER:       /home/user/qubes-builder/qubes-src/builder-debian//scripts/debian-parser
 DEBIAN_PLUGIN_DIR:   /home/user/qubes-builder/qubes-src/builder-debian/
 OUTPUT_DIR:          pkgs/jessie
 PACKAGE_LIST:        debian-vm/debian
 DISTRIBUTION:        debian
 DIST:                jessie
 DEBIANVERSION:       jessie
 UPDATE_REPO:         /home/user/qubes-builder/qubes-src/linux-template-builder/pkgs-for-template/jessie
 REPO_SUFFIX:         
 DISTRIBUTION_CAP:    Debian
 REPO_PROXY:          http://127.0.0.1:3142
 APT_GET_OPTIONS:     -o Acquire::http::Proxy=http://127.0.0.1:3142
 CHROOT_ENV:          BACKEND_VMM=xen 

Updating goal targets....
Considering target file 'update-repo'.
 File 'update-repo' does not exist.
  Considering target file 'update-repo-prepare'.
   File 'update-repo-prepare' does not exist.
   Finished prerequisites of target file 'update-repo-prepare'.
  Must remake target 'update-repo-prepare'.
You must provide a proper filename containing debian package file
mkdir: cannot create directory ‘chroot-debian’: File exists
mount: mount point chroot-debian/tmp/qubes-deb does not exist
/home/user/qubes-builder/qubes-src/builder-debian/Makefile.debian:275: recipe for target 'update-repo-prepare' failed
make[1]: *** [update-repo-prepare] Error 32
Makefile:297: recipe for target 'template-local-jessie+whonix-gateway+minimal+no-recommends' failed
make: *** [template-local-jessie+whonix-gateway+minimal+no-recommends] Error 
```

How to set from `jessie` to `stretch`?

```
How to fix that error? You must provide a proper filename containing debian package file
mkdir: cannot create directory ‘chroot-debian’: File exists
mount: mount point chroot-debian/tmp/qubes-deb does not exist
```

(Deleted that `chroot-debian` folder to no avail.)

**Comment by marmarek** [comment]
You should not set `DIST` directly, it should be derived from `DISTS_VM` by qubes-builder (based on `TEMPLATE_ALIAS` set in `qubes-src/template-whonix/builder.conf`.
Make sure you have `builder.conf` with basic settings, but do not override those on command line. Safe thing to do is to use `?=` instead of `=` in builder.conf.

After fixing above two things, it works for me on fresh qubes-builder clone (after adding your key). Including using stretch.

It looks like internal `COMPONENT` variable is empty for some reason. It should be derived from `COMPONENTS` (iterate over its elements). Make sure you don't override that either.

**Comment by marmarek** [comment]
Later in the process I've got this error while "Setting up whonix-repository (3:3.2-1)":
```
/usr/bin/whonix_repository: line 85: lsb_release: command not found
```

**Comment by adrelanos** [comment]
Marek Marczykowski-Górecki:
> Later in the process I've got this error while "Setting up whonix-repository (3:3.2-1)":
> ```
> /usr/bin/whonix_repository: line 85: lsb_release: command not found
> ```
> 

Was a missing dependency on lsb-release. Now fixed.

**Comment by adrelanos** [comment]
I don't manage to build it. Ruining from one error into another. It's undocumented, tons of  `make` code. Would take me ages to figure out.

Suppose a debian-9 VM (preferred) or fedora-26 VM on Qubes R4.

Could you please kindly provide a one liner or script to build Qubes-Whonix 14 / R4 that includes builder.conf and whatnot?

**Comment by marmarek** [comment]
1. Clone qubes-builder
2. Place [this](https://gist.github.com/marmarek/495552b34de6da59a9df91f9e8e7e23a) as `builder.conf`
3. Execute `make get-sources`
4. Execute `make template` or `make template-in-dispvm` according to your wish.

It is important that `get-sources` and `template` are separate make calls. You can join them using `&&` if you like.

**Comment by awokd** [comment]
@adrelanos , trying the build per the above steps.

**Comment by awokd** [comment]
Build successful:
~~~
+ exit 0
template_list: qubes-template-debian-9 
qubes-template-fedora-25 
qubes-template-fedora-26 
qubes-template-whonix-gw 
qubes-template-whonix-ws 
Use the following command in DOM0 to retreive this file:
qvm-run --pass-io dev26 'cat /home/user/qubes-builder/qubes-src/linux-template-builder/rpm/install-templates.sh' > install-templates.sh
~~~
So it should work fine in a full build too.

**Comment by adrelanos** [comment]
Kept some notes here, no more than a scratch pad, but I appreciate your efforts to get it really documented on qubes-os.org.

https://www.whonix.org/wiki/Dev/Qubes#Build_Qubes-Whonix_Templates_-_New_New

Thanks @marmarek, that helped a lot! Me happy building now! :)

**Comment by awokd** [comment]
@adrelanos Once Qubes-Whonix 14 is in "shipping" status, did you want me to write up a new doc on how to build the templates inside Qubes? I've been trying to avoid stepping on people's toes and also skipping docs outside my area of expertise, but I should be able to handle that if you like.

**Comment by adrelanos** [comment]
Help very much welcome!

**Comment by awokd** [comment]
@adrelanos Is [this](https://github.com/awokd/qubes-doc/blob/whonixtempl/building/building-whonix-template.md) what you had in mind? The Build Environment link is pending another PR.
(And is there a better place/preferred way to contact you on this item than in a closed issue? Not sure what's customary.)

**Comment by adrelanos** [comment]
Yes.

I personally don't like / use `./setup`, more generally gui tools for building. Looks magic. Troublesome experience. But it's not up to me to decide. If it works and enables other/more people to build Qubes-Whonix, that's fantastic!

Since it is a new documentation page, I guess a new Qubes ticket would be ok.

Also I am replying to all requests where I am highlighted. Unless I miss an e-mail notification which happens rarely. In that case feel free to ping me.
