### ISSUE TITLE
fedora-26 template package conflicts, broken dependencies 

### ISSUE THREAD

**Issue by mossy-nw** [QubesOS/qubes-issues#3442]
#### Qubes OS version:

R3.2

#### Affected TemplateVMs: 

fedora-26

---

### Steps to reproduce the behavior:

1. install fedora 26 from dom0 terminal: `sudo qubes-dom0-update qubes-template-fedora-26`

2. (A) update fedora 26 using the Qubes VM Manager "Update VM system" button _or_ (B) from a fedora-26 terminal:`sudo dnf update`

### Expected behavior:

all packages should update:
(A) from the Qubes VM Manager _or_
(B) from a terminal window in the fedora-26 template

### Actual behavior:

(A) from the Qubes VM Manager, nothing updates, throws error re: conflicts / broken dependencies (see below) _or_
(B) from the fedora-26 terminal, new/updated packages are installed except for:

```
packages with conflicts:
 dnf-plugins-core       noarch       2.1.1-1.fc26           fedora         49 k
 dnf-utils              noarch       2.1.1-1.fc26           fedora         39 k
 dnf-utils              noarch       2.1.5-1.fc26           updates        40 k
packages with broken dependencies:
 salt                   noarch       2017.7.2-1.fc26        updates       7.8 M
 salt-ssh               noarch       2017.7.2-1.fc26        updates        21 k

```

### General notes:

for packages with conflicts: is `add '--best --allowerasing' to command line to force their upgrade` a good idea?

---

#### Related issues:

#3429

**Comment by andrewdavidwong** [comment]
> for packages with conflicts: is `add '--best --allowerasing' to command line to force their upgrade` a good idea?

That's what I did, and it worked for me. If you don't want to do that, you can instead just download the prebuilt Fedora 26 templates:

```
$ sudo qubes-dom0-update qubes-template-fedora-26
$ sudo qubes-dom0-update qubes-template-fedora-26-minimal
```

Related threads:
* https://groups.google.com/d/topic/qubes-users/pD4KV9hOYhQ/discussion
* https://groups.google.com/d/topic/qubes-users/th7dTlIB9WA/discussion

**Comment by andrewdavidwong** [comment]
Filing this as a documentation task to be explained in the F25->F26 upgrade instructions.

**Comment by mossy-nw** [comment]
thanks! indeed that worked, but strangely was required for the fresh, prebuilt template installed (as above): 
`$ sudo qubes-dom0-update qubes-template-fedora-26`

This also removes the package `yum-utils.noarch 1.1.31-512.fc26`, I hope that won't be a problem!  But all seems fine now, I'm happy to add `sudo dnf update --best --allowerasing` to the docs.

Just a final note that a fresh template not updating properly straight off might be confusing for some users (esp. those relying exclusively on the GUI).  The GUI error message also gives no indication how to fix:
```
Problem 1: package salt-2017.7.2-1.fc26.noarch requires dnf-utils, but none of the providers can be installed
  - package dnf-utils-2.1.5-1.fc26.noarch conflicts with yum-utils < 1.1.31-513 provided by yum-utils-1.1.31-512.fc26.noarch
  - package dnf-utils-2.1.1-1.fc26.noarch conflicts with yum-utils < 1.1.31-513 provided by yum-utils-1.1.31-512.fc26.noarch
  - cannot install the best update candidate for package yum-utils-1.1.31-512.f26.noarch
  - cannot install the best update candidate for package salt-2016.11.5-3.fc26.oarch
 Problem 2: problem with installed package yum-utils-1.1.31-512.fc26.noarch
  - package dnf-utils-2.1.5-1.fc26.noarch conflicts with yum-utils < 1.1.31-513provided by yum-utils-1.1.31-512.fc26.noarch
  - package salt-2017.7.2-1.fc26.noarch requires dnf-utils, but none of the proiders can be installed
  - package dnf-utils-2.1.1-1.fc26.noarch requires dnf-plugins-core = 2.1.1-1.f26, but none of the providers can be installed
  - package salt-ssh-2017.7.2-1.fc26.noarch requires salt = 2017.7.2-1.fc26, bu none of the providers can be installed
  - cannot install both dnf-plugins-core-2.1.1-1.fc26.noarch and dnf-plugins-coe-2.1.5-1.fc26.noarch
  - cannot install the best update candidate for package salt-ssh-2016.11.5-3.f26.noarch
  - cannot install the best update candidate for package dnf-plugins-core-2.1.5-1.fc26.noarch
```

**Comment by andrewdavidwong** [comment]
@mossy-nw:
> thanks! indeed that worked, but strangely was required for the fresh, prebuilt template installed (as above):
> `$ sudo qubes-dom0-update qubes-template-fedora-26`

Oh, so that doesn't avoid it then. My mistake.

> This also removes the package `yum-utils.noarch 1.1.31-512.fc26`, I hope that won't be a problem!

Probably not, but I'm letting @marmarek review it first just in case.

> But all seems fine now, I'm happy to add `sudo dnf update --best --allowerasing` to the docs.

The new doc doesn't exist yet, so I've gone ahead and added it to https://github.com/QubesOS/qubes-doc/pull/505.

Thanks!

**Comment by marmarek** [comment]
On Fri, Jan 05, 2018 at 06:23:06AM +0000, Andrew David Wong wrote:
> @mossy-nw:
> > thanks! indeed that worked, but strangely was required for the fresh, prebuilt template installed (as above):
> > `$ sudo qubes-dom0-update qubes-template-fedora-26`
> 
> Oh, so that doesn't avoid it then. My mistake.

This is fixed in template builder
(https://github.com/QubesOS/qubes-builder-fedora/pull/15), but I haven't
rebuild the template yet.

> > This also removes the package `yum-utils.noarch 1.1.31-512.fc26`, I hope that won't be a problem!
> 
> Probably not, but I'm letting @marmarek review it first just in case.

It's ok.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by andrewdavidwong** [comment]
Reopening as a task for @marmarek to rebuild the template.
