### ISSUE TITLE
[UEFI-Only] Installer not starting, troubleshooting didn't solve the issue

### ISSUE THREAD

**Issue by myrage2000** [QubesOS/qubes-issues#3444]
#### Qubes OS versions :
3.2 and 4.0-RC3

---

### Steps to reproduce the behavior :
My new Thinkpad laptop is UEFI-Only, Secure-boot is disabled.
My .iso checksum is valid.
I'm booting from a USB key made with livecd-tools on Fedora (according to the troubleshooting guide for Lenovo's).
I added /mapbs /noexitboot and --efi=attr=uc to chainloader (I tried all possibilities).
Grub is booting.

### Expected behavior :
When entering "Install", Xen should boot and Anaconda should start.

### Actual behavior :
Nothing is happening when I enter "Install" (the screen goes black for less than 1 second and grub restarts).

### General notes :
I tried to boot xen.efi directly, but it's not working (the laptop freezes at "initrd.img").

**Comment by marmarek** [comment]
Have you tried booting xen.efi directly _and_ adding /mapbs /noexitboot --efi=attr=uc?

**Comment by myrage2000** [comment]
#### Behavior when booting xen.efi with /mapbs /noexitboot --efi=attr=uc :

> Xen 4.8.2 (c/s ) EFI loader
Using configuration file 'xen.cfg'
vmlinuz: [Some hexadecimal number]
initrd.img: [Some hexadecimal number]

And then nothing happens, the laptop is stuck on this screen.
I searched on qubes-users and on qubes-issues and didn't found this issue.

**Comment by marmarek** [comment]
Sorry, there should be a space after `--`.

**Comment by myrage2000** [comment]
Oh yes I did write it with a space (I followed UEFI Troubleshooting guide).

Btw even if I'm not able to use Qubes on this new laptop, thanks for the amazing work you are doing with the team.

**Comment by marmarek** [comment]
Try adding `qubes-verbose` before `/mapbs`, you should get some more details.

**Comment by myrage2000** [comment]
#### With /mapbs /noexitboot -- efi=attr=uc and qubes-verbose :

> [A long list of hex code]
Xen call trace:
[hex code] init_xen_time+0xa2/0x140
[hex code] __start_xen+0x2a4c/0x3320
Pagetable walk from [hex code]:
[A long list of hex code]
*******************************
Panic on CPU 0:
FATAL PAGE FAULT
[error_code=0000]
Faulting linear address: 00000000bfb3b072
*******************************
Reboot in five seconds....

And then it gets stuck, nothing is rebooting.

**Comment by myrage2000** [comment]
#### Issue fixed for new UEFI-Only laptop (thanks to Xen team) :
Boot with -- efi=no-rs

I will install it and see if it boots after that.

**Comment by marmarek** [comment]
You may need to add it to xen.cfg too, as in UEFI troubleshooting guide.

**Comment by myrage2000** [comment]
Thanks, everything is working !
I just have one issue remaining :
I am not able to boot xen.efi with the following custom entry (I get the : "Xen 4.8.2 (c/s ) EFI loader" and then a black screen) :

> chainloader (hd0,gpt1)/EFI/qubes/xen.efi

But I can boot xen.efi directly with no problem :/

Maybe you should add the efi=no-rs command to the UEFI Troubleshooting guide if it can help somebody.

**Comment by marmarek** [comment]
Have you tried adding `placeholder -- efi=no-rs` after xen.efi?

**Comment by myrage2000** [comment]
Yes, here is my 40_custom file :

> insmod part_gpt
insmod search_fs_uuid
insmod chain
chainloader (hd0,gpt1)/EFI/qubes/xen.efi placeholder /mapbs /noexitboot -- efi=no-rs

I had the same issue with the usb key (I had to boot xen.efi directly). Maybe this is related with my laptop.

**Comment by marmarek** [comment]
xen.efi is quite limited in handling filesystem, make sure you do _not_ have `set root` anywhere earlier, so EFI service is used to load file (instead of grub parsing filesystem structures). Also, do not specify device there, put just path to xen.efi (`/EFI/qubes/xen.efi`).
It may be tricky to do it in generated grub config, but maybe there is a way to unset `root` variable?

**Comment by myrage2000** [comment]
I will try thanks.
If it doesn't work, it's not very important, I'll just configure it to boot directly on xen.efi (grub is not very useful with only 1 entry).

Thanks for the help. I'm closing the issue.
