### ISSUE TITLE
Dolphin in Fedora 26 lack Qubes-related file actions

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#3449]
#### Qubes OS version:

R3.2, R4.0

#### Affected TemplateVMs: 

fedora-26

https://groups.google.com/d/msgid/qubes-devel/2B90FCCD-ED91-4BFA-B275-136117F40432%40mail.bitmessage.ch:
> The KDE/dolphin/Konqueror file-move actions are now missing and broken
in a default Fedora 26 template. They don't show up in Dolphin unless
put here:
>
>     sudo cp /usr/share/kde4/services/qvm-* /usr/share/kservices5/ServiceMenus/
>
> and the KDE bash scripts are also broken, such that in the following scripts
>
>     qvm-copy.desktop
>     qvm-move.desktop
> changing the instance of:
>
>      Exec=/usr/lib/qubes/qvm-copy-to-vm.kde %U
> to
>
>      Exec=/usr/lib/qubes/qvm-copy-to-vm.gnome %U

> seems to fix the issue for Dolphin and Konqueror.

**Comment by adrelanos** [comment]
debian-9 is also affected.
