### ISSUE TITLE
x86, kaiser, Meltdown, Spectre:  Use PCID CPU feature via Linux kernel version 4.14 or newer to avoid flushing the TLB too often in Qubes hypervisor and guests

### ISSUE THREAD

**Issue by MarkRijckenberg** [QubesOS/qubes-issues#3450]
#### Qubes OS version:
R3.2

Use PCID CPU feature via Linux kernel version 4.14 or newer to avoid flushing the TLB too often in Qubes hypervisor and guests

Source: https://patchwork.kernel.org/patch/10035481/

#### Affected TemplateVMs: 

All with Linux kernel version older than version 4.14

### Steps to reproduce the behavior:
grep pcid /proc/cpuinfo   

### Expected behavior:
Use of pcid feature

### Actual behavior:
No use of pcid feature

#### Related issues:

Source: https://patchwork.kernel.org/patch/10035481/

**Comment by marmarek** [comment]
This feature may lower the performance impact of KPTI patches applied in Linux. It does not workaround any of those CPU bugs itself. And since it looks like Xen will take totally different approach to workaround those issues (wrap PV domains in HVM/PVH), it is irrelevant in Qubes.
