### ISSUE TITLE
FR: link to individual row in hardware compatibility list.

### ISSUE THREAD

**Issue by inktrap** [QubesOS/qubes-issues#3451]
Feature Request: Please generate IDs for the individual devices in the [hcl](https://www.qubes-os.org/hcl/). Use them per row with the html ``id`` attribute or set anchor ``name``, so that one can link to a row. Edit: devices may be non-unique, so a link to a row, not to a device, I guess.

**Comment by andrewdavidwong** [comment]
@inktrap: Is this what you had in mind?

**Comment by inktrap** [comment]
Yes! Awesome!

Since the model number is often included, this should not lead to non-unique links.
