### ISSUE TITLE
Qubes trying to get windows VM

### ISSUE THREAD

**Issue by Beartooth23** [QubesOS/qubes-issues#3452]
#### Qubes OS version:

QubesOS version R3.2

#### Affected TemplateVMs: 

---

### Steps to reproduce the behavior:

qvm-start win7 --cdrom=personal:/home/user/downloads/en_windows_7_AIO_sp1_x64_86_dvd.iso

```
-->Loading the VM (type = HVM)...
Traceback (most recent call last):
   File "/usr/bin/qvm-start", line 136, in  <module>
      main()
   File "/usr/bin/qvm-start", line 120, in main
      xid = vm.start(verbose=options.verbose, preparing_dvm=options.preparing_dvm, start_guid=not options.tray else
      None)
   File "/usr/li64/python2.7/site-packages/qubes/modules/01QubesHVm.py", line 335, in start
      return super(QubesHVm, self).start(*args, **kwargs)
   File "/usr/li64/python2.7/site-packages/qubes/modules/000QubesVm.py", line1979, in start
      self.libvirt_domain.createWithFlags(libvirt.VIR_DOMAIN_START_PAUSED)
   File "/usr/li64/python2.7/site-packages/libvirt.py",line 1059, in createWithFlags
         if ret == -1: raise libvirtError ('virDomainCreateWithFlags() failed', dom=self)
libvirt.libvirtError: internal error: libxenlight failed to create new domain 'win7'
```

### Expected behavior:

HVM loads ISO for install

### Actual behavior:

"Libvirt.error" libxenlight failed to create new domain"

### General notes:

I know this looks like other problems and I have checked the error logs. I've looked at all of the other problems I've tried all the solutions of them and none of them work for me. 

---

**Comment by tonsimple** [comment]
@Beartooth23 

Try copying the ISO into dom0 and starting with a full path to ISO "locally"

**Comment by marmarek** [comment]
@Beartooth23 does it still happen?
Are you sure the ISO path is correct? In case of invalid path you'll get this error.
Check also `/var/log/libvirt/libxl/libxl-drivers.log`.

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 has reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
