### ISSUE TITLE
No sound in Debian Sid VM's

### ISSUE THREAD

**Issue by AhmedAA** [QubesOS/qubes-issues#3454]
#### Qubes OS version:

R4 RC3

#### Affected TemplateVMs: 

debian sid (unstable)

---

### Steps to reproduce the behavior:

`sudo qubes-dom0-update qubes-template-debian-9`
Update template to sid by pointing `/etc/apt/sources.list` to sid release, instead of stretch and running
`sudo apt-get update && sudo apt-get -u dist-upgrade`

### Expected behavior:

Working sound

### Actual behavior:

No sound

### General notes:

The pulseaudio version in the debian 9 template is 10, and sound works out of the box in the template vm.

Pulseaudio in Sid is version 11. I have tried the workaround from the related issue below, but it does not work.

---

#### Related issues:

https://github.com/QubesOS/qubes-issues/issues/1927#issuecomment-357406761

Don't know if there are others.

**Comment by mirrorway** [comment]
Sound is working in qubes-3.2 debian-buster. So a workaround is to grab the file /usr/lib/pulse-11.1/modules/module-vchan-sink.so from there.

**Comment by AhmedAA** [comment]
Can you assist with where I can grab that?
3.2 does not work on my hardware.

I tried making a buster install (follow steps from above, just with buster instead sid), but that did not help. I created the template, updated to buster, restarted the template, no sound.

**Comment by mirrorway** [comment]
Here it is.

Here is the hash if someone more trustworthy than me wants to chime in to confirm:
$ openssl sha256 module-vchan-sink.so
SHA256(module-vchan-sink.so)= a022479afbb2d0a8d85a05ded0ba451bd7a5fb0a464bc6801f8c312541de4282

**Comment by mirrorway** [comment]
[module-vchan-sink.so.gz](https://github.com/QubesOS/qubes-issues/files/1629536/module-vchan-sink.so.gz)

For anyone who has a buster install, they can verify that:

SHA256(module-vchan-sink.so)= a022479afbb2d0a8d85a05ded0ba451bd7a5fb0a464bc6801f8c312541de4282
SHA256(module-vchan-sink.so.gz)= 9523386349ab8d9fa4a4b67a03df383b870cba30c81ae22f5380fd59bf084779

**Comment by AhmedAA** [comment]
Okay, so!
I downloaded the file in a dispvm, unpacked, moved over to my debian sid template, moved into `/usr/lib/pulseaudio11.1/modules/module-vchan-sink.so`, rebooted my appvm, and now I have sound.

I have no idea what the difference between the version of the file you have and I have is, but yours apparently works.

Thanks!

I don't really want to mark this as solved though..
Care to chime in @andrewdavidwong ?

Cheers!

**Comment by andrewdavidwong** [comment]
@unman, @marmarek: Is there a way to incorporate this fix into the Debian Sid template?

**Comment by unman** [comment]
@andrewdavidwong 
We dont provide a Sid template - Sid is a moving target in Debian, the unstable release "run by developers and those who like to live on the edge". It's almost inevitable that things will be broken, and Sid is subject to huge changes on a daily basis.
A fix today might not work tomorrow.
I would close this Wont Fix.

**Comment by subproc** [comment]
please try to incorporate this fix in Debian Buster template, because of the same issue like explaned in #3532
