### ISSUE TITLE
sys-usb no network ?

### ISSUE THREAD

**Issue by ThierryIT** [QubesOS/qubes-issues#3458]
#### Qubes OS version:
     Type below this line. -->
R3.2

#### Affected TemplateVMs: 

fedora-26

---

### Steps to reproduce the behavior:

sudo qubesctl top.enable qvm.sys-usb
sudo qubesctl state.highstate

### Expected behavior:

To be able to install Yubico key tools
yum install ykpers 

### Actual behavior:

Error: Failed to synchronize cache for repo 'updates'

### General notes:

I do not have any network ... Not able to choose the right netVM (it is in grey)

---

#### Related issues:

No network

**Comment by marmarek** [comment]
For the record:
1. You should install software in a template of that VM, not the VM itself.
2. sys-usb have no network access intentionally, to make it harder to be attacked, and also leak data by malicious USB devices.
