### ISSUE TITLE
VMs not anymore running / Cannot execute qrexec-daemon ??

### ISSUE THREAD

**Issue by ThierryIT** [QubesOS/qubes-issues#3459]
#### Qubes OS version:

R3.2
Kernel 4.9.56-21

#### Affected TemplateVMs: 

---

### Steps to reproduce the behavior:

Installing AEM ?

**update**: VMs with devices selected do have an qrexec-daemon error and cannot start, this is not the case for VMs who do not have any devices selected. (what ever the default Template is: debian 9 or fedora 26)

### Expected behavior:

VMs running

### Actual behavior:

netVM is not running (cannot execute qrexec-daemon)
proxyVM is running if not link to my netVM.

### General notes:

I have installed yesterday AEM and sys-usb.
sys-usb has been removed following the procedure.
When booting I should have my two VMs "netVM and proxyVM" starting to boot automatically. Not the case anymore.
My wifi device doesn't seems to be up as it was before (internal not usb). Same if using ethernet (docking station)

---

#### Related issues:

Perhaps an interference since I have installed AEM ?

**Comment by andrewdavidwong** [comment]
You mentioned that you've removed `sys-usb`, but it depends on the steps you took to remove it. If you have not already done so, please follow these instructions in order to properly remove the USB qube:

https://www.qubes-os.org/doc/usb/#removing-a-usb-qube

**Comment by ThierryIT** [comment]
I did follow the correct procedure :)
Btw, I have done  an upgrade of the fedora-26 's Template too :)
Thx

**Comment by ThierryIT** [comment]
Trying to debug:

I have created a new netVM based on Debian 9 template (instead of fedora 26)
When booting without any devices selected, the VM is working even if the VM is based on fedora 26.
If I add network devices (ethernet controller) on both VM, I still do have an : qrerex-daemon error
So it seems that it has nothing to do with the Template.

**Comment by ThierryIT** [comment]
Still trying to give you the maximum useful information.
The booting menu give me the possibility between:

- AEM Qubes with Xen hypervisor
- Advanced options with AEM boot for Qubes (different kernel version)
- Qubes with hypervisor Xen
- Advanced options for  Qubes

If choosing "Qubes with hypervisor Xen" -> working at it was before
If choosing AEM ... -> qrexec-daemon pb

**Comment by ThierryIT** [comment]
nobody ? I am completely stuck on this  ....

**Comment by marmarek** [comment]
Check /var/log/xen/console/guest-sys-net.log just after trying to start sys-net.

**Comment by ThierryIT** [comment]
I do not have any logs to see.
If I am doing the last imput using "ls -rtl" the most recent input will be for the "hypervisor.log" ... 
All other logs are from the 17th, 15th ....

**Comment by marmarek** [comment]
Hmm, so lets see hypervisor.log.

**Comment by ThierryIT** [comment]
Not in the same pc, I am going to do my best:

(XEN) 89c527cea.... 00000000.... fffffffffff81.......  0000000000....
...
(XEN) 0000000000000 0000000000000 0000000000000 0000000000000
(XEN) 0000000000000 0000000000000 0000000000000 0000000000000

**Comment by marmarek** [comment]
Ough, looks bad. There should be some header, like domain X crashed and some textual reason.
What is the kernel version for sys-net?

**Comment by ThierryIT** [comment]
I have to reboot my Qubes and boot back to: Qubes with hypervisor Xen instead of AEM
I come back to you asap

**Comment by ThierryIT** [comment]
4.9.56-21

**Comment by marmarek** [comment]
Hmm, so the latest in stable. You could try 4.14.13 from testing, but I guess it wont help. AEM (specifically: tboot) do cause problems on some hardware, see [AEM README](https://github.com/QubesOS/qubes-antievilmaid/blob/master/anti-evil-maid/README) - section about memory size. Maybe this is another case like this? Having more detailed message could help, but better ask on xen-devel or tboot-devel mailing lists.

**Comment by ThierryIT** [comment]
No link with ticket:  #3465  ?
