### ISSUE TITLE
Cannot start VMs running 4.14.13-1 kernel

### ISSUE THREAD

**Issue by pugege** [QubesOS/qubes-issues#3466]
#### Qubes OS version:

R4.0

#### Affected TemplateVMs: 

debian-9

---

### Steps to reproduce the behavior:

attempt start vm from menu or cli

### Expected behavior:

successful start

### Actual behavior:

unsuccessful start "Cannot execute grexec-daemon"

### General notes:

VMs based on debian-8 start normally
VMs based on debian-9 start normally with 4.9.56-21 kernel

---

**Comment by ThierryIT** [comment]
Is it the same thing than #3459  ?

**Comment by andrewdavidwong** [comment]
> Is it the same thing than #3459 ?

The two issues do not look similar to me, except for mentioning `Cannot execute grexec-daemon`, which is a common error message. For example, #3459 doesn't mention kernel 4.14.13 at all. Am I missing any similarities?

**Comment by ThierryIT** [comment]
I have add this missing information in my ticket.
Thx

**Comment by marmarek** [comment]
Take a look at /var/log/xen/console/guest-(name of vm).log

**Comment by unman** [comment]
@andrewdavidwong Please close this. It refers to a long outdated kernel version and op did not provide further information.
