### ISSUE TITLE
Install of Yubikey in fedora 26 template 

### ISSUE THREAD

**Issue by ThierryIT** [QubesOS/qubes-issues#3472]
#### Qubes OS version:

R3.2

#### Affected TemplateVMs: 

fedora 26

---

### Steps to reproduce the behavior:

yum/dnf install qubes-yubikey-vm and qubes-yubikey-dom0

### Expected behavior:

make its install

### Actual behavior:

no match for argument

### General notes:

following your procedure from: "https://github.com/adubois/qubes-app-linux-yubikey"

---

#### Related issues:

Cannot install those packages

**Comment by marmarek** [comment]
Note that "Challenge-reponse mode" method is better supported: https://www.qubes-os.org/doc/yubi-key/#challenge-reponse-mode
