### ISSUE TITLE
Can't create new qubes or open VM Settings

### ISSUE THREAD

**Issue by molnara** [QubesOS/qubes-issues#3475]
#### Qubes OS version:

Qubes release 4.0 (R4.0)

#### Affected TemplateVMs: 

dom0

---

### Steps to reproduce the behavior:

1. sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing
2. sudo reboot (There was also a linux kernel update)
3. Click Qubes menu
4. Click Create Qubes VM shortcut
5. Click Qubes menu
6. Click any Domain: VM Settings
7. Click Qubes menu -> System Tools -> Qube Manager
8. Click a qube and click the cog button or right click and select Qube settings

### Expected behavior:

1. New Qubes GUI should open
2. VM Settings GUI should open

### Actual behavior:

This happens when clicking VM Settings from Qubes shortcut.
```
Houston, we have a problem...

Whoops. A critical error has occured.  This is most likely a bug in Qubes Manager.

TypeError: unorderable types:

builtin_function_or_method()
at line 9
of file /usr/lib/python3.5/site-packages/qubesmanager/utils.py
----
line: allow_default=False
func: __init_basic_tab__
line no: 290
file: /usr/lib/python3.5/site-packages/qubesmanager/settings.py
----
line: self.__init_basic_tab__()
func: __init__
line no: 83
file: /usr/lib/python3.5/site-packages/qubesmanager/settings.py
----

.....
```

This happens when you click the Qubes settings in the Qube Manager.

```
Houston, we have a problem...

Whoops. A critical error has occured.  This is most likely a bug in Qubes Manager.

TypeError: unorderable types:
builtin_function_or_method()
at line 852
of file /usr/lib/python3.5/site-packages/qubesmanager/utils.py
----
line: sorted(app.labels, key=lambda l: l.index),
func: prepare_label_choice
lineno.: 116
```

### General notes:

I typed out that stack trace, wasn't sure how to copy/paste from dom0. (Current docs are out of date?)  If someone needs more, I can type out the rest.

---

**Comment by molnara** [comment]
Ok, so there are actually two different critical errors.  One happens when you use the **VM Settings** shortcut and another one when you click the **Qubes Settings** from the **Qube Manager**.  I'll make an edit with the other stack trace.

**Comment by marmarek** [comment]
When exactly have you updated? Or better, what package versions do you have, at least `qubes-manger` and `qubes-core-admin-client`? You can check it this way:
```
rpm -q qubes-manager qubes-core-admin-client
```

**Comment by molnara** [comment]
I just updated about an hour ago.

Qubes Manager is 4.0.10-1.fc25.x86_64
Admin client is 4.0.13-0.1.fc25.noarch

**Comment by molnara** [comment]
I pulled down another update from test repo and now qubes is unstable.  It takes about 15 min to open firefox.  Previously I had no issues running existing qubes.  Also, my laptop has 16gb memory, I only was running sys-net sys-firewall and one personal cube.  All using fedora-26 template downloaded fresh.

**Comment by marmarek** [comment]
What packages were included in that last update run?

**Comment by marmarek** [comment]
What kernel do you use in VMs? Was is one of updated packages this time?

**Comment by molnara** [comment]
The last update that I applied was qubes-core-dom0 4.0.17-1.fc25.x86_64.  I am guessing I can just use dnf to roll this one back?

**Comment by molnara** [comment]
Also, I didn't change the vm kernels as I couldn't get into the vm settings unless that package changed them itself.  They have always been default.

**Comment by marmarek** [comment]
What was your previous qubes-core-dom0? 4.0.16 or 4.0.15?

**Comment by molnara** [comment]
It was 4.0.16

**Comment by marmarek** [comment]
`qubes-dom0-update --action=downgrade qubes-core-dom0-4.0.16`

Anyway, I don't see anything between .16 and .17 that could cause this. There is literally one commit and I don't see how it could cause such effect.
Thing that have changed between .15 and .16 is default virt_mode from HVM to PVH. In theory this could affect performance, but I'd rather expect improvement...
Maybe related to #3466? See memory assigned to each VM and/or swap usage inside of VM.

**Comment by molnara** [comment]
I couldn't downgrade to 4.0.16 but 4.0.15 worked.  As soon as the update completed, immediately my vms started to perform normally.

**Comment by molnara** [comment]
Sorry, where do I see how much memory is being used by my vms?  I can't get into Vm settings because of the critical error.

**Comment by marmarek** [comment]
domains widget (Q icon), or if that doesn't work, `xl list`

**Comment by marmarek** [comment]
Ok, if VM restart wasn't necessary, this is most likely related to a broken fix for #3265. That broken fix is already fixed in https://github.com/QubesOS/qubes-core-admin/pull/182. Let me build 4.0.17...

**Comment by molnara** [comment]
Ok, I didn't realize how much memory is being used by my vms:

Dom0 4067
sys-net 384
sys-net-dm 144
sys-firewall 3194
personal 3999

Seems like the firewall is chewing it all up.  My personal one only has one instance of firefox open with two tabs open including the one I am writing this on.  I'll try a reboot.

**Comment by marmarek** [comment]
It looks fine, firewall is using that much, because you have free ram. It will give it to other VMs when needed.

**Comment by marmarek** [comment]
[qubes-core-dom0 4.0.18](https://github.com/QubesOS/updates-status/issues/368) should fix this.

**Comment by mirrorway** [comment]
With qubes-manager-4.0.11-1 I can't open vm-settings:

AttributeError: default_dispvm has no default
at line 9
of file /usr/bin/qubes-vm-settings.

See error log attached..
[error.log](https://github.com/QubesOS/qubes-issues/files/1645257/error.log)

**Comment by marmarek** [comment]
Do you have other updates installed? Especially qubes-core-dom0 4.0.18 and qubes-core-admin-client >= 4.0.13

**Comment by mirrorway** [comment]
yes to both

**Comment by mirrorway** [comment]
qubes-prefs default_dispvm was set to: D   None,
after setting it to some VM it fixes the issue for me.

**Comment by molnara** [comment]
I just pulled down latest changes and I can confirm I now can edit VM Settings in and open Create  Qubes VM.

Updates applied:
qubes-core-dom0 4.0.18
qubes-dbus 1.0.4
qubes-desktop-linux-manager 4.0.6
qubes-manager 4.0.11
qubes-usb-proxy-dom0 1.0.14

Much appreciated all!  Thank you.

**Comment by tlaurion** [comment]
Still have this bug with all updates installed.

**Comment by tlaurion** [comment]
Even if i loop through all qvm-ls and set default_dispvm property to whonix-ws-dvm or -D, the result is still "AttributeError: default_dispvm has no default at line 9 of /usr/bin/qubes-vm-settings"

**Comment by marmarek** [comment]
Try setting _global_ property `default_dispvm`: 

    qubes-prefs default_dispvm whonix-ws-dvm
(or other value)

**Comment by tlaurion** [comment]
Seems like I do not understand global/local usage with qvm-prefs. It seems to only accepts domain as a first argument, which is how I always used qvm-prefs for.

qvm-prefs: error: no such domain: default_dispvm

**Comment by tlaurion** [comment]
qvm-ls|awk -F " "  {'print $1'}|while read vm; do qvm-prefs $vm default_dispvm -D; done

Same error.

if I apply to a single vm:
qvm-prefs build-openbmc default_dispvm whonix-ws-dvm

I get the same error.
