### ISSUE TITLE
No confirmation dialog when attaching USB mouse

### ISSUE THREAD

**Issue by mossy-nw** [QubesOS/qubes-issues#3481]
#### Qubes OS version:

R4.0

#### Affected TemplateVMs: 

---

### Steps to reproduce the behavior:

Attach USB mouse to system running sys-usb qube

### Expected behavior:

Dialog pops up requiring confirmation before mouse input is passed through sys-usb to dom0

### Actual behavior:

Mouse input it passed through with just a popup notification (no dialog/user action required).

### General notes:

Seems like even if intentional this could be a security risk?  I always feel nervous giving anything access to dom0, it makes me feel slightly better to give explicit consent (as under R3.2).  

---

#### Related issues:

perhaps removing friction from the default target input issue #3251 removed too much friction? : )

**Comment by marmarek** [comment]
This is intended effect, only mouse is allowed by default (but keyboard is not). See https://www.qubes-os.org/doc/usb/#security-warning-about-usb-input-devices for details

If you want to get confirmation, edit `/etc/qubes-rpc/policy/qubes.InputMouse` and change `allow` to `ask,default_target=dom0`.

**Comment by mossy-nw** [comment]
From [qrexec policy documentation](https://www.qubes-os.org/doc/qrexec3/) I think this is the result of default setting `/etc/qubes-rpc/policy/qubes.InputMouse` to 
```
sys-usb dom0 allow,user=root
```

**Comment by mossy-nw** [comment]
ah. you beat me to it. perfect, thanks @marmarek

**Comment by mossy-nw** [comment]
added to https://www.qubes-os.org/doc/usb/#security-warning-about-usb-input-devices
