### ISSUE TITLE
build Qubes-Whonix 14.0.0.5.7 templates for R3.2 and R4

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#3484]
Please build Qubes-Whonix 14.0.0.5.7 templates for R3.2 and R4.

After it has been build, I need to verify it's working fine before it can become a testers-only release.

* Qubes-Whonix 13 R3.2 upgraded to Qubes-Whonix 14 R3.2: working well for me
* Qubes-Whonix 13 R3.4 upgraded to Qubes-Whonix 14 R3.4: working well for me
* Qubes-Whonix 13 R4 upgraded to Qubes-Whonix 14 R4: working well for me
* Qubes-Whonix 14 R4 new build: didn't manage to test yet (https://github.com/QubesOS/qubes-issues/issues/3441#issuecomment-359270625)

-----

https://github.com/marmarek/qubes-template-whonix/pull/7

**Comment by buquser** [comment]
The upgrade from Whonix 13 to 14 in Qubes 3.2 doesn't work well for me. After the upgrade Whonix takes very long to start the qrexec-daemon, so it's throwing an error every time I start Whonix. After waiting a while everything seems to work well.
Because of this issue the trim-template function is not working anymore for the Whonix-Template.
I am using the patched Xen version.

Maybe this is related:
```
Jan 29 15:17:16 host systemd[1]: Started Initialize and mount /rw and /home.
Jan 29 15:17:59 host kernel: random: crng init done
Jan 29 15:18:45 host systemd[1]: dev-hvc0.device: Job dev-hvc0.device/start timed out.
Jan 29 15:18:45 host systemd[1]: Timed out waiting for device dev-hvc0.device.
Jan 29 15:18:45 host systemd[1]: Dependency failed for Serial Getty on hvc0.
Jan 29 15:18:45 host systemd[1]: serial-getty@hvc0.service: Job serial-getty@hvc0.service/start failed with result 'd
Jan 29 15:18:45 host systemd[1]: dev-hvc0.device: Job dev-hvc0.device/start failed with result 'timeout'.
Jan 29 15:18:45 host systemd[1]: dev-xvdc1.device: Job dev-xvdc1.device/start timed out.
Jan 29 15:18:45 host systemd[1]: Timed out waiting for device dev-xvdc1.device.
Jan 29 15:18:45 host systemd[1]: Dependency failed for /dev/xvdc1.
Jan 29 15:18:45 host systemd[1]: Dependency failed for Swap.
Jan 29 15:18:45 host systemd[1]: swap.target: Job swap.target/start failed with result 'dependency'.
Jan 29 15:18:45 host systemd[1]: dev-xvdc1.swap: Job dev-xvdc1.swap/start failed with result 'dependency'.
Jan 29 15:18:45 host systemd[1]: dev-xvdc1.device: Job dev-xvdc1.device/start failed with result 'timeout'.
```

**Comment by marmarek** [comment]
Qubes R3.2 builds:
whonix-gw: qubes-template-whonix-gw-4.0.0-201801270115 ([build log](https://raw.githubusercontent.com/QubesOS/build-logs/eab098aafee6bac612b595ecdabb9a9ccc8ea3c4/build-fedora3/log_2018-01-27_00-09-17))
whonix-ws: qubes-template-whonix-ws-4.0.0-201801270342 ([build log](https://raw.githubusercontent.com/QubesOS/build-logs/72a889fdceb81174f6aad8386d1b1ea8026d7ea7/build-fedora3/log_2018-01-27_01-31-59))
Both uploaded to unstable repository.

**Comment by marmarek** [comment]
Qubes R4.0 builds:
whonix-gw: qubes-template-whonix-gw-4.0.0-201802110155 ([build log](https://raw.githubusercontent.com/QubesOS/build-logs/138b6998cf9b0e6a466aff224974a33ecbc38e89/build-fedora4/log_2018-02-11_01-12-53))
whonix-ws: qubes-template-whonix-ws-4.0.0-201802110435 ([build log](https://raw.githubusercontent.com/QubesOS/build-logs/5f52f9787a6bad5f0ed40a30d3bbb21ef75dca74/build-fedora4/log_2018-02-11_03-15-17))
Uploading to unstable repository in progress, ETA 15min.

**Comment by mirrorway** [comment]
The versioning is kind of confusing. Couldn't it be made consistent with the other templates, i.e.

For jessie:
   qubes-template-whonix-gw-13-<version>
   qubes-template-whonix-ws-13-<version>

For stretch:
   qubes-template-whonix-gw-14-<version>
   qubes-template-whonix-ws-14-<version>

**Comment by marmarek** [comment]
👍 from me. @adrelanos ? That would probably make upgrades more complicated (need to clone/rename etc). Also not sure about amount of docs to be updated.

**Comment by adrelanos** [comment]
Marek Marczykowski-Górecki:
> 👍 from me. @adrelanos ? That would probably make upgrades more complicated (need to clone/rename etc). Also not sure about amount of docs to be updated.
> 

I am ok with this. It would ease testing and migration for users.

However, it would mean extra work for Marek. Meaning, changes to Whonix
salt formula as well as to Qubes installer. Dunno how complex this would
be or what chance for regressions. So I am leaving this to Marek.

**Comment by marmarek** [comment]
Yes, that would complicate things a little. But on the other hand, currently I must be very careful to include the right package on the ISO. Having different package names would avoid this problem.

**Comment by marmarek** [comment]
@adrelanos let me know if/when you want next build or moving this one to templates-community repository. If new build will be needed, I'll adjust its name to `whonix-gw-14` and `whonix-ws-14`.

**Comment by adrelanos** [comment]
@buquser please make that a separate bug report.

**Comment by adrelanos** [comment]
@marmarek 
> @adrelanos let me know if/when you want next build or moving this one to templates-community repository. If new build will be needed, I'll adjust its name to whonix-gw-14 and whonix-ws-14.

Due to https://github.com/QubesOS/qubes-issues/issues/3611 (and other bug fixes meanwhile) certainly new builds are required. I'll open a new ticket when new builds will be useful.
