### ISSUE TITLE
Installing qubes on Lenovo 20HDCTO1WW

### ISSUE THREAD

**Issue by leonardoporpora** [QubesOS/qubes-issues#3488]
Trying to install qubes r4.0 
Help me ;)
![66edffc3-8068-4d34-8f9e-059b832083b4](https://user-images.githubusercontent.com/34192761/35257329-ebc4ae32-fff8-11e7-8a62-32aacb7064ac.jpeg)

**Comment by andrewdavidwong** [comment]
Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this does not appear to be suitable for `qubes-issues`. We ask that you please send this to the `qubes-users` [mailing list](https://www.qubes-os.org/mailing-lists/) instead. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a brief comment explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.
