### ISSUE TITLE
Windows 7 x64 HVM and error 07B - how to change scsi controller type - 4.0RC3

### ISSUE THREAD

**Issue by happymeal00** [QubesOS/qubes-issues#3494]
#### Qubes OS version:

4.0 RC3

#### Affected TemplateVMs: 

StandaloneVM (Windows 7 HVM)

---

### Steps to reproduce the behavior:

when booting an existing Windows 7 x64 systems exported from VirtualBox, the system hangs with BSOD error 0x0000007B.
I have tried to follow suggested changes by enabling other scsi controllers by booting back into Virtual box and as explained here: http://www.justandrew.net/2009/10/stop-0x0000007b-on-p2vd-windows-7.html but nothing has changed. 

While looking at xen logs written in /var/log/xen/console/guest-<vmname>-dm.log i can see that passed scsi  controller is a mptsas1068 controller for which my Windows system doesn't have any 64 bit driver.

### Expected behavior:

normal boot of the Windows x64 HVM machine and recognition of the associated storage controller/ attached disks

### Actual behavior:

BSOD just after boot before loading all *.sys system drivers. 
BSOD error number is 0x0000007B 

### General notes:

I have tried to understand how to pass a diffrent scsi controller (lsi for instance) but it's unclear for me where to set this in the libvirt template. Directly in the xen.xml template file or in the block.xml template file? under what section and which syntax to be used?

---

**Comment by happymeal00** [comment]
I found a bypass solution for this problem by booting back the vm into virtualbox and by enabling the following registry keyword responsible for the load of the scsi mptsas1060 controller:

**HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\LSI_SAS**    **key:Start  value:0** (0 meaning to be loaded).

As a general solution i believe it would make sense to provide a way to edit (either temporary or permanently) a template configuration file allowing the choiche between available qemu emulated controller.

**Comment by awokd** [comment]
@alcreator, what's the easiest way to "[switch] r/w disks to IDE", like you described in #3651?

**Comment by alcreator** [comment]
When I was testing the ide disks, I used the same method that I've described in https://github.com/QubesOS/qubes-issues/issues/4321#issuecomment-423011787.

The argument replacement commands were:

````
#Convert SCSI rw disks to IDE
dm_args=$(echo "$dm_args" | sed "s/-drive\\${SP}file=\/dev\/xvd\(.\),if=none,id=disk\(.\),format=host_device,cache=writeback,readonly=off\\${SP}-device\\${SP}scsi-hd,bus=scsi0.0,drive=disk.,wwn=0x352540005175626./-drive\\${SP}if=ide,media=disk,file=\/dev\/xvd\1,id=disk\2,format=host_device,cache=writeback,readonly=off/g")
#Convert IDE cdrom to SCSI
dm_args=$(echo "$dm_args" | sed "s/-drive\\${SP}if=ide,readonly=on,media=cdrom,id=ide-51840,file=\/dev\/xvdi,format=host_device/-drive\\${SP}if=none,readonly=on,file=\/dev\/xvdi,format=host_device,id=ide-51840\\${SP}-device\\${SP}scsi-cd,bus=scsi0.0,drive=ide-51840,wwn=0x352540005175626f/g")
````

To get xen to provide these commands be default instead, take a look at the tools/libxl/libxl_dm.c file in xen and the patch-stubdom-linux-0005.patch from qubes-vmm-xen. The code to set the disks as SCSI is added by this patch; it can be modified to only attach ro disks as SCSI.
