### ISSUE TITLE
Windows qubes fail to connect to qrexec if set to autostart

### ISSUE THREAD

**Issue by Yethal** [QubesOS/qubes-issues#3497]
#### Qubes OS version:

3.2

#### Affected TemplateVMs: 

windows-7

---

### Steps to reproduce the behavior:

Create a Windows qube
Set the qube to autostart
Reboot physical machine
Observe qube state

### Expected behavior:

Qube autostarts and connects to qrexec

### Actual behavior:

Qube autostarts but fails to connect to qrexec

### General notes:

qrexec_timeout set to 120 but occurs also on 60

---

**Comment by marmarek** [comment]
Do you have any specific messages during VM startup (see `journalctl -u qubes-vm@NAME_OF_VM` in dom0), or just qrexec not connected later?

**Comment by marmarek** [comment]
Can you provide also messages of successful `qvm-start NAME_OF_VM`, including approximate time?

**Comment by Yethal** [comment]
`-- Logs begin at Sat 2017-12-09 00:48:59 CET, end at Fri 2018-01-26 23:06:06 CET. --
Jan 12 20:53:06 dom0 systemd[1]: Starting Start Qubes VM windows-tidal...
Jan 12 20:53:07 dom0 qvm-start[5080]: --> Starting NetVM sys-firewall...
Jan 12 20:53:07 dom0 qvm-start[5080]: --> Starting NetVM sys-net...
Jan 12 20:53:07 dom0 qvm-start[5080]: --> Creating volatile image: /var/lib/qubes/servicevms/sys-net/volatile.img...
Jan 12 20:53:07 dom0 qvm-start[5080]: /var/lib/qubes/servicevms/sys-net/volatile.img already exists, not overriding
Jan 12 20:53:07 dom0 systemd[1]: qubes-vm@windows-tidal.service: Main process exited, code=exited, status=1/FAILURE
Jan 12 20:53:07 dom0 systemd[1]: Failed to start Start Qubes VM windows-tidal.
Jan 12 20:53:07 dom0 systemd[1]: qubes-vm@windows-tidal.service: Unit entered failed state.
Jan 12 20:53:07 dom0 systemd[1]: qubes-vm@windows-tidal.service: Failed with result 'exit-code'.
Jan 12 20:53:07 dom0 qvm-start[5080]: Traceback (most recent call last):
Jan 12 20:53:07 dom0 qvm-start[5080]: File "/usr/bin/qvm-start", line 136, in <module>
Jan 12 20:53:07 dom0 qvm-start[5080]: main()
Jan 12 20:53:07 dom0 qvm-start[5080]: File "/usr/bin/qvm-start", line 120, in main
Jan 12 20:53:07 dom0 qvm-start[5080]: xid = vm.start(verbose=options.verbose, preparing_dvm=options.preparing_dvm, start_guid=not options.noguid, notify_function=tray_notify_generic if options.tray else None)
Jan 12 20:53:07 dom0 qvm-start[5080]: File "/usr/lib64/python2.7/site-packages/qubes/modules/01QubesHVm.py", line 335, in start
Jan 12 20:53:07 dom0 qvm-start[5080]: return super(QubesHVm, self).start(*args, **kwargs)
Jan 12 20:53:07 dom0 qvm-start[5080]: File "/usr/lib64/python2.7/site-packages/qubes/modules/000QubesVm.py", line 1949, in start
Jan 12 20:53:07 dom0 qvm-start[5080]: self.netvm.start(verbose = verbose, start_guid = start_guid, notify_function = notify_function)
Jan 12 20:53:07 dom0 qvm-start[5080]: File "/usr/lib64/python2.7/site-packages/qubes/modules/006QubesProxyVm.py", line 82, in start
Jan 12 20:53:07 dom0 qvm-start[5080]: retcode = super(QubesProxyVm, self).start(**kwargs)
Jan 12 20:53:07 dom0 qvm-start[5080]: File "/usr/lib64/python2.7/site-packages/qubes/modules/005QubesNetVm.py", line 122, in start
Jan 12 20:53:07 dom0 qvm-start[5080]: xid=super(QubesNetVm, self).start(**kwargs)
Jan 12 20:53:07 dom0 qvm-start[5080]: File "/usr/lib64/python2.7/site-packages/qubes/modules/000QubesVm.py", line 1949, in start
Jan 12 20:53:07 dom0 qvm-start[5080]: self.netvm.start(verbose = verbose, start_guid = start_guid, notify_function = notify_function)
Jan 12 20:53:07 dom0 qvm-start[5080]: File "/usr/lib64/python2.7/site-packages/qubes/modules/005QubesNetVm.py", line 122, in start
Jan 12 20:53:07 dom0 qvm-start[5080]: xid=super(QubesNetVm, self).start(**kwargs)
Jan 12 20:53:07 dom0 qvm-start[5080]: File "/usr/lib64/python2.7/site-packages/qubes/modules/000QubesVm.py", line 1951, in start
Jan 12 20:53:07 dom0 qvm-start[5080]: self.storage.prepare_for_vm_startup(verbose=verbose)
Jan 12 20:53:07 dom0 qvm-start[5080]: File "/usr/lib64/python2.7/site-packages/qubes/storage/xen.py", line 210, in prepare_for_vm_startup
Jan 12 20:53:07 dom0 qvm-start[5080]: super(XenStorage, self).prepare_for_vm_startup(verbose=verbose)
Jan 12 20:53:07 dom0 qvm-start[5080]: File "/usr/lib64/python2.7/site-packages/qubes/storage/__init__.py", line 256, in prepare_for_vm_startup
Jan 12 20:53:07 dom0 qvm-start[5080]: self.reset_volatile_storage(verbose=verbose)
Jan 12 20:53:07 dom0 qvm-start[5080]: File "/usr/lib64/python2.7/site-packages/qubes/storage/xen.py", line 207, in reset_volatile_storage
Jan 12 20:53:07 dom0 qvm-start[5080]: verbose=verbose, source_template=source_template)
Jan 12 20:53:07 dom0 qvm-start[5080]: File "/usr/lib64/python2.7/site-packages/qubes/storage/__init__.py", line 253, in reset_volatile_storage
Jan 12 20:53:07 dom0 qvm-start[5080]: self.volatile_img, str(self.root_img_size / 1024 / 1024)])
Jan 12 20:53:07 dom0 qvm-start[5080]: File "/usr/lib64/python2.7/subprocess.py", line 540, in check_call
Jan 12 20:53:07 dom0 qvm-start[5080]: raise CalledProcessError(retcode, cmd)
Jan 12 20:53:07 dom0 qvm-start[5080]: subprocess.CalledProcessError: Command '['/usr/lib/qubes/prepare-volatile-img.sh', '/var/lib/qubes/servicevms/sys-net/volatile.img', '10240']' returned non-zero exit status 1
-- Reboot --
Jan 12 20:59:45 dom0 systemd[1]: Starting Start Qubes VM windows-tidal...
Jan 12 20:59:46 dom0 qvm-start[3885]: --> Starting NetVM sys-firewall...
Jan 12 20:59:46 dom0 qvm-start[3885]: --> Starting NetVM sys-net...
Jan 12 20:59:46 dom0 qvm-start[3885]: --> Creating volatile image: /var/lib/qubes/servicevms/sys-net/volatile.img...
Jan 12 20:59:46 dom0 qvm-start[3885]: /var/lib/qubes/servicevms/sys-net/volatile.img already exists, not overriding
Jan 12 20:59:46 dom0 qvm-start[3885]: Traceback (most recent call last):
Jan 12 20:59:46 dom0 qvm-start[3885]: File "/usr/bin/qvm-start", line 136, in <module>
Jan 12 20:59:46 dom0 qvm-start[3885]: main()
Jan 12 20:59:46 dom0 qvm-start[3885]: File "/usr/bin/qvm-start", line 120, in main
Jan 12 20:59:46 dom0 qvm-start[3885]: xid = vm.start(verbose=options.verbose, preparing_dvm=options.preparing_dvm, start_guid=not options.noguid, notify_function=tray_notify_generic if options.tray else None)
Jan 12 20:59:46 dom0 qvm-start[3885]: File "/usr/lib64/python2.7/site-packages/qubes/modules/01QubesHVm.py", line 335, in start
Jan 12 20:59:46 dom0 qvm-start[3885]: return super(QubesHVm, self).start(*args, **kwargs)
Jan 12 20:59:46 dom0 qvm-start[3885]: File "/usr/lib64/python2.7/site-packages/qubes/modules/000QubesVm.py", line 1949, in start
Jan 12 20:59:46 dom0 qvm-start[3885]: self.netvm.start(verbose = verbose, start_guid = start_guid, notify_function = notify_function)
Jan 12 20:59:46 dom0 qvm-start[3885]: File "/usr/lib64/python2.7/site-packages/qubes/modules/006QubesProxyVm.py", line 82, in start
Jan 12 20:59:46 dom0 qvm-start[3885]: retcode = super(QubesProxyVm, self).start(**kwargs)
Jan 12 20:59:46 dom0 qvm-start[3885]: File "/usr/lib64/python2.7/site-packages/qubes/modules/005QubesNetVm.py", line 122, in start
Jan 12 20:59:46 dom0 qvm-start[3885]: xid=super(QubesNetVm, self).start(**kwargs)
Jan 12 20:59:46 dom0 qvm-start[3885]: File "/usr/lib64/python2.7/site-packages/qubes/modules/000QubesVm.py", line 1949, in start
Jan 12 20:59:46 dom0 qvm-start[3885]: self.netvm.start(verbose = verbose, start_guid = start_guid, notify_function = notify_function)
Jan 12 20:59:46 dom0 qvm-start[3885]: File "/usr/lib64/python2.7/site-packages/qubes/modules/005QubesNetVm.py", line 122, in start
Jan 12 20:59:46 dom0 qvm-start[3885]: xid=super(QubesNetVm, self).start(**kwargs)
Jan 12 20:59:46 dom0 qvm-start[3885]: File "/usr/lib64/python2.7/site-packages/qubes/modules/000QubesVm.py", line 1951, in start
Jan 12 20:59:46 dom0 qvm-start[3885]: self.storage.prepare_for_vm_startup(verbose=verbose)
Jan 12 20:59:46 dom0 qvm-start[3885]: File "/usr/lib64/python2.7/site-packages/qubes/storage/xen.py", line 210, in prepare_for_vm_startup
Jan 12 20:59:46 dom0 qvm-start[3885]: super(XenStorage, self).prepare_for_vm_startup(verbose=verbose)
Jan 12 20:59:46 dom0 qvm-start[3885]: File "/usr/lib64/python2.7/site-packages/qubes/storage/__init__.py", line 256, in prepare_for_vm_startup
Jan 12 20:59:46 dom0 qvm-start[3885]: self.reset_volatile_storage(verbose=verbose)
Jan 12 20:59:46 dom0 qvm-start[3885]: File "/usr/lib64/python2.7/site-packages/qubes/storage/xen.py", line 207, in reset_volatile_storage
Jan 12 20:59:46 dom0 qvm-start[3885]: verbose=verbose, source_template=source_template)
Jan 12 20:59:46 dom0 qvm-start[3885]: File "/usr/lib64/python2.7/site-packages/qubes/storage/__init__.py", line 253, in reset_volatile_storage
Jan 12 20:59:46 dom0 qvm-start[3885]: self.volatile_img, str(self.root_img_size / 1024 / 1024)])
Jan 12 20:59:46 dom0 qvm-start[3885]: File "/usr/lib64/python2.7/subprocess.py", line 540, in check_call
Jan 12 20:59:46 dom0 qvm-start[3885]: raise CalledProcessError(retcode, cmd)
Jan 12 20:59:46 dom0 qvm-start[3885]: subprocess.CalledProcessError: Command '['/usr/lib/qubes/prepare-volatile-img.sh', '/var/lib/qubes/servicevms/sys-net/volatile.img', '10240']' returned non-zero exit status 1
Jan 12 20:59:46 dom0 systemd[1]: qubes-vm@windows-tidal.service: Main process exited, code=exited, status=1/FAILURE
Jan 12 20:59:46 dom0 systemd[1]: Failed to start Start Qubes VM windows-tidal.
Jan 12 20:59:46 dom0 systemd[1]: qubes-vm@windows-tidal.service: Unit entered failed state.
Jan 12 20:59:46 dom0 systemd[1]: qubes-vm@windows-tidal.service: Failed with result 'exit-code'.
-- Reboot --
Jan 12 21:04:55 dom0 systemd[1]: Starting Start Qubes VM windows-tidal...
Jan 12 21:04:56 dom0 qvm-start[3109]: --> Starting NetVM sys-firewall...
Jan 12 21:04:56 dom0 qvm-start[3109]: --> Starting NetVM sys-net...
Jan 12 21:04:56 dom0 qvm-start[3109]: --> Creating volatile image: /var/lib/qubes/servicevms/sys-net/volatile.img...
Jan 12 21:04:56 dom0 qvm-start[3109]: /var/lib/qubes/servicevms/sys-net/volatile.img already exists, not overriding
Jan 12 21:04:56 dom0 qvm-start[3109]: Traceback (most recent call last):
Jan 12 21:04:56 dom0 qvm-start[3109]: File "/usr/bin/qvm-start", line 136, in <module>
Jan 12 21:04:56 dom0 qvm-start[3109]: main()
Jan 12 21:04:56 dom0 qvm-start[3109]: File "/usr/bin/qvm-start", line 120, in main
Jan 12 21:04:56 dom0 qvm-start[3109]: xid = vm.start(verbose=options.verbose, preparing_dvm=options.preparing_dvm, start_guid=not options.noguid, notify_function=tray_notify_generic if options.tray else None)
Jan 12 21:04:56 dom0 qvm-start[3109]: File "/usr/lib64/python2.7/site-packages/qubes/modules/01QubesHVm.py", line 335, in start
Jan 12 21:04:56 dom0 qvm-start[3109]: return super(QubesHVm, self).start(*args, **kwargs)
Jan 12 21:04:56 dom0 qvm-start[3109]: File "/usr/lib64/python2.7/site-packages/qubes/modules/000QubesVm.py", line 1949, in start
Jan 12 21:04:56 dom0 qvm-start[3109]: self.netvm.start(verbose = verbose, start_guid = start_guid, notify_function = notify_function)
Jan 12 21:04:56 dom0 qvm-start[3109]: File "/usr/lib64/python2.7/site-packages/qubes/modules/006QubesProxyVm.py", line 82, in start
Jan 12 21:04:56 dom0 qvm-start[3109]: retcode = super(QubesProxyVm, self).start(**kwargs)
Jan 12 21:04:56 dom0 qvm-start[3109]: File "/usr/lib64/python2.7/site-packages/qubes/modules/005QubesNetVm.py", line 122, in start
Jan 12 21:04:56 dom0 qvm-start[3109]: xid=super(QubesNetVm, self).start(**kwargs)
Jan 12 21:04:56 dom0 qvm-start[3109]: File "/usr/lib64/python2.7/site-packages/qubes/modules/000QubesVm.py", line 1949, in start
Jan 12 21:04:56 dom0 qvm-start[3109]: self.netvm.start(verbose = verbose, start_guid = start_guid, notify_function = notify_function)
Jan 12 21:04:56 dom0 qvm-start[3109]: File "/usr/lib64/python2.7/site-packages/qubes/modules/005QubesNetVm.py", line 122, in start
Jan 12 21:04:56 dom0 qvm-start[3109]: xid=super(QubesNetVm, self).start(**kwargs)
Jan 12 21:04:56 dom0 qvm-start[3109]: File "/usr/lib64/python2.7/site-packages/qubes/modules/000QubesVm.py", line 1951, in start
Jan 12 21:04:56 dom0 qvm-start[3109]: self.storage.prepare_for_vm_startup(verbose=verbose)
Jan 12 21:04:56 dom0 qvm-start[3109]: File "/usr/lib64/python2.7/site-packages/qubes/storage/xen.py", line 210, in prepare_for_vm_startup
Jan 12 21:04:56 dom0 qvm-start[3109]: super(XenStorage, self).prepare_for_vm_startup(verbose=verbose)
Jan 12 21:04:56 dom0 qvm-start[3109]: File "/usr/lib64/python2.7/site-packages/qubes/storage/__init__.py", line 256, in prepare_for_vm_startup
Jan 12 21:04:56 dom0 qvm-start[3109]: self.reset_volatile_storage(verbose=verbose)
Jan 12 21:04:56 dom0 qvm-start[3109]: File "/usr/lib64/python2.7/site-packages/qubes/storage/xen.py", line 207, in reset_volatile_storage
Jan 12 21:04:56 dom0 qvm-start[3109]: verbose=verbose, source_template=source_template)
Jan 12 21:04:56 dom0 qvm-start[3109]: File "/usr/lib64/python2.7/site-packages/qubes/storage/__init__.py", line 253, in reset_volatile_storage
Jan 12 21:04:56 dom0 systemd[1]: qubes-vm@windows-tidal.service: Main process exited, code=exited, status=1/FAILURE
Jan 12 21:04:56 dom0 systemd[1]: Failed to start Start Qubes VM windows-tidal.
Jan 12 21:04:56 dom0 systemd[1]: qubes-vm@windows-tidal.service: Unit entered failed state.
Jan 12 21:04:56 dom0 systemd[1]: qubes-vm@windows-tidal.service: Failed with result 'exit-code'.
Jan 12 21:04:56 dom0 qvm-start[3109]: self.volatile_img, str(self.root_img_size / 1024 / 1024)])
Jan 12 21:04:56 dom0 qvm-start[3109]: File "/usr/lib64/python2.7/subprocess.py", line 540, in check_call
Jan 12 21:04:56 dom0 qvm-start[3109]: raise CalledProcessError(retcode, cmd)
Jan 12 21:04:56 dom0 qvm-start[3109]: subprocess.CalledProcessError: Command '['/usr/lib/qubes/prepare-volatile-img.sh', '/var/lib/qubes/servicevms/sys-net/volatile.img', '10240']' returned non-zero exit status 1
-- Reboot --
Jan 13 18:21:13 dom0 systemd[1]: Starting Start Qubes VM windows-tidal...
Jan 13 18:21:13 dom0 qvm-start[3367]: --> Creating volatile image: /var/lib/qubes/appvms/windows-tidal/volatile.img...
Jan 13 18:21:13 dom0 qvm-start[3367]: --> Loading the VM (type = HVM)...
Jan 13 18:21:30 dom0 qvm-start[3367]: --> Starting Qubes DB...
Jan 13 18:21:30 dom0 runuser[8076]: pam_unix(runuser:session): session opened for user Yethal by (uid=0)
Jan 13 18:21:30 dom0 runuser[8076]: pam_unix(runuser:session): session closed for user Yethal
Jan 13 18:21:30 dom0 qvm-start[3367]: --> Setting Qubes DB info for the VM...
Jan 13 18:21:30 dom0 qvm-start[3367]: --> Updating firewall rules...
Jan 13 18:21:30 dom0 qvm-start[3367]: --> Starting the VM...
Jan 13 18:21:30 dom0 qvm-start[3367]: --> Starting the qrexec daemon...
Jan 13 18:21:30 dom0 runuser[8079]: pam_unix(runuser:session): session opened for user Yethal by (uid=0)
Jan 13 18:21:49 dom0 qvm-start[3367]: Waiting for VM's qrexec agent....................connected
Jan 13 18:21:49 dom0 runuser[8079]: pam_unix(runuser:session): session closed for user Yethal
Jan 13 18:21:49 dom0 qvm-start[3367]: --> Waiting for user 'user' login...
Jan 13 18:21:50 dom0 systemd[1]: Started Start Qubes VM windows-tidal.
-- Reboot --
Jan 13 19:44:03 dom0 systemd[1]: Starting Start Qubes VM windows-tidal...
Jan 13 19:44:03 dom0 qvm-start[3481]: --> Creating volatile image: /var/lib/qubes/appvms/windows-tidal/volatile.img...
Jan 13 19:44:03 dom0 qvm-start[3481]: --> Loading the VM (type = HVM)...
Jan 13 19:44:24 dom0 qvm-start[3481]: --> Starting Qubes DB...
Jan 13 19:44:24 dom0 runuser[9112]: pam_unix(runuser:session): session opened for user Yethal by (uid=0)
Jan 13 19:44:24 dom0 runuser[9112]: pam_unix(runuser:session): session closed for user Yethal
Jan 13 19:44:24 dom0 qvm-start[3481]: --> Setting Qubes DB info for the VM...
Jan 13 19:44:24 dom0 qvm-start[3481]: --> Updating firewall rules...
Jan 13 19:44:24 dom0 qvm-start[3481]: --> Starting the VM...
Jan 13 19:44:24 dom0 qvm-start[3481]: --> Starting the qrexec daemon...
Jan 13 19:44:24 dom0 runuser[9115]: pam_unix(runuser:session): session opened for user Yethal by (uid=0)
Jan 13 19:44:48 dom0 qvm-start[3481]: Waiting for VM's qrexec agent.........................connected
Jan 13 19:44:48 dom0 runuser[9115]: pam_unix(runuser:session): session closed for user Yethal
Jan 13 19:44:48 dom0 qvm-start[3481]: --> Waiting for user 'user' login...
Jan 13 19:44:49 dom0 systemd[1]: Started Start Qubes VM windows-tidal.
-- Reboot --
Jan 26 20:44:48 dom0 systemd[1]: Starting Start Qubes VM windows-tidal...
Jan 26 20:44:48 dom0 qvm-start[3332]: --> Starting NetVM sys-firewall...
Jan 26 20:44:48 dom0 qvm-start[3332]: --> Starting NetVM sys-net...
Jan 26 20:44:48 dom0 qvm-start[3332]: --> Creating volatile image: /var/lib/qubes/servicevms/sys-net/volatile.img...
Jan 26 20:44:48 dom0 qvm-start[3332]: /var/lib/qubes/servicevms/sys-net/volatile.img already exists, not overriding
Jan 26 20:44:48 dom0 systemd[1]: qubes-vm@windows-tidal.service: Main process exited, code=exited, status=1/FAILURE
Jan 26 20:44:48 dom0 systemd[1]: Failed to start Start Qubes VM windows-tidal.
Jan 26 20:44:48 dom0 systemd[1]: qubes-vm@windows-tidal.service: Unit entered failed state.
Jan 26 20:44:48 dom0 systemd[1]: qubes-vm@windows-tidal.service: Failed with result 'exit-code'.
Jan 26 20:44:48 dom0 qvm-start[3332]: Traceback (most recent call last):
Jan 26 20:44:48 dom0 qvm-start[3332]: File "/usr/bin/qvm-start", line 136, in <module>
Jan 26 20:44:48 dom0 qvm-start[3332]: main()
Jan 26 20:44:48 dom0 qvm-start[3332]: File "/usr/bin/qvm-start", line 120, in main
Jan 26 20:44:48 dom0 qvm-start[3332]: xid = vm.start(verbose=options.verbose, preparing_dvm=options.preparing_dvm, start_guid=not options.noguid, notify_function=tray_notify_generic if options.tray else None)
Jan 26 20:44:48 dom0 qvm-start[3332]: File "/usr/lib64/python2.7/site-packages/qubes/modules/01QubesHVm.py", line 335, in start
Jan 26 20:44:48 dom0 qvm-start[3332]: return super(QubesHVm, self).start(*args, **kwargs)
Jan 26 20:44:48 dom0 qvm-start[3332]: File "/usr/lib64/python2.7/site-packages/qubes/modules/000QubesVm.py", line 1949, in start
Jan 26 20:44:48 dom0 qvm-start[3332]: self.netvm.start(verbose = verbose, start_guid = start_guid, notify_function = notify_function)
Jan 26 20:44:48 dom0 qvm-start[3332]: File "/usr/lib64/python2.7/site-packages/qubes/modules/006QubesProxyVm.py", line 82, in start
Jan 26 20:44:48 dom0 qvm-start[3332]: retcode = super(QubesProxyVm, self).start(**kwargs)
Jan 26 20:44:48 dom0 qvm-start[3332]: File "/usr/lib64/python2.7/site-packages/qubes/modules/005QubesNetVm.py", line 122, in start
Jan 26 20:44:48 dom0 qvm-start[3332]: xid=super(QubesNetVm, self).start(**kwargs)
Jan 26 20:44:48 dom0 qvm-start[3332]: File "/usr/lib64/python2.7/site-packages/qubes/modules/000QubesVm.py", line 1949, in start
Jan 26 20:44:48 dom0 qvm-start[3332]: self.netvm.start(verbose = verbose, start_guid = start_guid, notify_function = notify_function)
Jan 26 20:44:48 dom0 qvm-start[3332]: File "/usr/lib64/python2.7/site-packages/qubes/modules/005QubesNetVm.py", line 122, in start
Jan 26 20:44:48 dom0 qvm-start[3332]: xid=super(QubesNetVm, self).start(**kwargs)
Jan 26 20:44:48 dom0 qvm-start[3332]: File "/usr/lib64/python2.7/site-packages/qubes/modules/000QubesVm.py", line 1951, in start
Jan 26 20:44:48 dom0 qvm-start[3332]: self.storage.prepare_for_vm_startup(verbose=verbose)
Jan 26 20:44:48 dom0 qvm-start[3332]: File "/usr/lib64/python2.7/site-packages/qubes/storage/xen.py", line 210, in prepare_for_vm_startup
Jan 26 20:44:48 dom0 qvm-start[3332]: super(XenStorage, self).prepare_for_vm_startup(verbose=verbose)
Jan 26 20:44:48 dom0 qvm-start[3332]: File "/usr/lib64/python2.7/site-packages/qubes/storage/__init__.py", line 256, in prepare_for_vm_startup
Jan 26 20:44:48 dom0 qvm-start[3332]: self.reset_volatile_storage(verbose=verbose)
Jan 26 20:44:48 dom0 qvm-start[3332]: File "/usr/lib64/python2.7/site-packages/qubes/storage/xen.py", line 207, in reset_volatile_storage
Jan 26 20:44:48 dom0 qvm-start[3332]: verbose=verbose, source_template=source_template)
Jan 26 20:44:48 dom0 qvm-start[3332]: File "/usr/lib64/python2.7/site-packages/qubes/storage/__init__.py", line 253, in reset_volatile_storage
Jan 26 20:44:48 dom0 qvm-start[3332]: self.volatile_img, str(self.root_img_size / 1024 / 1024)])
Jan 26 20:44:48 dom0 qvm-start[3332]: File "/usr/lib64/python2.7/subprocess.py", line 540, in check_call
Jan 26 20:44:48 dom0 qvm-start[3332]: raise CalledProcessError(retcode, cmd)
Jan 26 20:44:48 dom0 qvm-start[3332]: subprocess.CalledProcessError: Command '['/usr/lib/qubes/prepare-volatile-img.sh', '/var/lib/qubes/servicevms/sys-net/volatile.img', '10240']' returned non-zero exit status 1
-- Reboot --
Jan 26 20:49:29 dom0 systemd[1]: Starting Start Qubes VM windows-tidal...
Jan 26 20:49:29 dom0 qvm-start[3191]: --> Starting NetVM sys-firewall...
Jan 26 20:49:29 dom0 qvm-start[3191]: --> Starting NetVM sys-net...
Jan 26 20:49:29 dom0 qvm-start[3191]: --> Creating volatile image: /var/lib/qubes/servicevms/sys-net/volatile.img...
Jan 26 20:49:29 dom0 qvm-start[3191]: /var/lib/qubes/servicevms/sys-net/volatile.img already exists, not overriding
Jan 26 20:49:29 dom0 qvm-start[3191]: Traceback (most recent call last):
Jan 26 20:49:29 dom0 qvm-start[3191]: File "/usr/bin/qvm-start", line 136, in <module>
Jan 26 20:49:29 dom0 qvm-start[3191]: main()
Jan 26 20:49:29 dom0 qvm-start[3191]: File "/usr/bin/qvm-start", line 120, in main
Jan 26 20:49:29 dom0 qvm-start[3191]: xid = vm.start(verbose=options.verbose, preparing_dvm=options.preparing_dvm, start_guid=not options.noguid, notify_function=tray_notify_generic if options.tray else None)
Jan 26 20:49:29 dom0 qvm-start[3191]: File "/usr/lib64/python2.7/site-packages/qubes/modules/01QubesHVm.py", line 335, in start
Jan 26 20:49:29 dom0 qvm-start[3191]: return super(QubesHVm, self).start(*args, **kwargs)
Jan 26 20:49:29 dom0 qvm-start[3191]: File "/usr/lib64/python2.7/site-packages/qubes/modules/000QubesVm.py", line 1949, in start
Jan 26 20:49:29 dom0 qvm-start[3191]: self.netvm.start(verbose = verbose, start_guid = start_guid, notify_function = notify_function)
Jan 26 20:49:29 dom0 qvm-start[3191]: File "/usr/lib64/python2.7/site-packages/qubes/modules/006QubesProxyVm.py", line 82, in start
Jan 26 20:49:29 dom0 qvm-start[3191]: retcode = super(QubesProxyVm, self).start(**kwargs)
Jan 26 20:49:29 dom0 qvm-start[3191]: File "/usr/lib64/python2.7/site-packages/qubes/modules/005QubesNetVm.py", line 122, in start
Jan 26 20:49:29 dom0 qvm-start[3191]: xid=super(QubesNetVm, self).start(**kwargs)
Jan 26 20:49:29 dom0 qvm-start[3191]: File "/usr/lib64/python2.7/site-packages/qubes/modules/000QubesVm.py", line 1949, in start
Jan 26 20:49:29 dom0 qvm-start[3191]: self.netvm.start(verbose = verbose, start_guid = start_guid, notify_function = notify_function)
Jan 26 20:49:29 dom0 qvm-start[3191]: File "/usr/lib64/python2.7/site-packages/qubes/modules/005QubesNetVm.py", line 122, in start
Jan 26 20:49:29 dom0 qvm-start[3191]: xid=super(QubesNetVm, self).start(**kwargs)
Jan 26 20:49:29 dom0 qvm-start[3191]: File "/usr/lib64/python2.7/site-packages/qubes/modules/000QubesVm.py", line 1951, in start
Jan 26 20:49:29 dom0 qvm-start[3191]: self.storage.prepare_for_vm_startup(verbose=verbose)
Jan 26 20:49:29 dom0 qvm-start[3191]: File "/usr/lib64/python2.7/site-packages/qubes/storage/xen.py", line 210, in prepare_for_vm_startup
Jan 26 20:49:29 dom0 qvm-start[3191]: super(XenStorage, self).prepare_for_vm_startup(verbose=verbose)
Jan 26 20:49:29 dom0 qvm-start[3191]: File "/usr/lib64/python2.7/site-packages/qubes/storage/__init__.py", line 256, in prepare_for_vm_startup
Jan 26 20:49:29 dom0 qvm-start[3191]: self.reset_volatile_storage(verbose=verbose)
Jan 26 20:49:29 dom0 qvm-start[3191]: File "/usr/lib64/python2.7/site-packages/qubes/storage/xen.py", line 207, in reset_volatile_storage
Jan 26 20:49:29 dom0 qvm-start[3191]: verbose=verbose, source_template=source_template)
Jan 26 20:49:29 dom0 qvm-start[3191]: File "/usr/lib64/python2.7/site-packages/qubes/storage/__init__.py", line 253, in reset_volatile_storage
Jan 26 20:49:29 dom0 systemd[1]: qubes-vm@windows-tidal.service: Main process exited, code=exited, status=1/FAILURE
Jan 26 20:49:29 dom0 systemd[1]: Failed to start Start Qubes VM windows-tidal.
Jan 26 20:49:29 dom0 systemd[1]: qubes-vm@windows-tidal.service: Unit entered failed state.
Jan 26 20:49:29 dom0 systemd[1]: qubes-vm@windows-tidal.service: Failed with result 'exit-code'.
Jan 26 20:49:29 dom0 qvm-start[3191]: self.volatile_img, str(self.root_img_size / 1024 / 1024)])
Jan 26 20:49:29 dom0 qvm-start[3191]: File "/usr/lib64/python2.7/subprocess.py", line 540, in check_call
Jan 26 20:49:29 dom0 qvm-start[3191]: raise CalledProcessError(retcode, cmd)
Jan 26 20:49:29 dom0 qvm-start[3191]: subprocess.CalledProcessError: Command '['/usr/lib/qubes/prepare-volatile-img.sh', '/var/lib/qubes/servicevms/sys-net/volatile.img', '10240']' returned non-zero exit status 1
-- Reboot --
Jan 26 20:55:09 dom0 systemd[1]: Starting Start Qubes VM windows-tidal...
Jan 26 20:55:09 dom0 qvm-start[3799]: --> Creating volatile image: /var/lib/qubes/appvms/windows-tidal/volatile.img...
Jan 26 20:55:09 dom0 qvm-start[3799]: --> Loading the VM (type = HVM)...
Jan 26 20:55:41 dom0 qvm-start[3799]: --> Starting Qubes DB...
Jan 26 20:55:41 dom0 runuser[9001]: pam_unix(runuser:session): session opened for user Yethal by (uid=0)
Jan 26 20:55:41 dom0 runuser[9001]: pam_unix(runuser:session): session closed for user Yethal
Jan 26 20:55:41 dom0 qvm-start[3799]: --> Setting Qubes DB info for the VM...
Jan 26 20:55:41 dom0 qvm-start[3799]: --> Updating firewall rules...
Jan 26 20:55:41 dom0 qvm-start[3799]: --> Starting the VM...
Jan 26 20:55:41 dom0 qvm-start[3799]: --> Starting the qrexec daemon...
Jan 26 20:55:41 dom0 runuser[9004]: pam_unix(runuser:session): session opened for user Yethal by (uid=0)
Jan 26 20:56:11 dom0 qvm-start[3799]: Waiting for VM's qrexec agent..............................connected
Jan 26 20:56:11 dom0 runuser[9004]: pam_unix(runuser:session): session closed for user Yethal
Jan 26 20:56:11 dom0 qvm-start[3799]: --> Waiting for user 'user' login...
Jan 26 20:56:12 dom0 systemd[1]: Started Start Qubes VM windows-tidal.`

**Comment by marmarek** [comment]
The last one looks to be successful, did it worked?

**Comment by Yethal** [comment]
No, the last one is from manual vm start.

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
