### ISSUE TITLE
Cannot stop VM - Qubes 4.0 R3

### ISSUE THREAD

**Issue by ThierryIT** [QubesOS/qubes-issues#3501]
#### Qubes OS version:

4.0 R3

#### Affected TemplateVMs: 

wrong: ALL + StandaloneVM
Update: Only restored VMs from R3.2 have these problems

---

### Steps to reproduce the behavior:

Try to stop/restart VM

### Expected behavior:

stop or restart ... 

### Actual behavior:

ValueError: Could not convert string to float: at line 178
of line /usr/lib/python3.5/site-packages/qubesmanager/qube_manager.py

line: assert vm.is_running()
func: action_shutdown_triggered
line no.:766
file:/usr/lib/python3.5/site-packages/qubesmanager/qube_manager.py

### General notes:

Fresh install.
Did the restore of all my VMs from R3.2

---

**Comment by ThierryIT** [comment]
Hi,
Update has been done. Same problem with a different output.

ValueError: Could not convert string to float: at line 178
of line /usr/lib/python3.5/site-packages/qubesmanager/qube_manager.py

line: vm_start_time = datetime.fromtimestamp(float(vm.start_time))
func: check_if_vm_has_shutdown
line no.: 178
file ....... qube_manager.py

**Comment by ThierryIT** [comment]
The first patch seems to be working.
VMs are now stoping properly, but I do need to refresh Qubes Manager to have the right "states" of the VM (green/yellow spots)

**Comment by Simon-Davies** [comment]
I'm still getting the below error after updating with sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing:

ValueError: Could not convert string to float: at line 178
 of line /usr/lib/python3.5/site-packages/qubesmanager/qube_manager.py

line: vm_start_time = datetime.fromtimestamp(float(vm.start_time))
 func: check_if_vm_has_shutdown
 line no.: 178
 file ....... qube_manager.py

**Comment by lunarthegrey** [comment]
I'm still getting this when I try to shut down a VM in Qubes 4.0 rc4. Same error that Simon got: https://github.com/QubesOS/qubes-issues/issues/3501#issuecomment-364098912

I don't think the new package with the fix in it has been pushed to the testing repo yet though.

**Comment by Simon-Davies** [comment]
This bug is now fixed

**Comment by TheBubblePopped** [comment]
Same problem here, with the addition that it happens only when plasma installed. If not everything works fine.  The only problem here is that with plasma i can t even open a domain VM 

if i try to do the testing thing mentioned above i get in the terminal errors like gvm-ls error unrecognized arguments --kernel
