### ISSUE TITLE
Cannot stop VMs properly / Merge with ticket #3501

### ISSUE THREAD

**Issue by ThierryIT** [QubesOS/qubes-issues#3506]
#### Qubes OS version:

Qubes 4.0 R3

#### Affected TemplateVMs: 

All restored VMs from previous version of Qubes R3.2

---

### Steps to reproduce the behavior:

stop VMs

### Expected behavior:

Stop correctly

### Actual behavior:

Hi,
Update has been done. Same problem with a different output.

ValueError: Could not convert string to float: at line 178
of line /usr/lib/python3.5/site-packages/qubesmanager/qube_manager.py

line: vm_start_time = datetime.fromtimestamp(float(vm.start_time))
func: check_if_vm_has_shutdown
line no.: 178
file ....... qube_manager.py

### General notes:

Seems to be better than #3501 
When stopping the VM, I still do have this error message, but the yellow spot disappear if I refresh Qubes-Manager, and the VM seems to be properly stop.

---

**Comment by marmarek** [comment]
Reopened #3501 instead.
