### ISSUE TITLE
VHM shutdown on iso installation process - copy files to disk

### ISSUE THREAD

**Issue by virgileaime** [QubesOS/qubes-issues#3508]
Hello, i'm running 4.0 rc3.
I am trying to install both Kali and Windows 7 on a qube. The installation process works fine until shutting down abruptly in the middle of copying the files to the partition. 

I have the same problem with kali, win7, win10 and most probably other ISOs as well.
The qube runs with sufficient RAM (6GB and more) and sufficient disk space ...

I am able to run Kali Live however.

Can somebody help ?

**Comment by marmarek** [comment]
See `/var/log/xen/console/guest-VMNAME-dm.log` (replace VMNAME with actual name).
Have you created them as "StandaloneVM" (if using command line) or "Standalone qube not based on template" (if using GUI)?

**Comment by marmarek** [comment]
Ah, yes! Same here: https://github.com/QubesOS/qubes-issues/issues/3432#issuecomment-354362360

**Comment by virgileaime** [comment]
It worked. Disabled memory balancing and set the memory at the same level.
Thanks
