### ISSUE TITLE
Slow inter-vm network speed, turning on scatter gather helps to a degree

### ISSUE THREAD

**Issue by jarlethorsen** [QubesOS/qubes-issues#3510]
#### Qubes OS version:
3.2

#### Affected TemplateVMs: 
Fedora 26

---

### Steps to reproduce the behavior:
Have a 10Gbe network card in netvm. Run "iperf -c <external_serverip>"
Watch result.

Then do the same in appvm connected to netvm.
Watch result.

### Expected behavior:
Running the same iperf command in both netvm and appvm connected to it should show similar performance.

### Actual behavior:
Performance in netvm is a expected (8+ Gbit/s), while appvm is really slow (1.43Gbit/s)
The ksoftirqd process in netvm is showing a very high cpu-load when iperf is run in appvm.

### General notes:
Enabling Scatter Gather on vif* in netvm, and eth0 in appvm ("sudo ethtool -K eth0 sg on") has a huge performance boost. iperf in appvm can now send 4+ Gbit/s, but still far from 10 Gbit/s

Related thread: https://groups.google.com/forum/#!topic/qubes-users/RZVgpndzmow

### UPDATE:
Using the following setup:
appvm<->proxyvm<->netvm

I easily get 19Gbit/s from appvm to proxyvm (if SG is enabled in appvm), but I only get 3-4Gbit/s from proxyvm to netvm. Guess this is something to look into for the developers?

**Comment by ij1** [comment]
Also netvm -> proxyvm direction seems fine with 20Gbps+ after tx checksumming is enabled for the vif. 
This leaves only proxyvm -> netvm direction affected by this issue.

Curiously enough, there's significant difference in RTT depending on which direction the data is being transmitted (3x to 10x larger RTT when netvm is the sink).

**Comment by marmarek** [comment]
For reference:
SG is disabled [here](https://github.com/QubesOS/qubes-core-agent-linux/blob/master/network/setup-ip#L17) and [here](https://github.com/QubesOS/qubes-core-agent-linux/blob/master/vm-systemd/network-proxy-setup.sh#L27). It was introduced by [this commit](https://github.com/QubesOS/qubes-core-agent-linux/commit/5cbb38a2), back in 2011, with comment "Apparently vif frontend has broken sg implementation". Maybe it is no longer the case. Try enabling SG on eth0 in both proxyvm and appvm.
As for tx checksumming, see [here](https://github.com/QubesOS/qubes-core-agent-linux/blob/master/network/vif-route-qubes#L116) - worth checking if it doesn't break HVMs using emulated devices (Windows, or Linux with disabled PV drivers disabled).


> Also, netvm -> proxyvm direction seems fine with 20Gbps+ after tx checksumming is enabled for the vif.
> This leaves only proxyvm -> netvm direction affected by this issue.

Have you enabled SG on eth0 in proxyvm?

**Comment by ij1** [comment]
Thanks for taking a look.

> Have you enabled SG on eth0 in proxyvm?

Yes, SG was enabled for that eth0 and it increases throughput somewhat (roughly from 1.5-2Gbps to 4Gbps) but nowhere near what the opposite direction towards the proxyvm is capable of.

In addition, I've also tried to make sure that there is no TCP receiver window limitation (that the sender might hit due to the extra delay that seems to occur for some reason for that direction) but that just translated to a higher delay and not an increase in the throughput.

Is there perhaps something that causes different behavior in kernel and/or xen related e.g., to the fact that any PCI device is assigned there (that is only done for the netvm in this setup) even if the device used in the intervm test itself is just a virtual one? ...Given that there seems to be some extra delay, something related e.g., to IRQ delivery would seem like a good candidate.

I can later take a look on tx checksumming and HVM to see if I can find some breakage still with it.

**Comment by marmarek** [comment]
> Is there perhaps something that causes different behavior in kernel and/or xen related e.g., to the fact that any PCI device is assigned there (that is only done for the netvm in this setup) even if the device used in the intervm test itself is just a virtual one?

If we're talking about R3.2, there should be no difference. But in 4.0 there is - VMs with PCI devices are HVM, others are PVH.

**Comment by ij1** [comment]
> If we're talking about R3.2, there should be no difference.

R3.2, yes.

**Comment by ij1** [comment]
I'm quite sure now that it has something to with any PCI device being passed into the netvm.

I created a dummy netvm and set it as the netvm for the proxyvm. When the dummy netvm had no PCI devices, the performance is good (at least 14Gbps+). But then I put a PCI device there and I get only roughly 4Gbps through (the PCI device was no even a network device).

For the other direction traffic (netvm->proxyvm), having a PCI device in the proxyvm does not seem to affect performance.

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.

**Comment by MatrixManAtYrService** [comment]
@andrewdavidwong I'm using Qubes 4.0 and I think I'm seeing this same issue.

My numbers are less pronounced (probably because I don't have a gigabit switch) :

sg on, `sys-firewall` to external server: 456 Mbps
sg off, `sys-firewall` to external server: 902 Mbps
`sys-net` to external server: 936 Mbps

...but it's the same pattern.

**Comment by Kixunil** [comment]
It seems like I hit this issue too. Sending is insanely slow - around 30 KiB/s, receiving looks fine. It's impossible to turn on sg on physical adapter in sys-net. Turning on sg in other VMs doesn't help.

**Comment by marmarek** [comment]
> Enabling Scatter Gather on vif* in netvm, and eth0 in appvm ("sudo ethtool -K eth0 sg on") has a huge performance boost.

@fepitre can you try this?

**Comment by fepitre** [comment]
> > Enabling Scatter Gather on vif* in netvm, and eth0 in appvm ("sudo ethtool -K eth0 sg on") has a huge performance boost.
> 
> @fepitre can you try this?

Yes, I've tried that two years ago with good confirmation it was working. I've tested it this morning on separate hardware and between three Qubes instances:

```


                           .------------------------------------------------------.
                           |                      Qubes OS 2                      |
                           |                                                      |
                           |    .--------------------------------------------.    |
                           |    | eth0 (bridge iface) -- eth1 (bridge iface) |    |
                       .------->|                                            |----------.
                       |   |    |                   AppVM                    |    |     |
                       |   |    '--------------------------------------------'    |     |
                       |   |                                                      |     |
                       |   |                                                      |     |
                       |   '------------------------------------------------------'     |
                       |                                                                |
                       |                                                                |
                       |                                                                |
                                                                                        v
     .----------------------------------.                             .----------------------------------.
     |            Qubes OS 1            |                             |            Qubes OS 3            |
     |                                  |                             |                                  |
     |     .---------------------.      |                             |      .---------------------.     |
     |     |       sys-net       |      |                             |      |       sys-net       |     |
     |     '---------------------'      |                             |      '---------------------'     |
     |                ^                 |                             |                 |                |
     |                |                 |                             |                 v                |
     |     .---------------------.      |                             |      .---------------------.     |
     |     |    sys-firewall     |      |                             |      |    sys-firewall     |     |
     |     '---------------------'      |                             |      '---------------------'     |
     |                ^                 |                             |                 |                |
     |                |                 |                             |                 v                |
     |     .---------------------.      |                             |      .---------------------.     |
     |     | AppVM iperf3 client |      |                             |      | AppVM iperf3 server |     |
     |     '---------------------'      |                             |      '---------------------'     |
     '----------------------------------'                             '----------------------------------'
```

- `sg off` (default setup on the three Qubes):
```
[  5]   0.00-1.00   sec  42.3 MBytes   355 Mbits/sec                                                                                         
[  5]   1.00-2.00   sec  43.2 MBytes   363 Mbits/sec                  
[  5]   2.00-3.00   sec  42.9 MBytes   360 Mbits/sec                  
[  5]   3.00-4.00   sec  43.0 MBytes   361 Mbits/sec                  
[  5]   4.00-5.00   sec  42.9 MBytes   360 Mbits/sec                                                                                         
[  5]   5.00-6.00   sec  42.3 MBytes   354 Mbits/sec                                                                                         
[  5]   6.00-7.00   sec  42.3 MBytes   354 Mbits/sec                                                                                         
[  5]   7.00-8.00   sec  43.0 MBytes   361 Mbits/sec                                                                                         
[  5]   8.00-9.00   sec  43.0 MBytes   360 Mbits/sec                                                                                         
[  5]   9.00-10.00  sec  42.6 MBytes   357 Mbits/sec                                                                                         
[  5]  10.00-10.00  sec  79.8 KBytes   516 Mbits/sec
```

- `sg on` (on the three Qubes):

```
[  5]   0.00-1.00   sec   107 MBytes   896 Mbits/sec   73    154 KBytes       
[  5]   1.00-2.00   sec  85.0 MBytes   713 Mbits/sec   42    215 KBytes       
[  5]   2.00-3.00   sec  96.2 MBytes   807 Mbits/sec   10    391 KBytes       
[  5]   3.00-4.00   sec   108 MBytes   902 Mbits/sec   21    334 KBytes       
[  5]   4.00-5.00   sec   108 MBytes   902 Mbits/sec    0    528 KBytes       
[  5]   5.00-6.00   sec   109 MBytes   912 Mbits/sec   20    426 KBytes       
[  5]   6.00-7.00   sec   108 MBytes   902 Mbits/sec   10    441 KBytes       
[  5]   7.00-8.00   sec   108 MBytes   902 Mbits/sec    0    602 KBytes       
[  5]   8.00-9.00   sec   109 MBytes   912 Mbits/sec   10    555 KBytes       
[  5]   9.00-10.00  sec   108 MBytes   902 Mbits/sec    0    689 KBytes
```

To confirm that I've set `sg on` successively on each virtual upstream `eth0` inside `sys-firewall` and the qubes where `iperf3` is  started as client and server. Setting `sg on` on bridge interfaces on Qubes 2 shows very small differences ~ 5%.

**Comment by coolios11** [comment]
Hi Guys, I am having the same problem recently upgrade to 1000mbs speeds and I can't get more than 200-300 mbs, sometimes it drops to 11mbs. I have disposobale net VM running with kick secure16 template. I have all supporting hardware for the 1000mbs speeds. But tried to follow this guide but it wouldn't work. Would someone be able to help me please :(
