### ISSUE TITLE
Rudd-O's Network Server supports PVM. It needs to support HVM

### ISSUE THREAD

**Issue by tlaurion** [QubesOS/qubes-issues#3512]
#### Qubes OS version:

R3.2, R4.0

#### Affected TemplateVMs: 

---

### Steps to reproduce the behavior:

Only PVM is supported

### Expected behavior:

HVM support is needed

### General notes:

---

#### Related issues:

https://github.com/Rudd-O/qubes-network-server/issues/4

**Comment by andrewdavidwong** [comment]
FYI @Rudd-O.

**Comment by tlaurion** [comment]
What part changed in Qubes so that the theory of application is invalid in Qubes4 and HVM?

Theory of operation
Qubes OS relies on layer 3 (IP) routing. VMs in its networked tree send traffic through their default route interfaces, which upstream VMs receive and masquerade out of their own default route interfaces.

Qubes network server slightly changes this when a networked VM — a VM which has had its static_ip attribute set with qvm-static-ip — exists on the networked tree. As soon as a networked VM boots up, Qubes network server:

sets a static /32 route on every upstream VM to the networked VM's static IP, directing the upstream VMs to route traffic for that IP to their VIFs where they may find the networked VM
enables ARP neighbor proxying for the static IP on every upstream VM, such that every upstream VM announces itself to their own upstream VMs (and LAN, in the case of NetVMs) as the networked VM
sets firewall rules on every upstream VM that allow normal non-masquerading forwarding to and from the IP of the networked VM
(depending on the Qubes firewall policy of the networked VM) sets rules on every upstream ProxyVM that allow for certain classes of inbound traffic
(depending on the Qubes firewall policy of the networked VM) sets rules directly on the networked VM that allow for certain classes of inbound traffic

**Comment by tlaurion** [comment]
@marmarek @Rudd-O @andrewdavidwong @jpouellet @lamuse: Any documentation pointing to how to recreate a proper development environment to develop tools destined for dom0?  I can't believe that the only solution in [porting to the new qubesadmin api](https://github.com/Rudd-O/qubes-network-server/issues/5) is to repackage and deploy!?

**Comment by tlaurion** [comment]
Found it. 

https://www.qubes-os.org/doc/development-workflow/

**Comment by tlaurion** [comment]
Discussion [here](https://github.com/QubesOS/qubes-issues/issues/4028#issuecomment-399844929)

**Comment by andrewdavidwong** [comment]
> Thank you for opening the ticket. It may be difficult for me to adapt
to 4.0, so I kindly request anyone with the required skillset to send a
pull request adapting it to 4.0.

Since this is a feature request for a separate project, please open it on that project's issue tracker instead:

https://github.com/Rudd-O/qubes-network-server/issues

**Comment by Rudd-O** [comment]
HVM support should work as long as there's an agent that looks at the IP address in Qubes DB and sets the host's network card IP parameters correctly.

4.0 support is out and integrates with Qubes AdminVM. Enjoy!
