### ISSUE TITLE
New VMs without devices are HVM instead of PVH

### ISSUE THREAD

**Issue by mirrorway** [QubesOS/qubes-issues#3515]
#### Qubes OS version:

4.0 tracking current-testing

#### Affected TemplateVMs: 

Tested with debian-9.

### Steps to reproduce the behavior:

1. Create new AppVM using menu. Do not assign any devices.
2. Run `qvm-prefs <vm> virt_mode`

### Expected behavior:

pvh

### Actual behavior:

hvm

### General notes:

You can fix it by manually doing `qvm-prefs <vm> virt_mode --default`. But new users might not know this and wonder why their system is so slow...

**Comment by marmarek** [comment]
Indeed, GUI tool for creating new qube set `virt_mode` instead of leaving default. It should only set it to `hvm` if "install system from device" option is selected. And even that may not be necessary in some near future (but not now yet).
