### ISSUE TITLE
Qubes 4.0-rc4 installation with setting "create sys-usb" first run error

### ISSUE THREAD

**Issue by errin07** [QubesOS/qubes-issues#3518]
#### Qubes OS version:           

R4.0-rc4

#### Affected TemplateVMs: 

dom0

---

### Steps to reproduce the behavior:

Select "create sys-usb" from first boot/setup menu.

### Expected behavior:

Installation finished successful.

### Actual behavior:

Start failed: internal error: Unable to reset PCI device 0000:00:14.0: internal error: libxenlight failed to create new domain sys-usb

libxl-driver.log:
`2018-02-02 07:57:23.651+0000: libxl: libxl_pci.c:993:qemu_pci_add_xenstore: qemu refused to add device: 0000:00:14.0,msitranslate=0,power_mgmt=0
2018-02-02 07:57:23.652+0000: libxl: libxl_pci.c:1338:libxl__add_pcidevs: libxl_device_pci_add failed: -3
2018-02-02 07:57:23.652+0000: libxl: libxl_create.c:1512:domcreate_attach_devices: unable to add pci devices
2018-02-02 07:57:23.658+0000: libxl: libxl_pci.c:1176:libxl__device_pci_reset: The kernel doesn't support reset from sysfs for PCI device 0000:00:14.0`

qvm-pci:
`dom0:00_14.0  USB controller: Intel Corporation 7 Series/C210 Series Chipset Family USB xHCI Host Controller  sys-usb (no-strict-reset=True)`

### General notes:

Fresh Installation R4.0-rc4
Setting 'sys-usb virt_mode pv' works.

---

**Comment by pachulo** [comment]
I'm facing the same issue.
Apart from using `virt_mod pv`, detaching the offending controller makes sys-usb work with default config.

**Comment by marmarek** [comment]
@pachulo do you also have exact this message:
```
2018-02-02 07:57:23.651+0000: libxl: libxl_pci.c:993:qemu_pci_add_xenstore: qemu refused to add device: 0000:00:14.0,msitranslate=0,power_mgmt=0
2018-02-02 07:57:23.652+0000: libxl: libxl_pci.c:1338:libxl__add_pcidevs: libxl_device_pci_add failed: -3
```
?

Can you find related fragments of `/var/log/xen/console/hypervisor.log` (if any) and `/var/log/xen/console/guest-sys-usb-dm.log` from that time?

**Comment by pachulo** [comment]
Hey @marmarek !

Just to make sure that all the information is here: When I do:

`$ sudo systemctl status qubes-vm@sys-usb`

I see:

`Start failed: internal error: Unable to reset PCI device 0000:00:14.0: internal error: libxenlight failed to create new domain sys-usb`

The I see those exact messages in **/var/log/libvirt/lixl/libxl-driver.log**:

Then, in **/var/log/xen/console/hypervisor.log** the last message is:

`(XEN) pt_irq_create_bind failed (-16) for dom1`

And in **/var/log/xen/console/guest-sys-usb-dm.log**:

**Comment by sudomain** [comment]
I just want to add that I'm experiencing this on the final 4.0 release and my logs basically mirror @pachulo 's logs. A major difference for me is that I didn't create sys-usb at first boot. I installed dom0 updates then tried creating sys-usb using:
`sudo qubesctl state.sls qvm.sys-usb`
(per the docs).
I have 3 USB controllers and have tried giving various combinations of the 3 to sys-usb (as well as toggling no-strict-reset on some of them). For me, detaching the offending controller does not result in a working sys-usb, but thankfully switching to PV mode does. 
Trying to run sys-usb without any of the controllers attached results in this error:
`qrexec-daemon startup failed: connection to the vm failed`

**Comment by marmarek** [comment]
> (XEN) [VT-D] It's risky to assign 0000:00:1a.0 with shared RMRR at b9c0f000 for Dom1.

Note it's about different device.

> (XEN) pt_irq_create_bind failed (-16) for dom1

Can you provide more details about this device (00:14.0)? Like
this: `sudo lspci -vvs 00:14.0` in dom0. Especially interesting part is
about interrupt and MSI capabilities.
You can also add `pci=nomsi` kernel option for that VM (qvm-prefs, see
kernelopts property).

**Comment by sudomain** [comment]
> You can also add `pci=nomsi` kernel option for that VM (qvm-prefs, see kernelopts property).
I created a fresh sys-usb and appended the 'pci=nomsi' kernel option to the existing options using this command (in dom0):
`qvm-prefs -s sys-usb kernelopts "nopat iommu=soft swiotlb=8192 pci=nomsi"`
Is this the correct way to add that kernel option?
I got the same error as before (Unable to reset PCI device 0000:00:14.0)

> Can you provide more details about this device (00:14.0)? Like this: `sudo lspci -vvs 00:14.0` in dom0.
I realize this wasn't directed toward me since I didn't mention a BDF address in my first comment, but maybe info about my faulty PCI device (which also happens to be 00:14.0) will be helpful:

`00:14.0 USB controller: Intel Corporation 7 Series/C210 Series Chipset Family USB xHCI Host Controller (rev 04) (prog-if 30 [XHCI])
	Subsystem: Hewlett-Packard Company Device 179b
	Control: I/O- Mem- BusMaster- SpecCycle- MemWINV- VGASnoop- ParErr- Stepping- SERR- FastB2B- DisINTx-
	Status: Cap+ 66MHz- UDF- FastB2B+ ParErr- DEVSEL=medium >TAbort- <TAbort- <MAbort- >SERR- <PERR- INTx-
	Interrupt: pin A routed to IRQ 10
	Region 0: Memory at d4720000 (64-bit, non-prefetchable) [disabled] [size=64K]
	Capabilities: [70] Power Management version 2
		Flags: PMEClk- DSI- D1- D2- AuxCurrent=375mA PME(D0-,D1-,D2-,D3hot+,D3cold+)
		Status: D0 NoSoftRst+ PME-Enable- DSel=0 DScale=0 PME-
	Capabilities: [80] MSI: Enable- Count=1/8 Maskable- 64bit+
		Address: 0000000000000000  Data: 0000
	Kernel driver in use: pciback
	Kernel modules: xhci_pci
`
I think I'm having the same issue given the similarity of our logs, but it may be different due to the slightly different behavior that I mentioned in my first comment (sys-usb not starting even with all devices removed). Should I open a separate issue given this difference in behavior?

**Comment by that1consultant** [comment]
I just want to note that running qvm-prefs sys-usb virt_mode pv in dom0 resolved this issue for me.

**Comment by pachulo** [comment]
Is there anything else we can do to help resolve this @marmarek ?

**Comment by manhack** [comment]
I had the same problem with a fresh 4.0 install, @that1consultant command line fixed the issue, including after a reboot, thanks (but could be worth mentioned on https://www.qubes-os.org/doc/usb/) !

**Comment by brycepg** [comment]
I ran into this installing Qubes 4.0. `sys-usb` doesn't even exist.

I'm seeing an error in my journalctl log that might be relevant:

```
----------
ID: sys-net-usb
Function: qvm.prefs
Name: sys-net
Result: False
Comment: An exception occurred in this state: Traceback (most recent call last):
      File "/usr/lib/python2.7/site-packages/salt/state.py", line 1837, in call
	**cdata['kwargs'])
      File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1794, in wrapper
	return f(*args, **kwargs)
      File "/var/cache/salt/minion/extmods/states/ext_state_qvm.py", line 296, in prefs
	return _state_action('qvm.prefs', name, *varargs, **kwargs)
      File "/var/cache/salt/minion/extmods/states/ext_state_qvm.py", line 140, in _state_action
	status = __salt__[_action](*varargs, **kwargs)
      File "/var/cache/salt/minion/extmods/modules/ext_module_qvm.py", line 902, in prefs
	args.vm.devices['pci'].detach(current_assignment)
      File "/usr/lib/python2.7/site-packages/qubesadmin/devices.py", line 180, in detach
	device_assignment.ident))
      File "/usr/lib/python2.7/site-packages/qubesadmin/base.py", line 68, in qubesd_call
	payload_stream)
      File "/usr/lib/python2.7/site-packages/qubesadmin/app.py", line 557, in qubesd_call
	return self._parse_qubesd_response(return_data)
      File "/usr/lib/python2.7/site-packages/qubesadmin/base.py", line 102, in _parse_qubesd_response
	raise exc_class(format_string, *args)
    QubesVMNotHaltedError: Can not remove a persistent attachment from a non halted vm
Started: 16:55:10.524234
Duration: 314.957 ms
Changes:   
```

**Comment by czepiec** [comment]
I have exact the same problem like others, only partial workaround is PV mode.
I have notebook HP Folio 9470m, lspci for that USB:
```
00:14.0 USB controller: Intel Corporation 7 Series/C210 Series Chipset Family USB xHCI Host Controller (rev 04) (prog-if 30 [XHCI])
	Subsystem: Hewlett-Packard Company Device 18df
	Control: I/O- Mem+ BusMaster+ SpecCycle- MemWINV- VGASnoop- ParErr- Stepping- SERR- FastB2B- DisINTx+
	Status: Cap+ 66MHz- UDF- FastB2B+ ParErr- DEVSEL=medium >TAbort- <TAbort- <MAbort- >SERR- <PERR- INTx-
	Latency: 0
	Interrupt: pin A routed to IRQ 63
	Region 0: Memory at d0720000 (64-bit, non-prefetchable) [size=64K]
	Capabilities: [70] Power Management version 2
		Flags: PMEClk- DSI- D1- D2- AuxCurrent=375mA PME(D0-,D1-,D2-,D3hot+,D3cold+)
		Status: D0 NoSoftRst+ PME-Enable- DSel=0 DScale=0 PME-
	Capabilities: [80] MSI: Enable+ Count=1/8 Maskable- 64bit+
		Address: 00000000fee00318  Data: 0000
	Kernel driver in use: pciback
	Kernel modules: xhci_pci
```
I can provide any other information or log files.

**Comment by arno01** [comment]
> 07:57:23.658+0000: libxl: libxl_pci.c:1176:libxl__device_pci_reset: The kernel doesn't support reset from sysfs for PCI device 0000:00:14.0

@marmarek it looks like this error related to this code https://xenbits.xen.org/gitweb/?p=xen.git;a=blob;f=tools/libxl/libxl_pci.c;h=6f8f49c7c0a80478b244c52ae65e75f8a78c6481;hb=b03cee73197f4a37bf2941b9367105187355e638#l1150

I know we have the [no-strict-reset patch](https://github.com/QubesOS/qubes-core-libvirt/blob/release4.0/patches.qubes/0010-Add-nostrictreset-attribute-to-PCI-host-devices.patch#L160) which allows the libvirt to assign the PCI device that does not support any reset method (``FLReset-``), but how about Xen's libxl - shouldn't we add ``return 0`` there as well?

**Comment by arno01** [comment]
Hum, I glanced once more at the ``libxl__device_pci_reset()`` and figured that it does not seem to matter at all what return code it returns. As the parent functions `libxl__device_pci_add()` and `do_pci_remove()` do not seem to take into account the return code from the ``libxl__device_pci_reset()``.

**Comment by DemiMarie** [comment]
I wonder if this is due to a broken IOMMU implementation in the hardware.  @marmarek?

**Comment by marmarek** [comment]
No, device reset is mostly unrelated to IOMMU. And indeed many devices doesn't support proper reset themselves so ability to properly reset them mostly depends on the PCI topology - if such device is behind a separate bridge, you can reset the whole bridge. Otherwise, you can just hope the device driver will cope with possibly weird initial state it will find device in. In that last case, it is also unsafe to switch device between different domains (because it can retain some state from the previous one).
IOMMU (unless hardware bug) will still isolate that device from other parts of the system.

Issues like this are the reason why you can find in many places disclaimers that PCI passthrough is unsafe in generic case.

Anyway, back to the topic - this sounds related to https://github.com/QubesOS/qubes-issues/issues/6203#issuecomment-733189229, although not sure if is it the same as the original issue reported in 2018.
