### ISSUE TITLE
Qubes Settings / Running applications

### ISSUE THREAD

**Issue by ThierryIT** [QubesOS/qubes-issues#3522]
#### Qubes OS version:

4.0 r4

#### Affected TemplateVMs: 

---

### Steps to reproduce the behavior:

Qube/Setting add applications

### Expected behavior:

Be able to run chosen application from Applications/Domains: vname

### Actual behavior:

Not working, have to run chosen applications from : Run command in Qube

### General notes:

never work since move to Qubes 4.0

---

**Comment by marmarta** [comment]
How much RAM do you have? Maybe there's a problem with that. Do you have anything in `.xessession-errors ` in dom0?

**Comment by ThierryIT** [comment]
Seems to be coming from the ones who have been restored from 3.2 ...
I do not have any .xessession-errors

**Comment by ThierryIT** [comment]
oupsss my mistake, I do have an .xsession-errors
If starting keepassX :

- executed QUBESRPC qubes.WaitForSession dom0 pid 2741
send exit code 0
pid 2741 exited with 0
executed (nowait) QUBESRPC qubes.StartApp+keepassx dom0 pid 2753
send exit code 

and nothing else happen ....

**Comment by ThierryIT** [comment]
Even if from `dom0` I have done an: `qvm-sync-appmenus vmname  `
Thx

**Comment by ThierryIT** [comment]
allo ?

**Comment by marmarek** [comment]
3.2 VMs did not have `qubes.StartApp` service. I haven't yet fully developed template upgrade procedure (right now it is mostly manual, involving manual key import, repository switch etc).
But you should be able to switch to 3.2-way appmenus, by adding `appmenus-legacy` feature to that StandaloneVM/TemplateVM. Just to clarify - is it the case? It shouldn't be if you restore 3.2 AppVM but use a template from 4.0.

How to enable `appmenus-legacy` feature: `qvm-features NAME_OF_VM appmenus-legacy 1`

**Comment by ThierryIT** [comment]
Hi,
Doesn't seems to work for me.
This is a StandaloneVM.
Thx

**Comment by marmarek** [comment]
Have you called `qvm-sync-appmenus` after this change?

**Comment by ThierryIT** [comment]
no I have restated the VM

**Comment by ThierryIT** [comment]
After an update on my VM, seems to now work ...
Thx
