### ISSUE TITLE
Devices Widget: can't detach USB device

### ISSUE THREAD

**Issue by awokd** [QubesOS/qubes-issues#3525]
#### Qubes OS version:

R4.0rc4

#### Affected TemplateVMs: 

---

### Steps to reproduce the behavior:

Connect (non-block) USB device to a VM
Click on Eject in Device Widget to attempt to disconnect from VM

### Expected behavior:

USB device detached from VM

### Actual behavior:

USB device remains bold and attached to VM

### General notes:

Target VM syslog/journalctl displays message similar to "Device attach failed: No device info received, connection failed, check backend side for details"

---

#### Related issues:

https://github.com/QubesOS/qubes-issues/issues/3215

**Comment by awokd** [comment]
Attempting to use qvm-usb to attach results in the same "backend side failed" message.
Installing qubes-usb-proxy in sys-usb's template restored correct function to Device Widget's Eject. It already had qubes-input-proxy-sender.

Potential cause: Devices Widget not recognizing a failure message when used to connect a USB device

**Comment by awokd** [comment]
Same behavior noted when using widget to assign device to an AppVM that doesn't have qubes-usb-proxy installed. It gets "stuck" there and can't be unassigned with the widget. Physically removing the USB device works around it.

**Comment by kototama** [comment]
I have the same problem when the VM where the USB device was attached is shutdown before detaching. It's not possible then to detach from command line or UX. Should I create another ticket for that?

**Comment by andrewdavidwong** [comment]
> I have the same problem when the VM where the USB device was attached is shutdown before detaching. It's not possible then to detach from command line or UX. Should I create another ticket for that?

I recommend seeing if the patches for this issue fix it. If you have reason to believe your issue is different and will not be resolved by the patches for this one, please file a separate issue and take care to explain why it's not a duplicate of this one.

**Comment by marmarek** [comment]
This other problem is fixed here: https://github.com/QubesOS/qubes-desktop-linux-manager/pull/15
