### ISSUE TITLE
qubes manager "Update qube" doesn't work

### ISSUE THREAD

**Issue by mirrorway** [QubesOS/qubes-issues#3526]
#### Qubes OS version:

R4.0 rc4

#### Affected TemplateVMs: 

debian-9, fedora-26

---

### Steps to reproduce the behavior:

1. open qubes manager
2. right-click a template and choose Update qube

### Expected behavior:

The R3.2 behavior, namely: an xterm window opens and distro-specific updater runs.

### Actual behavior:

VM may start but updater doesn't run.

**Comment by subproc** [comment]
same here, and dom0 update through qubes manager do the same

**Comment by JPL1** [comment]
I can confirm this one too
