### ISSUE TITLE
Sys-net terminal opens on booting - can't close it

### ISSUE THREAD

**Issue by JPL1** [QubesOS/qubes-issues#3534]
#### Qubes OS version:
R4.0 rc4

### Expected behavior:
Qubes OS boots to blank desktop

### Actual behavior:
A red sys-net terminal opens. It is completely unresponsive. Will not accept text entry, cannot be closed down by right clicking or clicking the 'x' button.

### General notes:
No harm done, but annoying

---

**Comment by mirrorway** [comment]
In the Basic tab of the GUI, try unchecking "Run in debug mode".

**Comment by JPL1** [comment]
Thanks for the suggestion. "Run in debug mode" is not checked.
