### ISSUE TITLE
Create and update website man pages for CLI tools

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#3538]
Use the existing RST man pages in each respective tools' repo to render Markdown pages for the Qubes website. The results should be used to populate these pages:

 * https://www.qubes-os.org/doc/tools/3.2/dom0/
 * https://www.qubes-os.org/doc/tools/3.2/domU/
 * https://www.qubes-os.org/doc/tools/4.0/dom0/
 * https://www.qubes-os.org/doc/tools/4.0/domU/

Related issue: #3495

**Comment by awokd** [comment]
Would it be possible to update 3.2 pages as well? For example, I tried to link to `qvm-grow-root` but it's not there!

**Comment by andrewdavidwong** [comment]
> Would it be possible to update 3.2 pages as well? For example, I tried to link to `qvm-grow-root` but it's not there!

Just to confirm: The problem is that we *never* had a page for `qvm-grow-root` on the website, not that it was there but subsequently disappeared, right?

**Comment by awokd** [comment]
That is my understanding, yes. Believe this is a relatively new command for R3.2 (only, not 4.0) that never had a page on the website. There may be others; that's just one I wanted at the time.

**Comment by andrewdavidwong** [comment]
@awokd: The Qubes 3.2 man pages should all be up-to-date now.

**Comment by awokd** [comment]
Nice, thank you @andrewdavidwong . So if I want to link to a specific version of qvm-whatever it's /doc/tools/3.2/dom0/qvm-whatever, while /doc/dom0-tools/qvm-whatever will always point to the latest version available?

**Comment by andrewdavidwong** [comment]
No, `/doc/dom0-tools/qvm-whatever` redirects to the 3.2 version.
