### ISSUE TITLE
change default password manager from keepassx to keepassxc

### ISSUE THREAD

**Issue by mfc** [QubesOS/qubes-issues#3542]
#### Qubes OS version:

R3.2, R4.0

#### Affected TemplateVMs: 

fedora-26

---

KeePassX was last updated in October 2016:

https://www.keepassx.org/news/
https://www.openhub.net/p/keepassx

Since then most development has happened on a fork called KeePassXC:

https://keepassxc.org/blog/
https://github.com/keepassxreboot/keepassxc/
https://www.openhub.net/p/keepassxc

it includes many bugfixes, feature requests, and is generally responsive to users. it is in the default Fedora 26 repos as `keepassxc`.

**Comment by andrewdavidwong** [comment]
Is the current default chosen by Fedora? If so, this may be relevant:

https://www.qubes-os.org/faq/#what-is-qubes-attitude-toward-changing-guest-distros

**Comment by mfc** [comment]
there isn't a default password manager, we chose the default password manager (if any) that is included in Fedora templates.

**Comment by andrewdavidwong** [comment]
Oh, ok then! :+1:

**Comment by schnurentwickler** [comment]
keepassxc depends on Qt5. So instead 2-3 MB of installation size in fedora it demands around 40 MB.
Maybe use the vault based on debian template and Qt stuff.

**Comment by dmoerner** [comment]
+1 for this. Note that the worry about installation size is now moot: keepassx appears to be the only thing in the standard template depending on qt4, and switching to keepassxc and bringing in qt5 instead produces almost no change in size.

I think that we need to make this change eventually, keepassx is just getting quite old. KeepassXC has strong support for yubikeys, etc.

One reason to actually make this change soon is that although keepassxc is currently backwards compatible with keepassx, they have switched to a new key file implementation (https://github.com/keepassxreboot/keepassxc/pull/1326), and it currently warns users about using the old-style keys (https://github.com/keepassxreboot/keepassxc/pull/1327). It will ease any eventual transition if users have plenty of time to switch to new-style keys.

**Comment by andrewdavidwong** [comment]
Why do we modify the Fedora template to add a password manager, @marmarek? Why not follow our usual [policy](https://www.qubes-os.org/faq/#what-is-qubes-attitude-toward-changing-guest-distros) and leave it up to users to install (or refrain from installing) whichever password manager they like?

**Comment by mfc** [comment]
I think because `vault` is a great/popular suggested/example qube for users, in order to understand the compartimentalization/integration benefits of Qubes.

Given it has been a practice for a long time with new Qubes installations and I think it has clear benefits, I would suggest we make an exception to the policy for this.

**Comment by marmarek** [comment]
Yes, exactly, shipping vault qube by default, with password manager installed IMO is a nice suggestion how to compartmentalize data.

**Comment by marmarek** [comment]
That said, I can't find where (if at all) we add it by default to vault's menu. This step might be missing, making this addition less discoverable...
