### ISSUE TITLE
bind-dirs.sh silently fails if any of the config dirs are empty

### ISSUE THREAD

**Issue by lvh** [QubesOS/qubes-issues#3552]
#### Qubes OS version:

Any, though observed on 4.0RC4

#### Affected TemplateVMs: 

Any, though observed on fedora-26

### Steps to reproduce the behavior:

- Create e.g. /rw/config/qubes-bind-dirs.d/ in the template based VM and also put a real config file in /etc/qubes-bind.dirs.d/ in the template 
- Reboot VM or unmount & remount bind dirs 
- Bind mount in /etc/ doesn't work (silently on reboot)

### Expected behavior:

/etc/ specified bind mount is mounted

### Actual behavior:

/etc/ specified bind mount is not mounted

### General notes:

The bind-dirs.sh script checks if the different config directories exist with -d, but not if they're empty. Perhaps the easiest way to fix this is to use find to find all the config files?

**Comment by adrelanos** [comment]
It's using `shopt -s nullglob`. So an empty config folder shouldn't matter.

We need to know the exact error message why it is failing. What is the output of...?

    sudo systemctl --no-pager status qubes-mount-dirs.service

**Comment by rustybird** [comment]
The glob was evaluated before `shopt -s nullglob` - https://github.com/QubesOS/qubes-core-agent-linux/pull/91
