### ISSUE TITLE
kernel 4.14.13-3 in dom0 breaks resume on a thinkpad x230

### ISSUE THREAD

**Issue by h01ger** [QubesOS/qubes-issues#3555]
#### Qubes OS version:

3.2

#### Affected TemplateVMs: 

all

---

### Steps to reproduce the behavior:

install kernel and kernel-qubes-vm 4.14.13-3 from qubes-dom0-current-testing on a thinkpad x230 with coreboot, reboot into it, and suspend. then resume, and the screen stays black, forcing one into a reboot. also could reproduce this without starting any app-vms.

### Expected behavior:

resume works.

### Actual behavior:

screen stays black. the disk activity led is on though.

### General notes:

running kernel 4.9 in dom0 and 4.14.3 in the VMs seems to be a working workaround.

---

**Comment by h01ger** [comment]
so 4.14.18-1 seems to work at least a little better, so far it has survived one suspend/resume cycle, but then the external display didnt work anymore (which is not a regression as it happened before on Qubes 3.2), so I had to reboot anyway. 

I will keep this bug updated about how further suspend/resume cycles behave.

I just now wonder: I have 4.14.18, 4.14.13 and 4.9.56 installed. The next kernel update will thus remove 4.9.56 - how can I instead remove 4.14.13 so that 4.9.56 is kept?

**Comment by marmarek** [comment]
> so 4.14.18-1 seems to work at least a little better, so far it has survived one suspend/resume cycle, but then the external display didnt work anymore (which is not a regression as it happened before on Qubes 3.2), so I had to reboot anyway.

In some cases switching to text console and back helps.


> I just now wonder: I have 4.14.18, 4.14.13 and 4.9.56 installed. The next kernel update will thus remove 4.9.56 - how can I instead remove 4.14.13 so that 4.9.56 is kept?

Yes. Or increase `installonly_limit` in `/etc/dnf/dnf.conf`.

**Comment by h01ger** [comment]
On Sat, Feb 10, 2018 at 12:43:11PM -0800, Marek Marczykowski-Górecki wrote:
> > so 4.14.18-1 seems to work at least a little better, so far it has survived one suspend/resume cycle, but then the external display didnt work anymore (which is not a regression as it happened before on Qubes 3.2), so I had to reboot anyway.
> In some cases switching to text console and back helps.
 
will try that next time…

> > I just now wonder: I have 4.14.18, 4.14.13 and 4.9.56 installed. The next kernel update will thus remove 4.9.56 - how can I instead remove 4.14.13 so that 4.9.56 is kept?
> Yes. Or increase `installonly_limit` in `/etc/dnf/dnf.conf`.

thanks, done this now.


-- 
cheers,
	Holger

**Comment by h01ger** [comment]
so 4.14.18-1 seems to work at least a little better, so far it has survived one suspend/resume cycle, but then the external display didnt work anymore (which is not a regression as it happened before on Qubes 3.2), so I had to reboot anyway. 

I will keep this bug updated about how further suspend/resume cycles behave.

I just now wonder: I have 4.14.18, 4.14.13 and 4.9.56 installed. The next kernel update will thus remove 4.9.56 - how can I instead remove 4.14.13 so that 4.9.56 is kept?

**Comment by h01ger** [comment]
4.14.18 is not much better, after the initial success I do not remember one working resume in the last two days, maybe there was one, but I dont think there were two :(

**Comment by marmarek** [comment]
I can't reproduce... tried about 10 times suspend/resume cycle on x230 (+coreboot) and it just works. 4.14.18 in dom0 and all VMs.

**Comment by h01ger** [comment]
On Tue, Feb 13, 2018 at 03:47:26AM +0000, Marek Marczykowski-Górecki wrote:
> I can't reproduce... tried about 10 times suspend/resume cycle on x230 (+coreboot) and it just works. 4.14.18 in dom0 and all VMs.

fascinating. guess it's time to swap the disk into another x230 then and see if
it behaves the same. will keep this bug posted. thanks!


-- 
cheers,
	Holger

**Comment by h01ger** [comment]
4.14.18 is not much better, after the initial success I do not remember one working resume in the last two days, maybe there was one, but I dont think there were two :(

**Comment by h01ger** [comment]
marmarek: does your coreboot use the intel vga blob or the free vga bios written in ada? (thinking about what else than hardware could cause this…)

**Comment by marmarek** [comment]
intel one

**Comment by marmarek** [comment]
In `.config` I see also `CONFIG_S3_ROM_RUN=y`, not sure if relevant.

**Comment by grote** [comment]
@h01ger any update here? Which kernel works best for you? I seem to have run into the same problem on an X230 (still without coreboot).

**Comment by h01ger** [comment]
On Wed, May 30, 2018 at 08:12:15PM -0700, Torsten Grote wrote:
> @h01ger any update here? Which kernel works best for you? I seem to have run into the same problem on an X230 (still without coreboot).

I now use 4.14.35-1 and resume is almost reliable now, i'd say it works
in 95% of the cases (or maybe more even).

But, this is not really due to the kernel but rather because of using
the lenovo bios again, though I also believe it would be fine with
coreboot if I were using the non-free intel vga blob with coreboot.

This has yet to be confirmed though. (And then the free intel vga bios
needs to be fixed…)

And: wireless is still often broken after resume, but I have found a
workaround now: watch sys-net's console log and suspend+resume until
sys-net comes back with wireless working. This workaround is only
possible because resume is rather stable now…


-- 
cheers,
	Holger

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 has reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.

**Comment by grote** [comment]
Btw. in case somebody else finds this. I had this issue also with Qubes 4, but solved it by updating the bios on the thinkpad.
