### ISSUE TITLE
Display blank / won't refresh image after suspend/resume

### ISSUE THREAD

**Issue by Joeviocoe** [QubesOS/qubes-issues#3558]
#### Qubes OS version:
R4.0 (RC4)

---

### Steps to reproduce the behavior:
Suspend using any such as xfce4-session-logout --suspend
...wait for full suspend...
Resume system

### Expected behavior:
All monitors come back and system resumes as normal

### Actual behavior:
Any monitors that were inverted or rotated, will be black.  
The mouse does move across the screen... but no objects move on this screen.  

Refreshing the configurations by toggling to another terminal (ctrl-alt-f2) then back again (ctrl-alt-f1), or changing the resolution/position of screens in xrandr/arandr/etc/... will restore the last known image on the affected monitors.  

Reconfiguring the affected screen to remove invert/rotate settings does restore the image refreshing ability.  The monitors behave normal, but I need them inverted.

Logging off or restarting X server does not fix the issue.
A reboot is needed to restore the desired behavior of having a working and inverted screen.

**Comment by Joeviocoe** [comment]
Advanced Micro Devices, Inc. [AMD/ATI] Cape Verde PRO [Radeon HD 7750/8740 / R7 250E] [1002:683f] (rev 87) (prog-if 00 [VGA controller])

The graphics card is a 6 output DisplayPort card.  It works just fine on Qubes 3.2 without any additional so it has to be software related.

**Comment by andrewdavidwong** [comment]
Possibly related: #2420, #2387.

**Comment by Joeviocoe** [comment]
Anyone able to reproduce this on their own system?

**Comment by marmarek** [comment]
There is new kernel (4.14.18) in testing repository, try that.

**Comment by Joeviocoe** [comment]
I've been running with testing repo enabled.... and have had this kernel since the 8th.
Feb 08 18:24:51 INFO Installed: kernel-1000:4.14.18-1.pvops.qubes.x86_64

No difference, still a problem.
Thanks.

**Comment by marmarek** [comment]
There is also "kernel-latest" package, at 4.15.1 right now.

**Comment by marmarek** [comment]
A workaround idea: remove invert/rotate settings before suspend and apply them again after resume.

**Comment by Joeviocoe** [comment]
Thanks.  But that doesn't work.
It really isn't the state of having an inverted monitor at suspend time.  But rather, after suspend/resume,... I lose the ability to have rotated or inverted monitors.

The resolution is fine, and restarting X server and lightdm have no effect.
If unloading drivers at suspend time, and loading them at resume would help... I wouldn't know where to start.

Thanks.

**Comment by X4lldux** [comment]
I can also confirm having this problem.
The workaround doesn't work for me either.

**Comment by marmarek** [comment]
Do you have any related messages in dom0 kernel log or X server log?

**Comment by marmarek** [comment]
There is new kernel-latest package available (4.15.6), which should have panic on boot problem resolved.

**Comment by Joeviocoe** [comment]
[kernel.log](https://github.com/QubesOS/qubes-issues/files/1783253/kernel.log)

[Xorg.0.log](https://github.com/QubesOS/qubes-issues/files/1783251/Xorg.0.log)

**Comment by Joeviocoe** [comment]
The kernel-latest (4.15.6) does boot... but does not help the problem.

Also, I notice after resume... 
Every 5-7 seconds, the whole system will freeze/lag for about ~2 seconds.  The mouse moves, but I cannot click, drag, type, etc during that time.

**Comment by marmarek** [comment]
I don't see anything obviously related in those logs, there are even some gpu self tests after resume and all passed.
Do you know if it works on baremetal system using similar kernel? Fedora 27 Live should have 4.13 kernel. Do you remember on what kernel version on 3.2 it worked (initially 3.2 was released with 4.4.x, later updated to 4.9.x).

**Comment by Joeviocoe** [comment]
With 3.2, both 4.4 and 4.9 had major issues with suspend/resume.  But mostly that it would not come out of suspend at all.  All screens black, no response, not even switching terminals... and have to force kill with power switch.  So 4.0 has been better in that regard.  I have not tried bare metal running a fedora live cd.
