### ISSUE TITLE
No VM shutdown notifications

### ISSUE THREAD

**Issue by marmarta** [QubesOS/qubes-issues#3560]
#### Qubes OS version: R4.0rc4
If a VM is halted from inside (e.g., a template after updates), no notification at all is emitted. If 

### Steps to reproduce the behavior:
Shutdown a VM.

### Expected behavior:
Two notifications are emitted: one when shutdown process begins ([VM] is halting) and one when it's complete ([VM] is halted)

### Actual behavior:
If the VM is shut down from inside (e.g., after a template VM update completes), no notification at all is emitted. 
If the VM is shut down from manager or the qui-domains tool, only the [VM] is halting notification appears, and nothing about how shutdown was completed.

**Comment by donob4n** [comment]
The event is received but the callback doesn't send notification.

/qui/models/domains/domains.py (255):

```
        self.signal_callbacks = {
            'Starting': self.update_domain_item,
            'Started': self.update_domain_item,
            'Failed': self.update_domain_item,
            'Halting': self.update_domain_item,
            'Halted': self.remove_menu,
            'Unknown': self.update_domain_item,
        }

    def remove_menu(self, _, vm_path):
        ''' Remove the menu item for the specified domain from the tray'''
        vm_widget = self.menu_items[vm_path]
        self.tray_menu.remove(vm_widget)
        del self.menu_items[vm_path]
        self.tray_menu.queue_draw()
        
```

I would do a pull request but I can't find the repository.

**Comment by marmarek** [comment]
desktop-linux-manager

**Comment by donob4n** [comment]
Done.

Should the subprocess.call() be replaced by direct dbus events?

**Comment by marmarek** [comment]
On Thu, May 10, 2018 at 04:40:32AM -0700, donob4n wrote:
> Done.

Thanks!

> Should the subprocess.call() be replaced by direct dbus events?

Yes.

**Comment by taradiddles** [comment]
Is it expected to have a "domain is halting" notification *before* checking that a VM can be shutdown ?

For instance there's a "Domain sys-net is halting" notification pop up when I try to shutdown sys-net, despite the VM being impossible to shutdown because there are other VMs connected to this VM.

**Comment by andrewdavidwong** [comment]
> Is it expected to have a "domain is halting" notification before checking that a VM can be shutdown ?
> 
> For instance there's a "Domain sys-net is halting" notification pop up when I try to shutdown sys-net, despite the VM being impossible to shutdown because there are other VMs connected to this VM.

That sounds like a bug, but since it's a different bug than the one described by this issue, you should probably file a separate issue for it.

**Comment by andrewdavidwong** [comment]
> "Domain is halting"means that a VM will attempt a shutdown (which may or may not work).

Perhaps it would be clearer to say, "Attempting to shut down qube."
