### ISSUE TITLE
PVGrub standalone Qube doesn't boot

### ISSUE THREAD

**Issue by awokd** [QubesOS/qubes-issues#3563]
#### Qubes OS version:

R4.0

#### Affected TemplateVMs: 

---

### Steps to reproduce the behavior:

Create standalone qube from template, `kerntest` in below steps
~~~
sudo qubes-dom0-update grub2-xen
qvm-prefs kerntest virt_mode pvh
qvm-prefs kerntest kernel pvgrub2
qvm-start kerntest
~~~

### Expected behavior:

qube boots

### Actual behavior:

boot fails immediately with dom0 message
`Missing file: /var/lib/qubes/vm-kernels/pvgrub2/modules.img`

### General notes:

grub2-xen version is 2.02beta2-3.fc25
same behaviour with `virt_mode hvm`

---

#### Related issues:

#2822

**Comment by awokd** [comment]
and `virt_mode pv`

**Comment by awokd** [comment]
Doc link for tracking: https://github.com/QubesOS/qubes-doc/pull/584

**Comment by marmarek** [comment]
Besides modules.img problem, this wouldn't work with virt_mode pvh, because pvgrub2 does not support pvh yet. There are some patches for that in RFC stage, so this may change in the future.

**Comment by awokd** [comment]
It should work with `virt_mode pv` though, right?

**Comment by marmarek** [comment]
Yes (besides that `modules.img` bug). You can try by creating empty `modules.img` file.

**Comment by marmarek** [comment]
Additionally, templates for R4.0 comes with grub preinstalled, which can be used in HVM mode:
```
qvm-prefs vmname virt_mode hvm
qvm-prefs vmname kernel ''
```

**Comment by awokd** [comment]
Nice, that cuts out the pain of having to manually install grub, etc. like on R3.2.
