### ISSUE TITLE
The Qube Settings GUI displays information in a misleading way

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#3565]
#### Qubes OS version:

`R4.0`

---

In https://github.com/QubesOS/qubes-issues/issues/3561#issuecomment-364643800, @awokd wrote:
> the Qube Setting GUI is a bit buggy. If I use it to view anon-whonix's `default_dispvm` on the advanced tab, it claims it's set to the qubes-prefs' `default_dispvm`, even though it's actually using the value in `qvm-prefs anon-whonix default_dispvm`. I think there might be a similar issue out there too about the kernel value on this tab.
Also, hitting the drop-down for dispvm only lists `default` and `(none)`, when I'd expect it to list all templates where `template_for_dispvms` = `true`.

---

#### Related issues:

#3561

**Comment by marmarta** [comment]
You're completely right on the default dispvm thing - hopefully, I've fixed it. Although I'm not sure about the kernel thing - it uses the property_get_default of the current vm for the 'kernel' property, which I think is the desired behavior?

**Comment by awokd** [comment]
I remembered wrong, I was thinking of the virt mode on that tab: https://github.com/QubesOS/qubes-issues/issues/3517
Kernel is working properly.
