### ISSUE TITLE
IKEv2 VPN does not change to remote IP address on fedora based VMs

### ISSUE THREAD

**Issue by Polygonbugs** [QubesOS/qubes-issues#3568]
#### Qubes OS version:

R3.2

#### Affected TemplateVMs: 

fedora-26, fedora-26-minimal (PV domains)

---

### Steps to reproduce the behavior:

**Fedora VPN setup**

1. sudo dnf install -y strongswan

2. cd /etc/strongswan

3. sudo gedit ipsec.conf
-add config for VPN server

4. sudo gedit ipsec.secrets
-add credential

5. sudo rm -rf  ./ipsec.d/cacerts

6. sudo wget https://www.digicert.com/CACerts/DigiCertECCSecureServerCA.crt -O /etc/ssl/certs/DigiCertECCSecureServerCA.crt

7. sudo wget https://www.digicert.com/CACerts/DigiCertHighAssuranceEVRootCA.crt -O /etc/ssl/certs/DigiCertHighAssuranceEVRootCA.crt

8. sudo wget https://www.digicert.com/CACerts/DigiCertGlobalRootCA.crt -O /etc/ssl/certs/DigiCertGlobalRootCA.crt

9. sudo cp /etc/ssl/certs/* ./ipsec.d/cacerts

10. sudo strongswan restart

11. sudo strongswan up vpn

### Expected behavior:

VPN is established successfully and Public IP is changed to remote server.

### Actual behavior:

VPN is established successfully but Public IP is not changed.

### General notes:

Same VPN server is established succesfully and get server IP on HVM linux such as Linux Mint. Does Qubes need additional IP routing to change? I use default route settings of strongswan.conf. Or additional package needed?

**Comment by Polygonbugs** [comment]
Checked that debian template is also not working properly liked as mentioned above.

**Comment by Polygonbugs** [comment]
Same server OpenVPN works in PV mode machine. Could anybody test IKEv2 protocol on 4.0-rc5 which run PVH mode by default? I know that OpenVPN doesn't need kernel for this but IKEv2 dependent on it. See "https://openvpn.net/index.php/open-source/339-why-ssl-vpn.html"

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.

**Comment by onetuser** [comment]
I have the same issue in 4.0

**Comment by DemiMarie** [comment]
> I have the same issue in 4.0. OpenVPN works, IPsec does not (connects but no traffic goes via VPN). Kernel IP routing table does not change after IPsec connect. Using NetworkManager to connect (nmcli con up ...)

R4.0 is end of life, please upgrade to R4.1.
