### ISSUE TITLE
Qubes Settings GUI / setting Initial memory to less than 1/10th Max mem. requires enabling memory balancing 

### ISSUE THREAD

**Issue by taradiddles** [QubesOS/qubes-issues#3569]
[ very low prio ]

#### Qubes OS version:

4.0rc4

---

### Steps to reproduce the behavior:

* Choose a VM that is not included in memory balancing (eg. sys-net) and open its Qubes Settings  gui / advanced tab
* Try to change the Initial Memory to a lower value than 1/10th the value of the greyed out "Max memory" value.

### Expected behavior:

Initial Memory is set to a lower value.

### Actual behavior:

Error message - "Initial memory can't be less than one tenth Max Memory". However "Max Memory" is greyed out so one has to enable memory balancing, decrease the max memory, set a lower Initial memory value and then disable memory balancing.

### General notes:

IMHO, more generally (= also for VMs with memory balancing enabled) setting a lower value than 1/10th the Max memory should automatically decrease the Max memory to 10 times the new Initial memory value - maybe with a notification message.

---

**Comment by donob4n** [comment]
I had a similar problem. Ff you try to set more than more 'Max memory', you will get a warning message and the max value will be updated.

https://github.com/QubesOS/qubes-manager/blob/cb2aa56413a85d456af0b2fab10654ccd0186294/qubesmanager/settings.py#L431

This needs to check if the VM is not included in balancing. I've fixed it in my 3.2 dom0 but I considered it pretty dummy for requesting a pull. Also I thought it won't affect Qubes 4.

**Comment by donob4n** [comment]
It's hard to avoid it being called since it's called by the gui, so maybe a good solution could be:

    def check_mem_changes(self):
        # skip VMs not included in memory balancing
        if not self.include_in_balancing.isChecked()
            self.max_mem_size.setValue(self.init_mem.value())
            return

        if self.max_mem_size.value() < self.init_mem.value():
            QtGui.QMessageBox.warning(
                None,
                self.tr("Warning!"),
                self.tr("Max memory can not be less than initial memory.<br>"
                        "Setting max memory to equal initial memory."))
            self.max_mem_size.setValue(self.init_mem.value())
        # Linux specific limit: init memory must not be below
        # max_mem_size/10.79 in order to allow scaling up to
        # max_mem_size (or else "add_memory() failed: -17" problem)
        if self.init_mem.value() * 10 < self.max_mem_size.value():
            QtGui.QMessageBox.warning(
                None,
                self.tr("Warning!"),
                self.tr("Initial memory can not be less than one tenth "
                        "Max memory.<br>Setting initial memory to the minimum "
                        "allowed value."))
            self.init_mem.setValue(self.max_mem_size.value() / 10)

**Comment by jsmaniac** [comment]
Is there any reason for this 1/10 restriction? It is not enforced when you set memory from the command-line with `qvm-prefs`.

Also, if the max mem is 4096 and the min mem is e.g. 400, the gui will increase the min mem to 409, and then complain at every user action that 409 is less than 1/10 of the max memory (in other words, it acts as if it was rounding down when auto-increasing the min mem, but rounding up when doing the check).

**Comment by marmarta** [comment]
fixed by https://github.com/QubesOS/qubes-manager/commit/b058db4ccfc6332695dc90447a942aedb10e3bb7
