### ISSUE TITLE
Qubes OS R4.0 RC4 Qubes Manager bug not fixed yet

### ISSUE THREAD

**Issue by Simon-Davies** [QubesOS/qubes-issues#3570]
#### Qubes OS version:

Qubes OS R4.0 RC4

#### Affected TemplateVMs: 

N/A

---

### Steps to reproduce the behavior:

Upgrade to the latest version of Qubes Manager in the current-testing repo

Click on Restart VM, VM doesn't power down and a popup asks you to force kill it. Below error is displayed:

Whoops. A critical error has occurred. This is most likely a bug in Qubes Manager.

QubesNoSuchPropertyError: Invalid property 'force_shutdown' of work
at line 195
of file /usr/lib/python3.5/site-packages/qubesmanager/qube_m do response

line: raise exc_class(format_string, *args)
func: _parse_qubesd_response
line no.: 102
file: /usr/lib/python3.5/site-packages/qubesadmin/base.py

### Expected behavior:

Error message isn't thrown

### Actual behavior:

Throws error message

### General notes:

---

**Comment by lunarthegrey** [comment]
Hmm, I didn't have any problems with the most recent package. Although I wasn't prompted to force shutdown.

**Comment by lunarthegrey** [comment]
Actually... Just ran into this bug. Had a VM that prompted to kill, and I got the same result as @Simon-Davies.

**Comment by andrewdavidwong** [comment]
Updated title to be more descriptive.
