### ISSUE TITLE
Copy/paste from dom0 to guest

### ISSUE THREAD

**Issue by mirrorway** [QubesOS/qubes-issues#3571]
#### Qubes OS version:

R4.0 rc4

### Steps to reproduce the behavior:

1. Do the qubes clipboard copy procedure from dom0.

### Expected behavior:

The clipboard copy procedure should work for dom0 -> guest just like it does for guest1 -> guest2.

### Actual behavior:

It doesn't work.

### General notes:

There's also no right-click qubes-icon > "Copy to Dom0 clipboard" workaround anymore.

Extending the clipboard copy sequence to work with dom0 is more elegant than the right-click menu.

**Comment by andrewdavidwong** [comment]
@marmarek: What is the intended way to copy text from dom0 in 4.0? Our documentation states that the "Copy to Dom0 clipboard" option should work in 3.2 and newer:

https://www.qubes-os.org/doc/copy-from-dom0/#copypaste-from-dom0

**Comment by marmarek** [comment]
Indeed the clipboard copy action is gone with stripped down manager. But unifying copy operation [is complex](https://groups.google.com/d/msgid/qubes-devel/7a1af455-7c0c-dbd0-55d7-fdbf207a6584%40c3i.bg).
Should we have yet another icon there? Action in applications menu? Put somewhere into one of current applets (but note that there is no longer separate right-click menu - both right and left click menus are the same).

**Comment by andrewdavidwong** [comment]
Well, @mirrorway wants to be able to use the standard inter-VM clipboard keyboard shortcut. IIRC, that option was previously considered and rejected for security reasons. However, I can imagine having an option `qubes.guid` to enable it (but leaving it disabled by default).

As for the other options, it would probably be most intuitive to have it as an option in whatever's considered the most "global" applet.

**Comment by awokd** [comment]
The work-around procedure described in that doc does work on R4.0. Just make sure to use `-n` like `echo -n dom0 > qubes-clipboard.bin.source`.

**Comment by DemiMarie** [comment]
In what way is copy *from* Dom0 a security risk?  I cannot see how that creates attack surface.

**Comment by andrewdavidwong** [comment]
> In what way is copy from Dom0 a security risk? I cannot see how that creates attack surface.

The user could have secrets in dom0, e.g., keyfiles or passphrases for automating backups.

**Comment by andrewdavidwong** [comment]
How about, if the user tries to copy to the inter-VM clipboard from dom0 using the standard shortcute, there's a pop-up in dom0 to confirm the action (perhaps with a brief warning)? This would unify the UX with other inter-VM actions (copying files, Split GPG, etc.), and it wouldn't require the user to know anything new.

**Comment by andrewdavidwong** [comment]
Understandably, this is a major UX pain point for many users:

https://groups.google.com/d/topic/qubes-users/XbJJK2BapUQ/discussion

**Comment by marmarek** [comment]
Having the same keyboard shortcut is very hard to do without introducing race conditions (possibly with security implications), see https://github.com/QubesOS/qubes-issues/issues/3571#issuecomment-364812710.

What could be possible, is a different key combination, or some clickable action (as it was in R3.2).

**Comment by t4777sd** [comment]
Not being able to copy from dom0 is a frustrating user experience. I definitely like the idea of different keyboard shortcut and would like to see it work both to and from dom perhaps with a dialog box with a textarea box preview when going from VM -> dom0.

I view the risk of VM -> dom0 as slightly higher as a VM may place data on the clipboard to be copied to dom and the user may be copying it to a terminal with a quick paste and enter and not pay attention.

So, when dom0 attempts to put in its clipboard any data from VM a dialog box could popup. The dialog box could have a textarea box that displays the contents that is currently registered that will be applied to the dom0 clipboard if the box is clicked. This dialog with textarea provides an additional level of verification for the user.

Going from dom0 -> VM I think is far less risky. The biggest use-case is probably searching and debugging things like log file messages and post bug reports. I am not even sure it needs a dialog box to warn.

**Comment by andrewdavidwong** [comment]
There is now a "Qubes Clipboard" widget that allows for easily copying from dom0.
