### ISSUE TITLE
qubes-manager (4.0 RC4) VM state not refreshed on shutdown

### ISSUE THREAD

**Issue by lunarthegrey** [QubesOS/qubes-issues#3572]
#### Qubes OS version:

Qubes OS 4.0 RC4

#### Affected TemplateVMs: 

N/A

---

### Steps to reproduce the behavior:

Using the latest qubes-manager 4.0.14-1.fc25. When shutting down a VM from Qube Manager, the VM's "State" turns from green to yellow, and appears to have been fully shutdown if you run "qvm-ls" in dom0. Yet the yellow dot remains, making users think the VM is still shutting down. When pressing the "Refresh qube list" button, it actually appears that the VM had already shut down, but the state was unchanged until the button is pressed. So for some reason the state of a VM doesn't get refreshed when it has shut down.

### Expected behavior:

The VM's state turns from green -> yellow -> blank

### Actual behavior:

The VM's state turns from green -> yellow, but not blank until the "Refresh qube list" button is pressed.

### General notes:

Nothing further to note.

---

#### Related issues:

None that I'm aware of.

**Comment by andrewdavidwong** [comment]
@marmarta: I noticed that @marmarek has been assigning most `qubes-manager` bugs to you lately. In order to help out, I'm also going to start assigning them to you. However, if you ever think that I've assigned an issue to you that shouldn't be assigned to you, please feel free to unassign yourself or assign it to someone else. Likewise, if you find that this is not helpful in general, please let me know.

**Comment by lunarthegrey** [comment]
@marmarta I see. Would it be possible to just have the status refresh at a certain interval? I think that may be a better solution than removing the whole feature.

**Comment by marmarta** [comment]
That's not a great idea at the moment. I mean, those automatic refreshes were pretty much what caused the old qubes manager to be so buggy - I'm pretty afraid to re-introduce this feature. At the moment, the designated use cases for the Qube Manager are not really the everyday operations (the domains and devices widgets are for that) - it's more like "when you actually have to create/copy/update/in other ways manage your qubes". So, hopefully one not-so-distant day we'll have better, event-aware mechanism for updating the manager state, but today, sadly no.

**Comment by lunarthegrey** [comment]
@marmarta Sounds good. Thank you for the explanation. I completely understand now.

**Comment by marmarta** [comment]
It should have been fixed by https://github.com/QubesOS/qubes-manager/commit/875311932783695336e0a81dbcee620d3a53bab0#diff-e66f321e61dbeb6d68507cd260b4c4aa and later commits.
