### ISSUE TITLE
Changing a named dispVM's template's template causes qubesd to crash

### ISSUE THREAD

**Issue by 3hhh** [QubesOS/qubes-issues#3576]
#### Qubes OS version:
4.0rc4

#### Affected TemplateVMs: 
all?
tested during debian-8 --> debian-9 migration

### Steps to reproduce the behavior:

1. Use e.g. a named **_disposable_** sys-net VM with a template VM such as sys-net-dvm. Let's say sys-net-dvm uses a debian-8 template.

1. Whilst sys-net is running, switch the template of sys-net-dvm to e.g. debian-9 (yes, that works).

1. Reboot.

### Expected behavior:
qubesd works or I cannot change the template's template whilst an instance is running.

### Actual behavior:
qubesd crashes.

The root cause is an incorrect reference of the sys-net dvm instance to the old template in the qubes.xml file. It can be fixed by manually editing the file and rebooting.

**Comment by rustybird** [comment]
Looks like @3hhh described only the mildest case of this bug - the qubesd crash in that sequence is disruptive, but at least it fails closed. IMO the worst (and more frequent) case is that **auto_cleanup=False DispVMs can be started with a snapshot of the wrong root volume**, which is a potential privacy issue. /cc @andrewdavidwong

Starting a DispVM with wrong root volume:

    $ qvm-clone -q fedora-26 fedora-test  # this is not specific to Fedora ...
    $ qvm-clone -q debian-9  debian-test  # ... or Debian, they're just easy to tell apart
    $ qvm-create -t fedora-test --prop template_for_dispvms=True -l red bug-dvm
    $ qvm-create -t bug-dvm     -C DispVM                        -l red bug
    $ qvm-run -p bug 'head -n 1 /etc/os-release'
    NAME=Fedora
    $ until qvm-shutdown --wait bug; do sleep 1; done
    $ qvm-prefs -s bug-dvm template debian-test  # "journalctl -fu qubesd" prints "socket.send() raised exception." 11 times
    $ qvm-run -p bug 'head -n 1 /etc/os-release'  # should be Debian now:
    NAME=Fedora

Then crashing qubesd:

    $ until qvm-shutdown --wait bug; do sleep 1; done
    $ qvm-remove -f fedora-test
    $ qvm-start bug  # error message from volume's verify() - e.g. file-reflink:
    Missing image file '/var/lib/qubes/vm-templates/fedora-test/root.img' for volume appvms/bug/root
    $ systemctl restart qubesd
    Job for qubesd.service failed because the control process exited with error code.

(using newest current-testing dom0 packages)

**Comment by marmarek** [comment]
For now, as a quick fix, I'm going to forbid changing template of AppVM, when it have some DispVMs (running or not). Later a proper solution may be implemented.

**Comment by marmarek** [comment]
Reopening to remind about proper solution.

**Comment by shunju** [comment]
Maybe, priority should be lowered to reflect the reduced urgency, e.g. as a user I don’t see why this should delay the release of 4.0.

**Comment by DemiMarie** [comment]
@marmarek is this simply a matter of calling `on_property_set_template` for each DispVM based on this AppVM?

**Comment by marmarek** [comment]
Probably yes, needs testing.

**Comment by DemiMarie** [comment]
Can I safely test it locally by editing the Python files and deleting the
.pyc files?

**Comment by frozentime345** [comment]
Is there any way to safely change the dispvm's template's template manually right now? Other than deleting the dispvms and then recreating after?

**Comment by 3hhh** [comment]
> Is there any way to safely change the dispvm's template's template manually right now? Other than deleting the dispvms and then recreating after?

Manually editing `qubes.xml` and restarting `qubesd` afterwards appears to work. However it is certainly not "safe" as mistakes may cause big issues.

In particular every VM entry requires a change at 3-4 places inside `qubes.xml`.

I guess that's probably why this bug happened in the first time:
The same information occurring repeatedly in `qubes.xml` and likely in the internal qubesd representation was modified in only one place rather than all of them. Ideally one piece of information is stored in exactly one place. This however would require some re-design.

**Comment by tlaurion** [comment]
> Probably yes, needs testing.

@marmarek ?

**Comment by tlaurion** [comment]
@DemiMarie ?

**Comment by DemiMarie** [comment]
> @DemiMarie ?

This has been fixed quite a while ago.

**Comment by tlaurion** [comment]
> > @DemiMarie ?
> 
> This has been fixed quite a while ago.

For 4.1 only.

**Comment by DemiMarie** [comment]
> > > @DemiMarie ?
> > 
> > 
> > This has been fixed quite a while ago.
> 
> @DemiMarie [For 4.1 only.](https://github.com/QubesOS/qubes-issues/issues/6270#issuecomment-742816658)

In 4.0 this now gives an error message.
