### ISSUE TITLE
What The hell is going on Guys????

### ISSUE THREAD

**Issue by qalosc** [QubesOS/qubes-issues#3577]
#### Qubes OS version:
<4

#### Affected TemplateVMs: 

I am just really confused using Qubes 4. I downloaded it yesterday installed and the whole thing is messy when managing qubes. 
sys-net and other service vms should have their own category but they are listed as appvms!!.
Fedora-26-dvm and whonix-ws-dvm (there should also be a debian-9-dvm) should all be classed as disposable templates and give an option to create them. I hope this is just because its RC 4 and its still being worked on, because right now if feels like a mess. 

### General notes:

---

**Comment by marmarek** [comment]
See [here](https://www.qubes-os.org/news/2017/10/03/core3/) for explanation of some architectural changes in Qubes 4.0. Especially two fragments:

> We also no longer distinguish between AppVMs, NetVMs and Proxy VMs. Instead, each VM has a property provides_network, which is false by default, except for the VMs which we want to expose networking to other VMs (e.g. because they might have some networking device assigned, such as cellular modem or WiFi device, or because they act as VPNs or proxies of some sort).

> Another major change to DispVMs semantics in Qubes 4 (largely allowed by this relaxation of DispVM definition) is that any of the AppVMs can be now used as a template for the DispVM.
>
> This provides lots of flexibility, e.g. it’s easy to create a customized DispVM for signing PDF documents, or various disposable service VMs, such as Net- and VPN- VMs. One just creates a normal AppVM, sets everything up there, e.g. loads keys, configures VPNs, connects to known WiFi networks, and then shuts down the AppVM and in place of it starts a DispVM based on that AppVM.

Read the full article for more details. Those changes provide much more flexibility.

**Comment by qalosc** [comment]
oh.

**Comment by qalosc** [comment]
Thanks for the reply.
