### ISSUE TITLE
How to use multiple keyboard layouts

### ISSUE THREAD

**Issue by taradiddles** [QubesOS/qubes-issues#3578]
#### EDIT: a draft doc is available at https://github.com/Qubes-Community/Contents/blob/master/docs/localization/keyboard-multiple-layouts.md ; with enough interest and testing, it may get into the official qubes doc ###

---

#### Qubes OS version:

R4.0 (should be applicable to R3 too).

#### Background:
The official docs only cover how to change the layout *globally* - ie. both for dom0 and VMs, with a *single* layout  [1]; issue #1396 mentioned in the FAQ entry is only about keyboard layout propagation from dom0 to VMs.

Using *multiple* keyboard layouts and being able to *quickly* switch between them (*) isn't covered. One would imagine that this use-case is ubiquitous amongst qubes users communicating both in a language with a non-latin alphabet (eg. cyrillic) and in English.

(*) changing layouts has to be *fast*: for instance when writing mixed cyrillic/latin emails I always have to switch back and forth between layouts at least a dozen times a minute.

[1] https://www.qubes-os.org/faq/#my-keyboard-layout-settings-are-not-behaving-correctly-what-should-i-do

#### Proposed improvements to documentation:

1. Maybe we should  have a page dedicated to keyboard layouts (or maybe more generally, to internationalization) and have the keyboard FAQ point to it.

2. The following solutions exist for the multiple layouts use-case:

    1. Change the layout in dom0 with localectl ; it's a no-go as it requires a reboot
    2. Change the layout in dom0 like I suggested in #1396 with `setxkbmap -layout "us,bg(phonetic)" -option "grp:shifts_toggle"`. This workaround proved to work more or less OK over the past 2 years but wasn't optimal:
        * there's no way to know which layout is used when typing the screensaver's password
        * sometimes the keyboard layout would not be propagated to one of the VMs, requiring a reboot of the VM. 
    3. Configuring a keyboard shortcut in dom0 that would issue `qvm-run vname 'setxkbmap...'` to the VM whose window is under the mouse pointer (using `xprop -id $(xdotool getactivewindow`) ). I tried it, it works, but is a bit convoluted and `qvm-run` is sometimes slow when the system is under heavy I/O usage, so the layout switch doesn't happen immediately which is annoying.
    4. Best option IMO - issuing the `setxkbmap ...` command in *each* VM. This works surprisingly well. The downsides are that:
        * it requires modifying the user profile in each VM to issue the `setxkbmap` command, or tweaking the VM's template(s). Alternatively, maybe there's a way to issue the command *from* dom0 after the VM is started (I didn't investigate that yet).
        * only one layout in dom0 (since using `setxkbmap...` in dom0 would probably interfere with the VMs).

ideas ?

**Comment by shunju** [comment]
Why not use the Xfce Keyboard Layout switcher?

To add it, right-click on the top panel > Panel > Add New Items. In the opening window, pick “Keyboard Layouts”.

Customize the switcher by right-clicking > Keyboard settings. In the opening window, pick Layout tab. There you can add new keyboard layouts, define the order in which they can be scrolled though and even define a keyboard shortcut for switching layouts.

**Comment by taradiddles** [comment]
> Why not use the Xfce Keyboard Layout switcher?

As you saw, it doesn't work :)

But if #1396 is solved the graphical switcher would likely fall under case 2. ii.

**Comment by hugoncosta** [comment]
I believe I've found a way around this. Follow me:

1) Go to Settings - Keyboard. Make sure you have at least 2 types of keyboard. 

2) Set the "Change layout option" to something, I chose alt + shift because windows. 

3) Click on "Use system defaults"

4) Restart VM

Seems odd, but it has worked for me.

**Comment by roybernat** [comment]
Hi 
for some reason it work for limited time and stop working 

any idea

**Comment by hugoncosta** [comment]
> 
> 
> Hi
> for some reason it work for limited time and stop working
> 
> any idea

Explain a little more. I'm using the latest Qubes and I can easily switch on all VMs between layouts.

**Comment by taradiddles** [comment]
Quick update: R4.1 seems to have a mechanism for propagating keyboard layouts ; I haven't tested it as I'm still using using `setxkbmap` in each vm, which I'm used to and works perfectly for me, but this issue is probably not relevant anymore.
@andrewdavidwong , OK to close this issue ?

**Comment by andrewdavidwong** [comment]
Closing as resolved. If anyone believes this issue is not yet resolved, or if anyone is still affected by this issue, please leave a comment, and we'll be happy to reopen it. Thank you.
