### ISSUE TITLE
Unicode not supported in wireless network names (ESSIDs)

### ISSUE THREAD

**Issue by vladionescu** [QubesOS/qubes-issues#3580]
#### Qubes OS version:

4.0 rc4 (R4.0)

---

### Steps to reproduce the behavior:

1. Create a wireless network with unicode characters in the name, such as a hotspot on a mobile device with the SSID being an emoji.
2. Click the network icon in the Qubes taskbar.
3. Under "Wi-Fi Networks" notice the unicode characters are not rendered, instead they appear as char codes in a box.
4. When connected to the network, the desktop notification also does not render unicode properly.

### Expected behavior:

Unicode characters in network names are rendered appropriately.

### Actual behavior:

Unicode characters are not rendered in network names, they are shown as boxes with char codes inside.

### General notes:

While the repro steps mention emojis in the network name, this issue is more serious as it makes connecting to wireless networks in non-western countries potentially dangerous if the user cannot read the network names when they are written in other alphabets. The user may inadvertently connect to an undesirable network as a result of the confusion.

UTF-8

**Comment by marmarek** [comment]
There should be nothing Qubes-specific in this, it's just NetworkManager (+nm-applet). Check if appropriate fonts are installed. You may also want use `gnome-tweak-tool` (not installed by default) to change it.

**Comment by andrewdavidwong** [comment]
Closing as "not our bug." If you believe this is a mistake, please leave a comment, and we'll be happy to take another look. Thank you.
