### ISSUE TITLE
Ctrl Shift C / Ctrl Shift V for inter-VM copy/paste breaks copy/paste from terminal

### ISSUE THREAD

**Issue by shunju** [QubesOS/qubes-issues#3583]
In short, I think Qubes keyboard shortcuts should try to as much as possible to get out of the way of users and be customizable in case they happen to be still in the way of a minority of users.

Coming from Debian I am used to using Ctrl+Shift+C to copy from and Ctrl+Shift+V to paste into a terminal.

However, in Qubes, these shortcuts are intercepted by the dom0 GUI and never reach the terminal window. Therefore, I have to click on Edit and then Copy/Paste in the terminal. This is exacerbated by the fact that the standard Gnome terminal does not allow navigating the menu with the keyboard (e.g. Alt+E P). (I will install xfce4-terminal soon and expect that this will help me work around the issue somewhat).

I would expect Qubes to use another (not widely used) keyboard shortcut to achieve copy/paste interaction between VMs, e.g. Super+C and Super+V (where Super is the Windows key, Linux key, Qubes key or whatever).

Somewhat more generally, it would be nice if users were able to customize Qubes shortcuts. I find hard-coding shortcuts especially concerning because I see possible future shortcuts discussed (e.g. #2706) that potentially further restrict usability for some users.

**Comment by marmarek** [comment]
Try Ctrl+Ins and Shift+Ins. Works for me.

As for changing those shortcuts, see /etc/qubes/guid.conf.

**Comment by shunju** [comment]
Okay, that does work. And I just found https://groups.google.com/forum/#!topic/qubes-users/NvF0f7PCu9A with a reference to the same configuration file.

Now having the choice of which one to change (change Qubes secure copy/paste or just use the other shortcut already available for terminal), I must admit that the current default does have advantages.
