### ISSUE TITLE
Uninstalling Thunderbird removes needed Packages

### ISSUE THREAD

**Issue by Stifflersmum** [QubesOS/qubes-issues#3593]
#### Qubes OS version:

4.0rc-4

#### Affected TemplateVMs: 

fedora-26

---

### Steps to reproduce the behavior:

sudo dnf remove thunderbird

### Expected behavior:

The command uninstalls thunderbird

### Actual behavior:

While thunderbird is indeed uninstalled, it also removes the following packages needed:

Removing dependent packages:
 nftables                            x86_64 1:0.7-3.fc26       @fedora
 459 k
 python-backports-ssl_match_hostname noarch 3.5.0.1-4.fc26     @fedora
  18 k
 python-systemd-doc                  x86_64 234-1.fc26         @fedora
 750 k
 python2-crypto                      x86_64 2.6.1-14.fc26      @fedora
 2.2 M
 python2-cryptography                x86_64 2.0.2-2.fc26       @updates
 2.6 M
 python2-jinja2                      noarch 2.9.6-1.fc26       @fedora
 3.6 M
 python2-numpy                       x86_64 1:1.12.1-1.fc26    @fedora
  16 M
 python2-pillow                      x86_64 4.1.1-1.fc26       @fedora
 1.9 M
 python2-pyOpenSSL                   noarch 16.2.0-6.fc26      @updates
 523 k
 python2-qubesimgconverter           x86_64 4.0.15-1.fc26
@qubes-builder-vm-r4.0-current-testing

  40 k
 python2-requests                    noarch 2.13.0-1.fc26      @fedora
 409 k
 python2-tornado                     x86_64 4.4.2-3.fc26       @fedora
 3.9 M
 python2-urllib3                     noarch 1.20-2.fc26        @updates
 536 k
 python2-zmq                         x86_64 16.0.2-3.fc26      @fedora
 1.6 M
 qubes-core-agent-dom0-updates       x86_64 4.0.20-1.fc26
@qubes-builder-vm-r4.0-current-testing

 4.9 k
 qubes-core-agent-network-manager    x86_64 4.0.20-1.fc26
@qubes-builder-vm-r4.0-current-testing

 2.4 k
 qubes-core-agent-networking         x86_64 4.0.20-1.fc26
@qubes-builder-vm-r4.0-current-testing

  20 k
 qubes-mgmt-salt-vm-connector        noarch 4.0.6-1.fc26
@qubes-builder-vm-r4.0-current-testing

 5.3 k
 qubes-pdf-converter                 x86_64 2.1.3-1.fc26
@qubes-builder-vm-r4.0-current-testing

  15 k
 qubes-vm-recommended                noarch 4.0.1-1.fc26
@qubes-builder-vm-r4.0-current-testing

   0
 salt                                noarch 2017.7.3-1.fc26    @updates
  36 M
 salt-ssh                            noarch 2017.7.3-1.fc26    @updates
 3.8 k
 thunderbird-qubes                   x86_64 1.2.9-1.fc26
@qubes-builder-vm-r4.0-current-testing

  11 k
 zeromq                              x86_64 4.1.6-3.fc26       @fedora
 671 k
Removing unused dependencies:
 PyYAML                              x86_64 3.12-3.fc26        @fedora
 646 k
 ethtool                             x86_64 2:4.13-1.fc26      @updates
 386 k
 fakeroot                            x86_64 1.22-1.fc26        @updates
 188 k
 fakeroot-libs                       x86_64 1.22-1.fc26        @updates
 107 k
 iptables                            x86_64 1.6.1-2.fc26       @fedora
 1.5 M
 js-jquery                           noarch 3.2.1-1.fc26       @fedora
 508 k
 libnetfilter_conntrack              x86_64 1.0.6-2.fc26       @fedora
 143 k
 libnfnetlink                        x86_64 1.0.1-9.fc26       @fedora
  46 k
 libnftnl                            x86_64 1.0.7-2.fc26       @fedora
 220 k
 libtomcrypt                         x86_64 1.17-31.20160123git912eff4.fc26
                                                               @updates
 824 k
 libtommath                          x86_64 1.0-8.fc26         @updates
 106 k
 libvpx                              x86_64 1.6.1-2.fc26       @fedora
 2.0 M
 libyaml                             x86_64 0.1.7-2.fc26       @fedora
 121 k
 mozilla-filesystem                  x86_64 1.9-15.fc26        @fedora
   0
 openpgm                             x86_64 5.2.122-8.fc26     @fedora
 317 k
 pciutils                            x86_64 3.5.5-1.fc26       @updates
 205 k
 pciutils-libs                       x86_64 3.5.5-1.fc26       @updates
  71 k
 poppler-utils                       x86_64 0.52.0-11.fc26     @updates
 507 k
 pulseaudio-qubes                    x86_64 4.0.8-1.fc26
@qubes-builder-vm-r4.0-current-testing

  33 k
 pycairo                             x86_64 1.10.0-6.fc26      @fedora
 1.0 M
 python-backports                    x86_64 1.0-9.fc26         @fedora
 638
 python-chardet                      noarch 2.3.0-3.fc26       @fedora
 1.1 M
 python-enum34                       noarch 1.1.6-1.fc26       @fedora
 232 k
 python-ipaddress                    noarch 1.0.16-4.fc26      @fedora
 227 k
 python-xpyb                         x86_64 1.3.1-7.fc26       @fedora
 1.2 M
 python2-asn1crypto                  noarch 0.23.0-1.fc26      @updates
 924 k
 python2-babel                       noarch 2.3.4-5.fc26       @fedora
  20 M
 python2-backports_abc               noarch 0.5-3.fc26         @fedora
  30 k
 python2-futures                     noarch 3.1.1-1.fc26       @fedora
  91 k
 python2-idna                        noarch 2.5-1.fc26         @fedora
 563 k
 python2-markupsafe                  x86_64 0.23-13.fc26       @fedora
  83 k
 python2-msgpack                     x86_64 0.4.8-3.fc26       @fedora
 272 k
 python2-nose                        noarch 1.3.7-13.fc26      @fedora
 1.1 M
 python2-olefile                     noarch 0.44-2.fc26        @fedora
 3.5 M
 python2-psutil                      x86_64 5.4.3-2.fc26       @updates
 2.2 M
 python2-pysocks                     noarch 1.6.7-1.fc26       @updates
  79 k
 python2-singledispatch              noarch 3.4.0.3-7.fc26     @fedora
  46 k
 python2-systemd                     x86_64 234-1.fc26         @fedora
 262 k
 pytz                                noarch 2016.10-4.fc26     @fedora
 185 k
 qubes-core-agent-nautilus           x86_64 4.0.20-1.fc26
@qubes-builder-vm-r4.0-current-testing

  11 k
 qubes-core-agent-passwordless-root  x86_64 4.0.20-1.fc26
@qubes-builder-vm-r4.0-current-testing

 2.5 k
 qubes-gpg-split                     x86_64 2.0.27-1.fc26
@qubes-builder-vm-r4.0-current-testing

  58 k
 qubes-img-converter                 x86_64 1.2.4-1.fc26
@qubes-builder-vm-r4.0-current-testing

 6.6 k
 qubes-input-proxy-sender            x86_64 1.0.10-1.fc26
@qubes-builder-vm-r4.0-current-testing

  18 k
 qubes-usb-proxy                     noarch 1.0.15-1.fc26
@qubes-builder-vm-r4.0-current-testing

### General notes:

---

#### Related issues:

missing functions in templates like pdf-converter

**Comment by taradiddles** [comment]
You probably have the 'qubes-vm-recommended' "meta" rpm installed.
This rpm doesn't provide any file, its role is to pull dependencies that Qubes developpers think are needed in order to get a functional VM. You can [see in the spec file](https://github.com/QubesOS/qubes-meta-packages/blob/master/rpm_spec/qubes-vm-meta-packages.spec] that one of those dependencies is 'thunderbird-qubes', which depends on Thunderbird. So trying to remove Thunderbird will remove 'thunderbird-qubes' which in turn will remove 'qubes-vm-recommended' and all its dependencies.

One solution to remove thunderbird is to remove the 'qubes-vm-recommended'; as you see this will remove a bunch of rpms, but you can reinstall them after they're removed.

**Comment by andrewdavidwong** [comment]
I'm provisionally labeling this a bug, but it's unclear whether this should actually be considered one, both for the reasons @taradiddles points out and because we have `fedora-minimal` specifically for cases in which users want a Fedora template without extra packages like Thunderbird.

CC: @marmarek

**Comment by taradiddles** [comment]
A workaround would be to build the default fedora template without the `qubes-vm-recommended` package and have the dependencies installed with a script. That way users could remove whatever rpm they want without going through re-installing all the deleted packages afterwards.
Kind of defeats the idea of the meta package though.

**Comment by 0spinboson** [comment]
So the only way to get rid of thunderbird in an existing template is to remove qubes-vm-recommended and all of its "dependent packages", and then reinstalling all those "dependent" packages manually?

**Comment by unman** [comment]
@andrewdavidwong I dont see this as a bug - it is, as you say, a consequence of how things are packaged for the default template using ` qubes-vm-recommended`. I think the assumption is that users who want to reduce the standard template will be savvy enough to be able to cope with package dependencies. Perhaps there should be a more prominent hint that users who want to customise the templates would do better to start with a minimal template?

@0spinboson There is no need to _reinstall_ those packages which one wishes to keep from "recommended", since one can mark to keep them, and thus they will not be uninstalled. Using a decent package manager helps here.


.

**Comment by andrewdavidwong** [comment]
> I dont see this as a bug - it is, as you say, a consequence of how things are packaged for the default template using ` qubes-vm-recommended`. I think the assumption is that users who want to reduce the standard template will be savvy enough to be able to cope with package dependencies. Perhaps there should be a more prominent hint that users who want to customise the templates would do better to start with a minimal template?

Changing this to a documentation task to add such a hint.

**Comment by taradiddles** [comment]
@0spinboson : no need to remove/reinstall ; the following works for me: 

`sudo rpm -e qubes-vm-recommended thunderbird thunderbird-qubes`

or

`sudo dnf --noautoremove remove qubes-vm-recommended thunderbird thunderbird-qubes`

(dnf's  `--noautoremove` option is important here)

**Comment by joshfleming** [comment]
I don't want to get into the semantics of whether or not this is a bug, however I just uninstalled thunderbird on 3 of my debian based VMs and autoremoved, upon rebooting the template vms I realized I've lost sudo access. 

### 2 Questions.
 1. **Is there anyway to go back once I've removed thunderbird and all of the packages** that go along with that, rebooted and no longer have sudo access? Or do I need to start over from a fresh template VM now? At this point I see no way to reinstall thunderbird or the qubes-vm-recommended package.
 1. I think the problem with calling this a simple documentation task is there's no warning about this as it's happening. I doubt there's a way to have apt or rpm package managers alert you that you're about to remove important qubes packages. And even if it's documented in the documentation, a user probably won't be reading that part of the docs until they've already done this. At that point it seems to be too late and if there's been a lot of customization done to that templateVM it's a big time waster.

**Comment by 0spinboson** [comment]
> 
> 
> I don't want to get into the semantics of whether or not this is a bug, however I just uninstalled thunderbird on 3 of my debian based VMs and autoremoved, upon rebooting the template vms I realized I've lost sudo access.
> ### 3 Questions.
> 
>     1. **Is there anyway to go back once I've removed thunderbird and all of the packages** that go along with that, rebooted and no longer have sudo access? Or do I need to start over from a fresh template VM now? At this point I see no way to reinstall thunderbird or the qubes-vm-recommended package.
> 
>     2. I think the problem with calling this a simple documentation task is there's no warning about this as it's happening. I doubt there's a way to have apt or rpm package managers alert you that you're about to remove important qubes packages. And even if it's documented in the documentation, a user probably won't be reading that part of the docs until they've already done this. At that point it seems to be too late and if there's been a lot of customization done to that templateVM it's a big time waster.
> 
>     3. Also I see there's a fedora-minimal template, I don't see a debian-minimal. Is that in the works?

To gain access to the template, try sudo xl console vmname in dom0, then use root as the login name.

There is a warning, but you have to read the apt/dnf reports, and esp. in debian, it's fairly easy to miss stuff.

**Comment by joshfleming** [comment]
> > I don't want to get into the semantics of whether or not this is a bug, however I just uninstalled thunderbird on 3 of my debian based VMs and autoremoved, upon rebooting the template vms I realized I've lost sudo access.
> > ### 3 Questions.
> > ```
> > 1. **Is there anyway to go back once I've removed thunderbird and all of the packages** that go along with that, rebooted and no longer have sudo access? Or do I need to start over from a fresh template VM now? At this point I see no way to reinstall thunderbird or the qubes-vm-recommended package.
> > 
> > 2. I think the problem with calling this a simple documentation task is there's no warning about this as it's happening. I doubt there's a way to have apt or rpm package managers alert you that you're about to remove important qubes packages. And even if it's documented in the documentation, a user probably won't be reading that part of the docs until they've already done this. At that point it seems to be too late and if there's been a lot of customization done to that templateVM it's a big time waster.
> > 
> > 3. Also I see there's a fedora-minimal template, I don't see a debian-minimal. Is that in the works?
> > ```
> 
> To gain access to the template, try sudo xl console vmname in dom0, then use root as the login name.
> 
> There is a warning, but you have to read the apt/dnf reports, and esp. in debian, it's fairly easy to miss stuff.

You're right It does mention it's going to remove a bunch of qubes-* packages. I just wasn't paying attention as that wasn't something I thought of as a possibility.

I tried what you mentioned, but I'm being prompted for a username and password. Is there a default root password set that would be useable when passwordless root is lost? I tried leaving password blank and "changeme"

**Comment by 0spinboson** [comment]
username root, no pass, should work. other option you might try is qvm-run -u root vmname xterm.

**Comment by joshfleming** [comment]
Thanks @0spinboson ! That second option worked. 

When documenting this I'd suggest some hints on recovery for this in case I'm not the only dummy that got this far without realizing they were borking their template:

## Recovering A TemplateVM which you've already removed thunderbird and qubes-* packages
If you've already restarted your VM you've lost passwordless sudo access. You'll can login as root through dom0: 
```qvm-run -u root vmname xterm```
Once you're logged in as root or if you haven't rebooted after the initial removal of these packages, reinstall these packages (and their dependancies): 
```apt install qubes-core-agent-dom0-updates qubes-core-agent-passwordless-root qubes-gpg-split qubes-img-converter qubes-input-proxy-sender qubes-mgmt-salt-vm-connector qubes-pdf-converter salt-common salt-ssh```

Obviously these are what I did on debian.

**Comment by andrewdavidwong** [comment]
The documentation is a community effort. Please help us improve it by submitting a pull request:

https://www.qubes-os.org/doc/doc-guidelines/

**Comment by joshfleming** [comment]
Ok Happy to contribute that. I did a quick search in the docs for this issue and didn't see anything so I'll create a new page covering this, unless someone has started something or has opinions about where this info should exist or link from.

**Comment by taradiddles** [comment]
> I think the problem with calling this a simple documentation task is there's no warning about this as it's happening. I doubt there's a way to have apt or rpm package managers alert you that you're about to remove important qubes packages. And even if it's documented in the documentation, a user probably won't be reading that part of the docs until they've already done this. At that point it seems to be too late and if there's been a lot of customization done to that templateVM it's a big time waster.

IMO removing packages from templates is "advanced usage" so it's the (power) user's responsibility not to overlook stuff like dependencies removal. But mistakes happen, so when messing around with templates the first advice should be to backup the vm (it takes virtually no time on R4 with `qvm-clone`).
If the doc is updated, please use generic instruction: the problem here is not about thunderbird, it's about how to reinstall qubes-* packages - and even more generally, how to run commands in a VM that doesn't have qubes agent running.

BTW Fedora's dnf provides a "protected" feature exactly for the purpose of avoiding removing base packages: putting the qubes-* packages names in `/etc/dnf/protected/qubes.conf` will prevent removal, like so : 

~~~
sudo dnf remove  qubes-core-agent
Error: 
 Problem: The operation would result in removing the following protected packages: qubes-core-agent
~~~

No idea if debian's apt has a similar feature.

**Comment by marmarek** [comment]
Since qubes-vm-recommended no longer depends on thunderbird-qubes, this is solved already. In the future, this will be handled by using conditional dependencies (like here: https://github.com/QubesOS/qubes-meta-packages/commit/da13497ad9ebbca0701085ffe3665ed8f610aa3a)
