### ISSUE TITLE
Qube 3.2 iso build error 'linux-template-builder' Stretch+Standard

### ISSUE THREAD

**Issue by TimFW** [QubesOS/qubes-issues#3596]
#### Qubes OS version: 3.2

Version 3.2

#### Affected TemplateVMs: 

Stretch+Sandard possibly other debain templates

---

### Steps to reproduce the behavior:

Standard 3.2 ISO build qubes-builder 
Both #make qubes and #make each individual components
At $make linux-template-builder

### Expected behavior:

Should complete back to command line no fatal errors in *.logs

### Actual behavior:

component: linux-template-builder fails at stretch+standard template build stopped with failure:

$Makefile:56: recipe for target 'rootimg-build' failed
$make[1]: *** [rootimg-build] Error 100

Currently 3.2 standard iso does not build.

*Same error has been reproduced by others awokd 

### General notes:

These errors started in the last 4-5 days as I was successfully building 3.2 iso prior.

The following errors found in  template-stretch.log (attached at end):

**Adding system-user for exim (v4)
ERROR: ld.so: object 'libeatmydata.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.

Setting up dnsmasq-base (2.76-5+deb9u1) ...
ERROR: ld.so: object 'libeatmydata.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.

Setting up avahi-daemon (0.6.32-2) ...
ERROR: ld.so: object 'libeatmydata.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.

ERROR: ld.so: object 'libeatmydata.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.

Adding saned group and user...
ERROR: ld.so: object 'libeatmydata.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.

Configuration file '/etc/fstab'
 ==> File on system created by you or by a script.
 ==> File also in package provided by package maintainer.
 ==> Using new file as you requested.
Installing new version of config file /etc/fstab ...
chown: cannot access '/home_volatile/user': No such file or directory
dpkg: error processing package qubes-core-agent (--configure):
 subprocess installed post-installation script returned error exit status 1
dpkg: dependency problems prevent configuration of qubes-input-proxy-sender:
 qubes-input-proxy-sender depends on qubes-core-agent (>= 3.0.25); however:
  Package qubes-core-agent is not configured yet.

dpkg: error processing package qubes-input-proxy-sender (--configure):
 dependency problems - leaving unconfigured
Setting up xserver-xorg-video-all (1:7.7+19) ...
Setting up cups (2.2.1-8) ...
Setting up rpm (4.12.0.2+dfsg1-2) ...
Setting up libsmbclient:amd64 (2:4.5.12+dfsg-2+deb9u1) ...
dpkg: dependency problems prevent configuration of qubes-vm-recommended:
 qubes-vm-recommended depends on qubes-input-proxy-sender; however:
  Package qubes-input-proxy-sender is not configured yet.

dpkg: error processing package qubes-vm-recommended (--configure):
 dependency problems - leaving unconfigured

Errors were encountered while processing:
 qubes-core-agent
 qubes-input-proxy-sender
 qubes-vm-recommended
E: Sub-process /usr/bin/dpkg returned an error code (1)
Removing 'local diversion of /sbin/initctl to /sbin/initctl.distrib'
Makefile:56: recipe for target 'rootimg-build' failed
make[1]: *** [rootimg-build] Error 100**
[template-stretch.log](https://github.com/QubesOS/qubes-issues/files/1733128/template-stretch.log)

---

#### Related issues:

Awokd posted in qubes-users list thread: https://groups.google.com/forum/#!topic/qubes-users/BHFmzxSb6Lg

 Might be some kind of interaction between
https://github.com/QubesOS/qubes-core-agent-linux/pull/81/commits/41f568766f36e7f7588c14490196c906e57a2c22
 (merged 4 days ago) and
https://github.com/QubesOS/qubes-core-agent-linux/commit/00e846bbbe581aceeeaf4a8369748d4ff450b1b0

**Comment by awokd** [comment]
Was thinking a bit more about this and because it errors right after installing `fstab`, 

>Installing new version of config file /etc/fstab ...
>chown: cannot access '/home_volatile/user': No such file or directory

Maybe whatever fstab it's installing there loses the filesystem completely?

**Comment by TimFW** [comment]
That could be.  I did not consider that

**Comment by unman** [comment]
@andrewdavidwong 
The Template now builds correctly - I suspect commits in qubes-core-agent have fixed the issue, although I haven't investigated further.
Can you close this please.
