### ISSUE TITLE
Qubes Manager - manually stopping VM causes error message displayed

### ISSUE THREAD

**Issue by qubecub** [QubesOS/qubes-issues#3600]
#### Qubes OS version:

Qubes OS 4.0 rc4

#### Affected TemplateVMs: 

dom0 - Qube Manager

---

### Steps to reproduce the behavior:

Manually stopping VM, e.g. personal or untrusted or any other in fact, causes error message to pop up. 
Error message says:
"Whoops. A critical error has occured. This is most likely a bug in Qubes Manager.
ValueError: could not convert string to float:
at line 178
of file /usr/lib/python3.5/site-packages/qubesmanager/qube_manager.py"

### Expected behavior:

VM just stops after clicking on a manual stop icon.

### Actual behavior:

Manually stopping VM, e.g. personal or untrusted or any other in fact, causes error message to pop up. 
Error message says:
"Whoops. A critical error has occured. This is most likely a bug in Qubes Manager.
ValueError: could not convert string to float:
at line 178
of file /usr/lib/python3.5/site-packages/qubesmanager/qube_manager.py"

line: vm_start_time=datetime.fromtime.fromtimestamp(float(vm.start_time))
func: check_if_vm_has_shutdown
line: no: 178
file /usr/lib/python3.5/site-packages/qubesmanager/qube_manager.py"

### General notes:

---

**Comment by marmarek** [comment]
Check version of qubes-manager package - very similar bug was already fixed in [qubes-manager 4.0.15](https://github.com/QubesOS/updates-status/issues/411)

**Comment by qubecub** [comment]
Thank you, that's a very good news. 
I have installed Q4.0 rc4 as it is, without additional udpates/upgrades. 
If there is already a dev /test version of the qubes I will give it a try. I expect this this issue is now fixed.

**Comment by qubecub** [comment]
I've just checked and indeed I was running 4.0.13-1.fc25 version of qubes-manager. 
Can I upgrade official rc4 version with the one you mentioned (coming from the r4.0-dom0-cur-test) ?
Or should I just wait fro the next official qubes releases? 
Many thanks.

**Comment by lunarthegrey** [comment]
qubes-manager 4.0.15-1 is working fine for me. It does fix the bug it seems.

**Comment by andrewdavidwong** [comment]
@qubecub, you could try enabling the `current-testing` repo:

https://www.qubes-os.org/doc/software-update-dom0/#testing-repositories

Please let us know whether it fixes the bug for you so that we know whether this issue should be closed.

**Comment by marmarta** [comment]
Fixed by https://github.com/QubesOS/qubes-manager/commit/5af2709
