### ISSUE TITLE
DispVMs launched from whonix-ws-based VMs use clearnet by default

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#3601]
#### Qubes OS version:

`R4.0-rc4`

#### Affected TemplateVMs: 

`whonix-ws`

---

### Steps to reproduce the behavior:

1. In a default `R4.0-rc4` installation, create a new VM called `anon-whonix-2` based on `whonix-ws`.
2. Launch a DispVM from `anon-whonix-2`.

### Expected behavior:

The DispVM uses `sys-whonix` as its NetVM so that its traffic is Torified.

### Actual behavior:

The DispVM uses the NetVM of the `default_dispvm`, which is not `sys-whonix` by default, resulting in a high risk of deanonymization.

-----
### Related issues:

Reported by @mirrorway in #3595. Also see #3561.

CC: @adrelanos

**Comment by andrewdavidwong** [comment]
> Now that Whonix 14 is released, and now that we have salt / qubes-core-admin-whonix for this.... Does it work for you after using the following?
> 
> https://www.whonix.org/wiki/Qubes/Install
> 
> Most importantly from that page regarding this issue:
> 
>     sudo qubesctl state.sls qvm.whonix-ws-dvm

@mirrorway, please let us know if it works after doing this.

**Comment by adrelanos** [comment]
Is this still reproducible in Qubes R4.1?

**Comment by andrewdavidwong** [comment]
Closing due to the prolonged lack of user response. If anyone is still affected by this issue, please leave a comment, and we'll be happy to reopen it. Thank you.
