### ISSUE TITLE
/var/log/qubes/* disk usage: logrotate and decrease debug log level ?

### ISSUE THREAD

**Issue by taradiddles** [QubesOS/qubes-issues#3603]
#### Qubes OS version:

R4.0rc4

---

### Expected behavior:

* /var/log/qubes/\*disp\* log files (and maybe more generally all log files in this dir) should be compressed/rotated and old files ultimately deleted.
* There should be a knob to decrease the debug log level of guid* and qmmeman.

### Actual behavior:

* With the new random disp VM numbering the log dir ends up being cluttered with *dispXXXX* files. They should be deleted after some time (one month ?)
* Some log files are huge - see below. Total size is likely not a concern in itsef compared to what VMs use, but outputting thousands of lines over the course of a short dispvm usage isn't I/O friendly for people without SSDs.

```
1.2M Feb 13 18:59 guid.disp4856.log
1.2M Feb  9 21:25 guid.win7new.log.old
2.5M Feb 17 12:47 guid.disp3860.log
3.0M Feb 10 09:55 guid.disp6293.log
3.2M Feb 15 11:12 guid.disp9183.log
3.3M Feb 17 14:04 guid.disp4857.log
4.5M Feb 17 14:04 guid.disp230.log
5.5M Feb 11 13:25 guid.disp1576.log
5.6M Feb 14 13:40 guid.disp3318.log
8.9M Feb 17 20:43 guid.disp9486.log
11M Feb 10 18:34 guid.disp6497.log
11M Feb  9 17:49 guid.disp6934.log 
12M Feb 10 15:39 guid.disp132.log 
14M Feb 16 20:18 guid.disp8740.log
30M Feb 10 18:34 guid.disp7365.log
31M Feb 11 23:38 guid.disp60.log
34M Feb 18 09:08 qmemman.log
36M Feb 15 14:38 guid.disp7765.log
60M Feb 15 23:39 guid.disp3787.log
```

`wc -l guid.disp3787.log` : 763074 !

system uptime: < 2 days.

---

**Comment by 3hhh** [comment]
Totally supporting this statement.

My /var/log/qubes is currently 1.3G large, /var/log/journal 3.6G.

Both should have some reasonable limits set: From my point of view only the last 10 boot sessions or so should be deemed relevant.

Since these defaults slow down e.g. journalctl significantly I'd also consider this a bug rather than a feature request.

Related qubes-users discussion: https://groups.google.com/forum/#!topic/qubes-users/xuqbv-oR5iQ

**Comment by marmarek** [comment]
`/var/log/qubes/guid.*.log` are kept only for last two (the current and the previous) VM startups.  Same for `qrexec.*.log`, `qubesdb.*.log` and `pacat.*.log`.
Indeed with randomized DispVM names, there may be quite a lot of them. But normally they should be small - only errors are logged there by default. On my system the biggest one is ~300K. Did you enabled debug mode or increased verbosity in some other way @taradiddles ?

Two logs that really should have logrotate set are `/var/log/qubes/qmemman.log` and `/var/log/qubes/qubes.log`.

**Comment by taradiddles** [comment]
> Did you enabled debug mode or increased verbosity in some other way

No, I didn't change anything.

I had totally forgotten about that issue and your comment made me have another look at the `/var/log/qubes/guid.*.log` files. It seems that all the huge logs I have are from VMs that have/had debug enabled, with 99.9% of the lines like these:

```
shmimage for 0x400005d(remote 0xc00022), x: 2, y: 28, w: 13, h: 26
  do_shm_update for 0x400005d(remote 0xc00022), after border calc: x=2, y=28, w=13, h=26
```

Those lines are appended to the log when moving the mouse over a VM window (and probably when there's any "gui" activity), with hundreds of lines created just by moving the pointer from one border of a window to the other.

I see that I still have million+ lines dispvm logs from April to May of last year (99.9% of the lines are also "shm..." stuff). But I don't see any crazy sized guid.dispxxxx files anymore after that date. No idea if something changed with some qubes-* packages by that time or if I had managed to mistakenly enable debug for the disp template.

Maybe there should be a logrotate rule (or a `tmpwatch` cron) which deletes dispvm guid log files older than X months ?

I guess it's expected to have a lot of info when debug is enabled, but I mainly use that option to see the early display of (H)VMs that don't have the qubes display driver installed. Maybe it would make sense to separate the "real" debug from the "enable display" setting ? Or change the debug pref from boolean to integer (verbosity level), 1/true being for enabling the display ?

> Two logs that really should have logrotate set are /var/log/qubes/qmemman.log and /var/log/qubes/qubes.log.

Yes, they are properly rotated on my system.
