### ISSUE TITLE
windows tools 4.0

### ISSUE THREAD

**Issue by virgileaime** [QubesOS/qubes-issues#3605]
Are windows tools available yet in 4.0 for Windows 7?

Thank you

**Comment by Aekez** [comment]
There are a lot of threads discussing this on the google mails, you can find a lot of information about this issue there. Although not everything is discussed in all of them, so you have to search and look in various threads to get more information.

As for the Windows Tools, it's known that there is no one assigned to it atm, but there has been made work-arounds by the community, and there are people among the end-users considering to pick it up and patch it to Qubes 4, but nothing official yet. The takeaway, by the looks, is that not much needs to be done to make it work for Qubes 4, however, without any new features which would take much more work. Currently however, no one has taken up this work to bring Windows Tools back to a minimum basic state, without extra features, as of yet.

You can look here for a work-around approach to install a fresh new Windows on Qubes 4, https://groups.google.com/forum/#!searchin/qubes-users/win7$20install$20ivan%7Csort:date/qubes-users/CsVpMfpngP8/vWduZ9PwBwAJ
check the last post by Ivan Mitev, the 9th of february, for a way to extract the packages to install the 3.2. tools on Qubes 4. Note that this isn't anything official, but it should work, mostly, if you apply some extra work-arounds. Like fixing the lack of networking between Qubes 4 and Windows (and thereby internet) by putting a fixed IP after you disabled the Qubes-network tool service in Windows, as well as changing the cache to a fixed size. Note the IP can change, so this can be a bit annoying. Also Windows may crash initially without enough RAM, but after you change the cache and reboot once or twice, you should be able to minimize how much RAM it needs to avoid crashing. Probably best to start with 4GB RAM, and then move down to 2.5GB RAM as a minimum for light use-cases, once you fixed everything, though you should probably give it more than 2.5GB if you're up for heavier programs in windows.

All this is anecdotal, however, has been confirmed working on multiple computers, and no one has reported it not working yet. So its anecdotal from a statistical and scientific point of view (objective paradigm), but, the odds are good that it will work for you too.

**Comment by andrewdavidwong** [comment]
Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this does not appear to be suitable for `qubes-issues`. We ask that you please send this to the `qubes-users` [mailing list](https://www.qubes-os.org/mailing-lists/) instead. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a brief comment explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.
