### ISSUE TITLE
VM firewall: option to 'reject' output packets instead of 'drop'

### ISSUE THREAD

**Issue by taradiddles** [QubesOS/qubes-issues#3607]
#### Qubes OS version:

R4.x

#### Proposed enhancement

Implement an option to reject a VM's *outgoing* packets instead of dropping them, for VMs with "whitelist" firewalls (= "limit connections to..." in the gui).

The rationale behind rejecting out packets instead of dropping them is to avoid:
* having to wait for tcp timeouts to find out that there's no network connectivity to a given address
* breaking functionality of sites that load unwanted (= not whitelisted) third-party sites in a blocking way. When dropping packets the sites become functional only after the tcp/http request timeouts. The 'manager' site of the Linode cloud provider for instance falls into this category: the site tries to load a third-party support site and the login page and other functionality appear only when the http request to the support site timeouts.

Note: rejecting packets means sending icmp unreachable or tcp reset packets from the FirewallVM back to the originating VM ; I don't see how this would increase the attack surface on the FirewallVM (how would the reject packets be different than - say - fragmentation neeeded packets ?). But this should be given some thoughts if the option is to be implemented.

BTW I tried to implement this 'reject' functionality in the various qubes firewall.py files (admin, tests, ...) but I keep on getting errors so I must be missing something.

Workaround: in the VM's network VM (eg. sys-firewall), insert an nft reject rule at the appropriate position. For instance, add a rule for the VM with ip 10.137.0.7 at handle 22 before the catch-all 'drop' target (the handle number is determined by `nft list table qubes-firewall -a`):

`nft insert rule ip qubes-firewall qbs-10-137-0-7 position 22 reject`

**Comment by adrelanos** [comment]
output:
I agree. Reject should be preferred over drop. Imo not even an option
needed. Reject should be default. This ticket is about output only.

input:
Drop makes sense to avoid ddos. But this ticket is not about input, so
no need to discuss it here.

**Comment by marmarek** [comment]
:+1: for reject on output

**Comment by marmarek** [comment]
I wonder if this should be the only option - i.e. replace the current "drop" rule. Or make it configurable?

**Comment by DemiMarie** [comment]
@marmarek I think it should.  It is much more user-friendly and just as secure.

**Comment by donob4n** [comment]
In my opinion only reject would be fine.
