### ISSUE TITLE
qvm-copy doesn't work

### ISSUE THREAD

**Issue by dakka2** [QubesOS/qubes-issues#3614]
#### Qubes OS version:
R4.0

#### Affected TemplateVMs: 
All

### Steps to reproduce the behavior:
qvm-copy any file from any vm to any vm

### Expected behavior:
file copies

### Actual behavior:
Request Refused

### General notes:
from qrexec log in dom0:
Traceback (most recent call last):
  File /usr/bin/qrexec-policy, line 5, in <module>
    sys.exit(main())
  File /usr/lib/python3.5/site-packages/qubespolicy/cli.py, line 128, in main
    action.targets_for_ask, action.target or '', icons)
  File /usr/lib/python3.5/site-packages/pydbus/proxy_method.py, line 75, in __call__
    0, timeout_to_glib(timeout), None).unpack()
GLib.Error: g-io-error-quark: GDBus.Error:unknown.AssertionError: Input string was expected to be sanitized, but was not. (36)

Seems to be related to qubes-core-admin 4.0.23 / qubes-core-admin-linux 4.0.11 / qubes-core-agent-linux 4.0.22 but I don't know for sure. Packages in testing not unstable.

please delete #3613 it was created by mistake.

**Comment by marmarek** [comment]
You need to restart `qrexec-policy-agent` in dom0:
```
killall qrexec-policy-agent
qrexec-policy-agent &
```
Or simply restart the system.

**Comment by marmarek** [comment]
Also, be sure to install updates in templates before that.

**Comment by dakka2** [comment]
Just you you know it's still $default in qvm-copy/qvm-copy-to-vm in the templates. it worked after restarting policy agent anyway.
