### ISSUE TITLE
'qvm-run -u root' environment missing PATH, DISPLAY, etc. after QSB #38 updates

### ISSUE THREAD

**Issue by rustybird** [QubesOS/qubes-issues#3615]
#### Qubes OS version:

R4.0 rc4 (latest current-testing/security-testing in dom0)

#### Affected TemplateVMs: 

e.g. fedora-26

---

### Steps to reproduce the behavior:

    qvm-run -u root -p fedora-26-current-vm          env | sort >before
    qvm-run -u root -p fedora-26-security-testing-vm env | sort >after
    diff -u before after

### Expected behavior:

No significant environment differences

### Actual behavior:

Some environment variables have vanished:

- DISPLAY
- HISTCONTROL
- HISTSIZE
- HOSTNAME
- LANG
- MAIL
- PATH
- XDG_DATA_DIRS

### General notes:

The root user's shell is the default, Bash.

**Comment by tasket** [comment]
debian-9 appears partly affected. The following are not defined:
* DISPLAY
* HISTSIZE
* HOSTNAME
* MAIL
* PATH
But XDG_DATA_DIRS looks like it might not be normally set on Debian.

Some of the above like `PATH` are still available as set variables even though they aren't in env.

---
On f26 I get the same results as rustybird.

**Comment by rustybird** [comment]
This breaks built-in services like `qubes.ResizeDisk`:

    $ qvm-volume extend fedora-26-security-testing-vm:private $(( 10 * 1024**3 ))
    Online resize of volume appvms/fedora-26-security-testing-vm/private failed (you need to resize filesystem manually): /etc/qubes-rpc/qubes.ResizeDisk: line 11: resize2fs: command not found

Probably also `qubes.SuspendPre` and `qubes.SuspendPost`, because `modprobe` is in `/sbin`.

**Comment by marmarek** [comment]
@rustybird @tasket See linked PR. I've verified that missing environment variables are restored. But I don't want to make it worse - can you verify if the fix works for you?
The one side effect I'm aware of, is for normal user (`user`) the startup scripts are loaded twice. But it should be harmless...

**Comment by donob4n** [comment]
It restored VM updates from Qubes Manager on 3.2
