### ISSUE TITLE
Qubes R4.0 cannot launch any VMs

### ISSUE THREAD

**Issue by anoadragon453** [QubesOS/qubes-issues#3616]
#### Qubes OS version:
R4.0 rc4

#### Affected TemplateVMs: 
dom0

---

### Steps to reproduce the behavior:

* Install Qubes, all is fine
* Try to start a VM through the terminal as Qubes Manager doesn't launch

### Expected behavior:

* VM Opens

### Actual behavior:

* qvm-start crashes

### General notes:

Output for launching `sys-net`:

```
Traceback (most recent call last):
  File "/usr/bin/qvm-start", line 5, in <module>
    sys.exit(main())
  File "/usr/lib/python3.5/site-packages/qubesadmin/tools/qvm_start.py", line 158, in main
    args = parser.parse_args(args, app=app)
  File "/usr/lib/python3.5/site-packages/qubesadmin/tools/__init__.py", line 389, in parse_args
    action.parse_qubes_app(self, namespace)
  File "/usr/lib/python3.5/site-packages/qubesadmin/tools/__init__.py", line 176, in parse_qubes_app
    namespace.domains += [app.domains[vm_name]]
  File "/usr/lib/python3.5/site-packages/qubesadmin/app.py", line 86, in __getitem__
    if not self.app.blind_mode and item not in self:
  File "/usr/lib/python3.5/site-packages/qubesadmin/app.py", line 100, in __contains__
    self.refresh_cache()
  File "/usr/lib/python3.5/site-packages/qubesadmin/app.py", line 60, in refresh_cache
    'admin.vm.List'
  File "/usr/lib/python3.5/site-packages/qubesadmin/app.py", line 474, in qubesd_call
    client_socket.sendall(call_arg.encode('ascii'))
OSError: [Errno 107] Transport endpoint is not connected
```

Output for launching `qubes-qube-manager`:

```
line: client_socket.sendall(call_arg.encode('ascii'))
func: qubesd_call
line no.: 474
file: /usr/lib/python3.5/site-packages/qubesadmin/app.py
----
line: 'admin.vm.List'
func: refresh_cache
line no.: 60
file: /usr/lib/python3.5/site-packages/qubesadmin/app.py
----
line: self.refresh_cache()
func: __iter__
line no.: 108
file: /usr/lib/python3.5/site-packages/qubesadmin/app.py
----
line: return [vm for vm in self.qubes_app.domains]
func: <listcomp>
line no.: 396
file: /usr/lib/python3.5/site-packages/qubesmanager/qube_manager.py
----
line: return [vm for vm in self.qubes_app.domains]
func: get_vms_list
line no.: 396
file: /usr/lib/python3.5/site-packages/qubesmanager/qube_manager.py
----
line: vms_list = self.get_vms_list()
func: fill_table
line no.: 409
file: /usr/lib/python3.5/site-packages/qubesmanager/qube_manager.py
----
line: self.fill_table()
func: __init__
line no.: 362
file: /usr/lib/python3.5/site-packages/qubesmanager/qube_manager.py
----
line: manager_window = VmManagerWindow(qubes_app, qt_app)
func: main
line no.: 1182
file: /usr/lib/python3.5/site-packages/qubesmanager/qube_manager.py
----
line: load_entry_point('qubesmanager==4.0.13', 'console_scripts', 'qubes-qube-manager')()
func: <module>
line no.: 9
file: /bin/qubes-qube-manager
```

---

#### Related issues:

I was also unable to launch VMs on RC3.

Laptop is HP Spectre 15T, Processor [i7-8550u](https://ark.intel.com/products/122589/Intel-Core-i7-8550U-Processor-8M-Cache-up-to-4_00-GHz).

**Comment by unman** [comment]
@anoadragon453 Were you ever able to get Qubes working on this laptop? The fact that you were unable to do so using rc3 makes me think it is likely hardware/configuration specific. If you have any interest in reviving this, lets' talk on the qubes-users mailing list.
There are 2 entries on the [HCL](https://www.qubes-os.org/hcl/) for Spectre with i7-8550U processors, both reporting that the system works. One required some modification to the install media.

@andrewdavidwong - In view of age, and the HCL entries, I suggest this be closed.

**Comment by anoadragon453** [comment]
I'm afraid I don't quite remember whether I did get qubes working correctly in the end (I *think* not) and unfortunately since then the motherboard on this model has fried. I have a Thinkpad X1 Carbon 6th generation now which I can use to test an install if you'd like, but otherwise I probably won't be much use :slightly_smiling_face:
