### ISSUE TITLE
StandaloneVM from ISO (windows7) shuts down on logo

### ISSUE THREAD

**Issue by Luisames** [QubesOS/qubes-issues#3618]
**Qubes OS version**:
- Qubes release 4.0 (R4.0-rc4)

**Affected TemplateVMs:** 
- StandaloneVM from iso (windows7)

---

**Steps to reproduce the behavior:**
qvm-create win --class StandaloneVM --label purple
qvm-prefs win kernel ''
changing in /usr/share/qubes/templates/libvirt/xen.xml the video-section: "vga" to "cirrus" 
Qube Manager win-VM Settings (Basic and Advanced):
- Disk storage - Private storage max. size: 5120 MiB, System storage max. size: 30720 MiB
- Memory/CPU - Initial memory: 1024 MB, Max. memory: 2048 MB
- Virtualization - Mode: HVM

sudo qvm-start win --cdrom=sys-usb:<path to .iso>

**Expected behavior:**
- Windows Installation process

**Actual behavior:**
- VM shuts down

**General notes:**
- VM shuts down on windows logo or rather don`t react anymore

**Related issues:**
#3432

**Comment by Luisames** [comment]
I found some "out of PoD memory" errors in /var/log/xen/console/hypervisor.log". 
I tried to follow your windows install guide and now there aren`t any "out of PoD memory" errors, but now when I try to start the installing process with "sudo qvm-start win --cdrom=sys-usb:<path to .iso>" there comes the notification output "Not enough memory to start domain 'win'."

**Comment by taradiddles** [comment]
> "Not enough memory to start domain 'win'."

That means you don't have enough RAM available on your machine to start the VM. Try to shutdown unneeded VMs.
Alternatively you could try to lower Windows' memory to 3000 or something like that, but be prepared to loose some time if that value proves not to be enough (in which case the windows installer will crash and you'll have to begin from scratch).

**Comment by Luisames** [comment]
Thank you very much! Now everything is working after I closed unneeded VMs.

**Comment by taradiddles** [comment]
OK :)
I'll add a note about the "not enough memory" error in the upcoming windows documentation. Feel free to comment in #3592 if you find something that should be better explained or if you think something is missing or wrong

(you may close your issue if you think it's resolved).
