### ISSUE TITLE
sys-usb fail to start

### ISSUE THREAD

**Issue by holiman** [QubesOS/qubes-issues#3619]
#### Qubes OS version:

4.0 (R4.0)

#### Affected TemplateVMs: 

sys-usb

---

### Steps to reproduce the behavior:

* Plug in some usb-thing, expect something to happen. 
* Notice that the sys-usb is not running, try to start it with `qvm-start sys-usb` (or gui). 
* Get the message `PCI device <qubes.ext.pci.PCIDevice object at 0x72be4ade00f0> does not exist`

### Expected behavior:

* Plug in some usb-thing, something happens. 

### General notes:

Hardware Lenovo X1 Carbon Gen 5. USB devices have worked, but now they don't. Have only booted it a couple of times since it was installed, so I can't say how often it occurs yet. 

---

**Comment by holiman** [comment]
Rebooted now, and then did `systemctl status qubes-vm@sys-usb.service`. It says basically the same thing, failed to start because of some pci-device that does not exist.

**Comment by holiman** [comment]
It was connected to a lenovo docking station over usb-c while I was installing it. I wonder if that docking station is the "missing" PCI device... if so, how do I make qubes forget about it?

**Comment by marmarek** [comment]
Very likely. See `qvm-pci ls sys-usb`, and then use `qvm-pci detach sys-usb <the device>`

**Comment by holiman** [comment]
There are two devices there, one `USB controller: Intel ... xHCI Controller` and one `Unknown device`.

**Comment by marmarek** [comment]
Definitely the "Unknown" one.

**Comment by holiman** [comment]
Thanks, detaching the `Unknown device` made sys-usb boot again!

**Comment by thoughtless** [comment]
I ran into this recently and [this](https://github.com/QubesOS/qubes-issues/issues/3619#issuecomment-367757857) did fix it.

I use an external monitor with a USB hub. When I shut down my laptop, and then disconnect the monitor and USB hub, then I don't think this is an issue for me. However, if I disconnect the monitor and USB hub _while_ my laptop is shutting down, then (sometimes) I hit this issue.

I don't know enough about USB to know exactly what might be happening, but I thought that this info might help someone else who is hitting this problem work around it.
