### ISSUE TITLE
qubes-dom0-update fails when the template is missing /var/lib/qubes/dom0-updates dir

### ISSUE THREAD

**Issue by ij1** [QubesOS/qubes-issues#3620]
#### Qubes OS version:

R3.2

#### Affected TemplateVMs: 

debian-9 derived template that for some reason had /var/lib/qubes/dom0-updates missing.

The reason why it has gone missing is unknown, however, I recently (a few days ago) installed QSB\#38 packages into that template and this was the first time I used qubes-dom0-updates after that (IIRC).

---

### Steps to reproduce the behavior:

- Remove /var/lib/qubes/dom0-updates from updatevm
- Run sudo qubes-dom0-update in dom0

### Expected behavior:

Normal update process.

### Actual behavior:

\[dom0\]\$ sudo qubes-dom0-update
Using sys-firewall as UpdateVM to download updates for Dom0; this may take some time...
Running command on VM: \'sys-firewall\'...
Running command on VM: \'sys-firewall\'...
tar: /var/lib/qubes/dom0-updates: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
Dom0 updates dir does not exists: /var/lib/qubes/dom0-updates
\[dom0\]\$

### General notes:

I was able to restore the functionality by adding that /var/lib/qubes/dom0-updates and chowning it to user.user.

The same problem occurs also with --clean option so it won't help any.

**Comment by donob4n** [comment]
Fixed with https://github.com/donob4n/qubes-core-admin-linux/commit/facf84a4e66c1b0bb6b0614ff7c0ea55d5a07551

But I'm not sure if the bug is this not working when there is no /var/lib/qubes/dom0-updates or the fact it doesn't exist.

**Comment by ij1** [comment]
Will that fix actually work? Doesn't mkdir return an error if the directory is already there?

**Comment by donob4n** [comment]
Yes but qvm-run doesn't, so it just ignores it. I though about doing more elegant "if else" but is not really too much benefit since it's ignored and chown could fix a rare permission corruption.

**Comment by donob4n** [comment]
uhM, it seems retcode is ignored because there is no --pass-io

**Comment by ij1** [comment]
I think I've now found the cause for the missing the directory. The directory was present in qubes-core-agent v3.2.22 but not any more in the \#QSB38-fixed versions (probably due to some non-\#QSB38 related pending work that got included to the newer version).
