### ISSUE TITLE
Qubes Manager update feature not working

### ISSUE THREAD

**Issue by Simon-Davies** [QubesOS/qubes-issues#3621]
#### Qubes OS version:

Qubes 4.0 R4.0

#### Affected TemplateVMs: 

fedora-26
debian-9

---

### Steps to reproduce the behavior:

Right click template VM - Update qube in GUI
Click blue arrow - Update qube system in GUI 

### Expected behavior:

Qube updates

### Actual behavior:

Qube doesn't update.
You have to manually update by opening a terminal and executing the update commands:

Fedora - sudo dnf update 
Debian - sudo update && sudo upgrade 

### General notes:

---

**Comment by marmarek** [comment]
Looks like a duplicate of #3526.
Can you check what version of qubes-core-agent package in VMs do you have?
Alternatively, start qube first, then click on update and see what happens.

**Comment by Simon-Davies** [comment]
This is fixed after following advise from #3526 and enabling testing permanently in all templates
