### ISSUE TITLE
Qubes Manager - VM testing repo enabled (new bugs)

### ISSUE THREAD

**Issue by Simon-Davies** [QubesOS/qubes-issues#3623]
#### Qubes OS version:

Qubes 4.0 R4.0

#### Affected TemplateVMs: 

All

---

### Steps to reproduce the behavior:

Enable VM testing repo
Update template
Shutdown template
Start template 

First bug: 

Click the stop VM button in Qubes Manager to shut down the template 

Second bug: 

Right click VM template - Kill qube

Third bug:

Right click VM template - Restart qube

### Expected behavior:

Template shutsdown/is killed/restarts

### Actual behavior:

First bug: 

Whoops. A critical error has occurred. This is most likely a bug in Qubes Manager.

AssertionError:
at line 771
of file /usr/lib/python3.5/site-packages/qubesmanager/qubesmanager.py.

Second bug: 

Whoops. A critical error has occurred. This is most likely a bug in Qubes Manager.

AssertionError:
at line 829
of file /usr/lib/python3.5/site-packages/qubesmanager/qubesmanager.py.

Third bug:

Whoops. A critical error has occurred. This is most likely a bug in Qubes Manager.

AssertionError:
at line 809
of file /usr/lib/python3.5/site-packages/qubesmanager/qubesmanager.py.

### General notes:

---

**Comment by lunarthegrey** [comment]
I'm not getting this in qubes-manager version 4.0.15-1.fc25

What version do you have?

**Comment by Simon-Davies** [comment]
I've got the latest version from the dom0 current-testing repo. These bugs don't happen all the time but I experienced them yesterday
