### ISSUE TITLE
4.0-rc4 EFI installation has duplicates in xen.cfg & missing Rescue option

### ISSUE THREAD

**Issue by eduncan911** [QubesOS/qubes-issues#3624]
#### Qubes OS version:

4.0-RC4

#### Affected TemplateVMs: 

EFI booting: `/boot/efi/EFI/qubes/xen.cfg`

---

### Steps to reproduce the behavior:

- Install Qubes 4.0-RC4 on an EFI-only machine (tested on Apple hardware).
- Boot system and look at `/boot/efi/EFI/qubes/xen.cfg` entries

### Expected behavior:

Something like this would be more user friendly for a default Qubes installation:

```
[global]
default=qubes-4.14.13-2

[qubes-4.14.13-2]
options=loglvl=all dom0_mem=min:1024M dom0_mem=max:4096M iommu=no-igfx
kernel=vmlinuz-4.14.13-2.pvops.qubes.x86_64 root=/dev/mapper/qubes_dom0-root rd.lvm.lv=qubes_dom0/root rd.lvm.lv=qubes_dom0/swap i915.preliminary_hw_support=1 rhgb quiet
ramdisk=initramfs-4.14.13-2.pvops.qubes.x86_64.img

[qubes-4.14.13-2-rescue]
options=loglvl=all dom0_mem=min:1024M dom0_mem=max:4096M iommu=no-igfx
kernel=vmlinuz-4.14.13-2.pvops.qubes.x86_64 rescue
ramdisk=initramfs-4.14.13-2.pvops.qubes.x86_64.img
```

### Actual behavior:

This is currently written:

```
[global]
default=4.14.13-2.pvops.qubes.x86_64

[4.14.13-2.pvops.qubes.x86_64]
options=loglvl=all dom0_mem=min:1024M dom0_mem=max:4096M iommu=no-igfx
kernel=vmlinuz-4.14.13-2.pvops.qubes.x86_64 root=/dev/mapper/qubes_dom0-root rd.lvm.lv=qubes_dom0/root rd.lvm.lv=qubes_dom0/swap i915.preliminary_hw_support=1 rhgb quiet
ramdisk=initramfs-4.14.13-2.pvops.qubes.x86_64.img

[4.14.13-2.pvops.qubes.x86_64]
options=loglvl=all dom0_mem=min:1024M dom0_mem=max:4096M iommu=no-igfx
kernel=vmlinuz-4.14.13-2.pvops.qubes.x86_64 root=/dev/mapper/qubes_dom0-root rd.lvm.lv=qubes_dom0/root rd.lvm.lv=qubes_dom0/swap i915.preliminary_hw_support=1 rhgb quiet
ramdisk=initramfs-4.14.13-2.pvops.qubes.x86_64.img
```

### General notes:

Shortening the names would make it simpler for EFI Shell booting of Xen with parameters.

Also, I've only been testing and submitting patches for 4.0 RC4 on different Apple hardware.  Looking at the `bootloader.py`, there doesn't seem to be anything specific to Apple when it comes to writing the `xen.cfg`.

Therefore, it seems global to all EFI-only installations.

---

**Comment by DemiMarie** [comment]
Closing as it is unlikely to be applicable to R4.1.
