### ISSUE TITLE
Qubes doesn't start VMs on 20% of boots

### ISSUE THREAD

**Issue by 3hhh** [QubesOS/qubes-issues#3626]
#### Qubes OS version:
Since 4.0rc3, currently with 4.0rc4.

#### Affected component(s): 
VMs, dom0 starts fine

### Steps to reproduce the behavior:
boot and get unlucky in 20% of cases (at least for me that's the case)

### Expected behavior:
VMs can be started

### Actual behavior:
VMs seem to start (notification appears), but apparently they hang at some point; all are affected equally

Attempting to run `qvm-run -p vm 'echo bla'` returns
```
gntshr: error: ioctl failed: No space left on device
Failed to start data vchan server
```
Some suspicious entries from a dom0 `sudo journalctl -b0`:
Multiple
`Feb 24 12:50:27 dom0 qmemman.daemon.reqhandler[2067]: EOF`
and multiple
```
Feb 24 12:55:46 dom0 qubesd[2055]: unhandled exception while calling src=b'[VM name]' meth=b'qubes.NotifyUpdates' dest=b'dom0' arg=b'' len(untrusted_payload
)=2
Feb 24 12:55:46 dom0 qubesd[2055]: Traceback (most recent call last):
Feb 24 12:55:46 dom0 qubesd[2055]:   File "/usr/lib/python3.5/site-packages/qubes/api/__init__.py", line 262, in respond
Feb 24 12:55:46 dom0 qubesd[2055]:     untrusted_payload=untrusted_payload)
Feb 24 12:55:46 dom0 qubesd[2055]:   File "/usr/lib64/python3.5/asyncio/futures.py", line 381, in __iter__
Feb 24 12:55:46 dom0 qubesd[2055]:     yield self  # This tells Task to wait for completion.
Feb 24 12:55:46 dom0 qubesd[2055]:   File "/usr/lib64/python3.5/asyncio/tasks.py", line 310, in _wakeup
Feb 24 12:55:46 dom0 qubesd[2055]:     future.result()
Feb 24 12:55:46 dom0 qubesd[2055]:   File "/usr/lib64/python3.5/asyncio/futures.py", line 294, in result
Feb 24 12:55:46 dom0 qubesd[2055]:     raise self._exception
Feb 24 12:55:46 dom0 qubesd[2055]:   File "/usr/lib64/python3.5/asyncio/tasks.py", line 240, in _step
Feb 24 12:55:46 dom0 qubesd[2055]:     result = coro.send(None)
Feb 24 12:55:46 dom0 qubesd[2055]:   File "/usr/lib64/python3.5/asyncio/coroutines.py", line 210, in coro
Feb 24 12:55:46 dom0 qubesd[2055]:     res = func(*args, **kw)
Feb 24 12:55:46 dom0 qubesd[2055]:   File "/usr/lib/python3.5/site-packages/qubes/api/misc.py", line 123, in qubes_notify_updates
Feb 24 12:55:46 dom0 qubesd[2055]:     if self.src.storage.outdated_volumes:
Feb 24 12:55:46 dom0 qubesd[2055]:   File "/usr/lib/python3.5/site-packages/qubes/storage/__init__.py", line 564, in outdated_volumes
Feb 24 12:55:46 dom0 qubesd[2055]:     if volume.is_outdated():
Feb 24 12:55:46 dom0 qubesd[2055]:   File "/usr/lib/python3.5/site-packages/qubes/storage/__init__.py", line 238, in is_outdated
Feb 24 12:55:46 dom0 qubesd[2055]:     raise self._not_implemented("is_outdated")
Feb 24 12:55:46 dom0 qubesd[2055]: NotImplementedError: Volume FileVolume has is_outdated() not implemented
```
qubesd seemed to be up and running. A qubesd restart didn't change anything.

### General notes:
debian-8 and debian-9 templates were tested

#### Related issues:
#3616 sounds similar wrt the outcome, but I think it's a different issue.

**Comment by marmarek** [comment]
> Attempting to run qvm-run -p vm 'echo bla' returns
> 
> gntshr: error: ioctl failed: No space left on device
> Failed to start data vchan server

This looks related. How many VMs do you have running? Check also how many qrexec-client processes are in dom0 (should be about 1 per VM).

**Comment by 3hhh** [comment]
Yesterday I ran into this one again.

> This looks related. How many VMs do you have running?

It's directly after boot, so just 4.

>  Check also how many qrexec-client processes are in dom0 (should be about 1 per VM).

Yes, there was exactly one qrexec-daemon per VM; same for client (before I started trying qvm-run commands).

Another interesting fact:
```
xl console [vm] 
Unable to attach console.
```

**Comment by 3hhh** [comment]
`qvm-ls` however reported the [vm] to be running. No custom init scripts ran though, e.g. no network manager applet for sys-net etc.

**Comment by marmarek** [comment]
> Another interesting fact:
> 
> xl console [vm] 
> Unable to attach console.

Use `sudo xl console -t pv [vm]`

What `virt_mode` this VM have? (`qvm-prefs [vm] virt_mode`)

**Comment by 3hhh** [comment]
> Use sudo xl console -t pv [vm]

I think I also tried with sudo, but ok I'll try again next time it happens.

> What virt_mode this VM have? (qvm-prefs [vm] virt_mode)

3* pvh (out of these 1 disposable), 1* hvm (sys-usb as disposable).

I just sent you the entire journalctl output of the original issue description via e-mail as well - maybe you see more than I do (I didn't want to put it all online).

**Comment by 3hhh** [comment]
> sudo xl console -t pv [vm]

That was the right command, thanks!
All of my VMs seemed up and running fine according to their console, but the GUI didn't show.

Thus I believe I identified the root cause:
As part of #3149 I was starting VMs via the WM autostart (awesome for me), which apparently caused a racing condition between the Qubes GUI daemon (or whatever else is started in /etc/xdg/autostart) start and my autostarted VMs.

I just ran into this 7 times in a row and once I removed the VM autostart, waited a few seconds after my X showed up and then started the VMs manually it now worked 2 times in a row. Time will tell more.

I don't really understand this though as in the default Qubes config the VMs are started before the xdg autostart anyway? So why would I have to wait for it?

For reference some suspicious entries in the journal of one of the VMs (might indicate another unrelated issue though):
```
...
Mar 14 20:38:47 d-sys-usb systemd[1]: Started Session c27 of user user.
Mar 14 20:38:57 d-sys-usb qrexec-agent[633]: pid 1298 exited with -1
Mar 14 20:38:57 d-sys-usb qrexec-agent[633]: eintr
Mar 14 20:39:11 d-sys-usb qrexec-agent[633]: executed user:QUBESRPC qubes.WaitFo
Mar 14 20:39:11 d-sys-usb qrexec-agent[1317]: pam_unix(qrexec:session): session 
Mar 14 20:39:11 d-sys-usb systemd[1]: Started Session c28 of user user.
Mar 14 20:39:20 d-sys-usb qrexec-agent[633]: pid 1317 exited with -1
Mar 14 20:39:20 d-sys-usb qrexec-agent[633]: eintr
Mar 14 20:39:34 d-sys-usb qrexec-agent[633]: executed user:QUBESRPC qubes.WaitFo
Mar 14 20:39:34 d-sys-usb qrexec-agent[1338]: pam_unix(qrexec:session): session 
Mar 14 20:39:34 d-sys-usb systemd[1]: Started Session c29 of user user.
Mar 14 20:39:44 d-sys-usb qrexec-agent[633]: pid 1338 exited with -1
Mar 14 20:39:44 d-sys-usb qrexec-agent[633]: eintr
Mar 14 20:39:58 d-sys-usb qrexec-agent[633]: executed user:QUBESRPC qubes.WaitFo
Mar 14 20:39:58 d-sys-usb qrexec-agent[1392]: pam_unix(qrexec:session): session 
Mar 14 20:39:58 d-sys-usb systemd[1]: Started Session c30 of user user.
...
Mar 14 20:47:06 d-sys-usb kernel: xenbus: xen store gave: unknown error E2BIG
Mar 14 20:47:06 d-sys-usb qrexec-agent[633]: Data vchan connection failed
Mar 14 20:47:06 d-sys-usb qrexec-agent[633]: eintr
Mar 14 20:47:06 d-sys-usb qrexec-agent[633]: Cannot setup watch on /local/domain
Mar 14 20:47:06 d-sys-usb qrexec-agent[633]: Data vchan connection failed
Mar 14 20:47:06 d-sys-usb kernel: xenbus: xen store gave: unknown error E2BIG
...
```

**Comment by 3hhh** [comment]
> As part of #3149 I was starting VMs via the WM autostart (awesome for me), which apparently caused a racing condition between the Qubes GUI daemon (or whatever else is started in /etc/xdg/autostart) start and my autostarted VMs.
> 
> I just ran into this 7 times in a row and once I removed the VM autostart, waited a few seconds after my X showed up and then started the VMs manually it now worked 2 times in a row. Time will tell more.

Nowadays I call this script from the awesome WM autostart:

```bash
#!/bin/bash

#start all the XFCE autostart stuff
#for some stupid reason this apparently must happen BEFORE VMs are started -_- (as of 2018-03 Qubes otherwise crashes in 20% of the boots, cf. https://github.com/QubesOS/qubes-issues/issues/3626)
#dex doesn't block so we need to wait (it also screws with pipes, so we don't give it any)
pgrep -f -a mqui.tray | grep -v $$ || ( dex-autostart -a -e XFCE < /dev/null &> /dev/null ; sleep 10 )

#start VMs
#make sure they are not started by Qubes (qvm-prefs)
#qubes will automatically start all VMs further downstream
qvm-start --skip-if-running sys-usb &
pid=$!
qvm-start --skip-if-running sys-firewall
wait $pid
```

So far this fixed the issue.
It would be interesting to understand the root cause though.

**Comment by 3hhh** [comment]
Closing for now as no one else appeared to have had the same issue.

I haven't observed it myself anymore since back then, but then I didn't try without my workaround anymore neither.

**Comment by pixnion** [comment]
I believe that I get this very same error when I have a lot of windows open, like 20-30 terminals and browsers etc. spanning multiple VMs (currently 14 PVH and 2 HVM).

Whenever this happens I can't execute qvm-run for _any_ VM, but when I close one of the windows/processes already started via qvm-run (regardless of what VM it belongs to), it let's me spawn another one process, but afterwards I get the same issue again.

```
user@dom0:~$ qvm-run work xterm
Running 'xterm' on work
work: command failed with code: 1
```
```
user@dom0:~$ qrexec-client -d work id
gntshr: error: ioctl failed: No space left on device
Failed to start data vchan server
```
strace for `qrexec-client` above shows:
```
open("/dev/xen/gntalloc", O_RDWR)       = 3
ioctl(2, TCGETS, {B38400 opost isig icanon echo ...}) = 0
open("/dev/xen/evtchn", O_RDWR|O_CLOEXEC) = 4
ioctl(4, IOCTL_EVTCHN_BIND_UNBOUND_PORT, 0x7ffe560f321c) = 366
write(4, "n\1\0\0", 4)                  = 4
ioctl(3, _IOC(0, 0x47, 0x5, 0x18), 0x57162aee43d0) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_SHARED, 3, 0) = 0x7a3be41e5000
ioctl(3, IOCTL_GNTDEV_SET_UNMAP_NOTIFY, 0x7ffe560f31b0) = 0
ioctl(3, _IOC(0, 0x47, 0x6, 0x10), 0x7ffe560f31c0) = 0
ioctl(3, _IOC(0, 0x47, 0x5, 0x18), 0x57162aee4400) = 0
mmap(NULL, 65536, PROT_READ|PROT_WRITE, MAP_SHARED, 3, 0x1000) = 0x7a3be4131000
ioctl(3, _IOC(0, 0x47, 0x6, 0x10), 0x7ffe560f31c0) = 0
ioctl(3, _IOC(0, 0x47, 0x5, 0x18), 0x57162aee4400) = -1 ENOSPC (No space left on device)
```

I've been having this issue for quite some time (years?). I'm not out of free memory (got 32GB RAM). I don't reboot very often (leak?) -- this time it happened after 8 days, running:
- Qubes R4.0
- dom0 kernel 4.19.132-1.pvops.qubes.x86_64
- xen 4.8.5-23.fc25

**Comment by marmarek** [comment]
This one looks easy: grant tables limit too small. Write some large number to `/sys/module/xen_gntalloc/parameters/limit` in dom0.

**Comment by pixnion** [comment]
Ohhhh, nice. I doubled it from 1024 to 2048 and that allowed me to double the amount of currently running qvm-run spawned processes. Thanks! :)

**Comment by kocmo** [comment]
Unrelated, but may be also useful to people running into the dreaded ENOSPC "No space left on device" error - in my case it was due to BTRFS metadata block group running out of space, on Qubes 4.2.1 installed with BTRFS. Qubesd and other dom0 software started crashing with ENOSPC error, got the error in dom0 journal:

`dom0 kernel: BTRFS error (device dm-1): allocation failed flags 34, wanted 16384 tree-log 0, relocation: 0`

Resolved by:

`# btrfs fi resize -50G /`
`# btrfs balance start -dusage=30 -musage=10 -v /`
`# btrfs fi resize max /`

Added `btrfs balance start -dusage=30 -musage=10 -v /` command to /etc/cron.daily
