### ISSUE TITLE
R4.0rc4 mandb never gets run or was corrupted

### ISSUE THREAD

**Issue by u2482** [QubesOS/qubes-issues#3627]
#### Qubes OS version:

Qubes release 4.0 (R4.0)

R4.0rc4 

#### Affected component(s): 

dom0 apropos and whatis

---

### Steps to reproduce the behavior:

attempt to use apropos or whatis from the command line in dom0

### Expected behavior:

appropriate responses from apropos

### Actual behavior:

it can't find anything

### General notes:

It seems that mandb has never been run, or the database for whatis/apropos has been corrupted.  This issue is easily resolved by running mandb as root; some installer should have done this.

---

**Comment by esote** [comment]
@u2482 do you still have this issue on the full release? It may have been caused by a faulty update that a fresh stable install would fix.

**Comment by u2482** [comment]
Well, I have upgraded in place to 4.0.  Also, I figured out (before I wrote the bug report) how to fix the problem, and fixed it.  To prove whether the problem still exists (or not) I would have to reinstall.  I trust if you know where mandb is supposed to be run, you got it.
