### ISSUE TITLE
attaching usb device fails, usbip-host errors in sys-usb

### ISSUE THREAD

**Issue by maltesl** [QubesOS/qubes-issues#3628]
#### Qubes OS version:

Qubes release 4.0 (R4.0)
R4.0rc4
last updated this morning (2018-02-25) from testing

#### Affected component(s): 

qubes-usb-proxy (?)

---

### Steps to reproduce the behavior:

Try to attach a usb device (in my case a usb soundcard/wireless headphones):
`qvm-usb attach vm sys-usb:2-6`

### Expected behavior:

The device gets attached, gets recognized by pulseaudio etc. and can be used in the target vm.

### Actual behavior:

Device gets shown as attached in the widget, but not by qvm-usb.
qvm-usb shows no error message. 
There is an error message in sys-usb (output of `journalctl -f`):
>Feb 25 13:23:01 sys-usb kernel: usbip-host 2-6: CMD_SUBMIT: isoc invalid num packets 6
Feb 25 13:23:01 sys-usb kernel: usbip_core: unknown command
Feb 25 13:23:01 sys-usb kernel: usbip-host 2-6: recv invalid request
Feb 25 13:23:01 sys-usb kernel: usbip-host 2-6: stopped by a call to usb_kill_urb() because of cleaning up a virtual connection

the full output is:
> Feb 25 13:23:01 sys-usb audit[2699]: USER_AUTH pid=2699 uid=0 auid=4294967295 ses=4294967295 msg='op=PAM:authentication grantors=pam_rootok acct="root" exe="/usr/lib/qubes/qrexec-agent" hostname=? addr=? terminal=? res=success'
Feb 25 13:23:01 sys-usb qrexec-agent[491]: executed root:QUBESRPC qubes.USB+2-6 disp3297 pid 2699
Feb 25 13:23:01 sys-usb audit[2699]: CRED_ACQ pid=2699 uid=0 auid=4294967295 ses=4294967295 msg='op=PAM:setcred grantors=pam_rootok acct="root" exe="/usr/lib/qubes/qrexec-agent" hostname=? addr=? terminal=? res=success'
Feb 25 13:23:01 sys-usb systemd[1]: Started Session c7 of user root.
Feb 25 13:23:01 sys-usb qrexec-agent[2699]: pam_unix(qrexec:session): session opened for user root by (uid=0)
Feb 25 13:23:01 sys-usb audit[2699]: USER_START pid=2699 uid=0 auid=4294967295 ses=4294967295 msg='op=PAM:session_open grantors=pam_keyinit,pam_limits,pam_systemd,pam_unix,pam_lastlog acct="root" exe="/usr/lib/qubes/qrexec-agent" hostname=? addr=? terminal=? res=success'
Feb 25 13:23:01 sys-usb kernel: usbip-host 2-6: stub up
Feb 25 13:23:01 sys-usb kernel: usbip-host 2-6: usb_set_interface done: inf 1 alt 1
Feb 25 13:23:01 sys-usb kernel: usbip-host 2-6: usb_set_interface done: inf 1 alt 0
Feb 25 13:23:01 sys-usb kernel: usbip-host 2-6: usb_set_interface done: inf 2 alt 1
Feb 25 13:23:01 sys-usb kernel: usbip-host 2-6: usb_set_interface done: inf 2 alt 0
Feb 25 13:23:01 sys-usb kernel: usbip-host 2-6: endpoint 0 is stalled
Feb 25 13:23:01 sys-usb kernel: usbip-host 2-6: usb_set_interface done: inf 2 alt 1
Feb 25 13:23:01 sys-usb kernel: usbip-host 2-6: usb_set_interface done: inf 2 alt 0
Feb 25 13:23:01 sys-usb kernel: usbip-host 2-6: usb_set_interface done: inf 1 alt 1
Feb 25 13:23:01 sys-usb kernel: usbip-host 2-6: CMD_SUBMIT: isoc invalid num packets 6
Feb 25 13:23:01 sys-usb kernel: usbip_core: unknown command
Feb 25 13:23:01 sys-usb kernel: usbip-host 2-6: recv invalid request
Feb 25 13:23:01 sys-usb kernel: usbip-host 2-6: stopped by a call to usb_kill_urb() because of cleaning up a virtual connection
Feb 25 13:23:01 sys-usb qrexec-agent[491]: pid 2699 exited with -1
Feb 25 13:23:01 sys-usb qrexec-agent[491]: eintr
Feb 25 13:23:01 sys-usb kernel: usbip-host 2-6: reset full-speed USB device number 7 using xhci_hcd
Feb 25 13:23:02 sys-usb kernel: usbip-host 2-6: device reset
Feb 25 13:23:02 sys-usb qrexec-agent[2699]: pam_unix(qrexec:session): session closed for user root
Feb 25 13:23:02 sys-usb audit[2699]: USER_END pid=2699 uid=0 auid=4294967295 ses=4294967295 msg='op=PAM:session_close grantors=pam_keyinit,pam_limits,pam_systemd,pam_unix,pam_lastlog acct="root" exe="/usr/lib/qubes/qrexec-agent" hostname=? addr=? terminal=? res=success'
Feb 25 13:23:02 sys-usb audit[2699]: CRED_DISP pid=2699 uid=0 auid=4294967295 ses=4294967295 msg='op=PAM:setcred grantors=pam_rootok acct="root" exe="/usr/lib/qubes/qrexec-agent" hostname=? addr=? terminal=? res=success'

The messages in the target vm are:

> Feb 25 13:23:00 disp3297 qrexec-agent[491]: executed root:QUBESRPC qubes.USBAttach dom0 pid 2560
Feb 25 13:23:00 disp3297 audit[2560]: USER_AUTH pid=2560 uid=0 auid=4294967295 ses=4294967295 msg='op=PAM:authentication grantors=pam_rootok acct="root" exe="/usr/lib/qubes/qrexec-agent" hostname=? addr=? terminal=? res=success'
Feb 25 13:23:00 disp3297 audit[2560]: CRED_ACQ pid=2560 uid=0 auid=4294967295 ses=4294967295 msg='op=PAM:setcred grantors=pam_rootok acct="root" exe="/usr/lib/qubes/qrexec-agent" hostname=? addr=? terminal=? res=success'
Feb 25 13:23:00 disp3297 systemd[1]: Started Session c6 of user root.
Feb 25 13:23:00 disp3297 audit[2560]: USER_START pid=2560 uid=0 auid=4294967295 ses=4294967295 msg='op=PAM:session_open grantors=pam_keyinit,pam_limits,pam_systemd,pam_unix,pam_lastlog acct="root" exe="/usr/lib/qubes/qrexec-agent" hostname=? addr=? terminal=? res=success'
Feb 25 13:23:00 disp3297 qrexec-agent[2560]: pam_unix(qrexec:session): session opened for user root by (uid=0)
Feb 25 13:23:01 disp3297 kernel: vhci_hcd vhci_hcd.0: pdev(0) rhport(1) sockfd(0)
Feb 25 13:23:01 disp3297 kernel: vhci_hcd vhci_hcd.0: devid(131079) speed(2) speed_str(full-speed)
Feb 25 13:23:01 disp3297 kernel: vhci_hcd: vhci_device speed not set
Feb 25 13:23:01 disp3297 kernel: usb 1-2: new full-speed USB device number 4 using vhci_hcd
Feb 25 13:23:01 disp3297 kernel: vhci_hcd: vhci_device speed not set
Feb 25 13:23:01 disp3297 kernel: usb 1-2: SetAddress Request (4) to port 1
Feb 25 13:23:01 disp3297 kernel: usb 1-2: New USB device found, idVendor=046d, idProduct=0a1f
Feb 25 13:23:01 disp3297 kernel: usb 1-2: New USB device strings: Mfr=1, Product=2, SerialNumber=0
Feb 25 13:23:01 disp3297 kernel: usb 1-2: Product: Logitech G930 Headset
Feb 25 13:23:01 disp3297 kernel: usb 1-2: Manufacturer: Logitech
Feb 25 13:23:01 disp3297 kernel: input: Logitech Logitech G930 Headset as /devices/platform/vhci_hcd.0/usb1/1-2/1-2:1.3/0003:046D:0A1F.0002/input/input3
Feb 25 13:23:01 disp3297 kernel: hid-generic 0003:046D:0A1F.0002: input,hiddev96,hidraw0: USB HID v1.01 Device [Logitech Logitech G930 Headset] on usb-vhci_hcd.0-2/input3
Feb 25 13:23:01 disp3297 mtp-probe[2606]: checking bus 1, device 4: "/sys/devices/platform/vhci_hcd.0/usb1/1-2"
Feb 25 13:23:01 disp3297 mtp-probe[2606]: bus: 1, device: 4 was not an MTP device
Feb 25 13:23:01 disp3297 systemd[1]: Reached target Sound Card.
Feb 25 13:23:01 disp3297 kernel: vhci_hcd: connection closed
Feb 25 13:23:01 disp3297 kernel: vhci_hcd: stop threads
Feb 25 13:23:01 disp3297 kernel: vhci_hcd: release socket
Feb 25 13:23:01 disp3297 kernel: vhci_hcd: disconnect device
Feb 25 13:23:01 disp3297 kernel: usb 1-2: USB disconnect, device number 4
Feb 25 13:23:01 disp3297 pulseaudio[1750]: Failed to get card object.
Feb 25 13:23:01 disp3297 pulseaudio[1750]: Disabling timer-based scheduling because running inside a VM.
Feb 25 13:23:01 disp3297 systemd[1]: sound.target: Unit not needed anymore. Stopping.
Feb 25 13:23:01 disp3297 systemd[1]: Stopped target Sound Card.
Feb 25 13:23:01 disp3297 audit[2560]: USER_END pid=2560 uid=0 auid=4294967295 ses=4294967295 msg='op=PAM:session_close grantors=pam_keyinit,pam_limits,pam_systemd,pam_unix,pam_lastlog acct="root" exe="/usr/lib/qubes/qrexec-agent" hostname=? addr=? terminal=? res=success'
Feb 25 13:23:01 disp3297 audit[2560]: CRED_DISP pid=2560 uid=0 auid=4294967295 ses=4294967295 msg='op=PAM:setcred grantors=pam_rootok acct="root" exe="/usr/lib/qubes/qrexec-agent" hostname=? addr=? terminal=? res=success'
Feb 25 13:23:01 disp3297 qrexec-agent[2560]: pam_unix(qrexec:session): session closed for user root
Feb 25 13:23:01 disp3297 qrexec-agent[491]: send exit code 0
Feb 25 13:23:01 disp3297 qrexec-agent[491]: pid 2560 exited with 0
Feb 25 13:23:01 disp3297 qrexec-agent[491]: eintr

### General notes:

This worked perfectly out of the box since my first install of RC1 in September. An update a couple of weeks/months ago seems to have introduced this problem (unfortunately I don't remember anymore when it appeared precisely). 

Not all usb devices seem to have this problem, this one is the only one I tried that has it.

The problem appears to be the same for both debian and fedora templates. I tried both the current kernel (4.14.18-1) as well as 4.14.13-2. Unfortunately this is is the oldest of the three kernels currently installed, so I don't know how to test older ones should the kernel be where the problem is.

Sometimes it seems possible (by repeatedly executing the `qvm-usb attach` command until it hangs, then killing it and immediately executing another one - or something like that) to reach a state in which `qvm-usb` does list the device as attached and it is also listed in the target vm by `lsusb`, but leads to pulseaudio crashing / hanging, so I am not sure whether in that case the usb device is actually usable. This does not happen often, but happened twice yesterday while I was trying to debug this.

**Comment by marmarek** [comment]
Verify if you have the same kernel version in sys-usb and target VM. I think there were some major changes in USBIP (used by qvm-usb) between 4.9 and 4.14.

**Comment by maltesl** [comment]
I just tried this again after making sure `uname -a` reports both vms as running  `4.14.18-1.pvops.qubes.x86_64`, and the behavior is still the same. This is also the version running in dom0. I don't have any  pre-4.14 kernel installed anymore (is there an easy way to install older kernels then the three oldest that are retained?), so I can't check at the moment whether the update from 4.9 to 4.14 was the one that broke things.

**Comment by marmarek** [comment]
As for installing older kernels:
1. Increase `installonly_limit` in `/etc/dnf/dnf.conf`
2. Downgrade kernel-qubes-vm package: https://www.qubes-os.org/doc/software-update-dom0/#how-to-update-software-in-dom0

There are also some updates to USBIP in 4.15 kernel but doesn't look related to ` CMD_SUBMIT: isoc invalid num packets 6` error (at least not directly). So, I'd start with downgrading sys-usb kernel to 4.9.x

**Comment by aksiazek** [comment]
I hit the same issue with my wireless headphones and can confirm that a downgrade to 4.9 for sys-usb solved the issue for now

**Comment by manasb** [comment]
Found this issue while trying to figure out https://github.com/QubesOS/qubes-issues/issues/4103

I don't see a way to install the older 4.9 kernel, I am seeing the exact same messages in the logs for my `sys-usb` and VMs.

**Comment by manasb** [comment]
Found this issue while trying to figure out https://github.com/QubesOS/qubes-issues/issues/4103

I don't see a way to install the older 4.9 kernel, I am seeing the exact same messages in the logs for my `sys-usb` and VMs.

**Comment by manasb** [comment]
Tested today with `4.17.9`, no change.

**sys-usb**
```
Aug 11 14:32:20 localhost kernel: usbip-host 3-2: usbip-host: register new device (bus 3 dev 2)
Aug 11 14:32:20 localhost systemd[1]: sound.target: Unit not needed anymore. Stopping.
Aug 11 14:32:20 localhost systemd[1]: Stopped target Sound Card.
Aug 11 14:32:20 localhost kernel: usbip-host 3-2: stub up
Aug 11 14:32:21 localhost kernel: usbip-host 3-2: usb_set_interface done: inf 3 alt 1
Aug 11 14:32:21 localhost kernel: usbip-host 3-2: usb_set_interface done: inf 3 alt 2
Aug 11 14:32:21 localhost kernel: usbip-host 3-2: usb_set_interface done: inf 3 alt 0
Aug 11 14:32:21 localhost kernel: usbip-host 3-2: usb_set_interface done: inf 3 alt 1
Aug 11 14:32:21 localhost kernel: usbip-host 3-2: CMD_SUBMIT: isoc invalid num packets 6
Aug 11 14:32:21 localhost kernel: usbip_core: unknown command
Aug 11 14:32:21 localhost kernel: usbip-host 3-2: recv invalid request
Aug 11 14:32:21 localhost qrexec-agent[598]: pid 1284 exited with -1
Aug 11 14:32:21 localhost qrexec-agent[598]: eintr
```

**StandaloneVM - fedora28**
```
Aug 11 14:32:19 localhost kernel: vhci_hcd vhci_hcd.0: USB/IP Virtual Host Controller
Aug 11 14:32:19 localhost kernel: vhci_hcd vhci_hcd.0: new USB bus registered, assigned bus number 1
Aug 11 14:32:19 localhost kernel: vhci_hcd: created sysfs vhci_hcd.0
Aug 11 14:32:19 localhost kernel: usb usb1: New USB device found, idVendor=1d6b, idProduct=0002, bcdDevice= 4.17
Aug 11 14:32:19 localhost kernel: usb usb1: New USB device strings: Mfr=3, Product=2, SerialNumber=1
Aug 11 14:32:19 localhost kernel: usb usb1: Product: USB/IP Virtual Host Controller
Aug 11 14:32:19 localhost kernel: usb usb1: Manufacturer: Linux 4.17.9-1.pvops.qubes.x86_64 vhci_hcd
Aug 11 14:32:19 localhost kernel: usb usb1: SerialNumber: vhci_hcd.0
Aug 11 14:32:19 localhost kernel: hub 1-0:1.0: USB hub found
Aug 11 14:32:19 localhost kernel: hub 1-0:1.0: 8 ports detected
Aug 11 14:32:19 localhost kernel: vhci_hcd vhci_hcd.0: USB/IP Virtual Host Controller
Aug 11 14:32:19 localhost kernel: vhci_hcd vhci_hcd.0: new USB bus registered, assigned bus number 2
Aug 11 14:32:19 localhost kernel: usb usb2: We don't know the algorithms for LPM for this host, disabling LPM.
Aug 11 14:32:19 localhost kernel: usb usb2: New USB device found, idVendor=1d6b, idProduct=0003, bcdDevice= 4.17
Aug 11 14:32:19 localhost kernel: usb usb2: New USB device strings: Mfr=3, Product=2, SerialNumber=1
Aug 11 14:32:19 localhost kernel: usb usb2: Product: USB/IP Virtual Host Controller
Aug 11 14:32:19 localhost kernel: usb usb2: Manufacturer: Linux 4.17.9-1.pvops.qubes.x86_64 vhci_hcd
Aug 11 14:32:19 localhost kernel: usb usb2: SerialNumber: vhci_hcd.0
Aug 11 14:32:19 localhost kernel: hub 2-0:1.0: USB hub found
Aug 11 14:32:19 localhost kernel: hub 2-0:1.0: 8 ports detected
Aug 11 14:32:20 localhost kernel: vhci_hcd vhci_hcd.0: pdev(0) rhport(0) sockfd(0)
Aug 11 14:32:20 localhost kernel: vhci_hcd vhci_hcd.0: devid(196610) speed(2) speed_str(full-speed)
Aug 11 14:32:20 localhost kernel: vhci_hcd: vhci_device speed not set
Aug 11 14:32:20 localhost kernel: usb 1-1: new full-speed USB device number 2 using vhci_hcd
Aug 11 14:32:20 localhost kernel: vhci_hcd: vhci_device speed not set
Aug 11 14:32:20 localhost kernel: usb 1-1: SetAddress Request (2) to port 0
Aug 11 14:32:20 localhost kernel: usb 1-1: config 1 has an invalid interface number: 3 but max is 2
Aug 11 14:32:20 localhost kernel: usb 1-1: config 1 has an invalid interface number: 3 but max is 2
Aug 11 14:32:20 localhost kernel: usb 1-1: config 1 has an invalid interface number: 3 but max is 2
Aug 11 14:32:20 localhost kernel: usb 1-1: config 1 has no interface number 2
Aug 11 14:32:20 localhost kernel: usb 1-1: New USB device found, idVendor=262a, idProduct=100e, bcdDevice= 0.03
Aug 11 14:32:20 localhost kernel: usb 1-1: New USB device strings: Mfr=1, Product=2, SerialNumber=0
Aug 11 14:32:20 localhost kernel: usb 1-1: Product: FiiO USB DAC E17K
Aug 11 14:32:20 localhost kernel: usb 1-1: Manufacturer: FiiO 
Aug 11 14:32:20 localhost kernel: hid-generic 0003:262A:100E.0001: No inputs registered, leaving
Aug 11 14:32:20 localhost kernel: hid-generic 0003:262A:100E.0001: hidraw0: USB HID v1.00 Device [FiiO  FiiO USB DAC E17K] on usb-vhci_hcd.0-1/input0
Aug 11 14:32:20 localhost mtp-probe[1328]: checking bus 1, device 2: "/sys/devices/platform/vhci_hcd.0/usb1/1-1"
Aug 11 14:32:20 localhost mtp-probe[1328]: bus: 1, device: 2 was not an MTP device
Aug 11 14:32:20 localhost kernel: usbcore: registered new interface driver snd-usb-audio
Aug 11 14:32:20 localhost audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=alsa-state comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Aug 11 14:32:20 localhost systemd[1]: Started Manage Sound Card State (restore and store).
Aug 11 14:32:20 localhost systemd[1]: Reached target Sound Card.
Aug 11 14:32:20 localhost alsactl[1361]: alsactl 1.1.6 daemon started
Aug 11 14:32:20 localhost audit[1254]: USER_END pid=1254 uid=0 auid=4294967295 ses=4294967295 msg='op=PAM:session_close grantors=pam_keyinit,pam_limits,pam_systemd,pam_unix,pam_lastlog acct="root" exe="/usr/lib/qubes/qrexec-agent" hostname=? addr=? terminal=? res=success'
Aug 11 14:32:20 localhost audit[1254]: CRED_DISP pid=1254 uid=0 auid=4294967295 ses=4294967295 msg='op=PAM:setcred grantors=pam_rootok acct="root" exe="/usr/lib/qubes/qrexec-agent" hostname=? addr=? terminal=? res=success'
Aug 11 14:32:20 localhost qrexec-agent[529]: send exit code 0
Aug 11 14:32:20 localhost qrexec-agent[529]: pid 1254 exited with 0
Aug 11 14:32:20 localhost qrexec-agent[529]: eintr
Aug 11 14:32:20 localhost kernel: vhci_hcd: connection closed
Aug 11 14:32:20 localhost kernel: vhci_hcd: stop threads
Aug 11 14:32:20 localhost kernel: vhci_hcd: release socket
Aug 11 14:32:20 localhost kernel: vhci_hcd: disconnect device
Aug 11 14:32:20 localhost kernel: usb 1-1: USB disconnect, device number 2
Aug 11 14:32:20 localhost systemd[1]: Stopping User Manager for UID 0...
Aug 11 14:32:20 localhost systemd[1]: sound.target: Unit not needed anymore. Stopping.
Aug 11 14:32:20 localhost systemd[1]: Stopped target Sound Card.
```

**Comment by manasb** [comment]
My external USB audio device still does not work. I am on kernel `4.14.74-1.pvops.qubes.x86_64` in both my standalone Fedora 28 & `sys-usb` VMs. This bug (which was working just fine on R3.2), the annoying bug where modifier keys are detected by the system as being pressed when they are not (#4211) and the problems with using a USB-C or USB3 ethernet adapter are convincing me to replace Qubes with something else where I actually get to use all the capabilities of my laptop.

**Comment by maltesl** [comment]
I believe I have found the cause of this issue, it is a bug in the usbip driver in the Linux kernel. I submitted a [kernel patch](https://patchwork.kernel.org/patch/10899723/). Using qubes-builder to compile the kernel package (version 4.19.29-1) with my patch on top now solves the problem for me and the USB soundcard is usable again. I assume the best way to proceed with this issue is to wait for a fix (whether that will be the patch I submitted or another solution) to make it to the kernel upstream and then close once the fix arrived in Qubes(?).

**Comment by andrewdavidwong** [comment]
> I believe I have found the cause of this issue, it is a bug in the usbip driver in the Linux kernel. I submitted a [kernel patch](https://patchwork.kernel.org/patch/10899723/). Using qubes-builder to compile the kernel package (version 4.19.29-1) with my patch on top now solves the problem for me and the USB soundcard is usable again. I assume the best way to proceed with this issue is to wait for a fix (whether that will be the patch I submitted or another solution) to make it to the kernel upstream and then close once the fix arrived in Qubes(?).

Thank you! Since it's an upstream bug, and you've already submitted an upstream patch for it, we should close this issue now as `not our bug` so that no one mistakenly thinks that some action still needs to be taken on the Qubes side to fix this.

**Comment by marmarek** [comment]
@maltesl thanks for debugging this! Even though you're correct that this should go through upstream kernel process, please post an update here when this goes in. Also, I think it would be good to cc stable on this, as it is a bug fix.

**Comment by maltesl** [comment]
The fix has now been released upstream in the newest versions of the Linux kernel: 5.1, 5.0.14, 4.19.41, 4.14.117, and 4.9.174. I also submitted backports for 4.4 and 3.18 that are not in a released version yet, but I think Qubes only uses newer kernels, so as soon as the new releases arrive in the Qubes repos this issue should be fixed for everyone.

**Comment by maltesl** [comment]
I can confirm that the issue is now indeed resolved also in the Qubes stable repo (tried with the 4.19.43-1 kernel). :)
