### ISSUE TITLE
gnome-control-center crashes on fedora-26 template

### ISSUE THREAD

**Issue by rootkovska** [QubesOS/qubes-issues#3635]
With all the latest updates installed.

```
[user@fedora-26 ~]$ gnome-control-center 
libEGL warning: DRI2: failed to authenticate
libEGL warning: DRI2: failed to open swrast (search paths /usr/lib64/dri)
libEGL warning: DRI2: failed to authenticate
libEGL warning: DRI2: failed to open swrast (search paths /usr/lib64/dri)

(gnome-control-center:30621): GLib-CRITICAL **: g_strsplit: assertion 'string != NULL' failed
libEGL warning: DRI2: failed to authenticate
libEGL warning: DRI2: failed to open swrast (search paths /usr/lib64/dri)

(gnome-control-center:30621): GLib-CRITICAL **: g_strsplit: assertion 'string != NULL' failed

(gnome-control-center:30621): Clutter-CRITICAL **: Unable to initialize Clutter: Unable to initialize the Clutter backend: no available drivers found.
Segmentation fault (core dumped)
```

**Comment by marmarek** [comment]
Look like gnome-control-center Fedora package lack dependency it apparently require: `mesa-dri-drivers`. I'll add to template independently...

**Comment by marmarek** [comment]
@rootkovska unless you want to do full template reinstall, you need to install this package manually.

**Comment by rootkovska** [comment]
While at it, can you also make the git autocompletion work again in the fedora template? After switching to 4.0rc4 this stopped working for me in all my VMs.

**Comment by marmarek** [comment]
sudo dnf install bash-completion

**Comment by rootkovska** [comment]
Sure, but I meant: while fixing the default template (for rc5), let's also make sure this is instaled, as otherwise this is perceived as regression.

**Comment by marmarek** [comment]
I'm not so sure if we should ship everything that exists installed by default. fedora-26 template with similar package configuration set is *much* bigger than fedora-25, that's why number of installed packages were reduced. I'd focus on having GUI stuff working, console users will manage.

**Comment by marmarek** [comment]
(`bash-completion` is only 270k, so I'm not so much against it, just to keep the template size in mind)

**Comment by rootkovska** [comment]
I'd vote however for not introducing UX regressions compared to the default 3.2 template.
