### ISSUE TITLE
qubes.InputKeyboard prompt when resuming from sleep, but no external devices attached

### ISSUE THREAD

**Issue by mvermaes** [QubesOS/qubes-issues#3636]
#### Qubes OS version:

R3.2

#### Affected component(s): 

USB

---

### Steps to reproduce the behavior:

Suspend laptop, resume laptop, with no external keyboard attached.

### Expected behavior:

No system messages after resume from suspend.

### Actual behavior:

Dialog appears - _Do you allow domain "sys-usb" to execute qubes.InputKeyboard operation on the domain "dom0"?_

### General notes:

- Thinkpad x230
- `sys-usb` has all USB controllers assigned
- No custom policy settings
- From memory, this behaviour wasn't present in 3.1
- I think when I clean installed 3.2, it wasn't happening either, or at least was not happening consistently
- I think it started after either changing templates (was previously using various minimal/custom templates, now using the standard F26 one), or one of the Qubes/Xen updates. Sorry for not reporting the issue at the time I originally noticed it ...
- (_Edit to add:_ From clean boot, the issue seems not to appear, only following first suspend/resume)
- #3168 sounds like the same behaviour that I see, except for the dialog box text

---

#### Related issues:

#3168

**Comment by taradiddles** [comment]
I have the same problem: my laptop's integrated USB webcam is detected as a keyboard because it advertises (part of) itself as a HID. A workaround is to blacklist it by tweaking the udev rules in sys-usb's *template* (see #3604).
I'm on 4.0rc4 and you're on 3.2 so it seems the reason is a change/update in fedora. I haven't paid attention whether I have the pop up message at boot though

**Comment by mvermaes** [comment]
Thanks for the link, yes that sounds like the same thing I'm seeing. My camera is `5986:02d2 Acer, Inc`. I found another report [here](https://bugs.launchpad.net/ubuntu/+source/xserver-xorg-input-synaptics/+bug/1750110) which sounds similar as well.

I'm not that bothered by it anyway, but I agree with your suggestion in #3604 that it would be nice if there were some way to notify that it's the camera triggering this.

**Comment by andrewdavidwong** [comment]
> Same problem, but Qubes 4.0. (Does that qualify for a new issue?)

No, we generally only have one issue for the same problem across multiple Qubes versions.

**Comment by andrewdavidwong** [comment]
Is anyone still affected by this bug?

**Comment by mvermaes** [comment]
I'm not, but I haven't used the laptop that experienced the problem (or Qubes 3.2) since 4.0 was released.

**Comment by na--** [comment]
I have experienced it recently on 4.0, last week I think, but I can't check right now since I have other issues when I put my laptop to sleep... :sweat_smile:
