### ISSUE TITLE
Yubikey 4 and NEO / Encrypted emails 

### ISSUE THREAD

**Issue by ThierryIT** [QubesOS/qubes-issues#3638]
#### Qubes OS version:

4.rc4

#### Affected component(s): 

Yubikey 4 and NEO + Thunderbird + Enigmail

---

### Steps to reproduce the behavior:

1) attached the Yubikey to the targeted VM
2) send encrypted email
3) received email and decrypted it

### Expected behavior:

to decrypt: have to ask me the PIN number of my Yubikey not the passwd of my PGP user

### Actual behavior:

Ask me the passwd of my PGP user

### General notes:

If using the same key under Windows, I decrypt my encrypted emails with the PIN number of my Yubikey

---

**Comment by ThierryIT** [comment]
Be difficult, I do not have any other Linux available ...

**Comment by ThierryIT** [comment]
In firefox u2f is not activated by defaut, you have to "about:config" in the URL and switch "security.webauth.u2f to "True"

**Comment by marmarek** [comment]
Check this: https://wiki.debian.org/Smartcards/YubiKey4#OpenPGP

**Comment by esote** [comment]
@ThierryIT Do you still experience this / have you been able to test it on a non-Qubes machine? It is likely a non-Qubes issue.

**Comment by esote** [comment]
@andrewdavidwong Due to lack of response (& likely not our issue), should this issue be closed?

**Comment by andrewdavidwong** [comment]
Closing this for now due to the lack of response. If you revisit the matter in the future, or if anyone would like the issue to remain open, please leave a comment, and we'll be happy to reopen this. Thank you.
