### ISSUE TITLE
FirewallVMs don’t automatically reconnect when NetVM restarts

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#3642]
#### Qubes OS version:

R4.0

#### Affected component(s): 

Core Admin

---

### Steps to reproduce the behavior:

Reboot `sys-net`, then update the `netvm` pref as described in the docs.

### Expected behavior:

Other domains automatically reconnect to `sys-net`

### Actual behavior:

No automatic reconnection.

### General notes:

This forced me to reboot almost every AppVM.

---

**Comment by andrewdavidwong** [comment]
Possibly related: #3163, #1426

**Comment by marmarek** [comment]
Does it still happen @DemiMarie ?

**Comment by DemiMarie** [comment]
@marmarek It does not happen for me.  That said, I have not tested Windows HVMs.

**Comment by marmarek** [comment]
Windows HVMs seems to be out of scope for this issue (Windows cannot be a FirewallVM). If Windows indeed doesn't reconnect to its network-providing qube (which is likely...), I'd track it separately.
