### ISSUE TITLE
qubes-firewall service should policy only outgoing VM traffic

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#3644]
#### Qubes OS version:

R4.0

---

qubes-firewall service is designed to policy outgoing traffic from VMs. This is also the only part that can be configured in it (the traffic rules are assigned to source address). Currently it blocks any traffic not explicitly allowed by per-VM rules. This makes inter-VM networking harder to configure. Especially when the service use nftables instead of iptables.

**Comment by yonjah** [comment]
@marmarek is there any explanation on how to get inter-VM networking working in R4.0 ?
Documentation update seem to only apply for external communication and as much as I tried getting nftables configuration right I can only get pings going but nothing else

**Comment by marmarek** [comment]
https://www.qubes-os.org/doc/firewall/#enabling-networking-between-two-qubes should work (no need for manual nftables rules).
If you set restrictive firewall rules in qube settings (firewall tab), you need to also allow traffic there.
