### ISSUE TITLE
Thunderbird / send attachement(s) to VM doesn't work

### ISSUE THREAD

**Issue by taradiddles** [QubesOS/qubes-issues#3646]
#### Qubes OS version:

4.0rc4

#### Affected component(s): 

thunderbird-qubes in fedora-26 template

---

### Steps to reproduce the behavior:

Right click on an attachement and choose "Send to VM", or click on the "Send all to VM" button.

### Expected behavior:

Should popup a dialog to choose the destination VM.

### Actual behavior:

No popup dialog and no error shown when running thunderbird from a terminal.

### General notes:

This happens with the default fedora-26 template as well as a custom minimal one.

I don't remember if it was working with rc3.

Workaround: save file locally and use qvm-copy/move

---

**Comment by DTMW2** [comment]
I can confirm the bug. It first occured ca. 2-3 weeks ago after an update (without any other changes!) and is not limited to thunderbird but ALL "right-click-menus" in ALL VMs. e.g. in my fedora-26 office-vm "right click on a file" -> "copy/move to other AppVM" simply does nothing.

**Comment by taradiddles** [comment]
I just tried again and this time everything works (I've updated dom0 and my templates to current-testing a few times since my post).

That said I'm quite sure that I had updated everything to current-testing before creating the issue, but maybe the updates required a reboot.

Not closing the issue - waiting for @DTMW2's feedback

**Comment by DTMW2** [comment]
I just double checked (checked for updates available in dom0/testing -> no | checked for updates available in fedora-26 -> yes => installed | did NOT update my debian-8 | then did a complete system reboot).

the problem still exists in fedora-26 e.g. in "files" and in "thunderbird" and it exists in an unpatched debian-8 VM, too.

**Comment by taradiddles** [comment]
> updates available in fedora-26

Maybe you forgot to write 'testing' - if not you have to update the template too with updates in current-testing.

Other ideas:
- try to flush dnf's cache (dnf's `--refresh` option, or manually delete the appropriate files in /var/cache/dnf) ? The updates are already a few days ago so the cache's metadata should have expired but it may be worth a try.
- make sure that dom0 and your templates' date/time are OK because there was an issue with time synchronization some time ago ; it might cause dnf to assume the cache's metadata is still current

**Comment by DTMW2** [comment]
That did it! :-) Thanks for your further input! I forgot to include testing-repo. The copy dialog is fully functional.

**Comment by taradiddles** [comment]
cool !
closing the issue then.
