### ISSUE TITLE
HVM with cdrom option does not start unless 1024 MB of memory OR LOWER

### ISSUE THREAD

**Issue by Joeviocoe** [QubesOS/qubes-issues#3647]
#### Qubes OS version:
Qubes 4.0 rc4

#### Affected component(s): 
HVM qubes with CDROM livecd

### Steps to reproduce the behavior:

1. Download livecd (example: Tails 3.5 iso)
2. qvm-prefs hvm1 kernel ''
3. qvm-prefs hvm1 maxmem 2048
4. qvm-start hvm1 --cdrom=dom0:/home/user/tails.iso

### Expected behavior:
livecd boots as normal

### Actual behavior:
livecd does show grub boot selection menu... but crashes when attempting to boot.  No errors displayed on stderr of console.

### General notes:
Tails is just an easy to reproduce example, I cannot boot to other livecd iso files.  
If I lower the maxmem to 1024, it does boot as expected.... however, the performance is too slow to be usable.

---

**Comment by marmarek** [comment]
Unless you have Qubes-aware system inside, specially capable of reporting required memory, you need to set also `memory` property. Otherwise VM will use only that amount of memory even if maxmem is much larger.

**Comment by Joeviocoe** [comment]
Makes sense.
That did work, thank you.

P.S.
Is there any way to make a standaloneVM not based on a Template, more Qubes aware to the point I can at least attach USB devices without attaching the whole PCI USB controller?
I would like clipboard sharing and screen resolution too, if that is possible?
I run livecds and linux distros from iso files all the time, and cannot build templates out of them.

Thanks.

**Comment by marmarek** [comment]
> Is there any way to make a standaloneVM not based on a Template, more Qubes aware to the point I can at least attach USB devices without attaching the whole PCI USB controller?

You can try installing qubes-core-agent-qrexec and qubes-usb-proxy packages. rpm and deb are available on https://yum.qubes-os.org/r4.0/current/vm/ and https://yum.qubes-os.org/r4.0/current/vm/. But that's uncharted territory.


> I would like clipboard sharing and screen resolution too, if that is possible?

For that you'd need qubes-gui-agent package. Which ships own X server configuration and X session handling. Which is probably much more that you want.

**Comment by Joeviocoe** [comment]
I think I tried that with a base version of debian-8... and ran into dependency hell.  I was hoping it would be more like virtualbox that could run livecd with simple USB passthrough.  It could not do custom resolution, but it had Scaled Window mode that merely stretched to fit the monitor.  Is there any possibility for a Scaled mode in Qubes?

**Comment by marmarek** [comment]
> Is there any possibility for a Scaled mode in Qubes?

Unlikely to happen. Unless someone send a patch for https://github.com/QubesOS/qubes-gui-agent-xen-hvm-stubdom/.

**Comment by Joeviocoe** [comment]
Okay, thanks.
