### ISSUE TITLE
Broken gcc dependencies

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#3650]
#### Qubes OS version:

R4.0

---

### Steps to reproduce the behavior:

`sudo qubes-dom0-update --enablerepo=qubes*testing`

### Expected behavior:

Install updates, don't complain about dependencies.

### Actual behavior:

```
Dependencies resolved.
========================================================================================
 Package        Arch          Version                    Repository                Size
========================================================================================
Skipping packages with conflicts:
(add '--best --allowerasing' to command line to force their upgrade):
 cpp            x86_64        6.4.1-1.qubes1.fc25        qubes-dom0-cached        9.0 M
 libgomp        x86_64        6.4.1-1.qubes1.fc25        qubes-dom0-cached        197 k

Transaction Summary
========================================================================================
Skip  2 Packages
```

### General notes:

This is continuation of discussion [here](https://github.com/QubesOS/qubes-vmm-xen/pull/32) and [here](https://groups.google.com/d/msg/qubes-devel/DVt50QJrijI/h2lvqUQOAQAJ)

Since the problem applies not only to qubes-builder (where we can employ some workarounds), we need a better solution.

**Comment by marmarek** [comment]
@HW42 What about building i686 gcc? Can we cross compile it using the same environment, from the same repository/spec? Do you know how upstream handle it?

**Comment by HW42** [comment]
> @HW42 What about building i686 gcc? Can we cross compile it using the same environment, from the same repository/spec?

A simple `setarch i686 rpmbuild --target=i686` failed with errors in some headers. But maybe just some missing dependencies.

> Do you know how upstream handle it?

I guess they just have real i686 builders (probably running ob x86_64 capable hardware).

Anyway I looked at the libgcc content:

    --- libgcc-6.4.1-1.fc25.x86_64
    +++ libgcc-6.4.1-1.qubes1.fc25.x86_64
    ├── lib64
    │ ├── libgcc_s-6.4.1-20170727.so.1
    │ │ ├── readelf --wide --notes {}
    │ │ │ @@ -1,11 +1,11 @@
    │ │ │  
    │ │ │  Displaying notes found in: .note.gnu.build-id
    │ │ │    Owner                 Data size	Description
    │ │ │ -  GNU                  0x00000014	NT_GNU_BUILD_ID (unique build ID bitstring)	    Build ID: 4523a29e2c5d4c4ae5cc4ffec27ad8c7cfce310b
    │ │ │ +  GNU                  0x00000014	NT_GNU_BUILD_ID (unique build ID bitstring)	    Build ID: 16703f6d2d70b618fc62894c76ed4ec8d396be0d
    │ │ │  
    │ │ │  Displaying notes found in: .note.stapsdt
    │ │ │    Owner                 Data size	Description
    │ │ │    stapsdt              0x00000034	NT_STAPSDT (SystemTap probe descriptors)	    Provider: libgcc
    │ │ │      Name: unwind
    │ │ │      Location: 0x0000000000010190, Base: 0x0000000000013354, Semaphore: 0x0000000000000000
    │ │ │      Arguments: 8@%rdi 8@%rsi
    │ │ ├── readelf --wide --decompress --hex-dump=.gnu_debuglink {}
    │ │ │ @@ -1,6 +1,6 @@
    │ │ │  
    │ │ │  Hex dump of section '.gnu_debuglink':
    │ │ │    0x00000000 6c696267 63635f73 2d362e34 2e312d32 libgcc_s-6.4.1-2
    │ │ │    0x00000010 30313730 3732372e 736f2e31 2e646562 0170727.so.1.deb
    │ │ │ -  0x00000020 75670000 327915fb                   ug..2y..
    │ │ │ +  0x00000020 75670000 8baf39f8                   ug....9.

No content change. So we can just use Fedora's libgcc and be done with it. See PR QubesOS/qubes-gcc#1. We can reconsider building for i686 should the need arise for other reasons.

**Comment by marmarek** [comment]
Ok, that worked. There is still "broken" `libgcc-6.4.1-1.qubes1.fc25.x86_64` package in testing repository, but can be safely ignored since nothing depends on it. I'll remove it from there.

**Comment by awokd** [comment]
@andrewdavidwong / @marmarek Please reopen; based on testing described further in https://github.com/QubesOS/qubes-issues/issues/3707 and a couple mailing list comments this does not appear to be resolved in qubes-builder although I see https://github.com/QubesOS/updates-status/issues/442 is in stable.

Did a `git pull` in qubes-builder, followed by `make dist-clean` and rerunning `./setup`. After many hours of gcc building, this is the output:
```
make[1]: Entering directory '/home/user/qubes-builder'
sudo chroot /home/user/qubes-builder/chroot-fc25 dnf install -y gcc-6.4.1-1.qubes1.fc25.x86_64 libgcc.x86_64
Qubes OS Builder Repository                      19 kB/s | 257  B     00:00    
No package gcc-6.4.1-1.qubes1.fc25.x86_64 available.
Package libgcc-6.4.1-1.fc25.x86_64 is already installed, skipping.
Error: Unable to find a match.
make[1]: *** [qubes-src/vmm-xen/Makefile.builder:27: workaround-gcc-upgrade-fc25] Error 1
make[1]: Leaving directory '/home/user/qubes-builder'
make: *** [Makefile:224: vmm-xen-dom0] Error 1
```

**Comment by awokd** [comment]
Verified my `qubes-src/gcc/gcc.spec` appears to have both commits applied:
```
Summary: Various compilers (C, C++, Objective-C, Java, ...)
Name: gcc
Version: %{gcc_version}
Release: %{gcc_release}.qubes2%{?dist}
%global release_non_qubes %{gcc_release}%{?dist}
# libgcc, libgfortran, libgomp, libstdc++ and crtstuff have
# GCC Runtime Exception.
```

**Comment by marmarek** [comment]
Looks like https://github.com/QubesOS/qubes-vmm-xen/commit/b79f692a2da10856f01c68eefbecbf5b1bcf8820 needs to be reverted. @awokd can you test it?

**Comment by awokd** [comment]
Yes, definitely. Is there a faster way that doesn't involve the 12 hour GCC rebuild?

**Comment by marmarek** [comment]
You don't need to rebuild gcc, just xen.

**Comment by awokd** [comment]
Backed out https://github.com/QubesOS/qubes-vmm-xen/commit/b79f692a2da10856f01c68eefbecbf5b1bcf8820 by hand, and `make vmm-xen` is now building instead of failing immediately. I'll kick off a full `make qubes` after this completes to make sure the rest of the process is good too, but that was probably it. Thanks!

**Comment by awokd** [comment]
Build and ISO completed successfully. Needed to specify `WHONIX_TBB_VERSION` as current is newer than template's default setting- will document separately.

**Comment by marmarek** [comment]
Thanks!

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?
