### ISSUE TITLE
XScreenSaver prompt states: "This version of XScreenSaver is very old! Please upgrade!"

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#3652]
#### Qubes OS version:

`R3.2`

#### Affected component(s): 

XScreenSaver in dom0

---

### Steps to reproduce the behavior:

Lock the screen using XScreenSaver (the default screen locker) in dom0, then move the cursor or press any key.

### Expected behavior:

The normal XScreenSaver prompt is displayed.

### Actual behavior:

The XScreenSaver prompt states:

```
This version of XScreenSaver
is very old! Please upgrade!
```

### General notes:

With all normally available updates applied, the version of XScreenSaver is 5.36.

 - **Security:** It is possible that there are security issues fixed in newer versions of XScreenSaver. By staying on an old version, Qubes 3.2 could be vulnerable to such issues.
 - **UX:** This is probably a byproduct of the fact that dom0 in Qubes 3.2 uses Fedora 23, which has reached EOL. [Normally, this is not a security concern.](https://www.qubes-os.org/doc/supported-versions/#note-on-dom0-and-eol) Nonetheless, some users may be confused by the XScreenSaver message or suspect that the Qubes update mechanism is not functioning properly. In addition, the fact that this occurs on Qubes 3.2 but not on Linux distributions that use XScreenSaver (and in which it is updated normally) could be perceived as a shortcoming of  Qubes 3.2.

---

#### Related issues:

#1917

**Comment by marmarek** [comment]
Related discussion about similar problem in Debian stable: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=819703
But it does not directly apply to us, because xscreensaver isn't one of few packages we backport fixes for.

**Comment by unman** [comment]
I dont believe there are any security issues fixed in newer versions, so it's simply a cosmetic issue.

**Comment by Polygonbugs** [comment]
I'm experiencing this also.

**Comment by blissjoe** [comment]
I started getting this message in Qubes R4.0 today. 

XScreenSaver - 5.37

**Comment by fepitre** [comment]
Upstream package available in repos for Qubes 3.2 and 4.0.

**Comment by DemiMarie** [comment]
Confirmed

**Comment by fepitre** [comment]
As we have our own fork, maybe we can drop this code part?

**Comment by marmarek** [comment]
Yes, already here: https://github.com/QubesOS/qubes-xscreensaver/pull/4
I've included Debian patch fixing this arrogance.

**Comment by ninavizz** [comment]
Looking forward to QScreenSaver eventually existing. For so many reasons. This one, now, too. :)

**Comment by unman** [comment]
On Wed, Mar 31, 2021 at 08:32:01PM -0700, Nina Eleanor Alter wrote:
> Looking forward to QScreenSaver eventually existing. For so many reasons. This one, now, too. :)
> 

I'm waiting for a green light from someone.
I haven't yet seen any approval that we go this route.

**Comment by mfc** [comment]
this can be closed for now yes? and we can re-open if/when happens again
