### ISSUE TITLE
Missing icon for Visual Studio Code

### ISSUE THREAD

**Issue by SaswatPadhi** [QubesOS/qubes-issues#3653]
#### Qubes OS version:
`Qubes release 4.0 (R4.0)`

#### Affected component(s): 
Applications Icons in dom0

---

### Steps to reproduce the behavior:
1. Install Qubes 4.0~rc4
2. [Install VS Code on a Fedora 26 AppVM](https://code.visualstudio.com/docs/setup/linux#_rhel-fedora-and-centos-based-distributions)
3. Sync applications with dom0

### Expected behavior:
Appropriate tinted icon for VS Code should be added to the applications menu.

### Actual behavior:
A generic icon for the color associated with the AppVM is added to the applications menu.
However, the application link works fine.

### General notes:
The icon is located in `/usr/share/pixmaps/code.png` within the AppVM.

**Comment by marmarek** [comment]
Yes, should be in dom0's journalctl.

**Comment by SaswatPadhi** [comment]
I checked the `journalctl`. It complains "Image format violation".

[The source](https://github.com/QubesOS/qubes-linux-utils/blob/f42951578ae555143aba33013068799f5bdd53f7/imgconverter/qubesimgconverter/__init__.py#L196) reveals that this is raised when the image header is cannot be trusted. I am not sure why this is the case though. Everything looks normal on running `identify code-insiders.png`. I have attached the png file:

![code-insiders](https://user-images.githubusercontent.com/1577944/37195935-a76c6802-2329-11e8-94b7-560bc2f93d6f.png)

SHA256(code-insiders.png) = bedcade2c4d05f4a976f7ae9e85cfe31acabd97f223acf67b9a6c5126382349f

**Comment by marmarek** [comment]
Not sure why exactly you get this error (instead of "Image size constraint violation"), but the icon is 1024x1024, but maximum allowed by that code is 512x512.

**Comment by SaswatPadhi** [comment]
I see, thanks.

Can we update the code to use 1024 x 1024?
I think VS Code (and several other apps) use 1024 size for very high DPI (retina display like) devices.

**Comment by esote** [comment]
@marmarek You recently updated `qubes-linux-utils/imgconverter/qubesimgconverter` to [allow 2048x2048 icons](https://github.com/QubesOS/qubes-linux-utils/commit/4bfd10baaaf54b3d4126d9cce8127fae30b9d690). Is this related?

**Comment by marmarek** [comment]
Yes, it should be fixed with https://github.com/QubesOS/updates-status/issues/754 (already in stable)
