### ISSUE TITLE
Create new appvm does not update Qube Manager

### ISSUE THREAD

**Issue by holiman** [QubesOS/qubes-issues#3658]
#### Qubes OS version:

Qubes releaes 4.0 (R4.0)

#### Affected component(s): 

Qube Manager

---

### Steps to reproduce the behavior:

1. Open Qube manager
2. Create an AppVm, either via gui or via ` qvm-create --template debian-9 --label yellow debian-work`
3. Hit "refresh qube list" button in UI

### Expected behavior:

That the new qube shows up in the manager

### Actual behavior:

The qube does not show up, until the manager is restarted

### General notes:

---

**Comment by marmarta** [comment]
I know that bug! It should have been fixed by https://github.com/QubesOS/qubes-manager/pull/65 ; it looks like it was already merged, so maybe try updating?

**Comment by holiman** [comment]
Yes, I can confirm that it works after updating. Good work!
