### ISSUE TITLE
Qubes firewall - allowing temporary access causes python error

### ISSUE THREAD

**Issue by mirrorway** [QubesOS/qubes-issues#3661]
#### Qubes OS version:

R4.0 rc4, current-testing

#### Affected component(s): 

GUI firewall

### Steps to reproduce the behavior:

1. Create a VM with netvm := sys-firewall
2. Limit outgoing connections, click okay.
3. Allow full access for 5 mins

This affects existing VMs too.

### Expected behavior:

Allows temporary net access.

### Actual behavior:

ERROR: Firewall tab: Got empty response from qubesd. See journalctl in dom0 for details.

journalctl:
```
Mar 05 14:53:39 dom0 qubesd[15392]: unhandled exception while calling src=b'dom0' meth=b'admin.vm.firewall.Set' dest=b'test2' arg=b'' len(untrusted_payload)=101
Mar 05 14:53:39 dom0 qubesd[15392]: Traceback (most recent call last):
Mar 05 14:53:39 dom0 qubesd[15392]:   File "/usr/lib/python3.5/site-packages/qubes/api/__init__.py", line 262, in respond
Mar 05 14:53:39 dom0 qubesd[15392]:     untrusted_payload=untrusted_payload)
Mar 05 14:53:39 dom0 qubesd[15392]:   File "/usr/lib64/python3.5/asyncio/futures.py", line 381, in __iter__
Mar 05 14:53:39 dom0 qubesd[15392]:     yield self  # This tells Task to wait for completion.
Mar 05 14:53:39 dom0 qubesd[15392]:   File "/usr/lib64/python3.5/asyncio/tasks.py", line 310, in _wakeup
Mar 05 14:53:39 dom0 qubesd[15392]:     future.result()
Mar 05 14:53:39 dom0 qubesd[15392]:   File "/usr/lib64/python3.5/asyncio/futures.py", line 294, in result
Mar 05 14:53:39 dom0 qubesd[15392]:     raise self._exception
Mar 05 14:53:39 dom0 qubesd[15392]:   File "/usr/lib64/python3.5/asyncio/tasks.py", line 240, in _step
Mar 05 14:53:39 dom0 qubesd[15392]:     result = coro.send(None)
Mar 05 14:53:39 dom0 qubesd[15392]:   File "/usr/lib64/python3.5/asyncio/coroutines.py", line 210, in coro
Mar 05 14:53:39 dom0 qubesd[15392]:     res = func(*args, **kw)
Mar 05 14:53:39 dom0 qubesd[15392]:   File "/usr/lib/python3.5/site-packages/qubes/api/admin.py", line 1265, in vm_firewall_set
Mar 05 14:53:39 dom0 qubesd[15392]:     self.dest.firewall.save()
Mar 05 14:53:39 dom0 qubesd[15392]:   File "/usr/lib/python3.5/site-packages/qubes/firewall.py", line 570, in save
Mar 05 14:53:39 dom0 qubesd[15392]:     nearest_expire:
Mar 05 14:53:39 dom0 qubesd[15392]: TypeError: unorderable types: datetime.datetime() < bool()
```

**Comment by donob4n** [comment]
I think I have this fixed but doing it I discovered a problem with https://github.com/QubesOS/qubes-core-admin/blob/a8784df349910c2f3acf503207084a663c30e400/qubes/firewall.py#L204-L207
and https://github.com/QubesOS/qubes-manager/blob/819f2f45d47899f1f89cbef63f3c5dc42a1ff9bc/qubesmanager/firewall.py#L338

The datetime is not properly restored and I personally have a 5h diff. I tried even calling utcfromtimestamp() in qubes-manager itself and the time was wrong.

I'm gonna test without UTC.

**Comment by donob4n** [comment]
Now the call_later() works fine but this comparison fails https://github.com/QubesOS/qubes-core-admin/blob/a8784df349910c2f3acf503207084a663c30e400/qubes/firewall.py#L551

Could you check @marmarek ?

**Comment by pgporada** [comment]
This just happened to me after the latest round of Qube updates.

**Comment by unman** [comment]
Confirmed in rc5

**Comment by tlaurion** [comment]
I confirm this bug is still present in Qubes 4 release fully updated to current, and fixed by upgrading to qubes-dom0-current-testing. This greatly impact installation of other package repos, importing keys and user experience.

@marmarek : Maybe that fix should be pushed into current repo?

**Comment by marmarek** [comment]
> @marmarek : That fix should be pushed into current repo!

Yes, it will be, after making sure it really didn't introduce any regression in any supported configuration.
