### ISSUE TITLE
`qubes-firewall.service` fails on `fedora-26-minimal` fails because of bad `qubes-core-agent` version

### ISSUE THREAD

**Issue by SaswatPadhi** [QubesOS/qubes-issues#3663]
#### Qubes OS version:
Qubes release 4.0 (R4.0)

#### Affected component(s): 
Firewall service (qubes-core-agent) on fedora-26-minimal

---

### Steps to reproduce the behavior:
1. Install fedora-26-minimal template
2. `dnf update` the template
3. Install dependencies for a NetVM
4. Use it as TemplateVM for sys-firwall
5. Restart sys-firewall
6. Run within sys-firewall: `journalctl -u qubes-firewall.service -b`

### Expected behavior:
No errors in journal -- Qubes firewall updater runs without issues.

### Actual behavior:
```log
Mar 07 00:38:31 sys-firewall systemd[1]: Started Qubes firewall updater.
Mar 07 00:38:32 sys-firewall qubes-firewall[457]: Traceback (most recent call last):
Mar 07 00:38:32 sys-firewall qubes-firewall[457]:   File "/usr/sbin/qubes-firewall", line 6, in <module>
.
. . . <truncated> . . .
.
Mar 07 00:38:32 sys-firewall qubes-firewall[457]: pkg_resources.DistributionNotFound: The 'qubesagent==4.0.20' distribution was not found and is required by the application
Mar 07 00:38:32 sys-firewall systemd[1]: qubes-firewall.service: Main process exited, code=exited, status=1/FAILURE
```

### General notes:
This issue does not arise on Fedora 26 image which has 4.0.20 version of `qubes-core-agent`. But Fedora 26 Minimal image has 4.0.24.

**Comment by esote** [comment]
@SaswatPadhi Do you still experience this with Fedora 28? The packages involved have very likely been updated.

**Comment by SaswatPadhi** [comment]
No, things work as expected on Fedora 28 and Fedora 28 Minimal.

Thanks.
