### ISSUE TITLE
DNS error for non-template standalone VMs

### ISSUE THREAD

**Issue by 0pcom** [QubesOS/qubes-issues#3669]
#### Qubes OS version:

4.0-rc4

#### Affected component(s): 

non-template standalone VMs
networking

---

### Steps to correct the behavior:

After I successfully configured networking on 3.2 I attempted to replicate the configuration in 4.0-rc4 following the same procedure outlined in the documentation.

### Expected behavior:

The network configuration should be the same as it was for the previous version <i>unless otherwise noted in the documentation</i>

Internet in non template based standalone VMs should not generate DNS errors

### Actual behavior:

I was able to connect to my router's management page, but any web address or search query returns a DNS error and suggests checking DNS, proxy, and firewall settings

### General notes:

not a crippling issue, the solution is close but elusive

---

#### Related issues:

Not directly related but in the same general direction
in addition to the aformentioned difference in 4.0-rc4 vs 3.2
making non-template-based VMs work is also different.

I cannot seem to boot anything from domain dom0
Can't boot from block devices (in dom0)
can't boot from CD (dom0:/dev/sr0)
can't boot from an .iso on another harddisk (from dom0)

It's hard to believe this is intentional though according to the documentation,
booting VMs from dom0 is discouraged. It was possible with 3.2.
Even with 3.2 there were caveats of some nontemplate-based standalone VMs wanted to boot in certain ways and not in other ways. If I can document this more I will add an issue but I haven't thoroughly checked if this has been reported or not.

**Comment by andrewdavidwong** [comment]
Resolved in https://github.com/QubesOS/qubes-issues/issues/3857#issuecomment-384445718
