### ISSUE TITLE
Attaching a USB device to a AppVM fails silently

### ISSUE THREAD

**Issue by juniorz** [QubesOS/qubes-issues#3672]
#### Qubes OS version:

R4.0

#### Affected component(s): 

---

### Steps to reproduce the behavior:

1. Create a AppVM withouth `qubes-usb-proxy`
2. Start the AppVM
3. Connect a USB device
4. Use the "[domains widget](https://github.com/QubesOS/qubes-issues/issues/2132#issuecomment-319470107
)" to attach the USB device to the AppVM.

### Expected behavior:

There should be an error message saying that `qubes-usb-proxy` is not installed on the target AppVM.
Ideally, there would be an actionable message that could be used to install `qubes-usb-proxy` if the user wants to.

### Actual behavior:

The operation fails silently.

### General notes:

 

---

**Comment by awokd** [comment]
Might be a regression of https://github.com/QubesOS/qubes-issues/issues/3525#issuecomment-362931558
