### ISSUE TITLE
Qubes Manager - does not reflect changes in qube properties

### ISSUE THREAD

**Issue by unman** [QubesOS/qubes-issues#3675]
#### Qubes OS version:

4.0rc5

#### Affected component(s): 

Qubes Manager

---

### Steps to reproduce the behavior:

Change label , netvm or other properties.

### Expected behavior:

Manager will reflect change

### Actual behavior:

No change

### General notes:

I understand the reason for this, (no longer synchronous change to minimise problems that 3.2 version had), but want to capture this. 

---

#### Related issues:

#3572

**Comment by u2482** [comment]
I came here to mention this too.
More significantly, State doesn't change; whether it is running or updates are available.
The fields get updated if you select a qube and move off it.

**Comment by andrewdavidwong** [comment]
Reopening due to apparent regression reported in #4622.

**Comment by andrewdavidwong** [comment]
Reopening due to apparent regression reported in #5587.

**Comment by marmarta** [comment]
I'm unable to reproduce. Updating label was fixed in https://github.com/QubesOS/qubes-manager/commit/3cf9ff3ee2b2c3336e186d697b2fc81e200a460b and VM class cannot be changed.
