### ISSUE TITLE
No "Exit" on Qube Manager (i3wm)

### ISSUE THREAD

**Issue by holiman** [QubesOS/qubes-issues#3683]
### Qubes OS version:

4.0 (R4.0)

### Affected component(s): 

Qube Manager

---

### Steps to reproduce the behavior:

1. Start Qube Manager
2. Attempt to quit with the usual suspects: ctrl-c, ctrl-q, ctrl-w, shift-ctrl-q
3. Attempt to find 'Exit' via menus
4. Give up and quit using i3, `mod-shift-q`

### Expected behavior:

There is an "Exit" in the menu, also mapped to ctrl-q

### General notes:

I'm using i3wm, perhaps this is not a problem for regular users. 

---

**Comment by marmarek** [comment]
Previously the exit action was available from its tray icon (which is gone in 4.0).
