### ISSUE TITLE
MMU enabled in BIOS but not active in Q4 rc5

### ISSUE THREAD

**Issue by decnet** [QubesOS/qubes-issues#3684]
### Qubes OS version:

Qubes Release 4.0 (R4.0)

### Affected component(s): 

core

---

### Steps to reproduce the behavior:

`qvm-start sys-net`

### Expected behavior:

IOMMU should be enabled and the VMs should start without error. 

### Actual behavior:

When I start any non-template VM I get the following error:

`start failed: internal error: libxenlight failed to create new domain 'sys-net', see /var/log/libvirt/libxl-driver.log for details`

and in var/log/libvirt/libxl-driver.log for details
`...libxl__device_pci_add: PCI device 0000:00:19.0 cannot be assigned - no IOMMU?
...libxl__add_pcidevs: libxl_device_pci_add failed -1
...libxlcreate_attach_devices: unable to add pci devices`

### General notes:

MMU is enabled in the BIOS, however is shown as "not active" when I run qubes-hcl-report. I've been running Q3.2 for ages with no problems, but i've not attempted to run any previous 4.0 release candidates. Its a lenovo x230.

---

**Comment by marmarek** [comment]
Qubes 3.2 did not strictly required IOMMU (but it improved security there), now it is strictly required. So it's possible it didn't worked there either.
Anyway, I suspect there is some hardware related issue. You may need to update BIOS.
See `xl dmesg` output for details.

**Comment by decnet** [comment]
Updated BIOS to 2.70 and now it works. Thanks for your help!
