### ISSUE TITLE
Installer should detect SSD drive presence and set lvm issue_discards=1 config option itself

### ISSUE THREAD

**Issue by tlaurion** [QubesOS/qubes-issues#3686]
### Qubes OS version:

R3.2, R4.0

### Affected component(s): 

dom0

---

### Steps to reproduce the behavior:

Use Qubes intenseively. lvm_thin will use too much space compared to what is actually used on disk.

### Expected behavior:

Disk space should be related to what is actually used.
[Documentation specifies what should be done by user](https://github.com/QubesOS/qubes-doc/commit/f74759eede77b8503a03d3ea24b5a46dafa18307#diff-5bd980a25b2b51279cbab961bdd79eb3R62). It should be the installer's job to set the configuration option instead.

### Actual behavior:

Disk space is filled until all disks are remounted RO.

### General notes:

[Documentation specifies what should be done by user](https://github.com/QubesOS/qubes-doc/commit/f74759eede77b8503a03d3ea24b5a46dafa18307#diff-5bd980a25b2b51279cbab961bdd79eb3R62). It should be the installer's job to set the configuration option instead.

---

**Comment by marmarek** [comment]
lvm.conf `issue_discards=1` settings is relevant for SSD wear leveling, but not really for free space on lvm_thin. As noted in the documentation, all parts required for lvm_thin space calculation are already done by Qubes 4.0 installer (some fixes are part only of 4.0rc5, so if you have older version, you may need to enable `fstrim.timer` manually).
On 3.2 LVM thin volumes are not used (and even if you install with lvm_thin, all VMs are in dom0 filesystem as files), so this is not really needed. Unless you heavily customize storage layer manually.

The thing that is not done automatically, is passing this down to SSD disk. Doing this might help with some attacks on LUKS layer (reveal data layout, but not really data itself). See the article linked in the [documentation](https://www.qubes-os.org/doc/disk-trim/). So, this is a trade-off between security and SSD life time. We choose to have safer default.

**Comment by awokd** [comment]
Should we downgrade the "is recommended if using an SSD" to something like "you may wish to [...] if using an SSD"?

**Comment by andrewdavidwong** [comment]
> Should we downgrade the "is recommended if using an SSD" to something like "you may wish to [...] if using an SSD"?

This sounds like the right approach, but Marek's point should be made explicit. ("So, this is a trade-off between security and SSD life time. We choose to have safer default.") It sounds like the installer is choosing the safer default, while the documentation is currently advising the user to opt for a less-safe configuration. Not good!

**Comment by awokd** [comment]
> less-safe

I think it's splitting hairs to an extent, but will refer back to that linked article in my edit.

**Comment by marmarek** [comment]
It really depends on the threat model. My understanding is, based on the information revealed by the TRIM/DISCARD operation you can get used/free space. In practice, you can get from this a number and sizes of VMs (if you're lucky, because of blocks allocation by LVM thin/dom0 filesystem). Some don't consider this information to be sensitive, to the extend of publishing it explicitly: https://blog.invisiblethings.org/2011/03/13/partitioning-my-digital-life-into.html

But yes, changing "recommended" to "you may want" is a good idea.

**Comment by andrewdavidwong** [comment]
Are you sure this isn't necessary for freeing up space according to the Qubes Disk Space Monitor? I noticed that my disk usage (according to that widget) kept creeping up even though I was deleting large files inside AppVMs. Then I set `issue_discards = 1`, and it dropped by ~20 percentage points.

**Comment by tlaurion** [comment]
@marmarek : I confirm the problem is fixed only when all levels are fixed.

**Comment by tlaurion** [comment]
@marmarek: Maybe it is time to propose advanced/dynamic salt configuration options at install time?
https://github.com/SkypLabs/my-qubes-os-formula/issues

**Comment by tlaurion** [comment]
@marmarek: Bump

**Comment by marmarek** [comment]
Can anyone still replicate this? In the meantime an explicit `blkdiscard` call was added as part of #5077.
