### ISSUE TITLE
`default_dispvm` global default value

### ISSUE THREAD

**Issue by modulistic** [QubesOS/qubes-issues#3688]
### Qubes OS version:

Qubes release 4.0 (R4.0)
Up to date as of 2018-03-10 with repo `qubes-dom0-current-testing`

### Affected component(s): 

* `/var/lib/qubes/qubes.xml`
* `qvm-prefs`

---

### Steps to reproduce the behavior:

* `qvm-remove fedora-25-dvm`

### Expected behavior:

* qube `fedora-25-dvm` should be gone

### Actual behavior:

* qube `fedora-25-dvm` is not gone
* message in `/var/log/qubes/qubes.log`:
  `Cannot remove fedora-25-dvm, used by Qubes.default_dispvm`

### General notes:

* I am trying to get rid of the old qube `fedora-25-dvm` in favor of my new one `fedora-26-dvm`
* Everything works fine, I just want to get rid of the old one and reclaim the used harddisk space
* I could replace the default_dispvm pref from all my qubes, wifh `qvm-prefs XXX default_dispvm fedora-26-dvm`
* `Qubes` is not and hasn't been the name of any of any qube in my machine: it's something made up by `qvm-prefs` or its dependencies
* The structure of /var/lib/qubes/qubes.xml is like this;
```
<qubes>
  <labels>...</labels>
  <pools>...</pools>
  <properties>
    ...
    <property name="default_dispvm">fedora-25-dvm</property><!-- this is the problem, I guess -->
   ...
  <domains>
    <domain id="..." class="...">
      <properties>
        ...
        <property name="default_dispvm">fedora-26-dvm</property>
        ...
      </properties>
      ...
    </domain>
    ...
  </domains>
</qubes>
  ```
* I would expect, by reading the comment in the log, to be able to get rid of it by:

```
qvm-prefs Qubes default_dispvm fedora-26-dvm # or qvm-prefs -D Qubes default_dispvm
qvm-remove fedora-25-dvm
```

* Maybe there shouldn't be a `Qubes.default_dispvm`
* Or maybe it should have the role of `dom0.default_dispvm`, and this latter should not exist?
* Maybe the system's default value for `default_dvm` pref should be managed from the *Qubes Global Settings* tool, and it should set both `Qubes.default_dispvm` and `dom0.default_dispvm`?

---

**Comment by unman** [comment]
I suggest you read this page:
https://www.qubes-os.org/doc/dispvm/

You cant remove the fedora-25-dvm because it is set as the default_dispvm. (The log message tells you this but is somewhat misleading: you already realise this is the case.)
You need to set another qube as the default_dispvm, but you're using the wrong syntax.
`qubes-prefs default_dispvm <name>` is what you want.

The thing is that now there are multiple disposableVMs it doesn't really have the same impact as when there was only one - I assume that's the reason why it's no longer in the Global Settings tool.

So there's a host of things here:
1. It would be better if the error message identified the real problem.
2. The log message is confusing.
3. The docs aren't all that clear.
4. You dont know how to set the default dispvm.

Please change the Title to something more specific.

**Comment by marmarek** [comment]
Yes, it's about global default value. It can be managed with `qubes-prefs` tool.
Indeed it should be also added to Qubes Global Settings tool @marmarta

**Comment by modulistic** [comment]
Hey thanks for the quick and informative answer :)
Clearly I've lagged behind the documentation, glad to see it's talking about R4. Also I was unaware of `qubes-prefs`; I was confusing it with `qvm-prefs`.

**Comment by mirrorway** [comment]
I keep hearing about this issue. I think it would be more user-friendly if removing a VM that is the default_dispvm should automatically set it to none.

**Comment by RefinedSoftwareLLC** [comment]
If the qube being deleted is the "[Dom0] Qube Global Settings" Default DispVM, then display:

"This qube can't be deleted while it is the system default of Default DispVM.
Change the system default of Default DispVM to: "

Then give a dropdown with the options of the list of dvm-templates (except qube being deleted).
Lastly, display "Effected qubes: " and list of every qube who's Default DispVM would be changed.

If there are no other dvm-templates then:

"This qube can't be deleted while it is the system default of Default DispVM.
To delete this qube, first create another DVM-Template to replace it.

**Comment by unman** [comment]
The error message now explains that the qube cannot be removed and identifies it as "global property default_dispvm" or "global property management_dvm". That clearly deals with the original issue.
@andrewdavidwong I suggest closing this.

The proposal from @RefinedSoftwareLLC is a separate enhancement, which _may_ warrant a separate issue.
