### ISSUE TITLE
fail to upgrade dom0 kernel

### ISSUE THREAD

**Issue by coeusite** [QubesOS/qubes-issues#3690]
### Qubes OS version:
R4.0-rc5

### Affected component(s): 
- dom0 kernel upgrade

### Steps to reproduce the behavior:
- ```sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing kernel-latest```
- reboot, and run ```uname -a```

### Expected behavior:
- dom0 should run with a kernel 4.15.6-1 (current kernel-latest)

### Actual behavior:
- dom0 still uses kernel 4.14.13-2

### General notes:
The build is Ryzen 5 2400G + Gigabytes AB350N, which requires kernel 4.15 or above. So I wanna try kernel-latest. This problem also applies to the "kernel" package.

EFI/qubes/ is not recognized by the build, so I followed the EFI troubleshooting, copied EFI/qubes/ to EFI/BOOT/ and modified filenames. However, both "qubes" and "BOOT" have kernel 4.14.13-2 after upgrade. 

By the way, the EFI partition (200M) is almost full.

Here is the output of qubes-hcl-report: 
[Qubes-HCL-Gigabyte_Technology_Co___Ltd_-AB350N_Gaming_WIFI-20180311-223715.yml.log](https://github.com/QubesOS/qubes-issues/files/1800129/Qubes-HCL-Gigabyte_Technology_Co___Ltd_-AB350N_Gaming_WIFI-20180311-223715.yml.log)

Here is a log of ```sudo dnf reinstall kernel-latest``` with some errors:
[kernel-latest.log](https://github.com/QubesOS/qubes-issues/files/1800130/kernel-latest.log)

**Comment by coeusite** [comment]
Well, I forgot to say that it was rc4 and upgraded to rc5 by updating softwares from current-testing repo. 


Now I’m making a flesh rc5 installation on an Intel-based platform to check whether it will disappear.

**Comment by coeusite** [comment]
This issue persists if I simply move the disk to an Intel PC.

However, it disappears with a flesh rc5 installation on an Intel PC.

**Comment by coeusite** [comment]
I checked my old build (Qubes R3.2 on a Kabylake platform), and found out that this issue is an old problem, i.e. after kernel upgrade, dom0 on the old build still uses kernel 4.9.35 instead of 4.9.56 or any newer kernel.

Maybe copying EFI/qubes to EFI/BOOT raises this problem.

**Comment by euidzero** [comment]
I confirm here with fresh R4.0 on a lenovo laptop. I did also copy EFI/qubes to EFI/BOOT.
What command is responsible for managing EFI/qubes ? I'd like to investigate.

**Comment by esote** [comment]
@andrewdavidwong Due to the lack of response, newer updates to documentation, & that R4.0 has been released with many Xen and Linux kernel updates (meaning it's unlikely to still occur), should this issue be closed?

**Comment by andrewdavidwong** [comment]
Closing this for now due to the lack of response. If you revisit the matter in the future, or if anyone would like the issue to remain open, please leave a comment, and we'll be happy to reopen this. Thank you.

**Comment by euidzero** [comment]
I did try up update to both  but 4.14.103-1 and 4.14.114-2 coming from 4.14.74 : xen.cfg is not updated in boot/EFI/qubes.
I checked that only the BOOTX64.cfg is used during boot.
Then I updated manually the configuration BOOTX64.cfg to point to new kernel / ramdisk none of them is bootable -> filling another bug as soon as I can do screenshot of the onscreen message.

**Comment by andrewdavidwong** [comment]
> filling another bug as soon as I can do screenshot of the onscreen message.

If you're referring to the same bug as reported in this issue, then please do not open a duplicate issue for it. Instead, I'll simply reopen this one.
