### ISSUE TITLE
getting help / support link missing on qubes-os.org

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#3691]
A google search for `qubesos getting help` or `qubesos support` doesn't bring helpful results.

There used to be https://www.qubes-os.org/help but it doesn't exist anymore? Anyhow.

There is:

-----

Team

    Report a Security Issue
    Report a Bug
    Press Inquiries
    Business Inquiries
    Mailing Lists
    Join the Team

-----

But it's not enough. Nowadays many people don't know what mailing lists are for. This leads to users finding /team and e-mailing individual developers.

May I suggest a `help` and/or `support` link in the footer? And a new page `Getting Help` or so that explains how free (and or paid - if that exists?) support works? That page could then link to https://www.qubes-os.org/mailing-lists/.

Once that is done, I also suggest to link to that page from the top of https://www.qubes-os.org/team/.

**Comment by andrewdavidwong** [comment]
We've already been over this many times before: #2305, #2152, #1841, #1833.

I don't see that this report adds anything that has not already been discussed in these other issues. If you don't want people to email you, we can simply remove your email address from the Team page.

**Comment by adrelanos** [comment]
The main issue I am seeing is not unwanted e-mails. It is that there is no `help` / `support` page. Nowhere explained how support works. More on that in the last chapter of this comment.

-----

#2305 - I disagree it being related therefore.

#2152 - was about the [Qubes team page](https://www.qubes-os.org/team/), adding a button there. (With the primary goal of users finding support, and secondary goal of less unwanted e-mails.)

#1841 / #1833 - not about getting support specifically.

-----

What I am reporting here:

* people don't know what a mailing list is or what it is good for
* A google search for `qubesos getting help` or `qubesos support` doesn't bring helpful results.

-----

I suggest:

* on the [Qubes team page](https://www.qubes-os.org/team/): rename `Join the mailing lists` to `Getting support`. Reason: It's good to try to guess what the user think/want. "Joining a mailing list" is much less likely a goal. Much more common wish is to "get support".
* a page that explains how getting support for Qubes works
  * rename page https://www.qubes-os.org/mailing-lists/ to https://www.qubes-os.org/support
    * Reason: "Qubes support" and/or "Qubes help" and/or "Qubes forum" is probably a much more common google search term than "Qubes mailing list" by new users. (Since mailing lists are unpopular/uncommon nowadays.)
  * Modify https://www.qubes-os.org/mailing-lists/ to explain how support works.
    * Currently one gets lost at hello. Imagine someone asks how to get Qubes support, you link to https://www.qubes-os.org/mailing-lists/ and the first thing is "staying safe". Reaction: "What?" "Seems unrelated."
    * Mention the words `forums`, `support`, `help` so these get indexed by search engines (let's call it very lightweight SEO).
    * Briefly explain how support works.

**Comment by andrewdavidwong** [comment]
Ok, I agree.
