### ISSUE TITLE
build Qubes-Whonix 14.0.0.6.9 (Release Candate 2) templates for R3.2 and R4

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#3695]
This will become the stable version if no grave bugs are reported.

**Comment by marmarek** [comment]
Qubes 4.0:
 - qubes-template-whonix-gw-14-4.0.0-201803131452 [build log](https://raw.githubusercontent.com/QubesOS/build-logs/master/build-fedora4/log_2018-03-13_14-20-10)
 - qubes-template-whonix-ws-14-4.0.0-201803131521 [build log](https://raw.githubusercontent.com/QubesOS/build-logs/master/build-fedora4/log_2018-03-13_14-25-52)

Uploading to unstable repo.

Qubes 3.2 failed:
 - gw [build log](https://raw.githubusercontent.com/QubesOS/build-logs/master/build-fedora3/log_2018-03-13_13-39-08) 
 - ws [build log](https://raw.githubusercontent.com/QubesOS/build-logs/master/build-fedora3/log_2018-03-13_14-08-29)

Looks like a problem with core-agent-linux package.

**Comment by marmarek** [comment]
Ok, fixed it. Templates for Qubes 3.2:
 - qubes-template-whonix-gw-14-4.0.0-201803132158 [build-log](https://raw.githubusercontent.com/QubesOS/build-logs/master/build-fedora3/log_2018-03-13_21-24-55)
 - qubes-template-whonix-ws-14-4.0.0-201803132215 [build-log](https://raw.githubusercontent.com/QubesOS/build-logs/master/build-fedora3/log_2018-03-13_21-40-18)

**Comment by unman** [comment]
@andrewdavidwong The task has been completed. Do you want to close?
