### ISSUE TITLE
Error on dom0 update

### ISSUE THREAD

**Issue by marmarta** [QubesOS/qubes-issues#3697]
### Qubes OS version:
R4.0rc4

### Affected component(s): 
Updating dom0.

### Steps to reproduce the behavior:
Update dom0 for example with the GUI.

### Expected behavior:
No errors.

### Actual behavior:
qvm-ls: error: unrecognized arguments: --kernel

It's not exactly a system-breaking bug, but it looks bad.

**Comment by andrewdavidwong** [comment]
Duplicate of #3694

**Comment by andrewdavidwong** [comment]
This appears to be a duplicate of an existing issue. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.
