### ISSUE TITLE
Recent fedora template update broke sys-net and thus basically everything

### ISSUE THREAD

**Issue by coconutoil** [QubesOS/qubes-issues#3699]
### Qubes OS version:

4.0 (R4.0)

### Affected component(s): 

sys-net and as such basically all AppVMs.

---

### Steps to reproduce the behavior:

About 20 hours ago I updated dom0 with `sudo qubes-dom0-update`, and also updated my fedora 26 template with `sudo dnf update` AND my debian 9 template with `sudoa pt-get update && sudo apt-get dist-ugrade`. I fell asleep shortly after.
Upon waking I restarted my Dell XPS 9350 laptop and found nothing really would open, eventually giving me the "cannot execute qrexec-daemon!" error.
After loads of internet searching I narrowed it down to sys-net failing, and indeed, if I for example change my network proivder in my debian 9 template to None, I can now start that AppVM template, albeit without network.
Fedora however still won't start even with None for network.
I played around a tonne with trying to create a new debian 9 based sys-net and got in over my head. I can't remember all the correct qube manager settings now (should sys-net use sys-firewall for network? and what does sys-net use? etc). 
Regardless, even with doing the PCI passthrough on my Intel 8260 wireless card via the debian9 ys-net attempt I didn't get anywhere.

### Expected behavior:

I have done `sudo dnf update` many times recently, and this is the first time I'm seeing problem with the fedora 26 template after it.

### Actual behavior:

it _appears_ that the latest fedora 26 template `sudo dnf update` has broken some things, and thus basically everything since sys-net relies on it

Error "cannot execute qrexec-daemon!" on sys-net startup

### General notes:

I have 16GB of RAM and 512GB SSD dedicated solely to qubes. My templates are barely over 4 gig. Space/memory is not an issue.
dom0 is 4.14.13-3

I've tried to look at the logs but they're so dense I can't make much sense. If I knew more where to look I might find something. There are a lot of mentions about python, but since it will require me to copy logs to USB, transfer to other computer etc, I will only do if necessary.

---

**Comment by unman** [comment]
I've just tested this on rc5 and I dont see any problem with an updated Fedora-26 template. Qubes using it seem to start just fine.
This is quite strange.
@coconutoil  Can you try starting a qube - not one providing network, and without any network resources attached??

**Comment by unman** [comment]
To make it clear - that's an updated Fedora-26 on rc5 as backing for sys-net..
Works fine.
**MY** dom0 has 4.14.18-1 
sys-net has N6205 and 82579LM adapters - both work fine.
Can you check again that you have updated to latest available both in dom0 and Fedora.

**Comment by coeusite** [comment]
Same as unman. No issue occurs on my R4.0-rc5 build.

**Comment by coconutoil** [comment]
@unman I can only start debian based qubes and only without any network selected. anything Fedora related is still broken.
However, I have just now blown away the install completely, as I need a working computer right now and gone back to another distro. I still have no idea what happened, but I will close this issue for now, seeing as though I cannot troubleshoot it further anyway.
I tried two live images, antergos and Tails and wifi worked fine there so I know it's not hardware related.

**Comment by coeusite** [comment]
@coconutoil Sad to hear that, and actually you can reinstall the fedora template and upgrade to rc5.

**Comment by straussmaus** [comment]
@coeusite How can you reinstall the fedora template please?  I have no internet connectivity in my fedors-26 or debian-9 templates after upgrading to whonix-14 and using a new NetVM.  Should I also reinstall maybe?

**Comment by andrewdavidwong** [comment]
@straussmaus:
> How can you reinstall the fedora template please?

https://www.qubes-os.org/doc/reinstall-template/

Please ask these sorts of questions in the `qubes-users` [mailing list](https://www.qubes-os.org/support/) instead (if you cannot find the answer in the documentation). It is intended to field these kinds of questions, whereas `qubes-issues` is not.
