### ISSUE TITLE
Mistake in appvm configuration and can't boot anymore 

### ISSUE THREAD

**Issue by BenoitGEORGELIN** [QubesOS/qubes-issues#3700]
Hi,
I did a mistake and can't boot my system. 
I linked my I internal vga card into an appvm. This vm is in auto-start mode at boot.
Since I did that, my system keep rebooting when it reach the session (I guess when the appvm start)

Is there any possibility to disable appvm to boot or to change the configuration file somewhere?

I would like to boot in single user mode or something similar but so far I'm stuck and can boot :(

It's not an issue, but I would appreciate some help. 

Regards, 
Benoît

**Comment by BenoitGEORGELIN** [comment]
Maybe I can disable the right service with :

`quiet systemd.mask=xxx`

From grub?

**Comment by marmarek** [comment]
You can try that - service `qubes-vm@VM_NAME.service`
Anyway, you should ask on qubes-users mailing list.

**Comment by BenoitGEORGELIN** [comment]
Yes, that's what I figured out :) 

Thanks for you help .
