### ISSUE TITLE
Cannot Restore Backups from dom0

### ISSUE THREAD

**Issue by coeusite** [QubesOS/qubes-issues#3701]
### Qubes OS version:
R4.0-rc5 with latest dom0 update and stock kernel 4.14.18-1

### Affected component(s): 
- restore backups

### Steps to reproduce the behavior:
- restore qubes from qubes manager
- select backup source location as dom0
- click on the button to select backup file

### Expected behavior:
a file explorer dialog appears and I can choose a backup file.

### Actual behavior:
an error dialog appears as shown:
![unnamed](https://user-images.githubusercontent.com/8091196/37441725-bf6792ec-283d-11e8-90fe-3dd305d1e470.jpg)

### General notes:
- When backup source location is a qubes instance, this problem does not occurs.
- If my memory is correct, this also applies to rc4.
- If I use ```System Tools > Restore Backup```, same problem occurs with ``` QubesVMError Cannot start Dom 0 fake domain! ad line 102 of file base.py```

**Comment by andrewdavidwong** [comment]
Reopening due to apparent regression reported in #4205.

**Comment by andrewdavidwong** [comment]
@strugee, can you confirm that you're using `qubes-manager-4.0.17-1.fc25` or later?

**Comment by strugee** [comment]
@andrewdavidwong shoot, so sorry. I'm on a fresh install and I hadn't installed updates at the time I reported that bug; I just upgraded and it's fixed. Looks like I got hit by #4099.

So sorry about all the dupes I've been filing! I swear I searched :roll_eyes: 

Feel free to reclose.
