### ISSUE TITLE
Error final part of installation

### ISSUE THREAD

**Issue by h-miles** [QubesOS/qubes-issues#3710]
I get an error message at final part of installation, it happens after configuring the template vms. I also left all the options default. I believe its to do with network manager:

['/usr/sbin/service', 'qubes-netvm', 'start'] failed:
stdout: ""
stderr: "Redirecting to /bin/systemctl start qubes-netvm.service 
Job for qubes-netvm.service failed because the control process exited with error code. "See ststemctl status qubes-netvm.service" and "journalctl -xe" for details.
"
Note I checked the digests and I the media test passed fine. I also tried to complete the installation on different computers but that different help.

Its the same issue as described in this post: https://www.reddit.com/r/Qubes/comments/6b484q/having_an_issue_in_the_last_part_of_the/?st=J35Y5Y0X&sh=83624631

**Comment by adeptcoder7** [comment]
![img_20180316_151008](https://user-images.githubusercontent.com/37459068/37553963-8e319596-29c9-11e8-8417-b2c525d75836.jpg)

**Comment by marmarek** [comment]
Check details as instructed in the error message (you should be able to login after closing this error message).

**Comment by adeptcoder7** [comment]
Yes I can login but what does the error mean and the consequences of it?
Thanks,
Harri

**Comment by marmarek** [comment]
It failed to start sys-net and/or sys-firewall. If that was temporary, everything else should be fine. But if it's persistent, you wont be able to start any network-connected VM. See "journalctl -xe".

**Comment by adeptcoder7** [comment]
Okay I can get it working on my old computer, but on my main computer. The
disk password box never shows up can I fix this? Or alternatively type it
through the console?

**Comment by DemiMarie** [comment]
Closing as there have been no updates in over 4 years and R4.0 is end of life.
