### ISSUE TITLE
No information about which qubes need restarting after template update

### ISSUE THREAD

**Issue by rootkovska** [QubesOS/qubes-issues#3716]
The Qubes widget should display some icon (like the green circular arrows we had in Qubes 3.2 in the Qubes Manager) next to each (running) qubes which needs to be restarted in order for the template changes to take effect on the qube's filesystem.

**Comment by marmarek** [comment]
Slightly related: currently the only place where you can check in which template you should install software to be available in qube X, is qube manager. We were talking how to fit it also in the menu or domains widget, but didn't come with any good idea. @rootkovska some suggestions?

**Comment by rootkovska** [comment]
If anywhere, then I think this should be fitted into the appemenus (rather than for the Qubes UI widget) for the given AppVM (e.g. I go to work appmenu folder, then have a shortcut to: Open Template for this VM).
