### ISSUE TITLE
Qube Manager: automatically update list after any Settings window closes with OK.

### ISSUE THREAD

**Issue by rootkovska** [QubesOS/qubes-issues#3718]

**Comment by marmarek** [comment]
I think this is already done when you launch settings window from the manager itself. And IMO it shouldn't try to watch for settings launched from elsewhere. Qube Manager is no longer something that you keep open at all times (that's role of domains widget). If we keep adding "refresh when X", "refresh when Y", we'll quickly get back crappy code we just got rid of...
There is "refresh" button already and we all agreed this application should be static.
