### ISSUE TITLE
Qube Manager: display some UI when Qubes Manager starts...

### ISSUE THREAD

**Issue by rootkovska** [QubesOS/qubes-issues#3719]
... or else the user has no indication that anything's happening and this might take tens of seconds (!) if there are many qubes in the system.

**Comment by marmarek** [comment]
There is already notification "Domain X is starting". There are some issues related to it, for example https://github.com/QubesOS/qubes-issues/issues/3660#issuecomment-374047148, #3680, But lets keep duplicated issues to minimum.

**Comment by rootkovska** [comment]
No, it's not about starting apps from qubes. The "the app" in the title refers to the Qube Manager, of course...

**Comment by shunju** [comment]
Maybe renaming the issue to “Display some UI while Qube Manager is loading…” would make it clearer.

Apparently. this issue only arises when you have very many qubes. I have twelve custom qubes and the dialog starts within 2…3 seconds (however, fairly new hardware with an i7-8550U processor).

Why does it take longer when there are more qubes in the system? Is the status of each of them queried before the window is drawn? If so, would it be possible to open the Qube Manager, render it without the list of qubes and populate the list afterwards?
