### ISSUE TITLE
A handy page for: "we won't use software XYZ, unless there is an _easy_ way to verify its integrity and authorship"

### ISSUE THREAD

**Issue by rootkovska** [QubesOS/qubes-issues#3720]
... so that we don't need to repeating ourselves over and over again. E.g. see:
https://groups.google.com/d/msg/qubes-devel/ilxC6UpkZz4/df3Amn6_AgAJ

**Comment by andrewdavidwong** [comment]
@rootkovska, @marmarek: How's this?

https://www.qubes-os.org/faq/#are-there-restrictions-on-the-software-that-the-qubes-developers-are-willing-to-use

**Comment by andrewdavidwong** [comment]
Assuming this is good. If not, please feel free to reopen.
