### ISSUE TITLE
Feature request: start VM on boot but after login screen

### ISSUE THREAD

**Issue by shunju** [QubesOS/qubes-issues#3724]
### Qubes OS version:

R4.0-rc5

### Affected component(s): 

I don’t know

---

### Steps to reproduce the behavior:

Select “Start qube automatically on boot” in the settings of a qube.

### Expected behavior:

Qubes start after showing the login screen.

### Actual behavior:

Qube starts before login screen is shown. Multiple start jobs block the boot process and the login screen is only shown after all qubes are booted. When many qubes are started automatically, this results in a very long boot time.

### General notes:

I understand that the current behavior may be desired for sys-usb (when an external keyboard is used for login) and possibly for sys-net and sys-firewall (here I already don’t see when this would be beneficial, because Qubes is a single-user system and therefore doesn’t login via network). But for my work VM, which I always want to start automatically to ensure that files are always synchronized with my NextCloud, there is no reason why its booting process should block the Qubes booting process and prevent me from logging in while it’s booting.

I would try to do this on my own. However, I have neither sufficient knowledge of Qubes nor of X to even know where to start. Also, other users might also consider this an important feature.

My temporary workaround is to put `qvm-run` commands into the Session and Startup. However, in this case VMs start only after I login (thereby wasting time) and sometimes not at all due to #3533.

---

### Related issues:

None found.

**Comment by 3hhh** [comment]
related: #3149

**Comment by shunju** [comment]
@3hhh Thank you for making me aware of your issue. I hadn’t found it because the title is phrased in a completely different way, but it basically is the same thing. I’ll close this issue in favor of yours.
