### ISSUE TITLE
debian template - dpkg error processing package qubes-core-agent

### ISSUE THREAD

**Issue by tomemstv** [QubesOS/qubes-issues#3726]
### Qubes OS version:

R3.2

### Affected component(s): 

Debian 9 template
Package qubes-core-agent

---

### Steps to reproduce the behavior:

debian-9$] sudo apt-get update && sudo apt-get upgrade -y

### Expected behavior:

qubes-core-agent update installs sucessfully

### Actual behavior:

Setting up qubes-core-agent (3.2.26-1+deb9u1) ...
Removed /etc/systemd/system/multi-user.target.wants/haveged.service.
Created symlink /etc/systemd/system/multi-user.target.wants/haveged.service → /etc/systemd/system/haveged.service.
Leaving 'diversion of /etc/init/plymouth-shutdown.conf to /etc/init/plymouth-shutdown.conf.qubes-disabled by qubes-core-agent'
Leaving 'diversion of /etc/init/prefdm.conf to /etc/init/prefdm.conf.qubes-disabled by qubes-core-agent'
Leaving 'diversion of /etc/init/splash-manager.conf to /etc/init/splash-manager.conf.qubes-disabled by qubes-core-agent'
Leaving 'diversion of /etc/init/start-ttys.conf to /etc/init/start-ttys.conf.qubes-disabled by qubes-core-agent'
Leaving 'diversion of /etc/init/tty.conf to /etc/init/tty.conf.qubes-disabled by qubes-core-agent'
Leaving 'diversion of /etc/init/serial.conf to /etc/init/serial.conf.qubes-orig by qubes-core-agent'
error: Error opening directory '/etc/dconf/db': No such file or directory

Usage:
  dconf update

Update the system dconf databases

dpkg: error processing package qubes-core-agent (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 qubes-core-agent

### General notes:

---

**Comment by unman** [comment]
Another problem is that in a vanilla debian-8, dconf-service is installed, but the dconf tool is not, so an updated template *also* lacks the dconf tool. That means that the qubes-core-agent install on upgrade throws warning - "dconf: command not found"
I'm not clear why @tomemstv doesn't show this behaviour, even using packages from Qubes testing.

For all that, on **my** upgraded debian-8 the template upgrades to qubes-core-agent (3.2.26-1+deb9u1), and appears to be fully functional.

(If the dconf tool is required then qubes-core-agent should require dconf-cli)
