### ISSUE TITLE
Screen locks randomly

### ISSUE THREAD

**Issue by shunju** [QubesOS/qubes-issues#3727]
### Qubes OS version:

R4.0-rc4, RC4.0-rc5

### Affected component(s): 

Something in dom0

---

### Steps to reproduce the behavior:

Work at the computer for a long amount of time.

### Expected behavior:

Screen never locks while user is actively using the computer.

### Actual behavior:

Sometimes, out of the blue, seemingly randomly, the screen will lock. Screen lock window gives feedback and unlocks screen when correct password is provided.

### General notes:

The mouse can only move inside the X screensaver window, moving the mouse or typing any keys (including Alt+Tab, Strg+Alt+Left, Strg+Alt+Right, …) does not redraw the screen.

I have a feeling that this issue is getting worse (happens more often recently), but that is hopefully just my imagination. I have searched /var/log/X.org.0.log and ~/.xsession-errors, but haven’t found anything conspicuous. I will try to remember to capture and provide logs as requested when the issue occurs again.

---

### Related issues:

Maybe #2399 is related. However, in contrast to #2399, the screen is in fact locked in the present issue.

**Comment by marmarek** [comment]
See `journalctl` in dom0, maybe it's related to some problem with time synchronization (when time catch up, xscreensaver might think that inactivity timeout just elapsed, in seconds).

When screen is locked, are other windows visible, or are blacked out?

**Comment by andrewdavidwong** [comment]
@shunju, you didn't say which DE you're using, so I've assumed it's Xfce4. Let me know if it's a different one.

**Comment by Aekez** [comment]
I have an acquaintance (also on Qubes), who once had a similar problem like this (Xfce4, XScreenSaver, Qubes 4.0. some months back).

I found a fix for him by outright disabling XScreenSaver by clicking the "Disable Screen Saver" in the Mode: dropdown menu in XScreenSaver settings. 
- He no longer had the issue after fully disabling it.
- His problem was a bit different but similar (it didn't happen when Qubes was used, but instead it didn't respect the timer).
  - For example, despite setting it to the max 720 minutes, it still occured within an hour at the very least, despite having the setting to last 12 hours (720/60) of computer inactivity.
- It never happened for him while he was using Qubes, but the 720 minute count didn't wait for 12 hours, but instead sometimes randomly happened in-between when inactive (i.e. when streaming movie, but Qubes keyboard/mouse/etc. input was untouched).

I have not observed it on my own Qubes system. However I also disable the XScreenSaver inactivity countdown my self, and instead made it a habit to manually log screen when absent, or manually trigger it with suspend mode instead. So I don't think I can encounter the bug anyway given the countdown timer is disabled, but this is only a deduction based on an anecdotal observation.

--- 

Whether this bug still happens, I'm not sure, it's been some months now. If its still around, maybe it'll go away on its own once dom0 is updated to fc26+ or never XScreensaver version in dom0 fc25?

**Comment by kototama** [comment]
I can confirm this bug and the explanation of Marmarek

> when time catch up, xscreensaver might think that inactivity timeout just elapsed, in seconds

looks like a good one because it happens at the full hour for me, for example at 10:00 and I also have time synchronization issue: XFCE displays the UTC time after I boot instead of the local time and then resynchronize later.

**Comment by Kixunil** [comment]
Happened to me awhile ago. The screen locked while I was scrolling. I found "Time has been changed" in `journalctl` at 13:00. At first I thought that mouse doesn't reset the tier, only keyboard, but this makes more sense now.

**Comment by jsmaniac** [comment]
I can confirm @marmarek's explanation. The clock was out of sync earlier, then I connected to the network, did some work, and in between two keystrokes the xscreensaver lock appeared (It did this at random intervals from time to time). I just checked and the clock is back in sync, so it seems likely the abrupt time change is the issue.

Can an attacker trick xscreensaver into not locking the screen by slowing down time reported by the network (e.g. if the attacker has control over the local gateway or `sys-net`)? Not that one should rely on xscreensaver to lock the screen after leaving the machine, of course :-) .

**Comment by daniel-ayers** [comment]
I am continuing to have problems with the screensaver activating randomly, *despite the screensaver being disabled*. Given the nature of that problem and the number of open screensaver issues generally perhaps screensaver issues need to be given greater priority?  An OS that randomly blanks the screen while the computer is being used isn't a very functional operating system.

**Comment by thavlik** [comment]
I am having this issue as well. The screen saver will turn on while I'm using the computer. The screen will not lock, but parts of the screen are black until they are repainted.

**Comment by jroimartin** [comment]
I'm using Qubes 4.0.3 with XFCE4 and I have also started experiencing random screen locks. Specifically, in my case this was happening while reading long documents where I was basically scrolling up and down with the mouse wheel (using a trackpad). So, I started doing some basic tests to understand under what conditions this was happening.

The first thing I did was discarding the problem related to time synchronization mentioned by @marmarek. I checked the logs and there isn't any time change event around the time when the screen lock happens. Also, it is not the "compositing" glitch mentioned in the documentation (GUI troubleshooting).

First of all I set all the display power management settings in the Xfce Power Management dialog to "Never" ("Blank after", "Put to sleep after" and "Switch off after"). Then, I configured xscreensaver to blank the screen after 1 minute. So, we can discard that both power management systems are "fighting" each other.

After that I did the following tests:

**Focus in an AppVM window:**

* Keyboard key press: Xscreensaver is triggered 1 minute after the last key press, as expected.
* Moving the mouse: Xscreensaver is triggered 1 minute after the last mouse movement, as expected.
* **Mouse click or scroll (iirc both are mouse button events): Xscreensaver's timer is not reset, so it is triggered 1 minute after the last registered event (key press or mouse movement).**

**Focus in a Dom0 window:**

* Keyboard key press: Xscreensaver is triggered 1 minute after the last key press, as expected.
* Moving the mouse: Xscreensaver is triggered 1 minute after the last mouse movement, as expected.
* Mouse click or scroll: Xscreensaver's is triggered 1 minute after the last mouse click or scroll event, as expected.

It seems to me that this could have to do with how qubes handle X mouse button events in AppVM windows. Somehow Xscreensaver is not detecting it, thus not respecting the blank time. Does it make sense?

**Comment by Kixunil** [comment]
@jroimartin that sounds like a good analysis to me! I noticed this happening when scrolling through long articles but never thought why would I notice it more in those cases. I thought it's just my perception. So I guess you're on the right track here.

**Comment by jroimartin** [comment]
Checking the code of Xscreensaver 5.43 I found the following comment in **driver/timers.c:150** inside the function `notice_events()`:

```
     Note that we can't select for ButtonPress, because of X braindamage:       
     only one client at a time may select for ButtonPress on a given            
     window, though any number can select for KeyPress.  Someone explain        
     *that* to me.                                                              
                                                                                
     So, if the user spends a while clicking the mouse without ever moving      
     the mouse or touching the keyboard, we won't know that they've been        
     active, and the screensaver will come on.  That sucks, but I don't         
     know how to get around it.                                                 
                                                                                
     Since X presents mouse wheels as clicks, this applies to those, too:       
     scrolling through a document using only the mouse wheel doesn't            
     count as activity...  Fortunately, /proc/interrupts helps, on              
     systems that have it.  Oh, if it's a PS/2 mouse, not serial or USB. 
```

I'm not familiar neither with X internals nor with Xscreensaver, but the comments seems pretty related to the problem described before.

There is another very relevant comment in the Xscreensaver's code at **driver/timers.c:1008**:

```
           /* Starting in late 2014, GNOME programs don't actually select for      
           or receive KeyPress events: they do it behind the scenes through     
           some kind of Input Method magic, even when running in an en_US       
           locale.  However, those applications *do* update the WM_USER_TIME    
           property on their own windows every time they recieve a secret       
           KeyPress, so we must *also* monitor that property on every           
           window, and treat changes to it as identical to KeyPress.            
                                                                                
           _NET_WM_USER_TIME is documented (such as it is) here:                
                                                                                
             http://standards.freedesktop.org/wm-spec/latest/ar01s05.html       
             #idm139870829932528                                                
                                                                                
           Specifically:                                                        
                                                                                
             "Contains the XServer time at which last user activity in this     
             window took place. [...]  A client [...] might, for example,       
             use the timestamp of the last KeyPress or ButtonPress event."      
                                                                                
           As of early 2016, KDE4 does something really stupid, though: some    
           hidden power management thing reduces the display brightness 150     
           seconds after the screen is blanked -- and sets a WM_USER_TIME       
           property on a hidden "kded4" window whose time is in the distant     
           past (the time at which the X server launched).                      
                                                                                
           So we ignore any WM_USER_TIME whose timestamp is more than a         
           couple seconds old.                      
```

So, I did the following test:

1. I opened **xterm** in Dom0 and scrolling inside the xterms's window do not reset the Xscreensaver timer. The screen is locked before it should.
2. I opened **xfce4-terminal** in Dom0 and scrolling inside the xfce4-terminal's windows resets the Xscreensaver timer. The screen is locked respecting the Xscreensaver timeout after the last mouse button event is sent.

So, it's clear that it's not only about Dom0 windows vs AppVM windows. 

My guess is that this issue could be fixed modifying qubes-guid to update the property `WM_USER_TIME` of the AppVM window every time the user sends an event. @marmarek @andrewdavidwong what do you think?

As I said, I'm not familiar with all this, so excuse me in advance if what I wrote is not accurate or simply wrong.

**Comment by marmarek** [comment]
Yes, this makes much sense, thanks for finding those hints! Now we have some actionable way to fix it :)

**Comment by jroimartin** [comment]
Just for the record, xfce4-terminal uses `_NET_WM_USER_TIME` together with `_NET_WM_USER_TIME_WINDOW`. Given the rationale provided in the spec (copied under these lines for convenience), this might be the right way to proceed also in the case of qubes-guid.

> _NET_WM_USER_TIME_WINDOW
> 
> _NET_WM_USER_TIME_WINDOW WINDOW/32
> 
> This property contains the XID of a window on which the client sets the _NET_WM_USER_TIME property. Clients should check whether the window manager supports _NET_WM_USER_TIME_WINDOW and fall back to setting the _NET_WM_USER_TIME property on the toplevel window if it doesn't.
> 
> Rationale: Storing the frequently changing _NET_WM_USER_TIME property on the toplevel window itself causes every application that is interested in any of the properties of that window to be woken up on every keypress, which is particularly bad for laptops running on battery power. 

Reference: https://specifications.freedesktop.org/wm-spec/latest/ar01s05.html

**Comment by DemiMarie** [comment]
I’ll take this one, although it will be a while before I get around to it due to package manager issues.
