### ISSUE TITLE
Lenovo ThinkPad X1 Carbon Gen 6 boots to emergency shell on 4.0-rc5

### ISSUE THREAD

**Issue by Ranguvar** [QubesOS/qubes-issues#3729]
### Qubes OS version:

4.0-rc5

### Affected component(s): 

System boot

---

### Steps to reproduce the behavior:

Using Lenovo X1 Carbon Gen 6, attempt to boot from USB

### Expected behavior:

Successful boot

### Actual behavior:

Stalls, runs timeout scripts many, many times, then drops to recovery shell.
This is with CSM enabled. With CSM disabled, refuses to boot entirely (stuck at Xen info text).
https://pastebin.com/SCxEB7tF

### General notes:

---

**Comment by Ranguvar** [comment]
If I change boot to Legacy mode I can install and use the system.

**Comment by marmarek** [comment]
Looks like something goes wrong with preparation of the installation USB stick. According to logs, there is only one partition, but on actual installation image there should be two. Make sure you copy the image as a whole device (on linux - without "1" in device name).

**Comment by Ranguvar** [comment]
My apologies, this was the issue.
I should have read the guide more closely - I am used to writing in ISO mode with Rufus.

Thank you for all the work you do on this amazing project!
