### ISSUE TITLE
Qubes Manager 4.0.16 - "QubesVMNotStartedError: Domain is powered off" when killing VM

### ISSUE THREAD

**Issue by Simon-Davies** [QubesOS/qubes-issues#3730]
### Qubes OS version:

Qubes 4.0 RC5.0

### Affected component(s): 

Qubes Manager 4.0.16

---

### Steps to reproduce the behavior:

Click Kill VM

### Expected behavior:

VM is killed

### Actual behavior:

Whoops. A critical error has occurred. This is most likely a bug in Qubes Manager.

QubesVMNotStartedError: Domain is powered off:
'fedora-26'
at line 195
of file /usr/lib/python3.5/site-packages/qubesmanager/qubesmanager.py 

### General notes:

---

**Comment by marmarek** [comment]
@marmarta I guess you'll like this one.

**Comment by marmarta** [comment]
Oh for f... sake. (I know why this happens, I'm on it)

On March 22, 2018 4:57:35 PM GMT+01:00, "Marek Marczykowski-Górecki" <notifications@github.com> wrote:
>@marmarta I guess you'll like this one.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/QubesOS/qubes-issues/issues/3730#issuecomment-375358810

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by marmarta** [comment]
Oh don't be! It's very helpful - just this particular thing has been haunting me in various incarnations for a while :D

On March 22, 2018 5:03:40 PM GMT+01:00, Simon Davies <notifications@github.com> wrote:
>Sorry to be a bug reporting kill joy :)
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/QubesOS/qubes-issues/issues/3730#issuecomment-375360973

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by andrewdavidwong** [comment]
Updated title to be more descriptive.
