### ISSUE TITLE
Cannot use "check for dom0 updates" toggle in Qubes Global Settings

### ISSUE THREAD

**Issue by unman** [QubesOS/qubes-issues#3731]
### Qubes OS version:

4.0 rc5

### Affected component(s): 

Qubes Global Settings

---

### Steps to reproduce the behavior:

Run qubes-global-settings in dom0
Toggle checkbox value for "Check for dom0 updates"
Click OK

### Expected behavior:

Value of dom0 updates checking will change

### Actual behavior:

Whoops Critical error -
NotImplementedError: Toggle dom0 updates not implemented at line 279 of file global_settings.py

### General notes:

---

**Comment by marmarta** [comment]
It should have been fixed by https://github.com/QubesOS/qubes-manager/pull/74 and work correctly now.
