### ISSUE TITLE
Cannot change "qube updates" setting in 4.0rc5

### ISSUE THREAD

**Issue by unman** [QubesOS/qubes-issues#3732]
### Qubes OS version:

4.0 rc5

### Affected component(s): 

Qubes Global Settings

---

### Steps to reproduce the behavior:

Run qubes-global-settings
Change value in "Check for qube updates" checkbox.
Click OK

### Expected behavior:

Value for qube updates will change

### Actual behavior:

Global Settings window closes, with no error.
However qube updates value is not changed

### General notes:

---

**Comment by marmarta** [comment]
What do you except to happen? Perhaps this is not described as well as it could be - this option changes merely the default for new qubes, if you want to change it for all qubes, you need to use one of the buttons below. I'll update the description.
