### ISSUE TITLE
Computer does not recover from suspend

### ISSUE THREAD

**Issue by unman** [QubesOS/qubes-issues#3738]
### Qubes OS version:

R4.0 rc5

### Affected component(s): 

Resume after suspend

---

### Steps to reproduce the behavior:

Suspend by shutting lid

### Expected behavior:

Resume after suspend should work

### Actual behavior:

Computer does not recover.
Screen stays black and no response to keyboard ot trackpad use.
Fans do not spin up.
Sometimes computer will not restart.

### General notes:

I do not think this is the same issue as #3705 since symptoms are slightly different.
This is an old x230, with RAM at only 8GB.
It worked flawlessly under rc5 until I applied updates from current-testing. 
On previous packages from current, suspend/restore worked **every** time.
Since the update it fails every time.
I see nothing relevant in the logs.

Obviously i suspect the update to xen-4.8.3-4.
I'll revert the update and downgrade back to 8.3-3 to see what effect that has.

---

### Related issues:

#3705 - but I think this is not the same.

**Comment by unman** [comment]
I downgraded all relevant xen packages to 4.8.3-3 and previous functionality has been restored.
All seems to work fine now - at least, a couple of suspend/resume cycles have worked as expected, whereas with 3-4 they never worked.

**Comment by marmarek** [comment]
@HW42 xen-4.8.3-4 breaks suspend.

**Comment by tasket** [comment]
Is 4.8.3-4 the Spectre mitigation update?

@unman Lenovo recently released BIOS updates with Spectre mitigation support for Ivy Bridge Thinkpads like the x230. Have you updated?

**Comment by donob4n** [comment]
Hi,

I also had suspend/resume broken and booting an older kernel (4.14.13-2) works fine.

**Comment by andrewdavidwong** [comment]
> Is 4.8.3-4 the Spectre mitigation update?

According to [QSB 37](https://github.com/QubesOS/qubes-secpack/blob/master/QSBs/qsb-037-2018.txt), it's `4.8.3-3`.

**Comment by o-** [comment]
Hi, I can confirm I had the same issue with X1 5th gen carbon. I believe it was after microcode_ctl update, rather than xen update, but am not sure. Wakeup only worked when I shut down every VM, (even sys-usb and sys-net). Latest bios upgrade by lenovo fixed the issue. Seems to reliably work again.

**Comment by Simon-Davies** [comment]
I was also experiencing this issue on my Dell XPS 15 but flashing the latest Bios update fixed it for me.

**Comment by Simon-Davies** [comment]
@X4lldux Have you tried updating your system's Bios firmware by flashing the latest version from the Manufacturer? This fixed the issue for me.

**Comment by X4lldux** [comment]
@Simon-Davies should have mentioned ealier, already have the latest version and that doesn't change the above results.

**Comment by HW42** [comment]
QubesOS/qubes-issues#3738 should fix this in practice. But is strictly not complete:

Jan Beulich:
> Of course none of this addresses a possible NMI or #MC occurring before the microcode loading.

**Comment by marmarek** [comment]
In what cases those could happen?

**Comment by HW42** [comment]
TBH I don't know. AFAIU one case would be hardware faults (RAM or bus errors). Not sure if Xen is using any breakpoint tricks ore something similar for profiling and if this can be active during early resume.

FWIW: I never observed any such problems during testing.

Based on https://lists.xenproject.org/archives/html/xen-devel/2018-04/msg00836.html I assume that Jan or Andrew will come up with a follow-up patch to disable IBRS/IBPB during suspend.

**Comment by donob4n** [comment]
@marmarek I'm pretty confused

> The package python2-xen-4.8.3-5.fc25 has been pushed to the r4.0 testing repository for dom0.

I checked and I don't have this package installed in dom0. Is this normal? Has it relation with this bug?

I'm running an old kernel due this bug and I would like to run the latest version.

**Comment by marmarek** [comment]
> I checked it but I don't have this package installed in dom0. Is this normal?

Yes. Notification script is confused about multiple packages from a single source and just pick the first one. What is important is a package version (xen*-4.8.3-5.fc26)

**Comment by mirrorway** [comment]
The updates fixed my resume issues. :)

**Comment by donob4n** [comment]
This fixed also for me great :)
