### ISSUE TITLE
no "kernel-devel" for fedora 26 (any kernel), can't update one of my boxes's netvm :( need help building kernel module for new fedora

### ISSUE THREAD

**Issue by tonsimple** [QubesOS/qubes-issues#3742]
### Qubes OS version:

R 3.2

### Affected component(s): 

Fedora 26 templates (but this is continuation of an old and terrible issue)

---

### Steps to reproduce the behavior:

Try finding a way to build a kernel module for VMs that use Fedora 26 based templates 

### Expected behavior:

Kernel-devel package present for most recent VM kernel, install it and do a build, use the resulting module to get wireless dongle going

### Actual behavior:

no kernel-devel for fedora 26, means the netvm on one of my Qubes boxes will have to stay on fedora 25 (and kernel 4.4.31-11 because that's the latest kernel-devel supported on F25 :( )

### General notes:

There seems to be a long going, persistent issue with kernel-devel being available for qubes VMs.

It is... disconcerting.

Is there a way to get a kernel module build for Fedora 26 and recent kernel version that does not rely on kernel-devel (maybe debian, because frankly I'd rather use a debian-based VM) ?

if not, is kernel-devel going to be provided?

I am very unhappy with having a F25, old kernel VM running as sys-net but so far I have no other choice.

---

### Related issues:

There seems to be a  "thing" with kernel-devel. :(
https://github.com/QubesOS/qubes-issues/issues/3158

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 has reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
