### ISSUE TITLE
Enigmail 2.0 update breaks qubes-gpg-split

### ISSUE THREAD

**Issue by TFQOS** [QubesOS/qubes-issues#3750]
### Qubes OS version:
R3.2, fedora 26, testing repos enabled

### Affected component(s): 
qubes-gpg-split

---
### Steps to reproduce the behavior:
Use Enigmail 2.0 (on Thunderbird 52.7.0 x64) with qubes-gpg-split

### Expected behavior:
qubes-gpg-split should support '--no-auto-check-trustdb' option

### Actual behavior:
Thunderbird stays frozen indefinitely trying the command:
`/usr/bin/qubes-gpg-client-wrapper --charset utf-8 --display-charset utf-8 --no-auto-check-trustdb --batch --no-tty --status-fd 2 --with-fingerprint --fixed-list-mode --with-colons --list-keys`
The command returns:
`qubes-gpg-client: unrecognized option '--no-auto-check-trustdb`

### General notes:
Enigmail 2.0 use a new command-line option '--no-auto-check-trustdb'.  
qubes-gpg-split should support this option.  
  
Temporary fix: patching /usr/bin/qubes-gpg-client-wrapper with
```
--no-auto-check-trustdb)
shift
;;
```
to ignore the option.

---

### Related issues:
Not found

**Comment by holiman** [comment]
Can confirm the same on `4.0 (R4.0)`

**Comment by mfc** [comment]
thanks @TFQOS for investigating the root cause. 

I would bump up the priority of this and get the quick fix out, as this bug will break all split-gpg setups for all Qubes users.

related threads:
qubes-users: https://groups.google.com/d/msg/qubes-users/G2ii-BBOQgE/G5QV1w_1CQAJ
enigmail-users: https://admin.hostpoint.ch/pipermail/enigmail-users_enigmail.net/2018-March/004854.html

**Comment by TFQOS** [comment]
```+++ qubes-gpg-client-wrapper
@@ -10,6 +10,10 @@
 while [[ $1 ]]; do
     if ! ((eoo)); then
         case "$1" in
+            # https://github.com/QubesOS/qubes-issues/issues/3750
+            --no-auto-check-trustdb)
+                shift
+                ;;
             --import)
                 # ignore all the options and only collect file name(s) - if any
                 shift
```
This patch should be applied to /usr/bin/qubes-gpg-client-wrapper (preferably in the template, or at each start of the VM)

'--no-auto-check-trustdb' seems related to performance concerns, should we just ignore it in qubes wrapper?
Or should we patch qubes-gpg-client binary?

**Comment by marmarek** [comment]
After reading https://dev.gnupg.org/T2019, I'd go with adding the option to the whitelist.

**Comment by cooperq** [comment]
for those who are hand patching this I also had to add the following line to `/usr/bin/qubes-gpg-client-wrapper`:
```bash
--sender)
shift
;;
```

**Comment by Cyrixo** [comment]
Hello,
I use Qubes r4.0 and thunderbird, enigmail on fedora 26.
I installed the update under dom0 and fedora but the body of the message in thunderbird remains white.

**Comment by andrewdavidwong** [comment]
> I use Qubes r4.0 and thunderbird, enigmail on fedora 26.
> I installed the update under dom0 and fedora but the body of the message in thunderbird remains white.

The problem you're describing sounds different from the bug that this issue is about. If that's correct, please file a separate issue for your problem. If it's incorrect, please explain how the problem you're describing is the same as the one this issue is about.

**Comment by grote** [comment]
I am now having a similar issue with Enigmail adding `--sender address@example.org` to the command. Anybody else seeing this?

**Comment by cubi7** [comment]
Will the be a plan to add the updated qubes-gpg-split to r3.2 stable?  It is still on 2.0.28 and can not work with new enigmail and never version are nearly 2 months old.    This will stop user be able to update enigmail to fix coming GPG secuity issues

https://www.eff.org/deeplinks/2018/05/attention-pgp-users-new-vulnerabilities-require-you-take-action-now

**Comment by marmarek** [comment]
GPG update is not the same as enigmail update or qubes-gpg-split update.
