### ISSUE TITLE
Qubes Manager: Updating dom0 seems to not working

### ISSUE THREAD

**Issue by diffusae** [QubesOS/qubes-issues#3751]
### Qubes OS version: 

R4.0rc5

### Affected component(s):  

Qubes Manager

---

### Steps to reproduce the behavior: 

If you start Qubes Manager and try to update dom0, it tries to download the update list, but than nothing more is happen. 

### Expected behavior:

Normally you should see the screen with the package list.

### Actual behavior: 

A window is showing that updates are downloaded, but after that there is no more information.

### General notes: 

Maybe there aren't updates available, but I am not sure.

---

### Related issues:

?

**Comment by marmarta** [comment]
@marmarek , this is one of yours -  the qubes-dom0-updates script doesn't display any gui indication that there are no updates available
(line 229:
`else
    rm -f $UPDATES_STAT_FILE
    echo "No updates available" >&2
fi` )
