### ISSUE TITLE
GUI sub window issues - Work VM based on Debian 9 Template 

### ISSUE THREAD

**Issue by Simon-Davies** [QubesOS/qubes-issues#3752]
### Qubes OS version:

Qubes R4.0 RC5

### Affected component(s): 

GUI sub windows - Work VM based Debian 9 Template with kali rolling repositories added

---

### Steps to reproduce the behavior:

Launch BurpSuitePro from the terminal. Click on Proxy - HTTP history - Click on Filter section

### Expected behavior:

Filter sub window is shown

### Actual behavior:

Filter sub window isn't shown. I see it momentarily, it flashes 

### General notes:

---

**Comment by andrewdavidwong** [comment]
@DemiMarie, you added the "more info needed" label, but you didn't ask for any info. What info is needed?

**Comment by DemiMarie** [comment]
@andrewdavidwong does this still reproduce?

**Comment by andrewdavidwong** [comment]
> @andrewdavidwong does this still reproduce?

Why are you asking me? I've never experienced this issue and have no idea. I was asking *you* what info is needed in order to diagnose this issue, because *you* are the one who added the "more info needed" label.

**Comment by DemiMarie** [comment]
> > @andrewdavidwong does this still reproduce?
> 
> Why are you asking me? I've never experienced this issue and have no idea. I was asking _you_ what info is needed in order to diagnose this issue, because _you_ are the one who added the "more info needed" label.

I need to know if this still reproduces.

**Comment by andrewdavidwong** [comment]
> I need to know if this still reproduces.

@Simon-Davies?

**Comment by marmarta** [comment]
I think this can be safely closed after 5 years of no further reports.
