### ISSUE TITLE
Qubes4.0-rc5 final installation step fails - no qvms created

### ISSUE THREAD

**Issue by JorgenRask** [QubesOS/qubes-issues#3753]
### Qubes OS version:

4.0-rc5

### Affected component(s): 

installation

---

### Steps to reproduce the behavior:

Tried to install on a ThinkPad T430 laptop. Final installation step, where qvms should be created fails with this message (I did not change any of the preselected options)
![image](https://user-images.githubusercontent.com/33736127/37990837-ad96f8e0-3207-11e8-9fb1-107004538ad4.png)

I also tried to change the options, but got the same error regardless.

After reboot not much works. I have tried to select System Tools->Qubes Manager and ->Restore Backups, but they both fail with these messages:

![image](https://user-images.githubusercontent.com/33736127/37990909-e82fed86-3207-11e8-8a9f-07534604a9e7.png)

### General notes:

Qubes 4.0-rc5 does not work at all for me, so I end up scratching the installation.
I tried to install two times and both times with same result (final step fails).

---

**Comment by androto** [comment]
Hardware Lenovo X1 5th Gen.
Here is my output from the command.

![output-lenovo-x1-5th-gen](https://user-images.githubusercontent.com/37738881/38027669-c71e705c-3290-11e8-8243-453e0a4f6360.jpg)

**Comment by JorgenRask** [comment]
Here is output from journalctl on my Thinkpad T430:
![img_3094 1](https://user-images.githubusercontent.com/33736127/38028911-a601d194-3294-11e8-9299-da4416331a54.JPG)
![img_3095 1](https://user-images.githubusercontent.com/33736127/38028931-b04b8bea-3294-11e8-8c28-f90589702fdb.JPG)
![img_3098 1](https://user-images.githubusercontent.com/33736127/38028943-b9c83786-3294-11e8-82a2-f0592819c7d3.JPG)

**Comment by JorgenRask** [comment]
Right after first boot, I switched to console (F1) and saw this:
![img_3092 1](https://user-images.githubusercontent.com/33736127/38029026-01f209c4-3295-11e8-82a5-af8f0c71e5b6.JPG)

**Comment by JorgenRask** [comment]
systemctl status shows this:
![img_3099 1](https://user-images.githubusercontent.com/33736127/38029170-701e9f52-3295-11e8-8ce0-5a845594b385.JPG)
![img_3100 1](https://user-images.githubusercontent.com/33736127/38029178-75e48a64-3295-11e8-82e0-43f00bbe2d78.JPG)
![img_3101 1](https://user-images.githubusercontent.com/33736127/38029188-7bcd28fa-3295-11e8-8ee8-33b3c180d342.JPG)

**Comment by marmarek** [comment]
`ValueError: could not convert string to float: '9,27'`
#$%^&*&^%$#$ locale.
Create `/etc/systemd/system/qubesd.service.d/10_locale_fix.conf` with:
```
[Service]
Environment=LC_ALL=C.UTF-8
```
(you need to create that directory)

**Comment by marmarek** [comment]
After that, restart `qubesd` service and re-run initial setup with `sudo /usr/libexec/initial-setup/initial-setup-graphical`.

**Comment by JorgenRask** [comment]
I have done as you instructed, but trying to restart qubesd service did not seem to do the trick, but after a reboot I can run sudo /usr/libexec/initial-setup/initial-setup-graphical, and now it seems to work!

![img_3102 1](https://user-images.githubusercontent.com/33736127/38033639-c3c6b828-32a0-11e8-9726-016847227f99.JPG)

**Comment by marmarek** [comment]
Oh, I forgot about `systemctl daemon-reload` - systemctl warns about that.

**Comment by marmarek** [comment]
Wait, what settings have you used during installation? There is only English choice available. Some different variant than "US"?

**Comment by JorgenRask** [comment]
Yes, there is only "US English" language, but I selected "US (Denmark)" keyboard layout. Now that you mention it, it's a little curious that keyboard layout affects other language choices...!
PS! After the correction everything seems to work fine. I have Restored a backup of some qvm's from the previous Qubes3.2 installation, but I have not had time to check if everything works as expected - but at least I got past the initialization step :-)

**Comment by marmarek** [comment]
It isn't about keyboard layout. It's about decimal separator. And I've already found - en_DK is literally the only English variant that have a coma, not dot:
```
$ localectl list-locales|grep ^en|grep -i utf|while read x; do LC_NUMERIC=$x printf '%s: %f\n' $x 10; done
en_AG.utf8: 10.000000
en_AU.utf8: 10.000000
en_BW.utf8: 10.000000
en_CA.utf8: 10.000000
en_DK.utf8: 10,000000
en_GB.utf8: 10.000000
en_HK.utf8: 10.000000
en_IE.utf8: 10.000000
en_IL.utf8: 10.000000
en_IN.utf8: 10.000000
en_NG.utf8: 10.000000
en_NZ.utf8: 10.000000
en_PH.utf8: 10.000000
en_SG.utf8: 10.000000
en_US.utf8: 10.000000
en_ZA.utf8: 10.000000
en_ZM.utf8: 10.000000
en_ZW.utf8: 10.000000
```
