### ISSUE TITLE
Default menu shortcuts not pre-populated in Qubes VM Manager (Whonix 14 AppVMs/TemplateVMs)

### ISSUE THREAD

**Issue by torjunkie** [QubesOS/qubes-issues#3763]
### Qubes OS version:

R3.2

### Affected component(s): 

Qubes VM Manager

---

### Steps to reproduce the behavior:

1. Install latest Whonix 14 templates from unstable repos
2. Recreate the Whonix 14 AppVMs with sudo qubesctl state.sls qvm.anon-whonix

### Expected behavior:

AppVM and TemplateVM menu shortcuts are already populated with normal selection e.g. Arm, Dolphin, Konsole, etc.

### Actual behavior:

AppVM/TemplateVM menu shortcuts must be manually added one by one with the "Add more shortcuts" option from Qubes VM Manager

### General notes:

I know this is a relatively trivial issue, but it is counter to user expectations i.e. AppVMs/TemplateVMs should be pre-populated with set VM defaults for applications.

---

**Comment by andrewdavidwong** [comment]
It sounds like you're referring to the shortcuts in the application launcher menu, which is different from Qubes Manager. Are you using the default desktop environment, Xfce4?

**Comment by torjunkie** [comment]
Hi Andrew,

Apologies. You are correct re: application launcher menu. Using the standard default environment Xfce4.

If my expectation is incorrect re: pre-population, feel free to close this issue (it's been a while since I installed new templates and AppVMs related to them).

**Comment by adrelanos** [comment]
pre-population is expected.

(Defaults are configured here:

* https://github.com/Whonix/qubes-template-whonix/tree/master/appmenus_wheezy_whonix-gateway
* https://github.com/Whonix/qubes-template-whonix/tree/master/appmenus_wheezy_whonix-workstation)

There should be `*.list` files inside `/var/lib/qubes/vm-templates/whonix-gw-14/`. Example:

    ls -la /var/lib/qubes/vm-templates/whonix-gw-14/*.list

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 has reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
