### ISSUE TITLE
Proper debian-9 "shutdown qube"/"kill qube" fails, generates qubesmanager error

### ISSUE THREAD

**Issue by RooneyMcNibNug** [QubesOS/qubes-issues#3764]
### Qubes OS version:

Qubes release 4.0 (R4.0)

### Affected component(s): 

Issue triggered from the debian-9 template, error generated from dom0.

---

### Steps to reproduce the behavior:

Right clicking on the debian-9 template within the Qube Manager GUI and choosing "shutdown qube" doesn't go through with a proper shutdown. After several minutes, I attempted to "kill qube" and was greeted with the error in the Actual behavior section below.

### Expected behavior:

The template to shutdown fully/properly.

### Actual behavior:

```
[Dom0] Houston, we have a problem...

Whoops, A critical error has occurred. This is most likely a bug in Qubes Manager.

AssertationError:
at line 772
of file /usr/lib/python3.5/site-packages/qubesmanager/qube_manager.py
----
line: assert vm.is_running()
func: action_shutdownvm_triggered
line no.: 772
file: /usr/lib/python3.5/site-packages/qubesmanager/qube_manager.py'
```

### General notes:

Logging out and back in again certainly clears everything back to normal, but this issue persists if I go through the same process again afterwards.

---

**Comment by marmarta** [comment]
I have to ask - was the template actually running?

**Comment by marmarta** [comment]
This should be working more correctly now (no errors, at least, although I'm not sure why the longer shutdown times).

It was fixed by https://github.com/QubesOS/qubes-manager/pull/82
