### ISSUE TITLE
Qubes-Whonix 14 SaltStack state files required

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#3765]
I am not sure it was a good idea to go for versioned (suffixing `-14`) Whonix template names.

* We now have the issue that [salt uses](https://github.com/QubesOS/qubes-mgmt-salt-dom0-virtual-machines/blob/master/qvm/anon-whonix.sls) non-versioned hardcoded values.
* However, [instructions for testing newly built Qubes-Whonix 14 templates] need to refer to the versioned template names.
* Qubes-Whonix manual setup got to complicated that we now advice users to use salt for it. (#3447) So telling users to do that manually is not an option either.

Perhaps we should revert this for the next template release and go back to non-versioned template names? Do you see a better solution for this?

**Comment by mirrorway** [comment]
Isn't the natural solution to just modify and version the salt too? `qubesctl state.sls qvm.anon-whonix-14 dom0` This would allow the salt setup to be different between future diffferent major versions of whonix.

**Comment by adrelanos** [comment]
Shall I just duplicate all files with names containing `whonix` on https://github.com/QubesOS/qubes-mgmt-salt-dom0-virtual-machines/tree/master/qvm and add `-14` to the file names and file content where appropriate? @marmarek

**Comment by marmarek** [comment]
Salt can use variables, and those can be set pillars (separate files, also enabled/disabled with `top.enable`/`top.disable`). We use this for setting either separate sys-usb, or combined with sys-net, then when [referencing USB VM](https://github.com/QubesOS/qubes-mgmt-salt-dom0-virtual-machines/blob/master/qvm/sys-usb.sls), use `{{ salt['pillar.get']('qvm:sys-usb:name', 'sys-usb') }}` (`sys-usb` here is default value if it isn't defined in pillar). [pillar file](https://github.com/QubesOS/qubes-mgmt-salt-dom0-virtual-machines/blob/master/pillar/qvm/sys-net-as-usbvm.sls)

We can do the same with Whonix - use variable like `qvm:whonix:version_suffix` (with either empty value or `-14`, later `-15` etc). Then use it everywhere when referencing whonix-gw or whonix-ws templates (and probably also `whonix-ws-dvm` name). And provide files to set some particular value. This way, using non-default version would require just `qubesctl top.enable qvm.whonix-14` before `qubesctl state.sls qvm.anon-whonix`.

We can do the same with other Whonix-related VMs (sys-whonix, anon-whonix), but IMO by default those should stay with current names. Separate variable?

**Comment by adrelanos** [comment]
> We can do the same with other Whonix-related VMs (sys-whonix, anon-whonix), but IMO by default those should stay with current names.

Sounds good!

> We can do the same with other Whonix-related VMs (sys-whonix, anon-whonix), but IMO by default those should stay with current names.

I am divided. Should we go for 

-----

(A)

just keep

* sys-whonix
* anon-whonix

Questions:

* What would happen if someone major upgrades (Whonix 14 -> 15) using salt? No issues?
* Template whonix-gw-14 and whonix-ws-14 would simply be no longer used? Salt would change anon-whonix and sys-whonix to whonix-(gw|ws)-15?

Advantages:

* easy to persist Tor entry guards (important anonymity providing feature)

Disadvantages:

* Doesn't allow parallel usage of two Whonix versions at once. For testers which are very important. Would be possible in theory but instructions would look very complicated / messy. (Instructions: "First install using salt. (Required due to #3447.) Then create sys-whonix-15, then somehow set salt settings, then set back the template of your sys-whonix-14 to whonix-gw-14.)
* Installation of newer Whonix version using salt would change (sys|anon)-whonix templates to whonix-(gw|ws) without asking the user.

-----
or
(B)

* sys-whonix-14
* anon-whonix-14

And later...

* sys-whonix-15
* anon-whonix-15

Disadvantages:

* not easily persisting Tor entry guards
* messy instructions for persisting Tor entry guards (Instructions: "let your sys-whonix-14 VM use whonix-gw-15 as its TemplateVM")
* Perhaps we tell users how to copy over their Tor state data folder (for Tor entry guards) and Tor config using qvm-copy-to-vm instead? (Instructions: "Start sys-whonix-15. Click nothing in anon-connection-wizard. Start sys-whonix-14. Run these qvm-copy-to-vm commands etc. for migration.")
* looks strange when someone does an in-place major (Whonix 14 -> 15) upgrade since the old names would persist (whonix-gw-14, whonix-ws-14, sys-whonix-14, anon-whonix-14)
  * --> Or should we just explain in in-place upgrade instructions to change TemplateBasedVM names and TemplateVM names? Is that even possible for templates installed using rpm?

Advantages:

* can provide easy, clean, clear call for testers blog posts
* easy new installation without persisting of data
* sys-whonix-15 cleanly uses whonix-gw-15 etc.

----

I think we should go for (B).

**Comment by marmarek** [comment]
(A)
> Questions:
> 
>     What would happen if someone major upgrades (Whonix 14 -> 15) using salt? No issues?
>     Template whonix-gw-14 and whonix-ws-14 would simply be no longer used? Salt would change anon-whonix and sys-whonix to whonix-(gw|ws)-15?

Depending how salt is written - currently it will not touch existing sys-whonix and anon-whonix, but it is trivial to change that. And IMO it is a good idea to adjust it.

> Doesn't allow parallel usage of two Whonix versions at once. For testers which are very important. Would be possible in theory but instructions would look very complicated / messy. (Instructions: "First install using salt. (Required due to #3447.) Then create sys-whonix-15, then somehow set salt settings, then set back the template of your sys-whonix-14 to whonix-gw-14.)

We can create yet another pillar for such cases ("whonix-vms-suffix" or such).

(B)

> And later...
> 
>     sys-whonix-15
>     anon-whonix-15

This option also means the need for manually changing netvm sys-whonix-14->sys-whonix-15 for all other qubes using whonix.

> Or should we just explain in in-place upgrade instructions to change TemplateBasedVM names and TemplateVM names? Is that even possible for templates installed using rpm?

It isn't possible to rename (in 4.0 not even for non-templates), but it is always possible to clone.

**Comment by adrelanos** [comment]
Marek Marczykowski-Górecki:
> (A)
>> Questions:
>>
>>     What would happen if someone major upgrades (Whonix 14 -> 15) using salt? No issues?
>>     Template whonix-gw-14 and whonix-ws-14 would simply be no longer used? Salt would change anon-whonix and sys-whonix to whonix-(gw|ws)-15?
> 
> Depending how salt is written - currently it will not touch existing sys-whonix and anon-whonix, but it is trivial to change that. And IMO it is a good idea to adjust it.

Ok.

>> Doesn't allow parallel usage of two Whonix versions at once. For testers which are very important. Would be possible in theory but instructions would look very complicated / messy. (Instructions: "First install using salt. (Required due to #3447.) Then create sys-whonix-15, then somehow set salt settings, then set back the template of your sys-whonix-14 to whonix-gw-14.)
> 
> We can create yet another pillar for such cases ("whonix-vms-suffix" or such).

Since we're scarce on developer time, and since I don't speak `salt`, I
suggest to go for the shortest / easiest implementation path. Also the
term the most easy to understand solution (including for me when getting
support requests) would be preferred.

> (B)
> 
>> And later...
>>
>>     sys-whonix-15
>>     anon-whonix-15
> 
> This option also means the need for manually changing netvm sys-whonix-14->sys-whonix-15 for all other qubes using whonix.

Understood. Makes sense. So this would need to be covered in upgrade
instructions.

Wondering which would be the last confusing outcome of the user... I
guess.... Can/should there be a salt command to change 14->15 netvm
setting with this as well? Perhaps a separate ticket?

I prefer (B).

Could you implement this please? Implementation details (A) vs (B), etc.
are of course up to you.

**Comment by adrelanos** [comment]
Related:
`whonix-ws-based VMs lack the anon-vm tag`
#3595

**Comment by adrelanos** [comment]
Do you think you could help with this one? @viq

**Comment by viq** [comment]
Yeah, I'll need to dig some into how qubes does things under the mask, but I should be able to help some here. But first, let me refresh the discussion a bit, to make sure I have the details right, and understand the approach.

1. Template versioning
For me it makes most sense to treat it like we do fedora, debian etc, so I have no issue with having `whonix-gw-14` next to `whonix-gw-15`, which also potentially makes it easier to test new versions.

2. AppVM versioning
Unless what lives on `/rw/` changes in significant ways (does it? I don't know enough about whonix currently, and what changes `14` brings) then I would keep with the theme of other AppVMs and not use versioning

3. Testing new whonix versions
I don't see much issue here, either clone or set up a fresh `sys-whonix-next` (and there could be states for that) and on a couple AppVMs set that as NetVM. As for what to use for updating machines through, I'd need to find where and how it's set, and again that could be automated - but we'd need to find a decent place and way to set the value of that variable for salt to use.

**Comment by adrelanos** [comment]
Thanks so much for helping out!

viq:
> Yeah, I'll need to dig some into how qubes does things under the mask, but I should be able to help some here. But first, let me refresh the discussion a bit, to make sure I have the details right, and understand the approach.

Great!

> 1. Template versioning
> For me it makes most sense to treat it like we do fedora, debian etc, so I have no issue with having `whonix-gw-14` next to `whonix-gw-15`, which also potentially makes it easier to test new versions.

Alright.

> 2. AppVM versioning
> Unless what lives on `/rw/` changes in significant ways (does it? I don't know enough about whonix currently, and what changes `14` brings) then I would keep with the theme of other AppVMs and not use versioning

Actually, it doesn't change in incompatible ways. So let's drop AppVM
versioning.

> 3. Testing new whonix versions
> I don't see much issue here, either clone or set up a fresh `sys-whonix-next` (and there could be states for that) and on a couple AppVMs set that as NetVM. As for what to use for updating machines through, I'd need to find where and how it's set, and again that could be automated - but we'd need to find a decent place and way to set the value of that variable for salt to use.

Ok.

**Comment by marmarek** [comment]
No, but some whonix-ws package should place a file in `/etc/qubes/post-install.d` that would call it. This way it will be done automatically during template installation and update, regardless of used method. No action for this needed from salt.
The only requirement is that qubes-core-admin-addon-whonix is installed.

**Comment by viq** [comment]
@marmarek you mean the file and package should be present in dom0, or in a template?

**Comment by marmarek** [comment]
`/etc/qubes/post-install.d/(something).sh` in the template, `qubes-core-admin-addon-whonix` in dom0.

**Comment by adrelanos** [comment]
The appropriate package would be https://github.com/Whonix/qubes-whonix.

**Comment by adrelanos** [comment]
https://github.com/QubesOS/qubes-core-agent-linux/tree/master/post-install.d

**Comment by adrelanos** [comment]
Just now added. Let me know if file name and contents looks alright.

https://github.com/Whonix/qubes-whonix/blob/master/etc/qubes/post-install.d/30-whonix-ws.sh

Looked easy and I like sorting the easy things asp.
Later some commentary can be added (low priority). If it looks alright, I'll upload and upgraded package.

**Comment by marmarek** [comment]
Should be `qvm-features-request whonix-ws=1` (`=` not space)

**Comment by adrelanos** [comment]
Marek Marczykowski-Górecki:
> Should be `qvm-features-request whonix-ws=1` (`=` not space)

Fixed.

**Comment by viq** [comment]
https://github.com/QubesOS/qubes-mgmt-salt-dom0-virtual-machines/pull/10 is my attempt at it

**Comment by adrelanos** [comment]
`fix, run "qvm-features-request whonix-ws=1" only on Whonix-Workstation`:
https://github.com/Whonix/qubes-whonix/commit/5d5aa4e8864cfef9a5108b5f178cdd28733d7990

Should further `qvm-features-request whonix-ws=1` be only run in TemplateVM? If so, I could add another test making sure it will only be run in TemplateVM. Or not required?

**Comment by marmarek** [comment]
> Should further qvm-features-request whonix-ws=1 be only run in TemplateVM?

Shouldn't matter. IMO better leave as is, let dom0 extension decide.

**Comment by adrelanos** [comment]
https://github.com/QubesOS/qubes-mgmt-salt-dom0-virtual-machines/pull/10 was merged.

Current status: Waiting for package upgrade.

**Comment by marmarek** [comment]
Package is already in current-testing (https://github.com/QubesOS/updates-status/issues/543), I've uploaded it just after merging it.
The missing part is versioned template(s) in templates-community. Should I build a new one, or move the one from unstable?

**Comment by adrelanos** [comment]
Do you think you could provide instructions on how to test this? @viq 

https://forums.whonix.org/t/qubes-whonix-14-saltstack-state-files-testers-wanted/5324

**Comment by adrelanos** [comment]
Does https://forums.whonix.org/t/qubes-whonix-14-saltstack-state-files-testers-wanted/5324/2 suffice?

**Comment by adrelanos** [comment]
Ready for testing, yes, see: https://forums.whonix.org/t/qubes-whonix-14-saltstack-state-files-testers-wanted

Do you have the same issue like me in https://github.com/QubesOS/qubes-issues/issues/4082?

Anyhow. I suggest to close this initial implementation ticket and to create new bugs for any issues.
