### ISSUE TITLE
please remove these unstable Whonix builds

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#3766]
Basically all except the `-14` versioned Whonix builds from `unstable` repository only.

I don't know how fedora repository management works. Please make sure to not remove the stable Whonix 13 templates.

R4:
qubes-template-whonix-gw-4.0.0-201802110155.noarch.rpm
qubes-template-whonix-ws-4.0.0-201802110435.noarch.rpm

R3.2:
qubes-template-whonix-gw-3.0.6-201608050041.noarch.rpm
qubes-template-whonix-gw-3.0.6-201612182342.noarch.rpm
qubes-template-whonix-gw-4.0.0-201801270115.noarch.rpm
qubes-template-whonix-ws-3.0.6-201608050146.noarch.rpm
qubes-template-whonix-ws-3.0.6-201612182205.noarch.rpm
qubes-template-whonix-ws-3.0.6-201612190628.noarch.rpm
qubes-template-whonix-ws-4.0.0-201801270342.noarch.rpm

**Comment by marmarek** [comment]
Done.
