### ISSUE TITLE
Qubes Manager shows only anon-whonix in list of available VMs

### ISSUE THREAD

**Issue by ThierryIT** [QubesOS/qubes-issues#3767]
### Qubes OS version:

4.0 r5

### Affected component(s): 

Qubes manager

---

### Steps to reproduce the behavior:

Starting Qubes.

### Expected behavior:

Qubes manager showing the list of VMs available

### Actual behavior:

Qubes manager only showing one VM: anon-whonix

### General notes:

All VMs are working if running through `Applications/Service: vm-toto/terminator (as exemple)`

---

**Comment by ThierryIT** [comment]
Yes sorry.
I do not see anymore my VMs in Qubes manager.
I only see the anon-whonix VM.
I should see arouind 10 VMs.

**Comment by ThierryIT** [comment]
![screenshot_2018-04-05_07-48-21](https://user-images.githubusercontent.com/31948106/38349220-ad0c4102-38ae-11e8-99aa-cdc6d4a47cac.PNG)

**Comment by marmarta** [comment]
That's curious! Does refreshing (with the button) help?

**Comment by ThierryIT** [comment]
no

**Comment by ThierryIT** [comment]
`Apr 06 15:23:48 dom0 qmemman.systemstate[1852]: stat: dom '4' act=2473437319 pref=325441126.40000004 last_target=247343
Apr 06 15:23:48 dom0 qmemman.systemstate[1852]: stat: dom '5' act=4194304000 pref=401213030.40000004 last_target=419430
Apr 06 15:23:48 dom0 qmemman.systemstate[1852]: stat: xenfree=83814416 memset_reqs=[('5', 2748509839), ('4', 2229434416
Apr 06 15:23:48 dom0 qmemman.systemstate[1852]: mem-set domain 5 to 2748509839
Apr 06 15:23:48 dom0 qmemman.systemstate[1852]: mem-set domain 4 to 2229434416
Apr 06 15:23:48 dom0 qmemman.systemstate[1852]: dom '5' still hold more memory than have assigned (3589615616 > 2748509
Apr 06 15:23:48 dom0 qmemman.systemstate[1852]: mem-set domain 0 to 9962705507
Apr 06 15:23:49 dom0 qubesd[1858]: unhandled exception while calling src=b'dom0' meth=b'admin.vm.volume.Info' dest=b'an
Apr 06 15:23:49 dom0 qubesd[1858]: Traceback (most recent call last):
Apr 06 15:23:49 dom0 qubesd[1858]:   File "/usr/lib/python3.5/site-packages/qubes/api/__init__.py", line 262, in respon
Apr 06 15:23:49 dom0 qubesd[1858]:     untrusted_payload=untrusted_payload)
Apr 06 15:23:49 dom0 qubesd[1858]:   File "/usr/lib64/python3.5/asyncio/futures.py", line 381, in __iter__
Apr 06 15:23:49 dom0 qubesd[1858]:     yield self  # This tells Task to wait for completion.
Apr 06 15:23:49 dom0 qubesd[1858]:   File "/usr/lib64/python3.5/asyncio/tasks.py", line 310, in _wakeup
Apr 06 15:23:49 dom0 qubesd[1858]:     future.result()
Apr 06 15:23:49 dom0 qubesd[1858]:   File "/usr/lib64/python3.5/asyncio/futures.py", line 294, in result
Apr 06 15:23:49 dom0 qubesd[1858]:     raise self._exception
Apr 06 15:23:49 dom0 qubesd[1858]:   File "/usr/lib64/python3.5/asyncio/tasks.py", line 240, in _step
Apr 06 15:23:49 dom0 qubesd[1858]:     result = coro.send(None)
Apr 06 15:23:49 dom0 qubesd[1858]:   File "/usr/lib64/python3.5/asyncio/coroutines.py", line 210, in coro
Apr 06 15:23:49 dom0 qubesd[1858]:     res = func(*args, **kw)
Apr 06 15:23:49 dom0 qubesd[1858]:   File "/usr/lib/python3.5/site-packages/qubes/api/admin.py", line 348, in vm_volume
Apr 06 15:23:49 dom0 qubesd[1858]:     for key in volume_properties)
Apr 06 15:23:49 dom0 qubesd[1858]:   File "/usr/lib/python3.5/site-packages/qubes/api/admin.py", line 348, in <genexpr>
Apr 06 15:23:49 dom0 qubesd[1858]:     for key in volume_properties)
Apr 06 15:23:49 dom0 qubesd[1858]:   File "/usr/lib/python3.5/site-packages/qubes/api/admin.py", line 343, in _serializ
Apr 06 15:23:49 dom0 qubesd[1858]:     value = value()
Apr 06 15:23:49 dom0 qubesd[1858]:   File "/usr/lib/python3.5/site-packages/qubes/storage/__init__.py", line 238, in is
Apr 06 15:23:49 dom0 qubesd[1858]:     raise self._not_implemented("is_outdated")
Apr 06 15:23:49 dom0 qubesd[1858]: NotImplementedError: Volume FileVolume has is_outdated() not implemented
Apr 06 16:00:01 dom0 CROND[5153]: (root) CMD (/usr/bin/qvm-sync-clock > /dev/null 2>&1 || true)
Apr 06 16:58:41 dom0 systemd[1]: Time has been changed
Apr 06 16:58:41 dom0 systemd[4615]: Time has been changed
Apr 06 16:58:41 dom0 dmeventd[1031]: dmeventd was idle for 6956 second(s), exiting.
Apr 06 16:58:41 dom0 dmeventd[1031]: dmeventd shutting down.
Apr 06 16:58:41 dom0 audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=dm-event comm="systemd
Apr 06 16:58:41 dom0 kernel: audit: type=1131 audit(1523023121.206:173): pid=1 uid=0 auid=4294967295 ses=4294967295 msg
Apr 06 17:00:01 dom0 CROND[5166]: (root) CMD (/usr/bin/qvm-sync-clock > /dev/null 2>&1 || true)
Apr 06 17:00:02 dom0 systemd[4615]: Time has been changed
Apr 06 17:00:02 dom0 systemd[1]: Time has been changed
Apr 06 17:01:01 dom0 CROND[5174]: (root) CMD (run-parts /etc/cron.hourly)
Apr 06 17:01:01 dom0 run-parts[5177]: (/etc/cron.hourly) starting 0anacron
Apr 06 17:01:01 dom0 anacron[5185]: Anacron started on 2018-04-06
Apr 06 17:01:01 dom0 run-parts[5187]: (/etc/cron.hourly) finished 0anacron
Apr 06 17:01:01 dom0 anacron[5185]: Will run job `cron.daily' in 48 min.
Apr 06 17:01:01 dom0 anacron[5185]: Jobs will be executed sequentially
Apr 06 17:01:37 dom0 audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=lvm2-lvmetad comm="sys
Apr 06 17:01:37 dom0 kernel: audit: type=1131 audit(1523023297.029:174): pid=1 uid=0 auid=4294967295 ses=4294967295 msg
Apr 06 17:39:16 dom0 audit[5277]: USER_AUTH pid=5277 uid=1000 auid=1000 ses=2 msg='op=PAM:unix_chkpwd acct="u08127" exe
Apr 06 17:39:16 dom0 kernel: audit: type=1100 audit(1523025556.332:175): pid=5277 uid=1000 auid=1000 ses=2 msg='op=PAM
`

**Comment by andrewdavidwong** [comment]
@marmarta: Please see #3804 for another detailed report of this issue.

**Comment by ThierryIT** [comment]
For information, I do have the same pb with NOT imported 3.2 VMs ....

**Comment by ThierryIT** [comment]
Working. Thx a lot.
