### ISSUE TITLE
i3-settings-qubes and qubes-i3status doesn't exist

### ISSUE THREAD

**Issue by Deedasmi** [QubesOS/qubes-issues#3769]
### Qubes OS version:

4

### Affected component(s): 

i3

---

### Steps to reproduce the behavior:

You can't install i3-settings-qubes or qubes-i3status as you could in 3.2

### General notes:

https://www.qubes-os.org/doc/i3/

Is out of date.

---

**Comment by marmarek** [comment]
What _exactly_ have you tried? I've just successfully installed i3-settings-qubes package on fresh Qubes 4.0 installation using qubes-dom0-update.

**Comment by Deedasmi** [comment]
I must have typod. I double checked, but didn't see anything wrong. My apologies!
