### ISSUE TITLE
Qube Manager empty list under attach block devices

### ISSUE THREAD

**Issue by awokd** [QubesOS/qubes-issues#3772]
### Qubes OS version:

R4.0

### Affected component(s): 

Qube Manager

---

### Steps to reproduce the behavior:

Attach a block device
In Qube Manager, go to Qube -> Attach/detach block device

### Expected behavior:

List of available block devices

### Actual behavior:

Empty list

### General notes:

`qvm-block` and the devices widget work as expected

---

**Comment by marmarek** [comment]
Fixed by https://github.com/QubesOS/qubes-manager/pull/87
