### ISSUE TITLE
qvm-sync-appmenus

### ISSUE THREAD

**Issue by SeVaS2016** [QubesOS/qubes-issues#3775]
### Qubes OS version: 

Qubes 4 release.
KDE

### Affected component(s): 

dom0.
kde.
Maybe fedora-26?

---

### Steps to reproduce the behavior:

```
qubesctl state.sls qvm.sys-net
qubesctl state.sls qvm.sys-firewall
nano /etc/qubes-rpc/policy/qubes.InputMouse (allow dom0>sys-net)
Gui Qubes Manager: Edit Apps>add/remove apps (No change in kde menu)
qvm-sync-appmenus
```

### Expected behavior:

sync Qubes-Manager with KDE application start menu.

### Actual behavior:

```
Traceback (most recent call last):
  File "/usr/bin/qvm-sync-appmenus", line 9, in <module>
    load_entry_point('qubesdesktop==4.0.12', 'console_scripts', 'qvm-sync-appmenus')()
  File "/usr/lib/python3.5/site-packages/qubesappmenus/receive.py", line 379, in main
    vm = args.domains[0]
IndexError: list index out of range
```

### General notes:

When changing the name of my sys-net, the usb-mouse stops working, even after updating the 
`/etc/qubes-rpc/policy/qubes.InputMouse`
and/or
`/etc/qubes-rpc/policy/qubes.InputMouse`
I deleted the sys-net and reinstalled via `sls.state`
After reinstalling sys-net(sys-usb) and sys-firewall, the 
`qvm-sync-appmenus`
fails. 

I can, of course, add programs manually, but not with qubes-manager or the qvm code. 

Error:

```
Traceback (most recent call last):
  File "/usr/bin/qvm-sync-appmenus", line 9, in <module>
    load_entry_point('qubesdesktop==4.0.12', 'console_scripts', 'qvm-sync-appmenus')()
  File "/usr/lib/python3.5/site-packages/qubesappmenus/receive.py", line 379, in main
    vm = args.domains[0]
IndexError: list index out of range
```

---

### Related issues:

Reference that may be applicable?
https://github.com/QubesOS/qubes-issues/issues/2364

**Comment by DeltaHeavy** [comment]
Reproduced under XFCE Qubes 4.0. This and other tools have insufficient Python exception handling. Let me know if I should open a new issue, but I've noticed that `qvm-filewall del` similarly errors with improper arguments.

A larger issue "Improve qubes python tools error/exception UI" or similar should probably be opened to umbrella these sorts of issues.

Thanks all!

**Comment by andrewdavidwong** [comment]
> Let me know if I should open a new issue, but I've noticed that `qvm-filewall del` similarly errors with improper arguments.
> 
> A larger issue "Improve qubes python tools error/exception UI" or similar should probably be opened to umbrella these sorts of issues.

I can't speak for how the devs will decide to handle it, but I say feel free to open such an issue.

**Comment by marmarek** [comment]
Fixed in the linked PR
