### ISSUE TITLE
R4.0: User 'qubes' is allowed to be created during install but doesn't work.

### ISSUE THREAD

**Issue by btric-development** [QubesOS/qubes-issues#3777]
### Qubes OS version:

R4.0

### Affected component(s):

Installation

---

### Steps to reproduce the behavior:

1. Install Qubes with defaults, specify the name of user to be created as 'qubes'.
2. After first reboot, on Qubes OS option selection screen, selecting Done produces an error that a user is needed.
3. After second reboot, at Qubes Login dialog, user 'qubes' plus the password you chose earlier cannot login.

### Expected behavior:

Probably the best behavior is to prevent a user account called 'qubes' from being created.  If there are any other reserved words that should be avoided, they should be added to a blacklist and not allowed as the username of the first user you install with.

### Actual behavior:

Unsure. It does not appear to create a user, yet it allows me to pass that part of installation.  Believe that it does create the user but is then overwritten with an internal 'qubes' user.  That makes sense but I selected qubes to be the install user because I then create additional users for access to the secure information stored in our Qubes laptop.

### General notes:

Thank you for such a great piece of software.

---

**Comment by marmarek** [comment]
In theory `qubes` user should be perfectly fine user name. Only group `qubes` is reserved, but those facts may be related. Can you extract installation logs from `/var/log/anaconda`? If you can't log in, try using recovery mode of installation image (available in non-uefi mode).

**Comment by btric-development** [comment]
Here you go.  I ran through the install with a different username and confirmed it worked fine.  Went back and tried `qubes` again, and it failed the same way.

First error occurs after reboot, after confirming default setup it says `[Dom0] Error: You must create a user account to create default VMs.`  Then I click OK to close that and it allows you to complete the initial setup phase, but it then boots into Qubes with "Other..." in the top of the login box and using username `qubes` with the password fails.

Attached are the contents of the `/var/log/anaconda` and `/root` folders, in case the `/root/anaconda-ks.cfg` file is helpful.  Dummy password used for the reproduction so nothing has been redacted.

[root-all.tar.gz](https://github.com/QubesOS/qubes-issues/files/1869847/root-all.tar.gz)
[var-log-anaconda-all.tar.gz](https://github.com/QubesOS/qubes-issues/files/1869848/var-log-anaconda-all.tar.gz)

**Comment by marmarek** [comment]
Oh, interesting line:
```
20:24:04,107 INFO anaconda: Creating users
20:24:04,108 INFO anaconda: user account root setup with no password
20:24:04,109 INFO anaconda: user account root locked
20:24:04,777 WARN anaconda: User qubes already exists
```

**Comment by Kenny606** [comment]
This is closed so not sure anyone will see it but FYI Identical behavior on current 4.1 release with username "nobody".

I tried two installs back to back on the same machine with username "nobody" and seen the exact same behavior.
Tried a third with a different name and worked perfectly.

**Comment by unman** [comment]
On Mon, Apr 18, 2022 at 11:14:03AM -0700, Kenny606 wrote:
> This is closed so not sure anyone will see it but FYI Identical behavior on current 4.1 release with username "nobody".
> 
> I tried two installs back to back on the same machine with username "nobody" and seen the exact same behavior.
> Tried a third with a different name and worked perfectly.
> 

I'm sure that this is referenced in another issue - you cant use *any*
reserved system name.
Check out /etc/passwd and you will see many such names, usually with
shell of /sbin/nologin.
