### ISSUE TITLE
Sluggishness/unresponsiveness in domU and dom0 when VM runs out of free memory

### ISSUE THREAD

**Issue by 0spinboson** [QubesOS/qubes-issues#3780]
### Qubes OS version:
R4.0

---

### Steps to reproduce the behavior:

Assign a given amount of memory to a VM (say 4GB), make the VM run out of memory (youtube videos, interactive/heavy websites), get sluggishness / stutter both in domU and dom0.

### Expected behavior:

Graceful handling of this, no sluggishness/stutter bleeding into dom0.

### Actual behavior:

VM becomes sluggish in a way that I never ran into on R3.2 / on R4 roughly prior to when the Spectre/MD stuff 'happened'. More importantly, dom0 also becomes intermittently unresponsive, which should just not happen. Video playback also 

### General notes:

Ryzen 5 1600, 32GB ram. dom0 kernel 4.15.6

---

**Comment by lunarthegrey** [comment]
What is your system load like when you check in dom0 (when this happens)?

**Comment by lunarthegrey** [comment]
Have you checked logs like /var/log/messages, syslog on the VM? Anything in /var/log/xen/console/hypervisor.log in dom0?

**Comment by lunarthegrey** [comment]
Maybe @marmarek would know how to debug this better.

**Comment by 0spinboson** [comment]
seems to have been due to hardware acting up.
