### ISSUE TITLE
Update qubes-desktop-linux-i3 package to version 4.15

### ISSUE THREAD

**Issue by anadahz** [QubesOS/qubes-issues#3781]
### Affected component(s): qubes-desktop-linux-i3

The current i3 package version in Qubes R4.0 is too old (version 4.12), I prepared a patch and bumped up to the newer and recommended i3 version [4.15](https://i3wm.org/downloads/RELEASE-NOTES-4.15.txt).

I'm running into a compilation error so I'm not sure if I miss some dependencies or anything, below the error excerpt of `make rpms`:
```
  CC       src/i3-handlers.o
../../i3-4.15/src/handlers.c: In function 'handle_client_message':
../../i3-4.15/src/handlers.c:818:31: error: 'A__NET_REQUEST_FRAME_EXTENTS' undeclared (first use in this function)
     } else if (event->type == A__NET_REQUEST_FRAME_EXTENTS) {
                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../i3-4.15/src/handlers.c:818:31: note: each undeclared identifier is reported only once for each function it appears in
../../i3-4.15/src/handlers.c:844:13: error: 'A__NET_FRAME_EXTENTS' undeclared (first use in this function); did you mean 'A__NET_REQUEST_FRAME_EXTENTS'?
             A__NET_FRAME_EXTENTS,
             ^~~~~~~~~~~~~~~~~~~~
             A__NET_REQUEST_FRAME_EXTENTS
../../i3-4.15/src/handlers.c: In function 'handle_motif_hints_change':
../../i3-4.15/src/handlers.c:1309:87: error: 'A__MOTIF_WM_HINTS' undeclared (first use in this function); did you mean 'XCB_ATOM_WM_HINTS'?
                                                                        false, window, A__MOTIF_WM_HINTS, XCB_GET_PROPERTY_TYPE_ANY, 0, 5 * sizeof(uint64_t)),
                                                                                       ^~~~~~~~~~~~~~~~~
                                                                                       XCB_ATOM_WM_HINTS
../../i3-4.15/src/handlers.c: In function 'property_handlers_init':
../../i3-4.15/src/handlers.c:1452:34: error: 'A__MOTIF_WM_HINTS' undeclared (first use in this function); did you mean 'XCB_ATOM_WM_HINTS'?
     property_handlers[10].atom = A__MOTIF_WM_HINTS;
                                  ^~~~~~~~~~~~~~~~~
                                  XCB_ATOM_WM_HINTS
make[3]: *** [Makefile:2281: src/i3-handlers.o] Error 1
```
The changes can be found in the following repository:
https://github.com/anadahz/qubes-desktop-linux-i3/tree/update/i3-4.15

Happy to provide any further details and bring the update to the latest i3 version forward.

**Comment by marmarek** [comment]
Building i3-4.15 package from Fedora 26, on Fedora 25 (which should match what we have in dom0) works:
```
mock  -r fedora-25-x86_64 --rebuild i3-4.15-1.fc26.src.rpm
```
You may want to look at that package. On first sight looks pretty similar, but there may be some details.

Also note that just `make rpms` do not update dependencies. `rpmbuild` should fail if some are missing, but will not install/update them for you. You may want to either build src.rpm (`make srpms`) and use mock (see above), or use qubes-builder.

**Comment by anadahz** [comment]
The issue was on the rebase of the qubes patch on the newer i3 version.
Fixed and opened PR: https://github.com/QubesOS/qubes-desktop-linux-i3/pull/13

Feel free to close this issue.
