### ISSUE TITLE
Dual-cpu computer crashes

### ISSUE THREAD

**Issue by pascal-mignot-urca** [QubesOS/qubes-issues#3787]
### Qubes OS version: 
R4.0 (from iso downloaded 4 april 2018)

### Affected component(s): 
- can't install QuBes OS
- can't boot QuBes OS 

### Steps to reproduce the behavior:
Try installing QuBes 4.0 on a Dell Precision T7610 workstation (2 x Xeon processors)

### Expected behavior:
it should install and boot.

### Actual behavior:
Xen boot is ok. It detects 8 vcpus.
vmlinuz boot crashes after the trace: "Installing Xen timer for CPU 4"

### General notes:
It seems to be related to management of the vcpus on the second cpu.
Adding dom0_max_vcpus=4 as additional Xen boot option prevents the crashes.
OS can be then installed and launched if this options is set at boot time.
Unfortunately, it also uses half of the computer resources.

### Related issues:
More problems after install (VMs failed to start) but can't relate them to dual cpu for now.

**Comment by marmarek** [comment]
> Unfortunately, it also uses half of the computer resources.

This is fortunately not true. Dom0 is only small part of the system and actually it may be good idea to limit its resources.

> vmlinuz boot crashes after the trace: "Installing Xen timer for CPU 4"

Can you provide more details about the crash?

**Comment by pascal-mignot-urca** [comment]
Hi Marek,I can't see how I can provide more information, since the crash prevent me to access to the logs. If there is one, please enlight me. Limits of dom0: since this option is passed at the xen hypervisor boot, I understood it as a limitation of the hypervisor resources. But you surely know better than me.Thanks,PascalLe 4 avr. 2018 9:52 PM, Marek Marczykowski-Górecki <notifications@github.com> a écrit :
Unfortunately, it also uses half of the computer resources.

This is fortunately not true. Dom0 is only small part of the system and actually it may be good idea to limit its resources.

vmlinuz boot crashes after the trace: "Installing Xen timer for CPU 4"

Can you provide more details about the crash?

**Comment by marmarek** [comment]
Option `dom0_max_vcpus=4` is only about dom0.

At this early stage, the crash message woudn't get into logs anyway. If you have serial console, you can try this (add `console=com1` to Xen). If not, if you see it on screen, you can take a photo of it...

**Comment by philrdubois** [comment]
I just opened #3788 requesting to replace the kernel on the iso to 4.15; I also have a Dell Precision T workstation (1 cpu, 8 cores) that has this same issue and I found out last summer that it was a bug in the kernel, which has been repaired in 4.15. 

Apologies if I am incorrect in believing these are related. I will be attempting to add dom0_max_vcpus=4 at boot in the morning to see if they are related.

**Comment by pascal-mignot-urca** [comment]
Be sure to place this option just after the xen kernel: it's a xen boot option and not a linux one.

**Comment by philrdubois** [comment]
Strangely enough, I get different errors when booting from BIOS vs EFI. In EFI, I get errors similar to how you describe and cannot get to the linux kernel, however I cannot modify the boot commands (as is expected according to Xen documentation). In BIOS mode, I do not need to use dom0_max_vcpus=4 to get past Xen and into the kernel, where I get my kernel panic.

Due to this, our issues seem to be unrelated.
