### ISSUE TITLE
Option to filter or sort HCL page entries by Qubes release

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#3795]
A user has requested that we add an option to the [HCL page](https://www.qubes-os.org/hcl/) that allows one to view hardware entries according to the Qubes OS release for which the report was generated. One possibility is to create a feature that filters out all releases except one. Then, a visitor could click a button for a particular release to see only entries for that release. Another possibility is to make the "Qubes" column sortable so that all the entries from one release are grouped together. (However, they would still be segregated by platform type.)

CC: @zrubi, @tasket

**Comment by tasket** [comment]
I wondered if we should do this... the table is getting rather large and harder to browse.

My first inclination is to highlight or grey-out rows depending on the Qubes version. This sidesteps problems with sorting models that have multiple version entries and whatnot. It also keeps the page more coherent as nothing is shifting around. Lastly, I think it can be done without adding stuff like 3rd party jquery plugins.

**Comment by andrewdavidwong** [comment]
I would be fine with that approach. I wonder, though, whether it provides the reader much benefit beyond what can be achieved by using the built-in browser page search functionality to highlight every occurrence of the desired version number.

**Comment by Zrubi** [comment]
I think the current design can only be improved using:
- database (like) backend
- javascript table filtering: datatables.net

I would go with the javascrip direction  - if we really need any better than the current one.

**Comment by salgo** [comment]
Apologies for the duplicate issue. I’ll do this then as clearly I’m not alone in thinking it’s a good idea :)

**Comment by andrewdavidwong** [comment]
> Apologies for the duplicate issue. I’ll do this then as clearly I’m not alone in thinking it’s a good idea :)

No worries; thanks for doing it!

**Comment by andrewdavidwong** [comment]
I've opened two PRs to make the table sortable (https://github.com/QubesOS/qubesos.github.io/pull/150 and https://github.com/QubesOS/qubes-doc/pull/1097). However, some rows in the table break when sorted. This image shows exactly what I mean (warning, large image):

[hcl-sorted-broken.png](https://user-images.githubusercontent.com/10417133/100004123-e3bd6680-2d7b-11eb-8cb3-e67a5c1e98c0.png)

The problem seems to affect mainly the old rows. If anyone can figure out how fix this or can provide sorting code that works better with this table, please let me know.

**Comment by andrewdavidwong** [comment]
@SvenSemmler: FYI, the HCL tables now support sorting by column. I found and fixed a couple entries that contain superfluous single quotation marks, which broke this sorting (https://github.com/QubesOS/qubes-hcl/commit/e6824dff0afffaae854fa72d0f0d873cab70719b). Just wanted to alert you to this for future HCL reports.

**Comment by SvenSemmler** [comment]
> the HCL tables now support sorting by column

Seen it today: awesome!

> found and fixed a couple entries that contain superfluous single 
> quotation marks, which broke this sorting

Thank you!

> Just wanted to alert you to this for future HCL reports.

I'll clean up the entire HCL base and prepare a PR. Unfortunately I 
somehow lost (almost) all rights on GitHub. Once more I can't see the 
error logs and can't even 'testdeploy'

For this task both would be very useful.

**Comment by andrewdavidwong** [comment]
> Unfortunately I somehow lost (almost) all rights on GitHub. Once more I can't see the error logs and can't even 'testdeploy' For this task both would be very useful.

@fepitre, might you be able to help with this?
