### ISSUE TITLE
Dom0 should not have USB drivers

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#3801]
### Qubes OS version:

R4.0

### Affected component(s): 

Dom0 Kernel

---

### Steps to reproduce the behavior:

Run `find /lib/modules/4.14.18-1.pvops.qubes.x86_64/kernel/drivers/usb`

### Expected behavior:

No output or an error that the directory does not exist

### Actual behavior:

Lots of output

### General notes:

Dom0 does not need USB drivers, and they increase attack surface in the event of a misconfiguration.

---

**Comment by marmarek** [comment]
> Dom0 does not need USB drivers, and they increase attack surface in the event of a misconfiguration.

This is not true. Using USB VM is optional. Also Anti-Evil-Maid, or simply having the system installed on USB disk require USB in dom0.

**Comment by DemiMarie** [comment]
@marmarek I did not think of that configuration.
