### ISSUE TITLE
Bug in qubes-input-sender  

### ISSUE THREAD

**Issue by toxub23** [QubesOS/qubes-issues#3805]
### Actual behavior:

Logs from sys-usb
https://0bin.net/paste/B+3I3fbBsrNCHzFu#a97f-dAtLaVPeUlyqHNGW9a/0PqUKusDHTqEWrRJE2z 

### General notes:
The problem is that after connecting the mouse to the computer, the mouse can run for 10 minutes, then the system disconnects it from sys-usb, and then connects it again without any user interaction.
The second problem is that after connecting the keyboard via usb to sys-usb the keyboard does not work, only the backlight of the keyboard works, but the keyboard itself does not work. No buttons were detected in the system, therefore you can not write on it.

**Comment by marmarek** [comment]
As for the keyboard, it is intentional, see here: https://www.qubes-os.org/doc/usb/#how-to-use-a-usb-keyboard

**Comment by toxub23** [comment]
I do not mean that I have a desktop computer and this is how it happens. My point is that I have a laptop, where Qubes OS works rather normally and only after connecting a USB keyboard to sys-usb to my laptop the problem starts because the keyboard is not working and I can not use it. I can only use the keyboard built into the laptop.

**Comment by toxub23** [comment]
There is nothing explained there on this subject. I am talking about connecting the keyboard while the system is running, I am not talking about connecting the keyboard during system startup.

**Comment by taradiddles** [comment]
> I am talking about connecting the keyboard while the system is running, I am not talking about connecting the keyboard during system startup.

The document Marek linked to applies to both cases. It's a matter of permissions (ie. allowing the use of the USB keyboard), so it doesn't matter whether the keyboard is already plugged during boot or if you plug it later.

As for your first problem (disconnecting and reconnecting) I noticed that too twice when the system is under heavy I/O - but I couldn't reproduce the problem.

**Comment by toxub23** [comment]
@taradiddles Thank you very much. Your help was very helpful. Thanks to you I understand the problem with the keyboard :) As for the mouse, this is what happens to me in the normal use of the system. I do not have the latest and most powerful laptop in the world but with the usual browsing of the internet, eg in the default untrusted vm machine, there is such a problem. I have Intel Core I5-3320M, 8GB RAM and SSD.
