### ISSUE TITLE
No `/tmp` mount point in Debian 9

### ISSUE THREAD

**Issue by SkypLabs** [QubesOS/qubes-issues#3808]
### Qubes OS version:

Qubes OS R4.0

### Affected component(s): 

* Debian 9 template
* AppVM using Debian 9 as template
* Templates based on Debian 9

---

### Steps to reproduce the behavior:

Installing Qubes OS R4.0 with the built-in Debian 9 template.

### Expected behavior:

A `/tmp` mount point should be present when using the Debian 9 template (directly or indirectly).

### Actual behavior:

There is no `/tmp` mount point:

```
user@personal-dev:~$ mount | grep /tmp
user@personal-dev:~$
```

On a Fedora-base AppVM:

```
[user@disp1932 ~]$ mount | grep /tmp
tmpfs on /tmp type tmpfs (rw,size=1048576k,nr_inodes=40077)
[user@disp1932 ~]$
```

### General notes:

---

**Comment by marmarek** [comment]
I don't think it is a bug. It is just a difference between Fedora and Debian.
