### ISSUE TITLE
R4.0 laptop trackpad not enabled in installer, OK after first boot

### ISSUE THREAD

**Issue by trueriver** [QubesOS/qubes-issues#3816]
### Qubes OS version:

R4.0

### Affected component(s): 

Installer, trackpad

---

### Steps to reproduce the behavior:

Download r4.0 ISO, dd to USB
Boot from USB on Asus laptop, c Nov 2015

### Expected behavior:

Expected trackpad to work

### Actual behavior:

Trackpad ignored, mouse pointer stuck in centre of screen - did not move between X starting and reboot

### General notes:

Workaround: 
use Tab to select fields and shift-tab to go back to previous field.
keyboard worked OK.
Reboot when prompted
Trackpad works from first boot onwards

---

### Related issues:

NB this is different behaviour to #3784 which reported a Macbook Pro, where neither keyboard nor trackpad worked. At least mine was usable if clunky!

I have been using Qubes since the install and am not sure if the relevant logs will still be available. If someone tells me which log files and how to access them I will be glad to assist further.

Also I am not sure which VM will see my trackpad using lspci: be glad to post the relevant output if I know which one might help.

**Comment by lunarthegrey** [comment]
Specific model of the Asus laptop might help others troubleshoot as well.

**Comment by trueriver** [comment]
Quite so - that info would help me too ;)

Unfortunately I do not know the model name - it a laptop I got second hand.

Nor am I sure how to find out. It had been wiped when I got it and a
generic version of Win 10 (ie with no apparent Asus software/manuals/etc).
Win has been totally replaced by Qubes now, of course.

More relevant for this specific point would be to identify the trackpad. I
Would be grateful for tips on how to do this, either from within Qubes or
from a Mint live disk

**Comment by trueriver** [comment]
From the dmidecode file the BIOS Information tells me the BIOS version is for UX360CA.202 released 17 Feb 2016 (so my laptop is either more recent than suspected, or its previous owner reflashed its BIOS).

The laptop product name is UX360CA version 1.0, manufacturer ASUSTek COMPUTER INC.

And I now have the serial number which I didn't know before... so thanks for the heads up on dmidecode :)

Do feel free to ask if any of the other dmidecode info would help with this bug.
