### ISSUE TITLE
Progress bar erratic immediately after first boot

### ISSUE THREAD

**Issue by trueriver** [QubesOS/qubes-issues#3817]
### Qubes OS version:

R4.0

### Affected component(s): 

The component that sets up and configures selected VMs on first boot

---

### Steps to reproduce the behavior:

Follow usual install procedure on Asus laptop c Nov 2015. When asked which VMs to initialise, select Fedora 26, Debian 9, and all the sys-* options. 

Either select the whonix VMs as well, or leave them out (same behaviour both ways)

### Expected behavior:

When Qubes is initialising selected VMs, a progress bar shows a short bar osciallating to and fro. I expected this to continue moving throughout the process

### Actual behavior:

The slider stopped moving after 2-3 minutes, even though the initialisation took another 10-20 mins to complete. The only evidence of progress was that the name of the VM occasionally changed

### General notes:

This behaviour is potentially worrying to a newcomer who may assume the process has crashed.

Workaround is to tell users this may happen and encourage the to show patience if the GUI apparently freezes. Wait for the button to appear to complete initialisation.

NB: R3.2 worked fine on the same hardware, so this bug has been introduced in R4.0

If there will be any relevant logs please specify which files on whick VM(s) you would like to see

regards

---

**Comment by trueriver** [comment]
Not sure if it is relevant but for info I did NOT ask the installer to encrypt my files

**Comment by lunarthegrey** [comment]
I've experienced the same when installing the first 4.0 stable release.
