### ISSUE TITLE
HVM stub-domain occasionally runs out of memory

### ISSUE THREAD

**Issue by eug48** [QubesOS/qubes-issues#3821]
### Qubes OS version:

R4.0

### Affected component(s): 

HVM stub domains

---

### Steps to reproduce the behavior:

Run Windows 10 HVM, giving it 16GB of RAM (out of 32GB).
The VM occasionally fails when there's relatively high memory/cpu usage.

### Expected behavior:

VM runs without interruption

### Actual behavior:

The Windows 10 VM fails due to the stub-domain OOM killer killing qemu. 
Logs here: https://gist.github.com/eug48/472ede7f275bd1ccf4fb9bf1f6157b8d

### General notes:

---

**Comment by eug48** [comment]
It hope that increasing the stubdom's memory could mitigate this but I can't find how to do this even though these two patches suggest it is possible:

https://github.com/QubesOS/qubes-core-libvirt/blob/385f8f3f432fcdf6aacdbd8c11d62635cea10c2f/0020-libxl-add-support-for-stubdom_mem-option.patch
https://github.com/QubesOS/qubes-vmm-xen/blob/ab932b916883893f5c105b5338686c3856858fd7/patch-stubdom-linux-config-stubdom-mem.patch

Any help would be much appreciated.

**Comment by eug48** [comment]
I've figured it out: to set the stubdom's memory to ~500MB run `qvm-prefs Win10 stubdom_mem 500`. The setting can be verified through `xl list`.

This seems to have helped as I can now install the latest Windows 10 Feature Update.

**Comment by ben-grande** [comment]
Xentop also doesn't know, so I guess Xen doesn't know. The domid 2 is sys-net-dm: 

```python3
>>> dm = app.vmm.xc.domain_getinfo(2, 1)[0]
>>> {i: app.vmm.xs.read("", "/local/domain/2/memory/" + i) for i in app.vmm.xs.ls("", "/local/domain/2/memory")}
{'static-max': b'147456', 'target': b'147456', 'videoram': b'0'}
>>> dm['maxmem_kb'], dm['mem_kb']
(148480, 147456)
```

**Comment by ben-grande** [comment]
> The VM occasionally fails when there's relatively high memory/cpu usage.

What does it mean the VM fails? Does it fail boot during some update? Does it fail minutes after boot? What message do you see? Can you share detailed steps to reproduce the issue? Was there a notification sent? I am not sure we can get the data live, but when it fails and we receive a signal, there could be a notification informing that increasing `stubdom_mem` is recommended.
