### ISSUE TITLE
qubes-vm-settings can't be run (R4.0)

### ISSUE THREAD

**Issue by 0spinboson** [QubesOS/qubes-issues#3822]
### Qubes OS version:

R4.0 + updates-testing

### Affected component(s): 

qubes-vm-settings

---

### Steps to reproduce the behavior:

try to run Qube Settings

### Expected behavior:

Opens settings window

### Actual behavior:

Error: empty response from qubesd.

Journalctl: [exc.txt](https://github.com/QubesOS/qubes-issues/files/1911754/exc.txt)

**Comment by andrewdavidwong** [comment]
Fixed by @marmarek in https://github.com/marmarek/qubes-core-admin/commit/f9e34eff516825d37492df5f9518cf5e4cf48571
