### ISSUE TITLE
Macbook Pro (Retina, 13-inch, Early 2015): QubesOS R4.0 installer can't swich back to GUI via CTRL + ALT + F{N} (F7? F4?)

### ISSUE THREAD

**Issue by pruflyos** [QubesOS/qubes-issues#3824]
### Qubes OS version:

R4.0

### Affected component(s): 

Qubes OS R4.0 Installer

---

### Steps to reproduce the behavior:

- switch to another console while the Qubes 4.0 installer is running via CTRL + ALT + F1

### Expected behavior:

- There should way to switch back to the graphical installer. E.g. via CTRL + ALT + F7

### Actual behavior:

You can't switch back to the graphical (GUI) installer. I tried all consoles from F1 to F12 and none of them contains the GUI. It's strange that CTRL + ALT + F4 does nothing, while F3 and F5 have individual command promts. Might be that the GUI runs on console 4 but switching back to it doesn't work?

### General notes:

---

**Comment by marmarek** [comment]
AFAIR installer should be on tty6. Do you see X server process running on `ps aux` output? Any error on tty1, from where it is started?

**Comment by pruflyos** [comment]
Yes, X server is still running:
```
$ ps aux | grep Xorg
root  1256  0.5  0.1  246932  29396  tty6  Ssl+  01:00  0:00  /usr/libexec/Xorg -br -logfile /tmp/X.log :1 vt6 -s 1440 -ac -nolisten tcp -dpi 96 -noreset
```
There's no error message in the logfile at `/tmp/X.log`. The last line just says:
`AIGLX: Suspending AIGLX clients for VT switch`
