### ISSUE TITLE
The 3.2 qubes-dom0-current repo is not reachable

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#3827]
### Qubes OS version:

`R3.2`

### Affected component(s): 

The `qubes-dom0-current` repo (and probably others)

---

### Steps to reproduce the behavior:

Attempt to update dom0 from Qubes 3.2 within the past 24 hours of this report.

Tried:
 - https://yum.qubes-os.org/r$releasever/current/dom0/fc23 via ten different Tor circuits
 - https://yum.qubes-os.org/r$releasever/current/dom0/fc23 via clearnet
 - http://yum.qubes-os.org/r$releasever/current/dom0/fc23 via Tor
 - http://yum.qubes-os.org/r$releasever/current/dom0/fc23 via clearnet
 - http://yum.qubesos4rrrrz6n4.onion/r$releasever/current/dom0/fc23 via Tor

### Expected behavior:

Download updates or receive report that no updates are available without an error.

### Actual behavior:

```
Failed to synchronize cache for repo 'qubes-dom0-current', disabling.
No new updates available
```

### General notes:

It's normal for `Failed to synchronize cache` to happen occasionally (i.e., for a few bad Tor exit nodes or temporary network or server problems), but not consistently across many different Tor circuits and clearnet over the course of a whole day. This suggests some problem with the server hosting the repo.

**Comment by andrewdavidwong** [comment]
This is happening again.

**Comment by marmarek** [comment]
Fixed.
