### ISSUE TITLE
Can't migrate qube with custom conf file from 3.2 to 4.0

### ISSUE THREAD

**Issue by orwinslanner** [QubesOS/qubes-issues#3828]
The --custom-config option has been removed from qvm-start. This is a regression from 3.2, if there's nothing to replace it.

I have a standalone VM, without Qubes tools installed, that works fine on 3.2. I'm trying to migrate it to 4.0. I use a custom conf file with some sections like

    <disk type='block' device='disk'>
      <driver name='phy'/>
      <source dev='/var/lib/qubes/appvms/myvm/root.img'/>
      <target dev='xvda' bus='xen'/>
    </disk>

    <disk type='block' device='disk'>
      <driver name='phy'/>
      <source dev='/var/lib/qubes/appvms/myvm/myvm-1.img'/>
      <target dev='xvdb' bus='xen'/>
    </disk>

    <disk type='block' device='disk'>
      <driver name='phy'/>
      <source dev='/var/lib/qubes/appvms/myvm/myvm-2.img'/>
      <target dev='xvdd' bus='xen'/>
      <readonly/>
    </disk>

Backup/restore doesn't get myvm-1.img and myvm-2.img and my custom conf file, but that's ok, I can copy them manually. But the problem is the new LVM storage and the rewritten qvm tools; there doesn't appear to be a way to attach the .img files to the VM. Installing Qubes tools isn't an option, and the two .img files are essential for this VM.

**Comment by ctramnitz** [comment]
What about configuration statements that do not exist in libvirt but in xl or that are not implemented in libvirt (yet)?
Just thinking of xl's acpi_firmware and/or smbios_firmware.
There are similar directives available in libvirt but this cannot be mapped 1:1 (i.e. virsh domxml-from-native discards them). And even when stated in libvirt xml config syntax manually (i.e. sysinfo), they are not passed to the xl driver.

On vanilla Xen I'd work-around those by pushing this into Xenstore manually (at least for acpi this should work, not sure about smbios). However, the way domUs are started in Qubes this doesn't work (needs to be updated before the domU starts, there are no hooks).

**Comment by marmarek** [comment]
> What about configuration statements that do not exist in libvirt but in xl or that are not implemented in libvirt (yet)?

The most elegant way: get them supported by libvirt...

> However, the way domUs are started in Qubes this doesn't work (needs to be updated before the domU starts, there are no hooks).

There are. You can write [core-admin extension](https://dev.qubes-os.org/projects/core-admin/en/latest/qubes-ext.html) that handle [domain-spawn event](https://dev.qubes-os.org/projects/core-admin/en/latest/qubes-vm/qubesvm.html#event-domain-spawn) - it's called after domain is created, but while it's still paused. You can see example extensions linked above. It is possible to add extensions from outside of core-admin repository, you just need to advertise it with `qubes.ext` entry point in `setup.py`. For a more complete example of "external" extension, see [gui-daemon's setup.py](https://github.com/QubesOS/qubes-gui-daemon/blob/master/setup.py) and [the actual extension](https://github.com/QubesOS/qubes-gui-daemon/blob/master/qubesguidaemon/mic.py).
