### ISSUE TITLE
Current testing updates 4.0 broke xfce menu qube settings & qube manager

### ISSUE THREAD

**Issue by pugege** [QubesOS/qubes-issues#3831]
### Qubes OS version:

4.0

### Affected component(s): 

xfce menu qube settings all appvms
qube manager

---

### Steps to reproduce the behavior:

select menu qube settings any appvm
execute qube manager

### Expected behavior:

open appvm qube setting window with menu
open qube manager, display appvm list

### Actual behavior:

no qube setting window displayed; " Houston, we have a problem........"
no appvm list qube manager; " Houston, we have a problem.........."

### General notes:

---

**Comment by 0spinboson** [comment]
same: https://github.com/QubesOS/qubes-issues/issues/3822

**Comment by andrewdavidwong** [comment]
Duplicate of #3822
