### ISSUE TITLE
Current testing updates 4.0 broke xfce menu settings & qube manager

### ISSUE THREAD

**Issue by pugege** [QubesOS/qubes-issues#3832]
### Qubes OS version:

4.0

### Affected component(s): 

qube settings xfce menu all appvms
qube manager

---

### Steps to reproduce the behavior:

select qube settings xfce menu any appvm
execute qube manager

### Expected behavior:

selecting qube settings xfce menu creates functional window
executing qube manager creates appvm list

### Actual behavior:

qube settings menu selection in all appvms creates only " Houston, we have a problem......"
qube manager creates window with no appvm list and " Houston, we have a problem......."

### General notes:

---

**Comment by marmarek** [comment]
You've already reported this as #3831

**Comment by andrewdavidwong** [comment]
Duplicate of #3831
