### ISSUE TITLE
qubes-core-agent 3.2.28-1+deb9u1 is trying to overwrite '/etc/dconf/profile/user', which is also in package kali-defaults 2018.2.1

### ISSUE THREAD

**Issue by burghardt** [QubesOS/qubes-issues#3834]
### Qubes OS version:

Qubes release 3.2 (R3.2)

### Affected component(s): 

qubes-core-agent

---

### Steps to reproduce the behavior:

1. Try to upgrade Kali Linux domU.
2. Upgrade of qubes-core-agent from version 3.2.25-1+deb9u1 to 3.2.28-1+deb9u1 fails.

### Expected behavior:

Package qubes-core-agent is upgraded.

### Actual behavior:

Package qubes-core-agent fails to be upgraded. Details below.

```
The following packages will be upgraded:
   qubes-core-agent (3.2.25-1+deb9u1 => 3.2.28-1+deb9u1)
1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
21 not fully installed or removed.
Need to get 0 B/93.2 kB of archives.
After this operation, 21.5 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Reading changelogs... Done
dpkg-preconfigure: unable to re-open stdin: No such file or directory
(Reading database ... 286780 files and directories currently installed.)
Preparing to unpack .../qubes-core-agent_3.2.28-1+deb9u1_amd64.deb ...
Unpacking qubes-core-agent (3.2.28-1+deb9u1) over (3.2.25-1+deb9u1) ...
dpkg: error processing archive /var/cache/apt/archives/qubes-core-agent_3.2.28-1+deb9u1_amd64.d
 trying to overwrite '/etc/dconf/profile/user', which is also in package kali-defaults 2018.2.1
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Errors were encountered while processing:
 /var/cache/apt/archives/qubes-core-agent_3.2.28-1+deb9u1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
Done.
Press Enter to shutdown the template, or Ctrl-C to just close this window
```

### General notes:

None.

---

### Related issues:

Issue #3761 looks related.

**Comment by marmarek** [comment]
In standard Debian no package owns `/etc/dconf/profile/user`, but we need this file (likely with the same content as in `kali-defaults`), this is why qubes-core-agent contains the file.
@unman any idea how to solve this? Some config-package-dev trick?

**Comment by h01ger** [comment]
On Thu, Apr 19, 2018 at 11:02:39AM +0000, Marek Marczykowski-Górecki wrote:
> In standard Debian no package owns `/etc/dconf/profile/user`, but we need this file (likely with the same content as in `kali-defaults`), this is why qubes-core-agent contains the file.
> @unman any idea how to solve this? Some config-package-dev trick?

dpkg-divert might be the right answer, or just creating the file in
postinst, if it doesnt exist.

its a bit tricky because kali-dafaults and qubes-core-agent come from
different repos, so in theory lots of things could go/be wrong.

but then I think dpkg-divert was exactly designed for this, move
existing versions of a file out of the way and provide with ones one
version.

probably the kali-default maintainers could use dpkg-divert as well and
should be included in this discussion.


-- 
cheers,
	Holger
