### ISSUE TITLE
qubes applet's Run Terminal doesn't work

### ISSUE THREAD

**Issue by mirrorway** [QubesOS/qubes-issues#3837]
### Qubes OS version:

R4.0 current-testing

### Affected component(s): 

qubes applet in notification area

---

### Steps to reproduce the behavior:

1. Qubes applet > any vm > "Run Terminal"

### Expected behavior:

opens some terminal window

### Actual behavior:

nothing

### General notes:

Fails for fedora-26, debian-9, debian-10, whonix template-based-VMs
Opening a terminal from the qubes desktop menu works.
`qvm-run <vm> xterm` works.

---

**Comment by marmarek** [comment]
This require qubes-core-agent VM package version >= 4.0.25  (just uploaded to testing).
