### ISSUE TITLE
R4.0 Fails To Recognize VT-x Support on Lenovo Yoga 2 13

### ISSUE THREAD

**Issue by linuxluser** [QubesOS/qubes-issues#3839]
### Affected component(s):

installer

---

### Steps to reproduce the behavior:

Enable "Intel Virtual Technology" from the BIOS, boot into installer, and get error message that virtualization hasn't been enabled.

### Expected behavior:

Install proceeds as usual.

### Actual behavior:

Installer complains that virtualization hasn't been enable and Qubes OS probably won't work.

### General notes:

I have verified that `vmx` does indeed show up on my current OS (Ubuntu 16.04; kernel 4.4.0-93-generic) in `/proc/cpuinfo`. However, when I boot into the Qubes R4.0 installer, `/proc/cpuinfo` does not show `vmx` in the kernel flags section. Oddly, it instead shows `hypervisor`, which is a cpuinfo flag I've never encountered before. `uname -r` while in the installer shows `4.13.16-100.fc25.x86_64`.

[Full `/proc/cpuinfo` from Ubuntu](https://gist.github.com/linuxluser/2f5bbf4608c9f5c67bbe86a9505e8199#file-ubuntu-cpuinfo)
[Full `/proc/cpuinfo` from Qubes OS installer]( https://gist.github.com/linuxluser/2f5bbf4608c9f5c67bbe86a9505e8199#file-qubes-cpuinfo)

Hardware: Lenovo Yoga 2 13 (model 20344)
CPU: [Intel i5-4200U](https://ark.intel.com/products/75459/Intel-Core-i5-4200U-Processor-3M-Cache-up-to-2_60-GHz)

---

### Screenshot:
![img_20180421_191046](https://user-images.githubusercontent.com/41452/39090691-bacc61ca-459a-11e8-8185-5644e7bacda0.jpg)

**Comment by marmarek** [comment]
> I have verified that vmx does indeed show up on my current OS (Ubuntu 16.04; kernel 4.4.0-93-generic) in /proc/cpuinfo. However, when I boot into the Qubes R4.0 installer, /proc/cpuinfo does not show vmx in the kernel flags section. Oddly, it instead shows hypervisor, which is a cpuinfo flag I've never encountered before.

This is expected. vmx extension isn't available to Linux (running in dom0 in this case), because it is already used by Xen. As @crat0z says, `xl info` is more reliable way to check VT-x presence. Or even better: qubes-hcl-report

**Comment by marmarek** [comment]
There is no bug here, your hardware doesn't support VT-d, which installer correctly reported.

**Comment by linuxluser** [comment]
Thanks, everyone. It appears I was confused. `vtx` seems to simply indicate general VT support, not VT-d support.

I was able to successfully install R3.2, which did not give me the aforementioned warning. Would it be safe to install R4.0 instead and ignore the warning then?
