### ISSUE TITLE
Qubes Manager Requires Constant Refresh

### ISSUE THREAD

**Issue by qubesissues** [QubesOS/qubes-issues#3844]
### Qubes OS version:

4.0

### Affected component(s): 

Qube Manager

### Steps to reproduce the behavior:

Start, stop, or update a Qube

### Expected behavior:

The started Qube should show a green dot next to them.  Stopped should show no dot.  Updated should show no arrow.

### Actual behavior:

Dots and arrows are inconsistent.  It is necessary to "Refresh qube list" with the recycle icon constantly.

**Comment by andrewdavidwong** [comment]
Duplicate of #3572

**Comment by andrewdavidwong** [comment]
Duplicate of #3675

**Comment by andrewdavidwong** [comment]
This appears to be a duplicate covered by two existing issues. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.
