### ISSUE TITLE
Feature Request: Qube Manager Sort Options

### ISSUE THREAD

**Issue by qubesissues** [QubesOS/qubes-issues#3848]
### Qubes OS version:

4.0

### Affected component(s): 

Qubes Manager

---

### General notes:

It would be nice if you had more sort options in the Qube Manager.  

1. It would be great to sort by color

2. It would be great to sort by some second option.  For example By color and then alphabetically within that.  Or By type of Qube (proxy, template, etc.) and then by template used.  And then by color? :)

**Comment by andrewdavidwong** [comment]
Closely related: #1022, #3241.

**Comment by mirrorway** [comment]
I can sort by color by clicking the column header above the padlocks.

**Comment by andrewdavidwong** [comment]
> Related to (1), you can group by color by clicking the column header above the padlocks.

In that case, I think point 2 is already covered by #1022, so I'm closing this "not an issue." If anyone believes this is a mistake, please leave a comment, and we'll be happy to take another look. Thank you.
