### ISSUE TITLE
Boot / Shutdown splash screen not displayed with linux-kernel-latest v4.16.2-1

### ISSUE THREAD

**Issue by jharveyb** [QubesOS/qubes-issues#3849]
### Qubes OS version:

4.0 testing

### Affected component(s): 

Plymouth

---

### Steps to reproduce the behavior:

Install linux-kernel-latest v4.16.2-1 from testing
Shutdown and boot with kernel 4.16.2-1
Shutdown after boot

### Expected behavior:

Plymouth loads after selecting kernel, showing Qubes logo with disk password prompt and progress bar below. On shutdown Qubes logo is displayed with progress bar below.

### Actual behavior:

Plymouth does not load during either boot or shutdown so disk password prompt is shown in text mode, followed by kernel messages that are normally shown after pressing Home / Escape from Plymouth splash screen.

### General notes:

Was running linux-kernel-latest v4.15.6-1 before this and Plymouth behaved as expected, could switch to view kernel messages per boot without issue for subsequent boots or shutdowns. After installing linux-kernel-latest v4.16.2-1, booting linux-kernel-latest v4.15.6-1 still presents the Plymouth splash screen correctly.

---

### Related issues:

https://github.com/QubesOS/updates-status/issues/483

**Comment by jharveyb** [comment]
The same issue is present with https://github.com/QubesOS/updates-status/issues/542

rebuilding the initramfs using sudo plymouth-set-default-theme qubes-dark -R does not change the behavior.

However, the tribar theme does work on boot, even though the system still defaults to text mode (have to explicitly switch back to graphical mode to display the tribar). The same behavior is seen on shutdown, though there is no tribar and just a empty screen with black background.

**Comment by strugee** [comment]
I can reproduce this problem on kernel-latest 4.19.2-3. Let me know if there's any debugging information I can provide.

**Comment by opposablebrain** [comment]
+1

**Comment by marmarek** [comment]
Similar issue in Debian: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=897572
I don't think it's exactly the same (holding backspace does not bring proper luks prompt), but it may be related.

**Comment by fepitre** [comment]
I tested to revert the commit referenced in https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=897572 (https://github.com/fepitre/qubes-linux-kernel/commit/0abdd79f5fddeee7735ecf495bf128bd588c934f) but it had not effect. Also, newer version of plymouth does not have any effect as I encounter the same problem in testing dom0 under fc29 for R4.1.

**Comment by fepitre** [comment]
I also found in plymouth debug that in kernel above 4.14, it detects now hvc0 as console : kernel-4.14 log https://gist.github.com/fepitre/2e19f000393dcb7e12ca8f3d55db0aa4#file-plymouth-debug-kernel-4-14-L35, kernel-4.19 log https://gist.github.com/fepitre/33edf64428b6c5b986a8c7486eb3eed7#file-plymouth-debug-kernel-4-19-L34.

**Comment by marmarek** [comment]
In 4.19 log:
```
serial consoles detected, managing them with details forced
```
in old log:
```
creating objects for drm devices
```

This looks like a good lead. I'd look for some option to disable serial consoles in plymouth. Is there anything in some config file? Or maybe on kernel command line?

**Comment by fepitre** [comment]
@marmarek @andrewdavidwong : it has also a positive solution for me for installing 4.0.1. Indeed, as it ships kernel-4.19, I never reached the anaconda startup (first menu of selecting language). It was staying idle in black screen with blinking cursor. I just tested to add """plymouth.ignore-serial-consoles""" at the grub installer boot menu right after """quiet rhgb"""" and it solved the problem. I can now install 4.0.1. Maybe we should add this somewhere in the troubleshooting? This could be a same problem encountered by other users.

**Comment by andrewdavidwong** [comment]
> it has also a positive solution for me for installing 4.0.1. Indeed, as it ships kernel-4.19, I never reached the anaconda startup (first menu of selecting language). It was staying idle in black screen with blinking cursor. I just tested to add """plymouth.ignore-serial-consoles""" at the grub installer boot menu right after """quiet rhgb"""" and it solved the problem. I can now install 4.0.1. Maybe we should add this somewhere in the troubleshooting? This could be a same problem encountered by other users.

Sounds good. I could see it being added to either of these:

- https://www.qubes-os.org/doc/releases/4.0/release-notes/#known-issues
- https://www.qubes-os.org/doc/#troubleshooting

Mind submitting a PR?

**Comment by marmarek** [comment]
Since this applies to installation image, it may be a reason to release new one. If this indeed solve some common issue. Can anyone else confirm this?
@fepitre I understand you mean legacy boot (since you have grub there). Have you tried UEFI too?
But still, adding it to documentation is a good idea anyway.

**Comment by fepitre** [comment]
@marmarek, indeed it was with legacy boot. I did not retry with UEFI because I lack the time to do that currently. That would be great if anyone could confirm this too. In my case, it is not a problem with nouveau module because disabling it produced the same result: blinking cursor. Only the method described above solved the graphical boot.

**Comment by strugee** [comment]
I can confirm that this workaround works under UEFI.

**Comment by tlaurion** [comment]
Heads on headless systems (servers outputting to console) consequently requires that kernel parameter to be [removed](https://github.com/osresearch/heads/blob/master/boards/kgpe-d16/kgpe-d16.config#L29) as pointed in this [issue](https://github.com/osresearch/heads/issues/560)

**Comment by marmarek** [comment]
On the other hand, on laptop systems this option is needed, otherwise plymouth treats /dev/hvc0 (a console to Xen) as a serial console and disable graphical screen. Removing that option in a board config seems like a good compromise for me.

**Comment by tlaurion** [comment]
@marmarek 
> followed by kernel messages that are normally shown after pressing Home / Escape from Plymouth splash screen.

Those are still not present for me when pressing escape at boot:
`May 27 21:55:03 dom0 kernel: Command line: placeholder root=/dev/mapper/qubes_dom0-root ro rd.luks.uuid=luks-a35bb850-778b-46d7-9814-7a105669960e rd.luks.options=discard rd.lvm.lv=qubes_dom0/root rd.lvm.lv=qubes_dom0/swap i915.alpha_support=1 plymouth.ignore-serial-consoles intel_iommu=igfx_off fromiso=/dev/disk/by-uuid/2f00bca5-dd3c-4a39-98f2-4e0ffeeae9f8/Qubes-R4.0.3-x86_64.iso iso-scan/filename=/Qubes-R4.0.3-x86_64.iso rhgb quiet rd.qubes.hide_all_usb intel_iommu=on intel_iommu=igfx_off `
