### ISSUE TITLE
No internet but can connect to router- non-template standalone VMs DNS error

### ISSUE THREAD

**Issue by 0pcom** [QubesOS/qubes-issues#3857]
### Qubes OS version:

4.0
(I reported this in 4.0rc-4 also, but here is more detail)

https://github.com/QubesOS/qubes-issues/issues/3669

### Affected component(s): 

Non-template Standalone VMs (linux ISOs), network connectivity, DNS resolution

---

### Steps to reproduce the behavior:

This takes some time to reproduce because I can't boot these 'nontemplate VMs' from USB or hard disk. Lucky the DVD drive works.

#### needed components to reproduce the behavior:
-Non template standalone VM (any bootable linux .iso)
-DVD burner
-Blank DVDs

In my setup I used <a href="https://github.com/Portergos">Portergos</a>; a flexible archlinux based distro inspired by Antergos:

The April release of Portergos can be found: <a href="https://github.com/Portergos/portergos-iso/releases/download/iso_apr_18_2018/portergos-2018.04.18-x86_64.iso">here</a>

<b>Step 1:</b>
burn the .iso to a DVD

<b>Step 2:</b>
create and name a nontemplate VM

<b>Step 2a:</b>
optionally, increase the memory and available CPUs in settings.
optionally, deselect include in memory balancing in settings.

<b>Step 3:</b>
Boot qube from existing block device dom0:sr0

<b>Step 4:</b>
If using Portergos;
When the menu appears:
select option 0 to install
Or start a desktop session (i3 or xfce4)

(If you are serious about troubleshooting this behavior, i recommend installing this as a VM.)

<b>Step 5:</b>
When you finally have a desktop session:

-right click the networkmanager icon in the bottom panel
-click edit connections
-select wired connection 1
-click the gear button to edit
-click to ipv4 settings tab
-set the IP, gateway, and netmask the way it appears in the VM settings for this VM

ip 10.137.0.15
netmask 255.255.255.255
gateway 10.137.0.6

-check require IPV4 to complete this connection.

-open a browser (included with Portergos are opera and light-firefox)

*DNS error*

-Now, enter the IP address of your router in the address bar.

*i am able to connect to router*

### Expected behavior:

Working internet on all VMs
Specifically, I would assume this should work with the same instructions as it did in 3.2

### Actual behavior:

DNS errors, can't find websites, but can talk to router.

Adjusting the DNS address under the ipv4 settings of 'wired connection 1' did not seem to affect the ability to connect to the router or improve the DNS error for other queries.

I've tried:
0.0.0.0 (router local DNS)
1.1.1.1
10.137.0.6
10.137.0.5
255.255.255.255

### General notes:

This seems to be the kind of failure that occurs when routers are put in series with each other. I'm not familiar enough with network troubleshooting to speculate further, however the ability to connect to the router is a promising. Any insights are appreciated.

---

### Related issues:

I can't get a netVM to host a DHCP server (provide LAN) to computers connected to it via secondary network interface. Can't provide network to a netvm from another VM. Perhaps this was intentional.

**Comment by 0pcom** [comment]
https://github.com/QubesOS/qubes-issues/issues/3669

**Comment by 0pcom** [comment]
I figured it out.

For anyone experiencing a similar issue, open a Debian based Qube and copy the configuration in /etc/resolv.conf to the same place in the arch-based qube.

nameserver 10.139.1.1
nameserver 10.139.1.2

**Comment by andrewdavidwong** [comment]
> #3669

Ok, next time please just add a comment to the existing issue instead of opening a duplicate.

**Comment by andrewdavidwong** [comment]
Duplicate of #3669
