### ISSUE TITLE
UX: GUI move/copy to another VM prompts separately for each file

### ISSUE THREAD

**Issue by trueriver** [QubesOS/qubes-issues#3859]
### Qubes OS version:

R4.0 (and maybe earlier)

### Affected component(s): 

Nautilus context menus
Move to another VM
Copy to another VM

---

### Steps to reproduce the behavior:

Select multiple files in Nautilus
Right click any selected file
from the context menu select either copy or move to another VM

### Expected behavior:

Dialog selects destiantion of all files

### Actual behavior:

Dialog box opens once for each selected file. This is not useful even if you want to send the files to different destinations as you do not know which file is being moved/copied by each dialog box

### General notes:

My intuition suggest this might be harder to fix than it appears, depending exactly where in the workflow the dialog box is situated.

Workaround: use Nautilus to collect files into one folder and move/copy that.

---

**Comment by X4lldux** [comment]
@andrewdavidwong @trueriver I think this can be closed now, since the fix is already merged and even packaged in 4.0.27.
