### ISSUE TITLE
windows 7 crash, PoD error

### ISSUE THREAD

**Issue by mirrorway** [QubesOS/qubes-issues#3861]
### Qubes OS version:

R4.0

### Affected component(s): 

windows-7
qubes GUI settings

---

### Steps to reproduce the behavior:

1. windows 7 TemplateVM > Advanced Tab
2. enable memory balancing
3. set memory := 2048, maxmem := 3000
4. disable memory balancing
5. start the windows 7 VM.
6. wait a few minutes

### Expected behavior:

VM runs without crashing..

### Actual behavior:

Windows VM crashes.
hypervisor.log:

```
(XEN) p2m_pod_demand_populate: Dom8 out of PoD memory! (tot=524286 ents=243712 dom9)
(XEN) domain_crash called from p2m-pod.c:1218
(XEN) Domain 8 reported crashed by domain 9 on cpu#0:
(XEN) p2m_pod_demand_populate: Dom8 out of PoD memory! (tot=524286 ents=243712 dom9)
(XEN) domain_crash called from p2m-pod.c:1218
(XEN) p2m_pod_demand_populate: Dom8 out of PoD memory! (tot=524286 ents=243712 dom9)
(XEN) domain_crash called from p2m-pod.c:1218
```

### General notes:

Possible cause: `maxmem` > `memory` enables Populate on Demand, but there is no ballooning to prevent the guest from eventually exhausting the PoD memory pool, when it happens, Xen kills the guest. [1]

In R3.2 there was a safeguard:
If memory balancing is disabled, the Advanced tab greys out maxmem and automatically sets maxmem := memory (even though it is not reflected in the GUI immediately, reopening the tab shows this happens behind the scenes.)

In R4.0, there is no safeguard:
Disabling memory balancing still greys out maxmem, but does not set maxmem := memory..If you do not set them equal manually, then a PoD crash eventually occurs..

Note: The situation may arise more naturally than the reproduction steps imply. R3.2 Windows 7 VMs with memory balancing off, when to restored to R4.0, may automatically have maxmem > memory (perhaps the restore code, seeing memory balancing is off, and thinking `maxmem` irrelevant, sets  `maxmem` to a default value of 4000M),

For me, I did not pay close attention to the settings immediately after restoring my win-7 VM, I only know I experienced these PoD crashes soon after, that increasing the memory usually delays the crash, and that setting maxmem = memory prevents it.

---

### Related issues:

In R4.0, enabling "memory balancing" with maxmem > memory still results in PoD crash..

Reference for ballooning and PoD:
[1] https://blog.xenproject.org/2014/02/14/ballooning-rebooting-and-the-feature-youve-never-heard-of/

**Comment by marmarek** [comment]
Fixed together with #4135
