### ISSUE TITLE
Cannot unlock XScreenSaver after switching keyboard language

### ISSUE THREAD

**Issue by teknico** [QubesOS/qubes-issues#3862]
### Qubes OS version:

R4.0 (originally installed at 4.0-rc5)

### Affected component(s): 

XScreensaver

---

### Steps to reproduce the behavior:

- lock the screen (either manually or by waiting long enough)
- type the user password
- click the OK button, or press the Enter key

### Expected behavior:

Going back to desktop

### Actual behavior:

Unlocking is refused with message: "Authentication failed!"

### General notes:

The password does works at the initial login with the same username.

Desktop access can be regained with the following workaround:

- press Ctrl-Alt-F2
- login with the same username and password
- run the command: `sudo killall xscreensaver`
- press Ctrl-Alt-F1

---

### Related issues:

Cannot find anything relevant in log files in `/var/log/`.

In the Qube Manager, the menu entry Qube -> Logs is always empty, irrespective of which qube is selected.

**Comment by teknico** [comment]
Not able to check anymore, sorry.

**Comment by majorminors** [comment]
I believe this has occurred to me twice. Same Qubes version. Doesn't happen every time the screen locks though. Haven't tried the workaround but I will if it happens again. Just held the power button until the pc turned off and on reboot, the pc returned to normal operation.

**Comment by donob4n** [comment]
Just an idea... Has your password some rare symbols that could change if the keyboard language is changed?

**Comment by majorminors** [comment]
Yep! And I toggle between US and UK keyboards.

Also, happened a third time, and I confirm the workaround works.

**Comment by andrewdavidwong** [comment]
Keyboard layout switching was also mentioned in #1917.
