### ISSUE TITLE
Restoring a backup created with "--compress-filter 'gzip -3'" fails

### ISSUE THREAD

**Issue by keepiru** [QubesOS/qubes-issues#3865]
### Qubes OS version:
Backup created on R3.2, attempted restore on R4.0

### Affected component(s): 
qvm-backup-restore

### Steps to reproduce the behavior:
On R3.2:
qvm-backup -z -Z 'gzip -3' -d sys-usb /media/user/backups

On R4.0:
qvm-backup-restore -d sys-usb /run/media/user/backups/qubes-backup-2018-04-20T010203 my-vm

### Expected behavior:
Backup is restored without errors.

### Actual behavior:
app: Checking backup content...
qvm-backup-restore: error: Invalid backup header (value)

### General notes:
I was able to work around the issue with this patch:

```
diff -r -u site-packages-orig/qubesadmin/backup/restore.py site-packages/qubesadmin/backup/restore.py
--- site-packages-orig/qubesadmin/backup/restore.py	2018-03-03 19:33:29.000000000 -0800
+++ site-packages/qubesadmin/backup/restore.py	2018-04-27 23:37:00.206134065 -0700
@@ -143,9 +143,6 @@
             if key not in self.header_keys.keys():
                 # Ignoring unknown option
                 continue
-            if not _re_alphanum.match(value):
-                raise QubesException("Invalid backup header ("
-                                                 "value)")
             if getattr(self, self.header_keys[key]) is not None:
                 raise QubesException(
                     "Duplicated header line: {}".format(key))
@@ -153,6 +150,8 @@
                 value = value.lower() in ["1", "true", "yes"]
             elif key in self.int_options:
                 value = int(value)
+            if value == 'gzip -3':
+                value = 'gzip'
             setattr(self, self.header_keys[key], value)
 
         self.validate()
```

**Comment by iamahuman** [comment]
Qubes OS 4.0 indeed got much stricter in its command line parsing options. Relaxing this restriction within a sensible limit will resolve this issue.

Meanwhile, when _creating_ a backup with `--compress-filter 'gzip -3'` for example, tarwriter.py in R4.0 does not accept command line options for `--use-compress-program`<sup>[[src]](https://github.com/QubesOS/qubes-core-admin/blob/2164a8d7b8b3d788d42c65c3b092498d57304c41/qubes/tarwriter.py#L163)</sup>, unlike [GNU tar(1)](https://man7.org/linux/man-pages/man1/tar.1.html) which does:

>```
>       -I, --use-compress-program=COMMAND
>              Filter data through COMMAND.  It must accept the -d option,
>              for decompression.  The argument can contain command line
>              options.
>```

GNU tar uses a fully featured built-in lexer<sup>[[hdr]](https://git.savannah.gnu.org/cgit/tar.git/tree/lib/wordsplit.h?id=1ff0b63f48988ed2a94d42d52f7a81602f874cc8)[[src]](https://git.savannah.gnu.org/cgit/tar.git/tree/lib/wordsplit.c?id=1ff0b63f48988ed2a94d42d52f7a81602f874cc8)</sup> for splitting COMMAND<sup>[[src]](https://git.savannah.gnu.org/cgit/tar.git/tree/src/system.c?id=1ff0b63f48988ed2a94d42d52f7a81602f874cc8#n470)</sup>. Specifically,

 - It performs **environment variable expansion**.
 - It handles **C escape sequences**.
 - It handles single and double quotes, presumably according to shell lexing rules.
 - It coalesces multiple delimiting white-spaces into one, just like the shell.

Before resolving this issue, it's perhaps worth to look into above.

**Comment by marmarek** [comment]
The current restriction is specifically to avoid issues like https://github.com/QubesOS/qubes-secpack/blob/master/QSBs/qsb-051-2019.txt

**Comment by iamahuman** [comment]
Maybe strip out known flags like the compression level? It will allow for both compatibility with old backups and flexibility in compression control.

**Comment by DemiMarie** [comment]
Stripping out the compression level seems like a good idea.  Another option is to allow the user to specify the decompression program on restore, since we can assume that the restore command line is trusted.

**Comment by DemiMarie** [comment]
@marmarek if this option looks good I can make a PR.

**Comment by marmarek** [comment]
> Another option is to allow the user to specify the decompression program on restore, since we can assume that the restore command line is trusted.

Yes, I'd go this way - require explicit compression program on the command line, if it doesn't match any of whitelisted ones (which means also anything with arguments). Preferably this way:
1. if (de-)compression program is given by the user - use that, otherwise:
2. if backup header contains some on the whitelist - use that (`tar` will add `-d` option for decompression), otherwise:
3. error out, suggesting to specify/confirm custom compression program - here include also what was given in the backup header (with some sensible sanitization)

**Comment by DemiMarie** [comment]
I think we should also support this in the GUI, as it is an important feature.

It has been years since I have done anything GUI related, but I can try.
