### ISSUE TITLE
Qubesd gets bogged down

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#3869]
### Qubes OS version:

`R4.0`

### Affected component(s): 

qubes-core-admin (qubesd)

---

### Steps to reproduce the behavior:

Immediately after boot, launch several VMs in quick succession

### Expected behavior:

VMs spawn quickly

### Actual behavior:

VMs have latencies of several minutes

### General notes:

This could be because I have an SSD and an HDD instead of an all-SSD system.

---

**Comment by marmarek** [comment]
Starting VM involve creating LVM snapshots, which normally takes 1-2s per VM. If it significantly takes more on your system, can you check the logs what is the most time consuming operation?

**Comment by DemiMarie** [comment]
Thank you.  I will check the next time it happens.

**Comment by DemiMarie** [comment]
If I recall correctly, this has been partially fixed by cleaning up old files from `/etc/lvm/archive`, and partially fixed by me switching to faster (SSD) storage.

**Comment by DemiMarie** [comment]
This is fixed.
