### ISSUE TITLE
https://www.qubes-os.org/doc/ links are 404

### ISSUE THREAD

**Issue by awokd** [QubesOS/qubes-issues#3870]
### Qubes OS version:

N/A

### Affected component(s): 

https://www.qubes-os.org/doc/

---

### Steps to reproduce the behavior:

Click on one of the `https://www.qubes-os.org/doc/` documents

### Expected behavior:

Document is displayed

### Actual behavior:

`404 Not Found` error

### General notes:

Off-site links work normally

---

**Comment by marmarek** [comment]
Looks like git submodules are not fetched.
Github support says they are working on resolving this, but no ETA yet.

**Comment by j77h** [comment]
some links within the github docs seem broken too:
`verifying-signatures` is at 
`qubes-doc/security-info/verifying-signatures` but it's linked as 
`qubes-doc/security/verifying-signatures` from 
`qubes-doc/security/security-guidelines`  and from 
`qubes-doc/security-info/security`

**Comment by awokd** [comment]
> some links within the github docs seem broken too

I think that's ok; those links should (normally) get redirected by this portion of the `verifying-signatures.md` header:
~~~
---
layout: security
title: Verifying Signatures
permalink: /security/verifying-signatures/
redirect_from:
- /doc/verifying-signatures/
- /en/doc/verifying-signatures/
- /doc/VerifyingSignatures/
- /wiki/VerifyingSignatures/
---
~~~

**Comment by andrewdavidwong** [comment]
Further details from GitHub Support via @marmarek:

> Thanks for reaching out, and sorry for the trouble!
> 
> Our engineering team is currently performing unplanned maintenance on GitHub Pages. Unfortunately, sites relying on submodules will fail to build until this work is completed. Sites without submodules should continue to build successfully.
> 
> We're working to restore submodule functionality as soon as possible, but we don't yet have an ETA. As soon as we have an update to share, we'll certainly let you know.
>

**Comment by andrewdavidwong** [comment]
Announcement: https://groups.google.com/d/topic/qubes-users/TMb67V-ALtw/discussion

**Comment by marmarek** [comment]
The website works again :)
