### ISSUE TITLE
Unable to install virt-manager

### ISSUE THREAD

**Issue by kaspro** [QubesOS/qubes-issues#3873]
### Qubes OS version:
4.0

### Affected component(s): 
Template: fedora26

### Steps to reproduce the behavior:
- Start template
- run `sudo dnf install virt-manager`

### Expected behavior:
_virt-manager_ is being installed succesfully

### Actual behavior:
Installation fails due to Xen dependencies:

    Error: 
     Problem: conflicting requests
      - package virt-manager-1.4.3-2.fc26.noarch requires libvirt-glib >= 0.0.9, but none of the providers can be installed
      - package virt-manager-1.4.1-2.fc26.noarch requires libvirt-glib >= 0.0.9, but none of the providers can be installed
      - libvirt-glib-1.0.0-2.fc26.i686 has inferior architecture
      - package libvirt-glib-1.0.0-2.fc26.x86_64 requires libvirt.so.0()(64bit), but none of the providers can be installed
    ....
    ....

### General notes:
I'm using this as an administration tool for remote servers - so it's not about nested virtualization...

### Related issues:
-

**Comment by andrewdavidwong** [comment]
Related: https://github.com/QubesOS/qubes-issues/issues/2455#issuecomment-305764213 (and surrounding comments)

**Comment by kaspro** [comment]
virt-manager installs fine now with the fedora-28 template, so that does it for me... Thanks!
