### ISSUE TITLE
gedit problem in debian

### ISSUE THREAD

**Issue by trueriver** [QubesOS/qubes-issues#3874]
### Qubes OS version:

R4.0

### Affected component(s): 

Debian template: gedit

---

### Steps to reproduce the behavior:

open a terminal in a VM based on a fully updated Debian template

type the command
```
gedit
```

### Expected behavior:

gedit opens cleanly

### Actual behavior:

gedit opens but with the following message displayed in the terminal

(gedit:1461): dconf-WARNING **: unable to open file '/etc/dconf/db/local': Failed to open file '/etc/dconf/db/local': open() failed: No such file or directory; expect degraded performance

### General notes:

This is far from being urgent but I would expect anything that is installed in the template to work. Is that a daft expectation?

One fix would be to remove gedit from the debian template

A better fix, in my opinion, would be to supply the directory it is complaining about.

---

**Comment by marmarek** [comment]
Already fixed in https://github.com/QubesOS/qubes-core-agent-linux/commit/4329eab307d02032e91c2e52d0eaa2294a400d04 (see commit message for explanation). This is included in https://github.com/QubesOS/updates-status/issues/496
