### ISSUE TITLE
Can not find new domain with qubesadmin - Qubes

### ISSUE THREAD

**Issue by donob4n** [QubesOS/qubes-issues#3875]
### Qubes OS version: 

R4

### Affected component(s): 

Potentially all things using import Qubes from qubesadmin

---

### Steps to reproduce the behavior:

Currently I am trying to implement dbus events in Qube Manager. When recieve a 'DomainAdded' signal a callback function is called for handling it. Since it only knows the 'qid' of the domain it loops through qubes_app.domains and gets it. Unfortunately sometimes (maybe when there are some amount of domains) it does not find it. Here is a example log after creating two new domains:

```
/org/qubes/DomainManager1/domains/36
LOOKING FOR QID 36
21
15
27
13
17
36
36 found!!
/org/qubes/DomainManager1/domains/37
LOOKING FOR QID 37
21
15
27
13
17
36
28
9
20
35
2
33
16
0
29
19
4
10
11
30
34
32
12
31
24
42
40
6
5
7
22
18
14
25
23
26
3
1
8

NOT FOUND

```

### Expected behavior:

If we recieved a 'DomainAdded' signal, that domain should be in Qubes.domains.

### Actual behavior:

It is not.

### General notes:

Maybe is this due some kind of caching? After restarting qube-manager the new domain appears fine.

Making new Qubes() objects when I need to find a new domain also works fine.

---

**Comment by marmarek** [comment]
Yes, caching, see `qubes_app.domains.clear_cache()`.

**Comment by donob4n** [comment]
Ouch, ok thanks :)

**Comment by donob4n** [comment]
Ey @marmarek 

Could this cache be handled internally? I mean it gets cleared automatically when needed, otherwise I see a lot of places where it needs to be called and also its pretty error prune.
