### ISSUE TITLE
Can't delete VM created by backup restore process (qvm-remove refuses)

### ISSUE THREAD

**Issue by BobSchnatt** [QubesOS/qubes-issues#3884]
### Qubes OS version:

Qubes release 4.0 (R4.0)

### Affected component(s): 

A VM I'm trying to delete.

---

### Steps to reproduce the behavior:

Restore a VM that still exists in the system from a backup file. (In other words, I screwed up
changes to the debian-9 template VM, so I used the restore process to overwrite the existing
debian-9 template.) I later realized that this caused Qubes to clone the original debian-9 VM to a new
one called debian-91.
Use the Qube Manager to delete this older VM (debian-91).

### Expected behavior:

I expect the the domain (VM) to be deleted.

### Actual behavior:

I get an error from the Qube Manager:
"ERROR: VM installed by package manager"

### General notes:

I tried using the qvm-remove command to delete this VM (with and without the sudo command, and with
and without the --force option), but the results were the same. In the terminal, the message is:
"Error: VM installed by package manager"

I actually have 2 of these VM clones on my system that I can't get rid of. Both VMs are templates, they are not attached to network VMs and they are not the basis of DispVMs.
Help!

---

**Comment by marmarek** [comment]
Restoring backup never override existing VMs - `debian-91` is actually the one you've restored. You can see it in restore operation summary (just before confirming it).

See [here](https://www.qubes-os.org/doc/templates/) for details how to handle templates installed by default (including reinstalling it, or removing).

**Comment by marmarek** [comment]
Also, please use [qubes-users mailing list](https://www.qubes-os.org/support/#qubes-users) for generic questions.

**Comment by BobSchnatt** [comment]
Thank you. Clearly, I couldn't have made it plainer that I'm a newbie unless I took out a full page ad in the NY Times :)  Appreciate the help...

**Comment by BobSchnatt** [comment]
I still have the original problem. I changed all my AppVMs to point to debian-92, but I still get that same error message when I try to delete debian-9 or debian-91. (I now have ZERO AppVMs or DispVMs pointing to debian-9 or debian-91, and neither of those VMs are running.) I'll move any future problems to the newsgroup you mentioned, but could you help me resolve this? I would really appreciate it!

**Comment by BobSchnatt** [comment]
Here's the solution: In Dom0, type qvm-prefs debian-91 installed_by_rpm false.  After that change, I was allowed to delete the VM. Thanks again. Like I said, I'll move all future issues to the newsgroup you mention. Thanks for all you guys do. Qubes is nice :)
