### ISSUE TITLE
Renaming VM Should Adjust Dependencies

### ISSUE THREAD

**Issue by qubesissues** [QubesOS/qubes-issues#3892]
### Qubes OS version:
4.0

### Affected component(s): 

Qubes Manager

---

### Steps to reproduce the behavior:
Rename a Qube that provides Network.

### Expected behavior:

The Qube should take the new name and all Qubes that depend on this Qube should automatically adjust so they use the new name.  This happened in 3.2.

### Actual behavior:

You are told that you are not allow to rename the Qube!

**Comment by 3hhh** [comment]
This behaviour is currently wanted afaik, cf. #3576

**Comment by andrewdavidwong** [comment]
> This behaviour is currently wanted afaik, cf. #3576

Can you elaborate? #3576 looks like it's about changing templates, not renaming VMs or changing NetVMs.

**Comment by 3hhh** [comment]
> > This behaviour is currently wanted afaik, cf. #3576

> Can you elaborate? #3576 looks like it's about changing templates, not renaming VMs or changing NetVMs.

You're right, it was #2868

**Comment by andrewdavidwong** [comment]
> You're right, it was #2868

I thought there was a new feature that "renames" by (under the covers) cloning to the new name and removing the old VM. From the user's perspective, this looks like a "rename." I interpreted the original report as saying that this new "rename" feature should automatically adjust dependencies and should be usable on VMs with  dependents.

**Comment by qubesissues** [comment]
> I interpreted the original report as saying that this new "rename" feature should automatically adjust dependencies and should be usable on VMs with dependents.
@andrewdavidwong 

Yes that would be ideal.  Maybe difficult but definitely ideal.  Particularly useful when you rename a ProxyVM that 10 Qubes use for connectivity.  Now you have to change all of their network VM manually to something else, then change the name, then change all 10 again to the newly-named Qube.  Ack!
