### ISSUE TITLE
qubes-dom0-update --clean exits unexpectedly

### ISSUE THREAD

**Issue by lunarthegrey** [QubesOS/qubes-issues#3893]
### Qubes OS version:

Qubes Release 4.0

### Affected component(s): 

qubes-dom0-update

---

### Steps to reproduce the behavior:

Run this in a dom0 terminal: `sudo qubes-dom0-update --clean`

### Expected behavior:

Yum cache is removed successfully.

### Actual behavior:

Says that files were removed, then looks to be syncing repo-data. After a short (sometimes long) period of time you get an error and the process will be killed like:
`/usr/bin/fakeroot: line 181:  9686 Killed  FAKEROOTKEY=$FAKEROOTKEY LD_LIBRARY_PATH="$PATHS" LD_PRELOAD="$LIB" "$@"`

 

### General notes:

Seems to only happen when running `sudo qubes-dom0-update --clean`

---

### Related issues:

None that I know of.

**Comment by marmarek** [comment]
What VM you use for UpdateVM, default sys-firewall? What template it has, default fedora-26?
Do you see anything related in `journalctl -e` in that VM?

**Comment by lunarthegrey** [comment]
@marmarek I currently use sys-firewall and it's running off the default fedora-26 template. Thanks for the suggestion about checking journalctl. I actually found that it was OOMing and that's what caused the process to die. Once I gave more memory to sys-firewall the issue doesn't occur.

I kind of forgot how update VMs worked...
