### ISSUE TITLE
qvm-volume info throws KeyError: 'revisions_to_keep'

### ISSUE THREAD

**Issue by bmup** [QubesOS/qubes-issues#3900]
### Qubes OS version:

R4.0

### Affected component(s): 

qvm-volume info

---

### Steps to reproduce the behavior:

1.) run qvm-ls from dom0
2.) select a VM from the NAME column, and run qvm-volume list <VM>
3.) now run qvm-volume info <VMNAME:VOLUME_NAME> for some row identified in step 2 above

### Expected behavior:

information is listed about that volume

### Actual behavior:

stack trace results:
qvm_volume.py line 307
  sys.exit(main())
qvm_volume.py line 112
  value = getattr(volume, item)
qvm_volume.py line 178
  return int(self._info['revisions_to_keep'])
KeyError: 'revisions_to_keep'

### General notes:

If I remove 'revisions_to_keep' from info_items list at line 95 of qvm_volume.py, then the command executes successfully (although revisions_to_keep information is of course not displayed.) I doubt that is the correct fix however, since at first glance it appears qvm_volume.py intends but fails to support this query. I have not tested qvm-volume info command on every VM/volume combination, but it fails in this same manner on every combination which I have tested.

---

**Comment by marmarek** [comment]
What version of qubes-core-dom0 package do you have? If older than 4.0.25, please update.

**Comment by bmup** [comment]
Thank you, that resolves the problem.
