### ISSUE TITLE
"qvm-volume extend" fails calling qubes.ResizeDisk

### ISSUE THREAD

**Issue by davex25** [QubesOS/qubes-issues#3906]
### Qubes OS version:

4.0 rc3 upgraded, and fully reinstalled 4.0 release version.

### Affected component(s): 

qvm-volume

---

### Steps to reproduce the behavior:

Try to increase size of existing running VM root storage, e.g.

"sudo qvm-volume extend fedora-26:root 40GB"

In this case I'm doing an online resize, but have also tried offline and got similar results.

### Expected behavior:

Root size increased.

### Actual behavior:

Prints message:

"Online resize of volume qubes_dom0/vm-fedora-26-root failed (you need to resize filesystem manually): /bin/sh: /etc/qubes-rpc/qubes.ResizeDisk: No such file or directory"

VM root storage was not increased, but if I run "qvm-volume extend 40GB" again, I get:

"For your own safety, shrinking of root is disabled."

But this is also wrong, the disk wasn't actually resized to 40GB yet.

### General notes:

---

**Comment by davex25** [comment]
I think I see what happened here.  Also applies to the other issue I referenced (#3533)

The VM I'm working with is using an older template that I've upgraded multiple times.  Somehow certain rpc scripts that are expected to exist on that template do not, including qubes.StartApp and qubes.ResizeDisk.  

Is there a utility of some kind that ensures a specified VM has all the shell scripts the RPC system expects it to have?

**Comment by davex25** [comment]
For fun, tried copying those scripts from a VM that contained them, but seems there are other missing dependent executable scripts, e.g. /usr/lib/qubes/resize-rootfs.  I copied that one to my problematic VM and the resize seemed to work.  

But seems like there needs to be some way to automatically check that these kinds of scripts exist on the VM.  I've made many modifications to this template VM and don't really want to throw it away.

**Comment by marmarek** [comment]
Is it a template imported from 3.2?

**Comment by davex25** [comment]
Yes it was.

**Comment by marmarek** [comment]
The solution for this is updating packages to 4.0, so it covered with #3934.
