### ISSUE TITLE
Improve multi-speaker and multi-mic support

### ISSUE THREAD

**Issue by 3hhh** [QubesOS/qubes-issues#3914]
### Qubes OS version:
3.2, 4.x

### Description
Currently the support for speakers and mic is limited to the pulseaudio default device.

#### Speakers
Toggling output devices and ports during runtime of an AppVM requires a user to do something like that:
```bash
function setR {
local card="$1"
local port="$2"

#Examples:
#example for card change:
#pacmd set-default-sink alsa_output.pci-0000_00_1b.0.analog-stereo
#pacmd move-sink-input [input index id from pacmd list-sink-inputs] alsa_output.pci-0000_00_1b.0.analog-stereo
#
#example for port change:
#pacmd set-sink-port alsa_output.pci-0000_00_1b.0.analog-stereo analog-output-speaker

#set port first to make the transition smooth
pacmd set-sink-port "$card" "$port"
if [ $? -ne 0 ] ; then
	#some error (sometimes pulse gets confused) --> restart pulseaudio and try again
	killall pulseaudio
	sleep 3
	pacmd set-sink-port "$card" "$port"
fi

#make the new card the current default for future sources
pacmd set-default-sink "$card"

#move all current sources to the new default
pacmd list-sink-inputs | sed -r -n 's/^[ ]+index: ([0-9]+)$/\1/p' | while IFS= read -r sourceId ; do
	pacmd move-sink-input $sourceId "$card"
done
}
```
This is only suitable for power users. In particular I didn't find any Qubes-specific tool to simplify that.

Only setting the default will only change it for newly started VMs.

#### Microphones
The situation is identical here. In particular Qubes only supports forwarding the pulse default microphone to an AppVM via its GUI application. Other microphones are not displayed in the GUI.

### General notes:
Maybe some Qubes application to control which sound input or output device incl. port is assigned to which VM would help here. Maybe it could even be integrated in the qubes-vm-settings similar to the Devices tab.

### Related issues:
#2724

**Comment by marmarek** [comment]
See Pulseaudio Volume Control, by default accessible as "Audio Mixer" in volume control applet. If you have multiple cards, you can choose per-VM what card should be used. And in Input Devices / Output Devices you can choose a port.

**Comment by 3hhh** [comment]
I had seen that, but not noticed the buttons to switch sinks & sources... -_-

Thanks a lot Marek & sorry for bringing this up then - it's apparently invalid.
