### ISSUE TITLE
Disk Space Icon size issue

### ISSUE THREAD

**Issue by dmoerner** [QubesOS/qubes-issues#3918]
Thanks (@kalkin I think) for the new disk space icon - it's very useful. However, the icon appears to be the wrong size, and involve some sort of duplication as a result:

![disk image](https://user-images.githubusercontent.com/23582029/40387880-fa1ed980-5ddb-11e8-8482-ad86f4709f68.png)

I honestly have no idea why this is the case, since it's just using Adwaita icons. But the same problem persists if I switch to Hicolor or another icon theme.

**Comment by andrewdavidwong** [comment]
@dmoerner: Xfce4 on Qubes 4.0?

**Comment by dmoerner** [comment]
Yes, sorry, this is Xfce4 on Qubes 4.0.

**Comment by lunarthegrey** [comment]
I can confirm this is an issue. I see the same exact icon. Qubes 4.0 / Xfce4.

**Comment by marmarek** [comment]
Same here too. Actually I see full icon twice (I have slightly bigger notification area than default).

**Comment by dmoerner** [comment]
Using set_from_icon_name produces properly scalable tray icons for me. Here's a PR: https://github.com/QubesOS/qubes-desktop-linux-manager/pull/24

**Comment by esote** [comment]
I can verify this was fixed for me with the latest dom0 update. Thanks!

**Comment by lunarthegrey** [comment]
Yup, it's fixed for me as well!
