### ISSUE TITLE
CentOS template fails to build due to missing pyton34-pillow package

### ISSUE THREAD

**Issue by misterzed88** [QubesOS/qubes-issues#3919]
### Qubes OS version:

R4.0

### Affected component(s): 

qubes-builder-rpm

---

### Steps to reproduce the behavior:

Following the instructions in https://www.qubes-os.org/doc/building-archlinux-template:
1. Using the Fedora 26 template when setting up the builder VM.
2. Creating a builder.conf using the 'setup' script, with the following options:
- 'Build templates only' enabled
- 'mgmt-salt' disabled
- 'builder-rpm' enabled
- 'centos-7' being the only selected template
3. Downloading sources with `make get-sources`
4. Running build with `make qubes-vm`
5. The build fails, complaining about missing package: 'python34-pillow'

### General notes:

The failure is due to the python34-pillow package not being present in the public CentOS repositories. Although it is present in the Qubes CentOS repositories, it is not used, since only the public repos are enabled during the build.

A workaround which solves the problem is to add the Qubes CentOS repositories to the build, which can be done by:
1. Editing the file repos/qubes-repo-vm-centos.repo, setting 'enabled=1' in the section '[qubes-builder-vm-r%QUBESVER%-current]'
2. Adding 'USE_QUBES_REPO_VERSION := 4.0' to builder.conf

---

**Comment by fepitre** [comment]
In fact, in the package https://github.com/QubesOS/qubes-builder/blob/8676eb503c1bd0a9884b9ee30e70bfeb927831b1/example-configs/templates.conf#L292, python-pillow is missing (not up to date...). I will correct this.

Normally, you can either pick a ready to use config like qubes-os-r4.0.conf or use the setup which will pick some extra things from template.conf. Especially, the TEMPLATES list overrides the COMPONENTS if you have set to build only the templates. So this is why python34-pillow was not there.

USE_QUBES_REPO_VERSION is useful when you don't want to rebuild all the packages, but just one or more, or only the template. This is what we do with the continuous integration for example.
