### ISSUE TITLE
Updating to Xen 4.8.3-8 does not take effect

### ISSUE THREAD

**Issue by esote** [QubesOS/qubes-issues#3924]
### Qubes OS version:

R4

### Affected component(s): 

Xen

---

### Expected behavior:

`xl dmesg` shows Xen 4.8.3-8

### Actual behavior:

Updated using the current-testing repo using `sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing`. Xen and a few other packages were updated. `dnf` reports Xen is 4.8.3-8 while `xl dmesg` reports Xen is 4.8.3-3. As such, I cannot test the new Xen update (ie for issue #3689).

### General notes:

Continuing from discussion on issue #3689.

---

**Comment by esote** [comment]
Pinging @marmarek

**Comment by marmarek** [comment]
Do you have `xen-4.8.3.efi` file there? Is it different than `xen.efi`?

**Comment by esote** [comment]
Yes,
```
# tree
.
├── BOOT
│   ├── BOOTX64.cfg
│   ├── BOOTX64.efi
│   ├── initramfs-4.14.35-1.pvops.qubes.x86_64.img
│   ├── initramfs-4.14.41-1.pvops.qubes.x86_64.img
│   ├── vmlinuz-4.14.35-1.pvops.qubes.x86_64
│   ├── vmlinuz-4.14.41-1.pvops.qubes.x86_64
│   ├── xen-4.8.3.efi
│   └── xen.cfg.anacbak
└── qubes
    ├── initramfs-4.14.35-1.pvops.qubes.x86_64.img
    ├── initramfs-4.14.41-1.pvops.qubes.x86_64.img
    ├── vmlinuz-4.14.35-1.pvops.qubes.x86_64
    ├── vmlinuz-4.14.41-1.pvops.qubes.x86_64
    ├── xen-4.8.3.efi
    ├── xen.cfg
    ├── xen.cfg.anacbak
    └── xen.efi
```

`xen-4.8.3.efi` is different than `xen.efi` (and likewise `BOOTX64.efi`)

**Comment by esote** [comment]
@marmarek That's worked, I now see "Xen 4.8.3-8.fc25". I agree, the documentation should note the `xen-*.efi` file. I am now seeing "XPTI: enabled" in `xl dmesg`, indicating Xen's meltdown protection.

Thanks for your help.

**Comment by andrewdavidwong** [comment]
@esote:
> That's worked, I now see "Xen 4.8.3-8.fc25". I agree, the documentation should note the `xen-*.efi` file. I am now seeing "XPTI: enabled" in `xl dmesg`, indicating Xen's meltdown protection.

Please consider [submitting a PR](https://www.qubes-os.org/doc/doc-guidelines/). (I would just fix it myself, but I don't understand how you think the documentation should be changed, since [it already mentions `/boot/efi/EFI/BOOT/xen.efi`](https://www.qubes-os.org/doc/uefi-troubleshooting/#boot-device-not-recognized-after-installing).)

**Comment by esote** [comment]
@andrewdavidwong Will do, I will notify you when I've submitted the PR.

**Comment by esote** [comment]
Wanted to give an update on this: at some point (likely from a Xen update), I no longer need to use `/boot/efi/EFI/BOOT`, it just works with `/boot/efi/EFI/qubes`, which is great!

Keep up the great work on Qubes!
