### ISSUE TITLE
Cannot remove duplicate f26 Qubes packages after updating to f27 or f28

### ISSUE THREAD

**Issue by esote** [QubesOS/qubes-issues#3926]
### Qubes OS version:

R4

### Affected component(s): 

```
qubes-core-agent-networking
qubes-core-agent-qrexec
```

---

### Steps to reproduce the behavior:

Update f26 to f27 or f28 following the [instructions](https://www.qubes-os.org/doc/template/fedora/upgrade-27-to-28/). I used the workaround for `python2-xcffib`. I am experiencing this issue in two standalone VMs and one template VM.

### Expected behavior:

All packages are upgraded and the update goes as expected.

### Actual behavior:

Errors when trying to remove the duplicate packages `qubes-core-agent-networking` and `qubes-core-agent-qrexec`. `dnf` shows the following:

```
$ sudo dnf dsync
Last metadata expiration check: 0:00:06 ago on Thu 24 May 2018 02:40:53 PM CDT.
Dependencies resolved.
========================================================================================================
 Package                           Arch         Version              Repository                    Size
========================================================================================================
Removing dependent packages:
 qubes-core-agent-networking       x86_64       4.0.28-1.fc26        @qubes-vm-r4.0-current        21 k
 qubes-core-agent-qrexec           x86_64       4.0.28-1.fc26        @qubes-vm-r4.0-current        71 k

Transaction Summary
========================================================================================================
Remove  2 Packages

Freed space: 92 k
Is this ok [y/N]: y
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                1/1 
  Running scriptlet: qubes-core-agent-networking-4.0.28-1.fc26.x86_64                               1/2 
/var/tmp/rpm-tmp.b0IvSI: line 1: fg: no job control
/var/tmp/rpm-tmp.b0IvSI: line 2: fg: no job control
/var/tmp/rpm-tmp.b0IvSI: line 3: fg: no job control
/var/tmp/rpm-tmp.b0IvSI: line 4: fg: no job control
error: %preun(qubes-core-agent-networking-4.0.28-1.fc26.x86_64) scriptlet failed, exit status 1
Error in PREUN scriptlet in rpm package qubes-core-agent-networking
Error in PREUN scriptlet in rpm package qubes-core-agent-networking
  Running scriptlet: qubes-core-agent-qrexec-4.0.28-1.fc26.x86_64                                   2/2 
error: qubes-core-agent-networking-4.0.28-1.fc26.x86_64: erase failed
/var/tmp/rpm-tmp.zsz1Tj: line 1: fg: no job control
error: %preun(qubes-core-agent-qrexec-4.0.28-1.fc26.x86_64) scriptlet failed, exit status 1
Error in PREUN scriptlet in rpm package qubes-core-agent-qrexec
Error in PREUN scriptlet in rpm package qubes-core-agent-qrexec
qubes-core-agent-qrexec-4.0.28-1.fc26.x86_64 was supposed to be removed but is not!
  Verifying        : qubes-core-agent-qrexec-4.0.28-1.fc26.x86_64                                   1/2 
qubes-core-agent-networking-4.0.28-1.fc26.x86_64 was supposed to be removed but is not!
  Verifying        : qubes-core-agent-networking-4.0.28-1.fc26.x86_64                               2/2 
Notifying dom0 about installed applications

Failed:
  qubes-core-agent-networking.x86_64 4.0.28-1.fc26     qubes-core-agent-qrexec.x86_64 4.0.28-1.fc26    

Error: Transaction failed
```

Notice that it is trying to remove the f26 versions of those packages. These two are duplicates, and the f28 versions are already installed:

```
$ sudo dnf list installed | grep -e "qubes-core-agent-networking" -e "qubes-core-agent-qrexec"
qubes-core-agent-networking.x86_64     4.0.28-1.fc26                    @qubes-vm-r4.0-current
qubes-core-agent-networking.x86_64     4.0.28-1.fc28                    @qubes-vm-r4.0-current
qubes-core-agent-qrexec.x86_64         4.0.28-1.fc26                    @qubes-vm-r4.0-current
qubes-core-agent-qrexec.x86_64         4.0.28-1.fc28                    @qubes-vm-r4.0-current
```

### General notes:

After updating f26->f28, I am also experiencing a lot of errors about missing files and symbolic links in `/usr/lib64`. For example, after updating I was unable to use the `man` command, and to fix it I had to create a symbolic link `libgdbm.so.4 -> libgdbm.so.5.0.0`. I am also experiencing an issue with `valgrind` (looks like about `ld-linux-x86-64.so.2`). I may find more issues as I continue using the f28 VMs.

When going from f26->f27 I do not experience issues with `.so` files, but still cannot remove the duplicate Qubes packages.

---

**Comment by SmazeBrume** [comment]
I experienced the same issues as @esote when upgrading from f26 to f28 this evening (I also used the workaround for ` python2-xcffib ` ).  Issue also existed for an upgrade from f26 to f27.

I don't know if a dnf history would help anyone, but I've appended it below.

```
Begin time     : Thu May 24 21:18:31 2018
Begin rpmdb    : 1279:f43850642bb1b06e4384561c7d4f6dbf294f4c8f
End time       : Thu May 24 21:27:11 2018 (8 minutes)
End rpmdb      : 1474:d93b4228fec2b28a72ad6f5b2af0068f6bd19f60
User           :  <user>
Return-Code    : Success
Command Line   : --releasever=28 distro-sync --best --allowerasing -x python2-xcffib -x qubes-gui-vm -x qubes-gui-agent
Transaction performed with:
    Upgraded      dnf-2.7.5-2.fc26.noarch  (unknown)
    Upgraded      rpm-4.13.1-1.fc26.x86_64 @updates/26
Packages Altered:
 
[ ... ]

Scriptlet output:
   1 warning: /etc/group created as /etc/group.rpmnew
   2 warning: /etc/gshadow created as /etc/gshadow.rpmnew
   3 warning: /etc/passwd created as /etc/passwd.rpmnew
   4 warning: /etc/shadow created as /etc/shadow.rpmnew
   5 Detected system with incompatible nobody defined, creating /etc/systemd/dont-synthesize-nobody
   6 warning: /etc/pulse/client.conf created as /etc/pulse/client.conf.rpmnew
   7 warning: /etc/cups/cups-browsed.conf created as /etc/cups/cups-browsed.conf.rpmnew
   8 Error! DKMS tree already contains: u2mfn-4.0.19
   9 You cannot add the same module/version combo more than once.
  10 warning: %post(qubes-kernel-vm-support-4.0.19-1.fc28.x86_64) scriptlet failed, exit status 3
  11 warning: /etc/yum.repos.d/rpmfusion-free-updates.repo created as /etc/yum.repos.d/rpmfusion-free-updates.repo.rpmnew
  12 /var/tmp/rpm-tmp.rknkP6: line 1: fg: no job control
  13 /var/tmp/rpm-tmp.rknkP6: line 2: fg: no job control
  14 /var/tmp/rpm-tmp.rknkP6: line 3: fg: no job control
  15 /var/tmp/rpm-tmp.rknkP6: line 4: fg: no job control
  16 error: %preun(qubes-core-agent-networking-4.0.28-1.fc26.x86_64) scriptlet failed, exit status 1
  17 error: qubes-core-agent-networking-4.0.28-1.fc26.x86_64: erase failed
  18 
  19 ------------------------------
  20 Deleting module version: 4.0.19
  21 completely from the DKMS tree.
  22 ------------------------------
  23 Done.
  24 /var/tmp/rpm-tmp.IygMaZ: line 1: fg: no job control
  25 error: %preun(qubes-core-agent-qrexec-4.0.28-1.fc26.x86_64) scriptlet failed, exit status 1
  26 error: qubes-core-agent-qrexec-4.0.28-1.fc26.x86_64: erase failed
  27 
  28 UPGRADE: Automatically re-enabling default systemd units: fedora-import-state.service fedora-readonly.service
  29 
  30 warning: file /lib/i686/nosegneg/libthread_db-1.0.so: remove failed: No such file or directory
  31 warning: file /lib/i686/nosegneg/librt-2.25.so: remove failed: No such file or directory
  32 warning: file /lib/i686/nosegneg/libpthread-2.25.so: remove failed: No such file or directory
  33 warning: file /lib/i686/nosegneg/libm-2.25.so: remove failed: No such file or directory
  34 warning: file /lib/i686/nosegneg/libc-2.25.so: remove failed: No such file or directory
  35 warning: /etc/yum.repos.d/rpmfusion-nonfree.repo saved as /etc/yum.repos.d/rpmfusion-nonfree.repo.rpmsave
  36 warning: /etc/yum.repos.d/rpmfusion-nonfree-updates.repo saved as /etc/yum.repos.d/rpmfusion-nonfree-updates.repo.rpmsave
  37 grubby fatal error: unable to find a suitable template
  38 warning: file /lib/modules/4.15.10-200.fc26.x86_64/updates: remove failed: No such file or directory
  39 grubby fatal error: unable to find a suitable template
  40 grubby fatal error: unable to find a suitable template
  41 grubby: doing this would leave no kernel entries. Not writing out new config.

```

**Comment by taradiddles** [comment]
just saw this issue after posting to the ML...

there's likely an issue with the `preun` rpm script of the f26 (and f27?) versions of qubes-core-agent-networking and qubes-core-agent-qrexec - the rpm macro used there seems to be buggy, while the f28 version uses the plain `systemctl` command.

fix:

~~~
sudo rpm -e --noscripts qubes-core-agent-networking-4.0.28-1.fc26.x86_64 \
     qubes-core-agent-qrexec-4.0.28-1.fc26.x86_64
sudo dnf reinstall qubes-core-agent-networking qubes-core-agent-qrexec
~~~

no idea about the  .so issue of the OP though

**Comment by esote** [comment]
@taradiddles Your fix has worked for me (f26->f27).

I will now test f27->f28 and report back. As far as the .so issue, that only happened when going f26->f28, and I'll see if it then happens f27->f28.

**Comment by marmarek** [comment]
@taradiddles diagnosis is correct, package scripts are broken:
```
$ rpm -q --scripts qubes-core-agent-networking
postinstall scriptlet (using /bin/sh):
%systemd_post qubes-firewall.service
%systemd_post qubes-iptables.service
%systemd_post qubes-network.service
%systemd_post qubes-updates-proxy.service
preuninstall scriptlet (using /bin/sh):
%systemd_preun qubes-firewall.service
%systemd_preun qubes-iptables.service
%systemd_preun qubes-network.service
%systemd_preun qubes-updates-proxy.service
```
Probably missing BuildRequires defining those macros.

**Comment by marmarek** [comment]
>    1 warning: /etc/group created as /etc/group.rpmnew
   2 warning: /etc/gshadow created as /etc/gshadow.rpmnew
   3 warning: /etc/passwd created as /etc/passwd.rpmnew
   4 warning: /etc/shadow created as /etc/shadow.rpmnew
   5 Detected system with incompatible nobody defined, creating /etc/systemd/dont-synthesize-nobody
   6 warning: /etc/pulse/client.conf created as /etc/pulse/client.conf.rpmnew
   7 warning: /etc/cups/cups-browsed.conf created as /etc/cups/cups-browsed.conf.rpmnew

You may need to look at those .rpmnew files and apply changes to original files. But it's unlikely the reason for other problems.

**Comment by andrewdavidwong** [comment]
@marmarek: How can we fix this for future upgraders? Unless we update the code or the documentation (or both), we're about to get the same question many more times from a lot of very confused users.

**Comment by marmarek** [comment]
The %systemd macro fix is on its way. Handling rpmnew files is a part official [fedora upgrade process](https://fedoraproject.org/wiki/DNF_system_upgrade#Update_system_configuration_files).

**Comment by esote** [comment]
As @marmarek is working on the fix for the main issue I was having, for my "missing .so" issue, it all comes down to missing a few packages for compatibility. I will edit this comment as I fix more things, but so far:

* `man` is missing `libgdbm.so.4` -- solution: install `compat-gdbm` package
* `valgrind` is missing `ld-linux-x86-64.so.2` -- Fedora 28 is missing glibc-debug for x86_64, temporary fix: download and install from .rpm [here](https://rpmfind.net/linux/rpm2html/search.php?query=glibc-debuginfo&submit=Search+...&system=&arch=x86_64)

**Comment by andrewdavidwong** [comment]
@esote:
> As @marmarek is working on the fix for the main issue I was having, for my "missing .so" issue, it seems to come down to missing packages. I will edit this comment as I come across more things. [...]

You might want to file a separate issue for this.

**Comment by akkuladezeit** [comment]
still got this problem. 
I tried to update the f26 template to current-testing (sudo yum update --enablerepo=qubes-vm-r4.0-current-testing)
is will try to update some packages .. also
qubes-core-agent-networking-4.0.28-1.fc26.x86_64 -> qubes-core-agent-networking-4.0.30-1.fc26.x86_64 
qubes-core-agent-qrexec.x86_64 4.0.28-1.fc26 -> qubes-core-agent-qrexec.x86_64 4.0.30-1.fc26
but this is getting the same error as i try to upgrade directly to f27...

sudo yum update --enablerepo=qubes-vm-r4.0-current-testing
Qubes OS Repository for VM (updates-testing)                                                                                                             638 kB/s | 269 kB     00:00    
Last metadata expiration check: 0:00:00 ago on Tue Jun 12 23:35:05 2018.
Dependencies resolved.
=========================================================================================================================================================================================
 Package                                                  Arch                         Version                                 Repository                                           Size
=========================================================================================================================================================================================
Upgrading:
 python3-dnf-plugins-qubes-hooks                          x86_64                       4.0.30-1.fc26                           qubes-vm-r4.0-current-testing                       8.8 k
 qubes-core-agent                                         x86_64                       4.0.30-1.fc26                           qubes-vm-r4.0-current-testing                       110 k
 qubes-core-agent-dom0-updates                            x86_64                       4.0.30-1.fc26                           qubes-vm-r4.0-current-testing                       8.5 k
 qubes-core-agent-nautilus                                x86_64                       4.0.30-1.fc26                           qubes-vm-r4.0-current-testing                        11 k
 qubes-core-agent-network-manager                         x86_64                       4.0.30-1.fc26                           qubes-vm-r4.0-current-testing                       9.5 k
 qubes-core-agent-networking                              x86_64                       4.0.30-1.fc26                           qubes-vm-r4.0-current-testing                        18 k
 qubes-core-agent-passwordless-root                       x86_64                       4.0.30-1.fc26                           qubes-vm-r4.0-current-testing                       8.5 k
 qubes-core-agent-qrexec                                  x86_64                       4.0.30-1.fc26                           qubes-vm-r4.0-current-testing                        31 k
 qubes-core-agent-systemd                                 x86_64                       4.0.30-1.fc26                           qubes-vm-r4.0-current-testing                        22 k
 qubes-input-proxy-sender                                 x86_64                       1.0.12-1.fc26                           qubes-vm-r4.0-current-testing                        15 k
 xen-libs                                                 x86_64                       2001:4.8.3-8.fc26                       qubes-vm-r4.0-current-testing                       559 k
 xen-licenses                                             x86_64                       2001:4.8.3-8.fc26                       qubes-vm-r4.0-current-testing                        46 k
 xen-qubes-vm                                             x86_64                       2001:4.8.3-8.fc26                       qubes-vm-r4.0-current-testing                       138 k

Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                                                                                                 1/1 
  Running scriptlet: xen-licenses-2001:4.8.3-8.fc26.x86_64                                                                                                                           1/1 
  Upgrading        : xen-licenses-2001:4.8.3-8.fc26.x86_64                                                                                                                          1/26 
  Upgrading        : xen-libs-2001:4.8.3-8.fc26.x86_64                                                                                                                              2/26 
  Running scriptlet: xen-libs-2001:4.8.3-8.fc26.x86_64                                                                                                                              2/26 
  Upgrading        : python3-dnf-plugins-qubes-hooks-4.0.30-1.fc26.x86_64                                                                                                           3/26 
  Upgrading        : qubes-core-agent-qrexec-4.0.30-1.fc26.x86_64                                                                                                                   4/26 
  Running scriptlet: qubes-core-agent-qrexec-4.0.30-1.fc26.x86_64                                                                                                                   4/26 
  Running scriptlet: qubes-core-agent-4.0.30-1.fc26.x86_64                                                                                                                          5/26 
  Upgrading        : qubes-core-agent-4.0.30-1.fc26.x86_64                                                                                                                          5/26 
  Running scriptlet: qubes-core-agent-4.0.30-1.fc26.x86_64                                                                                                                          5/26 
  Upgrading        : qubes-core-agent-networking-4.0.30-1.fc26.x86_64                                                                                                               6/26 
  Running scriptlet: qubes-core-agent-networking-4.0.30-1.fc26.x86_64                                                                                                               6/26 
  Upgrading        : qubes-core-agent-network-manager-4.0.30-1.fc26.x86_64                                                                                                          7/26 
  Running scriptlet: qubes-core-agent-network-manager-4.0.30-1.fc26.x86_64                                                                                                          7/26 
  Upgrading        : qubes-core-agent-dom0-updates-4.0.30-1.fc26.x86_64                                                                                                             8/26 
  Upgrading        : qubes-core-agent-nautilus-4.0.30-1.fc26.x86_64                                                                                                                 9/26 
  Upgrading        : qubes-core-agent-systemd-4.0.30-1.fc26.x86_64                                                                                                                 10/26 
  Running scriptlet: qubes-core-agent-systemd-4.0.30-1.fc26.x86_64                                                                                                                 10/26 
  Upgrading        : xen-qubes-vm-2001:4.8.3-8.fc26.x86_64                                                                                                                         11/26 
  Running scriptlet: xen-qubes-vm-2001:4.8.3-8.fc26.x86_64                                                                                                                         11/26 
  Upgrading        : qubes-input-proxy-sender-1.0.12-1.fc26.x86_64                                                                                                                 12/26 
  Running scriptlet: qubes-core-agent-passwordless-root-4.0.30-1.fc26.x86_64                                                                                                       13/26 
  Upgrading        : qubes-core-agent-passwordless-root-4.0.30-1.fc26.x86_64                                                                                                       13/26 
  Running scriptlet: qubes-core-agent-systemd-4.0.28-1.fc26.x86_64                                                                                                                 14/26 
  Cleanup          : qubes-core-agent-systemd-4.0.28-1.fc26.x86_64                                                                                                                 14/26 
  Running scriptlet: qubes-core-agent-systemd-4.0.28-1.fc26.x86_64                                                                                                                 14/26 
  Cleanup          : qubes-core-agent-network-manager-4.0.28-1.fc26.x86_64                                                                                                         15/26 
  Running scriptlet: qubes-core-agent-networking-4.0.28-1.fc26.x86_64                                                                                                              16/26 
/var/tmp/rpm-tmp.7pb7wG: line 1: fg: no job control
/var/tmp/rpm-tmp.7pb7wG: line 2: fg: no job control
/var/tmp/rpm-tmp.7pb7wG: line 3: fg: no job control
/var/tmp/rpm-tmp.7pb7wG: line 4: fg: no job control
error: %preun(qubes-core-agent-networking-4.0.28-1.fc26.x86_64) scriptlet failed, exit status 1
Error in PREUN scriptlet in rpm package qubes-core-agent-networking
Error in PREUN scriptlet in rpm package qubes-core-agent-networking
  Cleanup          : qubes-core-agent-nautilus-4.0.28-1.fc26.x86_64                                                                                                                17/26 
error: qubes-core-agent-networking-4.0.28-1.fc26.x86_64: erase failed
  Cleanup          : qubes-core-agent-dom0-updates-4.0.28-1.fc26.x86_64                                                                                                            18/26 
  Cleanup          : qubes-core-agent-passwordless-root-4.0.28-1.fc26.x86_64                                                                                                       19/26 
  Running scriptlet: qubes-core-agent-passwordless-root-4.0.28-1.fc26.x86_64                                                                                                       19/26 
  Running scriptlet: qubes-core-agent-qrexec-4.0.28-1.fc26.x86_64                                                                                                                  20/26 
/var/tmp/rpm-tmp.DhfJzn: line 1: fg: no job control
error: %preun(qubes-core-agent-qrexec-4.0.28-1.fc26.x86_64) scriptlet failed, exit status 1
Error in PREUN scriptlet in rpm package qubes-core-agent-qrexec
Error in PREUN scriptlet in rpm package qubes-core-agent-qrexec
  Running scriptlet: qubes-core-agent-4.0.28-1.fc26.x86_64                                                                                                                         21/26 
error: qubes-core-agent-qrexec-4.0.28-1.fc26.x86_64: erase failed
  Cleanup          : qubes-core-agent-4.0.28-1.fc26.x86_64                                                                                                                         21/26 
  Running scriptlet: qubes-core-agent-4.0.28-1.fc26.x86_64                                                                                                                         21/26 
  Running scriptlet: xen-qubes-vm-2001:4.8.3-7.fc26.x86_64                                                                                                                         22/26 
  Cleanup          : xen-qubes-vm-2001:4.8.3-7.fc26.x86_64                                                                                                                         22/26 
  Running scriptlet: xen-qubes-vm-2001:4.8.3-7.fc26.x86_64                                                                                                                         22/26 
  Cleanup          : python3-dnf-plugins-qubes-hooks-4.0.28-1.fc26.x86_64                                                                                                          23/26 
  Cleanup          : xen-libs-2001:4.8.3-7.fc26.x86_64                                                                                                                             24/26 
  Running scriptlet: xen-libs-2001:4.8.3-7.fc26.x86_64                                                                                                                             24/26 
  Cleanup          : xen-licenses-2001:4.8.3-7.fc26.x86_64                                                                                                                         25/26 
  Cleanup          : qubes-input-proxy-sender-1.0.11-1.fc26.x86_64                                                                                                                 26/26 
  Running scriptlet: qubes-core-agent-4.0.30-1.fc26.x86_64                                                                                                                         26/26 
  Running scriptlet: qubes-input-proxy-sender-1.0.11-1.fc26.x86_64                                                                                                                 26/26 
Running as unit: run-reb5ef270e7d64076aa86f553678b164e.service
Running as unit: run-r77194dc28f794ba2b799c554d708dd90.service
  Verifying        : python3-dnf-plugins-qubes-hooks-4.0.30-1.fc26.x86_64                                                                                                           1/26 
  Verifying        : qubes-core-agent-4.0.30-1.fc26.x86_64                                                                                                                          2/26 
  Verifying        : qubes-core-agent-dom0-updates-4.0.30-1.fc26.x86_64                                                                                                             3/26 
  Verifying        : qubes-core-agent-nautilus-4.0.30-1.fc26.x86_64                                                                                                                 4/26 
  Verifying        : qubes-core-agent-network-manager-4.0.30-1.fc26.x86_64                                                                                                          5/26 
  Verifying        : qubes-core-agent-networking-4.0.30-1.fc26.x86_64                                                                                                               6/26 
  Verifying        : qubes-core-agent-passwordless-root-4.0.30-1.fc26.x86_64                                                                                                        7/26 
  Verifying        : qubes-core-agent-qrexec-4.0.30-1.fc26.x86_64                                                                                                                   8/26 
  Verifying        : qubes-core-agent-systemd-4.0.30-1.fc26.x86_64                                                                                                                  9/26 
  Verifying        : qubes-input-proxy-sender-1.0.12-1.fc26.x86_64                                                                                                                 10/26 
  Verifying        : xen-libs-2001:4.8.3-8.fc26.x86_64                                                                                                                             11/26 
  Verifying        : xen-qubes-vm-2001:4.8.3-8.fc26.x86_64                                                                                                                         12/26 
  Verifying        : xen-licenses-2001:4.8.3-8.fc26.x86_64                                                                                                                         13/26 
  Verifying        : qubes-input-proxy-sender-1.0.11-1.fc26.x86_64                                                                                                                 14/26 
  Verifying        : xen-libs-2001:4.8.3-7.fc26.x86_64                                                                                                                             15/26 
  Verifying        : python3-dnf-plugins-qubes-hooks-4.0.28-1.fc26.x86_64                                                                                                          16/26 
  Verifying        : xen-licenses-2001:4.8.3-7.fc26.x86_64                                                                                                                         17/26 
  Verifying        : xen-qubes-vm-2001:4.8.3-7.fc26.x86_64                                                                                                                         18/26 
  Verifying        : qubes-core-agent-4.0.28-1.fc26.x86_64                                                                                                                         19/26 
  Verifying        : qubes-core-agent-dom0-updates-4.0.28-1.fc26.x86_64                                                                                                            20/26 
  Verifying        : qubes-core-agent-nautilus-4.0.28-1.fc26.x86_64                                                                                                                21/26 
  Verifying        : qubes-core-agent-network-manager-4.0.28-1.fc26.x86_64                                                                                                         22/26 
qubes-core-agent-networking-4.0.28-1.fc26.x86_64 was supposed to be removed but is not!
  Verifying        : qubes-core-agent-networking-4.0.28-1.fc26.x86_64                                                                                                              23/26 
  Verifying        : qubes-core-agent-passwordless-root-4.0.28-1.fc26.x86_64                                                                                                       24/26 
qubes-core-agent-qrexec-4.0.28-1.fc26.x86_64 was supposed to be removed but is not!
  Verifying        : qubes-core-agent-qrexec-4.0.28-1.fc26.x86_64                                                                                                                  25/26 
  Verifying        : qubes-core-agent-systemd-4.0.28-1.fc26.x86_64                                                                                                                 26/26 
Notifying dom0 about installed applications

Upgraded:
  python3-dnf-plugins-qubes-hooks.x86_64 4.0.30-1.fc26        qubes-core-agent.x86_64 4.0.30-1.fc26                        qubes-core-agent-dom0-updates.x86_64 4.0.30-1.fc26            
  qubes-core-agent-nautilus.x86_64 4.0.30-1.fc26              qubes-core-agent-network-manager.x86_64 4.0.30-1.fc26        qubes-core-agent-passwordless-root.x86_64 4.0.30-1.fc26       
  qubes-core-agent-systemd.x86_64 4.0.30-1.fc26               qubes-input-proxy-sender.x86_64 1.0.12-1.fc26                xen-libs.x86_64 2001:4.8.3-8.fc26                             
  xen-licenses.x86_64 2001:4.8.3-8.fc26                       xen-qubes-vm.x86_64 2001:4.8.3-8.fc26                       

Failed:
  qubes-core-agent-networking.x86_64 4.0.30-1.fc26                                              qubes-core-agent-qrexec.x86_64 4.0.30-1.fc26                                             

Error: Transaction failed


reinstall is not working...
[user@fedora-26-test ~]$ sudo dnf reinstall qubes-core-agent-networking qubes-core-agent-qrexec --enablerepo=qubes-vm-r4.0-current-testing --allowerasing
Last metadata expiration check: 0:10:35 ago on Tue Jun 12 23:13:20 2018.
Error: 
 Problem 1: cannot install both qubes-core-agent-networking-4.0.30-1.fc26.x86_64 and qubes-core-agent-networking-4.0.28-1.fc26.x86_64
  - conflicting requests
 Problem 2: cannot install both qubes-core-agent-qrexec-4.0.30-1.fc26.x86_64 and qubes-core-agent-qrexec-4.0.28-1.fc26.x86_64
  - conflicting requests

**Comment by marmarek** [comment]
Update scripts of qubes-core-agent-*-4.0.28 are broken, you need to remove it manually, bypassing update scripts:
1. Make sure you have 4.0.30 version installed!
2. Call `sudo rpm -e --noscripts qubes-core-agent-qrexec-4.0.28-1.fc26.x86_64 qubes-core-agent-networking-4.0.28-1.fc26.x86_64`

**Comment by akkuladezeit** [comment]
Yeah i think both are installed
sudo dnf list installed | grep -e "qubes-core-agent-networking" -e "qubes-core-agent-qrexec"
qubes-core-agent-networking.x86_64      4.0.28-1.fc26              @qubes-vm-r4.0-current
qubes-core-agent-networking.x86_64      4.0.30-1.fc26              @qubes-vm-r4.0-current-testing
qubes-core-agent-qrexec.x86_64          4.0.28-1.fc26              @qubes-vm-r4.0-current
qubes-core-agent-qrexec.x86_64          4.0.30-1.fc26              @qubes-vm-r4.0-current-testing

sudo rpm -e --noscripts qubes-core-agent-qrexec-4.0.28-1.fc26.x86_64 qubes-core-agent-networking-4.0.28-1.fc26.x86_64

sudo dnf list installed | grep -e "qubes-core-agent-networking" -e "qubes-core-agent-qrexec"
qubes-core-agent-networking.x86_64      4.0.30-1.fc26                   @qubes-vm-r4.0-current-testing
qubes-core-agent-qrexec.x86_64          4.0.30-1.fc26                   @qubes-vm-r4.0-current-testing

after that the update to f27 seams to work.  maybe this should be added to the https://www.qubes-os.org/doc/template/fedora/upgrade-26-to-27/ ?
