### ISSUE TITLE
Warnings or non important messages handled by journald

### ISSUE THREAD

**Issue by donob4n** [QubesOS/qubes-issues#3927]
### Qubes OS version:

Qubes 4

### Affected component(s): 

journald / hardisk usage

---

### Steps to reproduce the behavior:

Hi,

I noticed tons of warnings from Vinagre,
`
(vinagre:17442): Gtk-WARNING **: Drawing a gadget with negative dimensions. Did you forget to allocate a size? (node box owner ViewAutoDrawer)
`
https://bugzilla.redhat.com/show_bug.cgi?id=1404688

After three days uptime (which plenty hours of sleep state) I have near 1GB on /var/log. I am trying to open vinagre from a desktop shortcut and discard this warnings, maybe an script calling "vinagre &> /dev/null" but I think some default alternative would be nice.

In my opinion standard user apps should not write warnings or messages to journald which is supposed to "system messages". 

At least it would be nice to have an option on 'qvm-run' for change this behaviour (--no-log?).

### Expected behavior:

Journal should handle only system relevant messages and maybe some important application. 

### Actual behavior:

It logs tons of unimportant messages and warnings.

### General notes:

---

**Comment by andrewdavidwong** [comment]
Possibly `notourbug`, but I'll leave that determination up to @marmarek.

**Comment by marmarek** [comment]
Yes, that's not the right place for such bug report.
The idea with a wrapper script redirecting stderr to /dev/null should work.

**Comment by donob4n** [comment]
Ok. After thinking about this maybe the useful thing would be a centralized way for see all logs from the system (log files and journalds).

**Comment by marmarek** [comment]
https://github.com/QubesOS/qubes-issues/issues/830 ?

**Comment by donob4n** [comment]
Yes, I was thinking about it.
