### ISSUE TITLE
All available applications for templateVM incorrectly appearing in "Start Menu" of dom0

### ISSUE THREAD

**Issue by SmazeBrume** [QubesOS/qubes-issues#3929]
### Qubes OS version:

R4.0

### Affected component(s): 

Shortcuts to applications in TemplateVM appearing in "Start Menu" in dom0

---

### Steps to reproduce the behavior:

Upgraded f26 template to f27 template.

### Expected behavior:

There should be no application shortcuts appearing in the "Start Menu" in dom0, other than those applications which have been moved from the "Available" column to the "Selected" column under the "Applications" tab of the Qube Settings Manager.  That is, if there were two "Selected" applications in the original template, then only those two "Selected" applications should appear in the "Start Menu" for the upgraded template. 

### Actual behavior:

All applications listed in the "Available" column of the "Applications" tab appear in the "Start Menu" in dom0 for the templateVM, even though no applications have been selected and moved into the "Selected" column.

### General notes:

Tried refreshing the applications in the Qubes Setting Manager to confirm that no applications had been selected.  This had no effect and all "Available" applications still appeared in the dom0 "Start Menu".

Also attempted to manually sync the applications in dom0 using ` qvm-sync-appmenus fedora-27` and then refreshed the applications in the Qubes Setting Manager.  This also had no effect and all "Available" applications still appeared, instead of the intended no applications.

---

**Comment by nailgao** [comment]
@andrewdavidwong  duplicate indeed. sorry for giving the trouble!

**Comment by marmarta** [comment]
I tried to duplicate this by updating various templates, and couldn't get it. Closing, please reopen if someone encounters this again.
