### ISSUE TITLE
Installer refers to URL that returns 404

### ISSUE THREAD

**Issue by Forbo** [QubesOS/qubes-issues#3932]
### Qubes OS version:

4.0

### Affected component(s): 

Installer

---

### Steps to reproduce the behavior:

Attempt to install on hardware where the "Unsupported Hardware Detected" dialog appears. It refers you to `https://www.qubes-os.org/system-requirements/` which returns a 404. The actual URL should be `https://www.qubes-os.org/doc/system-requirements/`

### Expected behavior:

Reference `https://www.qubes-os.org/doc/system-requirements/` in the error dialog.

### Actual behavior:

Refers to `https://www.qubes-os.org/system-requirements/` which returns a 404.

### General notes:

More of an annoyance than anything, very minor adjustment. Looks like there are two instances of the incorrect URL being used.
 - https://github.com/QubesOS/qubes-installer-qubes-os/blob/fbd48c789f390417975f489626ac5423bfa44ec4/anaconda/pyanaconda/ui/tui/spokes/warnings_spoke.py
- https://github.com/QubesOS/qubes-installer-qubes-os/blob/7489992dddf94aae18483d4ee5dea45506ab05df/anaconda/pyanaconda/ui/gui/spokes/welcome.glade

---

### Related issues:

N/A?

**Comment by marmarek** [comment]
@andrewdavidwong could you add redirection?

**Comment by andrewdavidwong** [comment]
Thanks for spotting this!

The URL has been `https://www.qubes-os.org/doc/system-requirements/` [since 2015-10-28](https://github.com/QubesOS/qubes-doc/blame/master/hardware/system-requirements.md#L4), so someone probably just made a typo when adding it to the "Unsupported Hardware Detected" message.

In the meantime, I'll add a redirect from `https://www.qubes-os.org/system-requirements/` to `https://www.qubes-os.org/doc/system-requirements/` so that it doesn't 404.

**Comment by Forbo** [comment]
Oh, wow, that was fast! I went in to edit with the two instances I had found and you had already tagged and reviewed.

**Comment by andrewdavidwong** [comment]
@Forbo:
> Oh, wow, that was fast! I went in to edit with the two instances I had found and you had already tagged and reviewed.

Two instances?

**Comment by Forbo** [comment]
Yes, one in `warnings_spoke.py` and one in `welcome.glade`. I added links for them in the general notes of the original submission. I just found them when searching the repo for `system-requirements`, which returned 14 results, only two of which lacked the `/doc/` portion of the URL.

**Comment by andrewdavidwong** [comment]
Oh, I see. Thanks!
