### ISSUE TITLE
Too much pulseaudio info/debug log 

### ISSUE THREAD

**Issue by donob4n** [QubesOS/qubes-issues#3933]
### Qubes OS version:

R4

### Affected component(s): 

journald, disk usage

---

### Steps to reproduce the behavior:

I found this messages on a lot of vm's, even on fedora template:
May 26 21:44:15 media pulseaudio[828]: write_to_vchan: all=3864000 waited=62012 nonwaited=3801988 full=0

May 26 21:44:58 media pulseaudio[828]: write_to_vchan: all=3872000 waited=62058 nonwaited=3809942 full=0

May 26 21:45:42 media pulseaudio[828]: write_to_vchan: all=3880000 waited=62099 nonwaited=3817901 full=0

May 26 21:46:25 media pulseaudio[828]: write_to_vchan: all=3888000 waited=62141 nonwaited=3825859 full=0

### Expected behavior:

If this is a useful info or a debug message log it a reasonable rate, else remove it.
If it is a debug info maybe it should only appear with some debug mode enabled.

### Actual behavior:

It logs more than one per minute when playing audio.

### General notes:

It is logged here https://github.com/QubesOS/qubes-gui-agent-linux/blob/4427218dc382c66a98e22d5e67bdef5a87a5b3ba/pulse/module-vchan-sink.c#L257 .  

---

**Comment by andrewdavidwong** [comment]
> @marmarek added the `good first issue` label 5 hours ago

But this isn't @donob4n's first issue. :slightly_smiling_face:

**Comment by andrewdavidwong** [comment]
Possibly related: #830

**Comment by marmarek** [comment]
> But this isn't @donob4n's first issue.

No, I'm marking low hanging fruits for first time contributors.

**Comment by andrewdavidwong** [comment]
> No, I'm marking low hanging fruits for first time contributors.

Ok, but it makes it sound like someone new to reporting issues did a good job on their first try. Do you mind if I rename the label to clarify?

**Comment by marmarek** [comment]
Personally I don't mind, but that's one of [github default labels](https://help.github.com/articles/about-labels/#using-default-labels).

**Comment by donob4n** [comment]
lol

So is this info useful for something? Better removing it, reducing output rate or doing it optional?

**Comment by marmarek** [comment]
@andrewdavidwong Oh, looks like this is not only one of default labels, but also [actively](https://groups.google.com/forum/#!topic/pandoc-discuss/mrFsj5RzNFA) [promoted by github](https://help.github.com/articles/helping-new-contributors-find-your-project-with-labels/)

@donob4n It's useful for debugging very weird cases we haven't seen for years. Either removing or making it optional is ok.

**Comment by andrewdavidwong** [comment]
> Personally I don't mind, but that's one of github default labels.
> 
> @andrewdavidwong Oh, looks like this is not only one of default labels, but also actively promoted by github

Ok, looks like my beef is with GitHub, not with you. :rofl: 

No problem. We can stick with this label so that people who are familiar with it from other projects will recognize it here.

**Comment by sstt011** [comment]
I am interested in making a PR for this - should be easy. However, I am worried about the GPG signing. Due to classified reasons, (for now at least) I must keep full anonymity. As a result, I have simply kept my GitHub name as the "Full name" and my GitHub commit email as the "Email address". Is this OK, or is this a problem?

**Comment by andrewdavidwong** [comment]
> I am interested in making a PR for this - should be easy. However, I am worried about the GPG signing. Due to classified reasons, (for now at least) I must keep full anonymity. As a result, I have simply kept my GitHub name as the "Full name" and my GitHub commit email as the "Email address". Is this OK, or is this a problem?

Shouldn't be a problem. We don't require anyone to use their "real" name for anything.

**Comment by marmarek** [comment]
As Andrew said, we require to use signatures, but not real names. This is mostly because we don't [trust infrastructure](https://www.qubes-os.org/faq/#what-does-it-mean-to-distrust-the-infrastructure), github included. This is one mitigation we take, to not rely on github authentication system too much.

See also [here](https://help.github.com/articles/about-commit-email-addresses/) how to keep email private on github.

**Comment by sstt011** [comment]
@marmarek @andrewdavidwong Thanks!

**Comment by donob4n** [comment]
If the debug is removed are the vars used for something?
	`static int all = 0, waited = 0, nonwaited = 0, full = 0;`

**Comment by marmarek** [comment]
> static int all = 0, waited = 0, nonwaited = 0, full = 0;

I don't think so.
