### ISSUE TITLE
Test and publish template/standalonevm 3.2->4.0 migration instruction.

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#3934]
I've realized we haven't published migration instruction for this case. While templates/standalonevms are mostly functional when imported from 3.2 backup, there is some missing functionality (for example #3906).

Here is some preliminary version: https://github.com/QubesOS/qubes-issues/issues/1854#issuecomment-391073371
One thing based on feedback there from @davex25 - all of this needs to be performed in root shell (`sudo -s`, or `qvm-run -u root ... xterm`), not individual `sudo` calls. Because you loose root access before installing `qubes-vm-recommended` metapackage.

**Comment by donob4n** [comment]
I have gui broken in standadlone vm's I restored from 3.2

I could get a bash from dom0 via qvm-run, I modified the sources and do an upgrade. But then I lost qrexec too.

**Comment by davex25** [comment]
Documentation should include a step for changing http to https in qubes repo file during the upgrade.

**Comment by awokd** [comment]
[Here's](https://github.com/Qubes-Community/Contents/blob/master/docs/system/restore-3.2.md) what we (mostly @taradiddles) came up with. If this is what you had in mind, I'll submit to qubes-doc and we can fine-tune there if needed.

**Comment by andrewdavidwong** [comment]
Closing since both 3.2 and 4.0 are EOL.
