### ISSUE TITLE
Mechanism for triggering template build

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#3935]
Right now template build require direct access to build machine. This is bad for various reasons, including:
 - lack of transparency
 - inability to delegate it

We've using a better mechanism for individual packages for some time. It consists of:
 - a script that build and upload to current-testing a package that got new signed version tag
 - a script that process signed comment on github to migrate package from current-testing to current (#2573)

This works well for normal packages, lets do something similar for templates.
The problem here is there is no natural place for template version tag - template consists of more than just linux-template-builder - in many cases we need to build new template after just updating individual packages (which doesn't involve any change in linux-template-builder).

I propose using something similar to #2573 for triggering the build too. The work flow would be:
 - template maintainer open new issue (in updates-status repository? or here?) with inline-signed command to build the template
 - appropriate script verify the signature and proceed to build the template (using `make build-template-in-dispvm`)
 - when build succeed, result is reported to https://github.com/QubesOS/updates-status/issues repository and template is uploaded to online repository
 - build failure would be also reported, in https://github.com/QubesOS/build-issues/issues

Open questions:
1. How build trigger command should look like (what we need there)? My current idea:

        build-template QUBES_VERSION TEMPLATE TIMESTAMP

    For example: `build-template r4.0 fc28+minimal 201805171636`

2. Do we need templates-itl-testing and templates-community-testing repositories and upload templates there first? And the use similar workflow to migrate them later to final repositories?

3. Replay protection - in the example above I've added TIMESTAMP (which will be used as `%release` part of template version) exactly for this reason. The script would verify if it isn't too far in the past. Any better idea?

4. Template package version is pretty meaningless right now (it's template builder version (but not builder plugin - containing most actual building scripts) + timestamp). Maybe we could use this occasion to change this too? For example specify template version manually too? Or build it based on qubes version (3.2.x for templates for Qubes 3.2 etc)?

This all would for example allow @adrelanos to trigger new Whonix template build or @fepitre for Fedora and CentOS, or @ptitdoc for Archlinux, or @unman for Debian.

cc @andrewdavidwong

**Comment by andrewdavidwong** [comment]
> Do we need templates-itl-testing and templates-community-testing repositories and upload templates there first? And the use similar workflow to migrate them later to final repositories?

This would probably be a good idea.

**Comment by marmarek** [comment]
@adrelanos see above questions, any opinion? Most of required changes are already done, I'd like to use it for Whonix 14 build (#4016).

**Comment by adrelanos** [comment]
It will be amazing to be able to create templates myself!

If you don't mind, I'd use it as a "SaaS" to more frequently build and test. (Images created locally by me may not 100% match the official build due to some mistake by me (config error, outdated qubes-builder git, unforeseeable). So I end up testing multiple times.)

> Do we need templates-itl-testing and templates-community-testing repositories and upload templates there first?

Very much need to test images before migrating to stable repository.

> `build-template QUBES_VERSION TEMPLATE TIMESTAMP`

Maybe...

    build-template QUBES_VERSION TEMPLATE TIMESTAMP SIGNED_GIT_TAG_TO_BUILD

> Template package version is pretty meaningless right now (it's template builder version (but not builder plugin - containing most actual building scripts) + timestamp). Maybe we could use this occasion to change this too? For example specify template version manually too? Or build it based on qubes version (3.2.x for templates for Qubes 3.2 etc)?

Maybe use `SIGNED_GIT_TAG_TO_BUILD` as template version?

That may also help to get rid of writing down `TIMESTAMP` manually since that could be extracted from `SIGNED_GIT_TAG_TO_BUILD`?

**Comment by marmarek** [comment]
> Maybe use SIGNED_GIT_TAG_TO_BUILD as template version?

Tag on what exactly? Which repository? Since template is built using apt/yum/other repositories, it makes perfect sense to trigger new template build without any change in linux-template-builder, builder-debian/builder-rpm, template-whonix repositories. Or even without any change in any of Whonix or Qubes repositories - for example to pick up some updated Debian package.

**Comment by adrelanos** [comment]
Marek Marczykowski-Górecki:
>> Maybe use SIGNED_GIT_TAG_TO_BUILD as template version?
> 
> Tag on what exactly? Which repository?

For example qubes-template-whonix.

> Since template is built using apt/yum/other repositories, it makes perfect sense to trigger new template build without any change in linux-template-builder, builder-debian/builder-rpm, template-whonix repositories. Or even without any change in any of Whonix or Qubes repositories - for example to pick up some updated Debian package.
> 

I see.

**Comment by marmarek** [comment]
@adrelanos what key do you want to use for signing build requests? 916B8D99C38EAF5E8ADC7A2A8D66066A2EEACCDA?

**Comment by marmarek** [comment]
@fepitre what key do you want to use for signing build requests? C7A3BA7D2DDAF042C77CA4D21DABC232BE02201E?

**Comment by marmarek** [comment]
@ptitdoc what key do you want to use for signing build requests? D85EE12F967851CCF433515A2043E7ACC1833B9C?

**Comment by marmarek** [comment]
@unman what key do you want to use for signing build requests? C6E2533D976E4B29A82B79CB0C6D15D5E0A9816E?

**Comment by adrelanos** [comment]
Marek Marczykowski-Górecki:
> @adrelanos what key do you want to use for signing build requests? 916B8D99C38EAF5E8ADC7A2A8D66066A2EEACCDA?
> 

Yes.

916B8D99C38EAF5E8ADC7A2A8D66066A2EEACCDA

**Comment by marmarek** [comment]
A quick how-to:
Post a comment in format described [here](https://github.com/qubesos/qubes-builder-github#build-template-command), anywhere in updates-status repo issues (I suggest this place: https://github.com/QubesOS/updates-status/issues/566). When command is properly recognized, new issue will be created about the template that starts to build ([example](https://github.com/QubesOS/updates-status/issues/568)). It may take 1-2 min. If it still isn't there, there is something wrong, re-check command syntax (typos? trailing spaces?).
When build succeed, there will be new comment with a link to build log in issue created at the build start. If it fails, there will be a new issue in https://github.com/QubesOS/build-issues/issues (for now there is no info about it in original issue, maybe I'll add some linking later).

You can check configured templates in https://github.com/QubesOS/qubes-builder/tree/master/release-configs (see `*templates*.conf`, especially `DISTS_VM` option - those are available values for "dist" parameter). Each template is built from separate config file pointed from there, actual template configs are in https://github.com/QubesOS/qubes-template-configs.
I've configured Whonix 14 build to use https://github.com/Whonix/qubes-template-whonix, master branch.

**Comment by marmarek** [comment]
Remaining tasks:
 - [ ] add templates-*-testing repositories definitions
 - [ ] link build failure notification to issue created at the build start

**Comment by marmarek** [comment]
Regardless of the remaining tasks above, building itself should work already.

**Comment by marmarek** [comment]
@adrelanos would you like to build whonix 14 using this new mechanism?

**Comment by adrelanos** [comment]
Marek Marczykowski-Górecki:
> @adrelanos would you like to build whonix 14 using this new mechanism?
> 

Yes.

**Comment by marmarek** [comment]
So, please do when ready :) See https://github.com/QubesOS/qubes-issues/issues/3935#issuecomment-402007886

**Comment by adrelanos** [comment]
The command to create the timestamp is...?

    date --utc +%Y%m%d%H%M

----

Only one command per message? I guess I'll write a small script to generate multiple signed build commands for gateway, workstation, R3.2, R4.0 (4 commands).

----

Is this safe against attacks, i.e. someone copying and pasting any comments? I.e. a replay attack. The signature is valid regardless how often it is posted.

**Comment by marmarek** [comment]
> The command to create the timestamp is...?
> 
> date --utc +%Y%m%d%H%M

Yes.

> Only one command per message?

For now yes.

> Is this safe against attacks, i.e. someone copying and pasting any comments? I.e. a replay attack. The signature is valid regardless how often it is posted.

This is why timestamp is included in the command. It's valid for one hour. There is also protection refusing to build template which already exists (exact version, including requested timestamp), so it's only possible to replay command (for one hour) for a failed build. Which I consider a feature (retry a build after intermittent network problem caused by Tor).

**Comment by marmarek** [comment]
BTW I see gpg2 supports expiration time for signatures (`--default-sig-expire`). But I haven't tried it and not sure if that's a good idea.

**Comment by adrelanos** [comment]
https://github.com/QubesOS/updates-status/issues/566#issuecomment-404574866 - Did I do something wrong?

**Comment by marmarek** [comment]
Looks fine, let me check the logs...

**Comment by marmarek** [comment]
Ok, I found the problem - I'm using subkey ID not primary key ID for access control, but actually listed primary key ID in configuration. Will fix in a moment

**Comment by marmarek** [comment]
Ok, retry now.

**Comment by adrelanos** [comment]
Issue for the build was created this time.

----

https://github.com/marmarek/qubes-builder-github/blob/master/lib/functions.sh

```
        eval "$local_signer"="$(grep -Po \
            '^\[GNUPG:\] VALIDSIG (([0-9A-F-]+ ){9}|)\K([0-9A-F]*)' \
            "$tmpdir/gpg-status")"
```

Not exactly same as https://github.com/QubesOS/qubes-issues/issues/4070 but couldn't we better avoid any `eval` here?

Could that be a bash script? Would a bash array help avoid the eval?

**Comment by marmarek** [comment]
eval here is is to assign to a variable named by `$local_signer`, how to do that? Alternatively it could write keyid to a file named by that variable... The point here is we need to return two things from that function - verified command and a key ID used to sign it.

**Comment by adrelanos** [comment]
File seems better. Otherwise the eval risks to evaluate anything form gpg status file output.

----

> https://github.com/QubesOS/updates-status/issues/576

Minor issue - duplicate comment:

> `Package for fc23 was built (build log) and uploaded to templates-community-testing repository`

**Comment by marmarek** [comment]
> File seems better. Otherwise the eval risks to evaluate anything form gpg status file output.

The function strictly grep for `[0-9A-F]*`, but will convert to a file anyway.

> Minor issue - duplicate comment:

That was me.

**Comment by adrelanos** [comment]
For example for https://github.com/QubesOS/updates-status/issues/581 what is the installation command?

`sudo qubes-dom0-update --enablerepo=templates-community-testing qubes-template-whonix-gw-14` says repository not found.

**Comment by marmarek** [comment]
The command is correct, but template definition isn't there yet.  See this:

> The template will be uploaded to appropriate templates testing repository. For now you need to create repository definition manually (copy existing one and append "-testing" to the name and URL).

**Comment by marmarek** [comment]
Oh and salt have hardcoded templates-community repo name: https://github.com/QubesOS/qubes-mgmt-salt-dom0-virtual-machines/blob/master/qvm/template-whonix-gw.sls#L19
So, testing this with salt require changing that line (it's `/srv/formulas/base/virtual-machines-formula/qvm/template-whonix-*.sls`).

**Comment by marmarek** [comment]
Ok, qubes-release-4.0-4 (building right now) contains templates testing repositories. Note I've also added metalinks there (for automatic mirror selection) - please let me know if you notice any problems with that.

**Comment by marmarek** [comment]
For 3.2, it's already in [qubes-release-3.2-2](https://github.com/QubesOS/updates-status/issues/582)

**Comment by marmarek** [comment]
> Is it possible to build from Qubes testing rather than Qubes stable repository?

Yes, add `USE_QUBES_REPO_TESTING=1` to https://github.com/QubesOS/qubes-template-configs/blob/master/R4.0/templates-community/whonix-14.conf

**Comment by adrelanos** [comment]
Ok, I assume packages are usually not uploaded to unstable. Good to know.

May I recommend to remove the unstable version since it's lower than testing version? Perhaps automated "if version in unstable lower than in testing or stable, remove from unstable"?

**Comment by marmarek** [comment]
> Ok, I assume packages are usually not uploaded to unstable. Good to know.

Yes, unstable repo is only for early testing versions, not suitable for broader testing. I'd say "developers only" in your repository layout.

> May I recommend to remove the unstable version since it's lower than testing version? Perhaps automated "if version in unstable lower than in testing or stable, remove from unstable"?

Any specific reason for that? Package manager picks newest available version. Also, unstable repository is disabled by default and no one really should have it enabled permanently (unless want a really unstable system) - this repository may include potentially known-broken packages.
Generally we do not remove packages from repositories.

**Comment by adrelanos** [comment]
Marek Marczykowski-Górecki:
> 
>> Ok, I assume packages are usually not uploaded to unstable. Good to know.
> 
> Yes, unstable repo is only for early testing versions, not suitable for broader testing. I'd say "developers only" in your repository layout.

I see.

>> May I recommend to remove the unstable version since it's lower than testing version? Perhaps automated "if version in unstable lower than in testing or stable, remove from unstable"?
> 
> Any specific reason for that?

Not not sure if a strong enough reason. When even developers / advanced
users get confused, maybe it's too difficult. :)

https://www.whonix.org/wiki/Qubes/Install/Testing still had:

sudo qubes-dom0-update --enablerepo=qubes-dom0-unstable
qubes-core-admin-addon-whonix

Since I expected all packages go through unstable -> testing -> stable.

Another reason: in case instructions once contain
"--enablerepo=qubes-dom0-unstable" and later packages are uploaded
straight to testing while skipping unstable, following documentation can
certainly lead to strange results, this can create confusion which is
difficult to sort out.

It's how Debian works. sid (unstable) -> testing -> stable.

Qubes unstable (maybe) | testing -> stable I find unexpected, confusing.

**Comment by adrelanos** [comment]
Me and testers also confused installing and old version of testers-only
Qubes-Whonix from unstable rather than a newer one from Qubes testing
earlier. That resulted in a lot not quickly accountable confusion and
lost time.

**Comment by adrelanos** [comment]
Due to frequent flaky network related build issues, could you add please an auto-retry loop of 3 to 5 attempts or so?

**Comment by adrelanos** [comment]
qubes-template-whonix-gw-14 `4.0.1-201807210556` even though https://github.com/QubesOS/updates-status/issues/609 says it has been uploaded, is not actually available in `templates-community-testing`.

qubes-template-whonix-gw-14 `4.0.1-201807190624` is being downloaded.

Upload failure not detected?

Out of disk space?

https://yum.qubes-os.org/r4.0/templates-community-testing/rpm/ has:

* qubes-template-whonix-gw-14-4.0.1-2018 07130946.noarch.rpm
* qubes-template-whonix-gw-14-4.0.1-2018 07171801.noarch.rpm
* qubes-template-whonix-ws-14-4.0.1-2018 07131452.noarch.rpm
* qubes-template-whonix-ws-14-4.0.1-2018 07171801.noarch.rpm

By the way, all older templates can all be purged to save disk space.

**Comment by marmarek** [comment]
> qubes-template-whonix-gw-14 4.0.1-201807210556 even though QubesOS/updates-status#609 says it has been uploaded, is not actually available in templates-community-testing.

It is, for 3.2 (not 4.0), here: https://yum.qubes-os.org/r3.2/templates-community-testing/rpm/

**Comment by adrelanos** [comment]
https://github.com/QubesOS/updates-status/issues/572#issuecomment-407166272 

> Upload core-agent-linux ec251da5d8e6ed5544e91d92695a41f4d86d43d5 r4.0 current repo

There's was no notification `Package for fc28 was built (build log) and uploaded to current repository`. Expected?

I guess such a notification if upload actually happened could save a some time in future in case it fails for some reason.

**Comment by ptitdoc** [comment]
Hello,

Sorry, I did not tested yet but the key D85EE12F967851CCF433515A2043E7ACC1833B9C is good for me for building templates.

**Comment by ptitdoc** [comment]
Hello,

I'm only starting to test this. I'm not sure where I should create specific archlinux configuration. Should I put it there:
https://github.com/QubesOS/qubes-builder/tree/master/release-configs
or there:
https://github.com/QubesOS/qubes-template-configs/tree/master/R4.0/templates-community

**Comment by marmarek** [comment]
The latter.

**Comment by unman** [comment]
@marmarek The second is my signing key for Qubes:
4B1F400DF25651B53C4141B38B3F30F9C8C0C2EF

Confirmed [here](https://github.com/unman/unman/blob/master/gpg-keys.asc)

**Comment by marmarek** [comment]
Ok, I read this as "use 4B1F400DF25651B53C4141B38B3F30F9C8C0C2EF for build commands access list"

**Comment by unman** [comment]
Yes, sorry. You've understood my somewhat gnomic comment aright.
Please use key  4B1F400DF25651B53C4141B38B3F30F9C8C0C2EF for access list.

**Comment by adrelanos** [comment]
Using...

    REPO_PROXY="" make DISTS_VM="whonix-gateway-16 whonix-workstation-16" template-github

Builds templates for Qubes R4.0.

What's the command for Qubes R4.1?

**Comment by adrelanos** [comment]
Got it.

**Comment by adrelanos** [comment]
Comment out from `builder.conf `: `RELEASE = 4.0` and

    RELEASE=4.1 REPO_PROXY="" make DISTS_VM="whonix-gateway-16 whonix-workstation-16" template-github

**Comment by marmarek** [comment]
This is all done for quite some time already.
