### ISSUE TITLE
Qubes VM widget displays incorrect states, prevents user from shuting down VMs

### ISSUE THREAD

**Issue by rootkovska** [QubesOS/qubes-issues#3937]
For about half of active qubes I see the "starting up" notifications (spinning circles) that won't go away forever. The context menu then allows only killing the VM, rather than cleanly shutting down.

**Comment by marmarek** [comment]
Duplicate of #3660

**Comment by rootkovska** [comment]
With latest updates installed in dom0 (from current), this problem still persists.

**Comment by marmarek** [comment]
This is still a duplicate of #3660 - see status there (the fix is in current-testing).
