### ISSUE TITLE
The installer skips the "media testing" step

### ISSUE THREAD

**Issue by ghost** [QubesOS/qubes-issues#3938]
Media testing is not being executed while trying to install QubesOS.

### Qubes OS version: 
R 4.0
### Steps to reproduce the behavior:
- download the image from a torrent or a mirror
- copy files to a USB drive with this command: `sudo dd if=Qubes-R4.0.iso of=/dev/sdX bs=1M && sync`
- boot from USB drive
- Select "Test this media and install" from the installation options

### Expected behavior:
Have the media checked with a feedback in percentages.

### Actual behavior:
The media isn't tested, no percentages appear in CLI, it moves straight to the next step, which is "showing the Qubes logo on a gray background with a loading bar underneath it".

**Comment by sstt011** [comment]
When I installed Qubes 4.0, when I selected this option, there was not obvious notification of this in the GUI, however in the CLI (press ESC), it was obvious it was being checked.

**Comment by Zig-03** [comment]
@sstt011 thanks, it worked. So it means it's just a UI bug, ok.
