### ISSUE TITLE
[Debian templates] - [qubes-gui-agent] - Qubes GUI broken because of Xorg ABI Interface update in package xserver-xorg-core 2:1.20.0-2 (debian testing)

### ISSUE THREAD

**Issue by mdik** [QubesOS/qubes-issues#3943]
### Steps to reproduce the behavior:
```
sudo apt update
sudo apt full-upgrade
```

### Expected behavior:
System is up-to-date and operational

### Actual behavior:
qubes-gui-agent gets removed during upgrade due to unresolved dependencies, i.e. `xorg-video-abi-23` vs `xorg-video-abi-24`.

### General notes:

The packages `qubes-gui-agent` and `xserver-xorg-video-dummyqbs` as they are provided by the Qubes Debian Repository for Debian testing, depend on the virtual package `xorg-video-abi-23` while the new version of the `xserver-xorg-core` package provides `org-video-abi-24`.

---

### Related issues:

This is basically the same issue as
https://github.com/QubesOS/qubes-issues/issues/2514
but for newer versions of Debian and Qubes OS ¯\\\_(ツ)\_/¯

**Comment by unman** [comment]
@andrewdavidwong This can be closed as the dependency is fixed and current upgrade to testing proceeds without issue.
