### ISSUE TITLE
Lost internet on all VMs after updating from testing repos

### ISSUE THREAD

**Issue by Simon-Davies** [QubesOS/qubes-issues#3949]
### Qubes OS version:

Qubes 4.0 - Latest version of qubes from testing repos

### Affected component(s): 

All VMs

---

### Steps to reproduce the behavior:

Connect to Wi-Fi and browse internet with Firefox

### Expected behavior:

I have internet connectivity

### Actual behavior:

I have no Internet connectivity. I can't even ping google - www.google.com or 8.8.8.8

### General notes:

---

**Comment by tasket** [comment]
See issue #3939 which might be the same.

Are you using Fedora 27 or 28? Check the status of qubes-iptables.service on your proxyVMs (sys-firewall) and sys-net: `sudo service qubes-iptables status`

**Comment by andrewdavidwong** [comment]
Can you provide the list of packages that were updated with version numbers?

**Comment by marmarek** [comment]
It's definitely https://github.com/QubesOS/updates-status/issues/550. It fixes Fedora 28, but at the same time breaks Fedora 26.

**Comment by Simon-Davies** [comment]
I'm using Fedora 26 templates so this sounds right @marmarek 

The question is how do I fix this without flashing a clean ISO of Qubes OS.

**Comment by marmarek** [comment]
dnf in the template should still work, you can downgrade `qubes-core-agent*` to previous version (`dnf downgrade ...`).

**Comment by Simon-Davies** [comment]
I ran the below in the fedora-26 template:

sudo did downgrade qubes-core-agent*

I get:

Error: Failed to synchronize cache for repo 'updates'

**Comment by RefinedSoftwareLLC** [comment]
I was able to fix an "Error: Failed to synchronize cache for repo 'updates'" error by using "sudo qubes-dom0-update --clean". Can anyone else tell us if that is safe to try as a fix?

**Comment by jimtahu** [comment]
I ran into this issue as well (qubes-iptables was failing with error messages about the firewall rules), was able to "fix" by reverting my template (fedora-27) root volume

**Comment by Simon-Davies** [comment]
When ypu say by reverting what do you mean by this? I tried downgrading all the qubes-core-agent* packages in the fedora-26 VM to the last version but it's still broken for me. 

I'm thinking of wiping the system and starting fresh as it's really annoying having no internet.

**Comment by jimtahu** [comment]
[qvm-volume](https://dev.qubes-os.org/projects/core-admin-client/en/stable/manpages/qvm-volume.html ) has an option to revert a volume.

For me, this meant doing this in dom0:
`qvm-volume list fc27` (see volumes, including fc27:root)
`qvm-volume info fc27` (see that fc27:root has a previous versions, named something like number-bak)
`qvm-volume revert –verbose fc27:root number-bak`

After restarting sys-net and sys-firewall (based on fc27), networking resumed working.

**Comment by DemiMarie** [comment]
Is this still an issue?
