### ISSUE TITLE
qubes-core-agent /etc/qubes/post-install.d mechanism / qvm-features-request broken

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#3951]
### Qubes OS version:
R4

### Affected component(s): 
all templates

### Steps to reproduce the behavior:
Upgrade qubes core agent.

When qubesdb is being upgraded (i.e. not running) and at the same time https://github.com/QubesOS/qubes-core-agent-linux/blob/master/qubes-rpc/qubes.PostInstall is processing a ` /etc/qubes/post-install.d/` trigger, 

### Expected behavior:
Functional.

### Actual behavior:

For example `qvm-features-request whonix-ws=1` won't work, because qubesdb not running.

Other things from https://github.com/QubesOS/qubes-core-agent-linux/tree/master/post-install.d will also not work.

```
Leaving 'diversion of /etc/init/tty.conf to /etc/init/tty.conf.qubes-disabled by qubes-core-agent'
Leaving 'diversion of /etc/init/serial.conf to /etc/init/serial.conf.qubes-orig by qubes-core-agent'
No such key 'auto-update-type' in schema 'org.gnome.settings-daemon.plugins.updates' as specified in override file '/usr/share/glib-2.0/schemas/20_org.gnome.settings-daemon.plugins.updates.qubes.gschema.override'; ignoring override for this key.
Failed connect to local daemon
Traceback (most recent call last):
  File "/usr/bin/qvm-features-request", line 81, in <module>
    sys.exit(main())
  File "/usr/bin/qvm-features-request", line 70, in main
    qdb = qubesdb.QubesDB()
qubesdb.Error: (2, 'No such file or directory')
Traceback (most recent call last):
  File "/usr/bin/qvm-features-request", line 81, in <module>
    sys.exit(main())
  File "/usr/bin/qvm-features-request", line 70, in main
    qdb = qubesdb.QubesDB()
qubesdb.Error: (2, 'No such file or directory')
Traceback (most recent call last):
  File "/usr/bin/qvm-features-request", line 81, in <module>
    sys.exit(main())
  File "/usr/bin/qvm-features-request", line 70, in main
    qdb = qubesdb.QubesDB()
qubesdb.Error: (2, 'No such file or directory')
Traceback (most recent call last):
  File "/usr/bin/qvm-features-request", line 81, in <module>
    sys.exit(main())
  File "/usr/bin/qvm-features-request", line 70, in main
    qdb = qubesdb.QubesDB()
qubesdb.Error: (2, 'No such file or directory')
Setting up qubes-core-agent-networking (4.0.28-1+deb8u1) ...
```

### General notes:

I think the current /etc/qubes/post-install.d implementation is fragile.

### Related issues:

Affects Whonix `anon-vm` tag implementation.

https://www.whonix.org/wiki/Dev/Qubes#anon-vm_tag

https://github.com/QubesOS/qubes-issues/issues/3765
https://github.com/QubesOS/qubes-issues/issues/3595

**Comment by marmarek** [comment]
@adrelanos could qubes-core-agent-linux have some dependency that its postinst script is called after qubes-db service is started again?

**Comment by adrelanos** [comment]
```
Leaving 'diversion of /etc/init/tty.conf to /etc/init/tty.conf.qubes-disabled by qubes-core-agent'
Leaving 'diversion of /etc/init/serial.conf to /etc/init/serial.conf.qubes-orig by qubes-core-agent'
No such key 'auto-update-type' in schema 'org.gnome.settings-daemon.plugins.updates' as specified in override file '/usr/share/glib-2.0/schemas/20_org.gnome.settings-daemon.plugins.updates.qubes.gschema.override'; ignoring override for this key.
Failed connect to local daemon
Traceback (most recent call last):
  File "/usr/bin/qvm-features-request", line 81, in <module>
    sys.exit(main())
  File "/usr/bin/qvm-features-request", line 70, in main
    qdb = qubesdb.QubesDB()
qubesdb.Error: (2, 'No such file or directory')
Traceback (most recent call last):
  File "/usr/bin/qvm-features-request", line 81, in <module>
    sys.exit(main())
  File "/usr/bin/qvm-features-request", line 70, in main
    qdb = qubesdb.QubesDB()
qubesdb.Error: (2, 'No such file or directory')
Traceback (most recent call last):
  File "/usr/bin/qvm-features-request", line 81, in <module>
    sys.exit(main())
  File "/usr/bin/qvm-features-request", line 70, in main
    qdb = qubesdb.QubesDB()
qubesdb.Error: (2, 'No such file or directory')
Traceback (most recent call last):
  File "/usr/bin/qvm-features-request", line 81, in <module>
    sys.exit(main())
  File "/usr/bin/qvm-features-request", line 70, in main
    qdb = qubesdb.QubesDB()
qubesdb.Error: (2, 'No such file or directory')
Setting up qubes-core-agent-networking (4.0.28-1+deb8u1) ...
```

**Comment by adrelanos** [comment]
This is a blocker for the release of Whonix 14.

**Comment by marmarek** [comment]
@adrelanos can you provide exact steps (versions etc) to reproduce? I've tried updating both qubesdb and qubes-core-agent at the same time in debian-9 template it it worked just fine. Was that during whonix-13 -> whonix-14 update?
Note that if you see those messages during template build, it doesn't matter, since qubes.PostInstall is also called at template installation time.

**Comment by marmarek** [comment]
[Debian policy](https://www.debian.org/doc/debian-policy/#s-binarydeps):
> Depends
>
>    This declares an absolute dependency. A package will not be configured unless all of the packages listed in its Depends field have been correctly configured (unless there is a circular dependency as described above).

So, `Depends: qubesdb-vm` should fix it. But since I can't reproduce the problem, cannot reliably test it. Will push the update to testing anyway.

**Comment by adrelanos** [comment]
Marek Marczykowski-Górecki:
> @adrelanos can you provide exact steps (versions etc) to reproduce?

If you have a Qubes-Whonix 14 template and upgrade it, this should be
reproducible.

> I've tried updating both qubesdb and qubes-core-agent at the same time in debian-9 template it it worked just fine. Was that during whonix-13 -> whonix-14 update?

Didn't test whonix-13 -> whonix-14 upgrade to reproduce this. No major
upgrade required. This was happening during Whonix 14 package upgrades.

> So, `Depends: qubesdb-vm` should fix it. But since I can't reproduce
the problem, cannot reliably test it. Will push the update to testing
anyway.

Very good! :) Once in testing, I will test. Will let you know in case I
spot this issue again.
