### ISSUE TITLE
Add Whonix versions to Supported Versions page

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#3952]
Before, Whonix TemplateVMs did not have user-facing version numbers. Recently, this was changed so that they now have version numbers. We should document these so that users can find out which Whonix TemplateVM versions are supported on each Qubes release:

https://www.qubes-os.org/doc/supported-versions/#templatevms

@adrelanos, if you let me know which versions are supported on each release, I will add them, or you can submit a PR to qubes-doc, if you prefer.

-----

This issue was prompted by:
https://groups.google.com/d/topic/qubes-users/mFOBta0OqKs/discussion

**Comment by adrelanos** [comment]
R3.1 and earlier:
unsupported

R3.2 / R4:
Whonix 13
