### ISSUE TITLE
Qubesd fails to start, freshinstall R4.0, string to float, localization

### ISSUE THREAD

**Issue by Bockwurst-Mit-Puls** [QubesOS/qubes-issues#3960]
### Affected component(s): 

---

### General notes:

---

**Comment by marmarek** [comment]
Looks like a duplicate of (already fixed in updates) https://github.com/QubesOS/qubes-issues/issues/3960
Let me guess, en_DK locale? You can install with different locale, update, then change back to en_DK.

**Comment by Bockwurst-Mit-Puls** [comment]
Yeah, I just made some typing here because of the fickle mobile site. At first the issue was empty.

**Comment by andrewdavidwong** [comment]
@marmarek 
> Looks like a duplicate of (already fixed in updates) #3960

Typo? #3960 is this issue.

**Comment by marmarek** [comment]
The correct issue is https://github.com/QubesOS/qubes-issues/issues/3753

**Comment by andrewdavidwong** [comment]
Duplicate of #3753
