### ISSUE TITLE
qvm-features does not have --get

### ISSUE THREAD

**Issue by RefinedSoftwareLLC** [QubesOS/qubes-issues#3965]
### Qubes OS version:

Qubes release 4.0 (R4.0)
I also used:
$ sudo qubes-dom0-update --enablerepo=qubes-dom0-security-testing

### Affected component(s): 

qvm-features in the terminal

---

### Steps to reproduce the behavior:

qvm-features vm-name video-model --get

### Expected behavior:

qvm-features to have the same --get that qvm-prefs has. All `qvm-` should have as many shared `--argument` features as possible.

### Actual behavior:

`qvm-features: error: unreconized arguments: --get`

**Comment by marmarek** [comment]
The qvm-prefs --get exists only for compatibility with Qubes 3.2 - see man qvm-prefs. The syntax to get the current value is `qvm-prefs vm-name property-name`, same as for qvm-features: `qvm-features vm-name feature-name` (like `qvm-features vm-name video-model`).
