### ISSUE TITLE
qvm-start should give a descriptive error message if private missing but tmp still present

### ISSUE THREAD

**Issue by jaseg** [QubesOS/qubes-issues#3968]
### Qubes OS version:
R4.0
### Affected component(s):
`qvm-start`
### Steps to reproduce the behavior:

I can not reproduce the original issue (private-tmp volume not being cleaned up for some reason) but I suppose if you manually rename the private volume you can provoke the unhelpful error message.

### Expected behavior:
When private volume is not found, but -tmp clone of private volume is still present, qvm-start should display an error message along the lines of ```Something bugged out, the vm's private volume is missing but its private-tmp is still there. Consult https://github.com/QubesOS/qubes-issues/issues/3314#issuecomment-345105356 to resolve.```

Ideally, `qvm-run` when called from one of the application menu shortcuts would display an error dialog, too. On my machine, it just failed silently.

### Actual behavior:
qvm-start just says something along the lines of "private volume not found". Figuring out what this means and how to fix took a bit of googling.

### General notes:

Though the original issue is that private volumes are not cleaned up, I think a more accurate error message would reduce the frequency of heart attacks among qubes users :wink:

---

### Related issues:

#3314

**Comment by marmarek** [comment]
There is even better thing work in progress - automatically handle this situation (cleanup it).
https://github.com/QubesOS/qubes-core-admin/pull/203#issuecomment-383236856

**Comment by andrewdavidwong** [comment]
Closing as "won't do" since the better solution @marmarek mentioned is already in progress. If anyone has a new argument for why this should be done even though the better solution is already in progress, please leave a comment, and we'll be happy to take another look. Thank you.
