### ISSUE TITLE
"How To make a VPN Gateway in Qubes" tutorial for R 4.0 is missing

### ISSUE THREAD

**Issue by ghost** [QubesOS/qubes-issues#3970]
here it is for R 3.2 only https://www.qubes-os.org/doc/vpn/

**Comment by tasket** [comment]
@andrewdavidwong The current VPN doc works with R4.0 so you may wish to close this.

**Comment by andrewdavidwong** [comment]
Many docs, including this VPN doc, have recently transitioned to external documentation, so that's another reason to close this issue. Opening further issues to improve these docs is welcome in [Qubes Community](https://github.com/Qubes-Community).
