### ISSUE TITLE
Issues when Restoring backup

### ISSUE THREAD

**Issue by yonjah** [QubesOS/qubes-issues#3975]
### Qubes OS version:
R4.0
### Affected component(s): 

Backup And Restore

---
### Steps to reproduce the behavior:
I just replaced my hardrive so I made a backup for all VMs and templates In my current R4.0 install
and then a fresh install And restore for the backups.

### Expected behavior:

Get all the a system that is identical to the backup (all vms and settings)

### Actual behavior:

After restore a few issues  (from major to minor) -
1. Nothing was really restored in Dom0 -
    A folder named home-restore-2018../dom0-home/user was created in my home folder but did not replace it (I'll try to do it manually later)
   I had a lot of customization in /etc (like /etc/qubes/guid.conf) none of them was restored    

2. VMs that were restore did not have the app selected shown  on the Application menu but instead show all apps

3. if a VM or template already existed (like fedora-26, sys-net and sys-usb) it was restored without replacing the existing vm (appending 1 to it's name) and replacing it with the new vm was hard to almost impossible (existing fedora-26 template cannot be removed easily)

4. Some of the restored vms had their template set to the new install template (fedora-24) and others had the restored template (fedora-241)

5. IPs of restored vm are completely different (this is a bit annoying cause I had a vm running nfs and other vms had specific permissions to get certain folders so I had to change all the ips manually)

### General notes:

I know getting an exact restore might be hard but it would be great if some of this issues can be solved
so after restore it there will only be minor changes

**Comment by andrewdavidwong** [comment]
> A folder named home-restore-2018../dom0-home/user was created in my home folder but did not replace it (I'll try to do it manually later)
> I had a lot of customization in /etc (like /etc/qubes/guid.conf) none of them was restored

This is working as intended. See #2271. However, it sounds like we need to add a message explaining what's happening.

> if a VM or template already existed (like fedora-26, sys-net and sys-usb) it was restored without replacing the existing vm (appending 1 to it's name)

I think this is intended, since we don't want restoring to unintentionally clobber existing VMs with the same name. Perhaps it might be useful to add an option to enable clobbering.

> IPs of restored vm are completely different (this is a bit annoying cause I had a vm running nfs and other vms had specific permissions to get certain folders so I had to change all the ips manually)

I think IPs are assigned based on the `qid`s in that system, which are probably determined for restored VMs by the order in which they were restored.

CC: @marmarek
