### ISSUE TITLE
Fail to build Qubes OS R4.0 iso from scratch - gcc failed to build - directory not found

### ISSUE THREAD

**Issue by yurikanestorm** [QubesOS/qubes-issues#3979]
### Qubes OS version:

R4.0 

### Affected component(s): 

qubes-builder
commit: mm_4e03c122

---

### Steps to reproduce the behavior:

git clone git://github.com/QubesOS/qubes-builder.git qubes-builder 
cd qubes-builder 
make get-sources
make qubes 

### Expected behavior:

All Qubes rpms are built

### Actual behavior:

The build fails with the following error:

-> Installing core RPM packages...
Failed to connect to bus: No such file or directory
Running in chroot, ignoring request.
-> Installing package groups...
Group 'Buildsystem building group' is already installed, skipping.
Group 'Development Tools' is already installed, skipping.
Package MAKEDEV-3.24-17.fc24.x86_64 is already installed, skipping.
[sudo] password for y:
mkdir -p /home/y/used/test/1/qubes-builder/chroot-fc25/home/user/qubes-src/gcc
/home/y/used/test/1/qubes-builder/scripts/create-archive /home/y/used/test/1/qubes-builder/chroot-fc25/home/user/qubes-src/gcc gcc-6.4.1-20170727.tar.bz2 gcc-6.4.1-20170727.tar.bz2/
~/used/test/1/qubes-builder/chroot-fc25/home/user/qubes-src/gcc ~/used/test/1/qubes-builder
~/used/test/1/qubes-builder
-> Building gcc (gcc.spec) for fc25 dom0 (logfile: build-logs/gcc-dom0-fc25.log)
[sudo] password for y:
--> build failed!
  transfig.x86_64 1:3.2.6-2.fc25                                               
  urw-fonts.noarch 3:2.4-22.fc24                                               
  xml-common.noarch 0.6.3-44.fc24                                              
  xorg-x11-font-utils.x86_64 1:7.5-32.fc25                                     
  xorg-x11-fonts-ISO8859-1-100dpi.noarch 7.5-16.fc24                           
  xz-devel.x86_64 5.2.2-2.fc24                                                 
  zlib-devel.x86_64 1.2.8-10.fc24                                              
  zziplib.x86_64 0.13.62-7.fc24                                                

Complete!
rm -rf /home/y/used/test/1/qubes-builder/chroot-fc25//home/user/qubes-src/gcc/pkgs/fc25/*
sudo chroot /home/y/used/test/1/qubes-builder/chroot-fc25 su -c 'cd /home/user/qubes-src/gcc; env BACKEND_VMM=xen  rpmbuild --define "dist .fc25" --define "fedora 25" --define "_rpmdir pkgs/fc25/" --define "qubes_builder 1" --define "backend_vmm xen" --define "dist .fc25" --define "fedora 25" --define "_rpmdir pkgs/fc25/" --define "qubes_builder 1" --define "backend_vmm xen" --define "_sourcedir /home/user/qubes-src/gcc" -bb gcc.spec' - user
Executing(%prep): /bin/sh -e /var/tmp/rpm-tmp.Oes7TO
+ umask 022
+ cd /home/user/rpmbuild/BUILD
+ cd /home/user/rpmbuild/BUILD
+ rm -rf gcc-6.4.1-20170727
+ /usr/bin/bzip2 -dc /home/user/qubes-src/gcc/gcc-6.4.1-20170727.tar.bz2
+ /usr/bin/tar -xof -
+ STATUS=0
+ '[' 0 -ne 0 ']'
+ cd gcc-6.4.1-20170727
/var/tmp/rpm-tmp.Oes7TO: line 37: cd: gcc-6.4.1-20170727: No such file or directory
error: Bad exit status from /var/tmp/rpm-tmp.Oes7TO (%prep)

RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.Oes7TO (%prep)
make[2]: *** [/home/y/used/test/1/qubes-builder/qubes-src/builder-rpm/Makefile-legacy.rpmbuilder:66: dist-package-build] Error 1
make[2]: Leaving directory '/home/y/used/test/1/qubes-builder'
make[1]: *** [Makefile.generic:166: packages] Error 1
make[1]: Leaving directory '/home/y/used/test/1/qubes-builder'
make: *** [Makefile:224: gcc-dom0] Error 1

### General notes:

I try to build Qubes OS with the latest kernel version available as defined in https://www.qubes-os.org/doc/qubes-builder/, the build environment is fedora 26, the sources are the last available on the qubes-builder respository on the master branch, they match the tag "mm_4e03c122".
After executing "make qubes", I got the error above.

I had a look on the directory ../home/user/rpmbuild/BUILD and within I found a directory named "gcc-6.4.1-20170727.tar.bz2" instead of "gcc-6.4.1-20170727", it could be an error in the extraction command for the archive within the generated rpm-tmp script. As the rpm-tmp file is each time generated with a new name and as the directory BUILD is cleaned after executing "make qubes" , I cannot try to correct this directly. 
Any idea how to correct this?

Kind Regards

---

**Comment by marmarek** [comment]
Indeed looks like a archive handling bug. I'll fix it in a moment. But believe me, you don't want to build gcc yourself, it takes 12h+... You can use pre-built package from yum.qubes-os.org by removing it from `COMPONENTS` (a list of things to build locally) setting in `builder.conf` and adding `USE_QUBES_REPO_VERSION = 4.0` instead.
