### ISSUE TITLE
Unable to use gnome-tweak-tools from debian template

### ISSUE THREAD

**Issue by Scinawa** [QubesOS/qubes-issues#3980]
### Qubes OS version:

4.0 R4.0

### Affected component(s): 

All debian 9 app VMs and the template.

---

### Steps to reproduce the behavior:

Simply run `gnome-tweak-tools` from command line, Qube Manager (run command in appvm)  and apply some edits. The software is executed , but the modifications (like the scaling factor of the fonts) are not applied upon quitting the windows, like with other fedora templates. 

### Expected behavior:

I expect to have the settings updated (like it happend with fedora template) when I close the software. Specifically I would like to update the scaling factor of the fonts of the qube. 

### Actual behavior:

``` $ gnome-tweak-tool
WARNING : Shell not installed or running
WARNING : Shell not running
None
WARNING : Error detecting shell
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gtweak/tweaks/tweak_group_shell_extensions.py", line 275, in __init__
    raise Exception("Shell not running or DBus service not available")
Exception: Shell not running or DBus service not available
```

### General notes:

I tried to run a gnome-shell, but withtout success. I'm using i3 (thianks!) but the problem persist even from XFCE. 

---

**Comment by SvenSemmler** [comment]
I have the same issue and environment. Using i3, recently changed from fedora to debian template (to be able to run signal-desktop). The Tweak Tool works as expected in Fedora based qubes as well as in Whonix14-based qubes (which are based on debian 9). 

Therefore it is possible to make this work and the Whonix guys already figured  it out. Maybe Patrick Schleizer can give us a hint?

I'll keep looking to and will report if I find the solution.
