### ISSUE TITLE
unable to boot

### ISSUE THREAD

**Issue by Klar** [QubesOS/qubes-issues#3981]
### Qubes OS version:

latest ISO:  Qubes-R4.0-x86_64.iso  - maybe updated after installation

### Affected component(s): 

Boot

---

### Steps to reproduce the behavior:

Installation of latest Qube OS ISO
Start boot from disk 
Playing around - update qubes - create delete run qubes etc.
shutdown
power on

### Expected behavior:

normal boot

### Actual behavior:

disk does not boot, for a short time black screen without information. 

### General notes:

I disabled "rhgb quiet" to see some logging messages, no luck.

Tried to fix it with: "Boot device not recognized after installing"  - same issue

BIOS Firmware upgrade done to latest version, it is an ASUS mainboard h170m-plus.

---

### Related issues:

Somethings wrong with the efi boot?

**Comment by RefinedSoftwareLLC** [comment]
These steps fixed my boot issue, feel free to try them:

Burn Qubes-R4.0-x86_64.iso to a DVD & Boot from it.
Select "Troubleshooting", then "Rescue a Qubes system".
Select `1` to continue.
`chroot /mnt/sysimage`
`vim /boot/efi/EFI/qubes/xen.cfg`
Change `default=...` to have the `...` be one of the options listed below in the same file. (All I had to change was the `41` to `35`)
Note: `Esc` Key, then `:w`, then `:q` should save changes and quit vim.
Reboot your computer.

**Comment by Klar** [comment]
Thanks for your answer! I tried but it does not work, my file looks like:

```
cat xen.cfg 
[global]
default=4.14.18-1.pvops.qubes.x86_64

[4.14.18-1.pvops.qubes.x86_64]
options=loglvl=all dom0_mem=min:1024M dom0_mem=max:4096M iommu=no-igfx ucode=scan
kernel=vmlinuz-4.14.18-1.pvops.qubes.x86_64 root=/dev/mapper/qubes_dom0-root rd.lvm.lv=qubes_dom0/root rd.lvm.lv=qubes_dom0/swap i915.alpha_support=1
ramdisk=initramfs-4.14.18-1.pvops.qubes.x86_64.img
```

Is there a way to see some more logs / debug? I do not see a grub bootloader, just a black screen for a short time.

**Comment by mex20** [comment]
@Klar I believe I know the solution to your issue. The "iommu=no-igfx" seems to be the culprit for a lot of issues like this. If you have an Intel based system with an integrated GPU or an AMD Ryzen system,  then you need to remove the "iommu=no-igfx" line. This is how I boot on my Ryzen system.

I would try "iommu=on" or "iommu=1" if simply removing the "iommu=no-igfx" doesn't work.

**Comment by Klar** [comment]
Thanks for your response, I switched computer and don't have access to test it, sorry about that :(

 I will close the task and it might help someone (please response if it helps) to fix the issue.
