### ISSUE TITLE
Fedora VMs not updating time

### ISSUE THREAD

**Issue by dmoerner** [QubesOS/qubes-issues#3983]
Fedora 28 templates and Qubes 4.0.

qvm-sync-clock is updating dom0 to the wrong time because sys-net has the wrong time because systemd-timesyncd isn't starting with error status=238/STATE_DIRECTORY. 

Fedora issue: https://bugzilla.redhat.com/show_bug.cgi?id=1559286. 
Upstream report: https://github.com/systemd/systemd/issues/7659

Manually changing /var/lib/private to 700, as mentioned in the above reports, fixed the problem for me. However, upstream commit https://github.com/systemd/systemd/commit/ebe6ff658d2f97fe5b1b8ce390ee75e8e592938f which is merged in systemd in Fedora 28, which was supposed to fix this problem, seems not to have fixed it. Perhaps it needed to be combined with changing the permission on /var/lib/private in the Fedora package.

**Comment by micah** [comment]
This happens to me on every boot. 

In order to fix it, I need to launch a terminal in sys-net and chmod 0700 /var/lib/private; systemctl start systemd-timesyncd.service and then go to dom0 and do sudo qvm-sync-clock in order for things to be right.

**Comment by aidecoe** [comment]
@micah have you tried changing this in the template VM?

**Comment by micah** [comment]
Amadeusz Żołnowski <notifications@github.com> writes:

> @micah have you tried changing this in the template VM?

yes, that is what I did and it works. 
-- 
        micah

**Comment by jpouellet** [comment]
For posterity, and to help those searching error messages:
```
● systemd-timesyncd.service - Network Time Synchronization
   Loaded: loaded (/usr/lib/systemd/system/systemd-timesyncd.service; enabled; vendor preset: enabled)
  Drop-In: /usr/lib/systemd/system/systemd-timesyncd.service.d
           └─30_qubes.conf
   Active: failed (Result: exit-code) since Thu 2018-08-30 01:37:48 EDT; 9s ago
     Docs: man:systemd-timesyncd.service(8)
  Process: 1246 ExecStart=/usr/lib/systemd/systemd-timesyncd (code=exited, status=238/STATE_DIRECTORY)
 Main PID: 1246 (code=exited, status=238/STATE_DIRECTORY)

Aug 30 01:37:48 sys-net systemd[1]: systemd-timesyncd.service: Service has no hold-off time, scheduling restart.
Aug 30 01:37:48 sys-net systemd[1]: systemd-timesyncd.service: Scheduled restart job, restart counter is at 5.
Aug 30 01:37:48 sys-net systemd[1]: Stopped Network Time Synchronization.
Aug 30 01:37:48 sys-net systemd[1]: systemd-timesyncd.service: Start request repeated too quickly.
Aug 30 01:37:48 sys-net systemd[1]: systemd-timesyncd.service: Failed with result 'exit-code'.
Aug 30 01:37:48 sys-net systemd[1]: Failed to start Network Time Synchronization.
```

**Comment by lunarthegrey** [comment]
Can confirm I experience the same behavior in sys-net with a fedora-28 template VM.

Running `chmod 0700 /var/lib/private` in the template then restarting sys-net seems to work.

**Comment by andrewdavidwong** [comment]
Reopening because this is still a problem with `sys-net` based on `fedora-29-minimal` on `R4.0.1`.

**Comment by andrewdavidwong** [comment]
The workaround mentioned above has worked for me so far.

**Comment by marmarek** [comment]
Which template version do you have? The one from stable or [from testing](https://github.com/QubesOS/updates-status/issues/848)? Can you confirm you have qubes-core-agent => 4.0.36 there?

**Comment by andrewdavidwong** [comment]
> Which template version do you have? The one from stable or from testing? Can you confirm you have qubes-core-agent => 4.0.36 there?

Stable. Yes, I hvae `4.0.40`.
