### ISSUE TITLE
Newly created windows don't always queue to the right of the last one

### ISSUE THREAD

**Issue by Zig-03** [QubesOS/qubes-issues#3988]
### Qubes OS version:
R4.0

### Affected component(s): 
XFCE panel and the way windows appear on it (the order)

### Steps to reproduce the behavior:
Have some apps opened, say Firefox and a Terminal windows. Minimize them and memorize their location on the panel. Next open a file, a folder, an app, whatever and you will see that they don't appear on the panel in a chronological order, instead some of them will appear in front of Firefox (even tho Firefox was the first one opened, so it should stay on the first position) some will add to the end, you can't really predict it.

### Expected behavior:
All newly opened windows should appear to the right of the last one opened, in a chronological way. 

### Actual behavior:
All newly opened windows (of any apps) appear sometimes at the beginning, sometimes at the end of the list of windows that we have on the default panel.

**Comment by andrewdavidwong** [comment]
This is not a Qubes issue; it's an Xfce4 setting:
```
Panel settings -> Window Buttons -> Sorting order: Timestamp
```
If you need further help, please seek out the Xfce4 documentation and consult their help resources.

**Comment by Zig-03** [comment]
Thank you @andrewdavidwong  So it's not an issue, tho beginners might consider it so. Then this issue might be considered as a suggestion, to have the Timestamp option, as the default one in Qubes, to avoid confusion and improve UX.

For anyone else looking to change this settings:
System tools > Setting Manager > Panel > Items > _select_ Windows Buttons > _click_ the wrench icon > Sorting Order > Timestamp

**Comment by andrewdavidwong** [comment]
> I'd then suggest treating this issue as a suggestion, to have the Timestamp option, as the default one in Qubes, to avoid confusion and improve UX.

No. The fact that it happens to be your personal preference is never a good reason to make it the default.

**Comment by andrewdavidwong** [comment]
Besides, we prefer to respect upstream decisions about defaults where possible (and especially when they're not security-relevant):

https://www.qubes-os.org/faq/#what-is-qubes-attitude-toward-changing-guest-distros
