### ISSUE TITLE
Hash Sum mismatch in Whonix

### ISSUE THREAD

**Issue by starius** [QubesOS/qubes-issues#3990]
### Qubes OS version:

R4.0

### Affected component(s): 

whonix-gw, whonix-ws

---

### Steps to reproduce the behavior:

Run `sudo apt-get update`

### Expected behavior:

Success

### Actual behavior:

```
$ sudo apt-get update 
...
W: Failed to fetch http://deb.qubes-os.org/r4.0/vm/dists/jessie/main/binary-amd64/Packages  Hash Sum mismatch

E: Some index files failed to download. They have been ignored, or old ones used instead.
```

### General notes:

I tried removing `/var/lib/apt/lists/*` to fix the issue as [suggested on askubuntu](https://askubuntu.com/questions/41605/trouble-downloading-packages-list-due-to-a-hash-sum-mismatch-error). It didn't help.

**Comment by marmarek** [comment]
Repository sync failed due to temporary network problem. Fixed.
