### ISSUE TITLE
Whonix notifications cover taskbar widgets and other notifications

### ISSUE THREAD

**Issue by RefinedSoftwareLLC** [QubesOS/qubes-issues#4001]
### Qubes OS version:

R4.0

### Affected component(s): 

dom0's notifications, dom0's taskbar widgets

---

### Steps to reproduce the behavior:

Reboot Qubes OS.
Notice two types of notifications.
One type is the smaller common ones.
The other type is larger, covering the taskbar widgets, covering the smaller notifications, has an [x] button.

### Expected behavior:

All notifications should use the same GUI library and never cover the taskbar widgets or each other.

**Comment by RefinedSoftwareLLC** [comment]
> [system whonix] `x`
Connected to Tor

This is the non-standard notification. It is fine that it is larger, but it needs to not overlap the taskbar nor other notifications.

**Comment by strugee** [comment]
Possible duplicate of #889?

**Comment by andrewdavidwong** [comment]
@RefinedSoftwareLLC:
> > [system whonix] `x`
> Connected to Tor
> 
> This is the non-standard notification. It is fine that it is larger, but it needs to not overlap the taskbar nor other notifications.

@strugee:
> Possible duplicate of #889?

This issue is really about Whonix notifications overlapping GUI elements. @RefinedSoftwareLLC  suggests arguably the same fix as #889, but this could be fixed in other ways.
