### ISSUE TITLE
Qube Manager: Create dvm-templates

### ISSUE THREAD

**Issue by RefinedSoftwareLLC** [QubesOS/qubes-issues#4004]
### Qubes OS version:

R4.0

### Affected component(s): 

dom0 Qube Manager, DVM-Template Qubes

---

### Steps to reproduce the behavior:

Create Qube.
Use console to change Qube into dvm-template.

### Expected behavior:

1. `qvm-features <vmname> appmenus-dispvm 1` shouldn't exist and is not needed.
- [ ] Instead if `qvm-prefs <vmname> template_for_dispvms true` then show in applications menu under both `Disposable:` and `Template:` (not `Domain:` but alternatively `DTemplate:` or `DVMTemplate:`)
- `Template:` is used for permanent updates but not app use.
- No where else does Qube Manager let you hide qubes from the applications menu. If it did, the feature shouldn't be tied to hiding an individual Disposable VM Template from permanent updates, but instead be a global setting that hides all services, templates, and dvm-templates. One way to implement this would be #4005.

2. "is a Disposable VM Template" setting:
Open "Qube Manager", right click a qube, "Qube Settings", Tab "Advanced".
- [ ] Add this setting as a checkbox: "is a Disposable VM Template" which runs:
- `qvm-prefs <vmname> template_for_dispvms true` (or false)
- If step 1 isn't implemented then `qvm-features <vmname> appmenus-dispvm 1` (or 0) 
- Maybe run `qvm-prefs <vmname> default_dispvm <vmname>` (to itself, not system default even if they are currently the same) then disable changing 'Default DispVM' from itself. This may be needed if it is too confusing for a dvm-template, when not manually instructed to, to spawn DispVM's from another dvm-template.

3. Create "AppVM (Disposable VM Template)" qube:
Open "Qube Manager", Menu "Qube", "Create new qube".
- [ ] Add this option to Type dropdown, "AppVM (Disposable VM Template)" which runs:
- `qvm-prefs <vmname> template_for_dispvms true`
- If step 1 isn't implemented then `qvm-features <vmname> appmenus-dispvm 1`
- Maybe run `qvm-prefs <vmname> default_dispvm <vmname>` (to itself, not system default even if they are currently the same) then disable changing 'Default DispVM' from itself. This may be needed if it is too confusing for a dvm-template, when not manually instructed to, to spawn DispVM's from another dvm-template.

### Actual behavior:

See "Steps to reproduce the behavior"

### General notes:

---

**Comment by andrewdavidwong** [comment]
Yes, there definitely needs to be a way to add `Disposable: <dvm_template>` menu entries like the default ones, since we expect users to create new DVM Templates (and users expect to be able to use them!). As far as I can tell, the only way to do that right now is to dig int the guts of the Xfce menu and create them manually.

**Comment by andrewdavidwong** [comment]
Oh, I just saw a hint in #4431 that `qvm-features ... appmenus-dispvm 1` might be the way to create those menu entries. I also saw that command mentioned here, but with no explanation of what it does.

Suffice it to say that if the only way I learned of it was because I happened to stumble across two bug reports, the vast majority of users will never know about it. :)

**Comment by marmarek** [comment]
Take a look here: https://www.qubes-os.org/doc/disposablevm-customization/

**Comment by andrewdavidwong** [comment]
> Take a look here: https://www.qubes-os.org/doc/disposablevm-customization/

Ok, fair enough. I should have found this.

However, the point still stands that there should be some kind of discoverable way to do this within the system, since it's expected to be a common task, and we have discoverable tools for other similar tasks.

**Comment by andrewdavidwong** [comment]
For example, even `qvm-features --help` doesn't hint that it's possible to do this. The user already has to know.
