### ISSUE TITLE
Applications menu: Hide Services/Templates qubes during routine app use

### ISSUE THREAD

**Issue by RefinedSoftwareLLC** [QubesOS/qubes-issues#4005]
Note: I do not know how much this overlaps with Qubes Admin API having managed Users.
Note: The goal is to provide an opt in experience, to hide options that are for installing/upgrading/configuring of any Qube/Application/dom0, during routine app use of Qubes OS. This increases security by hiding options you should not use during routine app use, while providing a minimalist experience to focus on productivity.

### Qubes OS version:

R4.0

### Affected component(s): 

dom0's Application Menu

---

### Steps to reproduce the behavior:

Open dom0's Application Menu and see all qubes (except dvm-templates).

### Expected behavior:

- [ ] 1. Add to Application Menu, as the first item, a "Simple Mode" checkbox (or "Minimal Mode" or "Routine Mode"). Do not name "Guest Mode" as it does not force only the use of DispVMs.
- Toggling this does not close the menu but instantly shows the new menu list.

- [ ] 2. Simple Mode: Hides "Run Program...", "Terminal Emulator", "Create Qubes VM", all "Service:" qubes, all "Template" qubes, and all "DVMTemplate" Qubes (see # 6 below).

- [ ] 3. Simple Mode: In the Application Menu, change "System Tools" to "Simple Mode System Tools", hiding all entries (even `Settings Manager` & `Qube Manager`) except: `About Xfce`, `Accessibility`, `Application Finder`, `Backup Qubes`, `Display`, `PulseAudio Volume Control`, `Screenshot`.

- [ ] 4. In the Application Menu, do not display `<vmname>: Qube Settings` inside any Qube, and if this was its only menu item, then hide the Qube completely from the Application Menu.

- [ ] 5. In Qube Manager, right click qube, Qube Settings, add checkbox "Hide during simple mode". This allows you to hide during simple mode, development/debugging/experimental Qubes you do not use routine apps on.

- [ ] 6. qvm-features <vmname> appmenus-dispvm 1 shouldn't exist and is not needed.
- Instead if `qvm-prefs <vmname> template_for_dispvms true` then show in applications menu under both `Disposable:` and `Template:` (not `Domain:` but alternatively `DTemplate:` or `DVMTemplate:`)
- `Template:`/`DVMTemplate:` is used for permanent updates but not app use.
- Simple Mode: Hide this `Template:`/`DVMTemplate:` entry from the Application Menu.

### Actual behavior:

dom0's Application Menu displays all qubes except dvm-templates.

**Comment by andrewdavidwong** [comment]
Somewhat related: #3910

**Comment by andrewdavidwong** [comment]
Related: #2646

**Comment by ninavizz** [comment]
Will be resolved with #6665, which is the development implementation to #5677

**Comment by marmarta** [comment]
As new app menu was created and is currently in testing (with that approach), this can be safely closed.
