### ISSUE TITLE
R4: Disk password input field crashing when typing special characters

### ISSUE THREAD

**Issue by Ekleog** [QubesOS/qubes-issues#4009]
### Qubes OS version:

R4

### Affected component(s): 

Splash screen for inputting the disk password

---

### Steps to reproduce the behavior:

1. Have a LUKS password including digits
2. Input them in the boot-time disk password field via the keypad while forgetting to turn NumLock on

### Expected behavior:

~Nothing happens (or ideally NumLock is turned on by default on boot), the password field sees as input the typed characters.

### Actual behavior:

The password entry prompt screen crashes during input and falls back to a tty with (IIRC) `systemd` logs displayed.

### General notes:

I unfortunately don't have access to the computer on which this happened, and don't have R4 installed locally, so won't be able to help much in debugging this… sorry!

---

**Comment by marmarek** [comment]
It isn't crashing. Pressing esc, arrows and other such keys switches between verbose and normal view. You can press esc to switch back to normal view. But if you want, you can also enter your password in verbose view.

**Comment by Ekleog** [comment]
Hmm, from memory there was no input field clearly visible, but I couldn't swear that.

That said, is there a reason why *arrows* switch to terminal view? (The numpad only has Home, PgUp, End, PgDn, Ins and arrow keys when NumLock is turned off) That's unexpected at best for the non-technical user, who will be freaked out by any terminal (which is exactly the situation I witnessed)

**Comment by Ekleog** [comment]
Hmmm that's likely indeed, so that's an upstream bug, will report to plymouth, thanks!

**Comment by Ekleog** [comment]
For the record, https://bugs.freedesktop.org/show_bug.cgi?id=106934
