### ISSUE TITLE
sudo allows root access after uninstalling auth package

### ISSUE THREAD

**Issue by tasket** [QubesOS/qubes-issues#4015]
### Qubes OS version:

R4.0

### Affected component(s): 

Debian 9 template

---

### Steps to reproduce the behavior:

```
sudo apt-get remove qubes-core-agent-passwordless-root
```
reboot...
```
sudo touch /TEST
```

### Expected behavior:

Error stating command is not authorized.

### Actual behavior:

Command runs with root privs.

### General notes:

---

**Comment by unman** [comment]
Installing the package adds user to sudo group, and removing it doesn't reverse that.

**Comment by andrewdavidwong** [comment]
Closing as "not an issue." If you believe this is a mistake, please leave a comment, and we'll be happy to take another look. Thank you.

**Comment by unman** [comment]
@andrewdavidwong Can you reopen please? It is a bug, and although I set out part of the problem it should remain open until the resolution is merged. Thanks.

**Comment by andrewdavidwong** [comment]
> Can you reopen please? It is a bug, and although I set out part of the problem it should remain open until the resolution is merged. Thanks.

Reopened. Sorry for the misunderstanding. Are you saying that removing the package should remove the user from the sudo group? What's responsible for that (and failing to do it)?

**Comment by unman** [comment]
Generally one would expect package removal to revert any changes made, (except for account creation - policy is not to remove accounts). In this case installing the package adds the user to the sudo group and removing the package does not remove the user from that group. This should be dealt with in the postrm maintainer scripts.

Of course, removing the user from the sudo group does not stop use of su, so root access will still be available.

There's another wrinkle to this in that the package is currently _required_ by qubes-vm-recommended, so attempting to remove it in standard way will suggest removing _that_ package and therefore all dependencies. This is almost certainly not what is wanted, and would be somewhat confusing.
A reasonable solution would be to make this package recommended by qubes-vm-recommended, so allowing users to remove it with minimal fuss.
@tasket @marmarek What do you think?

**Comment by unman** [comment]
> This looks to specific to Debian only, as on other templates only sudo configuration file is added (which is removed when you remove the package, so the change is reverted). Maybe the whole "add to sudo group" thing could be reverted on Debian?

There's a PR to do exactly this. QubesOS/qubes-core-agent-linux/pull/134
Another issue is that most of the work in `qubes-core-agent-passwordless-root` is done by config files, and "remove" wont clear them. You really need to do a purge. (We could remove those files as part of post-rm - I'm thinking about this)

Forgot about #2572 - I'll look at that again
