### ISSUE TITLE
build Qubes-Whonix 14.0.0.7.8 (Release Candate 3) templates for R3.2 and R4

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#4016]
This will become the stable version if no grave bugs are reported.

**Comment by andrewdavidwong** [comment]
> Would appreciate if you could have a quick look at #4016 beforehand.

This is #4016. Did you mean #4033?

**Comment by adrelanos** [comment]
Yes.

**Comment by adrelanos** [comment]
Template building was greatly enhanced in https://github.com/QubesOS/updates-status/issues/566 so no longer need to request Marek every time to do it.
