### ISSUE TITLE
Hard Drive Not Available when Creating Standalone Not From Template

### ISSUE THREAD

**Issue by qubesissues** [QubesOS/qubes-issues#4017]
### Qubes OS version:

4.0

### Affected component(s): 

Creation of Standalone Qube

---

### Steps to reproduce the behavior:

Create a new Qube.  Choose Standalone not from template.  Boot from external media (usb) on dom0.  

VM will boot from USB and try to install new OS.  But it can't find the hard drive.

### Expected behavior:

Because the Qube settings show a disk with 2048 I expect that this drive is available to the new standalone Qube.

### Actual behavior:

Actually I start the installer and it fails to detect a disk.

### General notes:

OS is Android86 64 bit.

EDITED: I think maybe this is specific to Android?  Seems like android only detects disks if they have a partition on them and that is not something I expected.  I must test with another OS to see if this is only for Android.

---

**Comment by unman** [comment]
@qubesissues Did you test with other OS or resolve the issue with Android?
The only related fact I can think of is that some installers will only work if the drives are presented as /dev/sda..  Is that what is happening here?
If so, this wouldn't seem to be a Qubes bug.

**Comment by unman** [comment]
@qubesissues ? Can you update please?

**Comment by andrewdavidwong** [comment]
Closing this for now due to the lack of response. If you revisit the matter in the future, or if anyone would like the issue to remain open, please leave a comment, and we'll be happy to reopen this. Thank you.
