### ISSUE TITLE
2 identical empty qubes boot from same iso CD differently, one works, one fails

### ISSUE THREAD

**Issue by RefinedSoftwareLLC** [QubesOS/qubes-issues#4023]
### Qubes OS version:

R4.0

### Affected component(s): 

"Boot qube from CDROM" feature

---

### Steps to reproduce the behavior:

Using the "Boot qube from CDROM" on Qubes with the exact same settings in the Qube Manager:
With one of my qubes, `Booting from ROM...` displays, and it crashes.
With one of my qubes, `Booting from DVD/CD...` displays, and it works.

#### Settings then Install
Download: Qubes-R4.0-x86_64.iso
Open Qube Manager, Menu `Qube`, Select `Create new qube`.

Note: `[Dom0] Create new qube` popup displays.
- Name and label: `settings-install`
- Type: `Standalone qube not based on a template`
- `[X]` launch settings after creation
- `[ ]` install system from device (also available from settings)

Press `OK`.

Note: `[Dom0] Settings: settings-install` popup displays.
Tab `Advanced`
- Mode: `HVM`

Press `Boot qube from CDROM`.

Boot from `Qubes-R4.0-x86_64.iso`.
```
SeaBIOS (version rel-1.10.2-0-g5f4c7b1-prebuilt.qemu-project.org)
Machine UUID <redacted>
Booting from ROM...
```
Note: Crashes.

#### Install then Settings
Download: Qubes-R4.0-x86_64.iso
Open Qube Manager, Menu `Qube`, Select `Create new qube`.

Note: `[Dom0] Create new qube` popup displays.
- Name and label: `install-settings`
- Type: `Standalone qube not based on a template`
- `[ ]` launch settings after creation
- `[X]` install system from device (also available from settings)

Press `OK`.

Boot from `Qubes-R4.0-x86_64.iso`.
```
SeaBIOS (version rel-1.10.2-0-g5f4c7b1-prebuilt.qemu-project.org)
Machine UUID <redacted>
Booting from DVD/CD...
```
Note: Works.
Open Qube Manager, Right click `install-settings` qube, Select `Qube Settings`.

Note: `[Dom0] Settings: install-settings` popup displays.
In tab `Advanced`, Press `Boot qube from CDROM`.

Boot from `Qubes-R4.0-x86_64.iso`.
```
SeaBIOS (version rel-1.10.2-0-g5f4c7b1-prebuilt.qemu-project.org)
Machine UUID <redacted>
Booting from DVD/CD...
```
Note: Still works.

### Expected behavior:

Booting from ISO CDROM should work on all Qubes.
If the example `settings-install` qube needs to have an internal setting changed, either:
- Temporarily change setting when the "Boot qube from CDROM" feature is used, and stop permanently setting it with the `install system from device (also available from settings)` feature.
- Permanently change setting on all qubes.
- Temporarily change setting for any qube in HVM mode.
- Add setting as an option in the "Boot qube from CDROM" feature.
- Add setting as an option in the Qube Manager's qube settings.

### Actual behavior:

2 qubes with the same Qube Manager settings, runs the "Boot qube from CDROM" feature differently, with one of them crashing.

### General notes:

---

### Related issues:

The solution to this issue, might also fix #3078.

**Comment by RefinedSoftwareLLC** [comment]
I was able to reproduce, and updated this bug report with the steps to.

I believe my example `settings-install` qube never calls `Booting from DVD/CD...` and `Booting from ROM...` is unrelated as just being the next boot option. But encase it is, searching online for `Booting from ROM...` has documentation of `Boot from a BEV entry on an optionrom.`

**Comment by awokd** [comment]
https://www.qubes-os.org/faq/#my-hvm-in-qubes-r40-wont-let-me-startinstall-an-os
