### ISSUE TITLE
Archlinux template build fails due to compilation error in vmm-xen

### ISSUE THREAD

**Issue by JohnDoe02** [QubesOS/qubes-issues#4026]
### Affected component(s): qubes-builder

---

### Steps to reproduce the behavior:

```
git clone https://github.com/QubesOS/qubes-builder.git
cd qubes-builder
cp example-configs/qubes-os-master.conf builder.conf
```
Then uncomment the last three lines in builder.conf to enable the build of the archlinux template.
```
make get-sources
make qubes-vm
```

### Expected behavior: 

Everything compiles without problems

### Actual behavior:

The compilation aborts when building vmm-xen with the following error message:
```
dsdt_pvh.c:3494:25: error: 'dsdt_pvh' undeclared here (not in a function); did you mean 'dsdt_pvh_len'?
 int dsdt_pvh_len=sizeof(dsdt_pvh);
```

### General notes:

I am using a Fedora 26 standalone qube for compilation.

---

**Comment by dimitar-petrov** [comment]
Facing the same issue

**Comment by arjan-s** [comment]
I created https://github.com/QubesOS/qubes-vmm-xen/pull/42 to fix this.

**Comment by ptitdoc** [comment]
I think this issue can now be closed based on @marmarek https://github.com/QubesOS/qubes-vmm-xen/pull/42 closure reason.
