### ISSUE TITLE
VM re-name with auto-boot flag enabled - causes minor error 

### ISSUE THREAD

**Issue by Aekez** [QubesOS/qubes-issues#4031]
### Qubes OS version:

Qubes 4.0.

### Affected component(s): 

Component responsible for auto-start of VM's during dom0 boot-time. Probably a missing logic in code for specific scenario.

---

### Steps to reproduce the behavior:

- Re-name a VM that has the qvm-prefs auto-boot flag enabled. 
- I have not tested it via terminal, changes was done via the VM GUI settings window.
- I've seen it happen many times since Qubes 4 (RC-2) till current version, though I always judged it harmless, albeit annoying.
- It's been happening since Qubes 4 RC-2 on multiple different hardware and Qubes 4 setups.
- As far as I'm concerned, it happens 100% all the time under the above scenario, but I haven't had the opportunity to test it enough to see if it happens all the time. It should be reproduce-able though.

### Expected behavior:

Applied logic to move all VM settings to new VM re-name, without keeping any old remnants of the old VM.

### Actual behavior:

The missing logic causes a duplicate of the auto-boot and the old auto-boot when changing name on a VM while auto-boot flag is enabled. In short, it doesn't delete the old auto-boot flag for the old VM name, after the re-name has finished, under the condition that the auto-boot flag was enabled (and maybe GUI needed, did not yet try it via terminal but may possibly be a factor).

### General notes:

- This issue appears very minor, almost only minor aesthetics level. For example it may annoy or give some people anxiety to see a VM fail to start during the boot-up, even though it's an old VM re-name, but it doesn't look like it carries any technical harm.
- Essentially it can possibly effect the overall impression of Qubes for newcomers, so it might carry some importance to fix in that regard. It may damage newcomers impression of Qubes 4 since it's literally a red colored failure flag in peoples face at every boot, in similar analogical fashion on how marketing ads indirectly effect people over time. 
- Beyond aesthetics, could it maybe affect the boot-time to take longer? If so, probably not much since it's still relative fast to boot, but it may be a question many people ask themselves when they see the red failed VM boot.
- I could have done more throughout predictability testing for the reproduce-ability but I'm short on time right now. From memory though, I've seen it happen pretty much every time I re-name a Qubes 4 VM, ever since Qubes 4 RC-2 (I did not actively use RC-1 so I can't speak about RC-1). 

---

### Related issues:

None that I can find. In general it appears as a harmless issue, so maybe it wasn't reported until now.

**Comment by Aekez** [comment]
https://github.com/QubesOS/qubes-issues/issues/4014 looks very similar to this issue, but doesn't look to be a duplicate since it's two different ways to reproduce towards the same end-result issue. Maybe the root cause is the same though?

**Comment by enricota66** [comment]
#4264  looks to be the same too.

**Comment by marmarek** [comment]
This is the same as #4014, because now rename is clone+remove.
