### ISSUE TITLE
check Qubes-Whonix 14 Template Appmenus implementation

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#4033]
Do you think appmenus (Qubes start menu default entries) will work like this? A quick look would be great so we don't need another template build just for this. (#4016)

* https://github.com/Whonix/qubes-template-whonix
* https://github.com/Whonix/qubes-template-whonix/tree/master/appmenus_stretch_whonix-gateway
* https://github.com/Whonix/qubes-template-whonix/tree/master/appmenus_stretch_whonix-workstation

[Just renamed from jessie to stretch (and removed wheezy symlinks).](https://github.com/Whonix/qubes-template-whonix/commit/f30acad3219ef9812d573ce39326a6e8b5a33cd1)

**Comment by Aekez** [comment]
- A minor feedback is that I really like you now give out-of-the-box user-choice between nautilus and dolphin. At least personally I can not stand dolphin in Qubes-Whonix. The included dolphin always gave me the feeling of being trapped in a small box, with annoying single-click special icon-links, and gives the feeling of cumberstone navigation. Kudos for putting in nautilus, and it's nice that both are included in the default menu entries for those who still prefer dolphin.

- In general for Qubes menu entries, I don't suppose it would be possible to make break-line categories in the XFCE4/other-menus' sub-folder menu entries? Pretty much similar to how Separator plugins work in the XFCE4 menu-bar.

For example with the case of Whonix (or any other OS-VM), something like this
```
    Whonix-WS menu example
-------------------------------------
konsole
dolphin
nautilus
------------break-line-------------
whonixcheck
whonix-irc-chat-support
janondisttorbrowser
anondist-torbrowser_update
------------break-line-------------
Qube Settings
-------------------------------------
```

**Comment by marmarek** [comment]
> Do you think appmenus (Qubes start menu default entries) will work like this?

Looks fine.
