### ISSUE TITLE
Pasting VM to VM does not work.

### ISSUE THREAD

**Issue by Jeeppler** [QubesOS/qubes-issues#4044]
### Qubes OS version:

R4.0

### Affected component(s): 

Pasting clipboard content does not work.

### Steps to reproduce the behavior:

See: "Actual behavior" section.

### Expected behavior:

1. In Qube A copy arbitrary text to clipboard CTRL+C
2. Copy arbitrary text to dom0 (inter-VM) clipboard using CTRL+SHIFT+C. A pop up appears stating that x bytes where copied to the clipboard.
3. Switch to Qube B.
4. Press CTRL+SHIFT+V to insert arbitrary text. A pop up notification will appear with the information that xy bytes have been pasted. 
5. In Qube B press CTRL+V to insert arbitrary text into any selected text field.

### Actual behavior:

1. In Qube A copy arbitrary text to clipboard CTRL+C
2. Copy arbitrary text to dom0 (inter-VM) clipboard using CTRL+SHIFT+C. A pop up appears stating that x bytes where copied to the clipboard.
3. Switch to Qube B.
4. Press CTRL+SHIFT+V to insert arbitrary text. The keyboard combination CTRL+SHIFT+V has no effect. No paste notification appears.

### General notes:

Copy and pasting worked after the installation of Qubes OS for several weeks.

I changed the keyboard layout from German to German Neo and back. Around the same time it stopped working. However, I also updated my VMs in the same time range. I am not sure if other users experience the same issue.

Restarting or updating the Qubes afterwards did not help. 

### Related issues:

Unkown.

**Comment by homotopycolimit** [comment]
I had may issues like this too - and most of the time it was because the k**eyboard shortcut was being used by a different app** as well. **CTRL+SHIFT+V is far too common** in my experience.

I suggest you try changing it in dom0 /etc/qubes/guid.conf to something that is certainly unique like `Ctrl-Alt-Shift-v` or sth like that. It might require more finger gymnastics to type, but ever since I never had problems with copying and pasting.

If you think your keyboard layout might be contributing to the problem, try running `xev` to see what actually happens when you press the keys,

**Comment by andrewdavidwong** [comment]
Have you modified the inter-VM copy/paste RPC policy?

**Comment by andrewdavidwong** [comment]
Does this happen all the time or only in certain destination VMs?

Does this happen with every program in the destination VM or only some of them?

**Comment by Jeeppler** [comment]
This behavior is consistent across Qubes regardless if I try to use Debian based Qubes or Fedora base Qubes.

Yes, it happens to all programs (which I normally use).

I mean I still see the notification 'xy bytes copied'. However, I do not see the paste notification. What command/program should be triggered when I press `CTRL+SHIFT+v`? Maybe, I can just trigger it manually by calling it directly and see if I get an error message or otherwise unusual behavior.

**Comment by marmarek** [comment]
Check `/var/log/qubes/guid.VMNAME.log` for relevant VM (where you want to paste).

**Comment by QOSRiddle** [comment]
Try XEV command to see if all keys you tab are recognized. Using DE and NEO i found out that the combination CTRL+SHIFT+v  is only getting CTRL+SHIFT as result.  Not sure why V is not recognized. Even with Mod4-v the V is not recognized, therefore I modified /etc/qubes/guid.conf to: 

secure_copy_sequence = “Mod4-c” ;    
secure_paste_sequence = “Mod4-m”;

and finally i got this basic function to work for Inter-VM copy/paste. 
Within a dom0 terminal Mod4-c is still not working. 
My mnemonic for this key combination:   Super-(C)opy   then   Super-(M)ove     to target VM.

(Mod4=Super=Windows Key)

**Comment by andrewdavidwong** [comment]
@Jeeppler, you still haven't said whether you've modified the inter-VM copy/paste RPC policy.

**Comment by Jeeppler** [comment]
So, I finally figured it out. There is no problem with the Qubes OS v4 copy and past functionality. It works just as intended. However, there are some very confusing things. 

What I did is, I installed Qubes with a [Neo keyboard layout](https://neo-layout.org/index_en.html). This layout is used for the luks/dm-crypt setup. Every time I boot my system I have to type my pass phrase using the Neo layout. The layout is always Neo regardless what the keyboard layout in the Qubes Dom0 or VMs is. 

After that I have to type in the password of the XCFE login screen. For the login screen I have to use the keyboard layout which is set in Dom0. 

Where it gets confusing is, when the screen saver dialog appears, then I have to type the password in using the English or German keyboard layout (I don't know which one, because I do not see the letters in plain text).

Furthermore, when I start a VM the VM will use whatever Dom0 has set at the boot time and VM's will keep that layout regardless if it is later changed in Dom0. In addition, the keyboard layout can be changed in the VM using `setxkbmap`. 

The problem I ran in is that even if I change the keyboard layout in Dom0 to something else than Neo, the Qubes paste shortcut is still bound to the layout set during the installation in the VMs, in my case Neo. The Neo shortcut for pasting in Qubes is CTRL+SHIFT+W on a QWERTY layout, which in many cases is already occupied in applications. Regardless, I just use the same Neo layout everywhere. Except for the lock screen and the "Qubes copy to VM" dialog. 

The "Qubes copy to VM" dialog falls back to the German keyboard layout. It is the same issue as with the lock screen.

@andrewdavidwong you can close this issue.
