### ISSUE TITLE
New standalone VMs inherit template's private filesystem state

### ISSUE THREAD

**Issue by tasket** [QubesOS/qubes-issues#4045]
### Qubes OS version:

R4.0

### Affected component(s): 

Standalone VMs created from templates

---

### Steps to reproduce the behavior:

1. Add some file to templateVM's /home/user then shutdown
2. Create standalone VM from template
3. Start standalone and view the files

### Expected behavior:

Standalone VM receives a newly-initialized private fs.

### Actual behavior:

Information from template private fs is retained.

### General notes:

---

**Comment by andrewdavidwong** [comment]
If I understand correctly, @tasket is saying that, since TemplateBasedVMs no longer inherit the contents of `/home` from their parent TemplateVMs in 4.0 (changed from 3.2), StandaloneVMs also should not inherit the contents of `/home` from the TemplateVMs from which they are created.

**Comment by tasket** [comment]
I was going to say that... Thanks for clarifying! The consistency part of it is the most important, IMO, because ppl will use template-based appVMs most of the time and expect the same 'cleanliness' from standalones -- but may leak files without realizing.

**Comment by marmarek** [comment]
Note that when you create a StandaloneVM from a Template, it is in fact `qvm-clone --class StandaloneVM` operation. But indeed it is inconsistent.

**Comment by tasket** [comment]
I guess this is limited to the GUI tool, as `qvm-create` gives me an error when I specify standaloneVM and a template.

Should this be resolved with `import_data(blank_file)` ?

**Comment by marmarek** [comment]
> Should this be resolved with import_data(blank_file) ?

Better skip cloning private volume at all in such a case. See [clone_vm function](https://github.com/QubesOS/qubes-core-admin-client/blob/master/qubesadmin/app.py#L391-L402). Maybe some extra argument there (`ignore_volumes`, or `clone_volumes`)? Then use it in qvm-clone tool (some extra option) and also in GUI when creating standalone VM.
