### ISSUE TITLE
Make signed scrypt binary available to Qubes users for emergency backup recovery

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#4047]
I've just updated [Emergency Backup Recovery without Qubes - format version 4](https://www.qubes-os.org/doc/backup-emergency-restore-v4/) to strongly recommend that Qubes users store a copy of the `scrypt` utility with their 4.x backups, since it is required in order to access the data in those backups (see https://github.com/QubesOS/qubes-doc/commit/bb2617308927b84ee1d32ce0301a093e1fa025f2 and, for background, #971).

@marmarek and I previously agreed that it would be a good idea to make a signed binary available to Qubes users so that all Qubes users don't have to compile it from source themselves.

One thing to think about is whether the signed binary should also be included in Qubes itself (e.g., in dom0) or just as a web download.

**Comment by marmarek** [comment]
We already have signed rpm package with the binary. You can easily extract binary (`rpmdev-extract` tool) from there and treat rpm as a signed container. Alternatively we could put just a binary with a detached signature somewhere. Obviously the first option if far less work, as it is already done: https://yum.qubes-os.org/r4.0/current/vm/fc28/rpm/scrypt-1.2.1-1.fc28.x86_64.rpm (you can also choose older Fedora version, to have it linked with older libraries - useful for usage on non-Fedora systems)

**Comment by andrewdavidwong** [comment]
@marmarek, I just tried to test these instructions and failed on step 6:

```
 6. Verify the integrity of and decrypt the `private.img` file that houses your
    data.

        [user@restore ~]$ for f_enc in vm1/private.img.???.enc; do \
            f_dec=${f_enc%.enc}; \
            echo "$backup_id!$f_dec!$backup_pass" | scrypt dec -P $f_enc $f_dec || break; \
            done
```

When I try this, I get:

```
scrypt-1.2.1-2: Input is not valid scrypt-encrypted block
```

**Comment by andrewdavidwong** [comment]
This is on 4.0.1, with a single test VM backup that I created just for the purpose of testing these instructions.
