### ISSUE TITLE
Deleted Pulseaudio from dom0 and broke every VM

### ISSUE THREAD

**Issue by Featheruser** [QubesOS/qubes-issues#4048]
### Qubes OS version:

R3.2

### Affected component(s): 

All VMs and dom0

---

### Steps to reproduce the behavior:

in dom0 'sudo dnf remove pulseaudio

### Expected behavior:

Remove pulseaudio from dom0 

### Actual behavior:

deleted pulseaudio, pulseaudiomodule-conf and:
paprefs
qubes-gui-dom0
rtkit
soxr
speexdsp
webrtc-audio-processing

### General notes:

stopped all vms from starting, how can I reinstall pulseaudio and the dependencies.

---

**Comment by andrewdavidwong** [comment]
Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this does not appear to be suitable for `qubes-issues`. We ask that you please send this to the `qubes-users` [mailing list](https://www.qubes-os.org/support/) instead. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a brief comment explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.

**Comment by marmarek** [comment]
That's a bad idea, as downloaded packages may be quite large (for example extra templates).

**Comment by Featheruser** [comment]
what was it that made dnf remove qubes-gui-dom0?

**Comment by marmarek** [comment]
qubes-gui-dom0 depends on pulseaudio, which you've removed.

**Comment by Featheruser** [comment]
the gui depends on an audio program?

**Comment by marmarek** [comment]
Yes, part of qubes-gui package is handling audio virtualization. Anyway, this isn't a place for this discussion, as @andrewdavidwong said before.
