### ISSUE TITLE
Consider giving Qube Manager persistent window memory (UX, probably minor)

### ISSUE THREAD

**Issue by Aekez** [QubesOS/qubes-issues#4049]
### Qubes OS version:

Qubes 4.0.

### Affected component(s): 

Qube Manager.
Dom0~

---

### Steps to reproduce the behavior:

Shutdown the Qube Manager application after making window-size state changes, and then start the Qube Manager again. Straight forward, 100% reproduce-able.

### Expected behavior:

The Qube Manager remembering the previous window-size state.

### Actual behavior:

Qube Managers window-size sate reverts back to the out-of-the-box default values.

### General notes:

**Purely user experience related.**
- Potentially minor, or potentially non-minor+ (depending on the end-user).
- Potential risk is people being less inclined to use the Qube Manager because of extra work to get window settings right every time its started.
- Another potential risk is if user keeps using the Qube Manager despite getting frustrated about having to change values every time.
- There is also the possibility that many users doesn't mind it much, depending on the users.
- The question how many whom still use the Qube Manager this far into the Qubes 4 release, may be a relevant question on whether to spend time to fix this lack of window memory.
- and other potential user-experience scenarios, etc.

---

### Related issues:

None that I could find with search.

### Additional followup suggestion:
Whether it is feasible/desirable to make an optional option to toggle the Qube Manager to remember which monitor it was on last, thereby making it easy to have a dedicated extra monitor for Qubes states on multi-monitor workstations. This however probably would require much extra work, and I guess it might be even more work with different window managers? This additional followup suggestion should be seen as separated as an extra suggestion to the OP suggestion.

It could however potentially be a sweet touch to Qubes, analogical to the dot above the i (when it comes to final minor quality details), if Qubes had an optional VM manager screen like described above.

**Comment by marmarta** [comment]
Remembering the size is a very good idea, I'll put it in; furthermore, Qube Manager (due to legacy code) was forced to appear int he top left corner of the screen. Now it will follow the normal rules of position, that is, close to wherever it was executed - I think it's more practical than remembering the location (and perhaps confusing the user who is used to programs appearing near the window they were ran from). But I'm open to being convinced otherwise.

**Comment by andrewdavidwong** [comment]
> furthermore, Qube Manager (due to legacy code) was forced to appear int he top left corner of the screen. Now it will follow the normal rules of position, that is, close to wherever it was executed - I think it's more practical than remembering the location (and perhaps confusing the user who is used to programs appearing near the window they were ran from). But I'm open to being convinced otherwise.

I think this part is just controlled by the window manager's settings.
