### ISSUE TITLE
Old bug resurrected: Changed Screen Resolution in Dom0 (external Monitor) not given to VMs

### ISSUE THREAD

**Issue by DTMW2** [QubesOS/qubes-issues#4052]
### Qubes OS version:

Qubes release 4.0 (R4.0)

### Affected component(s): 

graphical window system, input handling (mouse), resolution change and notification.

---

### Steps to reproduce the behavior:

I started with a release candidate version which got updated to final release. Newest updates (including qubes-dom0-current-testing) are installed. Everything worked fine but 2-4 weeks ago or so after installing updates the bug occured for the first time (again as in "resurrected").

### Expected behavior:

If an external display is connected (in my case 4K resolution via HDMI as an additional display to full-hd notebook-display) the resolution inside each VM shall get updated, too. Mouse clicks shall get detected inside a window at the correct xy-coordinates when one clicks inside a window (e.g. disp-VM -> firefox).

### Actual behavior:

Whenever I connect my external display with higher resolution (4K instead of full-hd of my internal display) running machines don't get a working info about that change. Those machines only recognize mouse-input if I move the corresponding windows to the upper left corner of my external display and if the window is not larger than full-hd.

### General notes:

1. Qubes is awesome!

2. This bug seems like a resurrected version of older ones. Both in Qubes 3.2 and 4RC this bug occured at least twice and got fixed by an update.

---

**Comment by andrewdavidwong** [comment]
> Please comment on the old issue, and we will reopen it.
