### ISSUE TITLE
When shutting down VMs, they often get stuck at 50% CPU usage

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#4057]
### Qubes OS version:

`R3.2`

### Affected component(s): 

Using `qvm-shutdown` from the command-line and shutting down VMs using Qubes Manager

---

### Steps to reproduce the behavior:

1. Select a running VM in Qubes Manager.
2. Press the shut down button.

or

1. Use `qvm-shutdown --wait` to shut down the VM.

### Expected behavior:

The VM shuts down normally.

### Actual behavior:

Around 30-40% of the time, the VM's CPU usage (as shown in Qubes Manager) goes up to 50%. The laptop's fan speeds up (ThinkPad T450s), and the VM does not shut down for a long time. If you wait, it will eventually either shut down or get killed due to the timeout.

**Comment by donob4n** [comment]
Hi, I think this also happens in Qubes 4.0, I have seen it many of times but I didn't report since I didn't found a way for reproduce it.

In my case I tailed '/var/log/xen/console/guest-'vm-name'.log' and I saw systemd waiting for some services to stop but unfortunately I could not read the affected services (the output was pretty ugly).

**Comment by andrewdavidwong** [comment]
@marmarek, let us know if there are any logs we should collect on 3.2 and 4.0 next time this happens.

**Comment by andrewdavidwong** [comment]
It seems like this has started happening much more often after recent updates.

**Comment by mig5** [comment]
For me it's the opposite - I've not seen this issue since September I think. VMs shut down pretty fast, always at a consistent speed every time, within about 5-10s.

**Comment by andrewdavidwong** [comment]
> For me it's the opposite - I've not seen this issue since September I think. VMs shut down pretty fast, always at a consistent speed every time, within about 5-10s.
> 
> (Qubes 4.0)

Probably a difference between 3.2 and 4.0. Still happening regularly on 3.2.

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 has reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
