### ISSUE TITLE
qfile-agent fatal error no such file

### ISSUE THREAD

**Issue by pietrushnic** [QubesOS/qubes-issues#4058]
### Qubes OS version:

 R4.0

### Affected component(s): 

qvm-copy between all VMs

---

### Steps to reproduce the behavior:

```
echo 1234 > a
qvm-copy vault a
```

### Expected behavior:

File should be copied to vault VM.

### Actual behavior:

qfile-agent throws error:

```
qfile-agent: Fatal error: stat vault (error type: No such file or directory)
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
EOF
```

### General notes:

The only thing I was able to narrow is that below version works:

```
sudo /usr/lib/qubes/qrexec-client-vm '$default' qubes.Filecopy /usr/lib/qubes/qfile-agent a
```

Debugging `qvm-copy-to-vm` show:

```shell
[user@personal ~]$ sudo qvm-copy vault a
+ set -e
+ '[' 3 -lt 2 ']'
+ '[' '$default' = --without-progress ']'
+ export PROGRESS_TYPE=console
+ PROGRESS_TYPE=console
+ VM='$default'
+ shift
+ '[' console = console ']'
++ du --apparent-size -c -- vault a
++ tail -1
++ cut -f 1
+ FILECOPY_TOTAL_SIZE=1
+ export FILECOPY_TOTAL_SIZE
+ '[' '$default' '!=' '$default' ']'
+ /usr/lib/qubes/qrexec-client-vm '$default' qubes.Filecopy /usr/lib/qubes/qfile-agent vault a
qfile-agent: Fatal error: stat vault (error type: No such file or directory)
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
EOF
```

I'm not sure if input params to `qfile-agent` changed or I messed up something. I'm not confident 100%, but this probably happen after template update.

---

**Comment by donob4n** [comment]
This is not a bug, qvm-copy is different in Qubes 4 (assuming in Qubes 3.2 was not modified).

You should do: 'qvm-copy a' , then you will get a dialog in dom0 asking the target VM. This way the source AppVM does not know the name of the destination VM.

**Comment by andrewdavidwong** [comment]
Filing this as a UX enhancement to improve the error message.

**Comment by pietrushnic** [comment]
Help of `qvm-copy` say:

```
usage: /usr/bin/qvm-copy-to-vm [--without-progress] dest_vmname file [file]+
```

This looks confusing to users.
