### ISSUE TITLE
Qubes-Whonix build failing - /bin/bash: -c: line 23: syntax error: unexpected end of file

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#4063]
https://travis-ci.org/Whonix/qubes-template-whonix/jobs/401657325
https://travis-ci.org/Whonix/qubes-template-whonix

`/bin/bash: -c: line 23: syntax error: unexpected end of file`

Any idea about this one?

**Comment by marmarek** [comment]
Old make in travis env again... Try now.
