### ISSUE TITLE
Reduce Qubes TemplateVM packages by using zerofree?

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#4076]
Thanks to a contribution by @onion_night the size of [Non-Qubes-Whonix](https://www.whonix.org/wiki/Non-Qubes-Whonix) (all raw images, VirtualBox ova and libvirt qcow2) downloadable images could be reduced by approximately 35%.

references:

* https://phabricator.whonix.org/T790
* https://github.com/Whonix/Whonix/blob/master/build-steps.d/2350_zerofree-raw
* https://forums.whonix.org/t/reducing-size-of-ova-images/5095
* https://packages.debian.org/stretch/zerofree

Do you think this is also possible for Qubes TemplateVMs?

**Comment by marmarek** [comment]
We already [run fstrim](https://github.com/QubesOS/qubes-linux-template-builder/blob/master/cleanup_image#L24) there, which I think have the same effect.
