### ISSUE TITLE
sys-usb devices automatically removed after anon-whonix is shut down

### ISSUE THREAD

**Issue by MartynasJanonis** [QubesOS/qubes-issues#4078]
### Affected component(s):

sys-usb, anon-whonix

---

### Steps to reproduce the behavior:

- Start anon-whonix
- After it starts, shut it down

### Expected behavior:

All sys-usb devices remain connected

### Actual behavior:

All sys-usb devices are automatically removed and not visible in the device manager menu.

### General notes:

Whonix version 14. I have to restart the sys-usb qube for the devices to reappear and only devices marked "dom0:" remain connected.

---

**Comment by MartynasJanonis** [comment]
They are totally independent. Nothing is connected to anon-whonix.

**Comment by MartynasJanonis** [comment]
Interestingly, the devices only disappear from the toolbar and qvm-usb still shows them. Attaching a random device to any qube makes all devices reappear in the toolbar.
![sys-usb issue1](https://user-images.githubusercontent.com/32335421/42710900-a03ec0e2-86ee-11e8-9ed7-399b88e2f458.png)

**Comment by marmarek** [comment]
Hmm, do you see any errors in `~/.xsession-errors` in dom0?

**Comment by MartynasJanonis** [comment]
Yes,
``
(Thunar:5453): thunar-WARNING **: Failed to launch the volume manager (Failed to execute child process "thunar-volman" (No such file or directory)), make sure you have the "thunar-volman" package installed.
``

**Comment by marmarek** [comment]
Anything else? Something with "qui" or "devices" in message?

**Comment by MartynasJanonis** [comment]
No, just a lot of "thunar-WARNING" messages.
Also, attaching USB devices fixes the problem (i.e. all devices become visible in the toolbar).
Attaching a screenshot of what happens after anon-whonix shuts down.
![screenshot_2018-07-13_20-05-01](https://user-images.githubusercontent.com/32335421/42711828-18c7afc6-86f2-11e8-8a69-af910b32bdbf.png)

**Comment by marmarek** [comment]
What is qid of anon-whonix and sys-usb on your system (see qvm-prefs tool)? Devices widget identifies qubes using qid and maybe get confused by this specific values for some reason?

**Comment by marmarek** [comment]
Ok, that's it. qid of anon-whonix is a prefix of sys-usb's qid. I can reproduce it by shutting down a VM with qid 1 (debian-9 in my case).
Apparently in some place comparing them is broken. @marmarta is looking where.

**Comment by marmarta** [comment]
This is a truly magnificent bug! Hopefully we've got it and the fix is underway (just let me test if it won't break another surprising thing...)
