### ISSUE TITLE
qvm-features-request whonix-gw=1 / anon-gateway tag / sdwdate-gui-qubes / review /etc/qubes/post-install.d/30-whonix-ws.sh

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#4080]
Added `qvm-features-request whonix-gw=1`.

https://github.com/Whonix/qubes-whonix/commit/436a278cf1e9f92e046b1ecf8a8dd97b9364a039

Required for sdwdate-gui-qubes.

Should [`/etc/qubes/post-install.d/30-whonix-ws.sh`](https://github.com/Whonix/qubes-whonix/blob/master/etc/qubes/post-install.d/30-whonix-ws.sh) have `errtrace` (`set -e`)? I.e. should it `exit` non-zero and therefore break apt when it fails? Better not?

Any other changes required? https://github.com/QubesOS/qubes-core-admin-addon-whonix/blob/master/qubeswhonix/__init__.py needs some ` if 'whonix-gw' in template.features:` above ` if 'whonix-ws' in template.features:` to add the `anon-gateway` tag but that's about all?

Related:

* https://github.com/QubesOS/qubes-core-admin/pull/216
* https://forums.whonix.org/t/sdwdate-gui-for-qubes-testers-wanted-developpers-welcome
* https://phabricator.whonix.org/T534

**Comment by marmarek** [comment]
> Should /etc/qubes/post-install.d/30-whonix-ws.sh have errtrace (set -e)? I.e. should it exit non-zero and therefore break apt when it fails? Better not?

Better not.

> Any other changes required? https://github.com/QubesOS/qubes-core-admin-addon-whonix/blob/master/qubeswhonix/__init__.py needs some if 'whonix-gw' in template.features: above if 'whonix-ws' in template.features: to add the anon-gateway tag but that's about all?

Yes, I'm on it.

**Comment by marmarek** [comment]
@adrelanos see https://github.com/QubesOS/qubes-core-admin-addon-whonix/pull/1
