### ISSUE TITLE
all Qubes-Whonix 14 Appmenu (Qubes start menu) entries missing

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#4083]
The only entry is `Qube Appmenu` for anon-whonix, sys-whonix, whonix-gw-14 and whonix-ws-14.

This was a reinstallation in the sense that all Whonix VMs were deleted, all dom0 dnf packages removed. Then reinstalled.

----

* https://github.com/Whonix/qubes-template-whonix
* https://github.com/Whonix/qubes-template-whonix/tree/master/appmenus_stretch_whonix-gateway
* https://github.com/Whonix/qubes-template-whonix/tree/master/appmenus_stretch_whonix-workstation

[Just renamed from jessie to stretch (and removed wheezy symlinks).](https://github.com/Whonix/qubes-template-whonix/commit/f30acad3219ef9812d573ce39326a6e8b5a33cd1)

(https://github.com/QubesOS/qubes-issues/issues/4033)

**Comment by marmarek** [comment]
What exactly do you mean? Which entries are present and which are missing?

**Comment by adrelanos** [comment]
Yes, was due to wrong installed template version.
