### ISSUE TITLE
Unable to connect to Ethernet after suspend/resume (but WiFi works)

### ISSUE THREAD

**Issue by ghost** [QubesOS/qubes-issues#4084]
### Qubes OS version:

Qubes release 4.0 (R4.0)

### Affected component(s): 

net-vm Ethernet connection

---

### Steps to reproduce the behavior:

1. Verify Ethernet connection works.
2. Suspend (sleep?) then resume.
3. Ethernet will not connect, previously connected Ethernet Network shows "disconnected" status with no option to connect.
4. WiFi connections do work though.
5. Restarting the system (not just net-vm) allows Ethernet connection again, until next suspend.

### Expected behavior:

Connect to same Ethernet Network after resume.

### Actual behavior:

Ethernet will not connect, previously connected Ethernet Network shows "disconnected" status with no option to connect.

### General notes:

Same hardware, did not have this issue on Qubes 3.2 (unsure which version, but it was months ago). Qubes is AMAZING otherwise.

Had this issue on 2 clean installs (same installation media, granted).

Tried the [wireless troubleshooting instructions](https://www.qubes-os.org/doc/wireless-troubleshooting/) except for the r8169 driver as opposed to the WiFi drivers. This did not resolve it. Reloading the r8169 driver via rmmod/modprobe had an effect, but Ethernet Network was perpetually "connecting" (with no connection). Tried adding to suspend-module-blacklist (along with the iwlmvm and iwlwifi modules) but after system reboot, no connections at all were possible (and rebooting was not possible either...) until I emptied the suspend-module-blacklist file.  

---

**Comment by atanasantonov** [comment]
Hi, same scenario happens to me. Also tried to blacklist and reload the driver as in the WiFi example  but no effect - after resume it stays disconnected to the network. 

Restart the **sys-net** solves the problem, but every domain that uses **sys-net** respectively **sys-firewall** must be shut down before doing that.

But yes... Qubes is AMAZING!!

**Comment by andrewdavidwong** [comment]
> Restart the **sys-net** solves the problem, but every domain that uses **sys-net** respectively **sys-firewall** must be shut down before doing that.

You can simply set `sys-firewall`'s NetVM to `none` before restarting `sys-net`. Then you won't have to shut down any other VMs.

**Comment by atanasantonov** [comment]
> Restart the **sys-net** solves the problem, but every domain that uses **sys-net** respectively **sys-firewall** must be shut down before doing that.

As mentioned above you can run the following commands in terminal emulator:

```
qvm-prefs sys-firewall netvm ''
qvm-shutdown sys-net
qvm-start sys-net
qvm-prefs sys-firewall netvm 'sys-net'
```

**Comment by andrewdavidwong** [comment]
Is this still a problem in 4.1?
