### ISSUE TITLE
please remove Whonix 14 from Qubes unstable repository

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#4086]
Please remove Whonix 14 (all Whonix versions) from Qubes unstable repository.

Qubes decided to no longer use `qubes-dom0-unstable` for template testing.
Qubes decided to use `templates-community-testing` for template testing.

(As per https://github.com/QubesOS/qubes-issues/issues/3935#issuecomment-405108744. This looks much better!)

Therefore, please remove Whonix 14 from `qubes-dom0-unstable` since that version has been superseded with versions available from `templates-community-testing`.

You might like to use that opportunity to remove any other outdated templates from `qubes-dom0-unstable`?

**Comment by marmarek** [comment]
Done (those were the only templates there - others were removed earlier).
