### ISSUE TITLE
New vm cannot boot from block device

### ISSUE THREAD

**Issue by yitjob** [QubesOS/qubes-issues#4092]
### Qubes OS version:

4.0

### Affected component(s): 

- Qube Manager
- Command line qvm-start 

---

### Steps to reproduce the behavior:

First create a new vm of the type Standalone not based on a template.

Then try to boot it:
1. From a dom0 terminal:
`qvm-start --cdrom=sys-usb:/dev/sdb foo_appvm` 

2. From Qube manager:
Settings, Advanced tab, boot from cdrom and selecting the bootable usb drive.

### Expected behavior:

The appvm boots from the specified block device.

### Actual behavior:

Same results in either way: The appvm shuts down without booting properly.

### General notes:

Not sure how (perhaps changing the virtualization type), but in some cases the arch linux grub boot menu appeared and then no installation could be performed since the installation process did not start.

---

### Related issues:

n/a

**Comment by andrewdavidwong** [comment]
Does this help?

https://www.qubes-os.org/faq/#my-hvm-in-qubes-r40-wont-let-me-startinstall-an-os

**Comment by yitjob** [comment]
In my case it does not, neither from the dom0 terminal nor the gui.
Instead a fast trace of kernel panic and shut down occurs.

**Comment by marmarek** [comment]
Try setting kernel to none (in qube settings) or to empty string (in qvm-prefs cmdline tool).
