### ISSUE TITLE
some Qubes-Whonix 14 Appmenu (Qubes start menu) entries missing

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#4093]
Qubes R4 / Qubes-Whonix 14

sys-whonix has:

* Dolphin
* Konsole
* Qube Settings
* WhonixCheck

Expected:

A lot more... All from https://github.com/Whonix/qubes-template-whonix/blob/master/appmenus_stretch_whonix-gateway/netvm-whitelisted-appmenus.list

I guess:

* that is because in Qubes R4 there is technically seen more NetVM (replaced by provides_network)?
* vm-whitelisted-appmenus.list is for TemplateBasedVM?
* whitelisted-appmenus.list is for TemplateVM?

-----

Do `*-appmenus.list` support `#` comments?

-----

* https://github.com/Whonix/qubes-template-whonix
* https://github.com/Whonix/qubes-template-whonix/tree/master/appmenus_stretch_whonix-gateway
* https://github.com/Whonix/qubes-template-whonix/tree/master/appmenus_stretch_whonix-workstation

(https://github.com/QubesOS/qubes-issues/issues/4033)

**Comment by marmarek** [comment]
> that is because in Qubes R4 there is technically seen more NetVM (replaced by provides_network)?
> vm-whitelisted-appmenus.list is for TemplateBasedVM?
> whitelisted-appmenus.list is for TemplateVM?

Yes, netvm-whitelisted-appmenus.list is unused in R4. 


> Do *-appmenus.list support # comments?

Theoretically no, but entries pointing non-existing menu entries are ignored, so in practice it should work.
