### ISSUE TITLE
'Connected to Tor.' message missing in Qubes-Whonix 14 / notify-send broken in Qubes-Whonix 14

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#4098]
### Qubes OS version:
R4

### Affected component(s): 
Whonix

---

### Steps to reproduce the behavior:
Boot Whonix 14.

    notify-send --expire-time 20000 '[sys-whonix]' 'Connected to Tor.'

### Expected behavior:
passive popup functional just like in non-Whonix VMs.

### Actual behavior:
No passive popup shown.

### General notes:
Not happening in R3.2. Strange, no?

Installing package `mate-notification-daemon` fixes the issue. This this an acceptable solution?

**Comment by marmarek** [comment]
Is there any other notification daemon installed? `dpkg -l|grep notification`?
Is hardcoding `mate-notification-daemon` in dependencies a good idea? Isn't it a problem when one use KDE (non-Whonix?)?

**Comment by marmarek** [comment]
It may be related to reduced dependencies of qubes-core-agent (split into smaller packages, split qubes-vm-recommended/qubes-vm-depencendies).

**Comment by adrelanos** [comment]
Marek Marczykowski-Górecki:
> Is there any other notification daemon installed? `dpkg -l|grep notification`?

No. Strangely that is ok for Non-Qubes-Whonix but not for Qubes-Whonix.)

> Is hardcoding `mate-notification-daemon` in dependencies a good idea? Isn't it a problem when one use KDE (non-Whonix?)?

Could be in theory. But works well in VirtualBox KDE Non-Qubes-Whonix.
So good enough.
