### ISSUE TITLE
USB Audio Device Unusable In Qubes R4.0

### ISSUE THREAD

**Issue by ghost** [QubesOS/qubes-issues#4103]
### Qubes OS version:

`R4.0`

### Affected component(s): 

Not entirely sure. `sys-usb`, `qvm-usb`, StandaloneVM running `fedora-28`, USB-based audio device (e.g FIIO Alpen 2 E17K)

---

### Steps to reproduce the behavior:

0. Set up USB Qube as described in documentation - USB Keyboard & Mouse work well
1. Attach USB Audio device
2. Attach audio device to a Qube where media is to be played
3. Play media

### Expected behavior:

- USB Audio device is properly attached - this step does not always work, `qvm-usb a <vm> sys-usb:1-1` for example will hang with various errors seen in the VM like:
```shell
usb 1-1: 3:1: usb_set_interface failed (-19)
```
or
```shell
vhci_hcd: vhci_device speed not set
```
or
```shell
usb 1-1: timeout: still 3 active urbs on EP #3
```
or
```shell
vhci_hcd vhci_hcd.0: pdev(0) rhport(0) sockfd(0)
vhci_hcd vhci_hcd.0: devid(196636) speed(2) speed_str(full-speed)
```
while `qvm-usb a ...` has not completed in `dom0`
- VM properly detects device and provisions it as a sound output device
- Sound plays through USB Audio device

### Actual behavior:

- Device doesn't always attach cleanly
- No new audio output device seen in VM
- Sound is heard through regular speakers and not through speaker/headset attached to USB audio device

### General notes:

This USB audio device worked fine in Qubes R3.2 with a USB qube and `fedora-25` StandaloneVM.

---

**Comment by manasb** [comment]
The behavior described in https://github.com/QubesOS/qubes-issues/issues/4127 seems to be what I am seeing here too. I did not have any stability issues at all with R3.2, the same USB audio device was stable and worked perfectly. Perhaps the instability has something to do with the USB audio device being unusable?

**Comment by manasb** [comment]
I think setting it as a duplicate of https://github.com/QubesOS/qubes-issues/issues/3628 makes more sense - that ticket has better information and also includes the actual messages seen in the sys-usb and AppVM logs.
