### ISSUE TITLE
cursory review of Qubes-Whonix 14 installation instructions

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#4112]
Could you have a glimpse please?

https://www.whonix.org/wiki/Qubes/Install/Testing

----

* There'll soon be a call for testers.
* I guess the templates are good enough for release now.
* I'd also take these instruction for official stable release.
* Requiring to install packages from Qubes testing repository is a bit messy but well. We get rid of them as these packages flow into Qubes stable.
* `/etc/yum.repos.d/qubes-templates.repo` vs `/etc/yum.repos.d/qubes-templates.repo.rpmnew` is very messy but well.

----

* Also messy:
  * Use Qubes R3.2 only: Qubes VM Manager -> sys-whonix -> right click -> VM settings -> Template -> whonix-gw-14 -> OK
  * Use Qubes R3.2 only: Qubes VM Manager -> anon-whonix -> right click -> VM settings -> Template -> whonix-ws-14 -> OK 
  * But maybe we release an `qubes-mgmt-salt-dom0-virtual-machines` upgrade to R3.2 once Qubes-Whonix 14 was released as stable?

----

* Most importantly:
  * Does the `qubes-mgmt-salt-dom0-virtual-machines` (`sudo qubesctl state.sls qvm.anon-whonix`) version in Qubes R4 already include versioned suffixes (`-14`)?

**Comment by andrewdavidwong** [comment]
@adrelanos: After reading the [Update](https://www.whonix.org/wiki/Qubes/Update) instructions, it looks like the main command that performs the actual update from Whonix 13 to 14 is:

```
sudo apt-get dist-upgrade
```

However, I (and probably other users) still have the old habit of using this command for regular daily updates:

```
sudo apt-get -y update && sudo apt-get -y dist-upgrade
```

(I can't remember where this habit came from. I think it used to be the standard recommended update command or built into a script somewhere.)

Does this mean that I already upgraded from Whonix 13 to 14 at some point without realizing it? If so, that's welcome news, but I don't see any way to check the version of a Whonix TemplateVM (tried searching the wiki, looking for an `/etc/*release*` file, WhonixCheck doesn't display it, etc.).

**Comment by adrelanos** [comment]
Andrew David Wong:
> @adrelanos: After reading the [Update](https://www.whonix.org/wiki/Qubes/Update) instructions, it looks like the main command that performs the actual update from Whonix 13 to 14 is:
> 
> ```
> sudo apt-get dist-upgrade
> ```
> 
> However, I (and probably other users) still have the old habit of using this command for regular daily updates:
> 
> ```
> sudo apt-get -y update && sudo apt-get -y dist-upgrade
> ```

I don't like that version of the command much since some apt sources
unavailable by apt-get update would still let dist-upgrade continue.

> (I can't remember where this habit came from. I think it used to be the standard recommended update command or built into a script somewhere.)


> Does this mean that I already upgraded from Whonix 13 to 14 at some point without realizing it?

No.

Following https://www.whonix.org/wiki/Upgrading_Whonix_13_to_Whonix_14
required. Won't be happening by "sudo apt-get -y dist-upgrade" alone
since one has to switch from jessie to stretch repositories.

> If so, that's welcome news, but I don't see any way to check the version of a Whonix TemplateVM (tried searching the wiki, looking for an `/etc/*release*` file, WhonixCheck doesn't display it, etc.).
> 

Whonix 14 has:

cat /etc/whonix_version

(Also "whonixcheck --verbose" shows it but among other things that cause
more questions than support could handle.)

**Comment by andrewdavidwong** [comment]
>> Does this mean that I already upgraded from Whonix 13 to 14 at some point without realizing it?
> 
> No.
> 
> Following https://www.whonix.org/wiki/Upgrading_Whonix_13_to_Whonix_14
> required. Won't be happening by "sudo apt-get -y dist-upgrade" alone
> since one has to switch from jessie to stretch repositories.
> 
Does this mean that the [Update](https://www.whonix.org/wiki/Qubes/Update) page is incorrect and needs to be updated?

I wonder whether we should even have these two separate sets of instructions:

1. https://www.whonix.org/wiki/Qubes/Update
2. https://www.whonix.org/wiki/Upgrading_Whonix_13_to_Whonix_14

Perhaps (1) should contain a list of "Upgrading_Whonix_N_to_Whonix_N+1" links, including (2), but (1) should not attempt to duplicate or generalize the instructions contained in those linked pages, or else we'll end up with the current situation, i.e., incorrect info in (1).

**Comment by adrelanos** [comment]
Btw terminology update vs upgrade is broken globally. Reference:
http://forums.whonix.org/t/defining-update-and-upgrade-for-whonix-wiki

Andrew David Wong:
> Does this mean that the [Update](https://www.whonix.org/wiki/Qubes/Update) page is incorrect and needs to be updated?
> 
> I wonder whether we should even have these two separate sets of instructions:

Yes. One is for usual upgrade; two is for release upgrade.

> 1. https://www.whonix.org/wiki/Qubes/Update

Btw do we have similar instructions on how to keep Qubes dom0 and templates such as Debian, Fedora up to date for Qubes?

> 2. https://www.whonix.org/wiki/Upgrading_Whonix_13_to_Whonix_14

Release upgrade. Similar to https://www.qubes-os.org/doc/upgrade-to-r4.0/.

> Perhaps (1) should contain a list of "Upgrading_Whonix_N_to_Whonix_N+1" links,

Yes, but only https://www.whonix.org/wiki/Upgrading_Whonix_13_to_Whonix_14 not a list of them.

(Confusing, not clear if these would still work, not clear if a good idea to upgrade from let's say 11 -> 12 -> 13 -> 14, not clear how many users are still on versions older than 13.)

Related tickets and discussions:

- "do not show this message again checkbox" tool needed - https://phabricator.whonix.org/T865
- Whonix Upgrade Notification needed - https://forums.whonix.org/t/whonix-upgrade-notification/3284
- More generally, there is no project news mechanism for any project - https://www.whonix.org/wiki/Dev/project-news

> (1) should not attempt to duplicate or generalize the instructions contained in those linked pages, or else we'll end up with the current situation, i.e., incorrect info in (1).

Yes.

**Comment by adrelanos** [comment]
Btw terminology update vs upgrade is broken globally. Reference:
http://forums.whonix.org/t/defining-update-and-upgrade-for-whonix-wiki

Andrew David Wong:
> Does this mean that the [Update](https://www.whonix.org/wiki/Qubes/Update) page is incorrect and needs to be updated?
> 
> I wonder whether we should even have these two separate sets of instructions:

Yes. One is for usual upgrade; two is for release upgrade.

> 1. https://www.whonix.org/wiki/Qubes/Update

Btw do we have similar instructions on how to keep Qubes dom0 and
templates such as Debian, Fedora up to date for Qubes?

> 2. https://www.whonix.org/wiki/Upgrading_Whonix_13_to_Whonix_14

Release upgrade. Similar to https://www.qubes-os.org/doc/upgrade-to-r4.0/.

> Perhaps (1) should contain a list of "Upgrading_Whonix_N_to_Whonix_N+1" links,

Yes, but only
https://www.whonix.org/wiki/Upgrading_Whonix_13_to_Whonix_14 not a list
of them.

(Confusing, not clear if these would still work, not clear if a good
idea to upgrade from let's say 11 -> 12 -> 13 -> 14, not clear how many
users are still on versions older than 13.)

Related tickets and discussions:

- "do not show this message again checkbox" tool needed -
https://phabricator.whonix.org/T865
- Whonix Upgrade Notification needed -
https://forums.whonix.org/t/whonix-upgrade-notification/3284
- More generally, there is no project news mechanism for any project -
https://www.whonix.org/wiki/Dev/project-news

> (1) should not attempt to duplicate or generalize the instructions contained in those linked pages, or else we'll end up with the current situation, i.e., incorrect info in (1).

Yes.

**Comment by adrelanos** [comment]
✘ Outdated: Installed whonix-gateway-packages-dependencies 3.4.2-1 is
outdated!

is now documented on

https://www.whonix.org/wiki/Qubes/Update

**Comment by adrelanos** [comment]
https://www.whonix.org/wiki/Qubes/Install/Testing is not in use currently.

https://www.whonix.org/wiki/Qubes/Install is in use currently.

I wouldn't know what else is to do in this ticket, therefore closing. If you disagree please don't hesitate reopening.
