### ISSUE TITLE
Random freezes and hardware restarts happening only with Qubes

### ISSUE THREAD

**Issue by nailgao** [QubesOS/qubes-issues#4115]
### Qubes OS version:

4.0.

### Affected component(s): 

laptop PC

---

### Steps to reproduce the behavior:

turn on the PC and start a desktop session.

### Expected behavior:

do whatever you want to do, and end it whenever you want to.

### Actual behavior:

random freezes of the computer that require hard shutdown.(not in every single desktop session, and not every day, but happened often enough to take notice of, particularly in the last weeks).
random restarts of the computer (much rarer than freezes)

(both problems had started to happen in 3.2., too, since a while ago)

### General notes:

Of course, Qubes was by no means among my initial suspects at first. I ran tests to detect typical hardware failures on hdd, ram and stability tests, too, each was run somewhere between 8 to 20 hours. all these tests ended with no errors.
Then I ran another OS on the same laptop for 3 days. No freezes, no random restarts.

This makes me ask to myself whether Qubes 4.0. operating system may perhaps have a mismatch with my hardware. 
can you please help?

Thank you in advance!

---

**Comment by andrewdavidwong** [comment]
Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this does not appear to be suitable for `qubes-issues`. We ask that you please send this to the `qubes-users` [mailing list](https://www.qubes-os.org/support/) instead. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a brief comment explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.
