### ISSUE TITLE
qvm-block / qvm-device broken in 4.0 -- no frontend-dev options like doc says

### ISSUE THREAD

**Issue by t4777sd** [QubesOS/qubes-issues#4119]
### Qubes OS version:
4.0
### Affected component(s): 
qvm-block / qvm-device

### Steps to reproduce the behavior:

Run any of the various commands that should be valid and you will see an error:

qvm-block attach --ro --frontend=xtest test-vm dom0:loop1
qvm-device block attach --ro --frontend-dev=xtest test-vm dom0:loop1

For qvm-block you can see the documentation lists valid options: https://www.qubes-os.org/doc/tools/3.2/dom0/qvm-block/

The "frontend" command is not being recognized in 4.0. There is no correspodning documentation for 4.0, so 3.2 documentation is the only available documentation for the 4.0 commands that I could find.

Regarding qvm-device, the latest documentation is here: https://dev.qubes-os.org/projects/core-admin-client/en/latest/manpages/qvm-device.html

frontend-dev is listed as an option, but when it is utilized it fails complaining of unrecognized option

### Expected behavior:

Commands succeed and frontend dev is set accordingly. Or the documentation is updated with the proper way to set the frontend dev

### Actual behavior:

Command fails complaining of unrecognized arguments

**Comment by marmarek** [comment]
In 4.0, it's `-o frontend-dev=...`

**Comment by andrewdavidwong** [comment]
@t4777sd, care to help us [update the documentation](https://www.qubes-os.org/doc/doc-guidelines/)?

**Comment by andrewdavidwong** [comment]
Closing as 4.0 has reached EOL.
