### ISSUE TITLE
a cloned VM does not inherit the selected apps of its source VM

### ISSUE THREAD

**Issue by nailgao** [QubesOS/qubes-issues#4124]
### Qubes OS version:

4.0.

### Affected component(s): 

app VMs

---

### Steps to reproduce the behavior:

clone an existing VM.
check the active (selected) applications list of cloned VM via "Applications" tab in Qubes Manager.

### Expected behavior:

as is familiar from 3.2., the cloned VM has the same "selected apps" list as the source VM.

### Actual behavior:

the "selected apps" list of the cloned VM that is displayed under "Applications" tab of Qubes Manager is empty or showing only the default 1-2 apps, like "Files" or "Terminal".

### General notes:

---

**Comment by marmarta** [comment]
I think this is a problem with app.clone_vm method, calling @marmarek
