### ISSUE TITLE
Qubes Gateway Server / Router LAN host providing external network

### ISSUE THREAD

**Issue by 0pcom** [QubesOS/qubes-issues#4125]
### Qubes OS version:

4.0

### Affected component(s): 

Networking
netVMs
Proxy VMs

---

### Question:

My question is regarding how to 'reverse the direction' of the second sys-net (sys-lan) so that it can host the LAN from the second onboard ethernet port and recieve network from another VM?

The setup would be like this:

internet--->external (home) router--->sys-net--->proxy-VM--->sys-lan--->ethernet switch or router--->client computers

sys-net and sys-lan are assigned eth-0 and eth-1 respectively
the proxy-VM has the VPN

Or you could use just 2 VMs and have the VPN running on sys-net

This is assumed to be possible if your Qubes hardware has 2 onboard (not PCI) Ethernet connections. Each may be assign each a netVM, however; If a VM is set to "provide network" it seems to only work for internal VMs. It would seem for a netVM to be a netvm it does not natively accept a connection from another qube.

Static IPs are just fine for the client connections.
I can insert a router if I really needed DHCP for the LAN

### Application notes:

There just isn't a router (that I own) with enough processing power to give decent bandwidth when using a vpn, and I will have to buy more client connections if I want all my devices to be covered by the VPN without a setup that puts all the network traffic through one computer

**Comment by andrewdavidwong** [comment]
Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this does not appear to be suitable for `qubes-issues`. We ask that you please send this to the `qubes-users` [mailing list](https://www.qubes-os.org/support/) instead. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a brief comment explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.
