### ISSUE TITLE
unstable connection of usb devices

### ISSUE THREAD

**Issue by nailgao** [QubesOS/qubes-issues#4127]
### Qubes OS version:

4.0.

### Affected component(s): 

usb devices
usb widget

---

### Steps to reproduce the behavior:

insert an usb device. 
connect it to a VM via usb widget.

### Expected behavior:

do your work with the usb, and when you're done, eject it via usb widget.

### Actual behavior:

the usb device is disconnected with its respective VM. Sometimes right after you connect it, sometimes 5 minutes later, while you're in the middle of your work with it.
this is not the case in every time you insert a usb device. there are sessions where they properly behave from start to end, too, but the former case is frequent. 

### General notes:

this was a problem known in 3.2., too, with more intensity. 
with 4.0. its persistence and scope seem to have been diminished to allow for some peaceful work with a usb device.

---

**Comment by luserx0** [comment]
Ejecting USB drives through the USB widget is definitely a nice addition to it.
Has reproduction of this been successful?
Ideas on why a usb drive might get "auto-removed" randomly from a vm?
