### ISSUE TITLE
Qubes Manager build error

### ISSUE THREAD

**Issue by thxqua** [QubesOS/qubes-issues#4136]
```
--> Removing old rpms from the installer repos...
---> Cleaning up repo: dom0-updates...
---> Cleaning up repo: installer...
---> Cleaning up repo: qubes-dom0...
--> Copying vmm-xen RPMs...
--> Copying core-libvirt RPMs...
--> Copying core-vchan-xen RPMs...
--> Copying core-qubesdb RPMs...
--> Copying linux-utils RPMs...
--> Copying python-xcffib RPMs...
--> Copying python-sphinx RPMs...
--> Copying python-pillow RPMs...
--> Copying core-admin RPMs...
--> Copying core-admin-client RPMs...
--> Copying core-admin-addon-whonix RPMs...
--> Copying core-admin-linux RPMs...
--> Copying core-agent-linux RPMs...
--> Copying intel-microcode RPMs...
--> Copying linux-firmware RPMs...
--> Copying linux-kernel RPMs...
--> Copying artwork RPMs...
--> Copying gui-common RPMs...
--> Copying gui-daemon RPMs...
--> Copying gui-agent-linux RPMs...
--> Copying gui-agent-xen-hvm-stubdom RPMs...
--> Copying vmm-xen-stubdom-linux RPMs...
--> Copying app-linux-split-gpg RPMs...
--> Copying app-linux-tor RPMs...
--> Copying app-thunderbird RPMs...
--> Copying app-linux-pdf-converter RPMs...
--> Copying app-linux-img-converter RPMs...
--> Copying app-linux-input-proxy RPMs...
--> Copying app-linux-usb-proxy RPMs...
--> Copying app-yubikey RPMs...
--> Copying mgmt-salt RPMs...
--> Copying mgmt-salt-base RPMs...
--> Copying mgmt-salt-base-topd RPMs...
--> Copying mgmt-salt-base-config RPMs...
--> Copying mgmt-salt-base-overrides RPMs...
--> Copying mgmt-salt-dom0-qvm RPMs...
--> Copying mgmt-salt-dom0-virtual-machines RPMs...
--> Copying mgmt-salt-dom0-update RPMs...
--> Copying infrastructure RPMs...
--> Copying meta-packages RPMs...
--> Copying dbus RPMs...
--> Copying manager RPMs...
ln: failed to access 'pkgs/fc25/noarch/qubes-manager-4.0.19-1.fc26.noarch.rpm': No such file or directory
make[1]: *** [/home/user/qubes-builder/qubes-src/builder-rpm/Makefile.rpmbuilder:143: update-repo-do] Error 1
make: *** [Makefile:454: iso.copy-rpms.manager] Error 2
```

**Comment by thxqua** [comment]
# vim: ft=make ts=4 sw=4

# Ready to use config for full build of the latest development version Qubes OS (aka "master").

GIT_BASEURL ?= https://github.com
GIT_PREFIX ?= QubesOS/qubes-
NO_SIGN ?= 1

BACKEND_VMM=xen

DIST_DOM0 ?= fc25
DISTS_VM ?= fc26 fc27 

MGMT_COMPONENTS = \
	mgmt-salt \
	mgmt-salt-base \
	mgmt-salt-base-topd \
	mgmt-salt-base-config \
	mgmt-salt-base-overrides \
	mgmt-salt-dom0-qvm \
	mgmt-salt-dom0-virtual-machines \
	mgmt-salt-dom0-update

COMPONENTS ?= \
    vmm-xen \
    core-libvirt \
    core-vchan-xen \
    core-qubesdb \
    linux-utils \
    python-xcffib \
    python-sphinx \
    python-pillow \
    core-admin \
    core-admin-client \
    core-admin-addon-whonix \
    core-admin-linux \
    core-agent-linux \
    intel-microcode \
    linux-firmware \
    linux-kernel \
    artwork \
    gui-common \
    gui-daemon \
    gui-agent-linux \
    gui-agent-xen-hvm-stubdom \
    vmm-xen-stubdom-linux \
    app-linux-split-gpg \
    app-linux-tor \
    app-thunderbird \
    app-linux-pdf-converter \
    app-linux-img-converter \
    app-linux-input-proxy \
    app-linux-usb-proxy \
    app-yubikey \
    $(MGMT_COMPONENTS) \
    infrastructure \
    meta-packages \
    dbus \
    manager \
    desktop-linux-common \
    desktop-linux-kde \
    desktop-linux-xfce4 \
    desktop-linux-i3 \
    desktop-linux-awesome \
    desktop-linux-manager \
    linux-dom0-updates \
    linux-pvgrub2 \
    linux-gbulb \
    linux-scrypt \
    linux-template-builder \
    installer-qubes-os \
    linux-yum \
    linux-deb \
    vmm-xen-windows-pvdrivers \
    antievilmaid \
    builder \
    builder-rpm

USE_QUBES_REPO_VERSION = 4.0
BUILDER_PLUGINS = builder-rpm
BUILDER_PLUGINS += mgmt-salt

WINDOWS_COMPONENTS = \
                     windows-utils \
                     core-agent-windows \
                     gui-agent-windows \
                     installer-qubes-os-windows-tools \
                     builder-windows

# Uncomment this to enable windows tools build
#DISTS_VM += win7x64
#COMPONENTS += $(WINDOWS_COMPONENTS)
#BUILDER_PLUGINS += builder-windows

BRANCH_vmm_xen = xen-4.8
BRANCH_linux_kernel = stable-4.14

TEMPLATE_ROOT_WITH_PARTITIONS = 1

TEMPLATE_LABEL ?=
TEMPLATE_LABEL += fc20:fedora-20
TEMPLATE_LABEL += fc21:fedora-21
TEMPLATE_LABEL += fc22:fedora-22
TEMPLATE_LABEL += fc23:fedora-23
TEMPLATE_LABEL += fc24:fedora-24
TEMPLATE_LABEL += fc25:fedora-25
TEMPLATE_LABEL += fc26:fedora-26
TEMPLATE_LABEL += fc27:fedora-27

TEMPLATE_ALIAS ?=
TEMPLATE_ALIAS += jessie:jessie+standard
TEMPLATE_ALIAS += jessie+gnome:jessie+gnome+standard
TEMPLATE_ALIAS += jessie+minimal:jessie+minimal+no-recommends
TEMPLATE_ALIAS += stretch:stretch+standard
TEMPLATE_ALIAS += stretch+gnome:stretch+gnome+standard
TEMPLATE_ALIAS += stretch+minimal:stretch+minimal+no-recommends

TEMPLATE_LABEL += fc20+minimal:fedora-20-minimal
TEMPLATE_LABEL += fc21+minimal:fedora-21-minimal
TEMPLATE_LABEL += fc23+minimal:fedora-23-minimal
TEMPLATE_LABEL += fc24+minimal:fedora-24-minimal
TEMPLATE_LABEL += fc25+minimal:fedora-25-minimal
TEMPLATE_LABEL += fc26+minimal:fedora-26-minimal
TEMPLATE_LABEL += fc25+xfce:fedora-25-xfce
TEMPLATE_LABEL += fc26+xfce:fedora-26-xfce
TEMPLATE_LABEL += wheezy:debian-7
TEMPLATE_LABEL += wheezy+standard:debian-7
TEMPLATE_LABEL += jessie:debian-8
TEMPLATE_LABEL += jessie+standard:debian-8
TEMPLATE_LABEL += stretch:debian-9
TEMPLATE_LABEL += stretch+standard:debian-9
TEMPLATE_LABEL += centos7:centos-7
TEMPLATE_LABEL += centos7+minimal:centos-7-minimal
TEMPLATE_LABEL += centos7+xfce:centos-7-xfce

# Uncomment this lines to enable CentOS template build
#DISTS_VM += centos7

# Uncomment this lines to enable Whonix template build
#DISTS_VM += whonix-gateway whonix-workstation
COMPONENTS += template-whonix
BUILDER_PLUGINS += template-whonix
GIT_URL_template_whonix = $(GIT_BASEURL)/marmarek/qubes-template-whonix.git

# Uncomment this lines to enable Debian 9 template build
DISTS_VM += stretch
COMPONENTS += builder-debian
BUILDER_PLUGINS += builder-debian

# Uncomment this line to enable Archlinux template build
#DISTS_VM += archlinux
#COMPONENTS += builder-archlinux
#BUILDER_PLUGINS += builder-archlinux

about::
	@echo "qubes-os-master.conf"



My builder.conf

**Comment by marmarek** [comment]
In the meantime I've pushed new qubes-manager. So you need to build it (make manager).

**Comment by andrewdavidwong** [comment]
@thxqua, wrap your logs in triple backticks (```).

**Comment by andrewdavidwong** [comment]
@thxqua, use more descriptive titles.

**Comment by CybaPunk** [comment]
also running into

make[1]: Entering directory '/home/Cybapunk/qubes-builder'
cp: cannot create hard link '/home/Cybapunk/qubes-builder/chroot-dom0-fc32//home/user/qubes-src/vmm-xen/pkgs/dom0-fc32/xen.spec.list' to 'qubes-src/vmm-xen/pkgs/dom0-fc32/xen.spec.list': Operation not permitted
make[1]: *** [Makefile.generic:130: generic-copy-in] Error 1

**Comment by marmarek** [comment]
@CybaPunk this looks like a different issue. Anyway, what distro you use? This looks like some hardening mechanism (grsec? SELinux?) preventing hardlink creation.

**Comment by CybaPunk** [comment]
Fedora 33

**Comment by CybaPunk** [comment]
@marmarek your right it was a hardening issue i was able to fix this by doing `sudo setenforce 0`

**Comment by CybaPunk** [comment]
@marmarek Also secondary question, how would i configure qubes to come bundled with Nvidia drivers, my RTX 3080 is my only gpu as i run a 16 Core Processor with no intergrated display adapter

**Comment by fepitre** [comment]
> a

This is offtopic. Please check our lists and discourse forum. It's a recurrent question with issues for which NVIDIA drivers does not work (correctly) with Xen.

**Comment by CybaPunk** [comment]
Thanks, I'll check it out.
