### ISSUE TITLE
Feature request: Application shortcut folders in the "start menu" of dom0

### ISSUE THREAD

**Issue by MartynasJanonis** [QubesOS/qubes-issues#4137]
I believe that having the ability to put application shortcuts in folders would be a big usability improvement. If a user has a VM with a lot of applications and wants to have all of them listed, it becomes a hassle to scroll down the huge list and find the program they are looking for.

![E.g. 1](https://user-images.githubusercontent.com/32335421/43141752-3d0551d4-8f46-11e8-8058-d72dc0c7d7c8.png)

Maybe we could right-click and select "Create a folder" and then drag-and-drop the AppVM shortcuts to it. Then those folders would show up in the start menu.

![E.g. 2](https://www.qubes-os.org/attachment/wiki/ManagingAppVmShortcuts/dom0-menu.png)

Or you could have "Create a folder" above or below the "Add more shortcuts..." entry

This would make it easier to organize the applications in your AppVM.

**Comment by andrewdavidwong** [comment]
I'm pretty sure this either:

- Is already possible (check your DE's docs)

or

- Should be an upstream feature request to your DE

Closing on that basis, but if you still think this is Qubes-specific for some reason, let me know.
