### ISSUE TITLE
upgrading of qubes-kernel-vm-support.x86_64 4.0.20-1.fc27 failed

### ISSUE THREAD

**Issue by akkuladezeit** [QubesOS/qubes-issues#4138]
### Qubes OS version: R4.0 testing

during update process upgrading of qubes-kernel-vm-support.x86_64 4.0.20-1.fc27 failed
```
Running scriptlet: qubes-kernel-vm-support-4.0.19-1.fc27.x86_64                                         47/64 
Error! There are no instances of module: u2mfn
4.0.19 located in the DKMS tree.
error: %preun(qubes-kernel-vm-support-4.0.19-1.fc27.x86_64) scriptlet failed, exit status 3
Error in PREUN scriptlet in rpm package qubes-kernel-vm-support
Error in PREUN scriptlet in rpm package qubes-kernel-vm-support
  Cleanup          : qubes-core-agent-passwordless-root-4.0.31-1.fc27.x86_64                              48/64 
error: qubes-kernel-vm-support-4.0.19-1.fc27.x86_64: erase failed
```

**Comment by zeb-stephen-downs** [comment]
@andrewdavidwong @akkuladezeit this is happening with version 20 to 21 update as well; erroring on the same module. I fixed it on two of my vms by doing this:

`sudo rpm -e --noscripts qubes-kernel-vm-support-4.0.20-1.fc28.x86_64
sudo rpm -e --noscripts qubes-kernel-vm-support-4.0.21-1.fc28.x86_64
sudo dnf install qubes-kernel-vm-support`

It should then prompt to install 21; you can then check it with `sudo dnf info qubes-kernel-vm-support` to verify that it only has one installed then.

**Comment by marmarek** [comment]
I think this is a case of https://github.com/dell/dkms/issues/25 - may be triggered by reinstalling the same package (dnf may want to do that in some rare cases), then each update would manifest this problem, until fixed with the procedure above.

As this is rather rare problem and we're dropping u2mfn module (#4280), I'm closing this one too.
