### ISSUE TITLE
Clarify instructions for assigning devices

### ISSUE THREAD

**Issue by ghost** [QubesOS/qubes-issues#4143]
This is not a major issue, but two lines of text would add a lot of clarity to this piece of documentation. In this exact paragraph I don't understand what exactly I should type, everything that comes after `0000:`? including `/usb3` text or not? To avoid all this, adding two examples would make everything clearer. Thank you.

https://www.qubes-os.org/doc/assigning-devices/ 

### Approximately expected documentation:

> This should output something like:
> 
> `../../../devices/pci-0/pci0000:00/0000:00:1a.0/usb3`
> 
> Now you see the BDF address in the path (right before final `usb3`). Strip the leading `0000:` and pass the rest to the `qvm-pci` tool to attach the controller with the version specific steps above.
>
> On R 4.0 the command would look something like
> `qvm-pci attach --persistent personal dom0:00:1a.0/usb3`
>
> On R 3.2 the command would look something like
> `qvm-pci -a personal 00:1a.0/usb3`

### Actual documentation:

> This should output something like:
> 
> `../../../devices/pci-0/pci0000:00/0000:00:1a.0/usb3`
> 
> Now you see the BDF address in the path (right before final `usb3`). Strip the leading `0000:` and pass the rest to the `qvm-pci` tool to attach the controller with the version specific steps above.

p.s. I'm not sure if what comes after `dom0` in this example `qvm-pci attach --persistent personal dom0:00:1a.0/usb3` is correct, since I haven't figured out what exactly I should copy from here `../../../devices/pci-0/pci0000:00/0000:00:1a.0/usb3` to make the command work properly.

**Comment by t4777sd** [comment]
You can click "Edit this page" on the doc page to change the documentation

**Comment by Zig-03** [comment]
@t4777sd thanks, never done that. I'll try.

**Comment by sarru1291** [comment]
The above link mentioned in this issue redirects to a PCI device attachment page that no longer contains the reported misleading paragraph.  However, the para belongs to a USB device [here](https://www.qubes-os.org/doc/usb-devices/).

Hence, check this corrected text so that I can make a PR.

> This should output something like:  

`../../../devices/pci-0/pci0000:00/0000:00:1a.0/usb3`

> Now you see the path and the text between `/pci0000:00/0000:` and `/usb3` i.e. `00:1a.0` is the BDF address. Strip the address and pass it to the `qvm-pci` tool to attach the controller to the targetVM.
For example, On R 4.0 the command would look something like

`qvm-pci attach --persistent personal dom0:00:1a.0`

>On R 3.2 the command would look something like

`qvm-pci -a personal 00:1a.0`

**Comment by andrewdavidwong** [comment]
There is no longer any need to include documentation about R3.2, since that release has long since reached EOL and been removed from the live documentation.

Other than that, the technical content will probably have to be reviewed as a PR.
