### ISSUE TITLE
No application shortcuts after installing Xenial template

### ISSUE THREAD

**Issue by unman** [QubesOS/qubes-issues#4146]
### Qubes OS version:

R4.0

### Affected component(s): 

Xenial Template

---

### Steps to reproduce the behavior:

Build and install Xenial template

### Expected behavior:

Application shortcuts populated in menu and available applications pane

### Actual behavior:

No shortcuts appear

### General notes:

Manually starting the template after installation and running qvm-sync-appmenus, fixes the issue

---

**Comment by marmarek** [comment]
See template logs from the installation time (inside of the VM), specifically related to qubes.PostInstall service. Also see if you didn't get any errors on dom0 console during template installation.

Anyway, I think that it would be you to debug such problems, as you are Debian/Ubuntu templates maintainer ;)

**Comment by unman** [comment]
Yes indeed. 
I just wanted to capture this to cross ref in PR - it's a PostInstall error and actually affects all latest Ubuntu variants.

**Comment by unman** [comment]
I can no longer reproduce this - at some point to date it has been fixed.
menu items correctly appear in Xfce menu for Ubuntu variants
