### ISSUE TITLE
Idea: qvm-sync-appmenus also parsing /usr/local/share/applications

### ISSUE THREAD

**Issue by t4777sd** [QubesOS/qubes-issues#4152]
### Qubes OS version:
4.0

### Affected component(s): 
Application menu syncing

### Steps to reproduce the behavior:
1. Install any locally installed app that a user may want in a particular VM, but not other VMs and they do not want to make it installed in all VMs and make a bunch of clones of VMs (as that creates its own problems)

2. Desktop file will be placed in /usr/local/share/applications

3. Sync the app menu and you will see it does not detect the apps

### Expected behavior:
It would be nice if desktop files also looked in /usr/local/share/applications. This provides a mechanism to install software locally without making a lot of template clones.

I understand why ~./.local/share/applications is excluded because it appears some apps install to both that and /usr/share/applications so that would require trying to parse out duplicates etc.

However, no packaged apps install into /usr/local/share/applications and that folder is local to the AppVM too.

### Motivation for locally installed apps

The primary motivation is because a single change does not warrant a template clone as that creates a bunch of other issues (resource issues, menu cluttering issues, etc).

1. The appvm wants to run a different version of software than those in other appvms

2. The application is less trusted so better to keep it entirely contained in the appvm

3. The software only belongs in one appvm and its not efficient to create a new template just because of that one software

4. The software is downloaded from the internet, only belongs in oen appvm, and it makes little since to transfer it to the templatevm (as that has no internet to download it) when it can just be kept in that appvm which is the only place it should run.

**Comment by marmarek** [comment]
> I understand why ~./.local/share/applications is excluded because it appears some apps install to both that and /usr/share/applications so that would require trying to parse out duplicates etc.

Actually handling duplicates shouldn't be a problem - the current code should do that well.

As for the general idea, I like it and in fact it shouldn't be that hard to implement. Mostly dom0 part of qvm-sync-appmenus (and actual .desktop files generating code) consider multiple template directories: one for template and in addition one for VM-private applications. The code lives here:
https://github.com/QubesOS/qubes-desktop-linux-common/tree/master/qubesappmenus

**Comment by andrewdavidwong** [comment]
Why isn't this a use case for [bind-dirs](https://www.qubes-os.org/doc/bind-dirs/)?

**Comment by t4777sd** [comment]
Do you mean make /usr/share/applications? The issue with that is then it would no longer update when the TemplateVM installs new software.

**Comment by marmarek** [comment]
Exactly as @t4777sd said. Plus, dom0 right now downloads application list only from TemplateVMs (and StandaloneVMs). It would be fine for substituting existing desktop files, but not for adding new ones.

**Comment by andrewdavidwong** [comment]
Ok, but what about symlinking or copying the needed files at VM startup with `/rw/config/rc.local`?

**Comment by t4777sd** [comment]
Another related issue to this one is that icons are not read when they exists on the private storage. As a result, it receives a default padlock icon. Maybe or maybe not related to this, but in the default install nautilus does not have an icon image. My guess is that it is related.
