### ISSUE TITLE
add missing Whonix tags anon-vm / anon-gateway to user created Whonix based VMs

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#4155]
```
    @qubes.ext.handler('domain-load')
    def on_domain_load(self, vm, _event):
        '''Retroactively add tags to sys-whonix and anon-whonix'''
        # pylint: disable=no-self-use
        if vm.name == 'sys-whonix' and 'anon-gateway' not in vm.tags:
            vm.tags.add('anon-gateway')
        if vm.name == 'anon-whonix' and 'anon-vm' not in vm.tags:
            vm.tags.add('anon-vm')
```

It's very good to have but VM names are hardcoded unfortunately. Can this be made generic?

Rather than `if vm.name == 'anon-whonix'` is it somehow possible to say `if the TemplateVM which this VM is based on has 'whonix-gw' in untrusted_features`?

(When is this missing tag scenario likely to happen? For users who created whonix-ws based VMs with Whonix 13 and then [upgraded](https://www.whonix.org/wiki/Upgrading_Whonix_13_to_Whonix_14) to Whonix 14.)

**Comment by marmarek** [comment]
> Then started anon-whonix-test (based on whonix-ws-14).

`domain-load` event is about loading VM metadata from disk, not starting the VM. Basically qubesd service startup. So, instead of starting the VM, restart qubesd service.

**Comment by adrelanos** [comment]
Closeable.
