### ISSUE TITLE
ISO BUILD error Qubes R3.2 

### ISSUE THREAD

**Issue by thxqua** [QubesOS/qubes-issues#4157]
Qubes R3.2

### Affected component(s): 
Building ISO from scratch

---

### Steps to reproduce the behavior:
Succesfully build iso

### General notes:
[user@f2 qubes-builder]$ make qubes
Currently installed dependencies:
git-2.13.6-3.fc26.x86_64
rpmdevtools-8.10-2.fc26.noarch
rpm-build-4.13.1-1.fc26.x86_64
createrepo-0.10.3-11.fc26.noarch
python2-sh-1.12.14-1.fc26.noarch
wget-1.19.5-1.fc26.x86_64
PyYAML-3.12-3.fc26.x86_64
dpkg-dev-1.18.24-1.fc26.noarch
debootstrap-1.0.97-1.fc26.noarch
dpkg-dev-1.18.24-1.fc26.noarch
debootstrap-1.0.97-1.fc26.noarch
make[1]: Entering directory '/home/user/qubes-builder'
/home/user/qubes-builder/scripts/create-archive /home/user/qubes-builder/chroot-fc25//home/user/qubes-src/vmm-xen/gui-agent-xen-hvm-stubdom gui-agent-xen-hvm-stubdom-5f57a59.tar.gz gui-agent-xen-hvm-stubdom/
~/qubes-builder/chroot-fc25/home/user/qubes-src/vmm-xen/gui-agent-xen-hvm-stubdom ~/qubes-builder
~/qubes-builder
mv /home/user/qubes-builder/chroot-fc25//home/user/qubes-src/vmm-xen/gui-agent-xen-hvm-stubdom/gui-agent-xen-hvm-stubdom-5f57a59.tar.gz /home/user/qubes-builder/chroot-fc25//home/user/qubes-src/vmm-xen
sed -i "s#@gui-agent-xen-hvm-stubdom@#gui-agent-xen-hvm-stubdom-5f57a59.tar.gz#" /home/user/qubes-builder/chroot-fc25//home/user/qubes-src/vmm-xen/xen.spec.in
/home/user/qubes-builder/scripts/create-archive /home/user/qubes-builder/chroot-fc25//home/user/qubes-src/vmm-xen/core-vchan-xen core-vchan-xen-42d07fb.tar.gz core-vchan-xen/
~/qubes-builder/chroot-fc25/home/user/qubes-src/vmm-xen/core-vchan-xen ~/qubes-builder
~/qubes-builder
mv /home/user/qubes-builder/chroot-fc25//home/user/qubes-src/vmm-xen/core-vchan-xen/core-vchan-xen-42d07fb.tar.gz /home/user/qubes-builder/chroot-fc25//home/user/qubes-src/vmm-xen
sed -i "s#@core-vchan-xen@#core-vchan-xen-42d07fb.tar.gz#" /home/user/qubes-builder/chroot-fc25//home/user/qubes-src/vmm-xen/xen.spec.in
/home/user/qubes-builder/scripts/create-archive /home/user/qubes-builder/chroot-fc25//home/user/qubes-src/vmm-xen/stubdom-dhcp stubdom-dhcp-53ea5b3.tar.gz stubdom-dhcp/
~/qubes-builder/chroot-fc25/home/user/qubes-src/vmm-xen/stubdom-dhcp ~/qubes-builder
~/qubes-builder
mv /home/user/qubes-builder/chroot-fc25//home/user/qubes-src/vmm-xen/stubdom-dhcp/stubdom-dhcp-53ea5b3.tar.gz /home/user/qubes-builder/chroot-fc25//home/user/qubes-src/vmm-xen
sed -i "s#@stubdom-dhcp@#stubdom-dhcp-53ea5b3.tar.gz#" /home/user/qubes-builder/chroot-fc25//home/user/qubes-src/vmm-xen/xen.spec.in
/home/user/qubes-builder/scripts/create-archive /home/user/qubes-builder/chroot-fc25//home/user/qubes-src/vmm-xen/gui-common gui-common-c611481.tar.gz gui-common/
~/qubes-builder/chroot-fc25/home/user/qubes-src/vmm-xen/gui-common ~/qubes-builder
~/qubes-builder
mv /home/user/qubes-builder/chroot-fc25//home/user/qubes-src/vmm-xen/gui-common/gui-common-c611481.tar.gz /home/user/qubes-builder/chroot-fc25//home/user/qubes-src/vmm-xen
sed -i "s#@gui-common@#gui-common-c611481.tar.gz#" /home/user/qubes-builder/chroot-fc25//home/user/qubes-src/vmm-xen/xen.spec.in
-> Building vmm-xen (xen.spec) for fc25 dom0 (logfile: build-logs/vmm-xen-dom0-fc25.log)
--> build failed!
make[2]: Entering directory '/home/user/qubes-builder'
/home/user/qubes-builder/qubes-src/builder-rpm//update-local-repo.sh fc25
sudo BACKEND_VMM=xen  chroot /home/user/qubes-builder/chroot-fc25 sh -c 'cd /home/user/qubes-src/vmm-xen; dnf  --refresh -y update'
Dependencies resolved.
Nothing to do.
Complete!
Failed to set locale, defaulting to C
/home/user/qubes-builder/qubes-src/builder-rpm/scripts/generate-spec /home/user/qubes-builder/chroot-fc25/home/user/qubes-src/vmm-xen/xen.spec.in /home/user/qubes-builder/chroot-fc25/home/user/qubes-src/vmm-xen/xen.spec
sudo BACKEND_VMM=xen  chroot /home/user/qubes-builder/chroot-fc25 sh -c 'cd /home/user/qubes-src/vmm-xen; dnf builddep --allowerasing --best  -y xen.spec'
Last metadata expiration check: 0:00:01 ago on Sat Jul 28 10:56:03 2018.
Failed to set locale, defaulting to C
No matching package to install: 'gcc >= 6.4.1-1.qubes1'
Package gettext-0.19.8.1-3.fc25.x86_64 is already installed, skipping.
Package perl-4:5.24.3-389.fc25.x86_64 is already installed, skipping.
Package perl-podlators-4.09-1.fc25.noarch is already installed, skipping.
Package perl-podlators-4.09-1.fc25.noarch is already installed, skipping.
Package systemd-231-19.fc25.x86_64 is already installed, skipping.
Package systemd-udev-231-19.fc25.x86_64 is already installed, skipping.
Not all dependencies satisfied
Error: Some packages could not be found.
make[2]: *** [/home/user/qubes-builder/qubes-src/builder-rpm/Makefile-legacy.rpmbuilder:57: dist-build-dep] Error 1
make[2]: Leaving directory '/home/user/qubes-builder'
make[1]: *** [Makefile.generic:177: packages] Error 1
make[1]: Leaving directory '/home/user/qubes-builder'
make: *** [Makefile:228: vmm-xen-dom0] Error 1

**Comment by thxqua** [comment]
Make install-deps
Make get-sources
Make qubes
Make iso 

What i did worng ?
[builder.txt](https://github.com/QubesOS/qubes-issues/files/2237913/builder.txt)

**Comment by thxqua** [comment]
Nobody?

**Comment by andrewdavidwong** [comment]
Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this does not appear to be suitable for `qubes-issues`. We ask that you please send this to the `qubes-users` [mailing list](https://www.qubes-os.org/support/) instead. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a brief comment explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.
