### ISSUE TITLE
Encryption vm (And how strong is the disk encryption)

### ISSUE THREAD

**Issue by thxqua** [QubesOS/qubes-issues#4172]
### Qubes OS version:
Qubes R.40

### Affected component(s): 

HI, sorry i dont know where to ask this question, so i am sorry about that. But i want to know how strong the disk encryption is from Qubes R.4.0

And how to encrypt also vm's is this possible ?

**Comment by MartynasJanonis** [comment]
This is definitely not the place to ask.
Read through this: https://www.qubes-os.org/faq/
https://en.wikipedia.org/wiki/Dm-crypt
https://en.wikipedia.org/wiki/Linux_Unified_Key_Setup

And close the issue, considering it's not really an issue.

**Comment by andrewdavidwong** [comment]
Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this does not appear to be suitable for `qubes-issues`. We ask that you please send this to the `qubes-users` [mailing list](https://www.qubes-os.org/support/) instead. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a brief comment explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.
