### ISSUE TITLE
Cannot pass Trezor device via qubes-usb-proxy

### ISSUE THREAD

**Issue by pruflyos** [QubesOS/qubes-issues#4173]
### Qubes OS version:

R4.0

### Affected component(s): 

qubes-usb-proxy
trezord

---

### Steps to reproduce the behavior:

Try to passthrough an **USB 3.0** device, specifically the `Trezor Model T` from `sys-usb` to any App VM.

### Expected behavior:

Device working and no dmesg errors.

### Actual behavior:

```
[ 2517.644162] usb 1-1: SetAddress Request (34) to port 0
[ 2517.667220] usb 1-1: New USB device found, idVendor=1209, idProduct=53c1
[ 2517.667287] usb 1-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 2517.667329] usb 1-1: Product: TREZOR
[ 2517.667353] usb 1-1: Manufacturer: SatoshiLabs
[ 2517.667395] usb 1-1: SerialNumber: XXXXXXXXXXXXXXXXXXXXXXXX
[ 2517.682497] hid-generic 0003:1209:53C1.000C: hiddev96,hidraw0: USB HID v1.11 Device [SatoshiLabs TREZOR] on usb-vhci_hcd.0-1/input1
[ 2525.985061] vhci_hcd: vhci_device speed not set
[ 2526.191132] vhci_hcd: vhci_device speed not set
[ 2526.399124] vhci_hcd: vhci_device speed not set
[ 2526.607101] vhci_hcd: vhci_device speed not set
[ 2526.815132] vhci_hcd: vhci_device speed not set
[ 2526.815208] usb usb1-port1: Cannot enable. Maybe the USB cable is bad?
...
[ 2533.351197] usb usb1-port1: Cannot enable. Maybe the USB cable is bad?
[ 2533.351274] usb usb1-port1: unable to enumerate USB device
```

### General notes:

Any thoughts if this could be a general issue with **USB 3.0** devices and `qubes-usb-proxy` or a specific issue with the `Trezor Model T` only? The device works fine on other operating systems (e.g. Ubuntu 16.04 and 18.04).
The `Trezor One` which is a **USB 2.0** device works fine on Qubes 4.0 though.

---

### Related issues:

See the following discussion in the `trezord` project:
https://github.com/trezor/trezord-go/issues/59

**Comment by marmarek** [comment]
USB3.0 devices should work with kernel >= 4.13 (both sys-usb and target AppVM). But the problem with trezor is probably unrelated to being USB3.0 (as you can see in linked ticket). See https://github.com/trezor/trezor-core/issues/167#issuecomment-386796999 for workaround for Trezor Model T problem.

**Comment by andrewdavidwong** [comment]
Closing as "not our bug." If you believe this is a mistake, please leave a comment, and we'll be happy to take another look. Thank you.

**Comment by slush0** [comment]
I think the problem lies somewhere in Qubes OS. Btw, Model T uses WebUSB, not HID for application protocol, that's why you see only one HID (it is for U2F).

At least, we are not aware of any issue on our side. Trezor Model T is standard WebUSB token and works seamlessly across any platforms, except Qubes (I use Qubes 3.2 myself). If you see any unusual/non-standard behavior on Trezor side, just let us know.

**Comment by andrewdavidwong** [comment]
Thanks, @ThomasWaldmann. Issue title updated.

**Comment by xaki23** [comment]
this looks like https://github.com/QubesOS/qubes-issues/issues/3778

https://github.com/trezor/trezord-go/blob/e0f400d59a04280cfbc8a3a9802af968ecacd902/trezord.go#L112

perhaps someone with such a device could try if it works with reset disabled...
