### ISSUE TITLE
document DVM Template / DisposableVM - Inheritance and Persistence

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#4175]
What does a DVM Template inherit upon creation? I guess `/etc/skel` to `/home`?

Which mount points do persist in a DVM Template after shutdown? I guess `/rw` and bind-dirs?

Does a DisposableVM really only inherit `/home` or all of `/rw` (including `/home`, `/usr/local`, `/rw/config`)? I guess it inherits all of `/rw`?

What about bind-dirs in DVM Template?

What about bind-dirs in DisposableVM? I guess those won't make things persistent either way?

----

* https://www.qubes-os.org/doc/templates/#important-notes-r40
* https://www.whonix.org/wiki/Template:Qubes_persistence

**Comment by rustybird** [comment]
Unless I'm missing something, an R4.0 "template for DispVMs" (named something-dvm if you follow that naming convention) is just a regular AppVM with the `template_for_dispvms` pref enabled. So there's nothing special to document, it works exactly the same as any AppVM when you start it as something-dvm, including persistence.

When you instantiate an actual DispVM from something-dvm, it will still look like a regular AppVM from the inside (with `qubesdb-read /qubes-vm-persistence` even returning `rw-only` as you pointed out in #4007).

> Does a DisposableVM really only inherit /home or all of /rw

The latter. A DispVM is started with a snapshot of the private volume of its template (e.g. `fedora-28-dvm:private`) - which hosts `/rw`. And with a snapshot of the root volume of its template's template (e.g. `fedora-28:root`).

> What about bind-dirs in DisposableVM? I guess those won't make things persistent either way?

Right.

**Comment by adrelanos** [comment]
Does https://www.whonix.org/wiki/Template:Qubes_persistence look good now?

**Comment by rustybird** [comment]
> Does https://www.whonix.org/wiki/Template:Qubes_persistence look good now?

It does to me. There's also /usr/local.orig -> /usr/local (for TemplateBasedVM and DVM Template inheritance), but they're just some trivial empty directories.

**Comment by adrelanos** [comment]
Closeable?

**Comment by andrewdavidwong** [comment]
> Closeable?

It really depends on whose opinion we want. Given the current state of things, I think it's fine to close this for now and reopen it if we discover later that the docs need to be updated.
