### ISSUE TITLE
whonix ws/gw 14 not in qubes stable repository

### ISSUE THREAD

**Issue by TNTBOMBOM** [QubesOS/qubes-issues#4176]
### Qubes OS version:

R.4

### Affected component(s): 

qubes-dom0-updates, qubes stable repo doesnt contain whonix-gw/ws-14 

---

### Steps to reproduce the behavior:

`sudo qubes-dom0-update qubes-template-whonix-gw-14`

doesnt install a thing.

### Expected behavior:

`sudo qubes-dom0-update qubes-template-whonix-gw-14`

to have whonix-gw-14 template to be downloaded/installed

### General notes:

better to have good mechanism for template availability checkup , otherwise maybe updated templates will be missed and most of the users will not recognize that leading to dangerous results. 

---

**Comment by marmarek** [comment]
Have you enabled templates-community repository? It works for me...
Template status you can check in relevant updates-status issue - see labels and automatic comments:
https://github.com/QubesOS/updates-status/issues/597
https://github.com/QubesOS/updates-status/issues/595
Maybe you have old metadata (try adding --refresh).

**Comment by adrelanos** [comment]
User error here:
https://www.whonix.org/wiki/Qubes/Install/Testing#Download_the_Whonix_Templates says "R3.2 only". This report is for R4.

Documentation error:
I should have added `--enablerepo=qubes-templates-community`. Now fixed.

Closable.
