### ISSUE TITLE
pulseaudio-qubes needs a rebuild now that Fedora 27 has pushed PulseAudio 12.2 to stable

### ISSUE THREAD

**Issue by mattmccutchen** [QubesOS/qubes-issues#4180]
As reported in [this comment](https://github.com/QubesOS/qubes-issues/issues/4072#issuecomment-409992901), pulseaudio-qubes needs another rebuild now that Fedora 27 has pushed PulseAudio 12.2 to stable. :frowning_face: :frowning_face: :frowning_face:

**Comment by marmarek** [comment]
https://github.com/QubesOS/updates-status/issues/630
https://github.com/QubesOS/updates-status/issues/629
