### ISSUE TITLE
Confirmation auto-accepts errant "enters" as acceptance

### ISSUE THREAD

**Issue by t4777sd** [QubesOS/qubes-issues#4185]
### Qubes OS version:
4.0

### Affected component(s): 
The GPG tool and potentially others have a security prompt that asks you something like: "are you sure you want [domain] to access your GPG keys (now and for the following 300 seconds)"

This prompt is presented with two options: [No] [Yes]

The issue is that this prompt may display while someone is typing on the keyboard. And, if someone hits enter while the prompt comes up it will automatically default to Yes.

It could even be a malware that listens while a user types and while they are typing initiate the action that causes that prompt to be initialized in dom0.

### Steps to reproduce the behavior:
1. Call the qubes-gpg-client program so that the prompt comes up
2. Hit enter

### Expected behavior:
By default the answer selected should be "No" unless someone tabs over to yes or clicks yes explicitly with the mouse.

### Actual behavior:
It will take any "Enter" key input as a "Yes" answer which may mean people say even when they do not want to.

**Comment by jsmaniac** [comment]
Confirmation windows now have a delay before clicking "Yes" or pressing Enter works. Since it partially solves this issue, should it be closed?

**Comment by andrewdavidwong** [comment]
Closing this as "resolved." If you believe the issue is not yet resolved, or if anyone is still affected by this issue, please leave a comment, and we'll be happy to reopen this. Thank you.
