### ISSUE TITLE
qubes-usb-proxy for Ubuntu template

### ISSUE THREAD

**Issue by pruflyos** [QubesOS/qubes-issues#4187]
### Qubes OS version:

R4.0

### Affected component(s): 

qubes-usb-proxy

---

### Steps to reproduce the behavior:

Build Ubuntu (xenial) template using `qubes-builder` and install in `dom0`.

### Expected behavior:

`qubes-usb-proxy` is installed or available for Ubuntu template.

### Actual behavior:

Attaching usb devices to Ubuntu AppVMs fails.
`qubes-usb-proxy` is missing in Ubuntu template and no documentation available how to install or compile + install it for Ubuntu.

### General notes:

---

**Comment by unman** [comment]
@pruflyos If you built the template then you have already built the qubes-usb-proxy package. (It will be in <build_directory/qubes-packages-mirror-repo/xenial/deb)
Copy the deb from your build qube to the Ubuntu template and install it there.
I dont think that qubes-usb-proxy is installed by default in any templates.

**Comment by andrewdavidwong** [comment]
Closing as "not an issue." If you believe this is a mistake, please leave a comment, and we'll be happy to take another look. Thank you.

**Comment by pruflyos** [comment]
@unman Thanks for the hint! I copied the whole mirror directory to the template vm and added it as a local repository via:

sudo vim /etc/apt/sources.list.d/qubesos.list
```
deb [trusted=true] file:/opt/qubes-packages-mirror-repo/xenial xenial main
```

And installed `qubes-usb-proxy` via `apt-get` in the template VM. However, I still can't attach any USB device from sys-usb to any xenial AppVM based on that template. I run into the same problem as described by another user here:
https://groups.google.com/forum/#!topic/qubes-users/uTY32_cvc1I

in dom0:
```
$ qvm-usb --verbose a ubuntutest sys-usb:2-2
Device attach failed:
```

No additional errors / details are given. Can't find anything in the logs either...

**Comment by andrewdavidwong** [comment]
> I run into the same problem as described by another user here:
> https://groups.google.com/forum/#!topic/qubes-users/uTY32_cvc1I

That user marked the issue as resolved in response to this message:

https://groups.google.com/d/msg/qubes-users/uTY32_cvc1I/82YehobNBgAJ

Please try what is described in that message.
