### ISSUE TITLE
Qube Manager does not show the correct kernel opts.

### ISSUE THREAD

**Issue by qubenix** [QubesOS/qubes-issues#4188]
### Qubes OS version:

R4.0

### Affected component(s): 

Qube Manger

---

### Steps to reproduce the behavior:

Go to Advanced tab of Qube Manger, it always shows `Kernel opts: [ ]`. Even when `qvm-prefs -g vm-name kernelopts` shows that there are options.

### Expected behavior:

Qube Manager shows the correct kernel opts.

### Actual behavior:

Qube Manager always shows that there are no kernel opts.

### General notes:

---

**Comment by lunarthegrey** [comment]
I can confirm this is an issue on 4.0. When checking kernelopts in the Qube Manager it shows [  ]

`qvm-prefs --get vmname kernelopts` returns the correct information.

**Comment by esote** [comment]
I also have this. I noticed it when enabling AppArmor after upgrading to Whonix 14.

**Comment by constantoverride** [comment]
cool but, that's a huge window :)
![bigwindowscreenshot_2019-01-05_20-17-13](https://user-images.githubusercontent.com/40925413/50728244-095d0a80-1127-11e9-9e02-a93b34c42eef.png)

**Comment by andrewdavidwong** [comment]
> cool but, that's a huge window :)

Technically this should be reported as a separate issue, but perhaps @marmarta just wants to commit a quick fix for this.
