### ISSUE TITLE
Announce Whonix 14 release on Qubes website

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#4193]
https://groups.google.com/forum/#!forum/qubes-announce

https://groups.google.com/forum/#!topic/qubes-users/5mBXxQ_LSvg

**Comment by andrewdavidwong** [comment]
`qubes-announce` is [only for QSBs and new Qubes OS releases](https://www.qubes-os.org/support/#qubes-announce). However, we can certainly announce it on the Qubes website, and I'd be happy to do so! (I also see that you've already announced it on the qubes-devel and qubes-users. Thanks!)

**Comment by andrewdavidwong** [comment]
(Updated title)

**Comment by lunarthegrey** [comment]
Would be nice to know how to properly install the latest Whonix version. Plans for a new template maybe?

**Comment by andrewdavidwong** [comment]
> Would be nice to know how to properly install the latest Whonix version. Plans for a new template maybe?

This is already answered in Patrick's announcement. See link above.

**Comment by adrelanos** [comment]
Lunar:
> Would be nice to know how to properly install the latest Whonix version. Plans for a new template maybe?
> 

I won't release a stable Qubes-Whonix announcement without accompanying
new stable Qubes-Whonix template.

In other words: there is a new template.

https://www.whonix.org/wiki/Qubes/Install

**Comment by h01ger** [comment]
On Tue, Aug 07, 2018 at 09:46:55PM -0700, Patrick Schleizer wrote:
> I won't release a stable Qubes-Whonix announcement without accompanying
> new stable Qubes-Whonix template.
 
nice.

> In other words: there is a new template.
> https://www.whonix.org/wiki/Qubes/Install

I believe that information was missing in the announcement, at least the
link.


-- 
cheers,
	Holger

-------------------------------------------------------------------------------
                    holger@(debian|reproducible-builds).org
