### ISSUE TITLE
Certain characters go missing or get garbled when going through the inter-VM clipboard

### ISSUE THREAD

**Issue by Summertime** [QubesOS/qubes-issues#4194]
### Qubes OS version:

R4.0

### Affected component(s): 

inter-VM clipboard, copy/pasting 

---

### Steps to reproduce the behavior:

1. find a string containing the FULL BLOCK character or others: █
2. copy it, then copy it to the qubes clipboard
3. paste it from the qubes clipboard, paste it

### Expected behavior:

All characters are preserved

### Actual behavior:

some characters come out garbled or missing

### General notes:

The following can be used to create a relevant character
```python
python3 -c 'print("\N{FULL BLOCK}")'
```

The following go missing, unless they are the only thing on the clipboard, then they get garbled
```
U+2580 Upper half block
U+2584 Lower half block
U+2588 Full block
U+258C Left half block
U+2590 Right half block
U+2591 Light shade
U+2593 Dark shade
```
The following request had successful reproductions
Summertime> could someone help me reproduce a bug? does inter-vm copypasting the following: "abc█def" result in the FULL BLOCK character being removed or similar for you?

---

**Comment by marmarek** [comment]
It looks the paste breaks them, on copy they are preserved (you can inspect copied content in dom0 in `/var/run/qubes/qubes-clipboard.bin`).
