### ISSUE TITLE
Archlinux: qubes-mount-dirs fail because of /usr/local not present in fstab

### ISSUE THREAD

**Issue by ptitdoc** [QubesOS/qubes-issues#4196]
### Qubes OS version:

Qubes release 4.0 (R4.0)

### Affected component(s): 

qubes-core-agent-linux (template)

---

### Steps to reproduce the behavior:

1/ Start a template
2/ the service qubes-mount-dirs fails with the following error and does not mounts additional bind-dirs

### Expected behavior:

qubes-mount-dirs starts successfully and mount bind all directories specified in qubes-bind-dirs.d

### Actual behavior:

```
* qubes-mount-dirs.service - Initialize and mount /rw and /home
   Loaded: loaded (/usr/lib/systemd/system/qubes-mount-dirs.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2018-08-08 11:43:58 CEST; 5min ago
  Process: 285 ExecStart=/usr/lib/qubes/init/mount-dirs.sh (code=exited, status=1/FAILURE)
 Main PID: 285 (code=exited, status=1/FAILURE)

Aug 08 11:43:58 archlinux mount-dirs.sh[285]: Checking /rw
Aug 08 11:43:58 archlinux mount-dirs.sh[285]: Private device size management: enlarging /dev/xvdb
Aug 08 11:43:58 archlinux mount-dirs.sh[285]: Private device size management: resize2fs of /dev/xvdb succeeded
Aug 08 11:43:58 archlinux mount-dirs.sh[285]: Finished checking /rw
Aug 08 11:43:58 archlinux mount-dirs.sh[285]: Mounting /rw/home onto /home
Aug 08 11:43:58 archlinux mount-dirs.sh[285]: Mounting /rw/usrlocal onto /usr/local
Aug 08 11:43:58 archlinux mount-dirs.sh[285]: mount: /usr/local: can't find in /etc/fstab.
Aug 08 11:43:58 archlinux systemd[1]: qubes-mount-dirs.service: Main process exited, code=exited, status=1/FAILURE
Aug 08 11:43:58 archlinux systemd[1]: qubes-mount-dirs.service: Failed with result 'exit-code'.
Aug 08 11:43:58 archlinux systemd[1]: Failed to start Initialize and mount /rw and /home.
```

### General notes:

In archlinux, /usr/local is not defined in /etc/fstab by default which cause this error since the pull request.

---

### Related issues:

the regression caused by the following issues/pulls:
https://github.com/QubesOS/qubes-issues/issues/1150
https://github.com/QubesOS/qubes-core-agent-linux/pull/125

**Comment by ptitdoc** [comment]
In fedora, fstab is managed entirely by qubes-core-agent package. However, there are reasons for the user to change fstab (eg: increasing tmpfs size ...). In these case, the user /etc/fstab will be prefered over the package one.

In such case, updating the package will cause such errors.

Maybe it is possible to use systemd.mount units to manage qubes specific mounts/binds instead of fstab ?

**Comment by unman** [comment]
@andrewdavidwong  @ptitdoc 
As a result of changes merged and updated packages, the Arch template for 4.0 builds correctly with no dependency errors.
Please close this issue.
