### ISSUE TITLE
Whonix salt creates new sys-net/sys-firewall instead of using default netVM

### ISSUE THREAD

**Issue by z64z** [QubesOS/qubes-issues#4198]
### Qubes OS version:

R4.0

### Affected component(s): 

Whonix-14 salt formula(s):

`sudo qubesctl state.sls qvm.anon-whonix`

---

### Steps to reproduce the behavior:

Follow the instructions (https://www.whonix.org/wiki/Qubes/Install):

in dom0:

remove all whonix VMs (including templates)
`sudo qubes-dom0-update qubes-core-admin-addon-whonix`
`sudo qubesctl state.sls qvm.anon-whonix`

### Expected behavior:

Newly created sys-whonix uses the system default netVM as netVM.

### Actual behavior:

On systems intentionally not having VMs named sys-net and sys-firewall these VMs are recreated, system settings changed to use them as UpdateVM etc, so sys-whonix can use the new sys-firewall as netVM.

### General notes:

I have renamed the original sys-net to sys-net-wlan and created a new sys-net-eth so I can assign the two network interfaces to two independent VMs. I did the same with sys-firewall (i.e. sys-firewall-wlan and sys-firewall-eth).
This way I can connect to both networks at the same time and assign/reassign different appVMs to them very easily.

I had to change dom0 `/etc/qubes-rpc/policy/qubes.UpdatesProxy` to use sys-net-wlan instead of the non existent sys-net.

Everything worked great.

Enter the whonix salt formulas: they recreate the default sys-net and sys-firewall and the UpdatesProxy rule.

Maybe the salt formulas should simply use the default netVM setting from the system for sys-whonix, instead of the current recreation.

---

### Related issues:

https://github.com/QubesOS/qubes-issues/issues/3189 Salt - Qubes R4 RC1 - fails to set sys-whonix's NetVM to default (sys-firewall)

**Comment by shaaati** [comment]
Just a quick update: This issue still seems to exist in a fully updated Qubes 4 installation. However, the behaviour seems to have changed a bit:
Both sys-net and sys-firewall are still created when running the salt formula, but they are not made the default for anything, as far as I could tell. So it was easily possible to delete them again after creation.
i double-checked `/etc/qubes-rpc/policy/qubes.UpdatesProxy` to be sure, but this file looks okay.
