### ISSUE TITLE
Fedora-28 template change breaks Audio Recording (dom0:mic)

### ISSUE THREAD

**Issue by ezekiel** [QubesOS/qubes-issues#4204]
### Qubes OS version:

Qubes release 4.0 (R4.0)

### Affected component(s): 

Audio Recording (Microphone) from any AppVM
* pulseaudio
* pacat-simple-vchan

---

### Steps to reproduce the behavior:

Behavior is the same in AppVM and DispVM, it is just easier to reproduce/compare using DispVMs:
* launch fresh disposable VM based on unmodified `fedora-28` template installed from qubes repository
* Dom0: `qvm-device mic attach dispXXX dom0:mic`
* DispVM: `parecord -d vchan_input /run/user/1000/recording.tmp`
* speak or tap on the mic, notice that `/run/user/1000/recording.tmp` filesize is NOT growing
* Dom0: `less /var/log/qubes/pacat.dispXXX.log`
** notice **absence** of `Recording start` messages
** notice **absence** of `Stream device <foo> resumed` messages
** notice **presence** of `Setting audio-input to enabled` and `Setting audio-input to disabled` messages

### Expected behavior:

Assign `dom0:mic` to a `fedora-28`-based AppVM and record audio successfully.

### Actual behavior:

Assign `dom0:mic` to a `fedora-28`-based AppVM and fail to record audio. Switch the **same** AppVM back to a `fedora-26` template, and audio recording works normally.

### General notes:

* Dom0: `pulseaudio-10.0`
* Fedora-26: `pulseaudio-11.1`
* Fedora-28: `pulseaudio-12.2`

Tried manually unloading `module-x11-publish` from pulse in `fedora-28`, with no change in behavior. This was the only marked difference I identified between pulse setup in `fedora-26` and `fedora-28`.

It seems important that when recording is requested from `fedora-28`-based AppVMs **without** `dom0:mic` attached to the VM, the `pacat` log **does not** show `Recording requested but not allowed`, as it does with `fedora-26`-based AppVMs.

---

**Comment by ezekiel** [comment]
Comparison of `pacat.FOO.log`from `fedora-26`-based DispVM and `fedora-28`-based DispVM.
Session is as follows:
* launch DispVM
* begin recording WITHOUT `dom0:mic` attached
* attach `dom0:mic`
* detach `dom0:mic`
* stop recording
* halt VM

Fedora-26 (functional recording):
```
Connection established.
Stream successfully created.
Buffer metrics: maxlength=4194304, tlength=10164, prebuf=9144, minreq=1024
Using sample spec 's16le 2ch 44100Hz', channel map 'front-left,front-right'.
Connected to device alsa_output.pci-0000_00_1f.3.analog-stereo (0, not suspended).
Stream successfully created.
Buffer metrics: maxlength=4194304, tlength=4096, prebuf=4294967295, minreq=4294967295
Using sample spec 's16le 2ch 44100Hz', channel map 'front-left,front-right'.
Connected to device alsa_input.pci-0000_00_1f.3.analog-stereo (1, not suspended).
Stream started.
Stream device alsa_input.pci-0000_00_1f.3.analog-stereo suspended.
Stream cork
Recording requested but not allowed
Setting audio-input to enabled
Recording start
Stream device alsa_input.pci-0000_00_1f.3.analog-stereo resumed.
Setting audio-input to disabled
Recording stop
```

Fedora-28 (non-functional recording):
```
Connection established.
Stream successfully created.
Buffer metrics: maxlength=4194304, tlength=10164, prebuf=9144, minreq=1024
Using sample spec 's16le 2ch 44100Hz', channel map 'front-left,front-right'.
Connected to device alsa_output.pci-0000_00_1f.3.analog-stereo (0, not suspended).
Stream successfully created.
Buffer metrics: maxlength=4194304, tlength=4096, prebuf=4294967295, minreq=4294967295
Using sample spec 's16le 2ch 44100Hz', channel map 'front-left,front-right'.
Connected to device alsa_input.pci-0000_00_1f.3.analog-stereo (1, not suspended).
Stream started.
Stream device alsa_input.pci-0000_00_1f.3.analog-stereo suspended.
Stream underrun.
Setting audio-input to enabled
Setting audio-input to disabled
```

**Comment by ezekiel** [comment]
Any word on how likely it is for the cause of this bug to be identified? Is there any additional information I can provide, or testing I should perform?

**Comment by eug48** [comment]
The microphone was working for me on fedora-28 until approximately 1-2 weeks ago I think.

I've just managed to fix it by downgrading to pulseaudio 11.1 (sudo dnf downgrade pulseaudio) & restarting the qube.

**Comment by marmarek** [comment]
Looks related to pulseaudio 12 update in Fedora. Updates already
available:
https://github.com/QubesOS/qubes-issues/issues/4151#issuecomment-408254811

**Comment by eug48** [comment]
My microphone doesn't work with the latest update (pulseaudio 12.2-1.fc28, qubes-gui-agent 4.0.14-1.fc28). Downgrading pulseaudio to 11.1-18.fc28 fixes it.

When in the broken state there is no VU meter bar in the pavucontrol Input Devices tab beneath "Qubes vchan input". Here is some output from alsa-info.sh: https://pastebin.com/yKyC1je6

Thanks

**Comment by ezekiel** [comment]
@marmarek, recording is still broken with pulse 12.2 updates from #4151 .

The `pacat` logs still show the same behavior where the recording device is never `resumed`. Perhaps there is some fundamental change in pulseaudio 12 which will require support implemented in `pacat`?

**Comment by lvh** [comment]
I'm still seeing this issue with qubes-dom0-current-testing updates from today.

**Comment by lvh** [comment]
Still seeing the same 44 byte recording.tmp file not grow after these updates, with the most recent dom0-current-testing packages. Let me know if you want specific package versions.

**Comment by ezekiel** [comment]
I've updated Dom0 and a Fedora28 Template with `testing` packages, and I have been able to record audio without issue.

**Comment by lvh** [comment]
To be clear, you did something like `sudo dnf --enablerepo=updates-testing update` in the fedora-28 template, and also enabled `qubes-dom0-current-testing`?

**Comment by ezekiel** [comment]
I cloned the qubes-provided fedora-28 template to a new template for this, and ran two update commands from dom0.
1: `qvm-run -u root fedora-28-testing "dnf --enablerepo=qubes-vm-*-current-testing -y update; dnf autoremove; dnf clean all"`
2: `sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing`

If you wanted to be more selective about WHICH packages are updated from testing in Dom0, just supply their package names.
