### ISSUE TITLE
Screen tearing - Popcorn Time

### ISSUE THREAD

**Issue by Simon-Davies** [QubesOS/qubes-issues#4208]
### Qubes OS version:

Qubes OS 4.0

### Affected component(s): 

All AppVMs

---

### Steps to reproduce the behavior:

Run Popcorn Time in AppVM

### Expected behavior:

Smooth video playback

### Actual behavior:

Video is choppy especially in scenes with lots of fast movement.

### General notes:

---

**Comment by andrewdavidwong** [comment]
Related (possible duplicate): #3194

**Comment by Simon-Davies** [comment]
Is this being looked into?

**Comment by marmarek** [comment]
Not really, since apparently it happens only on your hardware. But you may want to try update video driver, see https://github.com/QubesOS/qubes-issues/issues/4315#issuecomment-422230373 (I assume you have intel one, right?)

**Comment by Simon-Davies** [comment]
It doesn't happen only on my hardware. Have you seen the other thread about tearing?

It can happen on Arch aswell. It's an Intel specific thing by the looks of it.

**Comment by rustybird** [comment]
> I tried creating the 10-display.conf file about a month ago but it stopped X11 from starting and was a nightmare to fix as I had to mount the Encrypted LUKS partition with my Installation USB.

When your X server doesn't work, you can switch to a Linux terminal (e.g. Ctrl-Alt-F2) once all your autostart VMs have started, login, see what's up in `/var/log/Xorg.0.log`, edit your configuration, and `systemctl restart lightdm`.

BTW my Intel HD Graphics 4000 works fine with just one option in `/etc/X11/xorg.conf.d/90-intel.conf`:

```
Section "Device"
        Identifier "Intel Graphics"
        Driver "intel"
        Option "TearFree" "true"
EndSection
```

**Comment by Simon-Davies** [comment]
I'll give this config a try. Thanks @rustybird

**Comment by andrewdavidwong** [comment]
Re-labeling as a doc task. PRs welcome.
