### ISSUE TITLE
Qubes reboots always after initrd.img line

### ISSUE THREAD

**Issue by vnesterov** [QubesOS/qubes-issues#4210]
### Qubes OS version:

Qubes-R4.0

### Affected component(s): 

Installation steps

---

### Steps to reproduce the behavior:

Just run installation on VirtualBox 5.2 with enabled EFI (if this not enabled i'll getting "Failed loading kernel modules") and it will be all time rebooting after line initrd.img
![1](https://user-images.githubusercontent.com/7912537/44035601-87158b54-9f18-11e8-8c27-743e3dea5c0a.jpg)
and this screen
![2](https://user-images.githubusercontent.com/7912537/44035614-8f9a28ca-9f18-11e8-92b6-0892343c8ed9.jpg)

Please tell me the steps how to run Qubes-R4.0 installing process on VirtualBox 5.2.

**Comment by andrewdavidwong** [comment]
[Installing Qubes in a virtual machine is neither recommended nor supported.](https://www.qubes-os.org/faq/#can-i-install-qubes-in-a-virtual-machine-eg-on-vmware)

Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this does not appear to be suitable for `qubes-issues`. We ask that you please send this to the `qubes-users` [mailing list](https://www.qubes-os.org/support/) instead. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a brief comment explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.
