### ISSUE TITLE
Repository signing key - hard to find

### ISSUE THREAD

**Issue by unman** [QubesOS/qubes-issues#4212]
### Qubes OS version:

All

### Affected component(s): 

Infrastructure?
Qubes Debian Repositories

---

### Steps to reproduce the behavior:

Install Debian: attempt to add Qubes repositories and install Qubes packages

### Expected behavior:

Update and install as normal

### Actual behavior:

Repo signing key not found.

### General notes:

It's difficult to find the repository signing key: It didn't seem to be on keyservers, isn't included in the security pack, or on the website on the Keys page.

---

**Comment by lunarthegrey** [comment]
Would be good to know about! Subscribing to this.

**Comment by unman** [comment]
@z64z You prove my point.
It isn't that the key can't be found, but that it is *more* difficult to find than the Fedora repository key.  It should not be.
Although it is now on keyservers,  the Debian signing key should be included in the secpack and the Qubes keyserver.

**Comment by z64z** [comment]
Absolutely. I was in the same boat, I looked and looked before it dawned on me that I could just get it from the official template. I only documented how I did it for the benefit of people having the same issue in the future.

**Comment by esote** [comment]
@unman @andrewdavidwong Maybe these signing key(s) should also be put under https://keys.qubes-os.org/keys/ (if it's not there currently). That is where documentation links to for "Qubes PGP Keys."

**Comment by andrewdavidwong** [comment]
@esote:
> Maybe these signing key(s) should also be put under https://keys.qubes-os.org/keys/ (if it's not there currently). That is where documentation links to for "Qubes PGP Keys."

I believe that's precisely what @unman was suggesting when he wrote above:

> the Debian signing key should be included in the secpack and the Qubes keyserver.

**Comment by esote** [comment]
Thanks, I didn't catch the second part.

**Comment by adrelanos** [comment]
Where is the key in git?

**Comment by marmarek** [comment]
It's here: https://github.com/QubesOS/qubes-core-agent-linux/blob/master/misc/qubes-archive-keyring.gpg

I've uploaded it to keys.qubes-os.org too.

**Comment by unman** [comment]
All done

**Comment by adrelanos** [comment]
@marmarek 
> It's here: https://github.com/QubesOS/qubes-core-agent-linux/blob/master/misc/qubes-archive-keyring.gpg

That link is down.

**Comment by marmarek** [comment]
There were recently changes in repository layout, it's [here](https://github.com/QubesOS/qubes-core-agent-linux/blob/master/package-managers/apt-qubes-archive-keyring.gpg) now. The other link works:
https://keys.qubes-os.org/keys/qubes-release-4-debian-signing-key.asc
