### ISSUE TITLE
'make clean-chroot' does not remove chroots

### ISSUE THREAD

**Issue by unman** [QubesOS/qubes-issues#4214]
### Qubes OS version:

R4.0

### Affected component(s): 

Qubes builder

---

### Steps to reproduce the behavior:

Build a number of templates.
`make clean-chroot`

### Expected behavior:

as per help:
> 
remove all chroot directories

### Actual behavior:

/proc remains mounted within chroots, and chroots are not removed.

### General notes:

---

**Comment by fepitre** [comment]
Probably a stupid question but do DISTS_VM or/and DIST_DOM0 remain set with all your chroot for templates, e.g. DISTS_VM="fc25 fc26 centos7 stretch", when you try a make clean-chroot?

**Comment by unman** [comment]
Did not realize this was still open.
Can no longer reproduce.
