### ISSUE TITLE
Permission denied when trying to transfer template installer to Dom0? [solved]

### ISSUE THREAD

**Issue by SeemsToHaveLotsOfProblems** [QubesOS/qubes-issues#4222]
### Qubes OS version:

Qubes 4.0 | R4.0

### Affected component(s): 

Permissions

---

### Steps to reproduce the behavior:

Following this guide [Template Builder](https://www.qubes-os.org/doc/building-archlinux-template/)
everything succeeds and I get to the last line 
`cd /`
`sudo qvm-run –pass-io development ‘cat /home/user/qubes-builder/qubes-src/linux-template-builder/rpm/install-templates.sh’ > install-templates.sh` 
Run from Dom0.

### Expected behavior:

Transfer the template to dom0

### Actual behavior:

`bash: install-templates.sh: permission denied`

### General notes:

EDIT: I read the wrong steps, sorry. Everything is working fine.

I've tried checking the box on the install-templates file that allows running as an executable, but that changed nothing. 
Sorry if this is a really dumb question/issue, but I'm still new, and as my name suggest I run into lots of problems, though I can usually fix them myself.

---

**Comment by andrewdavidwong** [comment]
> EDIT: I read the wrong steps, sorry. Everything is working fine.

Closing as "not an issue." If you believe this is a mistake, please leave a comment, and we'll be happy to take another look. Thank you.
