### ISSUE TITLE
DVM Templates can't be deleted if they're their own default DVM Template

### ISSUE THREAD

**Issue by strugee** [QubesOS/qubes-issues#4224]
### Qubes OS version:

R4.0

### Affected component(s): 

Qubes Manager(?)

---

### Steps to reproduce the behavior:

1. Install with the default settings, making sure to enable Whonix integration
2. Try to delete `whonix-ws-dvm`
3. Receive an error message saying to check system logs
4. Observe that `journalctl -xn` says `Cannot remove whonix-ws-dvm, used by whonix-ws-dvm.default_dispvm`

### Expected behavior:

~VM~ DVM Template is removed without fuss as long as nothing else is using it.

### Actual behavior:

Qubes refused to delete the ~DispVM~ DVM Template because it was its own default ~DispVM~ DVM Template.

**Comment by andrewdavidwong** [comment]
I think you might be missing the distinction between [DVM Templates](https://www.qubes-os.org/doc/glossary/#dvm-template) and [DispVMs](https://www.qubes-os.org/doc/glossary/#dispvm).

**Comment by RefinedSoftwareLLC** [comment]
With R4.0, security-testing. I was unable to delete a "-dvm" qube because its "Default DispVM" was set to itself. Since the delete command will also delete the offending qube (itself) this shouldn't prevent the deletion.

P.S. Error message said to look at system logs, but didn't say which qube (I assume Dom0), and it didn't say which log file (Dom0 has many files in the system log folder.

**Comment by strugee** [comment]
@andrewdavidwong sorry for the delay! I definitely might be wrong about the terminology; I'm new to Qubes. I think the bug I was describing is still valid though.

**Comment by strugee** [comment]
@RefinedSoftwareLLC can you file a separate issue for the error message improvements? That would be a useful fix and probably pretty easy to do. You'd have to search for duplicates first.

**Comment by andrewdavidwong** [comment]
> I definitely might be wrong about the terminology; I'm new to Qubes. I think the bug I was describing is still valid though.

But it's important to get the terminology right, or else others won't understand what you're saying. Could you please update your issue with the correct terminology?

**Comment by strugee** [comment]
@andrewdavidwong fixed

**Comment by andrewdavidwong** [comment]
Thanks, but it still doesn't make sense to me to say that a DVM Template "is its own DVM Template." AFAIK, that's impossible, since only DispVMs (which cannot themselves be DVM Templates) have DVM Templates. But maybe that's the bug you're reporting.

**Comment by strugee** [comment]
I think you've misread the edit; I am talking about A DVM Template being set as its own _default_ DVM Template. AFAIUI this is the template that gets used by default when e.g. "open in DispVM" menu items are used.

**Comment by andrewdavidwong** [comment]
> I think you've misread the edit; I am talking about A DVM Template being set as its own default DVM Template. AFAIUI this is the template that gets used by default when e.g. "open in DispVM" menu items are used.

Ah, I think I see what you mean now. Thanks for the clarification.

**Comment by RefinedSoftwareLLC** [comment]
The confusion is coming from a typo in Qube Manager. Both the origional post and my above post are quoting a setting from the Qube Manager called "Default DispVM".

Open this window: "Qube Manager" > Menu "Qube" > "Qube Settings" > Tab "Advanced"
Then please rename the setting "Default DispVM:" to "Default DVM Template:".

**Comment by strugee** [comment]
> @RefinedSoftwareLLC can you file a separate issue for the error message improvements? That would be a useful fix and probably pretty easy to do. You'd have to search for duplicates first.

I didn't want this to drop off the radar so I went to file a new issue. While searching for duplicates I found #1300 but I'm not sure if it entirely covers the vague error messages being described above?

**Comment by andrewdavidwong** [comment]
> While searching for duplicates I found #1300 but I'm not sure if it entirely covers the vague error messages being described above?

I'd say it falls under #1300, but either way would be fine in this case.

**Comment by strugee** [comment]
In either case I filed QubesOS/qubes-core-admin#226 to fix the error message.

**Comment by strugee** [comment]
This should be reopened. I can still reproduce this bug under Qubes Manager 4.0.39. Trying to delete `whonix-ws-14-dvm` results in this error:

![Screenshot of a Qubes Manager error window saying that the VM cannot be deleted because `whonix-ws-14-dvm.default_dispvm` uses it](https://user-images.githubusercontent.com/911174/64913241-53f94280-d70a-11e9-8475-6fdf92ed04e7.png)

I can also file a new ticket if that's easier for the core developers to track.
