### ISSUE TITLE
Fedora 29 dom0 (QubesOS 4.1)

### ISSUE THREAD

**Issue by fepitre** [QubesOS/qubes-issues#4225]
Tracking issue for Fedora 29 dom0:
- [x] rebase desktop-linux-xfce4 (xfwm4 at least) on the version in fc29
- [x] rebase desktop-linux-kde (baseapps, settings?) on the version in fc29
- [x] build all packages
- [x] include at least Fedora 29+ as default template for VM
- [x] build and test a release candidate for QubesOS 4.1

**Comment by fepitre** [comment]
@andrewdavidwong : please do not hesitate to modify or/and add things. Thank you !

**Comment by marmarek** [comment]
@fepitre I've added:
- rebase desktop-linux-xfce4 (xfwm4 at least) on the version in fc29
- rebase desktop-linux-kde (baseapps, settings?) on the version in fc29

**Comment by fepitre** [comment]
@marmarek: should be close this one and linked to newer one(s)?

**Comment by fepitre** [comment]
@andrewdavidwong, @marmarek I marked it as achieve as we did all tasks listed. I referenced this issue in newer one.
