### ISSUE TITLE
dom0 unstable after install of 4.14.*

### ISSUE THREAD

**Issue by vincentadultman** [QubesOS/qubes-issues#4236]
### Qubes OS version:
3.2

After booting this kernel, the system initially seems okay but rapidly becomes completely unusable. Vms will boot but:

1. Quickly become unresponsive to mouse clicks
2. Dispvms boot with very slow or failing networking.
3. VMs get stuck using 100% CPU
4. One instance of qvm-shutdown -all caused the machine to freeze up completely.

Booting back to 4.9.56-21 resolves the issues completely.

Hardware is an HP 820 G3 with 16GB Ram.

**Comment by marmarek** [comment]
Do you see any kernel errors (`sudo dmesg` in dom0)?


> Booting back to 4.9.56-21 resolves the issues completely.

Even when VMs are still using 4.14.57?

**Comment by vincentadultman** [comment]
> Do you see any kernel errors (`sudo dmesg` in dom0)?
> 
Just updated to 4.14.57.2, same issue but didn't get past the login screen this time. I'll take a fresh backup and then see if I can get some logs for you.

> Even when VMs are still using 4.14.57?

Yup VMs are using 4.14.57. I have been seeing the occasional lock up (not more than once every several days) so will switch back to an older kernel for VMs and see if that goes away completely.

**Comment by vincentadultman** [comment]
Sorry for delay, please find attached dmesg.log
[dmesg.log](https://github.com/QubesOS/qubes-issues/files/2475739/dmesg.log)

**Comment by vincentadultman** [comment]
in reply to @thewildcat yes I also have ACPI errors, but they are different from yours and also appear present on older kernels on this machine

**Comment by vincentadultman** [comment]
Just as an update, having installed 4.14.74-1 this is more stable than previous Kernels of the series. I can login, start vms, visit web pages. However, the GUI is still weirdly unresponsive, I think because the screen is not being updated. An ideal example is playing video from Youtube, the sound plays smoothly and consistently but the video does not, you have to scroll the page up and down to get the page to update, the same is true for static pages. Only experimented for a short time before booting back to 4.9.56-21 which at least over the weekend has been completely stable, with the other problem I was experiencing in #4389 now resolved

**Comment by andrewdavidwong** [comment]
`This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 has reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.`
