### ISSUE TITLE
SELinux support in Fedora qubes

### ISSUE THREAD

**Issue by t4777sd** [QubesOS/qubes-issues#4239]
### Qubes OS version:
4.0 utilizing default Fedora 28 templates that are fully updated

### Steps to reproduce the behavior:
1. Edit /etc/selinux/config and enable selinux in the TemplateVM and restart the TemplateVM:

SELINUX=enforcing
SELINUXTYPE=targeted

2. Add the following kernel params to the AppVM domain where SELinux should be enabled:

qvm-prefs --set <appvm> kernelopts "nopat security=selinux selinux=1"

3. Start the AppVM

qvm-start <appvm>

### Expected behavior:
Expected that the AppVM can boot with SELinux enabled especially because SELinux is enabled by default in fedora.

### Actual behavior:

The VM does not start and eventually will need to be killed.

* Note: the behavior is the same even if SELINUX=permissive is set

**Comment by DemiMarie** [comment]
Does this happen if you use the stock Fedora kernel?

**Comment by t4777sd** [comment]
This was done a fresh fedora 28 template installed via package manager (not fedora 26 + updated to fedora 28) and then it was fully updated via yum update. I made no manual change of the kernel so it would be the default one that would be selected with those steps

**Comment by esote** [comment]
If you check the console while it's booting (or boot in debug mode), here is the error I get:
```
[    6.970855] audit: type=1404 audit(1543350043.241:2): enforcing=1 old_enforcing=0 auid=4294967295 ses=4294967295
SELinux:  Could not open policy file <= /etc/selinux/targeted/policy/policy.31:  No such file or directory
[    6.977989] systemd[1]: Failed to load SELinux policy.
[.[0;1;31m!!!!!!.[0m] Failed to load SELinux policy, freezing.
[    6.979601] systemd[1]: Freezing execution.
```
So it's missing the SELinux policy.

**Comment by marmarek** [comment]
Is `selinux-policy-targeted` package installed?

**Comment by esote** [comment]
@marmarek Not by default. That was the issue.

@t4777sd so if we want SELinux enabled by default, we need `selinux-policy-targeted` installed by default.

Now we need to decide if we want it enabled by default.

**Comment by esote** [comment]
@marmarek No. That fixed that. Now it sits at:

```
         Starting Relabel all filesystems...

*** Warning -- SELinux targeted policy relabel is required.
*** Relabeling could take a very long time, depending on file
*** system size and speed of hard drives.
```

And then it crashes with no more info. Any specific logs I should check besides `/var/log/xen/console/guest-vmname.log` (which only has above)?

**Comment by esote** [comment]
Here's the script used for fixfiles, if that helps. https://github.com/SELinuxProject/selinux/blob/master/policycoreutils/scripts/fixfiles

**Comment by marmarek** [comment]
Try increasing qrexec_timeout property.

**Comment by marmarek** [comment]
> Current mode: permissive

This isn't really protecting anything... What happens if you switch to enforcing mode? Check also if processes are labeled (`ps auxZ`).

**Comment by esote** [comment]
Running `setenforce 1` doesn't cause things to break, if that's what you mean. However it does reset after restarting, is there a permanent way to set it?

I'm not too familiar with SELinux, are things labelled correctly?
```
$ ps auxZ | grep qube
system_u:system_r:unconfined_service_t:s0 root 257 0.0  0.0 123252 168 ?       SLs  16:42   0:00 /usr/sbin/qubesdb-daemon 0
system_u:system_r:unconfined_service_t:s0 root 444 0.1  0.1 75696 1756 ?       SLs  16:42   0:00 /usr/bin/qubes-gui
system_u:system_r:unconfined_service_t:s0 root 478 0.0  0.1 296136 1864 ?      S    16:42   0:00 su -l user -c /usr/bin/xinit /etc/X11/xinit/xinitrc -- /usr/bin/X :0 -nolisten tcp vt07 -wr -config xorg-qubes.conf > ~/.xsession-errors 2>&1
system_u:system_r:unconfined_service_t:s0 user 538 0.0  0.1 216640 1440 ?      Ss   16:42   0:00 -bash -c /usr/bin/xinit /etc/X11/xinit/xinitrc -- /usr/bin/X :0 -nolisten tcp vt07 -wr -config xorg-qubes.conf > ~/.xsession-errors 2>&1
system_u:system_r:unconfined_service_t:s0 user 557 0.0  0.0 14000 124 ?        S    16:42   0:00 /usr/bin/xinit /etc/X11/xinit/xinitrc -- /usr/bin/X :0 -nolisten tcp vt07 -wr -config xorg-qubes.conf
system_u:system_r:unconfined_service_t:s0 user 558 0.5  5.0 790644 50084 ?     SLl  16:42   0:00 /usr/libexec/Xorg :0 -nolisten tcp vt07 -wr -config xorg-qubes.conf
system_u:system_r:unconfined_service_t:s0 user 567 0.0  0.3 214388 3032 ?      Ss   16:42   0:00 /bin/bash /usr/bin/qubes-session
system_u:system_r:unconfined_service_t:s0 user 686 0.0  0.2 66268 2256 ?       SL   16:42   0:00 /usr/bin/qrexec-client-vm dom0 qubes.WindowIconUpdater /usr/lib/qubes/icon-sender
system_u:system_r:unconfined_service_t:s0 user 719 0.0  1.3 250652 13320 ?     S    16:42   0:00 /usr/bin/python3 /usr/lib/qubes/icon-sender
system_u:system_r:unconfined_service_t:s0 user 750 0.0  0.8 516044 8696 ?      S<l  16:42   0:00 pulseaudio --start -n --file=/etc/pulse/qubes-default.pa --exit-idle-time=-1
unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 user 1029 0.0  0.0 213796 980 pts/0 S+ 16:44   0:00 grep --color=auto qube
```
Looks like `unconfined_service_t` is [the default](https://danwalsh.livejournal.com/70577.html)?

**Comment by esote** [comment]
Ah, now if I try `qvm-run -v -p vmname xterm` it returns
```
Running 'xterm' on vmname
connect: No such file or directory
```
Looks like this is the issue @DemiMarie gives in #4279.

**Comment by ideologysec** [comment]
Seems like the SELinux policies need to be written. Have you tried dumping the actions in permissive mode and creating rules, then testing in enforcing?

**Comment by DemiMarie** [comment]
@ideologysec I have done that, and it works.  The one caveat is that one *must* use `dbus-daemon` instead of `dbus-broker`, since the latter is busted when SELinux is involved.

**Comment by ritschmaster** [comment]
Just dumping my experience on this issue: I made it to actually run SELinux in the enforcing mode. But I am not really into SELinux, I did mess with labeling some Qubes files and tracking them in a module, but failed terrible.

The following steps allowed me running a Fedora based VM named selinuxtest in the enforcing mode:
1.  In dom0:
    1. qvm-prefs -s selinuxtest kernel ''
    2. qvm-prefs -s selinuxtest virt_mode hvm
2. In selinuxtest:
    1. sudo dnf install -y selinux-policy* policycoreutils* audit
    2. sudo shutdown -h now
    3. Edit /etc/selinux/config and set SELINUX=permissive
3. In dom0
    1. qvm-prefs -s selinuxtest qrexec_timeout 600
    2. qvm-prefs -s selinuxtest kernelopts "nopat security=selinux selinux=1 enforcing=0 autorelabel=1"
    3. qvm-start selinuxtest
4. In selinuxtest
    1. sudo su root
    2. grep qubes /var/log/audit/audit.log | audit2allow -M qubes
    3. semodule -i qubes.pp
    4. sudo setenforce 1

Sometimes it then works to open another Terminal via qvm-start and sometimes it does not.

**Comment by DemiMarie** [comment]
I have a git repository (which I will publish soon) that includes working SELinux policies for Fedora.  I have SELinux enforcing on most qubes I use, including the one I am using to type this message.

**Comment by irelativism** [comment]
o/ qubes, you should consider the HyperbolaBSD project once its finished, a openbsd kernel and userspace hard fork, with the focus in modularity and freedom, so by consequence security and privacy, also all mergerd works will be licensed under GPLv3. other efforts will be included like features from drangonfly, Gentoohardenedbsd debiankfreebsd, pacmanbsd and libertybsd scripts. hyperbola.info for more info. Cheers.

**Comment by ideologysec** [comment]
@DemiMarie any updates on the repo with working SELinux policies?

**Comment by DemiMarie** [comment]
@ideologysec My current repo will need significant cleanup, and there have been many other high-priority issues lately.

**Comment by DemiMarie** [comment]
Questions that still need to be answered:

- [ ] Should Qubes OS include workarounds for upstream bugs?
- [ ] Should `user` be mapped to `staff_u` or `unconfined_u`?
- [ ] How much should upstream-provided interfaces be used?
- [ ] Should the policy use the old policy language, or the Common Intermediate Language?

**Comment by DemiMarie** [comment]
Not sure what the milestone for this should be.

**Comment by andrewdavidwong** [comment]
> Not sure what the milestone for this should be.

Earliest affected release, which appears to be 4.0, so the current one is correct.

**Comment by DemiMarie** [comment]
This is now implemented.

**Comment by xbc5** [comment]
@ideologysec

**Comment by ideologysec** [comment]
@xbc5 thanks for the ping. And thanks everyone for the hard work of making this happen!

**Comment by jvoisin** [comment]
Given that there is [passwordless sudo]( https://www.qubes-os.org/doc/vm-sudo/ ) with a lengthy justification on how privesc are alright, what is the point of enabling SELinux in Fedora Qubes?

**Comment by marmarek** [comment]
User is running unconstrained, but having SELinux enabled allows using it for various in-VM sandboxes, like podman, bubblewrap, but also for extra hardening of receiving side of qvm-copy.
