### ISSUE TITLE
1 USB controller instead of 5 (Qubes Manager -- Settings -- Devices)

### ISSUE THREAD

**Issue by loadcorp** [QubesOS/qubes-issues#4242]
### Qubes OS version:

Qubes 4.0

### Affected component(s): 

15″ Laptop: https://system76.com/laptops/oryx
Qubes Manager -- Settings (in any VM) -- Devices

---

### Steps to reproduce the behavior:

Going to any VM Setting (which in HVM mode) via Qubes manager and open Device tab.
Than see that I have only 1 USB controller, but must be 5 at least (2× USB 3.1 Type-C, 3× USB 3.1 Type-A).

### Expected behavior:

I am choosing this only 1 USB controller and click on button 'Configure strict reset for PCI devices'.

### Actual behavior:

But when VM starting all my USB ports on my Laptop going to this VM. It means that even my usb mouse and all my flash drives with usb modems going to this VM.

### General notes:

Maybe existing some way, when I can connect only those usb ports to VM which contain devices in laptop at the same time?

---

### Related issues:

Even when I am turning this VM off, in any way all usb still not working in Dom0. They start working again in Dom0 only after whole laptop reboot.

**Comment by andrewdavidwong** [comment]
A USB controller is different from a USB port. You only have one USB controller. All five of your USB ports are using this single USB controller. For more information, see:

https://www.qubes-os.org/doc/usb/

Please address futher questions to `qubes-users` [mailing list](https://www.qubes-os.org/support/).
