### ISSUE TITLE
Using Purism TPM?

### ISSUE THREAD

**Issue by Kixunil** [QubesOS/qubes-issues#4243]
Hi, I'm running Qubes 4.0 and I can't find any documentation on how to setup TPM present on Pursm Librem 13 in order to protect against evil-maid attacks. Is this supported?

**Comment by andrewdavidwong** [comment]
Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this does not appear to be suitable for `qubes-issues`. We ask that you please send this to the `qubes-users` [mailing list](https://www.qubes-os.org/support/) instead. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a brief comment explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.
