### ISSUE TITLE
QubesPropertyAccessError triggered by renaming VM in Qube Manager

### ISSUE THREAD

**Issue by qubenix** [QubesOS/qubes-issues#4244]
### Qubes OS version:

r4.0

### Affected component(s): 

Qube Manager

---

### Steps to reproduce the behavior:

Rename a VM.

### Expected behavior:

No errors or warnings.

### Actual behavior:

```
Whoops. A critical error has occured. This is most likely a bug in Qubes Manager.

QubesPropertyAccessError: Failed to access 'qid' property
at line 993
of file /usr/lib/python3.5/site-packages/qubesmanager/qube_manager.py.

----
line: raise qubesadmin.exc.QubesPropertyAccessError(item)
func: __getattr__
line no.: 203
file: /usr/lib/python3.5/site-packages/qubesadmin/base.py
----
line: self.vms_in_table[vm.qid].update()
func: action_settings_triggered
line no.: 993
file: /usr/lib/python3.5/site-packages/qubesmanager/qube_manager.py
```

### General notes:

---

**Comment by andrewdavidwong** [comment]
Error message looks similar to some reported in #3856.

**Comment by esote** [comment]
I also notice that if I rename a qube while the Qube Manager is open, the Qube Manager stops refreshing until it is re-opened (ie does not update to show if a VM is started, DVM created, etc.).
