### ISSUE TITLE
Applications Self-Destruct

### ISSUE THREAD

**Issue by asddsaz** [QubesOS/qubes-issues#4246]
### Qubes OS version: R4
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
**Issue: Applications self destruct upon shut down**
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

Expected behavior: It to NOT do that.

Steps: Basically whenever I download an App or Flatpak or Snap and shut down the Qube it deletes the Application.

Operating System: QubesOS Debian 9

**Comment by esote** [comment]
This is by design. If you install something in an AppVM, it only persists until the AppVM is shut down. If you want to install something permanently, install it in the AppVM's template.

**Comment by andrewdavidwong** [comment]
See the documentation @esote linked. This is working as intended.
