### ISSUE TITLE
[Feature] Root TemplateVM

### ISSUE THREAD

**Issue by asddsaz** [QubesOS/qubes-issues#4249]
**Feature**: A fully featured RootVM for apps that need specific control over things like desktop customization.
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
**Why**?: Certain apps need full control over a computer and need to be running at all times. This should only be used by advanced users.
**Example**: Screen Sharing can many times require sharing your whole screen this would allow users to easily install customized screen sharing software and share it between other VMs.

**Comment by andrewdavidwong** [comment]
> A fully featured RootVM for apps that need specific control over things like desktop customization.

This sounds like the future GUI domain (#4186).

> Certain apps need full control over a computer and need to be running at all times. This should only be used by advanced users.

This sounds like dom0.

> Screen Sharing can many times require sharing your whole screen this would allow users to easily install customized screen sharing software and share it between other VMs.

I don't understand what you mean by "share it between other VMs." The screen sharing software would either be running in a privileged domain like dom0 (inadvisable) or the GUI domain (questionable) or an AppVM, in which case it would have access only to that AppVM's screen. Unless you mean "share" in the same sense in which TemplateVMs share their software with all the VMs based on them, but then that's just normal TemplateVM usage.

I don't see anything here that constitutes an appropriate feature request.
