### ISSUE TITLE
Killing salt process can cause Qubes to enter invalid state, leaving zombie VM until manual `virsh undefine`

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#4253]
### Qubes OS version:

R4.0

### Affected component(s): 

qubes-core-admin

---

### Steps to reproduce the behavior:

Kill a saltstack process at just the wrong time.  The problem is intermittent.

### Expected behavior:

All domains that were started are cleaned up

### Actual behavior:

Qubes (rarely) gets into an invalid state, in which qubesd and libvirt disagree as to whether a certain domain exists:

* qubesd does not think it exists, so it cannot be removed with Qubes tools
* but libvirt thinks it exists, so it refuses qubesd’s attempt to create a new vm with the same name

This forced me to do `virsh undefine` in dom0, which should never be required.

### General notes:

Reproducing this bug requires winning a race condition, which is hard.

---

**Comment by andrewdavidwong** [comment]
Possibly related: #2112, #1910

**Comment by DemiMarie** [comment]
The problem is that both libvirtd and qubesd are stateful, and both believe their state to be authoritative.  One of them needs to actually **be** authoritative, and update the state of the other one when needed.

**Comment by DemiMarie** [comment]
Proposed fix: never remove a domain from `qubes.xml` until libvirt confirms its removal.
