### ISSUE TITLE
Provide a location for user-provided files to be copied to VMs by Salt

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#4256]
### Qubes OS version:

R4.0

### Affected component(s): 

Salt Management Stack

---

### Steps to reproduce the behavior:

Look for a place to put user-provided files, which I want to refer to in Salt states with `salt://` URLs.

### Expected behavior:

There is a documented location for such files

### Actual behavior:

No such location

### General notes:

Putting the files in `/srv/user_salt` doesn’t work.

---

**Comment by unman** [comment]
I'm not sure where `/srv/user_salt` has come from.
The canonical place for storing files would be under /srv/salt. Have a look at the [getting started guide](https://docs.saltstack.com/en/getstarted/config/files.html).
And indeed, any files placed there become available for reference using salt://

Users can create their own directories under /srv/salt if they wish - I dont see any benefit in Qubes providing such a location.

**Comment by unman** [comment]
Sorry @DemiMarie 

> I'm not sure where /srv/user_salt has come from.

Completely forgot about `user_dirs` state. Presumably you've applied it.

But the point still holds true.
If you've applied  user_dirs, then you can just put files under /srv/user_salt and reference them using salt://, _provided_ your top file sets environment user:
If you are using base, then you can use files under /srv/salt

**Comment by p1llule** [comment]
Hi @DemiMarie

Looking to implement [anonymizing-your-mac-address](https://github.com/Qubes-Community/Contents/blob/master/docs/privacy/anonymizing-your-mac-address.md) as a salt formula I had to transfer files and it worked.

After using `sudo qubesctl state.apply qubes.user-dirs`

I started to populate the user_salt directory. For the formula cited, it consist in :

a configure.top file :
```` sls
base:
  d10_net:
  - d10_net.configure
````

a configure.sls file :
```` sls
/etc/NetworkManager/conf.d/00-macrandomnize.conf:
  file.managed:
    - source:
      - salt://d10_net/00-macrandomnize.conf
    - user:     root
    - group:    root
    - makedirs: True

/etc/network/if-pre-up.d/00_hostname:
  file.managed:
    - source:
      - salt://d10_net/00_hostname
    - user:     root
    - group:    root
    - makedirs: True
    - mode:     '0700'

/etc/hosts.lock:
  file.managed:
    - mode:     '0644'

/rw/config/protected-files.d/protect_hostname.txt:
  file.managed:
    - user:     root
    - group:    root
    - makedirs: True
    - mode:     '0644'
    - contents:
      - /etc/hosts
      - /etc/hostname
````

the directory structure looks like that :
````
/srv/user_salt/
├── d10_net
│   ├── 00_hostname
│   ├── 00-macrandomnize.conf
│   ├── clone.sls
│   ├── clone.top
│   ├── configure.sls
│   ├── configure.top
│   ├── create.sls
│   ├── create.top
│   ├── install.sls
│   └── install.top
├── locale
│   └── init.sls
├── template-debian-10-minimal
│   ├── create.sls
│   └── create.top
└── top.sls

3 directories, 15 files
````

The command I used to apply this state :
`sudo qubesctl --show-output --skip-dom0 --targets=d10_net     state.apply d10_net.configure saltenv=user`

The `saltenv=user` part is important.
I can change the top from `user:` to `base:` without noticing always needs to specify the saltenv.

I am not so confident on how to use salt but I hope it may helps you a little to figure out your issue.

**Comment by unman** [comment]
Thanks for adding the detail.
Is this still open?

@DemiMarie, @andrewdavdiwong - can you close it please? We already
provide the location asked for.

**Comment by zaz** [comment]
As part of the effort to make SALT more accessible to end users (#8218), would it make sense to have a directory where contents are automatically copied to target Qubes?

For example, the end user could create `/srv/user_salt/fs/fedora-??/etc/hosts.lock` and this would automatically be copied to all Fedora Qubes.
