### ISSUE TITLE
Login screen does not update on password input

### ISSUE THREAD

**Issue by labanskoller** [QubesOS/qubes-issues#4259]
### Qubes OS version:

R3.2

### Affected component(s): 

lightdm?

---

### Steps to reproduce the behavior:

1. Start the computer and unlock the disk encryption
1. Wait for the login screen to appear
1. Start typing password (my only user is automatically selected)

### Expected behavior:

Every keystroke should render a filled circle.

### Actual behavior:

Nothing happens and I initially thought the system was frozen. Then I realized that pressing F1 (zoom) or F2 (high contrast) will trigger the rendering of the correct amount of characters entered. After that a few new keystrokes are rendered fine but then it stops after about 1-2 seconds. I can repeat this process several times.

### General notes:

I can successfully login by entering the full password and press Enter, but the login dialog will not indicate that any characters have been entered as password.

I installed this system in December 2017 and have been using it a couple of times per month and have never seen this problem before until a few days ago. I've rebooted the computer several times and the problem persists.

dom0 is up-to-date (lightdm 1.10.6-4.fc23 for instance).

### Hardware:
```
$ lspci
00:00.0 Host bridge: Intel Corporation Device 5904 (rev 02)
00:02.0 VGA compatible controller: Intel Corporation Device 5916 (rev 02)
00:04.0 Signal processing controller: Intel Corporation Skylake Processor Thermal Subsystem (rev 02)
00:14.0 USB controller: Intel Corporation Sunrise Point-LP USB 3.0 xHCI Controller (rev 21)
00:14.2 Signal processing controller: Intel Corporation Sunrise Point-LP Thermal subsystem (rev 21)
00:15.0 Signal processing controller: Intel Corporation Sunrise Point-LP Serial IO I2C Controller #0 (rev 21)
00:15.1 Signal processing controller: Intel Corporation Sunrise Point-LP Serial IO I2C Controller #1 (rev 21)
00:16.0 Communication controller: Intel Corporation Sunrise Point-LP CSME HECI #1 (rev 21)
00:1c.0 PCI bridge: Intel Corporation Device 9d10 (rev f1)
00:1c.4 PCI bridge: Intel Corporation Sunrise Point-LP PCI Express Root Port #5 (rev f1)
00:1c.5 PCI bridge: Intel Corporation Sunrise Point-LP PCI Express Root Port #6 (rev f1)
00:1d.0 PCI bridge: Intel Corporation Sunrise Point-LP PCI Express Root Port #9 (rev f1)
00:1f.0 ISA bridge: Intel Corporation Device 9d58 (rev 21)
00:1f.2 Memory controller: Intel Corporation Sunrise Point-LP PMC (rev 21)
00:1f.3 Audio device: Intel Corporation Device 9d71 (rev 21)
00:1f.4 SMBus: Intel Corporation Sunrise Point-LP SMBus (rev 21)
3a:00.0 Network controller: Qualcomm Atheros QCA6174 802.11ac Wireless Network Adapter (rev 32)
3b:00.0 Unassigned class [ff00]: Realtek Semiconductor Co., Ltd. RTS525A PCI Express Card Reader (rev 01)
3c:00.0 Non-Volatile memory controller: Toshiba America Info Systems Device 0115 (rev 01)
```

### "User installed" dom0 packages:
```
$ sudo dnf history userinstalled
Packages installed by user
cryptsetup-1.7.2-1.fc23.x86_64
dnf-1.1.10-1.fc23.noarch
dosfstools-3.0.28-3.fc23.x86_64
efibootmgr-0.12-2.fc23.x86_64
i3-1000:4.12-5.fc23.x86_64
i3-settings-qubes-1.2-1.fc23.x86_64
kde-partitionmanager-1.2.1-6.fc23.x86_64
kernel-1000:4.4.14-11.pvops.qubes.x86_64
lvm2-2.02.132-2.fc23.x86_64
```

---

**Comment by anadahz** [comment]
> Affected component(s):
lightdm?

According to the user installed dom0 packages it could be related to i3lock (i3 WM screen locker).

> I can successfully login by entering the full password and press Enter, but the login dialog will not indicate that any characters have been entered as password.

The option `--no-lock-indicator` (in case you are using `i3lock`) does exactly this; disables the unlock indicator

**Comment by labanskoller** [comment]
Hi, @anadahz! Thanks for helping me by suggesting what has caused me problems.

> According to the user installed dom0 packages it could be related to i3lock (i3 WM screen locker).
> 
> > I can successfully login by entering the full password and press Enter, but the login dialog will not indicate that any characters have been entered as password.
> 
> The option `--no-lock-indicator` (in case you are using `i3lock`) does exactly this; disables the unlock indicator

I installed the package `i3` in my first QubesOS month but have only tried it a few times. I've used XFCE as my window manager many months without the problem described in this bug report. I don't use `i3lock`.

Just to rule out that the package `i3` and its dependencies caused my problem, I've removed it and rebooted the computer. The problem persists. I've also upgraded all dom0 packages to the latest version and rebooted again and that didn't help me either.

My list of user installed packages is now as follows:
```
$ sudo dnf history userinstalled
Packages installed by user
cryptsetup-1.7.2-1.fc23.x86_64
dnf-1.1.10-1.fc23.noarch
dosfstools-3.0.28-3.fc23.x86_64
efibootmgr-0.12-2.fc23.x86_64
kde-partitionmanager-1.2.1-6.fc23.x86_64
lvm2-2.02.132-2.fc23.x86_64
```

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 has reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
