### ISSUE TITLE
hwclock: ioctl() to /dev/rtc to turn on update interrupts failed unexpectedly: Input/Output error

### ISSUE THREAD

**Issue by 99ninetynine** [QubesOS/qubes-issues#4266]
### Qubes OS version:

Qubes release 4.0 (R4.0) / Coreboot 4.8.1

### Affected component(s): 

dom0

---

### Steps to reproduce the behavior:

``dom0 : qvm-sync-clock``

``hwclock: ioctl() to /dev/rtc to turn on update interrupts failed unexpectedly: Input/Output error``

### Expected behavior:

-

### Actual behavior:

-

### General notes:

time has changed only after the turn off laptop at night
similar problem
https://forums.puri.sm/t/hardware-clock-is-losing-time/2499
replacing CMOS battery do not solve the problem
I can not understand this is a problem with my hardware or with Qubes/coreboot.
if you load any live CD then there are no such problems with hwclock

---

**Comment by marmarek** [comment]
I see the same on my X230 with coreboot. AFAIR it worked before, so it's probably caused by some kernel/xen update.

**Comment by HW42** [comment]
In case you need to set your RTC on a buggy kernel: You can work around the problem by passing `--directisa` to `hwclock`.

It also only affects some models (i.e. I have systems where I got this problem with "newer" kernels (don't remember the version) and other it seems to work fine).

**Comment by rustybird** [comment]
Looks similar to https://github.com/karelzak/util-linux/issues/543, but in our case the RTC_UIE_ON ioctl returns EIO (which doesn't trigger the util-linux fallback code).

**Comment by vladimir-lu** [comment]
I have a Purism Librem 13v2 - don't think I had problems before updating from 4.14.57-1 to 4.14.67-1 but I am travelling at the moment so will verify next week. The `--directisa` workaround works.

**Comment by marmarek** [comment]
Thanks for providing those versions! In that range I see only one relevant commit: https://github.com/torvalds/linux/commit/6a929b97b77. But it returns `ENODEV` or `EINVAL`, not `EIO`. I've identified that `EIO` is from here: https://github.com/torvalds/linux/blob/v4.14/drivers/rtc/rtc-cmos.c#L412 (that's the only EIO in this code path). Looks like IRQ is missing. 

On working system:
```
$ cat /sys/bus/pnp/drivers/rtc_cmos/00:03/resources
state = active
io 0x70-0x77
irq 8
```

On broken one (same kernel, but different hardware - x230 with coreboot):
```
$ cat /sys/bus/pnp/drivers/rtc_cmos/00:03/resources
state = active
io 0x70-0x77
```

No idea why is this happening, can be a change in totally different kernel part. Cursory look at git log between those two version doesn't yield anything obvious (related to IRQ or Xen).

**Comment by sptankard** [comment]
I seem to be experiencing this problem since yesterday, after performing some upgrades. I think kernel was upgraded in both dom0 and in fedora-28 template. And also xen, in dom0. 
This is also a Librem 13v2. But I never had an issue with this until yesterday.

Before finding this bug report (by searching the dom0 hwclock error), I was searching for qubes and ntp in general. I noticed that sys-net on my system did not have `clocksync` service available. Not sure if is is supposed to, based on default?

**Comment by marmarek** [comment]
I think this dom0 kernel patch may help: https://lore.kernel.org/lkml/1553025739-92245-1-git-send-email-jennifer.herbert@citrix.com/
