### ISSUE TITLE
SAMBA unpleasantly broken on Debian VMs  with kernel 4.14.57-1, kernel 4.9.56-21 and below unaffected 

### ISSUE THREAD

**Issue by tonsimple** [QubesOS/qubes-issues#4270]
### Qubes OS version:

R 3.2

### Affected component(s): 

Debian VMs irrespective of debian version

specifically affected are samba server&client, samba client affected especially strongly

---

### Steps to reproduce the behavior:

Have a samba server serving something from one VM, and a samba client mounting it from another VM

the client invocation would be something like 
_sudo mount.cifs //[SERVER-VM-IP/MYSHARE /rw/SHAREMOUNT --verbose -o  uid=user,gid=user,username=[samba_user_username],password=[samba_user_password],domain=WORKGROUP,vers=3.0_

note the vers line, it kind of matters here

### Expected behavior:

samba to get mounted and be writable

### Actual behavior:

samba share mounts, but attempt to [edited] write to the share or delete file from the share [/edited] causes the VM to crash instantly, with no logs formed.

Also sometimes instantly crashes the server.

**Additional symptom:**
there is CIFS VFS: ioctl error in smb2_get_dfs_refer rc=-2" in dmesg

**Additional symptom 2:**

invoking it with vers 1.0 does not produce error in dmesg and does not cause crashes but samba 1.0 is bad news.

### General notes:

Using kernel 4.9.56-21 works okay.

The issue appears to be a debian issue or related to it based on log behavior and some of the bug's behavior ([link related](https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1748689) ) but the "whole machine crash" is not described in debian issue linked, so there may be Qubes-specific stuff here.

---

**Comment by marmarek** [comment]
Check `/var/log/xen/console/guest-VMNAME.log` for some more details.

**Comment by arjan-s** [comment]
This is a known issue in kernels 4.14.55 - 4.14.58

**Comment by andrewdavidwong** [comment]
Closing as "not our bug." If you believe this is a mistake, please leave a comment, and we'll be happy to take another look. Thank you.
