### ISSUE TITLE
Im locked out of my machine. Qubes USB port problem.

### ISSUE THREAD

**Issue by anobody1212** [QubesOS/qubes-issues#4277]
### Qubes OS version:

i have been using Qubes for a long time now and really enjoy it, however, recently I came across a issue that is driving me insane. You see, I rebooted my computer (which is fully encrypted with Qubes) and once the machine started back up I got sent to the Drive password screen like always. At this page, my computer doesn’t recognize my keyboard at all. I typed my password over and over again (made sure it was right) however nothing seems to happen. At first I thought maybe the page is frozen but it wasn’t, the little loading line at the bottom of the screen was moving right indicating it’s loading until it reaches the end and fully stops. I know it’s not the keyboard that is the issue as I tried multiple USB keyboards and they all work well when I’m on my computers boot menus or just scrolling through my setup (F2). Can you please help me resolve this issue? Or if not, lead me towards the right way to get this resolved.

I looked all over for a similar post about this issue and couldn't find one, so if there is one please link me to it and I'll delete this one. Also, I am not very knowledgeable in this field so if you could be specific when suggesting a fix, it will be very appreciated  

### Affected component(s): 

---

### General notes:

---

**Comment by pgerber** [comment]
This sounds to me like you're using an USB qube (sys-usb) but you have not allowed the use of USB keyboards. [This security warning](https://www.qubes-os.org/doc/usb/#security-warning-about-usb-input-devices) should explain why USB keyboards are not allowed by default. The instructions on how to enable USB keyboards can be found [here](https://www.qubes-os.org/doc/usb/#how-to-use-a-usb-keyboard) but without a keyboard, you'll need some kind of rescue system to enable it.

Your keyboard, not the USB keyboards, is it a built-in keyboard on a notebook? Does it not work at all (in BIOS, boot menu, etc.) or just in Qubes OS? Could a recent update have caused the issue?

**Comment by pgerber** [comment]
Based on your initial post, I understand that you had a working keyboard on that machine at some point. How was it connected? USB also or PS/2?

**Comment by anobody1212** [comment]
I had both a keyboard and mouse connected using USB. They always worked fine and I never had a problem with them until now. 
-- 
 Securely sent with Tutanota. Get your own encrypted, ad-free mailbox: 
 https://tutanota.com


Sep 6, 2018, 4:28 PM by notifications@github.com:

**Comment by pgerber** [comment]
Did your setup change in any way? Any configuration changes or installation of updates?

**Comment by anobody1212** [comment]
Non that i know of. Only sort of installations i do on my setup is updating my VMs templates and domo0

**Comment by pgerber** [comment]
Perhaps a recent kernel update broke something. Have you tried selecting a older Linux kernel? There should be  an "advanced options" or similar in the boot menu that allows you to do that.

Also, are you running Qubes 4?

**Comment by anobody1212** [comment]
Yes i am running Qubes 4. When i go to my boot menu my current options are:
network
M.2 PCIe SSD
Qubes
Windows boot manager
Onboard NIC (IPV4) & (IPV6)

**Comment by pgerber** [comment]
Looks like an EFI boot menu to me. Didn't get EFI working here so not sure how you get to the right menu. Could it be though, that another menu is shown when you select Qubes?

**Comment by anobody1212** [comment]
When i select Qubes all the line of code load up on my screen and i get prompted to the Disk Password page where i cant type my password.

**Comment by pgerber** [comment]
That's very odd, could it be that the menu is hidden? Can you try [this](https://askubuntu.com/questions/16042/how-to-get-to-the-grub-menu-at-boot-time)? You'll have to hit shift (or whatever the right key actually is) just after selecting Qubes in the first menu. We've some people at work using Ubuntu, which doesn't display a boot menu by default, and in my experience it can take a few tries to get the menu.

By any chance, do you remember changing the default Grub settings?

**Comment by anobody1212** [comment]
I tried this multiple times after selecting Qubes in the boot menu with ESC SPACE and SHIFT but i notice that once the code finishes loading on my screen my keyboards lights turn off, meaning my keyboard from that point on is unresponsive. For the second part i am not sure but i do not think so

**Comment by andrewdavidwong** [comment]
Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this does not appear to be suitable for `qubes-issues`. We ask that you please send this to the `qubes-users` [mailing list](https://www.qubes-os.org/support/) instead. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a brief comment explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.
