### ISSUE TITLE
Incorrect SELinux label of the domU qrexec daemon

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#4279]
### Qubes OS version:

`Qubes release 4.0 (R4.0)`

### Affected component(s): 

qubes-core-admin

---

### Steps to reproduce the behavior:

Start a VM (only tested with Fedora 28) with SELinux enabled

### Expected behavior:

Qrexec-daemon starts normally

### Actual behavior:

qrexec daemon won’t start

### General notes:

One of the culprits is that the domU qrexec daemon is incorrectly labeled, and cannot do its job.  I believe that setting it to `unconfined_exec_t` would fix it.

---

### Related issues:

#4278, #4239

**Comment by esote** [comment]
@DemiMarie @andrewdavidwong Try the steps I did in #4239.

**Comment by marmarek** [comment]
Fixed by https://github.com/QubesOS/qubes-core-qrexec/pull/84
