### ISSUE TITLE
Remove the need for the out-of-tree u2mfn kernel module

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#4280]
### Qubes OS version:

R4.0

### Affected component(s): 

qubes-core-admin

---

### Steps to reproduce the behavior:

Check the taint status of a domU kernel

### Expected behavior:

Kernel is not tainted

### Actual behavior:

Kernel is tainted by an out-of-tree module.

### General notes:

This is due to the u2mfn module.  Either this module should be upstreamed, or the need for it should be eliminated.  Presumably, Xen’s libvchan does not require it.

---

**Comment by marmarek** [comment]
> Presumably, Xen’s libvchan does not require it.

It doesn't. But gui-agent in R4.0 does. It will be solved in R4.1: https://github.com/QubesOS/qubes-gui-agent-linux/pull/34
