### ISSUE TITLE
Use Xen’s libvchan, not our own fork

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#4281]
### Qubes OS version:

R4.0

### Affected component(s): 

Qubes core

---

### Steps to reproduce the behavior:

Observe that Qubes has its own copy of libvchan

### Expected behavior:

Qubes uses Xen’s copy of libvchan

### Actual behavior:

Qubes has its own version of libvchan

### General notes:

Using the upstream version is desireable because it has more features (such as domU-to-domU vchans), and does not require the u2mfn kernel module, if I understand correctly.

---

**Comment by marmarek** [comment]
Our libvchan is a [shim over the upstream one](https://github.com/QubesOS/qubes-core-vchan-xen/blob/master/vchan/io.c), to provide Xen-agnostic API (being able to replace the libvchan with for example KVM version).
BTW, historically, the Xen's libvchan is a (improved) fork of Qubes one.
