### ISSUE TITLE
Ubuntu templates have unattended upgrade installed by default

### ISSUE THREAD

**Issue by unman** [QubesOS/qubes-issues#4285]
### Qubes OS version:

R4.0

### Affected component(s): 

Ubuntu templates

---

### Steps to reproduce the behavior:

Install Ubuntu Template

### Expected behavior:

Qubes and templates will not update themselves.

### Actual behavior:

Unattended upgrades installed by default.
apt-get timers triggered on qube start.

### General notes:

Obviously related to #2621 - may be that purging package and applying config solution is best.

---

### Related issues:

#2621

**Comment by marmarek** [comment]
I guess it's recommended by some other package. https://packages.ubuntu.com/xenial/unattended-upgrades doesn't have reverse dependencies, @unman can you check on installed system what pulled it in?

**Comment by unman** [comment]
It's pulled in by python3-software-properties, which is a dependency of software-properties-common, part of the Ubuntu package management system.
As I indicated in the title, it's installed and enabled by default in a standard Ubuntu (post Xenial) install. In *this* case I think it's best to override the distribution default.
