### ISSUE TITLE
Cannot build +gnome variant for Debian

### ISSUE THREAD

**Issue by unman** [QubesOS/qubes-issues#4286]
### Qubes OS version:

R4.0

### Affected component(s): 

Qubes Builder

---

### Steps to reproduce the behavior:

Select stretch+gnome from builder setup.
Build Template

### Expected behavior:

Template will contain gnome applications

### Actual behavior:

Template seems identical to basic Stretch template.
No extended Gnome applications included.

### General notes:

Tried build following discussion in #4195 and #1781

---

**Comment by marmarek** [comment]
I think it relies on [`TEMPLATE_FLAVOR_DIR += +gnome:$$SCRIPTSDIR/gnome`](https://github.com/QubesOS/qubes-builder/blob/master/example-configs/templates.conf#L272) in `builder.conf`

Do you have it?

**Comment by unman** [comment]
yes indeed

**Comment by marmarek** [comment]
TEMPLATE_FLAVOR_DIR is broken. If you look at the process list during the build, you'll find `sudo env -i ... TEMPLATE_FLAVOR_DIR=+gnome:CRIPTSDIR/gnome ...`. `$S` is missing, or actually, expanded `$SCRIPTSDIR`. Adding more dollars doesn't help (`TEMPLATE_FLAVOR_DIR=+gnome:/gnome`). 

Ideas welcome. It's about Makefile in linux-template-builder.

**Comment by unman** [comment]
I've had a quick look at this, and it seems as if it would affect *any* variant build.

There seem to be two issues:
First, we need "$$$$" in builder.conf so that we get $SCRIPTSDIR in template_builder. (That seems to be derived from examples/templates.conf.)
Second, as far as I can see, SCRIPTSDIR is never set, so even if the variable is correctly referenced in template-builder, it drops out at the build stage.

From the docs it looks as if SCRIPTSDIR should be retained as well as TEMPLATE_SCRIPTS set in Makefile.builder (BuilderPluginAPI refers).

I've put in two PRs to fix this.

**Comment by marmarek** [comment]
The sole purpose of `$TEMPLATE_SCRIPTS` is to have less ambiguous name for BuilderPluginAPI. But internally everything use `$SCRIPTSDIR`. Maybe we should deprecate the later and use `$TEMPLATE_SCRIPTS` everywhere?
Or at least in templates.conf (then exporting `SCRIPTSDIR` should be unnecessary).

**Comment by unman** [comment]
We need to have the (ugly) `$$$$` because we want `$TEMPLATE_SCRIPTS` in linux-template-builder Makefile. 
This, combined with exporting `TEMPLATE_FLAVOR_DIR` would do it.
An alternative would be to explicitly set `SCRIPTSDIR` at an early stage, so the variable is deferenced and remove the overwrite in linux_template_builder.

**Comment by marmarek** [comment]
> We need to have the (ugly) `$$$$` because we want `$TEMPLATE_SCRIPTS` in linux-template-builder Makefile.

Ok, lets do this, instead of $SCRIPTSDIR there. Later we may fix it some better way. Could you update https://github.com/QubesOS/qubes-builder/pull/62?

**Comment by marmarek** [comment]
Does it work now? @unman

**Comment by unman** [comment]
All good.
Closing now
