### ISSUE TITLE
kernel-qubes-vm 4.17 and 4.18 don't work for sys-whonix/whonix-gw based vms

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#4293]
[temporary_issue_user](https://forums.whonix.org/u/temporary_issue_user/summary) had [reported](https://forums.whonix.org/t/kernel-qubes-vm-4-17-and-4-18-dont-work-for-sys-whonix-whonix-gw-based-vms/5867)

> it appears the -j REDIRECT is blackholed somehow. on 4.16 and 4.14 I see the INPUT rules get hit but in 4.17 and 4.18 the INPUT rules are not hit.

I didn't verify it myself yet. But sounds scary. Rings a bell?

I guess it would be spotted by developer testing before uploading a new kernel to Qubes testing?

**Comment by marmarek** [comment]
I think it's https://github.com/QubesOS/qubes-issues/issues/4305, fixed recently.
