### ISSUE TITLE
Simplify keyboard layout switching - input language

### ISSUE THREAD

**Issue by QubyTester** [QubesOS/qubes-issues#4294]
### Qubes OS version:

3.2, 4.0

### Affected component(s): 

Qube Manager, ibus-xxx?

---

### Steps to reproduce the behavior:

1. Select the target VM in Qube Manager,
2. Click on the Qube Manager's "Set keyboard layout" button
3. Scroll through *MANY* languages and apply
4. When done typing in a different language, return to Qube Manager
5. Click on the Qube Manager's "Set keyboard layout" button
6. Click "none"
7. Repeat these steps <b>each time</b> you need to switch the languages

### Expected behavior:

Step 3. above: Click among *JUST a FEW* languages (previously selected)

### General notes:

If Qube Manager is the place to quickly switch the keyboard layouts, then it should show only a few keyboard layouts previously narrowed down by a user. (Most OS'es offer selecting the few needed layout choices in the general settings, and then subsequently their user quick-switches only between the few chosen layouts.) Switching layouts in Qubes should be quick as well, and not just offer a long general list of layouts <b>every time</b> you switch.
The initial keyboard layout preference could be set via:
   - A wizard / preference (during the installation? anytime after installation?), or
   - Manually - document how users can edit down the Qube Manager's list of keyboard layouts.

---

### Related issues:

Allow assigning a hot-key combination for each VM's keyboard layout.
The current "Language Localization" doc [https://www.qubes-os.org/doc/language-localization/ ] is deceitful because it is merely "How to set up pinyin input" and leaves the rest of the world wondering. It offers to dive into the Big Bro Google's qubes-users thread, and even that to no avail.
What if the 2nd language is not Pinyin - can ibus-pinyin example still be used? Else, can the listed command(s) be changed to load a different language?

**Comment by taradiddles** [comment]
@QubyTester:

> Switching layouts in Qubes should be quick as well

[This doc](https://github.com/Qubes-Community/Contents/blob/master/docs/localization/keyboard-multiple-layouts.md) may help until there are better options...

**Comment by marmarta** [comment]
I've got a proposal how to fix this:
- enable propagating dom0 keyboard layout to all VMs by default
- in qube manager, change the switch keyboard layout menu to one that shows the following options:
   - use default (checked by default)
   - select layouts (that allows you to set a global list of quickly available layouts)
   - layouts selected above for quick switching between them

**Comment by marmarta** [comment]
also related: https://github.com/QubesOS/qubes-issues/issues/1396

**Comment by tlaurion** [comment]
@marmarta
> enable propagating dom0 keyboard layout to all VMs by default

Would be awesome. Having both ca and usa keyboard, switching keyboards in VM with alt-shift would behave the same way userns normally expect keyboard layouts to switch.
