### ISSUE TITLE
some DVM Templates should be non-networked by default for better security?

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#4296]
Should some DVM Templates should be non-networked by default?

Perhaps default DVM Templates should be non-networked by default?

Reasoning: similar reasoning like for making TemplateVMs non-networked by default. A compromised DVM Template would be inherited by all DispVMs based on that DVM Template.

Would it therefore make sense to treat a DVM Template more like a TemplateVM?

**Comment by unman** [comment]
@adrelanos How does this differ from #4226 ?

**Comment by adrelanos** [comment]
Duplicate.
