### ISSUE TITLE
Rare full networking fail (routes maybe?) when starting VM with lots of /rw/config/rc.local housekeeping. Race?

### ISSUE THREAD

**Issue by tonsimple** [QubesOS/qubes-issues#4297]
### Qubes OS version:

R 3.2

### Affected component(s): 

Reproduced on Debian VMs. Never tested on Fedora VMs

---

### Steps to reproduce the behavior:

Have a VM with lost of housekeeping happening via /rw/config/rc.local and via qubes-firewall-user-script (VMs that do port forwarding or have br interfaces being brought up and configured are particularly affected, as are VMs that act as VPN VMs, initially issue was only observed in the later and reported https://github.com/QubesOS/qubes-issues/issues/3735  )

Start it up.

Occasionally, while all interfaces are present and firewall rules are in place, the networking just won't work at all.

For non-VPN VMs restarting the VM helps. For VPN VMs it may get more involved.

### Expected behavior:

Networking always working when it is expected to be working

### Actual behavior:

Very rarely (for non-VPN) and somewhat more frequently (for VPN VMs) the networking "does not take"

Since interfaces are present and firewall rules are all "as intended", I suspect it might be a route issue...

### General notes:

For non-VPN VMs the issue is solved by just restarting the VM

For VPN VMs (configured as [APP-VM]<->FirewallVM<->VPN-VM<->sys-net) the process is more involved and requires restarting the entire chain right up to the sys-net (the APP VMs, the firewall VM and the VPN VM), which is more annoying.

Starting your VPN-related VM chain slowly one by one and giving it a 1-2 second rest between VM starts vastly reduces incidence of this behavior in VPN-related conditions.

App-VM case is very rare (only observed it twice so far) so I kind of suspect it might be some sort of a race condition.

---

### Related issues:

https://github.com/QubesOS/qubes-issues/issues/3735

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 has reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
