### ISSUE TITLE
Trapped out of my machine. USB not detected

### ISSUE THREAD

**Issue by anobody1212** [QubesOS/qubes-issues#4300]
### Qubes OS version:

Hello Qubes community,
I have been using Qubes OS for a while now on my PC desktop and never had any issues nor any complaints using it, but now i am stock out of my machine. I encrypted my computer with Qubes and set a strong Drive password in order to get inside the system, followed up by another password and then you have complete access to all the VMs. I think that a recent update made my qubes system not recognize any USB connections to my PC as once qubes boots up i lose ability to use my keyboard and mouse among other things, leaving me unable to enter to enter my drive password. I wanted to try using a PS/2 keyboard but my PC doesn't have a PS/2 connection port. I am able to navigate through my bios menu and setup settings before starting Qubes which goes to show its not the keyboard to blame, and yes, i did try using a different keyboard. Is there any way i can fix this issue?

### Affected component(s): 

---

### General notes:

---

**Comment by anobody1212** [comment]
running on qubes 4

**Comment by andrewdavidwong** [comment]
Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this does not appear to be suitable for `qubes-issues`. We ask that you please send this to the `qubes-users` [mailing list](https://www.qubes-os.org/support/) instead. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a brief comment explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.
