### ISSUE TITLE
Port forwarding

### ISSUE THREAD

**Issue by AlphaMufasaOmega** [QubesOS/qubes-issues#4302]
### Qubes OS version:

$4.0
Basically I have a router that my wifi is connected to and I am trying to learn how to successfully Port forward in msfconsole from qubes 4.0 Obviously there is a net-vm ans a sys-usb vm and it is hard to see whether or not my applications are working due to this conundrum :) I would  also like to put the a listener through whonix if at all possible!

### Affected component(s): 

msfconsole
sys-net vm
firewall vm
whonix vms

---

### Expected behavior:

Port forwarding works the same as a windows machine connected to wifi

### Actual behavior:

Can't tell if I have to change my tactics for port forwarding from a normal computer due to the fact that there are so many virtual machines

### General notes:

No response form a listener due to the fact that there are multiple port forwarding obstacles.... infected program seems to be functioning normally

---

**Comment by awokd** [comment]
This isn't covered in https://www.qubes-os.org/doc/firewall/#port-forwarding-to-a-qube-from-the-outside-world ?

**Comment by AlphaMufasaOmega** [comment]
omg i luv you i will get back to you and let you know if this worked!

**Comment by w1k1n9cc** [comment]
I see you found the [script](https://gist.github.com/Joeviocoe/6c4dc0c283f6d6c5b1a3f5af8793292b).

**Comment by awokd** [comment]
> I can't get it to work

I haven't tried the script. Did you mark it executable? How about the manual procedure described in the doc.?

**Comment by unman** [comment]
@AlphaMufasaOmega I suggest you take this over to the qubes-users mailing list: it's more appropriate there, and more people will see it.

Please be more precise in describing your problems.
The issue you seem to have now is in using that script: as @awokd says, you will need to mark that script as executable, using chmod +x .

**Comment by andrewdavidwong** [comment]
Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this does not appear to be suitable for `qubes-issues`. We ask that you please send this to the `qubes-users` [mailing list](https://www.qubes-os.org/support/) instead. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a brief comment explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.
