### ISSUE TITLE
Installing a proper firewall distribution

### ISSUE THREAD

**Issue by kaspro** [QubesOS/qubes-issues#4303]
Giving several restrictions around the qubes- internal firewalling system (~40 rules, no DNS etc.) and the additional powers of other firewall distributions, I was thinking about puitting something like pf/opnsense, ipfire or similar as a replacement to "sys-firewall".
However, so far all attempts I've made failed - probably also because I couldn't find an in-depth documentation about the internal routing and NATting etc.
Did anyone attempt something like this already?
Any hints/gotchas?

**Comment by andrewdavidwong** [comment]
Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this does not appear to be suitable for `qubes-issues`. We ask that you please send this to the `qubes-users` [mailing list](https://www.qubes-os.org/support/) instead. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a brief comment explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.
