### ISSUE TITLE
Allow explicitly disabling encrypted backups

### ISSUE THREAD

**Issue by strugee** [QubesOS/qubes-issues#4308]
### Qubes OS version:

R4.0

### Affected component(s): 

Qubes Backup

---

### Steps to reproduce the behavior:

1. Use `qvm-backup` to create a backup
2. Try to disable the encryption, for example to pipe into a deduplicating system like [ZBackup](http://zbackup.org/)

### Expected behavior:

I should be able to override the usual requirement for an encryption passphrase.

### Actual behavior:

No such option exists. I tried creating an empty file and passing it to `--passphrase-file`, but that triggered [an exception in qubes-core-admin](https://github.com/QubesOS/qubes-core-admin/blob/5756e870bd91ddd8ed4a81e79881adeec7d8d78a/qubes/api/admin.py#L1376).

### General notes:

I certainly sympathize with the desire to require an encryption key by default; I'd do the same. But at the same time I know what I'm doing; I know ZBackup will do the encryption for me, _after_ it's done the deduplication. Perhaps this can just be an option in `qvm-backup` and not Qubes Manager? That way power users can get at it but the graphical option still has no option to disable encryption.

In any case, thank you for maintaining Qubes! It's much appreciated :)

**Comment by marmarek** [comment]
One of design decision of qvm-backup in R4.0 is to not allow to extract unencrypted data from dom0. Also, right now encryption and integrity protection is done in the same step (using `scrypt` tool). And we definitely don't want to allow not integrity protected backups.

On the other hand, you may try `qvm-backup --compress-filter`. It will get called for each VM's image separately and should read from stdin and write to stdout.

Alternatively, see #858 , there are many ideas and scripts to solve similar problem.

**Comment by zaz** [comment]
In light of #8308 and seeing as [people are finding workarounds to Qubes not allowing unencrypted backups](https://forum.qubes-os.org/t/guide-incremental-backup-using-the-official-backup-system/25792), perhaps it's time to revisit this?

Perhaps allow unencrypted backups with a warning?
