### ISSUE TITLE
IOMMU fails for entries beyond 0x80

### ISSUE THREAD

**Issue by JarrahG** [QubesOS/qubes-issues#4309]
### Qubes OS version:

R4.0

### Affected component(s): 

AMD IOMMU on Threadripper/X399

---

### Steps to reproduce the behavior:

Attempt to boot Qubes R4.0 on AMD Threadripper. I am using the ASRock Taichi X399 motherboard. 

### Expected behavior:

Qubes boots with IOMMU Support

### Actual behavior:

IOMMU is disabled with the following error message:
```
(XEN) IVHD Error: IO-APIC 0x81 entry beyond bounds
(XEN) AMD-Vi: Error initialization
(XEN) I/O virtualisation disabled
```

### General notes:

As far as I can work out, this is occuring as the version of Xen used in Qubes does not have the following patch: 
https://github.com/xen-project/xen/commit/f948ce4371cd935d0075d8c60309660bdd5ca178

The first version of xen that I can find including this patch is 4.9.2. I'll be attempting a build of Xen 4.9.2 sometime after next week but was looking for advice as to whether porting the qubes patches forward or porting the above patch back would be more beneficial and easier. 

---

### Related issues:

---

Thanks for your help and time working on Qubes.

**Comment by JarrahG** [comment]
Thanks @marmarek for the patch. I have managed to get it compiled and installed, and can confirm that it solves the issue. 

Would it be possible to get this patch upstreamed into the standard qubes repos for the next update? Cherry-picking your patch onto the current QubesOS/vmm-xen head compiled fine once I worked out the build system. 

Current output:
`(XEN) AMD-Vi: IOMMU Extended Features:
(XEN)  - Peripheral Page Service Request
(XEN)  - NX bit Supported
(XEN)  - Guest Translation
(XEN)  - Invalidate All Command
(XEN)  - Guest APIC supported
(XEN)  - Performance Counters
(XEN) AMD-Vi: IOMMU 0 Enabled.
(XEN) AMD-Vi: IOMMU Extended Features:
(XEN)  - Peripheral Page Service Request
(XEN)  - NX bit Supported
(XEN)  - Guest Translation
(XEN)  - Invalidate All Command
(XEN)  - Guest APIC supported
(XEN)  - Performance Counters
(XEN) AMD-Vi: IOMMU 1 Enabled.
(XEN) I/O virtualisation enabled
(XEN)  - Dom0 mode: Relaxed
`

**Comment by andrewdavidwong** [comment]
> Would it be possible to get this patch upstreamed into the standard qubes repos for the next update? Cherry-picking your patch onto the current QubesOS/vmm-xen head compiled fine once I worked out the build system.

It will eventually get there through the normal Qubes development workflow:

https://www.qubes-os.org/doc/development-workflow/

**Comment by vogelfreiheit** [comment]
I got it working too with the unstable repo but somehow after an update it all broke apart again.

How can I trigger a regen of the dracut initramfs images *and* load a HVM and related packages that contain the fix? Needless to say I can't do this from inside the Qubes system as it isn't possible to get networking to function without IOMMU.

**Comment by JarrahG** [comment]
Chances are that was the recent updates to xen released. 

While not recommended, you can change the virtualisation mode of sys-net to pv to get it to boot without IOMMU. That will allow you to pull down any updates and install them from inside qubes. Just remember to change it back when you get IOMMU working.

**Comment by vogelfreiheit** [comment]
Confirmed: neither marmarek's nor the regular repo include the fix, marmarek's has it only in a xen-4.8-amd... branch but it was never cherry picked or merged into stable. Not sure why this issue was closed when it is definitely still present. No packages built with the default builder configurations will ever contain the fix, as it was never merged into the branches.

**Comment by andrewdavidwong** [comment]
@vogelfreiheit:
> Not sure why this issue was closed when it is definitely still present.

What do you mean? This issue is open and has never been closed.

**Comment by vogelfreiheit** [comment]
My bad, I saw the dup right before and forgot this was the main issue. Do you need people to test any further AMD patches? I'm about to build the current branch from m' after cherry picking the issue. 

Is there a qubes-dev channel or such somewhere? (besides the main one) It's unrelated to this issue but I wanted to check in with the nouveau side of things, as f25 is EOL and their version does not have support for Pascal based cards/10xx. The AMD EPYC support and that are probably the main outstanding issues I have in this particular system and I can probably find enough motivation to help tackle both.

**Comment by andrewdavidwong** [comment]
> Do you need people to test any further AMD patches?

Just whichever ones land in the testing repos. Our general testing guidelines apply here:

https://www.qubes-os.org/doc/testing/

> Is there a qubes-dev channel or such somewhere? (besides the main one)

Not that I'm aware of. Just the main one:

https://www.qubes-os.org/support/#qubes-devel

> It's unrelated to this issue but I wanted to check in with the nouveau side of things, as f25 is EOL and their version does not have support for Pascal based cards/10xx. The AMD EPYC support and that are probably the main outstanding issues I have in this particular system and I can probably find enough motivation to help tackle both.

Sounds like that would probably be appropriate to discuss on qubes-devel.

**Comment by vogelfreiheit** [comment]
Is there an official build that contains the fix? Seems like somehow the builder re-based the source and it was actually built without the cherry picked patch. There goes an hour or two setting up a fresh Fedora building machine.

**Comment by andrewdavidwong** [comment]
> Is there an official build that contains the fix? Seems like somehow the builder re-based the source and it was actually built without the cherry picked patch. There goes an hour or two setting up a fresh Fedora building machine.

Probably not yet. @marmarek would be the one to ask about this.

**Comment by vogelfreiheit** [comment]
Let's wait then for his comment, I'm running the current master branch from git with the cherrypicked patch with no issues as far as IOMMU is involved.

**Comment by marmarek** [comment]
My comment: the patch looks harmless enough (even though it's long) to include in R4.0. Will be part of Xen 4.8.4-8 packages.
