### ISSUE TITLE
Impossible to start any VM, only dom0 is up at the beginning

### ISSUE THREAD

**Issue by Noitty** [QubesOS/qubes-issues#4310]
### Qubes OS version:

Qubes release 4.0 (R4.0)

### Affected component(s): 

All the VMs do not start

---

### Steps to reproduce the behavior:

Install the OS, boot the system, and open the Qube Manager. Only the dom0 is started. Try to start other VMs with this tool. The error message (presented before) appears. Using the command line, it is the same.

### Expected behavior:

The corresponding VMs start correctly.

### Actual behavior:

I have installed the Qubes OS 4.0 in the computer, and  I followed the initial configuration steps. Everything worked correctly, except the fact that after entering in the session, no AppVM is started. Only the dom0 runs correctly and enables to interact with the terminal. 

I have tried to manually start each AppVM through the Qube Manager, but an error appears:
`ERROR: Start failed: invalid argument: could not find capabilities for arch=x86_64 , see /var/log/libvirt/libxl/libxl-driver.log for details`. I have checked the libxl-driver.log, but this one is empty. Starting the AppVM using the command line (`qvm-start -v sys-net`) generates the same error. 

### General notes:

I am using a computer with the following features:
- CPU: AMD Ryzer 2600X (it has AMD-V, but it does not have RVI)
- RAM: 16 GB
- 250 GB SSD

---

### Related issues:

Thanks!

**Comment by marmarek** [comment]
>     * CPU: AMD Ryzer 2600X (it has AMD-V, but it does not have RVI)

This is the problem, RVI (or Intel equivalent) is required for Qubes 4.0, see https://www.qubes-os.org/doc/system-requirements/#qubes-release-4x

**Comment by marmarek** [comment]
Anyway, it's kind of surprising that new AMD CPU have AMD-V but not RVI. I'd expect each not-10-years-old one having AMD-V would also have RVI. Check BIOS settings, maybe it is disabled.

**Comment by Noitty** [comment]
Thank you @marmarek for your quick reply. I thought that this could be the issue. I am also surprised that this kind of CPU has not this option, but I have been googling it and all the sites indicate this. I will also check the BIOS settings. 

Again, thank you for your response!

**Comment by Noitty** [comment]
Hi again. You were right, @marmarek, the problem was in the BIOS settings. I did not know that the AMD-V feature was disabled by default.

For other users that have the same issue, I am using a MSI motherboard, and to enable the virtualization in the BIOS the option "SVM Mode" needs to be enabled.

After this, the Qubes OS 4.0 works perfectly. If you agree, I will try to upload the Hardware Compatibility List with my configuration.

Thanks!

**Comment by Noitty** [comment]
The issue was solved.

**Comment by andrewdavidwong** [comment]
Another user just [reported](https://groups.google.com/d/msgid/qubes-users/e5d19e77-26ec-40d4-8e89-1743257f28cb%40googlegroups.com) what appears to be the same problem.

If possible, we should hint to the user that enabling "SVM Mode" may fix their problem.

Even if that is not possible, we should at least improve the error message and not direct the user to check an empty log for details.
