### ISSUE TITLE
qubes-linux-dom0-updates for Qubes 4.x

### ISSUE THREAD

**Issue by xaki23** [QubesOS/qubes-issues#4315]
fc25 is showing its age. 

xorg-x11-drv-intel from fc28
problem was frequent gui restarts and hard lockups caused by a hyperactive watchdog in the intel drv on a system where use of usb3-storage does cause the system clock to be about 200ms slow per hour (so there _is_ some kind of blocking going on).
the fc28 driver handles the watchdog more gracefully, just a brief gui freeze instead of hard restarts.

xorg-x11-drv-ati from fc26
problem was windows not being rendered on a rotated display, probably https://bugzilla.redhat.com/show_bug.cgi?id=1429825
the fc26 driver resolved the issue.
went with fc26 (v7.9 from v7.7 in fc25) in this case because of major version jump in fc28 (v18.x)

both srpm build cleanly in the chroot-fc25 and require only a single rpm to be replaced each, no update dependencies on other pkgs or kernel or so.

**Comment by marmarek** [comment]
Actually, I think this is actionable already (but it may be because I know the context from irc chat).

**Comment by andrewdavidwong** [comment]
@marmarek: Please add the context, if you can. I have almost no idea what this is talking about.

**Comment by andrewdavidwong** [comment]
Took a guess at the labels.

**Comment by xaki23** [comment]
ups, sorry. will try to add some more context.

Qubes 4.0 dom0 is fc25 which is eol and showing its age by being seriously outdated in places.
sunday i spent another 2h talking a user through doing a xorg driver update to make his fresh Q4 install usable.

for older qubes releases the aging seems to have been worked around with this pkg/mod/repo:

        https://github.com/QubesOS/qubes-linux-dom0-updates

it contains updated versions of drivers, firmware for fc21/fc23 targets (qubes 3.x) and was last updated in january 2017.
to bring this into the Qubes 4.x age, @marmarek asked for specifics on what/why to update.

i opened this issue mostly just to keep the details in one place.
the general qubes issue metadata template did not really fit too well.

**Comment by marmarek** [comment]
I'll use this occasion to fix the old linux-dom0-updates repo layout. Namely, no longer commit binaries (src.rpm) directly to the repository, but download them and verify at build time. `.git` there is already 300MB+... This means the new `release4.0` branch (and `master` too) will be disconnected from its history. Eventually, we'll delete/archive old branches and repository will be back at sane size.

**Comment by marmarek** [comment]
@xaki23 
> went with fc26 (v7.9 from v7.7 in fc25) in this case because of major version jump in fc28 (v18.x)

According to [announcement](https://lists.freedesktop.org/archives/amd-gfx/2018-March/019793.html), it's "only" version scheme change (to be year-based), not a major change. And it's easier for me to get all the packages from the same place. So, I've built both packages from fc28. And uploaded to qubes-dom0-unstable. It would be very helpful if you could test them if they solve the problem.

**Comment by Simon-Davies** [comment]
So performing an update in dom0 with the qubes-dom0-unstable repo enabled will update the Intel drivers.

I thought dom0 was based on fc25 not fc28. Do we need to update dom0 to fc28? 

I'm a bit confused sorry.

**Comment by marmarek** [comment]
> So performing an update in dom0 with the qubes-dom0-unstable repo enabled will update the Intel drivers.

> I thought dom0 was based on fc25 not fc28. Do we need to update dom0 to fc28?

Yes, dom0 is based on fc25. qubes-dom0-update repository contains few newer packages than was in fc25 (here: two video drivers).

**Comment by Simon-Davies** [comment]
I've updated the drivers so will report back on whether this fixes the tearing. Thanks @marmarek
