### ISSUE TITLE
Qubes Manager not starting

### ISSUE THREAD

**Issue by Simon-Davies** [QubesOS/qubes-issues#4316]
### Qubes OS version:

Qubes RC4

### Affected component(s): 

Qubes Manager (Testing updates repo)

---

### Steps to reproduce the behavior:

Reboot system. Qubes Manager doesn't start. 

Try to start it manually and it doesn't start.

### Expected behavior:

Qubes Manager starts

### Actual behavior:

It doesn't start

### General notes:

---

**Comment by marmarek** [comment]
It would be more helpful if you'd include error message you've got. But I've found what's the problem already, fixed package will be in few minutes.

**Comment by Simon-Davies** [comment]
Sorry mate I wasn't getting any error messages.
