### ISSUE TITLE
Unable to convert Win10 VirtualBox File to HVM

### ISSUE THREAD

**Issue by e6lk7dqzm83p** [QubesOS/qubes-issues#4323]
### Qubes OS version:

R4.0

### Affected component(s): 

Following the instructions here:
https://www.qubes-os.org/doc/hvm/ (go to the "Converting VirtualBox VM to HVM" section)
does not yield a functionally Windows HVM.

---

### Steps to reproduce the behavior:

This documentation is inconsistent with that found at https://www.qubes-os.org/doc/windows-vm/, when using the correct documentation I entered:
```qvm-create win10 --class StandaloneVM --label red --property virt_mode=hvm --property kernel ='' --root-move-from /home/user/win10-root.img```

followed by `qvm-prefs win10 memory 8192` and `qvm-prefs win10 maxmem 8192`

Performing `qvm-start win10` yields a "no bootable device" error.  

I noticed that the win10 HVM has a Private storage max. size of 2048MiB and a System storage max. size of 10240, inspite of the fact the root image (win10-root.img) is ~41GB.

### Expected behavior:

The win10 VirtualBox Image is successfully converted to an HVM.

### Actual behavior:

Performing `qvm-start win10` yields a "no bootable device" error.  

### General notes:

---

**Comment by marmarek** [comment]
What version of qubes-core-admin-client package do you have? Similar issue is fixed in https://github.com/QubesOS/updates-status/issues/681

**Comment by Shie2doo** [comment]
Hello. I use updated Qubes R4.0 and have the same problem. I also found it is related to [#3838](https://github.com/QubesOS/qubes-issues/issues/3838).
I tried to solve it by creating a blank VM, extend its root volume, and dd copy win10-root.img into it, but I have got the same result - "No bootable device".
'''
qvm-create --class StandaloneVM --property virt_mode=hvm --property memory=4096 --property maxmem=4096 --property kernel='' --property debug=true -P hdd --label red win10
qvm-volume extend win10:root 19g
qvm-volume extend win10:root 28g
qvm-volume extend win10:root 37g
qvm-volume extend win10:root 46g
	// I have read that better not extend more than 10g.
sudo dd if=win10-root.img of=/dev/hddvg/vm-win10-root bs=1M status=progress oflag=sync
qvm-start win10
'''

**Comment by e6lk7dqzm83p** [comment]
@marmarek how do I check that? I do appear to have no pending updates, so I think my system is on the latest version.

Has anyone been able to get Windows working in Qubes 4.0 (even if I have to buy a license and use an ISO file) and if so could they post a link to instructions on how to do it?  I need Windows for work so any help would be greatly appreciated.

Thank you!

**Comment by e6lk7dqzm83p** [comment]
@marmarek I just did `sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing` and repeated the steps above for win10.  I still got a no bootable device error, but this time it appears the VM is the right size (about 41GB).

**Comment by e6lk7dqzm83p** [comment]
Hi,

I'm unsure, as I used the VM images here: https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/ (as referenced in https://www.qubes-os.org/doc/hvm/#converting-virtualbox-vm-to-hvm).  I used the Win10 image (as there is no longer an x64 Win 7 template), so it's possible that was installed in EFI mode.

I'll try with the x86 Win7 installation and report back.  Sorry for the delayed response...

**Comment by e6lk7dqzm83p** [comment]
Hi,
I tried with the x86 Win7 using the IE8 template and while it installs I get a blue screen; it may be that converting any of the VMs that Microsoft provides won't work (which would be contrary to the current Qubes documentation).

I don't have a Windows installer right now to try a fresh Windows install and would rather not spend a few hundred dollars to do an experiment (but may do it anyway).

Any thoughts on this?

**Comment by e6lk7dqzm83p** [comment]
I'm going to close this, as the issue appears to be the setup of the VMs.  I got Windows 10 working doing a fresh install (though I did find some issues).

I'd suggest updating the documentation to not use the test VMs provided by Microsoft.  I have found some issues with Windows in Qubes and will post those issues separately.

**Comment by andrewdavidwong** [comment]
> I'd suggest updating the documentation to not use the test VMs provided by Microsoft.

The documentation is a community effort. Please help us improve it by submitting a pull request:

https://www.qubes-os.org/doc/doc-guidelines/
