### ISSUE TITLE
Corrupted backup/clone of running VMs that are stored in a 'file' driver pool

### ISSUE THREAD

**Issue by rustybird** [QubesOS/qubes-issues#4324]
### Qubes OS version:
R4.0

### Affected component(s): 
qubes-core-dom0

### General notes:
I just realized the significance of a comment [in qubes-core-admin/qubes/storage/file.py](https://github.com/QubesOS/qubes-core-admin/blob/8b75b264ae352592aa9e2ab7f5e1c8f2963028b6/qubes/storage/file.py#L264-L267):

```python
def export(self):
    # FIXME: this should rather return snapshot(self.path, self.path_cow)
    #  if domain is running
    return self.path
```

So a [backup](https://github.com/QubesOS/qubes-core-admin/blob/8b75b264ae352592aa9e2ab7f5e1c8f2963028b6/qubes/backup.py#L374) or [clone](https://github.com/QubesOS/qubes-core-admin/blob/8b75b264ae352592aa9e2ab7f5e1c8f2963028b6/qubes/storage/file.py#L276) from any running VM stored in a `file` driver pool currently operates on the live data. If it is modified while the copy is in progress, that would probably result in silent data corruption, possibly on the VM filesystem level.

**Comment by tasket** [comment]
Not sure if this is an option with Xen...

Wouldn't opening the image files with an exclusive lock resolve this issue? Side effect would be that backing up, cloning, etc. would require the VMs to be in a stopped state.

**Comment by rustybird** [comment]
> Not sure if this is an option with Xen...
>
> Wouldn't opening the image files with an exclusive lock resolve this issue?

It's almost tempting, in a perverse way, to somehow try and shoehorn [mandatory file locks](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/Documentation/filesystems/mandatory-locking.txt?id=10dc890d4228cd17ddfd09ba9aaa9221627e29b2#n8) into the [`block-snapshot`](https://github.com/QubesOS/qubes-core-admin/blob/master/linux/system-config/block-snapshot) script... Advisory locks could work though. Then it would be up to the consumers of `export()` to implement the other side of the lock.

And/or get it over with and start deprecating the [`file` driver](https://image.ibb.co/fCpgXU/file_py.jpg) in R4.1. Like, no `varlibqubes` pool at all for non-FICLONE root filesystems, and a big fat warning whenever the user attempts to create any other `file` pool.
