### ISSUE TITLE
qubes.Filecopy policy not recognised

### ISSUE THREAD

**Issue by unman** [QubesOS/qubes-issues#4325]
### Qubes OS version:

R4.0

### Affected component(s): 

qvm-copy
qubes policy

---

### Steps to reproduce the behavior:

Have /etc/qubes-rpc/policy/qubes.Filecopy 
`$anyvm $anyvm ask`

Use `qvm-copy` or` qvm-move` in qube

### Expected behavior:

Confirmation dialogue opens,

### Actual behavior:

No confirmation.
File is copied.

### General notes:

---

**Comment by marmarek** [comment]
To where is it copied? `qvm-copy` do not have destination argument, so without the confirmation there is no destination defined...

Anyway, check the policy file again, specifically if you don't have any lines before that `$anyvm $anyvm ask`. Confirmation mechanism in R3.2 had "yes to all" option which put new entries at the top (before comments), and if there was only one such entry, it was easy to miss.

**Comment by unman** [comment]
Rebooted and everything works as expected.
Putting this down to stupidity.
