### ISSUE TITLE
part of whonix repo are "down", can't update whonix gw/ws templates

### ISSUE THREAD

**Issue by 99ninetynine** [QubesOS/qubes-issues#4328]
### Qubes OS version:

R4.0

### Affected component(s): 

whonix-ws-14
whonix-gw-14

---

### Expected behavior:

updates stuck on 97% [Waiting for headers]

### Actual behavior:

user@host:~$ sudo apt-get update
Ign:1 tor+http://vwakviie2ienjx6t.onion/debian stretch InRelease                                                                    
Ign:3 http://ftp.us.debian.org/debian stretch InRelease                                                                             
Get:4 http://deb.whonix.org stretch-proposed-updates InRelease [13.2 kB]                                                            
Get:6 http://deb.whonix.org stretch-proposed-updates/main amd64 Packages [51.1 kB]                                                  
Get:2 http://deb.qubes-os.org/r4.0/vm stretch InRelease [2,484 B]                                                                   
Get:7 http://deb.qubes-os.org/r4.0/vm stretch/main amd64 Packages [18.3 kB]                                                         
Get:8 tor+http://deb.dds6qkxpwdeubwucdiaord2xgbbeyds25rbsgr73tbfpqpt4a6vjwsyd.onion stretch-proposed-updates InRelease [13.2 kB]    
Get:10 tor+http://deb.dds6qkxpwdeubwucdiaord2xgbbeyds25rbsgr73tbfpqpt4a6vjwsyd.onion stretch-proposed-updates/main amd64 Packages [51.1 kB]
Get:5 http://security.debian.org stretch/updates InRelease [94.3 kB]                      
Get:9 tor+http://vwakviie2ienjx6t.onion/debian stretch Release [118 kB]                              
Get:11 http://ftp.us.debian.org/debian stretch Release [118 kB]                                               
Get:12 http://security.debian.org stretch/updates/main amd64 Packages [440 kB]                 
Get:13 http://security.debian.org stretch/updates/main Translation-en [190 kB]                   
Get:14 http://security.debian.org stretch/updates/contrib amd64 Packages [1,760 B]                                          
Get:15 http://security.debian.org stretch/updates/contrib Translation-en [1,759 B]                                     
Get:16 http://security.debian.org stretch/updates/non-free amd64 Packages [1,600 B]                                          
Get:17 http://security.debian.org stretch/updates/non-free Translation-en [691 B]                                      
Get:18 tor+http://vwakviie2ienjx6t.onion/debian stretch Release.gpg [2,434 B]                                              
Get:19 tor+http://vwakviie2ienjx6t.onion/debian stretch/main amd64 Packages [7,099 kB]
Get:20 tor+http://vwakviie2ienjx6t.onion/debian stretch/main Translation-en [5,393 kB]
Get:21 tor+http://vwakviie2ienjx6t.onion/debian stretch/main amd64 Contents (deb) [31.6 MB]                                         
Get:22 tor+http://vwakviie2ienjx6t.onion/debian stretch/contrib amd64 Packages [50.9 kB]                                            
Get:23 tor+http://vwakviie2ienjx6t.onion/debian stretch/contrib Translation-en [45.9 kB]                                            
Get:24 tor+http://vwakviie2ienjx6t.onion/debian stretch/contrib amd64 Contents (deb) [90.3 kB]                                      
Get:25 tor+http://vwakviie2ienjx6t.onion/debian stretch/non-free amd64 Packages [78.7 kB]                                           
Get:26 tor+http://vwakviie2ienjx6t.onion/debian stretch/non-free Translation-en [80.6 kB]                                           
Get:27 tor+http://vwakviie2ienjx6t.onion/debian stretch/non-free amd64 Contents (deb) [810 kB]                                      
Get:28 http://ftp.us.debian.org/debian stretch Release.gpg [2,434 B]                                                                
Get:29 http://ftp.us.debian.org/debian stretch/main amd64 Packages [7,099 kB]                                                       
Get:30 http://ftp.us.debian.org/debian stretch/main Translation-en [5,393 kB]                                                       
Get:31 http://ftp.us.debian.org/debian stretch/main amd64 Contents (deb) [31.6 MB]                                                  
Get:32 http://ftp.us.debian.org/debian stretch/contrib amd64 Packages [50.9 kB]                                                     
Get:33 http://ftp.us.debian.org/debian stretch/contrib Translation-en [45.9 kB]                                                     
Get:34 http://ftp.us.debian.org/debian stretch/contrib amd64 Contents (deb) [90.3 kB]                                               
Get:35 http://ftp.us.debian.org/debian stretch/non-free amd64 Packages [78.7 kB]                                                    
Get:36 http://ftp.us.debian.org/debian stretch/non-free Translation-en [80.6 kB]                                                    
Get:37 http://ftp.us.debian.org/debian stretch/non-free amd64 Contents (deb) [810 kB]                                               

Ign:38 tor+http://sgvtcaew4bxjd7ln.onion stretch/updates InRelease                           
Ign:39 tor+http://sgvtcaew4bxjd7ln.onion stretch/updates Release
Ign:40 tor+http://sgvtcaew4bxjd7ln.onion stretch/updates/main amd64 Packages
Ign:41 tor+http://sgvtcaew4bxjd7ln.onion stretch/updates/main all Packages
Ign:42 tor+http://sgvtcaew4bxjd7ln.onion stretch/updates/main Translation-en

### General notes:

---

**Comment by TNTBOMBOM** [comment]
> Ign:38 tor+http://sgvtcaew4bxjd7ln.onion stretch/updates InRelease
> Ign:39 tor+http://sgvtcaew4bxjd7ln.onion stretch/updates Release
> Ign:40 tor+http://sgvtcaew4bxjd7ln.onion stretch/updates/main amd64 Packages
> Ign:41 tor+http://sgvtcaew4bxjd7ln.onion stretch/updates/main all Packages
> Ign:42 tor+http://sgvtcaew4bxjd7ln.onion stretch/updates/main Translation-en

these are not whonix repos , these are Debian-Security onion repo. 

Try to open a ticket in Debian bugs reports.

**Comment by andrewdavidwong** [comment]
Closing as "not our bug." If you believe this is a mistake, please leave a comment, and we'll be happy to take another look. Thank you.

**Comment by 99ninetynine** [comment]
> Closing as "not our bug." If you believe this is a mistake, please leave a comment, and we'll be happy to take another look. Thank you.



> > Ign:1 tor+http://vwakviie2ienjx6t.onion/debian stretch InRelease
> 
> > Ign:38 tor+http://sgvtcaew4bxjd7ln.onion stretch/updates InRelease
> > Ign:39 tor+http://sgvtcaew4bxjd7ln.onion stretch/updates Release
> > Ign:40 tor+http://sgvtcaew4bxjd7ln.onion stretch/updates/main amd64 Packages
> > Ign:41 tor+http://sgvtcaew4bxjd7ln.onion stretch/updates/main all Packages
> > Ign:42 tor+http://sgvtcaew4bxjd7ln.onion stretch/updates/main Translation-en
> 
> these are not whonix repos , these are Debian onion repos.
> 
> Try to open a ticket in Debian bugs reports.

Ok,  done.
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=909355
