### ISSUE TITLE
Cloning template VM in Qube Manager causes "critical error" - KeyError at line 415 of qube_manager.py

### ISSUE THREAD

**Issue by daniel-ayers** [QubesOS/qubes-issues#4333]
### Qubes OS version:

4.0 (with current dom0 updates)

### Affected component(s): 

Qube Manager (specifically, cloning a template VM)

---

### Steps to reproduce the behavior:

Attempt to clone a (template) VM in Qube Manager.

### Expected behavior:

A copy of the VM is created.

### Actual behavior:

Critical error dialog ("Houston, we have a problem...") appears.  

Reports "KeyError: 13" at line 415 of file /usr/lib/python3.5/site-packages/qubesmanager/qube_manager.py.

Dialog says that line is "self.vms_in_table[vm.qid].update()" in check_updates().

(I am guessing from this that vm.qid == 13 and that key does not exist in the dict self.vms_in_table[]?".

### General notes:

The VM I was trying to clone was a template VM that itself was a clone of the fedora-28 template VM.

A new VM was created using the 'destination' name I specified in the cloning step.  It shows up on the Q menu at top left.  Appears it was not properly initialised, as the critical error dialog appears every 30 seconds with the same error message (very annoying!).

---

**Comment by daniel-ayers** [comment]
I can open the settings for the 'destination' qube.  It is obviously only partly configured.

Template value is blank. Networking is default (none) (current).

After deleting the destination VM a different error pops up every 30 seconds at the same line - QubesPropertyAccessorError 'qid' does not exist.

**Comment by daniel-ayers** [comment]
No error is generated if I clone the same VM from the dom0 command line using `qvm-clone`.

**Comment by daniel-ayers** [comment]
The QubesPropertyAccessorError 'qid' error message appears to occur whenever a qube is deleted outside of qubes manager, for example when upgrading whonix and deleting all the whonix templates/qubes from the command line.

**Comment by marmarta** [comment]
Should be fixed by https://github.com/QubesOS/qubes-manager/commit/f61871654832ebcc72251e83d3666e8b9c619664 - the problem was when events 'VM state changed' and 'VM removed' were processed by the manager in the wrong order.
