### ISSUE TITLE
Cannot set HVM VM to non-seamless mode

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#4342]
### Qubes OS version:

R4.0

### Affected component(s): 

qubes-core-admin, GUI

---

### Steps to reproduce the behavior:

Try to set an HVM VM to non-seamless mode

### Expected behavior:

There is a documented way to do this

### Actual behavior:

Either no such way, or I could not find the doucmentation

### General notes:

This is necessary for VoIP tools that use screensharing to work.

---

**Comment by andrewdavidwong** [comment]
I'm guessing that this is a Qubes Manager or widget UX issue, unless the functionality really disappeared between 3.2 and 4.0.

**Comment by marmarta** [comment]
As far as I can tell, it really did disappear due to not actually being able to do anything - ping @marmarek  ?

**Comment by marmarek** [comment]
See https://github.com/QubesOS/qubes-issues/issues/3585#issuecomment-403285826

**Comment by DemiMarie** [comment]
That’s annoying.  Would it be possible to allow for emulated graphics, or
am I stuck with GPU pass-through?

**Comment by DemiMarie** [comment]
Also, this reminds me of Qubes’s high-DPI woes — in both cases, Qubes’s
lack of hardware-accelerated graphics might make it unusably slow even if
it were possible.  I suspect that hardware-accelerated compositing in dom0
is likely the only reason Qubes is useable today.

There needs to be a secure way for virtualizing graphics.  Intel VT-G?

On Sep 27, 2018 2:46 PM, "Marek Marczykowski-Górecki" <
notifications@github.com> wrote:

See #3585 (comment)
<https://github.com/QubesOS/qubes-issues/issues/3585#issuecomment-403285826>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/QubesOS/qubes-issues/issues/4342#issuecomment-425202000>,
or mute the thread

**Comment by marmarek** [comment]
You can force emulated graphics by enabling debug mode in VM settings. Or open it on demand with `qvm-start-gui --force-stubdomain VMNAME`. But generally, if you have gui-agent installed in the VM, it takes precedence, otherwise emulated graphics is used.

**Comment by DemiMarie** [comment]
Would that solve the screen sharing problem?

**Comment by DemiMarie** [comment]
What would it take for screen sharing to work?

**Comment by DemiMarie** [comment]
Closing this issue as there does not appear to be a real bug.
