### ISSUE TITLE
qvm-usb in dom0 does not list USB devices as per documentation

### ISSUE THREAD

**Issue by daniel-ayers** [QubesOS/qubes-issues#4345]
### Qubes OS version:

4.0 (with current dom0 updates)

### Affected component(s): 

Unknown

---

### Steps to reproduce the behavior:

Invoke `qvm-usb` in dom0.

### Expected behavior:

A list of USB devices is displayed as shown in the "Use of qubes-usb-proxy (R4.0)" section of https://www.qubes-os.org/doc/usb/.

### Actual behavior:

A header line only is displayed (BACKEND:DEVID ...), no devices are listed.

### General notes:

Devices widget does show some USB devices - block devices and microphone.

The documentation of use of USB devices isn't great and may be outdated - not sure if the discrepancy between what the docs say I should expect and what I actually get means (a) there is a bug; or (b) the documentation is outdated.

---

**Comment by daniel-ayers** [comment]
As I have the issue there may be some benefit in me supplying additional debug info.  Happy to help out by doing that, but would need some guidance as to what information to provide - 26 yrs experience with Linux, <1 week with Qubes. :)

**Comment by marmarek** [comment]
Do you have USB VM (sys-usb)?

**Comment by daniel-ayers** [comment]
I did not at the time of raising the issue, but I do now.  "qvm-usb" now works as expected.

**Comment by andrewdavidwong** [comment]
> I did not at the time of raising the issue, but I do now. "qvm-usb" now works as expected.

I interpret this to mean that this issue should be a doc task to specify that a USB VM is required for `qvm-usb`.

**Comment by marmarek** [comment]
It's already [there](https://www.qubes-os.org/doc/usb/#attaching-a-single-usb-device-to-a-qube-usb-passthrough):
> Note, you cannot pass through devices from dom0 (in other words: a USB VM is required).

**Comment by andrewdavidwong** [comment]
> It's already [there](https://www.qubes-os.org/doc/usb/#attaching-a-single-usb-device-to-a-qube-usb-passthrough):
> > Note, you cannot pass through devices from dom0 (in other words: a USB VM is required).

Ah, I see. In that case, closing as "invalid."
