### ISSUE TITLE
Webcam, microphone and keyboard issues after update to Fedora 28

### ISSUE THREAD

**Issue by ioleo** [QubesOS/qubes-issues#4347]
### Qubes OS version:

R4.0

### Affected component(s): 

laptop built-in camera
laptop built-in microphone
laptop built-in keyboard

---

### Steps to reproduce the behavior:

* start with fedora-26 based qube with working webcam, microphone and working polish keyboard
* upgrade to fedora-27 following steps in https://www.qubes-os.org/doc/template/fedora/upgrade-26-to-27/
* upgrade to fedora-28 following steps in https://www.qubes-os.org/doc/template/fedora/upgrade-27-to-28/

### Expected behavior:

* expected microphone to work like it does when I open fedora-26 based qube
* expected webcam to work like it does when I open fedora-26 based qube
* expected share-screen to work like it does when I open fedora-26 based qube
* expected polish characters to work like it does in fedora-26 based qubes

### Actual behavior:

* bug 1: cannot type polish characters anymore
* bug 2: cannot use webcam in Google Meet/Zoom/similar software, google meet still "sees" the camera (I'm getting firefox promt for consent to use it), but it sais forever "starting camera" and nobody can see me
* bug 3: cannot use microphone in Google Meet/Zoom/similar software, google meet still "sees" the microphone (I'm getting firefox promt for consent to use it), but nobody can hear me
* bug 4: cannot share screen/present in Google Meet/Zoom/similar software, google meet still promts me if I want to share a window only or the whole screen, but either way, noone sees my scree

### General notes:

* bugs 2, 3, 4 happen also when downgraded to Firefox 60 or tried alternate browser (falkon)
* webcam seems to work just fine when using `cheese` (I can see image captured live)
* sound/video works just fine when viewing youtube videos
* yes, I did not forget to attach devices (microphone/webcam) to the qube
* the machine is: Asus Zenbook UX501JW

---

### Related issues:

* #4343

**Comment by lvh** [comment]
bug 3 may be the same as #4204.

**Comment by marmarek** [comment]
Do you have `pulseaudio-qubes` package installed? Maybe it was removed in the process? To make sure all standard packages are installed, do `sudo dnf install qubes-vm-recommended` in that template.

**Comment by ioleo** [comment]
```

**Comment by ioleo** [comment]
Sorry, accidentally pressed enter which apparently closes the issue without any promt.
About the package yes I have it installed:
```
$ rpm -qa | grep pulseaudio-qubes
pulseaudio-qubes-4.0.15-1.fc28.x86_64
```

**Comment by marmarek** [comment]
#4204 is fixed in 4.0.16. See https://github.com/QubesOS/qubes-issues/issues/4204#issuecomment-420783188

**Comment by ioleo** [comment]
OK, since I don't want to introduce possible other bugs, I'll try to update only that package.
`sudo dnf update qubes-gui-agent --enablerepo=qubes-vm-r4.0-current-testing`

> The component gui-agent-linux (including package pulseaudio-qubes-4.0.16-1.fc26)

I assume it's `qubes-gui-agent` as simple dnf update does not list anything like `gui-agent-linux`.

**Comment by ioleo** [comment]
The other command lists 4 packages to update
```
$ sudo dnf install qubes-vm-recommended
Last metadata expiration check: 0:06:45 ago on Thu Sep 27 22:44:54 2018.
Dependencies resolved.
========================================================================================================================
 Package                               Arch            Version                     Repository                      Size
========================================================================================================================
Installing:
 qubes-vm-recommended                  noarch          4.0.2-1.fc28                qubes-vm-r4.0-current          6.4 k
Installing dependencies:
 qubes-mgmt-salt-vm-connector          noarch          4.0.9-1.fc28                qubes-vm-r4.0-current          9.1 k
 salt                                  noarch          2018.3.2-2.fc28             updates                        8.9 M
 salt-ssh                              noarch          2018.3.2-2.fc28             updates                         23 k

Transaction Summary
========================================================================================================================
Install  4 Packages
```

should I also do this update?

**Comment by marmarek** [comment]
> sudo dnf update qubes-gui-agent --enablerepo=qubes-vm-r4.0-current-testing

If you want just one package, use `pulseaudio-qubes`.

> should I also do this update?

I don't think those are related to your problems.

**Comment by ioleo** [comment]
The last issue I'm having is not being able to type polish characters (`Alt + a`, `Alt + e`, `Alt + l`, `Alt + s`, `Alt + c` etc).  I've combared my fedora-26 and updated fedora-28 qubes settings and I seem to have everything the same (the same keyboard, language settings etc).

**Comment by marmarek** [comment]
What happen if you run `setxkbmap pl` in affected qube?

**Comment by marmarek** [comment]
And before that, what `setxkbmap -query` prints?

**Comment by ioleo** [comment]
```
$ setxkbmap -query
rules:      evdev
model:      pc105
layout:     us
options:    ctrl:nocaps
```

**Comment by ioleo** [comment]
and `setxkbmap pl` fixed it @marmarek :tada:

**Comment by ioleo** [comment]
Thank you very much for your help. I'll close this issue as I'm almost sure the video will work now. If not can always come back and reopen :)

**Comment by ioleo** [comment]
@marmarek Just confirmed. Audio/video works flawlessly. The keyboard fix also works (though I had to add it to `.bashrc` in AppVM as for some reason it got reset after restarting).

Screen sharing still does not work as expected (I can only present "entire screen", and my collegues could only see a white page - instead of my screen), but I guess it's not related to this bug. I have not used screen sharing on Fedora26 so I actually don't know if that ever worked. I'll look through issues here, perhaps someone already found an anwser for that. Again thanks for blazing-fast and accurate support - I'm amazed :D <3
