### ISSUE TITLE
Shutting down VM with attached mic or camera makes them unusable

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#4350]
### Qubes OS version:

R4.0

### Affected component(s): 

qubes-core-admin

---

### Steps to reproduce the behavior:

1. Attach microphone or USB camera to an AppVM
2. Shutdown the AppVM (without first detaching the device)
3. Try to attach the device to another AppVM

### Expected behavior:

The second attach fails, often with an “Empty response from qubesd” error.  The device is unusable until the system is rebooted.

### Actual behavior:

The second attach succeeds.

### General notes:

I don’t think there is a security reason to forbid this.  There certainly isn’t for the microphone.

This is one of a series of bugs in Qubes’s multimedia support.

---

**Comment by marmarek** [comment]
Does it still happen? Similar thing was fixed in https://github.com/QubesOS/updates-status/issues/741

**Comment by DemiMarie** [comment]
@marmarek This is fixed (tested on latest Qubes R4.0).
