### ISSUE TITLE
Screensharing in AppVMs

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#4351]
### Qubes OS version:

R4.0

### Affected component(s): 

domU GUI

---

### Steps to reproduce the behavior:

Use Slack Desktop with screensharing

### Expected behavior:

Screensharing works, in that it can share any screen space belonging to the AppVM

### Actual behavior:

Screensharing fails

### General notes:

This was an issue for me during an interview.  Probably the best solution is to allow running a full Linux desktop environment in a single Qubes window.

---

**Comment by marmarek** [comment]
Some details from @v6ak on the current state: https://groups.google.com/d/msgid/qubes-users/626cd5a7-97b0-497b-8d85-2eb7df9e9402%40googlegroups.com

**Comment by marmarek** [comment]
Not very scientific test: firefox with the same video and other settings. CPU usage for both VMs (with the change and without) is pretty much the same.

**Comment by ioleo** [comment]
@marmarek maybe this could be exposed as a AppVM setting? I've got about 20 AppVMs, but actually only need to screenshare from one.

**Comment by ioleo** [comment]
Thank you very much for this! @marmarek :tada: :clap: 
I'll try to update qubes-gui-agent from testing repositories tomorrow and test it. I'll let you know.

**Comment by v6ak** [comment]
There used to be update notifications from a bot. In this issue, I don't see any, which most likely means it is not yet in the repo.

**Comment by ioleo** [comment]
@v6ak I see. The command `sudo dnf update qubes-gui-agent --enablerepo=qubes-vm-r4.0-current-testing` actually shows that there is an update available:
```
================================================================================
 Package            Arch      Version            Repository                Size
================================================================================
Upgrading:
 qubes-gui-agent    x86_64    4.0.17-1.fc28      qubes-vm-r4.0-current     54 k
Installing dependencies:
 python3-xcffib     noarch    0.5.1-5.fc28       fedora                   192 k

Transaction Summary
================================================================================
Install  1 Package
Upgrade  1 Package
```

But I suspect it might be anything else :)

**Comment by marmarek** [comment]
This will be in 4.0.18. And also 3.2.29 some time later.

**Comment by ioleo** [comment]
@marmarek @v6ak I can confirm it works using `vncserver` and `dwm` locally (as per [daves blog](https://www.dave-cohen.com/blog/qubes-vnc-screenshare/) except all in one VM / without the inter-vm stuff - I don't need that).

**Comment by ioleo** [comment]
@marmarek @v6ak I can confirm it also works without those stuff. You're seeing all windows of your AppVM, but everything around is white. Which is actually really cool!

**Comment by succdo** [comment]
Nice features, Thanks for implementing this important features.
Looking forward to new release for R3.2.
