### ISSUE TITLE
Windows 10 StandaloneVM not booting

### ISSUE THREAD

**Issue by Simon-Davies** [QubesOS/qubes-issues#4352]
### Qubes OS version:

Qubes 4.0 (R4.0)

### Affected component(s): 

Windows 10 StandaloneVM 

---

### Steps to reproduce the behavior:

Create a Windows 10 StandaloneVM. Update the VM and install Qubes Windows Tools. Everything works at this point.

Close down the VM and increase the memory and max memory to 8049 in dom0

Windows 10 StandaloneVM won't boot (No GUI) State is Yellow.

### Expected behavior:

Windows 10 StandaloneVM boots (With GUI)

### Actual behavior:

Windows 10 StandaloneVM doesn't boot (No GUI) State is Yellow.

### General notes:

---

**Comment by unman** [comment]
A little more information might be useful - any errors reported?
Does window open and close again?
If you run qvm-start <win10> from  dom0 konsole, do you see any more detail?
Anything reported in logs? (You can access these from Qube Manager)

**Comment by Simon-Davies** [comment]
The GUI doesn't open at all

If I run qvm-start Windows-10 from dom0 I see no errors and it completes.

Logs:

/var/log/qubes/guid.Windows-10.log

Icon size: 128x128
domain dead
Failed to connect to gui-agent

**Comment by taradiddles** [comment]
> Everything works at this point.
> Close down the VM and increase the memory and max memory to 8049 in dom0
> Windows 10 StandaloneVM won't boot

Do you mean that you can consistently boot your VM without problem (with QWT installed) until you change the memory setting, or did booting fail just after you installed QWT ?

Did you try to enable debug to get an early gui console ? (`qvm-prefs win10 debug true`)

**Comment by Simon-Davies** [comment]
I have tried enabling qvm-prefs Windows-10 debug true with a fresh VM but I still get the issue.

I'm running Windows 10 Pro N for Workstations.

I was also getting the same issue with Windows 10 Pro.

The problem is introduced as soon as I install the latest version of QWT, reboot and start the system and then try to reboot again.

This time I set up all the correct RAM parameters at the start.

/var/log/qubes/qrexec.Windows-10.log

domain dead
cannot connect to qrexec agent: No such process

**Comment by taradiddles** [comment]
> I have tried enabling qvm-prefs Windows-10 debug true with a fresh VM but I still get the issue.

That's strange, with debug=true you should see a gui console of the VM - eg. the windows boot entry, windows boot logo, ..., until:
- QWT's display driver is enabled when windows loads the system drivers: the "main" windows appears and the "debug" one goes dark or stays with the windows logo
- or the VM crashes (the so called "blue screen of death"), which is most of the time the reason that qrexec didn't start

You could try to enable debug before you install QWT and check that you see the early console. If you don't, something's not OK, try to search other issues or file a new one.

By the way QWT for R4.0 are still a work in progress - they work OK for some people, and crash for others (see issue #3585)

**Comment by Simon-Davies** [comment]
I enabled debug before installing QWT and the output above is from that.

Why file a new issue when I've already filed this one?

**Comment by taradiddles** [comment]
> Why file a new issue when I've already filed this one?

Because it looked like you had two unrelated problems::
1. QWT breaks an otherwise functional VM - this issue.
2. the early gui console doesn't appear

I assumed 1. because you wrote:

> Steps to reproduce the behavior:
> Create a Windows 10 StandaloneVM. Update the VM and install Qubes Windows Tools.

If that's in that order, Windows being Windows, WindowsUpdate most likely rebooted the VM a zillion times. This would imply that you could reboot the VM without experiencing the 'domain dead' error.

> The problem is introduced as soon as I install the latest version of QWT, reboot and start the system and then try to reboot again.

Which seemed to confirm my assumption. But you then replied:

> I enabled debug before installing QWT and the output above is from that.

So, did you mange to have a functional VM without QWT installed ?

Anyway, what do `/var/log/xen/console/guest-Windows-10.log` and `/var/log/xen/console/guest-Windows-10-dm.log` show ?

**Comment by Simon-Davies** [comment]
Before installing QWT the VM is functional.

I can't check the logs now as I'm seeing if increasing the timeout helps aswell as setting debug to true.

If it does the same again with no GUI  I'll edit this comment and post the logs.

**Comment by Simon-Davies** [comment]
After Installing QWT again on a new Windows 10 Pro N for Workstations StandaloneVM.

![unnamed](https://user-images.githubusercontent.com/713455/46321751-0a891380-c5dd-11e8-9c14-d654d45fcc8a.jpg)

![unnamed2](https://user-images.githubusercontent.com/713455/46321758-107ef480-c5dd-11e8-89a1-921532a4957d.jpg)

**Comment by briped** [comment]
Just wanted to add a quick comment. Issue remains, but dicking around (I don't really have a clue what I'm doing), i got it somewhat working.
1. Installed latest Windows 10 (1903) downloaded directly from MS, into HVM as per standard instructions.
2. Installed latest updates.
3. Started Windows 10 "qvm-start windows-10 --install-windows-tools" (after getting them using the dom0 console).
4. Installed QWT, as per instructions and restarted.
5. Windows starts as expected. Doing another restart and Windows no longer starts, even though Qubes manager shows it running with a green icon.

This is where I started dicking around, trying to see what the various qvm-* commands did, and after a bit found qvm-features, so used it to compare my working windows-7 with the non-working windows-10. I noticed that windows-7 had gui-emulated set to blank whereas windows-10 had it set to 1. Also windows-7 gui was set to 1 where windows-10 gui was set to blank. Set changed this using "qvm-features windows-10 gui-emulated 0" and "qvm-features windows-10 gui 1!. After this I could start Windows 10 properly, even launching apps from the Q-menu.

I don't really have any idea what I did. I just saw "gui" and compared 7 to 10 and tried something which seems to have paid off. Feel free to enlighten me as to why it worked :)

Now I'm just missing the option to enable Seamless mode as is possible with Windows 7. Perhaps I should try installed QWT with the seamless mode as well, even though it clearly states it's only for Windows 7.

**Comment by marmarek** [comment]
> Set changed this using "qvm-features windows-10 gui-emulated 0" and "qvm-features windows-10 gui 1!

`0` is not the same as empty. But glad it works for you.



> Now I'm just missing the option to enable Seamless mode as is possible with Windows 7

There is no seamless mode for Windows 10 implemented. See https://github.com/QubesOS/qubes-issues/issues/1861

**Comment by GWeck** [comment]
See my comment in #5462 from 13 Jan. This seems to be a way that works (at least on my machine).

It might be a solution to incorporate the version 9.0 Xen drivers into QWT - but **caution**: These drivers seem to work only for Windows 10; they crash Windows 7, so probably both versions are needed in oder to support both W7 and W10. (And right now, that Microsft has terminated the support for Windows 7, Qubes and QWT are about the only environment to allow to run a decent Windows!)
