### ISSUE TITLE
Missing symlink in whonix-ws-14

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#4354]
### Qubes OS version:

R4.0

### Affected component(s): 

Whonix DispVMs

---

### Steps to reproduce the behavior:

Try to run Tor Browser in `whonix-ws-dvm`

### Expected behavior:

Success

### Actual behavior:

`~/.tb` not found

### General notes:

Runnint `ln -s '../../var/cache/tb-binary/.tb' ~/.tb` in whonix-ws-dvm solves the problem.

---

**Comment by adrelanos** [comment]
There is no missing symlink.

https://www.whonix.org/wiki/Tor_Browser#In_Qubes-Whonix

> Do not run Tor Browser in a TemplateVM (whonix-ws-14) or DVM Template (whonix-ws-14-dvm)!

Documented in wiki as well as Tor Browser startup prevented and explained in graphical user interface (GUI).

https://github.com/Whonix/tb-starter/blob/master/usr/bin/torbrowser#L216

```
 local MSG="<p>Do not run $tb_title in TemplateVM.<br></br>
```

https://github.com/Whonix/tb-starter/blob/master/usr/bin/torbrowser#L232

```
   local MSG="\
<p>Do not run Tor Browser in Qubes DVM Template!<br></br>
<br></br>
More info: <a href=https://www.whonix.org/wiki/Tor_Browser#Running_Tor_Browser_in_Qubes_DVM_Template>https://www.whonix.org/wiki/Tor_Browser#Running_Tor_Browser_in_Qubes_DVM_Template</a></p>"
```

Not a bug. Works as expected. Closeable.

**Comment by DemiMarie** [comment]
Still confused.

Without this symlink, torbrowser must download Tor Browser every time the
DispVM starts.  Running `update-torbrowser` in the TemplateVM is okay,
correct?

**Comment by adrelanos** [comment]
Yes. Very much ok. That is what documentation is saying. All you need to do. Then will be up to date in DispVM as well.

**Comment by DemiMarie** [comment]
Without the symlink, whonix-ws-dvm doesn't work.  I guess that is a bug of
its own?

**Comment by adrelanos** [comment]
Please elaborate on "doesn't work".

Do you have all apt-get upgrades as per https://www.whonix.org/wiki/Qubes/Update ?
