### ISSUE TITLE
system menu for attaching devices sometimes does not show all VMs as an option

### ISSUE THREAD

**Issue by dkg** [QubesOS/qubes-issues#4355]
### Qubes OS version:

4.0

### Affected component(s): 

system menu for device management that allows attaching/detaching USB devices and the microphone to a specific VM (sorry i don't know the name of the underlying tech component)

---

### Steps to reproduce the behavior:

launch a new disposable VM based on fedora-26.  try to attach a microphone to it via the menu. 

### Expected behavior:

I expect the newly-launched VM to always show up in the submenu of available VMs to attach to.

### Actual behavior:

sometimes, a VM does not show up in that list.  This seems to happen per-VM (that is, it doesn't change each time i open the submenu to look for it).

### General notes:

using `qvm-device attach` from the command line still works, as long as i know the name of the VM, so the problem is with the detection of VMs in the code (python?) that populates the submenu, i think.

---

**Comment by marmarek** [comment]
This hopefully should be fixed by just merged https://github.com/QubesOS/qubes-desktop-linux-manager/pull/30
