### ISSUE TITLE
Fix remaining dom0 packages for mockbuild

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#4356]
All R4.0 VM Fedora packages are already build with `mock`. But some dom0 packages still can be built with only legacy method (without generating proper src.rpm package).
Affectec packages:

- [x] linux-kernel (patches list missing in kernel.spec)
- [x] desktop-linux-xfce4 (mock can't find sources, those are in subdirectory)
- [x] desktop-linux-kde (mock can't find sources, those are in subdirectory)
- [x] desktop-linux-i3 (mock can't find sources, those are in subdirectory; `sh: perl: command not found`)
- [x] antievilmaid (not converted to spec.in format)

This is a subtask of #1508

**Comment by dmoerner** [comment]
I just used mock to build desktop-linux-i3 without any problems while trying to fix https://github.com/QubesOS/qubes-issues/issues/5168. Is there still an issue with that package?
