### ISSUE TITLE
Dom0 returns Input/Output error on every shell command after booting Windows7 HVM

### ISSUE THREAD

**Issue by Yethal** [QubesOS/qubes-issues#4357]
### Qubes OS version:

4.0, latest updates from testing repo installed

### Affected component(s): 

dom0

---

### Steps to reproduce the behavior:

Create a new Window HVM
Boot the HVM with .iso file attached
Proceed through the installation as usual (Windows HVM will shutdown at this point)
Boot the HVM again
Follow the installation procedure

### Expected behavior:

Installation finishes, it is possible to use the Windows VM. Rest of the QubesOS is unaffected.

### Actual behavior:

Windows VM shuts down on its own. Afterwards every shell command in dom0 returns Input/output error. As a result it is no longer possible to perform any action (even shut down the physical machine).

### General notes:

100% repro rate so far.
Thinkpad X230, i5 CPU, 8GB of RAM

---

**Comment by marmarek** [comment]
See `journalctl` in dom0. I guess it's about out of disk space. Check also disk usage widget, or `qvm-pool -i lvm` (size and usage fields).

**Comment by Yethal** [comment]
Widget says the usage is at 32.2% for lvm and 17.8% total. qvm-pool shows usage and size values aren't even in the same magnitude so I'd rule that out. I'll reproduce it once again and attach journalctl output.

**Comment by Yethal** [comment]
[log2.txt](https://github.com/QubesOS/qubes-issues/files/2431543/log2.txt)
Attached journalctl output.

**Comment by marmarek** [comment]
I don't see anything suggesting that any I/O error happened there. Maybe some details in kernel messages: `sudo dmesg`?

**Comment by Yethal** [comment]
Nothing out of the ordinary in dmesg, however I did notice that after the issue occurs and the screen locks itself it is no longer possible to unlock it (xscreensaver doesn't even display the password field)

**Comment by Yethal** [comment]
I managed to capture the actual error log. However due to the fact that filesystem becomes readonly at this point and I'm unable to start or interact with any AppVM I had to take pictures of journalctl with my phone. Also, the pictures are too big to be attached here and I didn't want to downsize them out of fear that they'll become unintelligible so I uploaded them to Dropbox. Here's the link to the folder:
https://www.dropbox.com/sh/wdg1eajgr12kx9v/AADmpnGKuIo55z-dSQ9N4ERCa?dl=0

**Comment by awokd** [comment]
I had this a week ago or so. Had a Win7 HVM running with the standard tools (not beta), stepped away for an hour or so. When I came back, dom0 was giving input/output errors and filesystem was read-only. Reboot fixed it. Seems like plenty of space free in all partitions.

**Comment by Yethal** [comment]
"A clock interrupt was not received on a secondary processor within the allocated time interval" - This message shows up after the VM BsoDs (visible with debug set to true).
