### ISSUE TITLE
Win7 HVM no longer starts

### ISSUE THREAD

**Issue by awokd** [QubesOS/qubes-issues#4361]
### Qubes OS version:

R4.0

### Affected component(s): 

Win HVM

---

### Steps to reproduce the behavior:

Update to latest stable Qubes patches
Start a previously working Win7 HVM

### Expected behavior:

Boots

### Actual behavior:

qrexec timeout after 300 seconds

### General notes:

- The `-dm` log's last lines are:
```
resize to 1024x768@32, 4096 required
vga s->lfb_addr = f0000000 s->lfb_end = f100000
```
- Using regular Windows tools, not the beta version
- Same issue on two separate systems, both Qubes 4.0
- No difference after changing `sys-firewall` to Fedora 28 from Debian 9

---

**Comment by marmarek** [comment]
> Update to latest stable Qubes patches

Can you provide exact version of `xen-hvm-stubdom-linux` package?

**Comment by awokd** [comment]
`xen-hvm-stubdom-linux` package is `1.0.9-1.fc25`.

**Comment by marmarek** [comment]
What do you see on emulated VGA output (enable debug mode for this VM)?

**Comment by awokd** [comment]
It was defaulting to Startup Repair, so I changed it to boot normally and it's actually behaving normally now! My network connection and video are both now working as expected. Thank you; I will see if I can get it to re-occur.

**Comment by awokd** [comment]
Disabling debug mode and booting again did not cause the issue to reoccur. Strange how they would both act up like that at the same time. I guess I will close this unless it happens again. Thank you for the fast response.
