### ISSUE TITLE
Cannot install pulseaudio-qubes in Xenial

### ISSUE THREAD

**Issue by unman** [QubesOS/qubes-issues#4364]
### Qubes OS version:

R4.0

### Affected component(s): 

pulseaudio-qubes

---

### Steps to reproduce the behavior:

Attempt to install pulse-audio-qubes

### Expected behavior:

Able to install package

### Actual behavior:

Cannot configure package - requires pulseaudio <=11.1
Version installed is 1:11.1-1

### General notes:

 I suspect this is because pulseaudio is installed with epoch 1, but no epoch is given in requirements,
With no epoch stated, Debian interprets that as 0:11.1.

---

**Comment by marmarek** [comment]
You're probably right. You need to adjust [this](https://github.com/QubesOS/qubes-gui-agent-linux/blob/master/debian/rules#L29) or [this](https://github.com/QubesOS/qubes-gui-agent-linux/blob/master/debian/rules#L11) line to include epoch of the package.

**Comment by unman** [comment]
I'd already made the change [here](https://github.com/QubesOS/qubes-gui-agent-linux/blob/master/debian/rules#L29)
I've checked and Ubuntu packages have epoch 1, while Debian packages don't. That's a pain.
We'll need different requirements for packages for Ubuntu

**Comment by unman** [comment]
After [this merge](https://github.com/QubesOS/qubes-gui-agent-linux/commit/3c9f6e6e4f18a63e64ed72bba5253dd1b35aed02), all should be good.
