### ISSUE TITLE
Build python-xcffib fails in Xenial

### ISSUE THREAD

**Issue by unman** [QubesOS/qubes-issues#4365]
### Qubes OS version:

R4.0

### Affected component(s): 

qubes-builder
python-xcffib

---

### Steps to reproduce the behavior:

Attempt to build python-xcffib for xenial

### Expected behavior:

Package builds

### Actual behavior:

Build fails with error:
`ERROR:  Failure: ValueError (Attempted relative import in non-package)`

### General notes:

The build succeeds for bionic.
Xenial has pybuild v2.20151103ubuntu1

---

**Comment by marmarek** [comment]
Can you provide more context, like full message?

**Comment by unman** [comment]
```
generating cffi module '/home/user/qubes-src/python-xcffib/debian-pkg/.pybuild/pythonX.Y_3.5/build/xcffib/_ffi.py'
   dh_auto_test -O--buildsystem=pybuild
I: pybuild base:184: cd /home/user/qubes-src/python-xcffib/debian-pkg/.pybuild/pythonX.Y_2.7/build; python2.7 -m nose test
E.EE
======================================================================
ERROR: Failure: ValueError (Attempted relative import in non-package)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/user/qubes-src/python-xcffib/debian-pkg/.pybuild/pythonX.Y_2.7/build/test/test_connection.py", line 23, in <module>
    from .testing import XcffibTest

ValueError: Attempted relative import in non-package
```
I see that debian/rules has `DEB_BUILD_OPTIONS = nocheck`
If the aim is to avoid running tests, then `export PYBUILD_DISABLE=test` is also required.
If the intention is to keep the tests, then some test_options will have to be passed in to avoid this error.
