### ISSUE TITLE
Kernel 4.14.67 Fan blowing incessantly

### ISSUE THREAD

**Issue by mycase** [QubesOS/qubes-issues#4372]
### Qubes OS version:

R3.2

### Affected component(s): 

---

### Steps to reproduce the behavior:

Boot into recent default kernel 4.14.67-1

### Expected behavior:

The fan stops blowing after boot.

### Actual behavior:

The fan doesn't stop blowing, even if no VMs are started. I.e. only dom0 runs, with relatively low cpu usage reported by the top command under dom0.

### General notes:

Booting into 4.9.56-21 works around the issue.

Laptop specifications:
Brand: CLEVO https://www.clevo.com.tw/
Model: W550EU (2012)
cat /proc/cpuinfo: # running under 4.9.56
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 58
model name	: Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz
stepping	: 9
microcode	: 0x20
cpu MHz		: 2594.192
cache size	: 3072 KB
physical id	: 0
siblings	: 2
core id		: 0
cpu cores	: 2
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu de tsc msr pae mce cx8 apic sep mca cmov pat clflush acpi mmx fxsr sse sse2 ss ht syscall nx lm constant_tsc arch_perfmon rep_good nopl nonstop_tsc eagerfpu pni pclmulqdq monitor est ssse3 cx16 sse4_1 sse4_2 popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm epb fsgsbase erms xsaveopt dtherm ida arat pln pts
bugs		:
bogomips	: 5188.35
clflush size	: 64
cache_alignment	: 64
address sizes	: 36 bits physical, 48 bits virtual
power management:

processor	: 1
vendor_id	: GenuineIntel
cpu family	: 6
model		: 58
model name	: Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz
stepping	: 9
microcode	: 0x20
cpu MHz		: 2594.192
cache size	: 3072 KB
physical id	: 0
siblings	: 2
core id		: 1
cpu cores	: 2
apicid		: 2
initial apicid	: 2
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu de tsc msr pae mce cx8 apic sep mca cmov pat clflush acpi mmx fxsr sse sse2 ss ht syscall nx lm constant_tsc arch_perfmon rep_good nopl nonstop_tsc eagerfpu pni pclmulqdq monitor est ssse3 cx16 sse4_1 sse4_2 popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm epb fsgsbase erms xsaveopt dtherm ida arat pln pts
bugs		:
bogomips	: 5188.35
clflush size	: 64
cache_alignment	: 64
address sizes	: 36 bits physical, 48 bits virtual
power management:

---

**Comment by thewildcat** [comment]
Maybe also similiar to https://github.com/QubesOS/qubes-issues/issues/4367 ? Any error messages in your logs?

**Comment by mycase** [comment]
[screen@dom0 ~]$ journalctl --boot=-2 --priority 0..3 > journalctl-2.priority3.out.txt
[journalctl-2.priority3.out.txt](https://github.com/QubesOS/qubes-issues/files/2448115/journalctl-2.priority3.out.txt)

**Comment by thewildcat** [comment]
My CPU has no Hyper Threading, so that one should at least not affect me, can't speak to it. Does you xl dmesg show the L1TF-vulnerable message?

**Comment by marmarek** [comment]
There is 4.14.74 kernel in [testing repository](https://www.qubes-os.org/doc/software-update-dom0/#testing-repositories). Worth testing if that helps.

**Comment by thewildcat** [comment]
Same problems, at least with my laptop

**Comment by mycase** [comment]
I switched to R4.0 on a Latitude E6230, which doesn't have this problem. No longer an issue for me.

**Comment by andrewdavidwong** [comment]
> I switched to R4.0 on a Latitude E6230, which doesn't have this problem. No longer an issue for me.

Closing as fixed in R4.0. If anyone on R4.0 or higher is still experiencing this problem, please leave a comment, and we'll be happy to reopen this.
