### ISSUE TITLE
Building gcc (gcc.spec) for fc25 dom0 - needs 'make -j4'

### ISSUE THREAD

**Issue by AaronNGray** [QubesOS/qubes-issues#4373]
### Qubes OS version:

R4.1

### Affected component(s): 

gcc (gcc.spec) for fc25 dom0

---

### Steps to reproduce the behavior:

make qubes

### Expected behavior:

fast build of gcc using all processor cores, **make -j4** or whatever

### Actual behavior:

slow build using single core

### General notes:

Build system needs streamlining ideally get to gether distributed builds based on git hashes ?

---

**Comment by marmarek** [comment]
This was done for a reason: https://github.com/QubesOS/qubes-gcc/commit/f8d7420429ac08147f47a2ebd92bbe59b6980972
Since this package isn't updated that often (actually we have own build of it, only because of _one_ set of patches), there is very little gain in debugging this.

**Comment by marmarek** [comment]
If you want to save on build time, you can use binary package from yum.qubes-os.org. For that, in `builder.conf`, remove gcc from COMPONENTS and add `USE_QUBES_REPO_VERSION=4.0`.
