### ISSUE TITLE
Qubes with Firewall rules cannot connect to specified network services 

### ISSUE THREAD

**Issue by scallyob** [QubesOS/qubes-issues#4379]
### Qubes OS version:

R4.0

### Affected component(s): 

All network connections on AppVM with Firewall rules set

---

### Steps to reproduce the behavior:

* Boot AppVM (based on debian 9)

* try to connect to services allowed in firewall via Firefox or SSH (fail)

* traceroute dies at sys-firewall

* I can ping sys-firewall nothing beyond that

* I go into Qubes Settings and change to "Allow all outgoing Internet connections", no change in behavior

* all other Qubes network connections fine

* I update dom0 and TemplateVM and rebooted all, no change

* I create a new Qube, everything works fine until I add the firewall rules in Qubes Settings. Then same problem - no network connection

* I go into Qubes Settings and change to "Allow all outgoing Internet connections", no change

* this time I switch to "Limit outgoing Internet connections to ..." delete all the rules one by one and then go back to "Allow all outgoing internet connections" and reboot the AppVM

Now connections work. 

Try the same in the original AppVM, remove all firewall rules and set to Allow all - Now connections work there as well.

### Expected behavior:

Successful connection to services specified in firewall rules

### Actual behavior:

No Connections work as long as there are firewall rules present for this qube

### General notes:

This Qube has existed for and worked as expected for many months. No known changes were made since last use to cause this. 

---

**Comment by marmarek** [comment]
See `sudo journalctl -u qubes-firewall` output in `sys-firewall`. If any rule (for given qube) fails to load, the fallback is to drop traffic (to avoid unintentional leaks).

**Comment by scallyob** [comment]
Thank you. I must have added a rule to load some external javascript recently. It failed to resolve and all traffic was blocked.

Solved!
