### ISSUE TITLE
Consider switching to 32-bit PV stubdomains

### ISSUE THREAD

**Issue by alcreator** [QubesOS/qubes-issues#4380]
Historically, out of the released XSA advisories that affect PV domains, there are a higher number of serious vulnerabilities which affect only 64-bit PV, compared to those which only affect 32-bit PV.
For instance, the following serious (more than DoS) XSA only affect 64-bit PV domains: 
[XSA-7](https://lists.xen.org/archives/html/xen-announce/2012-06/msg00001.html), [XSA-67](https://xenbits.xen.org/xsa/advisory-67.html), [XSA-195](https://xenbits.xen.org/xsa/advisory-195.html), [XSA-212](https://xenbits.xen.org/xsa/advisory-212.html), [XSA-213](https://xenbits.xen.org/xsa/advisory-213.html), [XSA-215](https://xenbits.xen.org/xsa/advisory-215.html) (limited impact), and [XSA-254](https://xenbits.xen.org/xsa/advisory-254.html) (meltdown).

Serious 32-bit PV XSA advisories are: 
[XSA-185](https://xenbits.xen.org/xsa/advisory-185.html) and [XSA-194](https://xenbits.xen.org/xsa/advisory-194.html) (limited impact).

Switching to 32-bit PV will also allow Xen XPTI mitigations to be disabled for 64-bit PV, which can improve dom0 performance.

I am able to build a 32-bit PV stubdomain from a clean qubes builder clone, and using the 32-bit-build branches of https://github.com/alcreator/qubes-vmm-xen.git and https://github.com/alcreator/qubes-vmm-xen-stubdom-linux.git

The relevant build steps are then prefixed with linux32 to build everything as 32-bit:

````
linux32 make gcc-dom0
RPM_BUILD_DEFINES="--without crosshyp" linux32 make vmm-xen-dom0
linux32 make core-vchan-xen-dom0
linux32 make linux-utils-dom0
linux32 make gui-common-dom0
linux32 make vmm-xen-stubdom-linux-dom0
````

A noarch xen-hvm-stubdom-linux rpm will be produced, containing the 32-bit stubdomain.

### General notes:

- https://github.com/QubesOS/qubes-issues/issues/3651 affects 32-bit qemu worse than 64-bit, it  should be resolved first.
- KPTI mitigations for 32-bit kernels are not available in 4.14, these have been added to the 4.19 kernel.
- If a second build environment is setup, the stubdom can be compiled with a fc28 chroot, to get the latest library versions.
- Some XSA regression tests (from https://xenbits.xen.org/docs/xtf/test-index.html) are not being compiled or run for 32-bit PV, even if they're not listed to affect 64-bit domains only. I've compiled and tested the missing ones, and aside from the XSA-182 test (which dosen't compile) they seem to compile and run ok, so I'm not sure why they're not included for normal testing.

---

### Related issues:

https://github.com/QubesOS/qubes-issues/issues/3651

**Comment by marmarek** [comment]
From the security point of view, this indeed may be a good idea.

> Switching to 32-bit PV will also allow Xen XPTI mitigations to be disabled for 64-bit PV, which can improve dom0 performance.

That may not be a good idea in general, because users can still use PV by changing `virt_mode`. If going this way, we need to be absolutely sure that no other 64-bit PV domain is running first (for example preventing a start of such VM if XPTI for PV is disabled).

> If a second build environment is setup, the stubdom can be compiled with a fc28 chroot, to get the latest library versions.

As for the build, at this point it may be a better idea to build everything needed as part of the stubdomain build, instead of copying binaries from the build environment. It may be worth looking at OpenXT's stubdomain build which use OpenEmbedded, instead of manually doing that all from a single Makefile:
 - https://github.com/OpenXT/xenclient-oe/blob/master/recipes-core/images/xenclient-stubdomain-initramfs-image.bb
 - https://github.com/OpenXT/xenclient-oe/tree/master/recipes-openxt/qemu-dm

**Comment by marmarek** [comment]
> It may be worth looking at OpenXT's stubdomain build which use OpenEmbedded, instead of manually doing that all from a single Makefile

I didn't managed to convince OpenEmbedded to use native toolchain and building the whole toolchain just for the stubdomain seems like an overkill. What about adding BuildRequires with specific architecture? Like `gcc.i686`, `glibc.i686` (or uclibc) etc? Fedora do support multilib, so in theory it should work.

**Comment by marmarek** [comment]
32-bit PV support is getting remove from Xen, so it makes no sense to keep this task open. In the future, we'd like to make stubdomain a PVH, but that's totally separate issue.
