### ISSUE TITLE
Qubes OS 4. Switch screen background

### ISSUE THREAD

**Issue by Qubes123** [QubesOS/qubes-issues#4381]
how can I change the screen background of the official Qubes OS 4.? Please help me, I am new to the IT world. maybe someone knows how to copy in Qubes 4 directly to Dom0 or connect the USB stick directly to Dom0? ask for instructions with a detailed explanation. Thank you in advance !;)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by andrewdavidwong** [comment]
Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this does not appear to be suitable for `qubes-issues`. We ask that you please send this to the `qubes-users` [mailing list](https://www.qubes-os.org/support/) instead. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a brief comment explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.
