### ISSUE TITLE
Add Redshift to dom0 [Enhancement]

### ISSUE THREAD

**Issue by Simon-Davies** [QubesOS/qubes-issues#4382]
### Qubes OS version:

Qubes 4.0 (R4.0)

### Affected component(s): 

dom0

---

### General notes:

http://jonls.dk/redshift/

---

**Comment by andrewdavidwong** [comment]
You can already install this yourself in dom0:

https://www.qubes-os.org/doc/software-update-dom0/

I'm a Redshift user myself, but we will not install this by default:

https://www.qubes-os.org/faq/#what-is-qubes-attitude-toward-changing-guest-distros

**Comment by Simon-Davies** [comment]
sudo dnf install redshift:

No package redshift available.
Error: Unable to find a match.

How do I install it?
