### ISSUE TITLE
qubes-builder fails to build debian-9 template

### ISSUE THREAD

**Issue by emkll** [QubesOS/qubes-issues#4387]
### Qubes OS version:

R4.0

### Affected component(s): 

qubes-builder, building debian-9 templates

template used for building: fedora28

---

### Steps to reproduce the behavior:

1. git checkout qubesos/qubes-builder
2. copy debian.conf (taken from from https://github.com/QubesOS/qubes-template-configs/blob/master/R4.0/templates-itl/debian.conf) into builder.conf (and set NOSIGN=1)
3. `make install-deps`, `make get-sources`, `make qubes-vm`, `make template`

### Expected behavior:

`make template` should complete successfully.

### Actual behavior:

`make template` command returns the following error during the debootstrap process: 
```
+ cp /home/user/qubes-builder/qubes-src/linux-template-builder/mnt/var/lib/apt/lists/debootstrap.invalid_dists_stretch_Release /home/user/qubes-builder/qubes-src/linux-template-builder/mnt//tmp/dummy-repo/dists/stretch/Release
cp: cannot stat '/home/user/qubes-builder/qubes-src/linux-template-builder/mnt/var/lib/apt/lists/debootstrap.invalid_dists_stretch_Release': No such file or directory
+ error 'Debootstrap failed!'
+ output 'ERROR: Debootstrap' 'failed!'
+ '[' 2 -ge 1 ']'
+ [[ -z '' ]]
+ [[ ehB != ehxB ]]
+ exit 1
+ umount_kill /home/user/qubes-builder/qubes-src/linux-template-builder/mnt
+ '[' 2 -le 2 ']'
+ test -o xtrace
+ true 'umount_kill: Disabling xtrace, because variable VERBOSE (2) is lower than or equal 2...'
+ set +x
Attempting to kill any processes still running in '/home/user/qubes-builder/qubes-src/linux-template-builder/mnt' before un-mounting
INFO: umount /home/user/qubes-builder/qubes-src/linux-template-builder/mnt
+ true 'umount_kill: Restoring xtrace...'
make[1]: *** [Makefile:63: rootimg-build] Error 1
make: *** [Makefile:310: template-local-stretch+standard] Error 1
```

### General notes:

It appears this behavior has been introduced late last week, perhaps due to changes in Debian?

---

**Comment by redshiftzero** [comment]
Flagging for your prioritization that we're hitting this for SecureDrop (we want to make custom templates based on Debian)

**Comment by marmarek** [comment]
Hmm, recent test builds succeed: https://travis-ci.com/QubesOS/qubes-builder-debian
Last change in builder-debian was <1day ago, so it might fixed that. I'll try on fedora-28 (the above is on ubuntu)

**Comment by marmarek** [comment]
I can reproduce the problem on fedora-28, even with the most recent builder-debian. Looks like debootstrap behavior change in fedora-28.
