### ISSUE TITLE
Firefox unusable in dispvms "gah your tab just crashed"

### ISSUE THREAD

**Issue by vincentadultman** [QubesOS/qubes-issues#4389]
### Qubes OS version:
R3.2

### Affected component(s): 

Firefox, in dispvms (even after clean boot) but also sometimes in appvms. The latter seems only the case if the system has been up for some time (i.e. several days).

---

### Steps to reproduce the behavior:

Start a dispvm with the firefox menu shortcut as normal.

### Expected behavior:

Firefox tabs do not crash / the browser is usable. 

### Actual behavior:

Start a dispvm with the firefox menu shortcut as normal. It will either open a tab which will crash very quickly, or immediately display the mozilla crash reporter. 

Crash reporter log shows following

```BuildID: 20181002222838
CrashTime: 1539457685
FramePoisonBase: 9223372036600930304
FramePoisonSize: 4096
InstallTime: 1539457682
Notes: Debian GNU/Linux 9.5 (stretch)
ProductID: {ec8030f7-c20a-464f-9b0e-13a3a9e97384}
ProductName: Firefox
ReleaseChannel: default
SafeMode: 0
StartupCrash: 1
StartupTime: 1539457682
ThreadIdNameMapping: 900:"Gecko_IOThread",901:"Timer",902:"Link Monitor",903:"Socket Thread",904:"JS Watchdog",909:"BGReadURLs",910:"Hang Monitor",915:"Cache2 I/O",916:"Cookie",917:"StreamTrans #1",
Throttleable: 1
UptimeTS: 4.073257
Vendor: Mozilla
Version: 60.2.2

This report also contains technical information about the state of the application when it crashed.
```

When trying to run firefox from dispvm terminal
```
firefox

(firefox-esr:1088): dconf-WARNING **: unable to open file '/etc/dconf/db/local': Failed to open file '/etc/dconf/db/local': open() failed: No such file or directory; expect degraded performance

###!!! [Parent][MessageChannel] Error: (msgtype=0x150080,name=PBrowser::Msg_Destroy) Channel error: cannot send/recv


###!!! [Parent][MessageChannel] Error: (msgtype=0x150080,name=PBrowser::Msg_Destroy) Channel error: cannot send/recv

[Parent 1088, Gecko_IOThread] WARNING: pipe error (117): Connection reset by peer: file /build/firefox-esr-RlCnTw/firefox-esr-60.2.2esr/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 353
[Parent 1088, Gecko_IOThread] WARNING: pipe error (111): Connection reset by peer: file /build/firefox-esr-RlCnTw/firefox-esr-60.2.2esr/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 353
[Parent 1088, Gecko_IOThread] WARNING: pipe error (110): Connection reset by peer: file /build/firefox-esr-RlCnTw/firefox-esr-60.2.2esr/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 353
[Parent 1088, Gecko_IOThread] WARNING: pipe error (108): Connection reset by peer: file /build/firefox-esr-RlCnTw/firefox-esr-60.2.2esr/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 353
[Parent 1088, Gecko_IOThread] WARNING: pipe error (105): Connection reset by peer: file /build/firefox-esr-RlCnTw/firefox-esr-60.2.2esr/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 353

###!!! [Parent][MessageChannel] Error: (msgtype=0x150080,name=PBrowser::Msg_Destroy) Channel error: cannot send/recv

[Parent 1088, Gecko_IOThread] WARNING: pipe error (108): Connection reset by peer: file /build/firefox-esr-RlCnTw/firefox-esr-60.2.2esr/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 353

###!!! [Parent][MessageChannel] Error: (msgtype=0x150080,name=PBrowser::Msg_Destroy) Channel error: cannot send/recv


###!!! [Parent][MessageChannel] Error: (msgtype=0x150080,name=PBrowser::Msg_Destroy) Channel error: cannot send/recv

ExceptionHandler::GenerateDump cloned child 1253
ExceptionHandler::SendContinueSignalToChild sent continue signal to child
ExceptionHandler::WaitForContinueSignal waiting for continue signal...
```

### General notes:

I assumed my fc28 template had corrupted, but switch the default dispvm template to debian9 displays the same behavior. I would presume just an error with the current version of firefox, if firefox didn't behave correctly in appvms most of the time. Completely confused!

Chromium in debian dispvm seems to operate okay, but be a little wonky (extension crashes etc, but is much better than firefox).

I've considered this may be a memory issue with the laptop, but memory test comes back clean and appvms behave okay after clean boot...

---

**Comment by ncm** [comment]
This happened on 4.14, for me.  I had to turn off firefox/settings/general/performance/ hardware acceleration.

**Comment by andrewdavidwong** [comment]
Since we appear to have multiple confirmations that this is a Firefox bug rather than a Qubes bug, I've left this closed and added the `not our bug` label.

**Comment by ncm** [comment]
Agreed. I thought it would be helpful to have a note here with a solution since searches land here.

In order to eliminate the crashes, it turns out I *also* had to turn off "smooth scrolling", nearby.

**Comment by ncm** [comment]
I should mention, too, that turning off "multi-process support" had no apparent effect on the crashing, so it might be another Firefox bug.
