### ISSUE TITLE
Windows manager does not focus appropriately

### ISSUE THREAD

**Issue by e6lk7dqzm83p** [QubesOS/qubes-issues#4393]
### Qubes OS version:

4.14

### Affected component(s): 

Windows manager

---

### Steps to reproduce the behavior:

Click on a link in Thunderbird

### Expected behavior:

The link opens in the browser and either the browser is visible or the Thunderbird window is in focus

### Actual behavior:

The focus appears to go to the browse (i.e. the mouse/controls appear to be affecting the browser, Firefox), but the Thunderbird window is still visible and appears unresponsive as input devices are going to the browser.

### General notes:

---

**Comment by andrewdavidwong** [comment]
This appears to be a [duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) of #3267 or #1455 (or both). If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.
