### ISSUE TITLE
Screensaver does not prevent people from viewing screen

### ISSUE THREAD

**Issue by e6lk7dqzm83p** [QubesOS/qubes-issues#4394]
### Qubes OS version:

4.0

### Affected component(s): 

The display manager?

---

### Steps to reproduce the behavior:

Plug an external monitor into a qubes laptop but do not select which screen should be primary (this mirrors the laptop screen on the monitor)

### Expected behavior:

When the screensaver comes on it covers both the external monitor and the laptop's monitor so you **can** see the desktop/open windows.

### Actual behavior:

When the screensaver comes on it does not cover both the external monitor and the laptop's monitor so you can not see the desktop/open windows.

### General notes:

---

**Comment by andrewdavidwong** [comment]
I assume you're using the default DE (Xfce4) and screen locker (XScreenSaver). If this is not the case, please let us know.

**Comment by e6lk7dqzm83p** [comment]
@andrewdavidwong, yes, I am using the defaults.  Sorry about that.

**Comment by imestin** [comment]
(I want to follow this but I don't know how to do that in Github so I will just write something here)

**Comment by ThomasWaldmann** [comment]
@e6lk7dqzm83p can you edit your top post and fix the qubes version?

**Comment by e6lk7dqzm83p** [comment]
@ThomasWaldmann, yes, sorry about that!

**Comment by unman** [comment]
@e6lk7dqzm83p I'm not able to replicate this on any of the laptops I've tried, in either KDE or Xfce.
Can you kill xscreensaver, and then restart with  `xscreensaver -verbose`, and post output?

Also, can you try setting `GetViewPortIsFullofLies:True` in .xscreensaver  and see if that makes any difference to you.

**Comment by e6lk7dqzm83p** [comment]
@unman here's the output of `xcreensaver -verbose`
`
xscreensaver 5.37, copyright (c) 1991-2017 by Jamie Zawinski <jwz@jwz.org>.
xscreensaver: 17:41:04: running as hg/hg (1000/1001)
xscreensaver: 17:41:04: in process 11407.
xscreensaver: 17:41:05: running on display ":0.0"
xscreensaver: 17:41:05: vendor is Fedora Project, 11903000.
xscreensaver: 17:41:05: useful extensions:
xscreensaver: 17:41:05:   MIT Screen-Saver (disabled at compile time)
xscreensaver: 17:41:05:   Shared Memory (1.2)
xscreensaver: 17:41:05:   Double-Buffering (1.0)
xscreensaver: 17:41:05:   Power Management (1.1)
xscreensaver: 17:41:05:   GLX
xscreensaver: 17:41:05:   XF86 Video-Mode (2.2)
Xlib:  extension "XFree86-Misc" missing on display ":0.0".
xscreensaver: 17:41:05:   XC Misc (unavailable)
xscreensaver: 17:41:05:   Xinerama (1.1)
xscreensaver: 17:41:05:   Resize-and-Rotate (1.5)
xscreensaver: 17:41:05:   XInput
xscreensaver: 17:41:05: screen 0 non-colormapped depths: 24.
xscreensaver: 17:41:05: WARNING: RANDR and Xinerama report different
xscreensaver: 17:41:05: 		screen layouts!  Believing RANDR.
xscreensaver: 17:41:05: screens in use: 1
xscreensaver: 17:41:05:    0/0: 2048x1152+0+0 (eDP1)
xscreensaver: 17:41:05: rejected screens: 4
xscreensaver: 17:41:05:    1/0: 2048x1152+0+0 (DP1) -- output disabled
xscreensaver: 17:41:05:    2/0: 1920x1200+0+0 (HDMI1) -- overlaps 0 (2048x1152+0+0)
xscreensaver: 17:41:05:    3/0: 2048x1152+0+0 (HDMI2) -- output disabled
xscreensaver: 17:41:05:    4/0: 0x0+0+0 (VIRTUAL1) -- output disabled
xscreensaver: 17:41:05: selecting RANDR events
xscreensaver: 17:41:05: not using XInputExtension.
xscreensaver: 17:41:05: 0: visual 0x20 (TrueColor,   depth: 24, cmap: default)
xscreensaver: 17:41:05: 0: saver window is 0x2600001.
xscreensaver: 17:41:05: selecting events on extant windows... done.
xscreensaver: 17:41:05: awaiting idleness.
`

**Comment by e6lk7dqzm83p** [comment]
Hi, 
I did some testing.  I can't manually replicate the issue in total, but have noticed that if I select `Blank Screen Now` in Screensaver Preferences it blanks almost the whole screen (except for a small sliver on the bottom).

I'll let you know if the .xscreensaver modification changes any of the behaviors (I'm traveling for work the next several days so I'll have to do more experiments when I get back).

Thank you!

**Comment by marmarek** [comment]
> blanks almost the whole screen (except for a small sliver on the bottom).

I think the reason is in `2/0` screen below:

> xscreensaver: 17:41:05: screens in use: 1
> xscreensaver: 17:41:05: 0/0: 2048x1152+0+0 (eDP1)
> xscreensaver: 17:41:05: rejected screens: 4
> xscreensaver: 17:41:05: 1/0: 2048x1152+0+0 (DP1) -- output disabled
> xscreensaver: 17:41:05: 2/0: 1920x1200+0+0 (HDMI1) -- overlaps 0 (2048x1152+0+0)
> xscreensaver: 17:41:05: 3/0: 2048x1152+0+0 (HDMI2) -- output disabled
> xscreensaver: 17:41:05: 4/0: 0x0+0+0 (VIRTUAL1) -- output disabled

**Comment by e6lk7dqzm83p** [comment]
Hi @unman,

I've noticed that even with the modifications I did that the problem reoccurs.  I've copied the output of `xcreensaver -verbose`:

>xscreensaver 5.37, copyright (c) 1991-2017 by Jamie Zawinski <jwz@jwz.org>.
xscreensaver: 21:23:19: in process 11828.
xscreensaver: 21:23:19: running on display ":0.0"
xscreensaver: 21:23:19: vendor is Fedora Project, 11903000.
xscreensaver: 21:23:19: useful extensions:
xscreensaver: 21:23:19:   MIT Screen-Saver (disabled at compile time)
xscreensaver: 21:23:19:   Shared Memory (1.2)
xscreensaver: 21:23:19:   Double-Buffering (1.0)
xscreensaver: 21:23:19:   Power Management (1.1)
xscreensaver: 21:23:19:   GLX
xscreensaver: 21:23:19:   XF86 Video-Mode (2.2)
Xlib:  extension "XFree86-Misc" missing on display ":0.0".
xscreensaver: 21:23:19:   XC Misc (unavailable)
xscreensaver: 21:23:19:   Xinerama (1.1)
xscreensaver: 21:23:19:   Resize-and-Rotate (1.5)
xscreensaver: 21:23:19:   XInput
xscreensaver: 21:23:19: screen 0 non-colormapped depths: 24.
xscreensaver: 21:23:19: screens in use: 1
xscreensaver: 21:23:19:    0/0: 2048x1152+0+0
xscreensaver: 21:23:19: rejected screens: 1
xscreensaver: 21:23:19:    1/0: 1920x1200+0+0 -- overlaps 0 (2048x1152+0+0)
xscreensaver: 21:23:19: selecting RANDR events
xscreensaver: 21:23:19: not using XInputExtension.
xscreensaver: 21:23:19: 0: visual 0x20 (TrueColor,   depth: 24, cmap: default)
xscreensaver: 21:23:19: 0: saver window is 0x2800001.
xscreensaver: 21:23:19: selecting events on extant windows... done.
xscreensaver: 21:23:19: awaiting idleness.

**Comment by e6lk7dqzm83p** [comment]
Possibly related issue, I am not able to lock my screen now.

**Comment by e6lk7dqzm83p** [comment]
Hi, 

Any further thoughts on this?

Thanks!

**Comment by euidzero** [comment]
Just experimented this with 4.1
Default xfce session. No dedicated dispVM.

The whole external screen was visible, the xscreensaver prompt was invisible but the mouse was locked into the prompt window space. Only the external display is active.

Xorg.0.log is being filled with "modeset(0): Page flip failed : Device or resource busy" and "present flip failed".
