### ISSUE TITLE
Add CPU usage to qui-domains widget

### ISSUE THREAD

**Issue by marmarta** [QubesOS/qubes-issues#4401]
### Qubes OS version:
R4.0

Add some sort of CPU percentage to qui-domains widgets. I'm not sure about the graphic presentation - maybe not to the widget itself but to the qube manager? It should be available from _somewhere_.

### Related issues:
https://github.com/QubesOS/qubes-issues/issues/3241

**Comment by brendanhoar** [comment]
A workaround is running the following in a dom0 window (preferably widened or maximized so it doesn't wrap each line):

xl top

Brendan

**Comment by esote** [comment]
> xl top

Just runs `xentop`, and with `xentop` you can use flags like `--iterations=N` or `--batch`.

**Comment by andrewdavidwong** [comment]
Is this just a duplicate of #4531 now?

**Comment by marmarta** [comment]
Yup, can be safely closed.
