### ISSUE TITLE
issues with qubes-builder-archlinux

### ISSUE THREAD

**Issue by aluquest** [QubesOS/qubes-issues#4405]
### Qubes OS version:

Qubes release 4.0 (R4.0)

### Affected component(s): 

Building archlinux template using scripts from: 
https://github.com/QubesOS/qubes-builder-archlinux/

---

### Steps to reproduce the behavior:

Follow this guide until step5: https://www.qubes-os.org/doc/building-archlinux-template/
Then follow the steps under "Steps to reproduce the behavior" from: https://github.com/QubesOS/qubes-issues/issues/3185

### Expected behavior:

archlinux template will build without errors

### Actual behavior:

Template fails to build because:
1) ttf-symbola package listed in https://github.com/QubesOS/qubes-builder-archlinux/blob/master/scripts/packages.list no longer exists as an official package (just remove the package from the file?)
2) in file https://github.com/QubesOS/qubes-builder-archlinux/blob/master/scripts/04_install_qubes.sh:
lines 26-28 should not have "# QubesTMP" in them, but should simply be:

echo "  --> Registering Qubes custom repository..."
cat >> "${INSTALLDIR}/etc/pacman.conf" <<EOF
[qubes]
SigLevel = Optional TrustAll
Server = file:///tmp/qubes-packages-mirror-repo/pkgs
EOF

### General notes:

Should I create a new issue regarding my mailing list post here: https://groups.google.com/forum/#!topic/qubes-users/fkcla6Nmpg8
regarding not being able to update the archlinux template? Is it worth trying to make this template successfully work?

---

### Related issues:

https://groups.google.com/forum/#!topic/qubes-users/fkcla6Nmpg8

**Comment by virtualdxs** [comment]
Regarding ttf-symbola, I had opened a pull request (https://github.com/QubesOS/qubes-builder-archlinux/pull/20), but closed it because I wanted to ensure that the build worked first. Thinking about it now, I'm just reopened it because it's such a straightforward change that it shouldn't cause any other problems (even if it does, that would only be because things reference the old package, which would fail anyway).

**Comment by virtualdxs** [comment]
I was able to build it adding ttf-symbola. `#QubesTMP` is in there for a reason, to disable that repo when done.

**Comment by zaoqi** [comment]
It was fixed
