### ISSUE TITLE
Installer and resulting install fails to detect IOMMU

### ISSUE THREAD

**Issue by achow101** [QubesOS/qubes-issues#4407]
### Qubes OS version:

R4.0

### Affected component(s): 

The installer, and the subsequent installed OS.

---

### Steps to reproduce the behavior:

Attempt to install on a system with an AMD threadripper 2950x CPU.

### Expected behavior:

The installer gives no warnings or errors and the installation works as normal. The resulting installation also works as normal

### Actual behavior:

A warning is given that hardware support for IOMMU and remapping interrupts was not detected. Ignoring the warning and continuing with the installation results in an installation that is unable to start any of the VMs due to failing to initialize/detect IOMMU.

### General notes:

I've been trying to install Qubes 4.0 on my new computer. It has an AMD Threadripper 2950x and an ASRock X399 Taichi motherboard. I have the latest BIOS from ASRock and I have enabled SVM mode (which enables the AMD-V stuff), IOMMU, and SR-IOV (Single Root IO Virtualization Support)  support. Those were the only options in the BIOS related to virtualization. The installer still says that it cannot detect IOMMU and remapping interrupts. However on an ubuntu install, I can see that AMD-V and IOMMU are both available. If I ignore the warning and continue with the installation, it does install. On first boot however, it is unable to start the VMs after configuring them. Once I login to dom0, I still can't start any VMs. Also, in `/boot/efi/EFI/qubes`, I no `xen.efi` file and an empty `xen.cfg`. There is a `xen-<some version>.efi` file.

**Comment by esote** [comment]
Perhaps whatever version of Xen / the dom0 kernel the installer comes with doesn't support IOMMU on the newer hardware. Just a guess.

**Comment by JarrahG** [comment]
This seems to be an exact replica of #4309. There is a patch in that thread that you'll have to add to xen to get it to recognize the IOMMU. 

Few options for you:
- Install from your current ISO, get a console and set sys-net, sys-firewall and sys-usb to use pv. post this you would have to update, compile vmm-xen with the patch and install it. 
- Compile a new qubes ISO yourself including the patch and install the latest version. 

Either way, systems been stable for about 18 hours now. That patch solves the problem. When it's installed, I recommend removing any config you've put into xen.cfg, that caused me some  problems on first boot. 

Good luck.

**Comment by achow101** [comment]
@JarrahG I actually that thought was the case, and I have been trying to build a new Qubes ISO myself but am running into a lot of problems (probably because I am unfamiliar with how qubes-builder works). I didn't realize that it was possible to compile and install vmm-xen with the patch from within the current install, so I'll try that next.

Closing as a duplicate of #4309.

**Comment by JarrahG** [comment]
I ran into a heap. That patch was released on the 6th, I only managed to get it working yesterday. 
If you go the route of compiling vmm-xen, you'll need to compile gcc first. Assuming that works and the sources download/git submodule download works, it should compile fine. Sadly there's no multithreading in the gcc build, so even on the 2950x it'll take about 4 hours.

When you compile vmm-xen, it'll output a list of RPMs. One will be xen-hypervisor-xxx.rpm. You'll want to move that over to dom0 to install. Just make sure you're running on the latest version of qubes. Update everything before you install the package.

**Comment by achow101** [comment]
Do you have any suggestions and/or a guide for how to build an ISO with that vmm-xen patch? I'm currently attempting (another) ISO build. Although if all I need are the the vmm-xen RPMs, I think this time I'll grab the vmm-xen RPMs once the build fails (because it probably will) and install them.

**Comment by JarrahG** [comment]
For the most part I bumbled around with the steps here: https://www.qubes-os.org/doc/qubes-r3-building/ though I assume you've done that.

Before you kick off the whole compile, go to `qubes-src/vmm-xen`, add Mareks repository as a remote, fetch and cherry pick the commit. 

Rather than running `make qubes`, simply issuing `make gcc &&  make vmm-xen` would only build the necessary parts. 

If you want to trust a random person on the internet with compiling software, I've attached the compiled RPM that I am using. 
```
1241ef07d6a4e3f980b7977d0c13024e1a05d61260acb68d4f3520001a1b2ad7  xen-hypervisor-4.8.4-5.fc25.x86_64.rpm
```

**Comment by marmarek** [comment]
You can save the gcc building time, by adding `USE_QUBES_REPO_VERSION = 4.0` to your `builder.conf`. This will download missing packages from the repository, so you can go straight to `make vmm-xen`. Or even `make vmm-xen-dom0` to build only dom0 package.
