### ISSUE TITLE
Debian-9 template not found when using qubes-dom0-update

### ISSUE THREAD

**Issue by unman** [QubesOS/qubes-issues#4410]
### Qubes OS version:

R4.0
(perhaps other)

### Affected component(s): 

Qubes infrastructure
Repository

---

### Steps to reproduce the behavior:

`sudo qubes-dom0-update qubes-template-debian-9`

### Expected behavior:

Debian-9 template is installed

### Actual behavior:

> No match for argument qubes-template-debian-9

### General notes:

templates-itl is enabled.

qubes-template-debian-8 works fine, as do Fedora templates.

Debian-9 templates are to be found at yum.qubes-os.org

---

**Comment by airelemental** [comment]
Same here, although I already have debian-9 installed.
This command seems to find the package:
`sudo qubes-dom0-update --action=upgrade qubes-template-debian-9`

**Comment by TNTBOMBOM** [comment]
same here nothing is working

**Comment by marmarek** [comment]
I cannot reproduce. With `--action=upgrade` I get "Nothing to do." as I already have newest version. With `--action=reinstall` the template is found and reinstalled.
Note that `--action=reinstall` will look for exactly the same template version. If that was some local build, or testing version not moved to stable, it will not found it (error message: "Installed package ... not available." and "Error: No packages marked for reinstall."). In that case, you can still try `--action=upgrade` (or even `--action=downgrade`, but it will install older version). Or, if that was from qubes-templates-itl-testing repository, you can enable it with `--enablerepo=qubes-templates-itl-testing`.

**Comment by TNTBOMBOM** [comment]
--action=reinstall just worked for me now

**Comment by marmarek** [comment]
@unman as for your initial report - the exact command you posted will work only if you don't have the template installed yet. Otherwise explicit action is needed.

**Comment by unman** [comment]
Right, and I hadn't realised that `--action=reinstall` will look for the same package version.
mea culpa

**Comment by andrewdavidwong** [comment]
The existing UX issue for this is #3299.
