### ISSUE TITLE
Gentoo template

### ISSUE THREAD

**Issue by fepitre** [QubesOS/qubes-issues#4412]
Creation of Gentoo template for QubesOS

Tasks:
- [x] build the template
- [x] document
- [x] upload to testing repo
- [x] migrate to stable repo
- [x] announce

If any issue affects Gentoo specifically (build failures, things that worked fine before etc), please add reference to this issue too.

cc @marmarek

**Comment by fepitre** [comment]
Almost one year ago I was doing some work around Gentoo template. There exist gentoo branches on my repository that I left as a pending work. As there is more and more question about a Gentoo template on QubesOS, I decided to restart/continue this work. Even if it is not my priority, it is fun to do it.

**Comment by TNTBOMBOM** [comment]
good luck!

**Comment by 0rb677** [comment]
@fepitre  Do you need a prebuilt gentoo template? 
I use it 6th month but need `qubes-meta` package gentoo maintainer. Maybe it helps to your work?

**Comment by fepitre** [comment]
@0rb677: currently I'm mostly lacking time and priority on this task. I'll try to move on a little bit as it misses few packages to have a workable template.

**Comment by fepitre** [comment]
![Screenshot_qubesos4 0-upgrade_2020-07-20_16:30:34](https://user-images.githubusercontent.com/26125607/87949837-d3803c80-caa6-11ea-884a-8f4691b4e227.png)
It shows a standard GNOME Qubes template under Gentoo. Be patient, announcement and a summary of current achievements and work is coming very soon.

**Comment by minic0m** [comment]
@fepitre thanks a lot wor your work! any chance to get  a prebuild beta template for play with it? :)

**Comment by fepitre** [comment]
@minic0m: Yes. I'm currently finishing and polishing the whole signature check and integration pipeline of the overlay and the Qubes sources at emerge time. I'm launching the build in few hours and testing the templates. I'm preparing the announcement at the time I'm writing to you. I should send it tomorrow morning. I plan to provide (links to my mirror) release candidate templates (Minimal, Gnome and XFCE) together with the announcement.

**Comment by fepitre** [comment]
@minic0m: we delay the announcement with proper references and PR for the next week as we want to release the templates in Qubes repositories directly. That let me time to prepare (automatic) validation tests :)

**Comment by 0rb677** [comment]
@fepitre is it possible to try it on 4.0 release?

**Comment by fepitre** [comment]
@0rb677 no that will be only for 4.1. It's currently into our validation test suites.

**Comment by blackva** [comment]
@fepitre when do you think 4.1 beta is going to be released? Really exited to try the template :)

**Comment by fepitre** [comment]
> @fepitre when do you think 4.1 beta is going to be released? Really exited to try the template :)

You can already test Qubes R4.1 with ISO found in our testing platform: https://openqa.qubes-os.org. For example a working ISO: https://openqa.qubes-os.org/tests/11537/asset/iso/Qubes-4.1-20200830-x86_64.iso. It's a matter of days (depending on availability of @marmarek) because we are surrounded by others critical tasks.

**Comment by 0rb677** [comment]
> @fepitre when do you think 4.1 beta is going to be released? Really exited to try the template :)

4.1 is absolute pre-alfa. It works slow on x220 instead 4.0 (maybe not optimized yet)

**Comment by fepitre** [comment]
Some of you have probably noticed that the template has been uploaded in current-testing of R4.1 :) A proper announcement is in preparation by @andrewdavidwong.

**Comment by 0rb677** [comment]
> Some of you have probably noticed that the template has been uploaded in current-testing of R4.1 :) A proper announcement is in preparation by @andrewdavidwong.

Any working 4.1 iso? 

https://openqa.qubes-os.org/tests/11537/asset/iso/Qubes-4.1-20200830-x86_64.iso

This build based on 4.14 hard freezes after install. Clicking on buttons doesn’t work. Can’t do anything

**Comment by fepitre** [comment]
@marmarek @andrewdavidwong I've uploaded to stable repository. Maybe it's time for closing this issue?
