### ISSUE TITLE
Qubes R4 Installer halt on nvm drive section

### ISSUE THREAD

**Issue by flomo29** [QubesOS/qubes-issues#4421]
Hi. First i wrote the Qubes R4 ISO to a sd card with etcher on a macbook and then boot
from it on the newest intel nuc with i7-8809G processor and intel visual bios with only uefi and no legacy boot option.

in oppsite to the Qubes R3.2 installer which showed me the grub boot menu with "Install Qubes R3.2",
Qubes R4 boots without the grub menu directly and after initializing the nvme drive, it stopped
and a dracut initqueue timout occured.

on a forum a user wrote that i could be occure because the file path of the nvm driver changes in the linux kernel and the initial ramdisk does not reflect that so the driver will not be found.
but i can see that the kernel can see the nvm drive correctly.

**Comment by ThomasWaldmann** [comment]
@flomo29 i recently installed qubes 4.0.1-rc1 on a ThinkPad T470s (which also has a NVME SSD and thus requires UEFI booting). Everything worked. The T470 entry on the HCL links to these instructions, which worked for me: https://www.qubes-os.org/doc/thinkpad-troubleshooting/
