### ISSUE TITLE
Transfering text file from dom0 to appvm doesnt open Qubesincoming folder

### ISSUE THREAD

**Issue by TNTBOMBOM** [QubesOS/qubes-issues#4423]
### Qubes OS version:

Qubes 4

### Affected component(s): 

Qubes dom0 -> AppVM file transfer

---

### Steps to reproduce the behavior:

- Open dom0 terminal , and create a text file using `> file` command
- try to transfer the file to any appvm using 

`qvm-run --pass-io debian 'cat> file.txt' < /home/user/file`

### Expected behavior:

It should open a folder with qubesincoming or something like that and the transferred content should be there no?

### Actual behavior:

the file transferred without being contained in a folder.

**Comment by unman** [comment]
> It should open a folder with qubesincoming or something like that and the transferred content should be there no?

No. 
You have explicitly passed the file using `cat >file.txt`. This is handled on the target in context of user profile, using ~ , so the file ends up as /home/user/file.txt. (If you specify `-u root`, then the file will be created in /root/file.txt)
**Any** file passed in this way will do the same, not just txt files.
If you want to create the file in a different location on the target you can give an absolute path, or write path relative to ~

You can use `qvm-copy-to-vm` in dom0, and this **will** end up in QubesIncoming on the target.

**Comment by TNTBOMBOM** [comment]
i see great then , thats solve it. Thx
