### ISSUE TITLE
qvm-create allows creation of an AppVM with --root-copy-from or --root-move-from

### ISSUE THREAD

**Issue by virtualdxs** [QubesOS/qubes-issues#4424]
### Qubes OS version:
R4.0

### Affected component(s): 
HVM Qubes

---
### Steps to reproduce the behavior:
    qvm-create chr --property virt_mode=hvm --label red --root-copy-from ~/chr-6.43.4.img
    qvm-prefs chr memory 512
    qvm-prefs chr debug true
    qvm-prefs chr kernel ''
    qvm-start chr

### Expected behavior:
Qube boots and stays booted

### Actual behavior:
Qube boots, but is killed after 30 seconds because the host cannot connect to qrexe

### General notes:
According to https://dev.qubes-os.org/projects/core-admin-client/en/latest/manpages/qvm-features.html#qrexec, the default is to assume the qube doesn't have qrexec and not kill it. This seems to contradict that. I have tried both ensuring that the qrexec feature is unset and explicitly setting it to false to no avail.

---
### Related issues:
None I'm aware of

**Comment by virtualdxs** [comment]
I figured out that it was because it was being created as an AppVM not a StandaloneVM. Should this issue be closed? I could see wanting to keep it open to decide what to do about this, as it's not ideal that you can choose a root image and have it still be an AppVM. Not sure if I'm making much sense as it's a bit late here and I haven't had coffee since morning lol

**Comment by marmarek** [comment]
> as it's not ideal that you can choose a root image and have it still be an AppVM.

Yes, keep it open, qvm-create should refuse this option.

**Comment by sptankard** [comment]
I think I am running into this problem while trying to do a manual upgrade of a fedora-28 template to f29.

After executing `sudo dnf system-upgrade reboot --allowerasing --best`, the qube shuts down and when i start it again with `qvm-start ...`, it exits saying that it cannot connect to qrexec agent for 60 seconds.

Looking at the logs, it doesnt appear that it crashed, it looks like it was powered off by dom0 while in the middle of performing the upgrade.

Note:
I am not following the instructions at https://www.qubes-os.org/doc/template/fedora/upgrade-27-to-28/
Instead, i am following the instructions at https://fedoramagazine.org/upgrading-fedora-28-fedora-29/

**Comment by marmarek** [comment]
> I think I am running into this problem while trying to do a manual upgrade of a fedora-28 template to f29.

This may look similar, but I think it's a different one: original issue is about qubes expecting qrexec, while in fact it isn't there; your issue is about too short qrexec timeout.

> Looking at the logs, it doesnt appear that it crashed, it looks like it was powered off by dom0 while in the middle of performing the upgrade.

By default qrexec timeout is 60 seconds. You may try to either set it to something bigger (1800 - 30min?), or temporary tell qubes to not expect qrexec at all: `qvm-features fedora-29 qrexec ''`. As soon the VM will propertly boot including qrexec-agent, dom0 should detect it automatically and 'qrexec' feature back to '1'.
