### ISSUE TITLE
No AppVMs boot

### ISSUE THREAD

**Issue by virtualdxs** [QubesOS/qubes-issues#4428]
### Qubes OS version:
R4.0

Excuse me for not using the template, but I'm on mobile since I can't get network on my laptop. 

I'm getting a kernel panic whenever I try to boot any appvm. Here is the console output:

https://imgur.com/a/tpsUmjE

Again, I apologize for not using the template or providing output as text.

Let me know if any more info is needed.

**Comment by virtualdxs** [comment]
Is there any more information I can give to diagnose this? It was working great, but then I rebooted. It may have been an update that caused it.

**Comment by marmarek** [comment]
It's looking for xvda3, but you have only xvda1 and xvda2 devices there. xvda is root volume of template, where the actual system is installed. I don't know what happened that one partition have disappeared from there, but something must have gone horribly wrong.
Try switching that VM to a different template. If that helps, the easiest thing would be to reinstall that broken template, see https://www.qubes-os.org/doc/reinstall-template/

**Comment by virtualdxs** [comment]
That worked! I'll reinstall the fedora template and report back, but I'm certain enough that will fix it that I'll close this now. Thank you!

**Comment by virtualdxs** [comment]
Welp. Reinstalling fedora-26 deleted /var/lib/qubes/vm-templates/fedora-26 and didn't replace it. Any ideas?

**Comment by virtualdxs** [comment]
To be more specific, I get the error "ERROR: Missing image file: /var/lib/qubes/vm-templates/fedora-26/root.img"

**Comment by lunarthegrey** [comment]
You can try installing the Fedora 28 template. Since Fedora 26 is EOL it'd probably be best to install 28 and just switch the template for your AppVM.

`sudo qubes-dom0-update qubes-template-fedora-28`

Did it actually reinstall the template? What is the output of `dnf list installed | grep fedora`

**Comment by virtualdxs** [comment]
Installing fedora-28 works as expected. Thanks!

**Comment by lunarthegrey** [comment]
> It does in fact list qubes-template-fedora-26.noarch. I'll go ahead and install 28 and report back. I'd be happy to help figure out what's wrong with 26 as well if you like.

You could try to completely uninstall it and then install it again. Not sure if that would make any difference.

> Installing fedora-28 works as expected. Thanks!

Glad to hear! I would stick with fedora-28 honestly, since 26 is EOL.
