### ISSUE TITLE
/etc/qubes-rpc/qubes.GetAppmenus: Syntax error: "(" unexpected

### ISSUE THREAD

**Issue by TNTBOMBOM** [QubesOS/qubes-issues#4435]
### Qubes OS version:

R 4

### Affected component(s): 

qubes.GetAppmenus

---

### Steps to reproduce the behavior:

Make sure your Qubes is updated. (after Qubes latest stable updates , it showed up)

### Expected behavior:

error like this should be fixed

### Actual behavior:

![qubesrpcerror](https://user-images.githubusercontent.com/11895339/47543195-933f5a80-d8d0-11e8-9e9c-eecdab8a73a3.png)

**Comment by marmarek** [comment]
Duplicate of #4417
