### ISSUE TITLE
Cannot boot from disk block device

### ISSUE THREAD

**Issue by unman** [QubesOS/qubes-issues#4438]
### Qubes OS version:

R4.0

### Affected component(s): 

qvm-start

---

### Steps to reproduce the behavior:

Create standalone HVM.
Set kernel none and fix up memory.
Have bootable USB device (tested on other machine), or imaged device, at (say) sys-usb:sda
`qvm-start qube --hddisk sys-usb:sda`

### Expected behavior:

qube boots.

### Actual behavior:

qube starts, but boot fails.
Depending on qvm-start arguments (--hddisk or --cdrom) I get different errors:
All Boot failed.
Using --hddisk:

> not a bootable device

Using --cdrom:

> Booting from DVD/CD..
> Boot failed: Could not read from CDROM (code 0005)

### General notes:

I'm not surprised at the failure and results of using `--cdrom`.

This is a windows recovery drive. Tested and working on other machine,

---

### Related issues:

I dont think this is the same as #4092 but there isn't enough detail there for me to tell.
Certainly it's not a problem with kernel options incorrectly set.

**Comment by jsmaniac** [comment]
The `--cdrom` option now seems to work when `kernel=(none)` in the avanced tab of the qube's properties, but the `--hddisk` option still does not work, it seems.

I was able to boot an HVM qube with `kernel=(none)` using the x86_32 and _64 Haiku-OS `haiku-release-anyboot.iso` via the `--cdrom` option (or equivalently via the `--drive cdrom:…`), but not via the `--hddisk` (equivalently `--drive hd:…`).

With the `--hddisk` option SeaBIOS prints:
```
…
Booting from Hard Disk...
Boot failed: not a bootable disk
…
```

The `.iso` is an anyboot one, meaning that it can be booted as-is when flashed to a hard disk or USB (disclaimer: I didn't check this particular file on real hardware).

**Comment by larpilla** [comment]
Affects 4.2.4

**Comment by ben-grande** [comment]
@unman Can you check if this has been solved?
