### ISSUE TITLE
Ubuntu build fails for 3.2

### ISSUE THREAD

**Issue by unman** [QubesOS/qubes-issues#4439]
### Qubes OS version:

4.0

### Affected component(s): 

Qubes builder

---

### Steps to reproduce the behavior:

Attempt to build bionic template for 3.2

### Expected behavior:

Build succeeds

### Actual behavior:

Debootstrap fails: apt-transport-https not available

### General notes:

Package is available but it is universe repositories.
By default, only "main" is loaded.

---

**Comment by keldnorman** [comment]
Hi unman, I saw you fixed the problem and had a successful build ( https://qubes.3isec.org/Templates_4.0/ ) 

What files did you alter to fix the "E: Couldn't find these debs: apt-transport-https" problem ?

[user@dev26 qubes-builder]$ make clean; make install-deps && make get-sources && make qubes-vm && make template^C
[user@dev26 qubes-builder]$ tail -n 10 build-logs/template-bionic.log
I: Checking Release signature
I: Valid Release signature (key id xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx)
I: Validating Packages 
I: Resolving dependencies of required packages...
I: Resolving dependencies of base packages...
I: Found additional required dependencies:  
I: Found additional base dependencies: libeatmydata1 tasksel-data 
I: Checking component main on http://archive.ubuntu.com/ubuntu...
E: Couldn't find these debs: apt-transport-https
make[1]: *** [Makefile:63: rootimg-build] Error 1

**Comment by unman** [comment]
@keldnorman Regrettably not. Those images were built before Marek pushed [this](https://github.com/QubesOS/qubes-builder-debian/commit/3a0e37e0872b7a64e63e6114fa60f9d605edd689#diff-823dee39572a198bbc31b71287940df6)
Fixing this should be simple - just adding universe to the repos. But, I checked this and the package sometimes isnt there , although an updated version is in bionic-security. And _that_ causes issues because debootstrap only handles one repository(see #4447).
I'm still trying to work out the logic of handling two repos, although the code in builder-debian clearly envisages doing this.
An added wrinkle is that security.ubuntu stores the packages in (e.g) security/bionic , and the existing code cant handle that.

**Comment by marmarek** [comment]
One solution could be running debootstrap from http mirror (which I think already is the case) and installing apt-transport-https later, after adding other repositories.

BTW @unman if you want, you can add handling your repositories in `template_qubuntu/distribution.sh` (a symlink to template_debian) in `installQubesRepo` function (or add another, ubuntu-specific, similar function). This will allow testing template build on travis. But keep in mind it will also increase traffic on your server.

**Comment by unman** [comment]
> One solution could be running debootstrap from http mirror (which I think already is the case) and installing apt-transport-https later, after adding other repositories.

Yes, this is what I'm looking at.

**Comment by unman** [comment]
KISS.After merge of https://github.com/QubesOS/qubes-meta-packages/pull/4 and https://github.com/QubesOS/qubes-core-agent-linux/pull/142, Ubuntu templates can be built. Closing.
