### ISSUE TITLE
Packet loss on wifi on fedora-28 NetVM

### ISSUE THREAD

**Issue by virtualdxs** [QubesOS/qubes-issues#4440]
### Qubes OS version:
R4.0

### Affected component(s): 
Networking

---
### Steps to reproduce the behavior:
Run mtr from an AppVM

### Expected behavior:
Little to no packet loss

### Actual behavior:
```
                                                                My traceroute  [v0.92]
personal (10.137.0.7)                                                                                                 2018-10-26T09:27:49-0700
Keys:  Help   Display mode   Restart statistics   Order of fields   quit

                             Last 113 pings
 1. _gateway                 .................................................................................................................
 2. 10.137.0.3               .................................................................................................................
 3. 192.168.x.1              ........????????..........................................................>???????????????????????????????.......
 4. 66-xxx-xxx-xxx.static.ctl ........????????...........................................................???????????????????????????????.......
 5. ae1-90G.ar7.LAX1.gblx.ne ........????????...........................................................???????????????????????????????.......
 6. ae10.edge1.LosAngeles9.L ........????????...........................................................???????????????????????????????.......
 7. 4.69.153.117             ........????????...........................................................??????????????????????????????........
 8. 4.68.73.62               .......????????............................................................??????????????????????????????........
 9. cloudflare.losangeles2.l .......????????............................................................??????????????????????????????........
10. one.one.one.one          .......????????............................................................??????????????????????????????........

Scale:  .:1 ms  1:6 ms  2:13 ms  3:24 ms  a:38 ms  b:54 ms  c:74 ms  >


```
### General notes:
I hadn't used Qubes with fedora-26 all that much so I can't know if the issue is present there.
I have noticed this on two completely separate networks, plus the mtr shows that the loss is between sys-net and the wifi network's gateway.
I haven't had a chance to test wired yet, but I plan to today.

---
### Related issues:
None I could find

**Comment by lunarthegrey** [comment]
Your MTR is lacking the packet loss info. Why does it look so weird?

**Comment by marmarek** [comment]
Do you see any worrying kernel messages when this happen?

**Comment by virtualdxs** [comment]
@lunarthegrey I put it in a different display mode to show they're in groups of downtime.

**Comment by virtualdxs** [comment]
@marmarek It may just be those two networks. I'll do more testing tomorrow.

**Comment by lunarthegrey** [comment]
@virtualdxs Can you show a regular `mtr -rw 1.1.1.1`

It's impossible to tell from that snippet where the packet loss is or even starts. Will be interested to see what you find.

**Comment by virtualdxs** [comment]
@lunarthegrey I assume you're on mobile then. On desktop it looks as expected; question marks indicate no reply. Loss is always between 10.137.0.3 and 192.168.x.1. If you would still like me to, I'll get a standard mtr next time I'm there (Friday - I have multiple jobs).

I tested wireless and wired at one of the problem sites. Wired doesn't have this problem. Wireless is a UniFi setup. The other site I'll be at again Wednesday evening, and I'll collect the same data from there.

**Comment by lunarthegrey** [comment]
I see, just very confused about the format and haven't seen it before. I'm on desktop. An `mtr -rw` would be nice from both sites. It's weird that you can see the route but can't reach anything along the way. Can you ping sys-net from the VM or try to run the MTR directly from sys-net as well?

**Comment by virtualdxs** [comment]
Let me clarify what it's demonstrating. Sometimes it works, and at that point it collects the route information. Every packet it sends it gets a response (`.`). Then it stops working, but mtr remembers the route. Every packet it sends does not get a response (`?`). Then it starts working again, and it records `.`s. Then it stops again, and records `?`s. Does the format make more sense now? It may make more sense to you if you see it in action. Start an MTR and press d, then disconnect your network (or drop your default route) and see what happens to the display.

**Comment by virtualdxs** [comment]
I haven't reproduced it, so I'll close it until such time as I do.
