### ISSUE TITLE
Trying to use seamless mode in Windows 10 breaks HVM

### ISSUE THREAD

**Issue by e6lk7dqzm83p** [QubesOS/qubes-issues#4441]
### Qubes OS version:

4.0

### Affected component(s): 

Windows/Qubes Windows Tools (Using Windows 10)

---

### Steps to reproduce the behavior:

Launch an application from the dom0 terminal, such as `qvm-run -a my-win10-appvm explorer.exe`

### Expected behavior:

The application doesn't change the behavior of the HVM.

### Actual behavior:

I'm unable to get a GUI even if I launch the TemplateVM on its own or run an AppVM derived from my Windows 10 TemplateVM

### General notes:

I am aware Seamless mode isn't supported for Windows 10 and likely never will be, this is due to the change in the behavior of the HVM after I try to use Seamless mode.

Also, the Windows/Windows tools documentation is not up to date.

---

### Related issues:

#1861

**Comment by andrewdavidwong** [comment]
> Also, the Windows/Windows tools documentation is not up to date.

The documentation is a community effort. Please help us improve it by submitting a pull request:

https://www.qubes-os.org/doc/doc-guidelines/

If you can't, please open a separate issue.
