### ISSUE TITLE
User FAQ: How to use a terminal/the command-line interface?

### ISSUE THREAD

**Issue by tokideveloper** [QubesOS/qubes-issues#4445]
forked and quoted from [#4179](https://github.com/QubesOS/qubes-issues/issues/4179#issuecomment-433437281):

> > On [the user FAQ page](https://www.qubes-os.org/faq/#users), we could add the question _How to use a terminal/the command-line interface?_ and, as an answer, provide a link to the Wikipedia article about e.g. [the command-line interface](https://en.wikipedia.org/wiki/Command-line_interface) since Wikipedia exists in many languages. Alternatively, we could also add a new doc page explaining it all by ourselves.
> 
> The first option is better for the reasons already covered. We don't want to maintain any documentation about this general, non-Qubes-specific topic when we can't even maintain our own Qubes-specific documentation!

So, this issue concerns how to solve that problem. Of course, other resources than Wikipedia and other ways than the mentioned ones shall also be allowed to be discussed here.

**Comment by tokideveloper** [comment]
Here are my thoughts: Instead of teaching it by ourselves, linking to a good resource could be sufficient. With "good", I mean

- multilingual (i.e. the *same content* in multiple languages),
- available,
- correct,
- easy to understand,
- practical, not theoretical and not just informative,
- concise and
- only showing how to use it in order to accomplish a task, not how to use it in order to code new scripts.

Did I miss something?

Unfortunately, it seems to be difficult to find a resource that matches at least the last item. Note that in our doc, the commands to execute are mostly already written-out (besides small adjustments). The user just has to type or copy/paste them into the terminal. No programming skills required.

**Comment by tokideveloper** [comment]
Concerning **Wikipedia** and **Wikibooks**:

The Wikipedia articles are too noisy IMHO, see e.g. [[1]], [[2]], [[3]], [[4]]. If you don't know what to focus on, you will get lost quickly. Also, the articles of the other languages don't match each other.

Wikibooks are more concise but mostly overkill for our purpose IMHO (leads to demotivation), see e.g. [[5]], [[6]]. In addition, these books are even lesser translated than Wikipedia articles.

The only at least practical (but not multilingual) Wikibook (chapter) I could find in a quick way is [this one].

Of course, we could also create our own Wikipedia article or Wikibook and translate them on our own, but this would be as time-consuming as maintaining an appropriate doc page.

Any (better) ideas?

[1]: https://en.wikipedia.org/wiki/Bash_(Unix_shell)
[2]: https://en.wikipedia.org/wiki/Shell_(computing)
[3]: https://en.wikipedia.org/wiki/Command-line_interface
[4]: https://en.wikipedia.org/wiki/Command_(computing)
[5]: https://en.wikibooks.org/wiki/Bash_Shell_Scripting
[6]: https://en.wikibooks.org/wiki/A_Quick_Introduction_to_Unix/Shells_and_subshells
[this one]: https://en.wikibooks.org/wiki/Fedora_And_Red_Hat_System_Administration/Shell_Basics

**Comment by unman** [comment]
I dont think that Qubes should take on the burden of teaching users basic use of Linux. There's neither the time nor resource. This may be a place where the user generated pages come in to play.

Absolutely, provide a link to good articles/books if you will, but frankly spoon feeding people who do not/will not look and learn for themselves is a pain, and often a waste of time. Sometimes people ask basic questions in the mailing lists, and they can be guided in the right direction, and come to learn - you can see that process happening.

There's an important point here. People who wont look and learn for themselves wont be able to make the best of Qubes or Whonix. In my experience, you can try to make the system as easy as possible and keep users well away from the command line - that's the approach that I favour. But that only works if you also limit the way in which they use Qubes: tailor it to what they want to do, and restrict their options for poking about.
I see users who haven't taken the time to understand the absolute *basics* of Tor/Whonix/Qubes, and I despair. There is almost no security benefit for those people in using these tools.

**Comment by tokideveloper** [comment]
> I dont think that Qubes should take on the burden of teaching users basic use of Linux. There's neither the time nor resource. This may be a place where the user generated pages come in to play.

What do you mean with "user generated pages"?

> There's an important point here. People who wont look and learn for themselves wont be able to make the best of Qubes or Whonix.

I agree, but maybe "good enough" or "better than nothing" is sufficient for them, at least from their perspectives.

> In my experience, you can try to make the system as easy as possible and keep users well away from the command line - that's the approach that I favour.

Yes, me too. A simple button to click is less error-prone than a command to enter and thus can raise both security and user satisfaction.

> But that only works if you also limit the way in which they use Qubes: tailor it to what they want to do, and restrict their options for poking about.  

Having both would be great (tailored GUI for everyday users (and problems) and terminal commands for the pros (and big problems)).

> I see users who haven't taken the time to understand the absolute _basics_ of Tor/Whonix/Qubes, and I despair. There is almost no security benefit for those people in using these tools.

I see, but is there a security gain when using a terminal? It's another topic, I guess.

**Comment by tokideveloper** [comment]
Here's a proposal for an FAQ item:

---
### What is a terminal?

A [terminal emulator](https://en.wikipedia.org/wiki/Terminal_emulator), nowadays often referred to as just a *terminal*, is a program which provides a text window. Inside that window, a [shell](https://en.wikipedia.org/wiki/Shell_(computing)) is typically running in it. A shell provides a [command-line interface](https://en.wikipedia.org/wiki/Command-line_interface) where the user can enter and run [commands](https://en.wikipedia.org/wiki/Command_(computing)).

Useful links: [here](https://en.wikibooks.org/wiki/Fedora_And_Red_Hat_System_Administration/Shell_Basics), [here](https://en.wikibooks.org/wiki/Bash_Shell_Scripting) and [here](https://en.wikibooks.org/wiki/A_Quick_Introduction_to_Unix/Shells_and_subshells).
