### ISSUE TITLE
Debootstrap issues in Debian builds

### ISSUE THREAD

**Issue by unman** [QubesOS/qubes-issues#4447]
### Qubes OS version:

R4.0

### Affected component(s): 

qubes-builder

---

### Steps to reproduce the behavior:

Build any Debian based template

### Expected behavior:

Template can be built.

### Actual behavior:

Issues with debootstrap can cause problems in build.
E.g, in Ubuntu builds, `apt-transport-https` is now only available in security repositories, which requires use of two repositories for a successful build.

### General notes:

The current process is that packages are downloaded, and configured for each specified repository.(in 01_install_core.sh) 
Debootstrap does not support use of more than one repository. There are tools that do this (e.g multistrap), but they, like the tools referenced in #1055, run on Debian, and cannot be used in a Fedora based build system.

Also, the base image is currently built from "base" , configured and then updated later.
It would be preferable for the system to be built from base+security packages from the start.

The logic of install_core should be reviewed.

---

**Comment by adrelanos** [comment]
[Non-Qubes-Whonix](https://www.whonix.org/wiki/Non-Qubes-Whonix) and [Kicksecure](https://www.whonix.org/wiki/Kicksecure) build process for multiple releases uses `grml-debootstrap` in combination with [`mmdebstrap`](https://manpages.debian.org/mmdebstrap) which has an amazing speed over `debootstrap` as well as better security since it can bootstrap Debian from multiple APT sources, Debian "main" repository as well as Debian security repository.

**Comment by adrelanos** [comment]
`grml-debootstrap`+ `mmdebstrap` combination has better security, the ability to "multistrap" (use Debian "main" repository as well as Debian security repository) (consider cases where APT in Debian "main" repository has a known security vulnerability) as well as would solve various other issues. (https://github.com/QubesOS/qubes-issues/issues/1055)

However... If the following is still a priority...

Quote https://github.com/QubesOS/qubes-issues/issues/4760#issuecomment-459445696

@adrelanos:
> Is it ok to require Debian templates being created using Debian based rather than Fedora based templates?

@marmarek:
>> No, it is not. Building Qubes should _not_ require running Qubes. It should be possible to get sufficiently recent distribution to build Qubes, including all supported templates. Currently this works on Debian and Fedora. With small tweaks probably others too. But introducing hard dependency on specific distribution for building is a bad idea.

Then I guess it will be difficult to implement this ticket.

**Comment by DemiMarie** [comment]
> `grml-debootstrap`+ `mmdebstrap` combination has better security, the ability to "multistrap" (use Debian "main" repository as well as Debian security repository) (consider cases where APT in Debian "main" repository has a known security vulnerability) as well as would solve various other issues. (#1055)
> 
> However... If the following is still a priority...
> 
> Quote [#4760 (comment)](https://github.com/QubesOS/qubes-issues/issues/4760#issuecomment-459445696)
> 
> @adrelanos:
> 
> > Is it ok to require Debian templates being created using Debian based rather than Fedora based templates?
> 
> @marmarek:
> 
> > > No, it is not. Building Qubes should _not_ require running Qubes. It should be possible to get sufficiently recent distribution to build Qubes, including all supported templates. Currently this works on Debian and Fedora. With small tweaks probably others too. But introducing hard dependency on specific distribution for building is a bad idea.
> 
> Then I guess it will be difficult to implement this ticket.

Could containerizing the build solve the problem?

**Comment by adrelanos** [comment]
@DemiMarie 
> Could containerizing the build solve the problem?

- If the container can run inside a Qubes VM? I presume that building Qubes inside a (Qubes) VM must be supported.
- Maybe, but where would the container base image come from? That either
  - a base image one would need to trust and download from elsewhere, or
  - if created using a script, then the same bootstrapping issue as here would happen.

**Comment by marmarek** [comment]
>     * a base image one would need to trust and download from elsewhere, or

I guess @DemiMarie (maybe unknowingly) meant this one. And this is in fact major reason why we don't use containers in qubes-builder yet.

**Comment by DemiMarie** [comment]
> > ```
> > * a base image one would need to trust and download from elsewhere, or
> > ```
> 
> I guess @DemiMarie (maybe unknowingly) meant this one. And this is in fact major reason why we don't use containers in qubes-builder yet.

I was specifically thinking a tarball of (say) a barebones Debian install, with hash hardcoded in qubes-builder.

**Comment by adrelanos** [comment]
> > > ```
> > > * a base image one would need to trust and download from elsewhere, or
> > > ```
> > 
> > 
> > I guess @DemiMarie (maybe unknowingly) meant this one. And this is in fact major reason why we don't use containers in qubes-builder yet.
> 
> I was specifically thinking a tarball of (say) a barebones Debian install, with hash hardcoded in qubes-builder. Podman, Docker, and similar tools are massive overkill for this.

Any then how would that image be created? Using grml-debootstrap + mmdebstrap on the Debian platform (= limited to the Debian platform)? That image also would need to be upgraded regularly.

For reproducible builds this could add an issue. The build shouldn't depend on on files on a remote that can change over time?

I guess if going for this, that image would need to stay online for a reasonable long period to allow rebuilders to reproducibly rebuild. Effectively rebuilders who wish to rebuild, verify it all would then be limited to the Debian platform.

That seems like an interesting general question "how much binaries in a build process is still considered Open Source"? Are we "building Qubes from source code" if the build process itself depends on downloading another binary (Debian base image)? Well, Qubes packages are downloaded as binary from Qubes repository during build process anyhow. As well as Debian packages but could be argued, that's different?
