### ISSUE TITLE
AppVMs based on Windows 10 TemplateVM die after launching

### ISSUE THREAD

**Issue by e6lk7dqzm83p** [QubesOS/qubes-issues#4448]
### Qubes OS version:

4.0

### Affected component(s): 

Windows 10 AppVMs

---

### Steps to reproduce the behavior:

Try to launch an AppVM based off of a Windows 10 TemplateVM

### Expected behavior:

The AppVM launches

### Actual behavior:

The AppVM launches and then dies, the following pop up appears:

> Qube Statues: win10-qube
Domain win10-qube has failed to start: Cannot connect to qrexec agent for 60 seconds, see /var/log/xen/console/guest-win10-qube.log for details.

Note: the referenced log file is empty.

### General notes:

Qubes Windows Tools is installed both on the Windows 10 Template and in dom0.

This is for Windows 10

---

### Related issues:

#4441 
#1861

**Comment by andrewdavidwong** [comment]
> I should point out that Windows 7 functions well as a template, with or without QWT. Perhaps you could amend the title of this issue?

Updated title.
