### ISSUE TITLE
Attaching iPhone (and presumably other USB devices) to Windows Template VM

### ISSUE THREAD

**Issue by e6lk7dqzm83p** [QubesOS/qubes-issues#4449]
### Qubes OS version:

4.0

### Affected component(s): 

Windows TemplateVM

---

### Steps to reproduce the behavior:

Connecting an iPhone to my Windows TemplateVM via the HW manager fails with the following error:

> Attaching device Apple_Inc._iPhone to win10-template failed. Error: Device attach failed:

### Expected behavior:

My iPhone or USB device can attach to the Windows Template VM

### Actual behavior:

My iPhone or USB device does not attach to the Windows Template VM

### General notes:

I'm using Windows 10 with Qubes Windows 10 installed.

---

### Related issues:

#4441 #1861 #4448

**Comment by e6lk7dqzm83p** [comment]
Ok, thanks for the clarification!

**Comment by e6lk7dqzm83p** [comment]
@marmarek sorry if this is off topic, but given that a number of security minded folks use iPhones, how do Qubes users manage these devices?  Separate computer?  I know getting VirtualBox to work in Qubes is a dicey proposition at best, and if there's no USB pass through to a Windows HVM, it seems like there is no practical way to do this within Qubes.

**Comment by ekaflaer** [comment]
I would be interested in this too. It is really annoying and my idea was also to use this.

@marmarek Would it work if I would detach the usb host controller from the sys-usb vm and add it to the Windows one for a short time? I tried that in the past and it did not work but I also had issues attaching the usb controller and did not know that I had to reset the controller `no-strict-reset=True`.

**Comment by marmarek** [comment]
USB support for windows implemented in #5802
