### ISSUE TITLE
QubesOS does not recognize full RAM

### ISSUE THREAD

**Issue by straussmaus** [QubesOS/qubes-issues#4451]
### Qubes OS version:

R4 with latest updates.

A laptop with 16GB RAM is showing 3967180 when I run "free" at the command line of dom0.

The same laptop dual booting to debian shows the full 16G.  Thank you.

### Affected component(s): 

---

### General notes:

---

**Comment by unman** [comment]
@straussmaus  You need to understand the way that Xen (and therefore Qubes) works. dom0 is only part of the picture and has its own memory allocation.
"free" in dom0 is reporting the memory allocated to dom0 - you can adjust this in the boot command line, by setting parameters.
To see the real position you need to use Xen tools - try `sudo xl info` in dom0 - that will show you the memory available to the system as a whole. and should match your expectation.

**Comment by straussmaus** [comment]
@unman Can you point me to a good documentation for this?  I read the Qubes docs and I haven't seen anything that explains this.  But maybe I simply went past it too quickly.

**Comment by straussmaus** [comment]
@unman `sudo xl info1 confirms 16308 RAM.  Thank you.
