### ISSUE TITLE
Qubes 4.0 - Whonix ws/gw unresponsive after updating dom0

### ISSUE THREAD

**Issue by piotruk84** [QubesOS/qubes-issues#4452]
Hi

I'm new to Qubes os. I have managed to update all templates including dom0. 
However, after I reboot my laptop and login to Qubes, dom0 does not update anymore and gets stuck at "please wait for the updater to launch".

Moreover, whonix gw/ws are not responding at all. The only function that works is 'qube settings'. Tor does not work either. Whonixcheck is down too.

Please advise me on how to proceed and make these templates work cause I'm stuck big time. I read that some users uninstalled and reinstaled whonix from repos. How would I do that? 

Cheers

Peter

**Comment by andrewdavidwong** [comment]
Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this does not appear to be suitable for `qubes-issues`. We ask that you please send this to the `qubes-users` [mailing list](https://www.qubes-os.org/support/) instead. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a brief comment explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.

**Comment by andrewdavidwong** [comment]
Duplicate of #4443
