### ISSUE TITLE
xenpm cannot get data for some cores

### ISSUE THREAD

**Issue by olekli** [QubesOS/qubes-issues#4456]
### Qubes OS version:

R4.0

### Affected component(s): 

---

### Steps to reproduce the behavior:

Run `xenpm get-cpufreq-para`.

### Expected behavior:

`xenpm` shows data for all cores.

### Actual behavior:

`xenpm` shows data for two of the four physical cores, the others have errors:
`[CPU1] failed to get cpufreq parameter`
`[CPU3] failed to get cpufreq parameter`

### General notes:

Thinkpad X1 Carbon 6th gen, I7-8650U, 4 cores. See [https://groups.google.com/forum/#!topic/qubes-users/5VzS5E-JaFg](https://groups.google.com/forum/#!topic/qubes-users/5VzS5E-JaFg)

The issue disappears after reverting to `smt=on` boot option.

---

**Comment by marmarek** [comment]
> `[CPU1] failed to get cpufreq parameter`
> `[CPU3] failed to get cpufreq parameter`

Hyperthreading is intentionally disabled, so this is expected. But increased temperature after suspend looks like a bug in Xen (likely not re-applying power management settings to those disabled threads).

**Comment by tfm1** [comment]
> > `[CPU1] failed to get cpufreq parameter`
> > `[CPU3] failed to get cpufreq parameter`
> 
> Hyperthreading is intentionally disabled, so this is expected. But increased temperature after suspend looks like a bug in Xen (likely not re-applying power management settings to those disabled threads).

But those are physicial cores. I have 4 physical cores. With `smt=off` `xenpm` tries to query 4 and 2 of them error out.

With `smt=on` and hyperthreading disabled in BIOS, `xenpm` shows 4 cores without errors.
