### ISSUE TITLE
*** ERROR while receiving updates: ( rsa sha1 (MD5) PGP MD5 NOT OK)

### ISSUE THREAD

**Issue by straussmaus** [QubesOS/qubes-issues#4458]
### Qubes OS version:

R4.0

### Affected component(s): 

Manual dom0 upgrade while upgrade to whonix-14 (https://www.whonix.org/wiki/Qubes/Install)

---

### Steps to reproduce the behavior:

- Install new QubesOS with no whonix templates

- Follow instructions on this page: https://www.whonix.org/wiki/Qubes/Install

---- 1st upgrade dom0  (success)

---- 2nd try `sudo qubesctl state.sls qvm.anon-whonix`  (hangs for 1 hour so I quit)

---- 3rd try `sudo qubes-dom0-update --best --allowerasing --enablerepo=qubes-dom0-current-testing qubes-mgmt-salt-dom0-virtual-machines`

### Expected behavior:

Expect one of three things.

Maybe 1:  `sudo qubes-dom0-update --best --allowerasing --enablerepo=qubes-dom0-current-testing qubes-mgmt-salt-dom0-virtual-machines` returned `OK`

Maybe 2: `sudo qubes-dom0-update --best --allowerasing --enablerepo=qubes-dom0-current-testing qubes-mgmt-salt-dom0-virtual-machines` returns instructions on how to troubleshoot ERROR

Maybe 3 `sudo qubes-dom0-update --best --allowerasing --enablerepo=qubes-dom0-current-testing qubes-mgmt-salt-dom0-virtual-machines` returns instructions on how to "use dnf directly now" because this is not clear.

### Actual behavior:

Within one minute this command returns this error:

```
*** ERROR while receiving updates:
Error while verifying qubes-template-whonix-ws-14-4.0.1-201807171801.noarch.rpm.signature: /var/lib/qubes/updates/rpm/ubes-template-whonix-gw-14-4.0.1-201807171801.noarch.rpm: rsa sha1 (MD5) PGP MD5 NOT OK

Domain sys-firewall sent not signed rpm: qubes-template-whonix-gw-14-4.0.1-201807171801.noarch.rpm
--> if you want to use packages that were downloaded correctly, use dnf directly now
```

### General notes:

It is difficult to understand the source of the problem.  Is a key missing from the keyring?  Why didn't first update dom0 download updated key?  Is the downloaded package bad and hash does not match?  Details will help greatly.

---

### Related issues:

https://github.com/QubesOS/qubes-issues/issues/4100 (But I do not think the solution can be the same?)

**Comment by marmarek** [comment]
Do you see any error earlier about too little space in sys-firewall, or network error? How much space do you have there?
You can also try adding `--clean` option to clean the cache.

**Comment by straussmaus** [comment]
`df -h /` in sys-firewall shows 5+GB free.  But I ran `--clean` before testing this.

The whonix-14 template is installed now.  What I am having some concern for is if the problem is fixed or did I install whonix-14 from repos where MD5 PGP etc were not correct so maybe I have bad files?

**Comment by marmarek** [comment]
> `df -h /` in sys-firewall shows 5+GB free.

That's plenty of space, the problem was probably somewhere else. Maybe some network error? Or some temporary problem with that particular mirror (mirror is chosen dynamically to optimize for download speed).

> What I am having some concern for is if the problem is fixed or did I install whonix-14 from repos where MD5 PGP etc were not correct so maybe I have bad files?

No, the faulty files are removed and don't get any chance to get installed. If you got the template installed, it means it passed the verification.

**Comment by straussmaus** [comment]
> That's plenty of space, the problem was probably somewhere else. Maybe some network error? Or some temporary problem with that particular mirror (mirror is chosen dynamically to optimize for download speed).

I don't think it is a problem with the network or the mirror.  I have installed Qubes R4.0 seven times in the past days and this problem happens each time.  The network is the same network but it is a very strong very fast connection that I never have troubles.

> No, the faulty files are removed and don't get any chance to get installed. If you got the template installed, it means it passed the verification.

This makes me happy.  But can you explain some more?  Because it is whonix templates I am extra nervous.

**Comment by andrewdavidwong** [comment]
> ---- 2nd try `sudo qubesctl state.sls qvm.anon-whonix` (hangs for 1 hour so I quit)

It might not actually be hung (see #4215). There's also a warning box on https://www.whonix.org/wiki/Qubes/Install that says:

> Before you execute the call, keep in mind that it can take a long time to execute (at least several minutes; some users reported more than 20 mins). No progress indicator is shown. Do not interrupt the salt process once it has started, or this can lead to an unstable system. The process is lengthy, particularly over Tor. 

Perhaps quitting prematurely caused the system to become unstable.

**Comment by marmarek** [comment]
> But can you explain some more? Because it is whonix templates I am extra nervous.

Each package is digitally signed (as in all Linux distributions today). But we have `qubes-dom0-update` (instead of dnf directly) specifically to make sure that those signatures are properly verified _before_ dnf try to do anything with the downloaded package. More details here: https://www.qubes-os.org/doc/software-update-dom0/#how-is-software-installed-and-updated-securely-in-dom0
