### ISSUE TITLE
Dependency libxen-4.8

### ISSUE THREAD

**Issue by toxub23** [QubesOS/qubes-issues#4459]
### Qubes OS version:
R4.0

### Affected component(s): 
libxen-4.8

### General notes:
What do you think about it? I do not know if this is only my sensitivity or actual problem. I do not know if this is the developers 'decision to use a newer version or maybe some problem with packages or other developers' decision. The entire update generally went smoothly and the machine was running smoothly without problems. Console logs are in the link. The updated machine is kali linux (kali is based on debian testing (buster)). The case concerns day before yesterday update. Day before yesterday I also updated dom0.

https://0bin.net/paste/SSgIy-TJK1A9Vl6D#VDYrhrUnKrALijMAz4UzC7yEXqP9gp3sqnu4eL8fa9P 

How do you think? Any action is needed from the user?

**Comment by andrewdavidwong** [comment]
Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this does not appear to be suitable for `qubes-issues`. We ask that you please send this to the `qubes-users` [mailing list](https://www.qubes-os.org/support/) instead. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a brief comment explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.
