### ISSUE TITLE
Switching/getting a new CPU appears to have broken qubes

### ISSUE THREAD

**Issue by eaten-squid** [QubesOS/qubes-issues#4461]
I recently changed my CPU from an Intel chip to a Ryzen 7 2700x (which supports IOMMU and SVM)

I was expecting there to be little issue as IOMMU was supported and has been enabled in bios.

This is on qubes 4.0

---

What actually happens is absolutely no Qube will boot. dom0 and all utilities are fine however. When attempting to boot each cube complains about `<Qubes.ext.pci.PCIdevice> at [some address]` not existing.

When running `qvm-pci ls <qube name>` it does not list any devices.

Edit:

This particular issue was because of the network device not being given to `sys-net`. However I'm at a new issue where all qubes still won't boot because of capabilities for arch=x86_64 (which I'm guessing I need to change to something else?)

**Comment by marmarek** [comment]
Changing CPU changed also what PCI devices you have in system (or at what addresses). This probably include network adapters and USB controllers.
See `qvm-pci ls sys-net` and `qvm-pci ls sys-usb` - you'll need to detach those unknown devices and attach actual network and USB devices.

**Comment by eaten-squid** [comment]
@marmarek  yes, Doing this has fixed that part of the issue however there is another issue that I have come across (see edit) I'm searching to see if something like this has been solved before.

**Comment by marmarek** [comment]
> won't boot because of capabilities for arch=x86_64

Looks like disabled AMD-V. Check BIOS settings.
You can also confirm this with `xl info` - should contain `virt_caps: hvm hvm_directio`

**Comment by eaten-squid** [comment]
Only `hvm_directio`.

There isn't anything in the bios for AMD-V only IOMMU and SVM.

I was about to link this issue too ( #4130 ).

**Comment by eaten-squid** [comment]
Awesome! Thanks, it now appears to be working as intended.
