### ISSUE TITLE
Moving or deleting VMs will not change them being auto-started under their former name on the next boot

### ISSUE THREAD

**Issue by noseshimself** [QubesOS/qubes-issues#4465]
### Qubes OS version:

R4.0

### Affected component(s): 

---

### Steps to reproduce the behavior:

Create a VM and set it to autostart.
Rename or delete the VM.

### Expected behavior:

The VM is gone and forgotten.

### Actual behavior:

If you watch the messages during system boot you will notice that the system will still try to start the VM under its old name.

### General notes:

---

**Comment by marmarek** [comment]
This is a duplicate of #4014 
Fix is already in current-testing repository.
