### ISSUE TITLE
Updating a VM using salt hangs

### ISSUE THREAD

**Issue by marmarta** [QubesOS/qubes-issues#4466]
### Qubes OS version:
R4.0

### Steps to reproduce the behavior:
Tried to update a template with      
`qubesctl --skip-dom0 --targets=fedora-28 --show-output pkg.upgrade refresh=True`

### Expected behavior:
VM updates.
### Actual behavior:
It just... hangs.

This is the process tree:
```
root       378  0.0  0.2  66136  2772 ?        SLs  19:12   0:00 /usr/lib/qubes/qrexec-agent
root       757  0.0  0.1 131824  2136 ?        SL   19:12   0:00  \_ /usr/lib/qubes/qrexec-agent
root       759  0.0  0.3 194920  4008 ?        S    19:12   0:00      \_ /usr/lib/qubes/qrexec-agent
root       766  0.0  0.8 279228 10032 ?        Ss   19:12   0:00          \_ /usr/bin/python2.7 -c import base64; exec(base64.b64decode("""IyBweWxpbnQ6IGRpc2Fib
root       783  0.0  0.0 214508   580 ?        S    19:12   0:00              \_ /bin/sh -l /usr/lib/qubes/qubes-rpc-multiplexer qubes.VMRootShell disp-mgmt-fed
root       789  0.0  0.0 209076   416 ?        S    19:12   0:00              |   \_ cat
root       784  0.0  0.0 214508   464 ?        S    19:12   0:00              \_ /bin/sh -l /usr/lib/qubes/qubes-rpc-multiplexer qubes.VMRootShell disp-mgmt-fed
root       785  0.0  0.0 208940   344 ?        S    19:12   0:00              |   \_ tee /tmp/qrexec-rpc-stderr-return.766
root       786  0.0  0.0 243516   876 ?        S    19:12   0:00              |   \_ logger -t qubes.VMRootShell-disp-mgmt-fedora-28
root       796  0.0  4.4 529548 51216 ?        S    19:12   0:01              \_ /usr/bin/python2.7 /var/tmp/.root_62a99a_salt/salt-call --retcode-passthrough -
root       886  1.0 14.7 618648 168500 ?       S    19:12   1:02                  \_ /usr/bin/python3 /usr/bin/dnf --quiet -y upgrade
root      2634  0.0  0.2 214708  3252 ?        S    19:18   0:00                      \_ /bin/sh /var/tmp/rpm-tmp.rMh9m2 2
root      2635  0.0  1.0 424956 11584 ?        Sl   19:18   0:00                          \_ flatpak remote-list --system
root       388  0.0  0.1 211088  1636 hvc0     Ss+  19:12   0:00 /sbin/agetty -o -p -- \u --keep-baud 115200,38400,9600 hvc0 vt220
```

**Comment by unman** [comment]
@marmarta  That's interesting. What salt version are you running?
Is that syntax right? Did it work for you in the past? It doesn't work for me at all, but I dont see any hanging..

I use `pkg.uptodate` instead, which is the documented call for 2017.7.1, and that works fine when used in a sls file, called  with `state.apply`. Does that work for you?

**Comment by marmarek** [comment]
I think it may be not salt problem directly, but this specific update (flatpak as it seems). `flatpak remote-list --system` called manually in a VM without network does _not_ hang, so it may be something more specific to the update process.

**Comment by marmarta** [comment]
so, this wasn't reproduced in future updates and in 4.2 we're moving slowly away from salt, so I think it's safe to close this.

**Comment by unman** [comment]
On Thu, Jan 12, 2023 at 06:25:26AM -0800, Marta Marczykowska-Górecka wrote:
> so, this wasn't reproduced in future updates and in 4.2 we're moving slowly away from salt, so I think it's safe to close this.
> 
Do you mean "moving slowly away from salt for updates, or "moving
slowly away from salt" for everything?
If the latter, I don't remember any discussion. 
What is going to replace it?

**Comment by marmarek** [comment]
> Do you mean "moving slowly away from salt for updates, or "moving slowly away from salt" for everything?

The former.

**Comment by unman** [comment]
On Wed, Jan 18, 2023 at 07:01:48PM -0800, Marek Marczykowski-Górecki wrote:
> > Do you mean "moving slowly away from salt for updates, or "moving slowly away from salt" for everything?
> 
> The former.
> 
Thanks for clarification.
