### ISSUE TITLE
No package for qubes-u2f in Fedora 29

### ISSUE THREAD

**Issue by dakka2** [QubesOS/qubes-issues#4467]
### Qubes OS version:
R4.0

### Affected component(s): 
Fedora 29 TemplateVM

### Steps to reproduce the behavior:
Attempt to install qubes-u2f

### Expected behavior:
Package for u2f installs

### Actual behavior:
No package.

**Comment by marmarek** [comment]
Just built and uploaded to testing repository: https://github.com/QubesOS/updates-status/issues/664#issuecomment-435522961

**Comment by dakka2** [comment]
Error: 
 Problem: conflicting requests
  - nothing provides python3-u2flib-host needed by qubes-u2f-1.2.2-1.fc29.noarch
