### ISSUE TITLE
Qubes won't boot on a Core i7-8850H system with Intel UHD 630 GPU enabled

### ISSUE THREAD

**Issue by noseshimself** [QubesOS/qubes-issues#4474]
### Qubes OS version:

R4

### Affected component(s): 

---

### Steps to reproduce the behavior:

Get a high-end system (e. g. Lenovo P52 or Dell Precision 5530; turn off the Intel GPU and install Qubes.

### Expected behavior:

Running system.

### Actual behavior:

Depending on the kernel the system will hang during boot. With the latest available kernel in current-testing it will boot but reboot as soon as the X server is started.

### General notes:

1) It doesn't work with the Linux distributions certified on it, either, but they include more recent versions of nouveau.
2) (tested with Arch) Even if a recent kernel is coming up with it, accessing the device using lshw freezes the system.
3) I don't have access to systems with i7-8750 but I would expect to see similar problems.

---

**Comment by 0spinboson** [comment]
that's with a Nvidia quadro p1000? Are those supported by the nouveau version shipped with fc25? And what happens if you include a 4.18-based kernel in the 'extra kernels' directory of the installer, or install that after Qubes installation?

**Comment by noseshimself** [comment]
> That's with a Nvidia quadro p1000?

Same series. Keep in mind that the X in Fedora is from March 2017.

> And what happens if you include a 4.18-based kernel in the 'extra kernels' directory of the installer, or install that after Qubes installation,

It won't change; it requires to get a newer version of Xorg backported to Fedora 26. No matter what kernel you boot, the nouveau driver will remain the same. Easiest would be getting the current sources and just compile them but the video driver API changed (from version 23 in Fedora 25 to 24).

I'm currently trying to set up a builder environment permitting me to compile a kernel against a newer release of X11 but I'm totally not used to that kind of stuff anymore (last time I did it was on 386BSD and FreeBSD-1 and don't have enough time.

> and/or if you toggle the nomodeset boot parameter?

Not helpful.

Even if we got an nVidia driver working it would be much more important to get the i915 working because this will be in the majority of new hardware. I'm pretty sure that the thing will be working soon but it would require to get the Qubes developers to pull up dom0 to a current Fedora or integrate a current X tree into Fedora 25. Both seem to be painful enough but without it will stop running on state of the art hardware, no matter how broken that may be.

**Comment by noseshimself** [comment]
> That's with a Nvidia quadro p1000?

Same series. Keep in mind that the X in Fedora is from March 2017.

> And what happens if you include a 4.18-based kernel in the 'extra kernels' directory of the installer, or install that after Qubes installation,

It won't change; it requires to get a newer version of Xorg backported to Fedora 26. No matter what kernel you boot, the nouveau driver will remain the same. Easiest would be getting the current sources and just compile them but the video driver API changed (from version 23 in Fedora 25 to 24).

I'm currently trying to set up a builder environment permitting me to compile a kernel against a newer release of X11 but I'm totally not used to that kind of stuff anymore (last time I did it was on 386BSD and FreeBSD-1 and don't have enough time.

> and/or if you toggle the nomodeset boot parameter?

Not helpful.

Even if we got an nVidia driver working it would be much more important to get the i915 working because this will be in the majority of new hardware. I'm pretty sure that the thing will be working soon but it would require to get the Qubes developers to pull up dom0 to a current Fedora or integrate a current X tree into Fedora 25. Both seem to be painful enough but without it will stop running on state of the art hardware, no matter how broken that may be.

**Comment by noseshimself** [comment]
@marmarek :
> We have https://github.com/QubesOS/qubes-linux-dom0-updates specifically for this purpose. There are backported intel and ati/amd drivers from Fedora 28.

Hm. I'm not sure I'm understanding you now; what exactly (which source files and from which repository) did you port back to dom0 (to be more exact: which part of nouveau was taken from where?)? 

I just booted this

Linux dom0 4.18.13-3.pvops.qubes.x86_64 #1 SMP Sun Oct 14 04:41:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

and Xorg.0.log tells me

[    68.773] 
X.Org X Server 1.19.3
Release Date: 2017-03-15
[    68.773] X Protocol Version 11, Revision 0
[    68.773] Build Operating System:  4.9.3-200.fc25.x86_64 
[    68.773] Current Operating System: Linux dom0 4.18.13-3.pvops.qubes.x86_64 #1 SMP Sun Oct 14 04:41:32 UTC 2018 x86_64
[    68.773] Kernel command line: root=/dev/mapper/luks-fdd2a3a5-318c-4008-843d-005150acf1bd rootflags=subvol=root rd.luks.uuid=luks-fdd2a3a5-318c-4008-843d-005150acf1bd rd.lvm.lv=NVMe0_qubes_LVM/swap rd.luks.uuid=luks-a77af9
[    68.773] Build Date: 15 March 2017  06:37:12PM
[    68.773] Build ID: xorg-x11-server 1.19.3-1.fc25 

which in terms of X is ancient.

On a rather current Arch running on identical hardware I've been getting

[   202.777] 
X.Org X Server 1.20.3
X Protocol Version 11, Revision 0
[   202.778] Build Operating System: Linux Arch Linux
[   202.779] Current Operating System: Linux archlinux 4.18.16-arch1-1-ARCH #1 SMP PREEMPT Sat Oct 20 22:06:45 UTC 2018 x86_64
[   202.779] Kernel command line: \\root\boot\vmlinuz-linux root=PARTUUID=49c70d37-000c-4348-8db4-9f97c3c2dc34 rootflags=subvol=root rw add_efi_memmap initrd=/root/boot/initramfs-linux.img
[   202.780] Build Date: 25 October 2018  04:42:32PM

and nouveau is coming up correctly, keeping the system about 15° cooler. And backlight controls are working.

Be aware of this Qubes

[    68.780] (II) Module ABI versions:
[    68.780]    X.Org ANSI C Emulation: 0.4
[    68.780]    **X.Org Video Driver: 23.0**
[    68.780]    X.Org XInput driver : 24.1
[    68.780]    X.Org Server Extension : 10.0

vs. Arch

[   202.787] (II) Module ABI versions:
[   202.787]    X.Org ANSI C Emulation: 0.4
[   202.787]    **X.Org Video Driver: 24.0**
[   202.787]    X.Org XInput driver : 24.1
[   202.787]    X.Org Server Extension : 10.0

difference (that must have been in February 2017, I spotted it reading https://www.phoronix.com/scan.php?page=news_item&px=xorg-server-1.20-video-abi).

So: Where do I find your current experimental kernel (or better: which version of Xorg does it contain 

what ABI versions does it report)?

> but Fedora 28 have the same nouveau driver version as Fedora 25 (1.0.15 in both cases).

It's the same in Arch but still it is detecting the hardware correctly. I would make Xorg (and the kernel parts of the nouveau driver) the culprit in not detecting the hardware correctly OR (and that would be your problem) Xen and the Qubes kernel are hiding something)

And the last Arch update I made a few days ago on the second machine brought in a comple new Xorg with all dependencies. Again. And that version doesn't crash upon detecting the UHD 630 anymore (and /sys/class/backlight is showing some content) although lshw still freezes the system.

[Xorg.0.log.arch.txt](https://github.com/QubesOS/qubes-issues/files/2549386/Xorg.0.log.arch.txt)
[Xorg.0.log.qubes.txt](https://github.com/QubesOS/qubes-issues/files/2549387/Xorg.0.log.qubes.txt)

**Comment by noseshimself** [comment]
(Should we move that to a new issue as it has not much relevance for the CPU/Intel GPU problem pair? I wold really like to be able to use the UHD 630, too, as the nVidia P3200 makes the CPU throttle as it needs both ends of the heat pipe))

> According to the logs you provided, the main difference is that Qubes does not use nouveau at all and use modesetting instead!

I just checked; Arch does not have any piece of xorg-config in its path and both systems generate identical xorg.conf.new files (except the font path) when running Xorg -configure.

(Turning modesetting off with nouveau.modeset=0 is not helpful because X will not come up with the well-known "(EE) [drm] failed to open drm device" error.)

> There is this line: (II) Using xf86-video-modesetting for Maxwell and newer GPUs..

Hm... With nouveau modesetting turned off the nVidia comes up in 1024x768 mode as initialized by firmware. https://nouveau.freedesktop.org/wiki/TroubleShooting/#index1h3 --> no X without it. and the P3200 is definitely Maxwell and newer.

> While this may make sense for intel graphics, you try to use nvidia one.

AND the Intel GPU has been turned off completely (firmware is set to "Discrete Graphics").

I'll attach the xorg.conf in a few minutes but the log stays the same as in [Xorg.0.log.qubes.txt](https://github.com/QubesOS/qubes-issues/files/2549387/Xorg.0.log.qubes.txt) above; modesetting goes wrong and nouveau will throw in the towel. And the only obvious difference between the systems is the kernel. Just to make sure I'll move the NVMe with the Arch installation to the designated Qubes system.

**Comment by marmarek** [comment]
> With nouveau modesetting turned off the nVidia comes up in 1024x768 mode as initialized by firmware.

No, I mean xorg driver modesetting (the generic one). Even with nouveau you still need modesetting enabled in the kernel.

> [   768.799] (==) Using config directory: "/etc/X11/xorg.conf.d"
[   768.799] (==) Using system config directory "/usr/share/X11/xorg.conf.d"
[   768.799] (==) No Layout section.  Using the first Screen section.
[   768.799] (==) No screen section available. Using defaults.
[   768.799] (**) |-->Screen "Default Screen Section" (0)
[   768.799] (**) |   |-->Monitor "<default monitor>"

This doesn't match the config you attached.

**Comment by marmarek** [comment]
It doesn't make sense. Exactly the same driver version works for you on Arch, but here refuses to pick up the device. Maybe this `(II) Using xf86-video-modesetting for Maxwell and newer GPUs.` is effect of some Fedora-specific patch? Let me dig what actually print this message and why.

**Comment by marmarek** [comment]
Oh, looks like fc25 package is intentionally broken: https://src.fedoraproject.org/rpms/xorg-x11-drv-nouveau/blob/f25/f/0001-remove-support-for-maxwell-and-higher.patch
fc25 is literally the only branch with this patch.
I'm going to add un-broken package to linux-dom0-updates...

**Comment by marmarek** [comment]
Try xorg-x11-drv-nouveau-1.0.15-4 from current-testing

**Comment by noseshimself** [comment]
Working. Now trying to change the resolution is getting me a blank screen bt no reboot anymore. Like on Arch the backlight can't be found so there is no control and we have to wait for thinkpad-acpi to learn something about the new hardware.
I'll create an xorg.conf to force X to use nouveau and turn on the UHD 630 next.
The CPU is getting its part of the heat pipe now.

**Comment by noseshimself** [comment]
This might be a BIOS-related problem, see https://old.reddit.com/r/Qubes/comments/9wlskz/dell_latitude_7490_core_i78650u_compatible_with/e9sb6xw/?context=3

If Thundebolt BIOS support is turned on (which might make Thunderbolt working in Qubes but at the same time bricks the P52 terminally) on not too similar machines like the X1 Carbon Gen6 is not experiencing problems (just verified that on a machine I have access to) so it might be limited to the high-end chipsets with broken firmware.

**Comment by brendanhoar** [comment]
I'm waiting for guaranteed fixes for the thunderbolt assist and hybrid/discrete bios^H^H^H^H^H bricking options to be fixed on the P52 and P1/X1E firmwares before attempting a QubesOS install.

For anyone who has managed to brick their unit while debugging (in general or for QubesOS install), here's an article on how you may be able to externally re-flash the motherboards should those options brick them. I posted the link to the lenovo forums but, surprise, surprise, moderators removed the link. 

http://posts.nadim.computer/2018/10/26/repairing-a-thinkpad.html

Brendan

**Comment by noseshimself** [comment]
>I'm waiting for guaranteed fixes for the thunderbolt assist and 
>hybrid/discrete bios^H^H^H^H^H bricking options to be fixed on the P52 
>and P1/X1E firmwares before attempting a QubesOS install.
>
>For anyone who has managed to brick their unit while debugging (in 
>general or for QubesOS install), here's an article on how you may be 
>able to externally re-flash the motherboards should those options brick 
>them. I posted the link to the lenovo forums but, surprise, surprise, 
>moderators removed the link.
>

Well...  Seems I succeeded to brick my fourth P52 by buying the 
Thunderbolt Dock which required a Thunderbolt firmware update which I 
did. Brick.


Achim

**Comment by evilaliv3** [comment]
@marmarek: i'm supporting a user with I7-8565U and Intel UHD graphics 620.

The system is trying to install but the install boot stops at:
```
Vmzlinux: 0x000...
Initrd.IMG: 0x000....
0x0000:0x00:0x02.0x0: ROM: 0x10000 bytes at 0x4e749018"
```

Is there any possibility to run the install activating the backports from Fedora 28 at install time? Would this help?

**Comment by marmarek** [comment]
The 4.0.1-rc1 image contains them. Give it some time - it may hang for a few minutes if some hardware detection takes more than usual (nvidia + intel graphics happen to have this issue).
Take a look also at https://www.qubes-os.org/doc/uefi-troubleshooting/#installation-freezes-before-getting-to-anaconda-qubes-40

**Comment by 0spinboson** [comment]
is this still an issue?
