### ISSUE TITLE
qvm-run --pass-io sys-usb 'echo test' > ~/test requires XFCE session to be started?

### ISSUE THREAD

**Issue by tlaurion** [QubesOS/qubes-issues#4478]
### Qubes OS version:

R4.0

### Affected component(s): 

Unknown. Searching for a workaround.

---

### Steps to reproduce the behavior:

Typing `qvm-run --pass-io sys-usb 'echo test' > ~/test ` directly from dom0 from tty2 or over a serial connection never returns if not logged in over XFCE first.

The use case here would be to login from OpenBMC into dom0. The goal here is to be able to use QubesOS on a server without X access.

After login under XFCE, running the same command from dom0 tty2 or from serial works. 

### Expected behavior:

Running `qvm-run --pass-io sys-usb 'echo test' > ~/test ` from dom0 without graphical login in XFCE is expected to work.

### Actual behavior:

`qvm-run --pass-io sys-usb 'echo test' > ~/test ` doesn't return if not logged in under XFCE.

### General notes:

Another problem I'm facing is being able to copy files from one VM to another without graphically confirming file operation. Could that be confirmed from a TTY? 

---

**Comment by marmarek** [comment]
> Typing `qvm-run --pass-io sys-usb 'echo test' > ~/test ` directly from dom0 from tty2 or over a serial connection never returns if not logged in over XFCE first.

There is --no-gui option for that.

> Another problem I'm facing is being able to copy files from one VM to another without graphically confirming file operation. Could that be confirmed from a TTY? 

Currently no. You can configure the qrexec policy (for qubes.Filecopy service) to not ask for confirmation for particular source and target VMs, see:
https://www.qubes-os.org/doc/qrexec3/#qubes-rpc-administration

In theory it could be possible to write confirmation service for tty (it needs to register itself on system dbus). But (besides actually writing such service) there is important issue: how to clearly mark that the prompt comes from dom0 and do not interfere with any other console output (especially when you use xl console, or other interact with some VM), or rather - other output do not interfere with the prompt.
