### ISSUE TITLE
Qubes R4 after upgrades boot process stuck at "Reached Target Basic System"

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#4479]
### Qubes OS version:
R4

### Affected component(s): 
dom0 boot

### Steps to reproduce the behavior:

Install Qubes R4 on USB HDD. Install qubes-template-fedora-28. Upgrade all templates. Upgrade dom0. Reboot.

### Expected behavior:
Normal boot.

### Actual behavior:
Boot process stuck `Reached Target Basic System`.

### General notes:
Already reinstalled, repeated the process to exclude a disk error but had the same result.

**Comment by marmarek** [comment]
Was the system rebooting normally after initial installation? Does it stuck before of after disk password prompt?
I guess only dom0 upgrade should matter here. Does it include testing repository, or only stable?

**Comment by adrelanos** [comment]
> Was the system rebooting normally after initial installation?

Yes.

> Does it stuck before of after disk password prompt?

After.

> Does it include testing repository, or only stable?

Testing.

**Comment by adrelanos** [comment]
How can I debug this? Problem is, I can't open a terminal at this point (ctrl + alt + F2).

Can I start recovery mode and then continue normal booting?

Can I boot normally but somehow get a terminal so we at least get a better error message or see where it is stuck?

**Comment by marmarek** [comment]
See https://freedesktop.org/wiki/Software/systemd/Debugging/, especially check `systemd.debug-shell=1` on kernel command line.

**Comment by knopperx** [comment]
Hi. I'm having this same issue after running `sudo qubes-dom0-update` in dom0 terminal and rebooting. I have sensitive data on the system and would like to either fix the system or recover the data. 

How do I manually repair qubes_dom0/pool100?

This seems to be an issue that has occurred for multiple people: https://groups.google.com/d/msg/qubes-users/PR3-ZbZXo_0/wem9wbGTBgAJ

**Comment by lunarthegrey** [comment]
@knopperx where you using the testing repository when you updated?

I'm not having this issue when using the stable repository. I plan to setup a test system in the future so I can help test issues like this.

**Comment by ryantate** [comment]
@adrelanos Did you ever get this resolved? Did you have to reinstall or was there some other solution? Hitting this myself: https://groups.google.com/forum/#!topic/qubes-users/u1gteTqGM3Y

**Comment by adrelanos** [comment]
Unfortunately, not. The only workaround I found was re-installing a newer version of Qubes which already had that offending upgraded package included.

**Comment by notbyosmosis** [comment]
All, I was able to recover from this state with a work-around today.  Details here:

https://github.com/QubesOS/qubes-issues/issues/5160

**Comment by adrelanos** [comment]
Potential duplicates / related:

* https://github.com/QubesOS/qubes-issues/issues/4479 `pool100`  
* https://github.com/QubesOS/qubes-issues/issues/5160 `pool100`  
* https://github.com/QubesOS/qubes-issues/issues/5632 `pool00`
* https://github.com/QubesOS/qubes-issues/issues/5160 `pool00`
* https://github.com/QubesOS/qubes-issues/issues/5643 `tpool`

//cc @tlaurion
