### ISSUE TITLE
Add OS based name to standaloneVM - Qubes Manager

### ISSUE THREAD

**Issue by TNTBOMBOM** [QubesOS/qubes-issues#4482]
### Qubes OS version:

Qubes 4.0

### Affected component(s): 

Qubes Manager Templates Naming

---

### Steps to reproduce the behavior:

Create StandealoneVM based on a template
Name the VM x or z.

### Enhancement suggestion:

let the Template column in Qubes Manager say/write StandaloneVM-debianbased or any info saying what is based on. 

because if we name it as x or y , we will never now from Qubes Manager what is it based on.

### Actual behavior:

Only written standaloneVM , without referring on which OS based on or created from.

**Comment by unman** [comment]
I would leave this to users. That is, if user wants this information they can put it in the name. Personally, I dont want details cluttered with extra information by default.
If #899 were implemented this wouldn't be an issue.

**Comment by TNTBOMBOM** [comment]
its not really up to the user even without a standaloneVM naming. 

templates/appvms all named by default. (im talking specifically on Template column in Qubes Manager)

user can still name his standaloneVM to x or y , but Template based on naming should be more descriptive as the names of others like appVMs.

**Comment by marmarek** [comment]
Please note that StandaloneVM (as the name suggests) is standalone, it is no longer connected to its template in any way. While initially it will be similar (if you create new StandaloneVM by cloning existing template, which isn't the only possibility), after you modify one or another, it will no longer be true. For example if you install some packages / updates / whatever in the template, StandaloneVM will not see it. Listing a template for it in this case will be more confusing than helping.

So, I agree with @unman - if anything, this should put into description (maybe automatically), but not as a template column. #899 is precondition for this.

**Comment by andrewdavidwong** [comment]
Closing as "won't do." If anyone has a new reason for why this should be done, please leave a comment, and we'll be happy to take another look. Thank you.
