### ISSUE TITLE
libxen-lowlevel

### ISSUE THREAD

**Issue by toxub23** [QubesOS/qubes-issues#4483]
### Qubes OS version:
R4.0
### Affected component(s): 
libxen-lowlevel
### Steps to reproduce the behavior:
Upgrade debian buster template the latest version
### General notes:
Although you can not see the problems at first glance, it is not known if they are not hidden deeper. From what you can see, the package has a dependency problem. An attempt to reinstall this package is practically impossible because Qubes tools will be removed.
https://0bin.net/paste/aC8XjAYA7BDZRXUK#RI0zgwVH0VVI0KpFf0UYIptAxm53m9WXOF7SVVUA+yY

**Comment by marmarek** [comment]
The removal of libxen-lowlevel is intentional. It got integrated back into libxen-4.8, to match upstream Debian packaging layout. See #3944
