### ISSUE TITLE
Building Centos 7 and fc29 templates fails missing qubes-mgmt-salt-vm-connector

### ISSUE THREAD

**Issue by noseshimself** [QubesOS/qubes-issues#4485]
### Qubes OS version:

4.0

### Affected component(s): 

template-centos7
template-fc29

---

### Steps to reproduce the behavior:

make qubes-vm
make template-local-centos7
make template-local-fc29

### Expected behavior:

builds a template

### Actual behavior:

+ /usr/sbin/chroot mnt yum --downloadonly install -q -y qubes-vm-dependencies qubes-vm-recommended
Error: Package: qubes-vm-recommended-4.0.4-1.centos7.noarch (template-builder-repo)
           Requires: qubes-mgmt-salt-vm-connector
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

     and

--> Copying prepared_images/fedora-29.img to qubeized_images/fedora-29/root.img...
--> Mounting qubeized_images/fedora-29/root.img
--> Installing RPMs...
Qubes Template Builder Repository               3.8 kB/s | 3.8 kB     00:01    
Error: 
 Problem: conflicting requests
  - nothing provides qubes-mgmt-salt-vm-connector needed by qubes-vm-recommended-4.0.4-1.fc29.noarch
make[1]: *** [Makefile:64: rootimg-build] Error 1

### General notes:

---

**Comment by marmarek** [comment]
Those templates were rebuild several times since the report. But also, fc29 is not supported anymore.
