### ISSUE TITLE
Qubes shutdown idle script is not working

### ISSUE THREAD

**Issue by n1m1** [QubesOS/qubes-issues#4490]
### Qubes OS version:

R4.0 (testing repos and security repos enabled)

### Affected component(s): 

Debian 9 based virtual machine

---

### Steps to reproduce the behavior:

1. `apt install qubes-app-shutdown-idle` in Debian 9
2. Shutdown Debian 9 template
3. According to this [readme](https://github.com/QubesOS/qubes-app-shutdown-idle/blob/master/README.md), set `shutdown-idle` service in a debian-9 based qube settings (I have used the graphical UI and run `qvm-service --enable VMNAME shutdown-idle` in dom0).
4. Run the VM with shutdown idle script enabled.

### Expected behavior:

After 15 minutes idle (no windows open) the qube should shutdown automatically.

### Actual behavior:

After 15 minutes nothing happens.

**Comment by andrewdavidwong** [comment]
Duplicate of #832

**Comment by andrewdavidwong** [comment]
This appears to be a [duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.
