### ISSUE TITLE
Insuficient access to /sys/devices/system/cpu/intel_pstate

### ISSUE THREAD

**Issue by noseshimself** [QubesOS/qubes-issues#4491]
### Qubes OS version:

R4.0

### Affected component(s): 

---

### Steps to reproduce the behavior:

[root@dom0 ap]# uname -a
Linux dom0 4.14.74-1.pvops.qubes.x86_64 #1 SMP Mon Oct 8 17:14:24 UTC 2018 x86_6
4 x86_64 x86_64 GNU/Linux
[root@dom0 tables]# cd /sys/devices/system/cpu/intel_pstate/
[root@dom0 intel_pstate]# cat *
100
0
cat: no_turbo: Resource temporarily unavailable
cat: num_pstates: Resource temporarily unavailable
off
cat: turbo_pct: Resource temporarily unavailable
[root@dom0 intel_pstate]# echo 92 > max_perf_pct 
bash: echo: write error: Resource temporarily unavailable
[root@dom0 intel_pstate]# echo 1 > no_turbo 
bash: echo: write error: Resource temporarily unavailable
[root@dom0 intel_pstate]# 

### Expected behavior:

error-free execution

### Actual behavior:

see above

### General notes:

System again is a Lenovo P52 running the CPU cores around 98°C by default. This works on a current Arch. The fact that there is an intel_pstate and not the ACPI equvalent indicates that the module feels confident about bein able to do its job.

---

**Comment by donob4n** [comment]
I think that this is Xen related. Have you tried "xenpm" command?

**Comment by noseshimself** [comment]
> I think that this is Xen related. Have you tried "xenpm" command?

Yes and it does not throw errors when run. Was the assumption that the
interface in sys should be working in Xen wrong? In that case it might
be a good idea to remove the module from the kernel.

Besides that: I assumed that I need to add "cpufreq=dom0-kernel" to the
xen options for xenpm to be able to do anything at all and was
reluctant to do so on this machine...

**Comment by marmarek** [comment]
> Besides that: I assumed that I need to add "cpufreq=dom0-kernel" to the xen options for xenpm to be able to do anything at all and was reluctant to do so on this machine...

No, `xenpm` talks to Xen directly, not to Linux's cpufreq driver.

**Comment by marmarek** [comment]
As for `/sys/devices/system/cpu/intel_pstate`, most CPU configuration, including power management is handled by Xen and dom0 kernel is blocked from accessing it. But I wouldn't remove this driver for various reasons:
 - we try to keep kernel config in sync with Fedora one, to ease maintenance; unless absolutely needed we'd like to avoid divergences
 - in some configurations it actually may be useful (probably `cpufreq=dom0-kernel`)
