### ISSUE TITLE
qubes-gpg-client-wrapper missing options that might be required by clients

### ISSUE THREAD

**Issue by noseshimself** [QubesOS/qubes-issues#4496]
### Qubes OS version:

4.0

### Affected component(s): 

---

### Steps to reproduce the behavior:

install GNOME evolution and configure it
set up split-gpg
force evolution to use it:
gsettings set org.gnome.evolution-data-server camel-gpg-binary '/usr/bin/qubes-gpg-client-wrapper'
Open a mail sent and signed by Zrubi.

### Expected behavior:

Verification of the signature.

### Actual behavior:

Error message: "Error verifying signature: Output from /usr/bin/qubes-gpg-client-wrapper: qubes-gpg-client: unrecognized option '--photo-viewer'

### General notes:

Maybe the rest of the world is using Thunderbird but if there is a MUA that could compete with Outlook we should keep it working.

---

**Comment by marmarek** [comment]
It is undesirable for gpg backend to give the frontend ability to execute arbitrary command (this is what the option does in practice). So, I'll add it to ignore list. This will probably break viewing photo attached to a key (unless evolution have some fallback), but shouldn't harm the main functionality.

**Comment by marmarek** [comment]
Could you add `set -x` at the top of qubes-gpg-client-wrapper (or use some other method) and provide the whole gpg command line? Just to verify there are no other unsupported options in use.

**Comment by marmarek** [comment]
I've added a test for evolution in linked PR. The `--photo-viewer` option was the only one missing (ignoring it probably will break showing a photo...). The test revealed also some race condition - some times encrypted message is not properly decrypted and appears to be empty. No idea why. Attaching `strace` to evolution shows the process do receive the message content, but for some reason does not show it.
