### ISSUE TITLE
System won't start

### ISSUE THREAD

**Issue by imestin** [QubesOS/qubes-issues#4497]
### Qubes OS version:
R4.0

### Affected component(s): 
Probably X server

### Steps to reproduce the behavior:

When I restart the system it will drop to emergency mode.

### Expected behavior:
The system starts

### Actual behavior:

The system is not getting to login prompt

### General notes:

I wanted to change the resolution of a HVM. I couldn't, then I come up with the idea of adding the video card as a device to the VM. Then everything became dark and the system halted, which is I guess normal, because in retrospect this was a bad idea.
But, the VM is not set to start on boot, so I don't understand why the system won't start.

```
Failed to start default.target: Transaction is destructive.
See system logs and 'systemctl status default.target' for details.
```

```
initrd.target - Initrd Default Target
Loaded: loaded (/use/lib/systemd/system/initrd.target; static; vendor preset: enabled)
Active: inactive (dead)
  Docs: man:systemd.special(7)
```

---

**Comment by strugee** [comment]
I don't really know but my guess is that the video card is being reserved for the qube even though it's not started automatically. That being said you should take this to [qubes-users](https://www.qubes-os.org/support/#qubes-users); this issue tracker is not the right place for support questions. See the [bug reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/).

**Comment by andrewdavidwong** [comment]
@strugee is correct. Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this does not appear to be suitable for `qubes-issues`. We ask that you please send this to the `qubes-users` [mailing list](https://www.qubes-os.org/support/) instead. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a brief comment explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.

**Comment by imestin** [comment]
Running fsck on /dev/mapper/qubes-dom0-root solved the problem.

Had to promp "y" 10-20 times
