### ISSUE TITLE
Fedora 29 minimal template prevents firewall rules from working

### ISSUE THREAD

**Issue by ekaflaer** [QubesOS/qubes-issues#4499]
### Qubes OS version:

4.0

### Affected component(s): 

Firewall rules

---

### Steps to reproduce the behavior:

* Activate the testing repo to be able to install Fedora 29 templates
* `sudo qubes-dom0-update qubes-template-fedora-29-minimal`
* Start the minimal template and install the `FirewallVM` packages specified [here](https://www.qubes-os.org/doc/templates/fedora-minimal/#package-table-for-qubes-40)
* Poweroff
* Configure this Template as base for the `sys-firewall` vm
* Create a vm and limit the outgoing connections under `Firewall rules`
* Start the vm and try if other connections are possible too

### Expected behavior:

The vm can only access for example a website specified in the Firewall rules.

### Actual behavior:

The firewall rules have no effect. I can access any site.

### General notes:

The issue does not appear with the regular fedora-29-template as base for `sys-firewall`. I was not able to find which package is actually needed for the .

Please let me know how I can debug it further.

**Comment by marmarek** [comment]
Looks like a version mismatch between qubes-core-agent and qubes-core-agent-networking. I'll add a dependency enforcing the same version of both packages.
