### ISSUE TITLE
qubes-rpc-multiplexer errors/qfile-agent "Failed to get last filename" when using qvm-copy

### ISSUE THREAD

**Issue by strugee** [QubesOS/qubes-issues#4501]
### Qubes OS version:

R4.0

### Affected component(s): 

Inter-VM file transfer

---

### Steps to reproduce the behavior:

1. Run `qvm-copy filename.txt` in a VM's terminal
2. When the file transfer target dialog box pops up, type the name of a second VM and hit enter

### Expected behavior:

The file is transferred without error.

### Actual behavior:

The terminal prints:

```
/usr/lib/qubes/qubes-rpc-multiplexer: 57: [: Linux: unexpected operator
/usr/lib/qubes/qubes-rpc-multiplexer: 68: /usr/lib/qubes/qubes-rpc-multiplexer: source: not found
EOF
Failed to get last filename
qfile-agent: Fatal error: File copy: Unknown error 544040295 (error type: Unknown error 544040295)
```

A Zenity dialog also pops up with the same text as the final line. The output appears _after_ OK'ing the dialog box.

### General notes:

The file does appear to be transferred. However IIRC I have observed cases in the past where it wasn't, especially for larger files. But I'm not sure if this is true and it could also potentially be a separate bug.

---

**Comment by marmarek** [comment]
> /usr/lib/qubes/qubes-rpc-multiplexer: 57: [: Linux: unexpected operator 
> /usr/lib/qubes/qubes-rpc-multiplexer: 68: /usr/lib/qubes/qubes-rpc-multiplexer: source: not found

That script has only 49 lines, so the problem is somewhere else.
Could you try `sh -x qvm-copy-to-vm '@default' filename.txt` to collect more info?

**Comment by marmarek** [comment]
Also, what `qubes-core-agent` version do you have? (`dpkg -l qubes-core-agent` or `rpm -q qubes-core-agent` - depending on template).

**Comment by marmarek** [comment]
What about target qube? Which template? Which qubes-core-agent version?
You can try adding `set -x` at the top of `/usr/lib/qubes/qubes-rpc-multiplexer` there, maybe that will show more details (the above looks fine).

**Comment by strugee** [comment]
Target and source qube are both based on the Debian 9 template, with a bunch of extra applications installed of course.

I added `set -x` at the top of `qubes-rpc-multiplexer` in both the source qube (`steevie-cloud`) and the target qube and reran `qvm-copy`:

```
% qvm-copy filename.txt
/usr/lib/qubes/qubes-rpc-multiplexer: 57: [: Linux: unexpected operator
/usr/lib/qubes/qubes-rpc-multiplexer: 68: /usr/lib/qubes/qubes-rpc-multiplexer: source: not found
+ stderr_pipe=/tmp/qrexec-rpc-stderr.2371
+ mkfifo /tmp/qrexec-rpc-stderr.2371
+ return_stderr_pipe=/tmp/qrexec-rpc-stderr-return.2371
+ mkfifo /tmp/qrexec-rpc-stderr-return.2371
+ exec
+ logger -t qubes.Filecopy-steevie-cloud
+ tee /tmp/qrexec-rpc-stderr-return.2371
+ cat
+ QUBES_RPC=/etc/qubes-rpc
+ LOCAL_QUBES_RPC=/usr/local/etc/qubes-rpc
+ [ 2 = 2 ]
+ export QREXEC_REMOTE_DOMAIN=steevie-cloud
+ export QREXEC_SERVICE_FULL_NAME=qubes.Filecopy
+ SERVICE_WITHOUT_ARGUMENT=qubes.Filecopy
+ [ qubes.Filecopy != qubes.Filecopy ]
+ [ -s /usr/local/etc/qubes-rpc/qubes.Filecopy ]
+ [ -s /etc/qubes-rpc/qubes.Filecopy ]
+ break
+ [ -x /etc/qubes-rpc/qubes.Filecopy ]
+ exec /etc/qubes-rpc/qubes.Filecopy
+ rm -f /tmp/qrexec-rpc-stderr-return.2371
+ rm -f /tmp/qrexec-rpc-stderr.2371
EOF
Failed to get last filename
qfile-agent: Fatal error: File copy: Unknown error 544040295 (error type: Unknown error 544040295)
```

`qubes-core-agent` version (same in both the target and the source since they're based on the same template):

```
% dpkg -l qubes-core-agent
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-=================================
ii  qubes-core-age 4.0.38-1+deb amd64        Qubes core agent
```

I should note that I just upgraded my Debian 9 template again to make sure that I had the latest bits, and I got this in the install log:

```
Setting up qubes-kernel-vm-support (4.0.22+deb9u1) ...
Loading new u2mfn-4.0.22 DKMS files...
dpkg: warning: version '4.14.18-1.pvops.qubes.x86_64
4.14.57' has bad syntax: invalid character in revision number
dpkg: warning: version '4.14.18-1.pvops.qubes.x86_64
4.14.57' has bad syntax: invalid character in revision number
It is likely that 4.14.74-1.pvops.qubes.x86_64 belongs to a chroot's host
Building for 4.14.18-1.pvops.qubes.x86_64, 4.14.57-1.pvops.qubes.x86_64, 4.14.57-2.pvops.qubes.x86_64, 4.14.74-1.pvops.qubes.x86_64, 4.9.0-6-amd64, 4.9.0-7-amd64 and 4.9.0-8-amd64
Module build for kernel 4.14.18-1.pvops.qubes.x86_64 was skipped since the
kernel headers for this kernel does not seem to be installed.
Module build for kernel 4.14.57-1.pvops.qubes.x86_64 was skipped since the
kernel headers for this kernel does not seem to be installed.
Module build for kernel 4.14.57-2.pvops.qubes.x86_64 was skipped since the
kernel headers for this kernel does not seem to be installed.
Building initial module for 4.14.74-1.pvops.qubes.x86_64
Error! Bad return status for module build on kernel: 4.14.74-1.pvops.qubes.x86_64 (x86_64)
Consult /var/lib/dkms/u2mfn/4.0.22/build/make.log for more information.
```

Not sure if that could be related? I assume not but putting it here just in case.

**Comment by marmarek** [comment]
Ok, that message is even before `/usr/lib/qubes/qubes-rpc-multiplexer` start executing. Looks like one of shell startup scripts is printing that to stderr (maybe it expect bash, while /bin/sh in Debian is dash?). And the qvm-copy error (`File copy: Unknown error 544040295`) is probably caused by some unexpected data on stdout (I'd guess by the same script).

Check `/etc/profile.d/`, and your `~/.profile`.

You can probably also get slightly more details (that stdout data) by calling `qrexec-client-vm @default qubes.Filecopy` from the source qube (it will not finish - you'll need to interrupt it, but you should get more messages).

**Comment by strugee** [comment]
Yep, moving the target VM's `.profile` out of the way fixed this... I dunno. I guess this is working as intended then, but it seems funky that this functionality loads `.profile`? What does that have to do with copying files? The error is sort of misleading too.

**Comment by marmarek** [comment]
Generally all of the qrexec services are started in full user environment, including loaded `.profile`. This allows you to set various environment variables affecting some of them (for example [split-gpg](https://www.qubes-os.org/doc/split-gpg/#setting-up-the-gpg-backend-domain)).
Shell startup scripts should _not_ output anything (at least not unless in [interactive mode](https://unix.stackexchange.com/a/26827)), exactly for the reason as described here. Printing any messages breaks many remote-execution tools, not only qubes file copy, but also scp, rsync etc.
