### ISSUE TITLE
No VMs starting

### ISSUE THREAD

**Issue by Simon-Davies** [QubesOS/qubes-issues#4502]
### Qubes OS version:

Qubes 4.0 (Latest updates from Dom0 testing repo)

### Affected component(s): 

Every VM

---

### Steps to reproduce the behavior:

Start system

### Expected behavior:

VMs start

### Actual behavior:

No VMs are starting 

See screenshot:

![111148ee-8b20-4de1-b397-2435281172ec](https://user-images.githubusercontent.com/713455/48340081-9c1a8500-e661-11e8-9eb5-bd5a2fdade9d.jpeg)

### General notes:

---

**Comment by marmarek** [comment]
Check `/var/log/xen/console/guest-sys-net.log`.

**Comment by Simon-Davies** [comment]
I installed the latest ISO from scratch as I needed a working system ASAP.

I will avoid the Dom0 testing repo on my work machine from now on.

**Comment by andrewdavidwong** [comment]
Closing this for now as it appears that the issue no longer affects any Qubes users. If you believe this is a mistake, or if anyone is still affected by this issue, please leave a comment, and we'll be happy to reopen this. Thank you.
