### ISSUE TITLE
Qube deletion doesn't clean up enabled systemd unit

### ISSUE THREAD

**Issue by strugee** [QubesOS/qubes-issues#4503]
### Qubes OS version:

R4.0

### Affected component(s):

Qube Manager

---

### Steps to reproduce the behavior:

1. Create a qube, say `foo`, and check "start automatically on boot" in its settings
2. Notice that `ls /etc/systemd/system/multi-user.target.wants/` lists `qubes-vm@foo.service`, as expected
3. Delete `foo`

### Expected behavior:

`qubes-vm@foo.service` is disabled.

### Actual behavior:

`qubes-vm@foo.service` is never removed from `/etc/systemd/system/multi-user.target.wants` and causes (completely cosmetic) failures on system startup.

### General notes:

Low priority, obviously, but a bug nevertheless :P

---

**Comment by andrewdavidwong** [comment]
> `qubes-vm@foo.service` is never removed from `/etc/systemd/system/multi-user.target.wants` and causes (completely cosmetic) failures on system startup.

Wouldn't this have non-cosmetic results if you ever create another VM with the same name in the future?
