### ISSUE TITLE
Mouse focus not always working when switching apps over workspaces in the workspace switcher

### ISSUE THREAD

**Issue by improvethings** [QubesOS/qubes-issues#4506]
### Qubes OS version:

R4.0

### Affected component(s): 

graphical window manager

---

### Steps to reproduce the behavior:

I'm not sure how to explain this well. I have 4 workspaces filled with running applications -- each workspace is two monitors. Often I'll click on a specific app in a window. 
For example, I'm writing this on the right monitor of workspace window 1. My dom0 terminal is left monitor of workspace window2. I click on the terminal icon at the top of my desktop to jump directly to the dom0 terminal -- and although workspace window 2 is now visible, and my mouse is hovering ther dom0 terminal, it has not "clicked" in that the cursor is still not accessible. 

In order to have the mouse focus where I intend, when this happens which is more often than not when switching workspace windows via the icons at the top of the desktop, is I have to switch to another workspace window to achieve mouse focus there, and then back to the intended workspace window and app, such as the dom0 terminal. Sometimes this takes several attempts of workspace window clicking until mouse focus happens. 

What I noticed today while clicking a little more umm actively, was that I got a popup from an app in another workspace on the side. 

On workspace window 1, I have Thunderbird full screen on the right monitor. On workspace window 2, I have terminator split into 4 terminals, also full screen. As I was clicking around teminator on the various terminals trying to get the mouse to focus on one of them so I could type, I saw a Thunderbird options menu quickly appear. For some reason it clicked a setting on workspace window 1, when I was only clicking around on the right side of workspace window 2. In this case, both of these apps were using the same Debian 9 AppVM. 

Note, this only happens sometimes, not all of the time -- but quite frequently. I haven't yet discovered how to consistently reproduce. 

### Expected behavior:

Expected behaviour is when I have mouse cursor focus in an app in one workspace, I should be able to click on the application icon in the top desktop panel workspace switcher, and jump immediately to the application I want, with mouse focus on that application. 

### Actual behavior:

I described above.

### General notes:

Qubes R4.0. Debian 9 AppVMs

---

**Comment by andrewdavidwong** [comment]
I assume you're using the default DE (Xfce4). This sounds like it might be an Xfce4 or Fedora bug, i.e., possibly not Qubes-specific. It also sounds like it might not be a bug at all, but just behavior dependent on user-configurable window focus settings. Please take a look at those settings and try some adjustments (search online for instructions, if needed, as that isn't Qubes software). If that still doesn't work and you have the ability to test on baremetal Fedora, that'd be helpful.

**Comment by marmarek** [comment]
I think this issue is already covered with https://github.com/QubesOS/qubes-issues/issues/1455 and https://github.com/QubesOS/qubes-issues/issues/3267

**Comment by improvethings** [comment]
Just as an update, as I'm dealing with it right now. This is in a debian9 AppVM. When I open a terminal or browser with another AppVM, I can type in those applications. 
In the Debian9 AppVM, I'm not sure what triggers it yet, but I can no longer type inside any app.
For example, I have a fedora26 (I know I know, I don't use it normally) terminal beside the debian terminal. If I click directly on "File" or "Edit" on both, Fedora works as expected, but the debian9 terminal comes to the front of the other terminal, but the menus don't actually open. If I click in the terminal, the cursor never goes solid to type. If I click in the main window of the fedora terminal, everything works fine. 
I am also able to use dom0 and Template debian 9 terminals just fine, just not this specific user AppVM after something happens.

**Comment by andrewdavidwong** [comment]
@improvethings, this issue has been closed as a [duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) of #1455 and/or #3267. Please comment on the appropriate one of those issues. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.
