### ISSUE TITLE
VMs not starting - libxenlight failed to create new-domain in 4.0

### ISSUE THREAD

**Issue by t3cher** [QubesOS/qubes-issues#4507]
### Qubes OS version:

`R4.0`

### Affected component(s): 

All VMs

---

### Steps to reproduce the behavior:

Installed `R4.0` iso. Qubes booted up with a few errors but they were fixed by Qubes.

### Expected behavior:

Qubes interface seemed to function

### Actual behavior:

I tried opening a few VMs in the terminal with `qvm-start`, for example the VM personal, but i got an error

![img_20181114_215831](https://user-images.githubusercontent.com/45058479/48534128-e9624680-e85b-11e8-8592-9fa2bafe4bdf.jpg)

Next I checked /var/log/libvirt/libxl/libxl-driver.log and here is what it contained

![img_20181114_215854](https://user-images.githubusercontent.com/45058479/48534194-27f80100-e85c-11e8-99ed-4289bad9eec8.jpg)

### General notes:

When I hover over all my VM's in the start menu I would expect to see multiple options but the only option I see is Qube settings

![img_20181114_215959](https://user-images.githubusercontent.com/45058479/48534218-43630c00-e85c-11e8-8a4a-061ab2d4f810.jpg)

I am a complete beginner at Qubes, so I am sorry if my explanation made no sense.  Just getting Qubes on my Dell Inspiron was frustrating enough, but now I am confronted with errors.  If someone could help me it would mean the world to me.

---

**Comment by marmarek** [comment]
According to libxl-driver.log, you have not (enabled) IOMMU. You probably also get this error at the start of installation, explaining it is necessary for Qubes to run.
Check your BIOS settings - it may be named like VT-d, or virtualization for direct io. Then after you enable it I suggest reinstall.

Anyway, this seems better fitted for qubes-users mailing list. See https://www.qubes-os.org/doc/reporting-bugs/ and https://www.qubes-os.org/support/#qubes-users
