### ISSUE TITLE
Failing to load kernel modules/X startup failed, aborting installation [AMD Ryzen 2200G]

### ISSUE THREAD

**Issue by riodejaneiro666** [QubesOS/qubes-issues#4510]
Hello,

I'm having trouble installing Qubes 4.0 on a new system. It's a Ryzen 2200G with integrated Vega graphics only, 8GB DDR4 and a ASROCK AB350-HDV Mainboard. I've found a almost identical mainboard model in the compatiblity list, so this shouldn't be an issue, aswell as the CPU since AMD supports the necessary virtualization features quite some time.

I've found a similiar thread reporting issue(s) getting a error message called "Failed to load kernel modules" and it seems there were people who managed to get further than the basis (very first) installation. I want to widen the discussion about the issue since I have a few other error messages besides the above mentioned, also there are still people reporting the same (or similiar to my) problem but there hasn't been a solution found yet in the other thread.

My installation medium is a USB drive, I created it using the "Rufus" tool.
I am attaching pictures of the installation process:

![1](https://user-images.githubusercontent.com/45089192/48600908-32a2bb00-e96e-11e8-9a76-0f5de276969b.JPG)
![2](https://user-images.githubusercontent.com/45089192/48600926-4e0dc600-e96e-11e8-8ae5-91bd92d708e3.JPG)
![3](https://user-images.githubusercontent.com/45089192/48600949-641b8680-e96e-11e8-9c31-33d5d8b48798.JPG)
![4](https://user-images.githubusercontent.com/45089192/48600974-801f2800-e96e-11e8-8f35-060fa187a946.JPG)
![4a](https://user-images.githubusercontent.com/45089192/48601018-9c22c980-e96e-11e8-993d-0a5be098a788.JPG)
![4b](https://user-images.githubusercontent.com/45089192/48601043-ae046c80-e96e-11e8-8ea8-b1ec32eb2075.JPG)
![4c](https://user-images.githubusercontent.com/45089192/48601061-be1c4c00-e96e-11e8-8c76-31dd7a202de6.JPG)

Once I start the installation in basics graphics mode I get additional information:

![img_1825](https://user-images.githubusercontent.com/45089192/48601094-ddb37480-e96e-11e8-8449-c5a51fd4a9bf.JPG)
![img_1827](https://user-images.githubusercontent.com/45089192/48601106-ed32bd80-e96e-11e8-9459-6dbfa6c1a750.JPG)
![img_1830](https://user-images.githubusercontent.com/45089192/48601111-f3c13500-e96e-11e8-90ff-25bed401b77e.JPG)

What I did as of now:
- Trying it with a ISO image, not a DD image.
- Disabling clocking down or boosting cpu frequency in BIOS (because of ACPI Error).
- Same for the RAM.
- Inspecting the BIOS for virtualization options and enabling them.
- Fiddling around with the "boot parameter" before you actually hit install, e.g. "noexitboot" and all this.
- Using legacy and UEFI to boot. Also using UEFI with secure boot disabled.
- Trying to delete the "System Volume Information" data which Windows writes on the installation medium. Shouldn't affect the process too much even if it worked though (?).

All of this doesn't help since it's becoming obvious the hardware and the installation medium/Xen having a problem communicating with each other. This first must be handled, I am even a complete Linux newb for this matter. How to solve this? I really want your OS.

I appreciate any help. Thank you.

**Comment by 0spinboson** [comment]
it's probably due to the 4.0 boot medium still using the 4.14 kernel, rather than kernel 4.18.

**Comment by riodejaneiro666** [comment]
> 
> 
> it's probably due to the 4.0 boot medium still using the 4.14 kernel, rather than kernel 4.18 (the former doesn't include support for RR/the vega APU yet).

Thanks for checking in. Do you have any information about 4.0.1-rc1 having the newer kernel? I couldn't seem to find any info on the official page. I am downloading and trying it anew with 4.0.1-rc1.

I can either do this or I need to build qubes myself using Linux, incorporating the new kernel myself. Those are the only two options, correct or not? If not what are my options to get the new?

**Comment by 0spinboson** [comment]
well, the directory structure of the qubes installation medium suggests it should be possible to include additional kernels in the relevant directory (iirc 'extra kernels'?), but idk if that works in practice.

**Comment by andrewdavidwong** [comment]
Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this does not appear to be suitable for `qubes-issues`. We ask that you please send this to the `qubes-users` [mailing list](https://www.qubes-os.org/support/) instead. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a brief comment explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.

**Comment by sysvar** [comment]
I am having the exact same issue. If there is a way of extracting detailed error messages out I'd be happy to post them. I so want to switch to Qubes!

**Comment by HarderCode** [comment]
@riodejaneiro666,Sir, I got the same issues at the begining and  I didn't find a solution for that( as I researched). But in the official website of Qubes OS, it says that you have to format Qubes OS-ISO as a DD Image. If you have no another configuration mistakes on Anaconda. It will work.
