### ISSUE TITLE
Removing a killed VM left a XEN VM behind that needs to be removed by hand

### ISSUE THREAD

**Issue by noseshimself** [QubesOS/qubes-issues#4511]
### Qubes OS version:

R4.0

### Affected component(s): 

---

### Steps to reproduce the behavior:

What I did:
cloned a bionic template and called it "kali" and started it
added the repository for kali-rolling
apt update
apt dist-upgrade

Somewhere during the installation of packages the VM closed its
terminal window and the communication with the VM ceased (although xl
console kali showed it was still alive): I didn't watch out for the removal of the qubes-* packages.

I tried qvm-shutdown kali and when that didn't work (which I expected)
qvm-kill kali, followed by qvm-remove kali..

Whenever I create a new machine called kali, I'm getting

[ap@dom0 ~]$ qvm-start kali
Start failed: operation failed: domain 'kali' already exists with uuid
f6264fd8-6c9e-4d41-a3ad-8ae44d4b64fb, see /var/log/libvirt/libxl/libxl-
driver.log for details

Taking a look at /etc/libvirt I can still see remains of kali in the xl
database...

### Expected behavior:

qvm-remove should remove a VM completely from Xen.

### Actual behavior:

I had to get rid of the remains using virsh undefine kali to cremate the remains.

### General notes:

I've found people asking how to deal with this error message from time to time, sometimes getting interesting hints for fixing it. Is is possible to provide a utility to check the consistency and correctness of the not directly connected parts of the virtualization infrastructure as in

$ qvm-check-sanity
[...]
There is a Xen domain "kali" not defined in Qubes. Remove [y/N]?

---

**Comment by unman** [comment]
See existing #1910, #4253

**Comment by noseshimself** [comment]
close it, please but it might be a good idea to change the title of #4253 a bit.

**Comment by andrewdavidwong** [comment]
> close it, please but it might be a good idea to change the title of #4253 a bit.

Title updated.
