### ISSUE TITLE
Debian 10 - buster having issues with sudo apt install

### ISSUE THREAD

**Issue by Simon-Davies** [QubesOS/qubes-issues#4513]
### Qubes OS version:

Qubes 4.0 (R4.0)

### Affected component(s): 

Debian 10 - buster template created by cloning and upgrading Debian 9 - stretch template

---

### Steps to reproduce the behavior:

Try to install kali-archive-keyring

### Expected behavior:

Installs fine

### Actual behavior:

```
sudo apt install ./kali-archive-keyring_2018.1_all.deb
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'kali-archive-keyring' instead of './kali-archive-keyring_2018.1_all.deb'
The following packages will be REMOVED:
  qubes-core-agent-passwordless-root
The following NEW packages will be installed:
  kali-archive-keyring
0 upgraded, 1 newly installed, 1 to remove and 20 not upgraded.
1 not fully installed or removed.
Need to get 0 B/6,888 B of archives.
After this operation, 43.0 kB disk space will be freed.
Do you want to continue? [Y/n] y
Get:1 /home/user/kali-archive-keyring_2018.1_all.deb kali-archive-keyring all 2018.1 [6,888 B]
(Reading database ... 132508 files and directories currently installed.)
Removing qubes-core-agent-passwordless-root (4.0.38-1+deb10u1) ...
Removing user user from group sudo
gpasswd: user 'user' is not a member of 'sudo'
dpkg: error processing package qubes-core-agent-passwordless-root (--remove):
 installed qubes-core-agent-passwordless-root package post-removal script subprocess returned error exit status 3
Errors were encountered while processing:
 qubes-core-agent-passwordless-root
N: Download is performed unsandboxed as root as file '/home/user/kali-archive-keyring_2018.1_all.deb' couldn't be accessed by user '_apt'. - pkgAcquire::Run (13: Permission denied)
E: Sub-process /usr/bin/dpkg returned an error code (1)
user@pentesting-kali2:~$ sudo su
root@pentesting-kali2:/home/user# apt install ./kali-archive-keyring_2018.1_all.deb
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'kali-archive-keyring' instead of './kali-archive-keyring_2018.1_all.deb'
The following packages will be REMOVED:
  qubes-core-agent-passwordless-root
The following NEW packages will be installed:
  kali-archive-keyring
0 upgraded, 1 newly installed, 1 to remove and 20 not upgraded.
1 not fully installed or removed.
Need to get 0 B/6,888 B of archives.
After this operation, 43.0 kB disk space will be freed.
Do you want to continue? [Y/n] y
Get:1 /home/user/kali-archive-keyring_2018.1_all.deb kali-archive-keyring all 2018.1 [6,888 B]
(Reading database ... 132508 files and directories currently installed.)
Removing qubes-core-agent-passwordless-root (4.0.38-1+deb10u1) ...
Removing user user from group sudo
gpasswd: user 'user' is not a member of 'sudo'
dpkg: error processing package qubes-core-agent-passwordless-root (--remove):
 installed qubes-core-agent-passwordless-root package post-removal script subprocess returned error exit status 3
Errors were encountered while processing:
 qubes-core-agent-passwordless-root
N: Download is performed unsandboxed as root as file '/home/user/kali-archive-keyring_2018.1_all.deb' couldn't be accessed by user '_apt'. - pkgAcquire::Run (13: Permission denied)
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

### General notes:

---

**Comment by h01ger** [comment]
On Sat, Nov 17, 2018 at 05:44:55AM -0800, Simon Davies wrote:
> Debian 10 - buster template created by cloning and upgrading Debian 9 - stretch template
 
what is your issue exactly? you have not described anything.


-- 
cheers,
	Holger

-------------------------------------------------------------------------------
               holger@(debian|reproducible-builds|layer-acht).org
       PGP fingerprint: B8BF 5413 7B09 D35C F026 FE9D 091A B856 069A AA1C

**Comment by Simon-Davies** [comment]
Read the error output from the terminal:

```
dpkg: error processing package qubes-core-agent-passwordless-root (--remove):
 installed qubes-core-agent-passwordless-root package post-removal script subprocess returned error exit status 3
Errors were encountered while processing:
 qubes-core-agent-passwordless-root
N: Download is performed unsandboxed as root as file '/home/user/kali-archive-keyring_2018.1_all.deb' couldn't be accessed by user '_apt'. - pkgAcquire::Run (13: Permission denied)
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by h01ger** [comment]
On Sat, Nov 17, 2018 at 05:49:51AM -0800, Simon Davies wrote:
> N: Download is performed unsandboxed as root as file '/home/user/kali-archive-keyring_2018.1_all.deb' couldn't be accessed by user '_apt'. - pkgAcquire::Run (13: Permission denied)

this package is not part of Debian...


-- 
cheers,
	Holger

-------------------------------------------------------------------------------
               holger@(debian|reproducible-builds|layer-acht).org
       PGP fingerprint: B8BF 5413 7B09 D35C F026 FE9D 091A B856 069A AA1C

**Comment by Simon-Davies** [comment]
I know it's not. I've installed the Kali repo and I'm trying to install the kali-archive-keyring so I can download packages from it. Kali uses Debian Testing as its base.

If you can't say anything useful why even reply?

**Comment by h01ger** [comment]
On Sat, Nov 17, 2018 at 05:56:18AM -0800, Simon Davies wrote:
> I know it's not. I've installed the Kali repo and I'm trying to install the kali-archive-keyring so I can download packages from it. Kali uses Debian Testing as its base.
> 
> If you can't say anything useful why even reply?

I could not say anything more useful that what I said, because you were
not giving all needed information.

But anyway, I will stay of of this issue now.


-- 
cheers,
	Holger

-------------------------------------------------------------------------------
               holger@(debian|reproducible-builds|layer-acht).org
       PGP fingerprint: B8BF 5413 7B09 D35C F026 FE9D 091A B856 069A AA1C

**Comment by Simon-Davies** [comment]
I'm sorry if I came across harsh. I've just been through hell recently. Helping hundreds of people for free running the largest hacking community globally but my ex who has serious mental health issues left me with just a text.

I earn a fortune running my own Security company but what's the point in money. Without love we aren't living.

If you want to join I work with DarkCoderSc and Mobman. The forum is ax0nes.com. Message me your username and I'll accept you.

Once again sorry for coming across harsh. I just feel dead inside atm.

**Comment by h01ger** [comment]
On Sat, Nov 17, 2018 at 09:05:05AM -0800, Simon Davies wrote:
> I'm sorry if I came across harsh.

apologies accepted & appreciated. and i'm sorry about your situation!

back to the topic, the full output of 'apt upgrade' or 'apt install'
would be useful to debug this, plus the contens of
/etc/apt/sources.list and /etc/apt/sources.list.d/*

the cause is probably that buster currently has no python-xpyb,
salt-common and salt-ssh packages, so you need to install those 3 from
sid.

(the reasons for that are explained on https://tracker.debian.org/xpyb
and https://tracker.debian.org/salt - look for 'updating $pkg introduces
new bugs: ###')


-- 
cheers,
	Holger

-------------------------------------------------------------------------------
               holger@(debian|reproducible-builds|layer-acht).org
       PGP fingerprint: B8BF 5413 7B09 D35C F026 FE9D 091A B856 069A AA1C

**Comment by Simon-Davies** [comment]
I fixed the issue by running the below command in the Terminal:

sudo gpasswd - a user sudo
