### ISSUE TITLE
seven new Meltdown and Spectre attacks

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#4516]
https://www.zdnet.com/article/researchers-discover-seven-new-meltdown-and-spectre-attacks/

**November 14, 2018**

Quote:

> Experiments showed that processors from AMD, ARM, and Intel are affected.

**Comment by andrewdavidwong** [comment]
Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this does not appear to be suitable for `qubes-issues`. We ask that you please send this to the `qubes-users` [mailing list](https://www.qubes-os.org/support/) instead. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a brief comment explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.

**Comment by adrelanos** [comment]
https://groups.google.com/forum/#!topic/qubes-users/eTSZ5vb5ugo
