### ISSUE TITLE
qubes-templates-community-testing repository metadata outdated

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#4517]
### Qubes OS version:
R4
### Affected component(s): 
dom0

### Steps to reproduce the behavior:

    sudo qubes-dom0-update --action=reinstall qubes-template-whonix-gw-14

### Expected behavior:

Download `qubes-template-whonix-gw-14 4.0.1-201811150918`.

### Actual behavior:

Download `qubes-template-whonix-gw-14-4.0.1-201811040215`.

### General notes:
The newer TemplateVM packages got uploaded but the yum repodata was not properly updated?

`sudo qubes-dom0-update --clean --action=reinstall qubes-template-whonix-gw-14` did not change the result.

Both,

* `qubes-template-whonix-gw-14 4.0.1-201811150918` and
* `qubes-template-whonix-gw-14-4.0.1-201811040215`

can be found in https://yum.qubes-os.org/r4.0/templates-community-testing/rpm/ - so we can be reasonably certain that `qubes-templates-community-testing` is properly enabled on my system.

Perhaps just an outdated mirror?

Setting `fastestmirror = 0` did not help though.
Commenting out `metalink` and using `baseurl` instead did not help either.

### Related issues:

Do we have a ticket for automation of removal of old versions of (TemplateVM) packages? Users thinking to reinstall a newer version (due to occasionally outdated repository metadata?) and then ending up installing a non-recommended version is a major source of confusion.

**Comment by andrewdavidwong** [comment]
Closing as "not an issue." If you believe this is a mistake, please leave a comment, and we'll be happy to take another look. Thank you.

**Comment by adrelanos** [comment]
Marek Marczykowski-Górecki:
> Action `reinstall` means "reinstall exactly the same package". It is not supposed to upgrade it. You probably meant `--action=upgrade`.
> 

This is correct. My mistake.
