### ISSUE TITLE
qubes-dom0-update combined --action=upgrade --action=reinstall command

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#4518]
### Qubes OS version:
R4

### Affected component(s): 
dom0

### Steps to reproduce the behavior:
Follow

* https://www.whonix.org/wiki/Qubes/Reinstall OR
* https://www.qubes-os.org/doc/reinstall-template/

### Expected behavior:
Easy combined upgrade and reinstall command without explanation required.

### Actual behavior:
Commands for upgrade and reinstall have to be tried separately. Usability issue.

* `--action=upgrade`
* `--action=reinstall`

I say "tried" since it is hard for users to find out the exact version of their currently installed TemplateVM package and then to also find out the latest TemplateVM package version, and to compare them.

### General notes:
When users say "I want to reinstall my TemplateVM" what most normal users probably actually want is "fix my TemplateVM". Only a very small and very technical amount of users will insist on "I want to reinstall the exact same version which is currently installed".

I think this is a source of confusion. When layman users run `--action=reinstall` regular users would expect the latest and greatest recommended (stable) TemplateVM. (Point release in technical terms.)

Keeping the original meaning of `--action=upgrade` and `--action=reinstall` is probably ok.

### Related issues:
https://github.com/QubesOS/qubes-issues/issues/4517

**Comment by andrewdavidwong** [comment]
I didn't understand what was being requested by this issue until I read https://www.whonix.org/wiki/Qubes/Reinstall. Now I (think I) understand that it's a request for a single command that builds in the logic and sequence of actions described on that page.

**Comment by alimirjamali** [comment]
@andrewdavidwong This issue from 2018 is about installing/reinstalling Whonix templates. The relevant Whonix Wiki on reinstalling Whonix templates on Qubes OS has been updated many times, mentioning the modern preferred `qvm-template` tool. The original issue is not relevant anymore. It was not even relevant for R4.1 and dates back to R4.

I believe the issue could be closed unless the Whonix project lead believes it to be still relevant.

**Comment by adrelanos** [comment]
This issue applies equally to `qvm-template`. User should first try `upgrade`, then `reinstall`. This is a usability issue that can be seen here:
https://www.whonix.org/wiki/Qubes/Reinstall

**Comment by alimirjamali** [comment]
> This issue applies equally to `qvm-template`.

In this case, I believe it is better to update Issue title. Otherwise it might remain unattended for a longer period.

**Comment by marmarek** [comment]
The GUI template manager got reworked in R4.3 and now proposes appropriate action automatically based on what version is currently installed and what is available.
