### ISSUE TITLE
Feature request: more flexibility to move qubes/vms to other storage pools

### ISSUE THREAD

**Issue by vogelfreiheit** [QubesOS/qubes-issues#4523]
### Qubes OS version:

R4

### Affected component(s): 

Qube Manager
qvm-clone

---

### Steps to reproduce the behavior:

- Attempt cloning/moving templates or VMs to other storage.
(with any of the supported cli or GUI tools)

### Expected behavior:

Seamless moving of a qube/vm from one storage pool to another, in a stable fashion that does not result (at any point) in that VM or template being moved back to the main storage.

### Actual behavior:

Often the qube/vm ends up moved to the main storage pool,, and there is no support for actually moving (that is, clone + erase from origin) a qube without a two step process that seems to fail at times. This manifested mostly when cloning or creating AppVMs of an imported template built via qubes-builder.

Renaming a qube actually results in said qube being moved back to the default/main pool.

### General notes:

I understand there is a degree of "wrapping existing tools" involved here, but without going to great lengths in pulling logs and trying to replicate the circumstances of those times when I had issues coming up (ex. a qube being moved back to default storage when it was already in another pool, ex. while renaming), it is safe to say the current tools are not handling secondary storage very well, meaning that the inner process obscured by the management tools can, and in some situations (like rneaming) *will* result in undesirable storage operations.

---

### Related issues:

While not directly related to this, I have observed major performance pitfalls when moving to/from NVMe to SATA based SSDs. That needs a separate issue and further inspection, though. It would help if fio or related tools were included in the dom0 package list (not installed by default), so advanced users can fine tune and benchmark their storage.

**Comment by vogelfreiheit** [comment]
Nice! Thanks M.

**Comment by brendanhoar** [comment]
@vogelfreiheit wrote:
> While not directly related to this, I have observed major performance pitfalls when moving to/from NVMe to SATA based SSDs. That needs a separate issue and further inspection, though. It would help if fio or related tools were included in the dom0 package list (not installed by default), so advanced users can fine tune and benchmark their storage.

Perhaps related to #5134 ? 

Brendan
