### ISSUE TITLE
Unable to boot into Qubes OS installer with VT-d on thinkpad T530

### ISSUE THREAD

**Issue by D30KP2** [QubesOS/qubes-issues#4524]
### Qubes OS version:

R4.0

### Affected component(s): 

Installer

---

### Steps to reproduce the behavior:

Note : in the following statements, VT-d is turned on with no explicit description.

Write a Qubes 4.0 iso into a USB-stick, with dd in fedora 26 or Ultraiso in windows 10.Boot ThinkPad T530 in legacy mode with the USB stick. When prompted by the installer, choose"Install Qubes 4.0".

### Expected behavior:

The installer(anacoda) should start normally.

### Actual behavior:

After choosing "Install Qubes 4.0", the screen splashes with sth like "Loading xen, linux 4.14, initial ramdisk", then the system freezes,  with the cursor splashing and the CPU fans rotating in a high speed.There is no any more information displayed on the screen, except the cursor.

### General notes:

If you disable VT-d and the TPM in bios, the installer can boot normally.

---

**Comment by D30KP2** [comment]
The hardware preferences are as follows: i7 3840QM , 4GB Samsung RAM *2, Nvidia NVS 5400(Disabled in bios) , bios version 2.73 (G4ETB3WW).

**Comment by andrewdavidwong** [comment]
Might be too localized for qubes-issues, but I'll leave it open for now to see what the devs think.

**Comment by esote** [comment]
@D30KP2 Try with the R 4.0.1-rc1 install. That has a newer kernel and Xen version.
