### ISSUE TITLE
Unable to Start Qubes OS 4.0 with VT-d turned on , on ThinkPad T530

### ISSUE THREAD

**Issue by D30KP2** [QubesOS/qubes-issues#4525]
### Qubes OS version:

R4.0

### Affected component(s): 

The whole OS.

---

### Steps to reproduce the behavior:

Install Qubes 4.0 on ThinkPad T530 in legacy mode, with VT-d turned off.Go to BIOS Setup, enable Intel VT-d, and restart the computer, to boot into qubes 4.0.

### Expected behavior:

The system should start normally.

### Actual behavior:

The same as issue #4524.

### General notes:

In order to work around, I tried to add "iommu=no-igfx" to the grub command line, but it does not work.

---

### Related issues:

See issue #4524 for more information about my laptop and the question.

**Comment by andrewdavidwong** [comment]
I don't understand. How is this different from #4524?

**Comment by andrewdavidwong** [comment]
Oh, I guess you're reporting that it still fails at a later stage after applying the workaround described in #4524. This should probably just be combined with #4524, then.

-----

This appears to be a [duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.
