### ISSUE TITLE
Enigmail frequently fails to initialize with Split GPG

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#4528]
### Qubes OS version:

`R3.2`

### Affected component(s): 

Split GPG (with Thunderbird and Enigmail on Fedora 28 and earlier)

---

### Steps to reproduce the behavior:

Start Thunderbird with the Enigmail plugin installed, which auto-starts my email VM, which in turn auto-starts my Split GPG backend VM.

### Expected behavior:

Enigmail interfaces with the Split GPG backend VM normally. This happens most of the time (estimated ~60%).

### Actual behavior:

Receive a popup in Thurderbird stating that Enigmail failed to initialize. This happens pretty frequently (estimated ~40%).

To work around it, I do the following:
1. Shutdown both the Split GPG backend VM and the email VM.
2. Start the Split GPG backend VM.
3. Start the email VM.
4. Start Thunderbird in the email VM.

Doing things in this particular order seems to avoid the problem.

### General notes:

This problem has been occurring for quite a while. All of these VMs are based on Fedora 28, but it also happened in previous Fedora versions. I have no reason to believe it's Fedora-specific.

---

**Comment by marmarek** [comment]
Is your email VM set to autostart? Does it also happen if you start it
manually (but not the Split GPG backend VM)?

**Comment by andrewdavidwong** [comment]
> Is your email VM set to autostart?

No, the VM is not set to autostart. I always start it manually.

> Does it also happen if you start it manually (but not the Split GPG backend VM)?

Yes. As explained above, it usually happens when I start Thunderbird in the email VM before the Split GPG backend VM is off. If I start the Split GPG backend first (before starting Thunderbird in the email VM), this problem usually does not occur. (Sometimes it still does, but less frequently.)

**Comment by SvenSemmler** [comment]
I see the same behavior, so it's nothing specific to Andrew's setup.

**Comment by marmarek** [comment]
Just Fedora template should be enough. Indeed there is no comment, but relevant labels are added.

**Comment by marmarek** [comment]
Clarification: the fix is on the backend side.

**Comment by andrewdavidwong** [comment]
> The package `app-linux-split-gpg` has been pushed to the `r4.0` stable repository for the **Fedora `centos7`** template.

@marmarek, is there an error in the announcement script?

**Comment by andrewdavidwong** [comment]
@marmarek: FYI, I tried to install it in the Fedora 28 TemplateVM on which my backend VM is based, but it wasn't found (and shouldn't already be installed, because `current-testing` is not enabled here):
```
$ sudo dnf install --refresh --enablerepo=qubes-vm-r3.2-current-testing qubes-gpg-split
Last metadata expiration check: 0:00:00 ago on 2018-12-20T18:29:49 CST.
Package qubes-gpg-split-2.0.33-1.fc28.x86_64 is already installed, skipping.
Dependencies resolved.
Nothing to do.
Complete!
```
It's ok, though. I'll just wait until it lands in the stable repo.

**Comment by marmarek** [comment]
> > The package `app-linux-split-gpg` has been pushed to the `r4.0` stable repository for the **Fedora `centos7`** template.
> 
> @marmarek, is there an error in the announcement script?

Oh, it looks to be the case. Fixed.

**Comment by marmarek** [comment]
> It's ok, though. I'll just wait until it lands in the stable repo.

You can try `upgrade` instead of `install`. I'm not really sure, but I think dnf doesn't try to upgrade on `install` action (contrary to `yum`...).
