### ISSUE TITLE
bring back "Show/Hide inactive VMs" button in qubes-manager (R4.0)

### ISSUE THREAD

**Issue by qjoo** [QubesOS/qubes-issues#4529]
### Qubes OS version:
4.0.1-rc1
  
### Affected component(s): 
qubes-manager

---

### Steps to reproduce the behavior:

Qubes Manager before R4.0 had a button to hide inactive VMs.

This is especially handy when the list contains many VMs but only the currently running
VMs are relevant.

### Expected behavior:
"Show/Hide inactive VMs" button is available in qubes-manager

### Actual behavior:

No such functionality is available in qubes-manager-4.0.22-1

**Comment by marmarek** [comment]
List of running VMs with basic info (memory, color) is available in domains widget, where you can also easily access qube settings. Do you think some more info would be useful there (that you use qube manager for that now)?

**Comment by qjoo** [comment]
* I was very glad when you brought back qubes-manager in R4.0 (after it was unavailable initially)
* now that #4163 has been fixed I'd like to get the features we already had in Qubes 2.x and 3.x back.

For me the widget isn't very user friendly since I can not access it via keyboard shortcuts and it simply hasn't the same amount of information as qubes-manager in R3 used to have.
For example I often need to quickly identify which DVM is causing high CPU load to simply kill it. In R3 that was an easily task, not so much in R4.


related: https://groups.google.com/d/msgid/qubes-users/675a3820-1374-e3f7-9b20-78afc4259c34%40riseup.net

**Comment by donob4n** [comment]
Hi, I would like to fix this ticket.
I am just testing the last version and seeing the icon size changes and the text added, so I don't know where to put some Show/Hide buttons (probably next to Restore)

My idea is to add a filter button for:
- Hide halted qubes
- Hide system qubes (net-vm's, sys-usb,...)
- Hide templates
- Once this is done maybe add an star icon on each row and a 'Show only favourites' button

I would like to hear some comments specially @ninavizz , @marmarta , @marmarek

**Comment by marmarta** [comment]
> Hi, I would like to fix this ticket.
> I am just testing the last version and seeing the icon size changes and the text added, so I don't know where to put some Show/Hide buttons (probably next to Restore) (EDIT: Maybe on the right part of the search bar?, it is tooooo long for qube name)
> 
> My idea is to add a filter button for:
> 
>     * Hide halted qubes
> 
>     * Hide system qubes (net-vm's, sys-usb,...)
> 
>     * Hide templates
> 
>     * Once this is done maybe add an star icon on each row and a 'Show only favourites' button
> 
> 
> I would like to hear some comments specially @ninavizz , @marmarta , @marmarek

Sounds good!  for me, next to search bar sounds best. It suits it both thematically and also provides a good use for all that space.

**Comment by donob4n** [comment]
Probably some cool icons would be better but I think that 'checkboxes' are pretty fine too. At least a good point for start to code:
![manager1](https://user-images.githubusercontent.com/35405566/97079003-b9e41900-15f0-11eb-920a-48136e985295.png)

What do you see better, select what you want to show or select what you want to hide? Maybe some combination of both...

**Comment by marmarta** [comment]
I like the checkboxes! Let's definitely keep it simple - not mixed mode, just "select what to show" XOR "select what to hide". I'm slightly in favor of "select what to show", it feels more intuitive.
