### ISSUE TITLE
qvm-device command options seem unintuitive and difficult to use

### ISSUE THREAD

**Issue by GammaSQ** [QubesOS/qubes-issues#4530]
### Qubes OS version: 4.0
qvm-device and derived commands (qvm-block, qvm-pci, qvm-usb) are very poorly documented and have confusing interfaces.

Starting with the official documentation: https://www.qubes-os.org/doc/tools/4.0/dom0/
There is no documentation. There are two links which both block tor-traffic. Since they are named "manpages", I guess I see the same with "man qvm-block".
First up, I would expect section NAME to list aliases. The way it is currently implemented, I only see "qvm-device" and expect to have made a typo calling man.

Second, the option-handling is not clear at all. (#4119) Especially since device-class isn't used when using qvm-block, -pci, -usb, I'm uncertain where to put options. Furthermore, "options" is used twice for different things. First, [options] is a commandline-option (--verbose, --help, --quiet, ...). Later, " Available options" refers to the device-class-specific options of block and pci. It is not made clear that these are device-class-specific options which require the option "--option". I recommend changing the name of device-specific options to e.g. "--param", or actually allowing them as command-options. (e.g. qvm-block --frontend-dev xvdz ...), complete with shortcuts. (we had -f and -ro for qvm-block in qubes 3.2)

Third, qvm-[block, usb, pci, device] all show the same --help message, which doesn't even mention further options. This is the first place I turn to when I forgot the exact name of an option (e.g. was it "--option" or "--param"?), so the help message should at the very least list valid options.

Fourth, detaching in qubes 3.x needed only the vmname to detach from:

    qvm-block -d work  

which is much less cumbersome than the new way which requires the path:  

    qvm-block d work sys-usb:sda1  

I enjoyed the old syntax a lot more and would request to reenable this behavior.

Fifth, it was briefly mentioned on the dev-mailinglist that qvm-block right now can't attach files but is supposed to regain this capability in the near future, warning users about this behavior in the manpage would be great. Since it has been capable to do that, I'd expect some explanation in the documentation (which apparently is the manpage) as to weather it's still capable. Additionally, a quick example how to use losetup to replicate this behavior (attaching a file to another VM) would be great. #

**Comment by marmarek** [comment]
> I enjoyed the old syntax a lot more and would request to reenable this behavior.

What would you expect to happen if there are multiple devices (for reference: the behavior in R3.2 was to detach all)?

**Comment by GammaSQ** [comment]
Oh! The grey numbers are RAM? I thought they were HDD-space. They are quite hard to read and for a tool I want to use to quickly check usage, readable font would be important. Even better, for me at least, would be bars.

Is there a way to set a color-scheme? I would love to have colorful usage-numbers. (green RAM and blue CPU worked great for me in the old qubes VM manager)

**Comment by GammaSQ** [comment]
Exactly that, detach all!
To dial in and remove just one device if several are connected is a great feature (forcing a user to remove all devices would be a bad idea, no doubt about that!), but always typing the full path nearly doubles the typing-time.

Additionally, it gets specifically cumbersome if the device-VM isn't clear. (e.g. when I use a dispvm to decrypt a drive, I don't remember the 4 random digits, so I have to look the name up before detaching)

P.S.: I believe I don't have the privilege to label this as a UX-issue?

**Comment by andrewdavidwong** [comment]
> P.S.: I believe I don't have the privilege to label this as a UX-issue?

Only certain Qubes team members have the ability to apply labels. This is intentional, since allowing everyone to assign labels would be a disaster.

**Comment by andrewdavidwong** [comment]
> There are two links which both block tor-traffic.

Blocking Tor traffic is bad, but this should be filed as a separate issue.

**Comment by andrewdavidwong** [comment]
I initially labeled this as a doc task, but after reading the issue description again, I realized that "documentation" is probably being used in the general sense that includes tool man pages, as opposed to referring specifically to content that originates in qubes-doc. (The `C: doc` label is usually specific to qubes-doc.) Since I don't see any specific qubes-doc tasks or enhancements mentioned (as opposed to tool man page enhancements) here, I've replaced those labels. (The exception is Tor blocking, as mentioned above.) If it turns out that there's anything actionable for qubes-doc, please file it as a separate issue.

**Comment by GammaSQ** [comment]
This is definitely not (solely) a documentation issue. The `qvm-device` command needs a UX-overhaul. I don't see any structure in when to use commands, options or arguments. Apparently, there are three global options: `--help`. `--verbose`, `--quite`, which can be placed anywhere with the command. (even `qvm-block a work --verbose sys-usb:sda1` is valid)

At the same time, `--all`, `--exclude`, `--options`, `--persistant` are position-specific to be put behind the command? Both start with two dashes, so I'd expect similar behavior.

I don't know what the default behavior is for the list-command. Why does `--all` exist? Are there VMs excluded by default? How would I change that? And why can't I use `--exclude` without `--all`?

The weirdest option?argument?parameter? to me is `--ro`. It's specific to `qvm-block attach`, yet it's an option of `qvm-device attach`? (This, specifically, may be a documentation/manpage issue)

I'm furthermore missing a `--list-device-classes` option. Apparently there is a `mic` device which isn't even mentioned in the manpage. Are there more such devices?

My expectation towards this command are:
 - options behave the same. i.e. everything that starts with double dashes can be placed anywhere within the command (or exclusively at the very end. Even if this isn't enforced, the documentation should suggest that's the way to do it. I'd prefer the first way, though.)
 - especially options to be applied via `--options, -o` are dropped. I believe the additional `-o` is just unnecessary. Just make it plain double-dashed options, with aliases. (e.g. `qvm-block a --frontend-dev xvdz work sys-usb:sda1`)
 - as far as possible, options shouldn't interfere with eachother. Command and device-class may restrict the option set, but `--exclude` shouldn't depend on `--all` and `--ro` vs. `-o readonly=no` shouldn't be an issue.
 - the `qvm-device [CLASS]` syntax shouldn't differ at all from the `qvm-[CLASS]` syntax. Right now, options are supposed to happen before the class: `qvm-device [options] DEVICE_CLASS`
 - `--help` is specific to the specified command. I.e. `qvm-device block attach --help` shows remaining possible options (e.g. possible device classes? ;) ), something like:

        ~]$ qvm-device block attach --help
        qvm-device block attach <target-vm> <source-vm>:<device> [options]
        OPTIONS:
          --help - show this ... [same for --verbose, --quiet]
          --read-only, -ro - attach read-only
          --frontend-dev, -f -specify dev-node
           .... and so on.

_BUT_ I'm no UX-designer. What little I have learned from my UX-colleagues is never to implement the users wishes right away. So please don't see this as a feature request, but rather a list of specific problems, with only vague ideas for solutions. (Not that I'd complain if it were to be implemented exactly like this.)

**Comment by andrewdavidwong** [comment]
> _BUT_ I'm no UX-designer. What little I have learned from my UX-colleagues is never to implement the users wishes right away. So please don't see this as a feature request, but rather a list of specific problems, with only vague ideas for solutions. (Not that I'd complain if it were to be implemented exactly like this.)

I've updated the issue title and labels in an attempt to capture this.

**Comment by marmarek** [comment]
> First up, I would expect section NAME to list aliases. The way it is currently implemented, I only see "qvm-device" and expect to have made a typo calling man.

I though that would be trivial to change, but apparently the man page processor we use (Sphinx) insist on NAME section being the same as actual man filename. Putting "qvm-devices, qvm-block, qvm-pci, qvm-usb" there resulted in a file named `qvm-devices, qvm-block, qvm-pci, qvm-usb.1`. And the same in the man header and footer ("QVM-DEVICE, QVM-BLOCK, ... (1)").
What do you think about keeping NAME as is, but listing aliases explicitly in SYNOPIS section (instead of `qvm-*DEVICE_CLASS*`)?
