### ISSUE TITLE
qvm-run --dispvm "fails" without error

### ISSUE THREAD

**Issue by GammaSQ** [QubesOS/qubes-issues#4533]
### Affected component(s): qvm-run --dispvm

---

### Steps to reproduce the behavior:

A surefire way to recreate this behavior is running a command that doesn't exist in the dvm. However, this sometimes happens with commands I'm certain exist (e.g. firefox in fedora), which I can only guess is too little memory. It was recently mentioned on the mailinglist there should be a "not enough memory"-error message. I have never seen that.

### Expected behavior:

`qvm-run --dispvm [dmv-template] [non-existing-command]` starts dispvm, tries to run non-existing command, fails, prints error-message.(in this cas`bash: [non-existing-command]: command not found`)

`qvm-run --dispvm [dvm-template] [existing-command]` starts dispvm, tries to run the command, doesn't find enough memory and prints an error-message.

### Actual behavior:

These three messages in the upper right corner of the screen (xfce):
"Domain disp... is starting."
"Domain disp.... has started."
"Domain disp... has halted."

**Comment by esote** [comment]
If you pass the IO from that VM to dom0 (use `-p` with `qvm-run`) you will see that it gives a "command not found" error.

**Comment by GammaSQ** [comment]
Yes, a short error message is always helpful if something breaks. Thank you for implementing that!
