### ISSUE TITLE
installation pane is dead or HAP/SLAT/EPT/RVI

### ISSUE THREAD

**Issue by tuso018** [QubesOS/qubes-issues#4535]
with **stable release Qubes-R4.0-x86_64.iso** i got the error "x startup failed, aborting installation ... **PANE IS DEAD**"

i also tried to install the new Release Candidate 4.0.1-rc1, but it did#t work

i use a desktop system with integrated graphics - AMD Ryzen 5 2400G - ASRock B450 Pro4

a community user told me he runs qubes on this configuration smoothely, so i build up the system. he told me later he also had the "pane is dead" problem and fixed it with the thread https://github.com/QubesOS/qubes-issues/issues/3340. (i wrote a comment to the thread but nobody answered for three days so i deleted it and opened this new issue.) 
with "tab" i edited the command line like proposed with different bios settings (legacy/uefi) but it didn#t work. 

![q1](https://user-images.githubusercontent.com/45185453/48923248-42aa2580-eead-11e8-9fdb-e34ef8a5b510.jpg)

![q2](https://user-images.githubusercontent.com/45185453/48923245-3cb44480-eead-11e8-97ab-e912c18c84d6.jpg)

also i edited with the windows program "anyburn" the config-files due to the thread in the iso. i burned a usb stick wit rufus but it wasn´t possible to write with dd. pane is dead was the result again. 

as far as i understand its a graphic card issue and x server is not starting. so i tested with a radeon r7 370 and a AMD FirePro W2100 graphic card. the installer menue loaded on both cards and i could choose the language, but afterwards i got the message "This hardware lacks features required by Qubes OS. Missing features: HAP/SLAT/EPT/RVI. Without these features, Qubes OS will not function normally. " When i reboot the system i got a [dom0] Error "...sys firewall failed... stderr: Start failed:... could not find capabilities for arch=x86_64... " thread https://github.com/QubesOS/qubes-issues/issues/3208 doesn`t help for troubleshooting. when i remove the graphic card and boot with the integrated graphic the system halted with error. 

i also tried to boot with the ssd of my working qubes laptop. but i only got a black screen.

can anyone help (i know only basic linux)?

**Comment by andrewdavidwong** [comment]
Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this does not appear to be suitable for `qubes-issues`. We ask that you please send this to the `qubes-users` [mailing list](https://www.qubes-os.org/support/) instead. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a brief comment explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.
