### ISSUE TITLE
Qubes Domains Widget not readable in every xfce-color-scheme

### ISSUE THREAD

**Issue by GammaSQ** [QubesOS/qubes-issues#4537]
### Affected component(s): Qubes Domains Widget

---

### Steps to reproduce the behavior:

Settings -> Appearance -> Select different Styles and click the blue Q-Icon. Readability changes drastically.

### Expected behavior:

All Styles use easily read color-scheme.

### Actual behavior:

Adawaita, Adawaita-dark, Clearlooks, Crux, Greybird, Industrial, Mist, Murrina-Family, ThinIce, have easily legible colors for RAM-usage.

Albatros, Bluebird, High Contrast [sic!], Raleigh, Xfce-Family (Xfce-basic has transparent widget-background, the RAM-usage looks like two numbers on top of eachother?) have bad to horrible readability. Some are just dark-grey text on light-grey background, others use text-shadows, which can turn out to be especially awful. (some had white shadows for black text.)

### General notes:

I had Xfce-kde2 active and don't remember ever changing that setting. Unless my memory eludes me, the default-setting after installation should be looked at?

---

### Related issues:

#4531

**Comment by marmarta** [comment]
Pretty sure the default setting is Clearlooks :) . To be honest I don't see a way to make colors that are readable under all possible color schemes - and it seems that even XFCE itself does not aspire to it. Even its own tools, like XFCE Power Manager, can be utterly horrible under some color schemes (like Albatross, that basically makes the display brightness part of power manager be unusable).  I don't think this is doable, especially with the huge differences between those Styles..
@andrewdavidwong , @marmarek , do you think we should try to change that?

**Comment by andrewdavidwong** [comment]
> Pretty sure the default setting is Clearlooks :) . To be honest I don't see a way to make colors that are readable under all possible color schemes - and it seems that even XFCE itself does not aspire to it. Even its own tools, like XFCE Power Manager, can be utterly horrible under some color schemes (like Albatross, that basically makes the display brightness part of power manager be unusable). I don't think this is doable, especially with the huge differences between those Styles..
@andrewdavidwong , @marmarek , do you think we should try to change that?

I'm deferring to your judgment about this, @marmarta. Closing as "won't do." If anyone has a new reason for why this should be done, please leave a comment, and we'll be happy to take another look. Thank you.
