### ISSUE TITLE
Qubes Documentation Blocks Tor Traffic

### ISSUE THREAD

**Issue by GammaSQ** [QubesOS/qubes-issues#4538]
### Affected component(s): documentation

---

### Steps to reproduce the behavior:

Use Tor (e.g. by using a whonix-proxy-vm), visit [Qubes Documentation and click "Dom0 Command-Line Tools for Qubes 4.0"](https://www.qubes-os.org/doc/tools/4.0/dom0/) -> Click one of the links.

### Expected behavior:

Documentation loads.

### Actual behavior:

Sometimes I get "CNAME Cross-User Banned | Cloudflare" , "Error 1014" (github for some reason can't process my .png screenshot, sorry.)
It may take some identity- / tor-circuit-refreshing (Ctrl+Shift+L in Torbrowser) to get the actual documentation. 

### General notes:

I don't quite understand why Qubes 4.0 documentation is at all on a different subdomain (dev.qubes-os.org) from general Qubes Documentation? I had no issues with www.qubes-os.org, ever. So maybe just move the documentation there?

---

### Related issues:

issue created after comment from Andrew on [#4530](https://github.com/QubesOS/qubes-issues/issues/4530#issuecomment-441172589)

**Comment by unman** [comment]
@GammaSQ I've never encountered this on the dev site and I use it regularly. Is there anything more here than the usual pains of using Tor and cloudflare? (It isn't a 4.0 documentation issue, I think. The dev site is autogenerated from source code, and clearly has different content and aim from the main site.)

@andrewdavidwong @marmarek  I thought we had Tor exit nodes whitelisted? Or is that only for www.qubes-os.org? Can you extend it to dev site?

**Comment by marmarek** [comment]
> I thought we had Tor exit nodes whitelisted? Or is that only for [www.qubes-os.org](http://www.qubes-os.org)? Can you extend it to dev site?

dev.qubes-os.org is hosted on readthedocs.org (which itself uses cloudflare) thus its configuration is outside of our control...

BTW since github pages support custom domains with https (lets encrypt), www.qubes-os.org does not use cloudflare anymore.

**Comment by GammaSQ** [comment]
> Is there anything more here than the usual pains of using Tor and cloudflare?

No, this pretty much sums up the issue. It's Q4.0 "specific" in the sense that tools for Q3.2 are documented on www.qubes-os.org, Q4.0 tools are not.

> The dev site is autogenerated from source code, [...]

I don't see why autogenerated content can't be hosted on www.qubes-os.org as well. In fact, Q3.2-tools were documented on www.qubes-os.org and [derived](https://www.qubes-os.org/doc/tools/3.2/dom0/qvm-block/) [from](https://www.qubes-os.org/doc/tools/3.2/dom0/qubes-prefs/) [source](https://www.qubes-os.org/doc/tools/3.2/dom0/qvm-backup/) [code](https://www.qubes-os.org/doc/tools/3.2/dom0/qvm-ls/) as well!
Additionally, I just found out the 4.0 DomU-CLI tools are not [documented completely w/o links to further documentation](https://www.qubes-os.org/doc/tools/4.0/domU/).

**Comment by andrewdavidwong** [comment]
> dev.qubes-os.org is hosted on readthedocs.org (which itself uses cloudflare) thus its configuration is outside of our control...
> 
> BTW since github pages support custom domains with https (lets encrypt), www.qubes-os.org does not use cloudflare anymore.

Then this issue is a `not our bug`. Closing.

Anyone should feel free to make a request to readthedocs.org to stop blocking Tor traffic.

> I don't quite understand why Qubes 4.0 documentation is at all on a different subdomain (dev.qubes-os.org) from general Qubes Documentation? I had no issues with www.qubes-os.org, ever. So maybe just move the documentation there?
> 
> I don't see why autogenerated content can't be hosted on www.qubes-os.org as well.

The topic of moving documentation from readthedocs.org to qubes-os.org was covered in #1931. Please feel free to comment there.
