### ISSUE TITLE
Device Widget never existed

### ISSUE THREAD

**Issue by GammaSQ** [QubesOS/qubes-issues#4541]
### Expected behavior:

According to the [documentation](https://www.qubes-os.org/doc/usb/#r40), I should see a "tool tray icon with a yellow square located in the top right of your screen".

### Actual behavior:

It doesn't exist. I do see the disk-space icon, the domains icon, but no devices icon. Plugging in USB-sticks doesn't change that.

### General notes:

I looked through the xfce-settings "Panel" and looked at "Notification Area". There is a list of known applications, consisting of

* Xfce Power Manager
* Devices.py
* Vmapp Command
* Domains.py
* Disk_space.py

All are non-hidden. I wouldn't know what "Vmapp Command" is supposed to be, but I believe I have never seen anything besides the disk_space, domains and power manager in that tray.

Possibly related:
#4397

**Comment by esote** [comment]
In dom0, run and check the output of:
```
$ ps ax | grep "mqui.tray.devices"
 2880 ?        Sl     0:00 python3 -mqui.tray.devices
```
If you do not see that process, then either it hasn't started or crashed.

**Comment by esote** [comment]
What happens if you run `python3 -mqui.tray.devices` (add `&` at the end if you want it to run in the background) in dom0? Does it crash, or start the widget normally?

**Comment by GammaSQ** [comment]
The tray-icon appears!
Plugging in a USB-stick, I see two new devices: the block-device and the USB-device. Thank you, this way I at least can start it.

When running the command, I get the following output:

    (devices.py:11662): Gdk-CRITICAL **: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed

But it doesn't quit or fail, tray-icon is there and working.

**Comment by esote** [comment]
Okay, that's good! That means it likely isn't starting correctly. I suppose you could throw that command in a startup script somewhere. Not sure what other places to check to see why it isn't starting automatically.

**Comment by GammaSQ** [comment]
It disappeared again at some point. My first suspicion was that laptop-sleep killed it, but tried sleeping and waking up a few times and now it survives.

I run QubesOS with "only" 16GB RAM and frequently run into out-of-RAM problems. (i.e. not being able to start another VM.) Though I doubt it, it might be related?

**Comment by esote** [comment]
Next time you run it, do it as such (assuming you're using bash):
```
python3 -mqui.tray.devices >> devices_errors 2>&1 &
```
This will capture the command's output to a file, so next time it crashes you can check the `devices_errors` file.

It may be related to running out of memory and some component of qubes freaks out. If you keep running out of memory, you should decrease the maximum memory of your qubes unless you absolutely need that much for it. Most of mine I only allocate 1-2 GB, some even less.

**Comment by GammaSQ** [comment]
I shouldn't have fixed RAM-issues before dissecting this issue properly. Additionally I've changed laptop in the mean time. The few times I checked back on my old machine the tray icon was properly displayed.

Though I cannot be sure, I'd conclude it was a RAM-related issue. Weirdly enough, my new machine runs on just 8GB, my old had 16GB. So it's not plain lacking memory.

**Comment by marmarta** [comment]
It likely was RAM related, but still, those widgets should restart themselves and now they will ( https://github.com/QubesOS/qubes-desktop-linux-manager/commit/a3cf971c100faf11d79707c5d9d1a67e3a49a43c ), so I'm closing this.
