### ISSUE TITLE
bond/VLAN interfaces in NetVM become disabled after a while

### ISSUE THREAD

**Issue by ghost** [QubesOS/qubes-issues#4545]
### Qubes OS version:

R4

### Affected component(s): 

NetVM components

---

### Steps to reproduce the behavior:

1. Use fedora-29 template or default sys-net
2. Configure a LACP bond with two Ethernet NICs
3. Configure VLAN for the bond
4. Restart (or just leave the sys-net as is) the NetVM

### Expected behavior:

The VLAN interface and bond remain active.

### Actual behavior:

VLAN interface comes online, but as soon as sys-firewall comes up or after a while, the VLAN interface is gone, and the bond is inactive. This forces the user to use single NIC links or WiFi, as is my case.

There are two overlapping icons in the notification area as well (see screenshot).

### General notes:

I'm not quite sure on what is causing this problem, but I can replicate it with a clean NetVM built from a minimal template too, including all the necessary packages (documented and otherwise). 

---

### Related issues:

The NetworkManager icons somehow overlap.

**Comment by andrewdavidwong** [comment]
> There are two overlapping icons in the notification area as well (see screenshot).

> The NetworkManager icons somehow overlap.

Please file this as a separate issue. (I think you forgot to include the screenshot, by the way.)

**Comment by vogelfreiheit** [comment]
I had to leave and a bunch of stuff came up. Here we go:
![Imgur](https://i.imgur.com/Rj5jSkv.png)

Either the Xfce component in the panel in dom0 is converging the icons or something else is happening. This does not happen usually in a fresh install, though. Note that there is no customization done to the templates other than using qubes-builder to grab f29 and its minimal version, and everything else is following the documentation (including the NetVM stuff for minimal templates).

I haven't been able to find the culprit of the bond/vlan interface disconnect problem, but it's fairly annoying. Single NICs work fine, but that means undeploying the LACP LAG at switch level to allow using those interfaces (or running a dedicated cable just for this, which is nonsense -a physical workaround for a software issue-). I will keep looking when I have a chance later.

**Comment by michaelschefczyk** [comment]
I can confirm the issue raised above. I run multiple PCs based on Supermicro motherboards with two 1GBE Intel NICs. They are connected to Netgear switches with 10 GBE uplinks. Some of these PC have their LAN connection based on LCAP bonding (802.3ad). This is no problem with Debian PCs where I set manual network scripts.

In Qubes 4.0.1, I can set up the connection via the GUI in sys-net using the NetworkManger menu including 802.3ad bonding. That does work, but after some reboots (I would guess after every third reboot on average), NetworkManager does autocreate two wired connection leaving everything including bonding unworkable. This can be resolved temporarily by deleting the autocreated wired connections and rebooting. That, however, is very inconvenient and difficult to explain to others. Disabling NetworkManager in the Fedora 29 template VM does not seem to be a very good idea. In addition, Fedora 29 does not have the classic RedHat/Centos/Fedora type network scripts anymore.

Does a known workaround exists which would be worth documenting? Is there a timeline for solving this?

**Comment by andrewdavidwong** [comment]
> Is there a timeline for solving this?

I'm afraid there's no specific timeline for most of our issues. It mainly depends on when the devs can get to it. We do welcome patches, though. :)
