### ISSUE TITLE
Recovering TemplateVM from boot failure caused by incorrect /etc/fstab

### ISSUE THREAD

**Issue by fabioberger** [QubesOS/qubes-issues#4546]
### Qubes OS version:
4.0

I made an accidental edit to `/etc/fstab` which is causing my TemplateVM to timeout on boot with error `Cannot connect to qrexec agent for 60 seconds...`.

Is there a way to edit a particular VM's `etc/fstab` without booting it up? Can I perhaps mount it's root filesystem? 

### Attempted solutions

1. I've tried adding `init=/bin/bash` to the kernel opts, starting the templateVM and then running `sudo xl console TEMPLATE_NAME` from Dom0 but I did not reach a command-prompt before `fstab` was read and executed.

2. I tried mounting the `root` filesystem for the TemplateVM from Dom0 with: `sudo mount /dev/qubes_dom0/vm-fedora-26-root mnt` but got error `wrong fs type, bad option, bad superblock...`

Any suggestions on how I could edit `/etc/fstab` for my TemplateVM before it gets executed?

### Affected component(s): 

- TemplateVM with faulty `/etc/fstub`

---

### Steps to reproduce the behavior:

1. Edit your `/etc/fstab` to be incorrectly formatted
2. Run `qvm-start YOUR_FAULTY_TEMPLATE`

---

### Related issues:

https://unix.stackexchange.com/questions/44027/how-to-fix-boot-failure-due-to-incorrect-fstab

**Comment by andrewdavidwong** [comment]
Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this does not appear to be suitable for `qubes-issues`. We ask that you please send this to the `qubes-users` [mailing list](https://www.qubes-os.org/support/) instead. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a brief comment explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.

**Comment by fabioberger** [comment]
Thanks for the heads up @andrewdavidwong, I've submitted the issue to the mailing list.
