### ISSUE TITLE
Sanitize inputs to various shell scripts

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#4555]
### Qubes OS version:

`Qubes release 4.0 (R4.0)`

### Affected component(s): 

`qubes-dom0-update` in dom0, and presumably various other shell scripts.

---

### Steps to reproduce the behavior:

Pass package names containing spaces

### Expected behavior:

They are rejected as malformed

### Actual behavior:

They are processed incorrectly

### General notes:

Qubes has shell scripts that rely on field splitting by the shell.  These shell scripts should validate their arguments to ensure that they do not contain any characters that would cause problems.

---

**Comment by unman** [comment]
@DemiMarie I dont disagree that the shell scripts *may* need input validation they currently lack, but your prime example doesn't show it at all.

The fedora packaging conventions dont allow for spaces within package names.
`dnf install` accepts a space delimited list of packages.
As far as I can see qubes-dom0-update simply mirrors the behaviour of dnf.

e.g `dnf install gnome terminal` does not "reject as malformed" - how could it? it doesn't know that's supposed to be the name of **one** package, and interprets it as names of two packages. qubes-dom0-update does exactly the same.

Are there any other scripts you can point to that require input sanitization?

**Comment by marmarek** [comment]
@unman I think @DemiMarie had `qubes-dom0-update "gnome terminal"` case in mind - note quoted argument. It will be misinterpreted as two packages, instead of rejected as invalid package name.

**Comment by DemiMarie** [comment]
This specific case has been fixed, leaving the issue as too vague to be actionable.  Closing.
