### ISSUE TITLE
qvm-create sometimes ignores the -l option

### ISSUE THREAD

**Issue by 3hhh** [QubesOS/qubes-issues#4556]
### Qubes OS version:
4.0

### Affected component(s): 

qvm-create

---

### Steps to reproduce the behavior:

in dom0:

```
qvm-create --class AppVM -l blue testapp
qvm-prefs testapp template_for_dispvms true
qvm-create --class DispVM --template testapp -l red d-testapp
qvm-ls d-testapp
```

### Expected behavior:

A red d-testapp is created.

### Actual behavior:

A blue d-testapp is created.

### General notes:

If the color is not explicitly specified, it should be inherited from the template. Otherwise the specified color should be used.

-l works for AppVMs.

---

### Related issues:

Maybe the ones about template inheritance.

**Comment by marmarek** [comment]
I can confirm this. When DispVM is started by some qrexec call (like qvm-open-in-dvm), its label is copied from DVM template. But apparently this code override explicit label specified with `qvm-create -l`.
