### ISSUE TITLE
whonix ws disposable vm selected for backup?

### ISSUE THREAD

**Issue by ThomasWaldmann** [QubesOS/qubes-issues#4564]
qubes 4.0.1-rc1

after a fresh install, the whonix ws disposable vm is selected for including in backups.

somehow does not make sense, does it?

**Comment by marmarek** [comment]
In theory you could make some customization there (like TorBrowser settings), and it would make sense to save it in backup. But I think it (customization, not including it in backup) have negative impact on anonymity.
@adrelanos what do you think?

**Comment by ThomasWaldmann** [comment]
hmm, am i understanding something wrong? i thought if you start a dvm and shut it down again, everything is disposed anyway?

**Comment by marmarek** [comment]
The -dvm qube is [DVM template](https://www.qubes-os.org/doc/glossary/#dvm-template), not DispVM itself.

**Comment by adrelanos** [comment]
Marek Marczykowski-Górecki:
> In theory you could make some customization there (like TorBrowser settings), and it would make sense to save it in backup. But I think it (customization, not including it in backup) have negative impact on anonymity.
> @adrelanos what do you think?
> 

No strong opinion either way.

Customization doesn't add itself without the user doing it. If
customized, the user probably wants default-backup (can still opt out).
And if the user did not customize, in worst case a VM that was never
started got backup. No issue either.

This report was the result of a misunderstanding. I haven't seen any
argument yet in favor of changing the default for whonix-ws-14-dvm to be
included or not included in backups by default.

**Comment by andrewdavidwong** [comment]
Closing as "not an issue." If you believe this is a mistake, please leave a comment, and we'll be happy to take another look. Thank you.
