### ISSUE TITLE
More discoverable qubes manager

### ISSUE THREAD

**Issue by airelemental** [QubesOS/qubes-issues#4566]
### Qubes OS version:

R4.0

### Affected component(s): 

qube manager

---

### Steps to reproduce the behavior:

1. be a new user
2. boot qubes for the first time

### Expected behavior:

Qubes manager is easy to find.

### Actual behavior:

Qubes manager is hidden under qubes menu > System Tools > Qube manager,
alongside dozens of settings entries.

### General notes:

Qubes manager is an easy way for new users to create/open/update VMs.

Please consider adding a menu entry called "Manage Qubes VMs" under "Create Qubes VM".

---

**Comment by marmarta** [comment]
I'm not that sure it is necessary - Create New Qube is up there in the menu, a tool for reminding about vm updates/performing them without pain is in testing (or waiting to be merged), and all the VMs are there in the menu already. The menu is quite cluttered as it is.

**Comment by t4777sd** [comment]
The only way I can see that would make it more discoverable without being annoying is to include a "view all qubes" button in the "Qubes indicator" that shows the list of running qubes in the indicator tray area. 

Maybe putting that with a dashed border at the end of the running Qubes list "View all Qubes"

**Comment by andrewdavidwong** [comment]
What's wrong with autostarting the way it does in 3.2?

**Comment by esote** [comment]
> What's wrong with autostarting the way it does in 3.2?

In my opinion it's annoying to auto-start things by default. I don't need to keep a watch on my VMs, so I would just close it each time. If the user wants it to start automatically they can configure it that way.

**Comment by airelemental** [comment]
It may be two clicks away, but it is not discoverable. A new user who doesn't know a management GUI even exists, won't know to look for it among the items under System Tools.

Automatic start is not a big bother, since it would launch on startup only. And the same people who would want to disable it, are probably past the point where it is useful to them, relying to CLI instead, so would be able to `systemctl disable qubes-manager` or something. As one of these CLI-only users myself, it's a minor inconvenience I'm happy to suffer if it makes Qubes more friendly to new users.

Out-of-the-box, Qubes should default to what's friendly for the new user.

**Comment by esote** [comment]
> Out-of-the-box, Qubes should default to what's friendly for the new user.

Our opinions can differ on what's user-friendly and whether Qubes should be user-friendly--but my view on that would be off topic for this issue I think.

> And the same people who would want to disable it, probably rely on CLI instead, so would be able to `systemctl disable qubes-manager` to disable automatic start forever.

Fair point. You're right, given the nature of the qubes manager, it would be most helpful to the kinds of people who wouldn't know how to enable it and / or find it among the menu.

**Comment by andrewdavidwong** [comment]
Most programs that autostart by default have an option to disable autostarting. Qubes Manager could follow this convention, and folks who don't want it to autostart could simply disable that option the first time it autostarts.

**Comment by manasb** [comment]
I used the Qubes Manager everyday on R3.2. I was surprised to find that it no longer auto-starts on R4.0. I use KDE and I have added it to the Application Dashboard widget which is bound to a global keyboard shortcut. I don't see any option for 'Create New Qube' in the Application Dashboard menu upon a search. I think it is a good idea to have the Qubes Manager auto-start. When using KDE, the Qube-related menu options do not appear to be there and these operations have to be performed through the Qubes Manager.

**Comment by unman** [comment]
>  I don't see any option for 'Create New Qube' in the Application Dashboard menu upon a search. I think it is a good idea to have the Qubes Manager auto-start. When using KDE, the Qube-related menu options do not appear to be there and these operations have to be performed through the Qubes Manager.

"Create Qubes VM" under System Tools in KDE.
Do you not have that @manasb ? It's on every system I've seen.

On the autostart issue, I didnt like Manager, and favoured it's removal. I think it creates a focus on the _how_, rather than the _why_ . I would reverse the order of options from @andrewdavidwong - have an "enable autostart" option when first starting, and make it easy to disable on subsequent use.

**Comment by esote** [comment]
> have an "enable autostart" option when first starting, and make it easy to disable on subsequent use.

Or an option in the installer. That allows novice users to figure out the OS (besides using the widgets, as we decomposed the manager #2132), and for people who don't want it to disable it right away.

**Comment by andrewdavidwong** [comment]
> I would reverse the order of options from @andrewdavidwong - have an "enable autostart" option when first starting, and make it easy to disable on subsequent use.

Reversing the order would makes things slightly easier for veterans but much more difficult for novices. It's easy for a novice to fail to enable autostarting the first time, when everything is new and confusing, then not know how to get Qubes Manager back again.

Autostarting by default with an option to disable is the norm for Windows applications, which is what many of our novice users are accustomed to. With this default, some veterans will be inconvenienced only *once* by having to uncheck a box after a fresh installation, while all novices will be repeatedly saved from "losing" Qubes Manager until they're comfortable enough to disable autostarting. (In fact, many of them will never choose to disable it. I'm a veteran who will happily leave autostart enabled.)

> Or an option in the installer. That allows novice users to figure out the OS (besides using the widgets, as we decomposed the manager #2132), and for people who don't want it to disable it right away.

It depends on what kind of installer option it is. The lazy version would be:

- [ ] Autostart Qubes Manager

But that would be a terrible idea. If it's your first time installing Qubes, you probably won't have any clue what that installer option even means. You've never experienced "Qubes Manager," so how are you supposed to know whether you want it to autostart?

On the other hand, if the option is something like:

- [ ] I'm new to Qubes. Show me around.

Then that could be good (see #1774 and #1395).

**Comment by manasb** [comment]
> > I don't see any option for 'Create New Qube' in the Application Dashboard menu upon a search. I think it is a good idea to have the Qubes Manager auto-start. When using KDE, the Qube-related menu options do not appear to be there and these operations have to be performed through the Qubes Manager.
> 
> "Create Qubes VM" under System Tools in KDE.
> Do you not have that @manasb ? It's on every system I've seen.
> 
> On the autostart issue, I didnt like Manager, and favoured it's removal. I think it creates a focus on the _how_, rather than the _why_ . I would reverse the order of options from @andrewdavidwong - have an "enable autostart" option when first starting, and make it easy to disable on subsequent use.

As I had mentioned in my previous post, I am using the Application Dashboard widget which I have bound to a global keyboard shortcut - this may differ from the usual KDE menu. I don't see any 'System Tools' option to begin with in the menu shown by this widget, but I can find a "Create Qube" link. My workflow has always been through the Qubes Manager, it lets me see which Qubes are running, which ones have updates, which ones need to be restarted for updates to be applied etc. I find it very useful and convenient for any qube-related activity.

**Comment by unman** [comment]
@manasb I have SystemTools on the  Application Dashboard widget.

I dont think we want to revisit the discussions about using the Qube Manager. Many folk use it extensively - some dont. If you come to think that the QM is the right way to do things then you will use it, and decry removal. 
As I've repeatedly said, in my experience, ordinary users very rarely need to use the QM, if at all. ( In the same way that ordinary Windows users need many of the admin plugins or regedit tools. _These_ things aren't autostarted.)

@andrewdavidwong Obviously for this reason I'm not worried about novice users "losing" the QM. However, your post was convincing, and I agree with your proposal for a "Show me around" option.

**Comment by ninavizz** [comment]
Guys—autostarting things is not how to fix poor discoverability. Whether or not something auto-starts, it still needs to be discoverable. For something to be discoverable, it also needs to fit into a user's mental-model of how something works (eg: they need to know they need what to find, to find it)... and users failing to grok Qubes mental models, imho seems like a bigger issue.

Is it expected that all Qubes users will have the innate curiosity like hacker/maker types?

Once I've gotten the proposal I'm working on now, completed, I'd be happy to take a crack at this. It sounds like a broader ecosystem problem, but not rocket science. If in fact it is a broader ecosystem problem and a band-aid fix is sought to address just this one thing asap, that will then likely make other things worse. FWIW.

**Comment by jpouellet** [comment]
Has this been adequately resolved by https://github.com/QubesOS/qubes-issues/issues/4395 / https://github.com/QubesOS/qubes-desktop-linux-manager/commit/60b4a0b6b936be384be894642a019ff8346df0f0, and can be closed now?

/cc @marmarta

**Comment by andrewdavidwong** [comment]
> Has this been adequately resolved by #4395 / [QubesOS/qubes-desktop-linux-manager@60b4a0b](https://github.com/QubesOS/qubes-desktop-linux-manager/commit/60b4a0b6b936be384be894642a019ff8346df0f0), and can be closed now?
> 
> /cc @marmarta

It appears so. However, if anyone believes that further work should be done to make the Qube Manager more discoverable, please leave a comment, and we'll be happy to reopen this.
