### ISSUE TITLE
enigmail / split gpg docs misleading

### ISSUE THREAD

**Issue by ThomasWaldmann** [QubesOS/qubes-issues#4569]
qubes 4.0.1-rc1, thunderbird and enigmail from debian9 (using the debian9 template).

i have split-gpg basically working, i can e.g. invoke `qubes-gpg-client -K` from a terminal and see my key.
i can also list keys, encrypt and decrypt stuff on the cli that way.

but: enigmail doesn't work (even though started from the same terminal).

i verified in /proc/PID/environ of the thunderbird process that `QUBES_GPG_DOMAIN=vault` is in there.

enigmail log complains about not having QUBES_GPG_DOMAIN.

or (in 'About' dialogue): that it can't talk to its core service.

i tried giving `/usr/bin/qubes-gpg-client` and also `/usr/bin/qubes-gpg-client-wrapper` to enigmail as gpg binary, both do not work.

**Comment by marmarek** [comment]
Do you have gpg backend domain set in `/rw/config/gpg-split-domain`?

**Comment by ThomasWaldmann** [comment]
@marmarek thanks, that fixed it.

i skipped that, because it is only mentioned in the qubes 3.2 specific part of the docs:

https://www.qubes-os.org/doc/split-gpg/#qubes-32-specifics

so, it is a docs bug.

**Comment by ThomasWaldmann** [comment]
also, the hint about using the `qubes-gpg-client-wrapper` for enigmail is also in the 3.2 specific part.
enigmail only works with the wrapper, not with qubes-gpg-client.

**Comment by andrewdavidwong** [comment]
The documentation is a community effort. Please help us improve it by submitting a pull request:

https://www.qubes-os.org/doc/doc-guidelines/

**Comment by ThomasWaldmann** [comment]
so, can I assume that this section applies to 3.2 as well as to 4.0?
