### ISSUE TITLE
usb devices tray applet sometimes terminates

### ISSUE THREAD

**Issue by ThomasWaldmann** [QubesOS/qubes-issues#4570]
qubes 4.0.1-rc1

sometimes it just vanishes. maybe in OOM conditions?

would be nice to have some menu entry to get it back.

**Comment by andrewdavidwong** [comment]
Possibly related to: #4541.

**Comment by esote** [comment]
> would be nice to have some menu entry to get it back.

Already a separate issue: #4397.

> maybe in OOM conditions

Likely. That's when it happeneds to me. You can always try to reproduce by consuming lots of memory. Not sure where the logs are sent to by default, though.

**Comment by DemiMarie** [comment]
Could these automatically restart on crash?

**Comment by ThomasWaldmann** [comment]
i did what qubesos-bot said (see previous post), but it doesn't fetch/install any update.
i also tried "dnf clean all", doesn't help.
