### ISSUE TITLE
Dialog boxes do not take keyboard focus in KDE

### ISSUE THREAD

**Issue by unman** [QubesOS/qubes-issues#4577]
### Qubes OS version:

R4.0

### Affected component(s): 

Actions requiring user input in dialog box - e.g qvm-move

---

### Steps to reproduce the behavior:

Download file
Right-click on file and select "move to " or use qvm-move in terminal 

### Expected behavior:

Dialog box will open and one can type in to box

### Actual behavior:

Dialog box opens.
Keyboard focus remains in calling window.
Have to click in to dialog to get keyboard focus.

### General notes:

A minor annoyance

---

**Comment by marmarek** [comment]
See focus stealing prevention setting of window manager. With default settings it works fine.

**Comment by unman** [comment]
And my prevention setting is "Low"

**Comment by tasket** [comment]
@unman You may have to turn it Off, as I have had to at times.

**Comment by tasket** [comment]
BTW, you can try experimenting with KDE Window Rules that allow you to match a regex like `^\[` for any domU window title, and apply focus-related properties on the fly.
