### ISSUE TITLE
Qubesd gets out of sync with libvirt

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#4578]
### Qubes OS version:

`Qubes release 4.0 (R4.0)`

### Affected component(s): 

qubesd

---

### Steps to reproduce the behavior:

Destroy a domain with `xl destroy`, then undefine it with `virsh -c xen:/// undefine`.  I only tested with a DispVM.

### Expected behavior:

Qubesd notices this and cleans up appropriately.

### Actual behavior:

Qubesd is in an inconsistent state: it thinks the domain, and its associated block devices, still exist, but they do not.  Restarting qubesd fails with an uncaught Python exception.  Fixing the problem requires editing `qubes.xml` manually.

### General notes:

The following do not trigger the bug:

* `xl shutdown`
* `virsh -cxen:/// shutdown`
* `virsh -cxen:/// destroy`
* `virsh -cxen:/// undefine` on a running DispVM, followed by shutting down the VM

This makes me think that this is actually a libvirt bug.

---

**Comment by marmarek** [comment]
There is more: `xl destroy` isn't synchronized with libvirt - it still thinks the domain is running. And this is probably the actual cause - even if you `virsh undefine` a "running" domain, libvirt will keep it (until its shut off) and still report it as running. You can restart `libvirtd` service to synchronize the state.

The problem doesn't happen if you `virsh destroy` instead of `xl destroy`. `xl` should be considered a last resort debug utility only. I wonder where would be the best place to put it into documentation - somewhere in "Troubleshooting" section?

**Comment by DemiMarie** [comment]
@marmarek That makes sense.  I tested what you said, and it works.  It does expose bugs in the GUI, but `qubesd` itself is fine.  The GUI bugs are legitimate bugs in Qubes, but this is probably a bug in libvirt.

Perhaps `qubesd` could restart `libvirtd` when either `qubesd` itself is restarted, or libvirt reports an internal error?  In the latter case, I would imagine that `qubesd` should then just retry the operation.

That said, some information is stored in two places: `qubes.xml` and in various libvirt XML files.  One of them needs to be the single source of truth.

**Comment by marmarek** [comment]
libvirt XML files are regenerated from qubes.xml at each VM start, and generally nothing besides libvirt touches them. AFAIR we've tried with transient domains before (that libvirt forgets about it as soon as it's destroyed), but we hit a lot of race conditions and other corner cases.

> or libvirt reports an internal error? In the latter case, I would imagine that `qubesd` should then just retry the operation.

This is terrible idea. This way you'll interrupt all the in-progress actions (starting, stopping other domains etc). Loose all the events - for example if any domain shut off in that time. And probably many more. Libvirt error reporting (specifically - libxl libvirt driver, don't know about others) indeed abuse "internal error" a lot. But very few of those could be "solved" by libvirt daemon restart. In many cases it's some missing file, missing hardware feature (like IOMMU), or such.

**Comment by andrewdavidwong** [comment]
> The problem doesn't happen if you `virsh destroy` instead of `xl destroy`. `xl` should be considered a last resort debug utility only. I wonder where would be the best place to put it into documentation - somewhere in "Troubleshooting" section?

It depends. Who should be using these commands, and under what circumstances?

If someone says, "Hey, I used this arcane Xen command and broke Qubes," I'm inclined to ask, "Well, what did you expect? You probably shouldn't use arcane Xen commands unless you really know what you're doing. You're supposed to use the Qubes commands instead." (Note that this isn't directed toward @DemiMarie who, I assume, is using these commands for testing purposes in order to find areas of improvement for Qubes, which is generally a good thing.)

**Comment by andrewdavidwong** [comment]
Anyway, I don't know whether this reveals an actual bug that we want to fix, or whether the answer is something like, "Just avoid doing that. And if you have to do that for some reason, do it according to this documentation."

I'll label it as a bug for now, but let me know if it should be a documentation or enhancement issue instead.

**Comment by DemiMarie** [comment]
> > The problem doesn't happen if you `virsh destroy` instead of `xl destroy`. `xl` should be considered a last resort debug utility only. I wonder where would be the best place to put it into documentation - somewhere in "Troubleshooting" section?
> 
> It depends. Who should be using these commands, and under what circumstances?
> 
> If someone says, "Hey, I used this arcane Xen command and broke Qubes," I'm inclined to ask, "Well, what did you expect? You probably shouldn't use arcane Xen commands unless you really know what you're doing. You're supposed to use the Qubes commands instead." (Note that this isn't directed toward @DemiMarie who, I assume, is using these commands for testing purposes in order to find areas of improvement for Qubes, which is generally a good thing.)

The real answer is somewhat more embarassing… I was trying to work around #4572 and tried `xl shutdown`.  That worked, so I tried running `xl destroy` on a DispVM and got in this situation.  That said, I have had to forcibly shut down VMs in the past.

> Anyway, I don't know whether this reveals an actual bug that we want to fix, or whether the answer is something like, "Just avoid doing that. And if you have to do that for some reason, do it according to this documentation."

I think the main bug here is that qubesd won’t start if `qubes.xml` gets out of sync with the actual state of the system, and doesn’t provide an way for the user to recover from such a situation.

**Comment by marmarek** [comment]
> I think the main bug here is that qubesd won’t start if `qubes.xml` gets out of sync with the actual state of the system, and doesn’t provide a way for the user to recover from such a situation.

Not `qubes.xml`, but libvirt internal state (not even libvirt xml files). It's libvirt reporting domain as running, while in fact it is not.
But I agree, this sort of problem should not prevent starting `qubesd`.
The actual exception is about failed re-connection to qubesdb-daemon (which isn't running for halted domain). The same thing will probably happen if qubesdb-daemon crashes (but I haven't seen it in practice). I see few options to recover automatically from _this particular situation_:
1. try to restart qubesdb-daemon (and re-fill what is possible, but some data will be lost) - in case of qubesdb-daemon crash it may be the right thing to do, but in this particular case qubesdb-daemon will exit shortly after (but late enough to allow qubesd start to complete, only some further actions related to this domain will fail)
2. only log a warning if qubesdb connection fails,
- then carefully review all the places where qubesdb is accessed (I believe a lot of places do assume qubesdb presence for every running domain); domain lacking qubesdb instance will have slightly limited functionality (for example attaching devices may not work)
3. (try to) kill the domain

The last one could recover from this specific situation, but unfortunately does not in the current libvirt version - destroy operation fails and libvirt thinks the domain is still running. I've also checked that (according to `strace`) libvirt damon does receive notification about domain destroyed with `xl destroy`, so it should be able to synchronized its state... I'll look into it.
But the qubesdb-daemon-not-running problem remains. I'm not really sure which one is the best thing to do. Especially when none of them will fix the actual libvirt issue, but only limit its impact.

**Comment by marmarek** [comment]
As for libvirt issue - discussion here: https://www.redhat.com/archives/libvir-list/2018-December/msg00196.html

**Comment by DemiMarie** [comment]
Testing on my system confirms that this is fixed.

**Comment by DemiMarie** [comment]
It isn’t actually fixed, but now only reproduces intermittently.
