### ISSUE TITLE
Visually indicate unsupported StandaloneVMs (incl. TemplateVMs) in Qubes Manager

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#4581]
@adrelanos [wrote](https://groups.google.com/d/msgid/qubes-devel/66eea35b-20f1-e417-939f-77561ca9d807%40whonix.org):
> Perhaps QVMM could show and visually(!) mark template packages as
> obsolete? This visual mark should be removable after the user upgraded.
> Perhaps a dom0 one time popup with a reminder? Using
> /etc/qubes/post-install.d/ mechanism?
> 
> That would hint users at having to upgrade.
> 

This is a great idea. Users shouldn't have to rely on seeing an announcement from me in order to know that they have to update something. The more of this external communication we can integrate into Qubes in a secure way, the more robust and self-sufficient the system will be.

(This doesn't mean we'll stop publishing announcements the way we currently do. We'd probably continue our current announcements to provide out-of-band verification and for those who want to be notified via email, RSS, or social media on non-Qubes devices.)

Related issue: https://github.com/QubesOS/qubes-issues/issues/3430

**Comment by alimirjamali** [comment]
The patch for #7818 solves this issue in some way. But we could still visually indicate EOL templates in Qube Manager.

@marmarta I appreciate if you could advise on this issue. Is the Updater tray widget notification on EOL templates enough? Or we still want to indicate it in Qubes Manager. I already made a patch (screenshot below).

![qube-manager](https://github.com/QubesOS/qubes-issues/assets/5407317/332b45ee-c1c7-412a-a9a6-980d87e8c06f)

**Comment by marmarta** [comment]
Oh this is a great idea. Reviewing the PR rn.
