### ISSUE TITLE
fedora 27 upgrade documentation issue

### ISSUE THREAD

**Issue by improvethings** [QubesOS/qubes-issues#4595]
### Qubes OS version:

R4.0

### Affected component(s): 

Fedora 26 -> Fedora 27 template 

---

### Steps to reproduce the behavior:

I'm following the steps here: 
https://www.qubes-os.org/doc/template/fedora/upgrade-26-to-27/

This line is causing an error: 
   [user@dom0 ~]$ qvm-block -A fedora-27 dom0:/var/tmp/template-upgrade-cache.img

qvm-block: error: argument command: invalid choice: 'fedora-27' (choose from 'list', 'ls', 'l', 'attach', 'at', 'a', 'detach', 'd', 'dt'')

if I try a instead of -A I get: 

qvm-block: error: backend vm dom0 doesn't expose device '/var/tmp/template-upgrade-cache.img'. 

### General notes:

---

**Comment by improvethings** [comment]
Also worth noting that:
bash: qvm-trim-template: command not found
which is also in the upgrade instructions.

**Comment by andrewdavidwong** [comment]
You're trying to perform the 3.2 instructions on 4.0. Please read the 4.0 section instead.

**Comment by improvethings** [comment]
I would highlight "This is for Qubes 4.0" at the top of the page, and state "Details for older versions at the bottom of this page", and put those instructions at the top. Why cater to old users first? 

It is not intuitive for someone doing an online search to realize that the docs don't have the version in the URL or at the top line in the page, and that Qubes places all versions for one process on the same page with no obvious versioning (in the middle of the discussion I now see there is an option on the right, and a little lower, the last place the English speaking human eye goes when reading.
