### ISSUE TITLE
split-gpg fails to start vault VM (most of the time)

### ISSUE THREAD

**Issue by GammaSQ** [QubesOS/qubes-issues#4596]
### Affected component(s): split gpg

---

### Steps to reproduce the behavior:

Setup: two VMs, vault and relay, had their `/home/user/` directory restored from backup. (duplicity backup, not qubes-backup). vault an relay were setup on their old computer to 
In dom0, `/etc/qubes-rpc/policy/qubes.Gpg` was edited to look like this:

    relay    vault    allow
    $anyvm  $anyvm  ask

### Expected behavior:

When relay requests split-gpg, vault is started and answers that call.
Rarely, this actually works. I'm still not sure weather this is random, but I believe it works when vault had been started already and was shut down again. Still investigating, will report more after my next system shutdown.

### Actual behavior:

Starting thunderbird in relay causes enigmail to complain no gpg-executable could be found, until vault is started manually. Once vault is started, enigmail has no problem.
(enigmail is configured to use `/usr/bin/qubes-gpg-client-wrapper` on both systems.)

### General notes:

Only difference in the VMs I can make out is that my old setup uses fedora-28 VMs, the new setup fedora-29.

On the old system, `/etc/qubes-rpc/policy/qubes.Gpg` read:

    relay    vault    allow
    $anyvm  $anyvm  ask

---

### Related issues:

Possibly, but I doubt it since the VM-boot-order isn't important: https://github.com/QubesOS/qubes-issues/issues/4528

**Comment by GammaSQ** [comment]
If it's in stable, it didn't fix the problem.
Ran `sudo qubes-dom0-update`, installed everything, rebooted -> same problem.
If it's in testing, could you tell me which package to update?

**Comment by marmarek** [comment]
Yes, qubes-gpg-split in the template on which your backend (vault) is based.

**Comment by GammaSQ** [comment]
Updated the VM-template as well (both vault and relay based on fedora-29), didn't work.
running `sudo dnf upgrade qubes-gpg-split --enablerepo=qubes-vm-r4.0-current-testing` says no packages available for update.

Rebooted after installing all the updates, starting relay didn't start vault.

**Comment by unman** [comment]
@GammaSQ  Just to be clear - is this behaviour limited to using Thunderbird? That is, if you start relay and run `qubes-gpg-client -K` does vault start then?
Is it expected that starting relay in itself would start vault, (as your last comment suggests)? I have never seen this. But I dont use Thunderbird.

I have tested using fedora-29 templates on both sides, and the vault(equivalent) starts on a call to qubes-gpg-client in relay.

**Comment by GammaSQ** [comment]
It is.
After a reboot I ran the command you specified and vault started automatically.

The expected behavior is that vault is started the moment thunderbird (not relay itself, sorry for the confusion) is started.

Though it *might* be an issue within thunderbird, it seems weird to me that sometimes vault gets started and sometimes it doesn't. (E.g. navigating to enigmail preferences seems to reliably start vault, while trying to read signed emails most of the time does not.)

**Comment by marmarek** [comment]
The backend qube should be started automatically when some request is directed to it. Whether Thunderbird does that on startup, opening preferences, or opening messages, is a Thunderbird thing. It may cache some results for example to not re-check signatures each time.

I mean, if `vault` is started when it's needed (even if that isn't exactly the moment when Thunderbird is started), then it's fine. But if some operations fails because the backend is not running, then we have a problem here.

So the question for you @GammaSQ : do you see Thunderbird failing some gpg-related action because of `vault` not running?
