### ISSUE TITLE
qvm-ls: Add tree like listing of VMs for use in Genmon plugin or in terminal.

### ISSUE THREAD

**Issue by Rot127** [QubesOS/qubes-issues#4597]
### Qubes OS version:
4.0 up

I wrote a little python script which is using the output of qvm-ls to print a tree like list of VMs (based on the net-vms they are connected to).
 
![gmon_tree](https://user-images.githubusercontent.com/45763064/49740163-8eb9e000-fc8b-11e8-9564-41a1f013fe4a.png)

In my case I use it as a Genmon plugin and formatted the strings in a way Genmon understands. But with a little extra work, it could be implemented in qvm-ls itself.

I think it would make the overview of all VMs much easier to understand. And as a side effect the output of qvm-ls would be Genmon compatible.

If there is any need for this, I could start implementing it.

**Comment by andrewdavidwong** [comment]
Thanks! Please see our guidelines on package contributions here:

https://www.qubes-os.org/doc/package-contributions/

**Comment by Rot127** [comment]
In case someone wants the python script for parsing the qvm-ls output as seen in the picture, find it here:
https://github.com/Rot127/scripts

**Comment by finn0** [comment]
@andrewdavidwong Is anyone working on this issue? I would like to work on this issue.

**Comment by andrewdavidwong** [comment]
@finn0: Please feel free to work on it. Our procedure for package contributions is explained here:

https://www.qubes-os.org/doc/package-contributions/

**Comment by finn0** [comment]
Start working after this week because currently busy in academics work.

**Comment by strikestat** [comment]
I would love to see this feature added again since it got dropped in version 4.
It was quiet a good feature to check if everything is connected where it should be.
Especially with a high amount of different qubes.
