### ISSUE TITLE
Fedora Settings not working

### ISSUE THREAD

**Issue by GWeck** [QubesOS/qubes-issues#4600]
### Qubes OS version:

R3.2, R4.0.1

### Affected component(s): 

Fedora-28, Fedora-29

---

### Steps to reproduce the behavior:

The settings application for VMs based on Fedora-28 (for Qubes R3.2) or Fedora-29 (for Qubes R4.0.1) do not start or not completely start, making it impossible to change the settings for the systems.

### Expected behavior:

The settings application should start when selected from the menu and should display all supported options.

### Actual behavior:

For Fedorsa-28 and Qubes R3.2, the settings application only starts correctly when using the KDE desktop. With the XFCE desktop, only the device pane is shown. For Fedora-29 and Qubes R4.0.1, the application does not start at all, neither for KDE nor for XFCE.

### General notes:

---

### Related issues:

Perhaps this is at least partially caused by Fedora now relying on functions of KDE.

**Comment by marmarek** [comment]
For 4.0, the actual crash looks like this:
```
$ gnome-control-center
**
ERROR:../shell/cc-shell-model.c:458:cc_shell_model_set_panel_visibility: assertion failed: (valid)
Aborted (core dumped)
```

This may be another issue about trying to start some gnome tool without actually running gnome. See #4575

**Comment by tquest1** [comment]
This can be solved by adding
`export XDG_CURRENT_DESKTOP=GNOME`
to the end of .bashrc in the home folder root

**Comment by GWeck** [comment]
I checked this with fedora-28 under Qubes R3.2 and with fedora-29 under Qubes R4.0.1, and it works. For ubuntu, the export has no effect.

**Comment by m4teh** [comment]
Until this problem gets fixed, you can modify **/etc/skel/.bashrc** in the TemplateVM with 

`export XDG_CURRENT_DESKTOP=GNOME`

...and this should persist across new AppVM's. Thanks to tquest1 for this temporary fix.

**Comment by GWeck** [comment]
I checked now for Fedora-29 under Qubes R4.0.1 (final version). The export in /etc/skel causes Settings to work in any appvms created from the template, but not in the template itself. To use settings in the template, the export is also needed in the home directory (not surprising).

**Comment by Elsaesser67** [comment]
Hello I'm new in under Qubes R4.0.1
Can you give me the complete directories of ".bashrc in the home folder root" is it in dom0 ?
Thanks

**Comment by sptankard** [comment]
Hi @Elsaesser67 , there will actually be a bunch of copies of .bashrc on your system: one inside each qube. The one in dom0 is definitely *not* the one you want!

You probably want the `~/.bashrc` file in whichever qube/appvm where you're trying to use GNOME Settings. Maybe that's your `personal` qube, or one you created like `my-logins`.

You *might* also want to change it inside one of your templateVMs (but I'm not sure I would recommend that for someone who's new and learning about Qubes).

BTW: The "GNOME Settings" app is still useful on Qubes, but it's not as useful on Qubes as it is on a normal linux desktop. This is because Qubes doesn't use a full version of GNOME inside each qube. It just uses some parts of GNOME.

**Comment by hexagonrecursion** [comment]
related: https://github.com/QubesOS/qubes-issues/issues/5433

**Comment by GWeck** [comment]
With the new Fedora-31 template available in the current-testing repository (under Qubes R4.0.3), the problem is still there but somewhat worse: Starting the gnome control center from the command menu fails even if the additions to `.bashrc` and to `/etc/skel/.bashrc` are made. Starting it from the console via the command` gnome-control-center`, however, works, if the export is set in `.bashrc`.

If no export was done in `.bashrc`, but the console command is preceded by `XDG_CURRENT_DESKTOP=GNOME`, the control center opens briefly but crashes immediately.

**Comment by GWeck** [comment]
The new Fedora-32 template for R4.0 behaves similarly, with two smal changes: The device tab has been split into several device types, and the crash occurs only for the display type. Furthermore, the start of the gnome control center is very slow - approx. 20 seconds.

**Comment by GWeck** [comment]
R4.1 behaves exactly the same way.

**Comment by GWeck** [comment]
Probably no longer relevant - Fedora 34 and 35 behave correctly.
