### ISSUE TITLE
sys-whonix: whonix_firewall failed to load

### ISSUE THREAD

**Issue by jrsmiley** [QubesOS/qubes-issues#4603]
### Qubes OS version:

4.0 is what /etc/qubes-release reports, although this is actually 4.0.1-rc1 downloaded and installed today after rigorously verifying keys and signatures for authenticity.  This is further verified by the fact that the fresh install uses fedora-29 rather than 26.  

### Affected component(s): 

sys-whonix

---

### Steps to reproduce the behavior:

Fresh install, using defaults and selecting the option to perform updates via Tor (sys-whonix)

### Expected behavior:

System starts as it did under the initial 4.0 release

### Actual behavior:

sys-whonix starts and immediately throws up a message box indicating:
Window title:[sys-whonix] whonicheck | Whonix-Gateway | Unknown Qubes VM Type
"ERROR: whonix_firewall failed to load!
...
whonix-firewall.service- Whonix firewall loader
Loaded: loaded (/lib/systemd/system/whonix-firewall.service: enabled: vendor preset: enabled)
Active: failed (Result: exitcode) since ... 54s ago
Docs: https:...
Proces:393 ExecStart=/usr/lib/whonix-firewall/enable-firewall (code=exited; status=1;/FAILURE)
Main PID: 393 ...

To see this for yourself...

### General notes:

I've scoured the net and your support site looking for any info on this and found nothing.  That tells me no one has installed rc1 and written about it.
I've also re-installed rc1 three times to make sure I wasn't doing something stupid.  The same thing happened every time.  There are other things that are odd as well, such as missing shortcuts and the inability to add them (but one issue at a time, right?)

---

### Related issues:

I see others writing about their rc3 install, so I may try that, but you just announced rc1 on Nov 5, 2018, which is way behind the roadmap date (which needs updating)

I have been asking myself how much more time I'm willing to sink into Qubes and as much as I like playing with new toys, there is a limit.  You seem to have a very small team.  One of your leaders just jumped ship to head up a new OS effort, your docs are way out of date, and you're way behind schedule.  I was most of the way through manually upgrading from Whonix 13 to 14 when I saw the rc1 announcement and figured I could save time by just re-installing using it.  Boy was I wrong!  No one expects a perfect product - especially one as complex as this, but when you combine all of the things I mentioned and then run into a snag like this right off the bat on your latest release, you begin to wonder if your time is being well spent.

**Comment by marmarek** [comment]
Adjusted title to be related the issue.

> 4.0 is what /etc/qubes-release reports, although this is actually 4.0.1-rc1

This is expected. See https://www.qubes-os.org/news/2018/11/05/qubes-401-rc1/#what-is-a-point-release

> Window title:[sys-whonix] whonicheck | Whonix-Gateway | Unknown Qubes VM Type
> "ERROR: whonix_firewall failed to load!

Could you provide the rest of the message? There should be info why it failed to load.
Also "Unknown Qubes VM Type" is worrying. @adrelanos do you have idea why it could happen? Have you seen anything like this?

Normally I'd recommend installing updates (for whonix-gw-14 at least), but if sys-whonix fails to start properly, whonix-gw-14 will fail to update.

There will be 4.0.1-rc2 early next week with a lot of fixes included.

> I see others writing about their rc3 install, so I may try that, but you just announced rc1 on Nov 5, 2018, which is way behind the roadmap date (which needs updating)

I think you have confused 4.0 with 4.0.1.

**Comment by jrsmiley** [comment]
I think this will be legible.  Let me know if it's not and we can find a way to get you something better.

![qubes-4 0 1-rc1_sys-whonix _tartup_error](https://user-images.githubusercontent.com/24857809/49907068-7c75a880-fe29-11e8-86ae-1fafddecacfe.jpg)

**Comment by jrsmiley** [comment]
I can't start a terminal in the instance, so no.

**Comment by jrsmiley** [comment]
The error window appears and then the qube dies.

**Comment by marmarek** [comment]
It looks like some of qubes services crashes in sys-whonix early. One of the reason why qube dies at startup could be qrexec agent failed start. I'd say it looks similar to https://github.com/QubesOS/qubes-issues/issues/4349, but the fix for it is included in the template shipped with 4.0.1-rc1.
Can you take a look at `/var/log/xen/console/guest-sys-whonix.log` and check if there is anything about failed service startup (qubes or other)? In Qube Manager you can right-click on sys-whonix and select the log from "Logs" sub-menu - you'll have an option to copy it to the clipboard.

**Comment by adrelanos** [comment]
Marek Marczykowski-Górecki:
> Also "Unknown Qubes VM Type" is worrying. @adrelanos do you have idea why it could happen? Have you seen anything like this?

Never seen before. By looking at
https://github.com/Whonix/whonixcheck/blob/master/usr/lib/whonixcheck/preparation.bsh
it looks like in case

qubes_vm_persistence="$(qubesdb-read /qubes-vm-persistence)" || true

outputs neither

- full
- rw-only
- none

then it will be set to "Unknown Qubes VM Type".

Are there new values in "qubesdb-read /qubes-vm-persistence" which are
not covered yet? In that case, whonixcheck bug.

Otherwise this is an indicator that qubesdb-read is broken.

**Comment by marmarek** [comment]
> Are there new values in "qubesdb-read /qubes-vm-persistence" which are not covered yet?

No. The only related change is #4007 , but it isn't included in packages shipped with 4.0.1-rc1.

**Comment by jrsmiley** [comment]
Re-filed as new issue #4628 with detailed notes and an observation that the debian template was not installed as a dependency when using the salt-based approach to installing Whonix 14.  Closing this issue since there's much better info in #4628
