### ISSUE TITLE
qubes-run-terminal exits prematurely

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#4606]
### Qubes OS version:

`R4.0`

### Affected component(s): 

Qubes domU agent

---

### Steps to reproduce the behavior:

Try to use `Run Terminal` in a DispVM

### Expected behavior:

The VM does not exit prematurely

### Actual behavior:

The VM does exit prematurely

### General notes:

`gnome-terminal` needs to be passed the `--wait` flag.

---

**Comment by DemiMarie** [comment]
@marmarek I have not tried the others, but I suspect they, too, have similar options.  For those that don’t, we might be able to use cgroups to solve the problem.

**Comment by marmarek** [comment]
The problem with most of such DispVM-incompatible applications (gnome-terminal included) is that actual application is not really a child of the process that starts it. It's started through a dbus and the actual process is child of dbus-daemon running as part of user session. If application doesn't provide specific mechanism to wait for it, or to get the actual process ID, the generic solution is hard to get right. 
Some idea is to observe service presence on dbus (the service name on the bus is included in .desktop file name), but that may be unreliable - for example Nautilus service stays running for some time even after you close the last window. And that's only about applications using "proper" dbus-activation, it doesn't solve the cases where .desktop file has no info about dbus being used. But it may be a good start...

**Comment by DemiMarie** [comment]
Could Qubes kill the VM when the window is closed?

**Comment by marmarek** [comment]
That's also some heuristic, we use similar thing for https://github.com/QubesOS/qubes-app-shutdown-idle (shutdown VM if there is no visible window for 15 minutes). For DispVM case it would need a shorter timeout, but then you may have some application that hide its window to re-open it a moment later (like, restarting firefox after some plugin install). So, it may work for some cases, but may be tricky for others.

**Comment by rustybird** [comment]
`--wait` is a nice find! It's available in gnome-terminal >= 3.27.1 (Fedora >= 28 and Debian >= 10).

Here's a [patch for qubes-run-terminal](https://github.com/rustybird/qubes-core-agent-linux/commit/6f8cbb129d31044135ed35fad180bb56a8ff97be), but it's useless without a fallback for old gnome-terminal versions. Not sure how to write that without making the code ugly and/or adding latency.
