### ISSUE TITLE
Problems with installing Qubes OS on workstation with ASUS Z motherboard 

### ISSUE THREAD

**Issue by justanormalday** [QubesOS/qubes-issues#4607]
### Affected component(s): Installing process (not sure what to write here)

[`/usr/bin/qvm-start/`, sys-firewall`] filed:
stdout: ""
stderr: "Start failed: internal error: libxenlight failed to create new domain `sys-net`, see /var/log/libvirt/libxl/libxl-driver.log for details
"

---

**Comment by andrewdavidwong** [comment]
Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this does not appear to be suitable for `qubes-issues`. We ask that you please send this to the `qubes-users` [mailing list](https://www.qubes-os.org/support/) instead. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a brief comment explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.
