### ISSUE TITLE
Debian template: systemd-modules-load.service failed

### ISSUE THREAD

**Issue by saf323fd** [QubesOS/qubes-issues#4608]
### Qubes OS version:

4.0

### Affected component(s): 

Debian-9 Template

---

### Steps to reproduce the behavior:

In Debian-9 template:
1. Do a dist-upgrade 
    or install **libvchan-xen, xen-utils-common, libxen-4.8** which require removing **libxen-lowlevel1.0**
2. Reboot and `systemctl --failed`

### Expected behavior:

0 failed

### Actual behavior:

```
● qubes-sync-time.service      loaded failed failed Update time from ClockVM    
● systemd-modules-load.service loaded failed failed Load Kernel Modules
```

### General notes:

`systemctl status systemd-modules-load.service`:

```
● systemd-modules-load.service - Load Kernel Modules
   Loaded: loaded (/lib/systemd/system/systemd-modules-load.service; static; vendor preset: enabled)
   Active: failed (Result: exit-code) since Thu 2018-12-13 02:20:07 EST; 3h 41min ago
     Docs: man:systemd-modules-load.service(8)
           man:modules-load.d(5)
  Process: 232 ExecStart=/lib/systemd/systemd-modules-load (code=exited, status=1/FAILURE)
 Main PID: 232 (code=exited, status=1/FAILURE)
```
`journalctl`:
```
Dec 13 02:20:06 localhost systemd-modules-load[232]: Inserted module 'lp'
Dec 13 02:20:06 localhost systemd-modules-load[232]: Inserted module 'ppdev'
Dec 13 02:20:06 localhost systemd-modules-load[232]: Inserted module 'parport_pc'
Dec 13 02:20:06 localhost systemd-modules-load[232]: Inserted module 'xen_evtchn'
Dec 13 02:20:07 localhost systemd-modules-load[232]: Inserted module 'xen_blkback'
Dec 13 02:20:07 localhost systemd-modules-load[232]: Inserted module 'xen_gntalloc'
Dec 13 02:20:07 localhost systemd-modules-load[232]: Inserted module 'xen_gntdev'
Dec 13 02:20:07 localhost systemd-modules-load[232]: Inserted module 'u2mfn'
Dec 13 02:20:07 localhost systemd-modules-load[232]: Inserted module 'xen_netback'
Dec 13 02:20:07 localhost systemd-modules-load[232]: Failed to insert 'xen_pciback': No such device
Dec 13 02:20:07 localhost systemd-modules-load[232]: Failed to find module 'evtchn'
Dec 13 02:20:07 localhost systemd-modules-load[232]: Failed to find module 'gntdev'
Dec 13 02:20:07 localhost systemd-modules-load[232]: Failed to find module 'netbk'
Dec 13 02:20:07 localhost systemd-modules-load[232]: Failed to find module 'blkbk'
Dec 13 02:20:07 localhost systemd-modules-load[232]: Failed to find module 'xen-scsibk'
Dec 13 02:20:07 localhost systemd-modules-load[232]: Failed to find module 'usbbk'
Dec 13 02:20:07 localhost systemd-modules-load[232]: Failed to find module 'pciback'
Dec 13 02:20:07 localhost systemd-modules-load[232]: Failed to insert 'xen_acpi_processor': No such device
Dec 13 02:20:07 localhost systemd-modules-load[232]: Failed to find module 'blktap2'
```

`cat /usr/lib/modules-load.d/xen.conf`:
```
xen-evtchn
xen-gntdev
xen-gntalloc
xen-blkback
xen-netback
xen-pciback
evtchn
gntdev
netbk
blkbk
xen-scsibk
usbbk
pciback
xen-acpi-processor
blktap2
```

---

### Related issues:

https://github.com/QubesOS/qubes-issues/issues/1546 
This is similar but in dom0

**Comment by unman** [comment]
Thanks for the report.
This is in every template, I think, and no dist-upgrade is required.
As far as I can see the package in fedora hasn't been applied to the Debian Template. It's of minor importance, because nothing rests on the failing package, but always better not to see error messages.

**Comment by marmarek** [comment]
The actual cause here is systemd bug - ENOENT and ENODEV should be only warnings not errors in `systemd-modules-load`. It's [fixed](https://github.com/systemd/systemd/pull/9516#pullrequestreview-137412106) in systemd >= 240, but stretch have systemd 239...

I can easily exclude non-existing modules (those are listed there for really old kernels).
The `xen-acpi-processor` case is problematic, because the module exists and should be loaded in dom0. Until our Debian package is for VM only, it isn't a problem.
