### ISSUE TITLE
What is the state if sys-usb is not running?

### ISSUE THREAD

**Issue by paxos1977** [QubesOS/qubes-issues#4609]
### Qubes OS version: R4.0

Perhaps this is a silly question. What is the status of USB support if I have (purposely) disabled sys-usb from running? Are USB devices merely disabled? Or does dom0 pick them up?

**Comment by andrewdavidwong** [comment]
Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this does not appear to be suitable for `qubes-issues`. We ask that you please send this to the `qubes-users` [mailing list](https://www.qubes-os.org/support/) instead. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a brief comment explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.

**Comment by unman** [comment]
On Thu, Dec 13, 2018 at 01:06:47PM -0800, Austin Gilbert wrote:
> ### Qubes OS version: R4.0
> 
> Perhaps this is a silly question. What is the status of USB support if I have (purposely) disabled sys-usb from running? Are USB devices merely disabled? Or does dom0 pick them up?
> 

It's not a silly question.
If you had set up a sys-usb on install, then,(as part of the setup), a
boot parameter is set which hides usb devices from dom0. 
If you now disable sys-usb then the devices do effectively disappear.
They will not appear in dom0.
If you *do* want them in dom0 then remove the "rd.qubes.hide_all_usb"
section from the boot line.
