### ISSUE TITLE
Problems with mouse

### ISSUE THREAD

**Issue by toxub23** [QubesOS/qubes-issues#4615]
### General notes:
For some time I have noticed a problem with the mouse probably caused by the Xen virtualization, so I'm not sure if I should report this bug on the Xen website, but maybe it is related to Qubes. Namely, from time to time my computer mouse connected to the sys-usb spontaneously disconnects and connects. This is not a mouse problem because in another Linux computer (Subgraph OS) it works just as well in Lubuntu. The only thing I noticed in the task manager is terminating "input-proxy-receiver" and then after a few seconds and sometimes after a few seconds, the process is restarted. It is not a security-threatening bug but it can be very annoying.

**Comment by toxub23** [comment]
I know that my problem is not related to security, therefore it is not dramatically serious but currently it makes it difficult to use a laptop. The mouse works one time for few minutes and I am forced to use only the touchpad which is a torment for me. This is a serious system or virtualization bug. An error significantly impeding the use of the system is unacceptable. With such mistakes you can get to the safest system in the world, one that you can not use and do nothing on it, and no one will ever hack into it because there will be nothing for and nobody not use this system :D :D

Any ideas? @marmarek

**Comment by toxub23** [comment]
Will there be a patch for this bug? It may be associated with the IO disk but it's weird and it should be somehow solved, because it makes the USB mouse useless. @marmarek

**Comment by andrewdavidwong** [comment]
> I know that my problem is not related to security, therefore it is not dramatically serious but currently it makes it difficult to use a laptop. The mouse works one time for few minutes and I am forced to use only the touchpad which is a torment for me. This is a serious system or virtualization bug. An error significantly impeding the use of the system is unacceptable. With such mistakes you can get to the safest system in the world, one that you can not use and do nothing on it, and no one will ever hack into it because there will be nothing for and nobody not use this system :D :D

> Will there be a patch for this bug? It may be associated with the IO disk but it's weird and it should be somehow solved, because it makes the USB mouse useless.

https://www.qubes-os.org/doc/reporting-bugs/#there-are-no-guarantees-that-your-issue-will-be-addressed

**Comment by unman** [comment]
@toxub23 This seems extremely localised since I dont recall anyone else complaining of this issue (and surely they would have?)
@andrewdavidwong  is this too localised for qubes-issues?

@toxub23 More information:
What is your setup? What mouse are you using?
Is your touchpad connected to sys-usb?
Have you made any changes to Qubes since install?
Do you see anything in the logs of sys-usb and dom0 that might relate to the disconnecting? Input-proxy-receiver is running in dom0 so look there.
What steps have you taken to troubleshoot the problem?
Does the same issue arise if you use a basic usb mouse?

**Comment by andrewdavidwong** [comment]
> is this too localised for qubes-issues?

Not enough information to tell.

> More information:
> What is your setup? What mouse are you using?
> Is your touchpad connected to sys-usb?
> Have you made any changes to Qubes since install?
> Do you see anything in the logs of sys-usb and dom0 that might relate to the disconnecting? Input-proxy-receiver is running in dom0 so look there.
> What steps have you taken to troubleshoot the problem?
> Does the same issue arise if you use a basic usb mouse?

These are very good questions.

**Comment by toxub23** [comment]
@unman
Unfortunately, this is not a bug only for me because I have already written about GitHub once and one of the users said that it also observed this in the situation of a large number of IO for the disk. So this looks like a bug with virtualization.

At the moment I have Qubes OS R4.0.1 the latest updated today. In addition, today's VM Fedora 29 updates on which the sys-sub is based.

I did not make any changes to the configuration files.

There is absolutely nothing in the logs. Of course, the problem only affects the USB mouse and not the touchpad. The mouse is connected to sys-usb and the touchpad is to dom0.

I have Getac laptop with Intel i5, 6GB RAM, and SSD disc connect by SATA.

My USB mouse is CA Gaming Cheetah CA-1206 but this problem also occurs in the Chinese noname mouse for 10 pln (around 3$).

I see only that process input-proxy was terminnated and after second started again but now often it is started again after for example 5 min.

**Comment by toxub23** [comment]
Anyone could help me with my problem? Currently, the computer mouse is disconnected every few seconds, therefore using it is not possible, only I can use the touchpad.
