### ISSUE TITLE
qubes-dom0-update unnecessary error message

### ISSUE THREAD

**Issue by airelemental** [QubesOS/qubes-issues#4616]
### Qubes OS version:

R4.0 current-testing

### Affected component(s): 

qubes-dom0-update

---

### Steps to reproduce the behavior:

1. `sudo qubes-dom0-update`

### Expected behavior:

```
Using sys-whonix as UpdateVM to download updates for Dom0; this may take some time...
No new updates available
```

### Actual behavior:

```
Using sys-whonix as UpdateVM to download updates for Dom0; this may take some time...
sys-whonix: command failed with code: 1
No new updates available

```

### General notes:

In /usr/bin/qubes-dom0-update:174, it seems like the tar commands produce no stdout/stderr, so `grep -v -E "s in the future"` fails. Since the purpose of this grep seems to be to suppress an innocuous error message, grep's nonzero exit code should not trigger the warning, which could be misinterpreted as something having gone wrong with the update process itself.

---

**Comment by marmarek** [comment]
This is already fixed in [qubes-core-dom0-linux 4.0.17](https://github.com/QubesOS/updates-status/issues/834) - in testing repository right now.

**Comment by airelemental** [comment]
I have qubes-core-dom0-linux-4.0.17-1.fc25.x86_64 installed.

**Comment by HW42** [comment]
To clarify: You also need [core-admin-client 4.0.24](https://github.com/QubesOS/updates-status/issues/838) (currently in testing) to suppress this error message.
