### ISSUE TITLE
Unable to increase AppVM system maximum storage size

### ISSUE THREAD

**Issue by achow101** [QubesOS/qubes-issues#4617]
### Qubes OS version:

R4.0

### Affected component(s): 

dom0, Qube Manager

---

### Steps to reproduce the behavior:

Try to increase the system max storage size in the Qube Manager for an AppVM, the option is greyed out.

Using the command:
```
$ qvm-volume extend qubename:root 20000000000
```

### Expected behavior:

In the Qube Manager, it should be possible to increase the maximum size of the system storage.

With the command, it should not error.

### Actual behavior:

In the Qube Manager, the option is not available.

With the command, I get the following error from the command:
```
Got empty response from qubesd. See journalctl in dom0 for details.
```
Looking at journalctl, I see that this error:
```
Dec 16 01:47:18 dom0 qubesd[2550]: Traceback (most recent call last):
Dec 16 01:47:18 dom0 qubesd[2550]:   File "/usr/lib/python3.5/site-packages/qubes/api/__init__.py", line 266, in respond
Dec 16 01:47:18 dom0 qubesd[2550]:     untrusted_payload=untrusted_payload)
Dec 16 01:47:18 dom0 qubesd[2550]:   File "/usr/lib64/python3.5/asyncio/futures.py", line 381, in __iter__
Dec 16 01:47:18 dom0 qubesd[2550]:     yield self  # This tells Task to wait for completion.
Dec 16 01:47:18 dom0 qubesd[2550]:   File "/usr/lib64/python3.5/asyncio/tasks.py", line 310, in _wakeup
Dec 16 01:47:18 dom0 qubesd[2550]:     future.result()
Dec 16 01:47:18 dom0 qubesd[2550]:   File "/usr/lib64/python3.5/asyncio/futures.py", line 294, in result
Dec 16 01:47:18 dom0 qubesd[2550]:     raise self._exception
Dec 16 01:47:18 dom0 qubesd[2550]:   File "/usr/lib64/python3.5/asyncio/tasks.py", line 240, in _step
Dec 16 01:47:18 dom0 qubesd[2550]:     result = coro.send(None)
Dec 16 01:47:18 dom0 qubesd[2550]:   File "/usr/lib/python3.5/site-packages/qubes/api/admin.py", line 459, in vm_volume_resize
Dec 16 01:47:18 dom0 qubesd[2550]:     yield from self.dest.storage.resize(self.arg, size)
Dec 16 01:47:18 dom0 qubesd[2550]:   File "/usr/lib/python3.5/site-packages/qubes/storage/__init__.py", line 488, in resize
Dec 16 01:47:18 dom0 qubesd[2550]:     yield from ret
Dec 16 01:47:18 dom0 qubesd[2550]:   File "/usr/lib/python3.5/site-packages/qubes/storage/lvm.py", line 283, in wrapper
Dec 16 01:47:18 dom0 qubesd[2550]:     return (yield from method(self, *args, **kwargs))
Dec 16 01:47:18 dom0 qubesd[2550]:   File "/usr/lib/python3.5/site-packages/qubes/storage/lvm.py", line 620, in resize
Dec 16 01:47:18 dom0 qubesd[2550]:     if size < self.size:
Dec 16 01:47:18 dom0 qubesd[2550]: TypeError: unorderable types: int() < str()
```

### General notes:

---

### Related issues:

I think #3143 might be related.

**Comment by unman** [comment]
@achow101 Are you trying to change the system size of a TemplateBasedVM? If I remember right, you cant do this because the system partition is taken from the underlying template. If you want more space there you would need to resize the template.
Can you check this with a StandAloneVM? Because the system partition is not ro, you should find that the resize tools work as you expect.

**Comment by achow101** [comment]
@unman Ah, I see. I am using a template based appvm. I am able to increase the size of the system storage for the TemplateVM itself. However the [documentation](https://www.qubes-os.org/doc/resize-disk-image/) does not mention this, or if it does, it was not clear to me.
