### ISSUE TITLE
QubesPropertyAccessError in Domains Widget

### ISSUE THREAD

**Issue by GammaSQ** [QubesOS/qubes-issues#4618]
### Affected component(s): Application Finder / Domains Widget

---

### Steps to reproduce the behavior:

It happened two times now. First, I thought it was because of a label 'gray' vm (which looks green, different bug). However, it now happened when I tried to start a fedora-29-dvm dispVM.
Alt+F3 opens the Application finder, selecting the appropriate program (gray VM libreoffice writer, second time fedora-29-dvm terminal) and pressing enter.

### Expected behavior:

Program starts

### Actual behavior:

A popup appears, Containing:

> Whoops. A critical error in Domains Widget has occurred. This is most likely a bug in the widget. To restart the widget, run 'qui-domains' in dom0.
> 
> QubesProeprtyAccessError: Failed to access 'label' property
> Traceback [... a lot of traceback]
> File "/usr/lib/python3.5/site-packages/qui/decorators.py", line 53, in icon
>   self.vm.label.icon, 16, 0)
> qubesadmin.exec.QubesPropertyAccessError: Failed to access 'label' property

(Might contain typos, can't select and copy text in the gtk-popup so I had to copy it by hand.)

---

### Related issues:

Though I doubt it, but it first happened with a "gray" VM, so possibly: https://github.com/QubesOS/qubes-issues/issues/3471

**Comment by marmarek** [comment]
Fix on the way: https://github.com/QubesOS/qubes-desktop-linux-manager/pull/37
