### ISSUE TITLE
bind-dirs configured in DVM Template do not mount in DisposableVM

### ISSUE THREAD

**Issue by airelemental** [QubesOS/qubes-issues#4624]
### Qubes OS version:

R4.0 current-testing

### Affected component(s): 

Bind dirs

---

### Steps to reproduce the behavior:

1. In fedora-28-dvm, configure a bind-dir in /rw/config/qubes-bind-dirs/50_user.conf
2. Verify that the bind-dir works in the **dvm template**, by restarting the dvm template, creating a file there, and seeing that it persists.
3. Now start a DisposableVM based on that DVM template and look for that file.

### Expected behavior:

Bind-dir mount point contains file.

### Actual behavior:

Bind-dir mount point lacks file.

### General notes:

`sudo journalctl -b | grep mount-dir` shows the following message in the DisposableVM, but not in the DVM Template:
>  localhost mount-dirs.sh[274]: No TemplateBasedVM detected. Exiting.

Also affects DisposableVMs created using qvm-create --class DispVM.
Very recent issue.

**Comment by marmarek** [comment]
Looks to be a side effect of #4007 fix

**Comment by imjustmatthew** [comment]
The actual line causing the problem dates all the way back to the original bind-dirs implementation in this commit: https://github.com/QubesOS/qubes-core-agent-linux/commit/d55cba0a450501621a27ba5baa251eb8e1cbed3c

That commit references the original implementation discussion at: https://phabricator.whonix.org/T414

It's not clear from that discussion (to me at least) why the "prerequisite" check is present and what it's intended function is. Is it solely trying to detect when we're in the TemplateVM vs the TemplateBasedVM?
