### ISSUE TITLE
qvm-run -q sometimes doesn't suppress output

### ISSUE THREAD

**Issue by 3hhh** [QubesOS/qubes-issues#4633]
### Qubes OS version:

4.x

### Affected component(s): 

qvm-run

---

### Steps to reproduce the behavior:

In dom0:
```
qvm-run -q -p testvm 'exit 33' ; echo $?
```

### Expected behavior:

It should print:
```
33
```

### Actual behavior:

It prints:
```
testvm: command failed with code: 33
33
```

### General notes:

https://github.com/QubesOS/qubes-core-admin-client/commit/954ffc4 recently introduced that error message to stderr whenever a non-zero exit code is returned by a VM.

This currently cannot be suppressed with the `-q` option contrary to Mareks statement in #4533 and thus makes parsing stderr unnecessarily hard.

Moreover this message is rather useless with `-p` involved as with `-p` the exit code equals the VM exit code anyway. On the other hand not adding it under these circumstances may cause future scripts to incorrectly rely on that behaviour and make it possible for an evil VM to write a different message to stderr.

---

### Related issues:

None are directly related.

qvm-run suffers from a bigger problem though:
It was obviously designed for manual command-line usage, but is nowadays also used by bash developers. Without interactive shell however it makes the resulting bash code prone to

1. Qubes OS changes intended for better interactive usage (e.g. the one above)
2. bugs causing potential security issues (default stdin redirection caused by `-p`, uncaptured printing to stderr from compromised VMs, auto-starting VMs, ... )

In general it would be better having a dedicated tool for either usage scenario.

**Comment by marmarek** [comment]
Duplicate of #4616
