### ISSUE TITLE
Starting apps on "named" DispVM fails

### ISSUE THREAD

**Issue by taradiddles** [QubesOS/qubes-issues#4636]
### Qubes OS version:
R4.0, updated with updates-testing

### Affected component(s): 
autogenerated .desktop files ?

---

### Steps to reproduce the behavior:
Create a "named" disposable VM like so: `qvm-create -C DispVM -t fedora-29-dvm -l red dispBrowser`

Try to run an app (eg. xterm) from the menu: nothing happens.

Running the app via command line with `xdg-open ~/.local/share/applications/dispBrowser-xterm.desktop` returns "Got empty response[...] See journalctl[...]".

journalctl shows:

> qubesd[2127]: unhandled exception while calling src=b'dom0' meth=b'admin.vm.CreateDisposable' dest=b'dispBrowser' arg=b'' len(untrusted_payload)=0
> qubesd[2127]: Traceback (most recent call last):
> qubesd[2127]:   File "/usr/lib/python3.5/site-packages/qubes/api/__init__.py", line 266, in respond
> qubesd[2127]:     untrusted_payload=untrusted_payload)
> qubesd[2127]:   File "/usr/lib64/python3.5/asyncio/futures.py", line 381, in __iter__
> qubesd[2127]:     yield self  # This tells Task to wait for completion.
> qubesd[2127]:   File "/usr/lib64/python3.5/asyncio/tasks.py", line 310, in _wakeup
> qubesd[2127]:     future.result()
> qubesd[2127]:   File "/usr/lib64/python3.5/asyncio/futures.py", line 294, in result
> qubesd[2127]:     raise self._exception
> qubesd[2127]:   File "/usr/lib64/python3.5/asyncio/tasks.py", line 240, in _step
> qubesd[2127]:     result = coro.send(None)
> qubesd[2127]:   File "/usr/lib/python3.5/site-packages/qubes/api/admin.py", line 1082, in create_disposable
> qubesd[2127]:     dispvm = yield from qubes.vm.dispvm.DispVM.from_appvm(dispvm_template)
> qubesd[2127]:   File "/usr/lib/python3.5/site-packages/qubes/vm/dispvm.py", line 168, in from_appvm
> qubesd[2127]:     if not appvm.template_for_dispvms:
> qubesd[2127]: AttributeError: 'DispVM' object has no attribute 'template_for_dispvms'
> 

### Expected behavior:

App is started.

### Actual behavior:

qubesd complains that the `template_for_dispvms` vm pref is missing. AFAICT named disposable VMs don't need such pref. Thinking it was maybe a new 4.0.1 thing, I tried to set the property to false but it fails:

~~~
$ qvm-prefs  dispBrowser template_for_dispvms false
usage: qvm-prefs [--verbose] [--quiet] [--help] [--help-properties] [--get]
                 [--set] [--default]
                 VMNAME [PROPERTY] [VALUE]
qvm-prefs: error: no such property: 'template_for_dispvms'
~~~

### General notes:

Until today I had a working setup with such named dispVM and  found out something was broken after updating my templates to fedora-29 and removing/ re-creating the named dispVM.

BTW, starting an app from dom0 works with the following commands:

```
qvm-run dispBrowser xterm
qvm-run -q -a --service -- dispBrowser qubes.StartApp+xterm
```

but fails with the command defined in the related .desktop file (eg. `$HOME/.local/share/applications/dispBrowser-xterm.desktop`):

```
qvm-run -q -a --service --dispvm=dispBrowser -- dispBrowser qubes.StartApp+xterm
```

I don't see how a dispVM can use itself as template - maybe the `--dispvm=dispBrowser` shouldn't be in the exec command line. Unfortunately I don't have a backup of the .desktop files to compare with the previously working setup.

---

**Comment by marmarek** [comment]
> --dispvm=dispBrowser

This option create _new DispVM_ based on a AppVM you specify here. Since `dispBrowser` is already DispVM, you shouldn't use this option. Similarly, do not set `appmenus-dispvm` feature on DispVM itself. Again - it can be set on AppVM to make menu entries create _new DispVM_ each time you start an application.

**Comment by taradiddles** [comment]
> This option create new DispVM based on a AppVM you specify here. Since dispBrowser is already DispVM, you shouldn't use this option.

Sure - that's what I meant by "I don't see how a dispVM can use itself as template ". 

The `--dispvm=` option are in the autogenerated .desktop files - I didn't modify anything.

The thing is, a few months ago (can't recall exactly) I created a named dispVM *exactly* like described in the issue, and everything worked perfectly. Now, after removing and re-creating the VM to use a different template, something doesn't work as before.

> Similarly, do not set appmenus-dispvm feature on DispVM itself.

The `appmenu-dispvm` feature was indeed set for the vm but not by me, so it must have been set automatically during the creation of the VM. But even after unsetting the pref (or setting it to 0) and refreshing the applications (confirmed by looking at the updated .desktop file timestamps), the `--dispvm=` option is still present in the `Exec=` command line in the .desktop files.

**Comment by marmarek** [comment]
Unset the feature with `qvm-features --unset`, then regenerate menu entries with `qvm-sync-appmenus --regenerate-only`.

**Comment by taradiddles** [comment]
> Unset the feature with qvm-features --unset

As written I've tried both: unsetting the pref, and since it wasn't working either, trying to set it to 0.

> regenerate menu entries with `qvm-sync-appmenus --regenerate-only`.

It doesn't help:

Pref is unset: `qvm-features dispBrowser`:

> check-updates      
> updates-available  1

Regenerating menus with `qvm-sync-appmenus --regenerate-only dispBrowser`

> dispBrowser: Creating appmenus

Checking the timestamp of one of the autogenerated .desktop files; this should have been updated to today (Dec 19) but is still from yesterday.
`ll .local/share/applications/dispBrowser-xterm.desktop`

> -rw------- 1 user user 484 Dec 18 20:57 .local/share/applications/dispBrowser-xterm.desktop

Trying to remove the file to see if it's created again when regenerating the menu:

~~~
rm .local/share/applications/dispBrowser-xterm.desktop
qvm-sync-appmenus --regenerate-only dispBrowser
ll .local/share/applications/dispBrowser-xterm.desktop 
~~~

> ls: cannot access '.local/share/applications/dispBrowser-xterm.desktop': No such file or directory

So, no luck.

**Comment by marmarek** [comment]
> Regenerating menus with `qvm-sync-appmenus --regenerate-only dispBrowser`
> 
> > dispBrowser: Creating appmenus
> 
> Checking the timestamp of one of the autogenerated .desktop files; this should have been updated to today (Dec 19) but is still from yesterday.

Ok, so this is likely the core problem here.

In the meantime, try another way of regenerating menu entries: qvm-appmenus --update --force dispBrowser

**Comment by taradiddles** [comment]
`qvm-appmenus --update --force dispBrowser` does recreate the .desktop files but the `--dispvm=` option is still in the Exec= command line of the .desktop files.

the problem seems to be twofold here:
- creating a named disposable VMs automatically adds the `appmenus-dispvm` feature to the VM. (just checked again, this happens for whatever "named" disposable VM that is created with `-C DispVM`).
- even after unsetting the feature, `qvm-appmenus` continues to generate menus as if the feature was still set.

Note: this is not an urgent issue - a simple workaround is to start apps in this VM with `qvm-run vm app` in dom0, or to fix the exec= commands of the .desktop files. But clearly something has changed within the past few months as I didn't experience this problem before.

**Comment by EncryptedGiraffe** [comment]
I've also encountered this in 4.1, both with manually created "named" DispVMs, and the installer-created disposable sys-* VMs.
This also happens when creating DispVMs through the Qube Manager interface

Clicking on their app menu entries, for example the terminal, does nothing.
The .desktop file for (installer-created disposable) sys-net contains:
`qvm-run -q -a --service --dispvm=sys-net -- qubes.StartApp+org.gnome.Terminal`  

Running this in a dom0 terminal gives `Got empty response from qubesd. See journalctl in dom0 for details.`
journalctl reads:
```
qubesd[2632]: AttributeError: 'DispVM' object has no attribute 'template_for_dispvms'
qubesd[2632]: if not appvm.template_for_dispvms:
qubesd[2632]: File "/usr/lib/python3.8/site-packages/qubes/vm/dispvm.py", line 204, in from_appvm
qubesd[2632]: dispvm = yield from qubes.vm.dispvm.DispVM.from_appvm(dispvm_template)
qubesd[2632]: File "/usr/lib/python3.8/site-packages/qubes/api/admin.py", line 1192, in create_disposable
qubesd[2632]: response = yield from self.mgmt.execute(
qubesd[2632]: File "/usr/lib/python3.8/site-packages/qubes/api/__init__.py", line 286, in respond
qubesd[2632]: Traceback (most recent call last):
qubesd[2632]: unhandled exception while calling src=b'dom0' meth=b'admin.vm.CreateDisposable' dest=b'sys-net' arg=b'' len(untrusted_payload)=0
```
Tweaking the command to `qvm-run -q -a --service -- sys-net qubes.StartApp+org.gnome.Terminal` and executing in a dom0 terminal works as expected, starting a terminal in the disposable sys-net.
Changing the Exec command in the .desktop file as well allows the app menu shortcut to work as expected.

Interestingly, the .desktop file for the disposable sys-net includes this command right above Exec like so:
```
X-Qubes-NonDispvmExec=qvm-run -q -a --service -- sys-net qubes.StartApp+org.gnome.Terminal
Exec=qvm-run -q -a --service sys-net -- qubes.StartApp+org.gnome.Terminal
```
The command for `X-Qubes-NonDispvmExec` will correctly start the terminal window, however I can only assume that it isn't being executed in favor of the Exec command, which silently fails.
