### ISSUE TITLE
whonix 14 won't update (stretch not supported anymore?)

### ISSUE THREAD

**Issue by straussmaus** [QubesOS/qubes-issues#4638]
### Qubes OS version:

4.0

### Affected component(s): 

whonix VMs

---

### Steps to reproduce the behavior:

As of today my whonix VMs tell me that debian is out of date.  It says to run update on the whonix-ws-14 template.  Doing this gives me an error about stretch.

### Expected behavior:

Either it should update or the dom0 updater should tell me that Qubes needs to be updated and it will download a new Qubes-ws-15 vm or something.

### Actual behavior:

I get the error and when I try to update whonix-gw-14 it says:

```
The repository 'tor+http://deb.ddddddddddddddddddddd.onion stretch Release' does no longer have a Release file.
N: Upodating from such a repository can't be done securely, and is therefore disabled by default.
```

### General notes:

I don't mind that I have to upgrade things.  I just wish you would document things more so I know what to do.

---

**Comment by unman** [comment]
It is documented. Read [this](https://www.whonix.org/wiki/Qubes/Update) page, specifically the section - "If an error message like this appears."
https://www.whonix.org/wiki/Qubes/Update

That page has details of possible problems and solutions you can try.
Stretch is fully supported.

**Comment by straussmaus** [comment]
@andrewdavidwong I see you closed this.  It is still an unresolved issue.

**Comment by straussmaus** [comment]
@unman The error is more similar to the one later in that and it says that one solution is to run `whonixcheck`.  When I do that it tells me to update.  When I update it gives me the error above.  When I look at the link you send for the part about getting that error above it tells me to run whonixcheck.

On whonix-gw-14:

```
user@host:~$ nslookup security.debian.org
;; connection timed out; no servers could be reached

user@host:~$ 
```

On a whonix VM based on whonix WS (the one I use to connect here now):

```
ser@host:~$ nslookup security.debian.org
Server:         10.139.1.1
Address:        10.139.1.1#53

Non-authoritative answer:
Name:   security.debian.org
Address: 128.61.240.73

user@host:~$ 
```

**Comment by straussmaus** [comment]
@unman using `arm` does not help because the instructions here https://www.whonix.org/wiki/Tor_Controller#Arm tell me to type `arm` and then type `n` but typing `n` does not do anything because the curses menu that comes up when I type `arm` does not recognize `n`.

**Comment by unman** [comment]
@straussmaus Both of these issues (original report, and non-functional arm) look Whonix specific to me. You may get more help over at www.whonix.org.

@adrelanos Do you want to reopen this here or pick it up at whonix support?

**Comment by straussmaus** [comment]
@adrelanos I don't think the problem is with .onion services because during the same update I *can* connect to many other .onion servers.

And it's not a temporary problem.  It's been happening for more than one week.  Are there things you want me to test?

**Comment by straussmaus** [comment]
@adrelanos I think the whonix-gs-14 template that installs by default onto Qubes has an outdated repository.  It is the one that starts with `dds6qkxpwdeu`.

**Comment by straussmaus** [comment]
@adrelanos I looked at the link you posted.  Please see that the error it describes is not the one I have.  (@unman made a similar mistake)

**Comment by andrewdavidwong** [comment]
I run a script overnight each night that repeatedly attempts to update my TemplateVMs via `sys-whonix`, logging each attempt. When I go through logs, I also see this sort of message on many Whonix TemplateVM attempts:

```
The repository 'tor+http://deb.ddddddddddddddddddddd.onion stretch Release' does no longer have a Release file.
```

However, I also see other Whonix TemplateVM upgrade attempts in the same run that go through perfectly normally without any unusual messages. This is all in the same run, so no settings are changing on my machine. It appears to just be randomly bad/unavailable Onion services or exit nodes or some other kind of Tor-related issue. It does not appear to be a Qubes-Whonix bug, since some of the Whonix TemplateVM upgrade attempts are definitely succeeding normally. As far as I can tell, the original link that @unman provided describes the situation accurately:

https://www.whonix.org/wiki/Qubes/Update

**Comment by adrelanos** [comment]
straussmaus:
> @adrelanos I don't think the problem is with .onion services because
during the same update I *can* connect to many other .onion servers.

Not a contradiction. Congestion can hit parts of the network only due to
network topology.

straussmaus:
> @adrelanos I looked at the link you posted.  Please see that the error it describes is not the one I have.  (@unman made a similar mistake)
> 

It may not be the exact same error message but the only answer I can
give remains the same:

Consider onions experimental. You'll get all updates over clearnet anyhow.

**Comment by unman** [comment]
On Fri, Dec 21, 2018 at 08:10:26PM -0800, straussmaus wrote:
> @adrelanos I looked at the link you posted.  Please see that the error it describes is not the one I have.  (@unman made a similar mistake)
> 
You are a tease.
Three people think it IS the same error. Why dont you *say* what the
difference is?

**Comment by straussmaus** [comment]
Beacuse it is just cutting and pasting what is already in this thread and it is better not to repeat.  But if you need it I will do it for you.  Okay.  You said I should go to this page and look at the "If an error like this appears section": https://www.whonix.org/wiki/Qubes/Update

I did that.  In the case that an "error like this appears" I am supposed to change the Tor circuit (done, no change), or run whonixcheck.  Done and the result is that whonixcheck tells me to update the VM.

But when I update the VM I get the error that I originally posted about.  So thank you for your suggestion but you see that I have pointed out clearly that it does not resolve this ongoing Issue.

@andrewdavidwong Thank you for trying to reproduce this Issue.  I understand why you think it is a problem with .onion services but for me the problem is not intermittent.  It is 100% of the time for two weeks HOWEVER I have no problem visiting .onion services from the same VM.  Also there is this new Issue that is similar but does not relate to Tor: https://github.com/QubesOS/qubes-issues/issues/4655

So it just does not seem like a "temporary problem with .onion services."

@unman 

>  You'll get all updates over clearnet anyhow.

What do you mean by this?  I thought I had things set up to accept all updates over Tor.  I do not disagree I just do not understand.

**Comment by adrelanos** [comment]
I see.

- Onions are optional.
- Onions are experimental.
- The experiment failed.
- For now ignore error messages by onions.
- If you want, disable onions to get rid of the error message.
- For foreseeable future: updates without onions required.

- Other onions being functional unfortunately is not a grantee this onion can be functional. Reason: technical reasons. More detailed:
  * Different [Tor entry guards](https://www.whonix.org/wiki/Tor_Entry_Guards).
  * Different routes through the Tor network.
  * onion v2 vs onion v3.
  * [onionbalance not available (yet?) for onion v3.](https://github.com/DonnchaC/onionbalance/issues/69)
  * Perhaps even server issues.

https://forums.whonix.org/t/onion-v3-for-whonix-website-repo-down/5693/14
