### ISSUE TITLE
qubes-builder make gcc fails during linking.

### ISSUE THREAD

**Issue by GammaSQ** [QubesOS/qubes-issues#4641]
### Affected component(s): qubes-builder

---

### Steps to reproduce the behavior:

In Fedora-29 AppVM, follow instructions to download qubes builder, install dependencies, run `make gcc`, build fails:

    Currently installed dependencies:
    python2-pyyaml-4.2-0.1.b4.fc29.x86_64
    createrepo_c-0.11.1-1.fc29.x86_64
    git-2.19.2-1.fc29.x86_64
    perl-Digest-MD5-2.55-417.fc29.x86_64
    perl-Digest-SHA-6.02-4.fc29.x86_64
    python2-sh-1.12.14-6.fc29.noarch
    rpm-build-4.14.2.1-2.fc29.x86_64
    rpmdevtools-8.10-7.fc29.noarch
    wget-1.19.5-5.fc29.x86_64
    make[1]: Entering directory '/home/user/qubes-builder'
    -> Building gcc (gcc.spec) for fc25 dom0 (logfile: build-logs/gcc-dom0-fc25.log)
    
    --> build failed!
    [...... can supply these lines if they are important]
    collect2: error: ld returned 1 exit status
    ../../gcc/ada/gcc-interface/Make-lang.in:601: recipe for target 'gnat1' failed
    make[3]: *** [gnat1] Error 1
    make[3]: Leaving directory '/home/user/rpmbuild/BUILD/gcc-6.4.1-20170727/obj-x86_64-redhat-linux/gcc'
    Makefile:4587: recipe for target 'all-stagefeedback-gcc' failed
    make[2]: *** [all-stagefeedback-gcc] Error 2
    make[2]: Leaving directory '/home/user/rpmbuild/BUILD/gcc-6.4.1-20170727/obj-x86_64-redhat-linux'
    Makefile:24072: recipe for target 'stagefeedback-bubble' failed
    make[1]: *** [stagefeedback-bubble] Error 2
    make[1]: Leaving directory '/home/user/rpmbuild/BUILD/gcc-6.4.1-20170727/obj-x86_64-redhat-linux'
    Makefile:24091: recipe for target 'profiledbootstrap' failed
    make: *** [profiledbootstrap] Error 2
    error: Bad exit status from /var/tmp/rpm-tmp.v7wgap (%build)
    
    
    RPM build errors:
        Bad exit status from /var/tmp/rpm-tmp.v7wgap (%build)
    make[2]: *** [/home/user/qubes-builder/qubes-src/builder-rpm/Makefile-legacy.rpmbuilder:71: dist-package-build] Error 1
    make[2]: Leaving directory '/home/user/qubes-builder'
    make[1]: *** [Makefile.generic:178: packages] Error 1
    make[1]: Leaving directory '/home/user/qubes-builder'
    make: *** [Makefile:229: gcc-dom0] Error 1

### General notes:

I'm wondering mainly wondering how to debug this. According to google, `collect2` complains when there is a linking-error, so it's probably just a missing library. Question is which one?
I couldn't find some kind of `--verbose` option for the make-target. The compiling takes several hours and the output was devoid of any `undefined` or `cannot find` - statements.

---

### Related issues:

Possibly: https://github.com/QubesOS/qubes-issues/issues/418 (simply because `collect2` is complaining there too.)

**Comment by GammaSQ** [comment]
I couldn't find anything in the logs either.
Regarding `USE_QUBES_REPO_VERSION = 4.0`: I try to build the `linux-kernel-dom0`-target. It still fails. But I guess I'll open another issue for that.

Is there a list of required libraries? I know there is a list of [required packages](https://www.qubes-os.org/doc/qubes-builder/), but I wouldn't see any library-/linker-related programs there. Being able to compile from source seems to be a huge security advantage for me.

**Comment by marmarek** [comment]
Nothing specific - the whole build happens in isolated environment (chroot or container depending on builder settings) and actual build dependencies are installed there. The packages listed in documentation are just for the builder itself to setup this environment.

Does the kernel build fails explicitly naming missing gcc, or some other error?

**Comment by GammaSQ** [comment]
> Does the kernel build fails explicitly naming missing gcc, or some other error?
I opened a new issue for the specifics. I'd devote this issue to the linker-error when gcc is built.

**Comment by marmarek** [comment]
No further reports about this issue, I assume it doesn't happen anymore.
