### ISSUE TITLE
qubes-builder linux-kernel-dom0 can't find gcc-package

### ISSUE THREAD

**Issue by GammaSQ** [QubesOS/qubes-issues#4644]
### Affected component(s): qubes-builder

---

### Steps to reproduce the behavior:

install qubes-builder in a fedora-29 vm, edit build.conf to contain

    NO_SIGN=1
    USE_QUBES_REPO_VERSION=4.0

run `make linux-kernel-dom0` in directory.

### Actual behavior:

The making fails with the following error:

    -> Building linux-kernel (kernel.spec) for fc25 dom0 (logfile: build-logs/linux-kernel-dom0-fc25.log)
    --> build failed!
    make[2]: Entering directory '/home/user/qubes-builder'
    /home/user/qubes-builder/qubes-src/builder-rpm//update-local-repo.sh fc25
    14:45:55: posix_spawn avoided (fd close requested) 
    14:45:55: posix_spawn avoided (fd close requested) 
    14:45:55: posix_spawn avoided (fd close requested) 
    14:45:55: posix_spawn avoided (fd close requested) 
    sudo BACKEND_VMM=xen  chroot /home/user/qubes-builder/chroot-fc25 sh -c 'cd /home/user/qubes-src/linux-kernel; dnf  --refresh -y update'
    Last metadata expiration check: 0:00:02 ago on Thu Dec 20 13:46:03 2018.
    Dependencies resolved.
    Nothing to do.
    Complete!
    sudo BACKEND_VMM=xen  chroot /home/user/qubes-builder/chroot-fc25 bash -c 'cd /home/user/qubes-src/linux-kernel; dnf builddep --spec  -y kernel.spec'
    Last metadata expiration check: 0:00:03 ago on Thu Dec 20 13:46:18 2018.
    chmod: cannot access '/root/rpmbuild/SOURCES/guards': No such file or directory
    chmod: cannot access '/root/rpmbuild/SOURCES/apply-patches': No such file or directory
    chmod: cannot access '/root/rpmbuild/SOURCES/check-for-config-changes': No such file or directory
    Package bc-1.06.95-16.fc24.x86_64 is already installed, skipping.
    Package coreutils-8.25-17.fc25.x86_64 is already installed, skipping.
    Package elfutils-libelf-devel-0.169-1.fc25.x86_64 is already installed, skipping.
    No matching package to install: 'gcc >= 6.4.1-1.qubes1'
    Package kmod-23-1.fc25.x86_64 is already installed, skipping.
    No matching package to install: 'qubes-kernel-vm-support'
    Not all dependencies satisfied
    Error: Some packages could not be found.
    make[2]: *** [/home/user/qubes-builder/qubes-src/builder-rpm/Makefile-legacy.rpmbuilder:59: dist-build-dep.spec] Error 1
    make[2]: Leaving directory '/home/user/qubes-builder'
    make[1]: *** [Makefile.generic:178: packages] Error 1
    make[1]: Leaving directory '/home/user/qubes-builder'
    make: *** [Makefile:229: linux-kernel-dom0] Error 1

### General notes:

I can resolve the error message about missing `qubes-kernel-vm-support` by copying `/etc/yum.repos.d/qubes-r4.repo` to the chroot-dir and running

    sudo BACKEND_VMM=xen  chroot /home/user/qubes-builder/chroot-fc25 bash -c 'dnf config-manager --add-repo /qubes-r4.repo'

before building. Mamarek suggested [adding `USE_QUBES_REPO_VERSION=4.0`](https://github.com/QubesOS/qubes-issues/issues/4641#issuecomment-448981121) to the build-config, but it had no effect.

---

### Related issues:

https://github.com/QubesOS/qubes-issues/issues/4641

**Comment by marmarek** [comment]
The `USE_QUBES_REPO_VERSION` is applied when preparing initial environment. You can force it by either cleaning it (`make clean-chroot`) or by forcing make to re-run that step (`touch qubes-src/builder-rpm/prepare-chroot-builder`)

**Comment by GammaSQ** [comment]
That was the problem, building works fine now, thanks!
