### ISSUE TITLE
4.0.1-rc2 Qubes Updater finds no updates after reporting that they are available after sys-whonix has connected to Tor

### ISSUE THREAD

**Issue by jrsmiley** [QubesOS/qubes-issues#4650]
### Qubes OS version:

4.0.1-rc2

### Affected component(s): 

Qubes Updater

---

### Steps to reproduce the behavior:

Hover mouse over gear icon at top right shows "Updates are available"
Left click the gear and select "Launch Updater"
fedora-29 shows that updates are available
Select Next
Open details window

### Expected behavior:

Updates are downloaded and installed

### Actual behavior:

Updater shows "SKIP (nothing to do)"

### General notes:

Either the updater is falsely reporting that  updates are available or the updater is not finding them

---

### Related issues:

https://github.com/QubesOS/qubes-issues/issues/4649

**Comment by jrsmiley** [comment]
Qube Manager shows the "updates available" icon for fedora-29 and was able to apply and install them by selecting the template in QM and launching Update Qube from left-click dropdown.

So Qubes Update app is correctly reporting that updates are available, but doesn't find any when the updater is launched from there.

**Comment by marmarek** [comment]
This is direct result of #2451 (fix on the way).

Also, you've created #4649, this one, #4651, #4652 about the same thing. Please don't.

**Comment by jrsmiley** [comment]
Those look like different problems in Qubes updater to me.  One was about it not waiting for sys-whonix to establish a connection before proceeding with checking for updates.  Another was about QM failing to open a dialog window for dom0 after launching updater from there.  

There appear to be at least two different updaters: 1. the updater app and 2. update qube from QM

**Comment by jrsmiley** [comment]
There was no way I would have associated #2451 with these from the description.

**Comment by jrsmiley** [comment]
I'm just getting started reporting issues with 4.0.1-rc2 as I configure it as a regular use system.  Would you prefer I don't report them since I may not always correctly identify one issue as being related to or the same as another?

**Comment by jrsmiley** [comment]
It would save me a lot of time.

**Comment by jrsmiley** [comment]
I certainly don't create separate issues for things that I see as the same as others.  In other words, if I create duplicate issues, it's because they don't look like the same issue to me.

**Comment by jrsmiley** [comment]
This is not a duplicate of #4649. See my comments there and pls reopen it
