### ISSUE TITLE
 The repository 'http://deb.debian.org/debian stretch Release' does no longer have a Release file.

### ISSUE THREAD

**Issue by straussmaus** [QubesOS/qubes-issues#4655]
### Qubes OS version:

4.0

### Affected component(s): 

debian-9 template

---

### Steps to reproduce the behavior:

As of 24 Dec 2018, try to update debian-9 template.  

- open Qubes Manager
- right-click on debian-9 template
- choose update
- allow VM to run
- watch xterm messages

### Expected behavior:

Template should apt-get update and upgrade VM

### Actual behavior:

During the apt-get update I see this error:

```
E: The repository 'http://deb.debian.org/debian stretch Release' does no longer have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default
```

Options are to close the template or just the window.

### General notes:

Also see this issue?  Error messages are the same: https://github.com/QubesOS/qubes-issues/issues/4638

---

**Comment by andrewdavidwong** [comment]
I'm guessing it's for the same general reason as discussed in #4638. Might be an upstream Debian issue (perhaps even just a documentation issue, if they don't already have this documented).

**Comment by unman** [comment]
@andrewdavidwong In the absence of any reply, the fact that the build completes successfully, and for the reasons I give, can you close this issue please.

**Comment by desci** [comment]
I'm getting this error on Debian 9 templates either via the qubes updater or via `sudo apt update` within the TemplateVM.

So I open https://deb.debian.org in a browser and I noticed this:

> The server deb.debian.org does not have packages itself, but the name has SRV records in DNS that let apt in stretch and later find places.
>
> To use it with a sufficiently recent apt, you for instance can put
> 
> deb http://deb.debian.org/debian unstable main
> deb http://deb.debian.org/debian-debug unstable-debug main
> deb http://deb.debian.org/debian-ports unstable main
> 
> in your sources.list.
> 
> As of October 2016 the SRV record is
> 
> _http._tcp.deb.debian.org.	IN	SRV	10 1 80 prod.debian.map.fastly.net.
> _http._tcp.deb.debian.org.	IN	SRV	10 1 80 dpvctowv9b08b.cloudfront.net.
> 
> If you hit the server behind deb.debian.org directly, either because you use an older apt or because you use a HTTP proxy that does not support SRV records, your requests will get HTTP redirected to one of the CDN instances. If you want to avoid the redirects, you can pick one instance directly. For instance, this also works in your sources.list:
> 
> deb http://cdn-fastly.deb.debian.org/debian stable main
> deb http://cdn-fastly.deb.debian.org/debian-security stable/updates main
> 
> The redirection service is also available on HTTPS, so with the apt-transport-https package installed, you can use:
> 
> deb https://deb.debian.org/debian stable main
> deb https://deb.debian.org/debian-security stable/updates main

Perhaps could we get random network errors because of that?

**Comment by marmarek** [comment]
Can you check `journalctl` for qrexec entries about `qubes.UpdatesProxy` calls? Maybe it's missconfigured and calls are rejected or redirected to a wrong place?
Details: https://www.qubes-os.org/doc/software-update-domu/#updates-proxy

**Comment by straussmaus** [comment]
@marmarek I am not having the problem now so I can't test but I will do this next time I have the problem.

**Comment by straussmaus** [comment]
I am closing this issue.  I have not had the problem recur in more than one year.  I will assume the problem was connecting over Tor for updates as @unman says.
