### ISSUE TITLE
USB device connected with qvm-usb cause problems on suspend

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#4657]
### Qubes OS version:

R4.0

### Affected component(s): 

usb-proxy

---

### Steps to reproduce the behavior:

1. Use qvm-usb to assign device from sys-usb to sys-net (like 3G modem).
2. Try to suspend the system

### Expected behavior:

System suspend successfully.

### Actual behavior:

A long timeout (~60sec) after which system seemingly suspend. But after resume, sys-usb is not working and in some cases sys-net neither.

### General notes:

I think it depends on suspend order - if one end of qvm-usb connection is suspended before the other, that other fails to suspend.

One solution would be to detach all such devices before suspend. It may be enough to force those USB devices suspend in appropriate order.

**Comment by andrewdavidwong** [comment]
> A long timeout (~60sec) after which system seemingly suspend. But after resume, sys-usb is not working and in some cases sys-net neither.

I'm confused. The issue title and most of the description imply that the machine is prevented from suspending, but the phrase "after resume" implies that it actually did suspend, otherwise there would be nothing to "resume" from.

If the machine actually does suspend, then this seems very similar to #4042.

> and in some cases sys-net neither.

Branched to #4658.

**Comment by marmarek** [comment]
> If the machine actually does suspend, then this seems very similar to #4042.

Indeed it looks similar, but I think it's still different. This is specifically caused by qvm-usb, #4042 looks to be independent of qvm-usb.
