### ISSUE TITLE
yum.qubes-os.org certificate expired

### ISSUE THREAD

**Issue by Summertime** [QubesOS/qubes-issues#4659]
### Qubes OS version:
4.0
### Affected component(s): 
updatin' n' stuff

---

### Steps to reproduce the behavior:
`sudo dnf update -v`

### Expected behavior:
to receive the latest and greatest updates from the fedora software ecosystem along with specially tailored packages to increase synergy with the qubes os framework

### Actual behavior:
```
[user@fedora-28-gaming ~]$ sudo dnf update -vvv -d 9999 --rpmverbosity debug
[...]
DNF version: 2.7.5
[...]
Cannot download 'https://yum.qubes-os.org/r4.0/current/vm/fc28': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried.
Error: Failed to synchronize cache for repo 'qubes-vm-r4.0-current'
```
and trying to browse the yum site shows that it is probably expired

### General notes:

---

**Comment by Rspigler** [comment]
Experiencing the same issues on my end.

Also for qubes-dom0-current and qubes-templates-itl

**Comment by marmarek** [comment]
Fixed (http server reload failed).
