### ISSUE TITLE
Add qubes version to boot menu (grub)

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#4663]
Make it easier to distinguish different installations (for example USB sticks).

**Comment by alimirjamali** [comment]
There is already a grub2-tools trigger in [core-dom0-linux.spec.in](https://github.com/QubesOS/qubes-core-admin-linux/blob/main/rpm_spec/core-dom0-linux.spec.in#L264-L266)

Adding modifications to `/etc/default/grub` or even `/etc/grub.d/20_linux_xen` to use something different than `"$(sed 's, release .*$,,g' /etc/system-release)"` for `GRUB_DISTRIBUTOR` should be doable. Even removing the `with Xen hypervisor` is an option.
