### ISSUE TITLE
Cant interact with fedora-29-minimal

### ISSUE THREAD

**Issue by unman** [QubesOS/qubes-issues#4671]
### Qubes OS version:

R4.0

### Affected component(s): 

fedora-29-minimal template

---

### Steps to reproduce the behavior:

Install fedora-29-minimal (201812151700) from testing
Start template.
Attempt to run any command, including `qvm-run -p `

### Expected behavior:

Able to interact with template

### Actual behavior:

Cannot run any commands, `qvm-run -p -u root passwd` simply hangs, as does any other attempt to use `qvm-run -p `

### General notes:

`sudo xl console` gets to a login prompt, but because passwordless root is not installed, cannot log in,

There's undoubtedly something I'm missing here.

---

**Comment by 0spinboson** [comment]
so -qvm-run -u root fedora-29-minimal xterm' doesn't do anything at all?

**Comment by unman** [comment]
On Sun, Dec 30, 2018 at 08:43:06AM -0800, Foppe wrote:
> so -qvm-run -u root fedora-29-minimal xterm' doesn't do anything at all?
> 
no

**Comment by 0spinboson** [comment]
I am seeing same behavior.

**Comment by 0spinboson** [comment]
update: I can get it to accept-run 1 qvm-run command per boot cycle (i.e., if I run this commend with the template disabled, it will start the vm and execute it). So qvm-run -u root -p fedora-29-minimal 'dnf install qubes-core-agent-passwordless-root polkit -y' will install those packages, after which you can xl console around. No idea what's up with the rest though.. no gui forwarding?

**Comment by marmarek** [comment]
The problem: missing e2fsprogs, so /rw cannot be prepared.
quick workaround: `qvm-run -u root --no-gui -p fedora-29-minimal 'dnf install -y e2fsprogs'`
