### ISSUE TITLE
Change to how xinit is invoked causes .bash_profile (QUBES_GPG_AUTOACCEPT overrides, etc) to be ignored

### ISSUE THREAD

**Issue by mig5** [QubesOS/qubes-issues#4673]
### Qubes OS version:

R4.0

### Affected component(s): 

qubes-gui-agent version 4.0.19-1+deb9u1

### Steps to reproduce the behavior:

Use a GPG vault VM based on Debian.

Override the `QUBES_GPG_AUTOACCEPT` variable from its default 300 in ~/.bash_profile as per the documentation.

### Expected behavior:

The override of `QUBES_GPG_AUTOACCEPT` should be respected by the qubes-gpg-client tools.

You should also be able to see the overrided value in a terminal with `echo $QUBES_GPG_AUTOACCEPT`

### Actual behavior:

The `QUBES_GPG_AUTOACCEPT` overridden value is ignored, and the default 300 is used.

The output of `echo $QUBES_GPG_AUTOACCEPT` is null.

### General notes:

This was caused by recent updates to qubes-gui-agent packages, specifically this merge https://github.com/QubesOS/qubes-gui-agent-linux/commit/130865253fe03d37cdec17c8fabdae6bbcca1354, which changed the invocation of xinit at startup to use `/bin/sh`, which happens to be `dash` on Debian. 

In dash, the `.bash_profile` file (and other such bash config files) are ignored, meaning that any user overrides such as `QUBES_GPG_AUTOACCEPT` were ignored when the x startup scripts (gpg agent etc) are started.

A fix is at https://github.com/QubesOS/qubes-gui-agent-linux/pull/60 (forces  /bin/bash). 

I was unsure if the convention when making PRs is to also file an issue here for 'completeness'. If nothing else, it might help other users who've noticed their `QUBES_GPG_AUTOACCEPT` has stopped working since the last qubes-gui-agent package updates (from around the 18th December?). If not necessary, feel free to close this.

**Comment by andrewdavidwong** [comment]
> I was unsure if the convention when making PRs is to also file an issue here for 'completeness'. If nothing else, it might help other users who've noticed their `QUBES_GPG_AUTOACCEPT` has stopped working since the last qubes-gui-agent package updates (from around the 18th December?). If not necessary, feel free to close this.

Yes, this is good practice. Thank you!

**Comment by unman** [comment]
The instructions are only an example. Rather than forcing bash, wouldn't it be better to change the documentation to show exporting the variable in ~/.profile? That covers both bash and dash.

**Comment by mig5** [comment]
> The instructions are only an example. Rather than forcing bash, wouldn't it be better to change the documentation to show exporting the variable in ~/.profile? That covers both bash and dash.

That is certainly the other option, and maybe 'better', at least for new users who have not set up Split GPG already.

But for users who have already set it up according to the docs, there is no way around the fact that this is an introduced regression. To me it is better to fix the regression caused by software, with software, rather than asking those users to go and change their setup according to a doc change. Probably a contentious discussion: by all means do whatever is easiest or makes most sense.

**Comment by mig5** [comment]
I'll make a documentation PR at some stage instead.

**Comment by anadahz** [comment]
Should this issue remain open until it's fixed?

I bet it affects a lot of users that consulted Qubes documentation to install and configure split gpg.

**Comment by andrewdavidwong** [comment]
Reopening as a doc task.
