### ISSUE TITLE
Qubes Update widget gives a green check even when the update resulted in an error

### ISSUE THREAD

**Issue by rsip22** [QubesOS/qubes-issues#4674]
### Qubes OS version: R4.0

After running the updater, the result is always a green check afterwards, no matter whether the update was successful or not. I find that this can cause confusion, by giving the user the wrong impression that the updates were installed successfully even when that is not the case. 

Suggestion: the green checker should be changed to something else (maybe a "red X"?) if the update is not completed successfully. A message to check the "details" would be helpful, too, since this is not visible by default, unless you click on it.

Steps to reproduce:
1. Launch the updater from the dropdown menu.
2. Chose a VM to update, but make sure you can't update it (for instance, lacking the internet connection)
3. Wait for the result and see the green "checked" mark next to the VM name.

![update-gui](https://user-images.githubusercontent.com/16676222/50566230-653a2480-0d1e-11e9-986f-2f308c62da94.png)

**Comment by marmarta** [comment]
This should have been fixed by https://github.com/QubesOS/qubes-mgmt-salt/commit/10c923f841d508fb6bd125502ad8e6d649c848d8 .
