### ISSUE TITLE
qubes-gpg-key-import opens dom0 conformation window

### ISSUE THREAD

**Issue by GammaSQ** [QubesOS/qubes-issues#4675]
### Affected component(s): qubes-gpg-import-key

---

### Steps to reproduce the behavior:

In a VM setup for split-gpg according to documentation, start a terminal. (both client and vault vm are based on fedora-29 template)
start `qubes-gpg-import-key`

### Expected behavior:

command executes, maybe with a vault-popup asking to allow client-vm access for the next X seconds. (Unless that appeared before and timeout hasn't run out yet)

### Actual behavior:

dom0-window appears with the text:

> **Operation execution**
> 
> Do you want to allow the following operation?
> Select the target domain and confirm with 'OK'.
> Source: [clientVM]
> Operation: qubes.**GpgImportKey**
> Target: [empty]

---

### Related issues:

I recently had another weird split-gpg-issue: https://github.com/QubesOS/qubes-issues/issues/4596
Other than the short succession I don't see a connection, though.

**Comment by andrewdavidwong** [comment]
This looks like normal, expected behavior if your policy requires approval for `qubes.GpgImportKey` for that combination of VMs. Could you clarify what the perceived bug is?

**Comment by GammaSQ** [comment]
I perceive this as bug because it never happened before. The content of `/etc/qubes-rpc/policy/qubes.Gpg` is set to allow any request from [client] to vault. I never touched `.../policy/qubes.GpgImportKey` and was never asked to approve the import before.

Rereading the documentation, apparently it _should_ open a popup, so maybe the bug is rather that it never appeared, across several (physical) systems and installations.

**Comment by GammaSQ** [comment]
On a friends machine, the window appears as well, so it appears the bug is rather that the window didn't appear before.

I'm not sure how to handle this issue now. Since the window appears on my current machine and the old one is gone, I can't reproduce an import without a window appearing.

Anyway, closing, not a bug.
