### ISSUE TITLE
Backup Qubes: Critical error has occured...

### ISSUE THREAD

**Issue by umbratic** [QubesOS/qubes-issues#4677]
### Qubes OS version:

R4.0

### Affected component(s): 

dom0, Backup Qubes

---

### Steps to reproduce the behavior:

Run `Backup Qubes` from `System Tools`

### Expected behavior:

No error

### Actual behavior:

After clicking `Finish`, the following error is displayed: `[Dom0] Houston, we have a problem..`
`Whoops. A critical error has occured. (...)`
`RuntimeError: Event loop stopped before Future completed.at line 286 of file __init__.py.` 

### General notes:

---

**Comment by xftroxgpx** [comment]
I think I got this if I pressed Cancel(or I don't remember the exact button to just try and exit the dialogs), before even starting the process. Can you try it?

**Comment by mfc** [comment]
I confirm encountering this same exact issue and error message. When running `qvm-backup` from command line, Qubes cold reboots instead of this error message. This happens around the same time for me, when the backup is around 40% complete or so.

**Comment by marmarek** [comment]
> When running `qvm-backup` from command line, Qubes cold reboots instead of this error message.

This looks like a different issue.

@mfc can you confirm when you get `RuntimeError: Event loop stopped before Future completed` message? After complete backup (pressing Finish), or before?

**Comment by constantoverride** [comment]
I do just start `Backup Qubes`(aka `qubes-backup`) then press `Cancel`, resulting in the Houston window
![hustonscreenshot_2019-01-09_12-18-02](https://user-images.githubusercontent.com/40925413/50896227-b7f39a80-1408-11e9-859b-139ade04c1bd.png)

**Comment by mfc** [comment]
> @mfc can you confirm when you get `RuntimeError: Event loop stopped before Future completed` message? After complete backup (pressing Finish), or before?

yes as i mentioned i can confirm getting that exact same message. it happens in the middle of the backup (at around 40%) - the backup process "completes" to 100% and presents the Finish button to select but the backup file itself is only ~40% the size of what it should be. i don't remember if the error only appears upon selecting Finish or is already appearing, in the next days i will run again to confirm.

>> When running qvm-backup from command line, Qubes cold reboots instead of this error message.

> This looks like a different issue.

yes this may be different issue, i haven't run it again to confirm.
