### ISSUE TITLE
VM name containing "-root" breaks qubes manager

### ISSUE THREAD

**Issue by duxovni** [QubesOS/qubes-issues#4680]
### Qubes OS version:

R4.0

### Affected component(s): 

qubes-manager, various other qvm tools

---

### Steps to reproduce the behavior:

- Create an appVM called `foo`
- Create an appVM called `foo-root`
- Try to start qubes-manager

### Expected behavior:

Either creating a VM with "-root" in its name fails with an error message about reserved keywords, or qubes-manager starts normally

### Actual behavior:

qubes-manager fails to start because qubesd returns an empty response

### General notes:

From what I can tell, this happens because in order to process some data about VM `foo`, a method in the qubes API searches for an LVM volume called `vm-foo-root-[number]-back` and tries to parse that number. If a VM called `foo-root` also exists, then there's an LVM volume called `vm-foo-root-private-[number]-back`, and the method winds up trying and failing to parse `private` as an integer.

It should either be impossible to create (or restore from backups) a VM with "-private" or "-root" in its name, or the code that parses these LVM volume names should be able to notice and avoid these cases.

---

**Comment by marmarek** [comment]
Generally I agree, but that's not something we can do easily in the stable release. In the meantime I fixed parsing code (see commit linked above).
