### ISSUE TITLE
Socket-based qrexec

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#4686]
### Qubes OS version:

`R4.0`

### Affected component(s): 

domU qrexec

---

### Steps to reproduce the behavior:

Find oneself writing qrexec services that just call `socat` or `ncat` to connect to an `AF_UNIX` socket.

### Expected behavior:

Qrexec services can either be executable files or Unix sockets.

### Actual behavior:

Only executable files are supported.

### General notes:

This is only a small benefit, but also only a small risk.

---

**Comment by marmarek** [comment]
This looks very similar to #3912 you created some months ago. Can you explain the difference, or close this one?

**Comment by DemiMarie** [comment]
Duplicate of #3912.
