### ISSUE TITLE
Provide a documented way to mount the image of a powered-off VM in another VM

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#4687]
### Qubes OS version:

`Qubes release 4.0 (R4.0)`

### Affected component(s): 

dom0 admin tools, probably

---

### Steps to reproduce the behavior:

Have a TemplateVM that won’t boot

### Expected behavior:

I can mount the TemplateVM’s filesystem in a (trusted) DispVM, and then apply standard troubleshooting practices.

### Actual behavior:

No documented way to do this.

### General notes:

---

**Comment by DemiMarie** [comment]
I suspect that this can be done manually using `qvm-block` (with no loss of security if done correctly).  Is this possible?

**Comment by airelemental** [comment]
To pass debian-9 root image into destvm:
```
qvm-clone debian-9 debian-9-tmp     # for safety
qvm-block attach -o frontend-dev=xvdr destvm dom0:"$(readlink /dev/mapper/qubes_dom0-vm--debian--9--tmp--root)"
qvm-run -u root destvm "mkdir -p /mnt/root && mount /dev/xvdr /mnt/root"
```
Have not tested this...!

**Comment by taradiddles** [comment]
@marmarek : I'd suggest simply adding instructions to the docs. Attaching volumes is only a part of the problem, dealing with the volume in the target VM (eg. finding out if the volume has partitions, mounting, possibly troubleshooting, ...) is for advanced users who won't have a problem typing 2-3 commands in dom0 (@airelemental was on the right way, see ML posts [here](https://groups.google.com/d/msg/qubes-users/RYSrJksz5Mg/3StAHRohCAAJ
) and [here](https://groups.google.com/d/msg/qubes-users/qvagsGbhPd4/b-1OmOdZAgAJ)).
Also  IMHO making it easy to attach volumes increases chances of bad opsec.

**Comment by neowutran** [comment]
Maybe the issue could be closed since the doc have been added ? https://www.qubes-os.org/doc/mount-lvm-image/

**Comment by donob4n** [comment]
Another similar way for doing this on btrfs?

**Comment by rustybird** [comment]
> Another similar way for doing this on btrfs?

Setup:

    dev=$(basename $(sudo losetup -f --show /var/lib/qubes/vm-templates/debian-9-tmp/root.img))
    qubesdb-write /qubes-block-devices/$dev/desc "debian-9-tmp root"  # same as LVM


Cleanup:

    qubesdb-rm /qubes-block-devices/$dev/  # same as LVM
    sudo losetup -d /dev/$dev

This should work with both `file-reflink` and legacy `file` storage pools, independent of the filesystem. But I've only tested it with `file-reflink` on Btrfs.

**Comment by er4z0r** [comment]
Whenever I try to attach the volume to the dispvm I get 

`qvm-block: error: backend vm 'dom0' does'nt expose device 'dm-121'`

What did I miss?

**Comment by er4z0r** [comment]
> Whenever I try to attach the volume to the dispvm I get
> 
> `qvm-block: error: backend vm 'dom0' does'nt expose device 'dm-121'`
> 
> What did I miss?

Never mind. Was a typo in the qubesdb-write path.
