### ISSUE TITLE
`qvm-prefs sys-net virt_mode hvm` results in "ERROR: Start failed: internal error: libxenlight failed to create new domain 'sys-net'"

### ISSUE THREAD

**Issue by ultimatevert** [QubesOS/qubes-issues#4689]
### Qubes OS version:

R4.0

### Affected component(s): 

Intel Wireless N 1000

---

### Steps to reproduce the behavior:

I installed QubesOS R4.0 and made it to the installation configuration page (where the system finishes installing, reboots, and then you are prompted with the config finishing installer) and I received this error

![img_20190105_212823](https://user-images.githubusercontent.com/39247961/50731397-6d84cc00-1131-11e9-94f2-d9bf852283de.jpg)

I also get this error message when I log into my QubesOS user and try to start sys-net as my WiFi does not work and the little Network applet on the panel is nowhere to be found.

This is what comes up when I check the log,

![img_20190105_212921](https://user-images.githubusercontent.com/39247961/50731447-a07b8f80-1132-11e9-9d4d-d6c061e0497d.jpg)

And I have tried to run the command to force attach the wireless card but I get this

![img_20190105_213510](https://user-images.githubusercontent.com/39247961/50731449-ab362480-1132-11e9-9694-d3f6e34bd3b4.jpg)

So I try the commands 

"sudo qvm-prefs sys-net virt_mode hvm"

But I still get the same error as above.

Any ideas? I installed qubesOS on this machine back in 2017 and simply kept updating it up to R3.2 (I think) and it always worked wonderfully. However R4.0 has this issue so I tried installing R3.2 and my WiFi card also did not work, R3.0 as well, but if I try Xubuntu 18.04/18.04 or any other distro my WiFi works fine. So idk what it is.

### General notes:

---

**Comment by andrewdavidwong** [comment]
Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this appears to be too localized for `qubes-issues`, since it depends on a specific hardware configuration. We ask that you please send this to the `qubes-users` [mailing list](https://www.qubes-os.org/support/) instead. `qubes-users` is intended for these sorts of issues and receives much more traffic, which means that your issue is more likely to receive a response there. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a comment briefly explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.

**Comment by ultimatevert** [comment]
There was an issue about USB Camera not working and it received lots of replies. https://github.com/QubesOS/qubes-issues/issues/4035

I dont know if my issue is relates to my wireless card, it shouldnt be as its worked in past Qube OS releases, I think it has to do with QubesOS not being able to set the PCI/wireless card (regardless of what kind) to the sys-net VM. I dont fully understand how QubesOS works though.

I think if I can fingure out how to change the VM to HVM then I should be able to attach the PCI card but despite the command, QubesOS prints the same error.

**Comment by andrewdavidwong** [comment]
> So I guess there is some type of bug that is not allowing me to change sys-net from pvh to hvm because I try the command but I still can't attach the PCI card.

Hm, ok. I'll reopen the issue and update the title to reflect that it's about this particular problem.

Even if the result is expected, you should probably receive a more informative error message.

**Comment by ultimatevert** [comment]
Okay so if you look at the last screenshot, I was selecting the personal VM instead of sys-net. When I try that, it says the device is already attached to sys-net. However, I still get the error when trying to launch sys-net as seen in the first screenshot.

**Comment by marmarek** [comment]
The second screenshot contains the answer - lack of IOMMU. Installer for Qubes 4.0 checks for this and there is a clear (or not?) message that it won't work without IOMMU and default option is to abort installation.
The exact message:

> This hardware lacks features required by Qubes OS. Missing features: IOMMU/VT-d/AMD-Vi. Without  these features, Qubes OS will not function normally. It is recommended that only developers and power users proceed with the installation. For more information on supported  hardware, please refer to https://www.qubes-os.org/doc/system-requirements/

I'll add also explicit error message at VM start for this case.
