### ISSUE TITLE
qvm-block allows attaching the same device to multiple qubes

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#4692]
### Qubes OS version:

R4.0

---

### Steps to reproduce the behavior:

```sh
qvm-block at vm1 sys-usb:sda
qvm-block at vm2 sys-usb:sda
```

### Expected behavior:

The second command fails as the device is already attached to `vm1`.

### Actual behavior:

Both commands succeed, and device is available in both VMs, possibly leading to data corruption at least, security issues at worst.

---

### Related issues:

Similar issue for R2.0: #950

**Comment by timdiels** [comment]
Seems this has become a duplicate of #6396 which also discusses whether to allow attaching the same device readonly.

**Comment by andrewdavidwong** [comment]
> Seems this has become a duplicate of #6396 which also discusses whether to allow attaching the same device readonly.

No, this was opened first, so #6396 would be a duplicate of this (_if_ it is, in fact, a duplicate at all).

**Comment by johnnyboy-3** [comment]
My setup is similiar, with persistence:
```
qvm-block --persistent vm1 sys-usb:sda
qvm-block --persistent vm2 sys-usb:sda
```
and it is intended, so this should be possible and not blocked.

1. A sufficient fix for my setup would be to fail the boot of an AppVM, if the attached storage is already in use at another running AppVM (or Template, DVM, ...).
2. A more advanced fix would be the simultaneously use of the attached storage in two (or more) AppVMs.

See also discussion @ https://github.com/QubesOS/qubes-issues/issues/6396

**Comment by DemiMarie** [comment]
At a minimum, it should be possible to attach the same device read-only to as many qubes as one wishes.  There is no risk of corruption there!

**Comment by andrewdavidwong** [comment]
Is this still a problem in 4.1?

**Comment by johnnyboy-3** [comment]
yes
