### ISSUE TITLE
qubes-mgmt-salt-dom0-virtual-machines sources are signed with unknown key

### ISSUE THREAD

**Issue by arjan-s** [QubesOS/qubes-issues#4694]
### Qubes OS version: 

R4.0

### Affected component(s): 

qubes-mgmt-salt-dom0-virtual-machines

---

### Steps to reproduce the behavior:

Try a clean build of any template.

### Expected behavior:

The "make get-sources" step completes successfully.

### Actual behavior:

The "make get-sources" command fails with the following output:

```
-> Updating sources for mgmt-salt-dom0-virtual-machines...
--> Fetching from https://github.com/QubesOS/qubes-mgmt-salt-dom0-virtual-machines.git master...
--> Verifying tags...
No valid signed tag found!
---> One of invalid tag:
object 4476968ee23fd320402fc6f5a1fa80ad7201df89
type commit
tag v4.0.15
tagger Simon Gaiser <simon@invisiblethingslab.com> 1543861251 +0100

version 4.0.15
gpg: Signature made Mon Dec  3 19:20:51 2018 CET
gpg:                using RSA key DA0434BC706E1FCF
gpg: Can't check signature: public key not found
make: *** [Makefile:195: mgmt-salt-dom0-virtual-machines.get-sources] Error 1
```

### General notes:

Apparently, the last commits in qubes-mgmt-salt-dom0-virtual-machines have been signed with an unknown key. It's a different key of Simon Gaiser than the one on the QubesOS website.
Perhaps I should run some key-download-script again? My build setup has worked just fine for more than a year, so it's possible that something was updated and I missed it.

---

**Comment by marmarek** [comment]
His code signing key is in [qubes-builder/qubes-developers-keys.asc](https://github.com/QubesOS/qubes-builder/blob/master/qubes-developers-keys.asc). The problem may be about order of downloads - builder itself is updated last. You can force updating it separately with `make COMPONENTS=builder get-sources`.

**Comment by arjan-s** [comment]
Thank you! Simply reimporting qubes-developers-keys.asc and thus adding the missing key has fixed the problem for me.
