### ISSUE TITLE
`swapoff -a` in /rw/config/rc.local keeps qube from starting

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#4696]
### Qubes OS version:

`Qubes release 4.0 (R4.0)`

### Affected component(s): 

---

### Steps to reproduce the behavior:

Include `swapoff -a` in `/rw/config/rc.local`

### Expected behavior:

Qube boots

### Actual behavior:

Qube does not boot

### General notes:

To fix this, I had to create a loop device (in dom0) for the VM’s private device, and then attach that to a DispVM.  I then edited the file in the DispVM.

---

**Comment by unman** [comment]
Not in a Debian template: boots just fine.
Nor in Fedora-28 - the only Fedora I have to hand.
What template are you using? Please update the title as appropriate.

**Comment by marmarek** [comment]
Can you provide more details and what would you expect? For now it sounds like you've tried very hard to break things (disable swap even though VM didn't have enough to work without it) and managed to...

As for troubleshooting by attaching private image, there is already #4687

**Comment by DemiMarie** [comment]
@marmarek I think you are correct, duh.  That said, running `sudo swapoff -a` *after the VM is already running* works, which I would not expect if the problem is lack of memory in the VM.

**Comment by marmarek** [comment]
Later in the VM life time qmemman may give it more memory (if you have some left). But:
 - its VM part needs to be running - `meminfo-writer` service (may not be the caneeds se at the rc.local start time
 - qmemman needs some time to actually reassign the memory

See https://www.qubes-os.org/doc/qmemman/#rationale

**Comment by DemiMarie** [comment]
@marmarek That makes sense.  I probably should have posted this on the [`qubes-users`](mailto:qubes-users@googlegroups.com) mailing list, sorry.
