### ISSUE TITLE
Cannot use "Firewall rules" GUI even after removing custom rules

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#4710]
### Qubes OS version:

`R4.0.1`

### Affected component(s): 

Firewall rules

---

### Steps to reproduce the behavior:

1. Back up a 3.2 VM with firewall rules.
2. Restore the VM on 4.0.1.
3. Open the Firewall rules GUI. It says:
> Firewall has been modified manually - please use qvm-firewall for any further configuration.
4. Use `qvm-firewall` to remove all rules.
5. Restart VM.
6. Check the Firewall rules GUI again. It still says the same thing.
7. Use `qvm-firewall` to add a single, plain `accept` rule.
8. Restart the VM.
9. Check the Firewall rules GUI again. It still says the same thing.

### Expected behavior:

There's some way to recover use of the Firewall rules GUI for a 3.2-restored VM.

### Actual behavior:

There seems to be no way to make the Firewall rules GUI usable again -- no way to recover from this state.

### General notes:

---

### Related issues:

Nothing in this thread seems to work:

https://groups.google.com/d/topic/qubes-users/sqhhBvkWBNU/discussion

**Comment by marmarek** [comment]
I don't have R3.2-restored VM with custom firewall handy, but just tried on some VM - I've added custom rule and got "Firewall has been modified manually" message, then removed all rules and added just plain accept with:
```
qvm-firewall VMNAME add action=accept
```
And GUI allow me to edit rules again.

As for making custom firewall rules working with GUI:
1. Blacklist mode is gone ("allow all except...").
2. The last rule must be either `action=accept` or `action=deny` (without any other options).
3. For `action=deny` as the last rule, other rules needs to be `action=accept` (possibly with other options too).
4. For `action=deny` as the last rule, you need to have `specialtarget=dns action=accept` and `proto=icmp action=accept` rule just before it.

**Comment by andrewdavidwong** [comment]
As mentioned above, even adding a single, plain `accept` rule doesn't work.

```
qvm-firewall VMNAME add action=accept
```

Just tried again with this command. No change.

**Comment by andrewdavidwong** [comment]
On 4.1, even if one does `qvm-firewall <QUBE_NAME> reset` and verifies that all firewall rules are gone using `qvm-firewall <QUBE_NAME>`, the GUI still says, "Firewall has been modified manually. Please use the 'qvm-firewall' command in dom0 for any further configuration."
