### ISSUE TITLE
Non-default apps are missing Application Launcher shortcut icons

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#4711]
### Qubes OS version:

`R4.0.1`

### Affected component(s): 

Application launcher

---

### Steps to reproduce the behavior:

1. Back up VMs on 3.2.
2. Restore VMs on 4.0.1.
3. Install/update a new TemplateVM.
4. Base the restored VMs on the new template.
5. `qvm-sync-appmenus <new_template>`
6. Try to click on the app launcher shortcuts for the restored VMs.

### Expected behavior:

The app launcher shortcuts have icons and start the appropriate VM and app when clicked.

### Actual behavior:

Most of them are missing icons, and most of them have no user-visible effect when clicked (including not starting the VM).

### General notes:

 - All templates are new, not restored.
 - When creating a new VM, all the app launcher shortcuts have icons and seem to work correctly. Only the restored VMs are affected, even after `qvm-sync-appmenus`.
 - The restored apps have the old `<vm_name>: Add more shortcuts...` link (which doesn't do anything) instead of the new `<vm_name>: Qube Settings` link (which works).

---

### Related issues:

 - #2449 -- But in this case, it happens with more than just Nautilus.
 - #3473 -- But in this case, the app doesn't start no matter how many times you click.
 - #3533 -- But in this case, the VM doesn't even start.

**Comment by marmarek** [comment]
How example broken `.desktop` file looks like? Does `qvm-appmenus --update --force <vm_name>` help?

**Comment by andrewdavidwong** [comment]
> How example broken `.desktop` file looks like?

Can you remind me where to find them?

> Does `qvm-appmenus --update --force <vm_name>` help?

Yes! That works! After doing this, all the shortcuts have icons, and clicking a shortcut starts the VM and starts the app in that VM. The only problem is that the old `<vm_name>: Add more shortcuts...` link is still leftover alongside the new `<vm_name>: Qube Settings` one.

**Comment by andrewdavidwong** [comment]
Looks like there are still a few broken shortcuts left over (some missing icons), but overall much better.

**Comment by andrewdavidwong** [comment]
Also, one of the restored VMs that had `<vm_name>: Add more shortcuts...` was renamed, but now there's a leftover entry for `<old_vm_name>-vm` with just the `Add more shortcuts...` item.

**Comment by marmarek** [comment]
> Can you remind me where to find them?

`~/.local/share/applications` - those are really used ones
`~/.local/share/qubes-appmenus` - internal directory, containing also those not selected to be in the menu

As for `<vm_name>: Add more shortcuts...`, this looks to be similar to https://github.com/QubesOS/qubes-issues/issues/1106, but that was fixed already... Have you overridden ~/.local` with the one from the backup?

**Comment by andrewdavidwong** [comment]
> Have you overridden ~/.local` with the one from the backup?

Yes, I overwrote the new dom0 `/home` with my old one when migrating.

**Comment by andrewdavidwong** [comment]
> `~/.local/share/applications` - those are really used ones
> `~/.local/share/qubes-appmenus` - internal directory, containing also those not selected to be in the menu

Thanks. I even had some Fedora 24 shortcuts in there. :slightly_smiling_face:

Looks like the remaining missing icons are all custom-installed programs (e.g., VLC). The .desktop file shows a path for the icon. (I'd copy/paste it here, but apparently we've lost the ability to easily copy/paste from dom0 in this release...)

**Comment by andrewdavidwong** [comment]
Ok, so it looks like problem now has nothing to do with whether the VM was restored or newly created (updating issue title to reflect this). Rather, it's just whether the application is non-default. For example, Dropbox, Keybase, and VLC have missing icons, but none of the default apps do.

**Comment by brycepg** [comment]
It looks like qubes only uses the `Icon=`  in `.desktop` files for the appmenu. Window icons in what xfce calls "Window Buttons" (the widow icon area for a workspace) appear to be only set by the process itself.  This is even true when I create a .desktop file on the AppVM.

I was able to set the "Window Button" icon for custom installed programs (e.g. AppImage stuff) by compiling and using xseticon (which sets _NET_WM_ICON to something like a bitmap? with libgd ).

**Comment by brycepg** [comment]
I was able to set an icon with byte packing in python and `xprop`, the caveat being that its limited to 7x7 pixels unless xprop source code is modified (a very tiny amount), probably can be done with ctypes however it would still depend on a png library to read the icon. Not sure how to get the X11 window ID from qvm-run/qrexec/RPC directly

**Comment by marmarek** [comment]
The code that sends icons is here: https://github.com/QubesOS/qubes-gui-agent-linux/blob/main/window-icon-updater/icon-sender

> It looks like qubes only uses the `Icon=` in `.desktop` files for the appmenu. Window icons in what xfce calls "Window Buttons" (the widow icon area for a workspace) appear to be only set by the process itself. This is even the case when I create a and run .desktop file on the AppVM

Yes, this is generally how it's supposed to work. There may be no associated .desktop file for some application (and you can start it for example from terminal) and even if there is one, it isn't always possible to find which one applies to a running application. So, using `Icon=` field from the desktop file for a running application is not something that can be done universally. But if there are cases where that would be an improvement, see if you could extend the code I linked above.

**Comment by andrewdavidwong** [comment]
I haven't run into this problem in a long time. If anyone is still experiencing this problem on a supported Qubes release, please leave a comment, and we'll be happy to reopen this issue.
