### ISSUE TITLE
rpc.idmapd conf_reinit : null

### ISSUE THREAD

**Issue by randomser443** [QubesOS/qubes-issues#4715]
I have created a bootable USB using the "Qubes-R4.0.1-x86_64.iso". But once I begin to boot my PC from the USB these errors pop up on the screen in this order(all same screen):

[12.493714] dracut-pre-udev[428]: rpc.idmapd: conf_reinit: open ("(null)", 0_RDONLY) failed
[12.494269] dracut-pre-udev[428]: rpc.idmapd: conf_reinit: open ("(null)", 0_RDONLY) failed
[14.074204] kfd kfd: kgd2kfd_ probe failed

After showing these it still pops up the Qubes logo and the very first screen to begin the installation process, but then in a few seconds it gives me an error message. I have no choice put to shut down because it won't allow me to continue.

There were errors given once the Qubes logo was brought up but I don't have them written down currently, but I'll post them once I get them. Right now I'm just wondering about the errors it shows before it even boots up.

**Comment by nakoo** [comment]
Did you solve this problem? I have tried media test mode but due to that problem, I couldn’t do It. It’s still possible to install Qubes OS though. (My version is Qubes-R4.0.3-x86_64)
