### ISSUE TITLE
Qubes GUI widgets get out of sync

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#4720]
### Qubes OS version:

`Qubes release 4.0 (R4.0)`

### Affected component(s): 

`domains.py`, `devices.py`, possibly others

---

### Steps to reproduce the behavior:

Various, but using `qui-domains` to kill an AppVM that is hung in startup or shutdown will reproduce the problem reliably.  Killing an AppVM that has attached devices can confuse `qui-devices`, but shutting the VM down cleanly does not.

### Expected behavior:

Qubes widgets stay in sync with reality

### Actual behavior:

Qubes widgets do not stay in sync with reality

### General notes:

The symptoms of this problem are similar to, but different from, #3100.

---

### Related issues:

#3100

**Comment by marmarta** [comment]
Could you say a bit more what do you mean by 'out of sync'? Not reporting on newly started VMs? Incorrect names of thing?

**Comment by DemiMarie** [comment]
@marmarta Mostly, failing to notice that VMs have been started or stop.

**Comment by marmarta** [comment]
What version of qubes-desktop-linux-manager do you have? (easy way to check: `rpm --version qubes-desktop-linux-manager` in dom0)
