### ISSUE TITLE
Remove /usr/local from list of template directories

### ISSUE THREAD

**Issue by theunlimited09** [QubesOS/qubes-issues#4722]
### Reasoning:

`sudo pip install <package>` installs packages in the directory `/usr/local/lib/python<version>/...`

Doing the same command without `sudo` isn't any better because then it's installed in `$HOME/.local/...`

This is annoying when you want to have a package installed across an entire template. (especially when it's a big package that has dependency issues you have to fix manually for every install!)

The other option is to use the `-t <directory` (target) option with `pip` to install to a custom directory. However, that's not preferable because it's not standard.

This leads me to wonder why the /usr/local directory is even included in the AppVM private disk. I don't know about you guys but for me (in my Kali (debian-9 based template with tools installed by Katoolin) that directory practically has nothing but empty directories and a couple of symlinks.

**Comment by andrewdavidwong** [comment]
Might be a `won't do` if there are good reasons for the status quo. Let's see what @marmarek says.

**Comment by marmarek** [comment]
`/usr/local` is a place where you can install applications for that one particular qube. While some applications do support installing in `$HOME` (like your pip example), in most cases it is far less than trivial. Adding `-t <directory>` to `pip` is definitely easier thing to do.

In this particular case, there is also a good reason to avoid using `pip` in template (especially if you have just one) - this (and many other) language-specific package manager do not verify any kind of signatures, relying solely on security of repository servers and https. Which means using `pip` increase risk of compromising that VM.
