### ISSUE TITLE
Use our own terminology more consistently throughout the system

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#4723]
### Qubes OS version:

`R4.0.1`

---

### "Qubes Domains: View and manage running domains."

From our glossary's definition of [domain](https://www.qubes-os.org/doc/glossary/#domain):
> An area or set of activities in one’s digital life that has certain security requirements and therefore involves the use of certain qubes. For example, suppose your “email” domain encompasses the activity of sending PGP-encrypted email. This domain may include your email qube and your Split GPG qube. **Note that domains and qubes are not the same thing. In this example, your “email” domain includes the use of two qubes. Furthermore, a qube can fall under multiple domains simultaneously. For example, your Split GPG qube may also be part of your “software development” domain if you PGP-sign your Git commits.**

So, this is a misuse of the term. Similarly, in the Application Launcher, we have `Domain: <vm_name>`, which is the same kind of misuse.

### "Create Qubes VM"

Either we should decide to use the term "VM" freely, or it should not be in the name of this nontechnical-user-facing tool (see #1015).

After clicking on `Create Qubes VM`, the window title is called `Create new qube`. This implies that "qube" is a synonym for "VM" (see https://github.com/QubesOS/qubes-doc/pull/764; CC: @unman).

When selecting a type, there are three options:

 - AppVM
 - Standalone qube based on a template
 - Standalone qube not based on a template

"Standalone qube based on a template" is a contradiction in terms, because a [StandaloneVM](https://www.qubes-os.org/doc/glossary/#standalonevm) is by definition a VM that is not based on a template. Conversely, "Standalone qube not based on a template" is redundant for the same reason. I think you probably meant "copied from" instead of "based on" here.

**Comment by marmarta** [comment]
@marmarek, I think you should read this too.
To be honest I am apparently a little confused by the terminology here. I was under the impression we were phasing out 'VM' in almost all places and replacing it by 'qube', while 'domain' would be an AppVM. I'm fine with any definition, as long as we all have just one set of those :)

**Comment by andrewdavidwong** [comment]
> I was under the impression we were phasing out 'VM' in almost all places and replacing it by 'qube'

I am under the same impression, which is why I opened this issue in order to point out that we have a menu entry called `Create Qubes VM`, which opens a window with the title `Create new qube`.

 - Shouldn't the menu entry be called `Create new qube` also?
 - Shouldn't the menu entry and the window title be the same, regardless of which name we choose?

(However, it's unclear to me whether we're actually still committed to using the term "qube" in this way, which is why I asked about that in https://github.com/QubesOS/qubes-issues/issues/1015#issuecomment-453444671.)

> while 'domain' would be an AppVM

I'm not aware of such a change in meaning. (By contrast, I _am_ aware of a change in the meaning of "AppVM," as discussed in https://github.com/QubesOS/qubes-doc/pull/748.)

> I'm fine with any definition, as long as we all have just one set of those :)

I might be a bit more picky about which definitions we choose, but I agree that there should be just one set. :)

**Comment by taradiddles** [comment]
IMHO you should stick to the "VM" definition instead of "qube": the majority of the official docs use "VM",  it's consistent with disp*VM*s, App*VM*s, ..., and most importantly, most people are used to the "VM" terminology.
Just my 2c.

**Comment by unman** [comment]
On Thu, Jan 17, 2019 at 10:36:37PM -0800, Ivan wrote:
> IMHO you should stick to the "VM" definition instead of "qube": the majority of the official docs use "VM",  it's consistent with disp*VM*s, App*VM*s, ..., and most importantly, most people are used to the "VM" terminology.
> Just my 2c.
> 
I dont think we want to revisit this. "qubes" was supposed to be more user
friendly, and consistent with the Qubes approach. I think it's suitable
for new users  and for that target, they wont be used to "VM".
If the majority of new user docs *do* use VM, then they should be
adjusted as we go.

**Comment by taradiddles** [comment]
> I dont think we want to revisit this.

OK. I didn't know this had been "visited" in QubesOS/qubes-doc#764 when I replied.

> If the majority of new user docs *do* use VM, then they should be adjusted as we go.

The problem is not adjusting *new* documents, it's fixing *existing* documents, GUIs and command line tools, because using "qube" in an official doc, "VM" in another + having mixed terms in tools/GUIs will definitely confuse non-tech users (whom it seems it's all about) A LOT more than a consistent "VM" terminology. And the quicker this extensive find/replace task is done, the better for such users.

TBH considering the lack of time of qubes devs and scarcity of doc contributors I find it a bit puzzling to spend time on such task but since it's been decided this way so be it.

(if my comment sounds harsh / makes it look like I'm entitled to something: it's not meant to/I'm not).

**Comment by unman** [comment]
On Fri, Jan 18, 2019 at 05:52:37AM -0800, Ivan wrote:
> > I dont think we want to revisit this.
> 
> OK. I didn't know this had been "visited" in QubesOS/qubes-doc#764 when I replied.
> 
> > If the majority of new user docs *do* use VM, then they should be adjusted as we go.
> 
> The problem is not adjusting *new* documents, it's fixing *existing* documents, GUIs and command line tools, because using "qube" in an official doc, "VM" in another + having mixed terms in tools/GUIs will definitely confuse non-tech users (whom it seems it's all about) A LOT more than a consistent "VM" terminology. And the quicker this extensive find/replace task is done, the better for such users.

I intended "docs for new users", not "new docs for users".

> 
> TBH considering the lack of time of qubes devs and scarcity of doc contributors I find it a bit puzzling to spend time on such task but since it's been decided this way so be it.

This is why I suggest it is done piecemeal as pages are edited,
rather than as discrete extensive task.

> 
> (if my comment sounds harsh / makes it look like I'm entitled to something: it's not meant to/I'm not).

**Comment by andrewdavidwong** [comment]
- Discussion about whether we should switch from "[App]VM" to "qube" and the best way to do so should be on #1015, not here.
 - There is a big difference between "AppVM" and "VM." They do not mean the same thing. Therefore, it matters whether "qube" means "AppVM" or whether it means "VM." See https://github.com/QubesOS/qubes-doc/pull/764#issuecomment-454654703. Maybe we can get away with "qube" being a ambiguous between these, but that should be a conscious decision carefully made. I am not optimistic that efforts to constrain "qube" to being a synonym of just "AppVM" (as opposed to "VM") will succeed. Even in this discussion among Qubes experts, the distinction was not recognized.

**Comment by h01ger** [comment]
On Fri, Jan 18, 2019 at 04:51:33PM -0800, Andrew David Wong wrote:
>  - Discussion about whether we should switch from "[App]VM" to "qube" and the best way to do so should be on #1015, not here.
>  - There is a big difference between "AppVM" and "VM." They do not mean the same thing. Therefore, it matters whether "qube" means "AppVM" or whether it means "VM." See https://github.com/QubesOS/qubes-doc/pull/764#issuecomment-454654703. Maybe we can get away with "qube" being a ambiguous between these, but that should be a conscious decision carefully made. I am not optimistic that efforts to constrain "qube" to being a synonym of just "AppVM" (as opposed to "VM") will succeed. Even in this discussion among Qubes experts, the distinction was not recognized.

maybe the (granted, long-term) solution then is to call it AppQube (etc)?!


-- 
tschüß,
	Holger

-------------------------------------------------------------------------------
               holger@(debian|reproducible-builds|layer-acht).org
       PGP fingerprint: B8BF 5413 7B09 D35C F026 FE9D 091A B856 069A AA1C

**Comment by marmarta** [comment]
@andrewdavidwong , I've made the Create New VM dialog use the following:

-Qube based on a template (AppVM)
-Standalone qube
-Standalone qube copied from a template

What do you think about it?

**Comment by andrewdavidwong** [comment]
> @andrewdavidwong , I've made the Create New VM dialog use the following:
> 
> -Qube based on a template (AppVM)

I still think we should preserve the distinction between VMs-for-running-applications (R3.2 AppVMs) and TemplateBasedVMs, but if we're not doing that, then this is fine.

> -Standalone qube
> -Standalone qube copied from a template
> 
> What do you think about it?

What is the difference between `Standalone qube` and `Standalone qube copied from a template`? In other words, if `Standalone qube` is not copied from a template, where does it come from?

**Comment by marmarek** [comment]
> In other words, if `Standalone qube` is not copied from a template, where does it come from?

It's empty, without any system installed. You can install a system there by starting it from some installation cdrom (image).

**Comment by andrewdavidwong** [comment]
> > In other words, if `Standalone qube` is not copied from a template, where does it come from?
> 
> It's empty, without any system installed. You can install a system there by starting it from some installation cdrom (image).

Maybe this option should say something like:

```
Empty standalone qube (install your own OS)
```

**Comment by andrewdavidwong** [comment]
A big one I've been noticing more lately is "DisposableVM." A while back, it was decided that the canonical term will be "DisposableVM." That means the following variants should **not** be used (but still frequently are):

```
Disposable VM
disposable VM
disposableVM
disposable vm
Disposable vm
Disposablevm
disposablevm
DispVM
dispVM
Dispvm
dispvm
disp vm
Disp VM
disp VM
disp-vm
Disp-VM
Disp-vm
disp-VM
etc.
```

**Comment by andrewdavidwong** [comment]
@marmarta, if you could point me to the relevant repo locations, I would be happy to submit PRs to fix and improve the language used throughout Qubes.

**Comment by DemiMarie** [comment]
> A big one I've been noticing more lately is "DisposableVM." A while back, it was decided that the canonical terms will be "DisposableVM" and "DisposableVM Template." That means the following variants should **not** be used (but still frequently are):
> 
> ```
> Disposable VM
> disposable VM
> disposableVM
> disposable vm
> Disposable vm
> Disposablevm
> disposablevm
> DispVM
> dispVM
> Dispvm
> dispvm
> disp vm
> Disp VM
> disp VM
> disp-vm
> Disp-VM
> Disp-vm
> disp-VM
> DVM Template
> dvm template
> DVM template
> dvmTemplate
> DVMTemplate
> template DVM
> templateDVM
> TemplateDVM
> DVM
> dvm
> Template for DVM
> etc.
> ```

I know that I use “DispVM” a **lot**, simply because it is shorter.  It is also used in quite a few more places internally, IIRC.

**Comment by DemiMarie** [comment]
```
$ make -C ~/qubes-builder grep 'RE=[Dd][Ii][Ss][Pp][Vv][Mm]'|wc -l
1432
$ make -C ~/qubes-builder grep 'RE=[Dd][Ii][Ss][Pp][Oo][Ss][Aa][Bb][Ll][Ee][Vv][Mm]'|wc -l
113
```

**Comment by marmarek** [comment]
Indeed, the internal class name is DispVM. That's something that IMO we should change.

**Comment by DemiMarie** [comment]
> Indeed, the internal class name is DispVM. That's something that IMO we should change.

Not just class name, but also property/API/etc name.  Switching right now would be a major breaking change.

**Comment by unman** [comment]
On Wed, May 12, 2021 at 04:48:48AM -0700, Demi Marie Obenour wrote:
> > Indeed, the internal class name is DispVM. That's something that IMO we should change.
> 
> Not just class name, but also property/API/etc name.  Switching right now would be a major breaking change.
> 

It's not about the code (although it would be desirable if code
reflected usage and documentation conventions).
It's about the user facing tools, documentation, and discussions.
We should be consistent and clear there. Making *that* change should not
be major at all.

**Comment by brendanhoar** [comment]
One of the key reasons to avoid DispVM is user/developer confusion between that and a "Display VM". Yes, even though the "Display VM" name is not correct (official term for that is "GUI VM").

**Comment by andrewdavidwong** [comment]
FYI, you're all rehashing the discussion about this from years ago, almost verbatim. 🙂

**Comment by ninavizz** [comment]
@andrewdavidwong The conversation I'm observing to be happening, for usability reasons; whether it's developer needs, or end-user needs in a Terminal, or end-user needs navigating an interface. Those needs are not being met by past decisions, it is sounding like. 

Solutions that work for everyone, are unlikely to come from a conversation al thread—and I'd recommend a moderated async workshop, to resolve. 

Canonical terms used in long-form writing, are often abbreviated for use in GUIs. Long character counts such as `Disposable VM` don't work to show users in a UI, because of the cognitive friction in the character count. That's a UX best practice consideration, and it's important. It also applies to CLI usability with typing-out a thing that could be easily misspelled because it has a lot of characters. 

A writing rule I've observed in practice that I feel best applies to the disposable vm situation, is to always refer to it in an abbreviated form throughout the UI. In documentation and writing, then, always begin topics involving disposable vms with the long-form mentioned, first, followed by the abbreviation in parenthesis... then continued use of the abbreviation for the rest of the writing. Same, for contextual help bubbles in the UI (that we need more of, throughout Qubes, and I proposed in my Applications Settings tab for Qube Settings. This is what I would recommend, for the disposable vms. 

The term in the Linux world for what matches a mental-model (mental, not literal) of what the GUI VM controls, is "Desktop" or "Desktop Environment." And yet it has been written about extensively as the GUI-VM. To get a definitive answer, some user research (a card sort is what is coming to mind) would be necessary. GVM

**Comment by SvenSemmler** [comment]
> The term in the Linux world for what matches a mental-model (mental,
> not literal) of what the GUI VM controls, is "Desktop" or "Desktop
> Environment." And yet it has been written about extensively as the
> GUI-VM. To get a definitive answer, some user research (a card sort
> is what is coming to mind) would be necessary. GVM

The use of "Desktop" would be inconsistent.

sys-usb ... USB
sys-net ... NIC
sys-audio ... audio / ALSA
sys-graphics ... GUI / GPU

The point being that we isolate interfaces in dedicated qubes (I like 
"qube" much better than VM ...but I think that's a lost battle).

**Comment by ninavizz** [comment]
> sys-usb ... USB
> sys-net ... NIC
> sys-audio ... audio / ALSA
> sys-graphics ... GUI / GPU

I really like sys-graphics, actually. Very straightforward, and less tech jargon-y than "GUI.' Also clearly tells non-technical users that this is a thing for the _system to use_ to make _its graphics_ happen. As it makes the internet happen with sys-net, and external devices accessible via sys-usb, and audio accessible with sys-audio. 

Yeah, in user-facing stuff, Marta and I are both also trying to get `qube` standardized around. Totally going to be a lost cause I think, with threaded contributor conversations like this, tho... until we're all used to seeing it in our UIs, I suspect.

**Comment by ninavizz** [comment]
Oh! **DQube** for Disp-VM. Using the _qube_ nomenclature in an easy-to-remember fashion, and very easy to say (which is a good indication towards cognitive processes)! "Disposable Qube" in written documentation, always written-out in the first sentence of contextual help as "Disposable Qube (DQube)"

There's only one _sys-graphics_ qube with that GUI isolation schema, so no need to go to GQube or 0Qube for dom0 or sys-graphics... is that correct?

![AppSettings-tips3](https://user-images.githubusercontent.com/8262612/118071724-2c360400-b35d-11eb-8390-6c66a21583ef.png)

**Comment by andrewdavidwong** [comment]
This issue is about using our terminology more consistently after it is decided upon, not deciding what specific terminology should be in the first place. So, many of these comments, while good, are simply off-topic for this issue. In particular, please post comments about what DisposableVM-related terminology should be here instead: https://github.com/QubesOS/qubes-issues/issues/4935

**Comment by andrewdavidwong** [comment]
> Those needs are not being met by past decisions, it is sounding like.

If the past decision about "DisposableVM" needs to be relitigated, that's fine. Please do it in https://github.com/QubesOS/qubes-issues/issues/4935.

> Canonical terms used in long-form writing, are often abbreviated for use in GUIs. [...]  A writing rule I've observed in practice that I feel best applies to the disposable vm situation, is to always refer to it in an abbreviated form throughout the UI. In documentation and writing, then, always begin topics involving disposable vms with the long-form mentioned, first, followed by the abbreviation in parenthesis... then continued use of the abbreviation for the rest of the writing.

The practice of introducing an abbreviation in writing often follows the pattern you're describing, but that's not necessarily the same as introducing a technical term. Some abbreviations are also technical terms, but not all of them are. Likewise, some technical terms are abbreviations, but not all of them are. When we're trying to use our terminology consistently through the OS and the documentation, it's important to understand what counts as being consistent. Using abbreviations may be fine, whereas making up non-standard variants of established technical terms may not.

> Same, for contextual help bubbles in the UI (that we need more of, throughout Qubes, and I proposed in my Applications Settings tab for Qube Settings.

I agree that we need more explanatory tooltips. We already have a separate issue for that: https://github.com/QubesOS/qubes-issues/issues/2211

**Comment by unman** [comment]
On Wed, May 12, 2021 at 12:57:20PM -0700, Nina Eleanor Alter wrote:
> @andrewdavidwong The conversation I'm observing to be happening, for usability reasons; whether it's developer needs, or end-user needs in a Terminal, or end-user needs navigating an interface. Those needs are not being met by past decisions, it is sounding like. 
> 
> Solutions that work for everyone, are unlikely to come from a conversation al thread???and I'd recommend a moderated async workshop, to resolve. 
> 
> Canonical terms used in long-form writing, are often abbreviated for use in GUIs. Long character counts such as `Disposable VM` don't work to show users in a UI, because of the cognitive friction in the character count. That's a UX best practice consideration, and it's important. It also applies to CLI usability with typing-out a thing that could be easily misspelled because it has a lot of characters. 
> 
> A writing rule I've observed in practice that I feel best applies to the disposable vm situation, is to always refer to it in an abbreviated form throughout the UI. In documentation and writing, then, always begin topics involving disposable vms with the long-form mentioned, first, followed by the abbreviation in parenthesis... then continued use of the abbreviation for the rest of the writing. Same, for contextual help bubbles in the UI (that we need more of, throughout Qubes, and I proposed in my Applications Settings tab for Qube Settings. This is what I would recommend, for the disposable vms. 
> 
> The term in the Linux world for what matches a mental-model (mental, not literal) of what the GUI VM controls, is "Desktop" or "Desktop Environment." And yet it has been written about extensively as the GUI-VM. To get a definitive answer, some user research (a card sort is what is coming to mind) would be necessary. GVM
> 

I don't think we should be crawling over past decisions, and I don't see
any evidence that end-user needs aren't being met by past decisions.
(They may not be - I just don't see evidence for that.)
I *do* think that the inconsistencies of usage over decisions that were
made in the past don't meet end-user needs, but that's a different
matter.

There was a suggestion that "qube" had lost the battle - is this true? I
don't see a good alternative.
It was one of those agreed things for beginners/non-technical use, and I
have always found to to be readily accepted. The failure to use it
consistently across the system was **exactly** what Andrew was pointing
to.

**Comment by SvenSemmler** [comment]
> There was a suggestion that "qube" had lost the battle - is this 
> true? I don't see a good alternative.

I was unsure of the outcome of previous discussions I participated in as 
they never led to any conclusion and things have remained as they are 
since then.

> It was one of those agreed things for beginners/non-technical use, 
> and I have always found to to be readily accepted. The failure to
> use it consistently across the system was **exactly** what Andrew
> was pointing to.

My impression is that everyone agrees with Andrew's point but 
immediately launched into discussing once more how things should be 
called. A necessary step before unifying.

**Comment by ninavizz** [comment]
@andrewdavidwong Got it, thx for the course-correction on this issue's topic. So, my question for you, would then be: as an Issue, what action are you seeking to "resolve" it? 

@unman We're currently learning about user needs through controlled research methods, for the first time. To me, that warrants some updating. Likewise, if the goals of the language have changed to be more inclusive to new and/or non-Linux native users. 

But yes, to Andrew's point above, agreed to "stay on point" which is not re-litigating use of language.

**Comment by andrewdavidwong** [comment]
> @andrewdavidwong Got it, thx for the course-correction on this issue's topic. So, my question for you, would then be: as an Issue, what action are you seeking to "resolve" it? 

I think the action to resolve this issue should just be to replace all known inconsistent uses of a given term with the official term, whatever that might be. In other words, if we're not sure what the official term is, pause this issue, decide that in its own issue, then finish this one. (Admittedly, we already have a bit of a mess of partially-overlapping issues in this area that have been dragging along for years due to lack of consensus and indecision.)

**Comment by andrewdavidwong** [comment]
Some user feedback:

https://twitter.com/Piniora/status/1462043541237022722

> I see inconsistency in naming scheme.
> There are:
> - Create Qubes VM
> - Qubes Global Settings
> - Qubes Update
> - Qubes Template Manager
> - Backup/Restore Qubes
> 
> and suddenly in:
> - Qube Manager
> which shows all Qubes, their state, ip, storage.

**Comment by unman** [comment]
The first should be "Create qube"
The rest seem consistent with our naming scheme, unless we change
"Backup/Restore Qubes" to "Backup/Restore qubes" for clarity.

Qubes in the first section refers to the OS - these are functions of
the OS. "Qube manager" because it's a manager for qubes, not for the OS.
Isnt that clear? What could be improvement?

**Comment by andrewdavidwong** [comment]
> The first should be "Create qube" The rest seem consistent with our naming scheme, unless we change "Backup/Restore Qubes" to "Backup/Restore qubes" for clarity. Qubes in the first section refers to the OS - these are functions of the OS. "Qube manager" because it's a manager for qubes, not for the OS. Isnt that clear? What could be improvement?

It's clear to me but apparently not to everyone. See my [replies](https://twitter.com/andrewdavidwong/status/1462771816632500228).

This is just one person's feedback, though, not a big data set.
