### ISSUE TITLE
Emergency backup restore v4 instructions unclear about how to read qubes.xml.000.enc

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#4728]
### Qubes OS version:

`R4.0.1`

### Affected component(s): 

Emergency backup restore v4:

https://www.qubes-os.org/doc/backup-emergency-restore-v4/

---

The first step says:

```
 1. Untar the main backup file.

        [user@restore ~]$ tar -i -xvf qubes-backup-2015-06-05T123456
        backup-header
        backup-header.hmac
        qubes.xml.000.enc
        vm1/private.img.000.enc
        vm1/private.img.001.enc
        vm1/private.img.002.enc
        vm1/icon.png.000.enc
        vm1/firewall.xml.000.enc
        vm1/whitelisted-appmenus.list.000.enc
        dom0-home/dom0user.000.enc

    **Note:** Each VM in the backup file has its path listed in
    `qubes.xml.000.enc` (search for the `backup-path` property). You can
    extract only the files necessary for your VM (`vmX`) with `tar -i -xvf
    qubes-backup-2015-06-05T123456 backup-header backup-header.hmac vmX/`.
```

The problem is that `qubes.xml.000.enc` is unreadable (because encrypted), and the instructions do not explain how to decrypt it.

**Comment by kschubitz** [comment]
The password is: `<backup-id>!<original-filename>!<passphrase>`

The original filename of qubes.xml.000.enc is **qubes.xml.000**
Assuming the backup password is "**password**", you would do this:

$ cat backup-header | grep backup-id
backup-id=**20190128T123456-1234**

$ scrypt dec -P qubes.xml.000.enc qubes.xml.000
Please enter passphrase: **20190128T123456-1234!qubes.xml.000!password**

$ tar -i -xvf qubes.xml.000

Now you have the plain qubes.xml and can work with that.

**Comment by andrewdavidwong** [comment]
@marmarek: If I understand correctly, one should not attempt to decrypt `qubes.xml.000.enc` until _after_ verifying the integrity of `backup-header`, since `qubes.xml.000` could be malicious. However, this would mean that one should perform steps 2-5 before performing step 1, which is a bit of a catch-22. Revising the instructions to account for this case might make them needlessly confusing for the standard case in which one is willing to untar the whole file, so I'm inclined to just omit this note.
