### ISSUE TITLE
Template updates start sys-whonix when it should not

### ISSUE THREAD

**Issue by t4777sd** [QubesOS/qubes-issues#4734]
### Qubes OS version:
4 most recently updated

### General notes:
When updating (sudo dnf update) in a template sys-whonix is starting when it should not. Qubes configuration has not been changed, so it should not be starting sys-whonix.

In Qubes Manager the Dom0 UpdateVM is set to sys-net.

In /etc/qubes-rpc/policy/qubes.UpdateProxy it contains this:

$type:TemplateVM $default allow,target=sys-net

In /etc/qubes-rpc/policy/qubes.UpdateProxy.rpmnew it contains this:

$tag:whonix-updatevm $default allow,target=sys-whonix

I did not modify these files. Inside the rpmnew it says upgrade all templates through sys-whonix by uncommenting a line. I did not uncomment that line.

Based on this, templatevm without whonix-updatevm should use sys-net. However, that is not the case. I verified in qvm-tags that the templates do NOT have sys-whonix. This did not always run sys-whonix it seems to be a recent thing.

So my guess is that there is some errors in these policy files. Note, I have never modified these policy files and only came across them when trying to figure out what is wrong.

**Comment by unman** [comment]
On Fri, Jan 18, 2019 at 01:01:16AM -0800, t4777sd wrote:
> ### Qubes OS version:
> 4 most recently updated
> 
> ### General notes:
> When updating (sudo dnf update) in a template sys-whonix is starting when it should not. Qubes configuration has not been changed, so it should not be starting sys-whonix.
> 
> In Qubes Manager the Dom0 UpdateVM is set to sys-net.
> 
> In /etc/qubes-rpc/policy/qubes.UpdateProxy it contains this:
> 
> $type:TemplateVM $default allow,target=sys-net
> 
> In /etc/qubes-rpc/policy/qubes.UpdateProxy.rpmnew it contains this:
> 
> $tag:whonix-updatevm $default allow,target=sys-whonix
> 
> 
> I did not modify these files. Inside the rpmnew it says upgrade all templates through sys-whonix by uncommenting a line. I did not uncomment that line.
> 
> Based on this, templatevm without whonix-updatevm should use sys-net. However, that is not the case. I verified in qvm-prefs that the templates do NOT have sys-whonix. This did not always run sys-whonix it seems to be a recent thing.
> 
> So my guess is that there is some errors in these policy files. Note, I have never modified these policy files and only came across them when trying to figure out what is wrong.
> 
> 

Can you identify the template you are trying to update, and post the full
content of /etc/qubes-rpc/policy/qubes.UpdateProxy 

Do you notice this behaviour with one specific template or is it ANY
template?
