### ISSUE TITLE
Inter-VM clipboard dom0 desktop notifications stop appearing after a while

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#4737]
### Qubes OS version:

`R4.0.1`

### Affected component(s): 

dom0 Xfce4 desktop notifications

---

### Steps to reproduce the behavior:

Use the inter-VM clipboard by pressing <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>C</kbd> and <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>V</kbd>.

### Expected behavior:

A dom0 desktop notification (text bubble in the upper-right corner of the screen) shows up for each inter-VM clipboard action (copy and paste).

### Actual behavior:

At first, dom0 desktop notifications appear for inter-VM clipboard actions. However, after using the system for a while (hours to days), they stop showing up, and there is no longer any visual indication when an inter-VM clipboard action occurs. The inter-VM clipboard still functions normally, with the ability to copy and paste between VMs.

### General notes:

---

**Comment by marmarek** [comment]
Check `~/.xsession-errors` in dom0 if you have some related messages there.

**Comment by andrewdavidwong** [comment]
I see quite a few errors in the file, but it's not clear which (if any) are related to this particular problem. I tried using the inter-VM clipboard right now to see if any lines were added, but none were. Any idea what I should look for earlier in the log?

**Comment by marmarek** [comment]
Anything containing "clipboard". You should also see `python3 -mqui.clipboard` process running, which is responsible for those notifications.
