### ISSUE TITLE
Qubes Update widget should indicate which VMs have updates available

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#4743]
### Qubes OS version:

`R4.0.1`

### Affected component(s): 

Qubes Update widget

---

### Steps to reproduce the behavior:

1. Click on the Qubes Update widget. It says, "Updates available for 1 qubes."
2. Click on the only option: Launch updater.
3. See a list of VMs including dom0 and all the TemplateVMs in the system.

### Expected behavior:

Somewhere in this process, I'm told which one VM has updates available so that I don't have to update all of them.

### Actual behavior:

I'm never told which VM has updates available.

### General notes:

---

**Comment by andrewdavidwong** [comment]
Someone mentioned that they see "highlighting" to indicate which VMs have updates available. I don't see any highlighting, maybe because of the color scheme I'm using. For accessibility reasons, this indication should not depend on highlighting. There should be some text indicating which VMs have updates available.

**Comment by andrewdavidwong** [comment]
I just tried out the default color scheme (and a few others). I never see any highlighting with any of them.

**Comment by marmarek** [comment]
> yet the widget says, "Updates available for 1 qubes."

I think this is what's actually wrong. Looks similar to #4593 
And actually I also see this issue - number of qubes with updates available reported is greater by one, compared to qubes on the list when you launch the updater.

**Comment by andrewdavidwong** [comment]
> I think this is what's actually wrong. Looks similar to #4593
And actually I also see this issue - number of qubes with updates available reported is greater by one, compared to qubes on the list when you launch the updater.

Ok. I was thinking #4667. Either way, though, it's clear that the phenomenon reported here is `not an issue` and instead the actual problem is #4593, #4667, or a new issue.
