### ISSUE TITLE
Display a progress indicator when the system is working

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#4744]
### Qubes OS version:

`R4.0.1`

### Affected component(s): 

Qubes GUI components (manager and widgets)

---

### Steps to reproduce the behavior:

Example:
1. Open the settings for a qube.
2. Change a bunch of configuration options.
3. Click "Apply" or "OK."

### Expected behavior:

There's some visual indication that the system is working. (I assume it's executing a bunch of `qvm-prefs` commands in the background and such.)

### Actual behavior:

No visual indication that anything is happening. It just seems like the system (or at least that particular GUI tool) is frozen and unresponsive.

### General notes:

When the Qube Manager first starts up, there's a nice progress indicator showing that it's loading. This is great! More like this. (It doesn't always have to be a progress bar, though. For shorter actions, it could just be a spinning icon or cursor, for example.)

---

**Comment by donob4n** [comment]
Ey @marmarta have you done something with this? If not I could work on it this week.

**Comment by marmarta** [comment]
I apologize very much for not answering, I was a bit out of commission for health reasons... and yeah, also not working on it. Sorry again!

**Comment by andrewdavidwong** [comment]
Please feel free to pursue this, @donob4n.

**Comment by donob4n** [comment]
Oh do not worry @marmarta , I am sorry to heart that, hope you feel better soon.

**Comment by donob4n** [comment]
@andrewdavidwong 
Do you think that there are more places where it should show a progress dialog?

**Comment by andrewdavidwong** [comment]
> Do you think that there are more places where it should show a progress dialog?

I'd suggest something like this:

- < 400ms: no indication necessary
- 400ms - 2000ms: cursor icon
- \> 2000ms: progress bar

I haven't timed how long anything takes, and some things may be more hardware-dependent than others. If you're willing to do some testing and timing on "average" hardware, then go with those numbers. If you're unable or unwilling to collect empirical timing data, then I'd just err on the side of caution and make sure everything has at least a cursor icon. We should be able to change the cursor based on what's happening in dom0, but if for some reason we can't, then just adding progress bars to everything (with a minimum on-screen time, so it doesn't just look like a flash), will probably be fine.

**Comment by donob4n** [comment]
QT provides an builtin system (and hardware independent) for only show the progress bar if it delays more than some fixed interval. So last point is fixed with the last commit.

The '400ms-2000ms: interval and cursor icon' sounds great. I didn't think about it, I will add to the PR during this week.
