### ISSUE TITLE
qubes-backup fails on some vms (especially on large ones) while with others it's working fine

### ISSUE THREAD

**Issue by slq32** [QubesOS/qubes-issues#4751]
### Qubes OS version:
R4.0

### Affected component(s):
qubes-backup (both GUI and console)

---

### Steps to reproduce the behavior:

qvm-backup --verbose --yes --passphrase-file pw.txt /bkroot/ vm-name

with or without compression is irrelevant

### Expected behavior:

the progress should reach 100% and the vm should be backed up

### Actual behavior:

the qubes-backup throws an error, sometimes at 20% , other times at 95% (error backing up), and exits with code 1

### General notes:

almost all backed up qubes are running, and as stated in the title, the issues are only with some of them, especially with larger ones. if the qube is stopped, everything goes fine. 

backing up everything using rsync and excluding cow files and volatile.img works even for running vms. it would also be nice to add an option to disable encryption, as probably most people are doing the backups to encrypted drives anyway, and disabling encryption and compression would greatly improve speed.

if this is normal behavior or someone already pointed this issue out, you can close it.

**Comment by andrewdavidwong** [comment]
> the qubes-backup throws an error, sometimes at 20% , other times at 95% (error backing up), and exits with code 1

Please provide the exact error message.

> it would also be nice to add an option to disable encryption, as probably most people are doing the backups to encrypted drives anyway, and disabling encryption and compression would greatly improve speed.

Compression is optional, but the decision to make encryption mandatory in 4.0 was an intentional design choice for security reasons. Encryption overhead should not have a significant performance impact on modern CPUs featuring an AES instruction set.

**Comment by slq32** [comment]
Here is the log:

[root@dom0 user]# qvm-backup --verbose --yes --passphrase-file pw.txt /bkroot/qubes2/ local-stuff
------------------+--------------+--------------+
               VM |         type |         size |
------------------+--------------+--------------+
      local-stuff |           VM |     52.1 GiB | <-- The VM is running, backup will contain its state from before its start!
------------------+--------------+--------------+
      Total size: |                    52.1 GiB |
------------------+--------------+--------------+
VMs not selected for backup:
other vm list comes here 

2019-01-22 09:11:24,792 [MainProcess selector_events.__init__:65] asyncio: Using selector: EpollSelector
Making a backup... 86.05%
Backup error: Failed to archive /var/lib/qubes/appvms/local-stuff/private.img file

the exit code is 1 if it helps

About the encryption, the design decision makes sense, however it's slower then rsync. Maybe it's because of the way qubes-backup handles sparse files ?

**Comment by marmarek** [comment]
>  local-stuff | VM | 52.1 GiB | <-- The VM is running, backup will contain its state from before its start!

This may be a problem. While the feature of backing up running VM works fine for LVM, it may not for file-based VMs. Try shutting it down.

**Comment by slq32** [comment]
If the VM is off, it gets backed up fine. The problem is only with some running VMs (large ones, 10GB+).
Most of them are AppVMs, and one StandaloneVM. The smaller ones get backed up fine, even when running.

**Comment by marmarek** [comment]
The problem is when VM gets modified during the backup. So it makes sense size matters here - the bigger VM, the longer it takes to backup and bigger chance it gets modified in the meantime.

**Comment by slq32** [comment]
I used rsync to "clone" the whole / and /boot (/proc /sys /run /dev excluded) to an external drive, modify fstab, crypttab, initrd and grub2 and i am able to boot the identical system from the external drive.
However you are right, backing up a live VM can lead to several problems. I guess the best way to go would be to write a simple script that shuts down the problematic VMs, backs them up and re-starts them.
 
Thanks for the clarification.
