### ISSUE TITLE
[Installation] with grub2iso doesn't detect RVI/SLAT on AMD Ryzen 2400G

### ISSUE THREAD

**Issue by LoveIsGrief** [QubesOS/qubes-issues#4755]
### Affected component(s):

  - Installer

---

### Steps to reproduce the behavior:

Running a system with Ubuntu 18.04

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: neon
Description:    KDE neon User Edition 5.14
Release:        18.04
Codename:       bionic
```

Using ISO from https://mirrors.edge.kernel.org/qubes/iso/Qubes-R4.0.1-x86_64.torrent

```bash
# install grml for grub2iso
sudo apt-get install grml-rescueboot

# Move ISO to /boot/grml
sudo mv ~/Downloads/Qubes-R4.0.1-x86_64/Qubes-R4.0.1-x86_64.iso /boot/grml

# Update /boot/grub/grub.cfg
sudo update-grub
```

**Modify `/boot/grub/grub.cfg/` to Xen from ISO**

Basically adapted instructions from this [Stackoverflow](https://unix.stackexchange.com/q/427595) to fix the `/dev/root` issue + [this other Stackoverflow](https://superuser.com/a/327782) to boot Xen and not straight `vmlinuz` directly.

My result is here [grub.cfg](https://github.com/QubesOS/qubes-issues/files/2787667/grub.cfg.txt) , but for reproducing the `set root` will have to be modified.

**restart and boot into iso**

### Expected behavior:

 - Graphical installer
 - RVI/SLAT support for CPU

### Actual behavior:

 - X doesn't work with Xen --> `inst.text` has to be added to kernel params
 - RVI/SLAT isn't recognized (see  [xen_cpuinfo.log](https://github.com/QubesOS/qubes-issues/files/2787692/cpuinfo.log)) however it is recognized on Ubuntu 18.04 ([ubuntu_cpuinfo.log](https://github.com/QubesOS/qubes-issues/files/2787702/ubuntu_cpuinfo.log))

### General notes:

**logs**

 - [anaconda.log](https://github.com/QubesOS/qubes-issues/files/2787628/anaconda.log)
 - [ifcfg.log](https://github.com/QubesOS/qubes-issues/files/2787629/ifcfg.log)
 - [lsmod.log](https://github.com/QubesOS/qubes-issues/files/2787630/lsmod.log)
 - [lspci.log](https://github.com/QubesOS/qubes-issues/files/2787631/lspci.log)
 - [program.log](https://github.com/QubesOS/qubes-issues/files/2787632/program.log)
 - [storage.log](https://github.com/QubesOS/qubes-issues/files/2787633/storage.log)
 - [X.log](https://github.com/QubesOS/qubes-issues/files/2787634/X.log)

---

### Related issues:

Possibly #4407

**Comment by andrewdavidwong** [comment]
I'm leaving this open as an installer bug for now, since Qubes should probably recognize RVI/SLAT if Ubuntu recognizes it. However, the devs might decide this is too localized.

**Comment by 0spinboson** [comment]
you don't? It should be under advanced CPU options, CBS or somesuch.

**Comment by andrewdavidwong** [comment]
> @andrewdavidwong , I hope they won't decide it's too localized. I can't be the only person with a 2400G trying to install Qubes.

Understandable. But bear in mind that, according to our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), issues that depend on a specific hardware configuration are too localized for `qubes-issues`, and we typically ask folks to write to the `qubes-users` [mailing list](https://www.qubes-os.org/support/) instead in these cases. `qubes-users` is intended for these sorts of issues and receives much more traffic, which means that such issues are more likely to receive a response there.

**Comment by LoveIsGrief** [comment]
Oh no...mailing lists 😅 Well then, I'm out. I'll close this once I have access to my account and just move on. Mailing lists are not for me.

Thanks for the responses!
