### ISSUE TITLE
Windows HVMs no longer boot after upgrading to xen 4.8.5-1

### ISSUE THREAD

**Issue by ffsec** [QubesOS/qubes-issues#4759]
### Qubes OS version:
R4.0

### Affected component(s):
XEN/Kernel/HVM

### Steps to reproduce the behavior:
Update dom0 with testing repo enabled.
The following packages are updated (at the moment):

Installing:
kernel 4.19.15-1
kernel-qubes-vm  4.19.15-1
perl-Math-BigRat 0.2608.02-289
perl-bignum 0.42-289
Upgrading:
python3-xen 4.8.5-1
qubes-core-dom0 4.0.38-1
qubes-desktop-linux-manager 4.0.14-1
qubes-manager 4.0.27-1
qubes-mgmt-salt-dom0-update 4.0.5-1
xen 4.8.5-1.fc25
xen-hvm 4.8.5-1
xen-hypervisor 4.8.5-1
xen-libs 4.8.5-1
xen-licenses 4.8.5-1
xen-runtime 4.8.5-1
Removing:
kernel 4.14.57-2
kernel-qubes-vm 4.14.57-2

### Expected behavior:
No new issues are introduced.

### Actual behavior:
So far I identified:
1. Graphical boot screen is gone, password prompt and boot is now console only. (not critical)
2. (Windows) HVMs will not boot anymore (error: failed to setup loop device)
I ran into this issue on a working Qubes notebook, my Windows 7 HVM did not boot anymore.

For troubleshooting I performed a clean install of Qubes 4.0.1 on a test machine and updated dom0 with testing repo enabled. After a restart I noticed also number 1 (graphical boot screen gone) and afterwards created a new HVM (Windows). The HVM started like normal and the Windows Installer showed up. After some time the installation medium provided by "--cdrom=" was suddenly missing in the HVM. Windows Installer complained about missing files (obviously). After shutting down the HVM it does not start anymore, just like on the notebook (error: failed to setup loop device).

### General notes:
My guess is, that this is caused by the new xen version and/or kernel, since these issues are gone when I boot with an older xen/kernel version (xen 4.8.4 + Linux 4.14.74-1).
Haven't tested other combinations like latest xen and older kernel or in reverse yet.
Also I did not test if there are any issues with other HVMs that are not Windows-based.

**Comment by DemiMarie** [comment]
The graphical boot screen problem is caused by the updated Linux kernel.  I see the same problem after installing the `kernel-latest` package.

**Comment by andrewdavidwong** [comment]
> So far I identified:
> 1. Graphical boot screen is gone, password prompt and boot is now console only. (not critical)
> 2. (Windows) HVMs will not boot anymore (error: failed to setup loop device)
> I ran into this issue on a working Qubes notebook, my Windows 7 HVM did not boot anymore.
> 
> For troubleshooting I performed a clean install of Qubes 4.0.1 on a test machine and updated dom0 with testing repo enabled. After a restart I noticed also number 1 (graphical boot screen gone) and afterwards created a new HVM (Windows). The HVM started like normal and the Windows Installer showed up. After some time the installation medium provided by "--cdrom=" was suddenly missing in the HVM. Windows Installer complained about missing files (obviously). After shutting down the HVM it does not start anymore, just like on the notebook (error: failed to setup loop device).

Could you please report each bug in a separate issue? [Each issue should be about a single thing.](https://www.qubes-os.org/doc/reporting-bugs/#every-issue-must-be-about-a-single-actionable-thing)

I'll retitle this issue to make it only about Windows HVMs no longer starting. Please open separate issues for the other problems (if there aren't already existing issues for them).

If you have the ability to test whether the problem is with all HVMs or only Windows HVMs, that would be helpful.

**Comment by 0spinboson** [comment]
I think I'm also affected by this, though I've been affected longer than the release of 4.8.5, so I'm guessing it's due to kernel more than Xen version.

**Comment by ffsec** [comment]
I'm using kernel-latest for over a week now and besides the fact that the graphical boot screen is gone, I haven't seen any side affects so far. Today I thought, i could look into this issue some more and installed xen 4.8.5 again. Surprisingly the Windows vms are still working. Haven't tried installing a new HVM using "--cdrom=" yet. Since kernel-latest is newer than the testing kernel packages, this might be the reason why it's working now.
