### ISSUE TITLE
port Qubes Debian Template Build Process to Multistrap or Similar for better Build Security

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#4760]
Current situation and problem:

`Qubes builder` -> `build Debian base image using debootstrap with mirror "packages.debian.org" but not "security.debian.org" because debootstrap can build only from one APT source` -> `might fetch vulnerable APT version like with DSA 4371` -> `vulnerable APT is used to apt-get update and dist-upgrade Debian base image using "packages.debian.org" and "security.debian.org"` -> `at this point the template build might be compromised`

----

Proposed solution:

It would be better to use multistrap because multistrap can create Debian base images using multiple APT sources, "packages.debian.org" and "security.debian.org".

`Qubes builder` -> `build Debian base image using multistrap with mirror "packages.debian.org"  and "security.debian.org"` -> `fetch security fixed packages only`

This doesn't only fetch security fixed APT but also never installs any already security fixed packages other than APT (think APT dependencies or anything other that is involved in processing code during installation such as libcurl perhaps).

----

Why? To be prepared for the next apt vulnerability.

* https://www.debian.org/security/2019/dsa-4371
* https://www.debian.org/security/2016/dsa-3733

**Comment by adrelanos** [comment]
Quote https://wiki.debian.org/RISC-V (different context perhaps!) but it mentions `mmdebstrap` as alternative to `multistrap`.

> At the time of writing, mmdebstrap is still rather new, but it provides a largely debootstrap-compatible user interface and can be used as a drop-in replacement for debootstrap in many cases. multistrap already exists for many years, but it behaves quite a bit different from debootstrap and a chroot created with multistrap requires several manual adjustments that aren't necessary when using mmdebstrap. Unless there are specific reasons for using multistrap, the use of mmdebstrap is therefore recommended.

**Comment by unman** [comment]
We already have #4447 which covers this.
The problem with multistrap is, as far as I know, that it only works under Debian - is multistrap available for Fedora, and does it work? Doesn't seem to be available.

**Comment by adrelanos** [comment]
mmdebstrap / multistrap is unlikely to become available for non-Debian based distributions since it requires apt-get to be installed.

Is throw out Fedora still the plan?

Is it ok to require Debian templates being created using Debian based rather than Fedora based templates?

**Comment by 0spinboson** [comment]
given that Qubes is currently someone to make fc29 ready for dom0 use in 4.1, I doubt it?

**Comment by unman** [comment]
I dont think that there is any plan to replace Fedora with Debian. In dom0 if Fedora goes, it's likely to be replaced with something much smaller and tighter.
In the build environment, there's no requirement for that to be Fedora at all, but the necessary porting hasn't been done. Its been a while since I tried it but it shouldn't be insuperable, particularly as the actual builds are done in chroot. But the code is very Fedora-centric, and a lot is unnecessary for Debian builds.

**Comment by marmarek** [comment]
> Is it ok to require Debian templates being created using Debian based rather than Fedora based templates?

No, it is not. Building Qubes should _not_ require running Qubes. It should be possible to get sufficiently recent distribution to build Qubes, including all supported templates. Currently this works on Debian and Fedora. With small tweaks probably others too. But introducing hard dependency on specific distribution for building is a bad idea.

**Comment by unman** [comment]
@adrelanos @andrewdavidwong  Since the meat of this is covered in #4447, and the proposed solution wont be implemented per @marmarek comment, I think this should be closed.

**Comment by andrewdavidwong** [comment]
Closing as "won't do." If anyone has a new reason for why this should be done, please leave a comment, and we'll be happy to take another look. Thank you.
