### ISSUE TITLE
Reinstall the target TemplateVM in dom0

### ISSUE THREAD

**Issue by n0sign4l** [QubesOS/qubes-issues#4765]
### Qubes OS version:

Qubes release 4.0 (R4.0)

### Affected component(s):

Reinstall the target TemplateVM in dom0 in my case debian-9 and whonix 14

---

### Steps to reproduce the behavior:
I'm following this guide... https://www.qubes-os.org/news/2019/01/23/qsb-46/

Everything got well till point 4, during `sudo qubes-dom0-update --enablerepo=<optional-additional-repo> \ <template-package-name>`

When I execute `sudo qubes-dom0-update --enablerepo=qubes-templates-community \ qubes-template-whonix-gw-14` I get: 'No match argument for: qubes-template-whonix-gw-14 Error: unable to find a match' The same happens with `qubes-template-debian-9` if I try with `qubes-template-debian-8` I download the VULNERABLE template.......

### Expected behavior:

I should be able to download the template for qubes-template-whonix-gw-14 and qubes-template-debian-9 

### Actual behavior:

I'm not able to download the new templates, I get this error:
'No match argument for: qubes-template-whonix-gw-14 
Error: unable to find a match'

### General notes:

Everything is up to date!
@marmarek 

---

**Comment by leonardoporp** [comment]
I have the same issue

**Comment by marmarek** [comment]
Make sure that old version of the template is removed - see step 3 in the QSB.
Alternatively, you can try in-place template upgrade by adding `--action=upgrade` option.

**Comment by leonardoporp** [comment]
I have completed step 3

**Comment by marmarek** [comment]
You can verify the template package is really removed with: `rpm -q qubes-template-whonix-gw-14` (adjust template name appropriately for other templates).

**Comment by andrewdavidwong** [comment]
Filing this as an issue to further clarify the instructions in the QSB, if necessary.

**Comment by leonardoporp** [comment]
![img_20190127_135953](https://user-images.githubusercontent.com/44808354/51801288-0643ce80-223c-11e9-9c1b-7553107ea083.jpg)


If I run as I said before rpm -q ... I get qubes-template-whonix.... (With the old vulnerable version)

**Comment by marmarek** [comment]
Oh, so whonix-gw-14 template is removed, but its _package_ is still there. That shouldn't happen in theory... But since it happened, you can cleanup it by removing package with: `rpm -e --noscripts qubes-template-whonix-gw-14`

**Comment by n0sign4l** [comment]
Ok, with that command I'm able to download the template, the problem is that running
`sudo qubes-dom0-update --enablerepo=qubes-templates-community \ qubes-template-whonix-gw-14`
I get prompted installing: 'qubes-template-whonix-gw-14' Arch:'noarch' and the version is: "4.0.1-201811291216" and the repository is obv: "qubes-template-community"

I do not understand why it downloads always the old vulnerable template...

**Comment by marmarek** [comment]
You should add `--enablerepo=qubes-templates-community-testing`

**Comment by leonardoporp** [comment]
Same issue even with community-testing

![img_20190127_155307 2](https://user-images.githubusercontent.com/44808354/51802582-ec11ec80-224b-11e9-8090-59ac7c6b5e76.jpg)

**Comment by marmarek** [comment]
Here you're downloading debian-9 template, not whonix-gw-14. Fixed debian-9 is in qubes-templates-itl-testing repository.

**Comment by n0sign4l** [comment]
Right now everything works well, for me you can close this issue.
Thanks a lot for your help

**Comment by andrewdavidwong** [comment]
> Will you publish a tweet when whonix and Debian will be available in a stable release (not testing repo)

We don't make a separate announcement when packages move from testing to stable. However, you can always subscribe to the appropriate issue to be notified when it does.

**Comment by andrewdavidwong** [comment]
> Right now everything works well, for me you can close this issue.
> Thanks a lot for your help

Looks like this is an edge case that doesn't merit updating the QSB. Closing this as "resolved." If you believe the issue is not yet resolved, or if anyone is still affected by this issue, please leave a comment, and we'll be happy to reopen this. Thank you.

**Comment by n0sign4l** [comment]
Hey @marmarek when I'm reinstalling whonix in Qubes I encounter some errors...

When I run `sudo qubesctl state.sls qvm.anon-whonix` I get:
"sudo qubesctl state.sls qvm.anon-whonix
[WARNING ] /var/cache/salt/minion/extmods/states/ext_state_qvm.py:142: DeprecationWarning: BaseException.message has been deprecated as of Python 2.6
  status = Status(retcode=1, result=False, stderr=err.message + '\n')

[ERROR   ] ====== ['features'] ======
Virtual Machine does not exist!

====== ['tags'] ======
[SKIP] Skipping due to previous failure!
[ERROR   ] ====== ['present'] ======
====== stderr ======
/usr/bin/qvm-create whonix-ws-14-dvm --class=AppVM --template=whonix-ws-14 --label=red 
app: Error creating VM: Got empty response from qubesd. See journalctl in dom0 for details.

====== ['prefs'] ======
Virtual Machine does not exist!

====== ['features'] ======
[SKIP] Skipping due to previous failure!

====== ['tags'] ======
[SKIP] Skipping due to previous failure!
local:
----------
          ID: template-whonix-ws-14
    Function: pkg.installed
        Name: qubes-template-whonix-ws-14
      Result: True
     Comment: Package qubes-template-whonix-ws-14 is already installed
     Started: 20:40:16.314620
    Duration: 989.251 ms
     Changes:   
----------
          ID: whonix-ws-tag
    Function: qvm.vm
        Name: whonix-ws-14
      Result: False
     Comment: ====== ['features'] ======
              Virtual Machine does not exist!
              
              ====== ['tags'] ======
              [SKIP] Skipping due to previous failure!
     Started: 20:40:17.305166
    Duration: 11.344 ms
     Changes:   
----------
          ID: whonix-ws-update-policy
    Function: file.prepend
        Name: /etc/qubes-rpc/policy/qubes.UpdatesProxy
      Result: True
     Comment: File /etc/qubes-rpc/policy/qubes.UpdatesProxy is in correct state
     Started: 20:40:17.318325
    Duration: 2.559 ms
     Changes:   
----------
          ID: whonix-get-date-policy
    Function: file.prepend
        Name: /etc/qubes-rpc/policy/qubes.GetDate
      Result: True
     Comment: File /etc/qubes-rpc/policy/qubes.GetDate is in correct state
     Started: 20:40:17.320980
    Duration: 1.304 ms
     Changes:   
----------
          ID: template-whonix-gw-14
    Function: pkg.installed
        Name: qubes-template-whonix-gw-14
      Result: True
     Comment: Package qubes-template-whonix-gw-14 is already installed
     Started: 20:40:17.322375
    Duration: 0.39 ms
     Changes:   
----------
          ID: whonix-gw-tag
    Function: qvm.vm
        Name: whonix-gw-14
      Result: True
     Comment: ====== ['features'] ======
              [SKIP] Feature already in desired state: ENABLE 'whonix-gw' = Enabled
              
              ====== ['tags'] ======
              [SKIP] All requested tags already set: created-by-dom0,whonix-updatevm
     Started: 20:40:17.322841
    Duration: 87.258 ms
     Changes:   
----------
          ID: whonix-gw-update-policy
    Function: file.prepend
        Name: /etc/qubes-rpc/policy/qubes.UpdatesProxy
      Result: True
     Comment: File /etc/qubes-rpc/policy/qubes.UpdatesProxy is in correct state
     Started: 20:40:17.410211
    Duration: 1.607 ms
     Changes:   
----------
          ID: sys-net
    Function: qvm.exists
      Result: True
     Comment: /usr/bin/qvm-check sys-net 
              VM sys-net exists None
     Started: 20:40:17.411922
    Duration: 225.185 ms
     Changes:   
----------
          ID: sys-firewall
    Function: qvm.exists
      Result: True
     Comment: /usr/bin/qvm-check sys-firewall 
              VM sys-firewall exists None
     Started: 20:40:17.637526
    Duration: 224.791 ms
     Changes:   
----------
          ID: sys-whonix
    Function: qvm.exists
      Result: True
     Comment: /usr/bin/qvm-check sys-whonix 
              VM sys-whonix exists None
     Started: 20:40:17.862723
    Duration: 233.229 ms
     Changes:   
----------
          ID: whonix-ws-14-dvm
    Function: qvm.vm
      Result: False
     Comment: ====== ['present'] ======
              ====== stderr ======
              /usr/bin/qvm-create whonix-ws-14-dvm --class=AppVM --template=whonix-ws-14 --label=red 
              app: Error creating VM: Got empty response from qubesd. See journalctl in dom0 for details.
              
              ====== ['prefs'] ======
              Virtual Machine does not exist!
              
              ====== ['features'] ======
              [SKIP] Skipping due to previous failure!
              
              ====== ['tags'] ======
              [SKIP] Skipping due to previous failure!
     Started: 20:40:18.100405
    Duration: 667.818 ms
     Changes:   
----------
          ID: qvm-appmenus --update whonix-ws-14-dvm
    Function: cmd.run
      Result: False
     Comment: One or more requisite failed: qvm.whonix-ws-dvm.whonix-ws-14-dvm
     Changes:   
----------
          ID: anon-whonix
    Function: qvm.vm
      Result: False
     Comment: One or more requisite failed: qvm.whonix-ws-dvm.whonix-ws-14-dvm
     Changes:   

Summary for local
------------
Succeeded: 9
Failed:    4
------------
Total states run:    13
Total run time:   2.445 s
DOM0 configuration failed, not continuing"


and when I run `sudo qubesctl state.sls qvm.whonix-ws-dvm` I get:
"sudo qubesctl state.sls qvm.whonix-ws-dvm
[WARNING ] /var/cache/salt/minion/extmods/states/ext_state_qvm.py:142: DeprecationWarning: BaseException.message has been deprecated as of Python 2.6
  status = Status(retcode=1, result=False, stderr=err.message + '\n')

[ERROR   ] ====== ['features'] ======
Virtual Machine does not exist!

====== ['tags'] ======
[SKIP] Skipping due to previous failure!
[ERROR   ] ====== ['present'] ======
====== stderr ======
/usr/bin/qvm-create whonix-ws-14-dvm --class=AppVM --template=whonix-ws-14 --label=red 
app: Error creating VM: Got empty response from qubesd. See journalctl in dom0 for details.

====== ['prefs'] ======
Virtual Machine does not exist!

====== ['features'] ======
[SKIP] Skipping due to previous failure!

====== ['tags'] ======
[SKIP] Skipping due to previous failure!
local:
----------
          ID: template-whonix-ws-14
    Function: pkg.installed
        Name: qubes-template-whonix-ws-14
      Result: True
     Comment: Package qubes-template-whonix-ws-14 is already installed
     Started: 20:39:36.977881
    Duration: 988.528 ms
     Changes:   
----------
          ID: whonix-ws-tag
    Function: qvm.vm
        Name: whonix-ws-14
      Result: False
     Comment: ====== ['features'] ======
              Virtual Machine does not exist!
              
              ====== ['tags'] ======
              [SKIP] Skipping due to previous failure!
     Started: 20:39:37.994290
    Duration: 30.579 ms
     Changes:   
----------
          ID: whonix-ws-update-policy
    Function: file.prepend
        Name: /etc/qubes-rpc/policy/qubes.UpdatesProxy
      Result: True
     Comment: File /etc/qubes-rpc/policy/qubes.UpdatesProxy is in correct state
     Started: 20:39:38.041067
    Duration: 20.863 ms
     Changes:   
----------
          ID: whonix-get-date-policy
    Function: file.prepend
        Name: /etc/qubes-rpc/policy/qubes.GetDate
      Result: True
     Comment: File /etc/qubes-rpc/policy/qubes.GetDate is in correct state
     Started: 20:39:38.062264
    Duration: 16.989 ms
     Changes:   
----------
          ID: template-whonix-gw-14
    Function: pkg.installed
        Name: qubes-template-whonix-gw-14
      Result: True
     Comment: Package qubes-template-whonix-gw-14 is already installed
     Started: 20:39:38.079366
    Duration: 0.414 ms
     Changes:   
----------
          ID: whonix-gw-tag
    Function: qvm.vm
        Name: whonix-gw-14
      Result: True
     Comment: ====== ['features'] ======
              [SKIP] Feature already in desired state: ENABLE 'whonix-gw' = Enabled
              
              ====== ['tags'] ======
              [SKIP] All requested tags already set: created-by-dom0,whonix-updatevm
     Started: 20:39:38.079857
    Duration: 81.321 ms
     Changes:   
----------
          ID: whonix-gw-update-policy
    Function: file.prepend
        Name: /etc/qubes-rpc/policy/qubes.UpdatesProxy
      Result: True
     Comment: File /etc/qubes-rpc/policy/qubes.UpdatesProxy is in correct state
     Started: 20:39:38.161293
    Duration: 1.653 ms
     Changes:   
----------
          ID: sys-net
    Function: qvm.exists
      Result: True
     Comment: /usr/bin/qvm-check sys-net 
              VM sys-net exists None
     Started: 20:39:38.163042
    Duration: 222.168 ms
     Changes:   
----------
          ID: sys-firewall
    Function: qvm.exists
      Result: True
     Comment: /usr/bin/qvm-check sys-firewall 
              VM sys-firewall exists None
     Started: 20:39:38.385618
    Duration: 223.004 ms
     Changes:   
----------
          ID: sys-whonix
    Function: qvm.exists
      Result: True
     Comment: /usr/bin/qvm-check sys-whonix 
              VM sys-whonix exists None
     Started: 20:39:38.609006
    Duration: 238.89 ms
     Changes:   
----------
          ID: whonix-ws-14-dvm
    Function: qvm.vm
      Result: False
     Comment: ====== ['present'] ======
              ====== stderr ======
              /usr/bin/qvm-create whonix-ws-14-dvm --class=AppVM --template=whonix-ws-14 --label=red 
              app: Error creating VM: Got empty response from qubesd. See journalctl in dom0 for details.
              
              ====== ['prefs'] ======
              Virtual Machine does not exist!
              
              ====== ['features'] ======
              [SKIP] Skipping due to previous failure!
              
              ====== ['tags'] ======
              [SKIP] Skipping due to previous failure!
     Started: 20:39:38.908707
    Duration: 696.01 ms
     Changes:   
----------
          ID: qvm-appmenus --update whonix-ws-14-dvm
    Function: cmd.run
      Result: False
     Comment: One or more requisite failed: qvm.whonix-ws-dvm.whonix-ws-14-dvm
     Changes:   

Summary for local
------------
Succeeded: 9
Failed:    3
------------
Total states run:    12
Total run time:   2.520 s
DOM0 configuration failed, not continuing"

What should i do to fix it?

**Comment by marmarek** [comment]
Looks like `whonix-ws-14` template is removed but its package `qubes-template-whonix-ws-14` is still there. Verify with `qvm-check whonix-ws-14` - if that template is indeed gone, then remove the package with `sudo rpm -e --noscripts qubes-template-whonix-ws-14`. Check `whonix-gw-14` with the same procedure. Then retry `qubesctl` command.
