### ISSUE TITLE
How to translate the 404 error page?

### ISSUE THREAD

**Issue by tokideveloper** [QubesOS/qubes-issues#4769]
The problem here is that there is only one 404 error page for the whole website [AFAIK](https://jekyllrb.com/tutorials/custom-404-page/).

**Comment by tokideveloper** [comment]
My suggestion: Print an error message in all offered target languages concatenized to the 404 page. Thus, everyone can read it.

The error message could be written in English in a special `404_error_message.txt` file. We could then upload it to Transifex and proceed with the results as already described.

**Comment by esote** [comment]
For what it's worth, it looks like not even Google translates their 404 error page. For example: [https://www.google.de/qubes-os](https://www.google.de/qubes-os)

**Comment by marmarta** [comment]
I think we can close this, we don't actually need to translate 404 page (we don't have to be better at localization than Google :) - and the added value from it is insignificant.
