### ISSUE TITLE
qubes-qmemman fails to start, causing all VMs to be unbootable

### ISSUE THREAD

**Issue by lunarthegrey-alt** [QubesOS/qubes-issues#4772]
### Qubes OS version:
R4.0

### Affected component(s):
qubes-qmemman

---

### Steps to reproduce the behavior:
- Change the `Minimal qube memory` and `dom0 memory boost` settings in Qubes Global Settings.
- Check the /var/log/boot.log after rebooting, notice that qmemman failed to start. Check the status of the qubes-qmemman service afterwards.

### Expected behavior:
qmemman starts with the values you put into the global settings.

### Actual behavior:
qmemman fails to start with ANY value I put into the global settings. Below was typed by hand because I can't start any VMs regardless of the values I have set.

```
sys.exit(main())
File "/usr/lib/python3.5/site-packages/qubes/tools/qmemmand.py", line 261, in main
qubes.utils.parse_size(config.get('global', 'vm-min-mem'))
File "/usr/lib/pyhton3.5/site-packages/qubes/utils.py", line 107, in parse_size
raise qubes.exc.QubesException("Invalid size: {0}.".format(size))
qubes.exc.QubesException: Invalid size: 543 MIB.
qubes-qmemman.service:Main process exited, code=exited, status=1/FAILURE
Failed to start Qubes memory management daemon.
qubes-qmemman.service: Unit entered failed state.
qubes-qmemman.service: Failed with result 'exit-code'.
```

### General notes:
I've tried several values, none of them work. Each time I've tried restarting the qubes-qmemman service and it fails with the same error no matter how much I put. 100 MiB, 256 MiB, 500 MiB, 512 MiB, 1000 MiB, 1024 MiB.

---

### Related issues:
Couldn't find any related issues.

**Comment by lunarthegrey-alt** [comment]
Tagging @marmarek @andrewdavidwong due to the importance of this.

I recently installed qubes-desktop-linux-manager 4.0.14 and qubes-manager 4.0.27 because of https://www.qubes-os.org/news/2019/01/23/qsb-46/ from `qubes-dom0-security-testing`, unsure if this is related.

**Comment by marmarek** [comment]
Should be fixed by [qubes-core-dom0 4.0.38](https://github.com/QubesOS/updates-status/issues/854), still in current-testing repo. You can try this:
```
sudo qubes-dom0-update --enablerepo=qubes*current-testing qubes-core-dom0
```

**Comment by lunarthegrey-alt** [comment]
> Should be fixed by [qubes-core-dom0 4.0.38](https://github.com/QubesOS/updates-status/issues/854), still in current-testing repo. You can try this:
> 
> ```
> sudo qubes-dom0-update --enablerepo=qubes*current-testing qubes-core-dom0
> ```

Sadly I cannot boot any VMs because of it, so I don't have an UpdateVM available to run that. Is there any way I would be able to boot VMs even without qmemman running? Thank you for the quick response.

**Comment by andrewdavidwong** [comment]
Lorenzo experienced the same problem and [wrote](https://groups.google.com/d/msg/qubes-users/5D8AxG3jtdw/CqyWjGEiGgAJ):
> Well, thanks to the help of someone more knowledgeable than me, I was able to fix it.
> The trick was to edit /etc/qubes/qmemman.conf.
> In the line vm-min-mem = 190MIB replace with 190M
> In the line dom0-mem-boost = 333MIB replace with 333M.

Others also experienced the problem and reported that this solution worked for them:

https://groups.google.com/d/topic/qubes-users/HMt9bZRnt-k/discussion

**Comment by lunarthegrey-alt** [comment]
Thank you @andrewdavidwong and @marmarek, you are life savers. Changing it from MiB to MB worked. I had no idea that file existed.

Installing that update now.

**Comment by lunarthegrey-alt** [comment]
The update fixed the issue!

**Comment by xftroxgpx** [comment]
The "bug" was present but inactive since a commit of Mar 24, 2011:
https://github.com/QubesOS/qubes-core-admin/commit/0962eab45ab4900a0a5107d7b45c51d760371f8e#diff-41cc757a2554a894db128529bdadb6e0R32
which assumes that all in the list of `units` are already uppercase.

It was only activated since the addition of things like `MiB` which contained lowercase chars, in a commit from Mar 10, 2016:
https://github.com/QubesOS/qubes-core-admin/commit/e0686e1e02a6362df7cd509283b8548fe573a415#diff-aafdee9ab4063d8674fcea40c7d03d4aL91

The fix is in a commit of Jan 17 2018: https://github.com/QubesOS/qubes-core-admin/commit/d934e811#diff-aafdee9ab4063d8674fcea40c7d03d4aR103
and only landed in stable repo on Feb 11th 2018, as per: https://github.com/QubesOS/updates-status/issues/854#issuecomment-462361471
