### ISSUE TITLE
Win7 standalone, copy-to/copy-from not working

### ISSUE THREAD

**Issue by wernerGibbel** [QubesOS/qubes-issues#4773]
### Qubes OS version:
qubes release 4.0 (R4.0)

### Affected component(s):
 Data-System of Win7/Qubes  

---

### Steps to reproduce the behavior:

- install Win7
- install QWT
- start Win7 (if VM is running, Statebutton is yellow, not green)
- copy-to/from works everywhere, but not for Win7, can't copy to or from Win7

user@dom0$ qvm-copy-to-vm win7 /home/user/Desktop/file.zip
gives error

### Expected behavior:

- normal file transfer between win7 and other

### Actual behavior:

user@dom0$ qvm-copy-to-vm win7 /home/user/Desktop/file.zip
connect: No such file or directory
E0F

### General notes:

Win7 starts with GUI, since now, everything works stable and fine
but not the filte transfers

after the installation of QWT, nothing hast changed. is there a test, if its actual working?

note: i had to shutdown every single VM, except dom0 to start win7VM because of the memory
is that the base of the problem?

---

### Related issues:

not sure...

**Comment by wernerGibbel** [comment]
has anybody an idea? 

did the whole Windows HVM Standalone & QWT installation process again now, no errors, seems to work fine, but.. same result

**Comment by marmarek** [comment]
Check `qvm-features win7` command in dom0 - it should list, among other things, `qrexec` with value `1`. If not, add it manually with `qvm-features win7 qrexec 1` and restart the qube.

**Comment by wernerGibbel** [comment]
Hello marmarek, 
thanks for the try. 

there was indeed no qrexec entry. 
$qvm-features win7
qubesmanager.maxmem_value 2646

that was all i'd get.

i added qrexec 1, like you told. and it shows up, when list the features again. 

now when i tried copy-to-vm again, the process starts without error. 
after time..
win7 crashes with the error: 
domain has failed to start: cannot connect to qrexec_agent for 300secs.
win7 starts again by it's own. 
this process loops. startup, crash, etc.
the copy-to process in dom0 shows nothing but that its working. 

can't find any IncomingQubes in Windows. not at documents, not at sys32 etc. 

thanks & greetings

**Comment by wernerGibbel** [comment]
error says also:
look at /var/log/xen/console/guest-win7.log
- file is empty.

**Comment by marmarek** [comment]
First, remove back that `qrexec` entry (`qvm-features -D win7 qrexec`).
Looks like qrexec is not installed at all. Did you got any errors while installing QWT? Which version?

**Comment by wernerGibbel** [comment]
ok, i changed it back. 

qubes-windows-tools-4.0.1-3.noarch is already installed

no, i had no errors during the installation, but
i had no notice of the installation process at all. 
when i qvm-start win7 --install-windows-tools 
win7 just started 'normal' and there was no change. 
but.. no errors

**Comment by marmarek** [comment]
Just using `--install-windows-tools` option is not enough. You actually need to launch the installed inside the VM. See https://www.qubes-os.org/doc/windows-tools/

**Comment by wernerGibbel** [comment]
oh oh.. 
i'm afraid i found my mistake. .

will inform you in a few minutes...

**Comment by wernerGibbel** [comment]
nope.. once again. 
i installed QWT again, and nothing changed.

**Comment by wernerGibbel** [comment]
oh sorry, i didn't see. 
i installed it within the win7vm too. 

same error when trying to copy-to-vm. E0F, no such directory. no QubesIncoming directory.
but no errors during installation

**Comment by kschubitz** [comment]
It's working fine for me, following these steps:
Follow summary at: https://www.qubes-os.org/doc/windows-vm/#qubes-40---windows-vm-installation
When installed and working, install all Windows Updates (SP1 fully updated)
Then do "bcdedit /set testsigning on" as Administrator and shutdown.
Install QWT inside Windows HVM. When being asked to restart during setup, make sure to select no (will reboot later) and go on with the setup. Also don't format anything if being asked, just ignore these dialogs. After installing several drivers, you should see the final "finished" screen of the installer. Now reboot.
If everything went well, you should now see console entries during the next boot like "moving users folder" etc.
After the final reboot you should be good to go.

Also worth to mention:
https://github.com/QubesOS/qubes-issues/issues/3585
https://www.qubes-os.org/doc/windows-template-customization/

**Comment by kschubitz** [comment]
Did you name the Windows user "user"? Otherwise see Issue 2 in https://github.com/QubesOS/qubes-issues/issues/3585

**Comment by wernerGibbel** [comment]
i noticed an anomaly. 
at the final start after installation of QWT, the windows repair center pops up and tries to repair something. after that it boots again and baff. no result, but vm runs.

**Comment by marmarek** [comment]
have you installed windows updates before QWT? Otherwise windows usually crash on boot and windows repair undo QWT installation...

**Comment by wernerGibbel** [comment]
sounds like the right direction. 

i haven't. i have an win7.iso with sp1 installed and updates to MAR2013. 
thought this would be enough.
is it not?

**Comment by kschubitz** [comment]
I already mentioned this before, install every Windows Update until everything is up to date. After each reboot do another search for Windows Update and install also new ones until there are no more Updates left.
For me there were about 200 Updates, which took hours. So the first thing I did afterwards was creating a backup so I don't have to do that again.
If that doesn't help, which edition of Windows 7 did you install exactly? 64-bit?

**Comment by marmarek** [comment]
You can see attempts at identifying which updates are really needed here: https://github.com/QubesOS/updates-status/issues/598
I'd recommend simply installing all available updates (it will take time).

**Comment by andrewdavidwong** [comment]
Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this does not appear to be suitable for `qubes-issues`. We ask that you please send this to the `qubes-users` [mailing list](https://www.qubes-os.org/support/) instead. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a brief comment explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.

**Comment by wernerGibbel** [comment]
Hello there, 
after 2 retries i just have done it. 

Like you said, it took nearly a day for the over 200 updates. 
Now, everything workes fine.
It was just a non-right-reading-of-the-manual problem, sorry for that.

Thanks for your help marmarek and kschubitz.
this is a good project, thanks for working on it in general.

one last question, if there's somebody left:
At the installation i noticed that, with all that updating, it would have been better with a even bigger root device. my root iss now filled with 22,9g, just for win7 Ult x64. 
I already cleared the update download files 'SoftwareDistribution".
is that size normal?


thanks again, have a nice day
