### ISSUE TITLE
weird networking issue

### ISSUE THREAD

**Issue by slq32** [QubesOS/qubes-issues#4774]
### Qubes OS version:
R4.0

### Affected component(s):

networking

---

### Steps to reproduce the behavior:

transfer from local network with wget over gigabit connection

### Expected behavior:

transfer speed should be ~100MB/s

### Actual behavior:

transfer speed is ~50MB/s

### General notes:

the laptop is a Dell Latitude E7470, Intel NIC.

the setup is work vm - firewall vm - hw net (where the NIC is attached)

from hw-net:

    wget -O /dev/null 192.168.10.10/test.img
    Length: 2097152000 (2.0G)
    /dev/null            32%[=====>              ] 656.13M   109MB/s    eta 12s

from sys-firewall:

    wget -O /dev/null 192.168.10.10/test.img
    Length: 2097152000 (2.0G)
    /dev/null            35%[======>             ] 711.57M  74.5MB/s    eta 17s

from any other VM behind sys-firewall:

    wget -O /dev/null 192.168.10.10/test.img
    Length: 2097152000 (2.0G)
    /dev/null            32%[=====>              ] 647.21M  52.5MB/s    eta 25s

notice the speed decrease ... 
however, from another host in the same network:

from hw-net:

    wget -O /dev/null 192.168.10.92/test.img
    Length: 2097152000 (2.0G)
    /dev/null            21%[===>                ] 439.47M   111MB/s    eta 14s

from sys-firewall:

    wget -O /dev/null 192.168.10.92/test.img
    Length: 2097152000 (2.0G)
    /dev/null            42%[=======>            ] 850.57M   107MB/s    eta 11s

from any other VM behind sys-firewall:

    wget -O /dev/null 192.168.10.92/test.img
    Length: 2097152000 (2.0G)
    /dev/null            47%[========>           ] 952.07M   104MB/s    eta 11s

both .10 and .92 are in the same LAN, and between them and from hw-net i get ~100MB/s. The only problem is from the VMs behind hw-net , and for that particular host (.10)

if it matters , the NIC on the laptop is:

       description: Ethernet interface
       product: Ethernet Connection I219-LM
       vendor: Intel Corporation
       physical id: 6
       bus info: pci@0000:00:06.0
       logical name: ens6
       version: 21
       serial: xx:xx:xx:xx:xx:xx
       size: 1Gbit/s
       capacity: 1Gbit/s
       width: 32 bits
       clock: 33MHz
       capabilities: pm msi bus_master cap_list ethernet physical tp 10bt 10bt-fd 100bt 100bt-fd 1000bt-fd autonegotiation
       configuration: autonegotiation=on broadcast=yes driver=e1000e driverversion=3.2.6-k duplex=full firmware=0.13-3 ip=192.168.10.54 latency=64 link=yes multicast=yes port=twisted pair speed=1Gbit/s
       resources: irq:91 memory:f2000000-f201ffff

nic on the .10 host:

       description: Ethernet interface
       product: 82599ES 10-Gigabit SFI/SFP+ Network Connection
       vendor: Intel Corporation
       physical id: 0
       bus info: pci@0000:03:00.0
       logical name: ens1f0
       version: 01
       serial: xx:xx:xx:xx:xx:xx
       size: 10Gbit/s
       width: 64 bits
       clock: 33MHz
       capabilities: pm msi msix pciexpress vpd bus_master cap_list rom ethernet physical fibre
       configuration: autonegotiation=off broadcast=yes driver=ixgbe driverversion=4.2.1-k duplex=full firmware=0x2b2c0001 ip=192.168.10.10 latency=0 link=yes multicast=yes speed=10Gbit/s
       resources: irq:227 memory:f0a00000-f0a7ffff ioport:d020(size=32) memory:f0c00000-f0c03fff memory:f0a80000-f0afffff memory:f0c04000-f0d03fff memory:f0d04000-f0e03fff

hw-net is HVM, with 2048MB RAM, no memory balancing, 4 VCPUs, and sys-firewall is PVH, 2048-4000MB RAM, memory balancing, 4 VCPUs.

The weird thing is that this happens only with that specific host, and from hw-net i get the full speed ... 

I am not really sure this is a Qubes issue, maybe someone has an idea ... 

---

**Comment by andrewdavidwong** [comment]
Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this does not appear to be suitable for `qubes-issues`. We ask that you please send this to the `qubes-users` [mailing list](https://www.qubes-os.org/support/) instead. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a brief comment explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.
