### ISSUE TITLE
Persistent USB device attach does not reattach when device reconnected

### ISSUE THREAD

**Issue by Eric678** [QubesOS/qubes-issues#4780]
### Qubes OS version:
R4.0.1

### Affected component(s):
dom0 ?

---

### Steps to reproduce the behavior:
In dom0 with USB device connected:
`qvm-usb at -p personal sys-usb:....`
then disconnect and reconnect the USB device.

### Expected behavior:
When the device is disconnected the front device is dropped from the appVM and when it is reconnected the front device is recreated with whatever processing hangs off it (mount, notify CUPS etc) run as before - exactly as an out of the box Fedora installation would, once up.

### Actual behavior:
Reconnection does not recreate the front device - it looks attached fine in `qvm-usb` and the devices tray widget shows it attached however the front device in the appVM is not present and it is not showing in `lsusb` in the appVM either.

### General notes:
Once in this state you are stuck and have to restart the appVM to get your device back.
Currently persistent USB attaches are only useful for devices that never get disconnected or switched off.
For transitory devices one has to manually attach the device every time it is connected - quite often if it is a  serial port adapter being used for programming microcontrollers that gets disconnected (by its reset) every time a device is plugged in for programming - always the same attach required.
Or a USB printer that is left switched off most of the time, but is always in the same place.

---

### Related issues:
While I was testing my devices tray widget crashed.  Not sure why and only saw it once. I restarted it using `python3 -mqui.tray.devices` in dom0 and it seemed OK, except complaining not connected to dbus (whenever it wanted to notify I presume).

**Comment by andrewdavidwong** [comment]
Related: #3437

**Comment by Eric678** [comment]
Incase useful, I have had a couple more stops of tray.devices since above post with the following error:

> Traceback (most recent call last):
  File "/usr/lib64/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.5/site-packages/qui/tray/devices.py", line 466, in <module>
    sys.exit(main())
  File "/usr/lib/python3.5/site-packages/qui/tray/devices.py", line 444, in main
    dispatcher.listen_for_events()))
  File "/usr/lib/python3.5/site-packages/gbulb/glib_events.py", line 736, in run_until_complete
    return future.result()
  File "/usr/lib64/python3.5/asyncio/futures.py", line 294, in result
    raise self._exception
  File "/usr/lib64/python3.5/asyncio/tasks.py", line 240, in _step
    result = coro.send(None)
  File "/usr/lib/python3.5/site-packages/qubesadmin/events/__init__.py", line 126, in listen_for_events
    yield from self._listen_for_events(vm)
  File "/usr/lib/python3.5/site-packages/qubesadmin/events/__init__.py", line 186, in _listen_for_events
    self.handle(subject, event, **kwargs)
  File "/usr/lib/python3.5/site-packages/qubesadmin/events/__init__.py", line 220, in handle
    handler(subject, event, **kwargs)
  File "/usr/lib/python3.5/site-packages/qui/tray/devices.py", line 210, in vm_start
    self.device_attached(vm)
  File "/usr/lib/python3.5/site-packages/qui/tray/devices.py", line 222, in device_attached
    self.get_submenu().dev_attached(vm)
  File "/usr/lib/python3.5/site-packages/qui/tray/devices.py", line 114, in dev_attached
    menu_item.attach()
  File "/usr/lib/python3.5/site-packages/qui/tray/devices.py", line 45, in attach
    assert not self.attached
AssertionError

**Comment by Eric678** [comment]
Thanks Marek, I tested the centos-7 update (cloned template, update as above, stop; start appVM on this new template) and it does not appear to work. No change in the symptoms as described originally. In the test appVM the package appears installed OK:
qubes-usb-proxy.noarch                  1.0.20-1.centos7               @qubes-vm-r4.0-current-testing

**Comment by marmarek** [comment]
@Eric678 the fix is in dom0 part of this package.

**Comment by Eric678** [comment]
Sorry the qubesos-bot email notification for dom0 went to junk my end. Did not notice. I cannot test as my test NUC has all USBs on the one controller and needs USB mouse/kbd. The dom0 update is not standalone and the whole of current testing is pretty brain damaged (eg Qubes Manager/Settings gets a Houston dialog).

I did notice a related issue and am not sure if you fixed it - given that USBs are transient (may be powered off) a persistent attach that is not plugged in and powered up prevents a VM from starting.  The VM should start and the device get attached when it is plugged in / powered up. Detatching using qvm-usb and then starting a VM that previously failed to start due to a persistent attach left tray.devices out of sync - it thought that the USB device was still attached when it was not.
Thanks, Eric

**Comment by marmarek** [comment]
> I did notice a related issue and am not sure if you fixed it - given that USBs are transient (may be powered off) a persistent attach that is not plugged in and powered up prevents a VM from starting. 

This is by design. `persistent` flag means the device will be there on VM startup. If it's not possible (for example device missing), the VM will not start.

This design doesn't fit nicely for USB, though. Yet another thing to fix in the design for R4.1 (#4626 )

**Comment by Eric678** [comment]
OK I see, my interpretation of "persistent" is having a particular device permanently connected to a specific VM as if it were a standalone machine.  If the device is not there it does not stop a machine booting, if a PCI the FS just does not get mounted. Guess this has not come up before as hot pluggable PCIs exist if supported by the BIOS but really are a server not workstation (Qubes) thing.

IMHO your definition of persistent is incorrect.
