### ISSUE TITLE
Using an Audio CD

### ISSUE THREAD

**Issue by straussmaus** [QubesOS/qubes-issues#4783]
### Qubes OS version:

4.0

### Affected component(s):

Audio CD Playback

---

### Steps to reproduce the behavior:

1  Insert Audio CD

2  Attach to running VM

3  Try to run `ripit` but `ripit` does not find the CD

4  Specify /dev/xvdi instead of /dev/cdrom

5  Look for doc on https://www.qubes-os.org/doc/

### Expected behavior:

The attached CD is expected to be available to players at /dev/cdrom or /dev/xvdi

### Actual behavior:

ripit, mpv etc do not find the cd to play or rip it

### General notes:

Probably it's easy and I just need a doc?

---

**Comment by Yethal** [comment]
Have you tried attaching the cd rom drive via qvm-pci?

**Comment by straussmaus** [comment]
@Yethal 

> Have you tried attaching the cd rom drive via qvm-pci?

Yes and no.  I have tried qvm-pci but there is no device for the CD but not the disk and I do not want to attach the main hard disk to this VM.  But also I don't really understand the device list so it is possible that I am wrong?

**Comment by Yethal** [comment]
You need to attach the entire sata controller to which the cd rom drive is connected.

**Comment by straussmaus** [comment]
@Yethal Please read my comment above.  I said "there is no device for the CD but not the disk" and that means if I attach the entire sata controller then I will lose the disk that my hard drive is on.  They are controlled by the same sata controller.  Well it seems like this from trying.

But I am able to use the icon in Qubes GUI to attach a DVD to a VM without the entire sata controller and the same GUI option is available for a CD so why am I getting the error I describe in the first comment with a CD?

**Comment by andrewdavidwong** [comment]
> Audio CDs aren't block devices, so can't get passed through to AppVMs. Options are same as described in https://www.qubes-os.org/doc/recording-optical-discs/.

Sounds like the task here is just to generalize that doc to "using" from "recording."

**Comment by straussmaus** [comment]
@andrewdavidwong 

> Sounds like the task here is just to generalize that doc to "using" from "recording."

Yes I agree this satisfies this Issue.
