### ISSUE TITLE
Allow Networking Between a Linux and Windows Qube

### ISSUE THREAD

**Issue by ur-annoying-printer** [QubesOS/qubes-issues#4785]
I've successfully enabled networking between two Linux qubes using:

https://www.qubes-os.org/doc/firewall/

But because the command `iptables` doesn't exist on Windows it doesn't work for Windows.

How might one go about accomplishing this?

I've tried:

`netsh interface portproxy add v4tov4 listenport=* connectaddress=<LINUX QUBE IP> connectport=*`

then connecting to a python SimpleHTTPServer (python -m SimpleHTTPServer 8080) from my Windows qube with no success.

**Comment by andrewdavidwong** [comment]
Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this does not appear to be suitable for `qubes-issues`. We ask that you please send this to the `qubes-users` [mailing list](https://www.qubes-os.org/support/) instead. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a brief comment explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.
