### ISSUE TITLE
Installer does not add UEFI boot entry when baremetal Fedora 29 does on the same hardware

### ISSUE THREAD

**Issue by Simon-Davies** [QubesOS/qubes-issues#4786]
### Qubes OS version:

4.0.1

### Affected component(s):

Qubes OS

---

### Steps to reproduce the behavior:

Install Qubes OS adding kernel boot options to disable the Noveau driver and add Intel Alpha support.

### Expected behavior:

Qubes UEFI boot entry is added and Qubes OS boots

### Actual behavior:

Qubes UEFI entry isn't added and Qubes OS doesn't boot.

### General notes:

---

**Comment by Simon-Davies** [comment]
I disabled nouveau by binary editing the Qubes OS installer iso.

A UEFI entry isn't added after the Qubes OS installer completes.

**Comment by marmarek** [comment]
Is [this](https://www.qubes-os.org/doc/uefi-troubleshooting/#installation-finished-but-qubes-boot-option-is-missing-and-xencfg-is-empty) relevant here?

**Comment by Simon-Davies** [comment]
This might fix the issue. But why does the installer fail to add it? Fedora 29 adds it fine.

**Comment by marmarek** [comment]
That's a good question. Take a look at `/var/log/anaconda` and see if there are any failures related to UEFI setup (grep for "efi" or such).
