### ISSUE TITLE
Make it easier to discover USE_QUBES_REPO_VERSION qubes-builder setting

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#4788]
For building just few selected packages, it's very useful to download pre-built qubes-specific dependencies from `{yum,deb}.qubes-os.org`. This is especially true for gcc, which takes several hours to build.

There is already `builder.conf` setting for this: `USE_QUBES_REPO_VERSION` and `USE_QUBES_REPO_TESTING`. But it isn't easily to discover, as it's only in detailed documentation, but not generic one (https://www.qubes-os.org/doc/qubes-builder/) and also it isn't proposed by `setup` script.

Tasks:
 - [x] Add info about `USE_QUBES_REPO_*` to the documentation
 - [x] Add option to set it with `setup` script

**Comment by marmarek** [comment]
@fepitre would you like to take care of this?

**Comment by fepitre** [comment]
Sure.
