### ISSUE TITLE
Why Does Qubes Leak /proc/cpuinfo

### ISSUE THREAD

**Issue by lookin-out4u** [QubesOS/qubes-issues#4789]
https://www.whonix.org/wiki/Protocol-Leak-Protection_and_Fingerprinting-Protection#Metadata

KVM doesn't do this... Why does Qubes?

**Comment by marmarek** [comment]
First of all, according to [bug reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/#issue-tracker-guidelines), such questions should be directed to qubes-users/qubes-devel mailing list.

Secondly, you can see details about why here: https://github.com/QubesOS/qubes-issues/issues/1142
