### ISSUE TITLE
qvm-backup-restore should check if there is enough disk space / should continuously make sure to not run out of disk space

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#4791]
### Qubes OS version:

R4.0

### Affected component(s):

dom0 qvm-backup-restore

---

### Steps to reproduce the behavior:

Backup.
Restore the backup which fails for some reason.
Try restore backup again.
Will fail due to low disk space?

### Expected behavior:

Check for enough disk space.

### Actual behavior:

Run out of disk space.

### General notes:

Running out of disk space risks a no longer bootable system.

Files it stored temporarily in /var/tmp are not deleted when trying to verify a backup which fails. Another attempt then can lead to no longer having enough disk space.

---

**Comment by tasket** [comment]
User report here:

https://groups.google.com/d/msgid/qubes-users/ADC61334-2172-4540-AABA-8E17C6FD06ED%40ryantate.com

**Comment by andrewdavidwong** [comment]
Another related user experience:

https://groups.google.com/d/msg/qubes-users/hv4Jao4V0BU/R7e7cFn_EwAJ
