### ISSUE TITLE
Qubes 4.0.1 fails to install on dell latitude e5xxx

### ISSUE THREAD

**Issue by jonull101** [QubesOS/qubes-issues#4795]
BIOS:
--General--
Boot Sequence
 -UEFI
Advanced Boot Options
 -Enable Legacy Option ROMs

--System Configuration--
SATA Operation
 -AHCI

TPM
 -ON

Installing works in Legacy External device boot
-USB Storage Device
else i get penguins.

Troubleshooting
->Rescue a Qubes system
->1) Continue
->LUKS passphrase
->{Enter] to get a shell
->sh-4.3#
-->Following the, which by the way should be updated:
https://www.qubes-os.org/doc/uefi-troubleshooting/#boot-device-not-recognized-after-installing

Part:
Installation finished but “Qubes” boot option is missing and xen.cfg is empty

->vi xen.cfg <-> is empty
here is the uefi-troubleshooting by qubes a config for 3.2
*does the same config work for 4.0.1?

->running the config from 3.2, adjusting kernel version and filesystem location , looks OK!

Now:
-------------------------------
4. 

Create boot entry in EFI firmware (replace /dev/sda with your disk name and -p 1 with /boot/efi partition number):

efibootmgr -v -c -u -L Qubes -l /EFI/qubes/xen.efi -d /dev/sda -p 1 "placeholder /mapbs /noexitboot"

-----------------------------------
->sh-4.3# efibootmgr
EFI variables are not supported on this system.

which means efivars kernel module is probably not enabled.
->sh-4.3#modprobe efivars
modprobe: FATAL: Module efivars not found in directory /lib/modules/4.14.74-1.pvops.qubes.x86_64

trying to allocate efivars, but cannot find it, and a few grubs directories.

From what i understand it's not necessary to run grubs in UEFI.

Am i missing something? Besides that the troubleshooting guide for UEFI is very poor and not updated.

Would appreciate if someone could give me a hand on this one.

**Comment by andrewdavidwong** [comment]
Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this does not appear to be suitable for `qubes-issues`. We ask that you please send this to the `qubes-users` [mailing list](https://www.qubes-os.org/support/) instead. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a brief comment explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.
