### ISSUE TITLE
Make "kernel options" editable in Qubes Manager

### ISSUE THREAD

**Issue by strugee** [QubesOS/qubes-issues#4797]
### Qubes OS version:

R4.0

### Affected component(s):

Qubes Manager

---

### Steps to reproduce the behavior:

1. Open a VM's settings
2. Go to "Advanced"

### Expected behavior:

I can edit the kernel options shown.

### Actual behavior:

It's just static text that I can't edit.

### General notes:

I'm tinkering with kernel options in order to improve AppVM boot performance, since that's the main source of slowness when I boot dom0. While searching for duplicates I ran across a comment that noted this functionality is accessible with `qvm-prefs` which was not at all obvious to me before. In fact I spent a lot of time searching the mailing list, etc. for how to change kernel parameters to no avail. This would make it a lot more discoverable.

---

**Comment by t4777sd** [comment]
I wish this was the case too. Almost every VM needs kernel options managed. At a minimum selinux would need to be enabled for example. So, this is something that most people need to do

**Comment by andrewdavidwong** [comment]
> I wish this was the case too. Almost every VM needs kernel options managed. At a minimum selinux would need to be enabled for example. So, this is something that most people need to do

I doubt that. As far as I can recall, I've never had to manage the kernel options for any of my VMs in all my years as a Qubes user.

**Comment by unman** [comment]
On Wed, Feb 13, 2019 at 08:38:25PM -0800, Andrew David Wong wrote:
> > I wish this was the case too. Almost every VM needs kernel options managed. At a minimum selinux would need to be enabled for example. So, this is something that most people need to do
> 
> I doubt that. As far as I can recall, I've never had to manage the kernel options for any of my VMs in all my years as a Qubes user.
> 

I agree: most users wont need to do this

I think this is one of those cases where it is assumed that people who want
to be able to set kernel options will have the nous to be able to use
the command line tools.
Perhaps this assumption is misplaced.

**Comment by strugee** [comment]
Also agree that this is a rare thing to do. SELinux, for example, may not get you all that much on top of Qubes' additional security, and if it was easy to do it'd be enabled already.

> I think this is one of those cases where it is assumed that people who want to be able to set kernel options will have the nous to be able to use the command line tools.

The problem is not the ability to use the commandline tools; rather it is the ability to _discover_ which commandline tool to use. I, for example, spent a _long_ time hunting for the right config file to edit in-VM or in dom0 to make this work. I had no idea that I was supposed to use `qvm-prefs` (I guess I should write some documentation about it?)

Putting it in the GUI makes it more discoverable. There could also just be some small (mouseover?) text that said "you can edit this with `qvm-prefs`" or something.

**Comment by ffsec** [comment]
> Putting it in the GUI makes it more discoverable. There could also just be some small (mouseover?) text that said "you can edit this with `qvm-prefs`" or something.

I agree with @unman and  on this. Only few (advanced) users are messing with kernel options and I'd assume that those know about command line options or at least are capable of reading the Qubes documentation.

IMO it shouldn't be too hard to actually get the required information, it took me only a few seconds to find these:

https://www.qubes-os.org/doc/managing-vm-kernel
https://www.qubes-os.org/doc/tools/3.2/dom0/qvm-prefs/

I don't think the GUI is the right place to advertise command line usages, especially if they are sparely used. Having hints in a GUI would suggest that this is something important/useful, while for most users it just is not. It could also lead to confusion for the average user, thinking this is some common feature they should proabably use.

Maybe you could add a topic to the "managing-vm-kernel" page, if that would be helpful? It already mentions "2. You can modify kernel options in VM settings", so there could aswell be an example.

**Comment by brendanhoar** [comment]
> I'm tinkering with kernel options in order to improve AppVM boot performance, since that's the main source of slowness when I boot dom0.

Somewhat off-topic aside to OP, perhaps useful: disabling auto-start for all VMs (except for sys-usb) dramatically improved time-to-desktop for me. Sure...startup of network-connected VMs is thus delayed a bit, but that delay is moved from pre-login to whenever I prefer it to happen. Also, I am not always intending to perform work across a network immediately after console login.

B

**Comment by marmarek** [comment]
> Somewhat off-topic aside to OP

Indeed off-topic here, but it's tracked at #3149

**Comment by marmarta** [comment]
Closing this, as documentation was improved, and there seems to be a pretty clear opinion that it's not a good idea to add editing kernel opts to GUI tools or to add hints to CLI tools to GUI.
