### ISSUE TITLE
ixgbe - Failed to allocate MSI-X interrupts. Err: -22

### ISSUE THREAD

**Issue by jarlethorsen** [QubesOS/qubes-issues#4799]
### Qubes OS version:
R4.0

### Affected component(s):
ixgbe network driver

---

### Steps to reproduce the behavior:
Having a network card that uses the ixgbe driver (for example Intel X540-AT2) connected to a netvm will automatically load the driver, but network card will not work, the link will not come up:

```
$ sudo dmesg |grep ixgbe
[    2.823319] ixgbe: Intel(R) 10 Gigabit PCI Express Network Driver - version 5.1.0-k
[    2.823360] ixgbe: Copyright (c) 1999-2016 Intel Corporation.
[    3.107050] ixgbe 0000:00:06.0: Failed to allocate MSI-X interrupts. Err: -22
[    3.107053] ixgbe 0000:00:06.0: Disabling SR-IOV support
[    3.107056] ixgbe 0000:00:06.0: Disabling RSS support
[    3.110167] ixgbe 0000:00:06.0: Multiqueue Disabled: Rx Queue count = 1, Tx Queue count = 1 XDP Queue count = 0
[    3.243037] ixgbe 0000:00:06.0: MAC: 3, PHY: 0, PBA No: G35632-015
[    3.243040] ixgbe 0000:00:06.0: a0:36:9f:83:8c:e2
[    3.389053] ixgbe 0000:00:06.0: Intel(R) 10 Gigabit Network Connection
[    3.659830] ixgbe 0000:00:07.0: Failed to allocate MSI-X interrupts. Err: -22
[    3.659870] ixgbe 0000:00:07.0: Disabling SR-IOV support
[    3.659896] ixgbe 0000:00:07.0: Disabling RSS support
[    3.662428] ixgbe 0000:00:07.0: Multiqueue Disabled: Rx Queue count = 1, Tx Queue count = 1 XDP Queue count = 0
[    3.794041] ixgbe 0000:00:07.0: MAC: 3, PHY: 0, PBA No: G35632-015
[    3.794104] ixgbe 0000:00:07.0: a0:36:9f:83:8c:e0
[    3.941049] ixgbe 0000:00:07.0: Intel(R) 10 Gigabit Network Connection
[    3.973999] ixgbe 0000:00:06.0 ens6f0: renamed from eth0
[    4.002432] ixgbe 0000:00:07.0 ens7f0: renamed from eth1
[    4.034616] ixgbe 0000:00:06.0: registered PHC device on ens6f0
[    4.188467] ixgbe 0000:00:07.0: registered PHC device on ens7f0
```

### Expected behavior:

Network card should work, and a link should come up when a network cable is connected.

### Actual behavior:

See "Steps to reproduce the behavior"

### General notes:

Notice the error:
ixgbe 0000:00:06.0: Failed to allocate MSI-X interrupts. Err: -22

This driver/card works fine in Qubes OS 3.2

Have tried connecting card to both Fedora 29 and Debian-9 base netvm, same problem.

Have tried manually compiling and loading latest version of the ixgbe driver, still same problem.

---

**Comment by marmarek** [comment]
Related patches already discussed on xen-devel: https://xen.markmail.org/thread/cmcznej4ax3faiti

**Comment by cybernatichaxor** [comment]
I'm having the exact same issues with the Intel 10G X550T network card on sys-net running Fedora 30. Any idea on when a patch will be released or is there a temporary work-around?

**Comment by djlongy** [comment]
I also have the exact same issues with the Intel 10G X550T network card on sys-net running Fedora 30. Looking forward to a patch/update for this network card.

**Comment by Vico999** [comment]
Same issue. All that is required is driver support.
