### ISSUE TITLE
dom0 /etc/default/grub value incorrect

### ISSUE THREAD

**Issue by brendanhoar** [QubesOS/qubes-issues#4801]
### Qubes OS version:

R4.0, currently updated to testing

### Affected component(s):

/etc/default/grub contents

---

### Steps to reproduce the behavior:

Change GRUB_DISABLE_SUBMENU to the opposite value
Rebuild grub config

### Expected behavior:

Grub menu changes

### Actual behavior:

No change to grub menu on boot.

### General notes:

In default setup, /etc/default/grub has a line like this:
GRUB_DISABLE_SUBMENU=true

However, if the intent was really to disable the submenu and show everything in a single list, it really should have been:

GRUB_DISABLE_SUBMENU="y"

After making that change and rebuilding grub config, all permutations of installed XEN and KERNELS are presented.

---

**Comment by brendanhoar** [comment]
Just a reminder - really setting this correctly (as the default) might really help folks who have a broken init.rd on their newly downloaded kernel get back to a working system faster. Just noticed a confused discussion on the list today regarding something similar.

**Comment by marmarek** [comment]
I see there is an upstream patch to accept all three "true", "yes" and "y".
But nevertheless, our intention was _not_ to enable it by default, so I'll also change default value (will affect only new installs, sadly).

**Comment by brendanhoar** [comment]
Oh well, that backfired. :)
