### ISSUE TITLE
qvm-backup applies compression even without the "--compress" option

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#4803]
### Qubes OS version:

`R4.0`

### Affected component(s):

`qvm-backup`

---

### Steps to reproduce the behavior:

Run `qvm-backup` without the `--compress` option.

### Expected behavior:

The backup is not compressed. Compression is off by default (as in R3.2).

### Actual behavior:

The backup is `gzip` compressed. There is no way to create a backup without compression. Compression is on by default, and there is no option to turn it off (e.g., `--no-compress`).

### General notes:

---

### Related issues:

#4751

**Comment by marmarek** [comment]
The default change was intentional, but indeed there should be `--no-compress` option and documentation should be updated.
