### ISSUE TITLE
qvm-copy hangs when vm copying to itself

### ISSUE THREAD

**Issue by jaseg** [QubesOS/qubes-issues#4804]
### Affected component(s):
qvm-copy

---

### Steps to reproduce the behavior:
Run `$ qvm-copy /var/empty` in domain $foo then select same domain $foo as target.

### Expected behavior:
Either of:
* The file/folder being correctly copied to the source VM's QubesIncoming
* An error message by the dom0 auth agent like "Bad destination: Domain can't copy to itself."

### Actual behavior:
 qvm-copy starts, but progress hangs at 0kB and nothing happens. When invoked from nautilus via the context menu, Nautilus hangs.

### General notes:
Showing an error message in dom0 might be done by extending the qubes policy framework to include a differentiation between `$anyvm` and `$anyvm` excluding the source vm. This might make sense to prevent user error in other cases.

---

### Related issues:
None that I could find.

**Comment by jaseg** [comment]
This also seems to affect some other services, I managed to hang `qvm-open-in-vm` with both file and URL arguments.

**Comment by marmarek** [comment]
This is directly caused by #951 
Indeed qrexec should handle it better. I can easily convert it into "request refused" error, and also remove source from target selection. Some more elaborate error reporting would require slightly bigger change than I'm comfortable with doing as stable update.

**Comment by jaseg** [comment]
Thank you for the fix!
