### ISSUE TITLE
52qubes-pause-vms preventing suspend

### ISSUE THREAD

**Issue by dmoerner** [QubesOS/qubes-issues#4806]
Qubes 4.0.1, running i3, on a Lenovo X1 Carbon 3rd generation

I use xfce4-power-manager to suspend the system on lid close.

Although I can't reliably reproduce the problem, it sometimes happens that the system does not suspend when the lid is closed. This is not a problem with detecting the lid closure, because the system does get as far as running a systemd service to lock the screen which is WantedBy suspend.target. However, it does not suspend.

On reopening the lid, I get a notification that suspend failed. The next time I run into this bug I will add that notification text to this bug report.

The system is then stuck in a situation where I cannot even reboot from the dom0 console; I get the following message: "Failed to reboot system during logind: There's already a shutdown or sleep operation in progress."

With the system in this state, if I run "sudo killall 52qubes-pause-vms", the system does instantly suspend. However, after waking up the system again, I still cannot get the system to suspend correctly with "systemctl -i suspend". That command only locks the screen until I run "sudo killall 52qubes-pause-vms", at which instance the system instantly suspends again. All I can do is reboot the system, at which point everything works again.

I have encountered this bug on several installs of Qubes R4 on this machine, but never reported it before.

Note that sys-usb always has to be manually restarted on this system after every suspend, whether or not I run into this bug, so it's possible that this has some relation to this bug, but I'm not sure: https://github.com/QubesOS/qubes-issues/issues/3689.

**Comment by marmarek** [comment]
The actual problem is that some VM fails to suspend. From your description I guess it's sys-usb.
The `52qubes-pause-vms` script is responsible for suspending/pausing all the VMs before allowing the host to suspend. This is especially important for VMs with PCI devices, as failing to do so will at least break that VM (which you observe), but in some cases may cause the whole suspend or resume operation to fail.

Can you provide more details about sys-usb, especially its console output when it fails to suspend? See `/var/log/xen/console/guest-sys-usb.log`

**Comment by dmoerner** [comment]
Unfortunately, there is nothing useful in guest-sys-usb.log. (The previous entries are days old.) 

I think this is a side-effect of https://github.com/QubesOS/qubes-issues/issues/4042.

**Comment by dmoerner** [comment]
I have not had this problem since upgrading to kernel 4.19.43-1, nor does sys-usb die on suspend with the new kernel. Closing this now, although hopefully 4.19 will make its way to -current soon.
