### ISSUE TITLE
Tablet battery level always displays at "50%%" and never changes until battery runs out

### ISSUE THREAD

**Issue by alinazzal** [QubesOS/qubes-issues#4807]
### Qubes OS version:

4.0.1

### Affected component(s):

I’m not able to accurately keep track of my tablets batter status. I do have the battery monitor on the toolbar but all it shows me is “50%%” with two percent signs and it never changes. Not until my tablet shuts down because it’s out of battery, but the batter monitor doesn’t reflect a change in batter percentage at all and it has two percent signs instead of just one.

---

### General notes:

---

**Comment by andrewdavidwong** [comment]
This might turn out to be too localized or an upstream bug (e.g., if the same problem exists on baremetal Fedora).

**Comment by strugee** [comment]
Which battery plugin are you using for the panel?
