### ISSUE TITLE
qvm-run blocking behavior change is causing UX problems

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#4808]
### Qubes OS version:

`R4.0`

### Affected component(s):

`qvm-run`

---

### Steps to reproduce the behavior:

Try to use `qvm-run` in dom0 in a non-blocking way (`R3.2` behavior), e.g., by appending `&` to the end of the command:

```
[user@dom0 ~]$ qvm-run --dispvm=my-dvm-template xterm &
[1] 12345
[user@dom0 ~]$ Running 'xterm' on $dispvm:my-dvm-template
^C
[user@dom0 ~]$ 
```

Problems:
* The message in the third line appears after a command prompt.
* The last two lines -- and all lines following until the terminal emulator is restarted -- will be in red, which is usually used to indicate I/O passed through from the VM. (This happens whether you just press <kbd>Enter</kbd> or <kbd>Ctrl</kbd>+<kbd>C</kbd>.)

You might instead try this:

```
[user@dom0 ~]$ qvm-run --dispvm=my-dvm-template --service qubes.StartApp+xterm
Running 'qubes.StartApp+xterm' on $dispvm:my-dvm-template

^C[user@dom0 ~]$ 
```

But this blocks, and trying to get the prompt back with <kbd>Ctrl</kbd>+<kbd>C</kbd> kills the DisposableVM that was just started.

Finally, if you come both approaches, you still end up with the same problems encountered with the first approach:

```
[user@dom0 ~]$ qvm-run --dispvm=my-dvm-template --service qubes.StartApp+xterm &
[1] 12345
[user@dom0 ~]$ Running 'qubes.StartApp+xterm' on $dispvm:my-dvm-template
^C
[user@dom0 ~]$ 
```

Problems:
* The message in the third line appears after a command prompt.
* The last two lines -- and all lines following until the terminal is restarted -- will be in red, which is usually used to indicate I/O passed through from the VM. (This happens whether you just press <kbd>Enter</kbd> or <kbd>Ctrl</kbd>+<kbd>C</kbd>.)

Workarounds:
* If you use `qvm-run`, open a new terminal tab/window to get a command prompt back, then close the original tab/window later when you're done with it.
* Restart your terminal after getting the red text.

### Expected behavior:

An easy, clean way to use `qvm-run` in a non-blocking way (exactly what we had in R3.2).

### Actual behavior:

All available methods to use `qvm-run` in a non-blocking way either require a lot of terminal emulator window/tab manipulation (not easy) or result in weird things happening with the terminal, like all text being colored red even though it's not VM passthrough (not clean).

### General notes:

The behavior in R3.2 was easy, clean, and intuitive. It's not clear why it was changed. Other users are also confused by this change, which appears to be a usability regression:

* https://groups.google.com/d/topic/qubes-users/7FtJrbZVZhs/discussion
* https://groups.google.com/d/topic/qubes-users/MmBREZoatus/discussion

As far as I know, the new blocking behavior is not documented anywhere.

---

**Comment by marmarek** [comment]
You can use `-q` option to suppress `Running 'xterm' on...` message.
The output coloring without `--pass-io` is clearly a bug.

**Comment by heinrich-ulbricht** [comment]
I'm currently stumbling over this blocking behavior in Qubes 4 while trying to copy something to the clipboard using `xclip`. Try to make this one return... :-|

This is how I want to copy an image file to the clipboard of a running AppVM 'work':

(dom0) `qvm-run work "xclip -selection clipboard -t image/png /home/user/Pictures/image.png"`

This blocks the terminal. Not what I want.

Here is the same command showing the output of xclip and how it waits for selection requests:

(dom0) `qvm-run --pass-io work "xclip -selection clipboard -verbose -t image/png /home/user/Pictures/image.png"`

My expectation is that I can make the command return immediately. I don't care that there are processes waiting to do things in the AppVM.

What does work is this, as hinted in the [Google Group](https://groups.google.com/d/msg/qubes-users/7FtJrbZVZhs/Hhvz5iopBwAJ):

(dom0) `/usr/lib/qubes/qrexec-client -d work -e DEFAULT:'xclip -selection clipboard -verbose -t image/png /home/user/Pictures/image.png'`

**Comment by marmarek** [comment]
Adding `&` at the end should tell the shell to run it in the background. You might want to use `-q` too in that case.

**Comment by heinrich-ulbricht** [comment]
I see. This combination I did not test.
This works:
(dom0) `qvm-run -q work "xclip -selection clipboard -t image/png /home/user/Pictures/image.png" &`
(Without `-q` it would block.)
Thank you.
