### ISSUE TITLE
mgmtVM - qvm-clone fails: Failed to clone appmenus, qvm-appmenus missing

### ISSUE THREAD

**Issue by deeplow** [QubesOS/qubes-issues#4809]
### Qubes OS version:

R4.0

### Affected component(s):
qubes-core-admin-client

---

### Steps to reproduce the behavior:
1. Delegate a VM as AdminVM (`test-mgmt`, for example) of another (`managed-work`) (through the process [here described](https://www.qubes-os.org/news/2017/06/27/qubes-admin-api/) ) 
2. on `test-mgmt` do
```bash
qvm-clone managed-work managed-work-2
```

### Expected behavior:
```bash
managed-work-2: Cloning private volume
managed-work-2: Cloning root volume
```

### Actual behavior:
```bash
app: Failed to clone appmenus, qvm-appmenus missing
qvm-clone: error: Failed to clone appmenus
```

### General notes:
The bug seems to have been introduced [in this commit](https://github.com/QubesOS/qubes-core-admin-client/commit/67897e3f9fd0db88ea1539a6bfeaa36b732ce6c8)

There is a `FIXME` in the code, which I suppose would solve the problem, when implemented.

As a temporary fix, I've commented out [these line](https://github.com/QubesOS/qubes-core-admin-client/commit/67897e3f9fd0db88ea1539a6bfeaa36b732ce6c8?diff=unified#diff-d50dd1c31b6d6078efc993edf2831838)

---

### Related issues:
Issues mentioned in [the commit](https://github.com/QubesOS/qubes-core-admin-client/commit/67897e3f9fd0db88ea1539a6bfeaa36b732ce6c8)

**Comment by marmarek** [comment]
Yes, implementing that `FIXME` would solve the issue, but this is too extensive change for R4.0 update.
In the meantime, it would be possible to either make that error non-fatal, or make `ignore_errors` parameter available on command line (`qvm-clone --ignore-errors`).

**Comment by conorsch** [comment]
> but this is too extensive change for R4.0 update

Understood, I appreciate your perspective on maintaining stability. Since you mentioned the `ignore_errors` param would handle this use case nicely in the interim, I've submitted https://github.com/QubesOS/qubes-core-admin-client/pull/92 as a candidate implementation. Happy to revise at your direction, @marmarek. Many thanks!
