### ISSUE TITLE
Cannot Select text in Visual Studio Code

### ISSUE THREAD

**Issue by ofey404** [QubesOS/qubes-issues#4810]
### Qubes OS version:
R4.0

### Affected component(s):
VS Code Version 1.31.0, x64

Hardware: Thinkpad T470

---

### Steps to reproduce the behavior:
1. Install Qubes 4.0~rc4
2. [Install VS Code on a Fedora 29 TemplateVM](https://code.visualstudio.com/docs/setup/linux#_rhel-fedora-and-centos-based-distributions)
3. Sync applications with dom0
4. Open VS Code in a AppVM, type something the try to select(hold the left bottom of mouse and drag the pointer above the text)

### Expected behavior:
Text under the route of pointer would be selected(highlighted) properly

### Actual behavior:
Nothing happens, nor the cursor moves.

### General notes:
While double or triple clicks, word and line would still be selected properly.

---

**Comment by kyletheninja** [comment]
I have this same issue on vscode installed on windows. I have some different extensions installed, I'm sure it could be related to those but it is very frustrating.

**Comment by fepitre** [comment]
It's weird. I'm using VS code since a long time on different Fedora, CentOS or Debian templates and I've never encountered any trouble you mean (even at all). Could you try to post more information by launching vscode in a terminal and try to figure out if any errors appear related to your attempt of selecting text.

**Comment by andrewdavidwong** [comment]
> I have this same issue on vscode installed on windows. I have some different extensions installed, I'm sure it could be related to those but it is very frustrating.

To clarify, do you mean in a Windows VM in Qubes, or just a normal baremetal Windows installation?

**Comment by kyletheninja** [comment]
Normal windows 10. Sorry I googled my way to this thread, maybe I am in the wrong place.

**Comment by andrewdavidwong** [comment]
Ok, if this is also happening in a normal baremetal Windows installation, then it must not be a Qubes-specific issue. Therefore, I'm closing this as "not our bug." If anyone believes this is a mistake, please leave a comment, and we'll be happy to take another look. Thank you.
