### ISSUE TITLE
Boot bug when installing Qubes 4.0.1 UEFI Dell Latitude

### ISSUE THREAD

**Issue by jonull101** [QubesOS/qubes-issues#4814]
### Qubes OS version:

R4.0.1

### Affected component(s):
Fresh install in UEFI mode.

---

### Expected behavior:
Be able to see HDD with qubes in BIOS.
Be able to se GRUB menu.
Not be able to see FAILED loading kernel modules.
Be able to boot qubes r4.0.1 without do the task that i described below.

### Actual behavior:

cd /mnt/sysimage/boot/efi/EFI
in the EFI directory there is qubes.
in qubes/ there is:

initramfs-4.14.74-1.pvops.qubes.x86_64.img
vmlinuz-4.14.74-1.pvops.qubes.x86_64
xen-4.8.4.efi
xen.cfg
xen.cfg.anacbak
xen.efi

Cannot see any BOOT Directory, unless i create it in rescue mode.

### General notes:
I had to:
cd /mnt/sysimage/boot/efi/EFI
$ cp -R qubes/. BOOT/
$ cp BOOT/xen.cfg BOOT/BOOTX64.cfg
$ cp qubes/xen-4.8.4.efi qubes/xen.efi
$ cp qubes/xen-4.8.4.efi BOOT/BOOTX64.efi

From USB in legacy boot + rescue qubes and ask for shell,
to be able to see my HDD in BIOS in UEFI mode, and to be able to log in to qubes.

But i still dont see the GRUB menu.

Am i missing something here? Or why does not my GRUB menu appears on display?
And why do i have to make a BOOT directory and fix the files, shouldn't that appear by default when installing qubes 4.0.1?

To me it seems that something buggy is going on. 

---

### Related issues:

Also i get the FAILED to load kernel modules before login.
Why is that?

**Comment by marmarek** [comment]
This looks like a duplicate of https://github.com/QubesOS/qubes-issues/issues/4786

I guess you've probably already found https://www.qubes-os.org/doc/uefi-troubleshooting/
Also, lack of grub is expected - it should start directly to Xen.
Generally, UEFI in Xen 4.8 (used in Qubes 4.0) is very minimal, which also cause various incompatibilities with Grub - this is why it isn't there. Qubes 4.1 will have newer Xen, which in theory have improved UEFI support (specifically, supports multiboot2 protocol, which should at least make it compatible with Grub again). Until then, you will need the workaround you did.

Modules loading failure is tracked here: #2638

**Comment by jonull101** [comment]
@marmarek Oki, thank you for your explanation!
Is there any security risk when going directly to Xen?
I suppose the purpose of GRUB has it reason why it's there in the first place before Xen.

**Comment by jonull101** [comment]
@marmarek i do not think it's a duplicate from #4786
Since the https://www.qubes-os.org/doc/uefi-troubleshooting/ does not works correctly when it comes to launching efibootmgr, i got the error:
**EFI variables are not supported on this system.**

**Comment by marmarek** [comment]
The purpose of grub is only giving you ability to choose what to start.

> EFI variables are not supported on this system.

Are you sure you started the system in UEFI mode? The above message suggests running legacy mode.

**Comment by jonull101** [comment]
Ok,
I am sure that i made a install in UEFI mode, and to make the config i had to go to legacy mode.
The reason for that is because the install options will not appear otherwise.

What i mean is that i can only see the option troubleshooting in UEFI booting from USB in legacy external mode.

When i run a install from UEFI mode, i get straight to the "choose language option" and to "Begin install".

I have a new Dell pc, Dell is trying to make EOL of legacy mode at year 2020, i only have legacy external device as an option and UEFI mode.

@marmarek could you understand what i mean?

**Comment by marmarek** [comment]
Ah I see - I've just added this section: https://www.qubes-os.org/doc/uefi-troubleshooting/#accessing-installer-rescue-mode-on-uefi

**Comment by jonull101** [comment]
@marmarek great one, really appreciate the work and effort you and the team put in to Qubes.
