### ISSUE TITLE
Networking dns does not work when using wicd inside of VMs (it does work inside sys-net)

### ISSUE THREAD

**Issue by t4777sd** [QubesOS/qubes-issues#4816]
This is for version 4.0. I had to install wicd as due to bugs in NetworkManager it cannot connect to a Wifi access point, but Wicd can. I thought it would be simple so I installed wicd and wicd-gui. I enabled wicd and disabled network manager.

Once I restarted I connected to the access point just fine. From within the sys-net things functioned good (access to outside world + access to DNS).

However, inside of a VM that utilized the sys-net I could ping IP addresses, but I could not perform any DNS. So, ping google.com would fail, but ping 8.8.8.8 would succeed and pinging the IP of google.com would succeed.

Also, as a side note, when I tried to remove NetworkManager it wanted to remove a whole bunch of other dependences of qubes. I didn't remove it, but it seemed strange so many dependencies were set on networkmanager.

**Comment by t4777sd** [comment]
Btw, I tested this various arrangements with both fedora 28 and fedora 29 and different kernels. So, I assume this is an issue in qubes where somehow it does not resolve the DNS requests for the VM using the net-vm

**Comment by andrewdavidwong** [comment]
Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this does not appear to be suitable for `qubes-issues`. We ask that you please send this to the `qubes-users` [mailing list](https://www.qubes-os.org/support/) instead. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a brief comment explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.

**Comment by t4777sd** [comment]
For other people who come across this bug you need to run this command:

sudo ln -s /usr/lib/qubes/qubes-setup-dnat-to-ns /etc/wicd/scripts/postconnect/qubes-setup-dnat-to-ns

The qubes-setup-dnat-to-ns script is responsible for setting the IP table rules that handle DNS. It needs to be run after connection in order for DNS to work in all the connected VMs.
