### ISSUE TITLE
Can't update restored R3.2 Fedora 28 TemplateVMs after upgrade to R4

### ISSUE THREAD

**Issue by fl02** [QubesOS/qubes-issues#4817]
### Qubes OS version:
R4.0 (testing repo enabled)

### Affected component(s):
Fedora TemplateVM

---

### Steps to reproduce the behavior:
1. Backup TemplateVM from R3.2
2. Restore TVM in R4.0
3. Try to update TVM

### Expected behavior:
Update runs through.

### Actual behavior:
Error message when trying to update the TemplateVM via the Qubes Update utility:
```
Error on updating fedora-28-personal: Command '['sudo', 'qubesctl', '--skip-dom0', '--targets=fedora-28-personal', '--show-output', 'state.sls', 'update.qubes-vm']' returned non-zero exit status 20
b'fedora-28-personal:\n  ----------\n            ID: dnf list updates --refresh >/dev/null\n      Function: cmd.run\n        Result: False\n       Comment: Command "dnf list updates --refresh >/dev/null" run\n       Started: 20:47:53.101857\n      Duration: 47572.04 ms\n       Changes:   \n                ----------\n                pid:\n                    1446\n                retcode:\n                    1\n                stderr:\n                    Error: Failed to synchronize cache for repo \'updates\'\n                stdout:\n  ----------\n            ID: update\n      Function: pkg.uptodate\n        Result: True\n       Comment: System is already up-to-date\n       Started: 20:48:43.778603\n      Duration: 2370.166 ms\n       Changes:   \n  \n  Summary for fedora-28-personal\n  ------------\n  Succeeded: 1 (changed=1)\n  Failed:    1\n  ------------\n  Total states run:     2\n  Total run time:  49.942 s\n'
```

### General notes:
Networking for AppVMs that are based on these TempateVMs works fine. 

---

**Comment by fl02** [comment]
Edit: Update of other Fedora-based TemplateVMs, like the one installed with R4.0, works fine.

**Comment by andrewdavidwong** [comment]
It is recommended that you not try to restore a 3.2 TemplateVM on 4.0. Instead, you should use fresh templates all installed with or downloaded from the repos for 4.0 (or cloned from these).

Nonetheless, the error message you're receiving is a problem. Qubes should either prevent you from getting to this point or tell you not to use this TemplateVM, or it should just work.

**Comment by fl02** [comment]
Andrew, thank you for your message. 
I followed this upgrade guide on Qubes' website: https://www.qubes-os.org/doc/upgrade-to-r4.0/

**Comment by marmarta** [comment]
So, I've added a warning to the updater for potential R3.2 templates (it's a heuristic, because they don't have any simple 100%-identifying traits), the docs mention that you should not do that ("Using TemplateVMs and SystemVMs from R3.2 is not fully supported (see #3514). Instead, we recommend using the TemplateVMs that were created specifically for R4.0, which you can customize according to your needs.") and I've made a PR to make it even clearer, so I think this can be safely closed.
