### ISSUE TITLE
Qubes 4.x Backup setting should not be set to save (replace) default settings by default

### ISSUE THREAD

**Issue by LeeteqXV** [QubesOS/qubes-issues#4819]
It seems to be ticked by default (per 4.0.1-RC/December, not the latest bugfix which I am about to prepare to upgrade to...), in case that is not changed this last month, isn't that default setting actually bad (for the personal...) security?

What if a person does not pay attention to that second sentence (making a backup in a rush, thinking one knows this tool, so not reading all info each time, etc..., but enters a password to protect the current backup, then unknowingly saves it as plain text...
I'd say that the check box should at least be UNchecked by default.
Besides, it is not obvious that that is what one wants as default: To actually save the new settings (loose/replace the last default..) without making a concious choice, so for that reason alone it should not be checked.

**Comment by mfc** [comment]
I agree. the default setting should be unchecked.

currently there is no way for the user to "save" the fact they don't want the backup passphrase saved in plaintext. every time they do a backup via GUI, they have to uncheck the box.

not sure if `c: updates` should be added as label?

**Comment by andrewdavidwong** [comment]
> not sure if `c: updates` should be added as label?

I don't see what this has to do with updates.

**Comment by mfc** [comment]
so maybe instead of it trying to save the password by default, it should instead be saving the *state* of the user's decision (yes/no). with a default no instead of default yes.

not sure if it's any different in R4.1.

**Comment by mfc** [comment]
maybe @marmarta you have thoughts (should have tagged you earlier, sorry)

**Comment by mfc** [comment]
https://github.com/QubesOS/qubes-manager/blob/master/ui/backupdlg.ui#L227

change `true` to `false`

**Comment by marmarta** [comment]
fixed by https://github.com/QubesOS/qubes-manager/pull/326
