### ISSUE TITLE
Unable to build Debian  template - "chroot already exists"

### ISSUE THREAD

**Issue by unman** [QubesOS/qubes-issues#4820]
### Qubes OS version:
R4.0

### Affected component(s):
Qubes builder

---

### Steps to reproduce the behavior:
clone qubes-builder 44921ba
Follow process to build Debian+minimal template
`make qubes-vm` creates chroot-vm-stretch (as expected)
All components build correctly

Try to build template

### Expected behavior:
Template built

### Actual behavior:
Build errors 
mkdir: cannot create directory 'chroot-debian':File exists

### General notes:

chroot-debian is created pointing to (non-existent) chroot-stretch

---

**Comment by marmarek** [comment]
I have it already fixed locally, but doing some final testing before pushing. In the meantime you can fix the symlink manually to point at chroot-vm-stretch.

**Comment by marmarek** [comment]
Pushed now.

**Comment by unman** [comment]
On Thu, Feb 14, 2019 at 05:40:38PM +0000, Marek Marczykowski-Górecki wrote:
> Pushed now.
> 
Cheers
