### ISSUE TITLE
[Fixed] DNS resolution does not work when using ubuntu bionic as sys-net template

### ISSUE THREAD

**Issue by cawilliamson** [QubesOS/qubes-issues#4828]
### Qubes OS version:
R4.0

### Affected component(s):
Ubuntu bionic / sys-net

---

### Steps to reproduce the behavior:
1.) Build ubuntu bionic template
2.) Set sys-net to use bionic as template
3.) Start sys-net

### Expected behavior:
DNS resolution should be setup properly to allow all connected VMs (typically sys-firewall only) to resolve DNS lookups.

### Actual behavior:
Whilst sys-net can perform lookups - absolutely no connected VMs can.

### General notes:

---

### Resolution:

I have already determined the problem and a possible resolution but I'm on not sure where this is built in the first place to submit a PR?

1.) After building the ubuntu template - run terminal on it
2.) Run "systemctl disable systemd-resolved"
3.) In the file /etc/NetworkManager/NetworkManager.conf below the "[main]" heading - add "dns=default"
4.) Stop ubuntu template
5.) Reboot Qubes completely to ensure the template changes are pushed out to sys-net and bang - working DNS for all.

If anyone can guide me on where I can PR this I'm more than happy to. Just wanted to document the resolution to this since it's a really simple fix when you know how! :)

**Comment by andrewdavidwong** [comment]
> I have already determined the problem and a possible resolution but I'm on not sure where this is built in the first place to submit a PR?
> 
> 1.) After building the ubuntu template - run terminal on it
> 2.) Run "systemctl disable systemd-resolved"
> 3.) In the file /etc/NetworkManager/NetworkManager.conf below the "[main]" heading - add "dns=default"
> 4.) Stop ubuntu template
> 5.) Reboot Qubes completely to ensure the template changes are pushed out to sys-net and bang - working DNS for all.
> 
> If anyone can guide me on where I can PR this I'm more than happy to. Just wanted to document the resolution to this since it's a really simple fix when you know how! :)

I think @unman might be the person to ask about this.

**Comment by unman** [comment]
@cawilliamson Thanks for the report. I hadn't tested this.
I'll check it out now.

**Comment by unman** [comment]
@cawilliamson Thanks for identifying this problem. Your solution has been merged, so this can now be closed.
