### ISSUE TITLE
Following Install Doc Fails to Upgrade qubes-template-whonix-gw-14 

### ISSUE THREAD

**Issue by jrsmiley** [QubesOS/qubes-issues#4829]
### Qubes OS version:

Qubes release 4.0 (R4.0)

### Affected component(s):

qubes-dom0-update

---

### Steps to reproduce the behavior:

Follow the instructions in https://www.qubes-os.org/doc/installation-guide/#qubes-401-warning

### Expected behavior:

Each templateVM is upgraded

### Actual behavior:

For the whonix-gw-14 template:
[admin@dom0 Desktop]$ sudo qubes-dom0-update --enablerepo=qubes-templates-community --action=upgrade qubes-template-whonix-gw-14
WARNING: Replacing a template will erase all files in template's /home and /rw !
Template VM halted
Attempting to operate on template of UpdateVM... backing up whonix-gw-14 to whonix-gw-14-backup-20190217-3OH
qvm-clone: error: VM name must be shorter than 32 characters
ERROR: Unable to make backup of UpdateVM template!

The other two templateVMs (debian-9 and whonix-ws-14) upgrade without error.

### General notes:

The steps given in the Install doc were run immediately after a fresh 4.0.1 install, starting sys-whonix, accepting the defaults for configuring the TOR connection, and establishing a connection to TOR.

The 4.0.1 install took all defaults except that the option to use sys-whonix for dom0 and template updates was checked.

---

**Comment by marmarek** [comment]
Quick workaround - switch UpdateVM to sys-firewall:
```
qubes-prefs updatevm sys-firewall
```
And after template update, switch back to `sys-whonix`:
```
qubes-prefs updatevm sys-whonix
```
Warning: this will download the template download over non-Tor connection. If that's a problem for you, you can manually apply the fix I've just pushed - edit `/usr/bin/qubes-dom0-update` and replace `32` with `31` on line 87.
