### ISSUE TITLE
clock in tray widget way behind

### ISSUE THREAD

**Issue by ThomasWaldmann** [QubesOS/qubes-issues#4835]
### Qubes OS version:

4.0.1

### Affected component(s):

clock widget?

---

### Steps to reproduce the behavior:

wake up your laptop from suspend.
look at the clock, wonder about the time being ~2h earlier than expected.

note: utc+1 timezone (not dst), so it does not look like a utc vs. localtime issue.

### Expected behavior:

show correct time.

### Actual behavior:

localtime was ~ 08:40, it showed ~ 06:40.

**Comment by ThomasWaldmann** [comment]
after clicking on the clock widget, time "jumped" to the correct value.

**Comment by ThomasWaldmann** [comment]
i observed it again, this time with just some minutes difference:
- put laptop to suspend for some minutes
- wake it up: it shows old time
- wait a minute or so: time display updates to correct value

**Comment by marmarek** [comment]
Was the time difference equal to the in suspend?

**Comment by ThomasWaldmann** [comment]
I think so, yes.

**Comment by ThomasWaldmann** [comment]
just had it again:
- looked at clock widget (after working for maybe 1 hour at the machine)
- thought "can't be"
- clicked on it -> it jumped ahead ~1h

So, sometimes the clock does not update at all.
