### ISSUE TITLE
Cannot Build Stretch template - architecture error

### ISSUE THREAD

**Issue by unman** [QubesOS/qubes-issues#4836]
### Qubes OS version:

R4.0

### Affected component(s):

Qubes Builder

---

### Steps to reproduce the behavior:
Attempt to build Stretch template.

### Expected behavior:
Template is produced.

### Actual behavior:
All packages are built in chroot-vm-stretch.
For template build, a new chroot is used - chroot-vm-buster.
The build fails:

> 'python-u2flib-host_3.0.3-1+deb9u1_amd64.buildinfo' looks like architecture 'amd64', but this is not listed in the Architecture-Header!
> To ignore use --ignore=surprisingarch.
> There have been errors!
> make[1]: *** [/home/user/qubes-builder/qubes-src/builder-debian/Makefile.debian:245: update-repo-do] Error 1
> make: *** [Makefile:310: template-local-stretch+minimal+no-recommends] Error 1

### General notes:

---

**Comment by cawilliamson** [comment]
+1 I'm getting this same issue with salt-mgmt when trying to build Ubuntu bionic.

Seems like a recent commit has likely broken things - will try and track it down.

**Comment by marmarek** [comment]
Same here, I can reproduce it too. Most likely caused by [this](https://github.com/QubesOS/qubes-builder-debian/commit/fa29b18c3e11fa9e0a45cae03ba575ac815e5415) commit.

**Comment by marmarek** [comment]
Specifically the problem about qubes-mgmt-salt package is because the package is built only for "all" architecture, but buildinfo file is marked for amd64.
