### ISSUE TITLE
Cannot build Bionic template - incorrect keyring used

### ISSUE THREAD

**Issue by unman** [QubesOS/qubes-issues#4837]
### Qubes OS version:
R4.0

### Affected component(s):
Qubes Builder

---

### Steps to reproduce the behavior:
Try to build Bionic template

### Expected behavior:

Packages are built and template is produced.

### Actual behavior:
Packages are built but template build fails.

```
 + mkdir -p chroot-vm-buster
 + echo '-> Installing debian build chroot...'
 + apt_https_pkgs=apt-transport-https,ca-certificates
 + COMPONENTS=
 + src/builder-debian/keys/buster-debian-archive-keyring.gpg bionic chroot-vm-buster
 + echo 'Error in debootstrap'
 + exit 1
 make[1]: *** [/home/user/qubes-builder/qubes-src/builder-debian/Makefile.qubuntu
 make: *** [Makefile:310: template-local-bionic] Error 1
```

### General notes:

The obvious problem is that building in a buster chroot uses the Debian keyring, but that wont wash for an Ubuntu install. The debootstrap fails immediately because the packages cant be verified.
I can't see at present *why* a buster chroot is being used at all for template building. Why does template build not use the same DIST as that used when building packages?

---

**Comment by marmarek** [comment]
buster chroot is [used for `reprepro`](https://github.com/QubesOS/qubes-builder-debian/blob/master/scripts/reprepro-wrapper) if you don't have it on your build host.
Do you have up to date builder-debian? I've [fixed](https://github.com/QubesOS/qubes-builder-debian/commit/472f75147e48759306263a0a06c1ed131074fc49) preparation of that chroot few days ago.

Previously chroot for reprepro was chosen pretty much randomly (the first distribution you build), which wasn't great (for example you end up with ancient reprepro from jessie).

**Comment by unman** [comment]
Sorry, my point wasn't clear, and my cut/paste foo lacking.
(I see now that buster is used as chroot for *all* template builds.)

The Ubuntu build fails because in the buster chroot, the keyring used for debootstrap is the debian keyring("src/builder-debian/keys/buster-debian-archive-keyring.gpg").
That should be easy to fix.

**Comment by unman** [comment]
All good now
