### ISSUE TITLE
Possible memory leak? VMs not giving back?

### ISSUE THREAD

**Issue by straussmaus** [QubesOS/qubes-issues#4847]
### Qubes OS version:

R4.0

### Affected component(s) or functionality:

Opening VMs

---

### Steps to reproduce the behavior:

Boot.
Open a lot of VMs until you are out of memory so you know your maximum.
Use them all for a few hours.
Close some of them.
Open them up again hours later.
Now you will not be able to start one of the Vms that you could start before.  So there is less memory available then there was before.

### Expected or desired behavior:

I expect to be able to open X VMs at one time on a system with Y RAM.

### Actual behavior:

X gets smaller over one session

### General notes:

If you can think of another explanation then maybe I am wrong.

---

**Comment by marmarek** [comment]
There are definitely memory leaks in a lot of software you use in VMs. Also some applications use more memory intentionally (accumulate some caches etc). Both things are very much visible for example on web browsers like Firefox or Chrome. Closing such applications from time to time helps.

There is nothing we can really do about it.

**Comment by brendanhoar** [comment]
> There is nothing we can really do about it.

Heh. Out of curiosity, I went off and googled: xen memory fragmentation

And then read posts from the first result, a 2011 thread on xen-devel...

...only at the end did I realize that your (Marek's) question originated the thread!  So, I suppose you've looked into these types of issues before... :)

B

**Comment by straussmaus** [comment]
@marmarek 

> There are definitely memory leaks in a lot of software you use in VMs.

But this memory leakage happens even if I close a VM and re-open it.  How can the memory leak persist after the VM is closed, unless the VM has access to dom0 memory?
