### ISSUE TITLE
Make it easier to run a single command in VM, regardless of characters in arguments

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#4850]
Right now both `qvm-run` tool and internal `vm.run()` API use `qubes.VMShell` service, which as the name suggests, use shell to launch the command. This means the command needs proper quotes/escapes if there are shell special characters (including spaces, dollars, etc). It is easy to miss, which may result in security issue. Similar issue resulted in [QSB#38](https://github.com/QubesOS/qubes-secpack/blob/master/QSBs/qsb-038-2018.txt).

If there is only a single command to run, there is very little reason to use shell at all.
Idea/plan:
 - [ ] add `QubesVM.run_with_args(*args, **kwargs)` function that will execute `*args` as a command with arguments (similar to `subprocess.run()`.
 - [ ] (R4.0) for now implement this as proper shell quoting using `shlex.quote()`
 - [ ] (R4.1+) later add a dedicated qrexec service, with command passed in the qrexec call argument, encoded to characters allowed in the argument in a way unambiguously separating arguments; using qrexec call argument will greatly simplify handling stdin/out to the actual command

The last point is tricky, as currently qrexec service name and argument are limited to 64 chars in total, which may be limiting for some commands. Additionally, only some characters are allowed.
Ideas for encoding the command and arguments:
1. Use NUL to separate command and arguments, then encode the whole string with base64 (modified to use something else instead of `/`, for example `-`).
2. Encode each argument separately with modified base64, then put them together, using yet another character as a separator.
3. Do not use base64-based encoding, instead come up with some escaping scheme. For example convert each non-alphanumeric character (including `-`) to -HH, where `HH` is hex code of the character, then join command and arguments with `+`

The first one is probably the easiest one to implement, the last one results in more readable (to human) call arguments.

Inspired by @v6ak

**Comment by DemiMarie** [comment]
64 characters is too low.  I routinely run commands with longer argument lists.

Can we declare `qubes.VMShell` and `qubes.VMRootShell` exempt from this restriction?  Alternatively, these could be handled using a specific keyword (distinct from `QUBESRPC`).  I prefer the latter option, as it makes it easier for my socket-based qrexec branch (and similar).

Also, this should be allowed for `qvm-run-vm` as well.

**Comment by marmarek** [comment]
It doesn't work this way at all. The problem is a field size in `trigger_service_params` structure: https://github.com/QubesOS/qubes-linux-utils/blob/24a25cce5f5f3fe38b27b7f888e9767c22e68300/qrexec-lib/qrexec.h#L93

So, there is no way of adding some exception for this service.

I mean, I definitely agree that 64 limit is too low, The 64 limit there is a blocker for moving the command to the call argument (instead of its stdin). Since this isn't the first time we hit this limit, I think we need to increase it (maybe even to arbitrary long argument at protocol level, and possibly limit it later at policy level). The problem is qrexec protocol change is a non-trivial task in terms of compatibility (we definitely don't want break ability to run commands in VM).

**Comment by DemiMarie** [comment]
Could we have some sort of handshake, whereby dom0 identifies the protocol version supported by the domU?

**Comment by marmarek** [comment]
[There is one already](https://github.com/QubesOS/qubes-linux-utils/blob/24a25cce5f5f3fe38b27b7f888e9767c22e68300/qrexec-lib/qrexec.h#L98-L100). But there are two problems with it:
 - both sides send the handshake (into the vchan buffer), in undefined order, then both receive what the other end sent
 -  if the version doesn't match, qrexec terminate the connection

This a bug in design, but it doesn't change the fact it is there.
I think the way forward is to:
1. Carefully analyze what really "undefined order" means, at implementation level. Specifically, whether implementation would allow dom0 part first wait what version domU part announce and only then respond.
2. The above applies not only to the control channel (dom0-domU), but also to the data channel - this may be harder, as both sides may be some VMs, so the question which part should send the handshake first is tricky.
3. Consider a fallback mechanism, where unknown messages are ignored, instead of breaking the connection (we already have message length in the message header).

We've done it better in GUI protocol, where you have MAJOR.MINOR version, where it is ok to communicate if MINOR version mismatch by ignoring unknown messages (one side could use knowledge of protocol version of the other side to send different messages, if that's important). Different MAJOR versions are not compatible, but the domU send the version first and dom0 (GUI VM) could choose to switch to some fallback handling. We didn't needed that yet.

**Comment by tasket** [comment]
Sounds good. May I make a suggestion (perhaps for another issue)...?

When coding sparsebak I found using `qvm-run` to be cumbersome because it does not handle command content (all of the command and args together) in the same manner as `sh -c` or `ssh`. The latter two take the remainder of the command line as arguments for the command, while qvm-run requires everything that is remote to appear as a (local) single argument (i.e. in quotes).

This meant that `qvm-run` could not be used interchangeably with sh and ssh (because the target can be local dom0, local guestvm, or remote) without special quoting and escaping tricks that in the end were impractical. I had to work around this qvm-run limitation by writing the command to a file, then sending the file to vm or remote if required, and finally issuing a command to execute the file.

It would have helped if `qvm-run` had an option like `-c` where everything afterward was taken as remote command content.

**Comment by marmarek** [comment]
Actually `sh -c`  behavior is a mix of this, and the current `qvm-run` behavior. If after `-c` there is only one argument, it is interpreted as a full command and word splitting etc rules applies to it.
This means you _can_ use qvm-run and sh -c interchangeably, by using this first form and always providing the command as a single argument.

**Comment by v6ak** [comment]
The sh -c … command is like qvm-run, but enriched by ability to pass additional arguments (that are ignored unless explicitly used):

~% sh -c echo ajf

~% sh -c 'echo $1' a b
b

If you want to replicate sh's behavior, you will be able to use the run_with_args with ['sh', '-c', …the args you want…]. Or you can use another shell (bash, zsh, dash, …) if you wish. While running shell commands is not the best way to be platform-agnostic, the way of run_with_args seems to be as close as possible.

By the way, it is likely going to be a PITA to implement this for Windows (if someone decides to). As far as I remember, Windows have no such thing as parameter list on system level. They just pass argument string and let the app to process it on its own. Various apps could use various escaping schemes in theory. Fortunately, there seem to be a single convention in practice.

**Comment by tasket** [comment]
But using that first form means an extra layer of quoting. Or I have to call it from python without `shell=True` which is a non-starter bc I often need pipes between commands.

**Comment by v6ak** [comment]
I probably don't get what are you missing… Maybe you would like to have QubesVM.run_with_args(*args, **kwargs) exposed to qvm-run?

If you have both QubesVM.run(*args, **kwargs) and QubesVM.run_with_args(*args, **kwargs), either accessible via API or via commandline tool(s) like qvm-run, I believe you have all you need. If you don't think so, provide some example that disprove my opinion.

**Comment by DemiMarie** [comment]
From dom0, it is trivial to execute an arbitrary command in any VM, using `qrexec-client`

Simple script:

```bash
s='user:exec'
for i; do
    s+=\'${i//\'/\'\\\'\'}\'
done
qrexec-client "-tTd$target_domain" "$s"
```
`qvm-run` could (and should) use this internally.  Since the command used is `exec`, there is no need to worry that the remote VM might accidentally interpret the command as an RPC call.

**Comment by tasket** [comment]
@v6ak You're right about sh -c. I was probably thinking about ssh which works as I described, in addition to doing a plain `subprocess.check_call` when local is targeted. The choice seemed to be no prefix (local), an ssh prefix or a qvm-run prefix (there is also a case for ssh via qvm-run).

The main issue is having to combine shell features like piping in a combined way (localy to/from qvm-run or ssh, and remotely, all together) without using a lot of extra python code (Popen + loops) to glue the pieces together. Saying 'supply the args with command in quotes' doesn't work, because some quotes also have to go to the guest/remote and (surprise!) the guestvm may be controlling an actual remote machine... this is too complex to layer single and double quotes on top of what is used in the python app.

@DemiMarie That's interesting, although its the kind of escaping technique I decided to forgo in favor of transporting a script file.

FWIW, I do have a reasonable workaround as I described, so my input here is just a suggestion. It would be nice if shell-targeted command lines could be interchanged with Unix exec tools, especially ssh. This means any quote-removal, escaping, parameter uptake and expansion would be handled the same way.

**Comment by v6ak** [comment]
For piping and other shell features, you will be able to use vm.run_with_args(['sh', '-c', 'some-command -- "$1" "$2" | some-other-command -- "$3" > "$4"', arg1, arg2, arg3, arg4]). This is the universal way.

I am sometimes confused by behavior of tools like ssh and watch (and maybe also adb shell). They perform some weird combo of safe processing and command values interpretation and I never know what is the right way to perform some generic command this way. I am not sure that it is a good idea to add something like this to Qubes OS.

Regards,
Vít Šesták 'v6ak'

On March 5, 2019 10:27:37 PM GMT+01:00, tasket <notifications@github.com> wrote:
>@v6ak You're right about sh -c. I was probably thinking about ssh which
>works as I described, in addition to doing a plain
>`subprocess.check_call` when local is targeted. The choice seemed to be
>no prefix (local), an ssh prefix or a qvm-run prefix (there is also a
>case for ssh via qvm-run).
>
>The main issue is having to combine shell features like piping in a
>combined way (localy to/from qvm-run or ssh, and remotely, all
>together) without using a lot of extra python code (Popen + loops) to
>glue the pieces together. Saying 'supply the args with command in
>quotes' doesn't work, because some quotes also have to go to the
>guest/remote and (surprise!) the guestvm may be controlling an actual
>remote machine... this is too complex to layer single and double quotes
>on top of what is used in the python app.
>
>@DemiMarie That's interesting, although its the kind of escaping
>technique I decided to forgo in favor of transporting a script file.
>
>FWIW, I do have a reasonable workaround as I described, so my input
>here is just a suggestion. It would be nice if shell-targeted command
>lines could be interchanged with Unix exec tools, especially ssh. This
>means any quote-removal, escaping, parameter uptake and expansion would
>be handled the same way.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/QubesOS/qubes-issues/issues/4850#issuecomment-469863986

-- 
Sent from my fruity BlackBerry phone. Please excuse my brevity.

**Comment by marmarek** [comment]
As for piping and python subprocess, it doesn't require that much of a code, just one statement per command:
```python
p1 = subprocess.Popen(..., stdout=subprocess.PIPE)
p2 = subprocess.Popen(..., stdin=p1.stdout, stdout=open(...))
```

@DemiMarie I'd strongly recommend against using `qrexec-client` directly, it's internal tool and it's a massive foot gun (as you already know in #4852). Furthermore, ability to run arbitrary command, instead of a qrexec service is a legacy feature which we fade away slowly. This very ticket is a part of it.

**Comment by v6ak** [comment]
My point was: You can get the full power of shell (not just pipes, but also subshells, variables, etc.) with the run_with_args and sh -c. You probably could do it by multiple calls in Python, but it is not that universal. You probably could implement everything that way (although it might result in a more complex code) but the client would become a proxy. It is probably a minor penalty for inter-VM communication within a single physical computer, but it could be a major hit for anything over network (e.g., ssh that was concerned about or maybe Qubes Air in future).

**Comment by DemiMarie** [comment]
@marmarek would it be possible to make `qrexec-client` a general-purpose tool?  `qrexec-client-vm` is.

**Comment by marmarek** [comment]
It should be sufficiently easy to add `qrexec-client-vm` tool to dom0 too. Internally it will be a different thing, but the interface can be the same.
But, given the goal of moving the whole user interface out of dom0, in the end user will have direct access to `qrexec-client-vm` only anyway.

**Comment by marmarek** [comment]
This all is already implemented.
