### ISSUE TITLE
Qubes Update cannot report cases where dnf has dependency conflicts

### ISSUE THREAD

**Issue by strugee** [QubesOS/qubes-issues#4851]
### Qubes OS version:

R4.0

### Affected component(s) or functionality:

Qubes Update Manager (Salt integration?)

---

### Steps to reproduce the behavior:

1. Have a template that has dependency conflicts
2. Upgrade the template in Qubes Updater

### Expected or desired behavior:

Qubes Updater reports to me that the template needs manual intervention.

### Actual behavior:

Qubes Updater reports that the upgrade went okay, but examining the Salt output indicates that no packages were installed and the update badge in my status bar does not go away.

### General notes:

Log from manually upgrading in the template:

```
$ sudo dnf upgrade
Fedora Modular 29 - x86_64 - Updates             21 kB/s |  13 kB     00:00    
Fedora 29 - x86_64 - Updates                     30 kB/s |  12 kB     00:00    
Dependencies resolved.

 Problem 1: cannot install the best update candidate for package devscripts-2.18.4-1.fc29.x86_64
  - nothing provides perl(GitLab::API::v4::Constants) needed by devscripts-2.19.2-3.fc29.x86_64
 Problem 2: package qemu-img-2:3.0.0-3.fc29.x86_64 requires libxenctrl.so.4.11()(64bit), but none of the providers can be installed
  - package qemu-img-2:3.0.0-3.fc29.x86_64 requires libxenguest.so.4.11()(64bit), but none of the providers can be installed
  - package qemu-img-2:3.0.0-3.fc29.x86_64 requires libxentoolcore.so.1()(64bit), but none of the providers can be installed
  - package qemu-img-2:3.0.0-3.fc29.x86_64 requires libxendevicemodel.so.1()(64bit), but none of the providers can be installed
  - cannot install both xen-libs-4.11.1-1.fc29.x86_64 and xen-libs-2001:4.8.4-8.fc29.x86_64
  - cannot install both xen-libs-4.11.0-7.fc29.x86_64 and xen-libs-2001:4.8.4-8.fc29.x86_64
  - cannot install the best update candidate for package xen-libs-2001:4.8.4-8.fc29.x86_64
  - cannot install the best update candidate for package qemu-img-2:3.0.0-1.fc29.x86_64
================================================================================
 Package            Architecture   Version                Repository       Size
================================================================================
Skipping packages with conflicts:
(add '--best --allowerasing' to command line to force their upgrade):
 xen-libs           x86_64         4.11.0-7.fc29          fedora          541 k
 xen-libs           x86_64         4.11.1-1.fc29          updates         539 k
Skipping packages with broken dependencies:
 devscripts         x86_64         2.19.2-3.fc29          updates         578 k
 qemu-img           x86_64         2:3.0.0-3.fc29         updates         880 k

Transaction Summary
================================================================================
Skip  4 Packages

Nothing to do.
Complete!
```

I suspect this might be related to #1648 and will file a separate bug if that's the case, but in any case Qubes Updater should at least report this condition to me.

---

### I have consulted the following relevant [documentation](https://www.qubes-os.org/doc/):

N/A

### I am aware of the following related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues:

Bug 1648, bug 4674 (not a duplicate because in this case it's not reported as an update failure _at all_)

**Comment by marmarta** [comment]
@marmarek, it looks like the salt incorrectly reports success

**Comment by marmarta** [comment]
@marmarek , has anything changed with error reporting by salt?

**Comment by marmarek** [comment]
I've looked into it more, and it looks like desired `dnf` behavior. `dnf update` will exit with code 0 even if some updates cannot be installed. `dnf update --best` will exit with error (code 1) in that case, but it will not install _any_ updates then. It is possible to set [`best=True` in `/etc/dnf/dnf.conf`](https://dnf.readthedocs.io/en/latest/api_conf.html#dnf.conf.Conf.best). And in fact this is planned to be done by default in Fedora 31: https://fedoraproject.org/wiki/Changes/DNF_Default_Best

So, I'd say it is an upstream issue, already planned to be resolved there.
