### ISSUE TITLE
unable to reset pci device 0000:00:14.0: no FLR, PM reset or bus reset available, see /var/log/libvirt/libxl/libxl-driver.log for details

### ISSUE THREAD

**Issue by Beckon5** [QubesOS/qubes-issues#4853]
**Qubes Os version:**

4.0.1

**Affected TemplateVMs:**

fedora-29 based on standard sys-usb

**Actual behavior:**

Standard sys-usb doesn't start with error: `Start failed: internal error: Unable to reset PCI device 0000:00:14.0: no FLR, PM reset or bus reset available. see /var/log/libvirt/libxl-driver.log for details`

During the installation of system(system configuration) was error: 
```
['systemctl', 'start', 'qubes-vm@sys-usb.service'] failed:
stdout:""
stderr: "Job for qubes-vm@sys-usb.service failed because the control process exited with error code.
See "systemctl status qubes-vm@sys-usb.service" and "journalctl -xe" for details
```

**Comment by marmarek** [comment]
See this FAQ entry: https://www.qubes-os.org/faq/#i-created-a-usbvm-and-assigned-usb-controllers-to-it-now-the-usbvm-wont-boot

**Comment by andrewdavidwong** [comment]
Closing as "not an issue." If you believe this is a mistake, please leave a comment, and we'll be happy to take another look. Thank you.

**Comment by Aporbel** [comment]
same error when I tried to connect pci usb  controller to any VM.
I did qvm-device pci attach <target_vm> dom0:01_11.0 --persistent 
Try to start and have this error.

**Comment by marmarek** [comment]
@Aporbel see the FAQ entry I've linked above - it contains solution. And when USB VM is created automatically (like, during installation), it is already applied.
