### ISSUE TITLE
spontaneous resets  at randome time

### ISSUE THREAD

**Issue by JosyJosy** [QubesOS/qubes-issues#4854]
### Qubes OS version:
3.2.1

### Affected component(s) or functionality:

---

### General notes:

Hello. Sorry for non-compliance with the template. I am very tired and write this on a faulty OS

I installed QubesOS on a weak old computer. Is have only 3 GB of RAM, old intel CPU and does not support hardware virtualization, but 3.2.1 can works on similar computers, as far as I know. 

At the end of the installation, after VM configuration, Noise consisting of multi-colored pixels appeared on the GUI elements. Then the computer restarts. I try to install 4.0.1 and 3.2.1 but this problem remained.

The configuration of VMs took place normally and only at the end of the process did a certain error occur with setting up the network or the user ...  Of not sure. The stage after the configuration of the VMs

I was able to complete the installation 3.2.1 only by selecting the option "do not configure anything (for advanced users)". Then the installation was completed successfully and i was able to work in OS.
So I avoided the problem step at the end of the configuration. VMs were created during previous attempts, so when the system was booted, I saw all the virtual machines in the manager. They work great.

No other settings besides “do not configure anything” helped to avoid a crash. I tried everything. Even if you uncheck all the settings, this error occurred.

During operation, after a random time, a similar interface failure occurs. The desktop is covered with rare grid of red dots, individual GUI elements are covered with black and other colors when you hover over them. When you hover the cursor over the elements, they are covered with noise. Some windows disappear after a crash.

Crash can happen anytime. A second after the system load, or a few tens of minutes or hour. Usually in 5-10 minutes. If during a crash, do not move the mouse and do not press anything, the computer continues to work, but the noise does not pass.if i press something during a crash, the computer will soon restart.

I try to turned off all the VMs, but crush was still happening. It seems, on the contrary, about high load it occurs much less frequently.

Otherwise the system works fine. Even VMs have been configured. If you could avoid reboots, everything is just fine. 

Sometimes Dom0 reports in VMs manager that he is not getting enough RAM. It usually has 1600-1200Mb, but i think that this problem is not related to RAM. Failures occur without correlation with the load on the RAM. They seem random

I have an assumption that their result is an dom0 interface interaction. Sometimes I work long without rebooting when I interact only with the browser. But this is a dubious guess.

---

**Comment by 0spinboson** [comment]
1. what hardware are you using?
2. until it is clear that this is actually a bug, rather than a config issue, you're probably better off asking for help here: https://groups.google.com/forum/#!forum/qubes-users

**Comment by JosyJosy** [comment]
>     1. what hardware are you using?
> 
>     2. until it is clear that this is actually a bug, rather than a config issue, you're probably better off asking for help here: https://groups.google.com/forum/#!forum/qubes-users

Hello! Thanks. I update hardware information is my issue, I'm trying to add text until another reboot occurs. I will supplement it as far as possible.

**Comment by andrewdavidwong** [comment]
Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this does not appear to be suitable for `qubes-issues`. We ask that you please send this to the `qubes-users` [mailing list](https://www.qubes-os.org/support/) instead. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a brief comment explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.
