### ISSUE TITLE
"Check for qube updates by default" in Qubes Global Settings keeps re-enabling itself

### ISSUE THREAD

**Issue by t4777sd** [QubesOS/qubes-issues#4856]
### Qubes OS version:

4.0 latest

### Affected component(s) or functionality:

Update function

---

### Steps to reproduce the behavior:

Uncheck this and also click disabling updates in all qubes. Restart the computer and you will see that it has been checked again.

### Expected or desired behavior:

It should stay unchecked and the update notifier should no longer notify of updates. 

### Actual behavior:
Currently it keeps re-checking and I keep getting notification of updates.

**Comment by andrewdavidwong** [comment]
I also experience this.

**Comment by SvenSemmler** [comment]
me2

**Comment by simonbytes** [comment]
It's not a bug, it's a feature.

**Comment by andrewdavidwong** [comment]
> It's not a bug, it's a feature.

Why do you say that?

**Comment by marmarta** [comment]
@marmarek, this is the bug caused by the lack of load_stage in app.py.
