### ISSUE TITLE
TemplateVM packages not available from some mirrors?

### ISSUE THREAD

**Issue by unman** [QubesOS/qubes-issues#4858]
### Qubes OS version:

R4.0

### Affected component(s) or functionality:
Infrastructure

---

### Steps to reproduce the behavior:

On system with no debian-9 template installed, attempt to install template with:
`sudo qubes-dom0-update --enablerepo=qubes-templates-itl qubes-template-debian-9`

### Expected or desired behavior:

Debian-9 template will be installed

### Actual behavior:

Error message:
No match for argument: qubes-template-debian-9
Error:  Unable to find a match

### General notes:

Reported on qubes-users mailing list by [Sphere](https://www.mail-archive.com/qubes-users@googlegroups.com/msg27042.html) 

I initially thought that this was a Whonix error, since using a Fedora qube as update worked fine for me , whether over Tor or not.
However, I tested on a few different boxes, and sometimes encountered the same error, with what appears to be exactly the same configuration.
The same error (sometimes) occurs using qubes-templates-itl-testing.

In *every* case it is possible to install qubes-template-debian-8

Inspection of the repositories at yum.qubes-os.org confirms that the templates are there.

This suggest to me that there is some issue with mirroring

---

**Comment by MystesofEternity** [comment]
I would like to add that this issue also exists for the case of fedora-29 with also the same actual behavior
But I could not fully test this as my circumstances cannot afford to have fedora-29 deleted for the sake of meeting Steps to reproduce the behavior

**Comment by simonbytes** [comment]
Maybe the vulnerable template images are moved or deleted, because of [QSB 46](https://www.qubes-os.org/news/2019/01/23/qsb-46/):
```
+------------------------------------------------------------------------------+
|     Old (Vulnerable)        |                  New (Fixed)                   |
| --------------------------- | ---------------------------------------------- |
| qubes-template-debian-8     | qubes-template-debian-8-4.0.1-201901231241     |
| qubes-template-debian-9     | qubes-template-debian-9-4.0.1-201901230644     |
| qubes-template-whonix-gw-14 | qubes-template-whonix-gw-14-4.0.1-201901231238 |
| qubes-template-whonix-ws-14 | qubes-template-whonix-ws-14-4.0.1-201901231238 |
+------------------------------------------------------------------------------+
```

**Comment by heinrich-ulbricht** [comment]
I seem to have this with the Debian 10 template. It cannot be found.

```
[user@dom0 ~]$ sudo qubes-dom0-update --enablerepo=qubes-templates-itl qubes-template-debian-10
Using sys-whonix as UpdateVM to download updates for Dom0; this may take some time...
No Match for argument qubes-template-debian-10
Nothing to download
```

:(

**Comment by marmarek** [comment]
This normally means you have the template already installed. It may happen that you have the matching package installed but you removed/renamed the template. Check `rpm -q qubes-template-debian-10` - if it lists the package, but you don't really have the template present (qvm-ls doesn't list it), you need to cleanup leftovers of the package: `rpm -e --noscripts qubes-template-debian-10`, then install it normally.

**Comment by marmarek** [comment]
@andrewdavidwong can you add the above to some common problems list? FAQ perhaps?

**Comment by heinrich-ulbricht** [comment]
@marmarek Spot on, thank you, problem solved.

For the record the console output:
```
[user@dom0 ~]$ rpm -q qubes-template-debian-10
qubes-template-debian-10-4.0.1-201910110047.noarch
[user@dom0 ~]$ qvm-ls | grep debian-10
debian-10-minimal                Halted   TemplateVM    black   -                                -
[user@dom0 ~]$ rpm -e --noscripts qubes-template-debian-10
error: can't create transaction lock on /var/lib/rpm/.rpm.lock (Permission denied)
[user@dom0 ~]$ sudo rpm -e --noscripts qubes-template-debian-10
warning: file /var/lib/qubes/vm-templates/debian-10/whitelisted-appmenus.list: remove failed: No such file or directory
warning: file /var/lib/qubes/vm-templates/debian-10/vm-whitelisted-appmenus.list: remove failed: No such file or directory
warning: file /var/lib/qubes/vm-templates/debian-10/root.img.part.03: remove failed: No such file or directory
warning: file /var/lib/qubes/vm-templates/debian-10/root.img.part.02: remove failed: No such file or directory
warning: file /var/lib/qubes/vm-templates/debian-10/root.img.part.01: remove failed: No such file or directory
warning: file /var/lib/qubes/vm-templates/debian-10/root.img.part.00: remove failed: No such file or directory
warning: file /var/lib/qubes/vm-templates/debian-10/netvm-whitelisted-appmenus.list: remove failed: No such file or directory
warning: file /var/lib/qubes/vm-templates/debian-10/icon.png: remove failed: No such file or directory
warning: file /var/lib/qubes/vm-templates/debian-10/clean-volatile.img.tar: remove failed: No such file or directory
warning: file /var/lib/qubes/vm-templates/debian-10/apps.templates: remove failed: No such file or directory
warning: file /var/lib/qubes/vm-templates/debian-10/apps.tempicons: remove failed: No such file or directory
warning: file /var/lib/qubes/vm-templates/debian-10/apps: remove failed: No such file or directory
warning: file /var/lib/qubes/vm-templates/debian-10: remove failed: No such file or directory
[user@dom0 ~]$ sudo qubes-dom0-update --enablerepo=qubes-templates-itl qubes-template-debian-10
Using sys-whonix as UpdateVM to download updates for Dom0; this may take some time...
```
And it started downloading.

**Comment by andrewdavidwong** [comment]
> @andrewdavidwong can you add the above to some common problems list? FAQ perhaps?

Done! https://github.com/QubesOS/qubes-doc/commit/c7c40636543c3c82862a14a78edf27f1c7638458
