### ISSUE TITLE
Updating AppVM Removes some App Menus

### ISSUE THREAD

**Issue by dylangerdaly** [QubesOS/qubes-issues#4861]
### Qubes OS version:
R4.0

### Affected component(s) or functionality:
App Menus

---

### Steps to reproduce the behavior:
Updating TemplateVMs remove App Menus, such as Slack, Signal etc.

### Expected or desired behavior:
Updating TemplateVMs should re-run `qvm-sync-appmenus`

### Actual behavior:
After updating the TemplateVM, I need to manually run `qvm-sync-appmenus <templateVM Name>`

### General notes:

---

**Comment by iprid23** [comment]
@dylangerdaly 
Confirming that this happens and is reproducible all the time.

**Comment by marmarek** [comment]
What template? How disappearing application was installed?
