### ISSUE TITLE
Installation - Stuck

### ISSUE THREAD

**Issue by Yousha** [QubesOS/qubes-issues#4869]
### Qubes OS version:
4.0.1 64bit

### Affected component(s) or functionality:

---

### Steps to reproduce the behavior:

1) Download QubesOS ISO file
2) Write the ISO file into the FlashDisk (via Unetbootin or Burnaware)
3) Boot the FlashDisk (BIOS or EFI)

### Expected or desired behavior:

Start QubesOS installer

### Actual behavior:

Stucks
Screenshot:
https://ibb.co/gWGL9yT

### General notes:

System:
x64 Intel Hardware - 12GB RAM
UEFI
AData 16GB FlashDisk - USB3

Screenshot:
https://ibb.co/gWGL9yT

---

**Comment by andrewdavidwong** [comment]
Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this does not appear to be suitable for `qubes-issues`. We ask that you please send this to the `qubes-users` [mailing list](https://www.qubes-os.org/support/) instead. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a brief comment explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.

**Comment by Yousha** [comment]
It is, because it's not possible to install QubesOS via USB3 socket and EFI mode.
Ok anyway.
