### ISSUE TITLE
qubes-builder asking for Username and Password for marmarek/qubes-anaconda-addon.git

### ISSUE THREAD

**Issue by Simon-Davies** [QubesOS/qubes-issues#4870]
I'm trying to create a new installation ISO as the latest installation ISO does not install in UEFI mode on my Dell XPS 15 Intel i9. I just get a black screen.

**Comment by marmarek** [comment]
It may not be the best moment to build R4.1 based on fc29. We're exactly in the middle of upgrading installer - some repositories are already upgraded, but not all. Especially, you'll need https://github.com/QubesOS/qubes-anaconda/pull/1 and https://github.com/QubesOS/qubes-installer-qubes-os/pull/29
