### ISSUE TITLE
qubes-builder not working for QubesOS branch on Fedora 29

### ISSUE THREAD

**Issue by Simon-Davies** [QubesOS/qubes-issues#4871]
Error: Building packages for stretch not supported by any of configured plugins.

**Comment by marmarek** [comment]
Looks like builder-debian plugin is not enabled. I assume you've used `setup` script, right? Wasn't it enabled by default?

**Comment by Simon-Davies** [comment]
I didn't use the setup script. I was following the old instructions.

I've just git cloned your building and following the instructions here seems to be working so far.

**Comment by marmarek** [comment]
Ok, it was missing in example config.

**Comment by Simon-Davies** [comment]
Thank you.

**Comment by Simon-Davies** [comment]
I'm getting the same error.

Does BUILDER_PLUGINS = builder-rpm need to be changed to the below:

BUILDER_PLUGINS = builder-rpm builder-debian

**Comment by marmarek** [comment]
Yes...

**Comment by Simon-Davies** [comment]
Thanks
