### ISSUE TITLE
Mute audio whenever the screen is locked

### ISSUE THREAD

**Issue by 4Y8Yp8P2EyrkA3VNnBfYfVYnZYigXC5i** [QubesOS/qubes-issues#4872]
### Qubes OS version:

R4.0

### Affected component(s) or functionality:

dom0 XScreenSaver ver 5.42-1.fc25

---

### Steps to reproduce the behavior:

Whilst having default configurations for the screensaver, play anything with audio, and lock the screen by manually folding the laptop or using the "Lock Screen" option.

### Expected or desired behavior:

Audio should no longer play.

### Actual behavior:

Audio persists to play.

### General notes:

Using Xfce 4.12

I am not sure if this is a bug or an intentional feature. However, I think people shouldn't be able to detect any distinguishable activity happening within the computer unless they have the password.

There also doesn't seem to be an option to mute the screensaver.

This is also the first time I opened up an issue. Please tell me if I overlooked certain steps.

---

### I have consulted the following relevant [documentation](https://www.qubes-os.org/doc/):

The Security, Privacy, Configuration, and Customization Guides within User Documentation and Security Information and System of Developer Documentation.

**Comment by andrewdavidwong** [comment]
I believe that XScreenSaver exhibits this behavior (not muting audio when locked) on all OSes on which it's used. (In general, I am not aware of any screen locker that attempts to affect audio.) Therefore, it is either not a bug or not our bug.

However, I'll interpret this is as a feature request for muting audio whenever the screen is locked.

**Comment by marmarek** [comment]
If anything, it should be a feature request for xscreensaver (or other favorite screen locker), there is nothing Qubes specific here.

But then, I think it should be optional at best, as there are definitely use cases for keeping music on while locking the laptop. And also to still hear notification sounds.

**Comment by andrewdavidwong** [comment]
> If anything, it should be a feature request for xscreensaver (or other favorite screen locker), there is nothing Qubes specific here.

Closing as "not our feature request" (but labeling `not our bug`, since we don't have enough issues of this type to merit a separate label, IMO).
