### ISSUE TITLE
Xenial build of vmm-xen fails

### ISSUE THREAD

**Issue by unman** [QubesOS/qubes-issues#4875]
### Qubes OS version:

R4.0

### Affected component(s) or functionality:

qubes-builder

---

### Steps to reproduce the behavior:

Use setup to select Xenial build.
make get-sources
make qubes-vm

### Expected or desired behavior:

Packages will be built.

### Actual behavior:

Build of vmm-xen-vm fails.
```
mk-build-deps: Unable to install xen-build-deps at /usr/bin/mk-build-deps line 402.
mk-build-deps: Unable to install all build-dep packages
make[2]: *** [/home/user/qubes-builder/qubes-src/builder-debian//Makefile-legacy.debian:39: dist-build-dep] Error 1
--> build failed!
make[1]: *** [Makefile.generic:180: packages] Error 1
make: *** [Makefile:217: vmm-xen-vm] Error 1
```

### General notes:

The build succeeds for Debian and for bionic.

---

**Comment by desci** [comment]
Output of

```bash
[user@fedora-29-builder qubes-builder]$ cat build-logs/vmm-xen-vm-xenial.log
```

https://pastebin.com/xC8yvQmG

---

Previous steps

- [x] Clone of latest untouched (but upgraded) _fedora-29 TemplateVM_ labeled **fedora-29-builder**

```bash
[user@fedora-29-builder ~]$ sudo dnf install gnupg git createrepo rpm-build make wget rpmdevtools python2-sh dialog rpm-sign dpkg-dev debootstrap PyYAML devscripts perl-Digest-MD5 perl-Digest-SHA
[user@fedora-29-builder ~]$ sudo dnf install git createrepo rpm-build make wget rpmdevtools python2-sh dialog rpm-sign gnupg
[user@fedora-29-builder ~]$ git clone git://github.com/QubesOS/qubes-builder
[user@fedora-29-builder ~]$ cd qubes-builder/
[user@fedora-29-builder ~]$ vim example-configs/qubes-os-r4.1.conf
```

- [x] Changed **DISTS_VM ?= fc29 stretch** to **DISTS_VM ?=**

```bash
[user@fedora-29-builder ~]$ ./setup
```

- [x]  Qubes Release 4.1
- [x] QubesOS/qubes
- [x] current
- [x] 'Yes' to to only build templates
- [x] xenial
- [x] builder-debian (tried first without and second with mgmt-salt)
- [x] 'Yes' to download and merge sources

```bash
[user@fedora-29-builder ~]$ make install-deps
[user@fedora-29-builder ~]$ make get-sources
[user@fedora-29-builder ~]$ make qubes-vm
```

Above error sent to pastebin shown on stderr.

**Comment by desci** [comment]
Seems like the relevant part of the log is the ```E: Can not write log (Is /dev/pts mounted?) - posix_openpt (2: No such file or directory)```

**Comment by marmarek** [comment]
Looks like a problem with build dependencies - it tries to remove `xen-build-deps`, instead of installing required packages. @unman any idea what is missing?

**Comment by marmarek** [comment]
If you want to use the template on R4.0, you need to choose Qubes Release 4.0

**Comment by desci** [comment]
Following @marmarek 's advice, using **Qubes Release 4.0**, the `make qubes-vm` command succeeded.

Now the `make template` gives an error. This is the _tail_ of _build-logs/templte-xenial.log_:

```
Err:11 https://deb.qubes-os.org/r4.0/vm xenial/main amd64 Packages
  404  Not Found
Ign:12 https://deb.qubes-os.org/r4.0/vm xenial/main all Packages
Ign:13 https://deb.qubes-os.org/r4.0/vm xenial/main Translation-en
Reading package lists...
W: The repository 'https://deb.qubes-os.org/r4.0/vm xenial Release' does not have a Release file.
E: Failed to fetch https://deb.qubes-os.org/r4.0/vm/dists/xenial/main/binary-amd64/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.
Removing 'local diversion of /sbin/initctl to /sbin/initctl.distrib'
make[1]: *** [Makefile:64: rootimg-build] Error 100
```

**Comment by unman** [comment]
> Seems like the relevant part of the log is the E: Can not write log (Is /dev/pts mounted?) - posix_openpt (2: No such file or directory)

This isn't the problem - that warning appears on every apt call. 

> 
> Err:11 https://deb.qubes-os.org/r4.0/vm xenial/main amd64 Packages
>   404  Not Found

There are *no* Xenial repositories on deb.qubes-os.org.
When you run setup, do not select anything on the "PreBuilt Packages" page.

The build still fails

**Comment by desci** [comment]
I have applied @unman advice and `make template` worked for me

If you want I can send the build-logs and update the step to step I did on my first comment

**Comment by unman** [comment]
Confirmed build of vmm-xen now works.
