### ISSUE TITLE
tzdata needs updates

### ISSUE THREAD

**Issue by h01ger** [QubesOS/qubes-issues#4876]
### Qubes OS version:

3.2 but also 4.0 as this is a general problem, read on:

### Affected component(s) or functionality:

tzdata

### Steps to reproduce the behavior:

timedatectl set-timezone Africa/Casablanca

### Expected or desired behavior:

the time is correct.

### Actual behavior:

the time is wrong, because the timezone data for Casablanca has changed since fc23 was out.

### General notes:

This is not limited to Qubes 3.2 nor to Casablanca, as timezone changes occur around the world all the time, so the tzdata package needs to be maintained by the Qubes team once the dom0 distribution because unmaintained upstream.

Luckily maintaining tzdata backports should be pretty trivial, a rebuild from whatever is in latest Fedora releases should be enough.

---

**Comment by grote** [comment]
Having the same issue with `America/Sao_Paulo`. Since today, the timewidget from `dom0` is showing a wrong time.

Also compare the output of `sudo timedatectl`:
* `dom0`: `Time zone: America/Sao_Paulo (-02, -0200)`
* AppVM: `Time zone: America/Sao_Paulo (-03, -0300)`
