### ISSUE TITLE
USB 3.0 issue for Librem 13 v2

### ISSUE THREAD

**Issue by skaven-gear** [QubesOS/qubes-issues#4877]
### Qubes OS version: 
R4.0 

### Affected component(s) or functionality:
USB 3.0

---

### Steps to reproduce the behavior:
Try to connect a HDD usb 3.0 to the right USB port

### Expected or desired behavior:
Mount and use the HDD

### Actual behavior:
HDD unavailable (I cannot see it anywhere, even if USB port deliver 5V)  

### General notes:
This is issue is not reproductive with PureOS (both USB ports will work).
However, I notice others unexpected behaviors with USB ports (try to connect USB HDD or USB stick) at the CoreBoot step (not all keys are recognized, this change with ... hazard???, and my TAILS encrypted USB stick will not work at CoreBoot step nor with Qubes nor with PureOS).
CoreBoot is up to date.

**Comment by andrewdavidwong** [comment]
Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this does not appear to be suitable for `qubes-issues`. We ask that you please send this to the `qubes-users` [mailing list](https://www.qubes-os.org/support/) instead. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a brief comment explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.

**Comment by skaven-gear** [comment]
As explained this is a bug specific to QubesOs on Librem desktop, so I doubt than the mailing list can help here.

**Comment by andrewdavidwong** [comment]
Please make sure to check the USB documentation:

https://www.qubes-os.org/doc/usb/

**Comment by skaven-gear** [comment]
I must have linked it here, so sorry,
but yes, I know this doc, thanks you.

As said, the HDD is totally unavailable for the right USB port, even it is available whith the left USB port.
So, nor the sys-usb nor the Dom0 seem to see it, nor via command line nor via the interface.

**Comment by sorandom** [comment]
In the past I needed to put it into quirks mode to get my USB3 hard drive to work properly:

in template of whatever runs sys-usb, using XXXX:YYYY USB ID from lsusb in usb qube:
# /etc/modprobe.d/blacklist_uas_name_of_harddrive.conf
# from https://ubuntuforums.org/showthread.php?t=2307662
options usb-storage quirks=XXXX:YYYY:u

**Comment by sorandom** [comment]
For what it's worth, on mine, plugging in a usb3 device on the right USB port connects to usb qube usb3 bus. On the left port, it connects to the usb2 bus despite appearing to be a usb3 port.

**Comment by xaki23** [comment]
would be interesting to know what devices are being used here.
as in, device IDs for the actual sticks/HDDs.

also useful tests would be to check if it works with a hub in between, separate for USB 3 and USB 2 hubs.
