### ISSUE TITLE
qubes devices widget doesn't show attached block devices

### ISSUE THREAD

**Issue by GammaSQ** [QubesOS/qubes-issues#4884]
### Affected component(s) or functionality:
qubes devices widget

output of `rpm -q qubes-desktop-linux-manager` (in dom0):

    qubes-desktop-linux-manager-4.0.15-1.fc25.noarch

---

### Steps to reproduce the behavior:
The same behaviour might happen randomly. However, I can reliably reproduce it by sending qubes to sleep, attaching a USB-drive, and waking up again.

### Expected or desired behavior:
`qvm-block`/`qvm-usb` showing the same devices as the qubes devices widget does. (I would understand a usb-drive attached during sleep not showing up, as long as it appears if i replugg it when the computer is awake.)

### Actual behavior:
qubes devices widget might stop reporting attached devics. `qvm-block` reports the usb-drive correctly, but it doesn't show up in the qubes devices widget.

### General notes:
The same behavior might occur randomly, i.e. a stick not showing up after attaching (while the computer is awake), but getting a notification it was attached and `qvm-block` reporting it.

---

### I am aware of the following related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues:

https://github.com/QubesOS/qubes-issues/issues/4849 (qubes devices widget missbehaving in another way)
https://github.com/QubesOS/qubes-issues/issues/4720 (This issue might be the more general case of this specific issue)

**Comment by yubiguel** [comment]
Seems to be a duplicate of #4849 perhaps explanation is a bit different but I think the bug is the same. I also explained it in this one that turned out to be a duplicate #4878

**Comment by GammaSQ** [comment]
Seem to be true, at least the fix (`sudo killal qui-devices`) works, but the devices-widget is then stuck with a phantom usb-stick once it's removed again. That's consistent with your error-description.
Closed as duplicate.
