### ISSUE TITLE
"Backup Qubes" tool breaks when user lacks write access to target directory

### ISSUE THREAD

**Issue by unman** [QubesOS/qubes-issues#4885]
### Qubes OS version:

R4.0

### Affected component(s) or functionality:

Qubes Backup

---

### Steps to reproduce the behavior:

Set backup to use directory to which user has no write access,

### Expected or desired behavior:

Backup will report error and remain usable.

### Actual behavior:

Backup reports error, identifying error as "Permission Denied"
Backup window remains: 
Finish button is not functional, 
Cancel button results in Critical error:

`QubesException: Backup operation not running at line 102 of file base.py`

Clicking OK returns to same dysfunctional Backup window

### General notes:

---

### I am aware of the following related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues:

I could find no directly related issues.

**Comment by fepitre** [comment]
I confirm this issue.
