### ISSUE TITLE
Cannot use QWT gui features in Win7

### ISSUE THREAD

**Issue by unman** [QubesOS/qubes-issues#4886]
### Qubes OS version:

R4.0 

### Affected component(s) or functionality:

QWT 4.0.1-3

---

### Steps to reproduce the behavior:

Install QWT 4.0.1-3, following documented procedure and advice in #3585

### Expected or desired behavior:

GUI features will be available in win7 HVM

### Actual behavior:

After setting debug False, and starting win7 HVM, the HVM boots, window display appears, showing windows boot and start up, but as soon as (presumably) user is logged in, the windows display disappears.

### General notes:

This is HVM template, fully updated.
Without installation of QWT the HVM works fine.

With QWT installed, all other features except GUI display seem to work, particularly qrexec and file copy.

---

### I have consulted the following relevant [documentation](https://www.qubes-os.org/doc/):

[https://www.qubes-os.org/doc/windows/](https://www.qubes-os.org/doc/windows/)
[https://www.qubes-os.org/doc/windows-tools/](https://www.qubes-os.org/doc/windows-tools/)

### I am aware of the following related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues:
#3585 - I find no reference in that (somewhat unwieldy) report to a similar issue. Most users (with whatever QWT version) seem to find graphics work fine.

**Comment by SvenSemmler** [comment]
I have the same behavior, which is why I am using Win7 without QWT at
this time. All other observations I have shared previously about QWT are
with debug on and observed during install attempts.

**Comment by francuss** [comment]
I have the same behavior here.

 I can add that when I try
qvm-prefs win7-clone debug true

it works again, but the window is small as if QWT are not installed, even if they are installed.

**Comment by marmarek** [comment]
Make sure to install all windows updates prior to installing QWT.

**Comment by francuss** [comment]
> Make sure to install all windows updates prior to installing QWT.

Yes, did that

**Comment by SvenSemmler** [comment]
On 3/17/19 12:29 PM, francuss wrote:
>     Make sure to install all windows updates prior to installing QWT.
> 
> Yes, did that

Same

**Comment by RachelHendy** [comment]
@francuss / @SvenSemmler  

If I may ask, what does the QGA log say?

**Comment by SvenSemmler** [comment]
On 4/6/19 6:37 AM, RachelHendy wrote:
> If I may ask, what does the QGA log say?

I don't know what that is. Please post instructions / explanation and I
will repeat an install and post the logs here.

**Comment by RachelHendy** [comment]
@SvenSemmler 
Check C:\Program Files\Invisible Things Lab\Qubes Tools\log

There are many logs there, one of them is the QGA log that deals with the qubes's windows GUI daemon

I think there is also a registry setting for log level, but I don't remember it and can't find the doc right now.

**Comment by BCSharp** [comment]
I had a similar issue as described here.

After installing QWT 4.0.1.3 on fully updated Windows 7 SP1 (with both recommended and optional updates), the window with the desktop stopped appearing. This only happened when I installed QWT **excluding** the GUI Agent component. With GUI Agent, the desktop appears OK (but GUI Agent has some other issues that make is unusable: #2678). What worked for me is setting `gui` feature to 1. E.g., if the Windows VM name is `win7`:

~~~
qvm-features win7 gui 1
~~~

What is happening is that after the QWT installation, the qube communicates back to dom0 whether GUI Agent is installed or not. If it is, feature `gui` is set to true (1) and `gui-emulated` to false (''). If it is not, `gui` is false ('') and `gui-emulated` is true (1). Somehow, however, if `gui` is not true, the qube window is not handled properly. Maybe it used to work in the past. I am running the latest, fully updated Qubes OS 4.0.1.

**Comment by brendanhoar** [comment]
FWIW, I use @crazyqube 's script to build and deploy windows 7, here:
https://github.com/crazyqube/qvm-create-windows-qube/

With a few local modifications, it has worked well for me.

B
