### ISSUE TITLE
Qubes Disk Space Monitor stale displayed value

### ISSUE THREAD

**Issue by Eric678** [QubesOS/qubes-issues#4888]
### Qubes OS version:
4.0

### Affected component(s) or functionality:
Qubes Disk Space Monitor widget

---

### Steps to reproduce the behavior:
Run your system for a long time without starting or stopping any VMs.

### Expected or desired behavior:
The disk monitor shows the current disk space used.

### Actual behavior:
The value displayed only updates when VMs are started/stopped (not sure if one or other or both).

### General notes:
`lvs qubes_dom0/pool00` gives the right answer and should be called upon every opening of the widget.

---

**Comment by Eric678** [comment]
Or you could be modern and conform to its name and run lvs every 1-2 seconds and animate the display  :-)

**Comment by marmarek** [comment]
The disk space widget refresh itself every 30sec. But indeed in case of LVM backend cache results and refresh it only at (any) VM start/stop.
I'll add refreshing the cache if it's old too.
