### ISSUE TITLE
perl: warning: Setting locale failed

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#4889]
### Qubes OS version:

4.0

### Affected component(s) or functionality:

Whonix

---

### Steps to reproduce the behavior:

in terminal:

`vrms`

### Expected or desired behavior:

normal output

### Actual behavior:

```
vrms 
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LANGUAGE = "",
        LC_ALL = (unset),
        LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").

No non-free or contrib packages installed on host!  rms would be proud.
```

### General notes:

Doesn't only happen (with obscure example) `vrms` also with many other applications, users reported it happening with youtube-dl.

This randomly started happening. Some update must have introduced it. No Whonix code related to this was changed in years.

A "lazy" fix would be installing package `locales-all`. But disk space could be pushing it?

> `After this operation, 130 MB of additional disk space will be used.`

Anyone having this issue outside of Whonix?

During template build we have: https://github.com/QubesOS/qubes-builder-debian/blob/master/template_debian/distribution.sh#L354-L358

```
function updateLocale() {
    debug "Updating locales"
    chroot_cmd localedef -f UTF-8 -i en_US -c en_US.UTF-8
    chroot_cmd update-locale LANG=en_US.UTF-8
}
```

I wonder why this randomly stops working now?

**Comment by TNTBOMBOM** [comment]
The issue exactly happened after installing "qubes-core-agent-passwordless-root " in debian-qubes-minimal 

cc @marmarek

**Comment by unman** [comment]
On Wed, Jun 19, 2019 at 07:35:30AM -0700, TNT BOM BOM wrote:
> The issue exactly happened after installing "qubes-core-agent-passwordless-root " in debian-qubes-minimal 
> 

No, it's present in the minimal template - nothing to do with installing
that package.

**Comment by TNTBOMBOM** [comment]
> No, it's present in the minimal template - nothing to do with installing that package.

It just showed up after installing it. If you see its not the case , what do you think causing that?

**Comment by XStreamke** [comment]
Getting the same error when installing whonix-15. Locale info is in /etc/locale.conf, but on installing the new whonix he can't set the locale nl_BE.UTF-8. It's a warning and doesn't block the installation.

**Comment by adrelanos** [comment]
I haven't seen this issue anymore for a while. No idea why it went away.

This is also the case in these new Qubes-Whonix templates which are currently being tested (but announcement not written yet) (and which might become the new stable version shouldn't there be any other release blockers):

* https://github.com/QubesOS/updates-status/issues/1661
* https://github.com/QubesOS/updates-status/issues/1662
* https://www.whonix.org/wiki/Qubes/Install/Testing

Therefore closing.

Anyone feel free to re-open this if this is still happening.

**Comment by adrelanos** [comment]
Same issue as before.

```
locale
```
```
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE=C.UTF-8
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

A messed up `locale` can be confusing and break scripts (for example breaks `str_replace` but can be worked around using `LANG=C str_replace`).

It is now re-happening after Qubes-Whonix 15 (Debian `bullseye` based) to Qubes-Whonix 16 (`bullseye` based) [release upgrade](https://www.whonix.org/wiki/Release_Upgrade), [Release Upgrade Whonix 15 to Whonix 16](https://www.whonix.org/wiki/Release_Upgrade_Whonix_15_to_Whonix_16).

The issue does not happen in [Non-Qubes-Whonix](https://www.whonix.org/wiki/Non-Qubes-Whonix). I therefore suspect there must be something wrong with how Qubes build process creates the Debian base image. https://github.com/QubesOS/qubes-issues/issues/1055 would probably solve that.

`sudo locale-gen` does not fix the issue.

```
cat /etc/default/locale
```
```
#  File generated by update-locale
LANG=en_US.UTF-8
```

Output of `cat /etc/locale.gen | grep --invert-match \#` is empty.

**Comment by DemiMarie** [comment]
Installing `locales-all` fixes the problem

**Comment by adrelanos** [comment]
@DemiMarie 
> Installing `locales-all` fixes the problem

I was about to write with concerns about insufficient space on Qubes installer DVD but then saw @marmarek did that already here: https://github.com/QubesOS/qubes-core-agent-linux/pull/322#issuecomment-903579127

**Comment by marmarek** [comment]
@adrelanos does it happen only on release upgrade from Whonix 15, or on a fresh build of Whonix 16 too?

This is how the locale is generated:
https://github.com/QubesOS/qubes-builder-debian/blob/master/template_debian/distribution.sh#L359-L363
I guess it should be also added to `/etc/locale.gen`, right?

An alternative idea is to set `LC_CTYPE=C.UTF-8` instead of `LANG=en_US.UTF-8` - to just enable UTF-8 in applications output, but don't specify explicit language. By reading comments in https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=609306, it seems setting `LANG=C.UTF-8` would be a bad choice.

**Comment by adrelanos** [comment]
(Added a workaround to Whonix. Referenced by github above. But that's just a band aid. A proper fix would be great.)

> @adrelanos does it happen only on release upgrade from Whonix 15, or on a fresh build of Whonix 16 too?

Only on release upgrade from Whonix 15.
Fresh build not yet tested. (Will do in near future.)

> This is how the locale is generated:
> https://github.com/QubesOS/qubes-builder-debian/blob/master/template_debian/distribution.sh#L359-L363
> I guess it should be also added to `/etc/locale.gen`, right?

(From https://github.com/grml/grml-debootstrap/issues/25) grml-debootstrap had the same issue (new builds) (https://github.com/grml/grml-debootstrap/issues/25) and the solution was this (https://github.com/grml/grml-debootstrap/commit/430c060be15f60f508428edbc03ea70d9bf04399). Perhaps have a look.

> This is how the locale is generated:
> https://github.com/QubesOS/qubes-builder-debian/blob/master/template_debian/distribution.sh#L359-L363
> I guess it should be also added to `/etc/locale.gen`, right?

Could be. But doing that after the issue happened and then running `sudo locale-gen`and/or `sudo update-locale` did not fix the issue for me. Maybe it would for new builds but I wouldn't know why.

**Comment by marmarek** [comment]
Hm, `sudo locale-gen` should fix that, if `en_US.UTF-8 UTF-8` line is uncommented in `/etc/locale.gen`. Maybe wrong line?

**Comment by marmarek** [comment]
> (From [grml/grml-debootstrap#25](https://github.com/grml/grml-debootstrap/issues/25)) grml-debootstrap had the same issue (new builds) ([grml/grml-debootstrap#25](https://github.com/grml/grml-debootstrap/issues/25)) and the solution was this ([grml/grml-debootstrap@430c060](https://github.com/grml/grml-debootstrap/commit/430c060be15f60f508428edbc03ea70d9bf04399)). Perhaps have a look.

So, they have `en_US.UTF-8` locale generated by default via `/etc/locale.gen`. Sounds like we should do that too.

**Comment by andrewdavidwong** [comment]
Same problem is still happening with a fresh debian-11-minimal template from the repo on a fresh Qubes 4.1.1 installation.

**Comment by andrewdavidwong** [comment]
Reverted title change based on https://github.com/QubesOS/qubes-core-agent-linux/pull/322#issuecomment-903579127.

**Comment by DemiMarie** [comment]
We need to figure out what locales the user needs, and generate them via `/etc/locale.gen`.

**Comment by TNTBOMBOM** [comment]
> We need to figure out what locales the user needs, and generate them via `/etc/locale.gen`.

Just use the default which is en_US.UTF-8 no need further expansion.

**Comment by rocodes** [comment]
I think this could use an `affects-4.2` tag as well - on 4.2.2-rc2 I see the same warnings in the journal of my debian 12 minimal qubes and via `locale`, with a report just like the one @adrelanos mentioned [above](https://github.com/QubesOS/qubes-issues/issues/4889#issuecomment-903328657)

**Comment by ranvik14** [comment]
I'm still getting this warning with the latest 'debian-12-minimal' template.

@apparatus suggested in Qubes Community Forum [1] that I'll report this here as well.

Here are the logs from my re-test:

* Delete 'debian-12-minimal' template - Done.
* Install 'debian-12-minimal'template again - OK - See "Log-001".
* Clone 'debian-12-minimal' into 'vr-aqt-dl12-00' - Done.
* The problem which I faced with minimal templates in Fedora Linux also exist in Debian ...
* -> See https://groups.google.com/g/qubes-users/c/m7TfBvVNUsw/m/Vr3rS7g7AwAJ
* --> Activate copy & paste for XTerm - OK - See "Log-002".
* Install 'qubes-core-agent-passwordless-root' package - OK - See "Log-003".
* -> See also https://www.qubes-os.org/doc/templates/minimal/#passwordless-root

```
### Log-001

    [vr@dom0 ~]$ 
    [vr@dom0 ~]$ sudo qubes-dom0-update qubes-template-debian-12-minimal
    Redirecting to 'qvm-template install  debian-12-minimal'
    Downloading 'qubes-template-debian-12-minimal-0:4.2.0-202308031621'...

    ...

    Installing template 'debian-12-minimal'...
    debian-12-minimal: Importing data
    [vr@dom0 ~]$ 

### Log-002

    user@vr-aqt-dl12-00:~$ 
    user@vr-aqt-dl12-00:~$ cat .Xresources
    XTerm.vt100.selectToClipboard: 1
    user@vr-aqt-dl12-00:~$ 

### Log-003

    root@vr-aqt-dl12-00:~# 
    root@vr-aqt-dl12-00:~# apt update
    Hit:1 https://deb.debian.org/debian bookworm InRelease
    Hit:2 https://deb.debian.org/debian-security bookworm-security InRelease
    Hit:3 https://deb.qubes-os.org/r4.2/vm bookworm InRelease
    Reading package lists... Done                        
    Building dependency tree... Done
    Reading state information... Done
    All packages are up to date.
    root@vr-aqt-dl12-00:~# 
    root@vr-aqt-dl12-00:~# apt install qubes-core-agent-passwordless-root
    Reading package lists... Done
    Building dependency tree... Done
    Reading state information... Done
    The following packages were automatically installed and are no longer required:
      python3-daemon python3-lockfile
    Use 'apt autoremove' to remove them.
    The following NEW packages will be installed:
      qubes-core-agent-passwordless-root
    0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
    Need to get 20.0 kB of archives.
    After this operation, 45.1 kB of additional disk space will be used.
    Get:1 https://deb.qubes-os.org/r4.2/vm bookworm/main amd64 qubes-core-agent-passwordless-root amd64 4.2.36-1+deb12u1 [20.0 kB]
    Fetched 20.0 kB in 0s (52.5 kB/s)                              
    perl: warning: Setting locale failed.
    perl: warning: Please check that your locale settings:
            LANGUAGE = (unset),
            LC_ALL = (unset),
            LANG = "en_US.UTF-8"
        are supported and installed on your system.
    perl: warning: Falling back to the standard locale ("C").
    locale: Cannot set LC_CTYPE to default locale: No such file or directory
    locale: Cannot set LC_MESSAGES to default locale: No such file or directory
    locale: Cannot set LC_ALL to default locale: No such file or directory
    Selecting previously unselected package qubes-core-agent-passwordless-root.
    (Reading database ... 20852 files and directories currently installed.)
    Preparing to unpack .../qubes-core-agent-passwordless-root_4.2.36-1+deb12u1_amd64.deb ...
    Unpacking qubes-core-agent-passwordless-root (4.2.36-1+deb12u1) ...
    Setting up qubes-core-agent-passwordless-root (4.2.36-1+deb12u1) ...
    locale: Cannot set LC_CTYPE to default locale: No such file or directory
    locale: Cannot set LC_MESSAGES to default locale: No such file or directory
    locale: Cannot set LC_ALL to default locale: No such file or directory
    root@vr-aqt-dl12-00:~# 

```
---
[1] https://forum.qubes-os.org/t/warnings-with-locales-in-debian-12-minimal-based-template/28723

**Comment by apparatius** [comment]
> Downloading 'qubes-template-debian-12-minimal-0:4.2.0-202308031621'...

It seems that the debian-12-minimal template with this change is not available yet.

**Comment by ben-grande** [comment]
Whoever is fixing this, also see https://github.com/QubesOS/qubes-issues/issues/10575

**Comment by ranvik14** [comment]
**This issue still affects 4.3 !**

I verified this statement by re-doing the steps I reported last time. - The only change is that my system is now on r4.3.1 - and - I'm using a template based on 'debian-13-minimal'.

Here's my log:

* Install 'debian-13-minimal' template - See "Log-001".
* Clone 'debian-13-minimal' into 'test-issue-4889' - Done.
* Activate copy & paste for XTerm - See "Log-002" - OK.
* Install 'qubes-core-agent-passwordless-root' package - See "Log-003" - OK ?
* ---> Install succeeds - but - the perl warning still occurs !

### Log-001

    bash: warning: setlocale: LC_COLLATE: cannot change locale (de_DE.UTF-8): No such file or directory
    bash: warning: setlocale: LC_COLLATE: cannot change locale (de_DE.UTF-8): No such file or directory
    bash: warning: setlocale: LC_COLLATE: cannot change locale (de_DE.UTF-8): No such file or directory
    [vr@dom0 ~]$ 
    [vr@dom0 ~]$ sudo qubes-dom0-update qubes-template-debian-13-minimal
    Using sys-firewall as UpdateVM for Dom0
    Downloading packages. This may take a while...
    Redirecting to 'qvm-template install  debian-13-minimal'
    Downloading 'qubes-template-debian-13-minimal-0:4.3.0-202510232142'...
    qubes-template-debian-13-minimal-0:4.3.0-202510232142:  13%|���| 28.3M/220M [00:qubes-template-debian-13-minimal-0:4.3.0-202510232142:  13%|���| 29.4M/220M [00:qubes-template-debian-13-minimal-0:4.3.0-202510232142:  14%|���| 30.4M/220M [00:qubes-template-debian-13-minimal-0:4.3.0-202510232142:  14%|���| 31.5M/220M 
    ...
    [00:3qubes-template-debian-13-minimal-0:4.3.0-202510232142: 100%|���| 219M/220M [00:3qubes-template-debian-13-minimal-0:4.3.0-202510232142: 100%|���| 219M/220M [00:34<
    Installing template 'debian-13-minimal'...
    debian-13-minimal: Importing data
    [vr@dom0 ~]$ 

### Log-002

    user@test-issue-4889:~$ 
    user@test-issue-4889:~$ ls -al
    total 72
    drwx------ 12 user user 4096 Jun 22 10:37 .
    drwxr-xr-x  3 root root 4096 Jun 22 10:23 ..
    -rw-------  1 user user  118 Jun 22 10:37 .bash_history
    -rw-r--r--  1 user user  220 Jul 30  2025 .bash_logout
    -rw-r--r--  1 user user 3526 Jul 30  2025 .bashrc
    drwx------  3 user user 4096 Jun 22 10:23 .config
    drwxr-xr-x  2 user user 4096 Jun 22 10:23 Desktop
    drwxr-xr-x  2 user user 4096 Jun 22 10:23 Documents
    drwxr-xr-x  2 user user 4096 Jun 22 10:23 Downloads
    drwxr-xr-x  3 user user 4096 Jun 22 10:23 .local
    drwxr-xr-x  2 user user 4096 Jun 22 10:23 Music
    drwxr-xr-x  2 user user 4096 Jun 22 10:23 Pictures
    -rw-r--r--  1 user user  807 Jul 30  2025 .profile
    drwxr-xr-x  2 user user 4096 Jun 22 10:23 Public
    drwxr-xr-x  2 user user 4096 Jun 22 10:23 Templates
    drwxr-xr-x  2 user user 4096 Jun 22 10:23 Videos
    -rw-rw-r--  1 user user   33 Jun 22 10:35 .Xresources
    -rw-------  1 user user 2236 Jun 22 10:37 .xsession-errors
    user@test-issue-4889:~$ 
    user@test-issue-4889:~$ cat ~/.Xresources
    XTerm.vt100.selectToClipboard:1

    user@test-issue-4889:~$ 

### Log-003

    [vr@dom0 ~]$ 
    [vr@dom0 ~]$ qvm-run -u root test-issue-4889 xterm
    Running 'xterm' on test-issue-4889

    ###

    root@test-issue-4889:~# 
    root@test-issue-4889:~# apt update
    Hit:1 https://deb.debian.org/debian trixie InRelease
    Hit:2 https://deb.debian.org/debian-security trixie-security InRelease
    Hit:3 https://deb.qubes-os.org/r4.3/vm trixie InRelease
    96 packages can be upgraded. Run 'apt list --upgradable' to see them.
    root@test-issue-4889:~# 
    root@test-issue-4889:~# apt full-upgrade -y
    Upgrading:                      
      base-files               libsystemd0
      bash                     libtiff6
      dhcpcd-base              libudev1
      dirmngr                  libvchan-xen1
      distro-info-data         libxencall1
      dpkg                     libxendevicemodel1
      e2fsprogs                libxenevtchn1
      gir1.2-glib-2.0          libxenforeignmemory1
      gnupg                    libxengnttab1
      gnupg-l10n               libxenhypfs1
      gpg                      libxenmisc4.20
      gpg-agent                libxenstore4
      gpgconf                  libxentoolcore1
      gpgsm                    libxentoollog1
      ifupdown                 libxml2
      keyboard-configuration   linux-sysctl-defaults
      libc-bin                 locales
      libc-l10n                logsave
      libc6                    nano
      libcap2                  openssl
      libcap2-bin              openssl-provider-legacy
      libcom-err2              python3-qrexec
      libext2fs2t64            python3-qubesdb
      libfreetype6             python3.13
      libgcrypt20              python3.13-minimal
      libgdk-pixbuf-2.0-0      qubes-core-agent
      libgdk-pixbuf2.0-common  qubes-core-qrexec
      libglib2.0-0t64          qubes-gui-agent
      libgnutls30t64           qubes-utils
      libgssapi-krb5-2         qubes-vm-dependencies
      libharfbuzz0b            qubesdb
      libjxl0.11               qubesdb-vm
      libk5crypto3             sed
      libkrb5-3                sqv
      libkrb5support0          sudo
      liblcms2-2               systemd
      libpam-systemd           systemd-sysv
      libpng16-16t64           tzdata
      libpython3.13-minimal    udev
      libpython3.13-stdlib     x11-common
      libqrexec-utils4         xen-utils-4.20
      libqubes-pure0           xen-utils-common
      libqubes-rpc-filecopy2   xenstore-utils
      libqubesdb               xserver-common
      libsqlite3-0             xserver-xorg-core
      libss2                   xserver-xorg-input-qubes
      libssl3t64               xserver-xorg-qubes-common
      libsystemd-shared        xserver-xorg-video-dummyqbs

    Installing dependencies:
      xcvt

    Summary:
      Upgrading: 96, Installing: 1, Removing: 0, Not Upgrading: 0
      Download size: 56.7 MB
      Space needed: 393 kB / 18.7 GB available

    Get:1 https://deb.debian.org/debian trixie/main amd64 libc6 amd64 2.41-12+deb13u3 [2,850 kB]

    ...

    Setting up qubes-vm-dependencies (4.3.8-1+deb13u1) ...
    Processing triggers for dbus (1.16.2-2) ...
    Processing triggers for shared-mime-info (2.4-5+b2) ...
    Processing triggers for procps (2:4.0.4-9) ...
    Processing triggers for debianutils (5.23.2) ...
    Processing triggers for libc-bin (2.41-12+deb13u3) ...
    Reading package lists...
    Building dependency tree...
    Reading state information...
    Calculating upgrade...
    0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
    root@test-issue-4889:~# 

    ###

    root@test-issue-4889:~# 
    root@test-issue-4889:~# apt install qubes-core-agent-passwordless-root -y
    Installing:                     
      qubes-core-agent-passwordless-root

    Summary:
      Upgrading: 0, Installing: 1, Removing: 0, Not Upgrading: 0
      Download size: 26.2 kB
      Space needed: 51.2 kB / 18.6 GB available

    Get:1 https://deb.qubes-os.org/r4.3/vm trixie/main amd64 qubes-core-agent-passwordless-root amd64 4.3.45-1+deb13u1 [26.2 kB]
    Fetched 26.2 kB in 0s (69.9 kB/s)                              
    perl: warning: Setting locale failed.
    perl: warning: Please check that your locale settings:
            LANGUAGE = (unset),
            LC_ALL = (unset),
            LC_CTYPE = (unset),
            LC_NUMERIC = (unset),
            LC_COLLATE = (unset),
            LC_TIME = (unset),
            LC_MESSAGES = (unset),
            LC_MONETARY = (unset),
            LC_ADDRESS = (unset),
            LC_IDENTIFICATION = (unset),
            LC_MEASUREMENT = (unset),
            LC_PAPER = (unset),
            LC_TELEPHONE = (unset),
            LC_NAME = (unset),
            LANG = "en_US.UTF-8"
        are supported and installed on your system.
    perl: warning: Falling back to the standard locale ("C").
    locale: Cannot set LC_CTYPE to default locale: No such file or directory
    locale: Cannot set LC_MESSAGES to default locale: No such file or directory
    locale: Cannot set LC_ALL to default locale: No such file or directory
    Selecting previously unselected package qubes-core-agent-passwordless-root.
    (Reading database ... 20042 files and directories currently installed.)
    Preparing to unpack .../qubes-core-agent-passwordless-root_4.3.45-1+deb13u1_amd64.deb ...
    Unpacking qubes-core-agent-passwordless-root (4.3.45-1+deb13u1) ...
    Setting up qubes-core-agent-passwordless-root (4.3.45-1+deb13u1) ...
    locale: Cannot set LC_CTYPE to default locale: No such file or directory
    locale: Cannot set LC_MESSAGES to default locale: No such file or directory
    locale: Cannot set LC_ALL to default locale: No such file or directory
    Reading package lists...
    Building dependency tree...
    Reading state information...
    Calculating upgrade...
    0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
    root@test-issue-4889:~#

**Comment by unman** [comment]
It IS an issue with the debian-13-mnnimal template. I dont know if it
affects fedora-minimal.
But of what significance is that? Minimal templates have MANY issues,
and users are warned of this. If you are not able to resolve this issue
then you probably should not be using a minimal template.

**Comment by andrewdavidwong** [comment]
@ben-grande: What's the rationale for switching the labels back?

**Comment by ben-grande** [comment]
> [@ben-grande](https://github.com/ben-grande): What's the rationale for switching the labels back?

To be closed soon, as per unman's response, issue is not valid cause it is a minimal template. I would have closed as declined, but I didn't read the full issue to do that, so just waiting for someone else to choose the destiny of this issue.

**Comment by andrewdavidwong** [comment]
> To be closed soon, as per unman's response, issue is not valid cause it is a minimal template. I would have closed as declined, but I didn't read the full issue to do that, so just waiting for someone else to choose the destiny of this issue.

Looks like it also affects Whonix, though, which isn't minimal.

**Comment by ranvik14** [comment]
> It IS an issue with the debian-13-mnnimal template. I dont know if it
> affects fedora-minimal.

It is a Debian-only issue. Using a template based on 'fedora-43-minimal' works w/o any warnings.

> But of what significance is that? Minimal templates have MANY issues,
> and users are warned of this. If you are not able to resolve this issue
> then you probably should not be using a minimal template.

I felt obliged to react, since I received an explicit email from 'github-actions' based on my input from 2024 ...
