### ISSUE TITLE
Issue building an ISO with qubes-builder on Fedora 29

### ISSUE THREAD

**Issue by Simon-Davies** [QubesOS/qubes-issues#4895]
Whenever I try to build an ISO with qubes-builder on Fedora 29 the build process seems to get stuck. See screenshot below:

![20190318_130525](https://user-images.githubusercontent.com/713455/54532586-fb760200-497f-11e9-85b2-c539b884b7ee.jpg)

**Comment by marmarek** [comment]
Log listed there may provide more details.

**Comment by Simon-Davies** [comment]
I'll provide you with the log now. Just running the build again to get it as I deleted the qubes-builder directory due to it failing.

**Comment by Simon-Davies** [comment]
Log Attached.

[desktop-linux-kde-baseapps-dom0-fc29.log](https://github.com/QubesOS/qubes-issues/files/2980688/desktop-linux-kde-baseapps-dom0-fc29.log)

**Comment by fepitre** [comment]
This is something known and this is why for the fc29 this is still a WIP: https://github.com/fepitre/qubes-desktop-linux-kde-baseapps/commit/bea2fdb34a68aea390a388d9fece9c1d9d9d4992. Updating KDE with respect to upstream need a little bit of work. They have migrated several things away from 'baseapps' so this is still a WIP.

**Comment by fepitre** [comment]
@andrewdavidwong: it does not seems to be 'Release 4.0 updates' as it is for R4.1.

**Comment by Simon-Davies** [comment]
Are we a long way off the release of 4.1?

I'm trying to build a working ISO to install of my Dell XPS 15 i9. The latest release boots into a black screen in UEFI mode. I don't even get to the installer.

I've tried the solutions from UEFI Troubleshooting with no success.

I've read the problem lies with the older version of Xen and The newer UEFI firmware. Is this correct?

**Comment by marmarek** [comment]
> Are we a long way off the release of 4.1?

Yes, more details here: https://groups.google.com/d/msgid/qubes-devel/20190306022447.GT5348%40mail-itl

Since KDE isn't included in default installation image, you can simply drop it from COMPONENTS in builder.conf. But I'd expect more problems down the road...

> The latest release boots into a black screen in UEFI mode. I don't even get to the installer.

I'd try legacy mode, if that's an option. If not, see https://www.qubes-os.org/doc/uefi-troubleshooting/, and also https://www.qubes-os.org/doc/releases/4.0/release-notes/#known-issues

**Comment by Simon-Davies** [comment]
"With R4.0.1, which ships kernel-4.19, you may never reach the anaconda startup and be block on an idle black screen with blinking cursor. You can try to add plymouth.ignore-serial-consoles in the grub installer boot menu right after quiet rhgb. With legacy mode, you can do it directly when booting the DVD or USB key. In UEFI mode, follow the same procedure described for disabling nouveau module (related solved issue in further version of Qubes)."

This could be the answer I'm looking for. Thanks Marmarek.

**Comment by Simon-Davies** [comment]
None of the troubleshooting docs fix the issue including the above from the second link.

Booting in UEFI mode just gives me a black screen on my DELL XPS 15 i9. I never get to the installer. The laptop does not support legacy mode.

Building also fails without the kde Components :(

**Comment by fepitre** [comment]
Have you tried to disable nouveau (adding at the end of 'kernel=' line: nouveau.modeset=0) and the runtime-services (adding simply at the end of 'options=' line: efi=no-rs is). It should be enough as I also had such problem with a bunch of Asus laptops and I solved all several kind of problems which a combination of these options.

What is your other problem for building an iso? Also, please remind that trying to build R4.1 is not recommended as it is still a WIP.

**Comment by Simon-Davies** [comment]
I have tried adding nouveau.modeset=0 but haven't tried editing the options line. I'll try that now. Thank you.

**Comment by Simon-Davies** [comment]
Adding efi-no-rs got me to the installer :) But now it's throwing an unknown error. See below:

![20190320_141528](https://user-images.githubusercontent.com/713455/54691131-a4586480-4b1a-11e9-9bdc-6e5a5c92359e.jpg)

**Comment by Simon-Davies** [comment]
You are a God send @fepitre 

I added the efi=no-rs and nouveau.modset=0 and finally I have a working Installer :)

Binary editing the ISO multiple times to get it right was a bitch but it's working at last.

![20190320_233025](https://user-images.githubusercontent.com/713455/54725900-a6e1ab00-4b68-11e9-88e3-730bc30cd29d.jpg)

**Comment by fepitre** [comment]
Happy you succeeded to finally get it working. Please note that the trouble you encountered is related to buggy supported uefi provided by hardware constructor and NVIDIA driver provided by nouveau which is also sometime not working well due to specific design of hardware. @marmarek can confirm or not what I'm saying.
