### ISSUE TITLE
Cannot Filter DNS Host Qubes Firewall

### ISSUE THREAD

**Issue by MasqueradedPacket** [QubesOS/qubes-issues#4896]
Steps to Reproduce:
1. Make new Qube on sys-firewall (I'm calling it dns-test)
2. Make `qvm-firewall dns-test list` look like this:
NO ACTION HOST            PROTOCOL  PORT(S)  SPECIAL TARGET  ICMP TYPE  EXPIRE COMMENT
0     accept    qubes-os.org -                     -                dns                          -                    -               -
Commands to do that:
    qvm-firewall dns-test del --rule-no 0
    qvm-firewall dns-test add accept qubes-os.org specialtarget=dns
3. Start Qube and run `dig qubes-os.org`

Expected Result: Returns DNS records associated with qubes-os.org (and would only be able to resolve that domain)
What Happened: Connection timed out, can't resolve any DNS names including qubes-os.org

Note: `qvm-firewall dns-test add accept specialtarget=dns` works but that lets all domain names be resolved; not just qubes-os.org.

**Comment by marmarek** [comment]
It doesn't work this way. `specialtarget=dns` means access to DNS server. Filtering individual queries is not supported.
More info:
https://www.qubes-os.org/doc/vm-interface/#firewall-rules-in-4x
