### ISSUE TITLE
Outdated paragraph in Split GPG limitations section

### ISSUE THREAD

**Issue by strugee** [QubesOS/qubes-issues#4901]
### Qubes OS version:

R4.0

### Affected component(s) or functionality:

qubes-doc

---

### Steps to reproduce the behavior:

N/A

### Expected or desired behavior:

N/A

### Actual behavior:

N/A

### General notes:

On https://www.qubes-os.org/doc/split-gpg/#current-limitations, this text:

> The Split GPG client will fail to sign or encrypt if the private key in the GnuPG backend is protected by a passphrase. It will give an Inappropriate ioctl for device error. Do not set passphrases for the private keys in the GPG backend domain. Doing so won’t provide any extra security anyway, as explained above and below. If you are generating a new key pair, or if you have a private key that already has a passphrase, you can use gpg2 --edit-key <key_id> then passwd to set an empty passphrase. Note that pinentry might show an error when you try to set an empty passphrase, but it will still make the change. (See this StackExchange answer for more information.)

seems to be outdated. Certainly I have successfully been using password-protected keys since day 1 with no issues; my vault qube just pops up a passphrase entry box like normal. I'm not sure if it's just that I have the right software installed or whether this was a limitation only in R3. Happy to make a PR either way, but I'm not sure what the best way to proceed is currently.

---

### I have consulted the following relevant [documentation](https://www.qubes-os.org/doc/):

N/A

### I am aware of the following related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues:

https://github.com/QubesOS/qubes-issues/issues?q=is%3Aissue+is%3Aopen+split+gpg+label%3A%22C%3A+doc%22

**Comment by andrewdavidwong** [comment]
From https://github.com/QubesOS/qubes-doc/pull/837:

> > If this is true, we should probably just remove that whole paragraph. @marmarek?
> 
> Generally yes. It requires graphical pinentry installed (like pinentry-gtk), text based one (the only one in minimal template by default) isn't enough.

Ok. If I understand correctly, this means that the existing text is still accurate, and the new sentence added by this PR is not really accurate. Closing.

If this is incorrect, please leave a comment or reopen.

**Comment by strugee** [comment]
@andrewdavidwong I still think that paragraph in the docs is inaccurate. Based on what Marek said shouldn't it then be adjusted to clarify that it only applies if a graphical pinentry isn't installed?

**Comment by andrewdavidwong** [comment]
> @andrewdavidwong I still think that paragraph in the docs is inaccurate. Based on what Marek said shouldn't it then be adjusted to clarify that it only applies if a graphical pinentry isn't installed?

Mind submitting a PR?

**Comment by vrushti-mody** [comment]
Can I fix the sentence?

**Comment by andrewdavidwong** [comment]
> Can I fix the sentence?

Please do. :)

**Comment by vrushti-mody** [comment]
Note: The error shows only if you **donot** have graphical pinentry installed. The Split GPG client let you use password-protected keys, the vault cube will show a passphrase if you are using R4. 

Does this sentence work?

**Comment by vrushti-mody** [comment]
> > Can I fix the sentence?
> 
> Please do. :)

Note: The error shows only if you **donot** have graphical pinentry installed. The Split GPG client let you use password-protected keys, the vault cube will show a passphrase if you are using R4. 

Does this sentence work?
