### ISSUE TITLE
fail to build Qubes OS R4.0 from scratch (core-libvirt-dom0 does not build)

### ISSUE THREAD

**Issue by yurikanestorm** [QubesOS/qubes-issues#4904]
### Qubes OS version:
R4.0

### Affected component(s) or functionality:
qubes-builder

---

### Steps to reproduce the behavior:

make get-sources
make install-deps
make qubes-vm
make qubes-dom0

### Expected or desired behavior:

The VMs are built.
Dom0 is built.

### Actual behavior:

The VMs are built.
Dom0 fails to build.

### General notes:

core-libvirt fails to build.
It seems to be related to missing dependencies for rpcgen.
You can find the full log below.

[core-libvirt-dom0-fc25.log](https://github.com/QubesOS/qubes-issues/files/2995507/core-libvirt-dom0-fc25.log)

``` 
--> build failed!
**No matching package to install: 'rpcgen'**
Not all dependencies satisfied
Error: Some packages could not be found.
make[2]: *** [/home/y/used/test/20/qubes-builder/qubes-src/builder-rpm/Makefile-legacy.rpmbuilder:59: dist-build-dep.spec] Error 1
make[2]: Leaving directory '/home/y/used/test/20/qubes-builder'
make[1]: *** [Makefile.generic:180: packages] Error 1
make[1]: Leaving directory '/home/y/used/test/20/qubes-builder'
make: *** [Makefile:229: core-libvirt-dom0] Error 1
```

I try to build the iso on 21.03.2019.

Kind Regards

---

**Comment by marmarek** [comment]
`rpcgen` dependency exists only in master branch (development version, future R4.1), but not in release4.0 branch. Make sure you use correct branch, see `example-configs/qubes-os-r4.0.conf`. Or use `setup` script to choose the right one.

**Comment by andrewdavidwong** [comment]
Closing as "not an issue." If you believe this is a mistake, please leave a comment, and we'll be happy to take another look. Thank you.
