### ISSUE TITLE
Ubuntu 16.04 Xenial fails to build (missing repo)

### ISSUE THREAD

**Issue by flamusdiu** [QubesOS/qubes-issues#4907]
### Qubes OS version:

R4.0

### Affected component(s) or functionality:
Make fails to find repository at https://deb.qubes.-os.org/r4.0/vm. 
![image](https://user-images.githubusercontent.com/1879197/54874578-7f871a00-4dc4-11e9-891b-6aa7f213e19d.png)

---

### Steps to reproduce the behavior:

Run `setup` and choose :
- 4.0 Qubes
- QubesOs/qubes Stable - Default Repo
- current Stable Repository
- Build Template Only? Yes
- Template Distribution Selection: xenial+desktop ONLY
- Builder Plugins Selection: builder-debian
- Run `make install-deps`
- Run `make get-sources`
- Run `make qubes -vm`
- Run `make template`

### Expected or desired behavior:
It should build the template.

### Actual behavior:
Fails due to missing repository on server. 

### General notes:

---

### I am aware of the following related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues:

I noticed some people have somehow built Ubuntu 16.04 at some point but others have had issues (different from what I can tell anyway).

**Comment by marmarek** [comment]
There are no repositories on deb.qubes-os.org, because Ubuntu is not officially supported.
@unman maintain unofficial repositories at https://qubes.3isec.org/
But indeed it should be clearly communicated, instead of just showing 404. @unman could you fix it?

**Comment by unman** [comment]
On Sun, Mar 24, 2019 at 04:35:32PM -0700, Marek Marczykowski-Górecki wrote:
> There are no repositories on deb.qubes-os.org, because Ubuntu is not officially supported.
> @unman maintain unofficial repositories at https://qubes.3isec.org/
> But indeed it should be clearly communicated, instead of just showing 404. @unman could you fix it?
> 
Yes

**Comment by flamusdiu** [comment]
Ahh, I see. However, the build system for Ubuntu doesn't work and probably
needs to be updated as well since it always fails with the repo errors.

Thanks for the information.

**Comment by marmarek** [comment]
> There are no repositories on deb.qubes-os.org

To be clear: this means it won't work if you select to use "current"  or "current-testing" online repositories. You need to disable that option.

**Comment by flamusdiu** [comment]
Ahh, gotcha. Somehow didn't realize that was causing the issue.

**Comment by unman** [comment]
@flamusdiu @andrewdavidwong  After merge of https://github.com/QubesOS/qubes-doc/pull/831, this can be closed

**Comment by marmarek** [comment]
Since users still stumble on this from time to time, I think documentation mention is not enough. template builder scripts (in builder-debian) should check for QUBES_REPO variables and either refuse to continue with explicit message how to fix, of ignore it for ubuntu template builds.

**Comment by unman** [comment]
On Fri, Aug 02, 2019 at 05:20:35AM -0700, Marek Marczykowski-G??recki wrote:
> Since users still stumble on this from time to time, I think documentation mention is not enough. template builder scripts (in builder-debian) should check for QUBES_REPO variables and either refuse to continue with explicit message how to fix, of ignore it for ubuntu template builds.
> 

That's a good idea.
I think we should ignore but throw warning, in case the user attempts
to build a mix of templates where repos are available for some and not
for others.
