### ISSUE TITLE
Domain whonix has failed to start

### ISSUE THREAD

**Issue by n0sign4l** [QubesOS/qubes-issues#4908]
### Affected component(s) or functionality:
I'm trying to open the Konsole in Whonix-gw-14 and in whonix-ws-14 when i click on the Konsole to make it open it takes some time and then I get `Domain whonix-gw-14 has failed to start: Cannot connect grexec agent fot 60 seconds, see /var/log/xen/console/guest-whonix-gw-14.log for details` same for whonix-ws-14

---

### Steps to reproduce the behavior:
Click on Konsole of whonix-gw-14

### Expected or desired behavior:
I should have the konsole

### Actual behavior:
I do not have the konsole

**Comment by marmarek** [comment]
> Cannot connect grexec agent fot 60 seconds, see /var/log/xen/console/guest-whonix-gw-14.log for details

Please provided details as pointed in the error message.

**Comment by n0sign4l** [comment]
Can you provide me an email address with PGP encryption or a Signal number where I can submit the logs?

Leonardo

**Comment by marmarek** [comment]
See https://www.qubes-os.org/team/

**Comment by adrelanos** [comment]
Did @n0sign4l e-mail you @marmarek? If not, I suggest to close this ticket "user disappeared" and wait for the user to re-open if required.

**Comment by andrewdavidwong** [comment]
Closing this for now due to the lack of response. If you revisit the matter in the future, or if anyone would like the issue to remain open, please leave a comment, and we'll be happy to reopen this. Thank you.
