### ISSUE TITLE
R4.1: qrexec protocol changes

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#4909]
Over the time, few qrexec protocol changes have accumulated. Lets implement them in R4.1, since qrexec will get some other related changes too (#4370)
Planned qrexec protocol changes for R4.1:
- [ ] Improve handshake to allow backward compatibility, instead of only detecting incompatibility. Lets each side of connection advertise own max supported protocol version, then use min of those two numbers as the actual version in use. If either side does not support this version, drop the connection. This change should be also backported to R4.0 (and maybe even R3.2), to allow smooth upgrade.
- [ ] Increase [data chunk size](https://github.com/QubesOS/qubes-linux-utils/blob/master/qrexec-lib/qrexec.h#L28). Even though ring buffer size may be much larger, data chunk is still at 4k, which affect performance.
 - [ ] Increase allowed length of requested qrexec service name - [MSG_TRIGGER_SERVICE message](https://github.com/QubesOS/qubes-linux-utils/blob/master/qrexec-lib/qrexec.h#L92). Preferably, at do not limit it at protocol level, use field length instead (similar as in `MSG_EXEC_CMDLINE`). For compatibility reasons, this should be a new message (available only in a new protocol version).

**Comment by brendanhoar** [comment]
@marmarek 
>  Increase [data chunk size](https://github.com/QubesOS/qubes-linux-utils/blob/master/qrexec-lib/qrexec.h#L28). Even though ring buffer size may be much larger, data chunk is still at 4k, which affect performance.

FYI, the above in the OP is a broken link.

Thanks,
Brendan

**Comment by marmarek** [comment]
Thanks, updated the links to point at the old (R4.0) version.

**Comment by brendanhoar** [comment]
copy_file still using 4KB buffer? 

 https://github.com/QubesOS/qubes-linux-utils/blob/master/qrexec-lib/copy-file.c
>char buf[4096];
