### ISSUE TITLE
Why won’t my Qubes OS recognize WiFi?

### ISSUE THREAD

**Issue by alrafaykhan** [QubesOS/qubes-issues#4910]
### Qubes OS version:

R4.0.1

### Affected component(s) or functionality:
Want to connect with internet but unable to see wifi icon on desktop.

---

### General notes:

---

**Comment by andrewdavidwong** [comment]
Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this does not appear to be suitable for `qubes-issues`. We ask that you please send this to the `qubes-users` [mailing list](https://www.qubes-os.org/support/) instead. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a brief comment explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.
