### ISSUE TITLE
Restore Qubes Tor onion services

### ISSUE THREAD

**Issue by leonardoporp** [QubesOS/qubes-issues#4911]
Guys you do have to explain better what does it mean with "We recommend that users who currently rely on any Qubes onion addresses transition to the corresponding clearnet addresses immediately." I do have updates over Tor for Qubes and for all the templates VM. Do I have to change all of them to clearnet? I mean what is the thing that we have to change to clearnet immediately? What does it imply? Can you explain better what changes you have done and what they imply. Will I be able to use syswhonix as netvm ?

**Comment by 0spinboson** [comment]
> Will I be able to use syswhonix as netvm ?

Of course; the only change is concerns where you download updates from -- there will no longer be an onioned mirror.

**Comment by leonardoporp** [comment]
I think that it should be explained better in their website as it could create some doubts

**Comment by andrewdavidwong** [comment]
Actually, @unman has volunteered to support onion services for the Qubes repos and website, so they'll be coming back. I'll use this issue for that.

**Comment by conorsch** [comment]
Thanks for the update, @andrewdavidwong, glad to hear it! For those following along at home, the original announcement (recently updated) can be found here: https://www.qubes-os.org/news/2019/03/24/tor-onion-services-no-longer-maintained/

**Comment by mig5** [comment]
@unman @andrewdavidwong if you are wanting to re-use the onion keys (e.g to avoid having to update apt sources) please get in touch. 

(But probably new keys is a better idea)

**Comment by marmarek** [comment]
[Update in core-agent-linux](https://github.com/QubesOS/qubes-core-agent-linux/pull/154) is merged. That should cover it for new Debian and Fedora templates. But for existing ones, if user have enabled onion usage, the file won't be automatically updated (new one will be saved as `.rpmnew`, or `.dpkg-new`). And since the old mirrors are unreachable, `apt update` fails.
In addition to core-agent-linux patch, we can add onion repo update to [update salt formula](https://github.com/QubesOS/qubes-mgmt-salt-dom0-update/blob/master/update/qubes-vm.sls). We used that for apt security fix and to remove jessie-backports already. What do you think @unman?

The similar problem applies to Whonix, when unreachable onion repos are referenced, `apt update` fails (or at least emit a warning, but salt IMO correctly treat it as a failure). We could use salt to replace or disable it there too. What do you think @adrelanos ?

**Comment by unman** [comment]
@marmarek I agree the salt route is the way to go, but should also be a post/update with simple editing instructions for those who do things manually.
I think @andrewdavidwong is working on this - maybe dependent on @adrelanos updating the Whonix instruction page?

**Comment by adrelanos** [comment]
> What do you think @adrelanos ?

Sounds great. Good service for the user.

> maybe dependent on @adrelanos updating the Whonix instruction page?

Dunno what's left to edit on Whonix page if anything. Just now done.

* https://www.whonix.org/w/index.php?title=Onionizing_Repositories&type=revision&diff=42401&oldid=41928

https://www.whonix.org/wiki/Template:Qubes_onion should be up to date by now.

Whonix wiki https://www.whonix.org/wiki/Onionizing_Repositories can be edited by anyone even without account. Edits are held for moderation (but that's mostly a spam prevention mechanism, we rarely have disputes on contents). Feel free to edit that page if need be.

**Comment by marmarek** [comment]
Ok, I'll add updating Qubes onion address into salt formula.

@adrelanos is there any new Whonix onion address?

**Comment by adrelanos** [comment]
Same was before.

**Comment by andrewdavidwong** [comment]
PR opened: https://github.com/QubesOS/qubes-posts/pull/58

**Comment by unman** [comment]
@andrewdavidwong  You're linking to a Whonix page that *still* says Onion service is unmaintained and contains **no** instructions on how to set the Onion address - better not do that.
Better to write our own instructions instead.

**Comment by andrewdavidwong** [comment]
> @andrewdavidwong You're linking to a Whonix page that _still_ says Onion service is unmaintained and contains **no** instructions on how to set the Onion address - better not do that.
> Better to write our own instructions instead.

All we have to do is undo these two revisions:

```
(cur | prev) 03:22, 26 March 2019‎ 0brand2 (talk | contribs)‎ . . (12,309 bytes) (+92)‎ . . (Format.) (undo) [checked by Patrick]
(cur | prev) 03:18, 26 March 2019‎ 0brand2 (talk | contribs)‎ . . (12,217 bytes) (+39)‎ . . (Configure Qubes http:// URI repos.) (undo)
```

I submitted an undo of the first one, but I can't easily undo the second one until the first one is approved, since undoing the second conflicts with the first.

CC: @adrelanos

**Comment by adrelanos** [comment]
Approved.

(No need to use the undo function. Just any text replacement is ok.)

**Comment by andrewdavidwong** [comment]
> (No need to use the undo function. Just any text replacement is ok.)

True, it's not required, but the undo function is less error-prone and exactly intended for this. :)

**Comment by andrewdavidwong** [comment]
Thanks to @unman, the Qubes Tor onion services have been restored:

https://www.qubes-os.org/news/2019/04/17/tor-onion-services-available-again/
