### ISSUE TITLE
Qubes Manager: Add column for disposable VM

### ISSUE THREAD

**Issue by t4777sd** [QubesOS/qubes-issues#4912]
### Qubes OS version: 

4.0

### Affected component(s) or functionality:
Qubes Manager

### Expected or desired behavior:

Qubes Manager should have a disposable VM column like it has a netVm / templateVM column. This is especially important given the security aspects of disposable VMs as revealed in https://www.qubes-os.org/news/2019/02/19/qsb-47/

### Actual behavior:
There is no easy way to see the disposable VM of a qube other than looking in the configuration, clicking advanced tab. This means that it is more likely someone can make a mistake and never catch it and put their security at risk.

### I am aware of the following related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues:

I looked and could not find a duplicate issue only a request for IP column and virt mode.

**Comment by andrewdavidwong** [comment]
Did you mean "DVM Template" instead of "disposable VM"? In other words, do you want a column that shows, e.g., that `disp2875` is based on `work`?

**Comment by t4777sd** [comment]
In the VM config under Advanced there is an option that says "default DispVM". Basically, I want there to be a column for that similar to how there is for the NetVM and TemplateVM settings.

That way it is quick to look in the grid what the default assigned DispVM is for a given qube and make changes if necessary.
