### ISSUE TITLE
Can not boot from DVD

### ISSUE THREAD

**Issue by straussmaus** [QubesOS/qubes-issues#4914]
### Qubes OS version:
 R.4.0

### Affected component(s) or functionality:

New Standalone VM

---

### Steps to reproduce the behavior:

1. Create a new standalong VM in Qubes Manager

2. Insert bootable/install DVD into DVD drive.

3. Choose "Advanced" "Boot qube from CDROM" and then choose DVD (sr0)

4. See this error messge when Qube boots:

```
SeaBIOS...
Machine UUID ...
Booting from Hard Disk...
Boot failed: not abootable disk

Booting from Floppy...
Boot failed: could not read the boot disk

No bootable device.
```

### Expected or desired behavior:

I expect to see the display try to boot from the DVD.  Also to succeed but at least to try.

### Actual behavior:

Qube window stops producing output at this point.

### General notes:

DVD is definitely bootable.

---

### I have consulted the following relevant [documentation](https://www.qubes-os.org/doc/):

From the web page search, a list of pages with "DVD" and "boot":

https://duckduckgo.com/?sites=https%3A%2F%2Fwww.qubes-os.org&q=boot+dvd&ia=web

**Comment by strak8** [comment]
Hi, with the penultimate test update it is impossible to start from the Qube Manager settings the Boot Qube from Cd - ROM from another VM. After selecting the iso image of another vm, the field remains empty, but accepts the possibility of writing the loop device and I think it works if you first create a loop device accessible from Dom0.
goodbye

**Comment by straussmaus** [comment]
@strak8 

>  with the penultimate test update

What does this mean?

>  it is impossible to start from the Qube Manager settings the Boot Qube from Cd - ROM from another VM

Is this one sentence or two?  Are you saying it is impossible to start a Qube from a CD?  Why does the UI show this option?  The sentence is not clear.

>  After selecting the iso image of another vm, the field remains empty

What field?  Why are you talking about iso images?  My bug report is not about iso images.

> I think it works if you first create a loop device accessible from Dom0.

What works?  What do you mean by "a loop device accessible from Dom0?"

**Comment by strak8** [comment]
sorry for my preschool English. I will try to be clearer.
After a recent update of qubes os (with current-testing option) it is no longer possible to start a vm with cdrom boot from the graphical interface. Selecting the ISO image file, the field remains empty (before the selected path appeared). Apart from the empty field, the virtual machine does not start, with an error:
"domain has failed to start: deby block device:
not available "
The field where the path to the file was supposed to be is always empty.
This is a bug. But you can still start from the command line:
qvm-start VM --cdrom: deby: /home/user/download/file.iso
thank you
bye

![vuoto](https://user-images.githubusercontent.com/42741237/55151348-595bd400-514e-11e9-8c5e-c75e70d1215c.png)
![nodevice](https://user-images.githubusercontent.com/42741237/55151346-58c33d80-514e-11e9-9b49-92a483a11ea5.png)

**Comment by strak8** [comment]
I believe that the problem that you report also concerns the one I have. Regardless of whether the cdrom device is real or virtual.

**Comment by straussmaus** [comment]
@strak8 I would like to test this but I still do not know what you are saying.

**Comment by strak8** [comment]
> @strak8 I would like to test this but I still do not know what you are saying.

sorry my hideous english.
the bug has been fixed with the next update.
just to clarify what the problem was:
to boot VM from cd-rom using the Qube Manager graphical interface> Advanced setting> boot qube from cdrom| there was a problem that did not select the chosen image. Since this bug is very similar to what I had, I think it was generated by the same problem.
Thanks anyway for trying to understand me, but to be even more explicit, the problem for me no longer exists.

**Comment by straussmaus** [comment]
@strak8  Thank you.  I do not mean to criticize your English.  Thank you for this.  I will leave this issue open until I test.

Do you know what "update" this will come in?  Something I can test now?

**Comment by straussmaus** [comment]
@strak8 I would like to test this.  Can you provide testing steps so I can test?  I run 4.0.3.

**Comment by straussmaus** [comment]
Okay here are the steps.  It's different from when I opened this issue so I was confused:

- Create new qube

- Type: Empty standalone qube (install your own OS)

- check: install system from device

- In the next dialog, choose your CDROM (ex: /dev/sr0)

- Confirmed working in 4.0.3.

Closing Issue

**Comment by straussmaus** [comment]
@strak8

Works, but it is very very slow to read the CDROM.  Just for your information.
