### ISSUE TITLE
Windows VM Does Not Access Internet

### ISSUE THREAD

**Issue by straussmaus** [QubesOS/qubes-issues#4916]
### Qubes OS version:

R4.0

### Affected component(s) or functionality:

Windows VM created with https://www.qubes-os.org/doc/windows-vm/

---

### Steps to reproduce the behavior:

Follow the very good instructions: https://www.qubes-os.org/doc/windows-vm/

Reboot Windows

See that internet does not work.  Windows says to turn the router on and off.  The router is sys-whonix.  sys-whonix is working for every VM on the system.

### Expected or desired behavior:

I expect Windows VM to use Networking VM like a router, like every VM on Qubes.

### Actual behavior:

Windows does not have internet access.

### General notes:

When I try to `Set Up a Network` I do not have any options in the blank box that should show network devices.

I tried with sys-firewall also.

When I am in `Network and Sharing Center` and I go to `Connect to a network` a little box says 

```
Not connected

No connections are available
Troubleshoot
```

Troubleshooting doesn't help.  It says `The default gateway is not available`

I think DHCP is not working?

---

### I have consulted the following relevant [documentation](https://www.qubes-os.org/doc/):

https://www.qubes-os.org/doc/windows-vm/

**Comment by marmarek** [comment]
It may be specific to Whonix. Does it work if you connect Windows VM to something else like sys-firewall?

**Comment by straussmaus** [comment]
@marmarek 

> It may be specific to Whonix. Does it work if you connect Windows VM to something else like sys-firewall?

No.  In `General Notes` I said I tried with sys-firewall.  Same situation.

**Comment by straussmaus** [comment]
@all closing this issue as it works now.  I don't know why but I am sure it was Windoze fault.
