### ISSUE TITLE
Debian9 template: outdated repositories (/etc/apt/sources.list). [easy fix?]

### ISSUE THREAD

**Issue by deft01** [QubesOS/qubes-issues#4917]
### Qubes OS version:
Qubes 4.0 (R4.0)

### Affected component(s) or functionality:
Debian9 template source list and packages functionalities.

### Steps to reproduce the behavior:
Generate an AppVM with the raw Debian9 Template and test an `apt update`.

### Expected or desired behavior:
Apt packages updating normally.

### Actual behavior:

Output will be something like that :
```user@localhost:~$ sudo apt update
Get:1 http://deb.qubes-os.org/r4.0/vm stretch InRelease [2,502 B]
Get:2 http://deb.qubes-os.org/r4.0/vm stretch/main amd64 Packages [19.7 kB]
Ign:3 https://cdn-aws.deb.debian.org/debian stretch InRelease
Get:4 https://cdn-aws.deb.debian.org/debian-security stretch/updates InRelease [94.3 kB]
Ign:5 https://cdn-aws.deb.debian.org/debian jessie-backports InRelease
Get:6 https://cdn-aws.deb.debian.org/debian-security stretch/updates/main amd64 Packages [481 kB]
Get:7 https://cdn-aws.deb.debian.org/debian-security stretch/updates/main Translation-en [213 kB]
Get:8 https://cdn-aws.deb.debian.org/debian-security stretch/updates/contrib amd64 Packages [1,760 B]
Get:9 https://cdn-aws.deb.debian.org/debian stretch Release [118 kB]
Get:10 https://cdn-aws.deb.debian.org/debian stretch Release.gpg [2,434 B]
Err:11 https://cdn-aws.deb.debian.org/debian jessie-backports Release
  404  Not Found
Get:12 https://cdn-aws.deb.debian.org/debian stretch/main amd64 Packages [7,084 kB]
Get:13 https://cdn-aws.deb.debian.org/debian stretch/main Translation-en [5,384 kB]
Get:14 https://cdn-aws.deb.debian.org/debian stretch/contrib amd64 Packages [50.9 kB]
Get:15 https://cdn-aws.deb.debian.org/debian stretch/non-free amd64 Packages [78.3 kB]
Get:16 https://cdn-aws.deb.debian.org/debian stretch/non-free Translation-en [80.3 kB]
Reading package lists... Done                                
E: The repository 'https://deb.debian.org/debian jessie-backports Release' does no longer have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```
This return code 100. We can see the outdated sources.

### General notes:
**EASY FIX?**
This can be easily fixed by removing the Jessie backports into /etc/apt/.
Deleting the line `deb https://deb.debian.org/debian jessie-backports main
` into _/etc/apt/sources.list_ makes the job as I tested.
And maybe upgrading to stretch backports?

### I have consulted the following relevant [documentation](https://www.qubes-os.org/doc/):
...

### I am aware of the following related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues:
...

**Comment by marmarek** [comment]
It's fixed already here: https://github.com/QubesOS/qubes-builder-debian/commit/07c4621d992da8de2780e07098e9dcab6680e673
And is part of updated template: https://github.com/QubesOS/updates-status/issues/870

But the fix isn't automatically applied to old templates, since
sources.list isn't part of any package. One solution would be to add it
to salt formula applying updates - we already do it for DSA-4371.
https://github.com/QubesOS/qubes-mgmt-salt-dom0-update/tree/master/update

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by marmarek** [comment]
BTW automated test detected it recently too: https://openqa.qubes-os.org/tests/1489#step/VmUpdates_debian-9/1
Looks like jessie-backports got removed from CDN recently, as the test succeeded 11 days ago.

**Comment by h01ger** [comment]
On Tue, Mar 26, 2019 at 10:36:00AM -0700, redcore wrote:
> ### Qubes OS version:
> Qubes 4.0 (R4.0)
> 
> ### Affected component(s) or functionality:
> Debian9 template source list and packages functionalities.
[...]
> E: The repository 'https://deb.debian.org/debian jessie-backports Release' does no longer have a Release file.

this doesn't match: stretch is Debian 9, while jessie is Debian 8.
(and jessie-backports is indeed EOL and gone, but shouldn't be used in
Debian 9 templates anyway.)


-- 
tschau,
	Holger

-------------------------------------------------------------------------------
               holger@(debian|reproducible-builds|layer-acht).org
       PGP fingerprint: B8BF 5413 7B09 D35C F026 FE9D 091A B856 069A AA1C

**Comment by marmarek** [comment]
> this doesn't match: stretch is Debian 9, while jessie is Debian 8.

Yes, this is exactly what this bug is about.

**Comment by xaki23** [comment]
(this is not really about this particular issue, which marmarek and h01ger are dealing with in a much more proper way, but i would like to leave a hint where the next poor sod who is googling this error for other reasons might find it) 

when debian repos are "EOL and gone", they seem to be actualy moved to an archive server, so if you are really truly positively sure you need a pkg for lenny in 2019, replace deb.debian.org by archive.debian.org in the repo spec.

**Comment by rafaelsoaresbr** [comment]
Isn't sources.list missing the following repositories?

```
deb https://deb.debian.org/debian strech-updates main contrib non-free
#deb-src https://deb.debian.org/debian strech-updates main contrib non-free
```

**Comment by marmarek** [comment]
As I understand https://wiki.debian.org/StableUpdates, it is optional, to get some updates faster than next point release.
@unman do you think we should include it by default?

**Comment by unman** [comment]
On Sat, May 04, 2019 at 02:16:53PM -0700, Marek Marczykowski-Górecki wrote:
> As I understand https://wiki.debian.org/StableUpdates, it is optional, to get some updates faster than next point release.
> @unman do you think we should include it by default?
> 

It is optional, but is installed by default in a standard stable
install.
We should include it in forthcoming buster for sure: maybe in any
updated stretch template too.

**Comment by h01ger** [comment]
On Sun, May 05, 2019 at 06:04:44AM -0700, unman wrote:
> It is optional, but is installed by default in a standard stable
> install.
> We should include it in forthcoming buster for sure: maybe in any
> updated stretch template too.

yes.

**Comment by Streetnology** [comment]
I got my computer back from France on Saturday after one year and a half, upgraded my system from R3.2 to 4 yesterday, impossible to update Debian9... 
I tried the sources.list proposed here: [https://wiki.debian.org/fr/SourcesList](url), it doesn't work. On top of it, doing so I carelessly messed up the original one. Means I can't even try to delete the line 'jessie-backports' as I saw on top of this page.
Could anyone copy/paste the original sources.list please? or even better, one who works!lol

Ps: sorry if I made english mistake, I'm not a native english speaker.

**Comment by andrewdavidwong** [comment]
> I got my computer back from France on Saturday after one year and a half, upgraded my system from R3.2 to 4 yesterday, impossible to update Debian9...
> I tried the sources.list proposed here: [https://wiki.debian.org/fr/SourcesList](url), it doesn't work. On top of it, doing so I carelessly messed up the original one. Means I can't even try to delete the line 'jessie-backports' as I saw on top of this page.
> Could anyone copy/paste the original sources.list please? or even better, one who works!lol
> 
> Ps: sorry if I made english mistakes, I'm not a native english speaker.

Please consider asking this on the `qubes-users` [mailing list](https://www.qubes-os.org/support/) instead. `qubes-issues` is not intended to be a support forum.
