### ISSUE TITLE
Linux templates no longer work in HVM mode

### ISSUE THREAD

**Issue by tasket** [QubesOS/qubes-issues#4920]
### Qubes OS version:
4.0

### Affected component(s) or functionality:
debian-9
fedora-28
fedora-29

---

### Steps to reproduce the behavior:
```
qvm-prefs debian-9 virt_mode hvm
qvm-prefs debian-9 kernel ''
qvm-run debian-9 qubes-run-terminal
```

### Expected or desired behavior:
App (term window) appears and is usable after vm starts in hvm mode.

### Actual behavior:
* Window may or may not appear; if it does, its distorted or blank or filled with noise.

* Vm does not respond to further qrexec calls.

Two other people have reported this so far in qubes-users.

### General notes:

---

### I am aware of the following related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues:

https://github.com/QubesOS/qubes-issues/issues/3591#issuecomment-476212317

https://groups.google.com/d/msgid/qubes-users/90695bc3-2297-44af-90cc-4f04a4d7e315%40googlegroups.com

**Comment by marmarek** [comment]
This looks like a missing u2mfn module. See [here](https://www.qubes-os.org/doc/managing-vm-kernel/#using-kernel-installed-in-the-vm-r40) how to reinstall it (dkms commands).

**Comment by auspicacious** [comment]
Thanks for the `u2mfn` tip, @marmarek, it's fixed part of the problem. I was able to boot a debian-9-based template using kernel 4.19.0-0.bpo.2-amd64 from stretch-backports, however, any time that I copy something to the clipboard from the terminal, the VM locks up.
