### ISSUE TITLE
fails to build Qubes OS R4.0 using example config file r4.0 (vmm-xen does not build, repo for debian stretch release not accessible)

### ISSUE THREAD

**Issue by yurikanestorm** [QubesOS/qubes-issues#4926]
### Qubes OS version:
R4.0

### Affected component(s) or functionality:

qubes-builder

---

### Steps to reproduce the behavior:

I am building on Fedora 26.

make get-sources
make install-deps
make qubes-vm
make qubes-dom0
make template

### Expected or desired behavior:

The VMs are built.
Dom0 is built.
Templates are built.

### Actual behavior:

vmm-xen does not build.

### General notes:

Hi, 

It seems to be related to a repository not accessible>

` # Make sure repo directory exists
-> Preparing stretch build environment
-> Installing debian build chroot...
I: Retrieving InRelease 
I: Retrieving Release 
E: Failed getting release file https://deb.debian.org/debian/dists/stretch/Release
Error in debootstrap
make[1]: *** [/home/y/.local/share/Trash/files/20.7/qubes-builder/qubes-src/builder-debian//Makefile-legacy.debian:20: /home/y/.local/share/Trash/files/20.7/qubes-builder/chroot-vm-stretch/home/user/.prepared_base] Error 1
make: *** [Makefile:219: vmm-xen-vm] Error 1`

You can see the full log under.

[build.log](https://github.com/QubesOS/qubes-issues/files/3019487/build.log)

and the builder.conf
[builder.conf.log](https://github.com/QubesOS/qubes-issues/files/3019492/builder.conf.log)

Kind Regards

---

**Comment by unman** [comment]
@yurikanestorm This looks like a network error on your side - there's nothing wrong with the build.
Check network connectivity in your build machine, and in the proxy you are using, if any.

**Comment by andrewdavidwong** [comment]
Closing as "not an issue." If you believe this is a mistake, please leave a comment, and we'll be happy to take another look. Thank you.
