### ISSUE TITLE
whonix update-torbrowser fails to run

### ISSUE THREAD

**Issue by mossy-nw** [QubesOS/qubes-issues#4930]
**Qubes OS version**
R4.0.1

**Affected component(s) or functionality**
whonix-ws-14 template

**Brief summary**
running `update-torbrowser` in the `whonix-ws-14` template fails with the following error:
~~~
INFO: not running inside Qubes DVM Template, ok.                                                                                     
INFO: Running connectivity check...                                                                                                  
INFO: CURL_OUT_FILE: /var/cache/tb-binary/.cache/tb/temp/tbb_remote_folder                                                           
INFO: Connectivity check succeeded.
INFO: Find out latest version... Downloading: https://www.torproject.org/projects/torbrowser/RecommendedTBBVersions...               
INFO: CURL_OUT_FILE: /var/cache/tb-binary/.cache/tb/RecommendedTBBVersions                                                           
INFO: Done, downloaded https://www.torproject.org/projects/torbrowser/RecommendedTBBVersions.

Could not find out latest Tor Browser version! Excessive version string length. (322 characters)                                     
Either check.torproject.org has been compromised or this is a Whonix bug.                                                            
~~~    

**To Reproduce**
1. open a `whonix-ws-14` terminal
2. run `update-torbrowser`

**Expected behavior**
tor browser updates in the template, to allow for the latest tor browser version (currently 8.0.8) in new whonix-ws-14 appVMs and disposable VMs based on the whonix-ws-14 template.

**Actual behavior**
fails with the error above

**Additional context**
Visiting the link `https://www.torproject.org/projects/torbrowser/RecommendedTBBVersions` seems to show the correct versions:
~~~
[
"8.0.8",
"8.0.8-MacOS",
"8.0.8-Linux",
"8.0.8-Windows",
"8.5a9",
"8.5a9-MacOS",
"8.5a9-Linux",
"8.5a9-Windows",
"8.5a10",
"8.5a10-MacOS",
"8.5a10-Linux",
"8.5a10-Windows"
]
~~~
so perhaps the `update-torbrowser` script is simply failing to parse the format (maybe the format has changed?)

**Comment by TNTBOMBOM** [comment]
Its actually not Whonix issue , its torproject issue. and all mentioned here:

https://forums.whonix.org/t/tor-browser-downloader-by-whonix-error-could-not-find-out-latest-tor-browser-version-excessive-version-string-length-323-characters/7063

**Comment by andrewdavidwong** [comment]
> Its actually not Whonix issue , its torproject issue. and all mentioned here:
> 
> https://forums.whonix.org/t/tor-browser-downloader-by-whonix-error-could-not-find-out-latest-tor-browser-version-excessive-version-string-length-323-characters/7063

Closing as "not our bug." If you believe this is a mistake, please leave a comment, and we'll be happy to take another look. Thank you.
