### ISSUE TITLE
Are donations still managed?

### ISSUE THREAD

**Issue by maximilize** [QubesOS/qubes-issues#4931]
I really like the qubes project and thought about donating some money to support this great work.

However, I checked the bitcoin address and found that the last payout was on 2017-07-15. The current balance is nearly 8 BTC, which is quite much money (about 25k EUR).
Here the infos on blockchain.info:
https://www.blockchain.com/btc/address/3GakuQQDUGyyUnV1p5Jc3zd6CpQDkDwmDq (BTC)
https://www.blockchain.com/bch/address/3GakuQQDUGyyUnV1p5Jc3zd6CpQDkDwmDq (BCH)

Is this address still in use? Who is maintaining it and when is the money paid out? And who will receive it?

**Comment by andrewdavidwong** [comment]
Hi @maximilize,

We appreciate your question, but I'm afraid that, based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), it does not appear to be suitable for `qubes-issues`. We ask that you please send it to the `qubes-project` [mailing list](https://www.qubes-os.org/support/) instead, and we will be happy to address it there. Thank you for your understanding.
