### ISSUE TITLE
Installer - after the target dirve for installation, it does not retrieve the USB installation Drive

### ISSUE THREAD

**Issue by athanaselos** [QubesOS/qubes-issues#4932]
### Qubes OS version:

Qubes Release 4.0.1

Installation problem, Anaconda does not retrieve the USB installation drive and after long time display an exception with the message "does not find /dev/sdgN" (usb installation drive)...

Processor : AMD FX 6350 six cores 4Ghz
Host bridge: Advanced Micro Devices, Inc. [AMD/ATI] RD9x0/RX980 Host Bridge (rev 02)
IOMMU: Advanced Micro Devices, Inc. [AMD/ATI] RD890S/RD990 I/O Memory Management Unit (IOMMU)

### Affected component(s) or functionality:

---

### General notes:

---

**Comment by andrewdavidwong** [comment]
Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this does not appear to be suitable for `qubes-issues`. We ask that you please send this to the `qubes-users` [mailing list](https://www.qubes-os.org/support/) instead. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a brief comment explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.
