### ISSUE TITLE
Xorg crash on Qubes 4.0 with kernel 4.19

### ISSUE THREAD

**Issue by AndreasKieling** [QubesOS/qubes-issues#4934]
### Qubes OS version:

R4.0

### Affected component(s) or functionality:

Xorg
Lightdm
Graphical Login
Radeon Driver

---

### Steps to reproduce the behavior:

Have Radeon Evergreen GPU, Start R4.0 with 4.19 kernel from repo. Try starting.

### Expected or desired behavior:

Lightdm starts and login works.

### Actual behavior:

Xorg in crash loop.
Logging is completely useless except dmesg, which weirdly isnt combined in journal.
Error message about radeon failed to create GEM object

### General notes:

Works normally on 4.14 kernel with same settings.

---

### I have consulted the following relevant [documentation](https://www.qubes-os.org/doc/):

Everything except module code.

**Comment by marmarek** [comment]
Can you paste exact kernel message?

**Comment by AndreasKieling** [comment]
[drm:radeon_gem_object_create [radeon]] *ERROR* Failed to allocate GEM object (8294400, 2, 4096, -14)

**Comment by akkuladezeit** [comment]
i have a similar configuration and get the same issue

**Comment by fepitre** [comment]
Have you tried kernel-latest? (5.1+ kernel)

**Comment by manuelschneider** [comment]
Same issue with amd chelsea xt gl (firepro m4000).

Upgrading to kernel-latest and kernel-latest-qubes-vm won't solve the issue here.

**Comment by fepitre** [comment]
Is it working with a latest Fedora?

**Comment by AndreasKieling** [comment]
Will try with kernel 5 again sometime.

**Comment by andrewdavidwong** [comment]
We're suddenly seeing a large number of reports on qubes-users of users whose systems are completely broken after a recent kernel update. (I can't determine whether they all pertain to this issue, but it looks like others have started commenting here around the same time as the qubes-users reports came in.)

* https://groups.google.com/d/topic/qubes-users/FsqNteykUKc/discussion
* https://groups.google.com/d/topic/qubes-users/KCZMbNOI5BQ/discussion
* https://groups.google.com/d/topic/qubes-users/eAgFpJX2dOA/discussion
* https://groups.google.com/d/topic/qubes-users/g110XKZu-cM/discussion

@awokd [asked](https://groups.google.com/d/msg/qubes-users/g110XKZu-cM/wkWkdw_lBQAJ):
> If 4.19 is this problematic, should the update be pulled? 

What do you think, @marmarek?

**Comment by marmarek** [comment]
> If 4.19 is this problematic, should the update be pulled?

For the time being, I've removed 4.19 from "current" repository.

**Comment by awokd** [comment]
> For the time being, I've removed 4.19 from "current" repository.

Thank you both. Will update here too once backup finishes and I can test 
4.19 with my Radeon.

**Comment by awokd** [comment]
Same issue here with Xorg crashing on 4.19.45-1 from current-testing with an older Radeon 7xxx. Switching back to 4.14.119-2 resolved. Attaching a portion of the log [radeondump.txt](https://github.com/QubesOS/qubes-issues/files/3221678/radeondump.txt).

**Comment by marmarek** [comment]
Thanks @awokd for the log, it's really helpful. I've found [a commit](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?id=913b2cb727b7a47ccf8842d54c89f1b873c6deed) queued for Linux 5.2, which according to the description should fix it. I'll try to backport it to 4.19.

**Comment by AndreasKieling** [comment]
@awokd How did you get this verbosity?

**Comment by awokd** [comment]
> @awokd How did you get this verbosity?

I have `options=loglvl=all` in my Xen boot options (not kernel), but I 
thought that only affected the Xen logs. To get the output I attached, I 
did `sudo journalctl` and looked for errors, then copy and paste.

**Comment by marmarek** [comment]
@awokd 4.19.46-3 contains the backport, can you test it?

**Comment by awokd** [comment]
4.19.46-3 works with my Radeon 7xxx. Whonix operation seems normal, tested debian-9, fedora-29, and whonix-ws through whonix-gw. Evastar on qubes-users seemed to have a stuck CPU issue on 4.19.43, but am unable to recreate.

**Comment by awokd** [comment]
Thanks, @marmarek. I'll try to be more proactive on testing AMD related updates in the future too, if I see them coming.

**Comment by manuelschneider** [comment]
4.19.47-1 works with my amd chelsea xt gl (firepro m4000). Thank you very much!

**Comment by AndreasKieling** [comment]
Works on my old radeon too

**Comment by andrewdavidwong** [comment]
@marmarek, did you mean to close this? Was it accidentally left open?
