### ISSUE TITLE
Remove deprecated R3.2 documentation

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#4936]
**Affected component(s) or functionality (if applicable)**

Documentation.

**Brief summary**

Since R3.2 has reached EOL, all R3.2 documentation should be removed.

It will still be accessible via git for historical reference, but it's a potential trap for users.

**Comment by GWeck** [comment]
For users still using / requiring R3.2, it would be helpful to provide an option to show the removed items.

**Comment by andrewdavidwong** [comment]
> For users still using / requiring R3.2, it would be helpful to provide an option to show the removed items.

That option is always available to you via the git repo history. You can simply check out an earlier commit and [serve the site locally](https://github.com/QubesOS/qubesos.github.io#instructions).

If you're referring to an option on the website itself, then you're welcome to file a feature request for this, and we'll consider it. However, it would have to be a community contribution, since we don't pour scarce developer resources into deprecated releases (and this also applies to the website and documentation).

Besides, there are several problems with such an option:

 - Our documentation is not segregated by version. (This has already been [debated ad nauseum in the MLs](https://groups.google.com/d/topic/qubes-users/H9BZX4K9Ptk/discussion). If it needs to be debated further, let's at least continue an existing discussion thread rather than starting another one here, please.) This means that the 3.2 and 4.0 content is usually in the same file, so it would not be straightforward to show/hide only part of the page (as opposed to a separate file).

 - The 3.2 content would still have to be present. It wouldn't really be "removed" if you could just select an option to show it. This means that it would still taint search results and potentially confuse users (i.e.,
it would still be a trap). If the content were moved into separate files, maybe it could more feasibly be hidden from crawlers.

This sort of thing would make more sense if we had a complete set of documentation for every version, like Fedora, but we don't have Fedora's resources. Our documentation is mostly a volunteer effort (with not a lot of volunteers). Even the documentation for our current and only supported release is highly incomplete. Supporting deprecated documentation is a luxury we can't afford.

**Comment by GWeck** [comment]
While installing an older version of the docs locally works rather straightfoward, there might be easier ways to support the user, without too much effort:

- One possibility might be to provide a script performing this installation. This might be helpful especially for the novice user who probably does not have an account with github and first must register to clone the repository.

- Another, still more user-friendly option might be just to clone the current documentaion tree and provide a link to it in the maintained version. I absolutely agree that splitting the tree into two separate trees for R3.2 and R4.x is a lot of work, which does not pay for a deprecated version. But for users of R3.2, it would suffice to have access to the current, mixed tree, which would not need to be updated anymore - removing information pertaining to R4.0 from this old tree would, in my opinion, not be necessary any more, as well as any changes.

**Comment by andrewdavidwong** [comment]
> One possibility might be to provide a script performing this installation. This might be helpful especially for the novice user who probably does not have an account with github and first must register to clone the repository.

It's already pretty straightforward with `docker-compose`. I'm not sure what you have in mind, but you're welcome to provide it.

> Another, still more user-friendly option might be just to clone the current documentaion tree and provide a link to it in the maintained version. 

Providing a GitHub link to the code at a particular tag is easy enough, but I think you're using the terms "clone" and "tree" in non-standard ways, so I'm not sure what you mean there. Anyway, I'll add these links to the README instructions for those who want to look back at the R3.2 site and docs as they were:

https://github.com/QubesOS/qubesos.github.io/tree/auto_8bc049d3
https://github.com/QubesOS/qubes-doc/tree/adw_0f285266

**Comment by GWeck** [comment]
I still see a problem with this approach, as it requires the user to first install some software (Docker and/or) Jekyll) before being able to access the previous documentation. This might not be appropriate or even not allowed in some high security environments.

As I appreciate your limited resources for keeping the documentation up to date, I tried two ways to provide access to the current doumentation state, which will soon be overriden.

- Some PDF-Creation Tools (I tried an old version of Abobe acrobat under Windows)  allow to create a PDF file from a complete web site. Copying https://www.qubes-os.org/doc/ resulted in a not too nice file, which still allows access to the R3.2 docs. For your convenience, I add a zipped version of ths file, which starts from the main entry point and goes two levels deep.
[Qubes_Docs.zip](https://github.com/QubesOS/qubes-issues/files/3050430/Qubes_Docs.zip)

- A better way might be just to perform
   wget -r -k https://www.qubes-os.org/doc/
and make the resulting file tree available, perhaps in a zipped form. (To me, it lokks quite reasonable.)

This would help any user who wants access to the deprecated documentation but does not want / is not allowed to install software on his/her system.

**Comment by unman** [comment]
On Sat, Apr 06, 2019 at 05:11:26AM -0700, Dr. Gerhard Weck wrote:
> I still see a problem with this approach, as it requires the user to first install some software (Docker and/or) Jekyll) before being able to access the previous documentation. This might not be appropriate or even not allowed in some high security environments.
> 
> As I appreciate your limited resources for keeping the documentation up to date, I tried two ways to provide access to the current doumentation state, which will soon be overriden.
> 
> - Some PDF-Creation Tools (I tried an old version of Abobe acrobat under Windows)  allow to create a PDF file from a complete web site. Copying https://www.qubes-os.org/doc/ resulted in a not too nice file, which still allows access to the R3.2 docs. For your convenience, I add a zipped version of ths file, which starts from the main entry point and goes two levels deep.
> [Qubes_Docs.zip](https://github.com/QubesOS/qubes-issues/files/3050430/Qubes_Docs.zip)
> 
> - A better way might be just to perform
>    wget -r -k https://www.qubes-os.org/doc/
> and make the resulting file tree available, perhaps in a zipped form. (To me, it lokks quite reasonable.)
> 
> This would help any user who wants access to the deprecated documentation but does not want / is not allowed to install software on his/her system.
> 

Andrew - I've knocked up some scripts that will strip out the 4.0
sections from the current web site.
I havent proofed the pages yet but I think that approach will be
reasonable.
If you think that's acceptable we could park those pages and link to
them either from the "download versions" page or at the head of the
index page. What do you think? I am sure there will be some users who
will *have* to use 3.2 for a while.

**Comment by andrewdavidwong** [comment]
> Andrew - I've knocked up some scripts that will strip out the 4.0
> sections from the current web site.

I'm guessing you meant "3.2" here?

> I havent proofed the pages yet but I think that approach will be
> reasonable.
> If you think that's acceptable we could park those pages and link to
> them either from the "download versions" page or at the head of the
> index page. What do you think?

I'm not quite sure what you mean. This sounds like it would still require us to maintain the deprecated pages.

> I am sure there will be some users who
> will *have* to use 3.2 for a while.

This doesn't change the fact that 3.2 has reached EOL and is now unsupported.

**Comment by andrewdavidwong** [comment]
> * A better way might be just to perform
>   wget -r -k https://www.qubes-os.org/doc/
>   and make the resulting file tree available, perhaps in a zipped form. (To me, it lokks quite reasonable.)
> 
> This would help any user who wants access to the deprecated documentation but does not want / is not allowed to install software on his/her system.

Thanks for the suggestion. Here you go:

 * https://github.com/QubesOS/qubesos.github.io#deprecated-documentation
 * https://github.com/QubesOS/qubesos.github.io/releases/tag/3.2-EOL

**Comment by unman** [comment]
On Sat, Apr 06, 2019 at 10:58:25AM -0700, Andrew David Wong wrote:
> > Andrew - I've knocked up some scripts that will strip out the 4.0
> > sections from the current web site.
> 
> I'm guessing you meant "3.2" here?

No - strip out 4.0 sections to leave only 3.2.

> 
> > I havent proofed the pages yet but I think that approach will be
> > reasonable.
> > If you think that's acceptable we could park those pages and link to
> > them either from the "download versions" page or at the head of the
> > index page. What do you think?
> 
> I'm not quite sure what you mean. This sounds like it would still require us to maintain the deprecated pages.

No, "park" was meant to suggest "put to one side" - this is supposed to
be a capture of the 3.2 docs before they get removed from the live docs.

> 
> > I am sure there will be some users who
> > will *have* to use 3.2 for a while.
> 
> This doesn't change the fact that 3.2 has reached EOL and is now unsupported.

Yes, but I dont think that's a reason to abandon them.
Anyway, looks like another solution has arisen.

**Comment by andrewdavidwong** [comment]
> Yes, but I dont think that's a reason to abandon them.

It depends on what you mean by "abandon." If "abandon" means "no longer maintain," then that's exactly what it is.

You wouldn't suggest that we continue to maintain the Qubes 3.2 code, even though people may still be using it, so why is the documentation any different? It's not as though we're permanently deleting it or trying to prevent anyone from accessing it. We're just not maintaining it any longer. Every piece of content on the website adds to the maintenance burden (in many ways that are not obvious to the casual observer).

**Comment by unman** [comment]
On Sat, Apr 06, 2019 at 05:06:38PM -0700, Andrew David Wong wrote:
> > Yes, but I dont think that's a reason to abandon them.
> 
> It depends on what you mean by "abandon." If "abandon" means "no longer maintain," then that's exactly what it is.
> 
> You wouldn't suggest that we continue to maintain the Qubes 3.2 code, even though people may still be using it, so why is the documentation any different? It's not as though we're permanently deleting it or trying to prevent anyone from accessing it. We're just not maintaining it any longer. Every piece of content on the website adds to the maintenance burden (in many ways that are not obvious to the casual observer).
> 

I meant abandon the users, as should have been obvious.

We're clearly not going to agree on this.
If there's some acceptable way that people who still use 3.2 (maintained
or not) can *easily* access the documentation that's fine.

**Comment by GWeck** [comment]
> Thanks for the suggestion. Here you go: ...

That's just what should help R3.2 users! Thank you.
