### ISSUE TITLE
System time gets reverted 10 minutes back

### ISSUE THREAD

**Issue by byte255** [QubesOS/qubes-issues#4939]
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
System time

**Brief summary**
System time is 10 minutes behind. Setting the time manually by running `date --set` command in dom0 works but few minutes later the time gets reverted back to 10 minutes behind the true time.

**To Reproduce**
1. Observe incorrect time in the clock tray - 10 minutes behind the actual time.

2. Verify the time in the clock tray is consistent with output of the date command in dom0, so it's not an issue with the clock widget in the tray but rather a system time issue.

3. In dom0 run the following commands:
sudo date --set "2019-04-02 09:00:00"
sudo hwclock -systohc --directisa

4. Verify the time is now correct by running date command and checking time in the clock widget in tray.

5. Several minutes later, check the time in the clock widget in the tray, it has been reverted to 10 minutes behind.

**Expected behavior**
System time and clock widget to have the correct time.

**Actual behavior**
System time and clock widget are 10 minutes behind the actual time.

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
https://github.com/QubesOS/qubes-issues/issues/4835
https://github.com/QubesOS/qubes-issues/issues/3374
https://github.com/QubesOS/qubes-issues/issues/4266

**Comment by marmarek** [comment]
A selected VM is responsible for providing time to dom0 (and other VMs), you can see it in global settings as "clockvm" - by default it is sys-net. So, if sys-net has wrong time, dom0 will be reverted to that time. There should be `systemd-timesyncd.service` running in sys-net, maybe it's broken?

**Comment by byte255** [comment]
Thank you @marmarek, systemd-timesyncd.service is indeed broken in sys-net:

```
[user@sys-net ~]$ sudo service systemd-timesyncd.service status
Redirecting to /bin/systemctl status systemd-timesyncd.service
● systemd-timesyncd.service - Network Time Synchronization
   Loaded: loaded (/usr/lib/systemd/system/systemd-timesyncd.service; enabled; >
  Drop-In: /usr/lib/systemd/system/systemd-timesyncd.service.d
           └─30_qubes.conf
   Active: inactive (dead)
Condition: start condition failed at Mon 2019-04-01 14:11:49 AEDT; 21h ago
           └─ ConditionPathExists=/var/run/qubes-service/clocksync was not met
     Docs: man:systemd-timesyncd.service(8)
```

I tried to start it manually with `sudo service systemd-timesyncd.service start` and it fails with the same error. Any ideas on how to fix it?

**Comment by marmarek** [comment]
Go to `sys-net` settings, to the Services tab. There should be checked "clocksync" entry. If it isn't there, add it and reboot.

**Comment by byte255** [comment]
I did that and the time is correct so far. Thank you @marmarek

**Comment by andrewdavidwong** [comment]
Is there still a bug to fix here, @marmarek?
