### ISSUE TITLE
Installer hangs on Thinkpad T470 with VT-d enabled

### ISSUE THREAD

**Issue by misterzed88** [QubesOS/qubes-issues#4941]
### Qubes OS version:
4.0.1

### Affected component(s) or functionality:
Qubes installation

---

### Steps to reproduce the behavior:

1. Create a bootable Qubes USB
2. Start installation on a Thinkpad T470 where VT-d is enabled.

### Expected or desired behavior:

The installer continues after switching to graphics, starting with the language selection dialog.

### Actual behavior:

The USB successfully boots all the way to where it writes 'Starting installer, one moment', but hangs directly after switching from text to graphics mode. It hangs on the initial graphics screen (blank grey background with cursor arrow in the middle). It does not respond to any mouse or keyboard input (not even the num-lock key)

### General notes:

The installer works all the way if disabling VT-d in the BIOS. The installed Qubes thereafter works fine, even after re-enabling VT-d.

The Qubes 4.0 USB installation does not have this problem, on the same system.

The ThinkPad T470 has the following hardware:
- Core i7 7820 HQ with 32 GB RAM
- Intel HD graphics 630 (integrated)
- Geforce 940 MX graphics

---

### I have consulted the following relevant [documentation](https://www.qubes-os.org/doc/):

The Thinkpad troubleshooting described in https://www.qubes-os.org/doc/thinkpad-troubleshooting is not completely relevant for this case, since it mentions other Thinkpad models, and requires a Xen configuration change after installation, which is not necessary in my case.

The graphics troubleshooting described in https://www.qubes-os.org/doc/intel-igfx-troubleshooting is also not completely on the target, since it deals with issues after an installation.

### I am aware of the following related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues:

Issue #4524 is similar but not identical, since this issue reports a hang at a different time, and there is no need to disable TPM as a workaround (as mentioned in that issue).

**Comment by marmarek** [comment]
The [IOMMU problem](https://www.qubes-os.org/doc/intel-igfx-troubleshooting/#iommu) may be relevant even for installation. Try adding `iommu=no-igfx` to Xen options (in case of UEFI, you need to edit `/EFI/BOOT/BOOTX64.cfg` on the second partition of installation USB).

See also https://github.com/QubesOS/qubes-issues/issues/4919 which have info about devel ISO build with newer kernel.

**Comment by misterzed88** [comment]
Adding `iommu=no-igfx` to the boot options solved the installer hang!

Will you consider making this the default for future releases (to make installation painless for other users suffering from the same problem), or do you think the problem will be solved with a new kernel?

Whenever you have release candidates I can test them on this hardware, if it is of any help.

**Comment by marmarek** [comment]
We had it enabled by default in some release candidate, but while it helps on some devices, it breaks others: https://github.com/QubesOS/qubes-issues/issues/2994

**Comment by misterzed88** [comment]
I see (caught between a rock and a hard place).

But since then (#2994) you have decided to re-enable it in the boot options for the installed Qubes, if I am correct. If the installed version works fine out there, perhaps the issues in #2994 have been fixed with updated kernels? Anyway, wouldn't it be logical to use the same setting (either enabled or disabled) both for the installer and the installed Qubes?

Another option is to just add a small clarification to the igfx troubleshooting page, to make it clear that it is relevant for installation media as well, and which file to edit to fix it.

**Comment by ScratLpp** [comment]
hello,

I got the same problem as you.
But I don't understand how "Open a terminal in dom0" to do this.  What is it ?

I only have my bootable USB and my computer empty. Can i open a terminal when i boot on the USB ?

**Comment by andrewdavidwong** [comment]
> But I don't understand how "Open a terminal in dom0" to do this. What is it ?

To open a terminal in dom0, click on the Applications Menu (sometimes called the "Start Menu"). By default, it's in the upper-left corner of your screen. Then select "Terminal Emulator."
