### ISSUE TITLE
Transient Domain feature similar to Disposable VMs, but better broader

### ISSUE THREAD

**Issue by t4777sd** [QubesOS/qubes-issues#4942]
**The problem you're addressing (if any)**
I have tried to use Disposable VMs, but they are somewhat limited. Correct me if I am wrong, but these appear to be the limitations:

- They are based on templates only. They cannot be based on AppVm or StandaloneVM. Sometimes software gets installed into an AppVM such as AppImages for that specific domain, compiled software, etc 

- It appears that they cannot run consecutive commands. Every time I attempted to use a disposable vm via the qvm-run syntax in the docs it exits as soon as the command finishes. In fact, it appears to exit so long as a GUI does not appear as sending the command "sleep 10000;" also causes an exit.

**What is the issue with the above limitations?**

For me, the primary value of a disposable VM is if there is a non-VM breakout malware, then it is contained to a VM that will be quickly discarded. An AppVM has this property for it's root file system, but all userland data is peristance and as such some malware can persist in this user space. A disposable VM solves this issue.

However, the limitations of a disposable VM mean that it can only be used in very narrow use cases. There are broader use-cases to use a short-lived domain that the disposable VM cannot meet. And thus, there is a sacrifice of security as users use non-transient/disposable VMs for those use cases when they do not need.

**Describe the solution you'd like**
I want to propose the idea of a **Transient Domain**. It is just like a disposable VM and a DisposableVM would be a sub-class of a transient domain. The differences are the following:

- ANY domain such as AppVM, StandaloneVM, TemplateVM can be made into a Transient Domain
- There is no limitations to how long, what can run, or the number of interactions a Transient Domain can have.
- It's primary defining feature is that any changes made to the Transient Domain will be discarded. Beyond that there are no restrictions.

- The transient domain will optionally (depend on if user wants) appear in the application menu. Unlike a Disposable domain it can run more than one application, so it makes since there is a _group of related tasks a user may want to do within that domain instance lifetime._ This is something that does not appear possible with disposable domains.

Upon creation it receives a unique name such as "Transient-834834". From this qvm-run can be run against it like a normal domain. Once it shuts down the snapshots are deleted.

A transient domain is basically the automation of cloning (creating snapshots) of an existing domain of any type, running it, and then automatically cleaning up its snapshots once done.

**Where is the value to a user, and who might that user be?**
The values to this are huge. It is better security than disposable VMs because it offers everything Disposable VMs do, but _allows the ability for the user to utilizes them more often which increases user security_

Example times that a user can utilize a Transient Domain where currently a Disposable VM will not suit their needs and thus increase user security:

1. Have an AppVM / StandaloneVM and want to install a software and try it out? Currently, to guarantee no cruft being installed (in any directory) you must clone a VM, run it, install, and delete it. Very cumbersome. With transient domains you just click on the domain and click "Start Transient Domain based off of [This Domain]". It starts up, you install the software, test it, shutdown the domain and just like a dispsoable VM it disappears.

2. Create long-running malware proof domains that can be used to run multiple commands. For example, I have some software I wrote that uses a domain to process to data. It does not seem I can use disposable VMs because that only allows running one command and then it dies.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
https://www.qubes-os.org/doc/disposablevm/

- No mention that disposable VMs are possible from AppVM or StandaloneVM

- qvm-run [...] automatically exits the disposable VM even if the user does not want it to. It appears to auto-exit if a graphical interface does not appear too since "sleep 10000;" also exits in a few seconds.

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
_A list of links to other bug reports, feature requests, or tasks in the qubes-issues tracker. Do not describe any other unreported bugs, features, or tasks here._

**Comment by marmarek** [comment]
>     * They are based on templates only. They cannot be based on AppVm or StandaloneVM. Sometimes software gets installed into an AppVM such as AppImages for that specific domain, compiled software, etc

Actually, Disposable VMs in R4.0 are based on AppVMs. See https://www.qubes-os.org/doc/disposablevm-customization/
Ability to create Disposable VM out of StandaloneVM is planned for R4.1:  #4670 

>     * It appears that they cannot run consecutive commands. Every time I attempted to use a disposable vm via the qvm-run syntax in the docs it exits as soon as the command finishes. In fact, it appears to exit so long as a GUI does not appear as sending the command "sleep 10000;" also causes an exit.

If you create Disposable VM by starting a service there, then yes. But you can create "static Disposable VM" which isn't automatically killed once a certain command/service ends: https://www.qubes-os.org/doc/disposablevm-customization/#using-static-disposablevms-for-sys-

The fact that you've created this issue may mean this feature isn't documented enough. Feel free to [propose documentation update](https://www.qubes-os.org/doc/doc-guidelines/#how-to-contribute)
