### ISSUE TITLE
Severe graphical slowdown and tearing after switching VTs

### ISSUE THREAD

**Issue by strugee** [QubesOS/qubes-issues#4943]
**Qubes OS version**

R4.0

**Affected component(s) or functionality**

dom0 Xorg

**Brief summary**

When I switch to either a different TTY or to LightDM running on a different VT (I have this situation because of light-locker), then switch back, Xorg is all messed up and doesn't draw stuff right.

**To Reproduce**

1. Switch to a VT with e.g. Ctrl-Alt-F4
2. Switch back to the original VT with Ctrl-Alt-F1(? I _think_ my Xorg's running on VT1 but I don't want to check because then I'd trigger this bug and have to reboot which would be annoying)

**Expected behavior**

I switch back and everything reacts normally.

**Actual behavior**

Xorg dom0 drawing is super slow. For example, it takes 3+ seconds for the window switcher to show up when I hit Alt-Tab.

**Screenshots**

![Screenshot_2019-04-02_17-05-51](https://user-images.githubusercontent.com/911174/55437439-e64ac700-556c-11e9-8877-009df15981f2.png)

I can confirm that this screenshot accurately depicts what actually ended up on my monitor. Notice that I have both a top and bottom bar (the latter of which isn't being drawn at _all_), and that both windows do not have their borders driven. Mousing over the window list in the bottom bar, or over the qubes icon in the upper-left, or generally forcing anything to change such that it would need redrawing does make (only) that particular element show up.

**Additional context**

```
% cat /etc/modprobe.d/disable-nvidia.conf
blacklist nouveau
blacklist nvidia
blacklist nvidia-drm
blacklist nvidia-modeset
alias nouveau off
alias nvidia off
alias nvidia-drm off
alias nvidia-modeset off

% cat /proc/cmdline
root=/dev/mapper/qubes_dom0-root rd.luks.uuid=luks-86339b49-c303-4652-8393-90f75f4f1055 rd.lvm.lv=qubes_dom0/root rd.lvm.lv=qubes_dom0/swap i915.alpha_support=1 nouveau.modeset=0 rd.driver.blacklist=nouveau video=vesa:off rhgb quiet rd.qubes.hide_all_usb plymouth.ignore-serial-consoles systemd.log_level=debug systemd.log_target=kmsg log_buf_len=1M printk.devkmsg=on enforcing=0
```

My laptop (a System76 Oryx Pro, oryp4) has dual Intel/Nvidia graphics cards. I had to disable Nvidia in order to get the Qubes ISO to boot and have kept that setting ever since. I haven't tried enabling Nvidia again since enabling things like `kernel-latest`.

Logs: 
[hypervisor.log](https://github.com/QubesOS/qubes-issues/files/3036012/hypervisor.log)
[Xorg.0.log](https://github.com/QubesOS/qubes-issues/files/3036013/Xorg.0.log)
[dmesg](https://github.com/QubesOS/qubes-issues/files/3036016/dmesg.log) (sorry for the systemd spam... I think it might be left over from some debugging and if it's a big problem I can look into it)

**Solutions you've tried**

None. I will probably try booting `kernel` instead of `kernel-latest` when I get a chance, just in case that's related.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

https://www.qubes-os.org/doc/gui-configuration/, https://www.qubes-os.org/doc/intel-igfx-troubleshooting/ (this sounds similar and I _do_ have the referenced Xorg log line, but it only happens when I switch to/from VTs), https://www.qubes-os.org/doc/nvidia-troubleshooting/

I also searched the mailing list.

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

https://github.com/QubesOS/qubes-issues/issues?utf8=%E2%9C%93&q=is%3Aissue+tty+flickering+is%3Aclosed+, https://github.com/QubesOS/qubes-issues/issues?q=is%3Aissue+switching+to+tty+is%3Aclosed

**Comment by na--** [comment]
@strugee, did you manage to fix or work around this issue?

**Comment by strugee** [comment]
No. I haven't poked at it since I filed this report though. Generally I just don't switch VTs.

**Comment by strugee** [comment]
This appears to have possibly gone away for me. I need to do some more testing, though.

**Comment by iamahuman** [comment]
Is this #5460? Then, does `xorg-x11-drv-intel-v2.99.917-49.20210126` (QubesOS/updates-status#2328) solve it?
