### ISSUE TITLE
VT-d interrupt remapping error during Qubes 4.0.1 install on Dell Precision T3500

### ISSUE THREAD

**Issue by Strazzom** [QubesOS/qubes-issues#4945]
### Qubes OS version:
Qubes version: 4.0.1

### Affected component(s) or functionality:
Qubes 4.0.1 Installer

---

### Steps to reproduce the behavior:
When installing Qubes 4.0.1 on a Dell Precision T3500, an error pops up about lacking "VT-d" and "Interrupt Remapping". This occurs after selecting the language options.

This motherboard and processor do support VT-x and VT-d, and I have verified that they are enabled in the BIOS.

### Expected or desired behavior:
Installation should proceed as normal, because VT-d is supported by the hardware.

### Actual behavior:
Error described above.

### General notes:
I have done some research into this issue, and have concluded that this hardware should theoretically work with Qubes 4.0.1. As an aside, I also tested this with the original Qubes 4.0 installer, which produced the same result (this was right after the initial 4.0 release).

The motherboard is the standard one for a T3500, I am not sure what the exact model number is.

The processor is a dual core Intel Xeon W3505, running at 2.4GHz. I have verified that this processor has the features required to run Qubes 4.0, and I have verified that all the relevant BIOS options are enabled (as described above.)

This desktop has 12GB DDR3 RAM.

Initially, the BIOS version was A01, the first one released (~2009 by my reckoning). I suspected that the issue was caused by a bug in the BIOS, so I updated it to the latest one (~2013) A17. This did not fix the issue. I have also tried resetting the BIOS to factory default settings (after updating to BIOS version A17) and then only enabling the virtualization related features (VT-x/VT-d). This also did not fix the issue.

From some initial research (https://software.intel.com/sites/default/files/managed/c5/15/vt-directed-io-spec.pdf) I have concluded that Interrupt Remapping is a standard feature of VT-d, and that any system which has VT-d should also have interrupt remapping.

The following passage is from the above PDF:

> A general requirement for all of above I/O virtualization models is the ability to isolate and restrict device accesses to the resources owned by the partition managing the device. Intel VT for Directed I/O provides VMM software with the following capabilities:
> [...]
> - Interrupt remapping: for supporting isolation and routing of interrupts from devices and external interrupt controllers to appropriate VMs.

Note that there were other features listed, I have included only IR for the sake of being concise.

My current theory is that Qubes is failing to detect VT-d for whatever reason, despite it technically being there. It may also be an issue with the BIOS being buggy, although I doubt it.
 

---

### I have consulted the following relevant [documentation](https://www.qubes-os.org/doc/):

I consulted the system requirements for Qubes 4.0.
https://www.qubes-os.org/doc/system-requirements/

There may have been other documentation, however I do not recall what specifically I looked at.

### I am aware of the following related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues:

https://github.com/QubesOS/qubes-issues/issues/4407
https://github.com/QubesOS/qubes-issues/issues/4309

**Comment by marmarek** [comment]
According to [ark.intel.com](https://ark.intel.com/content/www/us/en/ark/products/40800/intel-xeon-processor-w3505-4m-cache-2-53-ghz-4-80-gt-s-intel-qpi.html), Xeon W3505 do not have VT-d.
Here is a full list of processors that do have VT-d: https://ark.intel.com/content/www/us/en/ark/search/featurefilter.html?productType=873&0_VTD=True

**Comment by Strazzom** [comment]
My apologies, it seems only the motherboard supports VT-d, not the processor.

On the product page (https://ark.intel.com/content/www/us/en/ark/products/40800/intel-xeon-processor-w3505-4m-cache-2-53-ghz-4-80-gt-s-intel-qpi.html) it does not list VT-d at all, hence contributing to the confusion.

Looks like I am buying a new processor. Thanks for your help.
