### ISSUE TITLE
Missing 4.0 documentation: Implementation of DisposableVMs link in Qubes Documentation page only covers 3.2

### ISSUE THREAD

**Issue by brendanhoar** [QubesOS/qubes-issues#4948]
**Qubes OS version (if applicable)**
_If applicable, the version of Qubes OS that this task concerns (e.g., `R4.0`), available via the command `cat /etc/qubes-release` in a dom0 terminal._
R4.0
**Affected component(s) or functionality (if applicable)**
_If applicable, the component or functionality of Qubes OS that this task concerns._
Documentation
**Brief summary**
_A clear and concise summary of the task that should be done._
This is linked from the top level Qubes Documentation page under "Implementation of DisposableVMs": https://www.qubes-os.org/doc/dvm-impl/

However, it does not cover R4.0, just R3.2
**Additional context**
_Add any other context about the problem here._

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
_A list of links to the Qubes documentation (or other relevant software documentation) pages you have already consulted._

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
_A list of links to other bug reports, feature requests, or tasks in the qubes-issues tracker. Do not describe any other unreported bugs, features, or tasks here._

**Comment by pierwill** [comment]
@andrewdavidwong I'm happy to help revise this page. Are there any discussions or source code I could consult regarding the implementation of DisposableVMs in R4.* vs R3.2,,?

**Comment by andrewdavidwong** [comment]
> @andrewdavidwong I'm happy to help revise this page. Are there any discussions or source code I should consult first regarding the implementation of DisposableVMs in R4.* vs R3.2?

Not that comes to mind. @marmarek, do you know of any?

**Comment by marmarek** [comment]
I think the most complete (which doesn't mean really complete...) differences description is here: https://www.qubes-os.org/news/2017/10/03/core3/#disposable-vms-redesigned

**Comment by andrewdavidwong** [comment]
Closing as both 3.2 and 4.0 have reached EOL.
