### ISSUE TITLE
sys-net not starting and no vms booting

### ISSUE THREAD

**Issue by Seabass5701** [QubesOS/qubes-issues#4950]
### Qubes OS version:

Hey everyone, bear with me as I am somewhat of a noob to Qubes, and haven't been on in awhile due to this issue which I have held on the backburner. So one day, everything on Qubes was running fine and smoothly, until I (stupidly) decided to hard-shutdown my computer with all my vms still up and running, and when I booted back on again, I was met with Qubes not working at all. As far as booting is concerned, everything appeared to be fine, but sys-net would not start, and somehow, the debian-9 template private vm file was gone. Now I have tried deleting sys-net and re-creating it from scratch, but nothing has seemed to work so far, and I am in desperate need of help, as I have data on certain vms, which I'm unable to recover due to sys-net not properly running. Each time I used the command "qvm-start sys-net", it takes about 5 seconds for the top right corner of the screen to register "Domain sys-net is starting", but then I am met with a 60 second long wait time, during which the sys-net vm while attempting to start goes from 400MB down to 384MB, until the terminal returns a response saying "Cannot connect to qrexec agent for 60 seconds, see /var/log/xen/console/guest-sys-net.log for details". It does this each and every time I try to start sys-net. I have even checked the guest-sys-net log for details, as it has said, but I am met with an insurmountably long list of data, some of which I have no clue of what is being said. If someone could please help, I would greatly appreciate it, as this problem has kept me from using Qubes on my computer for about a year almost now, and I haven't been able to figure it out. Plus I have data that I am not willing to lose by completely reinstalling Qubes. Thanks!

### Affected component(s) or functionality:

sys-net and all other vms requiring routed internet access from sys-net > sys-firewall

---

### Steps to reproduce the behavior:

qvm-start sys-net

OR

qvm-start sys-firewall

### Expected or desired behavior:

sys-net starts and gives internet access to all other vms dependent upon it

### Actual behavior:

it takes about 5 seconds for the top right corner of the screen to register "Domain sys-net is starting", but then I am met with a 60 second long wait time, during which the sys-net vm while attempting to start goes from 400MB down to 384MB, until the terminal returns a response saying "Cannot connect to qrexec agent for 60 seconds, see /var/log/xen/console/guest-sys-net.log for details".

### General notes:

---

**Comment by andrewdavidwong** [comment]
Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this does not appear to be suitable for `qubes-issues`. We ask that you please send this to the `qubes-users` [mailing list](https://www.qubes-os.org/support/) instead. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a brief comment explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.
