### ISSUE TITLE
qubes-builder document GCC removal

### ISSUE THREAD

**Issue by awokd** [QubesOS/qubes-issues#4952]
**Qubes OS version**
_The version of Qubes OS you're using (e.g., `R4.0`), available via the command `cat /etc/qubes-release` in a dom0 terminal._
R4.0

**Affected component(s) or functionality**
_The component or functionality of Qubes OS that is not working as expected._
qubes-builder

**Brief summary**
_A clear and concise summary of the bug._
Documentation on using binary packages in qubes-builder is unclear.

**To Reproduce**
1. Perform standard build steps per https://www.qubes-os.org/doc/qubes-r3-building/
2. See https://github.com/QubesOS/qubes-issues/issues/3979#issuecomment-396071114
3. Edit builder.conf

**Expected behavior**
Find a COMPONENTS line somewhere from which to remove GCC

**Actual behavior**
Only reference to GCC is in comment about using package repositories

[builder.conf.txt](https://github.com/QubesOS/qubes-issues/files/3050970/builder.conf.txt)

**Comment by marmarek** [comment]
The actual COMPONENTS list is defined in included version-dependent config from example-configs (see series of `include` directives near the file beginning).

It is possible to exclude specific component by adding a line like this:
```
COMPONENTS := $(filter-out gcc,$(COMPONENTS))
```

**Comment by awokd** [comment]
Thanks, will update and re-test.

**Comment by awokd** [comment]
Please remove the "Bug" label; don't think I am allowed.

**Comment by andrewdavidwong** [comment]
> Please remove the "Bug" label; don't think I am allowed.

Why do you believe that this is not a bug?

**Comment by awokd** [comment]
It was a documentation task, not a code bug. Am I using different definitions?

**Comment by andrewdavidwong** [comment]
> It was a documentation task, not a code bug. Am I using different definitions?

Yes. The `T: bug` label applies to any problem or defect result in undesired behavior, which can include a problem in the documentation resulting in, e.g., a reader being confused or taking the wrong action.

**Comment by awokd** [comment]
Documentation merged.
