### ISSUE TITLE
VM startup/shutdown bottlenecks in lvm

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#4953]
**Qubes OS version**
_The version of Qubes OS you're using (e.g., `R4.0`), available via the command `cat /etc/qubes-release` in a dom0 terminal._

`Qubes release 4.0 (R4.0)`

**Affected component(s) or functionality**
_The component or functionality of Qubes OS that is not working as expected._

VM startup/shutdown

**Brief summary**
_A clear and concise summary of the bug._

When many VMs are started up or shut down simultaneously, their startup/shutdown seems to be serialized in `lvm`.  One instance uses nearly 100% CPU, while the rest are idle.

**To Reproduce**
_Steps to reproduce the behavior:_

1. Create at least one storage pool that uses an HDD.  This is not strictly necessary, but it makes the problem signficantly more noticeable.
2. Create a lot of VMs simultaneously
3. Wait for them to start up.
4. Shut them down simultaneously

**Expected behavior**
VM startup and shutdown happens in parallel, avoiding I/O bottlenecks.  These are especially severe on spinning disks.

**Actual behavior**
_What actually happened (instead of what you expected to happen)._

VM startup and shutdown is serialized in `lvm`.  Therefore, starting N VMs takes roughly N times longer than starting 1 VM.

**Additional context**

The problem is much, much more severe if at least one storage pool is on an HDD instead of an SSD.

**Solutions you've tried**
None yet.

**Comment by marmarek** [comment]
Related problem recently identified #4927 . Check if it isn't the same problem.

**Comment by DemiMarie** [comment]
@marmarek It is, thanks!
