### ISSUE TITLE
Not Able to Run Settings in sys-net

### ISSUE THREAD

**Issue by rayjos** [QubesOS/qubes-issues#4954]
**Qubes OS version**
R4.0
**Affected component(s) or functionality**
Configuration of networking in sys-net.  Not able to run Settings.

**Brief summary**
Not able to run sys-net Settings.  I would like to configure the wireless networks.

After adding "Settings" to sys-net in Qube Manager, clicking on "Service: sys-net | Settings" produced no observable system response.
After stopping sys-net, from dom0 Terminal, entering:
qvm-run sys-net gnome-terminal
the vm started and Terminal opened.
Entering:
qvm-run sys-net Settings
produced command failed with code 127 and no settings window.  
Entering:
qvm-run sys-net settings
produced 'Running 'settings' on sys-net
sys-net: command failed with code: 127

**To Reproduce**
After adding "Settings" to sys-net in Qube Manager, clicking on "Service: sys-net | Settings" produced no observable system response.
After stopping sys-net, from dom0 Terminal, entering:
qvm-run sys-net gnome-terminal
the vm started and Terminal opened.
Entering:
qvm-run sys-net Settings
produced command failed with code 127 and no settings window.  
Entering:
qvm-run sys-net settings
produced 'Running 'settings' on sys-net
sys-net: command failed with code: 127

**Expected behavior**
On running sys-net Settings, I expected some kind of network configuration method to arise (I am new and have not found any details on how to configure the wireless networks).  
**Actual behavior**
Either no response of command failure  code 127.

**Screenshots**
N/A

**Additional context**
Aftering installing R4.0, networking failed on the device.  I found the USB device had been attached to sys-net.  So I removed it and added my network device.  
If this can be created by improper installation, I would like to reinstall.  To do so, I would need to know how to correctly install it.  The hardware has been running networking on Debian 9 and networking was working on this machine with Qubes R3 but USB did not on R3.

**Solutions you've tried**
As stated above.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
I have looked at the first file on the list about configuration but found no information on setting up a wireless network.  I did not find a tool to generally search the documentation.

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
N/A

Thank you.

**Comment by andrewdavidwong** [comment]
Running Settings in `sys-net` seems like a red herring. It probably won't help with your real problem, which is that your wireless connection is not working. It's more likely that you need to install firmware for your network card, which is covered in the documentation, or some other troubleshooting, which you should ask about on the `qubes-users` [mailing list](https://www.qubes-os.org/support/) instead.

Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this does not appear to be suitable for `qubes-issues`. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a brief comment explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.
