### ISSUE TITLE
Make qvm-sync-appmenus harder to misuse

### ISSUE THREAD

**Issue by michaelschefczyk** [QubesOS/qubes-issues#4956]
Dear all,

in R 4.0.1 using the fedora-29 template, I did create additional AppVm shortcuts. I did install freedesktop and created shortcuts containing one exec statement initating a rdp connection. The shortcuts work, but the user documentation in https://www.qubes-os.org/doc/managing-appvm-shortcuts/ seems flawed in terms of managing shortcut menus.

After setting up the .desktop files in the template VM and running qvm-sync-appmenus fedora-29 in dom0, the qubes start menu contains a long list of entries for all AppVms based on fedora-29. This holds even for newly created AppVms. Changes via "Qube settings" are no longer picked up. The .menu entries in the applications-merged folder at dom0 are short. One can modify them, but that will not change anything even after reboots.

Effectively, control over shortcuts in the qubes start menu is lost - apparently permanently - after executing the qvm-sync-appmenus command. I suspect that this is a bug and/or a documentation flaw.

Regards,

Michael Schefczyk

**Comment by marmarek** [comment]
Have you by a chance executed `qvm-sync-appmenus` as root? Don't do that...

**Comment by marmarek** [comment]
Running menu-related tools as root will cause files to be created in different directories, not maintained by other qubes tools (/usr/share/applications, instead of ~/.local/share/applications).
To cleanup those entries, you may try to execute `qvm-appmenus --remove` (not `qvm-sync-appmenus`) as root for all affected VMs. If that doesn't help, you'll need to remove those files manually (from /usr/share/applications, /usr/share/desktop-directories and probably /etc/xdg/menus).

**Comment by andrewdavidwong** [comment]
Labeling this as a UX enhancement to make `qvm-sync-appmenus` harder to shoot oneself in the foot with. However, if it's deemed to be sufficiently safe already, this can be closed as `not an issue`.

**Comment by michaelschefczyk** [comment]
Thank you very much for your quick response! Indeed, running qvm-sync-appmenus as root was the cause. I did figure out which files do delete in order to resolve the problem. Nevertheless, a simple hint in the documentation would be good. As updating dom0 requires root, the common user may assume that root would be required in other situations where it is truely not only not required ...

**Comment by andrewdavidwong** [comment]
I know we already have a "don't run this as root" warning for certain Qubes CLI tools. Sounds like we need that for this one, too.

**Comment by t4777sd** [comment]
Even better than adding warnings why not just check if it is root with os.geteuid(). If it is root, then refuse to run and give an error explaining why.

If the only outcome of running a tool as root is going to be bad things, then preventing it from running is best I think.

**Comment by andrewdavidwong** [comment]
> Even better than adding warnings why not just check if it is root with os.geteuid(). If it is root, then refuse to run and give an error explaining why.
> 
> If the only outcome of running a tool as root is going to be bad things, then preventing it from running is best I think.

That's what I mean. We already have tools that detect when you try to run them as root, then explain why you shouldn't.
