### ISSUE TITLE
Can't build Whonix-gateway template

### ISSUE THREAD

**Issue by awokd** [QubesOS/qubes-issues#4957]
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
qubes-template-whonix

**Brief summary**
Build failure.
```
-> Building template stretch (logfile: build-logs/template-stretch.log)...
make: *** [Makefile:312: template-local-stretch+whonix-gateway+minimal+no-recommends] Error 1
```

**To Reproduce**
Follow https://www.qubes-os.org/doc/qubes-iso-building/ or https://www.qubes-os.org/doc/building-whonix-template/.

**Expected behavior**
Shiny new Whonix templates.

**Actual behavior**
From `template-stretch.log`:
```
Recommended packages:
  tor
The following NEW packages will be installed:
  apt-transport-tor
[...snip...]
Get:2 file:/tmp/qubes_repo stretch Release [342 B]
Err:3 tor+http://deb.dds6qkxpwdeubwucdiaord2xgbbeyds25rbsgr73tbfpqpt4a6vjwsyd.onion stretch-proposed-updates InRelease
  Could not connect to localhost:9050 (127.0.0.1). - connect (111: Connection refused) [IP: 127.0.0.1 9050]
Get:2 file:/tmp/qubes_repo stretch Release [342 B]
Get:4 file:/tmp/qubes_repo stretch Release.gpg
Ign:4 file:/tmp/qubes_repo stretch Release.gpg
Get:5 file:/tmp/qubes_repo stretch/main amd64 Packages [19.4 kB]
Hit:6 https://deb.qubes-os.org/r4.0/vm stretch InRelease
[...snip...]
W: Failed to fetch tor+http://deb.dds6qkxpwdeubwucdiaord2xgbbeyds25rbsgr73tbfpqpt4a6vjwsyd.onion/dists/stretch-proposed-updates/InRelease  Could not connect to localhost:9050 (127.0.0.1). - connect (111: Connection refused) [IP: 127.0.0.1 9050]
W: Some index files failed to download. They have been ignored, or old ones used instead.
[...snip...]
E: Unable to locate package qubes-whonix-gateway
Removing 'local diversion of /sbin/initctl to /sbin/initctl.distrib'
make[1]: *** [Makefile:64: rootimg-build] Error 100
```

**Additional context**
https://github.com/marmarek/qubes-template-whonix/commit/5f6fef1b09eef3384fb65a89f06faa48e5c1f95b

**Solutions you've tried**
Reverting above commit fixes it. I also tried installing tor and torsocks before apt-transport-tor since we're in `no-recommends` mode, but I was still getting `Could not connect to localhost:9050 (127.0.0.1). - connect (111: Connection refused) [IP: 127.0.0.1 9050]`. Maybe tor needs to be running and/or configured first if we want to use an .onion there?

**Comment by adrelanos** [comment]
I guess it's best I revert this.

Not easy to onionize the Debian template (which Whonix templates are based on) anyhow?

**Comment by awokd** [comment]
> I guess it's best I revert this.
> 
> Not easy to onionize the Debian template (which Whonix templates are based on) anyhow?

It might be my misunderstanding: are Whonix templates supposed to be built in an environment that already has Tor functional? Not sure which `localhost` it's referring to from inside a chroot. Otherwise, it's a bit of a chicken and egg scenario.

**Comment by adrelanos** [comment]
awokd:
>> I guess it's best I revert this.
>>
>> Not easy to onionize the Debian template (which Whonix templates are based on) anyhow?
> 
> It might be my misunderstanding: are Whonix templates supposed to be built in an environment that already has Tor functional?

I guess we shouldn't require that. "You need to use [effectively] [or
create your own Tor-Gateway] our binaries to create our binaries."
Wouldn't sound great.

**Comment by adrelanos** [comment]
Whonix 15 templates do build. See also:

https://github.com/QubesOS/qubes-issues/issues/5108#issuecomment-503890476

Won't fix for Whonix 14.

Therefore please close.
If not building, please reopen.
