### ISSUE TITLE
Screen locker in AppVM can DoS the user

### ISSUE THREAD

**Issue by u2482** [QubesOS/qubes-issues#4960]
**Qubes OS version**
Qubes release 4.0 (R4.0)

**Affected component(s) or functionality**
debian-9 template and derived appVMs.

**Brief summary**
Debian-9 derived AppVMs, if left running and not used (i.e. you are interacting with another AppVM for a long time) will lock the screen and you can't get it back without doing something sneaky/heroic.  Debian-9 template includes light-locker, and it's on; turn it off.

**To Reproduce**
_Steps to reproduce the behavior:_
_1. Start a Debian-9 based AppVM.  Leave it run.
_2. Deselect it and go interact with another AppVM for a long time.
_3. Eventually you get a black screen with a 1-pixel border in the color of your Debian-9 AppVM selected window header color.
_4. Try to get a GUI back....

**Expected behavior**
If you are at the keyboard and mouse, the screen shouldn't lock.
AppVMs should not include any "screensaver" or "locking" functionality; Dom0 should do that.

**Actual behavior**
Screen locks; unusual workaround required to get it back.

**Screenshots**

**Additional context**
Debian-9 template includes light-locker, the LightDM screensaver application.  And it's turned on.

Workarounds:
*  Ctrl-Alt-F2, log in, and qvm-kill any Debian-9 based AppVMs.
*  Ctrl-Alt-F2, log in, and qvm-run "ps aux" toward any Debian-9 based AppVMs, then grep (or otherwise find) the process for light-locker. Get the process number.  qvm-run "kill -9 \<process-number\>" toward that AppVM.
* Start Settings Manager/Session and Startup/Application Autostart/ ensure that Screen Locker is turned off.  This must be done in the TemplateVM and any existing AppVMs from the template.

**Solutions you've tried**

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

**Comment by brendanhoar** [comment]
@u2482 - does the app's light-locker window block all workspaces or just the workspace that the window is on? e.g. does ctrl-alt left/right not bring you to a different workspace that doesn't have the deb-9 window?

**Comment by u2482** [comment]
@brendanhoar Oooh, didn't know about that hotkey combination.  I have light-locker turned off now through the Settings Manager, and I actually need the computer now, so I can't try it.

I am pretty sure that the problem shows up if you have the Debian-9 AppVM on another workspace from the one I am currenly using.

**Comment by marmarek** [comment]
light-locker is not installed by default, so it must be pulled in by some package you've added to the template. But indeed it makes sense to disable it even if it gets installed.

**Comment by u2482** [comment]
1) I got it.  No, ctrl-alt-arrow does not get you a workspace you can see.  Yes, I had a DispVM on another workspace, sitting around doing nothing.
2) The DispVM had light-locker turned on by default, even though (I think) I had it turned off in the TemplateVM.  Must have done it wrong.

Yeah, I'll go look at installed packages and see what may have dragged it in.

**Comment by brendanhoar** [comment]
@u2482 - Does alt-space give you the window menu from which you can disable full-screen?

I know that for HVMs, the default setting is not to allow full screen, but the templates do allow it I think.

@marmarek - Are there any other manual or automatic mitigations against UI denial of service from a compromised (or misconfigured :) ) VM? I thought that the VMs could not control which workspace in dom0 their window(s) appeared on?

**Comment by marmarek** [comment]
There is way for VM to create a window outside of window manager control: use override-redirect flag. More details in https://github.com/QubesOS/qubes-issues/issues/4705
Such window will have a thin colorful border, but that's all. It's also always on top in most cases... So the only option is to switch to console and kill it from there (qvm-run or such).

**Comment by u2482** [comment]
@marmarek Yes, that thin border window is what I have.

**Comment by brendanhoar** [comment]
Curious if there is a programmatic way to periodically scan for such windows and force them to be moved/resized or not be at the top of the stack? Wouldn't be a fix for the security issue or a targeted DOS issue, but for inadvertent self-DOS attacks, might be helpful temporary mitigation.

**Comment by unman** [comment]
The last time I tested this I tried to duplicate the issue triggering light locker - the screen did *not* block , and the usual warning about an application attempting to open a large window appeared instead.
Trying to retest today, I get a format error in light-locker which is an upstream bug for Debian, not related to this: light-locker can not be activated under debian-9.

@andrewdavidwong 
In view of the above I suggest this issue be closed, since existing defaults deal with the reported issue.

**Comment by u2482** [comment]
Hello, I still exist.  In the time that has passed since I reported this, life has moved on, my system is now Qubes 4.1, and I am using mostly debian-10 based AppVMs.  Whatever I did to pull in light-locker, which was probably an accident/mistake, has not been replicated in my current configuration.  Is this still relevant?

(Yeah this bug was super-annoying when I first got it, but it must not be common because I think I was the only commenter.  I guess a troll could do something like perhaps get a browser to put up a light-locker-like window, but this is not a security problem.)

**Comment by DemiMarie** [comment]
> EDIT:- I had suggested that this issue be closed, but after further testing was able to confirm the original report, with _no_ warning triggered. The issue remains open.

@unman: https://github.com/QubesOS/qubes-gui-daemon/pull/71 might help with this in R4.1.  It prevents an override redirect window from exceeding the bounds of the work area, so it cannot cover the taskbar.  That said, the lack of a warning is a separate bug.  I wonder if the warning appears, but is (incorrectly) stacked under the bad window.

> Curious if there is a programmatic way to periodically scan for such windows and force them to be moved/resized or not be at the top of the stack? Wouldn't be a fix for the security issue or a targeted DOS issue, but for inadvertent self-DOS attacks, might be helpful temporary mitigation.

@brendanhoar: I am not aware of any legitimate reasons for an override redirect window to display on a workspace other than the one on which it was created.  There may be other approaches, too.  For instance, I suspect that notification window in the GUI qube should always be above any window displayed by the GUI daemon.

**Comment by DemiMarie** [comment]
The GUI daemon already has code to ensure that no qube window can draw over the screen locker.  That could be extended to cover the notification code as well.

**Comment by DemiMarie** [comment]
The `_NET_WM_STATE` and `_NET_WM_WINDOW_TYPE` properties appear to be the key here: if I am reading the specification correctly, they provide enough information to determine which windows must always kept on top.
