### ISSUE TITLE
StandaloneVM Created from Template has Black GUI if using VM Kernel

### ISSUE THREAD

**Issue by dylangerdaly** [QubesOS/qubes-issues#4965]
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
GUI Working

**Brief summary**
The entire GUI is black, gnome-console runs, but I can't see anything, same with Firefox

**To Reproduce**
Create a StandaloneVM from a Template, run grub update, set kernel to ``

**Expected behavior**
GUI Works

**Actual behavior**
GUI is Black

**Screenshots**
https://imgur.com/a/U7JdRLG

**Additional context**
None

**Solutions you've tried**
Using Xen Stubdom

**Comment by dylangerdaly** [comment]
It's 100% running gnome-terminal, it's just the gui is messed up
https://imgur.com/a/WQ6sckP

**Comment by marmarek** [comment]
Looks like missing u2mfn kernel module. See https://www.qubes-os.org/doc/managing-vm-kernel/#using-kernel-installed-in-the-vm

**Comment by dylangerdaly** [comment]
Okay cool, if anyone else has this issue, update the kernel first `dnf update`

Start the HVM, gnome-terminal will start black, goto dom0 terminal

`qvm-run --pass-io fedora-standalone 'sudo dkms status'`
Confirm Version and Remove it
`qvm-run --pass-io fedora-standalone 'sudo dkms remove u2mfn/4.0.23 --all'`
Rebuilt it
`qvm-run --pass-io fedora-standalone 'sudo dkms build u2mfn/4.0.23'`
Reinstall it
`qvm-run --pass-io fedora-standalone 'sudo dkms install u2mfn/4.0.23'`
Restart the appVM and the GUI should work fine
