### ISSUE TITLE
Caps Lock light doesn't work when decrypting Hard Drive

### ISSUE THREAD

**Issue by Simon-Davies** [QubesOS/qubes-issues#4971]
**Qubes OS version**
_The version of Qubes OS you're using (e.g., `R4.0`), available via the command `cat /etc/qubes-release` in a dom0 terminal._

4.0.1

**Affected component(s) or functionality**
_The component or functionality of Qubes OS that is not working as expected._

The caps lock light doesn't work when decrypting the Hard Drive

**Comment by andrewdavidwong** [comment]
I suspect that this is either `not our bug`, since Qubes is not even running yet at that point, or a problem that is localized to your specific hardware, but I'll leave it to the devs to decide.

**Comment by Simon-Davies** [comment]
It has been the case on two Dell XPS 15 laptops with different hardware, the i7 and i9 versions.

**Comment by marmarek** [comment]
Generally it looks like Caps Lock does not work in text console. I'm not sure if that's Qubes specific or not.
