### ISSUE TITLE
Applications can start in inconsistent/incomplete environment during VM boot

### ISSUE THREAD

**Issue by ij1** [QubesOS/qubes-issues#4976]
**Qubes OS version**

R4.0

**Affected component(s) or functionality**

Application start, at least debian-9 based templates affected.

**Brief summary**

An early starting (wrt. to VM boot) application (xterm) does get an inconsistent environment. 
Manifests as other problems such as ssh-agent environment variables not present or as a failure to correctly apply the white-on-black coloring from /etc/X11/app-defaults/XTerm-color (it uses just the XTerm file instead).

**To Reproduce**

It's hard to give a foolproof reproducer but for me this occurs now often enough currently with this sequence:

1. For a non-running qube in qube manager: run command in qube, type xterm
2. Wait for it to start
3. Do the same again slightly later
4. Compare environments

I believe this is not specific to qube manager "run" functionality as I've seen wrong terminal colors also for xterms started from window manager's menu.

I do not claim that somebody else can reproduce it with this sequence but seems to work for me now quite reliably on one machine (but not on other machines as frequently so it may be elusive).

**Expected behavior**

The starting shells gets the same environment (except obvious differences such as different PIDs).

**Actual behavior**

Some environment variables are not present for the early starting shell. The actual variables missing are not always same for the different runs but may be a larger/smaller set of variables (perhaps a race with init?). Here is one example:

```
--- first.env   2019-04-16 17:34:21.416000000 +0300
+++ second.env  2019-04-16 17:34:29.236000000 +0300
@@ -18,0 +19,2 @@
+GNOME_DESKTOP_SESSION_ID=c2
+GPG_AGENT_INFO=/run/user/1000/gnupg/S.gpg-agent:0:1
@@ -40 +42 @@
-PPID=600
+PPID=830
@@ -45 +47 @@
-QREXEC_AGENT_PID=528
+QREXEC_AGENT_PID=818
@@ -47,0 +50,2 @@
+QT_ACCESSIBILITY=1
+QT_LINUX_ACCESSIBILITY_ALWAYS_ON=1
@@ -48,0 +53,3 @@
+QUBES_ENV_SOURCED=1
+QUBES_KEYMAP=$'xkb_keymap {\n\txkb_keycodes { include "evdev+aliases(qwerty)"\t
+QUBES_USER_KEYMAP=
@@ -51 +58,3 @@
-SHLVL=2
+SHLVL=3
+SSH_AGENT_PID=687
+SSH_AUTH_SOCK=/tmp/ssh-YJPHDGsn8O9Q/agent.629
@@ -53,0 +63 @@
+UPDTYPE=NonUpdateableVM
@@ -55 +65,3 @@
-WINDOWID=2097165
+VMTYPE=AppVM
+WINDOWID=18874383
+WINDOWPATH=7
@@ -57 +69,4 @@
-XDG_SESSION_ID=c1
+XDG_SEAT=seat0
+XDG_SESSION_CLASS=user
+XDG_SESSION_ID=c2
+XDG_VTNR=7
```

**Additional context**

It's kind of nice that one can exec stuff as soon as possible but on the same time there is need to have a way to produce consistent behavior. Thus, I'm on the edge whether to call this "a feature" or a bug.

Probably impacts other than xterm too and could perhaps even prevent the app from starting(?) which would potentially make this duplicate of some other issue(s). I also occassionally see xterm not appearing at all.

I think that the impact is not limited to environment variables (as they would not explain the XTerm vs XTerm-color file selection).

DomU logs:

[journalctl.txt](https://github.com/QubesOS/qubes-issues/files/3086577/journalctl.txt)
[qubes.pkgs.txt](https://github.com/QubesOS/qubes-issues/files/3086579/qubes.pkgs.txt)
[xsession-errors.txt](https://github.com/QubesOS/qubes-issues/files/3086580/xsession-errors.txt)

PID 528 (qrexec PID taken from the env variable) started jiffies is 547 (starttimes from /proc/528/stat, 547 / 100 = 5.47s). Xterm at 570 and bash (the one where from the environment is extracted) at 709.

**Solutions you've tried**

None I know of.

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

These "not starting an application" reports might be caused by the same root issue but I'm not sure:
#4203
#3533

**Comment by marmarek** [comment]
can you reproduce it with `qvm-run` command? It already has mechanism waiting for full VM start, as opposed to the "run" option in qubes manager

**Comment by ij1** [comment]
Indeed, now that I try many times it doesn't seem to occur with qvm-run AFAICT. But then I think I've seen the wrong xterm colors to occur when launching something from menu which uses qvm-run (but then 1% of me is telling me I might have used qube manager run those times so I might just remember things wrong/mix up).

**Comment by marmarek** [comment]
If you could find a case where `qvm-run` has similar issue (other than `qvm-run --no-gui` which explicitly disable waiting for full GUI session), then I think it would be a significant progress towards solving #3533. I've tried many times and haven't found it yet...

**Comment by ij1** [comment]
Ok thanks, I'll keep that mind if I'm lucky enough to get the wrong colors when using menu.

**Comment by DemiMarie** [comment]
@marmarek I suspect this is a race condition in `qubes.WaitForSession`.  I don’t see any obvious bugs, but two things seem suspicious:

* using `/tmp` instead of `$XDG_RUNTIME_DIR` to store the env file
* relying on sequentially consistent filesystem behavior

Could the problem be missing synchronization somewhere?
