### ISSUE TITLE
Problems with update dom0

### ISSUE THREAD

**Issue by n0sign4l** [QubesOS/qubes-issues#4977]
**Qubes OS version**
Version is the 4.0

**Affected component(s) or functionality**
qubes update in dom0

**Brief summary**
Cannot update the dom0

**To Reproduce**
_Steps to reproduce the behavior:_
_1. update
**Expected behavior**
should update

**Actual behavior**
doesn't update

**Additional context**
This is the error I get:
```
sudo qubes-dom0-update
Using sys-whonix as UpdateVM to download updates for Dom0; this may take some time...
https://mirrors.rit.edu/fedora/archive/fedora/linux/releases/25/Everything/x86_64/os/repodata/9a2c1b0163804ec57bd22229f1729d58e976942454691326da85ffd88a2431f9-primary.sqlite.bz2: [Errno 14] curl#6 - "Could not resolve host: mirrors.rit.edu"
Trying other mirror.
http://mirrors.kernel.org/fedora-buffet/archive/fedora/linux/releases/25/Everything/x86_64/os/repodata/9a2c1b0163804ec57bd22229f1729d58e976942454691326da85ffd88a2431f9-primary.sqlite.bz2: [Errno 14] curl#6 - "Could not resolve host: mirrors.kernel.org"
Trying other mirror.
http://mirror.math.princeton.edu/pub/fedora-archive/fedora/linux/releases/25/Everything/x86_64/os/repodata/9a2c1b0163804ec57bd22229f1729d58e976942454691326da85ffd88a2431f9-primary.sqlite.bz2: [Errno 14] curl#6 - "Could not resolve host: mirror.math.princeton.edu"
Trying other mirror.
https://pubmirror1.math.uh.edu/fedora-buffet/archive/fedora/linux/releases/25/Everything/x86_64/os/repodata/9a2c1b0163804ec57bd22229f1729d58e976942454691326da85ffd88a2431f9-primary.sqlite.bz2: [Errno 14] curl#6 - "Could not resolve host: pubmirror1.math.uh.edu"
Trying other mirror.
https://pubmirror2.math.uh.edu/fedora-buffet/archive/fedora/linux/releases/25/Everything/x86_64/os/repodata/9a2c1b0163804ec57bd22229f1729d58e976942454691326da85ffd88a2431f9-primary.sqlite.bz2: [Errno 14] curl#6 - "Could not resolve host: pubmirror2.math.uh.edu"
Trying other mirror.
https://dl.fedoraproject.org/pub/archive/fedora/linux/releases/25/Everything/x86_64/os/repodata/9a2c1b0163804ec57bd22229f1729d58e976942454691326da85ffd88a2431f9-primary.sqlite.bz2: [Errno 14] curl#6 - "Could not resolve host: dl.fedoraproject.org"
Trying other mirror.
Error: failure: repodata/9a2c1b0163804ec57bd22229f1729d58e976942454691326da85ffd88a2431f9-primary.sqlite.bz2 from fedora: [Errno 256] No more mirrors to try.
```

I'm sure that the Internet connection isworking because I'm abke to update all the VMs

**Comment by lunarthegrey** [comment]
Can you `ping` or `dig` those mirrors from sys-whonix? If you're not using sys-whonix for your other VMs that might explain how the issue only shows up when using sys-whonix (as an update VM or network VM). I'd check the status of Tor on sys-whonix and figure out what the issue is there.

**Comment by adrelanos** [comment]
Try a general connectivity test in sys-whonix:

    whonixcheck --leak-tests

Should there be any issues with that, see this chapter (just now written):
https://www.whonix.org/wiki/Tor#Connectivity_Troubleshooting

If that works, try to visit that URLs with Tor Browser from Whonix-Workstation.

> Can you `ping` or `dig` those mirrors from sys-whonix?

That won't work anyhow, see:
https://www.whonix.org/wiki/Whonix-Workstation_Firewall#ping
