### ISSUE TITLE
Qubes Device Manager No Longer Shows Block Devices

### ISSUE THREAD

**Issue by Rspigler** [QubesOS/qubes-issues#4978]
**Qubes OS version**
4.0.1

**Affected component(s) or functionality**
Qubes Device Manager (specifically reading a block device)

**Brief summary**
I have always used the same portable HDD to backup my Qubes OS.  My last backup was last weekend.  Currently, for some reason, my Qubes Device Manager does not list any block device or USB drive (only the dom0:mic).  However, my HDD does power on when plugged in.

In dom0, `qvm-usb` returns no results.
In sys-sub, `lsusb` returns no additional results than the (Bus 001 Device 002) and (Bus 001 Device 001) that it always returns.

Yes, I have tried restarting my machine :)

**Expected behavior**
Qubes Device Manager should list block devices and USB drives

**Actual behavior**
Only shows dom0 microphone

**Additional context**
All template VMs are up to date, machine has been restarted and problem still stands.
Hardware is Purism Librem v3

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
https://www.qubes-os.org/doc/usb-devices/

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
https://github.com/QubesOS/qubes-issues/issues/4915

I followed their solution:

In dom0:

`sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing --action=upgrade qubes-desktop-linux-manger`
`killall qui-devices`

But the problem persists

**Comment by marmarek** [comment]
> In sys-sub, `lsusb` returns no additional results than the (Bus 001 Device 002) and (Bus 001 Device 001) that it always returns.

This suggests the problem is not with device manager, but with usb drivers.
Check kernel messages in sys-usb using `sudo dmesg` command and look for errors related to usb controllers, especially about `xhci` or `ehci` drivers.

**Comment by Rspigler** [comment]
This is the only error I see:

> piix4_smbus 0000:00:01.3: SMBus Host Controller not enabled!

**Comment by Rspigler** [comment]
God, I feel stupid.

Recently, I had to restore a backup, so this sys-usb is the restored version (on restore, named sys-usb1), and not the default (which I then deleted), and therefore doesn't have the USB controller connected.

However, I get this error when trying to connect:

> ERROR: Devices tab: Got empty response from qubesd. See journalctl in dom0 for details.

Journalctl returns these errors

> Fail to find module 'uinput'
Failed to start Load Kernel Modules
xenstored:  TDB: tdb_open_ex: could not open faile /var

**Comment by marmarek** [comment]
In sys-usb settings, there is an option to workaround this specific problem. See the button at the bottom of devices tab. Alternatively, you can use command line version: https://www.qubes-os.org/faq/#i-created-a-usbvm-and-assigned-usb-controllers-to-it-now-the-usbvm-wont-boot

**Comment by Rspigler** [comment]
Thank you!
