### ISSUE TITLE
Debian Buster Thunar - Failed to run preferred application

### ISSUE THREAD

**Issue by TNTBOMBOM** [QubesOS/qubes-issues#4981]
**Qubes OS version**
R4.0.1
**Affected component(s) or functionality**
Debian Buster 
**To Reproduce**
Just upgrade/use buster 
**Expected behavior**
should work 
**Actual behavior**
not working 
**Screenshots**

![af4a7fccd697e38b507d129b67d002701781ac2a](https://user-images.githubusercontent.com/11895339/56315190-9b24dc80-6146-11e9-966e-f16df5c6af9c.png)

**Comment by unman** [comment]
@TNTBOMBOM I've tried installing thunar in Debian-9 and upgrading, and upgrading and then installing thunar, and in both cases it just works.
Can you put some detail in the "To reproduce" section, and explain *how* you are trying to start thunar? The screenshot doesn't help.

**Comment by TNTBOMBOM** [comment]
go to "Launch Preferred Applications" called as well in the shortcuts "File Manager" (there are duplicates naming of the shortcuts, one for modifying the File Manager preferences and one which shows that error)

**Comment by unman** [comment]
On Thu, Apr 18, 2019 at 10:48:45AM -0700, TNT BOM BOM wrote:
> go to "Launch Preferred Applications" called as well in the shortcuts "File Manager" (there are duplicates naming of the shortcuts, one for modifying the File Manager preferences and one which shows that error)
> 

This really isnt a Qubes issue.
And buster is *still* in testing.

The missing file is installed as part of libexo-1-0 package: install
that package. (If you install thunar in stretch and then upgrade you'll
have it, I think)

I'm puzzled as to why you dont use the helpfully named "Thunar file
manager" shortcut.

**Comment by TNTBOMBOM** [comment]
Thanks @unman , issue resolved with installing that package. Appreciated!

@andrewdavidwong feel free to close this issue as resolved.

**Comment by andrewdavidwong** [comment]
> This really isnt a Qubes issue.

Closing as "not our bug." If you believe this is a mistake, please leave a comment, and we'll be happy to take another look. Thank you.
