### ISSUE TITLE
Use dm-crypt to encrypt swap devices and non-persistent volumes

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#4990]
**Qubes OS version (if applicable)**
`Qubes release 4.0 (R4.0)`

**Affected component(s) or functionality (if applicable)**
Storage backend

**Brief summary**
Whenever a non-persistent block device is created, we should use `dm-crypt` to encrypt the data, with the encryption key taken from `/dev/urandom`.  Before this, we should call `getentropy` to ensure that we have enough entropy.

`/etc/crypttab` has builtin support for this, so this should not be too difficult.

**Additional context**
This solves #1293, among others.  Technically, it is a duplicate, but this task provides a clear path to implementation.

**Comment by andrewdavidwong** [comment]
> This solves #1293, among others. Technically, it is a duplicate,

Please do not file duplicate issues! Comment on #1293 instead.

> but this task provides a clear path to implementation.

That does not merit a separate issue. It's _exactly_ the sort of thing that should be a comment on the issue that it solves. The solution to an issue should be posted on that issue.
