### ISSUE TITLE
Duplicate "reject" entry in nftables 

### ISSUE THREAD

**Issue by unman** [QubesOS/qubes-issues#4991]
**Qubes OS version**
_The version of Qubes OS you're using (e.g., `R4.0`), available via the command `cat /etc/qubes-release` in a dom0 terminal._
R4.0
**Affected component(s) or functionality**
_The component or functionality of Qubes OS that is not working as expected._
qubes-firewall
**Brief summary**
_A clear and concise summary of the bug._
nftables chains contain superfluous duplicate reject admin-prohibited rules.
**To Reproduce**
_Steps to reproduce the behavior:_
_1. Go to '...'_
_2. Click on '....'_
_3. Scroll down to '....'_
_4. See error_

Run qubes with "Deny except" reject rules.
Examine chains in firewall.

**Expected behavior**
_A clear and concise description of what you expected to happen._
nftables chains contain single catch-all reject rule at end.

**Actual behavior**
_What actually happened (instead of what you expected to happen)._

Chains contain second identical reject rule.

**Screenshots**
_If applicable, add screenshots to help explain your problem._

**Additional context**
_Add any other context about the problem here._
Entirely superficial and low priority issue.
**Solutions you've tried**
_If applicable, any solutions or workarounds you've already tried._

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
_A list of links to the Qubes documentation (or other relevant software documentation) pages you have already consulted._

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
_A list of links to other bug reports, feature requests, or tasks in the qubes-issues tracker. Do not describe any other unreported bugs, features, or tasks here._

**Comment by DemiMarie** [comment]
Not an issue in R4.1.  Maybe not worth backporting to R4.0.

**Comment by andrewdavidwong** [comment]
> Not an issue in R4.1. Maybe not worth backporting to R4.0.

Ok, but that's not a reason to change the issue type from "bug" to "task." It's still a bug in 4.0. It may end up being closed as `won't fix` for 4.0 (because already fixed in 4.1), but that doesn't mean it was never a bug in 4.0.

**Comment by TNTBOMBOM** [comment]
Still the case? any new appearing to this behavior? (specially in Qubes 4.2)

**Comment by andrewdavidwong** [comment]
If anyone is still experiencing this problem on Qubes 4.1 or higher, please leave a comment here, and we'll be happy to reopen this.
