### ISSUE TITLE
After cloning or renaming a qube, the devices are missing from the new qube

### ISSUE THREAD

**Issue by SomeNewQubesFan** [QubesOS/qubes-issues#4992]
**Qubes OS version**

Qubes release 4.0 (R4.0)
Although I thought it was 4.0.1 specifically

**Affected component(s) or functionality**
The Qubes Manager - Copying/Renaming Templates

**Brief summary**
Cloning qubes and Renaming qubes do not include any "devices" that were part of the originating qube

**To Reproduce**
1. Install Qubes
2. Boot Qubes
3. Run Qube Manager
4. Right click a VM containing at least one item in the "devices" tab of Qube Settings (sys-net is a good example)
5. Select Qube Settings
6. Choose "Clone qube" or "Rename"
7. Enter a name for the VM
8. Right click on the qube with the name from step 7
9. Select Qube Settings
10. Select "Devices" Tab

**Expected behavior**
Expected to see the devices from the device in step 4

**Actual behavior**
Devices is empty

**Solutions you've tried**
Adding the device manually, it worked

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
This is pretty similar but it is different 
https://github.com/QubesOS/qubes-issues/issues/4978

**Comment by unman** [comment]
I wonder if this is misplaced expectation?

Since PCI devices cant be allocated  to two qubes at the same time by default - you need to enable no-strict-reset to get this behaviour - one would not expect a cloned qube to have the same devices attached.

If I clone sys-net so that I can have a separate wifi sys-net I dont want the *same* devices attached.
I think the current behaviour is best for cloning.

**Comment by marmarek** [comment]
Even if that would be expected behavior of pure clone, definitely it is _not_ an expected behavior of rename. But even on clone, it should preserve all the configuration, including devices.

**Comment by unman** [comment]
@marmarek Completely agree on rename, which is why I referred only to cloning.

If cloning is to preserve configuration _including devices_, then how to overcome strict reset issue? Do we want potential for devices attached to multiple qubes by default? Or am I missing something?

**Comment by marmarek** [comment]
You can't start such domains simultaneously. But you can have them existing at the same time.

**Comment by brendanhoar** [comment]
@marmarta - consider re-opening this...

Using Qubes 4.0, w/ testing repo.  

After updating to testing yesterday, an existing script is no longer working. The script performs a qvm-clone command, and a pci device\* permanently associated to the source VM is currently not installed in the system. The source VM starts fine. 

As is, qvm-clone now fails with: "qvm-clone: error: Invalid PCI device: 05_00.0"

Presumably it should clone the VM with the device association, even if the device does not currently exist in the system. Alternately, if there is some lower-level Xen limit, it should clone without the device. Or add a qvm-clone flag to alter default behavior if one might think the user might need both cases and both can be handled.

Thanks,
Brendan

\* the device in particular is an expresscard usb 3.0 controller, which must be attached to the system at power-on to be recognized. i install it before power up when needed.

**Comment by marmarek** [comment]
> The source VM starts fine.

I've just tried similar situation and got:
```
$ qvm-pci ls testvm
BACKEND:DEVID  DESCRIPTION     USED BY
dom0:09_00.0   Unknown device  untrusted
$ qvm-start testvm
PCI device dom0:09_00.0 does not exist
```

Anyway, you can use `qvm-clone --ignore-errors` to not abort the close.

**Comment by brendanhoar** [comment]
Huh, ok...then, I made an assumption about the source still working, while clearly I was benefiting from the original defect! :) 

Well, now I have my solution and we can keep this closed, I suppose.

Thanks @marmarek and @marmarta!
