### ISSUE TITLE
GUI artefact from qui-disk-space in KDE

### ISSUE THREAD

**Issue by unman** [QubesOS/qubes-issues#4994]
**Qubes OS version**

R4.0

**Affected component(s) or functionality**

Display
qui-disk-space

**Brief summary**

The top Left hand corner of display has Black square overlying what should be Desktop control.
Clicking on it produces the disk space information available from disk-space icon in panel.
Killing qui-disk-space removes black square.

**To Reproduce**

Run KDE

**Expected behavior**

**Actual behavior**

**Screenshots**

**Additional context**

With panel at top of screen, the artefact does not appear.
Happens most of time after restart.

**Solutions you've tried**

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

**Comment by backamblock** [comment]
I can confirm this and some other issues with kde in qubes 4.0.1 (downloaded yesterday)

Thinkpad e590 i7 8gb
This is on a fresh uefi install, no kernel/efi settings changed, everything is fully updated and runs smoothly.

So i install the kde as described in the documentation
Then i make my settings, customize kde, etc.
Problems then started when first attaching my second monitor.

-"No battery" when checking the power panel
-The black square in the top left corner
-"Show all windows" when mouse to corner does not do anything (changed corners to confirm)
-Taskbar is not on the edge of the screen but has some -5mm spacing when dragging it to another side
-Qubes networking icon missing, but clicking the space on the bar still opens settings, so it is there
-menus from taskbar (network,qubes,sysusb,...) Do not auto hide but stay visible until clicking the icon again

All these happen randomly, single and mixed and come and go as they please between reboots.

Reapplying a default theme does not help.
Is there anything i miss here or is kde just abandoned and not compatible with 4.0.1?

**Comment by andrewdavidwong** [comment]
> Is there anything i miss here or is kde just abandoned and not compatible with 4.0.1?

It's not abandoned, but the devs are quite busy and haven't had time to address these KDE issues, especially since it's no longer the default DE in Qubes. Community patches would be very much welcome.

**Comment by backamblock** [comment]
The missing battery issue solved itself after a few reboots more.
And the thing with the black square/tray menus in the corner, just click to open the menus of each tray icon once after reboot :)

Sorry i can not help more, i have no clue about programming outside of gui drag and drop :D

**Comment by unman** [comment]
> And the thing with the black square/tray menus in the corner, just click to open the menus of each tray icon once after reboot :)

I am aware of this. Unfortunately, the artefact reappears spontaneously during use.

**Comment by tasket** [comment]
I don't notice the black square or the "taskbar not on edge" issue, but this may be because I always position my panel vertically.

The domU systray "menus... do not autohide" is an old pitfall*, and I thought this was independent of which DE was running. If possible, it would be good to detect a focus transition away from the domU menu, and send a signal such as escape-key to it.

* Note: This should be a separate issue as there are usage scenarios where it can mess up the UI. For example: User mouses over to the sys-net NM icon, but another VM is starting and the transient NM icon briefly appears as the user tries to click on the sys-net icon. The result is that the NM menu for the other VM never disappears until the appVM shuts down.
