### ISSUE TITLE
Configuration dialog does not appear after installing to non LVM storage

### ISSUE THREAD

**Issue by unman** [QubesOS/qubes-issues#4996]
**Qubes OS version**
_The version of Qubes OS you're using (e.g., `R4.0`), available via the command `cat /etc/qubes-release` in a dom0 terminal._
R4.0.1
**Affected component(s) or functionality**
_The component or functionality of Qubes OS that is not working as expected._
Installer
**Brief summary**
_A clear and concise summary of the bug._
After installing without LVM (thick or thin), no configuration options appear after reboot.
**To Reproduce**
_Steps to reproduce the behavior:_
_1. Go to '...'_
_2. Click on '....'_
_3. Scroll down to '....'_
_4. See error_
1. Install Qubes selecting manual disk configuration
2. Configure without LVM
3. Complete installation
 
**Expected behavior**
_A clear and concise description of what you expected to happen._
On reboot, configuration dialog should appear to enable selection of qube options.
**Actual behavior**
_What actually happened (instead of what you expected to happen)._
No configuration dialog appears
**Screenshots**
_If applicable, add screenshots to help explain your problem._

**Additional context**
_Add any other context about the problem here._

This worked fine in 4.0 and rc of 4.0.1.
If it's now a requirement to use LVM I *may* have missed this. Easily done.

Although dnf shows that templates are installed, it isnt possible to remove the Whonix templates - error message in postproc handling for package - no Qube of that name exists.

**Solutions you've tried**
_If applicable, any solutions or workarounds you've already tried._

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
_A list of links to the Qubes documentation (or other relevant software documentation) pages you have already consulted._

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
_A list of links to other bug reports, feature requests, or tasks in the qubes-issues tracker. Do not describe any other unreported bugs, features, or tasks here._

**Comment by marmarek** [comment]
Non-LVM configuration definitely is supported. We also have automated test for some such configurations, for example btrfs: https://openqa.qubes-os.org/tests/1501

I guess, `initial-setup` service failed. See logs about that service.

**Comment by marmarek** [comment]
BTW you can replace instructions in the issue template when you fill it, it will be easier to read.

**Comment by unman** [comment]
I managed to submit a report without any content - dont know how. Edited in the detail later.

I'll try another install and check the service log later.
