### ISSUE TITLE
Timezone does not support timezone declarations of 3 levels

### ISSUE THREAD

**Issue by t4777sd** [QubesOS/qubes-issues#5001]
**Qubes OS version**
4.0

**Affected component(s) or functionality**
Time zone related components specifically qubes-early-vm-config.sh

**Brief summary**
This is actually discussed here: https://groups.google.com/forum/#!msg/qubes-users/VIFIKJFuJB8/AsaXRt83AgAJ

I came across this trying to solve a time issue. Seeing as how this was posted a long time ago it does not seem solved. And, I searched the bugs and could not find something specifically about this.

As per the thread, timezones that are 3 layers deep such as "America/Argentina/Cordoba" get passed as "Argentina/Cordoba", so the first level is removed. The end result is that the tests in qubes-early-vm-config.sh cannot find the timezone declaration and no timezone is set.

**To Reproduce**
_1. set time zone in dom0 to America/Argentina/Cordoba
_2. In VM run qubesdb-read /qubes-timezone you will see that the first level is removed

**Expected behavior**
The time zone should not remove the first level, so that it works correctly

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
_A list of links to the Qubes documentation (or other relevant software documentation) pages you have already consulted._

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
_A list of links to other bug reports, feature requests, or tasks in the qubes-issues tracker. Do not describe any other unreported bugs, features, or tasks here._

**Comment by t4777sd** [comment]
I can give you the solution to this.

Here is what is happening. qubes/vm/qubesvm.py calls get_timezone() on line 2068 and it is that which has the error in it. Later on, this is used to set the qubesdb value for timezone. I personally wish that qubes looked at the domain prefs for the time zone and set the qubesdb with that. Only falling back to the dom0 timezone if nothing was set.

Anyways, **qubes/utils.py**: **42** is the root cause of the issue:

return '/'.join(os.readlink('/etc/localtime').split('/'[-2:])

You can see that it is getting the symbolic link path and then only taking the last two directories. Thus, it will error for any timezone that is 1 level deep or >=3 levels deep. Which is a LOT of timezones (the majority).

To resolve this you will want to replace that line with the following code, which will work in any normal case especially considering the dom0 environment is guaranteed and will definitely work in more cases than the current code.:

```
		link = os.path.realpath(os.readlink('/etc/localtime').lstrip('.'))
		if link.find('/usr/share/zoneinfo/') == 0:
			link = link.replace('/usr/share/zoneinfo/', '')
		else: link = '/'.join(link.split('/')[-2:])
		return link
```

**Comment by ejose19** [comment]
This was already fixed in https://github.com/QubesOS/qubes-core-admin/pull/276
