### ISSUE TITLE
USB Stick doesn't boot on AMD Threadripper

### ISSUE THREAD

**Issue by christoph-pieper** [QubesOS/qubes-issues#5002]
**Qubes OS version**
4.0.1

**Affected component(s) or functionality**
Live ISO Image

**Brief summary**
Can't boot from USB Stick to use oder install

**To Reproduce**
1. Write Qubes-R4.0.1-x86_64.iso on an USB Stick with Rufus (UEFI / DD Mode)

**Expected behavior**
The live system to show up.

**Actual behavior**
I see a console output (see screenshot) then a black screen (remains there)

**Screenshots**
![fr_5903](https://user-images.githubusercontent.com/29834530/56862285-9e6f6200-69a9-11e9-82d4-50638403ec8d.jpg)

**Additional context**
- CPU: AMD Threadripper 2950

**Solutions you've tried**
- Try non UEFI
- Try not DD to write on stick

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
https://www.qubes-os.org/doc/installation-guide/#copying-the-iso-onto-the-installation-medium

**Comment by KleinTong** [comment]
same black screen problem!
i use 1950x and msi creation.

**Comment by Kivilahti** [comment]
I have the same but a laptop, Asus G74SX

I made DD version and did not boot.  I made ISO version and modified config to see different results.

First error I found was related to smt:
****
"Booted on L1TF-vulnerable hardware with SMT/Hyperthreading"
"enabled, Please assess your configuration and choose an"
"explicit 'smt=<bool>' setting. See XSA-273."
****
BIOS does not have an option to turn smt off, so I set to config

Still no boot and modified and tested different variations, came out with this.

[qubes-verbose]
options=console=vga efi=attr=uc smt=1
#noexitboot=1
#mapbs=1
kernel=vmlinuz inst.stage2=hd:LABEL=Qubes-R4.0.1-x86_64 i915.alpha_support=1
ramdisk=initrd.img

Then it suggested to take a copy from the log and include to the bug report.

Happened to find this USB stick bug report but hard to say if related.  Could be.
[rdsosreport.txt](https://github.com/QubesOS/qubes-issues/files/3355680/rdsosreport.txt)

**Comment by Kivilahti** [comment]
As there was no answer I decided to look in to this today myself.

I made the USB stick with Rufus and in ISO mode LABEL was not matching with the BOOTX64.cfg. I fixed this and it started to boot.  Also I am using the previous config I mentioned.

Simply...
kernel=vmlinuz inst.stage2=hd:LABEL=QUBES-R4 i915.alpha_support=1
On windows side make sure it is the same.  I hope this will fix it for the most.

I tho was informed after that I a missing IOMMU/VT-d/AMD-Vi.  *sob*

**Comment by marmarek** [comment]
> I tho was informed after that I a missing IOMMU/VT-d/AMD-Vi. _sob_

In some cases it is disabled in BIOS, but I think [in your case it is indeed missing](https://ark.intel.com/content/www/us/en/ark/products/52219/intel-core-i7-2630qm-processor-6m-cache-up-to-2-90-ghz.html) (if I get correct CPU model).

**Comment by marmarek** [comment]
>  kernel=vmlinuz inst.stage2=hd:LABEL=QUBES-R4 i915.alpha_support=1

That's weird. Unmodified ISO image have the label including full version. If you add `rd.live.check` option to vmlinuz, it will run media validation at boot. It will obviously fail, since you've modified it, but it's interesting where it will fail. Your modifications should be near 4.5%-5%. If it fails earlier, then something else was modified too.

**Comment by Kivilahti** [comment]
I verified the ISO after download.

So..
1. Rufus to "burn" the ISO on USB stick.
2. Edited BOOTX64.cfg on the USB stick as mentioned before.
3. All booted fine until IOMMU.

Windows also show a label that is cut. Cannot now remember exactly what I did but in emergency console noticed that the labels did not match.

No other changes has been done, at least by me.

...

I have 2 older laptops and as unlucky as you can be both have the same CPU.  It is around 15 years when I was talking with a friend that there should be OS that can do what Qubes OS can do today. Few days ago I noticed Qubes and the history made me actually interested from the project. It is also rare these days I get interested from any project so good job gents.  Sad that the HW turned against me.

**Comment by ChristophPie** [comment]
So any news for this? I'd really liked to test Qubes on my TR...
Greetings

**Comment by 0spinboson** [comment]
> So any news for this? I'd really liked to test Qubes on my TR...
> Greetings

you've enabled IOMMU&SVM in the bios and it still doesn't boot?
