### ISSUE TITLE
Blockchain.info usage in proof of freshness is failing

### ISSUE THREAD

**Issue by JeremyRand** [QubesOS/qubes-issues#5006]
**Qubes OS version**
N/A since bug is in qubes-secpack, not in Qubes OS.

**Affected component(s) or functionality**
Proof of freshness in qubes-secpack

**Brief summary**
The blockchain.info API now only includes 10 blocks (0-indexed), so the proof of freshness script's attempt to get the 11th block (index 10) fails.

**To Reproduce**
_Steps to reproduce the behavior:_
1. `curl -s https://blockchain.info/blocks/?format=json | python3 -c "import sys, json; print(json.load(sys.stdin)['blocks'][10]['hash'])"`  (This is copied from https://github.com/QubesOS/qubes-secpack/blob/6f76ce7088c251759256cdb7611fd97088e08133/utils/proof_of_freshness_generator.sh#L17 )

**Expected behavior**
A Bitcoin block hash should be printed.

**Actual behavior**
~~~
Traceback (most recent call last):
  File "<string>", line 1, in <module>
IndexError: list index out of range
~~~

**Screenshots**
N/A

**Additional context**
N/A

**Solutions you've tried**
Switching to index 9 (the 10th block) fixes the error, although this may be non-ideal since more recent blocks are at higher risk of blockchain reorg.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
N/A

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
https://github.com/QubesOS/qubes-issues/issues/2685

**Comment by marmarek** [comment]
Thanks for the info, I'll fix the script before publishing next canary.
Anyway, for proof verification, you'll need to get 11th block _from the time the proof was made_, not the current time, so that json isn't useful for verification.

**Comment by JeremyRand** [comment]
> Anyway, for proof verification, you'll need to get 11th block from the time the proof was made, not the current time, so that json isn't useful for verification.

Yes, I know.  (I develop a free software project that borrows your script for our canaries, so I noticed the issue while trying to create a new canary.)

**Comment by marmarek** [comment]
It works again, blockchain.info provides more blocks (again) now.

**Comment by esote** [comment]
@marmarek @JeremyRand `blockchain.info` is again returning fewer blocks. Here's the response from today (right now only 6 blocks):

```
{ 
    "blocks" : [
    {
        "height" : 585751,
        "hash" : "0000000000000000001c8a9a367682a9e89eeb4fb38029381294c9e9d73621c0",
        "time" : 1563327395,
        "main_chain" : true
    },
    
    {
        "height" : 585750,
        "hash" : "0000000000000000001a1b6ac7642b951e673fc60578815b8c38255147a3d338",
        "time" : 1563326898,
        "main_chain" : true
    },
    
    {
        "height" : 585749,
        "hash" : "00000000000000000016c10be818703a4b1bfc657531134208450b091870bd34",
        "time" : 1563326242,
        "main_chain" : true
    },
    
    {
        "height" : 585748,
        "hash" : "0000000000000000001eecafa0a4e0ce86ae45a05c32ac67a64fa7cb168e4382",
        "time" : 1563324826,
        "main_chain" : true
    },
    
    {
        "height" : 585747,
        "hash" : "0000000000000000001c1fc2bfb972feee0e12a39fc8686d9d0620643eda7206",
        "time" : 1563324466,
        "main_chain" : true
    },
    
    {
        "height" : 585746,
        "hash" : "00000000000000000011da0f99fa4cb38036cc3d1a1e1a4dc37d59217279ba58",
        "time" : 1563324373,
        "main_chain" : true
    },
    
    {
        "height" : 585745,
        "hash" : "0000000000000000000021ce00a70239a168770d2a0ef319a8e7538a9228166f",
        "time" : 1563322761,
        "main_chain" : true
    }
    ]
}
```

**Comment by marmarek** [comment]
According to [documentation](https://www.blockchain.com/api/blockchain_api), this API endpoint gives blocks for a given day. This means there may not be enough blocks between 00:00 and 02:00 UTC on average. With the knowledge of the limitation, I think it's ok to leave it as is. The above more reliable method would require some more data processing (I'm specifically worried about feeding output of `getblockcount` back into another call - this would require some sanitization).

**Comment by esote** [comment]
@marmarek To address the sanitization concern: the Python script directly casts the height response to `int`, meaning if the response is non-integral the script crashes (which is good). The integer result is then passed into the URL using string formatting. I don't think this leaves much room for injection.
