### ISSUE TITLE
What is error by Qubes 4.0.1 OS? “Dom0 Error”

### ISSUE THREAD

**Issue by Cvrew** [QubesOS/qubes-issues#5008]
I installed Qubes OS to Lenovo Thinkpad t420, Error displayed. What is it?

And, what should I do to solve this error?

DomO Error

/usr/bin/qym-start, 'sys-firewall] failed: stdout:"

stderr:

"Start failed: invalid argument: could not find capabilities for arch x86-64, see /var/log/libvirt/libxl/libxl-driver.log for details
I got the following error while I was installing Qubes OS. I installed　without worrying about this.

Unsupported Hardware Detected This hardware lacks features required by Qubes OS. Missing features: HVM/VT-x/AMD-V, IOMMU/VT-d/AMD-Vi, HAP/SLAT/EPT/ RVI, Interrupt Remapping. Without these features, Qubes OS will not function normally. It is recommended that only developers and power users proceed with the installation. For more information on supported hardware, please refer to https://www.qubes-os.org/doc/ system-requirements/

**Comment by andrewdavidwong** [comment]
Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this does not appear to be suitable for `qubes-issues`. We ask that you please send this to the `qubes-users` [mailing list](https://www.qubes-os.org/support/) instead. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a brief comment explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.
