### ISSUE TITLE
Qubes Unique Identifiers

### ISSUE THREAD

**Issue by pidifytech** [QubesOS/qubes-issues#5010]
Hi,

I retried your original suggestion despite you hastily closing my original issue.

I created TWO separate whonix-ws. went to browserleaks.com selected Canvas TEST.

both the PNG hash and the canvas fingerprint where identical on two seperate whonix vms.

i think there may be a fundamental flaw in the way I am explaining the issue.

thank you

**Comment by andrewdavidwong** [comment]
It looks like you're referring to an existing issue. Please leave your comment there, even if it is closed, rather than opening a separate issue. Thank you.
