### ISSUE TITLE
Netfront and netback share the same MAC address

### ISSUE THREAD

**Issue by talex5** [QubesOS/qubes-issues#5013]
**Qubes OS version**
4.0

**Affected component(s) or functionality**
HVM AppVMs when using mirage-firewall as their netvm.

**Brief summary**
Qubes appears to configure the same MAC address for both the frontend and backend in XenStore. e.g.

```
[tal@dom0 ~]$ xenstore-ls /local/domain/3/backend/vif/19/0
frontend = "/local/domain/19/device/vif/0"
mac = "00:16:3e:5e:6c:00"
[...]

[tal@dom0 ~]$ xenstore-ls /local/domain/19/device/vif/0
mac = "00:16:3e:5e:6c:00"
```

(at least, I assume that the mac in the backend is supposed to be the MAC for the backend device, but I couldn't find where this is documented)

This works if the client uses just a simple ethernet device, but fails if it connects via a bridge. HVM domains have an associated stub domain running qemu, which provides an emulated network device. The stub domain uses a bridge to connect qemu's interface with eth0, and this doesn't work.

**To Reproduce**
Install an HVM stub domain, e.g. Windows 10. I don't have Windows, so I used OpenBSD and disabled the PV netfront driver instead, so that `ifconfig` shows the `re0` device being used.

Start it as a client of mirage-firewall 0.5. The qube can send traffic to mirage-firewall (e.g. ARP requests show up in the logs) but the responses do not arrive back.

**Expected behavior**
Qubes should allocate a different MAC address for backends. The Linux netback driver defaults to `fe:ff:ff:ff:ff:ff`, and sys-firewall seems to be using this rather than the value in XenStore.

**Additional context**
Original bug report from a Windows 10 user: https://github.com/mirage/qubes-mirage-firewall/issues/56

**Solutions you've tried**
I patched mirage-firewall to force the use of `fe:ff:ff:ff:ff:ff` (https://github.com/mirage/qubes-mirage-firewall/pull/61) and that fixed the problem for me.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
- https://xenbits.xen.org/docs/4.8-testing/misc/xenstore-paths.html (refers to `netif.h`)
- http://xenbits.xen.org/docs/unstable/hypercall/x86_64/include,public,io,netif.h.html (doesn't include the string `mac`)

**Comment by marmarek** [comment]
I don't see documentation either, but it looks like the [libxl toolstack intentionally writes the same mac to both backend and frontent xenstore entries](https://github.com/xen-project/xen/blob/master/tools/libxl/libxl_nic.c#L208-L236), unconditionally. For me it looks like the mac is intended for the frontend and backend should use some other method to obtain its mac - like hardcoded one, as it seems to be the case in Linux. It may be good to ask for clarification on xen-devel...

**Comment by andrewdavidwong** [comment]
If I understand correctly, this appears to be a bug (or question) for an upstream project rather than Qubes, so I'm closing as "not our bug." If this is a mistake, please leave a comment, and we'll be happy to reopen. Thank you.

**Comment by talex5** [comment]
OK. I've made a PR (https://github.com/mirage/mirage-net-xen/pull/87) so that the Mirage netback driver will use the hard-coded MAC address instead of looking in XenStore.
