### ISSUE TITLE
qubes-change-keyboard-layout is no longer working after being migrated to Python3

### ISSUE THREAD

**Issue by iprid23** [QubesOS/qubes-issues#5015]
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
qubes-gui-agent-linux component
qubes-change-keyboard-layout command

**Brief summary**
After this commit:
https://github.com/QubesOS/qubes-gui-agent-linux/commit/ff9edf4d6a9a5f6de514b67c7d9f7ac106aa3d9b
The qubes-change-keyboard-layout is no longer working, I've
experienced two bugs. If the layout list contains non-ascii
characters it simply crashes, but even if there are no such
characters and you try to change the layout, it will not work.

**To Reproduce**
1. Run qubes-change-keyboard-layout in Terminal in Fedora 29 based qube
2. Try to change the layout
3. The change does not take effect.

**Expected behavior**
You should write in the selected layout.

**Actual behavior**
You are stil writing in latin(ascii). Ie. you can't change the layout, though if you open qubes-change-keyboard-layout it will show the new layout is selected.

**Additional context**
If you do the same in a whonix based Qube, the qubes-change-keyboard-layout will crash because the layout file contains non-ascii characters. I guess this should be expected since Python3 strings are unicode by default or so it seems. 

**Solutions you've tried**
I've reverted back to Python2 by reverting this commit
https://github.com/QubesOS/qubes-gui-agent-linux/commit/ff9edf4d6a9a5f6de514b67c7d9f7ac106aa3d9b
and it works fine.

**Comment by mycase** [comment]
**Solutions you've tried**
_The Qube Manager keyboard layout button starts `/usr/bin/python3 /usr/bin/qubes-change-keyboard-layout` in the selected AppVM, which in turn starts `zenity` to ask the user for a choice of keyboard layout. Zenity's return value ends up as a byte-string in the python variable `choice`. The value of this variable is then supposed to be saved to a file which is opened with (the second occurance of) the statement `file = open(vm_layout, 'w')`. In python3 this should be `file = open(vm_layout, 'wb')` which solved the issue for me._

**Comment by iprid23** [comment]
@mycase
So I guess the issue is really with the Python3 strings being unicode by default. Your fix seems like it would work. Will write here when I test it.

**Comment by iprid23** [comment]
@mycase I've tested your proposed fix and it works. Seems like we really need wb to write those multibyte characters.

CC: @marmarek
