### ISSUE TITLE
System spontaneously reboots after being idle for at least 60 minutes (Lenovo P52/nouveau)

### ISSUE THREAD

**Issue by noseshimself** [QubesOS/qubes-issues#5018]
**Qubes OS version**
Qubes OS version
R4.0, kernel-latest
**Affected component(s) or functionality**
X11, nouveau
**Brief summary**
Idle system reboots after some time.
**To Reproduce**
Boot Qubes.
Attach a second display via DisplayPort.
Work with the system.
Call it a day and go to bed.
Return next morning.
**Expected behavior**
Xscreensaver was activated and waiting for your login password.
**Actual behavior**
The bootloader is greeting you with its question for the disk encryption password.
**Additional context**
I tried it for five consecutive days. 5 reboots. I removed the display again and the system remains stable.

**Comment by limnick** [comment]
I don't use an external display with my laptop (different brand as well) and I recently started seeing similar random reboot behavior after an update. It seems to mostly reboot when idle, and I haven't seen anything telling in any logs so far.
