### ISSUE TITLE
Qubes stubdomain DHCP server returns wrong gateway IP

### ISSUE THREAD

**Issue by talex5** [QubesOS/qubes-issues#5022]
**Qubes OS version**
4.0

**Affected component(s) or functionality**
HVM qubes using DHCP.

**Brief summary**
When an HVM qube uses DHCP to get its network configuration:

1. The HVM qube makes a DHCP request over its emulated network device.
2. The DHCP server in the stub domain replies, saying the router is 10.137.0.1 (see https://github.com/QubesOS/qubes-vmm-xen-stubdom-linux/blob/master/rootfs/init#L37).
3. The Qube tries to use this and fails, because that's not the IP address of the firewall.

However, this *does* work with sys-firewall, because it uses [proxy_arp](https://github.com/QubesOS/qubes-core-agent-linux/blob/e3db225aab74c26ff12d4a4e544cc5d60e1effd7/network/vif-route-qubes#L68). It therefore responds to the ARP request for 10.137.0.1 with its own MAC address. It seems to respond to any ARP request, e.g.

```
[user@test ~]$ sudo route add 8.8.8.8 eth0

[user@test ~]$ ping -c1 8.8.8.8
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=122 time=614 ms

[user@test ~]$ sudo arp -n 8.8.8.8
Address                  HWtype  HWaddress           Flags Mask            Iface
8.8.8.8                  ether   fe:ff:ff:ff:ff:ff   C                     eth0
```

**To Reproduce**
1. Configure an HVM domain to use the emulated network device (I tested with OpenBSD) and DHCP.
2. Observe that it gets a default gateway of 10.137.0.1, which is not the address of its firewall.

**Expected behavior**
The DHCP server should respond with the address of the firewall.

**Actual behavior**
The DHCP server responds with 10.137.0.1.

**Additional context**
Original issue from a Windows 10 user: https://github.com/mirage/qubes-mirage-firewall/issues/56

In https://groups.google.com/d/msg/qubes-devel/2GzoiAIIG1c/FG9l8A6BAQAJ Marek said:

> Oh, you've found a bug here. It was this way in R3.2, but not in R4.0 anymore.

**Solutions you've tried**
Replacing the IP address in the routing table with the correct one allows it to work.

**Comment by marmarek** [comment]
Backporting the fix to R4.0 is complex, because involve a slight API change (core-admin <-> stubdomain). 
Since in practice this applies to mirage-firewall + HVM only, the impact isn't big.
