### ISSUE TITLE
Mozilla apps unresponsive across whole OS if used before CPU thrashing stops

### ISSUE THREAD

**Issue by farrilis** [QubesOS/qubes-issues#5027]
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
Mozilla apps Thunderbird, Firefox or Tor Browser in Debian 9 standard/Whonix 14 appvms

**Brief summary**
If a whonix 14 DispVM Tor Browser instance is not given several minutes to finish start scripts, then subsequent instances of _ANY_ Mozilla app in _ANY_ other appvm/dispvm becomes unresponsive/unusable (the tor browser dispVM that was not left to finish CPU activity behaves the same way, unresponsive/unusable)

**To Reproduce**

1. open ```xentop```
2. open Tor Browser dispvm
3. do anything to make the Tor Browser instance interrupt it's scripts - resize window, click on UI buttons
4. now try to use Tbird/Ffox/TBrowser in any newly booted VM, the same unresponsive/unusable delays with UI interaction manifest

**Expected behavior**
Smooth, responsive functioning of any Mozilla app in any VM

**Actual behavior**
Unresponsive behaviour in Mozilla apps that persists until reboot or an unknown (1 hour+) amount of time

**Additional context**
All previously booted VMs continue to be responsive. All Mozilla apps in VMs booted after triggering the condition exhibit the unresponsiveness issue, but Xterm seems to work fine in those VMs

rebooting entire machine resets the behaviour, but waiting some unknown amount of hours without rebooting (shutting unresponsive VMs, + letting existing responsive VMs remain) and the issue in new VMs disappears 

The fact that this persists across all VM instances after the triggering of the bug suggests dom0 plays a part, ```xentop``` shows very high CPU for both dom0 and VMs using Mozilla apps until the Mozilla app or it's VM is shutdown

**Solutions you've tried**
* ```fstrim``` as per Qubes docs
* deleting old .lvm files from /etc/lvm/archive
* setting ```extensions.update.enabled```, ```extensions.torbutton.startup``` and ```services.sync.prefs.sync.extensions.update.enabled``` to 'false' in whonix-ws template for dispVM that triggers the condition

**Comment by farrilis** [comment]
> now try to use Tbird/Ffox/TBrowser in any newly booted VM, the same unresponsive/unusable delays with  > UI interaction manifest

this is incorrect

Only instances of Mozilla apps that were open before triggering this state continue to respond normally. Even in VMs that were open before the trigger, opening new Mozilla apps exhibit the unresponsive state and high CPU usage

**Comment by unman** [comment]
I'm trying to get clear about what you mean here, as I dont seem to be able to reproduce with a stock Debian-9 template. 
Can you give some detail about your hardware, and also explain:
1. Whether you have reproduced this in a Debian-9 template based qube.
2. How you create a "Tor Browser dispvm" - is this just a disposableVM with TBB installed? Or something else?
3. Which window and UI buttons you are using to "interrupt its scripts" - do you mean resizing the TBB config screen? 
4. Whether the bug only applies in disposableVMs - can you trigger it in a normal AppVM?
5. Do the effects cross templates? I mean, if you trigger it in a disposableVM based on one template, are the reported effects seen in qubes based on other templates? (You could clone an existing template to test this.)

**Comment by farrilis** [comment]
> Whether you have reproduced this in a Debian-9 template based qube.

I cannot trigger the state using Debian-9, but any FF/Tbird in Debian-9 is affected afterwards

> How you create a "Tor Browser dispvm" - is this just a disposableVM with TBB installed? Or something else?

standard Whonix 14 DispVm, created using the published salt command to install it

> Which window and UI buttons you are using to "interrupt its scripts" - do you mean resizing the TBB config screen?

the actual TBB window itself. I listen till the CPU fan has dissipated, then mouse over UI elements (usually the + symbol that opens a new tab), if the mouse-over responds quickly I proceed to use the TBB in that dispVM instance, else I expect to trigger the state in question. It's hard to say whether this is 100% deterministic, but I do actually wish to use the machine, and this actions seems to avoid triggering the condition

> Whether the bug only applies in disposableVMs - can you trigger it in a normal AppVM?

Cannot trigger from anything but a Whonix 14 dispVM instance. I use Debian-9 dispVM's less frequently than Whonix dispVMs, but frequently enough to make a reasonable assumption that it cannot be done. 

> Do the effects cross templates? I mean, if you trigger it in a disposableVM based on one template, are the reported effects seen in qubes based on other templates? (You could clone an existing template to test this.)

yes.

**Comment by farrilis** [comment]
ok, so it would be useful to eliminate a possible ```fstrim``` issue 


running ```fstrim -av``` in dom0 outputs:

```/boot: 778.3 MiB (816123904 bytes) trimmed
/: 879.6 GiB (944478048256 bytes) trimmed```

This output is produced instantly, whereas IIRC ```fstrim``` should take at least a few minutes, 
suggesting TRIM is not actually happing on the disk itself.

If I reboot and run ```fstrim -av``` again, the same ouput occurs, implying the 
trim command was not performed by the SSD


```dmsetup table``` tells me:

```luks-<redacted UUID>: 0 1951420416 crypt aes-xts-plain64 00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 0 8:2 4096 1 allow_discards```


Relevant files from /etc/ are:

<details> <summary> /etc/default/grub</summary>
GRUB_CMDLINE_LINUX="$GRUB_CMDLINE_LINUX rd.qubes.hide_all_usb"
GRUB_CMDLINE_LINUX="$GRUB_CMDLINE_LINUX rd.luks.options=discard"
GRUB_CMDLINE_XEN_DEFAULT="$GRUB_CMDLINE_XEN_DEFAULT ucode=scan"
GRUB_CMDLINE_XEN_DEFAULT="$GRUB_CMDLINE_XEN_DEFAULT smt=off"
</details>

<details> <summary> /etc/fstab</summary>
/dev/mapper/qubes_dom0-root /                       ext4    defaults,discard,x-systemd.device-timeout=0 1 1
UUID=<redacted UUID> /boot                          ext4    defaults        1 2
/dev/mapper/qubes_dom0-swap swap                    swap    defaults,discard=once,x-systemd.device-timeout=0 0 0
</details>

<details> <summary> /etc/crypttab</summary>
luks-46e38695-9ac4-4b43-b077-320648d769d0 UUID=46e38695-9ac4-4b43-b077-320648d769d0 none discard
</details>


I definitely ran ```grub2-mkconfig -o /boot/grub2/grub.cfg```, then ```dracut -f```, then rebooted

**Comment by farrilis** [comment]
how on earth does one edit these comments?

**Comment by farrilis** [comment]
ok, so it would be useful to eliminate a possible ```fstrim``` issue 


running ```fstrim -av``` in dom0 outputs:

```/boot: 778.3 MiB (816123904 bytes) trimmed```
```/: 879.6 GiB (944478048256 bytes) trimmed```

This output is produced instantly, whereas IIRC ```fstrim``` should take at least a few minutes, 
suggesting TRIM is not actually happening on the disk itself.

If I reboot and run ```fstrim -av``` again, the same ouput occurs, implying the 
trim command was not performed by the SSD


```dmsetup table``` tells me:

```luks-<redacted UUID>: 0 1951420416 crypt aes-xts-plain64 00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 0 8:2 4096 1 allow_discards```


Relevant files from /etc/ are:

<details> <summary> /etc/default/grub</summary>
GRUB_CMDLINE_LINUX="$GRUB_CMDLINE_LINUX rd.qubes.hide_all_usb"
GRUB_CMDLINE_LINUX="$GRUB_CMDLINE_LINUX rd.luks.options=discard"
GRUB_CMDLINE_XEN_DEFAULT="$GRUB_CMDLINE_XEN_DEFAULT ucode=scan"
GRUB_CMDLINE_XEN_DEFAULT="$GRUB_CMDLINE_XEN_DEFAULT smt=off"
</details>

<details> <summary> /etc/fstab</summary>
/dev/mapper/qubes_dom0-root /                       ext4    defaults,discard,x-systemd.device-timeout=0 1 1
UUID=<redacted UUID> /boot                          ext4    defaults        1 2
/dev/mapper/qubes_dom0-swap swap                    swap    defaults,discard=once,x-systemd.device-timeout=0 0 0
</details>

<details> <summary> /etc/crypttab</summary>
luks-<redacted UUID> UUID=<redacted UUID> none discard
</details>

<details> <summary> excerpt from /etc/lvm/lvm.conf </summary>
        # Configuration option devices/issue_discards.
        # Issue discards to PVs that are no longer used by an LV.
        # Discards are sent to an LV's underlying physical volumes when the LV
        # is no longer using the physical volumes' space, e.g. lvremove,
        # lvreduce. Discards inform the storage that a region is no longer
        # used. Storage that supports discards advertise the protocol-specific
        # way discards should be issued by the kernel (TRIM, UNMAP, or
        # WRITE SAME with UNMAP bit set). Not all storage will support or
        # benefit from discards, but SSDs and thinly provisioned LUNs
        # generally do. If enabled, discards will only be issued if both the
        # storage and kernel provide support.
        issue_discards = 1
</details>


I definitely ran ```grub2-mkconfig -o /boot/grub2/grub.cfg```, then ```dracut -f```, then rebooted

**Comment by farrilis** [comment]
Ok I think this was probably just the ```fstrim``` issue

```fstrim -v``` apparently reports the total possible amount of space that could be trimmed (i.e. full disk capacity), not the amoount of blocks that _are_ trimmed, so that confused me initially


I'm pretty convinced that this issue was acually the symptoms of an un-trimmed SDD that I'm using as the system disk for Qubes

**Comment by farrilis** [comment]
and I've discovered that I could've avoided this

I set trim up months ago, and what did I forget? to ```chmod +x``` the cron job file. 

Sorry yet again for the noise
