### ISSUE TITLE
Clones do not retain software

### ISSUE THREAD

**Issue by TungstenCarbideProjectile** [QubesOS/qubes-issues#5029]
Qubes R4.0

Installing software in cloned app vm fed 29

After cloning an app vm, new software installed in clone does not persist through reboot
Clone fedora app vm ( work, personal etc), open software gui install libre office.  Run libre office.  Reboot qube. Libre office is gone
Expected libre office to still be installed to clone app vm

Libre office was not installed in the app vm.

I know the app vms share stuff from template, is that the reason why software did not stay there?  I thought you could install different software to different app vms for different task groups etc.

**Comment by andrewdavidwong** [comment]
Software installed in AppVMs does not persist across AppVM reboots. The software must be installed in a TemplateVM in order to persist:

https://www.qubes-os.org/doc/templates/

Please direct future questions to the `qubes-users` [mailing list](https://www.qubes-os.org/support/).

**Comment by TungstenCarbideProjectile** [comment]
Okay thanks im sorry , why does installed software persist in qubes whonix app vms

**Comment by andrewdavidwong** [comment]
@TungstenCarbideProjectile:
> why does installed software persist in qubes whonix app vms

Please direct future questions to the `qubes-users` [mailing list](https://www.qubes-os.org/support/).
