### ISSUE TITLE
Boot ran out of space during update to kernel(4.14.116-1)

### ISSUE THREAD

**Issue by frozentime345** [QubesOS/qubes-issues#5038]
**Qubes OS version**
_The version of Qubes OS you're using (e.g., `R4.0`), available via the command `cat /etc/qubes-release` in a dom0 terminal._
R4.0

**Affected component(s) or functionality**
_The component or functionality of Qubes OS that is not working as expected._
Boot partition

**Brief summary**
_A clear and concise summary of the bug._
During an update to kernel (4.14.116-1) the boot partition ran out of space and caused the update to fail, I'm using a boot partition that has the uefi fix applied(boot not recognized->separate BOOT folder created). I had to delete initramfs for older kernels in /boot/efi/EFI/BOOT so I'm not sure if this will create future issues. I also had to recreate the xen.cfg section for the new kernel using the old kernel (4.14.103-1) so please let me know if anything should have changed other than the numbers.

**To Reproduce**
_Steps to reproduce the behavior:_
_1. Go to '...'_
_2. Click on '....'_
_3. Scroll down to '....'_
_4. See error_
Apply uefi fix(boot not recognized section), update to kernel 4.14.116-1. No other boot modifications.

**Expected behavior**
_A clear and concise description of what you expected to happen._
Successful update

**Actual behavior**
_What actually happened (instead of what you expected to happen)._
Update failed

**Screenshots**
_If applicable, add screenshots to help explain your problem._

**Additional context**
_Add any other context about the problem here._

**Solutions you've tried**
_If applicable, any solutions or workarounds you've already tried._
I managed to fix it by doing the following but I'm worried about future updates
0. Don't restart before fixing! Also you'll need an external boot to modify the boot partition later(can prepare after the shutdown step using a different system). Also this guide is designed under the assumption that you have applied the uefi fix(boot not recognized section) so modify as needed for other setups.
1. sudo unmount /boot/efi
2. mkdir /mnt/boottemp1
3. fdisk -l | grep /dev/s #find the boot partition
4. mount bootpartition /mnt/boottemp1
5. (not sure if this will create future issues) delete initramfs for older kernels in /mnt/boottemp1/EFI/BOOT 
6. cd
7. unmount /mnt/boottemp1
8. sudo mount bootpartition /boot/efi
9. Don't reinstall right away, before you reinstall the new kernel be prepared to do the following. Be prepared to open qubes global settings mid reinstall. You have to open qubes global settings when the second part of the reinstall starts(2/x)(this is important because some command finishes mk2efs before the second part starts)  and before it finishes, in that small time-frame you have to set default kernel to none. If you don't think you'll be able to do it let the reinstall fail and try next time(if it fails you'll need to interrupt when the reinstall reaches a point it can't get past (ctrl+c))(the reinstall fails saying the default kernel is the one you are trying to reinstall). Don't bother trying to set the default kernel to none before reinstalling, the first part of the reinstall sets the new kernel as default.
10. Reinstall keeping the above in mind, real time crunch.
11. Successful reinstall -> set default kernel to newest/whatever you want
11-5. Shutdown
12. Boot into external booter like the qubes installation iso (click ctrl +alt+f2 after the installation screen is loaded).
13. fdisk -l | grep /dev/s #find the (possibly different) boot partition label
14. mkdir /mnt/boottemp2
15. mount bootpartition /mnt/boottemp2
16. I like to reverse the uefi fix(be careful not to forget any boot modifications you'll have to reapply) before reapplying just to be safe (rm -r /mnt/boottemp2/EFI/BOOT). If you do so, don't reapply the uefi fix yet.
17. dont perform the uefi fix yet. using a text editor (ie vi ) edit /mnt/boottemp2/EFI/qubes/xen.cfg or edit the BOOTX64.cfg if you didnt bother to reverse the uefi fix
18. (There might be changes between kernels, will update if anyone can tell me what should be changed). The section for the new kernel was missing so I recreated it using the section for the old kernels, only changes I made were to reference new numbers(ie 4.14.116-1).
19. Save file
20. Reapply uefi fix(recording any boot modifications beforehand) like you should after every xen/kernel update
21. Reapply any boot modifications
22. Boot should work fine

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
_A list of links to the Qubes documentation (or other relevant software documentation) pages you have already consulted._

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
_A list of links to other bug reports, feature requests, or tasks in the qubes-issues tracker. Do not describe any other unreported bugs, features, or tasks here._

**Comment by DemiMarie** [comment]
I have had the same problem.  It took me three days to be able to procure boot media and verify the image.

**Comment by marmarek** [comment]
The update script should better handle out of disk space situation in /boot. This include:
1. Ideally make the rpm abort the update if there is not enough space in `/boot/efi`. rpm do check for space, but it doesn't know about generated files. Maybe something like [this](https://github.com/QubesOS/qubes-issues/issues/5043) for uefi too?

2. Regardless of the above, the script should _not_ switch to the new kernel, if initramfs generation failed. And probably also do not leave half-baked initramfs there.

**Comment by AlxHnr** [comment]
I've ran into the same issue when updating to 4.19.147-1. `sudo qubes-dom0-update` succeeded and returned 0, but created an incomplete initramfs resulting in a kernel panic. The created initramfs was significantly smaller in size than its supposed to be. I assume this happened because my boot partition was full and thats my own fault. But `sudo qubes-dom0-update` _should_ at least fail with an error message in this case.
