### ISSUE TITLE
Clarify license for the Qubes logos

### ISSUE THREAD

**Issue by maltesl** [QubesOS/qubes-issues#5042]
https://github.com/QubesOS/qubes-artwork/blob/master/COPYING seems to suggest
that the license for the Qubes logo files (which presumably fall under
"artwork", at least the png version, possibly also the svg version (is svg considered
"artwork" or "code"?)) are licensed under the Creative Commons Attribution-ShareAlike
4.0 International Licence.

However the page https://www.qubes-os.org/doc/style-guide/ seems to suggest
that those files are licensed under the GPLv2.

**Comment by andrewdavidwong** [comment]
Based on the consensus in #4219, the license will be CC BY-SA.
