### ISSUE TITLE
qvm-block attach, qvm-block list fail with "Got empty response from qubesd. See journalctl in dom0 for details." after I updated Qubes for the MDS mitigations.

### ISSUE THREAD

**Issue by kyoobees** [QubesOS/qubes-issues#5047]
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
`qvm-block attach`, `qvm-block list` - possibly everything related to `qvm-block` or `qvm-device`.

**Brief summary**
`qvm-block attach <destvm> dom0:sdx1` and `qvm-block list <vm>` don't always work.

**To Reproduce**
I'm not sure how reproducible this is, but the steps I followed were:
_Steps to reproduce the behavior:_
_1. Update dom0 with the security testing repo_
_2. Attach and detach a few devices_
_3. See error_

**Expected behavior**
`qvm-block` is able to attach and detach devices, as well as list available devices from a VM.

**Actual behavior**
It worked a few times and later I got a qubesd-related error:

> Got empty response from qubesd. See journalctl in dom0 for details.

**Additional context**
I updated dom0 with `sudo qubes-dom0-update --enablerepo=qubes-dom0-security-testing` and restarted. `qvm-block attach <destvm> dom0:sdx1` worked a few times to move some LUKS partitions of external and internal HDDs to a disp VM that does the decryption. Getting the names of the decrypted partitions that the disp VM exposes from dom0 console with `qvm-block list <dispvm>` worked once, then I attached those decrypted partitions of the disp VM to a source VM, again from the dom0 console with `qvm-block attach <destvm> <dispvm>:dm-x`. This succeeded the first 1 or 2 times. I had to redo the steps due to other issues (unrelated) and it didn't work anymore - neither detaching, nor attaching partitions like I used to. `qvm-block list <vm>` also doesn't work.  All I get is:

> Got empty response from qubesd. See journalctl in dom0 for details.

I also disabled hyper-threading, hardware prefetcher and adjacent cache line prefetch from the UEFI setup before updating Qubes.

journalctl output for `qvm-list somevmname`:

> May 21 01:07:11 dom0 qubesd[2641]: Failed to list block devices
> May 21 01:07:11 dom0 qubesd[2641]: Traceback (most recent call last):
> May 21 01:07:11 dom0 qubesd[2641]:   File "/usr/lib/python3.5/site-packages/qubes/devices.py", line 352, in assignments
> May 21 01:07:11 dom0 qubesd[2641]:     persistent=persistent)
> May 21 01:07:11 dom0 qubesd[2641]:   File "/usr/lib/python3.5/site-packages/qubes/events.py", line 198, in fire_event
> May 21 01:07:11 dom0 qubesd[2641]:     pre_event=pre_event)
> May 21 01:07:11 dom0 qubesd[2641]:   File "/usr/lib/python3.5/site-packages/qubes/events.py", line 170, in _fire_event
> May 21 01:07:11 dom0 qubesd[2641]:     effects.extend(effect)
> May 21 01:07:11 dom0 qubesd[2641]:   File "/usr/lib/python3.5/site-packages/qubes/ext/block.py", line 197, in on_device_list_attached
> May 21 01:07:11 dom0 qubesd[2641]:     backend_domain = vm.app.domains[backend_domain_node.get('name')]
> May 21 01:07:11 dom0 qubesd[2641]:   File "/usr/lib/python3.5/site-packages/qubes/app.py", line 467, in __getitem__
> May 21 01:07:11 dom0 qubesd[2641]:     raise KeyError(key)
> May 21 01:07:11 dom0 qubesd[2641]: KeyError: 'disp4083'
> May 21 01:07:11 dom0 qubesd[2641]: unhandled exception while calling src=b'dom0' meth=b'admin.vm.device.block.List' dest=b'somevmname' arg=b'' len(untrusted_payload)=0
> May 21 01:07:11 dom0 qubesd[2641]: Traceback (most recent call last):
> May 21 01:07:11 dom0 qubesd[2641]:   File "/usr/lib/python3.5/site-packages/qubes/api/__init__.py", line 266, in respond
> May 21 01:07:11 dom0 qubesd[2641]:     untrusted_payload=untrusted_payload)
> May 21 01:07:11 dom0 qubesd[2641]:   File "/usr/lib64/python3.5/asyncio/futures.py", line 381, in __iter__May 21 01:07:11 dom0 qubesd[2641]: File "/usr/lib/python3.5/site-packages/qubes/app.py", line 467, in getitem

> May 21 01:07:11 dom0 qubesd[2641]:     yield self  # This tells Task to wait for completion.
> May 21 01:07:11 dom0 qubesd[2641]:   File "/usr/lib64/python3.5/asyncio/tasks.py", line 310, in _wakeup
> May 21 01:07:11 dom0 qubesd[2641]:     future.result()
> May 21 01:07:11 dom0 qubesd[2641]:   File "/usr/lib64/python3.5/asyncio/futures.py", line 294, in result
> May 21 01:07:11 dom0 qubesd[2641]:     raise self._exception
> May 21 01:07:11 dom0 qubesd[2641]:   File "/usr/lib64/python3.5/asyncio/tasks.py", line 240, in _step
> May 21 01:07:11 dom0 qubesd[2641]:     result = coro.send(None)
> May 21 01:07:11 dom0 qubesd[2641]:   File "/usr/lib64/python3.5/asyncio/coroutines.py", line 210, in coro
> May 21 01:07:11 dom0 qubesd[2641]:     res = func(*args, **kw)
> May 21 01:07:11 dom0 qubesd[2641]:   File "/usr/lib/python3.5/site-packages/qubes/api/admin.py", line 1181, in vm_device_list
> May 21 01:07:11 dom0 qubesd[2641]:     device_assignments = self.dest.devices[devclass].assignments()
> May 21 01:07:11 dom0 qubesd[2641]:   File "/usr/lib/python3.5/site-packages/qubes/devices.py", line 352, in assignments
> May 21 01:07:11 dom0 qubesd[2641]:     persistent=persistent)
> May 21 01:07:11 dom0 qubesd[2641]:   File "/usr/lib/python3.5/site-packages/qubes/events.py", line 198, in fire_event
> May 21 01:07:11 dom0 qubesd[2641]:     pre_event=pre_event)
> May 21 01:07:11 dom0 qubesd[2641]:   File "/usr/lib/python3.5/site-packages/qubes/events.py", line 170, in _fire_event
> May 21 01:07:11 dom0 qubesd[2641]:     effects.extend(effect)
> May 21 01:07:11 dom0 qubesd[2641]:   File "/usr/lib/python3.5/site-packages/qubes/ext/block.py", line 197, in on_device_list_attached
> May 21 01:07:11 dom0 qubesd[2641]:     backend_domain = vm.app.domains[backend_domain_node.get('name')]
> May 21 01:07:11 dom0 qubesd[2641]:   File "/usr/lib/python3.5/site-packages/qubes/app.py", line 467, in __getitem__
> May 21 01:07:11 dom0 qubesd[2641]:     raise KeyError(key)
> May 21 01:07:11 dom0 qubesd[2641]: KeyError: 'disp4083'

I think disp4083 was one of the no-net disp VMs I use for decrypting the LUKS partitions. It was shutdown long before the error appeared.

**Solutions you've tried**
`sudo systemctl restart qubesd.service` - didn't fix anything.
I will reboot and see what happens.

**Comment by marmarek** [comment]
I don't think it's related to updates. This looks rather like you have shutdown that DispVM when device was still attached from it. This basically means, it is the same as https://github.com/QubesOS/qubes-issues/issues/4784
Try restarting VM to which that device was connected and see if that helps.
