### ISSUE TITLE
Qubes RPC and RPC policy overrides or change how the RPM package works

### ISSUE THREAD

**Issue by zS3mNH2** [QubesOS/qubes-issues#5048]
**The problem you're addressing (if any)**
It is impossible to override an RPC or RPC policy because their paths are fixed and package updates will override any changes or if the file is set to immutable, then package updates will no longer work.

RPC commands (those found in /etc/qubes-rpc) are basically executables. Similar to having a path variable for linux executables there should be a local path for RPCs and RPC-policies so they can be safely overwritten.

I understand the upcoming format change #4370 will allow some kind of overriding for policies, but it does not allow for overwriting of the handlers from what I can see (/etc/qubes-rpc/qubes.GetData for example). In addition, the complete format change for qubes-rpc will likely be far in the future whereas the allowing overriding in the existing framework would be a much quicker fix.

Example issue I had is updating /etc/qubes-rpc/qubes.GetDate to include some jitter in the time and thus the timestamp between VMs cannot be used to fingerprint. However, since it is impossible to really override this file due to package updates the changes keep getting overwritten.

**Describe the solution you'd like**
Make it so files are looked in /usr/local/etc/qubes-rpc as well as /etc/qubes-rpc where /usr/local/etc/qubes-rpc has precedence. This way people can make local changes that do not conflict with the provided package files

Another alternative would be to make it so the package that provides these do not fail to update when the file is not writeable. Instead, append rpmnew to it and continue if there has been a change.

I notice that for /etc/qubes-rpc/policy files the package will install and append rpmnew. However, for /etc/qubes-rpc files it will overwrite and fail if it cannot do so.

**Where is the value to a user, and who might that user be?**
The primary value is being able to make local changes to these files as needed. 

**Describe alternatives you've considered**
Instead of changing code make it so the RPM packages do not overwrite changes in /etc/qubes-rpc as is already done for /etc/qubes-rpc/policy

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

#4370 solves the policy issue however that is already primarily a non-issue as it appends rpmnew when changes have occurred. The main issue is the handlers in /etc/qubes-rpc which will either overwrite changes or fail to install updates if not writeable.

**Comment by marmarek** [comment]
> Make it so files are looked in /usr/local/etc/qubes-rpc as well as /etc/qubes-rpc where /usr/local/etc/qubes-rpc has precedence. This way people can make local changes that do not conflict with the provided package files

This is already the case.
Done :)
