### ISSUE TITLE
Suspend doesn't work at all. Computer shuts down with "systemctl suspend"

### ISSUE THREAD

**Issue by esox1** [QubesOS/qubes-issues#5049]
### Qubes OS version:
R4.0
Linux doom0 4.14.116-1
Lenovo e570

### Affected component(s) or functionality:

systemctl suspend.service

---

### Steps to reproduce the behavior:

Typing the command "systemctl suspend" in terminal or closing the lid

### Expected or desired behavior:

The computer will go into a supspend mode when the lid is closed

### Actual behavior:

Computer powers off

### General notes:

I am running i3 window manager,  in xfce4-settings-manager. I have the suspend mode set on when 'close the lid'
I have "mem_sleep_default=deep " parameter in grub.cfg and regenerated. But still with closing the lid, it will turn off the computer.

Doing "systemctl status qubes-suspend.service" shows suspend as loaded and inactive(dead)
Doing "journalctl -u qubes-suspend.service" shows

In terminal to check mem_sleep value "sudo cat /sys/power/men_sleep " shows  deep selected "s2idle [deep]"

In journactl log it shows
"-- Reboot --
Dom0 systemd[1]: Starting Qubes suspend hooks ...
Dom0 52qubes-pause-vms[12838]: 0
Dom0 systems[1]: Started Qubes suspend hooks.

--Reboot--
Dom0 systemd[1]: qubes-suspend. Service: Unit not needed anymore. stopping"
I am not sure why it shuts off. I am not using Evil maid in my boot btw. I have also tried to shut off all the VMs manually first. for example;  sys-usb and sys-net and then run the systemctl suspend command. But even then it still powers off the box. Any help is greatly appreciated

---

### I am aware of the following related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues:

I read all of the suspend issues but they seemed a little different than my issue where the computer tunrs off  whevever a suspend issue w

**Comment by andrewdavidwong** [comment]
This might turn out to be too localized for qubes-issues, but I'll leave it open until we find out more.

**Comment by esox1** [comment]
Worked after disabling TPM security in the bios.
