### ISSUE TITLE
qubes-dom0-update doesn't handle low disk space conditions well

### ISSUE THREAD

**Issue by strugee** [QubesOS/qubes-issues#5052]
**Qubes OS version**

R4.0

**Affected component(s) or functionality**

`qubes-dom0-update`

**Brief summary**

When the system has very low disk space, `qubes-dom0-update` fails with an error message that just says "failed with exit code 1" instead of something more helpful (like "No space left on device").

**To Reproduce**

1. Make sure your disk utilization is above the percentage reserved by ext4. You may change this value on your filesystem using `sudo tune2fs -m <percentage> /dev/mapper/qubes_dom0-root`, where `<percentage>` is the % of your filesystem that will be reserved for the superuser only; `df -h /` should report 0 in the "available" column
2. Run `qubes-dom0-update` with updates pending

**Expected behavior**

Either the update succeeds or the update fails and tells me that I'm out of disk space.

**Actual behavior**

The update fails with this output:

```
[alex@dom0 ~]$ sudo qubes-dom0-update
Using sys-firewall-disp as UpdateVM to download updates for Dom0; this may take some time...
--> Running transaction check
---> Package kernel-latest.x86_64 1000:5.1.2-1.pvops.qubes will be installed
---> Package qubes-gpg-split-dom0.x86_64 0:2.0.38-1.fc25 will be installed
---> Package qubes-manager.noarch 0:4.0.34-1.fc25 will be installed
---> Package qubes-mgmt-salt-dom0-qvm.noarch 0:4.0.8-1.fc25 will be installed
---> Package qubes-usb-proxy-dom0.noarch 0:1.0.21-1.fc25 will be installed
--> Finished Dependency Resolution
/var/lib/qubes/dom0-updates/packages/kernel-latest-5.1.2-1.pvops.qubes.x86_64.rpm already exists and appears to be complete
/var/lib/qubes/dom0-updates/packages/qubes-gpg-split-dom0-2.0.38-1.fc25.x86_64.rpm already exists and appears to be complete
/var/lib/qubes/dom0-updates/packages/qubes-manager-4.0.34-1.fc25.noarch.rpm already exists and appears to be complete
/var/lib/qubes/dom0-updates/packages/qubes-mgmt-salt-dom0-qvm-4.0.8-1.fc25.noarch.rpm already exists and appears to be complete
/var/lib/qubes/dom0-updates/packages/qubes-usb-proxy-dom0-1.0.21-1.fc25.noarch.rpm already exists and appears to be complete
find: '/var/lib/qubes/dom0-updates/var/cache': No such file or directory
EOF
'/usr/lib/qubes/qrexec-client-vm dom0 qubes.ReceiveUpdates /usr/lib/qubes/qfile-agent /var/lib/qubes/dom0-updates/packages/*.rpm' failed with exit code 1!
```

**Additional context**

ext4 reserves a certain percentage of disk space for the superuser; see [this](https://unix.stackexchange.com/q/7950/29146) Stack Exchange question for an explanation of why. This can come out to tens of gigabytes on large partitions. For example, in my case my Qubes partition is 590GB which comes out to ~29.5 GB of disk space reserved for the superuser only.

The reason I said the expected behavior might include the update succeeding is because in this case, there actually is plenty of free space, but it seems that some process invoked by `qubes-dom0-update` is running as a non-superuser. If it ran as the superuser, it would have permission to write to the reserved space in the filesystem. I do think it's probably a better idea to signal an ENOSPC error, though; that route seems like it's playing with fire.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

None

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

https://github.com/QubesOS/qubes-issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+qubes-dom0-update+free+space

**Comment by andrewdavidwong** [comment]
Somewhat related: #3299

**Comment by strugee** [comment]
@andrewdavidwong maybe `qubes-dom0-update` just needs to brush up on its error handling in general?

By the way, this reminds me of something I keep meaning to ask on the mailing list or something - have I been misusing the "non-duplicate issues" section of the issue template? I think every issue I've filed since it got added I've just linked to a search because my impression was that it's just to make sure people have searched for duplicates first, but I wanted to double-check if that's (not) correct.

**Comment by andrewdavidwong** [comment]
> @andrewdavidwong maybe `qubes-dom0-update` just needs to brush up on its error handling in general?

It appears so.

> By the way, this reminds me of something I keep meaning to ask on the mailing list or something - have I been misusing the "non-duplicate issues" section of the issue template? I think every issue I've filed since it got added I've just linked to a search because my impression was that it's just to make sure people have searched for duplicates first, but I wanted to double-check if that's (not) correct.

Linking search results is better than nothing, but linking specific issues is better, since it creates a visible link on each of those issues and more specifically conveys the ones you have checked and believe to be related non-duplicates.

**Comment by strugee** [comment]
> Linking search results is better than nothing, but linking specific issues is better, since it creates a visible link on each of those issues and more specifically conveys the ones you have checked and believe to be related non-duplicates.

OK, got it. FWIW I've found in the past that often it's difficult to find _any_ issue that seems even vaguely related, which makes it hard to actually fill out this section. I'm not sure; maybe my standards for "related" are too high? But that's been my experience when filing bugs in the past (which is why I tend to just link to search results). I'll certainly do my best though! Thanks for clarifying :thumbsup:

And thanks as always for maintaining Qubes OS. It's much appreciated!

**Comment by andrewdavidwong** [comment]
> OK, got it. FWIW I've found in the past that often it's difficult to find _any_ issue that seems even vaguely related, which makes it hard to actually fill out this section. I'm not sure; maybe my standards for "related" are too high? But that's been my experience when filing bugs in the past (which is why I tend to just link to search results). I'll certainly do my best though! Thanks for clarifying 
> 

In that case, you can just say "none." It's also useful to know that you looked for related issues and didn't find any. (When people just leaves the section blank, it's most likely that they didn't check at all.)

> And thanks as always for maintaining Qubes OS. It's much appreciated!

Thank you!

**Comment by strugee** [comment]
> In that case, you can just say "none." It's also useful to know that you looked for related issues and didn't find any. (When people just leaves the section blank, it's most likely that they didn't check at all.)

OK, that makes a lot of sense. Filed #5063 to clarify that (I think I didn't think of it because I assumed it was just to prove that I searched for duplicates).

**Comment by andrewdavidwong** [comment]
> OK, that makes a lot of sense. Filed #5063 to clarify that (I think I didn't think of it because I assumed it was just to prove that I searched for duplicates).

Good idea. Thanks!

This was a productive discussion, but since it's off-topic, I'm going to hide our comments now so that others can easily skim this issue. :slightly_smiling_face:
