### ISSUE TITLE
Qubes Disk Widget - please inform about/alert on pool metadata space

### ISSUE THREAD

**Issue by brendanhoar** [QubesOS/qubes-issues#5053]
**The problem you're addressing (if any)**
The new Qubes disk space widget is useful. However, some users of the default file system layout (ext4/etc. in a LVM Thin Provisioned Pool) are running out of metadata far before running out of disk space.

**Describe the solution you'd like**
- Add an additional line/bar displaying the amount/percent of metadata space left in the pool. 
- Additionally alert on low metadata space.
- Add a popup indicating what steps the user can take to address when metadata is low.
- Consider adding some warnings or monitoring to qvm-* tools that are likely lead to increased metadata as well.

**Where is the value to a user, and who might that user be?**
1. Resolving disk space issues is rather straightforward and when one is approaching or has reached the limit, there are steps that generally educated computer users can take to resolve.

2. On the other hand, resolving metadata space issues is not straightforward and some steps a user might take based as generally educated computer user can make the situation worse. In addition, generally, it is easy to get the pool+file systems into a non-recoverable state.

**Describe alternatives you've considered**
1. Qubes installer increases metadata size above the default (increase by factor of 2x to 4x, perhaps).
2. Switch from ext4+lvm thin provisioning to btrfs. Stability and/or baby/bathwater issues.
3. Chide users for not making backups.

**Additional context**
https://groups.google.com/forum/#!topic/qubes-users/qq_ElNPdx-g

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
I did not see anything addressing the issue on https://www.qubes-os.org

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
#5054

**Comment by brendanhoar** [comment]
Thanks @marmarta ! 

I tried several times to do all the api plumbing to get the data up to where it was needed in the widget and failed a couple months back.

Looking forward to R 4.1!

Brendan

**Comment by tlaurion** [comment]
@andrewdavidwong : the upgrade notes of QubesOS states that the user can apply upgrades from Qubes 4 and have the same system as if it was freshly installed. 

@marmarek This is false, since anaconda was modified since then and changes behavior for discards and metadata pool size, and consequently, newer installations are fixed to mitigate future problems, where upgraded systems are not.

As stated [here](https://github.com/tasket/wyng-backup/issues/53#issuecomment-583959832), the widget should inform/permit the user to fix problems related on that matter, so that freshly installed Qubes/upgraded 4.+ results in the same stable system for users on LVM discards/metadata pool potential problems.

**Comment by andrewdavidwong** [comment]
@tlaurion:
> @andrewdavidwong : the upgrade notes of QubesOS states that the user can apply upgrades from Qubes 4 and have the same system as if it was freshly installed.
> 
> @marmarek This is false, since anaconda was modified since then and changes behavior for discards and metadata pool size, and consequently, newer installations are fixed to mitigate future problems, where upgraded systems are not. ([True?](https://groups.google.com/d/msg/qubes-users/3r9MuyQHTUs/qLzKmpG4AQAJ))
> 
> @marmarta As stated [here](https://github.com/tasket/wyng-backup/issues/53#issuecomment-583959832), the widget should permit the user to fix problems related on that matter, so that freshly installed Qubes/upgraded 4.+ results in the same stable system for users on LVM discards/metadata pool potential problems.

Shouldn't this be reported as a separate issue? It sounds rather different from the topic of this issue ("inform about/alert on pool metadata space").

**Comment by tlaurion** [comment]
@andrewdavidwong 
> Shouldn't this be reported as a separate issue? It sounds rather different from the topic of this issue ("inform about/alert on pool metadata space").

The issue related here is still that once tpool is maxed out, the user is not informed of what to do to resolve the issue.

**Comment by andrewdavidwong** [comment]
> The issue related here is still that once tpool is maxed out, the user is not informed of what to do to fix it but informed it is near maxed out. What would be the proposed action? 

I see that @brendanhoar raised this point in the original issue description, where he wrote:

> Add a popup indicating what steps the user can take to address when metadata is low.
> [...]
> On the other hand, resolving metadata space issues is not straightforward and some steps a user might take based as generally educated computer user can make the situation worse. In addition, generally, it is easy to get the pool+file systems into a non-recoverable state.

It sounds like you're saying that this part of the issue has not yet been addressed, so you'd like for this issue to be reopened. Am I understanding you correctly?

**Comment by tlaurion** [comment]
Yes. Workaround referenced is unfortunately to reduce size of swap and affect that space to tpool. Other advices welcome.

It's an assured disaster waiting to happen. Even faster if playing around with wyng. 

It hit me twice. Upgraded to 4.0.3 since then.

On February 15, 2020 12:58:24 PM UTC, Andrew David Wong <notifications@github.com> wrote:
>> The issue related here is still that once tpool is maxed out, the
>user is not informed of what to do to fix it but informed it is near
>maxed out. What would be the proposed action? 
>
>I see that @brendanhoar raised this point in the original issue
>description, where he wrote:
>
>> Add a popup indicating what steps the user can take to address when
>metadata is low.
>> [...]
>> On the other hand, resolving metadata space issues is not
>straightforward and some steps a user might take based as generally
>educated computer user can make the situation worse. In addition,
>generally, it is easy to get the pool+file systems into a
>non-recoverable state.
>
>It sounds like you're saying that this part of the issue has not yet
>been addressed, so you'd like for this issue to be reopened. Am I
>understanding you correctly?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/QubesOS/qubes-issues/issues/5053#issuecomment-586587990

-- Sent from /e/ Mail

**Comment by DemiMarie** [comment]
Can this be backported to R4.0?  This is a serious issue that has caused data loss.

**Comment by marmarek** [comment]
Widget in R4.1 reports metadata usage already, and also the default metadata size was doubled to avoid this issue from happening.
