### ISSUE TITLE
Data loss when renaming qube

### ISSUE THREAD

**Issue by zS3mNH2** [QubesOS/qubes-issues#5056]
**Qubes OS version**
Latest fully updated qubes

**Affected component(s) or functionality**
Renaming a qube

**Brief summary**
I created a qube a while ago. It is a standalone qube based off of a template. Today I was doing stuff in it and I shut it down. I then decided to rename it. When I re-opened the qube all the recent changes were done.

**To Reproduce**
_Steps to reproduce the behavior:_
_1. Create standalone qube
_2. Do stuff in it later and shut it down
_3. Rename qube
_4. Data is loss

**Expected behavior**
There should be no data loss. I understand that when a qube is shut down there is a changed volume that gets merged when it gets started. THis should be merged prior to renaming so that there is no dataloss

**Actual behavior**
Data loss occurs

**Screenshots**
_If applicable, add screenshots to help explain your problem._

**Additional context**
_Add any other context about the problem here._

**Solutions you've tried**
_If applicable, any solutions or workarounds you've already tried._

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
_A list of links to the Qubes documentation (or other relevant software documentation) pages you have already consulted._

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
_A list of links to other bug reports, feature requests, or tasks in the qubes-issues tracker. Do not describe any other unreported bugs, features, or tasks here._

**Comment by zS3mNH2** [comment]
Maybe the cause of this or related there is some error with the Qubes widget that is in the top right of the screen. It lists basically all my VMs as running even though they are not running. It has it placed as "0 MB" of RAM. I tried to "kill" them, but of course they aren't running so it cannot be killed.

The normal Qubes manager shows things correctly.

**Comment by marmarek** [comment]
Do you have updates installed? A problem similar to this "0 MB" was fixed a while ago, which suggests some packages are outdated.

**Comment by zS3mNH2** [comment]
Yes, I just double checked an all updates are installed. I also run dom updates once a day automatically via cron.

**Comment by zS3mNH2** [comment]
Btw, to add more color to whether the system was updated. If there were changes that required a restart to take effect, then it could have been that they weren't applied. Due to the general rock-solid stability of Qubes I can go a couple weeks between restarts.

**Comment by andrewdavidwong** [comment]
> Btw, to add more color to whether the system was updated. If there were changes that required a restart to take effect, then it could have been that they weren't applied. Due to the general rock-solid stability of Qubes I can go a couple weeks between restarts.

In general, restarts are required only after Xen and kernel updates.

**Comment by donob4n** [comment]
Hi, I've just failed trying to reproduce this. Could you check again @zS3mNH2 ?

**Comment by DemiMarie** [comment]
I suspect this has been fixed in R4.1 unless someone can reproduce it.
