### ISSUE TITLE
Can't update buster templates from qubes-manager

### ISSUE THREAD

**Issue by airelemental** [QubesOS/qubes-issues#5057]
**Qubes OS version**
R4.0.1 current-testing

**Affected component(s) or functionality**
qubes-manager's right-click > update qube
debian-10, whonix-ws-15, whonix-gw-15

**Brief summary**
Updating a debian-10 template using the right-click menu item fails. 

**To Reproduce**
1. Obtain a buster-based template, either by upgrading a stretch template or downloading whonix-ws-15 from community-testing.
2. Right-click template in qubes-manager and choose upgrade

**Expected behavior**
xterm launched, upgrade proceeds

**Actual behavior**
```Failed to apply DSA-4371 fix: Error: Error: Could not determine Debian release!``` Does not upgrade.

**Solutions you've tried**
You can still upgrade the template by opening a terminal and manually running apt commands.

Cause is probably `/usr/libexec/qubes-manager/dsa-4371-update` around line 78 needs a case statement for 10.*

Inside debian-10 / whonix-ws-15:
$ cat /etc/debian_version
10.0

**Comment by lunarthegrey** [comment]
For some reason when I run `qubes-dom0-update` also with `--clean` I don't see `qubes-manager-4.0.36-1` in the stable repo at all. Says there's nothing to do.

When I enable `*current-testing` I see it though. Is there an issue where it's not being pushed to the stable repo? Or maybe it's fetching it from a mirror that doesn't have it?

**Comment by marmarek** [comment]
Yes, see https://github.com/QubesOS/qubes-issues/issues/4988#issuecomment-509483833

**Comment by lunarthegrey** [comment]
Thanks @marmarek. Tried looking around for the issue but couldn't find it.
