### ISSUE TITLE
qubesd failed to start

### ISSUE THREAD

**Issue by vujadev** [QubesOS/qubes-issues#5059]
### Affected component(s) or functionality:

---

### General notes:

---

**Comment by vujadev** [comment]
After changing default kernel in qubes manager qubesd failed to start after reboot.
I`ve manually edit qubes.xml with old version of kernel... but result was same...
the error for qubesd failed to start -  'default_template none'...  after spending a lot of time trying to find file where this default_template is set i gave up with an idea try to mount VM volume and pci usb controller in dom0 to get out the data and than reinstall qubes OS.  Without qubesd no qvm and qubes command are available, day more... disabling xen_modules,killing all qubes and xen services, udev rules, playing with /dev and sys/bus pciback and other  i still could not enable usb controller in dom0 the same with is with VM volumes.
all volumes are listed with lsblk the same is with USB controller with lspci 
Please don`t laugh loud and give me an advice how to mount VM volume in dom0 and add USB controller to dom0. 
Thanks in advance.

**Comment by andrewdavidwong** [comment]
Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this does not appear to be suitable for `qubes-issues`. We ask that you please send this to the `qubes-users` [mailing list](https://www.qubes-os.org/support/) instead. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a brief comment explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.
