### ISSUE TITLE
Fedora 30 template /etc/init.d directory is owned by no package

### ISSUE THREAD

**Issue by mvermaes** [QubesOS/qubes-issues#5060]
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
`qubes-template-fedora-30-4.0.1-201904301131`

**Brief summary**
The Fedora 30 template already has the directory `/etc/init.d`, with a single file - `qubes-gui-agent` within. Attempting to install a package (`chkconfig` - possibly others?) fails with the cpio error below.

**To Reproduce**
1. Download `qubes-template-fedora-30-4.0.1-201904301131` to dom0
2. Start template
3. `sudo dnf install chkconfig` in the template

**Expected behavior**
`chkconfig` is installed

**Actual behavior**
```
  Installing       : chkconfig-1.11-4.fc30.x86_64                           1/1 
Error unpacking rpm package chkconfig-1.11-4.fc30.x86_64
error: unpacking of archive failed on file /etc/init.d: cpio: File from package already exists as a directory in system
...
Failed:
  chkconfig-1.11-4.fc30.x86_64                                                  

Error: Transaction failed
```

**Solutions you've tried**
I checked a clean Fedora 28 template. In that template, `chkconfig` was already installed as part of the build process and owned the `/etc/init.d` directory, so this wasn't an issue.

**Comment by andrewdavidwong** [comment]
Related to: #4845

**Comment by fepitre** [comment]
PR opened. I managed to fix this problem as we don't need ```qubes-gui-agent``` init script.
