### ISSUE TITLE
Windows Qubes Disks

### ISSUE THREAD

**Issue by pidifytech** [QubesOS/qubes-issues#5062]
**Qubes OS version**
R4.0.1

**Affected component(s) or functionality**
When creating windows qubes as per the qubes guide found at https://www.qubes-os.org/doc/windows-vm/ 

**Brief summary**
When creating qubes as per the above mentioned guide windows detects 3 drives in the disk manager A) Main Drive B) Private Storage 2GB C) Another Device 10GB

**To Reproduce**
_1. Go to 'https://www.qubes-os.org/doc/windows-vm/ '
_2. follow the guide to creating a windows qube
_3. Install windows 7
_4. Go to Disk manager diskmgmt.msc

**Expected behavior**
Qubes should only see two drives the Primary drive & the private storage drive

**Actual behavior**
qube sees an additional drive of 10GB

**Comment by pidifytech** [comment]
qvm-volume info vmname

detects that it has an additional volume 'volatile' how come this is created by default? is there a way to remove it or not create it with future vm's

thank you

**Comment by marmarek** [comment]
Hmm, I don't see list of expected disks on that page. It is expected that VM has 3 disks, see https://www.qubes-os.org/doc/template-implementation/ for their description. While indeed "volatile" volume isn't very useful in Windows VM right now (you may use it as a big temporary space), there is no option to skip it.

**Comment by pidifytech** [comment]
@marmarek only problem is this wastes on average 12GB per windows VM in space which is lost. that sir is substantial

**Comment by marmarek** [comment]
As long as you don't write anything to that disk, the space isn't really used (thanks to LVM thin provisioning).

**Comment by unman** [comment]
On Fri, May 31, 2019 at 12:43:42AM +0000, pidifytech wrote:
> @marmarek only problem is this wastes on average 12GB per windows VM in space which is lost. that sir is substantial
> 

That space isnt lost on default thin provisioning.
If you dont use it it wont be allocated.
(The same applies to all qube disk space.)
