### ISSUE TITLE
Boot loop.

### ISSUE THREAD

**Issue by SysCallz** [QubesOS/qubes-issues#5064]
**Qubes OS version**
R4.0.1

**Affected component(s) or functionality**
Dose not boot as discribed below

**Brief summary**
Dose not boot to login screen after entering decryption password.

**To Reproduce**
Fresh install of qubes on amd 1950x and asus zenith extreme with nvme.  Boot and enter password for drive encyption. Watch the loop. 

**Expected behavior**
Boot OS and show login screen

**Screenshots**
![15592984800637524356517517320153](https://user-images.githubusercontent.com/28976032/58700169-47d5b900-8397-11e9-8c31-7686c7684b0d.jpg)

**Comment by andrewdavidwong** [comment]
Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this does not appear to be suitable for `qubes-issues`. We ask that you please send this to the `qubes-users` [mailing list](https://www.qubes-os.org/support/) instead. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a brief comment explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.
