### ISSUE TITLE
Qubes Manager: KeyError7 at line 1335

### ISSUE THREAD

**Issue by Nonestica** [QubesOS/qubes-issues#5066]
### Qubes OS version:

R4.0

### Affected component(s) or functionality:

Qubes Manager

(lib python3.5)

---

### Steps to reproduce the behavior:

Launching Qubes Update

### Actual behavior:

```
----
line: self.vms_in_table[vm.qid].info_widget.update_vm_state()
func: on_domain_status_changed
line no.:586
file: /usr/lib/python3.5/site-packages/qubesmanager/qube_manager.py
----
line: handler(subject, event, **kwargs)
func: handele
line no.:218
file: /usr/lib/python3.5/site-packages/qubesadmin/events/__init__.py
----
line: self.handle(subject, event, **kwargs)
func: listen_for_events
line no.:184
file: /usr/lib/python3.5/site-packages/qubesadmin/events/__init__.py
----
line: yeld from self._listen_for_events(vm)
func: listen_for_events
line no.:126
file: /usr/lib/python3.5/site-packages/qubesadmin/events/__init__.py
----
line: result = coro.send(None)
func: _step
line no.:240
file: /usr/lib64/python3.5/asyncio/tasks.py
----
line: raise self._exception
func: result
line no.:294
file: /usr/lib64/python3.5/asyncio/futures.py
----
line: return future.result()
func: run_until_complete
line no.:289
file: /usr/lib/python3.5/site-packages/quamash/__init__.py
----
line: asyncio.ensure_future(dispatcher.listen_for_events()))
func: main
line no.:1335
file: /usr/lib/python3.5/site-packages/qubesmanager/qube_manager.py
----
```

### General notes:

It seems there's a syntax error on line 1335:  lack or profusion of ')'

---

**Comment by marmarta** [comment]
Stack trace is not showing the previous line which has the appropriate opening braces, so it's not that, unfortunately; I'm going to add some safeguards to avoid this issue, but I'm very curious about details:
- is the error repeatable on your system?
- does it occur at the moment Qubes Update is launched?
- how are you launching it?
- are there any crashing or ending dispvms around?

**Comment by marmarta** [comment]
I'm closing this due to lack of response (and actions being taken to avoid this bug happening again). Please reopen if it reoccurs :)
