### ISSUE TITLE
How to add a new user into Qubes OS 4.0?

### ISSUE THREAD

**Issue by cokeflash** [QubesOS/qubes-issues#5069]
Hi!

How to add a new user into Qubes OS 4.0?

I want delete the old one and create a new one.

I opened 'Terminal Emulator'

# sudo su
# useradd -m user
# passwd user
# usermod -aG wheel user

...that works, but I can't login with the new user into Qubes OS.

If I then want to restart Qubes OS an error message appears: 

'Failed to receive a reply from the session manager.

Session manager must be in idle state when requesting a shutdown.'

# sudo shutdown -h now (that works)
...but after shutdown and reboot Qubes OS, Qubes OS booted into emergency-mode.
ROOT is locked, can't boot into Qubes OS.

How can I add a new user into Qubes OS and fix that error?

**Comment by unman** [comment]
On Sun, Jun 02, 2019 at 06:34:11AM -0700, cokeflash wrote:
> Hi!
> 
> How to add a new user into Qubes OS 4.0?
> 
> I want delete the old one and create a new one.
> 
> I opened 'Terminal Emulator'
> 
> # sudo su
> # useradd -m user
> # passwd user
> # usermod -aG wheel user
> 
> ...that works, but I can't login with the new user into Qubes OS.
> 
> If I then want to restart Qubes OS an error message appears: 
> 
> 'Failed to receive a reply from the session manager.
> 
> Session manager must be in idle state when requesting a shutdown.'
> 
> # sudo shutdown -h now (that works)
> ...but after shutdown and reboot Qubes OS, Qubes OS booted into emergency-mode.
> ROOT is locked, can't boot into Qubes OS.
> 
> How can I add a new user into Qubes OS and fix that error?
> 

This isnt appropriate for qubes-issues.
Why dont you continue the thread on this subject in qubes-users?

Qubes isnt designed to be a multi-user system.
However the actions that you have described do suffice to create a new
user who can log in.

**Comment by andrewdavidwong** [comment]
Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this does not appear to be suitable for `qubes-issues`. We ask that you please send this to the `qubes-users` [mailing list](https://www.qubes-os.org/support/) instead. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a brief comment explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.
