### ISSUE TITLE
Protecting a sensitive qube as a mitigation in case of physical attacks like device theft

### ISSUE THREAD

**Issue by rugk** [QubesOS/qubes-issues#5070]
<sub>When I say "offline attack", I mostly just mean physical attacks here. Sorry.</sub>

## The problem you're addressing (if any)

Short:
**User story:** As a user, I do may want to protect a specific qube, so I have some protection/mitigation against offline attacks when the device is powered-on. (i.e. device theft)

Longer explanation below.

### Example attack

Scenario: several qubes, one qube with "live-threatening data" (you can imagine scenarios)

**Device is unlocked**!

* **device theft:** an attacker gets access to the device when it is unlocked and can access all qubes. No isolation helps here.
  This is quite reasonable, because many, many people just standby there. And without https://github.com/QubesOS/qubes-issues/issues/2890 there is only one screen-lock that protects everything.
  On the other hand, I know, when your device is decrypted/in unlocked state, they could dump the RAM data or so even. But either consider them not so advanced or that they just don't have the time (see item below)…
* **temporary device access:** an attacker gets access to the unlocked device, but only temporary. You are away for a short time for toilet etc.

BTW: Instead of having an unlocked device, the same works if the attacker managed to catch your screen lock password ([shoulder-surfing](https://en.wikipedia.org/wiki/Shoulder_surfing_(computer_security))).

### Problem

You may have different **risk categories** on your device. As indicated above, this may go up until "live-threatening data".
Now, with Qubes you can already encrypt everything and isolate these on your device, which is good. However, this only works for attackers _inside_ of your device.

So one of the attackers presented above only needs one password or one minute having your device unlocked to get access to **all your data**.

This is not separated enough! It would be better, if the same way you can manage if your Qube is compromised by software (malware), you can also manage "high-risk" Qubes that have an additional protection against offline attackers.

### Actually, on a standard Linux desktop…

So now the crazy thing: actually, on a standard Linux desktop, you can very well do that already. **With different users!**

How it works:
* you have an restricted lock screen (gdm or so) with different accounts and different passwords
* you can choose one that unlocks only that part of your data/user environment
* you can switch between different ones, and they are locked separately (screen lock)

**Advantages:**
* You can choose what "users" ("risk categories") you use right now.
* You can choose not to enter that password for your high-risk VM in an potentially dangerous/hostile environment, 
* Thus, even if your device was snatched away by a thief, you know they could at least not access all data, at least your "high-risk" category would be safe.

Thus the whole thing is "only" **risk mitigation**. You are very certainly already in a bad situation, but with this feature you could prevent the worst. As said, it lets you manage your risk.

## Describe the solution you'd like
_If you have something in mind, a clear and concise description of what you want to happen. If you don't have something in mind, indicate as much._

So I do not have very concrete ideas, but here are some:

* porting the "Linux users" thing from above: just "password-protect" a Qube. This is then like a "lock screen" for each Qube. Unless you enter the password, you cannot use it.

**Note:** Obviously, this is can be circumvented when you dump the RAM or so, as it is only a screen lock and no encryption.

**Reasoning:** However, even a simple screen-lock like feature (when users really can do nothing else to get into a locked Qube) would IMHO help very much in the use case. E.g.:
* consider the temporary attacker: They cannot easily dump your whole RAM when you are away. However, currently, if they know the password they can take a quick look into the qube and see what they've wanted. (depending on the case, it may not be needed to copy any data, even)
* also considering not so sophisticated attackers: referring [xckd's famous "crypto nerd's" comic](https://www.xkcd.com/538/), actually thinking about RAM dumps may be thought well too sophisticated for most attacks/attackers. On the other hand, of course, if they torture you, there is also nothing this helps against.
  **However**, we were considering device theft, i.e. someone just overthrows you while you were doing something (i.e. snatches that device). They may not be technically advanced, but they have access to everything then – despite your use of a super-secure distro.
  You currently cannot limit what gets exposed when your device is Laptop or similar is taken away…

#### other idea

* alternative: https://github.com/QubesOS/qubes-issues/issues/1293, this would then also cover the more sophisticated attacks like RAM dumping. I.e. when your VM is not used, then it is secure.
  As said, however, even a simple screen lock as **every usual Linux distro** (with multiplem accounts) has it, would already help very much. Even usual Linux distros cover the whole threat model/attack scenario quite well.
  Of course, in Qubes OS case it does not have to be, technically, a screen lock, but just some kind of "Qube/VM lock/unlock". 

**Where is the value to a user, and who might that user be?**
To summarize: Protecting different VMs in different ways to mitigate the impact that happens in case of offline attacks, when the device is powered-on.

Or shorter: Security by isolation is missing for offline attacks in Qubes. 

## Describe alternatives you've considered

* use different devices with multiple Qubes (or even "standard Linux") installations, but this cannot be our aim as a distro. Depending on how much you need or space, money etc you have, this is limited by physical capacity, weight, money etc.
* you can built your own thing by using encrypted data containers or so in a VM. However, this only protects some data you put into it, is hard to use (one aim of Qubes is to make security by isolation usable, I guess, so recommending this is not really a solution). If it were integrated in Qubes, you could protect a whole working environment/space together. Also, it's way easier then to e.g. save all Firefox data in that VM, instead of trying how you properly put that into an encrypted container without leaking some data.
* use a standard Linux distro: huh, yeah. (I am sorry to say this, but…) If I am not attacked by the NSA – yes, keeping [the xkcd comic in mind again](https://www.xkcd.com/538/) – and mostly care about physical attacks/shoulder surfing, this may not be such a bad solution: I can at least separate the real important data there against such attacks…

## Additional context

I mostly wanted to describe the threat model/attack scenario/use case for this. If someone has other clever solutions to solve this that fits into Qubes OS, feel free to come up with them.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
N/A

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
* https://github.com/QubesOS/qubes-issues/issues/2890
* https://github.com/QubesOS/qubes-issues/issues/1293
* quite similar idea/use case likely: https://github.com/QubesOS/qubes-issues/issues/4444

**Comment by andrewdavidwong** [comment]
I'm tempted to close this as a duplicate of #1293, because it's not clear how the viable suggestions here differ from that issue.

The whole "porting Linux users" thing requires further explanation. Does Qubes somehow _disable_ the standard user things you can do with most Linux distros? If not, then what you're asking for isn't really porting over what already exists in standard Linux distros. Rather, you're asking for that general _concept_ to applied in a novel way to Qubes VM compartmentalization, and it's not clear why that isn't already covered by #1293.

**Comment by andrewdavidwong** [comment]
Given the lack of response indicating how this is not a [duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) of #1293, I'm now closing it as such. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.
