### ISSUE TITLE
Notify-send hangs in newer templates

### ISSUE THREAD

**Issue by tasket** [QubesOS/qubes-issues#5071]
**Qubes OS version**
R4.0
**Affected component(s) or functionality**
fedora-30
debian-10

**Brief summary**
The `notify-send` command hangs for nearly a minute without displaying a message.

**To Reproduce**
In a domU shell, run `notify-send HELLO`

**Expected behavior**
Message is displayed in a popup window and command returns in a short period of time.

**Actual behavior**
There is a 50sec delay and no message display.

**Additional context**
Log from debian-10:
```
Jun 02 14:20:28 personal-net dbus-daemon[896]: [session uid=1000 pid=896] Activating service name='org.freedesktop.Notifications' requested by ':1.25' (uid=1000 pid=2114 comm="notify-send HI ")
Jun 02 14:21:28 personal-net org.freedesktop.Notifications[896]: org.kde.knotifications: WaitForName: Service was not registered within timeout
Jun 02 14:21:28 personal-net dbus-daemon[896]: [session uid=1000 pid=896] Activated service 'org.freedesktop.Notifications' failed: Process org.freedesktop.Notifications exited with status 1
```

**Related issues**
VPN startup suffering 1min 40sec delay:
https://github.com/tasket/Qubes-vpn-support/issues/40

**Comment by tasket** [comment]
I tried installing mate-notification-daemon as suggested in issue #4098 but it didn't help.

**Comment by marmarek** [comment]
I've seen this before, which was the reason for https://github.com/QubesOS/qubes-app-linux-split-gpg/commit/42ac505ed5dae09c61f9ab800a657e5b1c6d75b6. But your report proves it isn't isolated issue for that particular installation. The error message is exactly the same.

**Comment by marmarek** [comment]
Can you give some more details how to reproduce it? I've tried both fedora-30 (and -minimal) and debian-10 and it works for me there... Some specific package installed? Or maybe removed?

**Comment by tasket** [comment]
I thought it always occurred, but now I see that in my unmodified fedora-30 template, I must have Qubes-vpn-support configured to run in order to trigger it.

If I comment-out the `notify-send` lines in qubes-vpn-ns and qubes-vpn-setup and restart the vm, the vpn client will start normally and I can use `notify-send` from the cli with no hanging. So running `notify-send` during startup from my service scripts is triggering the problem on fedora-30.

The debian-10 template is upgraded from 9 and heavily modified, with the most significant change being Gnome replaced with KDE. Here the `notify-send` command will hang even with all extra Qubes services disabled, and regardless of vm class. Its possible that something else is trying to use `notify-send` or something similar during startup. Perhaps later I'll try installing the pre-release debian-10 template.

**Comment by tasket** [comment]
Here is a log from fedora-30:
```
Jun 04 17:59:41 VPN2 systemd[571]: Starting D-Bus User Message Bus...
Jun 04 17:59:41 VPN2 dbus-broker-launch[772]: Service file '/usr/share/dbus-1/services/org.freedesktop.mate.Notifications.service' is n
ot named after the D-Bus name 'org.freedesktop.Notifications'.
Jun 04 17:59:41 VPN2 dbus-broker-launch[772]: Service file '/usr/share/dbus-1/services/org.gnome.evolution.dataserver.UserPrompter.serv
ice' is not named after the D-Bus name 'org.gnome.evolution.dataserver.UserPrompter0'.
Jun 04 17:59:41 VPN2 dbus-broker-launch[772]: Service file '/usr/share/dbus-1/services/org.gnome.evolution.dataserver.AddressBook.servi
ce' is not named after the D-Bus name 'org.gnome.evolution.dataserver.AddressBook9'.
Jun 04 17:59:41 VPN2 dbus-broker-launch[772]: Service file '/usr/share/dbus-1/services/org.gnome.evolution.dataserver.Calendar.service'
 is not named after the D-Bus name 'org.gnome.evolution.dataserver.Calendar7'.
Jun 04 17:59:41 VPN2 dbus-broker-launch[772]: Service file '/usr/share/dbus-1/services/org.gnome.evolution.dataserver.Sources.service' 
is not named after the D-Bus name 'org.gnome.evolution.dataserver.Sources5'.
Jun 04 17:59:41 VPN2 dbus-broker-launch[772]: Policy to allow eavesdropping in /usr/share/dbus-1/session.conf +31: Eavesdropping is dep
recated and ignored
Jun 04 17:59:41 VPN2 dbus-broker-launch[772]: Policy to allow eavesdropping in /usr/share/dbus-1/session.conf +33: Eavesdropping is dep
recated and ignored
Jun 04 17:59:41 VPN2 systemd[571]: Started D-Bus User Message Bus.
Jun 04 17:59:41 VPN2 dbus-broker-lau[772]: Ready
Jun 04 17:59:41 VPN2 systemd[571]: Created slice dbus\x2d:1.2\x2dorg.freedesktop.Notifications.slice.
Jun 04 17:59:41 VPN2 systemd[571]: Started dbus-:1.2-org.freedesktop.Notifications@0.service.
Jun 04 17:59:41 VPN2 mate-notification-daemon[784]: Unable to init server: Could not connect: Connection refused
Jun 04 17:59:41 VPN2 mate-notificati[784]: cannot open display: 
Jun 04 17:59:41 VPN2 systemd[571]: dbus-:1.2-org.freedesktop.Notifications@0.service: Succeeded.
Jun 04 17:59:42 VPN2 qubes-gui[424]: Ok, somebody connected.
Jun 04 17:59:42 VPN2 qubes-gui[424]: Connection to local X server established.
```

Notice the X server starts after the 'notifications' messages. When this happens, notify-send cannot be used for a very long time (if it works at all).

**Comment by tasket** [comment]
FYI, a debian-9-to-10 template I upgraded without KDE has no `notify-send` hanging problem.

**Comment by tasket** [comment]
A recent Fedora 30 update appears to have fixed the issue.

**Comment by fepitre** [comment]
I'm still having the issue with updated Fedora 30. Any try of 'notify-send' is hanging.

**Comment by marmarek** [comment]
Do you see similar messages in journalctl?

**Comment by fepitre** [comment]
I'm not seeing anything. Doing 'journalctl -f' does not pop anything while launching 'notify-send test'.

**Comment by marmarek** [comment]
Wait until timeout

**Comment by fepitre** [comment]
Yes...nothing.

**Comment by marmarek** [comment]
Can you provide a full list of package versions? (`rpm -qa`, please attach as file, not paste)

**Comment by fepitre** [comment]
I can do one with working and one with not

**Comment by fepitre** [comment]
Here is the package list (not exactly same template. The NOK have less packages)
[ok.txt](https://github.com/QubesOS/qubes-issues/files/3439483/ok.txt)
[nok.txt](https://github.com/QubesOS/qubes-issues/files/3439484/nok.txt)

**Comment by marmarek** [comment]
Looks very similar. The broken one has slightly newer packages and also few more gnome related ones. But that shouldn't be relevant, as the only notification daemon installed is `mate-notification-daemon`. Is it running?
Maybe it's about access to dbus? Is `DBUS_SESSION_BUSS_ADDRESS` env variable set to `unix:path=/run/user/1000/bus`? Or maybe `DISPLAY` variable is missing in dbus-launched processes (see `/proc/PID/environ` where `PID` is a pid of `dbus-broker-launch --scope user` process). I suspect it may be related to dbus-daemon -> dbus-broker change in fc30.

**Comment by fepitre** [comment]
On the working one DBUS_SESSION_BUS_ADDRESS in env and also in env of the ```dbus-broker-launch --scope user``` whereas it's not in the non working one.

**Comment by marmarek** [comment]
Maybe it's not enabled in the user session? Check `systemctl --user status dbus-broker`.
Are those templates based on the same build (template package version), or a different one? Or maybe upgraded in place from previous Fedora version?

**Comment by tasket** [comment]
FYI, its still working OK for me in fedora-30.

Do you have any services added to fedora-30... ones that would utilize `notify-send`? When I was experiencing the problem, `notify-send` in cli worked properly if there was no service that used it at startup. But when I enabled the service, it would hang in the cli.

**Comment by fepitre** [comment]
In fact, I got this problem when enabling qubes-tunnel service...

**Comment by fepitre** [comment]
According to discussion with @marmarek, this could lead to inconsistency when using Qubes as a server. Requiring direct gui tools is not a good idea because if there is no gui, notify-send will always fail whereas it's a great service to be used into a server of course. Related issues https://github.com/QubesOS/qubes-issues/issues/889

**Comment by tasket** [comment]
Then there's an inconsistency in Qubes' messaging about guis. Maybe its a good idea to make notify-send optional in a vpn client, but this is still about bugs in fedora-30. 

notify-send is present even in the minimal templates, but doesn't work in an _unmodified_ fedora-30-minimal. There is no hang, but no message either and the return code is 0.

**Comment by tasket** [comment]
On reflection, I think the best way to handle this would be for Qubes to add a notification function to '/usr/lib/qubes/init/functions' that interfaces with libnotify or whichever conveyance will be chosen in the future.

**Comment by marmarek** [comment]
libnotify (or rather - [`org.freedesktop.Notifications`](https://developer.gnome.org/notification-spec/)) _is_ a standard protocol for notification. If we'll add qubes-specific mechanism, it will be plugged into it.

**Comment by marmarek** [comment]
In short: there are two issues:
1. when `notify-send` is called before X server is started (for example from rc.local), notification daemon will fail to start and `notify-send` would timeout (60s or such) - this is an issue with how we use `notify-send`
2. If notification daemon failed to start initially, dbus-broker (new dbus implementation) will not retry (https://github.com/bus1/dbus-broker/issues/209)

To solve the first one, we could add appropriate service ordering to ensure rc.local (or other relevant service) is called only when GUI is running. But IMO that is undesired, as some of it genuinely _should_ start before. In some cases, maybe even running completely without a GUI (VPN case is a good example here). Until notification service failure detection is fixed, a workaround could be avoiding running `notify-send` if GUI isn't started yet. For example by looking for `DISPLAY` environment in user session:
```
systemctl --user show-environment |grep -q ^DISPLAY= && notify-send ...
```

**Comment by marmarek** [comment]
This happens for gnome-terminal too (gnome-terminal-server fails to start).

**Comment by sidhussmann** [comment]
For anyone still having this problem on `debian-minimal`-based templates: What solved it for me was to install `libnotify-bin` and `mate-notification-daemon`.

**Comment by andrewdavidwong** [comment]
Added `diagnosed` label based on https://github.com/QubesOS/qubes-issues/issues/5071#issuecomment-520189012. (If that's not correct, please remove or comment.)

**Comment by straussmaus** [comment]
Seems connected to VPN notifications failing: https://github.com/QubesOS/qubes-issues/issues/5139

**Comment by straussmaus** [comment]
An important note is that the affected templates for https://github.com/QubesOS/qubes-issues/issues/5139 were:

Fedora 30
Fedora 31
Fedora 32
Debian 9

NOT

Debian 10.  Debian 10 worked (the notification showed)

So maybe this is not related despite @marmarek 's troubleshooting suggestion.  But https://github.com/QubesOS/qubes-issues/issues/5139 will be easier to circle back to and diagnore once this is fixed.
