### ISSUE TITLE
Rework https://www.qubes-os.org/doc/bind-dirs/

### ISSUE THREAD

**Issue by noseshimself** [QubesOS/qubes-issues#5078]
**The problem you're addressing (if any)**
The tutorial regarding the use of bind-dirs is not aligned with the current environment anymore.

**Describe the solution you'd like**
Someone who knows how it is working should update it (but keep in mind that someone not knowing the internals will have to use it.

**Where is the value to a user, and who might that user be?**
Right now the information there is of limited use. It is confusing (as it is not explicitly demonstrating WHERE to put the directory to be linked to) and incorrect (at least on my fedora template `/usr/lib/qubes/bind-dirs.sh`  is at `/usr/lib/qubes/init/bind-dirs.sh` now and executing it results in 

```
# /usr/lib/qubes/init/bind-dirs.sh 
/var/spool/cron is not a symlink
/var/spool/cron is neither a directory nor a file and the path does not exist below /rw, skipping.
```
when called (ok, that's worth opening an issue, I guess).

**Additional context**
_Add any other context or screenshots about the feature request here._

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
https://www.qubes-os.org/doc/bind-dirs/

**Comment by unman** [comment]
>  WHERE to put the directory to be linked to

This is a misunderstanding. bind-dirs makes _existing_ directories persistent. One does not (generally) put a directory anywhere.

> incorrect (at least on my fedora template /usr/lib/qubes/bind-dirs.sh is at /usr/lib/qubes/init/bind-dirs.sh

True

> executing it results in error

This isn't an error, at least not in bind-dirs - check if you have  /var/spool/cron.

**Comment by unman** [comment]
@noseshimself Does [this reworking](https://github.com/QubesOS/qubes-doc/pull/827) help?

**Comment by unman** [comment]
@andrewdavidwong In the absence of any reply, I believe this can be closed after the merge of https://github.com/QubesOS/qubes-doc/pull/827
