### ISSUE TITLE
Copying files to external media is slow

### ISSUE THREAD

**Issue by AlxHnr** [QubesOS/qubes-issues#5086]
**Qubes OS version**
Qubes Version: `Qubes release 4.0 (R4.0)`
Dom0 Kernel: `4.19.43-1.pvops.qubes.x86_64`
Xen Version: `4.8.5-6.fc25`
VM OS: `Fedora 29`
VM Kernel: `4.19.43-1.pvops.qubes.x86_64`

**Affected component(s) or functionality**
Using external storage media.

**Brief summary**
I attached two external HDDs to a VM and copied a large file from one drive to another. This went surprisingly slow (41 MB/s).

**To Reproduce**
* Attach two external harddrives (see _Additional context_) to VM
* Mount both of them using nautilus
* Copy a big file from A to B

**Expected behavior**
The bandwidth of the underlying storage media is saturated.

**Actual behavior**
Only a fraction of the external devices bandwidth is utilized. E.g. 62 MB/s.

**Screenshots**
none

**Additional context**
Each harddrive contains a twofish-xts-plain64 volume with an xfs partition on top. All twofish-related modules are loaded in the VM and my machine is fast enough to handle it. Running `cryptsetup benchmark` in the VM yields 242.6 MiB/s for twofish-xts-plain64.

**Solutions you've tried**
I tried copying via Nautilus, the `cp` command and `dd`. They all had the same issue.

At first I assumed that Qubes/Xen was to blame for the overhead and tried tuning `xen_blkfront.max`, `max_sectors_kb` and the like, without any success.

Assigning more cores to the VM helped. The copying speed went up to 72 MB/s. It may be an improvement, but doesn't solve the issue and is still way to slow.

After experimenting with various `dd` flags on different filesystems, I came to the conclusion that the default mounting options are to blame for the slowdown. Right now my only solution is to either copy files using `dd` exclusively, or to tweak /etc/fstab in all template VMs until it seems to work. I would prefer to have defaults that "just work".

The following benchmarks have been created using an external HDD and the `dd` command, dropping caches before each test. These numbers can be reproduced reliably.

### Reference benchmarks

Reading/Writing from/to the attached device directly is as fast as the HDD permits:

```
$ sudo dd if=/dev/zero of=/dev/xvdi status=progress bs=1M count=10240
10719592448 bytes (11 GB, 10 GiB) copied, 89 s, 120 MB/s
10240+0 records in
10240+0 records out
10737418240 bytes (11 GB, 10 GiB) copied, 92.7988 s, 116 MB/s
```

Writing to a plain xfs partition is just as fast:

```
$ sudo dd if=/dev/zero of=/media/file status=progress bs=1M count=10240
10736369664 bytes (11 GB, 10 GiB) copied, 90 s, 119 MB/s
10240+0 records in
10240+0 records out
10737418240 bytes (11 GB, 10 GiB) copied, 90.0066 s, 119 MB/s
```

### Twofish + XFS

I created a Luks device using: `sudo cryptsetup luksFormat /dev/xvdi -c twofish-xts-plain -s 512`. XFS is used on top of that. Here are the results when reading a large file:

```
$ sudo dd if=/media/Qubes-R4.0-x86_64.iso of=/dev/null status=progress
4548313600 bytes (4.5 GB, 4.2 GiB) copied, 69 s, 65.9 MB/s
8947712+0 records in
8947712+0 records out
4581228544 bytes (4.6 GB, 4.3 GiB) copied, 69.584 s, 65.8 MB/s
```

Reading the same file with `bs=8M iflag=direct` leads to a significant improvement:

```
$ sudo dd if=/media/Qubes-R4.0-x86_64.iso of=/dev/null status=progress bs=8M iflag=direct
4529848320 bytes (4.5 GB, 4.2 GiB) copied, 39 s, 116 MB/s
546+1 records in
546+1 records out
4581228544 bytes (4.6 GB, 4.3 GiB) copied, 39.4806 s, 116 MB/s
```

Copying files between the two devices has the same issue, which can be fixed by passing `bs=8M iflag=direct`:

```
$ sudo dd if=/run/media/user/Device/Qubes-R4.0-x86_64.iso of=/media/file status=progress bs=8M iflag=direct
4504682496 bytes (4.5 GB, 4.2 GiB) copied, 40 s, 112 MB/s
546+1 records in
546+1 records out
4581228544 bytes (4.6 GB, 4.3 GiB) copied, 40.7593 s, 112 MB/s
```

Mount options:

```
/dev/mapper/a on /media type xfs (rw,relatime,attr2,inode64,noquota)
/dev/mapper/b on /run/media/user/Device type xfs (rw,nosuid,nodev,relatime,attr2,inode64,noquota,uhelper=udisks2)
```

### NTFS

Mount options:

```
gvfsd-fuse on /run/user/1000/gvfs type fuse.gvfsd-fuse (rw,nosuid,nodev,relatime,user_id=1000,group_id=1000)
fusectl on /sys/fs/fuse/connections type fusectl (rw,relatime)
/dev/fuse on /run/user/1000/doc type fuse (rw,nosuid,nodev,relatime,user_id=1000,group_id=1000)
/dev/xvdi on /media type fuseblk (rw,relatime,user_id=0,group_id=0,allow_other,blksize=4096)
```

Writing data:

```
$ sudo dd if=/dev/zero of=/media/file status=progress bs=1M count=10240
10734272512 bytes (11 GB, 10 GiB) copied, 250 s, 42.9 MB/s
10240+0 records in
10240+0 records out
10737418240 bytes (11 GB, 10 GiB) copied, 250.095 s, 42.9 MB/s
```

Writing data with `oflag=direct`:

```
$ sudo dd if=/dev/zero of=/media/file status=progress bs=1M count=10240 oflag=direct
10647240704 bytes (11 GB, 9.9 GiB) copied, 95 s, 112 MB/s
10240+0 records in
10240+0 records out
10737418240 bytes (11 GB, 10 GiB) copied, 95.8218 s, 112 MB/s
```

### AES + XFS

When using AES volumes (cryptsetup defaults) with XFS on top, the results are great and comparable to the reference benchmark. I don't know why AES works so well out of the box. Maybe the point at which it slows down/saturates is much higher. I don't have a fast external SSD to test beyond 120 MB/s.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
none

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
none

**Comment by AlxHnr** [comment]
### Addition to AES + XFS

While it is faster than plain NTFS or Twofish+XFS with the default mounting flags, it still doesn't use the full bandwith of the underlying devices. I've done another benchmark, copying a file between two devices. Both use _aes-xts-plain64_ with an XTS key size of 256 bit and XFS on top:

```
$ sudo dd if=/media/a/Qubes-R4.0-x86_64.iso of=/media/b/file status=progress
4564102656 bytes (4.6 GB, 4.3 GiB) copied, 51 s, 89.5 MB/s
8947712+0 records in
8947712+0 records out
4581228544 bytes (4.6 GB, 4.3 GiB) copied, 51.2027 s, 89.5 MB/s
```
This is about 25MB/s less than what the devices are capable of. Running `cryptsetup benchmark` in the same VM tells me that my machine can easily push 1GB/s or more for all supported AES variants.

**Comment by awokd** [comment]
@alxhnr FWIW, I noticed slow copy speeds on Debian on bare-metal too. Not sure this is specific to Qubes?

**Comment by AlxHnr** [comment]
I'm pretty sure if this would be the case on most mainstream Linux distributions, a lot more people would complain. I'm curious if other people can reproduce it on their Qubes OS setup.

**Comment by brendanhoar** [comment]
If these are usb 3 devices, have you tried xl sched-credit to increase the scheduling weight of the device domain’s associated stub domain?

**Comment by AlxHnr** [comment]
These are USB 3 devices. `xl shed-credit` fails with `command not implemented`. It doesn't matter if I run it inside dom0 or any other Qube, using sudo or not.

**Comment by awokd** [comment]
> `xl shed-credit`

Believe it is `xl sched-credit`. Mine are USB3 devices as well so will
try that next backup, but even bare metal Debian on same hardware I was
seeing around 50% throughput on USB3 devices with LUKS.

**Comment by brendanhoar** [comment]
Yeah, it's "sched" not "shed".

e.g.
```[admin@dom0 ~]$ xl sched-credit
Cpupool Pool-0: tslice=30ms ratelimit=1000us
Name                                ID Weight  Cap
Domain-0                             0   2000    0
sys-usb                              1   1000    0
sys-usb-dm                           2    **256**    0
[admin@dom0 ~]$ xl sched-credit -d sys-usb-dm -w 1000
[admin@dom0 ~]$ xl sched-credit
Cpupool Pool-0: tslice=30ms ratelimit=1000us
Name                                ID Weight  Cap
Domain-0                             0   2000    0
sys-usb                              1   1000    0
sys-usb-dm                           2   **1000**    0
[admin@dom0 ~]$ 
```

**Comment by AlxHnr** [comment]
> Yeah, it's "sched" not "shed".

You're right, that was a typo.

Unfortunately I don't have spare HDDs laying around to rerun those tests on a newer Qubes OS :slightly_frowning_face:
