### ISSUE TITLE
kernel-qubes-vm from current-testing breaks VM boot

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#5087]
### Qubes OS version:

`Qubes release 4.0 (R4.0)`

### Affected component(s) or functionality:

dom0-provided VM kernels

---

### Steps to reproduce the behavior:

Install `kernel-qubes-vm` from `updates-testing`

### Expected or desired behavior:

VMs boot normally

### Actual behavior:

VMs do not boot.  Logs reveal that `xenfs` is not recognized by the kernel.

### General notes:

Switching to the previously-installed kernel works, even if the new kernel remains installed.

---

**Comment by marmarek** [comment]
kernel-qubes-vm, or kernel-latest-qubes-vm? Can you confirm exact version?

**Comment by marmarek** [comment]
both

**Comment by jpouellet** [comment]
xref: https://github.com/QubesOS/updates-status/issues/1136#issuecomment-501855316
