### ISSUE TITLE
Nouveau/Intel issues with external monitors with kernels 4.19 and 5.1

### ISSUE THREAD

**Issue by iprid23** [QubesOS/qubes-issues#5092]
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
Booting,Plymouth password screen(LUKS), Resume from suspend

**Brief summary**
With kernels above 4.14, I've experienced the following issues:
Hang on boot if external monitor is attached.
Cannot resume from suspend or if I am able to,
nouveau is broken and unusable until restart.

**To Reproduce**
1. Get a laptop with intel/nouveau with some video inputs wired to the nvidia gpu
2. Attach a monitor to the nvidia gpu
3. Boot kernel 4.19 or 5.1
4. Try to suspend and resume

**Expected behavior**
You should be able to boot, suspend and then resume.

**Actual behavior**
Sometimes the boot will hang. Plymouth could hang. Pressing escape during password input may make it hang. If you manage to input your password, try suspending. Upon resume the monitor connected to the nvidia gpu will stop working. The nouveau kernel module will stop working until restart.

**Additional context**
_Add any other context about the problem here._

**Solutions you've tried**
Attaching monitors to the Intel gpu works fine. Removing rhgb can at least help you not get stuck with Plymouth.
I've tried nouveau.noaccel=1,nouveau.nofbaccel=1. Other things start to crash with this. I am being constantly logged out from lightdm. It's like lightdm is crashing non-stop.
Going back to 4.14 fixes everything.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
https://bugs.freedesktop.org/show_bug.cgi?id=105319
https://bugzilla.redhat.com/show_bug.cgi?id=1618906

**Comment by iprid23** [comment]
Confirming nouveau crash on resume from suspend with latest kernel 5.1.7-2.
```
[ 1056.259217] nouveau 0000:01:00.0: DRM: core notifier timeout
[ 1058.262963] nouveau 0000:01:00.0: DRM: core notifier timeout
[ 1060.262997] nouveau 0000:01:00.0: DRM: base-0: timeout
[ 1062.264809] nouveau 0000:01:00.0: DRM: core notifier timeout
```

**Comment by marmarek** [comment]
Try adding `iommu=no-igfx` to Xen command line (not Linux command line).

**Comment by iprid23** [comment]
@marmarek, thanks for the suggestion, but I already have it. This is a nouveau bug and is reproduced even without Xen as I have linked their issues. Hopefully it will get fixed in kernels above 5.1.7. So far the only notable commt I saw in the nouveau tree is this:
```
drm/nouveau/i2c: Disable i2c bus access after ->fini()
commit 342406e4fbba9a174125fbfe6aeac3d64ef90f76 upstream.
```
But it doesn't seem like it has anything to do with the core notifier timeout errors...

**Comment by iprid23** [comment]
Will write here when I test new kernels, though the bug is still listed here:
https://bugs.freedesktop.org/show_bug.cgi?id=105319
https://bugzilla.redhat.com/show_bug.cgi?id=1618906
as NEW
Also I don't see any fixes in the kernel tree for 5.1.

**Comment by iprid23** [comment]
@marmarek Will you continue to provide 4.14 kernels, because I've read that 4.0.2 was released with 4.19 but the nouveau bug I've posted a linked to above is still unresolved, meaning Nouveau is broken for kernels above 4.14.

**Comment by marmarek** [comment]
Yes, 4.14 kernel is still available and frequently updated in R4.0 repositories. To ease updates (`dnf` doesn't like forcing specific package version when newer is available) it's available as `kernel-414` package.

**Comment by marmarek** [comment]
There are multiple fixed for nouveau driver in 5.6 kernel. You can try it by installing kernel-latest package from current-testing repository.

**Comment by eug48** [comment]
Good news - my GeForce GTX 1060 Mobile (GP106BM) is now booting with nouveau on this kernel 5.6 and an external monitor is working. nouveau had not booted since 4.14. Thanks for all your work @marmarek !

**Comment by iprid** [comment]
I see that the current kernel is 5.10.16-1. Has anyone tested that? I am still on 4.14, but I will compile 5.10 and try it because of QSB-064.

Will write here when I have results.

CC:
@eug48 
@marmarek

**Comment by iprid** [comment]
Actually I've compiled 4.19.176. Nouveau works fine now, I can suspend and resume. Though I had other issues with xen.cfg lacking the boot entry for the newly installed kernel. So I had to add it manually - https://github.com/QubesOS/qubes-issues/issues/6413

So feel free to close this ticket with resolved, and thanks for notifying us that it was fixed @marmarek

**Comment by marmarek** [comment]
FWIW, we still build 4.19.x kernels (for R4.0), you just need to convince dnf/qubes-dom0-update to use that version, not the latest one. I'll soon switch the package name to `kernel-4.19`, which should make it easier.

**Comment by iprid** [comment]
4.19.x is fine. As for 5.x.x kernels, is there any benefit to using those(besides support for newer hardware)?
