### ISSUE TITLE
Add noresume to dom0 kernel linux command line to reduce boot time by 20-30s

### ISSUE THREAD

**Issue by brendanhoar** [QubesOS/qubes-issues#5095]
**The problem you're addressing (if any)**
Qubes boot takes an inexplicably long time for no good reason.

**Describe the solution you'd like**
Add "noresume" to the dom0 linux kernel command line to trim 20-30 seconds from the boot time.

As Qubes does not currently support hibernation of xen/dom0, and "noresume" bypasses a (futile?) attempt to find the swap partition/file which would be used by hibernation resume, and this search  takes 20-30s, and as this is already being used in non dom0 VMs...it could be a quick win.

**Where is the value to a user, and who might that user be?**
Any user who, upon booting the system, wonders what is taking so long...

**Describe alternatives you've considered**
1. Investigating why the system is configured to look for the swap partition/file on boot to support the resume from hibernation function.

2. Waiting.........

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
Already being done inside other non-dom0 VMs: https://github.com/QubesOS/qubes-core-agent-linux/commit/6c965a6

Brendan

**Comment by marmarek** [comment]
While generally this may a good idea, I wonder how specifically the current state is a problem. Maybe something specific to your setup?
By default root and swap partitions are within the same encrypted LUKS container, so when root become available (which you need to start the system anyway), swap is also there, so there should be no additional wait. Also, I don't see `resume=` option set anywhere (neither real kernel command line, nor dracut internal configuration, even generated one). Also, by inspecting boot log I don't see any significant delay related to resume. Just after entering LUKS passphrase I see 10s delay caused by LVM scan. But the very same second it completes, root partition is mounted and initramfs is done.

**Comment by brendanhoar** [comment]
I do not know the cause. Various non-qubes threads online also fail to properly diagnose the issue, but find that noresume resolves it. A bit cargo-cultish, sure.

My system was installed w/ default anaconda settings. Without “noresume“ a) systemd-analyze blame shows a large delay around cryptsetup and b) a large delay between two entries in dmesg.

B

**Comment by marmarek** [comment]
Don't you see the same cryptsetup delay with noresume too? It waits for you to enter the passphrase, so the delay is justifiable.

**Comment by brendanhoar** [comment]
I’ll run through some scenarios tonight. Thanks Marek.

**Comment by unman** [comment]
I've tested this on a number of machines, with various configurations. In no case does "noresume" cut the boot time significantly, (if at all.)
All these are single disk - would that make any difference?

**Comment by brendanhoar** [comment]
Marek - I think you’re right that I let some other unrelated delay mislead me. I can no longer reproduce a boot time improvement.

Let’s close this issue, call it user error (mea culpa) and I’ll dive further into the boot time concerns with reproducible experiments on identical hardware units with different settings next weekend.

**Comment by unman** [comment]
> Already being done inside other non-dom0 VMs: QubesOS/qubes-core-agent-linux@6c965a6

I have to say that I find this a non problem - that is, booting Debian HVMs (was standalone meant?) without noresume did not, in my experience, have a 20-30second boot delay which needed fixing - and ineffective.
I've just tested this and confirmed that removing the "noresume" parameter does _not_ result in a long delay in booting a standaloneVM

**Comment by brendanhoar** [comment]
Hi @unman:

Use of 'noresume' appears to be a band-aid related to location/visibility the swap partition/file during boot and the linux hibernation feature. So changes that impact this location/visibility (e.g. use of luks, use of encrypted /boot, use of lvm/dm, etc.) may impact whether this band-aid has anything to address.

I would not be surprised if noresume assisted R3.x templates w/r/t boot time, but changes in R4 made the band-aid moot.

B
