### ISSUE TITLE
Cannot install latest 4.14.119-2 kernel with qubes-dom0-update

### ISSUE THREAD

**Issue by iprid23** [QubesOS/qubes-issues#5100]
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
kernel, kernel-qubes-vm

**Brief summary**
Upon trying to install the newest 4.14 kernel, I get a message that it will be skipped

**To Reproduce**
_Steps to reproduce the behavior:_
_1. sudo qubes-dom0-update kernel kernel-qubes-vm

**Expected behavior**
Kernel 4.14.119-2 is installed

**Actual behavior**
Nothing is installed:
Package kernel-1000:4.14.74-1.pvops.qubes.x86_64 is already installed, skipping.
Package kernel-1000:4.14.103-1.pvops.qubes.x86_64 is already installed, skipping.
Package kernel-1000:4.19.43-1.pvops.qubes.x86_64 is already installed, skipping.
Package kernel-latest-1000:5.0.9-1.pvops.qubes.x86_64 is already installed, skipping.
Package kernel-latest-1000:5.1.2-1.pvops.qubes.x86_64 is already installed, skipping.
Package kernel-qubes-vm-1000:4.14.74-1.pvops.qubes.x86_64 is already installed, skipping.
Package kernel-qubes-vm-1000:4.14.103-1.pvops.qubes.x86_64 is already installed, skipping.
Package kernel-qubes-vm-1000:4.19.43-1.pvops.qubes.x86_64 is already installed, skipping.
Dependencies resolved.
Nothing to do.
Complete!

**Additional context**
Previously I've installed 4.19.* from unstable. Then I've installed 5.0.* and 5.1.* from latest.
After that 4.19.* was pushed to stable, so I've installed it.But since it had issues it was pulled back. So I went back to using 4.14.103-1

**Solutions you've tried**
Perhaps uninstalling 4.19 will fix the issue and allow me to install 4.14.119-2 since maybe it's thinking I am trying to install an older version. If someone confirms, I will test this(of course will backup first).

**Comment by marmarek** [comment]
> Perhaps uninstalling 4.19 will fix the issue and allow me to install 4.14.119-2 since maybe it's thinking I am trying to install an older version. If someone confirms, I will test this(of course will backup first).

Yes, try this.

Generally yum/dnf is quite picky about versions and installing not-the-latest version (while keeping newer versions installed) is highly non trivial thing. This is why kernel-latest has different name.

**Comment by iprid23** [comment]
Thanks, will try uninstalling 4.19. In the meantime I've tried the dnf downgrade to no avail:

sudo dnf downgrade kernel-4.14.119-2 kernel-qubes-vm-4.14.119-2
```
Qubes OS Repository for Dom0                                                                                                                                   63 MB/s | 210 kB     00:00    
Package kernel of lowest version already installed, cannot downgrade it.
Package kernel-qubes-vm of lowest version already installed, cannot downgrade it.
Error: Nothing to do.
```

**Comment by marmarek** [comment]
Sure, you can get it [here](https://github.com/QubesOS/updates-status/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+kernel+r4.0):
 linux-kernel-latest v5.1.7-2 (r4.0) r4.0-dom0-cur-test
 linux-kernel-4-19 v4.19.48-2 (r4.0) r4.0-dom0-cur-test
 linux-kernel v4.14.123-1 (r4.0) r4.0-dom0-cur-test

**Comment by marmarek** [comment]
(unstable is rarely used, only for really experimenting stuff, use current-testing)

**Comment by iprid23** [comment]
Thanks. Will test 5.1.7-2 and see how that goes. Hopefully the nouveau issues will be fixed so I can close my other issue. Recently there have been many problem with nouveau in 4.15+.

**Comment by andrewdavidwong** [comment]
Closing as "not an issue." If you believe this is a mistake, please leave a comment, and we'll be happy to take another look. Thank you.
