### ISSUE TITLE
Nouveau video tearing

### ISSUE THREAD

**Issue by iprid23** [QubesOS/qubes-issues#5104]
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
nouveau, Xorg

**Brief summary**
When playing a video from a VM, there is tearing on the monitors connected to an Nvidia GPU when running with the Nouveau driver. This happens in any configuration:

1. Nvidia GPU is primary GPU, Intel GPU uses PRIME
2. Intel GPU is primary gpu, Nvidia GPU uses PRIME
3. Only Nvidia GPU is enabled(Intel GPU is disabled from bios)

The Intel GPU works fine all the time and no tearing is observed when connecting screens to it.

**To Reproduce**
_Steps to reproduce the behavior:_
1. Get a laptop with an Nvidia GPU with at least one video outputs connected to the Nvidia
Note: many laptops will let you disable the Intel GPU, so if you prefer to, just do that
Note2: Nouveau does not have support for very modern GPUs, so check beforehand if it is supported here: https://nouveau.freedesktop.org/wiki/FeatureMatrix/
2. Connect a monitor to one of the ports connected to the Nvidia GPU
3. Try playing a video with a lot of horizontal movement(or just move a window really fast horizontally)

**Expected behavior**
The video should play smoothly

**Actual behavior**
Tearing is observed.

**Additional context**
The strange thing is that the tearing happens regardless of whether intel or nvidia is primary.
https://bugs.freedesktop.org/show_bug.cgi?id=103202 suggests that making nvidia the primary GPU should solve the problem but it does not.

**Solutions you've tried**
I've tried many solutions:

Switching between intel and nvidia. 

Disabling intel.

Xorg options for nouveau:
    Option "GLXVBlank" "true"
    Option "SwapLimit" "2"

ShadowFB, NoAccel lead to crashes

XFCE Compositor in Dom0

Custom compton in Dom0 or VM(bad idea to try this in VM I know but had to try)

TearFree works for the Intel graphics but does not help with the nvidia gpu

Trying to enable PRIME Synchronization(when Intel is primary, otherwise this should not be needed anyway).
xrandr --output ....  --set "PRIME Synchronization" 1

What I have not tried:
Wayland
Proprietary drivers

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
https://wiki.archlinux.org/index.php/Nouveau#Vertical_Sync
https://bugs.freedesktop.org/show_bug.cgi?id=103202
https://nouveau.freedesktop.org/wiki/

**Comment by iprid23** [comment]
Perhaps updating the Xorg driver can help:
https://cgit.freedesktop.org/nouveau/xf86-video-nouveau/ has version 1.0.16 out,
while Qubes is using 1.0.15

**Comment by marmarek** [comment]
What kernel version do you use?

**Comment by marmarek** [comment]
Lets, try with nouveau 1.0.16, I've uploaded it to unstable repository, you  can install it with:
```
sudo qubes-dom0-update --enablerepo=qubes-dom0-unstable xorg-x11-drv-nouveau
```

**Comment by iprid23** [comment]
Thanks, but so far it seems as if the problem is also with the DRM nouveau driver not having microcode for Vblanks or so. There are some workarounds for GL based stuff, but I guess the guid daemon in Dom0 does not use OpenGL to draw the windows. Apparently even the Nouveau developers are not sure of the exact cause of the tearing. Of course there's also the issue with Prime if the Nvidia card is not primary, but for tearing to not appear. 

Interestingly Intel also Tears unless using the generic modesetting Xorg DDX with a Compositor or using the Intel Xorg DDX with TearFree true.

I did some experiments with Wayland and Nvidia seems to there too, so my take on this is the DRM driver.

**Comment by ranchester2** [comment]
I had tearing when I tried to use nouveau with multiple monitors, but not in a single monitor setup (though I didn't use it like that long enough to notice if the contents themselves of guid windows were tearing).

Using the modesetting driver instead of the nouveau DDX driver, by removing xorg-x11-drv-nouveau, fixed the tearing for me (not only does the dom0 compositor not tear, but contents of guid windows too).

I am using this on a laptop where the internal display is connected to the iGPU, but I don't enable the internal display, have the NVIDIA GPU set as primary and use external monitors connected to the NVIDIA GPU.

**Comment by andrewdavidwong** [comment]
Is this still a problem in 4.1?
