### ISSUE TITLE
Release Qubes R4.0.2

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#5108]
As [discussed on qubes-devel](https://groups.google.com/d/topic/qubes-devel/lfCSltYV2ho/discussion) we should release new point release with updated templates (Fedora 30 in this case). This is a tracking for the task.

- [x] update references to included templates (installer, salt, anywhere else?)
- [x] build new ISO
- [x] test it
- [x] release (upload to mirrors, announce)

**Comment by marmarek** [comment]
@adrelanos is there any estimated schedule for Whonix 15? Does it worth delaying R4.0.2 to include it too, or better have it included in next point release?

I'd also like to build updated templates, including Whonix 14 (if that's what we should stick for now), but the build fails because `master` branch of `qubes-template-whonix` repo is already about Whonix 15. Can you create a branch for Whonix 14 build?

**Comment by unman** [comment]
buster has a release date of 6th July - it would be *really* cool if 4.0.2 included a buster template.

**Comment by adrelanos** [comment]
Probably better to build new Qubes-Whonix 15 templates. The Qubes-Whonix
15 the ones that I created a month ago or so are bit dated and still
untested.

Guestimate getting Qubes-Whonix 15 up to speed is less work than
maintenance work and rehashing Qubes-Whonix 14 in my mind.

Non-Qubes-Whonix 15 testers only version are being public tested for a
while now and work ok.

Upgraded Qubes-Whonix 14 -> Qubes-Whonix 15 are being public tested for
a while now and work ok.

So new Qubes-Whonix 15 builds seems the shorter route. Since above is
working all well, I don't expect much critical bugs requiring fixes.

The gpg key server fetching bug slows down development but fixing it in
Qubes is hard for me.

**Comment by adrelanos** [comment]
One perhaps blocker identified:
https://github.com/QubesOS/qubes-issues/issues/5111

Qubes-Whonix 15 templates tested with already existing sys-whonix / anon-whonix / workstation dvm template and working quite well except for above issue.

**Comment by adrelanos** [comment]
Related to Debian buster, see also:

* https://github.com/QubesOS/qubes-issues/issues/4970
* https://github.com/QubesOS/qubes-issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+buster+in%3Atitle

**Comment by adrelanos** [comment]
`Qubes-Whonix 15 TemplateVMs (Debian buster based) (4.0.1-201906232114) -- Testers Wanted!`
* https://forums.whonix.org/t/qubes-whonix-15-templatevms-debian-buster-based-4-0-1-201906232114-testers-wanted/7601
* https://twitter.com/Whonix/status/1143079049222414336

https://github.com/QubesOS/qubes-mgmt-salt-dom0-virtual-machines/pull/17

**Comment by marmarek** [comment]
I've built and uploaded R4.0.2-rc1. It includes all dom0 updates to this day (including those still in testing) and updated templates:
 - Fedora 30
 - Debian 10
 - Whonix 15
 - Linux 4.19 by default

Right now it's only at https://ftp.qubes-os.org/iso/, but soon other mirrors should catch up.

@andrewdavidwong could you prepare announcement, similar to 4.0.1-rc1? If no major issues will be discovered, final R4.0.2 will follow in few weeks.

**Comment by andrewdavidwong** [comment]
> @andrewdavidwong could you prepare announcement, similar to 4.0.1-rc1? If no major issues will be discovered, final R4.0.2 will follow in few weeks.

Will do!

**Comment by andrewdavidwong** [comment]
> > @andrewdavidwong could you prepare announcement, similar to 4.0.1-rc1? If no major issues will be discovered, final R4.0.2 will follow in few weeks.
> 
> Will do!

Opened: https://github.com/QubesOS/qubes-posts/pull/62
