### ISSUE TITLE
Can't set the fan speed of AMD GFX  Radeon R9 290x

### ISSUE THREAD

**Issue by rusagent** [QubesOS/qubes-issues#5109]
**Qubes OS version**
release 4.0 R4.0

**Affected component(s) or functionality**
AMD Radeon R9 290x Fanspeed

**Brief summary**
Fan speeds are to a maximum from startup.

**To Reproduce**
Just boot into Qubes after install and you'll hear it.

**Expected behavior**
Fans adjust to the temperature of the gpu

**Actual behavior**
Fans go full power and don't calm down anymore

**Solutions you've tried**
ran fancontrol and it didn't help :/

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
_A list of links to the Qubes documentation (or other relevant software documentation) pages you have already consulted._

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
_A list of links to other bug reports, feature requests, or tasks in the qubes-issues tracker (or "none" if you didn't find any). Do not describe any other unreported bugs, features, or tasks here._

**Comment by andrewdavidwong** [comment]
This might turn out not to be too localized or not a Qubes-specific bug, but I'll leave it open for now to see what the devs think.

**Comment by rusagent** [comment]
So what can I do about this? My computer is really really noisy with all the fans on 100% - kind of like a spaceship that wants to lift off :/
