### ISSUE TITLE
qubes-builder-debian: Debian buster based templates using UsrMerge causing issues

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#5111]
Symptom: `/usr/bin/bash` is same file as `/bin/bash`.

Symptom: whonixcheck fails due to no apparmor permission to access `/usr/bin/bash` (has access to `/bin/bash`).

references:

* https://www.whonix.org/pipermail/whonix-devel/2019-February/001303.html
* https://wiki.debian.org/UsrMerge

I suggest to find out what activates UsrMerge and not use it [until|if] Debian enables it by default.

**Comment by marmarek** [comment]
According to the wiki page you've linked, usrmerge is default in debootstrap. Does it meet the "[until|if] Debian enables it by default" condition?

**Comment by adrelanos** [comment]
I see. That puts the ball into our court.

Whonix is fully compatible with this now (at least no obvious bugs seen
by now). Already in the repository.

The change needed was "whenever an apparmor profile referenced
/bin/something we also need to add /usr/bin/something".

There is package usrmerge which I am wondering if we should install it.

https://packages.debian.org/search?keywords=usrmerge

No idea if this will cause any other issues. Seems kinda rushed to
enable such a major change when knowing little about it. On the other
hand, I guess Debian knows what its doing.

Although "apt-file list zsh" shows no file in /usr/bin/zsh, deleting
/usr/bin/zsh and "apt reinstall zsh" makes /usr/bin/zsh come back, so I
conclude somehow Debian sorted that there won't be any stale (outdated)
binaries in /usr/bin which was one of my concerns.

**Comment by unman** [comment]
Just for information, a standard buster install from iso also has UsrMerge - it's now the default.

**Comment by unman** [comment]
@adrelanos  Is there still an open issue here? If so, can you define? (Is it Whonix specific?) If not, close.
