### ISSUE TITLE
qubes-builder: Ubuntu sources don't exist or mislinked

### ISSUE THREAD

**Issue by cystek** [QubesOS/qubes-issues#5117]
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
qubes-builder

**Brief summary**
The sources to build Ubuntu Xenial templates do not exist where the builder looks for them.

log:
Fetched 218 kB in 10s (21.7 kB/s)
Reading package lists...
W: The repository 'https://deb.qubes-os.org/r4.0/vm xenial Release' does not have a Release file.
E: Failed to fetch https://deb.qubes-os.org/r4.0/vm/dists/xenial/main/binary-amd64/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.
Removing 'local diversion of /sbin/initctl to /sbin/initctl.distrib'
make[1]: *** [Makefile:64: rootimg-build] Error 100

**To Reproduce**
https://www.reddit.com/r/Qubes/comments/5vzg04/idiots_guide_to_installing_qbuntu_ubuntu_1604/

**Expected behavior**
The Ubuntu sources exist where the builder thinks they are, or proper repository is linked.

**Actual behavior**
The above error occurs when building the templates.

**Screenshots**
n/a

**Additional context**
Fetched 218 kB in 10s (21.7 kB/s)
Reading package lists...
W: The repository 'https://deb.qubes-os.org/r4.0/vm xenial Release' does not have a Release file.
E: Failed to fetch https://deb.qubes-os.org/r4.0/vm/dists/xenial/main/binary-amd64/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.
Removing 'local diversion of /sbin/initctl to /sbin/initctl.distrib'
make[1]: *** [Makefile:64: rootimg-build] Error 100

**Solutions you've tried**
n/a

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
https://www.reddit.com/r/Qubes/comments/5vzg04/idiots_guide_to_installing_qbuntu_ubuntu_1604/

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
none

**Comment by marmarek** [comment]
This is not a bug, there are no official binary packages for ubuntu. See https://www.qubes-os.org/doc/templates/ubuntu/ 

This means you need to _not_ select "Pre-built Packages Repositories" when running qubes-builder's `setup` script.
