### ISSUE TITLE
whonix-ws-14 will not update with Qubes Updater

### ISSUE THREAD

**Issue by straussmaus** [QubesOS/qubes-issues#5118]
**Qubes OS version**

R4.01

**Affected component(s) or functionality**

Qubes Updater

**Brief summary**

Can not upgrade whonix-ws-14 (only)

**To Reproduce**
1. Go to the little orange star
2. Click on 'Launch Updater'
3. See all other Qubes update
4. See error:

```
Domain disp-mgmt-whonix-ws-14 has failed to start: operation failed: domain 'disp-mgmt-whonix-ws-14' already exists with uuid xxxxxxxxx
```

**Expected behavior**

I expect it to update or to give a clearly written plain language error message that tells me what to look at.

**Actual behavior**

This error is unclear.

**Additional context**

All other Qubes update easily.

**Solutions you've tried**

Tried updating manually by right-click on Qube in Qubes Manager.  This succeeds.

**Comment by andrewdavidwong** [comment]
Duplicate of #1910

**Comment by andrewdavidwong** [comment]
This appears to be a [duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Comment by straussmaus** [comment]
@andrewdavidwong I do not think this is a duplicate.

My error comes from using Qubes Updater in the GUI.  (Not that I *can* update by right-clicking on the VM)

My error message is different from https://github.com/QubesOS/qubes-issues/issues/1910

It is possible that https://github.com/QubesOS/qubes-issues/issues/1910 is the source of this issue but the are not the same even if that is the case (and it might not be)

**Comment by straussmaus** [comment]
@andrewdavidwong This problem does not exist for me now.  After a few times updating manually it works now in the Qubes updater.  I think dom0 updated during this time also so maybe the bug was fixed.  I will close the issue unless it comes back.
