### ISSUE TITLE
Cannot fetch key for linux-scrypt in qubes-builder

### ISSUE THREAD

**Issue by unman** [QubesOS/qubes-issues#5122]
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
qubes-builder

**Brief summary**
make get-sources fails on scrypt sources

**To Reproduce**
_Steps to reproduce the behavior:_
In qubes-builder, `make get-sources`

**Expected behavior**
All sources fetched.

**Actual behavior**
Error downloading additional sources for linux-scrypt.
makefile.Common:70: scrypt-sigs-1.2.1

**Screenshots**
_If applicable, add screenshots to help explain your problem._

**Additional context**
Build on Fedora30

**Solutions you've tried**
Tried updating through clearnet instead of Tor
Dont currently have other templates available to try.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

**Comment by marmarek** [comment]
Cannot reproduce. Try removing `-q` wget option in `Makefile.common` to see what exactly fails.

**Comment by unman** [comment]
Cannot reproduce after checking out anew.
