### ISSUE TITLE
Qubes OS NodeJS problem

### ISSUE THREAD

**Issue by mthnglac** [QubesOS/qubes-issues#5124]
Greetings. I am using appVMs via debian-9 templateVM on Qubes OS 4. Node Interpreter is required to use my Webstorm IDE. To do this, I installed node and npm via nvm on templateVM. Now I want to use these packages to open Webstorm on appVM. However, when I reopen appVM, I cannot get nvm from templateVM, there is no nvm; therefore I cannot use the IDE. Can you help me?

**Comment by andrewdavidwong** [comment]
Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this does not appear to be suitable for `qubes-issues`. We ask that you please send this to the `qubes-users` [mailing list](https://www.qubes-os.org/support/) instead. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a brief comment explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.

**Comment by mthnglac** [comment]
The problem is **Storage** .  I increased it and solved the problem.
