### ISSUE TITLE
qrexec-policy daemon

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#5125]
The most time of opening qrexec call is spent on qrexec-policy process, called to evaluate policy at each call. Each time new (python) process is started, libraries imported etc. In extreme situation it can take up to 300ms per call...

Create policy handling daemon, instead of per-call process. This daemon should:
* be independent process from `qubesd` (for stability and isolation reasons), only query `qubesd` when needed
* listen on some local unix socket - qrexec-daemon should connect to that socket, instead of spawning separate `qrexec-policy` process
* handle multiple requests simultaneously (so one qrexec confirmation prompt do not block other call) - this in practice means usage of `asyncio` python module

In initial version, it's ok to load policy files at each call, query qubesd about existing VMs etc. Basically, the same thing that current `qrexec-policy` process do, but avoiding python startup overhead. If further optimizations will be needed, we can do that later.

_Originally posted by @marmarek in https://github.com/QubesOS/qubes-issues/issues/3293#issuecomment-353750084_

**Comment by marmarta** [comment]
The daemon should also notify user if policy was denied, see https://github.com/QubesOS/qubes-issues/issues/3904

**Comment by marmarta** [comment]
- [ ] TODO: do something with unknown/duplicated responses/qrexec client calls (for example ignore them instead of crashing)
