### ISSUE TITLE
qubes-manager: advanced menu in 'Creation VM'/'Clone qube'

### ISSUE THREAD

**Issue by fepitre** [QubesOS/qubes-issues#5127]
A very handy options in Qubes Manager could be an advanced menu in 'Creation VM'/'Clone qube' for allowing options like 'pool' destination if someone (like me) have multiple pools available for creating or cloning qube.

**Comment by fepitre** [comment]
@marmarta: do you think that could be feasible?

**Comment by marmarta** [comment]
Hmm, it's technically doable (we have access to all the necessary properties via AdminAPI), I just wonder if it's a good idea from complexity standpoint - can a user hurt themselves by accidentally setting this to something wrong?  Can they cause a security issue? (I think not, but I'm not that much of a pool master to be able to tell with certainty).
There are sometimes requests for more complex options for Create New VM, but we have usually decided that CLI is for that sort of things. I wonder if we should rethink this approach. What do you think, @marmarek?

**Comment by fepitre** [comment]
Maybe we could think about adding an option somewhere in a qubes conf to allow displaying advanced options/menu in Qubes Manager. That would prevent non aware users to do mistakes.

**Comment by marmarta** [comment]
that sounds very badly discoverable - you not only have to know about the option, know how to look for it in configuration somewhere else, and also know how to enable it. Dunno, reminds me a bit of the "press kernel version seven times to enable dev tools" in android (which I don't like at all). Useful for us who develop the system, but hard to use for others.

**Comment by fepitre** [comment]
You are right. So maybe simply refine the scope of the issue. Initially, users I know and myself, we daily encounter the case of choosing destination pool when creating or cloning qube. So even if we can do it from cmdline, choosing destination pool in Qubes Manager seems a reasonable option like choosing netvm or template. I don't see a lot of other advanced options which can be daily used too. What do you think?

**Comment by marmarek** [comment]
Storage pool is a useful case, because you can't change it later (you need to clone the qube for that). Maybe we need "advanced" section, collapsed by default?

**Comment by fepitre** [comment]
I would vote for that option. Currently, I don't see any other options except new feature like bridge?

**Comment by fepitre** [comment]
@hexagonrecursion: can you precise why you disagree such feature possibility?

**Comment by marmarta** [comment]
Alright :) I'll whip something up next week.

**Comment by marmarta** [comment]
Oh, maybe we should also put there 'copy devices: yes/no' for cloning a VM, there was some discussion about that recently.

**Comment by andrewdavidwong** [comment]
> Oh, maybe we should also put there 'copy devices: yes/no' for cloning a VM, there was some discussion about that recently.

Indeed, it was counterintuitive to me that a VM I recently cloned did not have the device settings of the original VM, since that meant it wasn't a true clone.

**Comment by marmarta** [comment]
Cloning devices was agreed to be a bug and fixed in https://github.com/QubesOS/qubes-core-admin-client/pull/136; the only thing remaining is asking for destination storage pool for cloning.
