### ISSUE TITLE
Qubes-Whonix 15 release coordination

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#5128]
This is to coordinate the release of Whonix 15.

Unless there is any reason / request to delay it,
(Qubes-)Whonix `15` is planed to be released in 3 day.

References:

* https://forums.whonix.org/t/qubes-whonix-15-templatevms-debian-buster-based-4-0-1-201906232114-testers-wanted/7601
* https://github.com/QubesOS/updates-status/issues/1174
* https://github.com/QubesOS/updates-status/issues/1175
* https://forums.whonix.org/t/qubes-whonix-version-14-debian-stretch-based-can-be-upgraded-to-version-15-debian-buster-based-testers-wanted/7143

**Comment by marmarek** [comment]
Those template builds directly, or you want another one with latest fixed (like DispVM one)? Note that, if you want a new build, updates tracking infrastructure won't allow moving to stable before 7 days in testing.

I assume we'll need a short announcement on qubes-os.org linking to actual post announcing Whonix 15 release. cc @andrewdavidwong

**Comment by andrewdavidwong** [comment]
> I assume we'll need a short announcement on qubes-os.org linking to actual post announcing Whonix 15 release. cc @andrewdavidwong

Yes, happy to. Please let me know when the Whonix announcement URL is available, @adrelanos.

**Comment by adrelanos** [comment]
https://forums.whonix.org/t/whonix-15-has-been-released/7616
https://twitter.com/Whonix/status/1145643994707369986

**Comment by andrewdavidwong** [comment]
- [x] Announced on Qubes News
- [x] Announced on qubes-devel
- [x] Announced on qubes-users
- [x] Quote tweeted Whonix's announcement tweet
- [x] Posted on /r/Qubes subreddit
- [x] Posted on the Qubes Facebook page
- [x] Posted on the Qubes LinkedIn page

Thanks for all your hard work, Whonix team!
