### ISSUE TITLE
Qubes start menu incompatible with DispVMs launching GUI applications into the background

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#5129]
`~/.tb/tor-browser/start-tor-browser.desktop` does as per Tor Browser upstream default

    Exec=sh -c '"$(dirname "$*")"/Browser/start-tor-browser --detach || ([ ! -x "$(dirname "$*")"/Browser/start-tor-browser ] && "$(dirname "$*")"/start-tor-browser --detach)' dummy %k X-TorBrowser-ExecShell=./Browser/start-tor-browser --detach

`--detach` is the default action Tor Browser developers have chosen (I disagree with). It launches the application into the background similar (or even same?) to `sleep 10 & disown`.

Therefore we have to use this hack:
https://github.com/Whonix/tb-starter/commit/bd9f6f8c991ad0c170e63ce1412006239aee0760

related:
https://phabricator.whonix.org/T818

**Comment by marmarek** [comment]
Yes, launching into background is incompatible with DispVM. Similar to #2581

**Comment by andrewdavidwong** [comment]
> Yes, launching into background is incompatible with DispVM. Similar to #2581

Does that mean this is a `won't fix`?

**Comment by marmarek** [comment]
> Does that mean this is a `won't fix`?

In this particular case, I'm afraid so. In similar case, we may want to invent a solution dbus-activation based applications, behaving like this too.
But generally, we need a definitive way to detect when the application terminated, to terminate DispVM too. If the application main process terminates and doesn't give any hints what else should be monitored, it won't work in DispVM.
