### ISSUE TITLE
qvm-remove does not check for persistently attached usb devices

### ISSUE THREAD

**Issue by dhnasa** [QubesOS/qubes-issues#5136]
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
qvm-remove

**Brief summary**
qvm-remove does not check if a qube has a usb device persistently attached with the to be removed qubes as a backend

**To Reproduce**

1. attach any usb device persistently to a qube, e.g. `qvm-usb a --persistent personal sys-usb:2-1`
2. remove the backend qube, e.g. `qvm-remove sys-usb`

**Expected behavior**
qvm-remove should refuse the removal if the qube is used as a backend or detach all devices provided by that qube

**Actual behavior**
qvm-remove just removes the qube
qubesd crashes on next boot, because it can not find the backend

**Screenshots**
_If applicable, add screenshots to help explain your problem._

**Additional context**
_Add any other context about the problem here._

**Solutions you've tried**
manually remove the usb device in /var/lib/qubes/qubes.xml, because qvm-usb does not work without qubesd

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
_A list of links to the Qubes documentation (or other relevant software documentation) pages you have already consulted._

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
_A list of links to other bug reports, feature requests, or tasks in the qubes-issues tracker (or "none" if you didn't find any). Do not describe any other unreported bugs, features, or tasks here._

**Comment by pwmarcz** [comment]
>qubesd crashes on next boot, because it can not find the backend

The qubesd crash has been fixed in QubesOS/qubes-core-admin@74f8d4531ec5fa4ea592e9a0bd27c5226d36a5dd and QubesOS/qubes-core-admin@49107fd2fc6cbab984cdc8d7fa8fa61d3265c076.
