### ISSUE TITLE
Add POOL as an available column in qvm-ls

### ISSUE THREAD

**Issue by brendanhoar** [QubesOS/qubes-issues#5138]
**The problem you're addressing (if any)**
Quickly find which LVM pool a VM belongs to.

**Describe the solution you'd like**
Add a column to the supported --fields list that qvm-ls supports.

**Where is the value to a user, and who might that user be?**
Any user who uses multiple pools should have a quick way to query which VMs are located on which pool.

**Describe alternatives you've considered**
Both `qvm-volume list` and `sudo lvs` can indirectly indicate the pool.

**Comment by marmarek** [comment]
This require a little clarification, since VMs have 4 volumes and each can be in a different pool. I think the most sense would be listing a pool of "private volume". Is it what you have in mind?

**Comment by brendanhoar** [comment]
Ah, good point, I did not consider this, as there's no VM-specific "pool" setting. It's just where the volumes are.

Private volume's pool might be the best single indicator.  Maybe change my request to "Add POOLS as an available column in qvm-ls" and return a comma delimited list of the pools utilized by all of the non-kernel volumes?

B

**Comment by alimirjamali** [comment]
PR Submitted

Review priority: low

`PRIV-POOL` & `ROOT-POOL` columns are added. I do not believe Kernel & Volatile pools to be very much necessary. But they are also possible.
