### ISSUE TITLE
Recent Fedora update breaks VPN function

### ISSUE THREAD

**Issue by straussmaus** [QubesOS/qubes-issues#5139]
**Qubes OS version**
R4.01

**Affected component(s) or functionality**
VPN Qube

**Brief summary**
A VPN Qube with Fedora 29 as template stopped working yesterday after upgrading Fedora 29 template

**To Reproduce**

_1. Create VPN Qube using the manual (not Network Manager) instructions here: https://www.qubes-os.org/doc/vpn/ 
_2. Have success for months!
_3. Upgrade Fedora 29 template on 29/30 June 2019
_4. Reboot VPN Qube
_5. See that VPN does not connect.  Two errors:

a. domain of VPN server not found (no DNS?)
b. using IP address, see this error:

`write UDP: operation not permitted`

**Expected behavior**
The VPN should connect and show a status message on the GUI.  Also I think the problem might be that the 

**Actual behavior**
No status message on the GUI.  See steps above for actual.

**Additional context**
I upgraded the Fedora 29 template yesterday and this was the first time using the VPN Qube after that.

**Solutions you've tried**
I reverted the VPN Qube to Fedora 26 template and it works.  

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
_A list of links to the Qubes documentation (or other relevant software documentation) pages you have already consulted._

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
https://github.com/QubesOS/qubes-issues/issues/3348

**Comment by straussmaus** [comment]
Fixed by making new versions of `qubes-firewall-use-script` and `qubes-vpn-handler.sh` from https://www.qubes-os.org/doc/vpn/.  I see there is new IPv6 info in one of them.  Maybe that was the issue?

**Comment by straussmaus** [comment]
I am having this problem again.  I looked for this ticket, my old solution, and I don't see the "new IPv6" info on https://www.qubes-os.org/doc/vpn/.

Is the VPN documentation a restored version of an older copy by some chance?

To be clearer, I created a new VPN Qube using https://www.qubes-os.org/doc/vpn/.  This does not work on Fedora 30 or 31.  But when I use the same Qube on Fedora 26 template that I still have, it works.  This makes me think the doc on https://www.qubes-os.org/doc/vpn/ is for Fedora 26, not the updated one I found as the original solution.  It's a theory, and I am reopening to ask if this is possible.

**Comment by fepitre** [comment]
I'm not sure this is a Qubes problem. It's either Fedora or you remote server VPN. I had such issues with Fedora 30 with specific AppVM holding my VPNs. This was because the remote server was too old for current OpenVPN version shipped with Fedora. The solution was to use Debian in my case. After upgrading the remote server, that has been solved for Fedora. I would suggest you to test Debian and then, if you can because it's you who manage the remote server, upgrade it.

**Comment by straussmaus** [comment]
Thanks but no because I did some testing.  I can connect to the VPN manually from the same Qube, just not using the `qubes-vpn-handler.sh`.  So my question is still if the docs at https://www.qubes-os.org/doc/vpn/ have been rebuilt from a backup?  Because I don't see anything in that page that includes the fix I found back in July.

**Comment by fepitre** [comment]
Ok so I'm offtopic sorry. I would let @andrewdavidwong answer your question. It's possible that could have happen.

**Comment by andrewdavidwong** [comment]
> Is the VPN documentation a restored version of an older copy by some chance?

> So my question is still if the docs at https://www.qubes-os.org/doc/vpn/ have been rebuilt from a backup?

I see no indication that the document was accidentally reverted to an earlier version or anything like that. You can see the [commit history](https://github.com/QubesOS/qubes-doc/commits/master/external/configuration-guides/vpn.md) and the [blame view](https://github.com/QubesOS/qubes-doc/blame/master/external/configuration-guides/vpn.md).

**Comment by straussmaus** [comment]
@andrewdavidwong Interesting that it was not rebuilt.  I did have a solution earlier with the IPv6 information (according to myself above).  Do you know any IPv6 information regarding VPN Qubes that could be useful in this situation?  Because it is still not possible to use Fedora30+ for a VPN qube.

@fepitre I tried different VPN providers.  I can say fairly sure that the problem is not the OpenVPN version.

**Comment by straussmaus** [comment]
Testing reveals VPN config from https://www.qubes-os.org/doc/vpn/ works with:

fedora 29
debian 10

but not

debian 9
fedora 30
fedora 31
fedora 32

**Comment by 92VV3M42d3v8** [comment]
I am using VPN on qubes based on fedora-32-minimal and it's working. I am using a provider which support both IPV4 and IPV6 and another provider which only support IPV4.

**Comment by andrewdavidwong** [comment]
> @andrewdavidwong Interesting that it was not rebuilt. I did have a solution earlier with the IPv6 information (according to myself above). Do you know any IPv6 information regarding VPN Qubes that could be useful in this situation? Because it is still not possible to use Fedora30+ for a VPN qube.

Sorry, I have no knowledge of this. However, perhaps @tasket might.

**Comment by tasket** [comment]
Its hard to say without a log or specific error.

One thing you could try is to disable the rc.local script by renaming it, then reboot the VM and run the script manually with `sudo groupadd -rf qvpn ; sleep 2s; sudo sg qvpn -c "openvpn --cd /rw/config/vpn/ --config openvpn-client.ovpn"`. That will show you what's happening and if it connects you should test the link to see if it works.

As to a possible cause, there is some variance between template versions as to when rc.local gets executed; the timing of that might affect the VPN client. Its only a guess, but if that does turn out to be a factor then you'd be better off with Qubes-vpn-support which has a more defined startup sequence using systemd.

Finally, as Andrew suggested, I have seen connections fail bc of openvpn version conflicts. I've also seen them fail bc the service provider changed their network but the user didn't download the updated config files.

**Comment by marmarek** [comment]
This may be related to https://github.com/QubesOS/qubes-issues/issues/5071
Check if running `qvm-run <VMNAME> /usr/libexec/mate-notification-daemon &` helps.

**Comment by tasket** [comment]
Interesting... that might explain a problem I've had in R4.1, although its intermittent and it starts working if I wait for it to timeout (I experience it as a delay, not a failure).

**Comment by straussmaus** [comment]
@marmarek 

> Check if running qvm-run <VMNAME> /usr/libexec/mate-notification-daemon & helps.

Yes, when I run this, it works.  

Does this mean the problem is only with the notification?  I am running 4.01 because that's what I installed but I stay current with updates, so if there was a natural 4.01 to 4.1 upgrade, I should have gotten it.

**Comment by marmarek** [comment]
#5071 is not really fixed yet. It happens only when notify-send is called before X server starts (so - rc.local is affected)

**Comment by straussmaus** [comment]
I looked at that thread.  I tested gnome-terminal and it does not open on the same Qubes that I have this problem on.  So I think that confirms it is https://github.com/QubesOS/qubes-issues/issues/5071.

I will close this thread because it seems like https://github.com/QubesOS/qubes-issues/issues/5071 is going to fix it.
