### ISSUE TITLE
Add Whonix 15 WS & GW to qubes-templates-community

### ISSUE THREAD

**Issue by TNTBOMBOM** [QubesOS/qubes-issues#5141]
**Qubes OS version**

4.0.1

**Affected component(s) or functionality**

installing Whonix 15 templates

**Brief summary**

Add the installation ability of whonix 15 templates 

**To Reproduce**

Run:
`
sudo qubes-dom0-update --enablerepo=qubes-templates-community --action=upgrade qubes-template-whonix-gw-15`

or 

`
sudo qubes-dom0-update --enablerepo=qubes-templates-community --action=upgrade qubes-template-whonix-ws-15`

**Expected behavior**
to install ws/gw

**Actual behavior**

templates not there

**Screenshots**

![whonix15qubesrepo](https://user-images.githubusercontent.com/11895339/60574089-69480d00-9d68-11e9-899c-fd9b7c2c88e0.png)

**Additional context**

I even tried with `-testing` but still got the same result

**Comment by marmarek** [comment]
Templates are there, but there is a temporary issue with update server - see "Failed to synchronize cache" message.

**Comment by TNTBOMBOM** [comment]
I see, i just tested that and this issue as well im having it on all my
templatesVM. Will wait until fixed and test again.

Marek Marczykowski-Górecki:
> Templates are there, but there is a temporary issue with update server - see "Failed to synchronize cache" message.
>

**Comment by marmarek** [comment]
Should be good now.

**Comment by TNTBOMBOM** [comment]
Just tested & yep its working! , Thank you :)

Marek Marczykowski-Górecki:
> Should be good now.
>

**Comment by andrewdavidwong** [comment]
Duplicate of #5130
