### ISSUE TITLE
Sometimes randomly shuts off at encryption screen

### ISSUE THREAD

**Issue by frozentime345** [QubesOS/qubes-issues#5142]
**Qubes OS version** 
_The version of Qubes OS you're using (e.g., `R4.0`), available via the command `cat /etc/qubes-release` in a dom0 terminal._
R4.0

**Affected component(s) or functionality** 
_The component or functionality of Qubes OS that is not working as expected._
Boot

**Brief summary** 
_A clear and concise summary of the bug._
Sometimes when I boot up the system freezes in the middle of typing my encryption password and shuts down. Happens rarely.

**To Reproduce** _Steps to reproduce the behavior:_
_1. Go to '...'_
_2. Click on '....'_
_3. Scroll down to '....'_
_4. See error_
Boot, type password, freeze.

**Expected behavior**
_A clear and concise description of what you expected to happen._

**Actual behavior**
_What actually happened (instead of what you expected to happen)._

**Screenshots**
_If applicable, add screenshots to help explain your problem._

**Additional context**
_Add any other context about the problem here._

**Solutions you've tried**
_If applicable, any solutions or workarounds you've already tried._

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
_A list of links to the Qubes documentation (or other relevant software documentation) pages you have already consulted._

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
_A list of links to other bug reports, feature requests, or tasks in the qubes-issues tracker (or "none" if you didn't find any). Do not describe any other unreported bugs, features, or tasks here._

**Comment by andrewdavidwong** [comment]
Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this does not appear to be suitable for `qubes-issues`. We ask that you please send this to the `qubes-users` [mailing list](https://www.qubes-os.org/support/) instead. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a brief comment explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.
