### ISSUE TITLE
Odd shutdown/restart behavior and session persistance

### ISSUE THREAD

**Issue by e6lk7dqzm83p** [QubesOS/qubes-issues#5144]
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
Session startup, starting up domains.

**Brief summary**
I have a number of issues which I think are related:
- When I startup my computer if it has been connected to a keyboard numlock is set (even if when reset the keyboard is not attached)
- I always have two terminal dom0 sessions (even though I only have one dom0 Terminal process in the application autostart menu)
- When I use `shutdown now` or `shutdown -h now` I tend to get the following error on reboot: `Domain (name) has failed to start: internal error Libxenlight failed to create new domain ‘name’` (these domains are started my autostart script).  This seems to occur less often if I use the `shutdown` button in the GUI.  Rebooting my computer seems to eliminate this

**To Reproduce**
The `Domain (name) has failed to start: internal error Libxenlight failed to create new domain ‘name’` I get by using `shutdown now` or `shutdown -h now`

**Expected behavior**
I get one terminal screen, the shutdown command causes no erroneous behavior, num lock state is determined on bootup.

**Actual behavior**
- When I startup my computer if it has been connected to a keyboard numlock is set (even if when reset the keyboard is not attached)
- I always have two terminal dom0 sessions (even though I only have one dom0 Terminal process in the application autostart menu)
- When I use `shutdown now` or `shutdown -h now` I tend to get the following error on reboot: `Domain (name) has failed to start: internal error Libxenlight failed to create new domain ‘name’` (these domains are started my autostart script).  This seems to occur less often if I use the `shutdown` button in the GUI.  Rebooting my computer seems to eliminate this

**Additional context**
None

**Solutions you've tried**
-Turned off session restore (which didn't seem to work, possibly a different issue)
-Moved startup for applications generally within a domain (e.g. using `.bash_profile` to start applications in my `work` domain...using commands in dom0 via autostart seemed inconsistent, possibly related)
-Using `shutdown now` instead of `shutdown -h now` and the GUI shutdown button

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
None that I could find, the other issues with that error message seemed unrelated to this issue.

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
None

**Comment by andrewdavidwong** [comment]
This sounds like it's due to some customization you've done to your dom0 desktop environment. Have you installed any packages in dom0? Which relevant settings have been changed from the defaults?

**Comment by e6lk7dqzm83p** [comment]
Hi,

As far as I know other than the startup scripts (which I can post), my desktop environment is the default one.

**Comment by andrewdavidwong** [comment]
Perhaps the startup scripts are relevant. Would you please post them?

**Comment by e6lk7dqzm83p** [comment]
Hi,
The following commands are run via the "Session and Startup" application (I've omitted the ones that were added by Qubes or an application install):
exo-open --launch TerminalEmulator
qvm-run -a locker keepassxc3
qvm-run -a untrusted chromium
qvm-run -a untrusted firefox
qvm-run -a work gnome-terminal


I have cleared my previous sessions and "save session" is still unchecked.

**Comment by e6lk7dqzm83p** [comment]
I noticed some additional odd behavior today.  I reset my computer four times, three by typing `reboot` in the dom0 terminal an once via the `shutdown` button in the GUI.

First reboot: Everything boots fine, except sys-usb
Second reboot: Same error issues as a above, but sys-usb boots
Third reboot: One domain didn't boot
Fourth reboot: Everything seems fine

**Comment by e6lk7dqzm83p** [comment]
I do still see this odd rebooting behaviour.

**Comment by e6lk7dqzm83p** [comment]
Hi, I'm wondering if #5446 is related to this. 

Any further thoughts on how to adjust this behaviour?

**Comment by e6lk7dqzm83p** [comment]
@marmarek which xfce related files can I remove to reset xfce to a known state (the only documentation I saw didn't line up with the files/folders I found in my home directory).  I am fairly certain the num lock behaviour is not xfce related as it was present even when I went into a terminal directly.

**Comment by marmarek** [comment]
You may have better luck looking at https://docs.xfce.org/
