### ISSUE TITLE
dsa-4371 fix and new debian versions

### ISSUE THREAD

**Issue by xaki23** [QubesOS/qubes-issues#5150]
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
qubes-manager rightclick-update

**Brief summary**
new debian_versions currently have to be added to the 4371-check by and, one by one.
this leads to kali, whonix, debian not being updateable through QM for days/weeks

**To Reproduce**
1. install whonix-15
2. rightclick-update whonix15 in qubes-manager
3. see "unknown debian version" error.

**Expected behavior**
working updates

**Actual behavior**
useless error

**Screenshots**
n/a

**Comment**
i suggest to remove dsa-4371-update at this point or at least make the *) case non-fatal.
new debians appearing at this point probably can be assumed to have the fix already.
and if you are still running some pre-2019 version of debian _and_ didnt update it in the last half year 4371 probably isnt your biggest problem.

**Comment by lunarthegrey** [comment]
I think this is a duplicate of https://github.com/QubesOS/qubes-issues/issues/5057

**Comment by xaki23** [comment]
> I think this is a duplicate of #5057

sortof. 
#5057 shows the problem of the current situation (where every potential vaguely debian based future distro has to be added to that matching in dom0) 

i opened this one because it seems quite possible that any future debian variants will not ship with dsa-4371 affected userland.
so perhaps we should call off adjusting a workaround for a fix that is now ... probably fixed in all the places that matter. 

and if someone now, lets say, installs a fresh legacy q4.0 with an affected debian-9 ... if they update their deb-9 _before_ ( updating dom0 _and_ restarting qubes-manager ) ... they are not getting the fix-check anyways.

@marmarek 
is making the else-branch in the version matcher non-fatal ok with you at this point?
or rather wait for q4.0.2? (aka "no longer shipping an installer that could be affected")

**Comment by xaki23** [comment]
closing because fix merged long ago.

a similar issue still exists with
 /srv/formulas/base/update-formula/update/dsa-4371-update
from pkg qubes-mgmt-salt-dom0-update
