### ISSUE TITLE
Misalignment of volatile LVs?

### ISSUE THREAD

**Issue by brendanhoar** [QubesOS/qubes-issues#5151]
**Qubes OS version**
R4.01 (current-testing)

**Affected component(s) or functionality**
Volatile LVs

**Brief summary**
Just by happenstance, while prepping some devices for new installs, I happened to type fdisk -l into the wrong window, and looked at the output of fdisk -l in dom0, which flagged the alignment issues in red.

**To Reproduce**
```
dom0% sudo fdisk -l
...
Device                                              Boot Start     End Sectors Size Id Type
/dev/mapper/qubes_dom0-vm--disp3379--volatile-part1          1 2097152 2097152   1G 82 Linux swap / Solaris

Partition 1 does not start on physical sector boundary.
...
```
**Expected behavior**
Start sector/block should be 0, not 1.

**Actual behavior**
Start is 1

**Additional context**
This is non-optimal from a SSD perfomance and device lifetime perspective, though I'm not sure how that interacts with the LVs being hosted on a thin-pool with 64KB clusters.

B

**Comment by brendanhoar** [comment]
Update: if 0 is not possible (I have read that LV should have a MBR block 0 partition table to prevent corruption of volume by poorly written tools), then probably something like 1024 or 2048 would be better from an alignment perspective, even if it "wastes" space temporarily. 

Unless someone has more wisdom on this than I, of course.

B

**Comment by marmarek** [comment]
Slightly related: #4974

**Comment by xaki23** [comment]
this seems actualy a bit silly. i did some rapid tests against the volatile of a vm on a raid1-of-two-ssds.

dom0 says in fdisk-l on the /dev/mapper/blahbla-volatile:
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 65536 bytes / 65536 bytes

so no weird sector sizes or anything.
but fdisk (only in dom0, not in fc29 vms) will complain about this "does not start on a physical sector boundary" unless i make the start a multiple of 64kb.

aligining the swap to 1MB might really be the sanest option there. (and as long we are talking lvm-thin with no more than 1MB blocksize, it doesnt really even waste that one mb)

**Comment by brendanhoar** [comment]
> aligining the swap to 1MB might really be the sanest option there. (and as long we are talking lvm-thin with no more than 1MB blocksize, it doesnt really even waste that one mb)

Ha! I didn't even think of this. 

If we skip forward to the 1MB for the partition, then at most one cluster will be written before that mark (for the partition table), so unless the LVM host VG is rather large, most of the 1MB will be unallocated anyway.
