### ISSUE TITLE
Problems while reinstalling whonix and updating fedora

### ISSUE THREAD

**Issue by n0sign4l** [QubesOS/qubes-issues#5152]
**Qubes OS version**
Release 4.0

**Affected component(s) or functionality**
Problems while updating fedora and while reinstalling whonix

**Brief summary**

I have removed all the VMs like whonix-ws-14 whonix-gw-14 anon-whonix etc. then i have tried to reinstall it through the command `sudo qubesctl state.sls qvm.anon-whonix` and the last part of the output that I got had was:

```
Summary for local
------------
Succeeded: 7
Failed:    6
------------
Total states run:    13
Total run time:   2.339 s
DOM0 configuration failed, not continuing
```

so I ran this command

```
sudo qubes-dom0-update --best --allowerasing --enablerepo=qubes-dom0-current-testing qubes-mgmt-salt-dom0-virtual-machines
```

and the installation of anon-whonix worked perfectly but from that moment on (the one that I ran that command) I'm not able anymore to update fedora or debian VMs...

I get this while trying to update fedora-30:

```
sudo qubes-dom0-update --best --allowerasing --enablerepo=qubes-dom0-current-testing qubes-mgmt-salt-dom0-virtual-machines
```

**To Reproduce**
I wrote what I have done before

**Expected behavior**
I should be able to update the VMs

**Actual behavior**
I cannot update them

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
https://www.whonix.org/wiki/Qubes/Install#cite_note-6

**Question**
I ran this command 

```sudo qubes-dom0-update --best --allowerasing --enablerepo=qubes-dom0-current-testing qubes-mgmt-salt-dom0-virtual-machines```

 as I wrote before so now does anything change when I run `sudo qubes-dom0-update` ? I do not want to be in the current-testing repo, how can I go back to the stable one?
Thanks

**Comment by andrewdavidwong** [comment]
> so I ran this command
> ```
> sudo qubes-dom0-update --best --allowerasing --enablerepo=qubes-dom0-current-testing qubes-mgmt-salt-dom0-virtual-machines
> ```
> [...]
> I get this while trying to update fedora-30:
> ```
> sudo qubes-dom0-update --best --allowerasing --enablerepo=qubes-dom0-current-testing qubes-mgmt-salt-dom0-virtual-machines
> ```

This looks like a copy/paste error. You accidentally pasted the same thing twice.

> I do not want to be in the current-testing repo, how can I go back to the stable one?

Using the `--enablerepo=qubes-dom0-current-testing` flag enables the `current-testing` repo only for that command. It does not "toggle" the `current-testing` repo on and off. Therefore, unless you have permanently enabled the `current-testing` repo in some other way, it will not be enabled for subsequent invocations of `qubes-dom0-update` in which that flag is not used. You can ensure that the `current-testing` repo is disabled by checking `/etc/yum.repos.d/qubes-dom0.repo` and ensuring that `enabled = 0` in the `[qubes-dom0-current-testing]` section.

**Comment by adrelanos** [comment]
https://github.com/QubesOS/updates-status/issues/1184 says mgmt-salt-dom0-virtual-machines >= `v4.0.16` is in stable. Therefore `--enablerepo` not needed. Please check version number. In dom0:

    sudo dnf list | grep mgmt-salt-dom0-virtual-machines

**Comment by adrelanos** [comment]
`I cannot update them` - please elaborate with output of what is happening.

**Comment by adrelanos** [comment]
In other words, just run `sudo qubes-dom0-update` as Whonix documentation says. I think this is a common issue. Users not wanting to run `sudo qubes-dom0-update` for whatever reasons. Some are valid since it has broken networking in past or the system did no longer boot (existing reports already).

Upgrade Qubes dom0. This step is mandatory. [2]

    sudo qubes-dom0-update

The comment `This step is mandatory.` seems weird but hope that helps. In theory selective updating of packages might help.

```
Summary for local
------------
Succeeded: 7
Failed:    6
------------
Total states run:    13
Total run time:   2.339 s
DOM0 configuration failed, not continuing
```

We will need the full output of this to see what is actually failing if this is still an issue.

**Comment by adrelanos** [comment]
User disappeared. Please close until/if we get more input.

**Comment by andrewdavidwong** [comment]
Closing this for now due to the lack of response. If you revisit the matter in the future, or if anyone would like the issue to remain open, please leave a comment, and we'll be happy to reopen this. Thank you.
