### ISSUE TITLE
gnome-terminal fails to start first time in Fedora 30 

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#5155]
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
core-agent? gui-agent? gnome-terminal

**Brief summary**
Launching gnome-terminal from the menu sometime fails when the VM isn't running yet

**To Reproduce**
_Steps to reproduce the behavior:_
_1. Get not running fedora-30 qube_
_2. Start gnome terminal from the menu in that qube_
_3. Observe qube starting_
_4. See gnome-terminal appearing and instantly closing_

**Expected behavior**
gnome-terminal stays there

**Actual behavior**
gnome-terminal disappear. `journalctl` inside VM reports:
```
Jul 09 09:55:36 slides qubes.StartApp+org.gnome.Terminal-dom0[843]: # _g_io_module_get_default: Found default implementation dconf (DConfSettingsBackend) for ‘gsettings-backend’
Jul 09 09:55:36 slides qubes.StartApp+org.gnome.Terminal-dom0[843]: # watch_fast: "/org/gnome/terminal/legacy/" (establishing: 0, active: 0)
Jul 09 09:55:36 slides qubes.StartApp+org.gnome.Terminal-dom0[843]: # unwatch_fast: "/org/gnome/terminal/legacy/" (active: 0, establishing: 1)
Jul 09 09:55:36 slides qubes.StartApp+org.gnome.Terminal-dom0[843]: # watch_established: "/org/gnome/terminal/legacy/" (establishing: 0)
Jul 09 09:55:36 slides gnome-terminal-server[878]: Inconsistency detected by ld.so: dl-open.c: 615: _dl_open: Assertion `_dl_debug_initialize (0, args.nsid)->r_state == RT_CONSISTENT' failed!
Jul 09 09:55:36 slides systemd[527]: gnome-terminal-server.service: Main process exited, code=killed, status=15/TERM
Jul 09 09:55:36 slides systemd[527]: gnome-terminal-server.service: Succeeded.
```

**Additional context**
Mostly unmodified fedora-30 template. Starting gnome-terminal again (when VM is already running) works.

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

Possibly related #3533, #2901, but I believe this one is specific to Fedora 30, as this particular error wasn't observed in previous cases.

**Comment by dmoerner** [comment]
Perhaps not particularly helpful, but I've started hundreds of Fedora 30 AppVMs and TemplateVMs this way, and I don't recall ever seeing this bug. And I think I would have noticed, since I found the old Nautilus bugs extremely annoying (https://github.com/QubesOS/qubes-issues/issues/2449). I use a heavily-modified template with most gnome* stuff removed, except for what is required by *qubes* packages.

**Comment by hexagonrecursion** [comment]
I can reproduce this issue, but it only happens once in a blue moon. The following script triggers it eventually. Note: "BUG" is an appvm based on fedora-30.
```
#!/usr/bin/python3

from qubesadmin import Qubes
from qubesadmin.events.utils import wait_for_domain_shutdown
import asyncio

app = Qubes()
loop = asyncio.get_event_loop()
bugvm = app.domains['BUG']
while True:
    bugvm.run('gnome-terminal -- poweroff')
    loop.run_until_complete(wait_for_domain_shutdown([bugvm]))
```
