### ISSUE TITLE
Custom sys-net fails to start

### ISSUE THREAD

**Issue by hexagonrecursion** [QubesOS/qubes-issues#5157]
**Qubes OS version**
Qubes release 4.0 (R4.0)

**Affected component(s) or functionality**
`kernel-qubes-vm-4.14.119-2.pvops.qubes.x86_64`

**Brief summary**
I tried to create a static disposable sys-net by following [this guide](https://www.qubes-os.org/doc/disposablevm-customization/#using-static-disposablevms-for-sys-), but it halted when I tried to start it. The domU kernel panicked. [See gist for panic message](https://gist.github.com/hexagonrecursion/8aca01f3292d303511968e81c39e7b9d).
Note: I made very sure that all qubes with pci devices are shut down before starting sys-net2.
```
dom0$ lspci
...
04:00.0 Network controller: Realtek Semiconductor Co., Ltd. RTL8188EE Wireless Network Adapter (rev 01)
...
dom0$ qvm-prefs sys-net2 kernel
4.14.119-2
dom0$ qvm-prefs sys-net2 kernelopts
nopat iommu=soft swiotlb=8192
```
Further debugging revealed that all custom sys-net qubes, not just static DispVMs are affected.

**To Reproduce**
1. clean up after the previous attempt
```
qvm-remove --force sys-net2
```
2. create `sys-net2`
```
qvm-create --template fedora-29 --label yellow sys-net2 
qvm-prefs sys-net2 virt_mode hvm
qvm-service sys-net2 meminfo-writer off
qvm-prefs sys-net2 provides_network true
qvm-pci attach --persistent sys-net2 dom0:04_00.0
```
3. start it
```
qvm-run --pass-io sys-net2 'nmcli device; poweroff '
```

**Expected behavior**
`sys-net2` starts and the NetworkManager sees the device:
```
sys-net2$ nmcli device
DEVICE  TYPE      STATE         CONNECTION 
wls6    wifi      disconnected  --         
lo      loopback  unmanaged     --         
```

**Actual behavior**
One of 4 things happens:
1 I get the above kernel panic and qrexec eventually times out
[example logs](https://gist.github.com/hexagonrecursion/8fa2c9f7916ea70481530b51da7e8073)
2 I get the same kernel panic and qvm-run exits immediately with this error:
```
sys-net2: qrexec-daemon startup failed: Connection to the VM failed
```
[example logs](https://gist.github.com/hexagonrecursion/8605fa0b9b6d327625fd0ee3aeb657f2)
3 one of the above, but the domU console log is apparently cut short
[example logs](https://gist.github.com/hexagonrecursion/4746df4d42861cf9db8bc3a5b8531857)
4 sys-net2 does not halt, but NM does not see the device:
```
sys-net2$ nmcli device
DEVICE  TYPE      STATE      CONNECTION 
lo      loopback  unmanaged  --         
```
[example logs](https://gist.github.com/hexagonrecursion/07f05920d9d447b4e1edfed462876afd)

**How reproducible is the issue?**
I ran the script a couple dozen times and did not get the expected result even once.

**Additional context**
1. The default sys-net works fine.
2. If I keep restarting sys-net2 without deleting and recreating it, it eventually somehow fixes itself and works fine from then on.

**A workaround**
Based on that with a bit of luck I figured out that if I:
1. First create sys-net2 without attaching the pci device
2. Then start and stop it once
3. Then attach the device 

Then sys-net2 starts fine every time.
For DispVMs the workaround is to start and stop the DVM template once.

logs from a good custom sys-net run for comparison:
https://gist.github.com/hexagonrecursion/ce812f3641b19cdbffea4be0343f9a61

**It appears as if having an uninitialized private volume causes a wifi driver to trigger a kernel panic.**

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
none

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
none

**Comment by hexagonrecursion** [comment]
The choice of userspace appears to affect the likelihood of different failure modes.
Note: in the interest of reproduceability the tests described below were performed without applying any updates inside the templates.

Qubes release 4.0 (R4.0)
qubes-template-fedora-29-4.0.1-201812180316.noarch (no updates applied)
kernel-qubes-vm-4.14.119-2.pvops.qubes.x86_64

Failure modes 1-3 are the most common

Qubes release 4.0 (R4.0)
qubes-template-fedora-29-4.0.1-201812180316.noarch (no updates applied)
[kernel-qubes-vm-4.19.67-1.pvops.qubes.x86_64](https://github.com/QubesOS/updates-status/issues/1266)

Same

Qubes release 4.0 (R4.0)
qubes-template-fedora-30-4.0.1-201907160147.noarch (no updates applied)
kernel-qubes-vm-4.14.119-2.pvops.qubes.x86_64

The failure mode 4 is so common that it took about a dozen attempts to trigger a panic

Qubes release 4.0 (R4.0)
qubes-template-fedora-30-4.0.1-201907160147.noarch (no updates applied)
kernel-qubes-vm-4.19.67-1.pvops.qubes.x86_64

Same

**Comment by hexagonrecursion** [comment]
Qubes release 4.0 (R4.0)
qubes-template-fedora-30-4.0.1-201907160147.noarch (no updates applied)
kernel-qubes-vm-4.19.67-1.pvops.qubes.x86_64

Attempting to troubleshoot when in failure mode 4 as per []()
```
[user@sys-net2 ~]$ sudo modprobe -vr rtl8188ee
rmmod rtl8188ee
rmmod rtl_pci
rmmod rtlwifi
rmmod mac80211
rmmod cfg80211
[user@sys-net2 ~]$ sudo modprobe -v rtl8188ee
insmod /lib/modules/4.19.67-1.pvops.qubes.x86_64/kernel/net/wireless/cfg80211.ko 
insmod /lib/modules/4.19.67-1.pvops.qubes.x86_64/kernel/net/mac80211/mac80211.ko 
insmod /lib/modules/4.19.67-1.pvops.qubes.x86_64/kernel/drivers/net/wireless/realtek/rtlwifi/rtlwifi.ko 
insmod /lib/modules/4.19.67-1.pvops.qubes.x86_64/kernel/drivers/net/wireless/realtek/rtlwifi/rtl_pci.ko 
insmod /lib/modules/4.19.67-1.pvops.qubes.x86_64/kernel/drivers/net/wireless/realtek/rtlwifi/rtl8188ee/rtl8188ee.ko 
[user@sys-net2 ~]$ nmcli device
DEVICE  TYPE      STATE      CONNECTION 
lo      loopback  unmanaged  --      
```

After performing the steps above the following was printed to the sys-net2 console log:
```
[  624.242398] cfg80211: Loading compiled-in X.509 certificates for regulatory database
[  624.242735] cfg80211: Loaded X.509 cert 'sforshee: 00b28ddf47aef9cea7'
[  624.316494] rtl8188ee: rtl8188ee: FW Power Save off (module option)
[  624.316676] rtl8188ee: Using firmware rtlwifi/rtl8188efw.bin
[  624.317982] rtl_pci: tx ring initialization failed
[  624.318013] rtl_pci: Failed to init PCI
[  624.320225] rtl8188ee: probe of 0000:00:06.0 failed with error -12
```
Note: for some reason the above messages didn't make it into the DomU journal.

**Comment by marmarek** [comment]
Error `-12` is "Out of memory". Try to assign more memory to that VM.

**Comment by hexagonrecursion** [comment]
Observations so far:
1. The default if 400MB
2. Assigning 2000MB appears to stop the issue from triggering
3. I didn't test the values in between the two extremes yet
I'll try to dig deeper.

**Comment by hexagonrecursion** [comment]
Narrowed it down: 550MB fails, 600MB works just fine.

**Comment by marmarek** [comment]
It may be that this particular driver needs a lot more memory than usual one. 400MB sys-net works fine with most Intel chips, but I've seen some Atheros that fails to load the module again (after suspend) unless mem is increased.
