### ISSUE TITLE
buy wrong laptop, searching for better one. 

### ISSUE THREAD

**Issue by githubboy1** [QubesOS/qubes-issues#5158]
Hello 
i don't now where to ask so if i in the wrong place... 
anyway, i have a little experience with computers but i like to have a laptop with qubes os on it for work/safety/privacy/protection reasons. 
I want to buy a secondary laptop for this but i am not sure which one. 
Specifications don't saying much for me. 
Can someone give me some advice? 
I have already buy and tried install qubes on a thinkpad t530 but with no luck.
So i guess i have buy the wrong one and the specifications are not good enough.

So can someone give me some brand/type laptops there good for this?

**Comment by strugee** [comment]
This is an issue tracker, not a discussion forum. You should post this question on the [qubes-users mailing list](https://www.qubes-os.org/support/#qubes-users) instead.

**Comment by andrewdavidwong** [comment]
Hi @githubboy1,

As @strugee pointed out, we have some rather specific [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/) for `qubes-issues` that this particular issue doesn't meet, so we ask that you please send your question to the `qubes-users` [mailing list](https://www.qubes-os.org/support/) instead. You're much more likely to receive a helpful answer to your question there!

Thank you for understanding.
