### ISSUE TITLE
DisposableVM gets updates-available set to 1

### ISSUE THREAD

**Issue by marmarta** [QubesOS/qubes-issues#5159]
**Qubes OS version**
R4.0, testing-current (as of 10.07.2019), dvm template is based on fedora-26

**Affected component(s) or functionality**
dispvm

**Brief summary**
a freshly spawned dispvm reports updates-available=1 (and check-updates=1)
It's not a nightmare, but it makes the all-new and shiny "show updates-available in qui-domains" a bit less shiny.

**To Reproduce**
start a dispvm based on a fedora-26-dvm template

**Comment by marmarek** [comment]
Fixed as part of #3736
