### ISSUE TITLE
not in Qubes stable repository although qubesos-bot claiming so - mgmt-salt-dom0-virtual-machines v4.0.16 (r4.0)

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#5161]
Quote https://github.com/QubesOS/updates-status/issues/1184

> Package for dom0 was uploaded to stable repository

Users reporting this is actually not the case:
http://forums.whonix.org/t/whonix-15-state-cls-is-not-available/7705/13

Note regarding issue tagging:
That's not something the Whonix project could solve: this is coming form qubes-os.org server, which I don't maintain.

**Comment by marmarek** [comment]
Fixed.
