### ISSUE TITLE
qvm-ls: "memory" field/column does not output

### ISSUE THREAD

**Issue by brendanhoar** [QubesOS/qubes-issues#5166]
**Qubes OS version**
R4.01 - current-testing

**Affected component(s) or functionality**
qvm-ls

**Brief summary**
The field/column of "memory" does not output when requested via the --fields parameter. However, qvm-prefs does show "memory" as a setting for the VMs.

**To Reproduce**
Open dom0 terminal
$ qvm-ls --fields name,memory,maxmem

**Expected behavior**
Three columns of output, with the middle column showing the memory setting

**Actual behavior**
Three columns of output, with the middle column always showing "-"

**Comment by arno01** [comment]
I'm getting the same in the stable ``R4.0``.
