### ISSUE TITLE
Backport newer device-mapper-persistent-data to dom0

### ISSUE THREAD

**Issue by tasket** [QubesOS/qubes-issues#5172]
**The problem you're addressing (if any)**
Unstable fedora-25 version of `thin_delta` has a tendency to segfault, but have no other crash details atm so filing as enhancement/upgrade request.

**Describe the solution you'd like**
Update `device-mapper-persistent-data` to 0.7.4 or later (i.e. 0.7.5 from fedora-28).

**Where is the value to a user, and who might that user be?**
Ability to run thin [lvm maintenance](https://github.com/tasket/sparsebak) utilities without crashing.

**Additional context**
Discussed with @marmarek here:
https://groups.google.com/d/msgid/qubes-devel/2009ea77-59cf-29a6-8b6e-3b7fe1628e22%40posteo.net

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

**Comment by marmarek** [comment]
Done in https://github.com/QubesOS/qubes-linux-dom0-updates/pull/4
