### ISSUE TITLE
qubes-core-admin-addon-whonix installed but Whonix policy files missing in folder qubes-core-admin-addon-whonix leading to sdwdate-gui issue

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#5174]
**Qubes OS version**
R4

**Affected component(s) or functionality**
qubes-core-admin-addon-whonix

**Brief summary**
qubes-core-admin-addon-whonix installed but Whonix policy files missing in folder `qubes-core-admin-addon-whonix`

**To Reproduce**
Unclear.

**Expected behavior**
Policy files should be there.

* whonix.GatewayCommand
* whonix.NewStatus
* whonix.SdwdateStatus

https://github.com/QubesOS/qubes-core-admin-addon-whonix/tree/master/qubes-rpc-policy

**Actual behavior**
Policy files missing.

**Solutions you've tried**

    sudo qubes-dom0-update qubes-core-admin-addon-whonix

> Package qubes-core-admin-addon-whonix-4.0.2-1.fc25.noarch is already installed, skipping.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
[enable sdwdate-gui in Qubes-Whonix](https://www.whonix.org/wiki/Network_Time_Synchronization#Enable_sdwdate-gui)

**Comment by marmarek** [comment]
Removed locally? I've just checked and I have the policy files in place. List package content with `rpm -ql qubes-core-admin-addon-whonix`, verify its files with `rpm -V qubes-core-admin-addon-whonix`.

**Comment by adrelanos** [comment]
Marek Marczykowski-Górecki:
> Removed locally?


No, I wouldn't get that idea. Not manually removed.

> I've just checked and I have the policy files in place. List package content with `rpm -ql qubes-core-admin-addon-whonix`,


Shows them as expected.

>verify its files with `rpm -V qubes-core-admin-addon-whonix`.


Show missing.

**Comment by adrelanos** [comment]
Issue worked around with:

sudo qubes-dom0-update --action=reinstall qubes-core-admin-addon-whonix

Works for now. Still mystery why that happened.

Feel free to close this one.

When sdwdate-gui-qubes gets enabled by default in the Whonix testers
(and later others) repository I hope we won't get a lot reports about this.
