### ISSUE TITLE
Kernel-latest-5.1.17-1 panic on Thinkpad W520

### ISSUE THREAD

**Issue by brendanhoar** [QubesOS/qubes-issues#5175]
**Qubes OS version**
R4.01 - current-testing with kernel-latest

**Affected component(s) or functionality**
Boot

**Brief summary**
Kernel panic
Reverting to 5.1.15 resolves issue.

**To Reproduce**
Update dom0 with kernel-latest

**Expected behavior**
Boots into Qubes

**Actual behavior**
Kernel panic

**Screenshots**
![kernel_panic_cropped](https://user-images.githubusercontent.com/8979139/61387148-8e1da380-a883-11e9-82f2-0455811617bd.png)

**Comment by marmarek** [comment]
Can you provide exact message? Or maybe a photo of it?

**Comment by brendanhoar** [comment]
Updated issue with screen shot. Thanks @marmarek

**Comment by marmarek** [comment]
For some reason initramfs didn't loaded. Maybe you've run out of disk space in `/boot` or `/boot/efi`?

**Comment by brendanhoar** [comment]
On the running system, /boot shows 38% used.

**Comment by brendanhoar** [comment]
Looks like initramfs was not generated, but other files (config, kernel, system.map),  were generated. Should I use rpm to reinstall package and watch the logging?

**Comment by marmarek** [comment]
> Should I use rpm to reinstall package and watch the logging and df output?

Yes, that's a good idea.

**Comment by brendanhoar** [comment]
I monitored df while running rpm reinstall for 5.1.17. It jumped from 38% to upper 40s, and back when done. So df wasn't the issue.

The reinstall ran fine and I'm running the new kernel now.

No idea what happened, but it appears to be a fluke. Closing out the issue.
