### ISSUE TITLE
Power Manager GUI qubes 4.0.2 has non-functional searchbox upper right side of GUI

### ISSUE THREAD

**Issue by pithouse** [QubesOS/qubes-issues#5176]
### Qubes OS version:
Qubes R4.0.2 

### Affected component(s) or functionality:
XFCE Power Management GUI has non-functional search box in upper right corner of the GUI

---

### Expected or desired behavior:
The Power Manager GUI Should allow search entries in the search box.

### Actual behavior:
Search box completely non-functional and does not allow search entries and search glass non-functional 

### General notes:

---

**Comment by andrewdavidwong** [comment]
It sounds like this might not be our bug, but we'll see.

**Comment by marmarek** [comment]
Can you provide a screenshot or some more detailed description how you get it? I don't see any search box in xfce power manager.

**Comment by pithouse** [comment]
I'll get a screenshot and send it to you as soon as I can.

**Comment by pithouse** [comment]
No issue. My mistake.
