### ISSUE TITLE
Issue connecting to devices for Debian 9 VMs

### ISSUE THREAD

**Issue by hard-money** [QubesOS/qubes-issues#5178]
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
Debian 9 and devices (/dev/xvdd, and /dev/xvdc)

**Brief summary**
The Debian 9 VMs time out waiting for the devices.

**To Reproduce**
_Steps to reproduce the behavior:_
_1. Select any VM based on Debian 9 template (or even the Debian 9 Template VM)
_2. Click on Start
_3. See error in logs

**Expected behavior**
No dependency issues in logs

**Actual behavior**
Dependency failed for swap and devices. Please see attached logs
[qubes_debian_issue.txt](https://github.com/QubesOS/qubes-issues/files/3409407/qubes_debian_issue.txt)

**Additional context**
I do not have this problem with Fedora based VMs

**Solutions you've tried**
Switched VMs to Fedora and it works

**Comment by unman** [comment]
I dont think I've come across this before - has Debian ever worked for you?
What version of the Debian template are you using?

**Comment by hard-money** [comment]
Yes it has and for many weeks. I wonder if there was an update from Debian 9 that broke it.

**Comment by unman** [comment]
@hard-money Did you try `qvm-volume revert` ?
Since the template is unusable, can you try removing it, then reinstalling and running the updates again?

**Comment by hard-money** [comment]
Hi unman, 

I did that and it worked.

Thank you!
