### ISSUE TITLE
Installing Whonix 15 leaves sys-whonix on Whonix 14

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#5183]
**Qubes OS version**

`R4.0`

**Affected component(s) or functionality**

Whonix 15 installation

**Brief summary**

Installing Whonix 15 with Whonix 14 already installed results in `sys-whonix` still on Whonix 14.

**To Reproduce**

1. Have Whonix 14 installed.
2. Follow the [instructions](https://www.whonix.org/wiki/Qubes/Install) to install Whonix 15. (Note: My UpdateVM uses `sys-whonix` for network access.)
3. At the end, `sys-whonix` is still based on `whonix-gw-14`.

**Expected behavior**

Either `sys-whonix` is automatically switched over to `whonix-gw-15`, or there are instructions that state what to do.

Maybe it is as simple as changing the TemplateVM of the pre-existing `sys-whonix` from `whonix-gw-14` to `whonix-gw-15`, or maybe this is dangerous and `sys-whonix` should instead be re-created, or maybe re-creating `sys-whonix` is inadvisable due to entry guard change fingerprinting. Who knows?

**Actual behavior**

`sys-whonix` is still based on `whonix-gw-14`.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

* https://www.whonix.org/wiki/Qubes/Install
* https://www.whonix.org/wiki/Upgrading_Whonix_14_to_Whonix_15

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

None found.

**Comment by iprid23** [comment]
Well, isn't it logical to inspect the /rw of sys-whonix and see if there are any files?

**Comment by andrewdavidwong** [comment]
> Well, isn't it logical to inspect the /rw of sys-whonix and see if there are any files?

I'm not sure what you mean. What do the contents of `/rw` on `sys-whonix` have to do with this?

**Comment by adrelanos** [comment]
Related:
https://github.com/QubesOS/qubes-issues/issues/6904

**Comment by adrelanos** [comment]
Made an edit here:
https://www.whonix.org/wiki/Qubes/Install#Remove_Old_Versions

Does it look good? Consider hitting the `[edit]` button if not.

Can this be considered documented and therefore closeable?

Any further improvements would be covered by https://github.com/QubesOS/qubes-issues/issues/6904 (unspecific to Qubes-Whonix), I think.

**Comment by andrewdavidwong** [comment]
Closing as resolved. If you believe this issue is not yet resolved, or if anyone is still affected by this issue, please leave a comment, and we'll be happy to reopen it. Thank you.

**Comment by DiagonalArg** [comment]
> Made an edit here: https://www.whonix.org/wiki/Qubes/Install#Remove_Old_Versions
> 
> Does it look good? Consider hitting the `[edit]` button if not.
> 
> Can this be considered documented and therefore closeable?

That link is now broken, but proper documnetation is here:
https://www.qubes-os.org/doc/templates/#switching

I am unable to edit the whonix wiki, or I would have added it there, but footnote 4 there does point, in what was a circular fashion, here.

**Comment by adrelanos** [comment]
https://www.whonix.org/wiki/Qubes/Install#Remove_Old_Versions is now https://www.whonix.org/wiki/Qubes/Install#Notices. Added an anchor just now.

But anyhow. When reading https://www.whonix.org/wiki/Qubes/Install from top to buttom, this is mentioned.

As for footnotes, see:
https://forums.whonix.org/t/wiki-footnotes/12861

> I am unable to edit the whonix wiki

https://www.whonix.org/wiki/Contribute#Documentation

We're having many edits from editors with and even without account every week.

**Comment by DiagonalArg** [comment]
@adrelanos  - I don't see the following sequence of commands, which are [here](https://www.qubes-os.org/doc/templates/#switching), on the wiki:

````
Base the disposable template on the new template.

qvm-create -l red -t <NEW_TEMPLATE> <NEW_DISPOSABLE_TEMPLATE>
qvm-prefs <NEW_DISPOSABLE_TEMPLATE> template_for_dispvms True
qvm-features <NEW_DISPOSABLE_TEMPLATE> appmenus-dispvm 1
qubes-prefs default-dispvm <NEW_DISPOSABLE_TEMPLATE>
````

That wasn't sufficient.  I also needed the following prior to deleting the old dispvm:

```
qvm-prefs anon-whonix default_dispvm whonix-ws-16-dvm
```

Not sure why I couldn't edit the wiki.  Maybe an addon?  I"ll look into it.
