### ISSUE TITLE
qubesctl reports dom0 update successful when there was actually an error

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#5186]
**Qubes OS version**

`R4.0`

**Affected component(s) or functionality**

`qubesctl`

**Brief summary**

When updating dom0 with `qubesctl`, there was a `Failed to synchronize cache for repo` error, but `qubesctl` reported the update as completely successful.

**To Reproduce**

In dom0:

```
$ sudo qubesctl --show-output state.sls update.qubes-vm
local:
----------
          ID: /etc/yum.repos.d/qubes-r4.repo
    Function: file.replace
      Result: True
     Comment: onlyif execution failed
     Started: 15:16:16.286150
    Duration: 909.447 ms
     Changes:   
----------
          ID: /etc/apt/sources.list.d/qubes-r4.list
    Function: file.replace
      Result: True
     Comment: onlyif execution failed
     Started: 15:16:17.196059
    Duration: 28.672 ms
     Changes:   
----------
          ID: dnf list updates --refresh >/dev/null
    Function: cmd.run
      Result: True
     Comment: Command "dnf list updates --refresh >/dev/null" run
     Started: 15:16:17.225202
    Duration: 1217.966 ms
     Changes:   
              ----------
              pid:
                  9471
              retcode:
                  0
              stderr:
                  Failed to synchronize cache for repo 'qubes-dom0-cached', disabling.
              stdout:
----------
          ID: update
    Function: pkg.uptodate
      Result: True
     Comment: System is already up-to-date
     Started: 15:16:18.450189
    Duration: 307848.229 ms
     Changes:   

Summary for local
------------
Succeeded: 4 (changed=1)
Failed:    0
------------
Total states run:     4
Total run time: 310.004 s
```

**Expected behavior**

`Failed: 1` due to `Failed to synchronize cache for repo 'qubes-dom0-cached', disabling.`.

**Actual behavior**

`Failed: 0`

**Solutions you've tried**

`qubes-dom0-update` does not have this problem and works fine.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

https://www.qubes-os.org/doc/salt/

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

I thought I remembered seeing an issue about `qubesctl` and/or the Qubes Update widget reporting success even though an update failed. However, now I can find no such issue.

**Comment by marmarek** [comment]
Error of this command is intentionally ignored - it's there only to invalidate dnf cache (workaround for dnf bug), the actual check for updates is in the next step.
BTW this step is not necessary in dom0. And in fact there is separate `update.qubes-dom0` state for dom0, without this step.

**Comment by andrewdavidwong** [comment]
> Error of this command is intentionally ignored - it's there only to invalidate dnf cache (workaround for dnf bug), the actual check for updates is in the next step.

Is there some way to make it clear to the user that this is expected and not a bug? For example, can we print some message to that effect?

> BTW this step is not necessary in dom0. And in fact there is separate update.qubes-dom0 state for dom0, without this step.

Oh, are you saying there's a better way to use `qubesctl` to update dom0? What is the command?
