### ISSUE TITLE
Move/copy-to-OtherAppVM not working on samba share after updating to fedora-30

### ISSUE THREAD

**Issue by umbratic** [QubesOS/qubes-issues#5189]
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
Nautilus 3.32.1-stable, Samba share, Move/Copy-to-OtherAppVM, View/Edit-in-DisposableVM

**Brief summary**
After updating TemplateVM from fedora-29 to fedora-30, the right-click options "Move/Copy-to-OtherAppVM" and "View/Edit-in-DisposableVM" do not work on a samba share but work perfectly on files on the local drive (home/user)

**To Reproduce**
_Steps to reproduce the behavior:_
_1. Update TemplateVM to fedora-30. Update all AppVMs
_2. Open Nautilus
_3. Attach samba share from remote NAS
_4. Right-click on any file, select Move/Copy-to-OtherAppVM or View/Edit-in-DisposableVM

**Expected behavior**
Same behavior as previously (fedora-29 etc.)

**Actual behavior**
Does not work on samba share, but works on local files (home/user)

**Screenshots**
When starting Nautilus in a terminal. the following messages are displayed:

_For "copy-To-Other-AppVM":_

```
Traceback (most recent call last):
  File "/usr/share/nautilus-python/extensions/qvm_copy_nautilus.py", line 34, in on_menu_item_clicked
    subprocess.call(cmd)
  File "/usr/lib64/python3.7/subprocess.py", line 323, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib64/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.7/subprocess.py", line 1453, in _execute_child
    restore_signals, start_new_session, preexec_fn)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

_For "View in Disposable VM":_

```
Traceback (most recent call last):
  File "/usr/share/nautilus-python/extensions/qvm_dvm_nautilus.py", line 56, in on_menu_item_clicked
    Popen(command, stdout=devnull, stderr=devnull)
  File "/usr/lib64/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.7/subprocess.py", line 1453, in _execute_child
    restore_signals, start_new_session, preexec_fn)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Additional context**
"none"

**Solutions you've tried**
see above

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
Qubes docs, github qubes-issues

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
"none"

**Comment by andrewdavidwong** [comment]
CC: @fepitre

**Comment by fepitre** [comment]
@umbratic: I did not succeeded to reproduce your error. I've mounted a samba share and launched "copy-To-Other-AppVM" and "View in Disposable VM" for several files like text or images without any problem. How do you attach your samba share? Is it a CIFS mount point or you browse it through nautilus ?

**Comment by umbratic** [comment]
@fepitre: When using Nautilus > Other locations > Connect to server I get the error I reported.
Meanwhile I had to change all machines on this site to use autofs, cifs-utils and edited  /rw/config. This works and allows people using samba shares again.

**Comment by fepitre** [comment]
I close this issue. If the problem appears again, I would be glad to try to reproduce it.
