### ISSUE TITLE
Run qvm-clone as a normal user (not root) or fix path to avoid broken shortcuts

### ISSUE THREAD

**Issue by stopthisbruh68** [QubesOS/qubes-issues#5193]
Skip to: https://github.com/QubesOS/qubes-issues/issues/5193#issuecomment-515732543

-----

**Qubes OS version**
_R4.0_

**Affected component(s) or functionality**
_Qubes Menu_

**Brief summary**
_A template from whonix_gw_14 that will not disappear after deleting it from Qube Manager._

**To Reproduce**
_Steps to reproduce the behavior:_
_1. Make a fresh install of Qubes OS_
_2. Execute those 3 commands displayed in the documentation after a fresh install of Qubes_
_3. Whonix-gw-14 is going to create a backup_
_4. Now you cannot delete the whonix-gw-14-backup-20190726-qa from the Menu_

**Expected behavior**
_That after deleting it from Qube Manager it will disappear from the Menu but it doesnt_

**Actual behavior**
_I delete the backup from the Qube Manager but it stays in the Menu. Unable to delete from anywhere in the dom0 system_

**Screenshots**
_I cant. But you know how there are Domain: Disposable: and Template: inside the Menu. One is called Template: whonix-gw-14-backup-20190726-qa with a Qube settings inside. Qube settings will not open btw._

**Solutions you've tried**
_I have found NO solutions to this problem._

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
_A list of links to the Qubes documentation (or other relevant software documentation) pages you have already consulted._

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
_A list of links to other bug reports, feature requests, or tasks in the qubes-issues tracker (or "none" if you didn't find any). Do not describe any other unreported bugs, features, or tasks here._

**Comment by andrewdavidwong** [comment]
Have you read this?

https://www.qubes-os.org/doc/managing-appvm-shortcuts/#fixing-shortcuts

**Comment by andrewdavidwong** [comment]
>  Execute those 3 commands displayed in the documentation after a fresh install of Qubes

Which three commands? Please provide a link to the documentation page you're referring to.

**Comment by hexagonrecursion** [comment]
> > Execute those 3 commands displayed in the documentation after a fresh install of Qubes
> 
> Which three commands? Please provide a link to the documentation page you're referring to.

I believe I experienced this issue too. I'm 99% certain stopthisbruh68 is referring to [this three commands](https://www.qubes-os.org/doc/installation-guide/#qubes-401-warning). And the shortcuts likely ended up in 
/usr/local/share/applications/ (not covered by the current documentation).

**Comment by stopthisbruh69** [comment]
Hello this is me again, I can't remember my password LOL. Anyways. Yes @andrewdavidwong I read it about fixing shortcuts only problem is that the vm name doesn't exist. It cannot find the name. I check inside /.local/share/applications/ and I didn't find anything inside with the same name. Aswell as /.config/menus/applications-merged/. There I found those 2 backup files. I deleted them both and it is still in the Menu.

About the 3 commands; https://www.qubes-os.org/doc/installation-guide/#qubes-401-warning

$ sudo qubes-dom0-update --enablerepo=qubes-templates-community --action=upgrade qubes-template-whonix-gw-14

This command will create that backup file in my Menu and stay there forever.

**Comment by stopthisbruh69** [comment]
Btw what happened to my other Issue?

**Comment by stopthisbruh69** [comment]
Here is my Reddit post btw; https://www.reddit.com/r/Qubes/comments/chcoso/editremove_appvm_from_the_menu/

**Comment by stopthisbruh69** [comment]
> And the shortcuts likely ended up in /usr/local/share/applications/ (not covered by the current documentation).
@hexagonrecursion Holy crap. This SOLVED it! I found 2 .desktop files with those names inside of /usr/local/share/applications/ and after I ran $ sudo rm -rf whonix-gw-14-backup.... they disappeared from the Menu all together. Thank you so much!

**Comment by stopthisbruh69** [comment]
Sorry for the spam; but the command "*qvm-sync-appmenus*" does not work. Like to says in the documentation: https://www.qubes-os.org/doc/managing-appvm-shortcuts/
It requires a vm-name at the end. 
1. I might be reading the documentation wrong or..
2. The documentation is saying we should execute qvm-sync-appmenus but actually that's what Linux is doing automatically. And we should actually be executing the command underneath.

**Comment by unman** [comment]
@stopthisbruh69 @andrewdavidwong I've added the additional path to check to the relevant [page](https://www.qubes-os.org/doc/managing-appvm-shortcuts/#fixing-shortcuts)
Please close.

**Comment by hexagonrecursion** [comment]
@unman It would be ideal to either fix qubes-dom0-update to run qvm-clone as a normal user (not root) or fix qvm-clone to no longer create *.application files, where a subsequent qvm-remove won't delete them, when ran as root. I think this issue should be left open until then.

**Comment by andrewdavidwong** [comment]
> @unman It would be ideal to either fix qubes-dom0-update to run qvm-clone as a normal user (not root) or fix qvm-clone to put *.application files in ~/.local/share/applications/ instead of /usr/local/share/applications/ when ran as root because qvm-remove automatically cleans up ~/.local/share/applications/ but it won't delete files in /usr/local/share/applications/ (even when ran as root). I think this issue should be left open until then.

Leaving open to see whether the Qubes devs agree to do this.

**Comment by someotherkyle** [comment]
just want to add that @hexagonrecursion 's  path added on 7/26/19 was where I found my shortcuts in i3's dmenu and the current docs still do not include this path

**Comment by andrewdavidwong** [comment]
> just want to add that @hexagonrecursion 's path added on 7/26/19 was where I found my shortcuts in i3's dmenu and the current docs still do not include this path

In case you (or anyone else reading this) is not already aware, the documentation is a community effort, and everyone is welcome to contribute. (That's how things like this get updated!) So, if you'd like to get involved with the project, this is a great way to do it. You can read more about how to submit documentation changes here:

https://www.qubes-os.org/doc/doc-guidelines/
