### ISSUE TITLE
CPU Usage missing from Qubes tray widget

### ISSUE THREAD

**Issue by SaswatPadhi** [QubesOS/qubes-issues#5195]
**Qubes OS version**
Qubes release 4.0 (R4.0)

**Affected component(s) or functionality**
Qubes tray widget

**Brief summary**
Although memory usage is always reported, CPU usage is missing for some arbitrary subset of qubes. See screenshot below.

**To Reproduce**
1. Click the Qubes tray widget

**Expected behavior**
CPU Usage (%) for every qube

**Actual behavior**
CPU Usage (%) is missing for most (sometimes all) qubes

**Screenshots**
![Screenshot_2019-07-26_15-45-43](https://user-images.githubusercontent.com/1577944/61985344-a72dff00-afbd-11e9-867d-0c0cfc533840.png)

**Comment by andrewdavidwong** [comment]
Related: #4531, #4401

CC: @airelemental, @marmarta

**Comment by airelemental** [comment]
CPU usage is suppressed when it is 0% (or more precisely, any CPU usage <1%, since it rounds down). You can verify this by comparing to xentop (divide the xentop numbers by the number of assigned cores).

**Comment by SaswatPadhi** [comment]
Thank you. I just verified this. Indeed, the CPU usage is suppressed for usage < 1%.

It would be nice to show a 0% in a grayed-out font so users are not confused. But this is definitely not a bug so feel free to close this issue.

**Comment by andrewdavidwong** [comment]
> Thank you. I just verified this. Indeed, the CPU usage is suppressed for usage < 1%.
> 
> It would be nice to show a 0% in a grayed-out font so users are not confused. But this is definitely not a bug so feel free to close this issue.

Classifying as a minor UX bug.

**Comment by airelemental** [comment]
I like showing 0% CPU as blank, because:
* On my system at least, most VMs would display 0%, so hiding it reduces clutter,
* Showing blank for 0% cpu usage makes the (common) no-cpu situation instantly recognizable. And as a result, any positive CPU usage stands out better, as it should.

**Comment by andrewdavidwong** [comment]
> I like showing 0% CPU as blank, because:
> 
> * On my system at least, most VMs would display 0%, so hiding it reduces clutter. The positive CPU usages stand out better.
> * Showing blank for 0% cpu usage makes the (common) no-cpu situation instantly recognizable, you don't need to parse the single-digit usage.

The problem is that users don't know that the empty space has a special meaning.

**Comment by marmarta** [comment]
I agree, this can be confusing. Obvious once you know what's going on, but definitely not clear unless you know it beforehand. A grayed-out 0% would solve this problem. Perhaps we should think about adding options to the widgets - it would be a bigger job though, especially figuring out where to place them to be both easily discoverable and not annoying.

**Comment by SaswatPadhi** [comment]
I tried making this change on my machine -- I think it's quite readable and much less confusing with a 0% text in `lightgrey` color.

#### Grey:
![grey](https://user-images.githubusercontent.com/1577944/62200421-3a5a9200-b33a-11e9-846e-fe1a1d041495.png)

#### LightGrey:
![lightgrey](https://user-images.githubusercontent.com/1577944/62200422-3a5a9200-b33a-11e9-8678-91f206d64763.png)

I can submit a (tiny) PR for whichever style we decide to go forth with.

**Comment by andrewdavidwong** [comment]
I think `lightgrey` is more easily distinguishable.

**Comment by airelemental** [comment]
The distinguishability may be reversed in dark themes where the background is black (like Adwaita-dark).

**Comment by marmarta** [comment]
@airelemental , you're right. It probably should use one of the theme styles for the appropriate color.

**Comment by SaswatPadhi** [comment]
Hi, I finally had some time to play with Gtk settings. As per your suggestions I looked at available theme colors and found the `INSENSITIVE` color for the text to work well -- this is the theme color for inactive text. Here are two screenshots with Adwaita and Adwaita-dark:

### Adwaita
![light](https://user-images.githubusercontent.com/1577944/64737044-d54d9c80-d4a0-11e9-8220-f8efe24d7f1b.png)

### Adwaita-Dark

![dark](https://user-images.githubusercontent.com/1577944/64737059-d979ba00-d4a0-11e9-9dcf-81315c86330f.png)

I am opening a WIP PR that we can merge when everyone is happy :)

**Comment by SaswatPadhi** [comment]
Thanks for merging my PR, @marmarek.

I am closing this issue now.
