### ISSUE TITLE
Qubes broke after disk hit max 

### ISSUE THREAD

**Issue by domousser** [QubesOS/qubes-issues#5196]
**Qubes OS version**
_The version of Qubes OS you're using (e.g., `R4.0`), available via the command `cat /etc/qubes-release` in a dom0 terminal._

R4.0.2-rc1-x86_64

**To Reproduce**
fill qubes HD to max, then it will break .  

vms will stop working upon hitting max. Restart causes several vms to fail to load. 

you will get qubes os failed message

**Expected behavior**
the system to boot properly and VM manager to work.

**Actual behavior**

only domo works  vm manager and all vms all inaccesible

**Additional context**

the second comment in this bug sums up my issue I think,.. my disk got full then the whole installation broke.. I restarted and I was really locked out of my VMs. VMs where buggy and broke before the restart around when the disk hit full. 

**Solutions you've tried**

tried to do fixes suggested online, but no fix online is complete in detail of how to execute said fix. 

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

https://github.com/QubesOS/qubes-issues/issues/4635

Failed to start Load Kernel modules
see 'systemct1' status systemd-modules-load.service' for details. 

when I start up.  Just having a bad time trying to figure this out.. Nothing anyone suggests I can get to half work. Most of the people with this issue " figure it out " by them selves and don't say how. 

how do I restore the qubes.xml

**Comment by domousser** [comment]
https://www.reddit.com/r/Qubes/comments/cif01z/qubes_issue_after_full_disk_then_restart/

to follow things ive tried or have been suggested.. Sturggling to work through this issues for my very first time, as a low experience linux user.

**Comment by domousser** [comment]
running systemctl in my qubes installation 

I get these errors 

Qubes-vm@sys-firewall.service loaded FAILED FAILED start Qubes VM sys-firewall
Qubes-vm@sys-net.service loaded FAILED FAILED Start Qubes VM sys-net
Qubes-vm@sys-whonix.service loaded FAILED FAILED Start Qubes VM sys-whonix
Qubesd.service loaded FAILED FAILED Qubes OS Daemon

**Comment by domousser** [comment]
yet another related ticket 

https://github.com/QubesOS/qubes-issues/issues/3376

**Comment by cfcs** [comment]
I've had reports from three different Qubes users about the thin_lvm blowing up when something runs low on space (not necessarily disk space, maybe some kind of metadata storage)?

**Comment by brendanhoar** [comment]
My suggestion would be:

Qubes will monitor, via disk space widget or other mechanism, the %age of default pool usage and metadata usage*. When that threshold is reached, all VMs that a) do not provide network and b) do not have PCI devices attached are then paused. A notification is given to the user to offload storage carefully before continuing. This notification is and pausing is periodic (checks every x minutes) until the pool or metadata usage threshold has been reduced below the threshold, perhaps with an option to temporarily turn off the auto-pause.

Threshold likely would be in percentage. While one may want to make the pool usage percentage user configurable, it's probably wise to enforce a conservative value on the metadata usage.

Brendan

\* metadata usage should probably also be shown in the disk widget as well, as @tasket and several others can attest to.

**Comment by cfcs** [comment]
@brendanhoar that sounds really hard to use for non-technical users, but could be useful for technical users indeed (although a bit complex to implement).

An alternative I'd like to see would be to provide a way (in the installer) to not use thin allocations, so we can recommend our non-technical friends to use that. At the moment this issue is generating support requests and unhappy friends at a pretty unprecedented rate. :-(

**Comment by brendanhoar** [comment]
I just booted the 4.02RC-1 installer and you do have the option to choose one of several methods: lvm, lvm thin, btrfs, standard file-based.

It's a little hard to find, you have to say you'll configure partitions/storage manually in the installer UI to get to that page.

**Comment by cfcs** [comment]
@brendanhoar thanks! It's been a while since I had the installer booted, but that works for me :-)

**Comment by marmarta** [comment]
metadata was implemented in the disk space widget here: https://github.com/QubesOS/qubes-desktop-linux-manager/commit/c17bfd4d3d614de4691969a6a1a7fc513c7571f4

**Comment by marmarta** [comment]
and default metadata pool size was increased here: https://github.com/QubesOS/qubes-blivet/commit/933b35eba35cb33586a25b6f82f89ec5fe03f9d5

**Comment by marmarta** [comment]
And I think default metadata size was increased here https://github.com/QubesOS/qubes-blivet/commit/933b35eba35cb33586a25b6f82f89ec5fe03f9d5

I think this can be closed (reopen please if you think it's needed)

**Comment by cfcs** [comment]
Do we have repair instructions for when this breaks on existing installs somewhere?

**Comment by andrewdavidwong** [comment]
> Do we have repair instructions for when this breaks on existing installs somewhere?

I don't recall seeing any. You're welcome to open a separate issue for adding such instructions to the documentation.
