### ISSUE TITLE
Since QubesOS focuses on security and on privacy then maybe we should use an alternative to groups.google.com?

### ISSUE THREAD

**Issue by ghost** [QubesOS/qubes-issues#5197]
> What is Qubes?
> Qubes OS is a free and open source operating system that focuses on security and **privacy**.

https://www.qubes-os.org/donate/#what-is-qubes

**The problem you're addressing (if any)**
I don't think it's a good idea to "send" people to any of google's websites (groups.google.com in this case) when we know very well what's Google's primary business model and how privacy-unfriendly it is.

**Describe the solution you'd like**
To use a Free/Libre and Open Source Software alternative.

**Where is the value to a user, and who might that user be?**
Privacy.

**Describe alternatives you've considered**
[Framalistes](https://framalistes.org/sympa/), [sympa](https://www.sympa.org/overview/features)... or maybe some of you know of a better one?

**Comment by unman** [comment]
No one is "sending people to any website", except this one.
Did you look at [this](https://www.qubes-os.org/support/#mailing-lists-vs-forums) ?
The google service is just free (as in beer) infrastructure.

Can you explain what you think the impact on "privacy" is? Use it as a mailing list, and if you want web access use the archives at [mail-archive](https://www.mail-archive.com/qubes-users@googlegroups.com/)
(That said, I would like to see a policy of linking to mail-archive, but dont see that it would be enforceable.)

**Comment by andrewdavidwong** [comment]
As @unman pointed out, this is already addressed here:

https://www.qubes-os.org/support/#mailing-lists-vs-forums

If you'd like to discuss it further, please start a thread on the [qubes-project](https://www.qubes-os.org/support/#qubes-project) mailing list.
