### ISSUE TITLE
booting file (.iso image) using GUI option not working

### ISSUE THREAD

**Issue by TNTBOMBOM** [QubesOS/qubes-issues#5202]
**Qubes OS version**

R4.0.1

**Affected component(s) or functionality**

Qube Manager

**Expected behavior**

To  send you to the location of the chosen appvm with graphical (thats what i have understood from that option)

**Actual behavior**

Just not working

**Screenshots**

![qubegui](https://user-images.githubusercontent.com/11895339/62014592-8074f180-b192-11e9-8da9-a29f512bd195.png)

**Solutions you've tried**

Address of the file needs to be done manually in order to boot it.

**Comment by marmarek** [comment]
Can you give some details about qube you've chosen? Was it running? What template it was based on?

**Comment by TNTBOMBOM** [comment]
> Can you give some details about qube you've chosen? 

Debian appvm

> Was it running?

yes

> What template it was based on?

Debian 10 buster

**Comment by unman** [comment]
There really should be a health warning when working with minimal templates.

Debian minimal templates dont have zenity, which is used to generate the file selection window.
Debian-9 and Debian-10 **do** have zenity, and the file selection there works for  me in both cases.

**Comment by TNTBOMBOM** [comment]
Ok Great it worked after installing zenity. It also missed in my debian-9 maybe its been removed while im managing some packages in template. 

But can i request from you to add this package with its functional here: 

https://www.qubes-os.org/doc/templates/debian-minimal/

So users are aware what is missed and what is not same as others functional/packages? 

Once its added feel free to close this issue.

**Comment by marmarta** [comment]
I've added a PR with actual error messags on fail; documentation is another issue, that I think also would need a bit of attention.

**Comment by unman** [comment]
@andrewdavidwong I've added a [note in the docs](https://www.qubes-os.org/doc/templates/minimal/#debian).
Please close.
