### ISSUE TITLE
Debian-10 template has unnecessary services running

### ISSUE THREAD

**Issue by unman** [QubesOS/qubes-issues#5206]
**Qubes OS version**
R4.0
**Affected component(s) or functionality**
Debian-10 templates

**Brief summary**
Timers are loaded for apt-daily-upgrade and apt-daily, although these services themselves are prevented from running.
cups-browsed service is loaded although inbound is blocked by firewall.
avahi-daemon.socket is loaded although actual avahi service is inactive

**To Reproduce**
_Steps to reproduce the behavior:_
_1. Install debian-10 template
_2. inspect loaded services

**Expected behavior**
Unnecessary services will be masked or inactive.

**Actual behavior**
As above
**Solutions you've tried**
Masking in template

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
General approach to take in Debian is raised at #2238
Suggestion of disabling cups itself is raised at #5179 ( I dont support that suggestion.)

**Comment by SaswatPadhi** [comment]
I recently upgraded my Debian 9 minimal template to Debian 10 (steps similar to https://www.qubes-os.org/doc/template/debian/upgrade-8-to-9/).

I don't see cups or avahi running. May be minimal templates don't have these services?

**Comment by unman** [comment]
@SaswatPadhi - no, minimal doesnt, but they should still be masked in case of later install.
It's only the Debian-10 template (and derivatives) as in  the heading.

@marmarek Is it enough to close this in the template (my thought),or do you think it should be applied to existing templates?
