### ISSUE TITLE
I210 network interfaces continuously reset

### ISSUE THREAD

**Issue by Pixistick** [QubesOS/qubes-issues#5216]
**Qubes OS version**
Qubes release 4.0 (R4.0)

**Affected component(s) or functionality**
The I210 network interfaces not connecting to network.

**Brief summary**
The I210 NICs keep resetting and never connect to the network. Affected Fedora 29 and Fedora 30 also.

**To Reproduce**
Nothing needed to do. Does this on boot.

**Expected behavior**
The network interface should connect to the network.

**Actual behavior**
On boot network manager keeps spinning the animation and produces alerts saying "disconnected from network."

**Solutions you've tried**
Fedora 29 and Fedora 30 fully upgraded with a usb wifi dongle I have to fall back on.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
Seems to be the same issue as this from R3.1.
https://groups.google.com/forum/#!msg/qubes-devel/9OybIE8hTrw/0v-B-bKsAAAJ

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
Possibly related to this from the mailing list discussion above. https://github.com/QubesOS/qubes-issues/issues/1734

[dom0-log.txt](https://github.com/QubesOS/qubes-issues/files/3464193/dom0-log.txt)
[sys-net-log.txt](https://github.com/QubesOS/qubes-issues/files/3464194/sys-net-log.txt)
[xen-log.txt](https://github.com/QubesOS/qubes-issues/files/3464195/xen-log.txt)

**Comment by marmarek** [comment]
```
[   35.920864] pciback 0000:07:00.0: Driver tried to write to a read-only configuration space field at offset 0x72, size 2. This may be harmless, but if you have problems with your device:
               1) see permissive attribute in sysfs
               2) report problems to the xen-devel mailing list along with details of your device obtained from lspci.
```
Check if enabling permissive mode helps, see https://www.qubes-os.org/doc/pci-devices/#permissive

**Comment by iprid23** [comment]
@Pixistick have you tried an older kernel? Like 4.19 or even 4.14?

**Comment by Pixistick** [comment]
I tried the setting the no-strict-reset=true, but the interfaces still reset. The only kernel options I currently have are 4.14.119 or 4.14.74 and still reset the interfaces.

**Comment by marmarek** [comment]
Try `permissive=true` too.

**Comment by Pixistick** [comment]
Set both permissive=true and no-strict-reset=true and no change.

[sys-net-log-permissive-nostrictreset.txt](https://github.com/QubesOS/qubes-issues/files/3465428/sys-net-log-permissive-nostrictreset.txt)

**Comment by Pixistick** [comment]
Attached is logs from dom0 and output from qvm-pci for sys-net. Looks like pciback "can't write" errors are for a couple USB controllers.

[dom0-permissive-nostrictreset-log.txt](https://github.com/QubesOS/qubes-issues/files/3474467/dom0-permissive-nostrictreset-log.txt)
[sys-net-pci-settings.txt](https://github.com/QubesOS/qubes-issues/files/3474468/sys-net-pci-settings.txt)
