### ISSUE TITLE
Create mutiple mouses

### ISSUE THREAD

**Issue by stopthisbruh69** [QubesOS/qubes-issues#5218]
### Describe the solution you'd like
_So the title is probably weird and not understandable to some. But let me explain. For example you wanna have an automated action in an AppVM via the terminal using xdotool. I also wanna be browsing at the same time in a different AppVM. So right now it isn't possible to duplicate a mouse pointer. But what if you could do Ctrl+Shift + Right+Left Click at the same time and create a new mouse that you can move to an AppVM with the "drag and drop" feature and "attach" a mouse pointer to it specifically? It would be the same as in VirtualBox where you have two pointers, one for dom0, one for a VM_

### Where is the value to a user, and who might that user be?
_Every user can benefit from this. From "paranoid" to regular users. I can guarantee if this feature only existed people would find it very useful. You have an AppVM that needs frequent attention but still has to do other work inside another AppVM that needs it's own mouse pointer and to not interrupt the other AppVM at the same time._

### Additional context
_
**Why that shortcut combo?**
Ctrl+Shift was taken from the "Copy and Paste between domains" feature. And to not be duplicating pointers everywhere I thought 'why not use both Left and Right click at the same time' which is never used. 

**How does it work?**
Ctrl+Shift + Left+Right Click = will create a floating movable mouse beside the real one and by hovering over opened AppVMs an outline will appear to "attach" the mouse to. After it is attached it can not "escape"(touch) other AppVMs. It should still be freely used around the whole screen except it cannot touch anything outside of the attached AppVM.

**How can I switch between pointers?**
To Switch between mouse pointers, a simple Ctrl+Shift + Scroll with the mouse will change pointers like the workspace switcher.

**How do I delete/remove a mouse pointer?**
To delete/remove a mouse pointer, a simple Ctrl+Shift + Scroll Click with the mouse in the AppVM will delete the current actively used mouse pointer. Deleting the original dom0 pointer will not work. The Scroll Click was taken from the way you can close tabs and windows with._

**Comment by marmarek** [comment]
If automation would be about a single AppVM only, you can do it by running `xdotool` within that AppVM and simply avoiding other interaction with that AppVM at the time. It isn't exactly second mouse pointer - it's the same - but if you don't interact with given AppVM, then actions with other AppVMs won't interfere.

Other than that, I'm afraid we can't realistically do this. Multiple mouse pointers are against multiple fundamental assumptions within graphics subsystem (notably Xorg). A lot of parts of the system assume there is just one, including features like following focus (no two windows can have a focus at once) etc. Changing that would require redesigning a lot of graphics stack, something that definitely isn't a focus of Qubes OS project. Especially given quite niche use case.
