### ISSUE TITLE
Opening Big Text Files leading to hanging 

### ISSUE THREAD

**Issue by TNTBOMBOM** [QubesOS/qubes-issues#5221]
**Qubes OS version**

4.0.1

**Affected component(s) or functionality**

Memory/CPU insufficient handling of large loading/reading process?

**Brief summary**

Opening large text files will lead to appvm hanging to couple of seconds.
Searching for a letter lets say D or A in large text will lead to full appvm (or at least the text editor itself)  hanging. 

**To Reproduce**

- Open large text file with text editor.
- ctrl+f and try searching for lets say D letter.

**Expected behavior**

Not to hang as long as there is enough memory/cpu and ssd hard drive

**Actual behavior**

hanging and wont go away unless you kill the process thus useless case

**Screenshots**

N/A

**Solutions you've tried**

Tried to turn off memory balancer and increased the memory to 4GB i got the same issue. 

**Test Sample**

This is big log of journalctl of dom0:

https://anonfile.com/icb5282fnd/file_text

**Comment by marmarek** [comment]
> Tried to turn off memory balancer and increased the memory to 4GB i got the same issue.

Can you confirm (for example looking at domains widget menu) that appvm indeed had 4GB memory?

Anyway, most likely the application you tried to use isn't designed to handle large files, nothing specific to qubes.
For example `vim` handle large files poorly, but `less` does the job.

**Comment by TNTBOMBOM** [comment]
> Can you confirm (for example looking at domains widget menu) that appvm indeed had 4GB memory?

Yes

>Anyway, most likely the application you tried to use isn't designed to handle large files, nothing specific to qubes.

i used the xfce mousepad. i cant make sure here maybe the text editor itself, thats probable .

**Comment by TNTBOMBOM** [comment]
but just one thing to make sure this is not a bug: 

> Can you confirm (for example looking at domains widget menu) that appvm indeed had 4GB memory?

it solved the issue after restarting the appvm. 

But wait a secon, isnt memory balancing should as well push the memory needs for an application or an appvm to the max if its needed to do that? 

because the default is 400mb to 4GB, so what i did i just turned off the memory balancing but kept the same max memory attached to it.

**Comment by marmarek** [comment]
Memory balancing is designed to give enough memory to run applications in all qubes, _as long as it doesn't starve other qubes_. If you assign 4GB statically, if you don't have that much free memory, qube won't start. But if you assign 4GB max with balancing enabled - if you don't have that much free RAM, qube will run at lower size (possibly using swap, which is slow).
