### ISSUE TITLE
4.0.1 install stuck on reboot: Restarting system after Successful install x86_64

### ISSUE THREAD

**Issue by JustHereToHelp** [QubesOS/qubes-issues#5222]
**Qubes OS version**
4.0.1

**Affected component(s) or functionality**
Booting after successful install on x86_64 with UEFI boot

**Brief summary**
after fresh install of verified 4.0.1 via DD usb, reboot is required and errors at this screen:
 Black screen with [terminated] [1815.571706] reboot : Restarting system.
System never restarts and a force reboot goes to a black screen.

**To Reproduce**
_Steps to reproduce the behavior:_
_1. Fresh install of 4.0.1 via dd usb
_2. Complete install and press reboot button
_3. Reboot hangs at screen with message :[terminated] [1815.571706] reboot : Restarting system.
_4. Force reboot goes to black screen

**Expected behavior**
Reboot should reboot with a completed install

**Actual behavior**
Reboot hangs at completely black screen with message [terminated] [1815.571706] reboot : Restarting system.

**Comment by JustHereToHelp** [comment]
Switching to Legacy boot fixed the issue.

**Comment by Kiryoko** [comment]
> Switching to Legacy boot fixed the issue.

What if I'm on a pc that doesn't have legacy boot anymore? Lenovo removed it in 2020 😅
