### ISSUE TITLE
qui-devices can become stale

### ISSUE THREAD

**Issue by jpouellet** [QubesOS/qubes-issues#5223]
### Qubes OS version:

r4.0.2-rc1 / qubes-desktop-linux-manager-4.0.20-1.fc25.noarch

### Affected component(s) or functionality:

qui-devices tray (qubes-manager)

### Steps to reproduce the behavior:

1. Start a DispVM
1. Attach one or more devices
1. Somehow terminate the DispVM (either shutdown or killing)
1. Repeat

### Expected or desired behavior:

The devices tray to show the same information as `qvm-block`

### Actual behavior:

![stale-devices](https://user-images.githubusercontent.com/1231207/62585799-8b154200-b888-11e9-8eee-084cbfa73fd3.png)

### General notes:

I noticed this in a DispVM which probed an LVM pool with many (several hundred) devices.

### I have consulted the following relevant [documentation](https://www.qubes-os.org/doc/):

- https://www.qubes-os.org/doc/block-devices/
- https://www.qubes-os.org/doc/usb-devices/
- https://www.qubes-os.org/doc/device-handling/

### I am aware of the following related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues:

Seemingly similar state-desynchronization issues:
- https://github.com/QubesOS/qubes-issues/issues/3525
- https://github.com/QubesOS/qubes-issues/issues/4878
- https://github.com/QubesOS/qubes-issues/issues/4849

**Comment by marmarta** [comment]
are you using the current-testing repo? ( https://www.qubes-os.org/doc/software-update-dom0/#testing-repositories )

**Comment by marmarta** [comment]
it should have been fixed in https://github.com/QubesOS/qubes-desktop-linux-manager/commit/2056e1ae2d8d6b3f986e09bd498e99711a1b4359 and looks like it works on my side; if you still experience this issue while using current-testing repository, please reopen this issue.
