### ISSUE TITLE
Missing systemd unit dependencies

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#5224]
### Qubes OS version:

`Qubes release 4.0 (R4.0)`

### Affected component(s) or functionality:

`qubes-core-agent`, mostly.

---

### Steps to reproduce the behavior:

Run code in `/rw/config/rc.local` that needs to run before interactive login.  Run `systemctl status` after boot, and have `/var/log` mentioned in `/rw/config/qubes-bind-dirs.d/50_user.conf`.

### Expected or desired behavior:

`/rw/config/rc.local` has already run before logins happen.  All user sessions are registered appropriately with `systemd-logind`, and user processes are in the appropriate cgroups.  `journalctl -b` shows all logs since AppVM boot.  Furthermore, `u2mfn.ko.xz` is built if needed.

### Actual behavior:

It has not always already run.  Furthermore, user processes are not always in the appropriate units, and early boot logs are missing.  `u2mfn.ko.xz` is not built automatically at boot.

### General notes:

The culprit is missing systemd unit dependencies.  Specifically:

* All services that log users in must include `After=systemd-logind.service`.
* `qubes-mount-dirs.service` must include `Before=systemd-journald.service`.
* `systemd-user-sessions.service` must have `After=` dependencies on `qubes-misc-post.service` and `rc-local.service`.
* `qubes-misc-post.service` must have an `After=` dependency on `user.slice` and `rc-local.service`.
* `multi-user.target` needs a `Wants=` and `After=` dependency on `dkms.service`.

---

**Comment by marmarek** [comment]
This all very much depends on a specific configuration of your VM. For example ordering of `qubes-mount-dirs.service` very much depends on what dirs you put in bind-mounts config. In your case it was about `/var/log` and `systemd-journald`, but that's just one specific case. In default confguration `/var/log` isn't there and adding such dependency is pointless (and will also slow down the VM startup).
Same applies to rc.local - it very much depends on what you put there.
`dkms.service` is interesting case - `u2mfn` module should be either already included in the kernel (if provided from dom0), or build on kernel installation (if in-vm kernel is used), not VM start time. Can you provide more details about the environment, how you get this situation? Preferably in a new issue.

As for this issue, unless I'm missing something, this is _at most_ documentation issue (but not sure if even this), that some modifications to rc.local or bind-dirs may require adding extra service ordering.
But this applies to many more things and I don't think it's really qubes specific.

**Comment by andrewdavidwong** [comment]
> As for this issue, unless I'm missing something, this is _at most_ documentation issue (but not sure if even this), that some modifications to rc.local or bind-dirs may require adding extra service ordering.
> But this applies to many more things and I don't think it's really qubes specific.

Closing as "not an issue." If you believe this is a mistake, please leave a comment, and we'll be happy to take another look. Thank you.
