### ISSUE TITLE
Buidling Ubuntu template error due to format-error in module-vchan-sink.c

### ISSUE THREAD

**Issue by Rot127** [QubesOS/qubes-issues#5227]
### Qubes OS version:

Qubes release 4.0 (R4.0)

### Affected component(s) or functionality:

Qubes-Builder building pulse for Ubuntu

---

### Steps to reproduce the behavior:

make qubes-vm

### Actual behavior:

Doing "make qubes-vm" to build a Ubuntu template the building process cancels while building "gui-agent-linux":

```
rm -f pulse/pulsecore
ln -s pulsecore-11.1 pulse/pulsecore
make -C pulse module-vchan-sink.so
make[3]: Entering directory '/home/user/qubes-src/gui-agent-linux/pulse'
gcc -Wall -Wextra -Werror -O2 -g -c `pkg-config --cflags vchan-xen` -fPIC module-vchan-sink.c  -DHAVE_CONFIG_H -I.
module-vchan-sink.c: In function 'module_vchan_sink_LTX_pa__init':
module-vchan-sink.c:681:12: error: format not a string literal and no format arguments [-Werror=format-security]
            DEFAULT_SINK_DESC));
            ^~~~~~~~~~~~~~~~~
module-vchan-sink.c:729:7: error: format not a string literal and no format arguments [-Werror=format-security]
       pa_modargs_get_value(ma, "source_desc", DEFAULT_SOURCE_DESC));
```

### General notes:

The gcc compiler version is up to date (8.3.1).

---

### I am aware of the following related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues:

Any of the "Ubuntu template isn't building"-like issues.

**Comment by unman** [comment]
Works for me.
@Rot127 Which Ubuntu version? Which Qubes version did you select to build?

**Comment by unman** [comment]
Never mind - you're building 4.1 and it works for me because I already patched it.
@marmarek  I've added -Wno-error=format-security in pulse/Makefile to allow build
Would this be OK across the board?

**Comment by Rot127** [comment]
@unman Worked flawlessly. Thank you for the quick patch.
