### ISSUE TITLE
Missing manpages for qrexec commands

### ISSUE THREAD

**Issue by pierwill** [QubesOS/qubes-issues#5229]
Some qrexec commands do not have manpages. (This was also mentioned in https://github.com/QubesOS/qubes-core-qrexec/issues/1.)

`qrexec-client-vm` currently does have a [manpage](https://github.com/QubesOS/qubes-core-qrexec/blob/master/agent/qrexec-client-vm.rst). (We also have `man qrexec-policy-graph`.)

It'd be nice to have most if not all of these:

- `man qrexec-client`
- `man qrexec-daemon`
- `man qrexec-policy`
- `man qrexec-policy-agent`
- `man qrexec-fork-server`

People could probably benefit from having even stubs for these commands. 

As the main qrexec documentation is revised (work has started with https://github.com/QubesOS/qubes-doc/pull/847), these manpages should be easier to produce.

**Comment by 3hhh** [comment]
Also missing:

`man  qvm-console`
`man qvm-connect-tcp`

Something like `qvm-console --help` or `qvm-console -h` usually doesn't work either.
