### ISSUE TITLE
Downloading some dom0 packages with Debian-based updatevm fails

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#5233]
**Qubes OS version**

R4.1 (fc29 dom0)

**Affected component(s) or functionality**

qubes-dom0-update, core-agent-linux?

**Brief summary**

Downloading some packages fails, because `yumdownloader` is unable to handle new dependencies format used in fc29.

**To Reproduce**
1. Set Debian-based updatevm
2. Call `sudo qubes-dom0-update redhat-rpm-macros`  in dom0

**Expected behavior**
Package is installed.

**Actual behavior**
Resolving dependencies fails:
```
---> Package redhat-rpm-config.noarch 0:119-1.fc29 will be installed
Traceback (most recent call last):
  File "/usr/bin/yumdownloader", line 327, in <module>
    util = YumDownloader()
  File "/usr/bin/yumdownloader", line 71, in __init__
    self.main()
  File "/usr/bin/yumdownloader", line 99, in main
    self.exit_code = self.downloadPackages(opts)
  File "/usr/bin/yumdownloader", line 211, in downloadPackages 
    result, resultmsgs = self.resolveDeps()
  File "/usr/lib/python2.7/dist-packages/yum/depsolve.py", line 751, in resolveDeps 
    CheckDeps, checkinstalls, checkremoves, missing = self._resolveRequires(errors)
  File "/usr/lib/python2.7/dist-packages/yum/depsolve.py", line 861, in _resolveRequires 
    thisneeds = self._checkInstall(txmbr)
  File "/usr/lib/python2.7/dist-packages/yum/depsolve.py", line 936, in _checkInstall
    provs = self.tsInfo.getProvides(*req)
  File "/usr/lib/python2.7/dist-packages/yum/transactioninfo.py", line 581, in getProvides 
    result = self.getOldProvides(name, flag, version)
  File "/usr/lib/python2.7/dist-packages/yum/transactioninfo.py", line 574, in getOldProvides
    for pkg, hits in self.rpmdb.getProvides(name, flag, version).iteritems():
  File "/usr/lib/python2.7/dist-packages/yum/rpmsack.py", line 1397, in getProvides
    pkgs = self.searchProvides(name)
  File "/usr/lib/python2.7/dist-packages/yum/rpmsack.py", line 485, in searchProvides
    ret = self.searchPrco(name, 'provides')
  File "/usr/lib/python2.7/dist-packages/yum/rpmsack.py", line 455, in searchPrco
    (n,f,(e,v,r)) = misc.string_to_prco_tuple(name)
  File "/usr/lib/python2.7/dist-packages/yum/misc.py", line 704, in string_to_prco_tuple
    raise Errors.MiscError, 'Invalid version flag: %s' % f
yum.Errors.MiscError: Invalid version flag: if
```

**Additional context**
```
$ rpm -qR redhat-rpm-config | head -1
(annobin if gcc)
```

Downloading dom0 updates in Debian-based VM use `yum-utils` package, as `dnf` isn't available in Debian.

**Comment by steakknife** [comment]
I'm seeing this in 4.1rc1. Also a ton of "No Match for argument" messages beforehand.

**Comment by darreal44** [comment]
In qubes Global preferences
You need to change to sys-firewall 
Then it works.

**Comment by unman** [comment]
On Sun, Dec 19, 2021 at 01:12:00PM -0800, darreal44 wrote:
> In qubes Global preferences
> You need to change to sys-firewall 
> Then it works.
> 

Well, obviously this wont work if you have a Debian based sys-firewall,
and haven't addressed the actual issue.

**Comment by ydirson** [comment]
After install with only debian-11 template, the first issue I see with updatevm (when attempting to launch `qubes-download-dom0-updates.sh` manually in `sys-firewall`) is not the above error, but missing directories in `/var/lib/qubes/dom0-updates/`: `/var/lib/rpm` and `/etc/yum.repos.d/` (and complains there are no enabled repos in the latter).

**Comment by h01ger** [comment]
On Sat, Jan 22, 2022 at 02:46:47PM -0800, Yann Dirson wrote:
> After install with only debian-11 template, the first issue I see with updatevm (when attempting to launch `qubes-download-dom0-updates.sh` manually in `sys-firewall`) is not the above error, but missing directories in `/var/lib/qubes/dom0-updates/`: `/var/lib/rpm` and `/etc/yum.repos.d/` (and complains there are no enabled repos in the latter).

do you have dnf and rpm installed in that template?


-- 
cheers,
	Holger

 ⢀⣴⠾⠻⢶⣦⠀
 ⣾⠁⢠⠒⠀⣿⡁  holger@(debian|reproducible-builds|layer-acht).org
 ⢿⡄⠘⠷⠚⠋⠀  OpenPGP: B8BF54137B09D35CF026FE9D 091AB856069AAA1C
 ⠈⠳⣄

If you upload your address book to "the cloud", I don't want to be in it.

**Comment by ydirson** [comment]
This is the standard debian-11 template, so I assume yes - though I can't check, I've nuked that non-functional install already.

**Comment by h01ger** [comment]
On Sun, Jan 23, 2022 at 04:15:01AM -0800, Yann Dirson wrote:
> This is the standard debian-11 template, so I assume yes - though I can't check, I've nuked that non-functional install already.

the standard debian-11 template doesn't have dnf nor rpm.


-- 
cheers,
	Holger

 ⢀⣴⠾⠻⢶⣦⠀
 ⣾⠁⢠⠒⠀⣿⡁  holger@(debian|reproducible-builds|layer-acht).org
 ⢿⡄⠘⠷⠚⠋⠀  OpenPGP: B8BF54137B09D35CF026FE9D 091AB856069AAA1C
 ⠈⠳⣄

If it feels like we’re breaking climate records every year, it’s because we are.

**Comment by ydirson** [comment]
> the standard debian-11 template doesn't have dnf nor rpm.

That would explain, but I'm surprised: the debian-11 template downloaded on my main laptop (0:4.0.6-202110081812, which `qvm-template` seems to show as current) does have them.  How is this possible ?

**Comment by h01ger** [comment]
On Sun, Jan 23, 2022 at 07:30:43AM -0800, Yann Dirson wrote:
> > the standard debian-11 template doesn't have dnf nor rpm.
> That would explain, but I'm surprised: the debian-11 template
> downloaded on my main laptop (0:4.0.6-202110081812, which
> `qvm-template` seems to show as current) does have them. 
> How is this possible ?

well, either the template has them or not. so either your or my
statement is wrong. :)

anyhow, if the template has the packages I guess the directories
you mentioned in this bug are missing. Can you check?


-- 
cheers,
	Holger

 ⢀⣴⠾⠻⢶⣦⠀
 ⣾⠁⢠⠒⠀⣿⡁  holger@(debian|reproducible-builds|layer-acht).org
 ⢿⡄⠘⠷⠚⠋⠀  OpenPGP: B8BF54137B09D35CF026FE9D 091AB856069AAA1C
 ⠈⠳⣄

This too shall pass.

**Comment by unman** [comment]
[quote]
well, either the template has them or not. so either your or my
statement is wrong. :)
[/quote]

The template has rpm and dnf.

The template is also missing those directories, but a debian-11-dvm
works fine for me as UpdateVM.
I don't believe I configured the template in any way.
I use testing repositories.

**Comment by ydirson** [comment]
Several things are not clear to me:
- if `/usr/lib/qubes/qubes-download-dom0-updates.sh` needs those dirs to be there, who's supposed to create them ?
- how is this supposed to work when `sys-firewall` is disposable, which is the default in the 4.1-rc3 installer GUI ?

This script seems to populate  `/etc/yum.conf` under `$DOM0_UPDATES_DIR`, but that seems to be all of the conf it populates, isn't it missing something ?

**Comment by unman** [comment]
At risk of repeating myself, the standard 4.1 debian-11 template has
rpm and dnf, does not have those directories, and dom0 updates work in
a disposable updateVM.

Unless any one can replicate the original issue on an updated system,
I think this issue could be closed.

Take discussion of the internals elsewhere - HINT: you aren't supposed to
run `/usr/lib/qubes/qubes-download-dom0-updates.sh` by hand. Look at
qubes-dom0-update.

**Comment by ydirson** [comment]
> Unless any one can replicate the original issue on an updated system, I think this issue could be closed. 

The procedure is quite simple, although it was done with a rc3 not rc4 install media:
- install with only debian-11 templates
- enable `sys-gui-gpu`

The problem I have with the "Unless any one can replicate" is that it does not factor in whether anyone actually tried to replicate ;)

>Take discussion of the internals elsewhere - HINT: you aren't supposed to run `/usr/lib/qubes/qubes-download-dom0-updates.sh` by hand. Look at qubes-dom0-update.

I'm only trying to launch that script by hand because it is the one reporting an error when attempting to install `dummy-psu` while configuring `sys-gui-gpu`.

**Comment by ydirson** [comment]
I realize I did not kept a copy of the error.  It was a failure of the `dummy-psu-dom0: pkg.installed` part of `sys-gui-gpu.sls`, and there was no clear error displayed, other than that this `qubes-download-dom0-updates.sh` script returned an error - which naturally prompted me to dig into this by attempting to reproduce by launching manually in `sys-firewall` the script with the arguments listed in the error message.

**Comment by unman** [comment]
This issue had a clear error message, with the root cause being the
absence of dnf in what was (I think) a debian-10 template.
You know that the debian-11 template has dnf installed.
I'm somewhat puzzled as to why you think it is the same error as this
issue.

**Comment by ydirson** [comment]
OK let's say it is a different issue, I can rerun that install and provide more details.  But before that I had an even uglier issue for which I can use some help to be able to produce a suitable bugreport without necessarily go through another full reinstall (https://forum.qubes-os.org/t/test-installing-on-usb3-stick-error-checking-storage-configuration/8850/7)

**Comment by unman** [comment]
The latest reason for holding this open was failure to install non existent packages, #7230, not an issue with Debian updates.
@ydirson has agreed that his was a separate issue, the original issue is long settled by move to Debian-11 in 4.1, this should be closed.
@andrewdavidwong - please close.
