### ISSUE TITLE
Wrong Policy applied for DisposableVM by qvm-open-in-vm 

### ISSUE THREAD

**Issue by neowutran** [QubesOS/qubes-issues#5235]
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
qvm-open-in-vm and Qubes Policy

**Brief summary**
qvm-open-in-vm is not always using the correct Qubes Policy

**To Reproduce**
From the doc, tried to execute a command similar to ``$ qvm-open-in-vm @dispvm:online-dvm-template https://www.qubes-os.org``

In my case it was ``qvm-open-in-vm @dispvm:web https://www.qubes-os.org``.
The content of my config file ``/etc/qubes-rpc/policy/qubes.OpenURL`` is 
```
$anyvm $dispvm allow
$anyvm $anyvm ask
```

**Expected behavior**
Command executed without popup.

**Actual behavior**
Saw a popup asking for permission (``[dom0] Operation execution``, ``qubes.OpenURL``)

**Solutions you've tried**
It work if I modify the file ``/etc/qubes-rpc/policy/qubes.OpenURL to
```
$anyvm $dispvm allow
$anyvm $anyvm allow
```
However, I should not have to modify the file. Since the command I executed say: Create a new disposable VM based on the "web" Template, the policy that should be applied is ``$anyvm $dispvm``, not ``$anyvm $anyvm``. 

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
https://www.qubes-os.org/doc/disposablevm/

**Comment by unman** [comment]
To achieve what you want you need :
`$anyvm @dispvm:web allow`
Otherwise Qubes is going to ask you to confirm *which* dispvm you want.

Or set web as default_dispvm for the calling qube and it will work as you expect with no change in rules. with `qvm-open-in-dvm`

**Comment by neowutran** [comment]
Hi, 
Thanks, I confirm that it is working :) 

I searched this syntax on the documentation, found https://www.qubes-os.org/doc/qrexec3/#extra-keywords-available-in-qubes-40-and-later . 

The page need to be a bit refreshed: ``This section is about a not-yet-released version, some details may change`` ( about Qubes R4.0 )

From the syntax, it is not obvious that ``$dispvm`` refer to the default dispvm and not every dispvm, but I guess it is because of historical reason since multiple disposableVM template are only possible since Qubes R4.0. 

Anyway, I will try to do a pull request for https://www.qubes-os.org/doc/disposablevm/#opening-a-link-in-a-disposablevm-based-on-a-non-default-disposablevm-template-from-a-qube to add a link to https://www.qubes-os.org/doc/qrexec3/#extra-keywords-available-in-qubes-40-and-later and to add your solution for the policy ``$anyvm @dispvm:online-dvm-template allow``

**Comment by neowutran** [comment]
Documentation have been updated
