### ISSUE TITLE
Github repositories require login

### ISSUE THREAD

**Issue by unman** [QubesOS/qubes-issues#5236]
**Qubes OS version**
4.0

**Affected component(s) or functionality**
Builder

**Brief summary**
Attempt to build 4.1
tpm_extra and trousers-changer require login

**To Reproduce**
_Steps to reproduce the behavior:_
_1. Attempt to build 4.1
_2. make get-sources

**Expected behavior**
Sources will be downloaded

**Actual behavior**
Prompt for github login

**Comment by jandryuk** [comment]
Seems like the new repo was not created or made public? https://github.com/QubesOS/qubes-tpm-extra returns 404 for me.

**Comment by unman** [comment]
Not yet created in QubesOS I think

**Comment by fepitre** [comment]
It is because we forgot to make it public after splitting qubes-antievilmaid. We will fix that.

**Comment by unman** [comment]
On Sun, Aug 11, 2019 at 07:41:57AM -0700, Fr??d??ric Pierret wrote:
> It is because we forgot to make it public after splitting qubes-antievilmaid. We will fix that.
> 
Cheers

**Comment by fepitre** [comment]
Done :)
