### ISSUE TITLE
WiFi does not work if template VM updated 

### ISSUE THREAD

**Issue by qrueky** [QubesOS/qubes-issues#5238]
**Qubes OS version**
Qubes release 4.0 (R4.0)

**Affected component(s) or functionality**
WiFi stops working if template VM (fedora 29) is updated

**Brief summary**
WiFi works fine when Qubes OS is installed but stops working on updating template VM (fedora 29), I reinstalled Qubes OS and made a backup before updating fedora 29 template VM but no luck it still doesn't work after updating fedora 29 template VM, I restored the backup fedora 29 VM and using same for WiFi. Currently I have both the fedora 29 template VM, the out of the box one and the updated one. 

**To Reproduce**
Update the fedora 29 template VM and try to use WiFi

**Expected behavior**
After update fedora 29 template VM WiFi should work fine.

**Actual behavior**
After updating fedora 29 template VM WiFi stops working

**Screenshots**
I will attach it later

**Additional context**
WiFi device name which appears in "Device" tab under VM setting is as below.
"02:00.0 Network controller: Qualcomm Atheros QCA9377 802.11ac Wireless Network Adapter"
Let me know what I can provide, which log and where I can get it.

**Solutions you've tried**
I installed fedora template 30 and used it as base OS for net-VM also tried all available kernels but no luck.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

**Comment by SaswatPadhi** [comment]
I had the same issue with a Qualcomm WiFi card both for Fedora 28 and 29. Installing `linux-firmware` on Fedora 29 template VM resolved it for me though.

1. Modify sys-net to use the old Fedora template VM so you can connect to WiFi
2. Install `linux-firmware` on Fedora 29
3. Use Fedora 29 template for sys-net and test if WiFi works

Hope this helps!

**Comment by SaswatPadhi** [comment]
This issue can probably be closed now. Newer Fedora VMs (31,32,33,34) all seem to work fine.
