### ISSUE TITLE
admin.vm.volume.Import fails for payloads larger than 2GiB

### ISSUE THREAD

**Issue by jpouellet** [QubesOS/qubes-issues#5239]
The symptoms manifest as:
```
  File "/usr/lib/python3.7/site-packages/qubesadmin/storage.py", line 224, in import_data
    self._qubesd_call('Import', payload_stream=stream)
  File "/usr/lib/python3.7/site-packages/qubesadmin/storage.py", line 76, in _qubesd_call
    payload_stream=payload_stream)
  File "/usr/lib/python3.7/site-packages/qubesadmin/app.py", line 663, in qubesd_call
    'Service call error: %s', stderr.decode())
qubesadmin.exc.QubesDaemonNoResponseError: Service call error: 
```

The chain of causes is:
- [`QubesRemote.qubesd_call()` throwing on non-zero exit of qrexec-client-vm](https://github.com/QubesOS/qubes-core-admin-client/blob/b8ddb39752b2bb34315044666d59661cbbc0c4c2/qubesadmin/app.py#L647-L649)
- surprisingly not actually caused by anything in dom0 - the admin.vm.volume.Import call returns 0 totally fine
- internally caused in qrexec-client-vm [somewhere in qrexec-agent-data.c process_child_io()](https://github.com/QubesOS/qubes-core-qrexec/blob/master/agent/qrexec-agent-data.c#L320-L521) returning -1 seemingly as a result of there remaining data on stdin after the remote rpc side has closed its input (and the -1 is propagated back to qrexec-agent-vm process exit and sign-dropped to 255)

demonstration of the relevant parts of the admin.vm.volume.Import implementation operating fine individually:
```
[user@dom0 ~]$ qubesd-query -e disp3470 admin.vm.volume.Import genode-devel private > /tmp/f; echo ret=$?; hexdump -C /tmp/f
ret=0
00000000  30 00 32 31 34 37 34 38  33 36 34 38 20 2f 64 65  |0.2147483648 /de|
00000010  76 2f 71 75 62 65 73 5f  64 6f 6d 30 2f 76 6d 2d  |v/qubes_dom0/vm-|
00000020  67 65 6e 6f 64 65 2d 64  65 76 65 6c 2d 70 72 69  |genode-devel-pri|
00000030  76 61 74 65 2d 69 6d 70  6f 72 74                 |vate-import|
0000003b
[user@dom0 ~]$ # the dd just ignores trailing stdin
[user@dom0 ~]$ echo -n ok | qubesd-query -c /var/run/qubesd.internal.sock disp3470 internal.vm.volume.ImportEnd genode-devel private > /tmp/f; echo ret=$?; hexdump -C /tmp/f
ret=0
00000000  30 00                                             |0.|
00000002
```

demonstration of dd not consuming input beyond its output quota, leaving data undrained in stdin and exiting zero:
```
$ echo foo bar | ( dd bs=4 count=1 > /dev/null; echo ret=$?; cat)
1+0 records in
1+0 records out
4 bytes copied, 4.1481e-05 s, 96.4 kB/s
ret=0
bar
```

demonstration of the qrexec-client-vm invocation exiting non-zero with inputs larger than 2GiB:
```
[user@disp3470 ~]$ dd if=/dev/zero bs=$((1024*1024)) count=2048 | qrexec-client-vm genode-devel admin.vm.volume.Import+private > /tmp/f; echo ret=$?; hexdump -C /tmp/f
2048+0 records in
2048+0 records out
2147483648 bytes (2.1 GB, 2.0 GiB) copied, 8.90376 s, 241 MB/s
ret=0
00000000  30 00                                             |0.|
00000002
[user@disp3470 ~]$ dd if=/dev/zero bs=$((1024*1024)) count=2049 | qrexec-client-vm genode-devel admin.vm.volume.Import+private > /tmp/f; echo ret=$?; hexdump -C /tmp/f
ret=255
00000000  30 00                                             |0.|
00000002
```

qubesd also emits import success events internally, and has no idea it failed:
```
genode-devel: domain-volume-import-begin {'volume': 'private'}
genode-devel: domain-volume-import-end {'success': 'True', 'volume': 'private'}
```

---

One proposed solution:
- In /etc/qubes-rpc/admin.vm.volume.Import, after the dd, try to consume from stdin. If there is anything to read, fail with an error. The indication of failure can then be propagated to the internal.vm.volume.ImportEnd call. This will make core-admin (instead of only core-admin-client) aware that something has failed, because it is detected on the dom0 side instead of only the client side via unread stdin (which may break in the future over alternate qrexec transports anyway).
- Optionally also have volumes created by admin.vm.Create.* start with no (or as little as possible) capacity, to eagerly detect qubes-admin-client consumers which do not appropriately call admin.vm.volume.Resize before admin.vm.volume.Import.

Alternative solution:
- Incrementally/dynamically grow the volume being imported as it's imported. This has the benefit of being easier, not needing to know the full size in advance (better supports streaming restores), and is easier to use for client consumers. However, it is also another resource-exhaustion DoS attack, and does not make it convenient to hook only admin.vm.volume.Resize in extensions to implement resource limiting policies, and does not map well to storage backends which expect full front-loaded resource pre-allocation.

From a backend perspective I prefer the former. From a client perspective I prefer the latter.

**Comment by jpouellet** [comment]
Actually: admin.vm.volume.Import intentionally does not mess with the existing data until the copy of new data has been successful. It seems a violation of this principle for the larger import action to require both a resize call and an import call, because the resize call might conceivably truncate the existing volume and then the subsequent import fail, causing harm that .Import was designed to avoid. It seems like there should be a way to specify size & data atomically. Neither proposed above solution does this alone, and it's not obvious how to achieve this cleanly in a backwards-compatible way.

**Comment by marmarek** [comment]
There is a special case for resize operation during the import. The way it's supposed to work is:
1. Open `admin.vm.volume.Import` call
2. Resize the volume (it will affect the current import)
3. Send the data

It isn't ideal, but it kind of works. I think a better approach to handle original issue here is to have a separate call to confirm import operation. Something like `admin.vm.volume.Import` returning only an "import id" which can be later committed or discarded. But I don't know yet how to avoid all kind of failure modes here (leftover import volumes, concurrent import operations etc).
