### ISSUE TITLE
USB keyboard won't work in app VM in spite of being attached and recognised.

### ISSUE THREAD

**Issue by Collisio-Adolebitque** [QubesOS/qubes-issues#5242]
**Qubes OS version**
The version of Qubes OS: R3.2

**Affected component(s) or functionality**
USB

**Brief summary**
USB keyboard won't work in app VM in spite of being attached and recognised.

**Expected behavior**
Keyboard to function.

**Actual behavior**
* sys-usb sys VM is installed and functional.
* Hewlett Packard keyboard can be seen in the results of qvm-usb.
* Keyboard has been attached to the app VM with qvm-usb.
* Keyboard can be seen as device 002 on bus 002 in the app VM:

```
[user@testvm ~]$ lsusb
Bus 003 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 002 Device 002: ID 03f0:2b4a Hewlett-Packard
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
[user@testvm ~]$
```

**Additional context**
Typing on the keyboard produces no output.

**Solutions you've tried**
The keyboard works in other computers.  I tried changing the virt_type from PVM to HVM with no change in results.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
* https://www.qubes-os.org/faq/
* https://www.qubes-os.org/doc/usb-devices/

**Comment by iprid23** [comment]
Not sure if Qubes 3.2 is still supported. Anyway have you tried with another keyboard? Also what do ```xinput``` and ```dmesg``` say? Have you tried ```xev```?

**Comment by marmarek** [comment]
R3.2 isn't supported anymore, but you'd probably get the same effect on R4.0 too.
If you connect USB keyboard to a specific qube, it can work only there(*). This is probably not what you want. To make it work globally, there is a specific service for USB keyboard, see [here](https://www.qubes-os.org/doc/usb-qubes/#enable-a-usb-keyboard-for-login) for details.

(*) If you want to use it only in a specific qube, then look into X server logs in that qube (`~/.local/share/xorg/Xorg.0.log`). There may be some permission issue about X server accessing `/dev/input/event...` device. If that's the case, you may need to add an udev rule to make that device accessible to `qubes` group.

**Comment by andrewdavidwong** [comment]
Closing as "invalid" since R3.2 is no longer supported. However, for the reasons Marek pointed out, this would probably be closed as "not an issue" if it were reported against R4.0. Nonetheless, you can probably get further help with this on the `qubes-users` [mailing list](https://www.qubes-os.org/support/).
