### ISSUE TITLE
default file permissions - Qubes default /etc/sudoers.d/umask 0002 vs security-misc default umask 0006

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#5243]
Due to my work on [security-misc](https://github.com/Whonix/security-misc) (https://github.com/QubesOS/qubes-issues/issues/1885) and with one of its goals to implement strong linux user account separation, user access rights are important to be hardened.

It's been (somewhat related) acknowledged earlier that linux user account separation is a good long term security goal for Qubes to protect Xen in comment https://github.com/QubesOS/qubes-issues/issues/2695#issuecomment-301316132.

In my view, a compromised non-root, user account (hypothetically as an example user `man`) should not have access to files of other users. In Qubes, probably most importantly no user other than user `user` should have read access in the home folder of user `user`. This is currently not the case. To test: `sudo -u man ls /home/user`. This is most likely not only an issue in Qubes but in most Linux distributions.

Qubes ships file `/etc/sudoers.d/umask`. (By package `qubes-core-agent`.)

```
# Sudo's defualt umask is 077 so set sane default of 022
Defaults umask = 0002
Defaults umask_override
```

Overview of different umask settings:

----

security-misc

```
umask 0006
touch test1
ls -la test1
-rw-rw---- 1 root root 0 Aug 14 07:40 test1
```

----

Qubes

```
umask 0002
touch test2
ls -la test2
-rw-rw-r-- 1 root root 0 Aug 14 07:42 test2
```

----

alleged sudo default 077

```
umask 077
touch test4
ls -la test4
-rw------- 1 root root 0 Aug 14 07:43 test4
```

----

I do agree that "alleged sudo default 077" does not make sense. Due to Debian using [UPG](https://wiki.debian.org/UserPrivateGroups), it is really ok for the "group" (which is same as the user by default) to also have read/write access.
(Alleged meaning, I didi't check in Debian buster.)

As default umask [we](https://forums.whonix.org/t/change-default-umask) concluded that `006` is most appropriate. Description in human terms should take preference over description in digits (`006`). I.e. read/write for the owner as well as the UPG seems appropriate. "Others" however, i.e. others than the owner of the file or the UPG should not have read access to any files.

For consistency (principle of least surprise), unless there is a reason against it, umask should be the same for everything, i.e. for files created by user `user`, login through pam, ssh login, root login, su, sudo, etc.

Also I would say that most users creating a file (file permissions are really hard for new and even existing linux users), don't expect these to be globally readable by all users on the same system. Again, principle of least surprise. However, one could argue the opposite and say "this has been the default in Debian/Linux for years so we should not change it. I would disagree since repeating a mistake and security issue for years does not make it right and changing defaults is OK for a security focused operating system.

I hereby suggest to change Qubes default umask from 0002 to 0006.

**Comment by unman** [comment]
There are distinct issues here:

> This is currently not the case. To test: sudo -u man ls /home/user. This is most likely not only an issue in Qubes but in most Linux distributions.

In which template do you see this? It isn't in Debian or Fedora templates.

> Also I would say that most users creating a file (file permissions are really hard for new and even existing linux users), don't expect these to be globally readable by all users on the same system. 

Most users probably dont have any thought on this. :-(
Your proposal will break functionally in unforeseen (by you) ways, particularly for system accounts like man.
To take simple "man" example - if I create a manpage, and use `man -l newpage` I expect it to work. It wont on your proposal unless I change permissions. That violates the "principle of least surprise".
Other service accounts similarly affected.

**Comment by adrelanos** [comment]
I will reply to this soon.

But before... Changed my mind on which umask...

`-rw-rw----` (`umask 0006`) is actually not a great idea.

`-rw-r-----` (`umask 027`) seems better.

Detailed reasoning:
https://forums.whonix.org/t/change-default-umask/7416/47

> Debian default umask.
> 
>     umask 022
>     touch uuu
> > ls -la uuu
> > -rw-r--r-- 1 user user 0 Aug 17 09:22 uuu
> 
> Currently security.misc changes to 006.
> 
>     umask 0006
>     touch abc
> 
> > ls -la abc
> > -rw-rw---- 1 user user 0 Aug 17 09:23 abc
> 
> While we harden, while we remove `others` from reading files, we also relax permissions. We allow group members to write to files where they previously did not have write access. This looked ok due to UPG.
> 
> However, upon reflection, since we change this system wide, this may be a bad idea.
> 
> Some folders/files created by the system/packages are created with a different group. I.e. owner might be `root` but group might be `shadow`, `pip` or otherwise.
> 
> Examples:
> 
>     ls -la /etc/cups/subscriptions.conf
> > -rw-r----- 1 root lp 93 Jul 19 09:40 /etc/cups/subscriptions.conf
> 
>     sudo ls -la /etc/ssl/private/ssl-cert-snakeoil.key
> > -rw-r----- 1 root ssl-cert 1704 Mar 27  2018 /etc/ssl/private/ssl-cert-snakeoil.key
> 
> Therefore our hardening attempts might result in actually relaxing write access for group when the group is different than the owner. Debian packages might keep care of the required umask but there might also be bugs.
> 
> Similar bugs (which were about too much hardened rather than too relaxed permissions) reported above (`command-not-found`).
> 
> Therefore I am planning on changing default umask yet again.
> 
>     umask 027
>     touch test2
>     ls -al test2
> > -rw-r----- 1 user user 0 Aug 17 09:26 test2
> 
> Thereby we would harden permissions, i.e. `others` cannot read files but we also don't relax any permissions (as previously allow `group` to write).

**Comment by adrelanos** [comment]
> There are distinct issues here:
> 
> > This is currently not the case. To test: sudo -u man ls /home/user. This is most likely not only an issue in Qubes but in most Linux distributions.
> 
> In which template do you see this? It isn't in Debian or Fedora templates.

Can't reproduce at the moment.

How / at which stage are correct permissions set?

> > Also I would say that most users creating a file (file permissions are really hard for new and even existing linux users), don't expect these to be globally readable by all users on the same system.
> 
> Most users probably dont have any thought on this. :-(

Surely not something something starts thinking about without the subject coming up.
Well, ask them: would you expect that on a mulit user system random other users can read your files? Something good or bad?

> Your proposal will break functionally in unforeseen (by you) ways, particularly for system accounts like man.
> Other service accounts similarly affected.

Looks not so bad. I've build Non-Qubes-Whonix testers version (`15.0.0.3.9`) with this. No bugs triggered except for one in `command-not-found`. This one:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=916783
(workaround easy: `sudo chmod o+r /var/lib/command-not-found/commands.db*`)

(manpages functional.)

> To take simple "man" example - if I create a manpage, and use `man -l newpage` I expect it to work. It wont on your proposal unless I change permissions. That violates the "principle of least surprise".

Could you please provide instructions for reproduction? Ideally, something (similar to) that users do usually.

**Comment by adrelanos** [comment]
Some issues:

https://forums.whonix.org/t/change-default-umask/7416/46?u=patrick

Concluded not needed:

https://forums.whonix.org/t/change-default-umask/7416/55?u=patrick

home folder permission lockdown (i.e. running only once `chmod o-rwx /home/user`) is sufficient:

https://forums.whonix.org/t/change-default-umask/7416/42
