### ISSUE TITLE
Installer hangs on UHD Graphics 600/605 because of lack of support from i915 driver on Kernel 4.14/4.19, also noexitboot=1 leads to crash

### ISSUE THREAD

**Issue by iprid23** [QubesOS/qubes-issues#5247]
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
qubes-iso

**Brief summary**
The screen becomes black and nothing happens after loading Xen and then Linux kernel, then it says various things(services loaded by systemd) the last of which is LVM2 Pvscan and then the screen goes black.

**To Reproduce**
1. Boot Qubes from USB stick via EFI

**Expected behavior**
You can get to Anaconda

**Actual behavior**
A black screen before Anaconda

**Solutions you've tried**
Combinations of efi=no-rs and iommu=no-igfx, etc.

I am thinking maybe it's the old xorg-x11-drv-intel. Also I can't switch the tty after the black screen, so I can't read any logs...

**Comment by iprid23** [comment]
Update:
Attaching an external monitor changes the behavior, it gets to Anaconda, but it's very blurred, you can only see white lines and blue lines, like the whole image is fuzzed and looks like radio noise. So you cant read any letter at all. But it does not hang, you can switch between ttys. I wonder if I just need a kernel 5.2 instead of 4.19.

**Comment by iprid23** [comment]
Update:
The issue was complex:
1. noexitboot=1 lead to Xen crash
Removing noexitboot=1 solved it. If that does not help, just add efi=no-rs and disable EFI services.

2. Afterwards the problem was with Kernels 4.14 and 4.19's kernel module i915 not supporting some CPUs leading to a hang: When Anaconda starts, Xorg is started which changes the vesa driver for i915(if you have Intel). One workaround is to use Kernel 5.2 instead. But if you are using the official Qubes ISO with Kernel 4.14 - you can just blacklist i915 on the kernel boot line: module_blacklist=i915

Hence:
```
[qubes-workaround]
options=console=vga loglvl=all efi=no-rs
kernel=vmlinuz inst.stage2=hd:LABEL=Qubes-[Your label]-x86_64 module_blacklist=i915
ramdisk=initrd.img
```

@marmarek, @andrewdavidwong feel free to add this to some troubleshooting guide if you want to. Perhaps a lot of people will need this if they try to install Qubes with Kernel 4.14/4.19 on Intel laptops which require Kernel 5.2 i915.

**Comment by marmarek** [comment]
Can you give some details what hardware is affected?

**Comment by iprid23** [comment]
@marmarek 
I think it's safe to assume that this is valid for some Intel CPUs from 2018+, since I have not seen any issue with 7*** CPUs(Kabylake I think?) and below.
For example this CPU seems affected:
https://en.wikichip.org/wiki/intel/pentium_silver/n5000
Or maybe it's better to talk about the affected graphics:
UHD Graphics 600 or UHD Graphics 605
