### ISSUE TITLE
qubes builder requires local packages even if Pre-Built selected

### ISSUE THREAD

**Issue by unman** [QubesOS/qubes-issues#5250]
**Qubes OS version**
R4.0 updated
Fedora-30 builder

**Affected component(s) or functionality**
qubes-builder

**Brief summary**
qubes builder requires local packages even if Pre-Built packages selected

**To Reproduce**
_Steps to reproduce the behavior:_
_1. Run setup
_2. Select Pre-Built Packages Repositories
_3. Select Build Template Only
_4. Select Buster
_5. Save
_6. `make template`

**Expected behavior**
Template will  be built using Pre-built packages from selected repository.

**Actual behavior**
Build fails:
"Error opening '/home/user/qubes-builder/qubes-packages-mirror-repo/vm-buster/deb/qubes-mgmt-salt_4.0.19-1+deb10u1_amd64.changes'

**Additional context**
Quite possible that my expectations are wrong here.
If so, just close

**Solutions you've tried**
_If applicable, any solutions or workarounds you've already tried._

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
https://www.qubes-os.org/doc/qubes-builder/
That page refers to using Pre-Built when building "just a few selected packages"

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
_A list of links to other bug reports, feature requests, or tasks in the qubes-issues tracker (or "none" if you didn't find any). Do not describe any other unreported bugs, features, or tasks here._

**Comment by marmarek** [comment]
qubes-builder expects local packages for things mentioned in `COMPONENTS` setting. If you want to use pre-built package for particular component, remove it from `COMPONENTS`.
