### ISSUE TITLE
`pkg.latest` et al ignore `enablerepo` when in dom0

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#5252]
### Qubes OS version:

`Qubes release 4.0 (R4.0)`

### Affected component(s) or functionality:

Salt management stack

---

### Steps to reproduce the behavior:

Use `pkg.latest` with `enablerepo: qubes-dom0-current-testing`

### Expected or desired behavior:

Selected packages from `qubes-dom0-current-testing` are installed.

### Actual behavior:

These packages are not installed.

### General notes:

My use case is for the `kernel-qubes-vm` and `kernel-latest-qubes-vm` packages.

---

**Comment by unman** [comment]
Not, I think, a Qubes issue, but upstream.
There were numerous issues with pkg.latest in salt2017, that I don't see with later versions.

I don't know what `enablerepo` means in this context.
It isn't a parameter for `pkg.latest` - if you meant `fromrepo` I dont believe that will enable a repo that isn't already enabled, (and indeed in some of the 2017 family it would not work at all.)
If you enable the testing repo, then `pkg.latest` will indeed install the latest available version of `kernel-latest-qubes-vm`

If you cant confirm this please post your state files.
