### ISSUE TITLE
Install fails at language select screen: md_info is None

### ISSUE THREAD

**Issue by allenjs** [QubesOS/qubes-issues#5258]
**Qubes OS version**
R4.0.1 and 4.0.2-rc1

**Affected component(s) or functionality**

Install

**Brief summary**

Install fails at language select screen, MDRaid.MDFormatPopulator

**To Reproduce**

Install from USB boots to language select screen and fails with "unknown error has occurred".

More info reveals that mdraid.MDFormatPopulator throws AttributeError: NoneType object has no attribute 'uuid'.  Object being referenced is md_info, which is set to None.

Machine is new HP Spectre X360 with PCIE NVME SSD drive.  I tested with factory installed setup, and also after wiping all partitions and reformatting under Ubuntu.  I tested with 4.0.1 and 4.0.2-rc1.  Same error in all cases.

**Expected behavior**

Expect install to succeed

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

"none"

I saw another error where user worked around by wiping partitions and using /dev/sda.

**Comment by marmarek** [comment]
That "more info" should also include file and line number, what do you have there?

**Comment by iprid23** [comment]
Are you sure that your NVME SSD is supported by Kernel 4.14/4.19?(though it should probably be).

**Comment by allenjs** [comment]
I got it working by booting into TailsOS in admin mode and deleting all partitions on the SSD, with no format.  The default Ubuntu install apparently created 2 partitions on the SSD (one fairly small, and the other taking up the remaining space).  The Qubes setup seems to bomb when the drive has more than one partition.

This may be a duplicate of #3789 (https://github.com/QubesOS/qubes-issues/issues/3789).  The person who posted that also got it working by deleting all partitions.
