### ISSUE TITLE
Gnome-Terminal in DVM is closed immediatly

### ISSUE THREAD

**Issue by akkuladezeit** [QubesOS/qubes-issues#5259]
Qubes Version 
R4.0.1

Description
Try to Open an Gnome-Terminal in DVM (fedora29 Template). The DVM Starts and immediatly get cloased.

Expacted behavor 
The DVM Keep Running with Gnome-Terminal Opened

Note
The xterm stays Open

Reproduce 
Qvm-run —dispvm:Name gnome-terminal

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by unman** [comment]
Longstanding issue: it's duplicate of #2581 and covers also #4606, #3878

**Comment by iprid23** [comment]
As far as I understand, there is a launcher process which terminates after the terminal is launched, hence the DispVM thinks it's main process was terminated so it's closed.

**Comment by andrewdavidwong** [comment]
Duplicate of #2581

**Comment by andrewdavidwong** [comment]
This appears to be a [duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.
