### ISSUE TITLE
SanDisk 0781:558c eMMC not detected

### ISSUE THREAD

**Issue by b-** [QubesOS/qubes-issues#5262]
**Qubes OS version**
4.0.2-rc1 (installer)

**Affected component(s) or functionality**
SanDisk `0781:558c` eMMC

**Brief summary**
Setup does not detect and will not install to the local eMMC, and presumably if I were to `dd` an installation to this disk it would not be able to boot from it as I'm guessing this is a matter of a kernel module, or something.

**To Reproduce**
_Steps to reproduce the behavior:_
1. Go to Micro Center
2. Bring a _WinBook_ TW110 2-in-1 to the checkout counter
3. Pay about $150
4. Attempt installation of Qubes OS on it

**Expected behavior**
The Qubes OS installer should detect the eMMC.

**Actual behavior**
The Qubes OS installer does _not_ detect the eMMC, and I cannot proceed using the internal storage as installation medium.

**Additional context**
Ubuntu 19.04's installer _does_ see the eMMC. I did not want to overwrite the eMMC with Ubuntu, and I don't know how to check what modules, etc. are allowing this device to work, but it shows up as `/dev/mmcblk0` so I'm presuming it's a relatively standard MMC controller. The MicroSD slot on this device shows up as `/dev/mmcblk1` which adds to my theory.

**Solutions you've tried**
None. I imagine it is as simple as using a kernel with the required module, but I do not know what module nor how to install Qubes with a custom kernel, let alone if this is even considered a Bad Idea for security. However, I'm open to workarounds.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
N/A

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
none

**Comment by iprid23** [comment]
You need a newer kernel probably. Your main choice would be to either build Qubes with newer kernel or wait for a new release with a newer kernel.
One idea would be to get the kernel from the Qubes package repo and modify the ISO, however you also need to build initrd image for it, so you can't just replace kernel.

**Comment by b-** [comment]
Okay, that's a good idea. Does Qubes have any specific kernel patches that I'd want to apply, or should I simply download the kernel source, configure it for my hardware and preferences, and build it (and the initrd)?

**Comment by iprid23** [comment]
Well, the kernel repo is here:
https://github.com/QubesOS/qubes-linux-kernel
It has custom patches.
As far as I am aware you should be able to build it as-is, though the Qubes builder also uses a patched version of GCC 6.
