### ISSUE TITLE
Path MTU discovery does not work when using WireGuard VPN

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#5264]
### Qubes OS version:

`Qubes release 4.0 (R4.0)`

### Affected component(s) or functionality:

Networking

---

### Steps to reproduce the behavior:

Use a WireGuard VPN with 1360 MTU.

### Expected or desired behavior:

MTU discovery works out of the box, so TCP connections have no problems.

### Actual behavior:

MTU discovery fails, causing TCP connections to fail.

### General notes:

Setting MTU manually in the VM connected to the VPN VM fixes the problem.

---

**Comment by ptitdoc** [comment]
Same problem here. This causes some websites to not work (eg: https://crt.sh in my case):
curl https://crt.sh works from my wireguard proxy vm
curl https://crt.sh does not work from a vm connected to the wireguard proxy vm

**Comment by ptitdoc** [comment]
On my wireguard server:
# tcpdump -i ens32 icmp -n
14:03:38.899277 IP 10.X.X.11 > 91.199.212.73: ICMP 10.X.X.11 unreachable - need to frag (mtu 1420), length 556
On my wireguard VPN proxy vm:
# ifconfig wg0
wg0: flags=209<UP,POINTOPOINT,RUNNING,NOARP>  mtu 1420
# tcpdump -i wg0 -n icmp
NOTHING..

**Comment by ptitdoc** [comment]
One option is described there:
https://keremerkan.net/posts/wireguard-mtu-fixes/
https://www.inetdoc.net/guides/iptables-tutorial/tcpmsstarget.html

I added this rule in 3rd position of POSTROUNTING in my proxy VM:
`sudo iptables -t nat -I POSTROUTING 3 -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu`

So that I ends up with the following rules in the POSTROUTING chain:
```
Chain POSTROUTING (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 ACCEPT     all  --  any    vif+    anywhere             anywhere            
    1    52 ACCEPT     all  --  any    lo      anywhere             anywhere            
    1    52 TCPMSS     tcp  --  any    any     anywhere             anywhere             tcp flags:SYN,RST/SYN TCPMSS clamp to PMTU
 322K   17M MASQUERADE  all  --  any    any     anywhere             anywhere            
```
Now it works. However I'm not sure this would be the ideal solution:
- this only seems to solve TCP fragmentation issues, what about potential UDP issues ?
- should MTU configuration be automatic, eg using ICMP unreachable packets ?

**Comment by ptitdoc** [comment]
The command `tracepath` also seems to be a great too to troubleshoot MTU issues. It shows where there are MTU restrictions.

**Comment by ptitdoc** [comment]
Fun fact: just running `tracepath` on the final vm (the one connected to the wireguard proxy vm) is apparently sufficient to learn the new MTU:
```
[user@myappvm ~]$ curl https://crt.sh
NO REPLY 

[user@myappvm ~]$ tracepath -n crt.sh
 1?: [LOCALHOST]                      pmtu 1500
 1:  10.137.0.11                                           0.109ms     <<<< the wireguard proxy VM
 1:  10.137.0.11                                           0.079ms 
 2:  10.137.0.11                                           0.101ms pmtu 1420
 2:  172.X.X.1                                          57.536ms  <<< wireguard server side IP
 3:  10.X.X.2                                            66.825ms   <<< wireguard server WAN IP
[...]
10:  85.91.224.14                                         73.517ms 
11:  85.91.224.106                                        76.134ms asymm 14 
12:  91.212.12.19                                         78.794ms asymm 15 
13:  no reply
14:  no reply
15:  no reply

[user@myappvm ~]$ curl https://crt.sh
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
```

**Comment by ptitdoc** [comment]
Another good source of information : https://erg.abdn.ac.uk/users/gorry/course/inet-pages/pmtud.html

**Comment by ptitdoc** [comment]
My final choice would be to go for `clamp-mss-to-pmtu` just before MASQUERADING in proxyvms and netvms.
http://www.tegola.org.uk/howto/pmtud.html

**Comment by DemiMarie** [comment]
I *believe* I figured out the problem: the remote WireGuard server successfully encapsulates the oversize packet, but the oversize packet doesn’t make it to the VM with the VPN.  The ICMP error packet produced is then returned to the WireGuard server, which drops it.  The WireGuard server can’t really do anything better, as the packet is unauthenticated and allowing unauthenticated packet injection would be a security risk.

UDP-based protocols generally don’t have this problem.  To avoid being used in amplification attacks, a server must authenticate its client before sending more UDP data than it received.  Therefore, the packet would be rejected at by the VPN endpoint as being too large, and the client will usually retry over TCP instead.  QUIC is an exception, but I believe QUIC requires packetization-level MTU discovery, which doesn’t rely on ICMP at all, precisely so it does not need to deal with problems like this.  Since QUIC is encrypted and authenticated, there is no way that a network intermediary can change requested MSS sizes, so QUIC’s solution is to try larger and larger packets until one eventually gets dropped.

**Comment by ptitdoc** [comment]
This issue is still active. My current solution is to add to `/rw/config/rc.local` of my wireguard VPN VM:
`iptables -t nat -I POSTROUTING 3 -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu`

**Comment by DemiMarie** [comment]
Closing as “not a bug”: this behavior is not a bug, merely an unfortunate consequence of how WireGuard and ICMP errors interact with each other.  The `--clamp-mss-to-pmtu` workaround is correct and reliable.

**Comment by joostbijl** [comment]
Thanks @DemiMarie  for the analysis. Windows clients suffer from the same issue, but there's no 'clamp-mss-to-pmtu' hack. Since my wireguard client was unworkable due to retransmits, i resorted to disabling path mtu discovery alltogether. This seems to resolve the issue 🤞.

For completeness sake, these are the steps from Microsoft to disable pmtu discovery:

1. Click Start, click Run, type regedit, and then click OK.
2. Locate the following key in the registry: HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters
3. On the Edit menu, point to New, and then click DWORD Value.
4. Type EnablePMTUDiscovery, and then press ENTER.
5. On the Edit menu, click Modify.
6. In the Value data box, type 0, and then click OK.
7. Quit Registry Editor, and then restart the computer.

**Comment by DemiMarie** [comment]
@joostbijl You’re welcome.  FYI, if you are using Qubes OS, you can set up WireGuard so that it is not in the Windows qube itself, but rather in the qube that provides networking to your Windows qube.  You can also set up firewall rules so that the qube with the WireGuard client (whichever it may be) can only connect to the WireGuard server.

I _believe_ there is a way to set the MTU on a Windows network interface.  That said, I recommend bringing this up on the WireGuard mailing list; I am no expert on WireGuard _or_ Windows networking.  Disabling path MTU discovery seems to be a hack that may cause problems down the line.
