### ISSUE TITLE
Qubes Repositories not available

### ISSUE THREAD

**Issue by unman** [QubesOS/qubes-issues#5265]
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
Infrastructure

**Brief summary**
Both yum.qubes-os.org and deb.qubes-os.org have been unavailable for some time.

**To Reproduce**
_Steps to reproduce the behavior:_
_1. apt update
_2. Wait

**Expected behavior**
updates

**Actual behavior**
Repository cannot be reached: Connection failed.

**Screenshots**
_If applicable, add screenshots to help explain your problem._

**Additional context**
Checked connection via clearnet - also not available.

**Solutions you've tried**
Waited and retried.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
_A list of links to the Qubes documentation (or other relevant software documentation) pages you have already consulted._

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
_A list of links to other bug reports, feature requests, or tasks in the qubes-issues tracker (or "none" if you didn't find any). Do not describe any other unreported bugs, features, or tasks here._

**Comment by marmarek** [comment]
There was scheduled downtime in the datacenter, supposedly ended at 15:00 UTC. There is an update that not everything is done yet, but our server should be online already. It responds to pings, but refuses connections on all the ports. I'll investigate.

**Comment by marmarek** [comment]
Seems to work now, not sure how stable yet.

**Comment by marmarek** [comment]
Should work now.
