### ISSUE TITLE
Debian templates cache downloaded packages

### ISSUE THREAD

**Issue by unman** [QubesOS/qubes-issues#5266]
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
Debian templates

**Brief summary**
Installed packages are cached in /var/cache/apt

**To Reproduce**
_Steps to reproduce the behavior:_
_1. Install packages or use qubes-updater
_2. `ls /var/cache/apt/archives`_

**Expected behavior**
Packages will not be retained in cache

**Actual behavior**
Packages are retained in cache.

**Screenshots**
_If applicable, add screenshots to help explain your problem._

**Additional context**
We clean cache after installation.

Although this is standard Debian behavour, in Qubes context, I'm not sure it makes sense to retain packages in cache for every template.
That said, `/var/cache/apt/archives` is important and shouldnt be removed

**Solutions you've tried**
`apt-get clean` is standard route.
Setting APT::Keep-Downloaded-Packages "0"

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
_A list of links to the Qubes documentation (or other relevant software documentation) pages you have already consulted._

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
_A list of links to other bug reports, feature requests, or tasks in the qubes-issues tracker (or "none" if you didn't find any). Do not describe any other unreported bugs, features, or tasks here._

**Comment by unman** [comment]
On Tue, Jun 08, 2021 at 01:52:15PM -0700, Andrew David Wong wrote:
> Since this has the 4.0 milestone, the fix is pending backport to 4.0, right?
> 

If it's not there, yes.

**Comment by andrewdavidwong** [comment]
> On Tue, Jun 08, 2021 at 01:52:15PM -0700, Andrew David Wong wrote:
> > Since this has the 4.0 milestone, the fix is pending backport to 4.0, right?
> > 
> 
> If it's not there, yes.
> 
> 

I didn't think it would already be there when there are no qubesbot comments on this issue stating so.
