### ISSUE TITLE
Clarify DisposableVM Template customization documentation

### ISSUE THREAD

**Issue by m4teh** [QubesOS/qubes-issues#5268]
### Qubes OS version:
**Qubes release 4.0 (R4.0)**

### Affected component(s) or functionality:
Any changes to the fedora-30-dvm template (as per https://www.qubes-os.org/doc/disposablevm-customization) are immediately cleaned when the dvm is shut down. Any new dispvms created always use the factory defaults.

---

### Steps to reproduce the behavior:

- Created new AppVM based on Fedora 30 called fedora-30-dvm
- Set: qvm-prefs fedora-30-dvm template_for_dispvms True
- Set: qvm-features fedora-30-dvm appmenus-dispvm 1
- Run: qvm-run -a fedora-30-dvm gnome-terminal
- Customize things.. install software
- sudo powroff (from inside disvm), or qvm-shutdown fedora-30-dvm (dom0)
- Open a new dispvm and test the result

### Expected or desired behavior:

- New dispvm created should have apps and changes installed from the changes to fedora-30-dvm

### Actual behavior:

- No changes are kept to dispvmxxxx

### General notes:
First time I've customized a dispvm - Is Qubes designed to smartly retain the changes in fedora-30-dvm's appvm using this method? It doesn't exactly surprise me that changes aren't kept (as fedora-30-dvm is also just an appvm, but according to the documentation, it should work?

---

### I have consulted the following relevant [documentation](https://www.qubes-os.org/doc/):

- https://www.qubes-os.org/doc/disposablevm-customization/

### I am aware of the following related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues:

- Can't find related bugs posted

**Comment by andrewdavidwong** [comment]
It sounds like you forgot to set your new DisposableVM Template as the default DisposableVM Template:

```
[user@dom0 ~]$ qubes-prefs default_dispvm fedora-30-dvm
```

**Comment by andrewdavidwong** [comment]
> First time I've customized a dispvm - Is Qubes designed to smartly retain the changes in fedora-30-dvm's appvm using this method? It doesn't exactly surprise me that changes aren't kept (as fedora-30-dvm is also just an appvm, but according to the documentation, it should work?

Changes to your settings will generally persist because they're stored in the home directory. Installed applications generally will not. Those should instead be installed in the TemplateVM on which the DisposableVM Template is based.

**Comment by m4teh** [comment]
I'm going to close this. I was trying to achieve something on the AppVM level rather than the TemplateVM level, where it should have been. The home folder settings are retained correctly by the way.
