### ISSUE TITLE
Choosing non-English language does not affect resulting Xfce interface language

### ISSUE THREAD

**Issue by alpha-and-omega** [QubesOS/qubes-issues#5271]
**Qubes OS version**
Qubes-R4.0.2-rc1

**Affected component(s) or functionality**
Xfce interface language always English.

**Brief summary**
Choosing non-English language (Russian and I bet any other non-English) does not affect resulting Xfce interface language, and there is no known (for me) way to add new locale to lightdm's list of locales.

**To Reproduce**
1) Choose Russian language (for installation and system) during installation
2) test language in xfce.

**Actual behavior**
Resulting locale in xfce and in lightdm: C.utf8.
Lightdm's list of locales is always the same and limited to a short list of en.* locales.

cat /etc/locale.conf is LANG=ru_RU.UTF-8

**Comment by marmarek** [comment]
How exactly have you chosen the language? Installation media contains only English, and the list there doesn't contain others.

After the installation you should be able to download langpacks, like this:
```
sudo qubes-dom0-update langpacks-ru
```

**Comment by alpha-and-omega** [comment]
Qubes-R4.0.2-rc1 - Second installation screen: "Language support" -> "Select additional language support to be installed" -> Russian (left panel) Русский (right)

Installed langpacks-ru and problem solved, thanks!

**Comment by donob4n** [comment]
I selected Spanish and, apart of missing es lang packages, I have my system locale set to C.utf8 .

**Comment by andrewdavidwong** [comment]
> How exactly have you chosen the language? Installation media contains only English, and the list there doesn't contain others.
> 
> After the installation you should be able to download langpacks, like this:
> 
> ```
> sudo qubes-dom0-update langpacks-ru
> ```

Is this intentional? I always see a long list of non-English language options in the Qubes installer, which would be misleading if selecting any of those options has no effect.
