### ISSUE TITLE
Qubes OS does not recover from X11 crash (shmoverride)

### ISSUE THREAD

**Issue by v6ak** [QubesOS/qubes-issues#5273]
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
GUI daemon, shmoverride

**Brief summary**
When X11 crashes (*not* when it is terminated correctly), user can log in again, but the VMs GUI does not work at all. While GUID is restarted, it imediatelly crashes.

**To Reproduce**
1. Make X11 crash. This can be a regular crash or even kill -9. (The `-9` is important. Without `-9`, X11 terminates correctly and this issue cannot be reproduced.)
2. Log in again.

**Expected behavior**
Qubes OS fully recovers and shows all the windows previously shown.

**Actual behavior**
All the windows just blink for a short time and GUI daemon crashes.

**Additional context**
Logs were posted to https://groups.google.com/forum/#!topic/qubes-users/UwjiRi3MS3c

**Solutions you've tried**

When I rename `/var/run/qubes/shm.id.0` and run `sudo systemctl restart lightdm`, the system partially recovers. The shm.id.0 fle is recreated with a different number and GUID works again. Newly started VMs seem to be 100% OK. Previously started VMs don't have sound output and some of them (looks like randomly chosen bunch of VMs) stop working until VM reboot – GUI is not shown and dom0 commands like `qvm-run -p vm-name ls` hang.

**Comment by DemiMarie** [comment]
Works in R4.1.
