### ISSUE TITLE
Qubes does not assign default devices (Acer Aspire 5 9720P) [4.0.1]

### ISSUE THREAD

**Issue by underlineGalaxy** [QubesOS/qubes-issues#5274]
### Qubes OS version: 
4.0.1

### Affected component(s) or functionality:
This error: https://i.imgur.com/lVzHTtH.jpg whenever I try to launch a VM

---

### Steps to reproduce the behavior:

Happens just after I try to launch a VM. I tried 2 reinstalls but nothing happened. I checked then the devices on sys-net: 
https://i.imgur.com/I1xobiy.jpg
From a reddit thread (https://www.reddit.com/r/Qubes/comments/cvdt7n/pci_device_on_a_laptop_not_doing_bus_reset/) it seems that each of those default Qubes (Sys-net, sys-firewall, personal) require some default things to be set as the device, like for instance how sys-net needs ethernet. Why doesn't it put some on each though?
Here's sys-net: https://i.imgur.com/I1xobiy.jpg

I tried putting the VGA controller which the system asked me to that gave me that error and instead it put my laptop on an infinite boot loop, along with giving some ghosting on my screen for some reason.

It seems like I have to manually assign each device to each vm? Can you guys guide me on how to do that?

### Expected or desired behavior:

Launching a VM normally, or not having to manually put each device on a VM after installation.

### Actual behavior:

Show these errors https://i.imgur.com/lVzHTtH.jpg

### General notes:

I'm still fairly new to linux and it's my first time trying to use QubesOS. I would appreciate any help in guiding someone new to this.
Yes, I did read the tutorials and hardware compatibility list, but nothing could help me (as there's no way to know if my laptop is compatible or not without installing the thing on it).

Honestly if I can't solve this I'm thinking of switching to the less secure Qubes 3.2.

---

### I have consulted the following relevant [documentation](https://www.qubes-os.org/doc/):

https://www.qubes-os.org/doc/system-requirements/
https://www.qubes-os.org/hcl/
https://www.qubes-os.org/getting-started/
https://www.qubes-os.org/doc/installation-guide/

### I am aware of the following related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues:

I did not find any related bug reports on my search, altough I didn't really look hard at it.

**Comment by donob4n** [comment]
> It seems like I have to manually assign each device to each vm? Can you guys guide me on how to do that?

Only sys-net (optionally sys-usb) should have pci devices attached in standard configuration.

You could try to configure strict reset for '01.00.1 Ethernet controller....' You can do it from Qubes Manager, 'https://i.imgur.com/I1xobiy.jpg' click on 'Configure strict reset for PCI devices' and select it. 

If this fails and you are going to use mostly wireless connection, you could just remove the Ethernet Controller from sys-net and try to start it.

Your problem seems more likely a hardware "incompatibility" than a Qubes issue, try mailing 'qubes-users@googlegroups.com' if this does not help.

**Comment by underlineGalaxy** [comment]
> 
> 
> > It seems like I have to manually assign each device to each vm? Can you guys guide me on how to do that?
> 
> Only sys-net (optionally sys-usb) should have pci devices attached in standard configuration.
> 
> You could try to configure strict reset for '01.00.1 Ethernet controller....' You can do it from Qubes Manager, 'https://i.imgur.com/I1xobiy.jpg' click on 'Configure strict reset for PCI devices' and select it.
> 
> If this fails and you are going to use mostly wireless connection, you could just remove the Ethernet Controller from sys-net and try to start it.
> 
> Your problem seems more likely a hardware "incompatibility" than a Qubes issue, try mailing '[qubes-users@googlegroups.com](mailto:qubes-users@googlegroups.com)' if this does not help.

Wow, it works, thank you so much kind stranger!
Altough I think the devs should make if so I get this error make this option manually activated? Or at least show these steps on the error. A google search and the documentation shows nothing about this which made me make a issue that had such an easy fix.

**Comment by donob4n** [comment]
> Glad to hear your problem was resolved!

Yes :)
