### ISSUE TITLE
Fixes committed to qubes-app-linux-snapd-helper months ago not yet released

### ISSUE THREAD

**Issue by daniel-ayers** [QubesOS/qubes-issues#5275]
**Qubes OS version**
_The version of Qubes OS you're using (e.g., `R4.0`), available via the command `cat /etc/qubes-release` in a dom0 terminal._

R4.0

**Affected component(s) or functionality**
_The component or functionality of Qubes OS that is not working as expected._

qubes-app-linux-snapd-helper

**Brief summary**
_A clear and concise summary of the bug._

An important fix [committed](https://github.com/QubesOS/qubes-app-linux-snapd-helper/commit/cf0b6fc9586ab14362db5ae3de5369af9f5afb3f#diff-f15f1cca5b1b8cc2fc84874de2cdacc3) in May has not yet appeared in released packages (fc30 at least).

I diagnosed and fixed the issue independently today and only discovered when I looked at the repo (to submit my own PR for the fix) that the problem had been already fixed in May, but the fix has not yet found its way into released packages.

**Comment by marmarek** [comment]
Update uploaded to current-testing: https://github.com/QubesOS/updates-status/issues/1274
