### ISSUE TITLE
"Cannot retrieve repository metadata (repomd.xml)" when trying to update dom0 or templateVM through terminal

### ISSUE THREAD

**Issue by RenatoLopes771** [QubesOS/qubes-issues#5276]
**Qubes OS version**

4.0

**Affected component(s) or functionality**

Updating through terminal

**Brief summary**

Can't update dom0 or template VM's through terminal.

**To Reproduce**

typing "sudo qubes-dom0-update -v" or trying to update another VM gives the error

**Expected behavior**

Updating

**Actual behavior**

gives the following output:

```
Using sys-whonix as UpdateVM to download updates for Dom0; this may take some time...
Error: Cannot retrieve repository metadata (repomd.xml) for repository: fedora. Please verify its path and try again
Config time: 0.033
repo time: 0.000
Setting up Package Sacks
Cannot retrieve repository metadata (repomd.xml) for repository: fedora. Please verify its path and try again
```

**Screenshots**

**Additional context**

Fresh install, literally didn't download anything yet besides updating the "personal" qube to fedora 30, and then later deleting it as well as the "work" qube.

**Solutions you've tried**

Couldn't find any with the exception of the one at the bottom of this issue

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

None found

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

https://github.com/QubesOS/qubes-issues/issues/3463
https://github.com/QubesOS/qubes-issues/issues/287 (has a fix that I refrained from using because it is 2 years old, plus it uses the test release)
https://github.com/QubesOS/qubes-issues/issues/1685

**Comment by andrewdavidwong** [comment]
> yes that works

In that case, it sounds like this is specific to updating via `sys-whonix`.

[However, it also looks like this is a very common error independent of Qubes and Whonix.](https://www.google.com/search?q=%22Cannot+retrieve+repository+metadata+%28repomd.xml%29+for+repository%22)

> Altough less safe I presume

Please see the comments on #2604 for more information about this point.

**Comment by e6lk7dqzm83p** [comment]
I had this issue and had to move to sys-firewall to do an update (it didn't work over my VPN qube).

**Comment by DemiMarie** [comment]
I think so
