### ISSUE TITLE
Add passing SLIC ACPI table to HVM guest to allow activate OEM Windows

### ISSUE THREAD

**Issue by jevank** [QubesOS/qubes-issues#5279]
**Allow use SLIC ACPI table to activate OEM installed Windows**
_In order to use Windows OEM install media, the SLIC table must be passed to a
guest. In addition all the OEM table IDs must match the SLIC or Windows will
think it is invalid and the install ends up unactivated._

**Describe the solution you'd like**
_Libxl support passing additional ACPI tables to HVM guest (acpi_firmware param), but it need also updating OEM ID it tables. It could possible with OpenXT patch._

_Second problem is libvirl libxl driver have no support to use acpi_firmware setting while have supporting SLIC table defining in domain common schema._

**Where is the value to a user, and who might that user be?**
_Any user with OEM Windows 7 could activate it_

**Additional context**
_All PR are ready to use_

**Comment by jevank** [comment]
short HowTo:
1. Create custom template in /etc/qubes/templates/libvirt/xen/by-name/_vmname_.xml
2. In `<os>` section add
`<acpi>`
`<table type='slic'>/sys/firmware/acpi/tables/SLIC</table>`
`</acpi>`

**Comment by marmarek** [comment]
Instead of copying the whole template, it should be enough to extend `os` block, like this:
```
{% extends "libvirt/xen.xml" %}
{% block os %}
{% super() %}
<acpi>
<table type='slic'>/sys/firmware/acpi/tables/SLIC</table>
</acpi>
{% endblock %}
```

As for the patches, have you considered sending them upstream (libvirt and xen respectively)?

**Comment by jevank** [comment]
ok, extending looks appropriate.

I think to offer libvirt patch to upstream, it is simple and useful. As for xen patch first I got in from OpenXT, second right now difficult to test upstream build for me. Perhaps patching to R4.1 packages will help with it.

**Comment by unman** [comment]
@jevank I'm intrigued, because I have activated Win7 on various machines without this patch without any problem.
Which manufacturer and Windows version gave you trouble?

Even if you couldn't register automatically, were you not able to activate by phone? I've had to do that in the past even with machines straight from the manufacturer.

**Comment by marmarek** [comment]
I don't think it's about inability to activate manually. It's rather about activating automatically with built-in OEM license (instead of of manually typing the key from the sticker).

**Comment by jevank** [comment]
@unman  OEM SLP type of license

> Computers that come pre-installed with Windows from large manufacturers usually come with two Product Keys.
> 
> OEM SLP: This is the key that came in Windows (from the factory). It works by connecting to a BIOS flag (the SLIC table) found only on  computers from that Manufacturer. It also checks for the existence of proper matching licenses in the OS itself. Once it sees both, it self-activates every time the machine is rebooted.
> 
> COA SLP: This is the key seen on the sticker located on the side, bottom or in the battery compartment of your machine. This key is for use if the OEM SLP self-activation stops working for whatever reason.
> 
>  You need to change the Product Key to the one on the COA sticker on the machine's case (or inside the battery compartment),  using the Change Product Key link at the bottom of the System properties page.
> 
> You may need to activate by phone. 

https://social.microsoft.com/Forums/en-US/6fb311e4-8498-4fdb-82ea-c29a3001dfca/windows-7-hp-oem-activation-from-clean-install

**Comment by jevank** [comment]
This type of activation could be offine completely

**Comment by marmarek** [comment]
> This type of activation could be offine completely

Oh, that's really cool!

**Comment by unman** [comment]
I know about the licenses. I'm pointing out that in my experience, offline activation is pretty hit and miss even on OEM hardware, and that manual is always a fallback.

**Comment by jevank** [comment]
This method requires saving xrm-ms certificate from OEM recovery media/partition and using it after fresh installation. Often it is necessary with hard disk to SSD replacement on Laptop. Without this certificate OS will not be activated.

**Comment by jevank** [comment]
All patches are in stable repository now, so close the issue. Thanks.

**Comment by brendanhoar** [comment]
In xen stable or in qubes stable? If in qubes stable, can this be enabled/disabled per VM?

**Comment by jevank** [comment]
> Can this be enabled/disabled per VM in Qubes?

yes, look at [this way](https://github.com/QubesOS/qubes-issues/issues/5279#issuecomment-525938992)  and [simple way](https://github.com/QubesOS/qubes-issues/issues/5279#issuecomment-525947408) comments in thread. And [here](https://dev.qubes-os.org/projects/core-admin/en/latest/libvirt.html) is doc about customizing libvirt VM config
