### ISSUE TITLE
Qubes U2F Proxy

### ISSUE THREAD

**Issue by n0sign4l** [QubesOS/qubes-issues#5281]
Hi, I wanted to install the Qubes U2F proxy (https://www.qubes-os.org/doc/u2f-proxy/) and there is written `These instructions assume that there is a sys-usb qube that holds the USB stack` .
It seems that my qubes R4.0 doesn't have it cause I have the grub-loader on a USB stick.. So my question is, can I install and use the Qubes U2F proxy? Should I follow the docs instructions (https://www.qubes-os.org/doc/u2f-proxy/) ? I think that I cannot install the sys-usb qube as it would make impossible for me to login again.

Lemme know

**Comment by andrewdavidwong** [comment]
Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this does not appear to be suitable for `qubes-issues`. We ask that you please send this to the `qubes-users` [mailing list](https://www.qubes-os.org/support/) instead. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a brief comment explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.
