### ISSUE TITLE
Debian 10 minimal template, incompatible networking package version

### ISSUE THREAD

**Issue by neowutran** [QubesOS/qubes-issues#5283]
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
Package management for Debian 10 minimal template

**Brief summary**
On the debian 10 minimal template provided by ITL ( ``sudo qubes-dom0-update --enablerepo=qubes-templates-itl-testing qubes-debian-10-template``), it is not possible to install qubes-core-agent-networking. 
``sudo apt-get install qubes-core-agent-networking`` 
=>
``qubes-core-agent-networking: Depends: qubes-core-agent (= 4.0.46.....) but 4.0.47..... is to be installed``

**To Reproduce**
See ``Brief summary``. Install template, install passwordless-root, try to install qubes-core-agent-networking

**Expected behavior**
The package is installed correctly

**Actual behavior**
The package is not installed due to incompatible dependencies

**Solutions you've tried**
In ``/etc/apt/sources.list.d/qubes-r4.list``, activate the candicates repository & testing repository (didn't checked it only one of them was necessary, I just activated both). After that it work.

The main repository should contains compatibles versions of packages (all 4.0.46 or all 4.0.47, or ... ). Or activate by default the other repository

**Comment by unman** [comment]
This isnt a bug - the template is available from the testing repo, and is built with packages from testing. That means that you  have to enable the "testing" repo to be able to install  more packages.
It is documented [here](https://www.qubes-os.org/doc/templates/debian/):
> to install additional Qubes packages you will have to enable the qubes-testing repository.

When the packages move to stable then the template can move to stable. We don't want to enable testing repositories by default.

@marmarek - is there a way to build a new template (in testing) using stable packages? I've probably missed this.

**Comment by andrewdavidwong** [comment]
Closing as "not an issue." If you believe this is a mistake, please leave a comment, and we'll be happy to take another look. Thank you.

**Comment by marmarek** [comment]
> @marmarek - is there a way to build a new template (in testing) using stable packages? I've probably missed this.

It's controlled by the template build config, here: https://github.com/QubesOS/qubes-template-configs/blob/master/R4.0/templates-itl/debian.conf#L23
So, the only way is to modify this config before the template build.
