### ISSUE TITLE
Unable to mount external hard drive - unknown ntfs

### ISSUE THREAD

**Issue by TNTBOMBOM** [QubesOS/qubes-issues#5285]
**Qubes OS version**

4.0.1

**Affected component(s) or functionality**

qubes-input-proxy-sender ? (not sure)

**Brief summary**

Mounting harddrive inside VM

**To Reproduce**

_1. Attach your harddrive
_2. Right Click on Qubes Devices
_3. Attach your harddrive to an AppVM
_4. Double click on the attached harddrive wont do anything, right click then press mounting you gonna then see the error.

**Expected behavior**

External HardDrive/Flash.. should be accessed normally

**Actual behavior**

Not working

**Screenshots**

![mounterror](https://user-images.githubusercontent.com/11895339/64120047-c113ec00-cd8a-11e9-8ab7-4ce9d0170c44.png)

**Comment by brendanhoar** [comment]
Make sure that the template used for the vm has the ntfs-3g package installed 
(install it if not), shut down the template and then (re-)start the AppVM.

**Comment by andrewdavidwong** [comment]
Are you using a Minimal TemplateVM? Does it work as expected on a standard TemplateVM?

**Comment by TNTBOMBOM** [comment]
> Make sure that the template used for the vm has the ntfs-3g package installed
(install it if not), shut down the template and then (re-)start the AppVM.

It worked, Thanks alot!

> Are you using a Minimal TemplateVM? Does it work as expected on a standard TemplateVM?

Debian,Fedora minimal , Whonix-WS Templates they dont have this package. (reminds me of zenity missing package issue)

**Comment by andrewdavidwong** [comment]
> > Make sure that the template used for the vm has the ntfs-3g package installed
> > (install it if not), shut down the template and then (re-)start the AppVM.
> 
> It worked, Thanks alot!
> 
> > Are you using a Minimal TemplateVM? Does it work as expected on a standard TemplateVM?
> 
> Debian,Fedora minimal , Whonix-WS Templates they dont have this package. (reminds me of zenity missing package issue)

Glad it's working for you. Closing as `not an issue` for the reasons documented here:

https://www.qubes-os.org/doc/templates/minimal/#important
