### ISSUE TITLE
New AppVMs aren't inheriting template's private volume

### ISSUE THREAD

**Issue by jpouellet** [QubesOS/qubes-issues#5286]
**Qubes OS version**
R4.0.2-rc1 + current updates

**Affected component(s) or functionality**
core-admin?

**Brief summary**
New AppVMs aren't inheriting template's private volume

**To Reproduce**
```
[user@dom0 ~]$ qvm-kill f30m-test-{app,tpl} >/dev/null 2>&1
[user@dom0 ~]$ qvm-remove -f f30m-test-{app,tpl} >/dev/null 2>&1
[user@dom0 ~]$ qvm-clone fedora-30-minimal f30m-test-tpl \
&& qvm-run f30m-test-tpl 'echo expected > foo' \
&& qvm-shutdown --wait f30m-test-tpl \
&& qvm-create -l red -t f30m-test-tpl f30m-test-app \
&& sleep 3 \
&& qvm-run -p f30m-test-app 'ls; echo; cat foo'
```

**Expected behavior**
output:
```
f30m-test-tpl: Cloning private volume
f30m-test-tpl: Cloning root volume
Running 'echo expected > foo' on f30m-test-tpl
foo

expected
```

**Actual behavior**
output:
```
f30m-test-tpl: Cloning private volume
f30m-test-tpl: Cloning root volume
Running 'echo expected > foo' on f30m-test-tpl

cat: foo: No such file or directory
```

**Additional context**
Same happens with DispVMs.

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

not sure if related, but I also sometimes see (intermittently, somewhat rarely):
```
permission denied for call b'admin.vm.Create.AppVM'+b'f30m-chrome' (b'dom0' → b'dom0') with payload of 20 bytes
```
in qubesd logs when using `qvm-create` (which then fails with "empty response from qubesd" on core-admin-client side), but so far never while using `qubes-vm-create`, and I haven't tracked down yet either.

**Comment by jpouellet** [comment]
These VMs are on an LVM thin pool as set up by the qubes installer.

I should probably trace lvm operations (& completion) while this is happening.

**Comment by andrewdavidwong** [comment]
That is not how TemplateVM inheritance works anymore:

https://www.qubes-os.org/doc/templates/#inheritance-and-persistence

**Comment by jpouellet** [comment]
Oh. Interesting. Do you happen to know when that changed or could point me to discussion about it? I'm curious about the rationale.

So now: What is the recommended way to have browser extensions in DispVMs? Should I put them in /etc/skel? Do I need to resort to more bind-mount madness to propagate updates?

**Comment by andrewdavidwong** [comment]
> Oh. Interesting. Do you happen to know when that changed or could point me to discussion about it? I'm curious about the rationale.
> 

The behavior changed in Qubes 4.0. See the discussion on https://github.com/QubesOS/qubes-issues/issues/1335 for details.

> So now: What is the recommended way to have browser extensions in DispVMs? Should I put them in /etc/skel? Do I need to resort to more bind-mount madness to propagate updates?

The recommended way is to use DisposableVM Templates:

https://www.qubes-os.org/doc/disposablevm-customization/#customization-of-disposablevm

**Comment by jpouellet** [comment]
Ah, derp. Of course.

What I was actually trying to do was create an additional dvm template that was derived from an existing one. Not sure what I was thinking.

Thanks!
