### ISSUE TITLE
qvm-remove: remove all the remains of the VM appmenus

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#529]
**Reported by joanna on 16 Apr 2012 14:16 UTC**
Specifically, I noticed that whenever a new AppVM is created a file in the

```
~/.config/menus/applications-merged/
```

is created, and named:

```
user-{VMNAME}-vm.menu
```

This file is not removed when we call qvm-remove. As a result, when a user opens Menu Editor in KDE, all the once-removed VMs are displayed there, confusing the user to no end...

Migrated-From: https://wiki.qubes-os.org/ticket/529

**Comment by andrewdavidwong** [comment]
Reopening due to apparent regression reported in #6180.

**Comment by mf5y** [comment]
I have also experienced this bug. If I were to create a VM with the name of a previously created now-deleted VM, this could cause issues. If the `.menu` file is not overwritten on creation of the VM, previously selected applications may appear there. This is not that far out of an idea, ex. if a user were to constantly be creating new StandaoneVMs for testing in different fresh OSs, all with the same name (maybe `delete` or `toss`). A residual app menu isn't the end of the world, but what else is left over behind the scenes?
