### ISSUE TITLE
Qubes daemon often doesn't start on boot

### ISSUE THREAD

**Issue by x4lldux** [QubesOS/qubes-issues#5295]
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
Qubes daemon, /usr/bin/qubesd

**Brief summary**
Qubes deamon often doesn't start on boot, systemd informs about start operation timeout. After X is started and loging in no VM can be started and `qvm-*` commands complaint about no socket to qubesd. Strating qubesd from a command line also doesn't solve the issue. Running it with both debug and verbose options does little to explain the issue.  
I need to reboot my machine several times in order for it to finally start working. After few tries it finally booted up properly. In the mean time, I didn't do any changes to software or hardware.

**To Reproduce**
1. Boot the machine,
2. Wait for qubesd to fail (not always happens).

**Expected behavior no 1**
For Qubes OS to always boot properly.

**Expected behavior no 2**
For `qubesd` to give meaningful information about why it cannot start, what it's doing and other helpful information that can be used to find out why it's not working properly.

**Actual behavior**
Qubesd doesn't start during the boot and trying to start later from command line also doesn't help (it just running in foreground but still no socket is created).

**Additional context**
Running it from command line:
```
$ /usr/bin/qubesd --debug -vvvvvv
2019-09-05 09:14:28,398 [MainProcess app.__init__:789] app: init() -> 0x728e658b6710
2019-09-05 09:14:28,398 [MainProcess app.__init__:790] app: stack:
2019-09-05 09:14:28,399 [MainProcess app.__init__:792] app: <FrameSummary file /usr/bin/qubesd, line 5 in <module>>
2019-09-05 09:14:28,399 [MainProcess app.__init__:792] app: <FrameSummary file /usr/lib/python3.5/site-packages/qubes/tools/qubesd.py, line 33 in main>
2019-09-05 09:14:28,400 [MainProcess app.__init__:792] app: <FrameSummary file /usr/lib/python3.5/site-packages/qubes/tools/__init__.py, line 362 in parse_args>
2019-09-05 09:14:28,400 [MainProcess app.__init__:792] app: <FrameSummary file /usr/lib/python3.5/site-packages/qubes/app.py, line 791 in __init__>
2019-09-05 09:14:28,642 [MainProcess libvirtaio._add_handle:354] virEventAsyncIOImpl: add_handle(fd=18, event=1, cb=..., opaque=...) = 0
2019-09-05 09:14:28,642 [MainProcess libvirtaio._update_handle:369] virEventAsyncIOImpl: update_handle(watch=0, event=0)
```
It doesn't crash or exit it's just keeps running doing noting. After few minutes I gave up and tried to reboot again.

qubes.log:
```
2019-09-05 09:14:28,398 [MainProcess app.__init__:789] app: init() -> 0x728e658b6710
2019-09-05 09:14:28,398 [MainProcess app.__init__:790] app: stack:
2019-09-05 09:14:28,399 [MainProcess app.__init__:792] app: <FrameSummary file /usr/bin/qubesd, line 5 in <module>>
2019-09-05 09:14:28,399 [MainProcess app.__init__:792] app: <FrameSummary file /usr/lib/python3.5/site-packages/qubes/tools/qubesd.py, line 33 in main>
2019-09-05 09:14:28,400 [MainProcess app.__init__:792] app: <FrameSummary file /usr/lib/python3.5/site-packages/qubes/tools/__init__.py, line 362 in parse_args>
2019-09-05 09:14:28,400 [MainProcess app.__init__:792] app: <FrameSummary file /usr/lib/python3.5/site-packages/qubes/app.py, line 791 in __init__>
2019-09-05 09:14:28,642 [MainProcess libvirtaio._add_handle:354] virEventAsyncIOImpl: add_handle(fd=18, event=1, cb=..., opaque=...) = 0
2019-09-05 09:14:28,642 [MainProcess libvirtaio._update_handle:369] virEventAsyncIOImpl: update_handle(watch=0, event=0)
```

running `qvm-ls`:
```
please wait... ..Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/qubesadmin/app.py", line 544, in qubesd_call
    client_socket.connect(qubesadmin.config.QUBESD_SOCKET)
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/qvm-ls", line 5, in <module>
    sys.exit(main())
  File "/usr/lib/python3.5/site-packages/qubesadmin/tools/qvm_ls.py", line 640, in main
    table.write_table(sys.stdout)
  File "/usr/lib/python3.5/site-packages/qubesadmin/tools/qvm_ls.py", line 420, in write_table
    for vm in sorted(self.domains):
  File "/usr/lib/python3.5/site-packages/qubesadmin/app.py", line 119, in __iter__
    self.refresh_cache()
  File "/usr/lib/python3.5/site-packages/qubesadmin/app.py", line 60, in refresh_cache
    'admin.vm.List'
  File "/usr/lib/python3.5/site-packages/qubesadmin/app.py", line 547, in qubesd_call
    'Failed to connect to qubesd service: %s', str(e))
qubesadmin.exc.QubesDaemonCommunicationError: Failed to connect to qubesd service: [Errno 2] No such file or directory
```

**Comment by marmarek** [comment]
Do you see anything more in `systemctl status qubesd` after failed start?

**Comment by x4lldux** [comment]
Nothing useful, notice to check journalctl for more information. And in journalctl all I see is:
```
-- Unit qubesd.service has begun starting up.
Sep 05 09:59:58 dom0 systemd[1]: qubesd.service: Start operation timed out. Terminating.
Sep 05 09:59:58 dom0 systemd[1]: Failed to start Qubes OS daemon.
-- Subject: Unit qubesd.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit qubesd.service has failed.
-- 
-- The result is failed.
Sep 05 09:59:58 dom0 systemd[1]: qubesd.service: Unit entered failed state.
Sep 05 09:59:58 dom0 systemd[1]: qubesd.service: Failed with result 'timeout'.
Sep 05 09:59:59 dom0 systemd[1]: qubesd.service: Service hold-off time over, scheduling restart.
Sep 05 09:59:59 dom0 systemd[1]: Stopped Qubes OS daemon.
-- Subject: Unit qubesd.service has finished shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit qubesd.service has finished shutting down.
Sep 05 09:59:59 dom0 systemd[1]: Starting Qubes OS daemon...
-- Subject: Unit qubesd.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit qubesd.service has begun starting up.
Sep 05 10:01:29 dom0 systemd[1]: qubesd.service: Start operation timed out. Terminating.
Sep 05 10:01:29 dom0 systemd[1]: Failed to start Qubes OS daemon.
-- Subject: Unit qubesd.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit qubesd.service has failed.
-- 
-- The result is failed.
Sep 05 10:01:29 dom0 systemd[1]: qubesd.service: Unit entered failed state.
Sep 05 10:01:29 dom0 systemd[1]: qubesd.service: Failed with result 'timeout'.
Sep 05 10:01:30 dom0 systemd[1]: qubesd.service: Service hold-off time over, scheduling restart.
Sep 05 10:01:30 dom0 systemd[1]: Stopped Qubes OS daemon.
-- Subject: Unit qubesd.service has finished shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit qubesd.service has finished shutting down.
```

**Comment by marmarek** [comment]
Strange, there are very few places that happens before reporting service start back to systemd. Generally, loading `qubes.xml` and related state, connecting to already running domains etc.
As for running domains - at this stage there is only dom0. Check if `qubes-db-dom0` and `xenstored` services are running.
As for `qubes.xml`, I don't see what could block its loading...

**Comment by x4lldux** [comment]
Yes, they begun starting the same second as qubesd, and both started successfully.
Though the xenstored the reported this in journal:
```
Sep 06 08:53:32 dom0 systemd[1]: Starting The Xen xenstore...
Sep 06 08:53:32 dom0 xenstored[5202]: TDB: tdb_open_ex: could not open file /var/lib/xenstored/tdb: No such file or directory
Sep 06 08:53:32 dom0 xenstored[5202]: Checking store ...
Sep 06 08:53:32 dom0 systemd[1]: Started The Xen xenstore.
Sep 06 08:53:32 dom0 launch-xenstore[5186]: Starting /usr/sbin/xenstored...
```
But when I checked after logging in that file does exists.

**Comment by marmarek** [comment]
> Sep 06 08:53:32 dom0 xenstored[5202]: TDB: tdb_open_ex: could not open file /var/lib/xenstored/tdb: No such file or directory

This message is harmless (I think the service never created this file).

What about the other one?

**Comment by x4lldux** [comment]
Also nothing:
```
Sep 06 08:53:32 dom0 systemd[1]: Starting Qubes DB agent...
Sep 06 08:53:32 dom0 systemd[1]: Started Qubes DB agent.
```

**Comment by awokd** [comment]
What Data and Meta % usages does `sudo lvs qubes_dom0/pool00` output? Also, make sure permissions on `/var/lib/qubes/qubes.xml` look like `-rw-rw----  1 root qubes`, but I don't see why they would change and allow it to start occasionally.

**Comment by x4lldux** [comment]
On a working boot up it's
```
Data%  Meta%
72.80  59.68
```
This shouldn't be much different on a not working boot up.

**Comment by Aporbel** [comment]
Have same problem, it problem started after modify attempt, then the file became 0 byte(null) and after restarted system - qubes did not start. How I can restore him? I tried found way for modify information in qube maneger. 

Namely, to find out where the alliases that are displayed in the qube manager. If I use VeraCrypt and encrypted my d isk then when I just start the system I see in qube manager that I have qube in volume. I don't want seen before I decrypt my volume. And I search way for this.

**Comment by marmarek** [comment]
There is a backup of qubes.xml created every boot in `/var/lib/qubes/backup`.

**Comment by Aporbel** [comment]
> There is a backup of qubes.xml created every boot in `/var/lib/qubes/backup`.
How I can hide information about VM in qube manager? I want to do I described above.  so that information in the VM in the system is taken from the encrypted volume

**Comment by awokd** [comment]
@x4lldux Try doing a diff of a working vs. not working boot log/`journalctl -b`. Your free space looks fine, but I'm wondering if your fs is getting mounted RO for some other reason. Might be hardware too, maybe try swapping out your hard drive.

**Comment by Aporbel** [comment]
> @x4lldux Try doing a diff of a working vs. not working boot log/`journalctl -b`. Your free space looks fine, but I'm wondering if your fs is getting mounted RO for some other reason. Might be hardware too, maybe try swapping out your hard drive.

Go to /var/lib/qubes and check your quebes.xml if file in empty, you need go to /var/liv/qubes/backup take last correct file and input him in /var/lib/qubes replace brokken qubes.xml

**Comment by x4lldux** [comment]
@Aporbel qubes.xml is not empty. Backup copy made today also looks .

@awokd nothing is mounted RO (only /sys/fs/cgroup, but it should). I have a RAID10 and it's not degraded and logs don't show any sign of HW problem.

**Comment by x4lldux** [comment]
@marmarek do you have some version of qubesd with enhanced debug logging? Cause right now we're just blind, and that would help to diagnose the problem if we could know why qubesd is not starting.
