### ISSUE TITLE
Error when running qvm-sync-appmenus on minimal VMs

### ISSUE THREAD

**Issue by SaswatPadhi** [QubesOS/qubes-issues#5296]
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
qubes-template-fedora-30-minimal

**Brief summary**
Attempting to refresh the list of applications for AppVMs based on fedora-30-minimal templates fails with a (very unhelpful) error message.

**To Reproduce**
_Steps to reproduce the behavior:_
1. Install `qubes-template-fedora-30-minimal`
2. Open the VM settings in Qubes Manager
3. In the "Applications Tab," click "Refresh Applications"

**Expected behavior**
The list of applications should be updated.

**Actual behavior**
An error message -- `Command '['qvm-sync-appmenus', '<VM_NAME_HERE>']' returned non-zero exit status 1`

**Solutions you've tried**
None ... Not sure what's failing. Are there any logs I can inspect? The error message should indicate that at the very least.

**Comment by SaswatPadhi** [comment]
I also see this issue on the Debian minimal template.
Any suggestions on what logs I should look at for more info?

Thanks.

**Comment by marmarek** [comment]
Try running that `qvm-sync-appmenus` command manually and see what it says.

**Comment by SaswatPadhi** [comment]
Sorry, I removed my last comment because noticed that the error was specific to my AppVM but not the debian minimal TemplateVM.

However, this error occurs on the `fedora-30-minimal` TemplateVM as the original bug report states. Here is the result of running `qvm-sync-appmenus`:

```
Traceback (most recent call last):
  File "/usr/bin/qvm-sync-appmenus", line 9, in <module>
    load_entry_point('qubesdesktop==4.0.18', 'console_scripts', 'qvm-sync-appmenus')()
  File "/usr/lib/python3.5/site-packages/qubesappmenus/receive.py", line 401, in main
    new_appmenus = retrieve_appmenus_templates(vm, use_stdin=use_stdin)
  File "/usr/lib/python3.5/site-packages/qubesappmenus/receive.py", line 377, in retrieve_appmenus_templates
    new_appmenus = get_appmenus(vm if not use_stdin else None)
  File "/usr/lib/python3.5/site-packages/qubesappmenus/receive.py", line 167, in get_appmenus
    "Error getting application list")
qubesadmin.exc.QubesException: Error getting application list
```

**Comment by SaswatPadhi** [comment]
I get the following error for my AppVM (my `sys-usb` VM based on `debian-10-minimal`):

```
$ qvm-sync-appmenus sys-usb
Traceback (most recent call last):
  File "/usr/bin/qvm-sync-appmenus", line 9, in <module>
    load_entry_point('qubesdesktop==4.0.18', 'console_scripts', 'qvm-sync-appmenus')()
  File "/usr/lib/python3.5/site-packages/qubesappmenus/receive.py", line 405, in main
    process_appmenus_templates(appmenusext, vm, new_appmenus)
  File "/usr/lib/python3.5/site-packages/qubesappmenus/receive.py", line 312, in process_appmenus_templates
    templates_dir)
  File "/usr/lib64/python3.5/shutil.py", line 241, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib64/python3.5/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/share/qubes-appmenus/qubes-start.desktop'
```

I suspect this is because of the VM being an HVM VM? Because I don't see the error for the TemplateVM, and this is a fresh AppVM based on it.

**Comment by SaswatPadhi** [comment]
I still get the same error on my "fedora-30-minimal" template:

```
$ qvm-sync-appmenus fedora-30-minimal
Traceback (most recent call last):
  File "/usr/bin/qvm-sync-appmenus", line 9, in <module>
    load_entry_point('qubesdesktop==4.0.20', 'console_scripts', 'qvm-sync-appmenus')()
  File "/usr/lib/python3.5/site-packages/qubesappmenus/receive.py", line 397, in main
    new_appmenus = retrieve_appmenus_templates(vm, use_stdin=use_stdin)
  File "/usr/lib/python3.5/site-packages/qubesappmenus/receive.py", line 373, in retrieve_appmenus_templates
    new_appmenus = get_appmenus(vm if not use_stdin else None)
  File "/usr/lib/python3.5/site-packages/qubesappmenus/receive.py", line 155, in get_appmenus
    "Error getting application list")
qubesadmin.exc.QubesException: Error getting application list
```

Please reopen this issue. Thanks.

**Comment by SaswatPadhi** [comment]
On running `/etc/qubes-rpc/qubes.GetAppmenus` in the VM, I see the list of lines from all the `.desktop` files, as expected.

However, running `qvm-run --pass-io --service -- fedora-30-minimal qubes.GetAppmenus` in dom0 only shows the first few lines and terminates with exit code 123.

Any ideas why this would be the case?

**Comment by SaswatPadhi** [comment]
Okay, that indeed was the issue! The "/usr/lib/python3.5/site-packages/qubesappmenus/receive.py" file was throwing an exception due to the same 123 exit code.

I also noticed that `/etc/qubes-rpc/qubes.GetAppmenus` emitted all lines from all `.desktop` files only when run as `root`. When run as `user`, it terminated with 123 exit code. So, there had to be some `.desktop` file that was readable by `root` but not by `user` and hence `GetAppmenus` kept dying.

Sure enough, the `/usr/local/share/applications/vim.desktop` file had 600 permission and was owned by `root`. This is definitely a bug in the vim package, but `qubes.GetAppmenus` should also be more resilient -- may be show a warning and ignore such unreadable `.desktop` files?

**Comment by andrewdavidwong** [comment]
@SaswatPadhi, would you still like for this to be reopened, or is the new problem separately reported in #217?
