### ISSUE TITLE
Make it easy to use the feature that automatically shuts down idle VMs

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#5298]
**The problem you're addressing (if any)**

Automatically shutting down idle VMs was implemented in #832, but most users don't know how to use it or even that it exists.

**Describe the solution you'd like**

Make it a user-friendly option in Qubes. For example, have a "Shut down after idle for: [text field] minutes" option in per-qube settings, as well as a global default "Shut down idle qubes after: [text field] minutes" option in the Global Qubes Settings. By default, these can be set to "never" if you're worried about user being surprised.

**Where is the value to a user, and who might that user be?**

All users who (would) want to use automatic shutdown-when-idle functionality but don't know how or don't know that it exists.

**Describe alternatives you've considered**

Documenting how to use it. This would be more difficult for users and less discoverable.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

https://github.com/QubesOS/qubes-app-shutdown-idle

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

https://github.com/QubesOS/qubes-issues/issues/832

**Comment by ninavizz** [comment]
This seems like a great memory saver, and shd def be considered in Qube manager explorations?

**Comment by marmarek** [comment]
First step is here: https://github.com/QubesOS/qubes-manager/pull/221
It makes it at least listed in the services tab.
The next step is adding it as a checkbox in basic or advanced tab.

**Comment by marmarta** [comment]
Do you think it's a bad idea to implement it with a fixed 15 minutes idleness period? That is, to have a checkbox saying "turn off after 15 minutes of idleness"? At the moment the script has hardcoded idleness period, implementing a more variable amount of time will require some more coding than just plopping down a checkbox - it will be done but I'm wondering about usefulness of this intermediate step.

**Comment by 100111001** [comment]
There are multiple factors on which the shutdown of the delay depends on:
- startup time of a vm (depends on my hardware)
- amount of VMs used concurrently vs. RAM of the box
- how often an App from a certain VM is needed 

As all these factors are individual, I'd vote for a variable idleness period.

To reduce dev effort (if needed), I'd suggest following simplifications:
1. introduce a slider with 0 mins <-------------|---------------------------> 24h
2. introduce 3 mutual exclusive options boxes () 15 min, () 30 min () 90 min
3. make this value variable to have the ability for advanced users to overwrite it per scripting in e.g. in /rw/config/rc.local

**Comment by marmarta** [comment]
Okay, so, because making the time period really configurable is a bit of a pain and I'd hate for the better to be the enemy of the good, I'm adding a "hardcoded 15 minutes" one to VM settings and if I have more time some day I'll make it more configurable. Alternatively, patches welcome :)

**Comment by andrewdavidwong** [comment]
@gonzalo-bulnes [asked](https://forum.qubes-os.org/t/poll-how-often-do-you-restart-your-qubes/4855/13?u=adw) to be pinged here.

**Comment by gonzalo-bulnes** [comment]
Thank you @andrewdavidwong! I'll take some time to get familiar with the package, and try the [approach outlined in the forum][forum], then propose a **Usage** section for the package repo's [README](https://github.com/QubesOS/qubes-app-shutdown-idle).

  [forum]: https://forum.qubes-os.org/t/4855/11

**Comment by marmarek** [comment]
In R4.1 there is checkbox in qube settings, see screenshot here: https://openqa.qubes-os.org/tests/18757#step/qubesmanager_vmsettings/5 (it is grayed out because the package is not installed, but then - you get info what package needs to be installed).

**Comment by marmarek** [comment]
There are some issues with the setting:
 - the feature controlling the thing is `service.shutdown-idle`, not just `shutdown-idle` (both in loading the feature and applying)
 - the `self.idle_shutdown_checkbox.setEnabled(False)` line is misaligned - disabling the thing always
 - there is an interaction with "services" tab - the basic tab is applied first, but then applying services tab removes the setting
