### ISSUE TITLE
Qube Starts but No Windows Open And No Error When Disk At Capacity

### ISSUE THREAD

**Issue by straussmaus** [QubesOS/qubes-issues#5299]
**Qubes OS version**
R 4.01
**Affected component(s) or functionality**
One Standalone Qube

**Brief summary**
A standalone Debian qube that worked for months now will not open any windows.  The Qube shows started (green dot in Qube Manager) but Terminal, Firefox, Files, anything will not open.  Other Qubes do open.

**To Reproduce**

_1. Open Q pull down menu
_2. Choose "Terminal" or any application from this standalone Qube
_3. See in Qubes Manager a green dot that the Qube is open
_4. See no Terminal or other application open.

**Expected behavior**
The application window (example "Terminal") should open.

**Actual behavior**
Just nothing.

**Additional context**
This Qube worked every day for many months.  

**Solutions you've tried**
Rebooting, opening from "Run command in qube" and opening other applications.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
I did not see a doc that answers this.

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

No other issues looked similar.

**Comment by marmarek** [comment]
Check console output of that VM, for example in `/var/log/xen/console/guest-VMNANE.log`. Maybe some service fails to start? Do you use testing repositories? Did it happened after some specific update?

**Comment by straussmaus** [comment]
@marmarek 

I don't see any clear errors.  The log does mention EXT3-fs (xvda3): re-mounted but no actual error.

I should be using the default repositories.  I did not change them (but I did add one or two some months ago).

>  Did it happened after some specific update?

I don't think so.  This is difficult to know because of the auto-updater.  It means I do not upgrade manually so I don't always remember what I upgraded.

Please remind me how to boot to the CLI for a Qube from the dom0 CLI?  I did that one to debug and it was very helpful.  The errors I get trying this will tell us something.

**Comment by straussmaus** [comment]
@marmarek

I tried `sudo xl console VMNAME` and I got a login prompt.  I can not log on though because this is the first time I saw a login prompt so I do not know what the root password is.  But this must give us some information.

**Comment by marmarek** [comment]
You can login as root without password.

**Comment by straussmaus** [comment]
@marmarek Now when I try `sudo xl console VMNAME` I get the error

`VMNAME is an invalid domain identifier (rc=-6)` and I am using the name of the Qube.  I get the same kind of error with `virsh -c xrn:/// console VMNAME` and the name of the Qube is typed the same as it shows in the Qubes Manager.  I did rename it a few times because I restored the bad Qube from a backup and renamed the bad one `VMNAMEBad` so I think this could be a different bug.  Should I create a new Issue?

**Comment by marmarek** [comment]
`sudo xl console VMNAME` and similar works only for running VMs.

**Comment by straussmaus** [comment]
@marmarek Okay.  Yes now I can log in with root and no password.  Now I can answer your question.  The repositories are standard. 

```
stretch main contrib non-free
stretch/updates main contrib non-free
```

When I log in as root and I try to `apt-get update` I get an error that there is no space left on the device.  I add 2G in the Qubes Manager and now windows will open.

So I think this is a bug because no useful error message was available to tell me that this was the problem.  I updated the title to show this.

Thank you for debugging with me, it solved my problem.  I will keep this open because I think this is really something you will want to fix (with a useful error message), thank you.

**Comment by straussmaus** [comment]
I seem to keep forgetting and posting this issue again.  Closing, because this one is more clear:

https://github.com/QubesOS/qubes-issues/issues/6416
