### ISSUE TITLE
restarting qubes-qube-manager with updating data

### ISSUE THREAD

**Issue by Aporbel** [QubesOS/qubes-issues#5302]
### Affected component(s) or functionality:
**qubes-qube-manager**

---

### Steps to reproduce the behavior:
I have an encrypted drive. I place the VMs there, VMs data is shown in **'qubes-qube-manager'**(which load data from _qubes.xml_). I modify _'/var/lib/qubes/qubes.xml'_ to display VMs when the disk is decrypted and not to display existing VMs when it is encrypted. I kill the proccess for restarting **'qubes-qube-manager'**. But the data remains the same, only restarting system gives the reading of the actual data from the _'/var/lib/qubes/qubes.xml'_

### Expected or desired behavior:
I want to modify the file and get the result based on the data in _'/var/lib/qubes/qubes.xml'_ without restarting system.
That is, for example, I have 5 VMs in the main memory and 5 in the encrypted section. I want to make it impossible to identify the presence of 5 machines in the system until the disk is decrypted.

### Actual behavior:
After killing procces of 'qubes-qube-manager' and starting him again, he take old (non-updated) data. New data is updated, but with a delay, maybe somewhere  can I change the file check _'/var/lib/qubes/qubes.xml'_?

### General notes:
Tried '` kill <process ID> && kill <parent's ID> && /bin/qui-domains '`
After modified 'qubes.xml' if I trying modify anything I get a error in **qubes-qube-manager**: "Someone else modified _qubes.xml_ in the meantime" but the action carried out.

---

### I have consulted the following relevant [documentation](https://www.qubes-os.org/doc/):
I consulted with https://www.qubes-os.org/doc/
I think that it all docs, I spent many time on learning this.

### I am aware of the following related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues:
None

**Comment by andrewdavidwong** [comment]
> I modify '/var/lib/qubes/qubes.xml' to display VMs when the disk is decrypted and not to display existing VMs when it is encrypted.
> [...]
> I want to modify the file and get the result based on the data in '/var/lib/qubes/qubes.xml' without restarting system.

Manually editing `/var/lib/qubes/qubes.xml` is neither recommended nor supported.

> I want to make it impossible to identify the presence of 5 machines in the system until the disk is decrypted.

See #2402 and #4444.

**Comment by andrewdavidwong** [comment]
This appears to be a [duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.
