### ISSUE TITLE
qvm-clone, maximum memory and disabled memory balancing (disabled meminfo-writer service)

### ISSUE THREAD

**Issue by brendanhoar** [QubesOS/qubes-issues#5306]
**Qubes OS version**
R4.0 current-testing

**Affected component(s) or functionality**
qvm-clone

**Brief summary**
source VM: initial=4096; max=4096; Include in memory balancing=UNCHECKED

**To Reproduce**
qvm-clone sourcevm targetvm

**Expected behavior**
target VM: initial=4096; max=4096; Include in memory balancing=UNCHECKED

**Actual behavior**
target VM: initial=4096; max=40**00**; Include in memory balancing=UNCHECKED

Right...4000, not 4096...plus there's also a hidden issue, discussed below.

**Additional context**
This leads to two issues:
1. A Windows 7 HVM clone that should be as stable as the source is not, either due to having a range of RAM assigned and/or having qmemman enabled (secretly?). Anyway Windows 7 crashes a lot until you can resolve the inproperly cloned settings.
2. If you go to the Qubes Setting GUI and navigate to the second tab, Qubes Settings warns you of the mismatch. If you click OK, it fixes the displayed maximum value to 4096. If you click OK, it *appears* you have corrected the value. You have not. If you open the Qubes Setting GUI again, and navigate to the second tab, the maximum is, again, set at 40**00**.

I cannot detect any significant differences between the output of qvm-preferences and qvm-features of the source and target (both have 0 in the maxmem), but the source does not have this issue and the target does.

I suspect what is happening is multi-pronged:
1) the 4000 is weird, probably standard fare bug.
2) the UI/CLI-based automatic handling, stored in qubesdb, of whether to perform memory ballooning (based on maxmem really being set to 0) are only two of the three ways this 0 can be set...however, qvm-clone is the third way and it is not automatically setting the ballooning info correctly in qubesdb.

Checking the checkbox, clicking apply, verifying or fixing the maxmem to 4096 if the UI hasn't already fixed it, then unchecking the checkbox and clicking OK resolves the issue each time.

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
https://github.com/QubesOS/qubes-issues/issues/4480

As above, the hidden qmemman setting was fixed in qvm-preferences and/or Qubes Settings, but was missed in qvm-clone.

From this previous thread, I don't even know if meminfo-writer is really a thing any more.

B

**Comment by brendanhoar** [comment]
in the qubes.xml, what exactly is the differences between <feature> name="qubesmanager.maxmem_value" ... and  <property> name="maxmem" ...?

FWIW, I think there appear to be some gaps between what I can get correctly stored for a cloned windows hvm via the GUI and via cli using qvm- commands.

**Comment by marmarek** [comment]
> in the qubes.xml, what exactly is the differences between <feature name="qubesmanager.maxmem_value" ... and <property name="maxmem" ...?

`qubesmanager.maxmem_value` is used by qubes manager only, to remember previous value of maxmem, while it is set to 0 (to disable dynamic memory management).

**Comment by brendanhoar** [comment]
Hmm, I think the weird behavior I am seeing with the Qubes Setting GUI's maxmem being 4000 instead of 4096 on the clone is related to the source VM having a PCI device configured but no value for qubesmanager.maxmem_value (as it was created entirely via CLI).

Both have the "Include in memory balancing" setting unchecked in the GUI, but the copy keeps showing a greyed out 4000 in the maxmem field, while the source correctly shows a greyed out 4096 in the maxmem field. Manually checking the "Include in memory balancing", clicking apply, and unchecking it, clicking apply and clicking OK clears the weird behavior (presumably as it sets the qubesmanager.maxmem_value correctly?

Notably, the copy created by qvm-clone does **not** have a PCI device configured.

1. Shouldn't it though? Shouldn't a clone be a clone, even if it prevents both VM copies from running at the same time?

2. Because the clone has no PCI device configured, there's probably a codepath being traversed that fills in the maxmem in the GUI correctly vs. the codepath without a PCI device that fills it in incorrectly.

Brendan

**Comment by marmarta** [comment]
The clone part is solved by https://github.com/marmarta/qubes-core-admin-client/commit/c0a8c6528a40312210ba1dd4b962109fbeaa9af0 , (this PR: https://github.com/QubesOS/qubes-core-admin-client/pull/136 ). Still working on the second problem :)

**Comment by brendanhoar** [comment]
Thanks!
