### ISSUE TITLE
Login password lost

### ISSUE THREAD

**Issue by e-man1** [QubesOS/qubes-issues#5307]
### Qubes OS version:

Hi,

I have Qubes 4.0 but have forgotten the login password. Is there a way to reset it or to bypass it somehow? If possible I’d rather not have to install qubes again.  

Thank you for your help! 

E-man1

### Affected component(s) or functionality:

---

### General notes:

---

**Comment by strugee** [comment]
The issue tracker isn't the appropriate place for this question. You should ask on the mailing list instead. https://www.qubes-os.org/support/

**Comment by e-man1** [comment]
Hi, thank you. The thing is when I open the link it’s just the general front page, I have no idea where to place the topic. Sorry to waste time.

Thank you 

Envoyé de mon iPhone

**Comment by andrewdavidwong** [comment]
> Hi, thank you. The thing is when I open the link it’s just the general front page, I have no idea where to place the topic. Sorry to waste time.

You have to read the page. :slightly_smiling_face: 

Specifically, this section: https://www.qubes-os.org/support/#qubes-users
