### ISSUE TITLE
VM choice of kernel-latest for Qubes default kernel often changes to non-latest on updates

### ISSUE THREAD

**Issue by brendanhoar** [QubesOS/qubes-issues#5309]
**Qubes OS version**
R4 current-testing with both kernel-latest and kernel-latest-qubes-vm

**Affected component(s) or functionality**
Default kernel for VMs

**Brief summary**
4.x series kernel becomes default kernel after updates,

**To Reproduce**
Install kernel-latest-qubes-vm
Set Qubes Global Settings/Kernel/Default kernel to 5.x series
...time passes...
qubes-dom-update
both kernel-qubes-vm and kernel-latest-qubes-vm received updates
check Qubes Global Settings/Kernel/Defalt
Note that it is now set to a 4.x series kernel

**Expected behavior**
If both packages are installed, the older version should not override a newer version

**Actual behavior**
Older kernel becomes default even though both a newer* kernel was the default and a newer kernel was installed in parallel.

**Solutions you've tried**
Manually check every time and reset it.

Note that it's not clear to me what the expected behavior should be. Keep the value the same until it is targeted for removal and then move to the next most recent within the same package?

B

\* so yes, a 4.x series kernel might be "newer" from one perspective if it has more recent security updates than the 5.x series kernel previously selected. however, an even newer (likely from all perspective) 5.x series kernel was also installed at the same time.

**Comment by brendanhoar** [comment]
Maybe one solution (though with repercussions on testing) is to uninstall kernel-qubes-vm?

**Comment by hexagonrecursion** [comment]
The code responsible for the change of the default vm kernel can be found here:
https://github.com/QubesOS/qubes-linux-kernel/blob/4e4cdf6d8ad2f77a644b17205ed8fa47cbbb4f81/kernel.spec.in#L558-L564
As you can see, kernel-qubes-vm sets itself as the default in the rpm %post scriptlet.

**Comment by hexagonrecursion** [comment]
Perhaps something like the below code can be used in the scriptlet:
```
if [ "$(rpm -q --file /var/lib/qubes/vm-kernels/"$(qubes-prefs default-kernel)" --qf '%{NAME}\n')" == %name ] ; then
  qubes-prefs --set default-kernel %version-%plainrel
fi
```
Warning: I have no experience in rpm scripting and the proposed solution is probably a disastrously bad idea for a dozen different reasons I'm not aware of. I'd like to hear those reasons though.

**Comment by marmarek** [comment]
This is great idea @hexagonrecursion ! This way if one choose kernel-latest as default kernel it will also update to newer kernel-latest on package update.

**Comment by brendanhoar** [comment]
Seemed to work as expected after this update...
