### ISSUE TITLE
PV USB

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#531]
**Reported by marmarek on 17 Apr 2012 12:59 UTC**
PV USB with Linux 3.x works fine, but needs some work to integrate with Qubes:
1. xen-usbfront and xen-usbback drivers (patch from xen-devel with some minor modification works ok). It is ready on my devel machine.
2. Add support for PV USB to libxl (or stay with standalone python scripts).
2a. This includes some script in backend VM (in some/most cases not dom0) that bind USB device to usbback driver - /usr/lib/qubes/unbind_pci_device.sh equivalent.
3. Add Qubes tool to manage USB devices (qvm-block equivalent).

Migrated-From: https://wiki.qubes-os.org/ticket/531

**Comment by adrelanos** [comment]
Can you please elaborate on the usability impact of PV USB? So once we have the USB VM and PV USB... Does it mean, that even if USB printer, USB input devices, USB phone connection, etc. are [all connected to same internal USB controllers](https://groups.google.com/forum/#!searchin/qubes-users/patrick$20schleizer$20printer/qubes-users/xBjy3M8izuM/kmH7_j5rt2MJ), that Qubes could selectively assign arbitrary devices to different VMs? The VMs would not have access to the real USB stack, but only a virtualized one?

**Comment by marmarek** [comment]
Yes, exactly. Of course still compromised USB VM could provide malicious
device to the target VM (instead of genuine one) and sniff all the
communication, but this would be much better than having full USB stack
in target VM (or even dom0).

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by marmarek** [comment]
Generally there are multiple implementations possible here:

1. Xen-specific PV USB drivers - project was dormant for a long time, but recently got [some attention](http://lists.xenproject.org/archives/html/xen-devel/2016-03/msg00247.html). Initially it was based on USBIP kernel driver. But currently backend driver is considered as part of qemu - haven't checked if that would work with driver domains (i.e. USB controllers in some USB VM instead of dom0).
2. USBIP - not Xen specific and since Linux ~3.19 moved out of "staging" tree to normal driver. This driver uses userspace tools for TCP communication and then pass socket FD to the kernel - it is possible to use qrexec socket instead of TCP.
3. OpenXT drivers - [Windows frontend](https://github.com/OpenXT/xc-vusb) and [Linux backend](https://github.com/OpenXT/xenclient-oe/tree/master/recipes-kernel/linux/4.4/patches). Linux frontend is [work in progress](https://github.com/OpenXT/pv-linux-drivers/tree/master/openxt-vusb).

USBIP seems to be the easiest and the most mature implementation, available in mainline Linux. I have some work in progress scripts for setting it up ("the backend part"). Will push it somehow this week. Probably needs help on frontend part (updating `qvm-usb` tool, adding Qubes Manager options etc).

cc @caschulz88

**Comment by caschulz88** [comment]
Hey, thanks for posting the possible implementation options here. For me also USBIP sounds the best way to go for an implementation. I'm looking forward to grab your code and work with it. Of course I'm also willing to support you and help on working on the backend and frontend part.

Please let me know as soon as it's online somewhere.

**Comment by marmarek** [comment]
Here: https://github.com/QubesOS/qubes-app-linux-usb-proxy
It requires: https://github.com/QubesOS/qubes-issues/issues/1876  (both dom0 and VM parts)
You can workaround that by editing `/etc/qubes-rpc/qubes.USB` in backend doman and hardcoding some device there (just for testing).
