### ISSUE TITLE
Some shutdown desktop notifications not showing for whonix-ws-15 based VMs after update

### ISSUE THREAD

**Issue by awokd** [QubesOS/qubes-issues#5312]
**Qubes OS version**
R4.0 current-testing

**Affected component(s) or functionality**
unsure

**Brief summary**
Some "Shutting down" and "Halted" messages MIA, but functionality not impacted.

**To Reproduce**
Shutdown AppVM based on whonix-ws-15 or debian-9 template, see both shutting down and halted popups
Shutdown anon-whonix based on whonix-ws-15 template, see only halted popup
Shutdown dispvm based on whonix-ws-15-dvm template, see neither popup

**Expected behavior**
See both popups on shutdown

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

Possibly https://github.com/QubesOS/qubes-issues/issues/5303 but I had rebooted after applying updates.

**Comment by awokd** [comment]
https://github.com/QubesOS/updates-status/issues/1303 (or some other update that came in at the same time) seems to have also disabled "Tor starting" and "Tor running" desktop notifications from sys-whonix. Not sure if same issue or new.

**Comment by marmarek** [comment]
No, this is intentional change in Whonix, details here: https://groups.google.com/d/msgid/qubes-devel/ce53949f-6b9b-17b2-ae31-451b647a46d1%40whonix.org

**Comment by adrelanos** [comment]
Is there still any issue here? @awokd

**Comment by awokd** [comment]
> Is there still any issue here? @awokd

Only with my biological memory. Thanks for the reminder.
