### ISSUE TITLE
Updates fail for 'vm-sudo' templates

### ISSUE THREAD

**Issue by tasket** [QubesOS/qubes-issues#5313]
**Qubes OS version**
R4.0.1

**Affected component(s) or functionality**
Linux templates

**Brief summary**
If a template is configured to prompt the user with a dialog when 'sudo' is invoked, it will display such a prompt when the user requests an update from the dom0 UI. The update will subsequently fail even if the user permits the 'sudo' request.

**To Reproduce**
1. Configure template according the the Qubes 'vm-sudo' doc.
2. Also configure dom0 according to the same doc.
3. Run an update of the template form the qui-updates widget.
4. When a 'VMAuth' prompt appears, click 'OK'.

**Expected behavior**
No prompt should appear and update should proceed smoothly.

**Actual behavior**
The following error appears:
```
Error on updating debian-10: Command '['sudo', 'qubesctl', '--skip-dom0', '--targets=debian-10', '--show-output', 'state.sls', 'update.qubes-vm']' returned non-zero exit status 67
```

**Additional context**
A similar issue appeared long ago with QM-initiated updates. The solution was to invoke the update script via the template's root user.

I don't know if its 'sudo' or 'su' or some other auth-triggering process that causes the prompt. But I think its much more preferable to launch the update from the root user.

**Solutions you've tried**
My qubes-multi-update script works fine with these template, because update is invoked via root user.

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

**Comment by GSF1200S** [comment]
I have not had the same issue as you, but my system is setup slightly different. In /etc/qubes-rpc/policy/qubes.VMAuth I have for example:

fedora-29 dom0 allow
disp-mgmt-fedora-29 dom0 allow
@anyvm dom0 ask,default_target=dom0

The idea behind my setup was not to have templatevms or updates bother me, but to enforce AppVMs prompting me for sudo via dom0. I just updated and Fedora completed without issues. If I am missing something, or if me testing something might help clarify the problem, let me know. I'll keep an eye on this issue...
