### ISSUE TITLE
When qube is starting, domains widget don't show its submenu

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#5315]
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
desktop-linux-manager
https://github.com/QubesOS/updates-status/issues/1295

**Brief summary**
Starting qube don't get a submenu, ">" symbol is missing and that menu row is misaligned.

**To Reproduce**
_Steps to reproduce the behavior:_
_1. Initiate qube start, for example start an application in non-running qube_
_2. Open domains widget_
_3. Observe entry for starting qube_

**Expected behavior**
Correct submenu for starting qube.

**Actual behavior**
No submenu, row is misaligned.

**Comment by marmarta** [comment]
weird, it works for me with current-testing domains widget. Is the VM special in some way? Do you have a very large amount of VMs running?

**Comment by marmarek** [comment]
Cannot reproduce now either.

**Comment by marmarta** [comment]
managed to reproduce it, fix incoming
