### ISSUE TITLE
Building archlinux template fails due pulseaudio incompatibility

### ISSUE THREAD

**Issue by ejose19** [QubesOS/qubes-issues#5317]
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
Qubes Builder

**Brief summary**
Trying to build archlinux template as stated by https://www.qubes-os.org/doc/building-archlinux-template/ fails because there's no compatibility by qubes-vm-pulseaudio (requires pulseaudio<12.3 and script pulls latest 13.0-1, so it throws error "unable to satisfy dependency"

**To Reproduce**
1. Follow the instructions stated in previous link
2. It will error on make gui-agent-linux-vm, apply the "fix" stated (https://www.qubes-os.org/doc/building-archlinux-template/#error-when-building-the-gui-agent-linux-with-pulsecore-error)
3. Continue with make template, and it will fail on what's explained in the summary

**Expected behavior**
make template should finish without errors

**Actual behavior**
make template errors with dependency issue

**Solutions you've tried**
I editted qubes-src/gui-agent-linux/archlinux/PKGBUILD (before 1st run of "make template") and removed the requirement 'pulseaudio<12.3' leaving only 'pulseaudio>=12.0'

**Comment by andrewdavidwong** [comment]
Possibly related: #4109

**Comment by ejose19** [comment]
@andrewdavidwong Yes, that issues explains what to do in the first error (which is already solved by following the guide). This error is at 'make template' command under chroot environment.

**Comment by ejose19** [comment]
This has been solved in https://github.com/QubesOS/qubes-gui-agent-linux/commit/9f1bca8dbbac007066156f552b736b636678e390

Now the template creation works without doing any "trick", just following the guide without doing troubleshooting, closing.

**Comment by huertanix** [comment]
Hi, I I'm on Qubes 4.0 and followed the guide (https://www.qubes-os.org/doc/building-archlinux-template/) without any additional tweaks and still ran into the same issue as encountered in #4109. Is this fix only available in 4.1?

**Comment by andrewdavidwong** [comment]
> Hi, I I'm on Qubes 4.0 and followed the guide (https://www.qubes-os.org/doc/building-archlinux-template/) without any additional tweaks and still ran into the same issue as encountered in #4109.

In that case, I'm confused as to why you're commenting on this issue rather than #4109.

> Is this fix only available in 4.1?

@fepitre, do you know?

**Comment by huertanix** [comment]
@andrewdavidwong Upon further inspection, I've realized it's a new version of pulseaudio causing the issue. This issue as well as #4109 are related but are different as they address and fix issues with older versions when they were missing.

**Comment by fepitre** [comment]
@andrewdavidwong the fix will certainly go into `release4.0` but as we are still on CI transition since one week, we want CI back on every stable branches before continuing to merge anything. @marmarek could state if he wants to backport the fix sooner.

**Comment by andrewdavidwong** [comment]
> @andrewdavidwong the fix will certainly go into `release4.0` but as we are still on CI transition since one week, we want CI back on every stable branches before continuing to merge anything. @marmarek could state if he wants to backport the fix sooner.

Ok, so it sounds like the fix for this will reach 4.0 eventually. I think you may just need to wait for it, @huertanix.
