### ISSUE TITLE
Qubes Thunderbird extension no longer works in Thunderbird 68.1.0

### ISSUE THREAD

**Issue by Geblaat** [QubesOS/qubes-issues#5318]
**Qubes OS version**
R4.0.1

**Affected component(s) or functionality**
Qubes Thunderbird extension (open attachment in DispVM, sent to VM etc.)

**Brief summary**
After updating Thunderbird from 60.8.0 to 68.1.0 in Fedora 30 TemplateVM, the Qubes specific options for attachments are gone. The extension list shows disabled extensions that are not compatible with Thunderbird 68, but the Qubes extension is not listed here.

**To Reproduce**
Update Thunderbird to 68.1.0 in Fedora 30 TemplateVM.

**Expected behavior**
Qubes attachment functionality still works.

**Actual behavior**
Qubes attachment functionality has disappeared.

**Additional context**
This may be related to the fact that Thunderbird 68 only accepts Webextensions. However, one would expect it to be listed among disabled extensions.

**Comment by andrewdavidwong** [comment]
@marmarek: Even after enabling the `current-testing` repo, I don't see any update available for Fedora 29. All I see available is `1.2.13`, which I already had installed.

**Comment by marmarek** [comment]
I do see the update here: https://yum.qubes-os.org/r4.0/current-testing/vm/fc29/rpm/thunderbird-qubes-2.0.0-1.fc29.noarch.rpm
Is it a template from R3.2, that still uses R3.2 repositories?
Also note the package have dependencies set to install only with thunderbird >= 68, if you have older one, this update won't install.

**Comment by andrewdavidwong** [comment]
> Is it a template from R3.2, that still uses R3.2 repositories?

Nope, it's a fresh R4 Fedora Minimal template using 4.0 repos.

> Also note the package have dependencies set to install only with thunderbird >= 68, if you have older one, this update won't install.

I only have `thunderbird-68.1.0` installed.

Maybe the problem is that I'm using the onion repo?

**Comment by andrewdavidwong** [comment]
> Maybe the problem is that I'm using the onion repo?

Yep, that was it. Switching to the clearnet address worked.

**Comment by Geblaat** [comment]
The new version from testing repo fixed it for me. Note that the extension was still disabled in thunderbird and I had to enable it manually.

**Comment by speedtester** [comment]
Hi,

I'm having the same problem but with the debian templatevm.
After the thunderbird updated from 60 -> 68, the extension is not working, and is not showing in extensions, although it is installed:

`apt search qubes-thunderbird
Sorting... Done
Full Text Search... Done
qubes-thunderbird/unknown,now 1.2.13-1+deb10u1 amd64 [installed,automatic]
  The Qubes extension for Thunderbird`

Tried manually enabling in extensions.json without success.
I guess the problem is with the incorrect version: 1.2.13-1 vs 2.0.2-1. 
How can I update the extension properly in the debian templatevm?

Thanks.

**Comment by speedtester** [comment]
> Anyway, I'll re-enable it in a moment, you'll get notification from @qubesos-bot when it's ready.

Thanks, it works!!!

**Comment by speedtester** [comment]
When will it be available in the (non-testing) default repository?

**Comment by marmarek** [comment]
On Monday.

**Comment by speedtester** [comment]
Great, thanks!
