### ISSUE TITLE
Add more restrictive Filecopy

### ISSUE THREAD

**Issue by HW42** [QubesOS/qubes-issues#5319]
[ Based on a mail from @DemiMarie to security@. Moving this here since we consider this an enhancement proposal and not a bug that needs private handling. ]

**The problem you're addressing (if any)**

Currently the Filecopy service is quite liberal what it accepts (strange filenames, abitrary symlinks, ...).

Rationale for the current behavior (citing @marmarek):
> Yes, this is a risk. We've discussed extensively (years ago) whether to
> allow symlinks at all or not. Result of that discussion was basically:
> better allow symlinks in our minimal file copy protocol with some
> safeguards like chroot(), than let users use more complex formats for
> transferring more files, with more risks on unpacking site instead. We
> transfer file permissions for the same reason.

**Describe the solution you'd like**

The proposal is to split this into two services. One with restrictive filtering ("normal" file names, no symlinks, no file mode, ...), which probably should be the default. And for cases where those features are needed the current version.

**Where is the value to a user, and who might that user be?**

In the most common case when copying stuff you care only about the name (which won't contains strange stuff like control chars or newlines) and the data. So make this case safer.

**Comment by iamahuman** [comment]
Maybe control this with a service argument e.g. `qubes.Filecopy+strict` / `qubes.Filecopy+loose`

**Comment by UndeadDevel** [comment]
It seems that this was "half"-implemented, i.e. the more secure file copy added but the old one removed; either way, it looks like this is either already completed (if issue is defined solely by title) or will be completed once #8332 is.
