### ISSUE TITLE
DisposableVMs aren't always reset properly

### ISSUE THREAD

**Issue by HW42** [QubesOS/qubes-issues#5323]
[ Reported by @DemiMarie to security@. Since it appears to be hard to hit and we currently don't know how to reproduce moving this into the public. ] 

**Qubes OS version**

4.0

**Affected component(s) or functionality**

DisposableVMs

**Brief summary**

Citing @DemiMarie:
> Under certain (rare) conditions, DispVM private volumes may not be
> reverted to that of their templates.  This has happened to me, but I do
> not have a reproduction case.  I hit it when using a named disposable
> ProxyVM and trying to change the template of its template.

>> Was unclean system shutdown involved?
>
> Yes, it was.  That said, I would not expect this to matter, and still
> consider this a vulnerability.  Furthermore, the problem continued even
> after subsequent clean shutdowns.
>
>>>  I hit it when using a named disposable
>>> ProxyVM and trying to change the template of its template.
>>
>> This operation should be blocked. Did you get something else?
>
> No.  I had to work around that limitation (which I may be able to propose
> a patch for) manually.

**To Reproduce**

Unknown. Probably/Maybe important:
> If I recall correctly, crucial elements included:
> 
> * Having two named DispVMs with the same template.
> * Unclean system shutdowns (probably due to hardware problems).

**Expected behavior**

DisposableVM state is discarded.

**Actual behavior**

DisposableVM state persists.

**Additional context**

Observation from @marmarek:
> I think unclean system shutdown is important factor here. There is
> explicit check to not reset unclean volume to avoid data loss in case if
> it's persistent. Looking at the code, there is a check for
> "save_on_stop" property (whether data should persist) in
> ThinVolume.start() function, but maybe some other place is missing this
> check.

**Comment by DemiMarie** [comment]
If we want to try to reproduce this issue, I recommend using Qubes-in-KVM, so that we can simulate unclean shutdowns.

**Comment by rustybird** [comment]
> I recommend using Qubes-in-KVM, so that we can simulate unclean shutdowns.

This might be close enough:

    systemctl stop  qubesd
    for vm in vmname1 vmname2 vmname3; do sudo virsh destroy "$vm"; done
    systemctl start qubesd

**Comment by DemiMarie** [comment]
Fixed in R4.1 by QubesOS/qubes-core-admin#397.  Not sure if this will be backported.
