### ISSUE TITLE
Setting the default template to none renders Qubes OS unusable

### ISSUE THREAD

**Issue by hexagonrecursion** [QubesOS/qubes-issues#5326]
**Qubes OS version**
Qubes release 4.0 (R4.0)

**Affected component(s) or functionality**
qubesd and Qubes Global Settings

**Brief summary**
Qubes Global Settings allows setting the default template to none, but doing so renders Qubes OS unusable after a reboot.

**To Reproduce**
1. Open Qubes Global Settings
2. Set default template to none
3. Press OK
4. Reboot

**Expected behavior**
It should either not be possible to set the default template to none (at least via GUI) or qubesd should not fail to start when it is none.

**Actual behavior**
Qubes OS is unusable: can't start any qubes, can't open Qubes Manager, can't even open Qubes Global Settings or run qubes-prefs to fix the situation.

**Additional context**
Relevant entry from the dom0 journal:
```
dom0 qubesd: Traceback (most recent call last):
dom0 qubesd:   File "/usr/bin/qubesd", line 5, in <module>
dom0 qubesd:     sys.exit(main())
dom0 qubesd:   File "/usr/lib/python3.5/site-packages/qubes/tools/qubesd.py", line 33, in main
dom0 qubesd:     args = parser.parse_args(args)
dom0 qubesd:   File "/usr/lib/python3.5/site-packages/qubes/tools/__init__.py", line 362, in parse_args
dom0 qubesd:     offline_mode=namespace.offline_mode)
dom0 qubesd:   File "/usr/lib/python3.5/site-packages/qubes/app.py", line 834, in __init__
dom0 qubesd:     self.load(lock=lock)
dom0 qubesd:   File "/usr/lib/python3.5/site-packages/qubes/app.py", line 937, in load
dom0 qubesd:     self.property_require('default_template')
dom0 qubesd:   File "/usr/lib/python3.5/site-packages/qubes/__init__.py", line 730, in property_require
dom0 qubesd:     raise ValueError('Property {!r} cannot be None'.format(prop))
dom0 qubesd: ValueError: Property 'default_template' cannot be None
dom0 libvirtd: 2019-09-17 15:00:21.188+0000: 910: error : virNetSocketReadWire:1808 : End of file while reading data: Input/output error
dom0 systemd: qubesd.service: Main process exited, code=exited, status=1/FAILURE
dom0 systemd: Failed to start Qubes OS daemon.
dom0 systemd: qubesd.service: Unit entered failed state.
dom0 systemd: qubesd.service: Failed with result 'exit-code'.

```

**Solutions you've tried**
The only way to get Qubes OS working again is to manually edit qubes.xml or replace it with a backup.

There is an unobvious way to hose yourself via GUI + if you trigger it, you can't even get back to the settings app = bad UX.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
none

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
none found

**Comment by marmarta** [comment]
@marmarek , take a look at this...
