### ISSUE TITLE
disposable VMs remain on qui Qubes Domains menu after shutdown/exit

### ISSUE THREAD

**Issue by brendanhoar** [QubesOS/qubes-issues#5327]
**Qubes OS version**
R4.0 current-testing kernel-latest

**Affected component(s) or functionality**
Qubes Domains menu

**Brief summary**
Menu item for exited VM remains.

**To Reproduce**
After successfully shutting down a disposable VM using the menu or closing the opening application, the menu entry for the VM remains in the menu with 0MB memory usage until rebooting Qubes.

**Expected behavior**
Menu item is removed.

**Actual behavior**
Menu item remains.

**Additional context**
xentop does not show the VM, so xen believes it has exited.
qvm-ls --running does not show the VM, so qubes believes it has exited.

**Comment by marmarta** [comment]
does it happen all the time, or only sometimes?

**Comment by brendanhoar** [comment]
Currently all the time.

**Comment by marmarta** [comment]
I think one of the fixes got rolled back during the "CPU usage" batch of updates - I pushed a fix with that and some more fixes applied.
