### ISSUE TITLE
kernel-qubes-vm-1000:4.19.71-1breaks Whonix routing

### ISSUE THREAD

**Issue by AnonymousCat5** [QubesOS/qubes-issues#5331]
**Qubes OS version**
Qubes release 4.0 (R4.0)

**Affected component(s) or functionality**
Routing traffic via sys-whonix.

**Brief summary**
After upgrading packages kernel-1000 and kernel-qubes-vm-1000 to version 4.19.71-1, Whonix AppVMs fail to connect to the internet.

**To Reproduce**
1. Run qubes-dom0-update in dom0
2. Install kernel{-qubes-vm}-1000:4.19.71-1
3. Reboot system
4. Start an AppVM that is connected via sys-whonix
5. Run whonixcheck inside AppVM (in case it is based on Whonix Workstation)

**Expected behavior**
Whonixcheck succeeds, AppVM can connect to the internet via Tor.

**Actual behavior**
AppVMs that have Whonix Gateway (aka sys-whonix) as their NetVM fail to connect to the internet. WhonixCheck report:

```
[INFO] [whonixcheck] disp7417 | Whonix-Workstation | whonix-ws-15-dvm DispVM AppVM | Thu 19 Sep 2019 05:55:18 AM UTC
[ERROR] [whonixcheck] Tor Connection Result:
Tor's Control Port could not be reached!

Troubleshooting:
- Confirm that Whonix-Gateway is running.
- Run whonixcheck on Whonix-Gateway and confirm success.

- Rerun whonixcheck here in this Whonix-Workstation.

(Technical information:)
(tor_circuit_established_check_exit_code: 277)
(tor_bootstrap_timeout_type: )
(tor_bootstrap_status: )
(check_socks_port_open_test: 28)
(Tor Circuit: not established)
```

Connections that originate _from within_ sys-whonix still work. Whonixcheck inside sys-whonix is successful.

**Additional context**
https://forums.whonix.org/t/tor-socksport-unreachable-just-in-anon-whonix/8072

**Solutions you've tried**
Setting an older default VM kernel (4.14.103-1) in the “Qubes Global Settings” in Qubes Manager solved the issue.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
N/A

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
Nothing known.

**Comment by awokd** [comment]
Might be https://github.com/QubesOS/qubes-issues/issues/5110 ?

**Comment by marmarek** [comment]
Can anyone still reproduce it?

**Comment by AnonymousCat5** [comment]
Problem solved itself after some kernel upgrade. Closing.
