### ISSUE TITLE
Installing QWT 4.0.1.3 Disables Network Access in Windows 10

### ISSUE THREAD

**Issue by GWeck** [QubesOS/qubes-issues#5332]
**Qubes OS version**
R4.0.1 fully updated

**Affected component(s) or functionality**
Qubes Windows Tools 4.0.1.3

**Brief summary**
I created a Windows 10 Standalone VM. This had access to the local net and to the Internet. After installing QWT, including the PV network driver, network access was lost. In  the VM, the network interface was shown as having no connectivity.

**To Reproduce**
Install QWT 4.0.1.3 on a Windows 10 Standalone VM.

**Expected behavior**
Network access should be preserverd.

**Actual behavior**
No more network connectivity, even to the local network

**Solutions you've tried**
The cause of the sems to be that required services are deactivated. After setting the startup mode for IP-Hilfsdienst (don't know how this is called in an English version of Windows) and DHCP-Client and after reconfiguring the network interface to use the correct manual configuration,
network access including Internet access is restored.
**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
_A list of links to the Qubes documentation (or other relevant software documentation) pages you have already consulted._

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
#3585

**Comment by GWeck** [comment]
It seems that these effects were caused by the fact that the original VM was taken from Qubes R3.2.

I now created an empty standalanone VM under R4.0.1, installed Windows 10 in this VM and then installed QWT 4.0.1.3 into it.

After the second boot, no window was shown, however. This was caused by the qvm-features parameter gui set to blank. After setting gui and gui-emulated to 1, the window is displayed, and now this VM seems to be stable.
 
Clipboard copy works in both directions. File copy from Windows to other VMs works. File copy into Windows does not work: The copy selector is displayed, but then no file appears in the windows VM - at least, I did not find any.

**Comment by brendanhoar** [comment]
If you did not name your primary windows user “user” then it ends up deep in the bowels of the system folder somewhere...

**Comment by marmarek** [comment]
> If you did not name your primary windows user “user” then it ends up deep in the bowels of the system folder somewhere...

It shouldn't be the case, if you modify `default_user` VM property accordingly.

**Comment by GWeck** [comment]
Setting this VM default_user property did the trick: Now files can be sent to Windows 10.

If the default_user property is set to the wrong user name, the files are stored in
  C:\Windows\System32\config\systemprofile\Documents\QubesIncoming\<sending-VM-name>

Now the Windows 10 VM runs most of the time OK. Often, however, it is killed because of qrexec timeout - Qubes complains that no connection to the qrexec agent is possible, although both proesses Qubes RPC agent and QubesDB daemon are running, according to the task manager. This happens after most starts of the VM. I fixed this by setting the qrexec_timeout property of the VM to 14400, which is enough for me.

**Comment by GWeck** [comment]
If the qrexec agent of  Windows 10 VM cannot be connected, this VM cannot be shut down from within Windows. If one tries to execute the Windows shutdown command, the error message that Qubes cannt connect to the qrexec agent is displayed immediately - no wait for timeout -, the VM is shut down and restarted immediately.

If the VM is shut down from the Qube Manager, an error message is displayed after about 30 seconds. Windows collects some error information and displays the peculiar error 0x0000dead in the xenbus.sys driver. In this case, the VM stays down, but can be started manually.

Could this be a problem with the Xen drivers?

**Comment by GWeck** [comment]
See #5462

**Comment by GWeck** [comment]
Since #5462 now seems to provide a solution, I close this issue.
