### ISSUE TITLE
failed to synchronize cache for repo qubes-templates-itl-testing

### ISSUE THREAD

**Issue by homotopycolimit** [QubesOS/qubes-issues#5333]
### Qubes OS version:
Qubes release 4.0 (R4.0)

The problem is cause by the file 
https://yum.qubes-os.org/r4.0/templates-itl-testing/repodata/repomd.xml.metalink   
which has zero size!

This results in an error when attempting to install a template (such as debian 10) from the itl-testing repository.

### Affected component(s) or functionality:

qubes-dom0-update

---

### Steps to reproduce the behavior:

enable the qubes-templates-itl-testing repo in /etc/yum.repos.d/qubes-templates.repo in dom0 running qubes 4.0 and then run sudo qubes-dom0-update qubes-template-debian-10

### Expected or desired behavior:

Debain 10 template is installed

### Actual behavior:

error message about failure to synchronize cache for the repo

### General notes:

---

**Comment by marmarek** [comment]
Fixed, thanks for the report.
