### ISSUE TITLE
logger running on Qubes

### ISSUE THREAD

**Issue by straussmaus** [QubesOS/qubes-issues#5338]
**Qubes OS version**
4.0.1

**Affected component(s) or functionality**
Application Qubes (tested on Debian 9)

**Brief summary**
Debian 9 Qubes have started having `logger` processes (along with `cat`) for no reason I know.  It slows the system down a lot.

**To Reproduce**
_Steps to reproduce the behavior:_
_1. Create a Debian 9 Qube based on template
_2. Use it for a while
_3. Someday your whole computer will be slow with the fan on
_4. `ps` shows `logger` and `cat` running.

**Expected behavior**
logger and cat should not be running like this, right?

**Additional context**

I think this is a Qubes error because `pstree` shows this:

```
systemd───qubes-desktop-r───qubes-rpc-multi───logger
```

**Solutions you've tried**
Rebuilding the Qubes, killing the process (makes the system speed up again)

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
_A list of links to the Qubes documentation (or other relevant software documentation) pages you have already consulted._

I don't see any doc that explains why `logger` and `cat` should run.
**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
_A list of links to other bug reports, feature requests, or tasks in the qubes-issues tracker (or "none" if you didn't find any). Do not describe any other unreported bugs, features, or tasks here._
none that I could see

**Comment by marmarek** [comment]
> _3. Someday your whole computer will be slow with the fan on

You didn't said that, but I assume you meant the `logger` process use a lot of CPU, right? What do you see on `top` output?

`logger` process is a part of normal qrexec call, I guess `qubes.StartApp`  (based on partial name `qubes-desktop-r` visible there). It if use a lot of CPU, it probably means some application produce a lot of output. So, the actual reason is that application, not the logger process itself. 
To find more, you can either see `journactl` command to see what is logged there, or see what actual application is connected there (should be another child of `qubes-desktop-run`). 

Anyway, this looks to be more suited for qubes-users mailing list.

**Comment by straussmaus** [comment]
@marmarek Maybe but please let me ask a few questions first before we decide it is not a bug.

- No, `logger` process does not use a lot of CPU but there is close correlation to my system fan running.  But I am most worried about why it runs at all.  The fans were only my indication.  I am worried I have serious spyware (maybe in the debian9 template?)

Some other things to help you and me decide if it is bug or feature:

- First I think this is something that only started to happen recently.

- Please tell me what you mean by "logger process is a part of normal qrexec call" meaning, why would it be running in a Qube?  I am trying to find if this is a bug or a feature.  Like what exact action should cause this process to start? 

- Also the process always runs with `tee` and `cat` and they also go back to `qubes-desktop-r` so does this also make sense that `tee` and `cat are "part of normal qrexec call?"

I am starting to be worreed that there is a virus or spyware that infected all Qubes, or maybe the Debian 9 template and is reporting logs and `cat` and `tee` data to someone.  Really kind of scared right now.

**Comment by marmarek** [comment]
> * Please tell me what you mean by "logger process is a part of normal qrexec call" meaning, why would it be running in a Qube?  I am trying to find if this is a bug or a feature.  Like what exact action should cause this process to start?
> 
> * Also the process always runs with `tee` and `cat` and they also go back to `qubes-desktop-r` so does this also make sense that `tee` and `cat are "part of normal qrexec call?"

Part of a qrexec service (for example used to start an application when you click on it in the menu) is redirecting its output to a system log. This is done with a shell script that use `tee`, `cat, and `tee`. Example (expected) process tree:
```
        ├─qubes-desktop-r─┬─(actual application)
        │                 ├─qubes-rpc-multi───cat
        │                 ├─qubes-rpc-multi─┬─logger
        │                 │                 └─tee
```

If it's only correlation, maybe the thing slowing down your system is the actual application started there? Is it firefox by a chance? ;) observe `top` to see what is using the CPU. See also at free memory, maybe it is swapping which could cause similar effect.

**Comment by straussmaus** [comment]
@marmarek 

> This is done with a shell script that use tee, cat, and tee`. Example (expected) process tree:

Okay so you verify that this is correct to see for Qubes?  Definitely?  Then I am not experiencing spyware.

> If it's only correlation, maybe the thing slowing down your system is the actual application started there? Is it firefox by a chance? ;) 

It is not firefox but I see why you guess that.  I think the problem is a combination of having so many Qubes open and a little paranoia.  Thank you for explaining this.

One more question: does this script also exist in the Fedora 29 template?  I never saw it there and that was one reason I was scared.

**Comment by marmarek** [comment]
> Okay so you verify that this is correct to see for Qubes?

Yes.

> One more question: does this script also exist in the Fedora 29 template?

Yes, it's part of qubes-core-agent package, installed in all the templates.
