### ISSUE TITLE
Deduplicate /boot/grub/grub.cfg kernel boot parameters /etc/default/grub

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#5340]
/etc/default/grub contains:

> GRUB_CMDLINE_LINUX="root=/dev/mapper/dmroot console=hvc0 console=tty0 swiotlb=8192 root=/dev/mapper/dmroot console=hvc0 console=tty0 swiotlb=8192 noresume"

Inside that line, following part is duplicated:

> root=/dev/mapper/dmroot console=hvc0 console=tty0 swiotlb=8192

----

`/etc/default/grub.d/30-qubes.cfg` then again adds:

> console=hvc0 console=tty0

----

I don't know if duplicate options can cause problems but it makes boot parameters more difficult to read and modify.

Related: #5212

**Comment by rapenne-s** [comment]
I don't think this issue is relevant anymore.

- `/etc/default/grub.d/30-qubes.cfg` doesn't exist on R4.1
- the parameter `console` is set to `none` on R4.1, and only once.
