### ISSUE TITLE
Problem with dependencies in kali linux

### ISSUE THREAD

**Issue by tocaphares** [QubesOS/qubes-issues#5341]
**Qubes OS version**
R4.0.1

**Affected component(s) or functionality**
Debian template with Kali Linux repositories

**Brief summary**
There is a problem when trying to dist-upgrade because one of the packages related to Qubes OS and more precisely with pulseaudio wants to be removed.

**To Reproduce**
Run sudo apt-get dist-upgrade in kali linux template

**Expected behavior**
Upgrade without problems.

**Actual behavior**
Upgrade with delete important qubes packages.

**Additional context**
I put the whole package list from dist-upgrade command with -V option on privatebin for the whole month

https://privatebin.net/?ae0e1b526b106f1c#82kHC6sCdqtuWqcPuRPyKM44NmUjWMM7PMdR2x6NTwZ4

Password:27shBS5ys52dplajv72G54[spqD

In sources I have kali linux rolling repo and debian buster.

**Comment by tocaphares** [comment]
In sources I have kali linux rolling repo and debian buster repo.

**Comment by fepitre** [comment]
This problem is going to be solved with bullseye. Moreover, a template for kali is on the road. Should be released soon (https://github.com/fepitre/qubes-template-kali https://github.com/QubesOS/qubes-builder/pull/90 https://github.com/QubesOS/qubes-template-configs/pull/7).

**Comment by unman** [comment]
@tocaphares Have you tried the kali template? Does it solve your issue?
In general, because Kali is based on Debian unstable there will always be issues like this.

**Comment by ideologysec** [comment]
how does one get/install the kali-linux template for Qubes?

**Comment by xaki23** [comment]
> how does one get/install the kali-linux template for Qubes?

https://www.qubes-os.org/doc/pentesting/kali/

i prefer something like the "katoolin" way, but only use the katoolin script to add the key + source entry.

**Comment by ideologysec** [comment]
@xaki23  I actually asked about the "kali template" specifically because there's a libgcc1/gcc-8 dependency issue in the latest Debian testing when following the instructions on the page you linked to; also based on the commits linked to this by @fepitre upthread, there was some kind of kali-linux template merged into the Qubes Template repo, though it looks like it's for 4.1 only unless I missed something.

**Comment by SvenSemmler** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

On Sun, May 24, 2020 at 04:28:38PM -0700, Eric wrote:
> @xaki23  I actually asked about the "kali template" specifically because there's a libgcc1/gcc-8 dependency issue in the latest Debian testing when following the instructions on the page you linked to; also based on the commits linked to this by @fepitre upthread, there was some kind of kali-linux template merged into the Qubes Template repo, though it looks like it's for 4.1 only unless I missed something.

You could build it with qubes-builder. 

/Sven


- -- 
 public key: https://www.svensemmler.org/0x8F541FB6.asc
fingerprint: D7CA F2DB 658D 89BC 08D6 A7AA DA6E 167B 8F54 1FB6

-----BEGIN PGP SIGNATURE-----

iQIzBAEBCgAdFiEE18ry22WNibwI1qeq2m4We49UH7YFAl7LDRkACgkQ2m4We49U
H7bc7A/+JrIn4OUUhr0cZ8+Sn7DHs7UDnImusH88zJrpNxtF9XEQpGZTzqHjAj7h
BHWw4rASwT8jm8EVRqQXN1QIbEAGcwee6rt+KtY1khmzYG0uByEl+KcGVpZKg4uw
7bmzhRhiUjrgr14Pst4TE8NmSHTSZHrn9pRZ+56Q1wFzh8jpC1sKO3ZSIXm7U2my
znD7PDHkMGcIIdiC3xAgTphhgLgbU7HGcGmNjQUa147H3ut2GFxdGtTg5oG+FqX8
kpSTWUjRPHyxWd/X0d2+wCkig8Bf+Mo2e5/9Gb3uyv3tGCreFdwBERWBfbU38UJO
UB1x6W0aSEFyh9kJvXh48dDzjrWaIzchiCYxu5StR1pXicF6T1htv8q+y9auKs06
MA2EFCQwCQqpttWQoOJE58M0eAIhnrMYuNqBERva0XVIgpwPVW8vzzP95hHrNaIE
rufIEjHXaFw69cSUCEqm6siKD0DPlSdOmHoTRYL4DVfvojT8JD6TqS9SV9D/rHnm
jrjZyFkNjI63wvGH+ZO1zyVaVKYpMuPmjJ74VEOYF0ki66JNwAebWX+ZgAlB2FRh
WHBZmd+/pB/+xF/Nnopu9cXEevm97WLVAgGpqPxiE14cZSEohE/D77dIQfeyXplj
2rG9oxy8ycdPBhM0z6nuO65G0Jl7ucd0OnQk0vIzyFLz2jaJtZQ=
=8Wov
-----END PGP SIGNATURE-----

**Comment by fepitre** [comment]
There is pending PR to fix build issues on bullseye. Those are needed for Kali. Initially, when I make available bullseye and kali it was right before a big issue with Salt who broke almost everything because debian removed it from testing/unstable repositories. Then python2 switch. It should now be good.

**Comment by fepitre** [comment]
@andrewdavidwong I think we can close this one. Bullseye and Kali are in repositories since few weeks so normally no more issue with missing dependencies.
