### ISSUE TITLE
32GB / 28.9 GiB Flash Drive rejected by installer as too small

### ISSUE THREAD

**Issue by ginto37** [QubesOS/qubes-issues#5345]
**Qubes OS version**
_The version of Qubes OS you're using (e.g., `R4.0`), available via the command `cat /etc/qubes-release` in a dom0 terminal._

R4.0.1 Installer (checksums and signature confirmed, installer verified via Grub menu tool)

**Affected component(s) or functionality**
_The component or functionality of Qubes OS that is not working as expected._

Installation Destination dialogue

**Brief summary**
_A clear and concise summary of the bug._

The installer for R4.0.1 rejects my 32GB / 28.9 GiB flash drive as too small, saying it needs an extra 1.55 GiB of space. This is at default settings and after reclaiming all possible drive space to produce a completely empty drive. All the official documentation indicates that 32GB should be sufficient.

**To Reproduce**
_Steps to reproduce the behavior:_

*All options were left at their defaults unless specified*

1) Boot Installer, click Done to confirm default language and location
options and reach the Installation Summary screen.

2) Enter the "Installation Destination" screen by following the
on-screen prompts.

3) Select the 32GB flash drive and de-select all others. This screen
reports the drive space in Base-2, so 28.9 GiB for the 32GB flash drive.

4) Click Done to reach the Installation Options window. It reports:
> Your current Qubes software selection requires 22.91GiB, including
19.39GiB for software and 3.52 GiB for swap space.

5) On the Reclaim Disk Space screen, re-claim all drive
space with the Delete All button, then click Done.

**Expected behavior**
_A clear and concise description of what you expected to happen._

6) This should bring us back to the Installation Summary screen, where we can now begin the installation to the flash drive

**Actual behavior**
_What actually happened (instead of what you expected to happen)._

It all goes wrong at the following steps:

5) On the Reclaim Disk Space screen, it now reports:
> Installation requires a total of 24.23GiB for system data.

Now we need 24.32 GiB instead of 22.91 GiB - an increase
of 1.41 GiB. We still have enough space though, so we re-claim all drive
space with the Delete All button, then click Done.

6) This brings us back to the Installation Summary screen, where a
warning banner at the foot of the screen reports:
> Not enough space in file systems for the current software selection.
> An additional 1.55 GiB is needed.

Now we're 1.55 GiB short, so the total install is 30.45 GiB (32.7GB) -
an increase of 6.13 GiB from the Reclaim Disk Space Screen, and now we
can't install to the 32GB flash drive.

**Screenshots**
_If applicable, add screenshots to help explain your problem._

**Additional context**
_Add any other context about the problem here._

I've just noticed that 28.9 GiB translates to 31 GB, not 32 GB (_29.8_ GiB is 32GB), and further checking shows that each of the identical branded 32GB drives I own are reported as 31 GB, not 32 GB, in various OSes. However, I'm not sure this matters in this context because the reported shortfall of 1.55 GiB translates to 1.66 GB, so 32 GB would still prove too small. This also doesn't explain the ever-increasing storage demands from one step to the next.

**Solutions you've tried**
_If applicable, any solutions or workarounds you've already tried._

I repeated the process over several boots of the installer with no change.
I tried disabling Encryption on the Installation Destination screen, but
the error remains.
I tried using the "I will configure partitioning" option to reach the
Manual Partitioning screen. I used the "click here to create
[partitions] automatically" option, and it successfully creates the
root, swap and EFI partitions with 21.26 GiB, 2.89 GiB and 500 MiB
respectively. On completion, it reports remaining space as 1.97MiB, so
that looks positive. But when I save the settings and return to the
Installation Summary screen, the error message appears, and I'm
1.55 GiB short again.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
_A list of links to the Qubes documentation (or other relevant software documentation) pages you have already consulted._

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
_A list of links to other bug reports, feature requests, or tasks in the qubes-issues tracker (or "none" if you didn't find any). Do not describe any other unreported bugs, features, or tasks here._

None

**Comment by andrewdavidwong** [comment]
@marmarek, if this is now expected, should we update the documentation to increase the required storage size?

**Comment by marmarek** [comment]
Looks like a bug in disk space calculation. I've just tried test install with 30GB and I see in the log:
```
anaconda: fs space: 18.42 GiB  needed: 19.58 GiB
```
Then, I've deselected Whonix and it was enough to fit.

Strange thing is, the final partition layout is:
- 1GB for /boot
- 28GB for LUKS+LVM
Looks fine for now, but when looking into LVM, there is:
 - 3GB swap (wanted to be ~6GB, but installer capped it at 10% disk space)
 - 21.66GB for thin pool, including root
 - 4.3GB **unallocated**

I think the last point is manifestation of those differences, but I have no idea (yet) why it happened. Maybe it's related to space reclaim wizard? Have you tried erasing target flash drive first and the starting the installation?

**Comment by ginto37** [comment]
Marek Marczykowski-Górecki:
> Looks like a bug in disk space calculation. I've just tried test install with 30GB and I see in the log:
> ```
> anaconda: fs space: 18.42 GiB  needed: 19.58 GiB
> ```
> Then, I've deselected Whonix and it was enough to fit.
> 
> Strange thing is, the final partition layout is:
> - 1GB for /boot
> - 28GB for LUKS+LVM
> Looks fine for now, but when looking into LVM, there is:
>  - 3GB swap (wanted to be ~6GB, but installer capped it at 10% disk space)
>  - 21.66GB for thin pool, including root
>  - 4.3GB **unallocated**
> 
> I think the last point is manifestation of those differences, but I have no idea (yet) why it happened. Maybe it's related to space reclaim wizard? Have you tried erasing target flash drive first and the starting the installation?
> 
Here's the steps I took on this fresh attempt:
	1) Mounted proposed destination flash drive in Gnome Disks in a Linux
distro
	2) Selected any pre-existing partitions on this drive in Gnome Disks
and deleted them
	3) Visually verified that all space on proposed destination is now
reported as Unallocated.
	4) Booted into R4.0.1 installer and left settings at defaults.
	5) Inserted proposed destination flash drive and entered Installation
Destination screen
	6) Refreshed Disks to allow installer to recognize proposed destination
flash drive.
	7) 28.9 GiB is reported as Free in Installation Destination for said
drive, sdc. Select drive sdc and click on Done.
	8) Installation Options dialogue says:
	26.7 GiB required for install:
		19.39 GiB for Software
		7.39 GiB for Swap
	0 Free space available for use
	0 Free space unavailable but reclaimable from existing partitions
	You don't have enough space available to install Qubes.
	9) Reclaim Disk Space:
		Reclaimable Space on sdc = 0
		Free Space = 28.9 GiB
		(NB: No partitions are listed on this drive at this point, it's all
Free Space.)
		Installation requires a total of 24.32 GiB for system data.
	10) Click on Done or Reclaim, returned to Installation Summary screen
where I see the same 1.55 GiB shortfall error.

	Because you've mentioned a possible bug in disk space calculation, I'm
going to advise you of another issue that I was going to report
separately but may be part of the same problem. I've noticed during
manual partitioning in the Qubes Installer that there is a discrepancy
between the chosen total sizes of Swap, Root and /Boot partitions and
the reported Total Remaining Space. For example, in testing with a 51
GiB root and 3.52 GiB Swap I was losing an additional 10 GiB that was
unaccounted for. I think the size of the discrepancy may function as a
percentage because I believe it increased slightly on a later attempt
with a larger Root partition.

This is reproducible and occurs also when applying the partitions using
the Automatic Qubes Partitioning option. The discrepancy appears only
when adding the Root partition.

**Comment by marmarek** [comment]
I've found out the installer (blivet library to be specific) try to reserve 20% of thin pool size for data/metadata grow later. Here is [commit](https://github.com/storaged-project/blivet/commit/6326c2845f11) adding this functionality. If I understand correctly, this is to mitigate issues like #3243 .
If that's the case and indeed the space is correctly reserved, we may want to use this, instead of increasing default metadata size.
But the wrong free space reporting is an issue anyway.

**Comment by marmarek** [comment]
Besides the size reporting issue, it does appear that the default qubes installation require more space than early 4.0 release candidates, specifically at least 32GiB, not 32GB. This isn't really practical for 32 [drivemaker's GB](https://xkcd.com/394/) usb sticks that aren't even 32GB, but we should clear this in the requirements anyway.
