### ISSUE TITLE
"Copy to Other AppVM" freezes file manager when qrexec is not running in target VM

### ISSUE THREAD

**Issue by GWeck** [QubesOS/qubes-issues#5347]
**Qubes OS version**
Version 4.0.1 fully updated

**Affected component(s) or functionality**
File Copy to other AppVM

**Brief summary**
When issuing Copy to Other AppVM, the File Manager freezes aand does not allow any other operation, cannot even be closed, if the target VM does not run qrexec (in my case, a Windows 10 Standalone VM with QWT 4.0.1.3 where qrexec did not seem to start or communicate with dom0).

**To Reproduce**
Start such a dysfunctional VM and the try to copy a file to it.

**Expected behavior**
There sould be an error message indicationg that file copy is not possible.

**Actual behavior**
File manager is useless. Other windows in the same VM work normally.

**Solutions you've tried**
The only solution seems to be to restart the sending VM running the File manager.

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
Possibly #5332 and #3585

**Comment by GWeck** [comment]
The sending VM still hangs if `qvm-features qrexec` is set but no qrexec daemon is running in the receiving VM. If the receiving VM is restarted with `qvm-features qrexec` removed, the file manager of the sending VM is responsive again. (Tested with R4.1 and updated `fedora-30` and `dom0` as instructed; the sending VM was the `untrusted `fedora AppVM, the receiving was a linux-kali-5.2.0 HVM. without qrexec installed.)

**Comment by GWeck** [comment]
I tested now with R4.0, sending VM is an AppVM based on centos-7, receiving an AppVM based on a template running kali-5.4.0. The results were exactly the same.

@marmarek Can it be that the sender simply assumes that the receiver has qrexec running, if its `qvm-features` parameter is set? If the sender cannot reliably determine if qrexec is really running in the receiver, perhaps a timeout might help, showing the user that there is some trouble.

**Comment by marmarek** [comment]
The sender cannot reliably detect it beforehand, but with the fix operation should not hang anymore, it should fail quickly. Are you sure you have the fixed package installed (note, it's in current-testing repository) - qubes-core-dom0 4.0.49? Can you check how command line `qvm-copy` tool behaves in this case?

**Comment by GWeck** [comment]
For R4.0, I have qubes-core-dom0.x86_64 in version 4.0.49-1.fc25, for R4.1 in version 4.1.8-1.fc31.
The command line tool (tested in both R4.0 and R4.1) pops up the target selection window. When I enter the target VM name, the window disappears and nothing happens. Especially the prompt is not displayed again, but I can get it back by typing Ctrl-C.

**Comment by marmarek** [comment]
Was qrexec ever running in the target vm but stopped, or wasn't started at all? What do you have in relevant `/var/log/qubes/qrexec.<VMNAME>.log` for the target VM?

**Comment by GWeck** [comment]
For the new tests, qrexec was never started at all - I set the `qvm-features` parameter manually. In these cases, the log files contain the message:
`domain dead`
`cannot connect to qrexec agent: No such file or directory`.
I Repeated the test now with a Windows 10 AppVM that had qrexec running. If I kill the RPC agent there and try to copy a file to this VM, the sending file manager stays responsive and the log file contains:
`eintr`
`libvchan_is_eof`

**Comment by pwmarcz** [comment]
Regarding 4.1, apparently there is an issue with qrexec-daemon blocking the interaction, I'm on it.

From my testing, if `qrexec-agent` fails to start on the machine at all (and the `qrexec` feature is enabled), the offending machine will be killed within 60 seconds after startup anyway (with "Cannot to connect to qrexec agent"). The file copy operation hangs for these 60 seconds because it assumes that the machine is still starting (and is stuck on `admin.vm.Start` call).

@GWeck Is that what happens in your case? Is the machine killed within 60 seconds after start attempt, or does it keep running?

**Comment by GWeck** [comment]
The VM without `qrexec `is killed after the value of `qrexec_timeout` in `qvm_prefs` (default 60 s). The sending machine's file manager is then aborted, but this VM continues to run. As far as I remember, the R4.0 system behaves the same way, but I will test it again.

**Comment by pwmarcz** [comment]
Maybe we should generally implement file copy so that it doesn't hang the file manager (but maybe displays a window so that you know it's still running). There are cases like new machine startup, and copying a large file, and that would make the UX better for them.

**Comment by GWeck** [comment]
For R4.0, I have the following strange behaviour:

- After sending to a VM with `qvm-features qrexec` set, but no `qrexec `running, the sendig file manager hangs.
- After `qrexec `timeout, the receiving VM is killed, and the sending file manager still hangs.
- The receining VM is autumatically restarted immediately, and the sending file manager still hangs.
- If the receiving VM is shut down within the timeout window, it is not restarted again, and the sending file manager gets responsive again.

**Comment by GWeck** [comment]
With R4.0.3, the file manager no longer freezes if `qrexec `is set and the `qrexec `daemon was running at startup of the receiving VM.
- If then the daemon is killed, the sending file manager still does not freeze, but of course no file is transmitted.
- If the daemon is restarted, still no file copy is possible, but the sending file manager still does not freeze.

This was tested with Windows 10 as the receiver.

If at the start of the receiver, `qrexec `is set, but no daemon is started at all, the behaviour is quite different:
- The sending file manager hangs.
- After `qrexec `timeout, the receiving VM is killed, and the sending file manager still hangs.
- The receiving VM is automatically restarted immediately, and the sending file manager still hangs.
- This time, after `qrexec `timeout, the file manager gets responsive again.
- If the receiver is manually shut down before `qrexec `timeout, it is automatically restarted immediately, and the sending file manager still hangs and gets responsive again after the next `qrexec `timeout.

This is all quite puzzling for me, but I hope this description will help somewhat.

**Comment by DemiMarie** [comment]
This needs to be pushed to stable.  @marmarek ok?

**Comment by mikey0000** [comment]
Hi yeah I got this today after trying to move a file to windows VM

**Comment by Qubes-Beginner** [comment]
Hi,

I'm completely new here and Qubes OS is completely new to me too. I ended up here looking for my bug report. So sorry if I'm wrong here.

My Qubes OS 4.0 is up to date. But only with normal updates without experimental ones.

Whenever I try to copy files between VMs I get the error message:

Error while copying
...

no such file in directory

It doesn't seem to matter which VMs it is. The VMs are also running. I am not very well versed, but I read from the Discussion that it could have something to do with qrexec.

Could someone please explain to me as simply as possible what the problem could be and what I can do about it? Many thanks in advance.
