### ISSUE TITLE
VM won't start after no space left disk [urgent]

### ISSUE THREAD

**Issue by sucrecacao** [QubesOS/qubes-issues#5352]
**Qubes OS version**
Qubes  `R4.0

**Affected component(s) or functionality**
App VM 
Haven't try with template VM and standalone but I think all vm except dom0.

**Brief summary**
After getting the following warning : "WARNING! you are running out of disk space. 0.9% space left in pool lvm"
I tried to delete a few VM that where not used , did a `sudo fstrim / -v` but the warning was still here. 

Few day after I got the same warning with 0% space left.
Then I found [#3907](https://github.com/QubesOS/qubes-issues/issues/3907), did some of the command `sudo fsck -f /dev/mapper/qubes_dom0-vm--my--vm--private, then ran `sudo fstrim / ` and after than Qubes broke. 

Now it will start up but only dom0 will work. I can't open any VM.

**To Reproduce**
_Steps to reproduce the behavior:_
_1. Fill your space to full
_2. ran command mentionned previously in dom0

**Expected behavior**
 - Deleting VM would actually free space
 - Qubes having some kind of hard boundary to avoid this kind of bug in addition to the warning

**Actual behavior**
Qubes crash and appVM won't start

**Additional context**
( I do have a few deadline next week and would be really nice if I can recover before Monday, so any help is strongly appreciated 🙏🙏🙏  )

**Solutions you've tried**
Tryed solution of #3907, but had the opposite effect of what expected

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
[#3007](https://github.com/QubesOS/qubes-issues/issues/3907)

**Comment by marmarek** [comment]
you need to free some space. You can try using Qube Manager to remove some qubes (it will show you disk space used by each qube).

Alternatively, you can start with removing backup copies of qubes disk volumes: in dom0, as root `lvs`. Then look for volumes with `-back` at the end and remove them with `lvremove`. It will not free much space, but maybe enough to start some VM.

Anyway, a better place for such help would be a [qubes-users mailing list](https://www.qubes-os.org/support/#qubes-users).

**Comment by andrewdavidwong** [comment]
Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this does not appear to be suitable for `qubes-issues`. We ask that you please send this to the `qubes-users` [mailing list](https://www.qubes-os.org/support/) instead. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a brief comment explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.

**Comment by sucrecacao** [comment]
> you need to free some space. You can try using Qube Manager to remove some qubes (it will show you disk space used by each qube).
Yes I tried that but even after using Qubes manager to free some space, I still had the warning , and no more space was available.
> 
> Alternatively, you can start with removing backup copies of qubes disk volumes: in dom0, as root `lvs`. Then look for volumes with `-back` at the end and remove them with `lvremove`. It will not free much space, but maybe enough to start some VM.
Ill try, but I had a real probleme of qubes not updating free space after deleting appVM and data inside appVM

**Comment by brendanhoar** [comment]
@sucrecacao - please try running sudo fstrim -av inside the VMs as well as in dom0.

**Comment by sucrecacao** [comment]
@brendanhoar , @marmarek 
> @sucrecacao - please try running sudo fstrim -av inside the VMs as well as in dom0.

I tried with fstrim -av ( with and without the -a ) but didn't fix the issue.

I running twice, the first time it will trim 250 G from / and ~ 800M from /boot
the second time 0 and 0 

But if I restart the computer the fstrim will give me the same result ( 250 G from / and ~ 800M from /boot). 

I guess that mean fstrim does work as supposed ?
