### ISSUE TITLE
VM settings bugs

### ISSUE THREAD

**Issue by marmarta** [QubesOS/qubes-issues#5356]
**Qubes OS version**
R4.1

**Affected component(s) or functionality**
Tab order in Advanced tab of VM Settings is no longer consistent with logic.
Service adding via keyboard fails.
See: https://openqa.qubes-os.org/tests/4022

**Comment by andrewdavidwong** [comment]
Switching milestone to 4.0 based on the "earliest affected release" rule. If this is incorrect, please let me know.
