### ISSUE TITLE
Xrandr doesnt work on Debian-CLI-HVM

### ISSUE THREAD

**Issue by TNTBOMBOM** [QubesOS/qubes-issues#5363]
**Qubes OS version**
R4.0.1

**Affected component(s) or functionality**
Screen display/resolution

**Brief summary**
~Debian as a cli seems it doesnt detect the display resolution or so.~ X11 or so missing feature.

**To Reproduce**
Install Debian CD cli , try to change the screen resolution using xrandr

**Expected behavior**
xrandr should read and show the available display resolution which it can possibly shift to

**Actual behavior**
xrandr always return `Can't open display` 

**Screenshots**
![xrandr](https://user-images.githubusercontent.com/11895339/65886385-c6655600-e38b-11e9-8c5d-cf883522fea8.png)

**Additional context**
Tried to search online for many solutions for xrandr but none is working it always giving the same result.

**Comment by TNTBOMBOM** [comment]
This is missing feature in X11 seems to be , i tried the same thing with debian-cli+vbox and its not responding. 

@marmarek  since we cant config resolution from within nor resizing from out what could be done to fix the frame size?

Main issue:

#5350

**Comment by TNTBOMBOM** [comment]
I have found a workaround: 

if you press on the VM screen from the top and trying to pull it up it will just shift the VM from window to windows in the Workspace of the taskbar. So in order to fix that someone need to pull it up from the edge of the HVM: 

![resize2](https://user-images.githubusercontent.com/11895339/66045363-1cb0d100-e513-11e9-9cd7-a3926dce05f1.png)

![resize](https://user-images.githubusercontent.com/11895339/66045366-21758500-e513-11e9-8aea-d9adf15c193c.png)

Note: the only HVM frame option Fullscreen doesnt work.

**Comment by marmarek** [comment]
`xrandr`, as the name suggests needs to connect to X, so, it needs to be started from X, not a text console. There is nothing wrong here.
