### ISSUE TITLE
pulseaudio update breaks pulseaudio-qubes

### ISSUE THREAD

**Issue by sid-com** [QubesOS/qubes-issues#5364]
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
pulseaudio in debian-testing

**Brief summary**
pulseaudio 13 hit debian-testing and it breaks pulseaudio-qubes. Using the qubes-updater removed pulseaudio-qubes without warning. It currently is not possible to re-install. 

**Additional context**
I noticed two related commits in qubes-gui-agent-linux regarding pulsaudio dependency fixes in archlinux and rpm [1][2]. To me it looks like in debian it's just a matter of triggering the build pipeline, since the dependency of libpulse gets resolved in https://github.com/QubesOS/qubes-gui-agent-linux/blob/master/debian/rules

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
[1]
https://github.com/QubesOS/qubes-gui-agent-linux/commit/9f1bca8dbbac007066156f552b736b636678e390
[2]
https://github.com/QubesOS/qubes-gui-agent-linux/commit/445a9367f07a693e5bd0b31172083011510836c7

**Comment by marmarek** [comment]
> To me it looks like in debian it's just a matter of triggering the build pipeline

Yes.

Anyway, I'd expect this type of issues happening from time to time on Debian **testing**.

**Comment by sid-com** [comment]
@marmarek agreed.

**Comment by marmarek** [comment]
Due to unfortunate timing, this will happen only next week.

**Comment by marmarek** [comment]
Update built (https://github.com/QubesOS/updates-status/issues/1367)

**Comment by sid-com** [comment]
Sweet! Thanks @marmarek !
