### ISSUE TITLE
Persist display arrangement

### ISSUE THREAD

**Issue by ioleo** [QubesOS/qubes-issues#5365]
**The problem you're addressing (if any)**
When I connect a secondary display via HDMI I can choose to use it to extend the display area and in Display settings I can setup the display resolution for both screens (laptop built-in and external) and their relative arrangement. 

However, if I disconnect the HDMI cable and reconnect it, Qubes does not remember/recognize this screen and I have to reconfigure everything.

**Describe the solution you'd like**
I'd like Qubes to keep track of all possible display combinations I've used:
- built-in only
- built-in & external enabled
- built-in disabled & external enabled

And remember the resolution/arrangement settings for each combination and automatically switch (or have a prompt `You've used this combination of displays before. Do you want to switch to last known settings? yes/no`) to last known settings for this combination of displays.

**Where is the value to a user, and who might that user be?**
The value is time saved, expecially for users who (like me) often travel with their laptop and have it connected to external displays in various locations.

**Describe alternatives you've considered**
none

**Additional context**
There is a related issue (bug) of "clickable area". If plug in my external display and by default it goes into 1920x1080 resolution. When I change it to 3440x1440 for all working VMs (including dom0) the additional space is not "clickable". So in order to have my whole screen area accessible I need to:
* plug the external display
* reconfigure it the way I want it
* shutdown the system (as the bug also affects dom0)
* start up the system again

Perhaps if Qubes would recognize the display device and "by default" go to last known settings (3440x1440) the bug would not affect me.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
--

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
--

**Comment by marmarek** [comment]
Theoretically newer Xfce can handle it. It's going to be part of Qubes R4.1.
Related: https://github.com/QubesOS/qubes-issues/issues/5330

**Comment by donowop** [comment]
Xfce on Qubes R4.1 is still having this issue for me. I save my external monitor arrangement but it never saves after a reboot/suspend

**Comment by mgladdish** [comment]
+1. This is such a pain in the bum.

I have a switch to use the same keyboard, mouse and monitor across multiple machines and Qubes forgets the monitor layout every single time.

**Comment by marmarek** [comment]
Xfce has a setting to remember specific monitor layout(s), you just need to save profile you like - in "Display" settings, in the "Advanced" tab. I use it pretty often it works reliably.
