### ISSUE TITLE
How to add IME keyboard with Qubesos?

### ISSUE THREAD

**Issue by Cvrew** [QubesOS/qubes-issues#5366]
I want to add a keyboard for my country language.  And I have used IME so far and I want to use it.  How can I install it?

**Comment by andrewdavidwong** [comment]
Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this does not appear to be suitable for `qubes-issues`. We ask that you please send this to the `qubes-users` [mailing list](https://www.qubes-os.org/support/) instead. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a brief comment explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.
