### ISSUE TITLE
qvm-run "--pass-io" option interrupts other active RPC calls

### ISSUE THREAD

**Issue by Osndok** [QubesOS/qubes-issues#5368]
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
* qvm-ls
* qvm-run
* [maybe more, but I have not tested]

**Brief summary**
Using the `--pass-io` option on `qvm-run` seems to interrupt an unrelated (but contemporaneous) RPC call.

**Test Vector**
```shell
#!/bin/bash
#
# https://github.com/QubesOS/qubes-issues/issues/5368
#

# When using '--pass-io', qvm-run interrupts other RPC calls.
QVM_RUN_FLAGS="--pass-io"

#set -vx
set -eu

TEMP1=$(mktemp /tmp/qubesbug1.XXXXXXXX)
TEMP2=$(mktemp /tmp/qubesbug2.XXXXXXXX)

# TEMP1 - what we "expect" qvm-ls to return
qvm-ls --running --raw-list > "$TEMP1"

# NB: qvm-ls output is blocked (reading line-by-line)
qvm-ls --running --raw-list | while read VM
do
	[ "$VM" == dom0 ] || qvm-run $QVM_RUN_FLAGS "$VM" "echo executed in $VM"

	# TEMP2 - "should" be the same as TEMP1
	echo "$VM" >> $TEMP2
done

diff -wub "$TEMP1" "$TEMP2"
RET=$?

rm -f "$TEMP1" "$TEMP2"

exit "$RET"
```

**Expected behavior**
The execution of other RPC programs should not break the functionality of `qvm-ls`.

I would expect the output of the above test vector to output:
```
executed in alpha
executed in beta
executed in gamma
```

**Actual behavior**
The `qvm-ls` command output is truncated (only printing the first vm name).

The above script outputing:
```
executed in alpha
--- /tmp/qubesbug1.EQowyA5b	2019-10-03 15:08:20.194003122 -0500
+++ /tmp/qubesbug2.a9jWqsuJ	2019-10-03 15:08:20.627003125 -0500
@@ -1,13 +1,2 @@
 dom0
 alpha
-beta
-gamma
```

**Screenshots**
N/A

**Additional context**
dom0 kernel version 4.19.71-1
qubes-utils-libs-4.0.25-1.fc25.x86_64
qubes-utils-4.0.25-1.fc25.x86_64
qubes-core-admin-client-4.0.26-0.1.fc25.noarch
qubes-db-4.0.11-1.fc25.x86_64

**Solutions you've tried**
I was able to work around the issue by collecting all the data before executing `qvm-run`, but I wonder if this bug has further implications than a simple script.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
* https://dev.qubes-os.org/projects/core-admin-client/en/latest/manpages/qvm-run.html
* https://dev.qubes-os.org/projects/core-admin-client/en/latest/manpages/qvm-ls.html

**Loosely-possibly-maybe-related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
* #5105 
* #3810
* #3626
* #3122
* #663
* #508
* #535

**Comment by marmarek** [comment]
The issue you see is that `qvm-run --pass-io` reads data from stdin and send it into VM's process. Specifically in your case, it reads further `qvm-ls` output, so next `read` call don't get anything more to read, as it was already consumed by `qvm-run`.
You can prevent this by connecting `qvm-run` stdin with `/dev/null`, like this:
`qvm-run .... < /dev/null`.
In short - the issue is in your test script, not the actual qvm-run.

One could argue that process running within the VM in this case (`echo`) do not read anything from stdin, so `qvm-run` shouldn't either. But since it's running within a VM, it can be untrusted/compromised process and you should really not depend on its properties for the correctness of your dom0 tools.

**Comment by Osndok** [comment]
I think that you are confused about how pipes or subprocesses work, but in any case, you can replace the pipe with a named pipe (ala `done < <(qvm-ls --running --raw-list)`) and you get the same effect.

Cheers.

**Comment by Osndok** [comment]
I see that you are right, of course... now that I really think of it, I'm pretty sure that I have encountered this scripting hazard in the past! Thanks your your time, and sorry for the noise.
