### ISSUE TITLE
xenstore dirs in network backend are not cleaned up correctly

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#5369]
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
xen

**Brief summary**
Xenstore directories of network backends are not cleaned up after removing actual backend devices. Empty directories named after previously connected VM's IDs remains. After fair amount of VM startups, empty dirs trigger per-vm entries quota (1000 entries). User visible effect is failure to connect/start further VMs and `E2BIG` messages in network backend VM kernel log.

**To Reproduce**

Start and stop a VM connected to sys-firewall a lot of times. Happens during integration tests.

**Expected behavior**
Old entries are removed.

**Actual behavior**
Actual entries are removed, but containing directory stays.

**Additional context**

I vaguely remember a call to remove this directory done by the backend, failing because of missing permission (would have worked with network backend in dom0). I can't find it right now.

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

Similar to https://github.com/QubesOS/qubes-issues/issues/5343.

**Comment by marmarek** [comment]
Found it: there is xen-hotplug-cleanup script, [patched](https://github.com/QubesOS/qubes-vmm-xen/blob/xen-4.8/patch-vm-0001-hotplug-do-not-attempt-to-remove-containing-xenstore.patch) in our package to specifically remove this cleanup as it didn't worked because of lack of permissions. And the script is gone in upstream Xen 4.12, as it wasn't called by anything anymore (and the actual commit removing it is mine...).

**Comment by talex5** [comment]
Aha - this is the cause of the mirage-firewall crashes in https://github.com/mirage/qubes-mirage-firewall/issues/35 too. We have to monitor all these empty directories in case new interfaces get added to them, but each one costs us a XenStore watch and if you ask for too many then XenStore returns `E2BIG`.
