### ISSUE TITLE
wifi rmmod and insert wont work

### ISSUE THREAD

**Issue by lattice0** [QubesOS/qubes-issues#5373]
Qubes version: 4.0.1

The tutorial on Qubes wiki about using rmmod and insert to fix wifi won't work, but simply clicking the wifi icon and disabling wifi and enabling it does!

The wifi adapter is Qualcomm Atheros QCA6174

Maybe this should be included in the wiki.

Also, anyone knows a way to disable and enable the wifi like I did but with a script?

**Comment by andrewdavidwong** [comment]
> Maybe this should be included in the wiki.

In case you (or anyone else reading this) is not already aware, the documentation is a community effort, and everyone is welcome to contribute. (That's how things like this get updated!) So, if you'd like to get involved with the project, this is a great way to do it. You can read more about how to submit documentation changes here:

https://www.qubes-os.org/doc/doc-guidelines/

> Also, anyone knows a way to disable and enable the wifi like I did but with a script?

Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this question does not appear to be suitable for `qubes-issues`. We ask that you please send this to the `qubes-users` [mailing list](https://www.qubes-os.org/support/) instead. Thank you for your understanding.
