### ISSUE TITLE
i3 on Qubes experiencing persistent graphical glitching

### ISSUE THREAD

**Issue by LawAbidingCactus** [QubesOS/qubes-issues#5377]
**Qubes OS version**
R4.01 on a 6th generation X1 Carbon

**Affected component(s) or functionality**
i3, gui

**Brief summary**
i3 will start experiencing graphical glitches after waking up from s3 suspend. For example, elements (window indicators, etc) will disappear off i3bar. They will temporarily reappear when switching workspaces with $mod+\<number\>. Black bars will also appear over window titles, and parts of window contents won't be rendered correctly (blocks of white will appear where window contents should be). This only started happening after updating sometime within the past month (towards the beginning of September?). Using i3 after a cold boot will also resolve this behavior temporarily.

**To Reproduce**
Steps to reproduce:
1. Install i3 with `sudo qubes-dom0-update i3 i3-settings-qubes`
2. Login to i3 from lightdm
3. Put the computer into s3 sleep (`systemctl suspend`)
3. Wake the computer up

**Expected behavior**
Normal i3 behavior.

**Actual behavior**
See above.

**Screenshots**
![2019-10-06-212936_1920x1080_scrot](https://user-images.githubusercontent.com/8339492/66276260-e069d180-e880-11e9-9f1e-45d6689b02fc.png)

**Solutions you've tried**
1. Removing all customization
2. Performing a clean reinstall of Qubes OS

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
https://www.qubes-os.org/doc/i3/

**Comment by marmarek** [comment]
Looks similar to #3194, #4943, #5092. See if hints mentioned there help.

**Comment by LawAbidingCactus** [comment]
Hmm, the first issue appears to be about dual monitors with different refresh rates, but I tried the xorg settings mentioned anyway; they don't appear to have done anything. The second issue doesn't mention a solution, and the third pertains to nouveau drivers (this laptop doesn't have a discrete graphics card).

**Comment by marmarek** [comment]
you can also try this: https://github.com/QubesOS/qubes-issues/issues/5244#issuecomment-535494380
Do you see any errors related to display driver in dom0's `journalctl` or X server log?

**Comment by LawAbidingCactus** [comment]
There doesn't appear to be anything relevant in the output of `'journalctl -xe`.

The only error I can see in `/var/log/Xorg.0.log` is `[   202.984] (EE) intel(0): Failed to submit rendering commands (Bad address), disabling acceleration.`.

**Comment by marmarek** [comment]
> [ 202.984] (EE) intel(0): Failed to submit rendering commands (Bad address), disabling acceleration.

This looks very much related. And very similar to this thread: https://groups.google.com/forum/#!msg/qubes-users/0W3BXvKV1Ow/N-SMsWyRHgAJ

**Comment by LawAbidingCactus** [comment]
That worked! Some people on irc were experiencing similar issues, so I'll relay this along to them.
