### ISSUE TITLE
idle shutdown script shutdown a VM even if there are active vif+ interfaces

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#5378]
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
app-shutdown-idle

**Brief summary**
A VM providing network to other VMs should not be automatically powered off.

**To Reproduce**
_Steps to reproduce the behavior:_
1. Start a VM providing network to other VM (like VPN VM)
2. Do _not_ open any window within it.
3. Connect other VM to it.
4. 15 minutes later observe it shutting down, cutting network off some VMs.

**Expected behavior**
VM providing network to other active VMs remains active.

**Actual behavior**
It shutdown.

**Additional context**
Not sure if relevant: Fedora 30 template, qubes-idle-1.0.1-1.fc30.noarch.

**Comment by marmarta** [comment]
Just to make sure: does this VM actually have shutdown-idle service enabled?

**Comment by marmarek** [comment]
Yes, otherwise the VM wouldn't shutdown itself.
