### ISSUE TITLE
Domain fails to start because policy `x not in list`

### ISSUE THREAD

**Issue by creviera** [QubesOS/qubes-issues#5381]
**Qubes OS version**
Qubes release 4.0 (R4.0)
(current testing repository dom0 and all templates up to date as of 10/8/2019)

**Affected component(s) or functionality**
A named disposable VM that needs persistent attachment to a USB device

**Brief summary**
A VM that needs persistent attachment to a USB device will not start if the USB policy specifies `user=root` (and there seems to be an additional mysterious component to this issue that I have not figured out).

**To Reproduce**
Unfortunately I cannot consistently reproduce this bug, but here's what I do and it sometimes works and sometimes doesn't (Note: I actually run a provisioning script specific to our infrastructure and does a lot of extra stuff, so I extracted the pieces relevant to these steps. I understand this is a less-than-ideal STR but it's been a pretty gnarly bug for me so I wanted to share what I've discovered so far.)
1. Provision a named disposable VM that uses persistent USB attachment, e.g.
   ```
   qvm-create --class DispVM --template named-disp-vm-template --label red named-disp-vm
   ```
   (`named-disp-vm-template` can be based on any old TemplateVM, for more info see our [sls file](https://github.com/freedomofpress/securedrop-workstation/blob/b49c5f29d84de363b0c005b71667e4f9cb2d3a83/dom0/sd-export.sls)

2. Plug in a usb device and then run:
   ```
   qvm-usb attach --persistent named-disp-vm sys-usb:4-2
   ```
   (replace `sys-usb:4-2` with the device name for the usb device that you just plugged in, to get this run `qvm-usb ls` from Dom0)

3. Now in Dom0 run:
   ```
   qvm-start named-disp-vm
   ```

**Expected behavior**
I would expect `named-disp-vm` to start and for Qubes to immediately attach the usb device specified in step 2 above.

**Actual behavior**
A Qubes popup error notification says `Domain sd-export-usb has failed to start: list.remove(x): x not in list` (where `sd-export-usb` is my version of `named-disp-vm`) and I see a stacktrace in the Dom0 logs when I run `journalctl -ef`:

```console
Oct 08 12:45:15 dom0 qubesd[2604]: unhandled exception while calling src=b'dom0' meth=b'admin.vm.Start' dest=b'sd-export-usb' arg=b'' len(untrusted_payload)=0
Oct 08 12:45:15 dom0 qubesd[2604]: Traceback (most recent call last):
Oct 08 12:45:15 dom0 qubesd[2604]:   File "/usr/lib/python3.5/site-packages/qubes/api/__init__.py", line 266, in respond
Oct 08 12:45:15 dom0 qubesd[2604]:     untrusted_payload=untrusted_payload)
Oct 08 12:45:15 dom0 qubesd[2604]:   File "/usr/lib64/python3.5/asyncio/futures.py", line 381, in __iter__
Oct 08 12:45:15 dom0 qubesd[2604]:     yield self  # This tells Task to wait for completion.
Oct 08 12:45:15 dom0 qubesd[2604]:   File "/usr/lib64/python3.5/asyncio/tasks.py", line 310, in _wakeup
Oct 08 12:45:15 dom0 qubesd[2604]:     future.result()
Oct 08 12:45:15 dom0 qubesd[2604]:   File "/usr/lib64/python3.5/asyncio/futures.py", line 294, in result
Oct 08 12:45:15 dom0 qubesd[2604]:     raise self._exception
Oct 08 12:45:15 dom0 qubesd[2604]:   File "/usr/lib64/python3.5/asyncio/tasks.py", line 240, in _step
Oct 08 12:45:15 dom0 qubesd[2604]:     result = coro.send(None)
Oct 08 12:45:15 dom0 qubesd[2604]:   File "/usr/lib/python3.5/site-packages/qubes/api/admin.py", line 834, in vm_start
Oct 08 12:45:15 dom0 qubesd[2604]:     yield from self.dest.start()
Oct 08 12:45:15 dom0 qubesd[2604]:   File "/usr/lib/python3.5/site-packages/qubes/vm/dispvm.py", line 220, in start
Oct 08 12:45:15 dom0 qubesd[2604]:     yield from super(DispVM, self).start(**kwargs)
Oct 08 12:45:15 dom0 qubesd[2604]:   File "/usr/lib/python3.5/site-packages/qubes/vm/qubesvm.py", line 1071, in start
Oct 08 12:45:15 dom0 qubesd[2604]:     start_guid=start_guid)
Oct 08 12:45:15 dom0 qubesd[2604]:   File "/usr/lib/python3.5/site-packages/qubes/events.py", line 236, in fire_event_async
Oct 08 12:45:15 dom0 qubesd[2604]:     effect = task.result()
Oct 08 12:45:15 dom0 qubesd[2604]:   File "/usr/lib64/python3.5/asyncio/futures.py", line 294, in result
Oct 08 12:45:15 dom0 qubesd[2604]:     raise self._exception
Oct 08 12:45:15 dom0 qubesd[2604]:   File "/usr/lib64/python3.5/asyncio/tasks.py", line 240, in _step
Oct 08 12:45:15 dom0 qubesd[2604]:     result = coro.send(None)
Oct 08 12:45:15 dom0 qubesd[2604]:   File "/usr/lib/python3.5/site-packages/qubesusbproxy/core3ext.py", line 323, in on_domain_start
Oct 08 12:45:15 dom0 qubesd[2604]:     yield from self.on_device_attach_usb(vm, '', device, options={})
Oct 08 12:45:15 dom0 qubesd[2604]:   File "/usr/lib/python3.5/site-packages/qubesusbproxy/core3ext.py", line 286, in on_device_attach_usb
Oct 08 12:45:15 dom0 qubesd[2604]:     device.backend_domain.name))
Oct 08 12:45:15 dom0 qubesd[2604]: ValueError: list.remove(x): x not in list
```

This stacktrace points to [this line of code](https://github.com/QubesOS/qubes-app-linux-usb-proxy/blob/95374267c01bba9f4e8c2d4075823c2024cfe179/qubesusbproxy/core3ext.py#L284) in qubesusbproxy/core3ext.py causing the `x not in list` error:
```py
policy.remove(
    '{} {} allow\n'.format(vm.name,
    device.backend_domain.name))
```

**Additional context**
If you review the code in the `on_device_attach_usb` method, you can see that `policy` mentioned in the code above is the list containing the lines returned by `readlines` for the policy file (in my case, the file is `/etc/qubes-rpc/policy/qubes.USB+4-2`). On my  system, I see `/etc/qubes-rpc/policy/qubes.USB+4-2` that contains many attempts to set the device policy, but more importantly that `user=root`:

```
named-disp-vm sys-usb allow,user=root
named-disp-vm sys-usb allow,user=root
named-disp-vm sys-usb allow,user=root
named-disp-vm sys-usb allow,user=root
...
```

You can also see here where root is specified: https://github.com/QubesOS/qubes-app-linux-usb-proxy/blob/95374267c01bba9f4e8c2d4075823c2024cfe179/qubesusbproxy/core3ext.py#L235-L237

The bug seems to be that Qubes tries to remove the policy `named-disp-vm sys-usb allow` instead of `named-disp-vm sys-usb allow,user=root`. 

One possible fix is to remove the policy matching `named-disp-vm sys-usb allow,user=root\n` instead of `named-disp-vm sys-usb allow\n`.

The strange thing is that I only run into this error _some of the time_ but when looking at this code pointed to by the stacktrace it looks like I should be hitting this error every time.

**Solutions I've tried**
This does not consistently fix the problem (it might have been a coincidence when it seemed to fix the issue once):

1. Kill qui-devices per https://github.com/QubesOS/qubes-issues/issues/4878#issuecomment-472175527

2. Re-provision the named disposable VM that uses persistent USB attachment, e.g.
   ```
   qvm-create --class DispVM --template named-disp-vm-template --label red named-disp-vm
   ```
   (`named-disp-vm-template` can be based on any old TemplateVM, for more info see our [sls file](https://github.com/freedomofpress/securedrop-workstation/blob/b49c5f29d84de363b0c005b71667e4f9cb2d3a83/dom0/sd-export.sls)

3. Plug in a usb device and then run:
   ```
   qvm-usb attach --persistent named-disp-vm sys-usb:4-2
   ```
   (replace `sys-usb:4-2` with the device name for the usb device that you just plugged in, to get this run `qvm-usb ls` from Dom0)

4. Now in Dom0 run:
   ```
   qvm-start named-disp-vm
   ```

**Relevant docs**
* https://www.qubes-os.org/doc/device-handling/#attaching-devices

   In these docs, it says: 

   > --persistent - attach device on targetVM-boot. If the device is unavailable (physically missing or sourceVM not started), booting the targetVM fails.

   We use this persistent flag since we want to attach the device on targetVM boot.

**Related non-duplicate issues**
* https://github.com/QubesOS/qubes-issues/issues/4849

   In this issue, someone is seeing the same stacktrace as me: 
 https://github.com/QubesOS/qubes-issues/issues/4849#issuecomment-473663486

**Comment by marmarek** [comment]
You hit this issue only sometimes, because there is also another case if the policy file wasn't there initially. Then, it's removed instead of just removing a single line.

**Comment by creviera** [comment]
Thanks @marmarek! I tested your fix and see the policy file written to disk and removed during VM startup. Fixes the issue! :tada:
