### ISSUE TITLE
Black screen after Xen output when attempting to install

### ISSUE THREAD

**Issue by AshleyYakeley** [QubesOS/qubes-issues#5383]
**Qubes OS version**
R4.0.1

**Affected component(s) or functionality**
Installer

**Brief summary**
I cannot install Qubes either through USB boot or UEFI boot. I get a black screen after Xen output.

**To Reproduce**

***Media Preparation***
1. Write installation ISO to USB drive
2. Mount partition 2 "ANACONDA"
3. Edit `EFI/BOOT/BOOTX64.cfg`
4. Under `[qubes-verbose]`, comment out `noexitboot=1` and `mapbs=1` lines.

***Method 1***
1. Reboot, in BIOS boot device menu, select USB
2. Select "Install Qubes R4.0"

Result: short text output, then black screen with flashing white text cursor.

***Method 2***
1. Reboot, in BIOS boot device menu, select USB
2. Select "Troubleshooting"
3. Select the installation choice for graphics issues.

Result: long text output, then black screen.

***Method 3***
1. Reboot, in BIOS boot device menu, select UEFI

Result: long text output, then black screen.

***Method 4***
1. Reboot, in BIOS boot device menu, select UEFI partition 2

Result: long text output, then black screen.

Screenshots for method 4:
![20191010_215719](https://user-images.githubusercontent.com/5609617/66628612-2b9f1f80-ebb4-11e9-805f-eb1c756fdad7.jpg)
![vlcsnap-2019-10-10-22h50m05s471](https://user-images.githubusercontent.com/5609617/66628635-39ed3b80-ebb4-11e9-951c-23f3c99782ca.png)

**Additional context**
Motherboard: ASRock X570M Pro4 Micro ATX AM4
Processor: AMD Ryzen 7 3700X
Video card: AMD Radeon HD 5450
(I have an NVidia card as well, but physically pulled it out to avoid NVidia issues.)

**Solutions you've tried**
First tried without editing `EFI/BOOT/BOOTX64.cfg`.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
https://www.qubes-os.org/hcl/ -- seems to be uselessly out-of-date
https://www.qubes-os.org/doc/uefi-troubleshooting/ -- followed advice to comment out lines

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
#5165 -- similar

**Comment by AshleyYakeley** [comment]
Looks like I might not have caught the top of the Xen output in my screenshot. Let me know if you want that.

**Comment by AshleyYakeley** [comment]
I found a work-around for this. (Note this is with 4.0.2-rc1, I haven't tried it with 4.0.1. Also I had both video cards installed.)

1. Write installation ISO to USB drive
1. Mount partition 2 "ANACONDA"
1. Edit EFI/BOOT/BOOTX64.cfg
1. Under `[global]`, change `default=qubes-verbose` to `default=qubes`
1. Reboot, in BIOS boot device menu, select UEFI partition 2

Installation can then proceed.

**Comment by marmarek** [comment]
Could you try a different change? Instead of setting `default=qubes`, keep it as `default=qubes-verbose`, but comment out `noexitboot=1` line in `[qubes-verbose]` section.

**Comment by AshleyYakeley** [comment]
But leave in the `mapbs=1` line?

**Comment by marmarek** [comment]
You can try both versions, but I don't think commenting it out would improve things.

**Comment by AshleyYakeley** [comment]
So as you can see from my original report, I already tried it with commenting out both lines.

In any case, I tried it commenting out `noexitboot=1` but leaving `mapbs=1`. The same problem happened, it got to a black screen and I was unable to proceed with installation.

**Comment by maximilize** [comment]
When trying to boot I get the same error, the screen stays black. Tested with Matebook X Pro 2020 with i7 10th gen, Geforce MX250.

It happens with the installer as well as a working qubes installation (assembled the SSD of another laptop).

What I tried so far:
- Followed this suggestions: https://www.qubes-os.org/doc/uefi-troubleshooting/
- Disabled the nouveau driver (`modprobe.blacklist=nouveau rd.driver.blacklist=nouveau`)
- Removed `noexitboot=1` and `mapbs=1`
- Set `iommu=no-igfx`
- Set `acpi=off`

When using the flags `xen=current,keep guest_loglvl=all` it takes ages to render the screen when new line is printed. However, after a while it ends up at something which looks like a text-based installer with the notice `* shell is available on TTY2`. Changing to TTY2 is not possible. Also the system freezes completely after a while (the casplock and fn key light does not turn on/off).

On my Matebook X Pro 2018 Qubes is working just fine after disabling nouveau, noexitboot and mapbs.

Related issues I found: #5788, #5165

**Comment by Germayn** [comment]
> 
> 
> I found a work-around for this. (Note this is with 4.0.2-rc1, I haven't tried it with 4.0.1. Also I had both video cards installed.)
> 
>     1. Write installation ISO to USB drive
> 
>     2. Mount partition 2 "ANACONDA"
> 
>     3. Edit EFI/BOOT/BOOTX64.cfg
> 
>     4. Under `[global]`, change `default=qubes-verbose` to `default=qubes`
> 
>     5. Reboot, in BIOS boot device menu, select UEFI partition 2
> 
> 
> Installation can then proceed.

I had the same issue, and your work-around helped as well.

I tracked down the problem to be the `options=console=vga` parameter.

So, instead of your purposed work-around change
`options=console=vga` to `options=console=none`

inside the `[qubes-verbose]` block.

After that everyhing worked as expected.

**Comment by maximilize** [comment]
Since `noexitboot=1` and `mapbs=1` is causing also issues on some systems, I think it's more safe to either document all solutions, or to stick with changing the `default` boot options.

**Comment by Germayn** [comment]
> 
> 
> Since `noexitboot=1` and `mapbs=1` is causing also issues on some systems, I think it's more safe to either document all solutions, or to stick with changing the `default` boot options.

I agree !
Since I don't know the impact (downside?) of disabling `noexitboot` and `mapbs`, I sticked with having them enabled since they were no issue for me.

So I would suggest to better document all solutions - unless somebody could maybe explain the impact so we could decide whether to document all solutions (also in which order one should try them) or to just stick with the easy fix by changing the `defaults` option.
