### ISSUE TITLE
Appmenus: hierarchical submenus

### ISSUE THREAD

**Issue by iamahuman** [QubesOS/qubes-issues#5386]
**The problem you're addressing (if any)**
Trying to make navigating app menus where there are many VMs or a lot of apps in a VM easier.

**Describe the solution you'd like**
I'm aware that there may not be a clear solution especially if we have to work above XDG. The most intuitive way I can think of right now would be to co-operate with some third-party xfce4/xdg/whatever menu editor, synchronizing changes back to `${XDG_DATA_HOME:-$HOME/.local}/qubes-appmenus` or something in between the lines.

**Where is the value to a user, and who might that user be?**
A user might save some time navigating Application menus or having to open up a terminal and type `qvm-run --service X... Y...`.
For users who have around 40+ Qubes (that are probably backed up regularly so that hiding them via setting the internal feature would be inconvenient) or a VM with a lot of subcategories, organizing entries into sub-menus would be a useful feature.

**Describe alternatives you've considered**
Another option users may take is to manage their own desktop menus, but these would need manual synchronization every time an app is added or removed.

**Additional context**
Not applicable.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
- https://www.qubes-os.org/doc/managing-appvm-shortcuts/
- http://www.freedesktop.org/wiki/Specifications/menu-spec
- https://wiki.xfce.org/howto/customize-menu

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
Not aware of any so far.

**Comment by andrewdavidwong** [comment]
Related: #2646, #4005, #5037, #5255

**Comment by ninavizz** [comment]
IMHO this would add a significant usability boost, to the App menu. It's cognitively exhausting having to navigate so many redundant words. After a while, one can become used to it—but for new users, especially, it's incredibly daunting.

**Comment by ninavizz** [comment]
Will be resolved with #6665, which is the solution being developed from the design and user research work in #5677

**Comment by UndeadDevel** [comment]
This should get an "Affects 4.1" label, as it relates to the old App Menu, while there is already the subsuming #6679 and #6680 for the new App Menu.
