### ISSUE TITLE
OpenBSD HVM freezes when running Chromium

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#5388]
**Qubes OS version**
`Qubes release 4.0 (R4.0)`

**Affected component(s) or functionality**
HVM emulated graphics

**Brief summary**
Running a graphics-intensive application (Chromium) in an HVM causes it to hang and not respond to `xl shutdown -Fw`.  This makes me think the stubdom freezes.

**To Reproduce**
1. Install OpenBSD in an HVM.
2. Enable `xenodm` with `rcctl`.
3. Install `chromium` with `pkg_add`
4. Run `chrome`.

**Expected behavior**
No freeze

**Actual behavior**
VM froze and had to be destroyed from dom0.

**Screenshots**
I didn’t get any.

**Additional context**
This could be an out of memory error in the stubdom.

**Solutions you've tried**
Use X11 forwarding over SSH instead

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
None

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
#4551

**Comment by marmarek** [comment]
Do you see any crash within stubdomain? See `/var/log/xen/console/guest-VMNAME-dm.log`

**Comment by DemiMarie** [comment]
@marmarek I see no evidence of a stubdom crash.

**Comment by esote** [comment]
@DemiMarie For what it's worth, I am able to run chromium in an OpenBSD HVM with 400 MB memory and 2 vCPUs. If I lower the memory to 200 MB it still runs, just slowly (and chromium crashed eventually).

![openbsd-chromium](https://user-images.githubusercontent.com/25505632/72403121-ada06680-3716-11ea-9dcd-43a414a4f6c1.png)

**Comment by irelativism** [comment]
o/ qubes, you should consider the HyperbolaBSD project once its finished, a openbsd kernel and userspace hard fork, with the focus in modularity and freedom, so by consequence security and privacy, also all mergerd works will be licensed under GPLv3. other efforts will be included like features from drangonfly, Gentoohardenedbsd debiankfreebsd, pacmanbsd and libertybsd scripts. hyperbola.info for more info. Cheers.

**Comment by DemiMarie** [comment]
Closing as I suspect this was an OpenBSD issue.
