### ISSUE TITLE
IPv6 doesn’t work in OpenBSD HVM

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#5389]
**Qubes OS version**
`Qubes release 4.0 (R4.0)`

**Affected component(s) or functionality**
Networking

**Brief summary**
IPv6 doesn’t work in an OpenBSD HVM, probably because NDP traffic is blocked.

**To Reproduce**
1. Install OpenBSD in an HVM
2. Enable IPv6 for the HVM
3. Try to set up IPv6 for the HVM
4. “Network is unreachable” error from OpenBSD

**Expected behavior**
IPv6 works

**Actual behavior**
IPv6 fails

**Screenshots**
N/A

**Additional context**
The MAC address of `fe:ff:ff:ff:ff:ff` for the peer could be a problem, too.  OpenBSD correctly detects that it is running on Xen, and uses Xen paravirtualized networking.  IPv4 works, but must be manually configured.

**Solutions you've tried**
Manually adding NDP entries

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
OpenBSD man pages

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
#4551

**Comment by marmarek** [comment]
Have you enabled IPv6 according to https://www.qubes-os.org/doc/networking/#ipv6 ? Make sure you configure addresses according to those listed by `qvm-prefs` (there is no autoconfiguration in place). There is a firewall that will reject any other source address (anti-spoofing rules).

**Comment by DemiMarie** [comment]
@marmarek I have, but was not able to send any packets.

**Comment by DemiMarie** [comment]
I found a workaround: manually inserting NDP entries in a network hook.  This works reliably.  I will make a PR soon.

**Comment by irelativism** [comment]
o/ qubes, you should consider the HyperbolaBSD project once its finished, a openbsd kernel and userspace hard fork, with the focus in modularity and freedom, so by consequence security and privacy, also all mergerd works will be licensed under GPLv3. other efforts will be included like features from drangonfly, Gentoohardenedbsd debiankfreebsd, pacmanbsd and libertybsd scripts. hyperbola.info for more info. Cheers.
