### ISSUE TITLE
I want to add a new type of keyboard with QubesOS.

### ISSUE THREAD

**Issue by Cvrew** [QubesOS/qubes-issues#5390]
I want to add a keyboard for my country language with QubesOS. What I want to add is the IME keyboard used in Windows. How can I add and use it?

**Comment by andrewdavidwong** [comment]
Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this does not appear to be suitable for `qubes-issues`. We ask that you please send this to the `qubes-users` [mailing list](https://www.qubes-os.org/support/) instead. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a brief comment explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.
