### ISSUE TITLE
Razer Blade Stealth 2016 does not properly resume from suspend (screen stays dark)

### ISSUE THREAD

**Issue by lattice0** [QubesOS/qubes-issues#5398]
**Qubes OS version**
4.0.1

**Affected component(s) or functionality**
closing laptop lid

**Brief summary**
When I close and reopen it, the keyboard ligths again, but the screen wont light up.
I tried kernels 4.14.74-1, 4.19.79-1 and 5.something, none of them worked.
When I used Ubuntu in this laptop, sleep always worked. I also tried Fedora 30 on a live USB and did the sleep test and it worked! 
Here's my HCL report: https://groups.google.com/forum/#!topic/qubes-users/PalZ-1inxnA, im using a Razer Blade Stealth 2016, which has a pretty nice compatiblity with Qubes, the only problems being sleep function and wifi dying sometimes, but I think if I update sys-net's drivers it will work (even the touchscreen worked out of the box).

**To Reproduce**
_Steps to reproduce the behavior:_
Click on the sleep button or close the notebook lid
Open the lid again
Keyboard lights up but screen wont appear, even if I press keyboard buttons or power button. Need to reboot.

**Expected behavior**
Screen simply appears and I can continue working

I love Qubes very much and this is a very important feature for me to continue working with it, so it'd be really nice if you guys could help me finding the root of the problem. I tried the qubes-users forum but nobody was able to help. I even read some things about laptop lids there but they weren't the same issue as mine.

Thank you sou much and keep up with the good work!

**Comment by 1nd0** [comment]
I have a similar issue with my late 2017 Razer blade stealth. It will wake up for about a minute but will then go back to sleep. Continues to repeat this until reboot.

**Comment by lucaszanella** [comment]
@1nd0 any news on this?

I have provided more details on https://github.com/QubesOS/qubes-issues/issues/5555

**Comment by andrewdavidwong** [comment]
Is this still a problem in 4.1?
