### ISSUE TITLE
LVM thin pool storage import assumes zeroing mode is set

### ISSUE THREAD

**Issue by iamahuman** [QubesOS/qubes-issues#5402]
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
- Qubes LVM Thin Pool storage pool import code (https://github.com/QubesOS/qubes-core-admin/blob/d2f4b5d694642f2b776441d458aaae5bb80945a2/qubes/storage/lvm.py#L520)

**Brief summary**
`dd conv=sparse` as used by the importing function seeks instead of explicitly punching holes in order to create a sparse output, leaving partial blocks uninitialized when zeroing newly provisioned blocks is disabled in the pool.

**To Reproduce**
1. Create a LVM thin provisioned pool backed by PVs that do not return all zeroes for discarded blocks (e.g. dm-crypt)
2. Create a lvm backed pool based on such pool if it doesn't already exist.
3. In dom0, run `lvchange -Zn VG/Pool` where VG/Pool is the path to LV used by Qubes.
4. Do `qvm-create --root-copy-from ...`, `qvm-volume import ...` or whatever.

**Expected behavior**
The contents of the source and the volume shall be equal, byte-to-byte.

**Actual behavior**
Some regions that were originally zero in the source file is filled with garbage data or otherwise non-zero bytes from the discarded sectors of the underlying PV.

**Screenshots**
Not applicable.

**Additional context**
I was doing a manual setup, and I was trying turning off the zeroing mode to see if it helps in performance.

**Solutions you've tried**
Enable zeroing back (-Zy) for now. I suppose this bug could be fixed by making the `dd` copy block size equal to the backing LV's extent and enabling `fullblock` so that we can ensure each provisioned block is properly zeroed, but I haven't tested this yet. `cp --sparse=...` _might_ also work, but I have't checked if it properly detects extent sizes of such block devices.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
- https://dev.qubes-os.org/projects/core-admin/en/latest/qubes-storage.html (Note that [the one](https://www.qubes-os.org/doc/storage-pools/) in the Qubes documentation website is for R3.x)

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
- TBD

**Comment by iamahuman** [comment]
For setups where LVM extents are smaller than the minimum discard sector size of underlying device, `-Zn` may also help extend lifetime of SSDs (in runtime of course, import process do need to zero the entire extent anyway)

**Comment by marmarek** [comment]
Setting `-Zn` sounds like a **VERY BAD IDEA** for security of your system. It could allow a VM to read data possibly owned previously by a different VM (think of creating empty private volume, extending existing, and probably more). Rather than finding all the places where LVM's own zeroing code would need to be re-implemented elsewhere, better use the feature designed exactly to do that. In fact, finding such dangerous settings is one of the reason why we consider limiting dom0 access drastically.

**Comment by poige** [comment]
> Setting `-Zn` sounds like a **VERY BAD IDEA** for security of your system. It could allow

Exactly the opposite. If some security targeted system depends on a feature of zeroing which can be turned off, this is the "VERY BAD-BAD" design principle.

**Comment by marmarek** [comment]
That's flawed reasoning. An open source system (that doesn't cripple your rights coming with this principle) allows you to modify it. You can always find a way to break it. The fact that you can modify everything doesn't mean you should.
