### ISSUE TITLE
Allow Qubes Manager to run inside a VM

### ISSUE THREAD

**Issue by fepitre** [QubesOS/qubes-issues#5403]
For GuiVM or more generally, any AdminVM, we need to be able to run Qubes Manager inside a VM. First try, result of failing due to https://github.com/QubesOS/qubes-manager/blob/12481fd5610a3e212f495ecda2fd7eed4addaf76/qubesmanager/restore.py#L29 which is due to python3 core-admin missing package under any VM. As core-admin is only a dom0 package, it should not be required.

TODO:
- [x] Remove dom0 package python dependency
- [x] Reduce calls to other qubes where current VM is not allowed to manage (https://gist.github.com/marmarek/b36478ac9e4c07b4a30ac49a11948d2a)
- [x] Determine all the minimal needed RPC (first ones are included in https://github.com/QubesOS/qubes-mgmt-salt-dom0-virtual-machines/pull/18)

Related PR for build: https://github.com/QubesOS/qubes-manager/pull/206
Related issues:
https://github.com/QubesOS/qubes-issues/issues/833
https://github.com/QubesOS/qubes-issues/issues/4186

**Comment by fepitre** [comment]
Here too: https://github.com/QubesOS/qubes-manager/blob/0c1072320508483a646e78fa772c1fcec35155be/qubesmanager/block.py#L25

**Comment by marmarek** [comment]
With recent commits (already in master) it kind of works in a VM. But since qrexec connection setup is slow, startup takes several minutes :(

**Comment by fepitre** [comment]
I will test it too. But yes, it's like running qvm-ls in cli. It's very long...

**Comment by fepitre** [comment]
@marmarek: I updated the description.

**Comment by marmarek** [comment]
Done.
