### ISSUE TITLE
ISO verification instructions fail on GPG 2.2.17

### ISSUE THREAD

**Issue by NieDzejkob** [QubesOS/qubes-issues#5404]
**Brief summary**
When trying to verify the signature on the QubesOS installer ISO, using a "stock" install of GnuPG 2.2.17, the signature
```
sig          DDFA1A3E36879494 2017-03-08  Qubes Master Signing Key
```
is not shown.

**To Reproduce**
1. Make sure your GnuPG is version 2.2.17 (the latest). Also, make sure your distribution doesn't modify GnuPG to fix this - I can reproduce this on Debian, but not on Arch Linux.
2. If desired, create a separate testing user to make sure any previously issued GPG commands didn't effect this issue.
3. As per [the guide](https://www.qubes-os.org/security/verifying-signatures/), fetch the master key:
```
gpg --fetch-keys https://keys.qubes-os.org/keys/qubes-master-signing-key.asc
```
4. Either edit the key to set the trust or don't -- this makes no difference/
5. Fetch the release signing key:
```
gpg --fetch-keys https://keys.qubes-os.org/keys/qubes-release-4-signing-key.asc
```
6. List the signatures on the key:
```
gpg --list-sigs "Qubes OS Release 4 Signing Key"
```

**Expected behavior**
The release key is shown as signed by the master key:
```
pub   rsa4096 2017-03-06 [SC]
      5817A43B283DE5A9181A522E1848792F9E2795E9
uid           [ unknown] Qubes OS Release 4 Signing Key
sig 3        1848792F9E2795E9 2017-03-06  Qubes OS Release 4 Signing Key
sig          DDFA1A3E36879494 2017-03-08  Qubes Master Signing Key
```

**Actual behavior**
The release key is shown as only self-signed:
```
pub   rsa4096 2017-03-06 [SC]
      5817A43B283DE5A9181A522E1848792F9E2795E9
uid           [ unknown] Qubes OS Release 4 Signing Key
sig 3        1848792F9E2795E9 2017-03-06  Qubes OS Release 4 Signing Key
```

**Additional context**
I first [asked about this](https://security.stackexchange.com/questions/219844/why-is-debian-not-showing-the-gpg-signatures-on-keys-that-arch-linux-is) on Security.StackExchange. After sharing the question to social media, I got pointed to [the release notes of GnuPG 2.2.17](https://lwn.net/Articles/793288/). As the changelog explains, GPG only retains self-sigs by default when downloading from a keyserver.

**Solutions you've tried**
Adding this line to `~/.gnupg/gpg.conf` fixes the issue:

```
keyserver-options no-self-sigs-only,no-import-clean
```

Finding this seems to have been non-trivial, though. I'm not sure if it's a proper solution or just a workaround, but either way, it seems like an update of the verification guide is warranted.

**Comment by andrewdavidwong** [comment]
Thanks for bringing this to our attention!

> Finding this seems to have been non-trivial, though.

I agree that editing the config file is too much for this introductory guide. Some users already struggle with this procedure as it is.

Instead, I tested the process with `gpg` rather than `gpg2`. Thankfully, everything still works correctly with `gpg`, so I'm adding a note that we strongly encourage using `gpg` rather than `gpg2` for this procedure, due to the special steps required for `gpg2` to work properly (with a link to this issue).

**Comment by marmarek** [comment]
I think `gpg` is not maintained anymore and recommending using it to download something from the internet is a bad idea.
But you don't need to edit configuration file, there is `--keyserver-options no-self-sigs-only,no-import-clean` command line switch that should have the same effect.

**Comment by NieDzejkob** [comment]
It might be worth noting that Debian- and Arch-based distros don't seem to be packaging both GPG versions.

**Comment by andrewdavidwong** [comment]
> I think `gpg` is not maintained anymore and recommending using it to download something from the internet is a bad idea.

I'm surprised! If there were security concerns about its use, I'd think it would be pulled from package repos or at least include a warning.

> But you don't need to edit configuration file, there is `--keyserver-options no-self-sigs-only,no-import-clean` command line switch that should have the same effect.

Ok, I'll update the document to recommend this instead.
