### ISSUE TITLE
xfce4-power-manager segfaults when I right click on it

### ISSUE THREAD

**Issue by meithecatte** [QubesOS/qubes-issues#5406]
**Qubes OS version**
Qubes release 4.0 (R4.0)

**Affected component(s) or functionality**
The power manager in the system tray

**Brief summary**
When the power manager icon in the system tray is right clicked, the icon disappears. A segmentation fault is logged in dmesg.

**To Reproduce**
1. Open a dom0 terminal, run `sudo dmesg -w`.
2. Hover your mouse over the power manager icon in the system tray.
3. Right-click. The power manager menu will be briefly shown.

**Expected behavior**
The power manager menu stays on screen, the program does not crash.

**Actual behavior**
After much less than a second, the menu disappears, and so does the icon. The terminal shows the following:

```
[ 3535.637293] xfce4-power-man[13296]: segfault at 0 ip 00007ec372e780f9 sp 00007ffc16503e00 error 4 in libgobject-2.0.so.0.5000.3[7ec372e64000+50000]
[ 3535.637302] Code: 5f ff ff 4c 89 ef e8 56 40 01 00 8b 35 74 d1 23 00 31 c9 31 d2 4c 89 e7 e8 f4 5e ff ff b8 ff ff ff ff f0 0f c1 03 49 8b 55 00 <48> 8b 0a 90 83 f8 01 74 0e 5b 5d 41 5c 41 5d 41 5e c3 0f 1f 44 00
[ 3535.637338] audit: type=1701 audit(1571684137.643:287): auid=1000 uid=1000 gid=1001 ses=2 pid=13296 comm="xfce4-power-man" exe="/usr/bin/xfce4-power-manager" sig=11 res=1
[ 3535.650270] audit: type=1130 audit(1571684137.656:288): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-coredump@1-13314-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[ 3536.234573] audit: type=1131 audit(1571684138.240:289): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-coredump@1-13314-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
```

**Solutions you've tried**
This persists since installation, through a few dom0 updates (both command-line `sudo qubes-dom0-update` and the GUI update manager) and subsequent reboots.

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
I didn't find any relevant issues.

**Comment by NieDzejkob** [comment]
This is no longer reproducible on my end. Perhaps some update fixed it.

**Comment by NieDzejkob** [comment]
Reproduced it again. Turns out it might be intermittent.

**Comment by NieDzejkob** [comment]
I noticed that this only happens when my laptop is connected to AC, possibly only when fully charged.
