### ISSUE TITLE
Improve/rewrite qvm-pool arguments parser

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#5407]
**The problem you're addressing (if any)**
qvm-pool arguments are inconsistent with other tools.

**Describe the solution you'd like**
Things to change:
 - use action as a first positional argument (`add`, `info`, `remove` etc) instead of an option (`-a`, `-i` etc)
 - accept multiple pool options in separate `-o` arguments, instead of one `-o` with coma separated values

**Where is the value to a user, and who might that user be?**
Consistency with other tools like `qvm-volume`, `qvm-device` etc.

**Additional context**
There need to be some kind of backward compatibility. I would use a tool `qvm-pool-legacy` accepting "old" options and redirect to it automatically when old action (`-a`, `-i`) is detected.

While at it, we should update https://www.qubes-os.org/doc/storage-pools/ (still R3.2).

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
https://www.qubes-os.org/doc/storage-pools/
https://dev.qubes-os.org/projects/core-admin-client/en/latest/manpages/qvm-pool.html

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

**Comment by SaswatPadhi** [comment]
I had some time and thought this would be a good first issue to work on :)

@marmarek, Please take a look at the PR I've opened when you have time.
