### ISSUE TITLE
VM crashes after unpause

### ISSUE THREAD

**Issue by lattice0** [QubesOS/qubes-issues#5409]
**Qubes OS version**
4.0.1

**Brief summary**
When I unpause a specific VM, it crashes sometimes. It's just that but I already reinstalled and even reinstalled qubes and reinstalled this VM. So the crash must have something to do with what I use on this VM. It's a standalone with template from debian 9. I use a lot of RAM (9gb) for it, and leave lots of things open. When I unpause, sometimes it crashes.

**Solutions you've tried**
I don't have any idea on how to debug this problem

**Comment by marmarek** [comment]
Check console output of this VM when it crashes. It's available in `/var/log/xen/console/guest-VMNAME.log`, you can access this file also in qube manager (right click on the VM, logs submenu).

**Comment by brendanhoar** [comment]
In my experience, this is related to memory sharing and the balloon driver, where the VM is asking and/or is asked to increase/return memory and it fails. Not sure if timing, or if entity being asked to do something not possible at the time.
