### ISSUE TITLE
Dead link on website

### ISSUE THREAD

**Issue by propeeves** [QubesOS/qubes-issues#5411]
https://www.qubes-os.org/support/ contains a dead link in the "Mailing Lists vs. Forums" section - the "unofficial forum" link goes to a dead domain.

**Comment by andrewdavidwong** [comment]
Thanks for the report! @Zrubi [announced](https://groups.google.com/d/msg/qubes-users/xXzLgVH7HD8/s1qFZHhRAgAJ) that the unofficial forum was taken offline, so I'll remove the link.
