### ISSUE TITLE
updating tor browser (anondist) in whonix-ws-14-dvm halts the disp vm

### ISSUE THREAD

**Issue by ThomasWaldmann** [QubesOS/qubes-issues#5414]
**Qubes OS version**
R4.0 with updates.

**Affected component(s) or functionality**
detection when a dispvm should be shut down.

**Brief summary**
In the past, when I started the tor browser via the respective menu entry, it usually automatically looked for an update and downloaded it. When it was dl'ed, it showed there an ready-to-apply-update (green up pointer) icon within tor browser. Clicking on it shortly shut down tb, applied update, restarted tb (within the same distvm).

Now it is impossible to update because the distvm gets shut down (and is disposed, so next time you start it, this repeats).

**To Reproduce**

1. Go to 'whonix-ws-14-dvm'
2. Click on 'Tor Browser (AnonDist)'
3. Wait for TB to display "update ready" icon (might be faster with manually checking for an update "Check for Tor Browser Update" from left-side onion menu)
4. Click "Restart to update Tor Browser" in right-side hamburger menu
5. It starts applying the update and then Qubes halts the dispvm.

**Expected behavior**
The dispvm should continue to run.

**Actual behavior**
dispvm halted and disposed.

Guess a workaround could be to keep another process open all the time, but in the past this worked without that hack.

**Comment by marmarek** [comment]
Whonix 14 is not supported anymore: https://www.qubes-os.org/news/2019/07/01/whonix-15-has-been-released/

**Comment by ThomasWaldmann** [comment]
Ah, thanks for the hint.

I can confirm that the issue is solved by upgrading to 15.
