### ISSUE TITLE
Why can't I start QubesOS?

### ISSUE THREAD

**Issue by Cvrew** [QubesOS/qubes-issues#5417]
If you try to start QubesOS at one time, you will not be able to login because it is displayed in white letters on a black screen like this: How can I solve it?

- Qubes release 4.8 (R4.8) 

- Kernel 4.19.71-1.pvops.qubes .x86_64 on an x86_64 (tty1) 

- dom login 
-  Passuord: Passward (my password)
- Login incorrect 
- 
- doma login: username
- Password: 
- Last login: Sat Oct 19 19:42:12 on :0- 
- -bash: warning: setlocale: LC_CTYPE: cannot chage locale (ja_JP . UTF -8 ): No such file or directory 
- -bash: warning setloca le: LC_COLLATE: cannot change locale ja_JP . UTF-8 ) : No such file or directory 
- -bash: warning: setlocale: LC_NUMERIC: cannot change locale (ja_JP . UTF -8): No such file or directory 
- -bash: waring: setloca le: LC TIME: cannot change locale (ja_JP.UTF-8): No such file or d irectory -bash: waring: setloca le: LC_MESSAGES: cannot change loca le ja_JP.UTF-8): No such file or directory

**Comment by andrewdavidwong** [comment]
Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this does not appear to be suitable for `qubes-issues`. We ask that you please send this to the `qubes-users` [mailing list](https://www.qubes-os.org/support/) instead. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a brief comment explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.
