### ISSUE TITLE
ubuntu 16.04 xenial template asks for sudo password ( newbie question ... ) debian/ubuntu

### ISSUE THREAD

**Issue by tricofait** [QubesOS/qubes-issues#5418]
Sorry for asking, this is the first time i am compiling a template that i need to simulate a production environment and therefore to install the lamp stack on it ( if possible )...

I followed the guide below only changing from [xenial destop option] to simple xenial:
https://denariustalk.org/index.php?/topic/305-guide-to-installing-qbuntu-ubuntu-1604-xenial-templatevm-in-qubes-402-rc1/

All worked perfectly well after 3 hours, no issues at all but to update the newly created template using:
sudo apt-get update 
on a terminal it asks me for the sudo password that i do not have anywhere on the system. 

Is there an option or some way to avoid the sudoer pass prompt upon the compilation of a new template?

Thank you so much in advance, this is an amazing OS, great great job!!!

**Comment by andrewdavidwong** [comment]
You can just start a root terminal from dom0:

```
qvm-run -u root <vm-name> xterm
```

Since `qubes-issues` is not a place for asking questions (see our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/)), please direct any follow-up questions to the `qubes-users` [mailing list](https://www.qubes-os.org/support/). If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a brief comment explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.

**Comment by unman** [comment]
On Sat, Oct 26, 2019 at 06:11:03AM -0700, tricofait wrote:
> Sorry for asking, this is the first time i am compiling a template that i need to simulate a production environment and therefore to install the lamp stack on it ( if possible )...
> 
> I followed the guide below only changing from [xenial destop option] to simple xenial:
> https://denariustalk.org/index.php?/topic/305-guide-to-installing-qbuntu-ubuntu-1604-xenial-templatevm-in-qubes-402-rc1/
> 
> All worked perfectly well after 3 hours, no issues at all but to update the newly created template using:
> sudo apt-get update 
> on a terminal it asks me for the sudo password that i do not have anywhere on the system. 
> 
> Is there an option or some way to avoid the sudoer pass prompt upon the compilation of a new template?
> 
> Thank you so much in advance, this is an amazing OS, great great job!!!
> 

It's Ubuntu - all you have to do is "sudo su - " and you get root shell.

**Comment by tricofait** [comment]
Thank you for helping,

@andrewdavidwong that command helped a lot but i could not have clipboard with xterm so i changed it to:
qvm-run -u root xenial qubes-run-terminal
( sharing because it could be useful for others ). That saved the day!

@unman no sudo command works without a password on that template. Thank you.
