### ISSUE TITLE
Ubuntu bionic  template: No Passwordless Root Access

### ISSUE THREAD

**Issue by zaoqi** [QubesOS/qubes-issues#5420]
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
Ubuntu bionic/xenial  template

**Brief summary**
su/sudo ask for password

**To Reproduce**

**Expected behavior**
Passwordless Root Access

**Actual behavior**
ask for password

**Screenshots**

**Additional context**

**Solutions you've tried**

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
https://www.qubes-os.org/doc/vm-sudo/

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
https://github.com/QubesOS/qubes-issues/issues/5418

**Comment by unman** [comment]
Why would you expect passwordless access? This is a stock Ubuntu install.
You don't say what you have read, what you have tried,  or what steps you have taken.
If you want passwordless access, either consult **any** Ubuntu guide as to how to configure the system to do this, or install the vm-sudo package.
It really isn't a Qubes issue.
