### ISSUE TITLE
Add option to open all links in other AppVM

### ISSUE THREAD

**Issue by heinrich-ulbricht** [QubesOS/qubes-issues#5425]
**The problem you're addressing (if any)**
As a Qubes user I want every link I click in an AppVM to open in another AppVM to not compromise my current AppVM.

**Describe the solution you'd like**
* Idea 1, using disposable VMs:
  * In Qubes Setting I'd like to tick a box near the Disposable VM Template that says something like "Open all Links in Disposable VM".
* Idea 2, using any AppVM:
  * In Qubes Setting I want to configure another AppVM that will be used to open links in a browser.

**Where is the value to a user, and who might that user be?**
This is a security benefit for every Qubes user. E.g. clicking links in Thunderbird or a messenger application or a development environment would always open a browser in another AppVM (NOT the current one).

**Describe alternatives you've considered**
I consider configuring this by hand as described here: https://micahflee.com/2016/06/qubes-tip-opening-links-in-your-preferred-appvm/ This solution leverages `qvm-open-in-vm`, the default web browser setting and a custom _.desktop_ file with scheme handlers e.g. for http(s).

But I'd prefer a built-in solution.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
I read through the Qubes Users Google Group and found many references to a [browser extension by Raffaele Florio](https://github.com/raffaeleflorio/qubes-url-redirector/). But this is too specific and... it's a browser extension.

**Comment by SvenSemmler** [comment]
Hi @heinrich-ulbricht,
I think as far as possible this is already build in through the policy and the respective dialog. The one thing you have to do manually at this point is to set the URL handler in the respective AppVM to qvm-open-in-vm by defining a desktop shortcut and calling xdg-settings.

See also https://github.com/Qubes-Community/Contents/blob/master/docs/common-tasks/opening-urls-in-vms.md

**Comment by heinrich-ulbricht** [comment]
@SvenSemmler 
From an end user perspective this has setup and maintenance costs that I'd like to reduce. And it looks like such functionality could be easily integrated into the existing Qubes UI. (Not sure about the difficulty of building the backend for this). So this is an early wish for Christmas :)

But since it seems like the only way I'll probably go this route. Thank you very much for the link to the docs, I did not know this page yet. Good info there.

**Comment by heinrich-ulbricht** [comment]
The documentation linked by @SvenSemmler is excellent and worked. Building a UI for this might be complex and not necessary, given that some text file changes are enough to configure this. Therefore I close this ticket.
