### ISSUE TITLE
Improve instructions for fetching all qubes repositories

### ISSUE THREAD

**Issue by hexagonrecursion** [QubesOS/qubes-issues#5428]
**Affected component(s) or functionality (if applicable)**
https://www.qubes-os.org/doc/source-code/

**Brief summary**
There are so many QubesOS repositories that the below command (quoted from the above doc page) doesn't actually clone all of them
```
curl "https://api.github.com/orgs/QubesOS/repos?page=1&per_page=100" | grep -e 'clone_url*' | cut -d \" -f 4 | xargs -L1 git clone
```

**Additional context**
There are 121 QubesOS repositories and the github API returns at most 100 items per request.

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
none

**Comment by andrewdavidwong** [comment]
CC @marmarek

**Comment by marmarek** [comment]
Alternative way to download all source code repositories is to use [qubes-builder](https://www.qubes-os.org/doc/qubes-iso-building/#build-using-setup-script). It will work regardless of repositories count, but on the other hand, it doesn't guarantee downloading all of them - only those need to build a specific qubes version. For example qubes-secpack or website aren't included.

**Comment by unman** [comment]
@hexagonrecursion  @andrewdavidwong  I've updated the [source code page](https://www.qubes-os.org/doc/source-code/) to resolve this issue, *and* to make it clear that it isnt necessary.
Please close this issue.
