### ISSUE TITLE
Changing keyboard layout prevents application hotkeys from working

### ISSUE THREAD

**Issue by hexagonrecursion** [QubesOS/qubes-issues#5431]
**Qubes OS version**
Qubes release 4.0 (R4.0)

**Affected component(s) or functionality**
Qubes Manager
Official Fedora 30 template

**Brief summary**
When using any non-default keyboard layout hot key combinations in many (all?) applications are not recognized.

**To Reproduce**
1. Start a qube
2. In Qubes Manager set keyboard layout for the qube to af (Afghani)
3. Open firefox in the qube
4. Try typing hotkeys (Ctrl+F, Ctrl+A, Ctrl+Z, Ctrl+C, Ctrl+V etc)

**Expected behavior**
Hotkeys work as they normally do.

**Actual behavior**
Hotkeys do nothing.

**Additional context**
In all other operating systems hotkeys work regardless of the keyboard layout.

**Solutions you've tried**
none so far

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
none

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
none

**Comment by marmarek** [comment]
Does it match dom0 keyboard layout? If not, that may be an issue and ultimately another case of #1396

**Comment by hexagonrecursion** [comment]
First of all: it is a per-qube setting. What is the point of it being per-qube if it has to match dom0?
Secondly: just to check I changed the dom0 keyboard layout to af (`localectl set-x11-keymap "af"` and reboot) and now copy-paste between domains doesn't work and hotkeys only work in domU if I manually set domU keyboard layout to us.

**Comment by hexagonrecursion** [comment]
Because this is present even when DomU layout happens to match Dom0 I believe this is a separate bug.

**Comment by jevank** [comment]
New variant layout propagation (https://github.com/QubesOS/qubes-issues/issues/1396, https://github.com/QubesOS/qubes-issues/issues/4294) makes current issue actual. Without latin layout hotkey mostly (completely?) doesn`t work. What about forcing double layout (actual + latin) to vm instead of sinlgle?
