### ISSUE TITLE
Gnome Control Center fails to start in template

### ISSUE THREAD

**Issue by hexagonrecursion** [QubesOS/qubes-issues#5433]
**Qubes OS version**
Qubes release 4.0 (R4.0)

**Affected component(s) or functionality**
qubes-template-fedora-30-201907160147
gnome-control-center-3.32.2-1.fc30

**Brief summary**
The fedora settings app (Gnome Control Center) fails to start in a template.

**To Reproduce**
run gnome-control-center in a template

**Expected behavior**
GCC starts normally

**Actual behavior**
```
$ gnome-control-center 
**
ERROR:../shell/cc-shell-model.c:458:cc_shell_model_set_panel_visibility: assertion failed: (valid)
Aborted (core dumped)
```
**Additional context**
This upstream bug is likely related: https://bugzilla.redhat.com/show_bug.cgi?id=1645855

**Solutions you've tried**
The bug report linked above suggests a workaround: start the GCC with a modified environment. This appears to work, but prints a flood of warnings to the console.
```
$ XDG_CURRENT_DESKTOP=GNOME gnome-control-center
```

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
none

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
https://github.com/QubesOS/qubes-issues/issues/3635 - likely unrelated because the error message is different.

**Comment by andrewdavidwong** [comment]
@marmarek, @fepitre: Is this a Qubes-specific bug?

**Comment by hexagonrecursion** [comment]
@andrewdavidwong Sorry. You are right. This is an upstream bug. Furthermore: even with the workaround GCC is buggy (some tabs take a while to load, the "devices" tab makes a core dump).
I think there is one thing we can fix though: the entry for the known-broken app should not be automatically added to the qvm-appmenus whitelist when the template is installed.

**Comment by fepitre** [comment]
> @marmarek, @fepitre: Is this a Qubes-specific bug?
No it's not.

> I think there is one thing we can fix though: the entry for the known-broken app should not be automatically added to the qvm-appmenus whitelist when the template is installed.
There is no easy way for doing such thing. Currently, it looks for every .desktop file entries in a given vm (system wide for template, user wide for appvm). Implementing a filtering in VM side would mean to maintain a specific list of non-working apps. Implementing a filtering in dom0, IMO, is not a good idea because dom0 should not have any intelligence of what is going on exactly in a VM (from app point of view).

Generally, I encountered such errors with Gnome due to badly configured xsession. So maybe the best way is to search for what exactly we should configure/set to make it working.

**Comment by hexagonrecursion** [comment]
> > I think there is one thing we can fix though: the entry for the known-broken app should not be automatically added to the qvm-appmenus whitelist when the template is installed.
> 
> There is no easy way for doing such thing.

Sorry if I was unclear. I meant this kind of whitelist: .https://github.com/QubesOS/qubes-builder-rpm/blob/master/template_scripts/appmenus_fc/whitelisted-appmenus.list

**Comment by andrewdavidwong** [comment]
Closing as "not our bug." If you believe this is a mistake, please leave a comment, and we'll be happy to take another look. Thank you.

**Comment by hexagonrecursion** [comment]
Interestingly enough Gnome Control Center technically manages to start when launched from the [community centos 7 template](https://github.com/QubesOS/updates-status/issues/1305). It is completely empty though.

**Comment by fepitre** [comment]
Yes, there is definitely something to investigate of what should be properly set etc.

**Comment by andrewdavidwong** [comment]
> Yes, there is definitely something to investigate of what should be properly set etc.

It might be clearer and less confusing to create a separate issue for this. (Or, if you all strongly prefer it for some reason, we could re-open and re-purpose this issue for that work.)

**Comment by fepitre** [comment]
> > Yes, there is definitely something to investigate of what should be properly set etc.
> 
> It might be clearer and less confusing to create a separate issue for this. (Or, if you all strongly prefer it for some reason, we could re-open and re-purpose this issue for that work.)

Yes. Better open another one with all the current investigation elements.
