### ISSUE TITLE
Qubes insufficient RAM reading

### ISSUE THREAD

**Issue by TNTBOMBOM** [QubesOS/qubes-issues#5434]
**Qubes OS version**
R.4

**Affected component(s) or functionality**
Qubes kernel? 

**Brief summary**
Qubes doesnt detect 50% of the ram usage

**To Reproduce**
Have a PC with 16 GB RAMs using 2 slots (8 and 8)

**Expected behavior**
Should be read as 16 not just 8

**Actual behavior**
only 8 

**Screenshots**
NA

**Additional context**
Im aware that dom0 uses 4GB of rams only (according to the related stuff on the ticket below) but now one of my PCs has 16GB but only 8GB is readable from dom0.

If you want further debugging commands please provide them.

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

https://github.com/QubesOS/qubes-issues/issues/1584

**Comment by marmarek** [comment]
dom0 (intentionally) use only part of the RAM. The easiest way to see how much RAM is detected and and usable by Qubes as a whole, you can use `qubes-hcl-report` tool.

**Comment by TNTBOMBOM** [comment]
ah thats the only way then to see the true reading of whole ram been used.

sorry i was looking at task manager readings, feel free to close.

Marek Marczykowski-Górecki:
> dom0 (intentionally) use only part of the RAM. The easiest way to see how much RAM is detected and and usable by Qubes as a whole, you can use `qubes-hcl-report` tool.
>
