### ISSUE TITLE
Wifi card not recognized MacBook air 2017 broadcom BCM4360

### ISSUE THREAD

**Issue by qwerty001100** [QubesOS/qubes-issues#5436]
**Qubes OS version**
qubes 4.0.2 rc1
**Affected component(s) or functionality**
Wifi card broadcom bcm4360

**Brief summary**
Qubes can't recognize the card, 
In this mac I have debian installed and i had to manage even there to get the wifi card working but I think it was easier to do.
I bought the thunderbolt adapter to get ethernet connection but I need the wifi..

I would like to have an easy or step by step workaround, i've read two people's post who solved this problem but qube os version was older and macbook either.

**To Reproduce**
no Wifi list

**Expected behavior**
possibility to chosose the wifi connection

**Actual behavior**
Nothing happens when i press the connection tab at the top right of the screen

**Solutions you've tried**
What's written in the post of those users may be outdated, in any case i'll try it.
Fact is explanation requires a bit of coding knownledge that i don't have

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
https://groups.google.com/forum/#!searchin/qubes-users/broadcom$20success/qubes-users/VVwWqvz5dX4/Xbum_4MaCgAJ

Thank you in advance for any help

**Comment by andrewdavidwong** [comment]
This might be too localized for qubes-issues or an upstream issue, but I'll leave it open for the devs to decide.
