### ISSUE TITLE
Upgrade the version of WireGuard and check the hash of the compressed tarball

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#5437]
**Qubes OS version (if applicable)**
`Qubes release 4.0 (R4.0)`

**Affected component(s) or functionality (if applicable)**
WireGuard module in dom0-provided kernels

**Brief summary**
The WireGuard module is currently an old version.  Furthermore, the build system only checks the signatures of the tarballs after decompressing them.

**Additional context**
Donenfield’s release emails are signed by his PGP key, and contain secure hashes of the compressed tarballs.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
[The relevant announcement](https://lists.zx2c4.com/pipermail/wireguard/2019-October/004594.html)

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

**Comment by marmarek** [comment]
Any idea how to script this? Even just extracting an email body in a plain text (to be verified by gpg2 directly) would be useful. The more manual work such update will need, the rarely it will be done. Manually extracting email (from the website or mbox file) and copying hash is clearly a regress here.

**Comment by xaki23** [comment]
wouldnt go for automated updates tbh. 
"old version" is kinda strong wording when the version is one release and one month "behind" for something that tends to have multi-month holes between releases.
more so on a project that tries to be as annoying as possible about releases. (you actualy need JS to even see the current version on the website!)

the "gpg signature is for uncompressed source" is something wg does just the same as linux kernel.

will toss another bump-to-current PR in the next days unless someone actualy steps up and wants to do automation here. 

(there is also some hope wg might be merged into mainline before hell freezes over since the debate on this seems to be at the he-said-she-said phase now, beyond the everyone-calling-each-other-names parts...)
see also: https://lore.kernel.org/lkml/CAHmME9pmfZAp5zd9BDLFc2fWUhtzZcjYZc2atTPTyNFFmEdHLg@mail.gmail.com/

**Comment by xaki23** [comment]
... and to 20191127 ... https://github.com/QubesOS/qubes-linux-kernel/pull/128

**Comment by fepitre** [comment]
I should implement the upgrade in the automatic updater. I will see what I can do.

**Comment by xaki23** [comment]
> I should implement the upgrade in the automatic updater. I will see what I can do.

dont spend too much time/energy on it, as said there is a reasonable chance now for wg to get merged into mainline _and_ its really just a s/olddate/newdate/ plus commit at this point. :)

**Comment by xaki23** [comment]
the renames are part of the prep to get wg merged into mainline.
it seems 5.5 will only contain the cryptoapi-groundwork for wg, but not wg itself yet.

**Comment by xaki23** [comment]
side note: https://github.com/janestreet/noise-wireguard-ocaml
this could lead to a mirage-unikernel wireguard gate. 
either standalone or as a feature of https://github.com/mirage/qubes-mirage-firewall
which sounds very interesting either way.
fyi ping @talex5 @laudecay
(yes, offtopic here, but i never figured out how to ping talex outside of github)

**Comment by DemiMarie** [comment]
Can we do the downloading and decompression in a DispVM?  @marmarek

**Comment by marmarek** [comment]
With the current build setup? not really.

**Comment by DemiMarie** [comment]
True, but the actual production binaries are built on QubesOS, so we can do it in a DispVM there.

**Comment by marmarek** [comment]
I understand the decompression process could potentially be complex, but don't think the risk necessary warrant spawning separate DispVM for this task, especially in context of [exactly 0 CVEs](https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&search_type=all&cpe_vendor=cpe%3A%2F%3Atukaani&cpe_product=cpe%3A%2F%3Atukaani%3Axz) in decompression code in the whole xz project history (the only _one_ is an issue in xzgrep script).
If you still think it's worth the effort, simpler solution would be to commit hashes of the compressed tarballs, or more specifically - have a script that automate this. And it happen we already have a place where such code could be added: https://github.com/QubesOS/qubes-linux-kernel/blob/master/update-sources (this is the part responsible for PRs opened by @fepitre-bot).
BTW, if want to work on this, you may also want to do the same about the kernel tarball itself - where also upstream publishes signatures only of the uncompressed version.

**Comment by DemiMarie** [comment]
Has xz been fuzz-tested?  It should probably be submitted to OSS-Fuzz.

**Comment by marmarek** [comment]
[It is already there](https://github.com/google/oss-fuzz/tree/master/projects/xz), since Nov 2018.

**Comment by xaki23** [comment]
this one can probably be closed considering wireguard is in mainline kernel since 2020-03

**Comment by laudiacay** [comment]
wow what a throwback
