### ISSUE TITLE
"View in DisposableVM" fails silently when no DVM template is selected

### ISSUE THREAD

**Issue by meithecatte** [QubesOS/qubes-issues#5439]
**Qubes OS version**
Qubes Release 4.0 (R4.0)

**Affected component(s) or functionality**
The "View in DisposableVM" option visible when right-clicking on a file in the file manager.

**Brief summary**
When you click on "view in DisposableVM" and the "default DisposableVM template" for the AppVM is set to "none", no error message is shown.

**To Reproduce**
1. Choose an AppVM to use for the experiment
2. Open Qube Manager
3. Right click on the chosen AppVM
4. Choose "Qube Settings"
5. Switch to the "Advanced" tab
6. In the other section, look at "Default DisposableVM Template", and make sure it is set to "none".
7. Close the dialog with "OK".
8. Boot the AppVM
9. Open file manager in the VM
10. Navigate to a folder with a pdf
11. Right click on the pdf file
12. Choose "View in DisposableVM"

**Expected behavior**
An error pops up explaining that no DVM template has been chosen and the feature can't be used. Bonus points: a dropdown is offered with available DVM templates to configure the feature in-place.

**Actual behavior**
The context menu disappears, and then... nothing. The user is wondering if the feature is taking so long or just isn't working.

**Additional context**
Qubes seems to be installed by default with the default DVM template set to "none". Perhaps it would be desirable to make the default "fedora-29-dvm" instead.

**Comment by hexagonrecursion** [comment]
Related: https://github.com/QubesOS/qubes-issues/issues/3904, https://github.com/QubesOS/qubes-issues/issues/5384
