### ISSUE TITLE
folow up Upcoming Qubes presentations at Platform Security Summit 2019

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#5441]
https://www.qubes-os.org/news/2019/09/18/qubes-presentations-at-platform-security-summit-2019/

Was any of this recorded on video or otherwise? If so, perhaps update?

**Comment by marmarek** [comment]
Yes, video was recorded and will be published on http://www.platformsecuritysummit.com/2019/videos/. It isn't there yet (but there are others already published, some very interesting!).

**Comment by andrewdavidwong** [comment]
I still don't see Marek's or Thierry's videos there. Anyway, I'm guessing that this is now old enough to no longer be actionable.
