### ISSUE TITLE
Website: Video tours Hope conference video does not play

### ISSUE THREAD

**Issue by rbrins4** [QubesOS/qubes-issues#5444]
**Qubes OS version**
4.0 (R4.0) 
Standard VM - Debian 9 firefox and Fedora 29 firefox

**Affected component(s) or functionality**
Website - https://www.qubes-os.org/video-tours/

**Brief summary**
The first video tour of qubes does not play and displays "Sorry, this video cannot be played on this browser or device." The link with the text as "Qubes OS: The Operating System That Can Protect You Even If You Get Hacked" does not go to a page. 

**To Reproduce**
_Steps to reproduce the behavior:_
1. Open a default fedora 29 VM's firefox with sys-firewall
2. Go to https://www.qubes-os.org/video-tours/
3. Try to view "Micah Lee present "Qubes OS: The Operating System That Can Protect You Even If You Get Hacked"
5. Repeat with Qubes OS default debian 9 VM's firefox with sys-firewall

**Expected behavior**
The video is able to load on the default firefox in the default VMs in qubes to help new users

**Actual behavior**
The video does not load

**Screenshots**
![Screenshot_2019-11-03 Video Tours of Qubes OS](https://user-images.githubusercontent.com/57331546/68092660-6b77c080-fe5b-11e9-9e54-bd27b6bddb41.png)

**Additional context**
I've had problems in general trying to figure out how to watch videos in the default VM, youtube seems to work just fine.

**Solutions you've tried**
On the debian 9 default VM, it pulls the video up (does not play it), you can click on Watch on Live Stream within the player. This live stream website seems to work. 
Current workaround for me is to view in debian 9 and click on watch on live stream button.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
I tried searching a few different places and saw that fedora may not have the right codex and that debian should work better. 
I tried to access the page in the qubes-os webpage in github to see about tinkering with the links in the code and couldn't find the specific page.
I found https://github.com/QubesOS/qubesos.github.io/commit/b60edc4d057f71eae41104a58ffe0a42bfe9b9ee which lead me to a page that didn't seem to even have the micah lee presentation.

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
none

**Comment by pabpas** [comment]
The codecs needed to play those videos (and many others) are in rpmfusion. First enable the repo and then install `ffmpeg`:

`sudo dnf config-manager --set-enabled rpmfusion-free`
`sudo dnf upgrade --refresh`
`sudo dnf install ffmpeg`

Restart firefox.

**Comment by andrewdavidwong** [comment]
It looks like this is a case of missing codecs in the visitor's web browser rather than any actual bug with the website, so I'll close this as `not an issue`. If you believe this is a mistake, please leave a comment, and we'll be happy to take another look. Thank you.
