### ISSUE TITLE
Audio icon won't load

### ISSUE THREAD

**Issue by e6lk7dqzm83p** [QubesOS/qubes-issues#5446]
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
Audio icon in system tray

**Brief summary**
I tried to unmute my audio, the icon was non-response and keyboard shortcuts stopped working.  I killed pulseaudio to see if it would restart the process automatically, and it did not.  I then restarted Qubes and the audio icon is still not there.  I have to control audio through the Pulse Audio Volume Control application.

**To Reproduce**
Unknown

**Expected behavior**
The audio system tray icon loads and can be used to control the volume/mute status; keyboard shortcuts for audio control work.

**Actual behavior**
The audio system tray icon does not load and cannot be used to control the volume/mute status; keyboard shortcuts for audio control do not work.

**Screenshots**
None

**Additional context**
None

**Solutions you've tried**
Restarting Qubes

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
I haven't found any documents or issues related to this

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
None that I could find

**Comment by e6lk7dqzm83p** [comment]
@andrewdavidwong I cannot find any documentation as to how to manually start the audio tray icon for pulseaudio...do you know what that command would be (I'd like to see if it's a command not starting issue or if there's something else wrong)?

**Comment by andrewdavidwong** [comment]
> @andrewdavidwong I cannot find any documentation as to how to manually start the audio tray icon for pulseaudio...do you know what that command would be (I'd like to see if it's a command not starting issue or if there's something else wrong)?

Sorry, I'm afraid I don't know it (perhaps someone else will chime in). However, I would think that it is not Qubes-specific. You may want to try searching for pulseaudio on Linux in general.

**Comment by e6lk7dqzm83p** [comment]
Ok, update....

I think this is an xfce4 issue, when I login using Gnome as my desktop manager the volume icon appears and my keyboard shortcuts to adjust the volume work as expected.  Is there a way to reset xfce?  Again, I think this is anomalous behavior/a bug since this isn't how xfce should behave, but that may be the fix (I'm also wondering if that would solve the odd issues in #5144 ).

**Comment by marmarek** [comment]
I'm not sure if there is a way to "reset xfce" other than manually removing appropriate files in `~/.config`. But you can add volume widget with: right click on the panel -> Panel -> Add New Items and select "PulseAudio Plugin".

**Comment by e6lk7dqzm83p** [comment]
Hi,
@marmarek that did the trick!  I'll tag you in #5144 to get more information about clearing the xfce files.  

I had a hard time finding documentation around xfce on the Qubes site, but perhaps my search-fu is weak.

Thank you!
