### ISSUE TITLE
Interrupt Remapping error during Qubes 4.0.2-RC2 install on ThinkPad T410 Core i7-620M

### ISSUE THREAD

**Issue by haphaeu** [QubesOS/qubes-issues#5449]
**Qubes OS version**
R4.0.2-RC2

**Affected component(s) or functionality**
Installer

**Brief summary**
During installation, Unsupported Hardware Detected message pops up with Interrupt Remapping missing. Processor has VT-d after [this](https://ark.intel.com/content/www/us/en/ark/products/43560/intel-core-i7-620m-processor-4m-cache-2-66-ghz.html).

**To Reproduce**
1. Launch Qubes R4.0.2-RC2 Installer on a ThinkPad T410 i7-620M
2. Select of language
3. Unsupported Hardware Detected message pops up.

**Expected behavior**
Normal installation flow without unsupported hardware messages.

The CPU Intel Core i7 620M has [VT-d](https://ark.intel.com/content/www/us/en/ark/products/43560/intel-core-i7-620m-processor-4m-cache-2-66-ghz.html#tab-blade-1-0-7). 

**Actual behavior**
Message "Unsupported Hardware Detected: missing Interrupt Remapping" pops up.

**Additional context**
Same behaviour with R4.0.1. 

Installation continues without problem. VMs can be launched. I'm not sure what is the real extend or consequences of the error or misinterpreted lack of Interrupt Remapping.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
Interesting to note that [System Requirements](https://www.qubes-os.org/doc/system-requirements/) page has no mentions whatsoever about "Interrupt Remapping", which is the nomenclature used by the installer. So it is sort of not straightforward to understand what is missing. After some research it seems to be linked to VT-d technology, but still not 100% sure.

**Comment by haphaeu** [comment]
HCL report:

```
---
layout:
  'hcl'
type:
  'notebook'
hvm:
  'yes'
iommu:
  'yes'
slat:
  'yes'
tpm:
  ''
remap:
  'no'
brand: |
  LENOVO
model: |
  2522ES7
bios: |
  6IET72WW (1.32 )
cpu: |
  Intel(R) Core(TM) i7 CPU       M 620  @ 2.67GHz
cpu-short: |
  FIXME
chipset: |
  Intel Corporation Core Processor DRAM Controller [8086:0044] (rev 02)
chipset-short: |
  FIXME
gpu: |
  NVIDIA Corporation GT218M [NVS 3100M] [10de:0a6c] (rev a2) (prog-if 00 [VGA controller])
gpu-short: |
  FIXME
network: |
  Intel Corporation 82577LM Gigabit Network Connection (rev 06)
  Intel Corporation Centrino Ultimate-N 6300 (rev 35)
memory: |
  8051
scsi: |
  SAMSUNG MZ7TD128 Rev: 4L0Q
  DVDRAM GU10N     Rev: MX05
usb: |
  2
versions:

- works:
    'FIXME:yes|no|partial'
  qubes: |
    R4.0
  xen: |
    4.8.5-11.fc25
  kernel: |
    4.19.81-1
  remark: |
    FIXME
  credit: |
    FIXAUTHOR
  link: |
    FIXLINK

---

```

**Comment by marmarek** [comment]
Can you check Xen messages related to VT-d? Like this: `xl dmesg|grep VT-d`

Unfortunately VT-d interrupt-remapping isn't listed as a separate feature on ark.intel.com. AFAIK it is available in desktop/mobile CPUs starting with Sandy Bridge (Q1 2011), even though it is described as part of the original Intel VT-d specification as one of available features.

**Comment by haphaeu** [comment]
Please see below. 
Does that mean that this CPU actually does not support the feature?
What are the implications of this? 
```
[raf@dom0 ~]$ xl dmesg | grep VT-d
(XEN) Intel VT-d iommu 0 supported page sizes: 4kB.
(XEN) Intel VT-d iommu 1 supported page sizes: 4kB.
(XEN) Intel VT-d Snoop Control not enabled.
(XEN) Intel VT-d Dom0 DMA Passthrough not enabled.
(XEN) Intel VT-d Queued Invalidation not enabled.
(XEN) Intel VT-d Interrupt Remapping not enabled.
(XEN) Intel VT-d Posted Interrupt not enabled.
(XEN) Intel VT-d Shared EPT tables not enabled.
```

**Comment by marmarek** [comment]
>  Does that mean that this CPU actually does not support the feature?

Yes, looks like it.

>  What are the implications of this?

That's complicated. In short: some attacks are still possible, but it is still _much_ better than no VT-d at all. Detailed version: https://invisiblethingslab.com/resources/2011/Software%20Attacks%20on%20Intel%20VT-d.pdf

**Comment by haphaeu** [comment]
Thanks! I guess that closes it. Cheet
