### ISSUE TITLE
TPM error at start-up , only dom0 work , VM won't start

### ISSUE THREAD

**Issue by sucrecacao** [QubesOS/qubes-issues#5450]
**Qubes OS version**
_The version of Qubes OS you're using (e.g., `R4.0`), available via the command `cat /etc/qubes-release` in a dom0 terminal._

**Affected component(s) or functionality**
App VM won't start. `qvm-*` command won't work

**Brief summary**
Only dom0 work. I have an TPM error at startup
`"a tpm error occurred attempting to read a pcr value"`

**To Reproduce**
Hard to know how to trigger the TPM error

**Expected behavior**
You can open an App VM.

**Actual behavior**
App VM won't start**Additional context**
I also had pb with a disk with no space left as I mentioned here  #5352 . But I tried everything to free space and trim and still it doesn't work.

**Comment by marmarek** [comment]
> App VM won't start. `qvm-*` command won't work

Can you say what exactly happens?
Please also provide more details about the hardware, ideally paste `qubes-hcl-report` command output.
