### ISSUE TITLE
Bug in packages in kali linux

### ISSUE THREAD

**Issue by abbaas-cyber** [QubesOS/qubes-issues#5451]
**Qubes OS version**
R4.0.1

**Affected component(s) or functionality**
 Debian template with Kali Linux repositories
   qubes-core-agent-dom0-updates (4.0.50-1+deb10u1)
   qubes-core-agent-passwordless-root (4.0.50-1+deb10u1)
   qubes-gpg-split (2.0.40-1+deb10u1)
   qubes-img-converter (1.2.6-1+deb10u1)
   qubes-input-proxy-sender (1.0.15-1+deb10u1)
   qubes-mgmt-salt-vm-connector (4.0.19-1+deb10u1)
   qubes-pdf-converter (2.1.6-1+deb10u1)
   qubes-thunderbird (1.2.13-1+deb10u1)
   qubes-usb-proxy (1.0.22+deb10u1)
   pulseaudio-qubes (4.0.27-1+deb10u1)
   qubes-vm-recommended (4.0.6-1+deb10u1)

**Brief summary**
 There is a problem when trying to dist-upgrade because one of the packages related to Qubes OS wants to be removed.

**To Reproduce**
Run sudo apt-get dist-upgrade in kali linux template

**Expected behavior**
Upgrade without problems.

**Actual behavior**
 Upgrade with delete important qubes packages.

**Additional context**
In sources I have kali linux rolling repo and debian buster.
 I put the whole package list from dist-upgrade command with -V option on privatebin for the whole month

https://privatebin.net/?554666abae961846#2XkQTJNoUFEFqMa5ZYnen8QAoKwUZyuyfSGFcxcVn9Lb

**Comment by marmarek** [comment]
It looks like pulseaudio is to be updated to 13.0. Debian buster has pulseaudio 12.2, so pulseaudio-qubes for buster is linked with this version too. You may want to try swiching qubes repositories to bullseye when using kali (I think kali is based on Debian testing or even Debian unstable). But also note Debian testing/unstable is (as the name suggests) less stable than Debian buster. Specific issue you may face is `salt` package intermittent  availability (see https://tracker.debian.org/pkg/salt):
```
[2019-10-12] salt REMOVED from testing (Debian testing watch)
[2019-09-18] salt 2018.3.4+dfsg1-7 MIGRATED to testing (Debian testing watch)
[2019-09-07] salt REMOVED from testing (Debian testing watch)
[2019-09-01] salt 2018.3.4+dfsg1-7 MIGRATED to testing (Debian testing watch) 
```

**Comment by andrewdavidwong** [comment]
Closing as "not our bug." If you believe this is a mistake, please leave a comment, and we'll be happy to take another look. Thank you.
