### ISSUE TITLE
Qrexec Agent Starts Incorrectly and too Early on Windows 10 HVM

### ISSUE THREAD

**Issue by GWeck** [QubesOS/qubes-issues#5462]
**Qubes OS version**
R4.0.1 fully updated

**Affected component(s) or functionality**
Qubes Windows Tools 4.0.1.3

**Brief summary**
When starting a Windows 10 (Version 1803 or 1909) HVM with QWT installed, both Qubes services start (Qubes RPC Agent and QubesDB daemeon), but most of the time Qubes complains that it cannot connect to the qrexec agent of the VM, and functions like file copy do not work. This seems to be a timing problem, as it does not always happen.
If, however, the Qubes RPC Agent start mode is set to Manual (or even disabled) and the agent was stopped (interactively or via the command _net stop qrexecagent_) before shutting down windows, this service does not start at the next boot. If then the service is started interactively, connection to Qubes is established immediately and the full functionality is available.

**To Reproduce**
Install QWT 4.0.1.3 on a freshly installed Windows 10 Pro systemrunning as HVM under Qubes. Set _qvm-feature gui_ to 1 to get an interactive window. Set _qvm-prefs qrecec_timeout_ to a larger value (600 or so) to reduce stress.
Reboot the VM and observe its state in the Qube manager.

**Expected behavior**
The state should always turn to green, and full functionality should be availabl,e like it is on Windows 7.

**Actual behavior**
If the state stays at yellow, which happens most of the time, the qrexec channel between host and guest is not working, although the correspondig Qubes RPC Agent service in the guest is running. If, on the other hand, the state turns to green, communication is established.

**Additional context**
The Qrexec Agent starts, irrespectively of its starttype, if it was active at the last shutdown before boot - even if its starttype is set to _disabled_. If it is running, it can be shut down interactively or via the command _net stop qrexecagent_. Trying to restart the service interactively or via the command _net start qrexec agent_ crashes Windows with error 0x0000dead in xenbus.sys.
If the agent is not running at boot time, it can be started interactively. Trying to start it via the command line leads to the same crash. The VM has to be killed in order to be able to start it again.
Probably not connected to this, but still annoying: The logs complain that the RPC _qubes.SetMonitorLayout_ fails due to _File not Found_. Creating a file with this name, e.g. by copying _qubes.SetGuiMode_ under  this name, in the _qubes-rpc_ directory removes this error, but does not change the other behaviour.

**Solutions you've tried**
First set the starttype of Qubes RPC Agent to Manual. This can be done while it is running, even if there is no communication with the host system.
Before shutdown of the VM, stop the service Qubes RPC Agent.
After booting, start the service Qubes RPC Agent **interactively** - not by command, as this would crash the VM.
In most cases, you have then a fully functional system.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
Documentaion on QWT

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
Possibly #5332 and #3585

**Log files on a successful start of Qubes RPC Agent with connection to the host**
[qrexec-agent-20191115-094051-6456.log](https://github.com/QubesOS/qubes-issues/files/3851055/qrexec-agent-20191115-094051-6456.log)
[qrexec-wrapper-20191115-094051-6552.log](https://github.com/QubesOS/qubes-issues/files/3851056/qrexec-wrapper-20191115-094051-6552.log)
[qrexec-wrapper-20191115-094051-6672.log](https://github.com/QubesOS/qubes-issues/files/3851057/qrexec-wrapper-20191115-094051-6672.log)
[qubesdb-daemon-20191115-094014-2784.log](https://github.com/QubesOS/qubes-issues/files/3851058/qubesdb-daemon-20191115-094014-2784.log)

**Comment by GWeck** [comment]
If the Windows 10 VM is created as a template VM, it behaves quite the same as the HVM does. This is the same no matter whether the Xen network and disk drivers are installed or not. (If the Xen base drivers are not installed, the Qubes RPC Agent  and the QubesDB Daemon cannot run at all, like with the HVM. So these drivers have to be installed.)

So the situation is as follows:
- If the Qubes RPC Agent is started at boot time, no communication with the host is possible. This occurs if the service starttype is set to automatic or if this service was running at the previous shutdown.
- If the service is restarted, the VM will crash.
- If the service is not running at boot time, it can be started. Most of the time, communication with the host is the established, but sometimnes the VM crashes instead.

If an AppVM based on this template is created, it behaves different:
- The Qubes RPC Agent is started at boot time, if it was runnung at the last shutdown of the template VM.
- If the service is running at boot time, no host communication is possible, just like this is the case with the template VM.
- If the service is not running at boot time, the AppVM will crash whenever the service is started. It was not possible to start it in any case.

I wonder if the newer Xen drivers (version 8.2.2), which are available now, are any better than the ones (version 8.2.1) currently used by QWT. It might be worth a try, but I was not able to run QWT with the newer drivers.

**Comment by GWeck** [comment]
If the Qubes RPC Agent is started manually, and Windows 10 crashes, communication with the host system is established shortly - the status indicator in the Qube Manager turns green, and a notification _Domain <vmname> has started_ is displayed - and then the VM crashes immediately. This occurs in the HVM, the template VM and in the AppVM in exactly the same way.

If a running Qubes RPC Agent is stopped and then restarted, the crash occurs immediately without communication being established, also in all types of VM.

During my tests, I once had a template VM starting the agent at boot time - the service starttype was set to _Automatic_ - and getting communication with the host. After shutdown of this template VM, the corresponding AppVM started and had communication with the host. The AppVM could be started severeal times, and each time communication was established. After the next boot of the template VM, the situation returned to the previous behaviour, i.e. no communication was established if the service starttype was set to _Automatic_, and the AppVM would crash if the service starttype was set to _Manual_ and the agent was started manually.

This is all rather confusing, but I hope it will help to track the problem down.

**Comment by brendanhoar** [comment]
I’ll ask the silly questions first: you have 4GB assigned for both mem and maxmem and have disabled memory balancing, correct?

**Comment by GWeck** [comment]
I had both initial and max memory set to 6144 MB. Memory  balancing was on for the HVM and the template VM, and off for the AppVM.

I now changed this to initial memory 4000 MB on all VMs - max. memory stayed at 6144 MB when memory balancing was turned off  - and switched memory balancing off on all VMs. The behaviour of all machines did not change - no communication if the agent was started automatically, and a mix of correct starts and crashes if it was started manually.

However, I found a certain pattern in the crashes:
- For the HVM and the template VM, the crashes do not occur randomly but on each second boot. So, if the agent starts correctly, I may leave it running when shutting down the VM; in this case it will run after the next boot, but etstablish no communication with the host. If I stop it before shutting down the VM, it will not run after the next boot and will crash the VM if it is started, but then after the next boot, it can be started manually and will establish host communication.
- For the AppVM, the behaviour depends on what happend before with the template VM. If the template VM crashed on the previous run, the agent will start correctly after each boot - just as is to be expected for the next boot of the template VM. If the template VM ran correctly on the previous run, the AppVM wil crash on each start of the agent.

So I suppose that shutting down the agent leaves something that will crash it on the next start, and that this crash somehow clears the offending data. This seems consistent with the fact that stopping the agent and then restarting it immediately crashes the VM. Anyhow, if the agent is started automatically, it runs, but without establishing host communication.

**Comment by GWeck** [comment]
Here are some log files that might help to investigate the errors.

**Installation logs of Qubes Windows Tools**
[Qubes_Windows_Tools_4.0.1.3_20191120115727.log](https://github.com/QubesOS/qubes-issues/files/3882400/Qubes_Windows_Tools_4.0.1.3_20191120115727.log)
[Qubes_Windows_Tools_4.0.1.3_20191120115727_001_qubes_tools_WIN7x64_4.0.1.3.msi.log](https://github.com/QubesOS/qubes-issues/files/3882401/Qubes_Windows_Tools_4.0.1.3_20191120115727_001_qubes_tools_WIN7x64_4.0.1.3.msi.log)

**Logs of Qubes RPC Agent starts without crash**
[qrexec-agent-20191123-101458-6308.log](https://github.com/QubesOS/qubes-issues/files/3882403/qrexec-agent-20191123-101458-6308.log)
[qrexec-agent-20191123-101129-7124.log](https://github.com/QubesOS/qubes-issues/files/3882404/qrexec-agent-20191123-101129-7124.log)
The first file concerns a start with a dysfunctional qrexec agent, i.e. the agent is running but unable to connect to the host. The second file describes a successful start after which communication is established. The first 41 lines of both files are equivalent, i.e. up to _WatchForEvents: waiting for event_.
In line 42 of the successful start, we get _WatchForEvents: event 1_ and then see that the channel to the host is working, whereas in that line in the unsuccessful start, we get the error message _SvcCtrlHandlerEx: code: 4 0x4_, probably meaning that the service control handler got a problem, and after that, there is silence.

**Log file of Qubes RPC Agent start crashing Windows and correspondig crash dump**
[qrexec-agent-20191123-105642-6628.log](https://github.com/QubesOS/qubes-issues/files/3882406/qrexec-agent-20191123-105642-6628.log)
[112219-12312-01.zip](https://github.com/QubesOS/qubes-issues/files/3882408/112219-12312-01.zip)
In the case of the crash, the log ends with line 11, _SvcMain: start_. It is unclear whether this was the cause of the crash or if the rest of the log simply could not be flushed to disk, because the crash was too quick. I have no idea if the dump file might be of any value, but at least it is there.

**Comment by GWeck** [comment]
If the Xen bus and storage drivers Version 9.9.0 are installed in a Windows 10 system *without* Qubes Windows Tools, and QWT 4.0.1.3 are installed *after* the Xen installation has finished, the Qubes interface works correctly. Files can be exchanged with other VMs, and the common clipboard works in both directions. So to get a working Windows 10 system under Qubes R4.0, the following steps should be performed:

- Install `xenvbd` and `xenbus` Version 9.9.0 from the Xen web site.

- After installation, reboot.

- Install Qubes Windows Tools 4.0.1.3, unselecting the Xen storage driver and the Move of user data to Drive D (which would probably lead to problems in Windows, anyhow).

- Shut down Windows.

- Set qvm-features gui 1.

- Reboot Windows. The VM starts, but does not show any window.

- Shutdown Windows from the Qube manager.

- Reboot Windows once more. Now the system is up, with QWT running correctly.

For me, this sequence worked for Windows 10 as template VM, and a correspondig AppVM worked too.

It might be a good idea to create a new version of QWT, containing these updated drivers, but unfortuately I was not able to do this.

**Comment by GWeck** [comment]
Installing the version 9.0.0 Xen drivers on Windows 7 (a system witout QWT - QWT uninstalled) leads to an unbootable system. The drivers install without error, but after reboot, the system aborts the reboot saying "Missing driver xenbus.sys".

So, for Windows 7, it seems that we have to stick to the current QWT 4.0.1.3.

**Comment by brendanhoar** [comment]
My recollection is that I had good luck with the latest version of the 8.x.x drivers before 9.0, using win7 on qubes r4.0.x. That version’s Pv storage driver seems stable and allows qubes-initiated block device attaches.

**Comment by GWeck** [comment]
That is also my impression. The 9.0.0 drivers seem to be targeted to Windows 10. Currently, I have W7 running with the 8.x.x drivers and W10 with the 9.0.0 drivers, both stable.  W10 even runs on Qubes R4.1 with these drivers, as long as no data transfer to/from another VM via clipborad or file copy is attempted (see #5003).

**Comment by Sixtiz** [comment]
> If the Xen bus and storage drivers Version 9.9.0 are installed in a Windows 10 system _without_ Qubes Windows Tools, and QWT 4.0.1.3 are installed _after_ the Xen installation has finished, the Qubes interface works correctly. Files can be exchanged with other VMs, and the common clipboard works in both directions. So to get a working Windows 10 system under Qubes R4.0, the following steps should be performed:
> 
>     * Install `xenvbd` and `xenbus` Version 9.9.0 from the Xen web site.
> 
>     * After installation, reboot.
> 
>     * Install Qubes Windows Tools 4.0.1.3, unselecting the Xen storage driver and the Move of user data to Drive D (which would probably lead to problems in Windows, anyhow).
> 
>     * Shut down Windows.
> 
>     * Set `qvm-features gui 1`.
> 
>     * Reboot Windows. The VM starts, but does not show any window.
> 
>     * Shutdown Windows from the Qube manager.
> 
>     * Reboot Windows once more. Now the system is up, with QWT running correctly.

I tried this but after the reboot, no more window, and the status stays yellow in Qube Manager... Even after setting gui to 0 again... any idea?

**Comment by peru3232** [comment]
First of all: Thanks for discription on how an Win10 with QWT works! It´s nearly correct, with one exception, that cost me a lot of time. So please let  me clearification the correct way: 
You must copy the QWT Application on Systemdrive before you make the reboot after installation from the drivers on the Xen web site.
If you make the reboot without this, you can`t boot the qube with the installation disk anymore - it`s a blue screen with boot disk error.

I thought at the beginning that the instruction are crap and that doesn't work with the drivers. Until I got the idea to boot again without the install disk and é volá: that's it - only now I had to put the QWT on it differently way ... so: just copy it from the mounted disk to C: beforehand and then everything is easy !

**Comment by GWeck** [comment]
**The following is an augmented checklist of my comment from 13 Jan - thanks to peru3232 for the clarification!**

If the Xen bus and storage drivers Version 9.9.0 are installed in a Windows 10 system without Qubes Windows Tools, and QWT 4.0.1.3 are installed after the Xen installation has finished, the Qubes interface works correctly. Files can be exchanged with other VMs, and the common clipboard works in both directions. So to get a working Windows 10 system (Standalone or Template VM) under Qubes R4.0, the following steps should be performed:

- Copy the installation kits of `xenvbd `and `xenbus `Version 9.9.0  from the Xen web site and Qubes Windows Tools 4.0.1.3 to the Windows system drive (normally `C:\`.)

- Extract `qubes-tools-4.0.1.3.exe` from the QWT installation media, and store it on the Windows system disk.

 - Install `xenvbd `and `xenbus `Version 9.9.0.

 - After installation, reboot. without the installation disk.

 - Install Qubes Windows Tools 4.0.1.3 by starting `qubes-tools-4.0.1.3.exe,` unselecting the `Xen storage driver` and the `Move of user data to Drive D` (which would probably lead to problems in Windows, anyhow).

 - Shut down Windows.

 - Set qvm-features gui 1.

 - Reboot Windows. The VM starts, but does not show any window.

 - Shutdown Windows from the Qube manager.

 - Reboot Windows once more. Now the system is up, with QWT running correctly.

For me, this sequence worked for Windows 10 as Template VM, and a correspondig AppVM worked too.

- After installation of Windows as a Template VM, the Windows disk manager may be used to add the private volume as disk `D:`, and you may, using the doumented Windows operations, move the user directories `C:\users\<username>\Documents` to this new disk, allowing depending AppVMs to have their own private volumes. Moving the hidden application directories `AppData`, however, is likely to invite trouble - the same trouble that occurs if, during QWT installation, the option `Move of user data` is selected.

It might be a good idea to create a new version of QWT, containing these updated drivers, but unfortuately I was not able to do this. QWT probably will need the version 8 drivers for Windows 7, and the verion 9 drivers for Windows 10, so both versions may be needed in order to support both versions of Windows.

**Comment by AlexW13** [comment]
Is there a working GUI driver yet for Windows 10?  After using QWecks install method, I am getting a xen incompatible Display driver.

**Comment by rastababy** [comment]
Hey, First of all very much thank for ur description.  Just a silly beginner question: It isn't possible to start apps like "word" in seamless mode in windows10, like u can do it in win7, or is it?

and a second question to my win7 hvm : if if start a app in terminal qvm-run -a win7 word.exe for exampl it says :command failed with code: 49 -just a few less apps like explorer.exe will start, but maybe that don't work? If i run the programm from the "start menu" in qubes then it starts. But there I don't know how to add a shortcut to the startmenu that is not in the list, because I  cannot enter the terminal in a Windows hvm and don't know how to create a .desktop file for the winhvm;) 

I hope and think that somebody can help me here and I can fix some problems soon.
Thank u so far!

**Comment by GWeck** [comment]
As far as I read the discussion concerning QWT, currently there is no way to use seamless mode with Windows 10. See #3585 and #5332.

**Comment by andrewdavidwong** [comment]
@rastababy, please do not ask off-topic questions on issues. See our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/) for more information. We ask that you please send any help or support questions to the `qubes-users` [mailing list](https://www.qubes-os.org/support/) instead. Thank you for your understanding.

**Comment by keldnorman** [comment]
> Installing the version 9.0.0 Xen drivers on Windows 7 (a system witout QWT - QWT uninstalled) leads to an unbootable system. The drivers install without error, but after reboot, the system aborts the reboot saying "Missing driver xenbus.sys".
> 
> So, for Windows 7, it seems that we have to stick to the current QWT 4.0.1.3.

Should the Install xenvbd and xenbus Version 9.9.0 be version 9.0.0 ?! I cant find any version 9.9.0 .. link please :) ?

**Comment by GWeck** [comment]
The version really is 9.0.0 - these were typing error which I have now corrected

**Comment by GWeck** [comment]
The installation of QWT in Windows 10 is now covered by the Qubes documentation for Windows installation and Qubes Windows Tools. 

Closing this issue as it is no longer needed.

**Comment by rastababy** [comment]
Hello, first of all sorry for my off topic post. I try to do it better in the future and was new here. But no problem:)
I followed this documentation from GWeck and in the qubes documentation last week, but I have no chance to see a gui after installing qwt in the Win10 TemplateVM. I think it is a problem with new WIndows 10 H2 october update. If I choose a Windows H1 Version and don't update the last function update then it is working. Do u know how to fix that?
And an other problem I got is, if I create an AppVM based on that template, then everything is working but I cannot access the Internet in that VM. At booting it looks fine, but then it switches to that "world-ball" and says I am not connected to the internet. I tried installing xennet drivers,too and several things, but cannot find a solution. If u can help my, I will be very thankful.
Stay healthy lovely community.

**Comment by GWeck** [comment]
I'll have a look at W10 20H2, but this may take some days. So far, I have not updated my VM.

With regard to internet access, I have sometimes found that Windows changes the IP address for its network interface, and if that is different from the address seen in Qubes (in the Qube manager), no network access is possible. Could you check the address assigned to the network adapter in your AppVM? If it is the same as in the template, the AppVM will not be able to connect to the internet.

**Comment by GWeck** [comment]
I just upgraded W10 from 1909 to 20H2. In the first attempt, it crashed during installation of the upgrade, due to qrexec timeout. This can be fixed by setting `qvm-features <VMname> qrexec -D` before performing the upgrade, working through half a dozen reboots, and then restoring `qvm-features <VMname> qrexec 1`. The resulting VM (template and corresponding AppVM) works normally, without any gui trouble, but the Windows defender firewall seems to block too much traffic. So there's more work in this area ...

**Comment by blobless** [comment]
@rastababy I had the same networking issue occur. @GWeck I also experienced the qrecec_timeout several times when trying to start the VM. None of this has happened with subsequent fresh installations of Windows 10.

**Comment by Kenny606** [comment]
This may be worhwhile information to a newb like me or it may be a waste of space in the comments...

There may have been an easier way to do this but after a clean install of 20H2 I had no NIC (literally no NIC in windows)
I thought it may be something specific to the newer release and 1909 had been able to make use of the NIC on a clean install.

I'm new to Qubes so I'm sure there may have been other ways to do this but....
I ended up just using WinISO on my other machine to throw the Xen 9.0 drivers and QWT setup file into an ISO.
Then starting the VM with the CDROM switch pointing to that ISO sitting on untrusted so I could access the drivers on the ISO.
After everything was installed I had a working including the NIC.

I'm working on building the template VM and then hopefully an AppVM now.
I guess somewhat unrelated but you had mentioned it above.
I know how to move the users properly with SysPrep, however it kept failing as on the standalone VM as Drive 2 kept getting wiped. Hence Sysprep couldn't see it anymore when it tried to move the folder to D:\Users. I'm not sure if I missed a parameter on the standalone VM's settings to make that drive persistent?
Hopefully as a template VM I'll have better luck, but I'll clone this template before trying.... as I did the standalone thankfully.

Thanks for posting all this info I'm going to move away from Windows as I possibly can. 
However due to work work related needs I have a lot of administrative tools that HAVE to function and on Windows 10 or Qubes is a no go for me.

**Comment by cbmiller2610** [comment]
@Kenny606 does attaching a USB device to the Windows VM work with your setup? USB is not working for me on 20H2 using the automated QWT installer, but I figure that might be because it's using the older PV drivers.

**Comment by GWeck** [comment]
@cbmiller2610 In my configuration, attaching a USB stick to Windows 10 worked. Configuration:

- Qubes R4.04 fully updated with kernel 5.11.8
- QWT 4.0.1.3 with Xen PV Bus Package 9.0.0.2 and Xen PV Storage Host Adapter 9.0.0.3 installed prior to QWT
- using sys-usb under Fedora 33
- Windows 10 20H2 Professional

Other devices (camera, microphone) cannot be attached in this configuration.

Ih hope this helps somewhat.

**Comment by cbmiller2610** [comment]
Thanks! This does help. After doing some more reading it seems that although your use case (flash drive) works, my use case (USB audio) is probably not supported with the Windows Xen PV drivers. See bottom of this page https://wiki.xenproject.org/wiki/Xen_USB_Passthrough. Currently, it seems that the best solution for full USB support in a Windows guest is to pass through the entire USB controller via PCI pass through.

**Comment by brendanhoar** [comment]
> Currently, it seems that the best solution for full USB support in a Windows guest is to pass through the entire USB controller via PCI pass through.

I concur. That is what I usually do. 

Luckily the laptops I use were older transition-period laptops so they have separate usb 2.0 and usb 3.0 controllers (comes in handy for this issue).

B

**Comment by GWeck** [comment]
@cbmiller2610 Audio is somewhat supported und Qubes R4.1, but otherwise, Windows support still has some problems there. See [Testing Windows and QWT in R4.1](https://qubes-os.discourse.group/t/testing-windows-and-qwt-in-r4-1/1143).

**Comment by GWeck** [comment]
Probably no longer relevant. There is now the new version 4.1-65 of QWT, and some of the effects described here are caused by Windows 10 normally not shutting down but just hibernating, which can be corrected by setting `powercfg -h off`, which makes the qrexec start correctly.
