### ISSUE TITLE
Can't join mailinglist captcha

### ISSUE THREAD

**Issue by deeplow** [QubesOS/qubes-issues#5465]
**Brief summary**

Can't join mailinglist though tor because google blocks tor users. I've been trying to join it for a while but google always blocks me. I'm not willing to connect without Tor.

**To Reproduce**

1. Be on Tor browser
2. subscribe to qubes-users mailinglist by sending an empty email to `qubes-users+subscribe@googlegroups.com`
3. click on `Join this group`
4. do captcha
5. See error "Your computer or network may be sending automated queries"

**Expected behavior**
> "Success! You've subscribed to the mailing list. You can now participate in discussions"

**Actual behavior**
> Your computer or network may be sending automated queries. To protect our users, we can't process your request right now. For more details visit our help page

**Screenshots**

![qubes-captcha](https://user-images.githubusercontent.com/47065258/68976323-75031000-07ed-11ea-9954-f31fd5b90e07.png)

**Solutions you've tried**
- Switching tor circuit.
- Doing it in different months

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
- https://www.qubes-os.org/support/#qubes-devel

**Other comments**
I get the argument that qubes distrusts the infrastructure

> The Google Groups service is just free infrastructure, and we distrust the infrastructure. 
>
> -- https://www.qubes-os.org/support/#mailing-lists-vs-forums

But this distrust of the infrastructure, may be blocking users from participating in the community. Is there any other way to subscribe to the mailinglist (maybe via email only)?

**Comment by marmarek** [comment]
You don't need to use web interface to join the mailing list. You can use any email account and send message to appropriate address. See https://www.qubes-os.org/support/#qubes-users for instructions.

**Comment by deeplow** [comment]
You're right. I misread the email. I can just reply to it and I'm immediately registered.

Sorry for the trouble!
