### ISSUE TITLE
fedora template should have qubes user be a member of the video group (for webcams / cameras)

### ISSUE THREAD

**Issue by Osndok** [QubesOS/qubes-issues#5468]
**Qubes OS version**
This was seen in the `fedora-29` template. I do not know if it has been fixed in later templates.

**Affected component(s) or functionality**
The user cannot initially use video devices without some special knowledge or help with a trivial fix.

**Brief summary**
The `user` user does not have permission to access the `/dev/video` device.

**To Reproduce**
_Steps to reproduce the behavior:_
1. Launch a fedora-templated vm
2. Attach a USB webcam to that qube
3. In that qube, type `id` into a terminal.
```
uid=1000(user) gid=1000(user) groups=1000(user),98(qubes)
```
4. Notice that `user` is not a member of the `video` group
5. type `ls -lat /dev/video?`
```
crw-rw----+ 1 root video 81, 1 Nov 16 07:46 /dev/video1
crw-rw----+ 1 root video 81, 2 Nov 16 07:46 /dev/video2
```
6. notice that only `root` and the `video` group may access this device

**Expected behavior**
Webcams are quite common and should be usable "out of the box".

**Actual behavior**
`Permission denied`

**Workaround**

Run this in your template, shut it down, and then re-start your qube:
```
sudo usermod -a -G video user
```
After that, you should be able to use your webcam in any qube derived from that template.

I'm not sure which qubes package this should be persisted in, but it's an easy fix for me...

I have also encountered a secondary issue with webcams >=8 megapixel related to the default buffer size, but I think that `cheese` is immune to that one.

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
* #4035

**Comment by marmarek** [comment]
> crw-rw----+ 1 root video 81, 1 Nov 16 07:46 /dev/video1
> crw-rw----+ 1 root video 81, 2 Nov 16 07:46 /dev/video2

The "+" sign means there are some ACLs set, you can see them with `getfacl` tool. udev/logind should automatically give `user` access to those devices, as `user` is logged in a "local, active session" and logind does the magic, without any extra steps like being in `video` group.

This mechanism was greatly improved in https://github.com/QubesOS/updates-status/issues/799

So, a few questions:
1. Do you have qubes-gui-agent >= 4.0.19 ?
2. Do you see `user` access in `getfactl /dev/video1` output?
3. If not, can you confirm that `loginctl show-session` does include `Active=yes` and `Remote=no`?

**Comment by Osndok** [comment]
> This mechanism was greatly improved in [QubesOS/updates-status#799](https://github.com/QubesOS/updates-status/issues/799)

If you are confident that this issue has been fixed, feel free to close this report, as adding `user` to the `video` group is sufficient for my purposes.

>     1. Do you have qubes-gui-agent >= 4.0.19 ?

Yes.
```
$ rpm -q qubes-gui-agent
qubes-gui-agent-4.0.27-1.fc30.x86_64
```

>     2. Do you see `user` access in `getfactl /dev/video1` output?

I don't really know how to interpret this, but I think the answer is yes.
```
$ getfacl /dev/video1
# file: dev/video1
# owner: root
# group: video
user::rw-
user:user:rw-
group::rw-
mask::rw-
other::---
```

>     3. If not, can you confirm that `loginctl show-session` does include `Active=yes` and `Remote=no`?
It does not.
```
$ loginctl show-session | egrep -i '(Active|Remote)'
<no output>
```

**Comment by marmarek** [comment]
> user:user:rw-

Yes, this means the `user` user do have access to the device.

> $ loginctl show-session | egrep -i '(Active|Remote)'
> <no output>

That's weird, `loginctl show-session` output should look like this:
```
EnableWallMessages=no
NAutoVTs=6
KillUserProcesses=no
RebootToFirmwareSetup=no
IdleHint=no
IdleSinceHint=0
IdleSinceHintMonotonic=0
DelayInhibited=sleep
InhibitDelayMaxUSec=5s
UserStopDelayUSec=10s
HandlePowerKey=poweroff
HandleSuspendKey=suspend
HandleHibernateKey=hibernate
HandleLidSwitch=suspend
HandleLidSwitchDocked=ignore
HoldoffTimeoutUSec=30s
IdleAction=ignore
IdleActionUSec=30min
PreparingForShutdown=no
PreparingForSleep=no
Docked=no
LidClosed=no
OnExternalPower=yes
```

Anyway, that's irrelevant for this issue, as device permissions are properly set. Can you verify on what exactly device you've got `Permission denied` message? If application itself don't tell you this, you can run it through strace (`strace -o log-file-name application-name`) and search the log for `EACCESS` errors.
