### ISSUE TITLE
Debian10 - removing qubes-core-agent-passwordless-root

### ISSUE THREAD

**Issue by akkuladezeit** [QubesOS/qubes-issues#5469]
**Qubes OS version**
R4.0 - Debian10 

**Affected component(s) or functionality**
removing qubes-core-agent-passwordless-root

**Brief summary**
i just installed the Debian10 and started doing my hardening stuff.. 
first step removing the passwordless-root

**To Reproduce**
start xterm for Dom0 with rub
_1. qvm-run -u root debian-10 xterm
_2. apt-get remove qubes-core-agent-passwordless-root

**Expected behavior**
_packet gets removed_

**Actual behavior**
_Error during removing user for group sude_
_user user is not a member of sudo_

**Solutions you've tried**
_i added user to group sudo before uninstall and didnt worked._
_usermod -aG sudo user_
package is removed but passwordless is still active

**Comment by andrewdavidwong** [comment]
Have you read this page? https://www.qubes-os.org/doc/vm-sudo/

**Comment by akkuladezeit** [comment]
no not yet but should this not be removed or set to default after removing the package?
