### ISSUE TITLE
Improvemement to the Installation Guide

### ISSUE THREAD

**Issue by luzeal** [QubesOS/qubes-issues#5471]
**The problem you're addressing (if any)**

Sorry for the long silence. I have busy working on a new Installation Guide. 

Right now, [the page explaining](https://www.qubes-os.org/doc/installation-guide/) the installation of Qubes OS on a new computer doesn't illustrate how the installation unfolds. 

**Describe the solution you'd like**

Illustrating these steps might be beneficial to new and former users alike. It well help them pick the set of options best suited to their specific needs and will help users avoid common pitfalls. I am about to send those changes. 

Some questions remain :

* Does Rufus with DD work with EFI and non-EFI systems ?
* Should Secureboot be deactivated in every case ? 
* Post-installation, the user may pick an option as a sub-element of : *Create USB qube holding all USB controllers*. 
    * What does *Use sys-net qube for both networking and USB devices* mean? Why would one check this ? (It is unchecked by default.)

Thanks for your attention. I look forward to receiving your feedback.

Lukas

**Comment by luzeal** [comment]
FYI : This issue is part of the [Season of Docs](https://developers.google.com/season-of-docs/) project.

**Comment by andrewdavidwong** [comment]
This was completed a long time ago. Looks like the issue was just forgotten.
