### ISSUE TITLE
4.1 builder fails on core-libvirt

### ISSUE THREAD

**Issue by JarrahG** [QubesOS/qubes-issues#5474]
**Qubes OS version**

Builder 4.1 on 4.0 system.
**Affected component(s) or functionality**

core-libvirt
**Brief summary**

The build of core-libvirt fails.
**To Reproduce**
_Steps to reproduce the behavior:_
_1. Go to '...'_
_2. Click on '....'_
_3. Scroll down to '....'_
_4. See error_
1. Clone qubes-builder
2. Run setup and select 4.1. Other options such as repositories, templates, etc don't change the outcome.
3. make install-deps
4. make get-sources
5. make qubes
    - Fails on core-libvirt

**Expected behavior**

Build completes to ISO building.
**Actual behavior**

Build fails on core-libvirt
**Console Output**

```
make[1]: Entering directory '/home/user/qubes-builder'
-> Building core-libvirt (libvirt.spec) for fc29 dom0 (logfile: build-logs/core-libvirt-dom0-fc29.log)
--> build failed!
make[2]: Entering directory '/home/user/qubes-builder'
/home/user/qubes-builder/qubes-src/builder-rpm/scripts/generate-spec /home/user/qubes-builder/chroot-dom0-fc29/home/user/qubes-src/core-libvirt/libvirt.spec.in /home/user/qubes-builder/chroot-dom0-fc29/home/user/qubes-src/core-libvirt/libvirt.spec
/home/user/qubes-builder/qubes-src/builder-rpm//update-local-repo.sh fc29
sudo BACKEND_VMM=xen  chroot /home/user/qubes-builder/chroot-dom0-fc29 sh -c 'cd /home/user/qubes-src/core-libvirt; dnf  --refresh -y update'
Qubes OS Builder Repository                     2.9 MB/s | 3.0 kB     00:00    
Qubes OS Builder Repository                      21 MB/s |  22 kB     00:00    
Fedora Modular 29 - x86_64                      3.1 kB/s | 2.8 kB     00:00    
Fedora Modular 29 - x86_64 - Updates             35 kB/s |  37 kB     00:01    
Fedora 29 - x86_64 - Updates                     42 kB/s |  39 kB     00:00    
Fedora 29 - x86_64                              5.0 kB/s | 2.8 kB     00:00    
Dependencies resolved.
Nothing to do.
Complete!
sudo BACKEND_VMM=xen  chroot /home/user/qubes-builder/chroot-dom0-fc29 bash -c 'cd /home/user/qubes-src/core-libvirt; dnf builddep --spec  -y libvirt.spec'
Qubes OS Builder Repository                     2.9 MB/s | 3.0 kB     00:00    
sh: hostname: command not found
Package perl-podlators-1:4.12-1.fc29.noarch is already installed.
Package autoconf-2.69-28.fc29.noarch is already installed.
Package automake-1.16.1-7.fc29.noarch is already installed.
Package gawk-4.2.1-3.fc29.x86_64 is already installed.
Package gcc-8.3.1-2.fc29.x86_64 is already installed.
Package gettext-0.19.8.1-18.fc29.x86_64 is already installed.
Package git-2.20.1-1.fc29.x86_64 is already installed.
Package gnutls-devel-3.6.7-1.fc29.x86_64 is already installed.
Package libblkid-devel-2.32.1-1.fc29.x86_64 is already installed.
Package libnl3-devel-3.4.0-6.fc29.x86_64 is already installed.
Package libtasn1-devel-4.13-5.fc29.x86_64 is already installed.
Package kmod-25-3.fc29.x86_64 is already installed.
Package ncurses-devel-6.1-8.20180923.fc29.x86_64 is already installed.
Package perl-interpreter-4:5.28.2-435.fc29.x86_64 is already installed.
Package python3-3.7.5-1.fc29.x86_64 is already installed.
Package systemd-devel-239-14.git33ccd62.fc29.x86_64 is already installed.
Package systemd-239-14.git33ccd62.fc29.x86_64 is already installed.
Package util-linux-2.32.1-1.fc29.x86_64 is already installed.
Package yajl-devel-2.1.0-11.fc29.x86_64 is already installed.
Error: 
 Problem: conflicting requests
  - nothing provides xen-libs = 4.12.1-2.fc29 needed by xen-devel-2001:4.12.1-2.fc29.x86_64
(try to add '--skip-broken' to skip uninstallable packages)
make[2]: *** [/home/user/qubes-builder/qubes-src/builder-rpm/Makefile-legacy.rpmbuilder:65: dist-build-dep.spec] Error 1
```
**Additional context**

Building only to test whether the following issues would be solved by 4.1 (xen 4.12):
* https://github.com/QubesOS/qubes-issues/issues/5416
* https://github.com/QubesOS/qubes-issues/issues/5422

**Solutions you've tried**

* Add/remove the current and current-testing repos
* git clone faster to both yes and no.
* fresh clone of repository.
* fresh download of sources.
**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

https://www.qubes-os.org/doc/qubes-builder/
https://www.qubes-os.org/doc/qubes-iso-building/

**Comment by marmarek** [comment]
I hit this issue too, I'll push the fix on Friday.
In the meantime, you can fix this yourselves: in `qubes-src/vmm-xen/xen.spec.in` look for dependencies with `= %{version}-%{release}` and change that to `= %{epoch}:%{version}-%{release}`. But I think there were more issues...

**Comment by JarrahG** [comment]
I can confirm that the above solution fixes the builder issue, though a simple find/replace doesn't. There are some places in the file that contain the correct `%{epoch}:%{version}-%{release}`. 

I have also come across an issue with the ISO builder. The EFI boot image it produces is too large:
```
Complete!
-> Building installer-qubes-os iso for fc29 (logfile: build-logs/installer-qubes-os-iso-fc29.log)...
--> build failed!
  File "/usr/lib/python3.7/site-packages/pylorax/executils.py", line 349, in runcmd_output
    return execWithCapture(cmd[0], cmd[1:], **kwargs)
  File "/usr/lib/python3.7/site-packages/pylorax/executils.py", line 251, in execWithCapture
    reset_handlers=reset_handlers, reset_lang=reset_lang)[1]
  File "/usr/lib/python3.7/site-packages/pylorax/executils.py", line 203, in _run_program
    raise subprocess.CalledProcessError(proc.returncode, argv, output)
subprocess.CalledProcessError: Command '['sh', '-x', '-c', '[ $(stat -c %s /home/user/qubes-src/installer-qubes-os/work/20191121/x86_64/os/images/efiboot.img) -le 33554432 ]']' returned non-zero exit status 1.
```

This seems to come from `./chroot-dom0-fc29/home/user/qubes-src/lorax-templates/templates/efi.tmpl`, which contains the following warning:
"# verify if the image is under 32MB (max size of boot image on iso9660)"

**Comment by marmarek** [comment]
If legacy boot is enough for you, then simply comment out this check. If not, there is a set of PRs working around this limitation, linked to this issue: https://github.com/QubesOS/qubes-issues/issues/4902

**Comment by fepitre** [comment]
Have a look on this PR https://github.com/QubesOS/qubes-vmm-xen/pull/66. I encountered this problem when building CentOS 8 few weeks ago. You can cherry-pick the commit.

**Comment by githubhun1** [comment]
I have also tried to build an R4.1 iso, which was OK - after @marmarek epoch fix to the builder scripts.  I also did not run into the EFI boot image large size issue.  However, after installing the iso I cannot start any HVMs, because I get this error message:
...libxl: libxl_dom.c:996:libxl__load_hvm_firmware_module: failed to read BIOS file: No such file or directory....
It might not be connected directly to the core-libvirt package, but rather to vmm-xen package, but I suspect this could be also python3 and EFI related. Are the guests now using EFI boot in R4.1-pre-release versions?
For Qubes, I don't use EFI boot (corebooted system), but I guess it is not strictly necessary to have EFI boot on the host, while having EFI booted guests right?
It might be a simple missing symlink, but so far I cannot find a solution to fix the HVM issue.

**Comment by marmarek** [comment]
> .libxl: libxl_dom.c:996:libxl__load_hvm_firmware_module: failed to read BIOS file: No such file or directory....

That's weird, I haven't seen this issue yet. But it sounds like missing `seabios-bin` package. Try installing it (copying rpm manually from fc29 repositories?).

**Comment by marmarek** [comment]
> Are the guests now using EFI boot in R4.1-pre-release versions?

No.

**Comment by marmarek** [comment]
> For Qubes, I don't use EFI boot (corebooted system), but I guess it is not strictly necessary to have EFI boot on the host, while having EFI booted guests right?

No, legacy should work just fine. And also I don't think coreboot supports EFI at all.

**Comment by githubhun1** [comment]
Thanks for the quick answers. Interestingly, even though the files are already there at /usr/share/qemu-xen/qemu/ folder (especially bios-256k.bin) there is still a problem with the path..
I had a previous build from around 23rd Sept, which was fully working (...until the guivm property appeared..) so I decided to make a new build (...now I see that guivm should point to dom0 for the time being). I still have the xen rpms from that build, but I cannot roll back as there were commits since then, which are preventing me to do so.  Especially, the Xen ABI versions are different (4.11 vs. 4.12) and also there were some python3 patches since late Sept.  I'll try to figure out what the problem could be.
Just a side note why I'm doing all of this: I would like to have a stable enough version of R4.1 with a working guivm, so that I can experiment on passing through my amd gpus to the guivm, which is not as straightforward as I assume the intel gpus will be.

**Comment by marmarek** [comment]
> I would like to have a stable enough version of R4.1

I don't want to discourage you, but there are few major changes still planned for R4.1:
 - dom0 update to fc31
 - Xen 4.13 (when released, early Dec)

As for testing fresh install of R4.1, I haven't done it for ~month - only updated my test machine. @fepitre did you tried fresh install recently? And running HVM?

> experiment on passing through my amd gpus to the guivm, which is not as straightforward as I assume the intel gpus will be.

I'm afraid you would be surprised about the intel ones...

**Comment by fepitre** [comment]
I did a fresh install three weeks ago but only PVH/PV as i'm into KVM for testing PCI passthrough.

**Comment by githubhun1** [comment]
A quick feedback: HVM is working now. The seabios-bin package in dom0 it didn't get installed for me from the ISO. In R4.0.x the location for the bios files is /usr/share/qemu-xen/qemu/. In current R4.1 build HVMs work only if the bios files are in /usr/share/seabios/. Maybe some of the scripts need some fixing.
Anyways, thanks for the help!

**Comment by JarrahG** [comment]
I can confirm that the above fixes worked, both for the `xen.spec.in` file (now included by default, thanks Marmarek) and the grub-efi change. Changing both the `qubes-anaconda` and `lorax-templates` repos to the `marmarek/grub-efi` branch and commenting out the offending line in `lorax-templates/templates/efi.tmpl` results in a bootable system on both legacy and EFI.

Considering that this solves the problem, can I ask whether 4.0 and 4.1 are backup compatible and whether update repos are working for 4.1? I'm assuming that I'd have to do a reinstall to get a final version of 4.1, potentially also for the major updates discussed above, but in the interim I'm happy with a less stable system if it supports the new hardware. Happy to provide bug reports as updates come out.

**Comment by marmarek** [comment]
> Considering that this solves the problem, can I ask whether 4.0 and 4.1 are backup compatible 

Backup tool is backward compatible - you can restore 4.0 backup on 4.1. In fact, you can restore any Qubes >= 2.0 backup (if I remember correctly) on the current Qubes version. But the other direction isn't guaranteed. The same applies to VM format/interface (templates/standalone especially).

> and whether update repos are working for 4.1?

Until release candidate phase, 'current' aka stable repos are empty. But packages are uploaded to 'current-testing'. 

> I'm assuming that I'd have to do a reinstall to get a final version of 4.1, potentially also for the major updates discussed above, but in the interim I'm happy with a less stable system if it supports the new hardware. Happy to provide bug reports as updates come out.

In the final version we plan to support in-place upgrade 4.0 -> 4.1 too. But that hasn't been tested yet.

**Comment by JarrahG** [comment]
> Backup tool is backward compatible - you can restore 4.0 backup on 4.1. In fact, you can restore any Qubes >= 2.0 backup (if I remember correctly) on the current Qubes version. But the other direction isn't guaranteed. The same applies to VM format/interface (templates/standalone especially).
> Until release candidate phase, 'current' aka stable repos are empty. But packages are uploaded to 'current-testing'.
Good to know. I'll give 4.1 a proper shot shortly. 

Closing as the compile issue is resolved using the steps outlined above.
