### ISSUE TITLE
qubes-input-proxy-sender package should depend on qubes-usb-proxy

### ISSUE THREAD

**Issue by imjustmatthew** [QubesOS/qubes-issues#5476]
**The problem you're addressing (if any)**
After installing qubes-input-proxy-sender in a new sys-usb VM it's possible to show USB devices available for attachment, but the actual process fails unless qubes-usb-proxy is also installed in the sys-usb VM. For example, this happens when following the existing fedora-minimal template setup documentation to create a sys-usb.

**Describe the solution you'd like**
Make the package for qubes-input-proxy-sender depend on qubes-usb-proxy since it's useless to be able to list devices that cannot be attached.

While the documentation can also be improved (and I've submitted a pull request to do that) I don't see why it would ever be appropriate to have qubes-input-proxy-sender installed without qubes-usb-proxy and therefore think the proper long-term solution is to create a package dependency.

**Comment by marmarek** [comment]
qubes-input-proxy-sender and qubes-usb-proxy are a different things. Input proxy is about using input devices (mouse, keyboard etc) without connecting the actual USB device anywhere else, while qubes-usb-proxy is about connecting USB devices to other VMs.
While in many cases it makes sense to install them both on sys-usb, they don't really depend on each other.

**Comment by imjustmatthew** [comment]
So if I'm understanding you correctly, in the docs for building a minimal temaplte it should suggest qubes-usb-proxy for a sys-usb and then qubes-input-proxy-sender only if a USB mouse or keyboard are needed?

**Comment by marmarek** [comment]
Yes, that would make sense too.
