### ISSUE TITLE
Restore of large VM to large pool fails with errors in /var/tmp

### ISSUE THREAD

**Issue by clayt0nk** [QubesOS/qubes-issues#5478]
**Qubes OS version**
R4.0 on both machines

**Affected component(s) or functionality**
Qubes Backup Restore

**Brief summary**
Trying to restore a large VM from machine one to a large pool on machine two failed.

**To Reproduce**
_Steps to reproduce the behavior:_
_1. backup a large_VM on machine one
_2. set default_pool to a pool with AMPLE space on machine two
_3. restore large_VM on machine two
_4. backup reports non recoverable errors and aborts

**Expected behavior**
A large VM is restorable to a large pool without error on machine two.

**Actual behavior**
Fails due to errors while processing intermediate files in /var/tmp of a SMALL pool on machine two

**Screenshots**
![Screenshot_2019-11-22_13-42-27](https://user-images.githubusercontent.com/3198617/69477364-6685ab80-0e20-11ea-9aa1-944dfd869127.png)

In the screenshot, note in the Dom0 terminal that the q40crypto-dash VM is correctly going to the big pool called "platter" which has multiples of the required free space.

Note in the Restore Qubes window that there are problems with /var/tmp which is on the much smaller lvm pool

Note the "Disk usage warning" indicating that pool lvm, where dom0 is locate, is running out of space. This is a thin pool so based on other people's experience of destroyed Qubes installations, I would consider this to be a very dangerous situation. For that reason I do not plan on knowingly reproducing this problem.

**Additional context**
Two machines, both with dom0 / root on a small SSD, and a much bigger non-SSD hard disk for, in some cases, very, very big VMs. It should be possible to backup and restore these big VMs within Qubes, but maybe not yet? I am not sure whether this is something Qubes cannot do yet, or should do and something is broken.

**Solutions you've tried**
What I have done up until present is manually rebuild these big VMs, which is time-consuming and tedious, so I thought I would try the fitted backup / restore this time.

It also occurs to me that it would be able to nice to be able sym link /var/tmp somewhere else, but Qubes' lvm / lvm_thin file system is so complicated I have no idea if or where I can do that safely.

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

https://github.com/QubesOS/qubes-issues/issues/1652
This discussion of a way to avoid using /var/tmp entirely seems topical. I am thinking an option would be nice. Do the nice, safe, debuggable restore via /var/tmp for small VMs. For whale-sized VMs, lets not use /var/tmp.

Update: I just freed up space on my SSD lvm pool SSD and redid the restore, same backup file. It worked this time, so there is nothing wrong with the file.

**Comment by a-barinov** [comment]
After facing the same problem and doing quite a bit of research I found the reason for that. If I do backup to a fast medium (e.g. ssd) things work ok. If I do backup to a slow medium (usb 2 hdd or over network) then my backup size become smaller (can be as bad as 25Gb turning into 4Gb over very slow network connection) and large vm get affected (not restoring from that backup) while small vms are ok.

I tried changing qubes.Backup replacing 'cat > $TARGET' with 'dd obs=10240000 of=$TARGET' and things become better but 20Gb+ vms are still not backed up properly. So the problem is linked to qubes (xen?) vm interconnect mechanism.

As a side note, obs=10240000 crashes dom0 unless it has 2Gb of memory allocated (I usually run it with 768Mb) which is surprising as we are talking about 10Mb buffer. Sort of confirms this is an inter-vm issue.

**Comment by hexagonrecursion** [comment]
> After facing the same problem and doing quite a bit of research I found the reason for that. If I do backup to a fast medium (e.g. ssd) things work ok. If I do backup to a slow medium (usb 2 hdd or over network) then my backup size become smaller (can be as bad as 25Gb turning into 4Gb over very slow network connection) and large vm get affected (not restoring from that backup) while small vms are ok.
> 
> I tried changing qubes.Backup replacing 'cat > $TARGET' with 'dd obs=10240000 of=$TARGET' and things become better but 20Gb+ vms are still not backed up properly. So the problem is linked to qubes (xen?) vm interconnect mechanism.
> 
> As a side note, obs=10240000 crashes dom0 unless it has 2Gb of memory allocated (I usually run it with 768Mb) which is surprising as we are talking about 10Mb buffer. Sort of confirms this is an inter-vm issue.

This sound different from what OP is experiencing. At the bottom he says (emphasis mine):

> Update: I just freed up space on my SSD lvm pool SSD and redid the restore, same backup file. It worked this time, so **there is nothing wrong with the file**.
