### ISSUE TITLE
Outdated signatures on qsb-002-2012.txt and qsb-023-2015.txt in qubes-secpack git

### ISSUE THREAD

**Issue by kocmo** [QubesOS/qubes-issues#5479]
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
qubes-secpack GitHub repository

**Brief summary**
None of signatures on QSBs/qsb-002-2012.txt and QSBs/qsb-023-2015.txt verify

**To Reproduce**
$ gpg --verify ./QSBs/qsb-002-2012.txt.sig.joanna  ./QSBs/qsb-002-2012.txt
gpg: Signature made Mon 05 Jan 2015 08:20:18 PM UTC
gpg:                using RSA key 0x4E6829BC92C7B3DC
gpg: BAD signature from "Joanna Rutkowska (Qubes Security Pack Signing Key) <joanna@invisiblethingslab.com>" [unknown]

$ gpg --verify ./QSBs/qsb-002-2012.txt.sig.marmarek ./QSBs/qsb-002-2012.txt
gpg: Signature made Mon 05 Jan 2015 08:12:52 PM UTC
gpg:                using RSA key 0xD655A4F21830E06A
gpg: BAD signature from "Marek Marczykowski-Górecki (Qubes security pack) <marmarek@invisiblethingslab.com>" [unknown]

$ gpg --verify ./QSBs/qsb-023-2015.txt.sig.joanna ./QSBs/qsb-023-2015.txt
gpg: Signature made Thu 17 Dec 2015 12:10:12 PM UTC
gpg:                using RSA key 0x4E6829BC92C7B3DC
gpg: BAD signature from "Joanna Rutkowska (Qubes Security Pack Signing Key) <joanna@invisiblethingslab.com>" [unknown]

$ gpg --verify ./QSBs/qsb-023-2015.txt.sig.marmarek ./QSBs/qsb-023-2015.txt
gpg: Signature made Thu 17 Dec 2015 11:58:39 AM UTC
gpg:                using RSA key 0xD655A4F21830E06A
gpg: BAD signature from "Marek Marczykowski-Górecki (Qubes security pack) <marmarek@invisiblethingslab.com>" [unknown]

**Additional context**
According to git log, it looks like QSBs/qsb-002-2012.txt and QSBs/qsb-023-2015.txt were updated later on but weren't re-signed, thus their signature files became stale and don't verify anymore. Doesn't look like foul play :-) (Well, I hope it's not a subtle hint that Qubes has been compromised and canary has been blown.)

Last time both signatures on QSBs/qsb-002-2012.txt verified successfully was commit 77c185131e6b3422d9e50f4e5501b47cf239c394 (tag: marmarek_sec_77c18513)

Last time both signatures on QSBs/qsb-023-2015.txt verified successfully was commit aeb6b239f7f5140c824923f76a0ac6f526eba8fd (tag: joanna_sec_aeb6b239)

**Comment by marmarek** [comment]
Thanks @kocmo for the report.
I've updated my signatures. @rootkovska please consider doing so too.

**Comment by unman** [comment]
@marmarek This has still not been resolved - should a note be added to the QSB page about this?

**Comment by andrewdavidwong** [comment]
Pinging @rootkovska

**Comment by DiagonalArg** [comment]
I'm finding the lack of response here a bit concerning.

**Comment by HughJackmann** [comment]
Really disappointing @rootkovska. Don't have time to do such a simple task.

**Comment by kocmo** [comment]
No choice but to interpret it as Joanna being under duress :-(

**Comment by andrewdavidwong** [comment]
In case it's a matter of GitHub notifications not getting through, I have sent Joanna an email about this.

**Comment by andrewdavidwong** [comment]
The signatures have been updated:

https://github.com/QubesOS/qubes-secpack/commit/bcfedada62cd62332e733dc4f14bfd9c9c2b4e53

Closing this as resolved. If you believe the issue is not yet resolved, please leave a comment, and we'll be happy to reopen this. Thank you.
