### ISSUE TITLE
After recent (3day ago) dom0 update VM updates, VM connection (VPN VM), fail. System tries everytime 127.0.0.1:8082 and fails.

### ISSUE THREAD

**Issue by LockedTab** [QubesOS/qubes-issues#5480]
**Qubes OS version**
Qubes R4.0.1

**Affected component(s) or functionality**
-Template VMs update/upgrade/install
-Dom0  templates/install

**Brief summary**
It started with when i changed sys-net to fedora-30-minimal. Then some day after i tried to update dom0 and it gave me error that it cannot find the qubes-dom0-update-download.sh (sorry if the name is not precise but i do not remember exactly)
**edit** I changed to fedora-minimal (network-manager installed) set dom0 updateVM to sys-net right now and the error message is the following:
[Superman@dom0 ~]$ sudo qubes-dom0-update
Using sys-nett as UpdateVM to download updates for Dom0; this may take some time...
bash: /usr/lib/qubes/qubes-download-dom0-updates.sh: No such file or directory

I was looking on the internet,( qubes DOCs, google.groups, and other linux websites to find any help.  I found a post where one post contained a very little similar issue like mine, that updates failed when using minimal template for sys-net. I changed sys-net to fedora-30 and the update succeeded. Fedora30 templates still failed but dom0 went through. kernel is now: 4.19.82-1

After the update, my VPN vm (using tasket`s Qubes openVPN support, with openvpn) failed to connect to sys-net completely. Removed qube, removed template, cloned new template from base untouched debian10, created AppVM. Before VPN install, it had access. After nothing. ping failed aswell. This is not the main issue but quite disturbing.

The main issue is no Template vm able to update, Only whonix15. But that had no issues at all before or after update, (I downloaded the current repositories, sources from the relavant distro Fedora,debian so my sourceslist supposed to be uptodate). dnf, apt returns error regarding to proxy 127.0.0.1:8082. Then i tried to download qubes templates to reinstall them, and returned the error message that could not find the template. All of my templates existing prior, downloaded with the command 
**sudo qubes-dom0-update qubes-template-DISTRO-XX**
Now all giving me "template could not be found" error. Screenshots linked for the issues i have.
I am completely clueless with this, and i am not certain if this is a bug, but would like to ask some directions where to look to fix this. 

**To Reproduce**
I do not know how to reproduce it on a different machine, but for me the commands:
change sys-net to minimal template then run the command in dom0 _sudo qubes-dom0-update_ to reproduce the dom0 error
For the other VMs it does not matter if minimal or not.
_sudo dnf update/upgrade
sudo apt update/upgrade
sudo dnf install [package]
sudo apt install [package]
sudo qubes-dom0-update qubes-template-fedora-30
sudo qubes-dom0-update qubes-template-debian-10
sudo qubes-dom0-update qubes-template-debian-10-minimal_ /or any other templates
**Expected behavior**
update runs and updates, or upgrades packages

**Actual behavior**
return error message 
debian 
 Reading from proxy failed - read (104: Connection reset by peer) [IP: 127.0.0.1 8082]
fedora
Error: Failed to download metadata for repo 'fedora-modular': Cannot prepare internal mirrorlist: Curl error (56): Failure when receiving data from the peer for https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-30&arch=x86_64 [Recv failure: Connection reset by peer]

**Screenshots**
https://postimg.cc/nCkBD6ZX
https://postimg.cc/DmtXTThG
https://postimg.cc/fJfTrnRD
https://postimg.cc/ZvzQd52N

**Additional context**
I have been introduced to linux enviroment first with Qubes OS about 4 month ago. Forgive me if my technical skills are not enough to troubleshoot alone a maybe simple problem. Please give some direction to me where can i solve my issue if posted here is not the good place.

**Solutions you've tried**
I checked the actual directory structure of the repos, and some of them were not similar like the mirror in my list so i changed them, but then i got another error. so i downloaded the originals from the distro pages, and using those.
I tried to remove the proxy setting in the templates in 01qubes-proxy, but it is reseted everytime the template starts.
I tried to look for the file /usr/lib/qubes/update-proxy-configs script but i could not find that in dom0.
I tried dnf clean all  /maybe the cache causing it
I tried update the  untouched base distro templates without success
Changing sys-net from minimal template to normal template solved the dom0 update error.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
https://www.qubes-os.org/doc/templates/fedora/
https://www.qubes-os.org/doc/templates/
https://www.qubes-os.org/doc/software-update-dom0/

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
I could not find relevant issue to my problem.

**Comment by marmarek** [comment]
Minimal template requires extra packages installed to be usable as updatevm, netvm etc. See documentation here: https://www.qubes-os.org/doc/templates/minimal/
Specifically, make sure you have `qubes-core-agent-dom0-updates` and `qubes-core-agent-networking` installed.

**Comment by LockedTab** [comment]
Networking i do, but i think dom0-updates agent not. Probably that was the reason. Actually i am fine using normal template for netVM. I try to install now and update post.

**Comment by LockedTab** [comment]
I have been browsing every related topicand i finally found the extremely simple solution. 

I never enabled manually the qubes-update-proxy, and because of this did not even checked that it is on or off. I found a post : https://www.reddit.com/r/Qubes/comments/agyune/how_to_use_update_proxy_on_standalonevm/ 
Then enlightement came. I should check the steps here as they looking related.
I did. 

_All i did was went to the Qube Manager settings in the TemplateVM, and enabled there the qubes-update-proxy service._

I do not know if the recent dom0 update switched the proxy off, or something went wrong, but i am sure that i did not switched it on or off before. 
So issue is SOLVED. I close this thread.

**Comment by marmarek** [comment]
> All i did was went to the Qube Manager settings in the TemplateVM, and enabled there the qubes-update-proxy service.

`qubes-update-proxy` service should _not_ be enabled in the template itself. But in a VM pointed by `qubes.UpdatesProxy` service policy. See https://www.qubes-os.org/doc/software-update-domu/#updates-proxy
