### ISSUE TITLE
Renaming VPN qube -> loss of data, clone of DIFFERENT qube with similar name.

### ISSUE THREAD

**Issue by ghost** [QubesOS/qubes-issues#5481]
**Qubes OS version**
4.0 (R4.0)

**Affected component(s) or functionality**
Renaming qubes.

**Brief summary**
I tried to rename a VPN qube (proxy vm). That qube was deleted. A renamed qube was produced, but the network access and firewall settings appear to be copied from another qube, albeit with a similar name. 

**To Reproduce**
Unsure if repeatable.

There are 3 similiarly named qubes - possibly confusing - so as a glossary:

1. Orginal VPN qube called "MullvadVPN"
	-standalone, deb-10
	-networking: (default) sys-firewall
	-IP range: Country 1 
	-working

2. Another VPN qube (for multihop), "MullvadVPN-clone-2"
	-standalone, deb-10	
	-networking: MullvadVPN
	-IP range: Country 2 
	-working
	-cloned from MullvadVPN and then modified

3. Actual product of renaming MullvadVPN-clone-2, "MullvadVPN-1-2"
	-standalone, deb-10
	-networking: (default) sys-firewall
	-IP range: Country 1
	-not working - no `ping` from terminal, no web browser `http/s`

History:

I followed the Mullvad website's instruction to set up a 'single-hop' NetVM, and it worked well, for weeks. It requires a deb-10 image and creating a standalone VM, I called "MullvadVPN".

For a multihop solution, Mullvad support gave me instructions that required a clone of MullvadVPN. I named it "MullvadVPN-clone-2". Worked fine.

~24 hours later, I tried to rename the multihop qube I called "MullvadVPN-clone-2" to something more logical, "MullvadVPN-1-2". I used "rename" button in the settings launched from Qube Manager.

**Expected or desired behavior**
Production of a qube named "MullvadVPN-1-2", identical in settings to "MullvadVPN-clone-2" (itself deleted).

**Actual behavior**
The MullvadVPN-clone-2 was removed. A qube named "MullvadVPN-1-2" was created, but appears identical in settings to a qube that was uninvolved in the operation, "MullvadVPN".

**Screenshots**
_If applicable, add screenshots to help explain your problem._

**Additional context**
Possibly relevant: MullvadVPN-clone-2 used MullvadVPN as its network provider. (MullvadVPN-1-2 reverted to default (sys-firewall)

Relevant log extracts:
I can find logs from "within" each of the qubes, of which relevant extracts are:

[vm-MullvadVPN-clone-2.log-20191117]:

2019-11-17 23:45:13,348 Activating the MullvadVPN-clone-2 VM

2019-11-18 19:01:36,718 Removing volume private: qubes_dom0/vm-MullvadVPN-clone-2-private

2019-11-18 19:01:36,720 Removing volume volatile: qubes_dom0/vm-MullvadVPN-clone-2-volatile

2019-11-18 19:01:36,720 Removing volume root: qubes_dom0/vm-MullvadVPN-clone-2-root

2019-11-18 19:01:36,721 Removing volume kernel: 4.19.81-1

[vm-MullvadVPN-1-2.log]:

2019-11-18 19:01:24,153 Creating directory: /var/lib/qubes/appvms/MullvadVPN-1-2

**Solutions you've tried**
...

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
Unable to find anything relevant, but may not have the expertise to search for it (or know it if I find it).

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

May be relevant:

Data loss when renaming qube https://github.com/QubesOS/qubes-issues/issues/5056

After cloning or renaming a qube, the devices are missing from the new qube
https://github.com/QubesOS/qubes-issues/issues/4992

**Comment by marmarek** [comment]
@marmarta any idea?

**Comment by marmarta** [comment]
No, but it looks similar to QubesOS/qubes-issues#5545 - although the place it happens in ios very different. I'm looking into it...

**Comment by marmarta** [comment]
Nope, never managed to reproduce this or find what the hell might be happening.

**Comment by andrewdavidwong** [comment]
Closing as "cannot reproduce" (we were unable to reproduce this issue). If anyone believes this is a mistake, or if anyone can reproduce the issue, please leave a comment, and we'll be happy to reopen this. Thank you.
