### ISSUE TITLE
qvm-sync-appmenus won't refresh list of applications

### ISSUE THREAD

**Issue by ghost** [QubesOS/qubes-issues#5483]
**Qubes OS version**
4.0.2-rc2

**Affected component(s) or functionality**
Windows 7 qube + QWT, Void Template (sometimes)

![tshoot1](https://user-images.githubusercontent.com/49844258/69518928-d9e70480-0f69-11ea-83ae-a8858558bdbc.png)

**Comment by c4tzz** [comment]
Is there any Qubes-USB-Proxy package for Win7 qube?

**Comment by SaswatPadhi** [comment]
I also notice this on Fedora minimal templates. I had opened an issue earlier: #5296
