### ISSUE TITLE
installing xorg-server (1.20.6-1) breaks dependency 'xorg-server<1.20.6'

### ISSUE THREAD

**Issue by c4tzz** [QubesOS/qubes-issues#5487]
**Qubes OS version**
4.0.2-rc2

**Affected component(s) or functionality**
Archlinux Template

![arch](https://user-images.githubusercontent.com/49844258/69627368-848b2000-105b-11ea-9890-475370005178.png)

**Comment by seberm** [comment]
https://github.com/QubesOS/qubes-gui-agent-linux/pull/79

**Comment by andrewdavidwong** [comment]
@marmarek, has this already been fixed by https://github.com/QubesOS/qubes-gui-agent-linux/pull/79?

**Comment by marmarek** [comment]
Yes.
