### ISSUE TITLE
Add information to template support status table

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#5489]
@marmarek wrote:
> BTW I think we need a canonical place for template support status table (supported, community supported, unsupported), including information who support what. Or maybe we do have it somewhere already? @andrewdavidwong

We have this table: https://www.qubes-os.org/doc/supported-versions/#templatevms

But it doesn't yet have all the types of information you listed.

_Originally posted by @andrewdavidwong in https://github.com/QubesOS/qubes-issues/issues/5488#issuecomment-558970239_

**Comment by andrewdavidwong** [comment]
@marmarek, when you say "supported," do you mean supported *by Qubes* or supported *by the upstream distro maintainer*?

The [template support table we currently have](https://www.qubes-os.org/doc/supported-versions/#templatevms) shows which templates are supported by which versions of Qubes.

If we're talking about whether a given upstream version is supported by its own maintainer, e.g., whether Fedora 23 is supported by the Fedora Project, then I question whether we should get into the business of maintaining such documentation about other projects rather than just linking to their own documentation about it.

**Comment by marmarek** [comment]
> when you say "supported," do you mean supported _by Qubes_ or supported _by the upstream distro maintainer_?

"by Qubes". But in principle (for templates), we keep it as a subset of "by the upstream distro maintainer". I.e. we don't provide template support beyond upstream support.

**Comment by marmarek** [comment]
This also means the said table is outdated, as Fedora versions < 29 are EOL. And 29 will be very soon too - on Nov 29 (which BTW we should announce).
How we should proceed with removing versions from that table? Should there be some history (beyond git)? Or it doesn't matter? I think from the user point of view, the most important info is about the current state.

**Comment by andrewdavidwong** [comment]
> This also means the said table is outdated, as Fedora versions < 29 are EOL. And 29 will be very soon too - on Nov 29 (which BTW we should announce).
> How we should proceed with removing versions from that table? Should there be some history (beyond git)? Or it doesn't matter? I think from the user point of view, the most important info is about the current state.

This is a misinterpretation of the table. The table shows which templates are supported *by a particular Qubes release*, not which upstream releases are supported by their upstream maintainers. It answers questions like, "Is there a Fedora 29 template for Qubes 3.2?" or "Which Debian versions are available as templates on Qubes 4.0?" The answers to these questions do not depend on whether any Fedora or Debian release has reached EOL, since they are pure Qubes questions about Qubes releases and Qubes templates.

In other words, "Qubes-RX supports Template-Y" in this table means that Template-Y can be installed successfully in Qubes-RX and can run without any Qubes-specific problems. It says nothing about what happens *inside* Template-Y, whether Template-Y is still receiving updates using its own internal updater, etc. It's purely about whether Qubes-RX and Template-Y are compatible from a Qubes perspective. For example, when Fedora 21 reached EOL, it did not change the fact that Qubes 3.0 supports the Fedora 21 TemplateVM. (This will always be true, even though both are now EOL.)

Maybe a better word than "supported" would be "compatible," since this also doesn't say anything about how long the Qubes OS Project will provide support for a TemplateVM. It's just about compatibility between a Qubes OS release and a particular Template.

There's at least three different kinds of information we're interested in:
* Is a particular OS (which happens to be used in a Qubes template) supported by upstream?
* Is a particular OS available in a Qubes template for Qubes RX?
* Is the Qubes OS Project still providing support (e.g., bug fixes) for a particular template?

This table currently only answers the second type of question.

> And 29 will be very soon too - on Nov 29 (which BTW we should announce).

Will do.

By the way, how do you find out about this? I'm subscribed to Fedora's devel-announce mailing list (in an attempt to stay apprised of EOLs), but this is the first I'm hearing of this. I've searched in vain for a way to receive EOL announcements from them.

**Comment by marmarek** [comment]
> This is a misinterpretation of the table. The table shows which templates are supported _by a particular Qubes release_, not which upstream releases are supported by their upstream maintainers.

The distinction I'm asking for is between "are supported" and "are or ever were supported". The latter is about just being able to install, the former about install and receive (Qubes specific) updates. Yes, the latter indeed sounds more like "compatible", not "supported".

> This table currently only answers the second type of question.

I see. IMO we need also a place to clearly provide info of the third type.

> By the way, how do you find out about this? I'm subscribed to Fedora's devel-announce mailing list (in an attempt to stay apprised of EOLs), but this is the first I'm hearing of this. I've searched in vain for a way to receive EOL announcements from them.

I see it here: https://lists.fedoraproject.org/archives/list/announce@lists.fedoraproject.org/thread/VUK3CJ5LO4ROUH3JTCDVHYAVVYAOCU62/

But personally, I simply remember they EOL Fedora version N a month after releasing N+2. And also use a helpful table on the wikipedia: https://en.wikipedia.org/wiki/Fedora_version_history#Version_history

**Comment by andrewdavidwong** [comment]
> The distinction I'm asking for is between "are supported" and "are or ever were supported". The latter is about just being able to install, the former about install and receive (Qubes specific) updates. Yes, the latter indeed sounds more like "compatible", not "supported".

Exactly. The table currently tells you only which templates are *available* for each Qubes version.

> I see. IMO we need also a place to clearly provide info of the third type.

I agree. I'll figure out a way to do this.

> But personally, I simply remember they EOL Fedora version N a month after releasing N+2.

You have a much better memory than me. :slightly_smiling_face: I knew this was the rule, but I have way too many other things to remember in my life, so I never spontaneously recall this piece of information at the right moment.
