### ISSUE TITLE
4.1 Installer does not correctly install Grub/Kernel

### ISSUE THREAD

**Issue by JarrahG** [QubesOS/qubes-issues#5493]
**Qubes OS version**
4.1 Manually compiled. 

**Affected component(s) or functionality**
Installer/bootloader on both EFI and legacy systems.

**Brief summary**
On both EFI and legacy boot, the 4.1 installer will not properly install and configure Grub.

**To Reproduce**
1. Compile and install Qubes r4.1
2. Attempt to boot newly installed system. (I used the default partitioning)
3. System will drop to grub command line. 

**Expected behavior**
Boot to 4.1. All relevant grub files are configured.

**Actual behavior**
Kernel files are missing, /boot/grub* is missing, the xen_linux section of grub.cfg is empty.

Manually adding the above files results in the following error:
```
error: invalid arch-dependent ELF magic
```

**Additional context**
This is using the grub-efi fork of anaconda and lorax-templates by Marmarek.

**Solutions you've tried**
* Manually add menuentry lines. 
* Manually install kernel rpm from build.
* Currently attempting to reinstall grub2-efi and repeat the above.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
No documentation exists for the pre-release version. 
UEFI-troubleshooting and the device specific EFI troubleshooting don't contain much about this.

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
None found.

**Comment by marmarek** [comment]
There are a couple of pull requests still not merged, related to bootloader installation, linked at https://github.com/QubesOS/qubes-issues/issues/4902. I assume you've tried those, right?

In theory it should affect EFI boot only, legacy was fine last time I've tried. Was the problem on legacy boot the same, or something different?

**Comment by JarrahG** [comment]
> There are a couple of pull requests still not merged, related to
> bootloader installation, linked at #4902
> <https://github.com/QubesOS/qubes-issues/issues/4902>. I assume you've
> tried those, right?
>
Those are the repository changes I made. I didn't pull the changes,
rather I just checked out your development branches (grub-efi I
believe). I should have mentioned that issue as related.
>
> In theory it should affect EFI boot only, legacy was fine last time
> I've tried. Was the problem on legacy boot the same, or something
> different?
>
I mostly tested on EFI, but also installed and booted on legacy to make
sure it wasn't EFI only. At a minumum, grub couldn't find it's config
and dropped me to a grub command line.

Happy to reinstall legacy and have a better poke around if that'll help.

**Comment by JarrahG** [comment]
Tested on legacy boot and noticed the following:

* Grub config is the same as above, nothing in the 20_xen_linux section.

* vmlinuz file is missing.

* Some EFI content is installed, however, this is also not bootable (as 
expected).

Overall, this is quite similar to the issues found in the EFI install.


Also, I forgot to note before that I had to use kernel-latest in the 
build. This was done by setting the kernel to the `master` branch in the 
4.1 config before running `make get-sources`.

**Comment by marmarek** [comment]
> Also, I forgot to note before that I had to use kernel-latest in the build. This was done by setting the kernel to the `master` branch in the 4.1 config before running `make get-sources`.

That may be an issue. AFAIR some extra steps are needed to have the installer pickup `kernel-latest` instead of `kernel` package. @fepitre do you remember details?

**Comment by JarrahG** [comment]
Good to know. I'm currently recompiling with the default kernel. I can
always install kernel-latest later.

**Comment by JarrahG** [comment]
I can confirm that using kernel-latest was the problem. Installed with the standard 4.19 kernel is working fine. 

I did also experience the HVM bios problem from the below comment. The fixes there worked. 
https://github.com/QubesOS/qubes-issues/issues/5474#issuecomment-559562914
