### ISSUE TITLE
Sys-Net opening unexpectedly after being disconnected

### ISSUE THREAD

**Issue by mcertini** [QubesOS/qubes-issues#5494]
### Qubes OS version:
Qubes release 4.0 (R4.0)

### Affected component(s) or functionality:
sys-net, fedora-30 (TemplateVM)

---

### Steps to reproduce the behavior:
1. Create a VPN (HVM)
2. Create a sys-net2 disposable VM.
3. Create a sys-firewall2 disposable VM.
4. Configure VPN VM in settings to use sys-firewall2 for networking.
5. Configure VPN VM on advanced tab as "Disposable VM Template".
    Configure VPN VM on basic tab to start up automatically on boot.
    Configure VPN VM on basic tab to include backups by default.
6. Configure sys-firewall2 in settings tab to use sys-net2 for networking.
7. Configure sys-firewall2 in basic tab to start qube automatically on boot.
8  Configure sys-firewall2 in advanced tab to use "default disposable VM template fedora-30-dvm".
8. Configure sys-net2 in devices tab to use ethernet controller.
9. Configure sys-net2 in advanced tab to use "default disposable VM template fedora-30-dvm".
10. Configure sys-net2 in basic tab to start qube automatically on boot.
11. Configure sys-net in devices tab to not use ethernet controller.  Take this out of available PCI devices.
12. Configure sys-net in basic tab not to backup, not to start up automatically on boot and on the advanced tab, unselect disposable template.  Change template on the basic tab to debian-10.
13. Configure sys-firewall in basic tab not to startup automatically on boot.  On the advanced tab, unselect "Disposable VM Template".
14. In the fedora-30 (TemplateVM) in the basic tab, select VPN as the networking VM.
15. In the fedora-30 VM unselect "Start qube automatically on boot.
16. In the fedora-30 VM advanced tab, in the default disposable VM template use "(none)(current)"

### Expected or desired behavior:
Wanting to update fedora-30 by using sys-VPN communicating with sys-firewall2 communicating with sys-net2 and connecting with update servers.

### Actual behavior:
When going into fedora-30 on the command line and attempting to update, the system opens sys-net and attempts to create a network connection with this along with a connection sys-net2.  I do not understand what is causing the sys-net connection to open.  There is nothing that should be opening this.  I believe that this is causing my network communication problem.  It is odd that sys-net has been completely taken out of the picture, as far as I know, and yet it still opens.

### General notes:
I am unable to connect to the update server and am getting an html error 500.  I though was able to download traceroute and install into fedora-30.  When running traceroute, the first hop is going to the ip for sys-VPN.  It then goes to a 172 ip address which I believe is the VPN server.  I use TunnelBear which has been configured in the sys-VPN

---

### I have consulted the following relevant [documentation](https://www.qubes-os.org/doc/):
https://www.qubes-os.org/doc/disposablevm-customization/ - I used the section under: "Using static DisposableVMs for sys-*" for guidance regarding creating the disposable VMs.

### I am aware of the following related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues:
Did a search using a couple of search terms but could not find any issue such as mine.  I can supply printscreens of my setup.  I attempted to attach a jpg file but got an error message in this window "Something went really wrong, and we can't process that file. Try again".

**Comment by marmarek** [comment]
Templates use a different mechanism to download updates, not the "networking" setting. This is also why by default it is set to "none" (and should stay this way for better protection of the templates). See https://www.qubes-os.org/doc/software-update-domu/#updates-proxy
In short: modify `/etc/qubes-rpc/policy/qubes.UpdatesProxy` to set what connection should be used by various templates to download updates.

**Comment by mcertini** [comment]
Hi Marek,

Thank you.

Mike
