### ISSUE TITLE
After Dom0 Update VM Windows Do Not Open

### ISSUE THREAD

**Issue by mcertini** [QubesOS/qubes-issues#5496]
**Qubes OS version**
_The version of Qubes OS you're using (e.g., `R4.0`), available via the command `cat /etc/qubes-release` in a dom0 terminal._
Qubes release 4.0 (R4.0)

**Affected component(s) or functionality**
_The component or functionality of Qubes OS that is not working as expected._
Gui-Agent

**Brief summary**
_A clear and concise summary of the bug._
After updating Dom0, I noticed that when I tried to open open individual windows in each VM, nothing would happen.  For example I tried to open File Manager or Terminal in each VM and nothing opened on the screen.

**To Reproduce**
_Steps to reproduce the behavior:_
_1. Go to '...'_ "Q" in upper left hand side of screen.
_2. Click on '....'_ Domain: personal, or any pre-installed domains.
_3. Scroll down to '....'_  Select personal: Files, personal: Terminal
_4. See error_  Go into Qubes Manager and select the VM that you just made the transaction on in #3 above.  Right click and go to "logs".  Select Guid.personal.log.  This is where you see the error message.

**Expected behavior**
_A clear and concise description of what you expected to happen._
When selecting Files or Terminal in each VM, I expected a window to pop up showing me the Files in the VM or to give me a terminal within the VM.

**Actual behavior**
_What actually happened (instead of what you expected to happen)._
When selecting Files or Terminal in each VM, I do not see anything happen.

**Screenshots**
_If applicable, add screenshots to help explain your problem._

**Additional context**
_Add any other context about the problem here._
Doing research on the internet, I believe that the problem revolves around a file conflict during the update process.  For some reason when this is encountered, the gui-agent service is deleted.  To validate this assumption I performed the following command in Dom0 : 

systemctl enable qubes-gui-agent.service

The message I got was: Failed to enable unit: No such file or directory

**Solutions you've tried**
_If applicable, any solutions or workarounds you've already tried._
I was attempting to find the proper package to install to fix this but could not find what was needed.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
_A list of links to the Qubes documentation (or other relevant software documentation) pages you have already consulted._
I did internet searches and attempted an install of a package I noted on the following site:
https://groups.google.com/forum/#!searchin/qubes-users/qubes-gui-agent.service%7Csort:date/qubes-users/w__It0h_tpA/swfx3hiCAwAJ

I though was not successful.  The packages are in the last forum message at the bottom of the screen.

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
_A list of links to other bug reports, feature requests, or tasks in the qubes-issues tracker (or "none" if you didn't find any). Do not describe any other unreported bugs, features, or tasks here._
none

**Comment by andrewdavidwong** [comment]
> 4. See error Go into Qubes Manager and select the VM that you just made the transaction on in #3 above. Right click and go to "logs". Select Guid.personal.log. This is where you see the error message.

Would you mind providing the content of the log here in case it's useful for the devs?
