### ISSUE TITLE
fedora-30: Can't install fail2ban because qubes-core-agent conflicts firewalld

### ISSUE THREAD

**Issue by sptankard** [QubesOS/qubes-issues#5502]
**Qubes OS version**
Qubes release 4.0 (R4.0)

**Affected component(s) or functionality**
template: fedora-30 
fedora package: fail2ban, firewalld
conflicting with: qubes-core-agent

**Brief summary**
I'd like to install fail2ban in some of my templates/qubes. This doesn't seem to be possible because qubes-core-agent conflicts with firewalld.

**To Reproduce**
1. Boot a fedora-30 qube.
2. In the qube, `sudo dnf install fail2ban`
3. Install fails with error.

**Expected behavior**
Install would succeed.

**Actual behavior**
Install failed.

**Screenshots**
```shell
user@t-f30 ~> dnf repoquery qubes-core-agent --conflicts
Last metadata expiration check: 0:20:24 ago on Thu Dec  5 23:44:38 2019.
firewalld
user@t-f30 ~> sudo dnf install fail2ban --best
Last metadata expiration check: 0:24:19 ago on Thu Dec  5 23:40:54 2019.
Error: 
 Problem: package fail2ban-firewalld-0.10.4-8.fc30.noarch requires firewalld, but none of the providers can be installed
  - package qubes-core-agent-4.0.44-1.fc30.x86_64 conflicts with firewalld provided by firewalld-0.6.5-1.fc30.noarch
  - package qubes-core-agent-4.0.44-1.fc30.x86_64 conflicts with firewalld provided by firewalld-0.6.3-2.fc30.noarch
  - problem with installed package qubes-core-agent-4.0.50-1.fc30.x86_64
  - package qubes-core-agent-4.0.45-1.fc30.x86_64 conflicts with firewalld provided by firewalld-0.6.5-1.fc30.noarch
  - package qubes-core-agent-4.0.45-1.fc30.x86_64 conflicts with firewalld provided by firewalld-0.6.3-2.fc30.noarch
  - package fail2ban-0.10.4-8.fc30.noarch requires fail2ban-firewalld = 0.10.4-8.fc30, but none of the providers can be installed
  - cannot install the best candidate for the job
  - package qubes-core-agent-4.0.46-1.fc30.x86_64 conflicts with firewalld provided by firewalld-0.6.5-1.fc30.noarch
  - package qubes-core-agent-4.0.46-1.fc30.x86_64 conflicts with firewalld provided by firewalld-0.6.3-2.fc30.noarch
  - package qubes-core-agent-4.0.47-1.fc30.x86_64 conflicts with firewalld provided by firewalld-0.6.5-1.fc30.noarch
  - package qubes-core-agent-4.0.47-1.fc30.x86_64 conflicts with firewalld provided by firewalld-0.6.3-2.fc30.noarch
  - package qubes-core-agent-4.0.48-1.fc30.x86_64 conflicts with firewalld provided by firewalld-0.6.5-1.fc30.noarch
  - package qubes-core-agent-4.0.48-1.fc30.x86_64 conflicts with firewalld provided by firewalld-0.6.3-2.fc30.noarch
  - package qubes-core-agent-4.0.50-1.fc30.x86_64 conflicts with firewalld provided by firewalld-0.6.5-1.fc30.noarch
  - package qubes-core-agent-4.0.50-1.fc30.x86_64 conflicts with firewalld provided by firewalld-0.6.3-2.fc30.noarch
(try to add '--allowerasing' to command line to replace conflicting packages or '--skip-broken' to skip uninstallable packages)
user@t-f30 ~> dnf repolist
repo id                                                                                         repo name
fedora                                                                                          Fedora 30 - x86_64
fedora-modular                                                                                  Fedora Modular 30 - x86_64
qubes-vm-r4.0-current                                                                           Qubes OS Repository for VM (updates)
rpmfusion-free                                                                                  RPM Fusion for Fedora 30 - Free
updates                                                                                         Fedora 30 - x86_64 - Updates
updates-modular                                                                                 Fedora Modular 30 - x86_64 - Updates
user@t-f30 ~> 

```

**Additional context**
In debian-10 qubes, `sudo apt install fail2ban` works fine. Fail2ban can be installed in debian-10 but not fedora-30.

**Solutions you've tried**
Enabling different qubes repos inside the qube/template (testing, etc).
dnf options `--best, --skipbroken`: no help to get fail2ban installed
dnf options `--allowerasing`: might work but i want to keep qubes-core-agent too

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
Nothing relevant comes up anywhere, including on google etc.

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
None, didn't find any.

**Comment by sptankard** [comment]
I found a partial workaround: `dnf install fail2ban-hostsdeny` works. I don't understand fail2ban well enough to know what functionality is being provided by what packages, so I don't really know what it means practically to use fail2ban with/without firewalld.

It's the pkg `fail2ban-firewalld` in particular which is conflicted by `qubes-core-agent`, not all of the fail2ban packages:
```shell
[user@disp7489 ~]$ dnf search fail2ban
Last metadata expiration check: 1:02:12 ago on Thu Dec  5 23:44:38 2019.
======================== Name Exactly Matched: fail2ban =========================
fail2ban.noarch : Daemon to ban hosts that cause multiple authentication errors
======================= Name & Summary Matched: fail2ban ========================
fail2ban-tests.noarch : Fail2Ban testcases
fail2ban-mail.noarch : Mail actions for Fail2Ban
fail2ban-sendmail.noarch : Sendmail actions for Fail2Ban
fail2ban-firewalld.noarch : Firewalld support for Fail2Ban
fail2ban-shorewall.noarch : Shorewall support for Fail2Ban
fail2ban-server.noarch : Core server component for Fail2Ban
fail2ban-all.noarch : Install all Fail2Ban packages and dependencies
fail2ban-systemd.noarch : Systemd journal configuration for Fail2Ban
fail2ban-hostsdeny.noarch : Hostsdeny (tcp_wrappers) support for Fail2Ban
[user@disp7489 ~]$ 
```

Perhaps this isn't a bug, just a consequence of firewalld being unwelcome, because it would mess up the Qubes firewalling setup?

Found a few links, not sure if related:
https://www.reddit.com/r/Qubes/comments/b9dlh3/using_firewalld_in_qubes_401/

https://github.com/QubesOS/qubes-issues/issues/3503
https://github.com/QubesOS/qubes-core-agent-linux/pull/95

**Comment by marmarek** [comment]
>  just a consequence of firewalld being unwelcome, because it would mess up the Qubes firewalling setup

That's exactly the case. But it should be possible to make qubes firewall tolerate firewalld - probably by configuring firewall through it when enabled.

**Comment by andrewdavidwong** [comment]
> Perhaps this isn't a bug, just a consequence of firewalld being unwelcome, because it would mess up the Qubes firewalling setup?

> That's exactly the case. But it should be possible to make qubes firewall tolerate firewalld - probably by configuring firewall through it when enabled.

It sounds like there is agreement that this is not a bug, so I'm closing as `not an issue`. If anyone believes this is a mistake, please leave a comment, and we'll be happy to take another look. Thank you.

**Comment by sptankard** [comment]
Agreed, sounds like this isn't a bug.

> it should be possible to make qubes firewall tolerate firewalld - probably by configuring firewall through it when enabled.

If i understand correctly... 
1. You are referring to a hypothetical future version, not to the current qubes-core-agent. 
2. It is currently the desired behavior (and in fact a security feature) for `dnf install fail2ban` to fail. (unless qubes-core-agent is uninstalled, of course)

Maybe not the place for this, but I'm wondering why debian-10 `apt install fail2ban` works fine. Perhaps... 
1. debian package fail2ban doesn't pull in firewalld (but, to my quick glance on pkgs.org, it looks like it does), or 
2. qubes firewalling is done differently in debian vms?
3. debian pkg `fail2ban` *does* pull in firewalld but simply doesn't provide `qubes-core-agent` a way to use pkg conflicts to prevent this?

In case of (3), this would seem like a potential bug in the debian template (potentially with security consequences?). Does `apt install fail2ban` damage qubes firewalling?

**Comment by sptankard** [comment]
FWIW...
- `apt install fail2ban` doesn't touch qubes-core-agent. 
- `apt install fail2ban` does *not* pull in `firewalld` in debian-10.
- `apt install firewalld` calmly informs that it will remove `qubes-core-agent` and a bunch of other qubes packages. I press Y to confirm and it proceeds to happily remove them, and the dispVM crashes. :)
- Contrary to debian-10, in fedora-30 `dnf install firewalld --allowerasing` does not cause VM to crash. Just throws a couple of errors during the dnf verification phase.

So... no security hole for the debian template. `apt install fail2ban` seems to be safe there. (Presumably you get fail2ban without firewalld integration.)

**Comment by marmarek** [comment]
> You are referring to a hypothetical future version, not to the current qubes-core-agent.

Yes.

>     2\. It is currently the desired behavior (and in fact a security feature) for `dnf install fail2ban` to fail. (unless qubes-core-agent is uninstalled, of course)

Yes.

> `apt install fail2ban` seems to be safe there. (Presumably you get fail2ban without firewalld integration.)

Looks like it.
