### ISSUE TITLE
debian package "qubes-core-agent" version "4.0.50+deb10u1" does not forward packets in "provides_network=true" VMs

### ISSUE THREAD

**Issue by pellywog** [QubesOS/qubes-issues#5504]
**Qubes OS version**
4.0

**Affected component(s) or functionality**
Building a new network VM from debian-10-minimal

**Brief summary**
When I create a new debian-10-minimal and install qubes-core-agent, I get a timeout in VMs I connect to this network VM

**To Reproduce**
```
# Build a new network VM from debian-10-minimal
qvm-clone debian-10-minimal test-network-vm

# Set prefs for a network VM
qvm-prefs test-network-vm netvm sys-firewall
qvm-prefs test-network-vm provides_network true
qvm-prefs test-network-vm virt_mode hvm
qvm-prefs test-network-vm autostart false

# Install debian packages required for a network VM
qvm-run -u root test-network-vm --pass-io 'apt-get -y install nftables qubes-core-agent-networking qubes-core-agent

# Shutdown the network VM
qvm-shutdown test-network-vm


# Create a VM to test the behavior with
qvm-clone debian-10-minimal test-vm

# Set the new network VM as network VM
qvm-prefs test-vm netvm test-network-vm
qvm-start test-network-vm

# Try if we can reach the internet
qvm-start test-vm
qvm-run -u root --pass-io test-vm 'ping -c 3 8.8.8.8'
# timeout here
```

From what I can see the packets are not forwarded to sys-firewall.

**Expected behavior**
There should be no timeout / packets should reach sys-firewall.

**Actual behavior**
There is a timeout / packets don't reach sys-firewall.

**Solutions you've tried**
It seems to me that:
```
qvm-run -u root test-network-vm --pass-io 'apt-get -y install nftables qubes-core-agent-networking qubes-core-agent=4.0.48-1+deb10u1
```
does work as expected.

The version that is currently installed by default:
```
apt-cache policy qubes-core-agent
# some output
 *** 4.0.50+deb10u1 500
# some more output
```

**Comment by marmarek** [comment]
Take a look at https://www.qubes-os.org/doc/templates/minimal/ - most likely you didn't installed `qubes-core-agent-networking`.

**Comment by marmarek** [comment]
I see two issues with steps you've provided:
 - you use `qvm-clone` to create an VM based on a template - in your example `test-vm` is in fact a template; although it shouldn't cause this issue, it's just probably not what you want
 - you are missing install of `qubes-core-agent-networking` in `test-vm` - this package is needed for any kind of networking, not only to provide network to other VMs

**Comment by andrewdavidwong** [comment]
> * you are missing install of `qubes-core-agent-networking` in `test-vm` - this package is needed for any kind of networking, not only to provide network to other VMs

It also looks to me like this was the missing step. Closing as "not an issue." However, if you believe that there is still a bug here, please leave a comment, and we'll be happy to take another look. Thank you.

**Comment by pellywog** [comment]
Yes, that was it, thank you! :)
