### ISSUE TITLE
qui-devices widget don't notice some attach/detach

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#5505]
**Qubes OS version**
R4.0, R4.1

**Affected component(s) or functionality**
usb proxy

**Brief summary**
When device is detached spontaneously (for example because device is reset by the driver), or when attached by directly calling relevant qrexec service, qui-devices widget won't notice it. Calling `qvm-usb` tool properly display the state.

**Expected behavior**
qui-devices widget properly reflect the system state, as `qvm-usb` does.

**Actual behavior**
qui-devices gets desynchronized.

**Additional context**
It's because events are sent only when the action is triggeder via dom0 qubesd code. When it's done some other means, events are missing, even though qubesd do receive notifications about the change.

**Solutions you've tried**
Alternative: refresh more info if any info about devices changes: https://github.com/QubesOS/qubes-desktop-linux-manager/pull/87
This is kind of similar to what `qvm-usb` does - it retrieve all the info from scratch on eatch call.

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
QubesOS/qubes-issues#4626

Reported by @rmol

**Comment by eloquence** [comment]
@marmarek Thanks again for resolving this issue. This is blocking us on https://github.com/freedomofpress/securedrop-workstation/pull/324 which is a high value change for the SecureDrop Workstation. As we're hoping to launch the pilot in 4-8 weeks, it'd be great for this change to land in the production repo soon. Is there any ETA yet on when it'll make it into the production 4.0 repo?

**Comment by marmarek** [comment]
There were few regressions introduced by this change, but the latest version should have it all fixed:
https://github.com/QubesOS/updates-status/issues/1584
It's in testing repo for 6 days already, should be in stable in about a week. If you can test this specific version and give a feedback (:+1: or :-1: on the above issue is enough), that would be much helpful.

**Comment by eloquence** [comment]
We'll do that, thanks very much for the quick update.

**Comment by rmol** [comment]
Thanks @marmarek, this looks great. A USB device automatically attached via udev rules is now shown as connected in the devices widget.
