### ISSUE TITLE
/etc/machine-id is not unique

### ISSUE THREAD

**Issue by zaoqi** [QubesOS/qubes-issues#5512]
**The problem you're addressing (if any)**
/etc/machine-id is not unique

**Describe the solution you'd like**
generate /etc/machine-id for each AppVM and DispVM

**Where is the value to a user, and who might that user be?**

**Describe alternatives you've considered**

**Additional context**

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

**Comment by andrewdavidwong** [comment]
Please consider filling out the other fields in the issue template. In particular:

> **Where is the value to a user, and who might that user be?**

**Comment by alimirjamali** [comment]
@andrewdavidwong This subject is very well covered and discussed in details in #8833

I suggest closing this thicket
