### ISSUE TITLE
Split GPG permission dialog is squished to a narrow width

### ISSUE THREAD

**Issue by eloquence** [QubesOS/qubes-issues#5513]
**Qubes OS version**
4.0

**Affected component(s) or functionality**
Split GPG

**Brief summary**
Permission dialog is squished

**To Reproduce**
Create a split-gpg VM setup and attempt to access it

**Expected behavior**
Permission dialog appears with normal width

**Actual behavior**
Permission dialog is squished to a narrow width, causing dialog title to be cut off, and dialog to look nonstandard

**Screenshots**
![Screenshot_2019-12-13_16-21-04](https://user-images.githubusercontent.com/213636/70833788-794f2880-1dad-11ea-96b9-2b508af1707d.png)

**Comment by marmarta** [comment]
Probably can be fixed along with https://github.com/QubesOS/qubes-issues/issues/5514
