### ISSUE TITLE
dummy initramfs required to boot mirage or custom kernel docs incorrect

### ISSUE THREAD

**Issue by marmot1791** [QubesOS/qubes-issues#5516]
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
Booting domU from a custom kernel installed in dom0

**Brief summary**
In the docs it states "All the files besides vmlinuz are optional." when installing customer kernels: https://www.qubes-os.org/doc/managing-vm-kernel/#kernel-files-structure

However, when testing a mirage firewall per this issue: https://github.com/mirage/qubes-mirage-firewall/issues/70

A dummy initramfs file still appears to be required. Is the documentation incorrect or is this a bug?

**To Reproduce**
_Steps to reproduce the behavior:_
_1. Install a customer kernel with only vmlinuz in dom0 for use as a domU kernel
_2. Create a domU that uses the custom kernel in PV mode
_3. Start the qube --- get and erro about no initramfs found
_4. Create dummy initramfs and qube starts successfully

**Comment by marmarek** [comment]
This is one of very few places where docs are ahead of the time (instead of outdated...). This is true for upcoming R4.1, but indeed in R4.0 dummy initramfs is still needed.

**Comment by marmot1791** [comment]
Thanks! Clarified this in the docs with pull request https://github.com/QubesOS/qubes-doc/pull/907 which should close this issue.

**Comment by palainp** [comment]
Currently initramfs is needed with Qubes 4.1 with this check: https://github.com/QubesOS/qubes-core-admin/blob/c177aacbe1afc35034826ef538c0e49ed40b6bc7/qubes/storage/kernels.py#L140

Is there a way to set something in the AppVM settings for booting without initramfs? (for example this file is not needed for qubes-mirage-firewall https://github.com/mirage/qubes-mirage-firewall/issues/70).

**Comment by andrewdavidwong** [comment]
@palainp: Please note that the issue tracker (qubes-issues) is not intended to be a place for fielding questions. Instead, we have other [venues meant for asking questions, asking for help, and having discussions](https://www.qubes-os.org/support/). (By contrast, the issue tracker is more of a technical tool intended to support our developers in their work.) Thank you for your understanding!

**Comment by palainp** [comment]
Thanks for your reply and sorry for posting here, my intention was more related to the issue than a user question.

I more wanted to ask for re-openning the issue as the documentation state that `initramfs` is optional in Qubes 4.1 (in https://www.qubes-os.org/doc/managing-vm-kernels/#kernel-files-structure) but this seems to not be the case as the code check for the file existence (line 140 of `kernel.py`).

**Comment by palainp** [comment]
Hi, I openned a PR https://github.com/QubesOS/qubes-doc/pull/1369 to update the documentation as initramfs is needed so far.
