### ISSUE TITLE
Installer keyboard layout doesn't propagate in r4.1.

### ISSUE THREAD

**Issue by JarrahG** [QubesOS/qubes-issues#5517]
**Qubes OS version**
4.1 custom compiled fully up to date with qubes-dom0-current-testing

**Affected component(s) or functionality**
Keyboard layout propagation.

**Brief summary**
The keyboard layout set in dom0 from the installer (or any other method) does not propagate to VMs. These always have the default layout.

**To Reproduce**
1. Install Qubes r4.1 with a non-default keyboard layout.
2. Start a VM.
3. Attempt to type.

**Expected behavior**
Layout propagates to the VM as with 4.0.

**Actual behavior**
Layout is set to the default "US".

**Solutions you've tried**
Manually setting the layout works. (setxkbmap)

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
https://www.qubes-os.org/faq/#my-keyboard-layout-settings-are-not-behaving-correctly-what-should-i-do

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
https://github.com/QubesOS/qubes-issues/issues/1396 - Main issue for keyboard layout issues. Deals with Changing the layout, not propagation of the one set during install.

**Comment by JarrahG** [comment]
Closing as resolved in new versions of 4.1.

**Comment by GWeck** [comment]
The issue has reappeared - see #1396

**Comment by andrewdavidwong** [comment]
> The issue has reappeared - see #1396

I'm confused about why we have both this issue and #1396. Is this a duplicate of #1396? Please keep in mind that we typically don't maintain separate issues for the same bug in different versions of Qubes. We typically just have one issue for all Qubes versions, where the milestone of that issue is set to the earliest affected Qubes version.

**Comment by JarrahG** [comment]
> I'm confused about why we have both this issue and #1396. Is this a duplicate of #1396?

This issue is about the installer keyboard layout not propagating to any VMs, currently booted or new. #1396 is a long running problem where if a user changes their keyboard layout during operation, the layout change will not propagate. 

At this time, I believe this issue was a regression which only effects earlier versions of 4.1 (and custom built ones, I can't find the patch that fixes it), but does not effect 4.0. Someone else who has installed a newer 4.1 image may be able to confirm.

#1396 affects all versions of QubeOS because the current design sets the keyboard layout once at VM boot time, rather than propagating it on a trigger from dom0 changes.
