### ISSUE TITLE
Cannot resize StandaloneVM

### ISSUE THREAD

**Issue by nil0x42** [QubesOS/qubes-issues#5518]
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
VM Resize (`qvm-volume resize`)

**Brief summary**
I am unable to resize a Standalone VM. This bug is probably due to a recent dom0 upgrade because i used to be able to use it months ago. 

**To Reproduce**
In dom0 terminal:
```
# qvm-volume resize win7:root 40g
You shouldn't use lvm size setter
```

**Expected behavior**
VM is resized

**Actual behavior**
I get error message:
`You shouldn't use lvm size setter`

**Solutions you've tried**
- tried running `qvm-volume extend` (alias of resize)
- made sure new size is bugger than previous one.
- tried to clone my VM, then resize the clone

**Comment by marmarek** [comment]
I've just tried and it works for me...
Can you give exact version of `qubes-core-dom0` and `qubes-core-admin-client` packages in dom0?

**Comment by nil0x42** [comment]
Hello, here are the version of packages you asked for:

`[user@dom0 ~]$ yum list qubes-core-dom0 qubes-core-admin-client`
```
Redirecting to '/usr/bin/dnf list qubes-core-dom0 qubes-core-admin-client' (see 'man yum2dnf')

Failed to synchronize cache for repo 'qubes-dom0-cached', disabling.
Installed Packages
qubes-core-admin-client.noarch                4.0.28-1.fc25                @qubes-dom0-cached
qubes-core-dom0.x86_64                        4.0.48-1.fc25                @qubes-dom0-cached

```

**Comment by marmarek** [comment]
The same.
Anything special about that VM? Is it just normal StandaloneVM, in default lvm pool?

**Comment by nil0x42** [comment]
Hi, i don't know much about qubes internals, lvm & xen stuff, are there command that can help discover in which lvm pool the VM is, or if something is different ?

I'd tend to say that everything is normal, the VM i, trying to resize is a windows StandaloneVM, created following qubes tutorial for windows 7 installation, one year ago

**Comment by marmarek** [comment]
Found it, the error message is misleading - it isn't lvm but file pool...
And resize indeed is broken in file pool.

**Comment by nil0x42** [comment]
Hello
I just applied your change locally in my dom0, in `/usr/lib/python3.5/site-packages/qubes/storage/file.py`
But when i try to resize my VM, the error message remains

**Comment by marmarek** [comment]
You need to restart `qubesd` service after this change.

**Comment by nil0x42** [comment]
Everything works fine since your commit. Just not sure if i sould close the issue or keep it open until your commit is merged

**Comment by andrewdavidwong** [comment]
> Everything works fine since your commit. Just not sure if i should close the issue or keep it open until your commit is merged

This issue will be closed automatically when https://github.com/QubesOS/qubes-core-admin/pull/301 is merged. :slightly_smiling_face:
