### ISSUE TITLE
Window Resize causes application to crash in r4.1

### ISSUE THREAD

**Issue by JarrahG** [QubesOS/qubes-issues#5519]
### Qubes OS version:
R4.1 Custom compiled, all updates from current-testing installed.

### Affected component(s) or functionality:
Resizing windows of any VM type (tested on HVM and PVH template based VMs)

---

### Steps to reproduce the behavior:
1. Open an appVM/TemplateVM window
2. Resize the window quickly (eg. by snapping the window to the screen edge in xfce)
3. Watch the window disappear.

Alternative failure mode:
2. Resize the window slowly.
3. After a certain point the window will continue resizing, but the elements in the window will not. The application will take up only a small part of the window.

### Expected or desired behavior:
Window resizes correctly as in r4.0

### Actual behavior:
Window either crashes or does not fully resize.

### General notes:
This issue is highly evident in i3 as windows are resized by large amounts when opening or closing an application. 
This issue may be exacerbated by my 4K monitor as it seems based on the amount I resize. I can partially fill a 1080p section of screen before the issue occurs. 

guid.log:
```
Icon size: 128x128
ErrorHandler: BadAccess (attempt to access private resource denied)
                 Major opcode: 130 (MIT-SHM)
                 Minor opcode: 1 (X_ShmAttach)
                 ResourceID:   0xc0000c
                 Failed serial number:  150
                 Current serial number: 151
XShmAttach failed for window 0x3a00009(remote 0x800003)
```
Relevant sections of guest log:
```
[2019-12-16 06:24:21] [    0.231527] Kernel command line: root=/dev/mapper/dmroot ro nomodeset console=hvc0 rd_NO_PLYMOUTH rd.plymouth.enable=0 plymouth.enable=0 xen_scrub_pages=0 nopat
[2019-12-16 06:24:21] [    0.231555] You have booted with nomodeset. This means your GPU drivers are DISABLED
[2019-12-16 06:24:21] [    0.231556] Any video related functionality will be severely degraded, and you may not even be able to suspend the system properly
[2019-12-16 06:24:21] [    0.231556] Unless you actually understand what nomodeset does, you should reboot without enabling it
```
```
[2019-12-16 17:56:20]          Starting .[0;1;39mUser Runtime Directory /run/user/1000.[0m...
[2019-12-16 17:56:20] [.[0;32m  OK  .[0m] Started .[0;1;39mUpdate UTMP about System Runlevel Changes.[0m.
[2019-12-16 17:56:20] [.[0;32m  OK  .[0m] Started .[0;1;39mUser Runtime Directory /run/user/1000.[0m.
[2019-12-16 17:56:20]          Starting .[0;1;39mUser Manager for UID 1000.[0m...
[2019-12-16 17:56:20]          Starting .[0;1;39mupdate of the roo…NSSEC validation in unbound.[0m...
[2019-12-16 17:56:20] [.[0;32m  OK  .[0m] Started .[0;1;39mUser Manager for UID 1000.[0m.
[2019-12-16 17:56:20] [.[0;32m  OK  .[0m] Started .[0;1;39mSession c1 of user user.[0m.
[2019-12-16 17:56:20] [.[0;32m  OK  .[0m] Started .[0;1;39mSession c3 of user user.[0m.
[2019-12-16 17:56:20] [.[0;32m  OK  .[0m] Started .[0;1;39mSession c2 of user user.[0m.
[2019-12-16 17:56:20] [   10.877575] Decoding supported only on Scalable MCA processors.
[2019-12-16 17:56:21] [   11.785811] Decoding supported only on Scalable MCA processors.
[2019-12-16 17:56:21]          Starting .[0;1;39mRealtimeKit Scheduling Policy Service.[0m...
[2019-12-16 17:56:21] [.[0;32m  OK  .[0m] Started .[0;1;39mRealtimeKit Scheduling Policy Service.[0m.
[2019-12-16 17:56:21]          Starting .[0;1;39mAuthorization Manager.[0m...
[2019-12-16 17:56:22] [   12.271535] Decoding supported only on Scalable MCA processors.
[2019-12-16 17:56:22] [   12.391307] fuse init (API version 7.27)
[2019-12-16 17:56:22]          Mounting .[0;1;39mFUSE Control File System.[0m...
[2019-12-16 17:56:22] [.[0;32m  OK  .[0m] Mounted .[0;1;39mFUSE Control File System.[0m.
[2019-12-16 17:56:22] [.[0;32m  OK  .[0m] Started .[0;1;39mAuthorization Manager.[0m.
[2019-12-16 17:56:23] [   13.307238] Decoding supported only on Scalable MCA processors.
[2019-12-16 17:56:23] [   13.309851] xen:grant_table: xen/grant-table: max_grant_frames reached cur=32 extra=1 limit=32 gnttab_free_count=0 req_entries=1
[2019-12-16 17:56:23] [.[0;32m  OK  .[0m] Created slice .[0;1;39msystem-systemd\x2dcoredump.slice.[0m.
[2019-12-16 17:56:23] [.[0;32m  OK  .[0m] Started .[0;1;39mProcess Core Dump (PID 1179/UID 0).[0m.
```

---

### I have consulted the following relevant [documentation](https://www.qubes-os.org/doc/):
None found.

### I am aware of the following related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues:
None found.

**Comment by marmarek** [comment]
> [2019-12-16 17:56:23] [   13.309851] xen:grant_table: xen/grant-table: max_grant_frames reached cur=32 extra=1 limit=32 gnttab_free_count=0 req_entries=1

That's it. Try adding `max_grant_frames=128` to Xen cmdline (not Linux). If that won't help, please read the message carefully, if the limit was really raised (there was a Xen bug in handling this parameter and I'm not sure if our version is affected).
Some discussion about the value: https://github.com/QubesOS/qubes-gui-agent-linux/pull/34#issuecomment-389186120

**Comment by JarrahG** [comment]
> That's it. Try adding `max_grant_frames=128` to Xen cmdline (not Linux). If that won't help, please read the message carefully, if the limit was really raised (there was a Xen bug in handling this parameter and I'm not sure if our version is affected).

I think ours might be. I've added the Xen parameter but Xen didn't recognize it. 
xl dmesg:
```
^C[Vimes@dom0 ~]$ xl dmesg
(XEN) parameter "no-real-mode" unknown!
(XEN) parameter "edd" unknown!
(XEN) parameter "max_grant_frames" unknown!
 Xen 4.12.1
(XEN) Xen version 4.12.1 (user@[unknown]) (gcc (GCC) 8.3.1 20190223 (Red Hat 8.3.1-2)) debug=n  Tue Dec  3 17:17:26 UTC 2019
(XEN) Latest ChangeSet: 
(XEN) Bootloader: GRUB 2.04
(XEN) Command line: placeholder console=none dom0_mem=min:1024M dom0_mem=max:4096M iommu=no-igfx ucode=scan smt=off no-real-mode edd=off max_grant_frames=128
```

Same error message from before but with the max_grant_frames change:
```
[   24.627398] xen:grant_table: xen/grant-table: max_grant_frames reached cur=32 extra=1 limit=32 gnttab_free_count=0 req_entries=1
```
Between the two, it seems that the parameter isn't being recognized.

**Comment by marmarek** [comment]
No, that's another issue. The argument apparently is `gnttab_max_frames`.

**Comment by JarrahG** [comment]
> No, that's another issue. The argument apparently is |gnttab_max_frames|.

I found that one in a Gentoo wiki and tried it too. Exactly the same
error occurs as in the first instance. Though Xen does recognize it.

**Comment by JarrahG** [comment]
I've also just tried setting `max_grant_frames=128` in
`/etc/xen/xl.conf` with no change.

**Comment by marmarek** [comment]
Ok, so this Xen version is affected. Try another method, edit `/usr/share/qubes/templates/libvirt/xen.xml` and add this anywhere within `<devices>`:
```
  <controller type='xenbus' maxGrantFrames='128'/>
```

**Comment by JarrahG** [comment]
|> <controller type='xenbus' maxGrantFrames='128'/>| |
|

|That solved the problem. Window resizing works and the full window is
taken up by the application. Thanks. |
||

**Comment by JarrahG** [comment]
Is the above the permanent solution to eventually be packaged or is the plan to try to patch the Xen bug/wait for Xen 4.13?

**Comment by 92VV3M42d3v8** [comment]
Xen 4.13 is already released.

**Comment by marmarek** [comment]
> Xen 4.13 is already released.

Yes, and the latest test image linked in #5529 already have it included.

**Comment by JarrahG** [comment]
> Yes, and the latest test image linked in #5529 already have it included.

Closing as resolved by this version.

**Comment by 0spinboson** [comment]
Forgive me for apparently being rather slow, but I've added the maxGrantFrames option inside the <devices> section, and yet I'm seeing max_grant_frames 'cur 64 limit 64' in the guest-vmname.log (plus attendant window crashes). What might I be missing?

**Comment by marmarek** [comment]
Do you see it in `virsh -c xen dumpxml VMNAME`?

**Comment by 0spinboson** [comment]
okay, no. it just says <controller type='xenbus' index='0'/> there, as I missed that I placed it in a bit that was inside an if statement that didn't apply. But when I place it anywhere else inside <devices>, the VM won't start, libxl-driver.log says 'invalid argument' (-3).

**Comment by JarrahG** [comment]
Reopening as the issue is back. The default was changed to 64 in Xen 4.13. This still isn't quite enough for a full 4K screen.

**Comment by 0spinboson** [comment]
> Reopening as the issue is back. The default was grant_tables was increased from 32 to 64 in Xen 4.13. This still isn't quite enough for a full 4K screen.
> 
> I've also seen the error above in 4.13. I didn't think it would matter at the time as the issue seemed solved. Fix from above no-longer works.

you're not running into the issue that you can't have VM windows open with a total area of more than ~8Mpixels per VM (at which point the extra area doesn't get drawn)?

**Comment by 0spinboson** [comment]
looks like others ran into this not being easily configurable as well: https://lists.xenproject.org/archives/html/xen-devel/2019-11/msg01607.html

**Comment by 0spinboson** [comment]
it seems changing it to 128 works (using xl set-parameters gnttab_max_frames=128), also allows me to  have multiple UHD-sized windows open.

**Comment by brendanhoar** [comment]
This thread in the debian bug repo about trying to tweak the grant table settings is somewhat alarming: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=880554

My gut says Qubes might want to set a value that covers 4K multi-monitor and lots of VMs running concurrently. Perhaps 256?

B

**Comment by 0spinboson** [comment]
> This thread in the debian bug repo about trying to tweak the grant table settings is somewhat alarming: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=880554
> 
> My gut says Qubes might want to set a value that covers 4K multi-monitor and lots of VMs running concurrently. Perhaps 256?
> 
> B

Interesting, so this issue (and private volumes becoming RO?) may even be related: https://github.com/QubesOS/qubes-issues/issues/5566

**Comment by 0spinboson** [comment]
it looks as though there's also a global issue with a maximum, as having too many windows in 4+ different VMs open also causes trouble, including with file I/O.

**Comment by brendanhoar** [comment]
Have you tried changing it to 256 to see if that reduces/eliminates the issues.

**Comment by 0spinboson** [comment]
yeah, changed it to 256, 368, 512, no dice.

**Comment by brendanhoar** [comment]
https://xenbits.xen.org/docs/unstable/man/xl.conf.5.html also has a map_maxtrack_frames that might come into play.

There seems to be something going upstream from xcp-ng in xen causing them issues with these too: 
https://xcp-ng.org/forum/topic/2109/error-in-xenopsd/4

2019-10-19 stormi:
"Not in this exact form, but I'm trying to build a version of xen that, while still defaulting at 32, allows to change the value for each domain (like [xcp-ng] 7.6 allowed before a Xen change removed that possibility)"

Also:
https://xcp-ng.org/forum/topic/2030/xcp-ng-8-max_grant_frames-reached/4
https://xcp-ng.org/forum/topic/2030/xcp-ng-8-max_grant_frames-reached/17
https://github.com/xcp-ng/xcp/issues/289

2019-10-10 stormi:
"If I understood correctly, previous versions of XCP-ng and XS allowed to raise that value through the platform/max_grant_frames VM parameter, but this ability disappeared due to changes in Xen. In order to take them into account again with the version of Xen that XCP-ng 8.0 uses, one needs to patch xenguest."

Xen patches from above:
https://github.com/xcp-ng-rpms/xen/commit/ac5451a44a5f1fc6f3f152996f154b6ad51ac8bb

B

**Comment by 0spinboson** [comment]
It doesn't seem like doubling the value (which I think was set to 1024?) of map_maxtrack_frames does anything either. But it's very clear that having multiple VMs and VM windows open simultaneously affects dom0's ability to handle the lot of them, especially once the system's been up and running for a few hours. Also keep seeing the IO errors on device xvdb, which appear more quickly the more websites I visit (due to browser caching). Shutting down other VMs doesn't "fix" that, so I guess the other issue isn't directly related.

**Comment by arno01** [comment]
I can confirm (Qubes R4.1 built on 26 Jan 2020 [xen 4.13.0, linux-4.19.94]):
- gedit crashes (when opening multiple files, Ctrl+O, move window around, Ctrl+O, ...)
- gedit crashes and takes down gnome-terminal which was in the background:
  ```
  [arno@dom0 ~]$ grep traps -B1 /var/log/xen/console/guest-personal.log | tail -5
  [2020-01-29 19:37:19] [18883.833226] xen:grant_table: xen/grant-table: max_grant_frames reached cur=64 extra=1 limit=64 gnttab_free_count=0 req_entries=1
  [2020-01-29 19:37:19] [18883.834301] traps: gedit[7048] trap int3 ip:78b3ac174095 sp:7ffefca2a990 error:0 in libglib-2.0.so.0.6000.7[78b3ac139000+82000]
  --
  [2020-01-29 19:37:19] [18883.863759] xen:grant_table: xen/grant-table: max_grant_frames reached cur=64 extra=1 limit=64 gnttab_free_count=0 req_entries=1
  [2020-01-29 19:37:19] [18883.864671] traps: gnome-terminal-[6749] trap int3 ip:7d93ecbe8095 sp:7ffe70aebd30 error:0 in libglib-2.0.so.0.6000.7[7d93ecbad000+82000]
  ```
  ```
  [user@personal ~]$ cat .xsession-errors 
  gntshr: error: ioctl failed: No space left on device
  gntshr: error: ioctl failed: No space left on device
  gntshr: error: ioctl failed: No space left on device
  executed QUBESRPC qubes.WaitForSession dom0 pid 6668
  send exit code 0
  pid 6668 exited with 0
  executed (nowait) QUBESRPC qubes.StartApp+org.gnome.Terminal dom0 pid 6705
  send exit code 0
  ```
- xvdb ext4 got an I/O error, corrupted ext4 FS, luckily ``e2fsck -z undo1 -p /dev/qubes_dom0/vm-work-private`` fixed the FS:
  ```
  [2020-01-27 17:55:24] Fedora 30 (Thirty)
  [2020-01-27 17:55:24] Kernel 4.19.94-1.pvops.qubes.x86_64 on an x86_64 (hvc0)
  [2020-01-27 17:55:24] 
  [2020-01-27 17:55:24] work login: [    8.462764] fuse init (API version 7.27)
  [2020-01-27 17:55:29] [   13.455057] kauditd_printk_skb: 75 callbacks suppressed
  [2020-01-28 03:42:48] [35251.780888] xen:grant_table: xen/grant-table: max_grant_frames reached cur=64 extra=1 limit=64 gnttab_free_count=0 req_entries=1
  [2020-01-28 03:42:48] [35251.817174] traps: gnome-terminal-[981] trap int3 ip:7967735df095 sp:7ffd2c2de890 error:0 in libglib-2.0.so.0.6000.7[7967735a4000+82000]
  [2020-01-28 03:48:22] [35586.122407] print_req_error: I/O error, dev xvdb, sector 63669192
  [2020-01-28 03:48:22] [35586.122487] Aborting journal on device xvdb-8.
  [2020-01-28 03:48:22] [35586.127725] EXT4-fs error (device xvdb): ext4_journal_check_start:61: Detected aborted journal
  [2020-01-28 03:48:22] [35586.127748] EXT4-fs (xvdb): Remounting filesystem read-only
```

I will try the patches https://github.com/xcp-ng-rpms/xen/commit/ac5451a44a5f1fc6f3f152996f154b6ad51ac8bb

**Comment by 0spinboson** [comment]
> **Update:**
> The ad-hoc `xl set-parameter gnttab_max_frames=128` seem to have helped!
> There is also a patch for `xl get-parameter` https://patchwork.kernel.org/patch/10965107/
> 
> **Update2:**
> The permanent fix would be to add `gnttab_max_frames=128` xen argument to `/etc/default/grub` file (`GRUB_CMDLINE_XEN_DEFAULT`), then `grub2-mkconfig -o /boot/efi/EFI/qubes/grub.cfg`

yeah, setting that higher certain alleviated the problem, but they didn't disappear (just run 6-7 VMs at the same time, and open windows in the lot of them).

**Comment by brendanhoar** [comment]
Right, the per-VM resources are still smaller than necessary.

**Comment by arno01** [comment]
I had to bump `128` to `256` (`gnttab_max_frames`) as I had qubes FS corruption again after opening more VM's than usually.
- Is this how the problem should be approached, by increasing `gnttab_max_frames` until it is "just" working?
- Why I haven't encountered the same issue in Qubes R4.0? Some differences between Xen 4.8 and 4.13?

**Comment by marmarek** [comment]
The main difference is that GUI in R4.0 do not use grant tables and in R4.1 it does. And it uses a lot of them.
But it also happens for non-qubes cases in case of large number of virtual disks (also using many grant entries): https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=880554

**Comment by arno01** [comment]
Didn't want to flood, but I really want to mention that after raising the ``gnttab_max_frames`` even higher, from ``256`` up to ``1024``, I can feel how fast everything is now. VM's starting faster, browsers are working faster and smoother.. can't even feel I am running Qubes OS since everything is so smooth & fast :-)

**Comment by brendanhoar** [comment]
> But it also happens for non-qubes cases in case of large number of virtual disks (also using many grant entries): https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=880554

In particular, Xen PV storage drivers support multiple queues through multiple grant tables. Storage IO should be substantially higher performance...assuming there are enough grant table frames to go around...

**Comment by 0spinboson** [comment]
what costs are there to raising the max_frames value, btw?

**Comment by arno01** [comment]
> what costs are there to raising the max_frames value, btw?

Reading this thread https://www.mail-archive.com/xen-devel@lists.xen.org/msg116921.html it looks like there was a thought (by Dongli Zhang) for changing the way grant tables are working (instead of "just" raising the `gnttab_max_frames` value), but it then got quickly rejected as they (Roger Pau Monné) would rather remove the grant tables than making the protocol more complex.

This is why everyone seem to be (acc. to the github code search) "resorted" to increasing the default value of ``gnttab_max_frames`` parameter. I've seen few occasions where people would raise the value up high to values such as ``20000``.

It looks like the grant tables are used by the PV drivers and the only cost that I can think of is that it would just use a bit of more memory:

> Each entry consumes 8 bytes, therefore 512 entries can fit on one page.
> The `gnttab_max_frames` which is a default of 32 pages. Hence 16,384
> grants. The ParaVirtualized (PV) drivers will use the grant reference (index
> in the grant table - 0 .. N) in their command ring.
>
> Source: https://xenbits.xen.org/gitweb/?p=xen.git;a=blob;f=docs/misc/netif-staging-grants.pandoc;h=cb33028adc3dadc8a9fb2a7739af6e5027690f82;hb=HEAD#l73

So, taking the above formula into account, setting the `gnttab_max_frames` to the value of `1024` would mean that Xen can allocate a maximum of `gnttab_max_frames * 512` bytes in RAM, e.g. `1024 * 512` = 512 KiB which isn't that much.

Refs.
- https://github.com/ooni/sysadmin/issues/240#issuecomment-436285298

**Comment by 0spinboson** [comment]
seriously? the overhead is that low, and yet they set the default to like 64? why?

**Comment by 0spinboson** [comment]
@arno01 thanks for finding that, the test command finally showed me that the command line option wasn't applying properly. currently testing 2048 as the max_frames setting.

**Comment by 0spinboson** [comment]
most VMs now up for 23h, no issues yet. seems like it works okay now.

**Comment by 0spinboson** [comment]
@marmarek would you like me to play around with lower gnttab settings to see if those also suffice (e.g. 512 or 368)?

**Comment by marmarek** [comment]
Given the low overhead of 1024 value, I'd go with just that.

**Comment by marmarek** [comment]
Does the value go up after extended usage?

**Comment by 0spinboson** [comment]
Will let you know more in another few days.

It mostly seems to depend on 'peak usage' (and it doesn't seem to release frames, although that may be due to my having set a rather high limit (2048). 
E.g. when I open 6 4k screens worth of windows simultaneously in a single VM, the nr_frames=187, but if I then close all of those and open another few, it stays at 187.

**Comment by brendanhoar** [comment]
There seem to be two major failure modes under Qubes when the grant table availability is constrained: windows failing to render on high-res/multi-monitor systems (somewhat problematic) and filesystem or LVM corruption (extremely problematic). The latter issue is very serious and must be avoided.

So, my opinion: under 4.1, set the *default* grant tables limit to an extremely high number (e.g. 2048) and be done with it (unless someone comes up with a convincing argument otherwise).

**Comment by arno01** [comment]
Whilst setting grant tables to a higher value is significantly increasing the system's performance, it does not appear to be entirely solving the I/O error related issues.
I've opened a separate issue for the I/O error related issues here https://github.com/QubesOS/qubes-issues/issues/5674
