### ISSUE TITLE
Allow show/hide password with a keyboard shortcut on boot auths

### ISSUE THREAD

**Issue by ninavizz** [QubesOS/qubes-issues#5521]
## Problem
I'm a new user both to Qubes, and to using multi-word passphrases. It's torture not being able to see what I'm typing in to either decrypt my drive, or to log-in to Qubes. If I weren't a designer and able to make this suggestion to the project, I'd probably just go back to using single-word easy-to-remember (and hack) passwords, to spare myself the pains of more secure but also more cumbersome behavior choices.

## Solution
Since the UI has not yet fully drawn, add text below the passphrase entry box that suggests a keyboard shortcut to enable hide/show... and pls enable hide/show. We can't "force" users to make safe choices, and when safe choices create too much pain for them they will go with what's easier but dangerous. :) 

![image](https://user-images.githubusercontent.com/8262612/70860040-4b630480-1ed1-11ea-9ec6-a59eac342556.png)

![image](https://user-images.githubusercontent.com/8262612/70870305-750a4300-1f46-11ea-9cc9-d196c291b942.png)

## Of Note
These contribs are mine alone, and unrelated to the SecureDrop Workstation project. :)

**Comment by marmarta** [comment]
I very much like the idea - @marmarek , is this implementable on our end? Can you point me to the appropriate packages? Or is it something to bother anaconda/fedora/??? people about?

**Comment by ninavizz** [comment]
Any chance this'll make it into 4.1 @marmarta ??

**Comment by rustybird** [comment]
Qubes uses [Plymouth](https://gitlab.freedesktop.org/plymouth/plymouth) (for the decryption prompt) and [LightDM](https://github.com/canonical/lightdm) (for the login prompt), maybe try the upstream bug trackers?

**Comment by ninavizz** [comment]
I see no linked PR for this, but somehow recall seeing it mentioned that this had made it into `4.1`

Any progress, perhaps?

**Comment by DemiMarie** [comment]
I would try to implement this, but I have absolutely no idea how to go about it tbh.

**Comment by 51lieal** [comment]
After learning for several days, I've been thinking a workround, and i have learning many too.

What I found :
1. systemd-ask-password only have 3 choice, {echo=yes,no,masked(*)}.
2. cryptsetup is disabling echo.
3. when plymouth is installed, cryptsetup would echo masked.

What I think : 
1. create a new plymouth theme.
3. a non-technical user as mentioned in #5652 would be given additional setup to configure plymouth.
4. adding ask a question in plymouth, user answer the question.
5. answered question would convert 'something' to 'something' (this required manual editing by user, example : user answered 'i am invisible' would be 'am i invisible' or 'asdf1234' be 'qwer7890')

To achieve that, would require modifying systemd unit, adding new service, and creating some script.

That's it for plymouth.
As for xfce login screen I still haven't read, but let's see what i found in next days.

note : consider this as my draft.

**Comment by 51lieal** [comment]
The UI, i found that this is possible.
The mecanism is required to edit the source (both plymouth and login screen), and i wonder that it would break someday. 
Again read this : 

    systemd-ask-password only have 3 choice, {echo=yes,no,masked(*)}.
    cryptsetup is disabling echo.
    when plymouth is installed, cryptsetup would echo masked.

If you have a collection of qubes wallpaper and images you want to implement, i could do pr for the UI.

**Comment by ninavizz** [comment]
@51lieal Dang, all of that looks great—TY so much for looking into all of that! Thoughts @marmarek ??

**Comment by bi0shacker001** [comment]
This appears to already be a thing in 4.2, should this be closed?
