### ISSUE TITLE
Regular UX Reviews

### ISSUE THREAD

**Issue by ninavizz** [QubesOS/qubes-issues#5523]
UX and design problems are difficult to resolve on a team, asynchronously. 

I am a full-time designer & design researcher, and have +20yrs of experience both designing detailed UI solutions, and researching user needs to guide design implementation efforts.

I'd love to volunteer my time to do a weekly or twice-monthly call, where team needs for a UX contributor can be discussed; or, in-progress solutions can be reviewed (as code or mockups). 

While I am a paid contributor to the SecureDrop project, this is a proposal entirely of my own doing and unrelated to work FPF has contracted with the Qubes team to do for the SecureDrop Workstation project. I'd love to see UX design and research work eventually get funded for the Qubes project, but until then—y'all need help from a dedicated practitioner, and I'd love to pick up that ball. 

I'll do my best to follow mentions in GitHub (cough, I only just learned how to do that), but taking time from the regular hustle of PRs and bug fixes to meet to discuss design needs—be they a redesign of a whole tool, fixing a confusing behavior, coming-up with a new icon, or how to get user feedback/input to inform an open issue—can do a lot more in a lot less time, than keeping it all async in GH comments. <3

**Comment by ninavizz** [comment]
## Topics (as design problems) nominated for near-term discussion
- App icon coloring
   - Problem: App icons need to be visually identified as belonging to a specific Qube, when they appear in their various contexts (Spaces, App menu, etc). Currently the "Coloring" of the app icon interferes with recognizing what the app itself is, when much of that information is in the icon's color details.

**Comment by threatmodel-logan** [comment]
Just want to bump this issue.

There's been some discussion in the [qube-users] mailing list about adapting more "friendly" UX and possibly a salt script to make a "Qubes for non-Techy Journalists"

**Comment by ninavizz** [comment]
@threatmodel-logan Sorry I did not see this, before! Yes, that has actually been my own motivation for involving with Qubes. 

Been distracted dealing with my country dissolving into white supremacy moreso than before, but am looking forward to re-engaging with Qubes more, in the days ahead. Will let you and @deeplow know when we start regular UX meetings, again! :)

**Comment by deeplow** [comment]
> Been distracted dealing with my country dissolving into white supremacy moreso than before, but am looking forward to re-engaging with Qubes more, in the days ahead.

Sounds like a pressing issue! Take your time!

And when you're back let's talk about Qubes Usability :smile:. Btw, I've sent you a message on gitter about this issue a while ago.

----

On another note, there is also a discussion on Qubes Usability [on the new Qubes Forum](https://qubes-os.discourse.group/t/qubes-usability-discussion/236/13) in case anyone reading this wants to join in.

**Comment by deeplow** [comment]
@ninavizz is this something you'd still be interested in?

**Comment by ninavizz** [comment]
@deeplow Long term, yes; immediately, aaack. Will get back on this in a month or two? Scoping all of 2021 atm, unfortunately!

**Comment by deeplow** [comment]
> @deeplow Long term, yes; immediately, aaack. Will get back on this in a month or two? Scoping all of 2021 atm, unfortunately!

Ping

**Comment by ninavizz** [comment]
@deeplow "Regular" still feels like a major commitment I may not be ready to make just yet—but I appreciate this nudge. A lot! I had a medical situation arise in January, that only got resolved a few weeks ago. Still catching-up on prep for App Menu user testing—which regrettably has a grant-imposed timeline we're behind on. :/

Perhaps we begin with scheduling a review of user testing prototypes and discuss a testing plan for the App Menu—possibly 2 weeks from now? 

Alternately: Is there something you'd like to nominate for discussion, sooner?

**Comment by DemiMarie** [comment]
> @deeplow "Regular" still feels like a major commitment I may not be ready to make just yet—but I appreciate this nudge. A lot! I had a medical situation arise in January, that only got resolved a few weeks ago. Still catching-up on prep for App Menu user testing—which regrettably has a grant-imposed timeline we're behind on. :/

Glad that you are doing better!

**Comment by deeplow** [comment]
>  had a medical situation arise in January, that only got resolved a few weeks ago.

Oh. Glad you're better now as well.

> @deeplow "Regular" still feels like a major commitment I may not be ready to make just yet—but I appreciate this nudge. A lot!

Yes, I think we shouldn't commit to anything regular atm. More on an "as-needed basis", basis perhaps?

> Perhaps we begin with scheduling a review of user testing prototypes and discuss a testing plan for the App Menu—possibly 2 weeks from now?
> 
> Alternately: Is there something you'd like to nominate for discussion, sooner?

I'd be up for that! But if the grant deadline is pressuring you, feel free to postpone it.

I do have something else that I'd like feedback on: a prototype for the [integrated onboarding tutorial I'm working on](https://github.com/QubesOS/qubes-issues/issues/1395#issuecomment-803401497) (it's a prototype on figma). But since it's for my personal work I'm not sure if it should be included in these meetings (up to you).

**Comment by ninavizz** [comment]
@deeplow If you feel your onboarding tutorial is something you'd like to see Qubes potentially adopt, I say let's make it a priority! If I'm not personally on the hook to present anything, I'm happy to facilitate and be available for feedback as often as folks need. 

Which extends to developers having questions and in search of quick feedback for things they're working on, too.

**Comment by deeplow** [comment]
> @deeplow If you feel your onboarding tutorial is something you'd like to see Qubes potentially adopt, I say let's make it a priority!

Cool! My whole dissertation hypothesis is that it does make a big difference on the onboarding experience. But there are still open questions about the maintainability of said tutorial since it will need to have a high-coupling to other system parts and may potentially break frequently (will depend on how it gets implemented). That's my main concern on the integration of it in Qubes.

So I can't say for sure right now if it's something that should be adopted. Only at the end of the project, when we can measure more accurately the maintainability of the code versus the learnability effectiveness. But I am hopeful.

**Comment by andrewdavidwong** [comment]
Everyone's willingness to do good work and help out is *very* much appreciated, but qubes-issues is not the place for setting up meetings with people, so I'm closing this issue. I notice that the main participants here are also active on the [Qubes Forum](https://qubes-os.discourse.group/). I think that venue would serve your purposes much better.
