### ISSUE TITLE
latest two kernels result in not booting for Heads+Qubes (PrivacyBeast) - also no logs can be displayed during boot

### ISSUE THREAD

**Issue by mfc** [QubesOS/qubes-issues#5524]
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
booting Qubes

**Brief summary**
latest two kernels result in not booting for Heads+Qubes (PrivacyBeast) - also no boot logs shown when I press ESC during boot.

this issue has previously happened with Heads / PrivacyBeast.

**Expected behavior**
1. Updating dom0 kernels shouldn't affect booting of OS. 
2. pressing ESC during boot should allow access to boot logs to understand why there are booting issues.

**Solutions you've tried**
I use Heads OS boot menu to boot an older kernel, currently two-older than current kernel. 

@tlaurion

**Comment by marmarek** [comment]
Can you clarify exact version? I do test it specifically on the certified laptop before pushing the update to stable. The kernel version currently in the stable repository is 4.19.84. I've also tested 4.19.86 and it works for me too.

**Comment by marmarek** [comment]
I'm aware of the boot logs issue.

**Comment by mfc** [comment]
> Can you clarify exact version? I do test it specifically on the certified laptop before pushing the update to stable. The kernel version currently in the stable repository is 4.19.84. I've also tested 4.19.86 and it works for me too.

what's the easiest way to check this besides rebooting and looking at OS boot choices? in Qubes Global Setting it is set to `4.19.84`, i don't know how to find the two newer options if I don't boot from them.

running `[dom0]$ rpm -qa 'kernel-qubes-vm*'` i get: `4.19.82`, `4.19.81`, `4.19.84`

**Comment by marmarek** [comment]
`rpm -qa kernel` will list you installed kernels for dom0
Can you clarify "not booting"? Since you were able to access global settings GUI, definitely you have started something...

**Comment by marmarek** [comment]
Or simply `ls /boot`

**Comment by mfc** [comment]
yep i mentioned the outputs of that earlier (4.19.82, 4.19.81, 4.19.84), and being able to get into Qubes is what happens when i select older kernel in OS boot option. 

the "not booting" is that the system hangs/freezes during boot with the Q logo and the loading bar, about halfway, without log no way to know what it causing it to hang.

when i have more time later today i will reboot and look at the exact boot options, it could be the case that the default boot option is messed up or something

**Comment by tlaurion** [comment]
@mfc: is it still current? I upgrade dom0 in newer images and boot laptops prior to shipping and am not able to reproduce with newer kernels? (And sorry, I never saw this issue :| )

**Comment by mfc** [comment]
no not getting this anymore, now have `4.19.94`,`4.19.84`,`4.19.82`. i'll close. maybe the lack of boot logs should be an issue if doesn't exist.
