### ISSUE TITLE
Create inventory of toast messages

### ISSUE THREAD

**Issue by ninavizz** [QubesOS/qubes-issues#5525]
## Problem
The toast messages include a lot of redundant words. Some of them could benefit from simple white icons to communicate in place of words, too (such as "Attach" or "Detach" or a Qube "Starting" vs "Shutting Down").

## Solution
I'd love to start looking at all of the messaging, holistically. Especially before too much effort is invested in translations. Once I'm able to have a solid inventory of all Toast messaging content, I'll feel comfortable to begin making recommendations to edits to various messages.

## Request
Is there a single file of code—or a handful of code files—that contain the text/formats for all of these? I'm happy to own the task of compiling it all into a spreadsheet for reference, but I would love to see where all of these messages exist in the code, first. @andrewdavidwong might you be able to point me to some files?

**Comment by marmarta** [comment]
Unfortunately there's no single file for that - they are basically in https://github.com/QubesOS/qubes-desktop-linux-manager/tree/master/qui , scattered in various files, findable through:
- emit_notification or send_notification functions 
- self.notify in the clipboard.py widget

**Comment by ninavizz** [comment]
Most awesome, ty @marmarta! I'll fork the repo and search those files against those queries, as my starting point.

**Comment by ninavizz** [comment]
Closing, as this is largely redundant with #6634

**Comment by andrewdavidwong** [comment]
Out of curiosity, why not keep this one open and close #6634 as a duplicate of it?

**Comment by ninavizz** [comment]
@andrewdavidwong Because this was just for toast messages (the black "Qubes is doing blah" bubbles), whereas #6634 is for all messages—error, info, activity, etc.
