### ISSUE TITLE
Building Qubes R4.1 aborts with "File not signed"

### ISSUE THREAD

**Issue by GWeck** [QubesOS/qubes-issues#5526]
**Qubes OS version**
Qubes R4.0.2 fully updated trying to build R4.1

**Affected component(s) or functionality**
Qubes Builder

**Brief summary**
When building R4.1, using the setup script and selecting Fedora-30 as build environment, the command *make qubes* aborts with the message 
`Filename: /home/user/qubes-builder/cache/fc30/base_rpms/acl-2.2.53-3.fc30.x86.rpm ist not signed.  Exiting!`
If Fedora-29 is selected instead, a similar error occurs.

**To Reproduce**
Build R4.1 according to the domumentaion in *Building Qubes OS ISO*(https://www.qubes-os.org/doc/qubes-iso-building/). The error occurs no matter if `NO_SIGN = 1` is set or not.

**Expected behavior**
*make qubes* should create the data for the command *make iso*.

**Actual behavior**
The build aborts.

**Additional context**
If the rpms in this directory are checked via *rpm -K*, the command tells that digests and signatures are o.k. for all files.

**Solutions you've tried**
Changing the reference to the makefile for Fedora in 
`qubes-builder/qubes-src/builder-rpm/Makefile.builder`
from *Makefile.rmpbuilder* to *Makefile-legacy.rpmbuilder* lets the command complete successfully. In this case, however, *make iso* aborts, because it does not find `qubes-builder/qubes-src/installer-qubes-os`.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
*Building Qubes OS ISO*(https://www.qubes-os.org/doc/qubes-iso-building/) and related docs

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
possibly #4458

**Comment by GWeck** [comment]
In order to get this far in the build process, the component *vmm-xen-stubdom-legacy* has to be disabled by commenting it out in  `qubes-builder/example-configs/qubes-os-master.conf`. Otherwise, the build process terminates already during *make get-sources* with the error message
`-> Updating sources for vmm-xen-stubdom-legacy...
--> Fetching from https://github.com/marmarek/qubes-vmm-xen-stubdom-legacy.git master...
--> Verifying tags...
No valid signed tag found!
---> One of invalid tag:
error: Tag 'mm_78690eb8-1-gd387ad5' nicht gefunden.
make: *** [Makefile:203: vmm-xen-stubdom-legacy.get-sources] Fehler 1
`

**Comment by marmarek** [comment]
I recommend using QubesOS org as a source, not my github account. Some repositories on my account may be heavily work in progress.

**Comment by marmarek** [comment]
Anyway, in this particular case, there is a signed tag on top of my master branch (`mm_d387ad57`), it's weird that it hasn't been downloaded.

**Comment by GWeck** [comment]
The error might be caused since I commented the line out, instead of deleting it. The *get-sources* seems to have terminated there, I got further by deleting the line completely, and also `tpm-extra,` `trousers-changer` and `antievilmaid`. In this case, I got to
`--> Downloading additional sources for desktop-linux-xfce4-garcon...` 
where I got the error
`make[1]: *** [Makefile.common:43: garcon-0.6.2.tar.bz2] Fehler 8
make: *** [Makefile:205: desktop-linux-xfce4-garcon.get-sources-extra] Fehler 2`
It's probably the best that I abort this build and repeat it from the Qubes OS repository. I will tell the result in one or two days.
Thank you anyhow!

**Comment by GWeck** [comment]
I Tried to build R4.1 from the Qubes OS stable repository, based on Fedora-29. The *make get-sources*  phase completed without error.
The phase *make qubes*, however, terminated again with the error message
`-> Verifying signatures...
Filename: /home/user/qubes-builder/cache/fc29/base_rpms/acl-2.2.53-2.fc29.x86_64.rpm is not signed.  Exiting!`
The command
`rpm -K /home/user/qubes-builder/cache/fc29/base_rpms/*.rpm`
returned for each file
`digests SIGNATURES NICHT OK`
If I do the same in a Fedora-30 build environment, I still get the corresponding error message, aborting the build, although `rpm -K` tells `digests signatures OK`

**Comment by marmarek** [comment]
Can you run `rpm -Kv` on such package?

**Comment by GWeck** [comment]
For fc 30, I get:
`/home/user/qubes-builder/cache/fc30/base_rpms/zlib-1.2.11-19.fc30.x86_64.rpm:
    Header V3 RSA/SHA256 Signature, Schlüssel-ID cfc659b9: OK
    Header SHA256 digest: OK
    Header SHA1 digest: OK
    Payload SHA256 digest: OK
    V3 RSA/SHA256 Signature, Schlüssel-ID cfc659b9: OK
    MD5 digest: OK`
For fc29, the result is:
`/home/user/qubes-builder/cache/fc29/base_rpms/zlib-1.2.11-18.fc29.x86_64.rpm:
    Header V3 RSA/SHA256 Signature, Schlüssel-ID 429476b4: NOKEY
    Header SHA256 digest: OK
    Header SHA1 digest: OK
    Payload SHA256 digest: OK
    V3 RSA/SHA256 Signature, Schlüssel-ID 429476b4: NOKEY
    MD5 digest: OK`
and similar for the other files.

**Comment by GWeck** [comment]
See also #5003 for using the current R4.1 ISO

**Comment by faerbersteve** [comment]
I face the similar issue when I try to build qubes os on my Fedora 31 machine.
When I run `make manager` I get the error on a different package.
Here is the output after `make manager`:
`-> Preparing fc31 build environment
-> Initializing RPM database...
-> Retreiving core RPM packages...
-> Verifying signatures...
Filename: /home/a/qubes/qubes-builder/cache/fc31/base_rpms/abattis-cantarell-fonts-0.111-3.fc31.noarch.rpm is not signed. Exiting!
make[1]: *** [/home/a/qubes/qubes-builder/qubes-src/builder-rpm/Makefile-legacy.rpmbuilder:41: /home/a/qubes/qubes-builder/chroot-dom0-fc31/home/user/.prepared_base] Fehler 1
make[1]: Verzeichnis „/home/a/qubes/qubes-builder“ wird verlassen`

I modified the script `prepare-chroot-base` (in build-rpm) and added the result of the signature check to the output.
The result of the signature check is `digests signatures OK`.
I have rpm version 4.15.1 installed on my machine.
It seems that the output text of rpm has changed with the new version.

I have fixed the script by changing `$PGP_SIGNED` to `digests signatures OK`.
After fixing the script the build went through successful.

**Comment by marmarek** [comment]
Are you sure you have up to date sources? The script does support rpm>=4.14 output here: https://github.com/QubesOS/qubes-builder-rpm/blob/master/prepare-chroot-base#L20

**Comment by faerbersteve** [comment]
Yes, I have downloaded the sources today.
I followed strict the guide [Qubes Builder](https://www.qubes-os.org/doc/qubes-builder/) 

Here you can see the complete output: https://pastebin.com/raw/yP9LfPp5

**Comment by adubois** [comment]
> Yes, I have downloaded the sources today.
> I followed strict the guide [Qubes Builder](https://www.qubes-os.org/doc/qubes-builder/)
> 
> Here you can see the complete output: https://pastebin.com/raw/yP9LfPp5

@faerbersteve 
Your output indicate that : This key does not have a trustworthy signature (translation from Dieser Schlüssel trägt keine vertrauenswürdige Signatur).
Have you followed [this](https://www.qubes-os.org/doc/VerifyingSignatures)?

**Comment by GWeck** [comment]
This seems to be related to a problem that showed up on creating QWT: Fedora changed the output of the `rpm` command such that parsing this output in the installation will fail. See [Testing Windows and QWT in R4.1](https://qubes-os.discourse.group/t/testing-windows-and-qwt-in-r4-1/1143/36)

As there are no new posts in the last several months, I am closing it now. If you believe this is a mistake, please leave a comment, and I'll be happy to reopen this. Thank you.
