### ISSUE TITLE
New Created AppVMs has private volume to be from unspecified where, rather than designated one.

### ISSUE THREAD

**Issue by ThinerDAS** [QubesOS/qubes-issues#5528]
**Qubes OS version**
_The version of Qubes OS you're using (e.g., `R4.0`), available via the command `cat /etc/qubes-release` in a dom0 terminal._

Qubes Release 4.0 (R4.0)

Fully updated as on Dec 17, 2019

**Affected component(s) or functionality**
_The component or functionality of Qubes OS that is not working as expected._

VM / Volumes

**Brief summary**
_A clear and concise summary of the bug._

Newly created AppVM will have its initial private volume to be the same regardless of the TemplateVM it is created from. I cannot determine where the initial private volume is from, but it mismatches with the root volume.

**To Reproduce**
_Steps to reproduce the behavior:_
_1. Having many TemplateVMs. (I guess two is sufficient but you should be able to distinguish the private storages of the two templates)_
_2. Try creating AppVMs based on different TemplateVMs._
_3. Find the VMs that have their private volume mismatch with their root ones or the template they are made from._

**Expected behavior**
_A clear and concise description of what you expected to happen._

No mismatch happens.

**Actual behavior**
_What actually happened (instead of what you expected to happen)._

On my QubesOS installation, the private volume is a fixed one, regardless of the template the AppVM come from.

**Solutions you've tried**
_If applicable, any solutions or workarounds you've already tried._

I would try to add a line `'source':None,` in `appvm.py` and reboot my machine later and see whether the private volume is correct.

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
_A list of links to other bug reports, feature requests, or tasks in the qubes-issues tracker (or "none" if you didn't find any). Do not describe any other unreported bugs, features, or tasks here._

[Issue 2256](https://github.com/QubesOS/qubes-issues/issues/2256) contains the commit that I suspect to be the culprit.

This [commit](https://github.com/QubesOS/qubes-core-admin/commit/80b459b6d5bc930fe2f01b09c50b8d7b83a3ecbb#diff-6043435a643c7257f60ee20ba460c2bb) may be relevant. I believe that 'source' slot of AppVM should exist and be None

**Update**

I believe I finally work out the logic here. Each time an AppVM is created, the private volume device is created EMPTY. Then at first startup of the AppVM the private volume is initialized (formatted, folder created, etc). The home folder is copied first from `/home.orig`, and then populated by the applications installed in the TemplateVM. (For example if the template has firefox installed, then `.mozilla` folder is created and initialized)

This logic is tricky and subtle. For example, if in a template an application is installed by default in /usr/local, it will be lost in new-created AppVMs. And this behavior (the use of `/home.orig`) is under-documented as far as I am concerned.

This could be a pure documentation issue.

**Comment by hexagonrecursion** [comment]
related: https://github.com/QubesOS/qubes-issues/issues/5286

**Comment by andrewdavidwong** [comment]
This appears to be a [duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) of #5286. If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.
