### ISSUE TITLE
Display "updates pending" icon for Dom0 correctly.

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#553]
**Reported by joanna on 30 Apr 2012 12:27 UTC**
... as indicated by qubes-dom0-update. Further, after I clicked on the Update button for Dom0, I got the message that there were no updates for Dom0. I closed the gpk-viewer window, yet this annoying icon is still being shown, urging me to update Dom0...

manager 1.2.14
core 2.0.22

Migrated-From: https://wiki.qubes-os.org/ticket/553

**Comment by qubenix** [comment]
This issue is re-existing for me since I updated about 12 hours ago.

Qubes manager is showing updates pending icon for dom0 even though there are none.
