### ISSUE TITLE
installer: Allow users to choose between Debian and Fedora

### ISSUE THREAD

**Issue by zaoqi** [QubesOS/qubes-issues#5533]
**The problem you're addressing (if any)**
I need to change all VM templates to Debian and uninstall Fedora templates after installation

**Describe the solution you'd like**
Allow users to choose between Debian and Fedora

**Where is the value to a user, and who might that user be?**
People using other distributions

**Describe alternatives you've considered**

**Additional context**

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

**Comment by marmarek** [comment]
Implemented here: https://github.com/QubesOS/qubes-anaconda-addon/pull/7
