### ISSUE TITLE
Add size to block devices list in devices widget

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#5541]
**The problem you're addressing (if any)**
Add size to block devices list in devices widget

**Describe the solution you'd like**
Besides device description, add a device/partition size. This is especially helpful when partitions are not labeled.

**Where is the value to a user, and who might that user be?**
It will ease distinguishing devices.

**Comment by brendanhoar** [comment]
Peanut gallery note: if possible think about the order of text layout so the list is easier to scan, perhaps putting same-width or padded-with info leftmost and varying-width info to the right. In addition consider enhanced layout when grouping devices and associated partitions such that the associations are very clear vs. unrelated devices.
