### ISSUE TITLE
UI - clarification needed for "Qubes Global Settings - Default Memory Settings"

### ISSUE THREAD

**Issue by brendanhoar** [QubesOS/qubes-issues#5546]
**The problem you're addressing (if any)**
An end user is likely to misunderstand the use of these memory settings.

e.g. 
My Minimal qube memory setting is 164MiB, but my system is running mirageOS VMs with only 32MB of memory. That seems like it conflicts with the settings, but it does not.

**Describe the solution you'd like**
1. Change "Default Memory Settings" to "Default Memory *Balancer* Settings" (or similar).
2. Possibly add parenthetical below the section title that it only applies to dom0 and other VMs that have memory balancing enabled on their Qubes Settings page.
3. Possibly also change description of the two values in that section to be more clear. e.g. "dom0 memory boost" ... does it mean that dom0 should never be asked by qmemman to give up RAM when it is allocated  at or below the combination of the two values? Or???

**Where is the value to a user, and who might that user be?**
Any user who might want clarity that these values relate only to memory *balancing*.

**Describe alternatives you've considered**
Popup help text to explain a bit more how these values are used by the system.

B

**Comment by andrewdavidwong** [comment]
CC: @marmarta, @ninavizz
