### ISSUE TITLE
Anaconda crashes installing Qubes-4.0.1 on hp Pavilion dv5

### ISSUE THREAD

**Issue by DSJ2** [QubesOS/qubes-issues#5548]
### Qubes OS version: 
Qubes-4.0.1

### Affected component(s) or functionality:
anaconda installer

---

### Steps to reproduce the behavior:
Boot the installer off a verified USB image. Anaconda will crash roughly 2 minutes after X starts.

### Expected or desired behavior:
Installer runs to completion.

### Actual behavior:
Anaconda reports "an error occurred"

### General notes:

---

### I have consulted the following relevant [documentation](https://www.qubes-os.org/doc/):
https://www.qubes-os.org/doc/reporting-bugs/
https://www.qubes-os.org/doc/
https://www.qubes-os.org/intro/
https://www.qubes-os.org/faq/
https://www.qubes-os.org/security/
https://www.qubes-os.org/doc/system-requirements/
https://www.qubes-os.org/doc/installation-guide/
https://www.qubes-os.org/getting-started/

### I am aware of the following related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues:
I've reviewed the issues that "is:open is:issue installer" finds in the tracker; none appear to be related. The symptoms listed in 4474, 4524, and 4941 are all different.

[Qubes-anaconda-crash.zip](https://github.com/QubesOS/qubes-issues/files/4009019/Qubes-anaconda-crash.zip)

**Comment by marmarek** [comment]
This is very interesting crash. It appears anaconda don't like pre-existing LVM volume with name starting with `+`.

**Comment by DSJ2** [comment]
Confirmed, removing the existing thin pool allows the installer to run.

**Comment by andrewdavidwong** [comment]
@marmarek, does that mean that this is an upstream bug in Anaconda?

**Comment by sjvudp** [comment]
Today I also had an anaconda crash right at the beginning of installation attempt on a machine where I had installed Qubes OS two times before, and after hitting reset, I also could install it another time.
![Screenshot (big & blurry, no GIMP in Quebes OS)](https://user-images.githubusercontent.com/6734808/74389258-e9098000-4dfd-11ea-9c79-33ddff911ca8.jpg)

**Comment by Gundaris** [comment]
Got the exact same issue during installation. I have tried remove all data from target device, as some forums suggested this was the issue. But no luck. i have tried multiple times, but no luck.  installing Qubes-R4.0.4-x86_64
![unnamed](https://user-images.githubusercontent.com/40198256/118033943-ae2c2a00-b369-11eb-8d95-f377e62f58ef.jpg)
