### ISSUE TITLE
Xorg crashes when activating a second 4k monitor

### ISSUE THREAD

**Issue by 0spinboson** [QubesOS/qubes-issues#5549]
**Qubes OS version**
R4.0, completely up to date, running kernel 5.4.x

**Affected component(s) or functionality**
X, VM guis

**Brief summary**
When I attach a second 4k screen, and disabled mirroring in the display settings, X crashes and I'm kicked out to the login screen, but I can no longer log in. 
Separately/connected, when I try to restore VM windows using qvm-start-gui --all after disconnecting 1 monitor (which allows me to log back in), this doesn't produce any windows, nor does restarting the VM entirely solve that problem.

**To Reproduce**
(using a radeon vega 56 (8gb ram), amdgpu kernel driver)
1. connect a second 4k screen
2. click on 'system tools/display'
3. untick 'mirror'

**Expected behavior**
Can extend screen to the second monitor

**Actual behavior**
X crashes, and I get kicked to the login screen, while all of the domU windows disappear.
[journalctl output.log](https://github.com/QubesOS/qubes-issues/files/4012156/xcrash.log)

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
I've tried to search for solutions using search engine, and in the google group. Cannot find relevant results.

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
this may be related to the (secondary) qvm-start-gui issue: https://github.com/QubesOS/qubes-issues/issues/3175 ?

**Comment by 0spinboson** [comment]
(This doesn't occur in the Qubes 4.1 build I tested yesterday.)

**Comment by marmarek** [comment]
Looks like a bug in amdgpu driver. Some more details may be in Xorg log (/var/log/Xorg.0.log). I don't think there is anything Qubes-specific in here.
Qubes 4.1 has much newer xorg drivers, so this is probably why it works there.
