### ISSUE TITLE
Feature: shut down VMs in sequence

### ISSUE THREAD

**Issue by tetrahedras** [QubesOS/qubes-issues#5561]
Right now if I have 2 VMs which are interdependent (e.g one provides network for the other) then I can start them simultaneously with `qvm-start vm1 netvm` (or even just `qvm-start vm1`) but I cannot shut them down simultaneously:
```
$ qvm-shutdown vm1 netvm
netvm: Shutdown error: There are other VMs connected to this VM: vm1
```

If qvm-shutdown gets a request to shut down a VM which is connected to a VM which it is currently shutting down, and there are no other VMs connected to the depended-upon VM, then it should wait until the dependent VM has shut down and then shut down the depended-upon VM. (Just as qvm-start does, but in reverse order.)

**Comment by marmarek** [comment]
It will work if you use `qvm-shutdown --wait`.

**Comment by GWeck** [comment]
Could this be made available (as an option) in the Qube Manager?

**Comment by andrewdavidwong** [comment]
> It will work if you use `qvm-shutdown --wait`.

Given that this is already implemented, what (if anything) should be the desired behavior for @tetrahedras' example, `qvm-shutdown vm1 netvm`?

Should this also shut down the VMs in sequence? Should the error message inform the user about `--wait`?

**Comment by tetrahedras** [comment]
On Wed, Jan 08, 2020 at 03:06:45AM -0800, Andrew David Wong wrote:
>> It will work if you use `qvm-shutdown --wait`.
>
>Given that this is already implemented, what (if anything) should be the desired behavior for @tetrahedras' example, `qvm-shutdown vm1 netvm`?
>
>Should this also shut down the VMs in sequence? Should the error message inform the user about `--wait`?

Probably the latter. This might be considered more of a documentation
bug:

that `--wait` will let VMs shut down in sequence (as opposed to merely
waiting until the VMs have shutdown before returning) does not appear in
either `qvm-shutdown --help` or `man qvm-shutdown`.

**Comment by SaswatPadhi** [comment]
This may be a dumb question, but is there a reason why `--wait` isn't the default?

When would the non-`--wait` behavior be desired? Does it have any advantages (or is faster than) `--wait`?

**Comment by tetrahedras** [comment]
Yes, I think in retrospect this is a very simple issue to solve: add documentation to `qvm-shutdown` explaining the full implications of the `--wait` option!

Relevant pull request:
https://github.com/QubesOS/qubes-core-admin-client/pull/122

**Comment by tetrahedras** [comment]
Something odd: when I use `--wait` to shutdown the qubes `my-VPN` and
`my-VPN-browsing-vm` then I still get the message that "my-VPN failed to
shutdown because my-VPN-browsing-vm is still connected". However, it
eventually still works (my-VPN and my-VPN-browsing-vm both shut down in
sequence)

**Comment by andrewdavidwong** [comment]
> Something odd: when I use `--wait` to shutdown the qubes `my-VPN` and `my-VPN-browsing-vm` then I still get the message that "my-VPN failed to shutdown because my-VPN-browsing-vm is still connected". However, it eventually still works (my-VPN and my-VPN-browsing-vm both shut down in sequence)
> […](#)
> On Thu, Jan 09, 2020 at 05:46:19PM -0800, Saswat Padhi wrote: This may be a dumb question, but is there a reason why `--wait` isn't the default? When would the non-`--wait` behavior be desired? Does it have any advantages (or is faster than) `--wait`? -- You are receiving this because you were mentioned. Reply to this email directly or view it on GitHub: [#5561 (comment)](https://github.com/QubesOS/qubes-issues/issues/5561#issuecomment-572836350)

This sounds like it might be #5591.

**Comment by marmarek** [comment]
Since documentation is updated for `qvm-shutdown --wait`, there is nothing more to do here.
