### ISSUE TITLE
Write errors in two different VMs at basically the same time (Qubes 4.1)

### ISSUE THREAD

**Issue by 0spinboson** [QubesOS/qubes-issues#5566]
**Qubes OS version**
Qubes 4.1, 12-27 iso

**Affected component(s) or functionality**
blkfront?

**Brief summary**
I'm seeing "Buffer IO errors on device xvdb" in the guest-.log of two different VMs, 1 second apart (with no interaction from me).

**Actual behavior**
[guest-Personal.log](https://github.com/QubesOS/qubes-issues/files/4049086/guest-Personal.log)
[guest-wd.log](https://github.com/QubesOS/qubes-issues/files/4049087/guest-wd.log)

**Comment by arno01** [comment]
Looks like related to https://github.com/QubesOS/qubes-issues/issues/5519#issuecomment-579907517

**Comment by 0spinboson** [comment]
better issue -> https://github.com/QubesOS/qubes-issues/issues/5674
