### ISSUE TITLE
TemplateVM backup cannot be deleted properly

### ISSUE THREAD

**Issue by zaoqi** [QubesOS/qubes-issues#5567]
**Qubes OS version**
4.0.2-rc3

**Affected component(s) or functionality**

**Brief summary**
TemplateVM backup cannot be deleted properly
cannot reinstall TemplateVM

**To Reproduce**
_Steps to reproduce the behavior:_
1. `sudo qubes-dom0-update --action=reinstall qubes-template-fedora-30`
2. open `Qube Manager` to remove the backup

**Expected behavior**
reinstall qubes-template-fedora-30
completely delete the backup of TemplateVM

**Actual behavior**

```
[user@dom0 ~]$ sudo qubes-dom0-update --action=reinstall qubes-template-fedora-30
WARNING: Replacing a template will erase all files in template's /home and /rw !
Template VM halted
Attempting to operate on template of UpdateVM... backing up fedora-30 to fedora-30-backup-20200111-Gosb
fedora-30-backup-20200111-Gosb: Cloning private volume
fedora-30-backup-20200111-Gosb: Cloning root volume
Using sys-firewall as UpdateVM to download updates for Dom0; this may take some time...
Fedora 25 - x86_64 - Updates                     68 kB/s |  24 MB     06:01    
Fedora 25 - x86_64                              2.2 MB/s |  50 MB     00:22    
Qubes Dom0 Repository (updates)                 981 kB/s |  16 MB     00:16    
determining the fastest mirror (15 hosts).. done..3 kB/s | 2.7 kB     00:00 ETA
Qubes Templates repository                      846  B/s |  14 kB     00:17    
Installed package qubes-template-fedora-30-4.0.1-201912111336.noarch not available.
Error: No packages marked for reinstall.
[user@dom0 ~]$ 
```
`fedora-30-backup-20200111-Gosb` remains in the menu.

**Additional context**

**Solutions you've tried**
```
[user@dom0 ~]$ find -name '*Gosb*'
./.config/menus/applications-merged/user-fedora-30-backup-20200111-Gosb-vm.menu
[user@dom0 ~]$ rm ./.config/menus/applications-merged/user-fedora-30-backup-20200111-Gosb-vm.menu
```

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

**Comment by hexagonrecursion** [comment]
possible duplicate: https://github.com/QubesOS/qubes-issues/issues/5193
