### ISSUE TITLE
Time synchronization problem: incorrect time in VMs after resuming from suspend

### ISSUE THREAD

**Issue by frederikfaye** [QubesOS/qubes-issues#5568]
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
Sys-Whonix time synchronisation

**Brief summary**
After sleeping (I think), I will not be able to connect via sys-whonix, due to a time synchronisation issue. 

**To Reproduce**
Put computer to sleep for an extended period of time. 

**Expected behavior**
Should still be able to connect through sys-whonix after waking computer.

**Actual behavior**
Is not able to connect through sys-whonix after waking computer.

**Additional context**
The Time Synchonisation Monitor icon will change to a large cross. 
The following are what I think are relevant snippets of the sdwdate's log:

The first thing in the log is the following:
```
Possible causes:

- The host clock is wrong -> shut down the VM, fix the clock in the host and restart the VM.

- The VM clock is wrong -> manually fix the clock. Restart Tor if necessary. Then restart sdwdate.

- A host clock attack succeeded.

- A hardware issue (for example bios clock issues).
```

Then, further down:

```
2020-01-10 21:17:15 - sdwdate - INFO - Success. Sleeping for 144.53333333333333 minutes.
2020-01-10 21:17:15 - sdwdate - INFO - Running command: sleep 8672.971586236
2020-01-10 21:17:15 - /usr/bin/whonix-gateway-firewall - OK: Skipping firewall mode detection since already set to 'full'.
2020-01-10 21:17:15 - /usr/bin/whonix-gateway-firewall - OK: (Full torified network access allowed.)
2020-01-10 21:17:15 - /usr/bin/whonix-gateway-firewall - OK: Whonix firewall loaded.
2020-01-10 22:40:19 - /usr/lib/sdwdate/suspend-pre - INFO - Creating /run/sdwdate/sdwdate_was_running.status...
2020-01-10 22:40:19 - /usr/lib/sdwdate/suspend-pre - INFO - Done, created /run/sdwdate/sdwdate_was_running.status.
2020-01-10 22:40:19 - /usr/lib/sdwdate/suspend-pre - INFO - Stopping sdwdate...
2020-01-10 22:40:19 - sdwdate - INFO - sclockadj not running, ok.
2020-01-10 22:40:19 - sdwdate - INFO - delete temp_dir: /tmp/tmp.h0sjG7HSaJ
2020-01-10 22:40:19 - sdwdate - INFO - Signal SIGTERM received. sdwdate stopped by user or system. 
2020-01-10 22:40:19 - /usr/lib/sdwdate/suspend-pre - INFO - Done, stopped sdwdate.
2020-01-10 22:40:19 - /usr/lib/sdwdate/suspend-pre - INFO - Deleting /run/sdwdate/first_success...
2020-01-10 22:40:20 - /usr/lib/sdwdate/suspend-pre - INFO - Done, deleted /run/sdwdate/first_success.
2020-01-10 22:40:20 - /usr/lib/sdwdate/suspend-pre - INFO - Deleting /run/sdwdate/success...
2020-01-10 22:40:20 - /usr/lib/sdwdate/suspend-pre - INFO - Done, deleted /run/sdwdate/success.
2020-01-10 22:40:20 - /usr/lib/sdwdate/suspend-pre - INFO - Entering Whonix firewall timesync-fail-closed mode.
2020-01-10 22:40:20 - /usr/bin/whonix-gateway-firewall - OK: Skipping firewall mode detection since already set to 'full'.
2020-01-10 22:40:20 - /usr/bin/whonix-gateway-firewall - OK: (Full torified network access allowed.)
2020-01-10 22:40:21 - /usr/bin/whonix-gateway-firewall - OK: Whonix firewall loaded.
2020-01-10 22:40:21 - /usr/lib/sdwdate/suspend-pre - INFO - Done, entered Whonix firewall timesync-fail-closed mode.
2020-01-10 22:40:21 - /usr/lib/sdwdate/suspend-pre - INFO - Creating /run/sdwdate/tor_was_running.status...
2020-01-10 22:40:21 - /usr/lib/sdwdate/suspend-pre - INFO - Done, created /run/sdwdate/tor_was_running.status.
2020-01-10 22:40:21 - /usr/lib/sdwdate/suspend-pre - INFO - Stopping Tor...
2020-01-10 22:40:21 - /usr/lib/sdwdate/suspend-pre - INFO - Done, stopped Tor.
2020-01-10 22:40:28 - /usr/lib/sdwdate/suspend-post - INFO - Deleting /run/sdwdate/sdwdate_was_running.status...
2020-01-10 22:40:29 - /usr/lib/sdwdate/suspend-post - INFO - Done, deleted /run/sdwdate/sdwdate_was_running.status.
```

I reckon that sys-whonix is told to stop when entering sleep mode, but then is unable to reconnect properly when waking again. 
It seems that `sudo qvm-sync-clock` in a dom0 terminal might fix the issue, but I would prefer not having to do this after everytime my computer sleeps. 

Any help appreciated.

**Comment by xaki23** [comment]
> ```
> Possible causes:
> 
> - The host clock is wrong -> shut down the VM, fix the clock in the host and restart the VM.
> 
> - The VM clock is wrong -> manually fix the clock. Restart Tor if necessary. Then restart sdwdate.
> 
> - A host clock attack succeeded.
> 
> - A hardware issue (for example bios clock issues).
> ```

> It seems that `sudo qvm-sync-clock` in a dom0 terminal might fix the issue, but I would prefer not having to do this after everytime my computer sleeps.

did you actualy check where/what clock is wrong?
and what steps fix it?

qvm-sync-clock in dom0 is unlikely to help since that syncs clock from clockvm to dom0.
this would fix "clock is wrong in dom0".
running qvm-sync-clock in your domU would sync from clockvm (or dom0) to the domU.

its a lot easier to come up with an automatic workaround when you know what needs fixing.
(and this sounds more like a whonix problem than qubes, but ...)

**Comment by frederikfaye** [comment]
@xaki23 No, I did not check where the clock is wrong - the main reason I'm writing in here is because I need help troubleshooting, hence I unfortunately cannot tell you exactly what needs fixing. 

Running `qvm-sync-clock` (with or without sudo) gives a `Request refused`.

**Comment by xaki23** [comment]
qvm-sync-clock always needs to be run as root // with sudo.
"Request refused" indicates you are trying it from an anon-vm or have unusual policies set.

to see in which VMs the clock is wrong, just open a terminal in them and run "date". 
(no sudo required for that)

vms that may be relevant for this are:
 - dom0
 - clockvm (default is sys-net, but you can check "qubes-prefs clockvm" in dom0)
 - sys-whonix

also try simply restarting your sys-whonix.
you can hard-restart it without shutting down the vms below it: qvm-kill sys-whonix ; qvm-start sys-whonix

**Comment by frederikfaye** [comment]
@xaki23 Thanks for the suggestions. 
I did indeed try `sudo qvm-sync-clock` in an AppVM (personal, with a debian-10 template, with sys-whonix networking), and it fails. I do not believe I have unusual policies set. 

Both sys-whonix and personal has wrong datetimes, however not the same. 

Restarting sys-whonix always works, but this is super annoying to do everytime I put my computer into sleep mode. Also, this does not fix the faulty datetime in sys-whonix (or in personal, for that matter). 

Any ideas? Can I somehow force these VMs to check and sync the time after sleeping?

**Comment by andrewdavidwong** [comment]
Is sys-whonix the only VM affected by this?

**Comment by frederikfaye** [comment]
No, personal also has the wrong time currently. It seem to be the same problem as in https://github.com/QubesOS/qubes-issues/issues/3374#issuecomment-381211224. I'm getting very similar output to running the commands given in the next comment by the same user, i.e.,
```
No usable clock interface found.
hwclock: Cannot access the Hardware Clock via any known method.
```

I unfortunately fail to understand what the fix is, following the mentioned threads (https://github.com/QubesOS/qubes-issues/issues/4266, https://github.com/QubesOS/qubes-issues/issues/4939).

**Comment by xaki23** [comment]
> ```
> No usable clock interface found.
> hwclock: Cannot access the Hardware Clock via any known method.
> ```

 - hwclock can/will only work in dom0 and only matters immediately after system full boot.
 - dom0 clock only matters for dom0, for domU while the clockvm (check qubes-prefs) is not running, and for a really brief moment during domU startup.
 - running appvm clocks being very slow to sync even if your clockvm has the right time is somewhat normal, the default interval is "check/sync every 6 hours".

tbh i dont know how whonix ties into all this, i just know a bit too much about the regular qubes clocksync mechanism.
i am also not familiar with suspend/resume (since its somewhere between "doesnt work" and "why would anyone do that" for me).

but to get back on track towards a solution ... 
... is there already some kind of event/hook in dom0 that could be used to trigger "run this after resume" tooling?

**Comment by andrewdavidwong** [comment]
> > since its somewhere between "doesnt work" and "why would anyone do that" for me
> 
> I'm not talking about hibernation, mind you. However, maybe I should adapt a similar thing. Do you simply choose "Xfce Power Manager > When Laptop lid is closed > Lock Screen" (for both On battery and Plugged in)?
> 
> EDIT: Ohh, actually I just found out that "System sleep mode" was set to "Hibernate" for "On battery", under "Xfce Power Manager" and then the "System" tab. That could very well be what causes all the problems. Does this mean that I have some huge hibernation file laying around somewhere on my disk?

Xen does not support hibernation, so hibernation is not possible in Qubes OS.

**Comment by andrewdavidwong** [comment]
> It seem to be the same problem as in #3374 (comment).

@marmarek, is this a duplicate of #3374?

**Comment by frederikfaye** [comment]
> Xen does not support hibernation, so hibernation is not possible in Qubes OS.

Glad to hear that! :)

**Comment by marmarek** [comment]
Just to be clear on terminology:
 - "suspend": suspend to ram, aka ACPI S3 - this one works on qubes
 - "hibernation": suspend to disk - this one does not

> I did indeed try `sudo qvm-sync-clock` in an AppVM (personal, with a debian-10 template, with sys-whonix networking), and it fails. I do not believe I have unusual policies set.

Do you have any extra tags set on this personal AppVM, like `anon-vm`? Normally, Whonix Workstation vms use a whonix-specific time synchronization method and are not allowed to run normal `qvm-sync-clock`, but non-whonix AppVM connected to sys-whonix is something in between. By default it should be allowed, unless you add `anon-vm` tag (which you may find in some whonix documentation).
If that's not the case, observe logs in dom0 with `journalctl -f` while calling `sudo qvm-sync-clock` in the AppVM. You should see some `qrexec ...` line. Looking at `/etc/qubes-rpc/policy/qubes.GetDate` may be helpful too.

**Comment by frederikfaye** [comment]
- I don't think I have any special tags added to the AppVM.
- The "personal" AppVM was created at installation of R4.0, and I then restored my old "personal" AppVM from a backup, which was also a R4.0 install, and that "personal" AppVM was also created through the installation of Qubes. 
- The "personal" AppVM is based on my debian-10 template, not a whonix workstation, so I guess it's in the in-between category. Is it not advisable to get network from sys-whonix on an AppVM that is not based on whonix-ws?

> observe logs in dom0 with journalctl -f while calling sudo qvm-sync-clock in the AppVM. You should see some qrexec ... line

The output is:
```
qubes.GetDate: personal -> @default: denied: denied by policy /etc/qubes-rpc/policy/qubes.GetDate:6
```
which refers to `$tag:anon-vm    $anyvm  deny`.

Does this hint at that my personal is indeed an `anon-vm`? How do I check this?

I should note that `date` now in the "personal" VM gives the correct output, after restarting it. I'm having trouble reproducing the problem reliably, so sorry about the speculations regarding its cause!

**Comment by marmarek** [comment]
>     * Is it not advisable to get network from sys-whonix on an AppVM that is not based on whonix-ws?

It should be fine.

> Does this hint at that my personal is indeed an `anon-vm`? How do I check this?

Yes, it looks like it. See `qvm-tags` tool.
I guess you may have changed personal's VM template to whonix-ws in the past temporarily and the tag stayed.

**Comment by frederikfaye** [comment]
Thanks, that worked! 

I did `qvm-tags personal del anon-vm` in dom0, and I'm now able to do `sudo qvm-sync-clock` in my personal AppVM.
I hope this will allow the AppVM to stay in sync, and thus allow for the whonix networking to function properly.
