### ISSUE TITLE
Problem installing qubes os(Compatibility)

### ISSUE THREAD

**Issue by liberatefrog** [QubesOS/qubes-issues#5569]
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
Qubes installation

**Brief summary**
I have problem installing Qubes OS on my desktop, and failed again on another one.
I think there is a compatibility problem with Intel 9th gen CPU, AMD Thread ripper CPU, and Nvidia 20th gen GPU

**To Reproduce**
1. boot from USB drive burnt with Qubes OS R4.0.iso
2. click install or install without GTK UI
3. face the black screen if clicking install, and face error if clicking install without GTK UI

**Expected behavior**
Proceed to the installation procedure

**Actual behavior**
Black Screen or error log

**Screenshots**
Pictures here (Link Expired)

**Additional context**
_Add any other context about the problem here._

**Solutions you've tried**
I tried to remove "quite of course" and "rhgb", or change the set up of computer. It did not work. Iommu and VT-D was turned on.
First computer: Motherboard: MSI-X399 CPU: 2990WX RAM: 64G
Second computer: Motherboard: Gigabyte Z390 CPU: 9900K RAM: 24G

**Comment by xaki23** [comment]
> I think there is a compatibility problem with Intel 9th gen CPU, AMD Thread ripper CPU, and Nvidia 20th gen GPU

> Black Screen or error log


probably "way too new" hardware.

does a fedora-31 boot on these machines? https://getfedora.org/en/workstation/download/

if that supports your hardware, you could try one of the qubes 4.1 QA builds.
a recent iso can be found here: https://openqa.qubes-os.org/tests/5250#downloads
or start at https://openqa.qubes-os.org/ and click a 4.1 build, any of the "green/yellow/red" dots, then logs+assets tab and grab the iso. 

note that 4.1 is far from user-grade and probably not usable at all, but even just seeing if it boots into a working GUI would be a relevant data point.

**Comment by liberatefrog** [comment]
Fedora 31 works on my computer!

**Comment by liberatefrog** [comment]
Updated photos [https://t.me/s/qubeserrorliberatefrog/12](url)

**Comment by 0spinboson** [comment]
nah, those CPUs should both work fine. The Nvidia GPU is much more likely to be the problem, as nouveau support for those is probably terrible. 

frog: you've enabled SVM and IOMMU in bios? Next, try disabling modesetting for the nvidia GPU (nouveau.modeset=0), as that's highly likely not to work.

**Comment by liberatefrog** [comment]
> 
> 
> nah, those CPUs should both work fine. The Nvidia GPU is much more likely to be the problem, as nouveau support for those is probably terrible.
> 
> frog: you've enabled SVM and IOMMU in bios? Next, try disabling modesetting for the nvidia GPU (nouveau.modeset=0), as that's highly likely not to work.

I tried to connect the HDMI cable directly to the motherboard instead of the GPU. It worked!!! Thanks!!
Is the compatibility problem of Nvidia solvable?

**Comment by 0spinboson** [comment]
> > nah, those CPUs should both work fine. The Nvidia GPU is much more likely to be the problem, as nouveau support for those is probably terrible.
> > frog: you've enabled SVM and IOMMU in bios? Next, try disabling modesetting for the nvidia GPU (nouveau.modeset=0), as that's highly likely not to work.
> 
> I tried to connect the HDMI cable directly to the motherboard instead of the GPU. It worked!!! Thanks!!
> Is the compatibility problem of Nvidia solvable?

you can probably install the closed driver in dom0 (see the qubes docs for a possibly-outdated guide), but it'd be a lot easier to just buy a second-hand rx550 through 570, or rx460, if you can find one. (rx580 is an option as well, but also overkill). And even the Intel iGPU is probably good enough for generating the output (so unless you want a multimonitor setup).
