### ISSUE TITLE
battery meter / widget misreporting ("charging" while discharging) - levono x230, coreboot, 3rd party battery

### ISSUE THREAD

**Issue by ghost** [QubesOS/qubes-issues#5571]
**Qubes OS version**
4.0 fully updated

**Affected component(s) or functionality**
battery or power widget in system tray (I may have the terminology wrong - top right of screen)

**Brief summary**
Been on battery for at least 2 hours, tells me it is _charging_ and I have a couple of hours until charged. "charging (39%, 2 hours)". Then ~30min later "charging (31%, 2 hours and 35 minutes).

EDIT: tried it again on the following night, same behavior.

Machine: Levono x230, coreboot. Uses an aftermarket battery.

**To Reproduce**

**Expected behavior**
Widget should say "discharging", with estimate of time remaining.

**Actual behavior**
widget reports "charging", and does not offer an estimate of battery time remaining.

**Comment by andrewdavidwong** [comment]
This might be specific to your laptop model. I am not seeing this on my laptop.

**Comment by MondayPeople** [comment]
Yes, I started to wonder. 
Have updated the initial post to be specific, help searches.

**Comment by MondayPeople** [comment]
(cannot edit original post for some reason)

Noticed something relevant:
1. Above behavior is observed after laptop has been removed from dock while operating (i.e. AC to battery). 
2. When laptop is suspended on dock, removed, then resumed only on battery, widget behaves normally.

Guess its a dock-detection thing.

**Comment by rapenne-s** [comment]
Could you try on a newer kernel?
