### ISSUE TITLE
Sys-USB issue while installing

### ISSUE THREAD

**Issue by 92VV3M42d3v8** [QubesOS/qubes-issues#5574]
**Qubes OS version**
Version 4.0.2rc3 but issue was also present with qubes4.0.1 stable
**Affected component(s) or functionality**
Sys-USB creation

**Brief summary**
Sys-USB cannot be created

**To Reproduce**
Installing Qubes with default configuration proceed until we reach on phase "setting up networking". This step stucks for almost half an hour then Error msg appears.
If we disable sys-usb creation while trying reinstallation it proceed without error and qubes running smoothly and as expected sys-USB is not created.

**Expected behavior**
Qubes should have installed with sys-USB during first install itself.

**Actual behavior**
I wasn't able to install with sys-USB

**Screenshots**
Error Msg says-
[systemctl', 'start', 'qubes-vm@sys-usb.service'] failed:
stdout: ""
stderr: "Job for qubes-vm@sys-usb.service failed because the control process exited with error code.
See "systemctl status qubes-vm@sys-usb.service" and "journalctl '-xe" for details.
"
**Additional context**
I am installing on desktop system with MSI tomahawk motherboard with latest proprietary bios with all type of virtualisation enabled, AMD Ryzen 5 3600 CPU, 8 GB RAM, NVIDIA GPU.

**Solutions you've tried**
I installed successfully without sys-USB

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
I tried every documentation. Nothing mentioned about this error.

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
I am not aware if there is.

**Comment by 0spinboson** [comment]
to be clear: you have both SVM and IOMMU enabled?
can you share the output of 'journalctl -xe'? Or is that the message you get during setup?

**Comment by 92VV3M42d3v8** [comment]
This same issue occured while installing Qubes build 4.1 20200113 and I just pressed enter, Qubes started but on checking status of sys-USB it was not there. I tried to install sys-USB by running command in terminal In Dom0 which gave no error. After even a few restarts, It worked fine. So I thought problem may be solved in this build but on shutting down system and on starting again, CPU went in soft lock up. I have to reinstall system again to solve that problem.

**Comment by 92VV3M42d3v8** [comment]
> to be clear: you have both SVM and IOMMU enabled?
> can you share the output of 'journalctl -xe'? Or is that the message you get during setup?

yup, both enabled.
I don't know where to look for that output.

**Comment by john590** [comment]
> I don't know where to look for that output.

You have to run command in dom0 terminal.

**Comment by 92VV3M42d3v8** [comment]
Is this issue somehow may be related to #3518 ?

**Comment by 92VV3M42d3v8** [comment]
Today I tried 14 feb build of Qubes-4.1 and tried to install with sys-usb. It failed as previous attempts. I found in logs following-
"Service -start Qubes VM sys-usb
usr/lib/systemd/system/qubes-vm@.service: enabled; vendor preset: disabled)
exit-code) since sun 2020-02-16 23:50:00 EST: 3min 36s ago
exited, status=1/FAILURE)

Starting start Qubes VM sys-usb...
            Start failed: Internal error: Unknown PCI header type '127' for device '0000:28:00.3' , see /var/log
            qubes-vm@sys-usb.service: Main process exited, code=exited, status=1/failure
             qubes-vm@sys-usb.service: failed with result exit code
 failed to start Qubes-vm sys-usb

**Comment by unman** [comment]
@92VV3M42d3v8  Need a little more information.
Are you using onboard USB or card?
What is `device 0000000:28:00.3` ?

How many USB controllers do you have?
If you create a USB qube, can you add individual controllers to it, and start it succesfully? (This might help to narrow down the issue.)
Read [this page](https://www.qubes-os.org/doc/usb-qubes/) for advice on manually creating a usb qube.

**Comment by 92VV3M42d3v8** [comment]
This is in "systemctl status qubes-vm@sys-usb.service"

![IMG_20200216_235741_1](https://user-images.githubusercontent.com/58817562/74655840-f10e4a80-5184-11ea-80da-a738e5794be6.jpg)

And following are from -journal

![IMG_20200217_000348](https://user-images.githubusercontent.com/58817562/74656204-95908c80-5185-11ea-9713-8596f859a33f.jpg)

**Comment by 92VV3M42d3v8** [comment]
![IMG_20200217_000603](https://user-images.githubusercontent.com/58817562/74656469-18194c00-5186-11ea-817d-68f1cecda303.jpg)
![IMG_20200217_000627](https://user-images.githubusercontent.com/58817562/74656578-4bf47180-5186-11ea-843e-a9aeba8c9635.jpg)

**Comment by 92VV3M42d3v8** [comment]
![IMG_20200217_000747](https://user-images.githubusercontent.com/58817562/74656826-d5a43f00-5186-11ea-8af3-faa3844d6fa5.jpg)
![IMG_20200217_000830](https://user-images.githubusercontent.com/58817562/74656903-01bfc000-5187-11ea-8197-f93ff2ea7841.jpg)

**Comment by 92VV3M42d3v8** [comment]
I will try manual method and try to update soon.

**Comment by 92VV3M42d3v8** [comment]
I have two USB controllers if I am right.( I am assuming this by devices available in settings of VMs) These are **03:00.0 USB controller: Advanced Micro Devices, INC AMD 400 series chipset USB 3.1 XHCI controller** and 28:00.3 USB controller: Advanced Micro Devices, INC AMD Matisse USB 3.0 Host controller.

**Comment by 92VV3M42d3v8** [comment]
When I tried manual method and created a template based VM sys-usb (HVM) and assigned it the above mentioned XHCI controller following error occured.
![IMG_20200217_114711](https://user-images.githubusercontent.com/58817562/75176716-ac455f00-5702-11ea-9904-c66ca7e12a52.jpg)

When I tried same for AMD Mattisse My PC just became irresponsive but no error message appeared, I have to restart my PC after that.
On using command line method sys usb got created and both controller were assigned to sys-usb but I was not able to start that.
So is this an hardware issue? @unman or Qubes issue?

**Comment by 0spinboson** [comment]
have you tried enabling permissive mode ('strict reset' off) for the usb controllers?

**Comment by 92VV3M42d3v8** [comment]
Thanks @0spinboson. I was able to create a sys-USB with manual method and no-strict-reset for device 03:00.0 USB controller: Advanced Micro Devices, INC AMD 400 series chipset USB 3.1 XHCI controller but still cannot assign 28:00.3 USB controller: Advanced Micro Devices, INC AMD Matisse USB 3.0 Host controller. to it by any means. One strange thing that I encountered is that I use usb mouse and I allowed it to dom0 always without asking with RPC policy but sometime it is available and sometime not after next boots. This behaviour is unpredictable. Is this somehow related to #5686? The issue of no-strict-reset is because of What? I have a SATA controller on 03:00.1 and PCI Bridge on 03:00.2. And Non essential instrumentaion reserved SPP on 28:00.0, Encryption controller on 28:00.1 and Audio device on 28:00.4

**Comment by 0spinboson** [comment]
Glad it worked. Check this doc about auto enabling mouse: https://www.qubes-os.org/doc/usb-qubes/#auto-enabling-a-usb-mouse

**Comment by 92VV3M42d3v8** [comment]
So closing this issue as it is an hardware issue I think. I was not able to attach USB 3.0 controller to sys-usb though. Referenced https://www.qubes-os.org/faq/#i-created-a-usbvm-and-assigned-usb-controllers-to-it-now-the-usbvm-wont-boot and https://www.qubes-os.org/doc/usb-qubes/#auto-enabling-a-usb-mouse and https://www.qubes-os.org/doc/usb-qubes/ and tried everything that is available in qubes-user mailing list.
@andrewdavidwong It could be great if we have proper documentation about these kind of issue solving in the same page USB-Qubes of documentation. And In PCI device documention, a note  may be added like what are the risk associated if no strict reset option is followed. Is it worth it to create sys-usb with such options. And cand risk be mitigated if usb block devices are attached to only one VM until reboots.

**Comment by andrewdavidwong** [comment]
> It could be great if we have proper documentation about these kind of issue solving in the same page USB-Qubes of documentation. And In PCI device documention, a note may be added like what are the risk associated if no strict reset option is followed. Is it worth it to create sys-usb with such options. And can risk be mitigated if usb block devices are attached to only one VM until reboots.

Please feel free to open a doc issue and/or PR for this.

**Comment by 92VV3M42d3v8** [comment]
Similar issue (possibly) here- https://openqa.qubes-os.org/tests/10828#step/firstboot/14

**Comment by marmarek** [comment]
> Similar issue (possibly) here- https://openqa.qubes-os.org/tests/10828#step/firstboot/14

Unlikely - that one looks like a timeout caused by slow nested virtualization.

**Comment by 92VV3M42d3v8** [comment]
This issue is not occuring with new build on openQA as system allowed sys-usb creation with no-strict-reset without any user input. The real surprise was that my Matisse controller, which I was not able to attach even with no-strict-reset previously is attached to this new sys-net (which also include sys-usb) and my PC is working extremely fine. No unresposiveness, no softlock etc. This made me to think if it was a hardware issue in first place itself?

**Comment by 0spinboson** [comment]
Or new kernel
