### ISSUE TITLE
qubes.ConnectTCP not working since last update

### ISSUE THREAD

**Issue by nil0x42** [QubesOS/qubes-issues#5575]
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
qubes.ConnectTCP

**Description**
Some weeks ago, is started using the inter-VM port forwarding capability offered by qubes.ConnectTCP (https://www.qubes-os.org/doc/firewall/#opening-a-single-tcp-port-to-other-network-isolated-qube).

I needed my `srv` Qube to be reachable on port 8080 from both `client` & `client2` Qubes.
So i added the following:
* `dom0:/etc/qubes-rpc/policy/qubes.ConnectTCP`
```
client @default allow,target=srv
client2 @default allow,target=srv
```
* `client:/rw/config/rc.local`
```
qvm-connect-tcp 8080:@default:8080
```
* `client2:/rw/config/rc.local`
```
qvm-connect-tcp 8080:@default:8080
```

The expected behavior is that when `client` Qubes connects to localhost:8080, socket is forwarded to `srv:8080`. And it worked fine when i made this setup some weeks ago.

But today, after upgrading and rebooting my machine, i discovered that my daemon on `srv` VM could not start anymore ! Indeed, it doesn't start because the port **8080** is already in use...

After taking a look on `srv` Qube, it looks like Qubes OS is responsible for this:
```
user@srv :: ~ $ nc -lvp 8080
Ncat: Version 7.70 ( https://nmap.org/ncat )
Ncat: Listening on :::8080
Ncat: bind to 0.0.0.0:8080: Address already in use. QUITTING.
```
```
user@srv :: ~ $ netstat -tanp
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 127.0.0.1:631           0.0.0.0:*               LISTEN      -                   
tcp        0      0 127.0.0.1:8080          127.0.0.1:8080          ESTABLISHED 16858/socat         
tcp6       0      0 ::1:631                 :::*                    LISTEN      - 
```
```
user@srv :: ~ $ sudo pstree -a
systemd --system --deserialize 47
  └─qrexec-fork-ser
      └─qrexec-fork-ser
          └─qubes.ConnectTC /etc/qubes-rpc/qubes.ConnectTCP 8080
              ├─qubes-rpc-multi -l /usr/lib/qubes/qubes-rpc-multiplexer qubes.ConnectTCP+8080 client
              │   └─cat
              ├─qubes-rpc-multi -l /usr/lib/qubes/qubes-rpc-multiplexer qubes.ConnectTCP+8080 client
              │   ├─logger -t qubes.ConnectTCP+8080-client
              │   └─tee /tmp/qrexec-rpc-stderr-return.16826
              └─socat STDIO TCP:localhost:8080
```

So there is a `socat` process on **srv Qube** that is using the port `8080` and impeaches the real daemon to start. As you can see, this `socat` process is being called by qubes.ConnectTCP.

**Comment by marmarek** [comment]
>               └─socat STDIO TCP:localhost:8080

This call looks correct, like connecting to port 8080 on localhost. 

> tcp        0      0 127.0.0.1:8080          127.0.0.1:8080          ESTABLISHED 16858/socat

Are you sure it is the same socat process? socat with "TCP:localhost:8080" target normally choose ephemeral source port. Maybe some recent socat change?

**Comment by nil0x42** [comment]
Hello, now i am sure, i just ran `pstree -ap`:
```
└─socat,16858 STDIO TCP:localhost:8080
```

Yes, it might be due to a recent socat change on fedora repo

**Comment by marmarek** [comment]
You can try changing `socat STDIO:localhost:$PORT` call into `nc localhost $PORT` in `/etc/qubes-rpc/qubes.ConnectTCP` in your template. You may need to install nc.

**Comment by nil0x42** [comment]
Hi ! Since i changed `/etc/qubes-rpc/qubes.ConnectTCP` with `nc` according to what @marmarek said, it worked for 1 month. Now, the problem appeared again, even though i checked the changed file, and it is still using `nc` instead of `socat`.

It looks like netcat started acting the same way as socat, using the same source port.

`$ sudo netstat -talnp`
```
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 127.0.0.1:631           0.0.0.0:*               LISTEN      426/cupsd           
tcp        0      0 127.0.0.1:8080          127.0.0.1:8080          ESTABLISHED 12961/nc            
tcp6       0      0 ::1:631                 :::*                    LISTEN      426/cupsd
```

**Comment by marmarek** [comment]
@pwmarcz have you seen such socat/nc behavior (not necessary on qubes)?

**Comment by pwmarcz** [comment]
No, looks very weird. If both socat and nc exhibit the same behaviour, I would suspect system configuration. Just in case, can you check `sysctl net.ipv4.ip_local_port_range`? (it's `32768 60999` for me).

(@marmarek we don't have anything that modifies settings around there, do we?)

The output of netstat (if there are no other processes listening at 8080) suggests that `nc` is connected to itself. I can reproduce that by doing `nc -p 8080 localhost 8080`.

**Comment by marmarek** [comment]
> (@marmarek we don't have anything that modifies settings around there, do we?)

No.

**Comment by matheusd** [comment]
I was having a similar issue, debugging with netcat a vm interconnection that was previously working.

One thing that seems to have solved it for me (at least temporarily) is to edit the corresponding policy in dom0's `/etc/qubes-rpc/policy/qubes.ConnectTCP` to `ask` instead of `allow`, running the command once, then switching back to `allow`. Looks like there's some auth flag somewhere that was set to refuse the `connectTCP` RPC call, even though the appropriate policy was set to `allow`.
