### ISSUE TITLE
Qubes R4.0 buster template fails on "qubes-vm-dependencies : Depends: qubes-gui-agent but it is not going to be installed"

### ISSUE THREAD

**Issue by arno01** [QubesOS/qubes-issues#5580]
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
``qubes-builder -> linux-template-builder -> buster`` (TemplateVM)

**Brief summary**

- ``qubes-vm-dependencies`` requires ``qubes-gui-agent`` -> https://github.com/QubesOS/qubes-meta-packages/blob/release4.0/rpm_spec/qubes-vm-meta-packages.spec.in#L23
-  ``qubes-gui-agent`` requires ``python%{python3_pkgversion}-xcffib`` https://github.com/QubesOS/qubes-gui-agent-linux/blob/release4.0/rpm_spec/gui-agent.spec.in#L58
- ``buster`` does not have ``python3-xcffib`` package
- hence ``buster`` template fails on "qubes-vm-dependencies : Depends: qubes-gui-agent but it is not going to be installed" 

```
+ mount /dev/loop0p3 mnt
+ export INSTALLDIR=mnt
+ INSTALLDIR=mnt
+ /home/arno/qubes-builder/qubes-src/builder-debian/template_debian/04_install_qubes.sh
Adding 'local diversion of /sbin/initctl to /sbin/initctl.distrib'
Get:1 file:/tmp/qubes_repo buster InRelease
...
...
...
Processing triggers for libc-bin (2.28-10) ...
Setting up qubes-usb-proxy (1.0.27+deb10u1) ...
Setting up qubes-core-agent-networking (4.0.51-1+deb10u1) ...
Setting up qubes-input-proxy-sender (1.0.16-1+deb10u1) ...
Setting up mate-notification-daemon (1.20.2-1) ...
Setting up qubes-core-agent-network-manager (4.0.51-1+deb10u1) ...
Setting up qubes-vm-recommended (4.0.6-1+deb10u1) ...
Processing triggers for initramfs-tools (0.133+deb10u1) ...
Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 qubes-vm-dependencies : Depends: qubes-gui-agent but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
Removing 'local diversion of /sbin/initctl to /sbin/initctl.distrib'
++ cleanup
++ errval=100
++ trap - ERR
++ trap
++ umount_kill /home/arno/qubes-builder/qubes-src/linux-template-builder/mnt
```

**To Reproduce**
Try to build a buster template using qubes-builder.
Target: Qubes R4.0; stable; + stable repo (current one, not current-testing!)

**Expected behavior**
buster template should be built.

**Actual behavior**
buster templatevm fails to build because ``qubes-vm-dependencies`` wants ``qubes-gui-agent``.

**Additional context**

buster templatevm fails to build because ``qubes-vm-dependencies`` wants ``qubes-gui-agent``, and ``qubes-gui-agent`` wants ``python3-xcffib`` and ``qt4-qtconfig``.

Then, there is no ``python3-xcffib`` package in the repo.

I've tried populating the ``qubes-builder/qubes-src/builder-debian/template_debian/packages_qubes.list`` as buster wanted, but then it failed on:

```
Package python3-xcffib is not available, but is referred to by another package.
```

**Solutions you've tried**

```
$ cat /home/arno/qubes-builder/qubes-src/builder-debian/template_debian/packages_qubes.list
qubes-vm-dependencies
qubes-gui-agent
python3-xcffib
qt4-qtconfig
```

```
+ readarray -t packages
+ info 'Packages: qubes-vm-dependencies' qubes-gui-agent python3-xcffib qt4-qtconfig
+ output 'INFO: Packages:' qubes-vm-dependencies qubes-gui-agent python3-xcffib qt4-qtconfig
+ '[' 0 -ge 1 ']'
+ aptInstall qubes-vm-dependencies qubes-gui-agent python3-xcffib qt4-qtconfig
+ files='qubes-vm-dependencies qubes-gui-agent python3-xcffib qt4-qtconfig'
+ chroot_cmd apt-get -o Dpkg::Options::=--force-confnew --yes -o Acquire::Retries=3 -o Dpkg::Options::=--force-unsafe-io --download-only install qubes-vm-dependencies qubes-gui-agent python3-xcffib qt4-qtconfig
+ '[' '' == 1 ']'
+ /usr/sbin/chroot mnt apt-get -o Dpkg::Options::=--force-confnew --yes -o Acquire::Retries=3 -o Dpkg::Options::=--force-unsafe-io --download-only install qubes-vm-dependencies qubes-gui-agent python3-xcffib qt4-qtconfig
Reading package lists...
Building dependency tree...
Reading state information...
Package python3-xcffib is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'python3-xcffib' has no installation candidate
+ cleanup
+ errval=100
+ trap - ERR EXIT
+ trap
+ error '/home/arno/qubes-builder/qubes-src/builder-debian/template_debian/04_install_qubes.sh: Error.  Cleaning up and un-mounting any existing mounts'
+ output 'ERROR: /home/arno/qubes-builder/qubes-src/builder-debian/template_debian/04_install_qubes.sh:' Error. Cleaning up and un-mounting any existing mounts
+ '[' 0 -ge 1 ']'
+ umount_all
```

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

- ``qubes-vm-dependencies`` requires ``qubes-gui-agent`` -> https://github.com/QubesOS/qubes-meta-packages/blob/release4.0/rpm_spec/qubes-vm-meta-packages.spec.in#L23
-  ``qubes-gui-agent`` requires ``python%{python3_pkgversion}-xcffib`` https://github.com/QubesOS/qubes-gui-agent-linux/blob/release4.0/rpm_spec/gui-agent.spec.in#L58

- https://github.com/QubesOS/qubes-issues/issues/4140#issuecomment-564344242
- https://github.com/QubesOS/qubes-issues/issues/4443#issuecomment-436484078

**Comment by marmarek** [comment]
There is indeed no python3-xcffib in standard Debian buster repositories, but we ship one ourselves: https://github.com/QubesOS/qubes-python-xcffib/
https://deb.qubes-os.org/r4.0/vm/pool/main/x/xcffib/

Are you sure you have enabled 'current' repository? Alternatively you can built it yourself by adding `TEMPLATE += python-xcffib` at the end of your `builder.conf`.

**Comment by arno01** [comment]
Thank you, Marek.
It must have been something wrong on my side. When I've restarted the build from the scratch everything worked just fine. I should have tried that in the first place, sigh.
