### ISSUE TITLE
R4.0 XEN 4.8 has reached EOL

### ISSUE THREAD

**Issue by zaoqi** [QubesOS/qubes-issues#5583]
**Qubes OS version**
R4.0

**Additional context**
https://wiki.xenproject.org/wiki/Xen_Project_Release_Features
```
Security support until Dec 2019
```

**Comment by marmarek** [comment]
Yes, we're aware. We'll provide security support for Xen 4.8 in Qubes 4.0, as long as Qubes 4.0 is supported.
