### ISSUE TITLE
archlinux: The output of `pacman -S` in TemplateVM is weird

### ISSUE THREAD

**Issue by zaoqi** [QubesOS/qubes-issues#5585]
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
archlinux Template

**Brief summary**

**To Reproduce**
_1. run `sudo pacman -Syu`

**Expected behavior**
```
$ sudo pacman -Syu
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
:: Starting full system upgrade...
 there is nothing to do
```

**Actual behavior**
TemplateVM:
```
$ sudo pacman -Syu
:: Synchronizing package databases...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  135k  100  135k    0     0  75815      0  0:00:01  0:00:01 --:--:-- 75857
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1643k  100 1643k    0     0   283k      0  0:00:05  0:00:05 --:--:--  334k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 4887k  100 4887k    0     0   485k      0  0:00:10  0:00:10 --:--:--  937k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  161k  100  161k    0     0  88009      0  0:00:01  0:00:01 --:--:-- 88009
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
:: Starting full system upgrade...
 there is nothing to do
```
AppVM:
```
$ sudo pacman -Syu
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
:: Starting full system upgrade...
 there is nothing to do
```

**Solutions you've tried**
check difference between `/home`/`/rw` of TemplateVM and `/home`/`/rw` of AppVM

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

**Comment by ejose19** [comment]
This is because pacman is using TemplateVM proxy via curl, instead of native one. Wouldn't say it's a bug, you can disable the proxy in pacman config and enable network access to the TemplateVM and it will work the same as a normal AppVM, but then you would lose the benefits of having no network access to the TemplateVM.

**Comment by marmarek** [comment]
Shouldn't there be some curl option to hide those messages?

**Comment by ejose19** [comment]
There are multiple options here:

1. Using -s hides all the output (but then you don't know about any errors or progress)
2. Using -s -S hides all output but shows errors (including those 404 on -Syu)
3. Using -# switch to a simpler progress bar, way less verbose than reported behaviour but doesn't show download speed.

@zaoqi if you want to use any of those options, create 02-curl-override.conf in /etc/pacman.d/ with the following content and replace $FLAG with the one you want to use

```
[options]
XferCommand = /usr/bin/env ALL_PROXY=http://127.0.0.1:8082/ /usr/bin/curl $FLAG -C - -f -o %o %u
```

**Comment by zaoqi** [comment]
@ejose19 If do not use the "external downloader" and use environment variables instead, everything will work fine.

**Comment by ejose19** [comment]
@zaoqi Yes, that's another way to make it work like if template had internet. @marmarek is there any particular reason the use of variables for pacman is not the default behaviour?

**Comment by marmarek** [comment]
> @marmarek is there any particular reason the use of variables for pacman is not the default behaviour?

Yes - to limit network access to package manager only. The whole point about this proxy is to prevent accidental access to network from within template and limit its exposure to untrusted data.

See https://www.qubes-os.org/doc/software-update-domu/#updates-proxy

**Comment by ejose19** [comment]
@marmarek what about overriding pacman with an alias? like:
```
alias pacman="sudo ALL_PROXY=http://127.0.0.1:8082 pacman"
```
Other commands would still have no implicit access to proxy.

**Comment by marmarek** [comment]
Alias is a fragile solution (think of different shells, scripts etc) - when it will sometimes work and sometimes not it will be very confusing. But maybe a wrapper script placed earlier in `$PATH`?

**Comment by ejose19** [comment]
For anyone stumbling on this, here's my solution based on @marmarek suggestion:

- create a file on ```/usr/local/bin``` called ```qpacman``` (Qubes pacman)
```bash
#!/bin/bash

# Wrapper script for pacman under Qubes OS template
/usr/bin/env ALL_PROXY=http://127.0.0.1:8082/ /usr/bin/pacman $@
```

- make it executable
- add this to ```/rw/config/rc.local```
```bash
# Remove option file created by /usr/lib/qubes/update-proxy-configs
# as XferCommand cannot be unset in a follow-up config file
rm /etc/pacman.d/01-qubes-proxy.conf
```

- restart the template, now you can use it with ```sudo qpacman``` and it will show the usual output.

Note: You can rename ```qpacman``` to any other non-conflicting name that you prefer to use.

**Comment by fepitre** [comment]
@ejose19: what about calling it `pacman` too and place it earlier in the `$PATH` like @marmarek suggested? If that works properly do you mind to adapt current implementation in `core-agent-linux`?

**Comment by ejose19** [comment]
@fepitre sure, I can submit a PR. Any recommended folder to place this script since it will be at the start of ```$PATH```?

**Comment by fepitre** [comment]
@ejose19 If we plan to create a custom location and add PATH to it, maybe something like `/usr/lib/qubes/bin` (currently in-existent)? @marmarek a suggestion?

**Comment by fepitre** [comment]
After discussing with Marek, `/usr/sbin` could be a better option instead of custom `PATH`.

**Comment by ejose19** [comment]
@fepitre I tried with that last suggestion but didn't manage to make it work. /usr/sbin is a symlink to /usr/bin and unlinking the pacman in /usr/sbin removes it from /usr/bin as well (where the original is located). Is there something I'm missing? Else I can proceed with first suggestion ```/usr/lib/qubes/bin```

**Comment by fepitre** [comment]
> @fepitre I tried with that last suggestion but didn't manage to make it work. /usr/sbin is a symlink to /usr/bin and unlinking the pacman in /usr/sbin removes it from /usr/bin as well (where the original is located). Is there something I'm missing? Else I can proceed with first suggestion `/usr/lib/qubes/bin`

I was not aware that `/usr/sbin` was a symlink under archlinux. So probably better go with the first suggestion. Ensure to make it system wide in any case that something would called `pacman` directly without specific location.

**Comment by marmarek** [comment]
Fixed in https://github.com/QubesOS/qubes-core-agent-linux/pull/254
