### ISSUE TITLE
icons in Qube Manager sometimes offset

### ISSUE THREAD

**Issue by zaoqi** [QubesOS/qubes-issues#5586]
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
Qube Manager

**Brief summary**
icons in Qube Manager sometimes offset

**To Reproduce**
Create and remove qubes

**Actual behavior**
icons in Qube Manager sometimes offset

**Screenshots**

![Screenshots](https://user-images.githubusercontent.com/19170231/72677298-c07bb800-3ad5-11ea-87ae-8c73ccab0ba3.png)

**Comment by andrewdavidwong** [comment]
Duplicate of #5114

**Comment by andrewdavidwong** [comment]
This appears to be a [duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.
