### ISSUE TITLE
Qubes Manager: does not reflect some changes immediately in menu

### ISSUE THREAD

**Issue by zaoqi** [QubesOS/qubes-issues#5588]
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
Qubes Manager

**Brief summary**
Some changes are updated after closing the Qubes Manager window

**To Reproduce**
_1. open Qubes Manager
_2. create a VM
_3. change the VM to DispVM
_4. open menu
_5. close Qubes Manager
_4. open menu

**Expected behavior**
reflect immediately

**Comment by andrewdavidwong** [comment]
By "menu" do you mean the "Applications Menu" (which is sometimes inaccurately referred to as the "Start Menu")?

**Comment by zaoqi** [comment]
@andrewdavidwong yes
