### ISSUE TITLE
Show storage size numbers in GB, not MB

### ISSUE THREAD

**Issue by strugee** [QubesOS/qubes-issues#5592]
**The problem you're addressing (if any)**

Most users think of sizes in GB, not MB, but the interface often uses sizes only in MB. This doesn't mean much to users (I, for example, frequently find myself converting MB to GB in my head to actually understand the number I'm being shown).

**Describe the solution you'd like**

Qubes Manager and qube settings' "Private/system storage max. size" should show sizes in GB when it makes sense. I suggest only showing MB if the size is below 1 GB, or _maybe_ 1.5 GB.

**Where is the value to a user, and who might that user be?**

This makes storage data easier to understand and manage.

**Describe alternatives you've considered**

None

**Additional context**

None

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

N/A

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

None

**Comment by GWeck** [comment]
This issue becomes more complicated as there is the difference between MB and GB on one side, MiB and GiB on the other (meaning MB and GB defined as 10^^6 / 10 ^^9 resp., and MiB, GiB as 2^^20 or 2^^30). I suppose that a general, user-friendly solution is needed, but I have no idea how this would look.

See also #5003 for this.

**Comment by ninavizz** [comment]
@GWeck Anyone for whom `MiB` or `GiB` may have meaning, will understand `MB` and `GB`, but not the other way around. 

### Recommendation
- Anything < 1 KB needs to be shown in `byte` units
  - All lowercase, with a space between the numeral and the `bytes` designation.
- Anything < 1 MB needs to be shown in `KB` units
  - Capital-K and capital-B, with a space between the numeral and the `KB` designation.
- Anything  ≥ 999.9 MB needs to be shown in `GB` units
   - Round to two decimal places out; anything longer, is excessive for >80% of all humans. 
      - eg: `4.4 MB` is good. `4.423 MB` will impose a cognitive burden on most users.
      - Sacrificing "accuracy" for alleviating cognitive burdens. Should this present a problem for advanced users for whom seeing `999.983 MB` might be useful, then there needs to be a setting to enable such a display if desired—with the simpler version, the default. 
- Anything ≥ 999.9 GB needs to be shown in `Terabyte` units
   - _I need to lookup best practices for expressing Terabytes, but the decimal stuff is the same._

**Comment by GWeck** [comment]
@ninavizz I completely agree with this suggestion. Non-technical users probably will not know the difference between the "i" units and the other ones. I would go even one step further and only allow integer values, as I see no great value in being able to specify 4.4 MB - it should be enough to specify 4 MB or 5 MB. Today our disks are so large that we will not need to save individual bytes!

**Comment by ninavizz** [comment]
Great suggestion @GWeck, I updated my recommendation accordingly. Decimals begin to have value for me, at the GB level; and, likewise, I checked how my Mac does it and that's where they begin decimals... so I added the "Integers Only" caveat for bytes, kilobytes, and megabytes Thx!! :)

**Comment by hexagonrecursion** [comment]
My 2 cents: VirtualBox uses a logarithmic slider for selecting disc sizes.
