### ISSUE TITLE
Boot hangs after Freeing SMP alternatives memory: 28K on Thinkpad X220 i7-2640M

### ISSUE THREAD

**Issue by destotelhorus** [QubesOS/qubes-issues#5593]
**Qubes OS version**
Qubes Release 4.0.1
as well as
Qubes Release 4.0.3-rc1

**Affected component(s) or functionality**
Unable to boot up system.

**Brief summary**
Boot on Thinkpad X220 (i7-2640M) 8GB RAM via Grub through Legacy (not UEFI) hangs after the line:
`Freeing SMP alternatives memory: 28K` if and only if VT-D is enabled in BIOS.
This goes for both 4.0.1 as well as 4.0.3-rc1 after being installed, or for their installers if launched with VT-D enabled and given the iommu=no-igfx line

**To Reproduce**
1. Boot installed system with VT-D enabled.

**Expected behavior**
Successful boot-up

**Actual behavior**
Boot-up freezes with fan spooling up.

**Screenshots**
![image](https://user-images.githubusercontent.com/13833743/72854411-97654e00-3cb4-11ea-8495-20c9a31aa45a.png)

**Solutions you've tried**
- I tried removing the smt=off parameter to no effect.
- Updating BIOS to newest version had no effect.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
1. https://www.qubes-os.org/doc/installation-guide/
2. https://www.qubes-os.org/doc/intel-igfx-troubleshooting/

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
1. Potentially something along the lines of https://github.com/QubesOS/qubes-issues/issues/2841

**Comment by brainletfish** [comment]
Install Coreboot or Heads, i use same configuration laptop. No problems with 4.0.3-rc1

**Comment by destotelhorus** [comment]
> Install Coreboot or Heads, i use same configuration laptop. No problems with 4.0.3-rc1

Thank you for the feedback!
Since going to Coreboot is more than just installing a BIOS update I'd love to double check first.

Could you set your BIOS to Legacy Only and fire up the 4.0.1 or 4.0.3 live CD from usb and see if it boots with vt-d enabled?
