### ISSUE TITLE
Leaking Firewall-VM to Network

### ISSUE THREAD

**Issue by akkuladezeit** [QubesOS/qubes-issues#5596]
### Qubes OS version:
Qubes release 4.0 

### Affected component(s) or functionality:
The Firewall VM sometimes makes requests on the Local Network outside of the PC.

Exampe:
Net-VM: 10.137.0.13  -> 192.168.178.10
Firewall-VM 10.137.14
App-VM 10.137.15

When Surfin in the App-VM the Firewall-VM sometime makes strange requests.
My hardware firewall blocks it and cause this log entry

Blocked:
Source: 10.137.0.14:43402	                    
Destination: 185.199.111.154:443	                           
Protocol: TCP:R 
		
but this ip (10.137.0.14) should never be on this network!

---

### Steps to reproduce the behavior:
-

### Expected or desired behavior:
No Internal Qubes-IP on the Network
(10.137.x.x or 10.138.x.x)

### Actual behavior:
10.137.0.14 on the local network

### General notes:

---

### I have consulted the following relevant [documentation](https://www.qubes-os.org/doc/):
https://www.qubes-os.org/doc/networking/

### I am aware of the following related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues:
-

**Comment by marmarek** [comment]
@pwmarcz you looked recently into firewall, can you spot what could be wrong?

**Comment by akkuladezeit** [comment]
can this be this issue? https://www.qubes-os.org/news/2019/12/25/qsb-056/
im currently on qubes-core-agent-4.0.50-1.fc30.x86_64

**Comment by marmarek** [comment]
It could be related, but not exactly the same. That QSB is about incoming packets, but you see outgoing not correctly translated.
Rules to apply NAT are pretty simple:
```
-A POSTROUTING -o vif+ -j ACCEPT
-A POSTROUTING -o lo -j ACCEPT
-A POSTROUTING -j MASQUERADE
```
Unless your network card interface is named `vif*`, I don't see how packet could pass through it. It could be a bug in iptables itself, but it's very unlikely. Maybe in some cases those rules are not there?

Do you know any more context when it happens? Switching network? Starting some VM? Closing some?

**Comment by akkuladezeit** [comment]
i start up the pc and sys-net and sys-firewall startup.
some time later is start an app-vm or disp-vm and start surfing.
no switching, no closing (is also happening on non sys-net/-firewall)
i filtered the log an it is always tcp port 443 (https) 
is there a special rule for 443?

how does the iptables should look like
sudo iptables -L -v -n ?

**Comment by marmarek** [comment]
The above listing is taken from from `iptables-save` command, which is more precise format.

**Comment by akkuladezeit** [comment]
iptables -L -v
Chain INPUT (policy DROP 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 ACCEPT     tcp  --  vif+   any     anywhere             anywhere             tcp dpt:us-cli
    0     0 DROP       udp  --  vif+   any     anywhere             anywhere             udp dpt:bootpc
   11  1210 ACCEPT     all  --  any    any     anywhere             anywhere             ctstate RELATED,ESTABLISHED
    0     0 ACCEPT     icmp --  vif+   any     anywhere             anywhere            
    1    52 ACCEPT     all  --  lo     any     anywhere             anywhere            
    0     0 REJECT     all  --  vif+   any     anywhere             anywhere             reject-with icmp-host-prohibited
   42  1680 DROP       all  --  any    any     anywhere             anywhere            

Chain FORWARD (policy DROP 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         
 124K  136M ACCEPT     all  --  any    any     anywhere             anywhere             ctstate RELATED,ESTABLISHED
 1319  198K QBS-FORWARD  all  --  any    any     anywhere             anywhere            
    0     0 DROP       all  --  vif+   vif+    anywhere             anywhere            
 1319  198K ACCEPT     all  --  vif+   any     anywhere             anywhere            
    0     0 DROP       all  --  any    any     anywhere             anywhere            

Chain OUTPUT (policy ACCEPT 14 packets, 3298 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain QBS-FORWARD (1 references)
 pkts bytes target     prot opt in     out     source               destination

**Comment by marmarek** [comment]
Check `nat` table too: `iptables -t nat -L -v`. Or simply `iptables-save` to all of it at once.

**Comment by akkuladezeit** [comment]
iptables-save
# Generated by iptables-save v1.8.2 on Wed Jan 22 22:10:15 2020
*raw
:PREROUTING ACCEPT [131976:139789561]
:OUTPUT ACCEPT [14:3298]
-A PREROUTING ! -s 10.137.0.6/32 -i vif21.0 -j DROP
COMMIT
# Completed on Wed Jan 22 22:10:15 2020
# Generated by iptables-save v1.8.2 on Wed Jan 22 22:10:15 2020
*nat
:PREROUTING ACCEPT [506:148736]
:INPUT ACCEPT [0:0]
:OUTPUT ACCEPT [9:927]
:POSTROUTING ACCEPT [0:0]
:PR-QBS - [0:0]
:PR-QBS-SERVICES - [0:0]
-A PREROUTING -j PR-QBS
-A PREROUTING -j PR-QBS-SERVICES
-A POSTROUTING -o vif+ -j ACCEPT
-A POSTROUTING -o lo -j ACCEPT
-A POSTROUTING -j MASQUERADE
-A PR-QBS -d 10.139.1.1/32 -p udp -m udp --dport 53 -j DNAT --to-destination 192.168.178.1
-A PR-QBS -d 10.139.1.1/32 -p tcp -m tcp --dport 53 -j DNAT --to-destination 192.168.178.1
-A PR-QBS -d 10.139.1.2/32 -p udp -m udp --dport 53 -j DNAT --to-destination 192.168.178.1
-A PR-QBS -d 10.139.1.2/32 -p tcp -m tcp --dport 53 -j DNAT --to-destination 192.168.178.1
-A PR-QBS-SERVICES -d 10.137.255.254/32 -i vif+ -p tcp -m tcp --dport 8082 -j REDIRECT
COMMIT
# Completed on Wed Jan 22 22:10:15 2020
# Generated by iptables-save v1.8.2 on Wed Jan 22 22:10:15 2020
*filter
:INPUT DROP [0:0]
:FORWARD DROP [0:0]
:OUTPUT ACCEPT [14:3298]
:QBS-FORWARD - [0:0]
-A INPUT -i vif+ -p tcp -m tcp --dport 8082 -j ACCEPT
-A INPUT -i vif+ -p udp -m udp --dport 68 -j DROP
-A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A INPUT -i vif+ -p icmp -j ACCEPT
-A INPUT -i lo -j ACCEPT
-A INPUT -i vif+ -j REJECT --reject-with icmp-host-prohibited
-A INPUT -j DROP
-A FORWARD -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -j QBS-FORWARD
-A FORWARD -i vif+ -o vif+ -j DROP
-A FORWARD -i vif+ -j ACCEPT
-A FORWARD -j DROP
COMMIT
# Completed on Wed Jan 22 22:10:15 2020

**Comment by akkuladezeit** [comment]
So i recorded the traffic on ens0 inside the net-vm with wireshark and filtered for the firewall-vm ip.
this ip should never be transmitted over ens0.

No.	Time	Source	Destination	Protocol	Length	Info
2190	41.001278821	10.137.0.26	151.101.112.133	TCP	54	54854 → 443 [RST] Seq=1 Win=0 Len=0
2197	41.001752813	10.137.0.26	151.101.112.133	TCP	54	54852 → 443 [RST] Seq=1 Win=0 Len=0
2738	81.634417105	10.137.0.26	151.101.112.133	TCP	54	54880 → 443 [RST] Seq=1 Win=0 Len=0
76954	216.256670802	10.137.0.26	151.101.112.133	TCP	54	54826 → 443 [RST] Seq=1 Win=0 Len=0
77245	217.467494446	10.137.0.26	151.101.112.133	TCP	54	54848 → 443 [RST] Seq=1 Win=0 Len=0
77437	223.301748880	10.137.0.26	151.101.112.133	TCP	54	55010 → 443 [RST] Seq=1 Win=0 Len=0

P.S with reloading github.com i can reproduce this error. this i not working with every website...

**Comment by marmarek** [comment]
It's always RST, interesting.

**Comment by akkuladezeit** [comment]
shouldnt this be impossible after postrouting/nat  -> (-A POSTROUTING -j MASQUERADE).
the MASQUERADE should set the external address (192.168.178.5)

**Comment by akkuladezeit** [comment]
ok i found some interesting stuff. Seams to be an issue on the netfilter
http://www.smythies.com/~doug/network/iptables_notes/
https://bugzilla.netfilter.org/show_bug.cgi?id=693

**Comment by marmarek** [comment]
Looks to be exactly this. @pwmarcz can you take care about the mitigations?

**Comment by pwmarcz** [comment]
On it.

**Comment by pwmarcz** [comment]
Steps to reproduce, using hping3

- On a machine connected to `sys-firewall`, generate a stream of RST packets to `$IP`:
    `hping -p 1234 --rst $IP -V -i 1`
- On `sys-firewall`, monitor the traffic on `eth0`:
    `sudo hping -p 1234 --rst $IP -V -i 1`

I'm seeing the packets to `$IP` being sent on eth0.

Adding the following rule on `sys-firewall` close to the beginning of FORWARD chain helps:
`-A FORWARD -m state --state INVALID -j DROP`

I will prepare a patch.

**Comment by akkuladezeit** [comment]
is this change applied to the sys-firewall (Firewall-VMs) only?
i think every VM that does NAT should have this rule

**Comment by pwmarcz** [comment]
@akkuladezeit Should be applied to all VMs that have "Provided network" enabled, not only sys-firewall.
