### ISSUE TITLE
qrexec-client-vm sometimes fails with "Error while vchan send, exiting"

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#5597]
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
qrexec

**Brief summary**
Sometimes at the end of connection qrexec-client-vm fails with "Error while vchan send, exiting" error and exit with non-zero code. This happens after all the data is already successfully delivered.
I've observed it in various different cases: split-gpg, qvm-open-in-dvm, [Whonix post-suspend hook](https://github.com/Whonix/updates-status/issues/1)

**To Reproduce**
_Steps to reproduce the behavior:_
1. `qrexec-client-vm dom0 qubes.GetRandomizedTime`, or use split-gpg
2. In some cases the issue happens, specific conditions are unclear

**Expected behavior**
Clean exit.

**Actual behavior**
"Error while vchan send, exiting" error is printed and exit code is non-zero, even though the remote service completed successfully.

**Solutions you've tried**
Various workarounds by ignoring exit code.

**Comment by GWeck** [comment]
Sometimes (not often) the Windows 7 client fails to start, also showing a qrexec error. Maybe these phenomena are connected?
