### ISSUE TITLE
Disk Password Fails and Launches Dracut Emergency Shell

### ISSUE THREAD

**Issue by liamcardenas** [QubesOS/qubes-issues#5602]
**Qubes OS version**
4.0.1

**Affected component(s) or functionality**
Disk decryption

**Brief summary**
Asks to enter disk password 3 times and then loads for a while and enters dracut emergency shell

I strongly do not believe this is due to entering the wrong password, but I suppose anything is possible. Given I entered the password many times without a problem prior to this, it seems unlikely.

**To Reproduce**
Unfortunately, I’m not sure how this happened.

**Expected behavior**
Asks for password and then boots

**Actual behavior**
Enters dracut emergency shell, displaying this error
```
Could not boot
/dev/mapper/qubes_dom0-root does not exist
/dev/qubes_dom0/root does not exist
/dev/qubes_dom0/swap does not exist
```
Notably, inside of the generated `/run/initramfs/rdosreport.txt` it states `Invalid passphrase` 3 times and then gives up (despite the passphrase being correct)

I would try to decrypt the volume via the shell, however, unlike the situation in similar bug reports, there is no `sda` or any other volume in `/dev/` 

Also running `lvm` and then `vgscan` shows nothing

One other weird fact is that I encountered this problem and, after many tries, was able to log in again successfully. Then upon reboot, I started experiencing the problem again and have not gotten it working since.

**Solutions you've tried**
I’ve tried implementing similar solutions to the below related issues, both of which do not address the problem — partly because no volumes are available

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
https://github.com/QubesOS/qubes-issues/issues/5160
https://github.com/QubesOS/qubes-issues/issues/5372

**Comment by frank0si0ss0** [comment]
I have the same I have do the right password but don't work
