### ISSUE TITLE
All Linux in HVM stadalone mode have no internet but Windows 10 does

### ISSUE THREAD

**Issue by lucaszanella** [QubesOS/qubes-issues#5605]
**Qubes OS version**
4.0.1

**Affected component(s) or functionality**
Linux standalone VMs in HVM mode

**Brief summary**
When I enter the VM, fresh after installation, I get no internet. 
I installed Kali Linux and Ubuntu 19. It's in HVM mode. I have no internet. I tried to edit the network options, and choose eth0 as the adapter.

ping google.com gives

temporary failure in name resolution

I tried adding 8.8.8.8 and 8.8.4.4 in the network options, but the error persists

Windows 10, also in HVM mode, **has internet.**

Also, I tried running in PV mode, choosing the most recent kernel. It simply halts rigth after the boot. Why?

**To Reproduce**
_Steps to reproduce the behavior:_
Install Linux standalone VM in HVM mode
Start
No internet

**Solutions you've tried**
I tried setting the DNS servers manually, tried creating a new connection on settings, but this seems to need more debugging. I also tried asking in qubes-users and tried googling but nobody had this error.

**Comment by unman** [comment]
On Mon, Jan 27, 2020 at 02:20:52PM -0800, Lucas Zanela wrote:
> **Qubes OS version**
> 4.0.1
> 
> **Affected component(s) or functionality**
> Linux standalone VMs in HVM mode
> 
> **Brief summary**
> When I enter the VM, fresh after installation, I get no internet. 
> I installed Kali Linux and Ubuntu 19. It's in HVM mode. I have no internet. I tried to edit the network options, and choose eth0 as the adapter.
> 
> ping google.com gives
> 
> temporary failure in name resolution
> 
> I tried adding 8.8.8.8 and 8.8.4.4 in the network options, but the error persists
> 
> Windows 10, also in HVM mode, **has internet.**
> 
> Also, I tried running in PV mode, choosing the most recent kernel. It simply halts rigth after the boot. Why?
> 
> **To Reproduce**
> _Steps to reproduce the behavior:_
> Install Linux standalone VM in HVM mode
> Start
> No internet
> 
> **Solutions you've tried**
> I tried setting the DNS servers manually, tried creating a new connection on settings, but this seems to need more debugging. I also tried asking in qubes-users and tried googling but nobody had this error.
> 

Did you set the network settings when you were installing?
You can check this from Qube manager, or using 'qvm-ls -n'

Certainly Ubuntu networking is fine in HVM mode.

**Comment by elliotkillick** [comment]
Does Windows have QWT installed? I noticed that if Windows doesn't have QWT installed then you must manually configure the networking properties such as the IP of the qube, the default gateway, the subnet mask, etc. as well as disabling APIPA (Automatic Private IP Addressing) which is a feature in Windows.

Perhaps it's the same deal for Linux HVMs with no Qubes tools excluding the disabling of APIPA?

**Comment by unman** [comment]
@lucaszanella  Please update this issue - do the HVM installations work when you manually set the IP details?

**Comment by unman** [comment]
@andrewdavidwong I suggest this be closed - I believe it is user error in not manually setting IP address.

**Comment by andrewdavidwong** [comment]
Closing this for now due to the lack of response. If you revisit the matter in the future, or if anyone would like the issue to remain open, please leave a comment, and we'll be happy to reopen this. Thank you.

**Comment by TheLagSa** [comment]
I'm having this problem too on Kali Linux. 

On internet settings and the Ethernet tab, I have chosen eth0 as device
Cloned MAC address as preserve

Under the IPv4 settings, I have chosen 
IP: 10.137.0.20
Netmask: 32
Gateway: 10.137.0.5

DNS: 10.139.1.1, 10.139.1.2

The above settings is from the VM: Qubes settings under the basic tab->Networking

Networking VM is sys-firewall.

**Comment by unman** [comment]
On Tue, Sep 22, 2020 at 01:29:24AM -0700, TheLagSa wrote:
> I'm having this problem too on Kali Linux. 
> 
> On internet settings and the Ethernet tab, I have chosen eth0 as device
> Cloned MAC address as preserve
> 
> Under the IPv4 settings, I have chosen 
> IP: 10.137.0.20
> Netmask: 32
> Gateway: 10.137.0.5
> 
> DNS: 10.139.1.1, 10.139.1.2
> 
> The above settings is from the VM: Qubes settings under the basic tab->Networking
> 
> Networking VM is sys-firewall.
> 

As in the docs, you need to manually set the IP - a 32 netmask is no
use, you want to set 255.255.255.0 
Covered **many** times on the qubes-users mailing list, and now in the
Forum

**Comment by TheLagSa** [comment]
> As in the docs, you need to manually set the IP - a 32 netmask is no use, you want to set 255.255.255.0

Already did that. Thought I made that clear. But as stated in the **EDIT**, it works now. /32 works just fine.

**Comment by unman** [comment]
On Tue, Sep 22, 2020 at 06:08:11AM -0700, TheLagSa wrote:
> > As in the docs, you need to manually set the IP - a 32 netmask is no use, you want to set 255.255.255.0
> 
> Already did that. Thought I made that clear. But as stated in the **EDIT**, it works now. /32 works just fine.
> 

I don't see where you made it clear, *or* your edit. :-(
