### ISSUE TITLE
How to connect to the internet in Qubes OS 4.0.3 using a USB modem ?

### ISSUE THREAD

**Issue by LinuxAndQubes-Newbie** [QubesOS/qubes-issues#5610]
### Qubes OS version:

4.0.3

### Affected component(s) or functionality:

Connecting to the internet by using USB modem (HUAWEI E3372).

---

### Steps to reproduce the behavior:

After a successful install of Qubes OS, I restarted the pc and plugged the USB modem in the pc before letting the pc do the last configurations.

When I logged into Qubes OS, a red icon in the upper right corner of the screen showed “No network connection”. I then right clicked on it, selected “Edit connections” -> Add, and followed the guide.

Afterwards I restarted the pc, and a new window came up regarding connecting to the Tor network. I have tried both a direct connection and all the bridged connections. They all stop at 2 or 5 %.

### Expected or desired behavior:

Connected to the internet.

### Actual behavior:

No connection.

### General notes:

I’m new to both Linux and Qubes OS.

I have installed Qubes OS 4.0.3 and wonder how I can connect to the internet using a USB modem (HUAWEI E3372 with also Linux drivers on it), and I hope I can get some help from you more experienced users now that I’m stuck and have run out of ideas.
.
.
Questions:

1)  Is it necessary to use a VPN to use Qubes OS to connect to the internet ?

2)  What shall I do to get connected to the internet ?

---

### I have consulted the following relevant [documentation](https://www.qubes-os.org/doc/):

https://bytefreaks.net/gnulinux/qubes-os-connect-to-wi-fi-or-ethernet-or-another-network

http://nukama.github.io/doc/QubesFirewall/

https://www.qubes-os.org/doc/networking/

https://www.qubes-os.org/doc/wireless-troubleshooting/

https://stackoverflow.com/questions/47144438/qubes-os-no-networking

**Comment by 0spinboson** [comment]
the qubes mailing list is probably a better place for questions like this -> https://groups.google.com/forum/#!forum/qubes-users
That said, assuming you have a USB qube (sys-usb) configured, you'll first need to click on the qubes devices systray icon, then connect the USB modem to your sys-net qube, before it'll be able to talk to it.

**Comment by LinuxAndQubes-Newbie** [comment]
Yes, I have made a thread there first. But I haven’t got any useful answers there yet. And as I found thread here with other users who have managed to get it working I thought I would try to get in touch with them here...

Although I didn’t mentioned it, I have tried to connect the USB modem to the sys-net qube by clicking on devices and click on the sum sign to the left of sys-net. But the result seemed to be the same.

Is there another way to do it... ?

And does it make any difference if I added the broadband connection before I added the device to the sys-net as mentioned before ?

**Comment by unman** [comment]
As @0spinboson says, this really isnt the place.
This isnt a support forum

**Comment by LinuxAndQubes-Newbie** [comment]
Yes, but what do I do then when I don’t get any useful answers in there and I can’t find any useful guides anywhere on the web about connecting Qubes OS to the web by using a USB modem ?

**Comment by andrewdavidwong** [comment]
As others have pointed out, based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this does not appear to be suitable for `qubes-issues`. We ask that you please send this to the `qubes-users` [mailing list](https://www.qubes-os.org/support/) instead. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a brief comment explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.
