### ISSUE TITLE
Tinyproxy port 8082 reachable from LAN

### ISSUE THREAD

**Issue by neowutran** [QubesOS/qubes-issues#5614]
**Qubes OS version**
`R4.0`

**Affected component(s) or functionality**
TBD

**Brief summary**
Tinyproxy is configured to listen to all the interfaces (0.0.0.0).
So, the port 8082 is reachable from LAN.
I see 3 main issues with that: 
- Increased attack surface
- Cannot use port 8082 to provide a custom service on the LAN
- Easy to detect a QubesOS machine on the LAN. It is a machine with 1 port open: tinyproxy listening the port 8082

**To Reproduce**
Do a port scan on the LAN

**Expected behavior**
No port is open for the QubesOS machine 

**Actual behavior**
The port 8082 is open, tinyproxy is listening

**Screenshots**

**Additional context**

**Solutions you've tried**
None yet. I have to better understand the point of tinyproxy and what are the things that really need to reach it. However, since the configuration contains 
``` 
Allow 127.0.0.1
Allow 10.137.0.0/16
```
, tinyproxy have probably no reason to be reachable from LAN. 
The `Listen` directive could be used

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

**Comment by marmarek** [comment]
Default firewall on Qubes allows connections to it only from vif+
interfaces, so it is not exposed to external hosts. Do you have it
different?

**Comment by neowutran** [comment]
My bad, I launched the port scan from one qube on 192.168.1.1/24, and it reported the tinyproxy on port 8082 for my machine IP. However I was able to see it only because I launched the scan from my QubesOS machine. The firewall correctly block outside connection.

**Comment by timove** [comment]
I have a different scenario, where this might be a problem. I tested ipv6 support in Qubes 4.0 in dedicated a qube. It has no NetVM assigned, has "Provides network" set, and I attached the qube via an USB-ethernet-adapter to a ipv6 network-setup. In this scenario port 8082 tcp is reachable via ipv6 from the outside.
Shall I open a dedicated issue?

**Comment by timove** [comment]
maybe this relates to #3800

**Comment by timove** [comment]
... my bad, I misinterpreted nmap output. tinyproxy to be not reachable.
