### ISSUE TITLE
HVM 'timezone' feature setting is effectively ignored by libvirt 3.3.0

### ISSUE THREAD

**Issue by iamahuman** [QubesOS/qubes-issues#5616]
**Qubes OS version**
R4.0.3

**Affected component(s) or functionality**
libvirt, old version

**Brief summary**
Qubes apparently allows the user to configure HVM clock timezones via `qvm-features <domain> timezone <value>` command and defaults to local time, but its value (or the default) as reflected in the libvirt XML configuration file is ignored by libvirt prior to 4.1.0. Qubes R4.0.3 uses libvirt 3.3.0.

**To Reproduce**
1. Create an HVM.
2. Optionally, set the timezone of its clock to anything other than UTC.
3. Start the VM with a nontrivial operating system or a firmware with a setup utility.
4. Observe its current time.

**Expected behavior**
The current time in HVM should reflect the timezone setting.

**Actual behavior**
The current time in HVM is always the UTC time of dom0, regardless of the timezone setting.

**Screenshots**
N/A

**Additional context**
Qubes uses libvirt to abstract management of virtual machines, but as of Feburary 2020 the only backend in use is the Xenlight (XL) driver. For a normal HVM Qube, [the libvirt XML configuration](https://github.com/QubesOS/qubes-core-admin/blob/master/templates/libvirt/xen.xml) (`/usr/share/qubes/templates/libvirt/xen.xml`) defaults its [clock basis](https://libvirt.org/formatdomain.html#elementsTime) to dom0 local timezone (`basis="localtime"`) unless overridden with `qvm-features`. The XL's implementation for the driver entry point `connectDomainXMLToNative`, as accessible in dom0 with `virsh domxml-to-native xen-xl <domid>`, does reflect in its output the clock setting as specified by the XML configuration; however, this is not actually used in domain creation performed directly by `libvirt`. The entry points actually involved in creating VMs (e.g. `dominCreateXML`) instead operates directly on a `libxl_domain_config` record and passes it to `libxl`, but prior to libvirt 4.1.0 (specifically [this commit](https://xenbits.xen.org/gitweb/?p=libvirt.git;a=commitdiff;h=c391e07eb08d713474ae8998cfd859e1827a4b2d), its changelog added in [this commit](https://libvirt.org/git/?p=libvirt.git;a=commitdiff;h=87876c7736646452f4139a4d3a8478c51b92abbe)) the `<clock />` basis and adjustment settings are not included.

**Workarounds**

1. Manually adjust the system time of the guest operating system every time it starts up (cumbersome).
2. Directly issue a `domctl` hypercall with command `XEN_DOMCTL_settimeoffset`, by using `libxc` or `xen.xc` python module in dom0 (cumbersome)
3. (Windows-specific) configure the registry as follows. For 32-bit Windows substitute `qword` with `dword`. [You may or may not have to disable the automatic time update depending on your Windows system or version](https://superuser.com/questions/975717/does-windows-10-support-utc-as-bios-time/975764#975764).

    ```reg
    Windows Registry Editor Version 5.00
    
    [HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Xen Project\Windows PV Drivers]
    "HostTime"="UTC"
    
    [HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\TimeZoneInformation]
    "RealTimeIsUniversal"=qword:00000001
    ```

    The first value configures `xenagent.exe` (included in Windows PV drivers from Xen) and the relevant code may be found [here](https://xenbits.xen.org/gitweb/?p=pvdrivers/win/xeniface.git;a=blob;f=src/xenagent/service.cpp;h=7243fa4de91c5dd8712470d0f94a830a2bd20805;hb=7a3bb8ccc22e74b1b5c0b3dbe7e89e681600a228#l378). It also fetches the current time from the hypervisor and synchronizes the guest system clock accordingly. Setting the value to `UTC` makes it deduce the UTC value from hypervisor-provided clock, and set the UTC time instead of the local time. If this one is not set, the agent will revert the time every time the system starts up.
    The second value instructs Windows to interpret the RTC (CMOS) clock as being in UTC, not in local time. More information can be found in the [Arch Linux Wiki](https://wiki.archlinux.org/index.php/System_time#UTC_in_Windows). For the rationale of this behavior, you may find [this link](https://devblogs.microsoft.com/oldnewthing/20040902-00/?p=37983) helpful.
4. Rebuild `libvirt` with [this patch](https://xenbits.xen.org/gitweb/?p=libvirt.git;a=commitdiff;h=c391e07eb08d713474ae8998cfd859e1827a4b2d) applied (not verified).

Fixing this issue may break the time setting with existing users who have worked around this issue. Since it is evident that this setting has never worked (see #1437), I propose that the default timezone in [the template](https://github.com/QubesOS/qubes-core-admin/blob/d7b90f92e0a656d9ee3fd2eaff7d5024c55257b6/templates/libvirt/xen.xml#L76) changed to `'0'` instead of `'localtime'` to retain the current behavior. This will also make it consistent with PVs.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
[Changing your Time Zone](https://www.qubes-os.org/doc/change-time-zone/) is affected by this issue.

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
#1437, #1184

**Comment by iamahuman** [comment]
Closing this issue as [R4.1 is intended to fix this issue](https://github.com/QubesOS/qubes-core-admin/commit/362e128ec68830c60ee02e579bf3a481352a3b68).

**Comment by andrewdavidwong** [comment]
> Closing as [R4.1 is intended to fix this issue](https://github.com/QubesOS/qubes-core-admin/commit/362e128ec68830c60ee02e579bf3a481352a3b68).

I suppose that's fine, as long as the fix doesn't need to be backported to R4.0.

**Comment by iamahuman** [comment]
@andrewdavidwong It came to me as a surprise that no one has ever filed this bug honestly. I assume the majority of Qubes userbase doesn't live around the Zulu timezone?

**Comment by unman** [comment]
On Mon, Feb 03, 2020 at 04:45:40AM -0800, iamahuman wrote:
> @andrewdavidwong It came to me as a surprise that no one has ever filed this bug honestly. I assume the majority of Qubes userbase doesn't live around the Zulu timezone?
> 
It's also possible that most users keep UTC rather than local time.

**Comment by iamahuman** [comment]
@unman ...which would require one of the workarounds I've described for Windows, anyway.

@andrewdavidwong This shouldn't be critical for overall Qubes functionality and would only affect guest operating systems that takes RTC time as being in local timezone. Still, [the aforementioned libvirt patch](https://xenbits.xen.org/gitweb/?p=libvirt.git;a=commitdiff;h=c391e07eb08d713474ae8998cfd859e1827a4b2d) is minimal and straightforward enough that it won't presumably cause any major distruptions or regressions &mdash; it basically has the same effect as applying the workarounds above &mdash; and would serve as a good stopgap measure before R4.1 is released (I think).

**Comment by iamahuman** [comment]
I'm reopening this issue since R4.0 would still be supported for 1 year after the next minor version is released. Feel free to close this issue if this is not the case or otherwise is or becomes irrelevant.

**Comment by andrewdavidwong** [comment]
> It came to me as a surprise that no one has ever filed this bug honestly. I assume the majority of Qubes userbase doesn't live around the Zulu timezone?

We don't know, since we don't collect any data about where Qubes users live. That seems like a safe guess, though.

> This shouldn't be critical for overall Qubes functionality and would only affect guest operating systems that takes RTC time as being in local timezone. Still, the aforementioned libvirt patch is minimal and straightforward enough that it won't presumably cause any major distruptions or regressions — it basically has the same effect as applying the workarounds above — and would serve as a good stopgap measure before R4.1 is released (I think).

> I'm reopening this issue since R4.0 would still be supported for 1 year after the next minor version is released. Feel free to close this issue if this is not the case or otherwise is or becomes irrelevant.

Sounds reasonable. Thanks.

**Comment by iamahuman** [comment]
I'm assuming this issue has been completely diag osed by Qubes OS development team (as per QubesOS/qubes-core-admin@362e128ec68830c60ee02e579bf3a481352a3b68), and this would be a matter of deciding whether to backport the fix or not.

Besides, the iwlwifi issue link appears to be a mistake.
