### ISSUE TITLE
QubesOS/qubes-builder-rpm GitHub description is wrong

### ISSUE THREAD

**Issue by strugee** [QubesOS/qubes-issues#5620]
Omitting the usual issue template since this is so trivial. The GitHub description for https://github.com/QubesOS/qubes-builder-rpm is set to "Qubes component: builder-fedora" but it should be "Qubes component: builder-rpm" instead, AFAICT. This needs a member of the QubesOS org to resolve.

**Comment by fepitre** [comment]
Yes it's because in past years it was named builder-fedora. Since we merged builder-centos in it, it was renamed builder-rpm. Nice catch :)

**Comment by marmarek** [comment]
Done, thanks :)
