### ISSUE TITLE
Device widget crashed when creating new VM

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#5622]
**Qubes OS version**
4.0

**Affected component(s) or functionality**
desktop-linux-manager

**Brief summary**
Devices widget crashed, and reappeared shortly.

**To Reproduce**
_Steps to reproduce the behavior:_
1. Open new vm dialog
2. Select standalone vm based on a template (not sure if relevant)
3. Enter name, select color
4. Click ok

**Expected behavior**
Widget stays alive

**Actual behavior**
Widget disappears for a few seconds.
Crash message from logs:
```
Feb 05 04:33:19 dom0 widget-wrapper[4907]: Traceback (most recent call last):
Feb 05 04:33:19 dom0 widget-wrapper[4907]:   File "/usr/bin/qui-devices", line 9, in <module>
Feb 05 04:33:19 dom0 widget-wrapper[4907]:     load_entry_point('qui==0.1', 'gui_scripts', 'qui-devices')()
Feb 05 04:33:19 dom0 widget-wrapper[4907]:   File "/usr/lib/python3.5/site-packages/qui/tray/devices.py", line 354, in main
Feb 05 04:33:19 dom0 widget-wrapper[4907]:     'org.qubes.qui.tray.Devices', qapp, dispatcher)
Feb 05 04:33:19 dom0 widget-wrapper[4907]:   File "/usr/lib/python3.5/site-packages/gbulb/glib_events.py", line 736, in run_until_complete
Feb 05 04:33:19 dom0 widget-wrapper[4907]:     return future.result()
Feb 05 04:33:19 dom0 widget-wrapper[4907]:   File "/usr/lib64/python3.5/asyncio/futures.py", line 294, in result
Feb 05 04:33:19 dom0 widget-wrapper[4907]:     raise self._exception
Feb 05 04:33:19 dom0 widget-wrapper[4907]:   File "/usr/lib64/python3.5/asyncio/tasks.py", line 240, in _step
Feb 05 04:33:19 dom0 widget-wrapper[4907]:     result = coro.send(None)
Feb 05 04:33:19 dom0 widget-wrapper[4907]:   File "/usr/lib/python3.5/site-packages/qubesadmin/events/__init__.py", line 126, in listen_for_events
Feb 05 04:33:19 dom0 widget-wrapper[4907]:     yield from self._listen_for_events(vm)
Feb 05 04:33:19 dom0 widget-wrapper[4907]:   File "/usr/lib/python3.5/site-packages/qubesadmin/events/__init__.py", line 183, in _listen_for_events
Feb 05 04:33:19 dom0 widget-wrapper[4907]:     self.handle(subject, event, **kwargs)
Feb 05 04:33:19 dom0 widget-wrapper[4907]:   File "/usr/lib/python3.5/site-packages/qubesadmin/events/__init__.py", line 217, in handle
Feb 05 04:33:19 dom0 widget-wrapper[4907]:     handler(subject, event, **kwargs)
Feb 05 04:33:19 dom0 widget-wrapper[4907]:   File "/usr/lib/python3.5/site-packages/qui/tray/devices.py", line 301, in on_label_changed
Feb 05 04:33:19 dom0 widget-wrapper[4907]:     def on_label_changed(self, vm, _event, **_kwargs):
Feb 05 04:33:19 dom0 widget-wrapper[4907]: AttributeError: 'VM' object has no attribute 'name'
```

**Additional context**
qubes-desktop-linux-manager 4.0.24

**Solutions you've tried**
_If applicable, any solutions or workarounds you've already tried._

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
_A list of links to the Qubes documentation (or other relevant software documentation) pages you have already consulted._

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
_A list of links to other bug reports, feature requests, or tasks in the qubes-issues tracker (or "none" if you didn't find any). Do not describe any other unreported bugs, features, or tasks here._

**Comment by 92VV3M42d3v8** [comment]
I might be having a separate issue but my device widget is not showing up in tray. I am on April testing build.

**Comment by marmarta** [comment]
> I might be having a separate issue but my device widget is not showing up in tray. I am on April testing build.

@92VV3M42d3v8 please make a separate issue - it's definitely a different sort of problem. It would be great if you could check in dom0 what's the result of `systemctl --user status qubes-widget@qui-devices`
