### ISSUE TITLE
log of fully updated system is different from log of a point release

### ISSUE THREAD

**Issue by zaoqi** [QubesOS/qubes-issues#5623]
**Qubes OS version**
R4.0

**Affected component(s) or functionality**

**Brief summary**
log of fully updated system is different from log of a point release

**To Reproduce**
_1. Install encrypted Qubes OS
_2. Press esc before entering the password

**Expected behavior**
log should be the same

**Actual behavior**
a point release: There are a few lines in front of `Please enter passphrase for disk`
fully updated system: `Please enter passphrase for disk` is the first line.

**Screenshots**

**Additional context**

**Solutions you've tried**

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

**Comment by andrewdavidwong** [comment]
Can you provide the different lines?
