### ISSUE TITLE
Add Rofi and Polybar to default packages in Dom0

### ISSUE THREAD

**Issue by 0rb677** [QubesOS/qubes-issues#5624]
**Qubes OS version (if applicable)**
R 4.0

https://github.com/polybar/polybar
(most usable Panel Bar)
https://github.com/davatorium/rofi
(Application launcher and dmenu replacement)

Qubes Polybar build issue
https://github.com/polybar/polybar/issues/2004

**Comment by fepitre** [comment]
Hi,
I setup those packages for Qubes R4.0 few days ago:
https://github.com/fepitre/qubes-polybar
https://github.com/fepitre/qubes-rofi

You can build it and test it. I'm currently using them and it's working great :)

**Comment by fepitre** [comment]
If you want to try: https://mirror.notset.fr/qubes/repo/notset/yum/r4.0/unstable/dom0/fc25/rpm/
It's on my mirror unstable repo. It's signed with this key https://mirror.notset.fr/qubes/repo/notset/RPM-GPG-KEY-notset

**Comment by 0rb677** [comment]
@fepitre Great. Thank you! :)
