### ISSUE TITLE
keyboard layout from setup not remembered

### ISSUE THREAD

**Issue by sjvudp** [QubesOS/qubes-issues#5630]
**Qubes OS version**
R4.0.3

**Affected component(s) or functionality**
Base system (boot, Login)

**Brief summary**
When installing R4.0.3, I had selected German keyboard in addition to the English keyboard, and it worked fine. When providing the LUKS password, the keyboard was indicated as German, and the claim was that the same keyboard would be used at boot time.

However when booting, there was no indication what the keyboard layout is.  When I was close to despair, I tried to enter my pass phrase on my German 102-key ("Windows-free") PS/2 keyboard as if it had an English layout. Then I succeeded!

Same problem when trying to log in: My password had a "z" in it. Only after I entered an "y" instead, I could log in.  Same then after having logged in: In each terminal of each VM the layout was English!

**To Reproduce**
Add German keyboard (and maybe German language support) when installing.
Select German keyboard layout (probably works best if you actually have a German keyboard layout)
Proceed as usual.
Boot the installed system.

**Expected behavior**
German keyboard layout should be used and keyboard layout should be indicated.
Preferrably the layout could be changed (limited to installed versions) also. "loadkeys de" (or similar) should work.

**Actual behavior**
Keyboard lyout is not indicated, defualt layout is English.
"loadkeys de" does not work.

**Screenshots**
(Available upon request)

**Solutions you've tried**
Imagine English keyboard layout on a German keyboard.

**Comment by GWeck** [comment]
The same for R4.1 - see #1396. For me, R4.0.3 works correctly.

**Comment by sjvudp** [comment]
I tried a re-install, but things were the same:
Everything was US-layout. It's quite annoying to fix:

- First there's a "keyboard" setting for Dom0 that doesn't seem to have any effect. (And I tere's no error logged in the system journal either)
- Then, you'll have to change the layouts in all VMs, and you'll have to start them all to be able to change the layout. Not to forget the template VMs as otherwise you're back at "standard", specifically for the disposable VMs.
- Finally I noticed that for fedora-30 I don't get a keyboard settings popup. Unsure what it is, but even if there's a popup, the list is sorted in a way that makes you scratch your head, wondering...

**Comment by andrewdavidwong** [comment]
This appears to be a [duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) of either #3234 or #3352. If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Comment by sjvudp** [comment]
So the boot password issue is still open, while the other isse should have been fixed in 2018?
It seems I have both issues, but after the third installation I made an interesting observation:
I had added a German keyboard, selected it and verified it. However during installation (when you can still create a user and a root password) I noticed that the layout was "US" again. So I hit the "switch keyboard combination" to switch to "DE". It seems this time I have German keyboard in Dom0, and in the VMs I can switch using the configured key combination.
What had made things worse for me before was that in the installation system a "loadkeys de" would work, but not in the Dom0 after installation.
