### ISSUE TITLE
Enigmail copies secret key to untrusted qube

### ISSUE THREAD

**Issue by unman** [QubesOS/qubes-issues#5639]
**Qubes OS version**
R4.0.3

**Affected component(s) or functionality**
Split-gpg

**Brief summary**
After using enigmail with split-gpg, the secret key is copied to the untrusted qube.

**To Reproduce**
_Steps to reproduce the behavior:_
_1. Create test qube_
_2.Configure split-gpg as instructions_
_3. Confirm that `gpg -K` produces no output_
_4. Configure Enigmail in Thunderbird to use split-gpg_
_5. Use Enigmail_
_6. Check `gpg -K`_

**Expected behavior**
The secret key should not be found in the test qube

**Actual behavior**
The secret key has been copied to test qube

**Screenshots**
_If applicable, add screenshots to help explain your problem._

**Additional context**
Reported on qubes-users in context of exporting keys from Enigmail by  [Claudio Chinichz](https://www.mail-archive.com/qubes-users@googlegroups.com/msg32387.html).  
There is no need to perform the "export" operation.

The stated advantage of split-gpg is :
> This way the compromise of your domain where Thunderbird or another client app is running – arguably a not-so-unthinkable scenario – does not allow the attacker to automatically also steal all your keys.

As things stand, this claimed advantage simply doesnt exist. The keys are there in the untrusted qube. This would be a major issue to users of Enigmail.

**Solutions you've tried**

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
https://www.qubes-os.org/doc/split-gpg/

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
None related

**Comment by andrewdavidwong** [comment]
FYI @marmarek

**Comment by fepitre** [comment]
@unman: can you check the fingerprint, expiration date and armor please? It seems that it's simply Enigmail who is creating it's own key.

**Comment by unman** [comment]
@fepitre You're right. Should have checked.
Closing due to stupidity
