### ISSUE TITLE
Qubes os usb boot installation bug

### ISSUE THREAD

**Issue by ciangxomqv** [QubesOS/qubes-issues#5641]
**Qubes OS version**
Qubes OS v4.0.3

**Affected component(s) or functionality**
Installation through a bootable usb

**Brief summary**
So essentially I clicked on “Test this media and install Qubes R4.0.3” in the Qubes OS boot screen after having booted my computer with my usb key. I then get this message “[17.632223] dracut-pre-udev [501]: rpc. idmapd: conf_reinit: open ("(null)", 0_RDONLY) failed” and then the Qubes OS logo and a sort of progress bar appears except it freezes. I’ve researched a bit and tried all the options yet nothing works

**To Reproduce**
note: My computer doesn’t have a supervisor account so I had to go into Legacy mode to deactivate secure boot.
1. Follow the instructions of the official of Qubes OS website to install the operating system.
2. Boot your computer with the Qubes OS as DD
3. On the Qubes OS boot menu choose “Test this media and install Qubes R4.0.3”
4. Wait and see the error “[17.632223] dracut-pre-udev [501]: rpc. idmapd: conf_reinit: open ("(null)", 0_RDONLY) failed” before the loading screen with the Qubes OS logo and an immobile progress bar appears.

**Expected behavior**
I just wanted to get to the next part of the installation process of the operating system (The Installer Home Screen)

**Actual behavior**
The error appeared and a Qubes OS loading screen with an immobile progress bar appeared.

**Screenshots**

The error I got:
![CEA1F1E1-FDE1-47EB-93DB-90D44CE2D698]
(https://user-images.githubusercontent.com/60892684/74175315-e0fee400-4c35-11ea-98d0-ba19c047fd4b.jpeg)
Additional text that appeared before the error:
![5D323703-A789-4F71-992C-BEBF4EE9603F](https://user-images.githubusercontent.com/60892684/74175321-e5c39800-4c35-11ea-8276-4fbc3329ea0b.jpeg)
The error again (it appears twice):
![BD25A051-16E5-40FA-9724-90888B068EAB](https://user-images.githubusercontent.com/60892684/74175324-e65c2e80-4c35-11ea-95c6-9adc69b98b41.jpeg)
Loading screen after the error (with the immobile progress bar):
![11B620D9-9EC0-465B-9FE8-5324533CAC20](https://user-images.githubusercontent.com/60892684/74175327-e78d5b80-4c35-11ea-9329-fe4262afab2a.jpeg)
The error I get if I try the alternative “Install Qubes R4.0.3”:
![B3610344-8746-426E-9614-F16B35EEF678](https://user-images.githubusercontent.com/60892684/74175331-e9571f00-4c35-11ea-8d02-d6c610220788.jpeg)

**Additional context**
Already provided

**Solutions I've tried**
-Trying again
-The option of Install Qubes R4.0.3 (also an error)

**Comment by wesakers** [comment]
I had this exact same issue and after many hours of trial and error the solution was for me to remove my RAID controller. None of the troubleshooting procedures worked and even changing BIOS settings (AHCI/IDE, Legacy) did nothing.  After physically removing the controller I was able to boot it straight up and am now going through the installation process.

**Comment by F1nnM** [comment]
I had this issue, but it came from not using dd to create my USB boot drive.
When I created it with dd, I still got the error messages, but the installer launched successfully.

**Comment by mruadmin** [comment]
Also getting the dracut-pre-udev issue. Im using version Qubes 4.04 with a AMD BM450 motherboard.

I did use the dd option in rufus to create the usb which is on a 8gig usb drive. I have no raid controllers to remove so cant use suggestion from wesakers. Would like to install to a external usb but cant get to that point. stuck on the  dracut-pre-udev issue. 

Is my only option to replace the motherboard or is there something else I could do? fyi, im normally a windows user so new to linux and qubes.

**Comment by mruadmin** [comment]
FYI, got around the issue by using the 4.1 alpha version of qubes.
