### ISSUE TITLE
Xen fails to resume on AMD Fam15h (and Fam17h?) because of CPUID mismatch

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#5644]
**Qubes OS version**
R4.0, R4.1

**Affected component(s) or functionality**
Xen

**Brief summary**
Xen panic on resume on AMD machines, at least Ryzen 2500U, Ryzen Pro 3700U, maybe more.

**To Reproduce**
Suspend system, observe panic on resume.

**Expected behavior**
Working resume

**Actual behavior**

`(XEN) CPU0: cap[ 1] is 7ed8320b (expected f6d8320b)`

If I read it right, this is:
  - OSXSAVE: 0 -> 1
  - HYPERVISOR: 1 -> 0

**Additional context**

https://groups.google.com/forum/#!topic/qubes-users/xtOYb9i9Bew
https://www.mail-archive.com/qubes-users@googlegroups.com/msg31517.html
https://lists.xenproject.org/archives/html/xen-devel/2020-02/msg00639.html

**Solutions you've tried**
https://github.com/QubesOS/qubes-vmm-xen/pull/70
"fixes" the issue, but is not a generic solution.

**Comment by githubhun1** [comment]
I checked your github (@marmarek) repo of qubes-vmm-xen (branch:xen-4.13-amd-suspend) and built the xen packages for R4.1 fc31-dom0.
The recent xen patch solved the Suspend/Resume issue for my AMD Fam15h, both the hypervisor and the HVMs are suspending/resuming fine!
Thanks @marmarek for taking this issue to xen-devel and eventually fix this in accordance with the long term security objectives of xen (and Qubes).

**Comment by mossy-nw** [comment]
@marmarek you're a star, thanks for making these hardware support fixes!  @githubhun1 is building xen from marmarek's github something one can do without prior experience or will the ordinary user need to wait til qubes 4.1 is released to access this fix?  thx, y'all!
