### ISSUE TITLE
DNS resolution failure (/usr/lib/qubes/qubes-setup-dnat-to-ns did not run on sys-net)

### ISSUE THREAD

**Issue by jschaul** [QubesOS/qubes-issues#5648]
**Qubes OS version** 
R4.0

**Affected component(s) or functionality**
DNS resolution in AppVMs other than `sys-net`

**Brief summary**
Sometimes after booting (about 20% of the time), DNS resolution in AppVMs does not work. `ping google.com` or `dig google.com` time out.
After some investigation, it appears something leads `/usr/lib/qubes/qubes-setup-dnat-to-ns` on `sys-net` to not be executed, or executed too early in the process.

When the issue arises, I can see that the rules from iptables on `sys-net` are not set:

```
iptables -t nat -L
```

```
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination         
PR-QBS     all  --  anywhere             anywhere            
PR-QBS-SERVICES  all  --  anywhere             anywhere            

Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination         
ACCEPT     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere            
MASQUERADE  all  --  anywhere             anywhere            

Chain PR-QBS-SERVICES (1 references)
target     prot opt source               destination         
REDIRECT   tcp  --  anywhere             10.137.255.254       tcp dpt:us-cli
```

After manually executing `/usr/lib/qubes/qubes-setup-dnat-to-ns`, entries with `10.139.1.1` appear and DNS resolution in other AppVMs works again:

```
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination         
PR-QBS     all  --  anywhere             anywhere            
PR-QBS-SERVICES  all  --  anywhere             anywhere            

Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination         
ACCEPT     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere            
MASQUERADE  all  --  anywhere             anywhere            

Chain PR-QBS (1 references)
target     prot opt source               destination         
DNAT       udp  --  anywhere             10.139.1.1           udp dpt:domain to:1.1.1.1
DNAT       tcp  --  anywhere             10.139.1.1           tcp dpt:domain to:1.1.1.1
DNAT       udp  --  anywhere             10.139.1.2           udp dpt:domain to:1.1.1.1
DNAT       tcp  --  anywhere             10.139.1.2           tcp dpt:domain to:1.1.1.1

Chain PR-QBS-SERVICES (1 references)
target     prot opt source               destination         
REDIRECT   tcp  --  anywhere             10.137.255.254       tcp dpt:us-cli
```

**To Reproduce**
I don't know what triggers this problem, but I've observed this for a few months on an off on two different laptops runnng Qubes 4.0 (one of them installed from 4.0.0 over 1 year ago and updated, another recently installed with 4.0.2-rc3 and updated)

**Expected behavior**
DNS resolves in the browser and when using `dig` or `ping`.

**Actual behavior**
DNS does not resolve after some computer restarts. This never automatically resolves.

**Solutions you've tried**
A real fix: manually running `/usr/lib/qubes/qubes-setup-dnat-to-ns` on `sys-net` when that happens.
Other options: Adding `nameserver 1.1.1.1` (or any other valid nameserver) to `/etc/resolv.conf` on the VM in question. This is however not ideal as it has to be run on all AppVMs that connect to the internet.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
* https://www.qubes-os.org/doc/networking/

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
* https://github.com/QubesOS/qubes-issues/issues/5576 (this may be the same issue, although in this issue iptabes do contain 10.139.1.1 nat entries)
* https://github.com/QubesOS/qubes-issues/issues/5291
* https://github.com/QubesOS/qubes-issues/issues/4828

**Comment by unman** [comment]
@jschaul It might be useful to know the specs of those laptops.

Also, when you change the nameserver entry (from what?) does that fix the problem? (I dont understand why it should do because the magic happens in the netvm, but best to check.)

**Comment by andrewclausen** [comment]
I don't know if this is the same issue, but qubes-setup-dnat-to-ns does not run when I start/stop VPNs.

Where are setup-ip and qubes-setup-dnat-to-ns invoked?  I'm not sure how to search -- the code is so dispersed!

**Comment by rjt** [comment]
I just set my ip address to be **static** instead of relying on DHCP.  Will take many more reboots to find out if this elucidates the source of the problem.  I noticed that the outside network connection was not linking up till after some of the appVMs started.  The NetworkManager notification message that the network is up would not appear until after VMs were started.   S**SD PCs boot up so fast now that DHCP lags behind, breaking services because they do not have an IP address just yet.**  Make sure to turn network switch ports to forwarding mode if a desktop is on the other end and not a switch.

**Comment by jschaul** [comment]
> @jschaul It might be useful to know the specs of those laptops.

* (1) Lenovo W520 Model 42823FG from ~2011
* (2) Lenovo T460p from ~2017

Are there any particular hardware specifics that you're interested in? Thinking about it, the issue occurs mostly on the older (1) laptop, but as initially stated, only sometimes. 

> 
> Also, when you change the nameserver entry (from what?) does that fix the problem? (I dont understand why it should do because the magic happens in the netvm, but best to check.)

When I change the default entry, i.e.

```sh
# sudo cat /etc/resolv.conf
nameserver 10.139.1.1
nameserver 10.139.1.2
```

to

```sh
nameserver 1.1.1.1
```

or

```
nameserver 1.1.1.1
nameserver 10.139.1.1
nameserver 10.139.1.2
```

in an appVM, then, for this appVM alone, dns lookups work again. This is however not a good solution, as it only works for one VM. I have had better results manually running `sudo /usr/lib/qubes/qubes-setup-dnat-to-ns` on `sys-net`.

**Comment by sgabe** [comment]
I just encountered this issue. If you are using `NetworkManager` to configure a VPN connection, DNS resolution will not work, because `qubes-nmhook` is [not executed](https://github.com/QubesOS/qubes-core-agent-linux/blob/7f92aecc434a5dd3f664dd4b10dcecf4c315d170/network/qubes-nmhook#L7) for `vpn-up` events. It seems that @andrewclausen has run into the same, however, the other similar problems might be unrelated. Please let me know if you would be interested in a PR for this.

**Comment by DemiMarie** [comment]
A PR would be great!
