### ISSUE TITLE
Whonix GUI usability

### ISSUE THREAD

**Issue by ninavizz** [QubesOS/qubes-issues#5653]
## Problem
As a non-technical high-risk user, I will need to understand how to perform basic network performance improvement or risk mitigation tasks, having to do with my network connection through Tor—without being fluent in Tor, Whonix, developer, or opsec unique concepts or language. 

## Solution
_working sketch that illustrates the below concepts, not a dev-ready solution._

![image](https://user-images.githubusercontent.com/8262612/74578781-8625ff00-4f4b-11ea-92ea-774c104b7792.png)

**1. Clearly surface a GUI control for Whonix among the Tray icons.**
  - Semiotic should speak to the broadest possible concept (Whonix or Tor), not a concept or sub-functionality within it (TimeSync, as it is, today).
  - Icon should be actionable via same interaction other Tray icons are. 
    - Today, all tray icons _but_ the TimeSync icon, are acted upon with a simple click. The TimeSync icon, however, requires a right-click. 
  - Icon should not break (and thus show as a different graphic to non-developer users), when clicked upon. 
    - Bug. Boo. 
  - Tooltip should simply say _Whonix_, not either how to open it or other info.
  - If redundant Whonix instances exist on a user's machine, build the Whonix widget enacted from the tray to elegantly handle that w/o redundant widgets showing-up.
    - Possibly a super-duper-edge-case, but currently how the SD Workstation is architected.

**2. Clearly label functionality within Whonix GUI**
![image](https://user-images.githubusercontent.com/8262612/74576066-486ea980-4f3e-11ea-866e-522bd2616276.png)
- Use the label _Time Sync_, instead of `sdwsdate`, which is the name of the thingy a lovely community contributor built. :)
- If a bit of functionality is rarely used (such as I'm guessing Restart sdwdate is), locate it within a control window's UI—not the menu.

**3. Where possible, show the status itself—not a link to showing a status in a window.**
- Connection Status. Just say what it is, in one word. :)

**4. Clearly describe functional outcomes and guiding concepts in text w/in [Connection Wizard](https://www.whonix.org/wiki/Anon_Connection_Wizard).**
- The Wizard is a great first-step, but its use of written language is likely confusing to non-technical users. 
- This complete flow should receive user testing and subsequent text iterations to simplify.

**5. Get user testing and subsequent design iterations funded.**
- Funding exists on the Qubes team to _implement_ usability enhancements to existing `sdwsdate` tool. It would be great to get some rudimentary user testing and iteration done on solutions, so that funding is used wisely.

----
Cross-referencing as part of proposed EPIC #5520

**Comment by marmarek** [comment]
@ninavizz could you please put it in Whonix task tracker (https://phabricator.whonix.org/)? It will give better visibility to Whonix team - they don't monitor all the tickets here.

**Comment by ninavizz** [comment]
You betcha!

**Comment by andrewdavidwong** [comment]
(The "Far in the future" milestone is because we don't yet know when this will be implemented by the Whonix team, and hence which Qubes OS version with which it will happen to coincide.)

**Comment by ninavizz** [comment]
Created a Whonix ticket, and am cross-referencing it here: https://phabricator.whonix.org/T963

FWIW, the Tray icons do break in my Qubes instance—along with some other random icons—and I don't know if that's a Qubes-wide bug (@marmarta?) or a Whonix-only bug.

**Comment by marmarta** [comment]
@ninavizz do you mean the Whonix icons or all icons? What kind of 'break'? If you mean they vanish, it can be either (it just means the program crashed, basically) - the Qubes widgets should auto-regenerate their icons, but I'm afraid I have no idea how Whonix does it.

**Comment by ninavizz** [comment]
@marmarta Just speaking to my Whonix icons. I'll create a separate issue for how my existing icons break—but yeah, they visibly "break" and the bottom half and top half invert, or a broken icon is shown.

**Comment by marmarta** [comment]
wow... I have no idea how to replicate this bug, I've never seen it (so it's not impossible it's a Whonix bug, or some interesting interaction between Whonix and Qubes)

**Comment by 92VV3M42d3v8** [comment]
Are you talking about this @ninavizz 
![IMG_20200224_121231](https://user-images.githubusercontent.com/58817562/75177412-16123880-5704-11ea-8aad-064ebbb93705.jpg)
If yes, than it usually occurs when clicking icons, this is also common with sys-net network manager icon in tray especially when you manually disconnect.

**Comment by ninavizz** [comment]
^ Bingo. I'd thought Erik Moeller (@eloquence) had also filed an issue about this, but I cannot find it.

**Comment by eloquence** [comment]
I had not filed an issue for it yet, but I have now: #5704

I think this is more likely to be a Qubes issue than a Whonix issue as I've seen other icons occasionally glitch as well. Note that Nina and I have both seen this on independently provisioned laptops, and there's another report of the issue in the comment above.

**Comment by marmarta** [comment]
@marmarek , you have found a reason for that, haven't you? I might have had fever-induced hallucinations, but I do remember something about a weird bug in the color-applying code.

**Comment by ninavizz** [comment]
Filed [a Phabricator issue](https://phabricator.whonix.org/T992) for the right-click invocation bit.

**Comment by ninavizz** [comment]
Closing, as all Whonix UX stuff I'll be working directly with @adrelanos on, pulling @marmarta and Marek in as needed. Thank you all for patiently indulging my learning curve around which projects control what things w/in the broader whole of my Qubes laptop. :)
