### ISSUE TITLE
Warnings when using qubesdb with python >= 3.8

### ISSUE THREAD

**Issue by neowutran** [QubesOS/qubes-issues#5658]
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
core-qubesdb

**Brief summary**
On archlinux, using qubesdb write show warning.

**To Reproduce**
Install or uninstall anything on the archlinux template using pacman.
( The issue is not directly related to archlinux. Python version used on archlinux is more recent than in the others template, so the warning will come for the others templates too )

**Expected behavior**
`pacman` command execute successfully, without warnings

**Actual behavior**
`pacman` command execute successfully, but display the following warning:
`/usr/bin/qvm-features-request:73: DeprecationWarning: PY_SSIZE_T_CLEAN will be required for '#' formats`

**Screenshots**

**Additional context**

**Solutions you've tried**
None yet. 
The issue is related to a new version of python. Below some relevant link:
Issue in another project: https://github.com/python-pillow/Pillow/issues/3750
Origin of the warning: https://github.com/python/cpython/commit/0895793194cd5f1153d2a286ed3a4fc876149b16
Fix used in that other project: https://github.com/python-pillow/Pillow/pull/3749/files

While I didn't tried to write and test a fix, I think the modifications should be done here https://github.com/QubesOS/qubes-core-qubesdb/blob/master/python/qubesdb.c 
(maybe https://github.com/QubesOS/qubes-core-qubesdb/blob/master/python/qubesdb.c#L131,  https://github.com/QubesOS/qubes-core-qubesdb/blob/master/python/qubesdb.c#L403, and maybe somewhere else) 

(Also, could drop the check for python version since Python2 is now dead: https://github.com/QubesOS/qubes-core-qubesdb/blob/master/python/qubesdb.c#L220 and in others places )

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

**Comment by neowutran** [comment]
Tried to write a patch https://github.com/neowutran/qubes-core-qubesdb/commit/dbd464f3a904bc409dc1f749b963bc195948ddc8 
Seems to be working (Don't have any warning messages) but I will test it for a few days. 

However it cannot be merged as I deleted the part specific to python2 in qubesdb.c but didn't removed the python2 compilation for the debian and fedora packages (  I am unsure if they are still required or if only the python3 version is used. And also never touched nor a debian nor a fedora package building script )

**Comment by marmarek** [comment]
Dropping python2 support in master branch is fine (and even desirable). But release4.0 branch should still have python2 to not break existing installation.s

**Comment by hexagonrecursion** [comment]
I can reproduce this issue on [qubes-template-fedora-32-minimal 4.0.1-202004291030 (r4.0)](https://github.com/QubesOS/updates-status/issues/1767)

**Comment by neowutran** [comment]
Hi @hexagonrecursion 
This issue should affect all template with recent version of python.
I won't work on this issue/pull request for the moment, I have another one that I want to finish first. 
On my side, I applied the patchs to my archlinux template (dropping python2 and small patch for qubesdb.c), work well (archlinux only, 4.0 only). 
if you want, you can go and finish to fix the issue :)

**Comment by hexagonrecursion** [comment]
Will there be core-qubesdb v4.1.7 for **r4.0**?

**Comment by marmarek** [comment]
not 4.1.7, but one with backported fix to release4.0 branch - should be in current-testing repo shortly.
