### ISSUE TITLE
kernel 4-19.94.1 does not boot (on my thinkpads)

### ISSUE THREAD

**Issue by unman** [QubesOS/qubes-issues#5659]
**Qubes OS version**
4.0.3 with updates

**Affected component(s) or functionality**
Boot

**Brief summary**
Attempts to boot kernel 4.19.94 fail - returns to boot screen

**To Reproduce**
_Steps to reproduce the behavior:_
_1. Update to kernel 4-19.94-1'_
_2. Start Qubes machine_

**Expected behavior**
_The machine will boot_

**Actual behavior**
_Returns to boot selection screen_

**Additional context**
_qubes-dom0-update worked without error_
_Tested on a variety of thinkpads with same result._

**Solutions you've tried**
_Selecting vmlinux-4.19.84 works fine_
_reinstalling the packages makes no difference_

I'm currently testing from testing repository to see if that fixes issue.
Will update tomorrow.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
_A list of links to the Qubes documentation (or other relevant software documentation) pages you have already consulted._

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
_A list of links to other bug reports, feature requests, or tasks in the qubes-issues tracker (or "none" if you didn't find any). Do not describe any other unreported bugs, features, or tasks here._

**Comment by marmarek** [comment]
Make sure you didn't run out of disk space in /boot (or /boot/efi). If you did, initramfs may be incomplete for example.
