### ISSUE TITLE
Increase timeout for VM shutdown when prep'ing for backup

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#566]
**Reported by joanna on 12 May 2012 10:47 UTC**
Allow at least 60sec for each VM to shutdown. And even then, don't shut it down automatically, but rather display a promopt to the user whether to wait more or kill it.

Migrated-From: https://wiki.qubes-os.org/ticket/566

**Comment by fepitre** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

Build-template r4.0 centos7 201811030008
-----BEGIN PGP SIGNATURE-----

iQIzBAEBCAAdFiEEx6O6fS3a8ELHfKTSHavCMr4CIB4FAlvc5w8ACgkQHavCMr4C
IB4Ufw/9HegzyaMygKn9LeHgbpPeR18cwkvcJp74zbLnYtl/QVh7Ev9nS/bXpUUT
nv1oUv4UF5Bc/auABWQIOa6a8RysRzsfxFXL+YVdxdZOb0QFU0Ap6Q5OH0hbCuIN
7l6WTSLnB4VpyspcItSYqcRXuRLfYdVs0tkH2texQHlVuKrcI64zd9gCoa7tHUJT
AN/DAJy3kjN1Q45bFNhqID4AmBZWA4GfrgwwE4VwhAelXu4mDfptJXcMVJAgD17t
VDGDI3Ie6VShz7fgfFoH09uiQ2L4H8+G28F54MJTtBnzwGA9zCN1UWAXYPcOrKPS
sRa+OzM+se2pGnfE1q8mlkxYqgk0z8tTUs1pLgRKfjhpm/sQ/RpnQBbO1WLGxQFL
V5dzo5+ssQZp8rsNLQOsu1kxdyomxcI4/jWtKr19qMTfJZ11gxGKisLTMtT6fx9x
+jCVwYqHAay2qZ4LXR7LAJfI5Ld1YWd1cPBu1n0/IqQrNhYj/TIyoR2r+EUCSLFj
MY1VQlXka3cBxOKBORcbbuZvp+CkHBNZCKdAMsL7obtms/F5fABJUorIZfYg9Izi
LxE4YC6iBCoz7Q1bflYvGp5BT/ZtWLPIyhQbwYcTMmifoA5UYrDfYHjDv9nTvFsi
SXzK6KkaQ9EQ+DAMApMKR6jFxkVTrcOrwg63etTWpbCaN4JiJQo=
=Tdn1
-----END PGP SIGNATURE-----

**Comment by fepitre** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

Build-template r4.0 centos7+xfce 201811030008
-----BEGIN PGP SIGNATURE-----

iQIzBAEBCAAdFiEEx6O6fS3a8ELHfKTSHavCMr4CIB4FAlvc5xAACgkQHavCMr4C
IB49rhAAlMEH+Dk6zSjKrX1b+0cgDnkn30kR0Ft5Adew5V8vsPrGuNhdv8VHDx7J
ksehR/qawgR5jRgN840CuYaDM+va1YiNjyw725n6HEvp16yPbFb5sV2XcQIesn5B
/eEg3SaYc2ORt/tXknsNaS979IPGuA9zuQeJ9BRHb88Nx5KGn5vT/Fed/0LnEKts
OMD/vUH5tE0udRwTNF/vDbIClKwnxfy4OcHpN+Jwlu493Acfy0Hx8FS0vaeI21A+
at33Ie6JH8TqjYT+DAX+rJeAiLHXixVoiQqXtNUqSRR8F4jjMDdZgRG/+1uWEM9S
iZ+3+WTBenuErSrp3I0SGv0V7eKNiEkkUA2luAknWqBnvF/bkIChQ5gyYHDwzGN8
CnxMhAXbiKHJ1BZlrnS1yWuFb7T7/yJRCo5k4nZvXq95kviBssDav8/snlOaireu
Tx0Xdgsvb86pe12K7DgpbEmeiQTqxvuIkEp5Hn5OljSW3RY/1ZUygRlaBaK8CwPG
/Fzy9BvPCbrdJjzrg5m6aLiA2t3jQaBrKhFkqQ+Enxur+V27Az4RX8+ubQBwc0cn
bmUmpB9alfrfoNrusa+bGvIMHXqA+Enj3ghUdaP54CiDZ1af/HjRHsim6zY8yty1
GsH2uBeC/h8SDu64H3L7EgIZBOCzg8vg+fcfqiJnIuZIemPo5vk=
=LX/h
-----END PGP SIGNATURE-----
