### ISSUE TITLE
Q4.1 - dom0 / domU dual block device mount protection bug

### ISSUE THREAD

**Issue by 0spinboson** [QubesOS/qubes-issues#5660]
I see Qubes 4.1 no longer allows you to mount domains in dom0 as well as a VM. This seems a good practice, but there's a small bug in the current implementation. If you try to mount the block device while it's mounted in dom0, and then unmount in dom0 and try again, it won't allow you to do so, "livxenlight failed to attach disk". Assigning to and mounting in another VM (that I haven't tried to mount it to while it was mounted in dom0) works fine.

**Comment by marmarek** [comment]
Can you tell *exactly* what steps leads to the issue?

**Comment by 0spinboson** [comment]
mount in dom0
try to mount to some VM, have it fail
unmount in dom0
retry attaching to VM < fail
attach to a different VM < works.

**Comment by marmarek** [comment]
What device are you mounting? Do you mean by "mount" , actually "attach using qvm-block"?

**Comment by 0spinboson** [comment]
a harddrive / block device, using the Qubes devices widget
