### ISSUE TITLE
qubes-builder - Kali does not appear in setup menu

### ISSUE THREAD

**Issue by unman** [QubesOS/qubes-issues#5666]
**Qubes OS version**
R4.0.3

**Affected component(s) or functionality**
qubes-builder

**Brief summary**
All the infrastructure is there for building Kali, but it does not appear in setup menu.

**To Reproduce**
_Steps to reproduce the behavior:_
_1. Configure qubes-builder as normal_
_2. Clear `builder.conf`_
_3. Run `setup`_
_4. See error_

**Expected behavior**
_Kali will appear in menu listing_

**Actual behavior**
_Kali not present._

**Additional context**
_Is this because Kali is still served from @fepitre  repository?_
_If so, feel free to close the issue_

**Solutions you've tried**
_Adding `DISTS_VM=kali` in `example-configs/templates.conf` fixes_

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
_A list of links to the Qubes documentation (or other relevant software documentation) pages you have already consulted._

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
_A list of links to other bug reports, feature requests, or tasks in the qubes-issues tracker (or "none" if you didn't find any). Do not describe any other unreported bugs, features, or tasks here._

**Comment by fepitre** [comment]
It's not a bug, it's normal. It's like whonix. The repository qubes-template-kali is holding builder informations about the template. This is why you need to select the builder plugin `template-kali` then, getting the sources and run the setup again to have the `kali` template available.

**Comment by unman** [comment]
It's a long time since I built Whonix and I remember thinking it was half assed then.
This should probably be documented under Qubes-builder rather than just on the Whonix page.

Also, where can I get a copy of your key that's certified?
