### ISSUE TITLE
Not enough memory to start domain

### ISSUE THREAD

**Issue by archalchemy** [QubesOS/qubes-issues#5669]
**Qubes OS version**
Qubes release 4.0 (R4.0)

**Affected component(s) or functionality**
Dom0

**Brief summary**
When trying to turn on a StandaloneVM (Windows 7 HVM). It does not turn on even though I have RAM available in Dom0.

**To Reproduce**
_Steps to reproduce the behavior:_
_1. Go to 'Qubes Manager'_
_2. Click on 'Windows Standalone VM'_
_3. Rick Click 'Start/Resume VM'_
_4. See error_ Domain Windows7 has failed to start: Not enough memory to start domain 'Windows 7'

**Expected behavior**
_If the host has memory it should start the VM.._

**Actual behavior**
_Currently the VM does not start._

**Screenshots**
_
![Screenshot_2020-02-18_14-29-16](https://user-images.githubusercontent.com/61000333/74776807-deb40f80-525d-11ea-801e-eea138958e47.png)
._

**Additional context**
_No additional context._

**Solutions you've tried**
_Only if the amount of startup RAM is low, it can start._

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
_https://www.qubes-os.org/doc/out-of-memory/_

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
_A list of links to other bug reports, feature requests, or tasks in the qubes-issues tracker (or "none" if you didn't find any). Do not describe any other unreported bugs, features, or tasks here._

**Comment by brendanhoar** [comment]
What is output of xentop? dom0 memory is assigned to the VM running dom0. xentop will show you the free xen memory.

**Comment by archalchemy** [comment]
Thank you very much for your prompt response. Apparently Xen no longer has memory :(

![Screenshot_2020-02-18_15-32-24](https://user-images.githubusercontent.com/61000333/74780713-c8aa4d00-5265-11ea-8244-85edb7b2d560.png)

**Comment by andrewdavidwong** [comment]
> Thank you very much for your prompt response. Apparently Xen no longer has memory :(
> 
> ![Screenshot_2020-02-18_15-32-24](https://user-images.githubusercontent.com/61000333/74780713-c8aa4d00-5265-11ea-8244-85edb7b2d560.png)

It sounds like you've discovered that the error message is, in fact, accurate, so there is no bug here, correct? In that case, I'll close this as "not an issue." If you believe this is a mistake, please leave a comment, and we'll be happy to take another look. Thank you.
