### ISSUE TITLE
qubes-users mailing list lost a day 2020.02.21?

### ISSUE THREAD

**Issue by arno01** [QubesOS/qubes-issues#5680]
Hello,

sorry for the off-topic, but I find this is the most convenient place to post this.

I sent an email to qubes-users yesterday which has never arrived, then I looked here https://groups.google.com/forum/?nomobile=true#!forum/qubes-users

And can see that there are absolutely 0 messages from yesterday 2020.02.21.

Does anyone know what is going on?
Is it the Google having issues?

![Screenshot_20200222-094205_Chrome](https://user-images.githubusercontent.com/3791945/75089300-abbc9500-5557-11ea-9215-a8550806a347.jpg)

**Comment by fepitre** [comment]
No we had several mails the 21th.

**Comment by unman** [comment]
@arno01  I don't know what time zone you are in. If you bothered to inspect "Debian 10 and clone have no ifconfig ..." you would see the first mail came indeed on Feb 21.
All the mails from Feb21 are reflected in Google interface (which I went to for the first time in years.)
No issue.

**Comment by andrewdavidwong** [comment]
> I sent an email to qubes-users yesterday which has never arrived

Your message got caught in the spam filter and has since been released. Quoting from https://www.qubes-os.org/support/:
> If your message is not successfully sent to the list, it probably got caught in the spam filter. We check the spam filter regularly, so please be patient, and your message should be approved (and your email address added to the whitelist) within a few days.

As for the "missing" messages, it's just a time zone difference, as @unman pointed out.

**Comment by arno01** [comment]
my TZ is UTC+1 and my email has finally arrived after 21 hour 17 minutes since it was sent.

I sent it yesterday at 14:29, and it came today at 11:47.

![Screenshot_20200222-130527_FairEmail](https://user-images.githubusercontent.com/3791945/75092023-09f77100-5574-11ea-895b-58fe569e3a1b.jpg)

**Comment by arno01** [comment]
> > I sent an email to qubes-users yesterday which has never arrived
> 
> Your message got caught in the spam filter and has since been released. Quoting from https://www.qubes-os.org/support/:
> 
> > If your message is not successfully sent to the list, it probably got caught in the spam filter. We check the spam filter regularly, so please be patient, and your message should be approved (and your email address added to the whitelist) within a few days.

oh, that explains!
Thank you.
