### ISSUE TITLE
Builder - Kali (and bullseye) template builds fail

### ISSUE THREAD

**Issue by unman** [QubesOS/qubes-issues#5681]
**Qubes OS version**
_R 4.0.3 updated_

**Affected component(s) or functionality**
_Qubes builder._

**Brief summary**
_Bullseye build fails._

**To Reproduce**
_Steps to reproduce the behavior:_
_1.Configure builder to build bullseye/Kali_
_2. Attempt to make template_
_3. Build fails_

**Expected behavior**
_Template will be built_

**Actual behavior**
_Template build fails with error:_
> Can not locate a package.list file

**Additional context**
_The build is attempting to install packages in script_bullseye/packages.list._
_That directory does not exist, and therefore file cannot be found._

Although Bullseye is not yet a direct target for users, Kali is (after configuration) .

**Solutions you've tried**
_If applicable, any solutions or workarounds you've already tried._

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
_https://www.qubes-os.org/doc/qubes-builder/._

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
_none_

**Comment by fepitre** [comment]
Please note that initially, Kali template builder support is meant to be built _above_ bullseye. At least, bullseye is missing in setup tool list.

**Comment by unman** [comment]
> Kali template builder support is meant to be built above bullseye

What does this mean?

**Comment by fepitre** [comment]
It means that if you look at https://github.com/fepitre/qubes-template-kali/blob/master/builder.conf it assumes kali built with bullseye template.

**Comment by 0rb677** [comment]
Why Kali? https://blackarch.org/tools.html -  Tool count: 2460.

**Comment by fepitre** [comment]
> Why Kali? https://blackarch.org/tools.html - Tool count: 2460.

Feel free to do it.

**Comment by unman** [comment]
@fepitre I did reference bullseye in the actual report, but brainfog/drugs intervened with buster as well.
Should be clear now - it's bullseye build that fails, and therefore kali

**Comment by fepitre** [comment]
Yes. There is an issue currently (see https://github.com/QubesOS/build-issues/issues/1383) with respect to https://github.com/QubesOS/qubes-core-agent-linux/blob/5239e1ff62d7aeb47fd48eb220e48a09dfe59acf/debian/control#L109. Until a port and a maintainer of `dnf` under debian (see https://lists.debian.org/debian-devel/2019/09/msg00218.html), we discussed about it with @marmarek and we decided to make it no required for bullseye. If you have any other idea...

**Comment by unman** [comment]
@fepitre Is that the same issue? It doesn't look like it to me.

**Comment by fepitre** [comment]
> @fepitre Is that the same issue? It doesn't look like it to me.

Ok so it's weird. I need to redo your steps because I never encountered this trouble while building packages/ template for bullseye and then kali.

**Comment by fepitre** [comment]
I'm closing this issue as `bullseye` and `kali` build out of the box. Both are available on R4.1 repositories (itl-testing and community-testing).

**Comment by Jeeppler** [comment]
@fepitre Kali works fine?
