### ISSUE TITLE
I tried to create a WindowsVM with QubesOS, but why can't I do that?

### ISSUE THREAD

**Issue by Cvrew** [QubesOS/qubes-issues#5687]
I want to make WindowsVM with QubesOS. I did the following site. https://www.militant.dk/2019/01/06/windows-10-on-qubes-os-4-0/
I booted from the Windows iso file with QubesOS and started it, and I was able to install it, but I got a screen to restart from there and restarted, but I can not do it from there. When you start again, you will see the same screen again and you will be asked to restart. How can I solve it? I was able to do that. https://www.militant.dk/wp-content/uploads/2019/01/afterfirst-restart2-1-768x592.png

**Comment by GWeck** [comment]
See #5462 comment from 13 Jan - perhaps this helps.

**Comment by andrewdavidwong** [comment]
Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this does not appear to be suitable for `qubes-issues`. We ask that you please send this to the `qubes-users` [mailing list](https://www.qubes-os.org/support/) instead. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a brief comment explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.
