### ISSUE TITLE
How can I switch from CUI to GUI on KaliOS?

### ISSUE THREAD

**Issue by Cvrew** [QubesOS/qubes-issues#5688]
I installed KaliOS on the VM with QubesOS and the installation was completed successfully. However, if you start from there, it will be the terminal CUI startup instead of the GUI startup screen. How do I start the GUI?

**Comment by andrewdavidwong** [comment]
Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this does not appear to be suitable for `qubes-issues`. We ask that you please send this to the `qubes-users` [mailing list](https://www.qubes-os.org/support/) instead. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a brief comment explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.
