### ISSUE TITLE
CPU Overheating - Thinkpad

### ISSUE THREAD

**Issue by bluesteal** [QubesOS/qubes-issues#5695]
### Qubes OS version:

R4.0

### Affected component(s) or functionality:
Intel i7 CPU, graphics display

---

### Steps to reproduce the behavior:

This issue seems to be happening when a sufficient number of applications are launched, causing a sufficient level of CPU load, which results in overheating and a subsequent system crash. 

### Expected or desired behavior:

CPU temperatures between 40 - 65 Celsius; when sufficient load is reached, CPU temperature spikes to 90 - 100 degrees Celsius; when this temperature is reached, it forces a shutdown.

### Actual behavior:

CPU utilization causes CPU overheating and forced shutdown.

### General notes:

Thinkpad X230 
Fedora Kernel Version - 4.19.80-1

What is an appropriate CPU temperature? Is it possible to adjust CPU fan speed in Dom-0? 

---

### I have consulted the following relevant [documentation](https://www.qubes-os.org/doc/):
Thinkpad Troubleshooting documentation

### I am aware of the following related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues:

None reported

**Comment by 0spinboson** [comment]
To clarify: This only occurs when you run Qubes, and this is a recent change, as you were using Qubes without issues before? 

https://groups.google.com/forum/#!forum/qubes-users probably is a better place for this, btw.

**Comment by unman** [comment]
I see high temperatures on corebooted thinkpads.
Try installing thinkfan in dom0 and set the temperatures aggressively.
I have an old i5 - sometimes, when compiling on that, the temperatures reach high 90s, and the fan starts take off. It throttles down quickly enough, and the machine *never* shuts down.
Have you tried fresh thermal paste, and a clean of the fan? Always helps.

**Comment by bluesteal** [comment]
Yes I tried fresh thermal paste. The issue was that the fan was busted; I had to order a new one and install it but everything works fine now with default settings; I looked into thinkfan a while ago but it seemed to be mainly a hardware issue.

**Comment by bluesteal** [comment]
Intel security fixes? Do you mean Heartbleed, etc.?

**Comment by andrewdavidwong** [comment]
> The issue was that the fan was busted; I had to order a new one and install it but everything works fine now with default settings

Thanks for the update. Since this was a localized hardware problem, I'll close this now.
