### ISSUE TITLE
u2mfn module fails to build for Linux kernel 5.6

### ISSUE THREAD

**Issue by ij1** [QubesOS/qubes-issues#5698]
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
AppVM windows fail to open or contain garbage.

**Brief summary**
Updating debian-10 based template breaks GUI in pvgrub2-pvh booted AppVM. Either no application window appear or contains garbage pattern. Reverting template's root volume resolved the problem. I narrowed down the number of packages down to one which breaks it (qubes-kernel-vm-support).

**Expected behavior**
Application windows appear normally like they do w/o pvgrub2-pvh (or before the upgrade).

**Actual behavior**
No application window appears or window appears but displays only a graphical pattern (=garbage).

**Comment by marmarek** [comment]
Is it just this change, or connected with kernel update?

**Comment by ij1** [comment]
I didn't change anything else.

And I just tested first running sudo update-grub pre-update and the GUI still worked. But not after update of that package.

**Comment by marmarek** [comment]
The symptoms suggests the `u2mfn` module isn't built. In the upgrade process the old module should be removed and the new installed, see the transcript below. Do you have it different?

<details>

```
user@d10test:~$ sudo apt -V install qubes-kernel-vm-support
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages will be upgraded:
   qubes-kernel-vm-support (4.0.26+deb10u1 => 4.0.27+deb10u1)
1 upgraded, 0 newly installed, 0 to remove and 91 not upgraded.
Need to get 15.8 kB of archives.
After this operation, 1,024 B of additional disk space will be used.
Get:1 https://deb.qubes-os.org/r4.0/vm buster/main amd64 qubes-kernel-vm-support amd64 4.0.27+deb10u1 [15.8 kB]
Fetched 15.8 kB in 0s (70.2 kB/s)            
Reading changelogs... Done
(Reading database ... 133368 files and directories currently installed.)
Preparing to unpack .../qubes-kernel-vm-support_4.0.27+deb10u1_amd64.deb ...

-------- Uninstall Beginning --------
Module:  u2mfn
Version: 4.0.26
Kernel:  4.19.0-5-amd64 (x86_64)
-------------------------------------

Status: Before uninstall, this module version was ACTIVE on this kernel.

u2mfn.ko:
 - Uninstallation
   - Deleting from: /lib/modules/4.19.0-5-amd64/updates/dkms/
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.

depmod.....

DKMS: uninstall completed.

-------- Uninstall Beginning --------
Module:  u2mfn
Version: 4.0.26
Kernel:  4.19.0-6-amd64 (x86_64)
-------------------------------------

Status: Before uninstall, this module version was ACTIVE on this kernel.

u2mfn.ko:
 - Uninstallation
   - Deleting from: /lib/modules/4.19.0-6-amd64/updates/dkms/
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.

depmod.....

DKMS: uninstall completed.

------------------------------
Deleting module version: 4.0.26
completely from the DKMS tree.
------------------------------
Done.
Unpacking qubes-kernel-vm-support (4.0.27+deb10u1) over (4.0.26+deb10u1) ...
Setting up qubes-kernel-vm-support (4.0.27+deb10u1) ...
update-initramfs: deferring update (trigger activated)
Loading new u2mfn-4.0.27 DKMS files...
Building for 4.19.0-6-amd64
Building initial module for 4.19.0-6-amd64
Done.

u2mfn.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/4.19.0-6-amd64/updates/dkms/

depmod...

DKMS: install completed.
Generating grub configuration file ...
Found linux image: /boot/vmlinuz-4.19.0-6-amd64
Found initrd image: /boot/initrd.img-4.19.0-6-amd64
Found linux image: /boot/vmlinuz-4.19.0-5-amd64
Found initrd image: /boot/initrd.img-4.19.0-5-amd64
done
Processing triggers for initramfs-tools (0.133+deb10u1) ...
update-initramfs: Generating /boot/initrd.img-4.19.0-6-amd64
cryptsetup: WARNING: The initramfs image may not contain cryptsetup binaries 
    nor crypto modules. If that's on purpose, you may want to uninstall the 
    'cryptsetup-initramfs' package in order to disable the cryptsetup initramfs 
    integration and avoid this warning.
I: The initramfs will attempt to resume from /dev/xvdc1
I: (UUID=5c104b4e-1042-4f57-928c-f32d42daf940)
I: Set the RESUME variable to override this.
user@d10test:~$ find /lib/modules -name u2mfn.ko
/lib/modules/4.19.0-6-amd64/updates/dkms/u2mfn.ko
```

**Comment by DemiMarie** [comment]
I had this problem in the past, and wrote a script to fix it.

**Comment by DemiMarie** [comment]
I see the problem: the new version needs to be successfully installed before the old one is uninstalled.

**Comment by marmarek** [comment]
This is how standard dkms integration in Debian is done - it first remove old module and then installs new one. I _guess_ it does it to not remove just built module while removing the old one. I see two related bugs in Debian's dkms package:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=704150
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=704788

Anyway, this should be an issue only when the (new) build fails, and it would be good to find out why - if that's what really happened.
Does any of you have an output from such a failed update?

**Comment by ij1** [comment]
Indeed, there is one line indicating that module build seems to be failing. And it's unrelated to the package upgrade itself as I now managed to trigger the same problem also with the older version of qubes-kernel-vm-support when adding a new kernel.

From the dkms build log for I find these errors for u2mfn build: virt_to_phys (implicit declaration) and proc_create_data (passing arg 4 from incompatible pointer type). The kernel is ~5.6.0-rc5 (earlier I used 5.5.0 + gntdev fix when I saw the problem during upgrade).

Something is a bit odd though as I've managed to install+use many 5.5.0 based kernels just fine with the older version of qubes-kernel-vm-support.

**Comment by marmarek** [comment]
This looks rather like u2mfn module is incompatible with 5.6 kernel. So, it's not qubes-kernel-vm-support update causing the issue, but a kernel update.

**Comment by ij1** [comment]
For these latest problems, yes.

But I wasn't upgrading from 5.5.0 to 5.6-rcs until now. I'll see later if I can still reproduce the issue with 5.5.0 kernels to get the errors from the logs also for that case.

**Comment by ij1** [comment]
There was no dkms build error with 5.5.0 while upgrading only the qubes-kernel-vm-support package I think that my issue in that case is caused by dkms not build the module for all installed kernels.

**Comment by marmarek** [comment]
This was fixed with the PR linked above.
