### ISSUE TITLE
Missing newline in qvm-usb timeout output

### ISSUE THREAD

**Issue by strugee** [QubesOS/qubes-issues#5701]
### Qubes OS version:

R4.0

### Affected component(s) or functionality:

qvm-usb

---

### Steps to reproduce the behavior:

1. Run `qvm-usb attach <domain> <device>` in some situation that will cause an attach timeout (in my case this is a separate bug that I'll report shortly)
2. Wait a few seconds

### Expected or desired behavior:

This error is printed:

```
Device attach failed: /usr/lib/qubes/usb-import: 94: echo: echo: I/O error
Attach timeout, check kernel log for details. VM: "steevie-cloud" File: "/usr/lib/qubes/usb-import" Version Control: https://github.com/QubesOS/qubes-app-linux-usb-proxy/blob/master/src/usb-import
```

Maybe without the `echo: echo:` too, I'm a little confused as to where those are coming from?

### Actual behavior:

This is printed:

```
Device attach failed: /usr/lib/qubes/usb-import: 94: echo: echo: I/O errorAttach timeout, check kernel log for details. VM: "steevie-cloud" File: "/usr/lib/qubes/usb-import" Version Control: https://github.com/QubesOS/qubes-app-linux-usb-proxy/blob/master/src/usb-import
```

Notice the newline which is missing in between "I/O error" and "Attach timeout".

### General notes:

```
[dom0] $ dnf info qubes-usb-proxy-dom0 | grep Version
Version     : 1.0.27
```

---

### I have consulted the following relevant [documentation](https://www.qubes-os.org/doc/):

None

### I am aware of the following related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues:

None

**Comment by bakeromso** [comment]
Affects 4.1

**Comment by alimirjamali** [comment]
@strugee @bakeromso Could you modify and change one line in the `/etc/qubes-rpc/qubes.USBAttach` file in your sys-usb:
```
qrexec-client-vm "$domain" "qubes.USB+$busid" \
    /usr/lib/qubes/usb-import "$statefile" \
    </dev/null >/dev/null 2>/dev/null &
```
to
```
qrexec-client-vm "$domain" "qubes.USB+$busid" \
    "$(/usr/lib/qubes/usb-import ${statefile})" \
    </dev/null >/dev/null 2>/dev/null &
```
and see if it fixes the issue? Since sys-usb is a disposable VM, you should not need to backup the file. Restarting sys-usb would revert the change.

**Comment by marmarek** [comment]
that's definitely not how it should be - the `/usr/lib/qubes/usb-import` path is an argument to qrexec-client-vm (which will call it locally)

**Comment by bakeromso** [comment]
@alimirjamali I wouldn't mind testing a fix, however I don't recall what device caused the timeout. If you have a way to force the timeout, then I'd be happy to give it a go. 

@marmarek Do you maybe have a different suggestion?

**Comment by alimirjamali** [comment]
> that's definitely not how it should be - the `/usr/lib/qubes/usb-import` path is an argument to qrexec-client-vm (which will call it locally)

Sorry for mistake. Just realized it. Mixes another bash related issue with this one. the qrexec-client-vm is not properly parsing the usb-import output. All new-line wraps are missing. Not just one. I will try to look into this further.

**Comment by atfinne** [comment]
if an update is needed

issue still persists

**Comment by alimirjamali** [comment]
PR Submitted

Affects 4.2 & 4.3 as well as 4.1

Review priority: Low

Development notes: PR Submitted against main branch of `qubes-app-linux-usb-proxy`. It should be decided if individual patches are needed for both r4.2 & r4.3 branches.
