### ISSUE TITLE
Whonix system tray icon breaks when right-clicking it

### ISSUE THREAD

**Issue by eloquence** [QubesOS/qubes-issues#5704]
**Qubes OS version**
_The version of Qubes OS you're using (e.g., `R4.0`), available via the command `cat /etc/qubes-release` in a dom0 terminal._

R4.0

**Affected component(s) or functionality**
_The component or functionality of Qubes OS that is not working as expected._

Whonix

**Brief summary**
_A clear and concise summary of the bug._

The Whonix sys tray icon (sdwdate-gui) is very glitchy; clicking it causes the icon to "fall apart" in interesting ways. Other system tray icons are also somewhat glitchy (e.g., I've seen the network manager icon overlap with itself after extended use), but not as bad as the Whonix icon.

**To Reproduce**
_Steps to reproduce the behavior:_
1. Ensure you have a Whonix gateway and workstation VM running.
2. Right-click the sdwdate-gui icon in the system tray repeatedly to get its context menu

**Expected behavior**
_A clear and concise description of what you expected to happen._

The context menu works normally and the icon does not change.

**Actual behavior**
_What actually happened (instead of what you expected to happen)._

The icon falls apart while you click on it. It gets glitchier the more you interact with it.

**Screenshots**
_If applicable, add screenshots to help explain your problem._

![screenshot](https://user-images.githubusercontent.com/213636/70689918-5f58fd00-1c6a-11ea-8253-0abbb5e0aeab.png)

From [another report](https://github.com/QubesOS/qubes-issues/issues/5653#issuecomment-590463801):

![screenshot](https://user-images.githubusercontent.com/58817562/75177412-16123880-5704-11ea-8aad-064ebbb93705.jpg)

**Comment by marmarek** [comment]
I can reproduce the issue by clicking on the icon. Interestingly sdwdate-gui is the only icon I have with this problem, others I've tried (hexchat, nm-applet, nexcloud) works fine.
I'll look more into this, but probably only next week.

**Comment by ninavizz** [comment]
Ok, this happened to me again, last night :/ Exactly as shown in the screen above. /cc @marmarta

**Comment by marmarek** [comment]
The update is still in testing repository only and for R4.1 only. Will migrate to R4.0 in few weeks.
