### ISSUE TITLE
Qubes Updater silent failure while updating debian-10 TemplateVM

### ISSUE THREAD

**Issue by emkll** [QubesOS/qubes-issues#5705]
**Qubes OS version**
Qubes release 4.0 (R4.0)

**Affected component(s) or functionality**
Qubes Updater / update/qubes-vm.sls

**Brief summary**
Qubes Updater fails to update Debian-based Template

**To Reproduce**
1. Open Qubes updater
2. Select debian-10
3. Click next
or
1. run `sudo qubesctl --show-output --skip-dom0 --targets debian-10 state.sls update.qubes-vm` in dom0.

**Expected behavior**

- Packages inside the VM should be upgraded, and return OK
- Otherwise, failed upgrade operations should return a failure message success in the UI

**Actual behavior**
- Packages in the VM are not upgraded, and output of the qubesctl command does not contain `OK`
- UI suggests the upgrade was successfully completed (qubesctl command returns 0), even though a Salt error occurred in the Template

What appears to be relevant output in `debian-10` template:
```
Mar  4 14:18:21 localhost systemd[1]: Started Session c14 of user root.
Mar  4 14:18:22 localhost qubes.VMRootShell-disp-mgmt-debian-10: SALT_ARGV: ['/usr/bin/python3', '/var/tmp/.root_62a99a_salt/salt-call', '--retcode-passthrough', '--local', '--metadata', '--out', 'json', '-l', 'quiet', '-c', '/var/tmp/.root_62a99a_salt', '--', 'test.opts_pkg']
Mar  4 14:18:22 localhost qubes.VMRootShell-disp-mgmt-debian-10: _edbc7885e4f9aac9b83b35999b68d015148caf467b78fa39c05f669c0ff89878
Mar  4 14:18:25 localhost systemd[1]: session-c14.scope: Succeeded.
Mar  4 14:18:25 localhost qrexec-agent[481]: send exit code 0
Mar  4 14:18:25 localhost qrexec-agent[481]: pid 1694 exited with 0
Mar  4 14:18:25 localhost qrexec-agent[481]: eintr
Mar  4 14:18:26 localhost qrexec-agent[481]: executed root:QUBESRPC qubes.VMRootShell disp-mgmt-debian-10 pid 1793
Mar  4 14:18:26 localhost systemd[1]: Started Session c15 of user root.
Mar  4 14:18:26 localhost systemd[1]: session-c15.scope: Succeeded.
Mar  4 14:18:26 localhost qrexec-agent[481]: send exit code 0
Mar  4 14:18:26 localhost qrexec-agent[481]: pid 1793 exited with 0
Mar  4 14:18:26 localhost qrexec-agent[481]: eintr
Mar  4 14:18:26 localhost qrexec-agent[481]: executed root:QUBESRPC qubes.VMRootShell disp-mgmt-debian-10 pid 1807
Mar  4 14:18:26 localhost systemd[1]: Started Session c16 of user root.
Mar  4 14:18:26 localhost qubes.VMRootShell-disp-mgmt-debian-10: SALT_ARGV: ['/usr/bin/python3', '/var/tmp/.root_62a99a_salt/salt-call', '--retcode-passthrough', '--local', '--metadata', '--out', 'json', '-l', 'quiet', '-c', '/var/tmp/.root_62a99a_salt', '--', 'state.pkg', '/var/tmp/.root_62a99a_salt/salt_state.tgz', 'test=None', 'pkg_sum=89f155d29e841fb86d260190219775a6bfafa1aeab4087303dfd9e763ca06cf5', 'hash_type=sha256']
Mar  4 14:18:26 localhost qubes.VMRootShell-disp-mgmt-debian-10: _edbc7885e4f9aac9b83b35999b68d015148caf467b78fa39c05f669c0ff89878
Mar  4 14:18:31 localhost qubes.VMRootShell-disp-mgmt-debian-10: Traceback (most recent call last):
Mar  4 14:18:31 localhost qubes.VMRootShell-disp-mgmt-debian-10:   File "/var/tmp/.root_62a99a_salt/salt-call", line 27, in <module>
Mar  4 14:18:31 localhost qubes.VMRootShell-disp-mgmt-debian-10:     salt_call()
Mar  4 14:18:31 localhost qubes.VMRootShell-disp-mgmt-debian-10:   File "/var/tmp/.root_62a99a_salt/pyall/salt/scripts.py", line 445, in salt_call
Mar  4 14:18:31 localhost qubes.VMRootShell-disp-mgmt-debian-10:     client.run()
Mar  4 14:18:31 localhost qubes.VMRootShell-disp-mgmt-debian-10:   File "/var/tmp/.root_62a99a_salt/pyall/salt/cli/call.py", line 57, in run
Mar  4 14:18:31 localhost qubes.VMRootShell-disp-mgmt-debian-10:     caller.run()
Mar  4 14:18:31 localhost qubes.VMRootShell-disp-mgmt-debian-10:   File "/var/tmp/.root_62a99a_salt/pyall/salt/cli/caller.py", line 119, in run
Mar  4 14:18:31 localhost qubes.VMRootShell-disp-mgmt-debian-10:     ret = self.call()
Mar  4 14:18:31 localhost qubes.VMRootShell-disp-mgmt-debian-10:   File "/var/tmp/.root_62a99a_salt/pyall/salt/cli/caller.py", line 232, in call
Mar  4 14:18:31 localhost qubes.VMRootShell-disp-mgmt-debian-10:     func.__module__].__context__.get('retcode', 0)
Mar  4 14:18:31 localhost qubes.VMRootShell-disp-mgmt-debian-10: KeyError: 'salt.loaded.int.module.state'
Mar  4 14:18:32 localhost qrexec-agent[481]: send exit code 1
Mar  4 14:18:32 localhost qrexec-agent[481]: pid 1807 exited with 1
Mar  4 14:18:32 localhost systemd[1]: session-c16.scope: Succeeded.
Mar  4 14:18:32 localhost qrexec-agent[481]: eintr
```
**Screenshots**
![updater](https://user-images.githubusercontent.com/15223328/75914985-b0b8f880-5e23-11ea-8d41-4b4c22ba1b21.png)

![qubesctl_dom0](https://user-images.githubusercontent.com/15223328/75914694-37210a80-5e23-11ea-8fe8-6896014c7e19.png)

**Additional context**
- Installing qubes 4.0.3 from scratch, I could not immediately reproduce, it seems like an issue with existing templates. 
For reference, the version of qubes-template-debian-10.noarch I am using is 4..1-201905201854

**Solutions you've tried**
- Running `apt upgrade` directly on the VM itself does work, it seems like the issue is limited to salt

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
none

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
none

**Comment by eribabu** [comment]
This issue may be related to #5598 
[My comment here.](https://github.com/QubesOS/qubes-issues/issues/5598#issuecomment-594796559)

Issue occurs on during intial setup, where progress bar hangs on configuring debian-10 TemplateVM.

**Comment by redshiftzero** [comment]
possibly related: https://github.com/saltstack/salt/issues/56131

**Comment by emkll** [comment]
I think the ticket linked by @redshiftzero is very likely related:

Based on my local testing, on a freshly installed Qubes 4.0.3 machine:

On a fully patched Fedora-30 template, the `salt` version is 3000-2. I have downgraded the `salt` package (via `sudo dnf downgrade salt`, which also downgrades `salt-ssh`) to version 2019.2.0-1.fc30. After downgrading this package, the updater (and Salt) work as expected.

**Comment by conorsch** [comment]
Worth noting that using F29 (warning: Fedora29 is EOL) for the mgmt vm also resolves, due to the implicit version downgrade. So setting `qvm-prefs default-mgmt-dvm template fedora-29`, assuming you still have `qubes-template-fedora-29`, lets `qubesctl` run successfully again. Sharing this info less as a workaround and more because I'm unsure what most folks have for the default mgmt dvm template. The last time I performed a clean install of the OS was Qubes 4.0.1, and if memory serves, I altered the value to F30 while removing F29 templates across the board a few months back.

**Comment by marmarek** [comment]
Looks like [this](https://github.com/QubesOS/qubes-mgmt-salt/commit/3e18918d0d784752bdbe31f9183d1bc449efa689) wants backporting. Note version difference - apparently failing without python-pip package is a common pattern in salt...

**Comment by DemiMarie** [comment]
Should we install the `python-pip` package?

**Comment by marmarek** [comment]
This is exactly what the commit I pointed in https://github.com/QubesOS/qubes-issues/issues/5705#issuecomment-595413698 does.

**Comment by marmarek** [comment]
If I read this correctly, we'd need python3-pip in every VM that is managed by salt, not only where salt-ssh is running. This means a simple dependency on a salt-related package isn't enough.

On the other hand, the failing code applies only to states using "onlyif" keyword - if I remove them, the update works. Since the salt bug will probably take some more time to fix (PR with the fix is there already, but then it would need to be merged, released and packaged into Fedora), I'd go with avoiding "onlyif" in the update formula. Fortunately, it is used only to apply updates that are incorporated into new templates already, so I can simply remove those entries.

**Comment by eloquence** [comment]
Thanks for the quick response & PRs, Marek. This is a critical issue for the SecureDrop Workstation pilot from our perspective as it prevents important system updates from succeeding, and we'd obviously prefer not to manually downgrade packages for security reasons. Is there any way we can help to get this over the finish line?

**Comment by marmarek** [comment]
Main blocker is testing capacity (openqa busy on other set of PRs already). If you could test those two PRs in your environment too, that would help a lot.

**Comment by xet7** [comment]
When I update Qubes VMs, after updates it still shows that all did not update, with green arrow icon.

To get Debian 10 template updated, I need to do manually:
```
sudo apt update
sudo apt -y dist-upgrade
sudo apt clean
sudo apt autoclean
sudo apt -y autoremove
```
For Fedora 30 templates, I need to do manually:
```
sudo dnf upgrade
sudo dnf clean all
```
Would it be possible to change update scripts so that all this cleanup would also be run automatically?

**Comment by conorsch** [comment]
Confirming that v4.0.9 of `qubes-mgmt-salt-dom0-update`, obtained via `sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing`, as [documented here](https://www.qubes-os.org/doc/software-update-dom0/#testing-repositories), resolves the issue completely. The GUI updater now properly updates packages within TemplateVMs. 

Many thanks for the quick action here, @marmarek! :smiley:

**Comment by conorsch** [comment]
Do you have an estimate for when v4.0.9 of `qubes-mgmt-salt-dom0-update` will land in the stable dom0 repos? According to https://www.qubes-os.org/doc/testing/, the package will be in testing "for a minimum of one week", which is true as of two days ago. It'd be great to see the package land this week, as we're currently in the final stages of QA before installs next week.
