### ISSUE TITLE
Qubes-4.x DNS stopped working

### ISSUE THREAD

**Issue by permezel** [QubesOS/qubes-issues#5706]
**Qubes OS version**
R4.0
(I thought if I kept up to date I was supposed to be the same as the recent 4.1 release.  Clearly not if it says R4.0 here, but I do keep up to date).

**Affected component(s) or functionality**
Fedora-30-based AppVM.
DNS lookup failing.  All sites.
Cannot ping the DNS server addresses.

**Brief summary**
Apparently the firewall rules for the nameserver pseudo hosts are not being applied.
A few days ago, and a few of the constant updates ago, everything worked.
 
**To Reproduce**
1.  $ cat /etc/resolv.conf
nameserver 10.139.1.1
nameserver 10.139.1.2
2. $ ping www.apple.com
ping: www.apple.com: Name or service not known
3. $ ping 8.8.8.8
  works fine

I mainly use this AppVM for WEB access.  Nothing works.  If I do:

 root# echo 'nameserver 8.8.8.8' >/etc/resolv.conf

It works.

Something broke in one of the recent updates.

Could it be because I cloned Fedora-30 and added my set of customisations to it and use that as the base for the AppVM?  I always base this AppVM off Fedora-XX-enhanced and whenever I update the templateVM I re-clone and re-create the -enhanced version and have been using this with no problems for months.

I also always apply the updates to dom0, Fedora-30 and Fedora-30-enhanced templates, and after one of these updates, this problem appeared.

sys-net and sys-firewall are based on fedora-30, and I suspect that the firewall mapping for the fake nameservers are in one of them, not in my AppVM.

**Expected behavior**
I expect the DNS to work.

**Actual behavior**
The DNS does not work.

**Screenshots**
_If applicable, add screenshots to help explain your problem._

**Additional context**
The update process still succeeds.  I assume that is because I am using WhoNix, which uses Tor, so bypasses DNS.

**Solutions you've tried**
I can rewrite the resolv.conf file to send the DNS reqs to 8.8.8.8.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
_A list of links to the Qubes documentation (or other relevant software documentation) pages you have already consulted._

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
_A list of links to other bug reports, feature requests, or tasks in the qubes-issues tracker (or "none" if you didn't find any). Do not describe any other unreported bugs, features, or tasks here._

**Comment by permezel** [comment]
Found out what most likely happened.

I used to connect via WiFi.
Then I added a wired connexion.  For a while, both (on the same LAN) were active.  Then I disabled the WiFi.  This broke the DNS resolution.

The wired entry uses DHCP.  Should pick up the DNS from the DHCP response.
I added a manual DNS entry, and did a disconnect/reconnect, undid the 8.8.8.8 change to the AppVM, and now things are working.  Weird thing is that it also gets an IPv6 address for DNS, plus it gets my domain. I did not specify that, so it is getting stuff from DHCP response.

Not sure why it is flakey, but now I know a) how to see the NAT entries (iptables --list was not showing them to me) and how to debug this better going forwards.

For now, until I reboot, I am happy and it is working.

**Comment by andrewdavidwong** [comment]
> (I thought if I kept up to date I was supposed to be the same as the recent 4.1 release. Clearly not if it says R4.0 here, but I do keep up to date).

R4.1 is still under development and testing. R4.0 is the latest stable release.

**Comment by andrewdavidwong** [comment]
> Found out what most likely happened.
> 
> I used to connect via WiFi.
> Then I added a wired connexion. For a while, both (on the same LAN) were active. Then I disabled the WiFi. This broke the DNS resolution.
> 
> The wired entry uses DHCP. Should pick up the DNS from the DHCP response.
> I added a manual DNS entry, and did a disconnect/reconnect, undid the 8.8.8.8 change to the AppVM, and now things are working. Weird thing is that it also gets an IPv6 address for DNS, plus it gets my domain. I did not specify that, so it is getting stuff from DHCP response.
> 
> Not sure why it is flakey, but now I know a) how to see the NAT entries (iptables --list was not showing them to me) and how to debug this better going forwards.
> 
> For now, until I reboot, I am happy and it is working.

This sounds like it might not be a Qubes-specific bug.

**Comment by permezel** [comment]
I just tried an experiment with sys-net.
1. Removed the explicit DNS server entry using "Advanced Network Configuration".
2. shutdown -r now (sys-net only)
3. restart sys-net
4. cat /etc/resolv.conf
-- contains valid DNS info
5. date
6. ls -l /etc/resolv.conf
-- shows updated after restart
7. iptables -t nat -n L
-- no DNAT entries to map NS1 and NS2 entries from AppVMs

Seems like a Qubes issue.

1. Manually disconnect using widget on top left menu bar.
2. Manually reconnect using same widget
3. Verify via mod time that resolv.conf updated: we are getting DNS info
4. Verify that NAT entries are not being installed.

1. Add back in the explicit DNS entry using Network Connexions app.
2. Confirm that I am using DHCP not "DHCP (address only)"
(only because I know you will ask: I never select the 'address only' variant)
3. Manually down/up the conx.
4. verify that the DNAT entries are added.

Actually, the first time, there were no DNAT entries added.  I then added 'local' to the search list, and did a down/up toggle, and this time the DNAT entries were added.

Anything you want me to do to try and get to the bottom of this?

**Comment by rjt** [comment]
My DNS broke as well.  Not sure if at all related, but one appvm has its Qubes firewall to whitelist specific internal ip addresses.  None of the whitelisted IP addresses are reachable.

**Comment by rjt** [comment]
You might try running `sudo /usr/lib/qubes/qubes-setup-dnat-to-ns` on the **sys-net** vm.

I set my IP addresses to be all static in the hopes that the problem lies in a DHCP network connection not linking and populating IP addresses until long after client VMs have booted up.

**Comment by permezel** [comment]
> On 10 Apr 2020, at 10:07, Robert Townley <notifications@github.com> wrote:
> 
> You might try running sudo /usr/lib/qubes/qubes-setup-dnat-to-ns on the sys-net vm.
> I set my IP addresses to be all static in the hopes that the problem lies in a DHCP network connection not linking and populating IP addresses until long after client VMs have booted up.
> 
> 

That works.  Thanks.

**Comment by arkenoi** [comment]
Now I have the same issue since I upgraded sys-net to fc35. Anything else I can do to help to resolve?

**Comment by DemiMarie** [comment]
> Now I have the same issue since I upgraded sys-net to fc35. Anything else I can do to help to resolve?

Problem is almost certainly with how Qubes configures DNS in the presence of systemd-resolved.  Can you provide the output of `sudo iptables-save` in sys-net?

**Comment by marmarek** [comment]
Can you try installing [updates from current-testing repo](https://www.qubes-os.org/doc/how-to-install-software/#testing-repositories), especially qubes-core-agent* 4.0.65?

**Comment by arkenoi** [comment]
I have 4.1.34-1

**Comment by marmarek** [comment]
> I have 4.1.34-1

For Qubes 4.1 the fixed version is 4.1.35

**Comment by andrewdavidwong** [comment]
Is this still a problem in 4.1?

**Comment by permezel** [comment]
Not a problem for me on 4.1.

**Comment by andrewdavidwong** [comment]
Closing as resolved. If anyone believes this issue is not yet resolved, or if anyone is still affected by this issue, please leave a comment, and we'll be happy to reopen it. Thank you.
