### ISSUE TITLE
Unable to launch installer from usb

### ISSUE THREAD

**Issue by zhihuiyuze** [QubesOS/qubes-issues#5709]
Qubes OS version:4.0.3
DD black screen after writing a screen of text after booting from u disk
Attempting to write to iso can write to 4G, but a text flashes during installation, and the screen keeps blanking.
I don't think it's a matter of read speed
The screen stays blank all night, so this is not a matter of reading and writing speed.
hardware information
A300M-STX
2400G
usb2.0

**Comment by andrewdavidwong** [comment]
Did you verify the ISO from your USB drive after writing it there?

**Comment by zhihuiyuze** [comment]
> 在USB驱动器中写入ISO后，您是否对其进行了验证？

Checked sha256 after downloading. The write is not verified. How do I verify?

**Comment by zhihuiyuze** [comment]
> 在USB驱动器中写入ISO后，您是否对其进行了验证？

[zhyz@zhyz-pc 下载]$ sudo dd if=/dev/sdb1 bs=1M iflag=count_bytes count=4830789632 | sha1sum
[sudo] zhyz 的密码：


记录了4607+0 的读入
记录了4607+0 的写出
4830789632 bytes (4.8 GB, 4.5 GiB) copied, 209.054 s, 23.1 MB/s
0152c87f762d58ce5579f23f0fd190efa197d7a7  -
Seems like something went wrong? I try to rewrite.

**Comment by zhihuiyuze** [comment]
`zhyz@zhyz-pc 下载]$ sudo dd if=Qubes-R4.0.3-x86_64.iso of=/dev/sdb bs=1048576 && sync
`[zhyz@zhyz-pc 下载]$ du -b Qubes-R4.0.3-x86_64.iso`
`[zhyz@zhyz-pc 下载]$ sudo dd if=/dev/sdb bs=1M iflag=count_bytes count=1048576 | sha1sum
记录了1+0 的读入
记录了1+0 的写出
1048576 bytes (1.0 MB, 1.0 MiB) copied, 0.0513907 s, 20.4 MB/s
bd6da418a29add3706c99a2f46e54114afbc836a  `
Is this correct?

**Comment by marmarek** [comment]
You hashed only the first 1MB, not the whole image - count= value is wrong.
As for the correct hashes, you can check them on the downloads page under "Digests" link.

**Comment by zhihuiyuze** [comment]
[zhyz@zhyz-pc 下载]$ sudo dd if=/dev/sdb1 bs=1048576 iflag=count_bytes count=4830789632 | sha1sum
[sudo] zhyz 的密码：
记录了4607+0 的读入
记录了4607+0 的写出
4830789632 bytes (4.8 GB, 4.5 GiB) copied, 124.131 s, 38.9 MB/s
8985cc3484bb2058e38401e2ff492e4402d07850  -
Verification successful

**Comment by zhihuiyuze** [comment]
My A300M-STX motherboard computer can run normally and successfully install by closing uefi and starting csm. Unfortunately, uefi is not supported
