### ISSUE TITLE
Initial setup: sys-usb option enabled on installation to USB drive, make the system unbootable

### ISSUE THREAD

**Issue by ds2k5** [QubesOS/qubes-issues#5710]
Version 4.0.3 with EFI, install with USB-Stick

![IMG_0037](https://user-images.githubusercontent.com/11292286/76128397-870af780-6004-11ea-8fab-a2f2a67a927d.JPG)

![IMG_0038](https://user-images.githubusercontent.com/11292286/76128413-91c58c80-6004-11ea-9335-a399df5df046.JPG)

got black screen

Strg + ALT + F2

![IMG_0033](https://user-images.githubusercontent.com/11292286/76128510-ce918380-6004-11ea-8ff9-dcf70042f9a7.JPG)

Power OFF / Power ON

![IMG_0035](https://user-images.githubusercontent.com/11292286/76128545-ea952500-6004-11ea-943a-33176f9473a8.JPG)

![IMG_0036](https://user-images.githubusercontent.com/11292286/76128556-f08b0600-6004-11ea-8865-7466b92b369c.JPG)

![IMG_0039](https://user-images.githubusercontent.com/11292286/76128578-fe408b80-6004-11ea-80a5-55586148f048.JPG)

Did not matter if using encryption or not

**Comment by zhihuiyuze** [comment]
I can't even get the installer. Try `startx?`

**Comment by ds2k5** [comment]
sorry at this point the system hang, no input possible... 
I can mount the system when boot from another system.
but only Xorg.9.log is there

[Xorg.9.log](https://github.com/QubesOS/qubes-issues/files/4301556/Xorg.9.log)

[boot.log](https://github.com/QubesOS/qubes-issues/files/4301557/boot.log)

**Comment by zhihuiyuze** [comment]
`nt9)
[    13.135] (II) No input driver specified, ignoring this device.`
可能是没有驱动,我对Qubes OS不是很熟悉。这可能会误导你
Maybe it is not driven, I am not very familiar with Qubes OS. This may mislead you

**Comment by marmarek** [comment]
It rather looks like some disk issue. In a dracut prompt check `lvm lvs` command - if you see root and swap volumes. Also check the rdsoreport.txt file for entries mentioning lvm, root and swap.
Anyway, it looks like a better fit for qubes-users mailing list, not issue tracker: https://www.qubes-os.org/support/

**Comment by ds2k5** [comment]
If I install and do not configure the system boot
but not useable because the settings not done

**Comment by ds2k5** [comment]
@ marmarek :  lvm lvs  did not show something

**Comment by ds2k5** [comment]
here the report file

[rdsosreport.txt](https://github.com/QubesOS/qubes-issues/files/4301681/rdsosreport.txt)

**Comment by ds2k5** [comment]
system is installed on a USB-Device, but can not see this device ...

but why did the system boot if do not configure the system
cancel  here at this point and select do not configure...

![Uploading cancel.JPG…]()

**Comment by marmarek** [comment]
Oh, I see. You installed to USB and then enabled sys-usb. This makes the USB controllers unavailable in dom0, which makes the system unable to locate then on boot. This option should be disabled when installed to USB.
Try reinstalling and disable sys-usb option in that dialog.

**Comment by ds2k5** [comment]
>Try reinstalling and disable sys-usb option in that dialog. 

thanks marmarek  this works for me!
