### ISSUE TITLE
bug with ddr or session

### ISSUE THREAD

**Issue by Aporbel** [QubesOS/qubes-issues#5712]
**Qubes OS version**
Qubes release 4.0 (R4.0)

**Affected component(s) or functionality**
work with operation memory (ddr)

**Brief summary**
I load the os, doing something and stay open windows(nautilus) and terminal after this I start shutdowning. After I turning on computer,  I figure out that all windows restore from last session.
Include the fact, that ddr must be clear each restarting. I have a doubt about security, cause if problem in ddr it possible to save my password there. Below I include the screenshot what's happen when system is starting.

**To Reproduce**
_1. Go to 'turn on computer'
_2. Open 2 different dirs
_3. Open terminal(also, it's save place, for example: from previous session: cd /sys/bus)
_4. Shutdown system
_5. Turning on
_6. Figure out that all windows restore from previous session. (not all, only a part(nautlius, terminal,veracrypt))

**Expected behavior**
I expected that it won't restore windows from previous session and all data on ddr will wrote with 0.

**Actual behavior**
A part of data(include path) was resotred.

**Screenshots**
![alt text](https://i.imgur.com/vXCMfNh.png "desc")​

**Solutions you've tried**
-
```
sync
echo 1 > /proc/sys/vm/drop_caches
reboot
```

**Comment by 0spinboson** [comment]
it's normal for dom0 open windows/apps to be reopened on login if you selected save state on logout/reboot.

**Comment by Aporbel** [comment]
> it's normal for dom0 open windows/apps to be reopened on login if you selected save state on logout/reboot.

Yes, but I don't have veracrypt or nautilus in session settings. Also, I think session settings spreading only to logout but not to off.

**Comment by marmarek** [comment]
This is exactly what @0spinboson said - this is saving session state. As for veracrypt, I'm pretty sure it registers itself to automatically start on boot.
