### ISSUE TITLE
Unable to Configure Qubes before Finishing Installation. Hangs on configuring TemplateVM

### ISSUE THREAD

**Issue by lambrou** [QubesOS/qubes-issues#5714]
### Qubes OS version:

R4.0.3

### Affected component(s) or functionality:

Installation

---

### Steps to reproduce the behavior:

Run qubes installer, reboot when prompted. Issues happens after rebooting.

### Expected or desired behavior:

Allow me to configure Qubes OS before finishing the installation.

### Actual behavior:
After following the steps on https://www.qubes-os.org/doc/uefi-troubleshooting/ to change the Xen configuration on USB media and removing the nomapbs and nofailboot flags, I install Qubes.
When I get prompted to restart, I follow the step:

> Use your preferred text editor (nano works) to edit /mnt/sysimage/boot/efi/EFI/qubes/xen.cfg

But xen.cfg is empty. I restarted and attempted to modify this path again, but this time there was no /mnt/sysimage folder at all.

I decided to continue with the install and booted into qubes. I got an error:

> Failed to load kernal modules. 

But it booted up anyway.
The installer said I needed to configure qubes before finishing the install. The install would hang on configuring templatevm. Sometimes it was the debian-10 and sometimes it would hang on configuring the whonix template.
I have tried multiple combinations of the configuration settings and none work. Most recently I chose to install none. This finally worked, but I was not able to configure anything on the installation screen.

### General notes:
Errors:
> Failed to load kernal modules
> /mnt/sysimage/boot/efi/EFI/qubes/xen.cfg is empty

Installation media:
16GB USB created by using dd in Ubuntu

Booting from a USB in Legacy mode.

Machine:
Dell Latitude E6420 (i7 proc version)
8GB RAM 250GB SSD

---

### I have consulted the following relevant [documentation](https://www.qubes-os.org/doc/):

https://www.qubes-os.org/doc/installation-guide/
https://www.qubes-os.org/doc/uefi-troubleshooting/

### I am aware of the following related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues:

https://github.com/QubesOS/qubes-issues/issues/5101
This issue is not relevant as the user said it was a visual issue and the installer actually completed. I let my laptop sit overnight while it was hanging on configuring templatevm and nothing ever happened. Upon rebooting, I am brought to the same 'Configure Qubes before Installing' screen unless I choose to configure nothing.

**Comment by rapenne-s** [comment]
Would you have the opportunity to check if you can reproduce this problem on R4.1?

**Comment by andrewdavidwong** [comment]
Could you try on R4.1 or R4.2 Release Candidate to see if the problem still exists?

**Comment by andrewdavidwong** [comment]
If anyone is still experiencing this problem on Qubes 4.1 or higher, please leave a comment here, and we'll be happy to reopen this.

**Comment by nopeitsnothing** [comment]
How long is it acceptable to have this hanging at "Installing TemplateVM debian-12-xfce"? It's been around 30 minutes. I'll run it for a few hours.
