### ISSUE TITLE
archlinux template: no response for 60 s

### ISSUE THREAD

**Issue by zaoqi** [QubesOS/qubes-issues#5718]
(I hit `enter` too early accidentally)
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
archlinux template

**Brief summary**
no response for 60s when installing

**To Reproduce**
_Steps to reproduce the behavior:_
_1. Create a new fedora-30 AppVM and build the template
_2. install it

**Actual behavior**
no response for 60s

**Screenshots**

**Additional context**

**Solutions you've tried**

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

**Comment by neowutran** [comment]
Do you have more details / logs ? ( if everything else fail, you can try to mount the lvm image to retrieve the logs https://www.qubes-os.org/doc/mount-lvm-image/ ) 

I just successfully built the "archlinux" and "archlinux-minimal" template and run "xterm" on them, so can't reproduce the issue

**Comment by zaoqi** [comment]
(I can't reproduce the issue anymore)
