### ISSUE TITLE
Huge virtd.log in dom0 leading to out of space in /tmp/ 

### ISSUE THREAD

**Issue by neowutran** [QubesOS/qubes-issues#5725]
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
Dom0 actions

**Brief summary**
/tmp/virtd.log file increase in size over time, fill all the space available in /tmp/, leading to crash of any dom0 tools requiring the use of /tmp/ (exemple: Qubes Backup / Restore, dom0 update / install ) 

**To Reproduce**
Install / uninstall template in dom0, use your computer for a lot of time...

**Expected behavior**
No crash, virtd.log keep a reasonable size compared to /tmp/ available space.

**Actual behavior**
"virtd.log" grow until it fill /tmp/ completly.
Additionnally, when a qubes template fail to be installed because of out of space in dom0, it cannot be uninstalled "easily" after. The out of space is indicated as a warning only, the template fail to be correctly installed, however, the package is counted as correctly installed. When you want to uninstall it, it try to delete the template (exemple: qubes-template-fedora-31 ), but it doesn't exist so the uninstall fail. You manually need to create a qube named "qubes-template-XXXXXX", and then run the uninstall to make it work. 

**Solutions you've tried**
Manually cleaning virtd.log work. 
Example: 
```bash
sudo su
echo "" > /tmp/virtd.log
```

Some kind of logrotate could be applied to this file to keep it's size reasonably low ?

**Comment by marmarek** [comment]
Isn't that some kind of very verbose debugging you have enabled? Standard installation doesn't have `/tmp/virtd.log` at all.

**Comment by neowutran** [comment]
Hmm, you are right. 
I probably enabled the most verbose output long ago when I was debugging some things, and forgot that it was not default. The parameter that I changed was "log_outputs" in /etc/libvirt/libvirtd.conf
