### ISSUE TITLE
Trusted PDFs do not print properly

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#5726]
**Qubes OS version**
`Qubes release 4.0 (R4.0)`

**Affected component(s) or functionality**
Qubes PDF convertor, and possibly qubes image convertor

**Brief summary**
Trusted PDFs do not print properly

**To Reproduce**

1. Convert a PDF to a Trusted PDF
2. Print the PDF using a USB printer
3. Look at the printed paper document
4. Notice that the document did not print properly.

**Expected behavior**
Trusted PDFs print correctly

**Actual behavior**
Trusted PDFs do not print correctly.  They seem stretched.

**Screenshots**
N/A

**Additional context**
I would like to convert PDFs before printing them to prevent a malicious PDF from compromising CUPS or my printer

**Solutions you've tried**
None

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
N/A

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
None

**Comment by marmarek** [comment]
What is the page size and the resolution? I think pdf converter preserve page size in pixels, but not necessary DPI.
