### ISSUE TITLE
Shut-down Animation confusing

### ISSUE THREAD

**Issue by ninavizz** [QubesOS/qubes-issues#5728]
As a new Qubes user who did not come into Qubes from Linux environments, it is confusing to me that the GUI things the machine does to shut-down, are identical to what I see the GUI doing upon boot. 

CAVEAT: This is a profoundly low priority "issue," in my mind—but is something I wanted to get onto the radar of things, should committing to making Qubes a more comfortable experience for non-Linux users, be elevated as a priority. If enough of these issues pile-up making an Epic for "Make Qubes mainstream friendly" shd maybe happen... but until then, ohai—just gonna leave this here.

**Comment by marmarta** [comment]
Gonna label this as far-in-the-future - I have no idea, to be honest, how would we even handle that at the moment.

**Comment by alimirjamali** [comment]
Development notes:
Current [Qubes Dark](https://github.com/QubesOS/qubes-artwork/tree/main/plymouth) plymouth splash animation source code & data.
Freedesktop [reference](https://github.com/QubesOS/qubes-artwork/tree/main/plymouth) on Plymouth programming.

Supported modes:  "boot", "shutdown", "suspend", "resume" or unknown.

**Comment by alimirjamali** [comment]
Further development notes:
The Freedesktop's document on Plymouth system state modes is outdated. The real software provides [more modes](https://gitlab.freedesktop.org/plymouth/plymouth/-/blob/main/src/client/plymouth.c?ref_type=heads&blame=0#L828-841). Having different Plymouth splash artwork for these modes are possible:

"boot-up", "shutdown", "reboot", "updates", "system-upgrade", "firmware-upgrade", "system-reset"
