### ISSUE TITLE
"Restart" as option in auth menu

### ISSUE THREAD

**Issue by ninavizz** [QubesOS/qubes-issues#5729]
## Problem
After running updates (or when my machine is buggy), I often want to reboot my machine. Currently, there is no "reboot" option in the user/auth menu (I click on my name next to the battery icon in the tray and the dropdown that is prompted). While it's entirely possible to sit there, wait for my laptop to shut down, then just press the boot button again—it's a bit of a drag, since a "Restart" menu option is common on Windows and Mac (and maybe on other Linux distros like Ubuntu, I dunno).

## Solution
It'd be nice for "Restart" to be added to this menu, just above "Shutdown."

**Comment by marmarek** [comment]
There is one: if you click logout.
I agree this standard Xfce menu is quite confusing here...

**Comment by marmarta** [comment]
This is a bigger problem with XFCE, not with Qubes tools themselves - I'm going to label it as far-in-the-future, because maintaining our own fork of  XFCE tools is infeasible, so there is no simple solution now that would allow us to fix it and not add a humongous amount of overhead, unfortunately.

**Comment by ninavizz** [comment]
@marmarek Rawwr!! `beats-head-on-wall`

@marmarta Wise call. Also: RAWRR!! ;)

**Comment by andrewdavidwong** [comment]
> There is one: if you click logout.
> I agree this standard Xfce menu is quite confusing here...

> This is a bigger problem with XFCE, not with Qubes tools themselves - I'm going to label it as far-in-the-future, because maintaining our own fork of XFCE tools is infeasible, so there is no simple solution now that would allow us to fix it and not add a humongous amount of overhead, unfortunately.

Closing as "not our bug." If you believe this is a mistake, please leave a comment, and we'll be happy to take another look. Thank you.
