### ISSUE TITLE
External HDMI monitor does not work with Intel Graphics

### ISSUE THREAD

**Issue by evilguc** [QubesOS/qubes-issues#5737]
**Qubes OS version**
* Qubes 4.0 current
* MSI GS65 Stealth Thin 8RE with Coffee Lake i7 (Intel UHD Graphics 630 + NVIDIA GeForce GTX 1060)
* Kernel Flags: i915.alpha_support=1 rd.blacklist.drivers=nouveau nouveau.modeset=0
* Bios:
    --UEFI/Legacy Boot: UEFI Only (same behavior for Legacy)
    --Secure Boot: Disabled

**Affected component(s) or functionality**
External Monitor
HDMI

**Brief summary**
External HDMI monitor doesn't work.

**To Reproduce**
1. Start Fresh install of Qubes 4.0
2. Connect HDMI external monitor

**Expected behavior**
Monitor is detected, display layout can be set up via xfce settings or xorg settings.

**Actual behavior**
When external HDMI monitor is connected `xfce4-display-settings --minimal` starts to fire each second, making impossible to work with a system and flooding screen with its instances.
Monitor sees no connection as well.

At the same time `xrandr` displays HDMI as disconnected all the time.

**Additional context**
* **nouveau** with my setup does not work at all - system freezes on boot screen
* `xfce4-display-settings --minimal` is triggered regardless of _"Configure new displays when connected"_ setting

**Solutions you've tried**
* laptop firmware is upgraded to latest version (after issue occurred)
* both LTS and `kernel-latest` are tried
* `video=HDMI-A-1:D` kernel flag - HDMI becomes connected in `xrandr` but other behavior stays the same
* leave monitor connected and turned on during boot

**Related issues**
Behavior is similar to described here: https://github.com/QubesOS/qubes-issues/issues/3897 but in my case firmware upgrade and fresh install of Qubes have no effect.

**Additional info**
Unfortunately I couldn't find how system reacts to monitor connection. `udevadm monitor`, `xorg` logs, `dmesg` in Dom0 don't have any sign of HDMI/monitor activity.

**Comment by evilguc** [comment]
Okay, according to this https://wiki.archlinux.org/index.php/MSI_GS65

> The HDMI and DP ports are wired to the Nvidia GPU

my issue couldn't be resolved the way I would like it to.

Since `nouveau` doesn't work I cannot use my DP and HDMI.

So either `nouveau` will start work with my hardware at some point in future (other linux distros seem to not have issues), or thunderbolt will work for me (need to get adapter to check this).


Still any more insight will be appreciated.

Thanks

**Comment by xaki23** [comment]
you could try updating the nouveau driver.
that requires some qubes-builder ritual dancing and isnt documented afaik, but is not actualy hard.

have you used qubes-builder before? or (re)compiled rpms?
if you are willing to try, hop on #qubes on irc.freenode.net and say hi!

**Comment by evilguc** [comment]
@xaki23 actually I managed to make it work just recently. Thank you for your feedback!

With no changes to any configuration enabled `nouveau` leads to an issue which looks like "bootscreen (the one with passphrase prompt for luks) freezes", but after some time system reboots itself.
Looking into `journal -b -1` gave following details:

```
Mar 22 18:16:39 dom0 kernel: ACPI Error: Aborting method \_SB.PCI0.PGON due to previous error (AE_AML_LOOP_TIMEOUT) (20191018/psparse-531)
Mar 22 18:16:39 dom0 kernel: ACPI Error: Aborting method \_SB.PCI0.PEG0.PG00._ON due to previous error (AE_AML_LOOP_TIMEOUT) (20191018/psparse-531)
Mar 22 18:16:39 dom0 kernel: acpi device:13: Failed to change power state to D0
Mar 22 18:16:41 dom0 kernel: video LNXVIDEO:01: Cannot transition to power state D0 for parent in (unknown)
Mar 22 18:16:41 dom0 kernel: nouveau 0000:01:00.0: can't change power state from D3cold to D0 (config space inaccessible)
Mar 22 18:16:41 dom0 kernel: video LNXVIDEO:01: Cannot transition to power state D0 for parent in (unknown)
Mar 22 18:16:41 dom0 kernel: nouveau 0000:01:00.0: can't change power state from D3cold to D0 (config space inaccessible)
Mar 22 18:16:41 dom0 kernel: video LNXVIDEO:01: Cannot transition to power state D0 for parent in (unknown)
Mar 22 18:16:41 dom0 kernel: nouveau 0000:01:00.0: can't change power state from D3hot to D0 (config space inaccessible)
Mar 22 18:16:41 dom0 kernel: nouveau 0000:01:00.0: tmr: stalled at ffffffffffffffff
```

Then I tried `nouveau.runpm=0` as a kernel argument and system booted successfully. `xrandr` displayed ports from both cards and I could connect external monitor.

For now it looks okay, will be monitoring. Can see some glitches when scrolling text in browser.

So summary for what exact changes were done:
1. `sudo qubes-dom0-update kernel-latest xorg-x11-drv-nouveau` 
not sure that's necessary, I just ended up with this when was trying to make things work
2. removed `nouveau.modeset=0 rd.driver.blacklist=nouveau video=vesa:off` from kernel args list
those were added during installation of qubes to disable `nouveau` completely and run intel graphics only
3. added `nouveau.runpm=0` to disable runtime power management for nvidia card
https://nouveau.freedesktop.org/wiki/KernelModuleParameters/

**Comment by andrewdavidwong** [comment]
@evilguc: If I understand correctly, you were able to resolve your own issue, which turned out not to have a Qubes-specific cause anyway. So, this should be closed, correct?

**Comment by evilguc** [comment]
@andrewdavidwong 
> turned out not to have a Qubes-specific cause

Yes, I think you can say so. More like xorg/video related issue.

I also notice there is no such issue with Xorg 1.20.x (ABI 24.0), it just works with no tweaking at all.
Is there any plans on upgrading xorg/video stack for Dom0?

Anyway, thank you for involvement.

**Comment by andrewdavidwong** [comment]
> Is there any plans on upgrading xorg/video stack for Dom0?

I imagine that this will get updated when dom0 gets updated to a newer Fedora release in Qubes 4.1 and higher.
