### ISSUE TITLE
Documentation regarding turning off SMT (HT) manually

### ISSUE THREAD

**Issue by JarrahG** [QubesOS/qubes-issues#5743]
**Qubes OS version**
R4.0. R4.1 is also affected.

**Affected component(s) or functionality**
Physical CPU cores are offlined when SMT is disabled. This results in a performance loss as half of the available CPU cores are not used.

**Brief summary**
When using a Ryzen Threadripper 2950X, Xen reports a single 8 core processor with 4 threads per core. This CPU is a 16 core processor with 2 threads per core.

**To Reproduce**
1. Enable SMT.
2. Run `xl info`
3. Note the `cores_per_socket` and `threads_per_core` lines.

**Expected behavior**
The following correct output from r4.0 should occur:
```
host                   : dom0
release                : 5.5.9-1.qubes.x86_64
version                : #1 SMP Sun Mar 15 07:00:08 CET 2020
machine                : x86_64
nr_cpus                : 32
max_cpu_id             : 127
nr_nodes               : 1
cores_per_socket       : 16
threads_per_core       : 2
```

**Actual behavior**
Half of the expected CPU cores are not reported. Each reported core has 4 threads.
```
host                   : dom0
release                : 5.5.9-1.qubes.x86_64
version                : #1 SMP Sun Mar 15 07:00:08 CET 2020
machine                : x86_64
nr_cpus                : 32
max_cpu_id             : 127
nr_nodes               : 1
cores_per_socket       : 8
threads_per_core       : 4
```

**Additional context**
This issue occurs with both SMT off (xen and bios) and on. However, with SMT off, half of the physical cores are not mapped at all. 

**Solutions you've tried**
Disabling SMT, upgrading to R4.1 and re-configuring the topology in BIOS.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
None found

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
https://github.com/QubesOS/qubes-issues/issues/5628 is potentially related as the CPU in question is a NUMA CPU.

**Comment by JarrahG** [comment]
Resolved from BIOS. I should have gone deeper the first time. Sorry for the unnecessary issue.

**Comment by xaki23** [comment]
could you please provide a brief summary of the BIOS changes required here anyways?
just for the next person who runs into the issue and finds this issue...

**Comment by JarrahG** [comment]
Evidently I closed this issue incorrectly. 
The BIOS change on my system actually has to be implemented from Ryzen Master in Windows, which is to set the memory access mode to local (meaning NUMA). There isn't a related setting in BIOS, but it does change the nvram/cpu config across boots/OS'.

Further testing today has shown that the error exists, but when this configuration is set, two NUMA nodes do show up. 

From the output below, it looks like Xen sees all CPUs on the second node to be threads on the CPUs of the first node. This results in the default Qubes configuration of `smt=off` disabling the threads. 

`xl info -n` (relevant parts)
```
nr_cpus                : 32
max_cpu_id             : 127
nr_nodes               : 2
cores_per_socket       : 8
threads_per_core       : 4
```
```
cpu_topology           :
cpu:    core    socket     node
  0:       0        0        0
  1:       0        0        0
  2:       1        0        0
  3:       1        0        0
  4:       2        0        0
  5:       2        0        0
  6:       3        0        0
  7:       3        0        0
  8:       4        0        0
  9:       4        0        0
 10:       5        0        0
 11:       5        0        0
 12:       6        0        0
 13:       6        0        0
 14:       7        0        0
 15:       7        0        0
 16:       0        0        1
 17:       0        0        1
 18:       1        0        1
 19:       1        0        1
 20:       2        0        1
 21:       2        0        1
 22:       3        0        1
 23:       3        0        1
 24:       4        0        1
 25:       4        0        1
 26:       5        0        1
 27:       5        0        1
 28:       6        0        1
 29:       6        0        1
 30:       7        0        1
 31:       7        0        1
```

This is with `smt=on` on the xen commandline. As you can see, CPU 0, 1, 16 and 17 are deemed to be on core 0. However, core 0 on node 1 is not differentiated from core 0 on node 0. This results in Xen reporting an SMT4 system and disabling the other 8 physical CPUs. 



@andrewdavidwong Sorry for the changes, but could you please remove the "not an issue" tag?

**Comment by 0spinboson** [comment]
this undoubtedly is a xen issue, but as such, shouldn't it go on the xen-users mailinglist? :)

**Comment by JarrahG** [comment]
> this undoubtedly is a xen issue, but as such, shouldn't it go on the xen-users mailinglist? :)

I've just sent that email off. Previously I'd only tested on Qubes OS.
But the same issue occurs on Debian on Xen. Thanks for the nudge in the
right direction.

**Comment by andrewdavidwong** [comment]
> this undoubtedly is a xen issue, but as such, shouldn't it go on the xen-users mailinglist? :)
> I've just sent that email off. Previously I'd only tested on Qubes OS. But the same issue occurs on Debian on Xen. Thanks for the nudge in the right direction.

Is there reason to think that there is a Qubes-specific bug here, or purely a Xen bug? If it's purely a Xen bug, we may want to close this as `nor our bug`.

**Comment by 0spinboson** [comment]
> 
> 
> > > this undoubtedly is a xen issue, but as such, shouldn't it go on the xen-users mailinglist? :)
> > 
> > 
> > I've just sent that email off. Previously I'd only tested on Qubes OS. But the same issue occurs on Debian on Xen. Thanks for the nudge in the right direction.
> 
> Is there reason to think that there is a Qubes-specific bug here, or purely a Xen bug? If it's purely a Xen bug, we may want to close this as `nor our bug`.

no, there's not.

**Comment by JarrahG** [comment]
Agreed. This affects multiple Xen versions on both Qubes and Debian. Not
a Qubes bug, though advice on reporting this to Xen would be
appreciated. I have received no response on Xen-users.

**Comment by iamahuman** [comment]
Related: #4456

**Comment by iamahuman** [comment]
I suppose it might be a good idea to convert this to a documentation task -- specifically, instruct users to turn off SMT (HT) manually (until Qubes R4.1 comes out).

**Comment by rapenne-s** [comment]
I think this can be closed, SMT is automatically disabled now.

**Comment by andrewdavidwong** [comment]
Closing as resolved. If anyone believes this issue is not yet resolved, or if anyone is still affected by this issue, please leave a comment, and we'll be happy to reopen it. Thank you.
