### ISSUE TITLE
Virtualization enable in BIOS but not recognized during installation (R4.0.3 on x220)

### ISSUE THREAD

**Issue by sucrecacao** [QubesOS/qubes-issues#5744]
**Qubes OS version**
R4.0.3

**Affected component(s) or functionality**
Installation from an USB stick

**Brief summary**
Qubes install say virtualization is not enable, yet it is enabled in the BIOS.

**To Reproduce**
on a thinkpad x220
1. burn R4.3 on a usb
2. enable virtualization in the BIOS
3. selection option "boot on UEFI only" in the BIOS
4. boot on the installation usb and see the error

**Expected behavior**
Installation process successfully

**Actual behavior**
Installation trigger a pop up saying that virtualization is not enabled and it would make qubes OS not work properly. It's possible to do the installation, but  qubes will not boot at startup.

**Additional context**
I installed qubes R4.0.0 or R4.0.1 on exactly the same hardware 2 years ago, and it worked perfectly fine so it should not come from the hardware.

**Solutions you've tried**
_If applicable, any solutions or workarounds you've already tried._

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

https://www.qubes-os.org/doc/thinkpad-troubleshooting/ But  it mentions other Thinkpad model.
https://www.qubes-os.org/doc/intel-igfx-troubleshooting/#iommu but need to have a terminal in dom0, and my installation doesn't boot.

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

https://github.com/QubesOS/qubes-issues/issues/4941, same as above.
https://github.com/QubesOS/qubes-issues/issues/2284 I got the same screen during install. But after a bit it come back to good resolution

**Comment by sucrecacao** [comment]
Tried to update BIOS to the latest version but it did not help

**Comment by sucrecacao** [comment]
on ubuntu `lscpu` give me 
```
...
Virtualization:      VT-x
...
```
But on Qubes dom0 , `lscpu` give me:
```
Virtualization:      none
```

**Comment by sucrecacao** [comment]
Solved !

So all 3 x220 in the HCL use the same CPU  and I wrongly assumes that my computer would also have the same one,  but I have a different one that doesn't support VT-d. 

The qubes issue not booting up was not related to that, I succeeded to do  the install after applying a thinkpad workaround. 
I just had to set `sys-net` and `sys-usb` to `PV` with the following command in dom0
`qvm-prefs sys-net virt_mode pv`
`qvm-prefs sys-usb virt_mode pv`

**Comment by andrewdavidwong** [comment]
I'm glad you were able to solve your issue, @sucrecacao!

I'll close this as resolved. If anyone subsequently has a reason for reopening this issue, please leave a comment. Thank you.
