### ISSUE TITLE
thunderbird "open in dispvm" and special attachment names

### ISSUE THREAD

**Issue by ThomasWaldmann** [QubesOS/qubes-issues#5750]
**Qubes OS version**

R4.0 + all updates

**Affected component(s) or functionality**

Attachment context menu "open in dispvm" in thunderbird.

**Brief summary**

I got an email with an attachment named like "test /1234/5678.pdf".

Clicking it or "open in dispvm" does nothing visible (although it works for other PDFs).

Note:
"save as" transforms the filename to "test -1234-5678.pdf" to get rid of the path separators.

**Solutions you've tried**

Of course, one can "save as", give it a less stupid filename and afterwards open via the file manager or "qvm-open-in-dvm".

**Comment by ThomasWaldmann** [comment]
@marmarek thanks for fixing this! did you intentionally choose a different transformation than "save as" uses?

**Comment by marmarek** [comment]
Not intentionally, I've accepted @MSathieu solution, which also is good.

**Comment by MSathieu** [comment]
I changed it to an underscore because that's the default when opening the attachment normally @ThomasWaldmann
