### ISSUE TITLE
Qube Starts but Applications will not Run

### ISSUE THREAD

**Issue by bomeisl** [QubesOS/qubes-issues#5751]
### Qubes OS version:

R4.0

### Affected component(s) or functionality:

Debian-10 template based qube

---

### Steps to reproduce the behavior:
Click the launch menu, scroll down to 'Domain: GPE' (the name of the qube in question) and click it. Then attempt to launch a terminal or any other application besides the Settings.

### Expected or desired behavior:

1) The application opens

2) Private storage is adjustable from Settings

### Actual behavior:

1) The application doesn't open

2) Private storage is not adjustable from the Settings application

### General notes:

The qube was working fine until recently (perhaps due to an update). When I attempt to open the terminal of the Debian-10 Domain: GPE by typing the command at the Dom0 terminal:
`sudo qvm-run GPE terminal` the following line is returned 'GPE: Command Failed with code 2`

Furthermore, private storage cannot be adjusted from the Settings of the GPE qube.

---

**Comment by andrewdavidwong** [comment]
What happens if you try `qvm-start GPE` and `qvm-run GPE xterm` from dom0?

**Comment by mfc** [comment]
I am facing (potentially) this same issue, also with Debian-10 based template and its qubes.

> What happens if you try `qvm-start GPE` and `qvm-run GPE xterm` from dom0?

it just says `running 'xterm' on domain` forever, doesn't timeout. when I escape the process there is no error printed.

this happens both for the template and for any qube based on the template. it only started with most recent updates from the last couple days.

the Qube Updates app seems to still work with checking for updates for the template, though there hasn't been any updates so not totally sure.

**Comment by mfc** [comment]
to update: I solved it by increasing Private Storage and System Storage of the _Debian-10-based template_ (increasing Private Storage of qube didn't help).

**Comment by andrewdavidwong** [comment]
> to update: I solved it by increasing Private Storage and System Storage of the _Debian-10-based template_ (increasing Private Storage of qube didn't help).

@bomeisl, does this also work for you?

**Comment by bomeisl** [comment]
I've tried that, unfortunately it doesn't resolve the issue.

**Comment by bluesteal** [comment]
Hello,

I am having a similar issue, but the output of "sudo qvm-run debian-10 terminal" is "Running 'terminal' on debian-10". But the terminal has not launched. when I try running the command with verbose logging, it returns the same output.

**Comment by mfc** [comment]
> Hello,
> 
> I am having a similar issue, but the output of "sudo qvm-run debian-10 terminal" is "Running 'terminal' on debian-10". But the terminal has not launched. when I try running the command with verbose logging, it returns the same output.

hey @bluesteal, have you seen my comments [here](https://github.com/QubesOS/qubes-issues/issues/5751#issuecomment-626384747) and [here](https://github.com/QubesOS/qubes-issues/issues/5751#issuecomment-626385243)? may work for you. 

since it didn't help OP maybe should be split into different issue.

**Comment by unman** [comment]
@bomeisl  Were you able to resolve this issue?
Do you still have that qube available?
