### ISSUE TITLE
Add section for Keybase interaction to Split GPG docs

### ISSUE THREAD

**Issue by jclement** [QubesOS/qubes-issues#5753]
**The problem you're addressing (if any)**
Getting Keybase to run under Split GPG is a bit of a pain because:
- Keybase doesn't make it obvious how to adjust it to call out to qubes-gpg-client
- Keybase service throws away environment variables (so doesn't haves access to QUBES_GPG_DOMAIN)

**Describe the solution you'd like**
I would like to add a brief section on working with Keybase to the Split GPG documentation.  Rough solution is:

Make a wrapper (/usr/bin/qubes-gpg-client-keybase):
```
#!/bin/bash
QUBES_GPG_DOMAIN=`cat /rw/config/gpg-split-domain` --sGPG /usr/bin/qubes-gpg-client "$@"

```
And then configure Keybase to use that wrapper:
keybase config set gpg.command /usr/bin/qubes-gpg-client-keybase

**Where is the value to a user, and who might that user be?**
This would be useful for anyone who is using Keybase under Qubes and would like GPG interaction.  The information is out there but scatter between various bug posts.

**Describe alternatives you've considered**
Modify the Keybase service to read /rw/config/gpg-split-domain so that we don't need another wrapper.

**Additional context**

Nothing

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

* https://www.qubes-os.org/doc/split-gpg/
* https://github.com/keybase/client/issues/14897

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

**Comment by marmarek** [comment]
The package ships similar wrapper already: qubes-gpg-client-wrapper

**Comment by jclement** [comment]
Well.... Thanks @marmarek  I'd missed what that was for.  That *just works*.  In any case, I think it might be worth a short section in the documentation mentioning how to configure Keybase to use that.  Thoughts?

**Comment by marmarek** [comment]
Yes, good idea.

**Comment by vrushti-mody** [comment]
I'd like to work on this issue

**Comment by andrewdavidwong** [comment]
> I'd like to work on this issue

Thank you. Please feel free to submit a PR for the short doc section @jclement mentioned (unless @jclement is already on it).


-----

In case you (or anyone else reading this) is not already aware, the documentation is a community effort, and everyone is welcome to contribute. (That's how things like this get updated!) So, if you'd like to get involved with the project, this is a great way to do it. You can read more about how to submit documentation changes here:

https://www.qubes-os.org/doc/doc-guidelines/

**Comment by jclement** [comment]
Hey guys.  This is already in and committed.  I guess I didn't close this properly.  My apologies!
