### ISSUE TITLE
Chromium snap often fails to start

### ISSUE THREAD

**Issue by greenrd** [QubesOS/qubes-issues#5757]
**Qubes OS version**
4.0

**Affected component(s) or functionality**
qubes-snapd-helper

**Brief summary**
I have chromium installed as a snap package, because the version in snap is newer than the Fedora version, and the Fedora version has a major bug. It fails to start increasingly often - today, I had to restart the AppVM about 5 times before it would run.

**To Reproduce**
It's non-deterministic so it might be necessary to do this a few times.
 1. Start AppVM
 2. Run a package installed via snap, such as chromium

**Expected behavior**
Chromium starts normally.

**Actual behavior**
Random error - file not found or something - and chromium fails to start and exits to the terminal. The error seems to be different each time I reboot the AppVM, although perhaps errors do repeat over the course of time.

**Additional context**
qubes-snapd-helper is installed. This problem seems to be occurring more frequently after recent TemplateVM package updates.

The same error repeats if I try re-running chromium without rebooting the AppVM.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
https://www.qubes-os.org/doc/software-update-domu/

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
https://github.com/QubesOS/qubes-issues/issues/5200

**Comment by maximilize** [comment]
When the app fails to start, please check the output of `snap list`. Does it show some `broken` packages?

If the broken package is for eg `core`, it helps to remove and reinstall it. This should fix the startup issue without rebooting the VM.
However, if you remove for eg chromium, you may loose some app related data.
