### ISSUE TITLE
Can't apply any gtk-icon-theme on 3rd party templates (ubuntu-desktop, for example)

### ISSUE THREAD

**Issue by ghost** [QubesOS/qubes-issues#5758]
**Qubes OS version**
4.0
![ubuntu-desktop](https://user-images.githubusercontent.com/60626673/78472965-bc128300-7745-11ea-9310-7ac2c7792a7a.png)

![ubuntu2](https://user-images.githubusercontent.com/60626673/78500769-166d0d00-7761-11ea-96ee-485116b357b1.png)
![ubuntu3](https://user-images.githubusercontent.com/60626673/78502667-e1fe4e80-776a-11ea-8919-968df4e118f6.png)

gnome-tweaks, gtk-settings.ini, gsettings, dconf, oomox, lxapperiance doesn't change anything.
why?
only if manually change it works

**Comment by SvenSemmler** [comment]
I share that observation for debian and ubuntu templates. However in case of fedora and whonix templates e.g. gnome-tweaks does work. Whether or not the gnome settings daemon runs might have something to do with it. 
On Ubuntu I ultimately had success via the GTK_THEME environment variable and using gsettings like this: gsettings set org.gnome.desktop.interface gtk-theme Breeze

**Comment by 0rb677** [comment]
@SvenSemmler thanks. On Archlinux it works too.
