### ISSUE TITLE
fedora-31-minimal [TESTING]: nothing provides python-daemon needed by qubes-core-agent-4.0.51-1.fc31.x86_64

### ISSUE THREAD

**Issue by Osndok** [QubesOS/qubes-issues#5759]
**Qubes OS version**
R4.0

template: fedora-31-minimal (in **TESTING** repo)

**Affected component(s) or functionality**
Unable to install `qubes-core-agent-networking` or `qubes-core-agent-network-manager` on minimal template to enable networking.

**Brief summary**
In Fedora 31, they deprecated python2, and in so doing they renamed all `python-*` packages `python2-*` (or something to that effect).

Thus, the RPM SPEC needs to be updated to identify either `python2-daemon` or `python3-daemon`, depending on the python version the agent is written in.

Also, this may be just one of several `python-*` package references that need to be changed.

**To Reproduce**
_1. Open a dom0 terminal
_2. Execute: `sudo qubes-dom0-update --enablerepo=qubes-templates-itl-testing qubes-template-fedora-31-minimal`
_3. Open a root terminal window therein: `qvm-run -u root fedora-31-minimal xterm`
_4. Execute: `dnf install qubes-core-agent-network-manager`
_5. See the error:

```
Last metadata expiration check: 0:22:31 ago on Sun Apr  5 12:36:08 2020.
Error: 
 Problem: conflicting requests
  - package qubes-core-agent-network-manager-4.0.50-1.fc31.x86_64 requires qubes-core-agent-networking = 4.0.50, but none of the providers can be installed
  - package qubes-core-agent-network-manager-4.0.51-1.fc31.x86_64 requires qubes-core-agent-networking = 4.0.51, but none of the providers can be installed
  - package qubes-core-agent-networking-4.0.50-1.fc31.x86_64 requires qubes-core-agent = 4.0.50, but none of the providers can be installed
  - package qubes-core-agent-networking-4.0.51-1.fc31.x86_64 requires qubes-core-agent = 4.0.51, but none of the providers can be installed
  - nothing provides python-daemon needed by qubes-core-agent-4.0.50-1.fc31.x86_64
  - nothing provides python-daemon needed by qubes-core-agent-4.0.51-1.fc31.x86_64
(try to add '--skip-broken' to skip uninstallable packages)
```

**Expected behavior**
The packages should install without error.

**Actual behavior**
The packages refuse to be installed because there is no longer a package named `python-daemon`.

**Screenshots**
...it would pretty much be a terminal window with the above text in it.

**Additional context**
_Add any other context about the problem here._

**Solutions you've tried**
None.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

* https://www.qubes-os.org/doc/templates/minimal/

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

* #5289
* #5297

**Comment by fepitre** [comment]
I think the problem is certainly due to python3 migration packages from time to time. I'll check that.

**Comment by fepitre** [comment]
I had no problem to install those components. Please enable current-testing repositories and update first. Templates need to be rebuilt with latest python3 migration packages.

**Comment by Osndok** [comment]
You know, it never occurred to me that I might need to enable & use the `testing` repo from within the `testing` image... that kind of makes sense.

**Comment by Osndok** [comment]
Obsolete/fixed.
