### ISSUE TITLE
SELinux relabel damages filesystem

### ISSUE THREAD

**Issue by robertfisk** [QubesOS/qubes-issues#5765]
**Qubes OS version**
Qubes R4.0

**Affected component(s) or functionality**
Fedora 30 template

**Brief summary**
I am attempting to enable SELinux in a Fedora 30 template. Following the instructions in [this issue](https://github.com/QubesOS/qubes-issues/issues/4239), I can successfully complete the filesystem relabel which takes a few minutes. After rebooting the template it never successfully boots again, getting stuck in emergency mode.

**To Reproduce**
1. Clone fedora 30 template
2. Install "selinux-policy-targeted" and dependencies
3. Edit /etc/selinux/config:
```
SELINUX=permissive
SELINUXTYPE=targeted
```
4. Set template's kernelopts to "nopat security=selinux selinux=1"
5. Set template's qrexec_timeout to 800
6. Boot template, wait for relabel process to complete on guest console
7. Boot template again

**Expected behavior**
Template boots up with SELinux in permissive mode.

**Actual behavior**
Template does not complete bootup. Guest console shows:

> (snip)
> Starting Journal Service...
> FAILED. Failed to mount /proc/xen.
> See 'systemctl status proc-xen.mount' for details.
> (snip)
> You are in emergency mode. After logging in, type "journalctl -xb" to view
> system logs, "systemctl reboot" to reboot, "systemctl default" or "exit"
> to boot into default mode.
> Press Enter for maintenance
> (or press Control-D to continue):

"systemctl status proc-xen.mount" returns (abbreviated):
> Loaded: loaded (/etc/fstab; generated)
> Active: failed
> Where: /proc/xen
> localhost mount[195]: mount: /proc/xen: unknown filesystem type.

**Solutions you've tried**
- Typing "systemctl default" or "exit" at the console loops back to emergency mode.
- Running "fixfiles relabel" seems to run for a few minutes, but does not fix the problem.
- Changing template kernelopts to "nopat security=selinux selinux=0" or "nopat" does not fix the problem.

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
https://github.com/QubesOS/qubes-issues/issues/4239

**Comment by marmarek** [comment]
>  localhost mount[195]: mount: /proc/xen: unknown filesystem type.

Custom kernel built with xenfs support disabled?

**Comment by robertfisk** [comment]
I'm running the default kernel:
```
# uname -r
4.19.107-1.pvops.qubes.x86_64
```
But you did give me an idea...
```
# cd /usr/lib/modules/4.19.107-1.pvops.qubes.x86_64
# tree
(snip)
6084 directories, 0 files
```
Aaah! Where did all my kernel modules go???

Clone a new Fedora 30 template and go through the process again. This time it didn't relabel the filesystem on bootup. I have no idea why not when it did yesterday. Anyway, SELinux is now enabled, yay!

```
$ sestatus
SELinux status:                 enabled
SELinuxfs mount:                /sys/fs/selinux
SELinux root directory:         /etc/selinux
Loaded policy name:             targeted
Current mode:                   permissive
Mode from config file:          permissive
Policy MLS status:              enabled
Policy deny_unknown status:     allowed
Memory protection checking:     actual (secure)
Max kernel policy version:      31
```
All good so far. What if I poke it?
```
$ sudo fixfiles relabel

    Files in the /tmp directory may be labeled incorrectly, this command
    can remove all files in /tmp.  If you choose to remove files from /tmp,
    a reboot will be required after completion.

    Do you wish to clean out the /tmp directory [N]? y
Cleaning out /tmp
Warning: Skipping the following R/O filesystems:
/sys/fs/cgroup
Relabeling / /dev /dev/hugepages /dev/mqueue /dev/pts /dev/shm /home /run /run/user/1000 /rw /sys /sys/fs/cgroup/blkio /sys/fs/cgroup/cpu,cpuacct /sys/fs/cgroup/cpuset /sys/fs/cgroup/devices /sys/fs/cgroup/freezer /sys/fs/cgroup/hugetlb /sys/fs/cgroup/memory /sys/fs/cgroup/net_cls,net_prio /sys/fs/cgroup/perf_event /sys/fs/cgroup/pids /sys/fs/cgroup/systemd /sys/fs/cgroup/unified /sys/fs/pstore /sys/kernel/debug /tmp /usr/lib/modules /usr/local
/ 100.0%
/dev 100.0%
/dev/hugepages 100.0%
Warning no default label for /dev/mqueue
/dev/mqueue 100.0%
/dev/pts 100.0%
/dev/shm 100.0%
/home 100.0%
/run 100.0%
/run/user/1000 100.0%
/rw 100.0%
/sys 100.0%
/sys/fs/cgroup/blkio 100.0%
/sys/fs/cgroup/cpu,cpuacct 100.0%
/sys/fs/cgroup/cpuset 100.0%
/sys/fs/cgroup/devices 100.0%
/sys/fs/cgroup/freezer 100.0%
/sys/fs/cgroup/hugetlb 100.0%
/sys/fs/cgroup/memory 100.0%
/sys/fs/cgroup/net_cls,net_prio 100.0%
/sys/fs/cgroup/perf_event 100.0%
/sys/fs/cgroup/pids 100.0%
/sys/fs/cgroup/systemd 100.0%
/sys/fs/cgroup/unified 100.0%
/sys/fs/pstore 100.0%
/sys/kernel/debug 100.0%
/tmp 100.0%
/usr/lib/modules 100.0%
/usr/local 100.0%

Cleaning up labels on /tmp
```
Check my modules are still there...
```
$ cd /usr/lib/modules/4.19.107-1.pvops.qubes.x86_64
$ tree
(snip)
6096 directories, 18671 files
```
All good so far. Reboot the template... Aaagh, emergency mode again!
```
You are in emergency mode. After logging in, type "journalctl -xb" to view
system logs, "systemctl reboot" to reboot, "systemctl default" or "exit"
to boot into default mode.
Press Enter for maintenance
(or press Control-D to continue):

# cd /usr/lib/modules/4.19.107-1.pvops.qubes.x86_64
# tree
(snip)
6084 directories, 0 files
```
**Somehow the fixfiles script deleted my modules on reboot???**

This is what "fixfiles check" reports about the modules folder, not sure if it's any help:
```
$ sudo fixfiles check
(snip)
Would relabel /usr/lib/modules/4.19.107-1.pvops.qubes.x86_64 from system_u:object_r:unlabeled_t:s0 to system_u:object_r:modules_object_t:s0
Would relabel /usr/lib/modules/4.19.107-1.pvops.qubes.x86_64/extra from system_u:object_r:unlabeled_t:s0 to system_u:object_r:modules_object_t:s0
Would relabel /usr/lib/modules/4.19.107-1.pvops.qubes.x86_64/build from system_u:object_r:unlabeled_t:s0 to system_u:object_r:modules_object_t:s0
Would relabel /usr/lib/modules/4.19.107-1.pvops.qubes.x86_64/build/virt from system_u:object_r:unlabeled_t:s0 to system_u:object_r:modules_object_t:s0
(snip)
```

**Comment by marmarek** [comment]
`/usr/lib/modules/4.19.107-1.pvops.qubes.x86_64` should be mounted from `/dev/xvdd`, which is read-only (there is actually overlay fs on top of /dev/xvdd). Maybe fixfiles is not happy about it?

**Comment by DemiMarie** [comment]
I suspect the overlayfs is the problem.  If we get rid of the overlayfs, and instead use a `seclabel` mount option, things should be fine.

**Comment by robertfisk** [comment]
I managed to work around this selinux issue a couple of months ago and haven't looked at it since then. However I can confirm that the issue still exists with a fresh Fedora 32 template.

Wrangling with overlayfs and seclabel options is currently beyond my experience, so I'll have to leave this issue for others to resolve.

**Comment by DemiMarie** [comment]
Changing labels and milestones as this was marked as “won’t fix” for R4.0.
