### ISSUE TITLE
qubes-windows-tools fails to format private disk to NTFS

### ISSUE THREAD

**Issue by lattice0** [QubesOS/qubes-issues#5768]
**Qubes OS version**
4.0.1

**Affected component(s) or functionality**
Windows Qubes

**Brief summary**
qubes-wiindows-tools installer fails to format the private disk and thus the user folder is not moved into the private disk. Then I think qrexec installation fails, because when I start the windows VM, it halts after 60 seconds saying it couldn't connect to qrexec. 
I don't know why, but I can only format the private disk using FAT or FAT32. NTFS wont work (windows could not format, something like that)

**To Reproduce**
_Steps to reproduce the behavior:_
_1. Install Windows 10
_2. start VM with qubes-windows-tools installer
_3. installation fails because couldn't format the disk, but the rest keeps installing

**Expected behavior**
No errors in the installaiton and private disk with my user in it, and no qrexec problems

**Comment by lucaszanella** [comment]
This is what happens when I try to format in the command prompt:

`format E: /fs:ntfs`

> Starting offset of the thinly provisioned or DAX partition is not aligned to a cluster boundary.
> Partition is 512 bytes aligned. To format with specified cluster size, align the partition to 4 KB.
> Format failed.

**Comment by marmarek** [comment]
I think this is already fixed in https://github.com/QubesOS/qubes-core-agent-windows/commit/0751e13dbf98bc3d52ec63acd36c64df6fb4a393, but there were no new builds since then (qubes-windows-tools currently lack active maintainer).

**Comment by GWeck** [comment]
A workaround may be not to specify the `Move user data` option during QWT installation, but to move the `C:\users\<username>\documents` folders manually after completing QWT installation. The completed Windows 10 system with QWT installed is then able to format disk `D:` with NTFS. At least, for me, it worked. Anyhow, moving user data from `C:` to another disk is crap in Windows 10.

See #5462 for details.
