### ISSUE TITLE
Arch Linux qube: missing qubes.db

### ISSUE THREAD

**Issue by scrouthtv** [QubesOS/qubes-issues#5769]
I am trying to install Arch Linux in a Qubes R4.0 using the guide over at https://www.qubes-os.org/doc/building-archlinux-template/ .

1. Some error occurs when trying to download the bootstrap tarball:
```
  --> Downloading Archlinux bootstrap tarball (v)...
--2020-04-12 14:56:12--  http://mirrors.kernel.org/archlinux/iso/latest/archlinux-bootstrap-2020.04.01-x86_64.tar.gz
Resolving mirrors.kernel.org (mirrors.kernel.org)... 149.20.37.36, 2001:19d0:306:6:0:1994:3:14
Connecting to mirrors.kernel.org (mirrors.kernel.org)|149.20.37.36|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: http://mirrors.edge.kernel.org/archlinux/iso/latest/archlinux-bootstrap-2020.04.01-x86_64.tar.gz [following]
--2020-04-12 14:56:13--  http://mirrors.edge.kernel.org/archlinux/iso/latest/archlinux-bootstrap-2020.04.01-x86_64.tar.gz
Resolving mirrors.edge.kernel.org (mirrors.edge.kernel.org)... 147.75.101.1, 2604:1380:2001:3900::1
Connecting to mirrors.edge.kernel.org (mirrors.edge.kernel.org)|147.75.101.1|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 165344016 (158M) [application/x-gzip]
```
And when trying to `make vmm-xen-vm` it is missing a `/tmp/qubes-packages-mirror-repo/pkgs/qubes.db` file:
```
  --> Configure sudo...
[multilib]
SigLevel = PackageRequired
Include = /etc/pacman.d/mirrorlist
[qubes]
SigLevel = Optional TrustAll
Server = file:///tmp/qubes-packages-mirror-repo/pkgs
--> Archlinux dist-prepare-chroot (makefile):
  --> Checking mounting of dev/proc/sys on build chroot...
    --> sudo mount -t proc proc /home/user/Downloads/qubes-builder/chroot-vm-archlinux/proc;
    --> sudo mount --bind /dev /home/user/Downloads/qubes-builder/chroot-vm-archlinux/dev;
    --> sudo mount --bind /dev/pts /home/user/Downloads/qubes-builder/chroot-vm-archlinux/dev/pts;
    --> sudo mount --bind /sys /home/user/Downloads/qubes-builder/chroot-vm-archlinux/sys;
    --> sudo mount --bind /home/user/Downloads/qubes-builder/cache/archlinux/pacman_cache /home/user/Downloads/qubes-builder/chroot-vm-archlinux/var/cache/pacman;
    --> sudo mount --bind /home/user/Downloads/qubes-builder/qubes-packages-mirror-repo/vm-archlinux /home/user/Downloads/qubes-builder/chroot-vm-archlinux/tmp/qubes-deb;
  --> Synchronize resolv.conf, in case it changed since last run...
-> Building vmm-xen (archlinux) for archlinux vm (logfile: build-logs/vmm-xen-vm-archlinux.log)
--> build failed!
--> Archlinux dist-build-dep (makefile)
-> Archlinux update-local-repo.sh
  -> Repo '/home/user/Downloads/qubes-builder/qubes-packages-mirror-repo/vm-archlinux/pkgs' appears empty; initialising with pacman itself...
cp: cannot stat '/home/user/Downloads/qubes-builder/chroot-vm-archlinux/var/cache/pacman/pkg/pacman*.pkg.tar.xz': No such file or directory
cp: cannot stat '/home/user/Downloads/qubes-builder/chroot-vm-archlinux/var/cache/pacman/pkg/sudo*.pkg.tar.xz': No such file or directory
cp: cannot stat '/home/user/Downloads/qubes-builder/cache/archlinux/pacman_cache/pkg/pacman*.pkg.tar.xz': No such file or directory
cp: cannot stat '/home/user/Downloads/qubes-builder/cache/archlinux/pacman_cache/pkg/sudo*.pkg.tar.xz': No such file or directory
ls: cannot access '*.sig': No such file or directory
ls: cannot access 'pkgs/*.pkg.tar.xz': No such file or directory
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
downloading multilib.db...
error: failed retrieving file 'qubes.db' from disk : Couldn't open file /tmp/qubes-packages-mirror-repo/pkgs/qubes.db
error: failed to update qubes (download library error)
error: failed to synchronize all databases
make[2]: *** [/home/user/Downloads/qubes-builder/qubes-src/builder-archlinux/Makefile.archlinux:114: dist-build-dep] Error 1
make[1]: *** [Makefile.generic:191: packages] Error 1
make: *** [Makefile:227: vmm-xen-vm] Error 1
```

**Affected component(s) or functionality**
qubes-builder / Archlinux

**Brief summary**
The installation guide for Arch refers to a qubes.db file that is missing.

**To Reproduce**
_Steps to reproduce the behavior:_
1. Go to https://www.qubes-os.org/doc/building-archlinux-template/
2. Follow the guide until `make vmm-xen-vm`
3. See error

**Solutions you've tried**
I already tried selecting `current` in this dialog:
![image](https://user-images.githubusercontent.com/23227405/79070592-ccd77180-7cce-11ea-9bf2-2f10e9cb24ed.png)
Did not work either.

I **don't** think this issue is related to #2565

**Comment by scrouthtv** [comment]
However if I change `./chroot-vm-archlinux/etc/pacman.conf` to not include
```
[qubes]
SigLevel = Optional TrustAll
Server = file:///tmp/qubes-packages-mirror-repo/pkgs
```
the `make vmm-xen-vm` works perfectly fine. Is the `qubes.db` outdated? There is no such folder in `/tmp/`, only `qubes-session-env` and `qubes-session-waiter`.
Do I even need the qubes repo? I read somewhere that the arch repo is not active anymore.

**Comment by marmarek** [comment]
This is repository for handling dependencies between packages you built locally. `make vmm-xen-vm` will work without it, as it doesn't depend on other qubes-specific packages, but most other packages will depend (directly or indirectly) on xen libs, and this is the repository where `make vmm-xen-vm` puts its results. In short: you need it to build the template.

The directory path is relative to chroot-archlinux directory and it is actually bind-mounted qubes-builder/qubes-packages-mirror-repo/archlinux`. The issue is here:


> Repo '/home/user/Downloads/qubes-builder/qubes-packages-mirror-repo/vm-archlinux/pkgs' appears empty; initialising with pacman itself...
> cp: cannot stat '/home/user/Downloads/qubes-builder/chroot-vm-archlinux/var/cache/pacman/pkg/pacman*.pkg.tar.xz': No such file or directory
> cp: cannot stat '/home/user/Downloads/qubes-builder/chroot-vm-archlinux/var/cache/pacman/pkg/sudo*.pkg.tar.xz': No such file or directory
> cp: cannot stat '/home/user/Downloads/qubes-builder/cache/archlinux/pacman_cache/pkg/pacman*.pkg.tar.xz': No such file or directory
> cp: cannot stat '/home/user/Downloads/qubes-builder/cache/archlinux/pacman_cache/pkg/sudo*.pkg.tar.xz': No such file or directory
> ls: cannot access '*.sig': No such file or directory
> ls: cannot access 'pkgs/*.pkg.tar.xz': No such file or directory

This step creates qubes.db, but it needs _some_ package to be there. Since `vmm-xen` is the first one to build (so it is empty initially), it tries to find something else - `pacman` and `sudo`, but apparently some path in Archlinux has changed.

How to fix it: find where some package (pacman is IMO a good example) is stored and adjust path to it in https://github.com/QubesOS/qubes-builder-archlinux/blob/master/update-local-repo.sh

**Comment by scrouthtv** [comment]
Okay I'll look into it later

**Comment by scrouthtv** [comment]
There is no package cache:
```
[user@personal chroot-vm-archlinux]$ pwd
/home/user/Downloads/qubes-builder/chroot-vm-archlinux
[user@personal chroot-vm-archlinux]$ sudo find | grep pkg.tar.xz
[user@personal chroot-vm-archlinux]$ 
```

**Comment by scrouthtv** [comment]
https://www.archlinux.org/news/now-using-zstandard-instead-of-xz-for-package-compression/

> As announced on the mailing list, on Friday, Dec 27 2019, our package compression scheme has changed from xz (.pkg.tar.xz) to zstd (.pkg.tar.zst).
> As a packager, you will automatically start building .pkg.tar.zst packages if you are using the latest version of devtools (>= 20191227).

**Comment by scrouthtv** [comment]
@marmarek I now changed `update-local-repo.sh` to copy `pacman*.pkg.tar.*` and `sudo*.pkg.tar.*` (since we don't know whether the developer who maintains `pacman` and `sudo` actually updated `devtools` to `>= 20191227`.
I suppose I have to change `update-remote-repo.sh`
 - `*.pkg.tar.xz` to `*.pkg.tar.*` (line 10)
 - `pkgs/qubes*.pkg.tar.xz` to `pkgs/qubes*.pkg.tar.*` (line 20)
_Is this correct?_

**Comment by marmarek** [comment]
I think so. There may be more places - do similar changes in `Makefile.archlinux` too. Not sure if all of them are strictly necessary, but some most likely are.

**Comment by scrouthtv** [comment]
Well actually line 10 is copying files from `qubes-builder/qubes-packages-mirror-repo/vm-archlinux/pkgs` which actually is a submodule:
```
[user@personal qubes-builder]$ ls qubes-packages-mirror-repo/ -all
total 16
drwxrwxr-x  2 user user 4096 Apr 12 22:11 .
drwxrwxr-x 16 user user 4096 Apr 12 22:14 ..
-rw-rw-r--  1 user user    3 Apr 12 22:11 .gitignore
-rw-rw-r--  1 user user  226 Apr 12 22:11 README
[user@personal qubes-builder]$ cat qubes-packages-mirror-repo/README 
RPM packages in this repo are hard links to the actual RPMs located in
qubes-src/*/pkgs/ directories that have been most recently built. They
might be used by other components in their build processes (e.g. *-devel
packages).
```
So I guess in this directory are no arch packages but rather rpm packages?
Also line 20 refers to the `qubes*.pkg.tar.xz` so I guess this isn't relevant either?

Who maintains the arch builder these days?

**Comment by scrouthtv** [comment]
```
[user@personal qubes-builder]$ grep -Fre *.pkg.tar.xz . 
./qubes-src/builder-archlinux/Makefile.archlinux:	@sudo rm "$(CACHEDIR)/pacman_cache/pkg"/qubes-*.pkg.tar.xz 2>/dev/null || true
./qubes-src/builder-archlinux/Makefile.archlinux:		for pkg in $$arch_chroot_dir/*.pkg.tar.xz; do\
./qubes-src/builder-archlinux/Makefile.archlinux:		ln -f -t $(BUILDER_REPO_DIR)/pkgs $$arch_chroot_dir/*.pkg.tar.xz;\
./qubes-src/builder-archlinux/Makefile.archlinux:	mv -t $$arch_pkg_dir $$arch_chroot_dir/*.pkg.tar.xz
./qubes-src/builder-archlinux/Makefile.archlinux:	    ln -f $(ORIG_SRC)/pkgs/$$pkgname-*.pkg.tar.xz $(UPDATE_REPO)/pkgs/;\
./qubes-src/builder-archlinux/Makefile.archlinux:	for filename in pkgs/*.pkg.tar.xz ; do
./qubes-src/builder-archlinux/update-remote-repo.sh:for filename in $package_directory/*.pkg.tar.xz ; do
./qubes-src/builder-archlinux/update-remote-repo.sh:sudo chroot chroot-$name su user -c 'cd /tmp/qubes-packages-mirror-repo; for pkg in `ls -v pkgs/qubes*.pkg.tar.xz` ; do repo-add pkgs/'"$db"'.tar.gz "$pkg";done;'
./qubes-src/builder-archlinux/scripts/04_install_qubes.sh:    'cd /tmp/qubes-packages-mirror-repo; for pkg in `ls -v pkgs/*.pkg.tar.xz`; do repo-add pkgs/qubes.db.tar.gz "$pkg"; done;'
./qubes-src/builder-archlinux/scripts/04_install_qubes.sh:    "cp /tmp/qubes-packages-mirror-repo/pkgs/qubes-vm-keyring*.pkg.tar.xz /etc/pacman.d/"
./qubes-src/builder-archlinux/scripts/arch-chroot-lite:        rm "$PACMAN_CACHE_DIR/pkg"/qubes-*.pkg.tar.xz 2>/dev/null || true
```

**Comment by scrouthtv** [comment]
I don't know what to do this line:
`./qubes-src/builder-archlinux/Makefile.archlinux`:
```
151 # Copies requested packages (based on PACKAGE_SET, COMPONENT, DIST) to
  1 # requested repository (UPDATE_REPO)
  2 update-repo:
  3 ifndef UPDATE_REPO
  4   $(error "You need to specify destination repo in UPDATE_REPO variable")
  5 endif
  6   mkdir -p $(UPDATE_REPO)/pkgs
  7   for arch_build_dir in $(ARCH_BUILD_DIRS); do\
  8     pkgnames=`cat $(ORIG_SRC)/$$arch_build_dir/PKGBUILD | grep pkgname | cut -d "=" -f 2 | tr -d '()"'`;\
  9     for pkgname in $$pkgnames; do\
 10       ln -f $(ORIG_SRC)/pkgs/$$pkgname-*.pkg.tar.xz $(UPDATE_REPO)/pkgs/;\
 11     done;\
 12   done;\
 13 
```
Line 151+10. Just copy it and replace `xz` with `zst`? Or replace `xz` with `*`?

**Comment by marmarek** [comment]
Try replacing with `*`.

**Comment by scrouthtv** [comment]
Changed it. Trying now
[patch.txt](https://github.com/QubesOS/qubes-issues/files/4467228/patch.txt)

**Comment by scrouthtv** [comment]
`make vmm-xen-vm worked so far`

**Comment by scrouthtv** [comment]
Everything works until `make template`:
```
mkdir -p /home/user/a/qubes-builder/qubes-src/linux-template-builder/pkgs-for-template/archlinux/pkgs
for arch_build_dir in archlinux; do\
  pkgnames=`cat qubes-src/app-linux-split-gpg/$arch_build_dir/PKGBUILD | grep pkgname | cut -d "=" -f 2 | tr -d '()"'`;\
  for pkgname in $pkgnames; do\
    ln -f qubes-src/app-linux-split-gpg/pkgs/$pkgname-*.pkg.tar.* /home/user/a/qubes-builder/qubes-src/linux-template-builder/pkgs-for-template/archlinux/pkgs/;\
  done;\
done;\

ln: failed to access 'qubes-src/app-linux-split-gpg/pkgs/qubes-gpg-split-*.pkg.tar.*': No such file or directory
make[1]: *** [/home/user/a/qubes-builder/qubes-src/builder-archlinux/Makefile.archlinux:153: update-repo] Error 1
make: *** [Makefile:320: template-local-archlinux] Error 1
```
The other packages / folders / whatever earlier (`qubes-src/builder-archlinux`, `qubes-src/vmm-xen`, ..., `qubes-src/gui-agent-linux`) worked out well, however there is **no** `pkgs/` folder in `qubes-src/app-linux-split/gpg/`:
```
[user@personal qubes-builder]$ ls qubes-src/app-linux-split-gpg/
.git/                       archlinux/                  qubes-gpg.sh                src/
.gitignore                  debian/                     qubes.Gpg.policy            tests/
.travis.yml                 doc/                        qubes.Gpg.service           version
Makefile                    gpg-client-wrapper          qubes.GpgImportKey.policy   
Makefile.builder            gpg-import-key              qubes.GpgImportKey.service  
README.md                   qubes-gpg-split.tmpfiles    rpm_spec/                   
```
(see https://pastebin.com/LxJR66xu)

**Comment by scrouthtv** [comment]
I guess the instructions are missing a `make app-linux-split-gpg-vm`?

**Comment by scrouthtv** [comment]
`make qubes-vm` actually includes building `app-linux-split-gpg`. The doc is definitely missing this part.

**Comment by andrewdavidwong** [comment]
In case you (or anyone else reading this) is not already aware, the documentation is a community effort, and everyone is welcome to contribute. (That's how things like this get updated!) So, if you'd like to get involved with the project, this is a great way to do it. You can read more about how to submit documentation changes here:

https://www.qubes-os.org/doc/doc-guidelines/

**Comment by scrouthtv** [comment]
@andrewdavidwong https://github.com/QubesOS/qubes-doc/pull/976 done.

**Comment by scrouthtv** [comment]
I'll post the fix once more https://github.com/QubesOS/qubes-builder-archlinux/files/4467439/zst-fix.txt and close this issue since it's fixed (for me).
