### ISSUE TITLE
Cannot start multiple VMs or multiple programs in a VM quickly, VMs randomly halt

### ISSUE THREAD

**Issue by unsigned-nerd** [QubesOS/qubes-issues#5770]
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
VMs or dom0 halt unexpectedly

**Brief summary**
If start multiple VMs, or when within a running VM, multiple programs within a short period of time (e.g., using a shell script which can start everything within a few minutes), random VMs or dom0 will unexpectedly halt which cause some files to corrupt

**To Reproduce**
1. Open multiple VMs from a shell script in dom0 or open multiple programs from a shell script in an already running VM

2. That VM might halt or the machine might hang or sometimes reboot

**Expected behavior**

All the VMs and apps can be started by using shell scripts within a short period of time (few minutes)

**Actual behavior**

Some VMs halt, sometimes machine hangs

**Solutions you've tried**

If the machine hangs, /var/lib/qubes/qubes.xml might be corrupted, fix it by using the file inside /var/lib/qubes/backup/.

If the machine cannot boot up, repairing the partition using lvm.

The partition error occurred to me only once.

The corrupted qubes.xml occured to me only two times.

> I have a workaround.  I just have to open each VM, one at a time until all the VMs I need are all up.  Then, within each VM, open each program I need, one at a time until all the programs I need are all up.  By doing this, I can run any number of VMs and programs simultaneously smoothly.

^^^ 20200413, This is wrong.  Today (20200413), even if I tried to open each VM and program slowly, random VM still halted randomly.  Unstable behavior.

Moreover, I had been running Qubes OS on this machine for a few weeks without problem until this week.

Some times:

- I ran a VM, then I opened Thunderbird, VM halted
- I opened a disposable VM, that disposable VM halted

Here is the error message from /var/log/qubes/qubes.log when the disposable VM halted before it even showed up when I started it:

```
2020-04-13 21:51:05,660 Creating directory: /var/lib/qubes/appvms/disp3990
2020-04-13 21:51:05,674 Creating icon symlink: /var/lib/qubes/appvms/disp3990/icon.png -> /usr/share/icons/hicolor/128x128/devices/appvm-red.png
2020-04-13 21:51:05,961 Starting disp3990
2020-04-13 21:51:07,572 Setting Qubes DB info for the VM
2020-04-13 21:51:07,573 Starting Qubes DB
2020-04-13 21:51:07,602 Activating the disp3990 VM
2020-04-13 21:51:15,901 permission denied for call b'admin.vm.volume.Info'+b'private' (b'dom0' → b'disp3990') with payload of 0 bytes
2020-04-13 21:51:16,064 Removing volume volatile: qubes_dom0/vm-disp3990-volatile
2020-04-13 21:51:16,064 Removing volume root: qubes_dom0/vm-disp3990-root
2020-04-13 21:51:16,064 Removing volume private: qubes_dom0/vm-disp3990-private
2020-04-13 21:51:16,064 Removing volume kernel: 4.19.107-1
2020-04-13 21:52:11,474 permission denied for call b'admin.vm.Kill'+b'' (b'dom0' → b'disp3990') with payload of 0 bytes
```

Hardware specs:
- Dell Precision 5540
- CPU: Intel Xeon E-2276M
- RAM: 64GB, 2x32GB, DDR4 2666MHz Non-ECC Memory
- Disk: 1 M.2 1TB PCIe NVMe Class 40 SSD
- Graphics card: Nvidia Quadro T1000 w/4GB GDDR5

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
-  [issue 2666](https://github.com/QubesOS/qubes-issues/issues/2666)

**Comment by andrewdavidwong** [comment]
Can you provide an example of the kind of shell script you're using to start multiple VMs and programs quickly? That might provide a clue to the devs of what's going wrong.

**Comment by unsigned-nerd** [comment]
> Can you provide an example of the kind of shell script you're using to start multiple VMs and programs quickly? That might provide a clue to the devs of what's going wrong.

In dom0:
```

#!/bin/bash

setxkbmap -option ctrl:swapcaps
ln-gnome-terminal $v; sleep 30
ln-gnome-terminal $c; sleep 30
ln-gnome-terminal $r; sleep 30
ln-gnome-terminal $i; sleep 30
ln-dvm-xterm &
sleep 30
ln-dvm-xterm &
sleep 30
ln-gnome-terminal borg; sleep 30
/home/user/bin/ln-backup-block-attach; sleep 10
/home/user/bin/ln-screen-vpn
```

In a VM:
```

#!/usr/bin/zsh                                                           

screen -dm -S m
screen -dm -S t
sleep 5

screen -S m -p 0 -X stuff "ln-startthunderbird\n"
sleep 30
screen -S m -p 0 -X stuff "ln-backup-mount\n"

screen -S t -p 0 -X stuff "cd todo; vi todo done/2018.1\n"

screen -S t -X screen

screen -S t -p 1 -X stuff "vi daily-loop\n"

screen -dr m
```

Note that I found out today that even if I opened each VM and program slowly, the problem still occurred.

I am now migrating the VMs to my old machine, also Qubes OS R4.0.  And, I will try reinstalling Qubes OS on this machine again to see if that helps with better log of what I do.  (My old machine runs Qubes OS smoothly without any issue for a year or so.)

**Comment by unsigned-nerd** [comment]
Today, when I tried to install QubesOS again, I ran a hardware check on my laptop and found an error like this:

Dell SupportAssist has detected a failing component on your system ...
Critical Error Message
...
Memory errors detected.  Limit exceeded. ...

I guess my brand new laptop is faulty.  Let's close this ticket.
