### ISSUE TITLE
i3-gaps

### ISSUE THREAD

**Issue by w1k1n9cc** [QubesOS/qubes-issues#5774]
**The problem you're addressing (if any)**
That's not really a problem. But I like the look of the [i3-gaps](https://github.com/Airblader/i3) project. Now that I use it, I think that the borders are better visible. For me it's easier to see to what qube a terminal belongs.

**Describe the solution you'd like**
I ported the patches for i3 to i3-gaps and extended it with an additional patch. I used [this repo](https://github.com/unendingPattern/i3-gaps-qubes).

**Where is the value to a user, and who might that user be?**
This add support for gaps and has the same features as i3.

**Additional context**
I already did the whole work and it works with i3 4.17.1. The code from 4.18 isn't much different so it also should work with that version and so for qubes 4.1.
Only a few modifications of the spec file and a small additional patch are necessary. But the question is how should I add it. I can fork the repo but the code overlaps a lot with [qubes-dekstop-linux-i3](https://github.com/QubesOS/qubes-desktop-linux-i3/tree/master). Maybe i3 could be replaced because it's from one of the maintainer from i3 and has the same features plus some nice additional ones.
It would also be great if we can backport 4.17.1 to Qubes 4.0. The colors are much better and for me it's running without problems.

**Comment by MrCapsLock** [comment]
Hi, I will follow this issue, I like to have i3-gaps on my Qubes, specially on newest release and I will prefer it officially. Thanks for opening this issue.

**Comment by andrewdavidwong** [comment]
> But the question is how should I add it. I can fork the repo but the code overlaps a lot with qubes-dekstop-linux-i3. Maybe i3 could be replaced because it's from one of the maintainer from i3 and has the same features plus some nice additional ones.

@marmarek, do you have an opinion about this?

**Comment by fepitre** [comment]
@marmarek: a solution could be to ship the whole package using QubesOS-contrib. Subpackage can be a good solution but If I understand correctly, it means having two sources? Then, it means complicating the spec file with respect to upstream.

**Comment by marmarek** [comment]
Yes, good idea @fepitre

**Comment by w1k1n9cc** [comment]
@fepitre: Yes, the sources are different. I can take a look how to solve it. But maybe it would be easier to fork the repo to QubesOS-contrib and then the changes that are made to original i3 can be merged to i3-gaps. That should be an easy and clear solution with git.

(P.S.: How can I install contrib packages?)

**Comment by fepitre** [comment]
Ok I'll manage to do it this weekend.

**Comment by fepitre** [comment]
> @fepitre: Yes, the sources are different. I can take a look how to solve it. But maybe it would be easier to fork the repo to QubesOS-contrib and then the changes that are made to original i3 can be merged to i3-gaps. That should be an easy and clear solution with git.
> 
> (P.S.: How can I install contrib packages?)

@marmarek should do an announcement soon for it :) But it's simply for dom0 packages: `qubes-dom0-update qubes-contrib-repo`. For template packages it's the same name too. Please note currently all the packages provided are testing.

**Comment by w1k1n9cc** [comment]
Great and thank you. If you have created the repo in contrib I will make a pull-request with the necessary changes.

**Comment by w1k1n9cc** [comment]
@fepitre: Little reminder?

**Comment by fepitre** [comment]
Its on my TODO list. Not on top yet...

**Comment by fepitre** [comment]
Build is in progress: https://github.com/QubesOS-contrib/updates-status/issues/22. Packages will appear progressively.

**Comment by fepitre** [comment]
@andrewdavidwong: as packages are now built and available on QubesOS-contrib, should we close this one and if any, open another one?

**Comment by andrewdavidwong** [comment]
> @andrewdavidwong: as packages are now built and available on QubesOS-contrib, should we close this one and if any, open another one?

Yes, sounds good.
