### ISSUE TITLE
i3: border color inverted

### ISSUE THREAD

**Issue by w1k1n9cc** [QubesOS/qubes-issues#5775]
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
Single window in i3

**Brief summary**
The color of the right border is inverted for horizontal split mode and the color of the bottom border for vertical split mode if only a single window is open. So don't know if this is a bug or a feature

**To Reproduce**
_1. Start i3
_2. Open an application (e.g. Alt+Enter for a terminal)
_3. Look at the color of right border 

**Expected behavior**
Right or bottom border should have the same color as the other borders.

**Actual behavior**
Right or bottom border has inverted color.

**Screenshots**
***inverted border color***
![2020-04-15-230135](https://user-images.githubusercontent.com/17565892/79388214-3c6a8c80-7f6d-11ea-9fa6-43c829048f7c.png)
***correct border colors***
![2020-04-15-230212](https://user-images.githubusercontent.com/17565892/79388217-3d032300-7f6d-11ea-9b38-b2190db5084e.png)

**Solutions you've tried**
Tried i3 4.16 and i3-gaps 4.17.1.

**Comment by fepitre** [comment]
Are you using official Qubes package? i3 is my primary Qubes desktop for months and I don't reproduce such trouble in R4.0 or R4.1.

**Comment by w1k1n9cc** [comment]
I have this "issue" with the i3 version 4.16-9 from qubes and also with me own created i3-gaps version 4.17.1. This appears with the default and my own config. So, maybe not i3 is the problem. But it happens with every program.

**Comment by fepitre** [comment]
I would rather think it's a config issue. I don't reproduce it with default i3 config.

**Comment by w1k1n9cc** [comment]
I used i3 for years now but most of the time with another os. Since one or two years I use qubes now and colors become important. Previously colors are only some nice accessory. Now they make a big difference.
On [reddit](https://www.reddit.com/r/i3wm/comments/4yq7m7/can_someone_help_me_with_my_borderindicator/) another user has the same issue with standard i3. So I look in the [docs](https://github.com/i3/i3/blob/4.16.1/docs/userguide):
> The indicator color is used for indicating where a new window will be opened.
For horizontal split containers, the right border will be painted in indicator
color, for vertical split containers, the bottom border. This only applies to
single windows within a split container, which are otherwise indistinguishable
from single windows outside of a split container.
This is a desired behaviour.

I think qubes has this configured too if we look in the standard [template](https://github.com/QubesOS/qubes-desktop-linux-i3/blob/release4.0/i3-settings-qubes/i3.config.keycodes) for the i3 configuration and also in the [unconfigured](https://github.com/QubesOS/qubes-desktop-linux-i3/blob/release4.0/i3/0001-Show-qubes-domain-in-configurable-colored-borders.patch) state (Last column should be indicator color).
