### ISSUE TITLE
setting windows10 qrexec feature to 0 wont make qubes stop using it 

### ISSUE THREAD

**Issue by lucaszanella** [QubesOS/qubes-issues#5776]
**Qubes OS version**
4.0.1

**Affected component(s) or functionality**
HVM qrexec

**Brief summary**
After installing qubes-windows-tools, it failed on moving the users folder to the D disk. I followed a guide: https://www.tenforums.com/tutorials/1964-move-users-folder-location-windows-10-a.html but after doing it, it reboots. Upon startup, the windows keeps loding (possibly moving the folder, I don't know). Then, since it wont start in less than 60 seconds, Qubes closes it by saying 60 seconds has passed and it couldn't communicate with qrexec. Sometimes it happens even if the windows is up, I guess the windows qrexec fils to load sometimes.

Anyways, setting it to 0 by doing

```
qvm-features windows10 qrexec 0
```

has no effect

**Comment by marmarek** [comment]
This is because `0` is not the correct value to disable it. Either remove it (`-D` option) or set to empty value (`""`)
