### ISSUE TITLE
Confusing interaction between xsel and qubes clipboard

### ISSUE THREAD

**Issue by cryslith** [QubesOS/qubes-issues#5781]
**Qubes OS version**: R4.0

**Affected component(s) or functionality**: Clipboard

**Brief summary**: Attempting to copy >4000 bytes between VMs using `xsel` results in confusing message.

**To Reproduce**
1. Open any AppVM
1. Run `python3 -c 'import sys; sys.stdout.buffer.write(b"A" * 4001)' | xsel -ib`
1. Press `Ctrl+Shift+C`

**Expected behavior**
Data should be copied properly; alternatively, an explanatory error message should be displayed.

**Actual behavior**
Popup message says "Copied 1 byte to the clipboard." and nothing is copied.

**Workaround**
One solution to copying large amounts of data in general is to use the `qvm-copy` command.  Another workaround is to use the window manager's usual copying UI instead of using `xsel`.

**Relevant documentation you've consulted**
- https://www.qubes-os.org/doc/copy-paste/ makes no mention of any size limit, nor does it point out that you should use `qvm-copy` to copy large amounts of data.

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
- https://github.com/QubesOS/qubes-issues/issues/5220 Not a duplicate, since that issue is about a different 65kb limit.

**Comment by marmarek** [comment]
This seems to be an issue with `xsel`. If I print it to the console, then copy from there, 4001 bytes are correctly copied.
But when I try to copy 66kb, only first 65000 bytes are copied and so says the message (nothing about exceeding the limit).

**Comment by cryslith** [comment]
Oops, you're right.  I thought I tried that.  Edited the issue.

**Comment by rootnoob** [comment]
I think my issue I discovered some-time has the same root-cause (sorry if this needs a new issue).

Attempting to ctrlc-ctrlshiftc from firefox dvm to ctrlshiftv-ctrlv to gedit results over rougly 65000 bytes as @marmarek said, results in exactly 1 byte being copied to the global clipboard, and 1 letter (the same letter every single time) being pasted into gedit.
