### ISSUE TITLE
DispVM templates not working right

### ISSUE THREAD

**Issue by jon-bit** [QubesOS/qubes-issues#5782]
**Qubes OS version**
4.0.3

**Affected component(s) or functionality**
When I try to make a new DispVM template based on Debian I can't seem to get it to work or sometimes even show up in the application menu. I do everything it says to do in the docs for qubes but still it does not work:
`qvm-create --template debian-10 -l red debian-10-dvm`
`qvm-prefs debian-10-dvm template_for_dispvms True`
`qvm-features debian-10-dvm appmenus-dispvm 1`

**Expected behavior**
I should have a disposable VM template for getting rid of what I don't want to keep data on. also there should be a image for it on the application menu and when started gives me a dispVM (eg. Dips7532) 

**Actual behavior**
I don't see the VM in the application menu and don't get to make them.

Sorry if this is simple or just looks bad. I usualy get this stuff to work and am new to git hub (First post)
Thanks in advance for the help

**Comment by andrewdavidwong** [comment]
>  do everything it says to do in the docs for qubes but still it does not work:
> ```
> qvm-create --template debian-10 -l red debian-10-dvm
> qvm-prefs debian-10-dvm template_for_dispvms True
> qvm-features debian-10-dvm appmenus-dispvm 1
> ```

You're entering these commands in dom0, correct? Do you receive any kind of feedback or error messages after entering them?

**Comment by jon-bit** [comment]
I just found out that that the disposable VMs are made and are created but they are not showing in the applications menu. Anyone know why?

**Comment by jon-bit** [comment]
I just got a disposableVM template working but when I removed it it is still in the application menu. Now I can't get any disposable template VMs working at all. What is going on! does anyone know what to do?

**Comment by n1m1** [comment]
Hi,
I have experienced the same problems reported by @jon-bit few days ago while I was trying to create a DisposableVM template for sys-sub. I followed to the letter the [instructions](http://www.qubesosfasa4zl44o4tws22di6kepyzfeqv3tg4e3ztknltfxqrymdad.onion/doc/disposablevm-customization/) on the Qubes OS site but they did not work: indeed, the new VM was appeared in the menu as an "AppVM" and not as a "Disposable". 

I made few attempts and it worked: now in the menu the DisposableVM template shows as "Disposable" (but I do not know how and why).

However, I have just made a test and tried to launch the following commands in Dom0:

```
qvm-create --template debian-10 -l red debian-10-dvm
qvm-prefs debian-10-dvm template_for_dispvms True
qvm-features debian-10-dvm appmenus-dispvm 1
```

Result: the VM created is not showed in the menu as "Disposable" (as it happens for instance for "Whonix-15-dvm") but as a normal VM.


One more weird thing. If in dom0 I type:

`qvm-features debian-10-dvm appmenus-dispvm [random value, i.e. "cdcdca"]`

I do not get any error message. Is this normal?

**Comment by jon-bit** [comment]
Same. No error message, and it dose not fix the problem I'm having.

**Comment by jon-bit** [comment]
WHAT??? now when I deleted a disposible VM template I made. it is now in the applicasion menu. what is going on?

**Comment by jon-bit** [comment]
Should I re install the OS?

**Comment by andrewdavidwong** [comment]
Please be patient and bear in mind that `qubes-issues` is not a support forum, but rather a place for reporting issues to the developers. Please see our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/). Many issues are reported here each day, and it can take a while for the devs to get to an issue. Please do not "bump" issues unless a long amount of time has passed or you have new information about an issue. For direct requests for help and support, which might receive helpful responses from the community more quickly, please see the `qubes-users` [mailing list](https://www.qubes-os.org/support/).

**Comment by Meta-Shift-q** [comment]
I've ran into the same issue. Something that worked in the past suddenly stopped working. To find out what is happening, you can set the menu to dispvms (i.e., `qvm-features your-dvm appmenus-dispvm 1`). Then start your-dvm and run `qvm-sync-appmenus your-dvm`. If you have this problem, it should fail throwing `qubesappmenus.DispvmNotSupportedError`. In my case, if fails on the following desktop entry in `/usr/lib/python3.5/site-packages/qubesappmenus/__init__.py` in `write_desktop_file`: 

> `[Desktop Entry]`
> `Version=1.0`
> `Type=Application`
> `Exec=qvm-start --quiet %VMNAME%`
> `Icon=%XDGICON%`
> `Terminal=false`
> `Name=%VMNAME%: Start`
> `GenericName=%VMNAME%: Start`
> `StartupNotify=false`
> `Categories=System;X-Qubes-VM;`

Maybe someone knows how this should be fixed.

**Temporary workaround:** Make sure your-dvm is not set to disposable vms in the menu by running `qvm-features -D your-dvm appmenus-dispvm`. Open the applications tab in the settings for your-dvm (`qubes-vm-settings --tab applications your-dvm`). Make sure that some applications are selected on the right hand side, for instance, xterm (but not Start). Apply your selection. Try setting the menus to disposable vms again: `qvm-features your-dvm appmenus-dispvm 1`. @jon-bit, does this work for you?

**Additional comment:** I think this might be a very annoying error for non-experts, who do not select a subset of desktop entries, so it would be great to fix it.

**Comment by jon-bit** [comment]
Well...0___0

Funny story. The CPU on my Laptop failed. I am trying to get a new laptop for qubes but in the moment I don't have a laptop that can support qubes os. If anyone has the same problem pleas let me know if that is a good solution and I will close the issue for the time being but at this time I am unable to get a proper laptop for qubes OS.

**Comment by marmarek** [comment]
Fixed in https://github.com/marmarek/qubes-desktop-linux-common/commit/d34a8955f8d63147389cfe66439ba0cc9eb382b0
