### ISSUE TITLE
builder - bionic - couldn't find remote ref release4.0 (python-pillow)

### ISSUE THREAD

**Issue by SvenSemmler** [QubesOS/qubes-issues#5783]
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
qubes-builder

**Brief summary**
bionic build currently broken

**To Reproduce**
1. git pull (qubes-builder)
2. ./setup (R4.0, stable, normal cloning, no pre-build packages, only templates, only bionic, builder-rpm + builder-debian + mgmt-salt)
3. make install-deps
4. make get-sources 

**Expected behavior**
'make get-sources' completes successfully

**Actual behavior**
-> Updating sources for python-pillow...
--> Fetching from https://github.com/QubesOS/qubes-python-pillow.git release4.0...
fatal: couldn't find remote ref release4.0
make: *** [Makefile:204: python-pillow.get-sources] Error 1

**Screenshots**
n/a

**Additional context**
I am pretty sure it is this commit by Frédéric that broke the bionic build:
https://github.com/QubesOS/qubes-builder/commit/fd916e66548ca33a7782b77227b2e81cf9751df4

... but I am too scared to mess with it or even do a pull-request. ;-)
@fepitre could you please have a look?

**Solutions you've tried**
git checkout 5560315de93ce32850e7557356de3dd67edb9300
(went back to commit by Paweł Marczewski from Tue Mar 17 11:41:42 2020 +0100)
--> bionic builds successfully

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
n/a

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
none

**Comment by marmarek** [comment]
That commit should have removed python-pillow from components list. Do you still have it listed in `make build-info`?

**Comment by SvenSemmler** [comment]
@marmarek: yes it is, but with an interesting difference: when I run 'build-info' with the latest commit python-build shows in red as opposed to the commit from Mar 17. If I understand correctly this means it was automatically added instead of removed. Attached the output of both experiments.
[old.txt](https://github.com/QubesOS/qubes-issues/files/4525636/old.txt)
[new.txt](https://github.com/QubesOS/qubes-issues/files/4525637/new.txt)

**Comment by marmarek** [comment]
I see, `setup` script copies `example-configs/templates.conf` to `builder.conf`, so a commit that removed it from `templates.conf` doesn't affect your `builder.conf`. 
You need to manually remove `python-pillow` from your `builder.conf`. Or remove `builder.conf` and let `setup` script regenerate it.

**Comment by SvenSemmler** [comment]
@marmarek: thank you!
@fepitre: sorry, I didn't know enough and thought this is a bug.
