### ISSUE TITLE
Chinese text shown as underscores in window title

### ISSUE THREAD

**Issue by ccll** [QubesOS/qubes-issues#5784]
### Qubes OS version:

`Qubes release 4.0 (R4.0)`

### Affected component(s) or functionality:

Chinese text are showing as underscores in window title, like this.

![image](https://user-images.githubusercontent.com/5366582/80200919-ede87c80-8655-11ea-9b4e-8a65abd6a5f1.png)

---

### Steps to reproduce the behavior:

When installing Qubes OS I didn't install Chinese language support, I guess this is the reason?

But I could not find applications or documents on installing language support after installation is done, what should I do?

### General notes:

---

**Comment by xaki23** [comment]
thats actualy very intentional and unrelated to installed language support.
check description of "allow_utf8_titles" here: https://www.qubes-os.org/doc/config-files/

**Comment by ccll** [comment]
@xaki23 That's quick, issue solved, thanks!
