### ISSUE TITLE
Domains widget does not update private storage max size

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#5786]
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
Domains widget

**Brief summary**
From IRC:
> <bitbit> Hi. I changed the default storage capacity of a VM through the GUI ("private storage max size") from 2GB to 12GB and restarted the VM. It seems to have expanded the storage in practice, but when I hover over the name of the VM in the Qubes tray menu it still shows "Private storage: 0.12GB / 2.0GB (6.2%)". Is there a better way to display how much storage each VM actually has allocated to it and how much of it is filled?

**Comment by marmarta** [comment]
At the moment the widget updates storage every two minutes; it was introduced in https://github.com/QubesOS/qubes-desktop-linux-manager/commit/00c7bc57c05f63f25ea4722a32538516c53275c9 . I'm going to close this, probably the user didn't have the update pulled in.
