### ISSUE TITLE
Grey / Blank screen before installer setup

### ISSUE THREAD

**Issue by ScratLpp** [QubesOS/qubes-issues#5788]
hello

**Qubes OS version**
R4.0.3

**Brief summary**
I got a grey / white screen before setup installer.

I'm on HP Elitebook 
VT-d i/O enabled
Legacy support enable / Secure Boot Disable
UEFI disabled, All legacy

**Solutions i tried**
I tried everything on https://www.qubes-os.org/doc/uefi-troubleshooting/ but doesn't work.
I got a macbook to edit my USB media, i mount it edit via textedit the bootx64.conf and dismount.

I saw that i should disable IOMMU but it seams to be on the last version of qube not the 4.0.
I tried since this morning and i have no idea what to do more ..

thanks

**Comment by Swenews** [comment]
How did you solve the problem?
