### ISSUE TITLE
Make sharing a single window work with Jitsi in Firefox

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#5789]
**The problem you're addressing (if any)**
Jitsi (and other video conference software) allows desktop sharing. This includes convenient feature of sharing a single window. When running under Qubes, only "entire screen" option is present. Of course this "entire screen" in practice includes only content from that single VM.

**Describe the solution you'd like**
Adjust gui-agent-linux to set necessary metadata to enable enumerating windows/applications in a format that normal window manager does.

**Where is the value to a user, and who might that user be?**
More useful desktop sharing.

**Additional context**
Firefox code using for window enumeration: https://hg.mozilla.org/mozreview/gecko/file/tip/media/webrtc/trunk/webrtc/modules/desktop_capture/window_capturer_x11.cc
Specifically this is interesting:
```
  // Iterates through |window| hierarchy to find first visible window, i.e. one
  // that has WM_STATE property set to NormalState.
  // See http://tronche.com/gui/x/icccm/sec-4.html#s-4.1.3.1 .
  ::Window GetApplicationWindow(::Window window);
```

Windows within Qubes VMs do not have `WM_STATE` property. According to linked documentation there, it is responsibility of a window manager (gui-agent in this case).

**Workaround**

Manually set `WM_STATE` property on a window you want to share:
```
xprop -f WM_STATE 32c -set WM_STATE 1
```
(and click on the window)

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

http://tronche.com/gui/x/icccm/sec-4.html#s-4.1.3.1

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
_A list of links to other bug reports, feature requests, or tasks in the qubes-issues tracker. Do not describe any other unreported bugs, features, or tasks here._

**Comment by Rudd-O** [comment]
It does seem like `WM_STATE` is a property that the window manager ought to respect / set.

Alternatively how about we push forward to Wayland?

**Comment by marmarek** [comment]
> It does seem like `WM_STATE` is a property that the window manager ought to respect / set.

Yes, exactly. And in case of AppVM, window manager = qubes-gui-agent.

> Alternatively how about we push forward to Wayland?

This is tracked here: https://github.com/QubesOS/qubes-issues/issues/3366

**Comment by xaki23** [comment]
as a sidenote: this works for google meet on firefox too. 
thanks!

**Comment by iamahuman** [comment]
This also affects Wine; specifically, there's a few seconds of delay before windows can be opened or closed.

This is what I'm using as a workaround: https://gist.github.com/iamahuman/34bd91b9815fb2cc5de72028d39d223c

The script acts as a "stub" window manager and handles the WM_STATE transition which the GUI agent lacks.
