### ISSUE TITLE
Cannot use Mock to build aarch64 packages

### ISSUE THREAD

**Issue by Rudd-O** [QubesOS/qubes-issues#5792]
Latest Qubes.  Mock (`mock`) requires `qemu-user-static` to run `aarch64` jails, which in turn are required to build `aarch64` packages.  `qemu-user-static` is not installable because Qubes overrides `xen-libs` with its own package `xen-libs:2001` and this package is not parallel-installable with `xen-libs`.

Suggested solution: whatever is necessary from the custom `xen-libs` package in Qubes, that differs from the upstream `xen-libs` package, should be spun to a separate package that deposits its files in a different directory or under different file names, thus making Qubes not prohibit the installation of `qemu-user-static` or `qemu-system-x86_64/aarch64/et cetera`.

**Comment by marmarek** [comment]
Qubes 4.1 already uses upstream xen-libs package, so this problem if fixed there already. And due to the required changes in packaging, it is not backportable to Qubes 4.0.
In the meantime, you can either use Debian, or build qemu from sources.

**Comment by Rudd-O** [comment]
OK.

I can't use Debian because `mock` is not in Debian, but I can wait for Qubes 4.1.
