### ISSUE TITLE
templates VMs not starting

### ISSUE THREAD

**Issue by jon-bit** [QubesOS/qubes-issues#5793]
**Qubes OS version**
4.0

**Affected component(s) or functionality**
kali VM and blackarchlinux vms are not starting after installing tools

**Brief summary**
I had been making pen testing templates (because I'm board) and they are not starting after installing some of the tools. They crash randomly

**To Reproduce**
1. make a debian minimal template VM
2. install katoolin or strap.sh
3. install tools
4. then it crashes

**Expected behavior**
It just works.

**Actual behavior**
I get an error window that says:
"can not connect to qrexec agent for 60 seconds see /var/log/xen/console/guest-blackarchlinux.log  for details."
when trying to start the templateVM

**Comment by andrewdavidwong** [comment]
> I get an error window that says:
> "can not connect to qrexec agent for 60 seconds see /var/log/xen/console/guest-blackarchlinux.log for details."
> when trying to start the templateVM

Could you share that log here?

**Comment by jon-bit** [comment]
Sorry for the late response. Here it is.

![less](https://user-images.githubusercontent.com/59271817/80898146-a0bc7880-8cef-11ea-9e63-57d54f41dd82.png)

**Comment by rapenne-s** [comment]
Could you try on R4.1 or R4.2 Release Candidate to see if the problem still exists?

**Comment by andrewdavidwong** [comment]
If anyone is still experiencing this problem on Qubes 4.1 or higher, please a comment here, and we'll be happy to reopen this.
