### ISSUE TITLE
Create "real" secure DisposableVMs?

### ISSUE THREAD

**Issue by thegodfatheranubis** [QubesOS/qubes-issues#5797]
How do I create secure DisposableVMs?

Hey guys and developers and users,

I recently started using Qube OS. As I see in the documentation, the following applies to DisposableVMs:

"If a DisposableVM Template becomes compromised, then any DisposableVM based on that DisposableVM Template could be compromised. In particular, the default DisposableVM Template is important because it is used by the “Open in DisposableVM” feature. This means that it will have access to everything that you open with this feature. For this reason, it is strongly recommended that you base the default DisposableVM Template on a trusted TemplateVM."

The question I have to ask myself is this.

I would like to create a SAFE DisposableVM which will be deleted on every reboot.

Here is an example:

I used the DisposableVM Web Browser and enter a compromised website which infects me. Now I want everything to be deleted and set to 0 at a shutdown of the VM.  How can I achieve this ?

Is it enough to just create a new Qube with the default DisposableVM template or what is the best way to create a secure DisposableVM browser that will ALWAYS be deleted and set to 0 again ? As I understood the documentation (if I was compiled using the DisposableVM Browser) ALL DisposableVM Templates are affected or did I get it wrong ?

Wouldn't it be better to create a preconfigured Qube that "really" Disposable resets itself to 0 at every shutdown and boot without infecting the DisposableVM template?

Thanks in advance for any help !

**Comment by xaki23** [comment]
> I used the DisposableVM Web Browser and enter a compromised website which infects me. Now I want everything to be deleted and set to 0 at a shutdown of the VM. How can I achieve this ?

just use a disposable vm.
if what you just describes differs from the default functionality of a disposable vm, i dont understand how/where.

**Comment by thegodfatheranubis** [comment]
If a DisposableVM Template becomes compromised, then any DisposableVM based on that DisposableVM Template could be compromised.

´When I use the Pre-Installed DisposableVM fedora-30 and Open a WebBrowser and get infected through the WebBrowser, the Documentation says that all DispoableVMs is infected as well. 

So on the next Start of the DisposableVM I can not be sure that I am not longer compromissed. 

Or do I get something wrong here ?

**Comment by xaki23** [comment]
you are mixing up (or ignoring) the "template" part of the warning.
an appvm (or disposable) can not make persistent changes to its template.
as long as you are not getting the _template_ infected, the disposable started based on that template will be clean.

**Comment by thegodfatheranubis** [comment]
Ah sorry you are totally right ! So basicly the pre-installed fedora-30 disposable will do exactly what I wrote above ?

**Comment by xaki23** [comment]
afaict, yes, that is the case.

but you should update to fedora-31 or even fedora-32! :smile: 
see https://www.qubes-os.org/news/2020/04/30/fedora-31-template-available/

**Comment by thegodfatheranubis** [comment]
Thanks for the tip 🗡️ 

Will better update now and test again after the update ^^

Thanks @xaki23
