### ISSUE TITLE
Unexpected argument handling of qvm-run-vm

### ISSUE THREAD

**Issue by Kixunil** [QubesOS/qubes-issues#5798]
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
`qvm-run-vm`, `/usr/lib/qrun-in-vm`

**Brief summary**
qvm-run-vm doesn't escape arguments properly leading to surprising behavior, possibly breaking scripts.

**To Reproduce**
_Steps to reproduce the behavior:_
_1. Run `qvm-run-vm --dispvm mkdir "/tmp/foo bar" ';' ls '/tmp/foo bar'`_
_2. Observe the output_

**Expected behavior**
`mkdir` creates dirs `/tmp/foo bar`, `;`, and `ls`, failing at the last argument with "already exists message"

**Actual behavior**
The output:
```
bar:

/tmp/foo:
```

suggests that `bar` and `/tmp/foo` were created, thus shell arguments don't seem to be escaped properly.

The offending code is in `/usr/lib/qrun-in-vm`, where it calls `join` on the arguments without escaping them properly first, the following line does some really basic escaping, just to satisfy `bash -c '%s'`

**Solutions you've tried**
One could obviously escape the arguments from the caller, but this is a footgun for anyone not knowing about this quirk. It may seem correct in usual inputs and break on a different input containing space or other special character.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
the man page
However, I now noticed, that `qvm-run-vm` actually documents this behavior under `--help`.  So updating the man page would be helpful, although I've never seen this behavior in any other software and still looks like a major footgun.

**Comment by marmarek** [comment]
This is also the reason for alternative method for starting single process: #4850
