### ISSUE TITLE
qubesd broken after 4.0.50 upgrade

### ISSUE THREAD

**Issue by earsoup** [QubesOS/qubes-issues#5801]
**Qubes OS version**
4.0

**Affected component(s) or functionality**
qubesd

**Brief summary**

**To Reproduce**
1. upgrade qubes-core-dom0 from 4.0.49 to 4.0.50 (plus all other packages released with it)
2. reboot

**Expected behavior**
qubesd starts fine and i can use qubes

**Actual behavior**
qubesd fails to start with qubes.exc.QubesException: no such class "AppVm"

**Screenshots**

![IMG_20200507_223114](https://user-images.githubusercontent.com/64987658/81342958-67e81f00-90b4-11ea-9654-3ccd53449c02.jpg)

**Additional context**

**Solutions you've tried**
I tried to downgrade but old package is not available any more locally and i have no internet access due to no VMs starting. How can I recover from this without having to use my one month old backup?

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

**Comment by marmarek** [comment]
This looks like some files went missing during update (see details below). Haven't you run out of disk space for example? 
As for recovering, you can boot from installation image and copy qubes-core-dom0 package from there.

<details>
It looks like the missing file is `/usr/lib/python3.5/site-packages/qubes-4.0.50-py3.5.egg-info/entry_points.txt`, it should look like this:

```
[qubes.devices]
block = qubes.ext.block:BlockDevice
pci = qubes.ext.pci:PCIDevice
testclass = qubes.tests.devices:TestDevice

[qubes.ext]
qubes.ext.admin = qubes.ext.admin:AdminExtension
qubes.ext.block = qubes.ext.block:BlockDeviceExtension
qubes.ext.core_features = qubes.ext.core_features:CoreFeatures
qubes.ext.gui = qubes.ext.gui:GUI
qubes.ext.pci = qubes.ext.pci:PCIDeviceExtension
qubes.ext.qubesmanager = qubes.ext.qubesmanager:QubesManager
qubes.ext.r3compatibility = qubes.ext.r3compatibility:R3Compatibility
qubes.ext.services = qubes.ext.services:ServicesExtension
qubes.ext.windows = qubes.ext.windows:WindowsFeatures

[qubes.storage]
file = qubes.storage.file:FilePool
file-reflink = qubes.storage.reflink:ReflinkPool
linux-kernel = qubes.storage.kernels:LinuxKernel
lvm_thin = qubes.storage.lvm:ThinPool

[qubes.tests.storage]
file = qubes.storage.file:FilePool
file-reflink = qubes.storage.reflink:ReflinkPool
linux-kernel = qubes.storage.kernels:LinuxKernel
lvm_thin = qubes.storage.lvm:ThinPool
test = qubes.tests.storage:TestPool

[qubes.vm]
AdminVM = qubes.vm.adminvm:AdminVM
AppVM = qubes.vm.appvm:AppVM
DispVM = qubes.vm.dispvm:DispVM
StandaloneVM = qubes.vm.standalonevm:StandaloneVM
TemplateVM = qubes.vm.templatevm:TemplateVM
```

**Comment by earsoup** [comment]
Thanks, I was able to reinstall that package, which fixed it. 
I did not run out of disk space, but maybe it was related to the system freezes I sometimes experience and did not manage to create an issue about yet . Will also problably now reinstall Qubes once I have a backup.
