### ISSUE TITLE
Can't Get A 2nd sys-net On The Network

### ISSUE THREAD

**Issue by BlueTeamByDay** [QubesOS/qubes-issues#5803]
**Qubes OS version**
Qubes OS R4.0

**Affected component(s) or functionality**
Networking

**Brief summary**
_I tried to separate everything into to two subnets meanings 2 NICs, 2 gateways (sys-net), 2 firewalls. Everything works on the network before the new gw and after it. All qubes can communicate to the firewall. After the gateway everything works properly on the physical network as designed and can get out to the internet if I connect any client other to it but the new gateway._

_The main gateway remains functional but the new one can't get on the network, hence the whole chain doesn't work._

**To Reproduce**
_Steps to reproduce the behavior (I tried 3 different way, same results):_
_First Version:_
_Simply clone the main gateway from Qubes Manager._

_Second Version:_
_From dom0 (as root) under` /srv/formulas/base/virtual/machines/formula` duplicate and edit the following two files: `sys-net.top` and `sys-net.sls` and run `qubesctl state.apply qvm/sys-net2` to create a new sys-net from scratch._

_Third version:_
_Create new stanadlone VM, mark "provides networking"_

**Expected behavior**
_My hope was that once I have a new sys-net I can just assign the other NIC to it and connect to the network just like the main gateway_

**Actual behavior**
_If I leave the advanced network manager on DHCP then the gw is not getting and IP from the server. (If I connect any other non-Qubes clients they get an IP right away). If I set the IP manually then it "takes it" but I still cannot get on the network, and can't get online._

**Additional context**
_The physical setup is this: modem <--> pfsense firewall <--> Unifi Switch <--> Server Running Qubes_

_The server has two built in NICs, one PCI and one WiFi. It might be important that if I assign all 3 (not in use) NICs to the 2nd gw then only 1 has a mac address. The other 2 show up as ens[0-9] but I don't see a mac_

_The network is setup so that the main gw on Qubes is on the main LAN segment on the network. The 2nd gw has a designated VLAN setup_

**Solutions you've tried**
_1) To make sure everything works on the server running Qubes and the network itself I used a live boot Linux and tried all NICs. Every NIC was able to connect to both the main LAN and the separate VLAN using both DHCP and manual IP settings._

_2) As I listed above I tried cloning the 2nd gw from the main one and I tried creating from scratch_

_3) I tried editing the gw network settings though nmcli and the GUI_

_4) I booted the server with a Fedora 31 live USB, set network setting manually, copied out the `/etc/sysconfig/network-scripts/ifcfg-interface-name` and manually entered all those through nmcli_

Just to reiterate once more, the network setup outside of Qubes is 100% functional. If I connect any machines to any segment of network to any port on the switch they always work as intended.

**Comment by unman** [comment]
On Fri, May 08, 2020 at 07:56:15AM -0700, BlueTeamByDay wrote:
> **Qubes OS version**
> Qubes OS R4.0
> 
> **Affected component(s) or functionality**
> Networking
> 
> **Brief summary**
> _I tried to separate everything into to two subnets meanings 2 NICs, 2 gateways (sys-net), 2 firewalls. Everything works on the network before the new gw and after it. All qubes can communicate to the firewall. After the gateway everything works properly on the physical network as designed and can get out to the internet if I connect any client other to it but the new gateway._
> 
> _The main gateway remains functional but the new one can't get on the network, hence the whole chain doesn't work._
> 
> **To Reproduce**
> _Steps to reproduce the behavior (I tried 3 different way, same results):_
> _First Version:_
> _Simply clone the main gateway from Qubes Manager._
> 
> _Second Version:_
> _From dom0 (as root) under` /srv/formulas/base/virtual/machines/formula` duplicate and edit the following two files: `sys-net.top` and `sys-net.sls` and run `qubesctl state.apply qvm/sys-net2` to create a new sys-net from scratch._
> 
> _Third version:_
> _Create new stanadlone VM, mark "provides networking"_
> 
> **Expected behavior**
> _My hope was that once I have a new sys-net I can just assign the other NIC to it and connect to the network just like the main gateway_
> 
> **Actual behavior**
> _If I leave the advanced network manager on DHCP then the gw is not getting and IP from the server. (If I connect any other non-Qubes clients they get an IP right away). If I set the IP manually then it "takes it" but I still cannot get on the network, and can't get online._
> 
> **Additional context**
> _The physical setup is this: modem <--> pfsense firewall <--> Unifi Switch <--> Server Running Qubes_
> 
> _The server has two built in NICs, one PCI and one WiFi. It might be important that if I assign all 3 (not in use) NICs to the 2nd gw then only 1 has a mac address. The other 2 show up as ens[0-9] but I don't see a mac_
> 
> _The network is setup so that the main gw on Qubes is on the main LAN segment on the network. The 2nd gw has a designated VLAN setup_
> 
> **Solutions you've tried**
> _1) To make sure everything works on the server running Qubes and the network itself I used a live boot Linux and tried all NICs. Every NIC was able to connect to both the main LAN and the separate VLAN using both DHCP and manual IP settings._
> 
> _2) As I listed above I tried cloning the 2nd gw from the main one and I tried creating from scratch_
> 
> _3) I tried editing the gw network settings though nmcli and the GUI_
> 
> _4) I booted the server with a Fedora 31 live USB, set network setting manually, copied out the `/etc/sysconfig/network-scripts/ifcfg-interface-name` and manually entered all those through nmcli_
> 
> Just to reiterate once more, the network setup outside of Qubes is 100% functional. If I connect any machines to any segment of network to any port on the switch they always work as intended. 
> 
> 

This is better suited for qubes-users - but you already know that
because it's been raised there.
Your specific problem seems to be inadequately described in the title.
It's not that you cant get a second NIC on network, but that you cant
configure that NIC to use the VLAN.
It's already been said on qubes-users that this set up is workable, with
or without VLAN.
Go back to qubes-users and post the NIC configuration for the VLAN

**Comment by andrewdavidwong** [comment]
Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this does not appear to be suitable for `qubes-issues`. We ask that you please send this to the `qubes-users` [mailing list](https://www.qubes-os.org/support/) instead. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a brief comment explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.
