### ISSUE TITLE
EPIC: Default tray UI things

### ISSUE THREAD

**Issue by ninavizz** [QubesOS/qubes-issues#5807]
...creating this issue, simply to track all things having to do with 2020 updates to the tray's default appearance, in a single Epic. :)

**Comment by ninavizz** [comment]
Question to @marmarta: What is the max-size each Tray icon's artwork should be created at? 16x16 is the smallest, and I know you need each multiple-of-8 thereafter; to a point. What may I ask is that point—128x128?

**Comment by marmarta** [comment]
@ninavizz 64x64 is enough - this is the maximum the widget can handle; and while in theory a `hover` state may possible be implementable, we never use it, so `selected/open` and `normal` is all.

**Comment by andrewdavidwong** [comment]
> ...creating this issue, simply to track all things having to do with 2020 updates to the tray's default appearance, in a single Epic. :)

We have [projects](https://github.com/QubesOS/qubes-issues/projects) now, so we no longer have to (ab)use issues for this purpose.

I've made a project for this and added all appropriate issues:

https://github.com/QubesOS/qubes-issues/projects/7

If you want to add/remove any issues to this project, please ping me on those specific issues to add/remove them.
