### ISSUE TITLE
Tray widgets layout/padding improvements

### ISSUE THREAD

**Issue by ninavizz** [QubesOS/qubes-issues#5808]
_Child issue within #5807_

---

**The problem you're addressing (if any)**
The icons in the tray are too smooshed together. This contributes to cognitive strain for the user when working to visually disambiguate what to click on. It also creates anxiety, as an omnipresent ui element.

**Describe the solution you'd like**
1. Kill the gray box. @marmarta and I have discussed this, previously.
2. Add padding to the sides of all of the icons.
3. Add more padding between the "group" of icons around connectivity, and all other system-functionality icons, as shown below. Visual space will create the desired grouping effect the gray outline does, and without the added visual noise.
![image](https://user-images.githubusercontent.com/8262612/81508227-d2b57800-92b7-11ea-9112-cd7a5cc88a06.png)

**Where is the value to a user, and who might that user be?**
1. There is currently a grey outline around many of the icons in the system tray. The outline creates a grouping, which is nice—but it does so by _adding_ more information to an area that already has too much, which creates difficulty for users trying to visually disambiguate things.
2. There is not enough padding

**Describe alternatives you've considered**
Well, it's a default for all Linux-y systems to just let the user customize everything. Unfortunately, that serves one user type: the "maker" user who wants to take the initiative to always do that. 

Even for the maker user-types, why not just ship things with the most usable solution as a default? It kind of sucks _requiring_ the user to modify things, to make their system usable; should a user desire modification, it should be to meet aesthetic preferences, not usability needs.

**Additional context**
Yep, I also need to create updated artwork for the Whonix and Network Connection widgets, to nix the white boxes around those. Will file the Whonix ones in their Phabricator tracking system and will cross-link to the above linked epic.

**Comment by brendanhoar** [comment]
Appears text in ticket above is cut off: "Also, this had been spoken to as a need in"
