### ISSUE TITLE
Qubes manager does not start if any Admin API call is refused

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#5811]
**Qubes OS version**
R4.1

**Affected component(s) or functionality**
qubes-manager

**Brief summary**
Trying to open qubes manager in a GUI domain with limited permissions fails.

**To Reproduce**
_Steps to reproduce the behavior:_
_1. Setup sys-gui_
_2. Open qube manager inside_

**Expected behavior**
Qube manager starts and shows as much info as is available. Info that cannot be retrieved, is marked as unavailable.
Ideally, any failure should be recoverable, but it may be unrealistic in some cases - like failure to getting `qid` (used internally by qube manager). In those cases, I propose either not list such qube at all (and perhaps show some warning on stderr, or some more user friendly place).

**Actual behavior**
Any failure (like, getting dom0's "features") cause qube manager to crash on startup.

**Screenshots**
Video of this job: https://openqa.qubes-os.org/tests/7988

**Additional context**
Qube manager running in GUI domain.

The same issue may apply also to qube settings dialog.

**Solutions you've tried**
Modify policy to give GUI domain every access qube manager needs.

**Comment by marmarta** [comment]
I think this is going to be easier to implement with this PR: https://github.com/QubesOS/qubes-manager/pull/195 ; or if not easier, it seems to be a bad idea to do it before merging that one.
