### ISSUE TITLE
Update Whonix Tray Icon

### ISSUE THREAD

**Issue by ninavizz** [QubesOS/qubes-issues#5813]
_Tracking as child w/in #5807_

---

**The problem you're addressing (if any)**
The `sdw-date` iconography that surfaces in the Qubes tray, is not intuitive to users unfamiliar with the technical details of Whonix. 

A majority of Qubes users will simply want to know if Whonix is or is not connected securely: yes or no. The clock semiotic only speaks to users who understand the concept of time-sync. This imposes a cognitive burden on all non-technical Qubes users, and users new to both Qubes and operating a computer in a high opsec environment. 

The existing clock icons are also difficult to decipher at the small sizes they currently display.

**Describe the solution you'd like**
In the directory [here](https://github.com/Whonix/sdwdate-gui/blob/master/usr/share/sdwdate-gui/icons/), the two existing Qubes tray icons for Whonix exist at `32x32`

I am proposing these two, that will clearly signal "Yes" or "No" with regards to the "Is Whonix (securely) connected?" question this widget's functionality exists to answer. Shown below is my own Qubes tray, mocked-up with the "Yes" icon; and, yes, I have 2 Whonix VMs. 

![image](https://user-images.githubusercontent.com/8262612/81603436-322c8a00-9383-11ea-8c47-8773ac3d9ec4.png)

![TS_Success-32](https://user-images.githubusercontent.com/8262612/81603398-1e812380-9383-11ea-862a-944d3043482c.png)

![TS_Stopped-32](https://user-images.githubusercontent.com/8262612/81603387-19bc6f80-9383-11ea-885d-9d2aa36fd821.png)

^^ Note: The icons in the existing directory, are something like 27x32, not 32x32. I know in a priour version, the icon appeared in my Qubes tray "broken," with a horizontal repeat. @marmarta fixed that, and I don't know if that fix was simply making the not-square icons square, or in code. FYI, the icons provided above, should be properly square PNG files, despite the lock-shapes not being properly square.

**Where is the value to a user, and who might that user be?**
- New users to Qubes, unfamiliar with how time-sync works
- Users who understand time-sync but don't want to squint at the existing icons to decipher them

**Describe alternatives you've considered**
Replacing the existing icons with these, feels like the lowest-burden solution possible, with a high return via a semiotic that clearly speaks to the Whonix branding, and in a clearly discernible symbol for the size of the space.

**Additional context**
CC'ing @troubadoour and [in Phabricator](https://phabricator.whonix.org/T991) for visibility.

I suspect the majority of the "work" with implementing this, will be in change-management wrt updating screenshots on both the Whonix and Qubes websites, and possibly documentation texts. I'm not a developer, so don't know how to do either the above, or changing out the icon in the production repo.

**Comment by marmarta** [comment]
A question: I see there three possible states: 'success' 'wait' and 'stopped'. Obviously we'd like to replace the 'success' and 'stopped' - are you proposing to also replace 'wait' with the same icon as 'stopped'?

**Comment by ninavizz** [comment]
@marmarta Aah, thank you! I'd only seen 2 of the 3 you mentioned. Update pending...

**Comment by ninavizz** [comment]
@marmarta Follow-up question (because my Qubes machine is in the middle of a very lengthy update and I can't look for myself): Will the "Stopped" and "Waiting" icons be colored to the VM as the "Success" icon is?

**Comment by ninavizz** [comment]
I created this 'lil group... and would like to do an animated spinner as part of the "waiting" one, if that's possible to do. The clock semiotic just isn't working for me. I'd also personally prefer to not see these colored per the VM, but I'm curious what you and other users might think of that. 

I question how many users understand what Time Sync is, or get the clock semiotics. Shifting the functional direction of the sdw-timesync widget to be a more general Whonix widget feels like a broader beneficial direction to move towards. 

Thoughts?

![WhonixLox](https://user-images.githubusercontent.com/8262612/81750358-3380b400-9462-11ea-8258-372bece20a40.png)

**Comment by marmarta** [comment]
As far as shifting it to a more general 'Whonix' semiotics, I'm not sure - I don't consider myself enough of a Whonix pro to feel comfortable with answering this. I'm tempted to say this is not a great idea, because clock sync is just part of bigger Whonix ecosystem and what if it fails but the rest does not?

As far as animated icons go, the short answer is that as far as I can tell, doing it as an animated icon is doable although more complex, and probably I will be the person to do it, so I'm much more in favor of a non-animated one :D

**Comment by ninavizz** [comment]
Your points are all fair, and point to a broader question: who should UI elements be optimized for, and do those optimizations leave other users behind? Ideally things could follow a pattern of "Broadest Possible Functionality" at the top level, then narrow down depending on how deeply the user navigates. I like the Time Sync stuff being at a top level w/in the Whonix menu itself, but non-power users still need to access Whonix functionality to reboot Tor, see its status, etc. 

It's currently not intuitive that a clock icon is what one clicks on to access any/all Whonix controls.

To your broader point, tho, I'd love to get some ideas in front of Whonix users—both in Qubes and in other environments—to get feedback. And, ok, without an animated icon for "Waiting." :)

**Comment by marmarek** [comment]
Can we please move the discussion about Whonix part to Whonix issue tracker? I don't think ppl most competent to answer (Whonix developers) are monitoring every issue here...
There is already issue for this: https://phabricator.whonix.org/T991

**Comment by adrelanos** [comment]
I am happy to subscribe here. As long as github notifications are functional, I'll usually follow. Please tag @adrelanos to notify me.
Can't follow all Qubes tickets (did that in past) but it's too much to keep following all.
I am using https://phabricator.whonix.org as a reminder / roadmap.

One thing worth mentioning:
In future networking will be blocked [1] until sdwdate succeeded. sdwdate-gui status "in progress" ("wait") will reflect that. Ticket: https://phabricator.whonix.org/T533

[1] Technical detail: All traffic blocked except obviously Tor and sdwdate.

> The existing clock icons are also difficult to decipher at the small sizes they currently display.

Agreed. The port to Qubes didn't implement graphics well.

> I see there three possible states: 'success' 'wait' and 'stopped'.

Indeed.

> Will the "Stopped" and "Waiting" icons be colored to the VM as the "Success" icon is?

Qubes (not Whonix) will always re-color.

> and would like to do an animated spinner as part of the "waiting" one, if that's possible to do.

I don't know if that is possible without code changes. Only way to find out is a test. If you have a test `gif` image it can be tried out.
That would be nicer indeed.

> I'd also personally prefer to not see these colored per the VM, but I'm curious what you and other users might think of that.

Guess this needs to be discussed separately in own ticket / conversation with Qubes.

> I question how many users understand what Time Sync is, or get the clock semiotics.

Right...

> As far as animated icons go, the short answer is that as far as I can tell, doing it as an animated icon is doable although more complex, and probably I will be the person to do it, so I'm much more in favor of a non-animated one :D

I had no idea if Qubes doesn't support animated systray icons but I guess that is what was just said.

> To your broader point, tho, I'd love to get some ideas in front of Whonix users

Could write a guest post at [Whonix news](https://forums.whonix.org/c/news/) and/or Qubes blog?

> Shifting the functional direction of the sdw-timesync widget to be a more general Whonix widget feels like a broader beneficial direction to move towards.

That is already somewhat the case since sdwdate-gui also shows Tor status, allows to start Tor control panel. So, yes, can be the Whonix widget. Also positive feedback by me as per https://phabricator.whonix.org/T963

My goal was to address all points. Please remind me should something be left unanswered.

**Comment by brendanhoar** [comment]
> @marmarta Follow-up question (because my Qubes machine is in the middle of a very lengthy update and I can't look for myself): Will the "Stopped" and "Waiting" icons be colored to the VM as the "Success" icon is?

Just wanted to note that the whonix (nee sdwdate) applet will always be running within the context of a particular instance of a sys-whonix{,-xyz,-etc} based on the whonix-gw template. Most users have either zero or one of these. Typically if one, it is called sys-whonix. Some users have several for multiple TOR entry points (*waves hands re: security best practices*) so the user can color them appropriate to the context.

FWIW, I've moved to using grey for all default sys-* VMs, so my default sdwdate icon color is grey.

**Comment by ninavizz** [comment]
@brendanhoar Thank you for clarifying that! I run a Qubes machine provisioned by an org, specifically for our customers—and indeed, we have 2 Whonix instances, on it. Good to hear feedback from your own observations. 

@adrelanos Many, many thanks to your detailed feedback, above! As noted in the Whonix Phabricator, I am working on getting funding secured for Whonix UX work. Parallel to that, I'd also like to get funding secured to pay a GUI developer to implement the improvements. 

I will email you directly, about getting a blog post up—as I feel that would be a terrific way to engage folks, both to contribute to structured user feedback, and to express interest in consideration for paid developer work. Likewise, about the funding applicaiton itself. 

Per @marmarek's note, above, I'm closing this issue, here. Also, because @adrelanos pushed the icons to the Whonix repo, yesterday—so the concern this issue was created to address, has already been tended to. 

I am still interested in learning when the updated icon will ship, so that I can inform our training team so that they're not surprised.

**Comment by ninavizz** [comment]
Oops, hit the wrong button... :D
