### ISSUE TITLE
Sketch Wireframes or Mockups

### ISSUE THREAD

**Issue by ninavizz** [QubesOS/qubes-issues#5816]
...nothing here needs "doing," just wanted somewhere central and share-able to keep updated versions of my Sketch file(s). In case I get hit by a bus, eaten by one of my cats, etc. 

Sketch is Mac-only software, as a heads-up. 

Also, all artwork I use to make PNGs or SVGs from, for use in UI things, lives in this file; source art for the Qute Qubes, among other things. 
[QubesOS.sketch.zip](https://github.com/QubesOS/qubes-issues/files/4619219/QubesOS.sketch.zip)

**Comment by andrewdavidwong** [comment]
> ...nothing here needs "doing," just wanted somewhere central and share-able to keep updated versions of my Sketch file(s).

Perhaps a [Gist](https://gist.github.com/) might be more appropriate?

**Comment by imme-emosol** [comment]
Just wondering; why are png's used?
In other words; when is svg not good?

**Comment by andrewdavidwong** [comment]
Closing as [non-actionable](https://www.qubes-os.org/doc/reporting-bugs/#every-issue-must-be-about-a-single-actionable-thing).
