### ISSUE TITLE
i3lock Intermittent Freezes When Unlocking

### ISSUE THREAD

**Issue by BawdyAnarchist** [QubesOS/qubes-issues#5817]
**Qubes 4.0.3**

**Affected component:**  i3lock  
**Summary:**  Unlock intermittently freezes at "verifying" 

### Steps to Reproduce Undesired Behavior

1. Lock computer (manual or timeout)
2. Wait time can be minutes or hours after locking
3. i3lock accepts password, but freezes at "Verifying"
4. Issue is not constant, only every 3 to 10 unlocks, seemingly random
5. Requires switching consoles and killing either i3lock or i3 entirely

### Solution

`vi /home/user/.config/i3/config`  
Search for `i3lock -d` and remove the \`-d' option

**Additional Context**  
This is present in the default config generated by i3 upon first login.  Could probably just be removed from [qubes-desktop-linux-i3-settings-qubes](https://github.com/QubesOS/qubes-desktop-linux-i3-settings-qubes) repo config files.

**Relevant Documentation**  
From the i3 man page:  
> DPMS  
       The -d (--dpms) option was removed from i3lock in version 2.8. There were plenty of use-cases that were not properly addressed, and plenty of bugs surrounding that feature. While features are not normally removed from i3 and its tools, we felt the need to make an exception in this case.

**Comment by Shic1983** [comment]
Can confirm i've had this happen a few times also. Very random in how/when it occurs. 
Am now running without the `-d` option to see how it goes.
