### ISSUE TITLE
BSD Base

### ISSUE THREAD

**Issue by straussmaus** [QubesOS/qubes-issues#5824]
**The problem you're addressing (if any)**
Linux foundation has added a forth Microsoft member, Huwai (may have) submitted a patch to Linux with a backdoor, etc.

**Describe the solution you'd like**

Wouldn't it be wonderful if Qubes was based on BSD, at least in dom0?  Maybe Linux Qubes would still be an option but the base system could be BSD.

**Where is the value to a user, and who might that user be?**

Everyone may benefit from moving away from Linux.  

**Additional context**

I really don't know.  This is obviously a very vague thought and I am interested in opinions.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

It's important to look into this yourself because I can't really prove any of this.  But I read today that Huwai submitted a backdoor to Linux, and it might be true or not.

**Comment by marmarek** [comment]
This is nowhere on our roadmap and given practical aspects (drivers support, number of developers contributing etc) we don't plan to change it.

**Comment by straussmaus** [comment]
@marmarek That makes sense.  It is a big undertaking.
