### ISSUE TITLE
Improve qubes-os.org HTTPS Encryption 

### ISSUE THREAD

**Issue by indolering** [QubesOS/qubes-issues#5825]
**The problem you're addressing (if any)**
The current HTTPS [setup is okay](https://www.ssllabs.com/ssltest/analyze.html?d=yum.qubes-os.org), but it could be upgraded to prevent HTTP MITM attacks, mitigate fraudulent HTTPS certificate publishing, and upgrade the cryptographic protocol suite.

**Describe the solution you'd like**
In order of increasing difficulty:

- [x] Update the server to accept TLS 1.3.
- [x] Add a [DNS CAA record](https://letsencrypt.org/docs/caa/) to prevent one of the thousands of certificate "authorities" from issuing a bad cert.
- [x] Force HTTPS everywhere using [strict transport security](https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security).  The Let's Encrypt program [should be able to handle  most of the legwork for you](https://timkadlec.com/2016/01/hsts-and-lets-encrypt/):
  - [x] Add HSTS header to **all** HTTP responses.  `http://qubes-os.org` is currently redirected to `http://www.qubes-os.org` first.
  - [x] Set the max-age to `31536000`.
  - [x] Signal HSTS for subdomains.
  - [x] Add the preload option.
  - [ ] [Switch to a wildcard certificate](https://community.letsencrypt.org/t/acme-v2-production-environment-wildcards/55578)?  This would ease deployment.
  - [x] Submit the domain to the [HSTS preload list](https://hstspreload.org/?domain=qubes-os.org) to prevent downgrade on first contact.

**Where is the value to a user, and who might that user be?**

1. HTTPS provides some fault tolerance for when other cryptographic methods fail [[1](https://github.com/QubesOS/qubes-secpack/blob/master/QSBs/qsb-028-2016.txt)][[2](https://github.com/QubesOS/qubes-secpack/blob/master/QSBs/qsb-046-2019.txt)].
2. [Fedora and Qubes do not sign repo metadata](https://github.com/QubesOS/qubes-issues/issues/891), leading to potential DoS for updates.
3. Checking PGP signatures of the ISO files is a PITA and is probably regularly skipped by users.

**Comment by marmarek** [comment]
Thanks for heads up. I've updated most of the above.
Note that some of the infrastructure is not directly under our control (see more why [it's ok for us](https://www.qubes-os.org/faq/#what-does-it-mean-to-distrust-the-infrastructure)) - for example the website is hosted via github pages. As so, we are limited to settings available there.

>     * [ ]  [Switch to a wildcard certificate](https://community.letsencrypt.org/t/acme-v2-production-environment-wildcards/55578)?  This would ease deployment.

That's not an issue, letsencrypt makes it easy enough. And TBH, I like to avoid wildcard certs if practical, so if one breaks into one server, will not get cert valid for other servers too.

**Comment by indolering** [comment]
> Note that some of the infrastructure is not directly under our control (see more why it's ok for us) - for example the website is hosted via github pages. As so, we are limited to settings available there.

Yup.

> That's not an issue, letsencrypt makes it easy enough. And TBH, I like to avoid wildcard certs if practical, so if one breaks into one server, will not get cert valid for other servers too.

According to [this scan](https://www.ssllabs.com/ssltest/analyze.html?d=qubes%2dos.org&s=2606%3a4700%3a3037%3a0%3a0%3a0%3a6818%3a6e43&latest) of qubes-os.org, Cloudflare appears to be issuing a wildcard cert for your primary domain.  It's also using TLS 1.0 and 1.1, which you really turn off.

And why do you list Comodoca as a cert authority?

**Comment by indolering** [comment]
Like, Comodo is seriously [the worst](https://en.wikipedia.org/wiki/Comodo_Group#Certificate_hacking).  They issued certs to some Iranian script kiddie, published an unpatched "secure browser", they tried to register for a bunch of Let's Encrypt trademarks....

**Comment by marmarek** [comment]
That's what Cloudflare adds automatically for the primary qubes-os.org domain, because that is indeed served by CF (mostly serving redirects). Subdomains have only letsencrypt listed.
I'll see if we can move primary qubes-os.org hosting elsewhere to avoid CF-issued certs at all.

**Comment by indolering** [comment]
I wouldn't spend too much time on it, just sign up for [report-uri.com](https://report-uri.com/products/expect_ct_reports) to get alerts for when a new cert is issued.  It's not like any other CDN will be more secure.
