### ISSUE TITLE
Enable LVM autoextend

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#5826]
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
lvm, installer

**Brief summary**
Installer (anaconda) leaves some space not allocated (~20% now, previously less). This is supposed to be used by LVM autoextend to automatically enlarge data or metadata volumes according to the needs. But autoextend is disabled.

**To Reproduce**
_Steps to reproduce the behavior:_
_1. Install Qubes 4.0_
_2. Check LVM pool size and settings_
_3. See ~20% not allocated, but `thin_pool_autoextend_threshold` in `/etc/lvm/lvm.conf` set to 100 (effectively disabling the feature)_

**Expected behavior**
When free space is left, autoextend should be enabled to make use of it.

**Actual behavior**
Autoextend not enabled.

**Additional context**
This is yet another countermeasure for filling up metadata volume.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
#3243 

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
_A list of links to other bug reports, feature requests, or tasks in the qubes-issues tracker (or "none" if you didn't find any). Do not describe any other unreported bugs, features, or tasks here._

**Comment by marmarek** [comment]
This one is annoying:  lvm config is quite unfriendly to modify via packages - there is no conf.d, and lvm complains about duplicated options (so appending at the end to override earlier value results in a warning)

**Comment by DemiMarie** [comment]
> This one is annoying: lvm config is quite unfriendly to modify via packages - there is no conf.d, and lvm complains about duplicated options (so appending at the end to override earlier value results in a warning)

`sed -Ei`?

**Comment by marmarek** [comment]
I'd like to avoid conflicting/overriding user changes as much as possible. This parameter does make sense for the user to change (for extremely large disks for example). I'd like to at least insert a comment saying what user needs to do, to override automatic value (which would be re-added at subsequent update).

**Comment by andrewdavidwong** [comment]
Should this have priority `P: blocker` since it's included in https://github.com/QubesOS/qubes-issues/projects/6?

**Comment by DemiMarie** [comment]
> I'd like to avoid conflicting/overriding user changes as much as possible. This parameter does make sense for the user to change (for extremely large disks for example). I'd like to at least insert a comment saying what user needs to do, to override automatic value (which would be re-added at subsequent update).

Should be doable.  What about modifying it if it is commented out or set to 100, and leaving alone otherwise?
