### ISSUE TITLE
qvm-volume extend <vm-name>:root <size> not working?

### ISSUE THREAD

**Issue by 0rb677** [QubesOS/qubes-issues#5827]
**Qubes OS version**
4.0.3

**Affected component(s) or functionality**

parrot appvm

```
qvm-volume extend parrot:root 50g
```
df -h shows only 30g in appvm. 

![qvm-volume](https://user-images.githubusercontent.com/60626673/82102418-2bea3500-9718-11ea-8c21-fb7e6a04bc21.png)

On debian it works. Strange..
![qvm-volume2](https://user-images.githubusercontent.com/60626673/82102966-efb7d400-9719-11ea-8787-57ac3827afcb.png)

**Comment by marmarek** [comment]
AppVM has non-persistent root volume (this is also why extending it is grayed out in GUI settings). So, this is correct that extend on root volume doesn't have persistent effect.
