### ISSUE TITLE
HVM-qube with ISO-image crashes after boot

### ISSUE THREAD

**Issue by ineedhelpwithqubes** [QubesOS/qubes-issues#5828]

**Comment by xaki23** [comment]
this is the wrong place for first level support of the "i need basic help with linux" kind.
the qubes-users mailinglist might be better.

please post the "qvm-prefs yourhvmvm" output.
(blind guess: assigned too much ram to the vm, try with 2GB)

**Comment by ineedhelpwithqubes** [comment]
I already tried changing RAM, didn't work. The Output: 

![20200516_173317](https://user-images.githubusercontent.com/65452272/82123825-a4dea080-979b-11ea-8201-c291b3aed498.jpg)

**Comment by xaki23** [comment]
the screenshot says your VM has 400MB of memory. that is probably not enough.

also measure the time it takes before the vm shuts down. is it about 60 seconds? then try setting qrexec_timeout to something higher, perhaps 120. now try again. does it shut down after 120 seconds now? then you need to disable qrexec.

**Comment by ineedhelpwithqubes** [comment]
Thank you very much for the help, I really appreciate that, but as you might have recognized I'm quite new to qubes and linux, so could you be so kind and write the commands down i have to type in the terminal to do so? :)

**Comment by xaki23** [comment]
to set the vm to 2GB of ram: qvm-prefs my-new-vm memory 2000

to measure how long it takes until the vm stops: use a clock that shows seconds, measure the time between you starting the vm and it shutting down. if it is qrexec-timeout, there should be no interaction with the vm required, it will always shut down after the same amount of time, about 60 seconds. 
if this is the case, please post "qvm-features my-new-vm" output.
(qrexec timeout should not be applied since this is a standalone, but who knows...)

**Comment by ineedhelpwithqubes** [comment]
It took 20 seconds, so it seems to be another issue..

**Comment by brendanhoar** [comment]
Is memory balancing disabled?

**Comment by ineedhelpwithqubes** [comment]
Its enabled

**Comment by ineedhelpwithqubes** [comment]
Ok I guess it worked now, but what do I have to do when it finished the installation of the OS in the VM? When I just click on "Restart", I cant boot the HVM itsself, I can just boot it with the ISO-File again, and then it logically begins the installation again. So where is the installed OS now and how can I boot it? (I know this might be a silly question, but I would appreciate some help here :+1: )

**Comment by brendanhoar** [comment]
For HVMs I generally disable memory balancing.

**Comment by ineedhelpwithqubes** [comment]
Okay thank you, but could you please tell me how to actually boot the HVM after its installation? (Without the ISO because its getting installed again then)

**Comment by marmarek** [comment]
In the menu you should have "start" option for this qube. If not,
alternative methods:
 - open Qube Manager, select the qube and click start
 - in dom0 console: qvm-start <qube name>

**Comment by ineedhelpwithqubes** [comment]
Thanks for the response, but thats what I already tried and it didn't work out for me. After clicking on "Continue" here: 
![20200517_083402](https://user-images.githubusercontent.com/65452272/82137522-566fe700-9819-11ea-8644-80e405d62779.jpg)
The VM shuts down as it should, but when I type qvm-start kali in dom0 or start it via GUI, that window pops up:
![20200517_083337](https://user-images.githubusercontent.com/65452272/82137539-7bfcf080-9819-11ea-93fc-bcc07a0651ff.jpg)
What am I doing wrong here? When I type the command to start it via ISO the installation begins again..

**Comment by marmarek** [comment]
Maybe you have installed it to the wrong disk? VM has 3 disks connected by default, you should use the first one for the system.

**Comment by ineedhelpwithqubes** [comment]
Thanks for your reply! During installation I have chosen the following:

Partitioning method: use entire disk
Select disk to partition: Virtual Disk 1 (xvda)
Partitioning scheme: All files in one partition

Is that right?

**Comment by ineedhelpwithqubes** [comment]
Windows HVM works though

**Comment by ineedhelpwithqubes** [comment]
Windows works though..

**Comment by ineedhelpwithqubes** [comment]
The issue is that the HVM cannot find the CDRom to boot from, so how do I tell it which one it is? As you can see on the screenshot, it is trying to boot from hard disk because it cant find the cdrom

**Comment by ineedhelpwithqubes** [comment]
The issue is that the HVM cannot find the CDRom to boot from, so how do I tell it which one it is? As you can see on the screenshot, it is trying to boot from hard disk because it cant find the cdrom

When I try to boot from additional drive (cdrom:the iso) it says "libxenlight failed to create new domain X". I tried to check /var/log/libvirt/libxl/libxl-driver.log, but it says "Permission denied", even with sudo/root

**Comment by ineedhelpwithqubes** [comment]
The issue is that the HVM cannot find the CDRom to boot from, so how do I tell it which one it is? As you can see on the screenshot, it is trying to boot from hard disk because it cant find the cdrom

When I try to boot from additional drive (cdrom:the iso) it says "libxenlight failed to create new domain X". I tried to check /var/log/libvirt/libxl/libxl-driver.log, but it says "Permission denied", even with  #sudo/root
![20200518_101512](https://user-images.githubusercontent.com/65452272/82190104-cc934d00-98f0-11ea-8a4f-331877f0c90c.jpg)

**Comment by marmarek** [comment]
> I tried to check /var/log/libvirt/libxl/libxl-driver.log, but it says "Permission denied"

I guess you did something wrong accessing the file. Try this: `sudo less /var/log/libvirt/libxl/libxl-driver.log`


> The issue is that the HVM cannot find the CDRom to boot from

VM is configured to boot from CDROM first, but if it isn't connected (like already installed system), it should boot from the hard driver (xvda). This is also visible on your earlier screenshot ("Booting from Hard Disk"). Maybe bootloader isn't installed? Also note, currently VM boots in legacy mode, not UEFI - check what kind of bootloader Kali installs.

**Comment by ineedhelpwithqubes** [comment]
Thank you for your answer, here's the log file, sudo less worked:
![20200518_131228](https://user-images.githubusercontent.com/65452272/82206862-433c4480-9909-11ea-9903-9e4228ad5c84.jpg)
What exactly is bootloader and how do I check if it is installed/what kind of bootloader kali installs? Thanks!
