### ISSUE TITLE
xxd not present in dom0

### ISSUE THREAD

**Issue by unman** [QubesOS/qubes-issues#5829]
**Qubes OS version**
R4.0.3

**Affected component(s) or functionality**
qvm-create error message

**Brief summary**
qvm-create fails, but error throws an error 

**To Reproduce**
_Steps to reproduce the behavior:_
_1. qvm-create using "--root-copy-from"_

**Expected behavior**
_Root will be imported or error message shown_

**Actual behavior**
_Fails, but throws error - ._
_/etc/qubes-rpc/admin.vm.volume.Import: line 38: xxd: command not found_

**Additional context**
_I'm importing a qemu ReactOS image_

**Solutions you've tried**
_Installing vim-common, which provides_

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
_None_

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
_Nothing relevant._

**Comment by marmarek** [comment]
Can you say something more about your setup? I do have `xxd` installed by default.

**Comment by unman** [comment]
Indeed, check on my main system and vim-common is installed.
