### ISSUE TITLE
Allow for functional NetVM without passwordless root package installed

### ISSUE THREAD

**Issue by TNTBOMBOM** [QubesOS/qubes-issues#5836]
**Qubes OS version**
R4

**Affected component(s) or functionality**
Sys-net , NetworkManager

**Brief summary**
installed fedora-31-minimal and installed needed packages from this page to support sys-net/networking:

https://www.qubes-os.org/doc/templates/minimal/

But NetworkManager doesnt function/connect without passwordless-root installed. 

**Note**: tested with fedora-31 (full) it shows the same results , unrelated to minimal or not. (ofcourse i removed passwordless-root package from fedora-full to test) 

**To Reproduce**

_1. Install fedora-31-minimal 
_2. Install whats needed for Minimal Template to make it sys-net (without passwordless-root and polkit) 
_3. NetworkManager doesnt provide internet connection

**Expected behavior**
It should work regardless to passwordless-root

**Actual behavior**
Doesnt work unless installed

**Comment by andrewdavidwong** [comment]
Please see: https://www.qubes-os.org/doc/templates/minimal/#important

In light of the above, I believe this should be closed as "not an issue." If you believe this is a mistake, please leave a comment, and we'll be happy to take another look. Thank you.

**Comment by TNTBOMBOM** [comment]
the issue is not with minimal or not tbh, the issue in fact with passworless-sudo exist or not. 

i tried it as well with fedora-full , same issue. 

i will edit my post to not confuse with minimal is the issue.

**Comment by unman** [comment]
You need  *some* modifications to the system authentication methods to have Network Manager working for ordinary users. So this would require shipping a new package to provide those limited mods, which would have some degree of overlap with passwordless-root.
If I remember, (at least on Debian), it's explicitly stated that there may be unexpected side effects in terms of granting new permissions to users of this method. We don't want those. I'd close this as "Wont do".

**Comment by andrewdavidwong** [comment]
Thanks for providing your insight, @unman.

Now I'm wondering: Why do you consider it a bug that sys-net does not work without passwordless-root, @TNTBOMBOM? What is the problem?

**Comment by TNTBOMBOM** [comment]
Because of its impact, the easiness of user space jumping to root space 
without password while this VM is passing all communications through it 
just doesnt fit secure practice.

so if i remove passwordless-root , VM should back to its original state 
of using normal user and root.

or whatever the solution is... but entire sys-net corrupted due to 
unrelated package deletion to sys-net(directly) is not sane.

https://forums.whonix.org/t/restrict-root-access/7658

Another issue as well, this command:

qvm-run -u root qubename appname

sorta useless in this case , what is the use of this command if i need 
to install passwordless-root anyway in the template?

> Thanks for providing your insight, @unman.
> 
> Now I'm wondering: Why do you consider it a bug that sys-net does not work without passwordless-root, @TNTBOMBOM? What is the problem?
>

**Comment by xaki23** [comment]
> Because of its impact, the easiness of user space jumping to root space without password while this VM is passing all communications through it just doesnt fit secure practice.

perhaps you should not be doing anything in your netvms where that matters? (=="not running an untrusted user application")


> what is the use of this command if i need to install passwordless-root anyway in the template?

the point of the minimal templates is that they can be used as basis for custom templates by allowing you to install whatever is needed for your need-a-custom-template usecase.
they are not meant as out of the box solution for arbitrary tinfoilhattery.

if you really want to customize your template(s) in that direction, i recommend reading https://www.qubes-os.org/doc/vm-sudo/

so i am with @unman on this one: the dependencies of NetworkManager are not an issue for a qubes template.

**Comment by marmarek** [comment]
Yes, I agree with @unman and @xaki23, minimal template is just a base for custom templates, not something to be used out of the box.

But also, there would be a value in a feature of functional netvm without passwordless root package installed. The harder we make live for attacker, the better.

**Comment by unman** [comment]
afaik you can remove passwordless-root from a full template, and still have a functional NetworkManager applet.
So this is **another** case of difficulty in configuring a minimal template - there really should be a health warning. Oh, there is.

**Comment by TNTBOMBOM** [comment]
I agree if the subject about minimal template only then this is an issue 
with the minimal template, but i believe i said its also effecting 
fedora-full stripped off passworldless-root,polkit packages. Sorry if i 
couldnt make it more clear than what i already wrote.

 > But also, there would be a value in a feature of functional netvm 
without passwordless root package installed. The harder we make live for 
attacker, the better.

Yes exactly thats what im trying to say. If this can happen in any 
coming day then this ticket can be closed as fixed because thats what i 
meant.


Thanks

Marek Marczykowski-Górecki:
> Yes, I agree with @unman and @xaki23, minimal template is just a base for custom templates, not something to be used out of the box.
> 
> But also, there would be a value in a feature of functional netvm without passwordless root package installed. The harder we make live for attacker, the better.
>

**Comment by unman** [comment]
> its also effecting fedora-full stripped off passworldless-root,

No, it isn't. You can remove passwordless-root from a full template (Debian or Fedora) and have a fully functioning NM applet.
I don't know what *polkit* packages you have removed, but they are obviously needed.

**Comment by fepitre** [comment]
I successfully made working a sys-net with minimal Fedora template + Networkmanager + PolKit + custom pkla file for allowing user to control network. This, without any sudo passwordless. Any refined goal up to allowing full network control for the user? For example, only allow user to connect disconnect but not modifying connections?

**Comment by TNTBOMBOM** [comment]
NetworkManager has alot of uses like for e.g cloning of mac address, VPN 
, maybe disabling IPv6 as well , maybe other options as well.

but how you made the NetworkManager tray working? i cant even change a 
thing inside it without installing passworldless.

or you changed things manually in the vm to just connect/disconnect 
without further possible changes? (what i understand from you)


Frédéric Pierret:
> I successfully made working a sys-net with minimal Fedora template + Networkmanager + PolKit + custom pkla file for allowing user to control network. This, without any sudo passwordless. Any refined goal up to allowing full network control for the user? For example, only allow user to connect disconnect but not modifying connections?
>

**Comment by fepitre** [comment]
Well, here is what I've done:
1) installed fedora-31-minimal + network-manager + polkit (+ network-manager-applet in a second test for checking the applet itself)
2) created the polkit file `/etc/polkit-1/localauthority/50-local.d/network-manager.pkla`:
```
[network-manager]
Identity=unix-group:qubes
Action=org.freedesktop.NetworkManager.*
ResultAny=yes
ResultInactive=yes
ResultActive=yes
```
With nmcli or nm-applet I'm able to enable, disable, create, remove, etc. Please note that I based the rule on `group: qubesos` instead of the user itself in case someone wants to create another user name.

If that would be enought, this could be easily packaged into qubes core-agent-linux network-manager package. In this case, password-less package would not be needed.

**Comment by unman** [comment]
I dont think we should provide this, or any such, configuration - there will be users who *dont* want the ordinary user account to be able to control NM.
In any case:
> 1.The Minimal TemplateVMs are intended only for advanced users. If you encounter problems with the Minimal TemplateVMs, we recommend that you use their standard TemplateVM counterparts instead.
> 2.If something works with a standard TemplateVM but not the minimal version, this is most likely due to user error (e.g., a missing package or misconfiguration) rather than a bug. In such cases, you should write to qubes-users to ask for help rather than filing a bug report, then contribute what you learn to the documentation.

**Comment by TNTBOMBOM** [comment]
I said before my trial was on fedora-full and so as fedora-minimal , 
please dont jump into conclusions before you try to yourself:


removing passwordless package from fedora-31-full version will remove:

```
================================================================================
  Package                   Arch   Version          Repository 
    Size
================================================================================
Removing:
  qubes-core-agent-passwordless-root
                            x86_64 4.0.55-1.fc31 
@qubes-vm-r4.0-current 2.5 k
Removing dependent packages:
  qubes-vm-recommended      noarch 4.0.7-1.fc31 
@qubes-vm-r4.0-current   0
Removing unused dependencies:
  ethtool                   x86_64 2:5.4-1.fc31     @updates 
   462 k
  fakeroot                  x86_64 1.24-2.fc31      @fedora 
   163 k
  fakeroot-libs             x86_64 1.24-2.fc31      @fedora 
   117 k
  libnftnl                  x86_64 1.1.3-2.fc31     @fedora 
   222 k
  libtomcrypt               x86_64 1.18.2-4.fc31    @fedora 
   943 k
  libtommath                x86_64 1.0.1-10.fc31    @fedora 
    98 k
  nautilus-python           x86_64 1.2.3-2.fc31     @fedora 
    60 k
  net-tools                 x86_64 2.0-0.55.20160912git.fc31
                                                    @fedora 
   1.0 M
  nftables                  x86_64 1:0.9.1-3.fc31   @fedora 
   813 k
  openpgm                   x86_64 5.2.122-17.fc31  @fedora 
   336 k
  pciutils                  x86_64 3.6.4-1.fc31     @updates 
   213 k
  pulseaudio-qubes          x86_64 4.0.29-1.fc31 
@qubes-vm-r4.0-current  41 k
  python3-babel             noarch 2.7.0-2.fc31     @fedora 
    26 M
  python3-jinja2            noarch 2.10.1-2.fc31    @fedora 
   2.5 M
  python3-markupsafe        x86_64 1.1.1-2.fc31     @fedora 
    60 k
  python3-msgpack           x86_64 0.6.1-3.fc31     @fedora 
   284 k
  python3-psutil            x86_64 5.6.7-1.fc31     @updates 
   2.1 M
  python3-pycryptodomex     x86_64 3.9.7-1.fc31     @updates 
   3.2 M
  python3-pytz              noarch 2019.2-1.fc31    @fedora 
   174 k
  python3-pyyaml            x86_64 5.3.1-1.fc31     @updates 
   693 k
  python3-zmq               x86_64 18.0.2-2.fc31    @fedora 
   1.6 M
  qubes-core-agent-dom0-updates
                            x86_64 4.0.55-1.fc31 
@qubes-vm-r4.0-current 7.2 k
  qubes-core-agent-nautilus x86_64 4.0.55-1.fc31 
@qubes-vm-r4.0-current 6.3 k
  qubes-core-agent-network-manager
                            x86_64 4.0.55-1.fc31 
@qubes-vm-r4.0-current 3.2 k
  qubes-core-agent-networking
                            x86_64 4.0.55-1.fc31 
@qubes-vm-r4.0-current  25 k
  qubes-gpg-split           x86_64 2.0.45-1.fc31 
@qubes-vm-r4.0-current  73 k
  qubes-img-converter       x86_64 1.2.8-1.fc31 
@qubes-vm-r4.0-current 4.5 k
  qubes-input-proxy-sender  x86_64 1.0.18-1.fc31 
@qubes-vm-r4.0-current  23 k
  qubes-mgmt-salt-vm-connector
                            noarch 4.0.22-1.fc31 
@qubes-vm-r4.0-current 5.4 k
  qubes-pdf-converter       x86_64 2.1.7-1.fc31 
@qubes-vm-r4.0-current  13 k
  qubes-usb-proxy           noarch 1.0.28-1.fc31 
@qubes-vm-r4.0-current  10 k
  salt                      noarch 3000.2-1.fc31    @updates 
    46 M
  salt-ssh                  noarch 3000.2-1.fc31    @updates 
   4.0 k
  socat                     x86_64 1.7.3.4-1.fc31   @updates 
   1.1 M
  thunderbird-qubes         noarch 2.0.4-1.fc31 
@qubes-vm-r4.0-current  10 k
  tinyproxy                 x86_64 1.10.0-4.fc31    @fedora 
   149 k
  usbutils                  x86_64 012-3.fc31       @fedora 
   372 k
  zeromq
```

now make new NetVM or check the NetVM based on this fedora and go to 
NetworkManager tray: No internet connection , You cant configure it.

solving this issue will solve the ticket , has no relation to minimal or 
full.



unman:
> I dont think we should provide this, or any such, configuration - there will be users who *dont* want the ordinary user account to be able to control NM.
> In any case:
>> 1.The Minimal TemplateVMs are intended only for advanced users. If you encounter problems with the Minimal TemplateVMs, we recommend that you use their standard TemplateVM counterparts instead.
>> 2.If something works with a standard TemplateVM but not the minimal version, this is most likely due to user error (e.g., a missing package or misconfiguration) rather than a bug. In such cases, you should write to qubes-users to ask for help rather than filing a bug report, then contribute what you learn to the documentation.
> 
>

**Comment by fepitre** [comment]
@unman, I agree as I don't want this neither but, this is not necessary a trivial configuration for all Qubes users. As we also want to move on with a better UX, I would suggest to at least provide a documentation and/or find a way for enabling it "userfriendly". @andrewdavidwong, @marmarek any thoughts?

**Comment by unman** [comment]
@TNTBOMBOM  I did confirm that a standard template will work as sys-net without passwordless-root. Apparently you didnt.
Passwordless-root is included in qubes-vm-recommended - if you want to keep the other packages in that meta-package, just mark them to be held. That is basic package management.
Of course, if you rip out *all* the packages in qubes-vm-recommended, you will  have issues with sys-net, but that wasn't what your issue was about.

**Comment by fepitre** [comment]
After few tests with Marek, it seems that the rule is not needed but only 'polkit' dependency. While testing this morning, I encountered the problem of having the session (loginctl) behing 'online' and not 'active'. I probably have not checked that before restarting the VM itself and went to writing a pkla directly. Polkit seems to configure things properly related to session without any supplementary conf. This is the default behavior related to NM policy.

**Comment by TNTBOMBOM** [comment]
Back to the future, this patch seems to be revoked in qubes 4.2 (in fedora and debian): 

![passwordlessroot](https://github.com/QubesOS/qubes-issues/assets/11895339/dc824cfd-58de-4951-8f0e-49505ace4d6d)

![passwordlessroot2](https://github.com/QubesOS/qubes-issues/assets/11895339/09f852c7-7890-4a30-b93a-7debc0407236)

**Comment by marmarek** [comment]
I don't think anything changed (in unexpected way) here? `qubes-vm-recommended` correctly depends on `qubes-core-agent-passwordless-root`, so when you remove the latter, the former is removed too. Without `qubes-vm-recommended` (so, when you refuse to use recommended setup, that is the one including `qubes-core-agent-passwordless-root`) you may need to manually choose to install (or not remove) packages you want. As Frédéric said above, that's basic package management.

I guess the confusing for you part might be that `dnf` has kinda automatic `apt autoremove` feature. If you don't like it, you can remove it by setting `clean_requirements_on_remove=0` (either in dnf.conf, or one time via cmdline: `--setopt=clean_requirements_on_remove=0`).

**Comment by TNTBOMBOM** [comment]
> I don't think anything changed (in unexpected way) here?

https://github.com/QubesOS/qubes-issues/issues/5836#issuecomment-633953029

Thats what reported before, thats what im reporting again now, please allow the remove of password-less-root package without removing anything else.

Whats happening now (same behavior as the original ticket) if you remove this package it will remove tons of other packages. This is qubes-debian buster version having the old patch:

![buster](https://github.com/QubesOS/qubes-issues/assets/11895339/52117055-c5c5-46d5-ac16-3eb4133bb0ee)

**Comment by marmarek** [comment]
> This is qubes-debian buster version having the old patch:

I don't know where you got this template from (was it maybe started from minimal one?) but it isn't behavior on any of the official debian-10 (or later) templates. I just checked. I guess you don't have `qubes-vm-recommended` package there installed anymore (likely removed earlier, or not installed at all if you started from minimal template).

> remove of password-less-root package without removing anything else.

The behavior on Debian is more or less this already. The `qubes-vm-recommended` package itself doesn't include any functionality itself (it is just meta-package). And `apt`, with options you use, does not remove any other packages (it will, if you run `apt autoremove` without marking which package should stay, but you can simply not call autoremove).

You can get similar behavior on Fedora too, as explained in my previous comment.

As a side note, there is a way to modify `qubes-vm-recommended` (at least on Debian) to use "Recommends", not "Depends" - then it wont be removed. But that will come with major downside as changes in "Recommends" are not considered during update (so added/removed "Recommends" packages won't be properly installed). I'm not going to break common setup to accommodate customized setup that can be achieved other ways (described above).
