### ISSUE TITLE
Linker error trying to build Arch template

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#5844]
**Qubes OS version**
`Qubes release 4.0 (R4.0)`

**Affected component(s) or functionality**
qubes-builder

**Brief summary**
Building the

**To Reproduce**
Try to build Arch Linux template with precompiled packages enabled.

**Expected behavior**
Either the build succeeds, or I get an error explaining what I am doing wrong.

**Actual behavior**
I get a linker error when building XenStore.

**Screenshots**
_If applicable, add screenshots to help explain your problem._

**Additional context**
The 65KB build log is included at the end.

**Solutions you've tried**
Remove chroots and restart

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
_A list of links to the Qubes documentation (or other relevant software documentation) pages you have already consulted._

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
none

**Comment by unman** [comment]
Also affects Bullseye build.

imo we should consider a moratorium on raising issues that affect *any* rolling or unstable/testing distro - it's a constant catchup. If they are raised on mailing list (as this one was) they would get dealt with just the same.

**Comment by fepitre** [comment]
@unman: FYI succeeded to build bullseye and kali few days ago. It remains PR to be merged by Marek for a Qubes build.

**Comment by unman** [comment]
On Sun, May 24, 2020 at 03:52:00AM -0700, Fr??d??ric Pierret wrote:
> @unman: FYI succeeded to build bullseye and kali few days ago. It remains PR to be merged by Marek for a Qubes build.
> 
> -- 
Cool

**Comment by DemiMarie** [comment]
@fepitre would you mind linking the PR in question?

**Comment by neowutran** [comment]
Relevant references
===================
https://github.com/QubesOS/qubes-vmm-xen/pull/77
https://lists.gt.net/xen/changelog/587737

Issue
=====
I have the same issue when I try to build the archlinux template (r4.0) (didn't tried the others yet). 
The patch is not applied correctly. 

Workaround
=================
qubes-vmm-xen is quite complex and i am far from understanding it all. 
However, a reference to this patch file is probably missing. 
Applied the following workaround to my build script 
```
echo "patch-xen-gcc10-fixes.patch" >> "$directory/qubes-src/vmm-xen/series-vm.conf"
```
(Again, this is a workaround, I am far from a correct understanding of qubes-vmm-xen repository, so it is probably not the best solution.)

**Comment by fepitre** [comment]
@DemiMarie: here is the PR https://github.com/QubesOS/qubes-meta-packages/pull/19. But currently we are waiting for packaging dnf for debian. In this case, we would be able to keep the package but in the meantime, you can try bullseye without possibility to use it as UpdateVM.

**Comment by DemiMarie** [comment]
@neowutran That solution worked for me too.

**Comment by lubellier** [comment]
The @neowutran solution solved also my archlinux build...

**Comment by fepitre** [comment]
is this issue still persisting?

**Comment by neowutran** [comment]
good for me, I don't need to manually apply the patch anymore

**Comment by DemiMarie** [comment]
This is fixed.
