### ISSUE TITLE
Log on fails for valid user

### ISSUE THREAD

**Issue by straussmaus** [QubesOS/qubes-issues#5846]
**Qubes OS version**
4.0.3

**Affected component(s) or functionality**
Login, and screensaver login

**Brief summary**
A valid user can not log on using the login at boot, or unlock the screensaver.

**To Reproduce**
_Steps to reproduce the behavior:_
_1. Install 4.0.3 with a user.  Complete installtion
_2. Fail to log on

**Expected behavior**
The valid user and password should log the user on.

**Actual behavior**
The login screen does not go away.

**Additional context**

In the window manager, if I choose "Other" and manually enter the username and password, I can log on.

Hitting ALT-F2 and logging onto the command prompt works.

Logging on after xscreensaver timeout fails.

**Solutions you've tried**
cli login works
manually entering username and password in the window manager works

But this does not solve the problem.  I am locked out of an important function by the screensaver.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
None found

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
None found

**Comment by straussmaus** [comment]
Workaround: log in on cli (ALT-F2) and kill the xscreensaver process.  It works.

**Comment by marmarek** [comment]
Different keyboard layout? caps lock? I would expect issue like this.

**Comment by straussmaus** [comment]
> Different keyboard layout? 

No

> caps lock? 

No.

Right, normal questions to ask but like I said, it works if I manually enter the username instead of choosing it from the  dropdown (and making no other changes, like caps lock or a different keyboard), so it's definitely a bug.

I don't think this is new.  In the past I installed Qubes and could not get in and I thought I must have mistyped my password.  At those times I did not try manually entering the username.  This time I did.  So I think it's not new.

**Comment by marmarek** [comment]
Anything special about your setup? Maybe your username conflicts with something? Can you check logs in dom0 (see `journalctl` command in dom0) after such failed attempts?

**Comment by straussmaus** [comment]
No there is nothing unusual about my setup.  I used this username before on my old system.

Also just now I upgraded dom0 and the problem went away.

Are there older logs I could post to help fix the problem, or should we assume it is resolved completely with a dom0 upgrade?

**Comment by marmarek** [comment]
> Are there older logs I could post to help fix the problem, or should we assume it is resolved completely with a dom0 upgrade?

If it ever happen again, login to dom0 using the other method you mentioned, then execute `sudo journalctl` to get recent logs. Based on timestamps, look for logs related to the issue.

**Comment by straussmaus** [comment]
I am reopening because this happened again after reboot, but I only read this now so I will update when I have that information.

**Comment by straussmaus** [comment]
I had the problem again with the screensaver, so I did `journalctl -xe`and I see pretty normal "authentication failure" and `FAILED LOGIN 1 ON DISPLAY 0:0` with no indication that there is anything unusual.  I can't cut and paste the errors because it's in another session but there is nothing out of the ordinary.

I know, you're thinking that I must have keyboard or typing problems.  I am trying everything like typing slow, and the errors are 100% of the time with the screensaver, and on and off (now that I upgraded dom0) with the window manager login.

I think other people probably have this problem when they install Qubes and they assume they forgot the password they just setup, so they reinstall until this doesn't happen.

**Comment by brendanhoar** [comment]
Is there anything peculiar about your username? E.g. outside of a-zA-Z0-9? Length?

**Comment by straussmaus** [comment]
@brendanhoar 

No, the username is "user" and I used it for a long time on Qubes.  Even on 4.0.3.

**Comment by straussmaus** [comment]
It is not consistent, except on the screensaver which never works.  But once in a while login will work correctly, equally possible is the manual entering of username does not fix but a reboot does, and most often default username use does not work and manual entry does.  It is not preventing use but it is very strange.

**Comment by unman** [comment]
To state the obvious, this is bizarre and (I suspect) particular to @straussmaus - otherwise we'd have seen it before many times. Reports of inability to login are actually quite sparse.
@straussmaus  - what setup do you have? How is the keyboard connected? Do you see typing errors during ordinary use? (I had a USB keyboard once which would occasionally double characters during use, but which more often failed at the screensaver. I just replaced the keyboard without digging further.)

**Comment by straussmaus** [comment]
Can not reproduce since reinstall.  I do not think I was doing anything wrong but I agree with the statement that the most likely problem is user error.

**Comment by straussmaus** [comment]
I did a fresh install and this problem happened again.  I do not believe it is user error.  So I did another fresh reinstall and it worked.
