### ISSUE TITLE
Qubes Builder 4.0 make iso error

### ISSUE THREAD

**Issue by wannabeQuser** [QubesOS/qubes-issues#5847]
**Qubes OS version**
4.0.3

**Affected component(s) or functionality**
Qubes Builder

**Brief summary**
make iso fails

**To Reproduce**
builder.conf

VERBOSE ?= 2

BACKEND_VMM ?= xen

GIT_BASEURL ?= https://github.com
GIT_PREFIX ?= QubesOS/qubes-

RELEASE ?= 4.0

DIST_DOM0 ?= fc25
DISTS_VM ?=

COMPONENTS = \
    installer-qubes-os \
    linux-yum \
    builder-rpm \
    linux-kernel

BUILDER_PLUGINS ?= builder-rpm

USE_QUBES_REPO_VERSION = $(RELEASE)

INSTALLER_KICKSTART=/home/user/qubes-src/installer-qubes-os/conf/iso-full-online.ks

Following https://www.qubes-os.org/doc/qubes-iso-building/

"make iso" returns error

Complete!
-> Building installer-qubes-os iso for fc25
usage: pungi-gather [-h] [--profiler] --arch ARCH --config PATH
                    [--lookaside [REPOID]] [--nodeps] [--selfhosting]
                    [--fulltree] [--greedy METHOD] [--multilib [METHOD]]
pungi-gather: error: unrecognized arguments: --exclude-debug --exclude-source --download-to=/home/user/qubes-src/installer-qubes-os/work/20200525/x86_64/os/Packages
Makefile:86: recipe for target 'iso-installer-gather' failed
make[1]: *** [iso-installer-gather] Error 2
--> build failed!
make: *** [Makefile:538: iso] Error 1

**Comment by marmarek** [comment]
Your configuration is mixing 4.1 and 4.0 parts, especially installer-qubes-os should be from `release4.0` branch. Try adding `BRANCH_installer_qubes_os = release4.0` and re-run `make get-sources`. See also configs in `example-configs` dir.

But also, a better place to ask questions about building is qubes-devel mailing list: https://www.qubes-os.org/support/#qubes-devel

**Comment by wannabeQuser** [comment]
That config is in 4.0 folder https://github.com/QubesOS/qubes-release-configs/blob/master/R4.0/qubes-os-iso-full-online.conf
I don't want to recompile packages. I just need newer kernel.

**Comment by fepitre** [comment]
Adding `linux-kernel` and doing `make iso` directly will not provide you newer kernel. At least you would need to build it by doing `make linux-kernel` after a proper `make get-sources`. The variable `USE_QUBES_REPO_VERSION` instructs the builder to use Qubes official repository for any action in the builder, like creating iso. If you want latest LTS kernel, add `USE_QUBES_REPO_TESTING=1` to your `builder.conf`

**Comment by fepitre** [comment]
BTW, I reproduce the error too. `installer-qubes-os` as not switched the branch to `release4.0`. I'll check what happened.

**Comment by wannabeQuser** [comment]
With config I posted I see kernel-latest-5.6.13 in in rpmbuild folder. It looks what I need.
`make iso COMPONENTS=` gives the same error without restarting everything.
May I ask to give a config that won't cause error with make iso or should I go and open request in google group?
I'm new to linux. Qubes is my first linux OS.

**Comment by fepitre** [comment]
It lacks `BRANCH_installer_qubes_os = release4.0`. Please have a look to example-configs in qubes-builder for more examples.

Moreover, before posting any issue/help on qubes-devel/users please have look to history. This question has been answered many times. Look *all* the thread in https://groups.google.com/d/msgid/qubes-users/6316622e-743c-4bc8-98e9-8ca7938c6c5c%40googlegroups.com?utm_medium=email&utm_source=footer. Another thing, you don't need to rebuild kernel as it's already built in Qubes repository. Please note we provide two type kernels: `kernel` and `kernel-latest`. The first one is LTS, currently 5.4.X, the second one is stable kernel, currently 5.6.X. We don't have easy procedure for building a full iso including only `kernel-latest`. Do you have any specific issue for not using Qubes OS ISO then upgrading to 5.6.X?

**Comment by wannabeQuser** [comment]
Yes, I have an issue with current kernel. It doesn't support driver for a storage device to which I want to install Qubes. I need kernel > 5.4. 
I mentioned that this config still uses old kernel for initramfs.  How to fix that?
I'll add `BRANCH_installer_qubes_os = release4.0` and start over.
