### ISSUE TITLE
RuntimeError: the PyQt4.QtCore and PyQt5.QtCore modules both wrap the QObject class

### ISSUE THREAD

**Issue by Osndok** [QubesOS/qubes-issues#5849]
**Qubes OS version**
`Qubes release 4.0 (R4.0)`

**Affected component(s) or functionality**
qubes-qube-manager
qubes-template-manager

**Brief summary**
Installing an app that depends on `python3-qt5` breaks the qube-manager & template-manager launch scripts.

**To Reproduce**
1. Open a `dom0` terminal
2. Execute: `sudo qubes-dom0-update python3-qt5`
3. Execute: `qubes-qube-manager`
4. See error (copied below)

**Expected behavior**
Installing other tools into dom0 should not break qubes tools.

**Actual behavior**
Installing python-based qt5 tools breaks at least two qubes apps.

**Screenshots**
```
[user@dom0 ~]$ qubes-qube-manager 
Traceback (most recent call last):
  File "/usr/bin/qubes-qube-manager", line 9, in <module>
    load_entry_point('qubesmanager==4.0.41', 'console_scripts', 'qubes-qube-manager')()
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2575, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2235, in load
    return self.resolve()
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2241, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.5/site-packages/qubesmanager/qube_manager.py", line 40, in <module>
    from PyQt4 import QtGui  # pylint: disable=import-error
RuntimeError: the PyQt4.QtCore and PyQt5.QtCore modules both wrap the QObject class
```

**Additional context**
The `python3-qt5` package brings in about 80mb of dependencies, but I'm pretty sure that it is the one that is actually disrupting the qubes apps.

**Solutions you've tried**
Executing `sudo dnf remove python3-qt5` can be used to temporarily workaround the issue. I suspect that one could use a harsher `rpm` command to remove only that package without dependencies to get the same effect (while leaving the system in an inconsistent state).

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
I have not consulted any Qubes documentation about this issue.

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

Other qt5 issue?
* #5354
* #5348
* #5278

**Comment by marmarek** [comment]
AFAIR quamash module loads qt5 when available, but qubes manager in R4.0 uses qt4. There was a method to force specific version, @marmarta do you remember how? Can you put that into qubes manager code (into release4.0 branch)? I assume it applies to all applications in qubes-manager repository (all are pyqt based).

**Comment by marmarek** [comment]
Fixed in https://github.com/QubesOS/qubes-manager/pull/237
