### ISSUE TITLE
thinkpad install instructions do not work with recent fedora

### ISSUE THREAD

**Issue by raedah** [QubesOS/qubes-issues#5851]
Install fails on thinkpads. This appears to be a known issue as it is documented in here  https://www.qubes-os.org/doc/thinkpad-troubleshooting/ and starts by stating the issue "Newer ThinkPads (e.g. T470, T470p, ThinkPad 25) are likely to fail installation attempts made from a USB stick that was created with dd"

The problem is that the documentation instructions for how to work around this are no longer valid with recent versions of  livecd-iso-to-disk . Upon running the cmd, the error is 
"Unable to find an EFI configuration file."

**Comment by raedah** [comment]
Solution seems to be that the regular Qubes usb installer works fine, the thinkpad troubleshootin document is unnecessary and misleading.

**Comment by raedah** [comment]
will also mention someone elses comment
"There is a typo in the docs, you need to edit EFI/BOOT/BOOTX64.cfg, not EFI/BOOT/xen.cfg"

**Comment by dmoerner** [comment]
I don't have any new enough Thinkpads to test this. But I was able to use `livecd-iso-to-disk` from Fedora 32 to make a bootable USB stick for a T460. I got the message "Unable to find an EFI configuration file", but that's not an error: Line 1845 of the script makes clear that it's only testing for grub.cfg, and so it doesn't recognize that R4.0 is booting xen.efi directly.

As I mentioned on IRC, there is a typo in https://www.qubes-os.org/doc/thinkpad-troubleshooting/,  it should be EFI/BOOT/BOOTX64.cfg, not EFI/BOOT/xen.cfg.

There is still a question, though, about whether the workaround in the docs is still necessary. @raedah, exactly what Thinkpad model did you test this on?

**Comment by raedah** [comment]
I did the install on a P53

**Comment by andrewdavidwong** [comment]
Please consider submitting a pull request (PR) to help improve the documentation. In case you (or anyone else reading this) is not already aware, the documentation is a community effort, and everyone is welcome to contribute. (That's how things like this get updated!) So, if you'd like to get involved with the project, this is a great way to do it. You can read more about how to submit documentation changes here:

https://www.qubes-os.org/doc/doc-guidelines/

**Comment by andrewdavidwong** [comment]
https://github.com/QubesOS/qubes-doc/pull/1014 indicates that it closes this issue. If anyone believes the issue is not yet resolved, or if anyone is still affected by this issue, please leave a comment, and we'll be happy to reopen this. Thank you.
