### ISSUE TITLE
xfce problem with volume - + 

### ISSUE THREAD

**Issue by gulyaev-artem** [QubesOS/qubes-issues#5858]
**Qubes OS version**
R4.0
dell xps 15 9560

**Affected component(s) or functionality**
xfce brightness 

**Brief summary**
I have f11 and f12 keys for setting suitable brightness. But ~2weeks ago this function was broken. When key is pressing I can see a notification in the bottom right angle but the brightness is not adjustable.

**To Reproduce**
_Steps to reproduce the behavior:_
_1._ Press f11 or f12

**Expected behavior**
Increase or decrease brightness

**Actual behavior**
doing nothing

**Solutions you've tried**
Set brightness via driver in /sys/devices/pci0000:00/0000:00:02.0/drm/card0/card0-eDP-1/intel_backlight/brightness

**Comment by Aporbel** [comment]
still does not work

**Comment by rapenne-s** [comment]
Could you try on R4.1 with latest kernel?

**Comment by andrewdavidwong** [comment]
Closing as "cannot reproduce" (we were unable to reproduce this issue). If anyone believes this is a mistake, or if anyone can reproduce the issue, please leave a comment, and we'll be happy to reopen this. Thank you.
