### ISSUE TITLE
timedatectl shows RTC time synced to local time and breaks OTP under Heads (Which thinks is UTC)

### ISSUE THREAD

**Issue by tlaurion** [QubesOS/qubes-issues#5859]
**Qubes OS version**
Qubes 4.0.3 installation media

`qvm-sync-clock `and `timedatectl`

**Brief summary**
UTC and local time are the same.

When syncing time externally, the next timedatectl invocation on dom0 reports:
`If at all possible, use RTC in UTC by calling 'timedatectl set-local-rtc 0'`

Which, when invoked and following through with https://www.qubes-os.org/doc/change-time-zone/ works.

New behavior having Heads showing local time instead of UTC time was unexpected. Do not know source of change. 

**To Reproduce**
1-Invoque timedatctl from dom0
2- See that UTC and Local time are the same.

**Expected behavior**
Local time and RTC should be different, and RTC being UTC. 
Unless one's live in UTC or GMT timezone, RTC UTC and local time could be the same.
Else RTC should be UTC.

**Actual behavior**
RTC and Local time are the same unless 'timedatectl set-local-rtc 0' is called, followed by `sudo qvm-sync-clock`

**Comment by marmarek** [comment]
What exact output of `timedatectl` do you have? Is that a fresh install, or older+updates?

**Comment by tlaurion** [comment]
> What exact output of `timedatectl` do you have? Is that a fresh install, or older+updates?

Fresh. I corrected the flaw already with `timedatectl set-local-rtc 0` but I expect you have the same behavior on PrivacyBeast X230.

Can provide you output if required? But it was LOCAL=RTC, which is clearly not desired.

**Comment by tlaurion** [comment]
@marmarek 

- Qubes Global settings clock vm: sys-net
- sys-net connected to wifi
`timedatecl`:
![LocalIsRTC](https://user-images.githubusercontent.com/827570/83282630-e1e96080-a1a7-11ea-8d1c-2ec0592d4d60.jpeg)
After applying `timedatectl set-local-rtc 0` and running `sudo qvm-sync-clock`
![RTCisUTCfixedAndSynced](https://user-images.githubusercontent.com/827570/83282602-d85ff880-a1a7-11ea-953f-b66b12940f64.jpeg)
