### ISSUE TITLE
Error downloading python-xcffib

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#5860]
**Qubes OS version**
`Qubes release 4.0 (R4.0)`

**Affected component(s) or functionality**
qubes-builder

**Brief summary**
Downloading python-xcffib fails

**To Reproduce**
Run `make get-sources`

**Expected behavior**
It succeeds

**Actual behavior**
It fails trying to download python-xcffib

**Screenshots**
N/A

**Additional context**
I am not sure if this breaks the overall build

**Solutions you've tried**
Cleaning and building from scratch

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
https://www.qubes-os.org/doc/building-archlinux-template/

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
none

**Comment by unman** [comment]
Works for me.
Are you trying to build Arch? Dom0? Any other templates?
A little more information would be useful.

**Comment by DemiMarie** [comment]
Arch only

**Comment by unman** [comment]
On Sun, May 31, 2020 at 06:16:00PM -0700, Demi Marie Obenour wrote:
> Arch only
> 

python-xcffib is pulled down with dom0 selected, not if only building
templates.
In any case, works for me.
