### ISSUE TITLE
Windows GUI Driver May Cause a You "attempted to perform an invalid or suspicious GUI request" Message Box to Appear

### ISSUE THREAD

**Issue by ElliotKillick** [QubesOS/qubes-issues#5864]
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
Most likely the Windows GUI `qvideo` driver. It's also possible that the method for detecting an "invalid or suspicious GUI request" needs to be adjusted.

**Brief summary**
A message box in Dom0/GuiVM may appear saying that you "attempted to perform an invalid or suspicious GUI request" may appear when the `qvideo` driver is in use by Windows. This seems to happen especially when the Windows qube first boots so maybe it's something to do with the logon screen.

Note, the `qvideo` driver currently only supports Windows 7/Server 2008.

**To Reproduce**
1. Boot Windows installed with the `qvideo` driver
2. The aforementioned message box may appear in Dom0/GuiVM

**Expected behavior**
Windows with the `qvideo` driver should never "perform an invalid or suspicious GUI request."

**Actual behavior**
Windows may "perform an invalid or suspicious GUI request."

**Additional context**
In the context of [qvm-create-windows-qube](https://github.com/elliotkillick/qvm-create-windows-qube), this causes the qube and as a result the entire automatic Windows qube installation to pause. Perhaps related to https://github.com/QubesOS/qubes-issues/issues/1044? Nobody is maintaining Qubes Windows Tools right now so this is mostly just to track the issue.

**Comment by elliotkillick** [comment]
Note that this rarely happens, so it's by no means a high priority issue.
