### ISSUE TITLE
Consider changing 'Domain' to 'Area' for (non-tech) users

### ISSUE THREAD

**Issue by imme-emosol** [QubesOS/qubes-issues#5865]
#5839 has a [side note](/QubesOS/qubes-issues/issues/5839#issuecomment-632870450):
> standardizing terms w/in the UI and w/in documentation, to either "Domain" or "App VM."

There in #5839 and in #5676 there are these two sketches:
<table><tbody><tr valign="top">
<td><img src="https://user-images.githubusercontent.com/8262612/74997021-fb8d4600-5409-11ea-8d46-638d558df44a.png" /></td>
<td><img src="https://user-images.githubusercontent.com/8262612/82702475-ee5d3e80-9c26-11ea-9597-a91e5227f953.png" /></td>
</tr></tbody></table>

Given that context, when I see it in the menu in the sketches, it stands out to me;
seeing domains under "Disposable VMs" and then dom0 under "Domains".

Also, Security Domain/Context/Realm .. "domain" may indeed be hard to grasp for end-users.
Perhaps a term such as 'Context', or keeping somewhat within geometry; 'Area', would be easier understood?
<table><tbody>
<tr><td>Area: work,</td><td>Context: safe browsing,</td></tr>
<tr><td>Area: mail,</td><td>Context: banking,</td></tr>
<tr><td>Area: work-mail.</td><td>Context: financial-administration.</td></tr>
</tbody></table>

Looking into this, I found that apparently 'Area' is also in line with the second word explaining 'domain' in the glossary, on https://www.qubes-os.org/doc/glossary/#domain :
<blockquote>[Domain:] An area or set of activities in one’s digital life that has certain security requirements and therefore involves the use of certain qubes. For example, suppose your “email” domain encompasses the activity of sending PGP-encrypted email. This domain may include your email qube and your Split GPG qube. Note that domains and qubes are not the same thing. In this example, your “email” domain includes the use of two qubes. Furthermore, a qube can fall under multiple domains simultaneously. For example, your Split GPG qube may also be part of your “software development” domain if you PGP-sign your Git commits.
</blockquote>
Coincedence? I think not ;)

So what do you think of replacing the word 'domain' for the word 'area' for end-users?
Another option would be 'context' though that's a rather broad term.
The advantage of either 'context' or 'area' over 'domain' is that either of those doesn't bring the connotation of 'domain name' with it.

In a menu, users would be "confronted" with four groupings;
Areas, Templates, Services, Temporary/Disposable Areas.

N.B. this is related to #1015, but not about changing the wording for 'AppVM' or 'qube', so I created a new issue for this.

**Comment by unman** [comment]
On Fri, May 29, 2020 at 11:25:30AM -0700, imme??mosol wrote:
> #5839 has a [side note](/QubesOS/qubes-issues/issues/5839#issuecomment-632870450):
> > standardizing terms w/in the UI and w/in documentation, to either "Domain" or "App VM."
> 
> There in #5839 and in #5676 there are these two sketches:
> <table><tbody><tr valign="top">
> <td><img src="https://user-images.githubusercontent.com/8262612/74997021-fb8d4600-5409-11ea-8d46-638d558df44a.png" /></td>
> <td><img src="https://user-images.githubusercontent.com/8262612/82702475-ee5d3e80-9c26-11ea-9597-a91e5227f953.png" /></td>
> </tr></tbody></table>
> 
> Given that context, when I see it in the menu in the sketches, it stands out to me;
> seeing domains under "Disposable VMs" and then dom0 under "Domains".
> 
> Also, Security Domain/Context/Realm .. "domain" may indeed be hard to grasp for end-users.
> Perhaps a term such as 'Context', or keeping somewhat within geometry; 'Area', would be easier understood?
> <table><tbody>
> <tr><td>Area: work,</td><td>Context: safe browsing,</td></tr>
> <tr><td>Area: mail,</td><td>Context: banking,</td></tr>
> <tr><td>Area: work-mail.</td><td>Context: financial-administration.</td></tr>
> </tbody></table>
> 
> Looking into this, I found that apparently 'Area' is also in line with the second word explaining 'domain' in the glossary, on https://www.qubes-os.org/doc/glossary/#domain :
> <blockquote>[Domain:] An area or set of activities in one???s digital life that has certain security requirements and therefore involves the use of certain qubes. For example, suppose your ???email??? domain encompasses the activity of sending PGP-encrypted email. This domain may include your email qube and your Split GPG qube. Note that domains and qubes are not the same thing. In this example, your ???email??? domain includes the use of two qubes. Furthermore, a qube can fall under multiple domains simultaneously. For example, your Split GPG qube may also be part of your ???software development??? domain if you PGP-sign your Git commits.
> </blockquote>
> Coincedence? I think not ;)
> 
> So what do you think of replacing the word 'domain' for the word 'area' for end-users?
> Another option would be 'context' though that's a rather broad term.
> The advantage of either 'context' or 'area' over 'domain' is that either of those doesn't bring the connotation of 'domain name' with it.
> 
> In a menu, users would be "confronted" with four groupings;
> Areas, Templates, Services, Temporary/Disposable Areas.
> 
> N.B. this is related to #1015, but not about changing the wording for 'AppVM' or 'qube', so I created a new issue for this.
> 

Is there any evidence that users are confused by:
a) `Domain` appearing in Menu 
b) `Domain` as a state of art term in Qubes?

In my experience, end users are not worried by either - particularly as
they can edit menus to make (a) cohere with (b). Sometimes I do this for
them.
I'm not sure "area" would bring anything new.

**Comment by andrewdavidwong** [comment]
There's nothing wrong with the term "domain."

The only problem I see here is that the menu (in that screenshot) has a subsection called "Domains," but there are domains under other subsections. This is just an organizational problem with the menu.

To address some of the specific points raised:

> Given that context, when I see it in the menu in the sketches, it stands out to me;
seeing domains under "Disposable VMs" and then dom0 under "Domains".

This is an organizational inconsistency, not a problem with terminology.

> Also, Security Domain/Context/Realm .. "domain" may indeed be hard to grasp for end-users.
Perhaps a term such as 'Context', or keeping somewhat within geometry; 'Area', would be easier understood?

I see no evidence that the term "domain" is any more confusing to end users than "context" or "area" would be.

> Looking into this, I found that apparently 'Area' is also in line with the second word explaining 'domain' in the glossary [...] Coincedence? I think not ;)

I wrote that entry. The fact that the word "area" is used in the definition does not mean that it would be a better term.

> The advantage of either 'context' or 'area' over 'domain' is that either of those doesn't bring the connotation of 'domain name' with it.

I've never heard of this being a problem. Is there any evidence that anyone is confused by this?

**Comment by imme-emosol** [comment]
There is indeed nothing wrong with the term.
The issue is a suggestion for improvement,
not about something being wrong.

This issue was made to provide a suggestion for a problem I see arising with a growing diversity of people that will try to use (and understand) QubesOS. Of course this is just my interpretation and you are more than welcome to dismiss that and close this issue.

By the way, both responses, asking me for evidence, make me feel like I should not have made this suggestion or at least not in this context. I am letting you know that, since it seems to contradict what I read on [the reporting bugs page](https://www.qubes-os.org/doc/reporting-bugs/#every-issue-must-be-of-a-single-type). Perhaps this should have been posted to a mailing list?

"WARNING" If you are _not really interested_ in continuing this issue,
then continuing to read this text will probably be a waste of your time.

----
To clarify, the suggestion is made in an attempt to make a clearer distinction between the concept of grouping qubes and technical terms or anything else for that matter, especially within QubesOS's own documentation, visuals (QubesOS's "user landscape").

Some observations (emphasis mine):
- The [Glossary section about domain](https://www.qubes-os.org/doc/glossary/#domain) contains: «Note that **domains and qubes are not the same thing**. In this example, your “email” domain includes the use of two qubes. Furthermore, a qube can fall under multiple domains simultaneously.»
- The [/intro/ page](https://www.qubes-os.org/intro/) contains: «**Qubes**, which are also **referred to as domains** or compartments»
- The [getting started page](https://www.qubes-os.org/getting-started/) contains: «each **qube _represents_** a security **domain**», «you might use the colors to show that **qubes belong to** the same **domain**», «there’s **one special domain** called “dom0,”», «**Dom0 is** more trusted than any other **domain** (including **TemplateVMs** and black-labeled **qubes**).»

According to me:
- These texts divided over three pages do not exactly contradict eachother.
- These texts divided over three pages do not exactly agree with eachother.

So, those texts confuse me, I have to think about them and determine when I think what is intended and then hope that I determined that correctly.
The texts left me with these observations:
- The term domain (outside of QubesOS) has several meanings, for instance a domain of expertise, or a domain on which a webserver can be reached.
- The term domain (as used in QubesOS documentation I have read) sometimes refers to the xen-type of a domain, sometimes it means some sort of grouping/color, sometimes it means a security context.
- You can assign colors to qubes and make up your mind about what that colors mean. A suggestion is to use the colors to indicate the level of security of such a qube. Another suggestion seems to be to use the colors to indicate the area in which the qube falls, such as 'work' or 'personal'.
- A domain (as defined in the glossary) is not something I can see within QubesOS. There is no image or textual thing for them. It is hinted that colors provide that information. That seems unlikely to be true, since it is possible for a qube to fall into multiple domains but as far as I know, only one of the colors can be assigned to a qube.

Sorry for the long text, I feel to have been misunderstood and tried to make it more clear. Hopefully it will lead to an improvement for QubesOS.

**Comment by ninavizz** [comment]
Thank you for this issue @imme-emosol! I'm also learning Qubes, while doing design work and user research to improve it. This week is rather busy for me, but I really look forward to digging into this issue and your thoughts, some more, hopefully next week. Thank you for all your thinking through this problem!

**Comment by unman** [comment]
On Tue, Jun 02, 2020 at 02:44:07PM -0700, imme??mosol wrote:
> There is indeed nothing wrong with the term.
> The issue is a suggestion for improvement,
> not about something being wrong.
> 
> This issue was made to provide a suggestion for a problem I see arising with a growing diversity of people that will try to use (and understand) QubesOS. Of course this is just my interpretation and you are more than welcome to dismiss that and close this issue.
>

I completely agree that the use of the term "domain" *may* be confusing
- in my experience, it isn't. That's why I have asked for some evidence.
It isn't an attack on you or your approach, and shouldn't be taken
personally - just a suggestion that we move forward addressing matters
that cause genuine confusion.

On the points you raise - revamping the menus is probably a good
opportunity to remove the term "Domain" from there - although, as I have
said, from working with a good number of new users NONE of them has
found this a source of confusion.
The `intro` page is just wrong, and should be corrected. Within ordinary
Qubes use I don't think I have *ever* seen qubes referred to as Domains
or compartments.
Again, the getting started page needs more clarity, but it's intended to
cover a range of different use cases with suggestions for how one might
want to go on.
Remember that these are general introduction pages.

On your final observations, I probably agree with them, excepting the
last. That is, I know people whose systems **do** show the use of
domains as per the glossary, and you would recognise that. The flexibility
of Qubes (excepting restrictions on range of colour/indicators) allows
that to be done.
Again, in my experience, it's through *use* that one becomes comfortable
with organising qubes. Introducing a new term of art wont help with
that.

**Comment by andrewdavidwong** [comment]
> By the way, both responses, asking me for evidence, make me feel like I should not have made this suggestion or at least not in this context. I am letting you know that, since it seems to contradict what I read on the reporting bugs page. Perhaps this should have been posted to a mailing list?

It's simply that empirical claims require empirical evidence. Please do not misinterpret the request for evidence as discouraging suggestions or anything like that. It's just a way to be direct and get to the heart of the matter. It should not be interpreted as bearing any negative emotional affect.

> These texts divided over three pages do not exactly agree with eachother.

Yes, you're quite right. This is the result of different pages being written by different people, and some being old and stale while others were more recently updated. The Intro page needs to be updated. The Getting Started page is being imprecise, but that's probably forgivable for such a page.

> A domain (as defined in the glossary) is not something I can see within QubesOS. There is no image or textual thing for them. It is hinted that colors provide that information. That seems unlikely to be true, since it is possible for a qube to fall into multiple domains but as far as I know, only one of the colors can be assigned to a qube.

I think this is a fair point. Perhaps the concept of a domain in Qubes (regardless of the term we use to pick out that concept) isn't very useful and could be abandoned without much loss.

**Comment by ninavizz** [comment]
When we do user testing with end users, there are ways to learn from them what concepts and words might feel natural to them. I'd rather work towards what _feels natural_ to users, vs what makes the most sense from a linguistics or mathematical concepts POV. Really looking forward to digging-in to the app menu, in the weeks ahead; user testing should be fun, to learn more about these things! Thanks all, for the thoughts above. :)
