### ISSUE TITLE
qvm-copy * fails but cd ..;qvm-copy * succeeds

### ISSUE THREAD

**Issue by brendanhoar** [QubesOS/qubes-issues#5870]
**Qubes OS version**
Qubes 4.0.3 current-testing

**Affected component(s) or functionality**
qvm-copy

**Brief summary**
qvm-copy fails with "qfile-agent: Fatal error: chdir to (null) (error type: No such file or directory)"

**To Reproduce**

```
[admin@dom0 ~]$ cd /var/log/qubes
[admin@dom0 ~]$ qvm-copy-to-vm *
```

Go to target VM
```
user@disp6466:~$ cd QubesIncoming/dom0
user@disp6466:~/QubesIncoming/dom0$ qvm-copy *
qfile-agent: Fatal error: chdir to (null) (error type: No such file or directory)
EOF
user@disp6466:~/QubesIncoming/dom0$ qvm-copy *
qfile-agent: Fatal error: chdir to (null) (error type: No such file or directory)
EOF
user@disp6466:~/QubesIncoming/dom0$ cd ..
user@disp6466:~/QubesIncoming$ ls
dom0
user@disp6466:~/QubesIncoming$ qvm-copy *
sent 2180546/2180683 KB
```

**Expected behavior**
Regardless of number of files and/or names of files, they copy

**Actual behavior**
Files can be copied, but sometimes the process has to be guarded by only passing the enclosing directory above the files to the qvm-copy command.

Notably, the issue did not arise with qvm-copy-to-vm in dom0, only with qvm-copy in a domU.

**Comment by SaswatPadhi** [comment]
I couldn't reproduce this issue ...
I am running Qubes 4.0.3 as well. I tried the exact same commands and used a DispVM as a target VM -- each step ran without any error though.

**Comment by brendanhoar** [comment]
I currently have a total of 3240 files in /var/log/qubes. I also manually trimmed this directory a couple of weeks ago.
