### ISSUE TITLE
Installer crash on Dell G3 3579

### ISSUE THREAD

**Issue by MassiveBattlebotsFan** [QubesOS/qubes-issues#5871]
**Qubes OS version**
R4.0.3

**Affected component(s) or functionality**
QubesOS and QubesOS installer 

**Brief summary**
I'm running Qubes installer on a usb flash drive on a Dell G3 3579 with an Intel i7 8th gen 8750H cpu, Nvidia Geforce GTX gpu, and 16 GB of RAM. Qubes installer will load to the page where you pick your drive, and then it crashes. When I ran Qubes after installing on an external HDD, it booted, and then crashed. 

**To Reproduce**
On Dell G3 3579, run Qubes installer or QubesOS. It will crash after ~30 seconds.

**Expected behavior**
I expect for Qubes to install when running the installer, and boot the OS when running it.

**Actual behavior**
It crashed.

**Screenshots**
None, sorry.

**Additional context**
The Dell G3 isn't on the supported hardware list, but it supports VT-d and VT-x.

**Solutions you've tried**
Everything from modifying arguments to installing on a different computer.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
There is nothing as far as I can tell.

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
None.

**Comment by F1nnM** [comment]
I'd also love to use Qubes on this Laptop and ran into the same issue half a year ago. Any updates so far?

**Comment by F1nnM** [comment]
If you need me to try something on that laptop or supply some logs or something similar, give me a ping. If I can do anything to be able to use Qubes sooner, I'd gladly help.
