### ISSUE TITLE
PCE AC88 (driver : brcmfmac4366c-pcie.bin)

### ISSUE THREAD

**Issue by Lailouezzz** [QubesOS/qubes-issues#5872]
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
Configuration/first boot

**Brief summary**
Freeze when configuration at "Setting up network" and after a forced reboot qubesOS freeze with only mouse pointer not movable

**To Reproduce**
1- Install a PCE-AC88 on your machine
2- Try to install qubesOS

**Expected behavior**
I want to boot on qubesOS x)

**Actual behavior**
Freezing

**Additional context**
The context is simple : I have a PCE AC88 wifi card who isn't supported by the most linux distributions. With Debian/Ubuntu etc... In the installation I switch on a terminal for copy the driver in /lib/firmware/brcm for the installation works.
So I think beceause of the configuration freeze at the network settings up, I think that beceause the driver is not found, and without my wifi card the qubes OS works (so I can install the driver manualy)

**Comment by Lailouezzz** [comment]
I've tried install without my card in PC, and I put my card after installation, all right. But I has not wifi (beceause of no PCI passthrough with sys-net), so I shutdown sys-net I add my card in the devices PCI (qubes settings) and I run sys-net... and freezing, I can't do anything I'm blocked

**Comment by Lailouezzz** [comment]
I will try to add a brcmfmac4366c-pcie.txt file (which is not necessary but that all distributions require to run brcmfmac4366c-pcie.bin)

**Comment by Lailouezzz** [comment]
I've tried to unload brcm driver of dom0 before run sys-net but not work

**Comment by Lailouezzz** [comment]
Ok so I have tried to create a Windows qubes, after windows installation I have been add my wifi card in devices for pci passthrough and the same result : QubesOS freeze instantly and I can't do anything I tried to look journalctl -b -1 but the log stop at the starting qubes and no error was showed
I tried to pci passthrough another devices in a fedora qubes (my intel ethernet card) and that's work, so WHY my wifi card won't works x)

**Comment by xaki23** [comment]
> so WHY my wifi card won't works x)

because (as you are aware since you mentioned it in the initial post here), you have a really bad wifi card.

this seems to be a dupe of https://github.com/QubesOS/qubes-issues/issues/3734

**Comment by Lailouezzz** [comment]
> because (as you are aware since you mentioned it in the initial post here), you have a really bad wifi card.

It's just a wifi card  no widespread so it's a hassle with the drivers. I close the issue because it is too localized a problem so I posted in qubes-users sorry for the inconvenience

**Comment by Lailouezzz** [comment]
> because (as you are aware since you mentioned it in the initial post here), you have a really bad wifi card.

It's just a wifi card  no widespread so it's a hassle with the drivers. I close the issue because it is too localized a problem so I posted in qubes-users sorry for the inconvenience
