### ISSUE TITLE
Dom0 doesn't have non-lating fonts

### ISSUE THREAD

**Issue by graudeejs** [QubesOS/qubes-issues#5874]
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
Dom0

**Brief summary**
non-latin fonts are missing

**To Reproduce**
_Steps to reproduce the behavior:_
_1. Open firefox in DomU and open site with title having non-latin characters (https://translit.ru/ for example)

**Expected behavior**
Taskbar and window titlebar should render non-latin characters

**Actual behavior**
Taskbar and window titlebar renders underlines

**Screenshots**
![image](https://user-images.githubusercontent.com/1020124/83654478-dc37b480-a5c5-11ea-9189-d3d6513db52e.png)

**Additional context**
none

**Solutions you've tried**
Haven't tried anything, It's my 2nd day with Qubes

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
none

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
none

**Comment by marmarek** [comment]
It's not about missing fonts, it's about preventing non-ASCII characters by default (eliminate all kinds of UTF-8 parsing and rendering bugs). But it's configurable, see https://github.com/QubesOS/qubes-issues/issues/1059

**Comment by graudeejs** [comment]
Thanks. That makes sense. I enabled this setting for personal and work vms.
