### ISSUE TITLE
split-gpg will break in Thunderbird 78

### ISSUE THREAD

**Issue by mfc** [QubesOS/qubes-issues#5877]
creating separate ticket from [this](https://github.com/QubesOS/qubes-issues/issues/5861#issuecomment-638223717)

**Qubes OS version**
R4.0

**Affected component(s) or functionality**
`qubes-app-linux-split-gpg`

**Brief summary**
https://blog.thunderbird.net/2019/10/thunderbird-enigmail-and-openpgp/

Thunderbird 78.0 is scheduled for June 30 release: 

* https://mail.mozilla.org/pipermail/tb-planning/2020-May/007621.html
* https://mail.mozilla.org/pipermail/tb-planning/2020-May/007626.html

**Proposed solutions**
https://bugzilla.mozilla.org/show_bug.cgi?id=1642614
https://phabricator.services.mozilla.com/D77805

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
https://www.qubes-os.org/doc/split-gpg/

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
https://github.com/QubesOS/qubes-issues/issues/5861

**Comment by mfc** [comment]
Mozilla is currently seeking testers to confirm whether their fixes for beta 78 work for split-gpg:
* https://bugzilla.mozilla.org/show_bug.cgi?id=1642614
* https://phabricator.services.mozilla.com/D77805

**Comment by marmarek** [comment]
Adding --unwrap shouldn't be a problem. I don't have mozilla bugzilla account (yet) to comment there.

**Comment by marmarek** [comment]
version 2.0.46 of split-gpg just uploaded to current-testing repository includes --unwrap option.

**Comment by mfc** [comment]
thanks Marek. still getting the [same error message in TB](https://bugzilla.mozilla.org/show_bug.cgi?id=1642614#c18) unfortunately

**Comment by mfc** [comment]
FYI I am testing this on Debian 10. on Fedora 31 [tbird is not finding `gpgme` (`libgpgme.so`) even though it is installed](https://bugzilla.mozilla.org/show_bug.cgi?id=1642614#c19).

**Comment by mfc** [comment]
FYI their current 68+Enigmail->78 transition time: https://mail.mozilla.org/pipermail/tb-planning/2020-June/007669.html

end of July at the earliest, flexibility built in until 68 EOL in September

**Comment by mfc** [comment]
[latest TB build now works](https://bugzilla.mozilla.org/show_bug.cgi?id=1642614#c39). closing, please re-open if anyone else tests and has split-gpg issues.

**Comment by yg-ht** [comment]
I am attempting to do an upgrade from an existing enigmail / Thunderbird install and having followed the documentation I am still getting problems.  Struggling to find any meaningful debug output as well, so any pointers on that would be appreciated.  What I have found in the Error Console is this one solitary line:

`cannot decrypt message decryption.jsm:528:15`

I have tested that the qubes-gpg-client-wrapper tool is still working by copying the PGP clock into a file and decrypting that with "-d".  I have also uninstalled enigmail in Thunderbird in case there was any conflict.  Any pointers would be appreciated and if there are additional steps required for upgrades rather than new installs.  Happy to update docs when complete too.  Thank you in advance!

**Comment by andrewdavidwong** [comment]
> I am attempting to do an upgrade from an existing enigmail / Thunderbird install and having followed the documentation I am still getting problems. Struggling to find any meaningful debug output as well, so any pointers on that would be appreciated. What I have found in the Error Console is this one solitary line:
> 
> `cannot decrypt message decryption.jsm:528:15`
> 
> In TB itself I get the error "the secret key that is required to decrypt this message is not available" and nothing else.
> 
> I have tested that the qubes-gpg-client-wrapper tool is still working by copying the PGP clock into a file and decrypting that with "-d". I have also uninstalled enigmail in Thunderbird in case there was any conflict. Any pointers would be appreciated and if there are additional steps required for upgrades rather than new installs. Happy to update docs when complete too. Thank you in advance!

This sounds like more of a support request. Please send it to the appropriate venue:

https://www.qubes-os.org/support/

**Comment by SvenSemmler** [comment]
Had the same issue. You need to install libgpgme11 on debian (probably 
the same on Fedora).
