### ISSUE TITLE
Bad signature for Xen tarball

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#5878]
**Qubes OS version**
`Qubes release 4.0 (R4.0)`

**Affected component(s) or functionality**
Qubes builder

**Brief summary**
`make get-sources` fails with `Wrong signature on xen-4.8.5.tar.gz.UNTRUSTED!`

**To Reproduce**
1. Fetch, verify, and checkout qubes-builder.
2. Run `make get-sources`

**Expected behavior**
All components fetched successfully.

**Actual behavior**
`Wrong signature on xen-4.8.5.tar.gz.UNTRUSTED!`

**Screenshots**
N/A

**Additional context**
I have had problems with qubes-builder in the past, but not this problem.

**Solutions you've tried**
Retrying the build later

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
N/A

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
#5860

**Comment by marmarek** [comment]
Check if it isn't download failure, like the file cut short.

**Comment by DemiMarie** [comment]
This was due to the signature being truncated, IIRC.  In any case, this isn’t a bug in qubes-builder.
