### ISSUE TITLE
ejecting (duplicate) .img mounts detaches unrelated USB drive automatically

### ISSUE THREAD

**Issue by ghost** [QubesOS/qubes-issues#5879]
**Qubes OS version**
4.0

**Affected component(s) or functionality**
File manager
Devices manager

**Brief summary**
.img files seem to mount twice in the vm; unmounting one or both causes an attached SD card reader to be dismounted as well.

**To Reproduce**
_Steps to reproduce the behavior:_
_1. mount an image file using Image Mounter via nautilus; (quite possibly not the first time for that image during a couple of hours' workflow).
_2. attach (not mount, necessarily) a usb drive
_3. use 'eject' button in navigator pane on one or both .img mounts
_4. See usb drive detach

**Expected behavior**
1. One img, one mount point.
2. System should remember that mount point for that .img (there were no restarts of vm).
3. ejecting one or two .img mounts should NOT trigger usb detachment.

**Actual behavior**
System provided two mount points, for the same image, but - I'm guessing here from the naming sequence - looks like it maybe DID remember and use the first point, but still trigger the creation of a new mount point.

$ lsblk 
NAME      MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
loop0       7:0    0 501.3M  1 loop 
└─loop0p1 259:0    0 485.2M  1 part /run/media/user/c92773f9-c5a6-4120-a979-4f95
loop1       7:1    0 501.3M  1 loop 
└─loop1p1 259:1    0 485.2M  1 part 
xvda      202:0    1    20G  0 disk 
├─xvda1   202:1    1   200M  0 part 
├─xvda2   202:2    1     2M  0 part 
└─xvda3   202:3    1  19.8G  0 part /
xvdb      202:16   1  49.6G  0 disk /rw
xvdc      202:32   1    10G  0 disk 
├─xvdc1   202:33   1     1G  0 part [SWAP]
└─xvdc3   202:35   1     9G  0 part 
xvdd      202:48   1   500M  1 disk 

I query my precise memory of how I interacted with the unused duplicate mount point (same device name), because it had no eject button. I may simply have clicked on it, or it vanished after a brief pause once I'd ejected the mounted one. Sorry.

The `lsblk` shows it cannot just be a GUI quirk (I've noticed several on this machine).

Most worryingly, on ejecting/clicking both the mounts (in nautilus), it automatically popped out the usb I'd just attached (but not mounted).

**Screenshots**
_If applicable, add screenshots to help explain your problem._

**Additional context**
_Add any other context about the problem here._

**Solutions you've tried**
_If applicable, any solutions or workarounds you've already tried._

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
_A list of links to the Qubes documentation (or other relevant software documentation) pages you have already consulted._

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
_A list of links to other bug reports, feature requests, or tasks in the qubes-issues tracker (or "none" if you didn't find any). Do not describe any other unreported bugs, features, or tasks here._

**Comment by MondayPeople** [comment]
Hi

Happened again, slightly different.

1. copied an ARM iso to SD card via terminal (`dd`). (I'll refer to this as the HD image or .iso); I detached the SD via Qubes Device widget.

Note, at some point (I had several terminal windows open over the last few busy days), this SD card and image was mounted as:
$ lsblk
NAME    MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
sda       8:0    1 14.9G  0 disk 
├─sda1    8:1    1  559M  0 part /run/media/user/openmediavault 20200325-17:17
└─sda2    8:2    1  2.8M  0 part 

But it wasn't at this point, it was unplugged from the computer.

2. I attempted to mount HD .iso via `loop -o` to a mountpoint of my own making: 

`[user@d-nanopi-m4 omv]$ sudo mkdir /media/omvtest
[user@d-nanopi-m4 omv]$ sudo mount loop -o openmediavault_5.3.9-amd64.iso /media/omvtest
mount: /media/omvtest: special device loop does not exist.`

(Why does this loop command not work? Sure its worked for me on other linux systems.)

3. Mounted via double-click in nautilus. Instant success, listed in the left-hand panel under the name `openmediavault- 20200325-17:17`. Browsed.

4. Reinserted the SD card, reattached via widget. Instantly nautilus *seems* to mount the SD card partition, and *also* named it `openmediavault- 20200325-17:17`. So, two entries in the lefthand pane, one after the other, same name, same file structure. No distinguishing information about the path differences (That I presume to exist) between them. 

From terminal:

[user@d-nanopi-m4 openmediavault 20200325-17:17]$ pwd
/run/media/user/openmediavault 20200325-17:17
[user@d-nanopi-m4 openmediavault 20200325-17:17]$ lsblk
NAME      MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
loop0       7:0    0  559M  1 loop 
├─loop0p1 259:0    0  559M  1 part /run/media/user/openmediavault 20200325-17:17
└─loop0p2 259:1    0  2.8M  1 part 
sdb         8:16   1 14.9G  0 disk 
├─sdb1      8:17   1  559M  0 part /run/media/user/openmediavault 20200325-17:17
└─sdb2      8:18   1  2.8M  0 part 
xvda      202:0    1   20G  0 disk 
├─xvda1   202:1    1  200M  0 part 
├─xvda2   202:2    1    2M  0 part 
└─xvda3   202:3    1 19.8G  0 part /
xvdb      202:16   1 49.6G  0 disk /rw
xvdc      202:32   1   10G  0 disk 
├─xvdc1   202:33   1    1G  0 part [SWAP]
└─xvdc3   202:35   1    9G  0 part 
xvdd      202:48   1  500M  1 disk 

So there's no way I can get to my SD card through nautilus. I can't get to it through the terminal, either. I tried to attach to my previous mountpoint:

[user@d-nanopi-m4 openmediavault 20200325-17:17]$ sudo mount /dev/sdb1 /media/omvtest
mount: /media/omvtest: /dev/sdb1 already mounted on /run/media/user/openmediavault 20200325-17:171.

I don't think the system can distinguish between the image on the hard disk and that on the SD card. They are copies of each other, after all, just with different paths.

In light of that, the behavior behind the first report might be less of a surprise: when I ejected the HD image file, it simultaneously popped the SD card becuase they are "the same". 

Now its behaving a little differently - nautilus has let me eject one `openmediavault- 20200325-17:17`, the bottom entry in the navigation pane (I got an error message and had to click "eject anyway" becuase bash was still using it). However, it won't let me eject the top `openmediavault- 20200325-17:17`, throwing this error message:

`Unable to eject openmediavault- 20200325-17:17
Error ejecting /dev/sdb: Commandline 'eject '/dev/sdb'' exited with non-zero exit status 1: eject: unable to eject`

Given all that, I have NO idea where any changes I made in that mounted drive would be written - the HD image or the SD, or both. That's incredibly dangerous.

I detached the SD card via the Qubes Devices widget. I notice while I am there that `d-nanopi-m4:loop0p2()` is available to attach to other qubes (but not `loop0p1`). I didn't do anything to list that there.

I find this all counter-intuitive behavior. I think this could lead to loss of work/data and needs remedy.  

Both user and the system need to be able to distinguish mounted volumes. For the user, that means the listing the navigation pane in nautilus has to provide more readily visible information (i.e. paths, perhaps on mouseover).
