### ISSUE TITLE
4.1: Qube Manager does not save autostart preference

### ISSUE THREAD

**Issue by jpds** [QubesOS/qubes-issues#5882]
**Qubes OS version**

4.1

**Affected component(s) or functionality**

Qube Manager

**Brief summary**

I've installed 4.1 onto a new system and `sys-whonix` starts on every boot. I untick the "Start qube automatically on boot" option in it's Qube Manager settings and press "Apply". A few moments later the box is reticked by itself.

**Comment by andrewdavidwong** [comment]
Related (possible duplicate of): #3606, #3554

**Comment by jpds** [comment]
I do not see this after using the `4.1-20200614` ISO.

**Comment by andrewdavidwong** [comment]
> I do not see this after using the `4.1-20200614` ISO.

Closing as resolved, but please let us know if the problem returns so that we can reopen this. Thank you.
