### ISSUE TITLE
"qvm-run --pass-io win7-template "type C:\file.txt" > ./file.txt" works only when win7-template is in poweroff state

### ISSUE THREAD

**Issue by esox1** [QubesOS/qubes-issues#5888]
Qubes OS version
#### Qubes release 4.0 (R4.0)

Affected component(s) or functionality
#### win7-template

Brief summary
I needed to transfer some files from win7-template to another appvm. I was suggested to use "qvm-run --pass-io" using the command "qvm-run --pass-io win7-template "type C:\file.txt" > ./file.txt"  
while win7-template was in a powered on state. The command/cursor just hanged in the terminal. I had to exit with ^C in terminal.

The command worked only after I powered off win7-template then "qvm-run --pass-io win7-template "type C:\file.txt" > ./file.txt" automatically powered on win7-template back on and  "file.txt" was copied to dom0 as expected.

ps: I can successfully copy files from any linux appvm to win7-template by going in any linux appvm, right click the file I want to transfer and then click on copy to another Vm (select win7-template) then the file will successfully transfer to win7-template QubesIncoming. So qrexec service works.

To Reproduce
power-on win7-template
in dom0 teminal:  "qvm-run --pass-io win7-template "type C:\file.txt" > ./file.txt"

Expected behavior
copies file.txt to dom0

Actual behavior
The  above command hangs in dom0 terminal. win7-template must be powered off prior to invoking the command in order for qvm-run --pass-io to work

Screenshots
https://imgur.com/a/KO8QWYE

**Comment by marmarek** [comment]
Try adding `--no-gui` option. If that changes anything, then it may be related to `qubes.WaitForSession` service or gui-agent in your windows vm.

**Comment by esox1** [comment]
Thank you. `--no-gui` worked!!

**Comment by andrewdavidwong** [comment]
It sounds like we still don't have a specific diagnosis, but the user's immediate problem is solved. Do you think there's still a bug worth investigating here, @marmarek?

**Comment by marmarek** [comment]
Yes,I'd prefer to keep it open until we fix the underlying issue.
