### ISSUE TITLE
Facing issue in qubes ISO building

### ISSUE THREAD

**Issue by vy159193** [QubesOS/qubes-issues#5894]
### Qubes OS version:

Hi 
I am facing issue in building qubes ISO , it is showing the below errors in between running the command make get-sources (when it comes to get extra sources for core libvirt)
ERRORS:
 make[1] : ***[Makefile.common:44:libvirt-3.3.0.tar.xz] error 4. 
 make:***[Makefile:206:core-libvirt.get-sources-extra] error 2.

### Affected component(s) or functionality:

---

### General notes:

---

**Comment by fepitre** [comment]
Please write **exatcly** what you have done (config content attached and commands) to obtain this error. Please also have a look to https://www.qubes-os.org/doc/qubes-iso-building/.

**Comment by andrewdavidwong** [comment]
Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this does not appear to be suitable for `qubes-issues`. We ask that you please send this to the `qubes-users` [mailing list](https://www.qubes-os.org/support/) instead. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a brief comment explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.

**Comment by vy159193** [comment]
Hello Sir,

I am building the qubes OS ISO by following
https://www.qubes-os.org/doc/qubes-iso-building/ and
https://www.qubes-os.org/doc/qubes-builder/
I am following all the steps but after that i am getting the error , in
detail i am writing the steps that i have followed:
I am using Qubes OS
1) I created a stand alone vm using fedora 30 template
2) Then i run the following commands as mentioned in documentation

$ sudo dnf install perl-Digest-SHA rpmdevtools rpm-build dialog
rpm-sign python2-sh dpkg-dev debootstrap devscripts
sudo dnf install gnupg git createrepo rpm-build make wget rpmdevtools
python3-sh dialog rpm-sign dpkg-dev debootstrap PyYAML devscripts
perl-Digest-MD5 perl-Digest-SHA

wget https://keys.qubes-os.org/keys/qubes-master-signing-key.asc
gpg --import qubes-master-signing-key.asc
gpg --edit-key 36879494
fpr
# Verify fingerprint! See Note below!
# Once verified, set trust to *ultimate*
# (Typical sequence is trust, 5, q)
wget https://keys.qubes-os.org/keys/qubes-developers-keys.asc
gpg --import qubes-developers-keys.asc

git clone git://github.com/QubesOS/qubes-builder.git
cd qubes-builder
git tag -v `git describe`

cp example-configs/qubes-os-master.conf builder.conf
# edit the builder.conf file and set the following variables:
NO_SIGN=1

cd ~/qubes-builder
./setup
# Select Yes to add Qubes Master Signing Key
# Select Yes to add Qubes OS Signing Key
# Select 4.0 for version
# Stable
# Select Current (if you want the option to use pre-built packages)
# No (we want a full build)
# Select fc30 and buster (for the currently shipping templates)
# Select builder-rpm, builder-debian, template-whonix, mgmt-salt
# Yes (to download)

Once it completes downloading, re-run setup to add the Whonix templates:

./setup
# Choose the same options as above, except at templates select:
# fc30, buster, whonix-gateway-14, whonix-workstation-14
# If prompted, choose Yes to add adrelanos's third party key

Continue the build process with:

make install-deps
make get-sources


After running the make get-source command the following errors are
coming, I am attaching the screenshot of the terminal. It is stucking
at the time of installing additional sources for core-libvirt.

Please help me.


PFA

Thanks and Regards
---------------------------------------------------------------------------
Vinita Yadav
Mobile Developer
Honeywell

**Comment by fepitre** [comment]
You are not following the doc because you are mixing both manual and automatic steps. In the doc it's written (https://www.qubes-os.org/doc/qubes-iso-building/#build-using-setup-script) to use `setup` script **OR** (https://www.qubes-os.org/doc/qubes-iso-building/#build-using-manual-steps) instead of using ./setup, you can manually configure the build. For further issue in your context, please use other channel like @andrewdavidwong provided in his previous message.

**Comment by vy159193** [comment]
Hello Sir,

I have been trying it for a long back .
Now I followed the following steps  but the same error is coming
1. I am using Fedora 30 OS and following the link
https://www.qubes-os.org/doc/qubes-builder/
2.  Then run the following command by following the link

sudo dnf install gnupg git createrepo rpm-build make wget rpmdevtools
python3-sh dialog rpm-sign dpkg-dev debootstrap PyYAML devscripts
perl-Digest-MD5 perl-Digest-SHA
# Import the Qubes master key
gpg --recv-keys 0xDDFA1A3E36879494

# Verify its fingerprint, set as 'trusted'.
# This is described here:
# https://www.qubes-os.org/doc/VerifyingSignatures

wget https://keys.qubes-os.org/keys/qubes-developers-keys.asc
gpg --import qubes-developers-keys.asc

git clone git://github.com/QubesOS/qubes-builder.git qubes-builder
cd qubes-builder

# Verify its integrity:
git tag -v `git describe`

cp example-configs/qubes-os-master.conf builder.conf
# edit the builder.conf file and set the following variables:
# NO_SIGN="1"

# Download all components:

make get-sources

After running get-source i am getting the same error in installing  core libvirt

make[1]: *** [Makefile.common:49: libvirt-6.4.0.tar.xz] Error 4
make: *** [Makefile:206: core-libvirt.get-sources-extra] Error 2

I am sharing the screenshot of the terminal.

Please help me out, I am facing the same problem from long back

Please share the steps from starting if I am lacking somewhere.

PFA

Thanks and Regards
---------------------------------------------------------------------------
Vinita Yadav

**Comment by andrewdavidwong** [comment]
@vy159193, you keep posting to this issue without reading our replies.

Again, based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this does not appear to be suitable for `qubes-issues`. We ask that you please send this to the `qubes-users` [mailing list](https://www.qubes-os.org/support/) instead. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a brief comment explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.
