### ISSUE TITLE
qvm-pool: Weird handling of undeclared options

### ISSUE THREAD

**Issue by 3hhh** [QubesOS/qubes-issues#5895]
### Qubes OS version:
4

### Affected component(s) or functionality:
qvm-pool

---

### Steps to reproduce the behavior:
In dom0:
```
qvm-pool -o dir_path=/mnt/foo -o bla=blub -a foo file
```

### Expected or desired behavior:
`journalctl -b0` shows something helpful about the unexpected option `bla`
_or_
the file driver complains about the additional option
_or_
the file driver just ignores the additional option.

### Actual behavior:
The additional option never reaches the file driver
```
usage: qvm-pool [--verbose] [--quiet] [--help] [-o options]
                [-l | -i POOLNAME | -a NAME DRIVER | -r NAME | -s POOLNAME | --help-drivers]
qvm-pool: error: failed to add pool foo: Got empty response from qubesd. See journalctl in dom0 for details.
```
and `journalctl -b0` shows something weird:
```
Jun 17 17:41:20 dom0 qubesd[1755]: permission denied for call b'admin.pool.Add'+b'file' (b'dom0' → b'dom0') with payload of 18 bytes
```
No python stack trace is shown in the journal.

### General notes:
What does Qubes RPC have to do with this?

This is rather annoying wrt typos.

Making additional options reach storage drivers can have its applications. Actually, I was trying to develop one and then hit into this bug.

---

### I have consulted the following relevant [documentation](https://www.qubes-os.org/doc/):
-

### I am aware of the following related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues:
-

**Comment by rustybird** [comment]
> ```
> qvm-pool -o dir_path=/mnt/foo -o bla=blub -a foo file
> ```

Not that it's relevant for this bug, but only the last `-o` argument counts... For multiple options, use the comma-separated syntax:

```
qvm-pool -o dir_path=/mnt/foo,bla=blub -a foo file
```

> What does Qubes RPC have to do with this?

That's the [Admin API](https://www.qubes-os.org/doc/admin-api/), specifically the `admin.pool.Add` RPC service responding to a request from `qvm-pool` and denying it [here](https://github.com/QubesOS/qubes-core-admin/blob/v4.1.13/qubes/api/admin.py#L696-L698):

```py
driver_parameters = qubes.storage.driver_parameters(self.arg)
self.enforce(
    all(key in driver_parameters for key in untrusted_pool_config))
```

> This is rather annoying wrt typos.

Yes, it's not very user friendly.

**Comment by 3hhh** [comment]
> > ```
> > qvm-pool -o dir_path=/mnt/foo -o bla=blub -a foo file
> > ```
> 
> Not that it's relevant for this bug, but only the last `-o` argument counts... For multiple options, use the comma-separated syntax:
> 
> ```
> qvm-pool -o dir_path=/mnt/foo,bla=blub -a foo file
> ```

Thanks for the hint!

I wonder what happens with commas inside paths?

So apparently that simply doesn't work as `qvm-pool -o dir_path=/mnt/foo,bla=blub -a foo file` could mean two things:

Either use the path `/mnt/foo,bla=blub` or use the path `/mnt/foo` and set the option `bla` to `blub`.

So storage pool driver implementations may fail due to qvm-pool ambiguities as well. :-(

Can this be handled as part of this bug or do we need another one for that?

**Comment by rustybird** [comment]
> I wonder what happens with commas inside paths?

> Can this be handled as part of this bug or do we need another one for that?

That part's already fixed in R4.1, where `qvm-pool` has a [new syntax](https://github.com/QubesOS/qubes-core-admin-client/pull/112) with multiple `-o` arguments (and they're not split on comma).

**Comment by 3hhh** [comment]
> That part's already fixed in R4.1, where `qvm-pool` has a [new syntax](https://github.com/QubesOS/qubes-core-admin-client/pull/112) with multiple `-o` arguments (and they're not split on comma).

Good news, thanks again for the hint!

Wrt your previous comment:
> That's the [Admin API](https://www.qubes-os.org/doc/admin-api/), specifically the `admin.pool.Add` RPC service responding to a request from `qvm-pool` and denying it [here](https://github.com/QubesOS/qubes-core-admin/blob/v4.1.13/qubes/api/admin.py#L696-L698):
> 
> ```python
> driver_parameters = qubes.storage.driver_parameters(self.arg)
> self.enforce(
>     all(key in driver_parameters for key in untrusted_pool_config))
> ```

Handling of additional parameters should be left to the receiving driver from my point of view.

What the code is attempting to protect against is that an attacker could use the additional parameter to somewhat attack pool driver code.

However:
1. Pool drivers will generally ignore additional parameters. If they don't, they need to do the same sanitization as with the allowed parameters in order not to be compromised.
2. If python itself is broken wrt "additional parameter handling", a lot of potential attacks exist.

So in total there seems to be no difference from an attacker's perspective with or without that parameter check to me. If the attacker finds faulty storage pool driver code and has admin.pool.Add rights, he'll be able to attack dom0.

I stand ready to be corrected though. ;-)

Alternatively, one could just skip all of those tests, if the source is dom0 as well. I actually attempted to allow the action in the Qubes RPC policy with `dom0 dom0 allow,target=dom0`, but it had no effect.

**Comment by rustybird** [comment]
Hmm I don't know the reason for that check, it's been there from the [beginning](https://github.com/QubesOS/qubes-core-admin/blob/fb7bd68/qubes/mgmt.py#L328-L329).

Out of curiosity, what's your use case for undeclared options? BTW the option values are also [limited](https://github.com/QubesOS/qubes-core-admin/blob/v4.1.13/qubes/api/admin.py#L676) to ASCII without `\n`.

**Comment by marmarek** [comment]
> Handling of additional parameters should be left to the receiving driver from my point of view.

It is. The `qubes.storage.driver_parameters` function basically takes pool driver `__init__` arguments - this means the driver can declare parameters freely. The purpose of preventing invalid parameters (instead of ignoring) is simple: avoid situation when typo (or perhaps older driver installed) makes a crucial argument ignored (for example `readonly=True`).
I agree the error reporting here could use some improvements - there is no point in hiding why this call was refused.

**Comment by 3hhh** [comment]
> The purpose of preventing invalid parameters (instead of ignoring) is simple: avoid situation when typo (or perhaps older driver installed) makes a crucial argument ignored (for example `readonly=True`).

Ok, that makes perfect sense, then I stand corrected. ;-)

So the error message is the only thing to fix here.

> Out of curiosity, what's your use case for undeclared options?

I wanted to proxy existing drivers dynamically and didn't want to re-declare all of their possible options.

But the fact that `admin.pool.Add` can be called from a VM in theory incl. parameters makes me favor a static config file, not related to other Qubes OS parts and certainly not editable from any VM anyway.

**Comment by rustybird** [comment]
@3hh:
> I wanted to proxy existing drivers dynamically and didn't want to re-declare all of their possible options.

That sounds like a really good use!

@marmarek:
> The purpose of preventing invalid parameters (instead of ignoring) is simple: avoid situation when typo (or perhaps older driver installed) makes a crucial argument ignored (for example `readonly=True`).

Why do the Pool base class and drivers (except LinuxKernel) even take a `**kwargs` argument? They don't do anything substantial with it. When I change ReflinkPool from

    def __init__(self, dir_path, setup_check='yes', revisions_to_keep=1,
                 **kwargs):
        super().__init__(revisions_to_keep=revisions_to_keep, **kwargs)

to explicitly forward the `name` parameter

    def __init__(self, *, name, revisions_to_keep=1,
                 dir_path, setup_check='yes'):
        super().__init__(name=name, revisions_to_keep=revisions_to_keep)

and comment out the option validation from `admin.pool.Add`, sure enough:

    TypeError: __init__() got an unexpected keyword argument 'bla'

So we could remove the `**kwargs` parameter from the existing base class and drivers, and make `admin.pool.Add` allow unknown options (blacklisting `self`, though Python will already complain about that) if the driver - like @3hhh's proxy - has such a type `inspect._VAR_KEYWORD` parameter. If the driver doesn't have it, print a friendly error message.

**Comment by marmarek** [comment]
We still need a way to list options, see `qvm-pool --help-drivers`.

**Comment by rustybird** [comment]
> We still need a way to list options, see `qvm-pool --help-drivers`.

I don't see the problem? `--help-drivers` would work as before, except that an unusual driver can allow additional undeclared options by taking `**kwargs`. E.g. a proxy driver might declare `backend_driver` and then forward everything else to that backend's `__init__()`, if I understand correctly what @3hhh is trying to do.

Another way to design such a proxy driver could be to let the user manually create the backend pool first and then pass the _name_ of that pool to to the proxy driver. But this is orthogonal to the question of why the existing drivers bother to take `**kwargs` at all.

**Comment by marmarek** [comment]
Yes, I absolutely agree about removing `kwargs`. My point is actually about using it in the proxy driver - which would break listing available options (in --help-drivers, and also in the current pool add method).
Perhaps a better way is more explicit options declaration - instead of extracting them from `__ini__` signature, add a `list_options` function. This will allow a "proxy" driver to add own options (but also remove some - for example when its value is fixed to some constant in this case). But also, it would allow returning some description for each option.

**Comment by 3hhh** [comment]
Yes, I had also noticed that `kwargs` is pretty much dead except for the need to to have to declare `name`.

For my particular use case I'll stick with the config file approach though as I don't want VMs to control the options, even with the `admin.pool.Add` permission. It would otherwise become more of an `admin.pool.ExecuteInDom0` permission...

(My use case is a driver adding callback capabilities to external dom0 programs to existing drivers. I hope I'll be able to send an upstream PR in 1-2 weeks. It should be interesting for debugging & custom encryption applications.)

The basic idea of the config file approach is to let the user or VM with `admin.pool.Add` permission pick a configuration ID as only `__init__` argument that leads to pre-configured commands in the config file to be executed in dom0. You just don't want these commands to be picked directly from a VM via whatever arguments (listed or not).

Actually you could even generalize this approach to all pool drivers and segregate the right to add pools (`qvm-pool -a`) from the right to configure pools (edit the config file). IDs would have to be somewhat complex as to make them not guessable from other VMs.
By Qubes not accepting any pool parameters other than the configuration ID, pool driver devs would have a harder time breaking the Qubes security model wrt `admin.pool.Add`.
An alternative, but probably quite some effort...

**Comment by brendanhoar** [comment]
I am now very very curious about your work @3hhh . Will this be layered on top of lvm, Btrfs or file volume driver? Please say lvm! :)

**Comment by 3hhh** [comment]
> I am now very very curious about your work @3hhh . Will this be layered on top of lvm, Btrfs or file volume driver? Please say lvm! :)

The driver & what you implement with the callbacks will remain your choice.
