### ISSUE TITLE
Latest kernel in ISO

### ISSUE THREAD

**Issue by jpds** [QubesOS/qubes-issues#5900]
**The problem you're addressing (if any)**

Sometimes newer hardware fails with the stock `kernel` package found in Qubes.

**Describe the solution you'd like**

Have a menu option in the installer ISO to boot the installer with the `kernel-latest` option instead.

**Where is the value to a user, and who might that user be?**

Less frustration with installs.

**Comment by SaswatPadhi** [comment]
More generally, an option to auto update (if internet is connected) during installation from ISO would be great!

**Comment by andrewdavidwong** [comment]
> More generally, an option to auto update (if internet is connected) during installation from ISO would be great!

For security reasons, the installer intentionally has no networking capability at all, so this might be difficult.

**Comment by SaswatPadhi** [comment]
Thank you for the clarification. That makes sense.

**Comment by marmarek** [comment]
@fepitre this should automatically get included in the next ISO build, for R4.1 too. I tested it locally, but another verification of your build wouldn't hurt. If it works, you can drop separate "kernel-latest" build and probably make some announcements about this change on the forum message about your builds.
So, next step here after the weekend when new build will be there :)

**Comment by fepitre** [comment]
> @fepitre this should automatically get included in the next ISO build, for R4.1 too. I tested it locally, but another verification of your build wouldn't hurt. If it works, you can drop separate "kernel-latest" build and probably make some announcements about this change on the forum message about your builds. So, next step here after the weekend when new build will be there :)

Done.
