### ISSUE TITLE
/bin/qubes-dom0-update: lime 251: [: too many arguments

### ISSUE THREAD

**Issue by rjt** [QubesOS/qubes-issues#5901]
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
ReInstalling qubes-template-fedora-31 by:
[Dom0 ] sudo qubes-dom0-update —action=reinstall qubes-template-fedora-31

**Brief summary**
ReInstall results  in error on line 251 of /bin/qubes-dom0-update

**To Reproduce**
_1. Follow instructions at https://www.qubes-os.org/doc/reinstall-template/
_2. Open  terminal in Dom0
_3. sudo qubes-dom0-update —action=reinstall qubes-template-fedora-31
_4. Notice it might look successful with  Reinstalled: 
  qubes-template-fedora31.noarch 4.0.1-202002142323

Complete!
/bin/qubes-dom0-update: line 251: [:  too many arguments

**Expected behavior**
qubes scripts should be able to handle documented number of arguments

**Actual behavior**
Script fails because too many arguments. 

**Screenshots**
**Additional context**
Trying to resolve non working qubes and fedora 31.

**Solutions you've tried**
Repeating and rebooting and repeating

**Relevant ([documentation]https://www.qubes-os.org/doc/) you've consulted**
https://www.qubes-os.org/doc/reinstall-template/

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

**Comment by 3hhh** [comment]
Looks like @fepitre forgot an `&&`.

https://github.com/QubesOS/qubes-core-admin-linux/commit/df3f29d1dba1d45b2e3941b93ed28ac2f1bbd74b#diff-6b87ee5cdb9e63b703415a14e5a505cdR251

I wonder why ShellCheck didn't catch that.

**Comment by rjt** [comment]
This time i tried to update the minimal version 
qubes-template-fedora-31-minimal.

Reminded me that the first attempt has another error line:
Total size: 487 M
Is this ok [y/N]: Operation Aborted.
/bin/qubes-dom0-update: line 251: [:  too many arguments

**Comment by fepitre** [comment]
> Looks like @fepitre forgot an `&&`.
> 
> [QubesOS/qubes-core-admin-linux@df3f29d#diff-6b87ee5cdb9e63b703415a14e5a505cdR251](https://github.com/QubesOS/qubes-core-admin-linux/commit/df3f29d1dba1d45b2e3941b93ed28ac2f1bbd74b#diff-6b87ee5cdb9e63b703415a14e5a505cdR251)
> 
> I wonder why ShellCheck didn't catch that.

Yes indeed. Running it under vscode integration or manually it does not catch it. Weird...My apologize.
