### ISSUE TITLE
usb-proxy incompatible with Linux Kernel 5.7+

### ISSUE THREAD

**Issue by neowutran** [QubesOS/qubes-issues#5905]
**Qubes OS version**
R4.0, testing repository

**Affected component(s) or functionality**
USB Proxy

**Brief summary**
Unable to pass USB device to others qubes when using Linux Kernel 5.7.4-1

**To Reproduce**
Use testing repository for R4.0. Upgrade kernel. Try to pass a usb device to another qubes

**Expected behavior**
Work as good as with Kernel < 5.7

**Actual behavior**
dom0: display an error popup "No device info received, connection failed, check backend side for details"
sys-usb journalctl: /usr/lib/qubes/usb-export: line 95: echo: Write Error: No such device

Maybe related to this part of the code (tested nothing, just a think) 

```
SYS_USB_DEVICES=/sys/bus/usb/devices
SYS_USBIP_HOST=/sys/bus/usb/drivers/usbip-host

# From /usr/include/linux/usbip.h
SDEV_ST_AVAILABLE=1
SDEV_ST_USED=2
SDEV_ST_ERROR=3
```

**Solutions you've tried**
Switch back to older kernel version

**Comment by neowutran** [comment]
Never mind, seems to be a duplicate of #3612

**Comment by neowutran** [comment]
In fact, i am unsure that it is really a duplicate. Sorry, I reopen it and let you decide

**Comment by 0spinboson** [comment]
I'm seeing the same thing in qubes 4.1

**Comment by m-v-b** [comment]
This issue was reported to the Linux kernel's Bugzilla instance by another person using usbip. Here is [a link to the bug report](https://bugzilla.kernel.org/show_bug.cgi?id=208267).

As I noted in my comment on the bug report page, reverting 5 commits appears to resolve this issue for the time being.

**Comment by andrewdavidwong** [comment]
It sounds like this might be an upstream bug.

**Comment by m-v-b** [comment]
@andrewdavidwong, I confirm that this is an upstream bug, but it has not received attention from upstream yet.

**Comment by andrewdavidwong** [comment]
Closing as "not our bug." If you believe this is a mistake, please leave a comment, and we'll be happy to take another look. Thank you.
