### ISSUE TITLE
qubes-gui: backport window pixmap grant references to R4.0

### ISSUE THREAD

**Issue by iamahuman** [QubesOS/qubes-issues#5909]
**The problem you're addressing (if any)**

 - (Possibly) #4943 - Severe graphical slowdown and tearing after switching VTs.
 - #5460 - DomU windows causing Intel GFX acceleration to fail (heavy screen artifacts after VT switch). [One user has reported that R4.1 indeed fixed the problem](https://github.com/QubesOS/qubes-issues/issues/5460#issuecomment-603071078).
 - No more `mlock`-leaks for VMA regions for pixmap buffers.
 - Possible (hypothetical) issues arising from the VM sending out weird pages (cache-ability inconsistency in PTE, some page pinning issues, ...)

**Describe the solution you'd like**
Let Qubes OS 4.0 use grant tables for window pixmap sharing, possibly with protocol negotiation and graceful fallback to MFNs in case either party ("GuiVM" and client VMs) do not support the new scheme. This is already implemented in https://github.com/QubesOS/qubes-gui-daemon/pull/21.

**Where is the value to a user, and who might that user be?**
This is a possible fix for all graphics drivers that use `get_user_pages`.

**Describe alternatives you've considered**
A known workaround of `modesetting + glamor`, albeit slower and with buggy XRandR keystone support, exists for Intel integrated graphics.

**Additional context**
Qubes uses "inter-VM shared memory" to accelerate rendering of VM window outputs. The VM's window composite buffer is shared to "GuiVM", which maps it into user space and then passes it to the driver which is supposed to copy it to the frame-buffer via DMA.

In Linux, this strategy is inherently heavily dependent on the implementation of Direct Rendering Infrastructure (DRI). For Intel X11 driver (`xf86-video-intel`, package `xorg-x11-drv-intel` in Dom0), this means to use the i915 `userptr` GEM object to _blit_ into video memory (via GTT or whatever). This is the _fastest_ possible way to render the VM windows.

However, this requires the memory segment to be pinned (in a similar manner to `mlock(2)`). This is accomplished with the Linux kernel's `get_user_pages` facility (located in `mm/gup.c`). One of the requirements imposed on such virtual memory pages is that they shall have none of the `VM_IO | VM_PFNMAP` flags _and_ have associated `struct page`s. `xc_map_foreign_pages` yields `/dev/xen/privcmd` pages, which satisfy none of them. This results in `-EFAULT`.

Meanwhile, the Xen grant tables implementation in Linux is not only [completely free of this problem](https://github.com/torvalds/linux/blob/v4.19/drivers/xen/gntdev.c#L1110), but also [exactly designed for this use case](https://github.com/torvalds/linux/blob/v4.19/drivers/xen/gntdev-dmabuf.c). (Actually using DMA-BUF should be a separate issue).

Hence, and to facilitate testing of the new `MFN_WINDOW_DUMP` implementation by existing Qubes users, I suggest providing the feature as opt-in for users affected by #5460.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
 - https://www.qubes-os.org/doc/gui/
 - Linux kernel documentation (along with source code)

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
#4943, #5460

**Comment by iamahuman** [comment]
If my analysis turn out to be correct, perhaps we shall mark the two issues above as diagnosed.

**Comment by marmarek** [comment]
This is not going to happen, this is too large change to introduce as a stable update. The proper process for such changes is a major upgrade - to Qubes OS 4.1 in this case.

**Comment by iamahuman** [comment]
@marmarek I agree. Actually, that's quite what I have speculated. This was intended to serve more of diagnosis of existing issues, although I'm also convinced that this issue might have known inside Qubes team internally as well.
