### ISSUE TITLE
SaltStack rendering broken on fedora 32

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#5919]
### Qubes OS version:

`Qubes release 4.0 (R4.0)`

### Affected component(s) or functionality:

SaltStack

---

### Steps to reproduce the behavior:

Use Salt to manage a Fedora 32 template.

### Expected or desired behavior:

Success

### Actual behavior:

```
2020-06-03 10:16:45,629 calling 'state.sls update.qubes-vm'...
2020-06-03 10:17:53,907 output: fedora-32:
2020-06-03 10:17:53,908 output:     - Rendering SLS 'base:update.qubes-vm' failed: Jinja variable 'dict object' has no attribute 'os'
```

### General notes:

This is with a Qubes-provided Salt state, so it should work.

---

### I have consulted the following relevant [documentation](https://www.qubes-os.org/doc/):

N/A

### I am aware of the following related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues:

N/A

**Comment by marmarek** [comment]
"Thanks to" Python 3.8 in Fedora 32, you need salt new enough (>= 3001) to work there. It is only packaged for Fedora 32. In short - you need switch default-mgmt-dvm to fedora-32 to manage fedora-32 (or create separate fedora-32-based mgmt disposable vm template just for managing fedora-32 template).

**Comment by andrewdavidwong** [comment]
We just published the Fedora 32 template announcement, which includes this:
> **Important:** If you wish to use the Qubes Update widget to update a Fedora 32 template, you must first switch the `default-mgmt-dvm qube` to a Fedora 32 template. (Alternatively, you can create a separate management DisposableVM Template based on a Fedora 32 template for the purpose of updating Fedora 32 templates.) This does not affect updating internally using `dnf`.

https://www.qubes-os.org/news/2020/06/30/fedora-32-templates-available/
