### ISSUE TITLE
ctrl-shift-c suddently stopped working without doing any changes.

### ISSUE THREAD

**Issue by johnblanc** [QubesOS/qubes-issues#5920]
Latest qubes here.
ctrl+c works but ctrl+shift+c right after that does nothing now. Nothing is moved in the interVM clipboard and hence nothing can be pasted with shift+ctrl+v and ctrl+v anywhere else.
The tray icon says "Qubes clipboard is empty" whatever you do.
The odd part is that it was working fine for months and today without doing any changes (like changing keyboard layout, messing with shortcuts or whatever, just doing my normal workflow as usual) it stopped working.

I can't restart right now to see if that will fix it, so looking for another solution?

**Comment by andrewdavidwong** [comment]
Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this does not appear to be suitable for `qubes-issues`. We ask that you please send this to the `qubes-users` [mailing list](https://www.qubes-os.org/support/) instead. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a brief comment explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.

**Comment by marmarek** [comment]
Duplicate of https://github.com/QubesOS/qubes-issues/issues/2189
