### ISSUE TITLE
sys-whonix unable to connect to TOR, sdwdate stuck in "initial time fetching in progress"

### ISSUE THREAD

**Issue by qubecub** [QubesOS/qubes-issues#5921]
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
sys-whonix, anon-whonix

**Brief summary**
sys-whonix stopped connecting to TOR network. Upon checking on sdwdate status it is stuck in the "initial time fetching in progress". Even when left for a long time the time is never fetched. Surprisingly, when TOR connection is configured using bridge (obfs4) sdwdate gets synced and TOR connection established. 
sys-whonix was working fine for months but it stopped in the past week or so. There is nothing different that I did / installed but I can't tell whether any of the system updates / template updates caused the change. 

**To Reproduce**
1. start sys-whonix VM - (this is QubesOS out-of-the-box VM without any modufications, just update via template)
2. start anon-whonix and run TOR browser. 
3. The previous actions will place sdwdate monitor icon no QubesOS taskbar. When you click on that icon and check "sys-whonix"->"Show sdwdate status" you get a pop-up message: "Initial times fetching in progress..."
That message is stuck and does not change after 5, 10 or even half an hour. 
4. When you try opening a URL in the TOR browser the address content will not load. 
5. Alternative actions: use bridged (obfs4) connection to TOR - can be set up in: sys-whonix-> TOR control panel. 
Connection type can also be change in sys-whonix-> Anon Connection Wizzard. 
6. Bridged connections always gets established and TOR connection accessible - both for .onion as well as HTTPS addresses. 

**Expected behavior**
sys-whonix autoamtially starts and establishes TOR connections without the need of using bridges. As mentioned before it's been working like that until last week. 

Does QubesOS offers a clean way of removing and then reinstalling whonix templates and VMs from scratch? 
Last resort would be full QubesOS re-installation if no solution is found. 

**Actual behavior**
sys-whonix does not connect to TOR unless bridged connection is used (obfs4). Also sdwdate is stuck in "initial time fetching in progress" state - suggesting it can't synchronize/randomize TOR clock. 

**Screenshots**
_If applicable, add screenshots to help explain your problem._

**Additional context**
I had this issue in Qubes R4.0.1 and I couldn't resolve it either, had to do complete QubesOS re-install. After clean reinstallation sys-whonix was working fine, connecting to TOR network without a bridge. sdwdate status was showing "Success. Sleeping for X minutes" message. 

**Solutions you've tried**
I tried sys-whonix suggested solutions:
1. running whonixcheck
2. re-adjusting host system clock (date -s  / timedatectl set-time), 
3. randomizing sys-whonix clock (clock-random-manual-gui)
4. even manually creating status files in sys-whonix  /run/sdwdate directory: sudo touch first_success. 

None of these actions resolved the issues. 

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
_A list of links to the Qubes documentation (or other relevant software documentation) pages you have already consulted._

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
_A list of links to other bug reports, feature requests, or tasks in the qubes-issues tracker (or "none" if you didn't find any). Do not describe any other unreported bugs, features, or tasks here._

**Comment by andrewdavidwong** [comment]
FYI @adrelanos

**Comment by andrewdavidwong** [comment]
> Does QubesOS offers a clean way of removing and then reinstalling whonix templates and VMs from scratch?

Yes: https://www.whonix.org/wiki/Qubes/Reinstall

**Comment by qubecub** [comment]
Reinstalling whonix in QubesOS is a big hassle and should be done only as the last resort.
I lost ability of direct connection to TOR via sys-whonix for the second time running (bridge only now). I diligently reinstalled QubesOS after first time but the problem returned again. What if it happens again in some time? 

Could this be investigated? I will try to provide information needed for investigation. Is there any quick-check / quick-fix procedure I could follow to make relevant tests? 

I somehow suspect it has something to do with the way sdwdate interacts with sys-whonix as this stage doesn't get completed when connecting to TOR directly. 

But once TOR connection is attempted through bridge, or even active VPN connection, sdwdate gets agreed with sys-whonix and TOR connection becomes active. 

Please investigate and help resolving the issue. Thank you.

**Comment by adrelanos** [comment]
Did you change any settings inside the VM such as timezone?

Note: clock is set in UTC. If you set manually, it must be in UTC. Not local timezone.

For analysis:

* https://www.whonix.org/wiki/Tor#Configuration_Check
* https://www.whonix.org/wiki/Tor#Log_Analysis

**Comment by qubecub** [comment]
After direct TOR connection in sys-whonix stopped working I tried various time changes. 

1. checked UTC time on https://www.timeanddate.com/worldclock/timezone/utc

2. verified that dom0 has the correct time set:
"[dom0]$ date -u"    ->   command returns UTC time in my dom0, the same as queried in point (1.)
(I also tried adjusting dom0 time by either of the commands:  "$ date -s "new-time"    or   "$ timedatectl set-time "new-time"  or  "$timedatectl set-timezone UTC"

3. verified sys-whonix time by "[sys-whonix]$ date -u" which returns exactly the same time as in dom0. The only difference is the format: dom0 has 24h time format whereas sys-whonix uses 12h and AM/PM convention. But the actual time in between the VM's the same. 

4. verified time in sys-net and sys-firewall VM's  ("date -u" ) - these too have matching and correct time in UTC, same as dom0 and sys-whonix. 

5. I looked up whonix website: https://whonix.orgwiki/Troubleshooting#Clock_Fix 
Followed instruction there but still couldn't make direct TOR connection to work. Connection works only when using bridge or through some VPN-VM. 

6. I even tried manually randomizing sys-whonix clock by "$ clock-random-manual-gui" followed by sdwdate restart. I also tried creating status files in /run/sdwdate folder ("first_success" or "success") yet still no positive results.


Again, I somehow suspect issues with time sync / randomizing in "sdwdate" as it's stuck in "initial time fetching in progress" or just "time fetching in progress" state. And I can't get it to move on to time fetched and "Success. Sleeping for x minutes". 

I will try and do 'anon-verify'  and 'log analysis' as you suggested although I'm not sure I will be able to spot issues. Will give it a go though.

**Comment by adrelanos** [comment]
What sdwdate says is kinda irrelevant. You can stop sdwdate.

sudo systemctl stop sdwdate

Set clock manually. From there, it won't interfere. Important thing is
to look what Tor is saying.

qubecub:
> After direct TOR connection in sys-whonix stopped working I tried various time changes. 
> 
> 1. checked UTC time on https://www.timeanddate.com/worldclock/timezone/utc


OK.

> 2. verified that dom0 has the correct time set:
> "[dom0]$ date -u"    ->   command returns UTC time in my dom0, the same as queried in point (1.)
> (I also tried adjusting dom0 time by either of the commands:  "$ date -s "new-time"    or   "$ timedatectl set-time "new-time"  or  "$timedatectl set-timezone UTC"


OK. (dom0 UTC time is not required btw. Only import that VM clock is
reasonably correct (+/- 10 minutes should be more than enough for Tor)

> 3. verified sys-whonix time by "[sys-whonix]$ date -u" which returns exactly the same time as in dom0. The only difference is the format: dom0 has 24h time format whereas sys-whonix uses 12h and AM/PM convention. But the actual time in between the VM's the same. 
> 
> 4. verified time in sys-net and sys-firewall VM's  ("date -u" ) - these too have matching and correct time in UTC, same as dom0 and sys-whonix. 
> 
> 5. I looked up whonix website: https://whonix.orgwiki/Troubleshooting#Clock_Fix 
> Followed instruction there but still couldn't make direct TOR connection to work. Connection works only when using bridge or through some VPN-VM. 
> 
> 6. I even tried manually randomizing sys-whonix clock by "$ clock-random-manual-gui" followed by sdwdate restart. I also tried creating status files in /run/sdwdate folder ("first_success" or "success") yet still no positive results.


OK.

> Again, I somehow suspect issues with time sync / randomizing in "sdwdate" as it's stuck in "initial time fetching in progress" or just "time fetching in progress" state. And I can't get it to move on to time fetched and "Success. Sleeping for x minutes". 


sdwdate has a log too. Reachable from sdwdate-gui systray for example.
But as said on above, sdwdate won't block Tor (yet, not implemented). As
long as Tor isn't working, no need to look into sdwdate.

> I will try and do 'anon-verify'  and 'log analysis' as you suggested although I'm not sure I will be able to spot issues. Will give it a go though. 


OK.

**Comment by qubecub** [comment]
/var/run/tor/log has the following entry for direct TOR connection attempt:

"[notice] Guard Hydra6 ($xxxxxxx) is failing more circuits than usual. Most likely this means the Tor network is overloaded. Success counts are 169/281. Use counts are 8/12. 266 circuits completed, 2 were unusable, 95 collapsed, and 301 timed out. For reference, your timeout cutoff is 60 seconds."

**Comment by qubecub** [comment]
Here is the time I've got in sys-whonix / $timedatectl

$ timedatectl 
           Local time: Wed 2020-07-08 17:55:25 UTC
           Universal time: Wed 2020-07-08 17:55:25 UTC
           RTC time: n/a
           Time zone: Etc/UTC (UTC, +0000)
System clock synchronized: no
           NTP service: inactive
           RTC in local TZ: no


I run "sudo date -s "2020-07-08 18:00:00"

Restarted tor using tor-control-panel - removing bridge from configuration. 

Still no direct connection over TOR. 

The thing is that after tor restart some KB of date get transferred, e.g. UTL  wikipedia.org will start loading for 1-2s and then stop completely. After that tor is stuck and no longer pulls any data. But there is this initial "batch" of few KB that gets transferred.

**Comment by adrelanos** [comment]
> /var/run/tor/log has the following entry for direct TOR connection attempt:
> 
> "[notice] Guard Hydra6 ($xxxxxxx) is failing more circuits than usual. Most likely this means the Tor network is overloaded. Success counts are 169/281. Use counts are 8/12. 266 circuits completed, 2 were unusable, 95 collapsed, and 301 timed out. For reference, your timeout cutoff is 60 seconds."

This is it. Not under my control. General Tor / Tor network issues. I don't think there's anything I can help with here.

**Comment by andrewdavidwong** [comment]
> > /var/run/tor/log has the following entry for direct TOR connection attempt:
> > "[notice] Guard Hydra6 ($xxxxxxx) is failing more circuits than usual. Most likely this means the Tor network is overloaded. Success counts are 169/281. Use counts are 8/12. 266 circuits completed, 2 were unusable, 95 collapsed, and 301 timed out. For reference, your timeout cutoff is 60 seconds."
> 
> This is it. Not under my control. General Tor / Tor network issues. I don't think there's anything I can help with here.

Closing as "not our bug." If you believe this is a mistake, please leave a comment, and we'll be happy to take another look. Thank you.
