### ISSUE TITLE
whonix gateway 15 has imagemagick packages installed

### ISSUE THREAD

**Issue by jorgejones7711** [QubesOS/qubes-issues#5922]
**Qubes OS version**
4.0

**Affected component(s) or functionality**
whonix gateway

**Brief summary**
Whonix gateway 15 has several imagemagick packages installed. It must be an error.

**To Reproduce**
In qubes manager, go to update whonix gateway 15. See that it wants to update several imagemagick packages.

**Expected behavior**
Such things are not installed.

**Actual behavior**
Such things are installed.

**Additional context**
It seems reasonable that a security focused product would be built with the minimum packages required to perform it's function. Packages such as imagemagick are ok in the workstation, but surely not in the gateway? It seems a somewhat embarrassing oversight that could lead to security problems.

**Comment by adrelanos** [comment]
Most likely not a Whonix issue.

Whonix source code does not require textual string `imagemagick`. Therefore unlikely that Whonix pulls this dependency.

`sudo apt remove imagemagick` shouldn't show any Whonix packages depending on them (unless some Qubes package depends on them). Not happening for me.

Most likely duplicate of https://github.com/QubesOS/qubes-issues/issues/5009

**Comment by h01ger** [comment]
On Wed, Jul 01, 2020 at 02:32:03PM -0700, Patrick Schleizer wrote:
> Most likely not a Whonix issue.

agreed.
 
> `sudo apt remove imagemagick` shouldn't show any Whonix packages depending on them (unless some Qubes package depends on them). Not happening for me.
 
while 'apt remove imagemagick' on my whonix-gw indeed just did that,
there are more packages from src:imagemagick installed and removing
them, removes more packages:

user@host:~$ dpkg -l |grep magick
rc  imagemagick                   8:6.9.10.23+dfsg-2.1    amd64   image manipulation programs -- binaries
ii  imagemagick-6-common          8:6.9.10.23+dfsg-2.1    all     image manipulation programs -- infrastructure
ii  imagemagick-6.q16             8:6.9.10.23+dfsg-2.1    amd64   image manipulation programs -- quantum depth Q16
ii  libmagickcore-6.q16-6:amd64   8:6.9.10.23+dfsg-2.1    amd64   low-level image manipulation library -- quantum depth Q16
ii  libmagickwand-6.q16-6:amd64   8:6.9.10.23+dfsg-2.1    amd64   image manipulation library -- quantum depth Q16
user@host:~$ sudo apt remove imagemagick-6-common
[...]
The following packages will be REMOVED:
  imagemagick-6-common imagemagick-6.q16 libmagickcore-6.q16-6 libmagickwand-6.q16-6 qubes-core-agent qubes-core-agent-networking qubes-gui-agent qubes-input-proxy-sender qubes-usb-proxy qubes-vm-dependencies qubes-whonix qubes-whonix-gateway qubes-whonix-shared-packages-recommended


-- 
cheers,
	Holger

-------------------------------------------------------------------------------
               holger@(debian|reproducible-builds|layer-acht).org
       PGP fingerprint: B8BF 5413 7B09 D35C F026 FE9D 091A B856 069A AA1C

**Comment by adrelanos** [comment]
It's a dependency chain.

    apt-cache show qubes-core-agent

    apt-cache show qubes-core-agent | grep --color imagemagick

`qubes-core-agent` `Depends:` on `imagemagick`

Whonix meta packages depend on `qubes-core-agent`. Therefore I still think most likely duplicate of #5009.

**Comment by h01ger** [comment]
On Thu, Jul 02, 2020 at 02:52:18AM -0700, Patrick Schleizer wrote:
> Whonix meta packages depend on `qubes-core-agent`. Therefore I still think most likely duplicate of #5009.

yes.

i was merely pointing out that imagemagic *is* installed on whonix-gw.


-- 
cheers,
	Holger

-------------------------------------------------------------------------------
               holger@(debian|reproducible-builds|layer-acht).org
       PGP fingerprint: B8BF 5413 7B09 D35C F026 FE9D 091A B856 069A AA1C

**Comment by andrewdavidwong** [comment]
This appears to be a [duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Comment by andrewdavidwong** [comment]
Duplicate of #5009
