### ISSUE TITLE
qvm-sync-clock syncs the wrong time

### ISSUE THREAD

**Issue by SvenSemmler** [QubesOS/qubes-issues#5925]
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
qvm-sync-clock

**Brief summary**
Since today qvm-sync-clock syncs the wrong time. This never happened before.

**To Reproduce**
[user@dom0 ~]$ timedatectl 
      Local time: Thu 2020-07-02 19:58:18 CDT  << correct!
  Universal time: Fri 2020-07-03 00:58:18 UTC
        RTC time: Fri 2020-07-03 06:57:06
       Time zone: America/Chicago (CDT, -0500)
 Network time on: no
NTP synchronized: no
 RTC in local TZ: no
[user@dom0 ~]$ sudo qvm-sync-clock 
[user@dom0 ~]$ timedatectl 
      Local time: Fri 2020-07-03 01:57:25 CDT << incorrect!
  Universal time: Fri 2020-07-03 06:57:25 UTC
        RTC time: Fri 2020-07-03 06:57:25
       Time zone: America/Chicago (CDT, -0500)
 Network time on: no
NTP synchronized: no
 RTC in local TZ: no

**Expected behavior**
syncs correct time

**Actual behavior**
syncs to 6 hours in the future

**Screenshots**
n/a

**Additional context**
qvm-sync-clock appears to be called regularly in a cron job

**Solutions you've tried**
qubes-prefs clockvm '' ... now qvm-sync-clock can't do any harm, but also no good 

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
didn't find anything

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
none

**Comment by GWeck** [comment]
With timezone Europe/Berlin (CEST, +0200), the time stays corrent.

**Comment by SvenSemmler** [comment]
Closing the issue. I am using a sys-net that is based on debian minimal. The ntp service was not installed. Once installed, it works as expected.
