### ISSUE TITLE
Consider moving towards a memory safe language for userspace C programs

### ISSUE THREAD

**Issue by iamahuman** [QubesOS/qubes-issues#5931]
**The problem you're addressing (if any)**
Reduce memory corruption vulnerabilities. TBD

**Describe the solution you'd like**
TBD

**Where is the value to a user, and who might that user be?**
TBD

**Describe alternatives you've considered**
TBD

**Additional context**
Not only a significant effort but also introduces a whole new toolchain to our trust model. May as well never get implemented.
Out of scope: port dependencies as well. Qubes however do get less eyeballs compared to e.g. Xen.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
TBD

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
TBD

**Comment by marmarek** [comment]
Yes, generally a good idea.

**Comment by iamahuman** [comment]
Duplicate of #6614
