### ISSUE TITLE
GPG Error when Updating Fedora-30 TemplateVM to Fedora-32

### ISSUE THREAD

**Issue by Rspigler** [QubesOS/qubes-issues#5936]
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
Updating Fedora TemplateVM

**Brief summary**
Following documentation detailed here:
https://www.qubes-os.org/doc/template/fedora/upgrade/

Fails after step #3: 'Attempt the upgrade process in the new template.'
Specifically, 'GPG Check error' even after importing new keys.

**To Reproduce**
_Steps to reproduce the behavior:_
Follow the detailed documentation:
_1. Ensure the existing template is not running.
_2. Clone the existing template and start a terminal in the new template.
_3. Attempt the upgrade process in the new template.
_4. Import new package signing keys

(I import two keys - the fingerprints are):
97A1 AE57 C3A2 372C CA3A 4ABA 6C13 026D 12C9 44D0
59A7 FE07 F664 C1B2 7687 C5D2 6DEE F051 C481 937A

**Expected behavior**
Upgrade process completes successfully.

**Actual behavior**
Upgrade process fails.

Here is the error info:

warning: /var/cache/dnf/rpmfusion-free-b06e117020f7383b/packages/rpmfusion-free-obsolete-packages-32-2.fc32.noarch.rpm: Header V3 RSA/SHA1 Signature, key ID 100bcd92: NOKEY
RPM Fusion for Fedora 32 - Free                 1.1 MB/s | 1.7 kB     00:00    
Importing GPG key 0xC481937A:
 Userid     : "RPM Fusion free repository for Fedora (31) <rpmfusion-buildsys@lists.rpmfusion.org>"
 Fingerprint: 59A7 FE07 F664 C1B2 7687 C5D2 6DEE F051 C481 937A
 From       : /etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-fedora-32
Is this ok [y/N]: y
Key imported successfully
Import of key(s) didn't help, wrong key(s)?
Public key for rpmfusion-free-obsolete-packages-32-2.fc32.noarch.rpm is not installed. Failing package is: rpmfusion-free-obsolete-packages-32-2.fc32.noarch
 GPG Keys are configured as: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-fedora-32
Public key for faad2-libs-2.9.1-3.fc32.x86_64.rpm is not installed. Failing package is: faad2-libs-1:2.9.1-3.fc32.x86_64
 GPG Keys are configured as: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-fedora-32
Public key for ffmpeg-4.2.2-5.fc32.x86_64.rpm is not installed. Failing package is: ffmpeg-4.2.2-5.fc32.x86_64
 GPG Keys are configured as: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-fedora-32
Public key for ffmpeg-libs-4.2.2-5.fc32.x86_64.rpm is not installed. Failing package is: ffmpeg-libs-4.2.2-5.fc32.x86_64
 GPG Keys are configured as: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-fedora-32
Public key for fuse-exfat-1.3.0-4.fc32.x86_64.rpm is not installed. Failing package is: fuse-exfat-1.3.0-4.fc32.x86_64
 GPG Keys are configured as: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-fedora-32
Public key for gstreamer1-libav-1.16.2-3.fc32.x86_64.rpm is not installed. Failing package is: gstreamer1-libav-1.16.2-3.fc32.x86_64
 GPG Keys are configured as: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-fedora-32
Public key for gstreamer1-plugins-bad-freeworld-1.16.2-5.fc32.x86_64.rpm is not installed. Failing package is: gstreamer1-plugins-bad-freeworld-1.16.2-5.fc32.x86_64
 GPG Keys are configured as: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-fedora-32
Public key for libavdevice-4.2.2-5.fc32.x86_64.rpm is not installed. Failing package is: libavdevice-4.2.2-5.fc32.x86_64
 GPG Keys are configured as: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-fedora-32
Public key for libdca-0.0.7-1.fc32.x86_64.rpm is not installed. Failing package is: libdca-0.0.7-1.fc32.x86_64
 GPG Keys are configured as: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-fedora-32
Public key for libde265-1.0.5-4.fc32.x86_64.rpm is not installed. Failing package is: libde265-1.0.5-4.fc32.x86_64
 GPG Keys are configured as: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-fedora-32
Public key for libmms-0.6.4-13.fc32.x86_64.rpm is not installed. Failing package is: libmms-0.6.4-13.fc32.x86_64
 GPG Keys are configured as: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-fedora-32
Public key for librtmp-2.4-17.20190330.gitc5f04a5.fc32.x86_64.rpm is not installed. Failing package is: librtmp-2.4-17.20190330.gitc5f04a5.fc32.x86_64
 GPG Keys are configured as: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-fedora-32
Public key for live555-2020.04.12-1.fc32.x86_64.rpm is not installed. Failing package is: live555-2020.04.12-1.fc32.x86_64
 GPG Keys are configured as: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-fedora-32
Public key for mjpegtools-libs-2.1.0-19.fc32.x86_64.rpm is not installed. Failing package is: mjpegtools-libs-2.1.0-19.fc32.x86_64
 GPG Keys are configured as: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-fedora-32
Public key for opencore-amr-0.1.5-10.fc32.x86_64.rpm is not installed. Failing package is: opencore-amr-0.1.5-10.fc32.x86_64
 GPG Keys are configured as: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-fedora-32
Public key for rpmfusion-free-appstream-data-32-3.fc32.noarch.rpm is not installed. Failing package is: rpmfusion-free-appstream-data-32-3.fc32.noarch
 GPG Keys are configured as: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-fedora-32
Public key for rpmfusion-free-release-32-1.noarch.rpm is not installed. Failing package is: rpmfusion-free-release-32-1.noarch
 GPG Keys are configured as: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-fedora-32
Public key for vlc-3.0.9.2-3.fc32.x86_64.rpm is not installed. Failing package is: vlc-1:3.0.9.2-3.fc32.x86_64
 GPG Keys are configured as: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-fedora-32
Public key for vlc-core-3.0.9.2-3.fc32.x86_64.rpm is not installed. Failing package is: vlc-core-1:3.0.9.2-3.fc32.x86_64
 GPG Keys are configured as: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-fedora-32
Public key for vo-amrwbenc-0.1.3-12.fc32.x86_64.rpm is not installed. Failing package is: vo-amrwbenc-0.1.3-12.fc32.x86_64
 GPG Keys are configured as: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-fedora-32
Public key for x264-libs-0.159-7.20191127git1771b55.fc32.x86_64.rpm is not installed. Failing package is: x264-libs-0.159-7.20191127git1771b55.fc32.x86_64
 GPG Keys are configured as: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-fedora-32
Public key for x265-libs-3.3-2.fc32.x86_64.rpm is not installed. Failing package is: x265-libs-3.3-2.fc32.x86_64
 GPG Keys are configured as: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-fedora-32
Public key for xvidcore-1.3.7-3.fc32.x86_64.rpm is not installed. Failing package is: xvidcore-1.3.7-3.fc32.x86_64
 GPG Keys are configured as: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-fedora-32
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Error: GPG check FAILED
[user@fedora-32 ~]$

**Comment by marmarek** [comment]
On Sun, Jul 05, 2020 at 04:05:34PM -0700, Robert Spigler wrote:
> RPM Fusion for Fedora 32 - Free                 1.1 MB/s | 1.7 kB     00:00    
> Importing GPG key 0xC481937A:
>  Userid     : "RPM Fusion free repository for Fedora (31) <rpmfusion-buildsys@lists.rpmfusion.org>"
>  Fingerprint: 59A7 FE07 F664 C1B2 7687 C5D2 6DEE F051 C481 937A
>  From       : /etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-fedora-32

Looks like RPM Fusion got their keys wrong in the initial release. See the filename is about fedora-32, but the key description is "Fedora (31)". 
It looks like there is an update in the repo - try installing normal updates first (`dnf update` should do) and only then perform release upgrade.
You can verify if you get the right key with `gpg /etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-fedora-32` command.

**Comment by Rspigler** [comment]
`sudo dnf upgrade --refresh`

Results in:

> Dependencies resolved
Nothing to do
Complete!

Checking `gpg /etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-fedora-32` shows that I do indeed have the Fedora 31 RPMFusion Key.

I guess I need to file this upstream?

**Comment by Rspigler** [comment]
https://bugzilla.rpmfusion.org/show_bug.cgi?id=5693

**Comment by marmarek** [comment]
Just to make sure you are using the right repo: try adding `--enablerepo=rpmfusion-free,rpmfusion-free-updates`.

**Comment by Rspigler** [comment]
That seems to be it! Thanks.  How do I enable that permanently? I tried `sudo dnf config-manager --add-repo /etc/yum.repos.d/rpmfusion-free-updates.repo`but that didn't work.

**Comment by Rspigler** [comment]
I'm confused what this repo is? Why is there an RPMFusion repo, plus an RPMFusion updates repo? For Fedora/Debian/Qubes, there's the repo which contains updates, and then additional repo's for testing/security-testing/etc.

**Comment by kwizart** [comment]
I confirm that both rpmfusion-free and rpmfusion-free-updates (and the related fedora and fedora-updates) are expected to be enabled by default for normal functionality.

**Comment by Rspigler** [comment]
I'm dumb, please disregard.  Fixed.
