### ISSUE TITLE
Korean characters not displayed in web browser

### ISSUE THREAD

**Issue by mfc** [QubesOS/qubes-issues#5937]
**Qubes OS version**
R4.0

**Brief summary**
FF, Chromium in Debian 10, FF in Fedora 32 all can display other non-latin languages like Chinese, Arabic, Japanese, etc. For some reason Korean isn't displayed.

**To Reproduce**
_Steps to reproduce the behavior:_
_1. Go to https://ko.wikipedia.org
_2. See all the unicode boxes

to compare, here is [Japanese wikipedia homepage](https://ja.wikipedia.org) and [Chinese wikipedia homepage](https://zh.wikipedia.org).

**Expected behavior**
Korean characters are also displayed.

**Actual behavior**
Korean characters are not displayed.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
https://www.qubes-os.org/doc/language-localization/

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
https://github.com/QubesOS/qubes-issues/issues/1059
https://github.com/QubesOS/qubes-issues/issues/5914

**Comment by marmarek** [comment]
Looks like some font package not installed by default. It works just fine on my fedora-32 customized template and also in stock fedora-30 template, but not on stock fedora-32 template.

**Comment by iamahuman** [comment]
Try `sudo dnf install naver-nanum-gothic-fonts` in TemplateVM.

For a comprehensive list of other Korean fonts, do `sudo dnf search --all Korean | grep -i font`.

That said, it would be nice if we used the existing GNOME software machinery to tell the user which additional fonts shall be installed, or install Noto Sans or Droid Sans Fallback CJK fonts by default as a catch-all fallback.

**Comment by zpc0** [comment]
This problem seems to be caused by the updated Droid Sans fonts.

`google-droid-fonts-20200215-3.fc32` uses DroidSansFallbackFull.ttf as the fallback fonts, but Hangul has been [removed](https://android.googlesource.com/platform/frameworks/base.git/+/562c45cc8416) from `DroidSansFallbackFull.ttf`.
Therefore, a system that doesn't have other Hangul fonts cannot display Hangul characters correctly.

I think `google-noto-sans-cjk-ttc-fonts` is a better choice. It provides more updated and complete fonts to CJK users.

**Comment by zpc0** [comment]
I'm considering using `@fonts` meta package to fix this issue. Maintaining fonts list is a hard task because it requires knowledge of many languages, so I think using `@fonts` is a simple solution.
Is it ok to add `@fonts` to [packages_fc.list](https://github.com/qubesos/qubes-builder-rpm/blob/master/template_scripts/packages_fc.list)?
If yes, I will send a patch.

**Comment by iamahuman** [comment]
@zpc0 I suppose https://github.com/mozilla/gecko-dev/blob/544653167f12b44d6358cc3a60a6151caca3c85d/gfx/thebes/StandardFonts-linux.inc would be a good reference

**Comment by zpc0** [comment]
> @zpc0 I suppose https://github.com/mozilla/gecko-dev/blob/544653167f12b44d6358cc3a60a6151caca3c85d/gfx/thebes/StandardFonts-linux.inc would be a good reference

Thank you. I checked the difference between `StandardFonts-linux.inc` and qubes fedora-32 template.
The following fonts are missing in the fedora-32 template.

`
  "Abyssinica SIL"
  "Caladea"
  "Carlito"
  "Comfortaa"
  "Jomolhari"
  "Khmer OS"
  "Liberation"
  "Lohit Assamese"
  "Lohit Bengali"
  "Lohit Devanagari"
  "Lohit Gujarati"
  "Lohit Kannada"
  "Lohit Odia"
  "Lohit Tamil"
  "Lohit Telugu"
  "Meera"
  "Mingzat"
  "Montserrat"
  "Noto Color Emoji"
  "Noto Sans CJK"
  "Noto Sans Gurmukhi"
  "Noto Sans Mono CJK"
  "Noto Sans Sinhala"
  "Nuosu SIL"
  "Padauk"
  "PakType Naskh Basic"
  "PT Sans"
  "STIX"
  "Symbola"
  "Waree"
`

**Comment by mfc** [comment]
still a problem in R4.1 with default templates (`debian 11`, `fedora 34`), but not an issue with `whonix-16-ws`.

would be good to have decent (and consistent) font representation in default templates, for instance by relying on externally maintained font meta-packages mentioned earlier in thread. looping in @fepitre so they're aware in case they have thoughts.

**Comment by UndeadDevel** [comment]
Still a problem on 4.2 with `debian-12-xfce` (haven't checked the other templates).

**Comment by mfc** [comment]
also a problem with `fedora-38-xfce` on R4.2, except for all CJK languages not just korean. 

installing `google-noto-sans-cjk` and `google-noto-sans-cjk-ttc-font` solves the problem, inspired from: https://bugzilla.redhat.com/show_bug.cgi?id=2188765#c0 and https://discussion.fedoraproject.org/t/chinese-font-issue-on-fedora-silverblue-39/100015/9

would be really amazing to ensure CJK fonts are included in template releases, ideally through font meta-packages.
