### ISSUE TITLE
4.1: Theme not applied correctly on dom0

### ISSUE THREAD

**Issue by jpds** [QubesOS/qubes-issues#5938]
**Qubes OS version**

4.1.

**Affected component(s) or functionality**

Appearance.

**Brief summary**

If I switch to `Adwaita-dark` in `System Tools > Apperence`, my top panel only appears to partially change the theme.

**Screenshots**

![Screenshot_2020-07-07_17-23-57](https://user-images.githubusercontent.com/29158971/86812751-45a05c80-c077-11ea-9782-103d5ad8e16d.png)

**Comment by blockomat2100** [comment]
For me `xfce4-panel -r` applies the theme for the whole panel.

**Comment by EncryptedGiraffe** [comment]
@blockomat2100 thank you! My panel is finally consistent with the rest of my dark theme! Now I just need to dig into why the window titles are so dark I can't read them. I'm using the arc-dark theme which came with R4.1

And yes, clicking through the themes in `Appearance` changes only that small rightmost section of the panel's color, the rest didn't update until I ran `xfce4-panel -r`

**Comment by 92VV3M42d3v8** [comment]
Issue persists in Qubes 4.1rc1. Can it be some Race condition? As few time it applies correctly.

**Comment by blockomat2100** [comment]
just an update to my previous comment which had the drawback of loosing panel icons because the panel is reloaded.
If I put the theme settings inside `~/.config/gtk-3.0/settings.ini` the theme is automatically applied correctly on boot and you do not need to repeat to reload the xfce-panel everytime.

Example file content:

```
[Settings]
gtk-theme-name=Matcha-dark-sea
```

**Comment by tommytran732** [comment]
> just an update to my previous comment which had the drawback of loosing panel icons because the panel is reloaded. If I put the theme settings inside `~/.config/gtk-3.0/settings.ini` the theme is automatically applied correctly on boot and you do not need to repeat to reload the xfce-panel everytime. (tested on 4.1rc2 and rc3)
> 
> Example file content:
> 
> ```
> [Settings]
> gtk-theme-name=Matcha-dark-sea
> ```

This works for me but the tray icons for apps from other VMs are still light themed. Do you know of a way to fix this?
On another note, I think it is better if you put the settings in `/etc/gtk-3.0/settings.ini` and add `gtk-application-prefer-dark-theme=1` as well.
