### ISSUE TITLE
DNF for Debian 11+

### ISSUE THREAD

**Issue by fepitre** [QubesOS/qubes-issues#5940]
Yum is removed from Debian 11+ repositories and DNF integration for Debian is WIP.

Related threads:
- https://lists.debian.org/debian-devel/2019/09/msg00218.html
- https://groups.google.com/forum/#!msg/qubes-devel/0_HBFHt7vXM/Btoy5RUqCAAJ

Qubes testing integration components:
- https://github.com/fepitre/qubes-libcomps
- https://github.com/fepitre/qubes-librepo
- ~~https://github.com/fepitre/qubes-libsolv~~ (debian MR merged https://salsa.debian.org/debian/libsolv/-/merge_requests/1)
- ~~https://github.com/fepitre/qubes-libmodulemd1~~ (not needed anymore)
- https://github.com/fepitre/qubes-libdnf
- https://github.com/fepitre/qubes-dnf

Freshly created bullseye template as UpdateVM makes dom0 update working.

Based on previous original work of author in https://lists.debian.org/debian-devel/2019/09/msg00218.html, packages have been uploaded to https://mentors.debian.net/packages/uploader/frederic.pierret%40qubes-os.org

**Comment by 0spinboson** [comment]
similar issue seems to be that python-nautilus (for the pdf converter) support is discontinued?

**Comment by fepitre** [comment]
It's replaced by python3-nautilus (https://github.com/QubesOS/qubes-app-linux-pdf-converter/commit/388278abcaf0d9dc3500dfb10017e8f867853306) but generally most of python2 packages are removed from us.

**Comment by 0spinboson** [comment]
I just upgraded a deb10 template to d11 (version 2.1.8), but it complains I can't install qubes-pdf-converter because python-nautilus is missing. Python3-nautilus indeed is installed.

**Comment by unman** [comment]
On Mon, Jul 20, 2020 at 07:26:23AM -0700, Fr??d??ric Pierret wrote:
> It's replaced by python3-nautilus (https://github.com/QubesOS/qubes-app-linux-pdf-converter/commit/388278abcaf0d9dc3500dfb10017e8f867853306) but generally most of python2 packages are removed from us.
> 

Affects qubes-core-agent-nautilus too.
python-nautilus is in sid, so will probably find its way to bullseye.

**Comment by 0spinboson** [comment]
qubes-core-agent-nautilus is installed here, so presumably depends on python3-nautilus. Maybe the | here isn't being interpreted correctly? https://github.com/QubesOS/qubes-app-linux-pdf-converter/blob/master/debian/control
I see it's done slightly differently in core-agent-linux:

in control: `
Package: qubes-core-agent-nautilus
Architecture: any
Depends:
    ${pythonver:Depends}-nautilus,
    qubes-core-qrexec,`

in rules: `
override_dh_gencontrol:
ifneq ($(shell grep -o 'stretch\|buster' /etc/debian_version),)
	echo "pythonver:Depends=python" >> debian/qubes-core-agent-nautilus.substvars
else
	echo "pythonver:Depends=python3" >> debian/qubes-core-agent-nautilus.substvars
endif
	dh_gencontrol`

**Comment by fepitre** [comment]
> qubes-core-agent-nautilus is installed here. (sid only has community ports for ARM)
> Maybe the | here isn't being interpreted correctly? https://github.com/QubesOS/qubes-app-linux-pdf-converter/blob/master/debian/control
> 
> I see it's done slightly differently in core-agent-linux:

Yes we tried another syntax. I would say that I don't know which one is the most hacky/is in the best practive but previous tests show that using '|' was working correctly. Which version of app-linux-pdf-converter do you have?

**Comment by 0spinboson** [comment]
it's offering 2.1.8-1 (but it won't install because it doesn't look for python3-nautilus, which is installed).

**Comment by fepitre** [comment]
@0spinboson do you mind to open an issue for that in order to keep separate the topic please?

**Comment by fepitre** [comment]
Just tried to rebuild those components and I ran into issues. It seems that currently used versions are now too old at least for `libsolv` and `libdnf`. Latest version of `libdnf` uses `libmodulemd2` which is in Debian repos so it allows to ignore the current version 1 component. But, it also requires `libsolv-0.7.0+`. Trying to sync `libsolv` with Debian version, makes needed patches for RPM home directory obsoletes, so work is needed here. Still, even using Debian `libsolv`, just to have at least `libdnf` building with `0.48.0`, with/without updating patches I'm running into the same build issues.

**Comment by fepitre** [comment]
I've updated all the related components (please see description update). We have normally/almost latest versions for each needed components. For example, current implemented version of `DNF` is `4.2.23` instead of the next and latest one `4.4.0` (some build issues) but even Fedora has just updated to this version few days ago. I've opened a PR for `libsolv` on Debian with updated/modified patches so **please help me to review the code** for it. Less duplicate work is done between Debian (@h01ger) and QubesOS the best it is for all of us.

**Comment by h01ger** [comment]
On Sun, Oct 11, 2020 at 03:23:08AM -0700, Frédéric Pierret wrote:
> I've opened a PR for `libsolv` on Debian with updated/modified patches
> so **please help me to review the code** for it.

https://salsa.debian.org/debian/libsolv/-/merge_requests/1/commits is the MR
in question.

Frédéric, did you use this code sufficiently already? (I'm trying to
understand why you are asking for a review.)

On the subject of updating libsolv: I'd give the maintainer some more
time (a week probably) to react on his own and then I'd be happy to ping
Mike and probably do an NMU with his permission - assuming the change is
good. (haven't looked myself yet)


-- 
cheers,
	Holger

-------------------------------------------------------------------------------
               holger@(debian|reproducible-builds|layer-acht).org
       PGP fingerprint: B8BF 5413 7B09 D35C F026 FE9D 091A B856 069A AA1C

Stop saying that we are all in the same boat.
We’re all in the same storm.
But we’re not all in the same boat.

**Comment by fepitre** [comment]
> https://salsa.debian.org/debian/libsolv/-/merge_requests/1/commits is the MR in question. Frédéric, did you use this code sufficiently already? (I'm trying to understand why you are asking for a review.) On the subject of updating libsolv: I'd give the maintainer some more time (a week probably) to react on his own and then I'd be happy to ping Mike and probably do an NMU with his permission - assuming the change is good. (haven't looked myself yet)

I've only tried in Qubes OS context for update but it works (search and download operations only). I'm asking for help into review because I don't know `libsolv` really so if anyone who knows this library and wants to have a look into those modifications, that would be very helpful!

**Comment by fepitre** [comment]
I've updated the description. Debian has merged the related work for `libsolv`. This is nice and big step! **Spoiler alert**: we do have `bullseye` in our testing repo of 4.1 since few days :champagne:

**Comment by h01ger** [comment]
On Tue, Oct 27, 2020 at 07:35:28AM -0700, Frédéric Pierret wrote:
> I've updated the description. Debian has merged the related work for `libsolv`. This is nice and big step! **Spoiler alert**: we do have `bullseye` in our testing repo of 4.1 since few days :champagne: 

yay, nice!

what's the next step needed to get dnf into debian?


-- 
cheers,
	Holger

-------------------------------------------------------------------------------
               holger@(debian|reproducible-builds|layer-acht).org
       PGP fingerprint: B8BF 5413 7B09 D35C F026 FE9D 091A B856 069A AA1C

There are only two kinds of nazis: stupid ones and those without an excuse.
(Volker Strübing)

**Comment by marmarek** [comment]
On Tue, Oct 27, 2020 at 09:47:54AM -0700, Holger Levsen wrote:
> what's the next step needed to get dnf into debian?

Have someone to sponsor uploads of those packages:
https://mentors.debian.net/packages/uploader/frederic.pierret@qubes-os.org/

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by h01ger** [comment]
On Tue, Oct 27, 2020 at 09:51:52AM -0700, Marek Marczykowski-Górecki wrote:
> On Tue, Oct 27, 2020 at 09:47:54AM -0700, Holger Levsen wrote:
> > what's the next step needed to get dnf into debian?
> Have someone to sponsor uploads of those packages:
> https://mentors.debian.net/packages/uploader/frederic.pierret@qubes-os.org/

thanks, that's a good overview! and some nice work it seems!

on a quick look I noticed:

- for several (all?) no ITP/RFP bug exist. this might be ok, if there's one
  for dnf, which reference the libraries, but there's non for dnf, so
  that's not good.
- for several, there are newer upstream versions available.

and then I wonder:

- is it ok to use this issue to discuss the topic 'dnf in debian' or should
  we do that elsewhere, where?
- what's the dependency graph? I guess libdnf, librepo and libcomps are all depends
  of dnf, but where does modulemd1 fit in? (IOW: wondering about the order of
  uploads and thus reviews needed.)


-- 
cheers,
	Holger

-------------------------------------------------------------------------------
               holger@(debian|reproducible-builds|layer-acht).org
       PGP fingerprint: B8BF 5413 7B09 D35C F026 FE9D 091A B856 069A AA1C

Dance like no one's watching. Encrypt like everyone is.

**Comment by fepitre** [comment]
Le 10/27/20 à 6:22 PM, Holger Levsen a écrit :

> On Tue, Oct 27, 2020 at 09:51:52AM -0700, Marek Marczykowski-Górecki wrote:
>  > On Tue, Oct 27, 2020 at 09:47:54AM -0700, Holger Levsen wrote:
>  > > what's the next step needed to get dnf into debian?
>  > Have someone to sponsor uploads of those packages:
>  > https://mentors.debian.net/packages/uploader/frederic.pierret@qubes-os.org/
> 
> thanks, that's a good overview! and some nice work it seems!
> 
> on a quick look I noticed:
> 
> - for several (all?) no ITP/RFP bug exist. this might be ok, if there's one
> for dnf, which reference the libraries, but there's non for dnf, so
> that's not good.

I think one would be easier to manage.



> - for several, there are newer upstream versions available.

Yes. As now I know that I'm having a working basis, I can go for latest stable version available.


> and then I wonder:
> 
> - is it ok to use this issue to discuss the topic 'dnf in debian' or should
> we do that elsewhere, where?

Depending on Marek's suggestion, I would say we can keep this one for this purpose.



> - what's the dependency graph? I guess libdnf, librepo and libcomps are all depends
> of dnf, but where does modulemd1 fit in? (IOW: wondering about the order of
> uploads and thus reviews needed.)
> 

I've written the good order of dependencies in the description:



 - libcomps

 - librepo

 - libdnf

 - dnf



I
 assume now that the case of "libsolv" is solved (:D). For libmodulemd1,
 we don't need it anymore as it's going to be deprecated and current 
build version of related components are using libmodulemd2 (which is 
libmodulemd in Debian). So we are on having only 3 dependencies for DNF.



I'll do my best do upgrade to latest versions soon and redo a send to mentors with proper ITP/RFP.



Best,

Frédéric

**Comment by h01ger** [comment]
Hi Frédéric,

On Tue, Oct 27, 2020 at 10:43:10AM -0700, Frédéric Pierret wrote:
> > - for several (all?) no ITP/RFP bug exist. this might be ok, if there's one
> > for dnf, which reference the libraries, but there's non for dnf, so
> > that's not good.
> I think one would be easier to manage.

ok, fine with me.
 
> > - for several, there are newer upstream versions available.
> Yes. As now I know that I'm having a working basis, I can go for latest stable version available.

cool!
 
> > - is it ok to use this issue to discuss the topic 'dnf in debian' or should
> > we do that elsewhere, where?
> Depending on Marek's suggestion, I would say we can keep this one for this purpose.

ok
 
> > - what's the dependency graph? I guess libdnf, librepo and libcomps are all depends
> > of dnf, but where does modulemd1 fit in? (IOW: wondering about the order of
> > uploads and thus reviews needed.)
> I've written the good order of dependencies in the description:

thanks for repeating it here! :)
 
> I assume now that the case of "libsolv" is solved (:D). For libmodulemd1,
>  we don't need it anymore as it's going to be deprecated and current 
> build version of related components are using libmodulemd2 (which is 
> libmodulemd in Debian). So we are on having only 3 dependencies for DNF.

ah, nice!

> I'll do my best do upgrade to latest versions soon and redo a send to mentors with proper ITP/RFP.

great! looking forward to that!


-- 
cheers,
	Holger

-------------------------------------------------------------------------------
               holger@(debian|reproducible-builds|layer-acht).org
       PGP fingerprint: B8BF 5413 7B09 D35C F026 FE9D 091A B856 069A AA1C

Dance like no one's watching. Encrypt like everyone is.

**Comment by fepitre** [comment]
Le 10/27/20 à 6:22 PM, Holger Levsen a écrit :
> On Tue, Oct 27, 2020 at 09:51:52AM -0700, Marek Marczykowski-Górecki wrote:
>  > On Tue, Oct 27, 2020 at 09:47:54AM -0700, Holger Levsen wrote:
>  > > what's the next step needed to get dnf into debian?
>  > Have someone to sponsor uploads of those packages:
>  > https://mentors.debian.net/packages/uploader/frederic.pierret@qubes-os.org/
> 
> thanks, that's a good overview! and some nice work it seems!
> 
> on a quick look I noticed:
> 
> - for several (all?) no ITP/RFP bug exist. this might be ok, if there's one
> for dnf, which reference the libraries, but there's non for dnf, so
> that's not good.

I think one would be easier to manage.

> - for several, there are newer upstream versions available.

Yes. As now I know that I'm having a working basis, I can go for latest stable version available.

> and then I wonder:
> 
> - is it ok to use this issue to discuss the topic 'dnf in debian' or should
> we do that elsewhere, where?

Depending on Marek's suggestion, I would say we can keep this one for this purpose.

> - what's the dependency graph? I guess libdnf, librepo and libcomps are all depends
> of dnf, but where does modulemd1 fit in? (IOW: wondering about the order of
> uploads and thus reviews needed.)
> 

I've written the good order of dependencies in the description:

   - libcomps
   - librepo
   - libdnf
   - dnf

I assume now that the case of "libsolv" is solved (:D). For libmodulemd1, we don't need it anymore as it's going to be deprecated and current build version of related components are using libmodulemd2 (which is libmodulemd in Debian). So we are on having only 3 dependencies for DNF.

I'll do my best do upgrade to latest versions soon and redo a send to mentors with proper ITP/RFP.

Best,
Frédéric

**Comment by fepitre** [comment]
@h01ger no chance for having `libsolv` patches in upstream: https://github.com/openSUSE/libsolv/pull/407

**Comment by h01ger** [comment]
On Sun, Nov 01, 2020 at 05:38:20AM -0800, Frédéric Pierret wrote:
> @h01ger no chance for having `libsolv` patches in upstream: https://github.com/openSUSE/libsolv/pull/407

I've come to think that libsolv actually is right here and that the root
of the problem is Debian's rpm package using ~/.rpm for the RPM database
instead of /var/lib/rpm as on Fedora. I dunno why this is the case but I
suppose it should be changed.

That said, didn't Mike accept the patch for libsolv so that for now we can
move on?


( & sorry for the delay in replying. I guess I would like to have researched
why Debian's rpm packages does that... and now decided to just sent this
mail as it is.)


-- 
cheers,
	Holger

 ⢀⣴⠾⠻⢶⣦⠀
 ⣾⠁⢠⠒⠀⣿⡁       holger@(debian|reproducible-builds|layer-acht).org
 ⢿⡄⠘⠷⠚⠋⠀ PGP fingerprint: B8BF 5413 7B09 D35C F026 FE9D 091A B856 069A AA1C
 ⠈⠳⣄

There are only two kinds of nazis: stupid ones and those without an excuse.
(Volker Strübing)

**Comment by fepitre** [comment]
> On Sun, Nov 01, 2020 at 05:38:20AM -0800, Frédéric Pierret wrote: @h01ger no chance for having `libsolv` patches in upstream: [openSUSE/libsolv#407](https://github.com/openSUSE/libsolv/pull/407)
> I've come to think that libsolv actually is right here and that the root of the problem is Debian's rpm package using ~/.rpm for the RPM database instead of /var/lib/rpm as on Fedora. I dunno why this is the case but I suppose it should be changed. That said, didn't Mike accept the patch for libsolv so that for now we can move on?

Yes indeed, the main issue here is the choice of Debian to use home directory for RPM database. That will also always generate supplementary work to sync and update with upstream.

We are good and synced with Mike. He has merged the MR few weeks ago already. From our side, I've finished yesterday to update to latest versions related packages and `DNF` and also they are all reproducible! Waiting for Marek's review and approval.

I need to finish the whole overview and probably few fixes but I think I will do a little update soon on Debian to notice that all of our Debian packages are finally reproducible (Xen included!).

**Comment by h01ger** [comment]
On Mon, Nov 30, 2020 at 04:39:36AM -0800, Frédéric Pierret wrote:
> Yes indeed, the main issue here is the choice of Debian to use home 
> directory for RPM database. That will also always generate supplementary
> work to sync and update with upstream.

yes, but things dont have to stay this way. because a.) always and b.) because
src:rpm is being requested to be adopted, see #923352 - https://bugs.debian.org/923352

> We are good and synced with Mike. He has merged the MR few weeks ago already.
> From our side, I've finished yesterday to update to latest versions related
> packages and `DNF` and also they are all reproducible! Waiting for Marek's
> review and approval.

great to hear & kudos!

> I need to finish the whole overview and probably few fixes but I think I will
> do a little update soon on Debian to notice that all of our Debian packages
> are finally reproducible (Xen included!).

neato.


-- 
cheers,
	Holger

 ⢀⣴⠾⠻⢶⣦⠀
 ⣾⠁⢠⠒⠀⣿⡁       holger@(debian|reproducible-builds|layer-acht).org
 ⢿⡄⠘⠷⠚⠋⠀ PGP fingerprint: B8BF 5413 7B09 D35C F026 FE9D 091A B856 069A AA1C
 ⠈⠳⣄

**Comment by fepitre** [comment]
@h01ger I've updated the latest packages: https://mentors.debian.net/packages/uploader/frederic.pierret@qubes-os.org/. Any other thing to do?

**Comment by marmarek** [comment]
We have dnf is in Debian bullseye! Thanks @fepitre @h01ger
