### ISSUE TITLE
Qube Firewall IPv6 addresses in GUI

### ISSUE THREAD

**Issue by jpds** [QubesOS/qubes-issues#5943]
**Qubes OS version**

4.1, or any.

**Affected component(s) or functionality**

Firewall.

**Brief summary**

`qvm-firewall` supports setting IPv6 addresses and "Firewall rules" tab of a qube's Settings supports showing them.

However, one can't actually input IPv6 as the "New address" dialog window ignores the `:` character.

**Comment by andrewdavidwong** [comment]
FYI @marmarta
