### ISSUE TITLE
adding "set -o noclobber" to VM ~/.bashrc prevents starting of applications

### ISSUE THREAD

**Issue by qubesanon** [QubesOS/qubes-issues#5945]
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
VMs will start, but programs will not be launchable through GUI or via qvm-run.

**Brief summary**
When `set -o noclobber` is present in the VM's ~/.bashrc, the VM will start, but it will not launch applications from the GUI, and `qvm-run` will hang indefinitely.

**To Reproduce**
_Steps to reproduce the behavior:_
1. Create a new VM
2. In new VM: `echo 'set -o noclobber' >> ~/.bashrc
3. Restart the VM
4. Start program in VM from GUI, it will never launch
5. From dom0 terminal, run `qvm-run VMNAME ls` and it will hang forever.

**Expected behavior**
Programs start as normal.

**Actual behavior**
Programs do not start.

**Screenshots**
n/a

**Additional context**
n/a

**Solutions you've tried**
n/a

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
I searched issues, https://github.com/QubesOS/qubes-issues/issues/5299 has the same behavior, but a different root cause.
I started a conversation on https://matrix.to/#/#cybersec-qubes_os:matrix.org, which helped teach me new techniques, but I was not able to fix it.

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
https://github.com/QubesOS/qubes-issues/issues/5299 has the same problem, but a different root cause.

Aside: I would love to learn how to debug what is going on here. I got pretty lucky that I figured out what was going on, but if someone fixes this, I'd get a lot out of learning why this broke things. Thank you!

**Comment by qubesanon** [comment]
I've worked around this problem by, you guessed it, not having that line in my RC file, so please take your time on this one, and I'd appreciate any info that will help me understand the mechanism by which this broke Qubes.

**Comment by strugee** [comment]
@qubesanon I doubt this is the problem, but if you run `/bin/sh -l` inside the qube with that line does it print anything besides the shell prompt? You can add the line after you boot the qube so you can get a terminal window before breaking the qube again.
