### ISSUE TITLE
sudo qubes-dom0-update getting packages from fc25 while using fedora-30 as System default template.

### ISSUE THREAD

**Issue by Smith127** [QubesOS/qubes-issues#5947]
**Qubes OS version**
_The version of Qubes OS you're using (e.g., `R4.0`), available via the command `cat /etc/qubes-release` in a dom0 terminal._
Qubes release 4.0 (R4.0)

**Affected component(s) or functionality**
_The component or functionality of Qubes OS that is not working as expected._
dom0 updates

**Brief summary**
_A clear and concise summary of the bug._
Using fedora-30 as a default template.

sudo qubes-dom0-update

(1) No Match for argument
(2) Running transaction check
(3) Package kernel will be installed
    - Package libvirt-daemon-driver will be installed
    - /var/lib/qubes-dom0-updates/packages/  already exists and appears to be complete
    - Successfully verified /var/lib/qubes-dom0-updates/packages **using .fc25** for some reason.

**To Reproduce**
_Steps to reproduce the behavior:_
_1. Go to '...'_
_2. Click on '....'_
_3. Scroll down to '....'_
_4. See error_

sudo qubes-dom0-update

**Expected behavior**
_A clear and concise description of what you expected to happen._
Should get packages from fedora-30 template/repository.

**Actual behavior**
_What actually happened (instead of what you expected to happen)._
Getting packages from fc25.

**Screenshots**
_If applicable, add screenshots to help explain your problem._

**Additional context**
_Add any other context about the problem here._
No answer in #qubes IRC chat.

Default kernel: 4.19.128-1

**Solutions you've tried**
_If applicable, any solutions or workarounds you've already tried._
Tried to enable test repos, security repos, unstable repos, without results.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
_A list of links to the Qubes documentation (or other relevant software documentation) pages you have already consulted._
https://www.qubes-os.org/doc/software-update-dom0/#how-to-update-dom0

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
_A list of links to other bug reports, feature requests, or tasks in the qubes-issues tracker (or "none" if you didn't find any). Do not describe any other unreported bugs, features, or tasks here._

**Comment by andrewdavidwong** [comment]
This is not a bug. In R4.0, dom0 is based on Fedora 25:

https://www.qubes-os.org/doc/supported-versions/#dom0
