### ISSUE TITLE
Hackintosh Thinkpad E15

### ISSUE THREAD

**Issue by ThenOrance** [QubesOS/qubes-issues#5949]
I have tried to hachintosh on my new Thinkpad E15 (Intel i7-10510U / 16GB RAM / 512GB SSD / Radeon RX 640),but it failed.Then I Googled it and found out that there were only me and a German trying to do this work .And it seemed we are facing the same question.

## The OpenCore Result (failed)

![image](https://user-images.githubusercontent.com/40057883/87372801-ff895280-c5ba-11ea-99b4-66a4407c5f2e.png)

## The Clover Result (failed)

![image](https://user-images.githubusercontent.com/40057883/87372823-1039c880-c5bb-11ea-9f45-a9f1e1af3140.png)

## EFI Files

[OC-fail-EFI.zip ](https://www.hackintosh-forum.de/attachment/144785-oc-fail-efi-zip/)
[MO-EFI mit +++++++.zip ](https://www.hackintosh-forum.de/attachment/144787-mo-efi-mit-zip/)

**Maybe you are trying to Hackintosh it too. Please let me know if you get it done.**

**Comment by 0spinboson** [comment]
@ThenOrance wrong issues tracker.

**Comment by ThenOrance** [comment]
> @ThenOrance wrong issues tracker.

I'm not good at English and this is my first time to ask something on Github.

**Comment by andrewdavidwong** [comment]
@ThenOrance, I suggest sending this to the `qubes-users` [mailing list](https://www.qubes-os.org/support/) instead.

**Comment by ThenOrance** [comment]
> @ThenOrance, I suggest sending this to the `qubes-users` [mailing list](https://www.qubes-os.org/support/) instead.

thanks。
