### ISSUE TITLE
network reconnection problems

### ISSUE THREAD

**Issue by tumbletree** [QubesOS/qubes-issues#5956]
**Qubes OS version**
4

**Affected component(s) or functionality**
networking

**Brief summary**
Upon 1. resume from suspension, 2. change of wireless network or 3. addition (then disconnection) of wired network, all qubes lose access to network. Network manager *seems* to be fine. Connectivity is resumed automatically after a ~10 minute period, or restart. Started in last 6 months or less, at a guess.

**To Reproduce**
1. Open one or more qubes, browse.
2. disturb network connections: suspend then resume; change wireless network; plug in / disconnect from wired connection.

**Expected behavior**
Seemless and immediate resumption of qubes' connectivity.

**Actual behavior**
a prolonged period of non-connectivity to the internet from any qube. Resumes in the background after ~10 minutes. Restart also works. 

n.b. Qube Updater proceeded without error messages. Updater is _not_ required to produce this behavior.

**Screenshots**
_If applicable, add screenshots to help explain your problem._

**Additional context**
_Add any other context about the problem here._

**Solutions you've tried**
Restarting network manager via sysctl command in sys-net.
Restart sys-net - can't recall if this works, but that's such a hassle (dependent vms) that a restart is easier.
On/Off wifi, networking via widget.

Only 1. restart, or 2. wait for 10 minutes (maybe more) seem to work. Note that mthod 2 might sometimes fail, but I haven't bothered to 

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
_A list of links to the Qubes documentation (or other relevant software documentation) pages you have already consulted._

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
similar elements https://github.com/QubesOS/qubes-issues/issues/5667

**Comment by andrewdavidwong** [comment]
Possibly related: #3008

**Comment by pabpas** [comment]
Open a terminal in sys-net and run any command with sudo: `sudo ls`
In my system this brings back (wired) connectivity instantly. Don't ask me why. Here an example:

```
Oct 12 19:47:32 sys-net kernel: Generic PHY r8169-30:00: attached PHY driver [Generic PHY] (mii_bus:phy_addr=r8169-30:00, irq=IGNORE)
Oct 12 19:47:33 sys-net kernel: r8169 0000:00:06.0 ens6: No native access to PCI extended config space, falling back to CSI
Oct 12 19:47:33 sys-net kernel: r8169 0000:00:06.0 ens6: Link is Down
Oct 12 19:47:33 sys-net kernel: IPv6: ADDRCONF(NETDEV_UP): ens6: link is not ready
Oct 12 19:49:11 sys-net kernel: r8169 0000:00:06.0 ens6: Link is Up - 1Gbps/Full - flow control rx/tx
Oct 12 19:49:11 sys-net kernel: IPv6: ADDRCONF(NETDEV_CHANGE): ens6: link becomes ready
```
