### ISSUE TITLE
4.1: Unable to update on -testing

### ISSUE THREAD

**Issue by jpds** [QubesOS/qubes-issues#5958]
**Qubes OS version**

4.1

**Affected component(s) or functionality**

`qubes-dom0-update`

**Brief summary**

As of yesterday, my 4.1 install fails to update dom0 with this error:

![Screenshot_2020-07-17_11-19-38](https://user-images.githubusercontent.com/29158971/87776712-17addb80-c820-11ea-8f63-ee1acee7857f.png)

I've tried deleting `/var/lib/qubes/dom0-updates/` on my updates-proxy but the issue persists.

**Comment by fepitre** [comment]
Please check the list before posting such issue. It has been subject of specific mail yesterday for that: https://groups.google.com/d/msg/qubes-devel/IWESHRQfeko/DN9LJ913BQAJ.
