### ISSUE TITLE
Black Screens instead of Login

### ISSUE THREAD

**Issue by stantond** [QubesOS/qubes-issues#5959]
**Qubes OS version**
R4.0.3

**Affected component(s) or functionality**
Unknown

**Brief summary**
After a successful install, I can boot and unlock the disk but can't get any further.

**To Reproduce**
_Steps to reproduce the behavior:_

1. Install and configure Qubes successfully
2. Boot Qubes
3. Enter the Disk Password
4. Switch to the console view to confirm that everything continues to load as expected
5. Wait for the login screen to appear

**Expected behavior**
Login Screen appears

**Actual behavior**
Black screens (multi-monitor). On the primary monitor, I can move the cursor for a few seconds, then it freezes. There is a small 5 x 5 pixel grey square in the top left corner.

**Screenshots**
_If applicable, add screenshots to help explain your problem._

![IMG_20200726_100854](https://user-images.githubusercontent.com/3207366/88475624-a362ee80-cf29-11ea-849d-34a69103f889.jpg)

**Additional context**
_Add any other context about the problem here._

**Solutions you've tried**
I wanted to try this: https://www.qubes-os.org/doc/nvidia-troubleshooting/#boot-in-failsafe but there is no failsafe option in the boot menu, just Qubes and an Advanced Options submenu

Unplugged all USB devices other than keyboard and mouse.

My graphics card is shown as compatible in the compatibility list, but I tried switching to internal graphics anyway and got the same result.

I then tried booting with `rhgb: nouveau.modeset=0 rd.driver.blacklist=nouveau video=vesa:off` and got the same result.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
https://www.qubes-os.org/doc/nvidia-troubleshooting/

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
N/A

**Comment by stantond** [comment]
@andrewdavidwong I've added some additional troubleshooting steps I've tried. Is there anything I can do to diagnose this further?

**Comment by andrewdavidwong** [comment]
> @andrewdavidwong I've added some additional troubleshooting steps I've tried. Is there anything I can do to diagnose this further?

Thanks! Nothing to do now except wait for the devs to get a chance to take a look.

**Comment by andrewdavidwong** [comment]
I've added the `hardware support` label because it sounds like this *might* be a hardware issue, but I'm not certain.
