### ISSUE TITLE
Qubes device Widget Crashed and unable to start.

### ISSUE THREAD

**Issue by 92VV3M42d3v8** [QubesOS/qubes-issues#5960]
**Qubes OS version**
Qubes -release 4.1 April build
**Affected component(s) or functionality**
Device Widget
**Brief summary**
Qubes device widget tray Icon disappeared and now its not there by any restart.

**To Reproduce**
I don't know the inciting event but Its not there now. It was there I first installed this version.
**Expected behavior**
Widget in tray icons
**Actual behavior**
No tray icon

**Screenshots**
_If applicable, add screenshots to help explain your problem._

**Additional context**
Discussed the issue with @marmarta  in #5622

**Solutions you've tried**
none but logs of    "systemctl --user status qubes-widget@qui-devices" providing below

qubes-widget@qui-devices.service - Qubes-Widet service
  Loaded: loaded (/usr/lib/systemd/user/qubes-widget@.service; static; vendor preset: enabled)
 Active: failed (Result: exit-code) since Fri 2020-07-17 06:21:07 EDT; 1h 31min ago
Process: 6062 ExecStart=/usr/bin/widget-wrapper qui-devices (code=exited, status=1/FAILURE)
CPU: 192ms

Jul 17 06:21:07 dom0 systemd [5771]: qubes-widget@qui-devices.service: Scheduled restart job, restart counter is at 3.
Jul 17 06:21:07 dom0 systemd [5771]: Stopped Qubes Widet service.
Jul 17 06:21:07 dom0 systemd [5771]: qubes-widget@qui-devices.service: Start request repeated too quickly.
Jul 17 06:21:07 dom0 systemd [5771]: qubes-widget@qui-devices.service: Failed with result 'exit-code' .
Jul 17 06:21:07 dom0 systemd [5771]: Failed to start Qubes Widet service.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
_A list of links to the Qubes documentation (or other relevant software documentation) pages you have already consulted._

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
_A list of links to other bug reports, feature requests, or tasks in the qubes-issues tracker (or "none" if you didn't find any). Do not describe any other unreported bugs, features, or tasks here._

**Comment by marmarta** [comment]
Sorry for taking so long to get back you, @92VV3M42d3v8 (holidays :) ), but if you still encounter this problem, could you try to run qui-devices in dom0 in console and paste the output here?

**Comment by 92VV3M42d3v8** [comment]
I'm sorry but I am now on qubes build 2020-07-26. I cannot reproduce the issue. I think we might close this issue.

**Comment by marmarta** [comment]
It probably got fixed in the meantime :)
