### ISSUE TITLE
Qubes R4.0 USB attach to HVM works and does not work.

### ISSUE THREAD

**Issue by 1mzec** [QubesOS/qubes-issues#5964]
No answer in #qubes IRC.

**Qubes OS version**
R4.0

**Affected component(s) or functionality**
sys-usb

**Brief summary**
Trying to attach an device from sys-usb to another HVM, it works when using a different device, the mounting works great as well.

**To Reproduce**
(1) sys-usb or dom0 terminal.
(2) attach the usb to the HVM.
$ qvm-usb attach "HVM machine" sys-usb:"id"
Domain 'HVM machine': qrexec not connected

When trying a different USB-device, it works and I can mount it to the "HVM machine".

**Expected behavior**
Should be able to attach and mount USB-device.
**Actual behavior**
qrexec not connected on "USB-device(1)"
Works fine on "USB-device(2)"

**Solutions you've tried**
Attaching a different "USB-device", + mount, works.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
https://www.qubes-os.org/doc/usb-devices/

**Comment by andrewdavidwong** [comment]
What type of USB device and what type of HVM?
