### ISSUE TITLE
dwm-6.1: can't open anything but terminal

### ISSUE THREAD

**Issue by ghost** [QubesOS/qubes-issues#5966]
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
When launching an application, it doesn't show up if using dwm.

**Brief summary**
When launch an application with '[qmenu-am --all](https://github.com/sine3o14nnae/qmenu)' while using XFCE, it works fine, but in conjunction with DWM it doesn't work.

If you try running an application from an AppVM, it won't launch and the VM will stop responding, even if switch back to XFCE.

**To Reproduce**
1. Install DWM with `sudo qubes-dom0-update dwm`
2. Log out and log in to DWM
3. Press Alt+Shift+Enter and try to open an application from an AppVM
4. Log out and log in to XFCE
5. The AppVM is now frozen and needs to be restarted

**Expected behavior**
Applications appear on the screen when launched

**Actual behavior**
Application do not appear on the screen

**Solutions you've tried**
- Use with [qubes-dmenu](https://github.com/raffaeleflorio/qubes-dmenu) (same problem)
- Use this [fork instead](https://github.com/raffaeleflorio/qubes-dwm) instead (same problem)
- Use this [updated fork](https://github.com/martin-paulus/qubes-dwm/tree/dwm-6-2), but it isn't finished (dwm doesn't open)
- Try to get newer version to work myself, but since I don't know C, there was no success either.

**Comment by deeplow** [comment]
I have reproduced this issue via both:
  - `sudo qubes-dom0-update dwm`
  - the fork https://github.com/raffaeleflorio/qubes-dwm

Both lead to a similar problem as the one in the issue. With some differences:
  - the AppVMs didn't seem to freeze
  - I tested switching back to i3wm instead of xfce

**Comment by elric1** [comment]
You need to start the Qubes guids, try something like this:
```qvm-start-gui --all --watch```
And the windows for your domU VMs will appear.

**Comment by deeplow** [comment]
> You need to start the Qubes guids, try something like this:
> `qvm-start-gui --all --watch`

This was all I needed. Thanks
