### ISSUE TITLE
Attempting to open more than ~40 terminal windows results in qvm-run error "command failed with code: 1"

### ISSUE THREAD

**Issue by lczerner** [QubesOS/qubes-issues#5969]
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
qvm-run fails with code 1. After some time using the system or enough open windows I can't open any more using qvm-run

**Brief summary**
 I am using i3 and a lots of urxvt terminals among other things spread though 6 VMs. When I open enough windows (nothing crazy maybe 40 or so) I can't open any more regardless of the vm I am using.
Most of the time, closing some of the terminals helps and I can open something else again.

**To Reproduce**
Keep opening terminal windows in VM until you can't open any more - for me it varies, but at the moment the limit is around 40 after which qvm-run fails with code 1.
I can still open more windows from the VM terminal (urxvt& for example) without any problem. By my shortcut (alt+enter) does not work anymore.

**Expected behavior**
Being able to open "unlimited" amount of windows, or at least as much as my system memory allows.  I have 32GB of RAM in the system and I still have enough free memory in the VM.

**Actual behavior**
qvm-run fails with code 1

**Comment by marmarek** [comment]
This seems to be related to https://github.com/QubesOS/qubes-issues/issues/5343
Generally qrexec connections use inter-VM shared memory which is limited resource. But in fact, you don't need to keep open connection for xterm. For example: `qvm-run VMNAME "xterm </dev/null &>/dev/null & :"`
Qrexec protocol does support just launching a process without keeping the connection open (without this shell boilerplate), but I think it isn't exposed in qvm-run tool right now.

**Comment by lczerner** [comment]
> This seems to be related to #5343
> Generally qrexec connections use inter-VM shared memory which is limited resource. But in fact, you don't need to keep open connection for xterm. For example: `qvm-run VMNAME "xterm </dev/null &>/dev/null & :"`

This seems to be working quite fine, thank you. Is that something that should be done for qubes-i3-sensible-terminal ? I am happy to send a patch if it helps.

-Lukas

**Comment by marmarek** [comment]
Yes, that could be helpful.
Note there is one case where keeping connection open is desirable: when running in DispVM. DispVM is destroyed when that one service closes the connection. Is `qubes-i3-sensible-terminal` used to open disposable VMs too?

**Comment by lczerner** [comment]
AFAICT it is only useful for situations when there is already a vm window avaliable, so the vm must be running. On the other hand I can imagine the situation where I run a program (lets say Firefox) in DispVM, then open a terminal using _qubes-i3-sensible-terminal_ and then close the Firefox later on. Based on your comment I assume the vm will be destroed at that point, regardless of opened terminal. Not sure if that matters much ?
I could possible extract the information about the vm type from the _QUBES_VMNAME(STRING) but that looks like a dirty solution to me.

**Comment by marmarek** [comment]
> Based on your comment I assume the vm will be destroed at that point, regardless of opened terminal.

Yes, that's right. In this case, it doesn't matter whether `qubes-i3-sensible-terminal` keeps the connection or not - it looks only for the initial connection that created the DispVM (firefox in this case).

**Comment by lczerner** [comment]
Sorry for the delay due to my holiday. I did send a PR that solves this issue for me by using qrexec-client directly. Let me know what you think.

Thanks!
-Lukas
