### ISSUE TITLE
Convert To Trusted options are absent in KDE Dolphin

### ISSUE THREAD

**Issue by tasket** [QubesOS/qubes-issues#5971]
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
Guest: Convert data files to Trusted

**Brief summary**
Context menu options for _Convert Pdf/Image to Trusted_ do not appear in KDE apps like Dolphin. This is despite the other Qubes functions like Move/Copy file being available in KDE.

**To Reproduce**
_Steps to reproduce the behavior:_
_1. Run `dolphin`_
_2. Right-click on any Pdf or image file_
_3. Qubes copy + move options are there, but not 'convert to trusted'_

**Expected behavior**
Conversion options available from Dolphin.

**Actual behavior**
Above mentioned options are absent.

**Additional context**
Using a Debian 10 template with KDE installed via `tasksel`.

**Comment by andrewdavidwong** [comment]
@tasket, do you happen to know anything about this?
