### ISSUE TITLE
Boot error generates "/run/initramfs/rdsosreport.txt"

### ISSUE THREAD

**Issue by galyoninion** [QubesOS/qubes-issues#5973]
**Qubes OS version**
_The version of Qubes OS you're using (e.g., `R4.0`), available via the command `cat /etc/qubes-release` in a dom0 terminal._

**Affected component(s) or functionality**
_The component or functionality of Qubes OS that is not working as expected._

**Brief summary**
_A clear and concise summary of the bug._

**To Reproduce**
_Steps to reproduce the behavior:_
_1. Go to '...'_
_2. Click on '....'_
_3. Scroll down to '....'_
_4. See error_

**Expected behavior**
_A clear and concise description of what you expected to happen._

**Actual behavior**
_What actually happened (instead of what you expected to happen)._

**Screenshots**
_If applicable, add screenshots to help explain your problem._

**Additional context**
_Add any other context about the problem here._

**Solutions you've tried**
_If applicable, any solutions or workarounds you've already tried._

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
_A list of links to the Qubes documentation (or other relevant software documentation) pages you have already consulted._

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
_A list of links to other bug reports, feature requests, or tasks in the qubes-issues tracker (or "none" if you didn't find any). Do not describe any other unreported bugs, features, or tasks here._

**Comment by galyoninion** [comment]
I started Qubes OS as usual. When I entered the password and waited to decrypt the disk, the following error was displayed. what is this? How can I solve it from here? I will also post the picture at that time.

information
QubesOS is the latest version of 4.0.2.
The hardware is Thinkpad t420
![_20200728_234111](https://user-images.githubusercontent.com/68936940/88756679-c5d85000-d153-11ea-8146-a3ad6d9c3045.JPG)

**Comment by andrewdavidwong** [comment]
In the future, please help us handle your issue more efficiently by filling out the bug report template.

**Comment by andrewdavidwong** [comment]
Were you able to view the contents of `/run/initramfs/rdsosreport.txt`?

**Comment by galyoninion** [comment]
Yes, you can see the file. However, what is written in the file is a very long sentence. How can I tell you that? Can I transfer the file to USB?

**Comment by andrewdavidwong** [comment]
Hm, sorry, I'm not sure about that. Let's wait for the devs to weigh in to see if it's even necessary.

**Comment by vanWorden** [comment]
I don't know if this is a coincidence but I had the same problem today. 
I looked at the system logs and saw that "fsck failed with error code 4" looks like the problem. I should "RUN fsck MANUALLY". Can I do that from this shell or during boot or do I need a liveCD/USB of Qubes

I've never had to deal with "unexpected inconsistencies" before or had to repair my Qubes install, so I don't know if things are different with Qubes or if I should follow a common Linux guideline?

**Comment by galyoninion** [comment]
understood. Then, can you tell me if you know the cause?

**Comment by vanWorden** [comment]
Unfortunately, I don't know the cause. I didn't have the time to try repairing my install yet but I did a little research.

What I can tell you is: 
I noticed unusual behavior before this error, especially different VM didn't start anymore (I tried opening a terminal or firefox) and then my desktop froze. I did a hard reboot and couldn't get past the emergency shell.

Maybe this issue could be related to [#5196  ](https://github.com/QubesOS/qubes-issues/issues/5196) or some similar issues but that is just a wild guess. 

I had this system running with no boot problems for more than a year (I think) and there shouldn't be problems with disk space since I have a 960GB SSD but you can see in some reports that there are cases where at some point there is some maxed out area that causes trouble. Nonetheless this came totally out of the blue for me.

**Comment by vanWorden** [comment]
Repairing does work from the emergency shell and afterwards I was able to boot Qubes again. My vault VM wouldn't start though and I have to do some more reading what to do next and what might be the culprit.

**Comment by vanWorden** [comment]
The error message near the end of the "journalctl" said to run fsck manually, so I ran:
fsck dev/mapper/qubes_dom0-root

**Comment by gga10** [comment]
Affects 4.1.2

**Comment by DemiMarie** [comment]
@gga10 please open a separate issue
