### ISSUE TITLE
After GRUB Menu -- Black screen with blinking cursor (new installation)

### ISSUE THREAD

**Issue by remagalot** [QubesOS/qubes-issues#5974]
### Qubes OS version:

R4.0.3

### Affected component(s) or functionality:

---

### Steps to reproduce the behavior:

After installation, reboot.

### Expected or desired behavior:
Continue with installation

### Actual behavior:
Black screen with blinding cursor top right

### General notes:
This is using LEGACY Boot 
Dell Precision 3510

---

### I have consulted the following relevant [documentation](https://www.qubes-os.org/doc/):
https://www.qubes-os.org/doc/uefi-troubleshooting/

**Comment by rafaelreis-r** [comment]
I can say this seems to be a real issue. Multiple reports on Qubes User Google Groups.

Happened to me after latest Qubes Update, on my Dell e5470 that has been running Qubes for over a year without a hitch, with kernel-latest.
Boot process goes normally all the way to righ before the xfce login box, and you get a black screen with a mouse cursor that moves, and no response from the system. Not even trying to switch to a different tty works.

Got around it by editing xen.cfg (I use UEFI boot) and rolling back all the way to kernel 4.19.107-1, which booted normally.
