### ISSUE TITLE
Ubuntu 18.04 template does not build correctly out of the box

### ISSUE THREAD

**Issue by aidancully** [QubesOS/qubes-issues#5975]
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
qubes-builder

**Brief summary**
Building an ubuntu template VM fails due to incorrect python version checks. The `app-linux-pdf-converter` and `app-linux-usb-proxy` setup.py scripts contain a python version check to determine if they're being built for dom0 or for the guest, but the ubuntu18.04 default version of python fails this test. 
The app-linux-usb-proxy and app-linux-pdf-converter are not built correctly.

**To Reproduce**
_Steps to reproduce the behavior:_
1. Follow the instructions on https://www.qubes-os.org/doc/templates/ubuntu/. I used a fedora-31 VM to run qubes-builder
2. Configure to build an ubuntu 18.04 (bionic beaver) template VM.
3. Run `make qubes-vm`.

**Expected behavior**
The build should succeed.

**Actual behavior**
The build failed in the `app-linux-pdf-converter` step.

**Screenshots**
```
install -m 0644 qvm-convert-pdf.desktop /home/user/qubes-src/app-linux-pdf-converter/debian/tmp/usr/share/kde4/services
make[2]: Leaving directory '/home/user/qubes-src/app-linux-pdf-converter'
make[1]: Leaving directory '/home/user/qubes-src/app-linux-pdf-converter'
   dh_install
dh_install: Cannot find (any matches for) "usr/lib/qubes/qpdf-convert-server" (tried in ., debian/tmp)

dh_install: qubes-pdf-converter missing files: usr/lib/qubes/qpdf-convert-server
dh_install: Cannot find (any matches for) "usr/bin/qvm-convert-pdf" (tried in ., debian/tmp)

dh_install: qubes-pdf-converter missing files: usr/bin/qvm-convert-pdf
dh_install: missing files, aborting
debian/rules:11: recipe for target 'binary' failed
make: *** [binary] Error 25
dpkg-buildpackage: error: fakeroot debian/rules binary subprocess returned exit status 2
make[2]: *** [/home/user/qubes-builder/qubes-src/builder-debian//Makefile-legacy.debian:50: dist-package] Error 2
make[1]: *** [Makefile.generic:191: packages] Error 1
make: *** [Makefile:227: app-linux-pdf-converter-vm] Error 1
```

**Additional context**
_Add any other context about the problem here._

**Solutions you've tried**
Investigation revealed that the `setup.py` used for `app-linux-pdf-converter` had an incorrect check for the python version for dom0 vs. the guest. The /usr/bin/python provided in ubuntu18.04 is python2.7, so this version check:
```
if sys.version_info[0:2] < (3, 7):
    # on older python install just tests (dom0 package)
    packages = ['qubespdfconverter.tests']
else:
    packages = ['qubespdfconverter', 'qubespdfconverter.tests']
```
incorrectly filtered out installation of the qubespdfconverter package. I changed this to `if False`, and the build succeeded. A similar `sys.version_info` bug appears to exist in `app-linux-usb-proxy`.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
_A list of links to the Qubes documentation (or other relevant software documentation) pages you have already consulted._

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
_A list of links to other bug reports, feature requests, or tasks in the qubes-issues tracker (or "none" if you didn't find any). Do not describe any other unreported bugs, features, or tasks here._

**Comment by 0x9060** [comment]
@aidancully could you elaborate on where exactly you changed that python code? I'm grepping and can't seem to find it...

Thanks!

**Comment by aidancully** [comment]
@0x9060 Those files were in the ubu1804 chroot, but the source comes from https://github.com/QubesOS/qubes-app-linux-pdf-converter/blob/b83e3547d67ab91ae55173b4079a8ec0d2dab699/setup.py#L30-L34 and https://github.com/QubesOS/qubes-app-linux-usb-proxy/blob/49f9dd18e97be517485f6a37257c3bb3e38d5497/setup.py#L28

**Comment by unman** [comment]
The diagnosis here is close but incorrect. Set-up.py is called with python3, and the Ubuntu version is 3.6

**Comment by icequbes1** [comment]
The real fix for this is to exclude building app-linux-pdf-converter for a bionic $DIST.

There's already exclusions for stretch, jessie, centos7, and centos8 for this very reason (python 3.7+ is required and bionic provides 3.6 by default) in app-linux-pdf-converter/Makefile.builder, just add `bionic` to it:

```
  # needs python 3.7+ - exclude stretch, jessie, and centos[78]
  ifeq ($(filter $(DIST), stretch jessie centos7 centos8),)
    DEBIAN_BUILD_DIRS := debian
    RPM_SPEC_FILES := rpm_spec/qpdf-converter.spec
  endif
```
