### ISSUE TITLE
enormous .xsession-errors.old

### ISSUE THREAD

**Issue by marmarta** [QubesOS/qubes-issues#5979]
**Qubes OS version**
R4.1

**Affected component(s) or functionality**
everything

**Brief summary**
icon-receiver gets stuck in a loop of errors and produces 121GB `.xsession-errors.old` file. (or bigger. That's just my pool size).

```
Traceback (most recent call last):
  File "/usr/lib64/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/lib/qubes/icon-receiver", line 259, in handle_pending_events
    for ev in iter(self.conn.poll_for_event, None):
  File "/usr/lib/python3.8/site-packages/xcffib/__init__.py", line 569, in wrapper
    self.invalid()
  File "/usr/lib/python3.8/site-packages/xcffib/__init__.py", line 559, in invalid
    raise ConnectionException(err)
xcffib.ConnectionException: xcb connection errors because of socket, pipe and other stream errors.
```

**Comment by rmol** [comment]
I'm seeing this too, but only with XFCE. It doesn't happen for me with i3. I've put together a PR that helps, by having `icon-receiver` retry the xcb connection, so eventually (after 6-7 seconds on my system, usually) the situation resolves and the log spam stops. The fact that it seems to be XFCE-specific suggests that there might be more that could be done to correct it -- adjusting ordering/timing of autostart tasks, maybe, or introducing a delay either when `icon-receiver` starts, or when errors are encountered? I'm just not familiar enough with the pieces in play here; I ran into it tangentially when testing other things under 4.1.
