### ISSUE TITLE
Poor UX/UI handling of no free space in TemplateVM

### ISSUE THREAD

**Issue by mfc** [QubesOS/qubes-issues#5984]
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
* all qubes based on TemplateVM
* TemplateVM
* Qubes Update widget

**Brief summary**
When a TemplateVM has no free space left, it and any qubes based on it can start, however no applications can be run (whether GUI or CLI).

interacting directly with any qubes based on this TemplateVM or the TemplateVM itself results in no errors, just hanged commands. so running something like `qvm-run YourQubeBasedOnTemplateVM gnome-terminal` in dom0 results in YourQube starting but gnome-terminal not running. 

**To Reproduce**
Have TemplateVM with no free space.
1. Try to run a program in a qube/AppVM based on this TemplateVM
2. the qube starts
3. the program doesn't run
4. no error message

1. Try to run a program in the TemplateVM
2. the TemplateVM starts
3. the program doesn't run
4. no error message
1. Try updating the problematic TemplateVM with Qubes Updater
2. no errors, green checkmark, no updates

**Expected behavior**
clear communication to user that the TemplateVM from which the qube is based needs its size to be increased. 

**Actual behavior**
No communication to user why applications within the qube are not working, why applications within the TemplateVM are not working, with the Qubes Updater can't update the TemplateVM.

**Solutions you've tried**
only by running in dom0 `qvm-run -u root --no-gui -p YourTemplateVM 'apt update'` and `qvm-run -u root --no-gui -p YourTemplateVM 'apt upgrade'` did I receive errors saying there is no free space in the TemplateVM. Increasing the TemplateVM's private/system storage solved the issue.

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
There are many issues related to running out of space on your full disk, I did not find any issues related to a TemplateVM running out of free space and the results (and lack of user-facing communication).

**Comment by marmarek** [comment]
In R4.1 disk widget do monitor in-VM disk space usage too. (https://github.com/QubesOS/qubes-issues/issues/1872)

**Comment by deeplow** [comment]
Citing here user feedback [from the forum](https://qubes-os.discourse.group/t/in-4-1-please-increase-default-sizes-for-system-storage-and-private-storage/1581/1):

> oijawyuh says:
>  [...] And in the second case, the system storage of the TemplateVM was full. Now to discover these problems, it took me a long time because there’s no alert system and I’m not a techy guy. And duckduckgoing (not googling) the problem would certainly not provide the right solution.
> [...]
> Recommendation 2: Include an alert system when either storage reaches 90% capacity in a given TemplateVM or AppVM.

This last part seems to match exactly the issue's title

**Comment by ninavizz** [comment]
Derp. Yeah, personally encountering this is actually why I included available disk space in the appmenu, so that it'll more readily be discoverable to users. A lot of folks really liked it, and a lot felt it'd be clutter in the menu. My suggestion on putting it there, would be to make it an optional inclusion there after Search is added to the new appmenu.

**Comment by deeplow** [comment]
> Derp. Yeah, personally encountering this is actually why I included available disk space in the appmenu, so that it'll more readily be discoverable to users.

Could it be a "just in time" thing? I.e. only show it in the menu when it was above 80% for example. That way it wouldn't clutter the menu when not needed.

**Comment by ninavizz** [comment]
@deeplow Ooh, meelikey that!
