### ISSUE TITLE
partial upgrade to Debian "bullseye" breaks X

### ISSUE THREAD

**Issue by ncm** [QubesOS/qubes-issues#5985]
### Qubes OS version:

4.0.3

### Affected component(s) or functionality:

Debian VM upgrade

---

### Steps to reproduce the behavior:

1. Install debian-10 VM template, clone it as debian-10-clone-1
2. Start debian-10-clone-1 template
3. In template: apt-get update; apt-get upgrade
4. Edit /etc/apt/sources.list to point to bullseye instead of buster
5. Edit /etc/apt/sources.list.d/qubes-r4.list to point to bullseye instead of buster
6. apt update; apt install xserver-xorg-input-qubes
7. Shut down debian-10-clone-1
8. Start debian-10-clone-1
9. In dom0: qvm-run -p --no-gui debian-10-clone-1 "bash -i"
10. In debian-10-clone-1: ps ax | grep X

### Expected or desired behavior:

Expect to be able to run X programs in the updated VM template.

### Actual behavior:

X server not running. /home/user/.xsession-errors reports a
version mismatch.

### General notes:

Step 6 brings in various additional packages as dependencies.
Normally, one would not upgrade just one package from the
repository, but this seems to be the minimal reproduction.

I.e.: Also upgrading other packages from the qubes-r4.list
repository doesn't help.  Apparently other xserver-xorg
packages from upstream are needed in order not to break X,
but not listed as dependencies. It appears that, at least, an 
additional dependence on, perhaps,  xserver-xorg-core >= 2:1.20.8 
is needed.

This failure, which breaks the template, would be encountered  
when pointing /etc/apt/sources.list.d/qubes-r4.list at the qubes 
bullseye repository and "apt upgrade"-ing, which is needed to 
bring in selected up-to-date programs from the upstream debian 
repository.

---

**Comment by johanna-a** [comment]
I think this is due to issue #6287, where python3-qubesdb has a dependency on python3 << 3.9
Anyhow, I managed to upgrade the standard debian-10 template to Debian "bullseye" just now by rebuilding the python3-qubesdb package and removing the (<<3.9) part of the python3 dependency. 
It's a hack, I needed a debian-11 template for a specific purpose, so I won't be running it enough to say wether it still works in all qubes-related regards. But qubes-gui-agent works at least.

**Comment by unman** [comment]
Debian-11 is a testing release, and it is expected that some things will break.
Currently, the process of upgrading from debian-10, and installing Qubes packages for Debian-11, produces a fully working system.
@ncm @andrewdavidwong  In view of above, I suggest this issue be closed
