### ISSUE TITLE
qvm-shutdown on paused VMs behaves oddly

### ISSUE THREAD

**Issue by 3hhh** [QubesOS/qubes-issues#5987]
**Qubes OS version**
4.0

**Affected component(s) or functionality**
`qvm-shutdown`

**Brief summary**
`qvm-shutdown` hangs for a while and then apparently kills paused VMs.

**To Reproduce**
```
qvm-run --dispvm surfing-dvm xterm
qvm-pause disp1234
qvm-shutdown --wait disp1234
```

**Expected behavior**
`qvm-shutdown` performs the shutdown. Possibly even gracefully (i.e. by unpausing the VM first).

**Actual behavior**
`qvm-shutdown` hangs for 10s or so. Then it apparently kills the VM.

**Recommendation**
From my point of view it would be sensible to handle paused VMs as follows:

`qvm-shutdown`: Unpause and shutdown gracefully as usual.
`qvm-kill`: Do not unpause, remove it from memory instantly (shouldn't take 10s).

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
#5967

**Comment by andrewdavidwong** [comment]
I can imagine that there might be a security concern here. If a VM was paused because it was doing something malicious, then I suppose unpausing it could be dangerous, even if only to shut it down. If that's the reason for the current behavior, perhaps the user should be prompted when attempting to a shut down a paused VM. Also, it may very well be that the user attempting the shutdown forgot that the VM was paused and would be grateful to be reminded.

**Comment by 3hhh** [comment]
> I can imagine that there might be a security concern here. If a VM was paused because it was doing something malicious, then I suppose unpausing it could be dangerous, even if only to shut it down. If that's the reason for the current behavior, perhaps the user should be prompted when attempting to a shut down a paused VM. Also, it may very well be that the user attempting the shutdown forgot that the VM was paused and would be grateful to be reminded.

That's what `qvm-kill` is for. Anyway this is not about the GUI in qubes-manager which allows to kill or unpause only anyway.

If a user manages to mistype `qvm-shutdown` vs `qvm-kill` I am reluctant to feel sorry. And if he forgot about that malicious paused VM, then apparently it wasn't so bad at all.

**Comment by andrewdavidwong** [comment]
> That's what `qvm-kill` is for. Anyway this is not about the GUI in qubes-manager which allows to kill or unpause only anyway.
> 
> If a user manages to mistype `qvm-shutdown` vs `qvm-kill` I am reluctant to feel sorry.

The user not knowing the difference seems much more likely than a typo.

> And if he forgot about that malicious paused VM, then apparently it wasn't so bad at all.

Oh, those were meant to be two separate examples.

**Comment by zaz** [comment]
This is still an issue and may become more prominent with the WIP implementation of [pre-loaded disposable VMs](https://github.com/QubesOS/qubes-issues/issues/1512).

### Expected behavior

`qvm-shutdown` should immediately terminate with the error that the domain is paused and a specific return code so that it can be chained together in a bash script with `qvm-kill` as a fallback.

### Actual behavior

```console
$ qvm-start myvm
$ qvm-pause myvm
$ time qvm-shutdown myvm
default-dvm: Shutdown error: Got empty response from qubesd. See journalctl in dom0 for details.

real    1m0.141s
```

During this time, `qvm-ls` and associated GUI is unusable.

**Comment by zaz** [comment]
Traceback if `qvm-shutdown` is killed while hung:

```
$ qvm-shutdown default-dvm
^CTraceback (most recent call last):
  File "/usr/bin/qvm-shutdown", line 5, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.11/site-packages/qubesadmin/tools/qvm_shutdown.py", line 88, in main
    vm.shutdown(force=force)
  File "/usr/lib/python3.11/site-packages/qubesadmin/vm/__init__.py", line 115, in shutdown
    self.qubesd_call(self._method_dest, 'admin.vm.Shutdown')
  File "/usr/lib/python3.11/site-packages/qubesadmin/base.py", line 76, in qubesd_call
    return self.app.qubesd_call(dest, method, arg, payload,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/qubesadmin/app.py", line 787, in qubesd_call
    return_data = client_socket.makefile('rb').read()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/socket.py", line 706, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
```

But even if you kill `qvm-shutdown`, `qvm-ls` remains unusable for the full minute.

**Comment by marmarek** [comment]
See #8580,  qvm-shutdown on paused VMs is already adjusted in R4.3.
