### ISSUE TITLE
Sleeping VMs cannot be woken up

### ISSUE THREAD

**Issue by 3hhh** [QubesOS/qubes-issues#5996]
**Qubes OS version**
4.0

**Affected component(s) or functionality**
core

**Brief summary**
VMs that go to sleep (ACPI S1-S4) out of their own accord cannot be woken up by Qubes OS.

**To Reproduce**

(Linux example, reproducible with the default Qubes OS kernel:)
1. Open a VM terminal:
   ```
   sudo su
   echo freeze > /sys/power/state
   ```
   (Will make the kernel go to S1 sleep. Use `mem` for S3.)
2. Attempt to bring up the VM again (Side note: `qvm-shutdown` won't work neither).

**Expected behavior**

There is a way to wake VMs from ACPI sleep states.

**Actual behavior**

There is not. Only `qvm-kill` to kill the VM.

This probably also affects Windows HVMs and the like.

**Solutions you've tried**
- `virsh dompmwakeup` only works if the sleep was triggered by `dompmsuspend` and otherwise complains that "the domain is not suspended".
- `xl trigger power`: Usually pressing the power button brings up physical machines from sleep. The trigger however only reaches VMs in hvm mode (pvh doesn't appear to create ACPI IRQs, cf. `cat /proc/interrupts | grep acpi`) and even there it appears to have no effect on sleeping VMs (it does shut down active VMs though).
- `xl trigger nmi ; xl trigger s3resume`: Appear to have no effect either.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
None.

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
https://bugzilla.redhat.com/show_bug.cgi?id=1223541
discussion @#5988

**Comment by andrewdavidwong** [comment]
> VMs that go to sleep (ACPI S1-S4) out of their own accord

Out of curiosity, is there a common use case for this? I can't say I've ever encountered it myself.

**Comment by 3hhh** [comment]
> > VMs that go to sleep (ACPI S1-S4) out of their own accord
> 
> Out of curiosity, is there a common use case for this? I can't say I've ever encountered it myself.

I guess most people wouldn't recognize it and assume that Qubes OS or their VM just had some hiccup or so.

Windows power settings usually have some sleeping enabled by default afaik, for Android it's likely even more aggressive. Linux kernels may have e.g. `CONFIG_PM_AUTOSLEEP` set (the default Qubes kernel currently doesn't) or some user space power management tools may put a VM to sleep.

Xen can block the deeper sleep states by not advertizing ACPI, but not S1.

Of course having it would be useful for energy savings. ;-)

Currently however a VM going to sleep during e.g. lunch break means that all unsaved data inside that VM is lost.
