### ISSUE TITLE
 DNF error: Error unpacking rpm package naver-nanum-gothic-fonts-3.020-16.20140930.fc24.noarch

### ISSUE THREAD

**Issue by MiguelNiblock** [QubesOS/qubes-issues#5998]
**Qubes OS version**
4.0.1

**Affected component(s) or functionality**
Installer

**Brief summary**
When installing from USB, I get the following error during the installation process: 
`The following error occurred while installing. This is a fatal error and installation will be aborted. 
DNF error: Error unpacking rpm package naver-nanum-gothic-fonts-3.020-16.20140930.fc24.noarch`

As possible related errors, at boot time I see the following in the terminal screen:
`[21.522294] ACPI Error: [\_PR_.CPU0._CST] Namespace lookup failure, AE_NOT_FOUD (20170728/psargs-364)`

**Additional context**
I have reviewed system requirements and my Thinkpad T450s meets them. BIOS virtualization is enabled. I don't get any "Unsuported Hardware" warnings.

According to the HCL, Thinkpad T450s has been reported to work on some R3.x versions. There is no entry there for R4.x as of now though.

**Comment by iamahuman** [comment]
Some ACPI errors are pretty common (damn firmware vendors) and can be mostly ignored.
