### ISSUE TITLE
qubes_security_level service

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#6]
**Reported by joanna on 6 Apr 2010 17:10 UTC**
...and display a warning to the user, that e.g. without IOMMU/VT-d there is no point of having a NetVM, as it cannot be securely isolated on a system without VT-d.

Migrated-From: https://wiki.qubes-os.org/ticket/6

**Comment by rootkovska** [comment]
Now tracked as part of the #2134.
