### ISSUE TITLE
Allow Qubes Domains widget to start VMs

### ISSUE THREAD

**Issue by GWeck** [QubesOS/qubes-issues#6007]
**The problem you're addressing (if any)**
The Q widget in the task bar allows to perform several actions for running VMs (Settings, Pause, Shutdown, and Run Terminal). In order to start a stopped VM, however, the Qube manager has to be started.

**Describe the solution you'd like**
It would be nice to be able not only to stop running VMs, but also to start non-running ones from the widget without having to resort to the Qube manager. At least, it would make the functionality of the widget more symmetric.

**Where is the value to a user, and who might that user be?**
VMs could be started from here without having to run the Qube manager or entering a shell command.

**Additional context**
A command like "Start new Qube" in the wiget coud display a list of stopped VMs to select one of them for starting.

**Comment by marmarek** [comment]
You can use also applications menu for that, it doesn't need to be qube manager.

**Comment by GWeck** [comment]
That's right, but the Q widget seems to me a logical place where to search for such a function. It is just a matter how users look for such a function.

@ninavizz: Do you have any information about how to model users' thoughts???

**Comment by unman** [comment]
I rarely use the Q widget because reasons.
It's almost unmanageable as it is with multiple running qubes, and adding stopped qubes to the mix would make the situation worse.
**If** this were implemented, then I'd suggest nesting the Stopped qubes off the main menu.

> @ninavizz: Do you have any information about how to model users' thoughts???

I would be interested in the reply to this question.

**Comment by airelemental** [comment]
> the Q widget seems to me a logical place where to search for such a function

I always thought of Q widget as pertaining to active VMs (current cpu usage, current RAM usage), whereas the applications menu launches VMs.

**Comment by ninavizz** [comment]
@GWeck We're about to launch a big study on Qubes users interests, and this is a terrific thing to probe into. TY for flagging!

**Comment by ninavizz** [comment]
I'm working on a redesign of the app menu right now, and will be sharing a few different "takes" on it with users. One of the takes I'm considering, merges the functionality of the "Domains Menu" in the tray (what I think @GWeck was calling the "Q Widget," and the App Menu, so that the group of Qubes a user sees in the App Menu is which ones are open, and specific controls available for each.

**Comment by ninavizz** [comment]
(also, we have yet to delve into interviews with user research, and are just beginning to parse survey results; will not have conclusive evidence around what users need, until interviews are done).

**Comment by andrewdavidwong** [comment]
> the "Domains Menu" in the tray (what I think @GWeck was calling the "Q Widget")

Yes, you're both referring to the same thing. Technically, this widget is called "Qubes Domains." (This can be seen by hovering over the icon.) It's important that people not rely on referring to it as "the Q widget," since the icon is no longer a "Q" in 4.1.

> ...the first group of Qubes a user sees would be...

UX question for you: Do you find this use of the term "qubes" to be confusing? We intentionally lowercase it when referring to VMs to avoid ambiguity with Qubes OS as a whole. This is off-topic in this issue, but we have a separate issue for it: #1015. (Let's discuss there, if you like.)

> Template VMs, App VMs, and Disp-VMs, would also be grouped, and their groups collapsible, so the user is not forced to see all available Qubes in the app menu in a single view. Curious what others might think of that?

Sounds pretty good. Personally, I'd want additional grouping: either custom user-defined groups or, if not that, at least grouping all ServiceVMs (sys-net, sys-firewall, sys-usb, etc.). The problem here is that, if a user creates a custom ServiceVM (e.g., sys-vpn), and it doesn't automatically get included in the ServiceVM group, then that could be really annoying.

**Comment by ninavizz** [comment]
I should never try spelling `qubes` without adequate coffee. That is truly the best answer that I can offer, to the above @andrewdavidwong. I fully agree with your sentiment as it pertains to my comment, and will edit accordingly. ;)

**Comment by andrewdavidwong** [comment]
Oh, I wasn't trying to call you out! I honestly want to know whether it's a good idea from a UX perspective and how we should handle it. You're certainly far from the only one who capitalizes it when referring to VMs.

**Comment by ninavizz** [comment]
@GWeck Question for you: why would you want to "start a VM" when not  also desiring to just open an app? Working on App Menu redesign stuff atm, and curious to learn your motivations behind the question.

**Comment by unman** [comment]
On Fri, Feb 05, 2021 at 01:59:25PM -0800, Nina Eleanor Alter wrote:
> @GWeck Question for you: why would you want to "start a VM" when not  also desiring to just open an app? Working on App Menu redesign stuff atm, and curious to learn your motivations behind the question. 
> 

There are plenty of cases where one might want a qube started without
"opening an app" - e.g. gpg or ssh backends, shared file servers,
caching proxies. Some of these may be automatically started when needed,
but not all.

**Comment by GWeck** [comment]
That's the same for me. There are situations where I just need a VM running in the backgroud, e.g. a recipient for a file copy (without wanting to wait for the VM to start when I actually start the copy operation), or later on to start an application without delay. This is especially important with Windows VMs which normally take sevral minuts to start.

**Comment by deeplow** [comment]
> @unman: I would prefer to have just one entry in the Q widget menu, something like "Start new qube", and the list of stopped qubes nested under this entry.

I think there is a better solution here that can be used straight away by users who want it. And not adding this extra cognitive cost to menus given most will probably not use it.

The solution is creating a menu shortcut called `<VM_NAME> start` which runs the command `qvm-start --quiet <VM_NAME>`. This actually already happens for some VMs (HVMs only, I think).

**Comment by marmarek** [comment]
You can add this menu entry always (see available applications in settings dialog), it's just selected by default for HVM only

**Comment by GWeck** [comment]
This solution works, o.k. But I am still not satisfied with it, for the following reasons:

- You end up with just one more Icon on the desktop and/or in the task bar. In R4.0 that is just a coloured padlock, which optically does not mean anything, and if you have already a lot of icons there, you will easliy miss it among the others.
- For each VM that you wish to start this way, you will have one additional icon, thus cluttering your desktop or task bar. Having just one command to start a VM concentrates this in one place. I would argue that the cognitive cost of this one command is less than that of several icons, but this is probably a personal preference.
- For non-HVMs, you first have to enable the start command in the VM's menu, a point that is not obvious - see your discussion above.

**Comment by marmarek** [comment]
>     * You end up with just one more Icon on the desktop and/or in the task bar. In R4.0 that is just a coloured padlock, which optically does not mean anything, and if you have already a lot of icons there, you will easliy miss it among the others.

Well, if you choose to _additionally_ copy them into desktop/task bar, then yes. The method I described is adding it to the applications menu, together with other entries to start applications. OTOH if you choose to copy all app/qube starting icons to the desktop/tark bar, then why this isn't an issue for ordinary applications and only for "start qube" entry?

**Comment by GWeck** [comment]
Copying app starting icons for any VMs is indeed not such a good idea. I would restrict this to apps started from dom0, like for instance the screenshot utility.

Starting VMs from the applications menu, on the other hand, can be cumbersome if you have a lot (say 40 or more) VMs, especially if you use the Whiskers menu, because you have to scroll a lot.

What I am looking for is just **one** menu entry "Start VM" at **one** place which then opens a selection menu containing all not yet started VMs.

**Comment by ninavizz** [comment]
@GWeck I'm currently working on the AppMenu, and am working this idea into that (via incorporating much of the Domains Widget functionality into it). [Thoughts (pls to share over there](https://github.com/QubesOS/qubes-issues/issues/5677#issuecomment-779511820), if you have any outside the specific request of the Start Qube bit this issue is about)?

**Comment by GWeck** [comment]
Just one more item on the original request: I had to stop all VMs and the Qube manager for a test. When the test was done, restarting sys-usb and the other service VMs could only be done via CLI or by starting the Qube manager - or am I missing something there? This is somewhat asymmetric, as I can shut these VMs down from the tool bar.

@ninavizz I am collecting ideas and will soon be back...

**Comment by ninavizz** [comment]
I believe you can open all VMs with QubesManager, but I agree—it'd be nice to be able to more easily do that, even if you only do it rarely. My own, non-user opinion, teehee. :)

**Comment by deeplow** [comment]
> **Describe the solution you'd like**
> It would be nice to be able not only to stop running VMs, but also to start non-running ones from the widget without having to resort to the Qube manager. At least, it would make the functionality of the widget more symmetric.

> That's the same for me. There are situations where I just need a VM running in the backgroud, e.g. a recipient for a file copy 

@GWeck I would say the new menu (available in Qubes 4.2) tackles the original issue and thus this can be closed. Would you agree?

![menu1](https://github.com/QubesOS/qubes-issues/assets/47065258/a5682f1b-953b-47bd-b3a8-786f196859bd)
