### ISSUE TITLE
Google Groups now doesn't allow web viewing of mailing list content without Google sign-in

### ISSUE THREAD

**Issue by mfc** [QubesOS/qubes-issues#6008]
**Affected component(s) or functionality**
all Qubes mailing lists hosted on Google Groups:
* [qubes-announce](https://groups.google.com/group/qubes-announce)
* [qubes-users](https://groups.google.com/group/qubes-users)
* [qubes-devel](https://groups.google.com/group/qubes-devel)
* [qubes-project](https://groups.google.com/group/qubes-project)
* [qubes-translation](https://groups.google.com/group/qubes-translation)

**Brief summary**
Google Groups now requires user to sign-in in order to access content from mailing lists. Previously the user could access past content without signing in.

Only [qubes-users](https://www.mail-archive.com/qubes-users@googlegroups.com/maillist.html) and [qubes-devel](https://www.mail-archive.com/qubes-devel@googlegroups.com/maillist.html) are set up with mail-archive.com currently, I'm not sure about other third-party mail archives which may have been following the other mailing lists.

Otherwise we may want to consider changing the host of our mailing lists :cold_face: 

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
https://www.qubes-os.org/support/

**Comment by andrewdavidwong** [comment]
For anyone reading this who isn't already aware, we're about to announce a new Discourse-based forum that will at least somewhat help with this problem.

**Comment by unman** [comment]
I dont want to rehash old arguments, but last time I used discourse, the "mailing list" support wasn't good.
If discourse is to be the primary means for communication, is it workable for those who use mail only?

**Comment by mfc** [comment]
> I dont want to rehash old arguments, but last time I used discourse, the "mailing list" support wasn't good.
> If discourse is to be the primary means for communication, is it workable for those who use mail only?

the current framing is that it won't be primary means for communication but just an additional means, and my understanding is similar that trying to use email *only* with Discourse is not going to be the same level of ease as with a mailing list (for example, it's not clear how to create categorized topics via email).

so it could certainly be the case that we *also* explore moving the mailing lists to a less crappy mailing list provider at some point. also the Discourse forum will be focused only on Qubes users, not `@qubes-devel` etc. so the existence of the Discourse forum doesn't change the crappy situation for the other mailing lists.

**Comment by unman** [comment]
On Thu, Aug 20, 2020 at 07:46:06AM -0700, Michael Carbone wrote:
> > I dont want to rehash old arguments, but last time I used discourse, the "mailing list" support wasn't good.
> > If discourse is to be the primary means for communication, is it workable for those who use mail only?
> 
> the current framing is that it won't be primary means for communication but just an additional means, and my understanding is similar that trying to use email *only* with Discourse is not going to be the same level of ease as with a mailing list (for example, it's not clear how to create categorized topics via email).
> 
> so it could certainly be the case that we *also* explore moving the mailing lists to a less crappy mailing list provider at some point. also the Discourse forum will be focused only on Qubes users, not `@qubes-devel` etc. so the existence of the Discourse forum doesn't change the crappy situation for the other mailing lists.
> 

Thanks Michael

**Comment by DemiMarie** [comment]
Could we have our lists archived somewhere else, such as https://marc.info or self-hosted Mailman?

**Comment by unman** [comment]
On Sat, Sep 12, 2020 at 09:57:19AM -0700, Demi Marie Obenour wrote:
> Could we have our lists archived somewhere else, such as https://marc.info or self-hosted Mailman?
> 

qubes-users and qubes-devel are already archived at mail-archive.com

**Comment by mfc** [comment]
FYI it seems Google has backtracked and you can now (again) access the mailing list archives without signing in. can others confirm?

> qubes-users and qubes-devel are already archived at mail-archive.com

shall we add all other lists to mail-archive.com? and then close this issue?

**Comment by SvenSemmler** [comment]
> access the mailing list archives without signing in. can others 
> confirm?

Yes, although one has to allow JavaScript (has always been the case).

> shall we add all other lists to mail-archive.com?

Yes, please. This option also works without any scripting enabled (much 
preferred).

**Comment by mfc** [comment]
@marmarek @andrewdavidwong according to the [mail-archive.com instructions](https://www.mail-archive.com/faq.html#newlist), we need to subscribe `archive+gg1@mail-archive.com` to the relevant lists. they are:
* https://groups.google.com/g/qubes-translation
* https://groups.google.com/g/qubes-project
* https://groups.google.com/g/qubes-announce (not entirely sure if needed since it is just copies of our news RSS...)

i don't have the necessary access so i leave it to you

**Comment by andrewdavidwong** [comment]
> @marmarek @andrewdavidwong according to the [mail-archive.com instructions](https://www.mail-archive.com/faq.html#newlist), we need to subscribe `archive+gg1@mail-archive.com` to the relevant lists. they are:
> 
> * https://groups.google.com/g/qubes-translation
> * https://groups.google.com/g/qubes-project
> * https://groups.google.com/g/qubes-announce (not entirely sure if needed since it is just copies of our news RSS...)
> 
> i don't have the necessary access so i leave it to you

Done. Thanks, Michael.

I think adding qubes-announce is still a good idea, since the list is not an exact mirror of Qubes News. Although the vast majority of announcements are posted to both, emails to qubes-announce are still manually sent and could, in theory, differ from what appears elsewhere. It's also just nice, in general, to have consistency and redundancy when it comes to archiving. :slightly_smiling_face:
