### ISSUE TITLE
Arch template does not build

### ISSUE THREAD

**Issue by unman** [QubesOS/qubes-issues#6011]
**Qubes OS version**
_R4.0_

**Affected component(s) or functionality**
_Qubes builder_

**Brief summary**
_As title_

**To Reproduce**
_Steps to reproduce the behavior:_
_1. Select arch template in `setup`_
_2. `make qube-vm`_
_3. `make template`_

**Expected behavior**
_Template is built_

**Actual behavior**
_Build fails._

**Additional context**
_font-bitstream-speedo is not available._

**Comment by nosy** [comment]
@unman it fixed

here 
https://github.com/QubesOS/qubes-issues/issues/5961

and

here

```
echo "patch-xen-gcc10-fixes.patch" >> "$directory/qubes-src/vmm-xen/series-vm.conf"
```

**Comment by unman** [comment]
@nosy Well, not yet fixed.
Completely missed #5961 , and that PR (like mine) has failed on verification.
