### ISSUE TITLE
User Typo in Memory Settings can cause Qube to be Unusuable

### ISSUE THREAD

**Issue by zellchristensen** [QubesOS/qubes-issues#6016]
**Qubes OS version**
Qubes R4.0

**Affected component(s) or functionality**
Qube Settings >> Advanced >> Memory section

**Brief summary**
If a user types a very large number in to the Initial memory field or Max memory field it becomes difficult to correct.  This can cause the Qube to fail to start due to lack of memory.

**To Reproduce**
Open Qube Settings for a Qube
Click Advanced tab
Type in the Initial memory field a very large number (ie 746588 MB) and push tab.
Try to quickly go back down to a more reasonable number (ie 2048 MB)

**Expected behavior**
A visual warning or other popup that prevents applying/saving if settings are incorrect but typed values shouldn't be automatically overridden in other fields.

**Actual behavior**
If the typed value in Initial memory is higher, Max memory always becomes equal to it.
If the typed value in Initial memory is lower than 1/10th the value of Max memory, Initial memory becomes set to it.

**Additional context**
If a user is not about to figure out the solution below, and they already saved the settings, they may find their only solution is to delete the Qube and create a new one as the original will not boot due to lack of memory available compared to the settings.

**Solutions you've tried**
The best work around is to hopefully click cancel before the setting is saved and open the settings again, losing any other settings that were set between opening the menu and clicking cancel.

Alternatively the user has to make sure "Include in memory balancing" is checked, then proceed to alternate between fields deleting a single digit (making sure to never have more than a 1/10th difference) in increments until reaching a desired reasonable value which is tedious and unintuitive.

**Comment by marmarta** [comment]
I think this is a good idea. Perhaps we should just move the alert to the apply phase of Settings, with a "do you want to abort and check it again" prompt? @marmarek , is this a bad idea?

**Comment by marmarek** [comment]
Check on apply is fine.
Generally having maxmem > 10*initial mem have rather mild consequences.  The (Linux) qube won't use more than 10*initial mem RAM so you just waste some RAM. But otherwise it will work. There is no reason for forcing it this hard.
