### ISSUE TITLE
R4.1, qubes-dom0-update fails: "garcon-0.6.4-4.fc32.i686 has inferior architecture"

### ISSUE THREAD

**Issue by RaphaelBalthazar** [QubesOS/qubes-issues#6017]
**Qubes OS version**
R4.1
**Affected component(s) or functionality**
qubes-dom0-update 

**Brief summary**
qubes-dom0-update fails with 
```shell_session
Error:
Problem: garcon-0.6.4-4.fc32.i686 has inferior architecture

    package xfce4-settings-qubes-4.0.4-1.fc32.x86_64 requires garcon >= 0.6.2, but none of the providers can be installed
    cannot install the best update candidate for package garcon-1000:0.6.4-4.fc32.x86_64
    package xfce4-settings-qubes-4.0.4-1.fc32.x86_64 conflicts with garcon = 1000:0.6.4 provided by garcon-1000:0.6.4-4.fc32.x86_64
    problem with installed package xfce4-settings-qubes-4.0.3-2.fc32.x86_64
    cannot install the best update candidate for package xfce4-settings-qubes-4.0.3-2.fc32.x86_64
    (try to add ‘skip-broken’ to skip uninstallable packages)
```
**To Reproduce**
1. Go to 'System Tools'
2. Click on 'Qubes Update'
3. Check the box 'dom0'
4. See error like mentioned above

**Expected behavior**
The UpdateVM is downloading and installing updates for dom0

**Actual behavior**
The UpdateVM is downloading but skipping installing because of a file conflict

**Solutions you've tried**
For now I've excluded the following package via terminal in order to be able to finish the updating process
```shell_session
sudo qubes-dom0-update --exclude="xfce4-settings-qubes-4.0.3-2.fc32.x86_64" 
```
I also tried "--enablerepo=dom0-current-testing" which leads to additional errors including 'libgarcon'

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
@GWeck reported problems building R 4.1 with an error involving the package "garcon-0.6.2.tar.bz2"
https://github.com/QubesOS/qubes-issues/issues/5526
I don't know if this is related

**Comment by fepitre** [comment]
Qubes R4.1 is a devel version. Please check Qubes devel list first before posting issue here. The problem has been rised in a summary post here https://groups.google.com/d/msg/qubes-devel/IWESHRQfeko/DN9LJ913BQAJ.
