### ISSUE TITLE
KeePassXC with YubiKey (Challenge-Response) - YubiKey not detected by AppVM

### ISSUE THREAD

**Issue by invalid-error** [QubesOS/qubes-issues#6019]
**Qubes OS version**
Qubes release 4.0 (R4.0)

**Affected component(s) or functionality**
YubiKey is listed in dom0 but cannot be attached to AppVM.

**Brief summary**
When you enter a YubiKey to a USB port dom0 will recognize the Yubikey
`lsusb`
```
...
...Yubico.com Yubikey 4 OTP+U2F+CCID
...
```
but the Device Manager does not list the YubiKey therefore it is not possible to attach the YubiKey to any AppVM. 

**To Reproduce**
KeePassXC use case example: It is not possible to generate or use any database (.kdbx) with YubiKey:
1. Launch KeePassXC
2. Create a new database
3. At ‘Data Master Key’ select ‘Add additional protection’ and click on 'Add YubiKey Challenger-Response > No YubiKey inserted

**Expected behavior**
Pass Yubikey via Qubes Devices Manager to AppVM and use it in KeePassXC application (in AppVM)

**Additional context**
There are some closed issues concerning USB / YubiKey:
https://github.com/QubesOS/qubes-issues/issues/3564
https://github.com/QubesOS/qubes-issues/issues/3612
Some have solved their issue some issues where poping up in newer version (which have been working before updating). I am a bit lost and I do not want to misconfigure my Qubes or lock myself out (since I have a USB keyboard). The Qubes documentation is outstanding but concerning Yubikey I could only find chats and very old solutions which are maybe obsolete. I would appreciate some guidance in setting up everything correctly and in mid-term having it in the documentation as a dedicated chapter.

Thanks a lot for you help.

**Comment by deeplow** [comment]
Hey @invalid-error. So the problem here seems to be that it is listed in dom0 (via `qvm-usb`?) but not showing-up on the devices manager, right?

If so, then the problem doesn't relate to the AppVM in question nor to KeepPassXC. It's before that.

**Comment by invalid-error** [comment]
You are right, Yubikey is listed in dom0 but not in Device Manager therefore not forwardable to AppVM. Sorry, I was setting up this issue from a (KeePassXC) use case point of view not from the root issue.

**Comment by deeplow** [comment]
No worries! Do you think you can edit issue to reflect that @invalid-error ?

**Comment by invalid-error** [comment]
> No worries! Do you think you can edit issue to reflect that @invalid-error ?
> 
> Sometimes you just need a different person to look from another perspective.

I made some modification and kept KeePassXC use case as an example.

**Comment by invalid-error** [comment]
https://qubes-os.discourse.group/t/yubikey-not-detected-in-device-manager-usb-keyboard-enabled/204

**Comment by invalid-error** [comment]
Issue has been solved:
When you have a Qubes OS with a USB keyboard / mouse setup and you want to use a Yubikey you simply have to run:
[https://www.qubes-os.org/doc/usb-qubes/#automatic-setup](https://www.qubes-os.org/doc/usb-qubes/#automatic-setup)
`sudo qubesctl state.sls qvm.usb-keyboard`
Afterwards launch the `sys-usb` and your are done.

Link to source (chat): [https://qubes-os.discourse.group/t/yubikey-not-detected-in-device-manager-usb-keyboard-enabled/204](https://qubes-os.discourse.group/t/yubikey-not-detected-in-device-manager-usb-keyboard-enabled/204)
