### ISSUE TITLE
manager icon is cropped on 4.1

### ISSUE THREAD

**Issue by fepitre** [QubesOS/qubes-issues#6021]
On default XFCE in R4.1, the new manager seems cropped a little bit on top and bottom. Maybe we can change default icon size or it's an issue from my side? @marmarta do you mind to confirm/unconfirm please? I've attached a pic of that bug I have on a testing laptop. Sorry for the bad quality. ![Wire 2020-08-25 at 16 11 10](https://user-images.githubusercontent.com/26125607/91233055-b20f1200-e730-11ea-9ba3-7a3b91d9014c.jpg)

**Comment by marmarta** [comment]
I see the same problem - I think I know where the problem is :)

**Comment by ninavizz** [comment]
Actually... so, yes @fepitre I am getting you and @marmarta  new icons that have empty-space in the PNGs all around the artwork. Something I just realized, though. Whonix recently shipped an update, with the icons I'd created for the `sdw-date` widget, included in the update. Those icons show perfectly and un-cropped in my Tray. I am curious if something was done differently in how @adrelanos implemented those, that could help us identify what's going on—either just with the tray icons, or with the tray and the App Menu icons?

This is what the Whonix icons look like in my Sketch app; they go to the edges of each canvas, just like the Qute Qubes do (ignore the names of the canvasses).

<img width="559" alt="Screen Shot 2020-10-15 at 12 54 24 PM" src="https://user-images.githubusercontent.com/8262612/96179619-fffcf680-0ee5-11eb-9cee-0dd1eb51cb2c.png">

**Comment by ninavizz** [comment]
@fepitre These are some updated Domains Widget icons, with more empty space around the edges of the artwork. Try these out—on an aside from my curiosity with why the `sdw-date` widget isn't cropping like the Domains and App Menu QuteQubes are.  
[QuteDomains2.zip](https://github.com/QubesOS/qubes-issues/files/5389330/QuteDomains2.zip)

**Comment by fepitre** [comment]
Sorry I've not seen your message. I'll try those icons soon. Thank you.

**Comment by fepitre** [comment]
@marmarta can you confirm me where exactly to put the new set please?

**Comment by unman** [comment]
@ninavizz
Nothing seems to have happened here for 10 months.
Are there newer icon sets that fix this or is the one linked the one
to test?

**Comment by ninavizz** [comment]
Urk, @unman thx for sharing!
@marmarta said she'd found something in the code that fixed it on her end. So, it wasn't the artwork, I don't think, but something else?

Not sure if either she or @fepitre pushed that fix... or if it just looks nice on someone's local build? Or if I still need to submit new artwork?

**Comment by unman** [comment]
On Mon, Aug 09, 2021 at 09:01:53AM -0700, Nina Eleanor Alter wrote:
> Urk, @unman thx for sharing!
> @marmarta said she'd found something in the code that fixed it on her end. So, it wasn't the artwork, I don't think, but something else?
> 
> Not sure if either she or @fepitre pushed that fix... or if it just looks nice on someone's local build? Or if I still need to submit new artwork?
> 

If it is fixed, it hasnt fed through to testing repos.
I have qubes-artwork 4.11: there's nothing later in current-testing.

**Comment by marmarta** [comment]
Rediagnosed: this is an interaction of XFCE4 panel's settings, size of icon and not-so-smartness of Gtk.StatusIcon widget. As the latter is deprecated (no, there is no replacement), the easiest fix (that by the way fixes also-cutoff device widget icon ) is changing settings of the notification area to disable showing frame.

**Comment by marmarta** [comment]
It only appears with some sizes of the panel (e.g. when I have my preferred 49px one it works fine, with 48px it doesn't), that's why it sometimes was solved for me and not for other people. Otherwise we could make special icons that have blank space on the sides, but not sure if this is a good idea.

**Comment by DemiMarie** [comment]
> Rediagnosed: this is an interaction of XFCE4 panel's settings, size of icon and not-so-smartness of Gtk.StatusIcon widget. As the latter is deprecated (no, there is no replacement), the easiest fix (that by the way fixes also-cutoff device widget icon ) is changing settings of the notification area to disable showing frame.

That does not solve the problem for me; my “maximum icon size” is 22.  It does help, though.

The future is AyatanaAppIndicator but I am not sure if we can rely on that in dom0.  Can we instead patch Gtk.StatusIcon?

**Comment by andrewdavidwong** [comment]
This seems like a minor issue that shouldn't block 4.1. If I'm wrong, please let me know.

**Comment by ninavizz** [comment]
@marmarta That is a very helpful thing to learn about XFCE needs w/ tray icons, in general—TY! Will deliver new one, accordingly. Linux norms with their "customize everything, always, even when 99% of the customizations are actually quite horrid!" kicking us in the tush, yet again. :P
