### ISSUE TITLE
Templates: Add Ubuntu 20.04 LTS ("Focal") template to the "setup" script

### ISSUE THREAD

**Issue by john-999** [QubesOS/qubes-issues#6022]
**The problem you're addressing (if any)**
Ubuntu 20.04 LTS is currently not supported in the templates' ```setup``` script. (https://www.qubes-os.org/doc/templates/ubuntu/)

**Describe the solution you'd like**
Could you please include Ubuntu 20.04 LTS ("Focal") so that it can be selected from the list of templates presented when running the templates' ```setup``` script?

**Where is the value to a user, and who might that user be?**
Ubuntu is the most popular Linux distro. 20.04 ("Focal") is even more important as it is an LTS version.

**Describe alternatives you've considered**
I have created a working 18.04 LTS ("Bionic") template using the ```setup``` script and then tried upgrading it to 20.04. The result is that the upgraded template won't boot. So that does not seem to be an option.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
https://www.qubes-os.org/doc/templates/ubuntu/

**Comment by andrewdavidwong** [comment]
My understanding is that the Ubuntu license legally prohibits us from doing this. @unman, is that correct?

**Comment by unman** [comment]
On Wed, Aug 26, 2020 at 04:40:06PM -0700, Andrew David Wong wrote:
> My understanding is that the Ubuntu license legally prohibits us from doing this. @unman, is that correct?
> 
No, there's no problem in building the templates.
The issue is that debootstrap in 32 supports focal, but I'm still
building on 31, which doesn't.

**Comment by andrewdavidwong** [comment]
> No, there's no problem in building the templates.
> The issue is that debootstrap in 32 supports focal, but I'm still
> building on 31, which doesn't.

Ok, thanks for the clarification!

**Comment by icequbes1** [comment]
A temporary(?) hack for a fedora 31 build VM is to manually add a symlink for focal to debootstrap.

```
sudo ln -s gutsy /usr/share/debootstrap/scripts/focal
```

Most targets in /scripts are just symlinks to a common `gutsy` script; a quick focal build worked on a Fedora 31 build VM (without any testing afterwards).

**Comment by unman** [comment]
After merge, this can be closed. Focal is available in setup script and builds correctly.
