### ISSUE TITLE
Root terminal button in Qube Manager

### ISSUE THREAD

**Issue by herypt** [QubesOS/qubes-issues#6026]
**The problem you're addressing (if any)**
Users that have a minimal template installed or removed passwordless root access need to run `qvm-run -u root X-minimal xterm` every time they want to install a package or otherwise open a root terminal in the qube.

**Describe the solution you'd like**
A button either in the Qube Manager or the qube widget to open a root terminal.

**Where is the value to a user, and who might that user be?**
Users wouldn't need to remember and type that command every time they want to start a root terminal.

**Describe alternatives you've considered**
Typing it manually every time.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
https://www.qubes-os.org/doc/templates/minimal/#passwordless-root

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
_A list of links to other bug reports, feature requests, or tasks in the qubes-issues tracker. Do not describe any other unreported bugs, features, or tasks here._

**Comment by unman** [comment]
On Mon, Aug 31, 2020 at 02:56:13AM -0700, herypt wrote:
> **The problem you're addressing (if any)**
> Users that have a minimal template installed or removed passwordless root access need to run `qvm-run -u root X-minimal xterm` every time they want to install a package or otherwise open a root terminal in the qube.
> 
> **Describe the solution you'd like**
> A button either in the Qube Manager or the qube widget to open a root terminal.
> 
> **Where is the value to a user, and who might that user be?**
> Users wouldn't need to remember and type that command every time they want to start a root terminal.
> 
> **Describe alternatives you've considered**
> Typing it manually every time.
> 
> **Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
> https://www.qubes-os.org/doc/templates/minimal/#passwordless-root
> 
> **Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
> _A list of links to other bug reports, feature requests, or tasks in the qubes-issues tracker. Do not describe any other unreported bugs, features, or tasks here._
> 
> 

I'd be against this since we probably *don't* want to make it easy for
users to (ab)use root access. My opinion.
In the two cases mentioned, minimal templates are intended only for
experienced users, and if you remove passwordless root, then you
should have the ability to work around this.
It would take a few minutes to knock up a script that provides the
functionality you want, and you could link to key or (?) desktop icon.

**Comment by icequbes1** [comment]
I'd agree with unman; is this something that's truly needed?

I'd be interested to hear why the user wouldn't just install `qubes-core-agent-passwordless-root` if a root shell was needed so often as to now seek a one-click solution. The Qubes team makes clear their take regarding [passwordless sudo access](https://www.qubes-os.org/doc/vm-sudo/).

Using minimal templates is not the default use case. If the user purposely wants to avoid passwordless root in the VM, I believe they should accept the consequences of that, which means having to use `-u root` in a `qvm-run` invocation.

There are many alternatives to 'typing it very time' such as a simple shell script, or even simpler - a launcher that can be added to the menu of the qube:

(assume "myqube" is the name of a qube a root shell is needed)

1. Right-click on the desktop
2. Create Launcher
3. Enter "myqube-root" for Name
4. Enter `qvm-run -u root myqube xterm` for Command
5. Click Create
6. Open a dom0 terminal, and:

   ```
   xdg-desktop-menu install ~/.local/share/desktop-directories/myqube-vm.directory ~/Desktop/myqube-root.desktop
   ```
This adds a menu entry for that qube to open a root shell in one click.

**Comment by andrewdavidwong** [comment]
I'm inclined to agree with the considerations presented above, so I'm closing this as "won't do." If anyone has a new reason for why this should be done, please leave a comment, and we'll be happy to take another look. Thank you.
