### ISSUE TITLE
Qubes tool shortcuts are duplicated in Applications Menu

### ISSUE THREAD

**Issue by herypt** [QubesOS/qubes-issues#6027]
**The problem you're addressing (if any)**
Qubes tools are listed in both the "Qubes tools" submenu as "System tools"

**Describe the solution you'd like**
Remove them from "System tools"

**Where is the value to a user, and who might that user be?**
It's easier to find things in system tools as those applications aren't duplicated across both menus.

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
#5831

**Comment by andrewdavidwong** [comment]
Duplication sounds like a bug, but I don't understand what you mean.

> Qubes tools are listed in both the "Qubes tools" submenu as "System tools"

I think there's a typo in this sentence. Both where? What is the other place besides "System Tools" where the Qubes tools appear? I can't find them anywhere else.

**Comment by herypt** [comment]
Sorry, should've specified that the Qubes tools submenu only exists in Qubes 4.1
![System_tools](https://user-images.githubusercontent.com/70331266/91895821-62c46680-ec87-11ea-8cdd-2fd8de5b22ce.png)
![Qubes_tools](https://user-images.githubusercontent.com/70331266/91895827-648e2a00-ec87-11ea-91de-b71646ad79c7.png)

**Comment by 92VV3M42d3v8** [comment]
"Qubes Update" only appears in System tools, It also need migration to Qubes Tools entry.
