### ISSUE TITLE
Arch Linux build failure on 4.1

### ISSUE THREAD

**Issue by jon-bit** [QubesOS/qubes-issues#6028]
**Qubes OS version**
R4.1

**Affected component(s) or functionality**
Archlinux template

**Brief summary**
I'm trying to make a arch linux template

**To Reproduce**
1. follow all of the steps in archlinux guide in the qubes website until you reach "make all the required qubes components"

**Expected behavior**
It is should make a work for a few hours and make the template

**Actual behavior**
I get 

```
*******************************************************************************
***                               ERROR                                      ***
*** Cannot create chroot because the current filesystem is mounted as nodev. ***
*** Build Qubes on a different filesystem, or run 'make remount' to remount  ***
*** /home with dev option.
***                                                                          ***
*******************************************************************************
```

and if I do make remount it goes for a while and then I get

```
==> Installing missing dependencies...
sudo: effective uid is not 0, is /usr/sbin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?
==> ERROR: 'pacman' failed to install missing dependencies.
==> Missing dependencies:
  -> python2
  -> bridge-utils
  -> python2-lxml
  -> lzo
  -> yajl
==> Checking buildtime dependencies...
==> Installing missing dependencies...
sudo: effective uid is not 0, is /usr/sbin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?
==> ERROR: 'pacman' failed to install missing dependencies.
==> Missing dependencies:
  -> wget
  -> git
  -> bin86
  -> dev86
  -> iasl
  -> yajl
  -> pixman
==> ERROR: Could not resolve all dependencies.
make[2]: *** [/home/user/qubes-builder/qubes-src/builder-archlinux/Makefile.archlinux:121: dist-package] Error 8
make[1]: *** [Makefile.generic:191: packages] Error 1
make: *** [Makefile:227: vmm-xen-vm] Error 1
```

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
https://www.qubes-os.org/doc/building-archlinux-template/

I have no clue why this is happening. Help is appreciated and thanks in advance.

**Comment by andrewdavidwong** [comment]
Duplicate of #4436

**Comment by andrewdavidwong** [comment]
This appears to be a [duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Comment by 0rb677** [comment]
@jon-bit quick and dirty fix

[user@builder-archlinux ~]$ vim /home/user/qubes-builder/qubes-src/builder-archlinux/update-local-repo.sh

```
# Now install deps
env $CHROOT_ENV chroot "$CHROOT_DIR" /bin/sh -c \
    "http_proxy='${REPO_PROXY}' pacman -S --noconfirm python2 bridge-utils python2-lxml lzo yajl wget git bin86 dev86 iasl yajl pixman qubes-vm-xen qubes-libvchan-xen"

```

**Comment by icequbes1** [comment]
After fixing `make remount` to allow `dev` and `suid`, the first error with qrexec is due to #4955 - qrexec was moved to a different repo in 4.1.

**Comment by fepitre** [comment]
FYI, I'm currently finishing the whole Archlinux integration in Qubes.

**Comment by fepitre** [comment]
With the four PR referenced above the template is working out of the box.

**Comment by jon-bit** [comment]
@fepitre I'm having a hard time understanding what it is I have to do. can you lay out a step by step instructions? I hate to ask but I really don't know what I'm doing.

**Comment by icequbes1** [comment]
@jon-bit the build instructions are the same. Ensure you have performed a `make get-sources`.

@fepitre I can confirm this builds on R4.1 with a Fedora 31 build host. Small issue was introduced elsewhere that causes network issues - #6145.

Small note, not sure if it matters - on a Fedora 32 build host, I still had to add `suid` to `scripts/remount`, as it appears `/home` is mounted `nosuid` by default. Otherwise, pacman/sudo complains:

```
==> Installing missing dependencies...
sudo: effective uid is not 0, is /usr/sbin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?
==> ERROR: 'pacman' failed to install missing dependencies.
```

It's a quick hack and I'm building in a dedicated VM, so it doesn't matter too much to me, but perhaps it might if people aren't using dedicated/disposable VMs/machines.

**Comment by RaphaelBalthazar** [comment]
@jon-bit 
Go to `/home/user/qubes-builder/`and open the remount script via nano (or vim) `sudo nano remount`
The last line is 
`sudo mount "$mountpoint" -o dev,remount`
add `suid` after `dev` 
`sudo mount "$mountpoint" -o dev,suid,remount`
write the changes (by pressing CTRL +O) 
Go to `/home/user/qubes-builder/` where you did everything along the lines of this guide:
https://www.qubes-os.org/doc/building-archlinux-template/
Before you run `make qubes-vm` (7.) you run `make remount`.
After that finish as explained in the guide above and building the template should be successful.

**Comment by RaphaelBalthazar** [comment]
After installing the template there is the following message:
```
Running scriptlet: qubes-template-archlinux-4.0.6-202010251327.noarch     1/1 
  Installing       : qubes-template-archlinux-4.0.6-202010251327.noarch     1/1 
  Running scriptlet: qubes-template-archlinux-4.0.6-202010251327.noarch     1/1 
archlinux: Importing data
archlinux: qubes.PostInstall service failed
Verifying        : qubes-template-archlinux-4.0.6-202010251327.noarch     1/1 

Installed:
  qubes-template-archlinux-4.0.6-202010251327.noarch                            

Complete!
```
Is this `qubes.PostInstall service failed` anything to worry about?

**Comment by icequbes1** [comment]
@RaphaelBalthazar Same error here. I noticed the same error when performing other dom0-initiated actions such as booting another Qube from an ISO stored on an Arch-based AppVM...there's some qrexec issues.

Debugging in the journal of the template shows a PAM error complaining about `postlogin` not found upon the qrexec call.

`/etc/pam.d/postlogin` indeed does not exist in the Arch template, and is being referenced by `/etc/pam.d/qrexec`.

This error appears to spawn from core-qrexec/agent using the wrong qrexec.pam file during build. There exists three versions: qrexec.pam[.archlinux|.debian]. The Makefile builder is using qrexec.pam, the RPM version, when building the Arch template:

```
ifeq ($(os), Debian)
        install -D -m 0644 qrexec.pam.debian $(DESTDIR)/etc/pam.d/qrexec
else ifeq ($(os), Ubuntu)
        install -D -m 0644 qrexec.pam.debian $(DESTDIR)/etc/pam.d/qrexec
else ifeq ($(os), Arch)
        install -D -m 0644 qrexec.pam.archlinux $(DESTDIR)/etc/pam.d/qrexec
else
        install -D -m 0644 qrexec.pam $(DESTDIR)/etc/pam.d/qrexec
```

This is because `$(os)` is empty for the Arch build. `os` definition relies on `lsb-release`:

```
override os := $(shell lsb_release -is)
```

And `lsb-release` is not part of the Arch chroot. Updating `core-qrexec/archlinux/PKGBUILD` to add `lsb-release` to the `makedepends` fixes the issue.

After that, appears there is complaints with `/usr/lib/qubes/upgrades-status-notify` not existing. It seems this file isn't installed in the Arch template, it is from core-agent.

Issues:

1. Add `lsb-release` as a `makedepends` in `core-qrexec/archlinux/PKGBUILD`
2. Install `usr/lib/qubes/upgrades-status-notify` during packaging

**Comment by jon-bit** [comment]
Sorry for the Late response but I got a little confused.
1. @RaphaelBalthazar That did work. I just didn't know I had to look in the script directory (and just for the record that is not me blaming you).  2. it took a few tries but yes IT WORKED! However... 3. Now I can't get networking good to go. Every time I run A script I get 

`ERROR: You dont have have an Internet connection`

However I can ping and install packages just fine, But I can web brows or use this script. Any suggestions?

**Comment by icequbes1** [comment]
It's a known issue, see #6145. For a workaround, run the template and just do `sudo touch /etc/resolv.conf`, shutdown the template, relaunch AppVM.

**Comment by jon-bit** [comment]
It did that and now I no apps are starting.

**Comment by jon-bit** [comment]
@icequbes1 Sorry it just took long to start the apps, However it's still saying the same thing.

**Comment by icequbes1** [comment]
@jon-bit Comment the last line in builder-archlinux/scripts/09_cleanup.sh (the one that `rm ... resolv.conf`, then run `make template` to get a new template.

Alternatively, modify the archlinux template rootfs while it isn't running to `touch /etc/resolv.conf`.

**Comment by jon-bit** [comment]
OK got it working. Thanks! However There is another problem and that is that I cant build Ubuntu. Would that be a new issue or should I post it here?

**Comment by andrewdavidwong** [comment]
> OK got it working. Thanks! However There is another problem and that is that I cant build Ubuntu. Would that be a new issue or should I post it here?

Sounds like that should be a separate issue, since this one is about Arch Linux (unless it's somehow the same bug, in which case this issue should be updated).

**Comment by jon-bit** [comment]
OK closing. Thanks everyone for the help!
