### ISSUE TITLE
HVM fails to start after update to Xen 4.14

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#6029]
Qubes 4.1:

hvm virtualization doesn't seem to be working for sys-net/sys-usb

The error in xl dmesg:
```
(d29) Invoking SeaBIOS ...
(XEN) MMIO emulation failed (1): d29v0 32bit @ 0008:fffeedfd -> 
(XEN) d29v0 Triple fault - invoking HVM shutdown action 1
```

This is reproducible in openQA too: https://openqa.qubes-os.org/tests/11619/file/serial0.txt

_Originally reported by @0spinboson in https://github.com/QubesOS/updates-status/issues/2008#issuecomment-684466376_

**Comment by 0spinboson** [comment]
[dmesg.txt](https://github.com/QubesOS/qubes-issues/files/5167509/dmesg.txt)
Here's one of my dmesg logs

**Comment by marmarek** [comment]
Sadly not fixed yet.

**Comment by jevank** [comment]
Just finished upgrading on test  laptop and yes, still same issue. If you need more details let me know. I see errors in xl dmesg like this
```
MMIO emulation failed (1): d1v0 32bit @ 0008:fffeedfd ->
d1v0 Triple fault - invoking HVM shutdown action 1
```
with vcpu state dump.

**Comment by marmarek** [comment]
Workaround:
```
cd /usr/share/seabios
mv bios.bin bios-128k.bin
ln -s bios-256k.bin bios.bin
```
