### ISSUE TITLE
Q4.1 keyboard layout setting propagation / layout loading issue

### ISSUE THREAD

**Issue by 0spinboson** [QubesOS/qubes-issues#6030]
Affects Qubes 4.1, Fedora & debian-based (fc32, debian 10 & 11) VMs and templates.

Actual behavior:
I've installed the same custom keyboard layout (with same name) in dom0 & every VM + template. Nevertheless, at least 50% of the time, after a VM reboot, the keyboard layout doesn't load properly, and I have to either reinstall or unselect & reselect the desired layout to get it to work.

Expected behavior:
In Qubes 3.2, it used to be the case that so long as the dom0 layout also existed in the VM, it would use the same one in the VM. This behavior seems to me correct.

related smaller bug: Qube Manager crashes when I try to use 'set keyboard layout', presumably because that option was removed recently.

**Comment by 0spinboson** [comment]
Additionally, debian-11-based VMs appear to be resetting the keyboard layout to qwerty after unlocking the screen. Fedora-based ones do not.

**Comment by marmarta** [comment]
a couple quick questions:
1. are your debian templates fully updated?

2. is the layout  name unlike other layout names? mostly, does it use any pluses or other special characters in the name?

**Comment by 0spinboson** [comment]
1. yes
2. it has a [ and , in the name

btw, when I add multiple keyboard layouts to dom0, the one set first in that list is propagated to VM. If I switch the active layout in dom0, this change isn't pushed to the VMs (not sure if this is doable, just saying).
perhaps relevant: the keyboard layout I set during installation is qwerty.

**Comment by marmarta** [comment]
@0spinboson well it most definitely should be propagated, I'll look for bugs in the propagation some more...

**Comment by tasket** [comment]
I suffer from this issue as well, but I did not "install" a custom layout in the system. I'm using a non-qwerty layout that has long been supplied by all Linux distros and worked without issue in Qubes 3.x and 4.0.

**Comment by fepitre** [comment]
On XFCE, it's needed to deselect "Use system defaults". There is something that override the interpreted layout from our last implementation.

**Comment by tasket** [comment]
@fepitre I'm using KDE and see no such setting for the keyboard.

**Comment by tasket** [comment]
@fepitre OK, the equivalent KDE setting to turn off appears to be "Configure Layouts"...?

Right now its working correctly.

**Comment by fepitre** [comment]
> @fepitre OK, the equivalent KDE setting to turn off appears to be "Configure Layouts"...?
> 
> Right now its working correctly.

Honestly I don't use KDE at all so I don't know. So if it works directly by turning off this option into VM without the need to restart anything, so yes certainly.
