### ISSUE TITLE
[Contribution] qubes-app-split-git

### ISSUE THREAD

**Issue by woju** [QubesOS/qubes-issues#6031]
A while ago I made split-git, which makes it possible to fetch signed commits from other VM using qrexec. It would be nice if it was packaged for everyone to use.

https://github.com/woju/qubes-app-split-git

**Comment by woju** [comment]
Cc @marmarek

**Comment by andrewdavidwong** [comment]
@woju, you added the `community-dev` label. Does that mean you intend for this to follow our [Package Contribution](https://www.qubes-os.org/doc/package-contributions/) procedure, even though you're a member of the core Qubes team?

**Comment by andrewdavidwong** [comment]
Assigning to @marmarek for initial review.

**Comment by woju** [comment]
@andrewdavidwong:

On Thu, Sep 03, 2020 at 04:58:45PM -0700, Andrew David Wong wrote:
> @woju, you added the `community-dev` label. Does that mean you intend for
> this to follow our Package Contribution procedure, even though you're
> a member of the core Qubes team?

@marmarek in private converation told me to add this label, probably so that
he'll have it on the same list as other "new" packages.

I've no strong opinion either way. I can undergo the procedure, especially if
that'd make things easier or more transparent.

**Comment by fepitre** [comment]
I've integrated it into `QubesOS-contrib`. Some packages are built and some are currently building.

**Comment by andrewdavidwong** [comment]
> I've integrated it into `QubesOS-contrib`. Some packages are built and some are currently building.

Does that mean this will be available for 4.0 or 4.1 (or both)?

**Comment by fepitre** [comment]
@andrewdavidwong Yes it's already available for both.

**Comment by iamahuman** [comment]
https://github.com/QubesOS-contrib/qubes-app-split-git/blob/6715422d94f92fd67a798bb159fdb08ae23dd124/qubes-rpc/git.Fetch#L24-L28

Are there any security implications for using `git cat-file --batch[=<format>]` in `git.Fetch`?

**Comment by andrewdavidwong** [comment]
> @andrewdavidwong Yes it's already available for both.

It sounds like this issue was already completed a long time ago. I guess we just forgot to close it.
