### ISSUE TITLE
documentation: some issues with intro diagram 

### ISSUE THREAD

**Issue by deeplow** [QubesOS/qubes-issues#6034]
**Qubes OS version**
Related to  `R4.0`

**Affected component(s) or functionality**
Documentation: first diagram on the intro page

**Brief summary**
The "intro" diagram (available at https://www.qubes-os.org/intro/) has some issues that need fixing (see "Expected Behavior" section)

**To Reproduce**
View the first diagram at https://www.qubes-os.org/intro/

**Expected behavior**
* `sys-whonix` connected to `sys-firewall`
* naming: AppVM1, AppVM2, AppVM3
* **edited later**: sys-net color should be red (untrusted)
* **edited later**: Whonix DispVM (AppVM3) has Tor Browser

**Actual behavior**
* `sys-whonix` connected to `networking hardware`
* naming: AppVM1, AppVM2, AppVM2
* **edited later**: sys-net color is gree (trusted)
* **edited later**: Whonix DispVM (AppVM3) has Firefox

**Screenshots**

> **Note:** This diagram is outdated. See latest comments for a more recent version

| Current | Proposal |
|----|----|
|![qubesosdiagram](https://user-images.githubusercontent.com/47065258/92313084-d54e8280-efb6-11ea-9185-ea61d817a95e.png) | ![qubes-trust-level-architecture](https://user-images.githubusercontent.com/47065258/92313086-da133680-efb6-11ea-8bd5-7c50adf57ad8.png)|

**Additional context**
* Issue originally brought up by GWeck on [this forum thread](https://qubes-os.discourse.group/t/suggestions-for-qubes-architecture-diagram/377/1)
* Related pull request for changing the diagrams: https://github.com/fepitre/qubes-diagrams/pull/1

**Solutions you've tried**
* see related pull request: https://github.com/fepitre/qubes-diagrams/pull/1

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
* https://www.qubes-os.org/intro/
* https://github.com/fepitre/qubes-diagrams/

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
none

**Comment by fepitre** [comment]
@andrewdavidwong @marmarek currently the most updated fork is mine and QubesOS does not have one. Maybe it's time to?

**Comment by andrewdavidwong** [comment]
Minor thing: Could you drop the solid black border that goes around the entire diagram? IMHO, it would be better to handle the border in CSS around the embedded image, _if_ a border is even needed.

**Comment by andrewdavidwong** [comment]
> currently the most updated fork it's mine and QubesOS does not have one. Maybe it's time to?

I agree that it makes sense to keep the canonical source files in a @QubesOS repo. We have [qubes-artwork](https://github.com/QubesOS/qubes-artwork), but I'm not sure whether it's intended for these sorts of diagrams.

What do you think, @marmarek?

**Comment by deeplow** [comment]
> Minor thing: Could you drop the solid black border that goes around the entire diagram?

Yes! I was thinking I was the only one who disliked that border (so I tried to keep it as close to the original as possible). Then I'll make that change.

Also, can I overload this thread to (attempt to) make some additional styling contributions? @andrewdavidwong

**Comment by deeplow** [comment]
Black border removed waiting for merging: https://github.com/fepitre/qubes-diagrams/pull/2

I made it so it has a transparent background but all elements are filled with white background (hardware boxes, and the disk). So in case someone wants to share this on their blog or something, where they have a non-white background, it should look decent-enough.

![qubes-trust-level-architecture](https://user-images.githubusercontent.com/47065258/92323092-6d835080-f025-11ea-9cd6-7d3b65c30595.png)

**Comment by deeplow** [comment]
Just noticed another problem. AppVM3 should have TorBrowser there instead of firefox (Firefox over Tor undermines Tor's anonymity advantages).

**Comment by andrewdavidwong** [comment]
> Also, can I overload this thread to (attempt to) make some additional contributions on the diagram? @andrewdavidwong

That seems appropriately in-scope for this issue.

**Comment by deeplow** [comment]
Quoting @andrewdavidwong [from the forum](https://qubes-os.discourse.group/t/suggestions-for-qubes-architecture-diagram/377/16) to keep everything related here: 
> Yes, sys-net should also be red.

Ok. Then I make that red, but then I also make the networking hardware red as well?

![usb_hw](https://user-images.githubusercontent.com/47065258/92359114-3cb12300-f0da-11ea-934d-25db7ddb995a.png)  >>>> ![net_hw](https://user-images.githubusercontent.com/47065258/92359243-77b35680-f0da-11ea-8f2d-48d07a975ffa.png)

Also @andrewdavidwong could you also check my above comment? Thanks

**Comment by deeplow** [comment]
Some more questions regarding how this new `sys-net` untrustedness propagates. Should the connection between sys-net and sys-firewall also be red? (or leave it as green?)

Here's an example:

![untrustedness](https://user-images.githubusercontent.com/47065258/92360967-32dcef00-f0dd-11ea-8d7b-d9f193b08b22.png)

**Comment by fepitre** [comment]
> Quoting @andrewdavidwong [from the forum](https://qubes-os.discourse.group/t/suggestions-for-qubes-architecture-diagram/377/16) to keep everything related here:
> 
> > Yes, sys-net should also be red.
> 
> Ok. Then I make that red, but then I also make the networking hardware red as well?

I would say yes because it's the default case in QubesOS. All the network devices go to `sys-net`.

> ![usb_hw](https://user-images.githubusercontent.com/47065258/92359114-3cb12300-f0da-11ea-934d-25db7ddb995a.png) >>>> ![net_hw](https://user-images.githubusercontent.com/47065258/92359243-77b35680-f0da-11ea-8f2d-48d07a975ffa.png)
> 
> Also @andrewdavidwong can I also change the firefox icon to Tor Browser? (as in the [above comment](https://github.com/QubesOS/qubes-issues/issues/6034#issuecomment-687813237))

I think it makes sense.

Also, don't hesitate to force push or to do multiple new things in your current pull request. Just edit the PR description and add prefix of related changed/new thing in your commit description if it helps.

**Comment by fepitre** [comment]
> > currently the most updated fork it's mine and QubesOS does not have one. Maybe it's time to?
> 
> I agree that it makes sense to keep the canonical source files in a @QubesOS repo. We have [qubes-artwork](https://github.com/QubesOS/qubes-artwork), but I'm not sure whether it's intended for these sorts of diagrams.
> 
> What do you think, @marmarek?

@marmarek will decide of it but, from my humble view of `qubes-artwork`, it's mostly for in-Qubes components (icons, wallpapers etc). Another possibility could be the `qubes-doc` repository as a content resource. Maybe not all would be used but it's useful for talks etc.

**Comment by deeplow** [comment]
Currently looking like this:

![qubes-trust-level-architecture](https://user-images.githubusercontent.com/47065258/92376162-b0aaf580-f0f1-11ea-9fb9-24bed860aff8.png)

**Comment by andrewdavidwong** [comment]
> Ok. Then I make that red, but then I also make the networking hardware red as well?

Yes.

> Also @andrewdavidwong can I also change the firefox icon to Tor Browser? (as in the above comment)

Yes.

> Some more questions regarding how this new `sys-net` untrustedness propagates. Should the connection between sys-net and sys-firewall also be red? (or leave it as green?)

Not sure about that. The edges in this graph are a bit under-defined. In this case, I suppose the inter-VM connection itself is trusted, so I'd be inclined to make it green (or perhaps even half green fading into half red).

**Comment by andrewdavidwong** [comment]
Oh, I'd also recommend changing `sys-whonix` to black, since that's the default in Qubes.

**Comment by deeplow** [comment]
> Not sure about that. The edges in this graph are a bit under-defined. In this case, I suppose the inter-VM connection itself is trusted

sys-USB to AppVM 1 is also red, hence my question.

>  I'd be inclined to make it green (or perhaps even half green fading into half red).

Hum. I'm more compelled to make it green. The fading effect might lead the user to think that there is some sort of filtration effect on the inter-VM connection it self -- which there isn't (AFAIK)

> Oh, I'd also recommend changing `sys-whonix` to black, since that's the default in Qubes.

Will do!

**Comment by andrewdavidwong** [comment]
> Hum. I'm more compelled to make it green. The fading effect might lead the user to think that there is some sort of filtration effect on the inter-VM connection it self -- which there isn't (AFAIK)

Ok, sounds good.

**IMHO:** At some point, we need to accept that these kinds of abstract representations can never capture all the details about how things actually work. It's good to strive for accuracy at our chosen level of representation, but we should also control the desire to make sure every last facet of reality is depicted, since this can lead to cryptic symbolism that only we understand.

I greatly appreciate your work and initiative on this, @deeplow. :slightly_smiling_face:

**Comment by deeplow** [comment]
I have implemented the above changes. See https://github.com/fepitre/qubes-diagrams/pull/2#issuecomment-688670041

**Comment by deeplow** [comment]
# Making GUI VM and Template Trusted
Now to keep everything consistent @fepitre @andrewdavidwong I have another proposal

## After
![qubes-trust-level-architecture_proposal](https://user-images.githubusercontent.com/47065258/92445911-90883e80-f1a4-11ea-9794-dcb5cc9b40e1.png)

## Before
![qubes-trust-level-architecture](https://user-images.githubusercontent.com/47065258/92445924-9a11a680-f1a4-11ea-9352-b9951dafa57b.png)

## Logic behind (propposed) change

Regarding that:
  * Now that sys-whonix is grey(-ish / black) it in the diagram is more trusted than the templates and GUI VM
  * In qubes the template VMs are black

I would advocacte for:
  * Making GUI VM and Templates Gray as:
    * **better match the default colors in Qubes** (Grey != black but we need a color to represent even more trusted components - and grey is close enough; plus no default machine is grey so no need for confusion)
    * **be more consistent** - templates are at least as trusted as vault-VMs / sys-whonix 

  * Replacing blue color with gray:
     * with these replacements the color blue in the diagram becomes useless so we replace it with grey

  * Making AdminVM / XEN as pure black since:
    * it **represents the ultimate level of trust**

How does this sound?

**Comment by GWeck** [comment]
This would also make it more consistent with the colours in the architecture diagram in Qubes Architecture Overview.

**Comment by andrewdavidwong** [comment]
> **better match the default colors in Qubes** (Grey != black but we need a color to represent even more trusted components - and grey is close enough; plus no default machine is grey so no need for confusion)

Indeed, this is also a bit of a problem in Qubes OS itself: https://github.com/QubesOS/qubes-issues/issues/3102

> [...] How does this sound?

Good ideas. I agree with your proposed changes.

**Comment by deeplow** [comment]
I've [made said changes](https://github.com/fepitre/qubes-diagrams/pull/2). Just to final things: 

> andrewdavidwong:
> > deeplow:
> > Some more questions regarding how this new `sys-net` untrustedness propagates. Should the connection between sys-net and sys-firewall also be red? (or leave it as green?)
> 
> Not sure about that. The edges in this graph are a bit under-defined. In this case, I suppose the inter-VM connection itself is trusted, so I'd be inclined to make it green (or perhaps even half green fading into half red).

Sorry, for insisting on tiny details, but I just noticed that in the [qubes-components diagram](https://github.com/fepitre/qubes-diagrams/blob/master/qubes-components.png) this `sys-net`-`sys-firewall` edge is red. Even though edges are a bit undefined, I think they should at least be consistent. Then we keep the green here and later changed the other. Or we do it the other way around?

![qubes-consistency](https://user-images.githubusercontent.com/47065258/92584232-e6cbaf00-f282-11ea-9e19-57efb3e3f7c4.png)

---

And the last thing: USB keyboard in the [qubes-components diagram](https://github.com/fepitre/qubes-diagrams/blob/master/qubes-components.png) is represented (left) while here it is not (right). Shall we include it as well?

![keyboard](https://user-images.githubusercontent.com/47065258/92584586-5b9ee900-f283-11ea-9c0c-38b250d8bd7b.png)  ![usb](https://user-images.githubusercontent.com/47065258/92603437-d45f6e80-f29e-11ea-950f-bf6159c8339b.png)

**Comment by fepitre** [comment]
> Sorry, for insisting on tiny details, but I just noticed that in the [qubes-components diagram](https://github.com/fepitre/qubes-diagrams/blob/master/qubes-components.png) this `sys-net`-`sys-firewall` edge is red. Even though edges are a bit undefined, I think they should at least be consistent. Then we keep the green here and later changed the other. Or we do it the other way around?

Don't worry it's great what you are doing. I would go with a green link between `sys-net`-`sys-firewall` because when updating templates we are directly "plugged" to `sys-net` so I would vote for a green connection.

> ![qubes-consistency](https://user-images.githubusercontent.com/47065258/92584232-e6cbaf00-f282-11ea-9e19-57efb3e3f7c4.png)
> 
> And the last thing: USB keyboard in the [qubes-components diagram](https://github.com/fepitre/qubes-diagrams/blob/master/qubes-components.png) is represented (left) while here it is not (right). Shall we include it as well?
> 
> ![keyboard](https://user-images.githubusercontent.com/47065258/92584586-5b9ee900-f283-11ea-9c0c-38b250d8bd7b.png) ![usb](https://user-images.githubusercontent.com/47065258/92603437-d45f6e80-f29e-11ea-950f-bf6159c8339b.png)

You can add keyboard indeed. Better keep the same amount of information.

**Comment by andrewdavidwong** [comment]
> Sorry, for insisting on tiny details

No apology necessary!

> I would go with a green link between `sys-net`-`sys-firewall` because when updating templates we are directly "plugged" to `sys-net` so I would vote for a green connection.

I'm not quite sure I understand the rationale. I could imagine someone arguing the opposite: `sys-net` is untrusted, so plugging directly into it is risky, or something. (Not saying I disagree with you or that this hypothetical argument is any good. Just saying I don't understand.)

> You can add keyboard indeed. Better keep the same amount of information.

Agreed.

**Comment by GWeck** [comment]
Some more thoughts on colours:

The proposed scheme lets some colours (orange, blue, purple) without relation to a trust level. This makes sense, since there are lots of possibilities to create VMs that are somewhat trustworthy (perhaps comparable to the "yellow" level of AppVM1 in the diagram), but without a possibilty of declaring them more or less trusted than other ones, e.g.

- a VM used for browsing only trusted websites, like banking or so, possibly restricted by firewall rules to access only such selected addresses;

- a VM used to process office documents exchanged with selected (business) partners, such that these documents may be regarded as trustworthy (but remember Emotet!);

- a template based Windows AppVM restricted by firewall rules to the local network such that any telemetry data transfer is blocked;

- a VM used only for mail exchange, restricted to access only a dedicated mail server.

These VMs are more trustworthy than a VM used for arbitrary browsing (like the VM "untrusted" in the default configuration), but less trustworthy than an isolated VM like "vault", but it would be difficult to say if any of them was more ore less trustworthy than another of them.

So it is good to have the possibilty of assigning different colours to them without meaning any ordering of their trustworthiness. The yellow level in the diagram thus stands for a multitude of different security models without any ordering, which is much more than most systems used to access classified information are able to support.

**Comment by deeplow** [comment]
> The proposed scheme lets some colours (orange, blue, purple) without relation to a trust level.

> So it is good to have the possibilty of assigning different colours to them without meaning any ordering of their trustworthiness.

I agree with you, but I don't interpret the diagram as telling people explicitly that's how they should do things. The purpose here is to explain to people what are the multiple components and their associated trust level. As andrewdavidwong pointed out earlier, the more complexity we add to the diagram, the more hard to decipher each part become (with other words).

What we seem to be pushing for here, it to have a diagram which is more consistent with the default coloring and icons to the default Qubes configuration.

But I think that strategies to organize the qubes (whether by trust level or something else) could be something addressed in the documentation.

**Comment by andrewdavidwong** [comment]
> But I think that strategies to organize the qubes (whether by trust level or something else) could be something addressed in the documentation.

This may be getting into #2646 territory.

**Comment by GWeck** [comment]
Completely o.k. The diagram should not be overloaded, but it is a good thing that Qubes provides these possibilities of organizing VMs.

**Comment by deeplow** [comment]
The only thing missing was just a (re-clarification) on the `sys-net` `sys-firewall` interconnect but upon re-reading the conversation, it seems both @andrewdavidwong and @fepitre agree it should be green (as it is now). So I think we can move forward and merge this and address fixes in the components diagram later. Sound good?

> > But I think that strategies to organize the qubes (whether by trust level or something else) could be something addressed in the documentation.
> 
> This may be getting into #2646 territory.

Yes, let's keep the conversations separate.

**Comment by fepitre** [comment]
> I'm not quite sure I understand the rationale. I could imagine someone arguing the opposite: `sys-net` is untrusted, so plugging directly into it is risky, or something. (Not saying I disagree with you or that this hypothetical argument is any good. Just saying I don't understand.)

@andrewdavidwong Sorry if I was no clear. I was meaning that the update proxy runs into `sys-net` so when updating template, it uses directly `sys-net` and not `sys-firewall`. So I was seeing this connection as `green`. I don't know the historical choice for using `sys-net` as holding the update proxy and not `sys-firewall`.

> The only thing missing was just a (re-clarification) on the `sys-net` `sys-firewall` interconnect but upon re-reading the conversation, it seems both @andrewdavidwong and @fepitre agree it should be green (as it is now). So I think we can move forward and merge this and address fixes in the components diagram later. Sound good?
 
@deeplow I'm waiting for Andrew's final feedback but it looks good for me.

**Comment by fepitre** [comment]
BTW, once the pending PR is done I've asked to @marmarek and we will fork `qubes-diagrams` into QubesOS. @andrewdavidwong you should then be able to merge this into it too.

**Comment by andrewdavidwong** [comment]
Looks good to me. Thank you!

**Comment by fepitre** [comment]
@andrewdavidwong @deeplow I've forked `qubes-diagrams` into https://github.com/QubesOS/qubes-diagrams with latest PR merged.

**Comment by andrewdavidwong** [comment]
The new version is now live on the website! :tada: 

Thank you @deeplow, @fepitre, and @GWeck!

**Comment by fepitre** [comment]
I really like it!
