### ISSUE TITLE
Qubes backup restoration error reporting does not give any details

### ISSUE THREAD

**Issue by strugee** [QubesOS/qubes-issues#6035]
### Qubes OS version:

R4.0

### Affected component(s) or functionality:

`qubes-backup-restore` GUI

---

### Steps to reproduce the behavior:

1. Open the "Restore Backup" application, or run it from a terminal
2. Select a backup for restore that is triggers some sort of error
3. Check the "Verify backup integrity, do not restore data" box
4. Hit next and select VMs for restore
5. Wait a few seconds

### Expected or desired behavior:

The restore functionality tells me exactly what type of error occurred, at what point in the process.

### Actual behavior:

The application simply shows "Finished, with errors" in red. It doesn't give any details as to what the error might have been, even on stdout.

### General notes:

I'm consistently seeing these errors on a large, freshly-created backup of a single, ~350GB VM. Obviously there is some underlying bug that's causing corrupt backups to be created, which I would like to report, but I have no idea where to even start looking for this bug because the restore functionality doesn't tell me what the error was.

I put a btrfs filesystem on the drive I'm writing to specifically so I could rule out silent corruption due to the drive, and I was indeed able to successfully rule this out with a clean btrfs scrub. So the data that the restore functionality processes is definitely the data that Qubes backup produced.

---

### I have consulted the following relevant [documentation](https://www.qubes-os.org/doc/):

https://www.qubes-os.org/doc/backup-restore/

### I am aware of the following related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues:

#5393
#3498
#3216

**Comment by strugee** [comment]
Just tried to reproduce this with a smaller (<1GB) VM and could not.

**Comment by andrewdavidwong** [comment]
> I'm consistently seeing these errors on a large, freshly-created backup of a single, ~350GB VM.

> Just tried to reproduce this with a smaller (<1GB) VM and could not.

It has been known for a long time that large VMs are problematic for `qvm-backup`, while small ones are not. Possibly related issues: https://github.com/QubesOS/qubes-issues/issues/5478, https://github.com/QubesOS/qubes-issues/issues/5393, https://github.com/QubesOS/qubes-issues/issues/4751

**Comment by marmarta** [comment]
a couple questions:
do you have enough disk space left?
is the backup in a VM or in dom0?
I'm trying to reproduce this to see when feedback gets lost

**Comment by andrewdavidwong** [comment]
In my experience, problems occur when I try to back up a large VM *with compression* when the data is not amenable to compression (e.g., already compressed or encrypted). In such cases, turning off compression (`--no-compress`) often eliminates the problem.

**Comment by strugee** [comment]
@marmarta I definitely had _very_ little disk space left. The backup was of an AppVM, and the destination was set to an external drive attached to sys-usb. I also had compression enabled, and a lot of the VM's data was photos or compressed backups - so not particularly amenable to compression.

**Comment by marmarta** [comment]
ok, so it seems it's a genuine problem of missing disk space (for compression tmp files etc.) - and also a bug in error reporting. Will push a fix in a couple minutes :)
