### ISSUE TITLE
Nirokey fails to mount on Debian AppVMs

### ISSUE THREAD

**Issue by sbstrkt** [QubesOS/qubes-issues#6038]
Hallo,

I am facing some issues in mounting Nitrokey(s) on the Debian AppVMs (sepcifically). It works fine with fedora VMs either standalone and AppVM. 

I tried the Nitrokey Pro 2, the Nitrokey fido 2, and the Nitrokey HSM 2. All resulted in the same:

`"Error: QubesException - Device attach failed"`

I am using Qubes 4, Fedora 30 and Debian 10 templates. No `sys-usb` so it directly mounts via `sys-net`.

Thanks.

**Comment by andrewdavidwong** [comment]
Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this does not appear to be suitable for `qubes-issues`. We ask that you please post this on the [`qubes-users` mailing list or forum](https://www.qubes-os.org/support/) instead. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a brief comment explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.
