### ISSUE TITLE
Installer help text inaccurate: claims user account is optional

### ISSUE THREAD

**Issue by zellchristensen** [QubesOS/qubes-issues#6043]
**Qubes OS version**
R4.0.3

**Affected component(s) or functionality**
Installer Configuration

**Brief summary**
After going through the install settings, the user is unable to finish without creating a user account.

**To Reproduce**
Install Qubes on a new machine as normal.
Don't add a user at the user creation selection

**Expected behavior**
User can continue the installation process, perhaps with a warning about a user not being set.

**Actual behavior**
The button to continue is always inaccessible and the user is unable to continue through the prompts without creating a user account.

**Additional context**
The HELP documentation on the User Creation page explicitly states that creating a user account is OPTIONAL and not required with a description of why you should create one anyway.
Disk encryption was not selected if that has any relevance.
The configuration page always says "Root account is disabled" under ROOT PASSWORD whether the root account is locked or unlocked or password added or not.
After a force restart, the Qubes logo shows up as if booting normally with the loading bar at the bottom, but appears to hang when the bar reaches 100%. 

**Solutions you've tried**
Locking/unlocking the ROOT account.
Adding a password for the ROOT account.
Force restarting the machine anyway.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
The HELP documentation from the installation media when clicking on HELP on the User Creation page.

**Comment by marmarek** [comment]
This is expected behavior. Installation without creating user account is not supported. That help text needs an update.

**Comment by andrewdavidwong** [comment]
Yes, as Marek said, there is no way to use Qubes without a user account. Is there some concern you have about the user account or some reason you do not wish to create one? Perhaps we can address that concern directly.

**Comment by zellchristensen** [comment]
> Is there some concern you have about the user account or some reason you do not wish to create one? Perhaps we can address that concern directly.

Just reinstalled and wanted to do so without any encryption/passwords as the screensaver lockout/screen lid lockout slow me down and I didn't have anything that needed to be secured while testing.  I figured there was a bug since reading the help it said it was optional.

**Comment by andrewdavidwong** [comment]
> Just reinstalled and wanted to do so without any encryption/passwords as the screensaver lockout/screen lid lockout slow me down and I didn't have anything that needed to be secured while testing. I figured there was a bug since reading the help it said it was optional.

Ah, I see. In that case, we'll use this bug to update the inaccurate help text, as Marek said.

> I suppose a solution would be to just disable the lock out screen entirely, but even with all the options i could find disabled, it still locks out when the screen is closed.

Perhaps try this:

System Tools -> Screensaver -> [ ] Lock screen after (uncheck this)

But maybe that won't affect closing the laptop lid. I don't see any option for that.

> That and some other screensaver/power management options, but I don't think any of those are qubes specific.

Indeed, they should not be Qubes-specific.
