### ISSUE TITLE
Qubes-builder on Fedora-32 has PyYAML as requirement but package not available.

### ISSUE THREAD

**Issue by unman** [QubesOS/qubes-issues#6045]
**Qubes OS version**
_4.0.3_

**Affected component(s) or functionality**
_Qubes builder_

**Brief summary**
_As title_

**To Reproduce**
_1 Follow requirements for builder set-up_
_2. Build fails because PyYAML not available_

**Expected behavior**
_Set up will complete and packages build_

**Actual behavior**
_As title._

**Solutions you've tried**
_If applicable, any solutions or workarounds you've already tried._

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
_A list of links to the Qubes documentation (or other relevant software documentation) pages you have already consulted._

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
_A list of links to other bug reports, feature requests, or tasks in the qubes-issues tracker (or "none" if you didn't find any). Do not describe any other unreported bugs, features, or tasks here._

**Comment by qufo418** [comment]
Hi, I followed the new process, but it's still missing: https://qubes-os.discourse.group/t/building-qubes-iso-fedora-32-dnf-error-python2-sh-unable-to-find-match/667/18?u=qufo

**Comment by qufo418** [comment]
I just build mgmt-salt. I changed in qubes-src/mgmt-salt/yaml-dumper the first line from 
`#!/usr/bin/python2 -O`
to
`#!/usr/bin/python -O`

I try to build the ISO now.

**Comment by marmarek** [comment]
Fixed with https://github.com/QubesOS/qubes-mgmt-salt/commit/41dd4a6e608e737b3d431fcc94e8622359225915 and https://github.com/QubesOS/qubes-mgmt-salt/commit/4290985be890ebf3128d3d90ca06d62f07860e8e
Downloading new sources (make get-sources) should be enough.
