### ISSUE TITLE
Restarting USB Qube, with Block Devices Attached to Other VM, Prevents Reattaching Same Block Device to Same VM

### ISSUE THREAD

**Issue by zellchristensen** [QubesOS/qubes-issues#6047]
**Qubes OS version**
R4.0.3

**Affected component(s) or functionality**
Assigning Block Devices to Other VMs from USB Qube

**Brief summary**
If a Block Device (sys-usb:sda) is assigned to a VM and then sys-usb is restarted, the drive cannot be attached to the original, still running, vm again.  

**To Reproduce**
_Steps to reproduce the behavior:_
Plug in a USB flash stick (Partitions format or number of partitions don't seem to matter)
Start up USB Qube (sys-usb)
Start up Other VM (personal)
Assign a Block Device (sys-usb:sda) to Other VM (personal)
Restart USB Qube (sys-usb)
When USB Qube (sys-usb) is back online, attach the same Block Device (sys-usb:sda) to the same Other VM  (personal) as before.

**Expected behavior**
The Block Device (sys-usb:sda) is detached on restart and can be attached as normal when back online.
OR
If the Block Device (sys-usb:sda) is actually attached as the error message implies, it should show up as being attached with the option to detach it once the USB Qube (sys-usb) comes back online.
OR
USB Qube is prevented from shutting down with a warning message that attached devices need to be detached first.

**Actual behavior**
The Block Device (sys-usb:sda) is not attached with an error popup saying "Error: Attaching device [Block Device name] to [Other VM name] failed.  Error: DeviceAlreadyAttached"

**Additional context**
The error only seems to occur on a per Block Device (sda, sda1, sda2, etc) and per VM basis.
Once the error occurs for a given Block Device and given VM, the same Block Device can still be used by any other VM.
Restarting the USB Qube (sys-usb) will create the error again for any attached Block Device to any VMs and could be done until all VMs are unable to have all Block Devices attached.

This does not seem to affect attaching the actual USB device (USB logo), only Block Devices (square logo).
This might be a topic for another issue, but if the actual USB device (USB logo) is attached and detached, block devices no longer show up at all until the USB Qube (sys-usb) is restarted.

**Solutions you've tried**
Restarting the Other VM (personal) fixes the issue for any Block Devices for that VM only.
I tried attaching and detaching the full USB device (USB Logo), but it just causes no Block Devices show up at all until the USB Qube (sys-usb) is restarted. 
The error persists until each affected Other VM (personal) is restarted.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
https://www.qubes-os.org/doc/usb-devices/
https://www.qubes-os.org/doc/usb-qubes/
https://www.qubes-os.org/doc/block-devices/

**Comment by 0spinboson** [comment]
you can usually work around this by running qvm-block d APPVM after sys-usb reboot, but yeah, it's a minor nuisance.
