### ISSUE TITLE
Unable to attach USB to appVM via sys-usb (qrexec or usb-proxy)

### ISSUE THREAD

**Issue by dylangerdaly** [QubesOS/qubes-issues#6048]
**Qubes OS version**
4.1

**Affected component(s) or functionality**
qrexec and or usb-proxy

**Brief summary**
When attempting to attach a USB Device to a Qube (any USB Device to any appVM) I'm greeted with the error

```
Attaching device <blah> to <blah> failed. Error: QubesExeception - Device attach failed: No device info received. connection failed, check backend side for details
```

Not sure how/where "backend side" is but sys-usb is running the latest version of qubes-app-linux-usb-proxy (version 1.0.29) on both dom0 and sys-usb/sys-net.

Running systemctl status for qrexec within sys-usb gives me
`qrexec-agent-data.c:272:handle_new_process_common: pid 1098 exited with 1`

I assume there's some issue with qrexec, how can I troubleshoot this more?

Note: Attaching dom0's mic to any appVM works perfectly, indicating it's sys-usb related.

**To Reproduce**
qvm-usb attach or use the USB Widget and attach any USB Device to any appVM

**Expected behavior**
The USB device is attached to the requested appVM

**Actual behavior**
Throws error `Device attach failed: No device info received. connection failed, check backend side for details`

**Solutions you've tried**
Ensuring latest qubes-app-linux-usb-proxy and qrexec packages are installed.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
https://github.com/QubesOS/qubes-core-qrexec/blob/9f621e6942bfc2d4039ca5da03ed2a7bb411a717/agent/qrexec-agent-data.c#L272

**Comment by andrewdavidwong** [comment]
Possibly related: #5905

**Comment by dylangerdaly** [comment]
Indeed it :100: is related, setting sys-usb to use 5.4 results in successful USB Attachment/Detachment. :tada: 

Apologies for not testing this, issue closed.

**Comment by andrewdavidwong** [comment]
No worries. I suppose I'll mark this as a duplicate of #5905, then.

**Comment by andrewdavidwong** [comment]
Duplicate of #5905
