### ISSUE TITLE
Qube Manager Does Not Refresh "Disk usage"

### ISSUE THREAD

**Issue by zellchristensen** [QubesOS/qubes-issues#6053]
**Qubes OS version**
4.0.3

**Affected component(s) or functionality**
Qube Manager

**Brief summary**
The "Disk usage" section doesn't seem to be refreshed when changes are made that affect it requiring a new instance to be loaded to view.

**To Reproduce**
1.) Open Qube Manager.
2.) Create new VM and copy some files to it and shut down  -OR- Clone existing VM (with disk usage) -OR - Rename existing VM
3.) Observe that Qube Manager reports 0.0 MiB for Disk usage for newly created Qube.
4.) Open second Qube Manager instance to compare and see that it's different.

**Expected behavior**
Disk usage is updated when changes that affect it are made.
OR
Disk usage is updated on a manual refresh from the user (f5 or GUI button).

**Actual behavior**
Disk usage reports 0.0 MiB until another instance of Qube Manager is launched (old instance still reports 0.0 MiB)

**Solutions you've tried**
Loading a new instance and closing the old instance seems to be the only way to update it.

**Comment by marmarta** [comment]
We don't really have live updates on disk utilization (for many reasons), but what can be done (and should be - I think it vanished during some update and nobody notices) is updating disk size periodically, like, every minute or so.

**Comment by marmarta** [comment]
debugging this depends on https://github.com/QubesOS/qubes-issues/issues/6086

**Comment by marmarta** [comment]
This is not implemented in 4.2 and I think it should be, although probably partially (updating size on disk is fairly slow).
