### ISSUE TITLE
qvm-device and qubesd: protocol error

### ISSUE THREAD

**Issue by andrewclausen** [QubesOS/qubes-issues#6057]
**Qubes OS version** R4.0 with all updates.

**Affected component(s) or functionality**
qvm-device and qubesd

**The Problem**

I can list/attach/detach devices correctly with the GUI "Qubes Devices" tool, but not on the command line:

```
[clausen@dom0 ~]$ qvm-device list
Got empty response from qubesd. See journalctl in dom0 for details.
[clausen@dom0 ~]$ sudo journalctl --since "10 seconds ago" | grep qubesd
Sep 16 12:10:44 dom0 qubesd[1815]: protocol error for call b'admin.vm.device.list.Available'+b'' (b'dom0' → b'admin') with payload of 0 bytes
```

**Comment by andrewclausen** [comment]
I should add: I am sure this worked last week.  I only noticed it stop working today.  I can't guess what changed.

**Comment by marmarek** [comment]
> [clausen@dom0 ~]$ qvm-device list

This couldn't possibly worked. You forgot device type, like `qvm-device usb list`.

**Comment by andrewclausen** [comment]
Shouldn't qvm-device give an appropriate error message?

**Comment by marmarek** [comment]
What you've done is requested list of devices of "list" type, which doesn't exist. Yes, the error message could be improved.
https://github.com/QubesOS/qubes-core-admin-client/pull/162

**Comment by andrewclausen** [comment]
Thanks a lot @marmarek !
