### ISSUE TITLE
Qubes Updater breaks Debian-Testing Template

### ISSUE THREAD

**Issue by sidhussmann** [QubesOS/qubes-issues#6061]
**Qubes OS version**
R4.0.3 up to date

**Affected component(s) or functionality**
Debian Testing Template

**Brief summary**
While I'm aware that debian-testing is not officially supported, I believe that this bug is worth sharing and there might be a rather easy solution to it. The Qubes updater removes following rather important package from a debian testing templates: 

* libpython-stdlib 
* python python-minimal 
* qubes-core-agent 
* qubes-core-agent-networking 
* qubes-gui-agent 
* qubes-input-proxy-sender 
* qubes-usb-proxy 
* qubes-vm-dependencies 
* xen-utils-common

The update fails and leaves the template and all the app-vms that depend on it in a non-bootable state. There is no way to circumvent/notice that these packages will be removed once you start the update using `qubes-update-gui`.

**To Reproduce**

Apart of using the `qubes-update-gui` the problem can be reproduced as follows:
1. in debian testing template:
```
$ cat /etc/apt/sources.list /etc/apt/sources.list.d/qubes-r4.list | grep -v '#'
deb http://deb.debian.org/debian testing main contrib non-free

deb http://security.debian.org testing-security main contrib non-free

deb [arch=amd64] https://deb.qubes-os.org/r4.0/vm bullseye main
```
2. Initiate a dist-upgrade:
```
$ sudo apt update
$ sudo apt dist-upgrade 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following packages were automatically installed and are no longer required:
  dconf-cli ethtool initscripts insserv kdevelop55-libs libpython2-stdlib libpython2.7-minimal libpython2.7-stdlib libqubes-rpc-filecopy2 libqubesdb net-tools python2 python2-minimal python2.7 python2.7-minimal python3-daemon
  python3-qubesdb python3-xdg qubes-utils qubesdb qubesdb-vm startpar sysv-rc tinyproxy tinyproxy-bin usbutils xenstore-utils xinit
Use 'sudo apt autoremove' to remove them.
The following packages will be REMOVED:
  libpython-stdlib python python-minimal qubes-core-agent qubes-core-agent-networking qubes-gui-agent qubes-input-proxy-sender qubes-usb-proxy qubes-vm-dependencies xen-utils-common
The following packages have been kept back:
  gcc-8-base
The following packages will be upgraded:
  libpython2-stdlib python2 python2-minimal
3 upgraded, 0 newly installed, 10 to remove and 1 not upgraded.
Need to get 73.0 kB of archives.
After this operation, 1,845 kB disk space will be freed.
Do you want to continue? [Y/n]
```
3. Hit Enter, shutdown template and try to start it again

**Expected behavior**
The template should never break during an update.
Either the updater shouldn't remove any packages, the update should fail before removing them or it should warn that there will be packages removed and giving an option to abort the update.

**Actual behavior**
The template breaks.

**Solutions you've tried**
The simplest solution IMHO is that the `qubes-update-gui` does not a full `dist-upgrade` but only a `upgrade`. The template remains in working state if I do the following:

```
$ sudo apt upgrade
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following packages have been kept back:
  gcc-8-base libpython2-stdlib python2 python2-minimal
0 upgraded, 0 newly installed, 0 to remove and 4 not upgraded.
```

**Comment by unman** [comment]
On Thu, Sep 17, 2020 at 08:32:52AM -0700, Sid Hussmann wrote:
> **Qubes OS version**
> R4.0.3 up to date
> 
> 
> 
> **Affected component(s) or functionality**
> Debian Testing Template
> 
> 
> 
> **Brief summary**
> While I'm aware that debian-testing is not officially supported, I believe that this bug is worth sharing and there might be a rather easy solution to it. The Qubes updater removes following rather important package from a debian testing templates: 
> 
> * libpython-stdlib 
> * python python-minimal 
> * qubes-core-agent 
> * qubes-core-agent-networking 
> * qubes-gui-agent 
> * qubes-input-proxy-sender 
> * qubes-usb-proxy 
> * qubes-vm-dependencies 
> * xen-utils-common
> 
> The update fails and leaves the template and all the app-vms that depend on it in a non-bootable state. There is no way to circumvent/notice that these packages will be removed once you start the update using `qubes-update-gui`.
> 
> 
> **To Reproduce**
> 
> Steps to reproduce the behavior:
> Apart of using the `qubes-update-gui` the problem can be reproduced as follows:
> 1. in debian testing template:
> ```
> $ cat /etc/apt/sources.list /etc/apt/sources.list.d/qubes-r4.list | grep -v '#'
> deb http://deb.debian.org/debian testing main contrib non-free
> 
> deb http://security.debian.org testing-security main contrib non-free
> 
> deb [arch=amd64] https://deb.qubes-os.org/r4.0/vm bullseye main
> ```
> 2. Initiate a dist-upgrade:
> ```
> $ sudo apt update
> $ sudo apt dist-upgrade 
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> Calculating upgrade... Done
> The following packages were automatically installed and are no longer required:
>   dconf-cli ethtool initscripts insserv kdevelop55-libs libpython2-stdlib libpython2.7-minimal libpython2.7-stdlib libqubes-rpc-filecopy2 libqubesdb net-tools python2 python2-minimal python2.7 python2.7-minimal python3-daemon
>   python3-qubesdb python3-xdg qubes-utils qubesdb qubesdb-vm startpar sysv-rc tinyproxy tinyproxy-bin usbutils xenstore-utils xinit
> Use 'sudo apt autoremove' to remove them.
> The following packages will be REMOVED:
>   libpython-stdlib python python-minimal qubes-core-agent qubes-core-agent-networking qubes-gui-agent qubes-input-proxy-sender qubes-usb-proxy qubes-vm-dependencies xen-utils-common
> The following packages have been kept back:
>   gcc-8-base
> The following packages will be upgraded:
>   libpython2-stdlib python2 python2-minimal
> 3 upgraded, 0 newly installed, 10 to remove and 1 not upgraded.
> Need to get 73.0 kB of archives.
> After this operation, 1,845 kB disk space will be freed.
> Do you want to continue? [Y/n]
> ```
> 3. Hit Enter, shutdown template and try to start it again
> 
> **Expected behavior**
> The template should never break during an update.
> Either the updater shouldn't remove any packages, the update should fail before removing them or it should warn that there will be packages removed and giving an option to abort the update.
> 
> 
> 
> **Actual behavior**
> The template breaks.
> 
> 
> **Solutions you've tried**
> The simplest solution IMHO is that the `qubes-update-gui` does not a full `dist-upgrade` but only a `upgrade`. The template remains in working state if I do the following:
> 
> ```
> $ sudo apt upgrade
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> Calculating upgrade... Done
> The following packages have been kept back:
>   gcc-8-base libpython2-stdlib python2 python2-minimal
> 0 upgraded, 0 newly installed, 0 to remove and 4 not upgraded.
> ```
> 
> 

Thanks for the report.
I've said it many times. Debian testing is a **testing** platform.
Things will break and this is to be expected.
> Sometimes, especially when packages are being restructured, packages that are not quite releasable may get into the next-stable distribution. So, there may remain some of the fun of using a constantly evolving development distribution. 

You've had some of that "fun".
Most (all?) of the time, for the stable OS, the updater action is correct, and
I think that your expectation is unreasonable when you *choose* to use a
testing version.
Would it be possible to identify testing platforms given the ability to
rename and clone templates? I doubt it.

**Comment by h01ger** [comment]
On Thu, Sep 17, 2020 at 08:59:58AM -0700, unman wrote:
> Thanks for the report.
> I've said it many times. Debian testing is a **testing** platform.
> Things will break and this is to be expected.

true that. also true is that such reports are useful to actually fix those 
breakages so I dont see why you are complaining about such reports.


-- 
cheers,
	Holger

-------------------------------------------------------------------------------
               holger@(debian|reproducible-builds|layer-acht).org
       PGP fingerprint: B8BF 5413 7B09 D35C F026 FE9D 091A B856 069A AA1C

Religion has been more harmful to humanity than cigarettes.

**Comment by sidhussmann** [comment]
> You've had some of that "fun".
> Most (all?) of the time, for the stable OS, the updater action is correct, and
> I think that your expectation is unreasonable when you *choose* to use a
> testing version.

@unman I understand that it can get frustrating to repeatably handle the same types of issues, especially when it comes to unsupported templates. Before discovering Qubes OS, I have been a debian unstable/sid user for many years. So I am fully aware of the risks of using debian testing. In this particular issue however, I would argue that even (or especially) for debian stable there is no need to trigger a `apt dist-upgrade` but just a `apt upgrade` from the `qubes-update-gui`. This would not jeopardize the "correctness" of updating debian stable, while making updating debian testing substantially less risky.

I can relate that the way I formulated the "expected behavior" would lead to your response. However, I don't see any arguments against the proposed solution.

**Comment by marmarek** [comment]
Using just `apt-get upgrade` instead of `apt-get dist-upgrade` will skip installing new packages, which is needed from time to time.

@h01ger Does apt have some mechanism preventing removal of selected packages? Yum/dnf has "protected packages" to mark key system packages.

Anyway, as for the root cause of the actual issue, I think it's related to python -> python2 rename. I'm not sure which package exactly, but probably [xen-utils-common](https://github.com/QubesOS/qubes-vmm-xen/blob/xen-4.8/debian-vm/debian/control#L101). Since we have migrated to python3 on Fedora completely, I think it shouldn't be a problem to change debian packaging too.

**Comment by h01ger** [comment]
On Thu, Sep 17, 2020 at 03:06:37PM -0700, Marek Marczykowski-Górecki wrote:
> @h01ger Does apt have some mechanism preventing removal of selected packages? Yum/dnf has "protected packages" to mark key system packages.

To put a package on hold: echo pkgname hold | dpkg --set-selections
To remove the hold: echo pkgname install | dpkg --set-selections 
 
> Anyway, as for the root cause of the actual issue, I think it's related
> to python -> python2 rename. I'm not sure which package exactly, but probably
> [xen-utils-common](https://github.com/QubesOS/qubes-vmm-xen/blob/xen-4.8/debian-vm/debian/control#L101).
> Since we have migrated to python3 on Fedora completely, I think it shouldn't
> be a problem to change debian packaging too.

on the contrary, python2 is (practically) gone from bullseye too and everything
should be moved to python3, /usr/bin/python3 as /usr/bin/python will go 
away / stay python2.


-- 
cheers,
	Holger

-------------------------------------------------------------------------------
               holger@(debian|reproducible-builds|layer-acht).org
       PGP fingerprint: B8BF 5413 7B09 D35C F026 FE9D 091A B856 069A AA1C

**Comment by marmarek** [comment]
> To put a package on hold: echo pkgname hold | dpkg --set-selections

Doesn't it also prevent package updates?

**Comment by unman** [comment]
On Thu, Sep 17, 2020 at 09:30:09AM -0700, Holger Levsen wrote:
> On Thu, Sep 17, 2020 at 08:59:58AM -0700, unman wrote:
> > Thanks for the report.
> > I've said it many times. Debian testing is a **testing** platform.
> > Things will break and this is to be expected.
> 
> true that. also true is that such reports are useful to actually fix those 
> breakages so I dont see why you are complaining about such reports.
> 
> 

Who was complaining?
I thanked for the report, and then explained why I thought the expectation
was misplaced, and why I thought the proposed solution was not good.
But such reports are good.

On the other hand, I find that many questons about (e.g) Kali and Qubes would best
be treated in the mailing list rather than directly in qubes-issues.

**Comment by h01ger** [comment]
On Thu, Sep 17, 2020 at 04:43:44PM -0700, Marek Marczykowski-Górecki wrote:
> > To put a package on hold: echo pkgname hold | dpkg --set-selections
> Doesn't it also prevent package updates?

yes. :/


-- 
cheers,
	Holger

-------------------------------------------------------------------------------
               holger@(debian|reproducible-builds|layer-acht).org
       PGP fingerprint: B8BF 5413 7B09 D35C F026 FE9D 091A B856 069A AA1C

**Comment by sidhussmann** [comment]
> Using just `apt-get upgrade` instead of `apt-get dist-upgrade` will skip installing new packages, which is needed from time to time.

@marmarek I wasn't aware of that. Reading the man page APT-GET(8), I notice that there is the option `--no-remove`, which would lead to a failed upgrade and thus not removing anything:

```
$ sudo apt-get dist-upgrade --no-remove -y
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following packages were automatically installed and are no longer required:
  dconf-cli ethtool initscripts insserv libpython2-stdlib libpython2.7-minimal libpython2.7-stdlib libqubes-rpc-filecopy2 libqubesdb libusrsctp1 net-tools python2 python2-minimal python2.7 python2.7-minimal python3-daemon
  python3-qubesdb python3-xdg qubes-utils qubesdb qubesdb-vm startpar sysv-rc tinyproxy tinyproxy-bin usbutils xenstore-utils xinit
Use 'sudo apt autoremove' to remove them.
The following packages will be REMOVED:
  libpython-stdlib python python-minimal qubes-core-agent qubes-core-agent-networking qubes-gui-agent qubes-input-proxy-sender qubes-usb-proxy qubes-vm-dependencies xen-utils-common
The following NEW packages will be installed:
  libltc11 libopenni2-0
The following packages have been kept back:
  gcc-8-base
The following packages will be upgraded:
  dconf-cli dconf-gsettings-backend dconf-service gstreamer1.0-gl gstreamer1.0-gtk3 gstreamer1.0-libav gstreamer1.0-plugins-bad gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-ugly gstreamer1.0-pulseaudio
  gstreamer1.0-x initramfs-tools initramfs-tools-core libavcodec58 libavfilter7 libavformat58 libavresample4 libavutil56 libdconf1 libglib2.0-0 libglib2.0-bin libglib2.0-data libglib2.0-dev libglib2.0-dev-bin libgnutls30
  libgstreamer-gl1.0-0 libgstreamer-plugins-bad1.0-0 libgstreamer-plugins-base1.0-0 libgstreamer1.0-0 libpostproc55 libpython2-stdlib librubberband2 libswresample3 libswscale5 libuv1 libwpebackend-fdo-1.0-1 python2 python2-minimal
39 upgraded, 2 newly installed, 10 to remove and 1 not upgraded.
E: Packages need to be removed but remove is disabled.
```

I couldn't find the repo of the code for `qubes-update-gui`. Is it a frontend for `qubes-mgmt-salt` and would it be possible to configure without having to rebuild `qubes-update-gui`?

**Comment by unman** [comment]
On Sat, Sep 19, 2020 at 09:01:55AM -0700, Sid Hussmann wrote:
> > Using just `apt-get upgrade` instead of `apt-get dist-upgrade` will skip installing new packages, which is needed from time to time.
> 
> @marmarek I wasn't aware of that. Reading the man page APT-GET(8), I notice that there is the option `--no-remove`, which would lead to a failed upgrade and thus not removing anything:
> 
> ```
> $ sudo apt-get dist-upgrade --no-remove -y
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> Calculating upgrade... Done
> The following packages were automatically installed and are no longer required:
>   dconf-cli ethtool initscripts insserv libpython2-stdlib libpython2.7-minimal libpython2.7-stdlib libqubes-rpc-filecopy2 libqubesdb libusrsctp1 net-tools python2 python2-minimal python2.7 python2.7-minimal python3-daemon
>   python3-qubesdb python3-xdg qubes-utils qubesdb qubesdb-vm startpar sysv-rc tinyproxy tinyproxy-bin usbutils xenstore-utils xinit
> Use 'sudo apt autoremove' to remove them.
> The following packages will be REMOVED:
>   libpython-stdlib python python-minimal qubes-core-agent qubes-core-agent-networking qubes-gui-agent qubes-input-proxy-sender qubes-usb-proxy qubes-vm-dependencies xen-utils-common
> The following NEW packages will be installed:
>   libltc11 libopenni2-0
> The following packages have been kept back:
>   gcc-8-base
> The following packages will be upgraded:
>   dconf-cli dconf-gsettings-backend dconf-service gstreamer1.0-gl gstreamer1.0-gtk3 gstreamer1.0-libav gstreamer1.0-plugins-bad gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-ugly gstreamer1.0-pulseaudio
>   gstreamer1.0-x initramfs-tools initramfs-tools-core libavcodec58 libavfilter7 libavformat58 libavresample4 libavutil56 libdconf1 libglib2.0-0 libglib2.0-bin libglib2.0-data libglib2.0-dev libglib2.0-dev-bin libgnutls30
>   libgstreamer-gl1.0-0 libgstreamer-plugins-bad1.0-0 libgstreamer-plugins-base1.0-0 libgstreamer1.0-0 libpostproc55 libpython2-stdlib librubberband2 libswresample3 libswscale5 libuv1 libwpebackend-fdo-1.0-1 python2 python2-minimal
> 39 upgraded, 2 newly installed, 10 to remove and 1 not upgraded.
> E: Packages need to be removed but remove is disabled.
> ```
> 
> I couldn't find the repo of the code for `qubes-update-gui`. Is it a frontend for `qubes-mgmt-salt` and would it be possible to configure without having to rebuild `qubes-update-gui`?
> 

That's no good, because there are cases where we *do* want to remove
packages.
Also, as I've pointed out, unless we use the tag system extensively,
how will we target this against debian-testing based templates? We don't
want a solution that only works against templates *called*
debian-testing.
My solution is simple - don't use automatic updates for any testing
based templates. ( I have quite a few.)

**Comment by sidhussmann** [comment]
@unman you are right. There are cases where we do want to remove packages. I do have a solution though. In the debian testing template:

```
# echo 'APT::Get::Remove "0";' > /etc/apt/apt.conf.d/80no-remove
```

This will lead to the behavior I described above, where a `dist-upgrade` would fail, when packages are to be removed, even when triggered from `qubes-update-gui`. To fix the failed `dist-upgrade` one would then need to manually initiate the dist-upgrade from within the template and disable the `--no-remove` option as follows:

```
$ sudo apt dist-upgrade -o APT::Get::Remove=1
```

In case of debian testing one should pay close attention when that happens, and only proceed when one is sure that the to be removed packages are indeed safe to let go.

**Comment by sidhussmann** [comment]
The breakage has been fixed in https://github.com/QubesOS/qubes-vmm-xen/commit/f0a5537640ecfa393f5ee7852a96d6fcd367315d so we can close this issue.
