### ISSUE TITLE
Resume from suspending is broken after update to Xen 4.14

### ISSUE THREAD

**Issue by jevank** [QubesOS/qubes-issues#6066]
Qubes R4.1

I`ve tested with X1 Thinkpad gen6. Hyperthreading is disabled in UEFI, kernel 5.4.51 and 5.4.61. With Xen 4.13 all works fine. 

Tried with and without VMs running. Looks like suspend successful (thinkpad's led smooth blinked), but it doesn't resume.

Is problem specific to me?

---
There are multiple bugs causing this, summary below.

S3 related bugs in Xen 4.14 summary:
 - Shadow Stack resume path broken - fix in https://github.com/QubesOS/qubes-vmm-xen/pull/88 (sent upstream too already)
 - CR4 restored too late: [discussion](https://lists.xenproject.org/archives/html/xen-devel/2020-10/msg00243.html), [fix](https://lists.xenproject.org/archives/html/xen-devel/2020-10/msg00243.html)
 - [`Assertion 'c2rqd(sched_unit_master(unit)) == svc->rqd' failed at credit2.c:2273`](https://lists.xenproject.org/archives/html/xen-devel/2020-09/msg02074.html) - no solution yet, [a change in Xen 4.14](https://lists.xenproject.org/archives/html/xen-devel/2020-10/msg00259.html) makes it more likely to happen
 - [crash in memguard_guard_stack](https://lists.xenproject.org/archives/html/xen-devel/2020-10/msg00261.html) - can be worked around by disabling Shadow Stack build time
 - hang after second resume (not analyzed yet)

**Comment by andrewdavidwong** [comment]
> X1 Thinkpad gen6

Was suspend ever working on this model in Qubes? I thought I remember hearing a *long* time ago that it wasn't working.

P.S. -- Please use the issue template. This is borderline unsuitable for qubes-issues.

**Comment by jevank** [comment]
Yes, It works with Xen 4.13 till upgrading to 4.14.

P.S. -- ok

**Comment by marmarek** [comment]
The same happens in openQA: https://github.com/QubesOS/qubes-issues/issues/6049

**Comment by marmarek** [comment]
Bisected to https://github.com/xen-project/xen/commit/633ecc4a7cb

**Comment by marmarek** [comment]
And the fix: https://lists.xenproject.org/archives/html/xen-devel/2020-09/msg01892.html

**Comment by jevank** [comment]
I my case patch gives me reboot while resume action...

**Comment by marmarek** [comment]
I do have a system where the resume is still broken, but looks like a proper panic instead of instant reboot now (5s timeout before reboot, instead of instant). Sadly I don't have serial console there, so I don't know what really happened.

**Comment by jevank** [comment]
Looks like I have similar timeout and have no serial port at laptop too

**Comment by marmarek** [comment]
Discussion on xen-devel: https://lists.xenproject.org/archives/html/xen-devel/2020-09/msg02074.html

**Comment by pwmarcz** [comment]
Seeing the same on System76 Galago Pro 4. Suspend worked on Xen 4.13. On 4.14 fans and screen wake up, the Fn-1 fan control works, but the laptop doesn't respond to anything else, and there is nothing on the logs after suspending.

**Comment by jevank** [comment]
@pwmarcz Have you tried [patch](https://github.com/QubesOS/qubes-vmm-xen/pull/88) from PR?

**Comment by pwmarcz** [comment]
@jevank I tried it just now, but there's no change, also with all the VMs stopped.

I should also mention that on this laptop reboot doesn't work, so it's possible that Xen was trying to reboot and froze the computer.

**Comment by marmarek** [comment]
I've run yet another bisection and here are the findings: https://lists.xenproject.org/archives/html/xen-devel/2020-10/msg00002.html

**Comment by marmarek** [comment]
Few bisection runs later... I've updated issue description with the summary.

**Comment by marmarek** [comment]
@pwmarcz I've force-pushed https://github.com/QubesOS/qubes-vmm-xen/pull/88 with fixes collected so far. Can you test it?

**Comment by pwmarcz** [comment]
@marmarek Works so far! I did two succesful resumes with VMs running.

**Comment by jevank** [comment]
Works fine, great, so much combined errors, thank you.

**Comment by planiitis** [comment]
Resume is still not working for me even on the newer releases of Xen (as of 4.14.0-6). Not sure whether this should be treated as the same or a new issue.

Qubes R4.1.0 on Thinkpad L14 Gen1 with AMD Ryzen 5 4500U.

On Xen 4.14.0-6, resume results in a solid power LED and (sometimes) fan spinning, but screen remains off. Any music playing in an AppVM continues after about 7 seconds. Keyboard input seems to have no effect. At about 17 seconds, playback breaks down (starts looping on a single chunk of audio). At about 22 seconds, the computer reboots by itself.

The updates did fix something: On older releases of Xen 4.14 (before 4.14.0-5), attempting to resume would result in fan turning on and keyboard briefly lighting up, but screen would remain black, with power LED still indicating suspend. No indication of VMs resuming. After maybe 10 to 20 seconds, the computer would emit a "SmartBeep" error code of "0002: Internal bus error".

On Xen 4.13.1-4, resume from suspend works perfectly and takes about 2.5 seconds.

**Comment by planiitis** [comment]
Resume still not working as of 4.14.1-1.

What's the best way to help get to the bottom of this issue?

**Comment by dmoerner** [comment]
Resume from suspend leads to a reboot on a Dell Latitude 4700, Intel i5-8365U, with 4.14.1-3 (with and without the HWP patches).

Is there any way to make bisecting this a bit less painful? I can't just downgrade to 4.13 without rebuilding a number of other packages that, as built, depend on 4.14.

**Comment by prdn** [comment]
This is still happening on x1 carbon gen 9, using 4.14.1-4

**Comment by bigdx** [comment]
> This is still happening on x1 carbon gen 9, using 4.14.1-4

X1 Carbon G9 and Tiger Lake (Intel Gen 11) doesnt support S3 at all, see https://github.com/QubesOS/qubes-issues/issues/6411

Btw. do current Ryzen 5000 CPUs (Ryzen 5500U, 5700U, 5300U) still fully support S3? Meaning, if this suspend-issue is fixed, they will suspend AND resume/wake up again?

**Comment by tlaurion** [comment]
@marmarek @fepitre Anything that can be tuned in to debug this kind of issue with clear steps to give proper debugging output?

Having same behavior on Q4.1 from x230 booted from coreboot 4.13 Heads branch.
Behavior is not present when booting live Fedora 32, which can suspend and resume from suspend. Xen is at cause, but how to troubleshoot?

Doing a `journalctl --boot -1` shows absolutely nothing interesting from dom0, which pauses VM and then go to suspend, where no xl dmesg trace is verbose enough to troubleshoot anything interesting there either.
The Power light flashes showing it is in suspend, but there is no way to resume, the power button keeps flashing and its impossible to wake it up but hard reboot.

Idea: could there be a debug build added to https://qubes.notset.fr/iso/ so that Xen is more verbose on its state?
Having a ISO (slower) with all debugging options passed to grub config would be a life saver for debugging purposes.
Or alternatively, a pointer into what needs to be added to have all important components output maximum output, with even maybe turning off disk caching so the logs are actually saved on disk directly?

**Comment by gw0** [comment]
Resume from suspend is also broken on Qubes R4.1-beta1 on Dell XPS 15 9750. Suspend seems to work, but resume just spins up the fan and keyboard backlight, and after a few seconds Xen reboots.

On R4.0.4 it worked flawlessly after adding kernel parameter `mem_sleep_default=deep`.

Failed attempts to get debugging output (maybe someone knows what is missing to prevent the screen from turning off or how to get the serial output out of a laptop):
- in `/etc/default/grub` for `GRUB_CMDLINE_XEN_DEFAULT` remove `console=none` and add `noreboot=1 loglvl=all dom0_max_vcpus=1 dom0_vcpus_pin` (`noreboot=1` prevents Xen reboot)
- in `/etc/default/grub` for `GRUB_CMDLINE_LINUX` add `initcall_debug ignore_loglevel no_console_suspend`
- `grub2-mkconfig -o /boot/efi/EFI/qubes/grub.cfg`
- force sequential suspend/resume process:`echo 0 > /sys/power/pm_async`
- trigger suspend

Failed attempts to fix resume based on common workarounds mentioned on HCL:
- turn off all VMs prior to suspend (or blacklist WiFi drivers in `sys-net`: `echo iwlmvm >> /rw/config/suspend-module-blacklist && echo iwlwifi >> /rw/config/suspend-module-blacklist`)
- xen parameters: `iommu=no-igfx`
- kernel parameters: `nomodeset i915.enable_rc6=0 i915.alpha_support=1 rd.blacklist.drivers=nouveau nouveau.modeset=0`
- BIOS: disable HT, disable TPM, disable Thunderbolt, disable C-states Control

If somebody wants to dig deeper:
- https://01.org/blogs/rzhang/2015/best-practice-debug-linux-suspend/hibernate-issues

@tlaurion, you can modify the xen/kernel parameters in Grub on-the-fly by pressing `e` and editing it prior booting (`Ctrl+x`).

**Comment by marmarek** [comment]
> Resume from suspend is also broken on Qubes R4.1-beta1 on Dell XPS 15 9750 (with Xen 4.14.2 and Linux 5.10.47-1.fc32 or 5.12.14-1.fc32`). Suspend seems to work, but resume just spins up the fan and keyboard backlight, and after a few seconds Xen reboots.

It is likely this issue:
>     * [`Assertion 'c2rqd(sched_unit_master(unit)) == svc->rqd' failed at credit2.c:2273`](https://lists.xenproject.org/archives/html/xen-devel/2020-09/msg02074.html) - no solution yet, [a change in Xen 4.14](https://lists.xenproject.org/archives/html/xen-devel/2020-10/msg00259.html) makes it more likely to happen

Does it happen for you always, or only sometimes?
I see it quite frequently on openQA tests.

As for collecting logs, I do have a method for that, but it's quite adventurous - make Xen kexec Linux on panic, to dump the memory content, and then to extract logs from there. It requires custom rebuilding Xen (because we have kexec disabled by default), kexec-tools (because the one in Fedora isn't built with Xen), build initramfs that dump the memory (kdump package helps with that, but requires few tweaks to make it work), and finally have some place to save the dump too - if using the main disk, you need to configure LUKS with a key file + allocate quite a lot of RAM for the crashkernel (because of memory-hard Argon2i in LUKS2).
When having the dump, extracting messages is relatively easy - I use `strings` for that. Theoretically the `crash` utility can do that more conveniently, but it didn't work for me.

**Comment by gw0** [comment]
> Does it happen for you always, or only sometimes?

Always.

> As for collecting logs, I do have a method for that, but it's quite adventurous...

Huh, it sounds quite complex to set up.

**Comment by brendanhoar** [comment]
> As for collecting logs, I do have a method for that, but it's quite adventurous - make Xen kexec Linux on panic, 

Is using a pcie serial port card (via expresscard before 4.1 or thunderbolt for 4.1 or later) one alternate way of capturing the combined Xen and Linux console output?

**Comment by marmarek** [comment]
In theory, could be. In practice, every single serial port on expresscard or thunderbolt I've seen was a USB device, not a PCIe device :/

**Comment by brendanhoar** [comment]
> In theory, could be. In practice, every single serial port on expresscard or thunderbolt I've seen was a USB device, not a PCIe device :/

I have a mix of types for expresscard (usb and direct pcie). 

And some pcie serial cards as well (requires thunderbolt to pcie card adapter, tend to be costlier). 

Maybe we should document?

**Comment by marmarek** [comment]
> I have a mix of types for expresscard (usb and direct pcie).

Can you share a model of a serial port expresscard that is really a pcie device?

> Maybe we should document?

Take a look at https://xenbits.xenproject.org/docs/unstable/misc/xen-command-line.html#com1-x86

**Comment by tlaurion** [comment]
On August 3, 2021 2:49:01 PM UTC, "Marek Marczykowski-Górecki" ***@***.***> wrote:
>> I have a mix of types for expresscard (usb and direct pcie).
>
>Can you share a model of a serial port expresscard that is really a pcie device?
>
>> Maybe we should document?
>
>Take a look at https://xenbits.xenproject.org/docs/unstable/misc/xen-command-line.html#com1-x86
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/QubesOS/qubes-issues/issues/6066#issuecomment-891910411
Isn't there tweaks that can be added from boot command line which would make logs saved synchronously and permit to troubleshoot this for everyone without a need of external additional devices @marmarek?

--
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by marmarek** [comment]
> Isn't there tweaks that can be added from boot command line which would make logs saved synchronously and permit to troubleshoot this for everyone without a need of external additional devices @marmarek?

Sadly, not. When Xen panic, dom0 has no chance to execute anything anymore. And it's dom0 who writes logs to the disk.

**Comment by brendanhoar** [comment]
> > I have a mix of types for expresscard (usb and direct pcie).
> 
> 
> 
> Can you share a model of a serial port expresscard that is really a pcie device?

Chipset is the obviously important thing:

![image](https://user-images.githubusercontent.com/8979139/128050404-a84cc800-7f7f-4218-a93e-43120a10be9f.jpeg)

![image](https://user-images.githubusercontent.com/8979139/128050429-8d27eff5-7976-404e-81ec-3b83d1d0810f.jpeg)

![image](https://user-images.githubusercontent.com/8979139/128050455-bd747871-0760-4911-b94e-9e6799a9c4a9.jpeg)

**Comment by brendanhoar** [comment]
If neithe me thunderbolt nor expresscard are available and the machine is recent enough to have one or more M.2 slots, then ifone doesn't mind sessions with the laptop case off (or potentially ribbon cables dangling out of the case), there's this clever solution. After all, an M.2 device is just a pcie device: 

https://www.ebay.com/itm/4-Port-RS-232-DB9-Serial-M-2-B-M-Key-2280-Controller-Card-Asix99100-Chipset-/274780227172?mkcid=16&mkevt=1&_trksid=p2349624.m46890.l6249&mkrid=711-127632-2357-0

**Comment by dmoerner** [comment]
I can't resume from suspend on an X1 carbon 3rd generation with 4.14.2 and fully-updated R4.1 dom0. I don't think I've ever had resume problems before on this machine, dating back to at least R3.2. It has no interesting hardware. It doesn't reboot on resume like my Latitude 7400, it just doesn't resume at all.

**Comment by tlaurion** [comment]
> > Isn't there tweaks that can be added from boot command line which would make logs saved synchronously and permit to troubleshoot this for everyone without a need of external additional devices @marmarek?
> 
> Sadly, not. When Xen panic, dom0 has no chance to execute anything anymore. And it's dom0 who writes logs to the disk (or anything else for that matter).

@marmarek:
>As for collecting logs, I do have a method for that, but it's quite adventurous - make Xen kexec Linux on panic, to dump the memory content, and then to extract logs from there. It requires custom rebuilding Xen (because we have kexec disabled by default), kexec-tools (because the one in Fedora isn't built with Xen), build initramfs that dump the memory (kdump package helps with that, but requires few tweaks to make it work), and finally have some place to save the dump too - if using the main disk, you need to configure LUKS with a key file + allocate quite a lot of RAM for the crashkernel (because of memory-hard Argon2i in LUKS2). When having the dump, extracting messages is relatively easy - I use strings for that. Theoretically the crash utility can do that more conveniently, but it didn't work for me.

This exact QubesOS 4.1 ISO deployment (debug iso) would help to debug so many corner cases for QubesOS project, no?

**Comment by andrewdavidwong** [comment]
> This exact QubesOS 4.1 ISO deployment (debug iso with all above dependencies preconfigured) would help to debug so many corner cases for QubesOS project, including this one? Instruct a willing tester to install QubesOS on spare drive and report results without having to go through the burden of customizing such testing testbed? Should that be discussed in a separate issue (with more details on doing this manual and then automate the process, maybe?)

This certainly sounds like a separate issue to me.

**Comment by brendanhoar** [comment]
@marmarek has acquired an M.2 pcie serial port adapter for Xen laptop suspend debugging (see here: https://github.com/QubesOS/qubes-issues/issues/6834#issuecomment-898649065 )

B

**Comment by marmarek** [comment]
Debugging session was quite fruitful: https://lore.kernel.org/xen-devel/YRuXNmpT+03aPo+p@mail-itl/T/
I have few fixes queued up (waiting for upstream Xen approving them). In the meantime, there is a workaround - go to BIOS and disable hyper threading. We disable it at Xen level anyway, so it shouldn't affect performance in practice.

**Comment by gw0** [comment]
It works, thank you very much @marmarek!

An alternative security-degrading workaround to turn on hyper-threading in Xen (parameter `smt=on`) also works.

**Comment by tlaurion** [comment]
[Fix thread](https://lore.kernel.org/xen-devel/ee399fcbf01ac32a4b26cc9660f400b8d60148b1.camel@suse.com/T/#t)

**Comment by marmarek** [comment]
Yes, this one. And also another one: https://lore.kernel.org/xen-devel/20210818113017.454251-1-marmarek@invisiblethingslab.com/T/#u

**Comment by tlaurion** [comment]
@marmarek are those Xen fixes pushed into new iso builds by @fepitre? From which date?

**Comment by marmarek** [comment]
Not yet.

**Comment by vladimir-lu** [comment]
> Not yet.

@marmarek Is there a plan to make builds with the fixes for R4.1 or will you wait for upstream xen release?

**Comment by johnnyboy-3** [comment]
Resume is broken for me too, but since the beginning I started using Qubes (R4.0).
The problem probably resides somewhere in `amdgpu` since the other users have a Ryzen APU too (2400G here).
I tried the suggestions here and got no luck either, been looking for a solution for months now. Had the same problem before Qubes with arch: blank screen, black screen, green screen, artifacts, a slow system with a screensaver I could unlock but a unresponsive system and dying after 30-60 seconds (screen tuns off, fans turn to 100%).
The problem resolved by itself on arch by the time after upgrading to newer kernels, iirc linux-5.8.5 used to work for me back then before i switched to Qubes. Unfortunately R4.1-beta1 has the same bug with even newer kernels.

**Comment by isodude** [comment]
I have some success in #6859 with newer Lenovo firmware, I will try to see if it's possible to apply the fix to Xen 4.14.

**Comment by isodude** [comment]
@marmarek Not sure I did this right applying patches and recompiling. Which packages are needed to be recompiled/reinstalled to properly add this to dom0?

**Comment by isodude** [comment]
Ignore my comment, it seems that I managed to get it in properly. Running with smt=on and resume works on 5.14.

**Comment by DemiMarie** [comment]
> Ignore my comment, it seems that I managed to get it in properly. Running with smt=on and resume works on 5.14.

smt=on is a very severe security risk, unless SMT is turned off in the firmware.

**Comment by isodude** [comment]
@DemiMarie It was a typo actually. Sorry about that.

**Comment by tlaurion** [comment]
@fepitre : https://github.com/marmarek/qubes-vmm-xen/commit/1bc4a41c0a4095f4d2c196ea89c11b184f0279cd is today+ ISO?

**Comment by DemiMarie** [comment]
Is this fixed?

**Comment by planiitis** [comment]
Resume is still not fully working for me, but since some time in July (possibly earlier), behaviour has been more or less as described in #6923.
