### ISSUE TITLE
Multiple gpg-agent processes cause issues

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#6067]
With the recent change of using separate gpg keyring per git repository, new gpg-agent is started for each of them. After building a few components, we end up with tens of them, each holding a few open files. Not long after we run out of global open FD limit...

Since we don't really do secret key operations in qubes-builder, maybe starting gpg-agent can be avoided? If not, there should be some mechanism to kill the unnecessary ones (after the usage? after some timeout?).

cc @fepitre

**Comment by fepitre** [comment]
I think we can close this one. Please reopen if it's not the case.
