### ISSUE TITLE
Changing Qube Settings Sometimes Locks Up Qube Manager

### ISSUE THREAD

**Issue by zellchristensen** [QubesOS/qubes-issues#6068]
**Qubes OS version**
R4.0.3

**Affected component(s) or functionality**
Qube Manager

**Brief summary**
Changing certain features in the Qube Settings menus sometimes causes Qube Manager to stop responding.  I can't seem to find a way to bring it back without a complete restart.

**To Reproduce**
1. ) Open Qube Settings
2. ) Change certain options such as the Debug Mode checkbox, Memory balancing checkbox, or Initial memory value or Max memory value.

**Expected behavior**
Settings are changed as normal.
OR
A warning pops up if something is incorrect or can't be set.

**Actual behavior**
Qube Manager seems to stop responding with the loading icon displayed on the pointer.
No other VM can be started or shutdown when this happens. 
You can still access the Qube Manager menu at the top to see running VMs.
Trying to open another instance of Qube Manager from that menu doesn't seem to do anything.
Selecting an option from the top menu (ie shutdown/restart for a given Qube) causes that menu to no longer be accessible.  
Attempting to close the Qube Settings window causes a popup a few seconds later saying the window is busy and not responding with the option to terminate.
If the user terminates the application, there doesn't seem to be a way to restart Qube Manager without a full restart.
The shutdown process takes an excessively long time when this happens.

**Additional context**
I haven't been able to figure out how to reliably reproduce this but it seems to only happen when modifying the settings of WindowsVMs with Windows Tools installed.
Initially I thought it was only changing settings while they were running, but it seems to occur sometimes when they're not running.
I can't recall encountering it on any linux VM.
It doesn't seem to occur all the time, but I've had it happen at least 3 to 4 times now.
I think this has only occurred on windowsVMs where the windows username was identical to the Qubes username "user1" in both cases.
I haven't noticed it for windowsVMs set to just "user" but will see if it does. 
I think it's happened for windowsVMs with and without a password set.

**Solutions you've tried**
Attempting to kill qubes-qube-manager from dom0 terminal `pkill qubes-qube-manager` (executes but nothing seems to happen)
Attempting to start `qubes-qube-manager` (seems to just hang, have to ctrl+c to break)
Attempting to start `qubes-qube-manager &` seems to run and gives a new PID each time, but the old GUI windows remain, unresponsive.
Clicking the x and clicking YES on the popup asking to terminate the application removes the windows from dom0 but there doesn't seem to be a way to open the qube manager GUI again without a full restart.

**Comment by marmarta** [comment]
that's really interesting! I'll try to reproduce it, but in the meantime, if this happens again, could you take a look into `journalctl -e` and see if there's anything that looks related/has anything to do with Qube Manager/etc?

**Comment by iamahuman** [comment]
Does `systemctl restart qubesd.service` help?
