### ISSUE TITLE
qrexec-client-vm can break other processes by setting a shared open file description non-blocking

### ISSUE THREAD

**Issue by mattmccutchen** [QubesOS/qubes-issues#6069]
**Qubes OS version:** R4.0

**Affected component(s) or functionality:** `qrexec-client-vm`

**Brief summary:** `qrexec-client-vm` sets its file descriptors 0 and 1 non-blocking for the duration of its execution.  If one of these points to an open file description shared with another process, the other process may get an EAGAIN that it does not expect and malfunction.  The only case I've found in which this happens is starting from a terminal, where fd 0 and 1 both point to the same read-write open file description referring to the terminal, though a similar thing could likely happen with a socket.  Normal users are unlikely to ever hit this, but it confused me for a while when I was using the terminal to test a potential rewrite of `qvm-run-vm` (to be proposed separately) that triggered essentially the reproduction steps below.

**To Reproduce**

1. Run in an AppVM terminal: `cat | qrexec-client-vm '$dispvm' qubes.VMShell`
2. Once the disposable VM starts, type in the original terminal: `echo meow`

**Expected behavior:** After the command executes in the disposable VM (printing `meow`), `cat` continues running so I can `echo purr`.

**Actual behavior:** `cat` meets an untimely death: `cat: -: Resource temporarily unavailable`.  Unfortunately, unlike with Schrödinger's cat, this happens all the time.

**Solutions you've tried**:

A workaround is to stick on another `cat`:

`cat | qrexec-client-vm '$dispvm' qubes.VMShell | cat`

The real solution, if we wish to pursue it, would be for `qrexec-client-vm` to create fresh open file descriptions with `open('/proc/self/fd/0', ...)` and `open('/proc/self/fd/1', ...)`.  I hope the assumption that `/proc` is available is acceptable for Qubes VM tools.  If `openat` supported something like `AT_EMPTY_PATH`, we could use that instead.  If the maintainers would like to take a patch, I might write one, but I don't have a strong desire for this problem to be fixed; I mainly wanted to document it.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted:** None?  The `qrexec-client-vm` man page doesn't address the issue.

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues:** none

**Comment by DemiMarie** [comment]
I *think* (but am not certain) that one can achieve the same effect by sending the file descriptor over a socket using `SCM_RIGHTS`.

**Comment by mattmccutchen** [comment]
@DemiMarie Unfortunately not: "The passed file descriptors behave as though they have been created with dup(2)." ([source](https://linux.die.net/man/7/unix))

**Comment by DemiMarie** [comment]
@mattmccutchen Sadly so.  I tested it and it didn’t work.
