### ISSUE TITLE
Add "Default Name" for Cloned Qubes from Settings Menu

### ISSUE THREAD

**Issue by zellchristensen** [QubesOS/qubes-issues#6070]
**The problem you're addressing (if any)**
When opening a Qube's Settings and choosing the Clone qube button, the name field for the new Qube is blank.

**Describe the solution you'd like**
In the Qube Manager, when right clicking and choosing "Clone qube", the name for the new clone is filled in with a Default name "vmname-clone-#"
I think having the same behavior from the Clone Qube button in the settings menu would be a good idea.

**Where is the value to a user, and who might that user be?**
Less typing for the user, faster workflow.
Otherwise the user has to type out a name which can introduce errors, or they have to close the dialog menu, close the settings menu, find the vm in the list, and right click and clone it to benefit from the default name feature.

**Describe alternatives you've considered**
None

**Additional context**
The two naming windows appear to have different titles.  One is "[Dom0] Qubes clone Qube" (right click menu) and the other "[Dom0] Clone qube" (Button in Settings menu).  

**Screenshots**
From Right Click Menu in Qube Manager: 
![Screenshot_2020-09-18_22-21-22](https://user-images.githubusercontent.com/38737447/93657303-6ed65500-f9f7-11ea-97f9-f45764f628c6.png)

From Clone Qube Button in Qube Settings: 
![Screenshot_2020-09-18_22-21-51](https://user-images.githubusercontent.com/38737447/93657304-7138af00-f9f7-11ea-824c-8c76d96f1aa9.png)

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
None

**Comment by marmarta** [comment]
That's fixed by https://github.com/QubesOS/qubes-manager/commit/bdc11582f1d4b175c0a229de7d575726213d862e - will be included in Qubes 4.1 :)
