### ISSUE TITLE
Remove "File Manager" under dom0 System Tools

### ISSUE THREAD

**Issue by zellchristensen** [QubesOS/qubes-issues#6071]
**The problem you're addressing (if any)**
When opening "File Manager" from the dom0 System Tools menu on the top left, it opens File Manager Preferences (thunar-settings).  

**Describe the solution you'd like**
Change the option to actually open File Manage (thunar) instead of File Manager Preferences (thunar-settings).
Alternatively have both options but named appropriately.

**Where is the value to a user, and who might that user be?**
Adds usability for the user and avoids confusion.
Allows the user to not have to open terminal to run `thunar` manually

**Describe alternatives you've considered**
Remove the option entirely.

**Additional context**
The location `/usr/share/applications/` contains two entries for "File Manager".
One is `exo-file-manager.desktop` which opens `thunar`.
One is `thunar-settings.desktop` which opens `thunar-settings`
Opening both files, they both appear to have the same English name vale "File Manager"

**Screenshots**
![Screenshot_2020-09-18_22-42-45](https://user-images.githubusercontent.com/38737447/93658003-24f06d80-f9fd-11ea-9996-609f2bfc9474.png)

**Solutions you've tried**
I tried modifying the thunar-settings.desktop file to change the name value to "File Manager Settings"  thinking there was some type of conflict with two entries and while it changes the value in the System Tools menu, it doesn't allow the other option to show up.

**Comment by andrewdavidwong** [comment]
Actually, this entry should probably just be removed, since using file managers in dom0 is [disrecommended for security reasons](https://www.qubes-os.org/doc/security-guidelines/#dom0-precautions).

**Comment by andrewdavidwong** [comment]
Duplicate of #2458

**Comment by andrewdavidwong** [comment]
This appears to be a [duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.
