### ISSUE TITLE
Can't Begin Installation if User Clicks Installation Source

### ISSUE THREAD

**Issue by zellchristensen** [QubesOS/qubes-issues#6073]
**Qubes OS version**
R4.0.3

**Affected component(s) or functionality**
Base Installer

**Brief summary**
When running the install media, the option "INSTALLATION SOURCE" under the SOFTWARE section is set to "Local Media" by default.  If the user clicks it, then clicks Done without making any changes, the installer can no longer continue and the user must start over.

**To Reproduce**

1. ) Run base installer.
2. ) Click "INSTALLATION SOURCE" option.
3. ) Click "Done" button on top left corner.

**Expected behavior**
If the user made no changes, no changes should be made.

**Actual behavior**
The installation source is changed causing an error "Error setting up base repository" or stuck "Setting up installation source..."

**Screenshots**
Before choosing any options
![IMG_3382c](https://user-images.githubusercontent.com/38737447/93661594-912f9900-fa1e-11ea-8684-3193f3cca98c.jpg)

After clicking Installation Source. On the Network section is greyed out except for the + and - buttons under Additional Repositories.
![IMG_3383c](https://user-images.githubusercontent.com/38737447/93661600-9b519780-fa1e-11ea-86b5-5a040cd0e873.jpg)

After clicking Done, no options were changed.
![IMG_3384c](https://user-images.githubusercontent.com/38737447/93661606-a60c2c80-fa1e-11ea-83f6-33a554ffe40c.jpg)

Opening the section again due to the Error notice and attempting to correct by selecting ISO file instead of On the Network.  Default option was used. 
![IMG_3385c](https://user-images.githubusercontent.com/38737447/93661627-d2c04400-fa1e-11ea-8c58-51b827519269.jpg)

After clicking Done again
![IMG_3387c](https://user-images.githubusercontent.com/38737447/93661642-ef5c7c00-fa1e-11ea-9ee1-9d18da72655a.jpg)

Software Selection section message changed from "Error downloading package metadata" to "Installation source not set up"
![IMG_3389c](https://user-images.githubusercontent.com/38737447/93661647-013e1f00-fa1f-11ea-89dc-bf0298d90a44.jpg)

The Installation Source section after configuring the Installation Destination section.
![IMG_3390c](https://user-images.githubusercontent.com/38737447/93661694-5ed26b80-fa1f-11ea-932b-46e361ca2cbc.jpg)

Installation Source and Software Selection are no longer accessible at all
![IMG_3391c](https://user-images.githubusercontent.com/38737447/93661700-73166880-fa1f-11ea-8cd7-0d69d693877f.jpg)

Begin Installation is greyed out and the only option is to Quit.
![IMG_3392c](https://user-images.githubusercontent.com/38737447/93661702-77428600-fa1f-11ea-90ef-40182c84e19f.jpg)

**Additional context**
If the user ignores the error and continues to set up the Installation Destination section and tries to return back to the Installation Source files, the Local Media section is no longer present at all.
After this step, sometimes the option can no longer be opened again at all.
The device is not connected to the internet during install.
I'm running the install media from a USB stick.

**Solutions you've tried**
Before moving on to the Installation Destination (disks) section, there's a section to select local media, but selecting the default options doesn't work.
There's an option to try to find an ISO file, but no ISO files seem to exist within the install media.
After opening the Installation Destination section, there's no longer any other solution except to Quit the installation and restart it again.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
Install media

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
None

**Comment by mgruene** [comment]
I had the same issue when using the latest version. I am now trying to install 4.0RC3 which is the version that was used when documenting the Lenovo T470 install routines. 
What I see is that the Linux "livecd-iso-to-disk" for the old version runs massively longer than for the new. It looks like for the newest version, when writing the ISO to USB, numerous rpm packages are omitted.

**Comment by joakim** [comment]
This seems to be worked around in 4.1.1?

I had the same issue as in the photos, which brought me here, but I was able to begin the installation. So while the UI issue remains, it's not blocking the installation. At least for me.

**Comment by andrewdavidwong** [comment]
> This seems to be worked around in 4.1.1?
> 
> I had the same issue as in the photos, which brought me here, but I was able to begin the installation. So while the UI issue remains, it's not blocking the installation. At least for me.

Closing as resolved in Qubes 4.1. Since [every issue must be about a single, actionable thing](https://www.qubes-os.org/doc/issue-tracking/#every-issue-must-be-about-a-single-actionable-thing), please open a separate issue for the UI portion. If anyone believes this issue is not yet resolved, or if anyone is still affected by this issue, please leave a comment, and we'll be happy to reopen it. Thank you.
