### ISSUE TITLE
Weird behaviour after attaching usb drive

### ISSUE THREAD

**Issue by johnblanc** [QubesOS/qubes-issues#6075]
I attached trusted usb drive to one of the VMs to copy some stuff to it, and number of problems happened

- the file saved to it was 0 bytes

-after attaching it again I could write to it, not even browse it actually

- the file explorer froze and has been like that for a day

- i can browse local files but when i try to open one in gedit, it just hangs on loading forever

latest version here

**Comment by andrewdavidwong** [comment]
Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this does not appear to be suitable for `qubes-issues`. We ask that you please post this on the [`qubes-users` mailing list or forum](https://www.qubes-os.org/support/) instead. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a brief comment explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.
