### ISSUE TITLE
Provide option to view unobfuscated backup/restore passphrase

### ISSUE THREAD

**Issue by tumbletree** [QubesOS/qubes-issues#6076]
### Affected component(s) or functionality:
Backup and Restore features

---

### Steps to reproduce the behavior:
Use it as normal. 
Note the password prompt for the encrypted backup.

### Expected or desired behavior:
Just like every other decent password field I encounter these days: 
a) see the password/phrase in plain text if desired
b) paste a passphrase in from a password manager
c) confirm the fidelity of the passphrase by taking input in duplicate field and checking passphrases match

In decryption (i.e Restore), omit (c)

### Actual behavior:

There's just a single, obfuscated line of *. It must be typed. I have no way of knowing if I have done it correctly.

### General notes:

I am pretty unhappy. I use KeePassXC religiously, and somehow the passphrase is not working. This is on two separate keepassxc database backups (done separately), and attempted on three separate qubes backups.

This is definitely user error. I have made a mistake somewhere. The problem is, I have no idea if I made the error when I set up the backup (failure to transcribe from/into KeepassXC), or if I am typing it wrong now. I cannot troubleshoot now, and could not prevent the error before.

This is bad. I have lost data, at least 12 months' work. Not to mention the hassle of fine-tuning all my vm set-ups.

I find myself cursing myself for not backing up individual files, but then - why should I be forced to back-up in defence against the OS's own back-up feature?

We are always liable to make mistakes, because we am human. Those other UX features (visibility, paste-enabled, double-checking and also password managers) developed to keep us safe from those mistakes and improve things by enabling long, strong, high-entropy passphrases. 

This is a really important feature of the system. It should be rectified promptly.

(FWIW - I am unsympathetic to any security tradeoffs, if they exist. There's nothing usefully safe about data sitting on your machine locked away forever.)

---

### I am aware of the following related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues:

I could not get any relevant hits in search field with "password backup restore", but I am almost certain I have seen discussion somewhere before.

**Comment by andrewdavidwong** [comment]
> a) see the password/phrase in plain text if desired
> b) paste a passphrase in from a password manager
> c) confirm the fidelity of the passphrase by taking input in duplicate field and checking passphrases match

I just tested this (Qube Manager -> System -> Backup qubes), and I can paste text from the clipboard, and there are two fields, the second for confirming the passphrase. So, (a) is missing, but (b) and (c) appear to be covered (though it's not recommended to run a password manager in dom0 or copy text into dom0). Are we looking at the same tool?

**Comment by tumbletree** [comment]
Yes Andrew, you are right. I am embarrassed to admit I got that wrong with b) and c). However, if we can't operate a password manager or shouldn't copy-paste into dom), it makes a visual check all the more important. 

Thanks for adding this to the milestone.
