### ISSUE TITLE
tlp breaks WiFi chip passthrough

### ISSUE THREAD

**Issue by artemislena** [QubesOS/qubes-issues#6077]
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
Networking/PCI passthrough

**Brief summary**
With my WiFi chipset (Intel 7265), the NetVM WiFi permanently breaks and the NetVM to be reinstalled whenever I ever use tlp in default settings. The `wls6` interface stays `DOWN` and `sudo ip link set wls6 up returns `RTNETLINK answers: Operation not permitted`.

**To Reproduce**
1. `sudo qubes-dom0-update tlp`
2. `sudo tlp start`
3. Reboot.

**Expected behavior**
WiFi should work.

**Actual behavior**
I cannot connect to any WiFi network.

**Additional context**
I wrote about it at https://fantasycookie17.onederfultech.com/posts/2020/09/qubes-os-tips-and-tricks.html

**Comment by iamahuman** [comment]
As a workaround, modify the `/etc/default/tlp` file in dom0 as follows:

```diff
--- /etc/default/tlp.rpmsave	2017-06-19 03:09:56.000000000 +0000
+++ /etc/default/tlp	2021-07-10 17:15:26.686040631 +0000
@@ -189,20 +189,21 @@
 # Exclude PCI(e) device adresses the following list from Runtime PM
 # (separate with spaces). Use lspci to get the adresses (1st column).
 #RUNTIME_PM_BLACKLIST="bb:dd.f 11:22.3 44:55.6"
 
 # Exclude PCI(e) devices assigned to the listed drivers from Runtime PM.
 # Default when unconfigured is "amdgpu nouveau nvidia radeon" which
 # prevents accidential power-on of dGPU in hybrid graphics setups.
 # Use "" to disable the feature completely.
 # Separate multiple drivers with spaces.
 #RUNTIME_PM_DRIVER_BLACKLIST="amdgpu nouveau nvidia radeon"
+RUNTIME_PM_DRIVER_BLACKLIST="amdgpu nouveau nvidia radeon pciback"
 
 # Set to 0 to disable, 1 to enable USB autosuspend feature.
 USB_AUTOSUSPEND=1
 
 # Exclude listed devices from USB autosuspend (separate with spaces).
 # Use lsusb to get the ids.
 # Note: input devices (usbhid) are excluded automatically
 #USB_BLACKLIST="1111:2222 3333:4444"
 
 # Bluetooth devices are excluded from USB autosuspend:
```
