### ISSUE TITLE
Ungoogled Chromium on Fedora 32 with SoloKey doesn't seem to work for U2F proxy

### ISSUE THREAD

**Issue by artemislena** [QubesOS/qubes-issues#6078]
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
U2F proxy

**Brief summary**
I could not get the U2F proxy to work in my setup.

**To Reproduce**
1. Install and enable U2F proxy in your Browsing VM.
2. Install chromium-browser-privacy from RPMFusion.
3. Try to log in on a site.

**Expected behavior**
Logging in with U2F should work.

**Actual behavior**
It doesn't. The U2F device isn't even asked for anything; the LED colour does not change.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
http://qubesosfasa4zl44o4tws22di6kepyzfeqv3tg4e3ztknltfxqrymdad.onion/doc/u2f-proxy/

**Comment by icequbes1** [comment]
FWIW and as a potential data point, U2F proxy worked on:

1. Fedora 31, fully updated as of October 11, 2020 (qubes-u2f-1.2.5-1.fc31)
2. Ungoogled Chromium 85
3. Yubikey
4. qubes-u2f-dom0-1.2.5-1.fc25

(when testing with WebAuthn.io)
