### ISSUE TITLE
Cloning VM too Quickly after Delete Causes Error

### ISSUE THREAD

**Issue by zellchristensen** [QubesOS/qubes-issues#6079]
**Qubes OS version**
R4.0.3

**Affected component(s) or functionality**
Qube Manager Cloning

**Brief summary**
If a clone is deleted then a new clone is attempted using the same name as the recently delete clone, an error occurs if it's done too quickly.

**To Reproduce**

1. ) Create a clone of a vm. `<vmname>-clone-1`
2. ) Delete the clone. `<vmname>-clone-1`
3. ) Quickly, clone the original VM again. `<vmname>-clone-1`

**Expected behavior**
Clone is created successfully.
OR
A forced wait period occurs preventing the error from happening similar to the loading wait that occurs when cloning a qube.

**Actual behavior**
If done too quickly, the clone is not created and an error message occurs instead. `Logical Volume "<vmname>-private" already exists in volume group "qubes_dom0"`

**Screenshots**
![Screenshot_2020-09-19_18-24-15](https://user-images.githubusercontent.com/38737447/93692664-93940080-fabb-11ea-807e-dd7725189e7d.png)

**Additional context**
The clone name in the error message has `-private` appended to it even though it wasn't added when naming the clone.
After the error occurs, the displayed data (text and icons) in Qubes manager becomes misaligned compared to the alternating color background.  Maybe this should be in a new issue.

**Solutions you've tried**
Waiting longer after a delete works or just attempting again after the error message.

**Comment by andrewdavidwong** [comment]
Related/possible duplicate: #4754
