### ISSUE TITLE
Changing CMDLINE for dom0 doesn’t modify TPM PCRs

### ISSUE THREAD

**Issue by dylangerdaly** [QubesOS/qubes-issues#6081]
**Qubes OS version**
R4.1

**Affected component(s) or functionality**
Bootloader Measurement via TPM

**Brief summary**
Modifying dom0's cmdline didn't change the PCR hashes, any change to the bootloader should result in the PCRs changing.

**To Reproduce**
Read PCRs, reboot, press 'e', add anything to dom0's CMDLINE, observe PCRs are identical.

**Expected behavior**
GRUB2 should report a change during Measured Boot.

**Actual behavior**
PCRs are identical.

**Screenshots**

**Additional context**

**Solutions you've tried**

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

**Comment by marmarek** [comment]
Currently the only supported measured boot in Qubes is via [Anti Evil Maid](https://www.qubes-os.org/doc/anti-evil-maid/). grub2 itself does not have proper TPM integration.

**Comment by dylangerdaly** [comment]
Is it something that can be enabled? I'd like to properly protect LUKs with PCRs/TPM.

Doesn't seem right grub2 doesn't support TPMs.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by marmarek** [comment]
Grub only recently (grub 2.04) got proper TPM support - the new version is available in Qubes 4.1, but not in 4.0.

**Comment by dylangerdaly** [comment]
Hm, that's interesting because I am running 4.1

Updating via the current-testing repos, meaning I _should_ have the TPM supporting grub2?

I'll confirm what exact version of grub2 I have installed tomorrow, I'm running 4.1 bleeding edge tho

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by marmarek** [comment]
Then take a look at https://www.gnu.org/software/grub/manual/grub/html_node/Measured-Boot.html. I think you don't have TPM driver loaded into grub.

**Comment by dylangerdaly** [comment]
This is indeed a grub2 configuration item, not a Qube's one.

**Comment by dylangerdaly** [comment]
Will Qubes be hardening Grub2 at all? Seems too easy to just hit 'e' and edit CMDLINE without any auth or anything, I understand Qube's whole ethos is 'why bother, we don't trust the hardware', but it's really too easy to edit this stuff.

**Comment by marmarek** [comment]
Kind of: https://github.com/osresearch/safeboot/issues/21 (note this is specifically useful with own keys enrolled into UEFI, not necessary Microsoft's ones).

Otherwise, just setting a passphrase for grub menu (or similar countermeasure) is trivial to bypass so you still don't know if your config wasn't modified.

**Comment by dylangerdaly** [comment]
> trivial to bypass so you still don't know if your config wasn't modified.

Not if I use TPM2-TOTP - https://github.com/tpm2-software/tpm2-totp, the TPM could no longer present my TOTP challenge to me (Because the PCR Policy failed), resulting in me immediately throwing the device into the bin.

**Comment by osresearch** [comment]
If Xen is started with multiboot, then I think grub does the loading of the various modules and this should cover the some of the pieces.  However, will the grub measurements accurately cover all of the files in a UEFI system?  The grub man page says "_Measured boot is currently only supported on EFI platforms_", so I'm a little worried that it isn't possible to correctly measure and validate the user's configuration with grub2.

When `xen.efi` is booted, my understanding is that grub only loads the Xen hypervisor.  Xen then loads the kernel and initrd using the UEFI Boot Services and currently `xen/common/efi/boot.c` does not measure or validate its command line, the `xen.cfg` config file, the intird, the x86 microcode nor the xsm module.  Only the bzimage is validated with the shim protocol (although it isn't apparent to me if it does any measurements?)
