### ISSUE TITLE
Debian Template

### ISSUE THREAD

**Issue by bluesteal** [QubesOS/qubes-issues#6082]
**Qubes OS version**
Qubes release 4.0 (R4.0)

**Affected component(s) or functionality**
qubes-template-debian-10

**Brief summary**
debian-10 template all of a sudden stopped booting; so as per instructions I switched the appVMs based on debian to a backup template and then copied the broken template. After that I removed the original debian template and tried to replace it, but the debian-10 template won't download, only the minimal version of debian is available for download.

**To Reproduce**

1. Break your debian template (make a backup first)
2. Delete the template
3. Attempt updating it via dom0 

**Expected behavior**

The debian-10 template should update 

**Actual behavior**

sudo qubes-dom0-update --enablerepo=qubes-templates-itl qubes-template-debian-10

Returns -> No match for argument qubes-template-debian-10

**Screenshots**

**Additional context**

**Solutions you've tried**

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

**Comment by marmarek** [comment]
See https://www.qubes-os.org/faq/#when-i-try-to-install-a-templatevm-it-says-no-match-is-found

**Comment by bluesteal** [comment]
I tried to diagnose the problem using the log files, but they weren't very helpful. is there a way to change the verbosity of the AppVM logs?

**Comment by bluesteal** [comment]
Thanks for your reply btw :)

How should somebody go about diagnosing a template that will not boot?

Thank you

**Comment by 0spinboson** [comment]
did you uninstall using dnf remove qubes-template-debian-10 ?

**Comment by andrewdavidwong** [comment]
Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this does not appear to be suitable for `qubes-issues`. We ask that you please post this on the [`qubes-users` mailing list or forum](https://www.qubes-os.org/support/) instead. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a brief comment explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.
