### ISSUE TITLE
R4.1 provides-network blocks net traffic on Debian 10

### ISSUE THREAD

**Issue by tasket** [QubesOS/qubes-issues#6088]
**Qubes OS version**

R4.1

**Affected component(s) or functionality**

qubes-template-debian-10 (from testing repo)

**Brief summary**

When using the Debian 10 template for sys-net or sys-vpn, no network traffic is forwarded downstream.

**To Reproduce**

Configure sys-net to use debian-10 template.

**Expected behavior**

VMs connection via sys-net should have net access.

**Actual behavior**

Traffic does not get through.

**Additional context**

This also occurs with a sys-vpn VM. For example, if sys-net uses fedora-30 and sys-vpn uses debian-10, then sys-vpn will be able to establish a link to the VPN provider, but downstream VMs will be blocked.

Networking for non-provides-network appVMs appears functional.

**Solutions you've tried**

Using Fedora for all proxy/net VMs.

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

**Comment by SaswatPadhi** [comment]
The `debian-10-minimal` template from ITL testing repo seems to work fine.

**Comment by tasket** [comment]
Workaround for me was to enable the Qubes buster-testing repo; subsequent update installed new qubes packages and Debian proxyVMs became operational.
