### ISSUE TITLE
Xen panic on installer startup - Qubes 4.0.3

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#6092]
Same problem as firstabor.  Dell Precision 7540 with most recent BIOS.  Read through installation docs to see which BIOS settings to try changing. No luck trying to install 4.03 from usb made with rufus dd.  Following settings have been tested
intel software guard extension set to enabled, disabled, controlled by OS.
secure boot is disabled.
TPM off
TPM 2.0 on
Fastboot minimal
Fastboot thorough
Switchable graphics (nvidia optimus/and power express) enabled and disabled.

All have resulted in attached screenshot when attempting to boot to usb.
![PXL_20200927_160426382](https://user-images.githubusercontent.com/43557511/94370149-36e8a500-00bc-11eb-96f0-5f72baaff2c3.jpg)

And it doesn't ever reboot, have to manually restart.

Not sure if this means anything but the top of the screen says ioapic_old_on and using old ack method.

_Originally posted by @n0101 in https://github.com/QubesOS/qubes-issues/issues/5553#issuecomment-699656562_

**Comment by n0101** [comment]
Is there a way to capture the output before the last screen?

**Comment by gw0** [comment]
I am experiencing the same issue with Quebes OS 4.0.3 on an USB stick (dd, verified checksum) on Dell XPS 15 7590 with latest BIOS, also tried turning a few options on and off. Booting over UEFI initially resulted in Dell Diagnostic to pop-up (probably it detected a crash), but it started booting when I turned off Secure boot.

@n0101 Luckily, the laptop has a 4K screen, so below is the whole booting output. It always crashes with the same stack output. It seems like Xen handles an interrupt incorrectly and jumps to a random memory location?

![IMG_20201006_135806](https://user-images.githubusercontent.com/803603/95200370-92aede80-07de-11eb-8f1e-6105ccc2a3fa.jpg)

**Comment by djt3** [comment]
I have the exact same problem on an ASUS Z490-G with the i5 10600k.

**Comment by DemiMarie** [comment]
Firmware bug?

**Comment by marmarek** [comment]
Yes! And pretty common one. Suffice to say, neither Windows nor Linux use this EFI call because of how common the bug is.
Context: https://lists.archive.carbon60.com/xen/devel/408709
We have it disabled in R4.1, the patch need a backport to R4.0. If you wonder why it isn't an upstream thing, see the thread linked above...

**Comment by andrewdavidwong** [comment]
> Yes! And pretty common one. Suffice to say, neither Windows nor Linux use this EFI call because of how common the bug is.
> Context: https://lists.archive.carbon60.com/xen/devel/408709
> We [have it disabled in Xen in R4.1](https://github.com/QubesOS/qubes-vmm-xen/pull/69), the patch need a backport to R4.0. If you wonder why it isn't an upstream thing, see the thread linked above...

So what's the resolution here? Can anything be done on the Qubes side?

**Comment by DemiMarie** [comment]
[It already has been](https://github.com/QubesOS/qubes-vmm-xen/blob/45f00840969afccb9509b8a5778b5674b326ac5a/patch-xen-disable-efi-gettime.patch)

**Comment by andrewdavidwong** [comment]
If I understand correctly, the only remaining action here is to backport the patch to 4.0, then this issue should be closed.

**Comment by DemiMarie** [comment]
@andrewdavidwong the most recent Xen version already includes it.

**Comment by marmarek** [comment]
Yes, I confirm, indeed it is already backported to R4.0, actually very shortly after Qubes 4.0.3 was released (it is in xen-4.8.5-15, while 4.0.3 has xen-4.8.5-14). So, the problem should be gone in 4.0.4.
