### ISSUE TITLE
Make Qubes package names consistent between Fedora and Debian

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#6094]
**Qubes OS version**

R4.0

**Affected component(s) or functionality**

Package naming

**Brief summary**

The package is called "thunderbird-qubes" for Fedora and "qubes-thunderbird" for Debian, which causes [user confusion](https://qubes-os.discourse.group/t/unable-to-add-qubes-extension-to-thunderbird-in-fedora-minimal/).

**Expected behavior**

Same package follows roughly same naming scheme across different distros, except for changes required by those distros.

**Actual behavior**

Package name is reversed for no apparent reason, somehow inconsistent with the documentation.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

https://www.qubes-os.org/doc/templates/minimal/

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

None found.

**Comment by fepitre** [comment]
Unfortunately, from what I remember, it's not the only one example. As I was about to find a way to get all the packages name (see https://github.com/QubesOS/qubes-builder/pull/123), I will be able to highlight the differences across distro easily and we should make it uniform.

**Comment by unman** [comment]
On Tue, Sep 29, 2020 at 12:31:55AM -0700, Fr??d??ric Pierret wrote:
> Unfortunately, from what I remember, it's not the only one example. As I was about to find a way to get all the packages name (see https://github.com/QubesOS/qubes-builder/pull/123), I will be able to highlight the differences across distro easily and we should make it uniform.
> 

I would favour the "qubes-XXX" versions - it's a consistent approach and
makes the packages easier to find/sort

**Comment by iamahuman** [comment]
How about keeping existing package names and provide aliases for one another, via Provides: or a virtual package?

**Comment by marmarek** [comment]
In case of any rename we'd need migration path like this anyway. But unifying package names make it easier to spot them on the package list too (like `rpm -qa`, `dpkg -l` etc). Aliases won't help you here...

**Comment by marmarek** [comment]
As for actual naming, Fedora has [a policy](https://fedoraproject.org/wiki/Packaging:Naming#Addon_Packages) for that:
> If a package is considered an "addon" package that enhances or adds functionality to an existing Fedora package without being useful on its own, its name SHOULD reflect this fact.

> The new package ("child") SHOULD prepend the "parent" package in its name, in the format: %{parent}-%{child}. 

This means, it should be thunderbird-qubes.

I don't see equivalent policy in Debian, and also I see kind of mix in practice, for example [nautilus](https://packages.debian.org/search?keywords=nautilus) - I see both "rabbitvcs-nautilus" and "nautilus-sendto".

**Comment by unman** [comment]
On Tue, Sep 29, 2020 at 05:35:52AM -0700, Marek Marczykowski-G??recki wrote:
> As for actual naming, Fedora has [a policy](https://fedoraproject.org/wiki/Packaging:Naming#Addon_Packages) for that:
> > If a package is considered an "addon" package that enhances or adds functionality to an existing Fedora package without being useful on its own, its name SHOULD reflect this fact.
> 
> > The new package ("child") SHOULD prepend the "parent" package in its name, in the format: %{parent}-%{child}. 
> 
> This means, it should be thunderbird-qubes.
> 
> I don't see equivalent policy in Debian, and also I see kind of mix in practice, for example [nautilus](https://packages.debian.org/search?keywords=nautilus) - I see both "rabbitvcs-nautilus" and "nautilus-sendto". 
> 

This is unfortunate, because imo it makes the packages more difficult to
find.  But if there's a policy, I suppose we should abide by it. (I don't
believe there is a corresponding guide in Debian and as you note, in
practice, there is a variety of use.)

**Comment by andrewdavidwong** [comment]
Generalized based on https://github.com/QubesOS/qubes-issues/issues/7033#issuecomment-959190651. Not sure if this should be tied to a specific release or not. Provisionally assigning to `non-release`.

**Comment by unman** [comment]
I believe that all packages are now consistent in naming between Debian and Fedora.
This can now be closed.
@andrewdavidwong

**Comment by andrewdavidwong** [comment]
Closing as resolved. If anyone believes this issue is not yet resolved, or if anyone is still affected by this issue, please leave a comment, and we'll be happy to reopen it. Thank you.
