### ISSUE TITLE
debian-11 update broken

### ISSUE THREAD

**Issue by GWeck** [QubesOS/qubes-issues#6095]
**Qubes OS version**
R4.0.3 fully updated

**Affected component(s) or functionality**
debian-11 template

**Brief summary**
The VM shows the sign that updates are available. When starting the update, the corresponding packets are downloaded and installed. As far as I can see, the Qubes packages seem to get removed.  The template then is broken.

**To Reproduce**
Update the debian-11 template via the update widget.

**Expected behavior**
The template is update and stiil functional.

**Actual behavior**
According to the Qube manager, the VM then seems to be stiil running but is unresponsive. It can be shut down from the Qube manager, but when started again, it stays in the "starting" stage for 60 seconds and then is killed with the message `Cannot connect to the qrexec agent...`.

**Additional context**
Here is the file `/var/log/xen/console/guest-debian-11.log`.
[log.zip](https://github.com/QubesOS/qubes-issues/files/5300433/log.zip)

**Solutions you've tried**
The template can be manually updated via `apt-get update && apt-get upgrade`, but the update marker still stays on. If the update then is started again, a lengthy update starts and breaks the template, like above.

**Comment by fepitre** [comment]
Sorry but the version you are referring is not even finished/released yet.

**Comment by andrewdavidwong** [comment]
> Sorry but the version you are referring is not even finished/released yet.

I'm guessing that this should be closed as `not an issue` since this template is not expected to be non-broken right now.

CC: @unman

**Comment by juodumas** [comment]
Same happened to me. Looks like debian's python2 removal is in progress in bullseye/testing and things are breaking. @marmarek mentioned `xen-utils-common` as a possible culprit in https://github.com/QubesOS/qubes-issues/issues/6061#issuecomment-694524323 and I guess this issue will be resolved when Debian fixes https://tracker.debian.org/pkg/xen for testing (right now it says `source package has 1 unsatisfiable build dependency`) and Qubes imports the changes.
