### ISSUE TITLE
Pane is dead

### ISSUE THREAD

**Issue by ThatAimDude** [QubesOS/qubes-issues#6096]
![20200929_201906](https://user-images.githubusercontent.com/46623193/94603509-a4502d80-0296-11eb-9f01-869e06225c49.jpg)

Hi so im trying to install Qubes and i had several problems. Right now when im on the installer i press "install Qubes os ..." and a bunch of code runs and then it says "Pane is Dead". Im not sure what to do and i dont know what it means.

PC Specs

-Ryzen 5 2600x

- RTX 2070

- 8 GB RAM

- Motherboard - asus prime a320m-k

**Comment by andrewdavidwong** [comment]
Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this does not appear to be suitable for `qubes-issues`. We ask that you please post this on the [`qubes-users` mailing list or forum](https://www.qubes-os.org/support/) instead. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a brief comment explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.
