### ISSUE TITLE
"Start" app entry is confusing and unnecessary

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#6099]
**Qubes OS version**

`R4.0`

**Affected component(s) or functionality**

"Start" app entry in shortcut list

**Brief summary**

The "Start" entry simply does `qvm-start --quiet <vm_name>`. This is not very useful. It's also misleading, because it's in the app list even though it's not an app.

**To Reproduce**

1. Go to add/remove app shortcuts for a VM.
2. See the "Start" entry.
3. Think that it's an app because it's in the app list.
4. Try it out.
5. Be confused when nothing seems to happen, because actually all it does is `qvm-start --quiet <vm_name>`, which duplicates existing functionality.

**Expected behavior**

Only actual apps are in the app list.

**Actual behavior**

Non-useful non-app is in the app list.

**Additional context**

This came up in: https://qubes-os.discourse.group/t/debian-start-application-doesnt-do-anything/676/

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

N/A

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

None found.

**Comment by marmarta** [comment]
Wait, it's still there? It's not on my (...highly experimental and oft-randomly updated with packages from 4.1 that may or may not work) instance of 4.0.

**Comment by marmarta** [comment]
Hmmm, maybe we should rename it to "Start qube"? so that if someone wants it (and there were some tickets from people who wanted it, see discussion in https://github.com/QubesOS/qubes-issues/issues/6007 ) they can add it.

**Comment by andrewdavidwong** [comment]
> Wait, it's still there? It's not on my (...highly experimental and oft-randomly updated with packages from 4.1 that may or may not work) instance of 4.0.

It's still there on my 4.0 installation.

> Hmmm, maybe we should rename it to "Start qube"? so that if someone wants it (and there were some tickets from people who wanted it, see discussion in #6007 ) they can add it.

I don't know what the best solution is, but that sounds reasonable to me.

Some other folks in the [forum thread](https://qubes-os.discourse.group/t/debian-start-application-doesnt-do-anything/676/) also want it and offered similar suggestions.
