### ISSUE TITLE
Help me TEST this survey of Qubes users!

### ISSUE THREAD

**Issue by ninavizz** [QubesOS/qubes-issues#6100]
Hello! I have been working closely with @marmarta on a survey that we hope to see properly published, sometime in the next week or so. 

Before we vest energy into its finishing touches, however, I need to get a sense of **_how long it takes folks to get through this_**; as it is. My ask of others with this issue is to please this a spin—**with a timer on**—and responding to questions with real thought, as if you're a real respondent. Yep, it's totally anonymous, and self-hosted on a server Marek runs. 

https://survey.qubes-os.org/index.php?r=survey/index&sid=137242&lang=en

I also assume that everyone here actually uses Qubes... so for getting a solid measure, I'll need some folks to respond to the 3rd question, that they are either not a Qubes user, or anticipate becoming one soon; then roleplay those answers. :)

Please then reply here, to let me know how long it took you, and what the key path forks you chose, were (yes/no to being a current Qubes user, and yes/no to participating in user research.

Feedback on the survey itself would _also_ be welcome and wonderful; my only ask for that, is that such comments go in the parent Issue: https://github.com/QubesOS/qubes-issues/issues/5732

All data collected in this will be purged, probably within a few days. Thx!!

**Comment by fepitre** [comment]
@ninavizz the links to previous issue don't work. I think you can write the full link instead.

**Comment by zellchristensen** [comment]
A little under 10 minutes.  I chose yes to being a qubes user and yes to participating in user research.

![2020-10-03_02-55-37](https://user-images.githubusercontent.com/38737447/94986444-7bdd6300-0524-11eb-802d-8479024d69ba.png)

**Comment by Yethal** [comment]
"Earlier in the survey, you said that you are not currently a regular user of a Linux OS. Had you previously been a regular Linux user?"
That question popped up despite the fact that I ranked Linux first on the list of operating systems previously

**Comment by andrewdavidwong** [comment]
@ninavizz: FYI, this sort of thing really belongs on the mailing lists rather than qubes-issues, but I'll leave it open since it's already in use.

**Comment by ninavizz** [comment]
I'm only needing a few people to test this @andrewdavidwong; and the request is purely to test.
I don't want to make multiple survey requests in the mailing lists. The ONLY  one that should go there, is for the final survey.

Only one person has given me their time. That's it. I need more people to take the survey in a testing capacity, and post their times, here. Somehow my text above did not communicate that clearly enough, as my need.  

> @ninavizz: FYI, this sort of thing really belongs on the mailing lists and/or forum rather than qubes-issues, but I'll leave it open since it's already in use.

**Comment by ninavizz** [comment]
@andrewdavidwong Also, I want to delete this "Task" entirely, once it's been completed. Getting folks to take surveys is hard, and the responses are potentially less accurate for some questions, the second time a user takes it. FYI. Sorry, I'd hoped to get to this step mid-week when FPF folks could help me with this, but it being the weekend I needed to post here. I won't make a habit of this, I promise! :D

**Comment by andrewdavidwong** [comment]
No worries, not a huge deal.

> Also, I want to delete this "Task" entirely, once it's been completed.

I don't think GitHub allows us to delete issues, so closing when it's done is probably all we can do.

> Getting folks to take surveys is hard

I'll take the survey now. :slightly_smiling_face:

**Comment by edozzo** [comment]
10 min 38 sec

**Comment by andrewdavidwong** [comment]
6.5 mins. No to being a current Qubes user, and no to participating in user research.

**Comment by ninavizz** [comment]
Ok! I made some tweaky fixes based on prior comments (as did @marmarta), added the QA Director's image to the confirmation page, and made general Question Codes visible to facilitate in QA. It's super helpful getting these times from folks; pls keep 'em coming, as well as the feedback on questions/logic stuff. Thx, all!

**Comment by zpc0** [comment]
10m 03s
Q3: Not just yet, but soon
user research: no

**Comment by ninavizz** [comment]
Shut it down for a bit this eve to make some tweeks, its back live again. Gotta work on that first question, tomorrow. THANK YOU to everyone who's taken the survey and shared times/feedback/etc!!

**Comment by ninavizz** [comment]
Closing, as survey was sufficiently tested, with the decision made to cut its length to reduce user time to complete. TY one and all who contributed to this issue, it was very helpful!
