### ISSUE TITLE
"Curl error (23): Failed writing received data to disk/application" When downloading Fedora 32 Template

### ISSUE THREAD

**Issue by baldover** [QubesOS/qubes-issues#6101]
**Qubes OS version**

**Affected component(s) or functionality**

**Brief summary**

**To Reproduce**

1. Attempt to do 'sudo qubes-dom0-update qubes-template-fedora-32'
2. See the curl error.

**Expected behavior**

It downloads and installs

**Actual behavior**

It errors out before completing the download

**Logs**

> sudo qubes-dom0-update qubes-template-fedora-32
> Using sys-firewall as UpdateVM to download updates for Dom0; this may take some time...
> Fedora 25 - x86_64 - Updates                    1.6 MB/s |  24 MB     00:15    
> Fedora 25 - x86_64                              2.0 MB/s |  50 MB     00:25    
> Qubes Dom0 Repository (updates)                 515 kB/s |  19 MB     00:38    
> determining the fastest mirror (15 hosts).. done.--  B/s |   0  B     --:-- ETA
> Qubes Templates repository                      4.5 kB/s |  17 kB     00:03    
> Dependencies resolved.

> ================================================================================
> Package                  Arch   Version              Repository           Size

================================================================================

> Installing:
>  qubes-template-fedora-32 noarch 4.0.1-202006110439   qubes-templates-itl 1.4 G
> 
> Transaction Summary
================================================================================
> Install  1 Package
> 
> Total download size: 1.4 G
> Installed size: 4.3 G
> DNF will only download packages for the transaction.
> Downloading Packages:
> done. Templates repo     [               ===  ] ---  B/s |   0  B     --:-- ETA
> [MIRROR] qubes-template-fedora-32-4.0.1-202006110439.noarch.rpm: Curl error (23): Failed writing received data to disk/application for https://mirrors.ulayer.net/qubes/repo/yum/r4.0/templates-itl/rpm/qubes-template-fedora-32-4.0.1-202006110439.noarch.rpm [Failed writing body (4132 != 16366)]
> [FAILED] qubes-template-fedora-32-4.0.1-202006110439.noarch.rpm: Curl error (23): Failed writing received data to disk/application for https://mirrors.ulayer.net/qubes/repo/yum/r4.0/templates-itl/rpm/qubes-template-fedora-32-4.0.1-202006110439.noarch.rpm [Failed writing body (4132 != 16366)]
> 
> The downloaded packages were saved in cache until the next successful transaction.
> You can remove cached packages by executing 'dnf clean packages'.
> Error: Error downloading packages:
>   Curl error (23): Failed writing received data to disk/application for https://mirrors.ulayer.net/qubes/repo/yum/r4.0/templates-itl/rpm/qubes-template-fedora-32-4.0.1-202006110439.noarch.rpm [Failed writing body (4132 != 16366)]
> 

**Additional context**

Fedora 32 Minimal downloaded and installed just fine.

**Solutions you've tried**

I deleted some barely used VMs to free up some space.
I attempted to download Fedora 32 Template many times already and even used a VPN.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

Issue #3693 seems related but it exclusively happens during 'sudo qubes-dom0-update qubes-template-fedora-32'. 'qubes-dom0-update' works just fine on my machine

**Comment by fepitre** [comment]
It's a mirror issue not Qubes issue. For temporary workaround comment `metalink=` and uncomment `baseurl=`.

**Comment by icequbes1** [comment]
Assuming it's not mirror issues,

> I deleted some barely used VMs to free up some space.
> I attempted to download Fedora 32 Template many times already and even used a VPN.

You might have disk space issues on the physical disk (volume group) where removing unused VMs would help.

However, as you are doing a `qubes-dom0-update` command, you also need to worry about the disk space _within_ the qube that retrieves your updates, which looks like sys-firewall. If you have downloaded a lot of updates, sys-firewall may have run out of disk space on its root file system.

If you start a terminal in sys-firewall, try the following two commands:

```
df -h /var/lib/qubes
du -h /var/lib/qubes/dom0-updates/packages
```

If the `df` output shows low space available and the `du` output shows a significant amount of space being used, removing the `/var/lib/qubes/dom0-updates/packages` directory should resolve the disk space issue. Or simply restart sys-firewall.

**Comment by andrewdavidwong** [comment]
> It's a mirror issue not Qubes issue. For temporary workaround comment `metalink=` and uncomment `baseurl=`.

Closing as "not an issue." (If it were a bug, it would be an upstream bug, but AFAIK such temporary mirror issues are not even considered bugs.) If you believe this is a mistake, please leave a comment, and we'll be happy to take another look. Thank you.

**Comment by baldover** [comment]
> It's a mirror issue not Qubes issue. For temporary workaround comment `metalink=` and uncomment `baseurl=`.

Hi thanks. Where exactly do I put it?

**Comment by icequbes1** [comment]
> Hi thanks. Where exactly do I put it?

`/etc/yum.repos.d/qubes-templates.repo`.

We can continue this support over at the [forum](https://qubes-os.discourse.group) or the qubes-users mailing list.
