### ISSUE TITLE
Impossible to use 'pillar={"x":"y"}' when targeting something else but dom0

### ISSUE THREAD

**Issue by bXV0ZQ** [QubesOS/qubes-issues#6106]
**Qubes OS version**
Qubes release 4.0 (R4.0)

**Affected component(s) or functionality**
Salt Management stack

**Brief summary**
Sending pillar data will result in a bad interpretation of the entire entry `pillar="{\"foo\":\"bar\"}` as a unique word on the target.
Salt will so consider it as the environment and fail in executing the expected state.

**To Reproduce**

All steps must be executed in `dom0`.

1. Create a state file as follow at `/srv/salt/test-pillar.sls`:
```yaml
is-pillar-there:
  test.check_pillar:
    - present:
        - foo
```
2. Execute the state file on the vm you want without pillar provided:
```bash
sudo qubesctl --skip-dom0 --target <anyvm> state.sls test-pillar
```
3. Check execution is in error with similar message `<anyvm>: ERROR (exit code 20, details in /var/log/qubes/mgmt-<anyvm>.log` and following details in the log file:
```
calling 'state.sls test-pillar'...
output: <anyvm>:
output: ----------
output: ID: is-pillar-there
output: Function: test.check_pillar
output: Result: False
output: Comment: Pillar key "foo" is missing.
...
output: Summary for <anyvm>:
output: ----------
output: Succeeded: 0
output: Failed: 1
output: ----------
output: Total states run: 1
...
exit code: 20
```
4. Now execute the state file on a vm with pillar provided:
```bash
sudo qubesctl --skip-dom0 --target <anyvm> state.sls test-pillar pillar="{\"foo\":\"bar\"}"
```

**Expected behavior**
```
calling 'state.sls test-pillar pillar='{"foo":"bar"}''...
output: <anyvm>:
output: ----------
output: ID: is-pillar-there
output: Function: test.check_pillar
output: Result: True
output: Comment: 
...
output: Summary for <anyvm>:
output: ----------
output: Succeeded: 1
output: Failed: 0
output: ----------
output: Total states run: 1
...
exit code: 0
```

**Actual behavior**
Please notice that the quote in the first line (`calling`) moved from after `pillar=` to before `pillar`, preventing the interpretation of the '=' sign by Salt.
```
calling 'state.sls test-pillar 'pillar={"foo":"bar"}''...
output: <anyvm>:
output:     - No matching salt environment for environment 'pillar={"foo":"bar"}' found
output:     - No matching sls found for test-pillar in env 'pillar={"foo":"bar"}'
exit code: 0
```

**Additional context**
It works as expected when executing the state with pillar provided on dom0 with:
```bash
sudo qubesctl state.sls test-pillar pillar="{\"foo\"=\"bar\"}"
```
Result is then:
```
local
----------
ID: is-pillar-there
Function: test.check_pillar
Result: True
Comment: 
...
Summary for local:
----------
Succeeded: 1
Failed: 0
----------
Total states run: 1
...
```

**Solutions you've tried**
I was not able to find any work-around to this issue.
After digging a bit within the management stack code, the issue could come from the following:
```python
exit_code, result = runner.salt_call(
    ' '.join([pipes.quote(word) for word in command]),
    return_output=show_output)
```
at https://github.com/QubesOS/qubes-mgmt-salt/blob/e5759d1f6d724c86ae5b7f25a1914bd86cd6e701/qubessalt/__init__.py#L225

`pipes.quote` considers `pillar={"foo":"bar"}` as a whole and protect the entire block.
As `pipes.quote` protects only when necessary, it worked until then when there no complex data to provide as argument.
Unfortunately, pillar requires a dictionary as argument and the '{' trigger the protection by `pipes.quote`.

Adding a split and join on the '=' sign to `pipes.quote` as two different word would do the trick but would require to only split on the first '=' sign found to make sure it doesn't break when there is one more '=' sign in the right operand of the equality.

In a worst case scenario, it would require to parse all the commands as Salt would do to make sure they are propagated the right way.

**Comment by marmarek** [comment]
Thanks for a very detailed bug report and an analysis. Quotes are added only to get things properly to salt-ssh call inside mgmt-dispvm-* (qubes.SaltLinuxVM service), they should not be passed down to the salt itself. This looks like some mismatch between pipe.quotes and qubes.SaltLinuxVM, I'll see how to fix it.

**Comment by bXV0ZQ** [comment]
Many thanks for your quick reply and all the great job you all do at QubesOS.

**Comment by lkubb** [comment]
This issue is still present in 4.2rc4 and caused by this line:

https://github.com/QubesOS/qubes-mgmt-salt/blob/780e0ef09c6c83cdd301a32d256bc6263c573596/qubes.SaltLinuxVM#L54

The rendered command string will simply be split on each whitespace without regard to usual shell tokenization rules.

This means, in addition, nothing containing whitespace can be passed, so this fails as well:

```console
$ qubesctl --skip-dom0 --show-output --target foobar test.echo 'hi there'
foobar:
      ----------
      retcode:
          1
      stderr:
          Passed invalid arguments: echo() takes 1 positional argument but 2 were given.

          Usage:
      stdout:
          Return a string - used for testing the connection

              CLI Example:

              .. code-block:: bash

                  salt '*' test.echo 'foo bar baz quo qux'
```

A minimal reproduction:

`slvm`
```bash
#!/usr/bin/env bash

read target_vm
read salt_command

./print_argv -w "$target_vm" $salt_command
```

`print_argv`
```python
#!/usr/bin/env python3

import sys
print(sys.argv)
```

The quoted keyword argument still contains quotes, since they do not carry special meaning:
```console
$ ./slvm
foobar
state.sls repro 'pillar={"foo":"bar"}'
['./print_argv', '-w', 'foobar', 'state.sls', 'repro', '\'pillar={"foo":"bar"}\'']
```

Worse, with whitespace, we get multiple arguments, the first and last containing the original quotes:
```console
$ ./slvm
foobar
test.echo 'hi there foobar'
['./print_argv', '-w', 'foobar', 'test.echo', "'hi", 'there', "foobar'"]
```

Possible fix:

`slvm`
```bash
#!/usr/bin/env bash

read target_vm
read salt_command

readarray -t -d '' salt_args < <(xargs printf '%s\0' <<<"$salt_command")
./print_argv -w "$target_vm" "${salt_args[@]}"
```

```console
$ ./slvm
foobar
state.sls repro 'pillar={"foo":"bar"}'
['./print_argv', '-w', 'foobar', 'state.sls', 'repro', 'pillar={"foo":"bar"}']
```

```console
$ ./slvm
foobar
test.echo 'hi there foobar'
['./print_argv', '-w', 'foobar', 'test.echo', 'hi there foobar']
```

I have verified this working with a patched template for `default-mgmt-dvm` and opened a PR, hope that's fine.
