### ISSUE TITLE
Sometimes have to confirm yes twice in a row for dom0 updates

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#6107]
**Qubes OS version**

`R4.0`

**Affected component(s) or functionality**

qubes-dom0-update

**Brief summary**

When updating dom0, you sometimes have to confirm yes twice in a row. This seems like a possible attack, if the attacker is somehow able to hide what the first confirmation is for (e.g., importing a new key), and make it look like some glitch.

**To Reproduce**

1. `sudo qubes-dom0-update`
2. 
```
Upgrade  2 Packages

Total size: 79 k
Is this ok [y/N]: y
Is this ok [y/N]: y
Downloading Packages:
```

**Expected behavior**

Only one confirmation prompt

**Actual behavior**

Two prompts for ostensibly the same action

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

N/A

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

None found.

**Comment by marmarek** [comment]
dnf is quite strict about what it considers an answer - any key pressed earlier is also retrieved by this prompt and for example if you press 'a' earlier, then it retrieve 'ay' and asks again. It indeed may be confusing, as it doesn't tell why it asks again.
Anyway, it all should be safe - qubes-dom0-update is designed the way it reject any suspicious packages early - if it gets to dnf, then it is already verified. There is no way for an UpdateVM to get a package to dnf that isn't properly signed, or send new repo file, or new key or other similar actions.

**Comment by andrewdavidwong** [comment]
> dnf is quite strict about what it considers an answer - any key pressed earlier is also retrieved by this prompt and for example if you press 'a' earlier, then it retrieve 'ay' and asks again. It indeed may be confusing, as it doesn't tell why it asks again.
Anyway, it all should be safe - qubes-dom0-update is designed the way it reject any suspicious packages early - if it gets to dnf, then it is already verified. There is no way for an UpdateVM to get a package to dnf that isn't properly signed, or send new repo file, or new key or other similar actions.

Thanks, Marek. That's reassuring and good to understand. In that case, it probably was me accidentally pressing another key. (I do that a lot...)

In any case, it sounds like this behavior is purely from upstream `dnf`, and since there is no security concern on the Qubes side, I'm closing this as `not our bug`.

**Comment by andrewdavidwong** [comment]
Now that I think about it, this behavior is probably common to most command-line tools (I think I've also noticed it when using git, for example), so probably wouldn't even be considered an upstream bug. I suppose it's just particularly noticeable (to me) when using `dnf` because of the y/n prompts.
