### ISSUE TITLE
Allow Cascading Shutdowns from Qube Manager

### ISSUE THREAD

**Issue by zellchristensen** [QubesOS/qubes-issues#6109]
**The problem you're addressing (if any)**
Currently, if a user wants to shutdown a "root" netVM, all connected "child" VMs must be shutdown first.  Doing this manually can be time consuming and tedious.

**Describe the solution you'd like**
An extra prompt or button to confirm cascade shutdown of all "child" VMs instead of the current error saying there are other VMs connected.

**Where is the value to a user, and who might that user be?**
Saves the user time so they don't have to individually shut down, in order, every connected VM, waiting in between for each one to shut down.
Increases usability by mimicing the behavior of cascading startups when a user starts a "child" VM, just in reverse.

**Describe alternatives you've considered**
Make some type of global setting where the user can choose the behavior they wish.
For example:
Never cascade shutdowns (same behavior as current)
Always cascade shutdowns (automatically shuts down all child VMs without warnings)
Prompt for cascade shutdown (makes the user confirm in an extra step when attempting so they can double check the running VMs)

OR

Allow the user to restart/shutdown a connected Qube independent of any other VM, maybe with an extra prompt/warning.

**Additional context**
Since it's possible to change netVMs in the settings while a Qube is running, being able to restart or shutdown a NetVM with connected Qubes doesn't seem like much of an issue.
It's also possible to "fudge" the cascade startups by starting a "child" vm while the parent netVM is already shutting down to get the desired effect but requires the user to have to time it just right and isn't consistent.

**Comment by sptankard** [comment]
I think this option is probably simpler/easier to implement as well as more useful:
> Allow the user to restart/shutdown a connected Qube independent of any other VM, maybe with an extra prompt/warning.

There's two main use cases where i have a couple workarounds currently:
1. Shutting down the computer: dom0 terminal -> `qvm-shutdown --all --exclude=sys-usb` (repeat this command as many times as needed to complete the cascade)
2. Issues with internet connection, need to reboot sys-net without rebooting everything else: open terminal in sys-net -> `poweroff`; open terminal in dom0 -> `qvm-start sys-net`

With the override option, one could accomplish (2) easily and could also accomplish (1) by shutting down all VMs one by one from the GUI. Not sure what use case an *actual* cascade feature would apply to.

**Comment by andrewdavidwong** [comment]
> 1. Shutting down the computer: dom0 terminal -> `qvm-shutdown --all --exclude=sys-usb` (repeat this command as many times as needed to complete the cascade)

This is not necessary. You can just do `qvm-shutdown --wait --all` once, and all VMs will shut down in the necessary order.

> 2. Issues with internet connection, need to reboot sys-net without rebooting everything else: open terminal in sys-net -> `poweroff`; open terminal in dom0 -> `qvm-start sys-net`

Another option is simply to change the NetVM of `sys-firewall` to `none`, reboot `sys-net`, then change it back again.
