### ISSUE TITLE
sys-whonix does not auto start on initial first boot

### ISSUE THREAD

**Issue by zellchristensen** [QubesOS/qubes-issues#6110]
**Qubes OS version**
R4.0.3

**Affected component(s) or functionality**
Qube settings/manager

**Brief summary**
After an initial clean install of Qubes, on the first boot, three base VMs are started automatically, sys-usb, sys-net, and sys-firewall.  Only when the user restarts for the first time does sys-whonix auto start.

**To Reproduce**
Install Qubes with default settings in the installer. (dom0 and template updates through Whonix is NOT selected)

**Expected behavior**
All default VMs that have the setting "Start qube automatically on boot" would be started on the initial boot.

**Actual behavior**
Only three of the Qubes with the auto start setting are started on initial boot.  On restart, the original 3 plus sys-whonix auto start.

**Additional context**
I like to disable the automatic starting of most qubes.
When I reinstall Qubes, I always forget to uncheck the auto start setting for sys-whonix since it's not running at initial boot.
On the next restart of Qubes, sys-whonix auto starts, which causes a cascade startup of its netVMs making me think I forgot to uncheck those too.

**Comment by DemiMarie** [comment]
> What does the label `C: Whonix` express? Whonix affected in some way, yes, ok.

@andrewdavidwong what does that label mean?

**Comment by andrewdavidwong** [comment]
> > What does the label `C: Whonix` express? Whonix affected in some way, yes, ok.
> 
> 
> 
> @andrewdavidwong what does that label mean?

It means that the affected component (or one of the affected components) is Whonix. I'm not a Whonix dev, so when I apply this label, it is merely a first-pass, best-effort, provisional, initial triage organization attempt. I rely on you,  the devs (both Whonix and non-Whonix), to inform the accurate updating of these labels, as you all  are the only ones with the requisite expertise to make authoritative technical diagnoses (not me, not users). I welcome any feedback, guidance, or advice you may have about how the issue tracker can serve you better. Ultimately, it is a tool to support your work, and my aim is to maintain it for that primary purpose.
