### ISSUE TITLE
'@anyvm dom0 ask default_target=dom0' policy doesn't work

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#6112]
**Qubes OS version**

R4.1

**Affected component(s) or functionality**

core-qrexec

**Brief summary**

Here is what "ask" is now showing in the log X3:
```
Oct 03 10:56:06 dom0 qrexec-policy-daemon[2296]: warning: !compat-4.0
directive in file /etc/qubes/policy.d/35-compat.policy line 16 is transitional
and will be deprecated
Oct 03 10:56:06 dom0 qrexec-policy-daemon[2296]: Task exception was never
retrieved
Oct 03 10:56:06 dom0 qrexec-policy-daemon[2296]: future: <Task finished
name='Task-201' coro=<handle_client_connection() done, defined at
/usr/lib/python3.8/site-packages/qrexec/tools/qrexec
_policy_daemon.py:50> exception=AssertionError()>
Oct 03 10:56:06 dom0 qrexec-policy-daemon[2296]: Traceback (most recent call
last):
Oct 03 10:56:06 dom0 qrexec-policy-daemon[2296]:   File
"/usr/lib/python3.8/site-packages/qrexec/tools/qrexec_policy_daemon.py", line
93, in handle_client_connection
Oct 03 10:56:06 dom0 qrexec-policy-daemon[2296]:     result = await
handle_request(**args, log=log,
Oct 03 10:56:06 dom0 qrexec-policy-daemon[2296]:   File
"/usr/lib/python3.8/site-packages/qrexec/tools/qrexec_policy_exec.py", line
272, in handle_request
Oct 03 10:56:06 dom0 qrexec-policy-daemon[2296]:     resolution =
policy.evaluate(request)
Oct 03 10:56:06 dom0 qrexec-policy-daemon[2296]:   File
"/usr/lib/python3.8/site-packages/qrexec/policy/parser.py", line 1275, in
evaluate
Oct 03 10:56:06 dom0 qrexec-policy-daemon[2296]:     return
rule.action.evaluate(request)
Oct 03 10:56:06 dom0 qrexec-policy-daemon[2296]:   File
"/usr/lib/python3.8/site-packages/qrexec/policy/parser.py", line 897, in
evaluate
Oct 03 10:56:06 dom0 qrexec-policy-daemon[2296]:     return
request.ask_resolution_type(self.rule, request,
Oct 03 10:56:06 dom0 qrexec-policy-daemon[2296]:   File
"/usr/lib/python3.8/site-packages/qrexec/policy/parser.py", line 613, in
__init__
Oct 03 10:56:06 dom0 qrexec-policy-daemon[2296]:     assert default_target is
None or default_target in targets_for_ask
Oct 03 10:56:06 dom0 qrexec-policy-daemon[2296]: AssertionError
```

Reported by @tasket in https://groups.google.com/d/msgid/qubes-devel/758d0bed-27ac-8fbd-bf34-b2a3c091411b%40posteo.net

**Comment by tasket** [comment]
Its still failing when I use `ask` in the qubes.VMAuth policy. This is after updating to 4.1.9-1. I also changed all references of 'dom0' to '@adminvm' to no avail.

Log:
```
Oct 11 21:32:43 dom0 qrexec-policy-daemon[2321]: qrexec: qubes.VMAuth+: d10-badsudo -> @adminvm: allowed to dom0
Oct 11 21:32:43 dom0 qrexec-policy-daemon[8666]: bash: DEFAULT:QUBESRPC: command not found
```

**Comment by tasket** [comment]
BTW, I also manually applied the change shown in v4.1.10 'parser.py', but it still doesn't work.

**Comment by tasket** [comment]
Based on the error `bash` is reporting, I think the error may be in how the 'cmd' variable is assigned around line 528 in parser.py. At least, it doesn't look like a normal bash command to me. :)

**Comment by marmarek** [comment]
You need to restart qubes-qrexec-policy-daemon service after applying the change if you do that manually. But then restarting the service will result in bad things - #6120

**Comment by tasket** [comment]
BTW, I am getting two prompts instead of one. They are both "qubes.InputKeyboard", and `qvm-device usb ls` shows only the one keyboard device.

**Comment by marmarek** [comment]
> BTW, I am getting two prompts instead of one. They are both "qubes.InputKeyboard", and `qvm-device usb ls` shows only the one keyboard device.

Can you check if that aren't really two separate calls? Compare journalctl in sys-usb (look for `Qubes input proxy sender` service startups) with journalctl in dom0 (qrexec lines).
