### ISSUE TITLE
Emergency Backup Recovery without Qubes (v4): 100+GB qubes consistently fail to untar

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#6113]
_This was originally [posted in the Qubes Community Forum](https://qubes-os.discourse.group/t/emergency-backup-recovery-without-qubes-v4-fails-to-untar-100-gb-qubes-consistently/977) by user **qufo**._

**Qubes OS version**

`R4.0`

**Affected component(s) or functionality**

Emergency backup restore (v4)

**Brief summary**

100+GB qubes consistently fail to untar

**To Reproduce**

I did a couple of disaster recovery simulations. Result is rather devastating.

Procedure:

1. Install Qubes-OS 4.0.3

2. Create Qubes with real data (small and big). Mine are from under a gigabyte up to over 130GB, including a standalone Qubes-Builder Qube.

3. Work with it a week and do daily backups. In my case around 250GB, if all Qubes are selected.
4. Attach the backup medium (in my case a brand new 4TB USB3 disk).

5. Follow the documentation at Emergency Backup Recovery without Qubes (v4). BTW: I scripted step 6 to 8. I was to lazy (and disappointed) to write a full script.

6. The biggest Qube (~130GB) fails consistently to untar:

       tar: Unexpected EOF in archive
       tar: Unexpected EOF in archive
       tar: Error is not recoverable: exiting now

7. Delete private.img, and try again. In hope that it was just a hiccup, but fails too.

8. In Qubes-OS backup only the Qube in question, and try again to restore. Same result.

9. Since all of the above takes ages, I give up and rsync my data out of the live Qube in question. That will run probably until late in the night.

**Additional context**

Note:
I started on Monday; today is Wednesday and I still haven’t recovered all the data. I used to work in enterprise disaster / recovery. If I would have needed more than one day to recover a storage system, I probably would have been fired the same day.

Conclusion:
The Qubes-OS backup is unreliable and in case of disaster by far to tedious, hence rather useless for production.

Below the script I used. Just to prove that I followed the documented procedure.

[unpack-vm-image.cpiogz ](https://qubes-os.discourse.group/uploads/short-url/r3ecVoMvCjkAUQ47vWZYrNIMgcc.cpiogz)

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

http://qubesosfasa4zl44o4tws22di6kepyzfeqv3tg4e3ztknltfxqrymdad.onion/doc/backup-emergency-restore-v4/

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

None

**Comment by qufo418** [comment]
I think the the amount of chunks are the problem. In this case qubes-backup created over 1100 chunks. In my experience splitting archives leads often to such kind of problems. I'm not a Python programmer, but what about creating an continuous stream? I played around with this:
Create:
`find [folder or image] | cpio -o | gzip -c | scrypt enc - [archive]`

Restore:
`cat [archive] | scrypt dec - | gzip -d | cpio -i`

No data would stored in dom0, hence no need for chunks. Maybe such a stream could work. But as I said I don't know the code good enough to be sure. Currently I've no Qubes installation to test.
