### ISSUE TITLE
[UxR] Create "Seeder" survey for users who opt-in to further user research

### ISSUE THREAD

**Issue by ninavizz** [QubesOS/qubes-issues#6116]
## Problem
When folks respond to the primary Qubes User Survey created in #5732 they will need to be followed-up with, and sent an additional survey to collect some basic information to inform the team on next steps. [User Persona](https://usable.tools/personas/) traits and scheduling needs, are among the information not collected in the first survey that has been published.

## Task
Questions were created for an early draft of the Survey, that were later removed from the survey created in #5732 to cut its total length. Those questions are necessary to prioritize participant outreach; and should be moved into their own, short survey. Nina can do this as part of ongoing user research efforts.

**Comment by andrewdavidwong** [comment]
Is this complete?

**Comment by ninavizz** [comment]
Yup! Closing...
