### ISSUE TITLE
[UxR] Survey Analysis + Findings

### ISSUE THREAD

**Issue by ninavizz** [QubesOS/qubes-issues#6117]
## Context
Per #5732 our first ever survey of Qubes users was created and launched. Huzzah!

## Need
- [ ] Follow-up with UxR interested respondents by contacting them with a Seeder survey
  - [ ] After the survey has run for 7 days
  - [ ] After the survey has run for 14 days
  - [ ] After the survey has run for 21 days
  - [ ] After the survey has run for 30 days
- [ ] After the survey has run for 30 days, @ninavizz export and thoroughly analyze all user data to shape findings
- [ ] Create lifecycle plan for @marmarta to continue the above, every 60-90 days

**Comment by andrewdavidwong** [comment]
The timeline of events laid out above has long since passed. It appears that this issue is complete. Closing.
