### ISSUE TITLE
Add Ability to Close Qube Shutdown Popup Window

### ISSUE THREAD

**Issue by zellchristensen** [QubesOS/qubes-issues#6123]
**The problem you're addressing (if any)**
If a user requests a shutdown of a Qube and the Qube fails to close for whatever reason, a Qube Shutdown popup occurs asking the user if they want to Kill! or Wait 20 seconds.
Clicking Kill will close the window but will also kill the Qube which may no longer be desired.
Clicking Wait closes the window but it re-occurs 20 seconds later.
There doesn't seem to be any option to just ignore or cancel the shutdown request and close the window if the user no longer wishes to shut down the Qube.
Clicking the red X does nothing.

**Describe the solution you'd like**
Maybe clicking the red X on the popup window just closes the window with no more popups occurring unless the user clicks stop/shutdown again.

**Where is the value to a user, and who might that user be?**
Sometimes the user may not want the window any longer if the Qube is operating correctly and the user no longer wants to shut it down.  Maybe the user clicked the stop button accidentally.  Otherwise the popup window must remain until the user shuts down the Qube and chooses one of the given options.

**Describe alternatives you've considered**
Ignore the popup window until finished or move it to another workspace.

**Additional context**
In a Windows HVM without Windows Tools installed, clicking the stop/shutdown options will not shut down the Qube but it will continue to operate normally.

**Comment by andrewdavidwong** [comment]
At the very least, the X button shouldn't do nothing. :slightly_smiling_face:

**Comment by marmarta** [comment]
So, I cannot do "stop shutdown" - if we started a shutdown it's started, I don't think I can just abort it. But I added a button saying "don't ask again" and (hopefully in all cases) made the box itself not have a close button.

**Comment by zellchristensen** [comment]
I think the main issue here is just the popup window remaining on a Qube that has no way to automate shutdowns (ie a windows VM without qubes tools) or just a way to ignore the popup if a qube needs to take a long time to shutdown on its own.  I don't want to have to come back every 20 seconds to click wait basically.
