### ISSUE TITLE
Qubes Builder: No valid signed tag found on qubes-libcomps tag v0.1.15-1

### ISSUE THREAD

**Issue by apapsch** [QubesOS/qubes-issues#6125]
**Qubes OS version**
None. I'm on Fedora 32 vanilla, building Qubes using qubes-builder in fedora:32 container (with podman).

**Affected component(s) or functionality**
Step `make get-sources` of qubes-builder does not complete.

**Brief summary**
Downloading of sources works fine until qubes-libcomps, which aborts with "no valid tag found".

**To Reproduce**

Brief steps to reproduce the behavior:
1. In Fedora 32, create a Fedora 32 container.
2. Follow https://www.qubes-os.org/doc/qubes-iso-building/ closely, build using manual steps.

Commands:
```
// in host
$ mkdir qubes-out
$ podman run -v qubes-out:/out:rw,z -it fedora /bin/bash
// in container
# adduser -m qubes
# visudo // Allow dnf for qubes. Or all. I enabled all.
# su - qubes
$ dnf install git createrepo rpm-build rpm-sign make python3-sh rpmdevtools rpm-sign dialog perl-open python3-pyyaml perl-Digest-MD5 perl-Digest-SHA wget
$ wget https://keys.qubes-os.org/keys/qubes-master-signing-key.asc
$ gpg --import qubes-master-signing-key.asc 
$ gpg --edit-key 36879494
$ wget https://keys.qubes-os.org/keys/qubes-developers-keys.asc
$ gpg --import qubes-developers-keys.asc
$ cd /out
$ git clone git://github.com/QubesOS/qubes-builder.git
$ cd qubes-builder
$ git tag -v `git describe`
$ export GNUPGHOME=/out/qubes-builder/keyrings/git
$ mkdir --parents "$GNUPGHOME"
$ cp ~/.gnupg/pubring.kbx "$GNUPGHOME"
$ cp ~/.gnupg/trustdb.gpg "$GNUPGHOME"
$ chmod --recursive 700 "$GNUPGHOME"
$ cp example-configs/qubes-os-master.conf builder.conf
$ make install-deps
$ make get-sources
```

**Expected behavior**
Following wiki steps closely should result in successful build, `make get-sources` should finish without intervention.

**Actual behavior**
It makes boom:

```
-> Updating sources for libcomps...
--> Fetching from https://github.com/QubesOS/qubes-libcomps.git master...
--> Verifying tags...
gpg: keybox '/out/qubes-builder/keyrings/git/libcomps/pubring.kbx' created
[...]
No valid signed tag found!
---> One of invalid tag:
object a3dc14f4d19f645752707e9e0befad2a5eb8de3e
type commit
tag v0.1.15-1
tagger Frédéric Pierret (fepitre) <frederic.pierret@qubes-os.org> 1602410207 +0200

version 0.1.15-1
gpg: Signature made Sun Oct 11 09:56:47 2020 UTC
gpg:                using RSA key 9FA64B92F95E706BF28E2CA6484010B5CDC576E2
gpg: Can't check signature: No public key
make: *** [Makefile:204: libcomps.get-sources] Error 1
```

**Solutions you've tried**
* I made a web search for the key, found it [here](https://gitlab.notset.fr/fepitre-bot/qubes-builder-gentoo/-/blob/11eeba5e0b38e54e452d67870c0175654c76c6d3/keys/9FA64B92F95E706BF28E2CA6484010B5CDC576E2.asc). Imported it, but gpg tells me `trust: unknown`, while keys from `qubes-developers-keys.asc` have full trust.
* Previously, I tried building on the host machine, though using the setup script. Build failed in another way (signatures missing on rpm packages).

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
https://www.qubes-os.org/doc/qubes-iso-building/
https://www.qubes-os.org/doc/qubes-builder/
https://www.qubes-os.org/security/verifying-signatures/#1-get-the-qubes-master-signing-key-and-verify-its-authenticity

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
I couldn't find bugs using terms "No valid signed tag found", "No public key" and "fepitre".

**Comment by fepitre** [comment]
We are in progress of adding newer components. Simply comment those components: https://github.com/QubesOS/qubes-builder/pull/127/files#.

**Comment by marmarek** [comment]
This is now finished, should work again.
