### ISSUE TITLE
Convert to Trusted PDF fails on Debian-10

### ISSUE THREAD

**Issue by deeplow** [QubesOS/qubes-issues#6130]
**Qubes OS version**

R4.0 and R4.1

**Affected component(s) or functionality**

- qubes-app-linux-pdf-converter
- debian-10 template

**Brief summary**

Running `qvm-convert-pdf` fails on debian-10 based AppVMs due to a strict default ImageMagick policy (`/etc/ImageMagick-6/policy.xml`)

I also tested with various combinations of fedora and debian distros:

| AppVM | DisposableVM | Result |
|----|---|---|
| debian-10 | debian-10-dvm | **Error** (IsCoderAuthorized/408) |
| debian-10 | fedora-32-dvm | **Error** (IsCoderAuthorized/408) |
| fedora-32 | debian-10-dvm | **OK** |
| fedora-32 | fedora-32-dvm | **OK** |

It works on fedora because it has a less strict default policy.

**To Reproduce**

1. Be on a debian-10 AppVM
2. Have a DisposableVM set
3. `qvm-convert-pdf file.pdf` (or whatever pdf file you have)

**Expected behavior**

```shell_session
$ qvm-convert-pdf file.pdf
-> Sending file to a Disposable VM...
-> Waiting for converted samples...
-> Receiving page 11 out of 11...
-> Converted PDF saved as: ./file.trusted.pdf
-> Original file saved as /home/user/QubesUntrustedPDFs/file.pdf
```

**Actual behavior**

```shell_session
$ qvm-convert-pdf demo.pdf 
-> Sending file to a Disposable VM...
-> Waiting for converted samples...
Page 1 conversion failed (PNG->PDF): convert-im6.q16: attempt to perform an operation not allowed by the security policy `PDF' @ error/constitute.c/IsCoderAuthorized/408.
```

**Screenshots**

**Additional context**

The discussion that originated this came from the [forum](https://qubes-os.discourse.group/t/error-with-qvm-convert-pdf/1113).

It has been reproduced by @GWeck and [Clarawolf](https://qubes-os.discourse.group/t/error-with-qvm-convert-pdf/1113) (kudos to Clara for starting the thread and GWeck for reproducing it)

**Solutions you've tried**

I've managed to solve this by removing the following line from the policy:

```xml
<policy domain="coder" rights="none" pattern="PDF" />
```

But it should also be possible to replace that with:

```xml
<policy domain="coder" rights="read|write" pattern="PDF" />
```

So the final fix should be changing the default ImageMagick policy (`/etc/ImageMagick-6/policy.xml`) that ships with the qubes debian-10 template.

From my understanding, this change of policy does NOT affect the security of of the conversion to trusted.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

- source code: https://github.com/QubesOS/qubes-app-linux-pdf-converter/
- [ImageMagick Policy Documentation](https://imagemagick.org/script/security-policy.php)

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

none

**Comment by deeplow** [comment]
A UX improvement may be to inform the user there is a problem with the policy. This when this component is used with any other distro template the users will know what to look for in order to fix it.

**Comment by icequbes1** [comment]
Looks to be due to Debian patches in [6.9.10.23+dfsg-2.1+deb10u1](https://sources.debian.org/patches/imagemagick/8:6.9.10.23+dfsg-2.1+deb10u1/200-disable-ghostscript-formats.patch/) which also addressed around 50 CVEs:

> Author: Steve Beattie <steve.beattie@canonical.com>
> Subject: disable ghostscript handled formats based on -SAFER insecurity
> 
> Based on Tavis Ormandy's Recommendations
> updated: 2019-11-11
> 
> ...
> +  
> +  <policy domain="coder" rights="none" pattern="PS" />
> +  <policy domain="coder" rights="none" pattern="PS2" />
> +  <policy domain="coder" rights="none" pattern="PS3" />
> +  <policy domain="coder" rights="none" pattern="EPS" />
> +  <policy domain="coder" rights="none" pattern="PDF" />
> +  <policy domain="coder" rights="none" pattern="XPS" />
>  </policymap>
>

**Comment by marmarek** [comment]
In a generic case it looks like a good idea to disable those coders. But here we operate explicitly on a safe input with no way to inject any code for ghostscript to parse. Setting rights to "write" for PDF coder should be safe in context of qvm-convert-pdf, but in generic case may open the user to some ImageMagick vulnerabilities...

Perhaps a better option is to look at graphicsmagick instead? #5009

**Comment by deeplow** [comment]
> But here we operate explicitly on a safe input with no way to inject any code for ghostscript to parse.

@marmarek Exactly. So ideally the there would de the default policy (strict) to prevent user foot-shooting mistakes and then "PDF write" policy specific to the qvm-convert-pdf. But I'm not sure that is possible on imagemagick. (I haven't looked to much into it)

> Looks to be due to Debian patches in [6.9.10.23+dfsg-2.1+deb10u1](https://sources.debian.org/patches/imagemagick/8:6.9.10.23+dfsg-2.1+deb10u1/200-disable-ghostscript-formats.patch/) which also addressed around 50 CVEs

@icequbes1 So in this case here, debian has a stricter policy than fedora. Doesn't this then mean that fedora is still exposed to these CVEs? Or is it because of the outdated Debian software? Maybe I'm missing something here.

**Comment by GWeck** [comment]
In R4.1, if a PDF file is converted to a trusted PDF via the corresponding function, the dispvm for the conversion is created, performs the conversion, but then stays running and has to be shutdown manually.

**Comment by unman** [comment]
@deeplow  This works for me 210610.
 Can you test again?

**Comment by deeplow** [comment]
> @deeplow This works for me 210610.
> Can you test again?

It seems to be working for me now.

**Comment by andrewdavidwong** [comment]
> > @deeplow This works for me 210610.
> 
> > Can you test again?
> 
> 
> 
> It seems to be working for me now.


Closing this as resolved. If you believe the issue is not yet resolved, or if anyone is still affected by this issue, please leave a comment, and we'll be happy to reopen this. Thank you.

**Comment by GWeck** [comment]
On QubesR4.1, the situation is unchanged: The conversion succeeds, but the dispvm does not close and has to be shut down manually.

**Comment by GWeck** [comment]
Even after applying all current updates to dom0 and the debian template, the situation is unchanged. The zombie dispvm sems to be in a somewhat queer state, as shutting it down from the Qube manager crashes the Qube manager.

**Comment by unman** [comment]
On Sun, Jun 13, 2021 at 03:07:59AM -0700, Andrew David Wong wrote:
> Reopened #6130.
> 

This is a separate 4.1 issue, and not Debian specific.

**Comment by DemiMarie** [comment]
> Even after applying all current updates to dom0 and the debian template, the situation is unchanged. The zombie dispvm sems to be in a somewhat queer state, as shutting it down from the Qube manager crashes the Qube manager.

Would you be willing to provide a backtrace?  qubes-manager crashing is an unrelated bug, though.

**Comment by andrewdavidwong** [comment]
> On Sun, Jun 13, 2021 at 03:07:59AM -0700, Andrew David Wong wrote:
> > Reopened #6130.
> > 
> 
> This is a separate 4.1 issue, and not Debian specific.
> 

I'm guessing "this" refers to @GWeck 's comments, which prompted me to reopen this issue? And I'm guessing you're saying that the issue on which we're commenting is actually still resolved and that @GWeck is experiencing a separate bug that should be reported in a separate issue? Re-closing as resolved, then...
