### ISSUE TITLE
Building archlinux & archlinux-minimal deletes /etc/resolv.conf from host

### ISSUE THREAD

**Issue by ejose19** [QubesOS/qubes-issues#6133]
**Qubes OS version**

R4.0

**Affected component(s) or functionality**

qubes-builder

**Brief summary**

Serial runs of archlinux & archlinux+minimal templates are removing /etc/resolv.conf on host, which makes the build fail.

**To Reproduce**

Follow the steps on the [guide](https://www.qubes-os.org/doc/building-archlinux-template/), but instead of selecting only archlinux as in: 
> Screen ‘Template Distribution Selection’ will give choices of distributions to build
> Deselect everything
> Select ‘archlinux’

select both archlinux & archlinux+minimal

continue with the rest of the steps, on ```make template```, just after 1st template is built (```archlinux```), the second template (```archlinux-minimal```) will error out on:
```
--> Archlinux 00_prepare.sh
  --> Downloading Archlinux bootstrap tarball (v)...
--2020-10-20 16:45:29--  http://mirrors.kernel.org/archlinux/iso/latest/
Resolving mirrors.kernel.org (mirrors.kernel.org)... failed: Name or service not known.
wget: unable to resolve host address 'mirrors.kernel.org'
--2020-10-20 16:45:29--  http://mirrors.kernel.org/archlinux/iso/latest/.sig
Resolving mirrors.kernel.org (mirrors.kernel.org)... failed: Name or service not known.
wget: unable to resolve host address 'mirrors.kernel.org'
--> Preparing GnuPG to verify tarball...
...
  --> Verifying tarball...
gpg: can't open 'cache_archlinux/.sig': No such file or directory
gpg: verify signatures failed: No such file or directory
make[1]: *** [Makefile:65: rootimg-build] Error 2
```

which is caused because the host had its /etc/resolv.conf wiped

**Expected behavior**

Builds should not change host files, and they should be able to run sequentially.

**Actual behavior**

/etc/resolv.conf on host is being wiped

**Solutions you've tried**

To make it work, after it errors out, you can restore resolv.conf file and then run ```./setup``` again to only leave archlinux-minimal (since the archlinux template is already build). Then run ```make template``` and it will finish without issues.

**Comment by fepitre** [comment]
I encountered this issue few days again and I found the issue. I'll commit the fix.
