### ISSUE TITLE
TemplateVM chains

### ISSUE THREAD

**Issue by TamaraneanGirl** [QubesOS/qubes-issues#6134]
**The problem you're addressing (if any)**
It can get cumbersome to manage the updates of multiple TemplateVMs that have been  assigned different purposes.

 Users have to download multiple updates for qubes which may have been derived from the same original TemplateVM, wasting storage space, and network bandwidth.

**Describe the solution you'd like**
Allow TemplateVMs to be templates of other TemplateVMs, forming a hierarchy.

**Where is the value to a user, and who might that user be?**
Users can save bandwidth by downloading less updates in total.

Ease of management, potentially increasing security.

**Describe alternatives you've considered**
Maintaining software collection of cloned TemplateVMs manually.

**Additional context**
This might not be feasible, as TemplateVMs have their entire root exposed, so tracking changes to distribute may be difficult.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
https://www.qubes-os.org/doc/templates/

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
Could not find.

**Comment by zaoqi** [comment]
> This might not be feasible, as TemplateVMs have their entire root exposed, so tracking changes to distribute may be difficult.

Users can write some script to describe changes

**Comment by andrewdavidwong** [comment]
> Allow TemplateVMs to be templates of other TemplateVMs, forming a hierarchy.

This has been suggested before and determined to be impossible:

https://groups.google.com/d/topic/qubes-users/iLJjTTQqgrw/discussion

Unless @marmarek says that it is now possible, this looks like a `won't do` (because `can't do`).

> Users can save bandwidth by downloading less updates in total.

This is a separate issue: https://github.com/QubesOS/qubes-issues/issues/1957
