### ISSUE TITLE
Preserve column width on Qube Manager

### ISSUE THREAD

**Issue by ejose19** [QubesOS/qubes-issues#6137]
**The problem you're addressing (if any)**

Currently, Qube Manager doesn't preserve column width after restarting, which is an issue since default widths aren't balanced, making only the last column to take all the available width and other columns such as name, template and netvm having their text broken in 2 lines if they exceed the default width.

**Describe the solution you'd like**

Simpler solution would make Qube Manager remember the user specified width for each column, so it would be an one-time setup.

**Where is the value to a user, and who might that user be?**

When some columns are broken in two lines, it degrades a lot the readability on the Qube Manager, so this change would preserve it no matter the name(s) length.

**Describe alternatives you've considered**

Other than setting widths each time Qube Manager is run (which is way too cumbersome), there's no alternative.

**Comment by donob4n** [comment]
Just a note. In current last version there is a call to 'resizeColumnsToContents()' which adjusts all columns automatically, also you can't get a line broken in two. I don't see too much benefit from storing the width if modified.

Maybe this behaviour can be easily backported to 4.0.

**Comment by marmarta** [comment]
Yeah, we can add this resizing easily, I just checked it does work. Will push a simple PR to 4.0 with it.

**Comment by marmarta** [comment]
That was actually done by https://github.com/QubesOS/qubes-manager/pull/271 , I just failed to tag this ticket (sorry!) :) closing.

**Comment by ejose19** [comment]
@marmarta Thanks for this! Any ideas when it will be released? Last version of qubes-manager for v4.0 was on Oct 27, 2020.
