### ISSUE TITLE
Error with mirror links for updating Fedora template

### ISSUE THREAD

**Issue by reallusionoftruth** [QubesOS/qubes-issues#6138]
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
update of fedora template from 30 to 32 

**Brief summary**
Installed Qubes today but just found out that 30 is EOL. Followed instructions linked in Announcement to update template to 32.  None of the mirror links worked due to faulty mirror link. UPDATE: Working now. Addressed under **solutions I tried**

**To Reproduce**

1. sudo qubes-dom0-update qubes-template-fedora-32 with sys-whonix running a obfs4 bridge

**Expected behavior**
Expected for regular update to occur

**Actual behavior**
Links to the mirror is correct but is broken due to the presence of a colon( : ) at the end of each link of each mirror. Attempted to enter the mirror link without the colon on a browser and it is possible to download rpm file

**Screenshots**
![Screenshot_2020-10-22_02-02-36](https://user-images.githubusercontent.com/37320014/96767376-0839c200-140f-11eb-8717-8082914382c9.png)

**Additional context**
None

**Solutions you've tried**
Working now. The main error was due to sys-whonix. I use a bridge for tor. 

Attempted to remove bridge and run sys-whonix as updatevm without proxies and bridges enabled. Still did not work with the **actual behavior** still occurring.  

Changing the mode from sys-whonix to sys-firewall for Dom0 UpdateVM under system default in Qubes Global Setting made it to work 

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
None

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
#4714

**Comment by reallusionoftruth** [comment]
Forgive me if there are things that does not make much sense. It is my first time issuing a bug and also the first time of mine using github.

**Comment by andrewdavidwong** [comment]
>  UPDATE: Working now. Addressed under solutions I tried
> [...]
> Working now. The main error was due to sys-whonix. I use a bridge for tor.

If I'm understanding you correctly, you've got everything working now, and it turned out there was no bug after all, so I'll close this as `not an issue`.

If I've misunderstood, and there's still a bug, please reply with a clear description of what exactly the bug is.
