### ISSUE TITLE
"Status" is not clear.

### ISSUE THREAD

**Issue by straussmaus** [QubesOS/qubes-issues#6141]
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
Qubes Manager

**Brief summary**
A qube shows a yellow dot next to it, under "Status" but yellow status is nowhere defined.

**To Reproduce**
I do not know what causes the yellow dot.  But I have a VPN Qube that shows the yellow dot sometimes, in Qubes Manager, in the Status column.

**Expected behavior**
The dot should be green, but more important I expect a mouseover explanation of what the problem is, or at least a doc somewhere that explains status levels.

**Actual behavior**
The yellow dot is there and makes me scared.

**Additional context**
The VM and its VPN seem to be functioning correctly?

**Solutions you've tried**
- Mouseover (shows nothing)

- Right-click and look at logs (shows good stuff like this:

```
"[21669.660620] audit: type=1130 audit(1603078239.762:96): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=qubes-sync-time comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
```

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

I searched for "yellow" and "status" on qubes-os.org and did not find anything that seemed relevant.

**Comment by marmarta** [comment]
This is fixed by https://github.com/QubesOS/qubes-manager/commit/bb1995af2e90aae51f07c518b74d98221c2d5cc1 (the great model/view rewrite of Qube Manager); to answer what a yellow dot means: it's usually the "transient" state, or booting, or halting.
