### ISSUE TITLE
Archlinux templates do not receive DNS configuration

### ISSUE THREAD

**Issue by icequbes1** [QubesOS/qubes-issues#6145]
**Qubes OS version**
4.0, 4.1

**Affected component(s) or functionality**
qubes-builder-archlinux

**Brief summary**
The fix in #6133 (resolv.conf deleted from host) causes an AppVM booted from the template to not have DNS and to most users appear to not have internet.

**To Reproduce**

1. Build archlinux template
2. Install template
3. Create an AppVM from template

**Expected behavior**

Ability to resolve hosts by default

**Actual behavior**

Inability to resolve hosts by default unless `/etc/resolv.conf` is manually created/modified.

**Additional context**

The fix in #6133 addressed successive builds of the template removing /etc/hosts from the build host. However, the resolution leaves the template with no DNS.

1. The fix removed /etc/resolv.conf from the $INSTALLDIR/etc/resolv.conf instead of /etc/resolv.conf, which resolves the issue described above.
1. However, that leads $INSTALLDIR/etc without a resolv.conf.
1. With no /etc/resolv.conf in the template, once the VM boots, systemd's tmpfiles.d links `/etc/resolv.conf` to `../run/systemd/resolv/stub-resolv.conf`
1. There is no systemd-resolved running in the template, so it's a dead symlink
1. When an AppVM boots, it relies on the Qubes scripts to setup DNS
1. Since /etc/resolv.conf is a symlink, those updates do not get made
1. This leaves an AppVM without DNS

**Solutions you've tried**

In an AppVM, remove the /etc/resolv.conf symlink and create a standard file with the expected content.

For build purposes:

Ensure $INSTALLDIR/etc/resolv.conf is the standard empty file before packaging:

```
# This file left intentionally blank
```

Analysis of resolv.conf usage in archlinux builder and rpm builder:

- The archlinux builder uses the build host's /etc/resolv.conf throughout the whole build process.

- The rpm builder initializes $INSTALLDIR/etc/resolv.conf with the blank file, and then bind mounts the build host /etc/resolv.conf only when performing yum commands. Unmounting the bind restores the original "blank file" contents by the time the template's root image is created.

**Comment by fepitre** [comment]
Yes you are right. Ideally, /etc/resolv.conf should be created too on boot but let's fix this first.

**Comment by ptitdoc** [comment]
One option if you want to keep systemd-resolved is to use fix DNS configuration within it such as in `/etc/systemd/resolved.conf`.

I however had bad experiences with systemd DNS handling and a big mess with the `.local` domains.

**Comment by icequbes1** [comment]
@ptidoc I agree that could resolve it as well, however my observation is the "Qubes OS" template approach is to not use any template-specific DNS configuration and rely on the upstream netvm to handle DNS by default. Of course the user can always update their template to do something else.

**Comment by ptitdoc** [comment]
Yeah it is better to force /etc/resolv.conf to be a real file than to mess with systemd. However if I remember glibc will still use systemd resolver by default instead of /etc/resolv.conf, depending on different things such as how /etc/nsswitch.conf is set.

If you look at how nsswitch.conf is set:
`hosts: files mymachines myhostname resolve [!UNAVAIL=return] dns`

It will try to use systemd resolver and never dns (resolv.conf).

Systemd resolver also ignore any .local domain (because somebody decided that only apple discovery protocol could use .local or something like that).

So in the end, I often tweak my configuration like that to force legacy DNS configuration:
`hosts: files mymachines myhostname dns resolve [!UNAVAIL=return]`

**Comment by unman** [comment]
@andrewdavidwong  @icequbes1 
As a result of changes merged and updated packages, the Arch template for 4.0 builds correctly with no dependency errors.
Any qubes created from the template resolve DNS queries correctly.
I don't have a working 4.1 to test that, but I believe the issue there is also fixed.
Please close this issue.
