### ISSUE TITLE
Renaming VM breaks launchers on panel and desktop

### ISSUE THREAD

**Issue by maqp** [QubesOS/qubes-issues#6147]
**Qubes OS version**: 4.0.3

**Affected component(s) or functionality**: Panel/Desktop launchers

**Brief summary**: Renaming VM breaks launchers on panel and desktop

**Steps to reproduce the behavior:**
1. Drag launcher of some application of some VM to desktop and to panel
2. Rename the VM
3. Try to open the application with the launcher

**Expected behavior**: Renaming the VM changes panel/desktop launchers' VM argument for related launchers, and the launcher keeps working

**Actual behavior**: The launcher's VM argument stays the same and the launcher stops working.

**Solutions you've tried**: Opening properties from the right-click menu of the launcher, and editing the name and command to reflect the new VM name works, but the icon of of the launcher disappears.

**Screenshots**: n/a

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**: n/a

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**: n/a

**Comment by unman** [comment]
On Sat, Oct 24, 2020 at 06:57:21PM -0700, Markus Ottela wrote:
> **Qubes OS version**: 4.0.3
> 
> **Affected component(s) or functionality**: Panel/Desktop launchers
> 
> **Brief summary**: Renaming VM breaks launchers on panel and desktop
> 
> **Steps to reproduce the behavior:**
> 1. Drag launcher of some application of some VM to desktop and to panel
> 2. Rename the VM
> 3. Try to open the application with the launcher
> 
> **Expected behavior**: Renaming the VM changes panel/desktop launchers' VM argument for related launchers, and the launcher keeps working
> 
> **Actual behavior**: The launcher's VM argument stays the same and the launcher stops working.
> 
> **Solutions you've tried**: Opening properties from the right-click menu of the launcher, and editing the name and command to reflect the new VM name works, but the icon of of the launcher disappears.
> 
> **Screenshots**: n/a
> 
> **Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**: n/a
> 
> **Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**: n/a
> 

Do you think that the system should be scanned for any potential
panel/desktop launchers/shortcuts to give effect to your expectation?
What about scripts in dom0? Scripts in other qubes that refer to the qube
that has been renamed?

If you clone a qube do you expect that launchers etc will be cloned too?

**Comment by maqp** [comment]
>Do you think that the system should be scanned for any potential
panel/desktop launchers/shortcuts to give effect to your expectation?

The launchers for panel are in `$HOME/.config/xfce4/panel/` under individual directories e.g. `launcher-1/<timestamp>.desktop` and the launchers for desktop are in `$HOME/Desktop/<name>.desktop`

Those directories would need to be scanned, yes.

As for scripts, no I don't think so: they probably don't have such standard form you could safely rename every occurrence of say word the `personal` or `work`. The context here was only Launchers.

>If you clone a qube do you expect that launchers etc will be cloned too?

I don't think that's a good idea. I'd expect no new launchers to be created when cloning a cube, but that renaming the clone would automatically rename any launchers created for that clone.
