### ISSUE TITLE
Xen version in install ISO is outdated and vulnerable

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#6150]
**Qubes OS version**

`Qubes release 4.0 (R4.0)`

**Affected component(s) or functionality**

Install ISO

**Brief summary**

Qubes R4.0.3 includes Xen 4.8.5-14.  This is vulnerable to QSB#58, QSB#59, and QSB#60.

**To Reproduce**

1. Boot the install ISO
2. See the Xen version flash during boot

**Expected behavior**

The install ISO includes a secure version of Xen.

**Actual behavior**

The install ISO includes a vulnerable version of Xen.  Since the installer does not connect to the Internet, this means that the version of Xen it installs is also vulnerable.

**Screenshots**

**Additional context**

**Solutions you've tried**

None known, other than building a bespoke install ISO.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

**Comment by marmarek** [comment]
You could say that after any QSB, or even after any update ("the package X on installation image is buggy").
It isn't viable to release new ISO after every update or even just after every QSB. You should simply install updates after installation, see [installation guide](https://www.qubes-os.org/doc/installation-guide/#next-steps).
