### ISSUE TITLE
Remove "Qube configuration problem!" Popup for Non-Networked Qubes Firewall Rules Setting

### ISSUE THREAD

**Issue by zellchristensen** [QubesOS/qubes-issues#6153]
**The problem you're addressing (if any)**
If the user selects the Firewall rules tab in a Qube's settings, if the Qube has no networking, a popup occurs forcing the user to select OK before continuing.  This happens every time the tab is selected, even in the same window session.

**Describe the solution you'd like**
Remove the popup since essentially the same message is already displayed in bold red at the top and all the options are already inaccessible/greyed out if the user doesn't change the radio button option. 
Maybe enhance the red text at the top to be more similar to the message in the popup so the information is still available to the user without being as obtrusive.

**Where is the value to a user, and who might that user be?**
Doesn't interrupt the user's workflow in case of an accidental misclick by forcing them to stop and click OK.  For example if they just want to switch between each tab in order, they're forced to stop, and click OK or push enter before they can continue.  

**Describe alternatives you've considered**
Hide/eliminate the firewall tab completely if networking is disabled.

**Additional context**
While it's less obtrusive if the user is using a keyboard only for navigation, it's more of an issue when using a mouse forcing the user to move to the center of the screen instead of their intended location.

**Comment by marmarta** [comment]
This was fixed by https://github.com/QubesOS/qubes-manager/commit/42affe0da66bdb5c3fab354ec5e1b6b815398fdc#diff-21dd7831456be115c64d4308caf06c2bea26300c1be7b188789bfdf736db42e0 ; definitely will be in 4.1, I think it's also in the testing branch.
