### ISSUE TITLE
Gentoo template fails to start: qrexec-daemon failed

### ISSUE THREAD

**Issue by betamax96** [QubesOS/qubes-issues#6154]
**Qubes OS version**

R4.1

**Affected component(s) or functionality**

qubes-template-gentoo

**Brief summary**

When installing the Gentoo template provided by the community repository, it installs but fails to startup. The follow notification shows upon installation: 
```
Qube Status: gentoo
Domain gentoo has failed to start: qrexec-daemon startup failed: Connection to the VM failed
```

**To Reproduce**

1. Install the gentoo template as provided in the documents: https://www.qubes-os.org/doc/templates/gentoo/#installation
2. sudo qubes-dom0-update --enablerepo=qubes-templates-community qubes-template-gentoo
3. Wait for completion; It will automatically start the VM but it will fail to start due to qrexec-daemon

**Expected behavior**

A working gentoo template

**Actual behavior**

Upon starting the template, the following error appears:
```
Qube Status: gentoo
Domain gentoo has failed to start: qrexec-daemon startup failed: Connection to the VM failed
```

**Screenshots**

**Additional context**

**Solutions you've tried**

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

https://www.qubes-os.org/news/2020/10/05/new-gentoo-templates-and-maintenance-infrastructure/
https://www.qubes-os.org/doc/templates/gentoo

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

https://github.com/QubesOS/qubes-issues/issues/4412

**Comment by fepitre** [comment]
I don't reproduce that. I've installed the template multiple times and another one yesterday from the template community. I can start normally applications. You specify Qubes 4.1 but which devel version are you using? Are you sure to be up to date with latest qrexec dom0 part? (current-testing enabled!).

**Comment by betamax96** [comment]
> I don't reproduce that. I've installed the template multiple times and another one yesterday from the template community. I can start normally applications. You specify Qubes 4.1 but which devel version are you using? Are you sure to be up to date with latest qrexec dom0 part? (current-testing enabled!).

Ah that was the reason, I didn't enable current-testing repo. Thank you very much.
