### ISSUE TITLE
Qubes 4.0/4.1: repository "qubes-repo-contrib" is broken on dom0

### ISSUE THREAD

**Issue by ghost** [QubesOS/qubes-issues#6157]
**Qubes OS version**
4.0, 4.1

**To Reproduce**

```
sudo qubes-dom0-update qubes-repo-contrib
```
enable repo in `/etc/yum/repos.conf.d/`
`enabled=1 `  
(`qubes-contrib-dom0-r4.0-current`,`qubes-contrib-dom0-r4.0-current-testing`)
```
sudo qubes-dom0-update --clean
sudo qubes-dom0-update --refresh
sudo qubes-dom0-update 
```
install something 
```
sudo qubes-dom0-update polybar
```
any package from repo returns `Curl error (37)`
and cannot be installed on system.

`Curl error (37): Couldn't read a file:// file for file:///etc/pki/rpm-gpg/RPM-GPG-KEY-qubes-4-contrib-fedora [Couldn't open file /etc/pki/rpm-gpg/RPM-GPG-KEY-qubes-4-contrib-fedora]`

**Comment by 0rb677** [comment]
Also request to add shadow compositor as `compton` to repo.
https://github.com/yshui/picom
Thanks!

**Comment by andrewdavidwong** [comment]
> Also request to add shadow compositor as `compton` to repo.
> https://wiki.archlinux.org/index.php/Picom
> https://github.com/yshui/picom
> Thanks!

Please note that [every issue must be about a single thing](https://www.qubes-os.org/doc/reporting-bugs/#every-issue-must-be-about-a-single-actionable-thing).

**Comment by Enteee** [comment]
This happened to me because I was missing `qubes-repo-contrib` on the build qube (`sys-firewall`).

To fix this install on `sys-firewall` (or in the template):
```
$ sudo dnf install qubes-repo-contrib
```

**Comment by N1ck9141** [comment]
I had the same issue. But did not need to install in my sys-firewall. I just ran: 

`
$ sudo rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-qubes-4-contrib-fedora `

in dom0 and then with first use I added `--clean ` tag and all was well
