### ISSUE TITLE
sys-usb suddenly prompting dom0 for qubes.InputMouse access on startup

### ISSUE THREAD

**Issue by GSF1200S** [QubesOS/qubes-issues#6160]
**Qubes OS version**
Qubes R 4.0

**Affected component(s) or functionality**
sys-usb or dom0 (uncertain)

**Brief summary**

For what its worth, I posted this in /r/Qubes on reddit as well. Since this is a change in behavior relating to dom0 input, I figure it's worth at least posting here to be cautious. It's also worth noting that to an extent this is a regression since at least in my case I must always deal with a prompt now when sys-usb starts regardless if I have a USB input device plugged in, etc. Here is the reddit post:

Today I updated Qubes and this included a dom0 update.

After the update I rebooted, and to my surprise sys-usb requested authorization for InputMouse twice AND it requested sudo privileges (via VMAuth- I have vm sudo setup). Not liking this, I deleted sys-usb and created a new one.

Now sys-usb no longer requests sudo privileges, but it still requests permission to attach InputMouse to dom0 at sys-usb startup (without any USB devices plugged in); it does this regardless of whether I use Fedora-32 or Debian-10 as sys-usb's TemplateVM.

Consider that before today I've never had any issues with sys-usb, and its behavior has always been the same: starting sys-usb works like any AppVM without any prompt, but then when I would plug in a USB mouse it asked for me to accept attaching to dom0.

I do notice this device:

    Bus 001 Device 002: ID 0627:0001 Adomax Technology Co., Ltd

But a ddg search suggests that this is normal and is to help with mouse accuracy. I could understand this being the device that causes dom0 to prompt me, but then why has it never done so before? Given that this is a security OS, I don't think its paranoid to ask...

That this behavior has suddenly changed (especially given it asking for root before I wiped sys-usb and redid it) is a bit spooky, but I also realize that dom0 had updates and so perhaps its just a bug or expected behavior.

Any guidance on this? Anyone else notice any difference in behavior with sys-usb?

I'm on an X230 which is quite commonly used with Qubes. I don't notice anything strange in lsusb under sys-usb. If I deny the first request for attaching InputMouse to dom0, in sys-usb I get:

    qubes-input-sender: request refused

But otherwise the system works fine. If I then plug in my USB mouse it will prompt me once again, and accepting results in the mouse working just fine. Do note that when I setup sys-usb, I have to disable strict pci reset or sys-usb won't start (factory lenovo UEFI firmware). 

FWIW, I do NOT have a keyboard attached to dom0 (I use the X230's keyboard), and I don't have a NetVM setup for sys-usb either. I'm considering filing a bug report on github, but I figured I'd ask here first.

**To Reproduce**

1. Boot sys-usb with no USB devices attached
2. Notice dom0 prompt related to qubes.InputMouse

**Expected behavior**
dom0 should only prompt when a USB input device (USB mouse) is connected.

**Actual behavior**
dom0 prompts upon startup of sys-usb even with no USB devices attached.

**Solutions you've tried**
Re-setup sys-usb and verified /etc/qubes-rpc/policy/qubes.InputMouse. Contents:

sys-usb dom0 ask,default_target=dom0
$anyvm $anyvm deny

If this is due to changes in dom0 or expected behavior, feel free to close this.

**Comment by marmarek** [comment]
This looks to be a bug in recent update: https://github.com/QubesOS/updates-status/issues/2072

**Comment by tumbletree** [comment]
I'll just note that I am also having issues with sys-usb. I also use an x230. Started sometime in last few weeks.

1. use laptop as a laptop
2. return to dock
3. observe loss/lack of function in usb mouse (attached to dock station)
4. restart sys-usb
5. all is well

I don't know if this is relevant. There are no prompts.

(Note too that start-up "on dock" delivers a mirrored display, not split screen (i.e. laptop + VGA) like it used to. Started around the same time, is dom0 related. I wondered if I had screwed something up in `xrandr` settings by making a shortcut to restore split screen on return to dock).

**Comment by GSF1200S** [comment]
As it turns out, the root thing does still seem to be the case as well. It prompts dom0 and heres the relevant lines from sys-usb's journal I cut out two lines exactly like the first one):

> Oct 29 23:45:46 sys-usb sudo[715]: pam_exec(sudo:auth): /usr/lib/qubes/qrexec-client-vm failed: exit code 126

>  Oct 29 23:45:47 sys-usb sudo[715]:     user : 3 incorrect password attempts; TTY=unknown ; PWD=/home/user ; USER=root ; COMMAND=/bin/systemctl --no-block start qubes-input-sender-mouse@event5.service

I think this might be relevant for us users who choose to run sudo in our AppVMs- sys-usb never used to prompt for sudo privileges before. Just FYI...

**Comment by marmarek** [comment]
As reported by @icequbes1 in https://github.com/QubesOS/updates-status/issues/2166#issuecomment-720153736:
> Fedora 32 HVMs with kernel set to None are getting a qubes.InputTablet qrexec deny after successful boot. In-vm kernel is 5.8.15-201.fc32.
> 
> Not observed on Fedora 32 HVM with kernel provided by Qubes (5.8.16-1.qubes).
> 
> Noticed after attempting to test [QubesOS/qubes-issues#6174](https://github.com/QubesOS/qubes-issues/issues/6174).
> 
> Compared to app-linux-input-proxy 1.0.20:
> 
>     * 1.0.20-1: qrexec denials for qubes.InputMouse are seen, only
> 
>     * 1.0.21-1: qrexec denials for qubes.InputTablet are seen, only

**Comment by marmarek** [comment]
It seems with a kernel from dom0 PCI BDFs are assigned differently, specifically 00:03.0 is skipped for some reason, which shifts other devices too. This means the USB controller from QEMU can be at 00:04.0 or 00:05.0. We use that to filter out the device - the filter needs to be adjusted.

**Comment by GSF1200S** [comment]
I don't know if anyone will see this or if I need to open a new issue, but I'm still sort-of having the problem I mentioned along with qubes.InputMouse. 

I pulled all the updates from testing (for the TemplateVMs and for dom0. This may be new expected behavior, but I want to make sure since it includes root. I have vm sudo setup, and sure enough when I start up sys-usb first time (debian or fedora templates) I get dom0 prompting me for root access. If I deny it 3 times (like any sudo request) it stops pestering me and my mouse (and everything else) still works fine. The error message I get in sys-usb's journal:

`sys-usb sudo[775]:     user : 3 incorrect password attempts ; TTY=unknown ; PWD=/home/user ; USER=root ; COMMAND=/bin/systemctl --no-block start qubes-input-sender-keyboard-mouse@event6.service
`

Again sys-usb never before (for years) prompted me for root access, and even denying it root access sys-usb still seems to perform fine. Is this expected behavior? Do I need to file a new bug report or should this one be re-opened?

**Comment by marmarek** [comment]
Can you confirm `event6` is indeed the device you want to use? For example check in sys-usb `udevadm info -q all -n input/event6`. Either way, it is a bug (still the same one), but depending on your answer the fix may differ.

**Comment by GSF1200S** [comment]
> Can you confirm `event6` is indeed the device you want to use? For example check in sys-usb `udevadm info -q all -n input/event6`. Either way, it is a bug (still the same one), but depending on your answer the fix may differ.

Sorry for the delay. Running that command I can confirm that event6 is indeed my mouse USB fob (the one I want to use). I'm pretty sure the mouse (Logitech MX Anywhere 2) has one of those unified receiver fob deals, so I see: ID_INPUT_MOUSE=1, ID_INPUT_KEY=1, and ID_INPUT_KEYBOARD=1 but I'm still only using it for the mouse. FWIW my issue occurs with no other USB device/fob/etc plugged in. If you need the output of that command or any other info, just let me know...
