### ISSUE TITLE
Documentation: how to run WireGuard as VPN

### ISSUE THREAD

**Issue by ratpoison4** [QubesOS/qubes-issues#6161]
All the guides I found are quite old. WireGuard is now in Debian buster-backports and it can be installed quite easily on Qubes.

I figured out how to do it and wrote instructions that worked for me. I would like to move the instructions to Qubes documentation so that other people can benefit from it.

The instructions: https://gist.github.com/ratpoison4/3d027d721812fc7a0954db1c1db4972e

**Comment by woju** [comment]
> The instructions: https://gist.github.com/ratpoison4/3d027d721812fc7a0954db1c1db4972e

I just write `wg-quick up /rw/config/wg0.conf` and avoid copying the file.

**Comment by andrewdavidwong** [comment]
Could you please submit this to the [Qubes Community documentation](https://github.com/Qubes-Community)? We are presently in the process of moving all external documentation there (https://github.com/QubesOS/qubes-issues/issues/4693).

**Comment by ratpoison4** [comment]
> I just write `wg-quick up /rw/config/wg0.conf` and avoid copying the file.

Thanks! Updated.
