### ISSUE TITLE
Qube manager tool bar too wide

### ISSUE THREAD

**Issue by GWeck** [QubesOS/qubes-issues#6166]
**The problem you're addressing (if any)**
In the new alpha version of R4.1 from 14-Oct-2020, the icons of the Qube manager tool bar all have descibing texts underneath (similar to the former texts in the tool tips). This causes the tool bar to have approximately twice the width of the former tool bar. If The Qube manager is configured to show only the most relevant columns, the tool bar is truncated and has to be manually expanded in order to access the rightmost icons, which is somewhat cumbersome.

**Describe the solution you'd like**
It would be nice to have an option to show only the icons and no texts, thus reverting to the old tool bar style, which is, in my opinion, more convenient for users knowing the meaning of the icons. If something is unclear, the tool tips could still help.

**Where is the value to a user, and who might that user be?**
With the old, narrow tool bar, all icons are shown and can be accessed without the need to expand the tool bar to access the rightmost functions, which saves about half of the necessary clicks.

**Describe alternatives you've considered**
currently none, although using the wide tool bar is somewhat a nuisance

**Additional context**
the width might be changed via an additional option in the View menu list.

**Comment by donob4n** [comment]
Hi, I was thinking on adding a 'Compact View' option for hide the buttons text.

**Comment by marmarta** [comment]
> Hi, I was thinking on adding a 'Compact View' option for hide the buttons text.

That's a very good idea. I'd keep the text as default (as when someone runs QM for the first time the buttons can be unclear), and store if this option was selected in settings. Do you want to do it?

**Comment by donob4n** [comment]
Oh yes, I tried to do it yesterday but it seems that there is no option for hide the text so I will have to store it somewhere and replace with empty strings.

**Comment by donob4n** [comment]
self.toolbar.setToolButtonStyle(Qt.ToolButtonIconOnly) does the trick!
