### ISSUE TITLE
Critical error when trying to open settings window for any qube (qubes-vm-settings)

### ISSUE THREAD

**Issue by KnightWhoSaysNeeeowWumPing** [QubesOS/qubes-issues#6171]
**Qubes OS version**

Qubes release 4.0 (R4.0)

**Affected component(s) or functionality**

Qubes Manager, qubes-vm-settings

**Brief summary**

When trying to open the qubes settings window for any qube, it simpy does not open.  
Executing the `qubes-vm-settings` command in a dom0 console results in an error.

**To Reproduce**

Steps to reproduce the behavior (via gui):
1. Open the Qubes Manager
2. Right-click onto a qube and select qube settings

Steps to reproduce the behavior (via terminal):
1. Open a terminal in dom0
2. Execute `qubes-vm-settings personal`

**Expected behavior**

The settings window for the specified qube should open without any error.

**Actual behavior**

When trying via the Qubes Manager GUI, nothing happens.  
Upon executing the terminal command, the following error occurs in the terminal:
```
$ qubes-vm-settings personal
Traceback (most recent call last):
  File "/usr/bin/qvm-appmenus", line 9, in <module>
    load_entry_point('qubesdesktop==4.0.20', 'console_scripts', 'qvm-appmenus')()
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2575, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2235, in load
    return self.resolve()
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2241, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.5/site-packages/qubesappmenus/__init__.py", line 41, in <module>
    import qubesimgconverter
  File "/usr/lib/python3.5/site-packages/qubesimgconverter/__init__.py", line 35, in <module>
    import numpy
  File "/usr/lib64/python3.5/site-packages/numpy/__init__.py", line 142, in <module>
    from . import add_newdocs
  File "/usr/lib64/python3.5/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/usr/lib64/python3.5/site-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/usr/lib64/python3.5/site-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/usr/lib64/python3.5/site-packages/numpy/core/__init__.py", line 14, in <module>
    from . import multiarray
ImportError: libgfortran.so.3: cannot open shared object file: No such file or directory
```

Apart from that an error message window appears with the following content:
```
Whoops. A critical error has occured. This is most likely a bug in Qubes Manager.

CalledProcessError: Command '['qvm-appmenus', '--get-whitelist', 'personal']' returned non-zero exit status 1 at line 9 of file /usr/bin/qubes-vm-settings.
```
The *Show Details...* button reveals the following additional information:
```
----
line: output=stdout, stderr=stderr)
func: run
line no.: 398
file: /usr/lib64/python3.5/subprocess.py
----
line: **kwargs).stdout
func: check_output
line no.: 316
file: /usr/lib64/python3.5/subprocess.py
----
line: ['qvm-appmenus', '--get-whitelist', self.vm.name]
func: fill_apps_list
line no.: 50
file: /usr/lib/python3.5/site-packages/qubesmanager/appmenu_select.py
----
line: self.fill_apps_list()
func: __init__
line no.: 46
file: /usr/lib/python3.5/site-packages/qubesmanager/appmenu_select.py
----
line: self.app_list_manager = AppmenuSelectManager(self.vm, self.app_list)
func: __init__
line no.: 227
file: /usr/lib/python3.5/site-packages/qubesmanager/settings.py
----
line: settings_window = VMSettingsWindow(vm, qapp, args.tab)
func: main
line no.: 1319
file: /usr/lib/python3.5/site-packages/qubesmanager/settings.py
----
line: load_entry_point('qubesmanager==4.0.43', 'console_scripts', 'qubes-vm-settings')()
func: <module>
line no.: 9
file: /usr/bin/qubes-vm-settings

```

**Comment by hackerncoder** [comment]
The first thing that stands out to me is `ImportError: libgfortran.so.3: cannot open shared object file: No such file or directory`, as if libgfortran isn't installed 

Is libgfortran installed in dom0? (`dnf info libgfortran`)

**Comment by marmarta** [comment]
That looks like a problem with libfortran library... could you perhaps check what version of it do you have in dom0 ( `rpm -qa || grep fortran` is an easy way)?

**Comment by marmarta** [comment]
Also @marmarek , we should be installing libgfortran with gcc, right? Because this looks like missing dependencies, but how can anything work with missing libgfortran?

**Comment by marmarek** [comment]
libgfortran is normally installed and set as dependency of appropriate packages. Perhaps it is some kind of disk issue? @KnightWhoSaysNeeeowWumPing can you verify that:
1. You have libgfortran installed: `rpm -q libgfortran`
2. All its files are in place: `rpm -V libgfortran` (if everything is ok there should be no messages)

**Comment by KnightWhoSaysNeeeowWumPing** [comment]
Sorry for taking so long to reply, I had startup problems with the system in question.

1. libgfortran is installed in version: `libgfortran-6.4.1-1.qubes2.fc25.x86_64`
2. There seem to be some files missing: 
```
missing     /usr/lib64/libgfortran.so.3
missing     /usr/lib64/libgfortran.so.3.0.0
```

I then tried to re-install the package with `sudo qubes-dom0-update libgfortran` and `sudo dnf reinstall libgfortran` as stated in the [documentation](https://www.qubes-os.org/doc/software-update-dom0/#how-to-re-install-a-package) but this fails since the first command does not download when the package is already installed - other than described in the documentation.

When I tried to install the missing packages directly via `sudo qubes-dom0-update libgfortran.so.3` it fails with:
```
Error: cannot install both libgfortran-6.4.1-1.fc25.x86_64 and libgfortran-6.4.1-1.qubes2.fc25.x86_64
```
... and I didn't want to break anything by using `--allowerasing` so I stopped there.

**Comment by DemiMarie** [comment]
What happens if you run `sudo qubes-dom0-update libgfortran-6.4.1-1.qubes2.fc25.x86_64`?

**Comment by KnightWhoSaysNeeeowWumPing** [comment]
The reinstall seemed to fix the problem regarding libgfortran.
Nevertheless executing `qubes-vm-settings personal` got me another error this time:
```
Traceback (most recent call last):
  File "/usr/bin/qvm-appmenus", line 9, in <module>
    load_entry_point('qubesdesktop==4.0.21', 'console_scripts', 'qvm-appmenus')()
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2575, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2235, in load
    return self.resolve()
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2241, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.5/site-packages/qubesappmenus/__init__.py", line 42, in <module>
    import qubesimgconverter
  File "/usr/lib/python3.5/site-packages/qubesimgconverter/__init__.py", line 35, in <module>
    import numpy
  File "/usr/lib64/python3.5/site-packages/numpy/__init__.py", line 142, in <module>
    from . import add_newdocs
  File "/usr/lib64/python3.5/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/usr/lib64/python3.5/site-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/usr/lib64/python3.5/site-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/usr/lib64/python3.5/site-packages/numpy/core/__init__.py", line 14, in <module>
    from . import multiarray
ImportError: libquadmath.so.0: cannot open shared object file: No such file or directory
Segmentation fault (core dumped)
```

So I tried the requested steps for libquadmath too by executing:
1. `rpm -q libquadmath` which returned `libquadmath-6.4.1-1.qubes2.fc25.x86_64`
2. `rpm -V libquadmath` which returned
```
missing     /usr/lib64/libquadmath.so.0
missing     /usr/lib64/libquadmath.so.0.0.0
```
3. `sudo qubes-dom0-update --action=reinstall libquadmath-6.4.1-1.qubes2.fc25.x86_64`

After all, the settings window appears to work again.
I can't think of any reason, why libgfortran and libquadmath were broken on my system but I'm glad it is now resolved.

**A big thank you to everyone involved in helping me resolve this error, namely @marmarta, @marmarek and @DemiMarie!**
