### ISSUE TITLE
Applications Merged

### ISSUE THREAD

**Issue by f0xy** [QubesOS/qubes-issues#6175]
**The problem you're addressing (if any)**

.config/menus/applications-merged/ menu items not deleted on qvm-remove

**Describe the solution you'd like**

qubesadmin.tools add-on for removal of deleted app menu items

**Where is the value to a user, and who might that user be?**

N/A

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

N/A

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

N/A

**Comment by andrewdavidwong** [comment]
Application Menu shortcut entries should already be handled automatically whenever a VM is removed. If they are not, then that is a bug in the existing functionality. Please report it. We do not need a new feature to make up for a bug in existing functionality. Instead, we just need to fix the existing bug.
