### ISSUE TITLE
Domains widget and manager do not realize a qube has finished starting

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#6176]
**Qubes OS version**

`Qubes release 4.0 (R4.0)`

**Affected component(s) or functionality**

Qubes manager and domains widget

**Brief summary**

Sometimes, a VM appears to still be starting, even long after it has started.

**To Reproduce**

I don’t have a good reproduction case, though it often reproduces on my laptop.  I suspect the problem to be due to a race condition.

**Expected behavior**
All started VMs appear to be started.

**Actual behavior**
A VM will appear to be in the starting state long after it has started.

**Screenshots**

**Additional context**
I suspect this is either a race condition or a lost update.  It could be a result of checking the status of VMs before watching for state changes.

**Solutions you've tried**
Restarting the widget helps, but loses the indicators that some AppVMs need to be restarted.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

N/A

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

None

**Comment by marmarta** [comment]
Hmm, do you get notifications "[VM] has started" for those VMs? Or just "[VM] is starting"?

**Comment by DemiMarie** [comment]
Not sure.  I will keep a look out.  The problem only arises at dom0 boot, so it isn’t easy to reproduce.

**Comment by ddevz** [comment]
Semi-Repeatable:  In 4.1, starting a system with 10 auto-start qubes causes, on average, one of the 10 qubes to be in a perpetual "starting" state in the "Qubes domains" widget even though the qube actually started and can be interacted with.

However, this differs from the original report in that "Qube Manager" *does* show the VM as having started.

Also, "Qubes domains" widget seems to occasionally "loose" a domain, where the domain does not show at all in "Qubes domains" widget (but does show in "Qube Manager")

Perhaps some way for it to reread the whole list every once in a while to resync things?

(If this should be a separate bug report let me know.)

**Comment by brendanhoar** [comment]
In the past, with R4.0, I added 10-15s sleeps in scripts between starts when starting many VMs together, mostly due to failed starts->VM halts and/or failed starts->indeterminate state. I never did track down the issue.

B

**Comment by ddevz** [comment]
Update #1:  it looks like domains that are entirely missing from qubes domains widget also happen on a semi-regular basis when there are 13 auto-start VMs.  They are just less obvious since you don't see them in the list.  

update #2: domains that are in qube manager, but are missing in the qubes domains widget are also missing from the list of domains that the USB widget is allowed to forward USB devices to.
