### ISSUE TITLE
Switching to VM Kernel from QubesOS Kernel

### ISSUE THREAD

**Issue by bluesteal** [QubesOS/qubes-issues#6178]
**Qubes OS version**

R4.0

**Affected component(s) or functionality**

Switching to Debian Kernel in AppVM

**Brief summary**

When attempting to switch to Debian Kernel with Whonix-ws getting an error message. Tried following 

http://qubesosfasa4zl44o4tws22di6kepyzfeqv3tg4e3ztknltfxqrymdad.onion/doc/managing-vm-kernel/

qvm-prefs <clonetemplatename> virt_mode hvm
qvm-prefs <clonetemplatename> kernel ''

This resulted in 

“Cannot connect to qrexec agent” error

Checked the logs for errors but there was no indication of what the error was

**To Reproduce**

1. 
2. 
3. 

**Expected behavior**

**Actual behavior**

**Screenshots**

**Additional context**

Trying to test out some of the security features of non-Qubes Whonix as per:

https://forums.whonix.org/t/qubes-whonix-security-disadvantages-help-wanted/8581

**Solutions you've tried**

Instead of copying and changing the templateVM maybe a better solution would be to run a VM containing Whonix inside the AppVM 

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

http://qubesosfasa4zl44o4tws22di6kepyzfeqv3tg4e3ztknltfxqrymdad.onion/doc/managing-vm-kernel/
http://qubesosfasa4zl44o4tws22di6kepyzfeqv3tg4e3ztknltfxqrymdad.onion/doc/vm-troubleshooting/#vm-kernel-troubleshooting

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

**Comment by bluesteal** [comment]
https://github.com/QubesOS/qubes-issues/issues/5212

**Comment by SaswatPadhi** [comment]
Hello,

I had previously run into this issue as well. There is a step missing on the "[Managing VM kernels](https://www.qubes-os.org/doc/managing-vm-kernels/)" manual page, which is: `grub2-install /dev/xvda`.

Try booting with the dom0 kernel, then run:
```console
$ sudo grub2-install /dev/xvda
$ sudo grub2-mkconfig -o /boot/grub2/grub.cfg
```
then switch back to the VM kernel and it should boot as expected.

**Comment by SaswatPadhi** [comment]
The linked PR is waiting for a review. Please take a look; it's a relatively small and simple change.
