### ISSUE TITLE
USB Stick Solution

### ISSUE THREAD

**Issue by ethanchinaski** [QubesOS/qubes-issues#6179]
I had the problem that neither the dd copy method on Linux or the Rufus Instructions on windows produced a UEFI USB Stick which i could use  to install Qubes. Only the 2nd partition was on the stick but not the large one (over 4 GB) .
i tried several different Tools ( balena Etcher, yumi and so on) but none of them worked.

My workaround is simple but effective and does not cause any security issues.
Instead of dd copying the Iso on a USB Stick on linux, i used the gnome-disk-utility for this purpose and it finally led to a perfect partitioned and working install medium
just select the USB Stick and choose the option to restore the drive, then chose the ISO.
it is then after the stick was made also possible to mount the boot partition and modify the conf file for the known UEFI boot problems.

i guess many others had this problem and struggled or even gave up by believing they did something wrong which is not true. something on a number of USB sticks from different Brands seem to block the dividing of the stick in to multiple partitions. only the gnome tool does the trick then

Hope someone find this useful and i could be of help in this case.

Kindest regards
Ethan Chinaski

**Comment by PROTechThor** [comment]
@ethanchinaski Thanks for documenting this. I think this should be added to the troubleshooting docs. 

Not sure if it should go on [USB Troubleshooting](https://www.qubes-os.org/doc/usb-troubleshooting/) or [Installation Troubleshooting](https://www.qubes-os.org/doc/installation-troubleshooting/#trouble-installing-from-usb-stick). 

Thoughts, @andrewdavidwong ?

**Comment by andrewdavidwong** [comment]
> Not sure if it should go on [USB Troubleshooting](https://www.qubes-os.org/doc/usb-troubleshooting/) or [Installation Troubleshooting](https://www.qubes-os.org/doc/installation-troubleshooting/#trouble-installing-from-usb-stick).
> 
> Thoughts, @andrewdavidwong ?

Hm, probably Installation Troubleshooting, or, if it's really common, directly in the Installation Guide, in this section:

https://www.qubes-os.org/doc/installation-guide/#copying-the-iso-onto-the-installation-medium

By the way, I just noticed that the Installation Troubleshooting page doesn't appear to be linked from the Installation Guide at all, which means that the people who need it the most are unlikely to find it at the time when they need it.

**Comment by ethanchinaski** [comment]
are you guys later able to close this issue ( even if its not an issue) by yourself or need me to close it later on ?

**Comment by GWeck** [comment]
On my machine (Windows 7 with Rufus 2.5 and 3.8), the needed partitions are both on the installation USB stick, but the boot partition is not set to "active", although Rufus is told to copy the installation iso using `dd`.

The fix is to set the active bit using some other tool, like `gparted `on a Linux system, after creating the USB installation media. After setting this bit, the stick boots fine.

**Comment by PROTechThor** [comment]
@GWeck @ethanchinaski 

Do you think [this pull request](https://github.com/QubesOS/qubes-doc/pull/1073) handles this issue?

**Comment by GWeck** [comment]
Currently, I don't see the active bit issue menrioned in the installation trouble guide. I think, it should be mentioned there.

**Comment by PROTechThor** [comment]
> Currently, I don't see the active bit issue menrioned in the installation trouble guide. I think, it should be mentioned there.

@GWeck I think I did mention it in the PR: https://github.com/QubesOS/qubes-doc/pull/1073/files

**Comment by GWeck** [comment]
Sorry - I did not see it there! So, that's fixed.

**Comment by ethanchinaski** [comment]
many thanks for acting that fast, one reason more to stay with Qubes. you guys are a great team and i appreciate your work.
