### ISSUE TITLE
Mouse clicks ignored when changing screen layout with already running Qube

### ISSUE THREAD

**Issue by ptitdoc** [QubesOS/qubes-issues#6185]
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
mouse

**Brief summary**
After extending the screen, If I put a windows **completely** into the second screen, mouse clicks on the windows content won't work.

I don't remember if it has been discussed in the past as I cannot find the issue. Basically, I think that the GUI agent inside my Qubes don't know that the screen has been enlarged and don't know what to do with mouse clicks outside the known windows frame. If I start or restart a Qube after having extended my windows, it will work properly.

Please note that this does not affects keyboard input.

**To Reproduce**

1. Start a Qube
2. Extend your screen using a secondary screen
3. Start any graphical tools with widgets / buttons
4. Move the window completely to the secondary screen
5. Try to click, right click ... on any buttons of the window to see that there is no effects.

**Solutions you've tried**
Restart the Qube after extending the screen.

**Comment by marmarek** [comment]
Take a look at https://www.qubes-os.org/doc/gui-configuration/

**Comment by ptitdoc** [comment]
Thanks I will try out, but I don't think it is related to video issues. The video is working properly on both screens, only I cannot interact with GTK widgets inside the window (I can interact with window border). It's like the VM mouse pointing coordinates are wrong because the qube don't know about a second screen and think the mouse is out of borders.

I will try running the VM in debug mode to give you more insights.

By the way my external screen is configured as primary. I will see if it has an impact on the bug.

**Comment by ptitdoc** [comment]
Sorry I missed the FAQ in https://www.qubes-os.org/doc/gui-troubleshooting/:

> Can’t click on anything after connecting 4k external display

Even if it makes little sense to me (why video RAM is needed for clicking?) it seems to solves the problem.

And a google search ends on this page... I only looked at issues somehow. Sorry for bothering you.
