### ISSUE TITLE
Using qubesctl to update templates results in traceback mentioning qubes-vm-connector

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#6189]
**Qubes OS version**

`R4.0`

**Affected component(s) or functionality**

salt, qubes-vm-connector?

**Brief summary**

Using qubesctl to update templates results in traceback mentioning qubes-vm-connector.

**How Reproducible**

Only started observing today. Observed three times in a row immediately following two normal updates in a row.

**To Reproduce**

```
sudo qubesctl --show-output --skip-dom0 --templates --max-concurrency 1 state.sls update.qubes-vm
```

**Expected behavior**

Normal update text.

**Actual behavior**

```
<vm_name>:
      ----------
      _error:
          Failed to return clean data
      retcode:
          1
      stderr:
          Traceback (most recent call last):
            File "/usr/lib/qubes-vm-connector/ssh-wrapper/ssh", line 101, in <module>
              sys.exit(main())
            File "/usr/lib/qubes-vm-connector/ssh-wrapper/ssh", line 94, in main
              return ssh(args)
            File "/usr/lib/qubes-vm-connector/ssh-wrapper/ssh", line 29, in ssh
              assert args[1] == '/bin/sh'
          AssertionError
      stdout:
```

**Additional context**

I normally run this qubesctl command five times in a row on a semi-daily basis. This is the first time I've observed this particular error. It happened on 3/5 of the runs (the last three).

**Solutions you've tried**

N/A

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

N/A

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

None found.

**Comment by conorsch** [comment]
Hey @andrewdavidwong, this sounds like the same issue reported in #6188. Could you check what the following commands show?

*  `qubes-prefs default_template` 
* `qvm-prefs default-mgmt-dvm template`

I'm guessing both will be `fedora-31`, or something else newer than `fedora-30`. Could you confirm?

**Comment by andrewdavidwong** [comment]
> Hey @andrewdavidwong, this sounds like the same issue reported in #6188. Could you check what the following commands show?
> 
> * `qubes-prefs default_template`
> * `qvm-prefs default-mgmt-dvm template`
> 
> I'm guessing both will be `fedora-31`, or something else newer than `fedora-30`. Could you confirm?

Yep, they're both based on fedora-32-minimal.

Thanks for the pointer. Closing as a duplicate of #6188.
