### ISSUE TITLE
Qubes Manager feature for prioritizing VM scheduling

### ISSUE THREAD

**Issue by tlaurion** [QubesOS/qubes-issues#6190]
**The problem you're addressing (if any)**

Videoconference lagging, choppy video, choppy audio

**Describe the solution you'd like**

Option to let users prioritize "Videoconf" or other AppVMs from QubesOS manager, seeing at a glance the priority of other AppVMs from the overview and sorting the column by this field.

On dom0 backend, resulting call to be done would be to apply `xl sched-credit -d AppVM -w WeightBetween_1_and_65535`

**Where is the value to a user, and who might that user be?**

Be able to enforce priority between VM to enforce QoS assurance. I do not know anybody that would choose compile time over Videoconf call quality.

**Describe alternatives you've considered**

Pausing active VM until call is finished...

**Additional context**

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

man xl exerpt:
```
       sched-credit [OPTIONS]
           Set or get credit scheduler parameters.  The credit scheduler is a
           proportional fair share CPU scheduler built from the ground up to
           be work conserving on SMP hosts.

           Each domain (including Domain0) is assigned a weight and a cap.

           OPTIONS

           -d DOMAIN, --domain=DOMAIN
               Specify domain for which scheduler parameters are to be
               modified or retrieved.  Mandatory for modifying scheduler
               parameters.

           -w WEIGHT, --weight=WEIGHT
               A domain with a weight of 512 will get twice as much CPU as a
               domain with a weight of 256 on a contended host. Legal weights
               range from 1 to 65535 and the default is 256.

```

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

#1322 #1404 #5628 #5086

**Comment by tlaurion** [comment]
@marmarta ?

**Comment by marmarek** [comment]
By changing scheduling parameters it is way easier to make your system completely unusable than to actually fix something.
If you really know what you are doing, you'll manage do make that one `xl` call when you really need it.

As for choppy audio/video, I bet the answer is different - this particular thing works quite poor in Firefox, but works fine in Chromium. In the very same VM, with the very same parameters. But also, make sure you're not running out of RAM (try closing some other application to free some if necessary) - swapping can degrade application performance quite a lot.

**Comment by andrewdavidwong** [comment]
It sounds like this is a "won't do." If anyone has a new reason for why this should be done, please leave a comment, and we'll be happy to take another look. Thank you.
