### ISSUE TITLE
qubes-tunnel: Port forwarding

### ISSUE THREAD

**Issue by Warthog-Capital** [QubesOS/qubes-issues#6194]
**The problem you're addressing (if any)**
My VPN allows forwarding incoming connections on certain ports (aka port forwarding). If I run the VPN client directly in my AppVM, port forwarding works and my application can be reached from the outside. The [qubes-tunnel](https://github.com/QubesOS-contrib/qubes-tunnel) contrib package does not allow port forwarding so it doesn't allow the user to run servers or P2P applications that require open ports through the tunnel.

**Describe the solution you'd like**
Allow the user to configure a list of TCP+UDP ports on which incoming connections will be forwarded to the AppVM, and extend the docs to show how to make the AppVM allow incoming connections from sys-vpn on those ports.

**Where is the value to a user, and who might that user be?**
Any user who wants to run servers or P2P applications behind a VPN, for example a torrent client.

**Describe alternatives you've considered**
Users who want to do this can not use the qubes-tunnel package and need to run the VPN client directly inside the AppVM, without the security benefits of a split setup.

**Additional context**
Posted on the Qubes Discourse and Reddit, but nobody was able to help:

- https://www.reddit.com/r/Qubes/comments/jn9opj/need_help_forwarding_vpn_ports_through_qubestunnel/gb06tk6/
- https://qubes-os.discourse.group/t/need-help-forwarding-ports-through-qubes-tunnel/1357

I am using Debian 10 as sys-vpn because the qubes-tunnel package is not available for the F32 template yet.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

I tried transferring the [article on port forwarding in the Qubes docs](https://www.qubes-os.org/doc/firewall/#port-forwarding-to-a-qube-from-the-outside-world) to qubes-tunnel, but failed. I don't want to accidentally break the security of qubes-tunnel by messing around with the firewall rules without knowing what I am doing.

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
None that I am aware of.

**Comment by DemiMarie** [comment]
I can think of two options here:

1. Use a patched OpenSSH.  This will give very good performance, at the expense of maintenance burden.
2. Use a stock OpenSSH.  This comes at a performance hit due to the encryption required.

**Comment by Warthog-Capital** [comment]
> I can think of two options here:
> 
>     1. Use a patched OpenSSH.  This will give very good performance, at the expense of maintenance burden.
> 
>     2. Use a stock OpenSSH.  This comes at a performance hit due to the encryption required.

Sorry, could you elaborate how this would help with port forwarding? As far as I am understanding, the only problem is setting the right firewall rules.

Btw., since nobody answered I have tried to research this again and found that the following changes might be helpful:

In sys-vpn, create a file at **/rw/config/qubes-firewall.d/91_port-forwarding** with the following content:
```
iptables -A INPUT -i tun+ -p tcp --dport PORTNUMBERHERE -j ACCEPT
iptables -A INPUT -i tun+ -p udp --dport PORTNUMBERHERE -j ACCEPT
```
(here PORTNUMBERHERE is to be replaced with the actual port number that should be forwarded). According to my understanding, this will accept new connections that are coming in via the tunnel interface.

However, this doesn't seem to solve the issue, yet. Any ideas how to make progress from here?

**Comment by DemiMarie** [comment]
> > I can think of two options here:
> > ```
> > 1. Use a patched OpenSSH.  This will give very good performance, at the expense of maintenance burden.
> > 
> > 2. Use a stock OpenSSH.  This comes at a performance hit due to the encryption required.
> > ```
> 
> Sorry, could you elaborate how this would help with port forwarding? As far as I am understanding, the only problem is setting the right firewall rules.

I was considering port forwarding over qrexec, sorry!

**Comment by Warthog-Capital** [comment]
Yay, I have finally made it to work! :) Based on the script from Joeviocoe: https://gist.github.com/Joeviocoe/6c4dc0c283f6d6c5b1a3f5af8793292b

In sys-vpn: **/usr/local/bin/portforwarding.sh**
```
#!/bin/bash

if [ "$#" -ne 3 ]; then
        echo "Usage: sudo portforwarding.sh <AppVM IP> <tcp/udp> <port>"
        exit
fi

# variables
to_ip=$1
type=$2
port=$3

iptables -I INPUT -i tun+ -p $type --dport $port -j ACCEPT
iptables -t nat -A PREROUTING -i tun+ -p $type --dport $port -j DNAT --to-destination $to_ip
iptables -I FORWARD 5 -i tun+ -p $type -d $to_ip --dport $port -m conntrack --ctstate NEW -j ACCEPT
nft add rule ip qubes-firewall forward meta iifname tun0 accept
```

In sys-vpn: **/rw/config/qubes-firewall-user-script**
```
/usr/local/bin/portforwarding.sh <AppVM IP> tcp <port>
/usr/local/bin/portforwarding.sh <AppVM IP> udp <port>
```

In the AppVM: **/rw/config/rc.local**
```
iptables -I INPUT 6 -p tcp --dport <port> -m conntrack --ctstate NEW -j ACCEPT
iptables -I INPUT 6 -p udp --dport <port> -m conntrack --ctstate NEW -j ACCEPT
```

This seems to work fine, even across restarts. The only problems I am seeing with this solution are:

1. Not sure if the "nft add" rule is necessary. `tun0` needs to be stated explicitly because nft does not accept the `tun+` syntax
2. AppVM accepts connections from ANY other AppVM now as far as I understand? The problem with using -s here is that the source IP is the original IP from external nodes connecting via the tunnel, so I don't know how to only accept traffic that was routed via sys-vpn, but not traffic from other AppVMs.
