### ISSUE TITLE
qvm-run works with any VM parameter

### ISSUE THREAD

**Issue by 3hhh** [QubesOS/qubes-issues#6197]
**Qubes OS version**

4.0

**Affected component(s) or functionality**

`qvm-run`

**Brief summary**

`qvm-run` accepts any VM parameter, even non-existing VMs.

**How Reproducible**

Always.

**To Reproduce**

```
qvm-run broken
echo $?
```

**Expected behavior**

A non-zero exit code and an error message indicates incorrect usage.

**Actual behavior**

A zero exit code is set, no message at all.

**Notes**

I guess this bug occured as qvm-run can also accept a command as only parameter with `--all` or `--dispvm`.

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

None.

**Comment by marmarek** [comment]
This gets interpreted as "run `broken` command on no VM"...
