### ISSUE TITLE
Integrated mic on X1 Carbon 7th Gen not working anymore since 4.0.3

### ISSUE THREAD

**Issue by silentresearch** [QubesOS/qubes-issues#6198]
### Qubes OS version:
R4.0

### Affected component(s) or functionality:
integrated mic on Lenovo X1 carbon Gen 7 

---

### Steps to reproduce the behavior:
Attached integrated mic to different VMs and tried with Telegram and Jitsi meet. 

### Expected or desired behavior:
integrated mic should capture sounds

### Actual behavior:
integrated mic doesn't capture any sounds.

### General notes:
Mic gets detected just fine but fails to capture any sounds. Tested on Debian 10 and Fedora 32 VMs with jitsi meet, telegram and some other browser based mic tests. 
It worked just fine until 4.0.3 update.
The mic itself works too - verified with elementary os live.

---

### I have consulted the following relevant [documentation](https://www.qubes-os.org/doc/):
https://www.qubes-os.org/doc/pci-devices/
https://www.qubes-os.org/doc/newer-hardware-troubleshooting/
https://www.qubes-os.org/doc/thinkpad-troubleshooting/
https://www.qubes-os.org/doc/pci-troubleshooting/

**Comment by silentresearch** [comment]
The issue appears to be related to the new linux kernel. Other owners of the notebook have reported similar issues with the integrated mic. It seems to work fine out of the box on Ubuntu 20.x.

**Comment by 1osdfkjo12sdfa** [comment]
@silentresearch does your sound work if you attach an external mic ?
