### ISSUE TITLE
Fedora32 Template Constantly Needing Updates

### ISSUE THREAD

**Issue by straussmaus** [QubesOS/qubes-issues#6204]
**Qubes OS version**
R4.01

**Affected component(s) or functionality**
Fedora32 Template

**Brief summary**
The newly installed fedora32 template needs extremely frequent updates, including immediately after successfully completing an update.

**How Reproducible**
Install the fedora32 standard template (https://www.qubes-os.org/news/2020/06/30/fedora-32-templates-available/)

See that it always needs an update.

Update.

Within a very short time, it will need another update.

Do this for weeks.  It still needs very frequent updates.

**Expected behavior**
I expect fedora32 to act like other templates and need updates every few days but not many times per day.

**Actual behavior**
Fedora32 Template Constantly Needing Updates

**Additional context**
Manually running updates does not suggest any problems.  The updates complete successfully.

Is there something within a template that waits/groups updates together?  Maybe this feature is disabled on fedora32?  So the problem is not that there are more updates, but that the scheduler is off?  Why do other templates only need updating once or twice per week?

**Solutions you've tried**
Manual updates, verifying disk space is sufficient, checking network connectivity.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

https://www.qubes-os.org/news/2020/06/30/fedora-32-templates-available/

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
None (https://github.com/QubesOS/qubes-issues/issues?q=fedora32)

**Comment by andrewdavidwong** [comment]
It sounds like this is purely concerned with the inner workings of Fedora 32, i.e., the frequency with which Fedora package updates become available to the Fedora package manager, `dnf`. Since this is entirely outside of the control of the Qubes OS Project and does not involve any Qubes code, we strongly suggest searching for normal Fedora solutions and/or reporting this to Fedora's issue tracker. Therefore, I'm closing this as "not our bug." If you believe this is a mistake, please leave a comment, and we'll be happy to take another look. Thank you.

**Comment by straussmaus** [comment]
I reinstalled the Fedora32 template and found that the errors seem to be connected to qubes repos.  Since the update happens in an xterm I'm not sure how to copy to the dom0 clipboard (usually in xterm you just highlight, then click both mouse buttons to paste, but what is the qubes clipboard equivalent of clicking both mouse buttons?)

Here is something I transcribed:

```
Problem 4: problem with installed package qubes-vm-recommended-4.0.7-1.fc32.noarch
	- package (same) requires pulseaudio-qubes, but none of the providers can be installed
```

**Comment by andrewdavidwong** [comment]
> @andrewdavidwong
> 
> I reinstalled the Fedora32 template and found that the errors seem to be connected to qubes repos. Since the update happens in an xterm I'm not sure how to copy to the dom0 clipboard (usually in xterm you just highlight, then click both mouse buttons to paste, but what is the qubes clipboard equivalent of clicking both mouse buttons?)
> 

I don't know. I used to be able to copy from xterm using the middle click menu, but that stopped working some time ago. If you figure it out, let me know. Maybe I'll ask on qubes-users to see if anyone knows.

> Here is something I transcribed:
> 
> ```
> Problem 4: problem with installed package qubes-vm-recommended-4.0.7-1.fc32.noarch
> 	- package (same) requires pulseaudio-qubes, but none of the providers can be installed
> ```
> 
> It must be reproducible because I did nothing to the Qube except try to update it, after installing with `$ sudo qubes-dom0-update qubes-template-fedora-32`

That sounds like it might be (related to) https://github.com/QubesOS/qubes-issues/issues/6234.

**Comment by straussmaus** [comment]
> That sounds like it might be (related to) #6234.

Maybe.  But it is a discrete bug that the updater completes with a green check mark, even though it continues to require an update for the same reasons as before the most recent update.

**Comment by andrewdavidwong** [comment]
> Maybe. But it is a discrete bug that the updater completes with a green check mark, even though it continues to require an update for the same reasons as before the most recent update.

That should be a separate bug report, then.

**Comment by straussmaus** [comment]
> That should be a separate bug report, then.

It is.  This here is that bug report.  The others are what you were referencing.

Anyway I find that this problem is resolved on my system within the last few days.  It is *now* appropriate to close this issue.

**Comment by andrewdavidwong** [comment]
> > That should be a separate bug report, then.
> 
> It is. This here is that bug report. The others are what you were referencing.
> 

No, because that's not what this report is describing.

> Anyway I find that this problem is resolved on my system within the last few days. It is _now_ appropriate to close this issue. (Also #6276 is more or less a duplicate, and still need attention.)

Based on the discussion of #6276, it appears to have been closed appropriately, in which case no further attention is needed. In any case, a request to consider reopening an issue should be made in a comment on *that* issue.
