### ISSUE TITLE
Kernel panic in dom0 after upgrade to 4.19.155

### ISSUE THREAD

**Issue by zet9** [QubesOS/qubes-issues#6210]
**Qubes OS version**
Latest stable with all updates installed.

**Affected component(s) or functionality**
Dom0 kernel, initramfs, updater.

**Brief summary**
After latest dom0 upgrade the system won't boot anymore and kernel panic is shown on boot:
Kernel panic - not syncing: VFS: Unable to mount root fs on unknown-block(0,0)
And system restarts.
The newly generated initramfs during the update is significantly smaller in size than the previous ones:
-rwx------  1 root root 32315402 okt 27 15:47 initramfs-4.19.152-1.pvops.qubes.x86_64.img
-rwx------  1 root root 22940570 nov 16 21:30 initramfs-4.19.155-1.pvops.qubes.x86_64.img
-rwx------  1 root root 32297694 okt 27 15:45 initramfs-4.19.94-1.pvops.qubes.x86_64.img
As the root fs is encrypted LUKS stored on nvme drive, is it possible that the initramfs doesn't include the modules needed to access it? 

**How Reproducible**
On my system 100%
System info: Asus P8Z68V-Pro Gen3, BIOS 3802, i7-3770, SSD SATA and NVMe drives.

**To Reproduce**
Install Qubes OS 4.0.3 and the available updates, make sure you have kernel 4.19.152 and then try to upgrade to any newer kernel, observe.

1. Install Qubes OS 4.0.3 and the available updates
2. Make sure you have kernel 4.19.152
3. Try to upgrade to any newer kernel, observe

**Expected behavior**
Normal boot

**Actual behavior**
Kernel panic on dom0 boot

**Screenshots**

**Additional context**

**Solutions you've tried**
This issue occured for me also in the past in any of the previous attempts to upgrade kernel to kernel-latest or kernels from the testing repo. I tested with root fs on nvme drive and on sata ssd drive, both caused kernel panic there was no way around it found. 
I tried to recreate the initramfs using dracut but no difference.
I tried to dig into the initramfs to find what's missing there but ran out of time later.
Online search inidicates that the (possibly corrupted or incomplete) initramfs is the root cause.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
Not such documentation found

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
Not found

**Comment by marmarek** [comment]
Looks like you've run out of disk space in /boot during update.

**Comment by DemiMarie** [comment]
The real problem, IMO, is that modifications to `/boot` are not transactional.

**Comment by marmarek** [comment]
@zet9 you can regenerate initramfs with (use full path to initramfs file):

    dracut -f initramfs-4.19.155-1.pvops.qubes.x86_64.img 4.19.155-1.pvops.qubes.x86_64

Is that EFI or legacy boot?

**Comment by zet9** [comment]
I checked the available space in /boot and there is plenty (800 MB) free.

It's EFI boot.

Manual recreation of the initramfs doesn't help, still kernel panic on boot with the same cause.
Attaching output from the generated initramfs file:
[lsinitrd-4.19.155-1.pvops.qubes.x86_64.txt](https://github.com/QubesOS/qubes-issues/files/5556355/lsinitrd-4.19.155-1.pvops.qubes.x86_64.txt)

**Comment by marmarek** [comment]
If it's efi, then take a look at `/boot/efi/EFI/qubes/initramfs*.img` (and free space there)

**Comment by zet9** [comment]
I checked there as well, still about 100 MB free space.

I also copied the manually created initramfs there and checked it will be picked on next boot.

**Comment by zet9** [comment]
Thanks for all the effort, the updates and fixes so far!

I have in the meantime uninstalled 4.0.3, got new disk and performed fresh installation of 4.1 using the alpha ISO and followed by all the subsequent updates. There were at least two new kernels (in the 5.4.x line) on 4.1 since the initial install and both installed properly.

I wasn't able to exactly pinpoint the original source of the problem. After uninstalling the 4.0.3, while fiddling with the machine, trying to install other OS's, I noticed that there was something wrong the the old EFI partition.

I remember that before the original install of 4.0.3 I tried to resize the existing EFI partition from about 100 MB to about 1 or 2 GB so all the (multiboot) loaders would fit. I did the whole EFI resize using gparted. The partition resize itself went OK, but I think there was some error reported while resizing the filesystem, something like that I need to do this from Windows or so like, not sure exactly anymore. 

After that I mounted and checked the EFI but it looked OK to me, the old data was still there, however I'm not exactly sure if it also reported bigger size. I tried to look in Windows if I can do something about it but I found no tool to do that and the EFI itself is hardly accessible from Windows itself anyway. The recovery console didn't work for me (reported some Windows version mismatch and exited) so I stopped there and just starting using the EFI partition as I didn't want to reinstall Windows.

The machine worked OK, the other boot loaders were still usable, but then this kind of problems started with Qubes loading. I did all the filesystem checks and free space checks and it all went OK. I double checked the initramfs contents. Forced initramfs creation and copied everything to place. I reinstalled whole Qubes few times, after installation there was no problem but after kernel update, it broke. I concluded there was problem with Qubes or incompatibility with my machine and logged this issue.

At that time I didn't suspect EFI and I didn't put things to perspective but later when I finally reinstalled Windows and created new EFI partition from scratch I learned then how to properly resize EFI using the Windows recovery console, then it kind of clicked for me finally  especially when afterwards there were no more problems with Qubes loader anymore. I didn't try to install 4.0.3 anymore though.

For other people: if you need to resize EFI, you can first make enough space for it using gparted, but don't touch EFI from gparted, then reboot and use the Windows recovery console diskpart to the actual resize - first copy the current EFI files elsewhere, when delete the old partition from diskpart, create new partition with bigger size and copy files back.

**Comment by andrewdavidwong** [comment]
> I still don't know for sure if the potentially half-broken EFI filesystem was the actual root cause as I am also not sure if it really was broken. For me the 4.1 works perfectly now and I'm not going to downgrade to 4.0.3 anymore unless there is a real need to double check something.
> 
> Therefore I suggest, unless there are no more ideas to further work on this issue, to close this issue.

Ok, closing. If anyone else would like for this issue to be reopened, please leave a comment.
