### ISSUE TITLE
Qubes R4.0.3 x86_64 iso xserver broken

### ISSUE THREAD

**Issue by agowa** [QubesOS/qubes-issues#6211]
**Qubes OS version**
R4.0.3 Setup on USB using Rufus

**Affected component(s) or functionality**
xserver

**Brief summary**
When booting the installation media it the xserver failing to start.

**How Reproducible**
Always

**To Reproduce**

1. Enable CSM in Bios (without it it doesn't boot at all shows briefly a few (5-6) lines of text before it instantly reboots)
2. Boot the setup media

**Expected behavior**
Setup starting

**Actual behavior**
xserver fails to start and setup therefore never starts.

**Screenshots**

**Additional context**

Hardware:
* CPU: AMD Ryzen 7 3800X
* GPU: AMD Radeon RX 5700 XT
* Motherboard: Gigabyte X570 AORUS PRO (AM4)

Logfiles:
* [anaconda.log](https://github.com/QubesOS/qubes-issues/files/5556735/anaconda.log)
* [X.log](https://github.com/QubesOS/qubes-issues/files/5556737/X.log)
* [storage.log](https://github.com/QubesOS/qubes-issues/files/5556738/storage.log)
* [syslog](https://github.com/QubesOS/qubes-issues/files/5557504/syslog.txt)

**Solutions you've tried**
None, but I'd like to note that Archlinux boots successfully, so the mainline linux kernel should support the hardware in general. Also xserver is working there with it's default configuration.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

https://www.qubes-os.org/doc/installation-guide

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
none

**Comment by marmarek** [comment]
Can you also add a log with kernel messages - either `syslog` or `journal.log` file?

**Comment by marmarek** [comment]
You can also try 4.0.4-rc1 - it has newer kernel.

**Comment by agowa338** [comment]
[syslog](https://github.com/QubesOS/qubes-issues/files/5557504/syslog.txt)

**Comment by marmarek** [comment]
This log is fine. I see it doesn't even try to load `amdgpu` driver. I think similar issue was discussed already in https://github.com/QubesOS/qubes-issues/issues/5416#issuecomment-679564602 (similar hardware, different error).
It seems at least Linux kernel 5.3 is required, so Qubes 4.0.4-rc1 isn't enough (there is AFAIR 4.19.150).
If you are brave enough, you can try alpha build of Qubes 4.1:
https://ftp.qubes-os.org/iso/Qubes-R4.1.0-alpha20201014-x86_64.iso (and its signature https://ftp.qubes-os.org/iso/Qubes-R4.1.0-alpha20201014-x86_64.iso.asc)

**Comment by agowa338** [comment]
Can confirm, it works with the alpha.

**Comment by DemiMarie** [comment]
Should we include a newer kernel on the 4.0.4 release ISO?

**Comment by agowa338** [comment]
If it is possible, to include Linux kernel 5.3 into the stable release ISO, that would be great.
But as also an archlinux user I may be biased towards shipping the most recent stable kernel as possible (as time of writing 5.9.9), but I'm not in to the whole XEN topic until now, so I don't know how that will come into play...

**Comment by marmarek** [comment]
As a general policy, we only use LTS kernels as the default one. This means we could switch to 5.4 there. I'll test on some laptops I have here and in case of no issues, will upload it to the current-testing repo + the next 4.0.4-rc.

**Comment by Mario0x1** [comment]
I assume i had the same issue. Attempted the solution from #6004 but didnt work on both 403 and latest  4.0.4-rc1. I got rid of the nouveau error but the tmp/x.log still showed no initialized monitors( not sure if correct term). 

Now boots into the Installation GUI in the alpha.  Thanks!

Got an Ryzen 5 3700, an MSI B450 Tomahawk, GTX 1660S

I would be happy to test.  @marmarek

**Comment by Mario0x1** [comment]
Qubes OS 4.0.4-rc2 fixed this for me
