### ISSUE TITLE
Failing to set a property results in an unhelpful error message

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#6218]
**Qubes OS version**

`Qubes release 4.0 (R4.0)`

**Affected component(s) or functionality**

qubes-core-admin

**Brief summary**

Trying to set a `visible_*` property (such as `visible_gateway`) results in this less than helpful error message:

```
usage: qvm-prefs [--verbose] [--quiet] [--help] [--help-properties]
                 [--hide-default] [--get] [--set] [--default]
                 VMNAME [PROPERTY] [VALUE]
qvm-prefs: error: no such property: 'visible_gateway'
```

**How Reproducible**

100%

**To Reproduce**
Run `qvm-prefs sys-firewall visible_gateway <something>`.  Other read-only properties also work.

**Expected behavior**

A useful error message is shown, such as “Cannot change property 'visible_gateway' of AppVM”.

**Actual behavior**

The error message claims that the property does not exist.

**Screenshots**

**Additional context**

This is intended to prevent an information leak via the Admin API.  It’s okay to pretend a property does not exist if the calling VM doesn’t have permission to access it.

**Solutions you've tried**

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

**Comment by iamahuman** [comment]
This is probably due to `AttributeError` unintentionally leaking out of a property accessor.

**Comment by DemiMarie** [comment]
Indeed it is @iamahuman!  Fix coming.
