### ISSUE TITLE
Fedora-32-minimal template cannot be updated using Salt

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#6220]
**Qubes OS version**

`Qubes release 4.0 (R4.0)`

**Affected component(s) or functionality**

Minimal Fedora template

**Brief summary**

`fedora-32-minimal` cannot be updated using Salt, only via DNF.

**How Reproducible**

100%

**To Reproduce**
Try to update `fedora-32-minimal` using the GUI updates widget

**Expected behavior**

Update succeeds

**Actual behavior**

Update fails

**Screenshots**

**Additional context**

**Solutions you've tried**

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

**Comment by marmarek** [comment]
Do you have fedora-32 based management dispvm assigned for it (directly or globally)? Because of python version in fedora-32, quite recent salt is necessary, which is available in fedora-32

**Comment by unman** [comment]
On Sat, Nov 21, 2020 at 12:26:52PM -0800, Marek Marczykowski-G??recki wrote:
> Do you have fedora-32 based management dispvm assigned for it (directly or globally)? Because of python version in fedora-32, quite recent salt is necessary, which is available in fedora-32
> 

Debian-minimal has the same fault, I think.
I thought it had been decided that minimal templates could not be salted
without additional packages?

**Comment by marmarek** [comment]
It should be possible to salt minimal template. The minimal template (without extra packages) is just not suitable for the DispVM used for salt (management_dispvm property).

**Comment by unman** [comment]
On Sat, Nov 21, 2020 at 06:48:45PM -0800, Marek Marczykowski-G??recki wrote:
> It should be possible to salt minimal template. The minimal template (without extra packages) is just not suitable for the DispVM used for salt (management_dispvm property).
> 

You're right, of course.

**Comment by DemiMarie** [comment]
@marmarek duh, I forgot to change my management DVM from the default (which is currently a Debian VM).  Closing.
