### ISSUE TITLE
FATAL PAGE FAULT [error_code=0002]

### ISSUE THREAD

**Issue by NoNameoN-A** [QubesOS/qubes-issues#6223]
Hi everybody i’m trying to install your OS on my device but when i try to start your .iso (that i was installed on a pendrive using rufus and FAT32 system and DD option) from my BIOS (through press f12 becausei have a dell), i have a fatal error.
I think that the official error message is the following:
*******************************
Panic on CPU 0:
FATAL PAGE FAULT
[error_code=0002]
Faulting linear address:
*******************************

[Image](https://ibb.co/rbkTjrD)

**Comment by andrewdavidwong** [comment]
Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this does not appear to be suitable for `qubes-issues`. We ask that you please post this on the [`qubes-users` mailing list or forum](https://www.qubes-os.org/support/) instead. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a brief comment explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.
