### ISSUE TITLE
Qubes Builder ::: Install A Template From Linux Custom Via ISO/CDRom

### ISSUE THREAD

**Issue by cheznewa** [QubesOS/qubes-issues#6224]
Hello, is possible to add in qubes-builder, a option allow choose iso/cdrom for build template for a custom linux our choice.

**Comment by marmarek** [comment]
No, building a template is not just installing that distribution, but also building and installing various qubes-specific packages. The process is described at https://www.qubes-os.org/doc/building-non-fedora-template/
If you want a plain, non "qubeized" system in a VM, you can use this process: https://www.qubes-os.org/doc/standalone-and-hvm/

**Comment by cheznewa** [comment]
OK, But It's Not Easy From A HVM, Always Install Windows Than Linux ...

**Comment by fepitre** [comment]
> OK, But It's Not Easy From A HVM, Always Install Windows Than Linux ...
Why do you always install Windows? The provided link if for helping you installing whatever you want, not Windows specific. It's just an example. You can attach any iso you want and install it with usual steps. It could be difficult if you want to build Qubes specific source components into your "unknown" distribution.

**Comment by cheznewa** [comment]
> Why do you always install Windows?
Windows 7 Is Dead And Windows 10 Not Work Or Not Easy To Working

Here I Want Install Another Linux From ISO Image And Building The Agents.
If I Install From A ISO Linux As HVM And Install The Agents Precompiled From APT, Is Working ... **NOT** Each Window Show A Pattern With A Black Background.
