### ISSUE TITLE
Qubes 4.1, bullseye template, qubes-contrib repo, missing "bullseye" component in qubes-contrib-r4.1.list

### ISSUE THREAD

**Issue by 0rb677** [QubesOS/qubes-issues#6237]
**Qubes OS version**
4.1

**Affected component(s) or functionality**
qubes-template-debian-11

**Brief summary**
Malformed entry 2 in list file (component)  in `qubes-contrib-r4.1.list` repo

**To Reproduce**

sudo qubes-dom0-update --enablerepo=qubes-templates-itl-testing qubes-template-debian-11
qvm-copy debian-11 vpn-template
install `qubes-repo-contrib` on vpn-template

**Solutions you've tried**
Easy to fix, manually add component `bullseye` to `/etc/apt/sources.list.d/qubes-contrib-r4.1.list`
and uncomment `testing` repo
```
cat /etc/apt/sources.list.d/qubes-contrib-r4.1.list 
# Qubes contrib repository
deb https://contrib.qubes-os.org/deb/r4.1/vm bullseye main
#deb-src https://contrib.qubes-os.org/deb/r4.1/vm bullseye main

# Qubes contrib updates testing repository
deb [arch=amd64] https://contrib.qubes-os.org/deb/r4.1/vm bullseye-testing main
#deb-src https://contrib.qubes-os.org/deb/r4.1/vm bullseye-testing main
```
Then you can install `qubes-tunnel`.

**Comment by fepitre** [comment]
Fix on the road :)

**Comment by 0rb677** [comment]
@fepitre thanks! :)
