### ISSUE TITLE
Mention OpenGL's software fallback (llvmpipe) in FAQ, which is good enough for basic games and gamedev

### ISSUE THREAD

**Issue by AlxHnr** [QubesOS/qubes-issues#6241]
**The problem you're addressing (if any)**

The documentation implies there is no OpenGL support at all. This is misleading and may put off people with basic needs (homework, game jams). AppVMs default to llvmpipe, which is a full-blown software implementation supporting shaders and more. It is definitely good enough for 2D games and simple 3D demos on systems with enough cores.

**Describe the solution you'd like**

Something like this:

```diff
 However, Qubes does allow for the use of accelerated graphics (OpenGL) in Dom0’s Window  Manager, so all the
 fancy desktop effects should still work.
+
+ **Note**: AppVMs will use a software implementation of OpenGL as a fallback, which may be good enough for
+ basic 2D/3D applications, depending on your CPU.
```

**Where is the value to a user, and who might that user be?**

Students, hobbyists, indie developers. Everybody who would otherwise have to spin up a second machine, without even trying what AppVMs can already do.

**Describe alternatives you've considered**

_none_

**Additional context**

_none_

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

_none_

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

Many games like are unplayable due to broken mouse controls: #4986

**Comment by andrewdavidwong** [comment]
In case you (or any others reading this) are not already aware, the documentation is a community effort, and everyone is welcome to contribute. (That's how things like this get updated!) So, if you'd like to get involved with the project, this is a great way to do it. You can read more about how to submit documentation changes here:

https://www.qubes-os.org/doc/doc-guidelines/
