### ISSUE TITLE
mgmt-salt commit 0f25aea482ea27e15ac7568aa7b9d3a9d9df1be9 has no signed tag

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#6243]
**Qubes OS version**

`Qubes release 4.0 (R4.0)`

**Affected component(s) or functionality**

`qubes-builder`

**Brief summary**

https://github.com/QubesOS/qubes-mgmt-salt/commit/0f25aea482ea27e15ac7568aa7b9d3a9d9df1be9 doesn’t have a tag pointing at it, although the commit itself is signed.  This causes qubes-builder to complain.

The commit itself is signed by @marmarek’s key, so there is no security problem.

**Comment by fepitre** [comment]
Yes that's why CI is also broken. I've noticed @marmarek. Waiting for him to sign :)

**Comment by DemiMarie** [comment]
Fixed.
