### ISSUE TITLE
Qube Manager VM Settings window width unwantedly expands depending on the character length of the "kernelopts" line

### ISSUE THREAD

**Issue by Kreyren** [QubesOS/qubes-issues#6247]
This issue affects Qube Manager GUI.

### Steps to reproduce
1. Invoke `qvm-prefs -s <VMNAME> kernelopts "whatever long here"`
2. Open `Qube Manager`, navigate to settings of `<VMNAME>` and notice it's minimum lenght expanding depending on value of `kernelopts`.

### Expected

Do not expand as that makes the UI painful to use e.g. requiring to drag from the edges of the screen multiple times to reach the desired UI.

---

NOTE: This is the minimum lenght of the UI that cannot be resized in smaller and more managable window.
![2020-12-02_04-06](https://user-images.githubusercontent.com/11302521/100823390-6b7a3380-3454-11eb-9024-2bdea37d0303.png)

---

This **seems to be** the relevant codeblock.
https://github.com/QubesOS/qubes-manager/blob/0ba5ea648fed59ba7b742667bf6f4c2eb8731806/qubesmanager/settings.py#L796

**Comment by marmarta** [comment]
@marmarek , can I make some assumptions like "kernel opts won't have space-less substrings longer than 80 characters"?
