### ISSUE TITLE
Add "restart" to Domain Widget

### ISSUE THREAD

**Issue by ejose19** [QubesOS/qubes-issues#6249]
**The problem you're addressing (if any)**
Domain Widget is missing "Restart" action, which is not in sync with Qube Manager actions (start is not needed in Domain Widget, as it only show VMs that are running)

**Describe the solution you'd like**
Adding the action after shutdown (to be in the same order as Domain Widget)

**Where is the value to a user, and who might that user be?**
When needing to restart AppVMs, it would be of great help to have this quick restart way instead of launching/using the qube manager, as when having many qubes it's slow to launch / slower to find the vm in all the list instead of the running vm list.

**Describe alternatives you've considered**
Using Qube Manager (with the drawbacks mentioned above)

**Additional context**

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

**Comment by JustMyGithub** [comment]
There is an issue with the current implementation. In qubes manager, a qube can be restarted even if other qubes are connected to it (e.g. if the are a netVM). In the domain widget the user gets an error notification.
