### ISSUE TITLE
Standard partitioning is broken

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#6252]
**Qubes OS version**

R4.1

**Affected component(s) or functionality**

installer

**Brief summary**

Installing with "standard partitions" (instead of LVM or btrfs) is broken. While this itself is not really useful, it is on the way to XFS using XFS filesystem.

**To Reproduce**

1.  Launch installation
2.  Select custom partitioning
3.  Choose automatic "Standard partitions" scheme

**Expected behavior**

Following partitions are created:
1. `/boot` - unencrypted
2. swap - encrypted
3. `/` - encrypted, 20GB
4. `/var/lib/qubes` - encrypted, the rest of the space

**Actual behavior**

Root partition is created tiny (about 2.5GB) and two actual partitions supposed to be / and /var/lib/qubes do not have mountpoint set.

**Screenshots**

https://openqa.qubes-os.org/tests/14044#step/install_partitioning_standard/25

**Additional context**

Reported by @rustybird in https://github.com/QubesOS/qubes-blivet/pull/12

Since standard partitions with ext4 are quite useless for qubes (because of lack built-in CoW feature), it may be better to ditch this option completely. Or replace with XFS (at least for `/var/lib/qubes`).

**Comment by DemiMarie** [comment]
Personally, I would prefer to deprecate and remove this option.  If it isn’t too difficult, we should continue to support using existing FILE pools so that in-place upgrades work, but I see no reason to support creating new ones.  The future is LVM/BTRFS/(someday) ZFS.

**Comment by marmarek** [comment]
Yes, standard partitions with ext4 should not be an autopart choice. But standard partitions with XFS can be - IIUC XFS does have a built-in support for CoW files, which `reflink` storage driver will use.
