### ISSUE TITLE
Arch Linux Template: pacman error: failed to init transaction (unable to lock database)

### ISSUE THREAD

**Issue by tsteinholz** [QubesOS/qubes-issues#6254]
**Qubes OS version**

R4.0

**Affected component(s) or functionality**

qubes-builer, arch linux template.

**Brief summary**

Suppose to build an Arch Linux template to use in Qubes OS.

**How Reproducible**

Have not been able to reproduce any other results.

**To Reproduce**

1. Follow the instructructions to build an Arch template.
2. gui-agent-linux-vm will fail due to Pulse core, this is fixable with a syslink.
3. make template will then fail
 

**Expected behavior**

To have a usable Arch Linux template vm.

**Actual behavior**

```
...earlier lines omitted....
--> Archlinux 01_install_core.sh
--> Archlinux prepare-chroot-base
  --> NB: INSTALLDIR '/home/user/qubes-builder/qubes-src/linux-template-builder/mnt' already appears to have an environment; will leave as-is!
  --> Unbinding INSTALLDIR...
umount: cache_archlinux/bootstrap/mnt: not mounted.
-> Installing package groups...
--> Archlinux 02_install_groups.sh
  --> Synchronize resolv.conf...
  --> Installing archlinux package groups...
    --> Selected packages: xorg xterm ethtool net-tools sudo wget diffutils ldns tmux vim terminus-font ttf-bitstream-vera ttf-dejavu ttf-inconsolata ttf-linux-libertine noto-fonts noto-fonts-emoji gnome-settings-daemon gtk-engines gvfs lxappearance leafpad thunar thunar-volman xfce4-terminal xfce4-settings evince firefox thunderbird checksec
error: failed to init transaction (unable to lock database)
error: could not lock database: File exists
  if you're sure a package manager is not already
  running, you can remove /var/lib/pacman/db.lck
make[1]: *** [Makefile:65: rootimg-build] Error 1
```

**Solutions you've tried**

* Attempted to see if there was any db.lck file.... found:

```
[user@qube-builder qubes-builder]$ sudo find . -name "db.lck"
./qubes-src/linux-template-builder/mnt/var/lib/pacman/db.lck
[user@qube-builder qubes-builder]$ sudo mount -o remount,rw qubes-src/linux-template-builder/mnt
mount: /home/user/qubes-builder/qubes-src/linux-template-builder/mnt: cannot remount /dev/loop9p3 read-write, is write-protected.
```
However, I was unable to modify it as it is read-only.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

The Arch Linux Template Building Guide.

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

#6028 
#6219 
#6172 
#6196

**Comment by unman** [comment]
@andrewdavidwong  @tsteinholz 
As a result of changes merged and updated packages, the Arch template for 4.0 builds correctly with no  errors.
Please close this issue.
