### ISSUE TITLE
Can not attach USB port to Qube

### ISSUE THREAD

**Issue by straussmaus** [QubesOS/qubes-issues#6259]
**Qubes OS version**
4.0.3 (fresh install)

**Affected component(s) or functionality**
An HVM qube with a (the) USB Device attached.

**Brief summary**
Laptop has three USB ports.

Devices shows three USB devices

One is the webcam.

One, I don't know.  when I attach to the Qube I can not start the Qube.

One is 1d, which I expected to be the USB ports on the device.  When attached, this Qube does not control any USB ports.

**How Reproducible**

I have used the USB ports on this laptop attached to a Qube before.  I think this error might be new in 4.0.3.  (It is also possible that I am doing something really stupid.)

**To Reproduce**

1. Fresh install of 4.0.3.

2. Do not create USB qube with Qubes install.

3. Create a new Qube.

4. Set as HVM, attach USB device 1d

5. Start new qube.

6. Plug in USB drive.
 
7. See drive controlled by dom0.

**Expected behavior**
Expected that USB drive will be owned by Qube.

**Actual behavior**
USB drive is owned by dom0.

**Additional context**
I prefer not to share what model laptop this is.

Manually attaching the USB drive to the qube using the icon on the upper right is successful.  However, for security it is necessary to not have to first attach to dom0 before attaching to qube.

**Solutions you've tried**
- Reboot
- Tried all USB ports (3 total)
- Tried all USB devices (1d "should" be correct.  1a is the webcam, 00:14 is something ghtat causes qube no tto boot)

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
https://github.com/QubesOS/qubes-issues/issues?q=is%3Aissue++USB+attach

(No matches.)

**Comment by DemiMarie** [comment]
Try passing `rd.qubes.hide_all_usb` on the dom0 command line.

**Comment by andrewdavidwong** [comment]
Please read and follow this documentation, which covers exactly this use case and may solve your problem:

https://www.qubes-os.org/doc/usb-qubes/

If you believe there is still a bug after reading this documentation and following the instructions it contains, please leave a comment explaining as specifically as possible what you believe the bug to be.
