### ISSUE TITLE
R4.1(x86_64) qubes-template-gentoo-minimal unexpectedly requires a root password

### ISSUE THREAD

**Issue by Kreyren** [QubesOS/qubes-issues#6261]
This issue affects gentoo-minimal templateVM

## Steps to reproduce
1. Install `qubes-template-gentoo-minimal` template e.g. `qubes-dom0-update qubes-template-gentoo-minimal` from contrib repository.
2. Open terminal in the mentioned templateVM and expect failure while trying to gain root access

## Expected
Do not require root password like other templates or make the password available somewhere.

**Comment by unman** [comment]
On Sun, Dec 06, 2020 at 04:48:17PM -0800, Jacob Hrbek wrote:
> This issue affects gentoo-minimal templateVM
> 
> ## Steps to reproduce
> 1. Install `qubes-template-gentoo-minimal` template e.g. `qubes-dom0-update qubes-template-gentoo-minimal` from contrib repository.
> 2. Open terminal in the mentioned templateVM and expect failure while trying to gain root access
> 
> ## Expected
> Do not require root password like other templates or make the password available somewhere.
> 

This is a common feature of all minimal templates:
https://www.qubes-os.org/doc/templates/minimal/

**Comment by Kreyren** [comment]
@unman Thanks, missed it!

Closing.

**Comment by fepitre** [comment]
@Kreyren: if you want to add only to your minimal template, you can emerge `core-agent-linux` with the use flag `passwordless-root`: https://github.com/fepitre/qubes-gentoo/blob/master/app-emulation/qubes-core-agent-linux/.qubes-core-agent-linux.ebuild.0#L23.
