### ISSUE TITLE
Debian-11 PV/HVM qube is unable to use dGPU through radeon on notebook in supertuxkart App/Standalone VM

### ISSUE THREAD

**Issue by Kreyren** [QubesOS/qubes-issues#6262]
**DISCLAIMER:** This issue has been filed to the forum (https://qubes-os.discourse.group/t/r4-1-x86-64-debian-11-pv-hvm-qube-is-unable-to-use-dgpu-through-radeon-on-20089-lenovo-g770-in-supertuxkart-appvm/1731) where neither the forum nor IRC members seems to know what is this caused by. I assume that this is either a bug or that this VM requires some kind of a procedure to make this work that is unknown to me.

This issue concerns debian-11/fedora-32 VMs created from templateVM being unable to use dGPU. (possibly other VMs as well)

## Terminology
Terminology as the procedure to get dGPU working in desired VM seems to be a common issue on QubesOS[4][5] hoping to be used as a reference for the end-users that might not understand the abbreviations.

##### GPU
Graphical Processing Unit used for processes that require graphical rendering

##### dGPU
Dedicated GPU used on e.g. notebooks for graphic-intensive processes where battery life is a concern

##### iGPU
Integrated GPU is usually a power efficient and resource limited GPU intended to handle the windowing system such as 'X'.

##### VGA
Video Graphic Array referring to the adapter that is providing the GPU.

##### dVGA
Adapter providing the dGPU.

##### iVGA
Adapter providing the iGPU.

## Steps to reproduce
0. Get system with Integrated GPU (iGPU) and dedicated GPU (dGPU) e.g. laptop.
1. Install debian-11/fedora-32 template e.g. `qubes-dom0-update qubes-template-debian-11`
2. Hide the VGA from dom0 to avoid QubesOS crash (https://github.com/QubesOS/qubes-issues/issues/6245)
3. Create new App or Standalone VM from debian-11 template and set it as PV or HVM
4. Attach the dGPU to the newly created VM
5. Run VM and notice the dVGA present in `lspci`
6. Disable `nomodeset` kernel cmdline so that the VM can use the VGA driver (see `Effects of nomodeset (kernel cmdline)` in `Tried solutions` below)
7. Expect debian using `llvmpipe` for graphics while being unable to use the assigned dGPU in e.g. `supertuxkart` (from `supertuxkart` package)

X. Try to set `gfx_passthru`? e.g. `qvm-features VMNAME gfx_passthru 1` (See `Effects of qfx_passthru` in `Tried solutions` below)

**NOTE:** Alternatively `glxinfo` from `mesa-utils` package can be used as `glxinfo | grep "OpenGL ren"` will show which graphic adapter is being for OpenGL (test taking below 1 sec)

## Expectation
Being able to use the dGPU in desired VM on QubesOS 4.1 e.g. in `supertuxkart`

### Unable to find configuration file for Xen VMs
I was unable to find the configuration file used for xen VMs as mentioned by Xen Wiki that expect these in `/etc/xen/<HOST>` where QubesOS seems to be parsing these through the pipeline (searched whole HDD looking for human readable files that contain test value set using `qvm-features <VMNAME> gfx_passthru "ajdkljlakjhladshjasueiowuyiweruy")` and tried to interpret the code.

Also tried `qvm-features`

### Usage of `DRI_PRIME`
Radeon driver on mentioned system required environment variable `DRI_PRIME` set to the value of `1` to allow the dGPU to work.

### Effects of `gfx_passthru` 
According to https://wiki.xenproject.org/wiki/Xen_VGA_Passthrough#The_effect_of_gfx_passthru.3D_option xen might(?) require `gfx_passthru` with value `1` that does not seem to affect this issue

option set using `qvm-prefs --set <VMNAME> gfx_passthru "1"` or `qvm-features <VMNAME> gfx_passthru "1"`

### Explicitly setting the `pci`
According to https://wiki.xenproject.org/wiki/Xen_VGA_Passthrough#New_kernels_.28v3.0_and_following.29 xen might require the VGA passed through `pci` option which i set using `qvm-prefs -s <VMNAME> pci "['0.0:0']"` that does not affect the issue

### Configuring Xorg to use the dGPU
This was proposed on IRC where the chat member though that Xorg is not using the dGPU.

Seems that forcing xorg to use the dGPU makes the VM unbootable or without video.

### Effects of `nomodeset` (kernel cmdline)
By default QubesOS sets `nomodeset` for all VMs which in this scenario prevents loading of dGPU drivers.

To disable it run:
```sh
# In VMNAME and save the output
cat /proc/cmdline

# Disables default flags
qvm-features VMNAME no-default-kernelopts 1

# Set the kernelopts and reboot
qvm-prefs -s VMNAME kernelopts "<Output from VMNAME's /proc/cmdline without nomodeset>"
```

Make sure the the dGPU driver is loaded e.g. `lsmod | grep radeon`

## Relevant informations
1. Qubes docs on PCI devices https://www.qubes-os.org/doc/pci-devices/
2. Qubes docs on troubleshooting PCI https://www.qubes-os.org/doc/pci-troubleshooting/
3. Qubes docs on device security https://www.qubes-os.org/doc/device-handling-security/
4. Community member posting GPU passthrough on reddit https://www.reddit.com/r/Qubes/comments/9hp3e7/gpu_passthrough_howto/
5. Community troubleshooting of GPU passthrough related issue on reddit https://www.reddit.com/r/Qubes/comments/66wk4q/gpu_passthrough/
6. Xen wiki describing the procedure to get dGPU in desired VM https://wiki.xenproject.org/wiki/Xen_VGA_Passthrough#The_effect_of_gfx_passthru.3D_option

**Comment by Kreyren** [comment]
Same issue on fedora-32 (PV) used as standaloneVM from TemplateVM.

**Comment by Kreyren** [comment]
CC @marmarek, Could you take a look a this please? ^-^

**Comment by asharp** [comment]
Qubes uses libvirt rather than raw xen, so look at /run/libvirt/libxl/[name].xml for the vm's xml config file. You might also find more information at /usr/lib/python3.5/site-packages/qubes and /var/lib/qubes/qubes.xml .

**Comment by SmugglerSMR** [comment]
@Kreyren, I am pursuing the same issue as you do, went through the same steps before stumbled upon your posts. Have you made any progress or successes with passing through dGPU or at least setting the gfx_passhtru option to libvirt config file?

**Comment by Kreyren** [comment]
Stale issue, don't use qubes anymore atm and i don't remember making this work
------- Original Message -------

**Comment by SmugglerSMR** [comment]
> > at least setting the gfx_passhtru option to libvirt config file
> 
> This specific step shouldn't be needed, we have a patch that do it automatically: https://github.com/QubesOS/qubes-vmm-xen/blob/xen-4.14/patch-libxl-automatically-enable-gfx_passthru-if-IGD-is-as.patch

@marmarek How would you suggest we may verify or modify it? As an example, I took a Win7 AppVM, which I managed to passthrough a dGPU (no Code 43 error). However, the igd is Intel-based, and once I run the VM and check the devices, I see the standard VGA graphics adaptor and Qubes Video Driver being used as primary video output, despite my attempts to set qvm-feature vga to none or device-model to anything else.
From what I read from [Xen VGA passhtru](https://wiki.xenproject.org/wiki/Xen_VGA_Passthrough), the way to control that state is by setting the gfs_passtru, device_model and VGA settings.

Another thing that is not clear to me is how the IGD is supposed to be assigned for gfx_passhtru awareness since attaching it similarly to dGPU will lead to a system crash, and setting pci=[00:02.0,permissive=1] has no effect on VMs' devices?

**Comment by marmarek** [comment]
You do need to assign it to the VM (using either `qvm-pci` command, or in VM settings), for the VM to have access to it. It means, dom0 cannot use it at the same time. If X server in dom0 uses the IGD, you need to stop it first (for example `systemctl stop lightdm`). But keep in mind, if IGD is the only device you use for dom0 video output, if you assign it to some VM, you'll loose video output in dom0. In most cases, it means you won't be able to do anything anymore...
