### ISSUE TITLE
Efficient compiled binary policy format

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#6266]
**The problem you're addressing (if any)**

The current qrexec policy format is inefficient.  Determining whether a request is allowed requires potentially consulting every policy rule, which is `O(n)`.

This is not a major problem now, as policies are rather small.  However, in R4.1, the entire policy will be (effectively) a single file, which means that the parsing overhead will be much larger.  Furthermore, other changes to qrexec have made it much more efficient, so the parsing overhead is a larger fraction of the total.

**Describe the solution you'd like**

There are several ways to speed up policy lookups:

- We can add a cache of recent policy evaluations.
- We can add indexes (similar to those used in a database) to avoid a linear scan of the entire policy.
- We can switch to a binary policy format, such as an SQLite database.

These approaches are not mutually exclusive, and not all need to be implemented.  For example, a cache must be invalidated when necessary, while a binary policy format is much more difficult to audit.

**Where is the value to a user, and who might that user be?**

There are some applications, such as proxying web requests over qrexec, where qrexec calls are performance critical.  This will help speed them up.

**Describe alternatives you've considered**

**Additional context**

This came up while thinking about #6264.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

**Comment by marmarek** [comment]
Currently the policy is loaded once (after a change) to a long living qrexec-policy-daemon. This avoids the most costly operation which is text file parsing. We can think of some further improvements if the current evaluation will be a bottleneck, but I think currently it isn't anymore.

**Comment by DemiMarie** [comment]
There are other improvements I can think of:

- Avoid spawning a `qrexec-client` process for each call.
- Handle all requests inside a single agent process, rather than forking a new process per connection.

**Comment by marmarek** [comment]
Since @DemiMarie opened yet another issue about the same thing, let me be clearer: not needed anytime soon. Actual policy evaluation (when it's already loaded and given "system info" structure) is a _tiny_ fraction of qrexec call setup time. For example, fetching system info takes much more time. So, I'm closing it for now, we can re-consider it when it could actually provide a meaningful difference (and not before that).

**Comment by marmarek** [comment]
Example of a change that actually makes a difference, based on performance tests: https://github.com/QubesOS/qubes-issues/issues/9362

**Comment by DemiMarie** [comment]
> Since @DemiMarie opened yet another issue about the same thing, let me be clearer: not needed anytime soon. Actual policy evaluation (when it's already loaded and given "system info" structure) is a _tiny_ fraction of qrexec call setup time. For example, fetching system info takes much more time. So, I'm closing it for now, we can re-consider it when it could actually provide a meaningful difference (and not before that).

Makes sense.

It’s worth noting that one can easily construct artificial benchmarks where policy evaluation _is_ the bottleneck by simply adding a lot of rules.  I’m more interested in performance in the real world.
