### ISSUE TITLE
R4.1 debian-11 from testing repo seemingly crashes and then becames unbootable

### ISSUE THREAD

**Issue by Kreyren** [QubesOS/qubes-issues#6271]
This issue concerns debian-11 templateVM in Qubes-testing.

> Cannot connect to qrexec agent for 60 seconds, see /var/log/xen/console/guest-VMNAME.log for details

### Steps to reproduce
1. Install debian-11 template VM from testing repo e.g. `qubes-dom0-update qubes-template-debian-11`
2. Create Standalone VM from it.
3. Start the standalone VM, open few windows in it and wait for them to close and then notice that your VM is not booting, seems to happen on random.
3.1. Suspecting `apt upgrade` relevant to it by triggering the `qubes-something`

### Reproducible
Always

#### guest-VMNAME.log
NOTE(Krey): The output shows login, but whenever i try to open terminal or anything with the VM it reboots.
NOTE(Krey): I can open disposable VM to access the console from qubes manager GUI, but i don't have time to login and do any action
https://gist.githubusercontent.com/Kreyren/dfe47f4a5dc5cdb6ed339c9525537e90/raw/df943ae4f05a7416e508b23ece2594b254d652ba/gistfile1.txt
> [2020-12-11 01:13:52] [    6.635659] systemd[1]: qubes-db.service: Main process exited, code=exited, status=1/FAILURE
> [2020-12-11 01:13:52] [    6.635872] systemd[1]: qubes-db.service: Failed with result 'exit-code'.
> [2020-12-11 01:13:52] [    6.636349] systemd[1]: Failed to start Qubes DB agent.

> [2020-12-11 01:13:53] [.[0;1;31mFAILED.[0m] Failed to start .[0;1;39mXen driver domain device daemon.[0m.

> [2020-12-11 01:13:53] [.[0;1;31mFAILED.[0m] Failed to start .[0;1;39mQubes remote exec agent.[0m.

#### grexec.VMNAME
```
domain dead
2020-12-11 01:49:35.276 qrexec-daemon[69781]: qrexec-daemon.c:339:init: cannot connect to qrexec agent: No such process
```

### Hypothesis
Looks like issue related to grexec killing the VM after 60 secs for some reason caused by qubes-core-something invoked during apt-upgrade?

#### Setup for onion services
I've replaced the mirrors from clearweb with onion services, but i doubt that being relevant.

#### Access point (99999 sec window)
I can open the VM and run `sudo xl console VMNAME` to gain access to the login prompt for around 30 sec before halt, but that does not accept my password.

Changed the timeout using `qvm-prefs VMNAME grexec_timeout 99999` 

Does not accept my non-root,root password

root does not have blank password

qubes-builder-debian does not expose any password that i can see

#### Kernel
This is PVH VM using same kernel as dom0 (5.4.67-1)

#### Effect of AppArmor
Context https://github.com/QubesOS/qubes-issues/issues/6271#issuecomment-742923618

Using `qvm-features VMNAME apparmor ''` results in https://gist.githubusercontent.com/Kreyren/c9cdbde40f543ed424a60f9bbb4e0872/raw/4ff31cf808f313f960cf1a83adfa59da5c9aaec0/gistfile1.txt

**Comment by marmarek** [comment]
There is also:
```
[2020-12-11 01:13:52] [    6.635659] systemd[1]: qubes-db.service: Main process exited, code=exited, status=1/FAILURE
[2020-12-11 01:13:52] [    6.635872] systemd[1]: qubes-db.service: Failed with result 'exit-code'.
[2020-12-11 01:13:52] [    6.636349] systemd[1]: Failed to start Qubes DB agent.
```

This sounds bad.

As for the root password, there should be autologin on a local console, if there isn't, that's another issue.

**Comment by marmarek** [comment]
Can it be related to apparmor? Try disabling it and see if anything changes.

**Comment by Kreyren** [comment]
@marmarek elaborate how to disable apparmor.

`aa-teardown` in dom0?

**Comment by DemiMarie** [comment]
@Kreyren are you using in-VM or dom0 kernel?

**Comment by Kreyren** [comment]
@DemiMarie This is PVH VM using same kernel as dom0 (5.4.67-1)

**Comment by DemiMarie** [comment]
@Kreyren what is your kernel command line?

**Comment by Kreyren** [comment]
```console
[kreyren@dom0 ~]$ cat /proc/cmdline 
placeholder root=/dev/mapper/qubes_dom0-root ro rd.qubes.hide_pci=01:00.0 rd.luks.uuid=luks-e9d4b73f-10ad-4a47-a2d4-577d9535c50b rd.lvm.lv=qubes_dom0/root rd.lvm.lv=qubes_dom0/swap plymouth.ignore-serial-consoles i915.alpha_support=1 rd.driver.pre=btrfs rhgb quiet
[user@personal ~]$ cat /proc/cmdline
root=/dev/mapper/dmroot ro nomodeset console=hvc0 rd_NO_PLYMOUTH rd.plymouth.enable=0 plymouth.enable=0 xen_scrub_pages=0 
```

Where the VMNAME in question should have cmdline: `root=/dev/mapper/dmroot ro nomodeset console=hvc0 rd_NO_PLYMOUTH rd.plymouth.enable=0 plymouth.enable=0 xen_scrub_pages=0`

**Comment by Kreyren** [comment]
> As for the root password, there should be autologin on a local console, if there isn't, that's another issue. @marmarek 

Doesn't seem to do auto-login

**Comment by marmarek** [comment]
In the log linked earlier I see:
```
Kernel command line: root=/dev/mapper/dmroot ro nomodeset console=hvc0 rd_NO_PLYMOUTH rd.plymouth.enable=0 plymouth.enable=0 xen_scrub_pages=0  apparmor=1 security=apparmor
```
those extra apparmor parameters are controlled by `apparmor` feature, you can try: `qvm-features <vmname> apparmor ''`

**Comment by Kreyren** [comment]
@marmarek Using `qvm-features VMNAME apparmor ''` results in https://gist.githubusercontent.com/Kreyren/c9cdbde40f543ed424a60f9bbb4e0872/raw/4ff31cf808f313f960cf1a83adfa59da5c9aaec0/gistfile1.txt

**Comment by Kreyren** [comment]
@marmarek Note that the VM was working fine without AppArmor when it was deployed from TemplateVM

**Comment by marmarek** [comment]
Ok, it fails exactly the same way, so it isn't AppArmor.

**Comment by Kreyren** [comment]
Invoked `qvm-features --default qubes-6271 apparmor`

**Comment by 0rb677** [comment]
Haven't this issues. I use debian-11 and kali from templates-itl-testing based on 5.4.67-1 and updated from main and testing repo's.

**Comment by Kreyren** [comment]
> I remember your bug, but you need update template first from main and testing repo in qubes-r4.list before use it @0rb677

This is my `/etc/apt/sources.list.d/qubes-r4.list`

```
# Main qubes updates repository
deb [arch=amd64] https://deb.qubes-os.org/r4.1/vm bullseye main
#deb-src https://deb.qubes-os.org/r4.1/vm bullseye main

# Qubes updates candidates repository
#deb [arch=amd64] https://deb.qubes-os.org/r4.1/vm bullseye-testing main
#deb-src https://deb.qubes-os.org/r4.1/vm bullseye-testing main

# Qubes security updates testing repository
#deb [arch=amd64] https://deb.qubes-os.org/r4.1/vm bullseye-securitytesting main
#deb-src https://deb.qubes-os.org/r4.1/vm bullseye-securitytesting main

# Qubes experimental/unstable repository
#deb [arch=amd64] https://deb.qubes-os.org/r4.1/vm bullseye-unstable main
#deb-src https://deb.qubes-os.org/r4.1/vm bullseye-unstable main


# Qubes Tor updates repositories
# Main qubes updates repository
#deb [arch=amd64] tor+http://deb.qubesosfasa4zl44o4tws22di6kepyzfeqv3tg4e3ztknltfxqrymdad.onion/r4.1/vm bullseye main
#deb-src tor+http://deb.qubesosfasa4zl44o4tws22di6kepyzfeqv3tg4e3ztknltfxqrymdad.onion/r4.1/vm bullseye main

# Qubes updates candidates repository
#deb [arch=amd64] tor+http://deb.qubesosfasa4zl44o4tws22di6kepyzfeqv3tg4e3ztknltfxqrymdad.onion/r4.1/vm bullseye-testing main
#deb-src tor+http://deb.qubesosfasa4zl44o4tws22di6kepyzfeqv3tg4e3ztknltfxqrymdad.onion/r4.1/vm bullseye-testing main

# Qubes security updates testing repository
#deb [arch=amd64] tor+http://deb.qubesosfasa4zl44o4tws22di6kepyzfeqv3tg4e3ztknltfxqrymdad.onion/r4.1/vm bullseye-securitytesting main
#deb-src tor+http://deb.qubesosfasa4zl44o4tws22di6kepyzfeqv3tg4e3ztknltfxqrymdad.onion/r4.1/vm bullseye-securitytesting main

# Qubes experimental/unstable repository
#deb [arch=amd64] tor+http://deb.qubesosfasa4zl44o4tws22di6kepyzfeqv3tg4e3ztknltfxqrymdad.onion/r4.1/vm bullseye-unstable main
#deb-src tor+http://deb.qubesosfasa4zl44o4tws22di6kepyzfeqv3tg4e3ztknltfxqrymdad.onion/r4.1/vm bullseye-unstable main
```

I believe it has the `testing main` used? (bullseye is current testing?)

---

@0rb677 Can you elaborate on what do you think is causing this issue?

**Comment by 0rb677** [comment]
Hi, @Kreyren  uncomment 
`#deb [arch=amd64] https://deb.qubes-os.org/r4.1/vm bullseye-testing main`
then update and you can use it. same with kali template.

**Comment by Kreyren** [comment]
uncommented bullseye-testing using onion mirrors (adapting for my threat model. Will let you know if the issue appears again.
