### ISSUE TITLE
R4.1 Permission error running `lx console VMNAME` on non-root is confusing

### ISSUE THREAD

**Issue by Kreyren** [QubesOS/qubes-issues#6272]
### Steps to reproduce
1. Start any VM
2. Run `lx console VMNAME` as non-root from dom0
3. Expect `Unable to attach console`
4. Prefix with `sudo` and the command works

### Expected
Return insufficient permission error instead of generic

**Comment by marmarek** [comment]
This is how upstream `xl` command behave, nothing Qubes specific. Please report upstream.
Furthermore, it is safer to use `qvm-console-dispvm` instead.
