### ISSUE TITLE
VPN doc is missing

### ISSUE THREAD

**Issue by straussmaus** [QubesOS/qubes-issues#6273]
**Qubes OS version**

N/A

**Affected component(s) or functionality**

website

**Brief summary**

404 error when navigating to https://www.qubes-os.org/doc/vpn/

**How Reproducible**

100%

**To Reproduce**

https://www.qubes-os.org/doc/vpn/

**Expected behavior**

The VPN doc should show, or a link to the new location

**Actual behavior**

404

**Additional context**

https://duckduckgo.com/?sites=https%3A%2F%2Fwww.qubes-os.org&q=vpn&ia=web

**Solutions you've tried**

**Comment by hackerncoder** [comment]
The VPN docs have been moved to github (https://github.com/QubesOS/qubes-doc/pull/1101/files#diff-07d30049577ad63d59568f238f9698d1254a2d1110e1a755b2f6b17ee2570c25R255), if you try to access it through https://qubes-os.org/doc, you should be redirected to github.

**Comment by straussmaus** [comment]
Okay.  I recommend editing your 404 page to say you have migrated many docs, and to link to the homepage so people can do a new search.

**Comment by unman** [comment]
On Fri, Dec 11, 2020 at 03:31:11AM -0800, straussmaus wrote:
> Okay.  I recommend editing your 404 page to say you have migrated many docs, and to link to the homepage so people can do a new search.
> 

Is there a stale link here, or had you bookmarked a dead link?
Do you think that custom 404 should be issued in every case or only
where pages have been migrated? For how long? 
Surely most people, when faced with a 404, just head up to the main page
and look again?

**Comment by hackerncoder** [comment]
The list of docs is correctly listing to the github, strassmaus has bookmarked a dead link or used duckduckgo where it incorrectly links to doc/vpn (see his link: https://duckduckgo.com/?sites=https%3A%2F%2Fwww.qubes-os.org&q=vpn)

**Comment by straussmaus** [comment]
Correct.  I got my link from duckduckgo.  It will filter through search engines soon.  However some people must have the pages bookmarked?

> Surely most people, when faced with a 404, just head up to the main page
and look again?

I disagree with this, but who knows?  And how many is "most people"?  51%?  99%?  How many confused people is acceptable considering that this thread is taking more time than a fix could take?

> Do you think that custom 404 should be issued in every case 

I think that every time a major change in page locations take place, good practice is to edit the 404 to say "we have recently changed our site map.  please click *here* to search manually for the content you are looking for."

**Comment by andrewdavidwong** [comment]
This is just an error in the redirects in the YAML header for that page, likely introduced during batch modification because the VPN page was somehow unique. I'll fix it now, and the old link will automatically be redirected to the new page. All the migrated pages should behave in this manner (i.e., redirect automatically rather than 404ing), so do let me know if any others 404.
