### ISSUE TITLE
Signed metadata verification broken on non-Fedora-based UpdateVMs 

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#6275]
**Qubes OS version**

`Qubes release 4.0 (R4.0)`

**Affected component(s) or functionality**

`qubes-dom0-update`

**Brief summary**

If I turn on `repo_gpgcheck` for the QubesOS repositories in dom0, DNF in the UpdateVM is unable to import the needed GPG keys.

**How Reproducible**

100%

**To Reproduce**

1. Add `repo_gpgcheck=1` to any enabled repository in `/etc/yum.repos.d/qubes-dom0.repo`.
2. Run `sudo qubes-dom0-update`

**Expected behavior**

`qubes-dom0-update` succeeds

**Actual behavior**

`qubes-dom0-update` fails

**Screenshots**

**Additional context**

**Solutions you've tried**

Running `ln -s RPM-GPG-KEY-qubes-4-primary /etc/pki/rpm-gpg/RPM-GPG-KEY-qubes-4.0-primary` fixes the problem.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

**Comment by marmarek** [comment]
I wonder how does it look with Debian-based UpdateVM, especially with debian-11 (where we have dnf instead of yum(downloader)). Can you check that too?

**Comment by DemiMarie** [comment]
With metadata verification turned on, Whonix UpdateVMs are totally broken.  Debian 10 and below UpdateVMs are presumably broken as well, as pygpgme isn’t available.

**Comment by DemiMarie** [comment]
This is fixed for Fedora UpdateVMs.  Leaving this open for Debian ones.

**Comment by andrewdavidwong** [comment]
> Add `repo_gpgcheck=1` to any enabled repository in `/etc/yum.repos.d/qubes-dom0.repo`.

Since `repo_gpgcheck` is not present in the repo def by default, I doubt that any users have taken the step to manually add this. So, in the absence of a `repo_gpgcheck` line, what is the default (0 or 1)?

Users are reporting that using a Debian UpdateVM currently allows for dom0 updates, which suggests that the default (in the absence of the line) is `repo_gpgcheck=0`, which @DemiMarie has informed me comes at a security cost.

Shouldn't the default, when not otherwise specified, be `repo_gpgcheck=1`? Is there any way to enforce this on existing installations?

**Comment by DemiMarie** [comment]
> > Add `repo_gpgcheck=1` to any enabled repository in `/etc/yum.repos.d/qubes-dom0.repo`.
> 
> Since `repo_gpgcheck` is not present in the repo defs by default, I doubt that (m)any users have taken the step of manually adding this. So, in the absence of a `repo_gpgcheck` line, what is the default (0 or 1)?

Sadly, the default is 0.

> Users are [reporting](https://qubes-os.discourse.group/t/debian-10-minimal-configuration/2603/27?u=adw) that using a Debian UpdateVM currently allows for dom0 updates, which suggests that the default (in the absence of the line) is `repo_gpgcheck=0`, which @DemiMarie has informed me comes at a security cost.
> 
> Following the principle of secure defaults, shouldn't the default, when not otherwise specified, be `repo_gpgcheck=1`? Is there any way to add this to existing installations without instructing every user to manually edit their repo defs?

It should be, but doing so causes breakage in some cases due to bugs in DNF.  It is possible to set it using `dnf config-manager` and some scripting.  The Qubes update scripts are aware of the bugs in DNF and work around them.

**Comment by brendanhoar** [comment]
> It should be, but doing so causes breakage in some cases due to bugs in DNF.  It is possible to set it using `dnf config-manager` and some scripting.  The Qubes update scripts are aware of the bugs in DNF and work around them.

Does this mean users should avoiding using dnf directly?

I typically alternate between dns use and the qubes updater (dnf and apt-get for convenience of parallel updates but also qubes updater to pick up some of the out-of-band changes the qubes teams uses it to push).

B

**Comment by DemiMarie** [comment]
> > It should be, but doing so causes breakage in some cases due to bugs in DNF.  It is possible to set it using `dnf config-manager` and some scripting.  The Qubes update scripts are aware of the bugs in DNF and work around them.
> 
> Does this mean users should avoiding using dnf directly?

For updates, generally yes.  Installing packages via dnf directly is fine.

> I typically alternate between dns use and the qubes updater (dnf and apt-get for convenience of parallel updates but also qubes updater to pick up some of the out-of-band changes the qubes teams uses it to push).
> 
> B

**Comment by andrewdavidwong** [comment]
I've just updated the [Updating Qubes OS](https://www.qubes-os.org/doc/updating-qubes-os/) documentation page to warn against using direct commands for updating. I'm now working on a PSA post to disseminate this information more widely across the userbase, since most Qubes users are accustomed to using direct commands for updating and probably won't notice this doc update.

**Comment by marmarek** [comment]
The problem with the third option (and to some extend the second too) is
that setting repo_gpgcheck=1 while having UpdateVM set to something
incompatible with it (like debian-10, or Whonix) breaks dom0 updates
completely.
So, given an option of slight security improvement (which is just yet
another mitigation, in addition to many more already in place) at the
risk of breaking dom0 updates completely, I prefer to not force it via
any kind of update.
This is especially because if dom0 updates are broken, we have no way to
ship a fix via a subsequent update. The only way is the user fixing it
manually. This is different from template updates, where we always have
a backup option of shipping an update via salt from dom0.

We can have it enabled for fresh installations of R4.1, and possibly
also those upgrade from R4.0.

**Comment by andrewdavidwong** [comment]
> The problem with the third option (and to some extend the second too) is that setting repo_gpgcheck=1 while having UpdateVM set to something incompatible with it (like debian-10, or Whonix) breaks dom0 updates completely. So, given an option of slight security improvement (which is just yet another mitigation, in addition to many more already in place) at the risk of breaking dom0 updates completely, I prefer to not force it via any kind of update. This is especially because if dom0 updates are broken, we have no way to ship a fix via a subsequent update. The only way is the user fixing it manually. This is different from template updates, where we always have a backup option of shipping an update via salt from dom0.

Those are very good points. I agree.

> We can have it enabled for fresh installations of R4.1, and possibly also those upgrade from R4.0.

This sounds like the most reasonable course of action (and consistent with not breaking existing stable installations).

It sounds like it's more accurate to view `repo_gpgcheck=1` as an enhancement than `repo_gpgcheck=0` as a bug, which would make it appropriate to wait for the next release.

**Comment by DemiMarie** [comment]
I wonder if we should have a feature for “can serve as UpdateVM with `repo_gpgcheck=1`”.  Fedora qubes would have this feature set by default, while other qubes would only have this feature set if DNF is installed.

**Comment by andrewdavidwong** [comment]
> Running `ln -s RPM-GPG-KEY-qubes-4-primary /etc/pki/rpm-gpg/RPM-GPG-KEY-qubes-4.0-primary` fixes the problem.

@DemiMarie, in which directory did you run this command? Should it be run as root?

**Comment by andrewdavidwong** [comment]
I was just testing this, and I noticed that `qubes-dom0-update` encounters the expected curl error (because I haven't done @DemiMarie's `ln -s` fix yet), but updating via `qubesctl` claims to succeed without any indication of error. Is this a bug?

Steps to reproduce:
1. Add `repo_gpgcheck=1` to all enabled repos in `/etc/yum.repos.d/qubes-dom0.repo`. (We expect this to cause a curl error.)

2. Test updating with `qubes-dom0-update`:
```
$ sudo qubes-dom0-update
Using sys-firewall as UpdateVM to download updates for Dom0; this may take some time...
Warning: Enforcing GPG signature check globally as per active RPM security policy (see 'gpgcheck' in dnf.conf(5) for how to squelch this message)
Qubes Dom0 Repository (updates)                 356  B/s | 833  B     00:02    
Qubes Dom0 Repository (updates)                 0.0  B/s |   0  B     00:00    
Errors during downloading metadata for repository 'qubes-dom0-current':
  - Curl error (37): Couldn't read a file:// file for file:///etc/pki/rpm-gpg/RPM-GPG-KEY-qubes-4.0-primary [Couldn't open file /etc/pki/rpm-gpg/RPM-GPG-KEY-qubes-4.0-primary]
Error: Failed to retrieve GPG key for repo 'qubes-dom0-current': Curl error (37): Couldn't read a file:// file for file:///etc/pki/rpm-gpg/RPM-GPG-KEY-qubes-4.0-primary [Couldn't open file /etc/pki/rpm-gpg/RPM-GPG-KEY-qubes-4.0-primary]
```
We got the expected curl error.


3. Now try updating with `qubesctl`:
```
$ sudo qubesctl --show-output state.sls update.qubes-dom0
local:
----------
          ID: /etc/yum.repos.d/qubes-dom0.repo
    Function: file.replace
      Result: True
     Comment: No changes needed to be made
     Started: 04:52:38.872954
    Duration: 7.623 ms
     Changes:   
----------
          ID: /etc/yum.repos.d/qubes-templates.repo
    Function: file.replace
      Result: True
     Comment: No changes needed to be made
     Started: 04:52:38.880689
    Duration: 1.336 ms
     Changes:   
----------
          ID: update
    Function: pkg.uptodate
      Result: True
     Comment: System is already up-to-date
     Started: 04:52:39.745785
    Duration: 109247.594 ms
     Changes:   

Summary for local
------------
Succeeded: 3
Failed:    0
------------
Total states run:     3
Total run time: 109.257 s
```
No indication of any curl error. It claims to have succeeded. Is the `qubesctl` update working around the bug, or is it falsely reporting success when it's actually encountering the same underlying curl error?

**Comment by DemiMarie** [comment]
> No indication of any curl error. It claims to have succeeded. Is the `qubesctl` update working around the bug, or is it falsely reporting success when it's actually encountering the same underlying curl error?

`qubesctl` has terrible error reporting.  There are many cases where it completely hide errors.  That is one reason I would like to have an interactive alternative.

**Comment by andrewdavidwong** [comment]
> > No indication of any curl error. It claims to have succeeded. Is the `qubesctl` update working around the bug, or is it falsely reporting success when it's actually encountering the same underlying curl error?
> 
> `qubesctl` has terrible error reporting. There are many cases where it completely hide errors. That is one reason I would like to have an interactive alternative.

I did some further investigation and testing, and I believe this is quite a serious problem, so I've reported it separately as https://github.com/QubesOS/qubes-issues/issues/6585.

**Comment by andrewdavidwong** [comment]
> > > Running `ln -s RPM-GPG-KEY-qubes-4-primary /etc/pki/rpm-gpg/RPM-GPG-KEY-qubes-4.0-primary` fixes the problem.
> > 
> > 
> > @DemiMarie, in which directory did you run this command? Should it be run as root?
> 
> The working directory should not matter, but root privileges are required.

```
[user@dom0 ~]$ sudo ln -s RPM-GPG-KEY-qubes-4-primary /etc/pki/rpm-gpg/RPM-GPG-KEY-qubes-4.0-primary 
ln: failed to create symbolic link '/etc/pki/rpm-gpg/RPM-GPG-KEY-qubes-4.0-primary': File exists
```

**Comment by andrewdavidwong** [comment]
> > > > > Running `ln -s RPM-GPG-KEY-qubes-4-primary /etc/pki/rpm-gpg/RPM-GPG-KEY-qubes-4.0-primary` fixes the problem.
> 
> > > > 
> 
> > > > 
> 
> > > > @DemiMarie, in which directory did you run this command? Should it be run as root?
> 
> > > 
> 
> > > 
> 
> > > The working directory should not matter, but root privileges are required.
> 
> > 
> 
> > ```
> 
> > [user@dom0 ~]$ sudo ln -s RPM-GPG-KEY-qubes-4-primary /etc/pki/rpm-gpg/RPM-GPG-KEY-qubes-4.0-primary 
> 
> > ln: failed to create symbolic link '/etc/pki/rpm-gpg/RPM-GPG-KEY-qubes-4.0-primary': File exists
> 
> > ```
> 
> 
> 
> Then there is no problem :smile:.

But it still doesn't work. I still get the curl error saying that it can't access the key. Is there some required fix that's not yet available for 4.0 stable?

**Comment by marmarek** [comment]
> [user@dom0 ~]$

it should be in what your UpdateVM is using as a template.

**Comment by 3hhh** [comment]
This is a debian 10 packaging bug.

They are packaging `yum` in an outdated version that has a runtime dependency on `python-gpgme` for the `repo_gpgcheck` functionality (see `misc.py`). `python-gpgme` (an unmaintained 2012 gpg python2 binding) however was deprecated for security reasons after debian 9.

debian 10 though ships the more recent `python-gpg`, which is used by newer `yum` versions.

So either they should've shipped a newer `yum` version or backported `python-gpgme`.

Using debian-9 for updates might work. Installing `pygpgme` via `pip` in debian-10 didn't work for me for some reason (`apt-get install ligpgme-dev python-ip && pip install pygpgme`) - probably a python2 PATH issue.

**Comment by DemiMarie** [comment]
Now that Debian 11 is available, can this be closed as “won’t fix for Debian 10, fixed in Debian 11”?

**Comment by marmarek** [comment]
Yes, and also Whonix (16) now is based on Debian 11.
