### ISSUE TITLE
4.1 , can't extend root partition in appvm by qvm-volume tool

### ISSUE THREAD

**Issue by 0rb677** [QubesOS/qubes-issues#6282]
**Qubes OS version**
4.1

**To Reproduce**

1.  qvm-volume extend  foo:root 100g
2.  qvm-volume info foo:root | grep size
size       100000000000
3. qvm-run -a foo xterm
4. df -h /

```
user@foo:~$ df -h /
Filesystem      Size  Used Avail Use% Mounted on
/dev/xvda3      9.6G  4.0G  5.2G  44% /
```

works only if trim template before:

1. qvm-clone foo foo2
2. qvm-extend  foo2:root 100g
3. create appvm based on foo2
4. then root partition is trimmed

I have no idea. Any new tools are used for resize appvm?

**Comment by iamahuman** [comment]
You can do `lvextend qubes_dom0/vm-VMNAME-root-snap -L SIZE-WITH-UNIT` in dom0, followed by `resize2fs /dev/xvda3` in AppVM.
