### ISSUE TITLE
StandaloneVM Memory Management

### ISSUE THREAD

**Issue by bluesteal** [QubesOS/qubes-issues#6286]
When creating a Standalone VM using dom0, the max memory is set to 1000 MB. This is too little and the VM will often crash or become unresponsive. I also notice this with other VMs as well and I am familiar with qmemman. Is there another more manual way of allocating memory using dom0 commands? VMs crashing and freezing due to resource requirements. This could maybe be address by having a better understanding of the overall pool of memory and CPU resources and maybe some dom0 commands that allow for manual change of VM memory (or via GUI). The StandaloneVm was created using a dom0 command but there was no parameter for setting max or available memory.

**Comment by bluesteal** [comment]
Is this index for dom0 cli commands?

https://dev.qubes-os.org/projects/core-admin/en/latest/genindex.html

**Comment by bluesteal** [comment]
Oh and also 

https://dev.qubes-os.org/projects/core-admin-client/en/latest/manpages/

**Comment by unman** [comment]
On Mon, Dec 14, 2020 at 09:21:48PM -0800, bluesteal wrote:
> When creating a Standalone VM using dom0, the max memory is set to 1000 MB. This is too little and the VM will often crash or become unresponsive. I also notice this with other VMs as well and I am familiar with qmemman. Is there another more manual way of allocating memory using dom0 commands? VMs crashing and freezing due to resource requirements. This could maybe be address by having a better understanding of the overall pool of memory and CPU resources and maybe some dom0 commands that allow for manual change of VM memory (or via GUI). The StandaloneVm was created using a dom0 command but there was no parameter for setting max or available memory. 
> 
> 

man qvm-create:
qvm-create --class StandaloneVM -l red --property=memory=4000 <qube>

Or after creation, use qvm-prefs:
qvm-prefs <qube> memory 4000

**Comment by andrewdavidwong** [comment]
Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this does not appear to be suitable for `qubes-issues`. We ask that you please post this on the [`qubes-users` mailing list or forum](https://www.qubes-os.org/support/) instead. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a brief comment explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.
