### ISSUE TITLE
python3-qubesdb needs update for python 3.9 in Debian bullseye repo

### ISSUE THREAD

**Issue by ajtowns** [QubesOS/qubes-issues#6287]
**Qubes OS version**
R4.0
(seems to be fixed in R4.1 testing, but not R4.0 testing or R4.1 itself)

**Affected component(s) or functionality**
Debian template running bullseye

**Brief summary**

Debian has updated to python 3.9, but qubes hasn't. This result in "apt-get dist-upgrade" upgrading python and removing all the qubes packages.

**How Reproducible**
100%

**To Reproduce**

```
$ grep '^[^#]' /etc/apt/sources.list.d/*
deb [arch=amd64] https://deb.qubes-os.org/r4.0/vm bullseye main
$ sudo apt-get install python3 python3-qubesdb
...
The following packages have unmet dependencies:
 python3-qubesdb : Depends: python3 (< 3.9) but 3.9.0-4 is to be installed
```

**Comment by fepitre** [comment]
We are already aware of this and multiple fixes are already merged/or pending but we need to rebuild packages for bullseye. This should be done in the next days.

**Comment by qtpies** [comment]
> We are already aware of this and multiple fixes are already merged/or pending but we need to rebuild packages for bullseye. This should be done in the next days.

[Bullseye has now become Debian Stable](https://www.debian.org/News/2021/20210814). I'm also waiting for official Bullseye support for another unrelated issue, but didn't want't to open a seperate issue for that. I understand you're busy but would really appreciate a status update
