### ISSUE TITLE
Choosing Hardware

### ISSUE THREAD

**Issue by bluesteal** [QubesOS/qubes-issues#6288]
What is the most performant hardware available for running QubesOS with all relevent CPU modules disabled and neutered and Coreboot with Heads installed?

**Comment by SvenSemmler** [comment]
On 12/15/20 7:18 PM, bluesteal wrote:
> What is the most performant hardware available for running QubesOS 
> with all relevent CPU modules disabled and neutered and Coreboot
> with Heads installed?

That's not an issue for an issue tracker. That's a question for the
qubes-user mailing list or the community forum. Here are some links you
might find helpful:

* https://www.qubes-os.org/support/
* https://www.qubes-os.org/doc/certified-hardware/
* https://www.qubes-os.org/hcl/

**Comment by andrewdavidwong** [comment]
Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this does not appear to be suitable for `qubes-issues`. We ask that you please post this on the [`qubes-users` mailing list or forum](https://www.qubes-os.org/support/) instead. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a brief comment explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.
