### ISSUE TITLE
Are you working on a Cubes 5? If yes: Are there any betas or release canidates yet?

### ISSUE THREAD

**Issue by 4tip** [QubesOS/qubes-issues#6294]
Are you working on a Cubes 5? If yes: Are there any betas or release canidates yet?

**Comment by andrewdavidwong** [comment]
Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this does not appear to be suitable for `qubes-issues`. We ask that you please post this on the [`qubes-users` mailing list or forum](https://www.qubes-os.org/support/) instead. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a brief comment explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.
