### ISSUE TITLE
Empty Standalone Qube Does Not Find Hard Disk on 4.0.3

### ISSUE THREAD

**Issue by straussmaus** [QubesOS/qubes-issues#6295]
**Qubes OS version**

 4.0.3

**Affected component(s) or functionality**

Empty Standalone Qube

**Brief summary**

When creating a custom standalone qube based on an iso, the installer inside the qube does not find a local hard disk, even when disk space is made available in the Qube Settings.

**How Reproducible**

100%

**To Reproduce**

1. Create an Empty Standalone Qube

2. Choose a recently downloaded iso (Android, Debian, FreeBSD, etc. does not matter)

3. Start installer.

4. Installer will fail because no local disk is detected.

**Expected behavior**

As with template and standalone qubes, the Qube creator should make "sda" etc. available to the qube.

**Actual behavior**

It seems that sda is not available to the Empty Standalone Qube.  

**Additional context**

I have successfully created Empty Standalone Qubes on previous versions.  So either this is a true bug, or perhaps some setting got moved that I am not seeing, or of course I could be missing something very obvious. 

**Solutions you've tried**

- Investigated all settings in the Qube Settings for the Empty Standalone Qube(s) that are affected.

- Several different boot iso OSes

- Various boot/install options in various OSes

- Booting to a rescue disk and running gparted
- 
**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

https://github.com/Qubes-Community/Contents/blob/master/docs/building/building-non-fedora-template.md
https://github.com/Qubes-Community/Contents/blob/master/docs/customization/windows-template-customization.md
https://github.com/Qubes-Community/Contents/blob/master/docs/os/linux-hvm-tips.md
https://theinvisiblethings.blogspot.com/2011/09/playing-with-qubes-networking-for-fun.html

**Comment by unman** [comment]
On Mon, Dec 21, 2020 at 02:46:39AM -0800, straussmaus wrote:
> 
> 
> **Qubes OS version**
> 
> 
>  4.0.3
> 
> 
> 
> **Affected component(s) or functionality**
> 
> 
> Empty Standalone Qube
> 
> **Brief summary**
> 
> 
> When creating a custom standalone qube based on an iso, the installer inside the qube does not find a local hard disk, even when disk space is made available in the Qube Settings.
> 
> 
> 
> 
> **How Reproducible**
> 
> 
> 100%
> 
> 
> **To Reproduce**
> 
> Steps to reproduce the behavior:
> 1. Create an Empty Standalone Qube
> 
> 2. Choose a recently downloaded iso (Android, Debian, FreeBSD, etc. does not matter)
> 
> 3. Start installer.
> 
> 4. Installer will fail because no local disk is detected.
> 
> **Expected behavior**
> 
> 
> As with template and standalone qubes, the Qube creator should make "sda" etc. available to the qube.
> 
> 
> **Actual behavior**
> 
> 
> It seems that sda is not available to the Empty Standalone Qube.  
> 
> **Additional context**
> 
> 
> I have successfully created Empty Standalone Qubes on previous versions.  So either this is a true bug, or perhaps some setting got moved that I am not seeing, or of course I could be missing something very obvious. 
> 
> **Solutions you've tried**
> 
> 
> - Investigated all settings in the Qube Settings for the Empty Standalone Qube(s) that are affected.
> 
> - Several different boot iso OSes
> 
> - Various boot/install options in various OSes
> 
> - Booting to a rescue disk and running gparted
> - 
> **Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
> 
> 
> https://github.com/Qubes-Community/Contents/blob/master/docs/building/building-non-fedora-template.md
> https://github.com/Qubes-Community/Contents/blob/master/docs/customization/windows-template-customization.md
> https://github.com/Qubes-Community/Contents/blob/master/docs/os/linux-hvm-tips.md
> https://theinvisiblethings.blogspot.com/2011/09/playing-with-qubes-networking-for-fun.html
> 
> 

Debian and FreeBSD can both be installed in an empty StandaloneHVM, so I
cant explain your inability.
Android cannot, because as you righly diagnose it looks for /dev/sda.
This issue has been resolved in 4.1

Had you consulted the qubes-user list or the Forum, which should be your
first port of call *before* raising an issue, you would find extensive
discussions of this issue, along with solutions. Please do this in
future.

**Comment by straussmaus** [comment]
> Debian and FreeBSD can both be installed in an empty StandaloneHVM, so I
cant explain your inability.

I have not tried pure Debian as there is already a Debian template, but debian-based distros did fail to find an install drive.  But FreeBSD failed to find a drive, as did OpenBSD.

Also had the problem with LineageOS.  At the time, I did not know this was Android-based so I wasn't searching for Android errors but now I will ignore this one.

However as of today I tried Knoppix and it *does* find `sda` 

>  the Forum

Wonderful!  Thank you for telling me about this.  I did not know this existed.

Because as of today Knoppix can find `sda`, I assume the problem with the other OSes is not caused by a Qubes bug so I will continue this at the Forum.  Thank you for informing me.

**Comment by straussmaus** [comment]
So putting it all together for other people who have this problem.

It was good that I posted here.  This is a bug (or inconsistent feature), not user error, and thank you to @unman for the reply, otherwise this would not have been fixable:

- within Qubes, a qube hard drive is called sda

- but in a Debian installer, specifying sda will not work.  You must specify xvda (why?  who knows?)

- except for sometimes, like in Knoppix, when it does show up as sda (why?  who knows?)

- Android/Lineage needs sda and that is hard coded, so it does not work (on 4.0.3)

**Comment by marmarek** [comment]
>     * within Qubes, a qube hard drive is called sda

No. The disk is named as kernel driver loaded for it choose to. In practice there are two drivers (in Linux kernel, other OS may differ) that can handle the disk - SCSI driver (`sd_mod` module) that attaches to the emulated disk and Xen PV disk driver (`xen-blkfront`  module) that attaches to PV transport. The former advertise the disk as `sda` the former as `xvda`. So it really depends what kernel drivers are included in given distribution.
There is no bug here, just differences between systems you run in such VM.

**Comment by straussmaus** [comment]
Thank you!  So the bug is really a doc bug because until now this was not documented.  , at least not in a place that was easily searchable.  (And a doc that isn't found is the same as a doc that doesn't exist.)

Great!

> No.

Oh, above I should have used a lowercase "q" and said:

`within (Debian) qubes, a qube hard drive is called sda`

Thank you for the correction.  Now because of this issue/ticket we have this somewhat documented for the next person who has trouble.

**Comment by andrewdavidwong** [comment]
> Thank you! So the bug is really a doc bug because until now this was not documented. , at least not in a place that was easily searchable. (And a doc that isn't found is the same as a doc that doesn't exist.)

This is not considered a Qubes doc bug, since the Qubes OS Project generally does not document the work of other projects:

https://www.qubes-os.org/doc/doc-guidelines/#core-vs-external-documentation

It sounds like you'd instead want to look into Linux documentation, for example.
