### ISSUE TITLE
Documentation for installation of Windows VM and QWT has vanished

### ISSUE THREAD

**Issue by GWeck** [QubesOS/qubes-issues#6296]
**Qubes OS version**

R4.0

**Affected component(s) or functionality**

Documentaion

**Brief summary**

When trying to reach this documentaion from [Windows VMs in Qubes OS](https://www.qubes-os.org/doc/windows/), an error 404 is displayed instead of the documentaion

**How Reproducible**

always

**To Reproduce**
Click on [Installing and Using Windows-based VMs](https://github.com/Qubes-Community/Contents/blob/master/docs/os/windows-vm.md) or [Installing and Using Qubes Windows Tools](https://github.com/Qubes-Community/Contents/blob/master/docs/os/windows-tools.md)

**Expected behavior**

The corresponding documentaion should be displayed.

**Actual behavior**

Github dispays error 404 `This is not the web page you are looking for.`

**Comment by iamahuman** [comment]
The refactoring in Qubes-Community/Contents@0c3f3bacfa66790effadecb12f465ba1eeafac65 apparantly has missed accompanying link updates from the official docs side.

**Comment by andrewdavidwong** [comment]
This has just been fixed by https://github.com/QubesOS/qubes-doc/pull/1105.

I'll also update those old links to point directly to the new pages.

**Comment by andrewdavidwong** [comment]
@iamahuman:
> The refactoring in [Qubes-Community/Contents@0c3f3ba](https://github.com/Qubes-Community/Contents/commit/0c3f3bacfa66790effadecb12f465ba1eeafac65) apparantly has missed accompanying link updates from the official docs side.

Actually, it's not that they were missed. Rather, I had to use a complicated series of `sed` commands and didn't get the path structure right in every case, since there were many different cases, some of which differed across both repos. See https://github.com/QubesOS/qubes-doc/pull/1105 for what was the actual problem in this particular case.
