### ISSUE TITLE
Updater improvements

### ISSUE THREAD

**Issue by tumbletree** [QubesOS/qubes-issues#6299]
**The problem you're addressing (if any)**
Qubes Updater is:
- opaque
- uninformative
- unresponsive
- prone to [crashing](https://github.com/QubesOS/qubes-issues/issues/6156), still. About once a month, hard reboot required.

It can be disruptive and distracting, but its essential. It should be better.

Updating is not trivial. At best, restarting all relevant qubes (sys-whatever + dependent vms) individually is very time-consuming, so a system restart is almost always required. Since restart takes so long (> 5 minutes), updating is not trivial.

The user is not given any tools by which they can manage the intrusion onto their workflow. There is no indication of the urgency, gravity and/or security of the updates - no idea of the packages at all. How can a user decide when to update? Is this "drop everything" or "when you can / overnight" priority?

**Describe the solution you'd like**
 
- It shouldn’t crash the machine. 
- “Details” should display full process in real time, just like `sudo dnf/apt upgrade` dialog
- “Cancel” should do exactly that. It doesn’t. It still chugs along anyway.
- Security / urgent updates labelled as such. Even a "traffic light" system.
- You shouldn’t need to click a checkbox to enable clicking on templates you want to force an upgrade. That should be enabled automatically.
- mouse-over each template should reveal what packages are going to be upgraded. 
- Qubes Security Bulletins (or their notification) should be distributed via the Updater. This is important information that should be "pushed", not rely on external services to "pull". [edit: added 2020-12-31]

**Where is the value to a user, and who might that user be?**

Everyone benefits, particularly 
- those on older/lower-spec hardware (specifically thinking of the restart times, but maybe also non-responsive issues)
- those for whom disruption to workflow represents a higher burden than others.
- (perhaps better compliance with updates? Which might be better for those who filed questions from unhappy users?)

**Describe alternatives you've considered**
`sudo apt/dnf update && sudo apt/dnf upgrade`

**Additional context**

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

[I gather ](https://qubes-os.discourse.group/t/updater-improvements-a-wishlist/1884)`salt` is an issue. I can't understand ( or devote the time to understand) that matter, but surely there has to be _something_. 

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

[Updater fail](https://github.com/QubesOS/qubes-issues/issues/6156)

**Comment by andrewdavidwong** [comment]
I've been thinking about this lately too. **Ideally**, I think Qubes should install all mandatory updates (especially mandatory critical security updates) automatically, in the background, without any user awareness (much less action) required. There should be options for not downloading updates over metered connections and for advanced users to opt out entirely. There should also be options for downloading (but not installing) non-mandatory updates and automatically installing all updates. (The appropriate defaults for non-mandatory updates are more open to debate.)

One of the biggest pain points is that updating can take a very long time, especially with many templates, especially over Tor. There's no reason that a human should be have to sit and wait while update data is being downloaded. It should be downloaded in the background (when appropriate, as unobtrusively as possible).

Another problem is users not knowing what exactly to do or not taking the appropriate action at the right time when a critical security update is released, such as when a new QSB is issued. For virtually all normal users, we already know that they want to install security updates when those updates are stable (and some even earlier, i.e., from `security-testing`). So, the logical default is for all stable security updates to be installed automatically. Qubes should be secure by default and keep itself that way by default.

Xen and kernel updates will require a dom0 reboot, but requiring a reboot after certain updates is nothing new for an operating system. Just handle this in the usual way: by notifying the user that a reboot is required and letting them choose when to do it. (Of course, the system should never forcibly reboot. The user gets to control the system; not the other way around. Which is, again, why there should also be an option to opt out of all of this.)

**Comment by DemiMarie** [comment]
> Xen and kernel updates will require a dom0 reboot, but requiring a reboot after certain updates is nothing new for an operating system. Just handle this in the usual way: by notifying the user that a reboot is required and letting them choose when to do it. (Of course, the system should never forcibly reboot. The user gets to control the system; not the other way around. Which is, again, why there should also be an option to opt out of all of this.)

I agree.  That said, it would also be nice to have an option for, “if it’s 2AM (say), reboot automatically if needed”.

The hardest part of this is going to be Salt.  Salt is designed for configuration management at massive scale, where watching individual updates happen is neither practical nor desirable.  That certainly is not the case for QubesOS!  To be honest, I wonder if Salt is the wrong tool for the job here.  It can enforce extremely complex configurations, but updates require only a tiny fraction of that complexity.  Furthermore, it is designed for unattended operation, whereas in the case of QubesOS feedback is highly desirable and sometimes even required.  Arch Linux officially does not support unattended upgrades, and not looking at the output from Pacman can cause problems.

A better approach is to run a shell script in the VM, with its stdin/out/err connected to an xterm.  Cancellation is then just a matter of Ctrl-C, and update progress is clearly visible.  The overhead of Salt and the management VM is eliminated.  Since the script would be supplied by dom0, vulnerabilities in the VM’s package manager can be mitigated as needed.  And we can make updates interactive for those who desire that.

**Comment by SvenSemmler** [comment]
On 12/22/20 12:17 PM, Demi Marie Obenour wrote:
> I wonder if Salt is the wrong tool for the job here.

Very much agree.

> A better approach is to run a shell script in the VM, with its 
> stdin/out/err connected to an xterm.

I always wondered why Salt was chosen for the update process. I used the 
updater a few times but found it slow/unresponsive and difficult to 
understand what's going on. Since then I simply use it as an indicator: 
when I see the little start in the toolbar, I open a dom0 terminal and 
kick my bash script/minimize the window.

The updater GUI could run similar scripts and be way more responsive 
that way, plus one could easily see which packages will be updated.

**Comment by andrewdavidwong** [comment]
> I always wondered why Salt was chosen for the update process. I used the
updater a few times but found it slow/unresponsive and difficult to
understand what's going on. Since then I simply use it as an indicator:
when I see the little start in the toolbar, I open a dom0 terminal and
kick my bash script/minimize the window.

Well, the problem is that the Salt updates do more than just run `dnf upgrade` or `apt upgrade` in the VM. They can also apply other security fixes:

https://groups.google.com/g/qubes-devel/c/n14n3Q295rw/

**Comment by DemiMarie** [comment]
> > I always wondered why Salt was chosen for the update process. I used the
> > updater a few times but found it slow/unresponsive and difficult to
> > understand what's going on. Since then I simply use it as an indicator:
> > when I see the little start in the toolbar, I open a dom0 terminal and
> > kick my bash script/minimize the window.
> 
> Well, the problem is that the Salt updates do more than just run `dnf upgrade` or `apt upgrade` in the VM. They can also apply other security fixes:
> 
> https://groups.google.com/g/qubes-devel/c/n14n3Q295rw/

Indeed they can, which is why I suggested running a shell script provided by dom0 instead.

**Comment by andrewdavidwong** [comment]
> > > I always wondered why Salt was chosen for the update process. I used the
> > > updater a few times but found it slow/unresponsive and difficult to
> > > understand what's going on. Since then I simply use it as an indicator:
> > > when I see the little start in the toolbar, I open a dom0 terminal and
> > > kick my bash script/minimize the window.
> > 
> > 
> > Well, the problem is that the Salt updates do more than just run `dnf upgrade` or `apt upgrade` in the VM. They can also apply other security fixes:
> > https://groups.google.com/g/qubes-devel/c/n14n3Q295rw/
> 
> Indeed they can, which is why I suggested running a shell script provided by dom0 instead.

Right, I was just replying specifically to @SvenSemmler's quoted remarks there, because I used to do exactly the same thing before asking about it in the linked thread.

**Comment by ninavizz** [comment]
+1 to all of this! I've been stuck in updater-hell for the past 2 weeks on my own Qubes laptop... and rethinking the updater to make it more user-friendly, to better manage tasks between torified and non-torified network connections, to more efficiently use `dom0` disk space w/o requiring disk space partitioning rejiggers, to automagically manage downloads and reboots when I'm not using the machine, and to offer me the option of seeing EVERYTHING in real-time and in a historic view, would be awesome. 

The technical particulars aren't my game, so I'm not going to delve into the Google Groups chats on the topic. But, I would like to approach an updater-ecosystem GUI rethink at some point in 2021.

@andrewdavidwong could this issue also get a UX tag on it?

**Comment by andrewdavidwong** [comment]
> @andrewdavidwong could this issue also get a UX tag on it?

Added!

**Comment by tumbletree** [comment]
Added a point re QSBs. 

Notification of QSB (link to the should (IMHO) be pushed out in the Updater. 

They're important, legitimate, system-relevant parcels of info. A webpage I need to specially go check, (I'm not going to remember) or a third party distribution service (and as of writing, I still only know of @andrewdavidwong's relaying this stuff to the subreddit) might have been okay for the early days of an experimental OS, but not now.

If its important info on running the OS, it should be delivered *in* the OS (trust, efficiency, fidelity, etc).

**Comment by ninavizz** [comment]
@tumbletree YES, I love that suggestion so much! Likewise, for how to message users about things they need to initiate, separate from what the updater itself can initiate. Really looking forward to unpacking everything this issue outlines and suggests, once I have the bandwidth to begin updater redesign sketches.

**Comment by tumbletree** [comment]
Thanks @ninavizz, look forward to it. I understand you may be busy getting as much done as possible in the last (maybe) few days of the greatest presidency ever, so, you know, when you can. 

Greatest presidency in the history of the universe, that is. Just in case I need to clarify.

**Comment by andrewdavidwong** [comment]
> Added a point re QSBs.
> 
> Notification of QSB (link to the should (IMHO) be pushed out in the Updater.
> 
> They're important, legitimate, system-relevant parcels of info. A webpage I need to specially go check, (I'm not going to remember) or a third party distribution service (and as of writing, I still only know of @andrewdavidwong's relaying this stuff to the subreddit) might have been okay for the early days of an experimental OS, but not now.
> 
> If its important info on running the OS, it should be delivered _in_ the OS (trust, efficiency, fidelity, etc).

> Likewise, for how to message users about things they need to initiate, separate from what the updater itself can initiate. 

This is already covered by #3430. It may or may not turn out to be the same mechanism.

> A webpage I need to specially go check, (I'm not going to remember) or a third party distribution service (and as of writing, I still only know of @andrewdavidwong's relaying this stuff to the subreddit)

They're also posted to our RSS feed, our mailing lists, our forum, Twitter, Facebook, and LinkedIn.

**Comment by tumbletree** [comment]
On the path from "first download of Qubes iso" to "used it for a few years", the need to monitor a (singular?) separate channel for update action (i.e. not Qubes Updater) is _not_ particularly well signposted.

Glad to see #3430, thankyou.

**Comment by andrewdavidwong** [comment]
> On the path from "first download of Qubes iso" to "used it for a few years", the need to monitor a (singular?) separate channel for update action (i.e. not Qubes Updater) is _not_ particularly well signposted.

As mentioned in the comment immediately above yours, it is not a singular channel. Rather, you only have to watch or subscribe to **one** of these not to miss any QSBs:

* [Qubes Security Pack](https://www.qubes-os.org/security/pack/) ([qubes-secpack](https://github.com/QubesOS/qubes-secpack))
* [Qubes News page](https://www.qubes-os.org/news/)
* [Qubes RSS feed](https://www.qubes-os.org/feed.xml)
* [QSB page ](https://www.qubes-os.org/security/bulletins/)
* [qubes-announce](https://www.qubes-os.org/support/#qubes-announce)
* [qubes-devel](https://www.qubes-os.org/support/#qubes-devel)
* [qubes-users](https://www.qubes-os.org/support/#qubes-users)
* [Qubes Forum](https://qubes-os.discourse.group/)
* [Twitter](https://twitter.com/QubesOS)
* [Reddit](https://www.reddit.com/r/Qubes/)
* [Facebook](https://www.facebook.com/QubesOS/)
* [LinkedIn](https://www.linkedin.com/company/qubes-os/)

I'll also add this information to the installation guide so that new users will be better informed.

**Comment by ninavizz** [comment]
I still believe all of the above, need to be handled elegantly in an updater. Requiring the user to pay attention to even one external channel, is a failure point. Good UX guides users w/o making them "think," while also not removing their agency.

I really like all of the ideas here to elegantly consolidate this stuff into an improved/rethought updater experience.

**Comment by andrewdavidwong** [comment]
> Requiring the user to pay attention to even one external channel, is a failure point.

Right. No one *wants* to require users to pay attention to any external channels (at least I certainly don't). But, given the *current* state of things, the choice is between requiring users to pay attention to an external channel or leaving them vulnerable, so we've chosen the former. I look forward to the day when we no longer have to do this.

**Comment by arkenoi** [comment]
I would say our update workflow is all broken. Requiring user to participate in many "manual" actions provides "false sense of agency" similar to false sense of security we all know. What could we do instead:

1. Make default "always up to date" mode automatic default. I think it is quite reasonable to assume almost every user just click the update icon whenever they see it is available, and almost no one makes manual testing of updates. However, there is no way to know in advance if an update breaks your system to unbootable state and thus we need to:

2. Make recovery easier. If we do not want the option to "boot to recovery system" always available for security reasons, a recovery flash drive that provides this option might make sense, and the recovery process to "restore dom0 to latest known successful boot state" should be easy (but we need means to record this state somehow, and it should be done semi-interactively AFTER the user started X11 session and *sees* that everything runs well indeed). The companion recovery system may be not qubes at all and may run generic latest kernel without xen.

..and also it would be nice to have:

3. "One-click" migration for templates approaching EOL with "undo button" available until we say "well, all is tested and running".

**Comment by DemiMarie** [comment]
For all of its flaws, Windows Update actually gets quite a few things right when it comes to user experience.  And I agree that we need to provide a recovery system.

**Comment by arkenoi** [comment]
Windows update system works reasonably well until something goes wrong. Then it becomes one a hell of "which update do i need to uninstall and which one do i need to install to bypass the glitch". Diagnostics of these situations "error code bla bla" is very painful.

**Comment by ninavizz** [comment]
Still have yet to attempt to really digest the depth of all the amazingness in this issue, but am now curious to learn more about "Recovery" considerations and workflows. Yep, all this is so wonderfully complicated... and wd really love to dig-in with some design explorations, sometime towards the end of this quarter.

**Comment by DemiMarie** [comment]
Good point @arkenoi.  That said, since we have a reasonable package manager, we aren’t likely to have those problems.

**Comment by arkenoi** [comment]
Also it is worth noticing that we have "real" update proxy that does not break the network isolation for dom0 only. For regular templates it is just security through obscurity, they are not network-isolated in fact. However, if we want to manage things like snap and pip for templates things become more tricky. Still doable, but requires individual workaround for each one.

**Comment by andrewdavidwong** [comment]
This issue contains so much great stuff that it's actually too big to go on as a single issue. As explained in our issue tracker guidelines, [every issue must be about a single, actionable thing](https://www.qubes-os.org/doc/reporting-bugs/#every-issue-must-be-about-a-single-actionable-thing). This is extremely important for making the issue tracker useful to developers. When an issue is too big and composite, it becomes intractable and drastically increases the likelihood that nothing will get done. It also tends to encourage pages and pages of general discussion that, while often good and helpful in itself, is simply not appropriate for qubes-issues. Therefore, I'm closing this issue, and I strongly encourage you to open separate issues for each of the (single, actionable) enhancements and bug fixes you believe are appropriate.

**Comment by andrewdavidwong** [comment]
Some more context from [this forum discussion](https://qubes-os.discourse.group/t/was-there-a-dom0-update-for-r4-0-in-the-last-few-days/4066/16?u=adw):

**fiftyfourthparallel:**
> [...] When there are no dom0 updates available, the Qubes Update tool prints:
> 
> Updating dom0
> 
> local:
>     ----------
> 
> This doesn’t provide enough information and can be confusing for new users and especially those switching from the CLI qubes-dom0-update (due to the current situation with metadata), because they don’t know what to expect and may not encounter an update for a long period due to the relatively sparse and irregular updates R4.0 dom0 receives. The lack of reporting could lead to confusion, like in this post. A simple addition of “No updates were found” to the printed message would be enough. [...]

**adw:**
> Hm, come to think of it, this might already be included in https://github.com/QubesOS/qubes-issues/issues/6299.

**fiftyfourthparallel:**
> I see why you’d think this might have been included, but the point the other user is making is much broader and isn’t as timely as the point I’m making, so I think some overlap should be tolerated if it means a focused spotlight is shone on the issue. Droves of qubes-dom0-update users will be migrating to the Updater due to the current situation and they will likely have fully updated dom0s, leading to the situation I described.
> 
> I think Salt’s false-positive reporting (leading to a ‘tick’ in the Updater GUI) creates further complications.

**adw:**
> I think what's happening here is that #6299 is actually too big of an issue. It violates our rule that [every issue must be about a single, actionable thing](https://www.qubes-os.org/doc/reporting-bugs/#every-issue-must-be-about-a-single-actionable-thing). Seeing this, your intuition is that your issue should be a separate one, not because it's not subsumed by #6299, but because you can see that #6299 has so much other stuff packed in that the distinct features of your specific issue (e.g., "timeliness") are not accurately reflected by the aggregate. You probably also have the sense (accurately, I think), that #6299, being so big and so general, will probably become one of those bike-shed "discussion" issues where nothing ever actually gets done. For all these reasons, I think it's appropriate to close #6299. I will open a separate issue for your specific thing.

**Comment by andrewdavidwong** [comment]
It's also worth noting that this is a partial duplicate (and already was when it was initially opened). For example, for "cancel" not really canceling dom0 updates, we already have https://github.com/QubesOS/qubes-issues/issues/6281.

**Comment by andrewdavidwong** [comment]
The crashing/freezing bug was already reported in #6156.

**Comment by andrewdavidwong** [comment]
As already mentioned above, the "QSB push" (which, I think is appropriate to generalize to "critical user action required") issue is already covered by #3430.

**Comment by andrewdavidwong** [comment]
The rest of the items in the list are more controversial.

> “Details” should display full process in real time, just like sudo dnf/apt upgrade dialog

I have also asked about this in the past. I don't know how difficult it would be. Since `qubesctl` also doesn't show this, it doesn't seem trivial. There is a general desire to focus on seamless automatic updates, where this functionality would not really be applicable, so at best this would probably be a minor long-term enhancement, possibly even "help wanted."

> Security / urgent updates labelled as such. Even a "traffic light" system.

This one seems hard, because AFAIK upstream doesn't categorize their updates that way (and we're certainly not going to do it for them). Maybe some distros do and some don't. Could we do it just for Qubes updates? Possibly, but I question the wisdom of doing something non-standard among distros when there is not a clear need for it. We already have a separate `security-testing` repo, so people who care strongly about getting security updates as early as possible can simply enable that.

> You shouldn’t need to click a checkbox to enable clicking on templates you want to force an upgrade. That should be enabled automatically.

This one seems especially controversial. I can imagine people arguing against it. Probably an empirical UX question.

> mouse-over each template should reveal what packages are going to be upgraded.

Seems to be another one where the question is whether the juice is worth the squeeze, especially with the move toward automatic updates and existing ways of seeing this information for technical users who really care about it.

-----

Since these remaining items are more in a gray area, and I am not fully convinced of them myself, I will leave it to others to make their case for them in separate issues.

**Comment by andrewdavidwong** [comment]
Automatic updates are covered in #4621.

**Comment by unman** [comment]
On Sat, May 22, 2021 at 12:31:59PM -0700, Andrew David Wong wrote:
> Automatic updates are covered in #4621.
> 

Andrew, thanks for your work on this and every where else, trying to
keep things sane.
