### ISSUE TITLE
Building the Ubuntu 20.04 template with qubes-builder on a Fedora 32 qube fails due to patch mismatch

### ISSUE THREAD

**Issue by asharp** [QubesOS/qubes-issues#6302]
**Qubes OS version**
4.0

**Affected component(s) or functionality**
qubes-builder

**Brief summary**
Building the Ubuntu 20.04 template fails using qubes-builder on a Fedora 32 Qube.

**How Reproducible**
Every time.

**To Reproduce**
Run the guide from https://blockforums.org/topic/451-guide-to-installing-qbuntu-ubuntu-2004-focal-fossa-templatevm-in-qubes-release-404-rc1 in a new fedora 32 qube.

**Expected behavior**
A Ubuntu 20.04 template rpm would be built.

**Actual behavior**
make qubes-vm fails with

> dpkg-source: info: applying patch-xen-gcc10-fixes.patch
> patching file tools/debugger/kdd/kdd.h
> patching file tools/libxl/libxlu_pci.c
> patching file tools/xenstore/utils.h
> patching file tools/xenstore/xenstored_core.h
> Hunk #1 FAILED at 209.
> 1 out of 1 hunk FAILED
> dpkg-source: info: the patch has fuzz which is not allowed, or is malformed
> dpkg-source: info: if patch 'patch-xen-gcc10-fixes.patch' is correctly applied by quilt, use 'quilt refresh' to update it
> dpkg-source: info: restoring quilt backup files for patch-xen-gcc10-fixes.patch
> dpkg-source: error: LC_ALL=C patch -t -F 0 -N -p1 -u -V never -E -b -B .pc/patch-xen-gcc10-fixes.patch/ --reject-file=- < debian-vm/debian/patches/patch-xen-gcc10-fixes.patch subprocess returned exit status 1
> dpkg-buildpackage: error: dpkg-source --before-build . subprocess returned exit status 2
> make[2]: *** [/home/user/qubes-builder/qubes-src/builder-debian//Makefile-legacy.debian:56: dist-package] Error 2
> make[1]: *** [Makefile.generic:191: packages] Error 1
> make: *** [Makefile:254: vmm-xen-vm] Error 1

**Additional context**
The patch doesn't quite match xenstored_core.h .

patch-xen-gcc10-fixes.patch has:
> diff --git a/tools/xenstore/xenstored_core.h b/tools/xenstore/xenstored_core.h
> index 9e9d960247..11aeabbbda 100644
> --- a/tools/xenstore/xenstored_core.h
> +++ b/tools/xenstore/xenstored_core.h
> @@ -209,7 +209,7 @@ void finish_daemonize(void);
>  /* Open a pipe for signal handling */
>  void init_pipe(int reopen_log_pipe[2]);
> 
> -xengnttab_handle **xgt_handle;
> +extern xengnttab_handle **xgt_handle;
> 
> int remember_string(struct hashtable *hash, const char *str);

as opposed to:
>/* Open a pipe for signal handling */
>void init_pipe(int reopen_log_pipe[2]);
>
> xengnttab_handle **xgt_handle;
>
> #endif /* _XENSTORED_CORE_H */

in xenstored_core.h itself.

**Solutions you've tried**
I've tried rerunning it on a new Qube, but had the same result.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
There doesn't seem to be any documentation on this.

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
A search didn't find any other similar issues.

**Comment by unman** [comment]
On Tue, Dec 22, 2020 at 06:38:43AM -0800, Alex Sharp wrote:
> **Qubes OS version**
> 4.0
> 
> **Affected component(s) or functionality**
> qubes-builder
> 
> **Brief summary**
> Building the Ubuntu 20.04 template fails using qubes-builder on a Fedora 32 Qube.
> 
> **How Reproducible**
> Every time.
> 
> **To Reproduce**
> Run the guide from https://blockforums.org/topic/451-guide-to-installing-qbuntu-ubuntu-2004-focal-fossa-templatevm-in-qubes-release-404-rc1 in a new fedora 32 qube.
> 
> **Expected behavior**
> A Ubuntu 20.04 template rpm would be built.
> 
> **Actual behavior**
> make qubes-vm fails with
> 
> `dpkg-source: info: applying patch-xen-gcc10-fixes.patch
> patching file tools/debugger/kdd/kdd.h
> patching file tools/libxl/libxlu_pci.c
> patching file tools/xenstore/utils.h
> patching file tools/xenstore/xenstored_core.h
> Hunk #1 FAILED at 209.
> 1 out of 1 hunk FAILED
> dpkg-source: info: the patch has fuzz which is not allowed, or is malformed
> dpkg-source: info: if patch 'patch-xen-gcc10-fixes.patch' is correctly applied by quilt, use 'quilt refresh' to update it
> dpkg-source: info: restoring quilt backup files for patch-xen-gcc10-fixes.patch
> dpkg-source: error: LC_ALL=C patch -t -F 0 -N -p1 -u -V never -E -b -B .pc/patch-xen-gcc10-fixes.patch/ --reject-file=- < debian-vm/debian/patches/patch-xen-gcc10-fixes.patch subprocess returned exit status 1
> dpkg-buildpackage: error: dpkg-source --before-build . subprocess returned exit status 2
> make[2]: *** [/home/user/qubes-builder/qubes-src/builder-debian//Makefile-legacy.debian:56: dist-package] Error 2
> make[1]: *** [Makefile.generic:191: packages] Error 1
> make: *** [Makefile:254: vmm-xen-vm] Error 1
> `
> 
> **Additional context**
> If you look at xenstored_core.h and the patch, the patch doesn't quite match.
> 
> patch-xen-gcc10-fixes.patch has
> `diff --git a/tools/xenstore/xenstored_core.h b/tools/xenstore/xenstored_core.h
> index 9e9d960247..11aeabbbda 100644
> --- a/tools/xenstore/xenstored_core.h
> +++ b/tools/xenstore/xenstored_core.h
> @@ -209,7 +209,7 @@ void finish_daemonize(void);
>  /* Open a pipe for signal handling */
>  void init_pipe(int reopen_log_pipe[2]);
>  
> -xengnttab_handle **xgt_handle;
> +extern xengnttab_handle **xgt_handle;
>  
>  int remember_string(struct hashtable *hash, const char *str);
> `
> as opposed to
> `/* Open a pipe for signal handling */
> void init_pipe(int reopen_log_pipe[2]);
> 
> xengnttab_handle **xgt_handle;
> 
> #endif /* _XENSTORED_CORE_H */
> ` in xenstored_core.h itself.
> 
> 
> **Solutions you've tried**
> I've tried rerunning it on a new Qube, but had the same result.
> 
> **Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
> There doesn't seem to be any documentation on this.
> 
> **Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
> A search didn't find any other similar issues.
> 
> 

It's this commit: 3bb54b43203b6a019cc5152f45b06154f8c27361
It also breaks the buster 4.0 build

Reverting the change, by :
- int remember_string(struct hashtable *hash, const char *str);
+ #endif /* _XENSTORED_CORE_H */

allows the package to be built.

**Comment by icequbes1** [comment]
I'm new to the party, but why doesn't the vmm-xen patch series in Debian (and Arch) follow the series in the rpm spec? They are both affected by the same build error.

vmm-xen/xen.spec.in has 275 patches applied for 4.8.5-28 in [fc32 vm build log](https://github.com/QubesOS/updates-status/issues/2238#issuecomment-745376108)

The latest commit in vmm-xen added `patch-0025-xenstore-rework-of-transaction-handling.patch`. This patch is a prequisite for the `patch-xen-gcc10-fixes.patch` which was also updated in the same commit.

Perhaps since Debian and Arch are not needed for dom0/hypervisor, it made sense to find the minimal patches for a proper/working build since only libraries and tools are used in domUs?

Is there something I fail to see to explain why all patches are not applied (so that the patched source tree is the same among all templates)? Or is it simply a "someone just needs to do the work" issue?

**Comment by marmarek** [comment]
> but why doesn't the vmm-xen patch series in Debian (and Arch) follow the series in the rpm spec?

Generally it should. There are some exceptions as we build just a subset of things in VM packages (for example stubdomain is excluded, and so its extra sources).

**Comment by asharp** [comment]
@unman confirmed, thanks for the fix!

**Comment by walliams** [comment]
i have this same exact issue attempting to create a focal+desktop VM on qubes 4.0. followed exact same procedure and get the same error even after applying the fix to the patch file mentioned here. is there a new mismatch?
