### ISSUE TITLE
Boot Issue From USB With Write-Protect Hardware Switch

### ISSUE THREAD

**Issue by jeffro256** [QubesOS/qubes-issues#6303]
### Qubes OS version:

R4.0

### Affected component(s) or functionality:

Bootup Sequence

---

### Steps to reproduce the behavior:

1. Install grub bootloader and /boot mount point to usb with hardware write switch (Legacy BIOS mode)
2. Try booting Qubes with switch on

### Expected or desired behavior:

The expected behavior was to be able to boot Qubes from a write-protected USB in Legacy BIOS mode.

### Actual behavior:

When the write protect switch is off, the bootup sequence works perfectly fine. When I turn it on it fails to boot.

Grub works great; it shows the menu with Xen. I can start Xen, and even type in my LUKS encryption password. However, between that step and the user login screen, I get dropped to an emergency Dracut shell. Sometimes it will let me type commands, and othertimes it wont, seemingly at random. 

### General notes:

I have been able to successfully dual-boot Qubes with Windows 10, keeping the bootloader and /boot mount point on a USB flash drive so as not to expose the unencrypted boot files to a malicious program or OS. However, I recently acquired a USB with a hardware write switch (Kanguru FlashBlu 30 8GB) and wanted to be able to keep the USB in without affording my Windows system the ability to override my Qubes boot partition.

System specs:
    Model: Dell XPS 15-9570
    CPU: Intel Core i7-8750H
    Architecture: x86_64
     

---

### I have consulted the following relevant [documentation](https://www.qubes-os.org/doc/):

https://www.qubes-os.org/doc/installation-troubleshooting/

**Comment by marmarek** [comment]
Try to modify `/etc/fstab` to include "ro" option for /boot partition.

**Comment by jeffro256** [comment]
Thanks, that worked! Question: why isn't that the default, aka why does the boot mount point need to be writeable?

**Comment by marmarek** [comment]
> Thanks, that worked! Question: why isn't that the default, aka why does the boot mount point need to be writeable?

To be able to install updates normally.

**Comment by andrewdavidwong** [comment]
It sounds like this was not actually a bug, just lack of user knowledge about how to do something non-Qubes-specific. 
Closing as "not an issue." If you believe this is a mistake, please leave a comment, and we'll be happy to take another look. Thank you.
