### ISSUE TITLE
Occasional "Failed to return clean data" error when updating templates

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#6304]
**Qubes OS version**

`R4.0`

**Affected component(s) or functionality**

Salt updates

**Brief summary**

When updating templates via Salt, I frequently get a `Failed to return clean data` error. It doesn't happen every time. Trying repeatedly allows the templates to be updated normally without error, so I'm assigning minor priority.

**How Reproducible**

On average, ~15 templates all being updated 5 times produces ~0-2 of these errors.

**To Reproduce**

1. Have ~15 templates (mixture of Fedora, Debian, Whonix).
2. In a bash script, run this five times in row over Tor.
```
sudo qubesctl --show-output --skip-dom0 --templates --max-concurrency 1 state.sls update.qubes-vm
```
3. When doing this, you will sometimes have the following error:
```
my-template-vm:
      ----------
      _error:
          Failed to return clean data
      retcode:
          None
      stderr:
      stdout:
          deploy
```

**Expected behavior**

No errors, or a more explanatory error message. If it's something user-fixable, it would be good to indicate what needs to be fixed. If it's just some transient Tor network problem, for example, and the best thing is for the user to just ignore and try again later, then having some indication of that would be very helpful.

**Actual behavior**

Error message with no indication of the nature of the problem or what (if anything) should be done.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

None found.

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

There are several [other issues](https://github.com/QubesOS/qubes-issues/issues?q=is%3Aissue+%22failed+to+return+clean+data%22) in which the `Failed to return clean data` error message is mentioned, but after reviewing all of those issues, I believe this report not to be a duplicate.

**Comment by DemiMarie** [comment]
IMO, a better approach would be for the update code to retry where needed.  Personally, I run my Arch updates using `until sudo ALL_PROXY=http://127.0.0.1:8082 pacman -Syu; do sleep 0.1||break; done` in zsh.

**Comment by unman** [comment]
On Thu, Dec 24, 2020 at 08:12:36AM -0800, Demi Marie Obenour wrote:
> IMO, a better approach would be for the update code to retry where needed.  

Isn't it better to take action to resolve the issue rather than just
retrying?
As I recall, you proposed and fixed this issue when it was salt ssh
related - just retrying wouldn't have helped there would it?

**Comment by DemiMarie** [comment]
> On Thu, Dec 24, 2020 at 08:12:36AM -0800, Demi Marie Obenour wrote: IMO, a better approach would be for the update code to retry where needed.
> Isn't it better to take action to resolve the issue rather than just retrying? As I recall, you proposed and fixed this issue when it was salt ssh related - just retrying wouldn't have helped there would it?

The `salt-ssh` problem was a bug in our fake-SSH program, and indeed retrying would not have helped.  That said, the fact that this only appears over Tor seems to imply that this is due to network problems, which retrying will often resolve.

@andrewdavidwong: would you mind sharing the system logs of the TemplateVMs in question?  Those might have the information needed to debug the problem.

**Comment by DemiMarie** [comment]
More specifically, the logs from the time of the update itself would be greatly appreciated.  Feel free to redact as much information as you want.

**Comment by andrewdavidwong** [comment]
> That said, the fact that this only appears over Tor seems to imply that this is due to network problems, which retrying will often resolve.

I don't know that it only happens over Tor. It's just that I do all of my regular updates over Tor, so I thought I'd mention it in case it's related.

> would you mind sharing the system logs of the TemplateVMs in question? Those might have the information needed to debug the problem.

> More specifically, the logs from the time of the update itself would be greatly appreciated. Feel free to redact as much information as you want.

Ok, where would I find the appropriate logs?

**Comment by DemiMarie** [comment]
> > That said, the fact that this only appears over Tor seems to imply that this is due to network problems, which retrying will often resolve.
> 
> I don't know that it only happens over Tor. It's just that I do all of my regular updates over Tor, so I thought I'd mention it in case it's related.
> 
> > would you mind sharing the system logs of the TemplateVMs in question? Those might have the information needed to debug the problem.
> 
> > More specifically, the logs from the time of the update itself would be greatly appreciated. Feel free to redact as much information as you want.
> 
> Ok, where would I find the appropriate logs?

`journalctl` should show them.  I am not sure what filters should be used.

**Comment by andrewdavidwong** [comment]
> `journalctl` should show them. I am not sure what filters should be used.

Ok, thanks. I'll see if I can get the logs the next time it occurs.

**Comment by andrewdavidwong** [comment]
The problem recurred. This time it was in the `whonix-ws` template. The problem occurred in an update on 2020-12-26 a little before 11:00 UTC. However, when I opened `journalctl` in `whonix-ws`, it said: `Logs begin at Sun 2020-12-27 20:06:02 UTC, end at Sun 2020-12-27 20:08:12 UTC.` So, for whatever reason, the log from when the problem occurred is not available.

**Comment by DemiMarie** [comment]
Is there any interesting information in the console logs?

**Comment by andrewdavidwong** [comment]
> Is there any interesting information in the console logs?

Where do I find those?

**Comment by DemiMarie** [comment]
The logs are in `/var/log/xen/console/guest-<vm-name>`, but you should copy them to a DispVM before viewing them.

**Comment by andrewdavidwong** [comment]
> The logs are in `/var/log/xen/console/guest-<vm-name>`, but you should copy them to a DispVM before viewing them.

Ok, thanks. Will check these the next time it occurs.
