### ISSUE TITLE
qvm-prefs --help-properties fails

### ISSUE THREAD

**Issue by 3hhh** [QubesOS/qubes-issues#6305]
**Qubes OS version**

4.0

**Affected component(s) or functionality**

`qvm-prefs`

**Brief summary**

`qvm-prefs --help-properties` fails

**How Reproducible**

Always.

**To Reproduce**
`qvm-prefs --help-properties`

**Expected behavior**

Outputs available properties.

**Actual behavior**

```
qvm-prefs --help-properties
usage: qvm-prefs [--verbose] [--quiet] [--help] [--help-properties]
                 [--hide-default] [--get] [--set] [--default]
                 VMNAME [PROPERTY] [VALUE]
qvm-prefs: error: the following arguments are required: VMNAME
```

**Solutions you've tried**

Adding an existing VM name makes it work.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

`man qvm-prefs`

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

None.

**Comment by unman** [comment]
This is, of course, in accord with both the help and the man page.
So this is a feature request (--help-properties should work
without a VMNAME), not a fail.

**Comment by marmarek** [comment]
Technically, properties (and their description) depends on VM type, so the list does depend on the VM you choose.

**Comment by 3hhh** [comment]
Well, if it is dynamic, this issue was pointless.

I was just irritated as the `qvm-ls --help-columns` text lead me to `qvm-prefs --help-properties` which then errored out.
