### ISSUE TITLE
pulseaudio-qubes places module-vchan-sink.so in /usr/lib/pulse-13.99 instead of /usr/lib/pulse-13.99.1 causing no audio on the ubuntu 20.04 template

### ISSUE THREAD

**Issue by asharp** [QubesOS/qubes-issues#6306]
**Qubes OS version**
4.0

**Affected component(s) or functionality**
qubes-builder

**Brief summary**
By default the built Ubuntu template doesn't have working sound. This appears to be due to module-vchan-sink.so being placed in /lib/pulse-13.99/modules by the package pulseaudio-qubes rather than /lib/pulse-13.99.1/modules with the rest of the pulseaudio modules. Moving it to /lib/pulse-13.99.1/modules in the template fixes the problem and audio then works.

I have noticed that even after moving the file, rarely pulseaudio still crashes on startup. Manually starting with pulseaudio --start -n --file=/etc/pulse/qubes-default.pa --exit-idle-time=-1 does fix audio though.

**How Reproducible**
100%

**To Reproduce**

1. Build template
2. Get no audio
3. Move the file
4. Get audio

**Expected behavior**
Working audio

**Actual behavior**
Not working audio

**Solutions you've tried**
Moving the file.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
There doesn't seem to be documentation on this

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
This doesn't seem to be related to an existing issue.

**Comment by icequbes1** [comment]
Confirming this is an issue as well.

gui-agent-linux/Makefile uses $PA_VER_MAJOR_MINOR for installing modules.

It appears Ubuntu uses $PA_VER_FULL for its modules directory.

Fedora 32 (14.0), Debian 10 (12.2), Archlinux (14.0) are all on MAJOR.MINOR versions at the moment.
