### ISSUE TITLE
Ubuntu 20.04 template builds with incompletely configured apt sources, preventing updates

### ISSUE THREAD

**Issue by asharp** [QubesOS/qubes-issues#6308]
**Qubes OS version**
4.0

**Affected component(s) or functionality**
qubes-builder

**Brief summary**
The Ubuntu 20.04 template is built with the qubes packages preinstalled, but without /etc/apt/sources.list.d/qubes-r4.list and the qubes repositories. As such the qubes packages can't be updated and no new qubes packages can be installed. 

**Expected behavior**
Qubes repositories would be installed in the template by default

># apt policy qubesdb
>qubesdb:
>  Installed: 4.0.15-1+focalu1
>  Candidate: 4.0.15-1+focalu1
>  Version table:
> *** 4.0.15-1+focalu1 100
>        100 /var/lib/dpkg/status
>     4.0.15-1+deb10u1 500
>        500 https://deb.qubes-os.org/r4.0/vm buster/main amd64 Packages

**Actual behavior**
Qubes repositories are not installed in the template by default

> # apt policy qubesdb
>
>qubesdb:
>  Installed: 4.0.15-1+focalu1
>  Candidate: 4.0.15-1+focalu1
>  Version table:
> *** 4.0.15-1+focalu1 100
>        100 /var/lib/dpkg/status

ie. there's no source for this package, it can't be updated.

**Additional context**
It looks like there's only generic debian packages in the repo rather than ubuntu specific, but they seem to work after i manually copied /etc/apt/sources.list.d/qubes-r4.list from a debian qube and ran apt-get update.

**Comment by unman** [comment]
On Thu, Dec 24, 2020 at 12:29:26PM -0800, Alex Sharp wrote:
> **Qubes OS version**
> 4.0
> 
> **Affected component(s) or functionality**
> qubes-builder
> 
> **Brief summary**
> The Ubuntu 20.04 template is built with the qubes packages preinstalled, but without /etc/apt/sources.list.d/qubes-r4.list and the qubes repositories. As such the qubes packages can't be updated and no new qubes packages can be installed. 
> 
> **Expected behavior**
> Qubes repositories would be installed in the template by default
> 
> ># apt policy qubesdb
> >qubesdb:
> >  Installed: 4.0.15-1+focalu1
> >  Candidate: 4.0.15-1+focalu1
> >  Version table:
> > *** 4.0.15-1+focalu1 100
> >        100 /var/lib/dpkg/status
> >     4.0.15-1+deb10u1 500
> >        500 https://deb.qubes-os.org/r4.0/vm buster/main amd64 Packages
> 
> **Actual behavior**
> Qubes repositories are not installed in the template by default
> 
> > # apt policy qubesdb
> >
> >qubesdb:
> >  Installed: 4.0.15-1+focalu1
> >  Candidate: 4.0.15-1+focalu1
> >  Version table:
> > *** 4.0.15-1+focalu1 100
> >        100 /var/lib/dpkg/status
> 
> ie. there's no source for this package, it can't be updated.
> 
> **Additional context**
> It looks like there's only generic debian packages in the repo rather than ubuntu specific, but they seem to work after i manually copied /etc/apt/sources.list.d/qubes-r4.list from a debian qube and ran apt-get update.
> 

There are no official "Qubes repositories" for Ubuntu packages, so there
is nothing to install in the template. Your expectations are misplaced.
I provide packages (and templates) at https://qubes.3isec.org but the best thing is to
build the packages yourself.

Don't mix Debian and Ubuntu packages - it's bad form, and they are not
necessarily compatible, and may interact in unexpected ways.

**Comment by kocmo** [comment]
@unman One of the packages present in deb.qubes-os.org, but not in in your Ubuntu repos, is qubes-snapd-helper.

**Comment by unman** [comment]
On Mon, Jan 04, 2021 at 09:21:11PM -0800, kocmo wrote:
> @unman One of the packages present in deb.qubes-os.org, but not in in your Ubuntu repos, is qubes-snapd-helper.
> 

Yes, it's not included in a standard build.
But *that* build is still broken - it needs to be updated to be closer to a
Debian-11.
