### ISSUE TITLE
flatpak installed applications do not show up in Qubes start menu

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#6325]
**Qubes OS version**
R4

**Affected component(s) or functionality**
Qubes start menu

**Brief summary**
Applications installed using flatpak do now show up in Qubes start menu.

**How Reproducible**
Always.

**To Reproduce**

Install an application using flatpak.

See Qubes start menu.

**Expected behavior**

Application installed using flatpak shows up in Qubes start menu.

**Actual behavior**

Application installed using flatpak does now shows up in Qubes start menu.

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

https://github.com/QubesOS/qubes-issues/issues/5076 (follow up feature once this ticket was implemented)

https://github.com/QubesOS/qubes-issues/issues/2766 (a much more integrated, sophisticated feature reqest)

**Comment by marmarek** [comment]
In the qube settings, applications tab, there is a "refresh" button that should retrieve current applications list. AFAIR flatpak currently does not trigger application list sync itself.

**Comment by TNTBOMBOM** [comment]
I think this issue with Flatpak has been largely resolved. There is only one app that isn't working for me when I click on its icon in the menu, which is the TorBrowser. It does nothing unless I start it from the terminal. However, all the other apps are working fine.
