### ISSUE TITLE
Error dom0 qmemman.systemstate: Xen free too small for satisfy assignments in journalctl

### ISSUE THREAD

**Issue by jamke** [QubesOS/qubes-issues#6328]
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
Memory manager (qmemman) in dom0. 

**Brief summary**
Every hour or even every couple of minutes in `journalctl -r` I see **red** lines with error:
```
Jan 01 12:00:30 dom0 qmemman.systemstate[5000]: Xen free = 526577477 too small for satisfy assignments! assigned_but_unused=513603439, domdict={'12': {'slow_memset_react': False, 'id': '12', 'mem_used': None, 'no_progress': False, 'memory_maximum': 851443712
````

**How Reproducible**
Every day, every hour.

**To Reproduce**
Install R4.0, use it and check `journalctl` for error messages.

**Expected behavior**
No error messages in `journalctl`

**Actual behavior**
Every hour or even every couple of minutes in `journalctl -r` I see *read* lines with error:
```
Jan 01 12:00:30 dom0 qmemman.systemstate[5000]: Xen free = 526577477 too small for satisfy assignments! assigned_but_unused=513603439, domdict={'12': {'slow_memset_react': False, 'id': '12', 'mem_used': None, 'no_progress': False, 'memory_maximum': 851443712
````

**Additional context**
I hope it does not affect the system work. But maybe I'm wrong and it has to be addressed by me as soon as possible?

**Solutions you've tried**
None.

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
I found none with this message substrings.

**Comment by jamke** [comment]
The easiest way to check these errors: `journalctl -r  -p 3` in `dom0`.
I see this error like every minute there. Can anyone check it too?

**Comment by zoechi** [comment]
I discovered this errors as well, while investigating frequent KDE freezes (no indication they are related so far though)

**Comment by donob4n** [comment]
Related to https://github.com/QubesOS/qubes-issues/issues/6314

I think that it is an expected "warning" if you open too many VM's for your memory. It just says that there are vm's demanding more memory than currently available. It should changed from log.error() to log.debug() or log.info().

https://github.com/QubesOS/qubes-core-admin/blob/df6407f50811573760879a7a48b9243ea31e504a/qubes/qmemman/__init__.py#L113

**Comment by jamke** [comment]
> I think that it is an expected "warning" if you open too many VM's for your memory. It just says that there are vm's demanding more memory than currently available. It should be changed from log.error() to log.debug() or log.info().

Many VMs - yes.
Not enough physical memory - probably not.

I think memory management in Qubes OS has some issue.
Something like this: Qubes OS gives a lot of memory to VMs (when those do not need it nor ask, just to distribute it) and then Qubes OS has issue to reallocated it (distribute) properly among many running VMs. And users see this error in logs constantly.

**Comment by zoechi** [comment]
I have 2 VMs that both only run Firefox and a third one where I run my development environment (Emacs, Chrome, Docker). The machine has 32GB of RAM.

**Comment by jamke** [comment]
> T: bug
> needs-diagnosis 

Any additional help needed to diagnose this bug? I can answer related questions if you needed it.

**Comment by jamke** [comment]
I have this bug on R4.1. Just checked the logs, it happens several times a day.
Once more: I can answer related questions to help with diagnosis.

**Comment by ubuntupunk** [comment]
Same issue here on 4.2.3

**Comment by ben-grande** [comment]
> I see _read_ lines with error:
> 
> ```
> Jan 01 12:00:30 dom0 qmemman.systemstate[5000]: Xen free = 526577477 too small for satisfy assignments! assigned_but_unused=513603439, domdict={'12': {'slow_memset_react': False, 'id': '12', 'mem_used': None, 'no_progress': False, 'memory_maximum': 851443712
> ```

- 526577477 -> Xen free
- 513603439 -> assigned_but_unused

Those are very close numbers in MiB.

> I have this bug on R4.1. Just checked the logs, it happens several times a day. Once more: I can answer related questions to help with diagnosis.

The message is logged to inform that qmemman might do a different thing as there is not enough memory free to be used by qubes that qmemman already assigned memory to them, but are not currently being used.

> > I think that it is an expected "warning" if you open too many VM's for your memory. It just says that there are vm's demanding more memory than currently available. It should be changed from log.error() to log.debug() or log.info().
> 
> Many VMs - yes. Not enough physical memory - probably not.
>
> I think memory management in Qubes OS has some issue. Something like this: Qubes OS gives a lot of memory to VMs (when those do not need it nor ask, just to distribute it) and then Qubes OS has issue to reallocated it (distribute) properly among many running VMs. And users see this error in logs constantly.

I believe this is a duplicate of:

- https://github.com/qubesos/qubes-issues/issues/9627

And diagnosis can be added there, as it already contains debugging steps for you to try. Although this is older than the other issue, I am closing it as duplicate as the other contains debugging steps, example output and a title containing the issue itself.

---

> It should be changed from log.error() to log.debug() or log.info().

`get_free_xen_mem()` affects a ton of things, so I think `error` is due.
