### ISSUE TITLE
USBGuard in sys-usb breaks USB device attach

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#6331]
**Qubes OS version**
`Qubes release 4.0 (R4.0)`

**Affected component(s) or functionality**
USB pass-through

**Brief summary**
If I run USBGuard in `sys-usb` and block USB devices by default, I cannot attach a USB device to another qube.  Allowing the USB device in USBGuard doesn’t help.

**How Reproducible**
100%

**To Reproduce**

1. Install USBGuard in the template for `sys-usb`.
2. Add `usbcore.authorized_default=0` to the `sys-usb` kernel command line.
3. Reboot `sys-usb`.
4. Attach a USB device from `sys-usb` to another qube.

**Expected behavior**
The attach succeeds, and the device can be used.

**Actual behavior**
The attach succeeds, but the device (a camera in this case) is not usable.  It *is* correctly detected by the frontend qube, but I can’t record video with it.

**Screenshots**
N/A

**Additional context**

**Solutions you've tried**
- Reloading the `usbip_host` kernel module
- Using the device in `sys-usb` before attaching it to the other qube.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

**Comment by marmarek** [comment]
Does manually authorizing the device (after connecting via qvm-usb) help?

**Comment by DemiMarie** [comment]
Manual authorization *before* connection does not help.
