### ISSUE TITLE
Qubes OS Stuck After Entering Disk Password.

### ISSUE THREAD

**Issue by Rudy006** [QubesOS/qubes-issues#6334]
I configured the OS for the first time, after configuring, it showed some sort of network error, I ignored it and continued, I logged in, and I was ready to use Qubes for the first time.

But when I booted it for the 2nd time, it was stuck at "enter disk password", I entered my password and pressed [ENTER], but it didn't do anything. The loading icon there moved to the end, but it also didn't do anything.

Please help, I have waited for 3 days to complete the installation.
I hope you understand my problem.

Regards
Rudraksh Singh

**Comment by andrewdavidwong** [comment]
Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this does not appear to be suitable for `qubes-issues`. We ask that you please post this on the [`qubes-users` mailing list or forum](https://www.qubes-os.org/support/) instead. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a brief comment explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.
