### ISSUE TITLE
Memory Management 

### ISSUE THREAD

**Issue by bluesteal** [QubesOS/qubes-issues#6335]
Hello,

If the amount of memory is changed in a qube; is it required to reboot the qube to have the memory be allocated to the available 

memory pool?

**Comment by andrewdavidwong** [comment]
Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this does not appear to be suitable for `qubes-issues`. We ask that you please post this on the [`qubes-users` mailing list or forum](https://www.qubes-os.org/support/) instead. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a brief comment explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.
