### ISSUE TITLE
NetworkManager applet (nm-applet) steals focus sometimes

### ISSUE THREAD

**Issue by AlxHnr** [QubesOS/qubes-issues#6338]
**Qubes OS version**

* R4.0 with latest patches
* i3 window manager, XFCE panel
* sys-net based on Fedora 32

**Affected component(s) or functionality**

GUI, system tray, network manager, XFCE, i3

**Brief summary**

When surfing the web, Firefox stops responding to my keyboard input. Pressing space opens nm-applets popup menu and all keys I press are redirected to this popup menu. To stop this I have to:

* Click on nm-applets tray icon to close the popup
* Fullscreen and un-fullscreen Firefox

**How Reproducible**

Occurs just a few times a week. But this has been happening consistently now for at least a year, probably even longer.
I'd have only seen this happen while using Firefox. Does not happen to tray applets other than nm-applet.

**To Reproduce**

1. Use i3 as your Window Manager, with XFCE panel
2. Ensure nm-applet is running in a Fedora 32 net vm
3. Use Firefox in an AppVM for a few days to see it happen once

**Expected behavior**

Focus stays on the current window.

**Actual behavior**

All keyboard keys are redirected to nm-applet, without clicking on its tray icon first.

**Screenshots**

**Additional context**

**Solutions you've tried**

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

**Comment by sebastianlutter** [comment]
I have the same behavior (R4.0 with i3wm with focus-follow-mouse=false). To get focus back to some window I open a second window (terminal), switch between them by mouse click and close the terminal again.

Using fullscreen and un-fullscreen is also a good workaround.

**Comment by AlxHnr** [comment]
I can reproduce a similar bug (i3-gaps as wm):

1. Select any text field in Firefox. Typing should work
2. Click on the nm-applet icon to open its menu
3. Click on the nm-applet icon again to close its menu
4. Click back into the text field in Firefox. Typing is broken

**Comment by DemiMarie** [comment]
Could this be an i3 bug?

**Comment by AlxHnr** [comment]
> Could this be an i3 bug?

Maybe. Occasionally when closing/switching windows in i3 my mouse and keyboard input gets forwarded to a window which isn't even focused. I stop this by fullscreening and unfullscreening the currently focused window. I can imagine it may cause people to input a password into the wrong window when not paying enough attention.

**Comment by AlxHnr** [comment]
Here is another way to run into this:

When casually moving my mouse over the nm-applet icon and holding my sensitive scroll wheel, it could cause a scroll event to be passed to nm-applet. This steals the focus. It doesn't help that nm-applet is located directly next to my volume widget on which I use my scroll wheel extensively.
