### ISSUE TITLE
[swdate synchronization fails, sometimes works]

### ISSUE THREAD

**Issue by qubed1** [QubesOS/qubes-issues#6339]
Can someone explain why most of the time swdate doesn't works properly? It seems like it tries to hold time correct but the systray icon above right displays most of the time it tries to fetch and then it has given up and very few times that swdate has successfully synchronized. 

Sadly i dont know how to append or share logfiles here on github, because im completely noob.

Greetings and stay safe
qubed1

**Comment by andrewdavidwong** [comment]
Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this does not appear to be suitable for `qubes-issues`. We ask that you please post this on the [`qubes-users` mailing list or forum](https://www.qubes-os.org/support/) instead. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a brief comment explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.
