### ISSUE TITLE
AEM-Qubes boot fails after installing AEM

### ISSUE THREAD

**Issue by aborrecimento** [QubesOS/qubes-issues#6340]
**Qubes OS version**

4.0.3

**Affected component(s) or functionality**

Anti Evil Maid

**Brief summary**

- booting AEM-Qubes option results in screen showing vertical colorful stripes
- system is not freezing

**How Reproducible**

100%

**To Reproduce**

Hardware:

- ThinkPad t430
- ivy bridge
- intel i7
- Optimus grafics (intel/nvidia)
- nouveau-driver
- legacy boot

Installing AEM:

- follow instructions here: https://github.com/QubesOS/qubes-antievilmaid
- the RACM-Update for 3rd-gen SINIT

**Expected behavior**

- On choosing "AEM Qubes" perfom measured boot and if unsuccessful fall back to normal boot

**Actual behavior**

- system boots to the phase between back screen with white cursor and plymouth boot screen
- screen shows vertical colored stripes and is unreadable
- Laptop reacts to Input and can be booted, but graphic output stays broken 

**Screenshots**

**Additional context**

**Solutions you've tried**

- change GPU in bios to intel: boot gets stuck at black screen with white cursor
- change GPU in bios to nvidia only: same issue
- set in grub: nouveau.modeset=0, removed "rhgb": same issue
- set in grub: disable plymouth: boot gets stuck in something like "Delegate password input to plymouth"

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

- https://github.com/QubesOS/qubes-antievilmaid
- Matrix and IRC

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

**Comment by jandryuk** [comment]
Hi, I'm familiar with TXT, but not the qubes implementation. I think you need 3rd-gen-i5-i7-sinit-67.zip SINIT ACM to do the measured not.  The RACM adds vulnerable ACMs to a blocklist, but it can't boot the system, from what I remember.

**Comment by aborrecimento** [comment]
@jandryuk I added  3rd-gen-i5-i7-sinit-67.bin to /boot as mentioned in the documentation. I had to do the RACM-Update never the less, because before the measured boot was failing to load " 3rd-gen-i5-i7-sinit-67.bin".

I found out some more facts: Actually the problems seams to be with the screen not the GPU. If I add an external display via MiniDisplayport it is activated, when plymouth loads. It shows the Qubes boot image, but no Password-Input (This is probably on the internal screen). I would like to try setting boot screen in the bios to VGA to test, but I do not own any VGA display any more.

I still cannot figure out if the measured boot is successful, as I cannot see if the secret gets displayed. I will try to get it running with external screen and collect the boot-log and txt-stat output.

@jandryuk Can you maybe explain to me how TXT can affect hardware functionality. I thought it is only measuring hardware params and calculates a hash.

Does anybody have an idea of a workaround? Can perhaps the graphical boot be turned of while keeping aem functionality in terms of pw entry and displaying the secret?

**Comment by jandryuk** [comment]
@aborrecimento TXT should not affect hardware functionality.

I would think MiniDisplayport would mirror the internal display.  Hitting `ESC` doesn't toggle the plymouth boot screen to messages?

In grub.cfg you can add logging=vga to the tboot line to have tboot write text to the display.  You may need to force grub to be in `terminal_output console` mode for it to display properly.  Not sure how to do that in Qubes.

**Comment by aborrecimento** [comment]
If I assume that @jandryuk is right and TXT does not affect the Hardware, there must be a difference in the boot process between 1. Qubes with AEM and 2. Qubes w/o AEM. To debug this further I post the GRUB-Menu-Entries:

```
if [ -d /aem/ ]; then
menuentry 'AEM Qubes, with Xen hypervisor' --class qubes --class gnu-linux --class gnu --class os --class xen $menuentry_id_option 'xen-gnulinux-simple-/dev/mapper/qubes_dom0-root' {
	insmod part_msdos
	insmod ext2
	set root='hd0,msdos1'
	if [ x$feature_platform_search_hint = xy ]; then
	  search --no-floppy --fs-uuid --set=root --hint-bios=hd0,msdos1 --hint-efi=hd0,msdos1 --hint-baremetal=ahci0,msdos1 --hint='hd0,msdos1'  f868b14f-e324-478b-a461-a8eb279b202c
	else
	  search --no-floppy --fs-uuid --set=root f868b14f-e324-478b-a461-a8eb279b202c
	fi
	echo	'Loading tboot ...'
	multiboot	/tboot.gz placeholder logging=memory,serial 
	echo	'Loading Xen 4.8.5-28.fc25 ...'
        if [ "$grub_platform" = "pc" -o "$grub_platform" = "" ]; then
            xen_rm_opts=
        else
            xen_rm_opts="no-real-mode edd=off"
        fi
	module	/xen-4.8.5-28.fc25.gz placeholder  console=none dom0_mem=min:1024M dom0_mem=max:4096M iommu=no-igfx ucode=scan smt=off ${xen_rm_opts}
	echo	'Loading Linux 4.19.155-1.pvops.qubes.x86_64 ...'
	module	/vmlinuz-4.19.155-1.pvops.qubes.x86_64 placeholder root=/dev/mapper/qubes_dom0-root ro rd.luks.uuid=luks-46a36886-0aea-47b1-b05f-9b5c5f1c08e0 rd.lvm.lv=qubes_dom0/root rd.lvm.lv=qubes_dom0/swap i915.alpha_support=1 plymouth.ignore-serial-consoles rhgb quiet rd.qubes.hide_all_usb  aem.uuid=f868b14f-e324-478b-a461-a8eb279b202c rd.luks.key=/tmp/aem-keyfile rd.luks.crypttab=no
	echo	'Loading initial ramdisk ...'
	module	/initramfs-4.19.155-1.pvops.qubes.x86_64.img
	echo	'Loading SINIT module 3rd_gen_i5_i7_SINIT_67.BIN ...'
	module	/3rd_gen_i5_i7_SINIT_67.BIN
}
```
```
menuentry 'Qubes, with Xen hypervisor' --class qubes --class gnu-linux --class gnu --class os --class xen $menuentry_id_option 'xen-gnulinux-simple-/dev/mapper/qubes_dom0-root' {
	insmod part_msdos
	insmod ext2
	set root='hd0,msdos1'
	if [ x$feature_platform_search_hint = xy ]; then
	  search --no-floppy --fs-uuid --set=root --hint-bios=hd0,msdos1 --hint-efi=hd0,msdos1 --hint-baremetal=ahci0,msdos1 --hint='hd0,msdos1'  f868b14f-e324-478b-a461-a8eb279b202c
	else
	  search --no-floppy --fs-uuid --set=root f868b14f-e324-478b-a461-a8eb279b202c
	fi
	echo	'Loading Xen 4.8.5-28.fc25 ...'
        if [ "$grub_platform" = "pc" -o "$grub_platform" = "" ]; then
            xen_rm_opts=
        else
            xen_rm_opts="no-real-mode edd=off"
        fi
	multiboot	/xen-4.8.5-28.fc25.gz placeholder  console=none dom0_mem=min:1024M dom0_mem=max:4096M iommu=no-igfx ucode=scan smt=off ${xen_rm_opts}
	echo	'Loading Linux 4.19.155-1.pvops.qubes.x86_64 ...'
	module	/vmlinuz-4.19.155-1.pvops.qubes.x86_64 placeholder root=/dev/mapper/qubes_dom0-root ro rd.luks.uuid=luks-46a36886-0aea-47b1-b05f-9b5c5f1c08e0 rd.lvm.lv=qubes_dom0/root rd.lvm.lv=qubes_dom0/swap i915.alpha_support=1 plymouth.ignore-serial-consoles rhgb quiet rd.qubes.hide_all_usb 
	echo	'Loading initial ramdisk ...'
	module	--nounzip   /initramfs-4.19.155-1.pvops.qubes.x86_64.img
}
```

**Comment by d-resistance** [comment]
Hello to the community of Qubes. After a long time I managed to properly and functionally install AEM. Using the same sinit module as you I had the same problem. I just found out what it was. The solution is to download the newest acm module that is not buggy. The link referring to racm in  QubesOS / qubes-antievilmaid  should be corrected also to the link below. 

https://cdrdv2.intel.com/v1/dl/getContent/630744?wapkw=intel%20txt%20sinit%20acm%20revocation%20

The sinit module you should use is called "SNB_IVB_SINIT_20190708_PW.bin"

**Comment by aborrecimento** [comment]
Hello @d-resistance, thx alot for your hint! It fixes my problem as well.

The documentation of qubes-antievilmaid needs to be updated. I will create a pull request.

Just one issue remains: When booting with AEM hibernation/suspend is not possible any more. The system can be suspended but not waken up. It gets stuck in a "half suspend" with HDDs, fan and Wifi on, but LED still showing suspend mode and screen turned of. Can somebody confirm this issue or even provide a fix?

**Comment by aborrecimento** [comment]
@d-resistance How did you find that download link? Is there any intel webpage referencing that ressource? I cannot find anything by searching.

**Comment by d-resistance** [comment]
@aborrecimento I found that link by searching in Intel's page "intel txt sinit acm revocation". The second link with  Content ID: 630744 is the link I published here. You can check it. Intel's page for acm modules has not been updated since 2018. This is not a problem from Qubes community. 

I don't know why or how you can fix the hibernation/suspend issue with your thinkpad model. I use x230. But if you read carefully  /usr/share/doc/tboot/README you can find the solution for your problem. Probably you have to configure grub.cfg tboot line.

It took me quite a while to be able to successfully install AEM on my x230 and x260. I'm not a developer or a computer expert. I move more in an experimental way which is time consuming, but successfully. I will post on Qubes OS forum a AEM setup guide on x230 and x260.
