### ISSUE TITLE
Qubes Updater fails for fedora-32 based template VMs

### ISSUE THREAD

**Issue by anthonyjmartinez** [QubesOS/qubes-issues#6343]
**Qubes OS version**
4.0

**Affected component(s) or functionality**
Qubes Updater

**Brief summary**
Qubes updater always fails for `fedora-32` templates

**How Reproducible**
100%

**To Reproduce**

1. Launch Qubes Updater
2. Select a template either identically `fedora-32` or created from a clone thereof
3. Press update

**Expected behavior**
Template is updated

**Actual behavior**
```
Updating fedora-32

fedora-32:
     - Rendering SLS 'base:update.qubes-vm' failed: Jinja variable 'dict object' has no attribute 'os'
```

**Screenshots**

**Additional context**

**Solutions you've tried**
Reinstalled template, but no change.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

**Comment by marmarek** [comment]
You need to switch `default-mgmt-dvm` to fedora-32 first. See https://www.qubes-os.org/news/2020/06/30/fedora-32-templates-available/

**Comment by anthonyjmartinez** [comment]
Thanks for the swift response and resolution. Indeed, I'd changed most of my VMs to have a `debian-10` template.
