### ISSUE TITLE
qubes-dom0-update: prevent concurrent execution

### ISSUE THREAD

**Issue by iamahuman** [QubesOS/qubes-issues#6345]
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
qubes-core-admin-linux: `qubes-dom0-update`

**Brief summary**
Multiple instances of `qubes-dom0-update` may run concurrently (e.g. `qubes-dom0-update --check-only` cron job running simultaneously with Qubes Updater), resulting in update cache corruption.

**How Reproducible**
100%

**To Reproduce**

1. Open terminal in dom0.
2. Start `qubes-dom0-update`.
3. Open another terminal in dom0.
4. Before the first update command finishes, wait for a while and start another `qubes-dom0-update`.

**Expected behavior**
Two instances of update command seralize with respect to each other.

**Actual behavior**
There are no attempts in synchronization, resulting in potential update data corruption.

**Screenshots**
TBD

**Additional context**
TBD

**Solutions you've tried**
Cleaning up cache every time such race condition happens is cumbersome.

Simplest solution would be to use locks to prevent concurrent invocation of `qubes-dom0-update`.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

- https://www.qubes-os.org/doc/software-update-dom0/

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
TBD

**Comment by alimirjamali** [comment]
PR Submitted. Low priority for review

**Comment by apparatius** [comment]
The `qubes-dom0-update` is calling itself from inside when switching the audio:
https://github.com/QubesOS/qubes-core-admin-linux/blob/3f0afb7030276f7afc0212bbaec187abdab72860/dom0-updates/qubes-dom0-update#L433
So this change is breaking the audio switching option:
https://forum.qubes-os.org/t/terrible-audio-quality-after-suspend-switching-to-pipewire-in-dom0-does-not-work/28893
Maybe add an option for `qubes-dom0-update` to skip the lock file check and use this option for `qubes-dom0-update` commands called from inside `qubes-dom0-update`?

**Comment by alimirjamali** [comment]
> The `qubes-dom0-update` is calling itself from inside when switching the audio:
> https://github.com/QubesOS/qubes-core-admin-linux/blob/3f0afb7030276f7afc0212bbaec187abdab72860/dom0-updates/qubes-dom0-update#L433
> So this change is breaking the audio switching option:
> https://forum.qubes-os.org/t/terrible-audio-quality-after-suspend-switching-to-pipewire-in-dom0-does-not-work/28893
> Maybe add an option for `qubes-dom0-update` to skip the lock file check and use this option for `qubes-dom0-update` commands called from inside `qubes-dom0-update`?
> Or skip the lock file check if `SWITCHING_AUDIO_IN_PROGRESS` variable is set.

Ops. I did not foresee that. I will work on a fix.

**Comment by alimirjamali** [comment]
PR Submitted
