### ISSUE TITLE
slow os loading, sys-usb won't start automatically (4.1, kernel - 5.4.88-1) 

### ISSUE THREAD

**Issue by IDBEHOLDS** [QubesOS/qubes-issues#6349]
**Qubes OS version**
4.1

**Affected component(s) or functionality**
dom0, sys-usb

**Brief summary**
after updates from qubes-dom0-repo and qubes-dom0-current-testing
operating system takes several times longer to load
gui terribly slow
sys-usb wont boot automatically
run it manually

**How Reproducible**

my current setup:
addons as gui/audio disabled by default install
sys-usb, sys-net, sys-firewall based on debian-11 with firmware-iwlwifi
default appvms as untrusted,vault,work,personal  disabled by default install
disposable vms - disabled by default install
sys-whonix also disabled too

i dont know related or not
everything i have is bunch of logs

[hypervisor.log](https://github.com/QubesOS/qubes-issues/files/5830655/hypervisor.log)
[guest-sys-usb.log](https://github.com/QubesOS/qubes-issues/files/5830701/guest-sys-usb.log)
[guest-sys-usb-dm.log](https://github.com/QubesOS/qubes-issues/files/5830702/guest-sys-usb-dm.log)
[guid.sys-usb.log](https://github.com/QubesOS/qubes-issues/files/5830703/guid.sys-usb.log)
[qubesdb.sys-usb.log](https://github.com/QubesOS/qubes-issues/files/5830711/qubesdb.sys-usb.log)
[sys-usb-dmesg.log](https://github.com/QubesOS/qubes-issues/files/5830715/sys-usb-dmesg.log)
[guest-sys-usb-dm.log](https://github.com/QubesOS/qubes-issues/files/5830746/guest-sys-usb-dm.log)

**To Reproduce**

1. 
2. 
3. 

**Expected behavior**

**Actual behavior**

**Screenshots**

**Additional context**

**Solutions you've tried**

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

**Comment by marmarek** [comment]
I believe this is the same issues as https://github.com/QubesOS/qubes-issues/issues/6174

**Comment by andrewdavidwong** [comment]
This appears to be a [duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.
