### ISSUE TITLE
qubes-vm-pulseaudio dependency failed with new pulseaudio-14.{1,2}

### ISSUE THREAD

**Issue by lubellier** [QubesOS/qubes-issues#6353]
**Qubes OS version**
`R4.0`

**Affected component(s) or functionality**
functionality: ArchLinux TemplateVM update, but later will impact all r4.0-*-stable
package: qubes-vm-pulseaudio
repository:  [gui-agent-linux](https://github.com/QubesOS/qubes-gui-agent-linux)

**Brief summary**
On Archlinux templateVM OS update, I got a package dependency error related to pulseaudio 14.2

**How Reproducible**
From Qube Manager, update the Archlinux Template VM

**To Reproduce**

1. Open Qube Manager
2. Right click on archlinux templateVM and choose Update qube

**Expected behavior**
OS update

**Actual behavior**
In the Details area of Qubes Updater, got the below pacman error
```
error: failed to prepare transaction (could not satisfy dependencies)
installing pulseaudio (14.2) breaks dependency 'pulseaudio<14.1' required by qubes-vm-pulseaudio
```

**Screenshots**
N/A

**Additional context**
Yes, another [pulseaudio update](https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/tags) that requires to update pulseaudio headers in gui-agent-linux! This time with pulseaudio **14.1 and 14.2** versions.

**Solutions you've tried**

- added pulseaudio headers to gui-agent-linux
- built qubes-vm-pulseaudio archlinux package 
- updated my archLinux repo

then my archLinux template got updated to pulseaudio-14.2

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
N/A

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
same as #6234 but this time for pulseaudio **14.1 and 14.2**

**Comment by lubellier** [comment]
I've just seen that @marmarek did the job on qubes-gui-agent-linux/master, commits: 
- [Add pulseaudio-14.1 headers](https://github.com/QubesOS/qubes-gui-agent-linux/commit/057bef245efb70f92735ed23edcaa89cbdcd5297)
- [Add pulseaudio 14.2 headers](https://github.com/QubesOS/qubes-gui-agent-linux/commit/291f697eb1a92f83954d75ee9d180906bda4ceed)

So just need to backport the [Add pulseaudio 14.2 headers](https://github.com/QubesOS/qubes-gui-agent-linux/commit/291f697eb1a92f83954d75ee9d180906bda4ceed) to qubes-gui-agent-linux/release4.0 (already done for [Add pulseaudio-14.1 headers](https://github.com/QubesOS/qubes-gui-agent-linux/commit/057bef245efb70f92735ed23edcaa89cbdcd5297))

**Comment by ejose19** [comment]
For any other time r4.0 doesn't get the headers update as quickly as master, one can run ```git cherry-pick -n $master_commit_hash``` using the commit that added the headers for master (given the changes are just bumping versions and adding the headers)

So for current issue one could do: ```cd qubes-gui-agent-linux && git tag -v $(git describe) && git checkout release4.0 && git cherry-pick -n 291f697eb1a92f83954d75ee9d180906bda4ceed```, run the build commands and cleanup after with ```git reset --hard HEAD```

**Comment by IDBEHOLDS** [comment]
agreed.  from 4.1

```
:: unable to satisfy dependency 'qubes-vm-qrexec' required by qubes-vm-dependencies
:: unable to satisfy dependency 'pulseaudio<14.1' required by qubes-vm-pulseaudio
:: unable to satisfy dependency 'qubes-vm-pulseaudio' required by qubes-vm-dependencies

```

**Comment by lubellier** [comment]
Marmarek added the [14.2 headers](https://github.com/QubesOS/qubes-gui-agent-linux/commit/4833e9340f8df97394240c74b543cbf27c5d70b3) and bumped the [4.0.35 version](https://github.com/QubesOS/qubes-gui-agent-linux/commit/5245d0668ce6458dcb43756c41399afc31147f47).

gui-agent-linux v4.0.35 (r4.0) is now available in current-testing repository
https://github.com/QubesOS/updates-status/issues/2331

So in few days will be available in stable repository.

**Comment by lubellier** [comment]
The gui-agent-linux 4.0.35 version [switched to stable 4 days ago](https://github.com/QubesOS/updates-status/issues/2331#issuecomment-784471037).
I built the ArchLinux packages and installed them on my ArchLinux Qubes, **all works fine**.

@andrewdavidwong : for me this issue is now closable.
