### ISSUE TITLE
Block devices too likely to get parsed

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#6355]
**Qubes OS version**
`Qubes release 4.0 (R4.0)`

**Affected component(s) or functionality**
dom0 udev rules

**Brief summary**
Certain block devices get probed for filesystems, etc when they really shouldn’t.

**How Reproducible**
100%

**To Reproduce**

Many ways; one of them is to create a LUKS device based on an LVM volume, and then assign the LUKS device to an AppVM.

**Expected behavior**
dom0 doesn’t probe the device.

**Actual behavior**
dom0 probes the device

**Screenshots**

**Additional context**

**Solutions you've tried**
I wrote some udev rules that solve the problem.  I will submit a PR for them.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

**Comment by iamahuman** [comment]
Duplicate of #2319

**Comment by andrewdavidwong** [comment]
> Duplicate of #2319

@DemiMarie, @marmarek, do you agree?

**Comment by DemiMarie** [comment]
@andrewdavidwong This issue is a bit more general, but overall I agree.
