### ISSUE TITLE
Problem installing QubesOS - Dracut-iniqueue[605]

### ISSUE THREAD

**Issue by Kingofwizard** [QubesOS/qubes-issues#6359]
Hello everybody!
I’m new to Qube and I’m having serious trouble in installing this system.
I’m installing Qube on the new Ryzen 7 5800x with 16GB of ram and a Geforce GTX 1060.
In order to install it I’m using a USB Sandisk 64GB.

At first after booting it would show me a black screen so I’ve followed the official guide for this issue ([UEFI Troubleshooting | Qubes OS](https://www.qubes-os.org/doc/uefi-troubleshooting/)) but it hasn’t worked out for me.

After trying everything is that section the best I have received is this:
![Qubes-problem](https://user-images.githubusercontent.com/76261261/105586526-4b4e5d00-5d91-11eb-9a1e-296dddc32e7b.jpg)

with the following error: Dracut-iniqueue[605] Dracut Timeout.
Right after this error it starts and emergency shell.

Does anybody know how can i fix this? is this an hardware problem?
I’ve also tried formatting the USB in both fat32 and NTFS with Ubuntu.

Sorry for any spelling error, and thanks for your help!

**Comment by DemiMarie** [comment]
Could be the Nvidia graphics card.  Have you tried disabling it in the firmware?

**Comment by andrewdavidwong** [comment]
Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this does not appear to be suitable for `qubes-issues`. We ask that you please post this on the [`qubes-users` mailing list or forum](https://www.qubes-os.org/support/) instead. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a brief comment explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.
