### ISSUE TITLE
On Qubes OS only, Emojis not visible at Chromium-based browsers. And Fedora 30 version of Firefox does not show emoji-containing kanban webpage at all.

### ISSUE THREAD

**Issue by xet7** [QubesOS/qubes-issues#6360]
**Qubes OS version**

R4.0

**Affected component(s) or functionality**

Chromium-based browsers on Standalone VM PVH copied from Debian 10 or Fedora 30 template
- Chromium Snap on Debian 10
- Chrome .rpm on Fedora
- MS Chromium Edge Linux .deb

And:
- Fedora current version of Firefox included, that is not newest

**Brief summary**

Does not work:
- At Chromium-based webbrowser leftmost demo card at [kanban board](https://boards.wekan.team/b/D2SzJKZDS4Z48yeQH/wekan-open-source-kanban-board-with-mit-license) there should be visible emoji :rainbow: :thumbsup: :100: , but it's not visible at all. Is some font missing?
- On Fedora 30 PVH Firefox browse right click / Inspect / Console shows this, and Wekan kanban board is not visible at all:
```
SyntaxError: invalid regexp group
```

Works:
- On newest Firefox downloaded from Firefox website, those emoji :rainbow: :thumbsup: :100: are visible.
- On Debian 10 PVH Firefox ESR, those emoji :rainbow: :thumbsup: :100: are visible.

**How Reproducible**

Not visible:
- Emojis not visible only happens on Qubes OS PVH Debian 10 and Fedora 30 using Chromium-based webbrowsers.
- `SyntaxError: invalid regexp group` only happens on Fedora 10 PVH included Firefox version.

Emojis are visible at:
- newest Firefox on Qubes OS
- Debian 10 Firefox ESR on PVH
- full HVM OS install
- Ubuntu 20.10/Mint newest/macOS Big Sur/Win10 full install of OS, works on Chromium-based browsers and newest Firefox.

**To Reproduce**

Snap version of Chromium on Debian 10 PVH:
1. `sudo apt install snapd`
2. shutdown and start PVH VM of Debian 10
3. `sudo snap install chromium`
4. `chromium`
5. Browse to [kanban board](https://boards.wekan.team/b/D2SzJKZDS4Z48yeQH/wekan-open-source-kanban-board-with-mit-license)
6. Leftmost demo card emoji :rainbow: :thumbsup: :100: are not visible.

Chrome:
1. Install Chrome .deb to Debian 10 PVH or .rpm to Fedora 30 PVH from Chrome website
2. Browse to [kanban board](https://boards.wekan.team/b/D2SzJKZDS4Z48yeQH/wekan-open-source-kanban-board-with-mit-license)
3. Leftmost demo card emoji :rainbow: :thumbsup: :100: are not visible.

MS Chromium Edge Linux:
1. Install .deb package from MS Chromium Edge website
2. Browse to [kanban board](https://boards.wekan.team/b/D2SzJKZDS4Z48yeQH/wekan-open-source-kanban-board-with-mit-license)
3. Leftmost demo card emoji :rainbow: :thumbsup: :100: are not visible.

Firefox of Fedora 30 PVH:
1. From Qubes OS menu, click `Disposable:fedora-30-dvm > Firefox`
2. Browse to [kanban board](https://boards.wekan.team/b/D2SzJKZDS4Z48yeQH/wekan-open-source-kanban-board-with-mit-license)
3. Kanban board webpage does not load at all. When doing right click / Inspect / Console, this error shows:
```
SyntaxError: invalid regexp group
```

**Expected behavior**

Emojis should be visible.

**Actual behavior**

At [kanban board](https://boards.wekan.team/b/D2SzJKZDS4Z48yeQH/wekan-open-source-kanban-board-with-mit-license):
- Emojis are not visible at all on Chomium-based browsers.
- Whole webpage is not visible at all on Fedora 30 PVH Firefox version.

**Screenshots**

Emoji visible at Firefox ESR Debian 10 PVH:

![emoji-firefox-esr](https://user-images.githubusercontent.com/15545/105618937-c9444f80-5df5-11eb-9fbf-ae9f2bf5df12.png)

Emoji not visible on Chrome on Debian 10 PVH:

![emoji-chrome-not-visible](https://user-images.githubusercontent.com/15545/105618939-d3fee480-5df5-11eb-899d-4fd1d326dba6.png)

Emoji not visible on Chromium Snap on Debian 10 PVH:

![emoji-chromium-snap](https://user-images.githubusercontent.com/15545/105618943-ee38c280-5df5-11eb-8308-37873d5b5a4e.png)

Emoji not visible on MS Chromium Edge on Debian 10 PVH:

![emoji-edge](https://user-images.githubusercontent.com/15545/105618947-fd1f7500-5df5-11eb-8d47-32cf9383e7b0.png)

Only in MS Chromium Edge seems to be these Violations errors. Those other isBoardAdmin errors are related to templates bug that I will fix later, it's not related to emojis.

![emoji-violation](https://user-images.githubusercontent.com/15545/105619136-52f51c80-5df8-11eb-9109-8f0c46298278.png)

Kanban webpage not visible at all at Firefox at Fedora 10 PVH, right click => Inspect => Console shows  `SyntaxError: invalid regexp group`:

![emoji-fedora-30](https://user-images.githubusercontent.com/15545/105618951-10324500-5df6-11eb-987b-790589818dbc.png)

**Additional context**

Emojis are visible at other OS like macOS Big Sur Safari, Win10 Chromium Edge, Ubuntu 20.10, newest Linux Mint Firefox and Chrome.

**Solutions you've tried**

- I did search issues for other browser issues that for some language suggested installing font for that language. Maybe some font is missing?

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

none

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

none

**Comment by andrewdavidwong** [comment]
Google Chrome in a Fedora 32 VM installed via `dnf` renders the emojis in your report normally.

(Note that Fedora 30 reached EOL a long time ago. Please try again with a supported Fedora version.)

**Comment by xet7** [comment]
Thanks!
