### ISSUE TITLE
T490s thinkpad trackball painful slow

### ISSUE THREAD

**Issue by sebastianlutter** [QubesOS/qubes-issues#6363]
**Qubes OS version**

R4.0

**Affected component(s) or functionality**

Thinkpad Trackball speed is very slow, changing accel settings do not help

**Brief summary**

On my t490s thinkpad laptop the Trackball is painful slow. Changing the `libinput Accel Speed` from `0.0` to `1.0` does not change much. I use i3wm.

This is a know problem with thinkpad trackballs:
* https://wayland.freedesktop.org/libinput/doc/latest/trackpoint-configuration.html
* https://askubuntu.com/questions/1241907/tpps-2-elan-trackpoint-on-thinkpad-t495-with-kubuntu-20-04/1291645#1291645

But since *libinput-utils* is not part of dom0 repo I cannot apply the known workaround in dom0.

**How Reproducible**

always

**To Reproduce**

1. get a t490s thinkpad laptop 
2. install R4.0 
3. install i3wm (don't think the WM makes any difference) 
4. use the trackball --> is is too slow to be used 

**Expected behavior**

libinput quirks are set depending on trackball, but having libinput-utils available in dom0 would be all I need to have `libinput quirks` tool available

**Actual behavior**

Slow trackball, no libinput-utils available in dom0

**Screenshots**

**Additional context**

The hardware details:
* `xinput list`
```
⎡ Virtual core pointer                    	id=2	[master pointer  (3)]
⎜   ↳ Virtual core XTEST pointer              	id=4	[slave  pointer  (2)]
⎜   ↳ Elan Touchpad                           	id=9	[slave  pointer  (2)]
⎜   ↳ Elan TrackPoint                         	id=10	[slave  pointer  (2)]
⎜   ↳ sys-usb: QEMU QEMU USB Tablet           	id=13	[slave  pointer  (2)]
⎣ Virtual core keyboard                   	id=3	[master keyboard (2)]
    ↳ Virtual core XTEST keyboard             	id=5	[slave  keyboard (3)]
    ↳ Power Button                            	id=6	[slave  keyboard (3)]
    ↳ Video Bus                               	id=7	[slave  keyboard (3)]
    ↳ Sleep Button                            	id=8	[slave  keyboard (3)]
    ↳ AT Translated Set 2 keyboard            	id=11	[slave  keyboard (3)]
    ↳ ThinkPad Extra Buttons                  	id=12	[slave  keyboard (3)]
    ↳ sys-usb: QEMU QEMU USB Tablet           	id=14	[slave  keyboard (3)]
```
* trackball xinput settings (`xinput --list-props 10`)
```
Device 'Elan TrackPoint':
	Device Enabled (150):	1
	Coordinate Transformation Matrix (152):	1.000000, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000, 0.000000, 0.000000, 1.000000
	libinput Accel Speed (296):	1.000000
	libinput Accel Speed Default (297):	0.000000
	libinput Accel Profiles Available (309):	1, 1
	libinput Accel Profile Enabled (310):	1, 0
	libinput Accel Profile Enabled Default (311):	1, 0
	libinput Natural Scrolling Enabled (298):	0
	libinput Natural Scrolling Enabled Default (299):	0
	libinput Send Events Modes Available (273):	1, 0
	libinput Send Events Mode Enabled (274):	0, 0
	libinput Send Events Mode Enabled Default (275):	0, 0
	libinput Left Handed Enabled (300):	0
	libinput Left Handed Enabled Default (301):	0
	libinput Scroll Methods Available (302):	0, 0, 1
	libinput Scroll Method Enabled (303):	0, 0, 1
	libinput Scroll Method Enabled Default (304):	0, 0, 1
	libinput Button Scrolling Button (312):	2
	libinput Button Scrolling Button Default (313):	2
	libinput Middle Emulation Enabled (314):	0
	libinput Middle Emulation Enabled Default (315):	0
	Device Node (276):	"/dev/input/event15"
	Device Product ID (277):	1267, 47
	libinput Drag Lock Buttons (307):	<no items>
	libinput Horizontal Scroll Enabled (308):	1
```

**Solutions you've tried**

Changing all available libinput settings of the trackball in dom0

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

**Comment by iprid** [comment]
@sebastianlutter
Technically you should be able to install in dom0 anything that's available for Fedora 25(I know - it's old).

So what about trying to use evdev as an alternative to libinput?
https://wiki.archlinux.org/index.php/Xorg

Another thing that would work for sure is for you to compile yourself a newer version of libinput or libinput-utils.

**Comment by sebastianlutter** [comment]
Looks like there is no libinput-utils package in Fedora 25 at all (only libinput): :(
* https://archives.fedoraproject.org/pub/archive/fedora/linux/releases/25/Workstation/x86_64/os/Packages/l/

I'll try to switch to evdev or compile libinput-utils on my own.
