### ISSUE TITLE
build and upload qubes-remote-support package

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#6364]
Task for @marmarek. (As confirmed by @marmarek.)

 - [ ] fork https://github.com/adrelanos/qubes-remote-support to https://github.com/QubesOS/qubes-remote-support
 - [ ] build https://github.com/QubesOS/qubes-remote-support
 - [ ] upload `qubes-remote-support`

----

Background:

https://www.whonix.org/wiki/Dev/Qubes_Remote_Support

**Comment by andrewdavidwong** [comment]
Was there a security discussion about this somewhere? I'd like to read more of the context.

This will be a sensitive topic for many users, who will want assurance that all remote functionality is strictly opt-in.

**Comment by marmarek** [comment]
> This will be a sensitive topic for many users, who will want assurance that all remote functionality is strictly opt-in.

This one is easy:
1. The package will not be installed by default.
2. The design requires explicit connection initiation by the user (no any open ports, extra network connections etc before that point). And when the user initiate the connection, it requires sharing a code word with the remote party to be able to connect.

**Comment by andrewdavidwong** [comment]
> > This will be a sensitive topic for many users, who will want assurance that all remote functionality is strictly opt-in.
> 
> This one is easy:
> 
> 1. The package will not be installed by default.
> 2. The design requires explicit connection initiation by the user (no any open ports, extra network connections etc before that point). And when the user initiate the connection, it requires sharing a code word with the remote party to be able to connect.

Good to hear. Thanks!

**Comment by tlaurion** [comment]
@marmarek the deadline for payout for that NlNet run is on April, after which money disappears.

Can we prioritize this?

**Comment by marmarek** [comment]
https://github.com/QubesOS/updates-status/issues/2353

**Comment by adrelanos** [comment]
* https://www.whonix.org/wiki/Remote_Administration#Qubes_-_SSH_or_VNC_into_Qubes_dom0
* https://www.whonix.org/wiki/Dev/Qubes_Remote_Support

**Comment by marmarek** [comment]
X2go is currently broken due to upstream issue: https://github.com/ArcticaProject/nx-libs/issues/1009. Fix was already proposed, but wasn't deployed yet.

**Comment by mfc** [comment]
I would add release notes tag and R4.1 milestone, i think this is quite notable *optional* functionality now present in R4.1.
