### ISSUE TITLE
Wifi no longer working after suspend on ThinkPad T480s

### ISSUE THREAD

**Issue by michaelschefczyk** [QubesOS/qubes-issues#6370]
Using current Oubes OS R4.0 with all current updates, wifi stopped working after waking up the ThinkPad T480s from sleep/suspend.

One does expect to be able to close the lid and open it again and then find wifi working as before the sleep/suspend situation.

Wifi did work without being impeded by sleep/suspend for much more than one year until approximately a week ago. Firmware was not updated, but dom0 including the kernel and Fedora VM were updated. Of course, I do not know which update did cause the change. I am also unable to use the correct nomenclature in terms of sleep states. However, needing to perform a reboot to regain wifi connectivity after having closed the lid is highly inconvenient.

**Comment by donob4n** [comment]
hi @michaelschefczyk have you check this https://www.qubes-os.org/doc/suspend-resume-troubleshooting/#drivers-do-not-reload-automatically-on-suspendresume ?

**Comment by andrewdavidwong** [comment]
Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this does not appear to be suitable for `qubes-issues`. We ask that you please post this on the [`qubes-users` mailing list or forum](https://www.qubes-os.org/support/) instead. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a brief comment explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.
