### ISSUE TITLE
file pool cannot start a VM with an exported volume

### ISSUE THREAD

**Issue by clayt0nk** [QubesOS/qubes-issues#6371]
**Qubes OS version**
4.0

**Affected component(s) or functionality**
a VM will not start

**Brief summary**
The VM in question has been working daily for a long time, and now fails to start after recent updates. No other recent changes.

**How Reproducible**
Failure is reproducible every time, even after reboot. dom0 is up to date.

**To Reproduce**

1. Start VM
2. Observer popup window saying "file pool cannot start a VM with an exported volume"

**Expected behavior**
VM starts

**Actual behavior**
VM does not start

**Additional context**
I have two pools, one the usual thin LVM on SSD called "lvm", another file pool on a spinning disk called "platter":

inux-kernel:5.8.16-1                              q40home-ssd                kernel       No
lvm:qubes_dom0/vm-q40home-ssd-private              q40home-ssd                private      Yes
lvm:qubes_dom0/vm-q40home-ssd-root                 q40home-ssd                root         No
lvm:qubes_dom0/vm-q40home-ssd-volatile             q40home-ssd                volatile     No

linux-kernel:5.4.88-1                              q40messaging-ssd           kernel       No
lvm:qubes_dom0/vm-q40messaging-ssd-private         q40messaging-ssd           private      Yes
lvm:qubes_dom0/vm-q40messaging-ssd-volatile        q40messaging-ssd           volatile     No
platter:appvms/q40messaging-ssd/root               q40messaging-ssd           root         No

linux-kernel:5.8.16-1                              q40work                    kernel       No
lvm:qubes_dom0/vm-q40work-root                     q40work                    root         No
platter:appvms/q40work/private                     q40work                    private      Yes
platter:appvms/q40work/volatile                    q40work                    volatile     No

Above are three VM's volume list. The first two start alright, the third (q40work) is the one that fails. It has root in the thin LVM, and private volume on file pool.

**Solutions you've tried**
Nothing yet, until data collection is complete, but I am betting if I clone q40work into the thin LVM pool it will probably work.

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
A search in open issues on "exported volume" gets zero hits.

**Comment by clayt0nk** [comment]
Further breakage that is most likely related: a backup that includes this same problematic  q40work VM also fails, immediately. Remove  q40work from the list of VMs to be backed up, and the backup continues normally.

**Comment by clayt0nk** [comment]
Just to raise the bar on this a bit: q40work VM fails to start from a template even when both VM and template are both in the same file pool ("platter" pool, from above).

**Comment by rustybird** [comment]
Some context:

In the legacy Qubes storage driver named `file`, compared to the `file-reflink` or `lvm_thin` drivers, many Qubes features either don't work at all or they're broken - sometimes dangerously. For example, backing up or cloning a running VM that has volumes stored in a `file` driver pool would lead to [corrupted backups/clones](https://github.com/QubesOS/qubes-issues/issues/4324).

Recently, safety checks were added to the `file` driver to abort a backup or clone operation on a running VM, and conversely to inhibit the VM from being started while such an operation is in progress.

But there are two false positives, where the safety checks trigger too often:

1. The first false positive is associated with bogus "file pool cannot start a VM with an exported volume" or "nested calls to export()" messages, and affects only Qubes R4.0. A [bugfix](https://github.com/QubesOS/qubes-core-admin/commit/fe66e3d) has already landed in the codebase (but hasn't been released yet), at the cost of a new false _negative_: The fixed R4.0 safety check can no longer inhibit a VM that's currently being backed up or cloned from being started, even though it's still just as dangerous. Anyway, if you don't want to wait for the qubes-core-dom0-4.0.57 package release, take a look at the linked commit: You could remove the same single line in R4.0 dom0's `/usr/lib/python3.5/site-packages/qubes/storage/file.py` and run `systemctl restart qubesd`. (Do not do this on R4.1!)

2. The second false positive is associated with bogus "file pool cannot export dirty volumes" messages. It affects both R4.0 and R4.1. A bugfix is in development at QubesOS/qubes-core-admin#384.

**Comment by DemiMarie** [comment]
I seriously suggest just deprecating the `file` driver, and removing it entirely in R4.1.  We might also want to provide a conversion tool so that users can upgrade to the `file-reflink` or `lvm_thin` drivers.  The easiest way to do this I can think of is in-place conversion of an ext4 filesystem to btrfs, which supports `file-reflink`.  @marmarek what do you think?

**Comment by clayt0nk** [comment]
`You could remove the same single line in R4.0 dom0's /usr/lib/python3.5/site-packages/qubes/storage/file.py and run systemctl restart qubesd.service`

Yes, it starts now, so far so good, thanks.

I am not all-in on thin LVM because, at least in the past, it has provided an easy path to bricking one's install simply by running out of space on dom0. As QubesOS is my main driver, that makes me very nervous. But I am not attached to the file driver, if file-reflink/btrfs play nice together that could be a happy alternative for my next machine with a similar setup. I have already been using btrfs on some of my non-Qubes machines for years, with zero complaints.

**Comment by DemiMarie** [comment]
> I am not all-in on thin LVM because, at least in the past, it has provided an easy path to bricking one's install simply by running out of space on dom0. As QubesOS is my main driver, that makes me very nervous. But I am not attached to the file driver, if file-reflink/btrfs play nice together that could be a happy alternative for my next machine with a similar setup. I have already been using btrfs on some of my non-Qubes machines for years, with zero complaints.

My understanding is that `file-reflink` doesn’t have any of the flaws of the `file` driver, since it is natively CoW.  Most of the problems of `file` are due to the `dm-snapshot` layer, which `file-reflink` doesn’t need.  The drawback is that ext4 isn’t supported by `file-reflink`.  However, ext4 filesystems can be converted to btrfs in-place.

**Comment by andrewdavidwong** [comment]
Reopening due to #6523.

**Comment by grote** [comment]
> The package qubes-core-dom0-4.0.57-1.fc25 has been pushed to the r4.0 stable repository for dom0.

While this might true, it seems that this package doesn't have the fix for Qubes 4.0. I have `qubes-core-dom0-4.0.58-1.fc25` installed, but `/usr/lib/python3.5/site-packages/qubes/storage/file.py` does not seem to include the fix for `is_dirty()`.

**Comment by grote** [comment]
I backported https://github.com/QubesOS/qubes-core-admin/commit/05eb0511932a47c5d2c8f462ee1fa829599b59dc to my `/usr/lib/python3.5/site-packages/qubes/storage/file.py` and now backup worked without complaining about the pool being dirty.

**Comment by DemiMarie** [comment]
@marmarek can that commit be backported to R4.0?

**Comment by rustybird** [comment]
Someone please add the "backport pending" label

**Comment by rustybird** [comment]
Thanks Demi!

@marmarek In case you're swamped, I just checked that the two commits from https://github.com/QubesOS/qubes-core-admin/pull/384 still apply cleanly on top of `release4.0`.
