### ISSUE TITLE
io-apic issues on install boot for 4.1 NUC10i5FNH

### ISSUE THREAD

**Issue by permezel** [QubesOS/qubes-issues#6372]
**Qubes OS version**

4.1

**Affected component(s) or functionality**

Initial boot

**Brief summary**

Initial boot fails.

**How Reproducible**

100%

**To Reproduce**

1. Burn most recent 4.1-rc
2. Boot on Intel NUC10
3. 

**Expected behavior**

I hope that it eventually boots and installs and runs

**Actual behavior**

Panic.

**Screenshots**

https://www.dropbox.com/s/jpo8yrb4atf442u/Intel-NUC10-4.1.pdf?dl=0

**Additional context**

noapic doesn't even get that far.

**Solutions you've tried**

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

**Comment by permezel** [comment]
This was using Qubes-4.1-20210117-x86_64.iso.

**Comment by permezel** [comment]
Comparing the `dmesg` output from booting `Fedora 33` and the `Qubes 4.1` attempt, I note some possibly salient differences.
Fedora:
```
[    0.268931] ..TIMER: vector=0x30 apic1=0 pin1=2 apic2=-1 pin2=-1
```
`Xen` hardwires: `vector=0xf0`.  The rest (`apic=`,`pin=`) are the same.

The newer version of `io_apic.c` has:
```
static inline void __init check_timer(void)
{
	struct irq_data *irq_data = irq_get_irq_data(0);
	struct mp_chip_data *data = irq_data->chip_data;
	struct irq_cfg *cfg = irqd_cfg(irq_data);
...
	apic_printk(APIC_QUIET, KERN_INFO "..TIMER: vector=0x%02X "
		    "apic1=%d pin1=%d apic2=%d pin2=%d\n",
		    cfg->vector, apic1, pin1, apic2, pin2);
```
The vector is not hard wired to 0xf0.  Initially, at boot time, the IRQ is being delivered to `IDT` vector 30, which is where IRQ0 comes in:
```
[root@nuc10 include]# cat /proc/interrupts 
            CPU0       CPU1       CPU2       CPU3       CPU4       CPU5       CPU6       CPU7       
   0:         18          0          0          0          0          0          0          0  IR-IO-APIC    2-edge      timer
```
As you see above, at boot time, there were 18 interrupts within the delay while `timer_irq_works()` was called.
From linux:
```
/*
 * IDT vectors usable for external interrupt sources start at 0x20.
 * (0x80 is the syscall vector, 0x30-0x3f are for ISA)
 */
#define FIRST_EXTERNAL_VECTOR		0x20
...

/*
 * Vectors 0x30-0x3f are used for ISA interrupts.
 *   round up to the next 16-vector boundary
 */
#define ISA_IRQ_VECTOR(irq)		(((FIRST_EXTERNAL_VECTOR + 16) & ~15) + irq)
```
Not sure about Xen:
```
/* IRQ0 (timer) is statically allocated but must be high priority. */
#define IRQ0_VECTOR             0xf0

/* Legacy PIC uses vectors 0x20-0x2f. */
#define FIRST_LEGACY_VECTOR     FIRST_DYNAMIC_VECTOR
#define LAST_LEGACY_VECTOR      (FIRST_LEGACY_VECTOR + 0xf)
```

When Qubes install boots, the code in the `Xen` version of `check_timer()` hardwires the `0xf0` vector, which *is* ultimately the vector used, but initially not the case for this particular NUC10 platform.

I'll poke around a bit trying to boot xen-4.14.1 directly on the NUC.  If I turn on `noapic` it does boot, and claims to be handing off to linux, but then blank screen for a while and then reboot.  There is no way to hook a serial port to the NUC so debug is a pain.

I'm not sure why we even care that the timer "works" thru the `i8259`.  We end up using the `ioapic` so why not just disable it and wire up whatever clock source we are going to select to the 0xf0 vector?

**Comment by elric1** [comment]
I have seen what I believe to the same symptoms on an Intel NUC10i7FNK that was delivered a couple of weeks ago.

**Comment by maximilize** [comment]
Seems like all NUC10 have this issue. Do you guys think there will be a fix in the near future for this? @permezel Seems like you dig quite deep into this matter already. How do you see this situation?

**Comment by iamahuman** [comment]
You can share Xen console with dom0 by passing `vga=keep` to Xen and `console=hvc0` to Linux. Not sure how well it interacts with `i915` though.

**Comment by permezel** [comment]
Planning on looking into this by trying to install Xen on NUC10 using Fedora 33 as dom0.  It has the same issues.

I like having a low-level serial based debug interface to stuff.  No serial port in the NUC means we are dependent on the USB-debug support.  I am hoping that the USB3 device in the NUC10 does support the USB 3.0 debug cable (type-A/type-A, m/m, high speed).  I've ordered one of these and it will show up in about a week.  It will require porting the xhci version of the early debug interface, but that should be straight forward.  Then I will be able to dump out various state from the apic and the IDT, etc, plus get some sort of debugger (breakpoint/resume/...) started.  Depending on what I find, I may be able to come up with something which is able to allow the NUC10 to boot plus not screw everything else up.  We'll see.

**Comment by permezel** [comment]
I confirm that this fixes the boot issues.  Thanks!
