### ISSUE TITLE
Update qvm-copy-to-vm doc 

### ISSUE THREAD

**Issue by behemothwerecat** [QubesOS/qubes-issues#6374]
**Qubes OS version**

4.0.3

**Affected component(s) or functionality**

Website - https://www.qubes-os.org/doc/tools/ 

**Brief summary**

qvm-copy-to-vm should be updated to qvm-copy. When you try to use the former, it outputs: 
```
qvm-copy-to-vm/qvm-move-to-vm tools are deprecated,
use qvm-copy/qvm-move to avoid typing target qube name twice
```

**Comment by andrewdavidwong** [comment]
In case you (or any others reading this) are not already aware, the documentation is a community effort, and everyone is welcome to contribute. (That's how things like this get updated!) So, if you'd like to get involved with the project, this is a great way to do it. You can read more about how to submit documentation changes here:

https://www.qubes-os.org/doc/doc-guidelines/

**Comment by brendanhoar** [comment]
In 4.0, qvm-copy-to-vm is still a valid dom0 tool (and qvm-copy does not work from dom0).
