### ISSUE TITLE
Various error messages during Qubes ISO build

### ISSUE THREAD

**Issue by permezel** [QubesOS/qubes-issues#6378]
**Qubes OS version**

4.0

**Affected component(s) or functionality**

Build

**Brief summary**

Some preliminary errors while building.

```
-> Installing core RPM packages...
error: setexecfilecon: (/usr/sbin/glibc_post_upgrade.x86_64) No such file or directory
error: setexecfilecon: (/sbin/ldconfig) No such file or directory
error: setexecfilecon: (/bin/sh) No such file or directory
Failed to connect to bus: No such file or directory
Running in chroot, ignoring request.
-> Installing package groups...usage: dnf [--allowerasing] [-b] [-C] [-c [config file]] [-d [debug level]]
           [--debugsolver] [--showduplicates] [-e ERRORLEVEL]
           [--rpmverbosity [debug level name]] [-q] [-v] [-y] [--assumeno]
           [--version] [--installroot [path]] [--enablerepo [repo]]
           [--disablerepo [repo]] [-x [package]] [--disableexcludes [repo]]
           [--repofrompath [repo,path]] [--noplugins] [--nogpgcheck]
           [--disableplugin [plugin]] [--color COLOR]
           [--releasever RELEASEVER] [--setopt SETOPTS] [--refresh] [-4] [-6]
           [--downloadonly] [-h]
Command line error: ambiguous option: --disable could match --disableexcludes, --disablerepo, --disableplugin
Group 'Buildsystem building group' is already installed, skipping.
Group 'Development Tools' is already installed, skipping.
Package rpm-sign-4.13.0.2-1.fc25.x86_64 is already installed, skipping.
-> Building gcc (gcc.spec) for fc25 dom0 (logfile: build-logs/gcc-dom0-fc25.log)
```

**How Reproducible**

I would assume 100% as it occurred during a clean build.

**To Reproduce**

1. Obtain a working build env for Qubes 4.0 ISO build ;-) 
2. Get as far as `make qubes`
3. make qubes
4. wait for error to appear.

**Expected behavior**

As someone who ruthlessly tracks down and kills any warnings whatsoever during a build process I am in charge of, I would expect there to be a clean build.  Approaching zero warnings. Less than or equal to zero errors.  Here we have errors.  Interestingly not process terminating errors.  Ignored errors.

**Actual behavior**

**Screenshots**

**Additional context**

Apparently, the `dnf` command syntax error comes from:
```
./prepare-chroot-builder:        chroot "$DIR" dnf config-manager --disable '*modular'
```
... so one might wonder what the consequences are.

I verified that this is the issue by `chroot`ing into the `chroot`ed root and issuing the command:

```
bash-4.3# dnf config-manager --disable '*wtf'
usage: dnf [--allowerasing] [-b] [-C] [-c [config file]] [-d [debug level]]
           [--debugsolver] [--showduplicates] [-e ERRORLEVEL]
           [--rpmverbosity [debug level name]] [-q] [-v] [-y] [--assumeno]
           [--version] [--installroot [path]] [--enablerepo [repo]]
           [--disablerepo [repo]] [-x [package]] [--disableexcludes [repo]]
           [--repofrompath [repo,path]] [--noplugins] [--nogpgcheck]
           [--disableplugin [plugin]] [--color COLOR]
           [--releasever RELEASEVER] [--setopt SETOPTS] [--refresh] [-4] [-6]
           [--downloadonly] [-h]
Command line error: ambiguous option: --disable could match --disablerepo, --disableplugin, --disableexcludes
```

If I issue the same command in the Fedora-32 system (as opposed to the -25 `chroot`) it works, as newer versions accept `--disable` and `--enable`.
```
[user@localhost qubes-builder]$ sudo dnf config-manager --disable '*wtf'
Error: No matching repo to modify: *wtf.
```
**Solutions you've tried**

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

**Comment by unman** [comment]
Out of interest what is the "working build env for Qubes 4.0 ISO build" that you are using?
