### ISSUE TITLE
build failure: /home/user/qubes-src/core-libvirt/libvirt-python-3.3.0.tar.gz: No such file or directory

### ISSUE THREAD

**Issue by permezel** [QubesOS/qubes-issues#6379]
**Qubes OS version**

4.0

**Affected component(s) or functionality**

QubesBuild ISO

**Brief summary**

The build fails due to missing `libvirt-python-3.3.0.tar.gz`. 
```
sudo chroot /home/dap/qubes-builder/chroot-dom0-fc25 su -c 'cd /home/user/qubes-src/core-libvirt; env BACKEND_VMM=xen  rpmbuild --define "dist .fc25" --define "fedora 25" --define "_rpmdir pkgs/dom0-fc25/" --define "qubes_builder 1" --define "backend_vmm xen" --define "source_date_epoch_from_changelog Y" --define "clamp_mtime_to_source_date_epoch Y" --define "use_source_date_epoch_as_buildtime Y" --define "dist .fc25" --define "fedora 25" --define "_rpmdir pkgs/dom0-fc25/" --define "qubes_builder 1" --define "backend_vmm xen" --define "source_date_epoch_from_changelog Y" --define "clamp_mtime_to_source_date_epoch Y" --define "use_source_date_epoch_as_buildtime Y"  --define "_sourcedir /home/user/qubes-src/core-libvirt" -bb libvirt-python.spec' - user
warning: Macro %version defined but not used within scope
error: File /home/user/qubes-src/core-libvirt/libvirt-python-3.3.0.tar.gz: No such file or directory
make[2]: *** [/home/dap/qubes-builder/qubes-src/builder-rpm/Makefile-legacy.rpmbuilder:82: dist-package-build] Error 1
make[2]: Leaving directory '/home/dap/qubes-builder'
make[1]: *** [Makefile.generic:191: packages] Error 1
make[1]: Leaving directory '/home/dap/qubes-builder'
make: *** [Makefile:262: core-libvirt-dom0] Error 1
```
Examination of the `chroot`ed directory shows that there is a file named `libvirt-3.3.0.tar.xz`:
```
[dap@localhost user]$ cd qubes-src/core-libvirt
[dap@localhost core-libvirt]$ ls -lrt
total 13996
-rw-rw-r--. 2 dap dap      455 May  6  2017 libvirt-3.3.0.tar.xz.asc
-rw-rw-r--. 2 dap dap 14043384 May  6  2017 libvirt-3.3.0.tar.xz
```
The Makefile references libvirt-3.3.0.tar.xz.
The source repository (https://libvirt.org/sources/) seems to only have the `.xz` version.

```

  | libvirt-3.3.0.tar.xz | 05-May-2017 21:46 | 13M |  
  | libvirt-3.3.0.tar.xz.asc | 05-May-2017 21:46 | 455 |  

```

It appears that the Makefile fetched the `.tar.xz` file, however, there is a reference to a .tar.gz file:
```
libvirt-python.spec:Source: https://libvirt.org/sources/python/%{name}-%{version}.tar.gz
```
I'm not sure whats happening here.  It is late, too many classes of wine, and I appear to be getting confused....

**How Reproducible**

Seems to be 100%

**To Reproduce**

1. make qubes
2. 
3. 

**Expected behavior**

An iso?

**Actual behavior**

**Screenshots**

**Additional context**

**Solutions you've tried**

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

**Comment by permezel** [comment]
Yes, clearly confused.  I'll close this until I get a better idea of what is happening.

**Comment by unman** [comment]
On Sun, Jan 31, 2021 at 04:19:57AM -0800, permezel wrote:
> Yes, clearly confused.  I'll close this until I get a better idea of what is happening.
> 

It would be much more helpful if you accumulated all your Fedora 33
build problems under ONE report, rather than raising many issues - that
will make it easier to resolve with documentation or changes to Builder.

Also, you may find it better to raise these problems in the mailing list
or Forum as support issues, and *then* raise issues here if they exist.
That's the right way to do it.
