### ISSUE TITLE
xorg-x11-drv-intel cannot be installed due to missing libXss.so.1()(64bit)

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#6380]
**Qubes OS version**
`Qubes release 4.0 (R4.0)`

**Affected component(s) or functionality**
`qubes-dom0-update`

**Brief summary**
`xorg-x11-drv-intel-2.99.917-49.20210126.fc25.x86_64` depends on `libXss.so.1()(64bit)`, but nothing provides that.

**How Reproducible**
100%

**To Reproduce**

1. `qubes-dom0-update` in dom0 

**Expected behavior**
Update succeeds

**Actual behavior**
Update fails

**Screenshots**

**Additional context**

**Solutions you've tried**
Removing `--best` from `qubes-domload-dom0-updates.sh` allows other updates to install.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

**Comment by marmarek** [comment]
Let me guess - you have disabled 'fedora' repository in dom0, right?

**Comment by DemiMarie** [comment]
:facepalm: Indeed I do.  Thanks!
