### ISSUE TITLE
Blackarchlinux tools brakes the template

### ISSUE THREAD

**Issue by jon-bit** [QubesOS/qubes-issues#6385]
**Qubes OS version**
4.0.4

**Affected component(s) or functionality**
Blackarchliux template

**Brief summary**
Whenever I boot up the VM it says that the qrexec is failing to connect after 60 sec. From what I can gather from what I've done it does not mount /proc/xen because it does not recognize the file type but I have no clue what to do from here.

**To Reproduce**
just make a archlinux template, install all the tools and this should be what happens

**Expected behavior**
it boots the VM.

**Actual behavior**
the VM crashes and shuts down.

**Solutions you've tried**
I'v tred mounting the /proc/xen manually but is still does not recognize the file system.

**Comment by andrewdavidwong** [comment]
Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this does not appear to be suitable for `qubes-issues`. We ask that you please post this on the [`qubes-users` mailing list or forum](https://www.qubes-os.org/support/) instead. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a brief comment explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.
