### ISSUE TITLE
pulseaudio update breaks pulseaudio-qubes

### ISSUE THREAD

**Issue by sidhussmann** [QubesOS/qubes-issues#6387]
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
pulseaudio-qubes in debian-testing 

**Brief summary**
pulseaudio 14.1 hit debian-testing and it breaks pulseaudio-qubes. 

**To Reproduce**
`sudo apt update && sudo apt dist-upgrade` in debian-testing 

**Additional context**
To me it looks like in debian it's just a matter of triggering the build pipeline, since the dependency of libpulse gets resolved in https://github.com/QubesOS/qubes-gui-agent-linux/blob/master/debian/rules

**Comment by iamahuman** [comment]
Related: #6353, #6348, #6234, #6172

**Comment by sidhussmann** [comment]
pulseaudio-qubes has been updated in debian-testing and matches the upstream dependencies of pulseaudio

**Comment by sidhussmann** [comment]
`pulseaudio-qubes` is getting removed again. @marmarek does it help if I reopen this issue each time I notice it? I'm assuming it does, since someone needs to manually trigger the pipeline that resolves the `libpulse` dependency in https://github.com/QubesOS/qubes-gui-agent-linux/blob/master/debian/rules

**Comment by iamahuman** [comment]
IMHO the pipeline should be launched automatically every time a new major version of `pulseaudio` lands in the upstream distro's "testing" repository.

**Comment by sidhussmann** [comment]
@iamahuman unfortunately it's not just major versions that break `pulseaudio-qubes`. We are now upgrading from 14.1-1 to 14.2-2..

**Comment by EncryptedGiraffe** [comment]
Indeed, the update to 14.2-2 has broken the audio in all of my debian-11 qubes in 4.1

**Comment by sidhussmann** [comment]
pulseaudio-qubes has been updated in debian-testing and matches the upstream dependencies of pulseaudio

**Comment by sidhussmann** [comment]
I re-open this issue as it's merely a matter of triggering the build pipeline.

**Comment by fepitre** [comment]
@sidhussmann which version? Currently the weekly updater is using Fedora versions which is currently `15.0` but I may use another input source.

**Comment by sidhussmann** [comment]
@fepitre it's regarding debian-testing on Qubes R4.0.

The dependency of `pulseaudio-qubes` gets resolved here: https://github.com/QubesOS/qubes-gui-agent-linux/blob/master/debian/rules

**Comment by sidhussmann** [comment]
@fepitre is there any way I can help/contribute regarding this issue?

**Comment by fepitre** [comment]
@sidhussmann You cannot do anything on your side. I see that 4.0.38 for gui-agent-linux is in `bullseye` for R4.0 so you should have pulseaudio-15 supported.

**Comment by sidhussmann** [comment]
@fepitre well, current debian-testing is the `bookworm` release, which does not have an apt repo at https://deb.qubes-os.org/r4.0/vm.

`pulseaudio` on Debian 11/bullseye is on version 14.2-2... So that clashes with pulseaudio from upstream debian-testing repo.

Is there any way I can help support debian-testing for https://deb.qubes-os.org/r4.0/vm?

**Comment by fepitre** [comment]
We talked recently to add `bookworm` to R4.1 which should be pretty straightforward. If you want to try, just build every components for `DISTS_VM=bookworm` after having added its support in `builder-debian` and give feedback and PR :)

**Comment by sidhussmann** [comment]
Thanks for clarifying this. This might be a good holiday project :)

**Comment by fepitre** [comment]
@sidhussmann I've created an issue to track the work for `bookworm`: https://github.com/QubesOS/qubes-issues/issues/7134. Don't hesitate to reference this issue in any contribution related to that work.

**Comment by DemiMarie** [comment]
The original problem has likely been fixed, as the Arch template keeps requiring support for newer and newer PulseAudio versions.  The more general problem is that PulseAudio modules use an unstable API, and this will be fixed when Qubes OS switches to PipeWire.
