### ISSUE TITLE
Arch template, pacman, http code 500 from proxy

### ISSUE THREAD

**Issue by raedah** [QubesOS/qubes-issues#6388]
Just built the latest arch-minimal template. Was able to get it to complete successfully, but pacman does not work. It appears to depend on a proxy that is returning a 500. I am told this is related to how templates are setup to use proxies. I dont know enough about the internals to identify it further.

**Comment by andrewdavidwong** [comment]
Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this does not appear to be suitable for `qubes-issues`. We ask that you please post this on the [`qubes-users` mailing list or forum](https://www.qubes-os.org/support/) instead. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a brief comment explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.

**Comment by raedah** [comment]
In case someone else has the same issue and finds this, the problem seems to be that the /run/qubes/bin/pacman script is no longer working. See https://github.com/QubesOS/qubes-core-agent-linux/blob/master/network/update-proxy-configs#L123
The workaround that can be used is to run  /bin/pacman  directly.
