### ISSUE TITLE
Failed to boot to install from USB with error "dracut-initqueue[503]: Warning: dracut-initqueue timeout - starting timeout scripts"

### ISSUE THREAD

**Issue by tonym1995** [QubesOS/qubes-issues#6389]
Hi, 
I am trying to install from USB but it fails with dracut-initqueue[503]: Warning: dracut-initqueue timeout - starting timeout scripts.

The boot log is attached.
[rdsosreport.txt](https://github.com/QubesOS/qubes-issues/files/5956183/rdsosreport.txt)

The laptop is a dell latitude 7280 with 8GB ram. BIOS version 1.9.3, TPM 2.0. I tried downgrading to TPM 1.2 but it fails with no error details. I have tried setting up the USB with DD but the bios will not allow a UEFI from the USB with iso9660 file format. Using Rufus to create the USB from the ISO allows the boot until the error has been reached. All virtualization is enabled. The laptop is currently running Linux Mint 5.4.0-60-generic #67-Ubuntu SMP Tue Jan 5 18:31:36 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux.

Any advice would be appreciated. All other tickets seem to be post install issues. This is an installation issue. If I can get the installer to boot I will upgrade the ram to 16GB and put in a 1TB SSD.

Many Thanks
Tony

**Comment by andrewdavidwong** [comment]
Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this does not appear to be suitable for `qubes-issues`. We ask that you please post this on the [`qubes-users` mailing list or forum](https://www.qubes-os.org/support/) instead. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a brief comment explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.
