### ISSUE TITLE
usb attach of specific device fails

### ISSUE THREAD

**Issue by aborrecimento** [QubesOS/qubes-issues#6392]
**Qubes OS version**

Qubes release 4.0 (R4.0)
- dom0: 5.4.88-1.qubes.x86_64
- sys-usb: same

**Affected component(s) or functionality**

- qubes-app-linux-usb-proxy

**Brief summary**

Attaching a device and recognizing in sys-usb works. Attaching to other qubes does not work.

**How Reproducible**

- 100%

**To Reproduce**

1. Connect specific device (Android mobile device, MTP and/or adb ) to any USB-Port
2. Device appears in sys-usb and works there
3. Attach device to any other qube (fedora or debian)

**Expected behavior**

- The device appears in other qube and is usable

**Actual behavior**

Case 1 MTP:

- device can get attached to any qube, but does not work
- it gets detached from qube
dmesg in qube with device attached:
```
[38053.453091] usb usb1-port1: Cannot enable. Maybe the USB cable is bad?
[38053.453944] usb 1-1: USB disconnect, device number 2
```
Case 2 adb:

- device appears functional in sys-usb, but cannot be attached to any other qube
Error message:
```
Device attach failed: /usr/lib/qubes/usb-import: 94: echo: echo: I/O errorAttach timeout, check kernel log for details. VM: "personal" File: "/usr/lib/qubes/usb-import" Version Control: https://github.com/QubesOS/qubes-app-linux-usb-proxy/blob/master/src/usb-import
```
- There is no useful information in any kernel log (dom0 none, sys-usb just a disconnect and reconnect).

**Solutions you've tried**

- different android connection modes
- different USB-Ports/Hubs (USB3, USB2)
- fedora and debian qubes

**Comment by 0spinboson** [comment]
duplicate: https://github.com/QubesOS/qubes-issues/issues/6330

**Comment by aborrecimento** [comment]
@0spinboson Sry for the duplicate. Haven't found the issue for some reason.
