### ISSUE TITLE
qubesd: NotImplementedError: Volume FileVolume has is_outdated() not implemented.

### ISSUE THREAD

**Issue by iamahuman** [QubesOS/qubes-issues#6398]
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
[qubes-core-admin](https://github.com/QubesOS/qubes-core-admin), qubesd

**Brief summary**
When a VM calls `qubes.NotifyUpdates` in dom0, qubesd emits unhandled exception `NotImplementedError: Volume FileVolume has is_outdated() not implemented.`.

**How Reproducible**
100%

**To Reproduce**

1. Create an AppVM with at least one volume residing in a `file` pool
2. Start the VM
3. Run in VM: `echo 1 | qrexec-client-vm dom0 qubes.NotifyUpdates`

**Expected behavior**
No warning logs in `/var/log/qubes.log`.

**Actual behavior**
In `/var/log/qubes/qubes.log`:

```
unhandled exception while calling src=b'<<<VM>>>' meth=b'qubes.NotifyUpdates' dest=b'dom0' arg=b'' len(untrusted_payload)=2
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/qubes/api/__init__.py", line 275, in respond
    untrusted_payload=untrusted_payload)
  File "/usr/lib64/python3.5/asyncio/futures.py", line 381, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib64/python3.5/asyncio/tasks.py", line 310, in _wakeup
    future.result()
  File "/usr/lib64/python3.5/asyncio/futures.py", line 294, in result
    raise self._exception
  File "/usr/lib64/python3.5/asyncio/tasks.py", line 240, in _step
    result = coro.send(None)
  File "/usr/lib64/python3.5/asyncio/coroutines.py", line 210, in coro
    res = func(*args, **kw)
  File "/usr/lib/python3.5/site-packages/qubes/api/misc.py", line 130, in qubes_notify_updates
    if self.src.storage.outdated_volumes:
  File "/usr/lib/python3.5/site-packages/qubes/storage/__init__.py", line 570, in outdated_volumes
    if volume.is_outdated():
  File "/usr/lib/python3.5/site-packages/qubes/storage/__init__.py", line 258, in is_outdated
    raise self._not_implemented("is_outdated")
NotImplementedError: Volume FileVolume has is_outdated() not implemented
```

**Screenshots**
N/A

**Additional context**
`file` pool has been deprecated and is only used for VMs migrated from R3.2. The default is lvm_thin or reflink depending on disk partition layout.

This bug does not leave Qubes in an inconsistent state.  The only implication of this bug is that a VM can flood `qubes.log` and rotate out (evict) old logs.

**Solutions you've tried**
N/A

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
- https://www.qubes-os.org/doc/storage-pools/
- https://www.qubes-os.org/doc/secondary-storage/

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
None.

**Comment by marmarek** [comment]
While we do need to fix it somehow (at least put a placeholder in place), please, stop using plain "file" storage pool driver. It is very inefficient in many ways, and is going to be removed at some point.

**Comment by iamahuman** [comment]
@marmarek Thanks for your comment, I was going to mention it in Addition Context later.

I had been using `file` pool mainly to run the web browser while troubleshooting the LVM pool. Now only the private/volatile volume lives there and they take up only a few megabytes, so I guess it's fine for now.

**Comment by DemiMarie** [comment]
@marmarek can we go ahead and remove it in `master`?

**Comment by marmarek** [comment]
No, we can not. There needs to be a proper migration period. See #6399
