### ISSUE TITLE
Which of this is a webcam? and how do i attach it to qube (webcam works in dom0) [its hp 1080p camera]

### ISSUE THREAD

**Issue by yoge67855** [QubesOS/qubes-issues#6400]
BACKEND:DEVID  DESCRIPTION                                                                                                      USED BY
dom0:00_00.0   Host bridge: Advanced Micro Devices, Inc. [AMD] Family 17h (Models 00h-0fh) Root Complex                         
dom0:00_00.2   IOMMU: Advanced Micro Devices, Inc. [AMD]                                                                        
dom0:00_01.0   Host bridge: Advanced Micro Devices, Inc. [AMD] Family 17h (Models 00h-0fh) PCIe Dummy Host Bridge               
dom0:00_01.3   PCI bridge: Advanced Micro Devices, Inc. [AMD]                                                                   
dom0:00_02.0   Host bridge: Advanced Micro Devices, Inc. [AMD] Family 17h (Models 00h-0fh) PCIe Dummy Host Bridge               
dom0:00_03.0   Host bridge: Advanced Micro Devices, Inc. [AMD] Family 17h (Models 00h-0fh) PCIe Dummy Host Bridge               
dom0:00_03.1   PCI bridge: Advanced Micro Devices, Inc. [AMD]                                                                   
dom0:00_03.3   PCI bridge: Advanced Micro Devices, Inc. [AMD]                                                                   
dom0:00_04.0   Host bridge: Advanced Micro Devices, Inc. [AMD] Family 17h (Models 00h-0fh) PCIe Dummy Host Bridge               
dom0:00_07.0   Host bridge: Advanced Micro Devices, Inc. [AMD] Family 17h (Models 00h-0fh) PCIe Dummy Host Bridge               
dom0:00_07.1   PCI bridge: Advanced Micro Devices, Inc. [AMD] Family 17h (Models 00h-0fh) Internal PCIe GPP Bridge 0 to Bus B   
dom0:00_08.0   Host bridge: Advanced Micro Devices, Inc. [AMD] Family 17h (Models 00h-0fh) PCIe Dummy Host Bridge               
dom0:00_08.1   PCI bridge: Advanced Micro Devices, Inc. [AMD] Family 17h (Models 00h-0fh) Internal PCIe GPP Bridge 0 to Bus B   
dom0:00_14.0   SMBus: Advanced Micro Devices, Inc. [AMD] FCH SMBus Controller                                                   
dom0:00_14.3   ISA bridge: Advanced Micro Devices, Inc. [AMD] FCH LPC Bridge                                                    
dom0:00_18.0   Host bridge: Advanced Micro Devices, Inc. [AMD] Family 17h (Models 00h-0fh) Data Fabric: Device 18h; Function 0  
dom0:00_18.1   Host bridge: Advanced Micro Devices, Inc. [AMD] Family 17h (Models 00h-0fh) Data Fabric: Device 18h; Function 1  
dom0:00_18.2   Host bridge: Advanced Micro Devices, Inc. [AMD] Family 17h (Models 00h-0fh) Data Fabric: Device 18h; Function 2  
dom0:00_18.3   Host bridge: Advanced Micro Devices, Inc. [AMD] Family 17h (Models 00h-0fh) Data Fabric: Device 18h; Function 3  
dom0:00_18.4   Host bridge: Advanced Micro Devices, Inc. [AMD] Family 17h (Models 00h-0fh) Data Fabric: Device 18h; Function 4  
dom0:00_18.5   Host bridge: Advanced Micro Devices, Inc. [AMD] Family 17h (Models 00h-0fh) Data Fabric: Device 18h; Function 5  
dom0:00_18.6   Host bridge: Advanced Micro Devices, Inc. [AMD] Family 17h (Models 00h-0fh) Data Fabric Device 18h Function 6    
dom0:00_18.7   Host bridge: Advanced Micro Devices, Inc. [AMD] Family 17h (Models 00h-0fh) Data Fabric: Device 18h; Function 7  
dom0:01_00.0   USB controller: Advanced Micro Devices, Inc. [AMD]                                                               
dom0:01_00.1   SATA controller: Advanced Micro Devices, Inc. [AMD]                                                              
dom0:01_00.2   PCI bridge: Advanced Micro Devices, Inc. [AMD]                                                                   
dom0:02_00.0   PCI bridge: Advanced Micro Devices, Inc. [AMD]                                                                   
dom0:02_01.0   PCI bridge: Advanced Micro Devices, Inc. [AMD]                                                                   
dom0:02_04.0   PCI bridge: Advanced Micro Devices, Inc. [AMD]                                                                   
dom0:02_06.0   PCI bridge: Advanced Micro Devices, Inc. [AMD]                                                                   
dom0:02_07.0   PCI bridge: Advanced Micro Devices, Inc. [AMD]                                                                   
dom0:03_00.0   Ethernet controller: Intel Corporation I211 Gigabit Network Connection                                           sys-net
dom0:07_00.0   Network controller: Realtek Semiconductor Co., Ltd. RTL8188EE Wireless Network Adapter                           sys-net
dom0:08_00.0   VGA compatible controller: NVIDIA Corporation GP106 [GeForce GTX 1060 6GB]                                       
dom0:08_00.1   Audio device: NVIDIA Corporation GP106 High Definition Audio Controller                                          
dom0:09_00.0   Non-Volatile memory controller: Lite-On Technology Corporation                                                   
dom0:0a_00.0   Non-Essential Instrumentation: Advanced Micro Devices, Inc. [AMD]                                                
dom0:0a_00.2   Encryption controller: Advanced Micro Devices, Inc. [AMD]                                                        
dom0:0a_00.3   USB controller: Advanced Micro Devices, Inc. [AMD] USB 3.0 Host controller                                       
dom0:0b_00.0   Non-Essential Instrumentation: Advanced Micro Devices, Inc. [AMD]                                                
dom0:0b_00.2   SATA controller: Advanced Micro Devices, Inc. [AMD] FCH SATA Controller [AHCI mode]                              
dom0:0b_00.3   Audio device: Advanced Micro Devices, Inc. [AMD]

**Comment by unman** [comment]
On Fri, Feb 12, 2021 at 12:54:59PM -0800, Demi Marie Obenour wrote:
> Closed #6400.
> 

Can we *not* close issues without an explanation.
If you think the issue is best dealt with somewhere else, tell the user where that
is, so they are not completely lost.

**Comment by andrewdavidwong** [comment]
Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this does not appear to be suitable for `qubes-issues`. We ask that you please post this on the [`qubes-users` mailing list or forum](https://www.qubes-os.org/support/) instead. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a brief comment explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.
