### ISSUE TITLE
Unable to uninstall KDE from dom0 using documentation instructions

### ISSUE THREAD

**Issue by ultrablasta** [QubesOS/qubes-issues#6401]
**Qubes OS version**
R4.0

**Brief summary**
I am aware that KDE has its issues at the moment within Qubes, however I was able to install it. I then wanted to uninstall it, and found the documentations recommendation to uninstall it does nothing:

```
sudo dnf remove kdelibs,plasma-workspace
No match for argument: kdelibs,plasma-workspace
Error: No packages marked for removal.
```

The documentation should really be updated with a warning about how KDE is not working properly within Qubes.

[Edit: By the way, I now do not actually want to remove KDE as it now makes some dom0 programs look really aesthetic such as Qubes Manager. If I could remove it and keep the aesthetics that would be great]

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
[https://www.qubes-os.org/doc/kde/](https://www.qubes-os.org/doc/kde/)

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

#5904
#2921

**Comment by unman** [comment]
On Fri, Feb 12, 2021 at 01:53:08PM -0800, ultrablasta wrote:
> **Qubes OS version**
> R4.0
> 
> **Brief summary**
> I am aware that KDE has its issues at the moment within Qubes, however I was able to install it. I then wanted to uninstall it, and found the documentations recommendation to uninstall it does nothing:
> 
> ```
> sudo dnf remove kdelibs,plasma-workspace
> No match for argument: kdelibs,plasma-workspace
> Error: No packages marked for removal.
> ```
> 
> The documentation should really be updated with a warning about how KDE is not working properly within Qubes.
> 
> **Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
> [https://www.qubes-os.org/doc/kde/](https://www.qubes-os.org/doc/kde/)
> 
> **Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
> 
> #5904
> #2921
> 

Kde works fine in Qubes with very minor issues - the only significant
one being the failure to display the nm-applet icon in the task bar.
Otherwise KDE is far superior to Xfce and makes for a much better Qubes
user experience.

The command you want should you wish (mistakenly) to remove it is:
`dnf remove kdelibs plasma-workspace`

**Comment by unman** [comment]
@ultrablasta, @andrewdavidwong  I've updated the documentation typo, so this can be closed.

**Comment by ultrablasta** [comment]
@unman Huh weird I assumed KDE was unstable due to some skim reading of some other threads (my bad). But also I found the application launcher really buggy from the little use I had with it. You're right it sounds like it should work just fine. I'll be sticking to i3 anyway.

Thanks for fixing it up in the documentation! :)
