### ISSUE TITLE
add window managers to software selection on anaconda installer

### ISSUE THREAD

**Issue by 0rb677** [QubesOS/qubes-issues#6404]
**The problem you're addressing (if any)**

Default installer has basic enviroment for Dom0. Its XFCE.

**Describe the solution you'd like**

Software Selection

Base Environment

1. QubesOS with i3wm
2. QubesOS with awesomevm
3. QubesOS with bspwm
4. QubesOS with dwm
5. QubesOS with herbstluftwm
6. etc etc...

and sets ot software instead xfce services.

**Where is the value to a user, and who might that user be?**

**Describe alternatives you've considered**

**Additional context**

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

**Comment by marmarek** [comment]
There is very specific reason why installer have just one selection: installation image size. Adding more options there would require including all those packages on the installation image too (installer have networking disabled on purpose, so downloading it from the network is not an option). and it already is quite huge.

**Comment by 0rb677** [comment]
@marmarek so, custom iso from qubes-builder is better idea?
