### ISSUE TITLE
No sound in Fedora 32 qubes

### ISSUE THREAD

**Issue by KnightWhoSaysNeeeowWumPing** [QubesOS/qubes-issues#6405]
**Qubes OS version**

Qubes release 4.0 (R4.0)
Kernel: 5.4.88-1.qubes.x86_64

**Affected component(s) or functionality**

Fedora 32 qubes and qubes based on Fedora 32

**Brief summary**

Any form of playing sound from within qubes that use Fedora 32 is not working - Debian 10 qubes all work fine.

**How Reproducible**

Always

**To Reproduce**

1. Install the Fedora 32 TemplateVM via `sudo qubes-dom0-update qubes-template-fedora-32` as stated in the documentation. (I did that a while ago)
2. Boot up a qube based on this template and run any application that 'makes sound' (e.g. VLC, YouTube video on Firefox)

**Expected behavior**

Sound should be played on the same output device as if I was using Debian-based qubes

**Actual behavior**

There is no sound playing whatsoever and I can also not select an output device for the Fedora qubes, since `pavucontrol` does not show them (see 'Solutions you've tried').

**Additional context**

[Related entry in the qubes discourse](https://qubes-os.discourse.group/t/no-sound-in-fedora-32-qubes/2800)

**Solutions you've tried**

When running `pavucontrol` in dom0 I only get a list of all running, Debian-based qubes on the tab `Playback` for which the sound works fine. Not a single Fedora 32 qube is shown there.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

[Documentation/news entry for upgrading to Fedora 32](https://www.qubes-os.org/news/2020/06/30/fedora-32-templates-available/) (Step 1 above)

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

none

**Comment by donob4n** [comment]
Could you check if inside your AppVM is there some process like:
`pulseaudio --start -n --file=/etc/pulse/qubes-default.pa --exit-idle-time=-1`

And also in dom0:
`pacat-simple-vchan -l X vm-name`

Maybe there is something related to pulseaudio in `journalctl`

**Comment by KnightWhoSaysNeeeowWumPing** [comment]
Searching for a running pulseaudio process (`ps aux | grep pulseaudio`) in my AppVM yields no results.

When running the first command manually I get an error, because the file `/etc/pulse/qubes-default.pa` does not exist - the `journalctl` tells me:
```
Feb 15 13:44:18 myVM pulseaudio[2569]: stat('/etc/pulse/qubes-default.pa'): No such file or directory
Feb 15 13:44:18 myVM pulseaudio[2569]: Failed to initialize daemon due to errors while executing startup commands. Source of commands: command line arguments
```
When trying the same command with the existing file `/etc/pulse/default.pa`, I get the following `journalctl` entry:
```
Feb 15 13:45:19 myVM pulseaudio[2583]: Failed to open cookie file '/home/user/.config/pulse/cookie': No such file or directory
Feb 15 13:45:19 myVM pulseaudio[2583]: Failed to load authentication key '/home/user/.config/pulse/cookie': No such file or directory
Feb 15 13:45:19 myVM pulseaudio[2583]: Failed to open cookie file '/home/user/.pulse-cookie': No such file or directory
Feb 15 13:45:19 myVM pulseaudio[2583]: Failed to load authentication key '/home/user/.pulse-cookie': No such file or directory
Feb 15 13:45:44 myVM pulseaudio[2583]: GetManagedObjects() failed: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
```

When running `ps aux | grep pacat` in dom0 I recognize a difference between the qubes with sound and the ones without, e.g.
```
root      4319  0.0  0.1 195796  4368 ?        SLl  10:07   0:00 pacat-simple-vchan -l 1 sys-net
user      6820  0.0  0.1 458112  7668 ?        SL   10:07   0:00 pacat-simple-vchan -l 5 untrusted
root      6831  0.0  0.1 195796  4432 ?        SLl  10:07   0:00 pacat-simple-vchan -l 6 myVM
user      6884  0.0  0.1 458112  7780 ?        SL   10:07   0:00 pacat-simple-vchan -l 7 personal
```
in this example, `untrusted` and `personal` are Debian-based, `sys-net` and `myVM` are Fedora-based qubes.
**It seems that the `pacat-simple-vchan` processes get started as root under Fedora.**

Apart from that, my dom0-`journalctl` does only contain the following lines since the last boot, when `grep`ing for *pulseaudio*:
```
Feb 15 10:07:55 dom0 dbus-daemon[2594]: [system] Activating via systemd: service name='org.freedesktop.RealtimeKit1' unit='rtkit-daemon.service' requested by ':1.37' (uid=1000 pid=6856 comm="/usr/bin/pulseaudio --start --log-target=syslog ")
Feb 15 10:07:55 dom0 rtkit-daemon[6857]: Successfully made thread 6856 of process 6856 (/usr/bin/pulseaudio) owned by '1000' high priority at nice level -11.
Feb 15 10:08:27 dom0 rtkit-daemon[6857]: Successfully made thread 6985 of process 6856 (/usr/bin/pulseaudio) owned by '1000' RT at priority 5.
Feb 15 10:08:59 dom0 rtkit-daemon[6857]: Successfully made thread 7203 of process 6856 (/usr/bin/pulseaudio) owned by '1000' RT at priority 5.
Feb 15 10:08:59 dom0 rtkit-daemon[6857]: Successfully made thread 7204 of process 6856 (/usr/bin/pulseaudio) owned by '1000' RT at priority 5.
```

**Comment by donob4n** [comment]
I also have a mix of `pacat-simple-vchan` started by user and root... I would say that started by root are based on fedora-minimal and one is an HVM.

uhM, maybe you have some broken dependency that affects qubes-pulseaudio, check `sudo dnf update` in the fedora template and also `sudo dnf install pulseaudio-qubes` in case of some dependency problem try `sudo dnf update --best --allowerasing`

Did you install the template recently?

**Comment by KnightWhoSaysNeeeowWumPing** [comment]
Wow, now I feel silly...
installing the package `pulseaudio-qubes` did the trick.

I don't know exactly when I installed the template but if I recall correctly, I did it a few weeks before Fedora 31 reached EOL - so maybe around November 2020...

Thank you very much!

**Comment by donob4n** [comment]
> I don't know exactly when I installed the template but if I recall correctly, I did it a few weeks before Fedora 31 reached EOL - so maybe around November 2020...

I asked because I remember this problem but I suppose that recent packages have now it fixed.
