### ISSUE TITLE
qvm-copy and qvm-move replace option

### ISSUE THREAD

**Issue by donob4n** [QubesOS/qubes-issues#6406]
**The problem you're addressing (if any)**

When you try to copy a file or folder to a VM which already has same name in QubesIncoming folder you get an error without any option:
`qfile-agent: Fatal error: A file named XXXXXX already exists in QubesIncoming dir (error type: File exists)`

**Describe the solution you'd like**

I would like to have an option to just replace that files without the need of manually deleting/moving that files in the destination and redoing the qvm-copy process. Ideally a new dialog asking for what to do (Cancel|Replace|ChangeName?), or at least a checkbox which I could enable a replace mode.

**Where is the value to a user, and who might that user be?**

Any user that does some workflow that implies moving same files many times from one VM to another.

**Comment by GWeck** [comment]
This might be dangerous, as it allows one VM to modify / delete data in another VM. Just copying without the possibility to overwrite means just adding something new, thus protecting data that already exist in the target VM.

**Comment by donob4n** [comment]
Well, the process is authorized by dom0 so is not a security risk. It is just an human error risk similar to manual removing the files on the destination VM. Also you have the 'private.img' snapshots in case you accidentally overwrite something. Additionally when you are sending some file with same file name, it is very likely that you are just sending an updated version of the same file so the risk of losing something is very very low.

**Comment by brendanhoar** [comment]
I think I have mentioned this elsewhere:

I believe the file receiver part of the client in target VMs should be sent a flag indicating what behavior it should perform:

**Comment by marmarek** [comment]
> Well, the process is authorized by dom0 so is not a security risk.

The fact that is authorized by dom0 does not make it magically safe. You may expect to override some specific file, but the sending VM in fact may send also other files that will override something else in `~/QubesIncoming/<vmname>` that you wouldn't expect to change otherwise.

In any case, this all is already discussed in #1772, I'm closing this one as a duplicate.

**Comment by marmarek** [comment]
Duplicate of #1772

**Comment by donob4n** [comment]
Ouch, I read like 6 pages of issues looking for duplicates -_-
