### ISSUE TITLE
RuntimeError: the PyQt4.QtCore and PyQt5.QtCore modules both wrap the QObject class

### ISSUE THREAD

**Issue by danon360** [QubesOS/qubes-issues#6409]
**Qubes OS version**
Qubes release 4.0 (R4.0)

**Affected component(s) or functionality**
qubes-qube-manager
qubes-template-manager

**Brief summary**
qube manager and template manager keep crashing whenever I try to open them

**To Reproduce**

1. Open a dom0 terminal
2. Execute: qubes-qube-manager
3. See error (copied below)

**Expected behavior**
qube manager should open fine, just as it has always done 

**Actual behavior**
it crashes and displays the error below 

**Screenshots**
```
Traceback (most recent call last):
  File "/usr/bin/qubes-qube-manager", line 9, in <module>
    load_entry_point('qubesmanager==4.0.45', 'console_scripts', 'qubes-qube-manager')()
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2575, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2235, in load
    return self.resolve()
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2241, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.5/site-packages/qubesmanager/qube_manager.py", line 44, in <module>
    from PyQt4 import QtGui  # pylint: disable=import-error
RuntimeError: the PyQt4.QtCore and PyQt5.QtCore modules both wrap the QObject class

```

**Additional context**
This problem likely started after one of the recent updates 

**Solutions you've tried**
I tried updating qubes manager, reinstalling it, removing and then installing it again, Even tried updating from the testing repository, however there were no updates there 

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
none that I know of 

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
It's almost identical to the issue below, however there was no fix suggested and the problem was supposedly resolved in an update, but for some reason, it just showed up again
#5849

**Comment by rustybird** [comment]
@marmarek It might make sense to bump the R4.0 qubes-manager package version, then this issue could be closed.

**Comment by donob4n** [comment]
@rustybird do you mean to master version? In that case it needs a few backporting fixes. Not very difficult.

What added PyQt5 to R4.0?

**Comment by rustybird** [comment]
No I mean that the [bugfix](https://github.com/rustybird/qubes-manager/commit/11d5c4387cf11a0fbeadbe23d5a527811bfd8615) was already applied to the [R4.0 branch](https://github.com/QubesOS/qubes-manager/commits/release4.0), but it's not yet installable via `qubes-dom0-update` until a new package is built from that branch.

> What added PyQt5 to R4.0?

@danon360 probably just installed some non-Qubes dom0 package that depends on PyQt5.
