### ISSUE TITLE
dom0 fails to update due to failure of host name resolution

### ISSUE THREAD

**Issue by GSF1200S** [QubesOS/qubes-issues#6412]
**Qubes OS version**
4.0

**Affected component(s) or functionality**
dom0 update

**Brief summary**
When attempting to run the qubes-updater through an update process, all TemplateVMs update properly; dom0 however fails with the following error:

> Error: Failed to download metadata for repo 'updates': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f25&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]

**How Reproducible**
Always. I have tried with a fedora32-minimal and debian10-minimal firewall as the UpdateVM- same result, and I've tried multiple times, and the problem continues to exist after a reboot.

**To Reproduce**

1. Launch qubes-updater
2. Select dom0 as an update
3. Press next
4. Observe reported error and red X

**Expected behavior**
Green checkmark; no error message

**Actual behavior**
Error message as above; red X denoting failure

**Solutions you've tried**
Changing TemplateVM from Fedora to Debian for firewall (which is what I use as an updateVM)

**Comment by eric-blabla** [comment]
often connections / mirrors are temporarily unreachable since connection goes over tor and whatever reason. Did you try several times? Did you launch

sudo qubes-dom-update   

in a dom0 terminal?

**Comment by GSF1200S** [comment]
Yes, I have tried several times over the last 2-3 days. I have also rebooted. When I try to update from dom0's CLI as you suggest I get:

> [user@dom0 ~]$ sudo qubes-dom0-update
Using disp-sys-firewall-debian as UpdateVM to download updates for Dom0; this may take some time...
Fedora 25 - x86_64 - Updates                    0.0  B/s |   0  B     04:00    
Errors during downloading metadata for repository 'updates':
  - Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f25&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]
Error: Failed to download metadata for repo 'updates': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f25&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]

I am about to file another bug report which seems very familiar: DNS fails to resolve on AppVMs as well...

**Comment by GSF1200S** [comment]
I cannot explain why this has resolved other than sys-net (which in my case was based off of debian) having received an update by proxy of debian-10-minimal being updated. 

I had DNS resolution issues with AppVMs that used both Fedora32 and Debian10, and as well had dom0 resolution errors. Changing the FirewallVM (between debian or fedora) made no difference, and rebooting did not fix. AppVMs that ran through a VPN had no such DNS resolution issues. 

Upon rebooting again (and still having the issues), I received notice of Debian updates and updated them, restarted sys-net, and sure enough all my problems are resolved. Going to close this- sorry for the trouble.

**Comment by zet9** [comment]
It's good to read that it has resolved itself. How did you achieve that? I seem to be running into the same problem since approx 15-Feb (error message on update "Could not resolve host: mirrors.fedoraproject.org") but so far no luck getting anywhere. Switching the sys-net VM from Fedora to Debian has no effect as neither of them seem to be able to access the update URL anymore.
