### ISSUE TITLE
Installing a compiled kernel in dom0 via rpm -Uvh does not create entry in xen.cfg

### ISSUE THREAD

**Issue by iprid** [QubesOS/qubes-issues#6413]
### Qubes OS version: 
R4.0

### Affected component(s) or functionality:
dom0 kernel

### Steps to reproduce the behavior:
Build/Download an RPM with kernel for dom0 - for example 4.19.176
Do ```sudo rpm -Uvh kernel-4.19.176-1.pvops.qubes.x86_64.rpm```

### Expected or desired behavior:
A new boot entry should be added to xen.cfg(in /boot/efi//EFI/qubes)

### Actual behavior:
[global]
default=...new...kernel

But there is no new kernel entry below

### General notes:

Perhaps one should use dnf or qubes-dom0-update,
so maybe it's my mistake for using rpm directly.
But  then again I take it they still call rpm in the end.
The difference being that they add flags and resolve deps(not needed).

I started using rpm directly, because I had issues when trying to upgrade
xen related packages via qubes-dom0-update(compiled RPMs).

### I have consulted the following relevant [documentation](https://www.qubes-os.org/doc/):
https://www.qubes-os.org/doc/software-update-dom0/

**Comment by marmarek** [comment]
Did you changed `default=` line before? The install script looks for the current default value, then copy that section as a template for the newly installed kernel.

**Comment by iprid** [comment]
Hm,```default``` had a value referring to one of the older kernels which had a kernel entry in xen.cfg.
It could be that using -U resulted the issue, because it uninstalled all older kernels.
(and removed their files from /boot and /boot/efi/EFI/qubes).

**Btw I've noticed a few strange things:**
1. The vmlinuz and initramfs files are both in /boot and in /boot/efi/EFI/qubes.
Why is this duplication happening?
2. Strangely, I have a leftover initramfs file in /boot/efi/EFI/qubes which is no longer in /boot.
(from an uninstalled old kernel)

**More importantly:**
Do I need to recreate my initramfs with dracut if I install a kernel with ```rpm```?

**Comment by marmarek** [comment]
> It could be that using -U resulted the issue, because it uninstalled all older kernels.

Yes, that could be an issue. dnf (and so qubes-dom0-update) is configured to keep last 3 kernel packages, so it basically does `rpm -i`, not `rpm -U`.



>     1. The vmlinuz and initramfs files are both in /boot and in /boot/efi/EFI/qubes.
>        Why is this duplication happening?

To have the same package working for both legacy and UEFI boot. In fact, the package ships only the file in /boot, which is then copied to /boot/efi/EFI/qubes (which lives on another partition) if EFI boot is detected.


> Strangely, I have a leftover initramfs file in /boot/efi/EFI/qubes which is no longer in /boot.

That's indeed strange, they should be removed when the package is uninstalled. Did you get any error messages on remove?

>  Do I need to recreate my initramfs with dracut if I install a kernel with `rpm`?

No, it should be done automatically.

**Comment by iprid** [comment]
Okay, thanks for the explanations.

One last thing - since I know sometimes I do dumb stuff, I have a backup EFI partition
from which I can boot(basically a different /boot/efi which is normally mounted as /boot/backup-efi).

And of course I have an efi record so I can boot from this /boot/backup-efi.

However when I tried to do it - I still got errors.
I should have been able to boot an older kernel from /boot/backup-efi.
There is a valid xen.cfg + older kernel and initramfs for that older kernel.

**Comment by marmarek** [comment]
What kind of errors? The thing you described should work, unless you made some typo, forgot a file (should be xen.efi, xen.cfg, then matching kernel and initramfs) or something like this.

**Comment by iprid** [comment]
Hm, not sure. But you're saying that the files in /boot don't matter if I am using EFI, so it should be fine?
Because the structure was like this:
/boot
new kernels
new kernels initramfs
/boot/efi-backup:
old-kernel
old-kernel-initramfs
/boot/efi:
new kernels
new kernels initramfs

Also I've just now checked my /lib/modules.
Strangely I still have kernel modules for the old uninstalled kernels there.
Shouldn't they have been removed or something?

**Comment by marmarek** [comment]
> But you're saying that the files in /boot don't matter if I am using EFI, so it should be fine?

Yes, that's correct.

> Strangely I still have kernel modules for the old uninstalled kernels there.
> Shouldn't they have been removed or something?

You sure the modules are really there, not just an empty directory?

**Comment by iprid** [comment]
Yep, you're right. The modules aren't in the folder. So I guess that's why it wasn't working => the modules were missing for the older kernels.
