### ISSUE TITLE
Qubes build-iso fails to build 4.1 within Qubes-based build

### ISSUE THREAD

**Issue by permezel** [QubesOS/qubes-issues#6417]
**Qubes OS version**

4.0

**Affected component(s) or functionality**

The Qubes build iso steps per the documentation

**Brief summary**

I carefully followed the instructions in https://www.qubes-os.org/doc/qubes-iso-building/.

The sole difference is that I build 4.1, not 4.0, as I am trying to test a recent bug fix (QubesOS/qubes-vmm-xen@075e6b1.)

It craps out in 

```
-> Building template fc30 (logfile: build-logs/template-fc30.log)...
make: *** [Makefile:341: template-local-fc30] Error 1

```

**How Reproducible**

100% of every time I have tried it.

**To Reproduce**

1.  Follow the steps in qubes-iso-building using a fed32 template vm
2. select '4.1' rather than '4.0'
3. Do the 'don't build gcc' step
4. Kick off build
5. Go for a walk on the beach
6. Check build log

**Expected behavior**

I was expecting to produce an iso image to test the boot/install on my NUC10.

**Actual behavior**

```
--> Installing 3rd party apps
Qubes Template Builder Repository               3.7 MB/s | 3.8 kB     00:00    
google-chrome - x86_64                          1.1 kB/s | 3.6 kB     00:03    
Qubes OS Repository for VM (updates)             56  B/s | 169  B     00:03    
Qubes OS Repository for VM (updates)            2.2 MB/s | 2.3 kB     00:00    
Importing GPG key 0x9E2795E9:
 Userid     : "Qubes OS Release 4 Signing Key"
 Fingerprint: 5817 A43B 283D E5A9 181A 522E 1848 792F 9E27 95E9
 From       : /etc/pki/rpm-gpg/RPM-GPG-KEY-qubes-4-primary
Qubes OS Repository for VM (updates)             55  B/s | 169  B     00:03    
Errors during downloading metadata for repository 'qubes-vm-r4.1-current':
  - Status code: 404 for https://yum.qubes-os.org/r4.1/current/vm/fc30/repodata/repomd.xml.asc (IP: 147.75.32.69)
Error: Failed to download metadata for repo 'qubes-vm-r4.1-current': GPG verification is enabled, but GPG signature is not available. This may be an error or the repository does not support GPG verification: Status code: 404 for https://yum.qubes-os.org/r4.1/current/vm/fc30/repodata/repomd.xml.asc (IP: 147.75.32.69)
/home/user/qubes-builder/qubes-src/builder-rpm/template_scripts/04_install_qubes.sh: line 54: mnt/etc/locale.conf: No such file or directory
make[1]: *** [Makefile:66: rootimg-build] Error 1

```

I checkout out https://yum.qubes-os.org/r4.1/current/vm/fc30/repodata/ and sure enough, there is no repomd.xml.asc.
See the screenshot.

There are some other errors and  in the build log for this component.  Perhaps they are the cause of the failure.  Please see the attached TAR file of the logs.

**Screenshots**

![image](https://user-images.githubusercontent.com/2313876/108617260-827f5f00-7460-11eb-964d-32e04e503903.png)

**Additional context**

Make log files, plus *.conf files:
[fail.tar.gz](https://github.com/QubesOS/qubes-issues/files/6017277/fail.tar.gz)

**Solutions you've tried**

I am trying to build with pretty much every other COMPONENT removed.  That is in progress.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

https://www.qubes-os.org/doc/qubes-iso-building

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

**Comment by permezel** [comment]
Tried building the ISO with most components commented out, per the instructions:

```
[user@qubes-build qubes-builder]$ make iso
-> Preparing for ISO build...
--> Removing old rpms from the installer repos...
---> Cleaning up repo: dom0-updates...
---> Cleaning up repo: installer...
---> Cleaning up repo: qubes-dom0...
--> Copying vmm-xen RPMs...
--> Copying mgmt-salt RPMs...
--> Copying mgmt-salt-base RPMs...
--> Copying mgmt-salt-base-topd RPMs...
--> Copying mgmt-salt-base-config RPMs...
--> Copying mgmt-salt-dom0-qvm RPMs...
--> Copying mgmt-salt-dom0-virtual-machines RPMs...
--> Copying mgmt-salt-dom0-update RPMs...
--> Copying template-whonix RPMs...
--> Copying template fc30 RPM...
ln: failed to access
'rpm/noarch/qubes-template-fedora-30-4.0.6-202102210504.noarch.rpm': No
such file or directory
make[1]: ***
[/home/user/qubes-builder/qubes-src/builder-rpm/Makefile.rpmbuilder:158:
update-repo-do] Error 1
make: *** [Makefile:537: iso.copy-template-rpms.fc30] Error 2
```

**Comment by permezel** [comment]
Added `linux-template-builder` back into COMPONENTS, did a `make linux-template-builder`, then `make iso` and it made a lot of progress, then failed again.
Looks as if I need to add:
```
qubes-pdf-converter-dom0
qubes-usb-proxy-dom0
qubes-release-notes
```
back to COMPONENTS.

My main complaint about this fragile, broken, build process is that I should just be able to do, initially, with no other setup on a pristine fed32 build VM, run  `make iso` and have it work.  Period.  Not all this weird stuff I have to cut and paste and execute, and two separate invokations of the menu-based `./setup`.  The default should be to not build any COMPONENTS, which would give a working example of the minimal COMPONENTS setting.  Then, if I have changes to any component, I can then make whatever changes, manually compile the component, and then `make iso` to test.

Anyway, lets see how far I get this time....

**Comment by permezel** [comment]
So the docs need to be updated?  Per the docs, and per the ./setup file. there is no fedora32 available.  Just 30 and 31, and the instructions call for 30.  I just ran ./setup again. I have 4.1 selected.  I am not presented with fc32 or fc33.  Just
```
fc30
fc30+minimal
fc30+fullyloaded
fc30+xfce
fc31+minimal
...
```
There is no `fc32` nor `fc33`.

**Comment by permezel** [comment]
I just read the README.md file which is part of the checked-out build stuff.  It claims I can use the ./setup script.
So both the build-iso documents and the README.md file need to be fixed so that they can lead to successfully building stuff.

**Comment by DemiMarie** [comment]
> So the docs need to be updated? Per the docs, and per the ./setup file. there is no fedora32 available. Just 30 and 31, and the instructions call for 30. I just ran ./setup again. I have 4.1 selected. I am not presented with fc32 or fc33. Just
> 
> ```
> fc30
> fc30+minimal
> fc30+fullyloaded
> fc30+xfce
> fc31+minimal
> ...
> ```
> 
> There is no `fc32` nor `fc33`.

That is definitely a bug, good catch!  I will file a PR.
