### ISSUE TITLE
resume from suspend broken for NUC10 on r4.1

### ISSUE THREAD

**Issue by permezel** [QubesOS/qubes-issues#6419]
**Qubes OS version**

4.1

**Affected component(s) or functionality**

suspend/resume

**Brief summary**

**How Reproducible**

I suspended.  Resume is not possible.

**To Reproduce**

1. suspend
2. try to resume

**Expected behavior**

I expect the hitting the power button (which is light-pulsing indicating in suspend mode) will break it out of suspend.
It does not.

**Actual behavior**

Just sits there pulsing the LED in the power button dimly.

**Screenshots**

**Additional context**

Found an older report, but it had been closed.

**Solutions you've tried**

Forced power off by holding for extended period.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

https://github.com/QubesOS/qubes-issues/issues/6066

**Comment by solardiz** [comment]
Same issue with 4.1 beta on Lenovo Thinkbook 15 G2 ITL (Intel Tiger Lake) - the system enters suspend seemingly OK, but then doesn't appear to even try to come out of it ("Just sits there pulsing the LED in the power button dimly.")

Enabling SMT (as suggested by some in #6066) didn't make a difference. (Enabled in firmware settings, enabled in GRUB config, confirmed the doubled number of logical CPUs via `/proc/cpuinfo`.)

Didn't try other than 4.1 beta on this laptop yet.

**Comment by lubellier** [comment]
@permezel I am also using a Nuc 10 and Qubes-OS 4.1, the suspend/resume works for me.

Suspend steps:

- XFCE session menu in tray bar (user), choose *Suspend*
- confirmation popup for **suspend to RAM**, 30s countdown, choose *Suspend* button
- 3s later, the power button is light-pulsing

Resume steps:
- push power button OR push a keyboard key
- displayed XScreenSaver popup which ask the user password, I fill the password
- displayed desktop

My dom0 uses the *stable* repositories, and is up-to-date:

```
[user@dom0 ~]$ uname -a
Linux dom0 5.10.109-1.fc32.qubes.x86_64 #1 SMP Sat Apr 2 20:41:53 CEST 2022 x86_64 x86_64 x86_64 GNU/Linux
[user@dom0 ~]$ cat /etc/qubes-release 
Qubes release 4.1 (R4.1)
[user@dom0 ~]$ lscpu | grep ^Model\ name
Model name:                      Intel(R) Core(TM) i7-10710U CPU @ 1.10GHz
```

Could you try again? I am ready to compare my setting with you...

**Comment by solardiz** [comment]
Incidentally, my comment above is misplaced - at the time I made it, I didn't realize "my" issue was specific to 11th gen (Tiger Lake) and on. This issue was about NUC10, so 10th gen, which is the latest where suspend/resume is still supposed to work in Qubes OS - so it's just right that it does work for you, @lubellier. Indeed, there could have been some other issue preventing it from working for @permezel back then, and it would be good to figure that out and maybe close the issue if it's gone in the latest 4.1.

**Comment by permezel** [comment]
> @permezel I am also using a Nuc 10 and Qubes-OS 4.1, the suspend/resume works for me.
> 

> Could you try again? I am ready to compare my setting with you...

My Qubes-OS system has been working fine (suspend/resume wise) for some time, but this may be because I swapped back to my NUC7.  Can't tell for sure.  I'm not currently allowed into that part of the house, so I can't check.  Once the restraining order has been rescinded, I will be able to venture out and check.

**Comment by permezel** [comment]
> > @permezel I am also using a Nuc 10 and Qubes-OS 4.1, the suspend/resume works for me.
> 
> > Could you try again? I am ready to compare my setting with you...
> 
I snuck out this morning and can confirm that the NUC10 has been suspending/resuming with no issues.  It was so long ago that it was resolved, I no longer have the faintest clue as to what I did.
I have it set to auto-suspend after N minutes of inactivity, and it always responds to the power button and comes right up.

**Comment by lubellier** [comment]
Thank you for this test.
