### ISSUE TITLE
r4.1 on IntelNUC10 fails to activate display at boot time

### ISSUE THREAD

**Issue by permezel** [QubesOS/qubes-issues#6420]
**Qubes OS version**

4.1

**Affected component(s) or functionality**

Initial boot

**Brief summary**

When I boot, the 'disk password' screen is not displayed.  I have to mess about with CTL-F1 to get it to toggle between the graphical and the textual.  Prior to that, they display is blank.

**How Reproducible**

2 of three total boots so far, post install.

**To Reproduce**

1.  power on the NUC
2. wait for the disk password screen
3. wonder if it will ever display
4. hit CTL-F1

**Expected behavior**

I expect the 'disk password' splash screen to be displayed.

**Actual behavior**

Nada.

**Screenshots**

**Additional context**

**Solutions you've tried**

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

**Comment by mtdcr** [comment]
This is likely what I'm experiencing with an external display on a docked notebook. I haven't tried Ctrl-F1, but the Escape key toggles between text and graphics mode, too, and the password prompt already appears after the first press and stays visible in both modes from that point on. It had already happened on every docked boot with 4.0 and hasn't changed in 4.1-rc3.

**Comment by arkenoi** [comment]
turned off rhgb because graphical boot screen never worked properly for my NUC. now everything is fine.. except there is no fancy graphical boot :)

**Comment by DemiMarie** [comment]
I turn off rhgb because the standard boot screen provides far more information.

**Comment by lubellier** [comment]
I'm using a Nuc10 (see the related [HCL entry](https://www.qubes-os.org/hcl/#intel_nuc10i7fnk_i7-10710u_comet-lake_integrated-graphics-uhd-620)), and the *disk password screen* (provided by [Plymouth](https://wiki.archlinux.org/title/Plymouth)) **is displayed**.

@permezel please provide more information (dom0 kernel version, kernel command line parameters)

```
[user@dom0 ~]$ cat /proc/version 
Linux version 5.10.112-1.fc32.qubes.x86_64 (mockbuild@ff7978a4d91e45159470e883db984435) (gcc (GCC) 10.3.1 20210422 (Red Hat 10.3.1-1), GNU ld version 2.34-6.fc32) #1 SMP Fri Apr 22 12:45:40 CEST 2022
[user@dom0 ~]$ cat /proc/cmdline 
placeholder root=/dev/mapper/qubes_dom0-root ro rd.luks.uuid=luks-b474aa57-c82a-4b95-b7a1-83716d964a34 rd.lvm.lv=qubes_dom0/root rd.lvm.lv=qubes_dom0/swap plymouth.ignore-serial-consoles rd.driver.pre=btrfs rhgb quiet

```

**Comment by permezel** [comment]
```
[root@dom0 qvm]# cat /proc/version
Linux version 5.15.52-1.fc32.qubes.x86_64 (mockbuild@b4f2def1000a4ff893efe4bc2b185fab) (gcc (GCC) 10.3.1 20210422 (Red Hat 10.3.1-1), GNU ld version 2.34-6.fc32) #1 SMP Tue Jul 5 16:22:24 CEST 2022
[root@dom0 qvm]# cat /proc/cmdline 
placeholder root=/dev/mapper/qubes_dom0-root ro rd.luks.uuid=luks-8afc8cab-c00d-4e16-93d4-538690bb1392 rd.lvm.lv=qubes_dom0/root rd.lvm.lv=qubes_dom0/swap plymouth.ignore-serial-consoles rd.driver.pre=btrfs rhgb quiet
```

**Comment by permezel** [comment]
@DemiMarie  Gunna try turning off `rhgb` next time just fer grins.
I usually want to see the boot-time info, but I have finally been worn down to the point that I no longer take the additional steps to enable it again and again (ie: setting bootargs=-v in nvram over and over over the decades).

My NUC10 has been booting fine now for quite some time.  I'm going to close this with this elegant comment.
