### ISSUE TITLE
windows hvm/qube with multithread cpu(vcpus no>1) will bsod(wont boot)

### ISSUE THREAD

**Issue by qubesacc** [QubesOS/qubes-issues#6421]
**Qubes OS version**

Qubes release 4.0 (R4.0)

**Affected component(s) or functionality**

xen configuration for windows HVMs (I guess)

**Brief summary**

i,m new to qubes os and xen
for last a few days i,m trying to boot windows with more than one cpu core/thread ,
machine starts but windows boot loader bsods with "MULTIPROCESSOR CONFIGURATION NOT SUPPORTED"
 i,ll boot again if i change vcpu to 1 again
but windows with one cpu thread is almost useless for me and for most things other ppl would want to do

after lots of googling i found out it,s related to cpuid and other information what xen send to windows .
unfortunately found no way to change it 

i,ll be bqck to debian +vmware worksation if i cant gove multo cores to windows hvms
**How Reproducible**

**To Reproduce**

1. create a hvm with enough ram (+4gb) , disable memory balancing , five 50gb (or anyother amount) system storage , no template , no kernel  , set vcpus to 1  (or set hifher and skip next step)
2.  start cm and everything is ok, windows installer will show , stop it and change vpus no to 2 or more 
3. start again and you will see crash due "MULTIPROCESSOR CONFIGURATION NOT SUPPORTED" , nothing does resolve it

**Expected behavior**

windows will boot and see a multi threaded cpu 

**Actual behavior**

windows wont boot and no solution 

**Screenshots**

![20210222_165256](https://user-images.githubusercontent.com/79457149/108714173-7530a600-752e-11eb-94c0-d4ccc1a1d6b7.jpg)

**Additional context**

win version tested : windows 10 2004  and windows server 2019
amd reyzen 9 3900x , msi meg x570 ace , 32gb 3200mhz ram , Nvidia 750ti gpu

**Solutions you've tried**

found no solution

**Comment by GWeck** [comment]
In my configuration (4GB memory, memory balancing disabled, HVM, no kernel) Windows 10 Professional 20H2 boots with vcpus=2 without any problem. Could it be that this is not supported for Windows Home?

**Comment by ejose19** [comment]
This was fixed in a later version of xen as far I recall, however since you're still using R4.0, just disable smt/hyperthreading on bios and you will be able to assign more than 1cpu (there won't be any performance loss as qubes disables multi-threading in boot opts).

**Comment by qubesacc** [comment]
@ejose19 
i had installed debian , wiped and installed qubes beta version again 40.04-rc2
it worked with smt disabled in bios 
but still didn,t work without explicitly disabling smt in bios
thabks alot for work around
how can i upgrade xen version inside qubes ?

**Comment by qubesacc** [comment]
@GWeck i tried all version of windows server , and win10 pro
if i,m correct , the problem occures in the bootloader of windows (like linux /boot), far behond what version exist in c:\windows 
maybe it,s about your board setting /model

**Comment by ejose19** [comment]
@qubesacc Installing Qubes 4.1 (which is not yet released) contains latest xen version. However you are better off with just keep smt disabled in bios, as I mentioned qubes already has it disabled in OS level, so you won't lose anything.

**Comment by iamahuman** [comment]
Related: #5743
