### ISSUE TITLE
io-apic + timer does not work: booting issue on xen-4.14.1-3

### ISSUE THREAD

**Issue by fepitre** [QubesOS/qubes-issues#6423]
I confirm that latest mitigation for Intel in https://github.com/QubesOS/qubes-issues/issues/6372 is failing my system having a processor AMD Ryzen 1800X on a motherboard Asrock X370 Gaming K4.

**Comment by ideologysec** [comment]
I can confirm that I am also having this issue on a Dell XPS 9570 with Intel i7-8750H Cannon Lake. It's unable to set up the IO-APIC timer. (additional info in #5374 ). Ubuntu 21.04 and Fedora 33 work fine.

**Comment by aaronjanse** [comment]
See the relevant xen-devel mailing list discussion. If someone could test the patch, that would be fantastic. I want Qubes to work on my laptop but I don't have motivation to compile Xen myself right now https://markmail.org/thread/qsnxiknqalo4qoke#query:+page:1+mid:byon4l7mtnwf6whz+state:results

**Comment by aaronjanse** [comment]
Oh whoops, I'll post on the other thread too

**Comment by DemiMarie** [comment]
@fepitre @ideologysec is this fixed by QubesOS/updates-status#2474?

**Comment by ideologysec** [comment]
I no longer have the hardware at issue for testing; I gave up. 😕
