### ISSUE TITLE
Dom0 update error if default template is set to debian-10

### ISSUE THREAD

**Issue by GWeck** [QubesOS/qubes-issues#6429]
**Qubes OS version**

R4.1 (from ISO 20210117)

**Affected component(s) or functionality**

Dom0 updater

**Brief summary**

If `debian-10` is selected as default template, `qubes-dom0-update` throws an error, and no update is performed.

**How Reproducible**

always

**To Reproduce**

1. Install Qubes R4.1 from the 17-Jan-2021 ISO.
2. In the second phase of the installation, select `debian-10` as default template.
3. After the installation has finished, open a dom0 terminal and enter `sudo qubes-dom0-update`.

**Expected behavior**

Dom0 should update, possibly using `sys-firewall` as its update proxy.

**Actual behavior**

The following error mesage is given:
`error: could not delete old database at /var/lib/qubes/dom0-updates/home/user/.rpmdbold.1163`
`Error: Cannot retrieve repository metadata (repomd.xml) for repository: fedora.`
`Please verify its path and try again`
`Cannot retrieve repository metadata (repomd.xml) for repository: fedora.`
`Please verify its path and try again`

**Additional context**

The directory `/var/lib/qubes/dom0-updates/`mentioned in the first line of the error messages does not exist. Also, there is no directory `/home/user/`, if the user specified during installation has a different name, not `user`.
If `fedora-32` is selected as the default template, the error does not occur.

**Comment by marmarek** [comment]
This looks pretty similar to https://github.com/QubesOS/qubes-issues/issues/5282. Can you check qubes-core-agent package version in your debian-10 template?

**Comment by GWeck** [comment]
`apt list -a` tells that version `4.1.15-1+deb10u1` is installed and that this is upgradable to `4.1.18-1+deb10u1`.

The debian-10 template can be updated, and then version `4.1.18-1+deb10u1` is installed. Trying to update dom0 fails again.

By the way, although the template VM debian-10 can be updated, `sys-firewall` and VMs depending on it have no network access ("`Destination host unreachable`"), while `sys-net` has network access.

After a reboot, network access is possible, and `sys-whonix` connects to the Tor network. Updating dom0 works, too.

So it seems that the originally installed template is too old.

**Comment by GWeck** [comment]
Probably no longer relevant - debian is now bullseye (11).
