### ISSUE TITLE
Sys-net freezing causing loss of network connection

### ISSUE THREAD

**Issue by progress225** [QubesOS/qubes-issues#6430]
**Qubes OS version**
 4.0

**Affected component(s) or functionality**
 sys-net network connection.

**Brief summary**
 sys-net VM freezes after I start a Whonix AppVM (sys-usb -> sys-net -> sys-firewall -> sys-whonix -> Whonix AppVM). Connection to the network is lost, and I am forced to kill the VM.

**How Reproducible**
 100%  of the time.

**To Reproduce**

1. Connect Wifi adapter from sys-usb to sys-net and connect to network.
2. Start sys-firewall and sys-whonix.
3. Start Whonix AppVM, and attempt to use.

**Expected behavior**
 The Whonix AppVM successfully runs, and use of the Whonix AppVM is possible.

**Actual behavior**
 The Whonix AppVM successfully syncs sdwdate. However, upon any use of the AppVM, sys-net freezes causing loss of network connection.

**Screenshots**

**Additional context**
 This issue occurs with both Debian 10 and Fedora 32 based sys-net VMs.
This issue occurs with different USB Wifi Adapters.
The sys-net VM runs perfectly until a Whonix AppVM is used.
Neither the sys-whonix or sys-usb VMs freeze. (sys-whonix does lose connection from sys-net though)
There is no difference in my sys-net "/var/log/xen/console/guest-sys-net.log" logs, between when the VM is running properly and after it has crashed. 

I really need advice on how I can identify the cause of this issue, as it has plagued me.
This issue has occured multiple times throughout my use of Qubes. I always begin new again, but the issue eventually arrises again.
 

**Solutions you've tried**
I have tried:
 - use of different wifi adapters 
 - use of fedora and debian based sys-net VMs
 - use of VPN VM as a NetVM for sys-whonix

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

**Comment by donob4n** [comment]
Really rare. If you use a non whonix AppVM connected to sys-whonix does it crash too?

Look also `guest-sys-net-dm.log` and `hypervisor.log`. I think that you will need some method for debug kernel panics and (maybe some special for Xen guests). 

What happens if you try: `sys-usb  -> sys-firewall -> sys-whonix -> Whonix AppVM`

I suppose that adding sys-net in the chain is just for fast switching to sys-net direct network and usb adapters.

**Comment by progress225** [comment]
> Really rare. If you use a non whonix AppVM connected to sys-whonix does it crash too?
> 
> Look also `guest-sys-net-dm.log` and `hypervisor.log`. I think that you will need some method for debug kernel panics and (maybe some special for Xen guests).
> 
> What happens if you try: `sys-usb -> sys-firewall -> sys-whonix -> Whonix AppVM`
> 
> I suppose that adding sys-net in the chain is just for fast switching to sys-net direct network and usb adapters.

Yes, using Windows 10 VM, Debian 10, and Fedora 32 with NetVM set to sys-whonix causes crash to sys-net also.

My guest-sys-net-dm.log is blank/empty both during a successfull connection with network, and after it has crashed.

Would adding Network Manager to my sys-firewall, and removing sys-net VM from my setup lead to any decrease in security? Would it function as both a firewall and network manager? I have no need for switching between direct network and usb adapters.

I can see that other users are dealing with issues pertaining to sys-net. Though they are dealing with seperate issues, I may need to attempt switching kernels as described here:

https://qubes-os.discourse.group/t/sys-net-not-functional-on-kernel-5-x/2544

Please let me know if you think this is worth trying.
I am looking into how to pull my hypervisor.log logs, and will post them soon.

**Comment by donob4n** [comment]
> Would adding Network Manager to my sys-firewall, and removing sys-net VM from my setup lead to any decrease in security? Would it function as both a firewall and network manager? I have no need for switching between direct network and usb adapters.

Don't add Network Manager to sys-firewall. In this case:
`sys-usb -> sys-firewall -> sys-whonix -> Whonix AppVM`

Network Manager should be enabled into sys-usb. I don't think that you decrease your security, your sys-usb is acting as sys-net (it handles the hardware drivers which are more prone to security bugs) and you have sys-firewall with the same trust level than before.

> I can see that other users are dealing with issues pertaining to sys-net. Though they are dealing with seperate issues, I may need to attempt switching kernels as described here:
> 
> https://qubes-os.discourse.group/t/sys-net-not-functional-on-kernel-5-x/2544
> 
> Please let me know if you think this is worth trying.

They are talking about connecting issues not sys-net crashing, so probably is not related. I personally had a lot of crashes of dom0 with kernels 5.8.X, and 5.10.X, similar (but not same log messages) to https://github.com/QubesOS/qubes-issues/issues/6397 So, If you don't want to try to debug kernel panics I won't touch dom0 kernel. Maybe you can try upgrading only VM kernels.

You can move any file from dom0 to some AppVM using '`qvm-copy-to-vm destVM file`'
