### ISSUE TITLE
Fedora 33 systemd-resolved documentation recommendation

### ISSUE THREAD

**Issue by michaelschefczyk** [QubesOS/qubes-issues#6431]
Users switching to the Fedora 33 TemplateVMs who want to resolve local domains while in their LAN will probably find that this does not work because Fedora 33 switched to systemd-resolved.

A quick fix should be to disable systemd-resolved and to enable NetworkManager in the TemplateVM.

There are probably smarter ways or resolving this and/or ways that are more compatible with the qubes security model and the notion of systemd-resolved propagating to other distros as well.

It might be good to add some documentation or at least a small note to the Fedora 33 announcement so that it is not for every affected user to find out individually.

**Comment by marmarek** [comment]
@andrewdavidwong can you add a link to F33 release notes? https://docs.fedoraproject.org/en-US/fedora/f33/release-notes/ or maybe their announcement https://fedoramagazine.org/announcing-fedora-33/ ?

**Comment by marmarek** [comment]
BTW I do use default settings and resolving local domains works for me if I use full name (with `.lan` suffix I use).

**Comment by michaelschefczyk** [comment]
Thank you for responding so rapidly! I think that the issue is, that .local was the Microsoft-based standard for active directory domains some time ago. Yes, .local was claimed by mDNS in February 2013 (https://tools.ietf.org/html/rfc6762), but that was pretty much an intrusion which certainly did not make everyone change on the spot. Many users will have kept it because there was no pressing reason to change. I am one of those - having not felt any consequence until installing the F33 today. While my domain is managed by a mix of Samba and Microsoft DC, the name still ends with .local

**Comment by andrewdavidwong** [comment]
I have updated the Fedora 33 TemplateVM announcement with a note about systemd-resolved as well as links to the official Fedora 33 release notes and announcement. Please let me know if you see any further room for improvement!

**Comment by 100111001** [comment]
@michaelschefczyk would you be so kind to explain how to do this step in detail?

> A quick fix should be to disable systemd-resolved and to enable NetworkManager in the TemplateVM.

**Comment by michaelschefczyk** [comment]
In the terminal of the F33 template VM type:
su
systemctl disable systemd-resolved
systemctl enable NetworkManager
