### ISSUE TITLE
Possible to mention if using ubuntu 20.04 or latest kernel same as ubuntu 20.04?

### ISSUE THREAD

**Issue by hiqsociety** [QubesOS/qubes-issues#6433]
Possible to mention if using ubuntu 20.04 or latest kernel same as ubuntu 20.04?

because there are certain improvement to ubuntu 20.04 so I'm curious if it's possible to mention this inside the versioning of qubes... for "security" changelog / update reasons.

and of course for compatibility with software installation.

Is qubes latest version compatible with ubuntu 20.04? sorry for asking. I would want to migrate infra and network to qubes but if it's using 18.04 then i wont do it for now.

**Comment by iamahuman** [comment]
Latest Qubes R4.0 comes with Linux kernel 5.4 LTS (shipped with Ubuntu 20.04) by default.

**Comment by unman** [comment]
On Mon, Mar 01, 2021 at 06:26:19AM -0800, hiqsociety wrote:
> Possible to mention if using ubuntu 20.04 or latest kernel same as ubuntu 20.04?
> 
> because there are certain improvement to ubuntu 20.04 so I'm curious if it's possible to mention this inside the versioning of qubes... for "security" changelog / update reasons.
> 
> and of course for compatibility with software installation.
> 
> Is qubes latest version compatible with ubuntu 20.04? sorry for asking. I would want to migrate infra and network to qubes but if it's using 18.04 then i wont do it for now.
> 

Hello @hiqsociety
Github isn't really the place for this sort of question - you'll find
better support for questions such as this at the mailing list, or the
forum:
qubes-users: qubes-users@googlegroups.com (no Google account required)
Forum: https://qubes-os.discourse.group
Take a look at https://www.qubes-os.org/support/ for guidance

The latest Qubes 4.0 comes with the same kernel version as Ubuntu 20.04,
so there should be no problem there.
This applies to the kernel used in dom0 and that available in template
based qubes.

There is also a Ubuntu 20.04 template - you can build this yourself
using the Qubes Builder, or I provide a pre-built template for download
from https://qubes.3isec.org/Templates

So, yes, Qubes 4.0 (the latest stable version) is compatible with
Ubuntu 20.04, and so will the next version (4.1) be.
I hope that encourages you to make the change to Qubes soon.

**Comment by andrewdavidwong** [comment]
Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this does not appear to be suitable for `qubes-issues`. We ask that you please post this on the [`qubes-users` mailing list or forum](https://www.qubes-os.org/support/) instead. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a brief comment explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.
