### ISSUE TITLE
Routing Tor Browser non-vm clients (Win, Lx) via sys-whonix via client-side firewall fails

### ISSUE THREAD

**Issue by Shaggy1444** [QubesOS/qubes-issues#6436]
### Qubes OS version:

R4.0, latest patches for DOM0 and sys-whonix.

### Affected component(s) or functionality:

Trying to route Win/Lux clients using TOR browser through HVM-Firewall to sys-whonix.
See network setup below.

---

### Steps to reproduce the behavior:

Network setup is as follows:

clients <--> Lan/RTR <--> HVM-Firewall <--> sys-firewall <--> sys-net <--> Physical-Firewall <--> ISP
clients <--> Lan/RTR <--> WAN Failover <-------failover-GW-----> sys-net <--> Physical-Firewall <--> ISP
clients <--> Lan/RTR <--> HVM-Firewall <--> sys-whonix <--> sys-firewall <--> sys-net <--> Physical-Firewall <--> ISP

Default gateway from HVM-Firewall is via sys-firewall which is treated as a WAN GW - this works fine.
WAN Failover goes direct to sys-net - this works fine.
Route from HVM-Firewall to sys-whonix and then out through sys-firewall - this fails.

Confirmed that sys-firewall (10.137.0.6) has route to sys-whonix (10.137.0.7).
Confirmed that sys-firewall has route to HVM-Firewall (10.137.0.99).
Confirmed that sys-whonix has route to sys-firewall.

1. Tried to create static route from HVM-Firewall (0.99) to sys-whonix - route fails.
2. Tried (as per web - Enabling networking between two qubes) to set sys-firewall rule to redirect HVM-Firewall to sys-whonix.
3. Tried (as per web - Enabling networking between two qubes) to set sys-whonix rc.local to accept traffic from HVM-Firewall.

### Expected or desired behavior:

Would like to achieve the following:

clients <--> Lan/RTR <--> HVM-Firewall <--> sys-whonix <--> sys-firewall <--> sys-net <--> Physical-Firewall <--> ISP

At lease to get the HVM-Firewall routing to sys-whonix.

### Actual behavior:

I don't think 1-above is necessary since the HVM-FW has a global route to 10.137.0.0/16, but cannot ping nor traceroute to sys-whonix.
It seems the breakdown is at sys-firewall since it cannot ping nor traceroute to sys-whonix - perhaps by design.
Stuck!

### General notes:

The HVM-Firewall is OPNsense.
Tried static route to sys-whonix (0.7) via the WAN GW (0.6).
There is a default ICMP (IPv4/6) deny rule from WAN interface.
HVM-Firewall can ICMP to anything that will allow it.

---

### I have consulted the following relevant [documentation](https://www.qubes-os.org/doc/):

Enabling networking between two qubes.
https://www.qubes-os.org/doc/firewall/#enabling-networking-between-two-qubes

### I am aware of the following related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues:

Nothing found.

**Comment by andrewdavidwong** [comment]
Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this does not appear to be suitable for `qubes-issues`. We ask that you please post this on the [`qubes-users` mailing list or forum](https://www.qubes-os.org/support/) instead. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a brief comment explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.
