### ISSUE TITLE
Fullscreen Multiple Monitors not possible

### ISSUE THREAD

**Issue by michaelschefczyk** [QubesOS/qubes-issues#6441]
In QubesOS R4.0, I have two monitors connected. I would like to achieve what does work in Debian, for example, that is:

xfreerdp /multimon

This leads to an freerdp connection across multiple monitors.

In QubesOS R4.0 it does work in principle. A window as wide as the set of monitors does get created. However, the fullscreen feature does not work. As soon as one clicks fullscreen, the window gets confined to one of the monitors.

Is there a way to overcome that limitation? If "fullscreen" can be made to work across physical monitors, xfreerdp /multimon should work as well.

Thank you very much!

Michael Schefczyk

**Comment by marmarek** [comment]
Normally, a VM window is not permitted to occupy the whole screen and hide its decoration. It can be allowed as described in https://www.qubes-os.org/doc/full-screen-mode/

**Comment by andrewdavidwong** [comment]
Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this does not appear to be suitable for `qubes-issues`. We ask that you please post this on the [`qubes-users` mailing list or forum](https://www.qubes-os.org/support/) instead. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a brief comment explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.

**Comment by michaelschefczyk** [comment]
Sorry if I did misstate that. This was not meant as a support question. My aim was to find out if something is intended behaviour that will last or not. Other users are unlikely to be able to answer that on behalf of the developers. Of course, you are under no obligation to answer at all.

The point is the following: I did make the setting as suggested by Marek Marczykowski-Górecki. But whenever you have two physical montiors side by side to form one large screen out of the left monitor and the right monitor, "fullscreen" gets limited to one of the monitors (so full monitor really instead of full screen). In many other non virtualized linux distros with GNOME for example, you can provoke full screen to cover the entirety of two monitors. One way to provoke that under Debian, for example, is to do "xfreerdp /multimon". Knowing if that can be made to work in R4.0 (or later in R4.1) would be helpful in order to sort out which applications might work and for which one might have to go back to plain Debian, for example.

Should I post this to the users mailing list?

**Comment by andrewdavidwong** [comment]
> My aim was to find out if something is intended behaviour that will last or not.

This is still not the appropriate venue for such questions, as explained above.

> The point is the following: I did make the setting as suggested by Marek Marczykowski-Górecki. But whenever you have two physical montiors side by side to form one large screen out of the left monitor and the right monitor, "fullscreen" gets limited to one of the monitors (so full monitor really instead of full screen). In many other non virtualized linux distros with GNOME for example, you can provoke full screen to cover the entirety of two monitors. One way to provoke that under Debian, for example, is to do "xfreerdp /multimon". Knowing if that can be made to work in R4.0 (or later in R4.1) would be helpful in order to sort out which applications might work and for which one might have to go back to plain Debian, for example.

This is basically still a support question.

> Should I post this to the users mailing list?

Yes, please do.

**Comment by michaelschefczyk** [comment]
Thank you. As you can imagine, I am respectful but not pleased. As I need the feature to work productively, I am trying to clarify the issue to avoid moving back to plain Debian prematurely, which I would regret and see as a personal setback in terms of secure computing. At my university, there was always some sort of admiration for someone from the business faculty focusing on PC security more than the informatics persons who do research on OS security and use Apple stuff or Windows 10 personally.

The empirical issue is that questions like this will not get answered. An exactly matching case is this:

https://qubes-os.discourse.group/t/multiple-monitors-and-full-screen-apps/1621

I did post the question and I still hope for the best.
