### ISSUE TITLE
SOLVED: No internet outside sys-net

### ISSUE THREAD

**Issue by gdvine** [QubesOS/qubes-issues#6442]
**Qubes OS version**

So far have tested fresh installs of 4.0.1, 4.0.3, and 4.0.4 as well as a system running 4.0.x with updates for a year before bug appeared.

**Affected component(s) or functionality**

Networking

**Brief summary**

No VMs outside `sys-net` get any internet. 
`sys-net` connects fine via WiFi and can access the web via Firefox or ping.

**How Reproducible**

**Laptop 1 (Dell**): Installed 4.0.x (latest) over a year ago, got this bug on fresh install. Continued testing for a few hours and several reboots later, the bug went away. Over a year later, the bug reappeared while I was away from the computer and I haven't been able to fix it. (My skills are not advanced though.) 

**Laptop 2 (Lenovo)**: Just bought this unit as a replacement in case bug was hardware-related on the Dell. Bug is present on fresh Qubes install with 4.0.1, 4.0.3, and now 4.0.4.

**To Reproduce**

1. Install fresh Qubes OS.
2. Connect to WiFi.
3. Try to get online with any other qube.

**Expected behavior**

On fresh install, `sys-firewall` should be able to ping or get on the web with Firefox, right? Or at least an AppVM could connect to the web using `sys-net` as net qube.

**Actual behavior**

No qubes whatsoever outside `sys-net` have any access to the internet. Pings and Firefox pageloads time out.

**Additional context**

My working Qubes 4.0.x setup was fine for about 14 months before this bug reappeared, so it may be a race condition or something.
Some detail: https://qubes-os.discourse.group/t/new-and-older-installs-have-no-networking-outside-sys-net/3100

**Solutions you've tried**

- Fedora 29,30,31,32,33 as template for `sys-net` and other VMs
- Debian as template (couldn't get online with `sys-net` though)
- Different laptop from HCL from a different brand
- Reinstall Qubes versions 4.0.1, 4.0.3, 4.0.4
- Restore from backup when VMs had internet
- Various combinations of PCI passthrough settings
- Disabling VT-D
- various combinations of boot order
- and more things I've seen on Github, Reddit, Discourse

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

At least a dozen Qubes documentation pages
Is there something I need to activate in order to get internet to share among qubes after install? I haven't found anything to that effect in the documentation.

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

I have seen a few similar issues to this on forums, along with issues #5648, #5576, #5570, #5291, and #5269, but none of the fixes on those issues has worked.

**Comment by hackerncoder** [comment]
> Is there something I need to activate in order to get internet to share among qubes after install? I haven't found anything to that effect in the documentation.

As I told you in reddit, no.

**Comment by gdvine** [comment]
> Are you trying to ping ip addresses or domain names? Is internal ping working (sys-firewall->sys-net, someAppVm-> sys->firewall) ?

Neither IP address nor domain name pings function outside `sys-net`.

How do I ping `sys-net`? Its IP is not listed in Qube Manager.

AppVM -> sys-firewall ping works.

**Comment by donob4n** [comment]
> How do I ping `sys-net`? **Its IP is not listed in Qube Manager.**

I would say that there is the problem. Your sys-net should have an internal IP and it should be displayed in Qube Manager. Try opening a terminal in 'sys-net' and look what shows "ifconfig". All vif interfaces should have the sys-net ip address. Also look in 'sys-net', maybe there is some useful information.

**Comment by gdvine** [comment]
`ifconfig` in `sys-net` shows

```
ens7: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        ether c8:5b:76:94:44:12  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device interrupt 44  memory 0xf2000000-f2020000  

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 2  bytes 92 (92.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 2  bytes 92 (92.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

vif9.0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.137.0.5  netmask 255.255.255.255  broadcast 0.0.0.0
        inet6 fe80::fcff:ffff:feff:ffff  prefixlen 64  scopeid 0x20<link>
        ether fe:ff:ff:ff:ff:ff  txqueuelen 32  (Ethernet)
        RX packets 185  bytes 13286 (12.9 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 13  bytes 922 (922.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

wls6: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.16.3.159  netmask 255.255.248.0  broadcast 172.16.7.255
        inet6 fe80::7f1c:d507:b42e:51f8  prefixlen 64  scopeid 0x20<link>
        ether f0:d5:bf:78:ce:d1  txqueuelen 1000  (Ethernet)
        RX packets 150673  bytes 219623473 (209.4 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 31937  bytes 3678333 (3.5 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

```

What do you mean by "look in `sys-net`"?

Oh actually now I do see the IP address for `sys-net`, sorry. I was looking in the qube settings where it's greyed out, but it's in the main table of Qube Manager.

I AM able to ping `sys-net` from `sys-firewall` after all.

**Comment by donob4n** [comment]
So:
- ping from `sys-net` to `your-router` works
- ping from `sys-firewall` to `sys-net` works
- ping from `sys-firewall `to `you-router` fails

Right? Have you got some firewall rules defined in `sys-firewall`? I would try to diagnose this with tcpdump o wireshark, check the iptables/nftables rules...  At some point the packets (or their reply) are being dropped.

**Comment by gdvine** [comment]
Your bullet list is correct - I just made sure by trying to ping the router.

I do NOT have any rules defined anywhere! This is a fresh install of 4.0.4 currently. As stated in the OP, 4.0.1 and 4.0.3 were also FRESH installs with standard setup (although I declined to have the default AppVMs installed) and also exhibited this bug.

The rest of your comments are above my skill level. If you'd like me to run another command, just let me know.

**Comment by brendanhoar** [comment]
Unlikely custom firewall, OP is stating this happens immediately after each install and also recently appeared on a working install.

Some of OP’s comments have been contradictory so I’m a little unclear if an app vm that routes directly to sys-net works.

Thinking maybe a local network issue with Max hops?

 Does your router/access-point have a limit in the TTL allowed for incoming packets? Does it generate local packets with very low TTL values?

Have you tried the default Qubes installs on other wifi networks? Have you tried with Ethernet (assuming you have a port on the laptop(s) and that you have assigned the device to sys-net)?

B

**Comment by gdvine** [comment]
Hello Brendan, thanks for your input.

> Unlikely custom firewall, OP is stating this happens immediately after each install and also recently appeared on a working install.

Correct.

> Some of OP’s comments have been contradictory so I’m a little unclear if an app vm that routes directly to sys-net works.

Sorry for any confusion. AppVM connecting through `sys-net` definitely does NOT work. Nothing I have tried enables _any_ internet in _any_ qube other than `sys-net`.

> Does your router/access-point have a limit in the TTL allowed for incoming local packets? Does it generate local packets with very low TTL values?

I have no idea about packet limits, but I can say my original Qubes install which did work was on this same network for several months before suddenly exhibiting this bug.

Regarding TTL, is that the ping time? The pings from `sys-net` to the router were returned in under 3ms.

> Have you tried the default Qubes installs on other wifi networks? 

My original setup exhibited this issue over a year ago on a different wifi network directly after fresh install. The bug went away after a few hours, however.

>Have you tried with Ethernet (assuming you have a port on the laptop(s) and that you have assigned the device to sys-net)?

I do not have access to an ethernet port at this location. I'm confused why you are focusing on the connection between the computer and the router since `sys-net` connects to the internet perfectly, but my knowledge is limited so I will go and test this setup on ethernet at a different location right now.

**Comment by donob4n** [comment]
First check this command on sys-net: `sudo sysctl -a | grep .forwarding` , all ipv4 interfaces should have forwarding enabled.

If ok try this on sys-net:
- `sudo dnf install tcpdump`
- `sudo tcpdump -i wls6`

Do some pings: sys-net->router, sys-firewall->router... (also sys-firewall->sys-net but probably are not captured by this interface) You should see packets captured by tcpdump.

-- Regarding TTL, is that the ping time? The pings from sys-net to the router were returned in under 3ms.
See: https://en.wikipedia.org/wiki/Time_to_live
If you don't have any other network for testing you could try sharing Wifi with your phone. It is unlikely but your problem seems pretty strange.

**Comment by gdvine** [comment]
Huge thanks to Brendan! I'm at new location on ethernet and everything is working! 

I am going to test WiFi at this location now

**Comment by gdvine** [comment]
WiFi also works at new location. Thank you so much for helping out with this issue.

I'm ready to offer any assistance I can so that users can diagnose this type of router (?) problem in future. Would you like to know anything else about this router?
