### ISSUE TITLE
Fedora 33: Starting xterm with too many arguments breaks the GUI/xserver

### ISSUE THREAD

**Issue by AlxHnr** [QubesOS/qubes-issues#6444]
**Qubes OS version**

Qubes release 4.0 (R4.0)

**Affected component(s) or functionality**

GUI, xserver

**Brief summary**

Starting xterm with too many arguments breaks the VMs graphical subsystem. This makes it impossible to start graphical programs.

**How Reproducible**

Every time.

**To Reproduce**

1. Install fedora-33
2. Run this command from dom0:

```sh
qvm-run fedora-33 "xterm -e 'sh -c \"sudo dnf install audacity ffmpeg-libs ffmpeg gimp htop krita ledger newsflash man-db man-pages network-manager-applet python3-pygments xsel xsane vlc gnuplot keepassxc scrypt exfat-utils fuse-exfat ripmime libwebp-tools openssh-askpass psmisc cloc cmake patch gcovr SDL_gfx-devel SDL_ttf-devel SDL_image-devel SDL_mixer-devel SDL_sound-devel python-devel python3-devel libasan libubsan libtsan liblsan gifsicle ShellCheck gcc-c++ gdb clang clang-analyzer lldb valgrind libstdc++-docs cppcheck\"'"
```

**Expected behavior**

Xterm starts in the template VM and proceeds to execute the given command.

**Actual behavior**

The running template VM is bricked and can't start any graphical programs. This also breaks terminal emulators, making it difficult to diagnose the issue.

**Screenshots**

_None_

**Additional context**

This issue did not occur on previous releases. My code snippet from the _To Reproduce_ section has worked on all prior releases. Running xterm with these arguments from a gnome-terminal will also break the VM. Replacing `xterm -e` with `gnome-terminal --` in the initial command results in `Failed to execve: Filename too long`, but doesn't break the graphical subsystem.

**Solutions you've tried**

1. Restarting the fedora 33 template VM
2. Starting a terminal manually
3. Doing all operations manually

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

**Comment by rustybird** [comment]
This issue can be closed. (It didn't close automatically because the fix went to a non-default branch.)
