### ISSUE TITLE
Mouse and tablet can't click-and-drag using sys-usb

### ISSUE THREAD

**Issue by danrubins** [QubesOS/qubes-issues#6453]
**Qubes OS version**
4.0.4

**Affected component(s) or functionality**
Mouse and tablet pass-through from sys-usb

**Brief summary**
Both mouse and tablet both lose the ability to click and drag when being passed through sys-usb

**How Reproducible**
Immediate effect (after reboot to begin using sys-usb)

**To Reproduce**

1. Fresh Qubes 4.0.4, installed without sys-usb
2. Verify mouse and touchpad support click and drag events like moving windows, selecting text, etc. in both dom0 and AppVMs
3. Add sys-usb `sudo qubesctl state.sls qvm.sys-usb`
4. Enable usb keyboard `sudo qubesctl state.sls qvm.usb-keyboard`
5. Set mouse and trackpad policy to auto-allow by adding/editing `/etc/qubes-rpc/policy/qubes.InputMouse` and `/etc/qubes-rpc/policy/qubes.InputTablet` to read `sys-usb dom0 allow`
6. Reboot & log in
7. Drag-and-drop no longer works

**Expected behavior**
All mouse and tablet functionality continues to work, regardless of whether it is connected through sys-usb or directly to dom0.

**Actual behavior**
Most mouse and tablet functionality works, moving, clicking, scrolling, even two-fingered scroll on trackpad. However, the drag-and-drop functionality used for moving windows, selecting text, etc. no longer works.

**Screenshots**

**Additional context**

**Solutions you've tried**
Removing sys-usb reverts the problem

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
https://www.qubes-os.org/doc/usb-qubes/

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

**Comment by marmarek** [comment]
Thanks for the report!
Do you mean an actual mouse (separate device) stops working for moving windows and selecting text? Or just tablet's function of emulating mouse?
Can you check the difference in `evtest` tool output on those devices in sys-usb and dom0? Just the initial info on what events are supported. You'll need to install it in both dom0 and the sys-usb's template/

**Comment by danrubins** [comment]
Thanks for taking a look! The actual mouse (HP J2X04AA) stops working, but just for the drag-and-drop functionality, as well the same for a tablet's mouse emulation (apple magic trackpad 2 via usb). I'll post `evtest` output shortly.

**Comment by marmarek** [comment]
This is really weird. I thought there is some issue with how device is presented (maybe some missing button or such), but those look pretty much the same. There must be something else...
Maybe some events are represented differently? Try to see what `evtest` will show when you try to click-and-drag. Note it will work in dom0 normally, but to test in `sys-usb`, you'll need to kill `input-proxy-sender` process connected to that device (and it will stop sending actual mouse/tablet events, until you unplug and plug it back). If you use USB keyboard, be careful to _not_ kill the `input-proxy-sender` process servicing it.

**Comment by danrubins** [comment]
These are what the events look like when I click and release, across both devices and whether plugged into sys-usb or dom0. Identical values other than the time.

Event: time 1616188876.378506, type 4 (EV_MSC), code 4 (MSC_SCAN), value 90001
Event: time 1616188876.378506, type 1 (EV_KEY), code 272 (BTN_LEFT), value 1

Event: time 1616188877.490566, type 4 (EV_MSC), code 4 (MSC_SCAN), value 90001
Event: time 1616188877.490566, type 1 (EV_KEY), code 272 (BTN_LEFT), value 0

**Comment by danrubins** [comment]
Interestingly, when I connect a bluetooth dongle to sys-usb and use a bluetooth mouse, everything works fine. Its certainly odd behavior but I now have a workaround.

**Comment by danrubins** [comment]
Closing since I have a workaround. I still can't use a USB mouse or tablet via sys-usb, but bluetooth is fine and that'll work.

**Comment by DemiMarie** [comment]
Reopening since bluetooth is less secure and this bug still needs to be fixed.

**Comment by WhatIsRealityBro** [comment]
I'm having the same issue while using my trackpad with the sys-usb qube - I'm unable to use two fingers to move windows around or drag and drop files and I can't right click at all. When not using the sys-usb qube I'm able to use my trackpad as normal.
