### ISSUE TITLE
Qubes Builder no longer verifying signatures

### ISSUE THREAD

**Issue by unman** [QubesOS/qubes-issues#6454]
### Qubes OS version:

4.0.4

### Affected component(s) or functionality:

Qubes Builder

---

### Steps to reproduce the behavior:
1. Configure builder with split gpg, and no gpg configuration in builder qube.
2. Close down gpg qube
3. `make get-sources`

### Expected or desired behavior:
gpg backend will be started and user prompted for access to keys. (Previous behaviour)

### Actual behavior:
gpg backend **not** started.
Update script shows:
```
--> Verifying tags...
---> Good tag 0adf571080d986e2efe93fd1a31671f7a3b21e3d
```

### General notes:
I *thought* that I had seen this behaviour before, but put it down to paranoia.
Unless I'm missing something, the signed tags should be verified using gpg - since the builder doesn't have its *own* gpg configuration, and split-gpg is correctly configured, the verification should fail if the back end is not available.
(I actually tested this in the past and confirmed that it failed.)

If the intention is to allow for cases where there is no gpg configuration, then the response should be appropriate and not be "Good tag".

---

### I have consulted the following relevant [documentation](https://www.qubes-os.org/doc/):
https://www.qubes-os.org/doc/qubes-builder/

**Comment by marmarek** [comment]
I'm not sure how you got this conclusion. Gpg works perfectly fine without any specific configuration. In fact, qubes-builder uses minimal gpg keyring by default for a long time already (see [`KEYRING_DIR_GIT` option](https://github.com/QubesOS/qubes-builder/blob/master/doc/Configuration.md#keyring_dir_git)). What have changed recently-ish, is to force `gpg.program=gpg` git option for the signature check purpose, to really use it, even if you have split-gpg configured in git. This way we are sure it really verifies signatures against known set of keys, not the whole keyring you happen to have.

**Comment by unman** [comment]
On Thu, Mar 11, 2021 at 08:51:07AM -0800, Marek Marczykowski-G??recki wrote:
> I'm not sure how you got this conclusion. Gpg works perfectly fine without any specific configuration. In fact, qubes-builder uses minimal gpg keyring by default for a long time already (see [`KEYRING_DIR_GIT` option](https://github.com/QubesOS/qubes-builder/blob/master/doc/Configuration.md#keyring_dir_git)). What have changed recently-ish, is to force `gpg.program=gpg` git option for the signature check purpose, to really use it, even if you have split-gpg configured in git. This way we are sure it really verifies signatures against known set of keys, not the whole keyring you happen to have.
> 

OK - I didnt interpret "explicitly set gpg.program" to mean "over ride user's
explicit setting"
