### ISSUE TITLE
Error creating VM: file pool cannot export dirty volumes

### ISSUE THREAD

**Issue by chris-freedom** [QubesOS/qubes-issues#6456]
**Qubes OS version**

R4.0

**Affected component(s) or functionality**

qvm-create and GUI Qube Manager

**Brief summary**

When i was trying to create new standalone vm based on a template i have got an error:
`myVM: Cloning root volume`
`app: Error creating VM: file pool cannot export dirty volumes`

**To Reproduce**

1. `qvm-create --class StandaloneVM --template debian-10 --label yellow --property virt_mode=hvm myVM`

**Expected behavior**

New VM created

**Actual behavior**

Got an error

**Comment by donob4n** [comment]
Is your template debian-10 running? I can't reproduce with btrfs pool I will try with lvm too.
uHm, are you using File Pool? Or maybe your AppVM destination pool.

Could you post your qubes pools?

**Comment by chris-freedom** [comment]
Debian template isn't running. How can i share my pools information? Do i need execute any command in my terminal?

**Comment by donob4n** [comment]
`qvm-pool` in dom0

**Comment by chris-freedom** [comment]
`[user@dom0 ~]$ qvm-pool`
`NAME          DRIVER`
`varlibqubes   file`
`linux-kernel  linux-kernel`

**Comment by donob4n** [comment]
That's all? So you don't have a LVM or btrfs pool maybe your error is expected. file pool doesn't support snapshots so creating a StandaloneVM will duplicate the root image.
Did you install it recently? What did you select on hard disk settings?

**Comment by chris-freedom** [comment]
That's all. I installed it a week ago and used this guide to have raid 0 and encrypted disk partitions:

 Boot from usb flash drive. Press `ctrl + alt + F2` to enter console

Create two partition on sda and sdb disks. You can test fdisk command without save if remove last symbol w in echo command:
`# echo -e "n\np\n1\n\n+1000M\nn\np\n2\n\n\nw" | fdisk /dev/sda`
`# echo -e "n\np\n1\n\n+1000M\nn\np\n2\n\n\nw" | fdisk /dev/sdb
`

Create RAID devices. On answer Continue creating array? enter y:
`# mdadm --create --verbose /dev/md0 --level=mirror --raid-devices=2 /dev/sda1 /dev/sdb1`
`# mdadm --create --verbose /dev/md1 --level=mirror --raid-devices=2 /dev/sda2 /dev/sdb2`

Create LUKS encrypted volume:
`# cryptsetup -v --hash sha512 --cipher aes-xts-plain64 --key-size 512 --use-random --iter-time 5000 --verify-passphrase luksFormat /dev/md1`

Open encrypted volume:
`# cryptsetup open /dev/md1 luks`

Create LVM volumes:
`# pvcreate /dev/mapper/luks`
`# vgcreate qubes_dom0 /dev/mapper/luks`
`# lvcreate -n swap -L 10G qubes_dom0`
`# lvcreate -n root -l +100%FREE qubes_dom0`

`# mkfs.ext4 /dev/md0`
`# mkfs.ext4 /dev/mapper/qubes_dom0-root`
`# mkswap /dev/mapper/qubes_dom0-swap`

check disks structure and ids:
`# lsblk`
`# blkid`

press `ctrl + alt + F6` to return to graphical installer.

In the `Installation destination` check both disks then check `I will configure partitioning` and uncheck `Encrypt my data` then press `Done`.

In `Unknown` spoiler set` /boot`, `/`, and `swap` mount points and check `Reformat` option for each one. During configuration may be errors which will produce reboot, it's okay.

**Comment by donob4n** [comment]
Try creating a new lvm pool inside your LVM https://www.qubes-os.org/doc/secondary-storage/ and then move (or clone) all your VM's to it.

In a standard installation `varlibqubes` pool only saves configuration files.

**Comment by chris-freedom** [comment]
thanks, i'll try it.
