### ISSUE TITLE
Cant update/upgrade due to fedora repos (http?!) connection failure 

### ISSUE THREAD

**Issue by TNTBOMBOM** [QubesOS/qubes-issues#6457]
**Qubes OS version**

R4.0

**Affected component(s) or functionality**
Fedora Repositories 

**Brief summary**
Fedora seems to have problems when trying to connect to their repos , Although fedora should use https only repos the error showing its trying to connect to http plain which weird. 

**How Reproducible**
No idea if its happening to me only or to others but i dont know how to reproduce if its not happening to someone else. 

**To Reproduce**
N/A

**Expected behavior**
Should update/upgrade normally using https repos

**Actual behavior**
Fail to update/upgrade because its trying to connect to an http repos which causes the connection to fail

**Screenshots**
![httpsqubesrep](https://user-images.githubusercontent.com/11895339/111026510-814bad00-83e2-11eb-869b-7ce28ab742ef.png)

![httpsqubesrep2](https://user-images.githubusercontent.com/11895339/111026516-86106100-83e2-11eb-8bd4-95e2f96d91c9.png)

**Comment by DemiMarie** [comment]
These errors are normal and harmless.  DNF will automatically switch from one mirror to another as needed.

**Comment by TNTBOMBOM** [comment]
Yeah but as you can see i cant get updates and http (without TLS) 
shouldnt be there at the first place. So for sure something is not 
normal in here.

Demi Marie Obenour:
> These errors are normal and harmless.  DNF will automatically switch from one mirror to another as needed.
>

**Comment by DemiMarie** [comment]
> Yeah but as you can see i cant get updates and http (without TLS) shouldnt be there at the first place. So for sure something is not normal in here.

Not getting updates is certainly not normal, but the use of HTTP is normal.  Fedora serves (over TLS) metalinks that contain secure hashes of the metadata, and the metadata contains secure hashes of the packages.  Furthermore, the packages themselves are signed.

What happens if you put `zchunk=False` (on a line of its own) in `/etc/dnf/dnf.conf`?

**Comment by TNTBOMBOM** [comment]
Solved the issue,Not sure how much by turning it off will effect 
anything. I believe this is more of a fedora project repositories issue 
not specific to qubes?

Demi Marie Obenour:
>> Yeah but as you can see i cant get updates and http (without TLS) shouldnt be there at the first place. So for sure something is not normal in here.
> 
> Not getting updates is certainly not normal, but the use of HTTP is normal.  Fedora serves (over TLS) metalinks that contain secure hashes of the metadata, and the metadata contains secure hashes of the packages.  Furthermore, the packages themselves are signed.
> 
> What happens if you put `zchunk=False` (on a line of its own) in `/etc/dnf/dnf.conf`?
>

**Comment by andrewdavidwong** [comment]
> Solved the issue,Not sure how much by turning it off will effect 
> anything. I believe this is more of a fedora project repositories issue 
> not specific to qubes?
> 

Yes, I think so. Either that or common transient network problems due to updating over Tor, in which case you can just retry again later.

**Comment by TNTBOMBOM** [comment]
Just for the sake of adding more beneficial and up-to-date logs, Fedora mirrors are garbage and often generate errors, which can be frustrating for users:

```
bash-5.2# dnf upgrade --refresh
Fedora 38 - x86_64                              6.7 kB/s | 6.5 kB     00:00    
Fedora 38 openh264 (From Cisco) - x86_64        744  B/s | 989  B     00:01    
Fedora 38 - x86_64 - Updates                     23 kB/s |  34 kB     00:01    
Fedora 38 - x86_64 - Updates                    788 kB/s | 4.0 MB     00:05    
Qubes OS Repository for VM (updates)            635  B/s | 833  B     00:01    
Dependencies resolved.
================================================================================
 Package              Architecture  Version                Repository      Size
================================================================================
Upgrading:
 hwdata               noarch        0.375-1.fc38           updates        1.6 M
 libX11               x86_64        1.8.7-1.fc38           updates        650 k
 libX11-common        noarch        1.8.7-1.fc38           updates        176 k
 libX11-xcb           x86_64        1.8.7-1.fc38           updates         12 k

Transaction Summary
================================================================================
Upgrade  4 Packages

Total download size: 2.4 M
Is this ok [y/N]: y
Downloading Packages:
[MIRROR] hwdata-0.374-1.fc38_0.375-1.fc38.noarch.drpm: Status code: 404 for http://ftp.iij.ad.jp/pub/linux/Fedora/fedora/linux/updates/38/Everything/x86_64/drpms/hwdata-0.374-1.fc38_0.375-1.fc38.noarch.drpm (IP: 127.0.0.1)
[MIRROR] libX11-1.8.6-1.fc38_1.8.7-1.fc38.x86_64.drpm: Status code: 404 for http://ftp.iij.ad.jp/pub/linux/Fedora/fedora/linux/updates/38/Everything/x86_64/drpms/libX11-1.8.6-1.fc38_1.8.7-1.fc38.x86_64.drpm (IP: 127.0.0.1)
[MIRROR] libX11-common-1.8.6-1.fc38_1.8.7-1.fc38.noarch.drpm: Status code: 404 for http://ftp.iij.ad.jp/pub/linux/Fedora/fedora/linux/updates/38/Everything/x86_64/drpms/libX11-common-1.8.6-1.fc38_1.8.7-1.fc38.noarch.drpm (IP: 127.0.0.1)
(1/4): libX11-1.8.6-1.fc38_1.8.7-1.fc38.x86_64.  18 kB/s |  42 kB     00:02    
[MIRROR] libX11-xcb-1.8.6-1.fc38_1.8.7-1.fc38.x86_64.drpm: Status code: 404 for http://ftp.iij.ad.jp/pub/linux/Fedora/fedora/linux/updates/38/Everything/x86_64/drpms/libX11-xcb-1.8.6-1.fc38_1.8.7-1.fc38.x86_64.drpm (IP: 127.0.0.1)
(2/4): libX11-common-1.8.6-1.fc38_1.8.7-1.fc38.  17 kB/s |  53 kB     00:03    
[DRPM 1/4] libX11-1.8.6-1.fc38_1.8.7-1.fc38.x86_64.drpm: done                  
(3/4): hwdata-0.374-1.fc38_0.375-1.fc38.noarch. 4.4 kB/s |  15 kB     00:03    
(4/4): libX11-xcb-1.8.6-1.fc38_1.8.7-1.fc38.x86 8.3 kB/s | 8.0 kB     00:00    
[DRPM 2/4] libX11-common-1.8.6-1.fc38_1.8.7-1.fc38.noarch.drpm: done           
[DRPM 3/4] libX11-xcb-1.8.6-1.fc38_1.8.7-1.fc38.x86_64.drpm: done              
[DRPM 4/4] hwdata-0.374-1.fc38_0.375-1.fc38.noarch.drpm: done                  
--------------------------------------------------------------------------------
Total                                            12 kB/s | 118 kB     00:09     
Delta RPMs reduced 2.4 MB of updates to 0.1 MB (95.2% saved)
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                        1/1 
  Upgrading        : libX11-common-1.8.7-1.fc38.noarch                      1/8 
  Upgrading        : libX11-1.8.7-1.fc38.x86_64                             2/8 
  Upgrading        : libX11-xcb-1.8.7-1.fc38.x86_64                         3/8 
  Upgrading        : hwdata-0.375-1.fc38.noarch                             4/8 
  Cleanup          : hwdata-0.374-1.fc38.noarch                             5/8 
  Cleanup          : libX11-1.8.6-1.fc38.x86_64                             6/8 
  Cleanup          : libX11-common-1.8.6-1.fc38.noarch                      7/8 
  Cleanup          : libX11-xcb-1.8.6-1.fc38.x86_64                         8/8 
  Running scriptlet: libX11-xcb-1.8.6-1.fc38.x86_64                         8/8 
  Verifying        : hwdata-0.375-1.fc38.noarch                             1/8 
  Verifying        : hwdata-0.374-1.fc38.noarch                             2/8 
  Verifying        : libX11-1.8.7-1.fc38.x86_64                             3/8 
  Verifying        : libX11-1.8.6-1.fc38.x86_64                             4/8 
  Verifying        : libX11-common-1.8.7-1.fc38.noarch                      5/8 
  Verifying        : libX11-common-1.8.6-1.fc38.noarch                      6/8 
  Verifying        : libX11-xcb-1.8.7-1.fc38.x86_64                         7/8 
  Verifying        : libX11-xcb-1.8.6-1.fc38.x86_64                         8/8 
Notifying dom0 about installed applications

Upgraded:
  hwdata-0.375-1.fc38.noarch               libX11-1.8.7-1.fc38.x86_64           
  libX11-common-1.8.7-1.fc38.noarch        libX11-xcb-1.8.7-1.fc38.x86_64       

Complete!
bash-5.2# 
```
