### ISSUE TITLE
Screen freezing in Qubes R4.0.4 with kernel 5.10

### ISSUE THREAD

**Issue by GWeck** [QubesOS/qubes-issues#6458]
**Qubes OS version**
R4.0 fully updated

**Affected component(s) or functionality**
complete system

**Brief summary**
If kernel 5.10 is installed in dom0 of Qubes R4.0.x, the system freezes sometimes. The mouse may be moved, but clicking or typing has no effect.

**How Reproducible**
Happens randomly, maybe once a day or so.

**To Reproduce**
Install kernel-latest on a system running R4.0. If the kernel version displayed from the `About` menu entry in the Qubes manager shows 5.10, you're stuck.

**Expected behavior**
The system should stay responsive.

**Actual behavior**
Random freezing.

**Additional context**
R4.1, running kernel 5.10 is not affected, as well as R4.0 running kernel 5.4.

**Solutions you've tried**
When the systems hangs, only a hard reset and reboot seem to help, thereby possibly losing current work results.
If Qubes is started with kernel 5.4 again, the problem disappears.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
This seems to be a general problem of the 5.10 kernel, which occurs in some configurations. It is reported for Arch Linux, too, and maybe is dependent on the processor and/or GPU type (nvidia??? or Intel Graphics?). See, for instance:
[Arch linux randomly freezes after updating to kernel 5.10](https://unix.stackexchange.com/questions/627513/arch-linux-randomly-freezes-after-updating-to-kernel-5-10)
[Xorg freeze / hang / process D-state with kernel 5.10.1+](https://gitlab.freedesktop.org/drm/intel/-/issues/2905)

**Comment by marmarek** [comment]
There is already 5.11 kernel in the current-testing repo, this may be fixed there already.
Also, which 5.10 specifically?

**Comment by GWeck** [comment]
I tested with 5.10.13-1. If I get the 5.11, I will test it.

**Comment by GWeck** [comment]
I installed the 5.11.4-1 on the same machine that had the freezing problem with the 5.10.13-1. So far, the system is running, but it may take some time till it freezes. So I cannot be sure if it's o.k. now or not. If no problem occurs during the next few days, we might have luck. Let's see ...

**Comment by GWeck** [comment]
So far, R4.04 with kernel 5.11.4-1 runs without problems, so maybe we are lucky. I changed my R4.1 test system to kernel 5.11.4-1, too, and it is running o.k.

In the first of the two links above, a user explains that the move to 5.10.16-1 solved the freezing problem. Maybe this is also the cause why I saw the freezing only under my Qubes R4.0.4, which was running with kernel 5.10.13-1, and not on Qubes R4.1 which was running under 5.10.16-1.

**Comment by GWeck** [comment]
So far, I had no screen freezing with 5.11.4-1 (neither for R4.0.4 nor R4.1), but this might still come sometime …

**Comment by GWeck** [comment]
Still no more screen freezing. I am running the R4.1 now with kernel 5.11.8-1, and that is o.k., too.

**Comment by DemiMarie** [comment]
5.10 does not boot for me due to a kernel bug.

**Comment by marmarek** [comment]
Which 5.10 specifically? And which qubes version?

**Comment by DemiMarie** [comment]
> Which 5.10 specifically? And which qubes version?

This is on R4.0.  All of the 5.10 versions I tried failed to boot, as does the most recent `kernel-latest`.  5.4 freezes intermittently.  4.19 works but has graphics glitches.

**Comment by GWeck** [comment]
Do you have a nvidia graphics driver? My system has uses the integrated Intel grphics of an i5-7200U prcessor. Perhaps this explains the difference??

**Comment by DemiMarie** [comment]
> Do you have a nvidia graphics driver? My system has uses the integrated Intel grphics of an i5-7200U prcessor. Perhaps this explains the difference??

I have an nvidia graphics card, but not the proprietary driver.  I can try disabling the nouveau driver.

**Comment by GWeck** [comment]
Meanwhile I have changed to kernel 5.11.8-1 in Qubes R4.0.4, too. So far, there has been no more screen freezing, so I suppose / hope that the problem has gone away with this kernel.

**Comment by GWeck** [comment]
Now it's kernel 5.11.12 in R4.1, and no more freezing occurred.

**Comment by GWeck** [comment]
Closing now since there was no more freezing since more than 2 months.
