### ISSUE TITLE
qrexec removes slashes from user parameters

### ISSUE THREAD

**Issue by iblue** [QubesOS/qubes-issues#6459]
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
qrexec

**Brief summary**
qrexec removes slashes from user parameters and replaces them by underscores.

**How Reproducible**
100% of the time

**To Reproduce**

1. Install https://github.com/iblue/qvm-mount (instructions there) on two debian-10 qubes named example1 and example2.
2. On example1, run `mkdir foo; qvm-mount example2:/tmp`

I think that's the easiest way. If you prefer a more simple testcase, you can use the example in https://www.qubes-os.org/doc/qrexec/#rpc-service-with-argument-file-reader where you replace `testfile1` with `/tmp/testfile1` or similar and you run into the same issues.

**Expected behavior**
So, the issue is that a slash gets replaced by an underscore in the user parameters. In my example, there should be a dialog asking you to execute `qubes.MountReadWrite+/tmp` and the parameter `/tmp` should be sent to the example2.

**Actual behavior**
There is a dialog asking to run `qubes.MountReadWrite+_tmp` and the parameter `_tmp` is sent to example2.

**Screenshots**
Probably not that relevant.

**Additional context**
So, I have been developing this tool to share directories across VMs. And I think it would be nice if the user could confirm not only the command but also the directory, in case the client VM is compromized. But it seems like qrexec somehow replaces the slashes in the paths, which requires an ugly workaround on my side and now if the user tries to mount directories containing underscores, thing go not so nice. See https://github.com/iblue/qvm-mount/blob/master/rpc/qubes.MountReadWrite#L7-L11

**Solutions you've tried**
I've tried to fix it myself, but I've seen from https://github.com/QubesOS/qubes-core-qrexec/blob/master/libqrexec/replace.c and by consulting an octal ASCII table, that it should NOT replace slashes and now I'm a little stuck. If you could point me to the solution I would try to fix it myself.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
* https://www.qubes-os.org/doc/qrexec/
* https://www.qubes-os.org/doc/qrexec-internals/
* https://www.qubes-os.org/doc/qrexec-socket-services/

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
I searched for *qrexec* and 5600 issues came up, so i searched for *qrexec replaces* and read both issues, but they do not seem to be related to my problem.

**Comment by iamahuman** [comment]
This is working as expected.

From https://www.qubes-os.org/doc/qrexec/#rpc-service-with-argument-file-reader:

> Make sure the file is executable! (The service argument is already sanitized by qrexec framework. It is guaranteed to not contain any spaces or slashes, so there should be no need for additional path sanitization.)

**Comment by iamahuman** [comment]
You may want to take a look at #2826 for the general discussion about sharing directories between VMs.

**Comment by iblue** [comment]
> You may want to take a look at #2826 for the general discussion about sharing directories between VMs.

Yes, I have read this issue a few days ago, found that none of the referred tools solve my problem and wrote qvm-mount. I will reference it in the thread.

So, to have a better user experience in my tool, I would like to display a path (including slashes) to the user to ask for confirmation AND get it as a parameter. Is there a way to do this? I could still just send the path as parameter, get it displayed with slashes and send it with the socket. But I think this is a not so elegant solution.

**Comment by iamahuman** [comment]
I believe this alternative approach (similar to https://github.com/woju/qubes-app-split-git) may be more secure:

1. Provide a UI on sharer side that lets you select directories to be shared (exported).
2. Create a directory `~/QubesShared` and put there symlinks to the shared directories.
3. On the client side, specify the share by the symlink name.

Anyway, thanks for your contribution!

**Comment by iamahuman** [comment]
That said, you can probably substitute `+` for a slash.

**Comment by iblue** [comment]
>     1. Provide a UI on sharer side that lets you select directories to be shared (exported).

That is actually a good idea. I will look into it. Thanks for your time!
