### ISSUE TITLE
skip the text if you want I was just wondering if this looks normal pretty much for this operating system.. it's a huge favor thank you

### ISSUE THREAD

**Issue by genericxero** [QubesOS/qubes-issues#6461]
I'm having a real hard time using this Android tablet but it's a good thing it has a USB port at least because my home network is infected which I'm starting to wonder if it doesn't have to do with solarwinds and my mom's work since I don't usually live here and it started when I moved here for a little bit also now after having my phone over at the chick's house which is my usual home one time and her getting all trust issue like and turning on Wi-Fi on I'm pretty damn sure I don't know how else it would happen her laptop is completely fucked this all started on Windows in both cases but I've been going through the operating systems and the bootable options like the Casper ski I think was the first of which don't even get me started on how that went

I'm just broken this thing trying to clamp it to a desk so that I can have a be steady enough and I'm not going to be able to edit but take a look at these this is only from within cubes or less

QUBES OS

I've been studying and learning and playing this game of chess for about a month now
Everything I'm going to say end of this thing after that point above has just turned into other words that I was not trying to say I mean how hard is it took comprehend bit longer
BitLocker
Ay y okay yyy
😤🤦🏽‍♂️
I'm sure at least somebody can relate

But can you relate to this:
I'm just getting back into Lenox and I have no clue but I definitely seen some weird shit after resetting cmos flashing bios pulling the rim for a day or two and having no drives which kind of funny I password protected them when I was overtired one day and now I can't seem to reformat them -.-
I should not make passwords ever on day three

I really can't stress how annoying this tablet

Is to use right now but anyways I don't have my network card in because everything wants to connect to everything and it's on every device in the house 
I could give a lot more information and if it's asked for I do have the text laptop here which 
The chicks as in the woman's laptop anyway which has Windows and has all the major stuff going on that was going on before the virtualization and windows which led to all the other crazy stuff but I found on a bunch of things while most of my friends who know a little of stuff here and there trying to tell me I was crazy and then I finally had somebody look at it who would even look and then they were like oh shit so anyway without further explanation on that here is what I'm seeing on the original computer that was infected and that's cool little Linux on USB drive and I would just like to know you guys if this looks at all normal there is a tree and some other stuff you can see there's about 330 processes running and it's definitely lying about the CPU temperature that's for sure but that could just be something inaccurate I don't know it's just a push just to get these uploaded even moving a file to another folder on this thing has been a bitch some of the time and I'm really lucky I was able to find a way to make bootable USB is with this at least...  And just now I almost lost all that after already trying to iterate this five basic rudimentary ways and losing it each time so I'm going to set up now and try to attach everything I can just let me know if this looks normal basically is all I really needed to say but I can't seem to ever get anything out anywhere long enough for anyone to care or no anything and I can't find a damn single person I know who either wants to look or knows what the hell they're looking at so that's what this is for because of all of you seem very knowledgeable and this operating system is definitely an innovation..  I was surprised to see some of the things I did perhaps you can search some of the texts or words like fake or just scan through and see what you think because I don't know man I'm feeling weird about it

**Comment by genericxero** [comment]
![IMG_20210314_132306_0](https://user-images.githubusercontent.com/80643216/111081224-b0dce100-84d8-11eb-834b-f491799c77a0.jpg)
![Screenshot_2020-09-21_00-26-34](https://user-images.githubusercontent.com/80643216/111081229-b3d7d180-84d8-11eb-8349-c1ec3743068a.png)
![Screenshot_2020-09-21_00-14-04](https://user-images.githubusercontent.com/80643216/111081230-b4706800-84d8-11eb-8135-7b4232ce2e79.png)
![Screenshot_2020-09-21_00-30-33](https://user-images.githubusercontent.com/80643216/111081231-b508fe80-84d8-11eb-895e-29615c9b23ba.png)
![Screenshot_2020-09-21_00-25-36](https://user-images.githubusercontent.com/80643216/111081232-b5a19500-84d8-11eb-949e-908a725a2ea5.png)
![IMG_20210314_130933_6](https://user-images.githubusercontent.com/80643216/111081233-b63a2b80-84d8-11eb-8aff-6807f792db50.jpg)
![Screenshot_2020-09-21_00-29-40](https://user-images.githubusercontent.com/80643216/111081234-b6d2c200-84d8-11eb-98a6-88d86627a57c.png)
![Screenshot_2020-09-21_00-27-08](https://user-images.githubusercontent.com/80643216/111081236-b76b5880-84d8-11eb-9898-8820d8bad63b.png)
![Screenshot_2020-09-21_00-25-06](https://user-images.githubusercontent.com/80643216/111081237-b76b5880-84d8-11eb-980e-8683f94f96ad.png)
![Screenshot_2020-09-21_00-39-38](https://user-images.githubusercontent.com/80643216/111081238-b803ef00-84d8-11eb-8b7b-6ec95c752f5a.png)
![Screenshot_2020-09-21_00-25-59](https://user-images.githubusercontent.com/80643216/111081239-b89c8580-84d8-11eb-9e4a-2a546abf0253.png)
![Screenshot_2020-09-21_00-27-59](https://user-images.githubusercontent.com/80643216/111081240-b9351c00-84d8-11eb-8d4b-1bdb0b3b48a8.png)

**Comment by genericxero** [comment]
![IMG_20210314_132306_0](https://user-images.githubusercontent.com/80643216/111081224-b0dce100-84d8-11eb-834b-f491799c77a0.jpg)
![Screenshot_2020-09-21_00-26-34](https://user-images.githubusercontent.com/80643216/111081229-b3d7d180-84d8-11eb-8349-c1ec3743068a.png)
![Screenshot_2020-09-21_00-14-04](https://user-images.githubusercontent.com/80643216/111081230-b4706800-84d8-11eb-8135-7b4232ce2e79.png)
![Screenshot_2020-09-21_00-30-33](https://user-images.githubusercontent.com/80643216/111081231-b508fe80-84d8-11eb-895e-29615c9b23ba.png)
![Screenshot_2020-09-21_00-25-36](https://user-images.githubusercontent.com/80643216/111081232-b5a19500-84d8-11eb-949e-908a725a2ea5.png)
![IMG_20210314_130933_6](https://user-images.githubusercontent.com/80643216/111081233-b63a2b80-84d8-11eb-8aff-6807f792db50.jpg)
![Screenshot_2020-09-21_00-29-40](https://user-images.githubusercontent.com/80643216/111081234-b6d2c200-84d8-11eb-98a6-88d86627a57c.png)
![Screenshot_2020-09-21_00-27-08](https://user-images.githubusercontent.com/80643216/111081236-b76b5880-84d8-11eb-9898-8820d8bad63b.png)
![Screenshot_2020-09-21_00-25-06](https://user-images.githubusercontent.com/80643216/111081237-b76b5880-84d8-11eb-980e-8683f94f96ad.png)
![Screenshot_2020-09-21_00-39-38](https://user-images.githubusercontent.com/80643216/111081238-b803ef00-84d8-11eb-8b7b-6ec95c752f5a.png)
![Screenshot_2020-09-21_00-25-59](https://user-images.githubusercontent.com/80643216/111081239-b89c8580-84d8-11eb-9e4a-2a546abf0253.png)
![Screenshot_2020-09-21_00-27-59](https://user-images.githubusercontent.com/80643216/111081240-b9351c00-84d8-11eb-8d4b-1bdb0b3b48a8.png)

**Comment by genericxero** [comment]
Okay these are very long especially the second one that I'm going to upload but the tree is what I was interested n people seeing
Sorry I'm imagining somebody who knows the system pretty well will know but I certainly can't completely tell and if it is still there somewhere if it's possible it's in my GPU? well this is all been incredibly frustrating and I and definitely started out fun for a good while but I'm going to bed

**Comment by genericxero** [comment]
[tree from qbs.txt](https://github.com/QubesOS/qubes-issues/files/6137533/tree.from.qbs.txt)


FINALLY 
that took forever to upload.. this

someone will know if it all looks normal.. especaially  by the bottom. says 214203 files  then there is the systemd-private-   with rtkit -daemon.service  [error opening dir]

**Comment by fepitre** [comment]
This is not the place for such request. Please use https://qubes-os.discourse.group/.

**Comment by andrewdavidwong** [comment]
Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this does not appear to be suitable for `qubes-issues`. We ask that you please post this on the [`qubes-users` mailing list or forum](https://www.qubes-os.org/support/) instead. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a brief comment explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.

**Comment by genericxero** [comment]
hey sorry man
im having the worst time at life. this girl has really put me through it,
and call it borderline or evil but, im just hanging on
anyway >> LISTEN REAL QUICK BRO <<---------------------------\/
this stuff going on is like all i have keeping me here

>>> I've done this digging and digging for over a month now, just to help
others. Please help it mean something


SCROLL TO BOTTOM FOR MAIN QUESTION IF YOU DO NOT CARE TO HEAR MY CHATTER ;)
but i could use a friendly person from the internet right now. I know that
the good will come back around <<<





i cant seem to get much done well on this tablet,... I got her hooked up
with keyboard and mouse now at least thank god


i bet you would know though right off the bat...

>>> take a look at this tree of files. <<<< default pretty much..

look normal?
I wanna be able to use the network for the first time in months, so i can
fix my chicks laptop and get done seeing her face after being abused for 4
years..

im too shy to even make a post rn bro
just point me in the right direction.

If i want to make sure there is nothing left wouldnt qubes be the os to
help me do it, when kaspersky, win pe, windows, and everything else i try,
(kubuntu, and a bunch of other av tools and rootkits tools) fail?


look at this if you want. or tell me its inappropriate..
i just cannot find anyone who will look at any of this stuff and i keep
loosing a lot of it with shit getting write protected and stuff

my phone had so much.. from day one ... jan 9th
in windows..
when the bitlocker folder appeared and then dissapeared.

or maybe you can tell me what would be helpful
maybe what place to start at..>>> beeping computer is not even a good
answer anymore lol <<<

!!!!!   >>>>>>>>       i want someone whos interested in whack ass awesome
creations like this., it climbs around like a monkey  doesnt care what
device or how it sends data, even if it kills a phone battery and sends 5
gigs the rest of my data, in like a couple minutes tops , to send whatever
its compressed on  a pc, with no bluetooth adapter ... its almost magic. (i
thikn it was the mouse fob that time)

do you know someone who would be interested in a remote session or two
trying out this windows laptop behind me and a few OSs? cant ask that
publicly.. <<<<<<<<<<<    !!!!

Can you point me in the right direction?   .... just answer me first then i
can email you the tree if you even reply. i try not to overwhelm... i need
someone i can directly talk to. possibly on mic even or phone, and let them
see everything i can recover + what i can do in front of me..

This has apppeared new from day one and i still dont see much

i mean maybe solarwinds or satalite hacking .. little bit of print spooler
action and callstranger on the router, that i got rid of when i got here...
but my mom works for LORD
they dont even seem to notice and she wont listent to me and tell them,,,
but i saw it on her work computer .. in the swiss cheeese of a windows
update 1903 i think


please man, forward this, talk to me do something
 help me be a part of the initiative
  if i could meet the creator i would love to


you should see this README i found in kasper
even just someone able to tell me that shit is NOT original lol

it had hints and clues in it that i guarantee anyone would enjoy
most names leading onky to githubs.
one government paper from berkly 1978

**Comment by genericxero** [comment]
i understand though.. i figured. worth a try.. so hard to even make that it
took hours on this thing lol.. i was so frustrated. my bad.

do read that other email please.. it is urgently needing something and not
so much for the sake of my rig or anything

i came here to serve humanity and this is the first time ive felt a calling
in years
you're a forum mod so i  know you like to help humanity too...

**Comment by andrewdavidwong** [comment]
I'm afraid we have to insist that you take your questions to the forum or qube-users mailing list (again, see [here](https://www.qubes-os.org/support/) for details).
