### ISSUE TITLE
Split GPG freezing Thunderbird

### ISSUE THREAD

**Issue by oija12** [QubesOS/qubes-issues#6462]
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
Thunderbird and qubes-split-gpg

**Brief summary**
On my laptop as well as that of 2 colleagues, Thunderbird freezes several times per day. This happens at a critical time when we hit send or when we open an encrypted email - in both cases Thunderbird is fetching the key from the vault-gpg. To fix the problem, we have to either kill Thunderbird and restart it, or shutdown vault-gpg and restart it. This is happening for work VM that is based on either Debian or in Fedora, and the vault-gpg VM is based on Fedora.

**How Reproducible**
It's happening several times per day, once every 20 or so use.

**To Reproduce**
1. Launch Thunderbird and allow access to vault-gpg
2. Click to open encrypted email, or create a new encrypted email and click "send"
3. Thunderbird freezes (a percentage of the time)

**Expected behavior**
I expect that the email decrypts or that the encrypted email sends

**Actual behavior**
Thunderbird freezes. Does not response to clicking. Folders and emails are not "clickable".

**Additional context**
This happened on 3 Thinkpad laptops, each a different model.

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
None

**Comment by DemiMarie** [comment]
I suspect that Thunderbird assumes that cryptography is synchronous, whereas signing with an external program is inherently asynchronous.

**Comment by DemiMarie** [comment]
There appear to be two problems here:

1. Thunderbird blocks the GUI event loop during signing.  This is a bug in Thunderbird; signing can be a slow process even outside of Qubes OS (such as if the key is on a smart card).
2. qubes-gpg-client hangs forever in certain conditions.  This is a bug in Qubes OS.

**Comment by DemiMarie** [comment]
The Qubes OS portion was fixed by <https://github.com/QubesOS/qubes-app-linux-split-gpg/commit/54a010e3e28d9d2152c81e82fdb4cdd3791efebb>.  The Thunderbird portion is a bug in Thunderbird and is not specific to Qubes OS.  Closing as “not our bug”.
