### ISSUE TITLE
xen-acpi-processor isn't auto loading

### ISSUE THREAD

**Issue by dylangerdaly** [QubesOS/qubes-issues#6465]
**Qubes OS version**
R4.1

**Affected component(s) or functionality**
Xen's ACPI cpufreq driver

**Brief summary**
xen-acpi-processor fails to auto load, resulting in `xenpm` not working.

**To Reproduce**

1. Run `xenpm get-cpufreq-states` on an AMD system

**Expected behavior**
xen-acpi-processor auto load

**Actual behavior**
User is required to run `modprobe xen-acpi-processor`

**Screenshots**
N/A

**Additional context**
N/A

**Solutions you've tried**
N/A

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
N/A

**Comment by jandryuk** [comment]
I looked at this a little last night.  xen-acpi-processor would be loaded by the loadmodules systemd unit, but that unit isn't run- the unit is vendor disabled.  I guess an addition to /lib/systemd/system-preset/ would fix that.

Maybe systemd is new enough now (at least for 4.1) that https://github.com/QubesOS/qubes-vmm-xen/commit/893fefac99467f4612b5879b737ed2a5ee1cda57 can just be reverted?

**Comment by iamahuman** [comment]
I suppose `/etc/sysconfig/modules/cpufreq-xen.modules` either fails or does not get invoked at all?

**Comment by jandryuk** [comment]
Nothing runs `/etc/sysconfig/modules/cpufreq-xen.modules`.  `loadmodules` systemd unit would run it, but the unit is vendor disabled and does not run.

I'm not familiar with the cpufreq-xen module in cpufreq-xen.modules.  The file is quite old, so it may just be a legacy module that no longer exists.

**Comment by marmarek** [comment]
@fepitre I think you worked on this, but I can't find where, is there any PR for this?
