### ISSUE TITLE
qubes-dom0-update not finding packages in dom0 on R4.1

### ISSUE THREAD

**Issue by dmoerner** [QubesOS/qubes-issues#6466]
**Qubes OS version**

R4.1

**Affected component(s) or functionality**

qubes-core-dom0-linux-4.1.9-1.fc32.x86_64. Both dom0 and fc32 updateVM are fully updated as of Mar 17.

**Brief summary**

`qubes-dom0-update` doesn't install anything.

** Steps to Reproduce**

If I run `qubes-dom0-update SDL`, or some other package not installed in dom0, it opens an UpdateVM xterm showing the file downloading, but then in dom0 it says:

```
No match for argument: **SDL**
Error: Unable to find a match: SDL
```

If I run `qubes-dom0-update --enablerepo=qubes-dom0-current-testing`, which I did to make sure I wasn't missing a more recent version of some component, I see packages downloaded in the updateVM xterm. (In this case, only qubes-manager). But I only get this output in dom0:

```
Using sys-firewall as UpdateVM to download updates from Dom0; this may take some time...
Last metadata expiration date: -1 day, 20:27:45 ago on Wed Mar 2021 07:58:25 PM EDT.
```

This made me think maybe I have a clock problem, but dom0 clock is correct.

**Expected behavior**

The package SDL should be installed in dom0. The packages from current-testing should be installed in dom0.

**Solutions you've tried**

Passing the `--console` flag to `qubes-dom0-update` doesn't make a difference.

**Comment by 0rb677** [comment]
What if `sudo dnf update` ?

**Comment by 0rb677** [comment]
I have another bug - when update process is starting , it calls sh script and triggered `xterm` from `sys-firewall` and update mechanism going from `dom0` to `sys-firewall`

**Comment by DemiMarie** [comment]
> I have another bug - when update process is starting , it calls sh script and triggered new window of `xterm` from `sys-firewall` and update mechanism going from `dom0` to `sys-firewall`

That’s deliberate; it allows the user to see the download progress without untrusted text needing to be displayed in a dom0 terminal.  However, it can be disabled.

**Comment by dmoerner** [comment]
Not reproducible after reboot, closing.
