### ISSUE TITLE
Cannot detach usb device persistently added to dom0

### ISSUE THREAD

**Issue by S-G-iscoding** [QubesOS/qubes-issues#6469]
**Qubes OS version**

R4.0

**Affected component(s) or functionality**

qvm-usb
dom0
sys-usb

**Brief summary**

If I attach a usb device persistently to dom0 via command line, I cannot detach it.

**How Reproducible**

**To Reproduce**

1. Install Qubes OS with usb qube.
2. List usb devices using `qvm-usb` in dom0
3. Attach a usb device to dom0 typing `qvm-usb attach --persistent dom0 <device identifier>`
4. Try to use the usb device with `lsusb` or `lsblk`: It isn't found in dom0.
5. Try to detach the usb device: `qvm-usb detach dom0 <device identifier>`
6. You will see the error message `Can not remove a persistent attachment from a non halted vm`
7. Halt dom0 with `sudo shutdown now`
8. The whole system is shutting down, as expected. No chance to detach the usb device. 
9. Reboot.
10. Try to fix it with shutting down and removing the sys-usb qube using the Qube Manager.
11. Shutting down is working, deleting the sys-usb qube is not possible and you will see the error message `VM has devices attached persistently to other VM: 3-2`

**Expected behavior**

It is possible to detach the usb device without any problems.

**Actual behavior**

You cannot detach the usb device without getting error messages that you have to halt dom0 (see "To Reproduce").

**Screenshots**

**Additional context**

**Solutions you've tried**

 - halt dom0
 - delete usb qube
(see "To Reproduce")

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

https://www.qubes-os.org/doc/usb-devices/

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

https://github.com/QubesOS/qubes-issues/issues/6057
https://github.com/QubesOS/qubes-issues/issues/6054
https://github.com/QubesOS/qubes-issues/issues/5736
https://github.com/QubesOS/qubes-issues/issues/5713

**Comment by dyercode** [comment]
Is there seriously no workaround for this? I took some bad advice from a forum post (i don't even remember where) and now my options are install from scratch or buy a new audio interface?

**Comment by DemiMarie** [comment]
This can be fixed by manually editing `qubes.xml`, but that is not a good idea unless one knows what they are doing.  @marmarek any better way to fix this?

**Comment by marmarek** [comment]
I'm afraid not... So, yes, the current fix is to:
1. Stop `qubesd` service: `systemctl stop qubesd`
2. Edit `/var/lib/qubes/qubes.xml` (find dom0 and remove the device from its "devices" section)
3. Start `qubesd` service.
