### ISSUE TITLE
Resign all GPG keys with SHA-256 or better

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#6470]
**Brief summary**

Several of the QubesOS developers GPG keys are signed with SHA-1.  SHA-1 is considered weak and should be replaced by SHA-256 or better.  This will require resigning the keys.

**Additional context**

This is a defense in depth task.  Since we assume that the GPG keys were honestly generated, finding a different key with the same SHA-1 hash would require a preimage attack, which is not considered feasible.

**Comment by andrewdavidwong** [comment]
Signed by whom? I'm guessing you mean by the Qubes Master Signing Key or the self-signature or both.

Related:
 - https://github.com/QubesOS/qubes-issues/issues/1116
 - https://github.com/QubesOS/qubes-issues/issues/2535
 - https://github.com/QubesOS/qubes-issues/issues/2818
 - https://github.com/QubesOS/qubes-issues/issues/4378
 - Discussion beginning around [here](https://groups.google.com/g/qubes-devel/c/XreFo6RM47Q/m/7ETu-WU6BgAJ)

I generally agree that replacing SHA-1 with SHA-256 where feasible would be a nice short-term improvement, and hence worth doing. However, as you can see from these related issues and the discussion, there are larger systemic concerns regarding the QMSK that should be addressed in the medium to long term, and addressing those concerns would naturally entailing using more modern primitives.

**Comment by DemiMarie** [comment]
> Signed by whom? I'm guessing you mean by the Qubes Master Signing Key or the key itself (self-signature) or both.

Both

> Related:
> 
> * #1116
> * #2535
> * #2818
> * #4378
> * Discussion beginning around [here](https://groups.google.com/g/qubes-devel/c/XreFo6RM47Q/m/7ETu-WU6BgAJ)
> 
> I generally agree that replacing SHA-1 with SHA-256 or SHA-512 where feasible would be a nice short-term improvement and hence worth doing. However, as you can see from these related issues and the discussion, there are larger systemic concerns regarding the QMSK that should be addressed in the medium to long term, and addressing those concerns would naturally entailing using more modern primitives.

Indeed

**Comment by DemiMarie** [comment]
The Release 4 signing key is still signed with SHA-1 by the QMSK.

**Comment by andrewdavidwong** [comment]
> The Release 4 signing key is still signed with SHA-1 by the QMSK.

This has been tripping up a lot of users, as evidenced by the forum posts I've been seeing about it. Increasing priority.

CC: @marmarek

**Comment by HW42** [comment]
all: FWIW: The [secpack](https://github.com/QubesOS/qubes-secpack) already contains updated keys since a while.
@marmarek: https://keys.qubes-os.org/ needs to be updated.

**Comment by DemiMarie** [comment]
> all: FWIW: The [secpack](https://github.com/QubesOS/qubes-secpack) already contains updated keys since a while. @marmarek: https://keys.qubes-os.org/ needs to be updated.

As do the various Fedora and Debian packages.

**Comment by HW42** [comment]
@DemiMarie:
> As do the various Fedora and Debian packages.

This one is easy:
QubesOS/qubes-core-agent-linux#361
QubesOS/qubes-core-agent-linux#360
QubesOS/qubes-core-agent-linux#359

**Comment by marmarek** [comment]
> @marmarek: https://keys.qubes-os.org/ needs to be updated.

updated

**Comment by andrewdavidwong** [comment]
Can this be closed, or are there still keys that need to be updated?

**Comment by marmarek** [comment]
I think all is done already.
