### ISSUE TITLE
Temperature bug

### ISSUE THREAD

**Issue by gitman23** [QubesOS/qubes-issues#6472]
Qubes 4.0, Lenovo X270

Sometimes my CPU temperature goes to 90 C  although the qubes OS has not much to do. If shutting down the responsible domain the temperature goes down again. The same if I pause the domain. After a while I found out that it only happens if not the first firefox browser tab is activated. In other words, if I make sure that always the first firefox tab is activated (and not the 2nd, 3rd ....)before switching to another domain then I don't run into temperature issues, but if I forget the machine is getting pretty hot. I tried it dozens of times in the meantime and always the same. Anyone having similar issues or is this a known bahavior or bug?

**Comment by andrewdavidwong** [comment]
Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this does not appear to be suitable for `qubes-issues`. We ask that you please post this on the [`qubes-users` mailing list or forum](https://www.qubes-os.org/support/) instead. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a brief comment explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.
