### ISSUE TITLE
BIOS updated now Qubes no longer boots in.

### ISSUE THREAD

**Issue by 2tbwXj46BDbdNBRV79DS** [QubesOS/qubes-issues#6478]
### Qubes OS version:

R4.0

### Affected component(s) or functionality:

boot

---

### Steps to reproduce the behavior:

encrypted qubes install on my M.2 ssd. used qubes fine for years then i update my bios

### Expected or desired behavior:

Boot in to qubes after updating bios.

### Actual behavior:

```
Reboot and Select proper Boot device
or Insert Boot Media in selected Boot device and press a key_
```

### General notes:

ived tried CSM support enabled/disabled, storage legacy/UEFI.(installed with legacy)

ive also tried clone zilla on to and SATA SSD nothing came of that.

Im not sure which bios verson i updated from. i know it was a couple years old and thought it would be a good idea to do the upgrade. would getting the previous older BIOS version installed help?

I have tried Troubleshooting with qubes usb installer, selecting disk, putting in password, but it does not see my qubes install.

this is a Intel x299 pc if this helps at all.

---

### I have consulted the following relevant [documentation](https://www.qubes-os.org/doc/):

https://www.qubes-os.org/doc/uefi-troubleshooting/ was installed with legacy so nothing helped here

**Comment by 0spinboson** [comment]
Sorry to hear you're having issues, but I would suggest asking for troubleshooting help either qubes-os.discourse.group/ or https://groups.google.com/forum/#!forum/qubes-users :)

**Comment by andrewdavidwong** [comment]
Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this does not appear to be suitable for `qubes-issues`. We ask that you please post this on the [`qubes-users` mailing list or forum](https://www.qubes-os.org/support/) instead. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a brief comment explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.
