### ISSUE TITLE
System Sleeps On Unlock

### ISSUE THREAD

**Issue by clucode** [QubesOS/qubes-issues#6479]
### Qubes OS version:
Qubes R4.0

### Affected component(s) or functionality:
Sleep/Hibernate Function

---

### Steps to reproduce the behavior:
Close laptop lid, Open laptop lid, Sign into user account, Wait 10-20 seconds. System then automatically hibernates. Issue persists until full reboot is preformed.

### Expected or desired behavior:
System should sleep/hibernate on lid close but not randomly during usage.

### Actual behavior:
System automatically hibernates 10-20 seconds after wake and login. Issue persists until full reboot is preformed.

### General notes:
Qubes is installed on a Razer 17 Pro Product No: RZ09-02202E75 With an Intel AX210, 1TB NvME, and 64GB RAM added after-market.
Running Kernel 5.11.4-1.fc25 on sys-net because of issue 5615

---

### I have consulted the following relevant [documentation](https://www.qubes-os.org/doc/):
https://www.qubes-os.org/hcl/#hardware-laptops
https://www.qubes-os.org/doc/suspend-resume-troubleshooting/
https://github.com/QubesOS/qubes-issues/issues/5615 

### I am aware of the following related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues:

Edit: I've tried disabling xscreensaver as recomended here: https://github.com/QubesOS/qubes-issues/issues/3727 and am currently scrubbing through a journalctl dump.

**Comment by Clu-less** [comment]
After running qubes-updater manually and rebooting, I am unable to recreate the error. I'll close this for now.

**Comment by Clu-less** [comment]
After some digging, I found the lid close dialogue and trimmed everything before it. But there's still 1081 lines of code that I'm not skilled enough to effectively analyze. I'm going to keep at it though!
 
[lid_close-journalctl.txt](https://github.com/QubesOS/qubes-issues/files/6194684/lid_close-journalctl.txt)

**Comment by iamahuman** [comment]
Can you check whether "sleep after n seconds" (and the like) is enabled in one of the following places?

1. XFCE Power Settings
2. XScreenSaver preferences
3. `/etc/systemd/logind.conf`
4. `/etc/systemd/logind.conf.d/*.conf` (if they exist)

**Comment by Clu-less** [comment]
Thanks for the reply! I just checked:

1. Everything is set to "never" in Power Manager.
2. XScreenSaver has all values set to max and is disabled.
3. No "Sleep" argument in the file.
4. Doesn't exist :(

Do you need me to include any other system logs?

**Comment by iamahuman** [comment]
Perhaps snoop D-Bus messages sent to logind? The command might be `sudo dbus-monitor --system "destination='org.freedesktop.login1'"` but I don't exactly recall which.

**Comment by Clu-less** [comment]
I ran the first command and triggered the sleep loop but forgot to run `script` in advance. 
T_T
Queue mad scramble to save the terminal output to a file mid-sleep loop. 

> Also please be sure to censor any sensitive information--the only thing we're probably going to need is the sender.

I ran a quick scan, and didn't see anything that jumped out at me as sensitive. But I may just be stupid, so... Hopefully i'm not stupid?
Anyways, Terminal dump attached.
[dbusLidMonitorDump1.txt](https://github.com/QubesOS/qubes-issues/files/6202569/dbusLidMonitorDump1.txt)

**Comment by Clu-less** [comment]
Sorry for the delay, Here are the results from the other two command variations:

`sudo dbus-monitor  --system path='/org/freedesktop/login1'`:  
[dbusLidMonitorDump2.txt](https://github.com/QubesOS/qubes-issues/files/6209374/dbusLidMonitorDump2.txt)

`sudo dbus-monitor --system interface='org.freedesktop.login1.Manager'`:  
[dbusLidMonitorDump3.txt](https://github.com/QubesOS/qubes-issues/files/6209383/dbusLidMonitorDump3.txt)

**Comment by Clu-less** [comment]
@iamahuman Is there anything else I should be doing?

**Comment by iamahuman** [comment]
Your logs show that VM monitor layout update is indeed happening. However, there seems to be the time window where the DisplayPort is briefly disconnected.

As to how to fix the issue, perhaps throttleing/coalescing monitor layout update might help.

**Comment by iamahuman** [comment]
I don't think so, as I'm not sure how to make forward progress in this issue at the moment.

As a workaround, you can do `systemd-inhibit --what handle-lid-switch:sleep --mode block sleep 30m` to keep the laptop on for 30 minutes for example.

**Comment by Clu-less** [comment]
Thanks for the tip, i'll keep experimenting!

**Comment by andrewdavidwong** [comment]
Is this still a problem in 4.1?

**Comment by pehhhhhh** [comment]
Could this potentially be a razer issue? I’ve recently installed Qubes on my Razer blade laptop and I’m experiencing the exact same issue.

**Comment by pehhhhhh** [comment]
> Is this still a problem in 4.1?

Yes, I installed the latest qubes release as of 03/09 and I’m experiencing the same issue on a razer blade laptop.

**Comment by andrewdavidwong** [comment]
Closing this for now as it appears that the issue no longer affects any Qubes users. If anyone believes this is a mistake, or if anyone is still affected by this issue, please leave a comment, and we'll be happy to reopen this. Thank you.
