### ISSUE TITLE
failed to build Ubuntu bionic

### ISSUE THREAD

**Issue by pczmr8v5n454iycf** [QubesOS/qubes-issues#6481]
**Qubes OS version**
4.1

**Affected component(s) or functionality**
Building ubuntu Template on a fedora-32 vm

**Brief summary**

```
rm -f /home/user/qubes-builder/chroot-vm-bionic//home/user/qubes-src/vmm-xen/debian-vm/version
cp "/home/user/qubes-builder/chroot-vm-bionic//home/user/qubes-src/vmm-xen/xen-4.14.1.tar.gz" "/home/user/qubes-builder/chroot-vm-bionic//home/user/qubes-src/vmm-xen/xen_4.14.1.orig.tar.gz"
-> Building vmm-xen (debian-vm/debian) for bionic vm (logfile: build-logs/vmm-xen-vm-bionic.log)
--> build failed!
make[2]: Entering directory '/home/user/qubes-src/vmm-xen/debian-vm'
/usr/bin/make -C xen install
make[3]: Entering directory '/home/user/qubes-src/vmm-xen/debian-vm/xen'
/usr/bin/make -f Rules.mk _install
dnsdomainname: No address associated with hostname
make[4]: Entering directory '/home/user/qubes-src/vmm-xen/debian-vm/xen'
/usr/bin/make -C tools
make[5]: Entering directory '/home/user/qubes-src/vmm-xen/debian-vm/xen/tools'
/usr/bin/make symbols
make[6]: Entering directory '/home/user/qubes-src/vmm-xen/debian-vm/xen/tools'
gcc -Wall -Werror -Wstrict-prototypes -O2 -fomit-frame-pointer -fno-strict-aliasing -Wdeclaration-after-statement -o symbols symbols.c
make[6]: Leaving directory '/home/user/qubes-src/vmm-xen/debian-vm/xen/tools'
make[5]: Leaving directory '/home/user/qubes-src/vmm-xen/debian-vm/xen/tools'
/usr/bin/make -f /home/user/qubes-src/vmm-xen/debian-vm/xen/Rules.mk include/xen/compile.h
make[5]: Entering directory '/home/user/qubes-src/vmm-xen/debian-vm/xen'
make[5]: Leaving directory '/home/user/qubes-src/vmm-xen/debian-vm/xen'
[ -e include/asm ] || ln -sf asm-x86 include/asm
[ -e arch/x86/efi ] && for f in boot.c runtime.c compat.c efi.h;\
	do test -r arch/x86/efi/$f || \
	   ln -nsf ../../../common/efi/$f arch/x86/efi/; \
	done; \
	true
/usr/bin/make -f /home/user/qubes-src/vmm-xen/debian-vm/xen/Rules.mk -C include
make[5]: Entering directory '/home/user/qubes-src/vmm-xen/debian-vm/xen/include'
mkdir -p compat
grep -v 'DEFINE_XEN_GUEST_HANDLE(long)' public/argo.h | \
/usr/bin/python3 /home/user/qubes-src/vmm-xen/debian-vm/xen/tools/compat-build-source.py >compat/argo.c.new
mv -f compat/argo.c.new compat/argo.c
gcc -E -m64 -DBUILD_ID -fno-strict-aliasing -std=gnu99 -Wall -Wstrict-prototypes -Wdeclaration-after-statement -Wno-unused-but-set-variable -Wno-unused-local-typedefs -O2 -fomit-frame-pointer -nostdinc -fno-builtin -fno-common -Werror -Wredundant-decls -Wno-pointer-arith -Wvla -pipe -D__XEN__ -ffile-prefix-map=/home/user/qubes-src/vmm-xen/debian-vm=. -mindirect-branch=thunk-extern -mindirect-branch-register -fno-jump-tables -I/home/user/qubes-src/vmm-xen/debian-vm/xen/include -I/home/user/qubes-src/vmm-xen/debian-vm/xen/include/asm-x86/mach-generic -I/home/user/qubes-src/vmm-xen/debian-vm/xen/include/asm-x86/mach-default -DXEN_IMG_OFFSET=0x200000 -msoft-float -fno-stack-protector -fno-exceptions -fno-asynchronous-unwind-tables -Wnested-externs -DHAVE_AS_NEGATIVE_TRUE -mno-red-zone -fpic -mno-sse -mskip-rax-setup -include public/xen-compat.h -DXEN_GENERATING_COMPAT_HEADERS -m32 -o compat/argo.i compat/argo.c
gcc: error: unrecognized command line option '-ffile-prefix-map=/home/user/qubes-src/vmm-xen/debian-vm=.'
Makefile:68: recipe for target 'compat/argo.i' failed
make[5]: *** [compat/argo.i] Error 1
rm compat/argo.c
make[5]: Leaving directory '/home/user/qubes-src/vmm-xen/debian-vm/xen/include'
Makefile:358: recipe for target '/home/user/qubes-src/vmm-xen/debian-vm/xen/xen' failed
make[4]: *** [/home/user/qubes-src/vmm-xen/debian-vm/xen/xen] Error 2
make[4]: Leaving directory '/home/user/qubes-src/vmm-xen/debian-vm/xen'
Makefile:263: recipe for target 'install' failed
make[3]: *** [install] Error 2
make[3]: Leaving directory '/home/user/qubes-src/vmm-xen/debian-vm/xen'
Makefile:130: recipe for target 'install-xen' failed
make[2]: *** [install-xen] Error 2
make[2]: Leaving directory '/home/user/qubes-src/vmm-xen/debian-vm'
debian/rules:196: recipe for target 'override_dh_auto_build' failed
make[1]: *** [override_dh_auto_build] Error 2
make[1]: Leaving directory '/home/user/qubes-src/vmm-xen/debian-vm'
debian/rules:140: recipe for target 'build' failed
make: *** [build] Error 2
dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2
make[2]: *** [/home/user/qubes-builder/qubes-src/builder-debian//Makefile-legacy.debian:56: dist-package] Error 2
make[1]: *** [Makefile.generic:191: packages] Error 1
make: *** [Makefile:254: vmm-xen-vm] Error 1
```

**Expected behavior**

Build successfully

**Actual behavior**

```
gcc: error: unrecognized command line option '-ffile-prefix-map=/home/user/qubes-src/vmm-xen/debian-vm=.'
```

**Solutions you've tried**

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

**Comment by marmarek** [comment]
It seems `-ffile-prefix-map` was introduced in GCC 8, Ubuntu Bionic (18.04LTS) uses GCC 7.4. @unman if you want to support bionic build, you can make the patch using it conditional.

**Comment by unman** [comment]
On Wed, Mar 24, 2021 at 05:03:13AM -0700, Marek Marczykowski-G??recki wrote:
> It seems `-ffile-prefix-map` was introduced in GCC 8, Ubuntu Bionic (18.04LTS) uses GCC 7.4. @unman if you want to support bionic build, you can make the patch using it conditional.
> 

I'm minded to support only 1 LTS, to be honest, and drop bionic.
Similarly for Debian, does any one use oldstable in Qubes? We just don't
know these things.

**Comment by genechuah** [comment]
Hi! Any word on how to solve this issue? Need to get my `ubuntu-bionic` template built but this error is blocking things.

**Comment by DemiMarie** [comment]
I am tempted to close this as “won’t fix” as @unman suggested.  @marmarek is this okay?

**Comment by unman** [comment]
On Fri, Dec 10, 2021 at 12:50:54AM -0800, Demi Marie Obenour wrote:
> I am tempted to close this as ???won???t fix??? as @unman suggested.  @marmarek is this okay?
> 
Give me a day and I'll post the PR for this. We might as well keep
bionic running until jammy in 2204.

**Comment by genechuah** [comment]
> On Fri, Dec 10, 2021 at 12:50:54AM -0800, Demi Marie Obenour wrote: I am tempted to close this as ???won???t fix??? as @unman suggested. @marmarek is this okay?
> Give me a day and I'll post the PR for this. We might as well keep bionic running until jammy in 2204.

Much appreciated, kind sir!

**Comment by genechuah** [comment]
Hello! Not to pester, but any luck with this?

**Comment by unman** [comment]
On Sun, Dec 26, 2021 at 12:56:43PM -0800, Gene Chuah wrote:
> Hello! Not to pester, but any luck with this?
> 

It is, of course, more complicated than thought.
Template is buildable, qubes start and are functional (qvm-copy/move etc
etc) but no GUI output. :-(

**Comment by genechuah** [comment]
Appreciate your efforts with it!

**Comment by ddevz** [comment]
> On Wed, Mar 24, 2021 at 05:03:13AM -0700, Marek Marczykowski-G??recki wrote: It seems `-ffile-prefix-map` was introduced in GCC 8, Ubuntu Bionic (18.04LTS) uses GCC 7.4. @unman if you want to support bionic build, you can make the patch using it conditional.
> I'm minded to support only 1 LTS, to be honest, and drop bionic. Similarly for Debian, does any one use oldstable in Qubes? We just don't know these things.

when typing ./setup after following the qubes-builder instructions, for ubuntu it only gives options to build xenial and bionic templates.  

But from the way you say that, does qubes-builder support either focal or jammy (I.E. are they just missing from the dialog "GUI"?)

To actually answer (or at least give you one data point for) the question you asked, I just installed jessie in a VM because I needed a old version of a software package for compatibility reasons.   However while maintaining legacy versions of one distribution could be useful, maintaining legacy versions of every distribution seems unnecessary to me.

Random thought:  If the build process is breaking, but the template itself would still work, maybe distribute it as a new "qubes-community-legacy-templates" channel of unmaintained templates.

Maybe even mention the version (hash) of qubes-builder, and the version of the installed tools in the VM that were used for the final build?

If it's still in LTS, they should still be able to type "apt-get upgrade" till the end of upstream support (or until Qubes 4.2 breaks compatibility)

**Comment by unman** [comment]
qubes-builder setup script supports focal - I dont know why you suggest it does
not.
I haven't included jammy yet because the build is still broken.

I'd be reluctant to distribute unmaintained templates at all.
