### ISSUE TITLE
Unable to boot HVMs on HPZ800 with X5570 Quad Core 2.93Ghz

### ISSUE THREAD

**Issue by Lophiel** [QubesOS/qubes-issues#6482]
**Qubes OS version**
Qubes release 4.0 (R4.0)

**Affected component(s) or functionality**
None of the HVM qubes are able to start-up  

**To Reproduce**

1.  Terminal
2.  run `xl dmesg`
3. add `iommu=no-intremap` to terminal 
4. reboot
5. start an hvm (dosen't boot)

**Expected behavior**
The expected behavior should have been the HVM's or VM's shoud have booted normally 

**Actual behavior**
The actual behavior that occurred was that my HVM qube fails to start saying that my hardware does not support IOMMU/VT-d/AMD-Vi despite being enabled in my bios. 

**General Notes**

Qubes is installed on a HPZ800 with X5570 Quad Core 2.93Ghz 32GB ram  2tb drive. Upon doing some additional research it seems [Xenserver](https://github.com/xenserver/xen.pg/blob/XS-8.2.x/master/tweak-iommu-policy.patch#L38-L52) has a patch for this issue which should be integrated into qubes but hasn't.

**Comment by Zophike1** [comment]
If anything is not clear in the report I can add additional comments or screenshots

**Comment by marmarek** [comment]
I believe you linked to a wrong place - it isn't a xenserver patch (although it is related).

**Comment by Zophike1** [comment]
@marmarek my bad I'm new to Xen so I'm not up to speed with all the relevant documentation care to point me in the right direction ? Also I spoke to one of the mountaineers regarding the issue and he said in order for the bug to be fixed is going to take some negations.

**Comment by marmarek** [comment]
You linked to https://www.suse.com/support/kb/doc/?id=000018235 which isn't xenserver patch.

**Comment by andyhhp** [comment]
The hardware in question is Nehalem era, with chipset errata concerning interrupt remapping.

The simple fix is https://github.com/xenserver/xen.pg/blob/XS-8.2.x/master/tweak-iommu-policy.patch#L38-L52

If disabling intremap by default isn't ideal, then the next best option is to only call tylersburg_intremap_quirk() if iommu_intremap is enabled.  This allows people to opt into a slightly less secure system, but not fully insecure, by booting with `iommu=no-intremap`

**Comment by Zophike1** [comment]
For my purpose disabling intremap  is fine I could also just have another *Nix with KVM+Virgil to play games :)
