### ISSUE TITLE
Design next major version of qubes-builder

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#6486]
This is a ticket for track things we would like to see in the next major version of qubes-builder. Actual implementation should be tracked in separate issues, linked to this one.

- [x] isolate component builds from the actual qubes-builder environment - preferably using DisposableVMs (currently we have it for template builds only)
- [x] isolate iso build (same as the above)
- [x] simplify configuration and usage - reduce entry barrier
- [x] more rely on existing and maintained tools (this is especially about "legacy" builds which currently prepare chroot for builds more or less using custom scripts) - consider docker/podman? (side note: "legacy" builds are mostly useful for development builds, as the build environment setup is _much_ faster - it doesn't require installing build deps each time)
- [x] clearer separate source (and dependencies) download from the actual build - allow more reliable logging of build inputs and environment, but also allow extra sanitization of inputs (things like checking their reproducibility proofs or plugging in [rpmcanon](https://github.com/QubesOS/RPM-Oxide/blob/main/rpm-writer/bin/rpmcanon.rs))
- [x] allow semi-trusted maintainers of only specific components, without giving practical unlimited control over other components as a side effect (see https://github.com/QubesOS/qubes-builder/pull/123#issuecomment-697010703 for more details)
- [ ] improve updates handling - painful limitations of the current qubes-builder:
    - no support for un-pushing an update (whether current-testing or current repo)
    - cannot move not the most recent update from current-testing to current

**Comment by andrewdavidwong** [comment]
Now that we have [projects](https://github.com/QubesOS/qubes-issues/projects), I've turned this into one, per our guideline that [every issue must be about a single, actionable thing](https://www.qubes-os.org/doc/reporting-bugs/#every-issue-must-be-about-a-single-actionable-thing):

https://github.com/QubesOS/qubes-issues/projects/11

**Comment by fepitre** [comment]
@andrewdavidwong @marmarek where are we supposed to discuss to the general ideas for the new design?

**Comment by andrewdavidwong** [comment]
> @andrewdavidwong @marmarek where are we supposed to discuss to the general ideas for the new design?

The issue tracker is not the place for discussing general ideas. That should take place on the mailing lists and/or forum before an issue is created. Once the discussion yields a specific actionable proposal, create an issue for it. That way, comments on the issue can be more usefully focused on specific implementation details.

**Comment by marmarek** [comment]
I don't want to use this issue for _discussing_ the design, but as a place for coordination and reference for this design process. Things like referring to "requirement number 3" in the discussion. And also a place to put the final design when done (at which point the task is complete, the issue can be closed, and actual implementation can be tracked separately).

I don't thing github project is a good fit for this, as those points are not really separate actionable tasks, but rather a set of a requirements for a single task. We could use some separate document for that (wiki? cryptpad? gist?) but I thought using an issue would help keep things organized in one place. @andrewdavidwong do you have some alternative proposal?

**Comment by andrewdavidwong** [comment]
> I don't want to use this issue for _discussing_ the design, but as a place for coordination and reference for this design process. Things like referring to "requirement number 3" in the discussion. And also a place to put the final design when done (at which point the task is complete, the issue can be closed, and actual implementation can be tracked separately).
> 
> I don't thing github project is a good fit for this, as those points are not really separate actionable tasks, but rather a set of a requirements for a single task. We could use some separate document for that (wiki? cryptpad? gist?) but I thought using an issue would help keep things organized in one place. @andrewdavidwong do you have some alternative proposal?

Ah, now that I understand what you have in mind, I think it's fine to use an issue for this. There are a few different things that can sometimes seem similar:

 1. **A "bucket" for holding several issues.** Sometimes people try to create a "meta-issue" for this, but it's better just to use a "project."
 2. **A discussion area or collaborative scratchpad.** People also try to use issues for this, but a mailing list, forum, or actual shared document are better suited.
 3. **A to-do item for creating an intangible deliverable, such as a design.** An issue is appropriate for this, because it is actionable, focused on one thing, and has clearly-defined end conditions. This may not be obvious at first, because usually the deliverable is code, not something intangible like a design, but a design is just as legitimate of a deliverable. It sounds like this is what you have in mind.

The way the issue description is phrased made me think you only wanted (1), but it sounds like you actually want (3), which is fine by me.

**Comment by ydirson** [comment]
Maybe we could add a items for documentation, both for using it as a user just willing to modify/build existing packages (which the current version has some of, though incomplete), and for using it as an integrator of new packages (which AFAIK is not documented for the current version).

**Comment by marmarek** [comment]
builderv2 already exists, and most of the above points are covered.
