### ISSUE TITLE
Duplicated content on Qubes XSA tracker page

### ISSUE THREAD

**Issue by mfc** [QubesOS/qubes-issues#6489]
**Affected component(s) or functionality**
https://github.com/QubesOS/qubes-doc/blob/master/project-security/xsa.md

https://www.qubes-os.org/security/xsa/ has duplicated Statistics and Tracker sections.

**Comment by marmarek** [comment]
https://github.com/QubesOS/qubes-doc/pull/1123 already fixes it.
