### ISSUE TITLE
Qt or GTK? - need for clear direction on GUI framework 

### ISSUE THREAD

**Issue by deeplow** [QubesOS/qubes-issues#6490]
**The problem you're addressing (if any)**

I'm opening this issue as I see contradicting information regarding the graphical user interface (GUI) framework to be used for future Qubes development.

The documentation [states](https://www.qubes-os.org/doc/usability-ux/#gnome-kde-and-xfce) (last edited 4 years ago -- emphasis mine):
>We are currently migrating towards using GNOME. We know some people prefer KDE, but we believe Gnome is easier to use for average non-technical users. Xfce will always be supported, and technical users will always have the choice to use KDE or other desktop environments.
> 
> **This change means you should use GTK rather than Qt for new GUIs.**

Currently only some Qubes components use GTK and there seems to be no sign of that changing much as the redesign of [Qubes Manager](https://github.com/QubesOS/qubes-issues/issues/5679#issuecomment-722677216)) and the [App Menu](https://github.com/QubesOS/qubes-issues/issues/5677#issuecomment-614903863) will possibly be implemented in Qt.

**Describe the solution you'd like**

With the above said, I'd like there to be a clearer messaging as to what GUI framework Qubes contributors should be using. If both are equally acceptable, then the docs should mention this.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

* https://www.qubes-os.org/doc/usability-ux/#gnome-kde-and-xfce
* [[qubes-devel] Preferred framework for graphical stuff?](https://www.mail-archive.com/qubes-devel@googlegroups.com/msg00744.html) (Nov 2016 discussion)

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

* none

**Comment by marmarek** [comment]
>  [App Menu](https://github.com/QubesOS/qubes-issues/issues/5677#issuecomment-614903863) will possibly be implemented in Qt.

I would treat use of term "GTK" or "QT" in that ticket is just a synonym for "some toolkit", not a specific choice, really. When we'll have a final UX design there, we'll choose appropriate toolkit (considering both the desired UI, but also consistency and integration with other DE elements) and I'm pretty sure it will be GTK.

Similarly for Qubes Manager - if/when it will get a redesign (perhaps a project for 2022?), it is likely it will get migrated to GTK (although I can't commit to this right now).

So, I think nothing have changed, it's just miscommunication in #5677.
