### ISSUE TITLE
Batch Convert to Trusted Image dialog boxes steal focus, preventing typing in other windows

### ISSUE THREAD

**Issue by afk11** [QubesOS/qubes-issues#6496]
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
Convert to Trusted IMG

**Brief summary**

I selected multiple images, right clicked and did Convert to Trusted IMG. When I switched back to firefox to type, the 'Progress' dialog with 'Converting image using disposable VM' pops up as I'm typing, and if I hit space, it cancels the operation for that image. 

I can't use qubes while it's doing this.

The VM with the files, and the VM with firefox, are the same FYI

**How Reproducible**

It's reproducible if you have a batch of images to process, because it takes place over minutes

**To Reproduce**

1. Copy some pictures into a directory
2. Ctrl A
3. Right click and select Convert to trusted IMG
4. Now try and respond to an email

**Expected behavior**

You should be able to type our email without the dialog box stealing focus and you cancelling operations unexpectedly

**Actual behavior**

The dialog boxes open, steals focus, and nothing happens until you hit space, which cancels the operation.

**Screenshots**

**Additional context**

**Solutions you've tried**

Go make a coffee. I wrote this issue during the experience and cancelled some more images.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

**Comment by afk11** [comment]
huh, I need to look into this some more, maybe it restarted the operation? Really hard to tell what happened

**Comment by afk11** [comment]
I think it might have restarted it for the images I cancelled because I saw what looked like an equal number of trusted, and "untrusted" images after. There was so many I gave up and skipped this part.

**Comment by Ark-of-the-copepod** [comment]
I'd like to second this issue. 

-select multiple images
-left click -> convert to trusted image
-a succession of dialog boxes pop-up, stealing focus from whatever else you are working on, no matter what qube or workspace.

In addition, the flurry of system notices about the disp-vms (e.g. "disp1234 is starting up...) is bloody annoying. Could they be suppressed in future? Make the whole process truly background.
