### ISSUE TITLE
python2-lxml required by archlinux qubes-vm-xen no longer exists in [extra] repository

### ISSUE THREAD

**Issue by ejose19** [QubesOS/qubes-issues#6502]
**Qubes OS version**

R4.0

**Affected component(s) or functionality**

Building archlinux packages

**Brief summary**

The package `python2-lxml` (https://archlinux.org/packages/extra/x86_64/python2-lxml/) was removed from the `[extra]` repository on 2021-03-17, which is needed to build `qubes-vm-xen`

**How Reproducible**

100%

**To Reproduce**

1. run `make qubes-vm`
2. notice the error about python2-lxml

**Expected behavior**

Build should continue without errors

**Actual behavior**

Missing package makes build to fail

**Screenshots**

**Additional context**

**Solutions you've tried**

A workaround is using `https://archive.archlinux.org/repos/2021/03/16` as `Server`, which makes the build to finish, however a better solution is preferred in order to use updated packages on build as well as decent speeds.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

**Comment by DemiMarie** [comment]
I ran into this bug myself.  Patch coming.

**Comment by raysongrey** [comment]
> **Qubes OS version**
> 
> R4.0
> 
> **Affected component(s) or functionality**
> 
> Building archlinux packages
> 
> **Brief summary**
> 
> The package `python2-lxml` (https://archlinux.org/packages/extra/x86_64/python2-lxml/) was removed from the `[extra]` repository on 2021-03-17, which is needed to build `qubes-vm-xen`
> 
> **How Reproducible**
> 
> 100%
> 
> **To Reproduce**
> 
> Steps to reproduce the behavior:
> 
>     1. run `make qubes-vm`
> 
>     2. notice the error about python2-lxml
> 
> 
> **Expected behavior**
> 
> Build should continue without errors
> 
> **Actual behavior**
> 
> Missing package makes build to fail
> 
> **Screenshots**
> 
> **Additional context**
> 
> **Solutions you've tried**
> 
> A workaround is using `https://archive.archlinux.org/repos/2021/03/16` as `Server`, which makes the build to finish, however a better solution is preferred in order to use updated packages on build as well as decent speeds.
> 
> **Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
> 
> **Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

How do we update the server to complete the build?

**Comment by ejose19** [comment]
@raysongrey use `export ARCHLINUX_MIRROR=https://archive.archlinux.org/repos/2021/03/16` before running 
`make qubes-vm`. 

If you previously ran the command, you will need to clear cached entries with:
 `sudo rm -rf -- qubes-builder/{cache,chroot-vm-archlinux}`

**Comment by ziQ** [comment]
@ejose19 thanks for the advice. Those archives are a handy thing to know about.

Your workaround doesn't appear to work anymore, though. These error messages appear in a loop:
```
(...)
==> Creating install root at /mnt
==> Installing packages to /mnt
:: Synchronizing package databases...
error: failed to update core (no servers configured for repository)
error: failed to update extra (no servers configured for repository)
error: failed to update community (no servers configured for repository)
error: failed to synchronize all databases
```

`^C` doesn't work to kill it, but `^Z` got it readable.

There's also this commit which replaces the `python2` references with `python` and removes `export PYTHON=/usr/bin/python` lines: https://github.com/QubesOS/qubes-vmm-xen/commit/f0a5537640ecfa393f5ee7852a96d6fcd367315d

Not sure how all this is tied together. The repo I cloned during archlinux build is `QubesOS/qubes-builder.git`, but that repo doesn't contain the `archlinux/PKGBUILD`. That seems to be part of https://github.com/QubesOS/qubes-vmm-xen/blob/xen-4.14/archlinux/PKGBUILD instead.

So what I'll try next is: replace all contents of my local `~/qubes-builder/qubes-src/vmm-xen/archlinux/PKGBUILD` and replace it with the contents of the file above (which appears to have been patched to replace python2 with python3).

**Comment by ejose19** [comment]
@ziQ yes, you're right. I'm using a modified `builder-archlinux` based on this PR https://github.com/QubesOS/qubes-builder-archlinux/pull/55, so the solution I provided won't work unless you apply the patch manually first.

On qubes 4.1 there shouldn't be any errors as its based on python3 already.

**Comment by ziQ** [comment]
Read through your PR and compared to my `Makefile.archlinux`. Then stumbled over the var called `PACMAN_MIRROR` instead of `ARCHLINUX_MIRROR`. Went through the file's change history. It was changed in December: https://github.com/QubesOS/qubes-builder-archlinux/commit/bdae7679811ce43437a509ee4e46b9169e3c13a0#diff-3cda552a15044717a6fbb9709af54b18a27314f255722b342d127bf3b34f3c31

Not sure how (and where in the code) the [QubesOS/qubes-builder-archlinux](https://github.com/QubesOS/qubes-builder-archlinux) repo gets pulled into [QubesOS/qubes-builder](https://github.com/QubesOS/qubes-builder)

Anyways, I've changed `PACMAN_MIRROR` from rackspace to `https://archive.archlinux.org/repos/2021/03/16` within `Makefile.archlinux` and will see how that goes.

**Comment by ctrlaltf24** [comment]
> I ran into this bug myself. Patch coming.

Any progress on the patch?

**Comment by DemiMarie** [comment]
> > I ran into this bug myself. Patch coming.
> 
> Any progress on the patch?

Sorry, I got distracted on other stuff.  I will go ahead and do it now.

**Comment by ctrlaltf24** [comment]
> > > I ran into this bug myself. Patch coming.
> > 
> > 
> > Any progress on the patch?
> 
> Sorry, I got distracted on other stuff. I will go ahead and do it now.

Sweet thanks, but the issue was building archlinux under R4.0 not R4.1
```
:: Running post-transaction hooks...
(1/1) Arming ConditionNeedsUpdate...
--> Archlinux dist-package (makefile)
  --> Building package in /home/user/qubes-src/vmm-xen
sudo BACKEND_VMM=xen  chroot "/mnt/qubes-builder/chroot-vm-archlinux" su user -c 'cd "/home/user/qubes-src/vmm-xen" && cp archlinux/PKGBUILD* ./ && env http_proxy="" SOURCE_DATE_EPOCH=1613656693 makepkg --syncdeps --noconfirm --skipinteg'
==> Making package: qubes-vm-xen 4.8.5-30 (Wed Apr 21 21:24:15 2021)
==> Checking runtime dependencies...
==> Installing missing dependencies...
error: target not found: python2-lxml
==> ERROR: 'pacman' failed to install missing dependencies.
==> Missing dependencies:
  -> python2
  -> bridge-utils
  -> python2-lxml
  -> lzo
==> Checking buildtime dependencies...
==> ERROR: Could not resolve all dependencies.
make[2]: *** [/mnt/qubes-builder/qubes-src/builder-archlinux/Makefile.archlinux:138: dist-package] Error 8
```

**Comment by unman** [comment]
The dependency has been removed.
https://github.com/QubesOS/qubes-vmm-xen/commit/2237b59
The issue can be closed - @andrewdavidwong  @ejose19
