### ISSUE TITLE
Repurpose "Template Manager" app name

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#6504]
**The problem you're addressing (if any)**

With the actual template manager (app to install/remove/update templates) coming to R4.1 (https://github.com/QubesOS/qubes-manager/pull/258), it makes sense for have it under "Template Manager" name. On the other hand, the old functionality of template manager (mass template switching) is integrated into qube manager now (https://github.com/QubesOS/qubes-manager/pull/273).

**Describe the solution you'd like**

- remove old template manager (or rename to something like template-manager-legacy)
- rename qvm-template-gui to qubes-template-manager
- add info where to look for the old template manager functionality (how to do it in qube manager)
- add a button to launch template manager from qube manager

**Where is the value to a user, and who might that user be?**

Long overdue GUI for template installation, without overwhelming the user with increased number of tools.
It may be misleading for users upgrading from Qubes 4.0 at first, but I believe the gains are worth it.

**Describe alternatives you've considered**

Keep both template managers in menu.

**Additional context**

https://github.com/orgs/QubesOS/projects/1

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

**Comment by GWeck** [comment]
Why not provide a link, for example an icon or button, from the new template manager to the old one, additionally? If a user call the new manager meaning the old one, it would give a simple way to perform the intended action.

**Comment by marmarek** [comment]
> Why not provide a link, for example an icon or button, from the new template manager to the old one, additionally? If a user call the new manager meaning the old one, it would give a simple way to perform the intended action.

Yup, good idea.

**Comment by marmarek** [comment]
Screenshots of the new template manager: https://github.com/QubesOS/qubes-manager/pull/258#issuecomment-682999263

@ninavizz this will definitely need some more love on the UX side (although not right now, lets finish the menu first). But I think we should really go ahead with the template manager GUI even in its current state, as this is long overdue missing GUI part. Doing it the way I proposed here will introduce some non-insignificant UX churn. Do you have some advice what to do _now_?

**Comment by ninavizz** [comment]
On the surface, this honestly just seems like a standard "major feature maturation." Like, I was sincerely confused around why the `4.0.4` Template Manager is an app separate from Qubes Manager, and yet the new one looks like a legitimate stand-alone app. I'll make my nitty UX comments on it, in its issue—but as far as naming is concerned, I think its fine. Just be sure to put up high in the Release Notes, it as a topic and then the first line as "All new functionality" (or something to that effect).
