### ISSUE TITLE
qvm.sys-net-with-usb no longer exists

### ISSUE THREAD

**Issue by ArtificialAmateur** [QubesOS/qubes-issues#6507]
**Qubes OS version**
Qubes release 4.0 (R4.0)

**Affected component(s) or functionality**
- qubesctl (salt-stack)
- sys-net
- sys-usb

**Brief summary**
[qvm.sys-net-with-usb](https://github.com/QubesOS/qubes-mgmt-salt-dom0-virtual-machines/commit/8b219ee528ae052c209db70ed92c543a71cc75a6) state no longer exists, removed and replaced with [pillar sys-net-as-usbvm](https://github.com/QubesOS/qubes-mgmt-salt-dom0-virtual-machines/commit/c21c87215c08ba25a9b2c560cc8e7c99dd26edc4). Documentation has not been updated [1](https://www.qubes-os.org/doc/salt/#qvmsys-net-with-usb) & [2](https://www.qubes-os.org/doc/installation-guide/).

No existing documentation on how to use sys-net for usb devices for relying "on a USB device for network access, such as a USB modem or a USB Wi-Fi adapter". 

**To Reproduce**

1. Install Qubes 4.0
2. Remove sys-usb
3. Attempt to create conjoined sys-net/sys-usb.

**Additional context**
I'd like sys-net to be the default VM with USB devices and not dom0, in order to properly use my USB WiFi adapter.

**Solutions you've tried**
1. Create sys-usb through `qubesctl`
2. Start NetworkManager
3. Open network connection.
4. (Works but is not persistent).

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
https://www.qubes-os.org/doc/salt/#qvmsys-net-with-usb
https://www.qubes-os.org/doc/installation-guide/

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
#2860

**Comment by marmarek** [comment]
It should be:
```
qubesctl top.enable qvm.sys-net-with-usb pillar=True
```
and then
```
qubesctl state.sls qvm.sys-usb
```

**Comment by andrewdavidwong** [comment]
Now that https://github.com/QubesOS/qubes-doc/pull/1239 has been merged, is there anything left to do for this issue?

**Comment by marmarek** [comment]
Yes, apparently there is an include missing so the second command on its own does not work...

**Comment by NieDzejkob** [comment]
Also, it seems that it wasn't only a change of name, but also from state to pillar.

**Comment by NieDzejkob** [comment]
Once the commands in https://github.com/QubesOS/qubes-issues/issues/6507#issuecomment-1067135102 are fixed, it'd be good to add them to the documentation somewhere.
