### ISSUE TITLE
fedora-33 AppVM can't resolve hostname in local network that fedora-32 AppVM can

### ISSUE THREAD

**Issue by yourcase** [QubesOS/qubes-issues#6511]
**Qubes OS version**
4.0

**Affected component(s) or functionality**
fedora-33 network host resolution

**Brief summary**
A newly created fedora-33 AppVM won't resolve hostnames on my local network, where as a newly created fedora-32 AppVM will.

**How Reproducible**
Always

**To Reproduce**

1. Create two AppVMs: `testdns32` and `testdns33` with templates `fedora-32` and `fedora-33` respectively, and connecting to the same `sys-firewall`.
2. Start one terminal in each of those AppVMs.
3. In `testdns32`, I can successfully ping a host on the local network called `server02`:
```
[user@testdns32 ~]$ cat /etc/redhat-release 
Fedora release 32 (Thirty Two)
[user@testdns32 ~]$ ifconfig
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.137.0.63  netmask 255.255.255.255  broadcast 10.255.255.255
        inet6 fe80::216:3eff:fe5e:6c00  prefixlen 64  scopeid 0x20<link>
        ether 00:16:3e:5e:6c:00  txqueuelen 1000  (Ethernet)
        RX packets 21  bytes 3154 (3.0 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 22  bytes 2195 (2.1 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 4  bytes 224 (224.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 4  bytes 224 (224.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

[user@testdns32 ~]$ cat /etc/resolv.conf 
nameserver 10.139.1.1
nameserver 10.139.1.2
[user@testdns32 ~]$ ping server02
PING server02 (192.168.21.117) 56(84) bytes of data.
64 bytes from server02 (192.168.21.117): icmp_seq=1 ttl=62 time=2.31 ms
64 bytes from server02 (192.168.21.117): icmp_seq=2 ttl=62 time=1.83 ms
^C
--- server02 ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1002ms
rtt min/avg/max/mdev = 1.831/2.071/2.311/0.240 ms
[user@testdns32 ~]$ 
```
4. In `testdns33` I can't:
```
[user@testdns33 ~]$ cat /etc/redhat-release 
Fedora release 33 (Thirty Three)
[user@testdns33 ~]$ ifconfig
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.137.0.20  netmask 255.255.255.255  broadcast 10.255.255.255
        inet6 fe80::216:3eff:fe5e:6c00  prefixlen 64  scopeid 0x20<link>
        ether 00:16:3e:5e:6c:00  txqueuelen 1000  (Ethernet)
        RX packets 15  bytes 2672 (2.6 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 31  bytes 2323 (2.2 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 4  bytes 224 (224.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 4  bytes 224 (224.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

[user@testdns33 ~]$ cat /etc/resolv.conf 
nameserver 10.139.1.1
nameserver 10.139.1.2
[user@testdns33 ~]$ ping server02
ping: server02: Name or service not known
```
**Expected behavior**
I expected the same behaviour from fedora-33 as from fedora-32 templates.

**Actual behavior**
fedora-33 behaves differently, and more particularly in an undesired way, since I can't reach local hosts without workarounds.

**Additional context**
1. A bare-metal fedora-33 on another PC does not have this problem, so this seems to be specific to the fedora-33 qubes template.
2. Even though as demonstrated above, ping doesn't know what host to ping, nslookup does find `server02` from `testdns33`:
```
[user@testdns33 ~]$ nslookup
> server02
Server:		10.139.1.1
Address:	10.139.1.1#53

Name:	server02
Address: 192.168.21.117
> ^C[user@testdns33 ~]$ 
```
3. The actual nameserver that provides the IP address for `server02` is a dd-wrt router.
4. External addresses are correctly resolved on `testdns33`:
```
[user@testdns33 ~]$ ping www.qubes-os.org
PING qubesos.github.io (185.199.110.153) 56(84) bytes of data.
64 bytes from cdn-185-199-110-153.github.com (185.199.110.153): icmp_seq=1 ttl=54 time=10.9 ms
64 bytes from cdn-185-199-110-153.github.com (185.199.110.153): icmp_seq=2 ttl=54 time=12.3 ms
^C
--- qubesos.github.io ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1002ms
rtt min/avg/max/mdev = 10.862/11.601/12.340/0.739 ms
```
5. For the duration of this demo, I was running `sys-net` and `sys-firewall` under `fedora-32`.

**Solutions you've tried**
As a workaround, I can add a line from `/etc/resolv.conf` on `sys-net` to `/etc/resolv.conf` on `testdns33`, and then it will work:
```
[user@testdns33 ~]$ cat /etc/resolv.conf
search mynetname.local
nameserver 10.139.1.1
nameserver 10.139.1.2
[user@testdns33 ~]$ ping server02
PING server02.mynetname.local (192.168.21.117) 56(84) bytes of data.
64 bytes from server02 (192.168.21.117): icmp_seq=1 ttl=62 time=1.96 ms
64 bytes from server02 (192.168.21.117): icmp_seq=2 ttl=62 time=6.77 ms
64 bytes from server02 (192.168.21.117): icmp_seq=3 ttl=62 time=2.55 ms
^C
--- server02.mynetname.local ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2003ms
rtt min/avg/max/mdev = 1.960/3.759/6.765/2.139 ms
```
One might therefore be tempted to think that AppVMs should have the same content in `resolv.conf` as `sys-net`, but that doesn't seen to be the case, since the `testdns32` AppVM has the exact same content for `/etc/resolv.conf` as `testdns33`.

Also note that without the extra line in `resolv.conf`, but pinging the long hostname doesn't help:
```
[user@testdns33 ~]$ cat /etc/resolv.conf
nameserver 10.139.1.1
nameserver 10.139.1.2
[user@testdns33 ~]$ ping server02.mynetname.local
ping: server02.mynetname.local: Name or service not known
```
**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
None

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

**Comment by marmarek** [comment]
This is related to intended Fedora 33 change: https://fedoraproject.org/wiki/Changes/systemd-resolved
There has been a lot of controversy around this change, some references are summarized here: https://www.phoronix.com/scan.php?page=news_item&px=F33-systemd-resolved-Sticks
We have included this info also in fedora 33 template announcement: https://www.qubes-os.org/news/2021/02/25/fedora-33-templates-available/

As a workaround, until upstream proposes some better option, you can either:
- disable systemd-resolved
- configure it to resolve single-word domains: create `/etc/systemd/resolved.conf.d/30_user.conf` in your template with:
```
[Resolve]
ResolveUnicastSingleLabel=true
LLMNR=false
```

**Comment by yourcase** [comment]
The configuration worked, Thanks!
