### ISSUE TITLE
i3 system tray position issue in multimonitor setup 

### ISSUE THREAD

**Issue by ultrablasta** [QubesOS/qubes-issues#6512]
**Qubes OS version**

`R4.0`

**Affected component(s) or functionality**

System tray may end up on an undesired monitor. 

**Brief summary**

While using i3 in a multimonitor setup, system tray seems to stick to a certain monitor and stay there. No matter what settings are set in xrandr/arandr - it seems to pick a monitor based on the graphics card slots and assigns it from there rather than anything within xrandr.

**Expected behavior**

System tray should really appear on the monitor that is selected as the primary monitor using arandr/xrandr. 

**Actual behavior**

System tray chooses monitor based on gpu slot.

**Solutions you've tried**

Software fixes I've tried with arandr include moving monitor positions around and changing the primary monitor.

The only solution I know of at the moment is making sure that the monitor that system tray should be on is connected to the right port on the gpu even if that means it requires some kind of conversion cable. Currently to fix this I bought a DVI to HDMI cable just to get system tray on the monitor I wanted.

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

#2242 is not directly related, but it shows how i3 needs some improvements to get system tray to function properly within qubes

**Comment by dmoerner** [comment]
I'm not sure if your Expected Behavior is the correct expected behavior, at least for i3. One way to do this in i3 is to specify `tray_output none` in the bars for other monitors in `~/.config/i3/config`. This is pretty brittle, but I'm not sure if i3 supports a better way. You might be interested in looking at this issue: https://github.com/i3/i3/issues/1855

**Comment by ultrablasta** [comment]
@dmoerner thanks for linking the i3 issue. Seems like setting `tray_output primary` in the bar section in the i3 config fixed the issue for me
