### ISSUE TITLE
Expired Certs / New Install

### ISSUE THREAD

**Issue by f0xy** [QubesOS/qubes-issues#6513]
**Qubes OS version: Release 4.0 (R4.0)**

**Affected component(s) or functionality**
qubes-dom0-update / new install Qubes-R4.0.4-x86_64.iso

**Brief summary**

Errors during downloading metadata for repository 'qubes-dom0-current':
  - Curl error (60): SSL peer certificate or SSH remote key was not OK for https://yum.qubes-os.org/r4.0/current/dom0/fc25/repodata/repomd.xml.metalink [SSL certificate problem: certificate is not yet valid]
Error: Failed to download metadata for repo 'qubes-dom0-current': Cannot prepare internal mirrorlist: Curl error (60): SSL peer certificate or SSH remote key was not OK for https://yum.qubes-os.org/r4.0/current/dom0/fc25/repodata/repomd.xml.metalink [SSL certificate problem: certificate is not yet valid]
Qubes Templates repository                      0.0  B/s |   0  B     00:01    
Errors during downloading metadata for repository 'qubes-templates-itl':
  - Curl error (60): SSL peer certificate or SSH remote key was not OK for https://yum.qubes-os.org/r4.0/templates-itl/repodata/repomd.xml.metalink [SSL certificate problem: certificate is not yet valid]

**How Reproducible**
New Install / qubes-dom0-update

**To Reproduce**

1. sudo qubes-dom0-update

**Expected behavior**
Error Message

**Solutions you've tried**
set sslverify = 0 in dom0 in /etc/yum.repos.d for each enabled repo in dom0.repo and qubes-templates.repo for new installs on Qubes-R4.0.4-x86_64.iso. After qubes-dom0-update remove sslverify = 0 for each enabled item and is self sustainable afterwords.

**Comment by DemiMarie** [comment]
“Certificate is not yet valid” almost always means that your system clock is slow.

**Comment by f0xy** [comment]
Remember runing qvm-sync-clock its possible I didn't wait long enough. Thanks DemiMarie

**Comment by DemiMarie** [comment]
You’re welcome!  Perhaps this should be documented.
