### ISSUE TITLE
qubesctl: error: argument --standalones: not allowed with argument --templates

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#6514]
**Qubes OS version**

`R4.0`

**Affected component(s) or functionality**

qubesctl

**Brief summary**

The arguments --standalones and --templates cannot be used at the same time.

**How Reproducible**

100%

**To Reproduce**

```
$ sudo qubesctl --skip-dom0 --templates --standalones state.sls update.qubes-vm
```

**Expected behavior**

The two arguments can be used at the same time.

**Actual behavior**

```
$ sudo qubesctl --skip-dom0 --templates --standalones state.sls update.qubes-vm
usage: qubesctl [-h] [--show-output] [--force-color] [--skip-dom0]
                [--max-concurrency MAX_CONCURRENCY]
                [--targets TARGETS | --templates | --standalones | --app | --all]
                ...
qubesctl: error: argument --standalones: not allowed with argument --templates 
```

**Additional context**

We explicitly tell users to run this command in [QSB-067](https://github.com/QubesOS/qubes-secpack/blob/master/QSBs/qsb-067-2021.txt).

**Solutions you've tried**

N/A

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

https://www.qubes-os.org/doc/salt/

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

**Comment by unman** [comment]
On Tue, Apr 06, 2021 at 01:11:04AM -0700, Andrew David Wong wrote:
> 
> 
> **Qubes OS version**
> 
> 
> `R4.0`
> 
> **Affected component(s) or functionality**
> 
> 
> qubesctl
> 
> **Brief summary**
> 
> 
> The arguments --standalones and --templates cannot be used at the same time.
> 
> **How Reproducible**
> 
> 
> 100%
> 
> **To Reproduce**
> 
> ```
> $ sudo qubesctl --skip-dom0 --templates --standalones state.sls update.qubes-vm
> ```
> 
> **Expected behavior**
> 
> 
> The two arguments can be used at the same time.
> 
> **Actual behavior**
> 
> 
> ```
> $ sudo qubesctl --skip-dom0 --templates --standalones state.sls update.qubes-vm
> usage: qubesctl [-h] [--show-output] [--force-color] [--skip-dom0]
>                 [--max-concurrency MAX_CONCURRENCY]
>                 [--targets TARGETS | --templates | --standalones | --app | --all]
>                 ...
> qubesctl: error: argument --standalones: not allowed with argument --templates 
> ```
> 
> **Additional context**
> 
> 
> We explicitly tell users to run this command in [QSB-067](https://github.com/QubesOS/qubes-secpack/blob/master/QSBs/qsb-067-2021.txt).
> 
> **Solutions you've tried**
> 
> 
> N/A
> 
> **Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
> 
> 
> https://www.qubes-os.org/doc/salt/
> 
> **Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
> 
> 

That help message ( and the code - where the targets form a mutually
exclusive group) tells you that those options are alternatives.
So this isnt a bug.

You may perhaps want to change it to a feature request.

**Comment by andrewdavidwong** [comment]
> That help message ( and the code - where the targets form a mutually exclusive group) tells you that those options are alternatives. So this isnt a bug. You may perhaps want to change it to a feature request.

Even though the code may be written so as to make the options mutually exclusive, @marmarek has told me multiple times to use both arguments together (one of which was in QSB-067), so this seems like unintended behavior, which would make it a bug. (Even if the code itself is perfect, if it does the wrong thing, that can still be a bug.)

**Comment by unman** [comment]
On Tue, Apr 06, 2021 at 11:50:13PM -0700, Andrew David Wong wrote:
> > That help message ( and the code - where the targets form a mutually exclusive group) tells you that those options are alternatives. So this isnt a bug. You may perhaps want to change it to a feature request.
> 
> Even though the code may be written so as to make the options mutually exclusive, @marmarek has told me multiple times to use both arguments together (one of which was in QSB-067), so this seems like unintended behavior, which would make it a bug. (Even if the code itself is perfect, if it does the wrong thing, that can still be a bug.)
> 

Interesting - I have never tried mixing target specifications like this,
because I dont salt in a way that would call for it.
@marmarek should we extend this to allow for mix and matching between
targets, maybe including individual specifications?

**Comment by marmarek** [comment]
Yes, the actual target selection already handles multiple target types (see https://github.com/QubesOS/qubes-mgmt-salt/blob/release4.0/qubesctl#L58-L74), it's just the argument parser refusing it...

**Comment by unman** [comment]
On Wed, Apr 07, 2021 at 06:08:43AM -0700, Marek Marczykowski-G??recki wrote:
> Yes, the actual target selection already handles multiple target types (see https://github.com/QubesOS/qubes-mgmt-salt/blob/release4.0/qubesctl#L58-L74), it's just the argument parser refusing it...
> 

So the only effort will be changing parser and deduping targets

**Comment by fepitre** [comment]
We need to be careful here.  If I remember correctly, the original modification was made for https://github.com/QubesOS/qubes-dist-upgrade/blob/master/qubes-dist-upgrade.sh#L486.
