### ISSUE TITLE
VM Suddenly Stopped Working. It starts but no reaction.

### ISSUE THREAD

**Issue by NewQuber** [QubesOS/qubes-issues#6516]
Hi, so I encountered a problem with my Qubes StandaloneVM Debian-10.

I used this qubes for a while now but suddenly, one day to another, it just doesn't work anymore. 

So it starts but when I try to open an app, terminal or whatsoever there is just no reaction. I also can't updated the qube.

I'm not a programmer and have barely a clue of anything. Is there a solution for this problem?

**Comment by andrewdavidwong** [comment]
Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this does not appear to be suitable for `qubes-issues`. We ask that you please post this on the [`qubes-users` mailing list or forum](https://www.qubes-os.org/support/) instead. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a brief comment explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.
