### ISSUE TITLE
Display all available wallpapers to user by merging wallpaper folders

### ISSUE THREAD

**Issue by mfc** [QubesOS/qubes-issues#6521]
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
wallpapers / https://github.com/QubesOS/qubes-artwork

**Brief summary**

When the user visits the Settings > Desktop > Background, there is a list of default shipped wallpaper options for the user. those displayed are from `/usr/share/backgrounds/images`. however there are also wallpapers in `/usr/share/backgrounds/qubes` that are not currently displayed.

i don't think was always the case but potentially some regression. issue was first raised on [Reddit](https://www.reddit.com/r/Qubes/comments/mp1ljz/i_found_wallpapers_inside_dom0_read_my_comment/) ("they don't show up on the Desktop Settings app") and i can confirm.

**To Reproduce**

1. visit Settings > Desktop > Background in XFCE
2. see available wallpapers. they do not include wallpapers in `qubes` folder
3. not able to select "Folder: Other" and select `qubes` (permissions issue?)

**Expected behavior**
All shipped wallpapers are presented and available to user in Settings > Desktop > Background

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
none. 
different issue: https://github.com/QubesOS/qubes-issues/issues/215
https://github.com/rootkovska/qubes-wallpapers

**Comment by EncryptedGiraffe** [comment]
Oh interesting, I never realized there was more than one folder with backgrounds. On my build of 4.1, I can select either folder, `images` is obviously the initial one. But I can switch to `qubes` and use the wallpapers from there (and I am because they look so nice). It would be nice if all wallpapers were in the same place/shown all together to the user though.

**Comment by mfc** [comment]
thanks for checking in R4.1! and i agree they should all be presented to the user in the same folder. 

@andrewdavidwong i think this should be done for both R4.0 and R4.1.

**Comment by lubellier** [comment]
@mfc : 

> not able to select "Folder: Other" and select qubes (permissions issue?)

This isn't a Qubes OS issue, but a XFCE issue, see [this topic](https://forum.xfce.org/viewtopic.php?pid=45688#p45688) on the xfce forum. I found other user reports (Ubuntu, ArchLinux; all near 2016/2017). See also the [xfce issue 12832](https://bugzilla.xfce.org/show_bug.cgi?id=12832) and the [associated commit](https://git.xfce.org/xfce/xfdesktop/commit?id=157f5b55cfc3629d595ef38984278de5915aac27). 

Note that you can select a **gray folder**, then click on the *Open* button, **it works** (yes it's not intuitive....). 

So two directions:

1. for 4.0 only, update the xfdesktop package if a newer version is available for Fedora-25, with the above commit. 
2. for 4.0 and 4.1, see with @marmarta and/or @fepitre if it is or it isn't a good idea to merge the two background folders (`/usr/share/backgrounds/images` and `/usr/share/backgrounds/qubes`).

**Comment by mfc** [comment]
give low priority and R4.1 now stable, i think we skip #1, and for #2 would be good to hear thoughts on merging background folders. there are no UI indications for a user to expect more wallpapers in other folders besides the default wallpaper folder.

**Comment by marmarta** [comment]
I think merging folders is a good idea. I'm almost certain they are split like this by mistake or oversight.
