### ISSUE TITLE
AEM on usb device: Sometimes "Failed to seal secrets (error @ line 231)!"

### ISSUE THREAD

**Issue by S-G-iscoding** [QubesOS/qubes-issues#6524]
**Qubes OS version**

**Affected component(s) or functionality**

Anti Evil Maid
anti-evil-maid-seal

**Brief summary**

Using AEM with 2FA and SRK password and a not write protected sd card in an usb sd card reader, sometimes the message

```
[...]
Sealed [...]secret.fre using --pcr 13 [...]
Syncing to /mnt/anti-evil-maid/aemsd
Failed to seal secrets (error @ line 231)!
Press <ENTER> to continue...
```
is shown.

**How Reproducible**

Not always reproducible. Sometimes it works, sometimes not.
I've tested it by just booting the laptop again and again and if it fails, I continue rebooting for resealing the secrets.

**To Reproduce**

1. Enable usb qube but allow dom0 to access the usb controller by removing the `rd.qubes.hide_all_usb` line in the /etc/default/grub file. 
2. Install AEM with 2FA and with srk password on the sd card using the internal sd card reader. 
3. Put the sd card into a usb reader to make it bootable.
3. Reboot several times using the usb device as boot device.

**Expected behavior**

The sealing is always working and not just sometimes.

**Actual behavior**

The following error message is shown at the boot screen:

```
[...]
Sealed [...]secret.fre using --pcr 13 [...]
Syncing to /mnt/anti-evil-maid/aemsd
Failed to seal secrets (error @ line 231)!
Press <ENTER> to continue...
```

**Screenshots**

**Additional context**

**Solutions you've tried**

Rebooting ;-)
Looking into the logs using `journalctl -u anti-evil-maid-unseal -u anti-evil-maid-seal`. In the logs, after entering SRK password, the error `rm: cannot remove '/mnt/anti-evil-maid/aemsd/tpms/[file]': Read-only file system` occures several times with different [files].

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

https://github.com/QubesOS/qubes-antievilmaid

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

**Comment by rustybird** [comment]
If you search through the full `journalctl` logs (not limited to the AEM units), there's a good chance the kernel printed the reason why the device was mounted read-only. It should be somewhere just before the AEM errors.
