### ISSUE TITLE
Improve User-Facing Communication

### ISSUE THREAD

**Issue by ninavizz** [QubesOS/qubes-issues#6527]
**The problem you're addressing (if any)**
QubesOS began as a developer/security-community project, and has gained amazing traction over the past ~9yrs. As censorship and targeting of activists around the globe has intensified in recent years, more and more non-FOSS and non-technical users have sought to adopt it. Yay! 

For users _not_ desiring investment in "a user community" via email lists and forums, and who would like to track a project only interested in how that project's product might serve them as a user, a product's website and Twitter are the standard media folks expect to look to for such communications. The expectations of content in those communications is also a far lower-bar of technically-detailed content, and simpler "What can I get and when" messaging.

**Describe the solution you'd like**
NOT razzle-dazzle marketing. We all agree that stinks. For starters, I think creating some new article topics for the website, a "Newsletter" (akin to how ProtonMail does it—up-front qualify how often we'd send it, like 4x a year, and then stick to that), and some strategies for "consumer" modeled communications, would be helpful. Maybe a Substack; which could be a great fundraising device, too? Likewise, a need to establish some writing styles for "consumer" vs "contributor" vs "IT manager" targeted content. There aren't a whole lot of models among the FOSS universe for projects that do this well, so this also feels like a great opportunity to really push ourselves to do more things unique and different. [Content Strategy](https://www.usability.gov/what-and-why/content-strategy.html) (but w/o the Capitalistic overtones), FTW!

**Where is the value to a user, and who might that user be?**
Helping bridge the gap between ultra-nerdy and ultra-Capitalistic product outreach models for users to choose from, such that we can include more folks into the pool of prospective and new users and reduce user attrition. Reciprocity and community participation are not desirable for many users. To grow the userbase of Qubes, we need to be more inclusive of those folks.

**Describe alternatives you've considered**
Forums and email lists for discussion... which are great for folks who've chosen to invest and to give-back to a community project, but not for folks who simply wish to adopt a technology once it requires less of their mental bandwidth. Forums and email lists imply reciprocity; one-way models are more desirable to just "keep up to date" or to keep an eye on when something might be right for a needy user to adopt as a product they can depend on.

**Comment by andrewdavidwong** [comment]
Can you provide some specific, concrete suggestions for how to make this actionable? Right now, this has a lot of nice-sounding but vague buzzwords that convey a positive vibe. It's the sort of post that's easy to upvote but difficult to implement. What are some real examples of our current communication, where exactly do they fall short, and what would make them better?

**Comment by andrewdavidwong** [comment]
Closing as not meeting our [issue tracker guidelines](https://www.qubes-os.org/doc/reporting-bugs/#issue-tracker-guidelines). If anyone has *specific, actionable* suggestions for how we can improve user-facing communications, we'll be happy to hear them.
