### ISSUE TITLE
qubes.InputKeyboard policy risk

### ISSUE THREAD

**Issue by MxMarl** [QubesOS/qubes-issues#6532]
qubes.InputKeyboard:
The agent asks if you agree that the keyboard can be used when reaching the session. This is ok. But in my case I use a dock (Thinkpad Dock)and I have to give about 10 'ok' each time. All 'Operation: qubes.InputKeyboard'. But now it would be useful to know which device exactly wants to be connected. For example by the ID or something like that to identify the device. I see a security risk there. An attacker could connect a bad-device, and the user just presses 'ok' 10 times - because it is surely the right one...
If the keyboard is connected directly to the USB port, there are about 3 windows to confirm.

Recommendation: Either it shows the ID/name of the keyboard, or you block all keyboards, and whitelist your 'trusted' sealed ones.

Would this be possible?

**Comment by andrewdavidwong** [comment]
Duplicate of #4787

**Comment by andrewdavidwong** [comment]
This appears to be a [duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.
