### ISSUE TITLE
Update LimeSurvey to most recent 3.2x.yy

### ISSUE THREAD

**Issue by ninavizz** [QubesOS/qubes-issues#6534]
## Problem
Today there is an Android bug on `survey.qubes-os.org`, that a few users have emailed to comment about. Similarly, many responses appear to either be cut-and-paste duplicates, or users entering the same thoughts with different words, while others include kvetches about survey malfunctions—presumably, because of the Android bug (or other bugs). :(

I have to fix some broken logic-forks, anyway, and thought it'd be great to get this update pushed before I invest time in that—on the likelihood that such an update may also break those changes should I make them now.

https://community.limesurvey.org/downloads/

## ...but NOT a Showstopper
`4.1` needs @marmarek's focus. So, this shouldn't distract from that. :) 

![giphy](https://user-images.githubusercontent.com/8262612/115089651-8ca16500-9ec7-11eb-9091-7c4300a2f8c2.gif)

**Comment by ninavizz** [comment]
@marmarek poke, poke? :D

**Comment by marmarek** [comment]
This was done at that time. But also not relevant until we'll do another survey (right now the survey instance is stopped).
