### ISSUE TITLE
"Enforcing GPG signature check globally as per active RPM security policy" not appearing in StandaloneVMs

### ISSUE THREAD

**Issue by Rspigler** [QubesOS/qubes-issues#6536]
**Qubes OS version**
Qubes 4.0

**Affected component(s) or functionality**
Fedora-based StandaloneVM's

**Brief summary**
I have a fully updated QubesR4, so I now see the message:

> Warning: Enforcing GPG signature check globally as per active RPM security policy (see 'gpgcheck' in dnf.conf(5) for how to squelch this message)

In both `dom0` and Fedora-32 `TemplateVM`.  However, I do not see this message in any Fedora-32 based StandaloneVM's.  Does this mean the update has not been properly applied, or is the message just not appearing consistently?

**How Reproducible**
It's consistent for me, but in terms of testing re: reverting to pre-QSB-067 and updating again to see if this happens always - I have not done so.

**Expected behavior**
All Fedora-32 based Qubes display the enforced signature check command.

**Actual behavior**
Only `dom0` and the Fedora-32 `TemplateVM` does.

**Comment by DemiMarie** [comment]
How do you update your qubes?  If you use the updates widget, it *should* work (if not, that’s a bug).

**Comment by Rspigler** [comment]
`sudo dnf upgrade --refresh` in `Terminal`

Also tried updating my TemplateVM to Fedora-33, but that did not change anything

**Comment by andrewdavidwong** [comment]
> `sudo dnf upgrade --refresh` in `Terminal`
> 

This is not the same as updating via the Qubes Update tool. The tool performs additional steps beyond merely running dnf. Please try the tool and report back.

**Comment by Rspigler** [comment]
Didn't know that.  I prefer manually updating myself in terminal, so I can see the output and know the packages that are updating.

Tried using Qubes Updater. The update completes successfully, but still no "Enforcing GPG signature check message".  In addition, I also don't see any "Enforcing GPG signature check" message in the Dom0 or Fedora-33 TemplateVM when using the Qubes Updater tool.

**Comment by Rspigler** [comment]
This somehow has now resolved itself:

`sudo dnf upgrade --refresh` shows the message "Warning: Enforcing GPG signature check..." for Fedora-33 based Standalone-VM's.
