### ISSUE TITLE
Backup cancel freezes qube manager

### ISSUE THREAD

**Issue by Eric678** [QubesOS/qubes-issues#6537]
**Qubes OS version**

R4.0

**Affected component(s) or functionality**

Qube Manager

**Brief summary**

Cancelling a backup while the file is being written through an appVM does stop the data flow, however the manager stops processing X events. Even redraw events are ignored. A bunch of qubes-rpc processes are left hanging in the target appVM.

**How Reproducible**

Seems 100%, only tried a couple of times.

**To Reproduce**

1. Set up a backup through to appVM file on a volume that is attached from sys-usb
2. Start the transfer, then cancel, and qube manager freezes

**Expected behavior**

Manager keeps working after the cancel and no processes are left hanging in the appVM

**Actual behavior**

Manager freezes and needs to be killed and restarted. The manager is not using CPU when it is frozen.
cats in target appVM need to be manually killed so that the volume can be unmounted

**Screenshots**

**Additional context**

The output volume was run through another appVM(f33) to decrypt LUKS, as I don't want to do that in sys-usb.
Testing to check that backup works after switching all system qubes to deb-10-min.

**Solutions you've tried**

Kill and restart manager, then kill rpc processes in the appVM.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

I am guessing it was working fine in 2015 when Marek fixed #793, something must have crept in, perhaps as this is not in the test suite.

**Comment by biergaizi** [comment]
I found a workaround: If you want to cancel the backup but Qubes Manager freezes, simply shutdown the target AppVM. As soon as it's down, it forces Qubes Manager comes back to life with `ERROR: Writing backup to VM $appvm failed!`.

**Comment by juju4** [comment]
This seems to be still valid. happen to me on 4.2.3.
no qubes-backup process to kill as per https://forum.qubes-os.org/t/is-there-a-way-to-cancel-this-backup/12186/10
but once shutdown the VM with backup target disk, got control back too.
