### ISSUE TITLE
"disable touchpad while typing" is missing

### ISSUE THREAD

**Issue by maltfield** [QubesOS/qubes-issues#6540]
**Qubes OS version**

R4.0

**Affected component(s) or functionality**

Xfce settings (for touchpad)

**Brief summary**

There is no longer an option for "disable touchpad while typing" in xfce's Settings Manager -> Mouse and Touchpad.

To be clear: this is a new issue. Yesterday, everything was working fine on my laptop. This morning, my horror was realized when I couldn't type anything without my thumbs constantly tapping the touchpad, causing every other word I typed to delete the previous paragraph. I went to the xfce Settings Manager for Mouse and Touchpad, and I found that the "disable touchpad while typing" option was totally missing.

I'm assuming that this was caused by a recent update? Here's my system info:

OS: QubesOS 4.0
Xfce: 4.12
Laptop: Asus UX331U

When I'm in the "Mouse and Touchpad" window, it lists my touchpad "Device" as "ELAN1200:00 04F3:309C Touchpad".

Please let me know if there's any more info I can provide to resolve this issue.

**How Reproducible**

Boot laptop. Type. Touchpad works while I type.

**To Reproduce**

1. Go to Xfce "Start" menu
2. Click System Tools -> Settings Manager
3. Click "Mouse and Touchpad" under the "Hardware" section
4. Choose the `ELAN1200:00 04F3:309C Touchpad` Touchpad device
5. Choose the "Touchpad" tab
6. See no option for "disable touchpad while typing" (anymore)

**Expected behavior**

I shouldn't suddenly loose this feature or its option

**Actual behavior**

I cannot choose "disable touchpad while typing" 

**Screenshots**

**Additional context**

**Solutions you've tried**

I've tried to manually run `syndaemon` and `synclient` (which I believe is the backend of this option), but it doesn't exist in dom0 or sys-usb.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

**Comment by maltfield** [comment]
I've also submitted this upstream here

 * https://gitlab.xfce.org/xfce/xfce4-settings/-/issues/307

However, I think the cause might be here -- not upstream -- because `syndaemon` doesn't exist in dom0, making me think this is some Qubes-specific issue.

**Comment by maltfield** [comment]
Is there any documentation on where X11/libinput options should be set for touchpads in QubesOS?

The upstream bug linked-to above suggested to set an option in libinput. Their docs describe many ways that libinput detects palms to prevent accidental touch events:

 * https://wayland.freedesktop.org/libinput/doc/latest/palm-detection.html
 
And afaict, it looks like the settings would be defined in X11:

 * https://www.mankier.com/4/libinput

Manual edits of X11 configs is hard enough, but I don't even know where to begin with QubesOS. Is the right file in dom0? sys-usb?

Please help point me in the right direction for how to re-enable "disable touchpad while typing" using libinput in QubesOS.

**Comment by maltfield** [comment]
I noticed that when I reboot `sys-usb`, my usb mouse stops working but the touchpad does not stop working. So I'd assume that changes for the touchpad wouldn't be made in `sys-usb`...

**Comment by maltfield** [comment]
How do I install the `Synaptics` input driver in dom0?

**Comment by maltfield** [comment]
If I'm reading these tickets correctly, it appears that QubesOS switched to libinput in 2016-10 for release in Qubes R4.0

 * https://github.com/QubesOS/qubes-issues/issues/2375
 * https://github.com/marmarek/qubes-installer-qubes-os/commit/355e8d032e3cde1ac90f19d6ed08961ef232d701

**Comment by maltfield** [comment]
Related: https://www.reddit.com/r/Qubes/comments/hoajhh/qubes_xfce4_laptop_disable_touchpad_while_typing/

**Comment by andrewdavidwong** [comment]
I think this is still a problem in 4.1.

**Comment by maltfield** [comment]
> I've also submitted this upstream here
> 
>     * https://gitlab.xfce.org/xfce/xfce4-settings/-/issues/307

fwiw, the upstream issue was fixed
