### ISSUE TITLE
add CCT, Discourse to Partners page

### ISSUE THREAD

**Issue by mfc** [QubesOS/qubes-issues#6546]
i think we should list CCT as a partner given they provide us services ([tax-deductible donations in EU](https://www.qubes-os.org/donate/#how-can-i-donate-via-eu-bank-transfer)) and Discourse given they [provide free forum hosting](https://blog.discourse.org/2018/11/free-hosting-for-open-source-v2/).

**Comment by andrewdavidwong** [comment]
Note that a logo and text blurb are required for each partner in the list.

**Comment by mfc** [comment]
great, please find my relevant pull requests above.
