### ISSUE TITLE
Per-user hypervisors

### ISSUE THREAD

**Issue by vporton** [QubesOS/qubes-issues#6547]
**The problem you're addressing (if any)**
There is well-known Qubes deficiency of not VMs not being user-restricted, as a consequence of HVM having no such feature.

I have reported to the security team several other related security vulnerabilities.

**Describe the solution you'd like**
You should make each user (optionally) start his or her own hypervisor (probably running inside the main HVM, so creating an enclosed hypervisor inside a hypervisor) and allow the user to use VMs inside their hypervisor in the same way as usual shared VMs (we could also have group hypervisors corresponding to Unix groups or like this).

This solves at once several serious problems than in practice make Internet, etc. much less secure.

**Where is the value to a user, and who might that user be?**

Users:
- Real multiuser systems.
- Humans with several "roles" (e.g. a user for work or for home).
- Systems where several users are used to prevent secret information leaks because of the same VM is running for several users.

**Describe alternatives you've considered**
The right way to solve the trouble would be to enhance the HVM by introducing in it users and groups.

But the above solution seems much easier to implement quickly.

**Additional context**
My solution may be low-performance and big disk usage, but to make that feature possible to use is better than not having it at all.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

**Comment by andrewdavidwong** [comment]
Qubes OS is not intended to be a multi-user system:

https://www.qubes-os.org/faq/#is-qubes-a-multi-user-system

Closing as "won't do." If anyone has a new reason for why this should be done, please leave a comment, and we'll be happy to take another look. Thank you.

**Comment by vporton** [comment]
The cited document says:

> It is very difficult to securely implement multi-user support.

That was the _reason why_ you didn't implement multi-user support.

In more details, the reason was that HVM does not support it.

I propose an easy to implement was to add (some of) useful for security multi-user functionality. Because in this way, it's relatively easy to implement (does not require to change HVM), your argument does not apply! I suggest to re-open the issue.

**Comment by vporton** [comment]
> > The cited document says:
> > > It is very difficult to securely implement multi-user support.
> > 
> > 
> > That was the _reason why_ you didn't implement multi-user support.

The reason for the assumption is that any other reason is irreasonable: that would be refusing to add a security-enhancing feature without it being difficult to implement.

> I see no basis for that assumption. It is simply a statement, not cited as the reason.
> 
> > In more details, the reason was that HVM does not support it.
> > I propose an easy to implement was to add (some of) useful for security multi-user functionality. Because in this way, it's relatively easy to implement (does not require to change HVM), your argument does not apply! I suggest to re-open the issue.
> 
> The "easy way" is nested virtualization? See below.

Gotcha, nested virtualization is _also_ had to implement. So, my point above is true but irrelevant.

> > You should make each user (optionally) start his or her own hypervisor (probably running inside the main HVM, so creating an enclosed hypervisor inside a hypervisor)
> 
> Nested virtualization has been considered and rejected multiple times. See, e.g., #4104, of which this issue may even be a duplicate.
> 
> > There is well-known Qubes deficiency of not VMs not being user-restricted, as a consequence of HVM having no such feature.
> 
> BTW, I dispute that this is a "well-known Qubes deficiency." Provide evidence if you wish for such claims to be taken seriously.

- It is well-known because it's in the FAQ.
- It is a deficiency, because a modern OS is clearly "lacking" without reasonable multi-user support. This is especially true for security projects. By deficiency I mean something like a feature users want, could have by some effort of developers, but lack. This case clearly falls under this definition of deficiency. That users want it follows from this post.

**Comment by andrewdavidwong** [comment]
> > > The cited document says:
> 
> > > > It is very difficult to securely implement multi-user support.
> 
> > > 
> 
> > > 
> 
> > > That was the _reason why_ you didn't implement multi-user support.
> 
> 
> 
> The reason for the assumption is that any other reason is irreasonable: that would be refusing to add a security-enhancing feature without it being difficult to implement.

That's quite a narrow view. You assume that multi-user support is a security enhancement, but only because you intend to use multiple user accounts as a single user. In principle, multi-user support is security-neutral. The security features you seek can be implemented in other ways directly -- and, in Qubes, many of them are.

> 
> > I see no basis for that assumption. It is simply a statement, not cited as the reason.
> 
> > 
> 
> > > In more details, the reason was that HVM does not support it.
> 
> > > I propose an easy to implement was to add (some of) useful for security multi-user functionality. Because in this way, it's relatively easy to implement (does not require to change HVM), your argument does not apply! I suggest to re-open the issue.
> 
> > 
> 
> > The "easy way" is nested virtualization? See below.
> 
> 
> 
> Gotcha, nested virtualization is _also_ had to implement. So, my point above is true but irrelevant.
> 
> 
> 
> > > You should make each user (optionally) start his or her own hypervisor (probably running inside the main HVM, so creating an enclosed hypervisor inside a hypervisor)
> 
> > 
> 
> > Nested virtualization has been considered and rejected multiple times. See, e.g., #4104, of which this issue may even be a duplicate.
> 
> > 
> 
> > > There is well-known Qubes deficiency of not VMs not being user-restricted, as a consequence of HVM having no such feature.
> 
> > 
> 
> > BTW, I dispute that this is a "well-known Qubes deficiency." Provide evidence if you wish for such claims to be taken seriously.
> 
> 
> 
> - It is well-known because it's in the FAQ.
> 
> - It is a deficiency, because a modern OS is clearly "lacking" without reasonable multi-user support. This is especially true for security projects. By deficiency I mean something like a feature users want, could have by some effort of developers, but lack. This case clearly falls under this definition of deficiency. That users want it follows from this post.

There are several flaws in your logic:

1. Your argument is circular ("deficient because... clearly lacking").

2. "Well-known deficiency" implies that many people regard something as a deficiency. That Qubes is a single-user system is a well-known *property* of Qubes, but you haven't shown that many people regard that property as a deficiency -- only that you do.

3. You assume that a security-oriented OS should have every requested feature that users believe would enhance their security and that developers could feasibly implement. However, unwitting users regularly ask for features that would (contrary to their intentions)  actually _undermine_ their own security. They also frequently request irrelevant and suboptimal features as the result of XY problems.

**Comment by vporton** [comment]
> > > > The cited document says:
> > 
> > 
> > > > > It is very difficult to securely implement multi-user support.
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > That was the _reason why_ you didn't implement multi-user support.
> > 
> > 
> > The reason for the assumption is that any other reason is irreasonable: that would be refusing to add a security-enhancing feature without it being difficult to implement.
> 
> That's quite a narrow view. You assume that multi-user support is a security enhancement, but only because you intend to use multiple user accounts as a single user. In principle, multi-user support is security-neutral. The security features you seek can be implemented in other ways directly -- and, in Qubes, many of them are.

Your response would be relevant only if you have already implemented these very useful security features in another way or planned to implement them soon in another way.

> > > I see no basis for that assumption. It is simply a statement, not cited as the reason.
> > 
> > 
> > > 
> > 
> > 
> > > > In more details, the reason was that HVM does not support it.
> > 
> > 
> > > > I propose an easy to implement was to add (some of) useful for security multi-user functionality. Because in this way, it's relatively easy to implement (does not require to change HVM), your argument does not apply! I suggest to re-open the issue.
> > 
> > 
> > > 
> > 
> > 
> > > The "easy way" is nested virtualization? See below.
> > 
> > 
> > Gotcha, nested virtualization is _also_ had to implement. So, my point above is true but irrelevant.
> > > > You should make each user (optionally) start his or her own hypervisor (probably running inside the main HVM, so creating an enclosed hypervisor inside a hypervisor)
> > 
> > 
> > > 
> > 
> > 
> > > Nested virtualization has been considered and rejected multiple times. See, e.g., #4104, of which this issue may even be a duplicate.
> > 
> > 
> > > 
> > 
> > 
> > > > There is well-known Qubes deficiency of not VMs not being user-restricted, as a consequence of HVM having no such feature.
> > 
> > 
> > > 
> > 
> > 
> > > BTW, I dispute that this is a "well-known Qubes deficiency." Provide evidence if you wish for such claims to be taken seriously.
> > 
> > 
> > 
> > * It is well-known because it's in the FAQ.
> > * It is a deficiency, because a modern OS is clearly "lacking" without reasonable multi-user support. This is especially true for security projects. By deficiency I mean something like a feature users want, could have by some effort of developers, but lack. This case clearly falls under this definition of deficiency. That users want it follows from this post.
> 
> There are several flaws in your logic:
> 
>     1. Your argument is circular ("deficient because... clearly lacking").

"Deficient" may be used in different senses (bug, misfeature, missing feature, slow performance, etc.), while the word lacking is of a more exact sense ("would be wanted by users" (in this case to improve security)) in English (in this context). So, I clarify an inexact term through a more exact term. That's not circular.

>     2. "Well-known deficiency" implies that many people regard something as a deficiency. That Qubes is a single-user system is a well-known _property_ of Qubes, but you haven't shown that many people regard that property as a deficiency -- only that you do.

Wrong: If it were not, it would certainly not be mentioned in FAQ. Absolutely sure.

>     3. You assume that a security-oriented OS should have every requested feature that users believe would enhance their security and that developers could feasibly implement. However, unwitting users regularly ask for features that would (contrary to their intentions)  actually _undermine_ their own security. They also frequently request irrelevant and suboptimal features as the result of XY problems.

That's irrelevant, because you didn't mention that this particular feature would undetermine security. My opinion is that this feature if implemented would not undetermine security.

**Comment by iamahuman** [comment]
GUI VMs would make a multiuser system more feasible. Such system can be implemented with per-user GUI VMs and video card access arbitration, accompanied by access restrictions imposed by Admin APIs. See https://groups.google.com/g/qubes-devel/c/f2gDpXE3NJ8.

Meanwhile implementing nested virtualization is an upstream issue, and utilizing it would likely only increase the attack surface (#4104).
