### ISSUE TITLE
Scr Lk key does not work

### ISSUE THREAD

**Issue by vporton** [QubesOS/qubes-issues#6551]
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
XFCE

**Brief summary**
Scr Lk key (the same as F12 key on my system) does not work, whatever modifier keys I press together with it.

**How Reproducible**
Reproducible.

**To Reproduce**

1. Enable Power Manager startup app.
2. Press on a laptop F12 together with the relevant modifier key.

**Expected behavior**
The screen is locked with a password (e.g. XScreenSaver started).

**Actual behavior**
Nothing.

**Screenshots**

**Additional context**

**Solutions you've tried**

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

**Comment by marmarek** [comment]
The default key combo for locking the screen in Xfce is Ctrl+Alt+Del. You can change it in "Keyboard" settings (Application Shortcuts tab).
