### ISSUE TITLE
Stop VMs on logout (to undisplay superfluous windows)

### ISSUE THREAD

**Issue by vporton** [QubesOS/qubes-issues#6552]
**The problem you're addressing (if any)**
If I open a non-dom0 window showing a secret information, log out and log in as a different user, the window is shown again without that second user approving. That is the window appears contrary to natural expectations and may cause an unexpected leak of secret information. Moreover, this turns a security measure into an anti-measure: I did setup two user for the purpose to avoid this scenario and was relying on it, having a false sense of security. That's quite a serious problem.

**Describe the solution you'd like**
There should be an easy way to set in `/etc/lightdm/lightdm.conf`
```
session-cleanup-script=
```
to such a value to kill the VMs. (Could you by the way provide such a script in a comment below?)

It also should be duplicated in 
```
session-setup-script=
```
because `session-cleanup-script` isn't called in some situations, e.g. if a a user used Linux console to start a VM.

Moreover such killing VMs should be the default, because otherwise it's insecure (and gives false sense of security).

**Where is the value to a user, and who might that user be?**
For example,
- a home user keeping a secret information
- somebody doing a remote presentation (e.g with a Zoom) independently on how safe is his/her physical environment

**Describe alternatives you've considered**
- Stop using Qubes at all. Buy a second computer.

**Additional context**
It is _not_ about making Qubes a real multi-user OS. It is mostly about the same user having several different logins for the purpose to keep information safe visually (not on the user access rights level).

Some VMs (dom0 and probably firewall/Tor VMs should not be killed: it seems that killing a firewall doesn't much increase security, but just would slow down the system).

This is a (rather severe) security report, but I publish it openly, because it seems to be no way for an attacker to use it.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

**Comment by andrewdavidwong** [comment]
> I did setup two user for the purpose to avoid this scenario and was relying on it, having a false sense of security. That's quite a serious problem. 

The problem is your faulty expectation. You know that Qubes is not intended to be a multi-user system, so why would you expect any such thing from the user switching mechanism?

> It is not about making Qubes a real multi-user OS. It is mostly about the same user having several different logins for the purpose to keep information safe visually (not on the user access rights level).

You're just trying to use the wrong tool for the job. Simply use virtual desktops or simply minimize those windows if you don't wish for their comments to be visible to others who can see the screen.

**Comment by vporton** [comment]
> > I did setup two user for the purpose to avoid this scenario and was relying on it, having a false sense of security. That's quite a serious problem.
> 
> The problem is your faulty expectation. You know that Qubes is not intended to be a multi-user system, so why would you expect any such thing from the user switching mechanism?

Any public interface of a "secure" system should be reasonable secure.

You are right that full multi-user security is not yet reasonable, because it is hard to implement.

But hiding windows is reasonable. I expect all important and reasonable security measures in a security-oriented system. Otherwise it's called a low-quality product.

> > It is not about making Qubes a real multi-user OS. It is mostly about the same user having several different logins for the purpose to keep information safe visually (not on the user access rights level).
> 
> You're just trying to use the wrong tool for the job. Simply use virtual desktops or simply minimize those windows if you don't wish for their contents to be visible to others who can see the screen.

Oh, Qubes is a wrong tool for keeping secret files? Should I instead install Ubuntu, because there secret windows don't appear on the screen unexpectedly?

The trouble is that it's to easy to forget to minimize a window (or for example there may be a power failure). That's relying on humans. You said exactly that you rely on a human for security.

Virtual desktops may be switched by pressing a key incidentally. That's very insecure. It's not a solution.
