### ISSUE TITLE
An attack scenario - replaced laptop and a way to mitigate

### ISSUE THREAD

**Issue by vporton** [QubesOS/qubes-issues#6554]
**The problem you're addressing (if any)**
Anti-evil maid doesn't help against this attack scenario:

Just replace the user's laptop by a similarly looking (and the same login screen) laptop with a networked keylogger.

Their measures don't help against this cheap attack at all.

Another trouble is that the system installer/admin does not always has access to BIOS. Yes, that happens sometimes. My solution does not need to change BIOS settings.

**Describe the solution you'd like**
The only way to solve this big security vulnerability (and also the problem Anti Evil Maid was invented for) is to ask user for some secret (like CAPTCHA dependent on input data, but unlike CAPTCHA dependent in an non-publicly known way) after login before continuing and after this require a second (different) password to decrypt the disk.

We could decrypt the disk by a cryptographic hash of two passwords combined.

**Where is the value to a user, and who might that user be?**
Anyone having a secret that is valuable enough to find a similar laptop and install Qubes here to gain the secret.

**Describe alternatives you've considered**

**Additional context**

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

**Comment by andrewdavidwong** [comment]
> The only way to solve this big security vulnerability (and also the problem Anti Evil Maid was invented for) is to ask user for some secret (like CAPTCHA dependent on input data, but unlike CAPTCHA dependent in an non-publicly known way) after login before continuing and after this require a second (different) password to decrypt the disk.

What you're describing is simply the AEM password, which is already implemented.
