### ISSUE TITLE
Ctrl+Alt+L by default assigned to both logout and lock screen in XFCE

### ISSUE THREAD

**Issue by vporton** [QubesOS/qubes-issues#6556]
**The problem you're addressing (if any)**
In conjunction with #6552 we need also to be able to logout easily.

There are two troubles:
- Ctrl+Alt+L is by default assigned not only to logout but also to lock screen in XFCE. That's a contradiction and makes the system work not as intended.
- The user should also have a logout button in XScreenSaver (optionally, because some users would not want to be logged out by anyone with keyboard access).

**Describe the solution you'd like**
- Correct the initial XFCE configuration.
- Add the optional new XScreenSaver button.

**Where is the value to a user, and who might that user be?**
One who wants to be able to login as a different user without exposing the current desktop or just one who wants to be logged out more easily.

**Describe alternatives you've considered**

**Additional context**

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

**Comment by andrewdavidwong** [comment]
Issues must be about only one thing. Updating this issue to be about only the first thing mentioned.

**Comment by andrewdavidwong** [comment]
Is this an upstream bug in Xfce? If so, please report it there instead.

**Comment by unman** [comment]
On Fri, Apr 23, 2021 at 12:23:00PM -0700, Andrew David Wong wrote:
> Is this an upstream bug in Xfce? If so, please report it there instead. 
> 

It is default configuration in Xfce, and not a Qubes issue.
I think the intention may be to close session if Xflock isnt present,
but I could be wrong.
In use, I don't think there's a problem - afaik the shortcut calls the
locker first, and doesn't close the session. But it's an issue for
Xfce, not us.
