### ISSUE TITLE
Android app to supplement Qubes security

### ISSUE THREAD

**Issue by vporton** [QubesOS/qubes-issues#6558]
**The problem you're addressing (if any)**
If I have a secret information on the screen, somebody phones me, I may raise the phone and incidentally send a screen photo.

**Describe the solution you'd like**
I want an Android app to supplement Qubes to turn camera off every time when a certain user is logged in in Qubes and the screen isn't blanked or a certain VM is running and the screen isn't blanked  or even every time when and screen isn't blanked.

Others may want an app for iPhone.

Qubes should recommend this app during installation and show a QR to install it. 

**Where is the value to a user, and who might that user be?**
Anyone with secret files and some mobile device neaby.

**Describe alternatives you've considered**
Buy a new house with more rooms.

**Additional context**
Personally me probably don't need to run off also the microphone, but others may want to.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

**Comment by fepitre** [comment]
> **The problem you're addressing (if any)**
> If I have a secret information on the screen, somebody phones me, I may raise the phone and incidentally send a screen photo.

If you would have worked seriously on confidential/secret data on your screen, you would know that phone is forbidden. Also, your request sounds like: If I'm driving and someone calls me and I decide to answer, I may have an accident. Simply don't answer.
 
> **Describe the solution you'd like**
> I want an Android app to supplement Qubes to turn camera off every time when a certain user is logged in in Qubes and the screen isn't blanked or a certain VM is running and the screen isn't blanked or even every time when and screen isn't blanked.

There is no "I want" here in Qubes OS or any other opensource project. There is "I would like" like it's proposed in the issue text. If you want something do it.

**Comment by vporton** [comment]
> > **The problem you're addressing (if any)**
> > If I have a secret information on the screen, somebody phones me, I may raise the phone and incidentally send a screen photo.
> 
> If you would have worked seriously on confidential/secret data on your screen, you would know that phone is forbidden. Also, your request sounds like: If I'm driving and someone calls me and I decide to answer, I may have an accident. Simply don't answer.

Forbidden by whom? :-) I am not a member of an organization. Do you think only officials have secrets?

In practice it means that my work may be paused till I move to a new house with more rooms.

> > **Describe the solution you'd like**
> > I want an Android app to supplement Qubes to turn camera off every time when a certain user is logged in in Qubes and the screen isn't blanked or a certain VM is running and the screen isn't blanked or even every time when and screen isn't blanked.
> 
> There is no "I want" here in Qubes OS or any other opensource project. There is "I would like" like it's proposed in the issue text. If you want something do it.

Sorry, I am not a native English speaker, I want and I would like sound too similar for me.
