### ISSUE TITLE
Replace @asyncio.coroutine with proper async

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#6559]
**Qubes OS version (if applicable)**

N/A

**Affected component(s) or functionality (if applicable)**

Most notably qubesd, but given how old our async Python code is, there are probably several others.

**Brief summary**

Legacy generator-based coroutines are [deprecated] and will be removed in Python 3.10.  We need to migrate away from them.

**Additional context**

We have a lot of old asynchronous Python code :smile:.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

https://docs.python.org/3/library/asyncio-task.html#asyncio-generator-based-coro

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

[deprecated]: https://docs.python.org/3/library/asyncio-task.html#asyncio-generator-based-coro

**Comment by rustybird** [comment]
Duplicate of #2738

**Comment by DemiMarie** [comment]
> Duplicate of #2738

Good catch, thanks!
