### ISSUE TITLE
Template Manager should have a per-qube "notes" field

### ISSUE THREAD

**Issue by Osndok** [QubesOS/qubes-issues#6560]
**The problem you're addressing (if any)**

From time to time, I find that I have software in particular qubes that is "stuck" to an older template version. Qubes handles this quite well, as it happily supports running applications from a mix of OSes and OS-versions.

However, it is often harder to manage the small bet of metadata of "why". As it stands, the streamlined template manager actually makes it a bit `too easy` to accidentally upgrade a qube's template (sometimes even requiring a restore from backup).

**Describe the solution you'd like**

I think it would be swell if an additional column would be added to the template manager interface. "Notes", where I could write (or at least `view`) previous assertions that may relate to the selected template.

Example notes might read:
* `requires fedora < 32 b/c software X requires python 2`
* `requires debian 9 b/c they removed package Y in v10`

I say "at least read" b/c even if the notes field was shared with a notes field in the qube settings, or only settable on the command line, I would still make use of it.

**Where is the value to a user, and who might that user be?**

This change is intended to help users better manage their templates, and decrease frustration therefrom.

**Describe alternatives you've considered**

I've considered keeping track of these template constraints in an external notes file.

**Additional context**

I have a lot of qubes running a lot of different OSes & OS-versions.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

https://www.qubes-os.org/doc/templates/

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

None found.

**Comment by ctrlaltf24** [comment]
While it doesn't integrate with the UI, you could use qvm-features to store that kind of information. for example `qvm-features debian-10 dont-update-reason "requires package X"`. And/Or use qvm-tags to indicate that you don't want to update a template `qvm-tags debian-10 add  no-dist-upgrade`.

**Comment by ninavizz** [comment]
This is an interesting request, TY for sharing and for the background!

**Comment by ninavizz** [comment]
...I'm also getting this request in the appmenu survey, FYI.
