### ISSUE TITLE
Incorrect qrexec policy handling

### ISSUE THREAD

**Issue by unman** [QubesOS/qubes-issues#6569]
**Qubes OS version**

R4.0 updated

**Affected component(s) or functionality**

qrexec policy

**Brief summary**

Policy parsing process unclear - policy is affected by later rules, despite matching earlier rule.

**How Reproducible**

100%

**To Reproduce**

1. Edit (e.g) qubes.OpenInVM to include these rules:
```
qube @anyvm ask
qube @anyvm allow, default_target=@dispvm:qube2
```

2. In `qube`, attempt `qvm-open-in-dvm`

**Expected behavior**

Dialog box will appear, allowing selection of DisposableVM target

**Actual behavior**

`Request refused`

**Screenshots**

**Additional context**

Quite possibly the new policy format at #4370 will resolve this issue.

**Solutions you've tried**

Commenting out the second line works, which suggests that policy parsing does **not** stop at the first match, as per policy file and documentation.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

https://www.qubes-os.org/doc/qrexec/

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

**Comment by marmarek** [comment]
Make sure there is no syntax error in the policy file. A syntax error anywhere in the file results in an instant reject.
If that's the case, check `journalctl` in dom0.

**Comment by unman** [comment]
Hm yes - I'd changed `ask` to `allow` in testing, but kept `default_target` instead of `target`.
Commenting out the first  `ask` line, and keeping the `allow` results in ` request refused` although there is not `deny` rule at all. journalctl has `invalid target` and indeed I had renamed the base for the disposableVM.

Not a syntax error but a brain error.
