### ISSUE TITLE
Issues with bind-dirs.sh when binds() includes directories or files in /usr in Fedora32 TemplateBasedVM

### ISSUE THREAD

**Issue by joshinsel** [QubesOS/qubes-issues#6571]
**Qubes OS version**

R4.0.4

**Affected component(s) or functionality**

bind-dirs.sh and binds() environmental variable in Fedora32 TemplateBasedVMs

**Brief summary**

I created a file /rw/config/qubes-bind-dirs.d/50_user.conf with full permissions for root in a new Fedora32 TemplateBasedVM. When including a file under /usr/bin in binds, it does not remain persistent after reboots. This occurs even if the file is manually added to /rw/bind-dirs/usr/bin. When the directories /usr or /usr/bin are included in binds, the VM crashes on startup. 

**How Reproducible**

It is always reproduced.

**To Reproduce**

1. Create a file /rw/config/qubes-bind-dirs.d/50_user.conf with full root access on a Fedora32 TemplateBasedVM
2. In the file, write binds+=('path'), with a file in /usr/bin or the directories /usr or /usr/bin in place of path
3. Reboot VM

**Expected behavior**

Files or changes to files or directories listed in 50_user.conf remain persistent after reboots.

**Actual behavior**

When files in /usr/bin are listed in 50_user.conf, they do not remain persistent after reboots, and if the directories /usr and /usr/bin are included in 50_user.conf, the VM crashes on startup.

**Solutions you've tried**

Manually adding relevant files and directories to /rw/bind-dirs. 

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

https://www.qubes-os.org/doc/bind-dirs/

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

https://github.com/QubesOS/qubes-issues/issues/2661

**Comment by joshinsel** [comment]
Log file produced by crash after including directory in /usr located here: https://github.com/joshinsel/Qubes-Issue-Logs/blob/master/guest-sys-vpn.log

**Comment by unman** [comment]
I **know** that this works for (some) individual files in /usr/bin on Fedora 32.
If you could say *which* file you are trying to bind, and post your bind-dirs config file that would be helpful.

**Comment by joshinsel** [comment]
> 
> 
> I **know** that this works for (some) individual files in /usr/bin on Fedora 32. If you could say _which_ file you are trying to bind, and post your bind-dirs config file that would be helpful.
> 
> It also works binding /usr/bin, and the qube does not crash, contrary to your report - although it seems that some flags (setuid) are then incorrect.
