### ISSUE TITLE
Docs: broken "edit this page" link (because of translations)

### ISSUE THREAD

**Issue by deeplow** [QubesOS/qubes-issues#6578]
**Qubes OS version**

Affects the website

**Affected component(s) or functionality**

qubesos.github.io

**Brief summary**

"edit this page" link is broken

**How Reproducible**

100%

**To Reproduce**

1. visit https://www.qubes-os.org/support/
2. click on "Edit This Page" on the sidebar

**Expected behavior**

link to https://github.com/QubesOS/qubes-doc/edit/master/introduction/support.md

**Actual behavior**

Links to https://github.com/QubesOS/qubes-translated/edit/master_doc/introduction/support.md

**Solutions you've tried**

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

None

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

Didn't find

**Comment by deeplow** [comment]
My hypothesis is that the issue lies on the "edit this page" being set to edit the translated page. However, there should be an "if" for when the user is in the canonical website (english)

**Comment by tokideveloper** [comment]
There is an "if" but the condition is wrong. I'll fix that.

Thanks for finding it!

**Comment by andrewdavidwong** [comment]
Fixed by https://github.com/QubesOS/qubesos.github.io/pull/167
