### ISSUE TITLE
Failed to install networking driver: Alfa AWUS036ACH ]

### ISSUE THREAD

**Issue by DevoUraq** [QubesOS/qubes-issues#6579]
Hello Everyone…
Iam looking To install The RTL8812AU Driver In qube
Iam Using Sys-net (As Sys-usb) i can see The Alfa in 
(lsusb in sys-net) And In (Qvm-usb)  So I try To install it in fedora 32 using this command:-
Git clone https://github.com/aircrack-ng/rtl8812au
Then Make && make install 
Reboot The Pc but I can't start fedora 32 Or sys-net because it based on iT (GOT Error) 

So i did A Clean Installation Of qube 
So my question can i install The RTL8812AU Driver 
On qube!?  
Really Need It 

thank You Guys

**Comment by andrewdavidwong** [comment]
Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this does not appear to be suitable for `qubes-issues`. We ask that you please post this on the [`qubes-users` mailing list or forum](https://www.qubes-os.org/support/) instead. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a brief comment explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.
