### ISSUE TITLE
Major OS error, all VMs unusable, network manager disappeared

### ISSUE THREAD

**Issue by sunsunnysun** [QubesOS/qubes-issues#6582]
I have encountered some very major issues making my whole OS unusable. Upon boot I saw a few [failed] processes, then when I logged in the network manager Icon has disappeared and all my VMs will not start they give me the error below ( I will post a picture also)

Domain sys-net has failed to start: qrexec-daemon start failed: connection to the VM

Then Depending on the VM I try to start :

Domain [ VM name ] has failed to start: qrexec-daemon start failed: connection to the VM failed

Additionally when I try to manually open the Network manager from the system tools it is all grayed out and not accepting inputs.
Also when I logged in all my desktop icons were randomly rearranged.

I have no idea what to do to fix this or what caused it, possibly a recent update?

Please advise me on any thoughts you could or ways to revert to a previously working version.
Any help is super appreciated, I have some personally valuable information stored in a VM so I can not just reinstall the OS.

This is not seemingly solely a networking issue because when I try to start non-connected QUbes such as Vault then i am meet with the same error

I can post some sysnet logs if that would be helpful

![image](https://user-images.githubusercontent.com/83728173/117198670-97298d00-ade9-11eb-812b-04b0e4b9d070.png)
![image](https://user-images.githubusercontent.com/83728173/117198699-9f81c800-ade9-11eb-8c5f-f812d9ae11a4.png)

**Comment by andrewdavidwong** [comment]
Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this does not appear to be suitable for `qubes-issues`. We ask that you please post this on the [`qubes-users` mailing list or forum](https://www.qubes-os.org/support/) instead. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a brief comment explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.
