### ISSUE TITLE
qubes-dom0-update UnicodeEncodeError with PL locale

### ISSUE THREAD

**Issue by aidecoe** [QubesOS/qubes-issues#6583]
**Qubes OS version**

R4.0.4

**Affected component(s) or functionality**

qubes-dom0-update and other commands like qubesctl.

**Brief summary**

With locale set to PL on installation, commands in dom0 terminal throw errors related to locale, primarily encoding related.

**How Reproducible**

100%

**To Reproduce**

1. Install Qubes OS with PL set upon installation.
2. Once installed and logged in, open dom0 terminal.
3. Try to install a new package with `qubes-dom0-update`.

**Expected behavior**

Commands should display messages in Polish.

**Actual behavior**

Instead errors are thrown: [qubes-dom0-update.log](https://github.com/QubesOS/qubes-issues/files/6430370/qubes-dom0-update.log)

**Screenshots**

**Additional context**

**Solutions you've tried**

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

**Comment by DemiMarie** [comment]
This appears to be a DNF bug.  Line 94 of `/usr/lib/python3.5/site-packages/dnf/logging.py` creates a `logging.FileHandler`, but does not specify an encoding.  In Python, encodings often default to `ascii`, which would trigger the errors @aidecoe saw.

@marmarek: is it practical for us to fix this in R4.0?
