### ISSUE TITLE
Spurious Qube Manager warning when disabling TemplateVM networking

### ISSUE THREAD

**Issue by SaswatPadhi** [QubesOS/qubes-issues#6592]
**Qubes OS version**
R4.1

**Affected component(s) or functionality**
Qube Manager

**Brief summary**
When changing the networking of TemplateVMs, I get a warning that says:

```
Connecting a TemplateVM directly to network is highly discouraged.

You are breaking a basic part of Qubes security and there is probably no real need to do so. Continue at your own risk.
```

This warning is useful in other cases, but not when I am disabling networking; in my case: changing from from "default" to "none". This seems like a recent change -- I had never encountered this before.

**How Reproducible**
100%

**To Reproduce**

1. Open Qubes Manager
2. Open Settings for any Template VM
3. Change Networking in the Basic tab to `(none)`

**Expected behavior**
Qubes Manager should warn only when _enabling_ networking on a TemplateVM, i.e. setting networking to anything other than `(none)`.

**Actual behavior**
Qubes Manager always warns on any change to TemplateVM networking.

**Comment by ninavizz** [comment]
Noting to #6634
