### ISSUE TITLE
Create GH "Project" to track small, near-term enhancements to existing Updater

### ISSUE THREAD

**Issue by ninavizz** [QubesOS/qubes-issues#6599]
**Brief summary**
@mfc @marmarta @DemiMarie @andrewdavidwong might a "Project" be able to be created, to track small/incremental changes to the updater experience, short of a complete redesign? Would that help or harm existing project management efforts? Only not CC'ing Marek, to avoid distracting him with pithy non-kernal/zen topix. :)

**Additional context**
I was going to create a new Issue to track this as an epic, but quite like GitHub's "Projects" feature, and feel it could be helpful to track more things in-progress through it.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
Many ideas have been communicated in other issues, that I would like to prioritize in this projects list. 
- Messaging and item status' that could be incorporated into today's Updater UI via #6590 
- A dynamic tray widget to communicate the number of pending updates, and with a clearer semiotic than today's "explodey" icon #5657 
  - A clearer "system" of icons across Qubes Manager and Domains Widget, to communicate what existing items already communicate (and within the context of a clearer icon created for the Tray area)
- Small items from #6299 
- Integration of Updater notifications into a future release of the TBD new AppMenu

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
Longer-term, it would be nice to be able to offer user configuration options for the updater... so that projects like SecureDrop Workstation don't have to build our own updater for the user to then use with the Qubes Updater; however that feels much more long-term and off in the distance.

**Comment by DemiMarie** [comment]
https://github.com/QubesOS/qubes-issues/projects/8

**Comment by DemiMarie** [comment]
> Yay, thx @DemiMarie! One more small request: that the _Project_ only track user-facing enhancements, vs bugs? That will help, meethinks.

Done, but you should be able to do this yourself without having to get someone else to do this.  @mfc can you get @ninavizz write access to this repo if she doesn’t have it already?

**Comment by DemiMarie** [comment]
@ninavizz You’re as much a part of the team as I am :heart:.

**Comment by andrewdavidwong** [comment]
> https://github.com/QubesOS/qubes-issues/projects/8

Closing as done.

> Done, but you should be able to do this yourself without having to get someone else to do this. @mfc can you get @ninavizz write access to this repo if she doesn’t have it already?

I'm sure this can happen without this issue needing to remain open.

**Comment by mfc** [comment]
@andrewdavidwong @marmarek can you add @ninavizz as a github member to the org? and then make sure she can edit and use this project? https://github.com/QubesOS/qubes-issues/projects/8

**Comment by andrewdavidwong** [comment]
> @andrewdavidwong @marmarek can you add @ninavizz as a github member to the org? and then make sure she can edit and use this project? https://github.com/QubesOS/qubes-issues/projects/8

I don't have permissions to do that. I think only @marmarek does.

**Comment by ninavizz** [comment]
Well, shoot. I cannot even edit the project—add a card for a closed issue, etc. :(

**Comment by marmarek** [comment]
Invite sent.
