### ISSUE TITLE
Logs should be on the private volume by default

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#6600]
**The problem you're addressing (if any)**

Logs are currently stored in the root volume, which is only persistent in TemplateVMs and StandaloneVMs.  In AppVMs, it is discarded at reboot.  Furthermore, if a TemplateVM or StandaloneVM’s root volume needs to be reverted due to a botched software update, the logs of the botched update are lost.

**Describe the solution you'd like**

Logs should be stored in the private volume.  This ensures that they are persistent across AppVM reboot, and that package manager logs persist if the root volume is reverted.

**Where is the value to a user, and who might that user be?**

All users who rely on system logs will benefit from improved visibility into system operation.

**Describe alternatives you've considered**

**Additional context**

I have this working on my own system and will submit a PR.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

**Comment by marmarek** [comment]
An alternative is LogVM: #830

**Comment by DemiMarie** [comment]
> An alternative is LogVM: #830

That’s a better solution, but it is also a lot of work.  This is an almost trivial change :smile:.

**Comment by ctrlaltf24** [comment]
As a user, I'd prefer that my logs don't persist across AppVM reboots. Having them persist would fill up AppVM's private volume faster, at no benefit to my workflow. The power users who want to setup that kind of auditing can add the log folders they want to persist to bind-dirs https://www.qubes-os.org/doc/bind-dirs. I understand the motivation to want to set this up, however it hurts the basic user, and the advanced users can do this "trivial change" themselves.

**Comment by DemiMarie** [comment]
> As a user, I'd prefer that my logs don't persist across AppVM reboots. Having them persist would fill up AppVM's private volume faster, at no benefit to my workflow. The power users who want to setup that kind of auditing can add the log folders they want to persist to [bind-dirs](https://www.qubes-os.org/doc/bind-dirs). I understand the motivation to want to set this up, however it hurts the basic user, and the advanced users can do this "trivial change" themselves.

Thanks for your feedback!  Right now, adding them to bind-dirs doesn’t actually work reliably, as the journal will start before bind-dirs runs.  Nevertheless, your feedback is very much valued, thanks!

`systemd-journald` offers options to limit the size of journals.  What if we kept the journals by default, but limited their size to something reasonable?

**Comment by unman** [comment]
On Thu, May 13, 2021 at 12:21:04AM -0700, Demi Marie Obenour wrote:
> > As a user, I'd prefer that my logs don't persist across AppVM reboots. Having them persist would fill up AppVM's private volume faster, at no benefit to my workflow. The power users who want to setup that kind of auditing can add the log folders they want to persist to [bind-dirs](https://www.qubes-os.org/doc/bind-dirs). I understand the motivation to want to set this up, however it hurts the basic user, and the advanced users can do this "trivial change" themselves.
> 
> Thanks for your feedback!  Right now, adding them to bind-dirs doesn???t actually work reliably, as the journal will start before bind-dirs runs.  Nevertheless, your feedback is very much valued, thanks!
> 
> `systemd-journald` offers options to limit the size of journals.  What if we kept the journals by default, but limited their size to something reasonable?
> 

I wouldn't want template based qubes to have persistent logs either.
I don't find the arguments for this in Templates to be convincing. If an
update borks the template to such an extent that a revert is the only
way out, I wouldn't want those logs to be retained.
It's hard enough to interpret logs without having logs that no longer
reflect the states that the machine has passed through.

**Comment by DemiMarie** [comment]
> I wouldn't want template based qubes to have persistent logs either.

Why is that?

**Comment by ctrlaltf24** [comment]
> `systemd-journald` offers options to limit the size of journals. What if we kept the journals by default, but limited their size to something reasonable?

That would help, but I'd still prefer the default not to persist logs, as it would still take space (even if its not much) that has no value to me.

> Thanks for your feedback! Right now, adding them to bind-dirs doesn’t actually work reliably, as the journal will start before bind-dirs runs.

If bnd-dirs wasn't the trivial solution, what mechanism were you planning to use to have them persist?



How would the AppVM's journal get updated from updates in the TemplateVM's journal? Consider the following scenario:
> Template VM installation (writes to initial journal)
> AppVM created (journal copied from the TemplateVM's journal)
> AppVM ran (journal updated with new entries)
> TemplateVM ran, updates applied (journal in TemplateVM updated)
> AppVM ran

Do the updates from the TemplateVM journal somehow get added to an existing AppVM? or have they already diverged?

> package manager logs persist if the root volume is reverted.

Why would you want such logs all the time? There may exist a couple scenarios in which you want the logs, but in which case wouldn't it be easier to copy the logs out of the root volume before it's reverted?

**Comment by DemiMarie** [comment]
> > Thanks for your feedback! Right now, adding them to bind-dirs doesn’t actually work reliably, as the journal will start before bind-dirs runs.
> 
> If bnd-dirs wasn't the trivial solution, what mechanism were you planning to use to have them persist?

`bind-dirs` *is* the trivial solution, but for it to work reliably, `systemd-journald` needs to wait until `bind-dirs` has had a chance to run.  Otherwise, it will be writing logs to a mounted-over directory!

**Comment by DemiMarie** [comment]
> How would the AppVM's journal get updated from updates in the TemplateVM's journal? Consider the following scenario:
> 
> * Template VM installation (writes to initial journal)
> * AppVM created (journal copied from the TemplateVM's journal)
> * AppVM ran (journal updated with new entries)
> * TemplateVM ran, updates applied (journal in TemplateVM updated)
> * AppVM ran

If I were designing the system, I would have `/var/log` be as much a part of `/rw` as `/usr/local` is.

**Comment by DemiMarie** [comment]
Closing this in favor of #830.
