### ISSUE TITLE
qubesctl cannot set qvm.prefs provides_network

### ISSUE THREAD

**Issue by p1llule** [QubesOS/qubes-issues#6609]
**Qubes OS version**
4.0

**Affected component(s) or functionality**
qubesctl, 
saltstack 2017.7.1 (nitrogen)

**Brief summary**
I cannot set or get the provides_network property of a VM via qubesctl. I can still do it with qvm-prefs.

updated tl.dr : the property 'provides_network' is not named consistently, sometimes you can uses it as it, sometimes you must use 'provide-network', `qubesctl` returns 'provides_network' but expect 'provides-network'.

**How Reproducible**
Always for me

**To Reproduce**

```` shell
sudo qubesctl qvm.prefs sys-net provides_network
````
returns :
```` sls
local:
    ----------
    retcode:
        1
    stderr:
    stdout:
        provides_network   : Invalid key!
````

**Expected behavior**
Be able to get and set this provides_network property with qubesctl

**Actual behavior**
I cannot get or set this provides_network property with qubesctl

**Screenshots**
none

**Additional context**
I seen that while trying to make a minimal debian sys-net salt formula. It is this very property that is affected (I can set others without problems).

**Solutions you've tried**

[Looking at the code](https://github.com/QubesOS/qubes-mgmt-salt-dom0-qvm/blob/master/_modules/ext_module_qvm.py)

Eventually I figured out that I was taking the wrong way : there is a flag property for qvm.create that allow to set provides_network at the creation of the vm,
you can see it under the qvm.present function here from the sys_net.create.sls I make :

```` sys_net.create.sls
include:
  - d10_net.clone

remove:
  qvm.absent:
    - names:
      - sys_net

qvm-create.id:
  qvm.present:
    - name:                 sys_net
    - template:             d10_net
    - label:                red
    - flags:
      - net

qvm-prefs.id:
  qvm.prefs:
    - name:                 sys_net
    - autostart:            False
    - include_in_backups:   False
    - memory:               300
    - pcidevs:              {{ salt['grains.get']('pci_net_devs', []) }}
    - vcpus:                2
    - virt_mode:            hvm

qvm-features.id:
  qvm.features:
    - name:                 sys_net
    - disable:
      - meminfo-writer
````

In fact if you want to setup a sys-net you really want to use this flag since it will automatically also set the network-manager and qubes-network services that otherwise, you have to declare with eg qvm.service

Now that I look again at the documentation, there is indeed an example with a proxy flag I missed, but still,
I don't understand why the salt formulas shipped with Qubes use directly qvm.prefs provides_network in their declarations and then, don't specify the services to activate ?

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
https://www.qubes-os.org/doc/salt/

**Comment by unman** [comment]
You want something like `qubesctl state.apply prefs`
where "prefs" is a salt state containing something like:
```
prefs:
  qvm-prefs:
    - name: sys-net
    - provides-network: true
```

**Comment by p1llule** [comment]
I used a shell command thinking it was more easy to make the point with it but well,
Your reply point out what is wrong here : 

````
sudo qubesctl qvm.prefs sys-net
````
returns:
```` sls
"local:
    ----------
    retcode:
        0
    stderr:
    stdout:
        autostart          : True
        debug              : *default*
        default_user       : *default*
        default_dispvm     : *default*
        template_for_dispvms: *default*
        virt_mode          : hvm
        label              : red
        backup_timestamp   : 1609950580
        include_in_backups : *default*
        installed_by_rpm   : *default*
        ip                 : *default*
        kernel             : *default*
        kernelopts         : *default*
        mac                : *default*
        maxmem             : 500
        memory             : 300
        netvm              : None
        pci_strictreset    : True
        pcidevs            : ['02:00.0']
        provides_network   : True
        template           : f32-net
        qrexec_timeout     : *default*
        updateable         : *default*
        vcpus              : *default*"
````

but we cannot uses 'provide_network' in our salt file. 
We must uses 'provide-network'.

It is not consistent with the others properties.
It is not consistent neither with the shell command qvm-prefs.

**Comment by DemiMarie** [comment]
Marking as a documentation bug (which is still a bug!).  Also, `Invalid key!` is an exceedingly unhelpful error message.  We can (and should!) do better.

**Comment by p1llule** [comment]
tbh `Invalid key!' is at least something : If you use provides_network in a .sls file, `sudo qubesctl --show-output [...]` returns 0, so you cannot rely at all on it to return an error in this case.

**Comment by DemiMarie** [comment]
> tbh `Invalid key!` is at least something : If you use provides_network in a .sls file, `sudo qubesctl --show-output state.apply [...]` returns 0, so you cannot rely at all on it to return an error in this case.

Salt’s error handling is notoriously bad.  I wonder if this is a bug in our code, or a bug in upstream Salt.
