### ISSUE TITLE
Asus UX331U touchpad issues

### ISSUE THREAD

**Issue by maltfield** [QubesOS/qubes-issues#6611]
**Qubes OS version**

R4.0

**Affected component(s) or functionality**

Touchpad pointer device

**Brief summary**

The touchapd on the Asus ux331 has numerous issues and is basically unusable.

**How Reproducible**

The issue is not immediate when first booting the laptop, but after some number of hours the touchapd has issues

**To Reproduce**

1. Install QubesOS on Asus UX331 laptop
2. Use touchapd for some number of hours
3. The issue occurs

**Expected behavior**

I should be able to use my touchpad like a normal touchpad.

**Actual behavior**

 * after some time, a single click on the touchpad is interpreted by the system as several rapid clicks (~6 clicks). For example, if I try to touch the top of a window and drag it, the >2 clicks makes the window maximized. If I try to click in the middle of a paragraph, then the entire word or line or paragraph is selected, depending on the number of clicks that are erroneously sent. To know how many clicks, I did a control+click on a link in firefox. This opens ~6 tabs. Of course, if I do the same test with a mouse, exactly one tab opens -- as expected.

 * sometimes, the touchpad is entirely unresponsive. After ~5 minutes, it suddenly works again.

In all cases, rebooting the laptop fixes the issues.

**Screenshots**

**Additional context**

From dom0

```
[root@dom0 ~]# xinput --list
...
ELAN1200:00 04F3:309C Mouse
ELAN1200:00 04F3:309C Touchpad
```

**Solutions you've tried**

Rebooting the computer. It works every time, but I can't reboot my computer 2-6 times per day to make my touchpad work like normal again..

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

 * https://github.com/QubesOS/qubes-issues/issues/6540

**Comment by lubellier** [comment]
Hi @maltfield ,
please see the ELAN1200 information on the ArchLinux wiki [Asus Laptop](https://wiki.archlinux.org/title/Laptop/ASUS) page. 

Maybe the [#1543769 issue](https://bugzilla.redhat.com/show_bug.cgi?id=1543769) could help you...

**Comment by techge** [comment]
I guess this can get closed then, OP reacted with thumbs up...

**Comment by maltfield** [comment]
OP here. I was not able to fix this issue. I used a mouse.

And I've since ditched the Asus for a ThinkPad. It works much better with QubesOS..
