### ISSUE TITLE
AMD Ryzen virtualization support not working

### ISSUE THREAD

**Issue by rzqb** [QubesOS/qubes-issues#6615]
**Qubes OS version: R4.1 / 4.1.0 alpha20201014**

**Affected component(s) or functionality**
hardware virtualization

**Brief summary**
I installed R4.1 on a AMD Ryzen 5 4500U system [(ASRock Mars 4500U)](https://www.asrock.com/nettop/AMD/Mars%204000U%20Series/index.asp).
SVM is enabled in BIOS/UEFI.
Still, Qubes cannot start any VMs.
The error message says 
> Failed to start an HVM qube with PCI devices assigned - hardware does not support IOMMU/VT-d/AMD-Vi

**How Reproducible**
Every time.

**To Reproduce**

1. Install R4.1 on the mentioned system
2. Start Qubes.

**Expected behavior**
Virtualization support should be recognized and used.

**Actual behavior**
Virtualization support is not recognized.

**Screenshots**

**Additional context**
Virtualization support of the hardware could be confirmed by executing the command
> cat /proc/cpuinfo

with a current ubuntu on the same hardware:
Flag "svm" is reported.

On the other side, this flag is not supported when running the same command on Qubes R4.1.

**Solutions you've tried**

None found yet.
dom0 can't be updated to the latest kernel because of sys-net and sys-firewall not starting.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

**Comment by herypt** [comment]
You need to have both SVM and IOMMU support enabled. Try to find an option for IOMMU/AMD-Vi in your BIOS and enable it.

**Comment by rzqb** [comment]
Thanks, I was under the impression IOMMU would be implied with the activation of SVM.
The BIOS doesn't seem to have an option named IOMMU or AMD-Vi, so I assume the motherboard doesn't support it.
Too bad :)

So this issue can be closed.
