### ISSUE TITLE
Create "Policy Manager" GUI

### ISSUE THREAD

**Issue by ninavizz** [QubesOS/qubes-issues#6616]
**The problem you're addressing (if any)**
Per discussions with Marek and a 2020 funding award, enabling users to modify policies in a GUI experience is sought. As such, I have been asked to design "a Policy Manager" UI. 

**Describe the solution you'd like**
Something intuitive, easy to self-learn, and that nicely dovetails into the new `dvm` CLI system. What that may look like, I am creating this issue to focus on helping me discern. :)

**Where is the value to a user, and who might that user be?**
In the most recent _App Menu_ survey, >2/3 of all +400 respondents desire an intuitive UI, and to not have to depend on CLI to engage with OS controls. In our general user survey that as-of this writing has received 5,300 complete responses, only 8.1% of all users said they prefer to engage with the OS at the CLI level. While 60% said they were comfortable with both CLI and UI tools, 23% of all users said they preferred to interact with a computer's OS through UI tools. 

Quoting one survey respondent: "I am comfortable with CLI but should never be forced to use it."

For the broader sustainability of the Qubes OS project, it has also been observed that Qubes needs to become easier for folks to adopt—both Linux-native and Windows/Mac folks. Likewise, to vulnerable users who may not be established security wonks. 

For all of these reasons, a clear "Gateway UI" to surface access and permissions between isolation domains, feels critically important. 

**Describe alternatives you've considered**
Tears. The CLI, which regrettably is not discoverable to non-technical folks.

**Additional context**
Many issues had previously been filed against specific concerns, that this issue can nicely answer for. Please feel free to tag this Issue, if you see that opportunity in another issue!

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
#6602 #3904 #3527 maybe #3412 and #6173 ??

**Comment by ninavizz** [comment]
Per a great idea from @SvenSemmler I created a discussion thread for folks to chat ideas and generally brainstorm on this topic, such that I might be able to use this GitHub ticket, more to track the task and to solicit feedback. w00t!

https://qubes-os.discourse.group/t/policy-manager-gui-why-how-what/4079

**Comment by ninavizz** [comment]
Note: A starting point that would be very helpful, would be if someone could plop into this issue a page from the docs with a DVM commands glossary/lookup? Assuming such a manifest of "All you can do with DVM policies!" exists?

**Comment by andrewdavidwong** [comment]
Duplicate of #4721

**Comment by andrewdavidwong** [comment]
This appears to be a [duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Comment by ninavizz** [comment]
@andrewdavidwong It is honestly not my intent to create duplicate issues. I do search for them. I just don't search with the terms often used in the titles. I don't want to be creating more work for you. I literally did a search for "Policy Manager" yesterday and did not see that issue in the search results. :(

**Comment by andrewdavidwong** [comment]
> @andrewdavidwong It is honestly not my intent to create duplicate issues. I do search for them. I just don't search with the terms often used in the titles. I don't want to be creating more work for you. I literally did a search for "Policy Manager" yesterday and did not see that issue in the search results. :(

No worries. Not a big deal. :slightly_smiling_face:
