### ISSUE TITLE
R4.1 Ultra slow perfomance on Sandy Bridge laptops with xen-acpi-processor enabled

### ISSUE THREAD

**Issue by ghost** [QubesOS/qubes-issues#6617]
**Qubes OS version**

4.1

**Affected component(s) or functionality**

Whole system

Disable everything while install system (audio/gui domain, disposable vms, whonix etc)
Only Debian-10 template, sys-net and sys-firewall.
Start any phv vm  ~ 16-20 sec, hvm x2 slower.
Any ideas how to fix and why it happens ?
Any xen tweaks or patches?
Thanks.

**Comment by marmarek** [comment]
You may be victim of #6174. But also, check Xen options (`xl info` -> `xen_commandline`) - add `ept=exec-sp` if you don't  have it already (you can add it in `/etc/default/grub` + `grub2-mkconfig -o /boot/grub2/grub.cfg`).

**Comment by 0rb677** [comment]
Thanks @marmarek will try

**Comment by DemiMarie** [comment]
> You may be victim of #6174. But also, check Xen options (`xl info` -> `xen_commandline`) - add `ept=exec-sp` if you don't have it already (you can add it in `/etc/default/grub` + `grub2-mkconfig -o /boot/grub2/grub.cfg`).

What does that flag do?

**Comment by marmarek** [comment]
> What does that flag do?

https://xenbits.xen.org/docs/unstable/misc/xen-command-line.html#ept
