### ISSUE TITLE
New Qubes OS 4.0.4 installation can't update dom0: unsigned `qubes-mgmt-salt-config-4.0.25-1.fc25`

### ISSUE THREAD

**Issue by QuriousCube** [QubesOS/qubes-issues#6619]
**Qubes OS version**
```
$ cat /etc/qubes-release 
Qubes release 4.0 (R4.0)
```

**Affected component(s) or functionality**
Update of dom0

**Brief summary**
Fresh install of Qubes OS 4.0.4 can't update dom0 because `qubes-mgmt-salt-config-4.0.25-1.fc25.noarch.rpm` is not signed.

**How Reproducible**
3 people in discourse have this issue. This issues seems to occur regardless if the update uses Tor.
See: https://qubes-os.discourse.group/t/unable-to-update-dom0-on-fresh-install-of-4-0-4/4102

**To Reproduce**

1. Install Qubes OS 4.0.4 with .iso file downloaded today
2. Use "Qubes update" tool to update dom0

**Expected behavior**
- Update dom0 without any problem

**Actual behavior**
- Update fails with error: `Domain sys-whonix sent not signed rpm: qubes-mgmt-salt-4.0.25-1.fc25.noarch.rpm`

**Screenshots**

**Additional context**

[Error for 1st attempt](https://github.com/QubesOS/qubes-issues/files/6506222/attempt1.txt)
[Error for 2nd attempt](https://github.com/QubesOS/qubes-issues/files/6506223/attempt2.txt)
[`sudo dnf clean all` and then get error from attempt 3](https://github.com/QubesOS/qubes-issues/files/6506224/dnf_clean_attempt3.txt)

**Solutions you've tried**
- In dom0 terminal, run `sudo dnf clean all`. Reboot. Use "Qubes update" tool. Get similar error.
- In dom0 terminal, run `sudo qubes-dom0-update`. Get similar error.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

**Comment by chihoko** [comment]
Just installed 4.0.4 to evaluate Qubes and hitting the same issue. Tried all the steps above. Unable to proceed without updates.

**Comment by icequbes1** [comment]
With a Qubes 4.0.4 fresh install (rpm-4.13), it seems rpms on or after around May 11 2021 show a different result for `rpm -K` output:

- Good (Oct 2020): `qubes-mgmt-salt-config-4.0.24-1: rsa sha1 (md5) pgp md5 OK`
- Good (March 18 2021): `rpm-4.14.2.1-3: rsa sha1 (md5) pgp md5 OK`
- Good (May 5 2021): `rpm-4.14.2.1-5: rsa sha1 (md5) pgp md5 OK`
- Bad (May 11 2021): `qubes-mgmt-salt-config-4.0.25-1: rsa sha1 md5 OK`

`qubes-receive-updates` (from qubes-core-dom0-linux-4.0.28-1) doesn't recognize the `rsa sha1 md5 OK` output as acceptable based on its regex.

**Comment by marmarek** [comment]
It correctly refuses this output - it says the package isn't signed properly. The issue is that new packages are signed in v4 format that old rpm can't understand; we're adjusting the signing scripts to use old format for R4.0 dom0 updates, and will re-sign all affected packages.

**Comment by andrewdavidwong** [comment]
I am not experiencing this on an up-to-date R4.0 installation. Does it only affect brand new installations when trying to perform the initial update?

**Comment by DemiMarie** [comment]
> I am not experiencing this on an up-to-date R4.0 installation. Does it only affect brand new installations when trying to perform the initial update?

Correct.

**Comment by marmarek** [comment]
All packages in the repository are re-signed in the correct format already. It may take few hours to have them propagate to all the mirrors.
