### ISSUE TITLE
R4.1: Switch to our fork of RPM once Fedora 32 goes EOL

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#6622]
**Qubes OS version (if applicable)**

R4.1

**Affected component(s) or functionality (if applicable)**

dom0 updates

**Brief summary**

Qubes OS has a hardened fork of RPM that is used for R4.0 dom0 updates.  We should use similar changes for R4.1 updates.

There are several additional improvements that may be possible for R4.1.  For instance, we may be able to rip out support for v3 signatures.

**Additional context**

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

**Comment by DemiMarie** [comment]
Fedora 32 has reached end-of-life and we should probably go ahead and switch.

**Comment by andrewdavidwong** [comment]
I just realized: Since this is for 4.1, it wasn't actually necessary to wait until F32 reached EOL, was it? At least not for user stability reasons, since there is no expectation of such stability in an in-development release. But if waiting facilitates development or testing, then never mind.

**Comment by marmarek** [comment]
> Since this is for 4.1, it wasn't actually necessary to wait until F32 reached EOL, was it?

The main reason for the wait, is to not miss any Fedora's native rpm update, that other parts of the base system may rely on. Now when F32 is EOL, we know there won't be any anymore.

**Comment by DemiMarie** [comment]
Nope.  We use rpmcanon for every RPM package that reaches dom0 now.
