### ISSUE TITLE
Qube Manager unable to select 'Template' and 'Networking'

### ISSUE THREAD

**Issue by Tonux599** [QubesOS/qubes-issues#6626]
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
Qube Manager

**Brief summary**
In Qube Manager *only* (qvm-prefs functions fine) no netVM's or templates appear to be selectable for defaults (under Settings -> Global Settings), for Create new qubes or for existing Qube's when Right-click -> Qube Settings.

When viewing the drop down to select your desired Template and/or Networking, only 'none' or 'default (none)' appears. This is despite there being template qubes and qubes with 'Provides network' being available.

**How Reproducible**
Persistent

**To Reproduce**

Steps to reproduce the behaviour:
1. Have available templates and netvm's configured correctly.
2. Create new Qube in Qube Manager
3. For 'Template' and 'Networking' drop-downs, observe non-existent options.

**Expected behavior**
'Template' and 'Networking' drop downs should be populated with available templates and netvm's.

**Actual behavior**
They are not.

**Screenshots**
Available on request.

**Additional context**
Setting via `qvm-prefs` works fine.

**Solutions you've tried**
System reboot.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
None.

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
None

**Comment by unman** [comment]
I cant reproduce this.
Have you made any changes to the default installation?
Have you, for example, set the internal flag on any templates or netvms?

**Comment by Tonux599** [comment]
Ah, I had the internal flag set to true for all of them as I was getting annoyed with fighting to remove unwanted menu entries for templates and netvms. Unsetting internal flag resolves issue.

Thanks @unman :+1:

**Comment by unman** [comment]
#6604 aims to make the meaning of "internal" clear
