### ISSUE TITLE
Qrexec ask policy resolution fails with disposable VM target

### ISSUE THREAD

**Issue by jevank** [QubesOS/qubes-issues#6629]
**Qubes OS version**
4.1

**Affected component(s) or functionality**
qubes-qrexec-policy-daemon

**Brief summary**
Choosing disposable target on Ask request fails.

**How Reproducible**
Always

**To Reproduce**
1. Create policy like
qubes.OpenInVM * @anyvm @dispvm ask

2. try qvm-open-in-dvm

**Expected behavior**
Disposable VM starts

**Actual behavior**
Daemon exception

**Comment by marmarek** [comment]
Uh, I see a race condition between you two ;)
