### ISSUE TITLE
Qubes Update tool: Inform the user when no updates are found

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#6632]
_This issue was reported by **fiftyfourthparallel** on the Qubes Forum in [this post](https://qubes-os.discourse.group/t/was-there-a-dom0-update-for-r4-0-in-the-last-few-days/4066/16?u=adw)._

-----

**Qubes OS version**
`R4.0`

**Affected component(s) or functionality**
Updating via Qubes Updater

**Brief summary**
When there are no dom0 updates available, the Qubes Update tool prints:

```
Updating dom0

local:
    ----------

``` 

This doesn't provide enough information and can be confusing for new users and especially those switching from the CLI `qubes-dom0-update` (due to the current situation with metadata), because they don't know what to expect and may not encounter an update for a long period due to the relatively sparse and irregular updates R4.0 dom0 receives. The lack of reporting could lead to confusion, like in [this post](https://qubes-os.discourse.group/t/was-there-a-dom0-update-for-r4-0-in-the-last-few-days/4066/16). A simple addition of "No updates were found" to the printed message would be enough.

**How Reproducible**
100%

**To Reproduce**
Run Qubes Update tool for dom0 after all packages have been updated.

**Expected Behavior**
Inform the user that no updates were found.

**Actual Behavior**
```
local:
    ----------

```

**Comment by andrewdavidwong** [comment]
Related issues: #6299, #6590

**Comment by andrewdavidwong** [comment]
The weird thing is that using `qubesctl` *does* already give you this feedback. For example, it says, `Comment: System is already up-to-date`. So maybe this is simply a matter of passing that through to the GUI tool.

**Comment by marmarta** [comment]
This is fixed by https://github.com/QubesOS/qubes-desktop-linux-manager/pull/139
