### ISSUE TITLE
Updater Nits (from AppMenu survey)

### ISSUE THREAD

**Issue by ninavizz** [QubesOS/qubes-issues#6633]
**The problem you're addressing (if any)**
In our recent AppMenu user survey, folks provided an abundance of feedback on Qubes on general—not just on the AppMenu. Some of those points of feedback, were on the updater experience. 

My first path to document these concerns, is to look for related issues. When that fails (which it often will, because I don't know all the technical details behind these things, whereas others do) I will document those things, here. 

I may also document repeat requests here, too, as a simple measure of community interest. 

**Where is the value to a user, and who might that user be?**
Keeping a reasonably secure operating system up to date is critical to retaining that "reasonably secure" qualifier.

**Comment by ninavizz** [comment]
> After installing qubes-4.0.3, three or even four months after the release of qubes 4.0.4 I stumbled over the shy hint, that I had to do the update from Q-4.0.3 to Q-4.0.4 by myself. No Q-Manager-gui tool alerted me.

**Comment by ninavizz** [comment]
Sorry Andrew, I got a better idea for organizing this info—this issue can get deleted. :D

**Comment by andrewdavidwong** [comment]
> Sorry @andrewdavidwong I got a better idea for organizing this info—this issue can get deleted. :D

GitHub doesn't allow us to delete issues, which is probably a good thing. Instead, I think it would be appropriate to just close this as "invalid" since this particular issue would not have passed our [issue tracking guidelines](https://www.qubes-os.org/doc/reporting-bugs/#issue-tracker-guidelines) anyway.
