### ISSUE TITLE
yum.qubes-os.org is down

### ISSUE THREAD

**Issue by kototama** [QubesOS/qubes-issues#6637]
yum.qubes-os.org is currently down. I checked on multiple machine and with this website: https://downforeveryoneorjustme.com/yum.qubes-os.org?proto=https

**Comment by brendanhoar** [comment]
Outage may have been temporary...I couldn't connect about 30 minutes ago, but updates are now downloading.

**Comment by DemiMarie** [comment]
Still down for me

**Comment by unman** [comment]
On Tue, May 25, 2021 at 03:59:03PM -0700, Demi Marie Obenour wrote:
> Still down for me
> 

@andrewdavidwong - there was a brief outage as far as I can see.
I've asked for monitoring to be upped to every 10 minutes.
Can you close and unpin.

**Comment by icequbes1** [comment]
Is GitHub the preferred way to report these types of issues?.

**Comment by icequbes1** [comment]
From what I can tell, the issue was limited to less than a day. Unless it appeared to be an extended outage I wouldn't want to raise unnecessary burden due to temporary/transient issues for the team.

**Comment by kototama** [comment]
> From what I can tell, the issue was limited to less than a day. Unless it appeared to be an extended outage I wouldn't want to raise unnecessary burden due to temporary/transient issues for the team.

It just happened the night were I needed to restore backups after an new installation but could not because I could not update. I thought it was worth opening an issue, specially if other experienced the same problem.

**Comment by andrewdavidwong** [comment]
> Is GitHub the preferred way to report these types of issues?

Yes, this is the appropriate place to report any problems in the Qubes OS Project infrastructure.
