### ISSUE TITLE
Better advice on "Choosing Hardware"

### ISSUE THREAD

**Issue by deeplow** [QubesOS/qubes-issues#6638]
**Affected component(s) or functionality**

website

**Brief summary**

I'd like there to be a paragraph of sensible high-level advice on ["Choosing hardware"](https://www.qubes-os.org/doc/system-requirements/#choosing-hardware) section of the website. This is such a key issue [according to the survey](https://www.qubes-os.org/news/2020/11/26/qubes-survey-results/) ("hardware compatibility was something a lot of people mentioned in the “reasons for not using Qubes/reasons for stopping using Qubes” questions.").

**Expected behavior**

Having there something along the lines of what @SvenSemmler [said on the forum](https://qubes-os.discourse.group/t/recommendation-for-quiet-laptop-low-zero-fan-noise/4215/2):

> Out of my own experience and also watching the HCL reports as they flow
in I would highly recommend to NOT go for the newest laptop with the
latest processor etc.
> 
> The older your hardware gets the better it will be supported by Qubes
OS. Concretely: if you are planing to run R4.0.4 I would recommend to
look for something that was around and on the market when Fedora 25 was
released.

**Actual behavior**

Just shows links to the HCL and certified hardware.

**Screenshots**

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

* https://www.qubes-os.org/doc/system-requirements/#choosing-hardware

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

None

**Comment by andrewdavidwong** [comment]
Care to take a stab at a PR, @deeplow?

**Comment by ddevz** [comment]
Some notes:
-  For laptops there is the 2 certified laptops at https://www.qubes-os.org/doc/certified-hardware/#qubes-certified-laptops . So if you are trying to choose a laptop, I don't see how that is vague.  Perhaps people are wondering "will it work with my *pre-existing* hardware?"
-  For desktops there is much less certainty in choosing new hardware.  For example, a end user will wonder which keyboards will work with a USB -> PS/2 adapter (most? some? few? (i personally know it is not all)).  Similarly they may wonder if most/all/some/few ps/2 PCIe cards will work.  (not all motherboards have ps/2 connectors anymore)
-  The HCL lists dell systems by model number, but I've heard that dell re-negotiates and re-decides on what parts to use in a specific model on a weekly basis, meaning for dell you not only need to know the model number but you also need to know the vintage (I.E. which week it was bought in).  Of course this is not helpful for someone looking to buy a QubesOS computer *next* week.

**Comment by deeplow** [comment]
Should this be closed as the associated PR [was closed](https://github.com/QubesOS/qubes-doc/pull/1147)? Or does someone else want to take another stab at it?

**Comment by andrewdavidwong** [comment]
I think it's fine as is. You discovered that almost everything you wanted to add is already at the top of the page, which mostly confirms this. If anyone wants to submit a PR, we can reopen.
