### ISSUE TITLE
Cache qrexec policy evaluation results

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#6639]
**The problem you're addressing (if any)**
Currently, qrexec calls require re-evaluating the policy every time.  This is slow.

**Describe the solution you'd like**
qrexec-policy-daemon should cache the results of policy evaluation.  The results cache must be invalidated (by qubesd) whenever a domain is created or destroyed.

**Where is the value to a user, and who might that user be?**

All users will benefit from improved qrexec performance.

**Describe alternatives you've considered**

We could port qrexec to Rust or another fast, safe language, such as OCaml.

**Additional context**

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

**Comment by marmarek** [comment]
>  Currently, qrexec calls require reloading and re-evaluating the policy every time. This is slow.

No, it doesn't. This is the main (the only?) reason why we added the daemon in the first place.

**Comment by DemiMarie** [comment]
> > Currently, qrexec calls require reloading and re-evaluating the policy every time. This is slow.
> 
> No, it doesn't. This is the main (the only?) reason why we added the daemon in the first place.

Oops!  I will re-open the issue with a better titile.

**Comment by marmarek** [comment]
Ah, I see. Will just cache will really improve anything? It sounds like only improving repeated the same call, which is not really a common case (maybe besides `qubes.ConnectTCP` in some cases).
Anyway, when working on qrexec performance optimizations, I propose to _start_ with measuring what phase takes how much time specifically, and only then focus on optimizing slowest parts. This is how we came up with the policy daemon with pre-loaded policy.
And in fact, I've just checked, policy evaluation takes about 0.5ms on a not-so-fast test laptop. On the other hand, getting info about existing VMs on the same system (`get_system_info()` call), takes 86ms. Could policy evaluation be faster? Maybe. But clearly it is not the place that's worth optimizing right now.
To be clear - do not take the above as a definitive info what it's worth optimizing, that's just a single place checked.

**Comment by DemiMarie** [comment]
> Ah, I see. Will just cache will really improve anything? It sounds like only improving repeated the same call, which is not really a common case (maybe besides `qubes.ConnectTCP` in some cases).

`qubes.ConnectTCP` (and variations thereof) are indeed the case I was thinking of when I made this proposal.  That said, it is probably a rather poor example: if we want `qubes.ConnectTCP` to be able to keep up with a web server like NGINX, we will almost certainly need to multiplex hundreds or even thousands of connections over a single vchan.

> Anyway, when working on qrexec performance optimizations, I propose to _start_ with measuring what phase takes how much time specifically, and only then focus on optimizing slowest parts. This is how we came up with the policy daemon with pre-loaded policy.

Absolutely!

> And in fact, I've just checked, policy evaluation takes about 0.5ms on a not-so-fast test laptop. On the other hand, getting info about existing VMs on the same system (`get_system_info()` call), takes 86ms. Could policy evaluation be faster? Maybe. But clearly it is not the place that's worth optimizing right now.

Indeed.  Could we merge the policy daemon into qubesd?  That would the IPC overhead and marshaling overhead.

**Comment by marmarek** [comment]
> Could we merge the policy daemon into qubesd? That would the IPC overhead and marshaling overhead.

I'd rather not. Policy handling is in separate process (and even separate python module) for a reason. qubesd is a complex beast, I don't want its code to be directly involved in policy evaluation - something that is a critical action, exposed to all VMs.

Anyway, this is still wrong approach to handle this (supposedly?) a problem. Picking a random part and trying to optimize it at all costs, won't get us anywhere. It will lead to a lot of wasted time, quite likely with negligible results in the end. I've explained the proper approach above already.

Plus, I suspect you base your guesses on R4.0 system, while qrexec in R4.1 already got major performance improvements.

So, I'm closing this now, as it not really productive.
