### ISSUE TITLE
Nice OS!!

### ISSUE THREAD

**Issue by noobtec** [QubesOS/qubes-issues#6644]
Works well.

Could smb. please add:

* Checkbox to disable label colors on GUI, i'm fine with [label] text...;
* Checkbox to automatically fire Ctrl+Shift+(c|v) and then Ctrl+(c|v) on Ctrl+(c|v)
* Qubes Windows Tools for Windows 10

That would be so nice, thanks!

**Comment by noobtec** [comment]
And i've seen "Convert To Trusted Img" in context menu. Does a "Check With AV" VM exist?

**Comment by andrewdavidwong** [comment]
Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this does not appear to be suitable for `qubes-issues`. Thank you for your understanding.
