### ISSUE TITLE
Building xorg-x11-drv-intel fails because extra source dependency is missing

### ISSUE THREAD

**Issue by kalkin** [QubesOS/qubes-issues#6645]
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
QubesOS building process

**Brief summary**
The component `xorg-x11-drv-intel` can not be build because it dependency https://ftp.qubes-os.org/distfiles/xf86-video-intel-20210126.tar.bz2 does not exists on the server.

**How Reproducible**
```bash
cd qubes-builder
rm qubes-src/xorg-x11-drv-intel/xf86-video-intel-20210126.tar.bz2
make get-sources-extra COMPONENTS="xorg-x11-drv-intel"
```

**Expected behavior**
The needed file is downloaded

**Actual behavior**
404 Not Found

**Comment by marmarek** [comment]
Fixed.
