### ISSUE TITLE
High CPU usage when idle on AMD Ryzen laptop without dGPU

### ISSUE THREAD

**Issue by na--** [QubesOS/qubes-issues#6647]
**Qubes OS version**
`R4.1`

**Are you using any [testing](https://www.qubes-os.org/doc/testing/) repositories? If so, please list them and where they are enabled (i.e., dom0, TemplateVM, or StandaloneVM).**
Yes, installed latest updates in `current-testing` after noticing the issue on `current`.

**Are you providing feedback about a specific package or packages in testing? (If so, please list the package(s) here and [provide feedback in `updates-status`](https://www.qubes-os.org/doc/testing/#providing-feedback), linking to this issue.)**

No

**Affected component(s) or functionality**

I'm not sure, either xen or something in dom0?

**Brief summary**

I installed QubesOS 4.1 on a new laptop with Ryzen 7 4800H (without a discrete GPU) and the CPU usage is very abnormal. Even when only dom0 is running, without any other VMs and doing nothing on its own, idle CPU thermals are also very high, 60-70 degrees Celsius and laptop fans constantly spinning. I see regular CPU usage spikes in `xl top`, though not in dom0 `htop`. Starting AppVMs seems to affect this, even if they are subsequently stopped, idle CPU temperature doesn't drop to previous levels.

**How Reproducible**

For me, every time, but I haven't seen anyone describing exactly the same problems in another issue, so :man_shrugging:

**To Reproduce**

:man_shrugging:

**Expected behavior**

A smooth experience with no/low CPU usage and fan noise when idle. I tried Xubuntu on the same hardware and got no CPU usage or fan noise when idle, steady ~40C CPU temperatures after the initial OS startup.

**Actual behavior**

Laptop fans never stop spinning, going only from medium power on idle to high power when I actually do something... Performance wise, in contrast to the people in https://github.com/QubesOS/qubes-issues/issues/6055, I **don't** actually get any visual stutters or mini lock-ups after I installed the `amdgpu` package. The machine is mostly usable if it's plugged in, even if very annoying to use with the noise and probably severely under-performing. And yeah, I am not accustomed to great battery life with previous QubesOS versions, but this is more than a bit worse than usual :sweat_smile: 

**Screenshots**

![Screenshot](https://user-images.githubusercontent.com/3336773/119956897-39ccca00-bfaa-11eb-8935-e82f84fe3a63.png)

**Additional context**

- The problem seems to be worse after I start an AppVM, even if I stop it afterwards. If I set `qvm-prefs <app-vm> autostart false` on `sys-net`, `sys-firewall` and `sys-usb`, then CPU thermals hover around 53C. That is worse than the ~40C I got in Xubuntu, but still better than what I get after I start an AppVM. When I start another VM, even if I then immediately stop it afterwards, the CPU temperature never drops below ~62C again... 
- It doesn't seem to matter if I've skipped the X login screen and logged directly into a VT. CPU thermals are still high after I start an AppVM, even if I stop it afterwards.
- `sudo htop` on an idle dom0 didn't reveal anything strange, as far as I can see - CPU usage at near 0%, while `xl top` shows occasional spikes in dom0 CPU usage... That said, the spikes are minor, climbing to a single-digit percentage every second refresh, so I'm not sure they can cause the symptoms I see :man_shrugging: 
- Not sure if it's related, by I also can't suspend the laptop - trying that results in a blank screen where nothing works, not even switching to a VT with Ctrl+Alt+Fx, though the CPU fans keep spinning pretty hard all the while, and I have to do a hard shutdown of the laptop
- I have an external screen, though that doesn't seem to matter, the issue occurs even when I don't plug it in
- I also experienced some visual stutters after the initial install on the laptop, though these were fixed when I installed `xorg-x11-drv-amdgpu` in dom0

[dmesg.log](https://github.com/QubesOS/qubes-issues/files/6559520/dmesg.log)
[xl-dmesg.log](https://github.com/QubesOS/qubes-issues/files/6559521/xl-dmesg.log)

**Solutions you've tried**

- `journalctl`, `dmesg`, `xl dmesg`, `powertop`, `htop`, `xl top`, `cat Xorg.0.log`, `lspci -nnk` didn't reveal anything strange besides the minor discrepancy between `xentop` and dom0 `htop`, though I am not well versed in monitoring the performance of a xen+linux system... :disappointed: 
- I experience this issue with the 5.10 kernels as well as the `latest` 5.12
- Tried adding various combinations of suggested xen and kernel boot options from https://github.com/QubesOS/qubes-issues/issues/6055 - nothing seemed to help at all, though there are so many things I don't understand there that I might have missed something important
- Tried to downgrade the dom0 xen packages to 4.14.0-4 - this caused my system to completely lock up a few seconds after I log in the GUI (though not when I did so in a VT)

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
- https://www.qubes-os.org/doc/hardware-troubleshooting/
- https://www.qubes-os.org/doc/gui-troubleshooting/

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
- https://github.com/QubesOS/qubes-issues/issues/6055, though I am not completely sure, since the symptoms seem different
- https://github.com/QubesOS/qubes-issues/issues/6066 - I experience some of the same suspend issues, though I am not sure if they are related to this one

**Comment by bigdx** [comment]
Although with Xen 4.15 this issue persists?

**Comment by na--** [comment]
The issue still persists to this day, with the latest QubesOS 4.1 `testing` updates. However, [qubes-vmm-xen](https://github.com/QubesOS/qubes-vmm-xen/) is still on Xen 4.14, and I don't know how to switch to Xen 4.15 and haven't had the time to look into it, so I don't know if the issue is still present with Xen 4.15... :man_shrugging:

**Comment by DemiMarie** [comment]
@marmarek will have to take this one; he’s expert on such low-level matters.

**Comment by na--** [comment]
I re-read my original issue description above, and all of it is still correct, except parts of this:

> Performance wise, in contrast to the people in #6055, I don't actually get any visual stutters or mini lock-ups after I installed the amdgpu package.

I still don't normally get visual stutters or lock-ups during regular laptop use. The CPU temperature and fan speeds are high, but the laptop is mostly usable. Unfortunately, a few times my system has entered a strange state where the stutters start happening - everything locks up for a few seconds and if I start `glxgears` in dom0, you can see the gears lock up and the FPS drop below 60 pretty often, _even_ if I close everything else on the system afterwards and nothing is running... :confused: A full restart fixes the problem.

Usually this issue happens when I'm doing something very CPU intensive, e.g. video conferencing with screen and camera sharing and people on the call tell me I've started chopping up. I haven't been able to diagnose the issue, because I'm usually in the middle of something important (e.g. middle of a call) and I have to restart quickly and resume it, but I'll try to find something strange in the logs the next time it happens.

**Comment by DemiMarie** [comment]
@na-- Can you trigger this issue with a trivial program that just loops forever and eats CPU?  Also, does switching to another virtual terminal (with Ctrl+Alt+F2) help?

**Comment by na--** [comment]
> Can you trigger this issue with a trivial program that just loops forever and eats CPU?

No, or at least I haven't triggered it with a small Go program that spawns a goroutine for every CPU core and just loops and adds numbers for over an hour. even while using the laptop for other things at the same time... :disappointed: 

> Also, does switching to another virtual terminal (with Ctrl+Alt+F2) help?

Haven't tried this when the system ended in that stuttering state, but it doesn't help the high CPU usage/fan noise I reported in the original issue post.

**Comment by na--** [comment]
My laptop entered the stuttering state again today, in the middle of a video call again. This time I captured `sudo journalctl -b` in dom0 before I restarted, and these are the interesting bits:
```
Jul 28 11:01:01 dom0 run-parts[23916]: (/etc/cron.hourly) finished 0anacron
Jul 28 11:13:09 dom0 kernel: amdgpu 0000:04:00.0: amdgpu: message: TransferTableSmu2Dram (28)         param: 0x00000007 is timeout (no response)
Jul 28 11:13:09 dom0 kernel: amdgpu 0000:04:00.0: amdgpu: Failed to export SMU metrics table!
Jul 28 11:13:14 dom0 kernel: amdgpu 0000:04:00.0: amdgpu: Msg issuing pre-check failed and SMU may be not in the right state!
Jul 28 11:13:14 dom0 kernel: amdgpu 0000:04:00.0: amdgpu: Failed to export SMU metrics table!
Jul 28 11:13:19 dom0 kernel: amdgpu 0000:04:00.0: amdgpu: Msg issuing pre-check failed and SMU may be not in the right state!
Jul 28 11:13:19 dom0 kernel: amdgpu 0000:04:00.0: amdgpu: Failed to export SMU metrics table!
Jul 28 11:13:24 dom0 kernel: amdgpu 0000:04:00.0: amdgpu: Msg issuing pre-check failed and SMU may be not in the right state!
Jul 28 11:13:24 dom0 kernel: amdgpu 0000:04:00.0: amdgpu: Failed to export SMU metrics table!
Jul 28 11:13:29 dom0 kernel: amdgpu 0000:04:00.0: amdgpu: Msg issuing pre-check failed and SMU may be not in the right state!
Jul 28 11:13:29 dom0 kernel: amdgpu 0000:04:00.0: amdgpu: Failed to export SMU metrics table!
Jul 28 11:13:34 dom0 kernel: amdgpu 0000:04:00.0: amdgpu: Msg issuing pre-check failed and SMU may be not in the right state!
Jul 28 11:13:34 dom0 kernel: amdgpu 0000:04:00.0: amdgpu: Failed to export SMU metrics table!
Jul 28 11:13:39 dom0 kernel: amdgpu 0000:04:00.0: amdgpu: Msg issuing pre-check failed and SMU may be not in the right state!
Jul 28 11:13:39 dom0 kernel: amdgpu 0000:04:00.0: amdgpu: Failed to export SMU metrics table!
Jul 28 11:13:44 dom0 kernel: amdgpu 0000:04:00.0: amdgpu: Msg issuing pre-check failed and SMU may be not in the right state!
Jul 28 11:13:44 dom0 kernel: amdgpu 0000:04:00.0: amdgpu: Failed to export SMU metrics table!
Jul 28 11:13:49 dom0 kernel: amdgpu 0000:04:00.0: amdgpu: Msg issuing pre-check failed and SMU may be not in the right state!
Jul 28 11:13:49 dom0 kernel: amdgpu 0000:04:00.0: amdgpu: Failed to export SMU metrics table!
Jul 28 11:13:54 dom0 kernel: amdgpu 0000:04:00.0: amdgpu: Msg issuing pre-check failed and SMU may be not in the right state!
Jul 28 11:13:54 dom0 kernel: amdgpu 0000:04:00.0: amdgpu: Failed to export SMU metrics table!
Jul 28 11:13:59 dom0 kernel: amdgpu 0000:04:00.0: amdgpu: Msg issuing pre-check failed and SMU may be not in the right state!
Jul 28 11:13:59 dom0 kernel: amdgpu 0000:04:00.0: amdgpu: Failed to export SMU metrics table!
Jul 28 11:14:04 dom0 kernel: amdgpu 0000:04:00.0: amdgpu: Msg issuing pre-check failed and SMU may be not in the right state!
Jul 28 11:14:04 dom0 kernel: amdgpu 0000:04:00.0: amdgpu: Failed to export SMU metrics table!
Jul 28 11:14:09 dom0 kernel: amdgpu 0000:04:00.0: amdgpu: Msg issuing pre-check failed and SMU may be not in the right state!
Jul 28 11:14:09 dom0 kernel: amdgpu 0000:04:00.0: amdgpu: Failed to export SMU metrics table!
Jul 28 11:14:14 dom0 kernel: amdgpu 0000:04:00.0: amdgpu: Msg issuing pre-check failed and SMU may be not in the right state!
Jul 28 11:14:14 dom0 kernel: amdgpu 0000:04:00.0: amdgpu: Failed to export SMU metrics table!
Jul 28 11:14:19 dom0 kernel: amdgpu 0000:04:00.0: amdgpu: Msg issuing pre-check failed and SMU may be not in the right state!
Jul 28 11:14:19 dom0 kernel: amdgpu 0000:04:00.0: amdgpu: Failed to export SMU metrics table!
Jul 28 11:14:24 dom0 kernel: amdgpu 0000:04:00.0: amdgpu: Msg issuing pre-check failed and SMU may be not in the right state!
Jul 28 11:14:24 dom0 kernel: amdgpu 0000:04:00.0: amdgpu: Failed to export SMU metrics table!
Jul 28 11:14:29 dom0 kernel: amdgpu 0000:04:00.0: amdgpu: Msg issuing pre-check failed and SMU may be not in the right state!
Jul 28 11:14:29 dom0 kernel: amdgpu 0000:04:00.0: amdgpu: Failed to export SMU metrics table!
Jul 28 11:14:33 dom0 kernel: amdgpu 0000:04:00.0: amdgpu: Msg issuing pre-check failed and SMU may be not in the right state!
Jul 28 11:14:33 dom0 kernel: amdgpu 0000:04:00.0: amdgpu: Attempt to get max GX frequency from SMC Failed !
Jul 28 11:14:35 dom0 kernel: amdgpu 0000:04:00.0: amdgpu: Msg issuing pre-check failed and SMU may be not in the right state!
Jul 28 11:14:35 dom0 kernel: amdgpu 0000:04:00.0: amdgpu: Failed to export SMU metrics table!
Jul 28 11:14:37 dom0 kernel: amdgpu 0000:04:00.0: amdgpu: Msg issuing pre-check failed and SMU may be not in the right state!
Jul 28 11:14:37 dom0 kernel: amdgpu 0000:04:00.0: amdgpu: Failed to disable gfxoff!
Jul 28 11:14:39 dom0 kernel: amdgpu 0000:04:00.0: amdgpu: Msg issuing pre-check failed and SMU may be not in the right state!
Jul 28 11:14:39 dom0 kernel: amdgpu 0000:04:00.0: amdgpu: Failed to export SMU metrics table!
Jul 28 11:14:40 dom0 kernel: amdgpu 0000:04:00.0: amdgpu: Msg issuing pre-check failed and SMU may be not in the right state!
Jul 28 11:14:40 dom0 kernel: amdgpu 0000:04:00.0: amdgpu: Attempt to get max GX frequency from SMC Failed !
Jul 28 11:14:44 dom0 kernel: amdgpu 0000:04:00.0: amdgpu: Msg issuing pre-check failed and SMU may be not in the right state!
Jul 28 11:14:44 dom0 kernel: amdgpu 0000:04:00.0: amdgpu: Failed to export SMU metrics table!
Jul 28 11:14:49 dom0 kernel: amdgpu 0000:04:00.0: amdgpu: Msg issuing pre-check failed and SMU may be not in the right state!
Jul 28 11:14:49 dom0 kernel: amdgpu 0000:04:00.0: amdgpu: Failed to export SMU metrics table!
Jul 28 11:14:54 dom0 kernel: amdgpu 0000:04:00.0: amdgpu: Msg issuing pre-check failed and SMU may be not in the right state!
Jul 28 11:14:54 dom0 kernel: amdgpu 0000:04:00.0: amdgpu: Failed to export SMU metrics table!
Jul 28 11:14:59 dom0 kernel: amdgpu 0000:04:00.0: amdgpu: Msg issuing pre-check failed and SMU may be not in the right state!
Jul 28 11:14:59 dom0 kernel: amdgpu 0000:04:00.0: amdgpu: Failed to export SMU metrics table!
Jul 28 11:15:04 dom0 kernel: amdgpu 0000:04:00.0: amdgpu: Msg issuing pre-check failed and SMU may be not in the right state!
Jul 28 11:15:04 dom0 kernel: amdgpu 0000:04:00.0: amdgpu: Failed to export SMU metrics table!
Jul 28 11:15:09 dom0 kernel: amdgpu 0000:04:00.0: amdgpu: Msg issuing pre-check failed and SMU may be not in the right state!
Jul 28 11:15:09 dom0 kernel: amdgpu 0000:04:00.0: amdgpu: Failed to export SMU metrics table!
Jul 28 11:15:14 dom0 kernel: amdgpu 0000:04:00.0: amdgpu: Msg issuing pre-check failed and SMU may be not in the right state!
Jul 28 11:15:14 dom0 kernel: amdgpu 0000:04:00.0: amdgpu: Failed to export SMU metrics table!
Jul 28 11:15:19 dom0 kernel: amdgpu 0000:04:00.0: amdgpu: Msg issuing pre-check failed and SMU may be not in the right state!
Jul 28 11:15:19 dom0 kernel: amdgpu 0000:04:00.0: amdgpu: Failed to export SMU metrics table!
Jul 28 11:15:24 dom0 kernel: amdgpu 0000:04:00.0: amdgpu: Msg issuing pre-check failed and SMU may be not in the right state!
Jul 28 11:15:24 dom0 kernel: amdgpu 0000:04:00.0: amdgpu: Failed to export SMU metrics table!
...
```

Again, this might be a different bug than https://github.com/QubesOS/qubes-issues/issues/6647#issue-904992159 :man_shrugging: The only other `amdgpu` messages in the logs before that are normal seeming init messages from when the laptop was first booted up.

**Comment by isodude** [comment]
I compiled my kernel with AMD_PMC=y (and also AMD_HSA_AMD=n), compiling it with AMD_PMC=y makes the PMC-driver add quirks and could make your life a bit easier.

I find that on my machine at least running a 5.15 kernel (the new PCI/MSI patches aren't in linux-stable yet, so not in 5.14.10) adding pci=nomsi makes the laptop very crash-resilient. If you would like to test it out to add another datapoint that would be neat. Currently I've described how to do it with linux-5.15-rc5 kernel in the linked issue.

**Comment by na--** [comment]
I forgot to update this a few months ago, when I figured out at least the first part of the issue :disappointed: It turned out that my CPU was constantly at a high temperature and the fans were constantly spinning on high, even while the laptop was idle, because... :drum: for some reason, QubesOS was installed with legacy boot, not with UEFI... :sob: No idea why I installed it like that, and no idea why it mattered so much, but the AMD laptop became much better performing once I changed the install to UEFI... :man_shrugging: 

_FWIW, if anyone has the same problem, this change can be done in-place. Since I didn't want to bother with re-installing, I successfully changed the existing install by roughly following [this guide](https://www.redhat.com/sysadmin/bios-uefi). The only missing (but, in my case, critically important step) in that guide can be found [here](https://unix.stackexchange.com/questions/323677/qubes-clobbered-my-boot-how-can-i-re-enable-efi-booting) and [here](https://unix.stackexchange.com/questions/323677/qubes-clobbered-my-boot-how-can-i-re-enable-efi-booting) - without that minor partition change my laptop didn't boot from the newly minted EFI boot partition :man_facepalming: Needless to say, make sure you have a backup before you do something like this_

Unfortunately, even though the laptop became much more usable, I still kept experiencing the stuttering + eventual crash issue (https://github.com/QubesOS/qubes-issues/issues/6647#issuecomment-888233936) from time to time, generally triggered by high CPU usage (especially video calls). I think this might have been an actual hardware issue though, since it seems like nobody else has hit it so far, while people have hit a bunch of the other AMD GPU issues I had (e.g. the ones with sleep/resume and things like https://github.com/QubesOS/qubes-issues/issues/7648). 

I no longer use that laptop, so I'll close this issue, considering the first part of it was solved by switching to UEFI and the second part might have been a hardware/overheating issue with my specific laptop.
