### ISSUE TITLE
Qubes Windows Tools QWT 4.1-65 seems to have disappeared

### ISSUE THREAD

**Issue by GWeck** [QubesOS/qubes-issues#6648]
**Qubes OS version**

R4.1

**Are you using any [testing](https://www.qubes-os.org/doc/testing/) repositories? If so, please list them and where they are enabled (i.e., dom0, TemplateVM, or StandaloneVM).**

dom0 current testing

**Are you providing feedback about a specific package or packages in testing? (If so, please list the package(s) here and [provide feedback in `updates-status`](https://www.qubes-os.org/doc/testing/#providing-feedback), linking to this issue.)**

Qubes Windows Tools

**Affected component(s) or functionality**

Qubes Windows Tools Version 4.1-65

**Brief summary**

Last December, a preliminary version of Qubes Windows Tools 4.1-65 for Qubes R4.1 was published at https://github.com/0rb677/dotfiles/raw/master/qubes-windows-tools-4.1-65.noarch.rpm. This file is no longer accessible. Clicking on the link throws a 404 error. 

**How Reproducible**

always

**To Reproduce**

1. Go to [Testing Windows and QWT in R4.1](https://qubes-os.discourse.group/t/testing-windows-and-qwt-in-r4-1/1143/55)
2. Click on the link provided there.
3. Observe the error.

**Expected behavior**

The file should be downloadable in order to install the QWT testing version.

**Actual behavior**

No access is possible, and no alternative location is provided.

**Additional context**

If neccessary, I could provide a copy of the rpm file.

**Solutions you've tried**

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

**Comment by fepitre** [comment]
I'm sorry but you are referencing a file not even hosted(built?) by Qubes.

**Comment by andrewdavidwong** [comment]
Closing as "not our bug." If you believe this is a mistake, please leave a comment, and we'll be happy to take another look. Thank you.

**Comment by GWeck** [comment]
Currently this file is the only working QWT installer for Qubes R4.1. Can we do anything to provide it again to users trying to test Windows VMs under R4.1? I'd be glad to help here.

**Comment by andrewdavidwong** [comment]
Not if it was not our file to begin with. (I don't know whether it was.)

**Comment by GWeck** [comment]
It seems to be based on the [qwt-crossbuild](https://github.com/tabit-pro/Qway-qubes-repo/tree/master/qubes-windows-tools) project. I have now idea if or how this is connected with Qubes development. I will try to find out more.

**Comment by GWeck** [comment]
It seems to be based on the [qwt-crossbuild](https://github.com/tabit-pro/Qway-qubes-repo/tree/master/qubes-windows-tools) project. I have now idea if or how this is connected with Qubes development. Maybe this could be used to build the rpm file? I am not familiar with the build environment, so I can't say. If it is possible, it might suffice to just provide a hint to that link.

**Comment by GWeck** [comment]
In order to put this on a more structured appoach, I started a discussion on [Windows support in Qubes](https://qubes-os.discourse.group/t/windows-support-in-qubes/4288), hoping this might lead somewhere.
