### ISSUE TITLE
qrexec policy daemon doesn`t kill disposable vm

### ISSUE THREAD

**Issue by jevank** [QubesOS/qubes-issues#6649]
**Qubes OS version**

4.1 current-testing

**Affected component(s) or functionality**

qubes-qrexec-policy-daemon

**Brief summary**

DispVMs started from VM via qubes-rpc stays alive after service closing

**How Reproducible**

always

**To Reproduce**
qvm-open-in-dvm

**Expected behavior**

Disposable VM dies after service/application closing

**Actual behavior**

Disposable VM  stays alive

**Comment by jevank** [comment]
Looks like qrexec-client sticks at waiting EOF
```C
            if (wait_connection_end) {
                /* wait for EOF */
                fd_set read_fd;
                FD_ZERO(&read_fd);
                FD_SET(wait_connection_end, &read_fd);
                select(wait_connection_end+1, &read_fd, NULL, NULL, 0);
            }
```

**Comment by marmarek** [comment]
Is the qrexec call finished on the DispVM side?

**Comment by jevank** [comment]
All qrexec-fork-server process are gone, only qrexec-agent is working, so I guess yes.
