### ISSUE TITLE
disable clipboard dom0 R4.0

### ISSUE THREAD

**Issue by 1mzec** [QubesOS/qubes-issues#6650]
**Qubes OS version**
R4.0

**Affected component(s) or functionality**

Qubes clipboard

**Brief summary**

Disable clipboard does not work.

**How Reproducible**

The window in dom0 pops up as a notification:
```
Qubes Clipboard fetched from VM:
Copied 'bytes' to the clipboard
Press ctrl-shift-v to copy this clipboard into dest VM's clipboard.
```

**To Reproduce**

1. vi /var/run/qubes/qubes-clipboard.bin
2. comment out everything with #. 
3. restart/reboot, nothing changes.

**Expected behavior**

Disabled clipboard.

**Actual behavior**

Clipboard not disabled.

**Solutions you've tried**

Following: https://www.qubes-os.org/doc/copy-paste/
* Re-editing the /etc7qubes-rpc/policy/qubes-ClipboardPaste
* Reboots, restarts.

**Comment by DemiMarie** [comment]
Disabling `qubes.ClipboardPaste` should disable pasting from the clipboard.

**Comment by andrewdavidwong** [comment]
Closing as "not an issue." If you believe this is a mistake, please leave a comment, and we'll be happy to take another look. Thank you.
