### ISSUE TITLE
Retrying build of a Fedora 33 template fails due to rpmdb issues

### ISSUE THREAD

**Issue by icequbes1** [QubesOS/qubes-issues#6651]
**Qubes OS version**
R4.0, using a Fedora 32 build VM

**Are you using any [testing](https://www.qubes-os.org/doc/testing/) repositories? If so, please list them and where they are enabled (i.e., dom0, TemplateVM, or StandaloneVM).**
No

**Affected component(s) or functionality**
builder-rpm

**Brief summary**
When attempting to build a Fedora 33 template on a Fedora 32 VM (yes, 32 is EOL at this point), in the event something fails after the `.prepared_base` file is written, successive builds fail due to `dnf` complaining about not knowing the release version when attempting to install packages in the template.

**How Reproducible**
Every time retrying the build of a Fedora 33 template with `make template` after it fails (for any reason - user-initiated or otherwise). This is on a Fedora 32 build VM.

**To Reproduce**

1. Use a Fedora 32 build VM
2. `make DISTS_VM=fc33 template`
3. Allow step 01 to succeed; ctrl+c during step 02 or 04 (Qubeize)
4. `make DISTS_VM=fc33 template`

**Expected behavior**

Template RPM file is produced.

**Actual behavior**

1. Step 01 succeeds
2. Step 02 fails upon attempting package installs - `dnf` says it can't detect the releasever and to specify `--releasever`, leaving `$releasever` in the repo URL, which is invalid.
3. Cannot continue template build

**Additional context**
I've debugged as much as I can and have isolated it to the code in builder-rpm/template_scripts/01_install_core.sh that performs an rpmdb export and then an rpmdb import.

- First run
  1. Build-vm rpm (4.15) installs packages into the template
  2. Build-vm rpm (4.15) performs an rpmdb export
  3. Template-vm rpm (4.16) performs an rpmdb import of the above
  4. Let's say in 04-qubes-groups.sh a repo is down so the build fails.
- Second run
  1. Build-vm rpm (4.15) performs an rpmdb export
     - **The export at this point is 0 in size** (maybe 4.15 rpmdb doesn't understand sqlite?)
  2. Template-vm rpm (4.16) performs an rpmdb import of the empty file
  3. Template-vm rpmdb appears to be wiped out, as if no packages are installed, so dnf can't detect presence of `fedora-release` package to figure out `releasever`.
  
  
It's been difficult trying to follow along with all the rpm changes, so I am not sure of the right solution here. 

Not sure if this is just a Fedora <32 to 33+ artifact or related to the recent rpm hardening, so I raise the issue here.

I know Fedora 32 is EOL, but I assume being able to build the next release from the previous is an acceptable expectation.

**Solutions you've tried**

My quick fix has been to only rebuild rpmdb within `prepare-chroot-base` at the end of the prepared_base block, so that it only executes once.

Of course, removing the prepared_image/root.img also resolves assuming the build executes successfully in one round.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

**Comment by DemiMarie** [comment]
> Build-vm rpm (4.15) performs an rpmdb export
> * **The export at this point is 0 in size** (maybe 4.15 rpmdb doesn't understand sqlite?)

That is exactly the problem.  The code should check for an empty file and not import it.

**Comment by icequbes1** [comment]
Thanks, I'll open a PR and test some combinations.

**Comment by icequbes1** [comment]
Above-referenced commits has accounted for this issue. Closing.
