### ISSUE TITLE
Split GPG cannot handle filenames that are too short

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#6656]
**Qubes OS version**

`R4.0`

**Are you using any [testing](https://www.qubes-os.org/doc/testing/) repositories? If so, please list them and where they are enabled (i.e., dom0, TemplateVM, or StandaloneVM).**

`security-testing`

**Are you providing feedback about a specific package or packages in testing? (If so, please list the package(s) here and [provide feedback in `updates-status`](https://www.qubes-os.org/doc/testing/#providing-feedback), linking to this issue.)**

I don't think so.

**Affected component(s) or functionality**

Split GPG

**Brief summary**

`qubes-gpg-client-wrapper --verify <file>` exhibits strange behavior depending on the name of `<file>`.

**How Reproducible**

100%

**To Reproduce**

Steps to reproduce the behavior, using a random clearsigned file from `qubes-secpack` as an example:

```shell
$ cd qubes-secpack/digests/
$ qubes-gpg-client-wrapper --verify Qubes-R4.0.4-x86_64.iso.DIGESTS
gpg: Signature made Thu 04 Mar 2021 06:11:18 AM PST
gpg:                using RSA key 5817A43B283DE5A9181A522E1848792F9E2795E9
gpg: Good signature from "Qubes OS Release 4 Signing Key" [full]
$ mv Qubes-R4.0.4-x86_64.iso.DIGESTS test.txt
$ qubes-gpg-client-wrapper --verify test.txt 
--verify with filename allowed only on the client side
$ mv test.txt test.txt.FOOBAR
$ qubes-gpg-client-wrapper --verify test.txt.FOOBAR 
gpg: Signature made Thu 04 Mar 2021 06:11:18 AM PST
gpg:                using RSA key 5817A43B283DE5A9181A522E1848792F9E2795E9
gpg: Good signature from "Qubes OS Release 4 Signing Key" [full]
```

**Expected behavior**

A valid clearsigned `.txt` file can be verified using `qubes-gpg-client-wrapper --verify`.

**Actual behavior**

The operation fails with the message `--verify with filename allowed only on the client side`. Appending a random uppercase "file extension" allows the operation to succeed.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

https://www.qubes-os.org/doc/split-gpg/

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

https://github.com/QubesOS/qubes-issues/issues/2165 looks like it might be related. Not sure.

**Comment by DemiMarie** [comment]
This is a bug in how qubes-gpg-client rewrites file names.  Fixing it in the C code would require somewhat invasive refactoring, but working around it in the wrapper script should be easy enough.

**Comment by marmarek** [comment]
This is already fixed in https://github.com/QubesOS/qubes-app-linux-split-gpg/commit/8d33d4d78f95df67dd5ed894d8c598ed45aa4015
