### ISSUE TITLE
"Valentina" App Menu

### ISSUE THREAD

**Issue by ninavizz** [QubesOS/qubes-issues#6665]
_**NOTE:** This is a "Parent" issue, from which many child issues descend. This organizational structure is to separate what is within the scope of a modest grant that funded user research, design, and a bare-bones implementation, for #5677_ 

---

**The problem you're addressing (if any)**
After reviewing all of the feedback received against the **[Bessie](https://www.qubes-os.org/attachment/survey/tour-bessie.webm)** and **[Jackie](https://www.qubes-os.org/attachment/survey/tour-jackie.webm)** app menu options presented to users in #6573 and in interviews with trainers, _Valentina_ was established as a design direction—based off the [Cinnamon menu](https://github.com/linuxmint/cinnamon-menus). The prioritization of features and form-factor/interaction-model choices were all based on user feedback. 

Cinnamon was picked as an existing menu to base the new Qubes app menu upon, for the following reasons:
1. It is an artifact that already exists, and elegantly supports both Light/Dark themes, as well as other DE themes.
2. Cinnamon has been praised for its high usability, and its core interaction patterns and keyboard navigation are well resolved. 

**Describe the solution you'd like**
This issue was created to consolidate discussion, needs, and implementation actions around the building of the design direction _Valentina_. Search will be implemented in the first enhancement release, and fancy features alluded to in _Bessie_ will be implemented on an opt-in basis for users—so, we will never force folks to have the abundance of "stuff" in their app menus, that _Bessie_ showed. 
![valentina - nosearch](https://user-images.githubusercontent.com/8262612/121439545-ffb0e000-c93a-11eb-96de-32ba289e43c8.png)

**Related Issues Et Cetera**
This is a child issue within #5677

**Comment by ninavizz** [comment]
After discussing with Marta, initial implementation priorities are:
1. To get the form-factor and central interactions correct, with the words "Domain" and "Service" and "Template" no longer preceding VM and App names. 
2. To facilitate user resizing (vertical) of the menu such that it may be as tall or as short as folks desire. 
3. An "Are you sure?" dialog for the Shutdown button
4. The "Favorites" list will mimic the list-view layouts shown in Bessie and Jackie (which are identical).
5. Search, the VM's connection-status icon, and the per-VM Shutdown/Open/etc. controls, are all value-add features... not core features. 
 
Search is very important, but is its own silo of interactions to get correct—so it is not a version-one priority.

For the grouping of VMs in the app menu, user mental models for engaging with Qubes are being followed, over literal technical categorization. Were it the latter, we would not have a clean, 3-bucket approach—and for the user needs of an appmenu, that would be silly. So, disposable qubes and disposable qube templates,  are grouped-in under "App" and admin qubes will be grouped in with either Service or Template groups.

## Secondary Priorities
Once the core/central interactivity is nailed, the implementation priorities will be as follows:
1. Show which qubes and apps are running by making a running item bold/white
2. Show qube's connectivity as an icon
3. Include each qube's shut-down/restart/start/etc controls at the bottom of the Apps list. 

## Tertiary Priorities
Next-up will be implementing user-customization options: Favorites (GUI), Pinning, and Colorization. 
DEPENDENT ISSUES (that need to first be completed) for this are #6366, #6652, #6654
1. [Application Settings checkboxes](https://github.com/QubesOS/qubes-issues/issues/6366) enabling users to "Pin" items to the top of their list of apps (Settings per-qube are always pinned by default), to designate an app a favorite. 
2. Creation of an App Menu Settings panel, where users can choose to have qube color expressed in menu selection colors, or in panel decoration colors (tbd); and, whether or not to show the connectivity icon. All further app menu customizations will need corresponding settings options (as simple as on/off, or more detailed settings) to live on this panel.

Per my [initial scoping comment](https://github.com/QubesOS/qubes-issues/issues/5677#issuecomment-840835773), at the point the menu should be included in a release candidate (suggesting `4.2`) so that we can get it into users hands asap for feedback to inform further developments.

**Comment by ninavizz** [comment]
The menu shown to the left in the top PNG, is fully scoped-down to show just the essentials we're targeting for an initial build. 
The view to the right in the top PNG shows the "three columns" and core areas of functionality.
Bottom PNG shows keyboard navigation (green) and general annotations (pink)

![valentina - 1st Release](https://user-images.githubusercontent.com/8262612/120851119-41055200-c52d-11eb-8b0b-6774d0f98028.png)

![valentina - details](https://user-images.githubusercontent.com/8262612/120851287-75790e00-c52d-11eb-8001-fcf39ad0724e.png)

**Comment by deeplow** [comment]
Looking really good. Can't wait to have this.

> After discussing with Marta, initial implementation priorities are:

Another thing that I think should be a priority and is super simple to implement: Map the "windows" key to open the menu. (not sure if mac has an equivalent). But on windows this is standard behavior. This allows for really fast application startup. For example I want to open the "work firefox".

1. press the "windows" key
2. type "work fi" (first and correct option shows up already highlighted)
3. hit enter to open

**Comment by ninavizz** [comment]
@deeplow Just the super-key "open app menu" should be easy, TY for the suggestion! 

2-3 qualify as "Search," unfortunately—and where getting search right, will be "hard." eg: we can't implement literally the pattern you suggest, without any UI for demonstrating the results nor a search bar UI to show the query. We got soooo many asks for that, in the survey that just closed. I absolutely want to make a great Search  happen—but to keep Search from being a mess, implementing a solid federated search logic for Search Results, has to happen. 

More urgently, though, I suspect that just getting the core form-factor "right," without the distraction of Search things, will also be very hard and involved. Hence, the primary reason I did not prioritize it for an initial test build.

**Comment by ejose19** [comment]
Hi @ninavizz, great work on this! I saw the first picture and had to ask, active DisposableVMs will be listed in the App Menu? And being that the case, can we launch more programs on that exactly DisposableVM like we would do for other AppVMs? If that's the case then it would be great, as having to launch a terminal to open more programs in a DisposableVM is cumbersome & not user friendly, so if my impression is correct then this will be greatly appreciated.

**Comment by ninavizz** [comment]
Hi @ejose19! You betcha. The "Open other stuff w/in my DispVM" topic was opened in #5557, and you are correct—Valentina proposes both showing running disposable qubes in the app menu, and also enabling folks to open more stuff w/in each disposable VM. 

As such, per the above example: If you select "Tor Browser" in "datascrub," it would open a new disposable qube. If you opened Tor Browser in _datascrub5678_ it would open Tor within the already running disposable qube, opened from the datascrub template. 

Totally agreed wrt user friendliness. It also stinks for non-techy folks trying to not crash our machines and wanting to spare our RAM.

**Comment by ninavizz** [comment]
@marmarta Zeplin spec screens for building Valentina's chrome and Dark Theme values, here: https://zpl.io/a8Qp95w

**Comment by brochard** [comment]
Hey @ninavizz, nothing to say in a usability standpoint, it looks incredibly easy to use, it also looks amazing, but I find the search bar very large, don't you think the left collumn should go all the way to the top like that ?
![image](https://user-images.githubusercontent.com/31168075/120902507-13113200-c641-11eb-9f54-97a3eb86e286.png)

**Comment by ninavizz** [comment]
@brochard Technically, no, because "everything" is queried against. The width of the Search bar is more of an expression of hierarchies, than an aesthetic choice. If the Search bar were only contained to the middle column, that would imply it's only searching qubes, whereas it's searching both qubes and apps. Does that make sense, or does it still rub you as "wrong"?

Search is also unlikely to be included in an initial release... so I'm not too worried about it, at this point. Will definitely want to do lots of testing/feedback on Search, before it's properly implemented. We did get a TON of feedback guiding how to do Search to user expectations, in the survey we just ran... so I'm optimistic we can get it right, once we do get to it.

**Comment by ejose19** [comment]
@ninavizz That's good to hear! This new App Menu seems to beat current menu in most aspects, but I do notice something that it's easier in current menu than in new one. Based from the screenshot menu, suppose you want to open `vault` settings, you will need to move the cursor all the way down to select `vault`, and then all the way up to select `settings`, in current menu the "submenu" always start at the selected qube level, so for most actions only moving the cursor to the right will be enough (this issue is also present in current whisker menu, and one point for which I favored normal menu, since it's noticeable when using large screens)

**Comment by brochard** [comment]
> 
> 
> @brochard Technically, no, because "everything" is queried against. The width of the Search bar is more of an expression of hierarchies, than an aesthetic choice. If the Search bar were only contained to the middle column, that would imply it's only searching qubes, whereas it's searching both qubes and apps. Does that make sense, or does it still rub you as "wrong"?
> 
> Search is also unlikely to be included in an initial release... so I'm not too worried about it, at this point. Will definitely want to do lots of testing/feedback on Search, before it's properly implemented. We did get a TON of feedback guiding how to do Search to user expectations, in the survey we just ran... so I'm optimistic we can get it right, once we do get to it.
> 
> Also, I just kinda like things lined-up the way they are. If the search bar only extended the width of the 2nd column, to keep the horizontal alignment of things across the middle and right columns, there'd need to be a lot of "dead" space at the top of the 3rd column... and the connectivity icon would be at the same level as the search bar, which felt "off" to me.

I was just talking about the left column going all the way to the top, the search bar in my example is still on top of both qubes and apps (I provided an image, don't know if you missed it). I just find this very long search bar a bit awkward and having a left column going all the way is familiar, Windows 10 has it.

**Comment by ninavizz** [comment]
@brochard The positioning of the search bar is also informed by keyboard navigation/usability needs. Whiskers is very problematic for many reasons, and I don't want to mimic its paradigms. Specifically for Search stuff, tho, it will be most helpful to collect feedback in the issue I created for it #6667. 

@ejose19 Yeah... no "one" thing is going to be perfect, unfortunately. A common problem with any menu, is going to be that many users have a gazillion apps within each qube.  With today's menu, that still opens a sub-menu that is the full monitor height, and would still force users to move their mouse all the way to the top of that, to get to the top most items. 

One solution to ease the burden of too-many apps, is the concept of "pinning" apps to the top of the menu. Right now, users are expressing frustration with "Settings" always getting lost in their sea of apps. So, we chose to pin it to the top, by default. In the [Bessie](https://www.qubes-os.org/attachment/survey/tour-bessie.webm) prototype, I introduced the concept of users being able to "pin" any app of their choosing. Bessie demonstrates my own personal preference to pin the print manager and file manager, and occasionally Terminal. 

You can also use keyboard navigation to get from your selected qube, to the first menu option. Because so many qubes users navigate by keyboards, and Arc/Cinnamon are so popular among non-launcher/menu type methods of navigating new things to open, this paradigm for the menu's form-factor was chosen. It also received about a 2:1 vote, in the #6573 survey—and while those votes were clarified by users as being for many things other than simply the form-factor/interaction-model alone (even tho the question asked users to answer on that criteria alone) right now I need to trust that weight. 

As an enhancement to this new menu, I'm also considering multiple columns for apps, with users being able to designate their max number of apps, before a list of items extends to another column. In [Jackie](https://www.qubes-os.org/attachment/survey/tour-jackie.webm), the McKinsey qube had multiple columns, to reduce extreme mouse movements.

**Comment by ninavizz** [comment]
@brochard ^ edited above, to reflect both keyboard navigation needs and ux best practices for hierarchies.

**Comment by ninavizz** [comment]
## Nina Owes Marta
- [ ] Initial Zeplin specs to build widget chrome from (scaling and truncation stuff, tbd)
- [ ] Artwork for icons (qubes, favorites, settings, shutdown, and the sorting widget; connectivity icons tbd in another issue)
- [ ] Wireframe for _Settings_
- [ ] Several weeks of fun phone calls for in-progress q/a, build reviews, etc. 

Open question for @marmarta : Can the full widget use the [Source Sans Pro](https://fonts.google.com/specimen/Source+Sans+Pro) family of fonts (what the mockups use and _Zeplin_ specs)? Its open sourced under an [Open Font License](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL).

**Comment by deeplow** [comment]
@ninavizz have you considered how this menu handles a large number of qubes?

From [the image](https://github.com/QubesOS/qubes-issues/issues/6665#issue-911730866) it seems running qubes are highlighted. But if you have 15+ you can no longer get cues about which ones are running (because they will be somewhere down on the scroll area).

## Proposal

If the user has more qubes than the vertical space to show them, then list them instead in two section:

----
**creo**
datascrub
└─ **3573-datascrub**
**fosswork**
**studio**
`---------- not running ---


----

**Comment by ninavizz** [comment]
@deeplow As always, TY for the suggestion—and, for such a clear mockup in ASCII. :) 

For the first release I am proposing a sort-order control, thaaat... as I scroll through all the above images, I realize was turned off in the wireframe before I created the PNGs. Oops. :) 

I'll re-create the PNGs WITH that control visible, after I finish typing this reply... but, in short, the control will enable users to sort qubes by Ascending A-Z, Descending A-Z, Color, and Status. The latter, would sort qubes precisely as you suggest—with the running qubes up top, the paused qubes next, and the not-running qubes, beneath—with the second priority sort order being A-Z Ascending. 

Once we have the base menu solid, that will be one of the first "Feature" enhancement priorities. Marek was adamant that _this_ was the one feature he really wanted... so how could I not prioritize it? Also, for the reason you cite—which is that for a user with dozens of qubes, it would be most irritating to always have to scroll to find a running qube to open an app within. Especially since one of the design goals in this, for me, was helping users make more informed choices with managing open qubes, with performance in mind.

I created a [GitHub Project](https://github.com/QubesOS/qubes-issues/projects/12) for the app menu, to give better visibility into how we've prioritized the app menu's features. I ordered the priorities in large part, based on user sentiment communicated in the #6573 but also in part based on the value/effort ratio. As always, I would love to get your thoughts on that! And that of others more engaged here and with forums, than I am (@unman @svensemmler @mfc off the top of my head).

**Comment by ninavizz** [comment]
## Feature Priorities
[This is the link to the GitHub Project](https://github.com/QubesOS/qubes-issues/projects/12) that breaks-down the full Valentina app menu into features, ordered and prioritized for implementation. _Search is hard, so it's slated for 4.3, unless a volunteer wishes to take it on before then. If you wish to comment on this prioritization, please direct those comments to its dedicated issue, #6667_ 

The first development milestone, will to simply get the form-factor of the menu right—in XFCE—with all qubes grouped according to type, and with the menu able to vertically re-size and then re-open after a reboot, predictably. That is the acceptance criteria for this issue to close. Once that threshold is passed, feature issues will be tackled one by one. The "Dev Next Up" column shows those features, in order of importance from top to bottom. 

Proper issues have yet to be created for many of the cards in that column, as at the time of this writing we're still quite early in the development of this design direction.

Qubes is built by an unusually lean team of full-time (cough, paid) contributors, developing a very non-trivial product: a high security operating system, compatible across multiple hardware devices. We depend upon our community to help us build and QA what y'all desire to see in what gets pushed into production. Of course we'd love to hire more full-time developers—and when millions of dollars fall from the sky, we promise we will! In the interm—if there's a feature you really want, and you're capable of working in GDK, we welcome volunteer contributions to helping us build this for our community of users.

**Comment by andrewdavidwong** [comment]
[No epics. Use projects!](https://www.qubes-os.org/doc/reporting-bugs/#every-issue-must-be-about-a-single-actionable-thing)

**Comment by ninavizz** [comment]
Note: Upon learning about [Disposable Templates](https://github.com/QubesOS/qubes-issues/issues/6709#issuecomment-864272548), need to make sub-section w/in "Templates" tab for disposable templates.

**Comment by DemiMarie** [comment]
> Note: Upon learning about [Disposable Templates](https://github.com/QubesOS/qubes-issues/issues/6709#issuecomment-864272548), need to make sub-section w/in "Templates" tab for disposable templates.

I am honestly not sure what a disposable template is.  @marmarek care to enlighten me?

**Comment by brendanhoar** [comment]
@DemiMarie 

That may have been me misinforming @ninavizz on the other thread. Going to edit that post.

**Comment by DemiMarie** [comment]
> @DemiMarie
> 
> That may have been me misinforming @ninavizz on the other thread. Going to edit that post.

Never mind, this was my fault; I should have read the glossary.

**Comment by brendanhoar** [comment]
I've edited my edit and have decided there are currently exactly five and a half types of VMs. Time for a beer.

**Comment by njk2002** [comment]
As for search, KDE Plasma 5.18 is able to perform requested "Super Key ->work fi ->Enter Key" function.
Maybe that can become a reference?

**Comment by marmarta** [comment]
Things still needed from my side from @ninavizz :
- [ ] mockup for system tools / settings pane (for first release, probably just whatever is in the current System Tools/Qubes Tools menus
- [ ] mockup for right click menu - what should it have in different places, how should adding stuff to favorites exactly work
- [ ] svgs for all the icons, in particular icons for panes, settings, poweroff, network on/off
- [ ] mockup for favorites pane

**Comment by ninavizz** [comment]
## artwork
Ok! I believe I got all the icons gathered that you'll need, in this ZIP file. I included all of the ones you'd mentioned above, plus the "network vpn" icon ("Network" indicator intended to be a triad; it's on, off, or it's on and routed through a VPN configured through Qubes... which, if that is epic scope-creep, no biggie to punt until later).
[Valentina-Artwork.zip](https://github.com/QubesOS/qubes-issues/files/6895863/Valentina-Artwork.zip)

**Comment by marmarta** [comment]
I've got the favorites mockup, marking as done.

**Comment by ninavizz** [comment]
## ETC
- Right-click menu: 
  - Per Qube: Same items as in Domains Menu, today
  - Per App: Favorite (or Remove Favorite), Hide From Appmenu, Open (or Quit)
- Tooltips: Not a priority yet, meethinks
- "Settings" and System Tools menu; for now, just plop what exists today, in the left-pane w/ the right-pane empty. Yes, I had ideas in Jackie and Bessie, but feel those are scope-creep for the 1.0 of this.

**Comment by locriacyber** [comment]
Full text search in xfce Application Finder is what I need the most. Currently, searching for `<app> <qube>` will not give any result.

**Comment by deeplow** [comment]
> Full text search in xfce Application Finder is what I need the most. Currently, searching for <app> <qube> will not give any result.

Yes, that's a known issue @locriacyber. See:

> Incremental search is helpful, but without a different organizational approach, the search results are dificult to navigate -- matches may occur on VM name or application name, which are fundamentally different organizational levels. So if I type "f" I get a match for fedora-32 and also for Firefox. To disambiguate searches clearly, I have to type so many characters that the search is barely saving me time at all. 
>
> [eloquence](https://github.com/eloquence) commented [on Apr 1, 2021](https://github.com/QubesOS/qubes-issues/issues/6487#issuecomment-812090291) from https://github.com/QubesOS/qubes-issues/issues/6487#issuecomment-812090291

Hopefully this will be addressed [in the future](https://github.com/QubesOS/qubes-issues/issues/6667). But that's now not that [prioritized as other stuff needs to come first](https://github.com/QubesOS/qubes-issues/projects/12#card-62540955).

**Comment by ninavizz** [comment]
Yes, it absolutely will be prioritized in the future! It's a heavy ux design lift to get right, and other things are known to be desired and have been fully designed and are ready for implementation, is the problem.
