### ISSUE TITLE
"Search" functionality in new app menu

### ISSUE THREAD

**Issue by ninavizz** [QubesOS/qubes-issues#6667]
**The problem you're addressing (if any)**
The strongest point of feedback on #6573 was to give the new appmenu basic search capabilities. Search being not very trivial and an enhancement to the core menu built, however, I wanted to separate and track as an enhancement. So, this issue. 

**Describe the solution you'd like**
A solution @deeplow articulated in #6665 is parallel to what much of the survey feedback also articulated. 
Super Key > type 'work fir' and Firefox in the Work VM opens. 

Beyond that, a clean faceted search pattern for results, feels important. Will expand more upon this issue in subsequent comments.

**Comment by locriacyber** [comment]
This is trivial. Full text search is a mature technology.

**Comment by ninavizz** [comment]
@locriacyber The usability work required to make search results meaningful, is the not-trivial part I was referencing. Also, hello! TY for your interest in contributing! :) 

If you navigate to the 1min mark in this video, at 1:14 the video demonstrates a user beginning a Search task. 
https://www.qubes-os.org/attachment/survey/tour-jackie.webm

The prototype in that video was created using a visual design tool called UXPin, so there's zero code to draw from. 

The current wireframes have the search bar placed at the global level, akin to how it was in the Jackie prototype (above).  Per-qube search is much less desirable imho, than global search—and to make a global search work, is also likely to not be trivial. The global search was heavily request in the survey we did last year to learn about what users want from the new app menu. I also have yet to do a blog post with detailed analysis of that survey, but should prioritize it for contributors. 

<img width="795" alt="Screen Shot 2022-03-05 at 4 54 13 PM" src="https://user-images.githubusercontent.com/8262612/156904709-a255a1f0-1c19-4531-8a0f-929cdc219a53.png">

I'm located on the West Coast of the US, and would be happy to hop on a call in my evening or very early AM, if you'd like to chat. We absolutely need all the help we can get so it's not just Marta doing all the work on this!

**Comment by locriacyber** [comment]
The menu in video seem different from the one I ran from source. Is that the same application?

**Comment by marmarta** [comment]
added with https://github.com/QubesOS/qubes-desktop-linux-menu/commit/2830de75a63aad04cb1de1fff79843bf1ba153b4
