### ISSUE TITLE
VM pre-startup dependencies for more than just networking

### ISSUE THREAD

**Issue by 3hhh** [QubesOS/qubes-issues#6674]
**The problem you're addressing (if any)**

Starting a VM currently only starts VM dependencies, if there is a _network_ dependency.

**Describe the solution you'd like**

Make it possible to define an arbitrary list of VMs as dependencies for a VM, ideally accessibnle via `qvm-prefs` and `qubes-vm-settings`. Qubes OS then makes sure that these VMs are started before the actual VM is started.

The network dependency is just another item on the list that Qubes OS adds by default.

**Where is the value to a user, and who might that user be?**

More freedom in defining dependencies.

For example users might want to

- start a service VM with some other VM, e.g.
  - a `split-gpg` VM along an `e-mail` VM
  - a `printing` VM along an `office` VM
  - a `sys-dns` VM providing a DNS service along `sys-net`
  - ...
- only sometimes run a VM with networking

**Describe alternatives you've considered**

Run custom startup scripts. As a matter of fact I do just that for a long time now.

Alternatively one could implement `qvm-start --by-tag` to start all VMs matching a certain tag or so and use tags to implement one's dependencies.

**Additional context**

-

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

-

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

-

**Comment by andrewdavidwong** [comment]
My email VM already automatically starts my Split GPG backend VM when the MUA tries to access the keyring, so it already works for more than just networking. It's just as-needed rather than on VM startup.

**Comment by unman** [comment]
On Mon, Jun 07, 2021 at 02:14:17PM -0700, Andrew David Wong wrote:
> My email VM already automatically starts my Split GPG backend VM when the MUA tries to access the keyring, so it already works for more than just networking. It's just as-needed rather than on VM startup. 
> 

This is, I think, true for all qrexec dependencies.

**Comment by 3hhh** [comment]
Point taken.

Taking it further, advanced users can already run arbitrary scripts on VM startup via e.g.
- the `callback` pool (the author just sometimes makes a fool out of himself ^^)
- listening to `qubesadmin.events` (non-blocking only)

So this is rather pointless after all.

**Comment by andrewdavidwong** [comment]
> Point taken.
> 
> Taking it further, advanced users can already run arbitrary scripts on VM startup via e.g.
> 
> * the `callback` pool (the author just sometimes makes a fool out of himself ^^)
> * listening to `qubesadmin.events` (non-blocking only)
> 
> So this is rather pointless after all.

And don't forget the intended way to run arbitrary scripts on VM startup: `/rw/config/rc.local`! (See https://www.qubes-os.org/doc/config-files/ for details.)

**Comment by 3hhh** [comment]
On 6/23/21 9:58 AM, Andrew David Wong wrote:
> And don't forget the intended way to run arbitrary scripts on VM startup: `/rw/config/rc.local`! (See https://www.qubes-os.org/doc/config-files/ for details.)

But you can't start other VMs from there unless you deploy some Qubes RPC service for that VM, which might not be so great security-wise.
