### ISSUE TITLE
[Build 2021032103-4.1] openQA test  startup

### ISSUE THREAD

**Issue by twins2020** [QubesOS/qubes-issues#6675]
## Observation

openQA test in scenario qubesos-4.1-pull-requests-x86_64-system_tests_basic_vm_qrexec_gui@64bit fails in
[startup](https://openqa.qubes-os.org/tests/16742/modules/startup/steps/2)

```
$TEXT_DATA$
```

## Reproducible

Fails since (at least) Build [2021022110-4.1](https://openqa.qubes-os.org/tests/16387)

## Expected result

Last good: [2021021116-4.1](https://openqa.qubes-os.org/tests/16230) (or more recent)

## Further details

Always latest result in this scenario: [latest](https://openqa.qubes-os.org/tests/latest?arch=x86_64&distri=qubesos&flavor=pull-requests&machine=64bit&test=system_tests_basic_vm_qrexec_gui&version=4.1)

**Comment by andrewdavidwong** [comment]
I’m not sure how to handle these issues, since they do not follow our issue template and usually do not include enough information. I see you closed this one without any comment or associated commit, @marmarek, so I’m guessing it was invalid.

**Comment by marmarek** [comment]
Yes, looks like a miss-click on openQA. We have there a button to create an issue out of a failed test, but it should be filled with actual information what went wrong.
