### ISSUE TITLE
Consider passing play/pause etc. media keys to all VMs, not just the focused one

### ISSUE THREAD

**Issue by strugee** [QubesOS/qubes-issues#6678]
**The problem you're addressing (if any)**

When playing music in a VM, the play/pause media key on my keyboard can't be used unless the application playing the music is focused. This rather defeats the purpose of having these quick shortcut keys.

I don't have a forward or back media key on my keyboard, but presumably these have the same problem.

**Describe the solution you'd like**

These media keys should just be forwarded to all VMs to act upon as they see fit.

Seems like the GUI daemon would be the natural place to apply this special forwarding logic. (At least I _think_, assuming I'm remembering correctly that the GUI daemon is the one that handles keyboard input.)

**Where is the value to a user, and who might that user be?**

These keys will work the way they're expected to. This affects any user who uses a media application and has one of these keys on their keyboard, essentially.

**Describe alternatives you've considered**

Instead of putting this in the GUI daemon, we could implement something separate and have that run in dom0 and pass the media key events over qrexec. This would have the additional advantage that the integration could be disabled entirely by disabling the daemon, or the user could exercise fine-grained control over it via qrexec policy if they didn't want their media key presses to leak to certain VMs for some reason. But this would be slightly more complicated to implement.

**Additional context**

N/A

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

https://www.qubes-os.org/doc/usb-qubes/

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

#2781

**Comment by jamke** [comment]
1) What happens on other systems when you have 4 different players and press Stop media key?
I always thought that Stop/Play/Next should be passed only to the current window on the usual GNU+Linux system.
If the behavior is the same on other GNU+Linux systems then nothing should be changed in Qubes OS in my opinion.

2) You can implement your idea with `xdotool` and `wmctrl` in own bash/python scripts and global shortcuts (Settings->Keyboard->Application shortcuts in current XFCE DE).
It can be very flexible - you can send these buttons events to appvm you want or not to send to some that you don't trust. Also you can send these button events only application you desire (e.g. smplayer, firefox and etc.) and a lot more.

I have dozen of scripts like that. It does not require any changes in Qubes OS.

P.S. I would also recommend to check out awesome `easystroke` gestures system to compensate for how ugly and not-flexible XFCE is compared to KDE.

**Comment by unman** [comment]
On Mon, Jun 14, 2021 at 10:31:34AM -0700, jamke wrote:
> 1) What happens on other systems when you have 4 different players and press Stop media key?
> I always thought that Stop/Play/Next should be passed only to the current window on the usual GNU+Linux system.
> If the behavior is the same on other GNU+Linux systems then nothing should be changed in Qubes OS in my opinion.
> 
> 2) You can implement your idea with `xdotool` and `wmctrl` in own bash/python scripts and global shortcuts (Settings->Keyboard->Application shortcuts in current XFCE DE).
> It can be very flexible - you can send these buttons events to appvm you want or not to send to some that you don't trust. Also you can send these button events only application you desire (e.g. smplayer, firefox and etc.) and a lot more.
> 
> I have dozen of scripts like that. It does not require any changes in Qubes OS.
> 
> P.S. I would also recommend to check out awesome `easystroke` gestures system to compensate for how ugly and not-flexible XFCE is compared to KDE.

In Debian, the keys can be mapped to session manager outputs, and in my
experience do NOT affect all active players - ymmv.
In Qubes, I find it useful to have a shortcut affect only the active
windows to session manager outputs, and in my experience do NOT affect
all active players - ymmv.
In Qubes, I find it useful to have a shortcut affect only the active
window - example, while on call browsing when a pop up player appears -
the natural thing is to want to pause that player while continuing with
other activities. Or I'm listening to something, and open a sound file
in a disposableVM - I want to pause the original so that I can hear the
new. Or I'm reading an article while listening to music, and want to
pause the music so I can concentrate - I don't want to pause *all* sound outputs.

All of these are areas where the current implementation works well in
Qubes.
If this proposal were adopted I'd be looking for a way of working
around it.

**Comment by jamke** [comment]
> If this proposal were adopted I'd be looking for a way of working
around it.

The same for me. The current way with sending key strokes only to the current focused appvm is the only proper one  and safe one.

I vote for this feature proposal to be rejected.

And I advise @strugee to make what they want using script as I mentioned previously: it will work, will be flexible and won't affect other users.

**Comment by strugee** [comment]
> What happens on other systems when you have 4 different players and press Stop media key?
I always thought that Stop/Play/Next should be passed only to the current window on the usual GNU+Linux system.
If the behavior is the same on other GNU+Linux systems then nothing should be changed in Qubes OS in my opinion.

Yeah, I've used this a bit on Fedora Silverblue and I honestly can't tell how which application gets paused is chosen, but it's definitely not the whole desktop.

Closing since this appears to not be a regular Linux distribution parity issue after all.

**Comment by marmarek** [comment]
I believe this is relevant: https://specifications.freedesktop.org/mpris-spec/latest/. [This](https://amish.naidu.dev/blog/dbus/) gives some hints how to use that from Python. I guess it's possible to write a script that do similar action in selected VM(s) in reaction on a key press in dom0.  Sounds like a good material for a contrib package ;)
