### ISSUE TITLE
Document that sys-firewall and sys-usb are DisposableVMs by default in 4.1

### ISSUE THREAD

**Issue by theperelomov** [QubesOS/qubes-issues#6684]
**Qubes OS version (if applicable)**

R4.1 weekly builds

**Affected component(s) or functionality (if applicable)**

sys-firewall

**Brief summary**

I usually used the sys-firewall to block Internet connections and allow connections between VMs
But now the sys-firewall uses fedora-33-dvm and configs are not saved.
I think need to notify users about this somewhere in the documentation.
Because documentation is currently using the sys-firewall exaples https://www.qubes-os.org/doc/firewall/#where-to-put-firewall-rules https://www.qubes-os.org/doc/firewall/#enabling-networking-between-two-qubes
```
[user@sys-firewall ~]$ sudo bash
[root@sys-firewall user]# echo "iptables -I FORWARD 2 -s 10.137.2.25 -d 10.137.2.6 -j ACCEPT" >> /rw/config/qubes-firewall-user-script
[root@sys-firewall user]# chmod +x /rw/config/qubes-firewall-user-script
```

**Additional context**

Its may relate to utils like qvm-expose-port

**Comment by andrewdavidwong** [comment]
@DemiMarie, by adding the doc label, are you saying this is new, intentional behavior in 4.1 (changed from 4.0) that needs to be documented?

**Comment by andrewdavidwong** [comment]
> But now the sys-firewall uses fedora-33-dvm and configs are not saved.

Does this mean that sys-firewall is a DisposableVM by default in 4.1?

**Comment by DemiMarie** [comment]
> @DemiMarie, by adding the doc label, are you saying this is new, intentional behavior in 4.1 (changed from 4.0) that needs to be documented (as opposed to, say, a firewall bug that should be fixed)?

I honestly do not know.

**Comment by marmarek** [comment]
> Does this mean that sys-firewall is a DisposableVM by default in 4.1?

Yes. And sys-usb too.

**Comment by andrewdavidwong** [comment]
I just (re)discovered https://github.com/QubesOS/qubes-issues/issues/3704, and now this issue makes a lot more sense.

Removing `release notes` since https://github.com/QubesOS/qubes-issues/issues/3704 already has it.

**Comment by Bwahharharrr** [comment]
Now that sys-firewall is disposable, how are we handling adding iptables rules because /rw/config/rc.local is not saved

**Comment by maltfield** [comment]
Sorry, is there documentation anywhere on  how to make `sys-usb` *not* a DisposableVM post-install?

I just installed the latest version of Qubes. I thought I had chosen to make my sys-net & sys-usb VMs *not* persistent, but today I was confused to discover that BusKill was uninstalled from `sys-usb` when I rebooted

 * https://www.buskill.in/qubes-os/

When I checked the template of the `sys-usb` AppVM, I saw that it's set to `fedora-36-dvm`. I selected the dropdown menu to try to change it to a non-dvm, but all the options were DispVMs! I looked around, but I couldn't find any option to give persistence back to `sys-usb`.

It's important to allow persistence in `sys-usb` for hardware dead man switches like BusKill.

How can I change `sys-usb` to have persistence again after install?

**Comment by andrewdavidwong** [comment]
@maltfield, this issue is not the best place for your questions. In general, the issue tracker (`qubes-issues`) is not intended to serve as a help desk, tech support center, or a place for fielding questions. Instead, we've set up other [venues where you can ask for help and support, ask questions, and have discussions](https://www.qubes-os.org/support/). (By contrast, the issue tracker is more of a technical tool intended to support our developers in their work.) Thank you for your understanding!

**Comment by maltfield** [comment]
> But now the sys-firewall uses fedora-33-dvm and configs are not saved.
> I think need to notify users about this somewhere in the documentation.
...
> this issue is not the best place for your questions

Sorry if I wasn't clear: I'm commenting on a ticket about documenting this change, and I'm asking that the documentation includes how to revert these new `sys-*` systems from being a DispVM to having persistence.

**Comment by unman** [comment]
[quote]
It's important to allow persistence in `sys-usb` for hardware dead man switches like BusKill.
[/quote]
Why do you need persistence for this?
Install any software in the template, and configure it in the disposable
template.
The BusKill page cited deals with exactly this configuration.

**Comment by tcosprojects** [comment]
I'm using Qubes 4.2.3 and ran into this following the docs at https://www.qubes-os.org/doc/firewall/#enabling-networking-between-two-qubes

Since sys-firewall is disposable I'm not sure what the right way is to persist these settings.
