### ISSUE TITLE
wwwtest is being indexed by search engines; need to use unique robots.txt to disallow

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#6686]
**Affected component(s) or functionality**

Test website: https://wwwtest.qubes-os.org/

**Brief summary**

The test website is intended only for dev testing, but it is being indexed by search engines. Users trying to find real information are finding pages from the test website in search results and getting confused.

**Expected behavior**

Test website is not indexed by search engines.

**Actual behavior**

Test website is indexed by search engines.

**Additional context**

See this forum thread:

https://qubes-os.discourse.group/t/what-this-website-link-in-details-that-looks-like-the-official-qubes-website/3485

**Proposed solution**

[Forum user codydaig suggests:](https://qubes-os.discourse.group/t/what-this-website-link-in-details-that-looks-like-the-official-qubes-website/3485/9?u=adw)

> Not sure of the exact CI process you have set-up, but the best way would be to have a unique robots.txt file just for wwwtest.qubes.org with the following content:
>``` 
> User-agent: * 
> Disallow: /
> ```
> I’ve done something similar in the past where I added a step to CI for staging deployments to copy robots-staging.txt to robots.txt.
> 

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

N/A

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

None found.

**Comment by andrewdavidwong** [comment]
Folks are still discovering wwwtest and asking whether it's an official site:

https://forum.qubes-os.org/t/is-this-site-an-official-qubes-os-site/5652

Is that expected?

**Comment by EncryptedGiraffe** [comment]
It would presumably take time for search engines to crawl it again and find the updated robots.txt? That could mean it would keep serving that result for a while longer.
