### ISSUE TITLE
unable to enter disk password on second attempt 

### ISSUE THREAD

**Issue by theperelomov** [QubesOS/qubes-issues#6687]
**Qubes OS version**

R4.1

**Are you using any [testing](https://www.qubes-os.org/doc/testing/) repositories? If so, please list them and where they are enabled (i.e., dom0, TemplateVM, or StandaloneVM).**

Weekly builds

**Affected component(s) or functionality**

Disk Password Input

**Brief summary**

I can log in if I enter the password for the disk on 1 try
following attempts fail 

**How Reproducible**

Always for me, i test it 5 times before write issue

**To Reproduce**

1. Reboot PC and wait for disk password input
2. Type wrong password "blablabla"
3. Type TRUE password

**Expected behavior**

My OS launch

**Actual behavior**

My OS think is the wrong password

**Solutions you've tried**

Reboot and type true password on first try

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

Updated
#6608
#3812
#6530

**Comment by theperelomov** [comment]
#6608 sorry

**Comment by theperelomov** [comment]
I think I misunderstood #6608

**Comment by SvenSemmler** [comment]
@theperelomov do you have a Caps Lock indicator on your keyboard? Would you know whether it is on or off just by looking at the keyboard? 

It is very unlikely that there is a bug not recognizing your correct password on the 2nd or 3rd try. Much more likely is that your Caps Lock is on without you knowing (maybe you pressed it instead of Shift during the first try).

**Comment by theperelomov** [comment]
Yes i have indicators, and I understand your suspicions
before I realized it was a bug, I started trying possible combinations, I spend about 30 min, then I load Qubes installer from usb, go to disk setup, and write password here for check and remind myself what password I could set during installation, and have access on the first try, okay reboot and type the same - it work, it surprised me, I know for sure that I entered this password many times

and for test I do this this 5 times before write issue, i always got the same thing.

1. Reboot PC and wait for disk password input
2. Type wrong password "blablabla"
3. Type TRUE password - not work
4. Reboot and write TRUE password - work
5. Go to 1

On 4 step, i always write true password without any errors, i think i could do this for 3 step
Or maybe my brain very lag:D

when installing i used version 20210529, if I remember it right

**Comment by theperelomov** [comment]
English letters and numbers

i had to reinstall the system, now version 20210610 and everything works fine
think I was the only one with this a problem, think I can close issue 

sorry if i caused inconvenience
I'm honestly starting to think about it myself  
> Or maybe my brain very lag:D

**Comment by johnnyboy-3** [comment]
test
