### ISSUE TITLE
Pull in Google's gfxstream (Graphics Streaming Kit) for Hardware Acceleration

### ISSUE THREAD

**Issue by dylangerdaly** [QubesOS/qubes-issues#6689]
**The problem you're addressing (if any)**
Utilize Google's Graphics Streaming Kit to allow 3D/2D hardware acceleration from the hosts GPU within dom0 to other domU's

**Describe the solution you'd like**
_We need more attack surface please /s_

Allow for hardware acceleration for specific domU's, this would be similar to Intel's GVT-g but would hardware agnostic (including ARM)

Forwards both OpenGL and Vulkan workloads to the hosts GPU

**Where is the value to a user, and who might that user be?**
YouTube that doesn't turn my laptop into a melting firepit, even terminal windows are being accelerated now

**Describe alternatives you've considered**
Intel's GVT-g

**Additional context**
Google's gfxstream is the default accelerator for crosvm

Obviously this opens attack surface, essentially opening dom0 up to direct chicanery, however I think a discussion should still be had.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
https://android.googlesource.com/device/generic/vulkan-cereal/
https://source.android.com/setup/create/cuttlefish-ref-gpu

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
NIL

**Comment by DemiMarie** [comment]
Qubes OS *will* implement hardware-accelerated graphics eventually.  It could take a very long time, though, so don’t hold your breath.

**Comment by DemiMarie** [comment]
I think this should be closed.  gfxstream uses the host’s OpenGL and Vulkan implementations, and these are not supported security boundaries.  This means that gfxstream would likely allow a VM escape.  Google might have the resources to prevent this in ChromeOS, but we don’t.  Instead, virtio-GPU native contexts will be used (#8552).
