### ISSUE TITLE
QSB-069 update: "cat: write error: Broken pipe"

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#6691]
**Qubes OS version**

`R4.0`

**Are you using any [testing](https://www.qubes-os.org/doc/testing/) repositories? If so, please list them and where they are enabled (i.e., dom0, TemplateVM, or StandaloneVM).**

`security-testing`

**Are you providing feedback about a specific package or packages in testing? (If so, please list the package(s) here and [provide feedback in `updates-status`](https://www.qubes-os.org/doc/testing/#providing-feedback), linking to this issue.)**

Not sure which package it is, but it's from the update batch for QSB-069 (see below).

**Affected component(s) or functionality**

Updates

**Brief summary**

Updating for QSB-069 results in `cat: write error: Broken pipe` on the first line of the scriptlet output.

**How Reproducible**

Unknown (I only had to do this update once), but probably 100%.

**To Reproduce**

Update for QSB-069, receiving this output (note scriptlet output line 1):

```
[...]
Transaction performed with:
     Installed     dnf-1.1.10-6.fc25.noarch   @anaconda/rawhide
     Installed     rpm-4.14.2.1-5.fc25.x86_64 @qubes-dom0-cached
Packages Altered:
     Upgraded microcode_ctl-2:2.1-32.qubes1.fc25.x86_64 @qubes-dom0-cached
     Upgrade                3:2.1-33.qubes1.fc25.x86_64 @qubes-dom0-cached
     Upgraded python3-xen-2001:4.8.5-32.fc25.x86_64     @qubes-dom0-cached
     Upgrade              2001:4.8.5-34.fc25.x86_64     @qubes-dom0-cached
     Upgraded xen-2001:4.8.5-32.fc25.x86_64             @qubes-dom0-cached
     Upgrade      2001:4.8.5-34.fc25.x86_64             @qubes-dom0-cached
     Upgraded xen-hvm-2001:4.8.5-32.fc25.x86_64         @qubes-dom0-cached
     Upgrade          2001:4.8.5-34.fc25.x86_64         @qubes-dom0-cached
     Upgraded xen-hypervisor-2001:4.8.5-32.fc25.x86_64  @qubes-dom0-cached
     Upgrade                 2001:4.8.5-34.fc25.x86_64  @qubes-dom0-cached
     Upgraded xen-libs-2001:4.8.5-32.fc25.x86_64        @qubes-dom0-cached
     Upgrade           2001:4.8.5-34.fc25.x86_64        @qubes-dom0-cached
     Upgraded xen-licenses-2001:4.8.5-32.fc25.x86_64    @qubes-dom0-cached
     Upgrade               2001:4.8.5-34.fc25.x86_64    @qubes-dom0-cached
     Upgraded xen-runtime-2001:4.8.5-32.fc25.x86_64     @qubes-dom0-cached
     Upgrade              2001:4.8.5-34.fc25.x86_64     @qubes-dom0-cached
Scriptlet output:
    1 cat: write error: Broken pipe
    2 Generating grub configuration file ...
    3 Found theme: /boot/grub2/themes/system/theme.txt
    4 Found linux image: /boot/vmlinuz-5.4.107-1.fc25.qubes.x86_64
    5 Found initrd image: /boot/initramfs-5.4.107-1.fc25.qubes.x86_64.img
    6 Found linux image: /boot/vmlinuz-5.4.98-1.fc25.qubes.x86_64
    7 Found initrd image: /boot/initramfs-5.4.98-1.fc25.qubes.x86_64.img
    8 Found linux image: /boot/vmlinuz-5.4.88-1.qubes.x86_64
    9 Found initrd image: /boot/initramfs-5.4.88-1.qubes.x86_64.img
   10 Found linux image: /boot/vmlinuz-5.4.107-1.fc25.qubes.x86_64
   11 Found initrd image: /boot/initramfs-5.4.107-1.fc25.qubes.x86_64.img
   12 Found linux image: /boot/vmlinuz-5.4.98-1.fc25.qubes.x86_64
   13 Found initrd image: /boot/initramfs-5.4.98-1.fc25.qubes.x86_64.img
   14 Found linux image: /boot/vmlinuz-5.4.88-1.qubes.x86_64
   15 Found initrd image: /boot/initramfs-5.4.88-1.qubes.x86_64.img
   16 Found linux image: /boot/vmlinuz-5.4.107-1.fc25.qubes.x86_64
   17 Found initrd image: /boot/initramfs-5.4.107-1.fc25.qubes.x86_64.img
   18 Found linux image: /boot/vmlinuz-5.4.98-1.fc25.qubes.x86_64
   19 Found initrd image: /boot/initramfs-5.4.98-1.fc25.qubes.x86_64.img
   20 Found linux image: /boot/vmlinuz-5.4.88-1.qubes.x86_64
   21 Found initrd image: /boot/initramfs-5.4.88-1.qubes.x86_64.img
   22 done
[...]
```

**Expected behavior**

No errors.

**Actual behavior**

`cat: write error: Broken pipe`

**Additional context**

@DemiMarie [wrote in a qubes-devel thread on this](https://groups.google.com/d/msgid/qubes-devel/b20a62b4-72c3-285f-a913-cb5ea8259a5c%40invisiblethingslab.com):
> This is normal, but it is still a bad user experience.  The culprit
is probably a shell script being invoked via systemd, but without
IgnoreSIGPIPE=false set (default is true).  Please file an issue.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

N/A

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

None found.

**Comment by marmarek** [comment]
Anyway, since the issue is minor, I'm going to upload `microcode_ctl` package to the stable repo, to have security fix shipped to all users.

**Comment by andrewdavidwong** [comment]
> Anyway, since the issue is minor, I'm going to upload `microcode_ctl` package to the stable repo, to have security fix shipped to all users.

Would it be possible to fix the `cat: write error: Broken pipe` before pushing that to stable, or would it delay the security update by too much? A lot of users will still be confused and worried by the `cat: write error: Broken pipe`. They won't know that it's harmless, and the vast majority of them won't know how to find this issue in order to learn that it's harmless. Of course, getting the security fix out to stable is more important, if we have to choose just one. I just wanted to point out that this will result in a lot of users worrying over nothing and repeatedly asking about it.

**Comment by marmarek** [comment]
The update changing verbosity is a separate update and so would need to stay in current-testing for about a week - that's the minimal delay and I'd rather avoid it in context of security fix.

**Comment by andrewdavidwong** [comment]
> The update changing verbosity is a separate update and so would need to stay in current-testing for about a week - that's the minimal delay and I'd rather avoid it in context of security fix.

No problem, then. Thanks for considering it!

**Comment by andrewdavidwong** [comment]
(Preemptively pinning this issue to make it easier for users to find.)

**Comment by DemiMarie** [comment]
Anything that makes `dracut` faster is certainly a good thing!
