### ISSUE TITLE
4.1 - Convert PDF leaves hanging disposableVM

### ISSUE THREAD

**Issue by unman** [QubesOS/qubes-issues#6695]
**Qubes OS version**

4.1

**Are you using any [testing](https://www.qubes-os.org/doc/testing/) repositories? If so, please list them and where they are enabled (i.e., dom0, TemplateVM, or StandaloneVM).**

4.1 with testing repositories enabled

**Are you providing feedback about a specific package or packages in testing? (If so, please list the package(s) here and [provide feedback in `updates-status`](https://www.qubes-os.org/doc/testing/#providing-feedback), linking to this issue.)**

qvm-convert-pdf

**Affected component(s) or functionality**

qvm-convert-pdf

**Brief summary**

Reported by @Gweck in #6130:

> In R4.1, if a PDF file is converted to a trusted PDF via the corresponding function, the dispvm for the conversion is created, performs the conversion, but then stays running and has to be shutdown manually.

**How Reproducible**

**To Reproduce**

1. Convert PDF file
2. 
3. 

**Expected behavior**

disposableVM will be removed after performing conversion.

**Actual behavior**

disposableVM remains running

**Comment by GWeck** [comment]
I checked now with a fedora dispvm. The behaviour is the same: The dispvm stays alive, and when it is shut down via the Qube manager, the Qube manager crashes. So it's truly independent from using a debian dispvm.

Here are some log files produced during the fedora test. I hope they could help somewhat.

[guid.disp2529.log](https://github.com/QubesOS/qubes-issues/files/6647821/guid.disp2529.log)
[guid.fedora-33.log](https://github.com/QubesOS/qubes-issues/files/6647822/guid.fedora-33.log)
[qrexec.disp2529.log](https://github.com/QubesOS/qubes-issues/files/6647823/qrexec.disp2529.log)
[qrexec.disp-mgmt-fedora-33.log](https://github.com/QubesOS/qubes-issues/files/6647824/qrexec.disp-mgmt-fedora-33.log)
[qrexec.fedora-33.log](https://github.com/QubesOS/qubes-issues/files/6647825/qrexec.fedora-33.log)

**Comment by unman** [comment]
@GWeck many thanks for the input.

**Comment by jevank** [comment]
I guess this is [the same problem](https://github.com/QubesOS/qubes-issues/issues/6649)

**Comment by neowutran** [comment]
I have the same issue. 
I played the game "kill every process until the VM shutdown". 
Ended up with: "qrexec-client-vm dom0 qubes.WindowIconUpdater"

I checked, killing this process only shutdown the VM in this particular case (called from rpc policy)
(It doesn't kill the vm for non-disposable VM, nor for disposable VM launched manually. So I am pretty confident this is directly related to the issue. But haven't looked the code to really understand the issue )

**Comment by marmarek** [comment]
Do you know what specific conditions are needed to reproduce it? It happened for me once, but then (after increasing verbosity of all relevant pieces) I cannot reproduce it anymore...
I've tried it with the DispVM based on fedora-32, fedora-33 and debian-10. The source VM is based on debian-10, but I don't think that matters that much. I tried also with smaller and bigger PDF files.

**Comment by jevank** [comment]
@marmarek Does qvm-open-in-dvm not reproduce it? I was sure it should...

**Comment by marmarek** [comment]
No, the DispVM is getting correctly cleaned up.

**Comment by jevank** [comment]
I have 100% reproducibility on work machine and confirm that problem is with WindowIconUpdater connection. Unfortunately can't check with clean reinstall system right now..

**Comment by neowutran** [comment]
I also have a 100% reproducibility ( I use "testing" for everything )

**Comment by neowutran** [comment]
For reproducibility, found something: 

/usr/lib/qubes/qrexec-client-vm @dispvm qubes.VMShell+WaitForSession "/usr/lib/qubes/qrun-in-vm" "sleep 0 && echo 'tata'"
=> print "tata" and the disposable VM is destroyed

/usr/lib/qubes/qrexec-client-vm @dispvm qubes.VMShell+WaitForSession "/usr/lib/qubes/qrun-in-vm" "sleep 1 && echo 'tata'"
=> print "tata" and the disposable VM is NOT destroyed

Tested that multiple time, reliable on my computer, I guess that by augmenting the "sleep" time it should be reproducible in all the cases. 
So I guess something that is not the original command try to execute new things (dom0 process automatically executing command in online vm ? ) 

( Didn't saw, but since this issue is "in progress" i stop trying to search the bug to avoid doing the same thing at the same time as someone else )
