### ISSUE TITLE
4.1 Shutting down zombie DisposableVM crashes Qube Manager

### ISSUE THREAD

**Issue by unman** [QubesOS/qubes-issues#6697]
**Qubes OS version**

4.1

**Are you using any [testing](https://www.qubes-os.org/doc/testing/) repositories? If so, please list them and where they are enabled (i.e., dom0, TemplateVM, or StandaloneVM).**

dom0

**Are you providing feedback about a specific package or packages in testing? (If so, please list the package(s) here and [provide feedback in `updates-status`](https://www.qubes-os.org/doc/testing/#providing-feedback), linking to this issue.)**

**Affected component(s) or functionality**

Qube Manager

**Brief summary**

Reported by @Gweck in #6130:

> Even after applying all current updates to dom0 and the debian template, the situation is unchanged. The zombie dispvm sems to be in a somewhat queer state, as shutting it down from the Qube manager crashes the Qube manager.

**How Reproducible**

**To Reproduce**

1. qvm-convert-pdf file from debian-10 based qube 
2. Note that disposableVM does not automatically close
3. Attempt to close disposableVM from Manager

**Expected behavior**

disposableVM will be closed
Manager remains running.

**Actual behavior**

disposableVM is closed.
Manager crashes

**Screenshots**

**Additional context**

**Solutions you've tried**

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

**Comment by GWeck** [comment]
This happens for fedora based dispvms, too. See #6695

**Comment by andrewdavidwong** [comment]
> Are you using any testing repositories? If so, please list them and where they are enabled (i.e., dom0, TemplateVM, or StandaloneVM).
> 
> dom0

FYI, this states the location but not which testing repos are enabled.

**Comment by DemiMarie** [comment]
@unman can you provide a backtrace?

**Comment by quser59** [comment]
I am also experiencing crashes of Qubes Manager when having to kill VMs that are acting 'strangely' (not limited to DisposableVMs). 
Qubes R4.1

**Comment by unman** [comment]
On Mon, Jun 14, 2021 at 07:33:01PM -0700, quser59 wrote:
> I am also experiencing crashes of Qubes Manager when having to kill VMs that are acting 'strangely' (not limited to DisposableVMs). 
> Qubes R4.1
> 

Yes, Manager seems fragile under 4.1.
Not limited to disposabeVM

**Comment by 3hhh** [comment]
The Qubes API now throws a [QubesVMNotFoundError](https://github.com/QubesOS/qubes-core-admin/commit/d2ab40de546275c4f7122f6544408d3d4579e6d4) and passes it to user space clients whenever it cannot find one of the involved VMs.

In the past this was just silently logged in the journal (or not at all). I assume Qubes Manager coped by observing the VM removal during the next event update.

It might require some better handling in Qubes Manager. But there should be a big stack trace window whenever it occurs that would directly point to this exception. It should also only happen for disposable VMs or during VM removal.

**Comment by 3hhh** [comment]
Btw https://github.com/QubesOS/qubes-manager/pull/291 apparently wasn't packaged to testing yet, but the API change was, so you very likely just hit into it.

**Comment by 3hhh** [comment]
> but the API change was

This is wrong - it wasn't packaged. So please ignore my previous statements as it's unrelated.

Anyway a new manager version went to 4.1-testing. So you might try again with it in case another commit fixes your issue.

A stack trace would help pinpoint this one, if it wasn't fixed yet.
