### ISSUE TITLE
'xl console' backspace/delete results in placeholders

### ISSUE THREAD

**Issue by quser59** [QubesOS/qubes-issues#6700]
**Qubes OS version**
Qubes R4.1

**Are you using any [testing](https://www.qubes-os.org/doc/testing/) repositories? If so, please list them and where they are enabled (i.e., dom0, TemplateVM, or StandaloneVM).**
No

**Are you providing feedback about a specific package or packages in testing? (If so, please list the package(s) here and [provide feedback in `updates-status`](https://www.qubes-os.org/doc/testing/#providing-feedback), linking to this issue.)**
No

**Affected component(s) or functionality**
'xl console' // (VM console - via command 'xl console')

**Brief summary**
'xl console' becomes impractial to use, (as although backspace/delete does function), the terminal display becomes visually scrambled - I use workaround below.

**How Reproducible**
Bug reproduced on same device using Qubes R4.1 on every VM using Dom0 Terminal to execute command

**To Reproduce**

1. Type 'sudo xl console [pv/serial] [vmName]' into Dom0 Terminal
2. Hit 'backspace', or 'delete'

**Expected behavior**
Backspace should remove previous char, delete should remove forward char - without placeholders.

**Actual behavior**
Backspace results in displaying .[K in place of previous character
Delete results in displaying .[1P or .[C* or .[K in place of deleted character
*.[C is sometimes ..[C or .[C.[C or .[C..[C. etc

**Screenshots**
None

**Additional context**
Keyboard layout in Dom0 and all appVMs is exactly the same
(AFAIR Qubes R4.0 did not have this issue)
Issue is only with 'xl console', workaround below

**Solutions you've tried**
Consulted xen documentation - couldn't find a public solution
Succesful Workaround:
virsh -c xen:/// console [vmName]

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
none

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
none

**Comment by marmarek** [comment]
This is an intentional feature - to not let the VM send control characters to the terminal emulator in dom0 (things like setting window title, colors etc - those features tend to be buggy and in extreme case could lead to taking over dom0). There is a `qvm-console-dispvm` tool that opens VM's console safely (in a DispVM, instead of dom0).

You can find it in several sections of troubleshooting guides, for example at https://www.qubes-os.org/doc/vm-troubleshooting/
