### ISSUE TITLE
Automatic index pages for every directory

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#6702]
**The problem you're addressing (if any)**

We have pages at URLs like this:

https://www.qubes-os.org/news/2021/06/15/qubes-forum-moving-to-new-home/

A visitor should be able to cut away the second half of this URL and view all posts from 2021 at this URL:

https://www.qubes-os.org/news/2021/

But currently that page just 404s.

We should automatically generate an index for every "intermediate piece" of each URL.

This also becomes more important due to the changes in #6701, since now we'll have URLs like this (specific example subject to change):

```
/doc/user/security-in-qubes/data-leaks/
```

A visitor should be able to go to `/doc/user/` and `/doc/user/security-in-qubes/` to see all the pages in each of those directories.

This would also allow us to create automatic breadcrumb trails at the top of each page, e.g.:

```
Documentation / User / Security in Qubes / Data Leaks
```
...where each `/`-separated phrase is a hyperlink.

**Describe the solution you'd like**

Whatever solution accomplishes the above. Here are some relevant search results I found:

https://web.archive.org/web/20200805203117/http://mrloh.se/2015/06/automatic-archives-for-jekyll-on-github-pages/

But it's not exactly the same use case. May or may not be the best way to go in our case.

Another:

https://github.com/rukbotto/jekyll-index-pages

**Where is the value to a user, and who might that user be?**

Website visitors who expect the structure of the website to work this way. Any website visitors who would find the website easier to navigate if it were this way.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

N/A

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

#6701

**Comment by tokideveloper** [comment]
First, I like the idea of having index pages and breadcrumb trails.

However, the suggestion breaks our translation scripts. At least:

- We shouldn't add a `ref` number to auto-generated index pages.
- We shouldn't upload auto-generated index pages to Transifex.

So, how can we recognize those auto-generated index pages? Maybe, we could add an `autogen: true` variable to the YAML front matter of those files and check its value before uploading to Transifex (or doing other stuff).

Another thing is that there should be a YAML file containing a mapping from directory paths to breadcrumb titles. E.g. from `/doc/user/security-in-qubes/` to `Security in Qubes`. This file should be uploaded to Transifex.

Currently, our translation scripts are not prepared for breadcrumbs or auto-generated index files. I wonder if we should first solve those issues before the translation problem or first start translating and then generate index files and breadcrumb trails. Maya and me like to start translations, so, new features should wait. @maiska, what do you think?

**Comment by andrewdavidwong** [comment]
Seems like we've decided against this. See discussion on #6701.
