### ISSUE TITLE
Qubes boot issues when "Above 4G MMIO" is enabled

### ISSUE THREAD

**Issue by Sean-StarLabs** [QubesOS/qubes-issues#6704]
**Qubes OS version**

Extensively tested with R4.0.4, but also apparent in R4.0.1 and R4.0.3.

**Are you using any [testing](https://www.qubes-os.org/doc/testing/) repositories? If so, please list them and where they are enabled (i.e., dom0, TemplateVM, or StandaloneVM).**

**Are you providing feedback about a specific package or packages in testing? (If so, please list the package(s) here and [provide feedback in `updates-status`](https://www.qubes-os.org/doc/testing/#providing-feedback), linking to this issue.)**
Xen?

**Affected component(s) or functionality**

Qubes

**Brief summary**

Qubes boot issues when "Above 4G MMIO" is enabled when using EDK2 as a payload. Affects multiple firmware platforms (AMI, Insyde, coreboot).

It's possible these are related: #6499 #5165 #6215 #5980 #5959

**How Reproducible**

Easily, if you have the capability to change the setting. Most closed source platforms hide this setting by default and coreboot doesn't support it being disabled.

**To Reproduce**

1. Boot a USB or boot an installation
2. If "Above 4G MMIO" is enabled, it won't work

**Expected behavior**

Qubes starts

**Actual behavior**

Booting a USB drive - Black screen
Booting an existing installation - `Xen must be loaded below 4Gb`

**Screenshots**

**Additional context**

**Solutions you've tried**

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

**Comment by matissime** [comment]
Are there any fix for this moment ?
I got the same problem, and this error message : 
`(XEN) Xen is relinquishing VGA console`
Thanks !

**Comment by DemiMarie** [comment]
> Are there any fix for this moment ?
> I got the same problem, and this error message :
> `(XEN) Xen is relinquishing VGA console`
> Thanks !

That isn’t an error message, but it *is* the last message that Xen normally writes to the console itself.  This seems to be a problem with Xen.

**Comment by sourceXORapprentice** [comment]
@Sean-StarLabs any luck? 

Receiving "Xen must be loaded below 4Gb" when attempting to boot the Qubes 4.0.4 installer on Acer Chromebook C740 with Coreboot "MrChromeBox-4.13"

Ran through all of these troubleshooting options by incrementally modifying my BOOTX64.cfg and trying each step:
https://www.qubes-os.org/doc/uefi-troubleshooting/
Additionally attempted "iommu=soft iomem=relaxed" as well as lowering the memory option to 3000M from 4096M.

Original HCL for Acer Chromebook C740 from dispuser5132 reported MrChromebox-4.12, though I'm not sure what change could have triggered this Xen error. Alternatively, it could have been Qubes 4.0.3?
Acer Chromebook C740 HCL:
https://forum.qubes-os.org/t/hcl-acer-chromebook-c740/4279/3

Coreboot and Gallium both installed and run on the C740 without issue. The Qubes 4.0.4 USB boots without issue on other machines.

**Comment by Sean-StarLabs** [comment]
Yes, for coreboot, you need these:
* https://github.com/MrChromebox/edk2/commit/f7fe27d6860c7de2b24d2621335ba66ef4f28a83
* https://review.coreboot.org/c/coreboot/+/56223
And to disable clock gating.

You then need to change qubes-verbose to qubes in the boot.cfg

**Comment by sourceXORapprentice** [comment]
Wow nice work getting that worked out, thank you for the quick update and timely info.
Got the laptop to experiment with Coreboot so here we go.

**Comment by sourceXORapprentice** [comment]
Thanks @Sean-StarLabs  that did it! Was able to compile these with help, and it flashed/worked no issue allowing a Qubes install, and it works on MrChromebox 4.14

**Comment by andrewdavidwong** [comment]
Sorry, I don't really understand the last few comments. Has this been diagnosed and/or resolved?

**Comment by Sean-StarLabs** [comment]
> You then need to change qubes-verbose to qubes in the boot.cfg

2/3 have:

1st issue: Xen seems to want an e820 that doesn't span more than 4G:

edk2 patch:
https://github.com/MrChromebox/edk2/commit/f7fe27d6860c7de2b24d2621335ba66ef4f28a83

coreboot patch (which should make this the default):
https://review.coreboot.org/c/coreboot/+/56223

2nd issue: Qubes doesn't seem to support 8254 Timer:
That can be changed in coreboot

For non coreboot platforms, these settings are called something like "Above 4G MMIO" and "Clock Gating".

3rd issue: Seems to be Xen related, only solution seems to be to change qubes-verbose to qubes in the boot.cfg

**Comment by marmarek** [comment]
> 3rd issue: Seems to be Xen related, only solution seems to be to change qubes-verbose to qubes in the boot.cfg

In R4.0 installation image, those differs with applied workarounds for common UEFI issues (specifically: qubes-verbose has "mapbs" and "noexitboot" enabled). Those two should not be needed anymore in R4.1. Can you try R4.1-beta1?

**Comment by Ben-StarLabs** [comment]
Yup, that does the trick. R4.1.0-beta1 works with version 7 of our coreboot firmware with Tianocore.

**Comment by DemiMarie** [comment]
R4.0 is EOL, and R4.1 does not have this problem.  Closing as fixed.
