### ISSUE TITLE
about disk resize in disposable sys-usb, sys-firewall, sys-net

### ISSUE THREAD

**Issue by theperelomov** [QubesOS/qubes-issues#6705]
**Qubes OS version (if applicable)**

R4.1 20210610-latest-kernel

**Brief summary**

Open Qubes Settings for disposable sys-usb/sys-firewall/sys-net 
Try set private size for VM to 10gb, now in qubes settings you see 10gb private space, but `df` in VM show 2gb
I guess it shouldn't be this way, it's confusing 

**For sys-usb/sys-firewall/sys-net you can set private space in fedora-33-dvm**
it took me a little time to figure it out, so +1 #6669 #2211

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

#6669 #2211

**Comment by andrewdavidwong** [comment]
Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this does not appear to be suitable for `qubes-issues`. We ask that you please post this on the [`qubes-users` mailing list or forum](https://www.qubes-os.org/support/) instead. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a brief comment explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.

**Comment by marmarek** [comment]
This is indeed an issue that resizing disk of a Disposable qube doesn't work.

**Comment by andrewdavidwong** [comment]
FWIW, it was closed because it does not follow the issue tracking guildelines, is incomplete (most of issue template deleted), is not actionable (in original description), and mis-typed (task instead of bug).
