### ISSUE TITLE
Introduce word "Qube" to App Menu prefixes & Notifications; kill "Domain" prefix

### ISSUE THREAD

**Issue by ninavizz** [QubesOS/qubes-issues#6707]
**The problem you're addressing (if any)**
The word "Domain" creates confusion when new users are working to adapt their thinking to fit a mental-model of how Qubes OS works. Additional work happening in #6694 has also eliminated use of the word "Domain" from introductory text for Qubes OS, and increasingly we're moving towards using the nomenclature "qube" in place of the word "Domain."

In `4.2` we are planning to remove prefixes, entirely, in the all-new appmenu for Qubes, instead bucketing qubes by types to simplify the appmenu. See #6665 

**Describe the solution you'd like**
EDITED to reflect solution that reflects below discussion.

This proposal seeks to make: 
- 1 basic text-only change to the existing app menu in 4.1, such that it will support learning and adoption for new and infrequent Qubes users: change `Domain:` prefix in the app menu to `Qube:`. 
- To support this change, the Notifications will also need to be updated, to omit the word "Domain" and replace that with the word "Qube." 
- The "Domains Widget" can remain as-is, as to leave more extensive changes to after some user research is done to validate more hypothesis and solution opportunities. 

![r4 1-menu1-2](https://user-images.githubusercontent.com/8262612/122469478-dcf17d80-cf71-11eb-93cd-65bc65cdc496.png)

The nomenclature "Qube" has been anecdotally determined to be more intuitive in this use. While we are uncertain how to scale that word across the complete Qubes OS ecosystem, and are also unsure how to name disposable entities—for the 4.1 appmenu (which is transitional towards #6665) the below "After" proposed solution feels like a low-effort usability win.

**Where is the value to a user, and who might that user be?**
Three-fold.
1. Make the items in the app menu more intuitive, to be acted upon more quickly and easily.
2. To remove the word "Domain" from the UI, where it should not really be.
3. To bridge the transition to the new appmenu #6665 in `4.2` with the cube icons and the word "Qube" now appearing in the app menu. 

The word "Domain" has already been removed from the "[How To Get Started](https://www.qubes-os.org/doc/how-to-get-started/)" section of the user guide.  Domains are an important concept for folks to understand in navigating operational security choices—but is an odd word for a user interface. 

**Describe alternatives you've considered**
Leaving it alone and marking this issue "won't do." 
So of course, uxtears.

**Additional context**
Andrew is great!

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
This is a design recommendation. 
But I've been told not to delete sections in issues, so I shall not be deleting this section. 

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
I don't think so.

**Comment by ninavizz** [comment]
Oopsie. If this issue gets accepted, the word "Domains" in the notification bubbles will need to be killed, too. Is that hard? :D

**Comment by andrewdavidwong** [comment]
To be consistent, shouldn't the prefix be `App:` for app qubes and `Disposable:` (or `Disp:` if you insist on brevity) for disposable Qubes, just like it's `Service:` for service qubes?

**Comment by andrewdavidwong** [comment]
> (or `Disp:` if you insist on brevity)

This is a long-standing issue due to potential ambiguity with "display."

**Comment by ninavizz** [comment]
My concern with the appmenu, is that when a user goes to it they are less interested in _categorically-correct prefixes_, as they are interested in disambiguating between "Where I go to open an app to do _my_ stuff" with daily tasks, and "Things that exist to support other things, and I only ever visit to do qubes stuff within" The second level on that decision tree, is most likely "what's ephemeral vs what is not," if opening an app to do app-y things is the goal. 

When going to open stuff in a Service or Template VM, it's usually to modify something about that VM's properties—so those tasks are endeavored to meet different user needs, and thus need the specific/clear prefix.

In Qubes Manager, it's totally different from the appmenu—users _are only there_ to do management and configuration stuff.

My recommendation with "qube" for the app menu is intentionally not specific. Stand-alone VMs qualify as a "qube" and non-ephemeral templated VMs are a "qube," but the ephemeral VMs get the disposable qube icons and "disp" as their prefix to call attention to their ephemerality—and they're also app qubes. Disposable qube _templates_ should also get the disp prefix and the disposable qube icon, as when the user goes to select it in the appmenu both types of qube result in an ephemeral thing opening—just, one you can open other things within, and the other you cannot. Which I'd also like to fix with 4.2. 

The 2-syllable prefix of an "AppQube," also imposes a cognitive burden when scanning a list of 20+ things with that prefix. When cognitive processes are overloaded, users are also more prone to making mistakes—and many users adapt to it, but also train themselves to ignore giant blocks of redundant information. On an aside from the annoyance/exhaustion factor. So, those reasons makes it a bad idea (same as Domain, but Domain is also just a confusing/outlier of a word). This is why "Disposable" is bad as a prefix. 

All of this is why I pitched re-doing the appmenu to bucket qubes by type, in the first place. :) In the new appmenu, disposable qubes, disposable qube templates, app qubes, and standalone vms, all exist in the same view (or, literally, tab). 

> This is a long-standing issue due to potential ambiguity with "display."

The new icons should fix that... tho I should file an issue per Marek's comment on our chat, earlier today.

**Comment by andrewdavidwong** [comment]
The problem with your proposed naming scheme is that it makes it sound like service qubes and templates are not qubes. And `disp-qube` is just redundant if we're already calling other things qubes. This kind of inconsistency is very jarring and confusing, even when the goal is to get things done. It contributes to user misconceptions and generally makes Qubes OS seem confusing and incomprehensible. When even the system does not talk about itself consistently, there is no hope for logic and order.

>  Disposable qube templates should also get the disp prefix

It would be a bad idea to treat DisposableVMs and DisposableVM Templates the same way. Users already get confused about this. It can be very dangerous to do something in a DisposableVM Template when you meant to do it in a DisposableVM.

> The 2-syllable prefix of an "AppQube,"

I didn't say two-syllable. I said `App:`.

**Comment by andrewdavidwong** [comment]
In general, I think you undervalue the benefits of things being logical and consistent. It's true that they're not what are most important to all users, and it's true that users vary in the extent to which they need or value such things. But, whether users realize it or not, things being logical and consistent make them understandable. Users may just have a vague sense that they understand how things work and fit together or that they don't. Most won't be able to explain exactly why. That doesn't make it any less real.

**Comment by ninavizz** [comment]
> I didn't say two-syllable. I said `App:`.

Ok. To that, then—identifying a menu item with "App" as a prefix, I cannot anticipate not being totally confusing. 

When "APP" is a tab above a group of qubes, and considered by a user against the other two tabs (Service, Template)—versus in a list as a redundant prefix to words like "banking" and "vault" and "work" and "personal," a very different contextual comprehension experience is offered-up. The context within which words appear, make a big difference. The latter process feels safe to presume to be cognitively exhausting. Users make mistakes and "stop trying," when they get into that headspace. 

You don't see corn or avacadoes at the grocery store, in the fruit section. Because that would make no sense to most people. And yet, avacadoes and corn are both fruit, by genus. Not vegetables. People don't go to the grocery store to learn about plant genus, they go to buy stuff to make meals from. It would be plausible to force a lesson in plant biology upon shoppers, if everyone shopped from lists—but many people do not. Hence, the concept of "merchandising." 

Andrew: you and I are both working to improve an operating system that is incredibly under-resourced, and incredibly difficult for many people to use whom are at-risk and need these kinds of tools. To make the generalization about my values as you are above, is insulting and I don't appreciate it. My recommendations come from directly observing user choices and behaviors in controlled studies, for many years. I respect your learned knowledge of user tendencies from online community activities, and your deep commitment to both understanding Qubes as an invaluable security tool, and to keeping the Qubes OS ship tight and orderly. There is no need to question what I do and don't value, against your own values, however. 

I want a confusing word removed from the UI. Yet, it is not a hill that I would like to die upon. If a clear and readily-evident option is possible before `4.1`'s RC1 deployment.

**Comment by andrewdavidwong** [comment]
> Ok. To that, then—identifying a menu item with "App" as a prefix, I cannot anticipate not being totally confusing.
> 
> When "APP" is a tab above a group of qubes, and considered by a user against the other two tabs (Service, Template)—versus in a list as a redundant prefix to words like "banking" and "vault" and "work" and "personal," a very different contextual comprehension experience is offered-up. The context within which words appear, make a big difference. The latter process feels safe to presume to be cognitively exhausting. Users make mistakes and "stop trying," when they get into that headspace.

Why is the `App:` prefix "cognitively exhausting" while the `disp-qube:` `qube:`, `Service:`, and `Template:` prefixes aren't?

> You don't see corn or avacadoes at the grocery store, in the fruit section. Because that would make no sense to most people. And yet, avacadoes and corn are both fruit, by genus. Not vegetables. People don't go to the grocery store to learn about plant genus, they go to buy stuff to make meals from. It would be plausible to force a lesson in plant biology upon shoppers, if everyone shopped from lists—but many people do not. Hence, the concept of "merchandising."

The relevant analogy to Qubes would be if I insisted on classifying qubes by some technical property that non-technical users wouldn't know or care about e.g., virtualization technology (PV, PVH, HVM, PVHVM). By contrast, app, service, template, and disposable are user-facing categories. We're already in agreement about using these user-facing categories; the disagreement is just over the text labels.

> Andrew: you and I are both working to improve an operating system that is incredibly under-resourced, and incredibly difficult for many people to use whom are at-risk and need these kinds of tools. To make the generalization about my values as you are above, is insulting and I don't appreciate it. My recommendations come from directly observing user choices and behaviors in controlled studies, for many years. I respect your learned knowledge of user tendencies from online community activities, and your deep commitment to both understanding Qubes as an invaluable security tool, and to keeping the Qubes OS ship tight and orderly. There is no need to question what I do and don't value, against your own values, however.

I apologize. My intention was to address the content of your argument, not make any pronouncements about you as a person. My wording was sloppy. I should have said, "In general, I think _your argument_ undervalues the benefits of things being logical and consistent."

Thank you. I don't claim to have your UX expertise. All I aim to do is share my own thoughts and experience.

I realize that I'm a minority in many respects compared to the average user, but if I were to encounter a system that uses its own terminology inconsistently when referring to parts of itself, I would consider that a negative mark against the system. It would likely strike me as some combination of poorly-designed, not well thought-out, and lacking in attention to detail. It might prompt me to question how well those working on the system understand it themselves, which might cause my faith in the system to waver. Of course, all of this would have to be weighed against other evidence and considerations when forming an overall impression.

> I want a confusing word removed from the UI. Yet, it is not a hill that I would like to die upon. If a clear and readily-evident option is possible before 4.1's RC1 deployment.

I don't think I'm asking for too much or for something unreasonable. I simply want consistency. I have to believe that UX best practices are possible to achieve within those rather broad parameters. I'd like logical, technical people to be able to admire Qubes just as much as non-technical novices. I'd like to believe that we don't have to choose one group over the other.

**Comment by ninavizz** [comment]
> Thank you. I don't claim to have your UX expertise. All I aim to do is share my own thoughts and experience.

You are Qubes Yoda. You potentially know more about how Qubes is today, than Marek. More importantly, you know more about how Qubes is today, impacts users, better than anyone. 

I also want consistency. But, it can be a tradeoff—consistently confusing, or inconsistently usable with dabbles of confusing. I realize that's akin to asking one to choose between liverwurst or headcheese. 

> Why is the App: prefix "cognitively exhausting" while the disp-qube: qube:, Service:, and Template: prefixes aren't?

"app" as a prefix to a container that runs apps, I'm guessing would be very confusing. To me, it speaks to the core conflict with mental models in users new to multi-environment systems. Seeing that redundantly as a prefix in a list, just feels like a comprehension brain-twist waiting to happen. "qube" and "disp-qube" are both words with no existing meaning to anybody outside of Qubes. 

You're not asking for anything "too much," and you never do. Selfishly, I'd just like for something to be easy, for a change, lol. But, I also do not want to make things worse for users, in a hasty effort to make things better.

**Comment by andrewdavidwong** [comment]
> You are Qubes Yoda. You potentially know more about how Qubes is today, than Marek. More importantly, you know more about how Qubes is today, impacts users, better than anyone.

No, no, no, this is definitely not even close to being true. Seriously, I'm not just being modest or anything. It's just a fact that Marek knows _orders of orders of_ magnitude more than me. Marek built much of Qubes himself and is a world-class expert in virtualization security, system architecture, high-availability systems, and Linux administration. He has years and years of professional experience in addition to advanced formal education.

Meanwhile, I can't even code. I'm just an enthusiast user who has been hanging around here for a while. I'm decent at Markdown syntax, though. :wink: But I acknowledge the intention behind the remark and thank you for the vote of confidence.

> I also want consistency. But, it can be a tradeoff—consistently confusing, or inconsistently usable with dabbles of confusing. I realize that's akin to asking one to choose between liverwurst or headcheese.

Yes, even bad things can be consistent. But that's why I don't think it's a high bar or too demanding of a standard.

> "app" as a prefix to a container that runs apps, I'm guessing would be very confusing. To me, it speaks to the core conflict with mental models in users new to multi-environment systems. Seeing that redundantly as a prefix in a list, just feels like a comprehension brain-twist waiting to happen. "qube" and "disp-qube" are both words with no existing meaning to anybody outside of Qubes.

I see what you're saying, but then I think the same might apply to `Service:`, because the qube itself is not a service; rather, it can provide one.

The confusion is less likely to matter with `Template:`, since even though a TemplateVM is not itself a template (_qua_ abstract pattern) but rather a VM that serves the function of a template, it probably won't matter in practice whether users are clear about this distinction.

> You're not asking for anything "too much," and you never do. Selfishly, I'd just like for something to be easy, for a change, lol. But, I also do not want to make things worse for users, in a hasty effort to make things better.

To be honest, I think the easy solution is the one you're already working on for the future, namely separating these into groups. Then we won't even have to have repeating prefixes (which seems like makeshift attempt to impose grouping without groups anyway).

I suppose I should look at this in terms of incremental improvement. The status quo is already inconsistent. As long as the proposed change doesn't introduce *worsen* the inconsistency, I shouldn't oppose it.

In that spirit, how about simply replacing `Domain:` with `Qube:` and leaving the rest the way it is? (Capitalized `Qube:` because all the other prefixes, including the current `Domain:` prefix, are capitalized, and because it's not ambiguous with Qubes OS as a whole as long as there's no `s` at the end.)

**Comment by ninavizz** [comment]
> Marek is Yoda and Luke Skywalker rolled into one. Meanwhile, I'm like... Jar Jar Binks or something.

The tourguide/docent often has a differently-deeper understanding of systems, than the architect/builder. Between those two, I do think you're the Obi-Wan Qubes Docent, with Marek—yeah... he pretty much is Yoda, Luke, Han, and Leia, all in one. 
His hair even kinda resembled Yoda's ears together with Leia's buns, when I was in Berlin last year! :D 

> I suppose I should look at this in terms of incremental improvement. The status quo is already inconsistent. As long as the proposed change doesn't worsen the inconsistency, I shouldn't oppose it.

I honestly do appreciate the pushback. It forces everyone to re-think things, which is good. 

Yeah, I can dig restricting this request to just removing "Domain" and replacing it with "Qube:" in both the AppMenu and Notifications. I dislike the multi-syllabic nature of dis-pose-uh-bull, but for all the `existential-wtf-trigger` reasons you cited above, agree it's likely prudent to just keep it as-is for now.

**Comment by marmarek** [comment]
All (recent) menu-related changes for R4.1 combined:
![menu-after1](https://user-images.githubusercontent.com/726704/124676588-1c4f2200-debf-11eb-861e-a4937214d3ed.png)

- "Domain" -> "Qube"
- new service icons
- disposable template got extra entry: to launching apps in that template directly. The "Template (disp)" prefix got sorted between "Template: debian-10" and "Template: fedora-33"...
- it is not visible here, but sys-usb and sys-firewall are of "disposable service qube" type/role, while sys-net and sys-whonix are just "service qube"

**Comment by ninavizz** [comment]
Looks terrific, Marek! Unrelated to this issue, the "Q" in Qubes Tools appears to be a little bit squished, horizontally. I can open another issue for that—incredibly fussy and minor as that is.

**Comment by marmarek** [comment]
> the "Q" in Qubes Tools appears to be a little bit squished, horizontally

Interesting, indeed it looks this way. But also, it seems to be this way, like, forever! I have it on my R4.0 system, and also on various older screenshots on our website. But, the [original file](https://github.com/QubesOS/qubes-artwork/blob/master/logo/qubes-logo-blue.svg) looks correct.

**Comment by ninavizz** [comment]
@marmarek Part of this issue, addresses what is probably a totally different part of the code—to remove the word "Domain" from the notifications. Should I open a separate issue for that? Nope, doesn't need to be in the 1st RC. Marek and Marta on holiday, need to be in the first RC for 4.1

**Comment by marmarek** [comment]
Yes, I haven't forgotten, and yes, it is a different part of the code. It's fine to keep it here.

**Comment by DemiMarie** [comment]
Please open a separate issue @quantumpacket.
