### ISSUE TITLE
Graphical bug

### ISSUE THREAD

**Issue by jrz42Fjd** [QubesOS/qubes-issues#6710]
**Qubes OS version**

4.1

**Are you using any [testing](https://www.qubes-os.org/doc/testing/) repositories? If so, please list them and where they are enabled (i.e., dom0, TemplateVM, or StandaloneVM).**

No.

**Are you providing feedback about a specific package or packages in testing? (If so, please list the package(s) here and [provide feedback in `updates-status`](https://www.qubes-os.org/doc/testing/#providing-feedback), linking to this issue.)**
No.

**Affected component(s) or functionality**

The entire system after logging in.

**Brief summary**

After i log in, i can use qubes without any problems for around 2-3 minutes, but after that, the windows don't refresh
properly, the cursor has a weird texture in some windows, the windows get weird textures too, sometimes they go black or the background goes black.

**How Reproducible**

Every time i use qubesos.

**To Reproduce**

1. Log into QubesOS
2. Open one or more windows
3. Use them for 1 to 3 minutes

**Expected behavior**

Be able to use Qubes without any graphical problems.

**Screenshots**

![1](https://user-images.githubusercontent.com/86050867/122375004-5e391800-cf52-11eb-89f1-e31ad443b80f.png)
![2](https://user-images.githubusercontent.com/86050867/122375006-5f6a4500-cf52-11eb-82e7-a64491598379.png)

**Additional context**

if that can help :
CPU = AMD Ryzen 5 3600X
RAM = 16GB
GPU = AMD Radeon RX 5700XT

**Solutions you've tried**

Switching from xfce to KDE.
Disabling the compositor in xfce and KDE.
Disabling XScreenSaver

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

https://www.qubes-os.org/doc/gui-troubleshooting/

**Comment by DemiMarie** [comment]
Can you provide the output of `uname -r` in dom0?  If your GUI domain is different, can you provide the output of `uname -r` in that domain as well?

**Comment by jrz42Fjd** [comment]
5.10.38-1.fc32.qubes.x86_64

**Comment by DemiMarie** [comment]
Are you using a GUI qube separate from dom0?

**Comment by jrz42Fjd** [comment]
No, can't see any in qubes manager

**Comment by DemiMarie** [comment]
Can you try with `kernel-latest`?

**Comment by jrz42Fjd** [comment]
I downloaded it and put it as default in the global settings but windows still end up looking like in the 2nd screenshot.
(uname -r didn't seem to update though, even after restarting the computer, don't know if that's normal)

**Comment by isodude** [comment]
Someone pointed out that downclocking the GPU could stabilize things, now that was with freezing, maybe it applies here as well?

https://gitlab.freedesktop.org/drm/amd/-/issues/892#note_987898
