### ISSUE TITLE
Cannot run, update or download Tor Browser in anon-whonix vm (while it works in disposable vm based on the same template)

### ISSUE THREAD

**Issue by newsyy** [QubesOS/qubes-issues#6711]
**Qubes OS version**

R 4.0

**Are you using any [testing](https://www.qubes-os.org/doc/testing/) repositories? If so, please list them and where they are enabled (i.e., dom0, TemplateVM, or StandaloneVM).**

No

**Affected component(s) or functionality**

Tor Browser and Tor Browser Downloader in Whonix VM (anon-whonix)

**Brief summary**

Whonix workstation and gateway template VMs are updated. 
When I try to open the Tor Browser in anon-whonix VM, i get:
_"Failed to run the following command:
cd /home/user/.tb/tor-browser"_
When I try the Tor Browser Downloader, i get:
_"Version file not found. (File /home/user/.tb/tor-browser/Browser/tbb_version.json does not exist.) Please report this Whonix Bug!"_ & it asks if I want to download an online detelcted version 10.0.17; when I say yes, i eventually get:
_"update-torbrowser script bug. (...)
BASH_COMMAND: rm --recursive --force "$gpg_bash_lib_input_temp_folder" exit_code: 0 (...)"_

I tried the:
sudo chown --recursive user:user /home/user as per the suggestion in the Error message, it doesn't change the situation.

The disposable whonix workstation, that is based on the same whonix workstation template and uses the same sys-whonix for networking does not encounter this issue. The Tor Browser runs normally there. 

I'm very new to Qubes and Whonix and have no idea what else I can try apart from the above suggested fix, which didn't work..

I looked for this in the issues here as well as in Qubes and Whonix documentation and forums, but was not able to find any information. The error message says "Please report this Bug", so I hope this is the correct area to include this in.

**Comment by andrewdavidwong** [comment]
CC @adrelanos

**Comment by brendanhoar** [comment]
Are you executing:

sudo update-torbrowser 

In the template?

**Comment by adrelanos** [comment]
Guess 1)

* https://www.whonix.org/wiki/Root#Inappropriate_Use_of_Root_Rights
* https://www.whonix.org/wiki/Root#Permissions_Fix

Guess 2)

Or data corruption.

Option A)

https://www.whonix.org/wiki/Manually_Downloading_Tor_Browser - which might fail due to permission issues / data corruptoin but that's general Linux user support. Not a (Whonxi) bug.

Option B)

https://www.whonix.org/wiki/Factory_Reset - Re-install method - re-creation of anon-whonix might be sufficient.

----

I don't think there is anything wrong with the tb-updater package / update-torbrowser script unless multiple users are affected. Already giving a hint what's wrong.

> Failed to run the following command
> cd /home/user/.tb/tor-browser

If you wish to attempt to debug / think this is a bug, do this manually.

```
cd /home/user
```
```
cd /home/user/.tb
```
```
cd /home/user/.tb/tor-browser
```

**Comment by andrewdavidwong** [comment]
Closing as "not an issue." If you believe this is a mistake, please leave a comment, and we'll be happy to take another look. Thank you.

**Comment by newsyy** [comment]
Thanks for your suggestions!
I don't remember, but it's possible that I had used "sudo update-torbrowser" at an earlier time.
Permissions Fix didn't work in this case and I realise I may have used it incorrectly as well, so I'm going to reinstall Qubes from scratch just to be safe.

**Comment by DemiMarie** [comment]
> Thanks for your suggestions!
> I don't remember, but it's possible that I had used "sudo update-torbrowser" at an earlier time.
> Permissions Fix didn't work in this case and I realise I may have used it incorrectly as well, so I'm going to reinstall Qubes from scratch just to be safe.

You can just reinstall the Whonix template: remove `anon-whonix`, then run `sudo qubes-dom0-update --enablerepo=qubes-templates-community --action=reinstall qubes-template-whonix-ws-15` in dom0.

**Comment by newsyy** [comment]
Unfortunately I run the Permissions_Fix in dom0 as I misunderstood the Error message I was getting from the system and even though I don't fully understand what it means, I figured it's probably not good. As I said, I'm super new to Qubes. It's a new system so I was able to reinstall it without losing anything, but a bit of extra time ;) Will make sure to study the documentation much more thoroughly from now on.

> > Thanks for your suggestions!
> > I don't remember, but it's possible that I had used "sudo update-torbrowser" at an earlier time.
> > Permissions Fix didn't work in this case and I realise I may have used it incorrectly as well, so I'm going to reinstall Qubes from scratch just to be safe.
> 
> You can just reinstall the Whonix template: remove `anon-whonix`, then run `sudo qubes-dom0-update --enablerepo=qubes-templates-community --action=reinstall qubes-template-whonix-ws-15` in dom0.
