### ISSUE TITLE
Kali Linux connection with Whonix

### ISSUE THREAD

**Issue by curiousgeorge567** [QubesOS/qubes-issues#6714]
Hello,

Trying to connect Kali Linux Standalone VM to Whonix but am unable to get a connection. All of the network settings have been manually entered from the Qube settings and the connection is showing up as connected in the VM but no traffic will pass with using ping.

**Comment by DemiMarie** [comment]
I am no expert on Whonix, but I believe ping failing is by design.  Do HTTP requests work?

**Comment by andrewdavidwong** [comment]
Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this does not appear to be suitable for `qubes-issues`. We ask that you please post this on the [`qubes-users` mailing list or forum](https://www.qubes-os.org/support/) instead. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a brief comment explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.
