### ISSUE TITLE
Create a client library for the GUI protocol

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#6716]
**Qubes OS version (if applicable)**

R4.2

**Affected component(s) or functionality (if applicable)**

qubes-gui-agent

**Brief summary**

The existing X11-based GUI agent will continue to be supported even after Wayland has become the default.  To avoid duplicating code between the two implementations, they should share a library that implements the client side of the GUI protocol.

**Additional context**

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

**Comment by marmarek** [comment]
Handling of GUI messages will be fundamentally different in Wayland. This likely include even things like a different event loop or such. I don't believe there will be much code to share, at best it will be few helper functions to read data from vchan (but even those may need some adjustment, depending on the event loop structure). The protocol definition itself is already in a separate header, in a separate package.

On the other hand, many other parts of the gui-agent-linux repository (user session handling etc) may be shared. But those are separate scripts/programs already.

**Comment by DemiMarie** [comment]
> Handling of GUI messages will be fundamentally different in Wayland. This likely include even things like a different event loop or such. I don't believe there will be much code to share, at best it will be few helper functions to read data from vchan (but even those may need some adjustment, depending on the event loop structure). The protocol definition itself is already in a separate header, in a separate package.

That is true!  The Wayland library provides its own event loop, which seems to be useful beyond just Wayland.

**Comment by DemiMarie** [comment]
https://github.com/QubesOS/qubes-gui-rust is this library.  Closing as fixed.
