### ISSUE TITLE
Kali-Whonix Connection

### ISSUE THREAD

**Issue by curiousgeorge567** [QubesOS/qubes-issues#6718]
Trying to connect Kali as a Standalone VM through Whonix but the connection will not work. All of the settings inside the Kali VM are

 manually set and are correct. The Kali VM works fine when using the default firewall VM but when using Whonix the connection doesn't 

work. Have tried turning IPv4 connection off/on to refresh settings within the Kali VM as a troubleshooting step.

**Comment by andrewdavidwong** [comment]
Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this does not appear to be suitable for `qubes-issues`. We ask that you please post this on the [`qubes-users` mailing list or forum](https://www.qubes-os.org/support/) instead. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a brief comment explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.

**Comment by curiousgeorge567** [comment]
I have reported this on the forum and have also viewed another post on github regarding this.

**Comment by unman** [comment]
On Fri, Jun 18, 2021 at 11:21:55PM -0700, curiousgeorge567 wrote:
> I have reported this on the forum and have also viewed another post on github regarding this.
> 

Follow up at the Forum detailing what you have tried so far, and how it
fails.
As always, you may get better response at the Whonix forums, since this
is Whonix specific.
