### ISSUE TITLE
i3 - dmenu missing - R4.1

### ISSUE THREAD

**Issue by neowutran** [QubesOS/qubes-issues#6723]
**Qubes OS version**

R4.1 
Started to migrate from 4.0 to 4.1, installed with the latest ISO from fepitre bot (19/06)

**Are you using any [testing](https://www.qubes-os.org/doc/testing/) repositories? If so, please list them AND where they are enabled (i.e., dom0, template, or standalone).**

Yes. Activated all the testing repos soon after the installation completed

**Are you providing feedback about a specific package or packages in testing? (If so, please list the package(s) here and [provide feedback in `updates-status`](https://www.qubes-os.org/doc/testing/#providing-feedback), linking to this issue.)**
Probably: 
- qubes-desktop-linux-i3-settings-qubes 
or
-  qubes-desktop-linux-i3 

**Affected component(s) or functionality**

i3 menu

**Brief summary**

Unable to start i3 menu

**How Reproducible**

**To Reproduce**

- Install fresh R4.1 iso
- Install i3 and i3-settings-qubes
- Start i3 WM
- Win+D to open menu

**Expected behavior**

The i3 menu is started

**Actual behavior**

Nothing happens

**Screenshots**

**Additional context**

**Solutions you've tried**

In dom0: qubes-dom0-updates dmenu
"dmenu" was not installed. It is required by "i3-dmenu-desktop" as used in https://github.com/QubesOS/qubes-desktop-linux-i3-settings-qubes/blob/master/i3.config
I guess a line need to be added in a RPM spec file 
"Requires: dmenu" 

Maybe in "qubes-desktop-linux-i3"

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

None

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

None found.

**Comment by holiman** [comment]
`dmenu` is already a recommend:https://github.com/QubesOS/qubes-desktop-linux-i3/blob/main/i3.spec.in#L84 . 
IMO this is correct - it's not a strict requirement, since a minimal i3 install can manage without it.

**Comment by neowutran** [comment]
Hi,  I am closing this issue. 
It was a regression since 'dmenu' was installed in 4.0 but not in the early 4.1 version. 
Now in dev build of R4.2 and current R4.1 version it seems to all be OK. 
( I also had incompatibilities between dmenu and default configured locale, but seems to be ok with the dev build of R4.2  )
