### ISSUE TITLE
QubesManager UI - R4.1 - "Initial memory" inconsistency between "Ok" and "Apply" button

### ISSUE THREAD

**Issue by neowutran** [QubesOS/qubes-issues#6724]
**Qubes OS version**

R4.1
Started to migrate from 4.0 to 4.1, installed with the latest ISO from fepitre bot (19/06)

**Are you using any [testing](https://www.qubes-os.org/doc/testing/) repositories? If so, please list them AND where they are enabled (i.e., dom0, template, or standalone).**

Yes. Activated all the testing repos soon after the installation completed

**Are you providing feedback about a specific package or packages in testing? (If so, please list the package(s) here and [provide feedback in `updates-status`](https://www.qubes-os.org/doc/testing/#providing-feedback), linking to this issue.)**

**Affected component(s) or functionality**

QubesManager

**Brief summary**

**How Reproducible**

100%

**To Reproduce**

1. Open Qubes Manager
2. Open settings window for a HVM qube
3. Try to change "Initial Memory" ("Include in memory balancing" is NOT checked") 
4. Click on "Apply"

**Expected behavior**

The new "Initial memory" settings is applied

**Actual behavior**

The "Initial memory" settings is reverted to the original value

**Screenshots**

**Additional context**

**Solutions you've tried**

Click on "Ok" instead of "Apply"

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

None

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

None found.

**Comment by aesrentai** [comment]
I've found this occurs in PVH qubes also and it's quite frustrating.  My "solution" was to just try setting it 20 times until it eventually worked.  Aside from that I cannot discern any pattern between what vms this occurs in or if the actual before/after values have any affect.

**Comment by EncryptedGiraffe** [comment]
I've just confirmed this, and interestingly, the "initial memory" property is actually being set, only the UI value is reverted back to the original.
Steps:
1. Change "Initial memory" value, e.g. from 400 to 350
2. Click Apply
3. Observe how after a moment, the UI switches back to 400
4. Close the Settings window, then reopen it
5. Observe the "Initial memory" shows 350

**Comment by neowutran** [comment]
Retested just now with the latest updates. 
Everything seems to be ok.
Closing the issue
