### ISSUE TITLE
Usb storage - remounting issue - R4.1

### ISSUE THREAD

**Issue by neowutran** [QubesOS/qubes-issues#6725]
**Qubes OS version**

R4.1
Started to migrate from 4.0 to 4.1, installed with the latest ISO from fepitre bot (19/06)

**Are you using any [testing](https://www.qubes-os.org/doc/testing/) repositories? If so, please list them AND where they are enabled (i.e., dom0, template, or standalone).**

Yes. Activated all the testing repos soon after the installation completed

**Are you providing feedback about a specific package or packages in testing? (If so, please list the package(s) here and [provide feedback in `updates-status`](https://www.qubes-os.org/doc/testing/#providing-feedback), linking to this issue.)**
No

**Affected component(s) or functionality**

USB data block device 

**Brief summary**

Can only mount the USB storage stick once.

**How Reproducible**

100%

**To Reproduce**

1. Plug a USB storage stick
2. Using the GUI, pass the "Data (block) Devices" to a qube ("toto")
3. Mount the /dev/xvdi 
4. Umount the /dev/xvdi
5. sync
6. Using the GUI, unattach the "Data (block) Devices"
7. Unplug the USB storage stick
8. Plug the USB storage stick
9. Using the GUI, pass the "Data (block) Devices" to the same qube ("toto")
10. Try to mount /dev/xvdi

**Expected behavior**

I can mount /dev/xvdi

**Actual behavior**

/dev/xvdi doesn't exist

**Screenshots**

**Additional context**

This was working as expected in R4.0

**Solutions you've tried**

Restart the qube "toto". Or attach the "Usb device" directly (not the "Data (Block) Devices")

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

None

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

None found.

**Comment by icequbes1** [comment]
I'm also observing this bug. My observations:

0. Fresh boot of sys-usb, VM 1, and VM 2
1. Works: attach block device A to VM 1
2. Works: attach block device B to VM 2
3. Works: attach block device A to VM 2
4. Fails: attach block device A back to VM 1
5. Fails: attach block device A back to VM 2
6. Works: attach block device B to VM 1

It appears sys-usb will only allow a block device to be attached to a particular VM only once. Restart of sys-usb is needed.

Additional info with limited debugging:

- Does not appear `/etc/xen/scripts/block remove` is triggered in sys-usb upon detach (after an initial successful attachment).
  - Even if it was triggered, `remove` is a no-op in R4.1 in that script.
  - In R4.0 /usr/lib/qubes/udev-block-remove is ultimately invoked through udev which does some qubesdb updates	
  - `/etc/xen/scripts/block add` is never triggered in the R4.1 failure case, though there are `xen-blkback: ... using 2 queues, protocol 1` kernel logs messages 
- The xenstore still retains `/local/domain/[sys-usb-domid]/backend/vbd/x/yyyy` upon detach after an initial successful attachment

I've manually invoked `DEVNAME=devicename /usr/lib/qubes/udev-block-remove` and `xenstore-rm /local/domain/[sys-usb-domid]/backend` but did not seem to change anything.

In the attached VM, when detaching the device after it initially works, there are sometimes messages in the kernel that were not present in R4.0:

```
xen:grant_table: WARNING: g.e. 0x14f8 still in use!
deferring g.e. 0x14f8 (pfn 0xffffffffffffffff)
xen:grant_table: WARNING: g.e. 0x1509 still in use!
deferring g.e. 0x1509 (pfn 0xffffffffffffffff)
xen:grant_table: WARNING: g.e. 0x1507 still in use!
deferring g.e. 0x1device/vbd/507 (pfn 0xffffffffffffffff)
block xdi: device/vbd/51840 was hot-unplugged, 0 stale handles
xen:grant_table: freeing g.e. 0x14f8
xen:grant_table: freeing g.e. 0x1509
xen:grant_table: freeing g.e. 0x1507
```

**Comment by jevank** [comment]
This looks like duplicate https://github.com/QubesOS/qubes-issues/issues/6996 and should be fixed too.

**Comment by andrewdavidwong** [comment]
This appears to be a [duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If anyone believes this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.
