### ISSUE TITLE
GitLab CI: Spurious HTML-Proofer failures

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#6726]
**Affected component(s) or functionality**

GitLab CI, website

**Brief summary**

There are two spurious HTML-Proofer failures affecting every Travis CI result.

**How Reproducible**

100%

**To Reproduce**

Test PR: https://github.com/QubesOS/qubesos.github.io/pull/176
GitLab CI log: https://gitlab.com/QubesOS/qubesos.github.io/-/jobs/1366901592#L444

```
- ./_site/doc/certified-hardware/index.html
  *  internally linking to /news/2020/03/04/nitropad-x230-qubes-certification/, which does not exist (line 306)
     <a href="/news/2020/03/04/nitropad-x230-qubes-certification/">announcement</a>
  *  internally linking to /news/2021/06/01/nitropad-t430-qubes-certification/, which does not exist (line 313)
     <a href="/news/2021/06/01/nitropad-t430-qubes-certification/">announcement</a>
htmlproofer 3.16.0 | Error:  HTML-Proofer found 2 failures!
```

But, in fact, these two links are good:
- https://www.qubes-os.org/news/2020/03/04/nitropad-x230-qubes-certification/
- https://www.qubes-os.org/news/2021/06/01/nitropad-t430-qubes-certification/

**Expected behavior**

HTML-Proofer failures are actual broken links.

**Actual behavior**

HTML-Proofer is flagging good links.

**Solutions you've tried**

N/A

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

N/A

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

None found.

**Comment by andrewdavidwong** [comment]
As @marmarek pointed out to me, the `/news/` directory inside of the GitLab CI job artifact is extremely old. The most recent post it contains is from 2019!

**Comment by marmarek** [comment]
Found it: https://github.com/QubesOS/qubesos.github.io/commit/ce6632fa85ab7909fbfb15fe66e4b64cd84ac700#diff-99d9b7b38e9395aab14da8716127ab50ba61e9d9d2aa4a56ce1bb84c85b162c8R68 :facepalm:

**Comment by andrewdavidwong** [comment]
> Found it: [QubesOS/qubesos.github.io@ce6632f#diff-99d9b7b38e9395aab14da8716127ab50ba61e9d9d2aa4a56ce1bb84c85b162c8R68](https://github.com/QubesOS/qubesos.github.io/commit/ce6632fa85ab7909fbfb15fe66e4b64cd84ac700#diff-99d9b7b38e9395aab14da8716127ab50ba61e9d9d2aa4a56ce1bb84c85b162c8R68)

Oh, interesting. Thank you for finding and fixing it!
