### ISSUE TITLE
Device widget showing root device on ZFS-as-root configuration

### ISSUE THREAD

**Issue by ayakael** [QubesOS/qubes-issues#6729]
**Qubes OS version**
R4.1

**Are you using any [testing](https://www.qubes-os.org/doc/testing/) repositories? If so, please list them AND where they are enabled (i.e., dom0, template, or standalone).**
Negative, using the standard current repo

**Are you providing feedback about a specific package or packages in testing? (If so, please list the package(s) here and [provide feedback in `updates-status`](https://www.qubes-os.org/doc/testing/#providing-feedback), linking to this issue.)**

**Affected component(s) or functionality**

qubes-desktop-linux-manager-4.1.7-1.fc32 package, device manager widget

**Brief summary**

With ZFS as root, and cfcs's qubes-storage-zfs as storage driver, device widget shows dom0's root device and VM block devices. 

**How Reproducible**

**To Reproduce**

1. Have ZFS as root, using qubes-storage-zfs as storage driver
2. See dom0 rpool visible on widget
3. Create vm on zfs_zvol pool. 
4. See VM block devices appear en-mass

**Expected behavior**

Block devices associated with VM and dom0 should not appear on device widget (and qvm-block for that matter), as is the case with (presumably) standard Qubes OS instances. 

**Actual behavior**

All block devices appear en-mass, obscuring most of my device widget list

**Screenshots**

![Screenshot_2021-06-23_14-22-27](https://user-images.githubusercontent.com/22207271/123148860-a5317c80-d42e-11eb-831f-482a432b4998.png)

**Additional context**

I could've sworn this issue didn't exist with r4.0. Mind you, I've been on r4.1 for many months, and just now have had the time to address this cosmetic issue, so my memory fails me here. Perhaps the backend migration from dbus to adminAPI caused this issue? 
Cannot test if this issue affects other configurations, as I do not have a space to install the standard configuration.
This isssue is no surprise with the qubes-storage-zfs driver as it is a WIP, far from being supported by Qubes (although a PR was opened by cfcs to merge it with qubes-admin-core). Since it affects zfs-as-root configurations, which (in my view) should at the very least be somewhat considered, I think this bug may be relevant to the Qubes team.

**Solutions you've tried**

I've tried going through qubes-desktop-linux-manager's source code to try to extrapolate where it differentiates between system block devices and addon block devices to no avail. I know enough of python to understand the generalities of what's happening, and can sometimes hack a solution together. I can attempt a fix here if someone can be so kind as to direct me towards the subroutine that does the differentiation. 

I could try to install to install an older version of this package to see if it's a bug that indeed didn't exist in the first version for r4.0 (4.0.1). As it isn't available for dom0's fc32 yum repo, I would have to build it myself, all the while suspecting it'll probably not work on r4.1.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

No relevant documentation in docs, tried going through forums to no avail.

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

Only relevant issues is #4301 that refers to a similar error with loop devices that was fixed in 4.0.11. A linked PR is the backend migration to AdminAPI, which informs my hypothesis that the bug might be coming from that migration.

**Comment by DemiMarie** [comment]
This is a udev rules problem: qube block devices are explicitly excluded from udev scanning and from inclusion in the device list, but somehow these devices are not being excluded.  I filed https://github.com/cfcs/qubes-storage-zfs/issues/3 to get these rules added.

Closing for now.  That said, using ZFS with the file or LVM pools should work, though the file pool is deprecated.  If you can reproduce the problem in such a configuration, please reopen this issue.
