### ISSUE TITLE
Firewall rules are not cleaned up

### ISSUE THREAD

**Issue by 3hhh** [QubesOS/qubes-issues#6733]
**Qubes OS version**

4.0

**Are you using any [testing](https://www.qubes-os.org/doc/testing/) repositories? If so, please list them AND where they are enabled (i.e., dom0, template, or standalone).**

no

**Are you providing feedback about a specific package or packages in testing? (If so, please list the package(s) here and [provide feedback in `updates-status`](https://www.qubes-os.org/doc/testing/#providing-feedback), linking to this issue.)**
no

**Affected component(s) or functionality**

qubes-firewall

**Brief summary**

When VMs are shut down, deleted or attached to other netvms, firewall rules in their firewall VM are not cleaned up.

**How Reproducible**

100%

**To Reproduce**

1. Shut down a VM, e.g. a disposable VM and remember its IP.
2. Check `nft list ruleset` in its netvm and find that it is still listed.

**Expected behavior**

The firewall rules do not contain deleted or shut down VMs.

**Actual behavior**

They contain deleted or shut down VMs.

**Additional context**

This may be bad in combination with race conditions (old rules still in place when a new VM is attached):
- if IPs are re-used
- if a VM is temporarily attached to another netvm, rules are changed and is attached back to its original netvm

**Solutions you've tried**

none

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

none

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

none

**Comment by unman** [comment]
This has been mentioned before.
When the qube is attached to a new netvm, the existing rules are
overwritten, so *that* shouldn't be an issue.
The same applies if an IP is reused.
You can check both of these yourself.
So, although the number and persistence of rules is a pain, I don't feel
it to be a security issue. (Could be wrong.)
nft provides atomic writes which should occur before the interface is
brought up - worth checking the scope for a race, but I don't think it
can happen.
