### ISSUE TITLE
Extend Cute Qubes icon family with qute-crown and qute-sushi icons

### ISSUE THREAD

**Issue by ninavizz** [QubesOS/qubes-issues#6738]
**The problem you're addressing (if any)**
dom0 is the most powerful VM within Qubes. As such, it deserves a little royal treatment.
However, with the addition of the qute-crown, the "Qute Qube" family's conceptual direction of communicating vague relational concepts is now muddled by the "star-qube" for Service VMs. As such, we now have the `qute-sushi` as an abstraction of "bringing-to" as a sort of junction-type block. These abstractions will hopefully be made clearer with illustrations that will be added to the docs for the 1st rc for 4.1

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/8262612/123857994-d8b15280-d8d7-11eb-87da-9b2c32d0062a.png)

**Where is the value to a user, and who might that user be?**
A visual differentiator between "everyday" qubes users interact with, and the king of all king qubes. 

**Describe alternatives you've considered**
Marta had previously created a version of the Black qube with an exclamation point over it—but that communicated more of an "Error State" semiotic. The crown on the qute-qube icon does not speak to any other common semiotic in computing, while still speaking to concepts of hierarchy. 

**Additional context**
It's qute!

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

n/a

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

#5676

**Comment by SvenSemmler** [comment]
My first impression of this icon was a little blue man inside the box 
throwing up his arms. :-)

Maybe put the crown on one side of the qube?

**Comment by ninavizz** [comment]
@SvenSemmler LOL, I will poke at it a bit to see what I can do. It's veeeeery hard to get icons to work well, at the 16x16 and 20x20 small-sizes. 

I tried one, earlier, that was fully square—which required the cube itself to be much smaller than the other qube icons in the list. Also tried one with a "golden" crown. The color yelow evokes "things" in computing UIs, so that felt a little prudent to avoid. Blue only evokes actionability, but it's also the Qubes OS brand color.

![image](https://user-images.githubusercontent.com/8262612/123346458-35de8a00-d50d-11eb-8f7b-6ae033958162.png)

So—to make the qube the same size as the other qube, the artwork needs to have the dimensions of a rectangle. Doing a version that is wider than it is tall, could make it difficult to keep nicely aligned with the other icons. Right now, we're able to compensate for this one being taller than all the other `qute qube` icons by just giving `dom0` more vertical space in the app menu and Qube Manager—which also makes sense, for "because it's dom0!" reasons. 

I will absolutely try, tho!

Until then, @marmarta I made these for ya. Let me know how they work? 
[qute-dom0.zip](https://github.com/QubesOS/qubes-issues/files/6712635/qute-dom0.zip)

**Comment by ninavizz** [comment]
@SvenSemmler Thoughts on this updated dom0 icon? @marmarta? 

![image](https://user-images.githubusercontent.com/8262612/123355658-fa4abc80-d51a-11eb-8736-9e5cd5a90be2.png)

**Comment by DemiMarie** [comment]
@ninavizz looks good to me!

**Comment by SvenSemmler** [comment]
@ninavizz looks good to me too! I like that it has the same basic shape as all the other qubes now but still stands out as the "king of qubes"

**Comment by ninavizz** [comment]
Marta, Marek, and Andrew are all on holiday right now, so this is not a priority for them—but I eagerly anticipate it hitting their radar(s) for feedback. I'm really partial to the crown above the qube, as I feel it is much cuter—but I also agree @SvenSemmler that from a visual-scanning vantage and for simple practicality, it's better for the shape to be more self-contained. TY for the nudge to further explore this! I gotta admit—it usually takes _dozens_ and dozens of versions of an icon, to get it "right," and so far the qute qubes family of icons have received the smallest investment of time I have ever dedicated to a single icon, let alone a family of them. :)

**Comment by andrewdavidwong** [comment]
Updated version looks good to me too.

**Comment by ninavizz** [comment]
Ok, this demonstrates "the latest," including a new icon for Standalone Qubes—and the complete family for Service qubes, across all 8 colors. Symbolically, this is the most consistent in applying the logic of how/why for all the different details. 

For dom0 there are 2 alternate variants that are labeled, and my own (soft) preference is in the UI. I still really like the blue crown atop the black qube, but its asymmetric shape as an icon could be a problem. For the one in the UI right now, it reminds me of the Westinghouse logo a bit much—and it's not quite as cute as the blue crown one.

For the Standalone Qubes and Service Qubes, I extended both families across color variants. 

@marmarek @marmarta @andrewdavidwong whenever y'all have a chance, I'd love your thoughts on this! Only not cc'ing Demi and Sven, as they've already shared their thoughts. 

![QM_Iterative-01ii](https://user-images.githubusercontent.com/8262612/123490888-25d8b000-d5ca-11eb-85c4-050d0da8d4e6.png)

**Comment by andrewdavidwong** [comment]
Looks good to me.

**Comment by marmarek** [comment]
I think the current in-UI icon is nice too! IMO the asymmetric one (var.1) is not a problem in the manager, but indeed could be a problem in other places.

**Comment by GWeck** [comment]
The current version with the crown inside the cube looks for me the best, too.

Just one disturbing thought: For Spanish speaking people, a crown is called "corona", and currently that word is not only associated with a beer - which would be fine for me - but also with COVID-19, which is not nice after all .., ;-)

**Comment by ninavizz** [comment]
@GWeck COVID social-terror support for iconography within Qubes OS is out of scope for the complete `4.x` release family. We hope to have the coverage to address these user concerns, in time for the `5.x` version family of Qubes OS. Thank you for sharing this relevant perspective (she says, with a touch of snark and a big eyeroll followed by a healthy facepalm of exhaustion with this entire silly pandemic).

**Comment by ninavizz** [comment]
Per Marek's nudges, I've made some improvements to the qute-sushi icons—shown below. While the improvements may seem exceedingly minor, I hope they will make their rendering at-size, cleaner. Only way to tell, though, is to plop them into the code and see how the OS itself, renders them. 

I'll be attaching new SVGs here, later this evening.

Two questions for @marmarta 
1. In the initial implementations of the qute-qubes icons, they were getting cut off. Was that because of a code problem, or did you need to use the SVGs with a pixel of white space all around the icons, to mitigate that?
2. What exactly are the dimensional-spec needs (pixel sizes) for the icons needed for the app menu and qube manager? 18x18 or 20x20 or 16x16? SVG and PNG, or just SVG?

![QM_Iterative-01jj](https://user-images.githubusercontent.com/8262612/123862533-4d3ac000-d8dd-11eb-8c71-64e50709d310.png)

**Comment by ninavizz** [comment]
Never heard back from ya regarding the above @marmarta (even tho I had said I'd ping the above inquiry elsewhere, but then pinged here, heh)... so I poked around the `qubes-artwork` repo and found the only qute-qube SVGs existing for 48x48. 

If in fact the app menu and Qubes Manager qute-qube icons are all rendered from those same 48x48 SVGs, then the below directory is our oyster! If you need PNGs created at 16x16, 22x22, 24x24, 32x32, 36x etc., let me know. :) 

NOTE: The below SVGs were created as 48x48 SVGs per the `qubes-artwork` repo, but the artwork itself is optimised for use at sizes at or below 32x32. Should icons be needed for uses larger than that, different artwork would be preferred. 

[QuteNu_Jun30.zip](https://github.com/QubesOS/qubes-issues/files/6738833/QuteNu_Jun30.zip)

**Comment by ninavizz** [comment]
Note: The "qute-sushi" moniker is internal and developer-facing name, only; and was created to differentiate the updated Service qube icon (speaking to plug/socket metaphor), from the star-on-qube icon. In release notes and documentation, it should simply be spoken to as the "Service Qube" icon.   

The admin-qube icon should also follow that same convention. However, the crown being such a unique symbol apart from any other currently used in Qubes OS iconography, calling it the "Crown Qube" or the "Queen/King Qube" icon is ok, too.

**Comment by marmarek** [comment]
All applied (qubesos/qubes-artwork#24).
