### ISSUE TITLE
 hardware does not support iommu / vt-d

### ISSUE THREAD

**Issue by broros** [QubesOS/qubes-issues#6741]
**Qubes OS version**
R4.0.4

I have installed Qubes os on my computer, everything works except virtualization is not detected and is giving me a warning message "hardware does not support iommu / vt-d"

my motherboard is: ASUS P8Z77-V LX

my processor is: i5-3570k

https://ark.intel.com/content/www/us/en/ark/products/65520/intel-core-i5-3570k-processor-6m-cache-up-to-3-80-ghz.html

I enabled the  Virtualization Technology (VT-x) and still not working..

any suggestions?

**Comment by broros** [comment]
I can confirm that in windows 10 Virtualization is running under "system information"
also, it shows virtualization is enable under task manager->  performance

**Comment by njk2002** [comment]
VT-x and VT-d isn't the same thing. 
In the Intel Ark, it says:
 Intel® Virtualization Technology (VT-x) ‡ Yes
Intel® Virtualization Technology for Directed I/O (VT-d) ‡ No
So unfortunately, you don't meet the hardware requirements. 
@andrewdavidwong Please close this as not an issue.

**Comment by andrewdavidwong** [comment]
Closing as "not an issue." If you believe this is a mistake, please leave a comment, and we'll be happy to take another look. Thank you.
