### ISSUE TITLE
Extend Qute Qubes icon family with qute-standalone

### ISSUE THREAD

**Issue by ninavizz** [QubesOS/qubes-issues#6745]
**The problem you're addressing (if any)**
To date, "Standalone" qubes have been a not-terribly-visible feature within Qubes OS. 

While endeavoring #6738 the below was also devised as a nice icon to communicate "a different but contained thing" within the Qute Qubes family. While it will always be a cognitive leap to communicate precise meaning of highly abstract and domain specific concepts within 18x18 icons, at a minimum it will help lift the visibility of "Oh, a VM that is neither the parent nor the spawn of another VM exists in this Qubes OS universe? Hmm!" 

**Describe the solution you'd like**
"Done" is better than "Perfect," and if the below does not suck, I would like to propose its implementation as a v1 to giving Standalone VMs their own marker within the Qubes OS UI. Because Standalone Qubes today inherit the same icon as App Qubes, simply making the change in the code that Standalone Qubes get their own icon, will be a great step forward.

![image](https://user-images.githubusercontent.com/8262612/123859905-1911d000-d8da-11eb-97d3-0baa72f0968f.png)

**Where is the value to a user, and who might that user be?**

Within the context of using Qubes OS, users can visibly see that there is such a thing as a qube that no other qube is based upon, and a qube that is not a derivative of another qube.

**Describe alternatives you've considered**

Today a Standalone qube is marked as such, in the Qubes Manager tool. That is a nice distinction, but if an icon could also passive information as a reinforcement of this paradigm, that would also be lovely.

**Additional context**

nope.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

nope.

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

#5676

**Comment by ninavizz** [comment]
To me, this should not be added to the rc1 for `4.1` as it is not as simple as overwriting existing icons. It also creates a new class of icon, where none previously existed. If it would make testing easier and go faster, then I see no reason for it to not go in with #6738 but I will leave this up to @marmarta to decide.

**Comment by ninavizz** [comment]
Labeled this issue "Help Wanted," because none of the core Qubes OS team are likely to be able to prioritize this anytime soon, abreast critical project priorities. That said: to me, this feels like an helpful addition to the UI. 

The core Qubes team have given their blessing to this UX solution, so should a developer like to take this on pls "@" me here and I'll hop-to gathering final SVG artwork to make this possible.

**Comment by Narvey** [comment]
OK I'm working on it at https://github.com/Narvey/qubes-artwork/tree/patch-1/icons/scalable/apps

**Comment by Narvey** [comment]
Sorry I got busy and didn't finish this. Thanks @marmarta  for finishing where I left off.
