### ISSUE TITLE
change PGP key links on Team page to updated, maintained, opt-in keyserver https://key.openpgp.org ?

### ISSUE THREAD

**Issue by mfc** [QubesOS/qubes-issues#6746]
keys.gnupg.net is currently having issues, and was part of SKS keyservers pool which is no longer maintained/working, see notice: https://sks-keyservers.net/

I think core team at minimum should make sure their keys (and all Qubes OS-related keys?) are on https://key.openpgp.org and we link to those keys for reliable access to PGP keys. I don't know if we want to explore having a [Web Key Directory](https://wiki.gnupg.org/WKD) like debian, gentoo, and some others listed in the doc.

**Comment by DemiMarie** [comment]
We should also provide the keys via direct download from our website and via a package.

**Comment by andrewdavidwong** [comment]
> We should also provide the keys via direct download from our website

In the past, the decision was made not to do this and instead to use public keyservers, as we don't want to have to manually maintain our own keyserver. Unless I'm told that this has changed, I'll presume it still holds.

> and via a package.

I'm guessing you mean something like an RPM or deb package rather than qubes-secpack (since the latter already exists). I will leave this up to you and the other devs to decide.

I consider both of these to be out-of-scope for the current issue, which I'm limiting to fixing only this problem, per https://www.qubes-os.org/doc/issue-tracking/#every-issue-must-be-about-a-single-actionable-thing:
> keys.gnupg.net is currently having issues, and was part of SKS keyservers pool which is no longer maintained/working, see notice: https://sks-keyservers.net/
> 
> I think core team at minimum should make sure their keys (and all Qubes OS-related keys?) are on https://key.openpgp.org and we link to those keys for reliable access to PGP keys. 

Everything else should be filed as (a) separate issue(s), as appropriate.

**Comment by andrewdavidwong** [comment]
Done. All PGP key links on https://www.qubes-os.org/team/ now use the new keyserver. I've just tested each link to make sure that each key can be downloaded successfully.

**Comment by mfc** [comment]
thanks @andrewdavidwong

**Comment by andrewdavidwong** [comment]
Example of user confusion regarding the new keyserver:
https://forum.qubes-os.org/t/contribute-to-qubes-os-how-to-get-a-valid-gpg-key-for-the-signature-checker-bot/1449/4?u=adw

**Comment by mfc** [comment]
i don't totally understand the issue, but if the issue is that some team members haven't confirmed their keys at keys.openpgp.org and they are not responsive, we could point to their keys on another still-existing keyserver that used used to be part of SKS, like keys.mayfirst.org or otherwise. maybe that would have been better intermediary step.

**Comment by andrewdavidwong** [comment]
> i don't totally understand the issue, but if the issue is that some team members haven't confirmed their keys at keys.openpgp.org and they are not responsive, we could point to their keys on another still-existing keyserver that used used to be part of SKS, like keys.mayfirst.org or otherwise. maybe that would have been better intermediary step.

I've set up the page to generate every keyserver URL automatically from each person's fingerprint, meaning we can't use different keyserver URLs for different team members without going back to a more error-prone, labor-intensive system of manually specifying the URL for each person. I am not willing to do that.

**Comment by unman** [comment]
On Sun, Jul 25, 2021 at 02:02:04PM -0700, Andrew David Wong wrote:
> > i don't totally understand the issue, but if the issue is that some team members haven't confirmed their keys at keys.openpgp.org and they are not responsive, we could point to their keys on another still-existing keyserver that used used to be part of SKS, like keys.mayfirst.org or otherwise. maybe that would have been better intermediary step.
> 
> I've set up the page to generate every keyserver URL automatically from each person's fingerprint, meaning we can't use different keyserver URLs for different team members without going back to a more error-prone, labor-intensive system of manually specifying the URL for each person. I am not willing to do that.
> 

I think one issue is that (I think) the user has to upload the key
themselves to generate the confirmation prompt. This may be a source of
confusion as the key is already there.

Of the keys on the server, 6 cannot be imported:
User research
Wojtek Porczk
Michal Chilinski
Joanna Golebiewska
Nina Eleanor Alter
Simon Gaiser

**Comment by unman** [comment]
On Fri, Jul 30, 2021 at 12:56:08PM +0100, unman wrote:
> On Sun, Jul 25, 2021 at 02:02:04PM -0700, Andrew David Wong wrote:
> > > i don't totally understand the issue, but if the issue is that some team members haven't confirmed their keys at keys.openpgp.org and they are not responsive, we could point to their keys on another still-existing keyserver that used used to be part of SKS, like keys.mayfirst.org or otherwise. maybe that would have been better intermediary step.
> > 
> > I've set up the page to generate every keyserver URL automatically from each person's fingerprint, meaning we can't use different keyserver URLs for different team members without going back to a more error-prone, labor-intensive system of manually specifying the URL for each person. I am not willing to do that.
> > 
> 
> I think one issue is that (I think) the user has to upload the key
> themselves to generate the confirmation prompt. This may be a source of
> confusion as the key is already there.
> 
> Of the keys on the server, 6 cannot be imported:
> User research
> Wojtek Porczk
> Michal Chilinski
> Joanna Golebiewska
> Nina Eleanor Alter
> Simon Gaiser

Apologies for spellings on those names.

**Comment by SvenSemmler** [comment]
On 7/30/21 6:56 AM, unman wrote:
> I think one issue is that (I think) the user has to upload the key
> themselves to generate the confirmation prompt. This may be a source of
> confusion as the key is already there.

I got the prompt automatically when @andrewdavidwong uploaded the keys, 
then followed the link and verified the fingerprint -- then confirmed.

Maybe this email ended up in the Spam folder or was sent to an old email 
address no longer monitored for Wojtek, Michal, Joanna, Nina & Simon?

-- 
  public key: https://www.svensemmler.org/2A632C537D744BC7.asc
fingerprint: DA59 75C9 ABC4 0C83 3B2F 620B 2A63 2C53 7D74 4BC7

**Comment by andrewdavidwong** [comment]
> Maybe this email ended up in the Spam folder or was sent to an old email address no longer monitored for Wojtek, Michal, Joanna, Nina & Simon?

I directly emailed all core team members about this at their current email addresses around three weeks ago with an explanation of the transition, instructions, links, etc. Presumably, they are aware but have decided not to proceed with the approval.
