### ISSUE TITLE
TestDeploy creates link to wwwpreview.qubes-os.org, which says "Access forbidden!... Error 403"

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#6747]
**Affected component(s) or functionality**

Website CI `TestDeploy`

**Brief summary**

In https://github.com/QubesOS/qubesos.github.io/pull/180, I issued the `TestDeploy` command. This resulted in a GUI element on the webpage showing the following text:

```
This branch was successfully deployed
1 active deployment
qa
— 1f863f11 Deployed 6 minutes ago by qubesos-bot
```

There is a button called "View deployment," which links to:

https://wwwpreview.qubes-os.org/

When I click the button to go to this URL, the page says:

```
Access forbidden!
You don't have permission to access the requested directory. There is either no index document or the directory is read-protected.

If you think this is a server error, please contact the webmaster.

Error 403
wwwpreview.qubes-os.org
Apache
```

**Expected behavior**

Live testing version of the website, like https://wwwtest.qubes-os.org/.

**Actual behavior**

https://wwwpreview.qubes-os.org/

with contents:

```
Access forbidden!
You don't have permission to access the requested directory. There is either no index document or the directory is read-protected.

If you think this is a server error, please contact the webmaster.

Error 403
wwwpreview.qubes-os.org
Apache
```

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

Just updated:

https://www.qubes-os.org/doc/doc-guidelines/#continuous-integration-ci

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

None found.

**Comment by marmarek** [comment]
You need to wait with TestDeploy command until website build completes. Otherwise it deploys an empty site...

**Comment by andrewdavidwong** [comment]
> You need to wait with TestDeploy command until website build completes. Otherwise it deploys an empty site...

Oh, I had no idea. I'll add that to the [documentation](https://www.qubes-os.org/doc/doc-guidelines/#continuous-integration-ci). Can we also get some kind of feedback to indicate this? Or is that not worth coding if we're the only ones using it?

**Comment by andrewdavidwong** [comment]
What's with the two different URLs (wwwtest vs wwwpreview)?

**Comment by marmarek** [comment]
wwwtest is manually uploaded, wwwpreview is managed with "testdeploy" command.

**Comment by andrewdavidwong** [comment]
> Can we also get some kind of feedback to indicate this? Or is that not worth coding if we're the only ones using it?

Guessing this part is a "won't do."

I've documented everything discussed here. Closing as completed with documentation only.
