### ISSUE TITLE
Hardware support: HP 840 G7 (intel gen 10). - R4.1 - New dom0 kernel are unusable

### ISSUE THREAD

**Issue by neowutran** [QubesOS/qubes-issues#6748]
**Qubes OS version**

R4.1

**Are you using any [testing](https://www.qubes-os.org/doc/testing/) repositories? If so, please list them AND where they are enabled (i.e., dom0, template, or standalone).**

Yes everything testing

**Are you providing feedback about a specific package or packages in testing? (If so, please list the package(s) here and [provide feedback in `updates-status`](https://www.qubes-os.org/doc/testing/#providing-feedback), linking to this issue.)**
Yes, dom0 kernel

**Affected component(s) or functionality**

Everything ? ( System is unusably slow) 

**Brief summary**

System cannot be used with recent kernel, it is way too slow. 
( In the screen to type the disk decryption password, everything lag. 1seconds+ delay between key press and the bullet showing on the screen. + graphical glitch ) 

**How Reproducible**

Hardware specific.
But 100%

**To Reproduce**
Hardware specific.

With a old dom0 kernel (5.4.67-1.qubes.x86_64 to be precise), system work as expected. 

With all the more recent kernel, system is not  usable. (More than 90% performance drop, + graphical glitch) 
( 5.10.42-1.fc32.qubes.x86_64, 5.10.43-1.fc32.qubes.x86_64, 5.12.10-1.fc32.qubes.x86_64 )
( I notice the ".fc32" string that don't exist in the oldest dom0 kernel ) 

**Expected behavior**

Standard performance

**Actual behavior**

Impossibly slow performances

**Screenshots**

**Additional context**

**Solutions you've tried**

- https://github.com/QubesOS/qubes-issues/issues/6617#issuecomment-843442468 , will retry, but don't seem to solve the issue
- Modifying the grub command line to use the "5.4.67-1.qubes.x86_64" entry and just replace the kernel version (to be sure that the options are the same ) 
- using a old dom0 kernel (5.4.67-1.qubes.x86_64)

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

None

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

Related, but don't think they are the same issues:

https://github.com/QubesOS/qubes-issues/issues/6411

https://github.com/QubesOS/qubes-issues/issues/6617

**Comment by bigdx** [comment]
I can confirm the glitches at the LUKS password and in qubes visual glitches of the mouse pointer (i.e. when switching between cursor- and arrow-symbol or while entering/exiting windows), but no other performance problems yet. It's a Intel Gen 11, not 10. With kernel 5.4 no glitches.

**Comment by neowutran** [comment]
( closing the issue, seems to be fixed )
