### ISSUE TITLE
secure paste broken in Qubes R4.1

### ISSUE THREAD

**Issue by 0spinboson** [QubesOS/qubes-issues#6749]
**Qubes OS version**

Qubes R4.1

**Are you using any [testing](https://www.qubes-os.org/doc/testing/) repositories? If so, please list them AND where they are enabled (i.e., dom0, template, or standalone).**

current-testing in both dom0 and vm templates

**Are you providing feedback about a specific package or packages in testing? (If so, please list the package(s) here and [provide feedback in `updates-status`](https://www.qubes-os.org/doc/testing/#providing-feedback), linking to this issue.)**

**Affected component(s) or functionality**

secure paste

**Brief summary**

a recent update (from the past two weeks or so?)

**How Reproducible**

100%

**To Reproduce**

1. secure copy something
2. try to secure paste (using ctrl-shift-v, in my case)
3. nothing

**Expected behavior**

works

**Actual behavior**

doesn't work. secure copy does still work though

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

Do not delete this section. Instead, replace this block of text with a list of
any relevant documentation you've consulted. We do not know what you've already
read unless you tell us. If you do not list anything, we will assume that you
haven't read any relevant documentation. If you're not aware of any relevant
documentation, write "None" (or "N/A" if not applicable).

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

Do not delete this section. Instead, replace this block of text with a list of
any related issues of which you're aware. Do not describe any other unreported
bugs, features, or tasks here. We do not know which issues you've already seen
unless you tell us. If there is another issue that seems like a duplicate, and
you did not mention it here, we will assume that you were not aware of it. If
you didn't find any related issues, write "None found."

**Comment by fepitre** [comment]
I don't reproduce it at all as I'm using R4.1 since one year and currently it is updated. Can you at least provide dom0: `sudo rpm -qa | grep qubes | sort`. Also, can you check that the secure copy paste keys are properly set in Qubes Global Settings please?

**Comment by 0spinboson** [comment]
of course. 
Secure copy & paste are both set to default key combination in dom0

[qubeslist.log](https://github.com/QubesOS/qubes-issues/files/6739592/qubeslist.log)

**Comment by marmarek** [comment]
Is `qubes-qrexec-policy-daemon` service running? Take also a look at `/var/log/qubes/guid.<qube>.log`, where `<qube>` is the qube where you paste to.

**Comment by 0spinboson** [comment]
How strange. Wasn't running, and the service was missing from the autostart list in /usr/lib/systemd/system. Thanks, sorry it was so boring. Tried to find which service performed this task before creating a bug report but I didn't quite know what to look for.
