### ISSUE TITLE
During installation it showed: Start failed: internal error: libxenlight failed to create new domain 'sys-firewall’

### ISSUE THREAD

**Issue by sudomonzter** [QubesOS/qubes-issues#6753]
Qubes os version is 4.0.4

**Brief summary**

While installing a fresh installation of 4.0.4 and the installation at the configuring networking it showed **“Start failed: internal error: libxenlight failed to create new domain 'sys-firewall.’**

Do not delete this section. Instead, replace this block of text with a list of
any relevant documentation you've consulted. We do not know what you've already
read unless you tell us. If you do not list anything, we will assume that you
haven't read any relevant documentation. If you're not aware of any relevant
documentation, write "None" (or "N/A" if not applicable).

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

Do not delete this section. Instead, replace this block of text with a list of
any related issues of which you're aware. Do not describe any other unreported
bugs, features, or tasks here. We do not know which issues you've already seen
unless you tell us. If there is another issue that seems like a duplicate, and
you did not mention it here, we will assume that you were not aware of it. If
you didn't find any related issues, write "None found."

**Comment by andrewdavidwong** [comment]
Please provide your hardware details.
