### ISSUE TITLE
sys-usb: faster dom0 keyboard & mouse redirection

### ISSUE THREAD

**Issue by Osndok** [QubesOS/qubes-issues#6755]
### Checklist
- [x] This issue follows the [Issue Tracking Guidelines](https://www.qubes-os.org/doc/issue-tracking/#guidelines).
- [x] I have [searched both open and closed issues](https://www.qubes-os.org/doc/issue-tracking/#search-tips) for duplicates.

-----
### The problem you're addressing (if any)

When using a hardware KVM with a qubes machine that uses sys-usb w/ keyboard & mouse redirection, it usually takes several seconds for qubes to notice the device and pass it to dom0.

### Describe the solution you'd like

I would like for new keyboards & mice to be fully usable within one second of them being connected. Other OSes respond within milliseconds.

### Where is the value to a user, and who might that user be?

In addition to pleasing the (very few) users of hardware KVM switches, I imagine that any gains here will also be felt by all users of usb keyboards & mice during boot (when there is a disk password field that does not accept input for some time).

### Describe any alternative solutions you've considered

Waiting the five seconds (or so) that it currently takes, wiggling the mouse and pressing keys until the black screen awakes.

### Additional context

None

-----
### Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted

* https://www.qubes-os.org/doc/usb-qubes/#enable-a-usb-keyboard-for-login
* https://github.com/QubesOS/qubes-app-linux-usb-proxy

### Related, [non-duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) issues

* #2270

**Comment by marmarek** [comment]
>  it usually takes several seconds for qubes to notice the device and pass it to dom0.

Hmm, I do have similar setup, and I have them working instantly after the switch. Can you check what takes so long? Start by looking at sys-usb logs to see when exactly the device gets connected.

**Comment by Osndok** [comment]
I left dmesg running in a terminal, and when I switch back... it promptly shows a flurry of activity when I switch to the qubes device (new usb devices and whatnot), but it is still several seconds before I can actually control the keyboard & mouse. During & after this limbo period, there are no additional dmesg entries.

**Comment by marmarek** [comment]
Can you check also `journalctl` in sys-usb, especially when `Qubes input proxy sender` or `qubes-input-sender-...` is started?

**Comment by andrewdavidwong** [comment]
Are you on R4.0?

**Comment by Osndok** [comment]
@marmarek attached
[sys-usb-journalctl.txt](https://github.com/QubesOS/qubes-issues/files/6756910/sys-usb-journalctl.txt)
 is a clip from journalctl for one round of me "leaving & returning" with those events (as well as the perceived pause) marked.

One thing that is not captured in this text format is that it has highlighted a few lines in yellow/red/blue, such as:
```
Jul 02 15:06:47 sys-usb kernel: usb 2-10.2: 4:1: cannot get freq at ep 0x84
...
Jul 02 15:06:48 sys-usb systemd-udevd[9200]: event8: Failed to call EVIOCSKEYCODE with scan code 0x7008b, and key code 107: Invalid argument
...
Jul 02 15:06:57 sys-usb gnome-terminal-[1456]: gdkproperty-x11.c:224 invalid X atom: 2836589690
```

@andrewdavidwong - yes, I am using R4.0

**Comment by marmarek** [comment]
So you say the delay is after "Started Qubes input proxy sender" messages, right?

**Comment by Osndok** [comment]
That's correct. I just tried what you asked, and found that journalctl in dom0 does not produce any messages just before or during this pause. The first relevant messages (appearing only after the pause) are:
```
Jul 02 22:56:21 cubi dbus-daemon[8019]: [session uid=1000 pid=8019] Activating via systemd: service name='org.freedesktop.Notifications' unit='xfce4-notifyd.service' requested by ':1.693' (uid=1000 pid=14039 comm="/usr/bin/python3 /usr/bin/qui-devices ")
Jul 02 22:56:21 cubi systemd[7913]: Starting XFCE notifications service...
Jul 02 22:56:21 cubi dbus-daemon[8019]: [session uid=1000 pid=8019] Successfully activated service 'org.freedesktop.Notifications'
Jul 02 22:56:21 cubi systemd[7913]: Started XFCE notifications service.
Jul 02 22:56:30 cubi qrexec[27322]: qubes.InputMouse: sys-usb -> dom0: allowed to dom0
Jul 02 22:56:30 cubi qrexec[27321]: qubes.InputKeyboard: sys-usb -> dom0: allowed to dom0
Jul 02 22:56:30 cubi qrexec[27323]: qubes.InputKeyboard: sys-usb -> dom0: allowed to dom0
Jul 02 22:56:30 cubi qrexec[27324]: qubes.InputKeyboard: sys-usb -> dom0: allowed to dom0
Jul 02 22:56:30 cubi qrexec[27325]: qubes.InputKeyboard: sys-usb -> dom0: allowed to dom0
Jul 02 22:56:30 cubi qrexec[27326]: qubes.InputMouse: sys-usb -> dom0: allowed to dom0
Jul 02 22:56:31 cubi kernel: input: sys-usb: Kinesis Advantage2 Keyboard System Control as /devices/virtual/input/input678
Jul 02 22:56:31 cubi systemd-udevd[27393]: Error calling EVIOCSKEYCODE on device node '/dev/input/event4' (scan code 0x7008b, key code 107): Invalid argument
Jul 02 22:56:31 cubi systemd-udevd[27393]: Error calling EVIOCSKEYCODE on device node '/dev/input/event4' (scan code 0x700e3, key code 104): Invalid argument
Jul 02 22:56:31 cubi systemd-udevd[27393]: Error calling EVIOCSKEYCODE on device node '/dev/input/event4' (scan code 0xc0183, key code 109): Invalid argument
Jul 02 22:56:31 cubi systemd-udevd[27393]: Error calling EVIOCSKEYCODE on device node '/dev/input/event4' (scan code 0xc0223, key code 102): Invalid argument
```

**Comment by marmarek** [comment]
So, you mean you get "Started Qubes input proxy sender" messages in sys-usb, then a pause and only then "qrexec" messages in dom0? That sounds weird, because qubes-input-sender first connects to dom0 even before opening the device. Do you see similar delay if you execute any other qrexec call (like file copy)?

**Comment by Osndok** [comment]
That's right. I just tested it again to be doubly sure. With both windows open I can see the start message in sys-usb, experience a significant delay, and only then do I see the first qrexec journalctl message appears only after the delay.

I always assumed there was some kind of "poll for new devices every 5 seconds" logic (which is why I initially phrased this as an enhancement). File copies between VMs are quite snappy (no noticeable delay between when the destination prompt comes up or the file copy starts).

If you can point me to where the "Started Qubes input proxy sender" is sent (in a python script, I presume), I might be able to add a bunch of logging statements to further refine where the delay is coming from.

**Comment by marmarek** [comment]
Generally, the whole thing lives in https://github.com/QubesOS/qubes-app-linux-input-proxy.
On the sys-usb side, there is [`/usr/bin/qubes-input-sender`](https://github.com/QubesOS/qubes-app-linux-input-proxy/blob/master/qubes-rpc/qubes-input-sender) started via a systemd service (the thing you see as "Started Qubes input proxy sender". It uses `qrexec-client-vm` to call relevant qrexec service (either `qubes.InputMouse` or `qubes.InputKeyboard`) in dom0. There, it goes through a policy in `/etc/qubes-rpc/policy/qubes.Input*` and then into the actual scripts in `/etc/qubes-rpc/qubes.Input*` (which are actually one-liners calling `/usr/bin/input-proxy-receiver` - binary handling the input events).
See also README in that repository for more details.

**Comment by Osndok** [comment]
I managed to shim an strace in (thank you script glue!). Keeping in mind that I'm not entirely sure what I'm looking at, I do have some observations:
* even though I think of my setup as "a keyboard & mouse", there are actually 6 HID devices for qubes to init. This could indicate that users with many input devices are effected, and mean that I could shave off a few seconds by discarding old entries in my logitech unifying receiver or unplugging my trackpad, etc.
* there seems to be a one second delay between starting the first two (keyboard & mouse) and the remaining four. Maybe a systemd anti-thrashing feature?
* each of the six processes experience (at least) a one second delay in their first read() from the qrexec pipe... so maybe part of the issue is really on the dom0 side?
* /usr/bin/qubes-input-sender should probably `exec` the qrexec helpers, rather than waiting around to do nothing

[strace-timings-6755.tar.gz](https://github.com/QubesOS/qubes-issues/files/6760007/strace-timings-6755.tar.gz)

**Comment by marmarek** [comment]
Thanks for the logs. I see about 1.5s delay before sys-net calling into dom0, and getting the call accepted:
```
19:34:16.272547 connect(3, {sa_family=AF_UNIX, sun_path="/var/run/qubes/qrexec-agent"}, 29) = 0
19:34:16.282291 connect(3, {sa_family=AF_UNIX, sun_path="/var/run/qubes/qrexec-agent"}, 29) = 0
19:34:17.188723 connect(3, {sa_family=AF_UNIX, sun_path="/var/run/qubes/qrexec-agent"}, 29) = 0
19:34:17.246127 connect(3, {sa_family=AF_UNIX, sun_path="/var/run/qubes/qrexec-agent"}, 29) = 0
19:34:17.280106 connect(3, {sa_family=AF_UNIX, sun_path="/var/run/qubes/qrexec-agent"}, 29) = 0
19:34:17.338025 connect(3, {sa_family=AF_UNIX, sun_path="/var/run/qubes/qrexec-agent"}, 29) = 0
19:34:18.662964 socketpair(AF_UNIX, SOCK_STREAM, 0, [4, 5]) = 0
19:34:18.663069 socketpair(AF_UNIX, SOCK_STREAM, 0, [6, 7]) = 0
19:34:18.664400 socketpair(AF_UNIX, SOCK_STREAM, 0, [4, 5]) = 0
19:34:18.664435 socketpair(AF_UNIX, SOCK_STREAM, 0, [6, 7]) = 0
19:34:18.669565 socketpair(AF_UNIX, SOCK_STREAM, 0, [4, 5]) = 0
19:34:18.669605 socketpair(AF_UNIX, SOCK_STREAM, 0, [6, 7]) = 0
19:34:18.670606 socketpair(AF_UNIX, SOCK_STREAM, 0, [4, 5]) = 0
19:34:18.670648 socketpair(AF_UNIX, SOCK_STREAM, 0, [6, 7]) = 0
19:34:18.682241 socketpair(AF_UNIX, SOCK_STREAM, 0, [4, 5]) = 0
19:34:18.682279 socketpair(AF_UNIX, SOCK_STREAM, 0, [6, 7]) = 0
19:34:18.691635 socketpair(AF_UNIX, SOCK_STREAM, 0, [4, 5]) = 0
19:34:18.694441 socketpair(AF_UNIX, SOCK_STREAM, 0, [6, 7]) = 0
```
The `connect` calls are before contacting dom0 and `socketpair` (two per device) are after connecting. And you can see all 6 devices were accepted around the same time, even when initial requests were at different times. So, the question is: what is dom0 doing at this time, that prevents it responding immediately. In your earlier log, I see messages about "XFCE notifications service" - that is likely related to showing new device notification. That should not block anything, at least in theory. But, maybe try anyway: stop the devices widget (responsible for this part): `systemctl --user stop .qubes-widget@qui-devices`

**Comment by Osndok** [comment]
Stopping that service does not improve the overall delay by any noticeable amount. :(

**Comment by Osndok** [comment]
Now on kernel `5.4.156-1.fc25.qubes.x86_64` / `4.0`

I've noticed what seems to be a closely related symptom.

If I run a `qvm-run` commands in the dom0 terminal serially, they each complete with a somewhat uniform but still higher than expected latency (350ms).

```
$ time for i in $(seq 1 10) ; do time qvm-run -p personal "echo $i" ; done
1

real	0m0.409s
user	0m0.066s
sys	0m0.041s
2

real	0m0.355s
user	0m0.068s
sys	0m0.045s
[ ... SNIP ...]
9

real	0m0.353s
user	0m0.069s
sys	0m0.046s
10

real	0m0.353s
user	0m0.066s
sys	0m0.047s

real	0m3.612s <--- total time
user	0m0.672s
sys	0m0.471s
```

But if I run the `qvm-run` calls in parallel... three of them are executed semi-quickly (1.5s), then there is a long pause (6 seconds), and then the rest complete at more or less the same time:

```
[robert@cubi /]$ for i in $(seq 1 10)
> do
> time qvm-run -p personal "echo $i" < /dev/null &
> done
[1] 555
[2] 556
[3] 557
[4] 559
[5] 561
[6] 563
[7] 566
[8] 568
[9] 570
[10] 571
[robert@cubi /]$ 6

real	0m1.517s
user	0m0.067s
sys	0m0.046s
8

real	0m1.625s
user	0m0.072s
sys	0m0.044s
4

real	0m1.650s
user	0m0.071s
sys	0m0.046s
9

real	0m5.997s
user	0m0.069s
sys	0m0.042s
10
vchan connection timeout

real	0m6.301s
user	0m0.068s
sys	0m0.046s

real	0m6.318s
user	0m0.072s
sys	0m0.044s
2

real	0m6.370s
user	0m0.073s
sys	0m0.045s
3
1

real	0m6.479s
user	0m0.065s
sys	0m0.052s

real	0m6.490s
user	0m0.073s
sys	0m0.045s
7

real	0m6.599s
user	0m0.073s
sys	0m0.043s

[1]   Done                    time qvm-run -p personal "echo $i" < /dev/null
[2]   Done                    time qvm-run -p personal "echo $i" < /dev/null
[3]   Done                    time qvm-run -p personal "echo $i" < /dev/null
[4]   Done                    time qvm-run -p personal "echo $i" < /dev/null
[5]   Exit 1                  time qvm-run -p personal "echo $i" < /dev/null
[6]   Done                    time qvm-run -p personal "echo $i" < /dev/null
[7]   Done                    time qvm-run -p personal "echo $i" < /dev/null
[8]   Done                    time qvm-run -p personal "echo $i" < /dev/null
[9]-  Done                    time qvm-run -p personal "echo $i" < /dev/null
[10]+  Done                    time qvm-run -p personal "echo $i" < /dev/null
[robert@cubi /]$ 
```
I also notice that one of the outputs is in red ('6' in this particular run), and one of them times out. These two effects seem quite repeatable (one red, one timeout) with the same command, but often it will be different ones within the batch.

I thought this might be an interesting test vector as it cuts out the first step (sys-usb->dom0), and the execution body (echo) does not have any of the complications that the other payload might be suspected of having... `echo` should be pretty fast.
