### ISSUE TITLE
[doc] Instalation Guide is missing: how to boot from USB stick

### ISSUE THREAD

**Issue by deeplow** [QubesOS/qubes-issues#6758]
### Checklist
- [x] I have [searched both open and closed issues](https://www.qubes-os.org/doc/issue-tracking/#search-tips) for duplicates.
- [x] This issue follows the [Issue Tracking Guidelines](https://www.qubes-os.org/doc/issue-tracking/#guidelines).

-----
### The problem you're addressing (if any)

The current description of how to boot from a USB stick is highly non-trivial for anyone who has never installed an operating system (most Windows and Mac users). It currently [only states](https://www.qubes-os.org/doc/installation-guide/#getting-to-the-boot-screen):

> ### Getting to the boot screen
> 
> Just after you power on your machine, make the Qubes OS medium available to the
computer by inserting your DVD or USB drive. This step is a little tricky
> 
> Shortly after the Power-on self-test (POST) is completed, you should be greeted with the Qubes OS boot
screen. 

### Describe the solution you'd like

A description on how to get into a boot menu on most computers.

### Where is the value to a user, and who might that user be?

Non-tecnical users who have never installed any OS and never even heard the word BIOS or how it looks like.

### Describe any alternative solutions you've considered

Leaving users stranded in the step.

### Additional context

- inspired by this thread: [Installing Qubes From USB Drive](https://forum.qubes-os.org/t/installing-qubes-from-usb-drive/4866)

-----
### Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted

- https://www.qubes-os.org/doc/installation-guide/#getting-to-the-boot-screen

### Related, [non-duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) issues

- https://github.com/QubesOS/qubes-issues/issues/5634

**Comment by deeplow** [comment]
Related:
  - [(Purism Forum) How to boot Qubes from a USB stick, Mac, PC, Linux](https://forums.puri.sm/t/how-to-boot-qubes-from-a-usb-stick-mac-pc-linux/3764) (Note: I haven't actually checked their instructions)
  - [Manjaro manual](https://mirrors.xtom.com/osdn//storage/g/m/ma/manjaro/Manjaro-User-Guide.pdf#page-31) (page 31)

**Comment by andrewdavidwong** [comment]
Would you be willing to submit a PR for this? :slightly_smiling_face:

**Comment by deeplow** [comment]
> Would you be willing to submit a PR for this? slightly_smiling_face

I probably can. But wanted to open an issue discussion for feedback. There are probably so many variations in BIOS settings and escape combinations.

Is anyone aware about a distro that explains this particularly well?
