### ISSUE TITLE
Ubuntu template does not boot after LVM pool was on 100%

### ISSUE THREAD

**Issue by Rot127** [QubesOS/qubes-issues#6759]
### Checklist
- [x] I have searched the [documentation](https://www.qubes-os.org/doc/) and [FAQ](https://www.qubes-os.org/faq/).
- [x] I have searched the [Qubes Forum](https://forum.qubes-os.org/) and [qubes-users](https://www.mail-archive.com/qubes-users@googlegroups.com/).
- [x] This issue follows the [Issue Tracking Guidelines](https://www.qubes-os.org/doc/issue-tracking/#guidelines).
- [x] I have [searched both open and closed issues](https://www.qubes-os.org/doc/issue-tracking/#search-tips) for duplicates.

-----
### Qubes OS version

R4.0

### Which [testing](https://www.qubes-os.org/doc/testing/) repositories are you using, if any?

None

### Affected component(s) or functionality

- resize2fs (resizing the root image after LVM pool was 100% full.)
- Ubuntu 20.04 Template (although I could not (don't have time to test) Fedora or Debian templates.

-----
### Brief summary

After the LVM pool was on 100% a Ubuntu HVM can't resize its root fs and fails to boot. Qubes will show a "Could not connect to qrexec-client" error.

**Cause**:

The script (resize-rootfs-if-needed.sh), which resizes the root fs on boot, returns the following error:
```
resize2fs: Permission denied to resize filesystem
```

Connecting to the maintenance shell and exit it (see commands below), continues to boot the VM normally and lets the `qrexec-client` connect. 

### How reproducible

I did not try to reproduce this issue because of fear to break any other VM.

### Steps to reproduce

Letting a LVM pool run out of space and restart the HVM/Template which caused the disk space exhaustion. 

### Expected behavior

Since it is possible for the VM to boot normally I would expect it to do and simply show an error message to the user that some resizing of the filesystem failed.
Especially, since this could save the day for not so technically minded users.    

### Actual behavior

It stops booting and waits for user interaction on the maintenance shell (which is not reachable on the default way vie qrexec-client consoles).

### Solutions you've tried

Used the following commands to get the error causes and the workaround:
```command
user@dom0 > sudo qmv-prefs VMNAME qrexec-timeout 600  # Increase timeout from 1min to 10min
user@dom0 > sudo xl console -t pv VMNAME  # Connect to maintenance shell
root@VMNAME > /usr/lib/qubes/init/resize-rootfs-if-needed.sh  # Run rootfs resize script

dumpe2fs 1.45.5 (07-Jan-2020)
dumpe2fs 1.45.5 (07-Jan-2020)
resize2fs 1.45.5 (07-Jan-2020)
Filesystem at /dev/mapper/dmroot is mounted on /; on-line resizing required
old_desc_blocks = 3, new_desc_blocks = 3
resize2fs: Permission denied to resize filesystem

root@VMNAME > exit  # Exit maintenance shell and continue boot up of VM.
# This is basically the workaround. But it has to be repeated each time the VM boots.
# Exits the maintenance shell and boots the HVM normally.
# The qrexec-client starts and one can use the VM as usual until the next start.
```

### Additional context

I am aware that the Ubuntu template is officially not supported by the Qubes core team. Though I wonder whether this problem occurs on Fedora and Debian templates as well.
Also I opened the issue here in case someone runs into this as well and does not know how to work around it.

### Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted

None of the documentation I could find seemed to address the issue.

### Related, [non-duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) issues

https://github.com/QubesOS/qubes-issues/issues/979#issuecomment-516275146

**Comment by andrewdavidwong** [comment]
Why did you delete the checklist? :frowning_face:

**Comment by Rot127** [comment]
I am sorry. I edited the issue and will take more care in the future.

**Comment by Rot127** [comment]
Finally found out how to fix the root image.

1. Mount the root image to a disposable VM by following [this guide](https://www.qubes-os.org/doc/mount-lvm-image/) until step 3.
2. In the disposableVM run: `sudo e2fsck /dev/xvdi3  # Assumes the image was attached as xvdi`
3. Detach the root image from the disposableVM and do step 6 in the guide to clean up.

Here the commands in order:
```command
# In dom0
# "root" if you want to fix the root image. Otherwise "private".
dev=$(basename $(readlink /dev/qubes/vm-VM_NAME-root))
qubesdb-write /qubes-block-devices/$dev/desc "VM_NAME root"
qvm-run -v --dispvm=YOUR_FEDORA_DVM_TEMPLATE --service qubes.StartApp+xterm &
qvm-block attach dispXXX dom0:$dev
```

```command
# In dispVM
sudo e2fsck /dev/xvdi3  # -p for automatic repair
```

```command
# In dom0
qubesdb-rm /qubes-block-devices/$dev/
qvm-block detach dispXXX dom0:$dev
```
