### ISSUE TITLE
The installer freezes

### ISSUE THREAD

**Issue by tsao-chi** [QubesOS/qubes-issues#6764]
### Qubes OS version
R4.1

Build20210612-kernel-latest-4.1
Build20210619-kernel-latest-4.1
Build20210626-kernel-latest-4.1
Build20210704-4.1

### Affected component(s) or functionality
Installer

### Brief summary

The installer always freezes when installing the first template (Fedora or Debian) after a while.

(There was no disk read/write operation)

### How reproducible

always

### Steps to reproduce

1. Install QubesOS on a Ryzen 4700 laptop
2. (optional) uncheck Fedora template
3. see the bug

### Solutions you've tried

+ uncheck Fedora template
+ keep Fedora template

### Additional context

-----

**Comment by njk2002** [comment]
How long had it stopped working before you thought it "froze"? 
The installer does behave like that . A while after the installer starts, it will look like ”stopped“. However, 10 mins later (maybe longer or shorter), you'll see the text in the pop-up window changed.

**Comment by tsao-chi** [comment]
Apparently only a portable SSD drive has this problem. The internal SSD works just fine

**Comment by brendanhoar** [comment]
What brand/model of portable SSD?
