### ISSUE TITLE
R4.1 PCI-e Ethernet Controller reattached to sys-net on Reboot

### ISSUE THREAD

**Issue by deeplow** [QubesOS/qubes-issues#6767]
### Qubes OS version

R4.1

### Which [testing](https://www.qubes-os.org/doc/testing/) repositories are you using, if any?

current-testing

### Are you providing feedback about a specific package or packages in testing?

No

### Affected component(s) or functionality

sys-net

-----
### Brief summary

My system has two PCI-e network devices: an ethernet one and a WiFi one. The ethernet was originally attached to dom0 (because it's a [testing system](https://www.qubes-os.org/doc/test-bench/)). The WiFi one was supposed to be attached to sys-net. This is how it was before I enabled current-testing on 4.1.

After that, my system now attaches automatically both PCI-e devices to sys-net. When I attempt to remove it from sys-net and start it again, it crashes. if I remove it (without restarting sys-net) and then reboot the computer, it's re-attached upon boot.

### How reproducible

100%

### Steps to reproduce

1. Start computer
2. Shutdown sys-net
3. Open sys-net qube settings
4. Remove Ethernet PCI-e controller from sys-net, leaving in a WiFi controller there
5. Applying the settings
6. Restart computer

### Expected behavior

Ethernet PCI-e controller is not attached to sys-net

### Actual behavior

Ethernet PCI-e controller is attached to sys-net

### Solutions you've tried

Half of the times, removing the PCI-e device from sys-net and then starting it (without computer reboot) - takes a lot of time to start and then says `Domain sys-net has failed to start: internal error: Failed to resume domain '11' with libxenlight`. The other half it starts just fine but with the PCI-e devices attached to it.

### Additional context

- I had just enabled the current-testing repos on 4.1. Before it was not happening.
- On the following files, the last reboots are a result of me restarting sys-net without the pci-e device but without rebooting the whole system.
[guest-sys-net.log](https://github.com/QubesOS/qubes-issues/files/6771323/guest-sys-net.log)
[guest-sys-net-dm.log](https://github.com/QubesOS/qubes-issues/files/6771324/guest-sys-net-dm.log)

-----
### Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted

None

### Related, [non-duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) issues

None found.

**Comment by DemiMarie** [comment]
> * I had just enabled the current-testing repos on 4.1. Before it was not happening.

That is very helpful information.  Can you obtain (from `dnf history`) the specific upgrade in which you first turned these repos on, and provide the list of packages upgraded in that transaction?

**Comment by deeplow** [comment]
Trying to get it for you.  But it was done through saltstack. Basically running the following:

https://github.com/marmarek/openqa-tests-qubesos/tree/master/extra-files/update

**Comment by deeplow** [comment]
In essence I ran the following commands:

```bash
export QUBES_VERSION=4.1
sudo qubes-dom0-update git
git clone https://github.com/marmarek/openqa-tests-qubesos/
cd openqa-tests-qubesos/extra-vars
sudo python3 ./setup.py install

sudo cp -a system-tests/ /srv/salt/
sudo qubesctl top.enable system-tests

PILLAR_DIR=/srv/pillar/base/update
mkdir -p $PILLAR_DIR
sudo printf 'update:\n  qubes_ver: '$QUBES_VERSION'\n' > $PILLAR_DIR/init.sls
sudo printf "base:\n  '*':\n    - update\n" >  $PILLAR_DIR/init.top
sudo qubesctl top.enable update pillar=True

sudo systemctl restart qubesd

# Apply states to VMs
qubesctl --show-output state.highstate # FIXME Takes forever...
qubesctl --max-concurrency=2 --skip-dom0 --templates --show-output state.highstate
```

Thanks for the help @DemiMarie. In these circumstances would you still be interested in the dnf history? It's quite verbose.

**Comment by deeplow** [comment]
Either way, here is the `dnf history` of dom0:
```shell_session
[user@dom0 ~]$ sudo dnf history
ID     | Command line                                                                                                                                           | Date and time    | Action(s)      | Altered
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
     5 | --exclude=qubes-template-whonix-gw-15,qubes-template-debian-10,qubes-template-fedora-33,qubes-template-whonix-ws-15 install git                        | 2021-07-06 14:09 | Install        |    9   
     4 | --exclude=qubes-template-whonix-gw-15,qubes-template-debian-10,qubes-template-fedora-33,qubes-template-whonix-ws-15 install python3-nose2              | 2021-07-06 13:22 | Install        |    3   
     3 | --setopt=reposdir=/etc/yum.repos.d install openssh-server                                                                                              | 2021-07-05 16:35 | Install        |    1   
     2 | --exclude=qubes-template-whonix-gw-15,qubes-template-debian-10,qubes-template-fedora-33,qubes-template-whonix-ws-15 install dhcp-client                | 2021-07-05 16:28 | Install        |    6  <
     1 |
```

The dnf history of fedora-33 is extremely verbose and I don't think it should matter much here *unless* we're talking about a security vulnerability where an update in a template can cause side-effects of PCI-e device reattachment. But I can get them for you -- is there a better command than `dnf history` for long history commands? (atm I have to increase the size of the window when running that just so everything fits).

**Comment by marmarek** [comment]
How do you detach the device from sys-net? Is it listed as detached (`qvm-pci`) also when sys-net is not running?

**Comment by deeplow** [comment]
> How do you detach the device from sys-net?

1. I shut down `sys-net`
2. I open sys-net's settings and remove the pci device



>  Is it listed as detached (`qvm-pci`) also when sys-net is not running?

Yes. Both when it's not running and it's attached and when it's not running and it is removed.

**Comment by marmarek** [comment]
> ```shell
> git clone https://github.com/marmarek/openqa-tests-qubesos/ # at this point I still had internet in dom0
> cd openqa-tests-qubesos/extra-vars
> sudo python3 ./setup.py install
> ```

Ok, this explains (almost?) everything. This contains a core-admin extension that is written specifically for running in openQA (Qubes nested inside KVM). The only thing it does is a set of workaround to make it all functional enough for running tests. At each sys-net startup, it adjust attached devices based on (v)IOMMU availability. You don't want this part running on a physical system.

**Comment by deeplow** [comment]
> > ```shell
> > git clone https://github.com/marmarek/openqa-tests-qubesos/ # at this point I still had internet in dom0
> > cd openqa-tests-qubesos/extra-vars
> > sudo python3 ./setup.py install
> > ```
> 
> Ok, this explains (almost?) everything. This contains a core-admin extension that is written specifically for running in openQA (Qubes nested inside KVM). The only thing it does is a set of workaround to make it all functional enough for running tests. At each sys-net startup, it adjust attached devices based on (v)IOMMU availability. You don't want this part running on a physical system.

Ah, you're right! (facepalm). Sorry about the confusion, then. In that case I'll try to reinstall and reproduce everything without that step and hopefully this is a non-bug.

**Comment by deeplow** [comment]
> Ok, this explains (almost?) everything.

It explains everything. Now working perfectly after a reinstall without that step. Thank you and sorry for the false flag @marmarek @DemiMarie.

Closing now.
