### ISSUE TITLE
Website: distinguishing email PGP keys from code-signing keys

### ISSUE THREAD

**Issue by deeplow** [QubesOS/qubes-issues#6770]
### Affected component(s) or functionality

Team page of the website: https://www.qubes-os.org/team/

-----
### Brief summary

It should be clear that the PGP privided key is the email one and not the code signing.

### Steps to reproduce

1. Go to Marek's profile: https://www.qubes-os.org/team/#marek-marczykowski-g%C3%B3recki-1
2. See buttown `PGP Key` and a Fingerprint `86BA 6E93 318F BA44 ...`

### Expected behavior

have som
- `PGP key` label would be labeled `@ PGP key` or something
- (optional) `Code-signing PGP key` would be listed
- fingerprint on the right would show that it's the email key

### Actual behavior

It's not clear that's the email key or that it's even different from code-siging key.
(Confirm fingerprint is different from the developer key: `86BA 6E93 318FB A446 ...`)

### Solutions you've tried

See "Expected behavior".

### Additional context

- finding the developer keys can be quite a hassle, especially for community members listed on the teams page.

-----
### Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted

None.

**Comment by andrewdavidwong** [comment]
Good point! We can easily add more links under a person's name and role description, but given that we display only one fingerprint, I'm not sure how best to handle this. We could label it, as you suggested, but where exactly should the label go? Should it be repeated for every fingerprint or for the whole column? Would just putting it in the title text be enough? Would it be misleading to have multiple key links but only one fingerprint?

**Comment by unman** [comment]
I think this should be clarified at the top of the page, and not for each fingerprint.
I don't think the code signing keys should be here at all.

**Comment by andrewdavidwong** [comment]
I've clarified in the title elements of both the PGP key download links and the fingerprint code blocks that these are email keys. I'm not keen to add any further non-hover text, as I believe it would harm the minimalist aesthetic of the page. I also agree with @unman that code signing keys don't belong here. This is not the right place to look for them in the first place. If code signing keys are a hassle to find, that's a separate problem that should be addressed with its own proper solution, not shoehorning it into this page.
