### ISSUE TITLE
Cannot perform updates with a Fedora 34 mgmtvm

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#6771]
### Qubes OS version

R4.0

### Which [testing](https://www.qubes-os.org/doc/testing/) repositories are you using, if any?

All in dom0, security-testing in domU

### Are you providing feedback about a specific package or packages in testing?

qubes-template-fedora-34-minimal

### Affected component(s) or functionality

Salt in the Fedora 34 minimal template

-----
### Brief summary

If a qube has the `management_dispvm` property set to a DispVM Template based on `fedora-34-minimal`, updates via Salt fail:

```
- Rendering SLS 'base:update.qubes-vm' failed: Jinja variable 'dict object' has no attribute 'os_family'
```

### How reproducible

100%

### Steps to reproduce

1. Make `default-mgmt-dvm` based on Fedora 34
2. Run `sudo qubesctl --skip-dom0 --target=fedora-34 -- state.show_sls update.qubes-vm`
3. 

### Expected behavior

Reasonable output

### Actual behavior

Above exception

### Solutions you've tried

Using a Fedora 33 management VM does not help.

### Additional context

This appears to be a Salt bug

-----
### Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted

This was originally reproduced on `fedora-34-minimal`, so https://www.qubes-os.org/doc/templates/minimal/#fedora, but `fedora-34` has the same problem.

### Related, [non-duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) issues

None found

**Comment by marmarek** [comment]
Can it be something R4.0 related? R4.1 test runs on openQA are successfully using stock fedora-34 template for default-mgmt-dvm.

**Comment by DemiMarie** [comment]
> Can it be something R4.0 related? R4.1 test runs on openQA are successfully using stock fedora-34 template for default-mgmt-dvm.

Perhaps?  No idea.  I *can* see (from `grains.ls` output) that there are far too few grains available.

**Comment by marmarek** [comment]
Or maybe some missing package?

**Comment by DemiMarie** [comment]
> Or maybe some missing package?

Perhaps?  `fedora-34` (not `-minimal`) seems to have the same problem.  `rpm -qv` indicates that the versions of Salt, Python, and Jinja are the same, which leads to even more confusion.

**Comment by DemiMarie** [comment]
Update: The problem may be a bad PAM config.  I will do more testing tomorrow to confirm.

**Comment by lubellier** [comment]
I see the same problem on a new installed 4.1.0-beta1 (installed 2 days ago) for the `fedora-34` template. No problem with the other templates (`debian-10`, `whonix-*-15`)

**Comment by DemiMarie** [comment]
> I see the same problem on a new installed 4.1.0-beta1 (installed 2 days ago) for the `fedora-34` template. No problem with the other templates (`debian-10`, `whonix-*-15`)

I managed to make this work, but I didn’t record exactly what steps I took, so I will need to figure out what changes I made.

**Comment by lubellier** [comment]
The complete stack:
```
user@dom0 ~]$ sudo qubesctl --skip-dom0 --targets=fedora-34 --show-output state.sls  update.qubes-vm
fedora-34:
      - Rendering SLS 'base:update.qubes-vm' failed: Jinja variable 'dict object' has no attribute 'os_family'
  [ERROR   ] Rendering exception occurred
  Traceback (most recent call last):
    File "/usr/lib/python3/dist-packages/salt/utils/templates.py", line 393, in render_jinja_tmpl
      output = template.render(**decoded_context)
    File "/usr/lib/python3/dist-packages/jinja2/asyncsupport.py", line 76, in render
      return original_render(self, *args, **kwargs)
    File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1008, in render
      return self.environment.handle_exception(exc_info, True)
    File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 780, in handle_exception
      reraise(exc_type, exc_value, tb)
    File "/usr/lib/python3/dist-packages/jinja2/_compat.py", line 37, in reraise
      raise value.with_traceback(tb)
    File "<template>", line 1, in top-level template code
  jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'os_family'
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/usr/lib/python3/dist-packages/salt/utils/templates.py", line 170, in render_tmpl
      output = render_str(tmplstr, context, tmplpath)
    File "/usr/lib/python3/dist-packages/salt/utils/templates.py", line 403, in render_jinja_tmpl
      buf=tmplstr)
  salt.exceptions.SaltRenderError: Jinja variable 'dict object' has no attribute 'os_family'
  [CRITICAL] Rendering SLS 'base:update.qubes-vm' failed: Jinja variable 'dict object' has no attribute 'os_family'
[user@dom0 ~]$ cat /etc/qubes-release 
Qubes release 4.1 (R4.1)

```
I understand that this stack comes from my updateVM, isn't it? My updateVM is sys-firewall, based on debian-10-dvm.

The sys-firewall templates.py file comes from : 
```
user@sys-firewall:~$ dpkg -S /usr/lib/python3/dist-packages/salt/utils/templates.py 
salt-common: /usr/lib/python3/dist-packages/salt/utils/templates.py
user@sys-firewall:~$ dpkg -l | grep salt-common
ii  salt-common                          2018.3.4+dfsg1-6+deb10u2                all          shared libraries that salt requires for all packages
user@sys-firewall:~$ cat /etc/debian_version 
10.10
```

The sys-firewall templates.py file content, near line 393:
```
user@sys-firewall:~$ tail -n +390 /usr/lib/python3/dist-packages/salt/utils/templates.py | head -n 8
    try:
        template = jinja_env.from_string(tmplstr)
        template.globals.update(decoded_context)
        output = template.render(**decoded_context)
    except jinja2.exceptions.UndefinedError as exc:
        trace = traceback.extract_tb(sys.exc_info()[2])
        out = _get_jinja_error(trace, context=decoded_context)[1]
        tmplstr = ''
```

and near line 170:
```
user@sys-firewall:~$ tail -n +168 /usr/lib/python3/dist-packages/salt/utils/templates.py | head -n 5
            tmplsrc.close()
        try:
            output = render_str(tmplstr, context, tmplpath)
            if salt.utils.platform.is_windows():
                newline = False
```

> I managed to make this work, but I didn’t record exactly what steps I took, so I will need to figure out what changes I made.

@DemiMarie : Maybe you switched sys-firewall from a debian template to a fedora template?

**Comment by lubellier** [comment]
I progressed in the analyze with Qubes-OS-4.1-beta1 and fedora-34 update request.

The qubectl update request works with:
```
[user@dom0 ~]$ qvm-prefs default-mgmt-dvm template
fedora-34
```
but fails with: 
```
[user@dom0 ~]$ qvm-prefs default-mgmt-dvm template
debian-10
```
In this case, the error message is the above post error ([this comment](https://github.com/QubesOS/qubes-issues/issues/6771#issuecomment-881909750), *os_family python/salt* error)

**Comment by DemiMarie** [comment]
> I progressed in the analyze with Qubes-OS-4.1-beta1 and fedora-34 update request.
> 
> The qubectl update request works with:
> 
> ```
> [user@dom0 ~]$ qvm-prefs default-mgmt-dvm template
> fedora-34
> ```

I am not surprised.  The problem I have seems to be R4.0-only.

**Comment by lubellier** [comment]
> I am not surprised. The problem I have seems to be R4.0-only.

So with my analyse and your remark, I understand it's not the same problem. 

Should I **create a new issue**, specific to my problem with 4.1-beta1 and debian-10 as template for default-mgmt-dvm ?

**Comment by andrewdavidwong** [comment]
> > I am not surprised. The problem I have seems to be R4.0-only.
> 
> 
> 
> So with my analyse and your remark, I understand it's not the same problem. 
> 
> 
> 
> Should I **create a new issue**, specific to my problem with 4.1-beta1 and debian-10 as template for default-mgmt-dvm ?

I suggest doing a search first. It sounds like it might be a duplicate. There are known problems with using Debian instead of Fedora for the mgmt qube.

**Comment by zoechi** [comment]
I have the same problem since a while.
It started a few weeks after I updated to 4.1

**Comment by marmarek** [comment]
Which template you have for default-mgmt-dvm? Make sure it is new enough (currently that would be fedora-36).

**Comment by DemiMarie** [comment]
I’m going to close this, as it has long since been fixed.  Please file a new issue for any problems.
