### ISSUE TITLE
Update GUI protocol documentation for R4.1

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#6773]
### Qubes OS version

R4.0

### Which [testing](https://www.qubes-os.org/doc/testing/) repositories are you using, if any?

N/A; this is a documentation issue

### Are you providing feedback about a specific package or packages in testing?

No

### Affected component(s) or functionality

Documentation

-----
### Brief summary

The GUI protocol documentation does not include the R4.1 changes to use Xen grant tables.

### How reproducible

100%

### Steps to reproduce

1. Look at the GUI protocol documentation at <https://www.qubes-os.org/doc/gui/>.
2. Check to see if all messages are listed. 

### Expected behavior

All GUI messages are listed.

### Actual behavior

Not all GUI messages are listed.

### Solutions you've tried

N/A

### Additional context

This is particularly important now, as I am collaborating with others on Wayland support.

-----
### Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted

<https://www.qubes-os.org/doc/gui/>

### Related, [non-duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) issues

None found

**Comment by andrewdavidwong** [comment]
Until #5308 is done, this is expected and not a bug, as our documentation reflects the latest **stable** release:

https://www.qubes-os.org/doc/documentation-style-guide/#version-specific-documentation

**Comment by andrewdavidwong** [comment]
Although, in this case, I suppose #5308 doesn't even matter, as 4.1 is still the same major release as 4.0 and hence would share the same body of documentation.

Nonetheless, the point about our documentation reflecting the latest stable release still applies.
