### ISSUE TITLE
Qubes SDD LVM memory lost

### ISSUE THREAD

**Issue by lepromeneur** [QubesOS/qubes-issues#6774]
Hi everybody.

**Qubes OS version:**

R4.0 RC2 with SSD 1TB NVME

Qubes OS 4.0

**Affected TemplateVMs:**

none (dom0 issue)

**Steps to reproduce the behavior:**
Create-remove several VM, create a veracrypt container until filling the whole disc, then free 700GB space

**Expected behavior:**
Getting back 700GB space

**Actual behavior:**
Getting back 300GB space despite fstrim --alll use under dom0 and under each VM

**General notes:**
return of sudo lvs attached here.

The issue seems to have been dealt with here
"Difficult to determine free and used disk space with LVM thin provisioning #3240" but I really cannot find any solution*.

My SSD is 1TB, 920GB are used for pool0. LVS tells that 563 are used but the sum of each VM gives 210 GB used effectivly. I confirm that there are around 200GB used when looking inside each VM.

If I create a new veracrypt container (300GB for instance) the SSD is saturated and goes in read only mode.
I have deleted about all my VM and tried fstrim everywhere but there always miss 500G (half of the disc).

I use Linux since 2003 and Qubes OS sincel 2018, I am not a computer scientist but I always managed to do everything I tried around the kernel, the network, the display... But I am completly stuck this time. Perhaps LVM.

Thanks for you help. PS, I would prefer not to reinstall for some good reasons.
I
[memory_lost.ods](https://github.com/QubesOS/qubes-issues/files/6795763/memory_lost.ods)

**Comment by andrewdavidwong** [comment]
Based on our [issue tracking guidelines](https://www.qubes-os.org/doc/issue-tracking/), this does not appear to be suitable for `qubes-issues`. We ask that you please post this on the [Qubes Forum or `qubes-users` mailing list](https://www.qubes-os.org/support/) instead. If, after reading our [issue tracking guidelines](https://www.qubes-os.org/doc/issue-tracking/), you believe we are mistaken, please leave a brief comment explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.
