### ISSUE TITLE
Attempting to start qube with unavailable persistently attached device leads to an infinite loop when attempting to start another qube

### ISSUE THREAD

**Issue by Eric678** [QubesOS/qubes-issues#6777]
### Qubes OS version

R4.0 up to date

### Which [testing](https://www.qubes-os.org/doc/testing/) repositories are you using, if any?

None that I am aware of

### Are you providing feedback about a specific package or packages in testing?

No

### Affected component(s) or functionality

dom0

-----
### Brief summary

dom0 goes into an infinite loop attempting to start a qube and failing

Triggers a 2nd bug: when alerts wrap around the whole screen, past TRH corner, that slot is filled and can never be cleared.

### How reproducible

Only tested this once.
Once in this state, alerts come up several times a second filling the screen and wrapping around

### Steps to reproduce

1. Attempt to start a qube with a persistent block device attach that is unavailable, puts up one of these status alerts.
2. Start a different qube without deleting that persistent device attach, causes dom0 to go into an infinite loop attempting to start the previous qube, filling the screen with alerts. The new qube does start.

### Expected behavior

Only the first attempt to start is made.

### Actual behavior

dom0 goes into infinite loop trying to start old broken qube

### Solutions you've tried

The new qube does start correctly, hiding behind all the alerts, halting that qube immediately stops dom0 trying to start the previous qube.  Deleting the persistent attach that is broken then fixes the problem.

2nd bug: clicking on all alerts cleared them except the TRH corner one that is still up now - some special code in there for those that run the panel along the top? Only gets filled in when alerts wrap around whole screen?

### Additional context

I had my first total lock up of Qubes, while dragging on a scroll bar in gnome terminal - screen keyboard mouse disk and network all dead.  After bringing back up and initial testing that seemed to indicate no permanent damage, upgraded dom0 and restarted. Then went around doing more detailed assessment of damage, in the past this alert happens to me whenever I restart (see #3437) but when that alert popped up I would go to dom0 and delete the persistent attach and try again until I caught all the broken ones. This time I was in a hurry to test elsewhere and thought to come back to that broken qube later....

No problems found in running system so I conclude this is a solid fault.

-----
### Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted

None

### Related, [non-duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) issues

None found.

**Comment by andrewdavidwong** [comment]
As you indicate, there are two separate bugs here, but [every issue must be about a single, actionable thing](https://www.qubes-os.org/doc/issue-tracking/#every-issue-must-be-about-a-single-actionable-thing). Ordinarily, this would mean that you should file a separate issue for the second bug. However, in this case, I think the second bug (screen filling with notifications) likely falls under another existing issue: #889.

**Comment by Eric678** [comment]
I am not getting notifications from Github??  Second bug is that once the screen is full of alert notifications the TRH corner notification is not able to be dismissed.  Different from #889, but fixing this would stop the screen filling and hide the second bug.

It has happened again, and I have deduced that the problem is an interaction caused by an NFS mount, through qrexec, of part of the partition attach that fails, due to being unavailable, due to the non support of symlinks in device names in qvm-block.  That mount as part of the startup of a VM is being retried in an infinite loop, attempting to start the target VM, without any backoff, causing the screen to fill with alert notifications, until the VM trying to NFS mount is halted.  Had problems like this before when a failure is just immediately retried blindly.
