### ISSUE TITLE
qvm-start-daemon does not relaunch on X restart

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#6780]
### Qubes OS version

R4.1

### Which [testing](https://www.qubes-os.org/doc/testing/) repositories are you using, if any?

All are enabled in dom0 (where the bug is)

### Affected component(s) or functionality

GUI and audio daemon lifecycle management

-----
### Brief summary

`qvm-start-daemon` uses a lock file (`$XDG_RUNTIME_DIR/qvm-start-daemon.pid`) to guard against multiple instances running.  However, an X restart (such as by `systemctl restart lightdm.service`) does not delete the lock file, so `qvm-start-daemon` fails to start the second time around.

### How reproducible

100%

### Steps to reproduce

1. Restart X with `systemctl restart lightdm.service`
2. Wait for the GUI daemon to come back up.

### Expected behavior

The GUI daemon comes back up normally.

### Actual behavior

The GUI daemon does not come back up.

### Solutions you've tried

Manually deleting the file helps.  A better solution would be to overwrite the file unless another process has a lock on it.

### Additional context

-----
### Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted

None

### Related, [non-duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) issues

#4729

**Comment by zaz** [comment]
I had this today on i3.  I'm not aware of anything I did differently to trigger it; it was preceded by a normal reboot. Further reboots didn't fix it and I had to manually delete the lock file.

**Comment by andrewdavidwong** [comment]
@zaz: Please open a separate issue.
