### ISSUE TITLE
Rust bindings for libvchan

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#6783]
### Qubes OS version (if applicable)

N/A

### Affected component(s) or functionality (if applicable)

Needed for several components to be ported to Rust.

-----
### Brief summary

We need Rust bindings for libvchan.  A pure-Rust implementation is also acceptable.

### Additional context

This is needed for several projects, so it is being marked `P: major`.

-----
### Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted

N/A

### Related, [non-duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) issues

Lots and lots; this is needed for many uses of Rust.

**Comment by marmarek** [comment]
> A pure-Rust implementation is also acceptable.

Please don't, at least not as part of introducing vchan into Rust code. First of all, this is the ABI we consider switchable between hypervisors (https://blog.invisiblethings.org/2013/03/21/introducing-qubes-odyssey-framework.html) - specially you can switch Xen version into KVM one, or others in the future. But also, the actual vchan is quite sensitive for subtle things like memory read/write ordering (as it is lock-less shared memory protocol), and even things like compiler optimizations can get in the way. Avoiding security bugs is one thing, but it's equally easy (if not easier) to introduce a deadlocks or other issues.

**Comment by DemiMarie** [comment]
https://github.com/QubesOS/qubes-gui-rust has such bindings, closing.
