### ISSUE TITLE
Potential deadlock in GUI code

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#6790]
### Qubes OS version

R4.0 but this concerns the code in git HEAD

### Which [testing](https://www.qubes-os.org/doc/testing/) repositories are you using, if any?

N/A

### Are you providing feedback about a specific package or packages in testing?

No

### Affected component(s) or functionality

GUI protocol

-----
### Brief summary

If the GUI daemon and GUI agent both block on sending a message over the vchan, the system will deadlock. I do not have a proof that this can happen, though.

### How reproducible

N/A; I do not have a reproducer.

### Steps to reproduce

I do not have one.

### Expected behavior

The protocol is obviously guaranteed to not deadlock.

### Actual behavior

The protocol has no such guarantee.

### Solutions you've tried

None yet, but buffering in the GUI agent’s output code should solve the problem, as it prevents the GUI agent from waiting on the GUI daemon and thus breaks the deadlock.

### Additional context

N/A

-----
### Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted

None

### Related, [non-duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) issues

None found

**Comment by marmarek** [comment]
gui-daemon does write buffering (see https://github.com/QubesOS/qubes-gui-daemon/blob/master/gui-common/txrx-vchan.c), so this issue is avoided already.

**Comment by DemiMarie** [comment]
> gui-daemon does write buffering (see https://github.com/QubesOS/qubes-gui-daemon/blob/master/gui-common/txrx-vchan.c), so this issue is avoided already.

Good catch!  I should have looked into that code more carefully; this will also be a useful implementation hint for the Rust version of the daemon.
