### ISSUE TITLE
Error when changing default net qube in Qubes Global Settings: `Failed to access 'default_netvm' property` (but net qube still changes)

### ISSUE THREAD

**Issue by unman** [QubesOS/qubes-issues#6799]
### Qubes OS version

4.1 

### Which [testing](https://www.qubes-os.org/doc/testing/) repositories are you using, if any?

dom0 - updates-testing
dom0 - security-testing

### Affected component(s) or functionality

Qubes-Global-Settings

-----
### Brief summary

Trying to change the default netVM gives an unhelpful error message

### How reproducible

100%

### Steps to reproduce

1. Open Qubes Global Settings
2. Change default netVM
3. 

### Expected behavior

netVM will be changed

### Actual behavior

An error message -
Failed to apply some settings:
Failed to set Default NetVM due to Failed to access 'default_netvm' property

Despite the error message, the netVM *is* changed.

### Additional context

-----

**Comment by ddevz** [comment]
This is happening on qubes 4.2 now (up to date 4.2 as of 2023-08-13) 
The following error occurred: Failed to access 'default_netvm' property

I'm not concerned as it still works, and it's just in the gui, but thought I should mention it.

**Comment by ddevz** [comment]
> > This is happening on qubes 4.2 now (up to date 4.2 as of 2023-08-13) The following error occurred: Failed to access 'default_netvm' property
> > I'm not concerned as it still works, and it's just in the gui, but thought I should mention it.
> 
> Hm, in the Global Settings tool? It should have been removed in 4.2 and replaced with the new-and-improved Global Config, I think...

I no longer remember what process I used to get that error message. Sorry :)

**Comment by marmarta** [comment]
Ok, cannot reproduce, closing, but if someone encounters this again, please reopen.

**Comment by hax0rbana-adam** [comment]
I am able to reproduce this error 100% with a fresh install of Qubes 4.2.0.

Here's the error:

![failed_to_access](https://github.com/QubesOS/qubes-issues/assets/118935832/ccc42d71-7684-4011-b0c1-75743b0c6446)

And the field I was changing was the "Net qube" on the setting of the VM, which I got to via the Qube Manager.

![vm_settings](https://github.com/QubesOS/qubes-issues/assets/118935832/ff1c245d-7536-4d32-aa50-4e49eeb4cf44)

After clicking OK on the error message, the field returns to the previous value. In practice, the VM's networking never seems to change. If there's any additional information I can provide to help with debugging this, please let me know. I'm happy to help, I am just not familiar with the code base or commands to inspect things like VM properties.

**Comment by hax0rbana-adam** [comment]
Oh, this is very interesting. If I start with my test qube set to use sys-net, I can switch to sys-firewall without any problem. I can also switch back to sys-net just fine.

When I switch to sys-vpn, the settings page switches just fine, but then attempting to change the net qube results in the error I posted in my previous comment.

It's also probably worth noting that sys-vpn doesn't seem to be providing any networking to my test qube, although networking works fine from within sys-vpn. I do have the "Provides network" checkbox checked. I made this VM fresh in 4.2 (as opposed to having imported it from Qubes 4.1) because my imported VM seemed to have the same problem.

I have another vpn service VM that works fine both in the VM and in terms of providing network. It's even the same VPN provider. So I'm really not sure what's going on here, but I'm very curious to understand what's going on here.

**Comment by hax0rbana-adam** [comment]
I stumbled across something like this again yesterday after doing a fresh install of Qubes 4.2 and trying to restore qubes from a backup. I noted down the file and line number in the error message: /usr/lib/python3.11/site-packages/qubesmanager/restore.py line 192 Failed to access 'provides_network' property.

I see that line calls `get_restore_info()` which calls `restore_info_verify(vms_to_restore)`, which deals with the `provides_network` attribute, but that code all looks pretty reasonable to me. I can't remember exactly which VMs I was restoring, but it's entirely possible I was trying to restore both the qube and the netvm that that qube used at the same time. If I'm able to reproduce this again, I'll take better notes and report back here.

**Comment by marmarta** [comment]
I've been trying to reproduce this on 4.2 without success - with a freshly made vm with provides_network, with one that was updated from 4.1... I'm very curious what's going on here, provides_network seems to not be working for some qubes, but I don't think this should ever happen, unless the qube in question is dom0, which is weird.

**Comment by hax0rbana-adam** [comment]
I've been thinking about this and I suspect the fact that I'm taking a backup from Qubes 4.1 and restoring on 4.2 might be an important part of being able to reproduce the issue. Qubes that use the usual sys-firewall seem fine in this case, but qubes that use a net_vm that I created seem to (at least sometimes) havr the problem.

I'm going to be reinstalling 4.1 again as part of debugging a different issue, and when I do, I'll try backing up my sys-vpn and a qube that uses it separately and without a password. That way I can have something that I can share publicly that might help in reproducing this issue. I'll also take detailed notes. Unfortunately, I don't have two computers that can run Qubes so going back and forth between 4.1 and 4.2 is not a fast operation for me.

**Comment by Zm4st3r-sci** [comment]
Using Qubes OS 4.2 release I faced this error as well. I solved it by choosing the default option then switching to the desired network provider qube in my case the sys-net qube

tried once more again and the error appeared again this time I had to kill the firewall qube

**Comment by ben-grande** [comment]
I believe this was the original issue and https://github.com/qubesos/qubes-issues/issues/10125 was a duplicate. That one got solved, closing this one as duplicate. Please notify if needs to be reopened. Didn't test.
