### ISSUE TITLE
4.1 beta1 - Global Settings - Default DisposableVM Template display shows internal value instead of name

### ISSUE THREAD

**Issue by unman** [QubesOS/qubes-issues#6800]
### Qubes OS version

4.1 beta-1

### Which [testing](https://www.qubes-os.org/doc/testing/) repositories are you using, if any?

dom0 - updates-testing
dom0 - security-testing

### Affected component(s) or functionality

Qubes-global-settings

-----
### Brief summary

As title

### How reproducible

100%

### Steps to reproduce

1. Open Global Settings
2. Observer value for default DisposableVM Template
3. 

### Expected behavior

Value will be a qube name 

### Actual behavior

Value is :
<object object at 0xHEX_VALUE>

### Additional context

Users will have no idea what this value represents.

-----

**Comment by marmarek** [comment]
What is the actual value as seen with `qubes-prefs`? I don't see this issue neither on my system, nor in openQA (https://openqa.qubes-os.org/tests/20705#step/qubesmanager_globalsettings/12).

**Comment by jevank** [comment]
This happens when sys-net fails to start during initial-setup. It reproduced on Lenovo X1C7+ and could be fixed with no-strict-reset option to LAN pci device. Also perhaps initial-setup should complete all configuration tasks before trying to start network
