### ISSUE TITLE
Debian minimal documentation should specify that the 'zenity' package is required to copy some files out of debian-10-minimal using the Nautilus menu option

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#6801]
### Qubes OS version

`R4.0`

### Which [testing](https://www.qubes-os.org/doc/testing/) repositories are you using, if any?

security-testing

### Are you providing feedback about a specific package or packages in testing?

No.

### Affected component(s) or functionality

qvm-copy

-----
### Brief summary

- When I try to qvm-copy a 35.4 MB file out of a debian-10-minimal-based qube, no file arrives at the destination.
- When I try again with a 9 MB file, it works normally.
- When I switch the underlying template to fedora-33-minimal, I can qvm-copy the 35.4 MB file normally.

### How reproducible

100%

### Steps to reproduce

1. Create an app qube based on debian-10-minimal with a ~35 MB PDF file inside.
2. In Nautilus, right-click on the file and attempt to copy it to another qube.
3. In the destination qube, the `~/QubesIncoming/<ORIGIN_QUBE>/` path is created, but there is no file inside.

### Expected behavior

File qvm-copies successfully.

### Actual behavior

No file arrives in destination qube.

### Solutions you've tried

Switching from debian-10-minimal to fedora-33-minimal works.

-----
### Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted

N/A

### Related, [non-duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) issues

None found.

**Comment by DemiMarie** [comment]
That is odd.  Can you post the stderr and stdout of the command?

**Comment by andrewdavidwong** [comment]
> That is odd.  Can you post the stderr and stdout of the command?

There was none.

**Comment by andrewdavidwong** [comment]
> That is odd. Can you post the stderr and stdout of the command?

Oh, I just discovered that the problem occurs only when using the Nautilus menu option. When using the CLI, it works normally. So, I can't provide stderr or stdout.

**Comment by brendanhoar** [comment]
Is the experiment with the same path/filename or do they differ?

If they differ any special characters or white space in the paths or file names?

If not sensitive, can you provide the paths, file names and exact sizes?

B

**Comment by andrewdavidwong** [comment]
> Is the experiment with the same path/filename or do they differ?
> 

Same. 

> If they differ, any special characters or white space in the paths or file names?
> 

No white space or any special characters. I only use lowercase letters, numbers, underscores, hyphens, and periods in filenames.

> If not sensitive, can you provide the paths, file names and exact sizes?
> 

I'd prefer not to share, but I don't think the exact path or filename matters. There isn't really anything unusual about it.

**Comment by andrewdavidwong** [comment]
Also, the filename is not long (shorter than the 9 MB file that copied normally).

**Comment by rustybird** [comment]
Does it work if you install the `zenity` package in debian-10-mininal?

**Comment by andrewdavidwong** [comment]
> Does it work if you install the `zenity` package in debian-10-mininal?

Yes, that was it.

My mistake. I should've known better and asked about this on qubes-users or the forum first.

Reclassifying as a documentation issue and fixing.

If the devs want to take further action on this, please feel free to reopen.

**Comment by andrewdavidwong** [comment]
I just noticed that `zenity` was already installed in my `fedora-33-minimal` template, and I don't remember installing it there. It could have been installed as a dependency, and I just forgot. Is it included in the fedora-minimal template by default? If so, why this difference between fedora-minimal and debian-minimal?

**Comment by rustybird** [comment]
It's because the .rpm package of `qubes-core-agent` declares the dependency on zenity, but the .deb doesn't. Maybe that's intentional: Debian builds `zenity` with WebKit support, which pulls in an enormous amount of bloat.

**Comment by marmarek** [comment]
On Thu, Jul 29, 2021 at 04:56:25AM -0700, Rusty Bird wrote:
> It's because the .rpm package of `qubes-core-agent` declares the dependency on zenity, but the .deb doesn't. Maybe that's intentional: Debian builds `zenity` with WebKit support, which pulls in an enormous amount of bloat.

Indeed, pulling in webkit in a minimal template is definitely undesirable.
Maybe there is a way to have something smaller there? Some different
package in that place (that doesn't require too much code changes)? Or
maybe simply skip displaying the progress if zenity is not installed,
instead of failing the copy.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab

**Comment by rustybird** [comment]
> Maybe there is a way to have something smaller there?

We could fall back to `PROGRESS_TYPE=console`, if only `qubes-run-terminal` accepted a parameter for launching a specific program. Unfortunately every terminal emulator seems to have its own crummy syntax and semantics for this: argv vs. shell code fragment vs. GLib string parsing nonsense :\

> Or maybe simply skip displaying the progress if zenity is not installed, instead of failing the copy.

Part of https://github.com/QubesOS/qubes-core-agent-linux/pull/319
