### ISSUE TITLE
Template not found

### ISSUE THREAD

**Issue by quser59** [QubesOS/qubes-issues#6802]
### Qubes OS version
R4.1

### Which [testing](https://www.qubes-os.org/doc/testing/) repositories are you using, if any?
None

### Are you providing feedback about a specific package or packages in testing?
No

### Affected component(s) or functionality
Qubes updater/package management

-----
### Brief summary
Qubes whonix gateway template is not found in the repos from my machine. 

### How reproducible
100% on single install

### Steps to reproduce

1. sudo qubes-dom0-update --action=search whonix 
(with community templates repo enabled)

### Expected behavior
Whonix gateway template should appear

### Expected behavior
Whonix gateway template should appear

### Actual behavior
See screenshots.

### Solutions you've tried
I rebooted, as per Whonix guide (after removing templates), to no avail.

### Additional context
Dom0 had updates but simply would not work through the GUI. After many unsuccesful attempts in Dom0 Terminal, eventually I had an output for updates, in the terminal, but had cancelled the command. Every time I issued the command I realised the updateVM (set to sys-whonix) output was not appearing. If I killed the VM (sys-whonix) and then issued the update command (forcing the VM to start), it would display briefly then go away. 

After changing the updateVM to sys-firewall I can update dom0 through the GUI and the updateVM display output appears everytime. 

Hence, I go to reinstall the template whonix-gw-15. I rename the existing template, and then remove whonix-gw-15. However, whonix-gw-15 no longer appears in the repository for me. 

-----
### Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted
https://www.whonix.org/wiki/Qubes/Reinstall

### Related, [non-duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) issues

![dom0-whonix-command-error](https://user-images.githubusercontent.com/85902586/127332562-909dcf66-11bf-4db0-9a65-1bd039db97ce.png)
![update search gateway](https://user-images.githubusercontent.com/85902586/127332567-a7ca9c84-3d1a-4e5b-a329-1e3d011d859c.png)

### Actual behavior
See screenshots.

### Solutions you've tried
I rebooted, as per Whonix guide (after removing templates), to no avail.

### Additional context
Dom0 had updates but simply would not work through the GUI. After many unsuccesful attempts in Dom0 Terminal, eventually I had an output for updates, in the terminal, but had cancelled the command. Every time I issued the command I realised the updateVM (set to sys-whonix) output was not appearing. If I killed the VM (sys-whonix) and then issued the update command (forcing the VM to start), it would display briefly then go away. 

After changing the updateVM to sys-firewall I can update dom0 through the GUI and the updateVM display output appears everytime. 

Hence, I go to reinstall the template whonix-gw-15. I rename the existing template, and then remove whonix-gw-15. However, whonix-gw-15 no longer appears in the repository for me. 

-----
### Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted
https://www.whonix.org/wiki/Qubes/Reinstall

### Related, [non-duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) issues

![dom0-whonix-command-error](https://user-images.githubusercontent.com/85902586/127332562-909dcf66-11bf-4db0-9a65-1bd039db97ce.png)
![update search gateway](https://user-images.githubusercontent.com/85902586/127332567-a7ca9c84-3d1a-4e5b-a329-1e3d011d859c.png)

**Comment by quser59** [comment]
I note that whonix-gw-15 appears in Qubes Templates Community Testing for R4.1 - should I enable this repo to install whonix-gw, I have not previously enabled it and I have received all updates for whonix templates, so I'm slightly confused.

See:
https://yum.qubes-os.org/r4.1/templates-community-testing/rpm/
https://yum.qubes-os.org/r4.1/templates-community/rpm/

**Comment by unman** [comment]
On Wed, Jul 28, 2021 at 06:54:44AM -0700, quser59 wrote:
> I note that whonix-gw-15 appears in Qubes Templates Community Testing for R4.1 - should I enable this repo to install whonix-gw, I have not previously enabled it and I have received all updates for whonix templates, so I'm slightly confused.
> 
> See:
> https://yum.qubes-os.org/r4.1/templates-community-testing/rpm/
> https://yum.qubes-os.org/r4.1/templates-community/rpm/
> 

Issues like this are best raised on the mailing list or in the Forum.

You enable the Templates repos when you want to install templates.
You get updated *packages* for those templates from the standard repos:
that's why you've been able to receive updates for the templates you
have.

**Comment by fepitre** [comment]
Please look at the documentation: https://www.qubes-os.org/doc/templates/#community.
