### ISSUE TITLE
CI: reproducibility test of vm-fc34 packages is using fc33 repository

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#6808]
### Qubes OS version

R4.1 (R4.0 too)

### Which [testing](https://www.qubes-os.org/doc/testing/) repositories are you using, if any?

n/a

### Are you providing feedback about a specific package or packages in testing?

n/a

### Affected component(s) or functionality

CI

-----
### Brief summary

https://gitlab.com/QubesOS/qubes-desktop-linux-xfce4-xfwm4/-/jobs/1463402359
Installing build dependencies fails:
```
Package desktop-file-utils-0.26-2.fc33.x86_64 is already installed.
Package gettext-0.21-3.fc33.x86_64 is already installed.
No matching package to install: 'libxfce4ui-devel >= 4.16'
Package make-1:4.3-2.fc33.x86_64 is already installed.
No matching package to install: 'xfconf-devel >= 4.16'
Not all dependencies satisfied
Error: Some packages could not be found.
```

Note it's using fc33 packages, not fc34.

### How reproducible

See `repro:vm-fc34` jobs.

### Expected behavior

Package built with fc34 repos.

### Actual behavior

Package built with fc33 repos, and fails.

### Additional context

Likely related to the docker image being fc33-based. But it should build inside a chroot (that it already downloads).

-----

**Comment by fepitre** [comment]
Just checking our configuration files, we don't do reprotest in R4.0?

**Comment by fepitre** [comment]
@marmarek I think we can close this now that all has been updated on CI images and CI files. Please re-open if you see a remaining issue.
