### ISSUE TITLE
Fedora-34-xfce AppVM has Screensaver and Lockscreen Enabled

### ISSUE THREAD

**Issue by deeplow** [QubesOS/qubes-issues#6810]
### Qubes OS version

R4.1

### Which [testing](https://www.qubes-os.org/doc/testing/) repositories are you using, if any?

All testing repos (I think) -- it's from openQA

### Are you providing feedback about a specific package or packages in testing?

No.

### Affected component(s) or functionality

fedora-34-xfce

-----
### Brief summary

![](https://forum.qubes-os.org/uploads/db3820/optimized/2X/d/d9cf09e57600e710bea033317875dd1bac585995_2_690x494.png)

### How reproducible

Did not test. Happened once.

### Steps to reproduce

1.  Start a qube based on the fedora-34-xfce tempalte
2. Leave it idle for a while 

### Expected behavior

screensaver and lockscreen do not show

### Actual behavior

screensaver and lockscreen show as maximized windows

### Additional context

- discussed in the forum (testing team) https://forum.qubes-os.org/t/fedora-34-xfce-appvm-has-screensaver-and-lockscreen-enabled/5387/1
- @marmarek mentioned this related change: https://github.com/QubesOS/qubes-mgmt-salt-dom0-virtual-machines/commit/1d20b65c1163b34485de14c4eaccec68195cb3b1

-----
### Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted

None

**Comment by marmarek** [comment]
Related: replace xfce4-screenlocker with xscreensaver. The former doesn't work in hybrid GUI qube at all (complains about missing DPMS extension). Both are already installed, but only the former is active.

**Comment by marmarek** [comment]
This needs some better solution, for the case when `xfce4-screensaver` gets pulled in by some other package (installed by the user).
