### ISSUE TITLE
Unmodified debian-9 template qrexec timeout, even after template reinstall from repo

### ISSUE THREAD

**Issue by brendanhoar** [QubesOS/qubes-issues#6815]
### Qubes OS version
R4.0

### Which [testing](https://www.qubes-os.org/doc/testing/) repositories are you using, if any?
dom0 has testing repo enabled

### Are you providing feedback about a specific package or packages in testing?
No.

### Affected component(s) or functionality
Startup of debian-9 template

-----
### Brief summary
Recently attempted to update a debian-9 template and two debian-10 templates that were `dist-upgrade`d from debian-9. All are falling into the emergency shell on startup.

~~Note: I understand that debian-9 is no longer supported, but some folks, including myself, had updated debian-9 to debian-10 during the changeover, and even this is failing.~~

*Correction:* debian-9 - andrew stated debian-9 is still supported. Apologies

Notably, the official debian-10 template from the qubes repo does not exhibit this problem.

### How reproducible
Fully for all templates initially based on qubes-template-debian-9.
No problems with any other repo-based templates or variations I have installed (debian-10, fedora-*, whonix-*).

### Steps to reproduce
Removed all copies of debian-9 and debian-9 to debian-10 (via dist-upgrade) templates.
Reinstalled debian-9 from qubes 4.0 repo
Problem remains

### Expected behavior
Start up template. terminal window appears

### Actual behavior
no terminal window, qrexec timeout is reported after 90s, VM is killed

### Solutions you've tried
Removed all copies of debian-9 and debian-9 to debian-10 (via dist-upgrade) templates.
Reinstalled debian-9 from qubes 4.0 repo
Problem remains

### Additional context
*On startup, journalctl indicates that /proc/xen failed to mount.*

I suspect the above failure of /proc/xen to load is the issue.

-----
### Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted
None

### Related, [non-duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) issues
None found

**Comment by andrewdavidwong** [comment]
> Note: I understand that debian-9 is no longer supported

It actually is supported:

https://www.qubes-os.org/doc/supported-releases/#templates

**Comment by andrewdavidwong** [comment]
>> Are you providing feedback about a specific package or packages in testing?
>>
> package is qubes-template-debian-9

But it's not in testing.

**Comment by brendanhoar** [comment]
Hi Andrew -

1. I have stricken the unsupported comment from the ticket.
2. I (mis-)parsed "### Are you providing feedback about a specific package or packages in testing?" as two questions instead of a single question. e.g.
-I am providing feedback about a specific package, yes.
-I am not providing feedback about packages in testing, no.

So to clarify, no, I am not providing feedback to packages in testing, and I will update that part of the ticket.

**Comment by andrewdavidwong** [comment]
> Hi Andrew -
> 
> 
> 
> 1. I have used strike-out on the "debian 9 unsupported" comment.
> 
> 2. I (mis-)parsed "### Are you providing feedback about a specific package or packages in testing?" as two questions instead of a single question. e.g.
> 
> -I am providing feedback about a specific package, yes.
> 
> -I am not providing feedback about packages in testing, no.
> 
> 
> 
> So to clarify, no, I am not providing feedback to packages in testing, and have updated that part of the ticket.

Thanks. While we're on the topic:

>> Which testing repositories are you using, if any?
>>
> dom0 has testing repo enabled

There is more than one testing repo in dom0. 

I've updated the wording of both of these testing-related questions in the issue template. Hopefully they'll be easier to understand now.

**Comment by unman** [comment]
On Mon, Aug 02, 2021 at 08:26:44AM -0700, Andrew David Wong wrote:
> > Note: I understand that debian-9 is no longer supported
> 
> It actually is supported:
> 
> https://www.qubes-os.org/doc/supported-releases/#templates
> 

Debian-9 is EOL. It's available under the LTS program, but isn't
supported by Debian.
I haven't looked at Stretch for some time.

**Comment by h01ger** [comment]
On Wed, Aug 04, 2021 at 06:10:09AM -0700, unman wrote:
> Debian-9 is EOL. It's available under the LTS program, but isn't
> supported by Debian.

well,

Debian 10/buster gets security support from the Debian Security team.
Debian 9/stretch gets security support from the Debian LTS team.

Both are Debian teams staffed by Debian members. In both cases all
packages are supported and exceptions to that are tracked in the
debian-security-support package. Both teams commonly use security-tracker.git
to track security issues.

Debian LTS is also hosted on Debian infrastructure.

Debian 9/stretch LTS will be supported until June 30, 2022, at which
time it will become ELTS. (And Debian 10/buster will become the new LTS
then.)

see https://wiki.debian.org/LTS/ for more info on LTS.

OTOH:

Debian 8/jessie gets security support for a limited number of packages
from an ELTS team at freexian. This is outside of Debian though currently
all people handling ELTS are Debian members too. Debian ELTS is *not* hosted
on Debian infrastructure. ELTS uses a clone of the security-tracker.git
mentioned aboved.

Both LTS and ELTS are funded by sponsors via freexian.
freexian is a the company of a DD.

I do a tiny bit of work these days for (E)LTS though I was more active in the
past. 


-- 
cheers,
	Holger

 ⢀⣴⠾⠻⢶⣦⠀
 ⣾⠁⢠⠒⠀⣿⡁  holger@(debian|reproducible-builds|layer-acht).org
 ⢿⡄⠘⠷⠚⠋⠀  OpenPGP: B8BF54137B09D35CF026FE9D 091AB856069AAA1C
 ⠈⠳⣄

People call vaccine mandates "Orwellian" even though Orwell died at 46 of
tuberculosis, which is now preventable with a vaccine.

**Comment by unman** [comment]
On Wed, Aug 04, 2021 at 06:35:33AM -0700, Holger Levsen wrote:
> On Wed, Aug 04, 2021 at 06:10:09AM -0700, unman wrote:
> > Debian-9 is EOL. It's available under the LTS program, but isn't
> > supported by Debian.
> 
> well,
> 
> Debian 10/buster gets security support from the Debian Security team.
> Debian 9/stretch gets security support from the Debian LTS team.
> 
> Both are Debian teams staffed by Debian members. In both cases all
> packages are supported and exceptions to that are tracked in the
> debian-security-support package. Both teams commonly use security-tracker.git
> to track security issues.
> 
> Debian LTS is also hosted on Debian infrastructure.
> 
> Debian 9/stretch LTS will be supported until June 30, 2022, at which
> time it will become ELTS. (And Debian 10/buster will become the new LTS
> then.)
> 
> see https://wiki.debian.org/LTS/ for more info on LTS.
> 
> OTOH:
> 
> Debian 8/jessie gets security support for a limited number of packages
> from an ELTS team at freexian. This is outside of Debian though currently
> all people handling ELTS are Debian members too. Debian ELTS is *not* hosted
> on Debian infrastructure. ELTS uses a clone of the security-tracker.git
> mentioned aboved.
> 
> Both LTS and ELTS are funded by sponsors via freexian.
> freexian is a the company of a DD.
> 
> I do a tiny bit of work these days for (E)LTS though I was more active in the
> past. 
> 
> 

Have things changed? LTS didn't used to support backports, so not
all packages are supported.

**Comment by andrewdavidwong** [comment]
> On Mon, Aug 02, 2021 at 08:26:44AM -0700, Andrew David Wong wrote:
> > > Note: I understand that debian-9 is no longer supported
> > 
> > It actually is supported:
> > 
> > https://www.qubes-os.org/doc/supported-releases/#templates
> > 
> 
> Debian-9 is EOL. It's available under the LTS program, but isn't
> supported by Debian.
> I haven't looked at Stretch for some time.
> 

You didn't read the link, did you?

**Comment by unman** [comment]
On Wed, Aug 04, 2021 at 05:25:23PM -0700, Andrew David Wong wrote:
> > On Mon, Aug 02, 2021 at 08:26:44AM -0700, Andrew David Wong wrote:
> > > > Note: I understand that debian-9 is no longer supported
> > > 
> > > It actually is supported:
> > > 
> > > https://www.qubes-os.org/doc/supported-releases/#templates
> > > 
> > 
> > Debian-9 is EOL. It's available under the LTS program, but isn't
> > supported by Debian.
> > I haven't looked at Stretch for some time.
> > 
> 
> You didn't read the link, did you?
> 

You're right I didn't. Mea culpa.
Now I'll *have* to look at Stretch.
