### ISSUE TITLE
fix yum repo mirror link in centos 7 template

### ISSUE THREAD

**Issue by olerichter** [QubesOS/qubes-issues#6818]
### Qubes OS version
R4.0

### Names and locations of enabled [testing](https://www.qubes-os.org/doc/testing/) repos

qubes-template-community

### Affected component(s) or functionality

qubes-template-centos-7

-----
### Brief summary
if you install the centos 7 template from scratch, it cant update because it tries to fetch a specific minor release url that is no longer available.

### How reproducible
install template 
run update

### Steps to reproduce

```
sudo qubes-dom0-update --enablerepo=qubes-templates-community qubes-template-centos-7
run qubes vm update
```

or better start template and run:
```
sudo yum update
```
to see log

### Expected behavior

updates

### Actual behavior

fails base mirrors with 404

### proposed Fix:
A)
uncomment baseurl lines in 
`/etc/yum.repos.d/CentOS-Base.repo`
to enable the rewrite of the URL from base/7.minorversion/ to base/7/

this should be applied to the template, so the update works out of the box. Otherwise updating only works as long as you are update regularly and stay on a non eol version, in this case the template would need to be updated to the newest minor version

B)
keep the current `/etc/yum.repos.d/CentOS-Base.repo`, but rebuild template to the newest minor version, and hope the user updates regularly before the minor version goes eol:

the moment the minor version goes eol all its packages are removed from the mirrors and moved to archive resulting in a 404

**Comment by DemiMarie** [comment]
Another option: deprecate the CentOS 7 template.  For one, it has a horribly broken version of RPM, so if `repo_gpgcheck=1` is not set, it is highly insecure.

**Comment by andrewdavidwong** [comment]
> Another option: deprecate the CentOS 7 template. For one, it has a horribly broken version of RPM, so if `repo_gpgcheck=1` is not set, it is highly insecure.

This prompted me to wonder whether CentOS 7 has already reached EOL. To my surprise, it appears that CentOS 8 will reach EOL at the end of this year, while CentOS 7 will remain supported until 2024!

https://endoflife.software/operating-systems/linux/centos

Of course, upstream EOL is independent of Qubes template support EOL, and we have no policy for CentOS, since it's not an official template.

https://www.qubes-os.org/doc/supported-releases/

**Comment by fepitre** [comment]
We have dropped CentOS 7 in R4.1 and also CentOS 8 too (an announcement will be done later in the month after we have build and made available CentOS Stream 8).

**Comment by fepitre** [comment]
Also, the original issue is about `/etc/yum.repos.d/CentOS-Base.repo` meaning it's CentOS specific package. We don't modify CentOS content. It is an upstream issue not Qubes one.

**Comment by andrewdavidwong** [comment]
> Also, the original issue is about `/etc/yum.repos.d/CentOS-Base.repo` meaning it's CentOS specific package. We don't modify CentOS content. It is an upstream issue not Qubes one.

Closing as "not our bug." If you believe this is a mistake, please leave a comment, and we'll be happy to take another look. Thank you.
