### ISSUE TITLE
After screen fills with alert notifications, top-right alert seems like it cannot be dismissed

### ISSUE THREAD

**Issue by Eric678** [QubesOS/qubes-issues#6819]
### Qubes OS version

R4.0 current

### Names and locations of enabled [testing](https://www.qubes-os.org/doc/testing/) repos

None

### Names of affected [testing](https://www.qubes-os.org/doc/testing/) repo packages

dom0?

### Affected component(s) or functionality

UI

-----
### Brief summary

When screen is filled with alert notification boxes, due to some other failure, TRH box cannot be dismissed by selection.

### How reproducible

100% so far, happened twice

### Steps to reproduce

1. See #6777
2. 
3. 

### Expected behavior

One can clear alerts by mouse selection.

### Actual behavior

All except TRH corner alerts can be cleared.

### Solutions you've tried

No workaround found.

### Additional context

-----
### Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted

None

### Related, [non-duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) issues

Posting this as a separate issue as requested by ADW in #6777

**Comment by DemiMarie** [comment]
Fixed in R4.1 I believe.

**Comment by marmarek** [comment]
This may look like it cannot be dismissed, but I think actually they can - but you simply have a lot of them in the same spot and one click dismisses only one of them...

**Comment by andrewdavidwong** [comment]
> Fixed in R4.1 I believe.

Closing as resolved since 4.0 is no longer supported and this is believed to be fixed in 4.1. If anyone believes this issue is not yet resolved, or if anyone is still affected by this issue, please leave a comment, and we'll be happy to reopen it. Thank you.
