### ISSUE TITLE
Dom0 Warning Message Gets Truncated (override_redirect protection)

### ISSUE THREAD

**Issue by deeplow** [QubesOS/qubes-issues#6822]
### Qubes OS version

R4.1

### Names and locations of enabled [testing](https://www.qubes-os.org/doc/testing/) repos

All

### Names of affected [testing](https://www.qubes-os.org/doc/testing/) repo packages

Not sure

### Affected component(s) or functionality

override_redirect warning message

-----
### Brief summary

The override_redirect gets truncated like the picture:

![5ad9e2e560ebe15a6b99acb649bcd9273b66d22a](https://user-images.githubusercontent.com/47065258/128407894-8ea3ae06-4847-49d8-9713-7fbcd172af20.png)

### How reproducible

Didn't test. May be 100%. At least two users experienced this: myself and @unman (posted on the testing team [here](https://forum.qubes-os.org/t/dom0-warnings-truncated-with/5388/4))

### Steps to reproduce

1. get window to try to get override_redirect on large window (see example in #6810)
2. see warning

### Expected behavior

Fully readable message (not truncated)

### Actual behavior

Truncated message shows (see picture)

### Solutions you've tried

None.

### Additional context

- See picture above
- issue came through the testing team [here](https://forum.qubes-os.org/t/dom0-warnings-truncated-with/5388)
- Happened with 1024x768 resolution
- The same happened with 1920x1080 resolution:
     
![override_redirect](https://user-images.githubusercontent.com/47065258/128409498-f20af2ca-d2c0-4a6a-8647-c164fe6f21f2.png)

-----
### Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted

N/A

### Related, [non-duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) issues

- possibly related (but very old) https://github.com/QubesOS/qubes-issues/issues/557

**Comment by SaswatPadhi** [comment]
I can confirm this as well. I have noticed this on my machine.

**Comment by DemiMarie** [comment]
Confirmed.
