### ISSUE TITLE
2FA with Yubikey prompts for unused passwords.

### ISSUE THREAD

**Issue by hackerfactor** [QubesOS/qubes-issues#6823]
### Qubes OS version
R4.1beta
/etc/qubes-release: Qubes release 4.1 (R4.1)

### Names and locations of enabled [testing](https://www.qubes-os.org/doc/testing/) repos
Not sure. See the bug description.

### Names of affected [testing](https://www.qubes-os.org/doc/testing/) repo packages
Not sure. See the bug description.

### Affected component(s) or functionality
2FA login using Yubikey

-----
### Brief summary
Qubes 4.1 prompts for the yubikey password multiple times.

1. In work: Setup the yubikey. (yubikey-personalization-gui).
2. In work: Generate a yubikey passcode (ykchalresp -2 mypassword)
3. In dom0: Add the passcode to luks. (sudo cryptsetup luksAddKey /dev/nvme0n1p3)
4. Make grub support the yubikey (this is the hard part, so I scripted it)

```
#!/bin/bash
grub="/etc/default/grub"
echo "Converting $grub to use yubikey"
cp "$grub" "$grub.bak"
cat "$grub.bak" |
  sed -e 's@rd.luks.uuid=@rd.ykluks.uuid=@g' \
      -e 's@rd.qubes.hide_all_usb@rd.ykluks.hide_all_usb@g' > "$grub"

echo "Generating new bootloader"
grub2-mkconfig -o /boot/efi/EFI/qubes/grub.cfg
echo "Generating new kernel"
dracut -f
```

After rebooting, it prompts for the yubikey (good!).
I plug in the yubikey and enter my ykpassword. The little progresss bar at the bottom moves a little. Then it waits for me to enter my ykpassword a second time.
I enter my ykpassword again. The little progresss bar at the bottom moves a little more. Then it waits for me to enter my ykpassword a third time.
I enter my ykpassword again. Then it boots up.

1. The first prompt says “Disk password”. Just press enter. This password is ignored.
2. The prompt changes to “Password”. Enter the yubikey passphrase. (Received response from Yubikey. Luks device opened.)
3. The third prompt says “Disk password”. Type anything; it is ignored. Then the system boots.

### How reproducible
100%. Always happens.

### Steps to reproduce
See the bug description.

### Expected behavior
I should only see 1 password prompt.

### Actual behavior
With R4.0, I only saw 1 password prompt. I could enter the Yubikey passphrase or text-only disk password and it would unlock. This is the correct behavior.

With R4.1, the first "Disk Password" is always ignored. The second "Password" only works with the Yubikey passphrase; then text-only passwork does not work. The third "Disk Password" is always ignored.

### Solutions you've tried
Tried entering yubikey password at first prompt; fails.
Tried entering the plain text password at the first or third password fails.
Entering the plain text password at the second prompt fails.

### Additional context
Too many failed passwords at the second prompt causes the 2nd prompt to stop accepting the real password. (Doesn't matter how many times you enter it correctly, it fails.)

-----
### Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted
See https://forum.qubes-os.org/t/yubikey-luks-on-qubes-4-1/5373

### Related, [non-duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) issues
None

**Comment by DemiMarie** [comment]
This is not a good idea because it opens dom0 up to USB attacks.  Fixing this will require `sys-usb` to come up in the initramfs.

**Comment by hackerfactor** [comment]
Is there any update or suggestion for resolving this issue?

As I noted in the issue, R4.0 did not do this. It only shows 1 prompt. At the problem, you can enter the yubikey passphrase OR the hard drive password (text, no yubikey, 1FA). It appears to try the yubikey first (2FA) and then falls back to checking if any of the 1FA passwords work.

With R4.1:
- It shows 3 prompts. The first and third prompt are never used.
- The 2nd prompt is for the yubikey. However, it never falls back to checking the 1FA text-only password.

What changed with R4.1 and is there a workaround?

**Comment by hackerfactor** [comment]
> This is not a good idea because it opens dom0 up to USB attacks. Fixing this will require `sys-usb` to come up in the initramfs.

I've been re-reading your reply and scratching my head. Can you explain how using 2FA to unlock the hard drive opens dom0 up to USB attack?

As  far as I can figure out:
1. The bootloader provides the password prompt and USB drivers for handling the 2FA validation. This happens before the hard drive is unlocked and long before dom0 is activated.
2. After unlocking the hard drive, the bootloader's USB drivers are effectively thrown out. The hard drive boots up, dom0 is initialized, and then dom0 spins up sys-usb to handle USB devices.

Since there is a clear separation between the bootloader's USB access and dom0's USB access, I don't see how enabling 2FA during grub can compromise dom0.

**Comment by DemiMarie** [comment]
> > This is not a good idea because it opens dom0 up to USB attacks. Fixing this will require `sys-usb` to come up in the initramfs.
> 
> I've been re-reading your reply and scratching my head. Can you explain how using 2FA to unlock the hard drive opens dom0 up to USB attack?
> 
> As far as I can figure out:
> 
> 1. The bootloader provides the password prompt and USB drivers for handling the 2FA validation. This happens before the hard drive is unlocked and long before dom0 is activated.
> 2. After unlocking the hard drive, the bootloader's USB drivers are effectively thrown out. The hard drive boots up, dom0 is initialized, and then dom0 spins up sys-usb to handle USB devices.
> 
> Since there is a clear separation between the bootloader's USB access and dom0's USB access, I don't see how enabling 2FA during grub can compromise dom0.

This assumes that GRUB’s USB stack does not have any vulnerabilities.  I do not believe this is a good assumption.

**Comment by marmarek** [comment]
> Since there is a clear separation between the bootloader's USB access and dom0's USB access, I don't see how enabling 2FA during grub can compromise dom0.

To clarify Demi's comment, bootloader is responsible for loading Xen, dom0's kernel etc. If it gets compromised, it can inject any kind of code into it. But that's kind of offtopic here, because the proposed solution does not use bootloader to access the 2FA token. It's done in the initramfs, run in early dom0 boot stage. The same argument still stands.

 The risk is mostly about _other_ USB devices present in the system, but specifically that 2FA token. If you can disconnect all the other devices for the system boot time, the risk is much smaller, but that isn't practical approach in many cases (especially if you have some integrated devices, even worse if they have persistent firmware storage - that could be infected).

**Comment by hackerfactor** [comment]
> The risk is mostly about _other_ USB devices present in the system

Doesn't this same issue happen if the computer only has a USB keyboard?

**Comment by marmarek** [comment]
> Doesn't this same issue happen if the computer only has a USB keyboard?

Yes, exactly. That's why it's better to have PS/2 keyboard, or a separate USB controller just for keyboard and no other devices.

**Comment by hackerfactor** [comment]
Given that I don't have the option to change the hardware that is internal to the laptop, what can be done to change the 2FA prompt from 3 password prompts (of which, only the 2nd is used) to just having one password prompt that is used correctly?

**Comment by Szewcson** [comment]
Is the official support for handling Yubikeys in LUKS during boot planed for Qubes? I understand that exposing bootloader to a USB is a security risk but since You made an exclusion for USB keyboard support maybe adding Yubikey option for people that accept the risk will be also acceptable?

**Comment by DemiMarie** [comment]
> Is the official support for handling Yubikeys in LUKS during boot planed for Qubes? I understand that exposing bootloader to a USB is a security risk but since You made an exclusion for USB keyboard support maybe adding Yubikey option for people that accept the risk will be also acceptable?

I do plan on implementing this at some point, but I plan to use a different approach: spawn a USB-handling unikernel from the initramfs.  The unikernel will have a minimal, trusted USB stack in a memory safe language, and in any case dom0 will consider the input from it to be untrusted.

**Comment by OrangeCakeZero** [comment]
> This is not a good idea because it opens dom0 up to USB attacks. Fixing this will require `sys-usb` to come up in the initramfs.
> The risk is mostly about _other_ USB devices present in the system, but specifically that 2FA token. If you can disconnect all the other devices for the system boot time, the risk is much smaller, but that isn't practical approach in many cases (especially if you have some integrated devices, even worse if they have persistent firmware storage - that could be infected).

Hello, Does the GRUB setup of @hackerfactor exposes dom0 to any USB devices before entering LUKS passphrase (before LUKS decryption) or is the exposure limited to Yubikey devices? If if there is such a limitation, doesn't this limit the attack surface more?

**Comment by Joeviocoe** [comment]
An important bit of info not in the original issue (only mentioned in the forum [thread](https://forum.qubes-os.org/t/yubikey-luks-on-qubes-4-1/5373/5))...
https://github.com/the2nd/ykluks was used to update initramfs with a ykluks dracut module.
This was done before updating GRUB with the script (so the GRUB part is not relevant to the problem). 

The mechanism for handling the auth is built into the dracut module that is built from those scripts. So if anything, something in 4.1 changed that probably has a new version that makes the script break.

The OP, @hackerfactor, should probably submit an issue with the2nd’s ykluks repo, but I suspect it's long abandoned since it was made for Qubes 3.2 and is only lucky that it worked for 4.0 at all.

@DemiMarie 
Is there anything in [ykluks.sh](https://github.com/the2nd/ykluks/blob/master/ykluks.sh) and [module-setup.sh](https://github.com/the2nd/ykluks/blob/master/ykluks.sh) that sticks out to you that might have broken from 4.0 to 4.1?  
There is mention of crypttab and xen-pciback.
These scripts build the dracut module that handle all the logic and would be responsible for the issue.

My system doesn't have **rd.luks.hide_all_usb** at all.  And I can't get it to work at all on my 4.1 system.
