### ISSUE TITLE
Desktop does not respect the "primay display" flag in settings

### ISSUE THREAD

**Issue by ddevz** [QubesOS/qubes-issues#6825]
### Qubes OS version

4.0  (current stable)

### Names and locations of enabled [testing](https://www.qubes-os.org/doc/testing/) repos

I believe I have a default setup (I.E. I believe I have no testing repos)

### Names of affected [testing](https://www.qubes-os.org/doc/testing/) repo packages

I believe I have a default setup (I.E. I believe I have no testing repos)

### Affected component(s) or functionality

desktop/taskbar

-----
### Brief summary

In a minimal setup with just 2 monitors, installing dual monitors seems to work fine, and going to "qubes button"->"system tools"->display shows both monitors as expected.
However:
 * if you set the right hand monitor to be the  the "primary display", the taskbar/menubar at the top does not switch to the right hand monitor.
 * If you move (drag) the right hand monitor to be the left hand monitor, the taskbar/menubar switches to display on what is now the left hand monitor, and will not move to the right hand monitor again.

In summary, it seems to be always presenting the bar on "the leftmost display in the layout" instead of the "primary display".
Note that when you move up to a more usable number of monitors, that people will normally want the center display as the primary display.

### How reproducible

100% reproducible on the one machine I've tested it on.

### Steps to reproduce

above

### Expected behavior

above

### Actual behavior

above

### Solutions you've tried

Switching the monitors on the desk.  This obviously leaves something to be desired cause it means that to get to the left hand screen, you move the mouse off the right edge of the screen, and visa-versa.

### Additional context

-----
### Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted

I searched through the bug list (open and closed) and was not able to find any other reports for this.

**Comment by EncryptedGiraffe** [comment]
When I was using dual monitors (I'm not anymore so can't test this), I had to tweak the settings in System Tools -> Panel to get it to move to the monitor I wanted. Also didn't respect the Primary Display setting.

**Comment by ddevz** [comment]
Interesting.  If you change System Tools -> Panel -> "Output:" from "automatic" to "monitor 2", it works!
Thanks so much!

So it's not expected behavior (where the "primary display" flag in the "display" form does nothing), but it can work.
Should I close the report, or change it to a documentation/User Experience thing so the next person doesn't have to go through it?

**Comment by andrewdavidwong** [comment]
> Interesting.  If you change System Tools -> Panel -> "Output:" from "automatic" to "monitor 2", it works!
> 
> Thanks so much!
> 
> 
> 
> So it's not expected behavior (where the "primary display" flag in the "display" form does nothing), but it can work.
> 
> Should I close the report, or change it to a documentation/User Experience thing so the next person doesn't have to go through it?
> 
> 

It doesn't sound like a documentation or UX issue to me. It sounds like a bug in the DE or something. However, it may not be a Qubes-specific bug, in which case it should be closed as "not our big."

**Comment by DemiMarie** [comment]
> It doesn't sound like a documentation or UX issue to me. It sounds like a bug in the DE or something. However, it may not be a Qubes-specific bug, in which case it should be closed as "not our bug."

There is one caveat here: if it is a bug fixed in a later version of the DE, backporting the fix to the old version in dom0 would likely be a good idea.

**Comment by ddevz** [comment]
> > Should I close the report, or change it to a documentation/User Experience thing so the next person doesn't have to go through it?
> 
> It doesn't sound like a documentation or UX issue to me. It sounds like a bug in the DE or something. However, it may not be a Qubes-specific bug, in which case it should be closed as "not our bug."

So "not our bug" means don't help qubes users work around it?  I can close it that way, I just want to be clear on what we are doing.

**Comment by andrewdavidwong** [comment]
> > > Should I close the report, or change it to a documentation/User Experience thing so the next person doesn't have to go through it?
> > 
> > 
> > It doesn't sound like a documentation or UX issue to me. It sounds like a bug in the DE or something. However, it may not be a Qubes-specific bug, in which case it should be closed as "not our bug."
> 
> So "not our bug" means don't help qubes users work around it? I can close it that way, I just want to be clear on what we are doing.

This topic seems to come up often enough that I've decided to add a new FAQ entry for it. Please have a look and let me know whether this answers your question:

https://www.qubes-os.org/faq/#why-dont-you-fix-upstream-bugs-that-affect-qubes-os

> If you want to add something to the documentation, you can.
> On the other hand, since it's an issue that is readily found online
> together with solution, imo it's one of those "don't clutter the docs"
> questions. (I may be in the minority in this view.)

I'm inclined to agree for the reasons explained [here](https://www.qubes-os.org/doc/documentation-style-guide/#core-vs-external-documentation), but I wouldn't be strongly opposed to a brief addition to one of the troubleshooting docs about this.

**Comment by ddevz** [comment]
Of interest:  My desire is for qubes to be a success, and i was attempting to be nicer then "well it works for me, so I don't care anymore".  However I do understand the issue of things splitting your focus.  I'll go ahead and close this issue and see if I can come up with a way to handle things like this in the future that won't effect the focus of qubes developers.

Offical close reason: "not our bug"
