### ISSUE TITLE
4.1 - cute Qubes tray icon is clipped

### ISSUE THREAD

**Issue by unman** [QubesOS/qubes-issues#6826]
### Qubes OS version

4.1  beta-1

### Names and locations of enabled [testing](https://www.qubes-os.org/doc/testing/) repos

dom0 - updates, updates-testing, security-testing

### Names of affected [testing](https://www.qubes-os.org/doc/testing/) repo packages

artwork?
![clipped](https://user-images.githubusercontent.com/13558340/128542989-4c7835f1-828f-4fa5-864f-6afe9fb28776.png)
![clipped](https://user-images.githubusercontent.com/13558340/128543046-5e65592a-268c-48e6-bd7e-1dcc9f1d8f86.png)

### Affected component(s) or functionality

GUI

-----
### Brief summary

The Qube icon in the system tray in Xfce is offset and clipped

### How reproducible

100%

### Steps to reproduce

1. Install Qubes 4.1
2. Update
3. Restart
4. Observe tray. 

### Additional context

This is immediately noticeable on 1366x768 resolution.
See screenshot (first for me) 

-----
### Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted

None

**Comment by ivpn786** [comment]
Duplicate of #6021.

**Comment by andrewdavidwong** [comment]
This appears to be a [duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.
