### ISSUE TITLE
Whonix WS Template not Booting

### ISSUE THREAD

**Issue by bluesteal** [QubesOS/qubes-issues#6827]
Whonix workstation template will boot but the window system will not launch. Trying to diagnose the issue. Checked 

journalctl in dom0 and the logs seem to be referencing PAM although not sure if this is relate.

**Comment by andrewdavidwong** [comment]
Based on our [issue tracking guidelines](https://www.qubes-os.org/doc/issue-tracking/), this does not appear to be suitable for `qubes-issues`. We ask that you please post this on the [Qubes Forum or `qubes-users` mailing list](https://www.qubes-os.org/support/) instead. If, after reading our [issue tracking guidelines](https://www.qubes-os.org/doc/issue-tracking/), you believe we are mistaken, please leave a brief comment explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.
