### ISSUE TITLE
Snap .mount files are randomly unmounted

### ISSUE THREAD

**Issue by SaswatPadhi** [QubesOS/qubes-issues#6836]
### Qubes OS version
 R4.0 & R4.1

### Affected component(s) or functionality
[qubes-app-linux-snapd-helper](https://github.com/QubesOS/qubes-app-linux-snapd-helper)

-----
### Brief summary
Several snaps fail to start, even with `qubes-snapd-helper` installed. Running `snap list` shows that these snaps are broken. Inspecting the systemd mount points reveals that several `snap-<name>-<rev>.mount` were unmounted.

### How reproducible
Depends on the snap. Fully reproducible for anbox and signal, may be for Chromium as well (see #5757).

### Steps to reproduce
(for `anbox` on Debian TemplateVM with VM kernel)

1. In AppVM, run `snap install --devmode --beta anbox`
2. Restart AppVM
3. Notice that `snap list` shows `anbox` is broken!

### Expected behavior
Anbox should work correctly after restarts.

### Actual behavior
Anbox doesn't start; `snap list` says it's broken.
Inspecting the systemd mount points reveals that several `snap-<name>-<rev>.mount` were unmounted.

### Solutions you've tried
Manually running `sudo systemctl start snap-anbox-NNN.mount` (NNN = 186 currently) works as expected.
For anbox, the `core` mount point also needs to be started: `sudo systemctl start snap-core-NNNNN.mount`.

### Additional context
A separate issue with anbox snap is that it installs a new systemd service (called `snap.anbox.container-manager.service`). This is not backed up by the `qubes-snapd-helper` and is thus lost upon restart. Without this service, the snap would appear fine (not `broken`) but would not start (time out).

-----

### Related, [non-duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) issues
#5757 probably has the same root cause.

**Comment by gcbrown** [comment]
Same happens to me when trying to install ungoogled-chromium. I followed the snap instructions on 'how to install software' in the Qubes wiki. It works great until I restart the AppVM at which point I see something like the following (randomly happens each time):

Device /var/lib/snapd/snaps/gnome-3-38-2004_70.snap is removed
Device /var/lib/snapd/snaps/ungoogled-chromium_11.snap is removed 

And whichever one has been removed shows as 'broken' in snap list. @SaswatPadhi have you found a way to stop the snaps from unmounting on every restart, aside from systemctl commands?

**Comment by tlaurion** [comment]
@marmarek @andrewdavidwong 

The workaround specified above works. Would be nice if something similar was implemented by default.

**Comment by maertsen** [comment]
Unfortunately, it does not work for me. My guess is that it’s racy, because a manual execution resolves the issue.

I can now confirm the earlier observation by @gcbrown in https://github.com/QubesOS/qubes-issues/issues/6836#issuecomment-903310640 that the appearance of errormessages seems to coincide with missing mounts. I’m not sure about the cause though.

**Comment by SaswatPadhi** [comment]
> My guess is that it’s racy, because a manual execution resolves the issue.

Yes, that would be my guess too The right solution would to add auto restart/remount capability to these `.mount` files so they are never unmounted.

**Comment by gcbrown** [comment]
@maertsen on my machine, the snaps are not of the form snap-*.mount, but instead var-lib-snapd-snap-*.mount. (This could perhaps be a difference between Fedora and Debian). Once I edited the above command to be:

for m in /etc/systemd/system/var-lib-snapd-snap-*.mount ; do systemctl start $(basename $m) ; done

It worked for me. I haven't tried opening all my snaps from a cold boot of the VM, but it definitely works if the VM is already running. Let me know if this works for you.

I don't know much, but maybe these questions are helpful: why does qubes-snapd-mount skip mounting the snap volumes if the .mount files already exist? Has some behavior of qubes or snapd changed recently to cause this problem, or has this been an issue for more than 3 weeks?

Thanks so much @SaswatPadhi for the quick fix.

**Comment by maertsen** [comment]
I can confirm that @lkubb's solution step 1 (quoted below) completely fixes this problem for me. @SaswatPadhi, would you be willing to try it? If it works consistently for multiple users, perhaps all that's left is a PR? @andrewdavidwong

>     [..] I fixed it with this patch on `qubes-snapd-mount`:
> 
> 
> ```diff
> --- a/qubes-snapd-mount
> +++ b/qubes-snapd-mount
> @@ -50,7 +50,17 @@ Options=nodev,ro,x-gdu.hide
>  [Install]
>  WantedBy=multi-user.target
>  EOF
> -        systemctl -q enable $unit_name.mount
> -        systemctl -q start $unit_name.mount
> +        cat >/etc/systemd/system/$unit_name.automount <<EOF
> +[Unit]
> +Description=Automount unit for ${app}, revision ${revision}
> +
> +[Automount]
> +Where=${target_dir}/${app}/${revision}
> +
> +[Install]
> +WantedBy=multi-user.target
> +EOF
> +        systemctl -q enable $unit_name.automount
> +        systemctl -q start $unit_name.automount
>      fi
>  done
> ```

**Comment by SaswatPadhi** [comment]
Thanks for the ping, @maertsen.

Indeed, @lkubb's patch works. And I believe that's the proper way to fix this problem. In a [previous comment](https://github.com/QubesOS/qubes-issues/issues/6836#issuecomment-911914054), I had narrowed down on it:

> The right solution would be to add auto restart/remount capability to these .mount files 

But I didn't know enough about `systemd`, and automount units in particular, at that time.

Thanks @lkubb! :)

**Comment by maertsen** [comment]
@andrewdavidwong I’m assuming the PR is waiting for review bandwidth, can you ping in due time if there’s anything else that can be done by us users?

**Comment by andrewdavidwong** [comment]
> @andrewdavidwong I’m assuming the PR is waiting for review bandwidth, can you ping in due time if there’s anything else that can be done by us users?

Thanks for the PR! The devs will comment here if they need any further information.

**Comment by SaswatPadhi** [comment]
Thanks again @maertsen for the fix, and @marmarek for merging it. Resolving this issue.
