### ISSUE TITLE
Anaconda shows blank screen in rescue or text mode

### ISSUE THREAD

**Issue by ilka-schulz** [QubesOS/qubes-issues#6839]
### Qubes OS release
R4.0.4

### Brief summary
On a Dell Latitude 5521 (supports only UEFI boot) with Nvidia MX450, Anaconda fails to start the xserver (see #3340). When selecting the `qubes-rescue` boot option in `/EFI/BOOT/BOOTX64.cfg` or adding `rescue` / `inst.rescue` / `inst.text` to the kernel line, Anaconda does not create any output at all, not even the error messages as seen in #3340.

### Steps to reproduce
- have Dell Latitude 5521 with Nvidia MX450
- create Qubes 4.0.4 boot medium and configure `/EFI/BOOT/BOOTX64.cfg` in any ONE of these ways (no combination):
  - switch boot option from `qubes-verbose` to `qubes-rescue`
  - add `rescue` to kernel line
  - add `inst.rescue` to kernel line
  - add `inst.text` to kernel line
  - add `nomodeset` to kernel line
- boot from boot medium

### Expected behavior
Anaconda starts in rescue or in text mode.

### Actual behavior
Init system runs through but blank screen afterwards.

Hint: It can be useful to attach an external monitor via HDMI as the internal monitor goes blank from time to time.

Hint: You can add those `nouveau.modeset=0 rd.driver.blacklist=nouveau video=vesa:off` kernel options from [here](https://www.qubes-os.org/doc/installation-troubleshooting/#not-asking-for-vnc-because-we-dont-have-a-network--x-startup-failed-aborting-installation--pane-is-dead-error-during-installation) or follow any of the other advice given there but it does not make a difference...

Hint: That `i915.alpha_support=1` in the default kernel options is required since I would not get any output at all without that.

Hint: The hardware is pretty fast but the boot process takes roughly half an hour anyways – maybe there is even more wrong... Also, `systemd-udev-settle` fails to start.

**Comment by ilka-schulz** [comment]
I am now sure that the kernel uses the i915 driver for video output: nouveau is disabled and I do not get any output when I do not enable the `i915.alpha_support` kernel option.

The current installer uses the `vmlinuz-5.4.98-1.fc25.qubes` kernel. Can the issue be caused by bad i915 driver implementations in Linux 5.3.x and 5.4.x kernel? https://linuxreviews.org/Intel_graphics#Troubleshooting

I will try those workarounds soon but they sound horrible...

**Comment by fepitre** [comment]
@ilka-schulz what about testing latest beta for R4.1?

**Comment by ilka-schulz** [comment]
> @ilka-schulz what about testing latest beta for R4.1?

Good idea! The newer kernel's i915 driver supports Intel's 11th generation "Tiger Lake" CPUs' GPUs well. ([news article](https://www.phoronix.com/scan.php?page=news_item&px=Intel-Tiger-Lake-Linux-5.7-Hit))

I guess that fixes this bug, so I will close it.

(I still got problems with the newer kernel that it hangs on [this bug](https://bugzilla.kernel.org/show_bug.cgi?id=204887) but that is a separate issue)
