### ISSUE TITLE
NVMe devices on Intel Raid controller not identified

### ISSUE THREAD

**Issue by ilka-schulz** [QubesOS/qubes-issues#6840]
### Qubes OS release

R4.1.0 beta (downloaded August 18th 2021)

(need to use that version because R4.0.4 uses an older kernel that does not support the new Intel Integrated Graphics chip in the CPU, see #6839)

### Brief summary
Qubes does not support any of the laptop's internal NVMe slots.

laptop model: Dell Latitude 5521

CPU: Intel 11th generation i7-11850H "Tiger Lake"

`lspci` output (created with Debian 11 (testing)):
```text
[...]

0000:00:0e.0 RAID bus controller: Intel Corporation Volume Management Device NVMe RAID Controller
	Subsystem: Dell Volume Management Device NVMe RAID Controller
	Control: I/O- Mem+ BusMaster+ SpecCycle- MemWINV- VGASnoop- ParErr- Stepping- SERR- FastB2B- DisINTx+
	Status: Cap+ 66MHz- UDF- FastB2B- ParErr- DEVSEL=fast >TAbort- <TAbort- <MAbort- >SERR- <PERR- INTx-
	Latency: 0
	IOMMU group: 9
	Region 0: Memory at 6072000000 (64-bit, non-prefetchable) [size=32M]
	Region 2: Memory at a4000000 (32-bit, non-prefetchable) [size=32M]
	Region 4: Memory at 6075100000 (64-bit, non-prefetchable) [size=1M]
	Capabilities: <access denied>
	Kernel driver in use: vmd
	Kernel modules: vmd

[...]

10000:e1:00.0 Non-Volatile memory controller: Toshiba Corporation Device 0116 (prog-if 02 [NVM Express])
	Subsystem: Toshiba Corporation Device 0001
	Control: I/O- Mem+ BusMaster+ SpecCycle- MemWINV- VGASnoop- ParErr- Stepping- SERR- FastB2B- DisINTx+
	Status: Cap+ 66MHz- UDF- FastB2B- ParErr- DEVSEL=fast >TAbort- <TAbort- <MAbort- >SERR- <PERR- INTx-
	Latency: 0
	Interrupt: pin A routed to IRQ 0
	NUMA node: 0
	IOMMU group: 9
	Region 0: Memory at a4000000 (64-bit, non-prefetchable) [size=16K]
	Capabilities: <access denied>
	Kernel driver in use: nvme
	Kernel modules: nvme
```

### Steps to reproduce

1. have the specified laptop model (or only the specified NVMe Raid controller, I guess)
2. boot from Qubes R4.1.0 beta boot medium
3. select verbose mode ("Troubleshooting")

### Expected behavior
Anaconda starts and presents SSD to select

### Actual behavior
- boot hangs at starting `systemd-udev-settle.service` for two minutes (timeout is 186 s)
- boot continues and then hangs at "Reached target Basic System"
- debug message `nvme0: I/O 25 QID 0 timeout, completion polled` gets printed to the screen every 30 seconds or so
- boot does not continue

If I add `pci=nomsi` to the boot options, the system boots and Anaconda starts but says it says "No disks detected" and offers network volumes instead.

### Additional information
- That exact same setup works just fine with Debian 11 (testing) but not with Debian 10.10
- That same NVMe SSD has worked fine with Qubes R4.0.3 in a Dell Latitude 7480

**Comment by ilka-schulz** [comment]
`lspci -vvv` run on Anaconda says this about the raid controller:
```text
00:0e.0 RAID bus controller: Intel Corporation Volume Management Device NVMe RAID Controller
	Subsystem: Dell Device 0a67
	Control: I/O- Mem+ BusMaster- SpecCycle- MemWINV- VGASnoop- ParErr- Stepping- SERR- FastB2B- DisINTx-
	Status: Cap+ 66MHz- UDF- FastB2B- ParErr- DEVSEL=fast >TAbort- <TAbort- <MAbort- >SERR- <PERR- INTx-
	Region 0: Memory at 6072000000 (64-bit, non-prefetchable) [size=32M]
	Region 2: Memory at a4000000 (32-bit, non-prefetchable) [size=32M]
	Region 4: Memory at 6075100000 (64-bit, non-prefetchable) [size=1M]
	Capabilities: [80] MSI-X: Enable- Count=19 Masked-
		Vector table: BAR=4 offset=00000000
		PBA: BAR=4 offset=00001000
	Capabilities: [90] Express (v2) Root Complex Integrated Endpoint, MSI 00
		DevCap:	MaxPayload 128 bytes, PhantFunc 0
			ExtTag- RBE- FLReset-
		DevCtl:	CorrErr- NonFatalErr- FatalErr- UnsupReq-
			RlxdOrd- ExtTag- PhantFunc- AuxPwr- NoSnoop-
			MaxPayload 128 bytes, MaxReadReq 128 bytes
		DevSta:	CorrErr- NonFatalErr- FatalErr- UnsupReq- AuxPwr- TransPend-
		DevCap2: Completion Timeout: Not Supported, TimeoutDis- NROPrPrP- LTR-
			 10BitTagComp- 10BitTagReq- OBFF Not Supported, ExtFmt- EETLPPrefix-
			 EmergencyPowerReduction Not Supported, EmergencyPowerReductionInit-
			 FRS-
			 AtomicOpsCap: 32bit- 64bit- 128bitCAS-
		DevCtl2: Completion Timeout: 50us to 50ms, TimeoutDis- LTR- OBFF Disabled,
			 AtomicOpsCtl: ReqEn-
	Capabilities: [e0] Power Management version 3
		Flags: PMEClk- DSI- D1- D2- AuxCurrent=0mA PME(D0-,D1-,D2-,D3hot-,D3cold-)
		Status: D0 NoSoftRst+ PME-Enable- DSel=0 DScale=0 PME-
	Kernel modules: vmd
```

It seems to not find the NVMe device.

**Comment by ilka-schulz** [comment]
I found a **workaround**:

In the Dell Latitude 5521 BIOS version 1.3.0 under "Storage" -> "SATA/NVMe Operation" it is possible to switch modes of the raid controller between
- Disabled
- AHCI/NVMe
- RAID On

AHCI/NVMe works for me.

However, this is not a proper solution...

**Comment by marmarek** [comment]
> It seems to not find the NVMe device.

I think this is expected when the RAID mode is enabled - it's a common practice to hide the underlying storage devices from the operating system, if the data is supposed to go through another controller.

Apparently, it wasn't hidden enough and the OS still tried to interact with NVMe directly (and this is a problem, not the fact it didn't worked).

> AHCI/NVMe works for me.
> 
> However, this is not a proper solution...

So, it seems NVMe works fine, the RAID controller does not. My question is: do you use the RAID functionality (like - have two disks combined by it)? If not, disabling it *is* the proper thing to do, not a workaround.

**Comment by ilka-schulz** [comment]
> I think this is expected when the RAID mode is enabled

Yet, the Debian 11 installer seemlessly identifies the NVMe SSD in the raid controller and installs to it. After that, booting Debian 11 from it works just fine. Qubes does not do that, neither does Debian 10.10.

> do you use the RAID functionality (like - have two disks combined by it)?

I currently only have one disk put in, so, yes, I might as well disable it. However, the OEM (Dell) shipped it with one NVMe SSD with Windows 10 installed and they decided to enable the raid controller. (Note, even Windows works with one SSD and raid controller enabled)

Also, I plan to use the raid controller with two SSDs in the future so it would be nice if it were supported.
