### ISSUE TITLE
Feature: EurKEY keyboard layout

### ISSUE THREAD

**Issue by ilka-schulz** [QubesOS/qubes-issues#6843]
### Qubes OS release

R4.0.4

### Brief summary
In dom0 I can select various keyboard layouts but the popular [EurKEY layout](https://en.wikipedia.org/wiki/EurKEY) is not included. I had to default to `English (international AltGr dead keys)` to get a pretty bad support for German umlauts.

### Steps to reproduce
- open graphical keyboard settings in dom0
- under `Layout`, click `Add`
- try to find EurKEY layout

### Expected behavior
I can select EurKEY layout as an option.

### Actual behavior
I can *not*select EurKEY layout as an option.

**Comment by marmarek** [comment]
This looks to be an Xfce issue, specifically this one: https://gitlab.xfce.org/xfce/xfce4-settings/-/issues/272

The layout itself is installed and can be enabled with `setxkbmap eu` command (sadly - needs to be done after each login). The above ticket includes another workaround - that maybe will persist system restart.

**Comment by ilka-schulz** [comment]
> This looks to be an Xfce issue, specifically this one: https://gitlab.xfce.org/xfce/xfce4-settings/-/issues/272
> 
> The layout itself is installed and can be enabled with `setxkbmap eu` command (sadly - needs to be done after each login). The above ticket includes another workaround - that maybe will persist system restart.

Awesome, that fixed it for me!
