### ISSUE TITLE
Dark modes interfere with system tray menus - promoting user error.

### ISSUE THREAD

**Issue by Ark-of-the-copepod** [QubesOS/qubes-issues#6844]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
4.0

### Brief summary
Dark mode does not apply highlighting to menu selections in drop-down menus of system tray, e.g. PCI attachment, Qubes Domains.

Combined with a latency in pop-up information (on mouse hover), and variations in the position of that pop-up, it can be very easy to confuse selection.

This is non-trivial: I have attached the wrong device to the wrong AppVM a couple of times, despite efforts to take care. 

Dark modes are a very welcome trend in all sorts of OSes. While I understand that GUI refinement hasn't been the focus of Qubes historically, _this_ is a threat to secure operation of a reasonably secure OS. Shouldn't have to chose between 'safe-for-eyeballs/sleep operation' on the one hand and 'operationally robust and secure' on the other.

(currently trying XFCE Dusk / Oxygen icons)

### Steps to reproduce
Try dark theme with various icons. Try system tray menus.

### Expected behavior
Unambiguous and responsive highlighting of menu selection, while still respecting 'dark' theming/mode.

### Actual behavior
No visible highlighting.

Also consulted https://github.com/QubesOS/qubes-issues/issues/6736

**Comment by andrewdavidwong** [comment]
FWIW, I also use dark mode and haven't experienced this, so it probably depends on the theme or something. (I'm using "Adwaita-dark" with Adwaita icons in Xfce.)

**Comment by Ark-of-the-copepod** [comment]
Thanks, Adwaita-dark works well.

I'd still like it to be considered by @ninavizz in here workover/s- shouldn't have malfunctioning options in there.

**Comment by ninavizz** [comment]
Roger that @Ark-of-the-copepod. Thx for flagging!
