### ISSUE TITLE
"Refresh Applications" unnecessarily starts TemplateVM

### ISSUE THREAD

**Issue by ilka-schulz** [QubesOS/qubes-issues#6847]
### Qubes OS release

- R4.0.3
- R4.0.4
- R4.1.0 beta1
- possibly older versions as well

### Brief summary

The `Refresh Applications` button in the `Qube Settings` GUI's `Applications` tab unnecessarily starts the according TemplateVM when refreshing the applications list from an AppVM. Afaik, every application in the TemplateVM is available in the AppVM as well. This prolongs refresh time from a second to half a minute as the TemplateVM is usually not running.

`qvm-sync-appmenus` does not have this bug, btw.

### Steps to reproduce

1. have an AppVM and the TemplateVM it is based on
2. shutdown the TemplateVM or make sure it is already shut down
3. start the AppVM
4. open the `Qube Settings` GUI for the AppVM
5. on the `Applications` tab, press `Refresh Applications`

### Expected behavior

`Qube Settings` GUI receives app list from AppVM within a second or so and is done.

### Actual behavior

`Qube Settings` GUI receives app list from AppVM within a second or so and then starts the TemplateVM to pull the app list from that as well, which takes around half a minute.

**Comment by marmarek** [comment]
> Afaik, every application in the TemplateVM is available in the AppVM as well.

We cannot rely on this assumption. Applications list extracted from a template is stored together with the template - and shared with all the AppVMs based on it. An AppVM can modify `/usr/share/applications` as they wish (you can for example do `dnf install` or `dnf remove`). Sure, such changes won't persist, but nevertheless it means an AppVM is not an authoritative source for list of applications installed in the template - that will affect other AppVMs based on this template too.

BTW, `qvm-sync-appmenus` called on an AppVM refreshes _only_ applications that are installed in this AppVM specifically (in user home, `/usr/local` etc). It does not refreshes applications installed in the template.

**Comment by andrewdavidwong** [comment]
Closing as "not an issue" (the reported behavior is not a bug or similarly for other issue types). If you believe this is a mistake, please leave a comment, and we'll be happy to take another look. Thank you.
