### ISSUE TITLE
4.1 - duplicate non-functional NM applet in tray

### ISSUE THREAD

**Issue by unman** [QubesOS/qubes-issues#6856]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
4.1 varieties

### Brief summary
As reported in [Forum](https://forum.qubes-os.org/t/duplicate-network-manager-icon-in-notification-area-applet/5376) 

### Steps to reproduce
Install 4.1
Note duplicate NM icon in Xfce panel

### Expected behavior
Only one applet

### Actual behavior
Reported second non functional icon.

**Comment by DemiMarie** [comment]
Does not reproduce on my (heavily customized) system.

**Comment by blockomat2100** [comment]
This happens sometimes for me too, but is not limited to the network manager icon.
For me it is the icon next to the whonix one. For example if i opened KeePassXC the whonix icon become the KeePassXC icon.
But is does not happen all the time, sometimes the icon is set correctly, sometimes not.
If I resize the XFCE Panel ("Row Size (pixels)") as described in the forum link mentioned above (e.g. from 32 to something smaller and then back), the correct whonix icon comes back and I can click the icon afterwards.

**Comment by ivpn786** [comment]
I find this issue time to time. Almost(?) always sys-whonix icon is culprit. It can be replced by sys-net (almost always) or clipboard icon (few time). 
Don't know how to get logs for this. Let me know, I can provide logs.
@marmarta, I don't have any network manager desktop file in `/etc/xdg/autostart`.
