### ISSUE TITLE
Keyboard layout choosen during install is not correctly configured after install when running Qubes-OS 4.1 Beta 1

### ISSUE THREAD

**Issue by stman** [QubesOS/qubes-issues#6860]
### Issue details

When installing Qubes-OS 4.1 Beta and choosing a specific keyboard layout during the installation process, this setting is not fully configured later on in Qubes-OS when running Qubes-OS :

It's okay for dom0, but not for all other VM's, where the default english layout will apply.

To correct this, one needs to manualy **uncheck** the [Dom0] Keyboard utility’s “**Use system defaults**” box from the **Layout tab** to force the choosen keyboard layout during installation process to be applied to all VM’s.

If not doing so, the choosen configuration for the keyboard layout choosen during install won’t be applied to all VM’s.

This small configuration bug was not present on the 4.0.4 release of Qubes-OS

### Steps to reproduce

See above. It's straight easy.

### Expected behavior

The “**Use system defaults**” should be unchecked automatically after installation process, like it was the case in Qubes-OS 4.0.4

### Actual behavior

Dom0 uses the choosen keyboard layout during the installation process (Can be easily checked by launching dom0's terminal), but within all other VM's, it's the english layout that is by default activated.

**Comment by stman** [comment]
Yes it is a duplicate, you are right. Still there is more info in my description as I give a workaround. Shall I copy/past my text in this duplicate then ?

**Comment by andrewdavidwong** [comment]
> Yes it is a duplicate, you are right. Still there is more info in my description as I give a workaround. Shall I copy/past my text in this duplicate then ?

Yes, please feel free to copy any pertinent information as a comment onto #6814 (if it's missing from that issue).
