### ISSUE TITLE
Telegram won't connect to socks5 proxy

### ISSUE THREAD

**Issue by Krispy5ockz** [QubesOS/qubes-issues#6863]
I cloned the fedora-30 vm and logged into another telegram. They both eventually ended up in a loop trying to connect to my proxy. I deleted the clone but its still not connecting. The proxy is labeled in green as available so i know thats not the problem. What can I do to connect to the proxy without losing my telegram account?

**Comment by andrewdavidwong** [comment]
Based on our [issue tracking guidelines](https://www.qubes-os.org/doc/issue-tracking/), this does not appear to be suitable for `qubes-issues`. We ask that you please post this on the [Qubes Forum or `qubes-users` mailing list](https://www.qubes-os.org/support/) instead. If, after reading our [issue tracking guidelines](https://www.qubes-os.org/doc/issue-tracking/), you believe we are mistaken, please leave a brief comment explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.
