### ISSUE TITLE
After upgrading to R4.1, dom0 notifications don’t appear

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#6864]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
R4.1

### Brief summary
After upgrading to R4.1, I don’t get notifications in dom0, such as for qube start/stop events.  This could very well be my own fault due to how customized my setup is, but I still wanted to put this out there.

### Steps to reproduce
Upgrade to R4.1

### Expected behavior
Notifications keep working

### Actual behavior
Notifications do not work

**Comment by marmarek** [comment]
Does "domains" widget start? It is responsible for showing the notifications.

**Comment by DemiMarie** [comment]
It does.  I also do not get notifications for when starting a qube fails due to memory exhaustion.

**Comment by marmarek** [comment]
On Sun, Aug 29, 2021 at 09:08:38AM -0700, Demi Marie Obenour wrote:
> It does.  I also do not get notifications for when starting a qube fails due to memory exhaustion.

Maybe notification daemon in dom0 (xfce4-notifyd?) fails to start?

**Comment by DemiMarie** [comment]
> Maybe notification daemon in dom0 (xfce4-notifyd?) fails to start?

Looks like it got clobbered during the distro-sync.

**Comment by scallyob** [comment]
I had this happen to me when using i3 and upgrading to 4.2-RC4. See: https://forum.qubes-os.org/t/no-notifications-in-qubes-os-4-2/22707/8

**Comment by DemiMarie** [comment]
@scallyob I’m pretty sure you hit an unrelated problem.  This is really a bug in the R4.0 → R4.1 upgrade process, which should be closed as R4.0 is end of life.
