### ISSUE TITLE
Create Debian 11 ("Bullseye") template

### ISSUE THREAD

**Issue by straussmaus** [QubesOS/qubes-issues#6865]
Tasks:
- [x] build all packages
- [x] build the template
- [x] document
- [x] upload to testing repo
- [x] migrate to stable repo
- [x] announce

If any issue affects the Debian 11 ("Bullseye") template (build failures, things that worked fine before, etc.), please add a reference to this issue.

**Comment by andrewdavidwong** [comment]
@unman, I couldn't find an existing issue for creating a Debian 11 template. Let me me know if I missed it.

**Comment by marmarek** [comment]
The template is in templates-itl-testing repo currently. But it is not very fresh build, I need to make another one anyway.

**Comment by andrewdavidwong** [comment]
> The template is in templates-itl-testing repo currently. But it is not very fresh build, I need to make another one anyway.

Right, but usually we have an open GitHub issue for creating a new template, and it generally remains open until that template lands in the stable repo of the current stable release. We always seem to do this with Fedora (latest example: https://github.com/QubesOS/qubes-issues/issues/6568); not sure why we don't seem to give Debian the same treatment.

**Comment by andrewdavidwong** [comment]
(I'm replacing the OP body with the same task list as in #6568.)

**Comment by andrewdavidwong** [comment]
(Since it's already in the testing repo, I've checked off the first four tasks.)

**Comment by unman** [comment]
The bullseye build is broken on 4.0 currently.

**Comment by unman** [comment]
This is the sort of issue best raised in the Forums/mailing lists first.
If you had checked the list of supported templates you would have seen
that 4.0 does not (yet) support debian-11.
There is currently no stable debian-11 template available for 4.0
There is a (somewhat aged) template available from the testing repo if
you enable the template-itl-testing repository

**Comment by andrewdavidwong** [comment]
@unman, I think you might be looking at an outdated version of this issue. It has been repurposed to be an issue for creating a Debian 11 template. The point is that we should always have such an issue to track the work of creating such a template when we plan to do it and are working on it. (More generally, all significant work done on Qubes OS should have an associated issue.) Such an issue should be created early on in the process, not just when a stable release draws near.

**Comment by vitali-dev** [comment]
I have installed the Debian 11-minimal under Qubes 4.0 and have problems mounting an exfat USB stick under sys-usb.
The two packages exfat-fuse and exfat-utils are installed.

**Comment by unman** [comment]
On Mon, Sep 06, 2021 at 01:10:21AM -0700, Vitali Repin wrote:
> I have installed the Debian 11-minimal under Qubes 4.0 and have problems mounting an exfat USB stick under sys-usb.
> The two packages exfat-fuse and exfat-utils are installed.
> 

This is best raised in the Forum or the mailing lists, where you will get help.
Take a look at https://qubes-os.org/support/ for your options.
Send a message there with some detail on what problems you have
encountered, and what template you are using for your sys-usb.

**Comment by straussmaus** [comment]
I see that this is in the testing repo and not stable.  Do you need someone to test?  If so please correct this command if there is another I should use:

`qubes-dom0-update --enablerepo=qubes-templates-testing qubes-template-debian-11

(Issue #2621 references "current-testing repository" but I don't know if that's what it is actually called.)

And is there a list of things to check?  I am very comfortable in Debian so should be able to test anything Debian related.  Might need instructions for qubes-specific things.

(It might be next month that I have time)

**Comment by marmarek** [comment]
> First, this command did not work:

There is `qubes-` part in the repo missing, I've updated my comment above.

> Second, is there a checklist of things to test?

Not really, just some generic stuff, like if standard applications work, no unexpected errors on startup etc.

**Comment by straussmaus** [comment]
Installing.  I'll work with it for a week or two and make notes of any problems.

**Comment by straussmaus** [comment]
@vebmaster 

Thanks I think it is just a slow network connection on both ends.

**Comment by marmarek** [comment]
@unman you [said](https://github.com/QubesOS/qubes-issues/issues/6568#issuecomment-966685958) there are some blockers for debian-11, can you link them here?

**Comment by straussmaus** [comment]
Just a general note, I finally was able to install the Debian 11 qube after it migrated to stable.  I don't know why but one possible reason is that the testing repo has a too-slow network connection.

**Comment by andrewdavidwong** [comment]
Oh, it's already migrated to stable? Should I announce it now, @marmarek? I didn't think it would've migrated to stable given this:

> @unman you [said](https://github.com/QubesOS/qubes-issues/issues/6568#issuecomment-966685958) there are some blockers for debian-11, can you link them here?

**Comment by straussmaus** [comment]
I installed this from Stable and it is running well now for some time so I will close this Issue.

**Comment by andrewdavidwong** [comment]
Announced:

https://www.qubes-os.org/news/2021/12/07/debian-11-templates-available/

**Comment by andrewdavidwong** [comment]
To be clear, I still haven't received an answer to https://github.com/QubesOS/qubes-issues/issues/6865#issuecomment-970233073, so I don't know what the deal is there. However, I do know that the Debian 11 templates have been in the stable repos for a while now and that many users are already using them, so the announcement seemed overdue. I would encourage more clarity and rigor in the future, specifically:

1. Refraining from migrating a thing to stable until its status is certain.
2. Granting the go-ahead to announce the thing as soon as it has migrated to stable.

**Comment by marmarek** [comment]
Ah sorry, I gave go-ahead together with Fedora 34 (https://github.com/QubesOS/qubes-issues/issues/6568#issuecomment-966672062)

**Comment by andrewdavidwong** [comment]
> Ah sorry, I gave go-ahead together with Fedora 34 ([#6568 (comment)](https://github.com/QubesOS/qubes-issues/issues/6568#issuecomment-966672062))

Right, I did see that, but then I saw @unman's follow-up comment immediately afterward (https://github.com/QubesOS/qubes-issues/issues/6568#issuecomment-966685958). I didn't see a reply to him there, and I also saw your question here (https://github.com/QubesOS/qubes-issues/issues/6865#issuecomment-966699543) and didn't see any statement on this issue that the Debian template had intentionally migrated to stable, all of which created the impression that only the Fedora template was really ready, while the Debian template was still in question. So, I figured I'd just announced the Fedora template immediately and ask for confirmation about the Debian template (https://github.com/QubesOS/qubes-issues/issues/6865#issuecomment-970233073). No worries, just might need a bit more communication.

**Comment by straussmaus** [comment]
@marmarek 

One issue I notice with the Debian 11 template is with printing.

The same printer, hooked up to the same Qube, using the same USB port.

On Debian 10, the printer auto configures and/or I can set it up in CUPS (127.0.0.1:631).

On Debian 11, it does not auto configure and CUPS does not see it.

In both cases, Qubes seems to recognize the printer as I see a white-on-black status message in the upper right corner staing that the printer is available.  The message is the same for each template.

I'll look into what software differences I might have between the two templates but I doubt that is the issue.

I will reply again if I learn anything.

**Comment by andrewdavidwong** [comment]
> @marmarek
> 
> One issue I notice with the Debian 11 template is with printing.
> 
> The same printer, hooked up to the same Qube, using the same USB port.
> 
> On Debian 10, the printer auto configures and/or I can set it up in CUPS (127.0.0.1:631).
> 
> On Debian 11, it does not auto configure and CUPS does not see it.
> 
> In both cases, Qubes seems to recognize the printer as I see a white-on-black status message in the upper right corner staing that the printer is available. The message is the same for each template.
> 
> I'll look into what software differences I might have between the two templates but I doubt that is the issue.
> 
> I will reply again if I learn anything.

Please open a separate issue for this. This issue is just about creating and releasing the Debian 11 template, not about any further bug fixes or enhancements pertaining to that template.
