### ISSUE TITLE
LUKS decryption at boot - only 1 try when entering a password with more characters than screen width

### ISSUE THREAD

**Issue by UserNo20** [QubesOS/qubes-issues#6866]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
R4.04 - Probably fixed in R4.1

### Brief summary
If you got a very long password for LUKS encryption (approx. 100+ characters) you only get one try on entering your password at boot up though you should have three tries. 
The issue seems actually to be related to passwords that are longer than your screen width (see Steps to reproduce) and not a certain amount of characters.
It also is probably related to Qubes R4.04. using fedora-25.
I tried with fedora-32 and there this bug does not appear/is fixed. I did not try with Qubes R4.1.
Unfortunately I cannot try on fedora-25 directly since my hardware will not boot any Live-fedora-image older than fedora-31 (there the bug does also not appear).
The bug is not related to hardware since I had this bug on my old and new machine and I switched hard drives like 3-4 times since I started using Qubes.
I had it since a very long time but did not come around to file a bug report and it was not that big of a issue for me.

### Steps to reproduce
At the installation of Qubes choose a password for LUKS encryption that is longer than your screen width at boot up (around 100+ characters for me). 
At boot up press  "F12" (or any "F" key). Enter your password. See how after you go beyond your screen width LUKS is creating a new line for every character you enter (very annoying but just that).
Intentionally use a wrong password.
You will be prompted to try again. 
Enter correct password. Machine does not boot up.
If you enter false password on second try you won't get a third try.

It does not matter whether you press the "F" key. The same behaviour appears when entering the LUKS password in graphical mode. 

### Expected behavior
Have 3 tries to enter password even if your password is longer than your screen width at boot up.

### Actual behavior
Only have first try to enter LUKS password that is longer than your screen width.

**Comment by andrewdavidwong** [comment]
This sounds extremely familia, but I wasn't able to find a duplicate.
