### ISSUE TITLE
Cannot attach USB devices to newer Linux VMs using newer qubes-usb-proxy

### ISSUE THREAD

**Issue by nereocystis** [QubesOS/qubes-issues#6868]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
4.0 (R4.0)

### Brief summary
If I choose a USB device from the device-manager-icon  and attach it to any Linux VM, I receive the message in the attached image
However, I can attach it to, say, sys-firewall without a problem.
I can also install to Linux VMs where the template has not been recently updated.

![Screenshot_2021-08-31_12-04-52](https://user-images.githubusercontent.com/2257107/131562069-743d8337-9ae6-4f7e-b5f8-e9032d623836.png)

### Steps to reproduce
If I choose a USB device from the device-manager-icon  and attach it to any Linux VM, I receive the message in the attached image
In this case, I am using Librem 13 Webcam, but the same problem occurs with 3 devices I have attached to the machine
However, I can attach the same device to, say, sys-firewall without a problem.
Here's the info on my VM. The same problem occurs with other VMs
VM which fails
user@personal:~$ uname -a
Linux personal 5.4.136-1.fc25.qubes.x86_64 #1 SMP Fri Jul 30 20:02:52 CEST 2021 x86_64 GNU/Linux

user@personal:~$ dpkg -l|grep usb|grep qubes
ii  qubes-usb-proxy                                             1.1.0+deb10u1                           amd64        USBIP wrapper to run it over Qubes RPC connection

VM which succeeds
user@devel:~$ uname -a
Linux devel 5.4.136-1.fc25.qubes.x86_64 #1 SMP Fri Jul 30 20:02:52 CEST 2021 x86_64 GNU/Linux
user@devel:~$ dpkg -l|grep usb|grep qubes
ii  qubes-usb-proxy                                             1.0.30+deb10u1                          amd64        USBIP wrapper to run it over Qubes RPC connection

The kernel versions are identical. 
Though the qubes-usb-proxy versions are different

I cloned the template VM which devel was based upon, and verified that I could attach the device
Then I updated qubes-usb-proxy, rebooted the clone.
 I can no longer attach the device

### Expected behavior

I should be able to attach the usb device

### Actual behavior

attachment fails

**Comment by nereocystis** [comment]
There was a similar bug in 2018:
https://github.com/QubesOS/qubes-issues/issues/3455

**Comment by conorsch** [comment]
This bit me recently. Same error as above:

<blockquote>
Device attach failed: /usr/lib/qubes/usb-import: 50: /usr/lib/qubes/usb-import: cannot open /sys/devices/platform/vhci_hcd/status: No such fileNo unused port found! VM: "fpf-vault" File: "/usr/lib/qubes/usb-import" Version Control: https://github.com/QubesOS/qubes-app-linux-usb-proxy/blob/master/src/usb-import/usr/lib/qubes/usb-import: 81: /usr/lib/qubes/usb-import: cannot create /sys/devices/platform/vhci_hcd/attach: Directory nonexistent
</blockquote>

As with the reporter above, I'm using a Debian-based template for my vault VM. As a temporary workaround, downgrading to `qubes-usb-proxy=1.0.30+deb10u1` resolved the issue for me. That's n-2 versions ago: downgrading to `qubes-usb-proxy=1.1.0+deb9u1` did _not_ resolve for me. I haven't tested with Fedora-based templates yet.

**Comment by tlaurion** [comment]
@marmarek 

```
[user@dom0 ~]$ qvm-usb
Failed to list 'usb' devices, this device type either does not exist or you do not have access to it.
```

Freshly updated debian-10/fedora-33 and dom0. 

sys-usb based on fedora:
```
[user@sys-usb ~]$ lsusb
Bus 004 Device 002: ID 8087:0024 Intel Corp. Integrated Rate Matching Hub
Bus 004 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 003: ID 04f2:b2ea Chicony Electronics Co., Ltd Integrated Camera [ThinkPad]
Bus 002 Device 002: ID 8087:0024 Intel Corp. Integrated Rate Matching Hub
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 005 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 001 Device 002: ID 0627:0001 Adomax Technology Co., Ltd QEMU USB Tablet
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```

**Comment by tlaurion** [comment]
@marmarek 

With fedora-33 template having qubes-usb-proxy-1.0.30-1.fc33.noarch installed:
```
[user@dom0 ~]$ sudo qubes-dom0-update qubes-usb-proxy-dom0-1.0.30-1.fc25
[user@dom0 ~]$ sudo reboot
[user@dom0 ~]$ qvm-usb
BACKEND:DEVID  DESCRIPTION                                      USED BY
sys-usb:4-1.6  Chicony_Electronics_Co.__Ltd._Integrated_Camera  
```

**Comment by tlaurion** [comment]
@andrewdavidwong @fepitre : can the faulty package be removed from repositories so users do not upgrade and flood the support channels?

**Comment by marmarek** [comment]
I think those may be two separate issues - one at dom0 side (reported by @tlaurion ) and one at debian template side (reported by @nereocystis ).
@tlaurion - can you check `journalctl` in dom0 after failed `qvm-usb` call?

@nereocystis / @conorsch - can you check your debian template if you have `/usr/sbin/modprobe`, or `/sbin -> usr/sbin` symlink in general?

**Comment by tlaurion** [comment]
Update: 
```
sudo qubes-dom0-update qubes-usb-proxy-dom0-1.0.30-1.fc25
sudo reboot
```
Then 
`sudo qubes-dom0-update`

....
Makes it work again?!

```
[user@dom0 ~]$ rpm -qa | grep qubes-usb-proxy
qubes-usb-proxy-dom0-1.1.0-1.fc25.noarch
```

```
[user@sys-usb ~]$ rpm -qa | grep qubes-usb-proxy
qubes-usb-proxy-1.1.0-1.fc33.noarch
```

```
[user@dom0 ~]$ qvm-usb
BACKEND:DEVID  DESCRIPTION                                      USED BY
sys-usb:3-1.6  Chicony_Electronics_Co.__Ltd._Integrated_Camera  
```

**Comment by nereocystis** [comment]
Here's journalctl entry:
Sep 02 13:21:30 dom0 qrexec[22060]: qubes.USB+2-4: personal -> sys-usb: allowed to sys-usb
In broken VM, I don't have /usr/sbin/modprobe
In working VM
user@devel:~$ ls -l /sbin/modprobe 
lrwxrwxrwx 1 root root 9 Feb  9  2019 /sbin/modprobe -> /bin/kmod

**Comment by nereocystis** [comment]
And /sbin does not link to /usr/sbin. They are 2 separate directories
Both in working and non-working VMs

**Comment by nereocystis** [comment]
I don't get the same problem on dom0 as @tlaurion has:
[dom0]$ qvm-usb
sys-usb:2-3  04ca_300d         
sys-usb:2-4  QUANTA_HD_WebCam 

[@dom0 ~]$ rpm -qa|grep qubes-usb-proxy
qubes-usb-proxy-dom0-1.1.0-1.fc25.noarch

**Comment by kramse** [comment]
Workaround, or if you cannot upgrade right now

It seems on my Debian the usb-import checks for modprobe in /usr/sbin - doesn't find it, then does not load the module, things don't work. So I got the same error as others.

quick fix before attaching the device, in you AppVM:
user@Projects:~$ sudo modprobe vhci-hcd 
user@Projects:~$ lsmod | grep vhci
vhci_hcd               57344  0
usbip_core             36864  1 vhci_hcd

then I could attach my USB device :-D

**Comment by nereocystis** [comment]
I just tested the change. It works.
dom0 change alone wasn't enough, but installing the Debian update allowed me to attach USBs to the VM
Thanks.
