### ISSUE TITLE
`qvm-copy-to-vm` from dom0 should not wait for a GUI session

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#6874]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
Not sure if this was on R4.0 or R4.1.

### Brief summary
`qubes.Filecopy` waits for a GUI session in the destination qube, even though there is no point in doing so.  This prevents copying files into a qube if the GUI session does not start.

### Steps to reproduce
Prevent the GUI in a qube from starting, then try to copy files into it.

### Expected behavior
Copy succeeds

### Actual behavior
Copy hangs

**Comment by DemiMarie** [comment]
@marmarek see edit — it’s a bug in `qvm-copy-to-vm`, which omits `--no-gui` from the `qvm-run` args.

**Comment by andrewdavidwong** [comment]
Does this affect Qubes 4.1?

**Comment by marmarek** [comment]
Yes, but it's fixed already. There was a duplicate opened at https://github.com/QubesOS/qubes-issues/issues/8239, and commits are associated with that one.

**Comment by bzillacodes** [comment]
> Yes, but it's fixed already. There was a duplicate opened at https://github.com/QubesOS/qubes-issues/issues/8239, and commits are associated with that one.

Does this fix `qubes.Input*` prompts not showing from sys-usb in dom0?
