### ISSUE TITLE
im having trouble installing qubes os into an external 500 GB SSD

### ISSUE THREAD

**Issue by kitkatmitmat** [QubesOS/qubes-issues#6875]
![FE682667-E23B-4BA0-8356-1CA5DC10DD59](https://user-images.githubusercontent.com/90080260/132083049-48ee3f7e-021f-4d29-bfdb-578c55232b36.jpeg)
does anyone have any solutions or explanantions to this?
This keeps happening after i press finish configuration before its supposed to prompt into the login screen, but it never gets to the stage where it prompts the login screen and freezes on this black screen beforehand.
My pc’s specs are:
Intel Core i-5 10th gen
16 GB RAM 1 TB HDD + 256 GB SSD ( Although i am installing qubes on an external 500 gb ssd)
Nvidia GTX 1650 with Intel IGP ( i always switched to the integrated GPU before installation)
i would appreciate some help.

**Comment by andrewdavidwong** [comment]
Based on our [issue tracking guidelines](https://www.qubes-os.org/doc/issue-tracking/), this does not appear to be suitable for `qubes-issues`. We ask that you please post this on the [Qubes Forum or `qubes-users` mailing list](https://www.qubes-os.org/support/) instead. If, after reading our [issue tracking guidelines](https://www.qubes-os.org/doc/issue-tracking/), you believe we are mistaken, please leave a brief comment explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.
