### ISSUE TITLE
Ryzen 7 4750U does not boot with dom0 kernel 5.13.x

### ISSUE THREAD

**Issue by n0madK** [QubesOS/qubes-issues#6881]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

Qubes 4.1 current-testing
dom0 kernel 5.13.13

### Brief summary

I am unable to boot any of the 5.13.x kernels on AMD Ryzen 7 PRO 4750U. After grub, the screen goes black and the laptop reboots. Currently booting off of 5.12.14 as a workaround.

### Steps to reproduce

On a Ryzen 7 PRO 4750U laptop, boot any 5.13.x kernel

### Expected behavior

Laptop boots normally

### Actual behavior

Laptop reboots immediately after grub. Nothing outputs to screen, and nothing is persisted in the logs.

Do you have any ideas to troubleshoot this further?

**Comment by na--** [comment]
This is the exact same issue I have. My laptop has AMD Ryzen 7 4800H, and I had the problem with both `v5.13.13` (https://github.com/QubesOS/updates-status/issues/2605) and `v5.13.6` (https://github.com/QubesOS/updates-status/issues/2578)

**Comment by johnnyboy-3** [comment]
Same issue here with AMD Ryzen 2400G on Qubes R4.1.0-beta1 and kernel-latest.
Default kernel runs fine, kernel-latest reboots before reaching luks password prompt.
I removed console=none and quiet from boot.cfg to check if there are any error messages, but xen seems to boot fine. No big (XEN) error messages. screen goes blank, then reboot.

**Comment by marmarek** [comment]
Try adding `console=hvc0 earlyprintk=xen` to Linux, and `loglvl=all guest_loglvl=all vga=,keep console=vga noreboot` to xen. Hopefully, this will get you see the Linux kernel panic message...

**Comment by johnnyboy-3** [comment]
Unfortunately the screen stays blank.
Booting without  `vga=,keep console=vga` gives me a screen with (XEN) messages again, but goes blank as before and stays blank (no reboot this time).

**Comment by ydirson** [comment]
It would be great to get updated firmware packages (and not only for enabling new GPUs, as our RENOIR required on 4.0), so we are sure newer driver versions get the ones they expect.

Between 5.12 and 5.13, there are a few fw-related changes in amdgpu - notably they changed things so on RENOIR they don't try to load the "mec2" firmware any more (whatever that is...)

**Comment by marmarek** [comment]
I think the issue is rather related to the CPU ucode. If I strip earlycpio from initramfs, then it boots correctly. I see two options:
 - Linux ucode loading got broken for AMD between those releases (in fact, dom0 should _not_ load ucode, Xen should do that)
 - ucode update changes something that makes newer Linux crash early

The crash happens very early in the dom0 boot process - before Linux kernel even prints its version.

Tested on Ryzen 5 4500U. It may be a different issue, but it's unlikely.

**Comment by marmarek** [comment]
FWIW the same happens on kernel 5.14

**Comment by DemiMarie** [comment]
> * Linux ucode loading got broken for AMD between those releases (in fact, dom0 should _not_ load ucode, Xen should do that)

Could the “should not load μcode when under Xen” check be broken?  That would certainly explain this behavior.

**Comment by marmarek** [comment]
Bisected down to torvalds/linux@a799c2bd29d19

**Comment by marmarek** [comment]
Crash message (from Xen):

![amd-dom0-crash](https://user-images.githubusercontent.com/726704/133084966-5038f37e-001b-4688-9f90-83d09be3dc2d.jpg)

**Comment by DemiMarie** [comment]
Talk about a useless stack trace!

**Comment by marmarek** [comment]
Fix: https://lore.kernel.org/lkml/20210914094108.22482-1-jgross@suse.com/T/#u

**Comment by johnnyboy-3** [comment]
I can confirm this fix works for me.

**Comment by ydirson** [comment]
Works here as well.  ggwp :)

**Comment by bigdx** [comment]
Is that patched kernel somewhere available for qubes?

But "commit zapped from the x86/urgent lineup. We'll have to have a third try later." ... so the patch is not final yet!?

**Comment by isodude** [comment]
This is not yet upstream anywhere I can find at least.

**Comment by marmarek** [comment]
I just got a notification about the patch being pulled into 5.14 branch, so it should be available in the next 5.14.x kernel.

**Comment by n0madK** [comment]
Just booted with 5.14.9 :+1:

**Comment by n0madK** [comment]
@na-- yes this issue is resolved. I was also able to clean install from the 4.1-rc1 iso and update the kernel to latest with no issues. Kernel 5.14 also cleared up a NVMe stall I have been getting on battery since 5.11 :+1:
