### ISSUE TITLE
`Couldn't open file /var/lib/qubes/updates/repodata/repomd.xml`

### ISSUE THREAD

**Issue by ydirson** [QubesOS/qubes-issues#6885]
### Qubes OS release

4.1beta

### Brief summary

Since suspend does not work well with the 5.10 default kernel in 4.1, I wanted to test the most uptodate `kernel-latest`, and without much fuss just tried:

```
[root@dom0 ~]# qubes-dom0-update kernel-latest
Using sys-firewall as UpdateVM to download updates for Dom0; this may take some time...
Qubes OS Repository for Dom0                                                                                                                                  0.0  B/s |   0  B     00:00    
Errors during downloading metadata for repository 'qubes-dom0-cached':
  - Curl error (37): Couldn't read a file:// file for file:///var/lib/qubes/updates/repodata/repomd.xml [Couldn't open file /var/lib/qubes/updates/repodata/repomd.xml]
Error: Failed to download metadata for repo 'qubes-dom0-cached': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
[root@dom0 ~]# ls /var/lib/qubes/updates/repodata/
[root@dom0 ~]# 
```

Digging a bit I found https://github.com/QubesOS/qubes-issues/issues/1685 which was about a "nothing to update" case.

Now if I just run `qubes-dom0-update` I see downoads going on; I interrupt this with Ctrl-C and try again my original commandline:

```
[root@dom0 ~]# qubes-dom0-update kernel-latest
Using sys-firewall as UpdateVM to download updates for Dom0; this may take some time...
Qubes OS Repository for Dom0                                                                                                                                  2.9 MB/s | 3.0 kB     00:00    
Qubes OS Repository for Dom0                                                                                                                                  4.0 MB/s |  70 kB     00:00    
Package kernel-latest-1000:5.12.9-1.fc25.qubes.x86_64 is already installed.
Package kernel-latest-1000:5.12.14-1.fc25.qubes.x86_64 is already installed.
Package kernel-latest-1000:5.12.14-1.fc32.qubes.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
[root@dom0 ~]# 
```

... so this looks like an edge case not fixed with #1685 ?

**Comment by andrewdavidwong** [comment]
Duplicate of #1685

**Comment by andrewdavidwong** [comment]
This appears to be a [duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Comment by Rot127** [comment]
Had the same problem with simple `sudo dnf update` in the xfce terminal. Thanks to @marmarek tip, I tried to run the update in a xterm window and it worked afterwards in the xfce terminal again.

**Comment by ThePowerOfDreams** [comment]
On R4.1 GA, I'm getting this:
`[user@dom0 ~]$ sudo qubes-dom0-update --enablerepo=qubes-dom0-unstable kernel-qubes-vm
Using sys-whonix as UpdateVM to download updates for Dom0; this may take some time...
Qubes OS Repository for Dom0                    0.0  B/s |   0  B     00:00    
Errors during downloading metadata for repository 'qubes-dom0-cached':
  - Curl error (37): Couldn't read a file:// file for file:///var/lib/qubes/updates/repodata/repomd.xml [Couldn't open file /var/lib/qubes/updates/repodata/repomd.xml]
Error: Failed to download metadata for repo 'qubes-dom0-cached': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
Ignoring repositories: qubes-dom0-cached
Package kernel-qubes-vm-1000:5.10.76-1.fc32.qubes.x86_64 is already installed.
Package kernel-qubes-vm-1000:5.10.90-1.fc32.qubes.x86_64 is already installed.
Package kernel-qubes-vm-1000:5.10.96-1.fc32.qubes.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!`

This also occurs when sys-net is used for updates.

**Comment by DemiMarie** [comment]
Does using `--clean` solve the problem?

**Comment by ThePowerOfDreams** [comment]
It does not; IIRC, the first line of the `sh` window says that zero files were removed, but the problem continues.

**Comment by Geblaat** [comment]
I upgraded from R4.0 to R4.1 and now I'm having the same issue.

**Comment by carriesnyder** [comment]
I'm on R4.1 and having the same issue.

**Comment by Geblaat** [comment]
> I'm on R4.1 and having the same issue.

Fresh install or upgrade from R4.0? I had it after upgrading. Did a fresh install later and issue was gone.

**Comment by thecryptofruit** [comment]
I upgraded from R4.0 to R4.1 and now I'm having the same issue, too. I noted that on 4.1, upgrading fedora-34 to 36 fails with OP's error, but 34 to 35 works.

**Comment by thecryptofruit** [comment]
I really didn't want to do it like so, because it is sketchy, but couldn't wait anymore, so resolved it by manually updating `/etc/yum.repos.d/qubes-r4.repo` to reference `qubes-vm-r4.1-current`. HTH

**Comment by Szewcson** [comment]
Got it on 4.2. Not sure if I have it on 4.1

**Comment by euidzero** [comment]
It prevents the upgrade from 4.1  to 4.2 for me  when trying
`sudo qubes-dist-upgrade -r -k -j`

**Comment by moonlitOrca** [comment]
Same here.  I am getting this error thrown in phase 2 of the upgrade from 41. to 4.2, and it stops the process

**Comment by marmarek** [comment]
What happens if you call `sudo qubes-dom0-update --console --show-output` ? Do you get more details?

Does calling `qubes-dom0-update --clean` help?

**Comment by moonlitOrca** [comment]
Thanks for the suggestions.  Unfortunately, they do not seem to make a difference with this and I am getting the same error.  I will try to provide as much detail as I can, in case it is helpful:

Firstly, I tried running `sudo qubes-dom0-update --console --show-output` and then `qubes-dom0-update --clean` independently without the upgrade process and both ran correctly and dom0 updated completely with no errors and no extra verbose logging.  So it seems dom0 updates fine.

The trouble starts when I try to upgrade the distribution to 4.2.  For example: If I simply run `qubes-dist-upgrade` alone with no arguments, it will proceed this way `WARNING: /!\ MAKE SURE YOU HAVE MADE A BACKUP OF ALL YOUR VMs AND dom0 DATA /!\
-> Launch upgrade process? [y/N] y
---> Allow shutdown of unnecessary VM (use --keep-running to exclude some): [y/N] y`
But then it will do nothing and simple return me to the dom0 prompt.

If I run the suggested upgrade command from the documentation `sudo qubes-dom0-update -y qubes-dist-upgrade`, then I get much more activity, including the error mentioned above:
> Using sys-firewall as UpdateVM to download updates for Dom0; this may take some time...
>Qubes OS Repository for Dom0                    0.0  B/s |   0  B     00:00    
>Errors during downloading metadata for repository 'qubes-dom0-cached':
 > - Curl error (37): Couldn't read a file:// file for file:///var/lib/qubes/updates/repodata/repomd.xml >[Couldn't open file /var/lib/qubes/updates/repodata/repomd.xml]
>Error: Failed to download metadata for repo 'qubes-dom0-cached': Cannot download repomd.xml: >Cannot download repodata/repomd.xml: All mirrors were tried
>Ignoring repositories: qubes-dom0-cached
>Package qubes-dist-upgrade-4.1.1-1.fc32.noarch is already installed.
>Dependencies resolved.
>Nothing to do.
>Complete!`

If I run just stage 1 of the upgrade or use the pre-reboot argument `sudo qubes-dist-upgrade --all-pre-reboot` then it starts stage 1 and updates the VMs sequentially.  For me this always fails because qubes tries to update my Windows 11 HVM which it always fails at and returns `Windows: ERROR (exit code 20, details in /var/log/qubes/mgmt-Windows.log)`  I am not sure how to exclude those from the process, but once that happens, it simply exits the process and returns me to the prompt.  I *assume* that if it did not try to update my windows HVM, then it would succeed at stage 1.  

So I tried just calling stage 2 to skip that error: `sudo qubes-dist-upgrade --release-upgrade` .   This process is where we see that dom0-cached error message almost immediately, so perhaps the issue comes when stage 2 is called:  

> 
> WARNING: /!\ MAKE SURE YOU HAVE MADE A BACKUP OF ALL YOUR VMs AND dom0 DATA /!\
> -> Launch upgrade process? [y/N] y
> ---> (STAGE 2) Upgrading 'qubes-release'...
> Using sys-firewall as UpdateVM to download updates for Dom0; this may take some time...
> Qubes OS Repository for Dom0                                                                          0.0  B/s |   0  B     00:00    
> Errors during downloading metadata for repository 'qubes-dom0-cached':
>   - Curl error (37): Couldn't read a file:// file for file:///var/lib/qubes/updates/repodata/repomd.xml [Couldn't open file /var/lib/qubes/updates/repodata/repomd.xml]
> Error: Failed to download metadata for repo 'qubes-dom0-cached': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
> Ignoring repositories: qubes-dom0-cached
> Package google-noto-sans-fonts-20181223-7.fc32.noarch is already installed.
> Package google-noto-serif-fonts-20181223-7.fc32.noarch is already installed.
> Dependencies resolved.
> Nothing to do.
> Complete!
> Using sys-firewall as UpdateVM to download updates for Dom0; this may take some time...
> Qubes OS Repository for Dom0                                                                          0.0  B/s |   0  B     00:00    
> Errors during downloading metadata for repository 'qubes-dom0-cached':
>   - Curl error (37): Couldn't read a file:// file for file:///var/lib/qubes/updates/repodata/repomd.xml [Couldn't open file /var/lib/qubes/updates/repodata/repomd.xml]
> Error: Failed to download metadata for repo 'qubes-dom0-cached': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
> Ignoring repositories: qubes-dom0-cached
> Package qubes-release-4.1-5.fc32.noarch is already installed.
> Dependencies resolved.
> Nothing to do.
> Complete!
> WARNING: /etc/yum.repos.d/qubes-dom0.repo is not updated to R4.2 version
> grep: /etc/yum.repos.d/qubes-dom0.repo.rpmnew: No such file or directory

I apologize for the lengthy post; I just want to give you as much information as to the cause as I can.  Please let me know if you need anything else tested, as I am happy to help.

**Comment by marmarek** [comment]
> I am not sure how to exclude those from the process, 

You can use `--only-update` option to list templates/standalones to update, contrary to the help message, it applies to stage 1 too (there isn't really an exclude option). Anyway, since updating others worked, you can skip this stage in subsequent attempts (but you will run into similar issue in stage 4...).


> * Curl error (37): Couldn't read a file:// file for file:///var/lib/qubes/updates/repodata/repomd.xml [Couldn't open file /var/lib/qubes/updates/repodata/repomd.xml]

This error usually means updatevm (sys-firewall in your case) failed to download updates.

Just an idea - have you maybe modified `/etc/yum.repos.d/qubes-dom0.repo` to have explicit `4.1` version instead of `$releasever`?

**Comment by moonlitOrca** [comment]
Thanks!  

> Just an idea - have you maybe modified `/etc/yum.repos.d/qubes-dom0.repo` to have explicit `4.1` version instead of `$releasever`?

I just checked in dom0, and qubes-dom0.repo seems to use `r$releasever/` everywhere, and I don't see explicit version numbers.

Basically the sources all look something like this:

> https://yum.qubes-os.org/r$releasever/current/dom0/fc32/repodata/repomd.xml.metalink

**Comment by marmarek** [comment]
What template your sys-firewall is based on?

**Comment by marmarek** [comment]
Can you try `sudo qubes-dom0-update --console --show-output --releasever=4.2 qubes-release`  (do _not_ confirm installing it)? Do you have some more detailed error then?

**Comment by moonlitOrca** [comment]
My sys-firewall is based on fedora-38-dvm.  

I just ran `sudo qubes-dom0-update --console --show-output --releasever=4.2 qubes-release` and this is the response:

> Using sys-firewall as UpdateVM to download updates for Dom0; this may take some time...
> Fedora 32 - x86_64                              5.2 kB/s | 5.1 kB     00:00    
> Fedora 32 - x86_64 - Updates                     12 kB/s | 5.0 kB     00:00    
> Qubes Dom0 Repository (updates)                  29 kB/s |  55 kB     00:01    
> Qubes Dom0 Repository (updates-testing)         335 kB/s | 4.1 MB     00:12    
> Qubes Dom0 Repository (security-testing)         63  B/s | 153  B     00:02    
> Errors during downloading metadata for repository 'qubes-dom0-security-testing':
>   - Status code: 404 for https://yum.qubes-os.org/r4.2/security-testing/dom0/fc32/repodata/repomd.xml.metalink (IP: 147.75.102.29)
> Error: Failed to download metadata for repo 'qubes-dom0-security-testing': Cannot prepare internal mirrorlist: Status code: 404 for https://yum.qubes-os.org/r4.2/security-testing/dom0/fc32/repodata/repomd.xml.metalink (IP: 147.75.102.29)
>

**Comment by marmarek** [comment]
Oh, ok, I see the problem. Try now.

**Comment by moonlitOrca** [comment]
Your change has made the command `sudo qubes-dom0-update --console --show-output --releasever=4.2 qubes-release` run through cleanly.  That succeeds.

So, I tried once more to run stage 2 of the upgrade and, while I still get the same error once, I don't get it the second time and it seems to succeed?

> 
> sudo qubes-dist-upgrade --release-upgrade --keep-running mullvadVPN-N
> WARNING: /!\ MAKE SURE YOU HAVE MADE A BACKUP OF ALL YOUR VMs AND dom0 DATA /!\
> -> Launch upgrade process? [y/N] y
> ---> (STAGE 2) Upgrading 'qubes-release'...
> Using sys-firewall as UpdateVM to download updates for Dom0; this may take some time...
> Qubes OS Repository for Dom0                                                                             0.0  B/s |   0  B     00:00    
> Errors during downloading metadata for repository 'qubes-dom0-cached':
>   - Curl error (37): Couldn't read a file:// file for file:///var/lib/qubes/updates/repodata/repomd.xml [Couldn't open file /var/lib/qubes/updates/repodata/repomd.xml]
> Error: Failed to download metadata for repo 'qubes-dom0-cached': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
> Ignoring repositories: qubes-dom0-cached
> Package google-noto-sans-fonts-20181223-7.fc32.noarch is already installed.
> Package google-noto-serif-fonts-20181223-7.fc32.noarch is already installed.
> Dependencies resolved.
> Nothing to do.
> Complete!
> Using sys-firewall as UpdateVM to download updates for Dom0; this may take some time...
> Qubes OS Repository for Dom0                                                                             2.9 MB/s | 3.0 kB     00:00    
> Qubes OS Repository for Dom0                                                                              59 kB/s | 1.6 kB     00:00    
> Package qubes-release-4.1-5.fc32.noarch is already installed.
> Dependencies resolved.
> =========================================================================================================================================
>  Package                          Architecture              Version                           Repository                            Size
> =========================================================================================================================================
> Upgrading:
>  qubes-release                    noarch                    4.2-0.3.fc32                      qubes-dom0-cached                     34 k
> 
> Transaction Summary
> =========================================================================================================================================
> Upgrade  1 Package
> 
> Total size: 34 k
> Is this ok [y/N]: y
> Downloading Packages:
> Running transaction check
> Transaction check succeeded.
> Running transaction test
> Transaction test succeeded.
> Running transaction
>   Preparing        :                                                                                                                 1/1 
>   Upgrading        : qubes-release-4.2-0.3.fc32.noarch                                                                               1/2 
> warning: /etc/yum.repos.d/qubes-dom0.repo created as /etc/yum.repos.d/qubes-dom0.repo.rpmnew
> 
>   Cleanup          : qubes-release-4.1-5.fc32.noarch                                                                                 2/2 
>   Running scriptlet: qubes-release-4.2-0.3.fc32.noarch                                                                               2/2 
> Running timer as unit: run-r93d55c74f3ee4431a3c77057c7b866ca.timer
> Will run service as unit: run-r93d55c74f3ee4431a3c77057c7b866ca.service
> 
>   Running scriptlet: qubes-release-4.1-5.fc32.noarch                                                                                 2/2 
>   Verifying        : qubes-release-4.2-0.3.fc32.noarch                                                                               1/2 
>   Verifying        : qubes-release-4.1-5.fc32.noarch                                                                                 2/2 
> 
> Upgraded:
>   qubes-release-4.2-0.3.fc32.noarch                                                                                                      
> 
> Complete!
> WARNING: /etc/yum.repos.d/qubes-dom0.repo is not updated to R4.2 version
> INFO: Found R4.2 repositories in /etc/yum.repos.d/qubes-dom0.repo.rpmnew
> ---> Replace qubes-dom0.repo with qubes-dom0.repo.rpmnew? [y/N] y
> INFO: Old /etc/yum.repos.d/qubes-dom0.repo saved with .bak extension

Is this correct?  It does not seem to block the upgrade process anymore, even though the error still pops up at one point.  I will continue through the upgrade process if this is OK.

**Comment by marmarek** [comment]
Yes, looks correct.

**Comment by moonlitOrca** [comment]
OK, I have just run stage 3 and stage 4.

In stage 3, I did end up with an error but I think it's a normal one that I frequently get.  It mentioned the many packages that it upgraded, newly installed, 2 that it downgraded, a bunch of kernel images installed, then it mentioned it failed to install a few kernel images.  It said `transaction failed` . I don't think this is related to the bug here because it happens frequently in my normal dom0 updates, and so I assume that the transaction failed just means there was an error with those and everything completed successfully otherwise.  Please let me know if that is not true :-)

Therefore, I rebooted and started stage 4.  I did notice on my reboot that my Plasma desktop is not working correctly anymore after the upgrade, so I will look into that, but again that's probably off-topic for this bug.  I loaded into XFCE instead and ran the stage 4 upgrade: `qubes-dist-upgrade --template-standalone-upgrade`.  As expected, the windows update was an error, but the script allowed me to continue.  I did get this same error with the repomd.xml however in both my debian-12 and my fedora-38 templates.  It seems to be specific to the securitytesting repositories in both:

> Upgrading debian-12...
> + [[ 0 -ne 0 ]]
> + '[' -e /etc/fedora-release ']'
> + '[' -e /etc/debian_version ']'
> ++ awk -F. '{print $1}' /etc/debian_version
> + releasever=12
> + '[' 12 -lt 11 ']'
> + cp /etc/apt/sources.list.d/qubes-r4.list /etc/apt/sources.list.d/qubes-r4.list.bak
> + sed -i s/r4.1/r4.2/g /etc/apt/sources.list.d/qubes-r4.list
> + sed -i 's/arch=amd64/arch=amd64\ signed-by=\/usr\/share\/keyrings\/qubes-archive-keyring-4.2.gpg/g' /etc/apt/sources.list.d/qubes-r4.list
> + export DEBIAN_FRONTEND=noninteractive
> + DEBIAN_FRONTEND=noninteractive
> + apt-get clean
> + apt-get update -o Dpkg::Options::=--force-confdef
> Hit:1 https://updates.signal.org/desktop/apt xenial InRelease
> Get:2 https://deb.qubes-os.org/r4.2/vm bookworm InRelease [2,513 B]
> Hit:3 https://deb.debian.org/debian bookworm InRelease
> Hit:4 https://deb.debian.org/debian-security bookworm-security InRelease
> Get:5 https://deb.qubes-os.org/r4.2/vm bookworm-testing InRelease [2,542 B]
> Hit:6 https://deb.debian.org/debian bookworm-backports InRelease
> Ign:7 https://deb.qubes-os.org/r4.2/vm bookworm-securitytesting InRelease
> Get:8 https://deb.qubes-os.org/r4.2/vm bookworm/main amd64 Packages [27.3 kB]
> Get:9 https://deb.qubes-os.org/r4.2/vm bookworm-testing/main amd64 Packages [27.6 kB]
> Err:10 https://deb.qubes-os.org/r4.2/vm bookworm-securitytesting Release
>   404  Not Found [IP: 127.0.0.1 8082]
> Reading package lists...
> E: The repository 'https://deb.qubes-os.org/r4.2/vm bookworm-securitytesting Release' does not have a Release file.
> ERROR: A general error occurred while upgrading debian-12 (exit code 100).
> -> Continue? [y/N] y
> ----> Upgrading fedora-38...
> + [[ 0 -ne 0 ]]
> + '[' -e /etc/fedora-release ']'
> ++ awk '{print $3}' /etc/fedora-release
> + releasever=38
> + '[' 38 -lt 37 ']'
> + cp /etc/yum.repos.d/qubes-r4.repo /etc/yum.repos.d/qubes-r4.repo.bak
> + sed -i s/r4.1/r4.2/g /etc/yum.repos.d/qubes-r4.repo
> + sed -i s/4-primary/4.2-primary/g /etc/yum.repos.d/qubes-r4.repo
> + dnf clean all
> 125 files removed
> + dnf distro-sync -y --best --allowerasing
> Fedora 38 - x86_64                              3.2 MB/s |  83 MB     00:25    
> Fedora 38 openh264 (From Cisco) - x86_64        991  B/s | 2.5 kB     00:02    
> Fedora 38 - x86_64 - Updates                    733 kB/s |  31 MB     00:43    
> Qubes OS Repository for VM (updates)            557  B/s | 833  B     00:01    
> Qubes OS Repository for VM (updates)            2.3 MB/s | 2.4 kB     00:00    
> Importing GPG key 0x8E34D89F:
>  Userid     : "Qubes OS Release 4.2 Signing Key"
>  Fingerprint: 9C88 4DF3 F810 64A5 69A4 A9FA E022 E58F 8E34 D89F
>  From       : /etc/pki/rpm-gpg/RPM-GPG-KEY-qubes-4.2-primary
> Qubes OS Repository for VM (updates)             78 kB/s | 185 kB     00:02    
> Qubes OS Repository for VM (updates-testing)    716  B/s | 833  B     00:01    
> Qubes OS Repository for VM (updates-testing)    2.3 MB/s | 2.4 kB     00:00    
> Importing GPG key 0x8E34D89F:
>  Userid     : "Qubes OS Release 4.2 Signing Key"
>  Fingerprint: 9C88 4DF3 F810 64A5 69A4 A9FA E022 E58F 8E34 D89F
>  From       : /etc/pki/rpm-gpg/RPM-GPG-KEY-qubes-4.2-primary
> Qubes OS Repository for VM (updates-testing)    129 kB/s | 341 kB     00:02    
> Qubes OS Repository for VM (security-testing)   146  B/s | 153  B     00:01    
> Errors during downloading metadata for repository 'qubes-vm-r4.2-security-testing':
>   - Status code: 404 for https://yum.qubes-os.org/r4.2/security-testing/vm/fc38/repodata/repomd.xml (IP: 127.0.0.1)
> Error: Failed to download metadata for repo 'qubes-vm-r4.2-security-testing': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
> + exit 3
> ERROR: An error occurred during upgrade transaction for fedora-38.
> -> Continue? [y/N]

I will try to run stage 5 now, but just wanted to report the repo error.

**Comment by moonlitOrca** [comment]
Stage 5 completed.  Again some errors, but nothing related to the repositories.  It ran through a bunch of appmenu changes and then:

> ---> (STAGE 5) Cleaning up salt
> Error on ext_pillar interface qvm_prefs is expected
> local:
>     True
> [CRITICAL] Specified ext_pillar interface qvm_prefs is unavailable
> local:
>     ----------
>     beacons:
>     clouds:
>     engines:
>     executors:
>     grains:
>         - grains.boot_mode
>         - grains.pci_devs
>         - grains.redefined_dom0_grains
>         - grains.whonix
>     log_handlers:
>     matchers:
>     modules:
>         - modules.debug
>         - modules.ext_module_qvm
>         - modules.module_utils
>         - modules.qubes
>         - modules.qubes_dom0_update
>         - modules.topd
>     output:
>     pillar:
>         - pillar.qvm_prefs
>     proxymodules:
>     renderers:
>     returners:
>     sdb:
>     serializers:
>     states:
>         - states.debug
>         - states.ext_state_qvm
>         - states.status
>     thorium:
>     utils:
>         - utils.__init__
>         - utils.fileinfo
>         - utils.matcher
>         - utils.nulltype
>         - utils.pathinfo
>         - utils.pathutils
>         - utils.qubes_utils
>         - utils.toputils
> ---> (STAGE 5) Adjusting default kernel
>   Logical volume "Qubes41UpgradeBackup" successfully removed
>  

So I do not know if any of those are related to the original bug, but it appears most of the upgrade has worked?  Is there anything else that you need me to test or check on?

**Comment by marmarek** [comment]
No, I think it all worked this time :)

The messages about security-testing repos in templates is because there were no security fixes for them in R4.2 yet. But still, there should be empty repository, not 404.

**Comment by moonlitOrca** [comment]
That's great to hear.  I want to thank you very much for the incredible work you do, and for taking the time to help out.  You are appreciated greatly. :)

**Comment by moonlitOrca** [comment]
It's worth noting here that, since the upgrade to 4.2, my Fedora 38 template will fail to update every time and give me a very similar error message:

> Updating fedora-38
> 
> Error: Failed to download metadata for repo 'qubes-vm-r4.2-security-testing': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
> 
> Error: Failed to download metadata for repo 'qubes-vm-r4.2-security-testing': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
> 

I apologize if this is not the same error.  It appears related to me so I figured I'd report it in the topic.

**Comment by marmarek** [comment]
Should be better now.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab

**Comment by moonlitOrca** [comment]
Awesome, That fixed it!  Thanks.  Your change seems to have affected the debian-11 and debian-12 templates too.  Since upgrading to 4.2, they were failing to update every time for me but with the error "no release file".  Now they are trying to update, but hanging at about 91% (this is using the graphical tool so I am not sure what the error is)

**Comment by no-usernames-left** [comment]
> Should be better now.

@marmarek What was the root cause of the issue each time your intervention improved things?

**Comment by marmarek** [comment]
Empty repositories were not created in place, so I created them.
