### ISSUE TITLE
Qubes-Whonix 16 for Qubes R4.1

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#6890]
Maintainer for Qubes-Whonix here.

Qubes-Whonix `16` for Qubes `R4.1` is not yet supported by me.

(And Qubes-Whonix `15` won't ever be since Qubes-Whonix `16` release for Qubes `R4.0` is very close. -> https://github.com/QubesOS/qubes-issues/issues/6891)

Some discussion here:

* https://github.com/QubesOS/qubes-issues/issues/6597#issuecomment-839799243
* https://github.com/QubesOS/qubes-issues/issues/6597#issuecomment-839923299

No rush, however please let me know when a Qubes `R4.1` signed ISO installer release (alpha, beta, stable) become available or any estimated release dates. Once that's done I need to sort out my personal Qubes hardware support issues.

I might update this post later. This ticket can be a placeholder, a general ticket usable as link to explain the current status to users, used for discussion...

Related:

* #6597
* #6891

**Comment by adrelanos** [comment]
Occasionally builds of Qubes-Whonix `16` are started by @marmarek such as recently here:
https://github.com/QubesOS/updates-status/issues/566#issuecomment-917398880

If things go well, these then show up in Qubes updates-status repository here:
https://github.com/QubesOS/updates-status/issues

Recently built Qubes-Whonix `16` templates for Qubes `R4.1`:

* https://github.com/QubesOS/updates-status/issues/2622
* https://github.com/QubesOS/updates-status/issues/2624

**Comment by marmarek** [comment]
I'll run them through openQA, it will do the very basic tests for us.

**Comment by adrelanos** [comment]
I finally managed to find time to download Qubes R4.1. Hopefully installing, testing and then porting Qubes-Whonix 16 soon.

Please let me know if Qubes R4.1 stable release approaches, any timelines if any, in case this turns into a release critical blocker.

**Comment by jonas-w** [comment]
> I finally managed to find time to download Qubes R4.1. Hopefully installing, testing and then porting Qubes-Whonix 16 soon.
> 
> Please let me know if Qubes R4.1 stable release approaches, any timelines if any, in case this turns into a release critical blocker.

Hey adrelanos, anything new on porting whonix 16?

**Comment by DemiMarie** [comment]
It is already finished, and in the official repositories :smile:.  Closing.

**Comment by Tie-fighter** [comment]
I hope you don't mind my asking, but is there a tutorial somewhere?
https://www.whonix.org/wiki/Qubes/Install still shows it as unsupported.

**Comment by DemiMarie** [comment]
> I hope you don't mind my asking, but is there a tutorial somewhere? https://www.whonix.org/wiki/Qubes/Install still shows it as unsupported.

Please report this as a Whonix bug.

**Comment by adrelanos** [comment]
This ticket suffices. No news.

> It is already finished, and in the repositories smile. Closing.

I am happy to hear if the Qubes team can support Qubes-Whonix 16 for Qubes R4.1 independently. Glad to receive any help available.

**Comment by adrelanos** [comment]
Note to self:

* https://github.com/QubesOS/updates-status/issues/2795
* https://github.com/QubesOS/updates-status/issues/2797

**Comment by adrelanos** [comment]
https://github.com/QubesOS/qubes-issues/issues/7250

**Comment by adrelanos** [comment]
This might remain a known issue for a while:

* https://github.com/QubesOS/qubes-issues/issues/7013

Impact assessment:

* https://github.com/QubesOS/qubes-issues/issues/7013#issuecomment-1035464345

**Comment by andrewdavidwong** [comment]
I'm a bit confused as to what's going on in this issue now. It looks like @DemiMarie previously closed this as resolved, but recent comments from @adrelanos suggest this might not be the case?

**Comment by DemiMarie** [comment]
> I'm a bit confused as to what's going on in this issue now. It looks like @DemiMarie previously closed this as resolved, but recent comments from @adrelanos suggest this might not be the case?

I viewed this as a tracking issue for Qubes-Whonix 16 in the repos, which has already been done.  #7013 is a UX bug that will be fixed with a qrexec policy change.

**Comment by adrelanos** [comment]
It was released without me signaling readiness, blessing Qubes-Whonix 16 for Qubes R4.1 stable. I had huge issues getting Qubes R4.1 to run due to hardware compatibility issues on one computer and non-functional (for me) USB installed Qubes on another computer. And didn't know when Qubes R4.1 would be released. Hence, wrote:

> Please let me know if Qubes R4.1 stable release approaches, any timelines if any, in case this turns into a release critical blocker.

Related:

* https://github.com/QubesOS/qubes-issues/issues/6515

Usually the Qubes-Whonix 16 release is coordinated between Qubes and Whonix, Qubes-Whonix blessed stable after my approval. Example process:

* https://github.com/QubesOS/qubes-issues/issues/6891

This wasn't done this time. Hence, wrote:

> I am happy to hear if the Qubes team can support Qubes-Whonix 16 for Qubes R4.1 independently. Glad to receive any help available.

So from my perspective it's still open. Still working to get done and check all the items similar to https://github.com/QubesOS/qubes-issues/issues/6891. But since Qubes-Whonix 16 for Qubes R4.1 is already available on Qubes R4.1 installer and community stable repository, that might seem a bit strange anyhow.

Related:

* https://github.com/QubesOS/qubes-issues/issues/7160

**Comment by andrewdavidwong** [comment]
@DemiMarie @marmarek: Why was Whonix 16 migrated to stable without Patrick's approval? Was there a miscommunication or misunderstanding that we can identify and learn from to ensure it doesn't happen again next time? Perhaps there's a process improvement safeguard we can implement here.

**Comment by marmarek** [comment]
It's Patrick who migrated it to stable at https://github.com/QubesOS/updates-status/issues/2797#issuecomment-1030913638

What was missing indeed, is clearer communication about R4.1 release schedule.

**Comment by DemiMarie** [comment]
> > It's Patrick who migrated it to stable at [QubesOS/updates-status#2797 (comment)](https://github.com/QubesOS/updates-status/issues/2797#issuecomment-1030913638)
> 
> But that was only five days ago, _after_ the 4.1 stable release, whereas @DemiMarie posted [#6890 (comment)](https://github.com/QubesOS/qubes-issues/issues/6890#issuecomment-996170417) nearly two months ago.

If I had to guess, this was because I have testing repositories enabled, and I closed this as soon as I had the new template installed.

**Comment by adrelanos** [comment]
> It's Patrick who migrated it to stable at [QubesOS/updates-status#2797 (comment)](https://github.com/QubesOS/updates-status/issues/2797#issuecomment-1030913638)

There were already Qubes-Whonix templates in Qubes R4.1 community stable repository before I did that.

I issued the command to migrate a newer template version from Qubes communty testing to Qubes community stable. The same version included in Qubes R4.1 installer. Reference:

* https://github.com/QubesOS/updates-status/issues/2795
* https://github.com/QubesOS/updates-status/issues/2797

I did that kinda as "damage control" due to lack of better term. Still catching up. The migrated template version is for sure better than the earlier one. And I didn't want users who re-install from Qubes community stable repository to get a template older than the one from Qubes R4.1 repository and then report bugs which have already been fixed. That would have been more confusing for everyone.

On the template migration that I did, I should have have posted what I said just now to avoid confusion.

**Comment by andrewdavidwong** [comment]
Good postmortem so far. We're learning valuable lessons. However, it sounds like we still haven't gotten to the bottom of how the Whonix 16 templates made it into the 4.1 community _stable_ repo in the first place.

**Comment by adrelanos** [comment]
> Good postmortem so far. We're learning valuable lessons.

Yes. :)

> However, it sounds like we still haven't gotten to the bottom of how the Whonix 16 templates made it into the 4.1 community _stable_ repo in the first place.

* https://github.com/QubesOS/updates-status/issues/2622#issuecomment-932657866
* https://github.com/QubesOS/updates-status/issues/2624#issuecomment-932657868

**Comment by andrewdavidwong** [comment]
> > However, it sounds like we still haven't gotten to the bottom of how the Whonix 16 templates made it into the 4.1 community _stable_ repo in the first place.
> 
> 
> 
> * https://github.com/QubesOS/updates-status/issues/2622#issuecomment-932657866
> 
> * https://github.com/QubesOS/updates-status/issues/2624#issuecomment-932657868
> 

I see, mechanically, what occurred, but I'm curious to understand the context that informed these actions. @marmarek, from your perspective, what was the situation and rationale at the time when these comments were posted?

**Comment by adrelanos** [comment]
* https://github.com/QubesOS/qubes-issues/issues/7265

**Comment by marmarek** [comment]
It looks to be the time just before R4.1.0-rc1 and at that time I usually move already tested packages/templates to stable repo, but honestly I don't remember why I did that for Whonix templates too - that shouldn't happen without confirmation from @adrelanos.

**Comment by adrelanos** [comment]
* :heavy_check_mark: ([Non-Qubes-Whonix 16 has been released.](https://forums.whonix.org/t/whonix-16-has-been-released-debian-11-bullseye-based-for-virtualbox-major-release/12297))
* :no_entry: [Release Upgrade Whonix 15 to Whonix 16](https://www.whonix.org/wiki/Release_Upgrade_Whonix_15_to_Whonix_16) is [unsupported](https://www.whonix.org/wiki/Unsupported) because [Whonix 15 has been already deprecated at time of writing](https://forums.whonix.org/t/whonix-15-end-of-security-support-and-deprecation-notice-all-users-should-move-to-whonix-16/12473).
* :heavy_check_mark: Qubes-Whonix 16 images built, tested by me.
  * :heavy_check_mark: https://github.com/QubesOS/updates-status/issues/2795
  * :heavy_check_mark: https://github.com/QubesOS/updates-status/issues/2797
* :heavy_check_mark: [Qubes-Whonix installation documentation update](https://www.whonix.org/wiki/Qubes/Install).
* :white_circle: Qubes-Whonix 16 release announcement at whonix.org.
* :white_circle: Qubes-Whonix 16 release announcement at qubes-os.org.

**Comment by adrelanos** [comment]
* :heavy_check_mark: [Qubes-Whonix 16 for Qubes R4.1 release announcement at whonix.org](https://forums.whonix.org/t/qubes-whonix-16-for-qubes-r4-1-is-available-debian-11-bullseye-based-major-release/13349).

> * :white_circle: Qubes-Whonix for Qubes R4.**0** deprecation notice at whonix.org.

Pending, coming soon.

> * :white_circle: Qubes-Whonix 16 for Qubes R4.1 release announcement at qubes-os.org.

Should this be done?

> * :white_circle: Qubes-Whonix for Qubes R4.**0** deprecation notice at qubes-os.org.

This?

**Comment by andrewdavidwong** [comment]
Thanks, @adrelanos!

> > * white_circle Qubes-Whonix 16 for Qubes R4.1 release announcement at qubes-os.org.
> 
> Should this be done?
> 

In the past, we have always announced each new template release only **once**. For example, when the Whonix 15 template first came out, when the Fedora 34 template first came out, when the Debian 11 template first came out, and so on. We already [announced when Whonix 16 template first came out](https://www.qubes-os.org/news/2021/09/30/whonix-16-template-available/). That announcement wasn't specific to any particular Qubes release (e.g., 4.0 or 4.1), and Whonix 16 is [already listed](https://www.qubes-os.org/doc/supported-releases/#templates) as (now the only) supported Whonix release for Qubes 4.0 and Qubes 4.1.

When we [announced Qubes 4.1 stable](https://www.qubes-os.org/news/2022/02/04/qubes-4-1-0/), we already included the list of updated templates it includes (Fedora 34, Debian 11, and Whonix 16). We didn't have separate announcements for Fedora 34 and Debian 11 being available in 4.1 (as opposed to 4.0), so it would be weird and unexpected to do that for Whonix 16.

The only reason to have *another* announcement about Whonix 16 being released on Qubes 4.1 is due to this weird situation where Whonix 16 made it into 4.1 stable before you were ready (or, rather, Qubes 4.1 stable was released with Whonix 16 inside of it before you were ready). However, explaining this situation (and that it has now been resolved) might be unnecessarily confusing for users, and it's not actionable for them anyway, since there is nothing for them to do except continue on as they already were (including keeping up with updates).

So, while I'm open to making another announcement if you (or anyone else) feels that we should have one, I would first like to understand the rationale for why there should be another announcement in this situation.

> > * white_circle Qubes-Whonix for Qubes R4.**0** deprecation notice at qubes-os.org.
> 
> This?

Already included in the 4.1 announcement [in this section](https://www.qubes-os.org/news/2022/02/04/qubes-4-1-0/#support-for-older-releases). I plan to do another announcement on 2022-03-20 when the deprecation occurs. (Thanks for extending the deadline, btw!)

**Comment by adrelanos** [comment]
Alright, great! Then from my perspective this is resolved. Closing.

I hope you don't mind for me copy/pasting the template which seems very well written which I was I think:

If anyone believes this issue is not yet resolved, or if anyone is still affected by this issue, please leave a comment, and we'll be happy to reopen it. Thank you.

**Comment by andrewdavidwong** [comment]
> It looks to be the time just before R4.1.0-rc1 and at that time I usually move already tested packages/templates to stable repo, but honestly I don't remember why I did that for Whonix templates too - that shouldn't happen without confirmation from @adrelanos.

In the future, perhaps it would make sense to require a signed comment from @adrelanos (either in addition or instead)? This way, there would be no risk of miscommunication or misunderstanding regarding whether both sides are ready to proceed.

Also, if anyone ever sees that something has happened that shouldn't have happened, please don't be afraid to speak up about it right away. That way we can reopen any relevant issue, and everyone will be informed of what happened (and can take appropriate action sooner rather than later).

**Comment by andrewdavidwong** [comment]
> I still have a question sweat_smile Who's responsibility is it to write tutorials on how to upgrade Qubes templates?

[The issue tracker is not the right place to ask questions.](https://www.qubes-os.org/doc/issue-tracking/#do-not-submit-questions)

**Comment by Tie-fighter** [comment]
Nevermind.

**Comment by adrelanos** [comment]
> @marmarek wrote:
> 
> > It looks to be the time just before R4.1.0-rc1 and at that time I usually move already tested packages/templates to stable repo, but honestly I don't remember why I did that for Whonix templates too - that shouldn't happen without confirmation from @adrelanos.
> 
> In the future, perhaps it would make sense to require a signed comment from @adrelanos (either in addition or instead)? This way, there would be no risk of miscommunication or misunderstanding regarding whether both sides are ready to proceed.

Not sure. Shouldn't be too strict. In the spirit of Open Source. Should I be unable to do it for any unexpected reason (hit by a bus), I would be happy for anyone else maintaining/contributing builds. But shouldn't matter much even if implemented since @marmarek  could always easily revert/change authorized keys.

As said in https://github.com/QubesOS/qubes-issues/issues/6890#issuecomment-1004086739

me:
> I am happy to hear if the Qubes team can support Qubes-Whonix 16 for Qubes R4.1 independently. Glad to receive any help available.

> Occasionally builds of Qubes-Whonix `16` are started by @marmarek such as recently here: [QubesOS/updates-status#566 (comment)](https://github.com/QubesOS/updates-status/issues/566#issuecomment-917398880)

> Recently built Qubes-Whonix `16` templates for Qubes `R4.1`:

@marmarek 
> I'll run them through openQA, it will do the very basic tests for us.

Also super helpful.
