### ISSUE TITLE
Qubes-Whonix 16 for Qubes R4.0

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#6891]
Status:

* :heavy_check_mark: ([Non-Qubes-Whonix 16 has been released.](https://forums.whonix.org/t/whonix-16-has-been-released-debian-11-bullseye-based-for-virtualbox-major-release/12297))
* :heavy_check_mark: [Release Upgrade Whonix 15 to Whonix 16](https://www.whonix.org/wiki/Release_Upgrade_Whonix_15_to_Whonix_16) supported.
* :heavy_check_mark: Qubes-Whonix 16 images built, tested by me.
* :heavy_check_mark: [Qubes-Whonix installation documentation update](https://www.whonix.org/wiki/Qubes/Install).
* :heavy_check_mark: [Qubes-Whonix 16 release announcement at whonix.org.](https://forums.whonix.org/t/qubes-whonix-16-has-been-released-debian-11-bullseye-based-major-release/12465)
* Qubes-Whonix 16 release announcement at qubes-os.org still pending. (Similar to https://github.com/QubesOS/qubes-issues/issues/5128)

Qubes-Whonix 16 images details:

* ~~Waiting for https://github.com/QubesOS/qubes-mgmt-salt-dom0-virtual-machines/pull/40 to be merged at Qubes.~~
  * ~~Edit was made using github web interface. I hope that's OK for minor edits?~~
* ~~Images built:~~
  * ~~https://github.com/QubesOS/updates-status/issues/2613~~ ~~(contains some discussion)~~
  * ~~https://github.com/QubesOS/updates-status/issues/2614~~

Any further Qubes salt changes required or something else?

**Comment by DemiMarie** [comment]
> * Waiting for [Whonix 16 qubes-mgmt-salt-dom0-virtual-machines#40](https://github.com/QubesOS/qubes-mgmt-salt-dom0-virtual-machines/pull/40) to be merged at Qubes.
>   
>   * Edit was made using github web interface. I hope that's OK for minor edits?

That will fail the code signing check I believe.

**Comment by adrelanos** [comment]
Demi Marie Obenour:
>> * Waiting for [Whonix 16 qubes-mgmt-salt-dom0-virtual-machines#40](https://github.com/QubesOS/qubes-mgmt-salt-dom0-virtual-machines/pull/40) to be merged at Qubes.
>>   
>>   * Edit was made using github web interface. I hope that's OK for minor edits?
> 
> That will fail the code signing check I believe.
> 


Could have been. Was also wondering about that. Very glad that
minor/trivial changes are still being accepted through github web interface.

**Comment by adrelanos** [comment]
Known issue: Default Qubes appmenu is empty. - Maybe fixed in next build.

**Comment by airelemental** [comment]
It looks like sys-whonix based on whonix-gw-16 can't be used as dom0 updatevm (DNF not configured to get DNS over tor?):

```
$ qubes-prefs updatevm sys-whonix-16
$ sudo qubes-dom0-update
Using sys-whonix-16 as UpdateVM to download updates for Dom0; this may take some time...
Unable to detect release version (use '--releasever' to specify release version)
Fedora 25 - x86_64 - Updates                    0.0  B/s |   0  B     00:00    
Errors during downloading metadata for repository 'updates':
  - Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f25&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]
Error: Failed to download metadata for repo 'updates': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f25&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]
```

**Comment by andrewdavidwong** [comment]
I was just told in https://github.com/QubesOS/qubes-issues/issues/1778#issuecomment-921921033 that Qubes-Whonix 16 is already in the stable repo, which is quite surprising. The link about the staged rollout doesn't provide any details about how exactly the staged rollout for Qubes-Whonix 16 works, and it's unclear to me at what point in the staged rollout we should publish Qubes announcements for these new templates. I guess you should just let me know when, @adrelanos.

**Comment by adrelanos** [comment]
> I was just told in [#1778 (comment)](https://github.com/QubesOS/qubes-issues/issues/1778#issuecomment-921921033) that Qubes-Whonix 16 is already in the stable repo, which is quite surprising, as I saw no indication of that here. The link about the staged rollout doesn't provide any details about how exactly the staged rollout for Qubes-Whonix 16 works,

Right. Generally plan:

stage 1:
Templates are added to stable community repository and documentation https://www.whonix.org/wiki/Qubes/Install is updated.

stage 2:
Release announcements.

stage 3:
Deprecation notice. - https://forums.whonix.org/t/one-time-popup-notification-of-whonix-15-deprecation-once-whonix-16-was-released/11720

Specifically this time:

Waiting for some fixes to be tested (default Qubes appmenu) and migrating to stable before starting stage 2. Current stable templates probably soon the be replaced with these ones:

* https://github.com/QubesOS/updates-status/issues/2625
* https://github.com/QubesOS/updates-status/issues/2626

> and it's unclear to me at what point in the staged rollout we should publish Qubes announcements for these new templates. I guess you should just let me know when, @adrelanos.

Yes, thank you! :)

**Comment by adrelanos** [comment]
> It looks like sys-whonix based on whonix-gw-16 doesn't work as dom0 updatevm (DNF not configured to get DNS over tor?):

Created https://github.com/QubesOS/qubes-issues/issues/6913 for it.

**Comment by adrelanos** [comment]
I would like to suggest moving all of these...

* https://github.com/QubesOS/updates-status/issues/2631
* https://github.com/QubesOS/updates-status/issues/2632
* https://github.com/QubesOS/updates-status/issues/2620#issuecomment-923442326

to stable. @marmarek 

No big changes were introduced. Just small bugfixes. Testing completed. (Could also wait the minimum time but I doubt someone else would test and report and blocking bugs before that.)

Once that's done, I'll write an announcement in the usual Whonix place.

**Comment by adrelanos** [comment]
[`Qubes-Whonix 16 has been Released! (Debian 11 bullseye based) - Major Release`](https://forums.whonix.org/t/qubes-whonix-16-has-been-released-debian-11-bullseye-based-major-release/12465)

Next: I'd suggest to wait a few days before announcing on Qubes news. But if there was a draft, I'd of course have a look.

**Comment by andrewdavidwong** [comment]
> [`Qubes-Whonix 16 has been Released! (Debian 11 bullseye based) - Major Release`](https://forums.whonix.org/t/qubes-whonix-16-has-been-released-debian-11-bullseye-based-major-release/12465)
> 
> Next: I'd suggest to wait a few days before announcing on Qubes news.

May I ask why? Users have only one month to upgrade, and each day we wait is one fewer day they have.

> But if there was a draft, I'd of course have a look.

Opened https://github.com/QubesOS/qubes-posts/pull/84. Please review when you get a chance.

**Comment by adrelanos** [comment]
> > [`Qubes-Whonix 16 has been Released! (Debian 11 bullseye based) - Major Release`](https://forums.whonix.org/t/qubes-whonix-16-has-been-released-debian-11-bullseye-based-major-release/12465)
> > Next: I'd suggest to wait a few days before announcing on Qubes news.
> 
> May I ask why?

Staged rollout.

> Users have only one month to upgrade, and each day we wait is one fewer day they have.

Right, well. No problem. I wouldn't start the counter until "fully released". The spirit isn't to be overly strict about it.

Arguably (?) according to https://www.whonix.org/wiki/About#Support_Schedule we previously said we'd post a deprecation notice at https://forums.whonix.org/c/news which might be a good idea for clarification anyhow.

The deadline doesn't mean:

* https://www.whonix.org/wiki/Qubes/Install becomes impossible (obviously not)
* release upgrade instantly becomes impossible.

Just that the more time passes, release upgrades can become increasingly difficult that it becomes infeasible to troubleshoot and that questions "how do I x,y, z on deprecated version x" become more confusing for other readers and harder to answer since fewer and fewer people are using it.

> > But if there was a draft, I'd of course have a look.
> 
> Opened [QubesOS/qubes-posts#84](https://github.com/QubesOS/qubes-posts/pull/84). Please review when you get a chance.

Looks perfect!

**Comment by andrewdavidwong** [comment]
> > > [`Qubes-Whonix 16 has been Released! (Debian 11 bullseye based) - Major Release`](https://forums.whonix.org/t/qubes-whonix-16-has-been-released-debian-11-bullseye-based-major-release/12465)
> > > Next: I'd suggest to wait a few days before announcing on Qubes news.
> > 
> > 
> > May I ask why?
> 
> Staged rollout.
> 

Ok, but some users become a bit confused when they see an announcement from the Whonix Project that Whonix 16 has been released with no similar announcement from the Qubes OS Project. Example (see replies):

https://forum.qubes-os.org/t/qubes-whonix-16-has-been-released-debian-11-bullseye-based-major-release/6647

> > Users have only one month to upgrade, and each day we wait is one fewer day they have.
> 
> Right, well. No problem. I wouldn't start the counter until "fully released". The spirit isn't to be overly strict about it.
> 

Ok, that's good. It's unclear to me what the official release date is with a staged rollout.

> Arguably (?) according to https://www.whonix.org/wiki/About#Support_Schedule we previously said we'd post a deprecation notice at https://forums.whonix.org/c/news which might be a good idea for clarification anyhow.
> 
> The deadline doesn't mean:
> 
> * https://www.whonix.org/wiki/Qubes/Install becomes impossible (obviously not)
> * release upgrade instantly becomes impossible.
> 

No, those are not the concerns. Rather, the concern is that there are no more security patches for EOL releases, so users definitely want to upgrade from Whonix 15 before it reaches EOL. If they're too slow or too late, they may be vulnerable to unpatched security bugs in their Whonix qubes.

> Just that the more time passes, release upgrades can become increasingly difficult that it becomes infeasible to troubleshoot and that questions "how do I x,y, z on deprecated version x" become more confusing for other readers and harder to answer since fewer and fewer people are using it.
> 
> > > But if there was a draft, I'd of course have a look.
> > 
> > 
> > Opened [QubesOS/qubes-posts#84](https://github.com/QubesOS/qubes-posts/pull/84). Please review when you get a chance.
> 
> Looks perfect!

Thanks! Since it's been a couple days, I'll go ahead and publish it now.

**Comment by andrewdavidwong** [comment]
@adrelanos, could you let me know when Whonix 15 has officially reached EOL so that I can make another announcement and update https://www.qubes-os.org/doc/supported-releases/#templates?

**Comment by adrelanos** [comment]
> > > > [`Qubes-Whonix 16 has been Released! (Debian 11 bullseye based) - Major Release`](https://forums.whonix.org/t/qubes-whonix-16-has-been-released-debian-11-bullseye-based-major-release/12465)
> > > > Next: I'd suggest to wait a few days before announcing on Qubes news.
> > > 
> > > 
> > > May I ask why?
> > 
> > 
> > Staged rollout.
> 
> Ok, but some users become a bit confused when they see an announcement from the Whonix Project that Whonix 16 has been released with no similar announcement from the Qubes OS Project. Example (see replies):
> 
> https://forum.qubes-os.org/t/qubes-whonix-16-has-been-released-debian-11-bullseye-based-major-release/6647

I see.

Well, since this release seems to not cause many upgrade troubles anyhow...

> > > Users have only one month to upgrade, and each day we wait is one fewer day they have.
> > 
> > 
> > Right, well. No problem. I wouldn't start the counter until "fully released". The spirit isn't to be overly strict about it.
> 
> Ok, that's good. It's unclear to me what the official release date is with a staged rollout.

Posted deprecation notice just now.

https://forums.whonix.org/t/whonix-15-deprecation-notice-all-users-should-upgrade-to-whonix-16/12473

> > Arguably (?) according to https://www.whonix.org/wiki/About#Support_Schedule we previously said we'd post a deprecation notice at https://forums.whonix.org/c/news which might be a good idea for clarification anyhow.
> > The deadline doesn't mean:
> > 
> > * https://www.whonix.org/wiki/Qubes/Install becomes impossible (obviously not)
> > * release upgrade instantly becomes impossible.
> 
> No, those are not the concerns. Rather, the concern is that there are no more security patches for EOL releases, so users definitely want to upgrade from Whonix 15 before it reaches EOL. If they're too slow or too late, they may be vulnerable to unpatched security bugs in their Whonix qubes.

I see. Seems like there are many ways to define "supported". Will keep this in mind.

> @adrelanos, could you let me know when Whonix 15 has officially reached EOL so that I can make another announcement and update https://www.qubes-os.org/doc/supported-releases/#templates?

Does https://forums.whonix.org/t/whonix-15-deprecation-notice-all-users-should-upgrade-to-whonix-16/12473 clarify it?

I see https://www.qubes-os.org/news/2021/09/30/whonix-16-template-available/ was published, thank you!

**Comment by andrewdavidwong** [comment]
> > @adrelanos, could you let me know when Whonix 15 has officially reached EOL so that I can make another announcement and update https://www.qubes-os.org/doc/supported-releases/#templates?
> 
> Does https://forums.whonix.org/t/whonix-15-deprecation-notice-all-users-should-upgrade-to-whonix-16/12473 clarify it?

Yes, thanks. I'll set a reminder for myself to perform the aforementioned actions on 2021-11-14.
