### ISSUE TITLE
Empty "Networking" utility applet installed as part of Fedora, on dom0

### ISSUE THREAD

**Issue by ninavizz** [QubesOS/qubes-issues#6894]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
4.0 and 4.1

### Brief summary
In the App Menu under "System Tools," there is an applet called "Network Connections." 

This applet is an artifact of Fedora, and within the Qubes-o-sphere does nothing. 

For new users this will be confusing. For existing users, it just takes up valuable disk space that should not have useless software on it.

### Steps to reproduce

1. Boot machine
2. Open AppMenu
3. Open System Tools
4. "Network Connections" is in the middle of the menu
5. Upon opening this applet, it shows nothing

### Expected behavior
In Step 5 above, upon opening the applet it would show me that sys-net is connected to my internal networking hardware, and that it pulls-in my internet connection. It would also show the relationship to sys-firewall, and how the two work together (insert a lot of handwaving) to keep my computer safe.

### Actual behavior
The above summarizes a user expectation for a custom Qubes applet. The actual behavior, is of a single-environment/Fedora applet. So, it shows nothing.

**Comment by EncryptedGiraffe** [comment]
I'm on 4.1 and don't see this applet in the App Menu.

**Comment by ninavizz** [comment]
@EncryptedGiraffe Did you look in "Qubes Tools" in your 4.1 menu?

**Comment by EncryptedGiraffe** [comment]
No. It's not under "Qubes Tools" or "System Tools" for me. As far as I know, my system is fully updated to the testing repos.

**Comment by ninavizz** [comment]
Per @DemiMarie there is a chance this could be an artifact of one of my Fedora templates from SecureDrop's Workstation install. I'll follow-up with @eloquence next week.
