### ISSUE TITLE
Confusing text on sys-net & Whonix "Firewall Rules" tab in Qube Settings

### ISSUE THREAD

**Issue by ninavizz** [QubesOS/qubes-issues#6895]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
4.0, 4.1

### Brief summary
Shown in the below image, is my Qube Settings window for sys-net.

- The red text in combination with the text of the dialog that always pops-up when I select the "Firewall Rules" tab, are combined very confusing. The fact that I have to either click "ok" or the close-x on the dialog to select a different tab from "Firewall Rules," also kind of sucks. 
- The red text and the dialog seem to be saying the same thing; but I'm sincerely unsure what that "same thing" is supposed to be.
- `This qube has no networking - it will not have any network access anyway` is just a strange and confusing line of text, even if it were 100% accurate.

I "got it" after conferring with folks in a chat. sys-firewall gets its internet from sys-net, and sys-net gets its internet from its attachment to hardware cards... and then distributes that internet to qubes that utilize it as their net-qube. The red text should say something to the effect of that, though. 

![IMG_0245](https://user-images.githubusercontent.com/8262612/132929185-c0e07944-c45e-41e8-9c2b-147e434c16cf.JPG)

### Steps to reproduce
1. Boot machine
2. Open sys-net's "Qube Settings" applet
3. Click on "Firewall Rules"

### Expected behavior
Anything else, tbh. I had no expectation of anything on this pane, as I didn't even really understand how a firewall works, until a fellow Qubes contributor explained it to me in the context of this issue.

This tab is to describe Firewall things. If this qube is not a firewall, then it is not a firewall. 

### Actual behavior
The "Firewall Rules" pane in Qube Settings attempts to explain other networking-related things, not directly related to the firewall this qube does not have.

### Etc
It feels like it would help for all qubes to have their "Role" designated on the "Basic" pane, and that Service qubes have slightly different and more relevant functionality to more clearly show their properties in their Settings windows? 

Like: the _type_ of this qube, an "App qube," is clearly stated in "General." However, as a service qube it has different needs to surface to users with regards to how its relationships with devices and connectivity are shown. If it _is_ a net-qube, it also should not have a dropdown for a net qube.

As a Service qube, like sys-firewall and sys-usb, sys-net will have unique properties that make some of the tabs in the "Qube Settings" pane irrelevant or seem confusing, given this qube's role. Whonix qubes are even more confusing, as my Whonix qube has no networking cards attached to it, yet the Whonix OS does its connections via my net-vm.

Can make a new issue to explore this concept, if folks here feel it may be warranted. This issue's focus, should simply be removing the confusing dialog and either removing or editing the red text, from the existing "Firewall Rules" pane on Network and Whonix qubes.

**Comment by ejose19** [comment]
I'm also in favor of dropping that alert (the red text along with the disabled buttons should be enough to know that nothing can be done in the current state). I've many times dread of misclicking "Firewall rules" instead of "Advanced" or "Devices" just to get that intrusive alert.

Kinda related: When increasing a qube "Max memory" significantly, one also get an alert regarding 10% "Initial Memory", I understand the intent but maybe it should be displayed in a less obtrusive way? An orange bold text below "Initial memory" should be enough to drag attention while not interfering with user workflow.
