### ISSUE TITLE
Provide a service for GPG signing with a specific key

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#6897]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### The problem you're addressing (if any)
As demonstrated by QSB#071, split-gpg has a very large attack surface.  split-gpg2 has much less attack surface, but still more than might be desired.  Additionally, both are all-or-nothing: either all operations can be allowed, or all of them denied.

### The solution you'd like
Provide a service that will only perform signing, and only with a specific key specified in the qrexec service argument.  This dramatically reduces attack surface, and allows qrexec policy to control which keys can be used by which qubes.  This might be needed if there are two secret keys on the same smart card, for example.

The following is an example implementation specialized for Git commit signing:

```python
#!/usr/bin/python3 --
def main():
    import sys, os, re, fcntl
    if len(sys.argv) != 2:
        print('usage: gpg2.py FINGERPRINT', file=sys.stderr)
        sys.exit(1)
    elif len(sys.argv[1]) != 40:
        print('gpg2.py: fingerprint must be 40 bytes long', file=sys.stderr)
        sys.exit(1)
    fpr = sys.argv[1]
    for i in fpr:
        if not (('0' <= i <= '9') or ('A' <= i <= 'F')):
            print('Invalid character in fingerprint', file=sys.stderr)
            sys.exit(1)
    fd = os.open('/dev/null', os.O_RDWR|os.O_NOCTTY)
    flags = fcntl.fcntl(fd, fcntl.F_GETFD)
    fcntl.fcntl(fd, fcntl.F_SETFD, flags & ~fcntl.FD_CLOEXEC)
    os.execv('/usr/bin/gpg2', (
        'gpg2',
        '--batch',
        '--status-fd=2',
        '--exit-on-status-write-error',
        '--with-colons',
        '--logger-fd=' + str(fd),
        '-basu',
        fpr + '!',
    ))
if __name__ == '__main__':
    main()
```

### The value to a user, and who that user might be
This is especially useful for code signing, but might also be useful for other purposes.  The advantages are less attack surface and the use of qrexec for access control.

**Comment by andrewdavidwong** [comment]
Change milestone from `Non-release` to `Release TBD` because if/when this gets done, it will be implemented in some Qubes OS release.

**Comment by DemiMarie** [comment]
Questions:

- Should ASCII armor vs no ASCII armor be selectable?  If not, armoring should be the default, as dearmoring is a trivial `gpg --dearmor` command.
- Is the `!` in the above service justified?

**Comment by marmarek** [comment]
Bonus points, if the backend can (optionally) log hashes of data that was signed.

**Comment by marmarek** [comment]
The package is built and uploaded to current-testing for both R4.1 and R4.2
