### ISSUE TITLE
qubes-doc commits to not expose CI status

### ISSUE THREAD

**Issue by ydirson** [QubesOS/qubes-issues#6899]
Pull requests on qubes-doc currently all get a FAILED CI run, because of an issue that can only be in `master`, but we cannot see the result of a CI run on `master`.

**Comment by andrewdavidwong** [comment]
Not true. You can see the log specifying the failure: Details > build:doc.

**Comment by ydirson** [comment]
> You can see the log specifying the failure: Details > build:doc.

Hm, I may be too much used to how gitlab presents this (expecting a CI in https://github.com/QubesOS/qubes-doc/commits/master).  I've seen that the CI jobs are actually run on gitlab, which brought me the expectation to see them in https://gitlab.com/QubesOS/qubes-doc/-/commits/master, where they are not either.

Additionally, if I look at the list of pipelines that include the failing PR's (https://gitlab.com/QubesOS/qubes-doc/-/pipelines) I can only see PR's, and no jobs pertaining to master - so technically I hold to my description of the problem.

And I don't see where I'm supposed to find "Details > build:doc".

Maybe some explanation of how the CI is set up would help

**Comment by andrewdavidwong** [comment]
> And I don't see where I'm supposed to find "Details > build:doc".

Yeah, it's pretty hard to find. Try this:

1. Go to your PR page, e.g., https://github.com/QubesOS/qubes-doc/pull/1195
2. Ctrl+F for `continuous-integration/pullrequest`. To the right of it there's a link named `Details`. Click that link.
3. Under the `Pipeline` tab, there's a `Build` heading. Under that heading there's a button named `build:doc`. Or you can just Ctrl+F for `build:doc`. Click that button.
4. You are now looking at the CI log. If there was a failure, the reason for the failure will be stated in this log, usually near the bottom.

(Note that I just fixed an unrelated broken link that was causing a CI failure for https://github.com/QubesOS/qubes-doc/pull/1195, and it's currently retrying the job.)

> Additionally, if I look at the list of pipelines that include the failing PR's (https://gitlab.com/QubesOS/qubes-doc/-/pipelines) I can only see PR's, and no jobs pertaining to master - so technically I hold to my description of the problem.

That's just the way it's set up. It tests your PR as if it were merged into `master`.

**Comment by ydirson** [comment]
>     1. Go to your PR page, e.g.,

This one I did see: it is the CI job for my PR.  The one I do not see is the CI job for master branch, which should have probably shown the broken-link problem you just fixed.

**Comment by andrewdavidwong** [comment]
> > ```
> > 1. Go to your PR page, e.g.,
> > ```
> 
> This one I did see: it is the CI job for my PR. The one I do not see is the CI job for master branch, which should have probably shown the broken-link problem you just fixed.
> 

There is no CI job for every commit to the master branch, only for PRs. Errors in master are reflected in the logs for PR jobs.

**Comment by ydirson** [comment]
> There is no CI job for every commit to the master branch, only for PRs. Errors in master are reflected in the logs for PR jobs.

That is in fact the object of this ticket.  It makes sense to exclude the master branch when noone can push directly to it.  Here it is obviously not the case, which causes errors like this broken link not to be noticed until sbd gets a failure in an unrelated PR.  This is just wrong.

**Comment by marmarek** [comment]
This is actually a bug, commits in the master branch should be tested too. It won't be as useful as for PR, because our spellchecker works by comparing results with the master branch (which would be useless here), but for the other checks it definitely makes sense.
Fixed.

**Comment by andrewdavidwong** [comment]
> This is actually a bug, commits in the master branch should be tested too. It won't be as useful as for PR, because our spellchecker works by comparing results with the master branch (which would be useless here), but for the other checks it definitely makes sense.
> Fixed.

Strange, last time I asked you about this, @marmarek, didn't you say it was intentionally set up this way and that it's sometimes useful to open a PR just to get the CI check even for those of us who have permission to push directly to master? Anyway, I'm not complaining, as I also prefer to have CI checks on master.

**Comment by andrewdavidwong** [comment]
> > There is no CI job for every commit to the master branch, only for PRs. Errors in master are reflected in the logs for PR jobs.
> 
> That is in fact the object of this ticket.

It was not clear to me that this is what you meant (until just then) due to the language barrier.

What's also strange is that I could've sworn there *used* to be CI checks on `master` some years ago...
