### ISSUE TITLE
4.1 installer does not refresh partition info?

### ISSUE THREAD

**Issue by ddevz** [QubesOS/qubes-issues#6906]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
4.1

### Brief summary
"PV /dev/sda2 Already exists" during 4.1 install

### Here's what happened:
I was testing the 4.1 installer, and when it wanted to know what disk space to use, it said the only disk had 30 megabytes left.
I jumped to TTY2, removed the partition tabled, went back to qubes install, hit refresh.  Now qubes installer said the full disk was free.
Configured the rest of the install information (I think it was just the user account)
install progress bar got to around 10% or so then gave a anaconda error, of which I believe the relevant part is:
"PV /dev/sda2 Already exists"
(note: networking was not enabled, so i couldn't get the full logs off the system)

I suspect that somehow anaconda still had the old partition table loaded.  

Assuming that is the problem, I plan to remove the partition table again, then reboot, and then going to try installing again.

### Expected behavior
it to install

### Actual behavior
it did not install

**Comment by ddevz** [comment]
Update:
Yes, it did install when rebooting after removing the partition table

**Comment by kord1e** [comment]
Sounds like a similar problem that I had when installing 4.1.0-rc4:

Reproducing steps as far as I can remember:
- Open the partitioning dialog, select two disks (let's say 100GB and 4TB) and Custom partitioning
- Click the link/button to automatically create partitions in the custom partitioning dialog
- Click the reset button
- Click "done" to get back to the installer main menu
- Open the partitioning tool again, select only one disk (100 GB) and choose Custom partitioning
- Observe the free/used space display on the bottom of the screen, it may still be showing 4.1 TB of space.
- Create the partitions automatically again and press the reset button
- Now the space display should be correct

**Comment by rustybird** [comment]
If you're removing the partition table manually by overwriting some data on the disk's block device and you don't want to reboot, `blockdev --rereadpt <device>` will inform the kernel.
