### ISSUE TITLE
openQA: test_101_resize_root_img_online consistently fails (ext4 pool)

### ISSUE THREAD

**Issue by deeplow** [QubesOS/qubes-issues#6909]
## Observation

openQA test in scenario qubesos-4.1-pull-requests-x86_64-system_tests_basic_vm_qrexec_gui_ext4@64bit fails in
[TC_05_StandaloneVM_debian-10-pool](https://openqa.qubes-os.org/tests/21484/modules/TC_05_StandaloneVM_debian-10-pool/steps/3)

```python

Traceback (most recent call last):
  File "/usr/lib64/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
AssertionError: 10050748 not greater than 19922944
```

## Test suite description
basic tests on ext4 filesystem (file pool)

## Reproducible

Has failed since it started being tested back in test [17349](https://openqa.qubes-os.org/tests/17349)

This always happens, according to the the following plot. It plots the test that match the following error regex: `.*AssertionError: \d+ not greater than 19922944.*` by test and template respectively:

| by test title | by test name (template) |
|----------------|---------------------------------|
|![not-greater-than_by-test](https://user-images.githubusercontent.com/47065258/133786144-26e05d21-e62c-426e-b2a6-fc2526085050.png) | ![not-greater-than_by-template](https://user-images.githubusercontent.com/47065258/133797339-9ba15656-0e5b-424f-ad1d-7e3f683e3847.png) |
| | **note**: the lines with high slope are due to the phasing out of `fedora-33`| 

## Expected result

Last good: none

## Further details

- Always latest result in this scenario: [latest](https://openqa.qubes-os.org/tests/latest?arch=x86_64&distri=qubesos&flavor=pull-requests&machine=64bit&test=system_tests_basic_vm_qrexec_gui_ext4&version=4.1)

- there is a similar error (`AssertionError: 4062912 not greater than 5976883`) but that happens on `test_250_resize_private_img` and has to do with instability.

**Comment by deeplow** [comment]
According to @marmarek this is to be expected since ext4 cannot do online resizing. So we should add an expected failure for this case.

> #### How to online resize the Ext4 filesystem?
>
> Online resizing of ext4 works in a similar manner as ext3, using either resize2fs or ext2resize, but there is currently a limit (around 4TiB or so) to the maximum filesystem size. Implementing online resize with the META_BG feature would allow this limit to be exceeded. 

However, I've also found information that it should indeed be able to work with offline resizing (from [the kernel's wiki](https://ext4.wiki.kernel.org/index.php/Frequently_Asked_Questions#How_to_online_resize_the_Ext4_filesystem.3F)). Maybe I'm missing some detail.

**Comment by marmarek** [comment]
You should have found at least one test run when it succeeded, see https://github.com/QubesOS/qubes-core-admin/pull/424

**Comment by deeplow** [comment]
Indeed. It might be a bug in my script. Will look into it.

**Comment by deeplow** [comment]
> You should have found at least one test run when it succeeded, see [QubesOS/qubes-core-admin#424](https://github.com/QubesOS/qubes-core-admin/pull/424)

Bug fixed. It's now showing that this is solved. (on the image it had some previous "sucesses" but those were because "system_test" probably gave no output. So the error didn't happen in the sense that it didn't have a chance to happen)

| Tests | Errors |
|---------|----------|
|![success_tests](https://user-images.githubusercontent.com/47065258/133990065-149529c4-eae9-4de3-adbf-b8b4e5c8d36f.png) | ![plot-error](https://user-images.githubusercontent.com/47065258/133990307-34b6b066-0c21-4330-bb53-b3fef5ddfd04.png) |

Closing
