### ISSUE TITLE
HVM doc shows obsolete `qvm-prefs` output, does not document block device handling

### ISSUE THREAD

**Issue by ydirson** [QubesOS/qubes-issues#6911]
https://www.qubes-os.org/doc/standalones-and-hvms/#cloning-hvms shows a `qvm-prefs` output that does not reflect what we get in v4.x, notably:

```
dir               : /var/lib/qubes/appvms/my-new-vm
config            : /var/lib/qubes/appvms/my-new-vm/my-new-vm.conf
pcidevs           : []
root img          : /var/lib/qubes/appvms/my-new-vm/root.img
private img       : /var/lib/qubes/appvms/my-new-vm/private.img
```

Somewhat related, when booting a HVM we can see `xvd[a-d]` are setup and passed to qemu, and it would be useful to document what to expect of them.

**Comment by marmarek** [comment]
Indeed that `qvm-prefs` output is outdated. The description of block devices is at https://www.qubes-os.org/doc/template-implementation/
