### ISSUE TITLE
Standalone Debian 10 Qube Fails to Open App With No Error Message

### ISSUE THREAD

**Issue by straussmaus** [QubesOS/qubes-issues#6912]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
4.0 (updated)

### Brief summary

When I open a Standalone Debian Qube that I use every day, it will not open an application.  The Qube itself does turn on and its underlying NetVM too.

### Steps to reproduce

See  description.

### Expected behavior

The application (in this case, Terminal, Firefox, xterm) should open on the display.

### Actual behavior

The underlying NetVM opens, the Qube shows a green dot, but the application does not open in display.  There is no error message, which is why this must be defined as a bug.

I *can* get to the terminal using qvm-console-dispvm <qube>.

dom0 /var/log/vm-QUBENAME.log does not show any error messages (or anything else for the timestamp when I tried to open the applications).

**Comment by straussmaus** [comment]
Ah, the disk was full.  Deja vu.  I have another ticket for this: https://github.com/QubesOS/qubes-issues/issues/6277

That ticket was closed as duplicate for https://github.com/QubesOS/qubes-issues/issues/4791

That ticket was closed, yet this problem remains.  

So I will leave this ticket open.

**Comment by DemiMarie** [comment]
Can you post the output of `systemctl status` in `qvm-console-dispvm`?

**Comment by unman** [comment]
On Sun, Sep 19, 2021 at 06:33:16PM -0700, straussmaus wrote:
> Ah, the disk was full.  Deja vu.  I have another ticket for this: https://github.com/QubesOS/qubes-issues/issues/6277
> 
> That ticket was closed as duplicate for https://github.com/QubesOS/qubes-issues/issues/4791
> 
> That ticket was closed, yet this problem remains.  
> 
> So I will leave this ticket open.
> 

I don't understand how you seem to manage to keep running out of disk space.
Do you not receive notifications of low disk space? If not, this would be
a regression.
Do you get notifications, but too late for you to take action?

**Comment by andrewdavidwong** [comment]
> Ah, the disk was full.  Deja vu.  I have another ticket for this: https://github.com/QubesOS/qubes-issues/issues/6277
> 
> 
> 
> That ticket was closed as duplicate for https://github.com/QubesOS/qubes-issues/issues/4791
> 

But this issue seems to be different from both of those issues, because they're about restoring from backups, whereas this one isn't. 

> 
> That ticket was closed, yet this problem remains.  
> 
> 
> So I will leave this ticket open.

What exactly is the problem in this case?
