### ISSUE TITLE
qubes-dom0-update broken in Whonix 16 / Debian 11 bullseye due to missing yumdownloader

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#6913]
`sudo qubes-dom0-update` results in VM using `/usr/lib/qubes/qubes-download-dom0-updates.sh` which is internally using `yumdownloader`. However, `yumdownloader` is no longer available in Debian 11 `bullseye`.

`yumdownloader` is part of package [yum-utils](https://packages.debian.org/buster/yum-utils) but that was last available for Debian 10 `buster`.

Debian 11 `bullseye` however does provide package [dnf](https://packages.debian.org/bullseye/dnf) `4.5.2`.

Perhaps `/usr/lib/qubes/qubes-download-dom0-updates.sh` could be ported to use it?

Tested only with Whonix 16 but should be same issue with Debian 11.

**Comment by marmarek** [comment]
`qubes-download-dom0-updates.sh` (tries to) use `yumdownloader` only if there is no `dnf` (which was the case on debian-10), so on debian-11 it should use dnf (which is also expressed in the package dependencies: https://github.com/QubesOS/qubes-core-agent-linux/blob/master/debian/control#L111). Maybe it's just about uwt wrapper for dnf?

**Comment by adrelanos** [comment]
Yes, it's working now.

Though, I was seeing in the xtrace that running `yumdownloader` as attempted. Unfortunately didn't keep the xtrace.

**Comment by airelemental** [comment]
I just updated whonix-gw-16 and I'm now able to run `qubes-dom0-update` with sys-whonix-16 as updatevm.

**Comment by unman** [comment]
> Tested only with Whonix 16 but should be same issue with Debian 11.

It didnt apply to the debian-11 template in testing.
> Yes, it's working now.

Please close.
