### ISSUE TITLE
[openQA] audio tests fail: "AssertionError: only silence detected"

### ISSUE THREAD

**Issue by deeplow** [QubesOS/qubes-issues#6915]
## Observation

Many times openQA fails in the suites `system_tests_basic_vm_qrexec_gui` with the following error: ([recent example](https://openqa.qubes-os.org/tests/19591#step/TC_00_AppVM_whonix-ws-15/17))

* When it happens in `test_223_audio_play_hvm`:

    ```python
    Traceback (most recent call last):
     File "/usr/lib/python3.8/site-packages/qubes/tests/integ/vm_qrexec_gui.py", line 610, in test_223_audio_play_hvm
       self.common_audio_playback()
     File "/usr/lib/python3.8/site-packages/qubes/tests/integ/vm_qrexec_gui.py", line 501, in common_audio_playback
        self.check_audio_sample(recorded_audio.file.read(), sfreq)
     File "/usr/lib/python3.8/site-packages/qubes/tests/integ/vm_qrexec_gui.py", line 461, in check_audio_sample
        self.fail('only silence detected, no useful audio data')
    AssertionError: only silence detected, no useful audio data
    ```

* When it happens in `test_225_audio_rec_unmuted_hvm`:

    ```python
    Traceback (most recent call last):
      File "/usr/lib/python3.8/site-packages/qubes/tests/integ/vm_qrexec_gui.py", line 632, in test_225_audio_rec_unmuted_hvm
        self.common_audio_record_unmuted()
      File "/usr/lib/python3.8/site-packages/qubes/tests/integ/vm_qrexec_gui.py", line 582, in common_audio_record_unmuted
        self.check_audio_sample(recorded_audio, sfreq)
      File "/usr/lib/python3.8/site-packages/qubes/tests/integ/vm_qrexec_gui.py", line 461, in check_audio_sample
        self.fail('only silence detected, no useful audio data')
    AssertionError: only silence detected, no useful audio data
    ``` 

## Test suite description
basic tests on all filesystems `basic_vm_qrexec_gui*` (file pool)

## Reproducible

Happens randomly, but I was able to reproduce it locally once.

This always happens, according to the the following plot. Using the filter regex for the error `".*only silence detected.*"` by test and templates for all the available suites we obtain the plots bellow. 

> **Note:** all job ids in the bottom of each plot are the respective parent job for easier comparison.

### Tests where it happens

As can be seen bellow, this only happens in the following tests:
  - test_225_audio_rec_unmuted_hvm
  - test_223_audio_play_hvm

|  system_tests_basic_vm_qrexec_**gui_btrfs** | system_tests_basic_vm_qrexec_**gui_xfs** |
|--------------|--------------|
| ![tests_gui_btrfs](https://user-images.githubusercontent.com/47065258/134180757-daf5be17-c215-4b66-a035-96c92c5d6c24.png) | ![tests_gui_xfs](https://user-images.githubusercontent.com/47065258/134180796-58f70524-253a-4a97-9579-ec4a7fb8a44d.png)

|  system_tests_basic_vm_qrexec_**gui** | system_tests_basic_vm_qrexec_**gui_ext4** |
|--------------|--------------|
|  ![tests_gui](https://user-images.githubusercontent.com/47065258/134180828-af3c37aa-8199-4b31-8615-3338c9feada5.png) | ![tests_gui_ext4](https://user-images.githubusercontent.com/47065258/134180847-bfc4af66-5b7a-46bf-9e96-144d8e122afb.png)|

### test_225_audio_rec_unmuted_hvm

|  system_tests_basic_vm_qrexec_**gui_btrfs** | system_tests_basic_vm_qrexec_**gui_xfs** |
|--------------|--------------|
| ![225_gui_btrfs](https://user-images.githubusercontent.com/47065258/134181762-ede6db45-a12c-4b4d-a901-9c9b4ce98f31.png) | ![225_gui_xfs](https://user-images.githubusercontent.com/47065258/134181787-f19d01eb-80a4-432b-abb0-98d5e1df212a.png) |

|  system_tests_basic_vm_qrexec_**gui** | system_tests_basic_vm_qrexec_**gui_ext4** |
|--------------|--------------|
| ![225_gui](https://user-images.githubusercontent.com/47065258/134181825-9a47c11d-adc7-4d71-9799-24139a53cd8a.png) | ![225_gui_ext4](https://user-images.githubusercontent.com/47065258/134181894-597be60c-6053-4929-a21f-770e460fd3f8.png) |

### test_223_audio_play_hvm

The reason why I separated the tests `223` and `225` is because there seems to be an odd pattern on test `223`:
  - It started affecting `fedora-33` a lot
  - then only once case in `fedora-34` across all test suites in test [19383](https://openqa.qubes-os.org/tests/19383#dependencies) (I wonder what happened there)
  - and more recently (`whonix-ws-15`)

Furthermore I've only been able to reproduce locally this issue (1/20 times) with the `whonix-ws-15`.

|  system_tests_basic_vm_qrexec_**gui_btrfs** | system_tests_basic_vm_qrexec_**gui_xfs** |
|--------------|--------------|
| ![223_gui_btrfs](https://user-images.githubusercontent.com/47065258/134181956-111170fe-224c-4a46-ae8b-c1db01d6417d.png) | ![223_gui_xfs](https://user-images.githubusercontent.com/47065258/134181996-d637c7dd-ed06-4ae7-9b56-d76d05c29e62.png) |

|  system_tests_basic_vm_qrexec_**gui** | system_tests_basic_vm_qrexec_**gui_ext4** |
|--------------|--------------|
| ![223_gui](https://user-images.githubusercontent.com/47065258/134182027-8fcdebdc-9edb-4a4d-890e-6a5556bc53c4.png) | ![223_gui_ext4](https://user-images.githubusercontent.com/47065258/134182070-1a98930a-b2f0-4674-b9e0-9b3f4ab5ec71.png)|

## Expected result

Last good: https://openqa.qubes-os.org/tests/17430

**Comment by andrewdavidwong** [comment]
Please make sure to specify the earliest affected Qubes OS version in all future issues.

**Comment by deeplow** [comment]
> Please make sure to specify the earliest affected Qubes OS version in all future issues. Taking an educated guess that this is about 4.1.

Oh. Sorry. Yes, I think we can assume it's 4.1. This has happened at least once in `4.0` tests (see [here](https://openqa.qubes-os.org/tests/12881#step/TC_00_AppVM_debian-10/17) but I don't have a lot of other data on 4.1 tests and all that I checked had no other issues like this.

**Comment by andrewdavidwong** [comment]
> This has happened at least once in `4.0` tests

Ok, reassigning to 4.0 updates. (The milestone reflects the earliest affected version.)

**Comment by deeplow** [comment]
By kernel version assuming the naming
  - `linux-image-amd64` in debian
  - `kernel` in fedora
  - I couldn't find how to obtain the kernel version from whonix's packages

![by_kernel](https://user-images.githubusercontent.com/47065258/134895111-6c306a95-4baf-4f1d-ac29-bb9a1a463e9f.png)

By pulseaudio's package version

![by_pulseaudii](https://user-images.githubusercontent.com/47065258/134894896-4b8b4cf1-c5b6-4e39-aa80-b1c6019be886.png)

So, not very conclusive, I would say.

**Comment by deeplow** [comment]
Some updated reports on this issue. Ran with these commands:

```bash
python3 openqa_investigator.py --suite "system_tests_basic_vm_qrexec_gui_xfs" --last 60 --error "only silence detected, no useful audio data" --test ".*/.*" --output plot_errors --verbose --db-path ./openqa_db.sqlite
python3 openqa_investigator.py --suite "system_tests_basic_vm_qrexec_gui_ext4" --last 60 --error "only silence detected, no useful audio data" --test ".*/.*" --output plot_errors --verbose --db-path ./openqa_db.sqlite
python3 openqa_investigator.py --suite "system_tests_basic_vm_qrexec_gui_btrfs" --last 60 --error "only silence detected, no useful audio data" --test ".*/.*" --output plot_errors --verbose --db-path ./openqa_db.sqlite
python3 openqa_investigator.py --suite "system_tests_basic_vm_qrexec_gui" --last 60 --error "only silence detected, no useful audio data" --test ".*/.*" --output plot_errors --verbose --db-path ./openqa_db.sqlite
```

### system_tests_basic_vm_qrexec_gui_xfs
![system_tests_basic_vm_qrexec_gui_xfs](https://user-images.githubusercontent.com/47065258/147875076-e727bc74-dcd9-440d-ad28-11c1e0172a51.png)
### system_tests_basic_vm_qrexec_gui_ext4
![system_tests_basic_vm_qrexec_gui_ext4](https://user-images.githubusercontent.com/47065258/147875077-55df0c23-f9fb-4c15-a8f8-7ac52836bf60.png)
### system_tests_basic_vm_qrexec_gui_btrfs
![system_tests_basic_vm_qrexec_gui_btrfs](https://user-images.githubusercontent.com/47065258/147875078-1731e812-8165-48ca-9e03-91a7652e49e9.png)
### system_tests_basic_vm_qrexec_gui
![system_tests_basic_vm_qrexec_gui](https://user-images.githubusercontent.com/47065258/147875079-e4caf318-eb3d-40bd-8a10-e5c843852d56.png)
