### ISSUE TITLE
4.1 qubes-tunnel in qubes-repo-contrib no longer available on debian-10/11-minimal-templates, key expired

### ISSUE THREAD

**Issue by jobforacowboy** [QubesOS/qubes-issues#6921]
Hi!
please update the keys for contrib repo.

```
GPG error: https://contrib.qubes-os.org/deb/4.1/vm buster/bullseye InRelease: The following signatures were invalid: EXPKEYSIG A8F7A1D....AA Qubes OS Contrib Release 4 Signing Key
The repository is not signed
```

**Comment by rustybird** [comment]
Someone encountered the same error after upgrading their Debian 10 template to Debian 11 in-place: https://forum.qubes-os.org/t/4-1-contrib-issues/6642/3

**Comment by mfc** [comment]
i get the same with R4.0:
```
Err:3 https://contrib.qubes-os.org/deb/r4.0/vm buster InRelease
  The following signatures were invalid: EXPKEYSIG A8F7A1DC99F29DAA Qubes OS Contrib Release 4 Signing Key
```

**Comment by rustybird** [comment]
Indeed R4.0 is affected too, and it doesn't matter whether the template was upgraded in place: The [qubes-repo-contrib PGP keys](https://github.com/QubesOS/qubes-meta-packages/tree/master/repos) for all distributions have expired.

Now why the hell doesn't `dnf` seem to care about key expiration...

**Comment by marmarek** [comment]
Fixed with https://github.com/QubesOS/qubes-meta-packages/pull/41
