### ISSUE TITLE
Update split-gpg tests for Thunderbird 91

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#6925]
Thunderbird 91 has significantly different user interface, the test needs to be updated to correctly use it.

This currently applies to fedora-34 template, but soon will be on others too.

**Comment by deeplow** [comment]
@marmarek is this something you want me to take a look at?

**Comment by marmarek** [comment]
I didn't thought about it, but actually that maybe a good idea :)

**Comment by deeplow** [comment]
> Thunderbird 91 has significantly different user interface

Just as important as the user interface change is to address the [removal of Movemail](https://www.thunderbird.net/en-US/thunderbird/91.0/releasenotes/).

**Comment by marmarek** [comment]
Ouch. Then probably find what's the easiest way to setup local POP3 or IMAP server... (similar how we do SMTP).

**Comment by deeplow** [comment]
> Ouch. Then probably find what's the easiest way to setup local POP3 or IMAP server... (similar how we do SMTP).

Yes. That's what I was looking into right now.

**Comment by andrewdavidwong** [comment]
Moving to "non-release," as it sounds like this is an enhancement to our testing infrastructure rather than an enhancement that will be implemented in Qubes OS 4.0 itself.
