### ISSUE TITLE
Add option to display mouse cursor in AppVM window

### ISSUE THREAD

**Issue by littlebenlittle** [QubesOS/qubes-issues#6926]
### The problem you're addressing (if any)

Assigning a USB mouse to an AppVM is currently possible, but the mouse cursor is hidden.

### The solution you'd like

Add an option for each AppVM window to "display mouse cursor" and an option to set that option by default on all of an AppVM's windows.

### The value to a user, and who that user might be

This change would give users the option to use the HID of their choice (tablets, USB mice, fancy LED-lit trackballs, etc) while limiting its access to resources on their system.

**Comment by marmarek** [comment]
Just to be sure: are you aware of qubes-input-proxy (`qubes.Input*` qrexec services)? They are designed to allow just specific type of input (USB) device access to the whole system.
https://www.qubes-os.org/doc/usb-qubes/#auto-enabling-a-usb-mouse

**Comment by littlebenlittle** [comment]
Thanks @marmarek. I'm specifically interested in keeping untrusted and/or potentially buggy devices from interacting with dom0.

Perhaps this is unnecessarily cautious.

**Comment by marmarta** [comment]
Closing this, because qubes.Input is just about that :). I don't think we'll ever go deeper than that.

**Comment by andrewdavidwong** [comment]
If I understand correctly, this issue has been closed as "won't do." If anyone has a new reason for why this should be done, please leave a comment, and we'll be happy to take another look. Thank you.
