### ISSUE TITLE
Debian security-testing repo is corrupt

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#6929]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
R4.1

### Brief summary
Debian security-testing repo is corrupt

### Steps to reproduce
`apt update` with security-testing enabled

### Expected behavior
Success

### Actual behavior

```
E: Failed to fetch https://deb.qubes-os.org/r4.1/vm/dists/bullseye-securitytesting/main/binary-amd64/Packages.gz  File has unexpected size (9546 != 9545). Mirror sync in progress? [IP: 127.0.0.1 8082]
   Hashes of expected file:
    - Filesize:9545 [weak]
    - SHA256:d4f9060250b5be4a1d32ffc04e2866f60e1b45397c15b5c156c0f4baed38b644
    - SHA1:b4fd83387617e82b12e7cb330bb35e14e4842337 [weak]
    - MD5Sum:28abbd15c4b3fa5297dbd4fb83d07a81 [weak]
   Release file created at: Mon, 27 Sep 2021 20:53:22 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by DemiMarie** [comment]
Fixed.

**Comment by DemiMarie** [comment]
I suspect the files were updated after InRelease was, not before.

**Comment by marmarek** [comment]
Fixed

**Comment by antarisherdeng4** [comment]
I have the same problem on QubesOS R4.0:

> E: Failed to fetch https://deb.qubes-os.org/r4.0/vm/dists/bullseye-securitytesting/main/binary-amd64/Packages.gz  File has unexpected size (6389 != 6393). Mirror sync in progress? [IP: 127.0.0.1 8082]
>    Hashes of expected file:
>     - Filesize:6393 [weak]
>     - SHA256:213beff25c661098c1720aea894c853c398897854f2ec3c4f9977c65dc55a4e9
>     - SHA1:c30b6477b122890d62e5097f13f8796b0b46b526 [weak]
>     - MD5Sum:fa436186203052a849385bb4fda7e3bc [weak]
>    Release file created at: Fri, 17 Jun 2022 00:16:56 +0000
>

**Comment by andrewdavidwong** [comment]
> I have the same problem on QubesOS R4.0

4.0 has reached EOL. Please upgrade to 4.1.

https://www.qubes-os.org/news/2022/08/04/qubes-4-0-has-reached-eol/
