### ISSUE TITLE
Monitor disk space in dom0

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#693]
**Reported by marmarek on 16 Dec 2012 14:53 UTC**
Disk space is monitored only in VM (by some GNOME application) - user will get nice warning.
There is nothing to inform the user about low disk space in dom0, which is much more critical event...
There should be also some tool to help with cleanup - for now the only way to free space is remove some VM (doing its backup first). There should be some tool to "compact" disk images (root.img and private.img) - something like cleanup_image in template-builder. Unfortunately it needs some free space for the operation (2 x image size, because image needs to be copied).

Migrated-From: https://wiki.qubes-os.org/ticket/693

**Comment by heinrich-ulbricht** [comment]
@marmarek So... how can I see the free disk space in dom0 in Qubes 4?

**Comment by marmarek** [comment]
There is a separate disk usage widget by default, with a disk icon. When you hover over it, it's described "Qubes Disk Space Monitor".
