### ISSUE TITLE
Thinkpad X1 Carbon gen 8 microphone does not work out-of-the-box

### ISSUE THREAD

**Issue by jalbstmeijer** [QubesOS/qubes-issues#6934]
### Qubes OS release

4.1

### Brief summary

There seems to be a microphone detected, but does not work.

### Steps to reproduce

Connect device "microphone" to VM and try to record input in that VM.
Used https://www.onlinemictest.com/ as simple test.

### Expected behavior

Detect or be able to record input

### Actual behavior

There is no input.

### Expected behavior

Detect microphone input.

Got is working with this information; https://askubuntu.com/questions/1336087/18-04-issues-with-x1-carbon-alsamixer-config-microphone-issues-what-does-pa

Load module manually on dom0 with;

pacmd load-module module-alsa-source device=hw:0,6

and persistent with the following in /etc/pulse/default.pa on dom0

load-module module-alsa-source device=hw:0,6

And change input device in "PulseAudio colume control" to "sof-hda-dsp"

**Comment by jevank** [comment]
Digital mic requires SOF firmware.
`sudo qubes-dom0-update alsa-sof-firmware`

**Comment by jalbstmeijer** [comment]
So that should be an alternative to the pacmd actions that made it work for me?

Installed alsa-sof-firmware now, commented /etc/pulse/default.pa entry I added and rebooted.

Microphone is not working again.

**Comment by jevank** [comment]
I've tested with 5.10.70 kernel and SOF firmware installed. Firmware boot successful according  kernel logs, pavucontrol shows devices sof-hda-dsp with multichannel input. Output works fine, external mic too, internal available but didn't detect sound. I guess problem might be with alsa profile or smth similar.

**Comment by jalbstmeijer** [comment]
> I've tested with 5.10.70 kernel and SOF firmware installed. Firmware boot successful according kernel logs, pavucontrol shows devices sof-hda-dsp with multichannel input. Output works fine, external mic too, internal available but didn't detect sound. I guess problem might be with alsa profile or smth similar.

Same result on kernel 5.14.9-1

**Comment by jevank** [comment]
`sudo qubes-dom0-update alsa-ucm` and reboot

**Comment by jalbstmeijer** [comment]
> `sudo qubes-dom0-update alsa-ucm` and reboot

That's fixes it for me too.
So is it to be expected this will work out-of-the-box with a future 4.1 release?

**Comment by jalbstmeijer** [comment]
So till now the fix has been;

sudo qubes-dom0-update alsa-sof-firmware alsa-ucm

how should I test this fix? remove "alsa-sof-firmware" and "alsa-ucm" first and see if "sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing" installs them again?

I was not aware these packages were also needed to be added to the Qubes templates besides dom0.

**Comment by marmarek** [comment]
The change makes the firmware pkgs included in the installation image, there are no relevant changes on package update (neither dom0 nor vm).

**Comment by Bwahharharrr** [comment]
I have 4.1.1 with a Gen 9 and pavucontrol showing no input devices, both alsa-sof-firmware and alsa-ucm are both installed

**Comment by marmarek** [comment]
Try kernel-latest: https://www.qubes-os.org/doc/hardware-troubleshooting/#audio-doesnt-work--troubleshooting-newer-hardware

**Comment by Bwahharharrr** [comment]
Seems quite a few reporting issues with the Gen 9 microphone not working here also, https://forum.qubes-os.org/t/sound-does-not-work-on-lenovo-x1-carbon-gen-9th/6035/20

**Comment by DemiMarie** [comment]
Does this work with `kernel-latest`?

**Comment by andrewdavidwong** [comment]
> DemiMarie modified the milestones: Release 4.1, Release TBD 2 hours ago

@DemiMarie, the milestone `Release TBD` makes no sense on bug reports. That would be saying that we plan to introduce this bug in some future release, but we haven't decided which one yet. :P
