### ISSUE TITLE
Arch build does not work

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#6935]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
R4.1

### Brief summary
Arch template build does not work

### Steps to reproduce
Try to build the Arch template

### Expected behavior
Build succeeds

### Actual behavior
Build fails.  I believe using an old base image is the culprit.

**Comment by unman** [comment]
On Tue, Oct 05, 2021 at 07:30:31AM -0700, Demi Marie Obenour wrote:
> [How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)
> 
> ### Qubes OS release
> R4.1
> 
> 
> 
> 
> ### Brief summary
> Arch template build does not work
> 
> 
> 
> 
> ### Steps to reproduce
> Try to build the Arch template
> 
> 
> 
> 
> ### Expected behavior
> Build succeeds
> 
> 
> 
> ### Actual behavior
> Build fails.  I believe using an old base image is the culprit.
> 
> 

The lack of detail here doesnt help.

Since I successfully built templates at the end of September, I wonder
if it is the use of a *new* base image (bootstrap from 2021-10-01) that
is the issue.

**Comment by DemiMarie** [comment]
> The lack of detail here doesnt help.

Honestly, the error messages I got were almost useless.  It was as if the base image didn’t include the needed OpenPGP keys.  I will attack an error log.

> Since I successfully built templates at the end of September, I wonder if it is the use of a *new* base image (bootstrap from 2021-10-01) that is the issue.

Quite possibly

**Comment by lubellier** [comment]
@DemiMarie : with the [#7282](https://github.com/QubesOS/qubes-issues/issues/7282) closed issue and the 
[7cfd553](https://github.com/QubesOS/qubes-builder-archlinux/commit/7cfd553666289b9951235bb2fd0a6c4ebb7d34d7) commit, this issue is now closable, isn't it?

**Comment by DemiMarie** [comment]
Can you build a template?

**Comment by DemiMarie** [comment]
I can’t, but @marmarek can :)

**Comment by lubellier** [comment]
Now it's OK, I built an ArchLinux template.
For updating the [building-archlinux-template](https://github.com/Qubes-Community/Contents/blob/master/docs/building/building-archlinux-template.md) guide with [PR #182](https://github.com/Qubes-Community/Contents/pull/182), I run all the build procedure and got a runnable template.

**Comment by techge** [comment]
This issue seems to be resolved, isn't it? Just got here in a search for problems...

**Comment by unman** [comment]
Yes, it is.
Arch builds OK.

**Comment by DemiMarie** [comment]
Closing as this bug appears to be fixed.
