### ISSUE TITLE
Website: Remove HR + 2 Social Icons to help discoverability of "Join The Community!" section

### ISSUE THREAD

**Issue by ninavizz** [QubesOS/qubes-issues#6936]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### The problem you're addressing (if any)
Towards the bottom of the website's homepage there is currently an HR below the sub-head "Join The Community!."  Below that HR, are the actual icons. When looking at it previously, I'd just assumed content the header spoke to had been blocked from loading-in because of my ad-blockers (which is a frequent thing for me). 

Further confusing things, is the presence of LinkedIn and Facebook icons—which has me think those are the general/corporate "How to find us" social icons for a company, and not an entry point into the Qubes Community.  Yes, Qubes does have a presence on those platforms, but those are not actual "communities."

At a high level, there is currently no clear easy to find entry into the community for folks. While #6835 seeks to address broader information architecture problems, This feels like a very easy quick fix, and like a fix that could help temper the direct-emailing folks problem. Apologies for not submitting my own PR on this, as I have noooo idea how to do that. Yes, I eventually need to find a visual editor I can do website stuff with.

### The solution you'd like
- Remove HR between `Join The Community!` and social icons (note: I looked at the code and have nooooo idea how to do this).
- Remove LinkedIn and Facebook icon. Those are for Qubes "pages" on the respective websites, but not where the "Qubes Community" is present. 

Stretch:
- A line of regular body text between the "Join The Community!" blurb and the social icons, that mirrors this one at the top of the "Help" page in the docs:

> The Qubes community is here to help! Since Qubes is a security-oriented operating system, we want to make sure you stay safe as you get the support you need, and we want to make sure our community remains a friendly and productive place by ensuring we all follow the Code of Conduct and discussion guidelines.

### The value to a user, and who that user might be
- Users or contributors looking for the Qubes community.
- Qubes team members and community managers, frequently fielding direct emails or GitHub posts asking questions that are more appropriate for the forums.

**Comment by ninavizz** [comment]
Or, instead of what is already in the docs:

> Got questions or need a hand? As a free and open-source project, our valued community of users and contributors from around the world are the go-to support resource for folks with questions. Volunteers from the community are often better poised to answer questions, than even the core team. 
> 
> We encourage and often point to our`<a>`discussion guide`</a>` to keep things positive and on track, and strictly enforce our `<a>`Code of Conduct`</a>`. We welcome newcomers and returning faces wanting to learn about Qubes, Linux, secure computing, free software, and `<a>`seeking to contribute`</a>`.  

Sorry... my brain just cannot get past the occasional "Your customer service sucks!" comments in the surveys, or people behaving badly in forums. Wanting to better manage folks' expectations.

**Comment by ninavizz** [comment]
@andrewdavidwong FWIW, two things I'm wanting to do with #6835 are 1. Create a "Community" page that spells-out stuff like mailing lists, Reditt is unofficial whereas the Forum is official, where to go for Support vs general banter, and that correctly contextualizes GitHub... and 2. Create a "Find Us" column for the fat footer, that includes all social links. 

Good catch on the Twitter inclusion in that blob!

Yes, the underline beneath a header is common on websites for sections—but there's only one line of stuff below that underline, before the next section. So it looks like there's missing content. Perhaps a new "Class" without the underline, for just that one section?

See below screenie, for brokenness observed. With a few lines of body copy below the underline, and then the fancy button, it will look a lot less broken. :)  I like the idea of the fancier button for the Forum, btw, good call! 
<img width="1317" alt="Screen Shot 2021-10-07 at 1 41 40 PM" src="https://user-images.githubusercontent.com/8262612/136459031-718336dd-2278-4091-a5a6-59380399873c.png">

Question: Is the fat-footer auto-generated, or manually curated?

**Comment by ninavizz** [comment]
> Sounds like this is all already covered on the support page.
> 
>         Create a "Find Us" column for the fat footer, that includes all social links.
> 
> These are already all linked from the footer.

Correct... however, it's not intuitive for users to find help/support content in documentation, or social links mixed-in with other content in a footer. One of the current "problems" with the website, is that Qubes is no longer a small OSS project; the team is small, and it's leaner than ever—but with +30k users and many coming into Qubes from outside the OSS space, more consumer-product conventions of findability are expected (eg: "Customer Service"). Hence, my desire to at least present some of this content more discoverably, for folks _not_ coming into the Qubes world from within FOSS.

Per mention in #6835 I'm wanting to take what already exists in the docs on the "Support" page, and move it outside of the docs and into a more consumable format (with Bootstrap accordions to make the page much shorter and easier for folks to find stuff).

**Comment by DemiMarie** [comment]
> This doesn't sound unreasonable to me, I just shudder a bit when I think about trying to do it then trying to maintain it all. I wonder if the time has come for us to migrate the website to some third-party platform that allows us to do "fancy" things more easily, like WordPress (or whatever the kids are using these days). Perhaps this might be complementary to migrating the docs to RTD.

noooooo!!!!!!  Not unless we pre-generate the site and serve the static files.  WordPress is loaded with security holes.
