### ISSUE TITLE
Debian-11 template for 4.0 does not support mounting exfat volumes

### ISSUE THREAD

**Issue by unman** [QubesOS/qubes-issues#6949]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
4.0.4
Qubes testing repositories enabled in dom0
All testing/updates repositories enabled in Debian-11

### Brief summary
Cannot mount exfat volumes

### Steps to reproduce
Use volume formatted to exfat: appears in sys-usb as /dev/sdX1
`mount /dev/sdX1 /mnt`

### Expected behavior
Volume will be mounted at /mnt

### Actual behavior
mount fails:
`mount: /mnt: unknown filesystem type 'exfat'`

N.B
Reported at https://forum.qubes-os.org/t/error-mounting-exfat-in-debian-11/6714
The exfat-utils are installed. Just to be sure, I removed them and re-installed.
ntfs volumes can be mounted - they also use fuse.
This is specific to the 4.0 template - everything works as expected in 4.1

**Comment by unman** [comment]
It is installed by default in the debian-11 template.
Did you read the link I provided to the original report?

**Comment by jevank** [comment]
I mean did you try to mount with exfat-fuse? As I understand current kernel version for debian and fedora dists contain new exfat kernel module. With R4.1 you have no problem with it. With R4.0  kernel version is 5.4 w/o kernel exfat support, but fuse packages still works:
```
user@debian-11:~$ sudo mount -t exfat /dev/sda1 /mnt/
mount: /mnt: unknown filesystem type 'exfat'.
user@debian-11:~$ sudo mount.exfat-fuse /dev/sda1 /mnt/
FUSE exfat 1.3.0
user@debian-11:~$ 
```

More serious problem is with fedora-34. Exfat support for fedora comes from rpmfusion repo and it was obsoleted lately, so it needs to build it from sources.

> Did you read the link I provided to the original report?

Sorry, missed that

**Comment by unman** [comment]
As this is specific to 4.0, can be closed.
