### ISSUE TITLE
`_NET_WM_PING` support

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#6950]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### The problem you're addressing (if any)
The GUI daemon doesn’t support [`_NET_WM_PING`].

### The solution you'd like
The GUI daemon should support `_NET_WM_PING`.

### The value to a user, and who that user might be
If the GUI daemon freezes it can be automatically detected.

**Comment by alimirjamali** [comment]
PR Submitted

Review priority: low

Video demo:

https://github.com/user-attachments/assets/67068d42-8332-4868-8cdd-3ff55af10b8c
