### ISSUE TITLE
`qubes-dist-upgrade` passes inexistent `--standalone` option to `qvm-check`

### ISSUE THREAD

**Issue by ydirson** [QubesOS/qubes-issues#6953]
### Qubes OS release

4.1beta

### Brief summary

While checking how this script works in more details, trying to see if I could selectively upgrade a single StandaloneVM to r4.1, which it apparently missed, I took this code from the script to check if it was running:

```
[root@dom0 ~]# for vm in $(qvm-ls --raw-list --fields name); do if qvm-check -q --standalone "$vm"; then echo "$vm"; fi; done
usage: qvm-check [--verbose] [--quiet] [--help] [--all] [--exclude EXCLUDE] [--running] [--paused] [--template] [--networked] [VMNAME [VMNAME ...]]
qvm-check: error: unrecognized arguments: --standalone
...
```

... and indeed this option does not exist.

Why on earth are you redirecting stderr to `/dev/null` on so many occurrences (including in qubes-builder) ?  I mean, how much can we trust scripts which actively hide reported errors ?

Related: https://github.com/QubesOS/qubes-dist-upgrade/pull/4

It looks like the reason why my only StandaloneVM was left with r4.0 fc32 repositories.

**Comment by marmarek** [comment]
Fixed
