### ISSUE TITLE
System-wide toggle for encrypting volatile volumes

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#6958]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### The problem you're addressing (if any)
https://github.com/QubesOS/qubes-core-admin/commit/c7ed3e9b6d16e4c4e0dbf0c5c73a955d33275608 makes volatile volume encryption opt-in, but doesn’t provide a system-wide tunable to set the default.

### The solution you'd like
Have a global “Encrypt volatile volumes with an ephemeral key” setting, which defaults to false.

### The value to a user, and who that user might be
Users who would like to turn on volatile volume encryption for all qubes can easily do so.

**Comment by brendanhoar** [comment]
In R4.1rc3, executing:
```
qvm-pool set vm-pool -o ephemeral_volatile=true
```
Enabled this feature.

I verified the additional layer via ```lsblk``` is using the crypt type on any newly started VMs.

Brendan
