### ISSUE TITLE
Dom0 USB Hardening

### ISSUE THREAD

**Issue by 3hhh** [QubesOS/qubes-issues#6959]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### The problem you're addressing (if any)

Dom0 is easy prey to USB attacks, if some hubs are not assigned to `sys-usb`.

However it may make a lot of sense to assign a hub to dom0 for a trusted USB keyboard or mouse as assigning those to `sys-usb` [has its own set of security issues](https://www.qubes-os.org/doc/device-handling-security/).

### The solution you'd like

Dom0 is reasonably secure even when it needs to handle some USB devices.

### The value to a user, and who that user might be

Input devices directly attached to dom0, some VMs on external USB disks, external sound cards, ...

### The solution I use

https://usbguard.github.io/

With a policy that:
- only allows USB hubs, block devices, smart cards, input devices and sound cards if they were attached at boot time
- allows the aforementioned devices on hotkey press after boot
- disallows all other devices at all times

### Side Notes

The same ideally applies to all other enabled ports. Unfortunately similar solutions do not appear to exist for these due to kernel limitations (except for maybe `bolt` for thunderbolt, nothing for HDMI).

Related: #2743

**Comment by 3hhh** [comment]
Here's what I recommend for the doc at least: https://github.com/Qubes-Community/Contents/pull/148

I designed it in a way that should be applicable to most users, i.e. it should even be possible to use it by default.

**Comment by marmarek** [comment]
Subset of it - specifically allowing only HID devices, got implemented for R4.1. Allowing other devices (but not all of them) still requires manually setting usbguard policy.

**Comment by 3hhh** [comment]
Awesome, thanks @DemiMarie @marmarek !

Then from my point of view this one can be closed unless you plan to do more in that regard.

**Comment by brendanhoar** [comment]
This topic is becoming more important over time and not just for desktop users: I just received a new production laptop where the integrated keyboard and pointer are both USB devices. :( And three of the four external USB ports are on the same bus or controller as the pointer/keyboard.

**Comment by DemiMarie** [comment]
> This topic is becoming more important over time and not just for desktop users: I just received a new production laptop where the integrated keyboard and pointer are both USB devices. :( And three of the four external USB ports are on the same bus or controller as the pointer/keyboard.

Which laptop is this?  The one that is *not* on the same controller is the one you will want to use for anything untrusted, though you still need to worry about boot attacks if it is recognized by the firmware.

**Comment by brendanhoar** [comment]
GPD Pocket 3 (11th gen intel).

I created a sys-net for the usb-c/thunderbolt port, moving a cluster of three associated pcie (sub-)devices to sys-net, but the three USB-A ports, which are on a standalone pcie USB 3.2 controller need to stay in dom0 or the keyboard/pointer will stop working.

Not the best topology for Qubes.

B

**Comment by marmarek** [comment]
Theoretically, you could plug another controller on a mPCIe card, then glue ports connected to the keyboard-having one. But in practice, there may be issues with that, like the mPCIe port in an inconvenient place - the thing I'm doing literally right now (for other reasons):
![laptop-usb](https://user-images.githubusercontent.com/726704/150394597-a669d423-6983-487d-9135-b531726cfba5.jpg)

**Comment by DemiMarie** [comment]
Test or prod system @marmarek?

**Comment by marmarek** [comment]
_very_ much test, the card isn't even completely inserted, because it doesn't fit in the case ;)

**Comment by brendanhoar** [comment]
> Theoretically, you could plug another controller on a mPCIe card, then glue ports connected to the keyboard-having one. But in practice, there may be issues...

Heh. 

I think there's only one internal pcie port which is for a single NVME. The unit is 198mm x 137mm x 20mm with an 8" screen, so not much room for Frankensteining. 

Even the expansion module's USB pins are tied to the same controller, sadly.

I'm wondering if the choice to use USB connections for kbd/pointer has to do with the unit's KVM console expansion module feature...or  maybe other laptop developers are also doing away with PS/2 support.

B

**Comment by marmarek** [comment]
I _guess_ (and hope) most laptops will stay with non-USB internal
keyboard, because technically it compelling to connect it to/through the
Embedded Controller - to capture various special (Fn+...) keys, and also
the power button. Otherwise, EC would need to gain USB support, or
having two interfaces to the keyboard (or subset of it).

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
