### ISSUE TITLE
Create "Contact Us" page for website

### ISSUE THREAD

**Issue by ninavizz** [QubesOS/qubes-issues#6964]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### The problem you're addressing (if any)
Per #6835, item 2 in the recommendations punchlist.

Problem: Without a "Contact Us" page or more discoverable paths to help/support, frustrated users are emailing individuals on the core team from the Team page. 

### The solution you'd like
1. "Inquiries" section removed from Team page
2. "Inquiries" content moved to new "Contact Us" page and ordered per below & [Figma mockup](https://www.figma.com/file/oMjfKRg1Vjc8NeRF11j2rU/IA-Overview—Menuzz?node-id=289%3A1421)
  - Will likely require a little more webdev-fu than any of the core team are able to provide.
     - Are you that awesome person? Hooray! 
        - In the upper-right on the Figma window, you should see an "Inspect" panel. That is where you can see dimensions and sizing and hex values and such.
        - All typography done with Roboto Condensed instead of Ostrich, assuming that CSS will eventually change. No intentions to have this page in Roboto Condensed, and the rest of the site Ostrich (so, code to global styles—and if/when those change, great!). 
3. Add "Enterprise Support" as item, as included on proposed "Help" page
4. Add "Need Support?" blab at bottom of page
4. Replace existing icons w/ PNGs & new icons
5. Team page moved from the main navigation to the footer

![ContactUs-PG](https://user-images.githubusercontent.com/8262612/137042289-40651d10-7f9e-411c-a7f5-79432c5cf14f.png)

### The value to a user, and who that user might be
- End Users
  - Folks using Qubes and unaccustomed to looking for crtical information in developer docs.
  - Folks using the Docs but unable to find "paid support" as an actionable item.
- Core Team
  - Folks currently email us from the _Team_ page, when they can't find stuff they need. This is a distraction and kind of a drag that may likely be easy to resolve or cut-down on, with more discoverable help content.   
  - Per above, demoting the "Team" page to the footer and only putting black-hole/generalized email addresses from the "Inquiries" section of that page, in the main nav.

**Comment by cheznewa** [comment]
But For A Question? How To Do It??

**Comment by andrewdavidwong** [comment]
> Inquiries!?
> 
> But For A Question? How To Send A Question In Mail??


Please note that the issue tracker (`qubes-issues`) is not intended to be a place for fielding questions. Instead, we have other [venues meant for asking questions, asking for help, and having discussions](https://www.qubes-os.org/support/). (By contrast, the issue tracker is more of a technical tool intended to support our developers in their work.) Thank you for your understanding!

**Comment by kennethrrosen** [comment]
Seems, given the date and non-response, and this page https://www.qubes-os.org/team/#core-team this ticket should be closed.
