### ISSUE TITLE
unable to build focal-desktop : fatal: couldn't find remote ref release4.0

### ISSUE THREAD

**Issue by openStove** [QubesOS/qubes-issues#6977]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
xen_version            : 4.8.5-35.fc25
Linux 5.13.6-1.fc25.qubes.x86_64
  
Installed Packages:  
  
kernel-qubes-vm.x86_64                            	1000:4.19.152-1.pvops.qubes 
kernel-qubes-vm.x86_64                            	1000:5.4.129-1.fc25.qubes 
kernel-qubes-vm.x86_64                            	1000:5.4.136-1.fc25.qubes 
kernel-qubes-vm.x86_64                            	1000:5.4.143-1.fc25.qubes 
python2-qubesadmin.noarch                         	4.0.32-1.fc25 
python3-qubesadmin.noarch                         	4.0.33-1.fc25 
python3-qubesdb.x86_64                            	4.0.16-1.fc25 
python3-qubesimgconverter.x86_64                  	4.0.34-1.fc25 
qubes-anaconda-addon.noarch                       	4.0.11-1.fc25 
qubes-artwork.noarch                              	4.0.1-2.fc25 
qubes-core-admin-addon-whonix.noarch              	4.0.2-1.fc25 
qubes-core-admin-client.noarch                    	4.0.33-1.fc25 
qubes-core-dom0.x86_64                            	4.0.58-1.fc25 
qubes-core-dom0-linux.x86_64                      	4.0.30-1.fc25 
qubes-core-dom0-linux-kernel-install.x86_64       	 
qubes-db.x86_64                                   	4.0.16-1.fc25 
qubes-db-dom0.x86_64                              	4.0.16-1.fc25 
qubes-db-libs.x86_64                              	4.0.16-1.fc25 
qubes-desktop-linux-common.noarch                 	4.0.22-1.fc25 
qubes-desktop-linux-manager.noarch                	4.0.25-1.fc25 
qubes-gpg-split-dom0.x86_64                       	2.0.53-1.fc25 
qubes-gui-dom0.x86_64                             	4.0.14-1.fc25 
qubes-img-converter-dom0.x86_64                   	1.2.10-1.fc25 
qubes-input-proxy.x86_64                          	1.0.24-1.fc25 
qubes-input-proxy-receiver.x86_64                 	1.0.24-1.fc25 
qubes-libvchan-xen.x86_64                         	4.0.9-1.fc25 
qubes-manager.noarch                              	4.0.45-1.fc25 
qubes-menus.noarch                                	4.0.22-1.fc25 
qubes-mgmt-salt.noarch                            	4.0.26-1.fc25 
qubes-mgmt-salt-admin-tools.noarch                	4.0.26-1.fc25 
qubes-mgmt-salt-base.noarch                       	4.0.4-1.fc25 
qubes-mgmt-salt-base-config.noarch                	4.0.2-1.fc25 
qubes-mgmt-salt-base-overrides.noarch             	4.0.2-1.fc25 
qubes-mgmt-salt-base-overrides-libs.noarch        	 
qubes-mgmt-salt-base-topd.noarch                  	4.0.2-1.fc25 
qubes-mgmt-salt-config.noarch                     	4.0.26-1.fc25 
qubes-mgmt-salt-dom0.noarch                       	4.0.26-1.fc25 
qubes-mgmt-salt-dom0-qvm.noarch                   	4.0.10-1.fc25 
qubes-mgmt-salt-dom0-update.noarch                	4.0.10-1.fc25 
qubes-mgmt-salt-dom0-virtual-machines.noarch      	 
qubes-pdf-converter-dom0.x86_64                   	2.1.12-1.fc25 
qubes-release.noarch                              	4.0-10 
qubes-release-notes.noarch                        	4.0-10 
qubes-rpm-oxide.x86_64                            	0.2.2-1.fc25 
qubes-template-debian-10.noarch                   	4.0.6-202011030518 
qubes-template-fedora-32.noarch                   	4.0.6-202011030518 
qubes-template-whonix-gw-15.noarch                	4.0.6-202009121407 
qubes-template-whonix-ws-15.noarch                	4.0.6-202009121407 
qubes-usb-proxy-dom0.noarch                       	1.1.1-1.fc25 
qubes-utils.x86_64                                	4.0.34-1.fc25 
qubes-utils-libs.x86_64                           	4.0.34-1.fc25 
xfce4-settings-qubes.x86_64                       	4.0.3-1.fc25 

### Brief summary
I try to build focal-desktop template with marmarek repo, but I get following error : 
fatal: couldn't find remote ref release4.0make get-sources
-> Updating sources for builder-debian...
--> Fetching from https://github.com/marmarek/qubes-builder-debian.git master (options: --depth=1)...
--> Verifying tags...
---> Good tag 5426d6b824cc3c36732d1800c4af70dc5874abb0
--> Merging...

-> Updating sources for vmm-xen...
--> Fetching from https://github.com/marmarek/qubes-vmm-xen.git xen-4.8 (options: --depth=1)...
--> Verifying tags...
---> Good tag 05b758e4e022191152ba054a05e64f63b5cf0a6b
--> Merging...

-> Updating sources for core-vchan-xen...
--> Fetching from https://github.com/marmarek/qubes-core-vchan-xen.git release4.0 (options: --depth=1)...
fatal: couldn't find remote ref release4.0
make: *** [Makefile:218: core-vchan-xen.get-sources] Error 1

### Steps to reproduce

- ./setup with maramarek repo (others als doesn't work with other errors)
- make install-deps
- make get-sources

### Expected behavior
the template is building correctly

### Actual behavior
error mentionned above

**Comment by unman** [comment]
Why are you using marmarek repo? There is no release4.0 branch there,
which is why your make get-sources fails.
Use the standard Qubes repositories.

You don't say what errors you have encountered with the Qubes
repositories. This is unfortunate since I build focal on a regular
basis, and the build completes.
It would be more useful if you asked on the mailing list or the Forum
for help with your build.

**Comment by andrewdavidwong** [comment]
Based on our [issue tracking guidelines](https://www.qubes-os.org/doc/issue-tracking/), this does not appear to be suitable for `qubes-issues`. We ask that you please post this on the [Qubes Forum or `qubes-users` mailing list](https://www.qubes-os.org/support/) instead. If, after reading our [issue tracking guidelines](https://www.qubes-os.org/doc/issue-tracking/), you believe we are mistaken, please leave a brief comment explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.
