### ISSUE TITLE
Fedora 37+ in dom0

### ISSUE THREAD

**Issue by fepitre** [QubesOS/qubes-issues#6982]
Tracking issue for Fedora 34+ dom0:
- [x] build all packages
- [x] include at least Fedora 34+ as default template for qubes
- [x] build and test a release candidate for QubesOS 4.2

**Comment by fepitre** [comment]
> Fedora 35 is being released tomorrow slightly_smiling_face

This why there is a 34+. There is a little jump between 32 and 34+ so now updating to 35, 36 or 37 would be easier I hope.

**Comment by DemiMarie** [comment]
> * [ ]  build and test a release candidate for QubesOS 4.2

That fast?  R4.1 isn’t even final yet!

**Comment by fepitre** [comment]
> > * [ ]   build and test a release candidate for QubesOS 4.2
> 
> That fast? R4.1 isn’t even final yet!

This is why this checkbox would probably be checked in several months :)

**Comment by DemiMarie** [comment]
> > > * [ ]    build and test a release candidate for QubesOS 4.2
> > 
> > 
> > That fast? R4.1 isn’t even final yet!
> 
> This is why this checkbox would probably be checked in several months :)

I hope we can get it done that fast!

**Comment by marmarek** [comment]
Current R4.2 builds are on fc37 dom0 already.

**Comment by the-moog** [comment]
Ref Dom0 in Qubes [4.2.0 release notes](https://www.qubes-os.org/doc/releases/4.2/release-notes/).
I was under the impression that [Fedora 37 is EOL](https://docs.fedoraproject.org/en-US/releases/eol/) as of two months ago?
What plans are there to adopt a newer release and is there a clean upgrade path or should we wait and do a fresh install once Qubes adopts the new release (or adopts Debian instead, cough - given Fedora 38 is also EOL[ in just three months](https://fedorapeople.org/groups/schedule/f-38/f-38-key-tasks.html))
Is it not a little worrying to base a "Reasonably Secure OS" on a distribution that lacks supported updates?

**Comment by xaki23** [comment]
the qubes dom0 fedora is somewhat traditionally EOL on the fedora side.
it is still supported and updated as needed as a qubes dom0 though.
see https://www.qubes-os.org/doc/supported-releases/#dom0
