### ISSUE TITLE
4.1rc1 - qvm-template install is broken for debian-11 and whonix updateVMs

### ISSUE THREAD

**Issue by unman** [QubesOS/qubes-issues#6985]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
4.1rc1
Updated from testing repositories.
templates updated from testing repositories.

### Brief summary
When using debian-11 and Whonix as updateVM, qvm-template install is broken.
Templates cannot be installed - download fails.

### Steps to reproduce
Use Debian-11 as updateVM for dom0.
Attempt to install template (either directly with `qvm-template` or with `qubes-dom0-update`)

### Expected behavior
Template will be installed

### Actual behavior
No data is downloaded.
`download failed, retrying`

**Comment by SaswatPadhi** [comment]
I hit this bug today as well when trying to install a new template. Regardless of the template & the template-repo I select, nothing gets downloaded.

Is there a workaround for this?

**Comment by SaswatPadhi** [comment]
I manually commented out the following lines in `/usr/bin/qubes-dom0-update` to fallback to the old behavior:

https://github.com/QubesOS/qubes-core-admin-linux/blob/79e26e563944e90826c8aa4418486582d8de89dc/dom0-updates/qubes-dom0-update#L131-L143

Worked as expected.

**Comment by daewok** [comment]
I ran into this as well. I tracked it down to `qvm-template-repo-query` in the UpdateVM (sys-firewall, debian-11 template for me).  It calls `dnf download ... --url ...` in order to get the URL for downloading the package.

Unfortunately, the download command is a plugin for dnf that is not packaged on Debian, so that command fails and then curl has no idea where to download the template from.

I get the following when I try to find the URL for the debian 10 template.

```
user@sys-firewall:~$ dnf download --releasever=4.1 --setopt=reposdir=/tmp/tmp.chSjZ1Q19S --quiet --url qubes-template-debian-10-0:4.0.6-202009131420
No such command: download. Please use /usr/bin/dnf --help
It could be a DNF plugin command, try: "dnf install 'dnf-command(download)'"
```

**Comment by marmarek** [comment]
> Unfortunately, the download command is a plugin for dnf that is not packaged on Debian

Ouch. I'll try to get that working without the plugin (either another command, that is actually available, or via python API directly...).

**Comment by marmarek** [comment]
I've evaluated several options, and the easiest thing to do seems to be ship `download.py` on Debian, from dnf-plugins-core package. It's 300 lines file (including comments), works standalone (without other plugins) and can be put in any directory (then, pointed at via `pluginpath` dnf option). Alternatives require comparable amount of boilerplate that would need to be actually written...

**Comment by daewok** [comment]
Hopefully Debian will package it eventually. Looks like someone is working on it: <https://ftp-master.debian.org/new/dnf-plugins-core_4.0.21-1~exp1.html>

**Comment by marmarek** [comment]
Fixed in https://github.com/marmarek/qubes-core-agent-linux/commit/e673a1fa36d49e672f85897e6a0cb7ea2bad0cd1
