### ISSUE TITLE
Qubes Manager inproperly handles qube start failure

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#6987]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

R4.1

### Brief summary

Qubes Manager does not register failed qube start.

### Steps to reproduce

1. Have a system with too little memory to start a qube
2. Click "start" on a qube in Qubes Manager
3. Click "ok" on a message that qube failed to start

### Expected behavior

Qube remain marked as stopped, it's possible to (try to) start it again.

### Actual behavior

Qube has yellow status dot, start button is inactive, but pause, shutdown and restart are active - all fail because qube is not really running.

**Comment by GWeck** [comment]
The same may happen if a qube shuts down somewhat awkwardly, which may happen for Windows and some community qubes. In Qube Manager, the qube stays at the yellow state although it is no longer running. Restarting the Qube Manager clears this situation.
