### ISSUE TITLE
[Bug] salt execution environment is not wiped by salt-ssh and interferes in app qubes states specifically

### ISSUE THREAD

**Issue by lkubb** [QubesOS/qubes-issues#6991]
Please consider this more a notice than an actual bug since I think the problem is found in upstream salt-ssh, but it has some confusing side-effects specifically regarding Qubes. I am not sure if this is fixable by configuration alone.

### Qubes OS release
4.1

### Brief summary
Applying salt states with `qubesctl --skip-dom0 --target=someid state.apply` will leave the salt folder `/var/tmp/root_<hash>_salt` behind [despite requesting a wipe](https://github.com/QubesOS/qubes-mgmt-salt/blob/53cd2f30067d130b324e982632285cc945acba20/qubes.SaltLinuxVM#L51), which can cause confusion when applying states to an app qube directly after targeting its template. In particular, `grains["id"]` will still contain the template id.

This was already described in https://github.com/QubesOS/qubes-issues/issues/4709 and apparently fixed from your side in https://github.com/QubesOS/qubes-mgmt-salt/pull/10, but at least on my system, salt-ssh will keep the configuration anyways. I filed a bug report upstream as well (https://github.com/saltstack/salt/issues/61083), including a simple fix. I'm not a salt pro though.

### Steps to reproduce
This is for the remaining configuration part, for incorrect grains['id'] refer to the linked Qubes OS issue.

```bash
qvm-clone debian-11-minimal someid
```

[/srv/salt/top.sls]
```yaml
base:
  someid:
    - teststate
```

[/srv/salt/teststate.sls]
```sls
packages-installed:
  pkg.installed:
    - names:
      - curl
```

```console
$ sudo qubesctl --skip-dom0 --target=someid state.apply
$ qvm-run --pass-io someid -- ls -lha /var/tmp
```

### Expected behavior
no `.root_<hash>_salt`

### Actual behavior
```console
$ sudo qubesctl --skip-dom0 --target=someid state.apply
$ qvm-run --pass-io someid -- ls -lha /var/tmp
total 20K
drwxrwxrwt  5 root root 4.0K Oct 20 12:34 .
drwxr-xr-x  5 root root 4.0K Oct 20 12:34 ..
drwx------  5 root root 4.0K Oct 20 12:34 .root_<hash>_salt
[...]
```

**Comment by andrewdavidwong** [comment]
> Please consider this more a notice than an actual bug since I think the problem is found in upstream salt-ssh

Based on our [issue tracking guidelines](https://www.qubes-os.org/doc/issue-tracking/), this does not appear to be suitable for `qubes-issues`. We ask that you please post this on the [Qubes Forum or `qubes-users` mailing list](https://www.qubes-os.org/support/) instead. If, after reading our [issue tracking guidelines](https://www.qubes-os.org/doc/issue-tracking/), you believe we are mistaken, please leave a brief comment explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.

Closing as "not our bug" (the Qubes OS Project does not develop the software that is causing this bug). If you believe this resolution is a mistake, please leave a comment, and we'll be happy to take another look. Thank you.

[FAQ: Why don’t you fix upstream bugs that affect Qubes OS?](https://www.qubes-os.org/faq/#why-dont-you-fix-upstream-bugs-that-affect-qubes-os)
