### ISSUE TITLE
qubes-core-admin-client should conflict with older qubes-core-dom0

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#6995]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

R4.1

### Brief summary

`qubes-core-admin-client` should depend on a `qubes-core-dom0` new enough to support all of the admin API calls it includes

### Steps to reproduce

    $ rpm -qv qubes-core-dom0
    qubes-core-dom0-4.1.22-1.fc32.noarch
    $ rpm -qv qubes-core-admin-client
    qubes-core-admin-client-4.1.17-1.fc32.noarch
    $ qvm-pool set -o ephemeral_volatile=True lvm
    qvm-pool: error: Failed to set option ephemeral_volatile for pool lvm: Got empty response from qubesd. See journalctl in dom0 for details.

### Expected behavior

`qubes-core-admin-client` should depend on a sufficiently new `qubes-core-dom0` to make #6994 impossible.

### Actual behavior

`qubes-core-admin-client` does not depend on a sufficiently new `qubes-core-dom0`

**Comment by marmarek** [comment]
No, it cannot. qubes-core-admin-client can be installed in VM too.

**Comment by marmarek** [comment]
I don't think it's appropriate to introduce hard dependency to avoid minor confusion. The risk outweighs benefits.
