### ISSUE TITLE
4.1rc1: Cross-attaching a block device only works once and fails afterwards

### ISSUE THREAD

**Issue by 3hhh** [QubesOS/qubes-issues#6996]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
4.1rc1

### Brief summary

Attaching a block device from one VM to another works only exactly once.

### Steps to reproduce
1. Create two disposable VMs, let's say `disp1` and `disp2`, then create a loop example device.
2. In `disp1`: `dd if=/dev/zero of=/home/user/loopfile bs=1M count=20`
3. In `disp1`: `sudo losetup -f /home/user/loopfile` (assuming that it returns `/dev/loop0`)
4. In `disp1`: `sudo mkfs -t ext4 /dev/loop0`
5. In `dom0`: `qvm-block a disp2 disp1:loop0` (first attach)
6. In `disp2`: `sudo mount /dev/xvdi /mnt && touch /mnt/somefile && umount /dev/xvdi`
7. In `dom0`: `qvm-block d disp2 disp1:loop0`
8. In `dom0`: `qvm-block a disp2 disp1:loop0 && qvm-block ls` (second attach)
9. In `disp2`: `lsblk ; dmesg|tail`

### Expected behavior

`xvdi` is available in `disp2`.

### Actual behavior

`xvdi` is not available in `disp2` even though `qvm-block ls` states that it should be.

### Notes

I know for sure that this works in 4.0, i.e. this bug _exclusively_ affects 4.1rc1.

**Comment by marmarek** [comment]
I can confirm it happens. It is somehow related to incomplete cleanup on detach (a device in state "closed" remains in xenstore after detach). This whole machinery is rather complex, so I'm not really sure if the problem is some missing cleanup step, or rather pre-existing entry breaking attaching new one in that place.
