### ISSUE TITLE
Qubesd failed to start (r4.1)

### ISSUE THREAD

**Issue by 0spinboson** [QubesOS/qubes-issues#6998]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

R4.1, up to date with updates testing

### Brief summary
Qubesd failed to start
![IMG_20211021_125509.jpg](https://user-images.githubusercontent.com/21077532/138263877-7fea6ab0-0d49-45b5-99c7-e2b8e9beac56.jpg)

### Expected behavior
Qubesd starts

### Actual behavior
Qubesd cannot start. 

### additional info

System uptime of 6 weeks, problem first noticed this morning prior to a reboot, when a vm refused to start. I somewhat foolishly did not investigate this further prior to rebooting the system. Last updates installed were the October 20 ones, few days ago the system definitely worked fine.

**Comment by marmarek** [comment]
This looks like a broken `/var/lib/qubes/qubes.xml` file. Check if it isn't truncated or something like this. Then, you can restore it from a backup in `/var/lib/qubes/backup` (it's made at each system start, check for the most recent non-broken one).

**Comment by tasket** [comment]
@marmarek I ran into a similar problem and I think it may be due to a Qubes bug:

qubesd refused to start, with the log reporting a 'KeyError: dom0'.  A quick look at qubes.xml showed the file to be complete; at least it had the closing `<\qubes>` tag.

The solution was to edit qubes.xml and move the 'domain-0' entry to the top of the `<domains>` section.  The way I found it, 'domain-0' was at least 4 entries down the list.

Also:  This happened on rebooting immediately after a hard system crash precipitated by starting a misconfigured _sys-usb_.  This suggests maybe there are _qubesd_ processes that write qubes.xml more than once, the first time with domains in the wrong order and then a second time with proper sorting.  A crash could interrupt that, leaving the incorrectly sequenced xml on disk.

**Comment by tasket** [comment]
I would also like to know if Qubes has an option to keep a backup of the previous qubes.xml.

**Comment by tasket** [comment]
This happened again, after a different sort of 'crash'.  The system stopped responding to actions like close window, shutdown vm, although some vms seemed to be responding to basic inputs.

After rebooting qubesd would not start and I had to edit qubes.xml in the same way as before.

I don't see anything that stands out in the system log, apart from what I already posted.

Qubes version numbers:

qubes-core-admin-addon-whonix.noarch         4.1.1-1.fc32                        @anaconda         
qubes-core-admin-client.noarch               4.1.27-1.fc32                       @anaconda         
qubes-core-dom0.noarch                       4.1.30-1.fc32                       @anaconda         
qubes-core-dom0-linux.x86_64                 4.1.23-1.fc32                       @anaconda         
qubes-core-dom0-linux-kernel-install.x86_64  4.1.23-1.fc32                       @anaconda         
qubes-core-qrexec.x86_64                     4.1.20-1.fc32                       @anaconda         
qubes-core-qrexec-dom0.x86_64                4.1.20-1.fc32                       @anaconda         
qubes-core-qrexec-libs.x86_64                4.1.20-1.fc32                       @anaconda         
qubes-db.x86_64                              4.1.15-1.fc32                       @anaconda         
qubes-db-dom0.x86_64                         4.1.15-1.fc32                       @anaconda         
qubes-db-libs.x86_64                         4.1.15-1.fc32                       @anaconda         
xen.x86_64                                   2001:4.14.5-20.fc32                 @qubes-dom0-cached
kernel-latest.x86_64                                           1000:6.1.12-1.qubes.fc32                                    @qubes-dom0-cached

**Comment by rustybird** [comment]
@tasket What exception traceback did you get before the `KeyError: 'dom0'` line?

I tried it by starting qubesd with the XML `domain` element for dom0 moved to the very end of the `domains` element. Here, the problem seems to be the `keyboard_layout` property:

<details>

    Traceback (most recent call last):
      File "/usr/lib/python3.8/site-packages/qubes/__init__.py", line 227, in __get__
        return getattr(instance, self._attr_name)
    AttributeError: 'DispVM' object has no attribute '_qubesprop_keyboard_layout'
    During handling of the above exception, another exception occurred:
    Traceback (most recent call last):
      File "/usr/lib/python3.8/site-packages/qubes/__init__.py", line 227, in __get__
        return getattr(instance, self._attr_name)
    AttributeError: 'DispVM' object has no attribute '_qubesprop_guivm'
    During handling of the above exception, another exception occurred:
    Traceback (most recent call last):
      File "/usr/lib/python3.8/site-packages/qubes/__init__.py", line 227, in __get__
        return getattr(instance, self._attr_name)
    AttributeError: 'Qubes' object has no attribute '_qubesprop_default_guivm'
    During handling of the above exception, another exception occurred:
    Traceback (most recent call last):
      File "/usr/bin/qubesd", line 5, in <module>
        sys.exit(main())
      File "/usr/lib/python3.8/site-packages/qubes/tools/qubesd.py", line 38, in main
        args = parser.parse_args(args)
      File "/usr/lib/python3.8/site-packages/qubes/tools/__init__.py", line 359, in parse_args
        namespace.app = qubes.Qubes(namespace.app,
      File "/usr/lib/python3.8/site-packages/qubes/app.py", line 930, in __init__
        self.load(lock=lock)
      File "/usr/lib/python3.8/site-packages/qubes/app.py", line 1023, in load
        vm.load_properties(load_stage=2)
      File "/usr/lib/python3.8/site-packages/qubes/__init__.py", line 691, in load_properties
        setattr(self, name, value)
      File "/usr/lib/python3.8/site-packages/qubes/__init__.py", line 248, in __set__
        oldvalue = getattr(instance, self.__name__)
      File "/usr/lib/python3.8/site-packages/qubes/__init__.py", line 230, in __get__
        return self.get_default(instance)
      File "/usr/lib/python3.8/site-packages/qubes/__init__.py", line 237, in get_default
        return self._default_function(instance)
      File "/usr/lib/python3.8/site-packages/qubes/vm/qubesvm.py", line 739, in <lambda>
        default=(lambda self: getattr(self.guivm, 'keyboard_layout', 'us++')),
      File "/usr/lib/python3.8/site-packages/qubes/__init__.py", line 230, in __get__
        return self.get_default(instance)
      File "/usr/lib/python3.8/site-packages/qubes/__init__.py", line 237, in get_default
        return self._default_function(instance)
      File "/usr/lib/python3.8/site-packages/qubes/vm/qubesvm.py", line 584, in <lambda>
        default=(lambda self: self.app.default_guivm),
      File "/usr/lib/python3.8/site-packages/qubes/__init__.py", line 230, in __get__
        return self.get_default(instance)
      File "/usr/lib/python3.8/site-packages/qubes/__init__.py", line 237, in get_default
        return self._default_function(instance)
      File "/usr/lib/python3.8/site-packages/qubes/app.py", line 763, in <lambda>
        default=lambda app: app.domains['dom0'], allow_none=True,
      File "/usr/lib/python3.8/site-packages/qubes/app.py", line 512, in __getitem__
        raise KeyError(key)
    KeyError: 'dom0'

</details>

[Making](https://gist.github.com/rustybird/42ab4201ea3e5b4d29bc747e42a509e9) `keyboard_layout` a `load_stage=4` property allowed qubesd to start again.

**Comment by tasket** [comment]
@rustybird Yes, seems to be the same:

<details>
```
Apr 14 16:40:10 dom0 qubesd[2353]: Traceback (most recent call last):
Apr 14 16:40:10 dom0 qubesd[2353]:   File "/usr/lib/python3.8/site-packages/qubes/__init__.py", line 227, in __get__
Apr 14 16:40:10 dom0 qubesd[2353]:     return getattr(instance, self._attr_name)
Apr 14 16:40:10 dom0 qubesd[2353]: AttributeError: 'AppVM' object has no attribute '_qubesprop_keyboard_layout'
Apr 14 16:40:10 dom0 qubesd[2353]: During handling of the above exception, another exception occurred:
Apr 14 16:40:10 dom0 qubesd[2353]: Traceback (most recent call last):
Apr 14 16:40:10 dom0 qubesd[2353]:   File "/usr/lib/python3.8/site-packages/qubes/__init__.py", line 227, in __get__
Apr 14 16:40:10 dom0 qubesd[2353]:     return getattr(instance, self._attr_name)
Apr 14 16:40:10 dom0 qubesd[2353]: AttributeError: 'AppVM' object has no attribute '_qubesprop_guivm'
Apr 14 16:40:10 dom0 qubesd[2353]: During handling of the above exception, another exception occurred:
Apr 14 16:40:10 dom0 qubesd[2353]: Traceback (most recent call last):
Apr 14 16:40:10 dom0 qubesd[2353]:   File "/usr/lib/python3.8/site-packages/qubes/__init__.py", line 227, in __get__
Apr 14 16:40:10 dom0 qubesd[2353]:     return getattr(instance, self._attr_name)
Apr 14 16:40:10 dom0 qubesd[2353]: AttributeError: 'Qubes' object has no attribute '_qubesprop_default_guivm'
Apr 14 16:40:10 dom0 qubesd[2353]: During handling of the above exception, another exception occurred:
Apr 14 16:40:10 dom0 qubesd[2353]: Traceback (most recent call last):
Apr 14 16:40:10 dom0 qubesd[2353]:   File "/usr/bin/qubesd", line 5, in <module>
Apr 14 16:40:10 dom0 qubesd[2353]:     sys.exit(main())
Apr 14 16:40:10 dom0 qubesd[2353]:   File "/usr/lib/python3.8/site-packages/qubes/tools/qubesd.py", line 38, in main
Apr 14 16:40:10 dom0 qubesd[2353]:     args = parser.parse_args(args)
Apr 14 16:40:10 dom0 qubesd[2353]:   File "/usr/lib/python3.8/site-packages/qubes/tools/__init__.py", line 359, in parse_args
Apr 14 16:40:10 dom0 qubesd[2353]:     namespace.app = qubes.Qubes(namespace.app,
Apr 14 16:40:10 dom0 qubesd[2353]:   File "/usr/lib/python3.8/site-packages/qubes/app.py", line 930, in __init__
Apr 14 16:40:10 dom0 qubesd[2353]:     self.load(lock=lock)
Apr 14 16:40:10 dom0 qubesd[2353]:   File "/usr/lib/python3.8/site-packages/qubes/app.py", line 1023, in load
Apr 14 16:40:10 dom0 qubesd[2353]:     vm.load_properties(load_stage=2)
Apr 14 16:40:10 dom0 qubesd[2353]:   File "/usr/lib/python3.8/site-packages/qubes/__init__.py", line 691, in load_properties
Apr 14 16:40:10 dom0 qubesd[2353]:     setattr(self, name, value)
Apr 14 16:40:10 dom0 qubesd[2353]:   File "/usr/lib/python3.8/site-packages/qubes/__init__.py", line 248, in __set__
Apr 14 16:40:10 dom0 qubesd[2353]:     oldvalue = getattr(instance, self.__name__)
Apr 14 16:40:10 dom0 qubesd[2353]:   File "/usr/lib/python3.8/site-packages/qubes/__init__.py", line 230, in __get__
Apr 14 16:40:10 dom0 qubesd[2353]:     return self.get_default(instance)
Apr 14 16:40:10 dom0 qubesd[2353]:   File "/usr/lib/python3.8/site-packages/qubes/__init__.py", line 237, in get_default
Apr 14 16:40:10 dom0 qubesd[2353]:     return self._default_function(instance)
Apr 14 16:40:10 dom0 qubesd[2353]:   File "/usr/lib/python3.8/site-packages/qubes/vm/qubesvm.py", line 739, in <lambda>
Apr 14 16:40:10 dom0 qubesd[2353]:     default=(lambda self: getattr(self.guivm, 'keyboard_layout', 'us++')),
Apr 14 16:40:10 dom0 qubesd[2353]:   File "/usr/lib/python3.8/site-packages/qubes/__init__.py", line 230, in __get__
Apr 14 16:40:10 dom0 qubesd[2353]:     return self.get_default(instance)
Apr 14 16:40:10 dom0 qubesd[2353]:   File "/usr/lib/python3.8/site-packages/qubes/__init__.py", line 237, in get_default
Apr 14 16:40:10 dom0 qubesd[2353]:     return self._default_function(instance)
Apr 14 16:40:10 dom0 qubesd[2353]:   File "/usr/lib/python3.8/site-packages/qubes/vm/qubesvm.py", line 584, in <lambda>
Apr 14 16:40:10 dom0 qubesd[2353]:     default=(lambda self: self.app.default_guivm),
Apr 14 16:40:10 dom0 qubesd[2353]:   File "/usr/lib/python3.8/site-packages/qubes/__init__.py", line 230, in __get__
Apr 14 16:40:10 dom0 qubesd[2353]:     return self.get_default(instance)
Apr 14 16:40:10 dom0 qubesd[2353]:   File "/usr/lib/python3.8/site-packages/qubes/__init__.py", line 237, in get_default
Apr 14 16:40:10 dom0 qubesd[2353]:     return self._default_function(instance)
Apr 14 16:40:10 dom0 qubesd[2353]:   File "/usr/lib/python3.8/site-packages/qubes/app.py", line 763, in <lambda>
Apr 14 16:40:10 dom0 qubesd[2353]:     default=lambda app: app.domains['dom0'], allow_none=True,
Apr 14 16:40:10 dom0 qubesd[2353]:   File "/usr/lib/python3.8/site-packages/qubes/app.py", line 512, in __getitem__
Apr 14 16:40:10 dom0 qubesd[2353]:     raise KeyError(key)
Apr 14 16:40:10 dom0 qubesd[2353]: KeyError: 'dom0'
```
</details>

However, there is still this quirk where qubes.xml appears to be saved twice two different ways.  That could create other issues.

**Comment by rustybird** [comment]
> However, there is still this quirk where qubes.xml appears to be saved twice two different ways.

I don't see `qubes.xml` being saved twice, but it looks like there's a bug in sorting dom0 relative to the other VMs: When dom0 - which is an AdminVM object but not a QubesVM object - more or less randomly happens be on the left side of an object comparison (with a QubesVM on the right side), it is [sorted first](https://github.com/QubesOS/qubes-core-admin/blob/v4.2.8/qubes/vm/adminvm.py#L85) as it should be; but when dom0 happens to be on the right side (QubesVM on the left), it is [sorted alphabetically](https://github.com/QubesOS/qubes-core-admin/blob/v4.2.8/qubes/vm/qubesvm.py#L961).

Your VM with a custom `keyboard_layout` probably has a name that alphabetically comes before dom0?

**Comment by tasket** [comment]
Yes, it comes before dom0. 

I wonder why its sometimes saved in alphabetical order, and sometimes not.  The latter only happens when the system crashes or degrades to the point of being unusable.

**Comment by tasket** [comment]
Well, I spoke too soon, because now qubes.xml domains are un-sorted.
