### ISSUE TITLE
4.1 rc1: Qubes Manager GUI offers "Disposable VM Template" for Template VMs but fails to apply/create/edit

### ISSUE THREAD

**Issue by rwiesbach** [QubesOS/qubes-issues#7001]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
4.1 rc1

### Brief summary
In 4.0, The "Advanced" Tab does not offer "Disposable VM Template" checkbox for TemplateVMs. In 4.1 it does, but failes with "Invalid Property" on apply or OK. Both templates (4.0 and 4.1) were unused templates during the test.

I am not sure what the intended behavior is - do dvm-template always need a TemplateVM as a basis or can dvm-templates be standalone? This is not clear to me, partly because the "new qube" wizard does not offer dvm-templates (but only templaes or dvms). This way or the other it is a bug, either to offer this option (which is not intended to be available) or to fulfill the corresponding change.

**Comment by alimirjamali** [comment]
I believe that this is already fixed in the PR for #7217

**Comment by rwiesbach** [comment]
If I understand correctly this will be fixed for Qubes 4.3 but not for 4.2, right?

**Comment by alimirjamali** [comment]
> If I understand correctly this will be fixed for Qubes 4.3 but not for 4.2, right?

Not necessarily. Some of new features will be only for Qubes r4.3. But many will be back-ported to r4.2. This might be one of those.
