### ISSUE TITLE
Due to deprecation of file-based pools, some of us need a ZFS qvm-pool backend

### ISSUE THREAD

**Issue by Rudd-O** [QubesOS/qubes-issues#7009]
### The problem you're addressing (if any)

Some of us use a file system that is not a stock Fedora file system, and are not willing to trust our data to other file systems.  In this particular case, we are talking about ZFS.

So far -- albeit complicated to use -- the file-based pool system has worked fine for us.  This is going to get deprecated in Qubes OS 4.1 and will be removed in the next release.

This leaves the abovementioned class of Qubes OS users without a solution that works to back our qubes with disk storage.

### The solution you'd like

I would like to see a ZFS-based qvm-pool backend, that preferably uses a tree of ZFS volumes arranged similarly to the LVM arrangement.  Cloning of VMs could be done extremely fast using ZFS snapshots and clones, and ephemeral file systems such as the root file system in standard AppVMs can also be supported in the same way.  Due to the way ZFS works, it is entirely likely that no loop devices or device-mapper mappings will need to be manipulated at all, which also means a gain in simplicity w.r.t. how the backend is implemented.

(Nota bene: this effort would be greatly helped by documentation on how to implement new storage drivers.)

### The value to a user, and who that user might be

The class of users is well-defined, although we understand that we are in a minority.

* Superior data reliability and trustworthiness.
* Higher performance, when combining rotational and solid storage devices (ARC / ZIL).
* Ability to perform snapshot sends and receives.
* Optionally, automatic snapshots for user-configurable revert of VMs to previous states.
* Given careful design, certain VMs may require an encryption key (particular to a specific ZFS volume) to boot.
* TRIM works by default and autotrim can be turned on -- all that is required from the VM itself is that `discard` is used as mount option.  Even in the case when this is not possible to arrange, filling the VM's disks with zeroes still causes an enormous disk space gain due to ZLE compression.

I would be willing to commit roughly 0.25 BTC to funding the work, contingent on the delivery of an optional driver -- installable as a package -- that I can test and verify myself, hopefully with the end goal of shepherding it into the main Qubes OS distribution at a later release.

Thanks in advance.

**Comment by tlaurion** [comment]
@andrewdavidwong bounty label should be added here, since @Rudd-O offered 0.25 BTC bounty here.

**Comment by tlaurion** [comment]
Also, it seems (from personal non-exhaustive research) that ZFS might be the only candidate we currently have to have pool-wide volumes reduplication (having qubes back up its advice to clone templates to specialize usage) without having exponential cost of storage with deployed software + in-place upgrades of fedora fast paced (annoying) release cycles.

**Comment by tlaurion** [comment]
@Rudd-O you saw https://github.com/QubesOS/qubes-core-admin/pull/289 ?

**Comment by Rudd-O** [comment]
> @andrewdavidwong bounty label should be added here, since @Rudd-O offered 0.25 BTC bounty here.

I will happily honor my offer if the funds are used to finance the developer time to finish the half-written ZFS pool driver.

**Comment by rustybird** [comment]
FYI, reflink support for ZFS also seems to be progressing nicely in [PR #13392](https://github.com/openzfs/zfs/pull/13392).

**Comment by ayakael** [comment]
Reflink support for ZFS is slated for release with OpenZFS 2.2. I've been using cfcs's work-in-progress ZFS driver, but this might make me drop it and use file-reflink directly.

**Comment by DemiMarie** [comment]
This pool has already been implemented, closing as fixed.

**Comment by Rudd-O** [comment]
> Reflink support for ZFS is slated for release with OpenZFS 2.2. I've been using cfcs's work-in-progress ZFS driver, but this might make me drop it and use file-reflink directly.

That's good news.

Do note that the ZFS driver being released with Qubes 4.2 lets you use ZFS snapshots to natively take care of your VM storage, supports send + receive, and of course will take advantage of ZFS encryption (if your system is set up to use it).

I have a backport of the driver for 4.1 here: https://repo.rudd-o.com/q4.1/packages/qubes-core-dom0-4.1.33.1-40.qbs4.1.noarch.rpm .  Do note upgrading your 4.1 system will result in this package being erased and you won't have a storage driver anymore.
