### ISSUE TITLE
qubes-dist-upgrade fails at stage 4

### ISSUE THREAD

**Issue by Rudd-O** [QubesOS/qubes-issues#7011]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

4.0

### Brief summary

Stage 4 fails with a `Status code: 404 for https://yum.qubes-os.org/r4.0/current/dom0/fc32/repodata/repomd.xml.metalink` in red color (this particular process is executing inside `sys-net`).

### Steps to reproduce

Just run `qubes-dist-upgrade --all` as root.

### Motivation

I'm doing all of this because the intention is to prepare all my Qubes OS utilities to work correctly with Qubes 4.1 before it is published.

**Comment by marmarek** [comment]
Fixed

**Comment by Rudd-O** [comment]
Fortunately I have two more Qubes OS machines in need of upgrade, so I will exercise my notes once again.
