### ISSUE TITLE
qubes.GetAppmenus can't find certain directory

### ISSUE THREAD

**Issue by Minimalist73** [QubesOS/qubes-issues#7025]
### Qubes OS release
4.1

### Brief summary
qubes.GetAppmenus can't find some directory, it throws errors when I install apps from apt

### Steps to reproduce
- Clean debian 11 template from repo 
- Testing repo enabled
- Install app with apt

### Expected behavior
Install the chosen app and set the .desktop entry

### Actual behavior
Install the app but throw errors like this:

```
Processing triggers for qubes-core-agent (4.1.27-1+deb11u1) ...
/etc/qubes-rpc/qubes.GetAppmenus: line 51: cd: /home/user/.local/share/applicati
ons: No such file or directory
/etc/qubes-rpc/qubes.GetAppmenus: line 51: cd: /usr/local/share//applications: N
o such file or directory
```

**Comment by DemiMarie** [comment]
This is actually harmless, but it would be better to not emit these errors.

**Comment by marmarek** [comment]
This is already fixed in https://github.com/QubesOS/qubes-core-agent-linux/pull/335
