### ISSUE TITLE
Use updates proxy by default even in non-template qubes

### ISSUE THREAD

**Issue by gangamstyle** [QubesOS/qubes-issues#7026]
I had an idea to enable updates proxy inside guests (not templates) and standalone vms, but rpc policy does not work.
I added this line in dom0 to /etc/qubes-rpc/policy/qubes.UpdatesProxy:
```
$tag:created-by-dom0 $default allow,target=sys-whonix
```
since all vms have this tag "ceated-by-dom0" it should work, bot it does not, any idea why?
I can create apt proxy manually and direct it to 10.137.255.254:8082 but that works only for standalone vms, not template based vms.

**Comment by unman** [comment]
On Fri, Oct 29, 2021 at 04:42:32PM -0700, gangamstyle wrote:
> I had an idea to enable updates proxy inside guests (not templates) and standalone vms, but rpc policy does not work.
> I added this line in dom0 to /etc/qubes-rpc/policy/qubes.UpdatesProxy:
> ```
> $tag:created-by-dom0 $default allow,target=sys-whonix
> ```
> since all vms have this tag "ceated-by-dom0" it should work, bot it does not, any idea why?
> I can create apt proxy manually and direct it to 10.137.255.254:8082 but that works only for standalone vms, not template based vms.
> 
> 
I suspect this is a support issue, which might be better dealt with in
the Forum or the mailing lists.
I dont think you are clear on what the policy does. Making an entry in
the policy file does not set up any qubes to use a proxy - that
is done by the relevant service. It sounds as if you think that the
policy creates the proxy entries.
You absolutely *can* create a proxy manually in the way you describe,
and it will work for template based qubes. Naturally, the proxy has to
be upstream of the calling qube.

**Comment by marmarek** [comment]
You may need to set `updates-proxy-setup` feature for VMs that should use the proxy. See https://www.qubes-os.org/doc/how-to-install-software/#updates-proxy

**Comment by gangamstyle** [comment]
@marmarek thanks, enabling updates-proxy-setup service creates related apt proxy file inside vm, and with my changes to /etc/qubes-rpc/policy/qubes.UpdatesProxy everything works fine!
I recommend adding this guide to documentation, this is important, or even make it default.

**Comment by andrewdavidwong** [comment]
> @marmarek thanks, enabling updates-proxy-setup service creates related apt proxy file inside vm, and with my changes to /etc/qubes-rpc/policy/qubes.UpdatesProxy everything works fine! I recommend adding this guide to documentation, this is important, or even make it default.

I've updated this issue in an attempt to capture what I understand to be your enhancement request.

To make it explicit, could you please explain why you think this should be the default?

**Comment by unman** [comment]
A better question might be "WHAT do you think should be the default?"
Unless you are using a caching proxy is there any benefit in using the
qrexec proxy system? What is it?

**Comment by gangamstyle** [comment]
Well, this should be default IF qubes user picked an option to route templates updates through sys-whonix (or any other connection).
Right now without my fix, with that option enabled, if user installs something inside vms or standalones using package manager, it downloads files through default (generally non sys-whonix) internet connection, this does not match the option and should be fixed.
I don't have many arguments, for me this problem is obvious.

BTW my old attempt to "direct it to 10.137.255.254:8082" failed, because it uses same network connection. RPC here is a must.

**Comment by unman** [comment]
On Tue, Nov 02, 2021 at 09:43:27AM -0700, gangamstyle wrote:
> Well, this should be default IF qubes user picked an option to route templates updates through sys-whonix (or any other connection).
> Right now without my fix, with that option enabled, if user installs something inside vms or standalones using package manager, it downloads files through default (generally non sys-whonix) internet connection, this does not match the option and should be fixed.
> I don't have many arguments, for me this problem is obvious.
> 
> BTW my old attempt to "direct it to 10.137.255.254:8082" failed, because it uses same network connection. RPC here is a must.

I must be missing something.
If you are running the qube through sys-whonix then the package
operations (install/updates), will go through Tor.
If you are not running through sys-whonix, why are you concerned about
package operations going through Tor when all your other operations
don't go through Tor?

I just don't understand your final comment about "the same network
connection". Unless this is some Whonix thing.

**Comment by andrewdavidwong** [comment]
> Well, this should be default IF qubes user picked an option to route **templates** updates through sys-whonix (or any other connection).

Notice that the option is to route **template** updates through `sys-whonix`. If you perform an update in a non-template qube, it should not be expected that the update will routed through `sys-whonix`, unless that qube happens to have `sys-whonix` as its net qube.

> Right now without my fix, with that option enabled, if user installs something inside vms or standalones using package manager, it downloads files through default (generally non sys-whonix) internet connection, this does not match the option and should be fixed. I don't have many arguments, for me this problem is obvious.

It sounds like you're assuming that the option means "route **all** updates through `sys-whonix`" when, in reality, it says "route **template** updates through `sys-whonix`." Given what the option actually says, the behavior your describe is **not** inconsistent with the option. All **template** updates *are* being routed through `sys-whonix`. However, your are also performing some updates in **non-templates** that are not being routed through `sys-whonix`.

**Comment by marmarek** [comment]
Updates proxy is a way to allow _only_ package manager to access the network. We use it as an alternative to normal network interface in templates, to cut of other applications from the network - as in: templates do not have other network access besides the updates proxy. This avoids mistakes like accidentally opening some website in a template.
@unman is right on point. Connecting a single qube to _both_ clearnet (via normal netvm setting) and Tor (via updates proxy) is a rather weird configuration, and generally negates benefits from using Tor - since it can be correlated via clearnet traffic. In extreme case, it may even harm other qubes using the same updates proxy. While technically possible, it's a bad idea to do it.
So, if you want a qube to access the network via Tor: do just that (you also have an easy way to do that globally if you like: set `sys-whonix` as default net qube). Doing it partially doesn't make sense.
