### ISSUE TITLE
Cannot start any vms after recent update

### ISSUE THREAD

**Issue by 0spinboson** [QubesOS/qubes-issues#7029]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

4.1,current testing

### Brief summary

After installing the most recent updates from current testing, I got this: 
![IMG_20211031_133609.jpg](https://user-images.githubusercontent.com/21077532/139592205-0637b7bc-c8d2-4645-9c4e-92991b65b882.jpg)
When trying to boot a qube. 

### Steps to reproduce

downgrading these resolved the problem for me. I have not yet tried reinstalling the updates one by one to figure out which is the problem, have a few deadlines I need to meet. 
![IMG_20211031_134218.jpg](https://user-images.githubusercontent.com/21077532/139592177-b242457c-6946-40e5-a82e-4f2c7fbbf575.jpg)

**Comment by marmarek** [comment]
You need to update your `xen-user.xml` libvirt config - there is no `script` attribute anymore.

**Comment by 0spinboson** [comment]
Aha, thanks once again. solved
