### ISSUE TITLE
qvm-open-in-dvm tries to start the disposable twice

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#7031]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

R4.1

### Brief summary

When the disposable qube start fails (for example not enough memory), `qvm-open-in-dvm` (or rather: qrexec handling the request at dom0 side) tries to start the disposable twice.

This is likely an interaction with qrexec-policy-daemon and a fallback to qrexec-policy-exec.

### Steps to reproduce

1. Have not enough memory
2. Try to open a file in a disposable qube

### Expected behavior

The call fails after trying to start the disposable once

### Actual behavior

It tries to start it twice.

**Comment by rustybird** [comment]
In case it helps with the diagnosis: Before #7023 ('VM killed with "out of PoD memory" error') was fixed, I noticed the same 2 attempts to start a VM - but here it was in R4.0 when running `qubes.StartApp` (and IIRC `qubes.VMShell` too), for any type of VM, initiated by dom0.
