### ISSUE TITLE
new menu: switching group in a "system tools" section via keyboard does not update list of apps

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#7036]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

R4.1+

### Brief summary

Navigating system tools section via keyboard does not update the apps list. Navigating with mouse works.

### Steps to reproduce

1. Switch to system tools section
2. Navigate with up/down keys

### Expected behavior

Apps list on the right update

### Actual behavior

It doesn't.

**Comment by andrewdavidwong** [comment]
I suggest we either change the milestone or the issue type, since it does not really make sense to have a bug assigned to 4.2. (This would mean that we intend to introduce this bug in 4.2.) If what we mean here is that we plan to address this in 4.2 (and not earlier), then I suggest reclassifying it from a bug to an enhancement. Any objections?

**Comment by marmarek** [comment]
> This would mean that we intend to introduce this bug in 4.2.

We kind of already did ;) The new app menu is a feature for 4.2. It is just implemented ahead of 4.2 schedule.
I thought it would be weird to have a bug with 4.1 milestone for a package that isn't part of standard 4.1 (but possible to install there nonetheless). But maybe that isn't a problem?

**Comment by andrewdavidwong** [comment]
> > This would mean that we intend to introduce this bug in 4.2.
> 
> We kind of already did ;) The new app menu is a feature for 4.2. It is just implemented ahead of 4.2 schedule. I thought it would be weird to have a bug with 4.1 milestone for a package that isn't part of standard 4.1 (but possible to install there nonetheless). But maybe that isn't a problem?

Ah, I see. So it's a bit of an unusual situation. In this case, I think your milestone and labels are fine. Never mind. :)
