### ISSUE TITLE
Qube VM Settings allows checking invalid properties

### ISSUE THREAD

**Issue by ydirson** [QubesOS/qubes-issues#7037]
### Qubes OS release

4.1rc1

### Brief summary

In Qube VM Settings for a TemplateVM, I can check "Disposable VM Template", and on Apply I just get an "Invalid property 'template_for_dispvms'" error message.

### Expected behavior

TemplateVMs do not seem to exhibit this property, probably it that checkbox should be greyed out.

I did not make a thorough investigation, possibly other properties have the same issue.

**Comment by alimirjamali** [comment]
> I did not make a thorough investigation, possibly other properties have the same issue.

The above line makes this issue a little bit different from #7217

Most invalid settings are not critical. Examples are `Include in backups by default`, `Start qube automatically on boot`, `Provides network` for DisposableVMs.
