### ISSUE TITLE
Default UsbVM setup by installer

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#704]
**Reported by joanna on 8 Feb 2013 18:45 UTC**
The goal is that a default Qubes installation has no USB controllers assigned to Dom0. This would prevent lots of USB attacks, as discussed in this article:

http://theinvisiblethings.blogspot.com/2011/06/usb-security-challenges.html
Two requirements:

1) PVUSB should work (#531)
2) Keyboard/Mouse should not use USB (typically they don't on most laptops)

Migrated-From: https://wiki.qubes-os.org/ticket/704

**Comment by v6ak** [comment]
I am in favor of making it optional, although the installer might ask the user. Rationale: Assume you install Qubes on a computer without a PS/2 keyboard.

An advanced solution for such case might be chosing a particular trusted USB controller connected to dom0 (e.g. for keyboard) and connecting the others to usbvm. But this should be IMO just *possible*, not necessarily easy for wide range of users.
