### ISSUE TITLE
4.1rc1 Create Qubes VM menu option does not copy features from template to AppVM during creation.

### ISSUE THREAD

**Issue by brendanhoar** [QubesOS/qubes-issues#7042]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
R4.1rc1

### Brief summary
"Menu"/"Qubes Tools"/"Create Qubes VM" does not copy features values from template to AppVM 

### Steps to reproduce
1. Create a Windows VM template using @elliotlkillick's qvm-create-windows-qube process.
2. The following features are enabled are set when complete: os=Windows; rpc-clipboard=1;qrexec=1;gui=<blank>;gui-emulated=1.
3. Invoke "Menu"/"Qubes Tools"/"Create Qubes VM"
4. Give a name.
5. Select AppVM.
6. Select correct source template created in 1 above.
7. Press OK.

### Expected behavior
qvm-features AppVM returns the same data as the templateVM

### Actual behavior
qvm-features AppVM returns no data.

**Comment by marmarek** [comment]
> ### Expected behavior
> 
> qvm-features AppVM returns the same data as the templateVM

No, it should not. Features directly on an AppVM are only those that are _overriding_ those from its template. Places where it makes sense consider a feature on an AppVM and fallback to a value from a template.
