### ISSUE TITLE
A single bad policy breaks the whole system

### ISSUE THREAD

**Issue by SaswatPadhi** [QubesOS/qubes-issues#7043]
### Qubes OS release
R4.1

### Brief summary
A single bad policy file in Dom0 breaks all policy checks, i.e. all policies for unrelated RPC calls and renders the whole system essentially unusable.

### Steps to reproduce
1. Create an invalid policy file in Dom0, something like `/etc/qubes-rpc/policy/xxx` containing `abc` would suffice.<sup>#</sup>
2. Try any RPC operation, e.g. FileCopy across VMs, update checks on VMs etc.
3. :-(

<sup>#</sup> A more realistic "mistake" that I just did was the following policy:
```
vm_a vm_b allow,default_target=vm_b
```
The mistake here is that `default_target` is not compatible with `allow` (only with `ask`, which I previously had).

### Expected behavior

Only the RPC call relevant to the particular policy should break.

### Actual behavior

ALL RPC calls across Qubes OS are broken.

**Comment by DemiMarie** [comment]
This is going to be tricky to fix.  In the future there will be an API to alter qrexec policy, which will only allow the creation of valid policies.

**Comment by SaswatPadhi** [comment]
Thanks @DemiMarie.

In the meantime, could the error message be perhaps refined? Could internal "errors" be made distinguishable from a "refusals" due to policy violation?

**Comment by ben-grande** [comment]
> In the meantime, could the error message be perhaps refined? Could internal "errors" be made distinguishable from a "refusals" due to policy violation?

Seems already fixed R4.1.

```
qrexec: qubes.GetDate: source -> @default: error loading policy: /etc/qubes-rpc/policy/qubes.GetDate:1: invalid parameters for action Allow: ['default_target=something']
```

> Right now, a single broken policy file results in all RPC calls being "refused" which is a bit misleading.

Intentional behavior.
