### ISSUE TITLE
Installation Destination shows only 1 of 7 drives

### ISSUE THREAD

**Issue by steakknife** [QubesOS/qubes-issues#7047]
### Qubes OS release

R4.1.0rc1 

### Brief summary

Only one device, nvme0n1, appears in Installation Destination.

- Motherboard: H11DSi (both CPU sockets populated with EPYC "Rome" 7002 processors)
- /dev/nvme0n1: Intel Optane SSD 905P Series 380GB PCIe x4 (SSDPEL1D380GA)
- /dev/nvme1n1: Segate FireCuda 520 2 TB PCIe x4 (ZP2000GM30002)
- /dev/nvme2n1: Segate FireCuda 520 1 TB PCIe x4 (ZP1000GM30002)
- /dev/sda: WDC 14 TB Ultrastar DC HC530 (WUH721414AL)
- /dev/sdb: WDC 14 TB Ultrastar DC HC530 (WUH721414AL)
- /dev/sdc: WDC 14 TB Ultrastar DC HC530 (WUH721414AL)
- /dev/sdd: WDC 14 TB Ultrastar DC HC530 (WUH721414AL)

### Steps to reproduce

1. Boot Qubes from USB.
2. Choose defaults until the last screen before installation.
3. Choose System > Installation Destination.

### Expected behavior

1. All 3 NVMe drives and 4 SATA/SAS drives should appear. CentOS 8.4 shows 3 SSDs and 4 SATA HDDs in the installer, which is correct.

### Actual behavior

1. Only the Intel nvme0n1 device appears in the UI.
2. All drives are detected correctly by Qube's underlying Linux, are online, and readable as block devices.

**Comment by marmarek** [comment]
> All drives are detected correctly by Linux, online, and readable as block devices.

Do you mean system where installer is running, or some other Linux? Can you share `/tmp/storage.log` from within the installer (you can access console via ctrl+alt+F2). Note, it will contain information on partitions, volumes etc present on all the disks - if any of this is sensitive, review the file first.

**Comment by steakknife** [comment]
Within Qubes: the OS detects all the drives (Ctrl-Alt-F3 over to another console and run `fdisk -l`), but the installer doesn't display them. CentOS installer DOES show them.

Qubes logs:
- [anaconda.log](https://gist.github.com/steakknife/f21d407db121c93cda6cdc278933ead3/raw/cc4bc926ceebaa3b487b0a81a87ae3304495c01b/anaconda.log)
- [storage.log](https://gist.github.com/steakknife/f21d407db121c93cda6cdc278933ead3/raw/cc4bc926ceebaa3b487b0a81a87ae3304495c01b/storage.log)
- [syslog](https://gist.github.com/steakknife/f21d407db121c93cda6cdc278933ead3/raw/cc4bc926ceebaa3b487b0a81a87ae3304495c01b/syslog)

**Comment by steakknife** [comment]
Hang on. After further research, the issue appears all drives are detected by the installer, but the installer GUI lacks affordances (indications of possibilities) that there are other drives. When in VGA video mode over the BMC, other disks can be completely hidden to the RIGHT of the first listed disk.

**Comment by marmarek** [comment]
Can you confirm just nvme0n1 is listed in the _first_ disk selection UI (like this one: https://openqa.qubes-os.org/tests/24101#step/install_partitioning_default/4)? The check mark on each disk is to select which will be available in the next step. By cursory look on the logs, I don't see anything wrong...

**Comment by steakknife** [comment]
Storage is working, however the UI has a nonfunctional UX problem under certain circumstances (low resolution displays).
