### ISSUE TITLE
Canceling an update via the GUI will freeze the updater until the update is complete

### ISSUE THREAD

**Issue by AlxHnr** [QubesOS/qubes-issues#7049]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

Qubes 4.0 (R4.0)

### Brief summary

When updating a template, clicking _cancel_ or closing the window will show a popup `Cancelling remaining updates` and freeze. But the update will proceed. The window closes immediately when the update is done.

### Steps to reproduce

1. Start `Qubes Update`
2. Select `Enable updates for qubes without known available updates`
3. Select a template of your choice
4. Click `next`
5. Try to close the updater

### Expected behavior

Either one of the following should happen:
* The Update stops within seconds and leaves the template like it was before
* The GUI is honest and says `Can't be stopped!`

### Actual behavior

The GUI freezes and the shown popup is useless.

**Comment by marmarta** [comment]
Currently truly cancelling updates is not easy, so I updated the message to be more, well, true. I hope once qubes update mechanism gets a bit smarter we will be able to truly cancel updates in the middle.

**Comment by DemiMarie** [comment]
> Currently truly cancelling updates is not easy, so I updated the message to be more, well, true. I hope once qubes update mechanism gets a bit smarter we will be able to truly cancel updates in the middle.

This requires #6661, so that cancelling an update does not leave the qube in an inconsistent state.
