### ISSUE TITLE
CoC probable link rot for Citizen Code of Conduct

### ISSUE THREAD

**Issue by steakknife** [QubesOS/qubes-issues#7050]
### Brief summary

[citizencodeofconduct.org](http://citizencodeofconduct.org) is down currently (DFEOJM: [http](https://downforeveryoneorjustme.com/citizencodeofconduct.org?proto=http) and [https](https://downforeveryoneorjustme.com/citizencodeofconduct.org?proto=https)) but still registered.

`Registry Expiration: 2022-07-28 18:06:14 UTC`

**Comment by andrewdavidwong** [comment]
Thanks for letting us know. I found the source for the (now dead) link on GitHub:

https://github.com/stumpsyn/policies/blob/master/citizen_code_of_conduct.md

I'll replace the dead link with this one.
