### ISSUE TITLE
Qualcomm Atheros QCA9377 Wireless Network Adaptor (rev 31) supported by Fedora 34 sys-net but not Debian 11

### ISSUE THREAD

**Issue by rlew-metastability** [QubesOS/qubes-issues#7053]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
4.1-RC1

### Brief summary
Initializing the Qubes-OS-4.1-RC1 installation with a default Fedora 34 template results in a sys-net Qube that supports the Atheros QCS9377.   However, initializing the Qubes-OS-4.1-RC1 installation with a default Debian 11 template results in a sys-net Qube that does not support the same wireless networking device.

Neither the Fedora nor the Debian templates result in a sys-net Qube that supports the wired Ethernet Atheros E2400 device.

### Steps to reproduce
Install Qubes-4.1-RC1; select Fedora 34 during initial system configuration; Observe Atheros QCS9377 functioning and able to connect to available wireless networks.

Reinstall Qubes-4.1-RC1 and then select Debian 11 as the default template.  Observe that QCS9377 wireless networking device is not recognized.  The Atheros E2400 wired Ethernet device is not recognized either.  Not that this results in a non-networked computer (if using a stock Dell XPS 8930) that cannot update software or install binary blobs to enable networking.

### Expected behavior
Both Debian and Fedora templates should provide functioning Ethernet networking.

### Actual behavior
Only the Debian 34 template provides working WiFi networking.  Wired networking does not work with either template.

**Comment by nikkus** [comment]
for the adapter:
Network controller: Qualcomm Atheros QCA9377 802.11ac Wireless Network Adapter (rev 30)

In RC1:
QubesOS I can "see" this adapter. after try a lot of trys, finally, I can connect to wifi.. BUT, no one domain can get internet connection.

In RC2:
QubesOS detect this adapter, but doesn't see any wifi.

**Comment by DemiMarie** [comment]
My understanding (which could be incorrect) is that Fedora includes non-free firmware by default, while Debian does not.  Could that be the cause?

**Comment by nikkus** [comment]
I don't think so... In my case, my "default domain" is setting to be a Debian-11, after this problem I try with Fedora, but with the same issue.. :(
