### ISSUE TITLE
New Qubes application menu does not reflect VM state change

### ISSUE THREAD

**Issue by GWeck** [QubesOS/qubes-issues#7058]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
R4.1 with unstable repository and new Qubes application menu installed

### Brief summary
If the number of VMs changes due to creation / destruction of a dispvm, or the state of a VM changes due to start or shutdown, this change is not displayed in the new menu VM list. Even when switching between panes or displaying the menu once again, the old state is displayed. The state change is only displayed when the menu is restarted via the `qubes-app-menu --restart` command.

### Steps to reproduce
Start a new dispvm or start / shutdown a qube and observe the VM list displayed in the new application menu.

### Expected behavior
The menu should show the updated list of qubes.

### Actual behavior
The menu shows the unchanged list until it is restarted.

### Additional information
It would be helpful, if the `--restart` option could be included in the XFCE launcher used to start the new menu.

**Comment by andrewdavidwong** [comment]
FYI @marmarta, @ninavizz

**Comment by GWeck** [comment]
In Qubes R4.2, the new app menu does not show newly created dispVMs.
