### ISSUE TITLE
New Qubes application menu should follow the selected desktop style

### ISSUE THREAD

**Issue by GWeck** [QubesOS/qubes-issues#7059]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### The problem you're addressing (if any)
Currently, the new Qubes application menu is displayed in a fixed, dark-theme style, which cannot be changed. Also, the location of the menu is determined a its start, somewhat randomly, and cannot be changed by dragginbg it to some other place.

### The solution you'd like
The menu should be displayed in the style selected for other desktop elements like the qube manager, application windows or such, and it should be possible to drag it around by holding the title bar.

### The value to a user, and who that user might be
This would provide a more consistent look and handling for any user, especially when not using a dark theme for the rest of the desktop.

**Comment by ninavizz** [comment]
@GWeck Heya! Yep, we are on it. We wanted to get it "built" first, then into the wild—then begin refinements. 

1. A "light" theme is next-up on our list, and I'm scrambling to finish the specs to hand off to @marmarta (who has been nagging me for those for several weeks). 
2. The location is another issue to tackle; and I don't know where that is in our priorities. I'll add this flag to our Project here, though!

**Comment by GWeck** [comment]
Perhaps you could use the desktop interface used by the Whiskers menu? Just an idea ...

**Comment by GWeck** [comment]
Under R4.2, the layout of the new app menu still does not follow the selected desktop design.

**Comment by GWeck** [comment]
Works like a charm! Thanks a lot!!!
