### ISSUE TITLE
HVM with kernel with empty `kernel` pref fails to start "exceeding maximum recursion level"

### ISSUE THREAD

**Issue by ydirson** [QubesOS/qubes-issues#7061]
### Qubes OS release

4.1rc1

### Brief summary

(hoping it would result in the HVM "booting from HDD") I set `qvm-prefs sys-usb kernel ""` (or equivalently select `(none)` in Qubes Manager).  Now starting this `sys-usb` results in endless nested exception getting killed by python:

```
Nov 14 20:54:03 dom0 qubesd[2156]: unhandled exception while calling src=b'dom0' meth=b'admin.vm.Start' dest=b'sys-usb' arg=b'' len(untrusted_payload)=0
Nov 14 20:54:03 dom0 qubesd[2156]: Traceback (most recent call last):
Nov 14 20:54:03 dom0 qubesd[2156]:   File "/usr/lib/python3.8/site-packages/qubes/__init__.py", line 227, in __get__
Nov 14 20:54:03 dom0 qubesd[2156]:     return getattr(instance, self._attr_name)
Nov 14 20:54:03 dom0 qubesd[2156]: AttributeError: 'AppVM' object has no attribute '_qubesprop_keyboard_layout'
Nov 14 20:54:03 dom0 qubesd[2156]: During handling of the above exception, another exception occurred:
Nov 14 20:54:03 dom0 qubesd[2156]: Traceback (most recent call last):
Nov 14 20:54:03 dom0 qubesd[2156]:   File "/usr/lib/python3.8/site-packages/qubes/__init__.py", line 227, in __get__
Nov 14 20:54:03 dom0 qubesd[2156]:     return getattr(instance, self._attr_name)
Nov 14 20:54:03 dom0 qubesd[2156]: AttributeError: 'AppVM' object has no attribute '_qubesprop_keyboard_layout'
...
```

I'm not really sure that what I expected would happen, but as a used-exposed feature available in the GUI the actual behaviour is probably not the expected one :)

**Comment by ydirson** [comment]
Hm, probably invalid and linked to some local code changes (although the link is still weak...)

**Comment by marmarek** [comment]
Does your `sys-usb` have `guivm` set to none too?

**Comment by ydirson** [comment]
@marmarek no it was still at default value... which happened to be non-working sys-gui-gpu.  I likely left my machine with it activated (as per my [salt recipe](https://forum.qubes-os.org/t/salt-recipes-for-easier-switching-sys-gui-gpu-on-off/6644)), and naturally later assumed it was off.  Embarrassing :)

**Comment by DemiMarie** [comment]
Feel free to reopen if the bug turns out to be in Qubes OS.

**Comment by ydirson** [comment]
There is likely something in the code that allows for this infinite recursion, it's maybe just happening in pathological configurations. Would still have to reproduce with unpatched xen+stubdom to be sure :)

**Comment by DemiMarie** [comment]
> There is likely something in the code that allows for this infinite recursion, it's maybe just happening in pathological configurations. Would still have to reproduce with unpatched xen+stubdom to be sure :)

I don’t really see how Xen + stubdom changes could cause this.
