### ISSUE TITLE
Installing Fedora template should create dispVM

### ISSUE THREAD

**Issue by straussmaus** [QubesOS/qubes-issues#7063]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

4.0 (updated)

### Brief summary

When installing a new Fedora template, a dispvm template should be installed with it.  This is labeled bug not enhancement because of the nature of dispVMs.

### Expected behavior

Install Fedora34 template.  Fresh dispVM template is available, as when you first install Qubes.

### Actual behavior

Install Fedora34 template.  Now you have to manually create a dispVM template.

Here is the reasoning for calling this a bug not an Enhancement request:

the nature of the disposable VM is to be identical to all other disp VMs not only on the user's system but on all users' systems.  Therefore it must be generated centrally.  But it is not, so the purpose of disp VMs is broken with updated Fedora templates, therefore bug.  At least this is my reasoning.

**Comment by andrewdavidwong** [comment]
> the nature of the disposable VM is to be identical to all other disp VMs not only on the user's system but on all users' systems. Therefore it must be generated centrally. But it is not, so the purpose of disp VMs is broken with updated Fedora templates, therefore bug. At least this is my reasoning.

No, this is a misguided expectation. The nature of a disposable is simply to self-destruct when shut down (currently, when the original window closes). That's it. Any other properties are ones you're mentally importing.

**Comment by andrewdavidwong** [comment]
Please read this:

https://www.qubes-os.org/faq/#what-about-privacy-in-non-whonix-qubes

> The main way Qubes OS provides privacy is via its integration with Whonix. Qubes OS does not claim to provide special privacy (as opposed to security) properties in non-Whonix qubes. **This includes disposables.**
> 
> For example, a standard Fedora qube is expected to have basically the same privacy properties as that upstream Fedora distribution, enhanced to some degree by the control Qubes provides over that qube. For most users, this level of privacy may be good enough for many common activities. However, users seeking more advanced privacy features should use Whonix qubes.
> 
> Privacy is far more difficult than is commonly understood. In addition to the web browser, there is also VM fingerprinting and advanced deanonymization attacks that most users have never considered (and this is just to mention a few examples). The Whonix Project specializes in protecting against these risks.
> 
> In order to achieve the same results in non-Whonix qubes (**including disposables**), one would have to reinvent Whonix. Such duplication of effort makes no sense when Whonix already exists and is already integrated into Qubes OS.
> 
> Therefore, when you need privacy, you should use Whonix qubes. Remember, though, that privacy is difficult to achieve and maintain. Whonix is a powerful tool, but no tool is perfect. Read the documentation thoroughly and exercise care when using it.
> 

-----

Also:

> Here is the reasoning for calling this a bug not an Enhancement request: [...]

This would still be an enhancement request, because you are asking for new functionality to be created and added (namely, automatic disposable template creation upon template installation). It does not matter that you think this functionality should already exist and doesn't.

**Comment by unman** [comment]
As it stands at present disposables are *not* based on templates - until #6720
is implemented, (if it is), then installing a template should have no
bearing on what disposables are present.

If the suggestion is that when installing a template a qube based on
that template should be created and configured as a disposable template,
I understand the reasoning, but am concerned by the scope.
If there were only one template, I could follow the logic - but
there isn't.

When installing a new template I may want it for a specific use - I would
not want arbitrary disposables created automatically. So how to decide
which templates *should* have disposable templates created and which not?

In 4.1 there is the option to choose which template should be installed.
I'm not aware that that choice is tracked.
