### ISSUE TITLE
Upgraded Debian 10-11 Standalone Fails to Open

### ISSUE THREAD

**Issue by straussmaus** [QubesOS/qubes-issues#7065]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

4.0 (updated)

### Brief summary
During the "Install" portion of the upgrade from buster-bullseye, a standalone qube shuts down and will no open apps again.

### Steps to reproduce

Have a standalone qube

change sources.list, apt update, apt dist-upgrade

### Expected behavior

Qube should boot to Debian 11

### Actual behavior

during package install, it quits (not sure what package)

Qube is not shut down, so I connected via dispVM and ran dpkg -a --configure and install finished

Now qube fails to boot.

`/var/log/xen/console/guest-Qubename.log` shows that it stops on one of many `A start job is running for Network ...nager Wait Online (52s / no limit)`

A few lines earlier there is:

`proc: Bad value for hidepid`

(Not a duplicate of https://github.com/QubesOS/qubes-issues/issues/6973)

**Comment by DemiMarie** [comment]
> `proc: Bad value for hidepid`

I believe this is not actually relevant.

**Comment by straussmaus** [comment]
> I believe this is not actually relevant.

That was my assumption also but it was the only complaint in the log that was close to the shutdown point so I added it just in case.  So that suggests it's the network?

**Comment by straussmaus** [comment]
Okay the problem was that I did not update the qubes sources in /etc/apt/sources.list.d/qubessomething before running dist-upgrade.  Or at least, when I did do this and attempted a fresh upgrade on a clone of the qube from before the failed upgrade, it worked.
