### ISSUE TITLE
Qubes OS on Lemp10 does not suspend properly

### ISSUE THREAD

**Issue by TheDarkTrumpet** [QubesOS/qubes-issues#7069]
### Qubes OS release

4.1rc1 - latest standard kernel

### Brief summary

This is largely out of the box, but if you install Qubes 4.1rc1 on the Lemp 10 (System76), and try and put the machine to sleep either by closing the lid, pressing the power button and selecting sleep, or through the menu, the machine does not sleep properly.

What happens instead is the screen will turn off, but hitting a key and/or waking through tapping the power button, does not allow the system to turn back on again.  I hear no fans or anything in the background, but am also not entirely sure it's hitting a sleep state at all anyways.

All packages/updates have been applied to 4.1 as of yesterday.  Testing was done over two installs (fresh install and one with updates applied), and tested multiple times when the machine is up.  The only remedy is to hold the power button to force shut off the machine.  I haven't found much in the logs surrounding what's happening.

### Steps to reproduce

Select "sleep" from the menu options within xfce, or shut the lid when lid close = sleep.

### Expected behavior

The machine properly goes to sleep, and can wake from that sleep.

### Actual behavior

The machine (appears, but not 100% sure) to sleep, but never wakes.

### Edit (Extra Testing)

Installed `kernel-latest` and tried it there, same behavior.  To rule out firmware being an issue, I also booted into Pop-OS and tried suspend there.  That worked.  Rebooted into Qubes, put to sleep and left it sit for while (~5m to ensure it fully attempted to sleep).  Saw the screen blank, then appear to come on (black screen), then blank again during the process.  Still won't wake.

**Comment by TheDarkTrumpet** [comment]
I should also add, that I'm testing qubes more than totally using it as a day to day machine til 4.1 fully gets released.  So if there are things that can help in aiding debugging, or testing, I'm willing to do anything to help.

**Comment by marmarek** [comment]
This looks exactly like #6411

**Comment by TheDarkTrumpet** [comment]
You're right, thanks.  I spoke with some at s76, and it really appears to be a xen issue that I'm not going to get around very easily.  I'll comment on the other ticket if I come up with anything new.  From the way tcrawford sounded, S3 is somehow working on some other chips in this class, but he's not sure how they're doing it.  Also saw there's some efforts to move away from xen and the like, so these may help some.

Thanks for pointing out that other ticket, I'll close this one.
