### ISSUE TITLE
qubes-desktop-linux-common dependency not provided for Fedora 33

### ISSUE THREAD

**Issue by Zerophase** [QubesOS/qubes-issues#7070]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

4.0

### Brief summary

Installing qubes-desktop-linux-common fails the install process with `nothing provides qubes-manager needed by qubes-desktop-linux-common-4.0.21-1.fc33.noarch`

### Steps to reproduce

Run `dnf install qubes-desktop-linux-common` from a minimal template.

### Expected behavior

qubes-desktop-linux-common pulls down the package for qubes-manager and installs.

### Actual behavior

command fails.

**Comment by marmarek** [comment]
Hmm, I think `qubes-desktop-linux-common` should not even be available to install in a VM (in R4.0). What are you trying to install it for?

**Comment by Zerophase** [comment]
I'm trying to install it in a minimal fedora qube. Trying to get web camera support working, and `qubes-desktop-linux-common` sounds like it might have the files needed.

**Comment by marmarek** [comment]
Nope, that package contains basic files for desktop environment (menu, desktop links etc). Something that in R4.0 is running in dom0 only.

**Comment by Zerophase** [comment]
Have any idea what I would need to add for web camera support?

**Comment by marmarek** [comment]
I'm not sure what problem you see, but the place for discussing it is either a qubes-users mailing list of a forum, see https://www.qubes-os.org/support/
