### ISSUE TITLE
Setting VM properties via salt qvm-present does nothing

### ISSUE THREAD

**Issue by 3hhh** [QubesOS/qubes-issues#7071]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

4.1rc1 with testing enabled

### Brief summary

salt state:
```
testing:
  qvm-present:
    - name: some-vm
    - class: AppVM
    - template: some-template
    - label: red
```

fails to apply a new template, if the VM already exists.

### Steps to reproduce

1. Create `some-vm` with a template `some-other-template`.
2. Run the aforementioned salt state.
3. Notice that `some-vm` still has `some-other-template` instead of `some-template`.

### Expected behavior

`qvm-present` means that the VM is present with the given properties as it's the default for all salt states.
Target states do not depend on preconditions.

### Actual behavior

`qvm-present` apparently means that the VM is present with any properties.
Target state depends on preconditions.

**Comment by unman** [comment]
Your expectation is misplaced, and you failed to report the comment in
the result.
The `qvm.present` state ensures that the qube exists - *not* that
the qube exists with some specific features.

To change template use qvm.prefs

> Target states do not depend on preconditions.
Many states depend on preconditions - I must be missing your point.

**Comment by 3hhh** [comment]
On 11/18/21 12:46 AM, unman wrote:
> Your expectation is misplaced, and you failed to report the comment in
> the result.
> The `qvm.present` state ensures that the qube exists - *not* that
> the qube exists with some specific features.
> 
> To change template use qvm.prefs

Salt states should generally be idempotent, i.e. as [salt puts it](https://docs.saltproject.io/en/latest/glossary.html): They should "ensure the system is in a well-known state _regardless_ of the system's state _before_ the action is applied." I guess that's why they call them "states" after all.

Since `qvm.present` depends on preconditions it is obviously not idempotent. So I could just run `cmd.run` on `qvm-create` instead. What's the added value of that state then?

> Many states depend on preconditions [..].

That may be fine, if they fail on unmet preconditions (e.g. `qvm.prefs` not finding the VM), but less so if that makes them non-idempotent.

**Comment by unman** [comment]
You haven't explained why you think qvm.present is *not* idempotent - it
surely is. 
You seem to think that qvm.present means - ensure a qube with these
characteristics exists. It doesn't.
It means: ensure that a qube with this name exists - if it doesn't,
create it with these characteristics.
If you don't know what qubes you have on your system there is the useful
qvm.exists state - this will return True or False, and it will not create a
qube if one does not exist.

As an aside, I have never seen a user complaining that qvm-create cant
be used to change a template, although the case is exactly analogous.
qvm.present is just the wrong tool for the job.

You can use cmd.run for almost any state - you could replace almost all
the file states with calls to cmd.run.

**Comment by 3hhh** [comment]
The whole point of salt is that it's different from cmd-line usage. Stating that it's the same for Qubes states indicates that the overall Qubes salt state design is somewhat botched.

Anyway I don't think we'll align on a common understanding and considering that you're the Qubes salt maintainer I don't think we'll see a way forward on this one any time soon.

So closing this one as unresolved.

**Comment by lkubb** [comment]
Tbh this behavior surprised me as well and does not seem to fit usual salt practices. Analogous example from the [salt docs](https://docs.saltproject.io/en/latest/ref/states/all/salt.states.user.html):
`user.present`
> Ensure that the named user is present **with the specified properties**

**Comment by unman** [comment]
On Sat, Nov 20, 2021 at 01:08:00AM -0800, 3hhh wrote:
> The whole point of salt is that it's different from cmd-line usage. Stating that it's the same for Qubes states indicates that the overall Qubes salt state design is somewhat botched.
> 
> Anyway I don't think we'll align on a common understanding and considering that you're the Qubes salt maintainer I don't think we'll see a way forward on this one any time soon.
> 
> So closing this one as unresolved.
> 

I'm not saying that the Qubes states are no different from cmd-line
usage - I'm saying that *many* salt states can be cast as cmd-line,
which I thought was your complaint.

I'm not the Qubes salt maintainer - I just seem to use and promote it
more than anyone else.
It may be that I'm just familiar with the current use, and so don't see
a point in changing it. It seems natural to me (and those I work with)
to have a separate state to manage preferences.
qubes are far more than just "name+preferences" - so it would seem that
you should want a state that provides
name+preferences+features+installed_software+configured_software:
nothing wrong with that, but it would be unwieldy in a way that
the current state separation isn't. If you *don't* think that would be
required, I'd be interested to hear your arguments.
(Currently that's best done with a state tree.)

It shouldn't be difficult to change the logic in the state - I will try
it and see how it works. 
As always, PRs are welcome, if anyone has time.

**Comment by 3hhh** [comment]
Yes, the proper design from my point of view would have been either

a) Deprecate qvm.prefs and make qvm.present include all qvm.prefs options.
b) Make qvm.present enforce its 3-4 preferences and/or make it fail when it cannot enforce them.
c) Remove the non-idempotent options from qvm.present and create some "default VM" (default template and red label or so) if it doesn't exist and otherwise be happy when some VM with the given name (and possibly type) exists.

Probably a) would be the cleanest as qvm.prefs doesn't make sense anyway without a VM being present.

**Comment by unman** [comment]
You haven't addressed the question I raised of features, software, and (I forgot)
firewall.
But, assuming you want to privilege preferences, in most cases the only
input that would be required (other than name) is label. Personally I
don't like default labels, and I suspect this will be unwanted, but we
can try.

Yes, qvm.prefs requires a qube be present, which is where `qvm.exists`
comes in to play. I have never had an issue with this. (But then I've
never had an issue with qvm.present, because I don't use it to change
preferences.)

**Comment by rocodes** [comment]
I know this issue was long since closed, but I agree with @3hhh that this is a bit counterintuitive. In the example below, I think the difference in outcome between the two states below is subtle and may create user confusion.

```
# precondition: suppose myappvm has already been created based on a fedora 40 template and is powered off.

example-state-noop:
  qvm.vm:
    - name: myappvm
    - present:
      - label: green
      - template: fedora-41  # template not changed

example-state-changes-template:
  qvm.vm:
    - name: myappvm
    - present:
      - label: green
    - prefs: 
      - template: fedora-41   # template changed
```

I think that ideally, the parameters used in qvm.present to satisfy the check of "is it present" (just name? name and label?) would be meaningfully separated from the "create if absent" arguments, since otherwise the implication is that all of them are part of the check.
