### ISSUE TITLE
qvm-firewall: '--before' option not documented on manpage

### ISSUE THREAD

**Issue by 3hhh** [QubesOS/qubes-issues#7074]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### The problem you're addressing (if any)
`qvm-firewall` can only add rules at the end.

### The solution you'd like
`qvm-firewall` can insert rules in the middle as well. This could either be implemented as `qvm-firewall add --rule-no=` similar to `qvm-firewall del --rule-no=` or as `qvm-firewall insert [index] [rule]`.

`qvm-firewall clear` to fully clear a firewall and cause a deny-all would also be nice. (The currently existing `qvm-firewall reset` creates the default allow-all rule.)

Another nice feature would be to fully write a firewall from stdin, e.g. `qvm-firewall read < rules.txt`.

The last two proposed features can however rather easily be implemented in e.g. `bash` if an insert primitive is available, but not otherwise.

All of these implementations should _not_ cause some intermittent time frame during which the firewall allows something that wasn't allowed before.

### The value to a user, and who that user might be

Not needing to do a lot of `qvm-firewall del` operations and `qvm-firewall add` operations to insert a rule in a specific place.

**Comment by marmarek** [comment]
```
$ qvm-firewall --help
...
Command 'add':
  usage: qvm-firewall VMNAME add [--verbose] [--quiet] [--help] [--before BEFORE] match [match ...]
...
```

Have you tried `--before` option?

**Comment by 3hhh** [comment]
That's precisely what I was looking for for years!
I had built quite complex workarounds in the past...

Anyway it is not documented at `man qvm-firewall` which explains why I never noticed it.

So this essentially becomes a doc issue, thanks for the hint!
