### ISSUE TITLE
Xorg crashes randomly at VGAarbiterSpriteMoveCursor() on machines with two GPUs in Dom0

### ISSUE THREAD

**Issue by biergaizi** [QubesOS/qubes-issues#7076]
### Qubes OS release
R4.0

### Brief summary
A known VGA arbitration bug in xorg-server 1.19.3 causes the X server to crash randomly when both an Intel & an extra GPU are installed on the system, regardless of whether the Intel GPU is used.

### Steps to reproduce

1. Have a Nvidia or AMD GPU as your display device (nouveau, radeon or modesetting, doesn't matter)
2. Have an Intel iGPU, unused (not listed in xorg.conf, effectively disabled)
3. Attach two monitors to the GPU (not sure if it's required to trigger the bug, but it's what I have here).
4. Start an X session, use the computer normally for up to a couple hours.

### Expected behavior

X server should not crash.

### Actual behavior

X server crashes at `VGAarbiterSpriteMoveCursor()`, systemd automatically restarts the login manager. The external behavior looks like an automatic log out.

### Additional context

Searching `VGAarbiterSpriteMoveCursor()` revealed that it's a known bug in xorg-server 1.19.3, and has been patched in commit `cf7517675d988c2d1ff967d6d162a17acbdad466`. QubesOS should apply the patch.

https://bugs.freedesktop.org/show_bug.cgi?id=101995

### Comments

Since I've added a dedicated graphics card, my desktop now crashes up to 6 times within an hour. I'd like to make a polite request to QubesOS maintainers to apply the patch soon. Thanks for your time.

I also tried the `rd.qubes.hide_pci` option but it was ineffective. This option is a misnomer, it only stops Dom0's kernel from binding a device driver to the device, but doesn't really hide it. Meanwhile, Xorg's VGA arbitration code is activated as long as it sees two VGA devices on PCI regardless of whether they are being actually used.

**Comment by biergaizi** [comment]
It's not an AMD-only issue. I just replaced the AMD graphics card with an Nvidia one for an unrelated reason, and found it can trigger the same bug.

**Comment by biergaizi** [comment]
With my system crashes 30 times a day, this problem is becoming intolerable, and I want to submit a patch to the upstream.

But it's not an easy problem - QubesOS doesn't use its own repository for most packages, so simply updating a source package with a patch won't help. Instead, it uses `qubes-linux-dom0-updates` to backport selected packages (currently only 3). So the most straightforward solution is backporting a newer X server from a newer Fedora. However, it means there will be a massive dependency upgrade, and worse, since this fix was only included in xorg-server 1.20, it breaks the Video ABI of all the existing Fedora 25 graphics driver in Dom0 as well, and those packages must also be rebuilt, so I really don't want to do that. Nevertheless, that effort can be worthwhile for supporting new hardware for other users and fix multiple open issues.

Another solution, which I plan to use here, is simply downloading the existing Fedora 25 source package, unpack, apply a custom patch, and repack. It requires modifying the shell script but seems much easier than a full backport.

**Comment by DemiMarie** [comment]
@biergaizi can you upgrade to R4.1?

**Comment by biergaizi** [comment]
@DemiMarie Thanks for the suggestion. But I prefer to avoid running a non-stable release for the moment.

**Comment by biergaizi** [comment]
I just created a patch, using the proposed "downloading the existing Fedora 25 source package, unpack, apply a custom patch, and repack" solution. However, I'm not familiar with Makefile or the QubesOS build system, the fix involves a lot of hacks, I don't think it's upstreamable in its current condition, nevertheless I think it's still a good idea to publish the patch in its half-finished form. I'd like to hear your suggestions on the proper way to extend the build script.
