### ISSUE TITLE
xen: shutdown doesn't shuts off the laptop (thinkpad P50)

### ISSUE THREAD

**Issue by 0xdd7fq** [QubesOS/qubes-issues#7077]
Duplicate question from Qubes Community.
I have similar issue, it was noticed on workstations like 
Thinkpad P5x series
Maybe any options in grub can fix it?
Qubes 4.1 with lastest kernel installed.

related ? [#1581](https://github.com/QubesOS/qubes-issues/issues/1581)

```
So far, everything works smooth except when I shut down the machine.

On shutdown, the screen goes blank, but the backlight keyboard stays powered and it doens’t appear as if the system fully shutdown. A short press of the power button does nothing.

A long press of the power button does a forced power-down on the machine and then a short press will restart the machine.

Any ideas on why my machine is no longer fully shutting down?
```

**Comment by 0xdd7fq** [comment]
Switched from tpm 2.0 to tpm 1.2. Now it works.

**Comment by cuddlepuppies** [comment]
I was having the same problem on my P50 and can confirm that changing to tpm 1.2 from 2.0 fixed it as detailed above.
A possibly useful observation was that when I was still using tpm 2.0 a Restart would actually power down the laptop for a split second before restarting as expected. Strange that a Shutdown could not achieve this at all.
All good.
