### ISSUE TITLE
Can not set "Max memory" limit after Selecting a USB device

### ISSUE THREAD

**Issue by straussmaus** [QubesOS/qubes-issues#7079]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

4.0 (rolling upgrades)

### Brief summary

After assigning a USB device in Qubes Settings > Devices, the Mam memory setting in Advanced sets to 400MB and can not be changed.

### Steps to reproduce

Change Qube to HVM mode

(RAM problem does not happen)

Assign a Device

See that Max memory is no longer an option to change and is now 400MB (was 4000MB)

### Expected behavior

I would expect the Max memory field to be unchanged, and to be user-editable like before.

### Actual behavior

Max memory reduced from 4000MB to 400MB, can not be changed

Note that Initial memory is 400MB.  I do not know if this is why the genie in the system chooses 400MB for Max memory.

**Comment by marmarek** [comment]
This is intended behavior, dynamic memory management is incompatible with having PCI devices assigned, and as such is automatically disabled.

**Comment by straussmaus** [comment]
@marmarek 

> dynamic memory management is incompatible with having PCI devices assigned, and as such is automatically disabled.

That makes sense, but just now I raised the min memory to 1024 and restarted the qube and now the max memory is available to me to change even when running.  That seems to contradict what you are saying or do I not understand.  The USB device is even attached and in use in that qube.

**Comment by straussmaus** [comment]
Even when I reduce min memory to 400, the max memory field is not locked anymore.  But from the slowness of the qube it seems that I am stuck at 400mb.  So I created https://github.com/QubesOS/qubes-issues/issues/7086

**Comment by brendanhoar** [comment]
Just to clarify, @marmarek was addressing the limitation of no dynamic memory support when a "PCI device" is attached. 

However, while the description in the OP seems to indicate that you attached a PCI-based USB controller, *after* that OP you've been referring to a "USB device" being attached. Notably, "USB devices" (e.g. usb drive) can be attached through a different mechanism.

Have you been testing the entire time with a "USB controller" (which is a "PCI device"), attached to this VM? Does the USB controller still show up in the Qubes Settings for this VM?

B

**Comment by straussmaus** [comment]
> Have you been testing the entire time with a "USB controller" (which is a "PCI device"), attached to this VM? Does the USB controller still show up in the Qubes Settings for this VM?

Yes and yes.  I'm not sure I understand the distinction you're making, so thank you for helping me clarify the issue.
