### ISSUE TITLE
Add rpmcanon to qvm-template

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#7080]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

Add extra hardening of rpm package parsing to qvm-template, by using rpmcanon tool. Similar as we do with dom0 updates.

### The value to a user, and who that user might be

More protection from maliciously malformed packages.

**Comment by DemiMarie** [comment]
Marking as `P: blocker` as this is (in at least one respect) a security regression compared to the old method of installing templates.
