### ISSUE TITLE
Use nanosecond resolution when syncing time to ClockVM

### ISSUE THREAD

**Issue by vyu** [QubesOS/qubes-issues#7081]
### The problem you're addressing (if any)

Currently, time in each VM is synchronized by querying ClockVM (sys-net by default) with a resolution of 1 second. This results in each VM having a lag between 0 seconds and 1 second (this is unrelated to clock randomization by Whonix's `sdwdate`) relative to ClockVM, which represents a significant loss of accuracy as the SNTP syncing by ClockVM should have sub-second (in fact, under 100 ms) precision in typical networks.

### The solution you'd like

I'd like to see nanosecond resolution used when syncing to ClockVM.

I have only glanced through the code, but I believe the following three lines of change might suffice. (This is untested!)

In [qubes-core-agent-linux:`qubes-rpc/qubes.GetDate`](https://github.com/QubesOS/qubes-core-agent-linux/blob/master/qubes-rpc/qubes.GetDate):
```diff
diff --git a/qubes-rpc/qubes.GetDate b/qubes-rpc/qubes.GetDate
index ebd9ebf..87b37be 100755
--- a/qubes-rpc/qubes.GetDate
+++ b/qubes-rpc/qubes.GetDate
@@ -19,4 +19,4 @@
 #
 #
 
-date -u -Iseconds
+date -u -Ins
```

In [qubes-core-admin:`qvm-tools/qvm-sync-clock`](https://github.com/QubesOS/qubes-core-admin/blob/master/qvm-tools/qvm-sync-clock):
```diff
a/qvm-tools/qvm-sync-clock b/qvm-tools/qvm-sync-clock
index 175f6f9e..b7a71af0 100755
--- a/qvm-tools/qvm-sync-clock
+++ b/qvm-tools/qvm-sync-clock
@@ -44,11 +44,11 @@ def main():
     untrusted_date_out = p.stdout.read(25).decode('ascii', errors='strict')
     untrusted_date_out = untrusted_date_out.strip()
 
-    if not re.match(r'^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\+00:?00$', untrusted_date_out):
+    if not re.match(r'^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2},\d{9}\+00:?00$', untrusted_date_out):
         sys.stderr.write('Invalid date received, aborting!\n')
         sys.exit(1)
     date_out = untrusted_date_out
-    subprocess.check_call(['date', '-u', '-Iseconds', '-s', date_out],
+    subprocess.check_call(['date', '-u', '-Ins', '-s', date_out],
         stdout=subprocess.DEVNULL)
     subprocess.check_call(['/sbin/hwclock', '--systohc'],
         stdout=subprocess.DEVNULL)
```

(Apparently, nanosecond resolution has been supported by GNU coreutil's `date` [since 2005](https://github.com/coreutils/coreutils/blob/725bb111bda62d8446a0beed366bd9d2c06c8eff/NEWS#L4512).)

### The value to a user, and who that user might be

Some applications require somewhat accurate absolute time. For example, currently, [`geth`](https://github.com/ethereum/go-ethereum) Ethereum nodes running in Qubes R4.0 will reject legitimate blocks when the VM's lag is relatively high (i.e., around a second).

**Comment by doug1** [comment]
Similar to #5876

**Comment by marmarek** [comment]
There is missing dom0 part
