### ISSUE TITLE
R4.1 qui-devices requires gnome-icon-theme

### ISSUE THREAD

**Issue by dmoerner** [QubesOS/qubes-issues#7082]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

R4.1, rc2

### Brief summary

Users of window managers like i3 often remove a lot of Xfce or gnome packages from dom0. On R4.0, the gui widget qui-devices was still usable. On R4.1, it requires the installation of gnome-icon-theme. This dependency should either be removed from the qui-devices code, or made explicit in the Fedora packaging. This also affects the R4.0 -> R4.1 upgrade path.

### Steps to reproduce

Remove gnome-icon-theme, run `widget-wrapper qui-devices`. You will find that the widget does nothing when clicked. In the console the traceback gives the following error:

```
gi.repository.GLib.Error: gtk-icon-theme-error-quark: Icon 'audio-input-microphone' not present in theme Adwaita (0)
```

### Expected behavior

The core Qubes widgets should not let you remove packages which inhibit their core functionality. 

Also, the upgrade path from R4.0 -> R4.1 should bring in any new dependencies for these widgets.

### Actual behavior

R4.1 systems without gnome-icon-theme cannot use the widget.

**Comment by marmarta** [comment]
I would like to at some point remove this dependency (and get custom icons, instead of using generic gnome icons), but as this is very much a future thing, you're right on putting them in fedora packaging explicitly.
