### ISSUE TITLE
distutils is being deprecated in Python 3.12

### ISSUE THREAD

**Issue by dmoerner** [QubesOS/qubes-issues#7083]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

R4.0 or R4.1 with Fedora 35 qubes.

### Brief summary

Python 3.10 in Fedora 35 is now starting to throw out warnings that distutils is going to be deprecated in Python 3.12. This is most obvious when running dnf, but there could be other instances as well.

### Steps to reproduce

```
user@net ~> sudo dnf upgrade
/usr/lib/python3.10/site-packages/dnf-plugins/qubes-hooks.py:23: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  from distutils.version import LooseVersion
```
It looks like the relevant functionality here is now provided by `packaging.version.Version`. However, I don't know if there are other uses of distutils in the code, I don't have a convenient copy of the Qubes source to grep through.

### Expected behavior

No error message is thrown when running ordinary dnf commands.

### Actual behavior

The above error message is thrown.

**Comment by fepitre** [comment]
Thank you creating the issue, I'm aware of this and forgot to create a ticket. I'll take care of that.
