### ISSUE TITLE
Migrate backups of Windows VMs created under Qubes R4.0 to R4.1

### ISSUE THREAD

**Issue by GWeck** [QubesOS/qubes-issues#7088]
Qubes R4.1-rc2

### Brief summary
Windows 7 / 10 / 11 VMs (Standalone / Template AppVM)  restored from a backup of these VMs created under Qubes R4.0 cannot be started under Qubes R4.1.
- Windows 7 starts without displaying a window, no matter how the `gui` and `gui_emulated` values are set. After some time (a minute or so) the VM stops without a message, but the Qube manager still shows it as starting (yellow dot).
- Windows 10 or 11 first start normally, but then crash with the error `Inaccessible Boot Device`, which can mean almost anything but probably is caused by a hardware representation that is different from that under Qubes R4.0.

This behaviour is independent from Qubes Windows Tools being installed in the VM; it occurs with and without QWT in the same way.

### Steps to reproduce
In Qubes R4.1, restore a backup of an Windows VM which was stored under Qubes R4.0. After the VM is created, try to start it.

### Expected behavior
If the VM does not contain Qubes Windows Tools, it should start the same way that it did under Qubes R4.0. With QWT 4.0.1.3 installed, it should start with a non-functioning QWT and allow to replace the Qubes Windows Tools with a version suitable for Qubes R4.1, e.g. QWT-4.1-65 from @jevank [tabit-pro/qubes-windows-tools-cross ](https://github.com/tabit-pro/qubes-windows-tools-cross)

### Actual behavior
The VM crashes after start. No real recovery is possible:

- For Windows 7, no action can be taken.

- For Windows 10, after letting the VM crash several (3 or so) times, an automatic repair is started, but never terminates (a well known bug of Windows 10). So far, I found no way of disabling this automatic repair, and trying to change anything via the command console had no effect. The option to start the VM in protected mode is not offered, so you are stuck with the non-working automatich repair.

- For Windows 11, the behaviour is similar, but the automatic repair really does some repair and then allows to start the system in protected mode. After the next reboot, the system seems to run normally. **But:** If QWT 4.1-65 is installed, which runs o.k. in a VM created under Qubes R4.1, it does not work in the VM created from the R4.0 backup. The two service processes are running, but file transfer to/from this VM does not work, indicationg that the `qrexec` interface is not really up. Also, if a restart of these processes is tried, it just times out, and the processes do not shut down. (In a VM newly created under Qubes R4.1, they can be shut down and restarted.)

It might be helpful to know what type of hardware a Windows VM does see, and how this differs between Qubes R4.0 and R4.1. Windows seems to rather fragile in this respect, in contrast to Linux-based VMs which can be well restored from backups created under R4.0.

**Comment by brendanhoar** [comment]
I suspect this is due to the different emulated devices presented by QEMU. E.g. under R4.0 the emulated disk devices are LSI SCSI devices, but I believe under R4.1 QEMU presents IDE/SATA devices to the Windows HVM.

Just as an aside w/r/t R4.0 QWT, @GWeck: I have been able to 100% reliably get the Xen PV Disk drivers (8.2.2, e.g. as packaged by tabit-pro) working under Windows 10 and Windows 7 in R4.0 by running this command *after installing them* but *before rebooting*:  
```
pnputil /delete-driver lsi_sas.inf /uninstall
```
The reason for the crashes has been that there end up being two valid routes to the device during boot (emulated and PV), but the PV drivers disable the emulated device as soon as they are activated.

It's *possible* that if you are able to get QWT 4.1.65 installed with that trick above under R4.0, you might not have the boot-device switcheroo issue when importing into R4.1.

**Comment by aesrentai** [comment]
I can verify that this does *not* happen on my machine with standalone Windows 10 vms.  This works regardless of whether or not networking is enabled.  QWT is installed but no other devices have been assigned to the vms.  This even worked when migrating to a whole new laptop.

**Comment by GWeck** [comment]
For Windows 10 and 11, there is a way to migrate backups created under Qubes R4.0 to R4.1. For this, the version of Qubes Windows Tools 4.1-65, created by @jevank [tabit-pro / qubes-windows-tools-cross ](https://github.com/tabit-pro/qubes-windows-tools-cross), has to be installed under Qubes R4.0, selecting the option to install the Xen PV disk driver, which emulates SCSI disks. For template VMs, the option to move user profiles may be selected, too. Then, the backup may be created, and this backup can be restored under Qubes R4.1, resulting in a VM well integrated into Qubes R4.1. If `qvm-features <VMname> audio-model ich6` is set, Windows 11 even will have audio, although somewhat scratchy. (For Windows 10, I was so far not able to make audio work at all.)

While this is somewhat straightforward, things get difficult if QWT 4.0.1.3 was installed in the VM. Prior to installing version 4.1-65, the old version has to be removed, which can be quite tricky:

- First, be sure that the automatic repair function is disabled. In a command window, execute  `bcdedit /set recoveryenabled NO`, and check that this worked by issuing the command `bcdedit`, without parameters, again.
- Now, uninstall QWT 4.0.1.3, using the `Apps and Features` function of Windows. This will most likely result in a crash.
- Restart Windows again, possibly two or three times, until repair options are offered. By hitting the `F8` key, select the restart menu, and there select a start in protected mode (in German, it's option number 4).
- The system wil start gain, but in a rather useless way. Just shut it down, and reboot again.
- Now Windows will start normally. Check in the `Apps and Features` display, if there are any Xen drivers left. If so, uninstall them.
- In the Windows device manager, check if there is still a (probably non working) Xen PV disk device. If so, uninstall it. Otherwise, QWT 4.1-65 will not install.
- In the `Apps and Features` display, check again, if the Xen drivers are removed. In my system, a Xen Bus Package (version 8.2.1.8) remains and cannot be removed, but does no harm. Any other Xen drivers should have disappeared.
- Now, finally, after one additional reboot, Qubes Windows Tools 4.1-65 can be installed., and after one more reboot, the backup for R4.1 may be created.

This is altogether not very nice, but at least, it works. For Windows 7, I found no way to migrate a backup, so far, but I am still trying. Wish me luck!

**Comment by GWeck** [comment]
The Windows 7 VMs do not start at all; they crash immediately with the error

`Start failed: Internal error: libxenlight faild to create new domain <VMname>`.

No log file is created in `/var/log/libvirt/libxl/`, and the logfile `libxl-driver.log`in this directory contains the new text:

`2021-12-07 11:33:01.112+0000: libxl: libxl_dm.c:2767:stubdom_xswait_cb: Domain 27:Stubdom 28 for 27 startup: startup timed out`
`2021-12-07 11:33:01.112+0000: libxl: libxl_create.c:1879:domcreate_devmodel_started: Domain 27:device model did not start: -9`

This happens always, no matter if QWT is installed or not. Where could I look for further information? Any help would be appreciated. (@marmarek ?)

On the other hand, a backup of an empty, new Windows 7 VM created in Qubes R4.0 can be restored and started under Qubes R4.1, even with QWT 4.1-65 previously installed under Qubes R4.0.

**Comment by marmarek** [comment]
> Stubdom 28 for 27 startup: startup timed out

Take a look at `/var/log/xen/console/guest-<VMname>-dm.log`, I guess there is some qemu startup error.

**Comment by GWeck** [comment]
Here is the log file:
[guest-Win7-dm.log](https://github.com/QubesOS/qubes-issues/files/7668548/g`uest-Win7-dm.log)

It seems that there is something terribly wrong as the file starts in line 2 with

`[2021-12-07 11:41:46] Xen Minimal OS (pv)!`

while regular log files start there with
`[2021-12-01 12:45:41] Linux version 5.4.74-xen-stubdom (mockbuild@build-fedora4) (gcc version 10.3.1 20210422 (Red Hat 10.3.1-1) (GCC)) #1 Wed Jun 23 14:40:30 CEST 2021`

for a Windows VM or

`[2021-12-02 12:50:48] [    0.000000] Linux version 5.10.76-1.fc32.qubes.x86_64 (mockbuild@build-fedora4) (gcc (GCC) 10.3.1 20210422 (Red Hat 10.3.1-1), GNU ld version 2.34-6.fc32) #1 SMP Fri Oct 29 03:58:58 CEST 2021`

for a Linix VM.

**Comment by DemiMarie** [comment]
> `[2021-12-07 11:41:46] Xen Minimal OS (pv)!`

That means that the VM is trying to use the legacy stubdomain, which is deprecated.  The next question is how the `linux-stubdom` feature got set to a false value.

**Comment by GWeck** [comment]
The VM showing this behaviour might - I am not sure - have been created under Qubes R3.2. Could this be a left-over?

Would it be possible to set the `linux-stubdomain` feature to the right value?

**Comment by marmarek** [comment]
> The VM showing this behaviour might - I am not sure - have been created under Qubes R3.2. Could this be a left-over?

This is likely, Qubes 3.2 has the old stubdomain by default and this is preserved over backup&restore (as Windows otherwise won't boot).

> Would it be possible to set the `linux-stubdomain` feature to the right value?

You can try by simply deleting it (`qvm-features -D <vmname> linux-stubdomain`) - it will switch to the default value (which is `1` now). But likely Windows won't like it... Maybe there is some way to tell Windows that major hardware change is coming so it can re-configure itself on the next startup? There was "sysprep" tool in Windows XP times, not sure how it can be done now.

**Comment by GWeck** [comment]
I tried, but it has no effect - Windows still tries to start with the old stub domain, as shown in the log file. So I suppose it would be best to create a new VM under R4.0 and migrate the contents from one VM to the other one.

**Comment by GWeck** [comment]
If a Windows 7 VM was created under Qubes R4.0, it can be migrated to R4.1 in the same way as is possible for Windows 10 or 11: Qubes Windows Tools 4.1-65 has to be installed under Qubes R4.0, selecting the option to install the Xen PV disk driver. A backup created from this VM under Qubes R4.0 can be restored under Qubes R4.1 and works, allowing file and clipboard copy to/from other VMs. So far, the only difference between the installations in both versions of Qubes - that I found - is that, in seamless mode, the Windows menu may sometimes be replaced by an empty rectangle. I will check this further.

If QWT 4.0.1.3 was installed prior to installing QWT 4.1-65, it has to be removed, which is a hassle similar to Windows 10 or 11, the main difference being that the necessary intermediate switch to a protected mode boot is painless and needs no repeated booting and disabling the non-working repair mode. At least in this respect, Windows 7 was the last halfway decent Windows, while Windows 10, as Microsoft puts it, is the "last" Windows (and Windows 11 the "very last")!

**Comment by GWeck** [comment]
The PV disk drivers used for migration can be removed after successful installation of the VM under Qubes R4.1. For this, the QWT installation has to be started, the option `Change` has to be selected, and the PV disk driver must be unselected. After completion, the VM has to be rebooted. For Windows 10 and 11, the VM will crash with the error `INACCESSIBLE BOOT DEVICE`, which can be repaired as described above.

After successful uninstallation of the PV disk drivers, the disks will appear as QEMU ATA disks.

**Caution:** This change may lead Windows to declare that the hardware was changed and that in consequence, the activation is no longer valid, possibly complaining that the use of the software is no longer lawful. It should be possible to reactivate the software if a valid product key is provided.

**Comment by GWeck** [comment]
Migrating backups od Windows qubes from R4.0 to R4.1 has now been described in the Qubes documentation. So I am closing this issue now.
