### ISSUE TITLE
dom0 boot loop with kernel-latest-5.14.15

### ISSUE THREAD

**Issue by icequbes1** [QubesOS/qubes-issues#7089]
### Qubes OS release

R4.0, stable + security-testing repos enabled

### Brief summary

After kernel-latest-5.14.15 was pushed to stable on November 22, 2021, an AMD Ryzen machine that uses amdgpu boot loops. It is OP's hypothesis that it is related to AMD/amdgpu, but this has not been proven.

### Steps to reproduce

1. Power on

### Expected behavior

1. Disk passphrase is requested

### Actual behavior

1. Disk passphrase is not requested
1. Machine immediately reboots

### Additional info

Initial comments were provided [0], where I stated:

> 1. xen loads
> 1. dom0 loads, kernel output shown
> 1. dom0: "Please enter passphrase for disk...." text-mode prompt seem very briefly 
> 1. dom0 kernel: `amdgpu: Topology: Add APU mode`
> 1. dom0 kernel: `fb0: switching to amdgpudrmfb from EFI VGA`
> 1. reboot
> 
> On successful boots with working dom0 kernel (5.13.6-1), lots of amdgpu output immediately after, so my guess is something in amdgpu broke between 5.13.6 and 5.14.15.

After a weak kernel version bisect (with xen 4.8.5-36), the observations are as follows:

1. kernel-latest-5.13.6: no issues
1. kernel-latest-5.14.10: no issues
1. kernel-latest-5.14.15: dom0 boot loop
1. kernel-latest-5.14.16: dom0 boot loop
1. kernel-latest-5.14.17: no issues

Based on the above, the fix was implemented in 5.14.17. The 5.14.17 changelog does reveal two notable changes in amdgpu, one of which mentions a certain feature being "severely broken" and reverting the feature [1]. I have not bisected by kernel commit to verify this and cannot state that this _is_ the reason for the boot loop; only that the boot loop was no longer observed in this version.

[0]: https://github.com/QubesOS/updates-status/issues/2696
[1]: https://cdn.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.14.17

**Comment by ydirson** [comment]
@icequbes1 which AMD GPU(s) do you have on this machine ?

**Comment by icequbes1** [comment]
Raven I believe.

**Comment by isodude** [comment]
Note:

I've done this trip, there is at least 5 proper broken commits between 5.14 and 5.16. There's
* A patch for shifting early memory allocation
* PCI/MSI broke, fixed somewhere in 5.15-rc4 I think
* Offlining CPUs broke in 5.15-rc4+ solved in 5.16 I think ( affecting both Xen and Non-Xen )
..

The PCI-problem is top of my mind and can be isolated via amdgpu.msi=0 as kernel commandline.
The early memory allocation thing needs to be patched.

If you want you can fetch the log by:
Xen cmdline: console=vga vga=keep noreboot
Linux cmdline: console=hvc0

I found that my camera had OTR-support which helped a lot :) I can pinpoint the patches if needed.

**Comment by icequbes1** [comment]
Closing as a later kernel-latest versions [5.16] did not experience the issue.
