### ISSUE TITLE
ALSA upgrade is missing packages causing broken audio

### ISSUE THREAD

**Issue by RealKeyboardWarrior** [QubesOS/qubes-issues#7091]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
4.1-rc2

### Brief summary
The Alsa UCM configuration files are missing, these aren't bundled with alsa-lib/alsa-tools anymore and I think this package should perhaps be installed by default.
The package commonly goes by `alsa-ucm-conf` but attempting to install that in `dom0` through the package manager said that it did not exist.

In `dom0` attempting to initialize the drivers will cause an error.
```
alsactl init
```
Will return the following error:
```
alsa-lib parser.c:2372 load_toplevel_config) Unable to find the top-level configuration file '/usr/share/alsa/ucm2/ucm.conf
``` 

After fixing that issue (see fix below) - a second error occurs when attempting to initialize ALSA.

```
direct firmware load for intel/sof/sof-cml.ri failed with error -2
```

This is because the package `alsa-sof-firmware` is missing.

### Fix missing ucm2 config files
In an AppVM (I used work)
```
git clone https://github.com/alsa-project/alsa-ucm-conf.git
cd alsa-ucm-conf
zip -r ucm2 ucm2.zip
pwd
```

Now transfer these configuration files over to `dom0` by executing the following in `dom0`.
```
sudo su
qvm-run --pass-io <src-vm> 'cat /path/to/file_in_src_domain/ucm2.zip' > /usr/share/alsa/ucm2.zip
cd  /usr/share/alsa
unzip ucm2.zip
rm ucm2.zip
``` 

### Fix Direct Firmware
In `dom0` 
```
sudo qubes-dom0-update alsa-sof-firmware
```

Running the following in `dom0` should return nothing if everything works:
```
alsactl init
```

Reboot because pulseaudio won't show the devices yet.

### Steps to reproduce

Install Qubes on a system with an intel built-in audio `Comet Lake PCH cAVS`.

### Expected behavior
Audio works out of the box

### Actual behavior
No audio devices detected except dummy.

# SEO for people looking for help with other intel sof drivers:
```
direct firmware load for intel/sof/sof-cml.ri failed
direct firmware load for intel/sof/sof-cfl.ri failed
direct firmware load for intel/sof/sof-tgl.ri failed
```

**Comment by solardiz** [comment]
@RealKeyboardWarrior Did simply installing `alsa-sof-firmware` provide these recent firmware files for you? That wasn't the case for me before, as Fedora 32's version of that package appeared to be too old (in particular, no `sof-tgl`), see #7055. OTOH, I somehow didn't run into the ALSA issue.

**Comment by RealKeyboardWarrior** [comment]
@solardiz it provided the files for Comet Lake but they may not include Tiger Lake, it might be too old for that.

**Comment by marmarek** [comment]
Updated alsa-sof-firmware is available in current-testing: https://github.com/QubesOS/updates-status/issues/3022
