### ISSUE TITLE
Special casing of windows template private volume import works for AppVM, but not for StandaloneVM

### ISSUE THREAD

**Issue by brendanhoar** [QubesOS/qubes-issues#7095]
### Qubes OS release
R4.1

### Brief summary
For qubes-provided linux templates, deploying an AppVM or StandaloneVM based on the template initiates the deployment of a "clean" (read:empty) private volume that does not include data from the private volume of the template (e.g. bash history, etc.). This is done by deploying a blank private volume during VM creation and then scripts within the boot process of the linux VMs autopopulate the empty private volume content, if such data is missing. Typically this occurs only on the first boot of the new VM.

There is, however, special case code in qubes-core-admin for Windows VMs (here: https://github.com/QubesOS/qubes-core-admin/blob/master/qubes/ext/windows.py ). QWT tooling lacks this clean-deployment on boot feature. The code referenced above (in qubes-core-admin) forces the import of the populated private volume from the template into the AppVM private volum if and only if the template is a Windows template.

This is a fine compromise and seems to work correctly for AppVMs. 

However, this special case does *not* trigger if you create a *StandaloneVM* from the Windows template instead. In that case, you get an empty private volume and boot failure.

Presumably a change needs to be made to ensure the private volume is also imported into the new VM if the new VM is both a) Windows and b) a StandaloneVM.

### Steps to reproduce
R4.1
Create Windows VM, make it a template.
Install tabit-pro's QWT ISO built from master branch (here: https://github.com/tabit-pro/qubes-windows-tools-cross ) so that we can move the user profile correctly.
Enable the move user profile feature (with recent changes to master branch you will need to manually enable this) and then reboot, double checking to see if the C:\Users directory now points to Q:\Users after the reboot.
Utilize Create Windows VM to create AppVM
Utilize Create Windows VM to create StandaloneVM

### Expected behavior
Both VMs work

### Actual behavior
AppVM works correctly
StandaloneVM fails to make it to usable desktop, as Q:\Users directory is missing due to a blank private volume.

**Comment by andrewdavidwong** [comment]
Is this related to #7088?

**Comment by brendanhoar** [comment]
> Is this related to #7088?

I don't believe so. #7088 appears to be an issue with QEMU presenting different emulated hardware to the windows HVMs.

B
