### ISSUE TITLE
Executing vulkaninfo in archlinux-minimal TemplateVM prints some incompatible driver error due to no Vulkan driver

### ISSUE THREAD

**Issue by alicewith** [QubesOS/qubes-issues#7107]
### Qubes OS release
4.1.0-rc2

### Brief summary
In archlinux-minimal TemplateVM from what I had built as described in [the manual](https://github.com/Qubes-Community/Contents/blob/4010951926124b7d205421e90476aa5a05a8dcd6/docs/building/building-archlinux-template.md), executing `vulkaninfo` prints some incompatible driver error due to no Vulkan driver. Furthermore, I could not find any relevant graphic drivers supporting the guest VM in Arch Linux package databases; even though my host system is using an AMD GPU, installing AMD graphic driver in guest VM was not helpful, as described the Note section.

### Steps to reproduce and actual behavior
```
$ uname -a
Linux archlinux 5.10.76-1.fc32.qubes.x86_64 #1 SMP Fri Oct 29 03:58:58 CEST 2021 x86_64 GNU/Linux
$ vulkaninfo
Cannot create Vulkan instance.
This problem is often caused by a faulty installation of the Vulkan driver or attempting to use a GPU that does not support Vulkan.
ERROR at /build/vulkan-tools/src/Vulkan-Tools-1.2.199/vulkaninfo/vulkaninfo.h:687:vkCreateInstance failed with ERROR_INCOMPATIBLE_DRIVER
```

### Expected behavior
It should print Vulkan-related information without any error.

### Note
I had tried to install some relevant packages by executing `sudo pacman -S vulkan-driver vulkan-devel vulkan-tools` in the VM and to shutdown the VM, to change the virtualization mode of the VM from PVH to both HVM and PV, and to append the `04:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Renoir` to PCI passthrough list, but entirely it didn't work; after changed the virtualization mode and started the VM, my computer was turned to display black screen immediately, and to reboot automatically soon.

**Comment by marmarek** [comment]
GPU currently are not available to the VMs, see https://www.qubes-os.org/faq/#can-i-run-applications-like-games-which-require-hardware-acceleration
