### ISSUE TITLE
Qubes Manager core dumps

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#7110]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

R4.1

### Brief summary

When I try to update one of my templates with the Qubes Manager GUI, the program core dumps with a backtrace mentioning PyQt5.

### Steps to reproduce

Update one of my qubes.  The problem doesn’t reproduce reliably.

### Expected behavior

Works

### Actual behavior

SIGABRT due to what appears to be an uncaught Python exception.  The actual crash happens in Qt.

**Comment by fepitre** [comment]
That would be helpful to have the backtrace somehow.

**Comment by DemiMarie** [comment]
Already sent privately to @marmarta 🙂

**Comment by DemiMarie** [comment]
Fixed.
