### ISSUE TITLE
Debian-10 and Fedora-33 Templates not updating, the rest is OK

### ISSUE THREAD

**Issue by interact0r** [QubesOS/qubes-issues#7111]
### Qubes OS release
R4.0.4

### Brief   summary
Debian-10 and Fedora-33 templateVM cannot be updated, with errors showing as below. This issue is exactly same to #5187

### Steps to reproduce
Install fresh R4.0.4. Update VMs from the Qubes Updater

### Expected behavior
All VM updates successfully

### Actual behavior
Dom0, Whonix ws and gw updates successfully, however both fedora and debian template shows the following error:

Debian-10:
`Failed to fetch https://deb.debian.org/debian/dists/buster/InRelease  Invalid response from proxy: HTTP/1.0 500 Unable to connect  Server: tinyproxy/1.10.0  Content-Type: text/html  Connection: close     [IP: 127.0.0.1 8082]`

Fedora-33:
`Failed to download metadata for repo 'updates': Cannot prepare internal mirrorlist: Curl error (56): Failure when receiving data from the peer for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f33&arch=x86_64 [Received HTTP code 500 from proxy after CONNECT]`

The only change I did was the Qubes is now connected to internet via my router. Previously connection to internet was through usb modem. Could it be that the router is somehow blocking the templateVM update? How can I troubleshoot the tinyproxy, if this has something to do with it at all? 

Note 1: everything was working fine previously (before using the router).
Note 2: content of `qubes.UpdatesProxy`
```

$tag:whonix-updatevm $default allow,target=sys-whonix
$tag:whonix-updatevm $anyvm deny

$type:TemplateVM $default allow,target=sys-net

$anyvm $anyvm deny
```

Thanks

**Comment by DemiMarie** [comment]
Fedora 33 is end of life, so you should upgrade to Fedora 34.  That said, this appears to be more suitable for the mailing lists.  @andrewdavidwong?

**Comment by unman** [comment]
500 is "internal server error".
OP could check that they can connect and download files manually in a
browser spawned on sys-net.
It does look like a support issue, and on the face of it OP is right to
suspect the router.

**Comment by andrewdavidwong** [comment]
> This issue is exactly same to #5187

This appears to be a [duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If anyone believes this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Comment by interact0r** [comment]
> > This issue is exactly same to #5187
> 
> This appears to be a [duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If anyone believes this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

Thanks @andrewdavidwong I will be commenting this on #5187 instead.
