### ISSUE TITLE
include xfce notification widget in default config

### ISSUE THREAD

**Issue by ydirson** [QubesOS/qubes-issues#7112]
Qubes produces some security-critical notifications which don't stick on screen, and in some context _loads_ of notifs come (eg. update several qubes). The "Notification Plugin" allows to see the last 10 notifs with one click, and the last 100 ones from "Notification settings/Log".  It looks like a really good fit for the default panel configuration.  There is [a bug preventing to see more than 100](https://gitlab.xfce.org/apps/xfce4-notifyd/-/issues/55) though, but that's not a critical one.

**Comment by ydirson** [comment]
arg, not a bug

**Comment by andrewdavidwong** [comment]
> arg, not a bug

For future reference, there is no need to close your issue when this happens. I will simply update the labels when I get to processing your report.

**Comment by andrewdavidwong** [comment]
Duplicate of #7113
