### ISSUE TITLE
update experts page to include endorsements connected to orgs/companies (not just individuals)

### ISSUE THREAD

**Issue by mfc** [QubesOS/qubes-issues#7119]
from: https://forum.qubes-os.org/t/deployments-of-qubes-by-entities-with-serious-stakes/8019/14

and potentially update main page website to have mix of individual capacity & org/company quotes. maybe two columns: "what experts are saying" and "what organizations are saying".

so:
* Let's Encrypt
* SecureDrop / FPF
* Google Enterprise Infrastructure Protection Team
* Mullvad

we'll see who is interested

**Comment by DemiMarie** [comment]
> * Google Enterprise Infrastructure Protection Team

Wow!

**Comment by mfc** [comment]
> > * Google Enterprise Infrastructure Protection Team
> 
> Wow!

was some individuals there but they don't seem to work there anymore. seeing if any still around.

**Comment by mfc** [comment]
https://twitter.com/mullvadnet/status/631010362083643392

could be used directly

**Comment by mfc** [comment]
emailed everyone (also [Latacora](https://www.qubes-os.org/partners/#latacora) ) except Mullvad since we already have a quote (tho it's old). so will probably email them too at some point but lower priority

**Comment by mfc** [comment]
from Let's Encrypt:

> Remote employees and remote administration capabilities are critical for our organization. Qubes OS gives us greater confidence in the security of systems being used to remotely access our servers, mainly because powerful physical and logical privilege separation between workspaces allows our engineers to select appropriate degrees of isolation for different processes.

maybe can be tightened to:

> Qubes OS gives us greater confidence in the security of systems being used to remotely access our servers, mainly because powerful physical and logical privilege separation between workspaces allows our engineers to select appropriate degrees of isolation for different processes.

**Comment by mfc** [comment]
from FPF/SecureDrop:

> SecureDrop depends on Qubes OS for best-in-class isolation of sensitive workloads on journalist workstations. Providing journalists with a sane way to handle untrusted content from unknown sources is part of our job, and Qubes gives us the tools we need to do that job well.

**Comment by andrewdavidwong** [comment]
> @andrewdavidwong @ninavizz i dunno if you have thoughts on how to integrate this into the website?
> 
> like maybe for the front page we have a mix of experts and orgs for the 4 slots, and on the experts page we have two sections, one of quotes from experts and one of quotes from orgs.

Is it weird to include orgs under a "What the experts are saying [...]" heading? If so, then we'll also have to generalize the heading for the front page (in which case it's unclear why we can't just use the same generalized heading for the experts page and keep just one section). If not, then it's unclear why we need two separate sections on the experts page.

**Comment by mfc** [comment]
yeah i think generalized heading makes the most sense. "what others are saying"?

then we don't need two sections.

**Comment by andrewdavidwong** [comment]
I'm not sure whether we want to change the URL from `/experts/`. What should it be, `/testimonials/`?

**Comment by andrewdavidwong** [comment]
Oh man, we even use `experts` throughout the code.

**Comment by andrewdavidwong** [comment]
Ok, all done! Added the three org endorsements (two of them to the front page), generalized the headings, URLs, internal refs, and miscellaneous other updates.

**Comment by mfc** [comment]
beautiful!! thanks andrew
