### ISSUE TITLE
qubes.TemplateSearch failed

### ISSUE THREAD

**Issue by MxMarl** [QubesOS/qubes-issues#7120]
### Qubes OS release
4.1rc2

### Brief summary
After a clean install and some time ( x ) its not possible to download a new template. No matter if fedora-34(minimal) | debian-11(-minimal)

No changes / updates have been done, all templates keeped default. But directly after another clean install it is possible.

### Steps to reproduce
in dom0 terminal: 
sudo qubes-dom0-update qubes-template-<DISTRO_NAME>-<RELEASE_NUMBER>

### Expected behavior
Downloading the templates

### Actual behavior
```
sudo qubes-dom0-update --verbose qubes-template-debian-11-minimal
Redirecting to 'qvm-template install --verbose debian-11-minimal'
[Qrexec] /bin/sh: /etc/qubes-rpc/qubes.TemplateSearch: No such file or directory
ERROR: qrexec call 'qubes.TemplateSearch' failed.
2021-12-13 23:34:13,399 [MainProcess qvm_template.main:1595] app: qrexec call 'qubes.TemplateSearch' failed.
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/qubesadmin/tools/qvm_template.py", line 1567, in main
    install(p_args, app)
  File "/usr/lib/python3.8/site-packages/qubesadmin/tools/qvm_template.py", line 908, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/qubesadmin/tools/qvm_template.py", line 1008, in install
    dl_list = get_dl_list(args, app, version_selector=version_selector)
  File "/usr/lib/python3.8/site-packages/qubesadmin/tools/qvm_template.py", line 792, in get_dl_list
    query_res = qrexec_repoquery(args, app, PACKAGE_NAME_PREFIX + template)
  File "/usr/lib/python3.8/site-packages/qubesadmin/tools/qvm_template.py", line 508, in qrexec_repoquery
    raise ConnectionError("qrexec call 'qubes.TemplateSearch' failed.")
ConnectionError: qrexec call 'qubes.TemplateSearch' failed.
```

**Comment by marmarek** [comment]
Is that full 4.1 install, or in-place upgrade from 4.0, or with template imported from a 4.0 backup? Especially: what template your updatevm is based on (see `qubes-prefs updatevm`)?

**Comment by MxMarl** [comment]
> Is that full 4.1 install, or in-place upgrade from 4.0, or with template imported from a 4.0 backup? Especially: what template your updatevm is based on (see `qubes-prefs updatevm`)?

It was my fault. I came from a 4.0 backup, but with the restored fedora-34 template. This one wasnt compatible with 4.1. and has replaced the 4.1 reinstalled fedora-34 template. The  `qubes-core-agent-qrexec` used the 4.0 Version. After changing  to 4.1 in the repos and an upgrade - its working again.
