### ISSUE TITLE
[archlinux] build failing: python<3.10

### ISSUE THREAD

**Issue by neowutran** [QubesOS/qubes-issues#7121]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
4.1

### Brief summary
Building the archlinux template is failing, python 3.10 is in the archlinux repository, and some components require a python version < 3.10. 
https://github.com/QubesOS/qubes-core-qubesdb/blob/master/archlinux/PKGBUILD#L12
https://github.com/QubesOS/qubes-core-agent-linux/blob/master/archlinux/PKGBUILD#L70

On my side I modified the dependency to ``python<3.11``, compiled and installed in my archlinux template. 
Everything seems to work as expected. 
Will submit PRs after some tests

### Steps to reproduce
Try to build the archlinux template

### Expected behavior
Archlinux template is build correctly

### Actual behavior
Build failure

**Comment by neowutran** [comment]
nevermind, someone already sent a pull request: https://github.com/QubesOS/qubes-core-agent-linux/pull/344

**Comment by DemiMarie** [comment]
Reopening because QubesDB has the same issue and because this still needs to be fixed.

**Comment by lubellier** [comment]
I built the packages with the two above @seberm 's PR, and I updated my ArchLinux VM with these packages. No issue detected, I **validate** the 2 PR.

**Comment by lubellier** [comment]
@neowutran @andrewdavidwong closable issue, the two PR merged and the related packages released.

**Comment by andrewdavidwong** [comment]
Closing as resolved. If anyone believes this issue is not yet resolved, or if anyone is still affected by this issue, please leave a comment, and we'll be happy to reopen it. Thank you.
