### ISSUE TITLE
Qubes Manager: Jump to Search (Name Filter) with Ctrl +F regression between 4.0 and 4.1

### ISSUE THREAD

**Issue by rwiesbach** [QubesOS/qubes-issues#7129]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### The problem you're addressing (if any)
Ease of use/UX

### The solution you'd like
Jump to Search (Name Filter) in Qubes Manager with Ctrl +F

### The value to a user, and who that user might be
Users, that use hotkeys to speed-up their usage of Qubes.

**Comment by andrewdavidwong** [comment]
Isn't that already how it works? I can just press Ctrl+F and start typing a qube name, and it works.

**Comment by rwiesbach** [comment]
I don't know which version you are using, in 4.1.19-1.fc32 it does not for me.

**Comment by DemiMarie** [comment]
Me neither.  @andrewdavidwong what version are you using?  Assigning @marmarta because she is the maintainer.

**Comment by DemiMarie** [comment]
Setting milestone to R4.1 updates because this is a regression, albeit not a very severe one.

**Comment by andrewdavidwong** [comment]
> I don't know which version you are using, in 4.1.19-1.fc32 it does not for me. (same for current 4.1.22-1)

I'm using `4.0.45-1.fc25`.

> Setting milestone to R4.1 updates because this is a regression, albeit not a very severe one.

Indeed, it appears so, which also makes this a bug rather than an enhancement.
