### ISSUE TITLE
Document "Open certain applications in disposables" feature

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#7130]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release (if applicable)

4.1

### Brief summary

Add documentation for https://github.com/QubesOS/qubes-issues/issues/6877
Few parts:
 - document relevant "services" in `qvm-service` man page
 - add page to qubes-doc for users, including what to expect, what are the limitations, and maybe list of applications known to work/known to not work with it

**Comment by marmarek** [comment]
In the meantime, for anybody wanting to try this:
```
qvm-service --enable <vmname> app-dispvm.<application-id>
```
The `<application-id>` is the application's desktop file name, without an extension. For example:
```
qvm-service --enable work-mail app-dispvm.mozilla-thunderbird
```

**Comment by DemiMarie** [comment]
This feature does not currently work with Flatpak applications.

**Comment by Geblaat** [comment]
> In the meantime, for anybody wanting to try this:
> 
> ```
> qvm-service --enable <vmname> app-dispvm.<application-id>
> ```
> 
> The `<application-id>` is the application's desktop file name, without an extension. For example:
> 
> ```
> qvm-service --enable work-mail app-dispvm.mozilla-thunderbird
> ```

Should this be working now on an up to date R4.0 with a Debian 11 AppVM? I tried this command for Thunderbird, but when I try to open an attachment (text file), it doesn´t open in a DispVM. Instead I get a file dialog from Thunderbird whether I want to open or save it, and when I click open, it opens inside the same AppVM.

**Comment by TheWanderer1983** [comment]
This works really well in R1. You can easily add other types to open with via the handlers.json file or directly in thunderbird via right clicking. Thank you @marmarek

**Comment by TheWanderer1983** [comment]
I've been playing around with this a bit today. I noticed that If I attached a disp that didn't have a browser installed (firefox, librewolf etc) and I clicked a web link within a thunderbird email it would keep spawning multiple DISPs over and over. Instead of just attempting once and stopping.

**Comment by marmarek** [comment]
> I've been playing around with this a bit today. I noticed that If I attached a disp that didn't have a browser installed (firefox, librewolf etc) and I clicked a web link within a thunderbird email it would keep spawning multiple DISPs over and over. Instead of just attempting once and stopping.

I believe this is https://github.com/QubesOS/qubes-issues/issues/7046
