### ISSUE TITLE
`logrotate` service fails to start during boot and afterwards because `qmemman.log` is missing.

### ISSUE THREAD

**Issue by Rot127** [QubesOS/qubes-issues#7132]
### Qubes OS release

4.1

### Brief summary

`logrotate.service` fails to start during boot and afterwards because `/var/log/qubes/qmemman.log` is missing.
journalctl log:
```
Dec 17 04:15:32 dom0 systemd[1]: Starting Rotate log files...
Dec 17 04:15:32 dom0 logrotate[9692]: error: stat of /var/log/qubes/qmemman.log failed: No such file or directory
Dec 17 04:15:32 dom0 systemd[1]: logrotate.service: Main process exited, code=exited, status=1/FAILURE
Dec 17 04:15:32 dom0 systemd[1]: logrotate.service: Failed with result 'exit-code'.
Dec 17 04:15:32 dom0 systemd[1]: Failed to start Rotate log files.
```

This happens on a machine with a freshly installed Qubes 4.1.
If the `qmemman.log` file is created the `logrotate.service` starts correctly.

### Steps to reproduce

```
systemctl start logrotate
# Fails
```

### Expected behavior

`logrotate` starts.

### Actual behavior

It doesn't.

<hr>

After several minutes no logs were written to `qmemman.log`. Is this log file even used anymore? If not I can create a PR to remove it from the `logrotate` config.

**Comment by rustybird** [comment]
> After several minutes no logs were written to `qmemman.log`. Is this log file even used anymore?

No it's been gone [since qubes-core-dom0 v4.1.19](https://github.com/QubesOS/qubes-core-admin/commit/9571765).

> If not I can create a PR to remove it from the `logrotate` config.

:thumbsup:
