### ISSUE TITLE
Cannot build app-linux-input-proxy on Debian/Ubuntu

### ISSUE THREAD

**Issue by unman** [QubesOS/qubes-issues#7138]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
4.0

### Brief summary
As title - build fails on bionic and focal - also checked with bullseye

### Steps to reproduce
Set up build environment.
Build template for bionic.
`make app-linux-input-proxy-vm`

### Expected behavior
Package will be built

### Actual behavior
Build fails.

```
dpkg-source: info: building qubes-input-proxy using existing ./qubes-input-proxy_1.0.25.orig.tar.xz
dpkg-source: info: using patch list from debian/patches/series
patching file qubes-rpc/Makefile
Hunk #1 FAILED at 9.
1 out of 1 hunk FAILED
dpkg-source: info: the patch has fuzz which is not allowed, or is malformed
dpkg-source: info: if patch '01_install_systemd_service.diff' is correctly applied by quilt, use 'quilt refresh' to update it
dpkg-source: error: LC_ALL=C patch -t -F 0 -N -p1 -u -V never -E -b -B .pc/01_install_systemd_service.diff/ --reject-file=- < app-linux-input-proxy.orig.IPuryb/debian/patches/01_install_systemd_service.diff subprocess returned exit status 1
dpkg-buildpackage: error: dpkg-source -b . subprocess returned exit status 2
make[2]: *** [/home/user/qubes-builder/qubes-src/builder-debian//Makefile-legacy.debian:56: dist-package] Error 2
make[1]: *** [Makefile.generic:197: packages] Error 1
make: *** [Makefile:265: app-linux-input-proxy-vm] Error 1
```

**Comment by fepitre** [comment]
I encountered the bug this morning with bookworm. Related PR: https://github.com/QubesOS/qubes-app-linux-input-proxy/pull/22

**Comment by Minimalist73** [comment]
Happened to me too, until the PR is merged revert back to tag `v1.0.24`.

**Comment by unman** [comment]
And I encountered it when looking at Ubuntu builds.

One question - why was this not picked up under CI? Are these packages
not included?

**Comment by andrewdavidwong** [comment]
> I encountered the bug this morning with bookworm. Related PR: [QubesOS/qubes-app-linux-input-proxy#22](https://github.com/QubesOS/qubes-app-linux-input-proxy/pull/22)

Is that PR merely related, or is it intended to actually fix this issue (meaning this bug has already been diagnosed)?

**Comment by DemiMarie** [comment]
@andrewdavidwong It should fix the bug, inasmuch as one cannot have a patch-related error without any patches.

**Comment by fepitre** [comment]
I think this issue can be closed now. Feel free to reopen it if it still happens.
