### ISSUE TITLE
Use L3 instead of L2 for inter-qube network interfaces

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#7141]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### The problem you're addressing (if any)
Currently, qubes are connected via paravirtual Ethernet devices.  This involves a substantial amount of code, such as ARP and NDP processing and neighbor table lookups.  It also requires a 14-byte Ethernet header to be added to each packet, which is checked and then removed by the qube it is sent to.  However, all of this work is wasted computation and useless attack surface.  The MAC addresses are *always* constant for a given interface, and (except for ARP frames) the Ethertype depends only on the IP version.  Furthermore, ARP and NDP are not transmitting anything that the respective qubes do not already know of.  Finally, there is a length field in the request, but it duplicates the field in the IP header, thought this might be unavoidable.

### The solution you'd like
Rip out the useless Ethernet framing and replace it with a dedicated point-to-point PV interface.

### The value to a user, and who that user might be
Point-to-point links will be slightly faster, *vastly* simpler, and have substantially less attack surface.

**Comment by marmarek** [comment]
The more non-standard config we'll use, the more things will break. We definitely _don't_ want to be in a place where _only_ VM configurations specifically curated by us works.
Static neighbor entries gave a glimpse of those issues - it caused problems even though it was only mildly weird.

In shot: no.

**Comment by h01ger** [comment]
nice, this seems like a great idea!

in addition to the already listed benefits this will also result in less
cpu cycles spent, thus less load, thus more battery life :)


-- 
cheers,
	Holger

 ⢀⣴⠾⠻⢶⣦⠀
 ⣾⠁⢠⠒⠀⣿⡁  holger@(debian|reproducible-builds|layer-acht).org
 ⢿⡄⠘⠷⠚⠋⠀  OpenPGP: B8BF54137B09D35CF026FE9D 091AB856069AAA1C
 ⠈⠳⣄

**Comment by h01ger** [comment]
should have read Marek's reply first, sorry for the noise!

I can definitly see how the benefits won't outweight the costs :)


-- 
cheers,
	Holger

 ⢀⣴⠾⠻⢶⣦⠀
 ⣾⠁⢠⠒⠀⣿⡁  holger@(debian|reproducible-builds|layer-acht).org
 ⢿⡄⠘⠷⠚⠋⠀  OpenPGP: B8BF54137B09D35CF026FE9D 091AB856069AAA1C
 ⠈⠳⣄

**Comment by DemiMarie** [comment]
> The more non-standard config we'll use, the more things will break. We definitely _don't_ want to be in a place where _only_ VM configurations specifically curated by us works. Static neighbor entries gave a glimpse of those issues - it caused problems even though it was only mildly weird.
> 
> In short: no.

That is definitely true.  If this was a supported feature of upstream Xen, that would be one thing.  But it is not.
