### ISSUE TITLE
Stop using obsolete networking tools

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#7142]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### The problem you're addressing (if any)
Qubes OS currently uses the obsolete `ifconfig` program in a few places.  That program is obsolete and adds a dependency on the `net-tools` package.

### The solution you'd like
Replace the 5 uses of `ifconfig` with `ip` and remove the dependency.

### The value to a user, and who that user might be

All users will save just under 1MiB of space per template or standalone qube, and the project will ditch some technical debt.

**Comment by andrewdavidwong** [comment]
This is set to "Release TBD," but it was just closed due to a PR merge, so I'm taking a guess that this is going to land in 4.2 and updating the milestone accordingly.
