### ISSUE TITLE
4.1 - Qubes Disk Space Monitor cannot handle deleted qubes (QubesVMNotFoundError: No such domain)

### ISSUE THREAD

**Issue by unknown-ter** [QubesOS/qubes-issues#7143]
### Qubes OS release
4.1 RC2

### Brief summary
From user perspective it seems that Qubes Disk Space Monitor sometimes does not react anymore and tray icon does not respond to clicks (I will refer to the app as QDSM).
Aftere deleting a qube, doing 
```
journalctl -f
```
with a subsequent click on the menu icon will reveal `QubesVMNotFoundError`.

### Steps to reproduce
- Create a qube
- Verify QDSM works / unfolds the popup
- Delete a qube
- In one terminal follow logs via `sudo journalctl -f` in dom0
- Click shortly after on tray icon
- QDSM does not react/show any menu 

### Expected behavior
QDSM should work after a qube beeing deleted.
 If an older cache is accessed, it should be resetted after deleteing qubes.

### Actual behavior
Example stack trace:
```
Dec 19 21:37:46 dom0 widget-wrapper[6517]: Traceback (most recent call last):
Dec 19 21:37:46 dom0 widget-wrapper[6517]:   File "/usr/lib/python3.8/site-packages/qui/tray/disk_space.py", line 382, in make_menu
Dec 19 21:37:46 dom0 widget-wrapper[6517]:     vm_data = VMUsageData(self.qubes_app)
Dec 19 21:37:46 dom0 widget-wrapper[6517]:   File "/usr/lib/python3.8/site-packages/qui/tray/disk_space.py", line 48, in __init__
Dec 19 21:37:46 dom0 widget-wrapper[6517]:     self.__populate_vms()
Dec 19 21:37:46 dom0 widget-wrapper[6517]:   File "/usr/lib/python3.8/site-packages/qui/tray/disk_space.py", line 53, in __populate_vms
Dec 19 21:37:46 dom0 widget-wrapper[6517]:     if vm.is_running():
Dec 19 21:37:46 dom0 widget-wrapper[6517]:   File "/usr/lib/python3.8/site-packages/qubesadmin/vm/__init__.py", line 236, in is_running
Dec 19 21:37:46 dom0 widget-wrapper[6517]:     return self.get_power_state() not in ('Halted', 'NA')
Dec 19 21:37:46 dom0 widget-wrapper[6517]:   File "/usr/lib/python3.8/site-packages/qubesadmin/vm/__init__.py", line 188, in get_power_state
Dec 19 21:37:46 dom0 widget-wrapper[6517]:     power_state = self._get_current_state()['power_state']
Dec 19 21:37:46 dom0 widget-wrapper[6517]:   File "/usr/lib/python3.8/site-packages/qubesadmin/vm/__init__.py", line 204, in _get_current_state
Dec 19 21:37:46 dom0 widget-wrapper[6517]:     response = self.qubesd_call(self._method_dest, 'admin.vm.CurrentState')
Dec 19 21:37:46 dom0 widget-wrapper[6517]:   File "/usr/lib/python3.8/site-packages/qubesadmin/base.py", line 74, in qubesd_call
Dec 19 21:37:46 dom0 widget-wrapper[6517]:     return self.app.qubesd_call(dest, method, arg, payload,
Dec 19 21:37:46 dom0 widget-wrapper[6517]:   File "/usr/lib/python3.8/site-packages/qubesadmin/app.py", line 748, in qubesd_call
Dec 19 21:37:46 dom0 widget-wrapper[6517]:     return self._parse_qubesd_response(return_data)
Dec 19 21:37:46 dom0 widget-wrapper[6517]:   File "/usr/lib/python3.8/site-packages/qubesadmin/base.py", line 109, in _parse_qubesd_response
Dec 19 21:37:46 dom0 widget-wrapper[6517]:     raise exc_class(format_string, *args)
Dec 19 21:37:46 dom0 widget-wrapper[6517]: qubesadmin.exc.QubesVMNotFoundError: No such domain: <name of just deleted qube>
```
, where `<name of just deleted qube>` is placeholder for deleted qube

**Comment by 3hhh** [comment]
Probably the widget wasn't updated yet to handle https://github.com/QubesOS/qubes-core-admin/pull/398

I guess it should just ignore removed VMs / not display them anymore on the exception.

**Comment by AmCrNi** [comment]
this change worked for me https://github.com/AmCrNi/qubes-desktop-linux-manager/commit/dde5f5d78a35b4b323de7219a1d76a45a76d4a69?diff=unified

**Comment by marmarek** [comment]
> this change worked for me [AmCrNi/qubes-desktop-linux-manager@dde5f5d?diff=unified](https://github.com/AmCrNi/qubes-desktop-linux-manager/commit/dde5f5d78a35b4b323de7219a1d76a45a76d4a69?diff=unified)

Sounds exactly like what it's needed? Can I take this commit directly? Or better: can you open a pull request with it?

**Comment by AmCrNi** [comment]
Sure thing. https://github.com/QubesOS/qubes-desktop-linux-manager/pull/119

apologies I'm not yet familiar with coding standards here.
