### ISSUE TITLE
Qubes R4.1 Crashes (Possible Memory Leak?)

### ISSUE THREAD

**Issue by e6lk7dqzm83p** [QubesOS/qubes-issues#7146]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
R4.1

### Brief summary
When I have longer video conferences (1-2 hours or more) in Google Meets in Chromium Qubes crashes; when I reboot I can't get any characters to show up in the password screen (to decrypt the boot drive); if I go to the terminal I see the characters (as asterisks) present and I can decrypt the drive and boot it.

Originally I thought it was a thermal issue, but that seemed to have been resolved and still was a problem.  I've noticed some instability with chromium in other VMs.

### Steps to reproduce
See above

### Expected behavior
The computer does not crash. 

### Actual behavior
The computer crashes

**Comment by DemiMarie** [comment]
Can you provide some information about your hardware?  Is there anything in the system logs that indicates a kernel panic in dom0?

> when I reboot I can't get any characters to show up in the password screen (to decrypt the boot drive)

This seems like a hardware problem to me.  I would expect a software problem to go away on reboot, but it seems that this problem does not.

**Comment by unman** [comment]
I do not use Chromium or Google Meets - I *do* have extensive video conferences,
including browser based.
On x220 and x230 with 16GB RAM, I have not encountered this.

Is it possible to run these conferences in some other browser for
comparison?

I suspect a hardware issue - could you set up a cooling fan aimed at/in the
machine?

**Comment by e6lk7dqzm83p** [comment]
Hi,
I have a System76 Pangolin with 64gb of RAM.  

@DemiMarie the password is recorded in the terminal screen (I see the asterisks), not in the main/typical password screen.

@unman, Google Meets only works in Chromium.

I'll keep an eye on the temperature (I uses sensors), but even if it's a thermal issue, it's a thermal issue due to some inefficiency in how Qubes is using the underlying HW (there's no reason why this combo should cause such high temps compared to any other operation).  I'll keep an eye on this and report back.

Thank you all!

**Comment by e6lk7dqzm83p** [comment]
I'm starting to think this is likely a HW issue (overheating), but I'm unclear why such a thermal load to be generated. 

I'll close this as it seems hyperspecific to me, but I do wonder if there's a way to have Qubes be more efficient.
