### ISSUE TITLE
Qubes Update: Allow to select all update targets easily

### ISSUE THREAD

**Issue by rwiesbach** [QubesOS/qubes-issues#7147]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### The problem you're addressing (if any)
If I want to check updates for each and every qube, I may have to select them one by one.

### The solution you'd like
A "select all" checkbox and/or a shortcut, maybe Ctrl+A and then space for selection

### The value to a user, and who that user might be
Save a little time each and every time it is used

**Comment by alimirjamali** [comment]
It is possible to click `checkbox_column` header two times to select all of them. See video below:

https://github.com/user-attachments/assets/a80c6a5f-29ec-4af4-8f77-eca454cd7c0c

Having said that, connecting `Ctrl+A` to select all in Intro Page is a good idea. I will work on it.

**Comment by alimirjamali** [comment]
PR Submitted

Review priority: Low

This is how it turns out:

https://github.com/user-attachments/assets/72188d70-e952-4862-bd6c-a172d78f4620
