### ISSUE TITLE
Stubdom gui agent crushes after an attempt fullscreen

### ISSUE THREAD

**Issue by jevank** [QubesOS/qubes-issues#7148]
### Qubes OS release
R4.1 with current-testing updates

### Brief summary
HVM gui-agent window could be forced to fullscreen when it has same resolution as dom0 screen with Alt+F11. After [upgrade components](https://github.com/QubesOS/updates-status/issues/2758) it leads to gui-agent fail with messages:
```
[2021-12-22 11:45:39] qubes_gui: got unknown msg type 145, ignoring
[2021-12-22 11:45:39] BUG: qubes_gui: got unknown msg type 145, but not ignored earlier
[2021-12-22 11:45:39] E: [vchan-sink] module-vchan-sink.c: .[1;31msink cork req state =1, now state=0.[0m
[2021-12-22 11:45:39] E: [vchan-sink] module-vchan-sink.c: .[1;31msource cork req state =1, now state=0.[0m
```  

### Steps to reproduce

Set windows 10 VM screen resolution same as dom0 and Alt+F11

### Expected behavior
Windows force to fullscreen

### Actual behavior
Window disappears

**Comment by jevank** [comment]
Reported with Qubes OS Forum https://forum.qubes-os.org/t/testing-windows-and-qwt-in-r4-1/1143/120

**Comment by jevank** [comment]
Rename to get bit more attention. 
@marmarek  @fepitre The fix looks simple, but meson build hasn't been merged to qubes-gui-agent-xen-hvm-stubdom repository yet.

**Comment by Mxxel** [comment]
Same issue with Windows 7 HVM and Qubes 4.1.0-rc3.

**Comment by fepitre** [comment]
@jevank I'll try to reproduce and fix that in the next days.

**Comment by fepitre** [comment]
@marmarek is already on it!
