### ISSUE TITLE
External monitor shows qubes desktop background and mouse movement, but no window updates

### ISSUE THREAD

**Issue by mylostone** [QubesOS/qubes-issues#7150]
### Qubes OS release

R4.0

### Brief summary
When connecting an external monitor, the monitor is detected and I can get it to sort of work (using xfce4-display-settings) by setting the refresh rate to 24Hz. The monitor will display the qubes desktop background with the logo, and the mouse cursor movements update as expected (using the default 60Hz usually results in some strange artifacts with what seem like huge versions of things with black horizontal lines all through the display ... still see mouse cursor movement).

If I move a window onto the monitor it will not display at all, but the mouse cursor still shows up. Then, if I leave the window partially (or completely) moved onto the monitor and then toggle the refresh rate to 60Hz and back to 24Hz, the monitor will display a static image of the window in question. The window can be moved back to the laptop monitor, but the static image remains on the external monitor. Retoggling 60Hz->24Hz clears the static image of the window and only the qubes desktop background is displayed.

The window in question can __usually__ still receive mouse and keyboard input (e.g. I can type commands in a terminal), including mouse-focus when mousing over the actual position of the window (as opposed to the apparent position, e.i. after moving the window, though its position on the external monitor doesn't appear to change). In some cases, the window will __not__ accept input any longer, although it does appear to still receive focus when moused-over (the cursor goes from hollow to solid).

I also just noticed that when the external monitor is plugged in, some windows on the laptop monitor don't seem to receive mouse clicks (e.g. emacs is OK, but firefox isn't getting any clicks).

### Steps to reproduce

See above.

### Expected behavior

All programs and windows behave the same on all monitors. Window updates are reflected in the external monitor.   

### Actual behavior

No window updates are reflected in the external monitor.

**Comment by mylostone** [comment]
UPDATE:

  For the record, I am running a Lenovo Extreme X1 Gen3. I have the UEFI/BOIS Display -> set to "Integrated Graphics".

  I'm not sure if something else changed, or if I didn't quite try this exact recipe. My external monitor is now working as expected.

  In order to get the external display to work as expected, one must boot with the HDMI cable disconnected. Once the machine is booted and one is logged in, then connect the HDMI cable and configure the display as usual (for me that means xfce4-display-settings), with the caveat that the refresh rate must be set to 24Hz.

**Comment by andrewdavidwong** [comment]
Closing this for now as it appears that the issue no longer affects any Qubes users. If anyone believes this is a mistake, or if anyone is still affected by this issue, please leave a comment, and we'll be happy to reopen this. Thank you.
