### ISSUE TITLE
[openQA] splitgpg tests fail: thunderbird closes right after opening

### ISSUE THREAD

**Issue by deeplow** [QubesOS/qubes-issues#7151]
## Observation

OpenQA has been failing in splitgpg tests ([example 1](https://openqa.qubes-os.org/tests/26805#step/TC_10_Thunderbird_debian-11/1), [example 2](https://openqa.qubes-os.org/tests/26805#step/TC_10_Thunderbird_fedora-34/1) and [example 3](https://openqa.qubes-os.org/tests/26805#step/TC_10_Thunderbird_fedora-34-xfce/1) -- all in the same test run)

As can be seen in the following image [from this video timestamp](https://openqa.qubes-os.org/tests/26805/video?filename=video.ogv&t=383), thunderbird stops right after it starts
![Screenshot 2021-12-24 at 07-10-36 Qubes OS openQA Video](https://user-images.githubusercontent.com/47065258/147351773-33ce8471-1ef1-4d63-8ccf-0d9c8cc7b32e.png)

## Test suite description
system_tests_splitgpg

## Reproducible
Happens sometimes. (plotted with [this](https://github.com/deeplow/openqa-tests-qubesos/blob/stability-utils-decoupled-child-jobs/utils/openqa_investigator.py))

![Figure_122](https://user-images.githubusercontent.com/47065258/147352102-b26d27b5-2e9c-4922-b08a-b222e327b5c4.png)

## Expected result

Last good: https://openqa.qubes-os.org/tests/24868

**Comment by deeplow** [comment]
We may need to increase the timeout of [for getting the app](https://github.com/QubesOS/qubes-app-linux-split-gpg/blame/master/tests/test_thunderbird.py#L83).

Sad to see the history of that piece of code:
  - 20 tries [6 years ago](https://github.com/QubesOS/qubes-app-linux-split-gpg/blame/8cc5f5cf2f05a9cec1efd49a5e7bd86b21118ac0/tests/test_thunderbird.py#L48)
  - 30 tries [Oct 26th 2018](https://github.com/QubesOS/qubes-app-linux-split-gpg/blame/b37761835149108841e900f028214502f585d740/tests/test_thunderbird.py#L65)
  - 50 tries [jan 21st 2019](https://github.com/QubesOS/qubes-app-linux-split-gpg/blame/4f5677284e27cccac7dd041dcf79bace88e58a31/tests/test_thunderbird.py#L89)
  - ??? tries Dec 2021

This may indicate things are getting slower, but not necessarily. Even if not likely, dogtail could be doing faster retries which would mean it's actually faster... (although not very likely the case)

**Comment by DemiMarie** [comment]
Is there a way to get Thunderbird out of the test entirely?  Thunderbird just invokes `/usr/bin/qubes-gpg-client-wrapper`

**Comment by deeplow** [comment]
> Is there a way to get Thunderbird out of the test entirely? Thunderbird just invokes `/usr/bin/qubes-gpg-client-wrapper`

I'm guessing the point with this integration test is not only the use of `/usr/bin/qubes-gpg-client-wrapper` (since that would be a unit test) but rather knowing if the way it uses it (which may change) somehow breaks something.

Knowing what commands it calls from `qubes-gpg-client-wrapper` and doing just that would for sure improve a lot the stability of this test, but it could miss some other things like the timing, how Thunderbird interprets those responses, random tb freezes when communication to the gpg-client, etc.

**Comment by deeplow** [comment]
https://github.com/QubesOS/qubes-app-linux-split-gpg/pull/51 should mitigate this.
