### ISSUE TITLE
Hubert Servidor

### ISSUE THREAD

**Issue by Kochise** [QubesOS/qubes-issues#7154]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release (if applicable)

Qubes OS 4.0

### Brief summary

Check this channel :

https://www.youtube.com/channel/UCf2repeCl1_k8JlF4ZTA00g/videos

**Comment by fepitre** [comment]
Based on our [issue tracking guidelines](https://www.qubes-os.org/doc/issue-tracking/), this does not appear to be suitable for `qubes-issues`. We ask that you please post this on the [Qubes Forum or `qubes-users` mailing list](https://www.qubes-os.org/support/) instead. If, after reading our [issue tracking guidelines](https://www.qubes-os.org/doc/issue-tracking/), you believe we are mistaken, please leave a brief comment explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.
