### ISSUE TITLE
Integrate Tresor kernel patch for cold boot attack protection of the disk encrytion key

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#716]
**Reported by joanna on 24 Feb 2013 15:22 UTC**
More details and thoughts:

https://groups.google.com/group/qubes-devel/msg/623ab08c2c743e5e

We need to somehow "integrate" all the various passphrases: LUKS, Tresor's and screenlocker preferably into one.

Migrated-From: https://wiki.qubes-os.org/ticket/716

**Comment by esote** [comment]
@marmarek It appears that the README, original paper, AESSE paper, and patch file downloads are all broken links. I think it's safe to say this project is dead.

**Comment by esote** [comment]
cc @andrewdavidwong, do you have any opinion on the possibility of this ever being implemented?

**Comment by andrewdavidwong** [comment]
Closing as "won't do." If anyone has a new reason for why this should be done, please leave a comment, and we'll be happy to take another look. Thank you.
