### ISSUE TITLE
Consider creating 4.0.5 iso

### ISSUE THREAD

**Issue by unman** [QubesOS/qubes-issues#7161]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Brief summary
The 4.0.4 iso ships with outdated templates: Fedora, Debian and Whonix all have later major releases.
In addition there are many patches and updated packages available in dom0 and templates.

Unless 4.1 is *imminent*, there would be value in releasing an updated iso for 4.0.5, so that new installs have the latest supported versions.

- [x] update references to included templates (installer, salt)
- [ ] build new ISO
- [ ] release for testing
- [ ] release (upload to mirrors, announce)

**Comment by andrewdavidwong** [comment]
Given that 4.1 has now been released, should this remain open?

**Comment by DemiMarie** [comment]
I am inclined to say no, since users should be installing R4.1, not R4.0.  R4.0 is supported to give existing users time to migrate.

**Comment by andrewdavidwong** [comment]
Closing as "won't do." If anyone has a new reason for why this should be done, please leave a comment, and we'll be happy to take another look. Thank you.
