### ISSUE TITLE
Running salt scripts against app vms does not work in 4.1 after upgrade

### ISSUE THREAD

**Issue by ghost** [QubesOS/qubes-issues#7162]
### Qubes OS release
4.1 rc3 (in-place upgrade from 4.0)

### Brief summary
While changing single template vms with Salt does work now after fixing  #7122 I am not able to run Salt against regular app vms.

I have a simple salt state to clean up cache data and similar in the vms.

I run it with
`$ qubesctl --app state.highstate`

At first it seems to work, `disp-mgmt-test` is started with 192MB memory but the actual app vm is never started.
The disp-mgmt app runs for some time with some cpu usage while the next mgmt vm is started and then shows the following error for each app vm after some time:

`test: ERROR (exception No such domain: 'disp-mgmt-test')`

`journalctl` does not show any relevant logs for this errors, besides:
```
Dec 30 08:08:01 dom0 qubesd[1740]: vm.disp-mgmt-test: Start failed: Cannot connect to qrexec agent for 60 seconds, see /var/log/xen/console/guest-disp-mgmt-test.log for details
```

I did not find any relevant errors in `/var/log/xen/console/guest-disp-mgmt-test.log`.

But `qrexec.disp-mgmt-test.log` shows the following:
```
$cat qrexec.disp-mgmt-test.log
domain dead
2021-12-30 08:08:02.046 qrexec-daemon[6435]: qrexec-daemon.c:340:init: cannot connect to qrexec agent: No such file or directory
```

```
$ cat mgmt-test.log
2021-12-30 08:06:55,280 calling 'state.highstate'...
```

```
$ cat qubesdb.disp-mgmt-test.log
vchan closed
reconnecting
vchan closed
```
Let me know if you need any additional log.

### Steps to reproduce

1. Create a simple salt script for apps and activate it
2. Run `qubesctl --app state.highstate`
3. Upgrade in-place to QubesOs 4.1 rc3
4. Run `qubesctl --app state.highstate` again

### Expected behavior

The disp-mgmt vms are started as well as the app vm and the Salt scripts are executed.

### Actual behavior

Only the disp-mgmt vms are started but not the actuall app vm and nothing is executed.

**Comment by unman** [comment]
This works for me without any problems.
That said, I have more initial RAM allocated than you do.
If I drop the RAM to 192MB I see the same "No such domain" error.

I'm a great trimmer, and *nothing* I have is running with initial RAM as low as that.

Did this work in 4.0 with 192MB allocated? 
Does it work against templates in 4.1 with 192MB allocated?
If you increase the RAM does that fix the problem for appVMs?

**Comment by ekaflaer** [comment]
@unman Thanks for testing.

It worked in 4.0 but even then I sometimes had issues with regular VMs which had less ram then 200MB. That's why I increased it for all my vms.

I am wondering though how do I change the initial ram of the management vms?

My `Minimum qube memory` is already 220, I have tried to change the ram by changing the settings of a management vm but this did not work either.

Thanks in advance.

**Comment by ekaflaer** [comment]
@unman Maybe it got missed in the previous post, how can I change the RAM configuration of the mgmt vms?

I have never changed the RAM configuration on purpose and `Minimum qube memory` setting had no effect, so it might be relevant for the in place upgrade.

**Comment by ekaflaer** [comment]
@andrewdavidwong is it anywhere documented how can I increase the memory default for the salt vms? Like I have said my minimal ram configuration is already bigger then the 192MB.

**Comment by andrewdavidwong** [comment]
> @andrewdavidwong is it anywhere documented how can I increase the memory default for the salt vms? Like I have said my minimal ram configuration is already bigger then the 192MB.

I don't know. I just let automatic memory balancing take care of everything ([qmemman](https://www.qubes-os.org/doc/qmemman/)).

Please note that the issue tracker (`qubes-issues`) is not intended to be a place for fielding questions. Instead, we have other [venues meant for asking questions, asking for help, and having discussions](https://www.qubes-os.org/support/). (By contrast, the issue tracker is more of a technical tool intended to support our developers in their work.) Thank you for your understanding!

**Comment by marmarek** [comment]
> At first it seems to work, `disp-mgmt-test` is started with 192MB memory but the actual app vm is never started.

As unman said, the low memory here is most likely cause. Check `memory` property on `default-mgmt-dvm` (or whatever you have set for `management_dispvm` qubes-prefs).
