### ISSUE TITLE
black screen when boot from usb

### ISSUE THREAD

**Issue by hellobigballs** [QubesOS/qubes-issues#7165]
hi i am using a 8gb usb to try to install qubes os but when i boot qubes off my usb, it does a little then the screen goes black. i’ve seen other forums but none of them have worked so if there is a solution please tell me.

**Comment by sajkbflksadbfkasdjf** [comment]
Please add some details on the qubes version used and your hardware. And the proper place to ask about this is the forum: https://forum.qubes-os.org/c/user-support/5

**Comment by andrewdavidwong** [comment]
[The issue tracker is not the right place to ask for help or support.](https://www.qubes-os.org/doc/issue-tracking/#i-need-help-have-a-question-or-want-to-discuss-something)
