### ISSUE TITLE
ARCH template build fails due to dependency issues

### ISSUE THREAD

**Issue by sajkbflksadbfkasdjf** [QubesOS/qubes-issues#7166]
### Qubes OS release
Release 4.1 (using fedora-34 as a build-vm due to issues with fedora-33-minimal)
### Brief summary
When building the arch linux template the build process fails on `make template` due to an infinite loop caused by dependency issues
### Steps to reproduce
https://github.com/Qubes-Community/Contents/blob/master/docs/building/building-archlinux-template.md
build fails on `make qubes-vm` due to a python3 issue. Fix is here and ready to be merged: https://github.com/QubesOS/qubes-core-qubesdb/pull/43
Then, after applying the commits, normally build the qubes-vm-stuff (works fine) and issue `make template`

### Expected behavior
I get a shiny new iso to install
### Actual behavior
```
warning: cannot resolve "X-ABI-VIDEODRV_VERSION=24.0", a dependency of "qubes-vm-gui"
warning: cannot resolve "X-ABI-XINPUT_VERSION=24.1", a dependency of "qubes-vm-gui"
warning: cannot resolve "qubes-vm-gui", a dependency of "qubes-vm-dependencies"
warning: cannot resolve "pulseaudio<14.3", a dependency of "qubes-vm-pulseaudio"
warning: cannot resolve "qubes-vm-pulseaudio", a dependency of "qubes-vm-dependencies"

:: The following package cannot be upgraded due to unresolvable dependencies:
      qubes-vm-dependencies

:: Do you want to skip the above package for this upgrade? [y/N] error: failed to prepare transaction (could not satisfy dependencies)

:: unable to satisfy dependency 'python<3.10' required by qubes-vm-core
:: unable to satisfy dependency 'qubes-vm-core' required by qubes-vm-dependencies
:: unable to satisfy dependency 'X-ABI-VIDEODRV_VERSION=24.0' required by qubes-vm-gui
:: unable to satisfy dependency 'X-ABI-XINPUT_VERSION=24.1' required by qubes-vm-gui
:: unable to satisfy dependency 'qubes-vm-gui' required by qubes-vm-dependencies
:: unable to satisfy dependency 'pulseaudio<14.3' required by qubes-vm-pulseaudio
:: unable to satisfy dependency 'qubes-vm-pulseaudio' required by qubes-vm-dependencies
```

**Comment by sajkbflksadbfkasdjf** [comment]
I actually did a bit of hacking and tried using older packages (e.g. pacman -U https://archive.archlinux.org/packages/x/xorg-server/xorg-server-1.20.13-3-x86_64.pkg.tar.zst). Still somehow doesn't update, will look into it tomorrow

**Comment by lubellier** [comment]
@sajkbflksadbfkasdjf please could you try again, because the follow issues are now solved :
- #7048 solved by [xorg ABI](https://github.com/QubesOS/qubes-gui-agent-linux/commit/0fa4e24e2d4945156093ddfee35eb60119828509) 
- #7121 python 3.11solved by [qubes-core-agent-linux PR#344](https://github.com/QubesOS/qubes-core-agent-linux/pull/344) and [qubes-core-qubesdb PR#43](https://github.com/QubesOS/qubes-core-qubesdb/pull/43)
- #6807 is closed

**Comment by sajkbflksadbfkasdjf** [comment]
Works fine... Only fix for https://github.com/QubesOS/qubes-issues/issues/7180 and workaround for https://github.com/QubesOS/qubes-issues/issues/7098 need to be manually applied
