### ISSUE TITLE
4.1 Bionic build of core-agent-linux fails

### ISSUE THREAD

**Issue by unman** [QubesOS/qubes-issues#7167]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
4.1

### Brief summary
As title

### Steps to reproduce
1. Set up build on fedora-34
2. Select 4.1, bionic
3. make qubes-vm

### Expected behavior
Build all packages

### Actual behavior
Build of core-agent-linux fails.
```
make[1]: Entering directory '/home/user/qubes-src/core-agent-linux'
Makefile:1: *** Invalid file operation: <version.  Stop.
make[1]: Leaving directory '/home/user/qubes-src/core-agent-linux'
dh_auto_clean: make -j4 -O distclean returned exit code 2
debian/rules:12: recipe for target 'clean' failed
make: *** [clean] Error 25
dpkg-buildpackage: error: fakeroot debian/rules clean subprocess returned exit status 2
make[2]: *** [/home/user/qubes-builder/qubes-src/builder-debian//Makefile-legacy.debian:56: dist-package] Error 2
```

This is result of commit 00b491433bff021a74f15850945c6a898842069e

**Comment by DemiMarie** [comment]
This is due to my changes, but it might just mean that the version of GNU make is too old.
