### ISSUE TITLE
modify qrexec policy syntax to allow autostart=no in the policy (allows to avoid unexpected autostart of VMs issue)

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#7168]
Quote @marmarek in https://phabricator.whonix.org/T930

> modify qrexec policy syntax to allow `autostart=no` in the policy

> This way, `whonix.SdwdateStatus` could be configured to not start the domain. 

----

related:

* https://github.com/QubesOS/qubes-issues/issues/5930
* https://github.com/QubesOS/qubes-issues/issues/5253

**Comment by marmarek** [comment]
Duplicate of https://github.com/QubesOS/qubes-issues/issues/5952 (already done)

**Comment by andrewdavidwong** [comment]
This appears to be a [duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If anyone believes this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.
