### ISSUE TITLE
qubes-core-admin-addon-whonix sdwdate-gui qrexec service should use autostart=no

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#7169]
* https://github.com/QubesOS/qubes-core-admin-addon-whonix/blob/master/qubes-rpc-policy/whonix.GatewayCommand.policy
* https://github.com/QubesOS/qubes-core-admin-addon-whonix/blob/master/qubes-rpc-policy/whonix.NewStatus.policy
* https://github.com/QubesOS/qubes-core-admin-addon-whonix/blob/master/qubes-rpc-policy/whonix.SdwdateStatus.policy

To test, I would just have to append `,autostart=no`, right? I.e.

`allow`
->
`allow,autostart=no`
?

related:
https://github.com/QubesOS/qubes-issues/issues/5952

**Comment by marmarek** [comment]
Yes, that should work, although while at it I'd convert it all to the new policy format: `/etc/qubes/policy.d/80-whonix.policy`:
```
# service            arg source            target            action params
whonix.SdwdateStatus  *  @tag:anon-gateway @tag:anon-vm      allow autostart=no
whonix.SdwdateStatus  *  sys-whonix        @tag:anon-vm      allow autostart=no
whonix.SdwdateStatus  *  @anyvm            @anyvm            deny
whonix.NewStatus      *  @tag:anon-vm      @tag:anon-gateway allow autostart=no
whonix.NewStatus      *  @tag:anon-vm      sys-whonix allow  autostart=no
whonix.NewStatus      *  @anyvm            @anyvm            deny
whonix.GatewayCommand *  @tag:anon-gateway @tag:anon-vm      allow autostart=no
whonix.GatewayCommand *  sys-whonix        @tag:anon-vm      allow autostart=no
whonix.GatewayCommand *  @anyvm            @anyvm            deny
```
(new format uses space for separating action params, not coma)
This should be placed instead of old policy files (simply remove them for testing)
What arguments those services take? The above allows any, but if stricter policy is desired, you can use `+<arg>` instead of `*` (especially - to allow only empty argument, use just `+`).

See https://www.qubes-os.org/news/2020/06/22/new-qrexec-policy-system/#new-policy-format for details

**Comment by adrelanos** [comment]
Sounds great, looks great! (I assume you wouldn't mind about some extra newlines.)

Since this is for sdwdate-gui only and not required for all of Whonix, would file name `/etc/qubes/policy.d/80-whonix-sdwdate-gui.policy` be acceptable?

If it shall be just 1 policy file (which is good), what would be the dom0 packaging mechanism to get rid of the legacy files?
(whonix.GatewayCommand.policy, whonix.NewStatus.policy, whonix.SdwdateStatus.policy)
Any example how to clean up such files somewhere?

**Comment by adrelanos** [comment]
@marmarek 
> Yes, that should work, although while at it I'd convert it all to the new policy format: `/etc/qubes/policy.d/80-whonix.policy`:
> 
> ```
> # service            arg source            target            action params
> whonix.SdwdateStatus  *  @tag:anon-gateway @tag:anon-vm      allow autostart=no

Does not work.

dom0 qrexec-policy-daemon error loading policy invalid action: @tag:anon-gateway

Syntax error?

**Comment by adrelanos** [comment]
https://github.com/QubesOS/qubes-core-admin-addon-whonix/pull/12

**Comment by marmarek** [comment]
> dom0 qrexec-policy-daemon error loading policy invalid action: @tag:anon-gateway

You sure you put it into the correct directory? New format policy lives in `/etc/qubes/policy.d`, not `/etc/qubes-rpc/policy`.

**Comment by brendanhoar** [comment]
> You sure you put it into the correct directory?

Maybe add a text file to the directory indicating (by name) that the dir is deprecated in R4.1; with file contents pointing to the correct location?

B

**Comment by adrelanos** [comment]
> > dom0 qrexec-policy-daemon error loading policy invalid action: @tag:anon-gateway
> 
> You sure you put it into the correct directory? New format policy lives in `/etc/qubes/policy.d`, not `/etc/qubes-rpc/policy`.

Indeed, that was my mistake.

@adrelanos:
> Any example how to clean up such files somewhere?

Didn't find any.

@adrelanos:
> If it shall be just 1 policy file (which is good), what would be the dom0 packaging mechanism to get rid of the legacy files? (whonix.GatewayCommand.policy, whonix.NewStatus.policy, whonix.SdwdateStatus.policy)

That seems rather unclear, complex as per:
https://www.cl.cam.ac.uk/~jw35/docs/rpm_config.html

**Comment by adrelanos** [comment]
> Yes, that should work, although while at it I'd convert it all to the new policy format: `/etc/qubes/policy.d/80-whonix.policy`:
> 
> ```
> # service            arg source            target            action params
> whonix.SdwdateStatus  *  @tag:anon-gateway @tag:anon-vm      allow autostart=no
> whonix.SdwdateStatus  *  sys-whonix        @tag:anon-vm      allow autostart=no
> whonix.SdwdateStatus  *  @anyvm            @anyvm            deny
> whonix.NewStatus      *  @tag:anon-vm      @tag:anon-gateway allow autostart=no
> whonix.NewStatus      *  @tag:anon-vm      sys-whonix allow  autostart=no
> whonix.NewStatus      *  @anyvm            @anyvm            deny
> whonix.GatewayCommand *  @tag:anon-gateway @tag:anon-vm      allow autostart=no
> whonix.GatewayCommand *  sys-whonix        @tag:anon-vm      allow autostart=no
> whonix.GatewayCommand *  @anyvm            @anyvm            deny
> ```

Working great, testing this from now on.

**Comment by adrelanos** [comment]
https://github.com/QubesOS/qubes-core-admin-addon-whonix/pull/13
