### ISSUE TITLE
qvm-template: Unable to view templates repositories other than templates-itl in 4.1-rc3 

### ISSUE THREAD

**Issue by drewlander** [QubesOS/qubes-issues#7170]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

4.1 (rc3)

### Brief summary

I searched the issues and could not find a duplicate of this issue. If I missed it I apologize.

This only happened when I did a fresh install of 4.1-r3. This worked just fine in 4.1-r2
I have since done yet another reinstall (After messing with sys-gui-gpu) and I am having the same issue.

Whenever I try to list ANY template that is not in the "default" repositories, it does not display them.
For example:
```
qvm-template --enablerepo=qubes-templates-itl-testing list
```
I would expect to see qubes-template-fedora35.x under "Available Templates" but none of that is listed there.
I would also try 
```
qvm-template --enablerepo=qubes-tempaltes-community-testing 
```
and it would not return anything in the testing repository either. It would only show what is in the standard repositories.
I have even tried manually enabling the repository in qubes-template.repo, running qubes-dom0-update, then qvm-template list and none of the templates in the testing repository would show, only the ones in the templates-itl repository. Nothing from the testing repository would show under "Available templates"

I also tried
```
$ sudo qubes-dom0-update --enablerepo=qubes-templates-community qubes-template-fedora-35
```
but that redirects to qvm-template install and it returns "fedora-35" not found

### Steps to reproduce

* install 4.1r3

Run
```
qvm-template --enablerepo=qubes-templates-community list
```

### Expected behavior* 

I would see the templates from the testing repository under "Available Templates"

### Actual behavior

I do not see the templates from the testing repository under "Available Templates"

**Comment by DemiMarie** [comment]
Confirmed.

**Comment by unman** [comment]
Is this related to #7133 ?
A fix for *that* is in the pipeline.

**Comment by 0xdd7fq** [comment]
@unman qvm-template which part of qubes-dom0-update is totally broken, I don’t understand how is 4.1-r3 realized without any ci/cd tests

**Comment by unman** [comment]
[quote]
@unman qvm-template which part of qubes-dom0-update is totally broken, I don???t understand how is 4.1-r3 realized without any ci/cd tests
[/quote]
There are such tests - clearly they failed in this case.
In any case, CI will not cover all cases of use tests - that's why this
is a rc - to allow users to identify problems *in use*.
The process seems to have worked.
