### ISSUE TITLE
Use XFS for qubes by default

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#7171]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### The problem you're addressing (if any)

ext4 does not support various nice features, such as reflinks.  It also has (or at least had) poor kernel AIO support, though with io_uring that is less relevant.  reflinks are very useful for all sorts of reasons.

### The solution you'd like

Use XFS instead.

### The value to a user, and who that user might be

All users will benefit from reflink support.

**Comment by marmarek** [comment]
You mean in-VM? Generally we [follow distribution defaults](https://www.qubes-os.org/faq/#what-is-qubes-attitude-toward-changing-guest-distros). Which means, for [Fedora 33 we should use btrfs](https://fedoraproject.org/wiki/Changes/BtrfsByDefault).

**Comment by DemiMarie** [comment]
> You mean in-VM? Generally we [follow distribution defaults](https://www.qubes-os.org/faq/#what-is-qubes-attitude-toward-changing-guest-distros). Which means, for [Fedora 33 we should use btrfs](https://fedoraproject.org/wiki/Changes/BtrfsByDefault).

Will this cause a significant performance regression?  My worry is that this is an inefficient CoW-on-CoW situation.

**Comment by marmarek** [comment]
> Will this cause a significant performance regression? My worry is that this is an inefficient CoW-on-CoW situation.

I don't think that matters for normal usage. But if that would be an issue, your proposed change would suffer the same.

Closing for the reason explained in previous comment.

**Comment by DemiMarie** [comment]
> proposed change would suffer the same.

XFS isn’t a CoW filesystems, but your other point stands.

**Comment by marmarek** [comment]
> XFS isn’t a CoW filesystem, but your other point stands.

You listed reflinks as one of the primary benefit - which is CoW... Similar to btrfs, if you don't like, you can not use this feature (but then why change?)

**Comment by DemiMarie** [comment]
> > XFS isn’t a CoW filesystem, but your other point stands.
> 
> You listed reflinks as one of the primary benefit - which is CoW... Similar to btrfs, if you don't like, you can not use this feature (but then why change?)

My understanding was that BTRFS is CoW by default, whereas XFS is not.

**Comment by rustybird** [comment]
> My understanding was that BTRFS is CoW by default, whereas XFS is not.

Indeed, but it looks like Btrfs mounted with `nodatacow` can do reflinks nowadays! Just tried it with kernel 5.15.5. I'm guessing at some point they've made the internal COW1 mode (or whatever it's properly called) generally available. Previously it was only used to snapshot *a subvolume containing* a nocow file.

Come to think of it, Btrfs mounted with `nodatacow` now seems like an attractive choice for VM volumes -  the user would get snapshots, reflinks, and online shrinking.

**Comment by DemiMarie** [comment]
> Come to think of it, Btrfs mounted with `nodatacow` now seems like an attractive choice for VM filesystems - the user would get subvolumes/snapshots, reflinks, and online shrinking.

I was not aware that `nodatacow` was a mount option!  That solves most of my worries regarding BTRFS.  Checksumming is still lost, but that can (and, IMO, should) be handled at the block layer.
