### ISSUE TITLE
archlinux: use python>=3.10

### ISSUE THREAD

**Issue by locriacyber** [QubesOS/qubes-issues#7173]
### The problem you're addressing (if any)
Python packages in arch repository won't work without symlink `site-package` to python 3.9's.

Related: #7048

### The solution you'd like

Rebuild all qubes os packages with python 3.10: #6333

### The value to a user, and who that user might be
- ability to get software upgrade on arch linux

**Comment by DemiMarie** [comment]
Is this still an issue?

**Comment by locriacyber** [comment]
I don't know. I have been building packages from source since. Never used package repository.

***

Just tried using this pacman repo

```
[qubes-r4.1-current]
Server = https://archlinux.qubes-os.org/r4.1/current/vm/archlinux/pkgs/
```
The result is, I can't even use the repo.

```
error: qubes-r4.1-current: key "CEDF003D544CCD1D1382E9138A871A1BBD7093EA" is unknown
:: Import PGP key CEDF003D544CCD1D1382E9138A871A1BBD7093EA? [Y/n] y
error: key "CEDF003D544CCD1D1382E9138A871A1BBD7093EA" could not be looked up remotely
error: failed to synchronize all databases (unexpected error)
```

**Comment by lubellier** [comment]
> Is this still an issue?

@DemiMarie : I don't see any issues with the python-3.10 transition, the current archLinux python version is python-3.10.5 and all is fine with my ArchLinux template and HVM...

> The result is, I can't even use the repo.

@locriacyber : I'm using this repo, maybe with `pacman-key --init` ?

**Comment by locriacyber** [comment]
> @locriacyber : I'm using this repo, maybe with pacman-key --init ?

No. pacman can't find key CEDF003D544CCD1D1382E9138A871A1BBD7093EA remotely. Can I have a copy of key CEDF003D544CCD1D1382E9138A871A1BBD7093EA?

**Comment by locriacyber** [comment]
closing as fixed

**Comment by lubellier** [comment]
> No. pacman can't find key CEDF003D544CCD1D1382E9138A871A1BBD7093EA remotely. Can I have a copy of key CEDF003D544CCD1D1382E9138A871A1BBD7093EA?

@locriacyber this key is in the [qubes-builder-archlinux](https://github.com/QubesOS/qubes-builder-archlinux/blob/master/keys/qubes-repo-archlinux-key.asc) git repository.

**Comment by locriacyber** [comment]
@marmarek Can you sign the key above?

**Comment by marmarek** [comment]
It is signed indirectly by being in a signed git repository. I'll not sign it with official qubes key, as Archlinux is a [community template](https://www.qubes-os.org/doc/templates/).
