### ISSUE TITLE
Private volume size for sys-usb and sys-firewall cannot be modified in R4.1 via UI - attempt leads to unexpected error popup.

### ISSUE THREAD

**Issue by brendanhoar** [QubesOS/qubes-issues#7174]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
R4.1rc2 updated to R4.1rc3 (w/ current-testing updates)

### Brief summary
Private volume size for sys-usb and sys-firewall cannot be modified in R4.1 via UI due to an unexpected error popup. Presumably an unexpected side effect of being a Named Disposable?

While I am unsure I would ever need to modify sys-usb private volume (others might?), in the past, I have found increasing the private volume for sys-firewall has been helpful if/when dom0 has a large update change set coming. Perhaps the need for this is mitigated due to the qvm-templates tool enforcing one template at a time, but I think this is still an unexpected result.

### Steps to reproduce
For sys-firewall, open Qubes Settings
You will be on the Basic tab
Navigate to Private storage max size, which defaults to 2.0GB.
Change value to 4.0GB.
Click OK.

Repeat for sys-usb.

### Expected behavior
No error and instances of sys-firewall have 4.0GB available on private volume.

### Actual behavior
Error message dialog.
- Title: [Dom0] Error while changing settings for sys-firewall
- Message: ERROR: Basic tab: \n Logical volume vm-sys-firewall-private-snap not found in volume group qubes_dom0.

Presumably this is due to default configuration of sys-firewall and sys-usb as Named Disposable?

Thanks,
Brendan

**Comment by rustybird** [comment]
Was the sys-usb DisposableVM shut down when you tried to resize its private volume? Resizing a snap_on_start volume only has a (temporary!) effect while the VM is running. When shut down it's an error or a no-op, depending on the storage driver.

If the storage system was changed to allow a snap_on_start volume's nominal size to be persistently larger than its source volume, that would make it necessary to resize the filesystem on the volume every time the VM is started (~1-2 seconds delay).

What you probably want is to resize the private volume of the sys-usb DisposableVM's template AppVM.

**Comment by brendanhoar** [comment]
> Was the sys-firewall DisposableVM shut down when you tried to resize its private volume? Resizing a snap_on_start volume only has a (temporary!) effect while the VM is running. When shut down it's an error or a no-op, depending on the storage driver.

Yes, it was shut down via ```qvm-shutdown --all --wait```

> If the storage system was changed to allow a snap_on_start volume's nominal size to be persistently larger than its source volume, that would make it necessary to resize the filesystem on the volume every time the VM is started (~1-2 seconds delay).
> 
> What you probably want is to resize the private volume of the DisposableVM's template AppVM.

That's exactly what I was doing.

I will note that the way that sys-usb and sys-firewall are installed under R4.1, there are *no* LVM volumes in the thin pool for these VMs until they are (auto-)started. This may be an important clue.

Brendan

**Comment by rustybird** [comment]
> ### Steps to reproduce
> 
> For sys-firewall, open Qubes Settings
> You will be on the Basic tab
> Navigate to Private storage max size, which defaults to 2.0GB.
> Change value to 4.0GB.

> > What you probably want is to resize the private volume of the DisposableVM's template AppVM.
> 
> That's exactly what I was doing.

No you were trying to resize the private volume of sys-firewall. What I meant was, resize the private volume of e.g. fedora-34-dvm instead. (The one that's shown as Template in the sys-firewall Qube Settings, or as the output of `qvm-prefs sys-firewall template`)

> They appear to be named disposables without the storage I have normally associated with a disposable template.

named DisposableVM != DisposableVM template

The only difference between a named DisposableVM (e.g. your sys-firewall) and a disp1234 DisposableVM is that the latter's auto_cleanup property is set to True, so it's deleted when it shuts down.

**Comment by AmCrNi** [comment]
I've tested this scenario on mine system and I wasn't able to reproduce it. I've installed qubes from scratch and I've restored app VMs from backup - without any sys-* vms. I don't have any testing updates enabled.
```
[root@dom0 ~]# lvs | grep firewall
  vm-sys-firewall-private-snap                   qubes_dom0 Vwi-aotz--   3.00g vm-pool   vm-fedora-34-dvm-private                       1.64   
```

**Comment by rustybird** [comment]
@AmCrNi are you sure that your sys-firewall is a DisposableVM and that it had been cleanly shut down before you tried?

**Comment by AmCrNi** [comment]
Isn't that expected? I mean if the disposable VM isn't running then lv is not created - therefore it cannot be resized.

**Comment by rustybird** [comment]
Exactly :)

AFAICT this is not a bug, pending confirmation from @brendanhoar
