### ISSUE TITLE
Failure to restore vm with disk size smaller than default

### ISSUE THREAD

**Issue by a-barinov** [QubesOS/qubes-issues#7176]
### Qubes OS release
4.1.0-rc3

### Brief summary
When trying to restore a TemplateVM with root or private volume smaller than default (10G and 2G respectively), restore fails with error "not enough data".
I have not tested other vm types or backups created in Qubes 4.0.

### Steps to reproduce
1. Create a new TemplateVM.
2. Shrink root volume to 2.5Gb and private volume to 0.5Gb, this requires a bit of manual fs, lvm and partition (in case of root volume) resizing.
3. Backup the VM.
4. Try restoring from the backup.

### Expected behavior
VM getting restored from backup and can be started without errors.

### Actual behavior
Trying to restore, you get the following error:
```
qubesadmin.backup: -> Restoring debian-full...
qubesadmin.backup: Extracting data: 1.8 GiB to restore
qubesadmin.backup: Failed to restore volume root of VM debian-full1: Data import failed: not enough data (copied 2684354560 bytes, expected 10737418240 bytes)
qubesadmin.backup: Failed to restore volume private of VM debian-full1: Data import failed: not enough data (copied 536870912 bytes, expected 2147483648 bytes)
qubesadmin.backup: -> Done.
```
Restored VM then cannot start.

**Comment by rustybird** [comment]
1. [This line of the restore code](https://github.com/QubesOS/qubes-core-admin-client/blob/v4.1.19/qubesadmin/backup/restore.py#L1881) should check for inequality

2. Storage driver support:
    1. `file-reflink`: works
    2. `lvm_thin`: see [this comment](https://github.com/QubesOS/qubes-issues/issues/5192#issuecomment-515377678)
    3. legacy `file`:  looks similar to `lvm_thin`

**Comment by marmarek** [comment]
> qubesadmin.backup: Failed to restore volume root of VM debian-full1: Data import failed: not enough data (copied 2684354560 bytes, expected 10737418240 bytes)

This is ~2.5G, while the root volume is 10G normally, so it isn't just about missing resize, it really got not enough data.

**Comment by rustybird** [comment]
@palainp Neat! `import_data_with_size()` instead of the current `resize()` + `import_data()` would work even for storage drivers that don't support shrinking.

[qubesadmin.backup.restore](https://github.com/QubesOS/qubes-core-admin-client/blob/master/qubesadmin/backup/restore.py) has the relevant code, but there's lots of indirection so it might have to be refactored a bit.

**Comment by a-barinov** [comment]
OK, I was kind of able to fix this, but due to too many API layers this is not the cleanest fix.

Contrary to what @rustybird said previously, the error message is actually triggered in [admin.vm.volume.Import](https://github.com/QubesOS/qubes-core-admin/blob/df6407f50811573760879a7a48b9243ea31e504a/qubes-rpc/admin.vm.volume.Import#L69) script, section starting from line 69. Commenting it out will get rid of the error, but your restored volumes will not be resized. I therefore decided to look for a cleaner way which sent me down a rabbit hole...

First, inspired by @palainp I made a similar change to restore code in [restore.py](https://github.com/QubesOS/qubes-core-admin-client/blob/d4bdee3dc56e5687e2c224feaa61d6b58a8f761c/qubesadmin/backup/restore.py)
```
+++ restore.py  2022-04-30 20:04:24.962001232 +0200
@@ -1866,7 +1866,7 @@
     def _handle_volume_data(self, vm, volume, stream):
         '''Wrap volume data import with logging'''
         try:
-            volume.import_data(stream)
+            volume.import_data_with_size(stream=stream, size=volume.size)
         except Exception as err:  # pylint: disable=broad-except
             self.log.error('Failed to restore volume %s of VM %s: %s',
                 volume.name, vm.name, err)
```

This was not enough though, as for whatever reason a function just below patched prohibits volume downsizing during restore, which I consider to be a bug. So one additional fix is needed:
```
+++ restore.py  2022-04-30 20:04:24.962001232 +0200
@@ -1874,8 +1874,7 @@
     def _handle_volume_size(self, vm, volume, size):
         '''Wrap volume resize with logging'''
         try:
-            if volume.size < size:
-                volume.resize(size)
+            volume.resize(size)
         except Exception as err:  # pylint: disable=broad-except
             self.log.error('Failed to resize volume %s of VM %s to %d: %s',
                 volume.name, vm.name, size, err)
```

This fixes restore code to properly take care of volume downsizing. I was hoping that this will do the job, but turned out the underlying storage driver cannot downsize volumes! I think this was done to prevent user from reducing volume size from qube settings or commend line (which is a right thing to do), but baking this into storage backend does sounds way too extreme to me. Anyway, I'm not keen to edit underlying Qubes API so I decided to fully restore the ability to downsize volumes.

As I use LVM backend, all the changes I needed are limited to [lvm.py](https://github.com/QubesOS/qubes-core-admin/blob/067b493aa9b83c24ebcb4ea2b4f44631aef78c0f/qubes/storage/lvm.py).

First, I had to remove backend restriction to downsize volumes:
```
+++ lvm.py  2022-04-30 21:00:51.311000681 +0200
@@ -607,12 +607,12 @@
             msg = 'Can not resize reađonly volume {!s}'.format(self)
             raise qubes.storage.StoragePoolException(msg)
 
-        if size < self.size:
-            raise qubes.storage.StoragePoolException(
-                'For your own safety, shrinking of %s is'
-                ' disabled (%d < %d). If you really know what you'
-                ' are doing, use `lvresize` on %s manually.' %
-                (self.name, size, self.size, self.vid))
 
         if size == self.size:
             return
```

Second, we need to allow extend operation to downsize volumes:
```
+++ lvm.py  2022-04-30 21:00:51.311000681 +0200
@@ -766,7 +766,7 @@
                    '--virtualsize=' + cmd[3] + 'B', '--', cmd[1]]
     elif action == 'extend':
         assert len(cmd) == 3, 'wrong number of arguments for extend'
-        lvm_cmd = ["lvextend", "--size=" + cmd[2] + 'B', '--', cmd[1]]
+        lvm_cmd = ["lvresize", "--force", "--size=" + cmd[2] + 'B', '--', cmd[1]]
     elif action == 'activate':
         assert len(cmd) == 2, 'wrong number of arguments for activate'
         lvm_cmd = ['lvchange', '--activate=y', '--', cmd[1]]
```

Keep in mind this will likely enable system-wide LVM volumes downsize. A cleaner approach would be to modify Qubes internal API so that restore operation could indicate that volume downsize shall be allowed. Alternatively, all the downsize checks can be move to appropriate frontends, leaving my added backend downsize capability intact. I definitely prefer second solution as more architecturally correct ne.

**Comment by DemiMarie** [comment]
@a-barinov You, I, and @marmarek all agree that the downsize checks do not belong in qubesd.  Care to send a PR with your changes?

**Comment by a-barinov** [comment]
You'll have it in a few days. Let me verify that other frontends have appropriate downsize checks, and also check other backends.
