### ISSUE TITLE
Qubes Backup shows a sync permission denied error when backing up  to SMB 3.0

### ISSUE THREAD

**Issue by ekaflaer** [QubesOS/qubes-issues#7177]
### Qubes OS release

4.1

### Brief summary

I have a backup vm which has a mount point to a NAS over SMB 3.0.
I am using this VM and its mount point as target for the Qubes Backup.

It works fine but as soon as 100% progress is reached I get an error stating the following:
```
ERROR: Writing backup to VM backup failed: sync: error syncing '/mnt/qubes-backup-2022-01-01T095442': Permission denied
```

Despite the error the file is saved on the NAS storage and when I verify the backup with Qubes Backup Restore it does not show any error.

So it seems that Qubes Backup runs a sync or similar command in the end which seems to have an issue with SMB mount points.

The mount point is mounted with the user and group permissions of the vm user.

### Steps to reproduce

1. Create a VM which automounts an SMB 3 storage during boot with user permissions
2. Run Qubes Backup and select this VM and the SMB mountpoint as target
3. Run the backup

### Expected behavior

Backup succeeds without an error.

### Actual behavior

Shows the following error each time even though the backup seems to be fine:
```
ERROR: Writing backup to VM backup failed: sync: error syncing '/mnt/qubes-backup-2022-01-01T095442': Permission denied
```

**Comment by rustybird** [comment]
> So it seems that Qubes Backup runs a sync or similar command in the end

Yes, `qubes.Backup` [now](https://github.com/QubesOS/qubes-core-agent-linux/pull/340) only considers the backup run a success after explicitly persisting to disk.

> which seems to have an issue with SMB mount points.

>     ERROR: Writing backup to VM backup failed: sync: error syncing '/mnt/qubes-backup-2022-01-01T095442': Permission denied

Do you also see a second error message (complaining about syncing the `/mnt` directory this time) right after the first one?

**Comment by ekaflaer** [comment]
> Do you also see a second error message (complaining about syncing the `/mnt` directory this time) right after the first one?

No, only the error message I have mentioned.

**Comment by rustybird** [comment]
Tbh I'm baffled that the SMB server or client would barf at a boring `fsync()` on a regular file - it's such a common operation... And then as a bonus `fsync()` on a directory works.

One thing you could try is changing [this line](https://github.com/QubesOS/qubes-core-agent-linux/blob/v4.1.31/qubes-rpc/qubes.Backup#L11) in `/etc/qubes-rpc/qubes.Backup` to

      cat > "$TARGET" && sync --file-system -- "$TARGET"

**Comment by DemiMarie** [comment]
What is the SMB server?

**Comment by ekaflaer** [comment]
> What is the SMB server?

I explicitly enforce `vers=3.0` in the mount command and the Samba server runs on a Synology NAS with DSM 7.0: https://kb.synology.com/en-ca/DSM/help/DSM/AdminCenter/file_winmacnfs_win?version=7

Opportunistic Locking is enabled.

**Comment by ekaflaer** [comment]
> One thing you could try is changing [this line](https://github.com/QubesOS/qubes-core-agent-linux/blob/v4.1.31/qubes-rpc/qubes.Backup#L11) in `/etc/qubes-rpc/qubes.Backup` to

I still get the same error after changing the line, only when I remove the sync command completely now error is shown.

Btw. I should have mentioned that I am using a Debian 11 template for the backup vm.

**Comment by rustybird** [comment]
> Opportunistic Locking is enabled.

Hmm not sure what that really does, but I wonder if it's somehow tripping over the sequence of operations here, which is `qubes.Backup` (1) writes out the file, (2) closes it, (3) opens it again, (4) fsyncs it, and (5) finally closes it for good. Maybe the error would go away if 2 and 3 are avoided?

Can you please try to replace the line in `/etc/qubes-rpc/qubes.Backup` again but this time with:

      dd bs=128K iflag=fullblock conv=fsync of="$TARGET" && sync -- "$args"

**Comment by ekaflaer** [comment]
> Can you please try to replace the line in `/etc/qubes-rpc/qubes.Backup` again but this time with:
> 
> ```
>   dd bs=128K iflag=fullblock conv=fsync of="$TARGET" && sync -- "$args"
> ```
This command works fine without showing any errors. The file also is there and verification was successful.

**Comment by rustybird** [comment]
Thanks for testing.

-> https://github.com/QubesOS/qubes-core-agent-linux/pull/353

**Comment by ekaflaer** [comment]
Many thanks for your fix.

Btw. I am mounting the smb mount point in `/rw/config/rc.local`. It seems that Qubes/Debian is not able to shut down the system then without using `qvm-kill`. Most likely because of the mount point - because if I unmount manually before shut down it works fine.

What would be the correct way to umount during shutdown as a counter part to `rc.local` or do I really have to create a template with fstab entries for just one vm?

Thanks in advance.

**Comment by DemiMarie** [comment]
> Many thanks for your fix.
> 
> Btw. I am mounting the smb mount point in `/rw/config/rc.local`. It seems that Qubes/Debian is not able to shut down the system then without using `qvm-kill`. Most likely because of the mount point - because if I unmount manually before shut down it works fine.
> 
> What would be the correct way to umount during shutdown as a counter part to `rc.local` or do I really have to create a template with fstab entries for just one vm?
> 
> Thanks in advance.

This is a question for the mailing list or the forum.
