### ISSUE TITLE
Window resize problems (in particular in LibreOffice)

### ISSUE THREAD

**Issue by marmarta** [QubesOS/qubes-issues#7179]
### Qubes OS release
r4.1, template: fedora 35

Qubes was updated from 4.0 to 4.1 in-place some months ago.

### Brief summary
When running LibreOffice (and some other apps, like xterm) from a VM based on Fedora 35, I consistently run into an issue where the LibreOffice window stops displaying/refreshing; the underlying app works (e.g. it reacts to keyboard shortcuts, tries to show windows etc.), but the window contents do not refresh, regardless of what I do (resizing, minimizing, doing things within the window).
### Steps to reproduce
Open LibreOffice, maximize the window, or just resize the window to a large size, or work for a longer time on a big document with complex formatting.
### Expected behavior
Display working.

### Actual behavior
LibreOffice window contents partially freeze and do not get updated with user actions; even things like opening menus result in a blank or glitched menu.
![libreoffice problem](https://user-images.githubusercontent.com/7242298/148273906-bb72b2f8-8dca-456a-a104-540396dbe4a7.png)

There is nothing interesting in dom0 logs, but there are some interesting things in X log inside the VM:
![libreoffice2](https://user-images.githubusercontent.com/7242298/148274911-3b8e7e43-a3da-44f3-a1c1-9993992ac379.png)

(a silly way to show it, but I can't manage to copy from the terminal because menu in xterm refuses to show itself, apparently due to the same problem).

Xen-commandline lacks the following parameter: `gnttab_max_frames=2048`

**Comment by marmarta** [comment]
Setting this param solved this issue, so this is a problem with the 4.0->4.1 upgrade mechanism.

**Comment by marmarek** [comment]
Related to #5685

**Comment by petaramesh** [comment]
I met the same issue when upgrading from 4.0 to 4.1RC4, bad to the point that I immediately reverted back to 4.0 as I badly need the machine to be usable on a daily basis.

I now have upgraded from 4.0 again to 4.1 final version, and I'm happy to report that for me the issue is now gone.
