### ISSUE TITLE
Arch build fails due to systemd-nspawn error

### ISSUE THREAD

**Issue by sajkbflksadbfkasdjf** [QubesOS/qubes-issues#7180]
### Qubes OS release
4.1rc3
### Brief summary
`make qubes-vm` fails due to error with systemd-nspawn
### Steps to reproduce
build archlinux on fedora34
### Expected behavior
functions as expected
### Actual behavior
error due to missing command `systemd-nspawn`

**Comment by lubellier** [comment]
> make qubes-vm fails due to error with systemd-nspawn

@sajkbflksadbfkasdjf , please could you give the error message or an explanation of the error. Thanks.

**Comment by sajkbflksadbfkasdjf** [comment]
> give the error message or an explanation of the error. Thanks.

Well, systemd-nspawn is not available on the system. The fix is simple, just install systemd-container, which adds the nspawn-command. Tested with fedora-34 template, systemd-container is not installed by default. Thus I've added systemd-container, the package providing the nspawn-command, to the list of dependencies.

**Comment by lubellier** [comment]
Today, I tested the ArchLinux builder, I confirm the issue and the solution ( [PR#197](https://github.com/QubesOS/qubes-builder/pull/197)).
Now I'm waiting the PR merge.
