### ISSUE TITLE
PiKVM mouse doesn’t work with input proxy 

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#7182]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

R4.1

### Brief summary
The PiKVM mouse does not work with the Qubes input proxy.  Specifically, click events are not sent.

### Steps to reproduce

Use PiKVM to control a Qubes system using the input proxy.

### Expected behavior
Button clicks work.

### Actual behavior
Button clicks do not work.

**Comment by brendanhoar** [comment]
I am very curious about how qubes project/ITL is utilizing PiKVM (after I saw @marmarek's PRs related to PiKVM recently). And if this is related to the USB-connected secure keyboarding initiative.

Brendan

**Comment by marmarek** [comment]
> I am very curious about how qubes project/ITL is utilizing PiKVM

https://github.com/QubesOS/qubes-posts/pull/91

**Comment by marmarek** [comment]
I believe the description is reversed - only clicks work, but not movement. And this issue is fixed already in https://github.com/QubesOS/qubes-app-linux-input-proxy/pull/29 (and later extended in https://github.com/QubesOS/qubes-app-linux-input-proxy/pull/34).
