### ISSUE TITLE
tar fails to extract root.img from template.rpm

### ISSUE THREAD

**Issue by sajkbflksadbfkasdjf** [QubesOS/qubes-issues#7183]
### Qubes OS release
4.1 with all updates applied (subscribed to testing)
### Brief summary
Qubes fails to install templates because the root.img extraction fails
### Steps to reproduce
Install template (I installed from commandline with `dnf install ./qubes-template-...`
### Expected behavior
Template is installed correctly
### Actual behavior
```archlinux: Importing data
tar: root.img: Cannot seek to 212860928: Broken pipe
tar: Exiting with failure status due to previous errors
Traceback (most recent call last):
  File "/bin/qvm-template-postprocess", line 5, in <module>
    sys.exit(main())
  File "/usr/lib/python3.8/site-packages/qubesadmin/tools/qvm_template_postprocess.py", line 431, in main
    loop.run_until_complete(post_install(args))
  File "/usr/lib64/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/lib/python3.8/site-packages/qubesadmin/tools/qvm_template_postprocess.py", line 297, in post_install
    import_root_img(vm, args.dir)
  File "/usr/lib/python3.8/site-packages/qubesadmin/tools/qvm_template_postprocess.py", line 109, in import_root_img
    raise qubesadmin.exc.QubesException('root.img extraction failed')
qubesadmin.exc.QubesException: root.img extraction failed
warning: %post(qubes-template-archlinux-4.0.6-202201062107.noarch) scriptlet failed, exit status 1

Error in POSTIN scriptlet in rpm package qubes-template-archlinux
  Running scriptlet: qubes-template-archlinux-4.0.6-202201062107.noarch                   2/2 
  Cleanup          : qubes-template-archlinux-4.0.6-202201062107.noarch                   2/2 
  Verifying        : qubes-template-archlinux-4.0.6-202201062107.noarch                   1/2 
  Verifying        : qubes-template-archlinux-4.0.6-202201062107.noarch                   2/2 ```
This has been tested with self-built arch template and the gentoo template I downloaded manually and moved to dom0 to install. Can't confirm it happens with "normal" installs from qvm-template too.

**Comment by marmarek** [comment]
Definitely try with `qvm-template`. But also, check if you have enough disk space - you need few GB (the size of the template, uncompressed) in dom0 root filesystem.

**Comment by sajkbflksadbfkasdjf** [comment]
`qvm-template` doesn't accept local rpms (some signature check failed), pulling from the repo isn't possible right now due to https://github.com/QubesOS/qubes-issues/issues/7170

**Comment by marmarek** [comment]
> `qvm-template` doesn't accept local rpms

It does, try `qvm-template install --nogpgcheck`

**Comment by sajkbflksadbfkasdjf** [comment]
root.img extraction fails too, the exception `qubesadmin.exc.QubesException: root.img extraction failed` appears in the python traceback. After that the `qvm-template` returns exit status 1 and quits.

**Comment by sajkbflksadbfkasdjf** [comment]
traceback for dnf:
```archlinux: Importing data
tar: root.img: Cannot seek to 212860928: Broken pipe
tar: Exiting with failure status due to previous errors
Traceback (most recent call last):
  File "/bin/qvm-template-postprocess", line 5, in <module>
    sys.exit(main())
  File "/usr/lib/python3.8/site-packages/qubesadmin/tools/qvm_template_postprocess.py", line 431, in main
    loop.run_until_complete(post_install(args))
  File "/usr/lib64/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/lib/python3.8/site-packages/qubesadmin/tools/qvm_template_postprocess.py", line 297, in post_install
    import_root_img(vm, args.dir)
  File "/usr/lib/python3.8/site-packages/qubesadmin/tools/qvm_template_postprocess.py", line 109, in import_root_img
    raise qubesadmin.exc.QubesException('root.img extraction failed')
qubesadmin.exc.QubesException: root.img extraction failed
warning: %post(qubes-template-archlinux-4.0.6-202201062107.noarch) scriptlet failed, exit status 1

Error in POSTIN scriptlet in rpm package qubes-template-archlinux
  Running scriptlet: qubes-template-archlinux-4.0.6-202201062107.noarch                   2/2 
  Cleanup          : qubes-template-archlinux-4.0.6-202201062107.noarch                   2/2 
  Verifying        : qubes-template-archlinux-4.0.6-202201062107.noarch                   1/2 
  Verifying        : qubes-template-archlinux-4.0.6-202201062107.noarch                   2/2 
```
and traceback for `qvm-template`: 
```Traceback (most recent call last):
  File "/usr/bin/qvm-template-postprocess", line 5, in <module>
    sys.exit(main())
  File "/usr/lib/python3.8/site-packages/qubesadmin/tools/qvm_template_postprocess.py", line 431, in main
    loop.run_until_complete(post_install(args))
  File "/usr/lib64/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/lib/python3.8/site-packages/qubesadmin/tools/qvm_template_postprocess.py", line 297, in post_install
    import_root_img(vm, args.dir)
  File "/usr/lib/python3.8/site-packages/qubesadmin/tools/qvm_template_postprocess.py", line 109, in import_root_img
    raise qubesadmin.exc.QubesException('root.img extraction failed')
qubesadmin.exc.QubesException: root.img extraction failed
ERROR: Command '['qvm-template-postprocess', '--really', '--no-installed-by-rpm', 'post-install', 'gentoo', '/var/tmp/tmpwbvffcui/var/lib/qubes/vm-templates/gentoo']' returned non-zero exit status 1.
```

**Comment by marmarek** [comment]
Are you sure the template rpm isn't simply truncated? Try `rpm -Kv` on it.

**Comment by marmarek** [comment]
Or not rpm file itself, but the root.img file inside - see `rpm -qpvl` on it, and compare file sizes with what you'd expect (root.img may be in several parts there, you need to sum them).

**Comment by sajkbflksadbfkasdjf** [comment]
The sum of the (8) parts is ~8GB big. The first command returns a few signature OK statements. 
I can append the results if you want but sadly I'm not yet knowledgeable enough about rpms to interpret the output

**Comment by fepitre** [comment]
> traceback for dnf:
> 
> ```
> tar: root.img: Cannot seek to 212860928: Broken pipe
> tar: Exiting with failure status due to previous errors
> Traceback (most recent call last):
>   File "/bin/qvm-template-postprocess", line 5, in <module>
>     sys.exit(main())
>   File "/usr/lib/python3.8/site-packages/qubesadmin/tools/qvm_template_postprocess.py", line 431, in main
>     loop.run_until_complete(post_install(args))
>   File "/usr/lib64/python3.8/asyncio/base_events.py", line 616, in run_until_complete
>     return future.result()
>   File "/usr/lib/python3.8/site-packages/qubesadmin/tools/qvm_template_postprocess.py", line 297, in post_install
>     import_root_img(vm, args.dir)
>   File "/usr/lib/python3.8/site-packages/qubesadmin/tools/qvm_template_postprocess.py", line 109, in import_root_img
>     raise qubesadmin.exc.QubesException('root.img extraction failed')
> qubesadmin.exc.QubesException: root.img extraction failed
> warning: %post(qubes-template-archlinux-4.0.6-202201062107.noarch) scriptlet failed, exit status 1
> 
> Error in POSTIN scriptlet in rpm package qubes-template-archlinux
>   Running scriptlet: qubes-template-archlinux-4.0.6-202201062107.noarch                   2/2 
>   Cleanup          : qubes-template-archlinux-4.0.6-202201062107.noarch                   2/2 
>   Verifying        : qubes-template-archlinux-4.0.6-202201062107.noarch                   1/2 
>   Verifying        : qubes-template-archlinux-4.0.6-202201062107.noarch                   2/2 
> ```
> 
> and traceback for `qvm-template`:
> 
> ```
>   File "/usr/bin/qvm-template-postprocess", line 5, in <module>
>     sys.exit(main())
>   File "/usr/lib/python3.8/site-packages/qubesadmin/tools/qvm_template_postprocess.py", line 431, in main
>     loop.run_until_complete(post_install(args))
>   File "/usr/lib64/python3.8/asyncio/base_events.py", line 616, in run_until_complete
>     return future.result()
>   File "/usr/lib/python3.8/site-packages/qubesadmin/tools/qvm_template_postprocess.py", line 297, in post_install
>     import_root_img(vm, args.dir)
>   File "/usr/lib/python3.8/site-packages/qubesadmin/tools/qvm_template_postprocess.py", line 109, in import_root_img
>     raise qubesadmin.exc.QubesException('root.img extraction failed')
> qubesadmin.exc.QubesException: root.img extraction failed
> ERROR: Command '['qvm-template-postprocess', '--really', '--no-installed-by-rpm', 'post-install', 'gentoo', '/var/tmp/tmpwbvffcui/var/lib/qubes/vm-templates/gentoo']' returned non-zero exit status 1.
> ```

I don't understand. I see that you try to install archlinux template where as there is post-install for gentoo. Can you please check that you have enough place inside dom0 like at least 7 or 8 GB.

**Comment by sajkbflksadbfkasdjf** [comment]
Why archlinux? I did try that too, but that might have been a failure in my build setup so I downloaded gentoo from the repos, manually transferred to dom0 and tried to install. `df -h` gives me ~9GB of free space, so I don't think the problem's about disk space

**Comment by sajkbflksadbfkasdjf** [comment]
With https://github.com/QubesOS/qubes-issues/issues/7170 fixed I tried to use qvm-template to download the gentoo template. This works fine, but the issue with the root.img persists.

**Comment by sajkbflksadbfkasdjf** [comment]
(the download works fine, the install fails as usual)

**Comment by sajkbflksadbfkasdjf** [comment]
any updates on the source of this issue? otherwise I might try a reinstall sometime soon, to ascertain whether it's a software problem...

**Comment by DemiMarie** [comment]
Can you successfully install other templates, such as Fedora 35?

**Comment by sajkbflksadbfkasdjf** [comment]
Nope, issue confirmed with fedora-33

**Comment by sajkbflksadbfkasdjf** [comment]
any updates? I'd be happy to test stuff if it helps w/ troubleshooting

**Comment by unman** [comment]
Are you OP?

Are there *any* templates that work for you?
If you download a template rpm and install it manually, does that work
for you?
If so, remove the template and try installing it again with
qvm-template.
Obviously use one of the templates that didn't work - I would use
Fedora-33, since we know that package has had extensive testing.

**Comment by sajkbflksadbfkasdjf** [comment]
> Are you OP? Are there *any* templates that work for you? If you download a template rpm and install it manually, does that work for you? If so, remove the template and try installing it again with qvm-template. Obviously use one of the templates that didn't work - I would use Fedora-33, since we know that package has had extensive testing.

I tried manual install, actually the arch template is self-built. I tried removing a template I didn't need any longer and reinstalling it, but that failed as well.

**Comment by sajkbflksadbfkasdjf** [comment]
> 
> What is the output of:
> 
> ```
> sudo lvs|grep -v vm-
> ```
> 
> ?
> 
> B



  LV                                             VG         Attr       LSize   Pool      Origin                                         Data%  Meta%  Move Log Cpy%Sync Convert
  root                                           qubes_dom0 Vwi-aotz--  20.00g root-pool                                                62.48                                  
  root-pool                                      qubes_dom0 twi-aotz--  24.00g                                                          52.07  35.43                           
  swap                                           qubes_dom0 -wi-ao----  <3.95g

**Comment by sajkbflksadbfkasdjf** [comment]
well, I think with 4.1 out I'll probably try a reinstall, does anyone need any more infos before that?

**Comment by BEBF738VD** [comment]
I'm having the same issue. I've tried with multiple templates (fedora, debian, whonix) and they all end with the same exception error: `qubesadmin.exc.QubesException: root.img extraction failed`

I have tried on 4.1 (as downloaded on the official website) as well as 4.1 kernel-latest provided by fepitre.

`df -h /`: Size 20G, Used 8.7G, Avail 9.9G
`rpm -Kv` shows that digests are OK.

The output of `rpm -qpvl` is included below. marmarek mentioned that `root.img` may be divided into parts; in my case the size of `root.img` is 0 while `root.img.part.00` is 984524800. I'm not sure if the former is supposed to be completely empty.

```
drwxrws---    2 root     qubes                       0 Aug 19  2021 /var/lib/qubes/vm-templates/debian-11-minimal
drwxrwxr-x    2 root     qubes                       0 Aug 19  2021 /var/lib/qubes/vm-templates/debian-11-minimal/apps
drwxrwxr-x    2 root     qubes                       0 Aug 19  2021 /var/lib/qubes/vm-templates/debian-11-minimal/apps.tempicons
drwxrwxr-x    2 root     qubes                       0 Aug 19  2021 /var/lib/qubes/vm-templates/debian-11-minimal/apps.templates
-rw-rw----    1 root     qubes                       0 Aug 19  2021 /var/lib/qubes/vm-templates/debian-11-minimal/clean-volatile.img.tar
-rw-rw-r--    1 root     qubes                      21 Aug 19  2021 /var/lib/qubes/vm-templates/debian-11-minimal/netvm-whitelisted-appmenus.list
-rw-rw----    1 root     qubes                       0 Aug 19  2021 /var/lib/qubes/vm-templates/debian-11-minimal/private.img
-rw-rw----    1 root     qubes                       0 Aug 19  2021 /var/lib/qubes/vm-templates/debian-11-minimal/root.img
-rw-rw----    1 root     qubes               984524800 Aug 19  2021 /var/lib/qubes/vm-templates/debian-11-minimal/root.img.part.00
-rw-rw-r--    1 root     qubes                       0 Aug 19  2021 /var/lib/qubes/vm-templates/debian-11-minimal/template.conf
-rw-rw-r--    1 root     qubes                      21 Aug 19  2021 /var/lib/qubes/vm-templates/debian-11-minimal/vm-whitelisted-appmenus.list
-rw-rw----    1 root     qubes                       0 Aug 19  2021 /var/lib/qubes/vm-templates/debian-11-minimal/volatile.img
-rw-rw-r--    1 root     qubes                      21 Aug 19  2021 /var/lib/qubes/vm-templates/debian-11-minimal/whitelisted-appmenus.list
```

I attempted to seek help on the forums with not much luck...
https://forum.qubes-os.org/t/cannot-install-templates-qvm-template-postprocess-error-root-img-extraction-failed-even-after-complete-qubesos-reinstall/11361/1

@sajkbflksadbfkasdjf sorry for tagging you, but have you found a solution?

**Comment by sajkbflksadbfkasdjf** [comment]
nope, sadly I had to reinstall and even now the issue persists. That's the reason I can't install fedora-35 on my machine...

**Comment by sajkbflksadbfkasdjf** [comment]
btw, issue confirmed for fully updated 4.1

**Comment by DemiMarie** [comment]
I suspect the problem is insufficient disk space in dom0.  Can you provide the output of `df` in dom0?

**Comment by sajkbflksadbfkasdjf** [comment]
sure, here you go:
devtmpfs                     1.9G     0  1.9G   0% /dev
tmpfs                        2.0G     0  2.0G   0% /dev/shm
tmpfs                        2.0G  2.4M  2.0G   1% /run
/dev/mapper/qubes_dom0-root   20G   11G  8.0G  58% /
tmpfs                        2.0G  4.0K  2.0G   1% /tmp
xenstore                     2.0G  392K  2.0G   1% /var/lib/xenstored
/dev/nvme0n1p4               974M  153M  755M  17% /boot
/dev/nvme0n1p1              1022M   72M  951M   7% /boot/efi
tmpfs                        391M   28K  391M   1% /run/user/1000

**Comment by DemiMarie** [comment]
I suspect you are running out of space in dom0.  Try extending the dom0 root volume.

**Comment by brendanhoar** [comment]
I use:

watch -d df -h

Which reruns df every second.

B

**Comment by sajkbflksadbfkasdjf** [comment]
I did pretty much the same, there were at least a few GB left at any moment of the install. After the line `fedora 35: Importing data` it threw the exception and quitted.

**Comment by sajkbflksadbfkasdjf** [comment]
Well, I've heard enough of it and will attempt an in-place upgrade according to the fedora docs. [1] Hopefully the issue will be fixed eventually. :-) Still, thanks for the support.

[1] https://docs.fedoraproject.org/en-US/quick-docs/dnf-system-upgrade/

**Comment by BEBF738VD** [comment]
Just an update to confirm that this issue still persists. I recently tried installing several templates with `qvm-template` as well as unman 's bookworm-minimal, but they all failed with the same error mentioned here.

> I suspect the problem is insufficient disk space in dom0. Can you provide the output of `df` in dom0?

@DemiMarie the template is less than 1G and my `/dev/mapper/qubes_dom0-root` has 20G available. I ran `df -h` at .2 second intervals and it never came close to filling up the space.

I also ran `journalctl` through the entire process and no erros were thrown.

Any suggestion is greatly appreciated...

**Comment by BEBF738VD** [comment]
New case reported on the forums: https://forum.qubes-os.org/t/cant-recover-any-backup-and-and-cant-install-templates/14668

They reported 77G of free disk space in dom0

**Comment by DemiMarie** [comment]
@BEBF738VD This is definitely bad, but I am not sure how to debug this problem without either being able to reproduce the problem, or having shell access to a machine that has the problem.

**Comment by BEBF738VD** [comment]
Does the available space in the various `tmpfs`, and in `xenstore` matter? Or is it only `/dev/mapper/qubes_dom0-root` I have to look at?

**Comment by DemiMarie** [comment]
> @DemiMarie thank you very much for taking interest in this issue. I would be happy to run on my machine any test that you suggest, at your convenience.

My first thought is to run `strace` on the `tar` command and see where it fails.  This will produce a lot of output, so use `-o` to save it to a file somewhere.

> Does the available space in the various `tmpfs`, and in `xenstore` matter? Or is it only `/dev/mapper/qubes_dom0-root` I have to look at?

Only the last one.

**Comment by sajkbflksadbfkasdjf** [comment]
I have run strace on the whole command (qvm-template install gentoo-minimal), hope this helps

**Comment by BEBF738VD** [comment]
I have found a solution!
When setting up Qubes, I removed vim. As it turns out, it is somehow necessary to the template script: 

reinstalling `vim` fixed it for me.

I'm now able to install any template I wish.
Hope this helps.

**Comment by sajkbflksadbfkasdjf** [comment]
Weird. I have uninstalled vim but hard-linked neovim to vim...

**Comment by marmarek** [comment]
I guess this is related:
```
$ rpm -qf /usr/bin/xxd
vim-common-8.2.2787-1.fc32.x86_64
```

**Comment by sajkbflksadbfkasdjf** [comment]
Seems correct, vim-common solves the problem

**Comment by BEBF738VD** [comment]
Fantastic. Cheers everyone for pitching in.
