### ISSUE TITLE
Forbid creating a qube called “Domain-0”

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#7187]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### The problem you're addressing (if any)

If I create a qube called `Domain-0`, starting it fails with a libxl error.

### The solution you'd like

Disallow creating a qube called `Domain-0`.  While having a disposable template be unstartable can be useful, an error from libxl isn’t the best way to enforce that. :laughing:

### The value to a user, and who that user might be

Not sure?  This is definitely `P: minor`.

**Comment by alimirjamali** [comment]
@DemiMarie do the above two commits solve this issue already? Could the issue be closed?
