### ISSUE TITLE
Sign Arch Linux package databases

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#7190]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### The problem you're addressing (if any)
Arch Linux package databases are not signed.  This is inconsistent with Qubes OS’s standard policy of signing all metadata.

### The solution you'd like
Arch Linux package databases should be signed.

### The value to a user, and who that user might be
All Arch Linux users will benefit from improved security.

**Comment by unman** [comment]
It seems to me that the databases *are* signed, but with a key that isnt (easily) available - that's a separate issue.

As it is, the official repositories dont seem to be configured in a new template, and the key isnt present.
(cf #6610)

**Comment by DemiMarie** [comment]
> It seems to me that the databases _are_ signed, but with a key that isnt (easily) available - that's a separate issue.

The packages are signed.  The databases are not.

**Comment by marmarek** [comment]
> The packages are signed. The databases are not.

https://archlinux.qubes-os.org/r4.1/current/vm/archlinux/pkgs/qubes-r4.1-current.db.sig

**Comment by DemiMarie** [comment]
> > The packages are signed. The databases are not.
> 
> https://archlinux.qubes-os.org/r4.1/current/vm/archlinux/pkgs/qubes-r4.1-current.db.sig

Ooops!  Turns out that Pacman does not fetch the signature if XferCommand is in use.  That’s a bug in Pacman, not Qubes, though.  Closing.

**Comment by andrewdavidwong** [comment]
(Minor side note: Since this wasn't a bug report, the "not our bug" resolution doesn't apply.)
