### ISSUE TITLE
PATH env variable in Fedora appVM

### ISSUE THREAD

**Issue by onetuser** [QubesOS/qubes-issues#7193]
### Qubes OS release
R4.0
Fedora 33, 33-minimal, 34

### Brief summary
1. `echo $PATH` in new terminal prints double modifications from `.bashrc`
2. changing `PATH` in `.bashrc` and running `echo $PATH` prints both old and new modifications from `.bashrc` (until appVM reboot)

Other variables from `.bashrc` are not modified twice. Also this issue is not reproduced in 'Debian 11' app VM.

### Steps to reproduce
1. create new app VM from Fedora template
2. modify `.bashrc`
In the beginning add:
   ```
   echo 'BEGIN .bashrc'
   echo $PATH
   echo $TEST_VAR
   ```
   In the end add:
   ```
   PATH=$PATH:~/test_dir
   TEST_VAR=TEST_VAR_VAL

   echo 'END .bashrc'
   echo $PATH
   echo $TEST_VAR
   ```
3. ***Reboot appVM***

### Expected behavior
Opening new terminal prints
>BEGIN .bashrc
>/home/user/.local/bin:/home/user/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin
>
>END .bashrc
>/home/user/.local/bin:/home/user/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:**/home/user/test_dir**
>TEST_VAR_VAL

Changing PATH modification  in .bashrc  to `PATH=$PATH:~/test_dir2` and opening new terminal prints
>BEGIN .bashrc
>/home/user/.local/bin:/home/user/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin
>
>END .bashrc
>/home/user/.local/bin:/home/user/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:**/home/user/test_dir2**
>TEST_VAR_VAL

### Actual behavior
Opening new terminal prints
>BEGIN .bashrc
>/home/user/.local/bin:/home/user/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:**/home/user/test_dir**
>
>END .bashrc
>/home/user/.local/bin:/home/user/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:**/home/user/test_dir:/home/user/test_dir**
>TEST_VAR_VAL

Changing PATH modification  in .bashrc to `PATH=$PATH:~/test_dir2` and opening new terminal prints
>BEGIN .bashrc
>/home/user/.local/bin:/home/user/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:**/home/user/test_dir**
>
>END .bashrc
>/home/user/.local/bin:/home/user/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:**/home/user/test_dir:/home/user/test_dir2**
>TEST_VAR_VAL

So any application is searched in `~/test_dir` first, not in `~/test_dir2`, even though there is no `~/test_dir` in `.bashrc` anymore.

**Comment by DemiMarie** [comment]
This is interesting.  On the one hand, one could argue that sourcing `~/.bashrc` is supposed to be idempotent: doing it twice should have the same effect.  That said, the difference in behavior is worth investigating.

**Comment by onetuser** [comment]
Sourcing may be not idempotent but still **new** terminal window should not contain old .bashrc PATH variable values. Looks like new terminal is run with this formed env variable, i do not know why. 

Adding `pstree -s -p $PPID >> from.txt` to  .bashrc prints to file:
>systemd(1)---qubes-gui(417)---qubes-gui-runus(473)---sh(615)---pstree(638)

on VM startup for Fedora. 
While no this record for Debian.
Next, running terminal adds 
>systemd(1)---systemd(587)---gnome-terminal-(1111)-+-bash(1128)---pstree(1130)
>                                                  |-{gnome-terminal-}(1112)
>                                                  ....

So only systemd(1) is common, i do not get why old PATH is passed in the second case.

Because of this issue 'node version manager' (nvm) does not apply changed default node version in new terminal (nmv modifies PATH from .bashrc only if there is no one already set in PATH, so only initial (old) node version directory is set in PATH in new terminals until VM reboot)

Running `sudo` with `-H` (`sudo -Hu user /bin/bash`) works as expected though (PATH is not passed, so formed PATH contains no old .bashrc values)
