### ISSUE TITLE
DispVM: Update qubesmanager to display DispVMs

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#72]
**Reported by joanna on 28 Sep 2010 08:13 UTC**
Currently the manager will not display DispVMs, because it only reads the qubes DB on file accesses to qubes.xml. Perhaps the easiest solution would be to touch this file whenever we create/destroy a new DispVM?

Migrated-From: https://wiki.qubes-os.org/ticket/72

**Comment by andrewdavidwong** [comment]
@marmarek, is this the correct issue for this bug report? (I'm hesitant to reopen it because it's so old...)

https://groups.google.com/d/msgid/qubes-users/fe95d6c1-7044-4a08-abb0-176a22a7faa9%40googlegroups.com :
> If a dispvm gets started qubes-manager inserts a line in qubes.xml. If 
> qubes-manager crashes or gets killed (which sometimes is necessary) it 
> somehow fails to keep track of the dispvms. A dispvm can now be shutdown 
> without it beeing removed from qubes.xml. (Manually deleting the 
> corresponding line helps.)

**Comment by marmarek** [comment]
I don't think so, see reply to that mail.
