### ISSUE TITLE
qrexec-daemon segfault while windows-core-agent communications

### ISSUE THREAD

**Issue by jevank** [QubesOS/qubes-issues#7201]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
R4.1 current-testing

### Brief summary
Intensive testing qrexec communication with Windows core agent leads to qrexec-daemon segfault failure
```log
dom0 kernel: qrexec-daemon[14024]: segfault at 60ffc6122958 ip 000060fbc611db14 sp 00007ffe2ddca0b0 error 6 in qrexec-daemon[60fbc611c000+4000]
dom0 kernel: Code: 00 89 85 c4 fe ff ff 48 8d 1d 68 56 00 00 8d 90 ff fd ff ff 89 b5 40 ff ff ff 44 89 e7 48 8b b5 d8 fc ff ff 89 85 44 ff ff ff <44> 89 24 93 ba 08 00 00 00 c7 85 2c fd ff ff 08 00 00 00 e8 84 eb
..
dom0 systemd-coredump[14790]: Process 14024 (qrexec-daemon) of user 1000 dumped core.
                                              
                                              Stack trace of thread 14024:
                                              #0  0x000060fbc611db14 main (qrexec-daemon + 0x3b14)
                                              #1  0x000071e880ecf082 __libc_start_main (libc.so.6 + 0x27082)
                                              #2  0x000060fbc611dfde _start (qrexec-daemon + 0x3fde)
```

### Steps to reproduce

```
[user@dom0 ~]$ for i in $(seq 100); do echo SEAMLESS | qvm-run -p --service win-dvm qubes.SetGuiMode; sleep 1; echo FULLSCREEN | qvm-run -p --service win-dvm qubes.SetGuiMode; done
2022-01-14 11:39:25.450 qrexec-client[14787]: ioall.c:75:read_all: EOF
2022-01-14 11:39:25.450 qrexec-client[14787]: qrexec-client.c:318:negotiate_connection_params: read daemon: Success
2022-01-14 11:39:25.532 qrexec-client[14799]: qrexec-client.c:184:connect_unix_socket: connect: Connection refused
2022-01-14 11:39:26.617 qrexec-client[14805]: qrexec-client.c:184:connect_unix_socket: connect: Connection refused
...
```

**Comment by marmarek** [comment]
Do you have the coredump file still (`coredumpctl` will tell you)? Can you send it to me privately (it may contain some data you exchange with this VM, not only as part of the current connections)?

**Comment by jevank** [comment]
> Do you have the coredump file still (`coredumpctl` will tell you)? Can you send it to me privately (it may contain some data you exchange with this VM, not only as part of the current connections)?

sent via email

**Comment by marmarek** [comment]
Got it. The issue is with handling too-many-connections case. Linked PR should fix it.

**Comment by jevank** [comment]
Confirm no crashes with the fix, but still got broken communications... 
```
2022-01-14 16:26:27.984 qrexec-client[24753]: ioall.c:75:read_all: EOF
2022-01-14 16:26:27.985 qrexec-client[24753]: qrexec-client.c:318:negotiate_connection_params: read daemon: Success
2022-01-14 16:26:29.084 qrexec-client[24759]: ioall.c:75:read_all: EOF
2022-01-14 16:26:29.084 qrexec-client[24759]: qrexec-client.c:318:negotiate_connection_params: read daemon: Success
2022-01-14 16:26:29.181 qrexec-client[24764]: ioall.c:75:read_all: EOF
2022-01-14 16:26:29.181 qrexec-client[24764]: qrexec-client.c:318:negotiate_connection_params: read daemon: Success
```

**Comment by marmarek** [comment]
There is a limit of concurrent connection to a single VM (the generic one is 256, but I think for windows it's even lower, about 20?). Looks like it is exceeded here.

**Comment by marmarek** [comment]
Uhm, in fact, it seems the Windows qrexec implementation never sends `MSG_CONNECTION_TERMINATION`, so qrexec-daemon thinks all the connections are still established. So, the above limit for Windows is in fact "this many connection for the VM uptime"...

**Comment by jevank** [comment]
Doesn't connection should be closed after request or w/ timeout?..

**Comment by jevank** [comment]
> Uhm, in fact, it seems the Windows qrexec implementation never sends `MSG_CONNECTION_TERMINATION`, so qrexec-daemon thinks all the connections are still established. So, the above limit for Windows is in fact "this many connection for the VM uptime"...

Ok

**Comment by marmarek** [comment]
I'm looking where it should be added.
Looking at https://github.com/QubesOS/qubes-core-agent-windows/blob/master/src/qrexec-agent/qrexec-agent.c, I think `StartChild()` currently just starts the process for a connection and forgets about it. Instead, `HandleExec()` (which uses `StartChild()`) it should also monitor when the process terminates, and send `MSG_CONNECTION_TERMINATION` to the qrexec-daemon. This probably means the handle returned by `CreateNormalProcessAsCurrentUser` should _not_ be closed, but instead monitored for process exit (in the main loop - `WatchForEvents` function?).

**Comment by jevank** [comment]
> I think StartChild() currently just starts the process for a connection and forgets about it. Instead, HandleExec() (which uses StartChild()) it should also monitor when the process terminates, and send MSG_CONNECTION_TERMINATION to the qrexec-daemon.

Yes, it seems so. We will try to make it similar to the linux version.
