### ISSUE TITLE
include LUKS2 in installer image

### ISSUE THREAD

**Issue by mylostone** [QubesOS/qubes-issues#7205]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### The problem you're addressing (if any)
 * Using the qubes installer iso -> rescue qubes system -> shell
 * cryptsetup luksOpen /dev/x y -> ERROR: LUKS2 not supported

### The solution you'd like

 In the rescue shell, I would like to be able top open a LUKS2 volume.

### The value to a user, and who that user might be

  Mucking about in one's previously encrypted volume, for any given user.

**Comment by marmarek** [comment]
It is there already, in R4.1, which uses LUKS2 by default.
