### ISSUE TITLE
q4.1 rc3 sys-net fails to reset PCI device

### ISSUE THREAD

**Issue by WithUnity** [QubesOS/qubes-issues#7207]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
Qubes 4.1 RC3 

### Brief summary
sys-net will not start. Message:
Qube sys-net has failed to start: internal error: unable to reset PCI device 0000:00:1f.6:n o flr. PM reset or bus reset available

### Steps to reproduce
Immediately after install: Login
click on sys-net files or any other app in sys-net

### Expected behavior
sys-net should start and the apllication should run.

### Actual behavior
aya-net fails to start reporing the above error.
Qube sys-net has failed to start: internal error: unable to reset PCI device 0000:00:1f.6:n o flr. PM reset or bus reset available

**Comment by WithUnity** [comment]
Found fix documented on line.

**Comment by legoktm** [comment]
@WithUnity could you share what you found? I ran into the same issue after a fresh install of 4.1rc4, found <https://www.qubes-os.org/doc/pci-troubleshooting/>, and removed my ethernet device from sys-net and was able to start it.

However, I just did a fresh install so there's no reason it should have been assigned to two qubes or already in use elsewhere, if I understand how this is supposed to work correctly.
