### ISSUE TITLE
Ctrl-O exits qvm-console-dispvm

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#7209]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

R4.1

### Brief summary

Typing Ctrl-O causes qvm-console-dispvm to exit

### Steps to reproduce

Type Ctrl-O in a console window opened by qvm-console-dispvm

### Expected behavior

Ctrl-O is sent to the qube

### Actual behavior

The console window is closed.

**Comment by marmarek** [comment]
[qubes.ShowInTerminal](https://github.com/QubesOS/qubes-core-agent-linux/blob/master/qubes-rpc/qubes.ShowInTerminal) has `socat ...,escape=0x0f`, which happens to be Ctrl-O. @fepitre do you remember what was the intention? This is rather unfortunate shortcut for exiting...

**Comment by unman** [comment]
Ctrl+D is the default value in the kernel for eof for the terminal - it
was used with `xl console`. Would this not work with socat?

**Comment by marmarek** [comment]
No `xl console` uses Ctrl+]. Ctrl+D would be bad, you couldn't use it in shell (like, exit _just_ subshell for example).

**Comment by DemiMarie** [comment]
In this case I don’t think any escape character should be used, as users can just close the console window.

**Comment by unman** [comment]
Of course, you're right.
