### ISSUE TITLE
Visual icon impariments in the alternative XFCE4 env

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#721]
**Reported by marmarek on 27 Feb 2013 01:27 UTC**
This includes normal menus and VM context menu. The same actions in toolbar have icons.
Also VM settings window lack frames around sections.
And lastly, "restart required" (aka "outdated") icon is cut in half (only this icon in all possible status icons).

This may be some theme setting thing...

Migrated-From: https://wiki.qubes-os.org/ticket/721

**Comment by andrewdavidwong** [comment]
Should this issue's priority be increased since we've moved to Xfce4 by default? (Or is it actually deprecated now?)

**Comment by woju** [comment]
This issue is abandoned, so I'm going to close it. If that's a mistake, feel free to reopen.
@marmarek @andrewdavidwong
