### ISSUE TITLE
`qubes-app-shutdown-idle` is missing on Fedora 35

### ISSUE THREAD

**Issue by SaswatPadhi** [QubesOS/qubes-issues#7212]
### Qubes OS release

R4.1

### Brief summary

`qubes-app-shutdown-idle`, which was earlier available on Fedora template VMs, is missing on the new Fedora 35 templates.

### Steps to reproduce

Run `dnf install qubes-app-shutdown-idle` in the template VM.

### Expected behavior

`qubes-app-shutdown-idle` is downloaded and installed.

### Actual behavior

`qubes-app-shutdown-idle` is not found in the software repositories!

**Comment by marmarek** [comment]
It is in current-testing repo there, but indeed it's time for it to move to current.

**Comment by SaswatPadhi** [comment]
Ah yes! I should have looked into the current-testing repo as well.

Thanks for the super quick response, @marmarek! Please feel free to close this report or leave it open until the package has been moved to `current`.

**Comment by marmarek** [comment]
done
