### ISSUE TITLE
Settings checkbox option ("Disposable template") isn't grayed out where it should be

### ISSUE THREAD

**Issue by Ark-of-the-copepod** [QubesOS/qubes-issues#7217]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

4.1 rc3

### Brief summary

A checkbox is not grayed out where it should be in Settings panel. Error message could be improved.

### Steps to reproduce

("Q Menu" = "Q")

0. believe that a disposable needs a "template" of some kind  (very late, dazzled and confused by newness of 4.1, genetically prone to stupid mistakes)

1. create template , i.e. Q > Create Qubes VM > Type:Template, Name "TEST".

2. check "Launch settings after creation" (or by Qubes Manager >) Settings > Advanced > Other > check "Disposable template" 
This is a 'live' option, but shouldn't be.

"Error: Advanced Tab: Invalid Property 'template_for_dispvms' TEST"

### Expected behavior

If its not an option, it should be grayed out.
If an error message is thrown, it should be informative for non-expert users. 

If checkbox cannot be solved, consider new text "This is a Template VM. Only AppVMs can be used as a template for disposables." Could also be very useful as a mouseover text.

**Comment by alimirjamali** [comment]
PR submitted

Both disabling `Disposable template`  check-box for anything but AppVMs as well as adding the text: `Only AppVMs could be turned in to Disposable Templates` to tool-tip is implemented.
