### ISSUE TITLE
Silent transition from disp-vm providing service to persistent AppM

### ISSUE THREAD

**Issue by Ark-of-the-copepod** [QubesOS/qubes-issues#7219]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

4.1
Maybe 4.0 also?

### Brief summary
[edit for clarity and detail]
 
4.1 regularly uses named disposables for network services. This encourages users to experiment with their own disposable setups, such as for VPN-vms. 

For non-named disp-vms, VPN services can be supplied by a non-named disposable, (e.g. 'dispXXXX-vm'). Both are volatile and disappear at shutdown.

[edit for clarity] However, the user can assign the 'dispXXXX-vm' to a regular AppVM to be its network provider (i.e. VPN connection). This can be done with GUI tools like Qubes Manager, Settings or new dropdown menu options. (I am pretty sure I also used the terminal for this at least once in the last few days). 

From the moment of assignment to an AppVM, dispXXXX-vm stops being a disposable. This transition happens silently and produces a persistent vm that looks very like a disp-vm.

(I have not tested reassigning a dispXXXX-vm to another non-service disp-vm).

- The vms are listed in Qubes Manager after restart, still named "dispXXXX'. 
- There is no difference in icon between a disposable service vm and a now-persistent service vm (you have to recognize the numbers and perhaps the non-running state).
- These vms are not in the dropdown Q menu. 

I am unaware if other types of disp-vms (esp. those providing service) are also prone to this.

This is inviting privacy and security breaches by user error. A user could accidentally use a misconfigured service, or expose unintentionally retained personal data, etc.

### Steps to reproduce

~~1. Launch a non-named disp-vm providing service (e.g. network)~~
~~2. Assign to a persistent AppVM~~

[More detail requested, @unman ]
1. Have an already-running AppVM (e.g. `Personal`) connected to `Named-disp-VPN-vm`
2. Use (or make) another `VPN-vm, (e.g. `xVPN-vm`) to make a template-for-disposable.
3. Launch `disp1234 from xVPN-vm`. 
4. Assign `disp1234`  to  `Personal`  as its network provider. 
5. `disp1234` is now a permanent entry in Qubes Manager as an AppVM, but there is little indication of this.

### Expected behavior

I suggest that disposables should be disposables, and only disposables should _look_ like disposables. It seems very weird that a qube can make a significant transition like this without a declaration from the system. The user rightly expects warnings for other system events (e.g. closing a qube with dependents).

1. when transitioning a qube from disposable to persistent, a pop-up warning should display, e.g.
"This action will convert this disposable qube to a persistent AppVM, which will provide [service] to [other AppVM]. Do you wish to continue?"
2. the name should change (as well as the icon). I understand that means cloning, but that should be doable.
"Please enter the new name for the persistent qube"
3. the vm should be listed in the Q menu.

### Actual behavior

Silent transition.

**Comment by unman** [comment]
"However, for example during troubleshooting or experimentation, the
'dispXXXX-vm' can be assigned to a regular AppVM."
What does this mean?
Is this something YOU do, or does it happen without user action?
If it is something YOU do, can you outline the steps to achieve this?

**Comment by Ark-of-the-copepod** [comment]
Apologies. Please see corrections above.

**Comment by DemiMarie** [comment]
Does dispXXXX-vm’s private volume persist across restarts?  The actual definition of a DispVM is that it does not.

**Comment by Ark-of-the-copepod** [comment]
Ok, so I just tested that. No, the private volume does not persist.

So what is happening is that dispXXXX-vm becomes a template for a _named_ disposable?

I still think that is un-intuitive, unexpected behavior that needs to be fixed. You can't tell by looking at them in Q. Manager.

But I have also just discovered several other dispXXXX-vms in Qubes manager that are still there after being closed. _These_ ones have a disposable icon. I am pretty certain at least one has survived a restart of the system (because its assigned a disp1674 as netVM, something I did days ago while being reminded of Kronebourg 1664(?) beer). 

They can be launched, worked in, then disappear.

```
[x@dom0 Desktop]$ qvm-run disp7542 xterm
Running 'xterm' on disp7542
disp7542: command failed with code: 255
[x@dom0 Desktop]$ qvm-run disp7542 xterm
usage: qvm-run [--verbose] [--quiet] [--help] [--user USER] [--autostart] [--no-autostart] [--pass-io] [--localcmd COMMAND] [--gui]
               [--no-gui] [--colour-output COLOUR] [--colour-stderr COLOUR] [--no-colour-output] [--no-colour-stderr]
               [--filter-escape-chars] [--no-filter-escape-chars] [--service] [--no-shell] [--dispvm [BASE_APPVM]] [--all]
               [--exclude EXCLUDE]
               [VMNAME] COMMAND [ARG [ARG ...]]
qvm-run: error: no such domain: 'disp7542'
```
Why are these ghost-disps hanging around?

**Comment by Ark-of-the-copepod** [comment]
A shot of the qubes I'm talking about in Q Manager. 

(Don't judge, this is an experimental install for me to play around with 4.1. Even at my level).

![QubeManager-crop](https://user-images.githubusercontent.com/83213325/150621352-832f9f0d-7980-49c8-94b3-84125dd2a281.png)

None of these dispXXXXs had any entry in the "Is DVM Template" field.
Disp1674 was from 2 days ago, several system restarts. Disp86 is the same day.
Disp8085 is fine - I personally created and took it offline for picture editing today.

**Comment by marmarek** [comment]
The temporary disposable qubes (the one named `dispXXX`) are just a DisposableVM qube that have `auto_cleanup` property set to true. This means, in addition to normal disposable properties (not preserving private volume or other state), they are automatically removed when shut down. What is happening here, is that removal fails, because the qube is used by something (set as a netvm for `personal`).

I see two solution for this issue:
1. Prevent using dispXXX as netvm
2. Forcefully unset it before removal

I think the first option is better, any other opinions?

**Comment by DemiMarie** [comment]
I suggest doing both.  I would like qubesd to automatically purge all such qubes at startup if it doesn’t already, and it ensures that existing invalid states get fixed.

**Comment by andrewdavidwong** [comment]
Definitely the first one, in which case the second should never come into play, but if it somehow did, doing both also sounds fine.

**Comment by unman** [comment]
The first is better, and would make the second redundant.
