### ISSUE TITLE
Bad DVM app menus when debian is selected as dvm template on install

### ISSUE THREAD

**Issue by ydirson** [QubesOS/qubes-issues#7222]
### Qubes OS release

4.1-rc3

### Brief summary

During fresh install, I selected only debian-11 for template installation, and a debian-11-dvm was created accordingly.  But the selected app menus do not match with the template: no app appears in the DVM menu, and the Qubes Manager shows just 2 "Application missing in template" entries (firefox.desktop and xterm.desktop)

**Comment by unman** [comment]
Duplicate (if updated ) of #6805

**Comment by andrewdavidwong** [comment]
This appears to be a [duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If anyone believes this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.
