### ISSUE TITLE
Installer should not warn if setup will install a non-fedora updatevm

### ISSUE THREAD

**Issue by ydirson** [QubesOS/qubes-issues#7225]
### Qubes OS release

4.1-rc3

### Brief summary

After installing Qubes with only Debian template, I'm unable to install some dom0 packages (in my case `dummy-psu` for a `sys-gui-gpu` setup).  This is [a known problem](https://github.com/QubesOS/qubes-issues/issues/5233) and the user should be at least warned the he's running into trouble.

**Comment by andrewdavidwong** [comment]
Perhaps the best solution is to require the creation of a Fedora-based update qube (unless the user opts for the expert installation in which none is created at all) until #5233 is fixed.
