### ISSUE TITLE
sys-gui-gpu.sls still references dummy-psu-dom0

### ISSUE THREAD

**Issue by ydirson** [QubesOS/qubes-issues#7230]
### Qubes OS release

4.1-rc4

### Brief summary

This should probably be replaced by `dummy-psu-sender`, but maybe there are other implications beyond this ?

**Comment by VasoVV** [comment]
Fresh installation of 4.1 with updates still contains _dummy-psu-dom0_ in `/srv/formulas/base/virtual-machines-formula/qvm/default/sys-gui-gpu.sls`

**Comment by Geblaat** [comment]
> This should probably be replaced by `dummy-psu-sender`, but maybe there are other implications beyond this ?
I tried setting up sys-gui-gpu on a fresh install. It failed because it cannot install the package dummy-psu-dom0.

**Comment by VasoVV** [comment]
Because it was replaced by `dummy-psu-sender`

**Comment by Geblaat** [comment]
> Because it was replaced by `dummy-psu-sender`

Yes, I understood that. I'm trying to say that one implication of it still referencing dummy-psu-dom0 is that the setup of sys-gui-gpu as documented on the Qubes website is now broken.(Unless of course the user manually replaces it but that is not documented on the main site.)

**Comment by andrewdavidwong** [comment]
> Yes, I understood that. I'm trying to say that one implication of it still referencing dummy-psu-dom0 is that the setup of sys-gui-gpu as documented on the Qubes website is now broken.(Unless of course the user manually replaces it but that is not documented on the main site.)


In case you (or any others reading this) are not already aware, the documentation is a community effort, and everyone is welcome to contribute. (That's how things like this get updated!) So, if you'd like to get involved with the project, this is a great way to do it. You can read more about how to submit documentation changes here:

https://www.qubes-os.org/doc/how-to-edit-the-documentation/

You may also be interested in the documentation style guide:

https://www.qubes-os.org/doc/documentation-style-guide/

**Comment by Geblaat** [comment]
> 

Yes, I read that recently. But I was thinking it would make more sense to just fix this(which seems like a quick, easy fix to me) than to edit the documentation and than later having to edit it back when it is fixed.
