### ISSUE TITLE
`qubes-gpg-client` hangs forever if the qrexec call is refused

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#7233]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
R4.1

### Brief summary
If the qrexec call is refused, `qubes-gpg-client` hangs forever.

### Steps to reproduce

`QUBES_GPG_DOMAIN=. qubes-gpg-client`

### Expected behavior

`qubes-gpg-client` exits promptly with a non-zero exit code.

### Actual behavior

`qubes-gpg-client` hangs.

**Comment by andrewdavidwong** [comment]
@DemiMarie, you reported this against 4.1 but assigned it to the "Release 4.0 updates" milestone. Was that a mistake?
