### ISSUE TITLE
Misleading error message if VM name starts with a character in `_0123456789-`

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#7234]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
R4.1

### Brief summary
`qvm-create _` fails with “VM name contains illegal characters”, which is misleading since `_` is perfectly valid in a qube name.

### Steps to reproduce

`qvm-create _`

### Expected behavior

Better error message, such as “VM names cannot start with an underscore”

### Actual behavior

Misleading error message

**Comment by alimirjamali** [comment]
The [current regex logic](https://github.com/QubesOS/qubes-core-admin/blob/main/qubes/vm/__init__.py#L57) for VM Name validation demands alphabet for the 1st character. Thus you can not choose `_*, -h, --help` as VM names.

It has to be decided if the current logic is fine or has to be changed to allow underscore as 1st character. Then the code could be fixed or the issue could be closed accordingly.
