### ISSUE TITLE
Simplify Qubes Windows Tools Installation for R4.1

### ISSUE THREAD

**Issue by GWeck** [QubesOS/qubes-issues#7240]
### The problem you're addressing (if any)
Qubes R4.1 is a huge step forward! So it is advisable to upgrade as soon as possible. For users having Windows VMs, however, this is currently rather difficult, because these VMs require a lot of manual steps in order to get Qubes Windows Tools upgraded to the new version. QWT 4.0.1.3 tends not to run under Qubes R4.1, and the solutions provided by @elliotkillick and [tabit-pro/qubes-windows-tools-cross](https://github.com/tabit-pro/qubes-windows-tools-cross) require technical steps which may be too complicated for non-technical users, thus causing them to stay with Qubes R4.0.

In order to help these users, a simple method to install Qubes Windows Tools under R4.1 is needed.

### The solution you'd like
The generation of QWT according to [tabit-pro/qubes-windows-tools-cross](https://github.com/tabit-pro/qubes-windows-tools-cross) generates a version which is already quite complete (currently version 4.1.66) and can be installed without too much effort, once it is generated. If would be helpful, if the resulting `.rpm` file for installation in `dom0` would be provided, possibly as a community supplied component. Alternatively, the `.iso` file created by the installation kit oder the `.msi`file contained in this iso could be made available for manual transport to a Windows VM, where it could be used to install QWT.

### The value to a user, and who that user might be
This solution would make the transition of Windows qubes to R4.1 much smoother and would probably help a lot of people to upgrade. Additionally, it could make Qubes R4.1 more attractive for current Windows users - there are still some of them around! - to move to a decent, reasonably secure system.

In an earlier [post](https://forum.qubes-os.org/t/windows-support-in-qubes/4288/3), @marmarek pointed out that creating a new QWT version will need a lot of work. Much of this has been achieved in the mean time. So, with the help of the cross-build project, there is now a version that could be provided to the users. (I am running this version since several months without greater problems.) Still, there are some enhancements conceivable, like a new graphics driver supporting more screen resolutions for Windows 7 and seamless mode for Windows 10/11, but these are details that could be implemented later.

One problem there could be that such a QWT build first may not be authenticated as a Qubes component, without much prior testing. From a security point of view, this would not be a big risk: As I found out to my distress, Windows installation media are not authenticated, either.  The Windows media creation tool just produces an installation `.iso` file, and Microsoft does not provide a signature, digest or hash value for this file. You just get it and have to hope that it was not modified on transit. For this reason, any Windows qubes have to be considered as untrustworthy. Installing QWT in such a qube wil not make it more trustworthy, but it cannot make it less. But running Windows under Qubes would still be much more secure than running it natively, especially as Qubes does not trust any of these VMs.

**Comment by jevank** [comment]
>  If would be helpful, if the resulting .rpm file for installation in dom0 would be provided, possibly as a community supplied component.

I try to approach this option :)

**Comment by DemiMarie** [comment]
> Microsoft does not provide a signature, digest or hash value for this file. You just get it and have to hope that it was not modified on transit.

Yikes!  That is *really* unfortunate.

**Comment by DemiMarie** [comment]
> Last time I checked (has been a while) unlike the ISOs generated my the media creation tool the ISOs downloaded from microsoft.com (like https://www.microsoft.com/en-us/software-download/windows10ISO, visit with a browser that claims to **not** run on Windows) at least don't change everytime. So you can at least compare hashes between users.

And also check that the TLS certificate was signed by a Microsoft root CA.

**Comment by HW42** [comment]
Not really, you can only expect that it's signed by a root CA accepted by most browsers. Currently they are using some DigiCert CAs (different for www.microsoft.com and software-download.microsoft.com, might also depends on from where you connect).

What's nice is that they are now listing hashes. IIRC this wasn't always the case. So now you don't need to download many GBs just to verify that you see the same.

**Comment by GWeck** [comment]
Maybe the situation is better in a professional environment using the WSUS service, but I cannot confirm this. What's unclear, too, is whether the created ISOs  may be different depending on serveral paramters (e.g language, country, license type etc.). This could be easily fixed by distributing some sort of digest, like it is done for Qubes. But Microsft customers seem to be content with the situation, so why should that be improved?

**Comment by taradiddles** [comment]
@jevank 
> > If would be helpful, if the resulting .rpm file for installation in dom0 would be provided, possibly as a community supplied component.
> 
> I try to approach this option :)

Would it be OK to temporarily publish a user-built QWT iso somewhere (eg. in a personal github repo) and put a link to it in the [forum wiki](https://forum.qubes-os.org/t/wip-windows-qwt-user-reports/9687), or do you prefer to wait until QWT becomes a contrib/official Qubes package ?
A binary package would help people who aren't really into building stuff or are encountering [problems](https://forum.qubes-os.org/t/wip-windows-qwt-user-reports/9687/17?u=taradiddles) ; the flip side is that it could become a burden (likely for you) when people using older builds report issues that are fixed in the master branch. (not mentioning security - installing a random user-built QWT package is obviously bad, but so is Windows anyway).

**Comment by jevank** [comment]
> Would it be OK to temporarily publish a user-built QWT iso somewhere 

I've made github release with binaries and control sums.
https://github.com/tabit-pro/qubes-windows-tools-cross/releases/tag/v4.1.67

**Comment by taradiddles** [comment]
> I've made github release with binaries and control sums.

Cool !

[re-reading my post above I realize it may have sounded like I was asking you to publish QWT, I hope it's not the case: to save you time I was thinking about building QWT myself and uploading it on github until QWT would be available officially; so many thanks for taking the time to do that yourself!]

**Comment by DemiMarie** [comment]
> Maybe the situation is better in a professional environment using the WSUS service, but I cannot confirm this. What's unclear, too, is whether the created ISOs may be different depending on serveral paramters (e.g language, country, license type etc.). This could be easily fixed by distributing some sort of digest, like it is done for Qubes. But Microsft customers seem to be content with the situation, so why should that be improved?

I suspect enterprises tend to use the Windows Media Creation Tool instead, and presumably *that* tool is signed by Microsoft.

**Comment by GWeck** [comment]
I am afraid, Microsoft still does not know how to do something right and secure: The Windows Media Creation Tool just selects and downloads the ISO file, without providing any checksum or digital signature, and, as far as I tried, I could not find any such information from Microsoft.

If the tool is signed or checks during download, that does not help at all, because the user needs to perform the check on the user's PC, on the downloaded file, which may have been altered during the download, and for this, the user needs the signature or checksum. Checking on the sender's, i.e. Microsoft's, side tells nothing about the integrity of the file at the user's side.

It's just as sloppy as we are used from this vendor. They should probably read how to do it correctly, as is well described for some other system ([Verifying the Qubes ISO](https://www.qubes-os.org/security/verifying-signatures/))... :-)

**Comment by GWeck** [comment]
@jevank I checked the `rpm` with Windows 7 and the `msi` with Windows 10 and 11. Works like a charm! Great!

**Comment by DemiMarie** [comment]
> If the tool is signed or checks during download, that does not help at all, because the user needs to perform the check on the user's PC, on the downloaded file, which may have been altered during the download, and for this, the user needs the signature or checksum. Checking on the sender's, i.e. Microsoft's, side tells nothing about the integrity of the file at the user's side.

It would be sufficient for the Windows Media Creation Tool to check the signature during the download process.  I have no idea if it actually does do so, however.  Would be an interesting reverse engineering challenge.

**Comment by GWeck** [comment]
For that, it would have to compute the signature on the downloaded file, and that would require to upload this file again - which defintely does not happen with my extremely slow upload speed. Just checking the signature on the outgoing data stream is not sufficient, as this stream may be altered after leaving the sending server.

Apart from that, I would even think that Microsoft could be able to use such an extremly complicated and useless feature - they do it often enough.

**Comment by DemiMarie** [comment]
> For that, it would have to compute the signature on the downloaded file, and that would require to upload this file again - which defintely does not happen with my extremely slow upload speed. Just checking the signature on the outgoing data stream is not sufficient, as this stream may be altered after leaving the sending server.

They could verify the signature locally.

**Comment by GWeck** [comment]
But how? For this, they would need to perform the verification on **my** computer, with software they downloaded on this machine! That would raise some interesting questions:

- Why should I trust verification software that was downloaded from the same source as the installation kit? Both the kit as well as the verification software may be manipulated.
- In the case of local verification, I cannot check the signature independently, because I don't have the signature key, do not know the verification method (signature / checksum) and the algorithms used. Why should I trust that? They might just say o.k., irrspective of the result of the verification.

Anyhow, the tool just gives me the `iso` without telling me anything about its correctness. so I suppose that they don't do any verification at all.

**Comment by DemiMarie** [comment]
> But how? For this, they would need to perform the verification on **my** computer, with software they downloaded on this machine! That would raise some interesting questions:
> 
> * Why should I trust verification software that was downloaded from the same source as the installation kit? Both the kit as well as the verification software may be manipulated.

Presumably the Windows Media Creation Tool is signed by a Microsoft code signing certificate, and you check that signature before running it.

> * In the case of local verification, I cannot check the signature independently, because I don't have the signature key, do not know the verification method (signature / checksum) and the algorithms used. Why should I trust that? They might just say o.k., irrspective of the result of the verification.

This applies to any proprietary update mechanism, such as Windows Update.

> Anyhow, the tool just gives me the `iso` without telling me anything about its correctness. so I suppose that they don't do any verification at all.

It could just return an error if the verification failed.

(Note: I am _not_ stating that the WMCT actually verifies the downloaded image.  I am merely stating that it _could_.)

**Comment by GWeck** [comment]
The tool is signed by a Microsoft certificate - but that is expired since more than a year! Somewhat sloppy again ...

For verifying the `iso` the tool would need the checksum or signature. Could be done, but there is no indication that it is, until the tool would complain that the `iso` is wrong. Never seen such a message. So, as you said, it _could_ be.

Thank you for the interesting discussion! Anyhow, it is somewhat academic, since: Why should we trust closed source software at all?

**Comment by taradiddles** [comment]
Interesting discussion indeed - which again shows how MS is bad at pretty nearly everything.
You could try to replace a byte in the iso and see if WMCT returns an error ? IIRC Windows won't allow changing a file while it's in use (/ being downloaded) but there's probably a way to do that with "lower level" command line tools.

**Comment by GWeck** [comment]
I found out that, when you directly, without WMCT, download a Windows installation iso from [Windows 10-Datenträgerabbild (ISO-Datei) herunterladen](https://www.microsoft.com/de-de/software-download/windows10iso). But this only works if you go from a non-Windows system, e.g. Linux, to the download website - otherwise, you are led to the standard WMCT website. On this alternative website, you can manually select a Windows edition and language, and then you are offered an option to verify the download, leading you to a table containing SHA256 checksums for the different downloadable iso files.

That's pretty complicated and still quite useless: Showing the SHA256 checksums on the download website, without any signature or digest gives you no guarantee that not the iso and its checksum are both manipulated. It would not be too difficult to build a manipulated website providing manipulated iso files and displaying checksums that would fit these files. As usual with security, they just provide snake oil.

**Comment by GWeck** [comment]
Thanks to the work of @jevank et al., QWT version 4.1.68.1 is now available in the current-testing repo and can be installed like described for earlier versions of Qubes, working as expected (and even better).

Thus the aim of this issue has been completely reached, allowing users without too much technical knowledge to create Windows VMs for Windows 7, 10, and 11! Congratulations!!!

So now I am closing this issue.

**Comment by DemiMarie** [comment]
> That's pretty complicated and still quite useless: Showing the SHA256 checksums on the download website, without any signature or digest gives you no guarantee that not the iso and its checksum are both manipulated. It would not be too difficult to build a manipulated website providing manipulated iso files and displaying checksums that would fit these files. As usual with security, they just provide snake oil.

I think you are supposed to use the Windows Media Creation Tool, which might well have these checksums hard-coded.  That tool is almost certainly signed by Microsoft.

**Comment by GWeck** [comment]
> signed by Microsoft.

but, as I wrote above, the signature has to be checked by unsigned software (the explorer). So, for me, the value of this signature is nil.

**Comment by GWeck** [comment]
The WCMT is signed, but this signature is from 29-SEP-2021. So it has to be older than the downloaded iso and cannot contain its signature or checksum.
