### ISSUE TITLE
[openQA] run Qubes automated tests from Qubes installed on USB

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#7243]
### The problem you're addressing (if any)

When Qubes is installed on USB, there are a few differences. For example, USBVM cannot be used. There are a few issues which are unique to USB installed Qubes.

### The solution you'd like

Qubes openQA should run also run on a Qubes installation which is installed on a USB harddrive (USB SSD).

### The value to a user, and who that user might be

Developers experiencing Qubes USB installed issues firsthand.

**Comment by adrelanos** [comment]
Seems like already implemented?

**Comment by adrelanos** [comment]
Is this the same as a real installation on a real USB disk? `firstboot-qubes-usbvm-unavailable` is useful but only part of it. Issues I am experiencing are from installation on real USB disk vs internal disk.

**Comment by marmarek** [comment]
Yes, this is the same as installing to a USB disk, and running Qubes from a USB disk. This is using QEMU-emulated hardware, so may not catch hardware-specific issues (with specific drivers, devices etc), but there is no such thing as testing _all_ existing hardware configurations...
