### ISSUE TITLE
Qubes Initial Setup impossible to debug

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#7244]
### Qubes OS release

R4.1+

### Brief summary

What is the Qubes Initial Setup? See this:
https://www.qubes-os.org/attachment/doc/initial-setup-menu.png
https://www.qubes-os.org/attachment/doc/initial-setup-menu-configuration.png

During Qubes Initial Setup there is no console output or virtual terminal (tty2; alt + tab + F2) available which makes it impossible to debug.

### Steps to reproduce

1. Install Qubes
2. Have some issue during Qubes Initial Setup (such as issues from installing Qubes on USB, graphic card crash or Qubes salt bug)

### Expected behavior

Qubes initial setup runs as a normal window after the first boot after Qubes has been installed after the first login. Then that window could be closed if issues are expected (such as if it didn't successfully complete at first installation attempt) and started from command line to get some console output that can be reported on qubes-issues.

### Actual behavior

Qubes initial setup is a "special" window. It's not a "normal" window. (Normal windows are those started after Xfce login such as browser etc. with a usual window decoration minimize, maximum, close.)

During Qubes initial setup phase, no virtual terminals are available.

----

This is "special":
https://www.qubes-os.org/attachment/doc/initial-setup-menu-configuration.png

This is normal:
https://www.qubes-os.org/attachment/doc/desktop-menu.png

**Comment by adrelanos** [comment]
Any workaround?

Can Qubes Initial Setup be manually started?

Maybe during the "real" Qubes Initial Setup choose "do not configure anything" and then start Qubes Initial Setup manual from a dom0 terminal emulator?

**Comment by marmarek** [comment]
> Can Qubes Initial Setup be manually started?

Yes, `/usr/libexec/initial-setup/initial-setup-graphical`.

> Maybe during the "real" Qubes Initial Setup choose "do not configure anything" and then start Qubes Initial Setup manual from a dom0 terminal emulator?

I think that should do.

> Qubes initial setup runs as a normal window after the first boot after Qubes has been installed after the first login.

There is an issue with this approach: the default user may not be created yet (that's the case for OEM install, where creating user is postponed to initial-setup phase).

> During Qubes Initial Setup there is no console output or virtual terminal (tty2; alt + tab + F2) available which makes it impossible to debug.

I think this should be possible to fix.

**Comment by adrelanos** [comment]
> > Qubes initial setup runs as a normal window after the first boot after Qubes has been installed after the first login.
> 
> There is an issue with this approach: the default user may not be created yet (that's the case for OEM install, where creating user is postponed to initial-setup phase).

Perhaps only create the default user (low risk of that breaking) and postpone everything else (Qubes initial setup) to run as a normal window after the first boot after Qubes has been installed after the first login?

----

Optional... Also to be considered: Set default user name to `user` in case Qubes isn't intending to become a mulit-user operating system anytime soon. Better privacy. Also usability wise. 1 question less to ask. For most users being asked what user name they would use for single user computers seems not useful. Using something other than user name `user` seems not a useful feature for me. By having a default, this might bet simpler, because GUI wouldn't have to ask.

**Comment by brendanhoar** [comment]
> Using something other than user name user seems not a useful feature for me.

FWIW, in dom0 I choose 'admin' instead of 'user' as a tertiary reminder that the current window is dom0 (after window decoration and hostname reminders). 

My recollection is that 'admin' was a Qubes default at some point, but memory might be wrong.

B
