### ISSUE TITLE
qubes global copy/paste rely on activation of clipboard tray

### ISSUE THREAD

**Issue by TNTBOMBOM** [QubesOS/qubes-issues#7247]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

4.1

### Brief summary

Due to the nature of qubes, Taskbar space better to be reserved for necessary applications.

Due to that i usually disable the appearing of clipboard tray/icon, But now in qubes 4.1 when i disable it the functionality of global copy/paste will be disabled as well. 

### Steps to reproduce

Go to qubes settings
Press on Session and Startup
Press on Application Autostart 
Untick Clipboard Tray
Restart Qubes

### Expected behavior

Should has no relation between tray and functionality

### Actual behavior

Doesnt work unless there is an activated tray for clipboard

**Comment by marmarek** [comment]
Nope, the clipboard tray is responsible only for the notification about the copy/paste, the functionality itself is independent.
