### ISSUE TITLE
Misc issues with USB in dom0

### ISSUE THREAD

**Issue by 3hhh** [QubesOS/qubes-issues#7248]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
4.1

### Brief summary
After switching to 4.1 I started testing the [new USBGuard feature](https://github.com/QubesOS/qubes-issues/issues/6959). Unfortunately it doesn't seem to work at all on my system (Lenovo T530). 

I also noticed some further minor issues (at the end).

### Steps to reproduce
Set `GRUB_CMDLINE_LINUX="$GRUB_CMDLINE_LINUX usbcore.authorized_default=0"` in `/etc/default/grub` and regenerate initramfs.

### Expected behavior
USB keyboard is available at luks prompt.

### Actual behavior
USB keyboard is not available, "Device is not authorized for usage".

Journal:
```
Feb 07 17:08:52 dom0 kernel: usb 1-1: Device is not authorized for usage
Feb 07 17:08:52 dom0 kernel: usb 2-1: New USB device found, idVendor=8087, idProduct=0024, bcdDevice= 0.00
Feb 07 17:08:52 dom0 kernel: usb 2-1: New USB device strings: Mfr=0, Product=0, SerialNumber=0
Feb 07 17:08:52 dom0 kernel: usb 2-1: Device is not authorized for usage
Feb 07 17:08:52 dom0 systemd[1]: Found device SAMSUNG_MZ7TD512HAGM-000L1 3.
Feb 07 17:08:52 dom0 kernel: usb 4-3: New USB device found, idVendor=2109, idProduct=0813, bcdDevice=90.15
Feb 07 17:08:52 dom0 kernel: usb 4-3: New USB device strings: Mfr=1, Product=2, SerialNumber=0
Feb 07 17:08:52 dom0 kernel: usb 4-3: Product: USB3.0 Hub
Feb 07 17:08:52 dom0 kernel: usb 4-3: Manufacturer: VIA Labs, Inc.
Feb 07 17:08:52 dom0 kernel: usb 4-3: Device is not authorized for usage
Feb 07 17:08:52 dom0 kernel: kauditd_printk_skb: 8 callbacks suppressed
Feb 07 17:08:52 dom0 kernel: audit: type=1334 audit(1644250132.620:19): prog-id=8 op=LOAD
Feb 07 17:08:52 dom0 audit: BPF prog-id=8 op=LOAD
Feb 07 17:08:52 dom0 audit: BPF prog-id=9 op=LOAD
Feb 07 17:08:52 dom0 audit: BPF prog-id=10 op=LOAD
Feb 07 17:08:52 dom0 kernel: audit: type=1334 audit(1644250132.621:20): prog-id=9 op=LOAD
Feb 07 17:08:52 dom0 kernel: audit: type=1334 audit(1644250132.621:21): prog-id=10 op=LOAD
Feb 07 17:08:52 dom0 audit: BPF prog-id=11 op=LOAD
Feb 07 17:08:52 dom0 audit: BPF prog-id=12 op=LOAD
Feb 07 17:08:52 dom0 kernel: audit: type=1334 audit(1644250132.623:22): prog-id=11 op=LOAD
Feb 07 17:08:52 dom0 kernel: audit: type=1334 audit(1644250132.623:23): prog-id=12 op=LOAD
Feb 07 17:08:52 dom0 systemd[1]: Starting Cryptography Setup for luks-9c2c78a3-e493-4910-ab23-aff71987a25b...
Feb 07 17:08:52 dom0 kernel: usb 3-3: new high-speed USB device number 2 using xhci_hcd
Feb 07 17:08:52 dom0 kernel: fbcon: i915drmfb (fb0) is primary device
Feb 07 17:08:52 dom0 kernel: usb 3-3: New USB device found, idVendor=2109, idProduct=2813, bcdDevice=90.14
Feb 07 17:08:52 dom0 kernel: usb 3-3: New USB device strings: Mfr=1, Product=2, SerialNumber=0
Feb 07 17:08:52 dom0 kernel: usb 3-3: Product: USB2.0 Hub
Feb 07 17:08:52 dom0 kernel: usb 3-3: Manufacturer: VIA Labs, Inc.
Feb 07 17:08:52 dom0 kernel: usb 3-3: Device is not authorized for usage
Feb 07 17:08:52 dom0 kernel: Console: switching to colour frame buffer device 240x67
Feb 07 17:08:52 dom0 kernel: i915 0000:00:02.0: [drm] fb0: i915drmfb frame buffer device

(I gave up here, removed the laptop from the dock and typed in the password from the built-in keyboard.)

Feb 07 17:09:10 dom0 kernel: usb 3-3: USB disconnect, device number 2
Feb 07 17:09:10 dom0 kernel: usb 4-3: USB disconnect, device number 2
Feb 07 17:09:16 dom0 kernel: atkbd serio0: Unknown key pressed (translated set 2, code 0xd9 on isa0060/serio0).
Feb 07 17:09:16 dom0 kernel: atkbd serio0: Use 'setkeycodes e059 <keycode>' to make it known.
Feb 07 17:09:16 dom0 kernel: atkbd serio0: Unknown key released (translated set 2, code 0xd9 on isa0060/serio0).
Feb 07 17:09:16 dom0 kernel: atkbd serio0: Use 'setkeycodes e059 <keycode>' to make it known.
Feb 07 17:09:41 dom0 kernel: usb 3-1: new low-speed USB device number 3 using xhci_hcd
Feb 07 17:09:41 dom0 kernel: usb 3-1: New USB device found, idVendor=046a, idProduct=0023, bcdDevice= 2.20
Feb 07 17:09:41 dom0 kernel: usb 3-1: New USB device strings: Mfr=0, Product=0, SerialNumber=0
Feb 07 17:09:41 dom0 kernel: usb 3-1: Device is not authorized for usage
Feb 07 17:09:51 dom0 kernel: usb 3-1: USB disconnect, device number 3
Feb 07 17:09:58 dom0 systemd-cryptsetup[473]: Set cipher aes, mode xts-plain64, key size 512 bits for device /dev/disk/by-uuid/9c2c78a3-e493-4910-ab23-aff71987a25b.
Feb 07 17:09:58 dom0 systemd-cryptsetup[413]: Set cipher aes, mode xts-plain64, key size 512 bits for device /dev/disk/by-uuid/af715d77-8bb8-4c0d-a320-2825e820fea9.
Feb 07 17:09:58 dom0 systemd-tty-ask-password-agent[426]: Invalid password file /run/systemd/ask-password/ask.FNFTIr
Feb 07 17:09:58 dom0 systemd-tty-ask-password-agent[426]: Failed to process password: Bad message
Feb 07 17:09:59 dom0 systemd[1]: Finished Cryptography Setup for luks-9c2c78a3-e493-4910-ab23-aff71987a25b.
```

I had also seen [these messages](https://github.com/QubesOS/qubes-core-admin-linux/pull/85#issuecomment-1011764245), but IIRC that was much later in the journal.

I also modified initramfs and tried with `usbcore.authorized_default=2`, but that didn't work either.
`usbguard` starts doing its job only much later and not at the luks prompt.

I also tried in combination with `rd.qubes.hide_all_usb`, but that only resulted in a kernel panic once `sys-usb` started up.

### Related

#6959 
https://github.com/QubesOS/qubes-core-admin-linux/pull/85

### Minor other issues

(Sorry for me testing late...)

- `RuleFile=/etc/usbguard/rules.conf` in `qubes-usbguard.conf` should be removed to avoid problems with Fedora default configurations and to avoid any confusion about the order in which rules are applied (`rules.d/` or `rules.conf` first?).
- Logging didn't work at all for me. I believe it's because `AuditBackend=LinuxAudit` and `systemctl status auditd` showed `disabled/dead` on my system. Going back to the default file-based logging fixed it for me (also appeared in journal). I guess one would have to setup logrotate for the usbguard logs then though.
- `usbcore.authorized_default=2` might be interesting for the future.

I could easily send a PR for these minor issues, but I guess the main functionality should be working first.

**Comment by 3hhh** [comment]
Hmmm I'm not 100% sure, but I think there is a race condition inside the USB setup.

It is caused by Fedora setting up usbguard via systemd before cryptsetup in addition to the Qubes setup, see `/etc/systemd/system/basic.target.wants/usbguard.service`.
I noticed that my usbguard was running _before_ the cryptsetup target even though I had none of the kernel options set for it to be enabled by `qubes-pciback`, but only removed all the systemd service conditions to be able to start the service later on.

So usbguard _may_ be running _before_ any of the [qubes-pciback code](https://github.com/QubesOS/qubes-core-admin-linux/blob/master/dracut/modules.d/90qubes-pciback/qubes-pciback.sh) is executed.
I suspect that playing around with low-level kernel interfaces inside `qubes-pciback` that usbguard uses itself may not interact so well with usbguard then.

I also wonder whether it might be worth doing the `qubes-pciback` stuff via systemd as well then and simply add a dependency between the two units.

@DemiMarie Fyi. Feel free to prove me wrong.

**Comment by taradiddles** [comment]
Quick FYI in case someone encounters that issue: don't add a `audit=0` kernel option (I usually do that to remove logging clutter). With that option and with `usbcore.authorized_default=0` it's impossible to type the LUKS password with a USB keyboard; so either usbguard uses the audit subsystem, or the lack of audit triggers a bug (I recall seeing red "failed ... usbguard" lines before the luks prompt but the display gets clear shortly after - eg. 0.5s - so I can't say for sure).

**Comment by brendanhoar** [comment]
> Quick FYI in case someone encounters that issue: don't add a audit=0 kernel option (I usually do that to remove logging clutter). 

Slightly OT, but an amusing and useful journalctl exclusion filtering workaround (using jq) can be found here:

https://github.com/systemd/systemd/issues/2720#issuecomment-634763894

B
