### ISSUE TITLE
Fedora template runs out of space after a few months of using Qubes Updater

### ISSUE THREAD

**Issue by AlxHnr** [QubesOS/qubes-issues#7249]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

Qubes 4.0 (R4.0)

### Brief summary

After a few months of updating, 97% of the templates partition is used up:

```
----------
            ID: update
      Function: pkg.uptodate
        Result: False
       Comment: Problem encountered upgrading packages. Additional info follows:
                
                result:
                    ----------
                    pid:
                        1128
                    retcode:
                        1
                    stderr:
                        Running scope as unit: run-refff185d499c4f6db05c4497c8d832b1.scope
                        Error: Transaction test error:
                          installing package kernel-debug-devel-5.16.5-100.fc34.x86_64 needs 54MB more space on the / filesystem
                        
                        Error Summary
                        -------------
                        Disk Requirements:
                           At least 54MB more space needed on the / filesystem.
```

### Steps to reproduce

1. Setup Fedora 34 template, install some packages via `sudo dnf install` (and some from rpm fusion)
2. Don't do much else with this template after initial setup
3. Update this template using _only_ Qubes Updater, when the tray widget tells you there are new updates
4. Do this for a few months and the template runs out of space

### Expected behavior

When using only high-level GUI tools and almost never fiddling with the template itself, this should never happen.

### Actual behavior

Space runs full and the user has to spend time fixing something that is supposed to just work.

**Comment by marmarek** [comment]
kernel-debug packages are huge, that's most likely why it filled the whole space. Have you installed it intentionally, or maybe something pulled it via a dependency? What happens if you try to remove it - does any needed package is proposed to remove too?

**Comment by AlxHnr** [comment]
The only kernel debug packages on my system are `kernel-debug-devel-5.*`. After uninstalling those, my template is still using up 97% of the default 10240 MiB. I'm not sure which package(s) are causing this.

**Comment by DemiMarie** [comment]
@AlxHnr what happens if you run `fstrim -av` as root in the template, then restart it once or twice?

**Comment by AlxHnr** [comment]
Makes no difference.

**Comment by unman** [comment]
sudo rpm -qa --queryformat '%10{SIZE} - %-20{NAME} \t %{VERSION}\n' | sort -nr | head -20

Will show you largest installed packages.

**Comment by AlxHnr** [comment]
A few weeks ago I did a clean reinstall of Fedora 34. Now its 89% full again. Maybe 10 GiB is way too low to be a reasonable default? I didn't do much other than installing a bunch of software like KDEnlive, Gimp, LLVM and then just used qubes updater for a while.

**Comment by DemiMarie** [comment]
@AlxHnr does `dnf clean all` get you back to a decent state?

**Comment by AlxHnr** [comment]
> @AlxHnr does `dnf clean all` get you back to a decent state?

It helps me to get from 89% down to 86% usage. I guess at this point I just give my template more storage and be done with it.

Why do we use exactly 10 GiB as the limit? VM's only occupy as much storage as they actually use.

**Comment by brendanhoar** [comment]
> It helps me to get from 89% down to 86% usage.

This may be kind of a big hammer, but I regularly run this after dnf clean:

sudo journalctl --vacuum-files=1

Sometime during 4.0 devs addressed some the ever growing logs in some places, so not sure if this is useful today, but I still do it.

B

**Comment by logoerthiner1** [comment]
I always start from fresh template and do things like `sudo dnf -y update && sudo dnf clean all`.

Anyway this is a good hint that we should check out the usage of /var when building a template. `sudo du /var` should be a useful command.

**Comment by AlxHnr** [comment]
@brendanhoar 

`sudo journalctl --vacuum-files=1` only freed ~300 MiB, allowing me to get down to ~83% usage. I guess the main problem here is that a 10 GiB default is nowadays not enough.

**Comment by andrewdavidwong** [comment]
@AlxHnr, is this still a problem on 4.1?

**Comment by AlxHnr** [comment]
I strongly assume so, but haven't tested it. Nowadays when upgrading templates, I just give the new ones more than enough space for ever. They only use up real storage when they get actually filled up.

The raw default Fedora 37 template couldn't even install a few hundred packages without running out of space. So its believable that with time, space may overflow trough ordinary updates.
