### ISSUE TITLE
/etc/qubes-rpc/qubes.TemplateSearch Missing

### ISSUE THREAD

**Issue by TNTBOMBOM** [QubesOS/qubes-issues#7251]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

4.1

### Brief summary

Trying to reinstall or upgrade any template through dom0

### Steps to reproduce

- Open dom0 terminal
- Try to reinstall or upgrade a template e.g:

```
[user@dom0 ~]$ sudo qubes-dom0-update --enablerepo=qubes-templates-community --action=reinstall qubes-template-whonix-gw-16
Redirecting to 'qvm-template reinstall --enablerepo=qubes-templates-community whonix-gw-16'
[Qrexec] /bin/sh: /etc/qubes-rpc/qubes.TemplateSearch: No such file or directory
ERROR: qrexec call 'qubes.TemplateSearch' failed.
```
I used as well this command:

`[user@dom0 ~]$ sudo qvm-template reinstall --enablerepo=qubes-templates-community qubes-template-whonix-gw-16`

Same thing.

**Comment by marmarek** [comment]
What do you have set as updatevm, and what version of `qubes-core-agent-dom0-updates` is inside?

**Comment by TNTBOMBOM** [comment]
> What do you have set as updatevm

fedora-34-minimal

and tools installed inside it to make it compatible with dom0 updates are followed from:

https://www.qubes-os.org/doc/templates/minimal/

> and what version of qubes-core-agent-dom0-updates is inside?

![fedoradom0update](https://user-images.githubusercontent.com/11895339/153017791-610399b0-92d1-4bdc-8acf-0983d9279cb1.png)

is there more tools added to 4.1 related to dom0 and missing in qubes wiki?

**Comment by marmarek** [comment]
Oh, so this one is from 4.0, you need this package updated to the 4.1's version.

`qubes-dist-upgrade --template-standalone-upgrade --only-update fedora-34-minimal` can do that for you, but it isn't exactly trivial to install the tool when you have R4.1 already...

Alternatively, simply change "4.0" to "4.1" in `/etc/yum.repos.d/qubes-r4.repo` (inside the template) and do `dnf distro-sync`.

**Comment by TNTBOMBOM** [comment]
> qubes-dist-upgrade

Command not found

> Alternatively, simply change "4.0" to "4.1" in /etc/yum.repos.d/qubes-r4.repo (inside the template) and do dnf distro-sync.

This made it work.


Though debian/debian based templates just crushed if i change 4.0 to 4.1 and perform upgrade.

If you see it useful, I can open another ticket and post the dpkg error for e.g:

```
dpkg: error processing archive /tmp/apt-dpkg-install-ehhcgV/25-xen-utils-guest_4
.14.3-7+deb11u1_amd64.deb (--unpack):
 trying to overwrite '/lib/systemd/system/xendriverdomain.service', which is als
o in package xen-utils-common 2001:4.8.5-36+u1
Preparing to unpack .../26-qubes-core-agent-thunar_4.1.31-1+deb11u1_amd64.deb ..
.
Unpacking qubes-core-agent-thunar (4.1.31-1+deb11u1) over (4.0.63-1+deb11u1) ...
Errors were encountered while processing:
 /tmp/apt-dpkg-install-ehhcgV/25-xen-utils-guest_4.14.3-7+deb11u1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```
qubes-core-agent-thunar
qubes-core-agent-network 

Same error as above leading to no internet templateVM (useless template, hard to fix) 

Gonna close the ticket as resolved, If you want separate ticket for debian just reply to this ticket.

Thanks for the help.

**Comment by marmarek** [comment]
Here is the script that do the template upgrade: https://github.com/QubesOS/qubes-dist-upgrade/blob/release4.0/scripts/upgrade-template-standalone.sh
You probably need this part:
```
apt-get install --allow-downgrades -y \
            'xen-utils-common=4.14*' \
            'libxenstore3.0=4.14*' \
            'xenstore-utils=4.14*'
```
