### ISSUE TITLE
qubes-dom0-update - `--action=` option

### ISSUE THREAD

**Issue by unman** [QubesOS/qubes-issues#7253]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
4.1

### Brief summary
qubes-dom0-update `--action=list` and `--action=list installed` work in strange ways.

### Steps to reproduce
A. run `sudo qubes-dom0-update --action=list`

B. run `sudo qubes-dom0-update --action=list installed`

### Expected behavior
Use of either option will perform as the same dnf command options.

### Actual behavior
A. UpdateVM is spawned and list of packages is displayed there, followed by "press Enter to Exit."
On Exiting the window, no output is shown in dom0.

B. UpdateVM is spawned, with error - "NO such command" ,followed by "press Enter to Exit".
On Exiting the window, the list of installed packages is shown in dom0.
In this case there is no reason to access the UpdateVM at all.

Both of these behaviours are confusing.
If qubes-dom0-update is intended to be the replacement for dnf in all cases, the output should be consistent with that tool.

**Comment by DemiMarie** [comment]
`--action-list` is not in the man page, so I suspect it is a deprecated alias.

**Comment by unman** [comment]
That's a typo, obviously.
