### ISSUE TITLE
Expanding qubes manager menu bar annoying

### ISSUE THREAD

**Issue by TNTBOMBOM** [QubesOS/qubes-issues#7255]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

4.1

### Brief summary

Dealing with qubes manager menu bar is annoying due to the fact it keeps closing if i dont move in the middle of the available space (check the uploaded image).

### Steps to reproduce

Open qubes manager
Press on << on the left upper side to expand it
Try to go to Global settings

### Expected behavior

Better design which doesnt close automatically unless for example i click in the middle of the expanded menu or any better ideal design but not automatically based on the mouse movement

### Actual behavior

- The X mean the menu will close/minimized because the pointer went out of the borders
- Red arrow mean its a legit and can be called common paths to go to the other side but with current design its not possible
- Green arrow only possible way to do that, Which is blocking hand free movement to go the other side of the menu (One need to move it with focus where the mouse/pointer is moving = annoying). 

![barspace](https://user-images.githubusercontent.com/11895339/153198692-5b3d6d29-5bea-4c46-aa3e-719150ab2346.png)

**Comment by DemiMarie** [comment]
@marmarta @ninavizz

**Comment by Minimalist73** [comment]
Check "Compact View" in the "View" menu and see if it works better for you.

**Comment by TNTBOMBOM** [comment]
yeah great, way much better, but sadly default is bugged with the above 
issue.

Thanks for the workaround.

Minimalist:
> Check "Compact View" in the "View" menu and see if it works better for you.
>

**Comment by alimirjamali** [comment]
> Better design which doesnt close automatically unless for example i click in the middle of the expanded menu or any better ideal design but not automatically based on the mouse movement

I am going to make a PR and purpose a patch for this small issue. In my patch, the Toolbar will not collapse for 1000 mill-seconds if mouse leaves it. I also tested the _"Do not collapse automatically on mouse leave"_ approach. but the former solution is much nicer and more pleasant (in my opinion).

**Comment by alimirjamali** [comment]
> Does that mean this issue also affects 4.2?

Yes
