### ISSUE TITLE
qubes-snapd-helper always show Device /tmp/sanity-sqwashfs-674038359 message

### ISSUE THREAD

**Issue by Nurmagoz** [QubesOS/qubes-issues#7260]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

4.1

### Brief summary

After installing qubes-snapd and snap packages in debian it will show this message. (nothing is not functional, but just annoying notification)

### Steps to reproduce

Following: 

https://www.qubes-os.org/doc/how-to-install-software/#installing-snap-packages

And Enable snaps on Debian and install snapd in:

https://snapcraft.io/install/snapd/debian

Commands: 

```
sudo apt install snap qubes-snapd-helper
sudo snap install core
sudo snap install snapd
```

### Expected behavior

Opening/Closing snapVM (appvm or standalonevm) shouldnt show messages

### Actual behavior

![snaperror](https://user-images.githubusercontent.com/11895339/153422639-49ff0d5e-a19e-4242-b82d-9f10b45efd5e.png)

**Comment by unman** [comment]
Do you mean that there should be existing rules which ignore this, or
that such rules need to be written?

**Comment by unman** [comment]
Thanks

**Comment by marmarek** [comment]
This is about qube having a device published via qvm-block, available to attach to another qube. @DemiMarie diagnosis is correct, that devices used by snapd should should be excluded from such publishing via udev rule.

**Comment by adrelanos** [comment]
Would a udev whitelist instead of a blocklist be possible and a more reliable solution?

**Comment by adrelanos** [comment]
Or perhaps maybe only VMs with setting `provides block device(s)` (or so) should be able to do this? For example VM `untrusted` would have this setting disabled by default. But VM `sys-usb` would have this setting enabled by default. For other VMs such as a custom `remote-webdav` (which would provide a block device) the user would have to opt-in this setting. That is, because most VMs don't provide block devices. Would that be a security enhancement?

**Comment by DemiMarie** [comment]
> Or perhaps maybe only VMs with setting `provides block device(s)` (or so) should be able to do this? For example VM `untrusted` would have this setting disabled by default. But VM `sys-usb` would have this setting enabled by default. For other VMs such as a custom `remote-webdav` (which would provide a block device) the user would have to opt-in this setting. That is, because most VMs don't provide block devices. Would that be a security enhancement?

That is a good idea, mostly because it prevents issues like this.  The actual attack surface of the current code is quite small and no vulnerabilities have ever been found.

> Would a udev whitelist instead of a blocklist be possible and a more reliable solution?

The problem with this is that Qubes OS cannot be aware of all possible block devices.
