### ISSUE TITLE
Can't use 2nd Monitor

### ISSUE THREAD

**Issue by natebartram** [QubesOS/qubes-issues#7263]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

4.1

### Brief summary

I upgraded-in-place, ever since my Qubes device will not recognize when a second display has been plugged into the HDMI output. Previously this worked fine.

### Steps to reproduce

Install (possibly upgrade-in-place) Qubes 4.1. Restart your device. Attempt to plug in a second monitor via HDMI.

### Expected behavior

The display should turn on and be visible/customizable from the Display settings.

### Actual behavior

Nothing. It doesn't even show up in the Display settings to be enabled/configured.

### Additional information

As I said, I upgraded in place from Qubes 4.0 to 4.1. From what I can tell, I have two video devices: Intel HD Graphics 630 and NVidia GeForce GTX 1060. I think the Intel one is the default one being used.

I am more than willing to provide additional logs or data, but I'm not exactly a command-line wizard so you may need to tell me where to find the requested data or what commands to enter.

Also, apologies if this topic has been opened. I didn't see it when I searched, and when I posted on Reddit for tech support I was told it might be a bug.

**Comment by andrewdavidwong** [comment]
Closing this for now as it appears that the issue no longer affects any Qubes users. If anyone believes this is a mistake, or if anyone is still affected by this issue, please leave a comment, and we'll be happy to reopen this. Thank you.

**Comment by octopus-san** [comment]
### Having similar issue on QubesOS R4.2.3

When I've just installed the system (QubesOS 4.2) - HDMI output worked even with GTX 1650 Max-Q despite not like a charm.

After updating using GUI updater and rebooting I'm facing the fact that external display is not even detectable through the XFCE Display settings.

What can I do? Is reinstalling the only way?

Additional info:
* My device is a laptop and it's also has integrated video card.
* Qubes OS Global Config at the "Device Information" section shows me both NVidia and amd GPUs.
