### ISSUE TITLE
Ethernet connection not working in 4.1

### ISSUE THREAD

**Issue by natebartram** [QubesOS/qubes-issues#7264]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

4.1

### Brief summary

I upgraded-in-place, ever since my Qubes device will not recognize ethernet when connected. WiFi works fine.

### Steps to reproduce

Install (possibly upgrade-in-place) Qubes 4.1. Restart your device. Attempt to plug in an ethernet cable.

### Expected behavior

You should get internet access (assuming all else works right.

### Actual behavior

Nothing (if I remember correctly, will attempt again in a few hours when I get home and update if I'm wrong).

### Additional information

As I said, I upgraded in place from Qubes 4.0 to 4.1. I have a Rivet Networks Killer E2500 gigabit ethernet controller.

I am more than willing to provide additional logs or data, but I'm not exactly a command-line wizard so you may need to tell me where to find the requested data or what commands to enter.

Apologies if this issue or one like it has been opened. I didn't see it when I searched.

**Comment by TNTBOMBOM** [comment]
> As I said, I upgraded in place from Qubes 4.0 to 4.1. I have a Rivet Networks Killer E2500 gigabit ethernet controller.

To quick resolve your issue and better security, Backup your appvms and install fresh 4.1, Thats my advise for you. Otherwise you gonna wait in long queue.

**Comment by natebartram** [comment]
> 

I did a fresh install today. Fixed my other issue (https://github.com/QubesOS/qubes-issues/issues/7263) but not this one. Also, honestly, I opened these issues mainly to assist others who are trying to upgrade-in-place.

**Comment by natebartram** [comment]
> Try this: [#7052 (comment)](https://github.com/QubesOS/qubes-issues/issues/7052#issuecomment-1030799336)

This worked. Thanks.
