### ISSUE TITLE
`/etc/qubes/suspend-post.d/qvm-sync-clock.sh` should not run in Qubes-Whonix after suspend-post

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#7265]
https://github.com/QubesOS/qubes-core-agent-linux/blob/master/qubes-rpc/suspend-post.d/qvm-sync-clock.sh shouldn't run in Whonix because Whonix uses sdwdate instead.

qvm-sync-clock.service systemd unit does not run in Whonix as expected due to a systemd configuration file drop-in.

Problem is that /etc/qubes/suspend-post.d/qvm-sync-clock.sh runs independently of the qvm-sync-clock.service systemd unit  configuration. Would it be acceptable for /etc/qubes/suspend-post.d/qvm-sync-clock.sh to run `systemctl --no-pager restart qubes-sync-time.service` instead?

If yes, I'd add a pull request.
If not, I'd add a more cumber some solution, that is config-package-dev hide /etc/qubes/suspend-post.d/qvm-sync-clock.sh.

**Comment by marmarek** [comment]
> Would it be acceptable for /etc/qubes/suspend-post.d/qvm-sync-clock.sh to run `systemctl --no-pager restart qubes-sync-time.service` instead?

Yes, it makes sense to have common entry point for time sync.

**Comment by adrelanos** [comment]
Great! Created https://github.com/QubesOS/qubes-core-agent-linux/pull/362 for it.
