### ISSUE TITLE
Anti-Evil-Maid (AEM) not available in 4.1

### ISSUE THREAD

**Issue by h4xor666** [QubesOS/qubes-issues#7272]
### The problem you're addressing (if any)
I had been successfully using AEM on 4.0. After installing 4.1, the anti evil maid package doesn't seem to exist.

### The solution you'd like
Anti evil maid for 4.1

### The value to a user, and who that user might be
I and many other users use it as an integral part of Qubes OS, it would make sense to have it in 4.1 as it was in 4.0

**Comment by zpc0** [comment]
Since AEM for 4.1 (and 4.2) are available, this can be closed?
QubesOS/updates-status#1562
QubesOS/updates-status#4134

**Comment by andrewdavidwong** [comment]
> Since AEM for 4.1 (and 4.2) are available, this can be closed?

Looks like it, yeah. Thanks for pointing this out.

Closing as resolved. If anyone believes this issue is not yet resolved, or if anyone is still affected by this issue, please leave a comment, and we'll be happy to reopen it. Thank you.
