### ISSUE TITLE
"Warning: USB in dom0 is not restricted" message is unclear

### ISSUE THREAD

**Issue by TNTBOMBOM** [QubesOS/qubes-issues#7275]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

4.1

### Brief summary

Booting qubes 4.1 will show this at the top, What is it trying to say how to solve it if its an issue?

### Steps to reproduce

Just boot qubes 4.1 after fully installed 

### Expected behavior

No warnings ? 

### Actual behavior

This warning at the top each time 4.1 booted.

**Comment by andrewdavidwong** [comment]
Sounds like this might need an [explanatory tooltip](https://github.com/QubesOS/qubes-issues/issues/2211).

**Comment by GWeck** [comment]
But this occurs **before** Qubes really starts - just after OS selection in GRUB.
