### ISSUE TITLE
Add dom0 Terminal to App Menu left-barre

### ISSUE THREAD

**Issue by ninavizz** [QubesOS/qubes-issues#7277]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### The problem you're addressing (if any)
For Qubes in its current state, many things are only actionable on the command-line. Likewise, +2/3 of all Qubes users are developers, who think in BASH more naturally than verbal languages. 

Even when Qubes OS is adopted by every journalist, human rights defender, and public utility worker in the world—it'll still have at not-insignificant userbase of developers that feel anxious when not having quick access to dom0's Terminal.

### The solution you'd like
Marta commented when looking at a [recent prototype of the App Menu](https://www.figma.com/proto/jg0a8go9LITnW7ONn7vEPz/valentina_figma?page-id=0%3A1&node-id=0%3A2&viewport=241%2C48%2C1&scaling=min-zoom&starting-point-node-id=0%3A2), that the ease of access to dom0's terminal was wonderful. As such, this issue is to add this feature to the next release of the appmenu!

#### Artwork
Note: The SVG below is set to use `#F032E6` intentionally, so that it final artwork is intentionally created to the correct color values. :D

![TerminalIcon—Pink](https://user-images.githubusercontent.com/8262612/154360163-47e0f5dd-c10e-43d3-858d-1c6e537b19d6.svg)

#### States in Figma
See [Library page in Figma](https://www.figma.com/file/jg0a8go9LITnW7ONn7vEPz/valentina_figma?node-id=511%3A7210)
NOTE: I'm still working on Light/Dark modes, but as of now, the power button and the app button both behave differently than the "tab" buttons above them—which I'm on the fence about. But shouldn't be, because it's a ux best practice.

<img width="681" alt="Screen Shot 2022-02-16 at 1 18 34 PM" src="https://user-images.githubusercontent.com/8262612/154360434-17c58980-c5a7-4cd4-821a-04366575cf4a.png">

### The value to a user, and who that user might be
Currently: All Qubes OS users
Future: Developers, Linux native users

**Comment by marmarta** [comment]
After a long-ish internal discussion, we decided not to implement it (let's not encourage dom0 usage); there is now working search and decent favorites, which cover the use case.
