### ISSUE TITLE
qvm-template shows confusing error message `ERROR: [Errno 2] No such file or directory: '/etc/qubes-rpc/qubes.TemplateSearch'` if dom0 UpdateVM is set to `none`

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#7287]
### Qubes OS release

R4.1

### Brief summary

Running qvm-template without a Qubes dom0 UpdateVM set shows a confusing error message.

### Steps to reproduce

1. set dom0 update VM to none
2. 

    qvm-template --verbose --enablerepo=qubes-templates-community-testing install whonix-gw-16 whonix-ws-16

### Expected behavior

A useful error message.

### Actual behavior

Confusing error message.

> ERROR: [Errno 2] No such file or directory: '/etc/qubes-rpc/qubes.TemplateSearch'

**Comment by deeplow** [comment]
I can confirm this. Running on 4.1 by simply running

```shell_session
$ qvm-template install  fedora-34-minimal
[Qrexec] /bin/sh: /etc/qubes-rpc/qubes.TemplateSearch: No such file or directory
ERROR: qrexec call 'qubes.TemplateSearch' failed.
```

And I can confirm `/etc/qubes-rpc/qubes.TemplateSearch` does indeed not exist.

For me there was no need to `set dom0 update VM to none` to experience this. It's the default `sys-firewall`.

**Comment by marmarek** [comment]
I think your sys-firewall use template imported from R4.0.

**Comment by deeplow** [comment]
Oh, right. That is correct. I was thinking this policy was in `dom0` but that's right, it's in `sys-firewall` and I must have changed sys-firewall` to the imported `fedora-34` template.

Changing it now the default fedora-34 (which I fortunately had) fixes it.

**Comment by jamke** [comment]
I have this too. Very confusing message and situation.
And I don't have `dom0 UpdateVM is set to none`.

**Comment by jamke** [comment]
In my case the reason for this error was UpdateVM set to a VM that had fedora-35-based template - it was also restored from backup from R4.0.
Changing template to fedora-36 for UpdateVM solved the issue.
