### ISSUE TITLE
A missing sun_family in pacat_simple_vchan.c

### ISSUE THREAD

**Issue by logoerthiner1** [QubesOS/qubes-issues#7288]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

R4.1

### Brief summary

https://github.com/QubesOS/qubes-gui-daemon/blob/master/pulse/pacat-simple-vchan.c#L748

Add a line of
```
    addr.sun_family = AF_UNIX;
```

Otherwise the `/var/run/qubes/audio-control.appvmname` UNIX Domain Socket cannot be `bind`ed in my `sys-audio` and mic does not pass.

Also, dom0 part of code `/usr/lib/python3.8/site-packages/qubesguidaemon/mic.py` summarizes all `subprocess.CalledProcessError` as a `pulseaudio agent not running`, which is not descriptive and it took me a while to diagnose that this issue is caused by a Qubes bug rather than my fault.

I believe that this is not a security critical issue.

**Comment by DemiMarie** [comment]
@logoerthiner1 do you want to make a PR?

**Comment by logoerthiner1** [comment]
> @logoerthiner1 do you want to make a PR?

https://github.com/QubesOS/qubes-gui-daemon/pull/92

Despite I being unfamiliar with qubes development, I just tried to make one.
