### ISSUE TITLE
[Qubes 4.1] Inconsistent microphone and webcam behaviour

### ISSUE THREAD

**Issue by petaramesh** [QubesOS/qubes-issues#7289]
### Qubes OS release

Qubes 4.1 (upgraded from Qubes 4.0)

Lenovo Thinkpad P51

### Brief summary

Webcam and microphone used to work properly in Qubes 4.0 (typically in MS Teams or Zoom), after upgrading to Qubes 4.1. I note the following issues :

- Microphone automatic level adjustment does not seem to work in either Teams or Zoom - mike volume is very low until manually raised.

- Webcam (Integrated USB device identifying itself as : SunplusIT_Inc_Integrated_Camera) shows erratic behaviour, sometimes working sometimes NOT.

When NOT working the following happens : 
- Starting the application that uses the webcam causes webcam LED to light up.
- But the app says “No webcam found” or “Webcam unavailable” or the like (same in “Cheese” application)
- Checking the USB Qubes icon shows that the webcam seems to have spontaneously “detached” from the Qube, however its LED stays lit (ON).

- From there it is impossible to get the webcam working unless completely restarting the Qube that was (trying to) use it.

- In some situations I found impossible to get the webcam working until a full system reboot.

This is new to Qubes 4.1 and never happened in 4.0.

Koind regards.

**Comment by DemiMarie** [comment]
Have you tried using Qubes Video Companion?  Assigning myself because this is a problem that I have experienced several times in the past and switching to Qubes Video Companion fixed it.

**Comment by jevank** [comment]
Increase sys-usb memory might helps too.

**Comment by petaramesh** [comment]
Thanks, I will try per your suggestions (first by increasing memory), and let you know.

**Comment by petaramesh** [comment]
qubes-video-companion github page states it can be easily installed as a package using “dnf install” but I can't find it, even in the contrib repo.
Am I supposed to compile it from sources ?

**Comment by DemiMarie** [comment]
> qubes-video-companion github page states it can be easily installed as a package using “dnf install” but I can't find it, even in the contrib repo. Am I supposed to compile it from sources ?

That is on me, good catch.

**Comment by 0spinboson** [comment]
this is probably due to the switch in domU from

**Comment by DemiMarie** [comment]
> this is probably due to the switch in fedora34 to pipewire from pulseaudio, and/or other changes in f34. When I atttach them to a f32 VM, it behaves fine, but when I try to attach to f34, I often have to connect a second time for things to work half-decent, and volume mixing seems broken.

f32 is end of life; please do not use it in a VM anymore.  For f34, try uninstalling the pipewire package.

**Comment by petaramesh** [comment]
I had definitely no problem using the webcam and microphone in Qubes 4.0 in either Fedora 32, 33 or 34 VMs.

The issue appeared after system upgrade to Qubes 4.1.

DemiMarie, so, am I supposed to compile Video Companion, or is ther a way I can get binary RPMs ?

**Comment by petaramesh** [comment]
I haven't tried Video Companion yet, but it looks like the webcam is working flawlessly on my system since I upgraded sys-usb RAM to 384 MB...
