### ISSUE TITLE
qubes-dist-upgrade rolls back more than desired, breaking Qubes installation

### ISSUE THREAD

**Issue by petaramesh** [QubesOS/qubes-issues#7290]
### Qubes OS release

Qubes 4.1

### Brief summary

Trying to use qubes-dist-upgrade to ONLY update restored Qubes, tries to rollback everything if Qube upgrade fails, thus breaking everything.

### Steps to reproduce

I had Qubes which I knew conversion might be problematic so I backed them up and erased them before upgrading the system to Qubes 4.1 using qubes-dist-upgrade. Upgrade went smooth.

Afterwards I restored the previous 4.0 qubes and told myself I should try to upgrade them *ONLY* using

qubes-dist-upgrade --template-standalone-upgrade --only-update my-restored-qube

### Expected behavior

Would have expected it to either succeed on said Qube or at least fail gracefully

### Actual behavior

It Failed to upgrade Qube SO IT DECIDED TO ROLLBACK EVERYTHING IMMEDIATELY WITHOUT USER INPUT : 

- REVERTED SYSTEM PARTITION TABLE that had been changed by actual upgrade, thus destroying /boot
- RESTORED PREVIOUS EFI ENTRIES.

=> SYSTEM FULLY BROKEN.

**Comment by andrewdavidwong** [comment]
@DemiMarie, why the 4.0 updates milestone? Does this also affect 4.0 somehow?

**Comment by petaramesh** [comment]
I would believe that qubes-dist-upgrade is part of 4.0 to upgrade to 4.1, so if it breaks everything in such situations, fixing it in 4.0 would seem logical ?

**Comment by DemiMarie** [comment]
@petaramesh yup.  @andrewdavidwong qubes-dist-upgrade is a part of 4.0, not 4.1.

**Comment by andrewdavidwong** [comment]
Ok, it just seemed odd, because the problem (if I understood the description correctly) occurred entirely in a 4.1 installation, i.e., the undesired rollback was after the system had already been successfully upgraded to 4.1. This makes it seem like `qubes-dist-upgrade` also runs on 4.1 (or else it's unclear to me how it could've caused a problem on a 4.1 system).

**Comment by DemiMarie** [comment]
> This makes it seem like qubes-dist-upgrade also runs on 4.1 (or else it's unclear to me how it could've caused a problem on a 4.1 system).

Ah, good point

**Comment by petaramesh** [comment]
You understand right, I installed qubes-dist-upgrade in 4.0 to allow upgrading to 4.1 as per the documentation.

However my understanding was that templates and standalone VMs from 4.0, restored onto 4.1, needed upgrade using this tool - which is still available once system upgraded to 4.1, so I don't actually know if it's still the same 4.0 version or a 4.1 version that got upgraded along with the rest.

However the matter is that, once started on 4.1 and failing to - ONLY - upgrade an individual qube, it tries - with no user interaction - to rollback the entire previous complete system upgrade, resulting in reverting the partition table and EFI nvram entries, thus destroying /boot and damaging the whole system beyond repair.

Whether or not I was mistaken using this tool at this stage, I strongly believe it should not, in any case, try to rollback a system upgrade that ended in success, let alone without any user interaction that could prevent a disaster.

Kind regards.

**Comment by andrewdavidwong** [comment]
Sounds like it should, at the very least, list the things that will be rolled back and ask if the user wishes to proceed.

**Comment by petaramesh** [comment]
Especially if you run it with :

qubes-dist-upgrade --template-standalone-upgrade --only-update some_specific_qube

You wouldn't expect it in any case to rollback anything else than what you asked it to do...

**Comment by andrewdavidwong** [comment]
Looks like automatic closure failed for some reason. Manually closing as fixed.
