### ISSUE TITLE
Two notification daemons installed in debian-11

### ISSUE THREAD

**Issue by 3hhh** [QubesOS/qubes-issues#7292]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
4.1, debian-11 template

### Brief summary

The default debian-11 template runs different notification daemons at the same time. `dbus` however only supports exactly one notification daemon (otherwise it randomly decides which daemon to use). This currently leads to the absurd situation that root (`mate-notification-daemon`) runs a different daemon than the user (`xfce4-notifyd`). Therefore these notifications also have a different look & feel.

4.0 ran `mate-notification-daemon` only.

### Steps to reproduce

Inside a deian-11 VM check `ps aux|grep notify` as `root` or `grep Notifi* /usr/share/dbus-1/services/*`.

I haven't checked Fedora.

### Expected behavior

Exactly one daemon installed.

### Actual behavior

Multiple daemons installed.

**Comment by 3hhh** [comment]
Btw removing `mate-notification-daemon` results in the same daemon for both `root` and the user. Removing `xfce4-notifyd` will remove `qubes-vm-recommended` which is not what one wants... I guess this is the old issue of rpm not being able to specify packages as optional dependencies. -_-

In general users should be able to decide their own notification daemon. Currently that can only be accomplished by deleting the respective `/usr/share/dbus-1/services/` file.

**Comment by DemiMarie** [comment]
I would strongly prefer `mate-notification-daemon`.  `xfce4-notifyd` is buggy to the point of requiring a workaround in the GUI daemon.

**Comment by 3hhh** [comment]
+1 from me for `mate-notification-daemon`.

However dom0 has `xfce4-notifyd` correctly set up, my outdated fedora-34 template oddly had no notification service at all in `/usr/share/dbus-1/`, but started `xfce4-notifyd` on `notify-send` from a user (not sure why) and didn't work with `notify-send` from `root`. I guess the latter would be a separate bug, but possibly upstream...

Btw it might make sense to implement an integration test for all templates and dom0 to check whether the services installed by default at `/usr/share/dbus-1/services/` have a unique name. Duplicates are always bugs as this one here.

**Comment by 3hhh** [comment]
`dunst` is also looks like a good alternative for users who need notification filters etc., but probably not viable as default.

**Comment by andrewdavidwong** [comment]
I see that the original report mentioned that this affects 4.1. Reopening.
