### ISSUE TITLE
Exporting a path in storage system is racy

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#7293]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

R4.1 but this problem probably predates R4.0

### Brief summary

According to the LVM developers, opening a logical volume without synchronizing against anything that might destroy it is a bug in the application.  However, the backup code does exactly that.  `export()` returns a path that is opened by an external program, without synchronizing against qubesd.

Having `export()` take a lock which is not released until `export_end()` is called is not sufficient, as it cannot be made robust against qubesd or the external program crashing or being restarted at exactly the wrong time.  Instead, `export()` should return a file descriptor.  Destroying a block device that is currently open deterministically fails with `-EBUSY`, so there is no race condition.  `export_end()` is still necessary so that the snapshot can be destroyed.

### Steps to reproduce

I have no idea how to trigger this race, much less a reproducer.

### Expected behavior

No race condition

### Actual behavior

Race condition

**Comment by marmarek** [comment]
I don't like FD passing approach in qubesd, because it can easily leak that FD to some unrelated process (you can try to set CLOEXEC, but that's getting complex if you want to actually allow inheriting it for some specific process). But `export()` can make a snapshot that is removed on `export_end()` - similar to what import code does.

BTW, currently you don't need to care about making usable backup in case of qubesd crash/restart. Restarting qubesd will interrupt making the backup (even if specific exported volume part is already scheduled to be packed, it won't be sent anywhere if qubesd dies for whatever reason).

**Comment by DemiMarie** [comment]
> I don't like FD passing approach in qubesd, because it can easily leak that FD to some unrelated process (you can try to set CLOEXEC, but that's getting complex if you want to actually allow inheriting it for some specific process).

At least in Python, CLOEXEC is the default, and I believe the subprocess module strips CLOEXEC where needed.  So I don’t think this is too much of a problem in Python, though it might be trickier in C.

> But `export()` can make a snapshot that is removed on `export_end()` - similar to what import code does.

The problem I ran into with this approach is figuring out how to handle removing the snapshot.  qubesd can’t remove the snapshot until `export_end()` is called, due to the race condition mentioned above.  But if the call to `export_end()` is missed for any reason (qubesd restart, etc), the snapshot (and its associated disk space) are leaked.

It is safe to remove the snapshot if `export()` has not been called since system bootup, since nobody could possibly be using it.  Therefore, one option would be to set a boolean flag (existence of a file in `/run`?) no later than the first call to `export()`, and delete all `export()`-generated snapshots during startup if the flag is not set.  That means that a reboot is required to reclaim the space, however, which is not nice.

The advantage of FD-passing is that removing a snapshot that is still in use will safely and deterministically fail with `-EBUSY`, so qubesd can safely garbage collect snapshots not in use.  It might even be able to use inotify to avoid the need for `export_end()` entirely.  It also fits with the general principle that one should prefer passing capabilities to objects rather than their names.  If we decide to implement privilege separation, for example, then FD passing will be necessary in any case.

**Comment by DemiMarie** [comment]
Given the complexity of this approach, I think a simpler solution is to make sure that even if a qube is resized while being backed up, the backup will still restore properly.  @marmarek thoughts?

**Comment by DemiMarie** [comment]
> For backup to be consistent, the volume that is backed up cannot change while reading it. It includes both its content, but also its size. Taking a snapshot sounds like an obvious solution for this, but there may be some other options - like disallowing resize while backup is running.

Taking a snapshot is the approach I would prefer, but I can’t think of a way to avoid races and/or leaks without FD passing.

**Comment by marmarek** [comment]
> currently you don't need to care about making usable backup in case of qubesd crash/restart. Restarting qubesd will interrupt making the backup

This gives you a place to cleanup.

**Comment by DemiMarie** [comment]
> > currently you don't need to care about making usable backup in case of qubesd crash/restart. Restarting qubesd will interrupt making the backup
> 
> This gives you a place for cleanup.

Turns out there is only one place where the block device is actually opened, and I can trivially refactor it to have qubesd itself open it.
