### ISSUE TITLE
Allow user to disable split-gpg notifications

### ISSUE THREAD

**Issue by mfc** [QubesOS/qubes-issues#7295]
### The problem you're addressing (if any)

as a user i find split-gpg access notifications distracting and not beneficial from security perspective.

if i have a rpc policy of:
```
mail gpg allow
$anyvm $anyvm ask
```
what is the value of being notified every time `mail` accesses `gpg`? i've allowed that to happen. obviously as user what i am interested in knowing is when `$anyvm` that is *not* `mail` is attempting to access `gpg`.

in the past I could disable notifications via commenting out notify-send in
`/etc/qubes-rpc/qubes.Gpg`: https://groups.google.com/g/qubes-users/c/ebgXRk5OMEw

in R4.1 notify-send no longer exists in the gpg rpc policy (now at `/etc/qubes-rpc/policy/qubes.Gpg`). does it exist some place else? or otherwise how can i disable these notifications? unlike other notifications (like OpenVPN connection notifications) there is no option in the notification to disable it.

**Comment by marmarek** [comment]
> in the past I could disable notifications via commenting out notify-send in
> `/etc/qubes-rpc/qubes.Gpg`

Nothing has changed here, you can still do it. Maybe you checkd wrong qube? Look into `gpg` (or rather: its template).

**Comment by mfc** [comment]
you're right, i was looking in wrong place (`dom0`). thanks!
