### ISSUE TITLE
Ambiguity in program running environment listing when using dmenu and DVMs

### ISSUE THREAD

**Issue by auroraanon38** [QubesOS/qubes-issues#7297]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

4.1

### Brief summary

The way `dmenu` or `rofi` lists programs to be run using `i3-dmenu-desktop` is ambiguous when trying to run programs in DispVMs based on DVM templates, as the name of the program and running VM is not indicative of whether they will be run using `qvm-run --dispvm` or without the `--dispvm` argument.

It instead simply lists the program and vm name multiple times with numbers appended (I think this is done by the Perl `i3-dmenu-desktop` script), without indication of what will be running in a dispvm or not. The order of presentation of the results also apparently cannot be relied upon.

### Steps to reproduce

1. Freshly install Qubes 4.1, install `i3` and `i3-settings-qubes`.
2. Create a DVM template and add some programs to show in the menus using the `Qube Manager`.
3. Open `dmenu` and enter the chosen program's name.
4. Try to open the program, which may or may not open in the template VM itself, or in a DispVM based on it instead.

### Expected behavior

Unambiguous listing of VM+Program selection in `dmenu`.

### Actual behavior

Ambiguous listing of VM+Program selection in `dmenu`. In Pre-4.1 versions, the TemplateVM listings simply did not appear, so all listings ran in DispVMs (for better or worse) without any ambiguity.

### Possible solutions

[I have a patch I'm currently using on my own system](https://github.com/auroraanon38/qubes-desktop-linux-common/tree/remove-dvm-ambiguity) which eliminates all such ambiguity without the loss of the new functionality (running in Template VM). All it does it change the name of the listing to reflect how it will be run.

One simply needs to regenerate the Application `.desktop` files after applying the patch for it take effect. That can be done by refreshing from the VMs in the `Qube Manager` "App shortcuts" menus.

**Comment by DemiMarie** [comment]
> ###
> [I have a patch I'm currently using on my own system](https://github.com/auroraanon38/qubes-desktop-linux-common/tree/remove-dvm-ambiguity) which eliminates all such ambiguity without the loss of the new functionality (running in Template VM). All it does it change the name of the listing to reflect how it will be run.

Please file a PR for this!  XFCE4’s desktop icons have the same problem.

**Comment by anadahz** [comment]
This is in fact very irritating.

I prefer the old behavior of `i3-dmenu-desktop` which was show only the desktop entries of the disposable VMs.
