### ISSUE TITLE
Editing Copy (inter-qube) keyboard shortcuts fails while Editing Paste (inter-qube) keyboard shortcuts succeeds

### ISSUE THREAD

**Issue by logoerthiner1** [QubesOS/qubes-issues#7302]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

R4.1

### Brief summary

Editing Copy (inter-qube) keyboard shortcuts fails while Editing Paste (inter-qube) keyboard shortcuts succeeds

### Steps to reproduce

1. open Qubes Global Settings
2. edit Keyboard shortcuts - Copy (inter-qubes) and Paste (inter-qubes)
3. try copying and pasting cross vm

### Expected behavior

The new key combination work when copying and when pasting.

### Actual behavior

The new key combination work only when pasting.

**Comment by brycepg** [comment]
Funny, the new key combination only works for me while copying, changing the paste combination causes all pasting to not work at the moment.

Also my custom Ctrl+Win+Shift+C and Ctrl+Win+Shift+V shortcuts were stripped during the upgrade from 4.0 to 4.1

**Comment by marmarek** [comment]
> Funny, the new key combination only works for me while copying, changing the paste combination causes all pasting to not work at the moment.

It should function for qubes started after the change.

> Also my custom Ctrl+Win+Shift+C and Ctrl+Win+Shift+V shortcuts were stripped during the upgrade from 4.0 to 4.1

Indeed, this seems to be a bug in upgrade tool (but since R4.0 is EOL already, that won't be fixed).
