### ISSUE TITLE
qubes-dist-upgrade 4.0=>4.1 does not work when Dom0 upgrade qube is sys-whonix

### ISSUE THREAD

**Issue by nereocystis** [QubesOS/qubes-issues#7304]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
4.0

### Brief summary
When qubes-dist-upgrade is run in 4.0, upgrade fails if Dom0 upgrade qube is sys-whonix

### Steps to reproduce
install qubes-dist-upgrade in a 4.0 release
Set Dom0 upgrade qube to sys-whonix, with template set to whonix-gw-16

### Expected behavior
Upgrade to 4.1 should proceed

### Actual behavior
When I run qubes-dist-upgrade, I receive the following message
[kevin@dom0 ~]$ sudo qubes-dist-upgrade
ERROR: UpdateVM (sys-whonix) should be at least Fedora 30 or Debian 11 template based VM.
[kevin@dom0 ~]$ exit

This message is confusing, since sys-whonix uses template of whonix-gw-16, which is Debian 11.
I modified qubes-dist-upgrade slightly to allow my setup to pass, and the upgrade continued successfully (with a few solvable problems on the way).
The script requires that the template be named "debian-n", where n >=11, or "fedora-m" where m>=30.

I suggest that the script be modified to allow template of whonix-gw-n, where n>=16.
Also, there error message should be more clear. Error should clearly state that template must have a well-defined name, regardless of the version of Debian or fedora. Alternatively, the script could check the real version of the VM, rather than the name of the template.

**Comment by andrewdavidwong** [comment]
> This message is confusing, since sys-whonix uses template of whonix-gw-16, which is Debian 11.

Just because Whonix is _based on_ Debian doesn't mean it's _the same_, for the same reason that Ubuntu isn't identical to Debian. There are a great many distros based on Debian. I think the problem here is just a faulty assumption. The error message is actually quite clear.

**Comment by DemiMarie** [comment]
> > This message is confusing, since sys-whonix uses template of whonix-gw-16, which is Debian 11.
> 
> Just because Whonix is _based on_ Debian doesn't mean it's _the same_, for the same reason that Ubuntu isn't identical to Debian. There are a great many distros based on Debian. I think the problem here is just a faulty assumption. The error message is actually quite clear.

This is in fact a bug in Qubes OS.  Whonix includes every Debian package available and should be more than capable of being an UpdateVM.

**Comment by andrewdavidwong** [comment]
> > > This message is confusing, since sys-whonix uses template of whonix-gw-16, which is Debian 11.
> 
> > 
> 
> > Just because Whonix is _based on_ Debian doesn't mean it's _the same_, for the same reason that Ubuntu isn't identical to Debian. There are a great many distros based on Debian. I think the problem here is just a faulty assumption. The error message is actually quite clear.
> 
> 
> 
> This is in fact a bug in Qubes OS.  Whonix includes every Debian package available and should be more than capable of being an UpdateVM.

Ok, but that still doesn't change the fact that Whonix is not Debian.

**Comment by nereocystis** [comment]
I appreciate the work which has gone into qubes -dist-upgrade.
If the person using qubes-dist-upgrade does not understand the error message,  then the error message is not clear.
Even if the error message is clear to the author. 

The error message should give enough information so that the used can figure out what to do next. 
A few other people have mentioned issues with upgrade,. I'm not alone.
Here are my suggestions. Please chose one or more of them :
1. Allow  sys-whonix to be used as upgrade.
2. Change error message to suggest steps to take to solve problem.
3. Change instruction page to mention this issue, and the steps to take to solve the problem. This step is important to make it easier to solve the problem.

**Comment by nereocystis** [comment]
As a further case. I usually clone the base debian template, say debian-11, and slightly change the name. I might just install additional packages, perhaps some directly downloaded. These modified templates would not work with the qubes-dist-upgrade script, though it is still a Debian release, it just has a different name.
When I think of a Debian release, I would probably look at /etc/debian_version to determine which version I have, rather than trusting the template name.
Of course, either of these can be faked.
And sys-whonix does show a debian_version of 11.2, in my template, which led me to think that I should be OK.
You can definitely argue that this isn't *really* Debian, but additional documentation would be helpful here.

**Comment by DemiMarie** [comment]
> > > > This message is confusing, since sys-whonix uses template of whonix-gw-16, which is Debian 11.
> > 
> > 
> > > 
> > 
> > 
> > > Just because Whonix is _based on_ Debian doesn't mean it's _the same_, for the same reason that Ubuntu isn't identical to Debian. There are a great many distros based on Debian. I think the problem here is just a faulty assumption. The error message is actually quite clear.
> > 
> > 
> > This is in fact a bug in Qubes OS.  Whonix includes every Debian package available and should be more than capable of being an UpdateVM.
> 
> Ok, but that still doesn't change the fact that Whonix is not Debian.

It’s not Debian, but it should work just fine for `qubes-dom0-update`.  If not, I would consider that a Whonix bug unless @adrelanos says otherwise.

**Comment by nereocystis** [comment]
> > > > > This message is confusing, since sys-whonix uses template of whonix-gw-16, which is Debian 11.
> > > > 
> > > > 
> > > > Just because Whonix is _based on_ Debian doesn't mean it's _the same_, for the same reason that Ubuntu isn't identical to Debian. There are a great many distros based on Debian. I think the problem here is just a faulty assumption. The error message is actually quite clear.
> > > 
> > > 
> > > This is in fact a bug in Qubes OS.  Whonix includes every Debian package available and should be more than capable of being an UpdateVM.
> > 
> > 
> > Ok, but that still doesn't change the fact that Whonix is not Debian.
> 
> It’s not Debian, but it should work just fine for `qubes-dom0-update`. If not, I would consider that a Whonix bug unless @adrelanos says otherwise.

I can verify that whonix works fine for an upgrade to 4.1. Tested 2 days ago.

**Comment by adrelanos** [comment]
> The script requires that the template be named "debian-n", where n >=11, or "fedora-m" where m>=30.

I don't think any script checkes dom0 template names and refused updating based on template name?

> It’s not Debian, but it should work just fine for `qubes-dom0-update`. If not, I would consider that a Whonix bug unless @adrelanos says otherwise.

I'd say a Qubes issue. There's no Qubes automated test checking if other (Fedora, Debian, Whonix) templates can successfully release upgrade from 4.0 to 4.1 (or more generically a.b to c.d)?

**Comment by DemiMarie** [comment]
> > The script requires that the template be named "debian-n", where n >=11, or "fedora-m" where m>=30.
> 
> I don't think any script checkes dom0 template names and refused updating based on template name?

It does :disappointed:

**Comment by brendanhoar** [comment]
Would tags be a better solution for candidate VMs/templates?

B

**Comment by marmarek** [comment]
> There's no Qubes automated test checking if other (Fedora, Debian, Whonix) templates can successfully release upgrade from 4.0 to 4.1 (or more generically a.b to c.d)?

Actually there one testing it with Debian 11.

Anyway, I'll change the check to look for `dnf` inside the updatevm - which is what really is needed.

**Comment by andrewdavidwong** [comment]
Looks like automatic closure failed for some reason. Manually closing as fixed.

**Comment by tlaurion** [comment]
@marmarek we are 7 days later. Packages will land in stable repos when?
