### ISSUE TITLE
update 'xen-4.14.4' fails boot for 'Above 4G' bios option

### ISSUE THREAD

**Issue by fiddler-on-the-roof** [QubesOS/qubes-issues#7308]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
4.1

### Brief summary
black screen on boot after update `xen` to (testing) `4.14.4`
turning off 'Above 4G' in UEFI BIOS is the cure

### Steps to reproduce
- up-to-date R4.1
- AMD GPU
- AMG CPU
- AMI BIOS
- turn on 'Above 4G' in BIOS
- try to update from 'current-testing' for 'xen*'

### Expected behavior
- still working with the current BIOS options on reboot

### Actual behavior
- black screen on reboot
- turn off 'Above 4G' in BIOS
- now boot is OK
- also update `xen` to `4.14.4-1.57` from `unstable` does not help with same behavior

**Comment by marmarek** [comment]
What is the exact BIOS setting name?

Try removing `console=none` option from xen cmdline (in grub) - does it give you more details?

**Comment by fiddler-on-the-roof** [comment]
It is 'Above 4G decoding' at 'Boot' page, with help about 'device decoding at boot stage'.
Enabling 'console' shows xen boots kernel OK, and it's kernel fail to output to GPU.
I've been managed to enter the password (at black screen) and system boots and works except display functioning.

Note: using kernel '5.16.x', because '5.10.x' does not work for this system.

**Comment by marmarek** [comment]
Can you attach a kernel log of such non working startup? Since the system otherwise starts, you should be able to extract it using `journalctl` (use `-b -1` flag for example, to get logs from previous boot). Good + bad Xen log would be useful too, you can get it from `/var/log/xen/console/hypervisor.log`.

**Comment by fiddler-on-the-roof** [comment]
Sorry, the issue was not so critical for me (at that moment).
Just now I have tested all current combinations of BIOS options and see kernels booting OK.
Thanks for attention.
