### ISSUE TITLE
gui daemon crashes when disconnecting HDMI display

### ISSUE THREAD

**Issue by honzahosek** [QubesOS/qubes-issues#7309]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
4.1

### Brief summary
Sometimes when disconnecting external (HDMI) display. All windows disappear, but for example sound plays on. In all guid logs is last line "Absurd work area, crashing"

### Steps to reproduce
It does not happen every time, so it might be hard to reproduce. But the "work area" could be simulated and fix it with better handling of some temporary state.

### Expected behavior
Recover from work area resizing.

### Actual behavior
Qubes need to be restarted.

**Comment by DemiMarie** [comment]
Thanks for the report!  This comes from [this code](https://github.com/QubesOS/qubes-gui-daemon/blob/341550de981904643a7a07f80e57b48328754d45/gui-daemon/xside.c#L480-L513), and the crash means that either there is a bug in the GUI daemon or the window manager is reporting completely nonsensical values for the width and height of the display.  The first step is to figure out what the incorrect work area _is_; I will file a PR for that.

**Comment by DemiMarie** [comment]
Reopening because https://github.com/marmarek/qubes-gui-daemon/commit/8c2d4132274366cab53ca5fca437f5e1af125684 just adds logging.

**Comment by honzahosek** [comment]
@DemiMarie How do I install gui-daemon with the new logging for reporting what is going on?

**Comment by DemiMarie** [comment]
> @DemiMarie How do I install gui-daemon with the new logging for reporting what is going on?

Update with the current-testing repository turned on

**Comment by honzahosek** [comment]
So I updated it and connected and disconnected HDMI few times. After last disconnect windows of 2 of 3 running appvms disappeared. 

The end of log file: 
```
reloading X server parameters...
reloading X server parameters...
reloading X server parameters...
reloading X server parameters...
ErrorHandler: BadAccess (attempt to access private resource denied)
                 Major opcode: 130 (MIT-SHM)
                 Minor opcode: 1 (X_ShmAttach)
                 ResourceID:   0x4400239
                 Failed serial number:  5563
                 Current serial number: 5564
XShmAttach failed for window 0x4400221(remote 0x2a00006)
PANIC: invalid work area:
     x: 0 (limit 1048576)
     y: 1111 (limit 1048576)
 width: 1920 (limit 1048576)
height: 18446744073709551585 (limit 1048576)
Exiting!

```
Width is width of my laptops screen. The external display is wider. I setup external display on top of the laptops screen.

I think the absurd work area is there only for a short moment. The daemon should wait a bit and try few more times before giving up.

**Comment by honzahosek** [comment]
Also I had other issue with external displays. 

I was connected to smaller display, then disconnected, then connected bigger display. One appvm worked well. But other had limited mouse events to size the smaller display.

So drawing on full screen of the display looked like the white area:
![2022-03-07-100121](https://user-images.githubusercontent.com/5223021/158050618-7e989f17-ca39-49e2-882f-b8bf751e730b.png)

**Comment by DemiMarie** [comment]
18446744073709551585 is `2 ** 64 - 31`, which is `UINT64_MAX - 30` or -31 in 2’s complement.

**Comment by marmarek** [comment]
> I think the absurd work area is there only for a short moment. The daemon should wait a bit and try few more times before giving up.

I agree, if there is work area already set, an absurd update should be ignored (just log warning, use old values).

**Comment by marmarek** [comment]
> 18446744073709551585 is `2 ** 64 - 31`, which is `UINT64_MAX - 30` or -31 in 2’s complement.

Hmm, do negative values have some special meaning there? I haven't seen that in the spec...
https://specifications.freedesktop.org/wm-spec/latest/ar01s03.html#idm46476783576048:
`These geometries are specified relative to the viewport on each desktop and specify an area that is completely contained within the viewport.`
For me it sounds like negative values are not valid (whatever negative height would mean).

So, regardless of making gui-daemon more resilient for such thing, it sounds like xfwm4 bug to be reported.

**Comment by DemiMarie** [comment]
> > I think the absurd work area is there only for a short moment. The daemon should wait a bit and try few more times before giving up.
> 
> I agree, if there is work area already set, an absurd update should be ignored (just log warning, use old values).

PR coming
