### ISSUE TITLE
Text no longer wrapped in dom0 notification and cannot be scrolled

### ISSUE THREAD

**Issue by JPL1** [QubesOS/qubes-issues#7312]
### Qubes OS release
4.1

### Brief summary
On opening LibreOffice writer for the first time after starting an AppVM based on Debian11 a large warning appears, but the text does not wrap making it illegible (see image)

### Steps to reproduce
Install LibreOffice in Debian11 template, open AppVM based on that template, open Writer

![Screenshot_2022-02-27_19-51-43a](https://user-images.githubusercontent.com/12783198/155897788-5e158a2b-acf3-4929-a8aa-0c90b30c1e5a.png)

**Comment by andrewdavidwong** [comment]
This same notification in 4.0 displays the text correctly wrapped so that it's readable, so this appears to be a regression in 4.1.

**Comment by andrewdavidwong** [comment]
Does hovering over the notification display the full text in a tooltip? (Probably not, but just checking.)

**Comment by JPL1** [comment]
No, hovering doesn't display the text

**Comment by 3hhh** [comment]
Possibly some fallout of #7292

**Comment by andrewdavidwong** [comment]
Pinning this, as I've seen questions about this crop up multiple times lately.
