### ISSUE TITLE
Confusing notifications on attaching USB devices

### ISSUE THREAD

**Issue by JPL1** [QubesOS/qubes-issues#7315]
### Qubes OS release
4.1

### Brief summary
On attaching a USB device to an AppVM using the USB widget, two notices pop up, one to say the device has been attached, and another to say it has been removed. I understand what is being attempted here but would argue that this is confusing and apparently contradictory (so it has been attached and removed?). The 'removed' message does not convey any useful information in the context, so I would suggest ditching the 'removed' message altogether to avoid confusion and provide a cleaner UX.

NB. On mounting a USB device with multiple partitions you get a whole series of these messages, one per partition,  which is even more confusing and messy.

### Steps to reproduce

Attach a USB storage device using the widget

![Screenshot_2022-02-28_19-57-14](https://user-images.githubusercontent.com/12783198/156051577-1ca8e467-2916-45f3-a2d7-ca562e66aba8.png)

**Comment by Szewcson** [comment]
And when attaching Yubikey, sometime there is also an popup about some "slow keys" (?)
