### ISSUE TITLE
 [Initial setup configuration failed]

### ISSUE THREAD

**Issue by ice-t1** [QubesOS/qubes-issues#7319]
Hi I have problem and I can find solution. After installation when is the configuration phase I see message " initial configuration failed" and when qubes finished configuration I don't have any templates in my Qubes 4.1. Any sugestion?

**Comment by andrewdavidwong** [comment]
Please note that the issue tracker (`qubes-issues`) is not intended to serve as a help desk or tech support center. Instead, we've set up other [venues where you can ask for help and support, ask questions, and have discussions](https://www.qubes-os.org/support/). (By contrast, the issue tracker is more of a technical tool intended to support our developers in their work.) Thank you for your understanding!
