### ISSUE TITLE
Allow users to opt-in to installing packages signed by SHA-1 in dom0

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#7321]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### The problem you're addressing (if any)

Some packages that users are actually using, such as the OpenZFS RPMs, are signed using SHA-1.  By default, rpmcanon (rightly) rejects such signatures as using an insecure algorithm.  However, some users actually need to install such packages, and so [wind up bypassing signature verification entirely.](https://github.com/cfcs/qubes-storage-zfs/tree/7e240c7bc2ada378d8c0a7350d781aa11f14c4a3)

### The solution you'd like

Advanced users who need to install a package in dom0 that is signed with SHA-1 should be able to do so without turning off signature checks entirely.

### The value to a user, and who that user might be

See above.

**Comment by fepitre** [comment]
`sudo dnf install mypackage.rpm` or simply `rpm -i mypackage.rpm`. I assume you have checked signature in an AppVM if you know what you are doing. More better, simply rebuild the package yourself. I don't think it deserves particular workflow from official tool as it's only for a very limited use-case and we can do differently (as just suggested). If @marmarek see a particular objection to what I said, please reopen.
