### ISSUE TITLE
Remove grub in EFI booting environments or improve the installer

### ISSUE THREAD

**Issue by noseshimself** [QubesOS/qubes-issues#7328]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

Qubes R4.10

### The installer sucks. Completely.

Trying to create my own setup with multiple disks and using btrfs for some partitions requires me to use the appropriate option for preparation of the target disks.

1) If you want to reuse an existing partition inside an encrypted container the resulting configuration fails to boot.

2) If you make a mistake during disk partitioning and don't take it back but delete the partition and recreate it later the resulting configuration fails to boot.

3) If the EFI partition is not created as first or last partition in the chain of partition creation the installer complains that the EFI partition is missing although there is one.

4) If you create more than one EFI partition on multiple devices (or there is one left on a device you don't even want to include in your configuration because the device has not yet been removed) the installer complains about not having an EFI partition.

### Steps to reproduce

1) Install multiple storage devices in a computer.
1 a) Bonus if one or more devices contain partitions from a previous installation of an EFI-bootable system

2) Try creating a setup with individual (LUKS encrypted) btrfs partitions with sub-volumes (including mounting root from a sub-volume "root") and a few more non-standard btrfs partitions

3) Install

4) Reboot

### Expected behavior

A working system.

### Actual behavior

Grub fails to mount the root volume

-----

I don't see a reasonable improvement of using grub at all (and I'm only trying to reinstall because the R4.10 upgrade destroyed my bootable R4.0 environment...). Best would be throwing it out or use something like rEFInd.

(Instead of using the anti evil maid environment the Qubes developers like I'm using an alternative method involving booting from a USB medium containing the required files for booting AND the necessary key material for the built-in devices so the maid can do with my device whatever she likes so understanding GRUB so deeply that I can get that working will be a major pain.)

**Comment by brenthl88** [comment]
/dev/root fails to mount on mine so I couldn't install Qubes.

I have a lot of issues with QubesOS 4.1:

dracut initqueue timeout script

Emergency Shell

Warning: /dev/root does not exist
