### ISSUE TITLE
qubes-u2f-proxy not work on 4.1

### ISSUE THREAD

**Issue by Szewcson** [QubesOS/qubes-issues#7329]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
4.1

### Brief summary
qubes-u2f-proxy installed according to https://www.qubes-os.org/doc/u2f-proxy/ guide just not work (tried with github and google).
There is an older issue about gihub and Qubes 4.0, but there is stated that it works with google. For me it don't.

### Steps to reproduce

1. Install qubes-u2f-dom0 in dom0
2. Install qubes-u2f in debian-11-template
3. enable qubes-u2f-proxy for testing VM
4. restart debian-11-template 
5. run testing VM
6. insert yubikey 5 NFC
7. open Firefox ESR on testing VM and try to log in to U2F enrolled account on github or google

### Expected behavior

I should be able to log in

### Actual behavior

U2F key is not visible to firefox ESR browser

**Comment by Szewcson** [comment]
Ok, fix it but there should be a change in the guide or in some config. Since my sys-usb has not enabled qubes-u2f-proxy by default. Maybe it is connected with that that I add sys-usb after installation since I have internal usb keyboard, and have to add it with support for that.

**Comment by marmarek** [comment]
`qubes-u2f-proxy` is not necessary on sys-usb, only on the VM you use U2F in. Maybe you started testing VM before template shutdown, in which case it doesn't see the package yet?

**Comment by Szewcson** [comment]
In my comment I was talking about enabling proxy service in sys-usb. Yes I was even reboot qubes to be sure that everything was applaied.

**Comment by andrewdavidwong** [comment]
@Szewcson:
> Ok, fix it but there should be a change in the guide or in some config. Since my sys-usb has not enabled qubes-u2f-proxy by default.

@marmarek:
> Enabling `qubes-u2f-proxy` is not necessary on sys-usb, only on the VM you use U2F in.

@Szewcson:
> In my comment I was talking about enabling proxy service in sys-usb.

Let me see if I understand the exchange here:
1. @Szewcson thought that the problem was that `qubes-u2f-proxy` was not enabled in his `sys-usb` and that enabling it fixed the problem.
2. @marmarek pointed out that enabling `qubes-u2f-proxy` in `sys-usb` is *not* necessary (and therefore must not be the fix).
3. @Szewcson reaffirms that he was, indeed, talking about enabling `qubes-u2f-proxy` in `sys-usb` (which @marmarek has already said is unnecessary).

Conclusion: We still don't know what really caused or fixed the problem.

**Comment by Szewcson** [comment]
for test qube I use `qvm-service --enable testVM qubes-u2f-proxy' in dom0 as a step 3. Proxy start working when I use `systemctl enable qubes-u2fproxy@sys-usb.service' in the debian-11 template and add gubes-u2fproxy in sys-usb qube settings->services->add->custom. If I don't understand something I'm realy sorry but I use qubes since week and half so I just start to learning it.

**Comment by Szewcson** [comment]
Adding it in settings of the sys-usb in fact causing some strange loop and spam me with errors when I check is everything is working now. So I assume it was even not activated before. So thing that fix it for me seems to be only 'systemctl enable qubes-u2fproxy@sys-usb.service'. But still it not works perfect on github. I have to try to login few times before it finally works.

**Comment by Szewcson** [comment]
Ok, after login to all of the google accounts I figured out that is working, only it is more then 2 times slower then normal U2F operation.

**Comment by DemiMarie** [comment]
@4NobleTruths Can you post the exact error you are getting?

**Comment by 4NobleTruths** [comment]
![u2fError](https://user-images.githubusercontent.com/7483645/173947909-c95e4dc8-78e7-4a8b-8c0b-4675c464d709.png)

This is for another FIDO key, and Yubikey is same error but with Yubikey in it.
`qubes-u2f` has been installed and reinstalled in the templates for this and also in templates for permanent qubes where it doesn't work - fedora and debian 11.

It does continue to work in an old Debian 10 standalone qube and new Whonix 16 qube, without any enabling commands or services.

**Comment by 4NobleTruths** [comment]
Reinstalling `qubes-usb-proxy` fixed it for me.
Thank you for your attention.
