### ISSUE TITLE
Document `qubes.enable_insecure_pv_passthrough`

### ISSUE THREAD

**Issue by AlxHnr** [QubesOS/qubes-issues#7334]
### Qubes OS release (if applicable)

4.1

### Brief summary

The [docs imply](https://github.com/QubesOS/qubes-doc/blob/5b29e903d2eb11ba2b3cdbc9fe2d5783d99ca4e3/introduction/faq.md#why-is-vt-damd-viamd-iommu-important) that Qubes OS works without an IOMMU. Having this kernel parameter documented, would make fixing `sys-net` after installation on IOMMU-free systems less painful. One could argue that `sys-net` makes no sense on systems with no IOMMU. But it would still be very convenient to just fix the default `sys-net`, as this is the fastest way to a working system. Here are the steps for doing so:

1. Switch `sys-net` to `PV`
2. Add `qubes.enable_insecure_pv_passthrough` to `GRUB_CMDLINE_LINUX` in `/etc/default/grub`
3. Run `sudo grub2-mkconfig -o /boot/efi/EFI/qubes/grub.cfg`
4. Reboot

**Comment by andrewdavidwong** [comment]
In case you (or any others reading this) are not already aware, the documentation is a community effort, and everyone is welcome to contribute. (That's how things like this get updated!) So, if you'd like to get involved with the project, this is a great way to do it. You can read more about how to submit documentation changes here:

https://www.qubes-os.org/doc/how-to-edit-the-documentation/

You may also be interested in the documentation style guide:

https://www.qubes-os.org/doc/documentation-style-guide/

**Comment by kwinz** [comment]
Thanks for sharing @AlxHnr AlxHnr! This was extremely helpful in making me able to try out QubesOS in VMWare Player before commiting on installing it on bare metal.

VMWare Player on my computer was only able to emulate/nest AMD-V, but not IOMMU/VT-d/AMD-Vi.

Be aware that if you are not using UEFI, but legacy BIOS (which is the default on VMWare Player), then you have to use
`sudo grub2-mkconfig -o /boot/grub2/grub.cfg` instead!
