### ISSUE TITLE
Qube Manager should save "Show tool bar" and "Show menu bar" settings

### ISSUE THREAD

**Issue by quantumpacket** [QubesOS/qubes-issues#7338]
### Qubes OS release

4.1

### Brief summary

I have a lot of qubes and a 13" laptop screen, so I need all the screen space I can get. Since the menu bar and tool bar in the Qubes Manager is mostly redundant with the right-click context menus I choose to hide them using the  _"Show tool bar"_ and _"Show menu bar"_ settings. However, the settings do not persist.

### Steps to reproduce

1. Open a new Qubes Manager window.
2. Choose _"View"_ from menu and un-check _"Show tool bar"_ and _"Show menu bar"_ .
3. Close Qubes Manager window.
4. Open a new Qubes Manager window.

### Expected behavior

The  _"Show tool bar"_ and _"Show menu bar"_ settings are saved, and both bars are hidden when opening the new window.

### Actual behavior

The  _"Show tool bar"_ and _"Show menu bar"_ settings are not saved, and both bars are displayed again.

**Comment by quantumpacket** [comment]
I'm using `qubes-manager.noarch 4.1.26-1.fc32`, but this behavior is still present.

**Comment by marmarta** [comment]
Today I've learned (for at least the second time in my life, judging from git blame) that Qt for some weird reason stores True / False in QSettings as 'true' and 'false' strings. Pushing a fix.
