### ISSUE TITLE
bad DKIM signature in forum mails

### ISSUE THREAD

**Issue by ilka-schulz** [QubesOS/qubes-issues#7341]
I could not find a support email address, but your forum summary mails' DKIM signatures are broken: they are signed by `discoursehosting.com` but the From-Field's host is `forum.qubes-os.org`. Thus, DKIM verification fails.

**Comment by DemiMarie** [comment]
Good catch!  @marmarek looks like we need to update our DKIM records.

**Comment by andrewdavidwong** [comment]
@Deeplow, is this something you can fix?

**Comment by deeplow** [comment]
Looks like this is an issue on the hosting provider's end. I'll question them about this.

**Comment by deeplow** [comment]
@ilka-schulz I've followed up with the provider. According to their testing tools the DKIM signature is valid,
the Sender: is discoursehosting.com and the From is not relevant here. They say it's an uncommon but valid setup.

Here's a sample report: https://www.mail-tester.com/test-pot1of7e7

Do you have a tool that can reports otherwise. If so, do let me know, if not, it may well be a case that your email client simply does not account for the possibility of the `sender` being different than the `from`. In that case we can close this as it's not on issue on our end.

**Comment by DemiMarie** [comment]
> @ilka-schulz I've followed up with the provider. According to their testing tools the DKIM signature is valid, the Sender: is discoursehosting.com and the From is not relevant here. They say it's an uncommon but valid setup.

That does not surprise me, but I believe that the From header does matter here.  In any case we (ITL) can work around it by setting SPF, DKIM, and DMARC records for `forum.qubes-os.org`.

**Comment by deeplow** [comment]
> But why should I trust `discoursehosting.com` that it is actually qualified to sign messages of `forum.qubes-os.org`?

Not sure I follow. Discoursehosting.com are the hosting company for the forum. So they can do anything with the forum, if they wanted to.

**Comment by ilka-schulz** [comment]
> Discoursehosting.com are the hosting company for the forum.

I see. Of course, the DKIM verifier does not know that so it will continue to show a warning for each mail signed by `discoursehosting.com`'s public key. I found that Thunderbird's "DKIM Verifier" addon allows custom rules with custom SDIDs so it is probably the best to manually enter `discoursehosting.com` as the trusted SDID for `forum.qubes-os.org`.

**Comment by DemiMarie** [comment]
@deeplow can you add the missing DKIM and DMARC records?

**Comment by DemiMarie** [comment]
> I don't have controll of the DNS either in Qubes' side nor discoursehosting. But if it's on the discoursehosting side, I may ask them. Not sure if that will be something they can accommodate, though.

It would be on the Qubes OS side, as Qubes OS controls the `forum.qubes-os.org` DNS records.

**Comment by andrewdavidwong** [comment]
> > I don't have controll of the DNS either in Qubes' side nor discoursehosting. But if it's on the discoursehosting side, I may ask them. Not sure if that will be something they can accommodate, though.
> 
> 
> 
> It would be on the Qubes OS side, as Qubes OS controls the `forum.qubes-os.org` DNS records.

I think only @marmarek has access to that.

**Comment by deeplow** [comment]
The person at the hosting company also suggests us to configure DKIM to sign with forum.qubes-os.org domain, since we have the whole domain delegated. Then, DMARC could be enabled and it wouldn't be "uncommon" setup anymore.

**Comment by marmarek** [comment]
Forum emails are signed with key from forum domain thanks to Communiteq's offer, which allowed us to set appropriate DMARC record too.
