### ISSUE TITLE
Recent LVM security update borked running system

### ISSUE THREAD

**Issue by brendanhoar** [QubesOS/qubes-issues#7344]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
R4.0 current-testing

### Brief summary
lvm2 security update modified default global filter and lvm no longer recognized currently open devices and changed existing behavior.

### Steps to reproduce
Create a new thin volume in main pool.
Create plain cryptsetup volume on top of thin volume.
Create a new PV using this crypt volume.

### Expected behavior
PV created
I can then:
Create VG
Create new thinpool
Add to qvm-pool
Create VMs there, etc.

### Actual behavior
PV not created due to:
/dev/mapper/eph-xxxxx-luks not found (or ignored by filtering)

---

First taste of this was when a second pool was already created using this thinvol/crypt(plain)/PV/VG/thinvol stack and VMs were deployed there and functional *before* the update.

After the update all continued to function *until* shutdown or startup of any VMs in that pool and then the volumes were not found during startup prep and/or shutdown cleanup.

Had to very carefully shut everything down.

Restarting, I found the issues reported above.

Presumably I'll need to resolve by changing the default filtering to allow my use case. 

However, I'm concerned others using multiple LVM pools may run into similar issues...but it may be particular to the layering I'm doing here.

B

**Comment by DemiMarie** [comment]
@brendanhoar what is the UUID of the device in question?  Does using the path under `/dev/disk/by-id/dm-uuid-CRYPT-LUKS` work instead?

**Comment by brendanhoar** [comment]
Correction to the above: it's plain cryptsetup, not luks. I'll update my issue.

**Comment by DemiMarie** [comment]
Can you provide the sysfs attributes of the rejected device?

**Comment by brendanhoar** [comment]
In /dev/disk/by-id/

The volume starts with dd-uuid-CRYPT-PLAIN-

B

**Comment by DemiMarie** [comment]
Thanks @brendanhoar.  Can you provide the full UUID?

**Comment by brendanhoar** [comment]
Modifying the global filter (copy commented block, paste block, remove initial # from all lines) in lvm.conf to insert a line for PLAIN similar to the line for LUKS seems to resolve my issue without changing my script:

"a|^/dev/disk/by-id/dm-uuid-CRYPT-PLAIN-.*|",

B

**Comment by brendanhoar** [comment]
> Thanks @brendanhoar.  Can you provide the full UUID?

If I'm understanding correctly...

Before the fix, the uuid that was generated was:

/dev/disk/by-id/dm-uuid-CRYPT-PLAIN-eph-26539-luks

Everything specified after PLAIN- is specified by me in the script (constant-pid-constant). pid (process id) changes per script run.

B

**Comment by DemiMarie** [comment]
> > Thanks @brendanhoar.  Can you provide the full UUID?
> 
> If I'm understanding correctly...
> 
> The uuid that was generated was if the form:
> 
> /dev/disk/by-id/dm-uuid-CRYPT-PLAIN-eph-26539-luks
> 
> Everything specified after PLAIN- is specified by me in the script (constant-pid-constant). pid (process id) changes per script run.
> 
> B

Okay!  This should be sufficiently different from what Qubes OS would generate for a distinction to be made.  Patch coming.

**Comment by DemiMarie** [comment]
@marmarek: is it okay to allow crypt-plain devices that have a dm-uuid that does not match the ones we use?  That would mean that any upgrade that adds new potentially untrusted dm-crypt devices needs to add a dependency on a new lvm2 package, which is annoying.

**Comment by marmarek** [comment]
I think that's fine. Can we reserve some pattern for our use, like we have "vm-*" lvm volumes?

**Comment by DemiMarie** [comment]
> I think that's fine. Can we reserve some pattern for our use, like we have "vm-*" lvm volumes?

We currently reserve `vm-volatile-*` and `*@crypt` with our udev rules.  What about reserving `^vm-`, `^qubes-`, and `@crypt$`?  The last is odd but we have to reserve anything that could match an untrusted device on a currently running Qubes system, since a system upgrade won’t make existing devices go away.

**Comment by marmarek** [comment]
> What about reserving `^vm-`, `^qubes-`, and `@crypt$`?

Why `^qubes-` for untrusted devices? We have for example `qubes_dom0` which is rather close, and should rather not be excluded (ok, maybe here it doesn't matter, since that would be nested LVM, but I think you get the point).

How are you planning to do it? The lvm filter behavior isn't exactly friendly for deny-list approach:
```
    # When multiple path names exist for a block device, if any path name
    # matches an 'a' pattern before an 'r' pattern, then the device is
    # accepted.
```

**Comment by marmarek** [comment]
> To clarify, these are specifically paths under `/dev/mapper/` and they must also be dm-crypt devices.

Ok, that makes sense.

**Comment by DemiMarie** [comment]
> ```
> devices {
>    global_filter = [
>       "a|^/dev/disk/by-id/dm-uuid-CRYPT-LUKS-[12]-|",
>       "a|^/dev/nvme[0-9]+n[0-9]+(p[0-9]+)?$|",
>       "a|^/dev/sd[a-z]+[0-9]*$|",
>       "a|^/dev/md[0-9]+(p[0-9]+)?$|",
>       "r|^/dev/disk/by-id/dm-uuid-CRYPT-PLAIN-qubes|",
>       "r|^/dev/disk/by-id/dm-uuid-CRYPT-PLAIN-vm|",
>       "r|^/dev/disk/by-id/dm-uuid-CRYPT-PLAIN-.*@crypt$|",
>       "a|^/dev/disk/by-id/dm-uuid-CRYPT-PLAIN-|",
>       "r|.*|"
>    ]
> }
> ```
> 
> That said, I wonder if we are at the point where it is best to just implement a bespoke filter in C. This feels very, _very_ fragile.

Given how fragile this appears, is something like this okay @marmarek?

```
devices {
   global_filter = [
      "a|^/dev/disk/by-id/dm-uuid-CRYPT-LUKS-[12]-|",
      "a|^/dev/nvme[0-9]+n[0-9]+(p[0-9]+)?$|",
      "a|^/dev/sd[a-z]+[0-9]*$|",
      "a|^/dev/md[0-9]+(p[0-9]+)?$|",
      "r|^/dev/disk/by-id/dm-uuid-CRYPT-PLAIN-qubes|",
      "r|^/dev/disk/by-id/dm-uuid-CRYPT-PLAIN-vm|",
      "r|^/dev/disk/by-id/dm-uuid-CRYPT-PLAIN-.*@crypt$|",
      "a|^/dev/disk/by-id/dm-uuid-CRYPT-PLAIN-trusted-crypt-|",
      "r|.*|"
   ]
}
```

**Comment by marmarek** [comment]
> "r|^/dev/disk/by-id/dm-uuid-CRYPT-PLAIN-qubes|",
>       "r|^/dev/disk/by-id/dm-uuid-CRYPT-PLAIN-vm|",

I think those two lines are redundant (those cannot not match `dm-uuid-CRYPT-PLAIN-trusted-crypt-`), but it doesn't hurt to include them anyway. I think this is ok, then we need to document somewhere the `trusted-crypt-` prefix.
