### ISSUE TITLE
[BOUNTYSOURCE] Your Funds may be at Risk

### ISSUE THREAD

**Issue by abebeos** [QubesOS/qubes-issues#7349]
## @ Bountysource Contributors

> It's great to see that [the Bountysource bounty](https://www.bountysource.com/issues/31778112-add-support-for-gnome-in-dom0-gui-domain) has reached $6,400. Hopefully we can see some more progress towards this soon!

source: https://github.com/QubesOS/qubes-issues/issues/1806#issuecomment-1000750271

-

Please be aware that Bountysource has problems, your funds may be at risk:

https://github.com/abebeos/bountysource

 
-----
@andrewdavidwong , please, get serious and try to patronize some kids with pseudo-analytic stuff like this: https://github.com/QubesOS/qubes-issues/issues/1806#issuecomment-1066165331. You're an analytical nothing without the power to block.

**Comment by andrewdavidwong** [comment]
Based on our [issue tracking guidelines](https://www.qubes-os.org/doc/issue-tracking/), this does not appear to be suitable for `qubes-issues`. We ask that you please post this on the [Qubes Forum or `qubes-users` mailing list](https://www.qubes-os.org/support/) instead. If, after reading our [issue tracking guidelines](https://www.qubes-os.org/doc/issue-tracking/), you believe we are mistaken, please leave a brief comment explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.
