### ISSUE TITLE
Laggy and pixelated disk decryption passphrase entry screen

### ISSUE THREAD

**Issue by vblimits** [QubesOS/qubes-issues#7350]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
4.0.4
4.1.0

running on Librem 14 with 2TB samsung NVMe 980 PRO (new)
32Gigs 3200 Ram (new)
### Brief summary
during boot when i get to enter my disk encryption phrase the mouse pointer, and text (balls as i type) are pixelated and entire is vary leggie (about 1 sec per char) it looks like a screen refresh issue as i can type at normal speed just takes a long time to catch up.

### Steps to reproduce
fresh install of 4.0.4 or 4.1.0 (3 diffrent times)

### Expected behavior
Smoth typing no screen artifact's

### Actual behavior
slow on screen update of type char's and screen artifacts on both the mouse cursor and "*" in the text box while typing,

**Comment by andrewdavidwong** [comment]
@vblimits, could you please fill out the issue description? We'll need a bit more to go on than just the title.

**Comment by vblimits** [comment]
> @vblimits, could you please fill out the issue description? We'll need a bit more to go on than just the title.

Sorry i am not sure what happend there, if you need a "screen" shot let me know ill take a picture with my phone

**Comment by fepitre** [comment]
@vblimits please give us your hardware description (especially video card), kernel version installed, Qubes release etc. I'm also encountering similar issue on a laptop since recent kernels

**Comment by vblimits** [comment]
brand new computer fresh install by me from the Qubes OS website ISO
Brand: Librem
Storage: Samsung 2Tb NVME 980 Pro
CPU: 4.70GHz Core i7 10710U Comet Lake
Memory: GSkill 32GB DDR4 3200Mhz
Operating System: Qubes OS 4.1.0 Kernel 5.10.90-1.fc32.qubes.x86_64
Ports: Card reader, USB 3.1 type-A, USB 3.1 type-C, HDMI 2, 3.5mm TRRS,
Camera: 1280x720px (0.9MP), 10FPS
Display (Size, Resolution): 14-inch matte IPS
GPU: Intel UHD Graphics 620

**Comment by fepitre** [comment]
@vblimits can you try to install `kernel-latest` in dom0? You may need to enable `current-testing` repository too (you can enable it through the Qubes Global Settings in menu, select "Testing updates" in `dom0 updates`). Then in a dom0 console:

```
$ sudo qubes-dom0-update kernel-latest
```

Reboot and you will start on kernel latest on the first grub entry. Check if it changes something.

**Comment by DemiMarie** [comment]
I have the same problem on my system (Lenovo P51)

**Comment by vblimits** [comment]
@fepitre no change new Kernel is 5.15.14-1.fc32.qubes.x86_64

**Comment by logoerthiner1** [comment]
I can reproduce this bug. CPU is i5-1135G7 and graphics is "Intel Corporation TigerLake-LP GT2 [Iris Xe Graphics]"

Also it seems that since I uses kernel-latest (for a different issue) I have not suffered from a similar issue; however when I was using the default kernel 5.10 in dom0, in the dom0 GUI the cursor goes pixelated when it is transiting states. (Not sure whether the issue is in kernel version)

**Comment by vblimits** [comment]
i can confirm i get a pixelated cursor at the desktop every now and then and when transiting .

**Comment by EncryptedGiraffe** [comment]
I also experience this, both on my old system and my current one. R4.1 kernel-latest, from current-testing.

**Comment by DemiMarie** [comment]
> Maybe Qubes OS should disable the fancy graphical splash screen by default? Just showing the TTY is fine.

I would be fine with this, but only if @ninavizz (user experience lead for Qubes OS) approves it.

**Comment by vblimits** [comment]
> Maybe Qubes OS should disable the fancy graphical splash screen by default? Just showing the TTY is fine.

this would only solve the 1 issue, not the seemingly related problem of the mouse pointer after boot

**Comment by crat0z** [comment]
Same thing on a 10850K, so this isn't a laptop specific issue.

**Comment by fepitre** [comment]
I'm rejecting the idea of disabling plymouth. This is happening to very few users because of missing hardware support. Having "fancy" output makes normal user or Linux users coming from other distro like Fedora, openSUSE, Ubuntu etc. not having the first impression of: "argh it's ugly".

**Comment by 51lieal** [comment]
This bug actually has been happened to me since 4.0, using discrete gpu only mode, fix the problem (no driver install or whatsoever needed)

I think it's intel gpu related.

**Comment by fepitre** [comment]
Unfortunately, 5.16.18 does not solve the problem :/

**Comment by arkenoi** [comment]
Had the same problem on NUC10i7

**Comment by ido** [comment]
Past the disk password screen, when you get into Xorg, add an Intel device section to your Xorg config, and set i915.force_probe=* (or set it to =XXXX where XXXX is the ID you get from the relevant dmesg output) in your kernel cmdline in the grub config. These two configuration changes resolved the pixelation, video lag, and slowness for me and got hardware rendering working with igfx.

Plymouth, unfortunately, has its own framebuffer/video config. Haven't bothered to fix that locally yet.

Above should work for kernel-latest and possibly even 5.15+ in Qubes R4.1.1

This is a configuration issue with Qubes and not an Intel graphics issue as far as I can see.

**Comment by lubellier** [comment]
I no more see this problem, I'm using stable dom0 (kernel 5.15.81, xen 4.14.5-15) with Intel NUC10 ([HCL report](https://github.com/QubesOS/qubes-hcl/blob/main/Intel-NUC10i7FNK-20220302-200651.yml)).
I don't know when it has been solved for me, I will say between 2 days and 1 month...
Other users: could you check for you?

**Comment by marmarek** [comment]
The root cause should be "fixed" by https://github.com/QubesOS/updates-status/issues/3353

**Comment by vblimits** [comment]
i just updated DOM0 my problem is also fixed :) thank you

**Comment by arkenoi** [comment]
Cannot check since my NUC10 died, I upgraded to NUC11 and the problem was not present there.
