### ISSUE TITLE
'/usr/bin/widget-wrapper qui-clipboard' fails to release file descriptors for /run/qubes/appviewer.lock -- fd starvation

### ISSUE THREAD

**Issue by auroraanon38** [QubesOS/qubes-issues#7352]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

4.1

### Brief summary

After running Qubes for a while and using the clipboard feature to transfer text between qubes, notification for clipboard copies suddenly stop working as does the clipboard transfer.

### Steps to reproduce

1. Copy and paste the clipboard until the file descriptor limit for the system is reached (default ulimit report appears to be 1024).
2. Observe failure of further notifications and copying between qubes.
3. Observe glitched out widget menu when clicking on it in your task/status bar.
4. Observe locks for `/run/qubes/appviewer.lock` via `lsof`

### Expected behavior

Qube clipboard functions keep continuing as necessary, without ceasing to work by opening hundreds of file descriptors for `/run/qubes/appviewer.lock` and not releasing them.

### Actual behavior

Qube clipboard functions fail once the maximum number of open file descriptors for the process is reached, as none of the descriptors are ever closed.

### Workaround

1. Kill the process for `/usr/bin/widget-wrapper qui-clipboard` in dom0
2. Run `/usr/bin/widget-wrapper qui-clipboard &` in dom0

### Logs

    dom0 widget-wrapper[4018]: Exception in callback AsyncioNotifier.handle_read()
    dom0 widget-wrapper[4018]: handle: <GLibHandle AsyncioNotifier.handle_read()>
    dom0 widget-wrapper[4018]: Traceback (most recent call last):
    dom0 widget-wrapper[4018]:   File "/usr/lib64/python3.8/asyncio/events.py", line 81, in _run
    dom0 widget-wrapper[4018]:   File "/usr/lib/python3.8/site-packages/pyinotify.py", line 1597, in handle_read
    dom0 widget-wrapper[4018]:   File "/usr/lib/python3.8/site-packages/pyinotify.py", line 1275, in process_events
    dom0 widget-wrapper[4018]:   File "/usr/lib/python3.8/site-packages/pyinotify.py", line 910, in __call__
    dom0 widget-wrapper[4018]:   File "/usr/lib/python3.8/site-packages/pyinotify.py", line 630, in __call__
    dom0 widget-wrapper[4018]:   File "/usr/lib/python3.8/site-packages/qui/clipboard.py", line 98, in process_IN_CLOSE_WRITE
    dom0 widget-wrapper[4018]:   File "/usr/lib64/python3.8/contextlib.py", line 113, in __enter__
    dom0 widget-wrapper[4018]:   File "/usr/lib/python3.8/site-packages/qui/clipboard.py", line 57, in appviewer_lock
    dom0 widget-wrapper[4018]: OSError: [Errno 24] Too many open files: '/var/run/qubes/appviewer.lock'
    dom0 qrexec-policy-daemon[1914]: warning: !compat-4.0 directive in file /etc/qubes/policy.d/35-compat.policy line 16 is transitional and will be deprecated
    dom0 widget-wrapper[4018]: Exception in callback AsyncioNotifier.handle_read()
    dom0 widget-wrapper[4018]: handle: <GLibHandle AsyncioNotifier.handle_read()>
    dom0 widget-wrapper[4018]: Traceback (most recent call last):
    dom0 widget-wrapper[4018]:   File "/usr/lib64/python3.8/asyncio/events.py", line 81, in _run
    dom0 widget-wrapper[4018]:   File "/usr/lib/python3.8/site-packages/pyinotify.py", line 1597, in handle_read
    dom0 widget-wrapper[4018]:   File "/usr/lib/python3.8/site-packages/pyinotify.py", line 1275, in process_events
    dom0 widget-wrapper[4018]:   File "/usr/lib/python3.8/site-packages/pyinotify.py", line 910, in __call__
    dom0 widget-wrapper[4018]:   File "/usr/lib/python3.8/site-packages/pyinotify.py", line 630, in __call__
    dom0 widget-wrapper[4018]:   File "/usr/lib/python3.8/site-packages/qui/clipboard.py", line 98, in process_IN_CLOSE_WRITE
    dom0 widget-wrapper[4018]:   File "/usr/lib64/python3.8/contextlib.py", line 113, in __enter__
    dom0 widget-wrapper[4018]:   File "/usr/lib/python3.8/site-packages/qui/clipboard.py", line 57, in appviewer_lock
    dom0 widget-wrapper[4018]: OSError: [Errno 24] Too many open files: '/var/run/qubes/appviewer.lock'
    dom0 systemd[3886]: Stopping XFCE notifications service...
    dom0 systemd[3886]: xfce4-notifyd.service: Succeeded.
    dom0 systemd[3886]: Stopped XFCE notifications service.
    dom0 systemd[3886]: xfce4-notifyd.service: Consumed 15.725s CPU time.
    dom0 systemd[3886]: Starting XFCE notifications service...
    dom0 systemd[3886]: Started XFCE notifications service.
    dom0 widget-wrapper[4018]: Exception in callback AsyncioNotifier.handle_read()
    dom0 widget-wrapper[4018]: handle: <GLibHandle AsyncioNotifier.handle_read()>
    dom0 widget-wrapper[4018]: Traceback (most recent call last):
    dom0 widget-wrapper[4018]:   File "/usr/lib64/python3.8/asyncio/events.py", line 81, in _run
    dom0 widget-wrapper[4018]:   File "/usr/lib/python3.8/site-packages/pyinotify.py", line 1597, in handle_read
    dom0 widget-wrapper[4018]:   File "/usr/lib/python3.8/site-packages/pyinotify.py", line 1275, in process_events
    dom0 widget-wrapper[4018]:   File "/usr/lib/python3.8/site-packages/pyinotify.py", line 910, in __call__
    dom0 widget-wrapper[4018]:   File "/usr/lib/python3.8/site-packages/pyinotify.py", line 630, in __call__
    dom0 widget-wrapper[4018]:   File "/usr/lib/python3.8/site-packages/qui/clipboard.py", line 98, in process_IN_CLOSE_WRITE
    dom0 widget-wrapper[4018]:   File "/usr/lib64/python3.8/contextlib.py", line 113, in __enter__
    dom0 widget-wrapper[4018]:   File "/usr/lib/python3.8/site-packages/qui/clipboard.py", line 57, in appviewer_lock
    dom0 widget-wrapper[4018]: OSError: [Errno 24] Too many open files: '/var/run/qubes/appviewer.lock'

**Comment by auroraanon38** [comment]
I haven't tried it yet, but I think putting [this line](https://github.com/QubesOS/qubes-desktop-linux-manager/blob/1728d2e0abf725d1aebedea8ea9ba272054996bf/qui/clipboard.py#L255) in a `finally` block would fix it.

**Comment by noskb** [comment]
This is more likely to occur when uptime is long and the inter-qube clipboard is used heavily. 

But If you want to reproduce it in a short time, copy something to the clipboard in the VM and then press and hold Ctrl+Shift+C for about 60 seconds.
