### ISSUE TITLE
Upgrade glibc in dom0

### ISSUE THREAD

**Issue by locriacyber** [QubesOS/qubes-issues#7353]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### The problem you're addressing (if any)
It's impossible to build any executable from any newer Linux distro for dom0 since it's still using Fedora 32 with glibc 2.31.

### The solution you'd like
I don't know any solution. I tried to build 2.31 headers in https://github.com/wheybags/glibc_version_header, but the project is a mess. glibc is a mess too.

Maybe I can get `ccache` to run in another VM with Fedora 32, or use docker to compile the project.

### The value to a user, and who that user might be
Package developers who don't wont to compile on Fedora 32.

**Comment by marmarek** [comment]
You should use the target environment for building (f32 in this case), not only because of glibc version, but other libraries too. [Qubes builder](https://www.qubes-os.org/doc/qubes-builder/) can help you with building packages in appropriate chroot.
