### ISSUE TITLE
Having a USB Security dongle connected to USB  with installing Qubes 4.1 fails to create disposable sys-usb without error

### ISSUE THREAD

**Issue by tlaurion** [QubesOS/qubes-issues#7355]
### Qubes OS release
4.1

### Brief summary
Having second stage install (on reboot) configure sys-usb in disposable mode fails to create it (without error) when a USB Security dongle is connected.

### Steps to reproduce

Have a Nitrokey Pro (I suspect any USB device other then a USB drive) connected on second stage boot prior of configuring the system.

### Expected behavior
Be able to configure the system with a USB Security dongle/token connected.

### Actual behavior
Continues without error but there is no disposable sys-usb existing on the installed system.
Reinstalling without a USB Security dongle connected succeeds to create disposable sys-usb.

**Comment by DemiMarie** [comment]
At least YubiKeys appear as USB keyboards.

**Comment by tlaurion** [comment]
@DemiMarie that may be the cause. Nitrokey Pro is also a HID device.
Why no error message?

**Comment by DemiMarie** [comment]
@tlaurion because Qubes OS is supported on hardware that only has a USB keyboard, and for which sys-usb would break the boot process.

**Comment by tlaurion** [comment]
Ok. So would it make sense to document this in Qubes installation @DemiMarie ?

Feels dumb that second stage would fail to deploy sys-usb because user behind computer didn't remove his security token, no?

Either documentation or code needs to be fixed with at least a warning. Otherwise other issues will be opened for sure. Which one we choose?

@marmarek @DemiMarie

**Comment by marmarek** [comment]
It is communicated during initial setup. https://openqa.qubes-os.org/tests/36517#step/firstboot/5 - see checkbox for USB qube, it reads "USB qube configuration disabled - you are using USB keyboard or USB disk".

**Comment by DemiMarie** [comment]
> It is communicated during initial setup. https://openqa.qubes-os.org/tests/36517#step/firstboot/5 - see checkbox for USB qube, it reads "USB qube configuration disabled - you are using USB keyboard or USB disk".

Can we have an option to override this?

**Comment by marmarek** [comment]
If system is booted from USB (the check looks specifically for rootfs on USB disk), not really - that guarantee a startup fail. But for USB keyboard, I think we can.

**Comment by tlaurion** [comment]
@marmarek https://osresearch.net/InstallingOS/#installing-qubes-41

I do get this screen:
https://user-images.githubusercontent.com/827570/156628021-d3ec34af-e620-48b8-aa39-45d84c968769.jpeg

**Comment by marmarek** [comment]
Okay, this is weird. The screen I shown you before was specifically with Nitrokey Pro plugged in. Can you confirm specific install ISO version?
Can you send me `journalctl` output after completing such firstboot step (that failed to create sys-usb, even though it was selected)?

**Comment by tlaurion** [comment]
I was wrong, really sorry for the noise. With (HID) USB Security dongle connected:
![signal-2022-03-17-082833](https://user-images.githubusercontent.com/827570/158814923-219d55b5-1240-4e54-b869-0ce40e2d7402.jpeg)

Without:
![signal-2022-03-17-083050](https://user-images.githubusercontent.com/827570/158814911-f60fa5a2-7fc9-4533-9fc6-1f431055f7e2.jpeg)

So I guess its documentation route.

**Comment by tlaurion** [comment]
Updated https://osresearch.net/InstallingOS/#installing-qubes-41
