### ISSUE TITLE
panel is gone: "failed to show the preferences dialog" 

### ISSUE THREAD

**Issue by deeplow** [QubesOS/qubes-issues#7358]
I haven't experienced it myself. Opening a bug report for this because people have been talking about this in the forum, but nobody stood up to creating it here on GitHub [after some insistence on my part](https://forum.qubes-os.org/t/xfce4-panel-doesnt-appear-after-booting/10089/6):
- https://forum.qubes-os.org/t/xfce4-panel-doesnt-appear-after-booting/10089/2
- https://forum.qubes-os.org/t/panel-is-gone/9242/1
- https://old.reddit.com/r/Qubes/comments/snmb10/panel_is_gone/
- https://forum.qubes-os.org/t/xfce-desktop-disappears-becomes-grey/2606/11

### Qubes OS release
4.1

### Brief summary

XFCE panel disappears on boot.

### Steps to reproduce

? No idea

### Expected behavior

XFCE interface shows like like normal

### Actual behavior

Quoting from [the forum](https://forum.qubes-os.org/t/panel-is-gone/9242/1):
> My panel in qubes4.1 is somehow gone… I was just browsing in the internet and then all at once my panel was gone. I rebooted the device but still it is missing.
>
> I found the xfce4-panel.xml file, so i guess it should be possible to “restart” it again but i don’t know how. I don’t know how to “start” the panel and if i have to make changes at the xml file i don’t know how to do that either.
> 
> When i right click and go to “Applications” → “System Tools” and then click on “Panel” i get this error message:
> 
> ![291106ffea79f0a1e15b1196ff8f05f59ae0c0c7](https://user-images.githubusercontent.com/47065258/159051059-a2126b9d-0b9d-4583-9853-9e4758ca40ad.jpeg)

### Solutions

[Solution 1](https://forum.qubes-os.org/t/xfce4-panel-doesnt-appear-after-booting/10089/7):
> This was the solution for me. To clarify:
> 
> Go to System Tools > Session and Startup > Application Autostart > Add+
> 
> Name: Start taskbar
> Command: xfce4-panel
> Trigger: on login
> 
> Reboot the machine and taskbar appears automatically again with all the icons including network icon which did not appear when I manually started the taskbar later on.

[Solution 2](https://forum.qubes-os.org/t/xfce-desktop-disappears-becomes-grey/2606/11)
> 1. running `xfwm4 --replace`
> 2. running `xfce4-panel`

**Comment by DemiMarie** [comment]
This blocks a change that I would like to make at some point in the future, which would cause the X server to exit in this case.
