### ISSUE TITLE
Qubes Manager and domains widget very slow to start when several VMs are starting

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#7361]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
R4.1

### Brief summary

When several VMs are being started (in my case, via qrexec), Qubes Manager and the domains widget are very slow to start.  It appears that Admin API calls are being slowed down, perhaps due to lock contention of some sort.

### Steps to reproduce

Have `.desktop` files in `~/.config/autostart` that start both Qubes Manager and several VMs

### Expected behavior

Qubes Managerstarts quickly

### Actual behavior

Qubes Manager starts very slowly

**Comment by DemiMarie** [comment]
I suspect (but cannot confirm) that qubesd’s event loop is being blocked due to blocking libvirt calls.  @marmarek is there a way to use asynchronous libvirt calls instead?

**Comment by marmarek** [comment]
> Have `.desktop` files in `~/.config/autostart` that start both Qubes Manager and several VMs

Consider using `autostart` property instead.

**Comment by DemiMarie** [comment]
> > Have `.desktop` files in `~/.config/autostart` that start both Qubes Manager and several VMs
> 
> Consider using `autostart` property instead.

Indeed that is a workaround, but I still think this problem should be tracked down and fixed.
