### ISSUE TITLE
UEFI Troubleshooting documentation does not reflect 4.1

### ISSUE THREAD

**Issue by littlebenlittle** [QubesOS/qubes-issues#7363]
### Qubes OS release

[Docs](https://www.qubes-os.org/doc/uefi-troubleshooting/) appear to match 4.0 but contradict 4.1

### Brief summary

Fresh installation media does not contain boot records described in the documentation.

### Steps to reproduce

Download and flash new installation media and then run `find . | grep xen\.efi` on the mounted drive

### Expected behavior

Files should exist

### Actual behavior

but they don't

**Comment by andrewdavidwong** [comment]
Thanks for the report! In case you (or any others reading this) are not already aware, the documentation is a community effort, and everyone is welcome to contribute. (That's usually how things like this get updated!) So, if you'd like to get involved with the project, this is a great way to do it. You can read more about how to submit documentation changes here:

https://www.qubes-os.org/doc/how-to-edit-the-documentation/

You may also be interested in the documentation style guide:

https://www.qubes-os.org/doc/documentation-style-guide/
