### ISSUE TITLE
Minor problems with Qubes Windows Tools

### ISSUE THREAD

**Issue by GWeck** [QubesOS/qubes-issues#7364]
### Qubes OS release
Qubes R4.1.0 with Qubes Windows Tools 4.1.67.1

### Brief summary
Some problems with using current Windows installations with QWT:

1. Audio for Windows 7 does not work; for Windows 10 and 11 it works but sounds somewhat scratchy.
2. While USB-Sticks may be attached and detached, other devices like SATA or NVME disks must be attached persistently before starting a Windows VM; otherwise, it will crash on accessing these disks.
3. For Windows 7 in non-seamless mode, screen resolution cannot be reasonably set. 

### Steps to reproduce

1. Try to play some sound (system sound, or, e.g. an MP3) in a Windows qube.
2. Attach another disk present in the system to a Windows qube via the task bar widget. The device will be visible as an additional disk in the Windows Explorer.
3. Screen resolution for Windows 7 in non-seamless mode is fixed to 1920 x 1055 (on my system, having a 1920 x 1200 display). 

### Expected behavior

1. Sound should be played as in Linux qubes.
2. Disk access should be possible like for USB disks.
3. Other screen resolutions should be offered and selectable, like for Windows 10 and 11.

### Actual behavior

1. Windows 7 does not have any sound device. For Windows 10 or 11, the system sounds like some very old vinyl disk.
2. Klicking on the newly displayed disk crashes the Windows qube with a fatal error message (not always the same).
3. The only other value for screen resolution offered is 800 x 600, but trying to change this just freezes the screen for several seconds, without changing the resolution.  Seamless mode works as expected.

**Comment by brendanhoar** [comment]
> This feature requires Xen PV Disk drivers installed and the last time I tried to reproduce the problem, I failed to achieve a crash over several dozen connections. So it might be Windows environment depends.

On a Win7 VM, I've been using the most recent 8.x series PV disk driver to hot add block devices for a couple years now w/o PV-related crashes.

B

**Comment by andrewdavidwong** [comment]
Generally speaking, [every issue should be about a single, actionable thing](https://www.qubes-os.org/doc/issue-tracking/#every-issue-must-be-about-a-single-actionable-thing). You might want to consider breaking this up into multiple issues.

**Comment by GWeck** [comment]
I grouped these three issues together because they probably come from the same cause: the (Xen) drivers bundled with the new QWT version. I hope so, at least.

**Comment by GWeck** [comment]
@jevank 


> QEMU emulates an Intel audio controller, make sure you have these device drivers if they didn't bundle w/ Windows

Windows 7 is here somewhat inconsistent: The device manager shows a "high definition audio device", saying that it works perfectly. On the other hand, trying to configure sound, Windows tells that the Windows audio service was not started. Trying to start this service then tells that there are no audio devices. ???

> Some noise may be the result of CPU load (youtube for example with video and network), but in the latest version of stubdomain I see significant improvements in this aspect in my environment. Perhaps some pulseaudio settings might help

My CPU load is quite small (typically about 10 %), so that should not be a problem. With pulseaudio, I did not find any reasonable parameter to set. Changing memory from 4 to 6 GB has no effect. Setting `qvm-features audio-model` from `ich6` to `ìch9`seems to improve the sound slightly, but not really.

> You need to manually change the size of the window borders, but not the properties of the virtual device

The window size and position can be changed manually, but then it immediately jumps back to the size of 1920 x 1055 and top left corner. If the Qubes ITL video display driver (version 1.0.0.0) is uninstalled by unselecting Qubes GUI Agent in the QWT installation dialog, the VM window behaves normally, so I suppose that it is a problem of this driver.

@brendanhoar I am using the Xen drivers version 8.2.2, bundled with QWT 4.1.67.1. So far, I did not have the nerves to try the version 9.0 drivers, which, in earlier attempts, crashed Windows 7. USB block devices work as expected; it is just SATA and NVME block devices that crash the qube.

**Comment by jevank** [comment]
> Windows 7 is here somewhat inconsistent: The device manager shows a "high definition audio device", saying that it works perfectly. On the other hand, trying to configure sound, Windows tells that the Windows audio service was not started. Trying to start this service then tells that there are no audio devices. ???

Windows audio service should starts fine even w/o audio devices, but it has dependencies and perhaps some of this services are disabled. Could you check it? Windows Audio Endpoint Builder service? 

>  My CPU load is quite small (typically about 10 %), so that should not be a problem. With pulseaudio, I did not find any reasonable parameter to set. Changing memory from 4 to 6 GB has no effect. Setting qvm-features audio-model from ich6 to ìch9seems to improve the sound slightly, but not really.

Windows integration is quite different from that of Linux. In Windows case the real interaction via qrexec/vchan with dom0 happens in stubdomain and Windows uses QEMU's audio/USB emulation. This approach has some advantages, especially there is no need to install guest tools (QWT) to make everything work.  However it has some disadvantages, in particular the sound quality or lags in USB communication due to possible low prioritization of such devices inside QEMU.

> The window size and position can be changed manually, but then it immediately jumps back to the size of 1920 x 1055 and top left corner. 

Could you try Alt+F8 keys then mouse movement to change window size?

**Comment by GWeck** [comment]
> Windows audio service should starts fine even w/o audio devices, but it has dependencies and perhaps some of this services are disabled. Could you check it? Windows Audio Endpoint Builder service?

Windows Audio Endpoint Builder service was disabled. When set to automatic start, Windows audio service, which already was set to automatic start, could be started and then started the other service. Now audio works for Windows 7, and even is not scratchy!

> Could you try Alt+F8 keys then mouse movement to change window size?

This does the trick: Window size can be changed and is reported as the upper size value. If seamless mode is then enabled and then disabled again, the previous, faulty behaviour is restored, but Alt+F8 gets you to the correct behaviour again.

Thanks a lot!!! Now Windows integration in Qubes is so good that I don't know anymore why one should use a native Windows system without Qubes! Congratulations!!!

**Comment by DemiMarie** [comment]
> > Windows audio service should starts fine even w/o audio devices, but it has dependencies and perhaps some of this services are disabled. Could you check it? Windows Audio Endpoint Builder service?
> 
> Windows Audio Endpoint Builder service was disabled. When set to automatic start, Windows audio service, which already was set to automatic start, could be started and then started the other service.

This is something the QWT installer should be able to handle.

> Now audio works for Windows 7, and even is not scratchy!

Is the audio still scratchy for later Windows versions?

**Comment by GWeck** [comment]
@DemiMarie No change - still scratchy for W10 and W11; just W7 is o.k. (in this and many other respects :-) )

**Comment by GWeck** [comment]
If, prior to QWT installation, the drive letter for the private volume on Windows 7 templates is changed from `D:` to `Q:`, the `Move User Profiles` works for Windows 7, too.

**Comment by DemiMarie** [comment]
> @DemiMarie No change - still scratchy for W10 and W11; just W7 is o.k. (in this and many other respects :-) )

What are the other ones?

**Comment by GWeck** [comment]
In my opinion, W7 was the last usable version of Windows. W10 and 11 are just cumbersome to use, slow, and ergonomically terrible - just apart from their sending telemetry data to Microsoft, which is unacceptable from a privacy standpoint and, in Europe, illegal according to GDPR.

**Comment by GWeck** [comment]
With the exception of seamless mode for Windows 10 and 11 - which is surely a bigger task - all these problems have now been solved. So I am closing this issue.
