### ISSUE TITLE
adding custom kernel to qubes ISO installer

### ISSUE THREAD

**Issue by eric-blabla** [QubesOS/qubes-issues#7365]
I would like to add a custom kernel to the installer (and not after install). I downloaded, verified and unpacked the iso. I can add the kernels into /extrakernels directory (I put the vmlinuz & initramfs in here), and cloned a grub.cfg entry. So far so good. I need help to repack it correctly.

mkisofs has 3 hunderd options, roughly and I don't get it t run. The indications for ubuntu given here https://gist.github.com/AkdM/2cd3766236582ed0263920d42c359e0f  

DO WORK, I am stupid. How can I ersed this post?

**Comment by DemiMarie** [comment]
> DO WORK, I am stupid. How can I ersed this post?

Don’t worry, everyone makes mistakes.
