### ISSUE TITLE
Add VM/Qube type when trying to backup Qubes in backup menu

### ISSUE THREAD

**Issue by TNTBOMBOM** [QubesOS/qubes-issues#7366]
### The problem you're addressing (if any)

Backup menu not showing type name of the VM is it a template or appvm or..etc, when you have many VMs its not easy to recognize them by memory and going back to check what are they not pleasant choice.

### The solution you'd like

Add VM/Qube type beside VM/Qube name

### The value to a user, and who that user might be

Ease/Surety to know what hes backing up, Because if user doesnt want to backup any TemplateVM or Standalone but only AppVMs thats impossible he know that unless he memorize them from Qube Manager menu/list.

### Image

E.g: Fedora-35 is it standalone or template or appvm or HVM..? (Its StandaloneVM, But Fedora-34 is a TemplateVM = Looks exactly the same)

![Improvetemplatenames](https://user-images.githubusercontent.com/11895339/159372710-f267c3f4-dff6-46bb-9d19-8074b0a0b000.png)

**Comment by DemiMarie** [comment]
Assigning @marmarta as is usual for this kind of stuff.
