### ISSUE TITLE
Cannot play streams or videos in qubes connected to GUI domain (sys-gui)

### ISSUE THREAD

**Issue by ZYousef** [QubesOS/qubes-issues#7367]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
**Qubes release 4.1.0**

### Brief summary

GUI-domain seems to be unable to render videos with audio streams, PulseAudio setup seems to be incomplete, (no autostart & when started manually says no cards available). Looking to ~/.xsession-errors says `sys-gui AUDIO connected to None. Skipping`
. I tried playing muted videos and it works fine, I suspect that the issue is coming from PulseAudio

### Steps to reproduce

```
sudo qubesctl top.enable qvm.sys-gui
sudo qubesctl top.enable qvm.sys-gui pillar=True
sudo qubesctl --all state.highstate
```
((wait for a long time)

`sudo qubesctl top.disable qvm.sys-gui
`
set default gui:
`qubes-prefs default-guivm sys-gui
`

### Expected behavior

Logging to GUI-Domain works fine.

### Actual behavior

GUI-Domain works reasonably well regardless of some cluttering, however, it cannot render videos or streams with audio.
_((videos not rendered at all unless it has no audio))_

**Comment by DemiMarie** [comment]
On the one hand this is definitely a bug, but on the other hand I am curious why you are trying to play videos in the GUI domain.  The GUI domain is highly privileged (via qrexec policy) and videos are generally considered untrusted.

**Comment by ZYousef** [comment]
I am sorry I wasn't clear in my OP. I meant to say that the video is played within a qube (appVM) on the sys-gui environment. 
When I log into the sys-gui and run say youtube on any qube, the video get stuck and doesn't play. The audio icon on the top right of sys-gui has an x-mark with a pop-up message: "Not connected to the PulseAudio server". I will share some logs shortly.

**Comment by ZYousef** [comment]
Below you can find some logs from:
`sudo pulseaudio --system`
& `~/.xsession-errors`

What I've noticed from these logs that pulseaudio isn't set up correctly and unable to connect


[xsession.txt](https://github.com/QubesOS/qubes-issues/files/8323687/xsession.txt)
[pulseaudio --system.txt](https://github.com/QubesOS/qubes-issues/files/8323688/pulseaudio.--system.txt)

**Comment by ZYousef** [comment]
**Update**
Surprisingly if you start the machine while you're in dom0 environment then switch to the sys-gui environment, and use it to run some videos it will play fine!

**Comment by DemiMarie** [comment]
@ZYousef Have you set sys-gui to also be the AudioVM?

**Comment by ZYousef** [comment]
do you mean setting default-audiovm to be sys-gui?
if so, yes! however, after setting it as audiovm, `~/.xsession-errors` now fails 
at `sys-net: Starting AUDIO` with `Task exception was never retrieved` ... `qvm_start_daemon.py:576> exception=FileNotFoundError(2,'No such file or directory'">`

**Comment by DemiMarie** [comment]
> **Update**
> I've installed _qubes-audio-daemon_ to fix the previous error, now it says: `sys-gui connected to None`.
> please note that I'm only using sys-gui without sys-audio being set up.

What happens if you set sys-gui’s AudioVM to dom0?

**Comment by ZYousef** [comment]
**Update**
I've found a workaround to solve this issue with the help of @DemiMarie, however, I'm concerned about the security implications of the solution. 

1. Setup sys-gui as mentioned before
> ### Steps to reproduce
> ```
> sudo qubesctl top.enable qvm.sys-gui
> sudo qubesctl top.enable qvm.sys-gui pillar=True
> sudo qubesctl --all state.highstate
> ```
> 
> ((wait for a long time)
> 
> `sudo qubesctl top.disable qvm.sys-gui ` set default gui: `qubes-prefs default-guivm sys-gui `
2. Change the preferences:
```
qubes-prefs default-guivm sys-gui
qubes-prefs default-audiovm sys-gui
qvm-prefs sys-gui audiovm dom0
```
3. install _qubes-audio-daemon_ on fedora-34-xfce (sys-gui's template)
4.  Create an autostart for _pulse-audio-with-vchan_ or edit /etc/xdg/autostart/qubes-pulseaudio.desktop on fedora-34-xfce

voilà you should be able to enjoy YouTube on GUI-domain!

**Comment by ben-grande** [comment]
From reading https://github.com/QubesOS/qubes-issues/issues/7367#issuecomment-1088454472, I believe this was solved and this issue can be closed.

> I am sorry I wasn't clear in my OP. I meant to say that the video is played within a qube/appVM on the sys-gui environment.

I just recommend correcting the title for people searching for it.

Recommended title:

_Can't play streams on qubes connected to GUI-domain (sys-gui)_

**Comment by ben-grande** [comment]
> (If it should still be closed, maybe it should be closed with another resolution, like [ R: not applicable](https://github.com/QubesOS/qubes-issues/labels/R%3A%20not%20applicable) ?)

Yes.
