### ISSUE TITLE
dom0 kernel-devel update conflicts

### ISSUE THREAD

**Issue by honzahosek** [QubesOS/qubes-issues#7368]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
4.1

### Brief summary

I have dkms in dom0. When there is kernel update comes in the dom0 update fails with error like this:

`file /usr/lib/.build-id/f7/9af12af50961eac585a667cbfce1ad5b947600 from install of kernel-devel-1000:5.10.104-3.fc32.qubes.x86_64 conflicts with file from package kernel-devel-1000:5.10.96-1.fc32.qubes.x86_64
`

### Steps to reproduce
In dom0 have kernel-devel and dkms packages installed and some dkms built. (Probably just kernel-devel package is enough.)
Try update dom0 with new kernel.

### Workaround

Uninstall kernel-devel, dkms and dependencies, update dom0, install packages again.

**Comment by logoerthiner1** [comment]
I have just encountered the issue; I ended up removing the kernel-devel package.

Minor issue for me but may be nontrivial for others.

**Comment by DemiMarie** [comment]
What dkms package do you have installed?

**Comment by honzahosek** [comment]
https://source.puri.sm/-/snippets/1170
