### ISSUE TITLE
Apple M1 Support - AARCH64/ARM support in General

### ISSUE THREAD

**Issue by dylangerdaly** [QubesOS/qubes-issues#7369]
### The problem you're addressing (if any)
Now that we can all collectively agree Intel's x86_64 is dead, it's time to start working on aarch64 support for Qubes

### The solution you'd like
Hopefully a migration away from Xen to something more versatile like KVM?

### The value to a user, and who that user might be
Access to a better ISA, aarch64 Chromebooks (fully, totally open ecosystem), access to Apple hardware if the user so chooses (it's in the title for that clickbaiting)

**Comment by fepitre** [comment]
Please take a look at https://github.com/QubesOS/qubes-issues/issues/4318.

**Comment by andrewdavidwong** [comment]
This is probably too broad to be a single issue. There's a high risk that this will turn into a sprawling years-long "discussion issue" like #4318, which we're very much trying to [avoid](https://www.qubes-os.org/doc/issue-tracking/#the-issue-tracker-is-not-a-discussion-forum).

I suggest starting a thread on [qubes-devel or the forum](https://www.qubes-os.org/support/) instead, then, once some details been fleshed out, subsequently opening more focused, targeted issues for [single, actionable things](https://www.qubes-os.org/doc/issue-tracking/#every-issue-must-be-about-a-single-actionable-thing). These can then be grouped into [projects](https://www.qubes-os.org/doc/issue-tracking/#projects).
