### ISSUE TITLE
USB Keyboard not working after waking up from standby

### ISSUE THREAD

**Issue by Szewcson** [QubesOS/qubes-issues#7370]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
4.1

### Brief summary
After waking up my laptop from hibernation I'm unable to provide the password in screensaver popup window. In most cases both my internal USB keyboard and external USB mouse not working (so I think that sys-usb qube not starting), but once have situation when mouse is working and keyboard not. Also the active field for cursor was reduced to that popup window.

### Steps to reproduce
1.) Setup system with sys-usb providing usb-keyboard support
2.) Leave the computer with screen lock (ctrl+alt+l), or just let it go to sleep
3.) Wait for the hibernation
4.) Press the button (I have only one since don't know if it is treated as reset/power or something else)
5.)Try to log in

### Expected behavior
I will be able to enter the password and log in

### Actual behavior
Keyboard and mouse are unresponsive.

**Comment by marmarek** [comment]
> once have situation when mouse is working and keyboard not

if this happens, you can try unplugging your keyboard and plugging it again

> Also the active field for cursor was reduced to that popup window.

This is normal behavior of xscreensaver.

> both my internal USB keyboard and external USB mouse not working (so I think that sys-usb qube not starting)

This may be the same as #4042 . The fix is close, so it will be worth trying when the package will be available. Or, if you're not afraid of building the kernel yourself, you can find the patch in [latest comment](https://github.com/QubesOS/qubes-issues/issues/4042#issuecomment-1075208930)

**Comment by marmarek** [comment]
> What is the status of other similar bug - the one that sys-usb sometimes not starting after boot?

Can you link a specific ticket?

**Comment by andrewdavidwong** [comment]
Xen doesn't support hibernation. You must mean standby/sleep. Updating title.

**Comment by Szewcson** [comment]
Ok, my fault but in Power Manager There is a Hybernation and Suspend. Since I'm working on AC adapter It should be Suspend but should I assume that for Xen both of them fallback to Standby?

**Comment by DemiMarie** [comment]
@Szewcson I am not sure.
