### ISSUE TITLE
Qubes 4.1/Nouveau/Linux 5.16: XFCE-Demirroring of multiple screens requires Disabling Compositor

### ISSUE THREAD

**Issue by r-cheologist** [QubesOS/qubes-issues#7373]
### Qubes OS release
4.1

### Brief summary
When using the onboard HDMI port of a ThinkPad P15 with `kernel-latest` (currently 5.16 and needed to make the NVIDIA graphics card used), neither the XFCE onboard configurator nor `xrandr` allow for de-mirroring of laptop and external screen.

### Steps to reproduce
Actual test machine:

> ThinkPad P15 Gen 2:
1x 11th Generation Intel® Core™ i7-11800H Processor(Core™ i7-11800H)
1x Bluetooth® 5.0 or above; Intel® Wi-Fi 6E AX210 2x2 AX
1x Ethernet; Combo audio/microphone jack; HDMI 2.0; 1 Power button; 2x TBT (DP 1.4
USB 3.2 Gen2); 2 USB 3.2 Gen 2 (Type A); SIM Card (Nano SIM)
1x 720P HD with Dual Array Microphone & ThinkShutter
1x NVIDIA RTX A2000 4GB 

On a machine using an `Ampere` class NVIDIA card:

1. Install `kernel-latest` in `dom0`
2. set the `display` option in the BIOS to `discrete`
3. connect an external monitor
4. use ` Q → System Tools → Display → uncheck “Mirror displays” ` 

Usage of `xrandr` from `dom0`s CLI reproduced the issue.

### Expected behavior
Monitors should be de-mirrored.

### Actual behavior
Monitors are apparently demirrored and their representations in the `Display` tool are actually arrangeable etc. BUT open windows appear on both screens. They can however, only be interacted with on one screen.

Additionally the mouse cursor actually behaves as expected.

### Remedy:
` Q → System Tools → Window Manager Tweaks → Compositor → uncheck “Enable display compositing” `  fixes the problem. Proper demirroring observed.

**Comment by DemiMarie** [comment]
> Monitors are apparently demirrored and their representations in the `Display` tool are actually arrangeable etc. BUT open windows appear on both screens. They can however, only be interacted with on one screen.

Does this apply to dom0 windows as well?  If dom0 windows work properly, then this is probably a GUI daemon bug.  Otherwise, this is either a kernel bug, an X server bug, or a window manager bug.

**Comment by r-cheologist** [comment]
> On 24.03.2022 16:09 Demi Marie Obenour ***@***.***> wrote:
> 
> 
> 
> 
> 
> > 
> > Monitors are apparently demirrored and their representations in the Display tool are actually arrangeable etc. BUT open windows appear on both screens. They can however, only be interacted with on one screen.
> > 
> 
> Does this apply to dom0 windows as well? If dom0 windows work properly, then this is probably a GUI daemon bug. Otherwise, this is either a kernel bug, an X server bug, or a window manager bug.`
> 
`dom0` windows in particular (e.g. xfce display and window manager tweaks apps).

**Comment by DemiMarie** [comment]
Can you report this as an xfwm4 bug?
