### ISSUE TITLE
qubes-gpg-split-2.0.57: Unknown list option 'no-show-policy-urls'

### ISSUE THREAD

**Issue by fepitre** [QubesOS/qubes-issues#7378]
Since qubes-split-gpg version 2.0.57, it fails with: `Unknown list option 'no-show-policy-urls'` when executing for example as client for debsign:

```
debsign -k77EEEF6D0386962AEA8CF84A9B8273F80AC219E6 -pqubes-gpg-client-wrapper --no-re-sign /home/user/qubes-builderv2/artifacts/components/core-qrexec/4.1.16-1/vm-bullseye/build/qubes-core-qrexec_4.1.16-1+deb11u1_amd64.changes
```
It works with version 2.0.55.

**Comment by DemiMarie** [comment]
Introduced by 49b70ad7726a7e595d7a9c8f10881cbdc02ce47a.  Marking as `P: critical` because it breaks debsign.
