### ISSUE TITLE
4.1 sys-gui - Qube Manager crash

### ISSUE THREAD

**Issue by unman** [QubesOS/qubes-issues#7379]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
4.1

### Brief summary
Qube Manager closes unexpectedly with sys-gui when QubesOS is selected from About menu.

### Steps to reproduce
Prepare sys-gui under 4.1
Log in - start Qube Manager
Select "About"->QubesOS

### Expected behavior
Information is displayed.

### Actual behavior
Manager closes.

**Comment by DemiMarie** [comment]
Can you provide a backtrace?

**Comment by DemiMarie** [comment]
I suspect the manager is trying to list dom0 packages and failing.

**Comment by Kenny606** [comment]
> I suspect the manager is trying to list dom0 packages and failing.

I've noticed the same problem in sys-gui-gpu, it only occurs the second time I do it, the first time I just get nothing.
The exact same behavior also occurs when trying to open a console on any VM.

I'd be happy to provide a "backtrace" however unfortunately I have no clue how to do that lol.
Is their a document somewhere with the steps?

**Comment by DemiMarie** [comment]
> I'd be happy to provide a "backtrace" however unfortunately I have no clue how to do that lol.

If you run qubes-manager in a console window, you should get some text printed on the console when it crashes.  That will help us debug the issue.

**Comment by Kenny606** [comment]
> > I'd be happy to provide a "backtrace" however unfortunately I have no clue how to do that lol.
> 
> If you run qubes-manager in a console window, you should get some text printed on the console when it crashes. That will help us debug the issue.

I couldn't get the information out of sys-gui-gpu as text or as a text file, attached pictures are the best I could do after an hour.

sys-gui, qvm-copy and qvm-copy-to-vm kept giving me request refused when trying to transfer a text file into a qube.

And for some reason while in the gui-domain I couldn't paste anything I placed in the global clipboard into a qube.
Copying between qubes worked fine, or from a qube to the gui domain.

![QM-About Qubes](https://user-images.githubusercontent.com/73485614/163924298-d6c05eb8-e0db-442d-b202-29ba54a54012.jpg)
![QM-Open Console](https://user-images.githubusercontent.com/73485614/163924299-162ce794-0b5c-448e-82e3-c03d604300c5.jpg)

**Comment by DemiMarie** [comment]
There are two different bugs here:

1. Qubes Manager relies on `/etc/qubes-release` and `/usr/bin/qvm-console-dispvm` for certain functions, but those files only exist in dom0.
2. Qubes Manager doesn’t handle the exceptions raised when these files are missing.

**Comment by andrewdavidwong** [comment]
> I couldn't get the information out of sys-gui-gpu as text or as a text file, attached pictures are the best I could do after an hour.
> 
> sys-gui, qvm-copy and qvm-copy-to-vm kept giving me request refused when trying to transfer a text file into a qube.
> 
> And for some reason while in the gui-domain I couldn't paste anything I placed in the global clipboard into a qube.
> Copying between qubes worked fine, or from a qube to the gui domain.

Does [this](https://www.qubes-os.org/doc/how-to-copy-from-dom0/) work? If not, please open a separate issue for this.

**Comment by Geblaat** [comment]
I'm also getting Qube Manager crashes on qube right-click context menu actions. For example clicking Update or Open console in qube. First time clicking and nothing happens, try again and Qube Manager crashes.

**Comment by DemiMarie** [comment]
> I'm also getting Qube Manager crashes on qube right-click context menu actions. For example clicking Update or Open console in qube. First time clicking and nothing happens, try again and Qube Manager crashes.

Can you provide the standard error from Qubes Manager?

**Comment by Geblaat** [comment]
> > I'm also getting Qube Manager crashes on qube right-click context menu actions. For example clicking Update or Open console in qube. First time clicking and nothing happens, try again and Qube Manager crashes.
> 
> Can you provide the standard error from Qubes Manager?

Ah yes, sorry.
From Open console in Qube:
```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/qubesmanager/qube_manager.py", line 1575, in action_open_console_triggered
    subprocess.Popen(['qvm-console-dispvm', vm.name],
  File "/usr/lib64/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib64/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'qvm-console-dispvm'
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/qubesmanager/qube_manager.py", line 1575, in action_open_console_triggered
    subprocess.Popen(['qvm-console-dispvm', vm.name],
  File "/usr/lib64/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib64/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'qvm-console-dispvm'
Aborted (core dumped)
```
From Update:
```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/qubesmanager/qube_manager.py", line 610, in run
    self.vm.run_service("qubes.InstallUpdatesGUI",
  File "/usr/lib/python3.9/site-packages/qubesadmin/vm/__init__.py", line 277, in run_service
    return self.app.run_service(self._method_dest, service, **kwargs)
  File "/usr/lib/python3.9/site-packages/qubesadmin/app.py", line 908, in run_service
    raise ValueError(
ValueError: non-default user not possible for calls from VM
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/qubesmanager/qube_manager.py", line 610, in run
    self.vm.run_service("qubes.InstallUpdatesGUI",
  File "/usr/lib/python3.9/site-packages/qubesadmin/vm/__init__.py", line 277, in run_service
    return self.app.run_service(self._method_dest, service, **kwargs)
  File "/usr/lib/python3.9/site-packages/qubesadmin/app.py", line 908, in run_service
    raise ValueError(
ValueError: non-default user not possible for calls from VM
Aborted (core dumped)
```

**Comment by Geblaat** [comment]
Also from Run command in Qube from completeness sake:
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 463, resource id: 8404060, major code: 40 (TranslateCoords), minor code: 0
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/qubesmanager/qube_manager.py", line 624, in run
    self.vm.run(self.command_to_run)
  File "/usr/lib/python3.9/site-packages/qubesadmin/vm/__init__.py", line 324, in run
    raise e
  File "/usr/lib/python3.9/site-packages/qubesadmin/vm/__init__.py", line 320, in run
    return self.run_service_for_stdio('qubes.VMShell',
  File "/usr/lib/python3.9/site-packages/qubesadmin/vm/__init__.py", line 300, in run_service_for_stdio
    raise exc
subprocess.CalledProcessError: Command 'sudo dnf update' returned non-zero exit status 126.
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/qubesmanager/qube_manager.py", line 624, in run
    self.vm.run(self.command_to_run)
  File "/usr/lib/python3.9/site-packages/qubesadmin/vm/__init__.py", line 324, in run
    raise e
  File "/usr/lib/python3.9/site-packages/qubesadmin/vm/__init__.py", line 320, in run
    return self.run_service_for_stdio('qubes.VMShell',
  File "/usr/lib/python3.9/site-packages/qubesadmin/vm/__init__.py", line 300, in run_service_for_stdio
    raise exc
subprocess.CalledProcessError: Command 'sudo dnf update' returned non-zero exit status 126.
Aborted (core dumped)

**Comment by Geblaat** [comment]
> > > I'd be happy to provide a "backtrace" however unfortunately I have no clue how to do that lol.
> > 
> > 
> > If you run qubes-manager in a console window, you should get some text printed on the console when it crashes. That will help us debug the issue.
> 
> I couldn't get the information out of sys-gui-gpu as text or as a text file, attached pictures are the best I could do after an hour.

I had issues with that too. Since I read you gave up after trying an hour, I figured just to go nuclear and set sys-firewall as net-vm for sys-gui to give it internet access and run Firefox directly in sys-gui :P (Note that it was a separate new install on another hard drive, so I didn't care about the security implications.) I opened an issue about the clipboard: https://github.com/QubesOS/qubes-issues/issues/7543
