### ISSUE TITLE
keyboard focus bug

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#738]
**Reported by marmarek on 16 Jun 2013 11:56 UTC**
On 06/09/13 10:09, ix4...@gmail.com wrote:
> This always involves the use of KeePassX, which traps [CTR-V] as "Perform
> auto-type". My typical workflow:
> 1. start "passwords" AppVM
> 2. highlight, copy, SHFT-CTRL-C my "personal" master pw
> 3. start "personal" AppVM by firing up Firefox & KeePassX
> 4. click on the KeePassX window, hit SHFT-CTRL-V & CTRL-V. The master pw is correctly copied into the dialog box and my personal AppVM pw db is unlocked.
> 5. ALT-TAB or click on the FF window to ensure the focus is on the right field (the "username" field of the form I want to autocomplete").
> 6. ALT-TAB or click on the KeePassX window, highlight the credentials entry I want to use, hit CTRL-V
> 7. Watch in horror as my master pw which was copied earlier from the non-networked password AppVM is pasted into Firefox!
> 8. At that point, with the KeePassX window in the foreground, clicking entries in it with the mouse, anything I type is received by the non-active Firefox window, not just CTRL-V.

On 06/12/13 01:22, ix4...@gmail.com wrote:
> On 11 June 2013 19:14, Joanna Rutkowska <joa...@invisiblethingslab.com>wrote:
>> IIUC the problem only affects switching focus between the two windows
>> belonging to *the same* AppVM, correct?
>>
>> joanna.
>>
>>
> Correct.
>
Ok, perhaps there is a bug there, which is a result of us not being able
to precisely reflect the order of windows within one domain. However, I
don't think I agree this could be classified as "dangerous", or even
security-related. We've been explaining this many time -- there is no
security isolation between apps running within one domain.

Details here: https://groups.google.com/d/msg/qubes-users/2m93GabHx6I/kIuL7ZQ7alIJ

Migrated-From: https://wiki.qubes-os.org/ticket/738

**Comment by nrgaway** [comment]
This is really fixed? That's been my top peeve :)

Guess I have some compiling to do...

**Comment by marmarek** [comment]
On Fri, May 22, 2015 at 06:14:24AM -0700, nrgaway wrote:
> This is really fixed? That's been my top peeve :)

I hope so :)
Unfortunately it isn't possible close the issue (with commit message)
when the commit is pushed to specific branch, so when I push a fix to
any branch (like testing or so), it automatically closes the issue. So I
can either mark proposed fix to close the issue (and possibly reopen it
later), or close it manually after some confirmation. I'm too lazy for
the later option ;)

> Guess I have some compiling to do...

Package is already in current-testing

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by nrgaway** [comment]
Did you push to fc20 testing repo too? Only my fc21 updated

**Comment by marmarek** [comment]
On Fri, May 22, 2015 at 06:43:31AM -0700, nrgaway wrote:
> Did you push to fc20 testing repo too? Only my fc21 updated

It is update for dom0, qubes-gui-dom0-3.0.4.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?
