### ISSUE TITLE
Qubes OS 4.1 is not usable on 11 gen Intel CPU with iGPU due to slow redrawing and high CPU consumption

### ISSUE THREAD

**Issue by jamke** [QubesOS/qubes-issues#7380]
### Qubes OS release
R4.1

### Brief summary
Installation and usage of Qubes OS 4.1 is not possible on 11 gen Intel CPU with iGPU because of slow drawing and high CPU consumption (XOrg consumes 100% of one CPU).
Screen redraw takes up to 1-2 seconds when internal GPU is used on Intel 11th generation CPUs (maybe 10, 12 too?).
Mouse is moving with huge lags and the whole system is unusable.

### Steps to reproduce
Run Qubes OS 4.1 installation process from flash disk or run already installed Qubes OS on 11 gen Intel CPU with iGPU connected to display via DP/HDMI/DVI, the symptoms are all the same - redrawing is insanely slow, mouse movement is laggy, CPU is hot.

### Expected behavior
Qubes OS 4.1 works as usual.

### Actual behavior
Qubes OS 4.1 is unusable. Redrawing is insanely slow, mouse is moving with huge lags.

### Work-arounds
Using external GPU (eGPU) and connecting Display to it instead of iGPU solves the problem.
But it destroys the whole point of using Intel iGPU that was always a recommended GPU for Qubes OS since forever.
Also redundant eGPU costs money, occupies 1-2 additional PCIe slots and provides additional noise with irreplaceable noisy coolers.

### Related issues
Possible this ones are related: #6356, #4943. But I have issues always, not after terminal switches or something. Just always and the system is unusable 100% of the time.
Similar problems are in #5244 but it's about 4.0 and not sure it's 100% the same, because I have latest and updated R4.1.

**Comment by DemiMarie** [comment]
Does installing `kernel-latest` help?

**Comment by jamke** [comment]
Well. After `sudo qubes-dom0-update kernel-latest` I can't boot at all with eGPU installed (even not connect to display, nor selected in BIOS as default one).
I have Kernel panic after selecting default boot option in grub, the screen has a lot of text, like 2-3 screens and at the end:

```
Kernel panic - not syncing: Fatal exception
Kernel Offset: disabled
```
And PC reboots automatically in a couple of seconds.


But when I removed eGPU, I got working Qubes OS with not problems mentioned in the report. So, huge thanks for advice. it kind of works!

On the other hand I still need eGPU, because I'm hoping to passthough it and not sure how to do so when Qubes OS does not boot like that.

**Comment by DemiMarie** [comment]
> Well. After `sudo qubes-dom0-update kernel-latest` I can't boot at all with eGPU installed (even not connected to display, nor selected in BIOS as default one). I have Kernel panic after selecting default boot option in grub, the screen has a lot of text, like 2-3 screens and at the end:
> 
> ```
> Kernel panic - not syncing: Fatal exception
> Kernel Offset: disabled
> ```

Can you get a backtrace from pstore on the next successful boot?

> But when I removed eGPU, I got working Qubes OS with not problems mentioned in the report. So, huge thanks for advice. it kind of works!

You’re welcome!

> On the other hand I still need eGPU, because I'm hoping to passthough it and not sure how to do so when Qubes OS does not boot like that.

My intuition is that this is a “PCIe hotplug needs to be enabled in dom0” issue, which needs more testing to make sure Xen and dom0 handle this properly.

**Comment by logoerthiner1** [comment]
For any hardware problems, try `sudo qubes-dom0-update` from time to time. Problem may one day get solved when linux-firmware or some similar packages get updated.

**Comment by turmoil995** [comment]
After installing kernel-latest it seem to be solved however it isn't. 
- From time to time cursor is not being cleared properly. Such artifacts remains and are being cleared randomly.
- I am not able to change primary built-in screen resolution. If I change it screen will be automatically switched off. However the list is full of possible resolution to choose from. 
- I can confirm that there is no problem with the external screen attached to builtin HDMI port it works with no issue.
my CPU is i7-11370H

**Comment by turmoil995** [comment]
I can also confirm cursor slowness/refresh problems in like 1/4 part of the upper screen area. Lower part of the screen doesn't seem to affected. I use laptop with built in screen for testing.

**Comment by jamke** [comment]
> * From time to time cursor is not being cleared properly.

Yes, I still have it on a clean up-to-date R4.1.1 installation, it's not fixed.
The movement over desktop icons or window borders instantly makes cursor fuzzy and surrounded with random pixels.

The way I partly fixed it for myself is similar - I added ` i915.enable_psr=0` to the `GRUB_CMDLINE_LINUX` in `/etc/default/grub`:

> `sudo nano /etc/default/grub`

And updating grub config. Documentation for R4.1 is outdated, so in my case I did it this way:

> `sudo grub2-mkconfig -o /boot/efi/EFI/qubes/grub.cfg`

Before that I made a copy of `/boot/efi/EFI/qubes/grub.cfg` to `/boot/efi/EFI/qubes/grub.cfg_orig` just in case.

This removed flickering but several problems are still in place with R4.1:
1) The password for LVM screen still has artifacts - every password char produces new ones. The progress bar is also disturbed.
2) The CPU consumption for mouse movement goes up to 20% of 1CPU, which is ridiculously high, 2 times more than I had on older PC with R4.0 with 2-4 times slower CPU.
3) Youtube at 1080p and 2x is unplayable and freezes (in Firefox at least), while mpv plays 1080p videos with much higher bitrate flawlessly.

**Comment by jamke** [comment]
I checked the situation with current Qubes OS USB installer with only iGPU (Intel) being used, without eGPU.
The installer uses kernel `5.15.52-1.fc32q.qubes.x86_64`. 

I saw no major issues with super-slow redrawing that I had before.
Therefore I'm closing this issue as solved for me.
