### ISSUE TITLE
Provide information on integrating Windows into Qubes R4.1

### ISSUE THREAD

**Issue by GWeck** [QubesOS/qubes-issues#7381]
### The problem you're addressing (if any)
The current documentation on Windows integration and Qubes Windows Tools (QWT) is outdated and meanwhile somewhat chaotic, describing QWT 4.0.1.3 and several methods to use it.

### The solution you'd like
As there is now a working solution for R4.1, its installation and use should be described as part of the Qubes documentation. I provided some texts as a starting point and created corresponding pull requests:
- [Add instructions for Windows under Qubes R4.1 #1243 ](https://github.com/QubesOS/qubes-doc/pull/1243)
- [Provide information on Windows under Qubes R4.1 #169 ](https://github.com/Qubes-Community/Contents/pull/169)

Hopefully, that helps.

### The value to a user, and who that user might be
Anyone trying to use Windows under Qubes R4.1 would benefit from such documentation.

**Comment by andrewdavidwong** [comment]
https://github.com/QubesOS/qubes-doc/pull/1243 has been merged. Thank you!

**Comment by jevank** [comment]
This is going to be great. Added some comments.

**Comment by GWeck** [comment]
@jevank I changed the texts accordingly. It seems that we are converging rather fast!

**Comment by brendanhoar** [comment]
The last 3 of 5 links give 404 if I use a browser without an existing GitHub login session.

The first 2 4.0-only links work ok.

B

**Comment by GWeck** [comment]
This directory has not yet been merged - it's still in the review process, but should be out soon.

Do you know will merge this, as it is in the community area?

**Comment by andrewdavidwong** [comment]
@awokd might be able to comment on that.

**Comment by taradiddles** [comment]
> @awokd or @taradiddles might be able to comment on that.

(fyi I resigned as an admin of the qubes-community project years ago so can't merge the PR).

@awokd usually merges PRs on week-ends; since he hasn't done so, either he was busy with something else, or maybe he was waiting for the PR to "stabilize" as there were still reviews/commits.

**Comment by awokd** [comment]
Above documentation has been merged.

**Comment by GWeck** [comment]
Thank you for the merge! I checked the links between the files and had to correct two files because their links still went to the main documentation, not to the community documentation. Hopefully they are correct now.

**Comment by GWeck** [comment]
The documentation now describes the installation of Windows 7, 10, and 11, and of Qubes Windows Tools 4.1.68.1, using the standard procedure for installation from the current-testing repo. Now, thanks to the work of @jevank et al., using Windows under Qubes has changed from being witchcraft to solid IT engineering. I sincerely hope that this will help to spread Qubes usage further!

@andrewdavidwong Could you perhaps consider moving the Windows chapter from its current location under "Advanced topics" to a more standard location, like "Templates" or "Operating system guides". Perhaps this might give users more courage to try it -especially Windows users afraid of Linux. There's no longer need to be frightened - if even I could do it, anyone can!

I'll leave the issue open for a few more days. Perhaps I can add a few screenshots to the installation description.

**Comment by andrewdavidwong** [comment]
> @andrewdavidwong Could you perhaps consider moving the Windows chapter from its current location under "Advanced topics" to a more standard location, like "Templates" or "Operating system guides". Perhaps this might give users more courage to try it -especially Windows users afraid of Linux. There's no longer need to be frightened - if even I could do it, anyone can!

(For anyone else following the discussion, we're referring to this page: https://www.qubes-os.org/doc/windows/)

Well, it doesn't really fit under "Templates," because there isn't a template package you can download and install, and it's not handled the way actual templates are. It also *technically* doesn't fit under "Operating system guides," since that's under "External documentation," and this page is *internal* documentation. However, while this page is internal, it's really just a brief stub with links to external documentation, so I suppose moving it under "Operating system guides" is acceptable and is the better fit between the two options.

One downside is that we end up hardcoding an internal absolute (as opposed to relative) link, which we generally [avoid](https://www.qubes-os.org/doc/documentation-style-guide/#relative-vs-absolute-links), but I suppose an exception can be made in this case. In the future, perhaps we can do away with this interstitial page and simply link directly to one or more external Windows documentation pages. @GWeck, you might consider creating a single Windows "landing page" so that we can link to just one external page instead of several. Or, I suppose we could just move this very page to the [community docs](https://github.com/Qubes-Community) and link to it there.

**Comment by GWeck** [comment]
Thank you for moving the Windows documentation!

I think the very last of your suggestions may be the best and the easiest one: Just move the landing page to the community docs. This page really has not much content, it just provides links to the real documentation. So, for me as an external observer, there is no difference if is flagged as internal or community.

As to the future: After EOL of Qubes R4.0, the first two links concerning this version, and the last link concerning migration, probably can be removed sometime - maybe in a year or so. I would prefer to keep the two pages concerning Windows and QWT in R4.1 separate, as they describe quite different actions. So we are still stuck with at least two pages, and the landing page still makes sense. What do you think?

**Comment by GWeck** [comment]
As the documentation is now quite complete, I close this issue.

**Comment by andrewdavidwong** [comment]
> I think the very last of your suggestions may be the best and the easiest one: Just move the landing page to the community docs. This page really has not much content, it just provides links to the real documentation. So, for me as an external observer, there is no difference if is flagged as internal or community.

Done. (See commits referenced above.)

> As to the future: After EOL of Qubes R4.0, the first two links concerning this version, and the last link concerning migration, probably can be removed sometime - maybe in a year or so. I would prefer to keep the two pages concerning Windows and QWT in R4.1 separate, as they describe quite different actions. So we are still stuck with at least two pages, and the landing page still makes sense. What do you think?

Sounds fine. Thanks again for all of your hard work!
