### ISSUE TITLE
enforce dom0 hostname before 4.1 upgrade

### ISSUE THREAD

**Issue by Osndok** [QubesOS/qubes-issues#7382]
### Qubes OS release

In the no-man's land between Qubes v4.0 & Qubes v4.1 (upgrade process).

The fix would probably fall under in the 4.0 packages.

### Brief summary

I experienced a lot of pain upgrading from 4.0 -> 4.1.

The chief complaint/symptom was that NO GUI APPS worked for any domN, although I could tell those that I set to auto-launch and have background processes work otherwise working.

By chance, I started working backwards from this stack trace that I found when trying to run the qubes global settings app:
```
----
line: raise KeyError(item)
func: __getitem__
line no.: 98
file: /usr/lib/python3.8/site-packages/qubesadmin/app.py
----
line: self.vm = self.qubes_app.domains[self.qubes_app.local_name]
func: __init__
line no.: 78
file: /usr/lib/python3.8/site-packages/qubesmanager/global_settings.py
----
line: window = window_class(qt_app, qubes_app)
func: run_synchronous
line no.: 558
file: /usr/lib/python3.8/site-packages/qubesmanager/utils.py
----
line: utils.run_synchronous(GlobalSettingsWindow)
func: main
line no.: 668
file: /usr/lib/python3.8/site-packages/qubesmanager/global_settings.py
----
line: load_entry_point('qubesmanager==4.1.23', 'console_scripts', 'qubes-global-settings')()
func: <module>
line no.: 11
file: /usr/bin/qubes-global-settings
```
... I deduced that qubes wanted (and was assuming that) my dom0 hostname to be `dom0`, which it was not.

I don't recall if I manually changed this some time after installing 4.0, or I actually customized it in the installer itself.

I changed my dom0 hostname to `dom0`, and rebooted. This seemed to be the key that re-enabled graphical applications, and made the operating system usable once again.

### Steps to reproduce

(presumed, untested)
1. Install qubes 4.0
2. change the hostname
3. upgrade to 4.1
4. try to use any non-dom0 graphical application

or maybe?
1. install qubes 4.1
2. change the hostname
3. reboot
4. try to use any non-dom0 graphical application

### Expected behavior

If the final qubes 4.1 install state requires a special hostname (or any other variable for that matter), I would expect it to either check-and-abort, warn-and-require-overide, or maybe even silently change it. Especially since the hostname is such an easy value to get.

### Actual behavior

Qubes 4.0 updates to 4.1 in an unusably-broken state that is difficult to diagnose.

### Additional information

I worked around the issue by using this command in dom0:
```
sudo hostnamectl set-hostname dom0
reboot
```

I am effected by #6824 & #7114 

There were several unclean rpm config files post-upgrade:
```
# find etc -name '*.rpmnew'
etc/pam.d/password-auth.rpmnew
etc/pam.d/fingerprint-auth.rpmnew
etc/pam.d/smartcard-auth.rpmnew
etc/pam.d/system-auth.rpmnew
etc/pam.d/postlogin.rpmnew
etc/nsswitch.conf.rpmnew
etc/dnf/dnf.conf.rpmnew
etc/qubes/qmemman.conf.rpmnew
etc/xen/xl.conf.rpmnew
etc/xscreensaver/XScreenSaver.ad.tail.rpmnew
etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfce4-keyboard-shortcuts.xml.rpmnew
etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xsettings.xml.rpmnew
etc/xdg/xfce4/panel/default.xml.rpmnew
etc/lvm/lvm.conf.rpmnew
```
^ I swapped some of them in, and can probably still get diffs of these if that would help. They didn't seem too interesting.

I notice several old packages linger after the upgrade:
```
$ rpm -qa | grep -v fc32 | grep python2
python2-qubesimgconverter-4.0.31-1.fc25.x86_64
python2-pycurl-7.43.0-6.fc25.x86_64
python2-futures-3.1.1-1.fc25.noarch
python2-systemd-234-5.1.fc25.x86_64
python2-backports_abc-0.5-1.fc25.noarch
python2-urllib3-1.15.1-3.fc25.noarch
python2-tornado-4.4.2-1.fc25.x86_64
python2-qubesadmin-4.0.32-1.fc25.noarch
python2-pysocks-1.6.7-1.fc25.noarch
python2-lxml-4.1.1-1.fc25.x86_64
python2-zmq-15.3.0-2.fc25.x86_64
python2-pygpgme-0.3-18.fc25.x86_64
python2-requests-2.10.0-4.fc25.noarch
python2-singledispatch-3.4.0.3-5.fc25.noarch
python2-nose-1.3.7-11.fc25.noarch
python2-msgpack-0.4.8-1.fc25.x86_64

$ rpm -qa | grep -v fc32 | egrep '(qubes|qvm|dom)'
python2-qubesimgconverter-4.0.31-1.fc25.x86_64
kernel-qubes-vm-5.4.175-1.fc25.qubes.x86_64
qubes-mgmt-salt-base-overrides-libs-4.0.2-1.fc25.noarch
kernel-5.4.185-1.fc25.qubes.x86_64
qubes-template-debian-11-4.0.6-202109010214.noarch
qubes-template-fedora-31-minimal-4.0.1-202002142323.noarch
qubes-template-centos-7-4.0.1-201909141946.noarch
kernel-latest-qubes-vm-5.15.5-1.fc25.qubes.x86_64
kernel-5.4.175-1.fc25.qubes.x86_64
qubes-template-whonix-ws-15-4.0.1-201906232114.noarch
kernel-qubes-vm-5.4.185-1.fc25.qubes.x86_64
qubes-template-whonix-gw-15-4.0.1-201906232114.noarch
qubes-release-notes-4.1-1.noarch
qubes-dist-upgrade-4.0.5-1.fc25.noarch
kernel-latest-qubes-vm-5.16.15-1.fc25.qubes.x86_64
qubes-release-4.1-1.noarch

$ rpm -qa | grep qubesadmin
python2-qubesadmin-4.0.32-1.fc25.noarch
python3-qubesadmin-4.1.21-1.fc32.noarch
```
^ I removed the older qubesadmin. and qubes-mgmt-salt-base-overrides-libs packages, but that did not seem to help #7114.

I don't know if this (changing the dom0 hostname) fixed #6755, or it was from the general update to 4.1, or if it was any number of hardware changes/upgrades that I have since filing that issue... but I no longer notice a long-and-embarassing pause when using a KVM switch.

**Comment by andrewdavidwong** [comment]
Since 4.0 is no longer supported, it sounds like this issue is no longer applicable. 
Closing as "won't fix." If anyone has a new reason for why this should be done, please leave a comment, and we'll be happy to take another look. Thank you.
