### ISSUE TITLE
Builder: Build of 4.1 bookworm fails on desktop-linux-manager

### ISSUE THREAD

**Issue by unman** [QubesOS/qubes-issues#7383]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
4.1

### Brief summary
Building bookworm template for 4.1 fails as title

### Steps to reproduce
1. Set up Build environment
2. Select bookworm template for 4.1
3. `make qubes-vm`

### Expected behavior
All Qubes packages will be built.

### Actual behavior
Build of desktop-linux-manager fails:

error: [Errno 17] File exists: '/home/user/qubes-src/desktop-linux-manager/debian/python3-qui/usr/share/locale/en/LC_MESSAGES/'
E: pybuild pybuild:367: install: plugin distutils failed with: exit code=1: /usr/bin/python3 setup.py install --root /home/user/qubes-src/desktop-linux-manager/debian/python3-qui
dh_auto_install: error: pybuild --install -i python{version} -p "3.10 3.9" --dest-dir /home/user/qubes-src/desktop-linux-manager/debian/tmp returned exit code 13
make[1]: *** [debian/rules:17: override_dh_auto_install] Error 25
make[1]: Leaving directory '/home/user/qubes-src/desktop-linux-manager'
make: *** [debian/rules:9: binary] Error 2
dpkg-buildpackage: error: fakeroot debian/rules binary subprocess returned exit status 2
make[2]: *** [/home/user/qubes-builder/qubes-src/builder-debian//Makefile-legacy.debian:56: dist-package] Error 2

**Comment by DemiMarie** [comment]
Can you try again with `USE_DIST_BUILD_TOOLS=1`?

**Comment by unman** [comment]
Use it already, so that is not cause.
