### ISSUE TITLE
Windows audio support is incompatible with sys-audio

### ISSUE THREAD

**Issue by jevank** [QubesOS/qubes-issues#7388]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

R4.1

### Brief summary

Based on reports on Forum 
https://forum.qubes-os.org/t/using-sys-audio-for-windows-audio/10416
https://forum.qubes-os.org/t/sys-audio-and-win-7-qube-s/9918

Here is workaround
https://forum.qubes-os.org/t/using-sys-audio-for-windows-audio/10416/9

### Expected behavior

Configuring the Audio VM for Windows virtual machines using the qvm feature (?)

### Actual behavior

Dom0 is hardcoded as Audio VM in stubdomain.

**Comment by jevank** [comment]
What is the proper way to pass the audiovm parameter to the stubdomain? To extend libvirt schema for sound parameters (libvirt + libxl patches)?

**Comment by marmarek** [comment]
You can use qemu cmdline (like we do for IP config already), which makes libvirt/libxl patching not needed.

**Comment by jevank** [comment]
Good, that's much easier, thank you.

**Comment by neowutran** [comment]
If it seems ok to you, I could make a pull request to fix that

I would modify https://github.com/QubesOS/qubes-core-admin/blob/main/templates/libvirt/xen.xml and https://github.com/QubesOS/qubes-vmm-xen-stubdom-linux/blob/main/rootfs/init to implement that : 
https://forum.qubes-os.org/t/audio-qube/20685#special-cases-of-non-linux-hvm-12

( It would probably be better to wait for QWT to be re enabled first. Don't known if someone intend to work on a rewrite and I didn't tried this pull request https://github.com/QubesOS/qubes-windows-tools-cross/pull/5 )
