### ISSUE TITLE
Backup seems not work propperly 

### ISSUE THREAD

**Issue by Szewcson** [QubesOS/qubes-issues#7391]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
4.1

### Brief summary
Yesterday I tested backup and restore utility seems for a period of learning Qubes I got many unnecessary changes and probably compromise security of the system in many ways. So I decide to reinstall Qubes and restore all my AppVMs and templates for them from backup. After verification run and restore run which both ended without errors I realized myself that templates simply don't working - ok I suspect that it can end like this (but there is no statement telling that in the guide, only about dom0). Not a big problem since I can reinstall all the apps rather quickly. But later I realized myself that backup restore not restore properly also user space of all the non default VMs. So if for personal, work, untrusted and vault I got all my configs and files, that for all VM's created by myself I only have list of appmenus restored. No config and files for them.

### Steps to reproduce
1.) Create a backup of all used VMs
2.) On freshly installed Qubes run Restore Backup
3.) First use "Test restore..."
4.) Finally perform restore

### Expected behavior
User spaces for all of the VMs should be restored

### Actual behavior
Restoring user spaces only for default VMs

**Comment by andrewdavidwong** [comment]
By "user space," you mean the home directory of each app qube, correct? Just to be absolutely clear, you are saying that the VMs themselves are restored, but all of your user data (files) are missing from inside of them?

**Comment by Szewcson** [comment]
Yes, VMs was restored, they have their colors, and appmenus but not have files in home directory (most importantly Firefox ESR profiles etc.). For VM's like personal everything was in place.

**Comment by Szewcson** [comment]
Also If templates are not backuped by design maybe they shouldn't appear on backup list.

**Comment by andrewdavidwong** [comment]
> Also If templates are not backuped by design maybe they shouldn't appear on backup list.

There's nothing wrong with backing up templates. Users are free to choose whether to back them up, so it's correct and intended that they appear in the backup list.

**Comment by andrewdavidwong** [comment]
> So they should also been restored with all the apps that I installed in them?

If you chose to restore them, yes.
