### ISSUE TITLE
Syncthing startup hang

### ISSUE THREAD

**Issue by fosslinux** [QubesOS/qubes-issues#7392]
### Qubes OS release

4.1

### Brief summary

After my most recent set of updates, syncthing does not start in *any* of my VMs. This is not unique to any one distribution. I can reproduce on Fedora, Debian, and even my **unupdated** Void Linux StandaloneVM. It previously worked fine (regression).

I still have a system that I have not updated and syncthing works perfectly on. I will attempt to track down the culprit update.

Debugging using delve seems to track down the hang to a CPUID call in https://github.com/klauspost/cpuid/blob/master/cpuid_amd64.s#L9.

I have tried:
- changing the kernel version

I am yet to try:
- downgrading any packages from dom0
- just calling CPUID to see if CPUID is borked

### Steps to reproduce

1. Fully update a Qubes OS system.
2. Install syncthing in any AppVM.
3. Attempt to run syncthing and note the hang. 

### Expected behavior

Syncthing starts.

### Actual behavior

Syncthing does not start.

**Comment by DemiMarie** [comment]
Can you get a backtrace from the hang?  Does the hang appear to be at the CPUID instruction itself (as if the instruction never finishes)?  Can the hung process be killed?  Does a simple program that calls CPUID manually work?

CPUID is intercepted by Xen and emulated in the hypervisor, so this could be a Xen bug.

**Comment by fosslinux** [comment]
Here is the full backtrace and code around the hang using delve (go debugger):

```
$ dlv exec ./syncthing 
Type 'help' for list of commands.
(dlv) r
Process restarted with PID 16155
(dlv) c
received SIGINT, stopping process (will not forward signal)
> github.com/klauspost/cpuid/v2.asmCpuidex() /home/user/go/pkg/mod/github.com/klauspost/cpuid/v2@v2.0.9/cpuid_amd64.s:21 (PC: 0x85cfea)
    16:	// func asmCpuidex(op, op2 uint32) (eax, ebx, ecx, edx uint32)
    17:	TEXT ·asmCpuidex(SB), 7, $0
    18:		MOVL op+0(FP), AX
    19:		MOVL op2+4(FP), CX
    20:		CPUID
=>  21:		MOVL AX, eax+8(FP)
    22:		MOVL BX, ebx+12(FP)
    23:		MOVL CX, ecx+16(FP)
    24:		MOVL DX, edx+20(FP)
    25:		RET
    26:	
(dlv) bt
 0  0x000000000085cfea in github.com/klauspost/cpuid/v2.asmCpuidex
    at /home/user/go/pkg/mod/github.com/klauspost/cpuid/v2@v2.0.9/cpuid_amd64.s:21
 1  0x000000000085cdaa in github.com/klauspost/cpuid/v2.asmCpuidex
    at :0
 2  0x0000000000858525 in github.com/klauspost/cpuid/v2.(*CPUInfo).cacheSize
    at /home/user/go/pkg/mod/github.com/klauspost/cpuid/v2@v2.0.9/cpuid.go:765
 3  0x000000000085c396 in github.com/klauspost/cpuid/v2.addInfo
    at /home/user/go/pkg/mod/github.com/klauspost/cpuid/v2@v2.0.9/detect_x86.go:33
 4  0x0000000000856505 in github.com/klauspost/cpuid/v2.Detect
    at /home/user/go/pkg/mod/github.com/klauspost/cpuid/v2@v2.0.9/cpuid.go:257
 5  0x000000000085643c in github.com/klauspost/cpuid/v2.init.0
    at /home/user/go/pkg/mod/github.com/klauspost/cpuid/v2@v2.0.9/cpuid.go:236
 6  0x00000000004489c7 in runtime.doInit
    at /usr/lib/go/src/runtime/proc.go:6498
 7  0x0000000000448919 in runtime.doInit
    at /usr/lib/go/src/runtime/proc.go:6475
 8  0x0000000000448919 in runtime.doInit
    at /usr/lib/go/src/runtime/proc.go:6475
 9  0x0000000000448919 in runtime.doInit
    at /usr/lib/go/src/runtime/proc.go:6475
10  0x000000000043b754 in runtime.main
    at /usr/lib/go/src/runtime/proc.go:238
11  0x000000000046d041 in runtime.goexit
    at /usr/lib/go/src/runtime/asm_amd64.s:1581
(dlv) 
```

I believe that it appears to be on line 21 as the CPUID instruction is executed, incrementing the line counter, but it never finishes, causing the hang. At least that is how it seems.

Yes, the hung process can be killed.

However, a simple assembly program calling CPUID does not hang, which is pretty strange.
The assembly provided as a more indepth example on the Wikipedia page for CPUID also returns correct values...

**Comment by DemiMarie** [comment]
> Yes, the hung process can be killed.

That seems to indicate that whatever is going on is _not_ the process being stuck in Xen, since that wouldn’t be killable.

> However, a simple assembly program calling CPUID does not hang, which is pretty strange.
> The assembly provided as a more indepth example on the Wikipedia page for CPUID also returns correct values...

Can you try calling manually CPUID with the exact same parameters as the failing call?  This seems like a strange low-level bug in either Xen or Linux.  Would you by any chance be able to see what happens in kernel mode when the CPUID instruction is issued?

**Comment by fosslinux** [comment]
Further investigation has revealed (not sure how I didn't pick up some of this earlier);

At [this loop](https://github.com/klauspost/cpuid/blob/v2.0.9/cpuid.go#L764), this loop never ends, creating the illusion that CPUID never ends (for somereason whenever I CTRL-Cd it always stopped around CPUID, probably due to those instructions being most intensive). 

On my AMD Ryzen 1600AF (aka basically 2600), the cpuidex call (CPUID extended, includes an extra argument), no matter the value of the second argument (which is what is being incremented), it returns the exact same values. I think this is incorrect but I cannot find data to back that up either way.

On my Intel i5-7200U laptop, after complete system upgrades, I *cannot* reproduce this issue. Seems to be limited to AMD systems?

In my second Qubes install for testing things (on a separate drive), I can reproduce this problem, but NOT if I run the syncthing binary in dom0 (any casual readers, please do not do this, the security implications are possible complete system compromise).

When I next have some spare time to investigate this, I will see whether the same call of CPUID in dom0 and a qube produces the same output. (Hypothesis: It will not).

**Comment by marmarek** [comment]
> On my AMD Ryzen 1600AF (aka basically 2600), the cpuidex call (CPUID extended, includes an extra argument), no matter the value of the second argument (which is what is being incremented), it returns the exact same values.

Can you say what specifically values are returned there?

**Comment by fosslinux** [comment]
> Can you say what specifically values are returned there?

```
Values returned:
	eax: 16673
	ebx: 29360191
	ecx: 63
	edx: 0
```

**Comment by fosslinux** [comment]
Ah, makes sense, but how come this worked in the past then?

**Comment by andyhhp** [comment]
It will be a consequence of https://github.com/QubesOS/qubes-vmm-xen/blob/xen-4.14/patch-stable-0002-x86-cpuid-support-LFENCE-always-serialising-CPUID-bi.patch being backported for speculation reasons.  Before that patch, 0x8000001c was reported as the max extended leaf, so userspace wouldn't have gone looking at 0x8000001d.

**Comment by andyhhp** [comment]
Actually, there is also a bug in whatever piece of userspace is looping here.  The AMD manual states that the contents of 0x8000001d and 0x8000001e are only valid if the TOPOEXT feature (CPUID.80000001.edx[22]) is visible.  Xen hides this feature, so userspace shouldn't go looking.

**Comment by DemiMarie** [comment]
> Actually, there is also a bug in whatever piece of userspace is looping here. The AMD manual states that the contents of 0x8000001d and 0x8000001e are only valid if the TOPOEXT feature (CPUID.80000001.edx[22]) is visible. Xen hides this feature, so userspace shouldn't go looking.

Time to be mean and inject #GP into the buggy guest userspace?  (Only half-joking.)

**Comment by andyhhp** [comment]
@fosslinux Any chance I can have a name & email address for a Reported-by tag on the upstream fix?

**Comment by fosslinux** [comment]
I don't use my real name (at least at this time). So if `fosslinux <fosslinux@aussies.space>` is OK, please use that.

**Comment by emacsomancer** [comment]
Is there any current workaround for this issue?

**Comment by DemiMarie** [comment]
@marmarek time to pop out a new Xen package?
