### ISSUE TITLE
no network with qubes-vm-kernel-latest (5.16.18)

### ISSUE THREAD

**Issue by b90g** [QubesOS/qubes-issues#7397]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

4.1

5.16.18-1

### Brief summary

sys-firewall isnt able to ping IPv4 addresses although sys-net connected to a network and reaches the same adress. (9.9.9.9)

sys-firewall is connected to sys-net

### Steps to reproduce

install kernel-latest for qubes-vms (5.16.18)

### Expected behavior

Having everything workin as it were in 5.16.15

### Actual behavior

offline, no ICMP, no TCP, nothing. :(

-----

switching the default kernel to an older version gets me connected, i tested on 2 different systems

**Comment by marmarek** [comment]
Can you see if kernel in sys-net complains about anything. It may be some driver-specific issue, I cannot reproduce it on my system.

**Comment by b90g** [comment]
I updated the Issue, it turned out sys-firewall isnt able to connect to anything when they run on 5.16.18. 

its fedora-35 template.

should i paste dmesg or anything? i am not a developer, sorry :/

**Comment by pgerber** [comment]
Looks like qubes-iptables.service fails on that kernel:

```
Mar 31 18:35:57 debian-11 systemd[1]: Starting Qubes base firewall settings...
Mar 31 18:35:57 debian-11 qubes-iptables[973]: iptables: Applying firewall rules:
Mar 31 18:35:57 debian-11 qubes-iptables[978]: iptables-restore v1.8.7 (nf_tables):
Mar 31 18:35:57 debian-11 qubes-iptables[978]: line 13: RULE_APPEND failed (No such file or directory): rule in chain PREROUTING
Mar 31 18:35:57 debian-11 qubes-iptables[978]: line 13: RULE_APPEND failed (No such file or directory): rule in chain PREROUTING
Mar 31 18:35:57 debian-11 qubes-iptables[978]: line 13: RULE_APPEND failed (No such file or directory): rule in chain POSTROUTING
Mar 31 18:35:57 debian-11 qubes-iptables[978]: line 13: RULE_APPEND failed (No such file or directory): rule in chain POSTROUTING
Mar 31 18:35:57 debian-11 qubes-iptables[978]: line 13: RULE_APPEND failed (No such file or directory): rule in chain POSTROUTING
Mar 31 18:35:57 debian-11 qubes-iptables[973]: FAIL
Mar 31 18:35:57 debian-11 systemd[1]: qubes-iptables.service: Main process exited, code=exited, status=1/FAILURE
Mar 31 18:35:57 debian-11 systemd[1]: qubes-iptables.service: Failed with result 'exit-code'.
Mar 31 18:35:57 debian-11 systemd[1]: Failed to start Qubes base firewall settings.
```

Works fine again when I downgrade to the previous kernel.

**Comment by crat0z** [comment]
Can confirm this is an issue. All VMs that start with 5.16.18-1 kernel will have broken iptables

**Comment by brendanhoar** [comment]
Confirmed in 4.0 as well.

**Comment by 51lieal** [comment]
maybe debian issue? my fedora-35 minimal is fine.

**Comment by b90g** [comment]
> maybe debian issue? my fedora-35 minimal is fine.

using fedora-35 (both disposable with vanilla config)
