### ISSUE TITLE
Ocasionally, in some rare cases, no MASQUERADE rule created in the NetVM

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#740]
**Reported by marmarek on 16 Jun 2013 12:20 UTC**
Sometimes iptables in netvm lack of MASQUERADE rule, which result in sending packets with firewallvm source IP to outside world. The packets most likely will be filtered by first router/firewall (so network traffic got lost).

This happen only sometimes, most likely at resume from s3 sleep. Details: https://groups.google.com/d/topic/qubes-users/V5QXOW7Y7zg/discussion

Perhaps related to #42?

Migrated-From: https://wiki.qubes-os.org/ticket/740

**Comment by unman** [comment]
@andrewdavidwong We have been unable to reproduce this issue in 3.2
