### ISSUE TITLE
qubes-rpc: @dispvm doesn't work as source

### ISSUE THREAD

**Issue by 3hhh** [QubesOS/qubes-issues#7406]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
4.1

### Brief summary

If `@dispvm` is used in the sourc esection of a qrexec policy, the requests are always denied.

### Steps to reproduce
Set a qrexec-policy such as
```
example.qrexec          *   @dispvm                  @default    allow target=somevm
```
or
```
example.qrexec         *   @dispvm:template                  @default    allow target=somevm
```

### Expected behavior
Requests from the template `template` work.

### Actual behavior

All requests are denied.

**Comment by marmarek** [comment]
It works as intended, see https://www.qubes-os.org/doc/qrexec/#qubes-rpc-administration
> @dispvm means “new VM created for this particular request,” so it is never a source of request

**Comment by 3hhh** [comment]
Thanks for the hint.

So ***@***.***:DispVM` does the job instead as source. It's just hard to filter for a specific template VM with that syntax.
