### ISSUE TITLE
Always use a FICLONE-capable filesystem in dom0

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#7415]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

R4.1

### Brief summary

Currently, a default install with LVM thin provisioning creates an ext4 filesystem for dom0.  This is bad because ext4 does not support FICLONE, so the reflink pool does not work.

### Steps to reproduce

Install Qubes OS using R4.1 ISO

### Expected behavior

varlibqubes pool uses reflink driver

### Actual behavior

varlibqubes pool uses deprecated file driver

**Comment by marmarek** [comment]
No, the solution is different: do not create varlibqubes pool in this case. With current LVM layout there is no space to store VMs there anyway.

**Comment by brendanhoar** [comment]
@DemiMarie - if you're trying to do what I think you're trying to do...

...you're going to have to create some thin-LVs, put file systems on them, and then mount them in dom0.

B

**Comment by DemiMarie** [comment]
Closing on account of @marmarek’s comment.
