### ISSUE TITLE
Sometimes qvm-firewall rules stop working for multiple qubes

### ISSUE THREAD

**Issue by juodumas** [QubesOS/qubes-issues#7418]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

4.0

### Brief summary

1. I have this netvm configuration: `my-vm -> sys-vpn -> sys-firewall -> sys-net`
2. In dom0 I use `qvm-firewall sys-vpn ...` to only allow traffic to the VPN server and drop everything else.
3. Sometimes the firewall rules stop working and `sys-vpn` can access everything (or partially).
4. I can fix the issue by fiddling around (calling `qvm-firewall reset my-vm` and re-adding my rules or rebooting).
5. When the issue appears, it affects multiple netvms that have custom rules added by `qvm-firewall`, not only `sys-vpn`.

All Qubes are running Debian bullseye.

Right now my setup is in such a state, so I would like to do some debugging to figure out the issue without rebooting/resetting the firewall, but I am not sure where to start.

### Steps to reproduce

N/A - normally this is working (fresh reboot, freshly added firewall rules). But it stops working after a while, maybe after a few suspend/resume cycles.

### Expected behavior

When `qvm-firewall sys-vpn` has a single drop everything rule, so I expect everything coming from `sys-vpn` to be dropped.

### Actual behavior

1. **dom0**:
   ```
   qvm-firewall sys-vpn
   NO  ACTION  HOST  PROTOCOL  PORT(S)  SPECIAL TARGET  ICMP TYPE  EXPIRE  COMMENT
   0   drop
   ```
* **sys-vpn**:
   ```
   user@sys-vpn$ ping -c1 1.1.1.1
   PING 1.1.1.1 (1.1.1.1) 56(84) bytes of data.
   64 bytes from 1.1.1.1: icmp_seq=1 ttl=55 time=4.80 ms

   --- 1.1.1.1 ping statistics ---
   1 packets transmitted, 1 received, 0% packet loss, time 0ms
   rtt min/avg/max/mdev = 4.800/4.800/4.800/0.000 ms
   user@sys-vpn$ curl -I https://google.com
   HTTP/2 301
   location: https://www.google.com/
   <...>
   ```

**Comment by marmarek** [comment]
Check status and logs of `qubes-firewall` service in sys-firewall (or wherever sys-vpn is connected right now). At least `sudo systemctl status qubes-firewall`, but looking more into `journalctl` may be useful too.

**Comment by juodumas** [comment]
Thanks. I see 3 issues:

1. qubes-firewall cannot resolve a hostname and it tries to show a notification by launching `runuser notify-send`. But PATH is wrong (at least for Debian bullseye) here https://github.com/QubesOS/qubes-core-agent-linux/blob/f5938cbd23ade4fef0ed79d23ac0239d72929762/qubesagent/firewall.py#L201 because runuser is in `/sbin/runuser` on Debian.
2. Wrong PATH causes `FileNotFoundError: [Errno 2] No such file or directory: 'runuser'` exception, but the code only handles `subprocess.SubprocessError` (it should probably handle `Exception`. This causes qubes-firewall to crash.
3. The notification says "blocking traffic", but it's unclear which VM is affected. Maybe this is by design.

**Comment by juodumas** [comment]
> At least in my debian-11 template /sbin is a symlink to /usr/sbin. Did you maybe modify that?

Interesting. No I didn't modify this. But my Debian has been dist-upgraded a few times from some old template. Anyway, "official" Docker bullseye image does not have the symlink either:
```
>>docker run -it --rm debian:bullseye-slim ls -ld /sbin /usr/sbin
drwxr-xr-x 2 root root 4096 Mar 28 00:00 /sbin
drwxr-xr-x 2 root root 4096 Mar 28 00:00 /usr/sbin
```

> It should mention the IP of the affected VM.

Ah, true, it does mention the IP. Hard to notice given that the notification takes the whole screen and I rarely have to think about VM IPs.

**Comment by 3hhh** [comment]
I see. Would you mind sending a PR then?
