### ISSUE TITLE
Slow and unusable on 11. Intel gen CPU

### ISSUE THREAD

**Issue by wkadh5** [QubesOS/qubes-issues#7420]
### Qubes OS release

Qubes R4.1.0-x86_64

### Brief summary

After installing Qubes OS 4.1 (which took really long)
and updating it, I noticed that after logging in, the system takes
a really long time to boot up sys-net, sys-firewall etc.. 

Further investigations lead to the conclusion that
the system is so slow that its usage its useless.
E.g. startup and usage from a disp vm is barely possible
and takes a long time.

Hardware specs:
Intel Core i7-1165G7
(Intel Iris Xe Graphics G7)
(64 GB RAM, 2TB SSD)

### Steps to reproduce

Installing Qubes R4.1 on the same hardware
(especially this CPU: Intel Core i7-1165G7) 

### Expected behavior

It should work as expected without beeing that slow on this hardware
(on older hardware it runs flawlessly - also I tried using Fedora 35 WS on the new hardware and it worked as expected, so I think the hardware is working)

### Actual behavior

System is slow and unresponsive.

Please let me know if you need any logs that can be helpful to you.

**Comment by TNTBOMBOM** [comment]
> Hardware specs:
> Intel Core i7-1165G7
> (Intel Iris Xe Graphics G7)
> (64 GB RAM, 2TB SSD)

Good but not enough check: 

https://www.qubes-os.org/doc/system-requirements/#minimum

Vt-d (**Mandatory**), Vt-x (**Mandatory**), TPM (optional but good), Disable HyperThreading (optional but good if you have this option in your BIOS)

**Comment by brendanhoar** [comment]
This page says both vt-x and vt-d are "Yes":

https://www.intel.com/content/www/us/en/products/sku/208662/intel-core-i71165g7-processor-12m-cache-up-to-4-70-ghz/specifications.html

B

**Comment by crat0z** [comment]
Probably related to #6411, have you tried using the latest kernels?

**Comment by andrewdavidwong** [comment]
Duplicate of #7380?

**Comment by wkadh5** [comment]
@crat0z I will try that and give feedback - thanks

@andrewdavidwong I read that issue and on my system I dont have those redrawing problems.

**Comment by wkadh5** [comment]
So I found the problem.
The kernel did not do the trick, but it was a rather simple issue - the power saving management in the BIOS was on (this somehow led to Qubes beeing slow (Xen?))  and I switched it to performance mode. Now it works flawlessly. 
Thank you for your time.
