### ISSUE TITLE
Recursive qvm-shutdown

### ISSUE THREAD

**Issue by ahmedalsudani** [QubesOS/qubes-issues#7427]
Note: I'd be more than happy to make this change. Just checking that the proposed solution is ok with the team before I submit a PR.

### The problem you're addressing (if any)

It's painful to shutdown a network qube and its connected VMs.

The user currently needs to run `qvm-shutdown --wait sys-net sys-firewall <all downstream VMs>`

### The solution you'd like

Running `qvm-shutdown --recursive sys-net` finds all networks qubes and queues them all for shutting down.

Note:

- In my vision, `--recursive` implies `--wait` and that confirmation is required.
- There is a flag `-y/--yes` that skips confirmation (optional)

### The value to a user, and who that user might be

This change would make shutting down a network VM and its connected VMs trivial whereas it now requires awareness of the dependency graph.

**Comment by GWeck** [comment]
Shutting down sys-net via the Qube Manager already does this recursively. Maybe this functionality is only missing from the CLI and thus could be fixed without too much effort.

**Comment by ahmedalsudani** [comment]
> Shutting down sys-net via the Qube Manager already does this recursively. Maybe this functionality is only missing from the CLI and thus could be fixed without too much effort.

Thanks--it's been a long time since I last used the Qube Manager so I was not aware.

This issue is referring to the qvm-shutdown cli.

**Comment by ahmedalsudani** [comment]
> It's also worth noting that if the desire is to shut down _only_ sys-net, it's not necessary to shut down any other connected qubes. Instead, you can simply switch sys-firewall's net qube to "none" first. This can be handy when you just want to restart sys-net without having to restart everything.

Yeah, I'm aware of that and use it when only the network VM needs to be restarted.

This switch would be useful for me because I have something along the lines of

```
sys-net
  ↑
sys-vpn-work
  ↑
sys-firewall-mirage-work
  ↑
sys-firewall-work
  ↑
dev-work | web-work | ...
```

When I'm done with work, I shut down all my work VMs. Adding recursive would make it easier to shut them all down without keeping track as the VMs change.

It sounds like you are not against the idea so I'll start playing with the qvm-shutdown script and create a PR once this is ready.

**Comment by SaswatPadhi** [comment]
As @GWeck pointed out, Qube Manager already supports this. However, the Qubes notification tray doesn't. Selecting "Shutdown" from the context menu for the VM there doesn't propagate the shutdown recursively. It would be nice to make the tray icon consistent with Qube Manager. Any reason not to?

I think the `--recursive` cmdline flag would be nice to trigger the Qube Manager style behavior from command line (or a script).

**Comment by alimirjamali** [comment]
Related (essentially the same issue): 

https://github.com/QubesOS/qubes-issues/issues/3757
