### ISSUE TITLE
Qubes openQA - Whonix/updates-status broken

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#7428]
Due to a major Whonix / Kicksecure source code split in process...

github.com/Whonix/updates-status

> The repository updates-status has been retired and cannot be reused.

Github does not let me re-create that repository.

Will contact support now.

**Comment by adrelanos** [comment]
github support swiftly removed the "retirement" status.

https://github.com/Whonix/updates-status has been re-created.

Does this solve this issue? Will Qubes openQA bot continue posting or some re-setup required?

**Comment by marmarek** [comment]
Should work fine, we'll see on Wednesday. BTW, if you'd prefer those test reports posted somewhere else, let me know. Another repo is trivial, but gitlab or email should be possible too.

**Comment by adrelanos** [comment]
Since https://github.com/Whonix/updates-status/issues/1 was created it works fine.
