### ISSUE TITLE
Adding some trustworthy minimal windows enviroment just for installing BIOS updates

### ISSUE THREAD

**Issue by Szewcson** [QubesOS/qubes-issues#7430]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### The problem you're addressing (if any)
Installation of BIOS updates for many manufacturers only supporting Windows. Sometimes it is possible to make some workaround, but even then it is a task to high experienced users. Since BIOS updates are critical from security point of view (most of them are security fixes for Intel ME firmware etc.) I think Qubes should provide some simple mechanism that make such update possible.

### The solution you'd like
Adding some minimal windows boot environment with possibility to pass to it BIOS updater executable from AppVM

### The value to a user, and who that user might be
Universal solution to regular updating BIOS firmware in the simple way. It will be security gain to all users.

**Comment by TNTBOMBOM** [comment]
This is not Qubes or generally any GNU/Linux issue to solve, If you bought a PC from stupid manufacture blame the stupid manufacture for not allowing their BIOSs updates through GNU operating systems. 

BIOSs you are referring to are proprietary software (coreboot or POWER-PC are better open/free software replacements) which are faraway to consider them secure/malware free software.  (Qubes certified PCs are with coreboot, POWER not yet supporting Xen only KVM) 

Intel ME is a security hole by itself no updates gonna solve ME issues unless removed/disabled completely. (sadly not always possible)

I think if there is a category called rejected/wont fix/cant fix this is suitable for this ticket.

https://www.whonix.org/wiki/Reporting_Bugs#Forum_Issue_Tracker_Labels

**Comment by DemiMarie** [comment]
@TNTBOMBOM I agree that this should be “won’t do”, though for different reasons.  Creating a secure Windows environment is very difficult, and since it would not be redistributable it would need to be regenerated locally on each person’s machine.  Furthermore, future Windows changes would likely break it.
