### ISSUE TITLE
Critical - Fedora 35 Networking Fail with latest update

### ISSUE THREAD

**Issue by rootnoob** [QubesOS/qubes-issues#7439]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
R4.1 latest

### Brief summary
Fedora 35 based templates succesfully forward networking traffic but no in-vm network applications are working. I guess it's a dns issue.
Ping, outputs
‘Temporary failure in name resolution’.

This has made all my fedora35 templates unusable, I've had to temporarily switch to debian.

### Steps to reproduce
Update fedora-35 templates to latest.

### Expected behavior
Networking should work.

### Actual behavior
Network is still forwarded to other vms (tested by switching sys-firewall to fed35-dvm, no issue forwarding to sys-net), but cannot access the web.

**Comment by DemiMarie** [comment]
This appears to be a duplicate of #7429.  If it isn’t, please leave a comment so that the team can take a closer look.
