### ISSUE TITLE
UTF-8 characters cannot be displayed on Whonix VM

### ISSUE THREAD

**Issue by Che15ea** [QubesOS/qubes-issues#7445]
### Qubes OS release
4.1.0(with latest update)
Whonix 16

### Brief summary
UTF-8 characters, like Japanese, Chinese, Korean, cannot be displayed on Whonix VM system and apps(except Tor Browser).
Like that: https://ibb.co/mJGF9js
Thank you!

**Comment by TNTBOMBOM** [comment]
Did you follow these instructions here: 

https://www.kicksecure.com/wiki/Language
https://www.kicksecure.com/wiki/Keyboard_Layout

**Comment by Che15ea** [comment]
> Did you follow these instructions:
> 
> https://www.kicksecure.com/wiki/Language https://www.kicksecure.com/wiki/Keyboard_Layout

Thanks for your reply!
I am concerning that setting up so may change the default fingerprint of the environment and compromise the anonymity of the OS.

**Comment by DemiMarie** [comment]
Should this be reported on the Whonix forums instead?

**Comment by TNTBOMBOM** [comment]
yes

**Comment by TNTBOMBOM** [comment]
Further details not related to the issue above please ask in the forums:

https://forums.whonix.org/

**Comment by andrewdavidwong** [comment]
Closing as "not our bug" (the Qubes OS Project does not develop the software that is causing this bug). If anyone believes this resolution is a mistake, please leave a comment, and we'll be happy to take another look. Thank you.

Related FAQ: [Why don’t you fix upstream bugs that affect Qubes OS?](https://www.qubes-os.org/faq/#why-dont-you-fix-upstream-bugs-that-affect-qubes-os)
