### ISSUE TITLE
Kicksecure  inside Debian Template sdwdate qrexec Denied message

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#7447]
Installing Kicksecure inside Debian Template (Following [distro-morphing](https://www.kicksecure.com/wiki/Debian) instructions) the Appvm which is based on kicksecure template will give tons of the same error reported above: (The Appvm called I2P)

![kicksecurecallsyswhonix](https://user-images.githubusercontent.com/11895339/163480499-54b5b0ec-e932-4d67-b812-d42572295f5b.png)

Any operation using the terminal/command line like e.g remove or install something it will regenerate similar messages. 

(This can be reproduced in StandaloneVM based on Debian then changed to Kicksecure)

_Originally posted by @TNTBOMBOM in https://github.com/QubesOS/qubes-issues/issues/7013#issuecomment-1099649653_

**Comment by adrelanos** [comment]
Status of [Kicksecure](https://www.kicksecure.com) [inside Qubes](https://www.kicksecure.com/wiki/Qubes):
https://www.kicksecure.com/wiki/Qubes#Template

Related Qubes qrexec source code file:
https://github.com/QubesOS/qubes-core-admin-addon-whonix/blob/master/qubes-rpc-policy/80-whonix.policy

qrexec policy line which is causing this:

    whonix.NewStatus     *         @anyvm            @anyvm            deny

Kicksecure uses sdwdate:
https://www.kicksecure.com/wiki/Sdwdate

qrexec polcy line which is preventing this for Qubes-Whonix:

    whonix.NewStatus     *         @tag:anon-vm      @tag:anon-gateway allow  autostart=no

It's prevented in Qubes-Whonix becuase these VMs have qrexec tag `anon-vm` added by https://github.com/QubesOS/qubes-core-admin-addon-whonix.

How should Kicksecure-Qubes sdwdate support be fixed in Qubes dom0 qrexec policy?

In absence of a Kicksecure-Qubes template and Qubes dom0 package qubes-core-admin-addon-kicksecure that seems difficult.

For sure we shouldn't re-use the tag `anon-vm`.

Telling users to manually add any tags seems cumbersome.

Changing the default `deny` to `allow` I guess also wouldn't be acceptable?

Should Qubes dom0 package qubes-core-admin-addon-kicksecure be invented? As long as there's no KIcksecure-Qubes template maintainer that I guess wouldn't work anyhow.

For tracking purposes:
This has just been fully diagnosed but directions from Qubes are required on how it could be fixed.

**Comment by DemiMarie** [comment]
Why is a non-Whonix VM calling `whonix.NewStatus` to begin with?

**Comment by adrelanos** [comment]
This is primarily a Qubes dom0 issue.

Suggested ticket tags:

* `C: Kicksecure` - New tag? If Qubes is interested in that.
* `P: default`
* `T: bug`

> Why is a non-Whonix VM calling `whonix.NewStatus` to begin with?

Kicksecure uses sdwdate.

**Comment by DemiMarie** [comment]
> > Why is a non-Whonix VM calling `whonix.NewStatus` to begin with?
> 
> Kicksecure uses sdwdate.

Is renaming the service an option?  `whonix.NewStatus` (a) implies that the service is Whonix-specific and (b) provides no indication that sdwdate is involved.  As far as tags, I would be fine with using `sdwdate-client` or similar.

**Comment by adrelanos** [comment]
> > > Why is a non-Whonix VM calling `whonix.NewStatus` to begin with?
> > 
> > 
> > Kicksecure uses sdwdate.
> 
> Is renaming the service an option?

Yes, sure.

However, that file is still part of Qubes dom0 package `qubes-core-admin-addon-whonix` which still would't be 100% clean but might be acceptable?

Even if renamed, I still don't see how we can fix the issue reported here without changing the sdwdate qrexed default from deny to allow or without a Kicksecure-Qubes template maintainer.

**Comment by marmarek** [comment]
Lets first try to figure out what should be the final goal, and only then - how.

> Installing Kicksecure inside Debian Template (Following [distro-morphing](https://www.kicksecure.com/wiki/Debian) instructions) the Appvm which is based on kicksecure template will give tons of the same error reported above: (The Appvm called I2P)

Ok, so the user did just this: took Debian template and morphed into Kicksecure. No Whonix is involved or even installed. What should happen?

**Comment by adrelanos** [comment]
Kicksecure VMs are primarily used non-torified, i.e. over clearnet (or VPN). That's the main use case. Some users might torify them for some reason but that would be the corner case. Torified Kicksecure makes little sense - because in that case using Whonix would be better.

> Lets first try to figure out what should be the final goal, and only then - how.
> 
> > Installing Kicksecure inside Debian Template (Following [distro-morphing](https://www.kicksecure.com/wiki/Debian) instructions) the Appvm which is based on kicksecure template will give tons of the same error reported above: (The Appvm called I2P)
> 
> Ok, so the user did just this: took Debian template and morphed it into Kicksecure. No Whonix is involved or even installed. What should happen?

Good question. I guess...

1)

The Kicksecure VM should be allowed to qrexec send `whonix.NewStatus` (to be renamed in a generic way) to sdwdate-gui running inside `@tag:anon-gateway`.

It's non-ideal since the Tor inside `@tag:anon-gateway` (most likely `sys-whonix`) doesn't really handle the Tor connections used by sdwdate. `@tag:anon-gateway` is just "coincidentally" the only place where sdwdate-gui is running inside Qubes as we don't know/have any more appropriate / more centralized place for it.

For Kicksecure outside of Qubes none of this is an issue. It has its own desktop environment so using its own sdwdate-gui is appropriate. How to best implement this in Qubes is a good question.

2)

Then also the `@tag:anon-gateway` should be allowed to send `whonix.SdwdateStatus` and `whonix.GatewayCommand` (both to be renamed in a generic way) to the Kicksecure VM.

That is until a cleaner solution https://phabricator.whonix.org/T930 is implemented which would abolish the need for a two-way qrexec calls.

**Comment by marmarek** [comment]
What's the purpose of this service? Is it only reporting status to be displayed in a single place (instead of separate icon for each qube)? Or is it also assisting with the actual time synchronization? If the former, maybe the solution for the case without Whonix is to run sdwdate-gui locally in the Kicksecure VM? May not be optimal if there are many of them, though...

**Comment by adrelanos** [comment]
> What's the purpose of this service? Is it only reporting status to be displayed in a single place (instead of separate icon for each qube)?

Yes, "mostly" only reporting the status and [...]

> Or is it also assisting with the actual time synchronization?

[...] "Not directly." Except for usability. It offers a few handy buttons buttons

* Show sdwdate status
* Open sdwdate's log
* Restart sdwdate
* Stop sdwdate

sdwdate-gui homepage:
https://www.kicksecure.com/wiki/Sdwdate-gui

screenshot of that menu:
https://www.kicksecure.com/wiki/File:Sdwdate2.png

> If the former, maybe the solution for the case without Whonix is to run sdwdate-gui locally in the Kicksecure VM?

Yes, that would of course work.

> May not be optimal if there are many of them, though...

Indeed. It's non-ideal.

**Comment by adrelanos** [comment]
Thoughts?

**Comment by DemiMarie** [comment]
Not sure

**Comment by b-bondarenko** [comment]
Greetings.

Any update on this issue, or maybe any clues on how to deal with it while the fix is not in place? 
I thought about applying tag `anon-vm` to the kicksecure AppVM may fix the problem, but I was wondering if that's an acceptable solution and wouldn't it cause any other problems.

Thanks in advance.

**Comment by Nurmagoz** [comment]
I dont think this behavior fixed yes?

**Comment by ArrayBolt3** [comment]
On the Qubes side, we shouldn't have to worry about what happens if a Kicksecure qube is in use and no Whonix qubes exist on the system. sdwdate-gui uses a configuration file to determine which VM it should try to talk to in order to show sdwdate information to the user, and by default that VM is set to `sys-whonix` (the user can change it if that doesn't work for them). It should in theory be doable to make it so that if the target VM isn't available, an sdwdate-gui instance is launched in the VM itself rather than trying to communicate with a remote sdwdate-gui instance. That can be done without needing to change any code on the Qubes side I believe.

What we probably *should* change on the Qubes side is use tags other than `anon-vm` and `anon-gateway` for this. I believe (though haven't tested it yet) that a non-Whonix VM could be used as the sdwdate-gui VM, and we already see that a non-Whonix VM can be the one trying to talk to the sdwdate-gui VM to show sdwdate info. I'd add an extra set of tags (not sure what to name them yet) and use those for that purpose. We probably also should rename the service so that it doesn't incorrectly appear Whonix-specific.

**Comment by ArrayBolt3** [comment]
I believe I have all needed changes for fixing this in flight on both the Kicksecure/Whonix and Qubes OS sides. On the Kicksecure/Whonix side:

* https://github.com/ArrayBolt3/sdwdate-gui/tree/arraybolt3/qubes-redesign
* https://github.com/ArrayBolt3/anon-gw-base-files/tree/arraybolt3/sdwdate-gui
* https://github.com/ArrayBolt3/kicksecure-base-files/tree/arraybolt3/sdwdate-gui

On the Qubes OS side:

* https://github.com/QubesOS/qubes-issues/issues/10020
* https://github.com/QubesOS/qubes-core-admin-addon-whonix/pull/21

Once all of these are merged and published for Qubes R4.3, this bug can be closed.

**Comment by ArrayBolt3** [comment]
This is fixed in R4.3, so this can be closed.
