### ISSUE TITLE
Devices list empty in sys-gui-gpu

### ISSUE THREAD

**Issue by Kenny606** [QubesOS/qubes-issues#7451]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
Qubes 4.1 , Xen 4.14.4 , Kernel 5.10.104.fc32 qubes x86_x64
dom0, Fedora-34 and Fedora-34-xfce templates up to date.

### Brief summary
After setting up sys-gui-gpu my “devices” icon is there but it’s blank, I just see a tiny empty bubble when I click on it.

### Steps to reproduce
Install and activate sys-gui-gpu and attempt to view usb devices in the GUI domain.

### Expected behavior
View list of attached or internal/external USB devices and passthrough as needed to VM's

### Actual behavior
Just an empty list with no devices,
In dom0 it's fine and I see all my devices. Normally I would see my built-in mic and webcam at a minimum and anything else I attach of course.

I also tried some external devices in the gui domain:
USB storage devices nothing
USB wireless keyboard/mouse receiver was the only sign of life I’ve seen I got a message: “Denied qubes.InputKeyboard from sys-usb to dom0”
So sys-usb is talking to sys-gui-gpu on some some level.
I verified the sys-usb was using the qubes default_guivm (sys-gui-gpu) and sys-gui-gpu's guivm is blank.

**Comment by marmarek** [comment]
What happens if you execute `qvm-usb` or `qvm-device mic` in sys-gui-gpu? Do you see any policy denial notification?

**Comment by Kenny606** [comment]
Qvm-usb doesn't seem to exist. However I executed all of these with and without a flash drive.
qvm-device mic ls
qvm-device usb ls
qvm-device block ls
qvm-device testclass ls
All of them gave me "Failed to list 'xxx' devices, this device type does not exist or you do not have access to it."  xxx is of course whatever class I asked for.
No other visible notifications beyond that message.
I ran them with --verbose as well hoping I may get more info for you but no luck.

The one that did work was "qvm-device pci ls" it took about 15 seconds of thinking but did bring up all pci devices.



________________________________

**Comment by marmarek** [comment]
Ok, I see, there is missing policy for those devices. See linked PR - you can add those lines to `/etc/qubes/policy.d/90-admin-default.policy` in dom0 and see if that helps. The file on your system will be much longer, because most of it is generated - you can put those extra lines at the end.

**Comment by Kenny606** [comment]
Added by still the same result.
All the list commands I previously ran produce the same result and devices icon still empty.

I do notice after making the change sys-gui-gpu sits there for a good 10+ seconds now before my keyboard and touchpad come to life if that gives you any hints.

**Comment by Kenny606** [comment]
Thanks. I'll run an update tonight :)
If for some reason it still doesn't work I'll try recreating sys-gui-gpu and give it a clean slate post-update.

**Comment by ZYousef** [comment]
I'm having the same issues I've tried adding the missing policies to 90-admin-default.policy and also linked them to qubesd.sock with correspondent names in /etc/qubes-rpc but it didn't work.

I can list qvm-device pci ls
but anything else fails with _this device type does not exist or you do not have access to it,_
