### ISSUE TITLE
sys-gui-gpu shutdown/restart commands result in blank screen

### ISSUE THREAD

**Issue by Kenny606** [QubesOS/qubes-issues#7452]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
Qubes 4.1 , Xen 4.14.4 , Kernel 5.10.104.fc32 qubes x86_x64
dom0, Fedora-34 and Fedora-34-xfce templates up to date.

### Brief summary
When I instruct the system to shutdown or restart from the log out menu all I end up with is a blank screen.
At no point will the system shutdown or restart. The commands appear to only affect the sys-gui-gpu VM and the GUI domain never comes back up upon restart

### Steps to reproduce
Set dom0 set to shutdown when I hitting the power button and sys-gui-gpu to ask.
Select log from the logout menu is sys-gui-gpu followed by shutdown or restart and the screen will simply go blank.

### Expected behavior
As it is a management domain I expect Qubes will shutdown and the laptop will power off or restart.

### Actual behavior
The screen will simply go blank presumably as sys-gui-gpu shuts down.
However the system never shuts down and if restarting the GUI domain never comes back up.

However qubes still appears to be up, specifically dom0. Since I have nothing to look at I can only base that on my observations and power button behavior as configured in dom0/sys-gui-gpu.
After giving it more than enough time in many tests.
I eventually tap the power button (not hold) and the system appears to shutdown cleanly in a normal amount of time with no issue.

**Comment by DemiMarie** [comment]
I’m not surprised at all; I suspect this simply has not been implemented yet.  Shutting down the whole system isn’t always the right thing to do, though, so this should be configurable.  For instance, one might need to restart sys-gui-gpu after a software update in its template.  In this case, restarting the whole system isn’t likely to be the best thing to do.  Ideally, sys-gui-gpu should automatically reconnect to the GUI agents it controls, but this, too, has not yet been implemented.

**Comment by marmarek** [comment]
Indeed, that part is not implemented yet.

I think we need a qrexec service for system power control (shutdown, reboot, maybe suspend too). But I'm not really sure how they should be integrated - as @DemiMarie said, shutting down the whole system with sys-gui-gpu isn't always the right thing to do.

**Comment by Kenny606** [comment]
If ultimately the plan is shutting down/suspending the GUI vm will dump you right into dom0 temporarily  then that's a good question. If not it seems like they should only be system wide actions.

Restart is though I don't know how customisable that logout window is. Maybe have two buttons Restart System and Restart GUI? You have a row of 3 and a row of 2 so one more would fit in nicely. That would definitely be a useful feature.


If the first paragraph is something bring considered and you can customize that logout window. Personally I would put two radio buttons at the top probably. To choose system or GUI (,or something to that effect).
At least that's the simplest thing I can think of UI wise.

Shutting down or suspending the GUI and getting over to dom0 to handle something would be cool but not sure how commonly it would be used so may not be worth the effort.


________________________________

**Comment by Kenny606** [comment]
FYI I hadn't noticed before or it slipped by mind. Currently if you hit restart since sys-gui-gpu never comes back to life you just end up with a blank screen and have to hard off the machine (hold down power button) zince Sys-Gui-GPU is still running dom0 won't pick up me hitting the power button.

Since I don't like to hard off with VM's running of course.
I just changed sys-gui to shutdown if I hit the power button as a work around. 
Just a handy setup for testing if I accidentally select restart, Then with one tap of power sys-gui-gpu shuts down then after a few seconds tap it again and dom0 intercepts it and does a graceful shutdown as well.
