### ISSUE TITLE
sys-gui-gpu Power Manager Icon and Notifications Missing

### ISSUE THREAD

**Issue by Kenny606** [QubesOS/qubes-issues#7453]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
Qubes 4.1 , Xen 4.14.4 , Kernel 5.10.104.fc32 qubes x86_x64
dom0, Fedora-34 and Fedora-34-xfce templates up to date.

### Brief summary
While in sys-gui-gpu the Power Manager icon is missing in the status tray and I get no notification such as battery charged, charger disconnected etc.

### Steps to reproduce
Install sys-gui-gpu

### Expected behavior
Visible Power manager icon with battery status and notifications about changes in power status as dom0 does.

### Actual behavior
The icon is not visible and all attempts to make it so have failed.
I have attempted to toggle the icon on and off as well as the notifications, I have also turned on logging for notifications and they are not recorded there either. I verified it was not not marked as hidden in panel manager.
When turning the icon on and off I can see all the tray icons flash as if something is being added but I end up with the same icons I started with.

**Comment by marmarek** [comment]
There is a proxy module ([dummy-psu](https://github.com/QubesOS/qubes-dummy-psu/)) specifically to transfer this information to sys-gui-gpu. Check if you see `qubes-psu-client` systemd service running in sys-gui-gpu.

@fepitre can you give some more debugging hints?

**Comment by Kenny606** [comment]
I see "module-load-dummy-psu-service"
Status: loaded/inactive/dead

However nothing under systemd




________________________________

**Comment by ben-grande** [comment]
@Kenny606 Can you test with the latest commit Marek did

- https://github.com/QubesOS/qubes-desktop-linux-xfce4/pull/30

It was only committed to Qubes R4.2.

**Comment by jmynes** [comment]
Affects 4.2, tested in `sys-gui` (haven't tried `sys-gui-gpu` yet)

**Comment by jmynes** [comment]
> There is a proxy module ([dummy-psu](https://github.com/QubesOS/qubes-dummy-psu/)) specifically to transfer this information to sys-gui-gpu. Check if you see `qubes-psu-client` systemd service running in sys-gui-gpu.
> 
> [@fepitre](https://github.com/fepitre) can you give some more debugging hints?

`sys-gui` has the qubes-service for `dummy-psu` enabled, per Qube Manager:
![Image](https://github.com/user-attachments/assets/06c532e1-0ee7-485e-8b22-97995d1a67d9)

However, if I run a console on `sys-gui`, then `systemctl` reports otherwise:
![Image](https://github.com/user-attachments/assets/a6592e20-3652-46f5-a4e6-b9dc7c01a999)

If I `grep` for `dummy` or `psu` instead of `qubes`, I get no results

**Comment by jmynes** [comment]
In `sys-gui`, here is the output of `sudo systemctl status qubes-psu-client@sys-gui.service`:
```
○ qubes-psu-client@sys-gui.service - Dummy power supply client service
     Loaded: loaded (/usr/lib/systemd/system/qubes-psu-client@.service; enabled; preset: enabled)
    Drop-In: /usr/lib/systemd/system/service.d
             └─10-timeout-abort.conf, 50-keep-warm.conf
     Active: inactive (dead)
  Condition: start condition unmet at Fri 2025-07-04 00:45:42 CST; 21min ago
             └─ ConditionPathExists=/var/run/qubes-service/dummy-psu@sys-gui was not met

Jul 04 00:45:42 sys-gui systemd[1]: qubes-psu-client@sys-gui.service - Dummy power supply client service was skipped because of an unmet condition check (ConditionPathExists=/var/run/qubes-service/dummy-psu@sys-gui).
```

There is no `/var/run/qubes-service/dummy-psu@sys-gui` file, and thus we get an unmet condition check above
There is, however, a `/var/run/qubes-service/dummy-psu`

Conversely, there is a `qubes-psu-client@sys-gui.service`
But there is no `qubes-psu-client.service`

---

`sudo systemctl list-unit-files | grep dummy`:
```
module-load-dummy-backlight.service    disabled    enabled
module-load-dummy-psu.service          disabled    enabled
```
`sudo systemctl list-unit-files | grep psu-client`:
```
qubes-psu-client@.service              indirect    enabled
```

**Comment by ben-grande** [comment]
I see the power manager and notifications on OpenQA's R4.3 sys-gui-gpu: https://openqa.qubes-os.org/tests/184709#step/gui_keyboard_layout/55.

**Comment by marmarek** [comment]
It's fixed only with this PR (not merged yet): https://github.com/QubesOS/qubes-dummy-psu/pull/6
