### ISSUE TITLE
`dkms` builds failing with `kernel-latest-devel`

### ISSUE THREAD

**Issue by SaswatPadhi** [QubesOS/qubes-issues#7459]
### Qubes OS release

R4.1

### Brief summary

My `dkms` builds started failing after I upgraded the kernel to `5.17.4` to grab the fix for #7359:

### Steps to reproduce

1. Upgrade to `kernel-latest` and `kernel-latest-devel` version `5.17.4` from `current-testing` channel
2. `dkms build <module>/<version> -k 5.17.4-2.fc32.qubes.x86_64`

### Expected behavior

The modules build successfully, as they used to before the kernel upgrade.

### Actual behavior

```
DKMS make.log for ~~~~[redacted]~~~~ for kernel 5.17.4-2.fc32.qubes.x86_64 (x86_64)
Fri 22 Apr 2022 06:55:05 AM UTC
make: Entering directory '/usr/src/kernels/5.17.4-2.fc32.qubes.x86_64'
/bin/sh: -c: line 0: syntax error near unexpected token `('
/bin/sh: -c: line 0: `if [ "gcc (GCC) 10.3.1 20210422 (Red Hat 10.3.1-1)" != ""gcc (GCC) 10.3.1 20210422 (Red Hat 10.3.1-1)"" ]; then \'
make: *** [Makefile:1717: prepare] Error 1
make: Leaving directory '/usr/src/kernels/5.17.4-2.fc32.qubes.x86_64'
```

### Solution

The problem seems to be with bad quotes in `/usr/src/kernels/5.17.4-2.fc32.qubes.x86-64/Makefile`.

The following patch fixed the errors for me and my modules build fine again.

```patch
--- Makefile.old	2022-04-22 07:09:24.778016788 +0000
+++ Makefile.new	2022-04-22 07:08:57.535015977 +0000
@@ -1714,9 +1714,9 @@
 # now expand this into a simple variable to reduce the cost of shell evaluations
 prepare: CC_VERSION_TEXT := $(CC_VERSION_TEXT)
 prepare:
-	@if [ "$(CC_VERSION_TEXT)" != "$(CONFIG_CC_VERSION_TEXT)" ]; then \
+	@if [ "$(CC_VERSION_TEXT)" != $(CONFIG_CC_VERSION_TEXT) ]; then \
 		echo >&2 "warning: the compiler differs from the one used to build the kernel"; \
-		echo >&2 "  The kernel was built by: $(CONFIG_CC_VERSION_TEXT)"; \
+		echo >&2 "  The kernel was built by: "$(CONFIG_CC_VERSION_TEXT); \
 		echo >&2 "  You are using:           $(CC_VERSION_TEXT)"; \
 	fi
```

**Comment by fepitre** [comment]
I'm suspecting some upstream issue but I'll take a look.

**Comment by fepitre** [comment]
Note to myself: https://lore.kernel.org/lkml/20220307223231.608498-1-mst@redhat.com/T/

**Comment by SaswatPadhi** [comment]
Looks like this is fixed in 5.18.16.

**Comment by icequbes1** [comment]
@SaswatPadhi are `dkms` builds actually succeeding for you on 5.18.16?

While the quotes issue with `$CONFIG_CC_VERSION_TEXT` seems to be fixed, compiling out-of-tree modules with `make` complains about gcc plugin incompatibility:

> cc1: error: incompatible gcc/plugin versions
> cc1: error: failed to initialize plugin ./scripts/gcc-plugins/structleak_plugin.so

e.g., attempting to compile the [rtl8812au](https://github.com/aircrack-ng/rtl8812au) module:

```
$ make
make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/5.18.16-1.fc32.qubes.x86_64/build M=/home/user/QubesIncoming/disp3342/rtl8812au  modules
make[1]: Entering directory '/usr/lib/modules/5.18.16-1.fc32.qubes.x86_64/build'
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: gcc (GCC) 10.3.1 20210422 (Red Hat 10.3.1-1)
  You are using:           gcc (GCC) 11.3.1 20220421 (Red Hat 11.3.1-2)
  CC [M]  /home/user/QubesIncoming/disp3342/rtl8812au/core/rtw_cmd.o
cc1: error: incompatible gcc/plugin versions
cc1: error: failed to initialize plugin ./scripts/gcc-plugins/structleak_plugin.so
cc1: error: incompatible gcc/plugin versions
cc1: error: failed to initialize plugin ./scripts/gcc-plugins/latent_entropy_plugin.so
make[2]: *** [scripts/Makefile.build:289: /home/user/QubesIncoming/disp3342/rtl8812au/core/rtw_cmd.o] Error 1
make[1]: *** [Makefile:1838: /home/user/QubesIncoming/disp3342/rtl8812au] Error 2
make[1]: Leaving directory '/usr/lib/modules/5.18.16-1.fc32.qubes.x86_64/build'
make: *** [Makefile:2251: modules] Error 2
```

**Comment by SaswatPadhi** [comment]
Hi @icequbes1,

Yes, the `dkms` builds succeed for me on 5.18.16. The `gcc` that's installed by default on my Dom0 is 10.3.1 though.

Looking at your error message, it seems your Dom0 has `gcc` at version 11.3.1, which is causing the mismatch. If you don't want to downgrade to the default 10.3.1 `gcc`, then you could try setting the `IGNORE_CC_MISMATCH=1` environment variable and then building your module.

**Comment by SaswatPadhi** [comment]
Closing this issue since all 5.19.x and 6.0.x kernels from current-testing no longer trigger this.
