### ISSUE TITLE
Whonix Qube Restarts Itself

### ISSUE THREAD

**Issue by straussmaus** [QubesOS/qubes-issues#7460]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

4.1

### Brief summary

Several (perhaps all?) whonix-ws-16 Qubes will restart themselves after shutdown.  Repeatedly.

### Steps to reproduce
Open a Qube using the whonix-ws-16 template.

Close it using "sudo poweroff"

Watch it start itself.

Close it in Qube Manager.

Watch it start itself again... and again... and again.

Kill it.  Watch it start itself again.

This repeats for a while, then stops without any indication why.

### Expected behavior

A shutdown Qube should not start itself (and maybe not be *able* to start itself!)

### Actual behavior

Zombie Qube!

**Comment by marmarek** [comment]
Can it be related to #7013  ? Check in dom0's journalctl if you see qrexec calls directed at that qube. And also, if you see sdwdate shutdown call from it to sys-whonix.

**Comment by andrewdavidwong** [comment]
Sounds like this:

https://forum.qubes-os.org/t/whonix-qube-restarts-after-being-killed/1760

According to that thread, it's supposed to be fixed already.

@adrelanos [posted](https://forum.qubes-os.org/t/whonix-qube-restarts-after-being-killed/1760/28?u=adw) that it's most likely https://github.com/QubesOS/qubes-issues/issues/7169, which has already been closed for a while with updates in stable.

**Comment by straussmaus** [comment]
It does sound like that thread but my system is up to date and the issue is not fixed on mine.

Regarding #7169 I don't know where that code should be appended to so I can't test/verify if it is the same problem.

@marmarek https://github.com/QubesOS/qubes-issues/issues/7013 is an error message and regards DispVMs but this is a standalone whonix VM and there is no error, just a restart.

About journalctl, I'm sorry but I can't make it do it now for some annoying reason.  It does it all day every day.  Except now.  I've tried five times and I'll try to remember the next time it happens, and then to log in here.

**Comment by straussmaus** [comment]
@marmarek

The error happened again and here is the output of `sudo journalctl -xe | grep 'TheQube'`

```
Apr 28 03:30:37 dom0 qrexec[6915]: whonix.SdwdateStatus: sys-whonix -> TheQube: allowed to TheQube
Apr 28 03:30:38 dom0 qrexec[5063]: qubes.WindowIconUpdater: TheQube -> dom0: denied: qrexec-client failed
Apr 28 03:30:41 dom0 qubesd[5111]: vm.TheQube: Starting TheQube
```

**Comment by DemiMarie** [comment]
@straussmaus what version of `qubes-core-admin-addon-whonix` do you have in dom0?

**Comment by adrelanos** [comment]
User disappeared?

**Comment by andrewdavidwong** [comment]
Closing due to the prolonged lack of user response. If anyone is still affected by this issue, please leave a comment, and we'll be happy to reopen it. Thank you.
