### ISSUE TITLE
Some converted pdf to trusted dont show up 

### ISSUE THREAD

**Issue by Vageh1234** [QubesOS/qubes-issues#7464]
Some pdf converted to trusted don't appear after the process finishes, why this happens only with some pdf?

**Comment by andrewdavidwong** [comment]
Based on our [issue tracking guidelines](https://www.qubes-os.org/doc/issue-tracking/), this does not appear to be suitable for `qubes-issues`. We ask that you please post this on the [Qubes Forum or `qubes-users` mailing list](https://www.qubes-os.org/support/) instead. If, after reading our [issue tracking guidelines](https://www.qubes-os.org/doc/issue-tracking/), you believe we are mistaken, please leave a brief comment explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.
