### ISSUE TITLE
qvm-open-in-vm text filter does not match dispvm-names

### ISSUE THREAD

**Issue by rwiesbach** [QubesOS/qubes-issues#7466]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### The problem you're addressing (if any)
The suggestions in "open in" include
Disposable VM (%template-name%), for example "Disposable VM (dvm-internet)"

if I type a filter text , e.g. "inter" this filter text does not match the Disposable VM (dvm-internet)" - and even worse: it does match the dvm template! So if I type the text of the dvm-type that I would like to use I am lead to open it in the template instead of a dvm!

### The solution you'd like
The filter text should match the template name as well. I think there is no way that it makes sense that it does not. Furthermore it may be worth considering, that "open in" does hide all dvm templates (and only show dvm instances)

### The value to a user, and who that user might be
Possible intoxication/compromising of a dispVM-template would be avoided.

**Comment by rwiesbach** [comment]
Still handled this way in Q4.2

**Comment by rwiesbach** [comment]
Seems like this has been silently fixed and now both are matched (the template and a new dispvm from the template). It does not match existing dispVMs based on that template (which may be useful, but given it is named dispXYZ you would not necessarily expect it is matched.

As I suggested two years ago:
"Furthermore it may be worth considering, that "open in" does hide all dvm templates (and only show dvm instances)"

**Comment by alimirjamali** [comment]
Related (solved) issue: #8583

Hiding DVM Templates from Target choices could be implemented. I am not sure if this is a good idea.
Filtering to DVMs based in the DVM Template name could be also implemented. Again,  I am not sure if this is a good idea.

I believe the Title of this issue has to be changed as it does not reflect the request.

**Comment by rwiesbach** [comment]
> Hiding DVM Templates from Target choices could be implemented. I am not sure if this is a good idea. Filtering to DVMs based in the DVM Template name could be also implemented. Again, I am not sure if this is a good idea.

Why wouldn't this be a a good idea? It reduces the risk of a user accidentally "tainting" a DVM template with data that he explicitly wants to use in a DVM. I cannot think of a scenario it would be a bad idea.

Maybe the dialog could have a checkbox "hide DVM templates" so it would be clear to any user (not only the one that configured the system). Or if it is considered a bad idea in general (like connecting templates to a NetVM directly) it could have a warning next to the (in this scenario default-checked)  checkbox.

**Comment by marmarek** [comment]
What qubes are available in the list can be configured in global config, in the "file access" tab. If you don't want to copy files to DVM templates ever, you can add a rule denying it - it won't be listed then.
