### ISSUE TITLE
Old kernels may be used due to saved grub entries

### ISSUE THREAD

**Issue by 3hhh** [QubesOS/qubes-issues#7467]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
4.1

### Brief summary

`GRUB_DEFAULT=saved` in `/etc/default/grub` causes a once selected kernel to be reused again and again.

This is most unexpected as the [default setting](https://www.gnu.org/software/grub/manual/grub/html_node/Simple-configuration.html) is `GRUB_DEFAULT=0` which always selects the newest kernel. I guess this was set by upstream Fedora.

So a small mistype during Grub load may cause an old dom0 kernel to be used for a long time. This in turn may cause security issues / QSBs not to be resolved even though updates were installed.

In fact, I had just checked whether my kernel had the fixes for one of the QSBs and surprisingly noticed that I was using the oldest available kernel.

### Steps to reproduce

1. Select a kernel in GRUB.
2. Reboot.
3. Notice that it's still the active kernel in `uname -r`.

### Expected behavior

The newest kernel should always be the default.

### Actual behavior

A previously selected kernel is the default.

**Comment by DemiMarie** [comment]
@marmarek should this be fixed by editing `/etc/default/grub`?

**Comment by wowtendies** [comment]
I'm unable to reproduce this neither with kernel-5.15.94-1 nor with kernel-latest-6.0.12-1. After reboot active kernel is kernel-latest-6.1.12-1, the newest version I have

**Comment by 3hhh** [comment]
Well, what does your `GRUB_DEFAULT` in `/etc/default/grub` say?
Did you modify it?

Maybe Fedora switched back to the more reasonable default, idk and I cannot check anymore as I modified it manually.

**Comment by wowtendies** [comment]
It is `GRUB_DEFAULT=saved`, I haven't modified this file.

According to GRUB's docs, to save booted kernel for future runs as default option there should be `GRUB_SAVEDEFAULT=true` in config which I don't have.

**Comment by 3hhh** [comment]
> According to GRUB's docs, to save booted kernel for future runs as default option there should be `GRUB_SAVEDEFAULT=true` in config which I don't have.

Yes, and that _should_ require the invocation of `grub2-set-default` to make a change, which I don't recall having done, but cannot find it being automatically called by Fedora or Qubes either (maybe it's called as postinstall by rpm after a grub2 update or so, idk).

The only other inconvenience with `GRUB_DEFAULT=saved` I see is that users of `/boot` integrity protection such as `heads` will see warnings for `/boot/grub2/grubenv` from time to time whenever grub2 (or rather systemd after boot?) updates the saved entry, but that should also happen after unsuccessful boots etc.

So well, since no one can reproduce this anymore, feel free to close.

**Comment by andrewdavidwong** [comment]
> So well, since no one can reproduce this anymore, feel free to close.

Closing as "cannot reproduce" (we were unable to reproduce this issue). If anyone believes this is a mistake, or if anyone can reproduce the issue, please leave a comment, and we'll be happy to reopen this. Thank you.
