### ISSUE TITLE
External USB drive sometimes not detected

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#7470]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

Qubes 4.0

### Brief summary

An external USB drive is sometimes not detected by the system at all. Unplugging and replugging the drive does nothing. No messages in `journalctl` in sys-usb or dom0. No notifications. `qvm-block` remains empty. Rebooting dom0 usually fixes it, but only temporarily until it stops working again. The machine (ThinkPad T450s) is suspended each day, which may or may not be related to the problem.

### Steps to reproduce

1. Have a USB drive plugged in.
2. Start sys-usb.

### Expected behavior

sys-usb consistently detects the USB drive.

### Actual behavior

sys-usb sometimes detects the USB drive and sometimes does not. When it stops working, dom0 has to be restarted before it will work again.

Please let me know if there any other logs I can check.

**Comment by GWeck** [comment]
Sometimes I have the same effects on an HP 840 G4 EliteBook.

**Comment by DemiMarie** [comment]
@andrewdavidwong can you provide logs?  Feel free to send them to me directly if they are sensitive.

**Comment by andrewdavidwong** [comment]
> @andrewdavidwong can you provide logs? Feel free to send them to me directly if they are sensitive.

Sure, just let me know which logs and how to get them.

Also, FWIW, I've tried not using suspend (S3 sleep) anymore, and so far I haven't experienced this problem again.

**Comment by andrewdavidwong** [comment]
This still happens on occasion. When I look to see why my backup script failed, I see it's because Qubes failed to detect the USB external hard drive connected to `sys-usb`:

```
qvm-block: error: backend vm 'sys-usb' doesn't expose device 'sda'
```

@DemiMarie, could you tell me how to find the logs?

**Comment by DemiMarie** [comment]
@andrewdavidwong: `journalctl -b` in `sys-usb`
