### ISSUE TITLE
Thin pools use 256KiB block size by default

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#7478]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

Found on my system that dates back to R4.0.

### Brief summary

LVM thin pools currently use a block size of 256KiB, which penalizes snapshot-heavy workloads such as Qubes OS.

### Steps to reproduce

`dmsetup table /dev/mapper/qubes_dom0-pool00-tpool`

### Expected behavior

The chunk size is 64KiB

### Actual behavior

The chunk size is 256KiB

**Comment by brendanhoar** [comment]
I think it's relative to size of the thinpool itself at creation? Mine is 64KB on a 512GB SSD.

**Comment by DemiMarie** [comment]
Not sure.  @fepitre how big are your thin pools?
