### ISSUE TITLE
Boot failure on Thinkpad T430 with kernel-latest 5.17.4-2 and 5.17.5-1

### ISSUE THREAD

**Issue by icequbes1** [QubesOS/qubes-issues#7480]
### Qubes OS release
R4.1

### Brief summary
A Thinkpad T430 machine with Heads installed fails to boot kernels 5.17.4-2 and 5.17.5-1. Booting kernel 5.16.18-2 does not fail. There is no change in xen or xen/linux kernel arguments.

### Steps to reproduce

1. Enable current-testing repos in dom0 while booted into 5.16.18-2
2. Install kernel-latest 5.17.4-2, or 5.17.5-1
3. Reboot the machine

### Expected behavior

Normal system bootup prompting for disk passphrase.

### Actual behavior

Unresponsive machine after Heads kexec's the xen kernel. Backlight is on. Display is blank. Assuming display might be the issue, entering the disk passphrase blindly and pressing enter does not show any disk activity or any change in behavior. Hard reset is the only option. Maximum time waited for any output is 20 minutes.

### Notes

May be related to #7462 however that issue involves AMD while this machine is an Intel CPU without a discrete GPU.

**Comment by DemiMarie** [comment]
Looks like either a bug in Linux or a bug in Heads.  @tlaurion any ideas?

**Comment by icequbes1** [comment]
Additional analysis:

1. Xen is booting
2. Linux kernel is booting
3. Issue is likely graphics related: adding `nomodeset` does change boot behavior

Justification:

1. When performing an "insecure" boot from Heads which ignores signatures, Heads adds arguments to the linux kernel to turn the screen background red. For the non-booting kernels, the screen does turn red indicating that at least the linux kernel has started. Machine is still unresponsive.
2. When excluding the initramfs image from grub.cfg, the screen remains frozen on the output indicating the "kexec" command that is being executed. When including the initramfs, the screen blanks, but remains empty. Machine is still unresponsive.
3. When performing an "insecure" boot from Heads and adding "nomodeset" to the kernel arguments with the initramfs being loaded, the screen remains stuck on the "kexec" output. However, it responds to ctrl+alt+delete.
4. In the case above, blindly entering the disk passphrase (while the screen is stuck on the "kexec" output) does yield immediate disk activity as if the machine is booting. However, the screen output does not change, since I was hoping to be greeted with the lightdm login screen.
5. In the case above, the screen output also does not change switching to a separate virtual terminal with ctrl+alt+f2; however, logging in _does_ appear to work as I was able to reboot the machine using the `reboot` command after blindly logging in to the second virtual terminal.

Note that on the T430 and Heads, I've never been able to see any Xen console output at boot. On the kernels that worked (<=5.16.18), I've also never seen early bootup printks; the prompt for disk passphrase and 5-10 more lines before that is usually the first thing I see after the "kexec" output from Heads.

My guess is that this is something Intel graphics related. Is there anything I can try, now knowing that `nomodeset` at least allows further progress?

**Comment by tlaurion** [comment]
@icequbes1 So this is qubes testing kernel on top of maximized t430/x230 ROMs?

**Comment by tlaurion** [comment]
vbt tables present in coreboot 4.13+ have resolved in the past the issues of booting 5.10 kernels. 

I am not aware of the results of those 
testing kernels unfortunately.
 
@marmarek : testing those in QA qubes testing env succeeds?

**Comment by marmarek** [comment]
I don't have "kernel-latest" tests on x230/t430, only "kernel" (so, 5.4 / 5.10). I'll look into adding those too.

**Comment by icequbes1** [comment]
> @icequbes1 So this is qubes testing kernel on top of maximized t430/x230 ROMs?

@tlaurion yes, it is Qubes' kernel-latest but not the maximized ROM (`make BOARD=t430`).

**Comment by icequbes1** [comment]
So far, a very slow bisect (since it takes 4 hours to compile a kernel):

- 5.17.5: no boot
- 5.17.4: no boot
- 5.17.3: no boot
- 5.17.2: no boot
- 5.17.1: no boot
- 5.16.20: boots

**Comment by DemiMarie** [comment]
> So far, a very slow bisect (since it takes 4 hours to compile a kernel):
> 
> * 5.17.5: no boot
> * 5.17.4: no boot
> * 5.17.3: no boot
> * 5.17.2: no boot
> * 5.17.1: no boot
> * 5.16.20: boots

I suggest using `git bisect` so you can skip a bunch of intermediate steps.

**Comment by icequbes1** [comment]
Fixed in kernel-latest-5.17.7-1.

Possibly from the patch in #7479 (`[PATCH] x86/PAT: have pat_enabled() properly reflect state when running on e.g. Xen`), but I did not try kernel 5.17.7 without the patch.

**Comment by marmarek** [comment]
> Fixed in kernel-latest-5.17.7-1.

:tada: 

> Possibly from the patch in #7479 (

Unlikely, I have been running a kernel with similar patch for some time and the issue did happened. I have looked at the changelog between 5.17.5 and 5.17.7 and haven't found anything suggesting a fix for the sound, but that could be a side effect of anything else.
