### ISSUE TITLE
Uprgade of qubes-core-dom0-linux fails due to preset of masked unit

### ISSUE THREAD

**Issue by Rudd-O** [QubesOS/qubes-issues#7484]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

4.1

### Brief summary

My system masks `usbguard.service` because it causes a dependency cycle with `zfs-mount.service` (involving the systemd TTY ask password prompt.  Other users may want to mask `usbguard.service` for reasons of their own.

https://github.com/QubesOS/qubes-core-admin-linux/blob/7d0476db14903bf2fbc75a4d165923e7edbcfe6d/rpm_spec/core-dom0-linux.spec.in#L201

Masking the unit causes upgrades to fail:

```
Upgrading         : qubes-core-dom0-linux-4.1.21-1.fc32.x86_64               2/4
Failed to preset unit: Unit file /etc/systemd/system/usbguard.service is masked.
```

The preset stanza in the postscript should either be guarded with a "if first install" conditional, or it should detect using something like `systemctl status usbguard.service | grep masked` if the unit is masked, and skip masking it, or it should simply end with ` || true` to omit the error and let the scriptlet finish.

In fact, all of the commands in the scriptlet should have proper error hanling, and should not abort the scriptlet if one of them fails.

Please fix.

**Comment by DemiMarie** [comment]
@marmarek what do you think?

**Comment by Rudd-O** [comment]
There is an RPM scriptlet macro for presetting units in the right way.  Please use that.
