### ISSUE TITLE
Upgrade to 4.1 denies VMRootShell to mgmt VM when updating Whonix WS

### ISSUE THREAD

**Issue by tetrahedras** [QubesOS/qubes-issues#7486]
### Qubes OS release
4.1

### Brief summary

When attempting to update the Whonix WS template (via QubesUpdater or `$ sudo qubesctl --show-output --skip-dom0 --templates state.sls update.qubes-vm`) the update fails with the user notification pop-up:
```
Denied qubes.VMRootShell from disp-mgmt-whonix-ws-16 to whonix-ws-16
```
and the console log entry
```
whonix-ws-16:
      ----------
      _error:
          Failed to return clean data
      retcode:
          126
      stderr:
          Request refused
      stdout:
```

If I run `apt update` and `apt upgrade` on the template manually, it works fine.

Updates of non-Whonix templates also work fine.

It looks like there is a qrexec configuration issue specific to this one template, but I'm not sure where to go looking for it.

**Comment by andrewdavidwong** [comment]
This appears to be a [duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If anyone believes this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.
