### ISSUE TITLE
Provide a maintained OpenSSH package in dom0 for those who manually install it

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#7493]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### The problem you're addressing (if any)

Some users install Qubes OS on servers, which they do not have physical access to.  Such servers need to be managed remotely.

The simplest way to do this is for the user to run `sudo qubes-dom0-update openssh-server` to get the OpenSSH server package, then have sys-net to forward port 22 to it over qrexec.  This means that dom0’s SSH is exposed to the public Internet, and so it needs to be kept secure.

### The solution you'd like

OpenSSH is (correctly) not shipped by default in dom0.  However, if one _does_ run `sudo qubes-dom0-update openssh-server`, one should get a package that does not have any known vulnerabilities.

### The value to a user, and who that user might be

Users who manually set up remote access of some sort will not introduce any security holes they were not expecting to introduce.

**Comment by andrewdavidwong** [comment]
I thought that all types of remote management were supposed to be disabled in the default open-source edition of Qubes OS. Isn't dom0 supposed to be strongly isolated from all networking (especially the public internet) *by design* in its default configuration? If so, OpenSSH doesn't even belong in the default open-source edition's dom0. There shouldn't be any kind of "remote dom0" code on users' systems, *unless they opt in to it first*. See #6364 for a prior, related discussion and #5358 for a similar tool for performing the same task.

**Comment by unman** [comment]
On Wed, May 04, 2022 at 10:54:43PM -0700, Andrew David Wong wrote:
> I thought that all types of remote management were supposed to be disabled in the default open-source edition of Qubes OS. Isn't dom0 supposed to be strongly isolated from all networking (especially the public internet) *by design* in its default configuration? If so, OpenSSH doesn't even belong in the default open-source edition's dom0. There shouldn't be any kind of "remote dom0" code on users' systems, *unless they opt in to it first*. See #6364 for a prior, related discussion and #5358 for a similar tool for performing the same task.

Second this.
imo remote access should be limited to managementVM, limited by qrexec
policies.

The default install doesn't have openssh-server at all.

**Comment by DemiMarie** [comment]
> I thought that all types of remote management were supposed to be disabled in the default open-source edition of Qubes OS. Isn't dom0 supposed to be strongly isolated from all networking (especially the public internet) _by design_ in its default configuration? If so, OpenSSH doesn't even belong in the default open-source edition's dom0. There shouldn't be any kind of "remote dom0" code on users' systems, _unless they opt in to it first_. See #6364 for a prior, related discussion and #5358 for a similar tool for performing the same task.

I absolutely agree with this; sorry for the ninja edit.  This is exclusively those who use Qubes on _servers_, and who manually install the relevant packages.

**Comment by alimirjamali** [comment]
After the package for #9342 is tested and verified, it might solve this issue as well

https://github.com/QubesOS/qubes-openssh

**Comment by alimirjamali** [comment]
@DemiMarie is this issue still valid? I wonder if [qubes-openssh](https://github.com/QubesOS/qubes-openssh) and included patches fixes it.

**Comment by DemiMarie** [comment]
It does.
