### ISSUE TITLE
Mini PC  

### ISSUE THREAD

**Issue by MikeyBeez** [QubesOS/qubes-issues#7496]
I've check Qubes documentation and support, but I can not find what I want.  I'm hoping to find a low power mini pc that has all the requirements for the latest version of cubes.  Sorry if I'm asking in the wrong place.

**Comment by andrewdavidwong** [comment]
Based on our [issue tracking guidelines](https://www.qubes-os.org/doc/issue-tracking/), this does not appear to be suitable for `qubes-issues`. We ask that you please post this on the [Qubes Forum or `qubes-users` mailing list](https://www.qubes-os.org/support/) instead. If, after reading our [issue tracking guidelines](https://www.qubes-os.org/doc/issue-tracking/), you believe we are mistaken, please leave a brief comment explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.
