### ISSUE TITLE
Wrong LUKS password fails poorly

### ISSUE THREAD

**Issue by MonkeyBars3k** [QubesOS/qubes-issues#7497]
### Qubes OS release
4.1

### Brief summary
After five tries typing in the wrong disk decryption password, user is given no clear indication that the passwords were all wrong and is unceremoniously dumped into a crippled dracut emergency shell. I am logging this as a bug since it seems poorer than usual UX to fail so ungracefully after mere incorrect disk password entries.

### Steps to reproduce
Boot up encrypted Qubes 4.1 install and type the wrong password several times into the input and submit until it exits out.

### Expected behavior
I actually am not certain what the expected result is here – perhaps a simple, clear message (like "**All disk decryption password attempts have failed; you are now exiting to an emergency shell.**") before being dumped to the crippled shell.

### Actual behavior
Disk error message followed by choice to launch command shell or "continue", which fails.

__________________

Related issues that are possibly just examples of the user forgetting correct password and being confused by the crippled emergency shell and thinking there's some error in the disk or boot paradigm:
#5602
#5160
#5372

**Comment by frenchy64** [comment]
Affects 4.2.
