### ISSUE TITLE
Graphics artefacts with Intel UHD Graphics 770 and kernel 5.17.7

### ISSUE THREAD

**Issue by tzwcfq** [QubesOS/qubes-issues#7507]
### Qubes OS release
Qubes R4.1 current-testing

### Brief summary
CPU: Intel i9-12900K
I'm using integrated GPU Intel UHD Graphics 770 as my display source.
After updating kernel-latest to the version 5.17.7 and booting Qubes with it I'm getting graphics artefacts in places where the image is being redrawn. This problem is present starting with LUKS password input stage.
The kernel version 5.17.5 works fine.
I've checked logs but didn't see any errors or difference compared to the kernel version 5.17.5.
I've tried bare-metal debian with kernel 5.17.6-1 from sid repository and there is no such problem.
When kernel 5.17.7-1 will be available in sid repo I'll try again.
Maybe it's upstream bug.

### Steps to reproduce
1. Update kernel-latest to version 5.17.7.
2. Boot Qubes with kernel 5.17.7.
3. Observe graphics artefacts.

### Expected behavior
No graphics artefacts.

### Actual behavior
Getting graphics artefacts in places where image is being redrawn.

**Comment by tzwcfq** [comment]
I've tried Xubuntu 22.04 with kernel 5.17.7 from kernel-ppa:
https://kernel.ubuntu.com/~kernel-ppa/mainline/v5.17.7/
And it works without any problem.
So it should be Qubes-related issue or maybe Xen-related issue.

**Comment by asharp** [comment]
That sounds like a bug I've seen.

My fix was to install kernel-latest and add:
`cat /etc/X11/xorg.conf.d/99-intel.conf
Section “OutputClass”
Identifier “intel”
MatchDriver “i915”
Driver “intel”
Option “AccelMethod” “sna”
Option “TearFree” “true”
Option “DRI” “3”
EndSection`

Hope this helps.

**Comment by tzwcfq** [comment]
I've tried to start with this config with kernel 5.17.5 and 5.17.17 but Xorg is failing to start:
```
dom0 systemd-coredump[7253]: Process 7243 (Xorg) of user 0 dumped core.
                                             
                                             Stack trace of thread 7243:
                                             #0  0x00007bd82acee7d5 raise (libc.so.6 + 0x3c7d5)
                                             #1  0x00007bd82acd7895 abort (libc.so.6 + 0x25895)
                                             #2  0x0000630e5f6560e0 OsAbort (Xorg + 0x1c60e0)
                                             #3  0x0000630e5f65b959 AbortServer (Xorg + 0x1cb959)
                                             #4  0x0000630e5f65c6aa FatalError (Xorg + 0x1cc6aa)
                                             #5  0x0000630e5f4f1e3d dix_main (Xorg + 0x61e3d)
                                             #6  0x00007bd82acd9082 __libc_start_main (libc.so.6 + 0x27082)
                                             #7  0x0000630e5f4dae6e _start (Xorg + 0x4ae6e)
```

**Comment by tzwcfq** [comment]
There was a problem with wrong quotes character ” instead of " and missing EndSection keyword.
With this config:
```
Section "OutputClass"
Identifier "intel"
MatchDriver "i915"
Driver "intel"
Option "AccelMethod" "sna"
Option "TearFree" "true"
Option "DRI" "3"
EndSection
```
Graphics with kernel 5.17.7 works fine.
Thanks for your help!
