### ISSUE TITLE
Dom0 Kernel updates do not properly clean up /usr/lib/modules

### ISSUE THREAD

**Issue by brendanhoar** [QubesOS/qubes-issues#7508]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
R4.0 current-testing kernel-latest

### Brief summary
/usr/lib/modules/ directory has non-empty directories for every kernel installed on system since install.

### Steps to reproduce
cd /usr/lib/modules
du -d 1 -h .

### Expected behavior
One large directory per installed  kernel

### Actual behavior
One large directory per installed kernel plus one small directory per no-longer-installed kernel.

The latter set are about 4MB+ each.

B

**Comment by DemiMarie** [comment]
I have noticed the same thing myself and come up with a script for cleaning it up.  I wonder if the use of overlayfs is responsible.
