### ISSUE TITLE
appmenus color in menu sometimes doesn't match the current VM label

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#751]
**Reported by marmarek on 18 Oct 2013 23:14 UTC**
Simple to reproduce: just change VM label, menu will still use the old one.
Even Xorg restart doesn't fix it. Recreating appmenus for this VM also doesn't fix it. Looks like KDE somewhere caches icon and didn't notice symlink change. 

In Xfce4 it is much better: application icons are updated instantly, VM directory icon - after regenerating appmenus (any change in selected apps).

Migrated-From: https://wiki.qubes-os.org/ticket/751

**Comment by unman** [comment]
@andrewdavidwong I believe this issue is resolved in 3.2, and can be closed
