### ISSUE TITLE
Improved certified hardware

### ISSUE THREAD

**Issue by anonaddict** [QubesOS/qubes-issues#7516]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### The problem you're addressing (if any)
Low spec certified hardware

### The solution you'd like
Work with a vendor to provide higher-spec hardware

### The value to a user, and who that user might be
Given the nature of qubes it swallows a *lot* of RAM. While people running a normal linux distro or even windows on 8-16 GB ram might be completely fine they will likely experience ram management issues on qubes (take it with a grain of salt since I only have 8). In particular I've seen several people mention they might need a windows qube due to company policy or some proprietary SaaS and they will most definitely start having issues. 

Additionally all the certified hardware has screens 14" (nitropad t430) or much smaller which isn't very good for most things I personally use it for in terms of gaming and videos. I wouldn't ever personally spend the money for 32-64 gb ram and other upgrades on a laptop if it doesn't have a >14" screen 

All certified hardware only supports 16 gb ram at most

No certified hardware supports more than 1600x900, just 1920x1080 would be a major improvement

**Comment by DemiMarie** [comment]
I have 16gb RAM and I regularly run into out of memory conditions.

**Comment by brendanhoar** [comment]
I was very lucky when I ran into Qubes (2015? 2016?) via the Open Technology Fund (OTF) where a friend worked. Especially as I had already purchased a Thinkpad W520 in 2011 (via IBM EPP discount) that supported 32GB TAM (4x RAM slots).

I find that if you must use large memory footprint HVMs (e.g. Windows) for some work, while also having several other non-sys VMs open, having at least 32GB of RAM gives breathing room that 16GB does not.

Also I do find that if/when browsers are in the mix, it's useful to pause VMs you aren't using (which happens to also temporarily remove them from memory balooning operations!) if time critical tasks or audio/visual work must be done in a different VM.  Having the additional RAM means less fiddling with squeezing memory out of these other VMs (via several techniques) before pausing them is needed.

Anyway, the Thinkpad W520 (Sandy Bridge) and W530 (Ivy Bridge) are workhorses. Last I checked they were rather cheap on the used market. Be sure to get a quad core for 32GB RAM as some units were dual core supporting only 16GB. Then be sure the firmware is updated to the last version (2020?).

B

**Comment by andrewdavidwong** [comment]
Based on our [issue tracking guidelines](https://www.qubes-os.org/doc/issue-tracking/), this does not appear to be suitable for `qubes-issues`. (Too general and not specifically actionable. Misunderstands how the hardware certification process works.) We ask that you please post this on the [Qubes Forum or `qubes-users` mailing list](https://www.qubes-os.org/support/) instead. If, after reading our [issue tracking guidelines](https://www.qubes-os.org/doc/issue-tracking/), you believe we are mistaken, please leave a brief comment explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.
