### ISSUE TITLE
Failed USB Installation - Warning: dracut-initqueue timeout - starting timeout scripts

### ISSUE THREAD

**Issue by glenjennings** [QubesOS/qubes-issues#7518]
### Qubes OS release

Qubes OS R4.1.0-x86_64.iso

### Brief summary

When I boot from USB I can't make it to the Installation Setup Panel because I get a timeout script dump

### Steps to reproduce

1) Download latest Qubes OS ISO from https://www.qubes-os.org/downloads/
2) Verify the ISO file
3) Download Rufus
4) Create Bootable USB Image and select "DD" image
5) Reboot computer
6) Select to boot from USB
7) Select Install Qubes OS
8) Wait a few minutes for it to do its thing
9) Receive timeout scripts

### Expected behavior

Successful OS installation

### Actual behavior

Get timeout scripts and unsuccessful installation

### System Specs

CPU: AMD Ryzen 9 3950x 16-Core Processor
Mobo: Alienware 0NWN7M A00
BIOS: UEFI Alienware 2.2.5
SMBIOS Version: 3.2
Embedded Controller Version: 255.255
Secure Boot: OFF
GPU: NVIDIA GeForce RTX 2080 Ti
RAM: 64GB DDR4
Storage: 1 TB NVMe SSD, 1 TB HDD
Network: Wireless

### journalctl 

```
ACPI BIOS Warning (bug): Incorrect checksum in table [BGRT] - 0x47, should be 0x49 (20200925/tbprint-173)
```

```
ACPI: [Firmware Bug]: BIOS _OSI(Linux) query ignored
```

```
Expanded resource Reserved due to conflict with PCI Bus 0000:00
```

```
[Firmware Bug]: ACPI MWAIT C-State 0x0 not supported by HW (0x0)
```

```
hpet_acpi_add: no address or irqs in _CRS
```

```
ccp 0000:0d:00.1: ccp: unable to access the device: you might be running a broken BIOS
```

```
multipath[1345]: sdb: can't store path info
multipath[1216]: uevent trigger error
multipath[1346]: sdb: can't store path info
multipath[1216]: sdb: spurious uevent, path not found
multipath[1216]:: uevent trigger error
dracut-initqueue[1224]: Warning: dracut-initqueue timeout - starting timeout scripts
dracut-initqueue[1224]: Warning: Could not boot
systemd[1]: Starting Dracut Emergency Shell...
```

```
dracut-initqueue[1224]: Warning: Not all disks have been found.
dracut-initqueue[1224]: Warning: You might want to regenerate your initramfs
Warning: /dev/root does not exist
```

**Comment by DemiMarie** [comment]
Looks like something is horribly wrong with your firmware.  Does a firmware update help?

**Comment by DemiMarie** [comment]
Do you still get the `[Firmware Bug]` messages?

**Comment by DemiMarie** [comment]
Also, can you select a different kernel in the installer @glenjennings?

**Comment by tzwcfq** [comment]
> Do you mean find an ISO that says "kernel-latest" on it?

You can try latest Qubes 4.1 ISO build with kernel-latest from here:
https://qubes.notset.fr/iso/

**Comment by tzwcfq** [comment]
> If anyone knows how to get the full log to my desktop from the bootable USB so I can share the whole thing I'm more than happy to do so

I think after dracut-initqueue timeout you'll be able to enter the shell and copy logs on another USB.
You can check logs location here:
https://docs.fedoraproject.org/en-US/quick-docs/anaconda/anaconda_logging/

**Comment by tzwcfq** [comment]
> What commands should I use when trying to copy the logs?

Assuming /dev/sdc1 is you USB drive that you want to store logs on:
```
mkdir mount
mount /dev/sdc1 mount
cp /run/initramfs/rdsosreport.txt mount/.
umount mount
```

**Comment by tzwcfq** [comment]
Maybe you have the same problem with faulty creation of the USB installation medium:
https://www.qubes-os.org/doc/installation-troubleshooting/#warning-dracut-initqueue-timeout---starting-timeout-scripts-during-installation
Similar problem:
https://forum.qubes-os.org/t/installation-stuck-at-attached-scsi-removable-disk-then-goes-into-dracut-timeout/3842
