### ISSUE TITLE
"Turn on scatter-gather and checksum offload" commit broke open-iscsi

### ISSUE THREAD

**Issue by a-barinov** [QubesOS/qubes-issues#7522]
### Qubes OS release
4.1

### Brief summary
"Turn on scatter-gather and checksum offload" commit makes open-iscsi discs shared with other qubes read-noly.

### Steps to reproduce
This was tested on debian-11.

The setup is intended to open encrypted luks sitting on iscsi device on Synology NAS.  Qubes setup is as follows: network qube -> iscsi qube -> decryptor qube -> reader qube. Devise sharing done using qvm-block. As soon as iscsi device (/ev/sda) is shared to decryptor qube you can no longer write to this device. Decrypting and mounting the device  from inside iscsi qube (i.e. without sharing the device with other qubes) works just fine.

### Expected behavior
iscsi device shared with other qubes should work normally.

### Actual behavior
iscsi device shared with other qubes can only be mounted as read-only, any write attempt times out.

This is caused by the following part of ["Turn on scatter-gather and checksum offload" commit](https://github.com/QubesOS/qubes-core-agent-linux/commit/045e85eb26e9891a43bf55bcfd731215027511b8), related to setup-ip script:
`
            /sbin/ethtool -K "$INTERFACE" sg off
            /sbin/ethtool -K "$INTERFACE" tx off
`
Adding back these lines or adding equivalent code to rc.local makes iscsi work normally.

**Comment by marmarek** [comment]
Can you try disabling just checksum offload (`tx`)?

**Comment by a-barinov** [comment]
> Can you try disabling just checksum offload (`tx`)?

It works the other way around, unfortunately. Setting tx on or off does not make any difference, turning sg on immediately breaks open-iscsi.

**Comment by DemiMarie** [comment]
My intuition is that this is a kernel bug in the iSCSI module but I have no idea what kind of bug it is.

**Comment by marmarek** [comment]
This may still affect R4.2. If anybody cares about this use case, please provide complete reproduction steps on a supported template, including iscsi setup.
