### ISSUE TITLE
Document that DNF is not to be used for removing templates

### ISSUE THREAD

**Issue by TNTBOMBOM** [QubesOS/qubes-issues#7525]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

4.1

### Brief summary

Trying to remove fedora-34 template (same for as any template), using this command: 

`sudo dnf remove qubes-template-fedora-34`

According to this wiki:

https://www.qubes-os.org/doc/templates/#uninstalling

### Expected behavior

should be removed or show a message that it cant be removed because there are VMs dependent on it..

### Actual behavior

```
[user@dom0 ~]$ sudo dnf remove qubes-template-fedora-34
No match for argument: qubes-template-fedora-34
No packages marked for removal.
Dependencies resolved.
Nothing to do.
Complete!
[user@dom0 ~]$ 
```

![fedora34](https://user-images.githubusercontent.com/11895339/170413606-c99633f0-5696-4391-a86f-ce4811db75b1.png)

**Comment by ZYousef** [comment]
Use `qvm-template remove fedora-34` instead.

**Comment by TNTBOMBOM** [comment]
Cool this one worked, Thanks.

Maybe this one need a wiki upgrade.

Yousef Alzahrani:
> Use `qvm-template remove fedora-34` instead.
>

**Comment by andrewdavidwong** [comment]
Sounds like a change from 4.0 to 4.1.

**Comment by marmarek** [comment]
> Sounds like a change from 4.0 to 4.1.

Yes, exactly.

**Comment by alimirjamali** [comment]
> Maybe this one need a wiki upgrade.

@TNTBOMBOM do you find the current [official guide on removing templates](https://www.qubes-os.org/doc/templates/#uninstalling) good and satisfactory? If the answer is yes, the issue might be closed accordingly.

We also added some advisory help on removing the templates via DNF in PR for #4763

**Comment by alimirjamali** [comment]
PR submitted
