### ISSUE TITLE
Make the default update button command for debian templates to use apt instead of apt-get 

### ISSUE THREAD

**Issue by TNTBOMBOM** [QubesOS/qubes-issues#7526]
### The problem you're addressing (if any)

When i press update/upgrade button from Qubes manager to debian template it will run the update/upgrade command with apt-get which is the older name.

### The solution you'd like

Use apt only as it will show the progress bar on how much left from loading when installing packages, also apt now replaced apt-get.

### The value to a user, and who that user might be

Seeing progress bar, Using newest default recommendation from upstream.

**Comment by unman** [comment]
On Wed, May 25, 2022 at 09:13:35PM -0700, TNT BOM BOM wrote:
> ### The problem you're addressing (if any)
> 
> When i press update/upgrade button from Qubes manager to debian template it will run the update/upgrade command with apt-get which is the older name.
> 
> ### The solution you'd like
> 
> 
> Use apt only as it will show the progress bar on how much left from loading when installing packages, also apt now replaced apt-get.
> 
> 
> ### The value to a user, and who that user might be
> 
> 
> Seeing progress bar, Using newest default recommendation from upstream.
> 
> 

apt-get is not "the older name" - it is a separate application.
It has not been "replaced" by apt.

As per the manpage for apt - 
The apt(8) commandline is designed as an end-user tool and it may change behavior between versions.
While it tries not to break backward compatibility this is not guaranteed either if a change seems beneficial for interactive use.
All features of apt(8) are available in dedicated APT tools like apt-get(8) and apt-cache(8) as well.
apt(8) just changes the default value of some options (see apt.conf(5) and specifically the Binary scope).
So you should prefer using these commands (potentially with some additional options enabled) in your scripts as they keep backward compatibility as much as possible.

In any case, use of this method is deprecated, and there has been a
discussion on standardising on the update tool  - #6635
