### ISSUE TITLE
split-gpg: support `--tofu-policy` and `--quick-lsign-key`

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#7527]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### The problem you're addressing (if any)

`--tofu-policy` and `--quick-lsign-key` are quite useful for key management, and are safe.

### The solution you'd like

Support both in split-gpg.

### The value to a user, and who that user might be

Users will be able to adjust TOFU settings and locally sign keys via split-gpg.

**Comment by marmarek** [comment]
> `--quick-lsign-key`

This is called by the user manually, not from some application, right? In that case, the user can call it directly in the backend qube.

**Comment by DemiMarie** [comment]
Yeah, or expose a (trivial) qrexec service to do so.

**Comment by DemiMarie** [comment]
This is actually about split-gpg version 1, which makes me think it should just be closed as “won’t do”.  @marmarek is that reasonable?

**Comment by marmarek** [comment]
On Fri, May 27, 2022 at 12:52:27PM -0700, Demi Marie Obenour wrote:
> This is actually about split-gpg version 1, which makes me think it should just be closed as “won’t do”.  @marmarek is that reasonable?

Yes

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab

**Comment by DemiMarie** [comment]
Closing as “won’t do” (the Qubes developers have decided not to do this).  split-gpg1 is in maintenance mode and split-gpg2 does not have this limitation.
