### ISSUE TITLE
Add pulseaudio-16 headers

### ISSUE THREAD

**Issue by lubellier** [QubesOS/qubes-issues#7531]
### Qubes OS release
4.1

### Brief summary

PulseAudio 16.0 is now published (see [16.0 tag](https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/tags/v16.0)), the PulseAudio headers and the package dependency versions should be updated.

**It is not yet a problem**, but it will become a problem in few days (ArchLinux already published the [pulseaudio-16.0 package](https://archlinux.org/packages/testing/x86_64/pulseaudio/)).

### Related issues

- #6807
- #6353

**Comment by Ban3** [comment]
Just a heads-up: Module installation location has changed, and the Makefile will need to be modified to install vchan-sink to the correct location on versions >= 16:

> Modules are now installed to $libdir/pulseaudio/modules, previously they were installed to $libdir/pulse-$version/modules.

https://www.freedesktop.org/wiki/Software/PulseAudio/Notes/16.0/#moduleinstallationlocationchangedremembertoupgradepaprefstothelatestversion

**Comment by lubellier** [comment]
Note: yesterday, Gentoo also [switched to PulseAudio-16](https://packages.gentoo.org/packages/media-sound/pulseaudio).
See also the discussions in the above 158 PR.

**Comment by marmarek** [comment]
There are already headers for pulseaudio 16.1: https://github.com/QubesOS/qubes-gui-agent-linux/pull/160
