### ISSUE TITLE
Mid-4.1 Upgrade Failure Causes qrexec-daemon failure. Unable to start any Qube

### ISSUE THREAD

**Issue by ymbr4DA** [QubesOS/qubes-issues#7532]
Qubes 4.04, upgrading to Qubes 4.1
Coreboot 4.14
Purism Librem 15v3
Intel Core i7

Following the in place upgrade instructions on Qubes' website [here](https://www.qubes-os.org/doc/upgrade/4.1/).

Stage 0 and Stage 1 completed without issue.  Stage 2 failed mid-way, and the whole upgrade process stopped.  I tried to restart the upgrade, but Stage 2 failed again.  I restarted the computer, and then no VM could start at all.  Trying to start any VM resulted in this error message:

>Domain sys-usb has failed to start: qrexec-daemon startup failed: Connection to the VM failed.

I looked for previous reports of this issue:

[This post](https://forum.qubes-os.org/t/freshly-created-vms-fail-with-qrexec-daemon-startup-failed/4280/2) suggests to increase `qrexec_timeout`  I did this, but it did not have any effect.

[This post](https://forum.qubes-os.org/t/qrexec-agent-not-starting-after-vm-update/5286/4) says that it is a compatibility issue with the new/old qrexec-daemon/agent, and that you must reboot, and then proceed with the later steps, to then later return to Step 2.  However, there is a failure at any stage because no VM can open due to the qrexec failure (`sys-net` and `sys-firewell` need to open, but can't).  In addition, there is an additional failure message in `dom0`:

> ERROR: UpdateVM (sys-firewall) should on [sic] a template that have 'dnf' installed - at least Fedora 30, Debian 11, or Whonix 16.

`systemctl status qubes-qrexec-agent.service` results in:

>Unit qubes-qrexec-agent.service could not be found.

It seems the error was also reported [here](https://forum.qubes-os.org/t/4-1beta-upgrade-stage1-errors/5227/4) without conclusion.

It has also been reported by many users on Reddit [here](https://www.reddit.com/r/Qubes/comments/socymc/41_upgrade_failure/).

I remember reading a suggestion that newly created VMs can be opened (can't find the post now).  However, I tried to create a new sys-usb, and it cannot open and still has the same error message.

I made a backup right before the upgrade attempt, so don't really care about fixing the issue (although from a bug perspective, maybe we should). I really just want to restore the backup, but since no VM can be opened, I can't open sys-usb to restore the backup from my external drive!

[This post](https://forum.qubes-os.org/t/qrexec-deamon-startup-failed-connection-to-the-vm-failed/8470/5) recommends that I post the content of `journalctl -f` and `journalctl -p crit`.  Because my Qubes-laptop cannot open any VM, there is no way to copy that data to post here.  Therefore, unfortunately I have to take pictures of dom0 to post the data here (from my Mac). Sorry!

I know it looks awful at first, but you should be able to click on the image and zoom in, to see the text clearly.

`journalctl -f` (then attempting to open sys-usb):

![journalctl -f 1](https://user-images.githubusercontent.com/106555684/171055337-b338f1a6-3fae-4709-87c9-3f30f709bd49.JPG)

![journalctl -f 2](https://user-images.githubusercontent.com/106555684/171055347-78d35db6-4025-4958-a6c3-a4bef05c4742.JPG)

`journalctl -p crit`:

>Disabling IRQ #16
Disabling IRQ #16
Disabling IRQ #16
Disabling IRQ #16
Disabling IRQ #16
Disabling IRQ #16
Disabling IRQ #16
watchdog: watchdog0: watchdog did not stop!

Thank you for your help in advance

**Comment by DemiMarie** [comment]
Sadly I think the only option at this point is to restore from backup.  This is a known limitation of in-place upgrades.  The upgrade code for R4.1 ⇒ R4.2 will not have this problem.

**Comment by ymbr4DA** [comment]
Thank you, but how do I go about restoring if I cannot start sys-usb to connect my external drive?

**Comment by andrewdavidwong** [comment]
> Thank you, but how do I go about restoring if I cannot start sys-usb to connect my external drive?

I believe what Demi means is:

1. Download the Qubes 4.1 ISO.
2. Perform a clean installation of Qubes 4.1 from the ISO.
3. Restore your qubes from a backup.

(Of course, this assumes that your sys-usb problem is specific to your current installation (which was upgraded in-place) and will not be present on a clean installation from the ISO.)

**Comment by andrewdavidwong** [comment]
> Sadly I think the only option at this point is to restore from backup. This is a known limitation of in-place upgrades. The upgrade code for R4.1 ⇒ R4.2 will not have this problem.

Does this mean that this issue is a "won't fix"?

**Comment by ymbr4DA** [comment]
>Perform a clean installation

Is there any downside of this, in comparison to the in place upgrade?

**Comment by andrewdavidwong** [comment]
> > Perform a clean installation
> 
> Is there any downside of this, in comparison to the in place upgrade?

The downside is that none of your data or customizations persist. It is a clean installation with none of your changes. You will lose everything that is not backed up.

Other than that, it is preferable to an in-place upgrade, as fewer things can go wrong.

For any further questions or discussion of this matter, please note that the issue tracker (`qubes-issues`) is not intended to be a place for fielding questions. Instead, we have other [venues meant for asking questions, asking for help, and having discussions](https://www.qubes-os.org/support/). (By contrast, the issue tracker is more of a technical tool intended to support our developers in their work.) Thank you for your understanding!
