### ISSUE TITLE
"Very large window" alert triggered every time LibreOffice is opened for the first time in a qube

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#7533]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

4.0.4

Debian-based qubes

### Brief summary

The "very large window" warning alert (full text below) appears every time I open a LibreOffice spreadsheet the first time in a qube, which rapidly causes [alarm fatigue](https://en.wikipedia.org/wiki/Alarm_fatigue). Qubes has trained me to immediately click away this notification without reading it every time it appears because (a) it is *always* a false positive, and (b) it is extremely verbose and therefore time-consuming (or time-wasting) to read.

### Steps to reproduce

1. Start a qube.
2. Open a LibreOffice spreadsheet (normal maximized window).

### Expected behavior

No intrusive or distracting notification that requires user action to dismiss it.

### Actual behavior

This alert always appears and persists until I click on it:

> This VM has attempted to create a very large window in a manner that would have prevented you from closing it and regaining the control of Qubes OS's graphical user interface.
> 
> As a protection measure, the "override_redirect" flag of the window in question has been unset. If this creates unexpected issues in the handling of this VM's windows, please set "override_redirect_protection" to "false" for this VM in /etc/qubes/guid.conf to disable this protection measure and restart the VM.
> 
> This message will only appear once per VM per session. Please click on this notification to close it.

**Comment by DemiMarie** [comment]
Is this still an issue in 4.1 @andrewdavidwong?

**Comment by andrewdavidwong** [comment]
> Is this still an issue in 4.1 @andrewdavidwong?

Yes, definitely.
