### ISSUE TITLE
openQA uses ethtool when it does not need to.

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#7536]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

R4.1

### Brief summary

openQA expects that ethtool is installed in sys-net.  As of QubesOS/qubes-core-agent-linux@045e85eb26e9891a43bf55bcfd731215027511b8 this is no longer the case by default.

### Steps to reproduce

See openQA run.

### Expected behavior

No errors related to ethtool

### Actual behavior

Errors related to ethtool

**Comment by marmarek** [comment]
> See openQA run.

Can you point specific failed run?

**Comment by marmarek** [comment]
If you mean the suspend test on "hw1", then it tries to use ethtool indeed, but that isn't the reason for the failure (and ethtool isn't really necessary there, that part needs to be cleaned up).

**Comment by DemiMarie** [comment]
> If you mean the suspend test on "hw1", then it tries to use ethtool indeed, but that isn't the reason for the failure (and ethtool isn't really necessary there, that part needs to be cleaned up).

Yes, I do mean that test.
