### ISSUE TITLE
Ubuntu Jammy template needs pulseaudio 15.99.1 headers

### ISSUE THREAD

**Issue by unman** [QubesOS/qubes-issues#7537]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
4.1

### Brief summary
As title
Build fails as pulse headers for 15.99.1 are not included

### Steps to reproduce
Attempt to build jammy (2204 LTS) packages - specifically gui-agent-linux-vm

### Expected behavior
Build completes

### Actual behavior
PA build fails as PA_VER_FULL is 15.99.1
Only headers for 15.0 are included.

**Comment by lubellier** [comment]
@unman: is it a duplicate of #7531 ? Or is it really specific to 15.99.1 as it seems?

**Comment by unman** [comment]
On Wed, Jun 01, 2022 at 12:46:45PM -0700, Ludovic Bellier wrote:
> @unman: is it a duplicate of #7531 ? Or is it really specific to 15.99.1 as it seems?
> 

It is specific to 15.99.1
