### ISSUE TITLE
sys-gui terminal, several commands not found.

### ISSUE THREAD

**Issue by Geblaat** [QubesOS/qubes-issues#7541]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
R4.1

### Brief summary
Using qubesctl and qubes-dom0-update commands in sys-gui result in command not found. Not sure if more commands are missing, as I usually use GUI when possible instead of commandline. I also tried qvm-start and qvm-prefs but those work succesfully.

### Steps to reproduce
Fresh install of R4.1, update Dom0 and templates, reboot. Setup hybrid sys-gui according to doc, set sys-gui as default guivm. Login to sys-gui, try to use Qubes Updates. It fails with "sudo: qubesctl: command not found". Running "sudo qubes-dom0-update" in sys-gui terminal also results in command not found.

### Expected behavior
Not sure what to expect, since maybe we want sys-gui to not have to many privileges, but I'd expect if sys-gui is not allowed to do those commands itself, it would at least proxy them to dom0 succesfully and show output in sys-gui. 

### Actual behavior
Command not found

**Comment by ben-grande** [comment]
Update mechanism does not use Salt anymore. I believe this issue can be closed.

There is a more recent issue about updates in sys-gui:

- https://github.com/QubesOS/qubes-issues/issues/8934
