### ISSUE TITLE
Release Qubes 4.1.1

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#7544]
As [previously discussed on qubes-devel](https://groups.google.com/d/topic/qubes-devel/lfCSltYV2ho/discussion), we aim to publish new [patch releases](https://www.qubes-os.org/doc/version-scheme/) periodically. Given that we recently [published new Fedora 35 templates](https://www.qubes-os.org/news/2022/05/26/fedora-34-approaching-eol-fedora-35-templates-available/) and have fixed numerous bugs since the initial 4.1.0 release, now may be a good time to consider a new patch release ISO.

- [x] Update references to included templates (installer, salt, anywhere else?)
- [x] Build new ISO
- [x] Test new ISO
- [x] Upload ISO to mirrors
- [ ] Announce

**Comment by DemiMarie** [comment]
I suggest waiting until 2022-06-09 12:00 UTC or later, since there are embargoed Xen Security Advisories that will be made public at that time.

**Comment by evil-user** [comment]
@andrewdavidwong any expected release date for qubes 4.1.1 ? thanks for great work done into an amazing os

**Comment by andrewdavidwong** [comment]
> @andrewdavidwong any expected release date for qubes 4.1.1 ? thanks for great work done into an amazing os

We expect to make the first release candidate available very soon.

**Comment by andrewdavidwong** [comment]
> > @andrewdavidwong any expected release date for qubes 4.1.1 ? thanks for great work done into an amazing os
> 
> We expect to make the first release candidate available very soon.

Qubes OS 4.1.1-rc1 is now available: https://www.qubes-os.org/news/2022/06/27/qubes-4-1-1-rc1/
