### ISSUE TITLE
Tray Icon rendering completely broken after dom0 update

### ISSUE THREAD

**Issue by ilka-schulz** [QubesOS/qubes-issues#7547]
### Qubes OS release
R4.1

### Brief summary
After a recent update of dom0, the tray icon are not rendered correctly anymore.

### Steps to reproduce
1. upgrade dom0 to current stable R4.1
2. reboot

### Expected behavior
- tray icons are displayed
- tray icons are displayed in the color of their VM

### Actual behavior
- some tray icons are not displayed at all (just a white square)
- some tray icons flicker / are displayed partially when hovering over them with the mouse
- when tray icons are shown, they have their native coloring, not the color of their VM
- Tray icons shown by applications running in dom0 (`Qubes Domains`, `Qubes Devices`, `Global Clipboard`, `Qubes Disk Space Monitor` and `Qubes Update` and `Power Manager`) are _not_ affected by the bug.

**Comment by zoechi** [comment]
Same issue after upgrade from 4.0 to 4.1.
Using KDE
In the tray the some icons are shown correctly, some are just white squares, some are colored qubes.
In the task bar many icons (pinned apps and running apps) are shown as colored squares

![Screenshot_icons](https://user-images.githubusercontent.com/405837/213160218-2e859a31-df81-4d38-bc5d-7407e6801815.png)

The cube icons for running apps are all for Chrome windows in different VMs.
(Firefox is shown with the correct icon but currently not used)
