### ISSUE TITLE
Fedora template(s) cannot be build

### ISSUE THREAD

**Issue by fireneat** [QubesOS/qubes-issues#7550]
### Qubes OS release
Qubes OS:  4.1
Builder: Fedora 34

### Brief summary
Trying to build Fedora templates with [qubes-builder](https://github.com/QubesOS/qubes-builder) fails if no option in the setup menu "Choose Pre-Built Packages Repositories" is selected. This seems to be because "nothing provides python3-gbulb needed by qubes-core-qrexec-4.1.18-1.fc36.x86_64" and there is no mention of python3-gbulb when trying to build fedora templates expect when it fails with Error 1.

### Steps to reproduce
Clone [qubes-builder](https://github.com/QubesOS/qubes-builder) and then follow [this guide](https://github.com/Qubes-Community/Contents/blob/master/docs/building/building-archlinux-template.md) but select builder-rpm and not builder-archlinux and then select any fedora template for example fedora-35. Then [follow these steps](https://github.com/Qubes-Community/Contents/blob/master/docs/building/building-archlinux-template.md#5-make-all-the-require-qubes-components) and wait until the builder complains because of the following:
```
$ make template
-> Building template fc35 (logfile: build-logs/template-fc35.log)...
make: *** [Makefile:352: template-local-fc35] Error 1
```
The log is more specific though:
```
--> Installing RPMs...
Qubes Template Builder Repository               3.7 MB/s | 3.8 kB     00:00    
Error: 
 Problem 1: package qubes-core-agent-4.2.0-1.fc35.x86_64 requires qubes-core-qrexec-vm, but none of the providers can be installed
  - package qubes-vm-dependencies-4.1.21-1.fc35.noarch requires qubes-core-agent, but none of the providers can be installed
  - package qubes-core-qrexec-vm-4.1.18-1.fc35.x86_64 requires qubes-core-qrexec = 4.1.18-1.fc35, but none of the providers can be installed
  - conflicting requests
  - nothing provides python3-gbulb needed by qubes-core-qrexec-4.1.18-1.fc35.x86_64
 Problem 2: package qubes-core-agent-dom0-updates-4.2.0-1.fc35.x86_64 requires qubes-core-agent = 4.2.0, but none of the providers can be installed
  - package qubes-core-agent-4.2.0-1.fc35.x86_64 requires qubes-core-qrexec-vm, but none of the providers can be installed
  - package qubes-vm-recommended-4.1.21-1.fc35.noarch requires qubes-core-agent-dom0-updates, but none of the providers can be installed
  - package qubes-core-qrexec-vm-4.1.18-1.fc35.x86_64 requires qubes-core-qrexec = 4.1.18-1.fc35, but none of the providers can be installed
  - conflicting requests
  - nothing provides python3-gbulb needed by qubes-core-qrexec-4.1.18-1.fc35.x86_64
(try to add '--skip-broken' to skip uninstallable packages)
make[1]: *** [Makefile:66: rootimg-build] Error 1
```

### Expected behavior
Fedora template builds successfully without having to select Pre-Built Package Repositories

### Actual behavior
Fedora template build fails because of python3-gbulb

**Comment by fepitre** [comment]
Please follow the official documentation at least https://www.qubes-os.org/doc/qubes-builder/#use-pre-built-qubes-packages.

**Comment by andrewdavidwong** [comment]
Closed as "not an issue" (the reported behavior is not a bug, or the proposal is not suitable as an enhancement or task). If anyone believes this is a mistake, please leave a comment, and we'll be happy to take another look. Thank you.
