### ISSUE TITLE
Problems accessing SMB shares from Fedora-36 and Fedora-37

### ISSUE THREAD

**Issue by GWeck** [QubesOS/qubes-issues#7552]
### Qubes OS release
R4.1 with Fedora-36 installed from testing repos

### Brief summary
When trying to access an SMB share (in my case, on a machine running Windows 7), the prompt for workgroup, username and password is displayed, but then access is denied with an error message stating a parameter fault.

### Steps to reproduce
Start an AppVM based on a Fedora-36 template, open the Files utility (Nautilus), position to  `Other places`, select `Connect to server` and enter a valid address like `smb://<Servername>/<Sharename>/`.

### Expected behavior
The share should be opened and usable from Nautilus.

### Actual behavior
Access is rejected due to parameter error.

### Additional information
This seems to be an upstream error from Fedora which already appeared some 2 months ago in Fedora-35 and then disappeared after an update some days after. For Fedora-36, it has now reappeared.

Currently, there is a rather simple workaround:
- In the template, execute the command `sudo dnf downgrade libsmbclient` .
- Then update again with `sudo dnf upgrade`.

After this, everything works again. Perhaps some library in the template has to be updated?

**Comment by GWeck** [comment]
@alt3r-3go Unfortunately, I don't have the test environment, where the error occurred, any longer, and Windows 8.1 is not available for me. Sorry!

With Qubes R4.1.1 and Fedora-36 fully updated, the error does not occur anymore; everything works as expected. So I am closing this issue.

**Comment by marmarek** [comment]
As reported in https://github.com/QubesOS/qubes-issues/issues/7921#issuecomment-1435597744 this is still the case in Fedora 37.

**Comment by marmarek** [comment]
It's a different issue in F37.
