### ISSUE TITLE
VM using kernel 5.10.112 unable to resume after suspension

### ISSUE THREAD

**Issue by logoerthiner1** [QubesOS/qubes-issues#7554]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

R4.1

### Brief summary

May be related: #7548 #7404

I have found that certain qube using the latest stable kernel will freeze after a suspension - resume loop.

It is observed twice respectively in a kali vm (installed manually from debian-11) and a fedora vm (customized from fedora-34-xfce), both with 5.10.112 kernel, and no PCI device passthrough.

When the VM freezes, the windows is not responsive other than the cursor may change style between different windows (R4.1 feature?), there is no additional log output in VM console, and it is impossible to execute any command with qrexec. Also it cannot be properly shut down, so I can only kill the vm.

Currently I have to avoid using the latest kernel.

UPDATE: 5.15+ does not have this behavior

### Steps to reproduce

1. update Qubes OS dom0 and switch to 5.10.112 kernel
2. boot up the vm
3. suspend & resume

### Expected behavior

No VM freeze

### Actual behavior

VM using the latest 5.10.112 kernel freeze

**Comment by resulin** [comment]
@logoerthiner1 Can you test this again? Seems to have been fixed on my end.

**Comment by 19v19** [comment]
I have the same issue
More info:https://github.com/QubesOS/qubes-issues/issues/7634

**Comment by logoerthiner1** [comment]
5.10 is not used any more on my side; similar issues do not happen to my VM that are using 5.15+ kernels.

I decide to close this issue; if anyone has similar problem please open a new one.
