### ISSUE TITLE
qubes-dom0-update often sets a zero exit code even when it fails

### ISSUE THREAD

**Issue by 3hhh** [QubesOS/qubes-issues#7558]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
4.1

### Brief summary
As stated in https://github.com/QubesOS/qubes-issues/issues/6585#issuecomment-1150117548 , `qubes-dom0-update` often uses `xterm -e`, which _always_ sets a zero exit code regardless of the result of the executed command. It doesn't use it with salt, so #6585 is not identical.

Potential fix in https://github.com/QubesOS/qubes-issues/issues/6585#issuecomment-1151241629

### Steps to reproduce
1. Disconnect the network from your update VM.
2. Run `qubes-dom0-update`
3. Check the exit code: `echo $?`

### Expected behavior

Non-zero = failing exit code.

### Actual behavior

Zero exit code.

**Comment by DemiMarie** [comment]
I’ll take this.

**Comment by 3hhh** [comment]
Might be fixed by https://github.com/QubesOS/qubes-core-admin-linux/commit/41c5f12ae4bbe5e79676abc5b90700d724dd3109 - I haven't tested it yet.
