### ISSUE TITLE
document why `/etc/yum.real.repos.d/qubes-cached.repo` is using `repo_gpgcheck = 0`

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#7561]
Just had a discussion about Qubes insecurity since allegedly not all packages are verified.

dom0

    sudo grep -r gpgcheck /etc

See:

    cat /etc/yum.real.repos.d/qubes-cached.repo 

```
[qubes-dom0-cached]
name = Qubes OS Repository for Dom0
baseurl = file:///var/lib/qubes/updates
gpgkey = file:///etc/pki/rpm-gpg/RPM-GPG-KEY-qubes-4-primary
gpgcheck = 1
repo_gpgcheck = 0
metadata_expire = 0
```

A comment in the same file would be useful.

https://github.com/QubesOS/qubes-core-admin-linux/blob/master/dom0-updates/qubes-cached.repo#L6

I guess it's not needed?

**Comment by marmarek** [comment]
You have the explanation in the link you pasted (commit message):
> dom0 generates its own metadata, which obviously isn’t signed.

**Comment by adrelanos** [comment]
PR:
https://github.com/QubesOS/qubes-core-admin-linux/pull/100

maybe related:
https://github.com/QubesOS/qubes-issues/issues/7414
