### ISSUE TITLE
qvm-open-in-dvm not opening in default browser

### ISSUE THREAD

**Issue by HPOA909** [QubesOS/qubes-issues#7562]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

R4.1

### Brief summary

As I recently switched to Brave from Firefox, I notice that the command doesn't want to open Brave despite I removed Firefox. I have every single files in every single qubes were defaulted to open with qvm-open-in-dvm, and yet, none of those files open in the default Brave Browser to listen some offline songs. 

Source: https://forum.qubes-os.org/t/qvm-open-in-dvm-feature-request-help/11945

### Steps to reproduce

1. Make the application open with the defaulted web browser
2. Make standalone command settings that dedicated to qvm-open-in-dvm
3. Makes sure that the application works with any available web browsers

### Expected behavior

I expected the application/command open the default web browser rather than Firefox.

### Actual behavior

Me: *open with qvm-open-in-dvm
qvm-open-in-dvm: *opens
dispXXXX: Nope, not this time. I didn't see a web browser here.
Me: I saw the web browser

**Comment by unman** [comment]
This works as expected for me, but I dont understand your report.
You say that you "removed Firefox", but your "Expected" suggests that
Firefox is still present.

What is "the application" in Step 1 and step 3?
What does Step 2 *mean*?

Can you confirm that you can use qvm-open-in-dvm to open a (saved) web
page, and that it will open in Brave?
What steps have you taken (in detail) to ensure that "offline songs"
will open in Brave? What format are those "offline songs"?
Are you able to open these songs in the disposable template and have
them open in Brave? How have you confirmed this?
