### ISSUE TITLE
Unclear vulnerability to Spectre-BHB attacks

### ISSUE THREAD

**Issue by domUser** [QubesOS/qubes-issues#7568]
### Qubes OS release
Qubes 4.1

### Brief summary
My system runs on a 10th generation Intel processor. According to QSB-077, only the 11th generation and later are affect by Spectre-BHB attacks. However, the current kernel warns of possible data leaks via such attacks.

### Steps to reproduce
1. Install Qubes 4.1 on a machine with a 10th generation Intel processor.
2. Update dom0.
3. Reboot.
4. Run `journalctl -b` and notice the following message:
> dom0 kernel: Spectre V2 : WARNING: Unprivileged eBPF is enabled with eIBRS on, data leaks possible via Spectre v2 BHB attacks!

### Expected behavior
If the vulnerability logged by the kernel is legitimate, it would be nice to have the relevant kernel patches being backported. Otherwise, QSB-077 could be updated to include the 10th generation processors.
If the kernel warning is a false positive, maybe it could be explained in QSB-077.

### Actual behavior
The kernels 5.10.112-1 and 5.10.121-1 warn of possible data leaks.
[A fix has been pushed to the kernel 5.16 and above](https://www.intel.com/content/www/us/en/security-center/advisory/intel-sa-00598.html). When testing the version 5.18.3-1 from the current-testing repository, no Spectre-BHB warning is logged.

**Comment by marmarek** [comment]
The description in QSB-077 is accurate. Dom0 kernel may warn about what it sees, but user/root (or user/kernel) boundary within dom0 is not really a security boundary (user in dom0 has full control over the system anyway). The cross-vm aspects (which is a security boundary) of this issue are mitigated at Xen level, and dom0 kernel has no idea about them.

**Comment by domUser** [comment]
Sorry for having raised a non-issue. Thanks for the explanation.
