### ISSUE TITLE
Installation failure on Ryzen 9 6900HS

### ISSUE THREAD

**Issue by n0madK** [QubesOS/qubes-issues#7570]
### Qubes OS release
Qubes 4.1 ISO built with kernel-latest 5.18.3-1.fc32.x86_64

### Brief summary
Booting with Qubes 4.1, kernel 5.17 or lower results in a black screen,
booting with kernel 5.18.3-1.fc32.x86_64 hangs with some errors.

Booting the installer:
```
[    6.325255] dracut-pre-udev[643]: modprobe: FATAL: Module cramfs not found in
 directory /lib/modules/5.18.3-1.fc32.qubes.x86_64
[    6.467288] dracut-pre-udev[694]: modprobe: FATAL: Module floppy not found in directory /lib/modules/5.18.3-1.fc32.qubes.x86_64
[   OK   ] Started Show Plymouth Boot Screen.
[   OK   ] Started Forward Password Requests to Plymouth Directory Watch.
[   OK   ] Reached target Local Encryption Volumes.
[   OK   ] Reached target Paths.
[FAILED] Failed to start udev Wait for Complete Device Initialization.
See 'systemctl status systemd-udev-settle.service' for details.
[  OK  ] Started Device-Mapper Multipath Device Controller.
[  OK  ] Reached target Local File System (Pre).
[  OK  ] Reached target Local File System.
            Starting Open-iSCSI...
            Starting Create Volatile Files and Directories...
[  OK  ] Started Open iSCSI
            Starting dracut initqueue hook...
[  OK  ] Finished Create Volatile Files and Directories.
[  OK  ] Reached target System Initialization."
[  OK  ] Reached target Basic System.
```

Booting in troubleshooting mode:
```
...
[  OK  ] Started Device-Mapper Multipath Device Controller.
[  OK  ] Reached target Local File System (Pre).
[  OK  ] Reached target Local File System.
            Starting Open-iSCSI...
            Starting Create Volatile Files and Directories...
[  OK  ] Started Open iSCSI
            Starting dracut initqueue hook...
[  OK  ] Finished Create Volatile Files and Directories.
[  OK  ] Reached target System Initialization."
[  OK  ] Reached target Basic System.
[  128.328664] systemd-gpt-auto-generator[1087]: EFI loader partition unknown, exiting.
[  128.329699] systemd-gpt-auto-generator[1087]: (The boot loader did not set EFI variable LoaderDevicePartUUID.)
```
### Steps to reproduce
- Download [Qubes-20220615-kernel-latest-x86_64.iso](https://qubes.notset.fr/iso/Qubes-20220615-kernel-latest-x86_64.iso)
- Load onto USB
- Boot USB
- See errors above

What can I do to troubleshoot this further?

**Comment by DemiMarie** [comment]
Can you provide the output of `journalctl -b`?

**Comment by n0madK** [comment]
It is stopped at that point in the log, unresponsive to key commands. Do you know how I can get a journalctl output?

**Comment by n0madK** [comment]
![1](https://user-images.githubusercontent.com/58864335/174295321-0a1cdf95-b044-4d95-bc1b-4949024bb510.jpg)
![2](https://user-images.githubusercontent.com/58864335/174295336-39a08924-c315-4422-a7ed-be67cd73369f.jpg)
![3](https://user-images.githubusercontent.com/58864335/174295346-ab8081de-2f50-4d83-9ba4-e2fb79d87575.jpg)
![4](https://user-images.githubusercontent.com/58864335/174295349-92e027b3-01ad-43fd-918e-b2b1531ec272.jpg)
![5](https://user-images.githubusercontent.com/58864335/174295357-04bd8737-a39e-4e90-9776-76be435680fb.jpg)
![6](https://user-images.githubusercontent.com/58864335/174295363-86a3a92c-0be1-45f7-a78f-73443f892764.jpg)
![7](https://user-images.githubusercontent.com/58864335/174295367-2eea3b4f-4663-4bac-bdb2-4afe98f052c9.jpg)

**Comment by tzwcfq** [comment]
Maybe you have some problems with your USB 3.0. Try to disable USB 3.0 in BIOS or look for xHCI configs there and try to change them.

**Comment by n0madK** [comment]
Adding `iommu=soft swiotlb=force` to the grub kernel entry brings it up a little further to some amdgpu problems. Settings `dom0_max_vcpus=1 dom0_vcpus_pin` on the xen cmdline seems to be the winner though. There seems to be some race conditions as sometimes it boots and sometimes it hangs.

**Comment by itaishmueli** [comment]
I was facing the exact same logs as @n0madK , and I can confirm that adding `dom0_max_vcpus=1 dom0_vcpus_pin` solved the problem for me, but I now cannot boot without it.
Without it the configuration on the first boot fails (getting similar logs in journalctl), and on subsequent boot the password field was spammed without me pressing the keys.

**Comment by DemiMarie** [comment]
Interesting

**Comment by itaishmueli** [comment]
tried installing 4.0.4, some logs appear briefly and then I'm left with a blank screen.

**Comment by maltesl** [comment]
The `xhci_hcd` errors followed by the `nvme` timeout look exactly like #7433.

**Comment by DemiMarie** [comment]
Duplicate?

**Comment by andrewdavidwong** [comment]
This appears to be a [duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If anyone believes this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Comment by lankredotp41** [comment]
Issue https://github.com/QubesOS/qubes-issues/issues/7433 seems to be removed from github.

**Comment by andrewdavidwong** [comment]
> Issue https://github.com/QubesOS/qubes-issues/issues/7433 seems to be removed from github.

Interesting. Well, I guess this is no longer a duplicate, then (since a thing can't duplicate something that doesn't exist).
