### ISSUE TITLE
Qubes desktop hangs everything except for mouse cursor and must be rebooted

### ISSUE THREAD

**Issue by ddevz** [QubesOS/qubes-issues#7572]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
4.1

### Brief summary
It started as this: 
Qubes has started to occasionally lock the desktop where nothing can be clicked, however the mouse cursor can still move around the screen.  If I wait for a like 15 seconds or something both screens will flash to black and then a second later everything will resume like normal.  This has been going on for over a week (a couple weeks?).  I believe it stopped happening for a while in that timeframe.

The new issue:
I did a update of dom0 yesterday, turned the system off including the monitors, and today I powered up and 2 hours later the desktop froze, I could still move the mouse, but I could not click.  However this time it never came back.  The keyboard was also frozen (I.E. the caps lock light wouldn't even turn on).

Possible related things:
  mouse goes through the first sys-usb qube
  keyboard goes into the PS/2 socket
  a system backup was running
  Things were working fine 2 months ago
  I am using dom0 desktop, not sys-gui desktop

### journalctl shows that some kind of computing was still happening after the screen freeze:
Jun 16 11:57:49 dom0 qrexec-policy-daemon[3114]: qrexec: whonix.SdwdateStatus+: sys-whonix -> disp7147: allowed to disp7147
Jun 16 11:57:49 dom0 qrexec-policy-daemon[3114]: qrexec: whonix.SdwdateStatus+: sys-whonix -> disp8134: allowed to disp8134
Jun 16 11:57:56 dom0 systemd-logind[1998]: Power key pressed.
Jun 16 11:57:59 dom0 qrexec-policy-daemon[3114]: qrexec: whonix.SdwdateStatus+: sys-whonix -> disp7147: allowed to disp7147
Jun 16 11:57:59 dom0 qrexec-policy-daemon[3114]: qrexec: whonix.SdwdateStatus+: sys-whonix -> disp8134: allowed to disp8134
Jun 16 11:58:09 dom0 qrexec-policy-daemon[3114]: qrexec: whonix.SdwdateStatus+: sys-whonix -> disp7147: allowed to disp7147
Jun 16 11:58:09 dom0 qrexec-policy-daemon[3114]: qrexec: whonix.SdwdateStatus+: sys-whonix -> disp8134: allowed to disp8134
Jun 16 11:58:19 dom0 qrexec-policy-daemon[3114]: qrexec: whonix.SdwdateStatus+: sys-whonix -> disp7147: allowed to disp7147
Jun 16 11:58:19 dom0 qrexec-policy-daemon[3114]: qrexec: whonix.SdwdateStatus+: sys-whonix -> disp8134: allowed to disp8134
Jun 16 11:58:29 dom0 qrexec-policy-daemon[3114]: qrexec: whonix.SdwdateStatus+: sys-whonix -> disp7147: allowed to disp7147
Jun 16 11:58:29 dom0 qrexec-policy-daemon[3114]: qrexec: whonix.SdwdateStatus+: sys-whonix -> disp8134: allowed to disp8134
Jun 16 11:58:39 dom0 qrexec-policy-daemon[3114]: qrexec: whonix.SdwdateStatus+: sys-whonix -> disp7147: allowed to disp7147
Jun 16 11:58:39 dom0 qrexec-policy-daemon[3114]: qrexec: whonix.SdwdateStatus+: sys-whonix -> disp8134: allowed to disp8134
Jun 16 11:58:49 dom0 qrexec-policy-daemon[3114]: qrexec: whonix.SdwdateStatus+: sys-whonix -> disp7147: allowed to disp7147
Jun 16 11:58:49 dom0 qrexec-policy-daemon[3114]: qrexec: whonix.SdwdateStatus+: sys-whonix -> disp8134: allowed to disp8134
Jun 16 11:58:55 dom0 systemd-logind[1998]: Power key pressed.
Jun 16 11:58:59 dom0 qrexec-policy-daemon[3114]: qrexec: whonix.SdwdateStatus+: sys-whonix -> disp7147: allowed to disp7147
Jun 16 11:58:59 dom0 qrexec-policy-daemon[3114]: qrexec: whonix.SdwdateStatus+: sys-whonix -> disp8134: allowed to disp8134
-- Reboot --
Jun 16 12:01:38 dom0 kernel: Linux version 5.10.112-1.fc32.qubes.x86_64 (mockbuild@ff7978a4d91e45159470e883db984435) (gcc (GCC) 10.3.1 20210422 (Red Hat 10.3.1-1), GNU ld version 2.34-6.fc3

The "Power key pressed" is me giving up on it comming back and hitting the front power button in hopes that doing that would initiate a shutdown.  (is the power button supposed to do something?)

### I suspect this is the journalctl time period that the freeze started at, as this clip seems to start with user interaction, and nothing happens after this except lines similar to above.

Jun 16 11:20:10 dom0 qubesd[3108]: vm.disp8134: Activating the disp8134 VM
Jun 16 11:20:10 dom0 audit[26845]: CRED_ACQ pid=26845 uid=0 auid=4294967295 ses=4294967295 msg='op=PAM:setcred grantors=pam_rootok acct="user" exe="/usr/sbin/runuser" hostname=? addr=? term>
Jun 16 11:20:10 dom0 runuser[26845]: pam_unix(runuser:session): session opened for user user by (uid=0)
Jun 16 11:20:10 dom0 kernel: audit: type=1103 audit(1655396410.874:400): pid=26845 uid=0 auid=4294967295 ses=4294967295 msg='op=PAM:setcred grantors=pam_rootok acct="user" exe="/usr/sbin/ru>
Jun 16 11:20:10 dom0 kernel: audit: type=1105 audit(1655396410.874:401): pid=26845 uid=0 auid=4294967295 ses=4294967295 msg='op=PAM:session_open grantors=pam_keyinit,pam_limits,pam_unix acc>
Jun 16 11:20:10 dom0 audit[26845]: USER_START pid=26845 uid=0 auid=4294967295 ses=4294967295 msg='op=PAM:session_open grantors=pam_keyinit,pam_limits,pam_unix acct="user" exe="/usr/sbin/run>
Jun 16 11:20:12 dom0 kernel: xen-blkback: backend/vbd/23/51712: using 2 queues, protocol 1 (x86_64-abi) persistent grants
Jun 16 11:20:12 dom0 kernel: xen-blkback: backend/vbd/23/51728: using 2 queues, protocol 1 (x86_64-abi) persistent grants
Jun 16 11:20:13 dom0 kernel: xen-blkback: backend/vbd/23/51744: using 2 queues, protocol 1 (x86_64-abi) persistent grants
Jun 16 11:20:13 dom0 kernel: xen-blkback: backend/vbd/23/51760: using 2 queues, protocol 1 (x86_64-abi) persistent grants
Jun 16 11:20:15 dom0 runuser[26845]: pam_unix(runuser:session): session closed for user user
Jun 16 11:20:15 dom0 audit[26845]: USER_END pid=26845 uid=0 auid=4294967295 ses=4294967295 msg='op=PAM:session_close grantors=pam_keyinit,pam_limits,pam_unix acct="user" exe="/usr/sbin/runu>
Jun 16 11:20:15 dom0 audit[26845]: CRED_DISP pid=26845 uid=0 auid=4294967295 ses=4294967295 msg='op=PAM:setcred grantors=pam_rootok acct="user" exe="/usr/sbin/runuser" hostname=? addr=? ter>
Jun 16 11:20:15 dom0 kernel: audit: type=1106 audit(1655396415.538:402): pid=26845 uid=0 auid=4294967295 ses=4294967295 msg='op=PAM:session_close grantors=pam_keyinit,pam_limits,pam_unix ac>
Jun 16 11:20:15 dom0 kernel: audit: type=1104 audit(1655396415.538:403): pid=26845 uid=0 auid=4294967295 ses=4294967295 msg='op=PAM:setcred grantors=pam_rootok acct="user" exe="/usr/sbin/ru>
Jun 16 11:20:15 dom0 qrexec-policy-daemon[3114]: qrexec: whonix.SdwdateStatus+: sys-whonix -> disp7147: allowed to disp7147
Jun 16 11:20:17 dom0 qrexec-policy-daemon[3114]: qrexec: qubes.WindowIconUpdater+: disp8134 -> @adminvm: allowed to dom0
Jun 16 11:20:17 dom0 qrexec-policy-daemon[3114]: qrexec: whonix.NewStatus+status: disp8134 -> sys-whonix: allowed to sys-whonix
Jun 16 11:20:18 dom0 qrexec-policy-daemon[3114]: qrexec: whonix.SdwdateStatus+: sys-whonix -> disp8134: allowed to disp8134
Jun 16 11:20:19 dom0 qrexec-policy-daemon[3114]: qrexec: whonix.SdwdateStatus+: sys-whonix -> disp7147: allowed to disp7147
Jun 16 11:20:19 dom0 qrexec-policy-daemon[3114]: qrexec: whonix.SdwdateStatus+: sys-whonix -> disp8134: allowed to disp8134
Jun 16 11:20:29 dom0 qrexec-policy-daemon[3114]: qrexec: whonix.SdwdateStatus+: sys-whonix -> disp7147: allowed to disp7147
Jun 16 11:20:29 dom0 qrexec-policy-daemon[3114]: qrexec: whonix.SdwdateStatus+: sys-whonix -> disp8134: allowed to disp8134
Jun 16 11:20:38 dom0 qrexec-policy-daemon[3114]: qrexec: whonix.NewStatus+status: disp8134 -> sys-whonix: allowed to sys-whonix
Jun 16 11:20:38 dom0 qrexec-policy-daemon[3114]: qrexec: whonix.SdwdateStatus+: sys-whonix -> disp8134: allowed to disp8134

**Comment by DemiMarie** [comment]
Can you use sysrq to kill the X server?

**Comment by ddevz** [comment]
Is sysrq enabled in qubes 4.1 by default?  If so, what key sequence is it bound to?

**Comment by ddevz** [comment]
You are proposing enabling sysrq features via /proc before a lockup, then doing Alt-Sysrq-k after a lockup, right?

If so, I'll try that next time

**Comment by ddevz** [comment]
The screen went black for a moment, came back but desktop was still motionless.  However hovering over the volume icon and scrolling the mouse wheel did make the music which was continuing to play to get louder, and the "hamburger button" in a whonix instance was flashing rapidly.

However, the keyboard did not lock this time, and I found more interesting information:

```
Jun 17 12:50:54 dom0 kernel: radeon 0000:b3:00.0: ring 0 stalled for more than 10080msec
Jun 17 12:50:54 dom0 kernel: radeon 0000:b3:00.0: GPU lockup (current fence id 0x00000000002b9af8 last fence id 0x00000000002b9b1f on ring 0)
Jun 17 12:50:54 dom0 kernel: radeon 0000:b3:00.0: failed to get a new IB (-35)
Jun 17 12:50:54 dom0 kernel: [drm:radeon_cs_ib_fill [radeon]] *ERROR* Failed to get ib !
```



possibly relavant lspci output:
```
00:1f.3 Audio device: Intel Corporation Device a1f0 (rev 09)
	Subsystem: ASRock Incorporation Device f892
	Kernel driver in use: snd_hda_intel
	Kernel modules: snd_hda_intel
```
  [[[Note: this is what the music was playing to]]]


```
b3:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Cedar GL [FirePro 2460]
	Subsystem: Advanced Micro Devices, Inc. [AMD/ATI] Device 2002
	Kernel driver in use: radeon
	Kernel modules: radeon
b3:00.1 Audio device: Advanced Micro Devices, Inc. [AMD/ATI] Cedar HDMI Audio [Radeon HD 5400/6300/7300 Series]
	Subsystem: Advanced Micro Devices, Inc. [AMD/ATI] Cedar HDMI Audio [Radeon HD 5400/6300/7300 Series]
	Kernel driver in use: snd_hda_intel
	Kernel modules: snd_hda_intel
```
   [[[Note: b3:00.1 audio is unused and does not seem to show up in the "Output Devices" of the dom0 volume control mixer]]]

Strange that a "intel" module is loaded on a AMD card... Could that be the problem?

Possible options:
  Should I blacklist the unused b3:00.1?  Would this cause problems if I was to try sys-gui-gpu on this system later on?
  Should i try a different driver then radeon and try amdgpu instead?

**Comment by DemiMarie** [comment]
I suggest trying AMDGPU if it supports your card.  I believe Radeon is a legacy driver.  Blocklisting `b3:00.1` should be harmless unless you use HDMI audio.

**Comment by ddevz** [comment]
I replaced the card and the newer card automatically uses the amdgpu driver, and after booting up was able to close https://github.com/QubesOS/qubes-issues/issues/7434 (LUKS login screen strangeness)

I'll wait and see if this problem happens again, but the problem might be solved.

**Comment by maltfield** [comment]
I'm also having this issue on a Lenovo Thinkpad X1 Carbon 6th Generation. At the moment everything is up-to-date.

Sometimes, after I leave my laptop locked for some hours, I come back to it and unlock it. The xscreensaver password prompt works flawlessly, but after I type the correct password, the screen is black except for the cursor. Curiously, as I move the mouse around the screen, it switches from a pointer to a text-input-cursor depending on where it is. Also, the location changes if I use ctrl+alt+arrow to change the virtual desktop. So it's like all my windows are there and I can interact with everything -- I just can't see anything because it's all black.

This happens twice in the past 24 hours. Very annoying because I have to just hold the power button, boot fresh, and then launch all my AppVMs to get back to work.

I'm surprised this is an open bug because isn't the X1 carbon the same laptop employed by the QubesOS devs? What generation of the X1 carbon do you folks use?
