### ISSUE TITLE
ERROR: Logical volume "vm-sys-net-root-snap" already exists in volume group "qubes_dom0"

### ISSUE THREAD

**Issue by Sirwhofromwhere** [QubesOS/qubes-issues#7573]
Relatively fresh install of Qubes 4.1

**Affected component(s):**
All VM's

After a system crash sys-firewall, sys-usb, and sys-net are failing to start. I get various errors, when I try to start sys-net manually, I get:

"Sys-net has failed to start: sys-net-private-snap already exists in volume group "qubes_dom0"

For sys-firewall and sys-usb, systemctl status gives this as well as other  information (this seems most relevant, can post all)

For sys-firewall:

vm-sys-net-volatile already exists in volume group "qubes_dom0"

For sys-usb:

Can't create snapshot vm-KeepasXC-private-snap as origin vm-KeepassXC-private is not suspended.

This appears to be similar to issue #3964 

Any advice is appreciated.

**Comment by andrewdavidwong** [comment]
This appears to be a [duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If anyone believes this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Comment by andrewdavidwong** [comment]
> This appears to be similar to issue https://github.com/QubesOS/qubes-issues/issues/3964

Since the error message is exactly the same, unless you have some reason to think this is a separate bug (I didn't see any such reason mentioned here), then let's assume it's the same for now.

**Comment by Sirwhofromwhere** [comment]
@andrewdavidwong Sorry I haven't used github so I wasn't sure if I needed to create another. My mistake.

**Comment by andrewdavidwong** [comment]
No worries.
