### ISSUE TITLE
Fresh install 4.1 experiencing sudden VM shutdown / Dom0 freezing. 

### ISSUE THREAD

**Issue by Sirwhofromwhere** [QubesOS/qubes-issues#7579]
**Qubes-os version**
4.1

**Hardware**
Thinkpad w530 k1000m DGPU 16gb ram on HEADS firmware

**Are you using any [testing](https://www.qubes-os.org/doc/testing/) repositories? If so, please list them and where they are enabled (i.e., dom0, TemplateVM, or StandaloneVM).**

Stock defaults. Fresh install updated dom0.

**Affected component(s) or functionality**

Laptop freezing under load. 

**Brief summary**

When I have relatively small numbers of Appvm's doing simple loads running, Qubes freezes. Perhaps a RAM issue, but I am not sure how to diagnose the exact issue, where the relevant log is.

**edit:** Under further inspection I believe I have misinterpreted xentop, and the issue isn't an overload of CPU activity, but RAM. When I create a new VM, the VM is using all the maximum RAM allocated. However, I don't think it is properly memory balancing.

Now that I have adjusted the RAM levels in each VM (Sys-whonix was using 4gb), the laptop is now functional, but I am still noticing that the VM is eating up the max allocated RAM. Is this a misunderstanding of mine of RAM, or an issue of memory balancing?

**How Reproducible**
Every VM

**How to reproduce**
Have enough VM's open that's total RAM allocation exceeds total RAM.

**Expected behavior**
VM's to not immediately use 100% of their max ram allocation.

**Actual behavior**
VM's use 100% of their RAM allocation.

**What have you done to try and fix the issue**
Reduce RAM levels, which helps but hasn't addressed the key issue

**Further information**

In top the VM's often aren't using the max ram allocation, often a reasonable amount, but the total RAM used by the VM is the max allocated. Is this me fundamentally misunderstanding the RAM allocaiton?

Let me know what I can produce to help troubleshoot this issue. Your assistance is greatly appreciated.

**Comment by brendanhoar** [comment]
Does the problem occur if you haven't used the sleep function since the last reboot?

Have you tried kernel-latest in dom0 and/or in VMs?

B

**Comment by Sirwhofromwhere** [comment]
@brendanhoar Thanks for your response. I believe I've been dealing with this issue since my first boot in to the system, so I don't think it was triggered by any activity within Qubes on my behalf.

The problem does occur without using the sleep function between the last reboot & the current experience of the problem.

By kernel-latest, is this for updates? I just ran a dom0 update & updated the kernel. When I type that in to dom0 I get command not found, is there something I am not understanding there?

Thank you.

**Comment by DemiMarie** [comment]
@Sirwhofromwhere `kernel-latest` refers to the `kernel-latest` package, which you can install with `sudo qubes-dom0-update kernel-latest` in dom0.

**Comment by Sirwhofromwhere** [comment]
@DemiMarie First of all thanks for your response. Unfortunately I misdiagnosed the issue. I read the xentop information wrong and falsely thought CPU was being ate up, in fact I believe the issue is with the RAM.

Perhaps the issue is in my failure to understand how the RAM allocation works, but all qubes are eating up their full RAM allocation. They aren't using it, as I can see in 'top', but they are reserving the full amount. Is this expected behavior? I thought memory balancing was supposed to prevent things like sudden crashing due to a lack of free RAM.

I've since gone and adjusted the max RAM allocation and I have a usable system that is no longer inexplicably crashing, so that's great progress.

Is there a way to test the RAM itself in Qubes, or would I need to boot a live usb to do so, given the compartmentalization.

Thanks again Marie & co.

**Comment by andrewdavidwong** [comment]
Please note that the issue tracker (`qubes-issues`) is not intended to serve as a help desk or tech support center. Instead, we've set up other [venues where you can ask for help and support, ask questions, and have discussions](https://www.qubes-os.org/support/). (By contrast, the issue tracker is more of a technical tool intended to support our developers in their work.) Thank you for your understanding!

**Comment by brendanhoar** [comment]
> Perhaps the issue is in my failure to understand how the RAM allocation works, but all qubes are eating up their full RAM allocation. They aren't using it, as I can see in 'top', but they are reserving the full amount. Is this expected behavior? I thought memory balancing was supposed to prevent things like sudden crashing due to a lack of free RAM.

The memory balancing scheme in Qubes will allow VMs to use their full allotment *until* there is a VM that needs memory not already free in the memory pool, at which point the balloon driver in VMs will be asked to give up memory and if they agree their memory allotment will shrink.

B

**Comment by Sirwhofromwhere** [comment]
@brendanhoar @andrewdavidwong  @DemiMarie What are some ways I can diagnose the issues to better create a ticket for help?

The RAM appears to not be dynamically balancing, and it seems as though the VM is not giving up its excess RAM to other VM's in need, causing crashing.

Also, I am having freezing issues sometimes even when nothing is running. I will leave the screen unattended and return with no appvm's open, and it will be frozen.

I will open a single youtube video in one of my VM's, and my CPU usage in that VM will be too high and crashing the tab, then eventually crashing the VM if I persist.

This is after trying to add more Virtual CPU's etc. to the VM.

On an I7-3840QM with 16gb RAM I can't believe this is expected performance, there is some issue, but I don't know how to collect the crash logs & relevant information to properly create a framework for investigation.

Thank you for any help you can provide.
