### ISSUE TITLE
Qubes colored-border malfunctioning in sys-gui-gpu

### ISSUE THREAD

**Issue by ZYousef** [QubesOS/qubes-issues#7580]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
Qubes R4.1

### Brief summary
Window borders not working inside sys-gui-gpu environment.

### Steps to reproduce
Setting up sys-gui-gpu using salts formula

### Expected behavior

sys-gui-gpu GUI runs properly color-coded windows.

### Actual behavior

All windows appear in gray, however, right-clicking inside vm-gui shows colored border menu options.

**Comment by fepitre** [comment]
Which theme do you actually use inside sys-gui-gpu? Let me guess, is it arc-theme?

**Comment by DemiMarie** [comment]
@andrewdavidwong the reason I marked this as security is because it would be a security problem if it happened in dom0 without significant customizations.

**Comment by fepitre** [comment]
I've suggested `arc-theme` because of https://github.com/horst3180/arc-theme/pull/801. I don't think this is a security issue because by default we provide a working theme.

**Comment by DemiMarie** [comment]
@fepitre That makes this a bug in our patched xfwm4.

**Comment by marmarek** [comment]
Do you have current-testing repository enabled in dom0? If yes, you probably got sys-gui-gpu based on fedora-36(-xfce) template, which is still in testing - in which case, install updates from current-testing repository in that template too.

**Comment by fepitre** [comment]
@DemiMarie @marmarek Maybe this is the time to support coloring theme like described by comments in linked issue?

**Comment by ZYousef** [comment]
Nope, I wasn't using any themes @fepitre, updating fedora-34-xfce fixed the issue!

**Comment by andrewdavidwong** [comment]
Closing as "not an issue" (the reported behavior is not a bug, or the proposal is not suitable as an enhancement or task). If anyone believes this is a mistake, please leave a comment, and we'll be happy to take another look. Thank you.
