### ISSUE TITLE
Qubes system requirements shows IOMMU as minimum requirement but Qubes HCL contradicts it and shows that Qubes can run without IOMMU

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#7581]
https://www.qubes-os.org/doc/system-requirements/ expresses under `Minimum` that `Intel VT-d or AMD-Vi (also known as AMD IOMMU)` is an absolute hard requirement and without it Qubes won't run.

On the other hand https://www.qubes-os.org/hcl/ shows a large table of computers that say `IOMMU: no` while at the same time some of them express `HVM: yes` as well as one saying `Qubes: R4.0`. This strongly implies that `IOMMU` is not an absolute hard requirement and Qubes can run without IOMMU.

It's a contradiction.

Furthermore, on https://www.qubes-os.org/hcl it's states `IOMMU` `Intel VT-d or AMD IOMMU technology (required for effective isolation of network VMs and PCI passthrough).` Ok, so `IOMMU` is required for `required for effective isolation of ...`. That implies, without `IOMMU` there is simply no `required for effective isolation of ...`. That might still be acceptable for some users. In absence of any other operating systems providing `required for effective isolation of ...` on hardware without `IOMMU` that seems OK.

Suggested fix: Move `Intel VT-d or AMD-Vi (also known as AMD IOMMU)` from `Minimum` to `Recommended`.
(But that's already the case. So just remove IOMMU from `Minimum`.)

**Comment by marmarek** [comment]
It was the case for R4.0, not for R4.1 anymore. Your sys-net/sys-usb won't start at all without IOMMU there (you could modify your system to workaround it, but that can't be called "Qubes works on this system" anymore, because by default it does not).
