### ISSUE TITLE
Lost access to Desktop Environment

### ISSUE THREAD

**Issue by ymbr4DA** [QubesOS/qubes-issues#7583]
Qubes 4.1
Coreboot 4.14
Purism Librem 15v3
Intel Core i7

Using my phone account.

I was working on my machine, when all of a sudden my screen lost all the surrounding Qubes GUI/icons. (Please see first attached picture)

![367117EA-2781-46BC-82D7-F1CF5275BC18](https://user-images.githubusercontent.com/106555684/174696066-d5aedd6e-7720-44c1-bc24-6f96abae6514.jpeg)

I did still have applications open at this time, but I minimized them since it was unreleased work (once minimized, they disappeared forever since I lost my desktop environment).

I decided to logout and log back in and this is what I had

![74509250-30ED-4273-A0B7-4F7228306071](https://user-images.githubusercontent.com/106555684/174696679-9108cb04-534a-460d-a069-bc55c6c191f3.jpeg)

Thinking a reboot might help, but I was back at this:

![AC383A52-FF90-43E7-AFC1-D0F1A9392025](https://user-images.githubusercontent.com/106555684/174696240-07ae065e-2844-4040-a6b8-84b8c3a99ccb.jpeg)

Unfortunately, I have absolutely no idea how to reproduce, ~~and can’t check any logs.~~

Any ideas?

Thank you

Robert

**Comment by ymbr4DA** [comment]
I believe I found the pertinent logs:
(Apologize for the pictures instead of copy/paste, but it is all I can do without my computer working, and the quality is fortunately quite good). 

![76D07AE4-4B17-41F9-897F-98AEAE9A1D59](https://user-images.githubusercontent.com/106555684/174705631-e0629b65-d446-46a8-9bf1-e9d0c24dd03e.jpeg)

![3D672A38-F073-43B5-B0C8-ECC3E8117F8C](https://user-images.githubusercontent.com/106555684/174705652-bae3da23-7ecb-4c3e-869f-77bb2eecb51b.jpeg)

![AE57D0DB-8FF0-4CC8-8DC8-4EBBBF6CAB86](https://user-images.githubusercontent.com/106555684/174705669-088e9794-8641-4bac-96cf-3df70eced325.jpeg)

![04F76FD0-8367-4746-A64B-FA2F91048A2C](https://user-images.githubusercontent.com/106555684/174705687-8a678c47-9d91-45cd-9aa7-7d1a1849e76a.jpeg)

![0F52F79E-BD93-4EF5-8F91-1B009729CF78](https://user-images.githubusercontent.com/106555684/174705710-d4cef46b-09dd-4e73-aa87-65882fa28e27.jpeg)

![F4A401E8-8EEB-4654-9A74-44610BA2452A](https://user-images.githubusercontent.com/106555684/174705739-d78c961f-b458-4568-87dc-6b042109e198.jpeg)

![2011C040-44BF-4AC6-ACD0-6DD8F82F74CB](https://user-images.githubusercontent.com/106555684/174705764-239cf059-c6b3-44d2-bbb7-01d74c7e07dd.jpeg)

![EB786A48-D3A7-4D73-A005-6D2AB5338EE7](https://user-images.githubusercontent.com/106555684/174705809-de6a9fe8-60c0-4992-8d02-f4521683639d.jpeg)

**Comment by ymbr4DA** [comment]
Tried various commands to restart xfce; no luck.

![6B3539C2-5ED5-454D-913B-52B79AE4091C](https://user-images.githubusercontent.com/106555684/174717588-09acea55-4fda-4047-87ce-84c5a16bc2de.jpeg)

**Comment by ymbr4DA** [comment]
Tried killing the process to restart. Did not work:

![306AECC8-EE28-45D4-A582-159D2C51A450](https://user-images.githubusercontent.com/106555684/174721716-9c4541c6-843c-4c6c-a69b-b10c0b7ee47c.jpeg)

![43E012A0-204F-47EE-A6FC-69832BA22D6E](https://user-images.githubusercontent.com/106555684/174721734-c188b4d2-df6f-4a1c-8b69-79ad3767fa9c.jpeg)

Deleted `/tmp/.X0-lock` as suggested in one of the outputs and tried some of the commands again, no change.

**Comment by andrewdavidwong** [comment]
Please note that the issue tracker (`qubes-issues`) is not intended to serve as a help desk or tech support center. Instead, we've set up other [venues where you can ask for help and support, ask questions, and have discussions](https://www.qubes-os.org/support/). (By contrast, the issue tracker is more of a technical tool intended to support our developers in their work.) Thank you for your understanding!

**Comment by deeplow** [comment]
Discussion followed on the forum:

https://forum.qubes-os.org/t/lost-access-to-desktop-environment-up-to-500-bounty/12132/
