### ISSUE TITLE
Provide choice to install up-to-date linux firmware in dom0

### ISSUE THREAD

**Issue by logoerthiner1** [QubesOS/qubes-issues#7585]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### The problem you're addressing (if any)

Currently dom0 is using mostly firmware version coming from its fedora distro, which is usually out of date.

Some firmware packages that is required to be installed in dom0, for example alsa-sof-firmware, linux-firmware, are not the latest by default. Qubes users of the latest hardwares usually demand the latest firmware and they get usually confused and failed to notice that the default installed firmware is not the latest.

Also it may be risky for anyone trying the latest firmware that their computer fails for the firmware update.

### The solution you'd like

Either document about how to correctly, safely, and securely apply firmware updates in dom0, or update the firmware version in Qubes repo.

### The value to a user, and who that user might be

Allow user of the latest hardware to correctly update firmwares.

**Comment by marmarek** [comment]
Updated alsa-sof-firmware is available in current-testing: https://github.com/QubesOS/updates-status/issues/3022
