### ISSUE TITLE
unable to setup sys-gui-gpu correctly 

### ISSUE THREAD

**Issue by ZYousef** [QubesOS/qubes-issues#7587]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

R4.1

### Brief summary

enabling sys-gui-gpu breaks the OS, and makes it restarts infinitely.

### Steps to reproduce

_sudo qubesctl top.enable qvm.sys-gui-gpu
sudo qubesctl top.enable qvm.sys-gui-gpu pillar=True
sudo qubesctl --all state.highstate
sudo qubesctl state.sls qvm.sys-gui-gpu-attach-gpu 
reboot_

### Expected behavior

The system boots up in the sys-gui-gpu desktop environment

### Actual behavior

The PC keeps crashing and rebooting unless I disable sys-gui-gpu using qubes.skip_autostart

Note: 
I have a single GPU setup with Intel UHD Graphics 630, using kernel parameter _**module_blacklist=i915**_ or _**rd.qubes.hide_pci=00:02.0**_ occasionally fixes the problem.

However, I'm not sure if there's a better way to do this, or if it's a necessary undocumented prerequisite.

**Comment by DemiMarie** [comment]
i915 cannot handle the device being ripped out from under it.

**Comment by ZYousef** [comment]
@DemiMarie so Is it necessary to blacklist the i915 for this to work?

**Comment by DemiMarie** [comment]
@ZYousef It is necessary to not have X11 running in dom0 when sys-gui-gpu starts.

**Comment by holiman** [comment]
> It is necessary to not have X11 running in dom0 when sys-gui-gpu starts.

So, any pointers on how one accomplishes that?

**Comment by DemiMarie** [comment]
> > It is necessary to not have X11 running in dom0 when sys-gui-gpu starts.
> 
> So, any pointers on how one accomplishes that?

`systemctl disable lightdm.service` and `qvm-prefs sys-gui-gpu autostart True` should do that.

**Comment by holiman** [comment]
> `systemctl disable lightdm.service` and `qvm-prefs sys-gui-gpu autostart True` should do that.

I tried that, unfortunately the effect of sys-gui-gpu autostart seems to be that it crashes earlier, immediately during boot. So now my system is roughly in the same shape as original reporter of this ticket :)

**Comment by holiman** [comment]
Oh, just saw this in my `guest-sys-gui-gpu.log`:

```
[2022-08-11 04:16:44] [    2.780620] i915 0000:00:05.0: Your graphics device 46a6 is not properly supported by the driver in this
[2022-08-11 04:16:44] [    2.780620] kernel version. To force driver probe anyway, use i915.force_probe=46a6
[2022-08-11 04:16:44] [    2.780620] module parameter or CONFIG_DRM_I915_FORCE_PROBE=46a6 configuration option,
[2022-08-11 04:16:44] [    2.780620] or (recommended) check for kernel updates.
```
Might be why the gui vm dies.

**Comment by DemiMarie** [comment]
@holiman what kernel version are you using?  Try `kernel-latest-qubes-vm` or the in-VM kernel.

**Comment by holiman** [comment]
I was using `5.18.9-1`, which was the latest at time of writing.

**Comment by euidzero** [comment]
I suspect qubes is affected by : https://lists.xenproject.org/archives/html/xen-devel/2022-10/msg01820.html

**Comment by marmarek** [comment]
It may be the case, although it does work on some devices even with the slot difference.
