### ISSUE TITLE
split-gpg1: Allow exporting keyring backups

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#7588]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### The problem you're addressing (if any)

split-gpg1 does not allow `--export-options`, so it is not possible to export a full backup of the public keyring.  This makes migration to split-gpg2 unnecessarily difficult

### The solution you'd like
Allow `--export-options backup`.

### The value to a user, and who that user might be

Users who use split-gpg1 will be able to more easily migrate to split-gpg2.

**Comment by andrewdavidwong** [comment]
Given that this is an enhancement, should it have a later milestone?
