### ISSUE TITLE
make get-sources stuck at gpgv can't allocate lock

### ISSUE THREAD

**Issue by ZYousef** [QubesOS/qubes-issues#7590]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release (if applicable)

qubes-builder 
builder.con qubes-os-r4.1

### Brief summary
I'm trying to get the sources to build an iso, however, the _make_ stops every time at:
_gpgv: can't allocate lock for '/home/user/qubes-builder/keystring/linux-pvgrub2/linux-pvgrub2-trustedkeys.gpg'_

**Comment by marmarek** [comment]
Check if you have enough disk space in there.

**Comment by ZYousef** [comment]
> Check if you have enough disk space in there.

I removed all of the other components and tried to get linxpvgrub2 [ _make get-sources COMPONENTS=linuxpvgrub2_
 ] by itself but still gives the same error

**Comment by ij1** [comment]
I just hit this same issue. My make get-sources got stuck and last visible message was about that lock.

While it was stuck, the command hunging was: gpgv --keyring linux-pvgrub2-trustedkeys.gpg (no other arguments). But the Makefile for linux-pvgrub2 provides also $(SIGN_FILE) and $(SRC_FILE) so perhaps the lack of some package caused those to be empty (just guessing).

For me, it got resolved when I installed all the packages listed as required by qubes builder. Curiously enough, the same message is still there, but make get-sources is successful.

**Comment by DemiMarie** [comment]
Can we replace gpgv with sqv @marmarek?

**Comment by marmarek** [comment]
> Can we replace gpgv with sqv @marmarek?

In this place - preferably no, since sqv is not as widely available as gpgv. Anyway, it doesn't look like a solution for this particular issue, so it's offtopic.

**Comment by DemiMarie** [comment]
> > Can we replace gpgv with sqv @marmarek?
> 
> In this place - preferably no, since sqv is not as widely available as gpgv. Anyway, it doesn't look like a solution for this particular issue, so it's offtopic.

The reason I mentioned sqv is that sqv does not use keyrings that require locking, so it cannot have this particular problem.
