### ISSUE TITLE
Unable to Fix Screen Tearing in 4.1 / XFCE 4.14

### ISSUE THREAD

**Issue by SenorFusion** [QubesOS/qubes-issues#7591]
### Qubes OS release
4.1 current

### Brief summary
Extreme screen tearing during video playback

### Steps to reproduce
Open Firefox or Chromium
Play a youtube video

### Expected behavior
video plays without tearing

### System
Lenovo Thinkpad P70 Skylake
Nvidia M3000 Quadro
noveau
xen 4.14.5
kernel 5.10.112

### What I have Tried

All of the suggestions in #4208 #3194 #4943 #5092 #5244
None of these work and all of the issues are nearly 3 years old at this point and none are about Qubes 4.1

The suggestions mostly boil down to 2 things:

1. 

_Window Tweak Settings > Compositor> Synchronize drawing on the vertical blank._

This is no longer available in Xfce 4.14 so cannot be done that I can find.

I also tried disabling the compositor completely under WIndows Tweaks, that did not help either. 

2. 

Add items to a xorg config file as listed in the [GUI Configuration Doc](https://www.qubes-os.org/doc/gui-configuration/)

```
Section "Device"
		Identifier "Intel Graphics"
		Driver "intel"
		Option "TearFree" "true"
EndSection

```
I've tried multiple other variations on this file with i915, vsync, and triplebuffer.

After every attempt at adding this file qubes GUI does not boot and I have to log in from the terminal and rm the file.

It hangs on the screen that shows all boot checks (which do not normally show during boot) and then stops at `Starting Hold until boot process finishes up....` but it never finishes

Attached is a picture of the boot hang, and a copy of Xorg log

![qubes-boot](https://user-images.githubusercontent.com/1929777/176251221-bd2ff551-b68e-4c60-9c7d-050106026528.jpeg)

[Xorg.0.log](https://github.com/QubesOS/qubes-issues/files/9003638/Xorg.0.log)

**Comment by marmarek** [comment]
You have two graphics cards, try adding `BusID "PCI:0@0:2:0"` to the `Device` section to be specific which one to use. Otherwise, connecting `intel` driver to Nvidia card indeed may result in Xorg not starting at all.

**Comment by SenorFusion** [comment]
Thank you for the help! I tried the following in `/etc/X11/xorg.conf.d/90-intel.conf`

```
Section "Device"
		Identifier "Intel Graphics"
                BusID "PCI:0@0:2:0"
		Driver "intel"
		Option "TearFree" "true"
EndSection
```

It didn't work but it failed at a slightly different place in the boot process:

![qubest-boot-2](https://user-images.githubusercontent.com/1929777/176316851-ac7e7080-1718-48ec-a9ba-698f58231849.jpeg)
[Xorg.0.log](https://github.com/QubesOS/qubes-issues/files/9005891/Xorg.0.log)

**Comment by marmarek** [comment]
Are you sure this log if from the time you tried with `/etc/X11/xorg.conf.d/90-intel.conf` ? I don't see any mention of using "intel" driver there, but only "modeset" one.

**Comment by marmarek** [comment]
In that case, copy somewhere `Xorg.0.log` (just to avoid overriding it by subsequent Xorg start) before removing `90-intel.conf`. 
You can also take a look at `Xorg.0.log.old`, maybe it's still there.
