### ISSUE TITLE
Does not suspend immeditely

### ISSUE THREAD

**Issue by deeplow** [QubesOS/qubes-issues#7593]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
R4.1

### Brief summary
On a laptop running on battery, I clicked on "suspend" (via the XFCE menu) and it only locked the screen. A long time after it randomly suspends (I supposed because it was hanging).

### Steps to reproduce
Suspend. Sometimes it happens some times it doesn't.

### Expected behavior
Suspend immediately.

### Actual behavior
 A long time after it randomly suspends (I supposed because it was hanging).

**Comment by deeplow** [comment]
This is what I see in journalctl:

```
Jun 30 10:35:55 dom0 pkexec[52828]: user: Executing command [USER=root] [TTY=unknown] [CWD=/home/user] [COMMAND=/usr/lib64/xfce4/session/xfsm-shutdown-helper --suspend]
Jun 30 10:36:04 dom0 systemd-logind[1948]: Lid closed.
[...]
Jun 30 11:53:54 dom0 systemd[1]: Finished Qubes suspend hooks.
Jun 30 11:53:54 dom0 audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=qubes-suspend comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? re>
Jun 30 11:53:54 dom0 systemd[1]: Reached target Sleep.
Jun 30 11:53:54 dom0 kernel: audit: type=1130 audit(1656586434.234:530): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=qubes-suspend comm="systemd" exe="/usr/lib/systemd/systemd" hos>
Jun 30 11:53:54 dom0 systemd[1]: Starting Suspend...
Jun 30 11:53:54 dom0 systemd-sleep[63197]: Suspending system...
Jun 30 11:53:54 dom0 kernel: PM: suspend entry (deep)
Jun 30 11:54:06 dom0 kernel: Filesystems sync: 0.020 seconds
Jun 30 11:54:06 dom0 kernel: Freezing user space processes ... (elapsed 0.003 seconds) done.
Jun 30 11:54:06 dom0 kernel: OOM killer disabled.
Jun 30 11:54:06 dom0 kernel: Freezing remaining freezable tasks ... (elapsed 0.095 seconds) done.
Jun 30 11:54:06 dom0 kernel: printk: Suspending console(s) (use no_console_suspend to debug)
Jun 30 11:54:06 dom0 kernel: PM: suspend devices took 1.500 seconds
[...]
```
If more is needed, let me know.

**Comment by marmarek** [comment]
That's _extremely_ long time. When is the line "starting Qubes suspend hooks"? just after "Lid closed"?

**Comment by deeplow** [comment]
Yes. And this also happened with the shut down. I'd do shut down and it just wouldn't. All it would do is show the session login window. If I clicked on the shut down buttion from there it would do nothing.

I took a look at the line you asked and something doesn't look right. There is no "Starting Qubes suspend hooks" between  "lid is closed" (at `Jun 30 10:36:04`) and "finished suspend hooks" (at `Jun 30 11:53:54`). Probably it was from an earlier suspend attempt that day.
```shell_session
$ sudo journalctl | grep "Starting Qubes suspend hooks" | grep "Jun 30"
Jun 30 07:16:44 dom0 systemd[1]: Starting Qubes suspend hooks...
Jun 30 08:17:18 dom0 systemd[1]: Starting Qubes suspend hooks...
Jun 30 12:15:27 dom0 systemd[1]: Starting Qubes suspend hooks...
Jun 30 15:52:09 dom0 systemd[1]: Starting Qubes suspend hooks...
Jun 30 22:48:34 dom0 systemd[1]: Starting Qubes suspend hooks...
Jun 30 22:58:14 dom0 systemd[1]: Starting Qubes suspend hooks...
```
