### ISSUE TITLE
sys-net startup crash - kernel panic / hardware

### ISSUE THREAD

**Issue by f0xy** [QubesOS/qubes-issues#7595]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
Qubes 4.1.1-rc1

### Brief summary
--------------------------
sys-net crashes on startup due kernel crash from the mentioned hardware resulting in the displayed error messages.
Hardware: RTL8821CE 802.11ac PCIe Wireless Network Adapter
Kernel Version: 5.15.48-1.fc32.qubes.x86_64

Error Messages:  

"domain dead
 2022-07-02 00:07:47.415 qrexec-daemon[11930]: qrexec-daemon.c:340:init: cannot connect to qrexec agent: No such file or directory"

[2022-07-02 00:07:44] [ 3.339433] Kernel panic - not syncing: Fatal exception
[2022-07-02 00:07:44] [ 3.339609] Kernel Offset: 0x0 from 0xffffffff81000000 (relocation range: 0xffffffff80000000-0xffffffffbfffffff)

[Screenshot](https://i.imgur.com/xMRkjbo.png)

### Steps to reproduce
--------------------------
sys-net startup with the mentioned hardware running the specified kernel.

### Expected behavior
--------------------------
Networking VM startup without crash

### Actual behavior
--------------------------
Networking VM startup crash

**Comment by andrewdavidwong** [comment]
> Running a simple VM with a PCI WiFi network interface under HVM causes the networking **template** to crash without any modifications to the template.

Is this a typo? Nothing that happens to a VM should ever cause its parent *template* to crash (unless it crashes the entire system or something).

**Comment by f0xy** [comment]
Just standard networking VM. After installing 4.1.1-rc1. sys-net crashed following sys-firewall after fresh install. I removed the WiFi adapter from the PCI devices and started right up. Tested a few PCI WiFi adapters with the same result, ending in a crash on two separate systems.

**Comment by unman** [comment]
On Fri, Jul 01, 2022 at 03:25:32PM -0700, f0xy wrote:
> Just standard networking VM. After installing 4.1.1-rc1. sys-net crashed following sys-firewall after fresh install. I removed the WiFi adapter from the PCI devices and started right up. Tested a few PCI WiFi adapters with the same result, ending in a crash on two separate systems.
> 
I'm still unclear what it is you are reporting.
The initial report said "simple VM" causes template to crash: steps
seemed to suggest that you were attaching the PCI device to the template.
But this is clearly *not* what you are doing.

Can you clarify, and give some more detail in the "steps to reproduce".

Also, what is the significance of "following sys-firewall" - do you mean
that sys-net works fine *until* sys-firewall started?
If you start sys-net with the device attached will it continue to run?

"two separate systems" - do you mean that you duplicated this effect on
two separate Qubes systems with different hardware, and attaching
different PCI devices?

**Comment by f0xy** [comment]
> On Fri, Jul 01, 2022 at 03:25:32PM -0700, f0xy wrote: Just standard networking VM. After installing 4.1.1-rc1. sys-net crashed following sys-firewall after fresh install. I removed the WiFi adapter from the PCI devices and started right up. Tested a few PCI WiFi adapters with the same result, ending in a crash on two separate systems.
> I'm still unclear what it is you are reporting. The initial report said "simple VM" causes template to crash: steps seemed to suggest that you were attaching the PCI device to the template. But this is clearly *not* what you are doing. Can you clarify, and give some more detail in the "steps to reproduce". Also, what is the significance of "following sys-firewall" - do you mean that sys-net works fine *until* sys-firewall started? If you start sys-net with the device attached will it continue to run? "two separate systems" - do you mean that you duplicated this effect on two separate Qubes systems with different hardware, and attaching different PCI devices?

"domain dead
2022-07-02 00:07:47.415 qrexec-daemon[11930]: qrexec-daemon.c:340:init: cannot connect to qrexec agent: No such file or directory"

Which was lead up by --->

[2022-07-02 00:07:44] [    3.339433] Kernel panic - not syncing: Fatal exception
[2022-07-02 00:07:44] [    3.339609] Kernel Offset: 0x0 from 0xffffffff81000000 (relocation range: 0xffffffff80000000-0xffffffffbfffffff)

----------------------------------------
Test device is: RTL8821CE 802.11ac PCIe Wireless Network Adapter

The initial crash was after installation of Qubes 4.1.1-rc1. That is correct it is not on the template its a regular Networking VM which HVM Privs.

**Comment by unman** [comment]
On Sat, Jul 02, 2022 at 12:26:45AM -0700, f0xy wrote:
> > On Fri, Jul 01, 2022 at 03:25:32PM -0700, f0xy wrote: Just standard networking VM. After installing 4.1.1-rc1. sys-net crashed following sys-firewall after fresh install. I removed the WiFi adapter from the PCI devices and started right up. Tested a few PCI WiFi adapters with the same result, ending in a crash on two separate systems.
> > I'm still unclear what it is you are reporting. The initial report said "simple VM" causes template to crash: steps seemed to suggest that you were attaching the PCI device to the template. But this is clearly *not* what you are doing. Can you clarify, and give some more detail in the "steps to reproduce". Also, what is the significance of "following sys-firewall" - do you mean that sys-net works fine *until* sys-firewall started? If you start sys-net with the device attached will it continue to run? "two separate systems" - do you mean that you duplicated this effect on two separate Qubes systems with different hardware, and attaching different PCI devices?
> 
> "domain dead
> 2022-07-02 00:07:47.415 qrexec-daemon[11930]: qrexec-daemon.c:340:init: cannot connect to qrexec agent: No such file or directory"
> 
> Which was lead up by --->
> 
> [2022-07-02 00:07:44] [    3.339433] Kernel panic - not syncing: Fatal exception
> [2022-07-02 00:07:44] [    3.339609] Kernel Offset: 0x0 from 0xffffffff81000000 (relocation range: 0xffffffff80000000-0xffffffffbfffffff)
> 
> ----------------------------------------
> Test device is: RTL8821CE 802.11ac PCIe Wireless Network Adapter
> 
> The initial crash was after installation of Qubes 4.1.1-rc1. That is correct it is not on the template its a regular Networking VM which HVM Privs.  
> 

Thanks, much clearer.
Can you edit the title and report, to reflect kernel panic with PCI
device.

**Comment by f0xy** [comment]
> > On Fri, Jul 01, 2022 at 03:25:32PM -0700, f0xy wrote: Just standard networking VM. After installing 4.1.1-rc1. sys-net crashed following sys-firewall after fresh install. I removed the WiFi adapter from the PCI devices and started right up. Tested a few PCI WiFi adapters with the same result, ending in a crash on two separate systems.
> > I'm still unclear what it is you are reporting. The initial report said "simple VM" causes template to crash: steps seemed to suggest that you were attaching the PCI device to the template. But this is clearly _not_ what you are doing. Can you clarify, and give some more detail in the "steps to reproduce". Also, what is the significance of "following sys-firewall" - do you mean that sys-net works fine _until_ sys-firewall started? If you start sys-net with the device attached will it continue to run? "two separate systems" - do you mean that you duplicated this effect on two separate Qubes systems with different hardware, and attaching different PCI devices?
> 
> "domain dead 2022-07-02 00:07:47.415 qrexec-daemon[11930]: qrexec-daemon.c:340:init: cannot connect to qrexec agent: No such file or directory"
> 
> Which was lead up by --->
> 
> [2022-07-02 00:07:44] [ 3.339433] Kernel panic - not syncing: Fatal exception [2022-07-02 00:07:44] [ 3.339609] Kernel Offset: 0x0 from 0xffffffff81000000 (relocation range: 0xffffffff80000000-0xffffffffbfffffff)
> 
> Test device is: RTL8821CE 802.11ac PCIe Wireless Network Adapter
> 
> The initial crash was after installation of Qubes 4.1.1-rc1. That is correct it is not on the template its a regular Networking VM which HVM Privs.

done

**Comment by qubestest31** [comment]
Same issue with dom0 kernel-latest (5.18.3 and 5.18.9) 

As a workaround, I compiled this driver https://github.com/tomaspinho/rtl8821ce using in-vm Fedora 36 kernel and I blacklisted the module rtw88_8821ce.

With this driver, wifi is working using in-vm Fedora 36 kernel 5.17.9 (from the image) and 5.18.9 (up to date kernel).
The downside is it can't connect in WPA3 (it's possible with rtw88_8821ce on regular Fedora 36), the access point needs to be in WPA2...
