### ISSUE TITLE
Zombie entries in applications-merged after qube deletion 

### ISSUE THREAD

**Issue by unman** [QubesOS/qubes-issues#7596]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
4.1

### Brief summary
~/.config/menus/applications-merged is littered with entries for non-existent qubes

### Steps to reproduce
1. Use kde menu editor and observe zombie entries.
2. Examine ~/.config/menus/applications-merged

### Expected behavior
Menu entries will be removed after qube is deleted.

### Actual behavior

Menu entries are not removed after qube is deleted.

**Comment by EncryptedGiraffe** [comment]
Oh I just noticed this for the first time this morning.
I also get a bunch of messages like this in dom0's journal.
```
Jul 01 21:27:02 dom0 plasmashell[5131]: Entry is not valid "applications:org.qubes-os.vm.qube-name.debian-xterm.desktop" QSharedPointer(0x5d32d12bfcb0)
```

**Comment by GWeck** [comment]
These zombie entries appear also in the KDE menu editor, most of them as `qubes-nm directory-<VMname>`. There they can be removed by the KDE menu editor, but the entires in `~/.config /menus/applications-merged\` remain.
