### ISSUE TITLE
Black screen after installing qubes os 4.1-4.1.1, no boot entry selection.

### ISSUE THREAD

**Issue by gamolk** [QubesOS/qubes-issues#7597]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
4.1
4.1.1

### Brief summary
No boot menu after installing qubes, just a black screen with no text.

### Steps to reproduce
After installing qubes , I restart my computer and get a black screen without a boot menu

### Expected behavior
The presence of a boot menu to run qubes

### Actual behavior
Black screen on boot

________________________
Some information after installation and solutions that I used:
1) In `/boot/efi/efi/qubes` I have the following files:
`fonts  grub.cfg  grubx64.efi  xen-4.14.5.efi  xen.efi`
2) I have no files in /boot/efi/efi/boot
3)` efibootmgr --verbose` command says no boot entries
4) If I boot into recovery mode and add a boot entry:
`efibootmgr -v -c -u -L MyOS -l /EFI/qubes/grubx64.efi -d /dev/sda -p 1`
This entry will disappear after a reboot.
5) If I copy the file `/boot/efi/efi/qubes/grubx64.efi` to `/boot/efi/efi/boot/` and change it to `bootx64.efi`, then after rebooting the computer, a boot entry is automatically created in efibootmgr:
`Boot0003* UEFI OS HD(1,GPT,....,0x800,0x12c000)/File(\EFI\BOOT\BOOTX64.EFI)..BO`
Now I can run qubes os.
6) In point number 4, I tried to manually add a boot entry that is not saved after a reboot. But now that I have the file `/boot/efi/efi/bootx64.efi` and the boot entry automatically created: `Boot0003* UEFI OS HD(1,GPT,....,0x800,0x12c000)/File(\EFI\BOOT \BOOTX64.EFI)..BO` , I again tried using the manually created boot entry `efibootmgr -v -c -u -L MyOS -l /EFI/qubes/grubx64.efi -d /dev/sda -p 1`, now it persists after reboot and after that I can boot from that boot entry.
7) Now there are two boot entries in the output of efibootmgr --verbose and both work:
```
Boot0000* MyOS	HD(1,GPT,....,0x800,0x12c000)/File(\EFI\QUBES\GRUBX64.EFI)
Boot0003* UEFI OS	HD(1,GPT,....,0x800,0x12c000)/File(\EFI\BOOT\BOOTX64.EFI)..BO
```
8) If I delete the file /boot/efi/efi /boot/bootx64.efi , then both boot entries are gone and I again get a black screen without the ability to start qubes os.

I hope for help from the developers, although I understand that the problem is more likely in my equipment.
Actually my questions:
1) What boot record should I use? Manually created `EFI\QUBES\GRUBX64.EFI` or automatically created `EFI\BOOT\BOOTX64.EFI`?
2) Do I need to copy the rest of the files to the `EFI\BOOT\` directory, namely the `grub.cfg xen-4.14.5.efi xen.efi fonts`?
3) What are my further actions with these files after updating the system?
4) What to do when changing kernel parameters? With `grub2-mkconfig -o`, which efi file should I refer to, `EFI\QUBES\GRUBX64.EFI` or `EFI\BOOT\BOOTX64.EFI`?

Thanks in advance for any help with this issue.

**Comment by andrewdavidwong** [comment]
> I hope for help from the developers, although I understand that the problem is more likely in my equipment.
> Actually my questions: [...]

Please keep in mind that the issue tracker (`qubes-issues`) is not intended to serve as a help desk or tech support center or as a place to ask questions. Instead, we've set up other [venues where you can ask for help and support, ask questions, and have discussions](https://www.qubes-os.org/support/). (By contrast, the issue tracker is more of a technical tool intended to support our developers in their work.)

Having said that, I don't know whether there's an actual bug in this case, so let's see what the devs think. I'm just letting you know in order to temper your expectations about receiving support here and having questions answered here.
