### ISSUE TITLE
Flaky qrexec-agent on vchan error

### ISSUE THREAD

**Issue by iacore** [QubesOS/qubes-issues#7598]
### Qubes OS release
r4.1

### Brief summary
Sometimes (regular enough), when starting up system, I cannot open any GUI app.

By connecting to console using display DVM, I found the error
```
> cat ~/.xsession-errors
....
Not in GuiVM or dom0. Exiting.
qrexec-fork-server[xxx]: qrexec-agent-data.c: vchan connect error
qrexec-fork-server[xxx]: qrexec-agent-data.c: vchan connect error
qrexec-fork-server[xxx]: qrexec-agent-data.c:159:handle_just_exec: executed (nowait): QUBESRPC qubes.StartApp+xfce4-terminal dom0 (pid 1262)

```

~~One way to "fix" this is to run `systemctl restart qubes-gui-agent`, and it works immediately. Even the app previous I want to open (Application Finder in dom0) opens without any request.~~ This only worked sometimes.

I read the logs with `sudo journalctl -xeu qubes-gui-agent`, but I cannot find any error there.

I suspect this is another race condition, when "qubes-gui` should start before `qrexec-fork-server`, or vice versa.

### Steps to reproduce
This is difficult.
1. install this modified branch https://github.com/QubesOS/qubes-gui-agent-linux/pull/154.
2. install a new version of "qubes-gui-agent.xxxxx.tar.zst" in arch linux AppVM
3. `shutdown 0`
4. Start any app using Application Finder from dom0

**Comment by locriacyber** [comment]
So, when the AppVM is still starting up, if I try to open an app, something seem to be broken until restart.
