### ISSUE TITLE
Spurious keystrokes while switching between windows

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#7599]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

R4.1, but R4.0 is probably affected too.

### Brief summary

When cycling between windows, qubes are sent keystroke events that they really should not be.

### Steps to reproduce

See https://github.com/QubesOS/qubes-gui-daemon/pull/98#discussion_r820048640 and related discussion.

### Expected behavior

No extraneous keystrokes.

### Actual behavior

Extraneous keystrokes.

**Comment by marmarek** [comment]
> Steps to reproduce

Please include exact steps to reproduce here in the issue description. By doing simple alt-tab, I don't see any extra keystroke events being sent, so there must be something more to it.

**Comment by DemiMarie** [comment]
> > Steps to reproduce
> 
> Please include exact steps to reproduce here in the issue description. By doing simple alt-tab, I don't see any extra keystroke events being sent, so there must be something more to it.

I don’t remember the details, but I think the problem may have been missing focus events.

**Comment by marmarek** [comment]
That's what linked discussion suggests, but there is no specific issue details. And without ways to reproduce the issue, I can't verify if that change really fixes it (and won't accept the change blindly hoping it does).

**Comment by DemiMarie** [comment]
Per private discussion with @marmarek it looks like this may have been a bug in R4.0’s XFWM4 that is fixed in the R4.1 version.  In any case, I am not able to reproduce this problem.

Closing as “cannot reproduce”.  If anyone finds a way to reproduce this bug, please comment here and the issue will be reopened.
