### ISSUE TITLE
Tray icon missing after several suspension

### ISSUE THREAD

**Issue by logoerthiner1** [QubesOS/qubes-issues#7602]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

R4.1

### Brief summary

After several suspension - resume loop (for a long time probably), tray icon for appvms are not working. Neither network manager icon from sys-net nor other tray icon are displayed.

killing qubes-guid or xfce4-panel and then restart it does not help.

### Steps to reproduce

Use the system for several days with suspending and resuming.

### Expected behavior

Tray icons for appVMs are always visible.

### Actual behavior

At some time, tray icons for appVMs become invisible until a reboot.

**Comment by DemiMarie** [comment]
Does logging out and in to your GUI qube help?

**Comment by DemiMarie** [comment]
> > Does logging out and in to your GUI qube help?
> 
> I have just tried `poweroff` in sys-net and then start it again in Qube Manager, and the Network Manager icon reappears.
> 
> However this is not a good trick for VM with a lot of app running, nor can it be applied frequently on VM with PCI devices attached - occasionally devices refuses to be reset and attached again. It would be better if the bug is fixed.

What about restarting the qube’s GUI daemon?  Obviously this is not a fix, but it could help indicate where the problem lies.  Can you provide the logs from the GUI daemon in debug mode?

**Comment by logoerthiner1** [comment]
```
$ cat guid.sys-net.log.old 
Icon size: 128x128
ErrorHandler: BadAccess (attempt to access private resource denied)
                 Major opcode: 130 (MIT-SHM)
                 Minor opcode: 1 (X_ShmAttach)
                 ResourceID:   0x1e00007
                 Failed serial number:  1117
                 Current serial number: 1118
XShmAttach failed for window 0x44001d4(remote 0xa00002)
ErrorHandler: BadAccess (attempt to access private resource denied)
                 Major opcode: 130 (MIT-SHM)
                 Minor opcode: 1 (X_ShmAttach)
                 ResourceID:   0x440db16
                 Failed serial number:  287888
                 Current serial number: 287889
XShmAttach failed for window 0x440db11(remote 0xa0f27c)
Window 0x440dcb6 is still set as transient_for for a 0x440dcbe window, but VM tried to destroy it
ErrorHandler: BadAccess (attempt to access private resource denied)
                 Major opcode: 130 (MIT-SHM)
                 Minor opcode: 1 (X_ShmAttach)
                 ResourceID:   0x1e00007
                 Failed serial number:  314710
                 Current serial number: 314711
XShmAttach failed for window 0x440e318(remote 0xa10aee)
reloading X server parameters...
reloading X server parameters...
reloading X server parameters...
reloading X server parameters...
reloading X server parameters...
reloading X server parameters...
libvchan_is_eof
Icon size: 128x128
domain dead
Failed to connect to gui-agent
```

The other VM having tray icon missing has a very long guid log, however most of it is composed with MIT-SHM errors and occasionally (but intermittently) "Window ... is still set as transient_for for a ... window, but VM tried to destroy it".

Killing and restarting guid of appvm in dom0 does not work as I mentioned at the top of post. (or you mean others?) Currently I have one VM with tray icon missing (my working VM) and one working (sys-net).

My working VM is still running, so if you have any thought, I can test it out.

**Comment by DemiMarie** [comment]
> Killing and restarting guid of appvm in dom0 does not work as I mentioned at the top of post. (or you mean others?) Currently I have one VM with tray icon missing (my working VM) and one working (sys-net).

I meant logging out and back into dom0, which will restart the dom0 X server and window manager.

**Comment by logoerthiner1** [comment]
> > Killing and restarting guid of appvm in dom0 does not work as I mentioned at the top of post. (or you mean others?) Currently I have one VM with tray icon missing (my working VM) and one working (sys-net).
> 
> I meant logging out and back into dom0, which will restart the dom0 X server and window manager.

Today I have a chance to witness disappearance of several tray icons. I tried logging out and back into dom0 and the icons come back.

The logs are:
```
$ cat guid.sys-net.log.old
Icon size: 128x128
ErrorHandler: BadAccess (attempt to access private resource denied)
                 Major opcode: 130 (MIT-SHM)
                 Minor opcode: 1 (X_ShmAttach)
                 ResourceID:   0x1600007
                 Failed serial number:  1117
                 Current serial number: 1118
XShmAttach failed for window 0x42001d4(remote 0x800002)
```

And (after I have logged out in dom0)
```
X connection to :0.0 broken (explicit kill or server shutdown).
```

Btw everything should be up to date (sys-net is updated to fedora-36 and same issue appears) and it is not related to appvm distros (another debian11 vm have its tray icon disappeared)

Hope this will help.

**Comment by logoerthiner1** [comment]
> > Killing and restarting guid of appvm in dom0 does not work as I mentioned at the top of post. (or you mean others?) Currently I have one VM with tray icon missing (my working VM) and one working (sys-net).
> 
> I meant logging out and back into dom0, which will restart the dom0 X server and window manager.

Update: this issue can be effectively triggered by dom0 command `pkill xfce4-panel; xfce4-panel&`. This means that if xfce4-panel crashes or exits for any reason, the icons will disappear. I do not know what is the proper way of fixing this behavior though. IMHO xfce4-panel crashing is harder to fix, but it seems that when it crashes, it will restart itself. Therefore I only need one command that can recover all the appvm tray icons when it crashes. It will be better to let the tray icon reappear by itself (basically to execute mentioned command when xfce4-panel restarts)

This behavior is kind of annoying, especially considering existence of #7673 so logging out is not desired.
