### ISSUE TITLE
Rarely GUI program randomly crashes in one appVM

### ISSUE THREAD

**Issue by logoerthiner1** [QubesOS/qubes-issues#7608]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

R4.1

### Brief summary

I have encountered several cases where inside one VM, all gui programs become unstable and prone to crashing, from xfce4-terminal, Files, ibus to editors (vscode, and other editor that I start from docker).

The programs do not crash immediately, but gradually crashes more frequently. When a event (remains to be investigated) happens, starting from then ibus crashes more frequently. Before it crashes, it will be less responsive and does not show tray icon and the hovering window that should appear when typing.

Later more and more program crashes, for example xfce4-terminal.

I have grabbed the core dumps and may look into it when I am less busy.

The crashing VM happens to be a fedora-34-xfce derived VM, but I have the feeling that problem happens inside the qubes os specific X server implementations.

### Steps to reproduce

It is rare so I do not have very stable way of reproducing this. However these may be related:
1. have ibus up (btw `ibus-setup` does not work, and I have been using `ibus-daemon -d`)
2. plug a screen of 4000x3000 onto the computer

### Expected behavior

GUI programs do not crash from time to time.

### Actual behavior

At some point GUI programs crash from time to time.

**Comment by locriacyber** [comment]
We need more logging.
