### ISSUE TITLE
Add multiple drive space allocate support

### ISSUE THREAD

**Issue by Che15ea** [QubesOS/qubes-issues#7609]
I have an SSD and an HDD in my laptop. I'd like to use SSD for performance use cases such as operating system and software, and use HDD for Storage purposes, such as full blockchain, media storage, database etc. Is it possible to dynamically and separately allocate space for both SSD and HDD? Like "Private storage max size on Drive 1" "Private storage Max Size on Drive2" "System Storage Max size(on Drive 1)".
So far I solve my demand by storing everything on SSD, or mount multiple external HDD on different VMs respectively. But it will waste either the SSD speed or large HDD space(such as using 2TB HDD for 100GB Block chain).

**Comment by andrewdavidwong** [comment]
Please note that the issue tracker (`qubes-issues`) is not intended to serve as a help desk or tech support center. Instead, we've set up other [venues where you can ask for help and support, ask questions, and have discussions](https://www.qubes-os.org/support/). (By contrast, the issue tracker is more of a technical tool intended to support our developers in their work.) Thank you for your understanding!
