### ISSUE TITLE
update proxy docs bug

### ISSUE THREAD

**Issue by nyxnor** [QubesOS/qubes-issues#7610]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
4.1

### Brief summary

https://www.qubes-os.org/doc/how-to-install-software/#updates-proxy reports some incorrect information.

> Updates proxy is a service which allows access only from package managers.

Incorrect, not only package managers but any program that uses the proxy. Package managers are only configured to use the proxy.
I think the wording **only** is misleading because it really can be any program that accepts proxy, curl, wget, etc.

A suggestion is:
_Updates proxy is a service which allows access for package managers configured to use the proxy by default, but can be used by any other configured application._

---------------

> The proxy is running in selected VMs (by default all the NetVMs (1)) and intercepts traffic directed to 10.137.255.254:8082. 

Deprecated, `/etc/tinyproxy/updates-blacklist` called by `/etc/tinyproxy/tinyproxy-updates.conf`, `Filter` option, blocks this virtual ip.

Suggestion:
_The proxy is running in selected VMs (by default all the NetVMs (1)) and intercepts traffic directed to 127.0.0.1:8082._

--------------

**Comment by andrewdavidwong** [comment]
Thank you for the report! In case you (or any others reading this) are not already aware, the documentation is a community effort, and everyone is welcome to contribute. (That's how things like this get updated!) So, if you'd like to get involved with the project, this is a great way to do it. You can read more about how to submit documentation changes here:

https://www.qubes-os.org/doc/how-to-edit-the-documentation/

You may also be interested in the documentation style guide:

https://www.qubes-os.org/doc/documentation-style-guide/

**Comment by nyxnor** [comment]
I am aware of those docs, just opened the issue to discuss first if I made some mistake or not. But as this seems like a template reply, I will wait for an OK to proceed.

**Comment by unman** [comment]
On Fri, Jul 08, 2022 at 03:58:13PM -0700, nyxnor wrote:
> I am aware of those docs, just opened the issue to discuss first if I made some mistake or not. But as this seems like a template reply, I will wait for an OK to proceed.
I'll give you that OK. The docs haven't kept up with code changes.

**Comment by nyxnor** [comment]
Note to self to improve wording:

https://forum.qubes-os.org/t/why-does-the-updateproxy-not-have-a-whitelist/11087/4
> Yes, that was a direct reason why whitelist was removed. But in general, the purpose of the proxy (instead of direct network access) is to limit what applications in a template can access the network. Not necessarily what part of the network they can access. The reasoning here is to give network access only to applications we trust to properly verify anything downloaded. This is briefly mentioned in the documentation at [How to install software | Qubes OS](https://www.qubes-os.org/doc/how-to-install-software/#why-dont-templates-have-network-access) but indeed could be further clarified.
