### ISSUE TITLE
Qubes 4.1.1 resume from suspend fails - system doesn't wake up 

### ISSUE THREAD

**Issue by esatravi** [QubesOS/qubes-issues#7611]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

4.1.1-rc1

### Brief summary

Fresh installation of QubesOs 4.1.1-rc1 on HP 840 G8 laptop. 
Press power button to suspend the OS. The system goes to sleep as expected. The tiny led on the power button flashes slowly indicating sleep mode. 

To resume - pressing power button again - nothing happens. The systems doesn't wake up. Hard power-down is required to restart QubesOS as a fresh boot. 

It proves impossible to resume / wake-up QubesOs after it's been suspended. One in suspended mode the OS is stuck there. Hard power down required. 

### Steps to reproduce
See above. 

### Expected behavior

Pressing power button when the systems is in suspended mode should resume it, wake it up. 

### Actual behavior

Pressing power button when the system is in suspended mode does not wake it up.

**Comment by esatravi** [comment]
Issue resolved by updating sof firmware in dom0

**Comment by esatravi** [comment]
Hes anyone found some workaround for waking-up the laptop from the sleep mode without the need of the hard reboot? 

I tried to find some ideas on the net but so far nothing of a practical value. 

For now, I just keep the laptop running and reboot on major templates updates.

**Comment by slayoo** [comment]
Same symptoms here (I'm a new user, first installation).
What is your hardware (posting output from `qubes-hcl-report dom0` might help?). 

Also, what do the following two commands output on your machine?:
- `sudo dmesg | grep ACPI | grep supports`
- `cat /sys/power/mem_sleep`

See also discussion in #6411

**Comment by cordygram** [comment]
Same issue here.  OS 4.14.6. HP x360 7i laptop.  Won't wake from suspend and power button remains illuminated.

Also, when laptop is locked screen goes black but remains backlit.

Any assistance would be appreciated.
