### ISSUE TITLE
For certain apps, window disappears while app is still running in Fedora 35 app qube

### ISSUE THREAD

**Issue by Khoramyar** [QubesOS/qubes-issues#7615]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
Qubes 4.1 with Fedora 35 template
Dom-0 kernel: 5.16.18-2.fc32
Fedora 35 template kernel: 5.10.112-1.fc32

### Brief summary
Some apps window management crashes when launched. Their window is briefly shown, but all of a sudden disappears. The apps are still active, but their window disappears.

Some of the Apps in question:
- Anydesk ( I am aware of the former window bug with qubes and Anydesk, this effects this app in a different way)
- Outline Manager
- Outline Client
- Spotify ( This particular app will be open the first time you launch, but if you close and reopen it disappears )
- Publii

Observation: most of the apps above are packaged as .AppImage

### Steps to reproduce
Have Qubes 4.1 with App VM fedora 35 and launch above applications.

### Expected behavior
The apps are launched and their windows remain active.

### Actual behavior
The apps are launched but their windows shown for a split second and then disappears.

### Temporary action taken to address the issue:
Downgrade to fedora 34 template or switch to Debian template will address the issue.
Fedora 34 template works using the same kernel version of fedora 35 - 5.10.112-1.fc32

**Comment by marmarek** [comment]
Can you post errors from `/var/log/xen/console/guest-(VMNAME).log` from affected VM?

In such broken state, you can access the VM console by calling `qvm-console-dispvm` (login as root, shouldn't prompt for the password). Please check `systemctl status qubes-gui-agent` - if it crashed, please tell with what message.

**Comment by Khoramyar** [comment]
##Lines added to /var/log/xen/console/guest-(VMNAME).log when launching the outline client, it crashes and quits:

[2022-07-12 12:28:40] [  570.472734] kauditd_printk_skb: 54 callbacks suppressed
[2022-07-12 12:28:40] [  570.472741] audit: type=1701 audit(1657621721.625:385): auid=1000 uid=1000 gid=1000 ses=1 pid=2362 comm="outline-client" exe="/tmp/.mount_OutlinM6rmmK/outline-client" sig=31 res=1
[2022-07-12 12:28:40] [  570.488633] audit: type=1334 audit(1657621721.641:386): prog-id=108 op=LOAD
[2022-07-12 12:28:40] [  570.488850] audit: type=1334 audit(1657621721.641:387): prog-id=109 op=LOAD
[2022-07-12 12:28:40] [  570.489012] audit: type=1334 audit(1657621721.641:388): prog-id=110 op=LOAD
[2022-07-12 12:28:40] [  570.489776] audit: type=1130 audit(1657621721.642:389): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-coredump@28-2377-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[2022-07-12 12:28:41] [  570.667972] audit: type=1131 audit(1657621721.820:390): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-coredump@28-2377-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[2022-07-12 12:28:41] [  570.700483] audit: type=1701 audit(1657621721.853:391): auid=1000 uid=1000 gid=1000 ses=1 pid=2398 comm="outline-client" exe="/tmp/.mount_OutlinM6rmmK/outline-client" sig=31 res=1
[2022-07-12 12:28:41] [  570.710761] audit: type=1334 audit(1657621721.863:392): prog-id=111 op=LOAD
[2022-07-12 12:28:41] [  570.711009] audit: type=1334 audit(1657621721.863:393): prog-id=112 op=LOAD
[2022-07-12 12:28:41] [  570.711263] audit: type=1334 audit(1657621721.864:394): prog-id=113 op=LOAD



##Result of "sudo systemctl status qubes-gui-agent" in affected VM after the crash above:

sudo systemctl status qubes-gui-agent
● qubes-gui-agent.service - Qubes GUI Agent
     Loaded: loaded (/usr/lib/systemd/system/qubes-gui-agent.service; enabled; vendor preset: enabled)
     Active: active (running) since Tue 2022-07-12 12:19:14 CEST; 13min ago
    Process: 443 ExecStartPre=/bin/mkdir -p /var/run/console (code=exited, status=0/SUCCESS)
    Process: 454 ExecStartPre=/bin/touch /var/run/console/user (code=exited, status=0/SUCCESS)
    Process: 457 ExecStartPre=/bin/sh -c p=/sys/kernel/mm/transparent_hugepage/enabled; fgrep -q [always] $$p && echo madvise > $$p; true (code=exited, status=0/SUCCESS)
   Main PID: 459 (qubes-gui)
      Tasks: 1 (limit: 4643)
     Memory: 4.0M
        CPU: 1.338s
     CGroup: /system.slice/qubes-gui-agent.service
             └─ 459 /usr/bin/qubes-gui

Jul 12 12:19:17 (VMNAME) qubes-gui[459]: error reading WM_NORMAL_HINTS
Jul 12 12:19:34 (VMNAME) qubes-gui[459]: got num_mfn=0x0 for window 0x1c000df (0x-1776476192)
Jul 12 12:19:34 (VMNAME) qubes-gui[459]: error reading WM_NORMAL_HINTS
Jul 12 12:27:15 (VMNAME) qubes-gui[459]: XGetWindowAttributes for 0x2400006 failed in handle_crossing, ret=0x0
Jul 12 12:27:15 (VMNAME) qubes-gui[459]: XGetWindowAttributes for 0x1804ad0 failed in handle_create, ret=0x0
Jul 12 12:27:24 (VMNAME) qubes-gui[459]: got num_mfn=0x0 for window 0x2400007 (0x-1776476192)
Jul 12 12:27:24 (VMNAME) qubes-gui[459]: error reading WM_NORMAL_HINTS
Jul 12 12:27:49 (VMNAME) qubes-gui[459]: error reading WM_NORMAL_HINTS
Jul 12 12:28:41 (VMNAME) qubes-gui[459]: got num_mfn=0x0 for window 0x2400007 (0x-1776476192)
Jul 12 12:28:41 (VMNAME) qubes-gui[459]: error reading WM_NORMAL_HINTS

**Comment by marmarek** [comment]
Interesting, so the gui-agent still is there, I guess Xorg too, but the app windows are gone. Do you see them on `xwininfo -root -tree` output within VM? The app process is still there, right?
FWIW, I briefly tried with Publii 0.40.1 AppImage on fedora-35 and fedora-36 templates, and the same kernel, and it works for me.

**Comment by Khoramyar** [comment]
I just checked, the updated publii version 0.40.1 which is the current version works, but the older version I had from before 0.38.3 crashes. 

Also right now the latest versions of AnyDesk, Outline client, outline manager, and beaker browser crashes.

The process for AnyDesk, BeakerBrowser are still there, but I don't see processes from Outline or Outline manager, it seems their processes crash and quit:

     0xc00001 "anydesk": ("anydesk" "Anydesk")  10x10+10+10  +10+10
        1 child:
        0xc00002 (has no name): ()  1x1+-1+-1  +9+9
     0x40000a (has no name): ()  22x22+0+0  +0+0
        1 child:
        0xc0001c "AnyDesk": ("AnyDesk" "AnyDesk")  22x22+0+0  +0+0
           1 child:
           0xc0001d (has no name): ()  1x1+-1+-1  +-1+-1
     0x400021 (has no name): ()  22x22+0+0  +0+0
        1 child:
        0x1c000e3 "beaker-browser": ("Beaker Browser1" "Beaker Browser1")  22x22+0+0  +0+0
           1 child:
           0x1c000e4 (has no name): ()  1x1+-1+-1  +-1+-1
