### ISSUE TITLE
Onionsite Not Found (yum.qubes-os.org)

### ISSUE THREAD

**Issue by johnnyboy-3** [QubesOS/qubes-issues#7616]
Qubes OS release
R4.1

Brief summary
http://yum.qubesosfasa4zl44o4tws22di6kepyzfeqv3tg4e3ztknltfxqrymdad.onion/
```
Onionsite Not Found

The most likely cause is that the onionsite is offline. Contact the onionsite administrator.

Details: 0xF0 — The requested onion service descriptor can't be found on the hashring and therefore the service is not reachable by the client.

```

Steps to reproduce

- Change baseurl in dom0@/etc/yum.repos.d/qubes-dom0.repo
- sudo qubes-dom0-update --enablerepo=qubes-dom0-security-testing --clean -y
 

Expected behavior
New security packages will be downloaded

Actual behavior
Could not connect to server

**Comment by DemiMarie** [comment]
Known problem, due to a hardware fault.  Being worked on.

**Comment by andrewdavidwong** [comment]
This appears to be a [duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If anyone believes this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.
