### ISSUE TITLE
Qubes Manager should refresh disk usage automatically

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#7619]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### The problem you're addressing (if any)

Qubes Manager does not refresh some statistics (such as disk usage) automatically.  Refreshing them requires closing and relaunching it.

### The solution you'd like

Qubes Manager should automatically refresh these statistics.

### The value to a user, and who that user might be

All users who use Qubes Manager will benefit from up-to-date disk usage information.

**Comment by alimirjamali** [comment]
> Qubes Manager should automatically refresh these statistics.

How frequently? There is essentially no event hook for many of the statistics (.e.g disk usage change). This has to be done via a timer.

**Comment by alimirjamali** [comment]
> Is it not possible to create a hook to avoid polling a large number of VMs?

There are already hooks for property and feature changes. But disk usage is neither a property nor a feature. During the execution of the VM, it could dynamically change a lot many times per second.

**Comment by alimirjamali** [comment]
It turns out that there is a timer to update storage stats, [written by Marmarta last year](https://github.com/QubesOS/qubes-manager/commit/df5748ca25f7199dedcff3ec7b24f052dece8ebd). And it updates the storage stats every 5 minutes (which is too slow IMO). 

Some considerations:
- Updating too fast might result on some sort of race conditions. I tested 100ms and it did not break anything.
- Adding a config to Qube Manager for setting the update period is doable. But contradicts the trend of breaking Qube Manager to smaller parts.
- This is a minor issue. We could keep it simple. Reducing 5 minutes to 1000ms sounds reasonable.

**Comment by marmarek** [comment]
Refreshing disk usage too often is a bad idea. Fetching this data is quite heavy operation and doing it every second will produce noticeable load be quite battery-unfriendly. This is the main reason why it isn't done more often. And BTW, what you did isn't really refreshing it every 1s or even 100ms, there is internal cache for 30s on the core-admin side.

**Comment by alimirjamali** [comment]
> Refreshing disk usage too often is a bad idea. Fetching this data is quite heavy operation and doing it every second will produce noticeable load be quite battery-unfriendly. This is the main reason why it isn't done more often. And BTW, what you did isn't really refreshing it every 1s or even 100ms, there is internal cache for 30s on the core-admin side.

Ok. I was not aware about the core-admin side cache. Considering that the code only refreshes the stats for running qubes, is it still a heavy operation to do it every 30s?

**Comment by marmarek** [comment]
Maybe make that configurable? If somebody keeps qubes manager open all the time (I know some users do), 30s could still be noticeable.
Or maybe, do 30s if qubes manager has focus and 5min otherwise?

**Comment by alimirjamali** [comment]
> Or maybe, do 30s if qubes manager has focus and 5min otherwise?

This sounds the most reasonable. And automatic refresh on getting refocused.
