### ISSUE TITLE
Issues with Lenovo Yoga Slim 7 ProX (AMD Ryzen 6800HS)

### ISSUE THREAD

**Issue by dylangerdaly** [QubesOS/qubes-issues#7620]
### Qubes OS release
R4.1 (ISO built with kernel-latest - 5.18.9-1) - https://builds.sr.ht/~dylanger/job/804051

### Brief summary
Following on from https://github.com/QubesOS/qubes-issues/issues/7570, in order to install and boot, I'm required to add `dom0_max_vcpus=1 dom0_vcpus_pin` to dom0's CMDLINE, this is [similar](https://github.com/QubesOS/qubes-issues/issues/6055#issuecomment-692946662) to what I had to do when Ryzen 4000 series laptops had just come out

When I attempt to start an appVM, any appVM, fedora-36 templateVM for example, the VM starts, then the entire device hangs and resets, I'm unable to view any logs because the entire device resets before I can read logs.

xen-devel mailing list thread: https://xen.markmail.org/search/?q=Dylanger#query:Dylanger+page:1+mid:svghzn57btjkwjax+state:results

### Steps to reproduce
- Create a Qubes ISO with kernel-latest
- Boot it on a Yoga Slim 7 ProX

### Expected behavior
- QubesOS working

### Actual behavior
- Limiting dom0 to 1 pinned vcore
- Starting any appVM results in the device resetting

**Comment by dylangerdaly** [comment]
I've submitted a PR to fix the keyboard on Ryzen 6000 platforms here -> https://github.com/QubesOS/qubes-linux-kernel/pull/614

You can download the rpm here: https://builds.sr.ht/~dylanger/job/805565 but you shouldn't trust it.

**Comment by n0madK** [comment]
Getting the same thing on a Ryzen 9 6950HS with kernel 5.18.14-1. Booting template VM causes the system to hang, mouse stops responding, then the system reboots 5 seconds later. Anyone have ideas how to debug further?

**Comment by dylangerdaly** [comment]
Okay so this confirms it's not a Lenovo specific UEFI thing, it's affecting all AMD Ryzen 6000 series CPUs. This is the _exact_ issue I'm having.

I've already written into the xen mailing list however I don't think anyone is running Xen on Ryzen 6000 yet, at all, if I had to guess it fees like a DMA/Memory violation issue.

**Comment by dylangerdaly** [comment]
I'm pleased to say I have Qubes working quite stable on the Yoga Slim 7 ProX (AMD Ryzen 6800HS)

In order to drop the `dom0_max_vcpus`, you simply add `x2apic=false` to Xen's CMDLINE this allows Xen to work correctly on AMD Ryzen 6000 Series laptops.

Aside from this, pciback'ing troublesome PCIe devices such as AMD's "Multimedia Controller" fixed the reset issues I was having.

The device is now functional.

**Comment by andrewdavidwong** [comment]
Closed as "not a bug" (the reported behavior is not a bug and is already working as intended). If anyone believes this is a mistake, please leave a comment, and we'll be happy to take another look. Thank you.

**Comment by samet-g** [comment]
I have same processor and It seems like Qubes doesn't support it. Anyone can help me?

**Comment by andrewdavidwong** [comment]
@samet-g: Please note that the issue tracker (`qubes-issues`) is not intended to serve as a help desk or tech support center. Instead, we've set up other [venues where you can ask for help and support, ask questions, and have discussions](https://www.qubes-os.org/support/). (By contrast, the issue tracker is more of a technical tool intended to support our developers in their work.) Thank you for your understanding!
