### ISSUE TITLE
Per-disposable configuration

### ISSUE THREAD

**Issue by ddevz** [QubesOS/qubes-issues#7623]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### The problem you're addressing (if any)
When using disposables (for example sys-net), it's not possible to configure things that are unique to the disposable (as opposed to configuration settings that are applied to all disposables made from that single template).  Example: setting a static ip address in sys-net

### The solution you'd like
Ability to configure qubes to automatically run a disposable specific command after boot of the disposable.  For example, allow user to configure it to run "ifconfig eth0 192.168.0.101"
This could be generalized further into configuring a (optional) "rc.local" for a disposable

### The value to a user, and who that user might be
 * The above example case is people who want static IP addresses in sys-net
 * A more generalized class of people would be people who want to change one configuration option of a disposable without having to create a separate template each time.

Another possible example could be wanting to deny certain classes of usb devices is sys-usb1, and deny other classes of usb devices in sys-usb2.

**Comment by marmarek** [comment]
> making changes to a disposable template by doing "qvm-run -a debian-11-dvm gnome-terminal" is actually configuring the "private storage" (I.E. the /rw volume) and not the "system storage", meaning that system updates will not increase the storage size?

Yes, exactly.
