### ISSUE TITLE
Debian minimal templates include qubes-core-agent-networking

### ISSUE THREAD

**Issue by unman** [QubesOS/qubes-issues#7625]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
4.1

### Brief summary
As title.

### Steps to reproduce
Examine installed packages in debian-11-minimal

### Expected behavior
qubes-core-agent-networking will not be installed.
(It is not installed in Fedora minimal templates.)

### Actual behavior
qubes-core-agent-networking is installed.

It is pulled in via qubes-vm-dependencies.
In fact that package is in *both* qubes-vm-dependencies and qubes-vm-recommended, in Debian.

**Comment by DemiMarie** [comment]
That is strange.  I wonder if the `Recommends: qubes-vm-recommended` line is the problem.

**Comment by unman** [comment]
PEBKAC
