### ISSUE TITLE
Gray qube icons in Qube Manager are black instead of gray

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#7627]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

Qubes 4.1.1

### Brief summary

In the Qube Manager, qubes with the gray/grey label should have gray qube icons. Instead, they have black qube icons.

However, the icon colors in the app menu (default/old, not the new/testing one) are correct.

(Historical note: This is reminiscent of #3471 but now with black instead of green.)

**Comment by marmarta** [comment]
....found it, pushed a fix, and well, I wish git blame didn't show that it was my fault for accidentally calling gray black in one place :D
