### ISSUE TITLE
Qubes Update tool: Support controlling the "Details" pane using the keyboard

### ISSUE THREAD

**Issue by dominoomni** [QubesOS/qubes-issues#7635]
### The problem you're addressing (if any)

In Qubes OS versions 4.0 and 4.1 Dom0 Qubes Updater have window element ( text label ) called "Details" that can not be pressed from keyboard

### The solution you'd like

One possible solution can be conversion window element "Details" from text label to checkbox

### The value to a user, and who that user might be

There will be more consistency when control window elements from keyboard

**Comment by dominoomni** [comment]
Files that can be modified to achieve desired behaviour

```/usr/lib/python3.5/site-packages/qui/updater.py```
```/usr/lib/python3.5/site-packages/qui/updater.glade```

**Comment by dominoomni** [comment]
proposed changes

```diff
--- /home/user/projects/_py_/qui/updater.py.orig	2020-10-25 10:01:08.000000000 +0600
+++ /home/user/projects/_py_/qui/updater.py.new	2022-04-29 23:00:14.943000000 +0600
@@ -68,8 +68,8 @@
         self.details_icon = self.builder.get_object("details_icon")
         self.builder.get_object("details_icon_events").connect(
             "button-press-event", self.toggle_details)
-        self.builder.get_object("details_label_events").connect(
-            "button-press-event", self.toggle_details)
+        self.builder.get_object("details_label").connect(
+            "clicked", self.toggle_details)
 
         self.load_css()
 
```

and

```diff
--- /home/user/projects/_py_/qui/updater.glade.orig	2020-10-25 10:01:08.000000000 +0600
+++ /home/user/projects/_py_/qui/updater.glade.new	2022-04-29 22:58:05.731000000 +0600
@@ -170,16 +170,12 @@
                       </packing>
                     </child>
                     <child>
-                      <object class="GtkEventBox" id="details_label_events">
+                      <object class="GtkCheckButton" id="details_label">
+                        <property name="label" translatable="yes">Details</property>
                         <property name="visible">True</property>
-                        <property name="can_focus">False</property>
-                        <child>
-                          <object class="GtkLabel" id="details_label">
-                            <property name="visible">True</property>
-                            <property name="can_focus">False</property>
-                            <property name="label" translatable="yes">Details</property>
-                          </object>
-                        </child>
+                        <property name="can_focus">True</property>
+                        <property name="receives_default">False</property>
+                        <property name="draw_indicator">True</property>
                       </object>
                       <packing>
                         <property name="expand">False</property>

```

**Comment by dominoomni** [comment]
modified Qubes Updater screenshot

qubes_updater_checkbox_details_2022-07-21_18-20-58.png

![qubes_updater_checkbox_details_2022-07-21_18-20-58](https://user-images.githubusercontent.com/109735700/180213287-22cdd9bf-e822-4f24-86f3-82ad5b93a054.png)

**Comment by DemiMarie** [comment]
@dominoomni can you submit a PR?

**Comment by dominoomni** [comment]
https://github.com/QubesOS/qubes-desktop-linux-manager/pull/130

is it correct ?

**Comment by dominoomni** [comment]
also added PR https://github.com/QubesOS/qubes-desktop-linux-manager/pull/131

backported mnemonics from https://github.com/QubesOS/qubes-desktop-linux-manager/pull/128 to v4.0

**Comment by dominoomni** [comment]
https://github.com/QubesOS/qubes-issues/issues/7635#issuecomment-1191415408

changes in this comment are compatible with both branches "release4.0" and "release4.1"

**Comment by marmarta** [comment]
Fixed by https://github.com/QubesOS/qubes-desktop-linux-manager/pull/132
