### ISSUE TITLE
Support for drawing tablet with stylus

### ISSUE THREAD

**Issue by iacore** [QubesOS/qubes-issues#7636]
### Qubes OS release
r4.1

### The Issue
Buttons on the tablet work in sys-usb, but not sent to dom0.
Buttons on the pen work (since it has the same XInput deviceid with Motion events)

Also, I got three more axis in dom0, and the coordinate system is different. Did not appear to affect tablet usage.

Logs in dom0:
```
EVENT type 17 (RawMotion)
    device: 2 (23)
    detail: 0
    flags: 
    valuators:
          0: 4262.00 (4262.00)
          1: 3096.00 (3096.00)
          2: 0.00 (0.00)
          3: 0.00 (0.00)
          4: 0.00 (0.00)
          5: -900.00 (-900.00)
```

### Details
Example events from `xinput test-xi2` in sys-usb:

device id
2 (8) is buttons on the tablet itself
2 (9) is buttons on the pen

```
EVENT type 1 (DeviceChanged)
    device: 2 (8)
    reason: SlaveSwitch
	Reporting 8 classes:
		Class originated from: 8. Type: XIButtonClass
		Buttons supported: 8
		Button labels: None None None None None None None None
		Button state:
		Class originated from: 8. Type: XIValuatorClass
		Detail for Valuator 0:
		  Label: Abs X
		  Range: 0.000000 - 16777215.000000
		  Resolution: 0 units/m
		  Mode: absolute
		  Current value: 0.000000
		Class originated from: 8. Type: XIValuatorClass
		Detail for Valuator 1:
		  Label: Abs Y
		  Range: 0.000000 - 16777215.000000
		  Resolution: 0 units/m
		  Mode: absolute
		  Current value: 0.000000
		Class originated from: 8. Type: XIValuatorClass
		Detail for Valuator 2:
		  Label: Abs Pressure
		  Range: 0.000000 - 16777215.000000
		  Resolution: 0 units/m
		  Mode: absolute
		  Current value: 0.000000
		Class originated from: 8. Type: XIValuatorClass
		Detail for Valuator 3:
		  Label: None
		  Range: 0.000000 - 4096.000000
		  Resolution: 0 units/m
		  Mode: absolute
		  Current value: 0.000000
		Class originated from: 8. Type: XIValuatorClass
		Detail for Valuator 4:
		  Label: None
		  Range: 0.000000 - 4096.000000
		  Resolution: 0 units/m
		  Mode: absolute
		  Current value: 0.000000
		Class originated from: 8. Type: XIValuatorClass
		Detail for Valuator 5:
		  Label: Abs Wheel
		  Range: 0.000000 - 71.000000
		  Resolution: 0 units/m
		  Mode: absolute
		  Current value: 0.000000
		Class originated from: 8. Type: XIValuatorClass
		Detail for Valuator 6:
		  Label: None
		  Range: 0.000000 - 71.000000
		  Resolution: 0 units/m
		  Mode: absolute
		  Current value: 0.000000

EVENT type 15 (RawButtonPress)
    device: 2 (8)
    detail: 1
    flags: 
    valuators:

EVENT type 16 (RawButtonRelease)
    device: 2 (8)
    detail: 1
    flags: 
    valuators:

EVENT type 17 (RawMotion)
    device: 2 (9)
    detail: 0
    flags: 
    valuators:
          0: 1103.69 (1103.69)
          1: 16770151.65 (16770151.65)
          2: 0.00 (0.00)
```

### Comments

RawMotion.valuators[2] is pressure

We have to use XInput extension to get those events.

The valuators [0] and [1] go up to 10000000. For precision, maybe? (IEEE float doesn't care though)

Current code for mouse (x/y means pixel from top left) won't work at all for this type of devices. No idea how X server handles this.

**Comment by locriacyber** [comment]
Wrong label. Is `T: enchancement`.

**Comment by marmarek** [comment]
There is `qubes.InputTablet` qrexec service, you can allow it in qrexec policy.

**Comment by locriacyber** [comment]
Sorry, I updated the issue description accordingly.

**Comment by DemiMarie** [comment]
I wonder how Wayland handles this.  Wayland has a much better model than X11 does, especially when it comes to security.

**Comment by locriacyber** [comment]
From reading this
https://wayland-book.com/seat/pointer.html
https://wayland-book.com/seat/keyboard.html
https://wayland-book.com/seat/touch.html

Some findings:
- seat capability
- game controller is wl_pointer (motion & axis events are here)
- "focus" is not a concept. instead...
- surface receive `enter/leave` event from wl_pointer, when the mouse cursor enter/leave the surface rectangle
- surface receive `enter/leave` event from wl_keyboard. I think popular wl compositor will give keyboard focus
- every seat has only 1 wl_pointer & 1 wl_keyboard

>  If you plug a second keyboard into your computer, it's generally assigned to the same seat as the first, and the keyboard layout and so on are dynamically switched as you start typing on each. These implementation details are left to the Wayland compositor to consider.

I didn't find "pressure" in those 3 capabilities. Maybe pressure is mapped as "axis"? I don't use wayland so I don't know.
The decision is made by the compositor with libinput.
https://wayland.freedesktop.org/libinput/doc/latest/tablet-support.html

I also found this proposal of IME capability (like a virtual device for text). Qubes OS could share 1 IME for all VM.
https://dcz_self.gitlab.io/posts/input_method/

https://wayland.freedesktop.org/libinput/doc/latest/what-is-libinput.html#libinput-and-wayland
![image](https://user-images.githubusercontent.com/74560659/180484456-d08af0ab-06c3-4a9b-8913-05b4d1f90251.png)

**Comment by locriacyber** [comment]
Turns out pressure is not supported. https://forum.qubes-os.org/t/support-for-pressure-sensitive-pen-tablet/6098/6
