### ISSUE TITLE
I cannot figure out how to anonymous my Mac address

### ISSUE THREAD

**Issue by zachbarnes544** [QubesOS/qubes-issues#7638]
The explanation on GitHub makes no sense to me and I cannot figure out how to enter those commands or file them or create a file and I am extremely lost. can someone please help me, i'm very new to the os

**Comment by andrewdavidwong** [comment]
Please note that the issue tracker (`qubes-issues`) is not intended to serve as a help desk or tech support center. Instead, we've set up other [venues where you can ask for help and support, ask questions, and have discussions](https://www.qubes-os.org/support/). (By contrast, the issue tracker is more of a technical tool intended to support our developers in their work.) Thank you for your understanding!
