### ISSUE TITLE
"QubesIncoming" directory is automatically in Nautilus' favorites in every qube

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#7640]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

Qubes 4.1.1

### Brief summary

Not sure if this is intentional, but I've noticed that the `QubesIncoming` directory is in my Nautilus favorites in every qube, even though I didn't add it. I find myself having to manually remove it from every qube. (And these are all existing qubes restored from a backup.)

If this was intentional, please reconsider. It's a really bad idea to mess with users' favorites and add junk that they don't want.

**Comment by SaswatPadhi** [comment]
Looks like this script is responsible:
https://github.com/QubesOS/qubes-core-agent-linux/blob/master/qubes-rpc/nautilus/qvm_nautilus_bookmark.sh

**Comment by marmarek** [comment]
https://github.com/QubesOS/qubes-issues/issues/2229

**Comment by andrewdavidwong** [comment]
> #2229 - intentional feature

Ah, thanks for the ref. I had forgotten about that issue.

Well, I've already expressed my opinion about this and made my case in the comments on #2229, so feel free to close this as "won't fix" if you disagree.

**Comment by andrewdavidwong** [comment]
On second thought, I guess this should actually be closed as a duplicate, since #2229 already exists.
