### ISSUE TITLE
Using qubesctl to update dom0 appears to output some literal code

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#7641]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

Qubes 4.1.1

### Brief summary

I think attempting to update dom0 is outputting some literal code instead of running the code.

### Steps to reproduce

In dom0, run:

```
sudo qubesctl --show-output state.sls update.qubes-dom0 2>&1
```

### Expected behavior

Normal output; no literal code.

### Actual behavior

This is in the output:

```
Name: if qubes-dom0-update --quiet --assumeyes --clean --action=clean expire-cache >/dev/null 2>&1; then
    echo "result=True comment='Cache cleaned'"
else
    echo "result=False comment='Could not clean cache'"
fi
```

I'm guessing that I, as the user, am only supposed to see either 'Cache cleaned' or 'Could not clean cache'.

**Comment by andrewdavidwong** [comment]
On second look, these are the next lines of the output:

```
    ESC[0;32m  Result: TrueESC[0;0m
    ESC[0;32m Comment: Cache cleanedESC[0;0m

```

So I guess it's working correctly and this is just an extremely verbose "name" that should probably be something more user-facing.

**Comment by DemiMarie** [comment]
You guessed correctly @andrewdavidwong.  I will fix this.
