### ISSUE TITLE
qubes-gui-daemon 4.1.22 breaks seamless mode in Windows 7 qubes

### ISSUE THREAD

**Issue by GWeck** [QubesOS/qubes-issues#7643]
### Qubes OS release

R4.1.1

### Brief summary

If dom0 is updated from the current-testing repository, `qubes-gui-daemon` is upgraded from version 4.1.21 to version 4.1.22. After this, any window of a Windows 7 VM running in seamless mode is empty.

### Steps to reproduce

Update dom0 from the current-testing repository and observe that the version of `qubes-gui-daemon` has changed. Then start some application in a Windows 7 VM running QWT 4.1.68.

### Expected behavior

The window of this application should show its content as it did before.

### Actual behavior

The window just shows the border created by Qubes and is empty.

### Additional context

Downgrading `qubes-gui-daemon` to its previous version via `sudo qubes-dom0-update --action=downgrade qubes-gui-daemon` restores the previous correct behavior.

Is there a way to stop the update of just this one component, even if the current-testing repository for dom0 is activated?

**Comment by marmarek** [comment]
Can you enable debugging for this VM ("debug" property) and share `/var/log/qubes/guid.<vmname>.log`?

**Comment by DemiMarie** [comment]
This is almost certainly due to <https://github.com/QubesOS/qubes-gui-daemon/commit/b3bd97cfe91da06efbf0bf7358fd60a45e49eea1>.

**Comment by GWeck** [comment]
@marmarek As far as I can see it, that log is empty.

Hopefully,  the issue is solved now. It went in the direction that @DemiMarie described, which I suspected, too.

Thanks a lot for your quick and competent help !!!

**Comment by GWeck** [comment]
Hi - I checked the new version. Everything o.k. Thanks again!
