### ISSUE TITLE
Error when starting anon-whonix: "Qube anon-whonix has failed to start: internal error: libxenlight failed to create new domain ‘anon-whonix’"

### ISSUE THREAD

**Issue by qqubes** [QubesOS/qubes-issues#7645]
### Qubes OS release

4.1

### Brief summary

This issue is possibly two similar but separate issues. It/they were [reported](https://forum.qubes-os.org/t/problems-with-anon-whonix/12705) in the Qubes forums:

I’ve seen the following two issues recur a number of times:

1) When I try to start `anon-whonix` a popup with the following error appears:

#### Qube anon-whonix has failed to start: internal error: libxenlight failed to create new domain ‘anon-whonix’

2) I can start `anon-whonix`, but it fails the connectivity test, i.e. the IP Check on the Whonix welcom page. Shutting down the qube and restarting it does not help.

The only way I know to fix either of these is to restart the computer.

Could it possibly be related to [issue-1269902751](https://github.com/QubesOS/qubes-issues/issues/7563#issue-1269902751)?

### Steps to reproduce

As described this only happens intermittently and is unpredictable.

### Expected behavior

`anon-whonix` starts up properly.

**Comment by andrewdavidwong** [comment]
[Every issue must be about a single, actionable thing.](https://www.qubes-os.org/doc/issue-tracking/#every-issue-must-be-about-a-single-actionable-thing) Adjusting this issue to be only about the first problem described.

**Comment by andrewdavidwong** [comment]
FWIW, "internal error: libxenlight failed to create new domain" is a very common error message:

https://github.com/QubesOS/qubes-issues/issues?q=%22internal+error%3A+libxenlight+failed+to+create+new+domain%22

**Comment by DemiMarie** [comment]
> FWIW, "internal error: libxenlight failed to create new domain" is a very common error message:
> 
> https://github.com/QubesOS/qubes-issues/issues?q=%22internal+error%3A+libxenlight+failed+to+create+new+domain%22

This error basically means, “something went wrong in libxl, look at libxl logs for details”.  It should really be replaced with a better error message, ideally one that actually indicates what happened in libxl.  Right now it is basically a useless catchall.

**Comment by qqubes** [comment]
> This error basically means, “something went wrong in libxl, look at libxl logs for details”. It should really be replaced with a better error message, ideally one that actually indicates what happened in libxl. Right now it is basically a useless catchall.

I'm not sure where I can find the `libxl` logs so that I can check them next time this happens?

**Comment by rustybird** [comment]
> #### [...] internal error: libxenlight failed to create new domain [...]

> As described this only happens intermittently and is unpredictable.

@qqubes can you try this search in dom0:

    journalctl -g 'still has dirty pages|losetup .* failed|libxenlight failed'

If you're seeing those three messages close together around the time the error happens, then it's due to a kernel bug (which will be [fixed](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=98ded54a33839e7b8f8bed772e01a544f48e33a7) in v5.19).

**Comment by qqubes** [comment]
Issue (2) just occurred after a suspend and resume, which others have reported in the forum.

I notice that the padlock is not even responsive. So I tried to stop `sys-whonix`, but it gives an error. `journalctl` says (I cannot copy & paste the whole output from `dom0`): `internal error: Failed to shutdown domain '6' with libxenlight`.

Nothing in `libxl` logs for this second case.

**Comment by adrelanos** [comment]
For issue tracking purposes:

* Affects Qubes-Whonix: Yes, as reported.
* Caused by Whonix-Whonix source code: Highly unlikely.
* This is primarily a Qubes dom0 issue.

----

Feature request:

* Improve the error message, automatically collect any logs the user should append to this bug report to make it actionable by developers.

**Comment by DemiMarie** [comment]
> Feature request:
> 
> * Improve the error message, automatically collect any logs the user should append to this bug report to make it actionable by developers.

Unfortunately the error message (which comes from libvirt) is absolutely terrible.  Somewhere the actual error gets swallowed before qubesd gets it.

IMO this needs to be fixed so that the actual error is somewhat self-contained.
