### ISSUE TITLE
Qube Manager: Progress bars don't move

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#7647]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

Qubes 4.1.1

### Brief summary

When renaming a qube in the Qube Manager, a progress bar is displayed, but it never moves. Not sure if this is theme-dependent. Eventually, it finishes normally, but some users might think it's frozen/hung due to the progress bar not moving.

### Steps to reproduce

Rename a qube in the Qube Manager (other operations might also work).

### Expected behavior

Progress bar moves while the operation is in progress.

### Actual behavior

Progress bar is stuck/static. Never moves.

**Comment by marmarta** [comment]
Hm, I can't reproduce this: I get a so-called pulsating progress bar, which is not showing actual progress (because we generally don't have info on that), but is animated slightly to given an impression of something happening.

**Comment by andrewdavidwong** [comment]
> Hm, I can't reproduce this: I get a so-called pulsating progress bar, which is not showing actual progress (because we generally don't have info on that), but is animated slightly to given an impression of something happening.

It looks different for me now too. It used to be a segment that was supposed to be move back and forth across an empty meter but just stood still. Now It's a full bar with a striped pattern, where the pattern is animated and moves continuously. So, all good now.

---

Closing as "cannot reproduce" (we were unable to reproduce this issue). If anyone believes this is a mistake, or if anyone can reproduce the issue, please leave a comment, and we'll be happy to reopen this. Thank you.
