### ISSUE TITLE
Qubes 4.1.1. fresh installation - no audio

### ISSUE THREAD

**Issue by esatravi** [QubesOS/qubes-issues#7653]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

4.1.1

### Brief summary

After fresh installation of Qubes 4.1.1 on HP 840 G8 laptop there is no audio available in any of the VMs. 

### Steps to reproduce

No sound / audio available after fresh 4.1.1. installation. 
open any mp3 file to play it comes out mute - I can see playing progress in VLC but no sound is coming through the speakers or headphones. The laptop is not on mute. Just no sound at all. 
Even Qubes standard error message sounds are missing. 

I followed the audio troubleshooting documentation and upgraded kernel to 'latest' but that did not change anything. I have no sound/audio in qubes 4.1.1 whatsoever. 

### Expected behavior

Audio / sound through the speakers when playing sound files / streams/ etc. 

### Actual behavior

no sound / no audio in the quebes os system.

**Comment by esatravi** [comment]
Thank you for this suggestions. I run dmesg command in dom0 and got the following output: 

[   78.399060] sof-audio-pci-intel-tgl 0000:00:1f.3: DSP detected with PCI class/subclass/prog-if info 0x040100
[   78.399191] sof-audio-pci-intel-tgl 0000:00:1f.3: Digital mics found on Skylake+ platform, using SOF driver
[   78.399217] sof-audio-pci-intel-tgl 0000:00:1f.3: enabling device (0000 -> 0002)
[   78.400388] sof-audio-pci-intel-tgl 0000:00:1f.3: DSP detected with PCI class/subclass/prog-if 0x040100
[   78.400489] sof-audio-pci-intel-tgl 0000:00:1f.3: bound 0000:00:02.0 (ops i915_audio_component_bind_ops [i915])
[   78.407343] sof-audio-pci-intel-tgl 0000:00:1f.3: use msi interrupt mode
[   78.442345] sof-audio-pci-intel-tgl 0000:00:1f.3: hda codecs found, mask 5
[   78.442350] sof-audio-pci-intel-tgl 0000:00:1f.3: using HDA machine driver skl_hda_dsp_generic now
[   78.442357] sof-audio-pci-intel-tgl 0000:00:1f.3: DMICs detected in NHLT tables: 4
[   78.442844] sof-audio-pci-intel-tgl 0000:00:1f.3: Direct firmware load for intel/sof/sof-tgl.ri failed with error -2
**[   78.442848] sof-audio-pci-intel-tgl 0000:00:1f.3: error: sof firmware file is missing, you might need to
[   78.442849] sof-audio-pci-intel-tgl 0000:00:1f.3:        download it from https://github.com/thesofproject/sof-bin/
[   78.442850] sof-audio-pci-intel-tgl 0000:00:1f.3: error: failed to load DSP firmware -2
[   78.443763] sof-audio-pci-intel-tgl 0000:00:1f.3: error: sof_probe_work failed err: -2**

The last few lines suggests missing firmware file: "download it from https://github.com/thesofproject/sof-bin/"

How do I install it in qubes? Please explain. 
Many thanks

**Comment by esatravi** [comment]
@alt3r-3go
[RESOLVED]
I downloaded the new sof-bin firmware and installed it in dom0 (copied it) - as mentioned in dmesg. 

The sound is back again!

I'm so pleased the fix was as easy as that. 

Thank you very much @alt3r-3go for your expert advice. :)

**Comment by esatravi** [comment]
If you could also help or suggest something for my 2 other issues I would would be forever grateful: 

1. https://github.com/QubesOS/qubes-issues/issues/7652 - resizing windows run in a VM freezes that VM.

2. https://github.com/QubesOS/qubes-issues/issues/7611 - laptop doesn't wake-up from suspend mode.

Thank you :)

**Comment by esatravi** [comment]
Resolved with sof firmware update in dom0

**Comment by DemiMarie** [comment]
Reopening as the new firmware should be available by default.

**Comment by esatravi** [comment]
@DemiMarie 
You beat me to it. But a bit more investigation is required as qubes tends to lose the audio after some time - from what I've observed so far audio starts deteriorating, and eventually not be available, when I open new VMs. But I need more time to look at the symptoms - something to do with memory consumption? cpu? other? I will periodically monitor dmesg for details.

Nevertheless, the new firmware did bring back audio to my qubes installation - which is most important.

**Comment by na--** [comment]
@esatravi, I had the same issues as you on an laptop with an 11th generation Intel CPU. I also solved them the same way, by manually installing [sof-bin](https://github.com/thesofproject/sof-bin/) in dom0... :disappointed: So yeah, I'd really appreciate some newer drivers in dom0. Unfortunately, I also hit the same issue with the audio deteriorating and breaking up, though I found the most unlikely workaround completely by accident! :sweat_smile: I still haven't had time to figure out **why** it works, but it does work for me, for some weird reason... :man_shrugging: 

Open the volume mixer in dom0 by running `pavucontrol` or by left clicking on the volume icon in the system tray and then "Audio Mixer...". Go to the "Configuration" tab (last one) and make sure that the "Show volume meters" option at the bottom is checked. Voila, audio should now work! :rofl: No idea why, and no idea why it starts breaking up as soon as I close the volume control app or uncheck the "Show volume meters" checkbox :confused: :man_shrugging: But as long as I keep the window open, I get high quality audio... :man_facepalming: 

I assume this is some weird heisenbug where actually monitoring at the volume fixes some driver/firmware bug :man_shrugging: Bug again, no idea why it actually works... 

Please share if this also fixes the issue for you, one more data point either way might be helpful.

**Comment by brendanhoar** [comment]
My gut says the trigger (not root cause, but trigger) might have something to do with dom0 changing the bitrate/channels(/codec?) at the hardware level when a single source starts playing solo vs. sticking to the working hw config and having dom0 do software conversions to that particular default bitrate/channels(/codec?).

Keeping a monitoring window open might block dom0 from switching b/c(/c?) and use software conversion leading to the latter situation even when no sound is playing.

Still not clear to me if this is some sort of Xen/pci issue or just the fact that Qubes users tend to use now-ancient hw and no one is testing hw initialization of older sound hardware under linux sound driver changes.

B

**Comment by marmarek** [comment]
Updated alsa-sof-firmware is available in current-testing: https://github.com/QubesOS/updates-status/issues/3022

**Comment by esatravi** [comment]
@na--  Thank you for your comments and the tip. I would have never discovered it myself. But for now it seems like a good-enough workaround - to always keep the pavucontrol panel open. FYI - the 'show volume meters' was already checked by default after fresh qubes install. It is keeping the panel open (yet minimized) that prevents sound from deterioration. 

The new qubes 4.1.1 also introduced another strange issue for me: https://github.com/QubesOS/qubes-issues/issues/7652 - what does window resize has got to do with VM freezing??? But it does.

**Comment by na--** [comment]
@marmarek, thanks! I removed my manually installed sof-bin v2.2 packages and installed `alsa-sof-firmware-2.1.1-1` from `current-testing` (along with all of the other current-testing updates) and can confirm it works for me, audio still works despite the new package being a slightly older version than the one I had before :tada: Unfortunately, the [heisenbug](https://github.com/QubesOS/qubes-issues/issues/7653#issuecomment-1199347657) that I and @esatravi encountered still exists, even on the slightly newer 5.18.14 kernel... Fortunately, the `pavucontrol` workaround also still works :sweat_smile: :tada: :man_shrugging: 

@brendanhoar, I didn't understand most of your post, sorry... My knowledge of both Linux and QubesOS audio details is very scarce and surface-level :disappointed: I can assist with remote debugging to test your hypothesis, if you tell me what to do, but I need to grok quite a few things before I can debug this on my own :disappointed:

**Comment by blockomat2100** [comment]
Your sound quality issue bug sounds similar to the one I already reported in #7634.

**Comment by na--** [comment]
@blockomat2100, I'd somehow missed that issue, but yeah, it seems like the same problem, especially since you also mention it gets fixed by having `pavucontrol` open. I was just about to open a new issue, but now I'll just subscribe to yours :eyes:

**Comment by esatravi** [comment]
We seem to have the temporary workaround for the audio playback but I struggle to get the microphone working. Right from the boot the little organge LED is on - Fn mute key, doubling as F8. There is no way I can turn it off, it is just on all the time as if the mic had some driver issues. 

Is it something that anybody else is experiencing with the 4.1.1. qubes release and 11th generation Intel CPU? 

@na--  
Is your microphone working OK? Perhaps you've got yet another tricks to suggest to get the mic working as well.

**Comment by na--** [comment]
Ah, indeed, my microphone also doesn't work! I hadn't even noticed that the laptop built-in mic doesn't work since I usually use an external USB microphone, but I rely on the built-in mic when traveling. Unfortunately, I don't have any tricks this time... :disappointed:

**Comment by na--** [comment]
@esatravi, since this issue was closed, and since https://github.com/QubesOS/qubes-issues/issues/7634 more accurately describes our problems now that the `alsa-sof-firmware` package was published, I suggest we move our discussion here?

**Comment by z01999** [comment]
same issue , even after upgrading to alsa-sof-firmware-2.1.1-1 , audio just working in one AppVM !
