### ISSUE TITLE
`sys-usb` has "Provides network" enabled by default

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#7669]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

Qubes OS 4.1.1

### Brief summary

It seems like a bug that `sys-usb` has `Provides network` enabled by default in the first place on systems with no networking devices in `sys-usb`.

Related: #7298

**Comment by marmarek** [comment]
It is intentional and it was pretty much always this way, so I'm a bit surprised you consider it a "bug" only now. There is some discussion (although not much) at https://github.com/QubesOS/qubes-issues/issues/1629. AFAIR that's to make easier use of USB network devices, including 3G/LTE modems, without necessarily routing all your network traffic through it (those some years ago, mobile data was significantly less available/more expensive and I think in some areas it still is).

**Comment by andrewdavidwong** [comment]
> It is intentional and it was pretty much always this way, so I'm a bit surprised you consider it a "bug" only now.

Hmm, strange that I never noticed it before (or maybe just forgot). Perhaps it's been so long since my last reinstallation that this is my first clean install since it became the default.

> There is some discussion (although not much) at https://github.com/QubesOS/qubes-issues/issues/1629. AFAIR that's to make easier use of USB network devices, including 3G/LTE modems, without necessarily routing all your network traffic through it (those some years ago, mobile data was significantly less available/more expensive and I think in some areas it still is).

The reason it seemed like a bug to me is simply that if I'm using a traditional `sys-net` and my offline `sys-usb` is not used for networking at all, then having `Provides network` enabled by default seems like a insecure default that slightly increases attack surface (and the possibility of accidental assignment) for no benefit on many machines. It seems like it would be better to ask or detect whether `sys-usb` *needs* to be used as a network provider on that machine, then enable it only for the users who need it, rather than for everyone.

However, I don't know how feasible that would be to implement. If you say that this is intentional, then I respect that. It's not difficult to uncheck this box once per installation (though I suspect many less experienced users will probably never know to do that).
