### ISSUE TITLE
Qubesos.github.io repo build failed with exit code 1

### ISSUE THREAD

**Issue by HPOA909** [QubesOS/qubes-issues#7671]
`qubes-issues` [is not the right place to ask questions or request
support](https://www.qubes-os.org/doc/issue-tracking/#do-not-submit-questions).
Instead, please see [help, support, mailing lists, and
forum](https://www.qubes-os.org/support/).

I committed the pull request on qubesos.github.io repo for 3-4 days before the 4.0 depreciate. However, the building bot was failed with erorrno 1. Anything wrong with the modification?

**Comment by andrewdavidwong** [comment]
> Anything wrong with the modification?

You can see by clicking on the "Details" link.

-----

Please note that the issue tracker (`qubes-issues`) is not intended to serve as a help desk or tech support center. Instead, we've set up other [venues where you can ask for help and support, ask questions, and have discussions](https://www.qubes-os.org/support/). (By contrast, the issue tracker is more of a technical tool intended to support our developers in their work.) Thank you for your understanding!
