### ISSUE TITLE
Allow creating sys-usb in installer even when USB keyboard is used

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#7674]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### The problem you're addressing (if any)

Most modern machines have just one USB controller, when it's left in dom0, all USB devices will be presented to dom0 (whether they will be useful is another question). It means that even on systems with primary keyboard on USB, having sys-usb improves overall security (it reduces impact of USB compromise from "unrestricted access to all the data" to "control over user input" - the latter makes the attack at least user-visible).
Secondly, there are cases where the is some USB keyboard (or device that looks like one, #7239, #3203) connected during installation, but the primary keyboard isn't there at all. In those cases, user should be able to enable sys-usb normally.

Besides security implications, having sys-usb when primary user input devices are on USB has also reliability implications. If sys-usb breaks, user has no way to interact with the system, in most cases leaving just hard reboot option. Example issues:
 - #6755 
 - #5823
 - #6445
 - #5445 
 - #7370 
 - #6824 

This is continuation of https://github.com/QubesOS/qubes-issues/issues/3516

### The solution you'd like

1. Do not block creating sys-usb even if USB keyboard is detected.
2. Add an option to allow USB keyboard (#3516) in initial setup
3. Enable the option above if USB keyboard is detected

And finally, until reliability issues listed above are solved, do _not_ enable sys-usb by default if USB keyboard is detected (but allow the user to choose creating it).

### The value to a user, and who that user might be

More consistent USB devices handling, slightly better dom0 isolation even if USB keyboard is used.

**Comment by arkenoi** [comment]
why not to whitelist just the specific keyboard that was available during the boot?

**Comment by DemiMarie** [comment]
@arkenoi If only it were that simple.  It turns out that USB device handling is generally a disaster.

**Comment by marmarek** [comment]
The initial-setup screen when keyboard is detected looks now like this:
![image](https://user-images.githubusercontent.com/726704/215265537-9f1697e7-df17-41a5-8944-4a5065c80d11.png)
