### ISSUE TITLE
Missing packages: kernel-devel / kernel headers for 5.15.x and 5.18.x

### ISSUE THREAD

**Issue by qufo418** [QubesOS/qubes-issues#7675]
### Qubes OS release
4.1

### Brief summary

I need to build the Tuxedo-Keyboard module bundle. I created a standalone HVM based on the template Fedora-32; installed development tools, and want to install the kernel-headers for kernel

    kernel-5.15.52-1.fc32.qubes.x86_64
    kernel-latest-5.18.9-1.fc32.qubes.x86_64

but what I can get, regardless of which kernel is active, is

    kernel headers 5.11.19-100.fc32

I don’t even have a 5.11.x kernel installed.

I tried this package

https://yum.qubes-os.org/r4.1/current/dom0/fc32/rpm/kernel-latest-devel-.18.9-1.fc32.qubes.x86_64.rpm

but it doesn’t work:

```
make -C /lib/modules/5.18.9-1.fc32.qubes.x86_64/build M=/home/user/My-Stuff/Development/Tuxedo-Keyboard/git/tuxedo-keyboard modules
make[1]: Entering directory '/usr/lib/modules/5.18.9-1.fc32.qubes.x86_64/build'
/bin/sh: -c: line 0: syntax error near unexpected token `('
/bin/sh: -c: line 0: `if [ "gcc (GCC) 10.3.1 20210422 (Red Hat 10.3.1-1)" != ""gcc (GCC) 10.3.1 20210422 (Red Hat 10.3.1-1)"" ]; then \'
make[1]: *** [Makefile:1724: prepare] Error 1
make[1]: Leaving directory '/usr/lib/modules/5.18.9-1.fc32.qubes.x86_64/build'
make: *** [Makefile:29: all] Error 2
```
### Steps to reproduce

1. Install kernel-latest and kernel-latest-qubes-vm 
2. Install and update fedora-32 template
3. Create standalone HVM based on the template fedora-32
4. Set kernel to 5.18
5. Start the standalone VM
6. Install kernel-devel or kernel-headers

Background as to why: https://forum.qubes-os.org/t/tuxedo-pulse-15-gen1-amd-ryzen-7-4800h-with-radeon-graphics-intermittent-crashes-and-worrying-messages-in-the-journal/12886

### Expected behavior

That the matching headers are installed.

### Actual behavior

dnf installs the kernel headers for 5.11

**Comment by marmarek** [comment]
> https://yum.qubes-os.org/r4.1/current/dom0/fc32/rpm/kernel-latest-devel-5.18.9-1.fc32.qubes.x86_64.rpm

This is the correct one.

> but it doesn’t work:

And this is the actual issue.

**Comment by qufo418** [comment]
> > https://yum.qubes-os.org/r4.1/current/dom0/fc32/rpm/kernel-latest-devel-5.18.9-1.fc32.qubes.x86_64.rpm
> 
> This is the correct one.

Good.

> 
> > but it doesn’t work:
> 
> And this is the actual issue.

You mean the make error, right? The syntax error that make throws makes no sense, because the Makefile in .../build seems to me okay. Did I miss it?

**Comment by marmarek** [comment]
Apparently it's about format of `include/config/auto.conf`. As a temporary workaround, remove all `"` from it (`sed -e 's/"//g' -i include/config/auto.conf` should do the trick).

**Comment by qufo418** [comment]
Ah, right. Thanks for the workaround.
What about that these packages aren't available via dnf in standalone VM?

**Comment by marmarek** [comment]
You are talking about dom0 kernel, so the package is in repository for dom0, not for a VM.

**Comment by qufo418** [comment]
Hmm, I think I tried that, but I check again.
But why not for a VM? That leads to building modules or even software in dom0. That's potentially dangerous. That's why I build a standalone VM based on Fedora 32. Build the modules, and maybe even a rpm (that's new to me, so I can't promise), and then I transfer only the rpm (ideally), or the modules to dom0. Shouldn't that the official way to build certain kernel modules?

**Comment by marmarek** [comment]
In fact, if you set the VM to the same kernel version as you use in dom0, you'll get kernel headers there automatically.

**Comment by qufo418** [comment]
> sed -e 's/"//g' -i include/config/auto.conf

I ran that sed command in `/usr/src/kernel/include/config`, and checked all double quotes are gone in auto.conf. But I get still the same error. I'm in the wrong directory?

**Comment by qufo418** [comment]
> In fact, if you set the VM to the same kernel version as you use in dom0, you'll get kernel headers there automatically.

Not on my system. I tested it this morning by creating a new standalone HVM based on the template fedora-32; kernel set 5.18. After creation I checked the directory /usr/src/kernels; it's empty. Then I ran the command:

- `sudo dnf install kernel-headers` - result: dnf offered the 5.11 kernel-headers but claimed that they are already installed.

then I ran:

- `sudo dnf install kernel-devel `- result: dnf offered the 5.11 kernel-devel package. After installation the kernel headers v 5.11... are installed under /usr/src/kernels

**Comment by qufo418** [comment]
> > sed -e 's/"//g' -i include/config/auto.conf
> 
> I ran that sed command in `/usr/src/kernel/include/config`, and checked all double quotes are gone in auto.conf. But I get still the same error. I'm in the wrong directory?

Probably...

I just tried to run:

`sudo sed -e 's/"//g' -i /lib/modules/5.18.9-1.fc32.qubes.x86_64/build/include/config/auto.conf`

but I got:

`sed: cannot rename /lib/modules/5.18.9-1.fc32.qubes.x86_64/build/include/config/sedjAmUXG: Operation not permitted`

Root has no permission?

**Comment by marmarek** [comment]
This filesystem is read-only indeed, nothing within the VM can modify it...

> I ran that sed command in `/usr/src/kernel/include/config`, and checked all double quotes are gone in auto.conf. But I get still the same error. I'm in the wrong directory?

Check what the module's makefile is using. Alternatively, you can build module using specific kernel sources by going to that kernel sources and calling `make M=MODULE_PATH modules` where `MODULE_PATH` is path to the module source dir.

**Comment by qufo418** [comment]
> qubes-builder uses a chroot and/or container to build the packages, so the version of the OS that qubes-builder is running on does not matter. Using a Fedora 32 VM is a bad idea

Hi DemiMarie, could I use qubes-builder to build only specific kernel-modules?

**Comment by qufo418** [comment]
> you can build module using specific kernel sources by going to that kernel sources and calling `make M=MODULE_PATH modules` where `MODULE_PATH` is path to the module source dir.

I got it. I copied the kernel-src from /usr/src/kernels to my build directory under my home directory, then I applied the sed fix. The build ran without errors for 5.18...; I transferred the modules to dom0 loaded them manually without any errors. Then made persistent across restarts, which works also. Now it's testing time and see what happens.
