### ISSUE TITLE
System crashes completely and restarts

### ISSUE THREAD

**Issue by hgoumner** [QubesOS/qubes-issues#7676]
### Qubes OS release

Qubes OS R4.1

> xen_version            : 4.14.3
Linux 5.10.90-1.fc32.qubes.x86_64
Installed Packages:  
grub2-qubes-theme.x86_64                          	5.14.4-2.fc32 
i3-settings-qubes.x86_64                          	1.9-1.fc32 
kernel-qubes-vm.x86_64                            	1000:5.10.90-1.fc32.qubes 
python3-qubesadmin.noarch                         	4.1.20-1.fc32 
python3-qubesdb.x86_64                            	4.1.12-1.fc32 
python3-qubesimgconverter.x86_64                  	4.1.16-1.fc32 
qubes-anaconda-addon.noarch                       	4.1.8-1.fc32 
qubes-artwork.noarch                              	4.1.12-1.fc32 
qubes-artwork-anaconda.noarch                     	4.1.12-1.fc32 
qubes-artwork-plymouth.noarch                     	4.1.12-1.fc32 
qubes-audio-daemon.x86_64                         	4.1.19-1.fc32 
qubes-audio-dom0.x86_64                           	4.1.19-1.fc32 
qubes-core-admin-addon-whonix.noarch              	4.0.2-1.fc32 
qubes-core-admin-client.noarch                    	4.1.20-1.fc32 
qubes-core-dom0.noarch                            	4.1.24-1.fc32 
qubes-core-dom0-linux.x86_64                      	4.1.17-1.fc32 
qubes-core-dom0-linux-kernel-install.x86_64       	4.1.17-1.fc32 
qubes-core-qrexec.x86_64                          	4.1.16-1.fc32 
qubes-core-qrexec-dom0.x86_64                     	4.1.16-1.fc32 
qubes-core-qrexec-libs.x86_64                     	4.1.16-1.fc32 
qubes-db.x86_64                                   	4.1.12-1.fc32 
qubes-db-dom0.x86_64                              	4.1.12-1.fc32 
qubes-db-libs.x86_64                              	4.1.12-1.fc32 
qubes-desktop-linux-common.noarch                 	4.1.11-1.fc32 
qubes-desktop-linux-manager.noarch                	4.1.11-1.fc32 
qubes-dom0-meta-packages.noarch                   	4.1.20-1.fc32 
qubes-gpg-split-dom0.x86_64                       	2.0.55-1.fc32 
qubes-gui-daemon.x86_64                           	4.1.19-1.fc32 
qubes-gui-dom0.x86_64                             	4.1.19-1.fc32 
qubes-img-converter-dom0.x86_64                   	1.2.11-1.fc32 
qubes-input-proxy.x86_64                          	1.0.26-1.fc32 
qubes-input-proxy-receiver.x86_64                 	1.0.26-1.fc32 
qubes-input-proxy-sender.x86_64                   	1.0.26-1.fc32 
qubes-libvchan-xen.x86_64                         	4.1.7-1.fc32 
qubes-manager.noarch                              	4.1.22-1.fc32 
qubes-menus.noarch                                	4.1.11-1.fc32 
qubes-mgmt-salt.noarch                            	4.1.13-1.fc32 
qubes-mgmt-salt-admin-tools.noarch                	4.1.13-1.fc32 
qubes-mgmt-salt-base.noarch                       	4.1.4-1.fc32 
qubes-mgmt-salt-base-config.noarch                	4.1.1-1.fc32 
qubes-mgmt-salt-base-topd.noarch                  	4.1.3-1.fc32 
qubes-mgmt-salt-config.noarch                     	4.1.13-1.fc32 
qubes-mgmt-salt-dom0.noarch                       	4.1.13-1.fc32 
qubes-mgmt-salt-dom0-qvm.noarch                   	4.1.4-1.fc32 
qubes-mgmt-salt-dom0-update.noarch                	4.1.8-1.fc32 
qubes-mgmt-salt-dom0-virtual-machines.noarch      	4.1.16-1.fc32 
qubes-pdf-converter-dom0.x86_64                   	2.1.12-1.fc32 
qubes-release.noarch                              	4.1-0.27 
qubes-release-notes.noarch                        	4.1-0.27 
qubes-repo-templates.noarch                       	4.1.2-1.fc32 
qubes-rpm-oxide.x86_64                            	0.2.3-1.fc32 
qubes-usb-proxy-dom0.noarch                       	1.1.1-1.fc32 
qubes-utils.x86_64                                	4.1.16-1.fc32 
qubes-utils-libs.x86_64                           	4.1.16-1.fc32 
xfce4-settings-qubes.x86_64                       	4.0.5-2.fc32 

### Brief summary

The system crashes randomly, but often when i stop a qube and start another one at the same time. When i had R4.0 installed on the same system there were no crashes and i have not done any fancy changes to the configuration of the system.

### Steps to reproduce

Either i just browse the internet or i start/stop a qube as mentioned above.

### Expected behavior

No crash.

### Actual behavior

Complete system crash and restart. I have attached the last syslog (journalctl -b 0) below. It seems that "qubes-qube-mana" has an issue, but i don't know what that is and how to use the info in the file to help me find the problem.

[crash.txt](https://github.com/QubesOS/qubes-issues/files/9242905/crash.txt)

Thanks for the work and any help in advance.

**Comment by marmarek** [comment]
> Linux 5.10.90-1.fc32.qubes.x86_64

Please install updates first, there is much newer kernel available.

**Comment by hgoumner** [comment]
Thanks for the prompt response. I updated dom0 and all qubes to the newest kernel. If the problem occurs again, i'll post here again. 

Is there a recommended method of obtaining the necessary info about a crash or is for example 'journalctl -p err' in dom0 enough?

**Comment by hgoumner** [comment]
Hello again,

today my computer crashed again, this time when i refreshed the app menus in the fedora-35 template. That's also the last thing that was written out to the syslog in dom0.

Any advice?

journal output: [crash_04_08.txt](https://github.com/QubesOS/qubes-issues/files/9260636/crash_04_08.txt)

**Comment by sucrecacao** [comment]
I have a similar issue, but not exactly the same, not sure if i'm suppose to open a new issue. 

Qubes shutdown and restart when I have one qube doing an intense work ( compiling gcc ) and I start a browser in another qube (  I was able to reproduce ). The hardware is thinkpad 380 toga

@marmarek  in which log file can I get relevant info about the crash ?

**Comment by andrewdavidwong** [comment]
> I have a similar issue, but not exactly the same, not sure if i'm suppose to open a new issue.

I'm not sure about the specifics of this case, but usually you should open a separate issue under those circumstances.

**Comment by sucrecacao** [comment]
@hgoumner 

You might want to rollback to kernel version 5.10, it fixed the issue for me!
