### ISSUE TITLE
Provide an always-available rescue VM for recovery

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#7680]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### The problem you're addressing (if any)

If a user somehow manages to mess up all of their templates, it is very difficult for them to recover without a reinstall, as at least one VM must be working for a reinstall to work.

### The solution you'd like

There should be an always-available disposable VM template for system recovery.  This VM should have enough in it for `qvm-template` in dom0 to work.  It could also be used for `default-mgmt-dvm`’s template.

### The value to a user, and who that user might be

All users will benefit from more recovery options.

**Comment by unman** [comment]
What template will the disposable template be using?
That cant be "messed up", or the disposable would be useless.
In that case, the user could just use the working template that they
have.

The only thing that might be useful if *all* the templates are messed up
would be a standalone. If *that* can be protected from user error why cant
the same be done for a template?

Why not have a template that was not accessible to the user except
in disaster recovery? (Have to be preloaded with network packages and
drivers, and even then may not fit all users.)

**Comment by marmarek** [comment]
I think storing yet another template is pretty wasteful for something that ideally would never be used at all... And if you do manage to break _all_ your templates at the same time (which is already pretty unlikely), and it's really an issue with all those templates (and not with dom0, in which case yet another template would not help), then you still have options:
 - you can rollback changes to some previous revision
 - you can take template rpm package from installation image

**Comment by DemiMarie** [comment]
@marmarek @unman: The rescue VM I am thinking of is not really a full template.  It is only has enough for networking and Salt, and might well have its root volume be a read-only squashfs.  Not sure if this is worthwhile, though.

**Comment by brendanhoar** [comment]
Fwiw...

My previous suggestion is that Qubes-installed templates should be fully immutable, non-runnable and hidden (from the perspective of Qubes tooling anyway). 

Then, a cow-or-similar clone of the fully immutable source is created by the system and used as the user-facing and user-updatable template for all appvms that depend on the template.

E.g. installer or dom0 qvm-tool -> installs fedora-36-ro(hidden) (e.g. from first run or remote repo) -> immediately clones to fedora-36 -> runs fedora-36 once to get applications list in dom0 -> installed. AppVMs are created from fedora-36.

Naming/tagging up to devs of course.

That prevents Qubes users (that use Qubes tooling only) from breaking the local ro copy and allows rollback of template to installed state without depending on external connectivity, with little additional storage cost.

[This may also provide a benefit of caching an unmodified version of the template locally for those who may want to reduce tracking of root filesystem fingerprints across appvm runs without forcing a full download of the template from a remote host.]

B
