### ISSUE TITLE
xserver-xorg-input-all is breaking sys-usb separation

### ISSUE THREAD

**Issue by TheWanderer1983** [QubesOS/qubes-issues#7682]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

xen_version            : 4.14.5
Linux 5.18.9-1.fc32.qubes.x86_64
  
**Installed Packages:**  
  
grub2-qubes-theme.x86_64                          	5.14.4-2.fc32 
kernel-latest-qubes-vm.x86_64                     	1000:5.18.9-1.fc32.qubes 
kernel-qubes-vm.x86_64                            	1000:5.15.52-1.fc32.qubes 
python3-qubesadmin.noarch                         	4.1.23-1.fc32 
python3-qubesdb.x86_64                            	4.1.13-1.fc32 
python3-qubesimgconverter.x86_64                  	4.1.16-1.fc32 
qubes-anaconda-addon.noarch                       	4.1.8-1.fc32 
qubes-artwork.noarch                              	4.1.12-1.fc32 
qubes-artwork-anaconda.noarch                     	4.1.12-1.fc32 
qubes-artwork-plymouth.noarch                     	4.1.12-1.fc32 
qubes-audio-daemon.x86_64                         	4.1.21-1.fc32 
qubes-audio-dom0.x86_64                           	4.1.21-1.fc32 
qubes-core-admin-addon-whonix.noarch              	4.1.1-1.fc32 
qubes-core-admin-client.noarch                    	4.1.23-1.fc32 
qubes-core-dom0.noarch                            	4.1.27-1.fc32 
qubes-core-dom0-linux.x86_64                      	4.1.23-1.fc32 
qubes-core-dom0-linux-kernel-install.x86_64       	4.1.23-1.fc32 
qubes-core-qrexec.x86_64                          	4.1.18-1.fc32 
qubes-core-qrexec-dom0.x86_64                     	4.1.18-1.fc32 
qubes-core-qrexec-libs.x86_64                     	4.1.18-1.fc32 
qubes-db.x86_64                                   	4.1.13-1.fc32 
qubes-db-dom0.x86_64                              	4.1.13-1.fc32 
qubes-db-libs.x86_64                              	4.1.13-1.fc32 
qubes-desktop-linux-common.noarch                 	4.1.12-1.fc32 
qubes-desktop-linux-manager.noarch                	4.1.14-1.fc32 
qubes-dom0-meta-packages.noarch                   	4.1.21-1.fc32 
qubes-gpg-split-dom0.x86_64                       	2.0.60-1.fc32 
qubes-gui-daemon.x86_64                           	4.1.21-1.fc32 
qubes-gui-dom0.x86_64                             	4.1.21-1.fc32 
qubes-img-converter-dom0.x86_64                   	1.2.11-1.fc32 
qubes-input-proxy.x86_64                          	1.0.26-1.fc32 
qubes-input-proxy-receiver.x86_64                 	1.0.26-1.fc32 
qubes-input-proxy-sender.x86_64                   	1.0.26-1.fc32 
qubes-libvchan-xen.x86_64                         	4.1.7-1.fc32 
qubes-manager.noarch                              	4.1.23-1.fc32 
qubes-menus.noarch                                	4.1.12-1.fc32 
qubes-mgmt-salt.noarch                            	4.1.14-1.fc32 
qubes-mgmt-salt-admin-tools.noarch                	4.1.14-1.fc32 
qubes-mgmt-salt-base.noarch                       	4.1.4-1.fc32 
qubes-mgmt-salt-base-config.noarch                	4.1.1-1.fc32 
qubes-mgmt-salt-base-topd.noarch                  	4.1.3-1.fc32 
qubes-mgmt-salt-config.noarch                     	4.1.14-1.fc32 
qubes-mgmt-salt-dom0.noarch                       	4.1.14-1.fc32 
qubes-mgmt-salt-dom0-qvm.noarch                   	4.1.4-1.fc32 
qubes-mgmt-salt-dom0-update.noarch                	4.1.9-1.fc32 
qubes-mgmt-salt-dom0-virtual-machines.noarch      	4.1.17-1.fc32 
qubes-pdf-converter-dom0.x86_64                   	2.1.12-1.fc32 
qubes-release.noarch                              	4.1-2.fc32 
qubes-release-notes.noarch                        	4.1-2.fc32 
qubes-repo-templates.noarch                       	4.1.2-1.fc32 
qubes-rpm-oxide.x86_64                            	0.2.5-1.fc32 
qubes-u2f-dom0.noarch                             	1.2.9-1.fc32 
qubes-usb-proxy-dom0.noarch                       	1.1.1-1.fc32 
qubes-utils.x86_64                                	4.1.16-1.fc32 
qubes-utils-libs.x86_64                           	4.1.16-1.fc32 
xfce4-settings-qubes.x86_64                       	4.0.5-2.fc32 

### Background
I'm using a Intel Nuc with latest Qubes 4.1.1. I have a USB keyboard and mouse setup in SYS-USB as per
["How to create a USB qube for use with a USB keyboard"](https://www.qubes-os.org/doc/usb-qubes/). 
I have A Yubikey 4 USB that I was struggling to get working with a debian-11-minimal template. It was working fine with the default debian-11 template. Here are [some](https://forum.qubes-os.org/t/solved-issue-getting-yubikey-working-on-deb-11-minimal-vms/13040) [forum](https://forum.qubes-os.org/t/missing-package-yubikey-usb-keyboard-not-proxied-to-minimal-template-qubes/10230) posts discussing the issue. 
I found that after installing `xserver-xorg-input-all`  Yubikey would provide a 2fa response in a web-browser.  However, it appears it's not a fix but a bug.

### Brief summary
Yubikey is able to provide a 2fa response to any of my AppVMs even when it isn't attached via sys-usb to a VM. Tested with three separate VMs, all worked. This appears only to happen if I have `xserver-xorg-input-all` installed. As you can see below it's not attached to anything. Also tested with the Debian-11 default template and it works here too. If i remove xserver-xorg-input-all  from the template and don't attached via SYS-USB it works as expected.

qvm-usb
```
BACKEND:DEVID                        Description                                                            USED BY
sys-usb:2-1.1                            USB_gaming_Keyboard_USB_gaming_Keyboard      
sys-usb:2-1.2                            SteelSeries_SteelSeries_Rival_3              
sys-usb:2-10                             8087_0026                                    
---->   sys-usb:2-3                              Yubico_Yubikey_4_OTP+U2F+CCID           
sys-usb:2-7                              VLI_Inc._USB_2.0_BILLBOARD_0000000000000001  
```

qvm-pci
```
dom0:00_00.0  Host bridge: Intel Corporation                                                                                                
dom0:00_02.0  VGA compatible controller: Intel Corporation Comet Lake UHD Graphics                                                          
dom0:00_08.0  System peripheral: Intel Corporation Xeon E3-1200 v5/v6 / E3-1500 v5 / 6th/7th/8th Gen Core Processor Gaussian Mixture Model  
dom0:00_12.0  Signal processing controller: Intel Corporation Comet Lake Thermal Subsytem                                                   
----->   dom0:00_14.0  USB controller: Intel Corporation Comet Lake PCH-LP USB 3.1 xHCI Host Controller   
                                           sys-usb (no-strict-reset=True)
dom0:00_14.2  RAM memory: Intel Corporation Comet Lake PCH-LP Shared SRAM                                                                   
dom0:00_14.3  Network controller: Intel Corporation Comet Lake PCH-LP CNVi WiFi                                                             sys-net
dom0:00_15.0  Unknown: Intel Corporation Serial IO I2C Host Controller                                                                      
dom0:00_15.2  Unknown: Intel Corporation Comet Lake PCH-LP LPSS: I2C Controller #2                                                          
dom0:00_16.0  Communication controller: Intel Corporation Comet Lake Management Engine Interface                                            
dom0:00_17.0  SATA controller: Intel Corporation Comet Lake SATA AHCI Controller                                                            
dom0:00_1c.0  PCI bridge: Intel Corporation Comet Lake PCI Express Root Port #5                                                             
dom0:00_1d.0  PCI bridge: Intel Corporation Comet Lake PCI Express Root Port #9                                                             
dom0:00_1d.5  PCI bridge: Intel Corporation                                                                                                 
dom0:00_1f.0  ISA bridge: Intel Corporation Comet Lake PCH-LP LPC Premium Controller/eSPI Controller                                        
dom0:00_1f.3  Audio device: Intel Corporation Comet Lake PCH-LP cAVS                                                                        
dom0:00_1f.4  SMBus: Intel Corporation Comet Lake PCH-LP SMBus Host Controller                                                              
dom0:00_1f.5  Unknown: Intel Corporation Comet Lake SPI (flash) Controller                                                                  
dom0:00_1f.6  Ethernet controller: Intel Corporation Ethernet Connection (10) I219-V                                                        sys-net (no-strict-reset=true, permissive=true)
dom0:01_00.0  PCI bridge: Intel Corporation JHL7540 Thunderbolt 3 Bridge [Titan Ridge 2C 2018]                                              
dom0:02_00.0  PCI bridge: Intel Corporation JHL7540 Thunderbolt 3 Bridge [Titan Ridge 2C 2018]                                              
dom0:02_01.0  PCI bridge: Intel Corporation JHL7540 Thunderbolt 3 Bridge [Titan Ridge 2C 2018]                                              
dom0:02_02.0  PCI bridge: Intel Corporation JHL7540 Thunderbolt 3 Bridge [Titan Ridge 2C 2018]                                              
dom0:03_00.0  System peripheral: Intel Corporation JHL7540 Thunderbolt 3 NHI [Titan Ridge 2C 2018]                                          
dom0:39_00.0  USB controller: Intel Corporation JHL7540 Thunderbolt 3 USB Controller [Titan Ridge 2C 2018]                                  sys-usb (no-strict-reset=True)
dom0:3a_00.0  Non-Volatile memory controller: Samsung Electronics Co Ltd NVMe SSD Controller SM981/PM981/PM983                              
dom0:3b_00.0  SD Host controller: Genesys Logic, Inc GL9755 SD Host Controller                                                              
                                                         

```

### Steps to reproduce
Debian-11-minimal template
1. Clone debian 11 minimal template 
2. Setup sys-usb
3. Open AppVM and attach USB devices, and test separation works
4. install xserver-xorg-input-all
5. detach all usb devices
6. Can still use Yubikey even in appVM when not attached

Debian-11 template
1. clone template
2. setup sys-usb
3. remove xserver-xorg-input-all 
4. plugin Yubikey and test separtion
5. Install xserver-xorg-input-all  
6. detach Yubikey from AppVM
7. test Yubkey

### Expected behavior

Not able to use Yubikey when not attached via sys-sub to a VM.

### Actual behavior

Can use yubikey when not attached to a Qube.

**Comment by marmarek** [comment]
yubikey present itself as a keyboard - I guess you allowed USB keyboard globally (https://www.qubes-os.org/doc/usb-qubes/#usb-keyboards). You can see what actually happened by looking at `journalctl` command in dom0 when you connect yubikey.

**Comment by TheWanderer1983** [comment]
You are right. It was that. 
journalctl
```
dom0 qrexec-policy-daemon[2496]: qrexec: qubes.InputKeyboard+: sys-usb -> @adminvm: allowed to dom0
dom0 kernel: input: sys-usb Yubico Yubikey 4 OTP+U2F+CCID as /devices/virtual/input/input24
```
Sorry about that. hmmm... this makes me think of badusb and I really should find another solution for my keyboard and mouse.
