### ISSUE TITLE
 Update Tool reports failure on Fedora minimal templates

### ISSUE THREAD

**Issue by unman** [QubesOS/qubes-issues#7690]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
4.1

### Brief summary
Updating Fedora-minimal templates results in reported failure.

### Steps to reproduce
Install fedora-minimal template
Update with Update Tool

### Expected behavior
Update will complete wih nice Green Tick

### Actual behavior
Update completes wih bad Red Cross

Packages are in fact updated, but the state "dnf-makecache" fails:
"could not create DNF metadata cache".

mgmtVM is Debian based.
dom0 updated with packages from testing.
I've had occasion to install both 35 and 36 minimal templates. Both fail on this state.
Full Fedora template reports succesful update.

**Comment by andrewdavidwong** [comment]
> "could not create DNF metadata cache"

I also see this intermittently. I usually just wait and try again later, then it eventually succeeds.
