### ISSUE TITLE
no audio output in debian-12 VMs

### ISSUE THREAD

**Issue by xaki23** [QubesOS/qubes-issues#7692]
### Qubes OS release

4.1

### Brief summary

debian-12 based VMs produce no audio output because the vchan-sink module is not loaded

### Steps to reproduce

* upgrade a debian-11 to debian-12/testing
* try to generate audio output
* silence
* pavucontrol doesnt show qubes vchan sink, just the dummy one

### Expected behavior

* working audio output

### Actual behavior

* no audio output

### root cause

* it seems debian added a +dfsg1 suffix to the pulseaudio packages in deb12
* this results in the vchan-sink module having the wrong path

### workaround

```
sudo ln -s /usr/lib/pulse-15.0/modules/module-vchan-sink.so /usr/lib/pulse-15.0+dfsg1/modules/
pactl load-module module-vchan-sink
```
==> working audio

### see also

may be related to https://github.com/QubesOS/qubes-issues/issues/7482

**Comment by BernhardOnline** [comment]
I upgraded a debian-11 to debian-12 and have no sound any more. The "workaround" (despite that we are in pulse-16.0 now) does no longer work....  

Any help in sight?

**Comment by xaki23** [comment]
my guess is this is unrelated to the original problem in this ticket.

the "we are in pulse-16.0 now" makes me suspect the pkg got uninstalled during the update. 
(because of an unraveling dependency chain)

try "apt-get install pulseaudio-qubes".

**Comment by BernhardOnline** [comment]
```
user@vm:~$ sudo aptitude update && sudo aptitude install pulseaudio-qubes
pulseaudio-qubes is already installed at the requested version (4.1.30-1+deb12u1)
pulseaudio-qubes is already installed at the requested version (4.1.30-1+deb12u1)
No packages will be installed, upgraded, or removed.
0 packages upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

```

seems up to date ... maybe a reinstall ?

**Comment by xaki23** [comment]
that is unexpected.

* what is the full version of the installed pulseaudio pkg?
* does "pactl list short modules" show module-vchan-sink?

**Comment by BernhardOnline** [comment]
Thanks for quick reply. Maybe I copy a bit too much now, but here we go

```
Package: pulseaudio                      
Version: 16.1+dfsg1-2+b1
State: installed
Automatically installed: yes
Multi-Arch: foreign
Priority: optional
Section: sound
Maintainer: Pulseaudio maintenance team <pkg-pulseaudio-devel@lists.alioth.debian.org>
Architecture: amd64
Uncompressed Size: 6,617 k
Depends: libasound2 (>= 1.2.1.1), libc6 (>= 2.34), libcap2 (>= 1:2.10), libdbus-1-3 (>= 1.9.14), libfftw3-single3 (>= 3.3.5), libgcc-s1 (>= 3.0), libglib2.0-0 (>=
         2.31.18), libgstreamer-plugins-base1.0-0 (>= 1.10.0), libgstreamer1.0-0 (>= 1.14.0), libice6 (>= 1:1.0.0), libltdl7 (>= 2.4.7), liborc-0.4-0 (>= 1:0.4.25),
         libpulse0 (= 16.1+dfsg1-2+b1), libsm6, libsndfile1 (>= 1.0.20), libsoxr0 (>= 0.1.1), libspeexdsp1 (>= 1.2.1), libstdc++6 (>= 11), libsystemd0, libtdb1 (>=
         1.2.7+git20101214), libudev1 (>= 183), libwebrtc-audio-processing1, libwrap0 (>= 7.6-4~), libx11-6 (>= 2:1.7.0), libx11-xcb1 (>= 2:1.8.1), libxcb1, libxtst6,
         adduser, lsb-base (>= 3.2-13), libasound2-plugins, pulseaudio-utils
PreDepends: init-system-helpers (>= 1.54~)

```


The second question has the following answer:


```
$ pactl list short modules
1	libpipewire-module-rt	{
            nice.level    = -11
            #rt.prio      = 88
            #rt.time.soft = -1
            #rt.time.hard = -1
        }	
2	libpipewire-module-protocol-native		
3	libpipewire-module-profiler		
5	libpipewire-module-metadata		
7	libpipewire-module-spa-device-factory		
9	libpipewire-module-spa-node-factory		
11	libpipewire-module-client-node		
13	libpipewire-module-client-device		
15	libpipewire-module-portal		
16	libpipewire-module-access	{
            # access.allowed to list an array of paths of allowed
            # apps.
            #access.allowed = [
            #    /usr/bin/pipewire-media-session
            #]

            # An array of rejected paths.
            #access.rejected = [ ]

            # An array of paths with restricted access.
            #access.restricted = [ ]

            # Anything not in the above lists gets assigned the
            # access.force permission.
            #access.force = flatpak
        }	
17	libpipewire-module-adapter		
19	libpipewire-module-link-factory		
21	libpipewire-module-session-manager		
536870912	module-always-sink	

```

Thank you, Bernhard

**Comment by BernhardOnline** [comment]
Maybe another useful one:

```
sudo pactl load-module module-vchan-sink
Connection failure: Connection refused
pa_context_connect() failed: Connection refused

```

**Comment by xaki23** [comment]
so you are running some kind of pulseaudio/pipewire hybrid?

here the module list looks like so:
```
user@debian-12:~$ pactl list short modules
0	module-device-restore		
1	module-stream-restore		
2	module-card-restore		
3	module-augment-properties		
4	module-vchan-sink		
5	module-udev-detect		
6	module-native-protocol-unix		
8	module-always-sink		
9	module-intended-roles		
10	module-suspend-on-idle		
11	module-systemd-login		
12	module-position-event-sounds		
13	module-role-cork		
14	module-filter-heuristics		
15	module-filter-apply		
16	module-x11-publish		
17	module-switch-on-port-available		
```

is your debian-12 a "fresh" install? (mine is an in-place-upgraded debian-11)
did audio ever work for that debian-12 template?
did you make any changes in a pipewire direction?

**Comment by BernhardOnline** [comment]
Well, to my best knowledge qubes-repos have no debian-12, yet:  forcefully, it is an in-place upgrade. Audio worked perfectly in debian-11, but never in debian-12.

**Comment by DemiMarie** [comment]
@BernhardOnline I suspect you are using `pipewire-pulse` instead of the real PulseAudio.  The Qubes PipeWire support package is only for R4.2, so you will need to uninstall `pipewire-pulse` on R4.1.

**Comment by xaki23** [comment]
also, debian-12 template has been "available" since april, but is still hiding in the -testing repository.
so this should work:
```
qvm-template --enablerepo qubes-templates-itl-testing install debian-12
```

**Comment by BernhardOnline** [comment]
So I uninstalled (in the VM, to test, not in the template) pipewire, and reinstalled pulseaudio. That did not bring sound back, yet.

So I looked again:  surprisingly,  after these 2 manipulations,   libpipewire-0.3-0  subsisted. I cannot remove it easily: Actually it is a dependency of mpv media player that I have installed in my debian-12-multimedia template. So that is odd. Is the only way to 
(1)  grab a list of packages for the debian-12-work and debian-12-multimedia templates
(2)  grab a clean debian-12
(3) clone it and reinstall both parts all required packages ?? 

 I would prefer to correct the problem in-place ...

**Comment by marmarek** [comment]
> So I uninstalled (in the VM, to test, not in the template) pipewire, and reinstalled pulseaudio.

I just tried, and installing `pulseaudio` seems to correctly remove pipewire-audio (and few other related packages) at the same time. After doing that in the template, and shutting down the template, you should have working audio in newly started app qubes.

**Comment by BernhardOnline** [comment]
Dear Marmarek, 

since the in-place-update  installed both,  (re)installing one would not remove the other. But I removed in the template pulsewire,  and reinstalled not only pulseaudio but also pulseaudio-qubes. That did it! Thank you!

As far as my problem is concerned, the issue can go to sleep, again.

**Comment by zaz** [comment]
I had the same issue.  This fixed it for me:

> try `apt-get install pulseaudio-qubes`
