### ISSUE TITLE
rc.local scripts sometimes fail if they depend on qrexec

### ISSUE THREAD

**Issue by gp397** [QubesOS/qubes-issues#7699]
### Qubes OS release
4.1 fully patched, example using Fedora 36 template

### Brief summary
In my /rw/config/rc.local script I use qrexec to attach a device and mount it.  This sometimes fails because qrexec fails to open a socket because the qrexec agent has not yet started.

### Steps to reproduce
Write an rc.local script that uses qrexec in some way.

Observe that qubes-misc-post.service sometimes fails with errors relating to qrexec failing to open the agent socket

### Expected behavior
rc.local scripts run successfully

### Actual behavior
qubes-misc-post.service fails.

### My Fix
Add "qubes-qrexec-agent.service" to the "After" list in /usr/lib/systemd/system/qubes-misc-post.service in the Template the AppVM is based on.

This works for me but happy to accept feedback and suggestions for a better solution.

**Comment by gp397** [comment]
$ cat /usr/lib/systemd/system/qubes-misc-post.service 
[Unit]
Description=Qubes misc post-boot actions
After=network-pre.target qubes-mount-dirs.service qubes-network.service qubes-firewall.service qubes-qrexec-agent.service

**Comment by DemiMarie** [comment]
You can use systemctl to express an ordering dependency.
