### ISSUE TITLE
qvm-block loopback device cannot be removed

### ISSUE THREAD

**Issue by logoerthiner1** [QubesOS/qubes-issues#7700]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

R4.1

### Brief summary

dom0 `sudo losetup -f --show /path/to/some/file` creates a term in `qvm-block`/`qvm-device`. `sudo losetup -d /dev/loopx` to cancel the device does not remove the device.

This is a bit of experimenting based on [this](https://www.qubes-os.org/doc/how-to-use-block-storage-devices/) only that source is dom0.

(I wonder which device is able to enter the `qvm-block` list or how can a device enter the list to be attachable to other appvm.)

### Steps to reproduce

1. dom0 `touch a; sudo losetup -f --show a` -> /home/username/a is available
2. dom0 `sudo losetup -d /dev/loopx` where x is the correct loopback number

### Expected behavior

The device is shown to be removed.

### Actual behavior

The device is still visible.

**Comment by 3hhh** [comment]
This is a dup of #7000.

**Comment by andrewdavidwong** [comment]
This appears to be a [duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If anyone believes this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.
