### ISSUE TITLE
Whonix uses deprecated /etc/qubes-rpc/policy file

### ISSUE THREAD

**Issue by unman** [QubesOS/qubes-issues#7706]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
4.1

### Brief summary
Turning on updates over Tor enables a file under /etc/qubes-rpc/policy in dom0

### Steps to reproduce
Turn on updates over Tor

### Expected behavior
File will be created/edited under /etc/qubes/policy

### Actual behavior
File will be created/edited in /etc/qubes/policy/qubes.UpdatesProxy
Although this works, and is supported under 4.1, since the defaults are
set in /etc/qubes/policy/90-default.policy, it makes sense to set *this*
policy in the new framework.

Reports in the forum of confusion about this.

**Comment by adrelanos** [comment]
Done.

No longer using `/etc/qubes/policy/qubes.UpdatesProxy` in Qubes R4.2.

new file location in dom0 in Qubes R4.2:
`/etc/qubes/policy.d/50-config-updates.policy`

related:
https://www.whonix.org/wiki/Qubes/UpdatesProxy

Can be closed.
