### ISSUE TITLE
Popup window from the same VM overlap with each other

### ISSUE THREAD

**Issue by iacore** [QubesOS/qubes-issues#7714]
### Qubes OS release
r4.1

### Brief summary
![scr](https://user-images.githubusercontent.com/74560659/186798448-3673b8b8-0995-402e-ac9b-fdf2496f87b9.png)

For any popup window that spawn popup window. The child window is always under the parent popup.

e.g.
```
A: "normal" window

A -> B -> C

C is shown under B
```

e.g. 2 (the case with IME)
```
root: the root X window

A -> B
root -> C

C is shown under B
```

### Steps to reproduce - A

- focus on a text input in any popup window from any web extension in Firefox
- type in rime-ibus

You will see the IME window shown below.

### Steps to reproduce - B

- click on search bar in Firefox (it should now have input focus)
- hover over it to show popup
- type in rime-ibus

### Expected behavior
I took a screenshot inside the VM, and it looked normal. Only when on dom0's side it's broken.

### Actual behavior

See summary

**Comment by andrewdavidwong** [comment]
I was under the impression that the term for these was "tooltip" rather than "pop-up."

**Comment by locriacyber** [comment]
I mean X windows that will disappear when you click on somewhere else, such "popup window".

And yes, the menu bar dropdown in GTK, and Extension Windows in Firefox suffer the same problem.
