### ISSUE TITLE
Qube Manager: Sorting by icon doesn't sort meaningfully

### ISSUE THREAD

**Issue by unman** [QubesOS/qubes-issues#7715]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
4.1 updated from testing repositories

### Brief summary
The Icon column appears to be sortable but only sorts by color.

### Steps to reproduce
Click on top of icon column

### Expected behavior
If the icons mean anything, (and it's opaque what the intended meaning is), then the rows should be sorted by that meaning.
Possibly the rows should be sorted by color and subsorted by meaning.

### Actual behavior
Rows are sorted only by color.

**Comment by GWeck** [comment]
Sorting first by meaning and then by color would also make sense.
