### ISSUE TITLE
Installation fails on new Lenovo P1 Gen5

### ISSUE THREAD

**Issue by hgoumner** [QubesOS/qubes-issues#7716]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

Qubes OS 4.1.1

### Brief summary

The installation fails in the beginning phases. I have attached screenshots of the messages. My drive is split up into multiple partitions because i want to use Fedora and Qubes as a dual boot option.

### Steps to reproduce

Write ISO file to USB, plug into new machine and boot.

### Expected behavior

Installation window opens und installation is successful.

### Actual behavior

GRUB menu appears, installation option is selected, terminal messages show up and the installation crashes in what looks like a tmux session, saying there is an error with X startup.

![PXL_20220828_075142064](https://user-images.githubusercontent.com/11947421/187064473-92fc198f-527a-4241-8d86-f6a130e3162b.jpg)
![PXL_20220828_075250680](https://user-images.githubusercontent.com/11947421/187064474-68a5ccb0-03cd-4cbe-b5d2-a5b3a7f473e5.jpg)
![PXL_20220828_075225352](https://user-images.githubusercontent.com/11947421/187064478-e15b47b8-d975-4a6b-befb-18de7e75a60f.jpg)
![PXL_20220828_075208868](https://user-images.githubusercontent.com/11947421/187064480-67791659-3cbc-4264-8254-acd4145075de.jpg)

**Comment by hgoumner** [comment]
Does anyone have any ideas? Fyi, i'm a paying "customer" as i donate money every month.

**Comment by andrewdavidwong** [comment]
> Does anyone have any ideas? Fyi, i'm a paying "customer" as i donate money every month.

As an open-source software project, we are grateful for your donation. However, please keep in mind that (1) [donors are not entitled to any special support](https://www.qubes-os.org/donate/#do-donors-get-personalized-support-or-special-feature-requests), and (2) the issue tracker (`qubes-issues`) is not intended to serve as a help desk or tech support center. Instead, we've set up other [venues where you can ask for help and support, ask questions, and have discussions](https://www.qubes-os.org/support/). (By contrast, the issue tracker is more of a technical tool intended to support our developers in their work.) Thank you for your understanding!
