### ISSUE TITLE
qubes builder cannot use sudo to build

### ISSUE THREAD

**Issue by ZYousef** [QubesOS/qubes-issues#7719]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### The problem you're addressing (if any)

qubes-builder [documentation ](https://www.qubes-os.org/doc/qubes-iso-building/)states that qubes-builder could be used on any rpm-based OS. However, using any OS other than qubes requires additional work.

Also, you may add a note to set SELINUX to **permissive | disabled** since it interferes with the build process. 

### The solution you'd like
The documentation should say that if you want to build on an alternative OS you should have some mechanism to use sudo, the builder won't allow you to continue if you give it a "sudo bash as stated"

The solution is to use a configuration similar to [passwordless-root](https://www.qubes-os.org/doc/vm-sudo/) on your system or alternatively modify the make file to continue with root access.

### The value to a user, and who that user might be
Developers could save time and enjoy coding.

**Comment by andrewdavidwong** [comment]
In case you (or any others reading this) are not already aware, the documentation is a community effort, and everyone is welcome to contribute. (That's how things like this get updated!) So, if you'd like to get involved with the project, this is a great way to do it. You can read more about how to submit documentation changes here:

https://www.qubes-os.org/doc/how-to-edit-the-documentation/

You may also be interested in the documentation style guide:

https://www.qubes-os.org/doc/documentation-style-guide/

**Comment by unman** [comment]
https://www.qubes-os.org/doc/qubes-builder/ does say:
```
One additional useful requirement is that `sudo root' must work without any prompt, which is default on most distros (e.g. `sudo bash' brings you the root shell without asking for any password). This is important as the builder needs to switch to root and then back to user several times during the build process.
```

**Comment by ZYousef** [comment]
@andrewdavidwong noted, thanks!

@unman 
**As I said earlier.** 
> the builder won't allow you to continue if you give it a "sudo bash as stated"

**Comment by unman** [comment]
> @unman 
> **As I said earlier.** 
> > the builder won't allow you to continue if you give it a "sudo bash as stated"
The "sudo bash" is an example - I dont know what you mean by "giving this"
to builder.
But if you find it unclear, please change it.

**Comment by unman** [comment]
As the documentation *already* says that passwordless sudo is required,
and OP hasn't proposed any amendment, I suggest this be closed.

**Comment by andrewdavidwong** [comment]
Closing as an "unsuitable proposal" (the proposed action is unsuitable, e.g., because it rests on a false assumption or misunderstanding, such as a proposed enhancement designed to fix something that is not really a problem in the first place). If anyone believes this is a mistake, please leave a comment, and we'll be happy to take another look. Thank you.
