### ISSUE TITLE
Global Settings for Update checks - unclear

### ISSUE THREAD

**Issue by unman** [QubesOS/qubes-issues#7729]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### The problem you're addressing (if any)
The "Updater checks" section in Qubes Global Settings is unclear.
Evidenced in the Forum by user qubist:
"I may have misunderstood the interface. In "Updater checks" section the checkboxes are unchecked. I assumed (obviously wrongly) that the "Disable All" button is equivalent to that but now I understand that clicking the button does something else."

### The solution you'd like
While the checkbox does refer to "as default for new qubes", the Buttons do not make it clear that they apply to *existing* qubes.
Simple solution to make this clear - change "individual" to "existing", or "current".

Why is there a checkbox *and* a button ? In what use case would you want to disable checks in current qubes while leaving a different default for new qubes?
Perhaps the buttons could be removed and the checkbox apply to both current *and* new qubes?

### The value to a user, and who that user might be
All users - clarity of intention.

**Comment by marmarta** [comment]
That was actually fixed by https://github.com/QubesOS/qubes-desktop-linux-manager/pull/133 (new update section in global config)
