### ISSUE TITLE
builderv2: N-of-M signatures validation

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#7739]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### The problem you're addressing (if any)

Currently qubes-builder accepts sources if they carry at least a single valid tag from a trusted key. There is no support for requiring several peoples signing a release.

### The solution you'd like

Add support for requiring N signed tags from different maintainers. This should be defined together with component maintainers. Lets focus on source code verification, do not add similar feature for github commands yet.

I don't exclude more complex schemes (3 tags from any of A,B,C,D,E or 2 tags if at least one is made by X), but lets start with a simpler option first. And it's possible to emulate more complex schemes with the simple one by some people having multiple keys (although that's a bit clumsy).

### The value to a user, and who that user might be

More trustworthy release process, with technically enforced review (or at least acknowledge) from multiple people.

**Comment by fepitre** [comment]
@marmarek Should we close this issue assuming we already done the main goal, i.e., supporting N signed tags from different maintainers?
