### ISSUE TITLE
builderv2: trigger ISO build via github comment

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#7740]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### The problem you're addressing (if any)

Currently building ISO requires manually calling a shell command

### The solution you'd like

Have a similar process to template build.

### The value to a user, and who that user might be

Even more simplified release process would allow more frequent point releases.

**Comment by fepitre** [comment]
I think this one is already done as we do weekly build of 4.2 ISO with this approach. I think we might open dedicated issue for specific additional feature related to ISO build with GitHub command.
