### ISSUE TITLE
[Feedback] Kernel Latest: glitches and artefacts in windowserver with Intel Graphics

### ISSUE THREAD

**Issue by b90g** [QubesOS/qubes-issues#7744]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

R4.1

Kernel-latest in dom0: 5.19.6

Tested with i7-8550U & i7-10710U same results.

### Brief summary

All displayed content glitches and shows artefacts over DomU and Dom0 interface (Panel and window content) after some time. 

### Steps to reproduce

Install kernel latest 5.19.6 in dom0, reboot and enjoy the show.

### Expected behavior

same stable behaviour as in  5.18.16 (previous kernel-latest)

### Actual behavior

All displayed content glitches and shows artefacts over DomU and Dom0 interface (Panel and window content) after some time. 
Often ends up in crashing the whole system (CTRL+SHIFT+F[1-6] didnt bring me to TTY), sometimes window server restarts and i can login in again.

---
(if a screen capture is desired let me know)

I dont expect this to be fixed, since its kernel latest, just put this here as feed back maybe some aditional tweaking is required for future kernels.

(Will close the issue once a newer kernel-latest is build and eventually reopen)

**Comment by andrewdavidwong** [comment]
We use the [updates-status](https://github.com/QubesOS/[updates-status](https://github.com/QubesOS/updates-status/issues)/issues) repo for this type of feedback. I've copied your post as a comment on https://github.com/QubesOS/updates-status/issues/3040.
