### ISSUE TITLE
Samba shares not syncing correctly sometimes

### ISSUE THREAD

**Issue by swamba** [QubesOS/qubes-issues#7746]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

4.1.1

### Brief summary
When using VM kernels after 5.12.14 (that is the latest kernel I could see that works correctly) then Samba shares don't work quite right.
It seems the timestamps on the file beeing worked on gets updated too early and the application (Netbeans being the application we see this mostly in) then sees that the file has been modified externally and pops up an error.

### Steps to reproduce
Create a normal Samba share on a Debian server (not sure if it needs to be a Debian server).
Mount it in a VM using kernel later then version 5.12.14. For example I could reproduce this issue using kernel-latest-qubes-vm-5.14.10 but not when using kernel-latest-qubes-vm-5.12.14. 
Open a file on the Samba share, I had most success with using Netbeans and just typing some text in the file.
After a while (perhaps 100 lines of text) then I could type in some text, press ctrl-s and up would pop an error saying the file had been modified externally.
I must underline that I have tried a lot of stuff, different versions of Netbeans, different parameters to cifs mount, different qubes, different templates but the only thing that seems to work is downgrading the kernel from 5.15 to 5.12.

### Expected behavior
The saving of files using applications like Netbeans succeeds without errors.

### Actual behavior
Sometimes there is an error while saving files, and this causes problems in Netbeans in regards to history (the history disappears) and where in the file the cursor is placed (the cursor sometimes jumps to the bottom of the file).

**Comment by DemiMarie** [comment]
This does not seem like a Qubes-specific problem.

**Comment by andrewdavidwong** [comment]
Closing as "not our bug" (the Qubes OS Project does not develop the software that is causing this bug). If anyone believes this resolution is a mistake, please leave a comment, and we'll be happy to take another look. Thank you.

Related FAQ: [Why don’t you fix upstream bugs that affect Qubes OS?](https://www.qubes-os.org/faq/#why-dont-you-fix-upstream-bugs-that-affect-qubes-os)

**Comment by swamba** [comment]
Umm, this is a kernel issue and this kernel is from Fedora 32 or 33 which is no longer supported by Fedora Project. Kernels that are not compiled from source are not eligible for support in upstream kernel. So where do I report this except here?

I did try out kernel 6.0 and 6.1 and that did fix a lot of the problem but not quite all. Our developers say they experience this bug once in a while but not quite as often as when on 5.15. But the 5.12 kernel never shows this problem.

I appreciate that you don't fix upstream bugs but if you could forward this bug to the right place that would be fantastic :-)

**Comment by marmarek** [comment]
Qubes does not use kernel packages from Fedora by default, but build own package, which is pretty close to vanilla upstream release (we have currently [8 minor patches](https://github.com/QubesOS/qubes-linux-kernel/), compared to 100+ in Fedora for example). So, I think upstream kernel is correct place to report this issue. Maybe folks from Samba (https://www.samba.org/samba/support/) can help?
