### ISSUE TITLE
Create GUI for changing encryption password

### ISSUE THREAD

**Issue by marmarta** [QubesOS/qubes-issues#7748]
### The problem you're addressing (if any)

There is no GUI way to change disk encryption password.

### The solution you'd like

Add it to new Global Settings.

### The value to a user, and who that user might be

People who prefer GUI tools (27% of our users, based on Survey) or like to use GUI tools not just CLI (65% of users).

**Comment by DemiMarie** [comment]
> It would be great if this separately allowed deleting password slots, so multiple disk decryption passwords can exist at once. I usually keep my old password for a few weeks until I am sure the new password has been fully burned into my memory. I am probably not the only one.

Sadly this is not reliable on SSDs due to wear leveling.

**Comment by marmarek** [comment]
> Sadly this is not reliable on SSDs due to wear leveling.

Great majority of users (like, 99.9999% of them) don't need to be concerned about it (due to complexity of finding and extracting such data, and also due to a chance for it to be overridden by something else later). But if you are, you probably should wipe the whole disk when you change the passphrase even in the same slot.

In other words: this concern is out of scope for this tool.

**Comment by DemiMarie** [comment]
> > Sadly this is not reliable on SSDs due to wear leveling.
> 
> Great majority of users (like, 99.9999% of them) don't need to be concerned about it (due to complexity of finding and extracting such data, and also due to a chance for it to be overridden by something else later). But if you are, you probably should wipe the whole disk when you change the passphrase even in the same slot.
> 
> In other words: this concern is out of scope for this tool.

This is valid.  We might be able to use the TPM to avoid it, but that can come later.

**Comment by jamke** [comment]
Just a note - this feature is very well desired for other distros too. 

I mean, maybe it's not a Qubes OS's task, because even in Kubuntu, that positions itself as user-friendly, people had to change and manage LVM passwords using terminal without GUI.

**Comment by marmarek** [comment]
https://github.com/QubesOS/qubes-disk-password-gui
It's very simple, but should be generic enough to use also outside of Qubes OS.
