### ISSUE TITLE
Archlinux template lacks upgrades-status-notify and upgrades-installed-check

### ISSUE THREAD

**Issue by Szewcson** [QubesOS/qubes-issues#7753]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
4.1

### Brief summary
After updating arch tempalte using qubes updater there is an error 
```
stderr:
                /bin/bash: line 1: /usr/lib/qubes/upgrades-status-notify: No such file or directory
```
and in fact the file is missing

### Steps to reproduce
1.) Build and install arch template
2.) Perform update on it using qubes updater

### Expected behavior
There will be confirmation on success update

### Actual behavior
There is always an error due to lacking scripts.

**Comment by lubellier** [comment]
### Analysis

The ArchLinux [qubes-core-agent-linux](https://github.com/QubesOS/qubes-core-agent-linux) packages don't include these files

```
[user@tpl-archlinux-41 ~]$ ls -l /usr/lib/qubes/updates-*
ls: cannot access '/usr/lib/qubes/updates-*': No such file or directory
```

whereas the debian/fedora/gentoo packages include it:

```
user@tpl-d11:~$ dpkg -S /usr/lib/qubes/upgrades-installed-check 
qubes-core-agent: /usr/lib/qubes/upgrades-installed-check

user@tpl-f36:~$ rpm -qf /usr/lib/qubes/upgrades-installed-check 
qubes-core-agent-4.1.37-1.fc36.x86_64

tpl-g-min ~ # equery b /usr/lib/qubes/upgrades-installed-check 
app-emulation/qubes-core-agent-linux-4.2.0
```

### What to do?

So the idea is to fix the ArchLinux package recipe to include the `upgrades-installed-check` and `upgrades-installed-check` files, in [PKGBUILD](https://github.com/QubesOS/qubes-core-agent-linux/blob/master/archlinux/PKGBUILD) from qubes-core-agent-linux. 

If a PKGBUILD fluent user read this, PR are welcome.

**Comment by techge** [comment]
Just found this issue again, this was fixed by https://github.com/QubesOS/qubes-core-agent-linux/pull/391 thus, this issue can be closed

**Comment by lubellier** [comment]
The @techge 's PR merged on the [core-agent-linux-4.1.39](https://github.com/QubesOS/qubes-core-agent-linux/commits/release4.1) **BUT** the last version in the ArchLinux Qubes-OS repository is only the [core-agent-linux-4.1.37](https://archlinux.qubes-os.org/r4.1/current/vm/archlinux/pkgs/).

**Comment by unman** [comment]
On Sun, Apr 09, 2023 at 03:59:48AM -0700, Ludovic Bellier wrote:
> The @techge 's PR merged on the [core-agent-linux-4.1.39](https://github.com/QubesOS/qubes-core-agent-linux/commits/release4.1) **BUT** the last version in the ArchLinux Qubes-OS repository is only the [core-agent-linux-4.1.37](https://archlinux.qubes-os.org/r4.1/current/vm/archlinux/pkgs/).
> 
Ah, and I have 4.1.38, and template built on 20230130, which (I think)
missed this by a day.

**Comment by techge** [comment]
I see. I am using this version for a while by installing it manually, did not know it is still not in the repo

**Comment by lubellier** [comment]
@fepitre I request an ArchLinux CD build for qubes-core-agent-linux-**4.1.40**, first for current-testing.
Current is only 4.1.37, see [bot status](https://ftp.qubes-os.org/~qubesos2-bot/status.html) and above comments.
Thank.

**Comment by marmarek** [comment]
Archlinux builder brought back to life, it should pickup pending packages shortly.

**Comment by lubellier** [comment]
In the builder process, pacman failed to join the mirror.rackspace.com Archlinux repository:

https://github.com/QubesOS/build-logs-secondary/blob/7698c145cc3bce2cd845f64dd0777273f93d12f8/build-archlinux/log_2023-04-14_22-03-16#L1987

I suggest to follow the below [ArchLinux advice](https://wiki.archlinux.org/title/Mirrors#Enabling_a_specific_mirror): 

> Tip: Uncomment 5 favorite mirrors and place them at the top of the mirrorlist file. That way it is easy to find them and move them around if the first mirror on the list has problems. It also makes merging mirrorlist updates easier.

**Comment by lubellier** [comment]
Now this is a closable issue. 
Reasons: PR merged, package published in the stable repository and the missed file is now available:

```
[user@tpl-archlinux-41 ~]$ pacman -Qo /usr/lib/qubes/upgrades-status-notify 
/usr/lib/qubes/upgrades-status-notify is owned by qubes-vm-core 4.1.41-16
```
