### ISSUE TITLE
builderv2: optionally download additional packages in init-cache stage

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#7763]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### The problem you're addressing (if any)

mock/pbuilder is called in a disposable environment (DispVM, container). Normally it caches downloaded packages, for future builds, but in our use cases, extra build dependencies are re-downloaded each time.

### The solution you'd like

Add a (per-dist) configurable list of additional packages to download, that will populate mock/pbuilder cache at the build stage. 

Rationale why this way: the cache cannot be preserved after "normal" build, because that would break isolation between components. But we can manually provide a list of packages extracted from spec files or build logs. This won't cover all the packages (some may be updated in the meantime, some dependencies may change), but should cover most of them.

Ideally, packages should be downloaded including all relevant dependencies (like `dnf download --resolve` does), to avoid the need to list transient dependencies too. But if that isn't easy, we can list all packages too.

### The value to a user, and who that user might be

Faster builds, save network traffic.

### Current implementation status:

- [x] ArchLinux (https://github.com/QubesOS/qubes-builderv2/pull/38)
- [x] Fedora
- [x] Debian

**Comment by fepitre** [comment]
Here is how the implementation looks like: https://github.com/QubesOS/qubes-builderv2/blob/main/example-configs/archlinux.yml#L21

**Comment by fepitre** [comment]
@marmarek This is now complete without this `dnf download --resolve` approach. Would you like to open a separate ticket or we assume we will start like this for now?
