### ISSUE TITLE
`sys-net` hangs at boot

### ISSUE THREAD

**Issue by 3hhh** [QubesOS/qubes-issues#7769]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

4.1
VM kernel: 5.15.63.1
dom0 kernel: 5.10.136-1
dom0 Xen: 4.14.5

### Brief summary
During VM startup, `sys-net` often seems to hang with kernel 5.15.63.1. This hasn't happened with older dom0 & VM kernels.

Hanging means that GUI is not started / NetworkManager shows a blank white tray icon. `qvm-run` never returns.

`qvm-console-dispvm` shows the following interesting "last lines":
```
wls7: associated
backend has not mapped grant: 4208
xvda disabled for further use
vif vif-5-0 vif5.0: Guest Rx ready
sys-net login:
```
(Logging in doesn't work / hangs after the user name.)

`sys-net` cannot be shut down / needs to be killed.

This only happens when `sys-net` is started right at boot.

### Steps to reproduce

Boot.

### Expected behavior

`sys-net` starts as usual.

### Actual behavior

`sys-net` hangs.

**Comment by asharp** [comment]
I think i've also seen this bug on two boxes now - qubes can still boot vms, including sys-net with no devices passed through, but when you add the pcie passthrough back the boot hangs. Changing 'strict reset' doesn't change things, and changing from disposable to not disposable sys-net doesn't change things. At the moment kernel 5.18-9 doesn't seem to have this bug, but 5.18-16 does. This is using xen 4.14.5 and intel.

**Comment by 3hhh** [comment]
VM kernel 5.15.64-1 currently didn't expose this behaviour yet.
