### ISSUE TITLE
Exception rendering Salt states results in a zero exit code

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#7772]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

R4.1

### Brief summary

If an exception occurs while rendering a Salt state, qubesctl returns a zero exit code.

### Steps to reproduce

Create a Salt state that fails to render for some reason.

### Expected behavior

Non-zero exit code from qubesctl

### Actual behavior

Zero exit code

**Comment by lkubb** [comment]
Pretty sure this is caused by salt-ssh exiting with 0 in that case as well, as mentioned in https://github.com/QubesOS/qubes-issues/issues/7993 and https://github.com/saltstack/salt/issues/64514. That issue will be fixed upstream in `3006.2`.
