### ISSUE TITLE
Using the name of a nonexistent qube produces a usage error

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#7773]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

R4.1

### Brief summary

If the name of a nonexisting qube is used in a command that uses the Qubes argument parser, a spurious usage error is produced in addition to the actual error about the qube not existing.

### Steps to reproduce

See above.

**Comment by marmarta** [comment]
Could you give some examples of those commands? I tried a qubes-vm-settings and got a reasonable error:
```
usage: qubes-vm-settings [--verbose] [--quiet] [--help] [--tab TAB] VMNAME
qubes-vm-settings: error: no such domain: 'adfdsfs'
```

**Comment by marmarta** [comment]
I mean, I find the usage line helpful, because the error might come from user making an error in qube name, or from user e.g. omitting the -- before an option.
