### ISSUE TITLE
Can't open file Manager from "Qubes Domains" after installing VSCode

### ISSUE THREAD

**Issue by Che15ea** [QubesOS/qubes-issues#7786]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
4.10.1 Latest

### Brief summary
I found that when I click"file manager" of a Qube with VSCode being installed from "Qubes Domains" at the top right corner, VSCode pops up.

### Steps to reproduce
You can replicate the issue by installing VSCode in a debian-11 Standalone Qube and open file manager from the blue Cube icon on the top right corner.

### Expected behavior
File Manager starts

### Actual behavior
VSCode starts

**Comment by Minimalist73** [comment]
This is not a Qubes issue. I got this too and here's how to fix it:
- Edit/Create file `~/.config/mimeapps.list`
- It should contain something like this:
  ```
  [Added Associations]
  application/x-shellscript=org.gnome.gedit.desktop;
  text/plain=org.gnome.gedit.desktop;
  inode/directory=org.gnome.Nautilus.desktop;
  ```
- Open file manager and check

**Comment by andrewdavidwong** [comment]
Closing as "not our bug" (the Qubes OS Project does not develop the software that is causing this bug). If anyone believes this resolution is a mistake, please leave a comment, and we'll be happy to take another look. Thank you.

Related FAQ: [Why don’t you fix upstream bugs that affect Qubes OS?](https://www.qubes-os.org/faq/#why-dont-you-fix-upstream-bugs-that-affect-qubes-os)
