### ISSUE TITLE
Sys-usb heating the CPU until a console is run

### ISSUE THREAD

**Issue by euidzero** [QubesOS/qubes-issues#7788]
### Qubes OS release
This behavior exists since 3.2 and is present in 4.1.1

### Brief summary
Sometimes, usually after resume from suspend, sys-usb starts to make the CPU overheating (fan at max, CPU temp stays at 70°C)

Simply opening a terminal in sys-usb stops the issue preventing the identification of the process responsible for the CPU usage.
Note : Using Lenovo X1 carbon gen5

**Comment by asharp** [comment]
By 'opening a terminal' do you mean via qvm-run or via qubes manager? Qubes manager's 'open console in qube' opens the serial console of a qube, which should disturb the qube less.

**Comment by logoerthiner1** [comment]
I have also observed similar issue in the past. This issue will occur around every 2 weeks on average when normally using the computer (approximately) and is hard to spot as the cpu usage goes down after the xterm/xfce4-terminal pops out. I have once luckily spotted the culprit but I did not record it, it seems to be a kworker or something.

You may try `qvm-run --pass-io sys-usb ps -ef` when the issue happens again to see whether you find a suspicious process taking much cpu.

**Comment by euidzero** [comment]
Just found 2 processes with 1.9% CPU. Everything else with zero CPU usage.


Le sam. 24 sept. 2022 à 11:52, logoerthiner1 ***@***.***> a
écrit :
