### ISSUE TITLE
Failure reading storage configuration in VmWare

### ISSUE THREAD

**Issue by holema** [QubesOS/qubes-issues#7789]
### Qubes OS release

Qubes release 4.1.1

### Brief summary

I want to install Qubes OS in my VMWare Workstation 16. The Host is a Win10
I activate all necessary extension in the CPU settings.
The installation is starting, but when I`m on the step to start the installation I always get this error:
![image](https://user-images.githubusercontent.com/22790152/191935354-65c80b48-db1b-4075-81dd-76e12664493c.png)

### Steps to reproduce
I use:
VMware® Workstation 16 Pro
16.2.4 build-20089737

### Expected behavior

Installation completed

### Actual behavior

![image](https://user-images.githubusercontent.com/22790152/191935354-65c80b48-db1b-4075-81dd-76e12664493c.png)
Getting this error

**Comment by fepitre** [comment]
This is not suitable for Qubes OS issues tracker. Please use the forum instead: https://forum.qubes-os.org/.
