### ISSUE TITLE
Cannot boot Qubes after successful installation

### ISSUE THREAD

**Issue by NoneHead** [QubesOS/qubes-issues#7790]
I’m having trouble running Qubes 4.1.1 at my computer. Validity of the ISO is confirmed as asked in documentation.

**THE SETUP**
Intel Core i9-10900K
MSI MPG Z490 GAMING EDGE WIFI
Corsair MP400 2TB

**THE PROCEDURE**
1, Reset BIOS to default values
2, Disabled Secure Boot
3, Enabled Intel VT-D Tech
4, Set SATA Mode to AHCI Mode
5, Installed Qubes using ‘Test media and install Qubes OS R4.1.1’

Installation ends with saying the operation was successful and I’m ready to use Qubes.
Getting this after clicking Reboot button:
![image](https://user-images.githubusercontent.com/114309523/192113132-7ec24138-77b5-4a67-b4c7-b5a1bab6936c.png)
When I power off the computer and remove the USB stick I boot into UEFI.

**TROUBLESHOOTING PASSED**

### Boot device not recognized after installing
Tried to execute command:
`p -r /boot/efi/EFI/qubes/. /boot/efi/EFI/BOOT`
Output:
`cp: cannot stat '/boot/efi/EFI/qubes/.': No such file or directory`
`cd boot`
`ls`
Output:
`initramfs-5.15.52-1.fc32.qubes.x86_64.img`
There is no `efi` folder in the `boot` folder. Installation error?

### Accessing installer Rescue mode on UEFI
`pkill -9 anaconda`
`anaconda --rescue`
`1`
`{PASSPHRASE}`
Output:
`You don't have any Linux partitions. Rebooting.`
`Please press ENTER to get a shell:`
`fdisk -l`
Output:
![image](https://user-images.githubusercontent.com/114309523/192113338-b9a734d0-1e81-48f3-9a86-c1ee59b88040.png)
How can I have no Linux partitions as Qubes just installed?

**Comment by andrewdavidwong** [comment]
Please note that the issue tracker (`qubes-issues`) is not intended to serve as a help desk or tech support center. Instead, we've set up other [venues where you can ask for help and support, ask questions, and have discussions](https://www.qubes-os.org/support/). (By contrast, the issue tracker is more of a technical tool intended to support our developers in their work.) Thank you for your understanding!
