### ISSUE TITLE
Cursor out of sync for many HVMs

### ISSUE THREAD

**Issue by Szewcson** [QubesOS/qubes-issues#7791]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
4.1.1

### Brief summary
Don't know if it isn't duplicate since this bug is rather old but I can't find the open issue for it. For many HVMs (Plan9, TempleOS, Redox... but sometimes also modern traditional OSes like Ubuntu or Windows) cursor is out of sync - You can see two cursor: one native qubes and one from the HVM and they are in the other places on HVM window. When you moving mouse the distance between them sometimes seems to be random - not the constant distance.

### Steps to reproduce

Start one of the less typical OSes that I mentioned as HVM for them it is 100% probability that this bug appears.

### Expected behavior
Cursors are in sync.

### Actual behavior
There is a shift between qubes native cursor and HVM cursor.

**Comment by Szewcson** [comment]
For some OSes it is only an issue when full "desktop" is larger then the window in Qubes. In that case changing resolution is an workaround. But for some OSes like plan9 the problem persist at any resolution.

**Comment by DemiMarie** [comment]
Is the distance actually random, or is it dependent on where the cursor is on the screen?  In OpenBSD it is the latter.

**Comment by Szewcson** [comment]
Yes, it is depentent on how far it is from right botom corner.

**Comment by Szewcson** [comment]
Yes, it is depentent on how far it is from right botom corner. In OpenBSD changing resolution is a workaround, on Plan9 it not work as it should for any resolution. Stranger is that that for 9front it works good from the beginning.

**Comment by Szewcson** [comment]
I'm doubt if it only affects 3.1 and earlier. I will check that today on 4.2.

**Comment by Szewcson** [comment]
Just booted Redox under 4.2 - problem still appears.
