### ISSUE TITLE
Consider `xenpm set-scaling-governor powersave` before suspension in order to improve suspension stability on thinkpad

### ISSUE THREAD

**Issue by logoerthiner1** [QubesOS/qubes-issues#7794]
### The problem you're addressing (if any)

Qubes OS on some thinkpad have unstable suspension - it works but occasionally fails: #7340 .

I suspect that the problem can be related to the cpu scaling governor being `ondemand`, since there may and has been problems when S3 sleep meets an on-going frequency scaling. See https://www.thinkwiki.org/wiki/Problems_with_ACPI_suspend-to-ram .

I suspect that the problem can be solved when `xenpm set-scaling-governor powersave` is executed before suspension. I hope anyone can try it out to see whether this helps.

### The solution you'd like

Add the line `xenpm set-scaling-governor powersave` or anything similar to the pre-suspension script, and add some recovering code in post-suspension script, or edit xen S3 sleep code equivalently.

### The value to a user, and who that user might be

User who suffers from unstable suspension can have a more stable suspension and does not need to hard reset Qubes OS frequently on suspension.

**Comment by 100111001** [comment]
That's the result if I execute `xenpm set-scaling-governor powersave`
on a intel i7-1165G7

```
[CPU1] failed to set governor name (22 - Invalid argument)
[CPU3] failed to set governor name (22 - Invalid argument)
[CPU5] failed to set governor name (22 - Invalid argument)
[CPU7] failed to set governor name (22 - Invalid argument)
[CPU8] failed to set governor name (22 - Invalid argument)
[CPU9] failed to set governor name (22 - Invalid argument)
[CPU10] failed to set governor name (22 - Invalid argument)
[CPU11] failed to set governor name (22 - Invalid argument)
[CPU12] failed to set governor name (22 - Invalid argument)
[CPU13] failed to set governor name (22 - Invalid argument)
[CPU14] failed to set governor name (22 - Invalid argument)
[CPU15] failed to set governor name (22 - Invalid argument)
```

**Comment by DemiMarie** [comment]
How many CPU cores do you have @100111001?  How many hyperthreads per core?

**Comment by 100111001** [comment]
@DemiMarie: According to the intel specs (i7-1165G7):
cores: 4
threads: 8

**Comment by logoerthiner1** [comment]
This proposal gets invalid as the root cause of #7340 is found out. Closed
