### ISSUE TITLE
gentoo template: remove the deprecated xorg-x11 dependency

### ISSUE THREAD

**Issue by lubellier** [QubesOS/qubes-issues#7804]
### Qubes OS release
4.1.1

### Brief summary
Gentoo deprecates the [xorg-x11](https://packages.gentoo.org/packages/x11-base/xorg-x11) package but gubes-gui-agent depends on it.

### Steps to reproduce
Update the gentoo template : 

```
These are the packages that would be merged, in reverse order:

Calculating dependencies... done!

Total: 0 packages, Size of downloads: 0 KiB

!!! The following installed packages are masked:
- x11-base/xorg-x11-7.4-r3::gentoo (masked by: package.mask)
/var/db/repos/gentoo/profiles/package.mask:
# Matt Turner <mattst88@gentoo.org> (2022-10-01)
# Metapackage that has outlived its purpose. Made some sense in the immediate
# aftermath of X.Org modularization 15 years ago.
# Removal on 2022-11-01. Bugs #755233, #872119.

For more information, see the MASKED PACKAGES section in the emerge
man page or refer to the Gentoo Handbook.


Nothing to merge; quitting.

tpl-g-min ~ # equery d x11-base/xorg-x11
 * These packages depend on x11-base/xorg-x11:
app-emulation/qubes-gui-agent-4.1.26 (x11-base/xorg-x11)
tpl-g-min ~ # 
```

### Expected behavior
No more dependency warning 

### Actual behavior
Dependency above warning. But after the 2022-11-01 removal, it will be an error.

**Comment by lubellier** [comment]
### Analysis
The old xorg-x11 meta package mainly pulls the bitmap fonts, two ways:
- if qubes-gui-agent really depends on the bitmap fonts or other packages from the meta package, then replace the xorg-x11 dependency by the wanted packages
- else just remove this dependency

Gentoo resources : 
- the [related thread in the Gentoo forum](https://forums.gentoo.org/viewtopic-t-1157659-highlight-xorgx11.html) 
- the [Xorg wiki entry](https://wiki.gentoo.org/wiki/Xorg).

**Comment by fepitre** [comment]
Would it be possible to force use it or I would need to add it somehow? We are switching to Wayland but this is something I've not followed completely on when we are going to integrate it. @marmarek?

**Comment by lubellier** [comment]
> Would it be possible to force use it 

A basic workaround:
```
# cat /etc/portage/portage.unmask/xorg-x11.unmask
x11-base/xorg-x11
# 
```

> I would need to add it somehow? 

See which packages are required for `app-emulation/qubes-gui-agent` and replace the `x11-base/xorg-x11` dependency with the identified packages.

> We are switching to Wayland but this is something I've not followed completely on when we are going to integrate it. @marmarek?

Maybe a misunderstood sentence in my report? Gentoo doesn't remove Xorg, only the `x11-base/xorg-x11` meta-package... So migrating to Wayland is a future but not an immediate requirement.

**Comment by lubellier** [comment]
>  >     I would need to add it somehow?
>  See which packages are required for app-emulation/qubes-gui-agent and replace the x11-base/xorg-x11 dependency with the identified packages.


I found these packages : 

- `x11-apps/xprop` for `/usr/bin/xprop` used in `/etc/X11/xinit/xinitrc.d/50guivm-windows-prefix.sh`
- `x11-apps/xsetroot` for `/usr/bin/xsetroot` used in `/usr/bin/qubes-session`
- `x11-apps/xrandr` for `/usr/bin/xrandr` used in `/usr/bin/qubes-set-monitor-layout`
- `x11-apps/setxkbmap` for `/usr/bin/setxkbmap` used in `/usr/lib/qubes/qubes-keymap.sh`

So in https://github.com/fepitre/qubes-gentoo/blob/master/app-emulation/qubes-gui-agent/.qubes-gui-agent.ebuild.0 I suggest to replace the L28:

```
        x11-base/xorg-x11
```

by

```
        x11-apps/xprop
        x11-apps/xsetroot
        x11-apps/xrandr
        x11-apps/setxkbmap
```

**Comment by fepitre** [comment]
@lubellier shoud be now fixed.
