### ISSUE TITLE
builderv2: repository publish/unpublish should call upload too

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#7808]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### The problem you're addressing (if any)

`qb repository publish` (and `unpublish`) only modify local copy of the repository. Then, it needs to be uploaded with a `qb package upload` call separately.

### The solution you'd like

There should be a way for upload to happen automatically. Either by default, or with some option.

### The value to a user, and who that user might be

Easier usage of builderv2.

**Comment by fepitre** [comment]
What about `automatic-upload-on-publish`?

**Comment by marmarek** [comment]
On Wed, Oct 26, 2022 at 08:07:49AM -0700, Frédéric Pierret wrote:
> What about `automatic-upload-on-publish`?

Yes, makes sense. And then maybe remove `package upload` from `package all` (as publish would upload already).

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
