### ISSUE TITLE
"Verify Backup" function should actually verify the backups

### ISSUE THREAD

**Issue by ddevz** [QubesOS/qubes-issues#7809]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
4.1

### Brief summary
The "Verify Backup" function will tell people that all qubes were successfully backed up when some qubes were not successfully backed up.

Note: I do not understand what "Verify Backup" actually does if it's not comparing the hash of each qube in a backup file against hashes that were written at the time of the backup.  (maybe it's computing the hash of qubes it can find the recorded hash for, and for qubes that it cant find a hash for it just "skips" those?  (note that it knows enough about those qubes without hashes to display them to the screen to say that they backed up fine)

Note: I'm breaking this out as a separate issue. It was originally part of https://github.com/QubesOS/qubes-issues/issues/7567 under the "New Even Larger Concern:" area )

### Steps to reproduce
1. Rig your system to create a error during the backup.  (Example: damage a sector of the media where the image that is going to be backed up resides so that it will generate a read error when it tries to be read (like happened in https://github.com/QubesOS/qubes-issues/issues/7567))
2. Run the backup program and select several qubes, with the qube that will cause the error in the middle of the list
3. Run the backup and let it hit the error (probably causing it to hang)
4. Reboot system to make sure the backup is not still running
5. Run the "restore backup" program, and do a verify

(untested alternative:  you might be able to just remove the end of a successful backup, or do a kill -9 to the backup process as it's backing up to accomplish the same thing?)

### Expected behavior
I expect the verify to say that several of the qubes were not backed up successfully

### Actual behavior
Verify says that *all* qubes backed up fine

**Comment by andrewdavidwong** [comment]
This appears to be a [duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) of #3498 and/or #6386. If so, please comment on the appropriate existing issue instead. If anyone believes this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.
