### ISSUE TITLE
R4.0.4 installer problem on new laptop

### ISSUE THREAD

**Issue by patranger** [QubesOS/qubes-issues#7811]
### Qubes OS release
R4.0.4

### Brief summary
A few days ago I bought a new laptop and wanted to install Qubes OS 4.1 on it, but due to the error described in this thread:
https://github.com/QubesOS/qubes-issues/issues/7433

I couldn't do that. The same situation was for version 4.1-rc4 rc-3 etc. until I got to version 4.0.4 and knowing the problems of this version when installing with UEFI (my laptop already has only UEFI) I followed the guide
https://www.qubes-os.org/doc/uefi-troubleshooting/

I tried this solution:
```
# noexitboot = 1
# mapbs = 1
```

and (options = console = none)
```
[qubes-verbose]
options = console = none efi = attr = uc
# noexitboot = 1
# mapbs = 1
kernel = vmlinuz inst.stage2 = hd: LABEL = Qubes-R4.0-x86_64 i915.alpha_support = 1
ramdisk = initrd.img
```

but unfortunately the effect is the same each time.

Nothing happens when booting from a pendrive. It doesn't even have a menu, there's nothing. Just as if the system didn't exist but it exists when I mount it to Garuda and check it.
I burned it with this:
`sudo dd if = Qubes-RX-x86_64.iso of = / dev / sdY status = progress bs = 1048576 conv = fsync`

Asus ROG Strix G15 (2022)
AMD Ryzen™ 9 6900HX
NVIDIA® GeForce RTX™ 3070
DDR5-4800
NVM

### Expected behavior
Hassle-free installation

**Comment by andrewdavidwong** [comment]
Qubes 4.0 has reached end-of-life and is no longer supported, so we are no longer accepting new issues for that release.

I see that you mentioned that there is already a separate open issue that covers your problem with Qubes 4.1, so I will close this issue.
