### ISSUE TITLE
Adding a lighting program to a basic installation

### ISSUE THREAD

**Issue by patranger** [QubesOS/qubes-issues#7812]
### The problem you're addressing (if any)
The problem of the lack of control over the lighting and the flexible change of the color temperature in the automatic night mode.
On PC, sys-usb is not used, hence the lighting control must be with Dom0, while in laptops sys-usb there is no access to the integrated keyboard control.

### The solution you'd like
I suggest that the Qubes OS system from the first run should has software such as OpenRGB (or better) and Redshift (or better)

### The value to a user, and who that user might be
1. The problem is aimed at everyone who has RGB keyboards / mouse on USB or who have built-in RGB keyboards in laptops.
2. People who frequently use the computer in the evenings and need to use programs that change the color temperature at night.

As we know, there are most of such people because RGB keyboards or work at night is the norm today.

**Comment by andrewdavidwong** [comment]
This sounds like it's probably covered by:

https://www.qubes-os.org/faq/#could-you-please-make-my-preference-the-default
