### ISSUE TITLE
Warn about outdated qubes in Qubes "Update" Widget

### ISSUE THREAD

**Issue by deeplow** [QubesOS/qubes-issues#7818]
### The problem you're addressing (if any)

There is the risk of certain qubes never getting updated:

>[...] if vault was an App qube of a Template with no other app qube getting online to hae a successful update check reporting updates to dom0, that Template would never get update notifications pushed to dom0

Mentioning this in the documentation is not enough. Users mustn't have to read full docs in order to be aware of security edge-cases like this one.

Issue originally described and quoted from @tlaurion

### The solution you'd like

> - The *Qubes Update* widget *should* tell the user of the last time dom0 received an update notification for a specific template directly under Qubes Update widget 
>  - Adding a "**Last received update notification**" timestamp column, stating the last time an update notification was received from dom0 would most probably be enough?
> - The user *should be able to easily notice* that other greyed *templates* in the Qubes Update widget *have not received dom0 notifications since different dates*, **while updates were available for other templates**.  
>  - That should be enough to entice users into ticking the "enable updates for qubes without known available updates" which will give the real deal. If there is still no updates, nor errors given when manually attempting to update softwares in a Template: an end-user should be worried and look for EOL notices or at least minimally investigate the potential issue (unless he uses a really old template intentionally for development purposes, there should not be any reason for using deprecated and unmainted software on a daily use. *Maybe that Template should even be deleted*. **My point is that it should be as visible as possible that unmaintained Templates are being installed, and potentially used by and only by offline qubes which don't warn users of available updates since offline quebes don't notify dom0 of available updates.)**
>  - Adding an additional column "**Last update check**" should permit the user to notice EOL Templates easily since the timestamp for "**Last received update notification**" would still be old still old even if "Last update check" is recent.

### The value to a user, and who that user might be

Being aware of potentially outdated software, creating an urge to update it.

### Context

This report came out of this discussion: https://forum.qubes-os.org/t/14098/17

**Comment by deeplow** [comment]
@piotrbartman I heard this might already be implemented, at least the backend part. Is this correct?

**Comment by marmarek** [comment]
https://github.com/QubesOS/qubes-core-admin/pull/497

**Comment by andrewdavidwong** [comment]
@marmarta, @piotrbartman: Should this be closed as completed?
