### ISSUE TITLE
qubes window with incorrect color

### ISSUE THREAD

**Issue by xaki23** [QubesOS/qubes-issues#7820]
### Qubes OS release
4.1

### Brief summary
i just had a window for a fresh VM come up with an incorrect window frame color.
this actualy feels like a security issue, but since i dont have working repro steps, i will file it as-is for now. 

### Steps to reproduce
unknown.

i basicly just did a qvm-create, some prefs adjustment, started a terminal in it.
and the window has the wrong frame color.
the tasklist bar/tray color is correct, qvm-ls lists the right color.

![Screenshot from 2022-10-15 21-11-18-crop](https://user-images.githubusercontent.com/34632232/196004262-504b5b41-8e16-42f1-ac2b-b98adc744750.png)

edit: repro steps found!
```
[root@dom0 ~]# qvm-create -l red test-colors
[root@dom0 ~]# qvm-run test-colors gnome-terminal
Running 'gnome-terminal' on test-colors
(comes up as red as expected)
[root@dom0 ~]# qvm-remove -f test-colors
[root@dom0 ~]# qvm-create -l gray test-colors
[root@dom0 ~]# qvm-run test-colors gnome-terminal
Running 'gnome-terminal' on test-colors
(incorrectly still comes up as red)
```
== this seems to be caused by removing a vm, and creating one with the same name and different label/color.

### Expected behavior
windows have right color.

### Actual behavior
window has an unrelated color.

**Comment by DemiMarie** [comment]
Can you provide the output of `ps -ef qubes-guid|grep build-templates`?  That should provide the command line that the GUI daemon for the qube is using.

**Comment by xaki23** [comment]
that mainly results in "error: process ID list syntax error", but i guess you are looking for this:
```
admin    3310615       1  0 20:33 ?        00:00:00 /usr/bin/qubes-guid -N build-templates -c 0xcc0000 -i /usr/share/icons/hicolor/128x128/devices/appvm-red.png -l 1 -q -C /var/run/qubes/guid-conf.2689 -d 2689
```
so the guid is convinced the VM should be red. 
the guid.conf.2689 is "functionally empty".

i am unsure what color it had on first start before i adjusted the prefs. 
additional windows right now also come up as red. 
the taskbar icon being gray is an additional wtf.

**Comment by DemiMarie** [comment]
> that mainly results in "error: process ID list syntax error", but i guess you are looking for this:

oops, my mistake

> ```
> admin    3310615       1  0 20:33 ?        00:00:00 /usr/bin/qubes-guid -N build-templates -c 0xcc0000 -i /usr/share/icons/hicolor/128x128/devices/appvm-red.png -l 1 -q -C /var/run/qubes/guid-conf.2689 -d 2689
> ```
> 
> so the guid is convinced the VM should be red. the guid.conf.2689 is "functionally empty".
> 
> i am unsure what color it had on first start before i adjusted the prefs. additional windows right now also come up as red. the taskbar icon being gray is an additional wtf.

My current hypothesis is that you ran into a race condition.  It might be possible that `qvm-start-daemon` didn’t pick up on the changed qube label (color) and so started `qubes-guid` with an incorrect command line.  The tray icon receiver is started separately and so could have gotten the correct label.

There are a few possible solutions I can think of:

1. Have the GUI daemon support changing the label at runtime, and notify it when the label needs to be changed.
2. Have `qvm-start-daemon` kill and relaunch a qube’s GUI daemon if the qube’s label changes.
3. Do not allow a label change to take effect before `qvm-start-daemon` acknowledges it, and do not allow the qube to start in the meantime.

The last one is the one I currently prefer.

> i just had a window for a fresh VM come up with an incorrect window frame color. this actualy feels like a security issue, but since i dont have working repro steps, i will file it as-is for now.

I am inclined to believe that this is not a security issue, since if the problem is what I think it is, it cannot be triggered by any qube that is not already allowed to change the VM’s label via the Admin API.  That said, the final decision is up to @marmarek and @HW42.

**Comment by xaki23** [comment]
there was no change of label of an existing VM involved.
there was an older VM by the same name that was removed right before creating the current one, and _that_ one was indeed red.
if thats really a race condition, its a _huge_ one because i type fast, but not _that_ fast and there was remove-create-resize-start-poweroff-prefs-prefs-prefs-start. as in, more like a minute than "fractional seconds".

**Comment by xaki23** [comment]
but yay, that leads to repro steps!
```
[root@dom0 ~]# qvm-create -l red test-colors
[root@dom0 ~]# qvm-run test-colors gnome-terminal
Running 'gnome-terminal' on test-colors
(somes up as red as expected)
[root@dom0 ~]# qvm-remove -f test-colors
[root@dom0 ~]# qvm-create -l gray test-colors
[root@dom0 ~]# qvm-run test-colors gnome-terminal
Running 'gnome-terminal' on test-colors
(incorrectly still comes up as red)
```

**Comment by andrewdavidwong** [comment]
The repo steps seem to indicate that the VM was (1) force removed (2) without shutting it down first. I wonder whether either or both of those helps explain why this occurrs.

**Comment by xaki23** [comment]
the vm was shut down via poweroff inside the terminal.
and afaik the -f on qvm-remove just skips the are-you-sure dialog. 
```
[root@dom0 ~]# qvm-create -l red test-labels
(note no attempt is made to start the red instance)
[root@dom0 ~]# qvm-remove test-labels
This will completely remove the selected VM(s)...
  test-labels
Are you sure? [y/N] y
[root@dom0 ~]# qvm-create -l gray test-labels
[root@dom0 ~]# qvm-run test-labels gnome-terminal
Running 'gnome-terminal' on test-labels
(window comes up as gray)
[root@dom0 ~]# qvm-shutdown --wait test-labels
[root@dom0 ~]# qvm-remove test-labels
This will completely remove the selected VM(s)...
  test-labels
Are you sure? [y/N] y
[root@dom0 ~]# qvm-create -l green test-labels
[root@dom0 ~]# qvm-run test-labels gnome-terminal
Running 'gnome-terminal' on test-labels
(window still comes up as gray)
```
so the -f on remove is not required.
starting the old-label VM is required. (which might narrow down _where_ the label is cached)

**Comment by xaki23** [comment]
installed the mentioned updates on r4.1:
```
python3-qubesadmin-4.1.31-1.fc32.noarch
qubes-core-admin-client-4.1.31-1.fc32.noarch 
qubes-core-dom0-4.1.31-1.fc32.noarch
```

problem still exists. 

does this require a reboot or any restarting that is not done by pkg postinstall scripts?

**Comment by marmarek** [comment]
> does this require a reboot or any restarting that is not done by pkg postinstall scripts?

Yes, either restart of `qvm-start-daemon --all --watch` process, or logout+login.
