### ISSUE TITLE
xfce "window menu" icons are all blank

### ISSUE THREAD

**Issue by ddevz** [QubesOS/qubes-issues#7823]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
4.1

### Brief summary
While windows displayed in the "taskbar" panel widget have icons (with the correct qubes colors) as expected, windows displayed in the "window menu" panel widget have no icons at all (just a blank space).

When there are many windows in the taskbar, the taskbar will have a pulldown menu to display the windows that couldn't fit in the taskbar (as expected), however the pulldown also shows blank spaces instead of icons.

It continues to do this even after a reboot.

It was working on this particular system, then backing up qubes, replacing storage device, reformatting, restoring qubes, and now it's not working.

Crazy thought:  could this be related to the rd.qubes.hide_all_usb grub parameter?  It may have started after doing that.

This phenomenon has seen by this guy: https://forum.qubes-os.org/t/4-1-xfce-panel-add-on-window-menu-no-icons/7325

Any ideas how i could get debugging information to help with this?

### Steps to reproduce
1. Add "window menu" to the panel
2. Click the Pull down application list
3. Look for icons

### Expected behavior
See icons

### Actual behavior
Dont see Icons

**Comment by brycepg** [comment]
@ddevz were you able to regenerate the icons with `qvm-sync-appmenus <vmname>`?

**Comment by ddevz** [comment]
> @ddevz were you able to regenerate the icons with `qvm-sync-appmenus <vmname>`?

The "application list" is the list of running windows in a vertical list so I don't think that will help. 
But on the off chance qvm-sync-appmenus would help, i tried running it with a couple of the running VMs as parameters, but no change.

**Comment by brycepg** [comment]
Thanks for the confirmation @ddevz 

I was able to toggle the icons via clicking "System Tools" > Appearance. In the "Settings" tab make sure "Show images on buttons" and "Show images in menus" are checked
