### ISSUE TITLE
Check all places that use gettext in python for avoid f-strings

### ISSUE THREAD

**Issue by marmarta** [QubesOS/qubes-issues#7824]
### Brief summary

Check all places that use gettext for working with Python f-strings correctly (that is, they should not be using them, instead, they should use explicit .format()

**Comment by SaswatPadhi** [comment]
Hello,

Pardon my ignorance, but is there a security concern with using f-strings?

I tried searching online, but this thread seemed to suggest that they are actually "safer": https://security.stackexchange.com/questions/238338/are-there-any-security-concerns-to-using-python-f-strings-with-user-input.

**Comment by marmarta** [comment]
It's not about security - gettext converts a string to its translated format, and thus it won't work correctly if the f-string is inside gettext (from what I've seen in my tests), because the string fed to gettext will vary depending on how the variables were translated. So (with `_` as the gettext magic function):
```
_(f"my string {variable}")
```
will result in different strings being passed to gettext depending on what variable was, and also confusing it during the "collect stuff" phase.
 But if I do it like this:
```
_("my string {}").format(variable)
```
the string interpolation happens after translation, so it's all good.
It's not a security problem, it's a translation problem.

**Comment by SaswatPadhi** [comment]
Got it! Thank you; that makes sense.

**Comment by andrewdavidwong** [comment]
When you say "translation," do you mean in the sense of natural languages or programming languages? Just trying to figure out how to classify this issue.

**Comment by SaswatPadhi** [comment]
I believe it's about natural languages. gettext is about internationalization.
