### ISSUE TITLE
Input proxy tests use python-uinput which doesn't work on Fedora 37 anymore

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#7833]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

R4.1

### Brief summary

input proxy tests fail with:
```
Python 3.11.0rc2 (main, Sep 13 2022, 00:00:00) [GCC 12.2.1 20220819 (Red Hat 12.2.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib64/python3.11/site-packages/uinput/__init__.py", line 86, in <module>
    _libsuinput_path = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "_libsuinput" + sysconfig.get_config_var("SO")))
                                                                                     ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
TypeError: can only concatenate str (not "NoneType") to str
```

python-uinput seems to be abandoned: https://github.com/tuomasjjrasanen/python-uinput/issues/39

### Steps to reproduce

Example openQA job:
https://openqa.qubes-os.org/tests/52479

### Context

Found when preparing Fedora 37 template: #7807

**Comment by marmarek** [comment]
options I see:

- fork python-uinput and maintain a fork (the fix currently needed is rather trivial)
- write C wrapper for uinput
- find wrapper that somebody else already written
- call required ioctls manually from python - probably require substantial usage of ctypes and struct

**Comment by parkerlreed** [comment]
Was there ever a patch for python-uinput?

**Comment by marmarek** [comment]
Patch is [here](https://github.com/marmarek/python-uinput/commit/168bb8734e3722c4fdc24d4d75d07e992c09be53) but I haven't sent it upstream, since it seems to be abandoned repo.
