### ISSUE TITLE
builderv2-github: make notifications more accurate

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#7835]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

R4.2

### Brief summary

Current github notification (comments) from builderv2-github are sometimes not very accurate. For example https://github.com/QubesOS/updates-status/issues/3074#issuecomment-1292503713 - it should say just "uploaded", as it was built earlier already.

### Steps to reproduce

Build and upload package using builderv2-github, simulate some failures.

### Expected behavior

- when build fails: comment in updates-status and set appropriate *-failed label
- when build and "publish" succeed but upload fails: comment in updates-status (indicating successful build but failed upload), set normal `*-cur-test` label and perhaps additional `*-upload-failed` label?
- when upload to current (of a package in current-testing) succeed: comment that just publish+upload succeeded
- when publish to current worked, but upload failed - adjust labels similar to the second point above

The reasoning for the second point is that subsequent upload (even of a different component) will fix the issue. So, make the labels track it properly (for subsequent upload to stable commands).

### Actual behavior

https://github.com/QubesOS/updates-status/issues/3074#issuecomment-1292503713 - upload is notified as "build and upload" comment. 
Initial attempt at untangling this is at https://github.com/QubesOS/qubes-builderv2-github/commit/28a2fbbfeee8fdf9368c34a8273226cc5c3dc1d0, but that isn't enough.

**Comment by fepitre** [comment]
@marmarek do you still have some issue with this one or latest iteration were enough?

**Comment by marmarek** [comment]
I think it's okay now. If I notice some issue, I'll report again.
