### ISSUE TITLE
2 Questions in 1 | Unable to connect a USB stick to another qube than sys-usb

### ISSUE THREAD

**Issue by user-458956** [QubesOS/qubes-issues#7836]
**Hello everyone**, first of all I apologize if my question is stupid, I'm just starting out so I'm having a little trouble... I tried to do my best before posting this, I also apologize for my not so good English, it's not my native language.

First question/problem: I did my best to create the sys-usb VM with the wiki qubes I thought everything was fine until today when I wanted to connect a <USB or other> device to another Qube, it's impossible for me to read the content of the usb or to use the device I don't even see it connected to the virtual machine while before sys-usb everything was working fine (on the other hand it works perfectly in sys-usb).

Second question/problem: I tried to customize the GRUB but I realized that changing the timeout completely broke the grub, is it normal? (my manipulation : I modified this file : /etc/default/grub and I executed : grub2-mkconfig -o /boot/efi/EFI/qubes/grub.cfg)

Thanks to everyone who will take the time to answer a "Noob" like me!
(I'm sorry if these questions have already been solved elsewhere, I didn't find anything... maybe it's the fact that I have a little trouble with English so if a generous person could explain me clearly here it would be nice)

**Comment by andrewdavidwong** [comment]
Please note that the issue tracker (`qubes-issues`) is not intended to be a place for fielding questions. Instead, we have other [venues meant for asking questions, asking for help, and having discussions](https://www.qubes-os.org/support/). (By contrast, the issue tracker is more of a technical tool intended to support our developers in their work.) Thank you for your understanding!
