### ISSUE TITLE
dom0 metadata error

### ISSUE THREAD

**Issue by bluesteal** [QubesOS/qubes-issues#7842]
### Qubes OS release
R4.1

### Brief summary
Error: Failed to download metadata for repo ‘qubes-dom0-cached’: Cannot download repomd.xml: All mirrors were tried

Command: 
sudo dnf install ./3isec-qubes-task-manager-0.1-1.x86-64.rpm

**Comment by andrewdavidwong** [comment]
Have you tried waiting a bit and trying again later?

**Comment by unman** [comment]
This is the *local* repository.
I've seen this only after a cache clean. It should be fixed after the next
update when the local cache will be repopulated.

I've answered on the Forum (the right place for this issue, not here),
that you can run dnf disabling all repos with `--disablerepo=*`, when 
installing packages locally in dom0.

There's nothing for Qubes here.
Suggest close.
