### ISSUE TITLE
Cloning an HVM breaks network configuration for the clone due to Qubes assigning it a different internal IP address

### ISSUE THREAD

**Issue by Nurmagoz** [QubesOS/qubes-issues#7845]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

4.1.1

### Brief summary

Since qubes support only static IP method so the OS which is installed inside the HVM gonna be configured on a fixed IP,gateway..etc but if qubes cloning method used for this HVM to have HVM2 connection going to be lost because the new HVM2 has different IP given by qubes but internally within the OS it will inherit the previous HVM static IP configuration.

ofcourse user need to reconfigure the static IP within the new HVM2 to inherit the new changes.

### Screenshot

![hvmlostconnection](https://user-images.githubusercontent.com/11895339/198529524-aa855ab4-1972-4522-9f88-98eca3f0c93b.png)

### Steps to reproduce

1. Download debian .iso (or any OS)
2. Install it inside an HVM
3. Configure it to use the internet with static IP method
4. Shutdown and clone the HVM
5. Open debian inside HVM2 
6. No internet connection

Not sure if its possible to have multiple network interfaces within qubes e.g: 

HVM1 -> IP 123 

Clone it

HVM1 -> IP 123
HVM2 -> IP 123 linked to  another interface -> IP 849 -> then internet

by this HVM 1&2 gonna have same static IP configurations internally without loosing internet (ofcourse the OS inside the HVM wont know the difference of whats going on outside of it).

Or any solution possible.

**Comment by marmarek** [comment]
This is still the case on R4.2, but I believe it is intended behavior (duplicated IP addresses, while technically possible to handle, will be _very_ confusing and in case of any issues, very hard to debug). Maybe it wants documenting that cloned qube that doesn't have qubes tools installed may need reconfiguring network.
