### ISSUE TITLE
Fedora 37 VM - rpm/yum - security-testing/vm/fc37 dir missing.

### ISSUE THREAD

**Issue by brendanhoar** [QubesOS/qubes-issues#7848]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
R4.1 (testing Fedora 37 VM template)

### Brief summary
repo/dir missing for:
http://yum.qubes-os.org/r4.1/security-testing/vm/fc37

Can lead to failed fedora 37 updates, since repo is marked as skip_if_unavailable=false in qubes-r4.repo file.

### Steps to reproduce
Enable security-testing repo, perform updates.

### Expected behavior
Repo checked and any pending updates presented to user.

### Actual behavior
Updates fail.

B

**Comment by marmarek** [comment]
Fixed
