### ISSUE TITLE
'qubesctl --templates' calls all templates whether salt-agent is installed or not

### ISSUE THREAD

**Issue by unman** [QubesOS/qubes-issues#7849]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
4.1

### Brief summary
As title 

### Steps to reproduce
In update GUI - select windows template for updating.
At CLI - `qubesctl --templates` or `qubesctl --targets=QUBE` where QUBE has not salt agent installed.
 
### Expected behavior
No salt call will be made or call will gracefully fail.

### Actual behavior
In Update GUI, template is started, but will (in most cases) close automatically.
At CLI, the target qube is started but is not closed. User intervention is required.

I was uncertain whether to raise this as bug or enhancement.
It is not, of course, limited to target templates, but most obvious there.

Possible solution might be to change the pillar to include some tag - all stock templates could have tag "saltable".
This would be inherited by cloning.
Valid targets should be restricted to qubes having that tag.

Aside - the update GUI should only display for potential updates qubes controllable by salt. (separate feature request?)

**Comment by andrewdavidwong** [comment]
> Aside - the update GUI should only display for potential updates qubes controllable by salt. (separate feature request?)

That should be a separate issue, yes, as [every issue must be about a single, actionable thing.](https://www.qubes-os.org/doc/issue-tracking/#every-issue-must-be-about-a-single-actionable-thing)

**Comment by marmarek** [comment]
FWIW `qubesctl --templates state.highstate` (or similar) will only target templates that have non-empty top file. So, if your top file targets all templates (also those not really saltable, like Windows ones), qubesctl will try to follow the request. You can adjust your top file to target only some templates to avoid this issue.
This optimization is enabled only for `state.highstate` and `state.apply` commands.

If you have a case where it's not enough, on R4.2, please tell so.
