### ISSUE TITLE
Qubes Domains widget becomes unresponsive during VM startup/shutdown/kill activity

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#7855]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

R4.1

### Brief summary
The domains widget stops responding intermittently, usually when lots of VMs are starting or widget is shutting down or killing a VM.

### Steps to reproduce

Use the domains widget to kill a VM

### Expected behavior

The widget stays responsive

### Actual behavior

The widget stops responding.

**Comment by andrewdavidwong** [comment]
I've also noticed this.
