### ISSUE TITLE
Hardware support: Ryzen 7000 series / Zen 4 / AM5

### ISSUE THREAD

**Issue by neowutran** [QubesOS/qubes-issues#7856]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
4.1

### Brief summary
Qubes OS does not support Ryzen 7000 series
More specifically, Xen panic saying that it doesn't known the CPU family n° 25
From my understanding, supporting recent hardware would require upgrading xen+libvirt+dom0 
( Started few day ago a work to try to upgrade that, but unsure if I will suceed )

### Steps to reproduce
Try to run the qubes installer on a computer with a ryzen 7000 serie 

### Expected behavior
Qubes installer is running

### Actual behavior
Xen panic

**Comment by DemiMarie** [comment]
@marmarek can the needed Xen patches be backported?

**Comment by 0spinboson** [comment]
https://forum.qubes-os.org/t/ryzen-7000-serie/14538/14 < relevant forum thread. Neowutran's made quite some progress, now working on anaconda-qubes patches

**Comment by neowutran** [comment]
I have made a lot of progress lately, and I am now confident that I will make it work as I want (A lot of work is still required on my side. And a lot of testing.).
It is a major upgrade of many dependencies (dom0 fc37+, xen 4.16+, libvirt 8.9+, qemu 7.1+, python 3.11+), so lot of breaking changes, lot of repository that need to be modified etc etc. 

Is that a work that interest the Qubes projet for a futur major upgrade (5.x ? 4.3+ ? ... ) ? 
In case it is of interest for Qubes projet, do you know how you want to proceed ?

**Comment by marmarek** [comment]
Qubes 4.2 will include at least Xen 4.17 and libvirt 8.9, part of that is already done here: qubesos/qubes-vmm-xen#144 qubesos/qubes-core-libvirt#43. Such major changes will _not_ be supported on 4.1.

**Comment by DemiMarie** [comment]
@neowutran could the relevant patches be backported to the versions used in R4.1?

**Comment by neowutran** [comment]
I will try to find the set of patches required next week. If I succeed I will post it here. 
Before that I am still trying to understand some issue I have with my AM5 motherboard (bios is buggy / unstable & unreliable, but maybe some of the issues could be related to kernel version, will try to rule out that)

**Comment by vlad-timofeev** [comment]
Did this work include support for AMD Phoenix CPUs, such as Ryzen 7940HS?
