### ISSUE TITLE
Qubes OS 4.1.1 has only one VM - dom0 after installation, no other qubes present

### ISSUE THREAD

**Issue by jamke** [QubesOS/qubes-issues#7872]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
R4.1.1

### Brief summary
After installation of Qubes OS it has only one VM - dom0.

### Steps to reproduce
* Run installation of Qubes OS 4.1.1 from a USB flash-disk.
* Set partitioning and user settings, keep all other settings as is. 
* Wait for installation to finish and installer to restart the PC.

### Expected behavior
Qubes OS starts and works. Or asks any additional information about templates or qubes to install.

### Actual behavior
Qubes OS starts but it's unusable - I see no templates, nor qubes in Qubes Manager - only dom0.

### Additional details:
0) I was not asked about any template decisions, like which one to use - fedora or debian, nor if I need default pack of qubes like personal and etc.
1) I tried to reinstall and the result was the same. It's easy for me to reinstall again for any additional information required for fixing the issue.
3) I'm using Custom partitioning during install to use it on the disk with other OSes installed. Not manual but "custom" with a click on automatic partition creation on free space feature.  I can provide more information about partitioning if it's relevant.

**Comment by GWeck** [comment]
On a similar issue in Qubes R4.0, @marmarek suggested:

You can start the post-installation wizard with `sudo /usr/libexec/initial-setup/initial-setup-graphical`.
As to find out why it wasn't started automatically, take a look at `initial-setup` related entries in `journalctl`.

For further information, see issue [#5003](https://github.com/QubesOS/qubes-issues/issues/5003).

**Comment by jamke** [comment]
Thank you @GWeck for this information.

Currently the installer of R4.1.1 has a bug that prevents post-install wizard from running in case of manual (but automatic!) partitioning. At least in my case it was the reason. Completely automatic partitioning worked fine and post-installer wizard was shown.

The whole process of manual partitioning in the installer is very unreliable and buggy for now. But it comes from Fedora, I suppose.
