### ISSUE TITLE
Archlinux Builder: Not all commands are logged when debugging template build

### ISSUE THREAD

**Issue by tezeb** [QubesOS/qubes-issues#7875]
### Qubes OS release

4.1.1

### Brief summary

While debugging https://github.com/QubesOS/qubes-issues/issues/7874, I've noticed that trace log of command execution is set after
some commands are already executed in `00_prepare.sh` of `archlinux-builder`. It makes debugging harder.

### Steps to reproduce

Run `make qubes-vm VERBOSE=3`.

### Expected behavior

All commands executed in scripts shall be logged.

### Actual behavior

Some commands are executed before `set -x`, thus they are not visible in trace log.

**Comment by lubellier** [comment]
@tezeb : this issue is closable with the merged https://github.com/QubesOS/qubes-builder-archlinux/pull/61 PR.
If you agree, close it.
