### ISSUE TITLE
xfce4-panel (including Application menu) does not honor DPI, font size and theming settings of xfce sometimes

### ISSUE THREAD

**Issue by jamke** [QubesOS/qubes-issues#7881]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
R4.1.1

### Brief summary
xfce4-panel (including Application menu) does not honor DPI nor font size settings of xfce.
It always has the same small font and default color.s
In R4.0 I had no such issue, so maybe it's a regression or a xfce bug.

### Steps to reproduce

I have no straight forward way to get in this situation.
I got in this situation twice in a something-like-that way:

1. Install Qubes OS 4.1.1.
2. Set custom DPI or Default Fond size in `Appearance` -> `Fonts` tab of the xfce settings.
3. Set other settings in xfce settings and use the system for some time (not sure what can cause).
4. Reboot PC

### Expected behavior
xfce4-panel, including Application menu, uses custom DPI, fonts, theming colors.

### Actual behavior
xfce4-panel, including Application menu, uses default and ignores any changes in xfce4 settings.

**Comment by andrewdavidwong** [comment]
Just to clarify, is this the new app menu or the old one?

**Comment by jamke** [comment]
It's about the old one (one from R4.0 and one I have by default with clean R4.1.1).

**Comment by jamke** [comment]
After another reboot the situation change completely. It makes me look stupid again =)
Now it honors DPI setting and Default Font size setting on-fly, applying the changes to the size the moment the settings are changed.
But **I am sure it was not working at all** that way yesterday, even after reboot. I do not know why it fixed itself, maybe due to dom0 updates or something.

**Comment by jamke** [comment]
I reinstalled R4.1.1 from scratch on an empty ssd. And I have the same situation again.
The font is small and does not depend on DPI settings, font size settings.
Reboot does not help either.

Additional info that make the issue more important - the whole xfce panel does not honor fonts and dpi. The clock widget is also small when I click it. On R4.0 previously I had no such problem and clock (calendar) was bigger according to the xfce settings.

**Comment by jamke** [comment]
@marmarta do not spend time it's probably not easy to get this state.
I had some more general problems with XFCE panel (that includes Application menu that I noticed originally).

The font was small (original) for the whole panel. The only way to fix it - was to run:
`xfce4-panel -r`
This restarts the panel. And after it the panel was becoming fine: proper DPI, font size and theming but only until the reboot. So that proved for me that the settings in were correct. But after reboot the panel, including Application menu was again broken as described in the ticket.

The way I currently "solved" it - I created almost empty `/home/user` directory to reset all and tuned DPI, fonts and etc again manually. It works at least for now.

I saved the original user directory with this bugs but first analysis and compering provided no information that could cause the issues with the panel, so I may try to find out the reason again later.

**Comment by unman** [comment]
4.1 clean install.
menu responsive to font changes as intended.
Continues to be so after full update.

**Comment by jamke** [comment]
> 4.1 clean install. menu responsive to font changes as intended. Continues to be so after full update.

Of course is it, I had to reset user folder to get it work again. It's similar to the clean reinstall.

The problem is that somehow making changes to settings of xfce I was able to get in this mess-situation twice, even after clean reinstall.
Maybe qubes restore tools are somehow involved as both times I was restoring my vms from R4., and both times I was not recovering dom0 just to avoid such problems of incompatibility.

The fact, that `xfce4-panel -r ` fixes it (temporary) means that the config is OK, and that something breaks it, almost certainly a bug. But I'm not sure if it's QubesOS-related problem or just another xfce bug.

**Comment by andrewdavidwong** [comment]
> Maybe qubes restore tools are somehow involved as both times I was restoring my vms from R4., and both times I was not recovering dom0 just to avoid such problems of incompatibility.

If you skipped restoring dom0 when restoring from a backup, I don't see how that could affect anything. In fact, even if you *do* restore dom0 from a backup, the Qubes backup restore tool creates a subdirectory in dom0's home directory and restores the files from the backup inside that subdirectory, so you'd have to manually move them out of that subdirectory in order for them to have any effect.

**Comment by unman** [comment]
On Fri, Nov 18, 2022 at 07:28:21AM -0800, jamke wrote:
> > 4.1 clean install. menu responsive to font changes as intended. Continues to be so after full update.
> 
> Of course is it, I had to reset user folder to get it work again. It's similar to the clean reinstall.
> 
> The problem is that somehow making changes to settings of xfce I was able to get in this mess-situation twice, even after clean reinstall.
> Maybe qubes restore tools are somehow involved as both times I was restoring my vms from R4., and both times I was not recovering dom0 just to avoid such problems of incompatibility.
> 
> The fact, that `xfce4-panel -r ` fixes it (temporary) means that the config is OK, and that something breaks it, almost certainly a bug. But I'm not sure if it's QubesOS-related problem or just another xfce bug.
> 
In your original issue you gave steps to reproduce which referred only
to installing 4.1.1.
When you reopened, again you referred only to reinstalling from scratch.
 
Marta said she didn't see this but her system is upgraded in place.
I was stating that on a clean install I don't see the issue.

Now you say that you had made changes to settings in xfce.
I doubt that restoring of qubes would cause this, so it's important
you set out what changes you made to the Xfce settings.
When you trigger this what is content of xsettings.xml?

**Comment by jamke** [comment]
> If you skipped restoring dom0 when restoring from a backup, I don't see how that could affect anything.

I see it the same way, just mentioned it in case restoring dom0 makes some magic for transition R4.0->R4.1 that I could have skipped.

> In your original issue you gave steps to reproduce which referred only to installing 4.1.1.

@unman I see, I was misunderstood. I will modify the first post.
My point about clean reinstall was that I did a clean reinstall and after changing DPI, font size other theming settings and using the system for a day - I still got the same issue, so it was not such a unique situation for my case.

> I doubt that restoring of qubes would cause this, so it's important

Did you mean "not important"?
I mentioned it mostly because restoring qubes makes a lot of icons and desktop files inside `/home/user` directory of `dom0` (where the problem is probably located) and populates Application menu, which is also a part of `xfce4-panel` that was also involved as force restarting it was fixing the xfce state.

> When you trigger this what is content of xsettings.xml?

What do you mean with "trigger this"? When I get this problem? It's not like a moment or something, it's that after reboot the panel with all menus was ignoring a lot of xfce settings including fonts, DPI and theming.

But I have user directory from a buggy setup and current, when I had to set all xfce settings from scratc h for the third time and it still works OK for now. So I can provide the difference in `xsettings.xml` between those:

```
$ diff xsettings.xml.working_stable xsettings.xml.from_buggy_setup
7c7
<     <property name="DoubleClickTime" type="int" value="500"/>
---
>     <property name="DoubleClickTime" type="int" value="400"/>
13,14c13,14
<     <property name="EnableEventSounds" type="empty"/>
<     <property name="EnableInputFeedbackSounds" type="empty"/>
---
>     <property name="EnableEventSounds" type="bool" value="false"/>
>     <property name="EnableInputFeedbackSounds" type="bool" value="false"/>
18c18
<     <property name="Antialias" type="empty"/>
---
>     <property name="Antialias" type="int" value="1"/>
24c24
<     <property name="CanChangeAccels" type="empty"/>
---
>     <property name="CanChangeAccels" type="bool" value="false"/>
26c26
<     <property name="FontName" type="empty"/>
---
>     <property name="FontName" type="string" value="Sans 12"/>
29c29
<     <property name="ToolbarStyle" type="empty"/>
---
>     <property name="ToolbarStyle" type="string" value="icons"/>
39a40
>     <property name="MonospaceFontName" type="string" value="Sans 12"/>
42a44,46
>   </property>
>   <property name="Gdk" type="empty">
>     <property name="WindowScalingFactor" type="int" value="1"/>


```

**Comment by jamke** [comment]
I modified the first post. 
@andrewdavidwong please consider changing the topic to something like:
> xfce4-panel (including Application menu) does not honor DPI nor font size settings of xfce

because I was wrong that this bug affects only Application menu and not the whole panel.

@Bwahharharrr thank you for your thumb up on a ticked. Does it mean you had a similar issue? Maybe you can provide some additional information because I have no idea why such situation happened to me twice.

**Comment by marmarek** [comment]
> > ```
> >  <property name="Gdk" type="empty">
> >     <property name="WindowScalingFactor" type="int" value="1"/>

This, and various font sizes set explicitly looks to be related. I guess changing something in "Appearance" settings made it save those values. That said, I'm not sure what should be saved there, if anything.

**Comment by jamke** [comment]
I think `WindowScalingFactor` and other values are saved in this xml config in case those have been changed.
If the user changes the scale to `2` and then back to the original `1` then the config still will have an explicit default value, I think.

**Comment by unman** [comment]
> Did you mean "not important"?
No, it's important that you set out exactly what Xfce changes you made.
You haven't yet done this.

**Comment by jamke** [comment]
> No, it's important that you set out exactly what Xfce changes you made.
> You haven't yet done this.

Oh, "it's important" is about previous sentence. For me it's hard to understand you man sometimes.

Unfortunately I am not recording all the options I change in xfce settings. And right now I have no issue with panel despite I was making seemingly the same changes as two first times when I had that issue. So, maybe I was changing settings in some different way, I can't tell.

**Comment by unman** [comment]
> Oh, "it's important" is about previous sentence. For me it's hard to understand you man sometimes.
It's part of the same sentence continued on the next line.(That
next line really *is* hard to understand otherwise.)

**Comment by jamke** [comment]
I tried to mess with xfce-configs to bring the xfce4-panal back to the broken state but I could not.
So, I'm not sure if this issue can be solved without an ability to reproduce it.

Xfce is not only ugly but also has a lot of bugs. So, it's probably a xfce bug anyway. 

So, I think the issue can be closed.
And the fact that this behavior is reported here (on Qubes issue-tracker) will allow anybody to provide their feedback if they got in a similar situation.

**Comment by jamke** [comment]
I installed R4.1.1 on a new computer and started to change settings manually to look the same as I have on main computer.
And it got broken again. Something with theming and dpi is broken in XFCE,

**Comment by jamke** [comment]
@andrewdavidwong I am sorry, I meant affects R4.2.3, I do not know about R4.3. My bad.

**Comment by jamke** [comment]
It affects R4.3. I have the same problems on R4.3 install.
