### ISSUE TITLE
qubes-dom0-update does not provide valid information about matching packages in case one is not matched

### ISSUE THREAD

**Issue by jamke** [QubesOS/qubes-issues#7885]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
4.1.1.

### Brief summary
`qubes-dom0-update` does not provide valid information about matching packages in case one is not matched.

### Steps to reproduce
Consider 4 packages in repos:
**normal1** - usual, not installed, e.g. `mc`
**normal2** - usual, not installed, e.g. `mousepad`
**notexisting** - not existing package, installed, e.g. `blablabla`
**someinstalled** - usual, installed, e.g. `dconf`.

If we call in dom0: `sudo qubes-dom0-update normal1 normal2 notexisting someinstalled` we will get a `[sys-firewall] sh` terminal window with:

> No match for argument: **notexisting**
> Package **someinstalled** is already installed.
> Error: Unable to find a match: **notexisting**
> Fetching updates failed with code 1: press Enter to exit

While `[dom0] Terminal` provides different information:

> No match for argument: **normal1**
> No match for argument: **normal2**
> No match for argument: **notexisting**
> Package **someinstalled** is already installed.
> Error: Unable to find a match: **normal1 normal2 notexisting**

Which is wrong and misleading about normal1 and normal2.

### More info
I consider it to be a very minor issue. But I could not find it on the issue-tracker, so I am adding it at least for documentation purposes.

**Comment by alimirjamali** [comment]
> While `[dom0] Terminal` provides different information:

I believe that the `qubes-dom0-update` behaviour and reporting might have improved and changed a lot since the filing of this issue. Is the issue still valid? I currently only get only the `updatevm` output on 4.2.2
