### ISSUE TITLE
Make consistent use of MiB (binary sizes) in GUI and tools and to avoid any misinterpretation

### ISSUE THREAD

**Issue by jamke** [QubesOS/qubes-issues#7889]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### The problem you're addressing (if any)

Currently Qubes OS uses "MB" to describe the size of 1024*1024 bytes. It has this disadvantages.

1. You never know what MB is. It can be 2^20 bytes as in Windows, or 10^6 bytes as in memory and disk specifications.
2. All other GNU+Linux-based OSes and almost all software for them uses "MiB", "KiB" and etc to avoid any misinterpretation. I think, Qubes OS should stick to GNU+Linux standards of naming. Dolphin, Partition manager, command-line tools like `dd` do support binary notation.

### The solution you'd like
The usage of `MiB` and other binary prefixes for sizes everywhere (in GUI and qubes commandl-ine tools)  can make everything clear and consistent.
The usage of MB, especially as 10^6 should be left for sellers of RAM, HDD and SSD to deceive their buyers only.

### The value to a user, and who that user might be
No misunderstanding and misinterpretation, consistent values in Qubes OS GUI and tools.

**Comment by alimirjamali** [comment]
PR Submitted

Review priority: low

p.s. This is for Qube Manager only. If there is any other occurrence of MB or GB in other GUI (or CLI) tools, please report them by replying to this issue.
