### ISSUE TITLE
salt-ssh not available for Debian bookworm

### ISSUE THREAD

**Issue by unman** [QubesOS/qubes-issues#7896]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
4.1

### Brief summary
salt-ssh package is not available in bookworm

### Steps to reproduce
`apt install  salt-ssh`

### Expected behavior
Will install

### Actual behavior
Wont install

salt-ssh is available in sid, but not in bookworm.
soft freeze is scheduled for 2023-02-12
If salt-ssh has not moved in to testing by then, we'll have to provide a package ourselves

This is dependency of #7134

**Comment by marmarek** [comment]
For reference: https://tracker.debian.org/pkg/salt
