### ISSUE TITLE
Get rid of the "Cannot start qrexec for domain XYZ, do you want to wait or not" message

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#790]
**Reported by joanna on 2 Feb 2014 10:53 UTC**
Nobody likes "modal" dialog boxes that ask strange questions nobody knows why!

Just display a notification message and automatically kill the VM and perhaps automatically attempt to start it again.

Migrated-From: https://wiki.qubes-os.org/ticket/790

**Comment by mdik** [comment]
Right now I'm running into timeouts when doing
`qvm-create-default-dvm whonix-ws`
and I would really appreciate either a longer timeout, or the option to wait a bit longer :-}
