### ISSUE TITLE
qubes installer not working on 12th Gen Intel  cpu

### ISSUE THREAD

**Issue by tusind** [QubesOS/qubes-issues#7900]
### Qubes OS release

I tried three qubes isos

1. official Qubes-R4.1.1-x86_64.iso
2. Qubes-20221112-x86_64.iso  from qubes.notset.fr
3. Qubes-20221112-kernel-latest-x86_64.iso from qubes.notset.fr

### Brief summary

qubes-os installer isn't working on 

Machine
model: PRO Z690-A WIFI DDR4(MS-7D25)

CPU:
12th Gen Intel Core i9-12900K

Graphics
AMD Navi 22 Radeon6700 XT

Memory: 64 GiB ddr4

[dmesg message that I saved before the installer freeze the host](https://gist.github.com/tusind/9a9a7e035743aad721f20747db5b4d75)

### Steps to reproduce

boot from a  usb with an intel  i9-12900K and amd  Radeon6700 XT
the installer failed just before starting the gui installer. the host freeze after it 

I tried to install it with uefi mode and legacy mode.
I disabled the onboard nic card and added an external dual 1GB card. 

### Expected behavior

have a working qubes-os installation process

### Actual behavior
the host freeze and the installation stop right before starting the gui part.

**Comment by jamke** [comment]
If you have time and desire you can try to boot an already-installed Qubes OS on the same hardware.
To find out if the installer is a core problem or something else.

**Comment by tusind** [comment]
> If you have time and desire you can try to boot an already-installed Qubes OS on the same hardware. To find out if the installer is a core problem or something else.

I installed qubes os with Qubes-20221112-kernel-latest-x86_64.iso . 
uefi installation didn't boot on the hardware
legacy installation boot up qubes grub on the hardware but when the X should start I only got tree dots. no tty is available, and it looks like the host freeze because they keyboard isn't working

it looks like amd gpu isn't the best alternative to use with qubes os, this is such a bummer because I need 4 outputs that is why I have the amd gpu :( 

I only found nvidia install driver [here](https://github.com/Qubes-Community/Contents/blob/master/docs/configuration/install-nvidia-driver.md)

**Comment by tusind** [comment]
I just removed the amd gpu and the same legacy boot disk can't load qubes os at all.
I have this message  as soon the host is power on

```
There is no VBIOS support detected inthis card.
BIOS CSM/UEFI Mode' settings in BIOS will be changed to Enabled
```

:disappointed:

**Comment by tusind** [comment]
> What if you switch to UEFI boot in this case?

I switched to uefi but the OS can't be found. the installation process finished but I can't configure qubes on the host with the integrated intel gpu.

**Comment by jamke** [comment]
It probably will not help, but check if "Above 4G" is off (see #7308). Helped me on 11gen.

**Comment by tusind** [comment]
> It probably will not help, but check if "Above 4G" is off (see #7308). Helped me on 11gen.
I used Qubes-20221125-x86_64.iso with Above 4G disabled, UEFI mode. the installation finished but the first boot on disk never show up. I can't even see the qubes os option on the bios. :disappointed:

**Comment by tusind** [comment]
:wave:  

last weekend I configured successfully post install qubes 4.1.1 on 12th Gen on  PRO Z690-A WIFI DDR4 BIOS CSM with nvidia 210 card.

There is something missing in the qubes 4.1.1 installer because the onboard video card is not working at all after the first boot from nvme.  

```
| integrated graphics card:  | first boot nvme not working at all BIOS CSM or UEFI mode |
| AMD Navi 22 Radeon6700 XT: | first boot nvme not working at all BIOS CSM or UEFI mode |
| GeForce 210 1GB DDR3:      | first boot nvme not working UEFI mode                    |
| GeForce 210 1GB DDR3:      | first boot nvme working BIOS                             |

```

I tried two qubes isos:

+ official Qubes-R4.1.1-x86_64.iso
+ Qubes-20221213-kernel-latest-x86_64.iso from qubes.notset.fr

both qubes isos worked with BIOS CSM and GeForce 210 1GB DDR3 opensource driver.

**Comment by tusind** [comment]
Hi All.
I just tried to install Qubes-4.2.202301293-x86_64.iso on  MSI PRO Z690-A WIFI DDR4  12th Gen CPU with AMD Navi 22 Radeon6700 XT.

The installer didn't start anaconda gui, I tried uefi and bios CMS (legacy boot) 
I collected logs from basic graphic mode and kernel -6.1.7.1 options like so [4.2 logs](https://gist.github.com/tusind/ff6753ce86f956cacdf68a8bc781276d)


is Qubes-4.2.202301293-x86_64.iso  based on fedora 37 ?

What is the amdgpu driver included in Qubes-4.2.202301293-x86_64.iso  . 
It is possible to install amdgpu rpm package like https://repo.radeon.com/amdgpu/21.40.1/rhel/8.5/main/x86_64 after booting the iso? 


Is there any amd gpu  supported by qubes 4.1 with four or more outputs . I need to connect at least four monitors.

**Comment by tusind** [comment]
I solved the issue by using a Radeon RX 570

**Comment by jamke** [comment]
I don't think this issue should be closed. Maybe it should be reopened?

Adding Radeon is not a **solution** but **workaround**. Besides, not all devices by far allow adding Radeon graphics, almost all laptops do not. So even this workaround is not available for them.

**Comment by tusind** [comment]
> I don't think this issue should be closed. Maybe it should be reopened?
> 
> Adding Radeon is not a **solution** but **workaround**. Besides, not all devices by far allow adding Radeon graphics, almost all laptops do not. So even this workaround is not available for them.

this issue is not related to laptops though. 
it looks like qubes 4.1 and qubes 4.2 do not support Navi 22 at the moment.

**Comment by jamke** [comment]
> this issue is not related to laptops though.
> it looks like qubes 4.1 and qubes 4.2 do not support Navi 22 at the moment.

OK, makes sense.
