### ISSUE TITLE
qvm-template-gui hard/impossible to navigate with keyboard

### ISSUE THREAD

**Issue by unman** [QubesOS/qubes-issues#7901]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
4.1

### Brief summary
As title

### Steps to reproduce
Open qvm-template-gui
Attempt to navigate template list
Attempt to select navigate and select "Apply"

### Expected behavior
User will be able to easily move up and down templates lists
User will be able to select Reset/Apply

### Actual behavior
When row is selected, UP/DOWN moves 1 row and immediately opens action sub menu.
You have to "Esc" that menu , Esc again, before UP/DOWN keys work on rows.

If you Esc once, the TAB key moves down 1 row and immediately opens action sub menu.
Sometimes TAB does nothing.

There is no way of selecting Refresh/Apply without mouse action.

**Comment by andrewdavidwong** [comment]
Sounds somewhat related to https://github.com/QubesOS/qubes-issues/issues/7635.
