### ISSUE TITLE
qvm-move vanishes files when given partially incorrect parameters

### ISSUE THREAD

**Issue by marmarta** [QubesOS/qubes-issues#7905]
### Qubes OS release

R.4.1.1

### Brief summary

`qvm-move` removes files from source VM and does not put them in target VM sometimes.

### Steps to reproduce

When I do:
`qvm-move file_I_dont_have_permission_to_read other_files`
I get an error (correct), but the `other_files` vanish from source VM and are not in the target VM. 

### Expected behavior

Error and no files moved, error and accessible files moved, in any case no vanishing files.

**Comment by jamke** [comment]
@andrewdavidwong 
Please, make the issue `critical` because it's about user's data loss.

**Comment by rustybird** [comment]
Yeah it's brutal!

In `qvm-move`,

`qrexec-client-vm @default qubes.Filecopy /usr/lib/qubes/qfile-agent file_I_dont_have_permission_to_read other_files`

exits 0 (even though `qfile-agent ...` exits 1) and that already seems wrong. But shouldn't the remote end (`qfile-unpacker` in `qubes.Filecopy`) also exit unsuccessfully?

**Comment by rustybird** [comment]
Besides the `qvm-move` CLI this also affects GUI file move, although the latter will fail safe in cases where `du file_I_dont_have_permission_to_read` exits nonzero.

**Comment by rustybird** [comment]
A very similar case affecting the `qvm-move` CLI (but not the GUI, thanks to `du` failing) is when it doesn't have read permissions on a file (so it cannot be copied) but *does* have write permissions on the parent directory (so the file will be deleted regardless):

    $ echo foo >foo
    $ chmod 000 foo
    $ qvm-move foo
    qfile-agent: Fatal error: open foo (error type: Permission denied)
    EOF
    $ ls file
    ls: cannot access 'foo': No such file or directory

**Comment by DemiMarie** [comment]
Losing user data is not acceptible.  Marked as blocker.
