### ISSUE TITLE
PCIe USB Controller is unusable in R4.1 due to `xHCI host controller not responding, assume dead` error

### ISSUE THREAD

**Issue by jamke** [QubesOS/qubes-issues#7906]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
R4.1.1.

### Brief summary
PCIe USB Controller is unusable in R4.1 in usb qube because it is disconnected by Qubes OS (kernel?) with a error message `xHCI host controller not responding, assume dead`.

### Steps to reproduce
1. Start qube (HVM) with attached PCIe USB Controller (that work perfectly fine on Qubes R4.0).
2. Connect flash drive.
3. Mount it
4. Open directory in a file manager
5. Make any changes to the files (remove, create new).

### Expected behavior
Everything works as it worked on R4.0.

### Actual behavior
After a couple of seconds (when fsync happens probably) the file manager freezes for a moment and then the usb drive is disconnected without user doing anything.
Dom0 shows popups that device was removed.
The logs provide errors that `xHCI host controller not responding, assume dead`.

**Comment by jamke** [comment]
**Errors in `sudo dmesg`:**

```
[  573.875145] xhci_hcd 0000:00:06.0: xHCI host controller not responding, assume dead
[  573.875172] xhci_hcd 0000:00:06.0: HC died; cleaning up
[  573.875201] usb 3-2: USB disconnect, device number 2
[  573.879089] blk_update_request: I/O error, dev sda, sector 10465 op 0x1:(WRITE) flags 0x100000 phys_seg 1 prio class 0
[  573.879122] Buffer I/O error on dev sda1, logical block 10463, lost async page write
[  573.879158] blk_update_request: I/O error, dev sda, sector 10755 op 0x1:(WRITE) flags 0x100000 phys_seg 1 prio class 0
[  573.879184] Buffer I/O error on dev sda1, logical block 10753, lost async page write
[  573.879254] blk_update_request: I/O error, dev sda, sector 234244610 op 0x1:(WRITE) flags 0x100000 phys_seg 256 prio class 0
[  573.879285] Buffer I/O error on dev sda1, logical block 234244608, lost async page write
[  573.879304] Buffer I/O error on dev sda1, logical block 234244609, lost async page write
[  573.879322] Buffer I/O error on dev sda1, logical block 234244610, lost async page write
[  573.879340] Buffer I/O error on dev sda1, logical block 234244611, lost async page write
[  573.879357] Buffer I/O error on dev sda1, logical block 234244612, lost async page write
[  573.879375] Buffer I/O error on dev sda1, logical block 234244613, lost async page write
[  573.879393] Buffer I/O error on dev sda1, logical block 234244614, lost async page write
[  573.879410] Buffer I/O error on dev sda1, logical block 234244615, lost async page write
[  573.879489] blk_update_request: I/O error, dev sda, sector 3240 op 0x0:(READ) flags 0x0 phys_seg 1 prio class 0
[  573.879527] exFAT-fs (sda1): error, failed to access to FAT (entry 0x0002534d, err:-5)
[  573.879550] exFAT-fs (sda1): Filesystem has been set read-only
[  573.899554] blk_update_request: I/O error, dev sda, sector 10465 op 0x1:(WRITE) flags 0x100000 phys_seg 1 prio class 0
[  573.899594] blk_update_request: I/O error, dev sda, sector 10755 op 0x1:(WRITE) flags 0x100000 phys_seg 1 prio class 0
[  573.899982] exFAT-fs (sda1): error, failed to access to FAT (entry 0x00000004, err:-5)
[  579.484302] exFAT-fs (sda1): error, failed to access to FAT (entry 0x00000004, err:-5)
```


**Errors in `sudo journalctl`:**
```
Nov 21 18:03:37 usb-qubes-name kernel: xhci_hcd 0000:00:06.0: xHCI host controller not responding, assume dead
Nov 21 18:03:37 usb-qubes-name kernel: xhci_hcd 0000:00:06.0: HC died; cleaning up
Nov 21 18:03:37 usb-qubes-name kernel: usb 3-2: USB disconnect, device number 2
Nov 21 18:03:37 usb-qubes-name kernel: blk_update_request: I/O error, dev sda, sector 10465 op 0x1:(WRITE) flags 0x100000 phys_seg 1 prio class 0
Nov 21 18:03:37 usb-qubes-name kernel: Buffer I/O error on dev sda1, logical block 10463, lost async page write
Nov 21 18:03:37 usb-qubes-name kernel: blk_update_request: I/O error, dev sda, sector 10755 op 0x1:(WRITE) flags 0x100000 phys_seg 1 prio class 0
Nov 21 18:03:37 usb-qubes-name kernel: Buffer I/O error on dev sda1, logical block 10753, lost async page write
Nov 21 18:03:37 usb-qubes-name kernel: blk_update_request: I/O error, dev sda, sector 234244610 op 0x1:(WRITE) flags 0x100000 phys_seg 256 prio class 0
Nov 21 18:03:37 usb-qubes-name kernel: Buffer I/O error on dev sda1, logical block 234244608, lost async page write
Nov 21 18:03:37 usb-qubes-name kernel: Buffer I/O error on dev sda1, logical block 234244609, lost async page write
Nov 21 18:03:37 usb-qubes-name kernel: Buffer I/O error on dev sda1, logical block 234244610, lost async page write
Nov 21 18:03:37 usb-qubes-name kernel: Buffer I/O error on dev sda1, logical block 234244611, lost async page write
Nov 21 18:03:37 usb-qubes-name kernel: Buffer I/O error on dev sda1, logical block 234244612, lost async page write
Nov 21 18:03:37 usb-qubes-name kernel: Buffer I/O error on dev sda1, logical block 234244613, lost async page write
Nov 21 18:03:37 usb-qubes-name kernel: Buffer I/O error on dev sda1, logical block 234244614, lost async page write
Nov 21 18:03:37 usb-qubes-name kernel: Buffer I/O error on dev sda1, logical block 234244615, lost async page write
Nov 21 18:03:37 usb-qubes-name kernel: blk_update_request: I/O error, dev sda, sector 3240 op 0x0:(READ) flags 0x0 phys_seg 1 prio class 0
Nov 21 18:03:37 usb-qubes-name kernel: exFAT-fs (sda1): error, failed to access to FAT (entry 0x0002534d, err:-5)
Nov 21 18:03:37 usb-qubes-name kernel: exFAT-fs (sda1): Filesystem has been set read-only
Nov 21 18:03:37 usb-qubes-name kernel: blk_update_request: I/O error, dev sda, sector 10465 op 0x1:(WRITE) flags 0x100000 phys_seg 1 prio class 0
Nov 21 18:03:37 usb-qubes-name kernel: blk_update_request: I/O error, dev sda, sector 10755 op 0x1:(WRITE) flags 0x100000 phys_seg 1 prio class 0
Nov 21 18:03:37 usb-qubes-name kernel: exFAT-fs (sda1): error, failed to access to FAT (entry 0x00000004, err:-5)
Nov 21 18:03:43 usb-qubes-name kernel: exFAT-fs (sda1): error, failed to access to FAT (entry 0x00000004, err:-5)

```

**Comment by jamke** [comment]
I though it is a kernel issue, but no, on R4.0 these USB PCIe Controllers were working perfectly well with `5.16.18-2.fc25` kernel, which is rather new.
On R4.1.1 I tried `5.15.76-1.fc32` and `6.0.2-2.fc32` with the same not-working results described in the messages above.

If somebody has ideas for tests or diagnosis - please provide.

**Comment by jamke** [comment]
I tried to connect a printer that worked perfectly well with R4.0 or previous computer via the same PCI->USB Controller.
I see the printer for some time but before I am able to print something - the printer and the whole controller disconnects with the same `dead` message in `dmesg`.

So, for me Qubes OS R4.1.1 is unusable for printing or scanning too. 

Please, any ideas?

**Comment by marmarek** [comment]
Can you post output of `sudo lspci -vv` - the fragment about that usb controller? Do it both in dom0 and in sys-usb - the output will slightly differ, and some of those differences may be relevant for the issue.

BTW, there is also 6.0.8 kernel in [current-testing repository](https://www.qubes-os.org/doc/how-to-install-software-in-dom0/#testing-repositories). And just to double check - when you write about kernel version, you mean the kernel used in sys-usb, right?

**Comment by jamke** [comment]
> Can you post output of `sudo lspci -vv` - the fragment about that usb controller? Do it both in dom0 and in sys-usb - the output will slightly differ, and some of those differences may be relevant for the issue.

Here it is: https://gist.github.com/jamke/5984a672ddde2cc97a574d8586af64de



> And just to double check - when you write about kernel version, you mean the kernel used in sys-usb, right?

Right, the kernel of the HVM usb qube (set with combobox in `qubes-vm-settings`).

**Comment by marmarek** [comment]
> Here it is: https://gist.github.com/jamke/5984a672ddde2cc97a574d8586af64de

Is it (roughly) at the same time? The difference in `MSI: Enable+` and MSI: Enable-` is worrying. Can you check `/var/log/xen/console/guest-sys-usb-dm.log` if you see some related errors?
What is the dom0 kernel version?
Can you try with [permissive mode](https://www.qubes-os.org/doc/how-to-use-pci-devices/#permissive)?

**Comment by jamke** [comment]
> Is it (roughly) at the same time?

Yes, Like 5 minutes difference.

Just to be clear with what's happening: I connect USB device, e.g. flash drive to the PCI Controller and it IS accessible within the usbqube. I can do nothing and both controller and drive will be OK, no dmesg errors. I can open some small files and it's still OK. But if I copy or write something like 1MiB - the controller is disconnected with `assumed dead` message.

P.S. I will provide answers to other questions and 6.0.8 kernel test very soon.

**Comment by jamke** [comment]
> Can you check `/var/log/xen/console/guest-sys-usb-dm.log` if you see some related errors?

Maybe it's related https://gist.github.com/jamke/b8663f6554fe60d9c55df53712142f5a
Search for `00:06.0`.

> What is the dom0 kernel version?

Currently this one:
```
[user@dom0 ~]$ uname -a
Linux dom0 6.0.2-2.fc32.qubes.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Oct 21 03:09:25 CEST 2022 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by jamke** [comment]
> Can you try with [permissive mode](https://www.qubes-os.org/doc/how-to-use-pci-devices/#permissive)?

Tried, the same behavior.

**Comment by marmarek** [comment]
```
[2022-11-30 13:27:45] pcifront pci-0: device or AER driver is NULL
[2022-11-30 13:27:45] pcifront pci-0: device or AER driver is NULL
[2022-11-30 13:27:45] pcifront pci-0: device or AER driver is NULL
```
This seems to be device reporting an issue (AER is Advanced Error Reporting), but forwarding it into actual HVM isn't supported right now. I don't think it's the cause of the issue, but having that feature supported would (hopefully) give more info what went wrong...

**Comment by jamke** [comment]
Just another note - it's for sure is not a hardware malfunction issue because:
* This PCI controller is well-supported on Linux in general
* It was working on R4.0 perfectly well for years with the same way of use
* And I have two of them and tried both

**Comment by jamke** [comment]
Maybe I should try some really old kernels for this HVM qube, like ~ 4.0.0 or older?
Is there an easy way to do that in Qubes OS?

**Comment by marmarek** [comment]
another idea: try adding `pci=nomsi` to `kernelopts` of that usb qube

**Comment by jamke** [comment]
> another idea: try adding `pci=nomsi` to `kernelopts` of that usb qube

Nothing changed, dies when coping file (NOTE: I kept permissive mode in this test).

**Comment by royger** [comment]
Can you paste the output of `sudo lspci -vv` when using pci=nomsi?

Thanks.

**Comment by royger** [comment]
Also, can you boot Xen with `iommu=verbose` on the command line and paste the full output of `xl dmesg` after hitting the issue at least once?  Would be good if you could do this with a debug hypervisor.

**Comment by jamke** [comment]
> Can you paste the output of `sudo lspci -vv` when using pci=nomsi?

Here: https://gist.github.com/jamke/5669c911a127d682167597db2da0a403

**Comment by jamke** [comment]
> Also, can you boot Xen with `iommu=verbose` on the command line and paste the full output of `xl dmesg` after hitting the issue at least once? Would be good if you could do this with a debug hypervisor.

Should I keep permissive flag for this test? What kernel version do you prefer? Do you want this log to be with `pci=nomsi`?

**Comment by royger** [comment]
> > Also, can you boot Xen with `iommu=verbose` on the command line and paste the full output of `xl dmesg` after hitting the issue at least once? Would be good if you could do this with a debug hypervisor.
> 
> Should I keep permissive flag for this test? What kernel version do you prefer? Do you want this log to be with `pci=nomsi`?

Keep them is that what used to work in previous releases.  I don't care that much about the kernel. any that triggers the issue will be fine.  You can drop the pci=nomsi, as it doesn't seem to have any effect.

**Comment by jamke** [comment]
Another idea - maybe I should try to disable iommu completely inside the qube or the dom0? Can it help the testing process?

**Comment by marmarek** [comment]
Without IOMMU, PCI passthrough to HVM will not work at all

**Comment by jamke** [comment]
> Keep the permissive flag if that used to work in previous releases. I don't care that much about the kernel, any that triggers the issue will be fine. You can drop the pci=nomsi, as it doesn't seem to have any effect.

I did it. Do you want `xl dmesg` from `dom0` or `usbqube`?
Because in case of `dom0` it has not changed (`xl dmesg > file.txt` before usbqube started and after it started and issue happened are the same).

> Without IOMMU, PCI passthrough to HVM will not work at all
I see, will not try then.

**Comment by jamke** [comment]
> Also, can you boot Xen with `iommu=verbose` on the command line and paste the full output of `xl dmesg` after hitting the issue at least once? Would be good if you could do this with a debug hypervisor.

Here: https://gist.github.com/jamke/12deb6e464c499c2061cec08077980f7
I hope I've done what you expected, if not - please provide details to make it again.

@marmarek 
Is it OK: `parameter "no-real-mode" unknown!`. It was provided by Qubes OS, not me.

**Comment by royger** [comment]
> > Keep the permissive flag if that used to work in previous releases. I don't care that much about the kernel, any that triggers the issue will be fine. You can drop the pci=nomsi, as it doesn't seem to have any effect.
> 
> I did it. Do you want `xl dmesg` from `dom0` or `usbqube`? Because in case of `dom0` it has not changed (`xl dmesg > file.txt` before usbqube started and after it started and issue happened are the same).

`xl dmesg` will only be available from dom0. Can you paste it anyway, just to take a look?

Thanks.

**Comment by jamke** [comment]
> `xl dmesg` will only be available from dom0. Can you paste it anyway, just to take a look?

Yeah, the link is just above, we posted at the same moment.

**Comment by marmarek** [comment]
> Is it OK: `parameter "no-real-mode" unknown!`. It was provided by Qubes OS, not me.

Yes, that's ok

**Comment by royger** [comment]
Can you also paste the `lspci -vv` output from dom0?  So that we can know the real SBDF of the device.

**Comment by jamke** [comment]
> Can you also paste the `lspci -vv` output from dom0? So that we can know the real SBDF of the device.

You need it whole or only some devices?

**Comment by marmarek** [comment]
> > Can you post output of `sudo lspci -vv` - the fragment about that usb controller? Do it both in dom0 and in sys-usb - the output will slightly differ, and some of those differences may be relevant for the issue.
> 
> Here it is: https://gist.github.com/jamke/5984a672ddde2cc97a574d8586af64de

@royger it's here already, `05:00.0`

**Comment by marmarek** [comment]
@jamke can you post `sudo lspci -vv`  from dom0 when the issue happens (but before restarting usb qube)?

**Comment by jamke** [comment]
> @jamke can you post `sudo lspci -vv` from dom0 when the issue happens (but before restarting usb qube)?

You mean usb qube should be started, the issue should happen and before I halt it manually - I should provide `sudo lspci -vv` from `dom0`, right? Do you need only PCI controller section?

**Comment by jamke** [comment]
https://gist.github.com/jamke/c4381db09f618630919a4972a0748e68

Here it is for all 4 stages:
1) Just booted, usbqube is still down.
2) Started usbqube with PCI and flashd drive in it.
3) Run copy to trigger the issue, usbqube is still up.
4) After halting usbqube and getting PCI device back to dom0.

**Comment by jamke** [comment]
@royger  @marmarek if you need any additional information - please tell.
It's not great to have no usb qubes and no printer/scanner/mtp and etc. Especially when I have several PCIe->USB Controllers and none of them work.

**Comment by marmarek** [comment]
Do you see some kernel messages in dom0 about the time the controller stops working?

**Comment by marmarek** [comment]
So, when issue happens, those are the differences:
```
2c2
< 	Control: I/O- Mem+ BusMaster+ SpecCycle- MemWINV- VGASnoop- ParErr- Stepping- SERR- FastB2B- DisINTx-
---
> 	Control: I/O- Mem- BusMaster- SpecCycle- MemWINV- VGASnoop- ParErr- Stepping- SERR- FastB2B- DisINTx-
4d3
< 	Latency: 0, Cache Line Size: 64 bytes
6c5
< 	Region 0: Memory at 51100000 (64-bit, non-prefetchable) [size=8K]
---
> 	Region 0: Memory at 51100000 (64-bit, non-prefetchable) [virtual] [size=8K]
10,11c9,10
< 	Capabilities: [70] MSI: Enable+ Count=1/8 Maskable- 64bit+
< 		Address: 00000000fee01078  Data: 0000
---
> 	Capabilities: [70] MSI: Enable- Count=1/8 Maskable- 64bit+
> 		Address: 0000000000000000  Data: 0000
18,19c17,18
< 		DevCtl:	CorrErr+ NonFatalErr+ FatalErr+ UnsupReq+
< 			RlxdOrd- ExtTag- PhantFunc- AuxPwr- NoSnoop+
---
> 		DevCtl:	CorrErr- NonFatalErr- FatalErr- UnsupReq-
> 			RlxdOrd+ ExtTag- PhantFunc- AuxPwr- NoSnoop+
21c20
< 		DevSta:	CorrErr- NonFatalErr- FatalErr- UnsupReq- AuxPwr- TransPend-
---
> 		DevSta:	CorrErr+ NonFatalErr- FatalErr- UnsupReq+ AuxPwr- TransPend-
33c32
< 		DevCtl2: Completion Timeout: 50us to 50ms, TimeoutDis- LTR+ OBFF Disabled,
---
> 		DevCtl2: Completion Timeout: 50us to 50ms, TimeoutDis- LTR- OBFF Disabled,
42c41
< 		UESta:	DLP- SDES- TLP- FCP- CmpltTO- CmpltAbrt- UnxCmplt- RxOF- MalfTLP- ECRC- UnsupReq- ACSViol-
---
> 		UESta:	DLP- SDES- TLP- FCP- CmpltTO- CmpltAbrt- UnxCmplt- RxOF- MalfTLP+ ECRC- UnsupReq- ACSViol-
45c44
< 		CESta:	RxErr- BadTLP- BadDLLP- Rollover- Timeout- AdvNonFatalErr-
---
> 		CESta:	RxErr- BadTLP- BadDLLP- Rollover- Timeout- AdvNonFatalErr+
47c46
< 		AERCap:	First Error Pointer: 00, ECRCGenCap- ECRCGenEn- ECRCChkCap- ECRCChkEn-
---
> 		AERCap:	First Error Pointer: 12, ECRCGenCap- ECRCGenEn- ECRCChkCap- ECRCChkEn-
49c48
< 		HeaderLog: 00000000 00000000 00000000 00000000
---
> 		HeaderLog: 4a000040 00000100 05001000 ffff00ff
```

I'm not sure what `CESta: AdvNonFatalErr+` or `UESta: MalfTLP+` is, but `DevSta: UnsupReq+` or `DevSta: CorrErr+` looks interesting.
And also, MSI got disabled and the whole PCI CONTROL register got zeroed (including memory decoding and bus mastering). Such device isn't going to work, but I guess that's a fallout from the problem reported by AER, not its cause. Maybe, if AER would be properly virtualized, the driver would recover?

**Comment by marmarek** [comment]
Another idea for workaround (with rather significant security implications :/) - try switching this usb qube virt_mode to PV. IIUC AER should be correctly passed down to the driver then.

**Comment by jamke** [comment]
> Do you see some kernel messages in dom0 about the time the controller stops working?

I have this in `sudo dmesg`:
```
[48181.065658] pcieport 0000:00:1c.5: DPC: containment event, status:0x1f05 source:0x0500
[48181.065664] pcieport 0000:00:1c.5: DPC: ERR_FATAL detected
[48181.210938] pcieport 0000:00:1c.5: AER: device recovery successful
```

And related `dmesg` output inside the usbqube before and after the issue happens: 
https://gist.github.com/jamke/ddedbb51c6070aa0fcfe52dfdfaacf8e

**Comment by jamke** [comment]
> So, when issue happens, those are the differences:

Yes, I saw the differences, but cannot help here due to the lack of understanding of this part. 
`AER` is something that I see in dom0 too.

Once again, I have this controller working on R4.0 on slightly different PC. So, I can try to run R4.0 on the same (this) PC and test it, and save the logs if it will be useful.

**Comment by marmarek** [comment]
You may want to check if it's fully seated in the PCIe slot.

**Comment by jamke** [comment]
> Another idea for workaround (with rather significant security implications :/) - try switching this usb qube virt_mode to PV. IIUC AER should be correctly passed down to the driver then.

I powered off the usbqube, changed its mode to `PV` (instead of `HVM`) the behavior has not changed at all.
Both `dmesg` in dom0 and usbqube seems to be the same during issue. I also had 3 messages wth `DPC: ERR_FATAL detected` and `AER: device recovery successful` in `dom0`.

**Comment by jamke** [comment]
> You may want to check if it's fully seated in the PCIe slot.

I pressed and it clicked a but. So, I was hoping it's a slot population, but no, after reboot still the same.
And I have 2 controllers of the same model that I put in 2 different PCI slots and both does not work (die as `assumed dead`), so slot population is not a reason.

Why PV mode did not change anything? Should it have?

Why after the Qubes OS boot and before usbqube being started I see no block devices in `dom0` if I have USB flash drives inserted? Should I see them the same way I see when I put them into USB connectors of motherboard?

**Comment by jamke** [comment]
But the way, another (3rd) USB controller I have was not working even on R4.0.
Name: `USB controller: Renesas Technology Corp. uPD720201 USB 3.0 Host Controller`.

I have in `dmesg` inside usbqube for this controller:
```
[    2.566376] xhci_hcd 0000:00:07.0: failed to load firmware renesas_usb_fw.mem, fallback to ROM
[    2.567071] xhci_hcd 0000:00:07.0: xHCI Host Controller
[    2.567684] xhci_hcd 0000:00:07.0: new USB bus registered, assigned bus number 4
...
[   12.567773] xhci_hcd 0000:00:07.0: can't setup: -110
[   12.567823] xhci_hcd 0000:00:07.0: USB bus 4 deregistered
[   12.569370] xhci_hcd 0000:00:07.0: init 0000:00:07.0 fail, -110
[   12.569400] xhci_hcd: probe of 0000:00:07.0 failed with error -110
```

I was not using it on R4.0 because I had 2 working controllers. Now I would love to have at least one for scanner/printer and other stuff.

**Comment by 3hhh** [comment]
> But the way, another (3rd) USB controller I have was not working even on R4.0.
> Name: `USB controller: Renesas Technology Corp. uPD720201 USB 3.0 Host Controller`.

https://mjott.de/blog/881-renesas-usb-3-0-controllers-vs-linux/

**Comment by jamke** [comment]
> https://mjott.de/blog/881-renesas-usb-3-0-controllers-vs-linux/

Thank you, now I understand that it's easier for me to throw my `Renesas Technology Corp. uPD720201` away to the trash.

But two `NEC Corporation uPD720200` I have work perfectly well in both R4.0 and usual GNU/Linux without any proprietary firmware tricks or anything. I hope I got it work in R4.1 too, somehow.

**Comment by jamke** [comment]
I changed slots, reconnected everything and one of the PCI USB Controllers works. So, maybe it is somewhat hardware problem (defective motherboard or PCI slot(s), curved computer case preventing reliable PCI fit, defective Molex power to the card or something else).
I will investigate further and after that I will either close this issue as solved or provide more details. Thanks to everybody who tried to help me.

**Comment by jamke** [comment]
Further experiments provided new information.
1. I disassembled controllers' brackets to avoid any slot population problem and it's not about it.
2. I have 3 PCIe slots and 2 PCI-USB controllers on the motherboard and found out that in 2 of them the PCI Controller dies like described in the first post and in only one it works reliably. I'm not sure if it's a Qubes OS related issue or motherboard's, because PCI audio card works perfectly well in these 2 possibly-problem PCI slots.

Not sure what the reason of issue is and what to do then.

**Comment by brendanhoar** [comment]
Probably not helpful but: is the main board firmware (uefi/bios, etc.) up to date? If not, probably update ... or at least peruse the release notes if available.

B

**Comment by jamke** [comment]
> Probably not helpful but: is the main board firmware (uefi/bios, etc.) up to date? If not, I would probably update ... or at least peruse the release notes if available.

Thanks for advice. I was updating BIOS before on this motherboard but now I see one more update available and will indeed install it just in case. The changelog of this update is not promising though.

Another idea - to change chipset's PCI slots mode to fixed v1, v2, v3 in BIOS (by default it's `auto` there). I hope it will not disrupt anything and maybe at some mode the PCI controllers will stop dying.
But audio-card works in them with no issues with this `auto` mode, so, the issue is probably tricky, not a defected motherboard.

The next step - I will replace the motherboard with a different model and will try to run the same Qubes OS that I already have without reinstallation. I will post results here.

**Comment by jamke** [comment]
Changing Motherboard Chipset's PCI slots mode from `auto` to `v2` in BIOS maybe fixed the issue!

I will try other modes and will keep everybody posted if the issue is really solvable this way, because I never saw this solution for similar problems on forums.

**Comment by jamke** [comment]
After several tests the results for a PCIe-USB Controller (`NEC Corporation uPD720200`) and PCIe Sound card inserted in slots that are provided by motherboard's chipset (`B560`) are these:

In `BIOS` (`UEFI`) the setting `PCH PCIe Link Speed` set to:
* `Auto`  - The error `assumed dead` happens for USB Controller. Sound-card works.
* `Gen1` - USB Controller is not visible. Sound-card works.
* `Gen2` - **USB Controller works. Sound-card works.**
* `Gen3` - The error `assumed dead` happens for USB Controller. Sound-card works.

So, `Auto` means `Gen3` in my case and results in non-working state of PCIe USB Controller. Sound card is probably Gen1 and it works in all possible ways.

The issue is not solved but a workaround found:
* Change PCIe Link speed to `Gen2`. It makes USB Controller `NEC Corporation uPD720200` work reliably in chipset slots but limits `Gen3` devices if you have them.
