### ISSUE TITLE
qubes arbitrarily shut down in normal use

### ISSUE THREAD

**Issue by unman** [QubesOS/qubes-issues#7909]
### Qubes OS release
4.1 updated with testing repositories
I believe this can be seen in kernel 6.0.8, and in 5.15 etc.

### Brief summary
E.g. Certified x230 16GB RAM
On occasion, when opening a new qube other qubes are culled.
This predominantly affects qubes where the mem/maxmem have been adjusted
from standard settings, but it is not restricted to them.
(E.g. sys-firewall 400/800)

This is yet another case of "Fings aint what they used to be", and again,
restricts usability of certified hardware.
It used to be that sometimes one was unable to open a new qube because
of insufficient memory.
Now, we rarely see that, and instead other qubes are culled, presumably
to free memory.

Because of other issues with 4.1 we have already scaled back the number
of running qubes, allocated stock value to dom0, and reinstated swap.
Attempting to monitor used memory does not suggest there should be a memory issue.

### Steps to reproduce
Qubes with 8 or 9 running qubes.
Attempt to open another qube.

### Expected behavior
qube will open or will fail with "insufficient memory"
Other qubes will not be affected.

### Actual behavior
qube opens but other qubes are closed.
Work may be lost, or interrupted.

Other significant effects on dom0, and other qubes, when opening a new qube:
e.g. sound fails while other qube is started;
 display affected - window movement/desktop etc laggy or interrupted;
Many reports of freeze/crash related to qubes opening/closing.
These are all new and unwanted behaviour.

**Comment by DemiMarie** [comment]
@unman can you provide console logs from the dying qubes?  My first thought is a kernel panic but without logs I cannot know for certain.

**Comment by unman** [comment]
I have looked in the past, but (as with dom0 crash) there's nothing that
stands out to me in the logs.
I'll check again when I am back home, or when I next encounter the issue.

**Comment by andrewdavidwong** [comment]
> I'll check again when I am back home, or when I next encounter the issue.

Were you ever able to check again, or did you ever encounter the issue again, @unman?
