### ISSUE TITLE
Qubes Kali template stopped working after update

### ISSUE THREAD

**Issue by lorenzog** [QubesOS/qubes-issues#7912]
### Qubes OS release

Qubes 4.1.1 (R4.1)
Debian package for qubes-core-qrexec version `4.1.18-1+deb11u1_amd64`

### Brief summary

The Kali template was broken by the latest upgrade.
The problem appears to be with `/usr/lib/qubes/qrexec-agent`:

```
qrexec-agent[...] qrexec-agent.c:335:handle_vchan_error: Error while vchan server_init, exiting
``` 

### Steps to reproduce

1. Update kali-rolling (as per 2022-11-20)
2. qrexec will stop working, execute a console from dom0 (suggested: `qvm-prefs kali qrexec_timeout 1800`)
3. Run `/usr/lib/qubes/qrexec-agent`

Please note, the error was triggered initially by `dpkg-reconfigure qubes-core-qrexec`, with an error in the Perl script `/usr/bin/deb-systemd-invoke` on line 145 which I think is just a wrapper around `systemctl -system restart qubes-qrexec-agent.service`.

### Expected behavior

The qrexec agent starts

### Actual behavior

Qrexec doesn't start

**Comment by unman** [comment]
What is the base of this kali qube?
Where did you get it from, or did you build from source?
What steps did you take before updating?

One thing that stands out to me is that Kali is now based on
debian-12, but you are installing a qubes-core-qrexec package for
debian-11.

**Comment by lorenzog** [comment]
> What is the base of this kali qube? Where did you get it from, or did you build from source? What steps did you take before updating? One thing that stands out to me is that Kali is now based on debian-12, but you are installing a qubes-core-qrexec package for debian-11.

I am using the kali community template as per 
```
sudo qubes-dom0-update --enablerepo=qubes-templates-community-testing qubes-template-kali
```

I tried with `--action=upgrade` but it tells me that the template is already the highest version. 
Will try with `--action=reinstall` to restore functionalities, although I suspect the problem has something to do with recent Debian/Kali system upgrades.

**Comment by DemiMarie** [comment]
Try using the Debian 12 Qubes repositories.

**Comment by lorenzog** [comment]
> Try using the Debian 12 Qubes repositories.

@DemiMarie the Kali template uses Debia bullseye (11.5) repositories. Is there any reason why I should try to use Debian 12 besides troubleshooting? I know I never altered the repository source, which makes me think the problem might be systemic for the kali template.

Sources in the kali template are:
```
$ cat /etc/apt/sources.list.d/qubes-r4.list   |grep -v \#
deb [arch=amd64] https://deb.qubes-os.org/r4.1/vm bullseye main

$ cat /etc/apt/sources.list
deb https://deb.debian.org/debian bullseye main contrib non-free
deb https://deb.debian.org/debian-security bullseye-security main contrib non-free
```

 I ran `apt-get update` and no problem arose, trying `apt-get dist-upgrade` to see if it breaks again.

**Comment by lorenzog** [comment]
Using `bookworm` instead of `bullseye` seems to be working now. 
Still using the 4.2 repos is causing issues, but that's for another day.
Closing
