### ISSUE TITLE
sys-net proxy service startup failure

### ISSUE THREAD

**Issue by fullTalgoRythm** [QubesOS/qubes-issues#7920]
### Qubes OS release

4.0/4.1

### Brief summary

After adding VLANs to my sys-net configuration it appears to have broken the proxy service startup which shows approx 10 failures in a row and I think it gives up after that.

### Steps to reproduce

Presumably if you add enough VLANs to your sys-net you should see this issue.

### Expected behavior

Proxy service waits / retries as appropriate to startup correctly. Possbily also a notification message could be nice if it fails.

### Actual behavior

Proxy service fails to start as it retries too quickly. Would therefore be greatful if the service options could be adjusted to set a larger delay for retries.

**Comment by DemiMarie** [comment]
Can you post the output of `journalctl -b -u qubes-updates-proxy.service`?
