### ISSUE TITLE
Qubes Whonix Booting Issue

### ISSUE THREAD

**Issue by bluesteal** [QubesOS/qubes-issues#7925]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
R4.1

### Brief summary
whonix workstation 16 will not boot 

### Steps to reproduce
please see the following link: 
https://forum.qubes-os.org/t/vm-startup-error/14998/10

**Comment by fepitre** [comment]
This is not something actionable. An issue is not a place for referencing several problems described elsewhere. Make it self content first.
