### ISSUE TITLE
whonix workstation not booting (Existing Issue)

### ISSUE THREAD

**Issue by bluesteal** [QubesOS/qubes-issues#7928]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

R4.1 

### Brief summary
will not boot this template vm 

### Steps to reproduce
please see:
https://forum.qubes-os.org/t/vm-startup-error/14998

**Comment by marmarek** [comment]
Based on our [issue tracking guidelines](https://www.qubes-os.org/doc/issue-tracking/), this does not appear to be suitable for `qubes-issues`. We ask that you please post this on the [Qubes Forum or `qubes-users` mailing list](https://www.qubes-os.org/support/) instead. If, after reading our [issue tracking guidelines](https://www.qubes-os.org/doc/issue-tracking/), you believe we are mistaken, please leave a brief comment explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.
