### ISSUE TITLE
Keyboard and mouse input lags due to write process inside USB qube with different external PCI USB Controller attached

### ISSUE THREAD

**Issue by jamke** [QubesOS/qubes-issues#7932]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
R4.1.1.

### Brief summary
Keyboard input and mouse cursor movement is choppy and unresponsive when I write data to a flash drive connected to a usb qube via external PCI-USB Controller.
Keyboard and mouse is connected to USB Controller that is connected to `dom0`.
I had no such problem on R4.0 on a different PC with the same external PCI-USB Controller.

### Steps to reproduce
1. Start qube with PCI USB Controller attached. In my case: `USB controller: NEC Corporation uPD720200 USB 3.0 Host Controller`
2. Start some writing process for a flash drive connected to the controller. In my case: `sudo dd if=/dev/zero of=/dev/sda  status=progress conv=fsync`

### Expected behavior
Keyboard input and mouse movement are not affected by the write process in USB qube.

### Actual behavior
Keyboard input is not usable. Example of typing `Test message that is typed in during copy process`:
`T ssage thati typein durrrrrring copppppy proooccess`.
**Entering the lock password in `xscreensaver` becomes almost impossible.**
Mouse is very choppy (#7893 may be related).

### More info
1. I had this controller on older PC and used it in the same way and had issue like that.
2. Stopping `dd` returns keyboard typing and mouse movement back to normal.

**Comment by jamke** [comment]
Even more info:

1. The issue #7893 is not the same, because in it I tried to shut down all appvms and move movements were still choppy even with only dom0 running without any activity. And it was not involving USB controllers at all.

2. If I connect the same flash drive to `dom0`, attach this device dom0:sda to the same usb qube and run the same `dd` command there - I have no input lags for both mouse and keyboard, everything is fine.

**Comment by loneicewolf** [comment]
I have also noticed this (Not exactly the write proc. Though.) But, I have been trying to re inst. Qubes now in many diff. ways, using uefi and non uefi, burning on windows, burning qubes on linux instead, etc. etc. Still persist. will come back if I find any clue/progress
