### ISSUE TITLE
Graphical glitch install qubes 4.1.1 on L380 Yoga

### ISSUE THREAD

**Issue by sucrecacao** [QubesOS/qubes-issues#7933]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

Qubes 4.1.1

### Brief summary

Glitch appear when the screen need, there look like thoses: 
![image](https://user-images.githubusercontent.com/55893070/205890773-cd960d60-d9cd-4ffc-b4a6-c48522442eda.png)

There also appear on boot, when asking decryption password, as reported on https://github.com/QubesOS/qubes-issues/issues/7350 ( at the different that the issue persist after )

### Steps to reproduce

 on a lenovo L380 Yoga i5
16g RAM , Samsung EVO 980 2TB
Install Qubes 4.1.1 on legacy mode, with windows dual boot

### Expected behavior

No glitch appear

### Actual behavior

Glitches ( small rectangle ) appear, 
There most noticeable when the pixel switch to a color highly contrasting with the previous color ( from black to white, or white to black )

**Comment by sucrecacao** [comment]
Does rolling back to 4.0 could solve the issue?

**Comment by marmarek** [comment]
This looks to be same as #4782 , there are some workaround proposed until the actual issue get fixed.

**Comment by sucrecacao** [comment]
Thanks @marmarek !

In deed https://github.com/QubesOS/qubes-issues/issues/4782#issuecomment-975920223 solved the issue for me!

But after pretty long research I was not able to find this issue, and I'm surprised that the issue is actually documented!

In my opinion,  [the GUI trouble shooting page ](https://github.com/QubesOS/qubes-doc/blob/master/user/troubleshooting/gui-troubleshooting.md)  should have a link pointing to [The specific intel driver troubleshooting page ](https://github.com/Qubes-Community/Contents/blob/master/docs/troubleshooting/intel-igfx-troubleshooting.md) . Would you accept a PR?

**Comment by andrewdavidwong** [comment]
> This looks to be same as #4782 , there are some workaround proposed until the actual issue get fixed.

This appears to be a [duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If anyone believes this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.
