### ISSUE TITLE
System Tools, Mouse and Touchpad, Reverse scroll direction has no effect

### ISSUE THREAD

**Issue by caluml** [QubesOS/qubes-issues#7944]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

$ cat /etc/qubes-release
Qubes release 4.1.1 (R4.1)

### Brief summary

System Tools, Mouse and Touchpad, Reverse scroll direction has no effect

### Steps to reproduce

Toggle the scroll direction

### Expected behavior

Scroll direction should toggle

### Actual behavior

Scroll direction doesn't toggle

### Additional information

This worked fine before I reinstalled to update to 4.1.

**Comment by ehanoc** [comment]
Confirm. Have the same.

**Comment by timeyyy** [comment]
Confirm. Have the same.

**Comment by caluml** [comment]
Affects 4.2
