### ISSUE TITLE
dom0 Testing Update Has Broken GUI

### ISSUE THREAD

**Issue by quantumpacket** [QubesOS/qubes-issues#7951]
### Qubes OS release

4.1.1

### Brief summary

I use the _"Testing updates"_ repository. I performed an update last night and once it had updated `dom0` problems started. First, the GUI locked up, where I was unable to click or move any windows. The system was not frozen as the mouse could move, and the updater was still running in the background and producing notifications. I was able to invoke the shutdown prompt and shutdown normally.

After doing a reboot my Xfce panel was missing my additional workspaces in the workspace switcher. My wallpaper was reset as well. The panel settings I don't believe were completely reset as my sensors graph was still there and all other configurations were still intact as far as I could tell.

The worst was yet to come. All windows no longer have their window borders. So it's missing the colored title bar, close button, etc. In addition, none of the open applications appear in the the Xfce panel, so even right clicking from there won't allow me to close or minimize a window.

I tried to do something as simple as change the wallpaper, but when I click on _"apply to all workspaces"_ the Xfce panel crashes. Even trying to add an additional workspace does not work, as the '+' button is not clickable. It seems some windows components are no longer clickable or causing issues.

Whatever updates came within the past 24-48 hours has caused really bad breakage.

### Steps to reproduce

1. Use Xfce as desktop environment.
2. Choose the _"Testing updates"_ repository.
3. Run a dom0 update.

### Expected behavior

dom0 update should complete with possible minor issues as it is the testing repository.

### Actual behavior

Multiple issues, mainly with GUI.

**Comment by quantumpacket** [comment]
At first I couldn't run that command as the terminal window would not take input focus for the text cursor. It's one of the GUI items that is not able to take focus. Another example is if I open up the browser (Firefox derivative) the master password prompt dialog window shows up and I can focus the window, but cannot type in the input field. Rebooting allowing me to type in in the terminal. I've rebooted multiple times and the focus seems to be erratic as if something is stealing the focus so I can't click on certain items at certain times.

For `qubes-db` I have `4.1.15-1` while `core-qubesdb` (which I assume is the same package) is `4.1.15`

**Comment by marmarek** [comment]
Haven't you ran out of disk space in dom0?

**Comment by quantumpacket** [comment]
Doesn't appear to be the case. Unless I'm reading this wrong. Btw, why would I have what seems to be a more recent package version of `qubes-db` than what was on the above linked list?

```sh
$ df -h
Filesystem                   Size  Used Avail Use% Mounted on
devtmpfs                     1.9G     0  1.9G   0% /dev
tmpfs                        2.0G     0  2.0G   0% /dev/shm
tmpfs                        2.0G  2.0M  2.0G   1% /run
/dev/mapper/qubes_dom0-root   20G  7.2G   12G  39% /
tmpfs                        2.0G  8.0K  2.0G   1% /tmp
xenstore                     2.0G  344K  2.0G   1% /var/lib/xenstored
/dev/nvme0n1p1               974M  296M  611M  33% /boot
tmpfs                        390M   24K  390M   1% /run/user/1000
```

```sh
$ sudo lvs | head -n 4
  LV                                                 VG         Attr       LSize   Pool      Origin                                             Data%  Meta%  Move Log Cpy%Sync Convert
  root                                               qubes_dom0 Vwi-aotz--  20.00g root-pool                                                    37.82                                  
  root-pool                                          qubes_dom0 twi-aotz--  24.00g                                                              31.52  22.75                           
  swap                                               qubes_dom0 -wi-ao----  <3.95g                           
```

**Comment by marmarek** [comment]
> For `qubes-db` I have `4.1.15-1`, while the above listed `core-qubesdb` (which I assume is the same package) is `4.1.15`

That's the same version, `-1` part is optional (sometimes it's skipped when it's `-1`)

**Comment by quantumpacket** [comment]
5.15.81-1.fc32.qubes.x86_64

**Comment by quantumpacket** [comment]
**SOLVED!** After the `dom0` update `xfwm4` either crashed or failed to restart, which is what caused the GUI to lockup. When I performed a restart from the Xfce menu it saved the current `xfwm4` state for that session. So all login sessions from then on would not have the window manager running. I started the window manager from terminal and restarted to saved the session and now all is working again as normal.

@andrewdavidwong Should we keep this open to determine why the window manager did not restart or crashed after the recent update? It may happen to other users when upgrading to these changes.

**Comment by andrewdavidwong** [comment]
> @andrewdavidwong Should we keep this open to determine why the window manager did not restart or crashed after the recent update? It may happen to other users when upgrading to these changes.

Let's leave it up to the devs to decide whether there's anything actionable here on the Qubes side (and hence whether to keep this issue open).

**Comment by quantumpacket** [comment]
Closing as changes have been available for +4months, and no reports of the same issue.
