### ISSUE TITLE
sys-gui-gpu & sys-usb HVM autostart race condition fails

### ISSUE THREAD

**Issue by ZYousef** [QubesOS/qubes-issues#7954]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
QR4.1

### Brief summary

When having sys-gui-gpu and sys-usb set to start automatically they endup crashing 20% of the times.

### Steps to reproduce
set both sys-usb & sys-gui-gpu autostart to true.
set sys-usb target to sys-gui-gpu (/etc/qubes/input-proxy-target in dom0)
try to boot up into sys-gui-gpu

### Expected behavior

The guivm starts up and has access to the keyboard & mouse from sys-usb

### Actual behavior
20% of the time the system fails when running AppVMs startup sequence. 
Sometimes the guivm runs without access to usbvm keyboard or mouse, deeming it unusable. 

Note: Currently if disable the qubes-vm@sys-usb service it works fine most of the time, but takes a much longer time to fully boot up.

**Comment by marmarek** [comment]
What if you setup a ordering dependency between those two?
You can do this by creating `/etc/systemd/system/qubes-vm@sys-usb.service.d/30_order.conf` with:
```
[Service]
After=qubes-vm@sys-gui-gpu.service
```

**Comment by ZYousef** [comment]
Thanks! this works fine. If guivm is available the usbvm should install this service instead

> What if you setup a ordering dependency between those two? You can do this by creating `/etc/systemd/system/qubes-vm@sys-usb.service.d/30_order.conf` with:
> 
> ```
> [Service]
> After=qubes-vm@sys-gui-gpu.service
> ```
