### ISSUE TITLE
Utilize memory hotplug to add VM memory by qmemman

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#7956]
(...)

Which brings an idea that perhaps we should change how we start VMs:
 - alternative to consider: start with `maxmem==memory` (400M) and use memory hotplug when more memory is needed

This would require changes to libvirt config (easy) and qmemman (possibly less easy). The current approach is used because memory hotplug used to be unstable, but I think that isn't the case anymore for a long time already.

_Originally posted by @marmarek in https://github.com/QubesOS/qubes-issues/issues/7023#issuecomment-954265370_

**Comment by DemiMarie** [comment]
@marmarek does `memory_hotplug.memmap_on_memory=1` on the kernel command line allow all 4GB to be used?

**Comment by marmarek** [comment]
As a more context, this should also speed up VM startup significantly, for several reasons:
 - it would no longer need to balloon down at the start (this alone can take few seconds)
 - less overhead for memory accounting of memory not actually usable (initially) - will leave more memory for the userspace
 - less memory to clear on boot (with `init_on_free=1 init_on_alloc=1` by default now)
