### ISSUE TITLE
sys-usb Suddenly Stopped Working:  qrexec-daemon.c:135sigchld_parent_handler: Connection to the VM failed

### ISSUE THREAD

**Issue by BawdyAnarchist** [QubesOS/qubes-issues#7961]
### Qubes OS release
4.1.1 
5.15.81-1

### Brief summary
sys-usb stopped working for no apparent reason, and I have no clue why. It was working one moment when I sent my Pixel to a VM, and then I tried to switch sys-usb template to a debian template instead, and then this happened.

`qrexec-daemon[14929]: qrexec-daemon.c:135sigchld_parent_handler: Connection to the VM failed`

I tried to detach and re-attached the USB device. 

`qvm-pci detach sys-usb dom0:00_14.0`
`qvm-pci attach sys-usb dom0:00_14.0 --persistent -o no-strict-reset=true -o permissive=true`

And I rebooted. Same error.  It appears to boot up sys-usb, the light turns green, then the error message pops up. I tried to start from terminal qvm-start -v sys-usb and it gave no additional help.

### Expected behavior
I have stopped expecting Qubes to not break in random weird ways. 

### Actual behavior
See above

**Comment by hast0011** [comment]
I have a similar error. It is related to the memory setting somehow. I was increasing memory setting for the vm from 2 GB to 4 GB. Then the error appeared - swiching back the memory setting and it runs fine. However, I'm using a fedora template 36.

**Comment by BawdyAnarchist** [comment]
Problem solved. It was required to:
1. `qvm-pci detach sys-usb <DEVICE>`    
2. `qvm-remove sys-usb`    
3. `REBOOT`  
4. `sudo qubesctl state.sls qvm.sys-usb`   ## The fast way to create a new sys-usb
5. `REBOOT` again    

Worked fine after that. Can close.
