### ISSUE TITLE
installing qubes-repo-contrib with salt and pkg.latest results in UnboundLocalError

### ISSUE THREAD

**Issue by deadc0de6** [QubesOS/qubes-issues#7962]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

Qubes 4.1

### Brief summary

Trying to install `qubes-repo-contrib` using salt and `pkg.latest`
```
qubes-repo-contrib:
  pkg.latest:
    - name: qubes-repo-contrib
```

results in following python issue
```
          ID: qubes-repo-contrib
    Function: pkg.latest
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python3.8/site-packages/salt/state.py", line 2153, in call
                  ret = self.states[cdata["full"]](
                File "/usr/lib/python3.8/site-packages/salt/loader.py", line 2087, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python3.8/site-packages/salt/states/pkg.py", line 2668, in latest
                  avail = __salt__["pkg.latest_version"](
                File "/var/cache/salt/minion/extmods/modules/qubes_dom0_update.py", line 598, in latest_version
                  for pkg in (x for x in updates if x.name == name):
              UnboundLocalError: local variable 'updates' referenced before assignment
```

Using `pkg.installed` instead of `pkg.latest` seems to work though.

Declaring `updates` before [this if](https://github.com/QubesOS/qubes-mgmt-salt-dom0-update/blob/main/_modules/qubes_dom0_update.py#L540) would probably solve the issue but I'm not sure the implications for the rest.

**Comment by unman** [comment]
pkg.latest works for me without error.
I used the state file you instanced.

what versions of the salt tools do you have?
