### ISSUE TITLE
building archtemplates invalid gpg key

### ISSUE THREAD

**Issue by loeken** [QubesOS/qubes-issues#7963]
### Qubes OS release
Qubes 4.1.1 (R4.1)

### Brief summary
followed instructions to build arch template ( https://github.com/Qubes-Community/Contents/blob/master/docs/building/building-archlinux-template.md ). 

might be due to missing pacman-key --init ( https://bugs.archlinux.org/task/76855 )

### Steps to reproduce
clone qubes builder repo and follow the arch community build instructions it seems to fail during the 
```
make vmm-xen-vm
```
phase

### Actual behavior
```
[user@build-archlinux qubes-builder]$ make qubes-vm
Currently installed dependencies:
createrepo_c-0.20.1-1.fc36.x86_64
createrepo_c-0.20.1-1.fc36.x86_64
debootstrap-1.0.127-1.fc36.noarch
dialog-1.3-41.20220117.fc36.x86_64
dpkg-dev-1.21.9-1.fc36.noarch
git-2.38.1-1.fc36.x86_64
perl-Digest-MD5-2.58-479.fc36.x86_64
perl-Digest-SHA-6.03-1.fc36.x86_64
python3-sh-1.14.2-4.fc36.noarch
rpm-build-4.17.1-3.fc36.x86_64
rpmdevtools-9.6-1.fc36.noarch
systemd-container-250.9-1.fc36.x86_64
--> Archlinux preparing build chroot environment
--> Archlinux prepare-chroot-builder
  --> Installing archlinux build root:
--> Archlinux prepare-chroot-base
  --> Bootstrap chroot environment may not exist, calling 00_prepare.sh...
--> Archlinux 00_prepare.sh
--2023-01-01 13:22:48--  https://mirrors.edge.kernel.org/archlinux/iso/latest/sha256sums.txt
Resolving mirrors.edge.kernel.org (mirrors.edge.kernel.org)... 147.75.80.249, 2604:1380:4601:e00::3
Connecting to mirrors.edge.kernel.org (mirrors.edge.kernel.org)|147.75.80.249|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 396 [text/plain]
Saving to: ‘STDOUT’

-                        100%[==================================>]     396  --.-KB/s    in 0s      

2023-01-01 13:22:48 (29.6 MB/s) - written to stdout [396/396]

  --> Downloading Archlinux bootstrap tarball (v)...
--2023-01-01 13:22:48--  https://mirrors.edge.kernel.org/archlinux/iso/latest/archlinux-bootstrap-2023.01.01-x86_64.tar.gz
Resolving mirrors.edge.kernel.org (mirrors.edge.kernel.org)... 147.75.80.249, 2604:1380:4601:e00::3
Connecting to mirrors.edge.kernel.org (mirrors.edge.kernel.org)|147.75.80.249|:443... connected.
HTTP request sent, awaiting response... 304 Not Modified
File ‘/home/user/qubes-builder/cache/archlinux/archlinux-bootstrap-2023.01.01-x86_64.tar.gz’ not modified on server. Omitting download.

--2023-01-01 13:22:48--  https://mirrors.edge.kernel.org/archlinux/iso/latest/archlinux-bootstrap-2023.01.01-x86_64.tar.gz.sig
Resolving mirrors.edge.kernel.org (mirrors.edge.kernel.org)... 147.75.80.249, 2604:1380:4601:e00::3
Connecting to mirrors.edge.kernel.org (mirrors.edge.kernel.org)|147.75.80.249|:443... connected.
HTTP request sent, awaiting response... 304 Not Modified
File ‘/home/user/qubes-builder/cache/archlinux/archlinux-bootstrap-2023.01.01-x86_64.tar.gz.sig’ not modified on server. Omitting download.

  --> Preparing GnuPG to verify tarball...
gpg: Note: third-party key signatures using the SHA1 algorithm are rejected
gpg: (use option "--allow-weak-key-signatures" to override)
gpg: key 3348882F6AC6A4C2: 1 bad signature
gpg: key 3348882F6AC6A4C2: "Pierre Schmitz (Arch Linux Master Key) <pierre@master-key.archlinux.org>" not changed
gpg: key 5184252D824B18E8: 1 signature not checked due to a missing key
gpg: key 5184252D824B18E8: "Thomas Bächler (Arch Linux Master Key) <thomas@master-key.archlinux.org>" not changed
gpg: key 7EFD567D4C7EA887: 1 signature not checked due to a missing key
gpg: key 7EFD567D4C7EA887: "Ionut Biru (Arch Linux Master Key) <ionut@master-key.archlinux.org>" not changed
gpg: key BA1DFB64FFF979E7: 4 signatures not checked due to missing keys
gpg: key BA1DFB64FFF979E7: "Allan McRae (Arch Linux Master Key) <allan@master-key.archlinux.org>" not changed
gpg: key A04F9397CDFD6BB0: 2 signatures not checked due to missing keys
gpg: key A04F9397CDFD6BB0: "Dan McGee (Arch Linux Master Key) <dan@master-key.archlinux.org>" not changed
gpg: key 7F2D434B9741E8AC: 9 signatures not checked due to missing keys
gpg: key 7F2D434B9741E8AC: 5 bad signatures
gpg: key 7F2D434B9741E8AC: "Pierre Schmitz <pierre@archlinux.de>" not changed
gpg: Total number processed: 6
gpg:              unchanged: 6
  --> Verifying tarball...
gpg: Signature made Sun Jan  1 10:40:34 2023 EST
gpg:                using EDDSA key 3E80CA1A8B89F69CBA57D98A76A5EF9054449A5C
gpg:                issuer "pierre@archlinux.org"
gpg: Can't check signature: No public key
  --> Unbinding INSTALLDIR...
umount: /home/user/qubes-builder/cache/archlinux/bootstrap/mnt: no mount point specified.
make[1]: *** [/home/user/qubes-builder/qubes-src/builder-archlinux/Makefile.archlinux:88: /home/user/qubes-builder/chroot-vm-archlinux/home/user/.prepared_base] Error 1
make: *** [Makefile:265: core-vchan-xen-vm] Error 1
```

**Comment by loeken** [comment]
i fixed it by adding the following into qubes-src/builder-archlinux/scripts/00_prepare.sh
```
echo "  --> Preparing GnuPG to verify tarball..."
curl -LO 'https://archlinux.org/iso/latest/archlinux-bootstrap-x86_64.tar.gz.sig'
gpg --keyserver keyserver.ubuntu.com --keyserver-options auto-key-retrieve --verify archlinux-bootstrap-x86_64.tar.gz.sig
```

**Comment by loeken** [comment]
i fixed it by adding the following into qubes-src/builder-archlinux/scripts/00_prepare.sh
after the line 24 ( echo "  --> Preparing GnuPG to verify tarball..." )
```
curl -LO 'https://archlinux.org/iso/latest/archlinux-bootstrap-x86_64.tar.gz.sig'
gpg --keyserver keyserver.ubuntu.com --keyserver-options auto-key-retrieve --verify archlinux-bootstrap-x86_64.tar.gz.sig
```

**Comment by loeken** [comment]
i fixed it by importing the key in question:
```
wget -N -P "$CACHEDIR" "https://pierre-schmitz.com/wp-content/uploads/pierre-packager-key.asc"
gpg --keyring "${CACHEDIR}/gpghome/pubring.gpg" --import "${CACHEDIR}/pierre-packager-key.asc" || exit
```

by editing the file qubes-src/builder-archlinux/scripts/00_prepare.sh

**Comment by na--** [comment]
I hit the same issue, but I am a bit leery from importing some key from the internet, even if the domain seems legit :sweat_smile: I temporarily masked the issue by just using last month's Archlinux bootstrap .iso from [here](https://mirrors.edge.kernel.org/archlinux/iso/2022.12.01/), by manually modifying this [line in builder-archlinux](https://github.com/QubesOS/qubes-builder-archlinux/blob/f735eecac93d8d4b7fe3c9b59350156f04db79a8/scripts/00_prepare.sh#L14):
```diff
-BOOTSTRAP_URL="${ARCHLINUX_SRC_PREFIX}/iso/latest/${BOOTSTRAP_TARBALL}"
+BOOTSTRAP_URL="https://mirrors.edge.kernel.org/archlinux/iso/2022.12.01/archlinux-2022.12.01-x86_64.iso"
```

Not ideal and more time-consuming to update all of the packages, but it worked well enough and seemed safer than importing some new key.

This key, `3E80CA1A8B89F69CBA57D98A76A5EF9054449A5C`, also appears in https://archlinux.org/master-keys/, but not where I'd expect to see it :confused: It is listed as "Owner's Signing Key" for Pierre Schmitz. I don't know how exactly Arch handle these things, but https://github.com/QubesOS/qubes-builder-archlinux/blob/main/keys/archlinux-master-keys.asc was last updated 8 years ago, so it might be time to update it :sweat_smile:

**Comment by na--** [comment]
That is the PR that addresses the issue, so I think the issue should be closed after it (or something like it) is merged, right?

**Comment by andrewdavidwong** [comment]
> That is the PR that addresses the issue, so I think the issue should be closed after it (or something like it) is merged, right?

That sounds right.

**Comment by andrewdavidwong** [comment]
@loeken, please stop closing this issue without a good reason.

**Comment by unman** [comment]
I have asked the arch folk whether this is a mistake - it looks to me as
if the wrong signing key may have been used, in which case we should not
make changes to accommodate it.

**Comment by fahrstuhl** [comment]
> I hit the same issue, but I am a bit leery from importing some key from the internet, even if the domain seems legit sweat_smile I temporarily masked the issue by just using last month's Archlinux bootstrap .iso from [here](https://mirrors.edge.kernel.org/archlinux/iso/2022.12.01/), by manually modifying [these lines in builder-archlinux](https://github.com/QubesOS/qubes-builder-archlinux/blob/f735eecac93d8d4b7fe3c9b59350156f04db79a8/scripts/00_prepare.sh#L12-L14):
> 
> ```diff
> -BOOTSTRAP_TARBALL=$(wget -O- "$ARCHLINUX_SRC_PREFIX"/iso/latest/sha256sums.txt | grep -o "archlinux-bootstrap-[0-9.]*-x86_64.tar.gz")
> +BOOTSTRAP_TARBALL="archlinux-bootstrap-2022.12.01-x86_64.tar.gz"
>  
> -BOOTSTRAP_URL="${ARCHLINUX_SRC_PREFIX}/iso/latest/${BOOTSTRAP_TARBALL}"
> +BOOTSTRAP_URL="${ARCHLINUX_SRC_PREFIX}/iso/2022.12.01/${BOOTSTRAP_TARBALL}"
> ```

Thank you, your approach worked for me! And it made more sense to wait for a response by the Arch team what went wrong here. I had to get the tarball from the Arch Linux archives though, so I modified an additional line in 00_prepare.sh:

```diff
-ARCHLINUX_SRC_PREFIX="${ARCHLINUX_SRC_PREFIX:-https://mirrors.edge.kernel.org/archlinux}"
+ARCHLINUX_SRC_PREFIX="${ARCHLINUX_SRC_PREFIX:-https://archive.archlinux.org}"
```
