### ISSUE TITLE
No sound on fresh Qubes OS. 

### ISSUE THREAD

**Issue by im7mortal** [QubesOS/qubes-issues#7966]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

Qubes 4.1.1

### Brief summary

I didn't have a sound after I installed Qubes OS. I reinstalled it 4 times. At most first time I had sound after some random manipulations. But because of other problems I had to reinstall it. I've never remembered what I have done at first set up.
I did many tries to get a sound. I did everything mentioned from #7653 and some other issues which now I don't recall.

**Comment by im7mortal** [comment]
Suddenly it started to work after I toogled "Play HiFi quality music" . I toogled it back and it still worked. So I have no idea what happened but It can be solution for some body. 

Just FYI . I toogled many other options in all setting GUIs. I switched input/output sources infinite ammount of times

![20230103_194816](https://user-images.githubusercontent.com/5336231/210403444-558098ea-fb25-42f6-ae23-5d0cbaf07857.jpg)

**Comment by im7mortal** [comment]
As I only restored the sound. I was harry to be happy. There is a problem with quality of sound when "Volume control" GUI is off.
Very weird. I will post changes later

**Comment by na--** [comment]
There already is an issue about the distorted sound when "Volume Control" (`pavucontrol`) is closed, see  https://github.com/QubesOS/qubes-issues/issues/7634#issuecomment-1200157928

**Comment by andrewdavidwong** [comment]
Some more information about your hardware setup may be useful to the devs in diagnosing this.

**Comment by im7mortal** [comment]
# 1 Start system

System doesn't have sound till I switch off and switch on "Profile"

I tried to change many different options but only this one give result

https://user-images.githubusercontent.com/5336231/211165360-2dbf28cb-c990-4993-9d6d-c3b26cc494a1.mp4

# 2 Sound distortions

With **Audio mixer** on, I have no problems but when I close it. I start to have many sound distortions. If I open it again then the distortions disappear


https://user-images.githubusercontent.com/5336231/211165469-586b851c-27e5-4239-9736-24399b5ca80c.mp4


# 3 Hardware 

There is my [HCL](https://forum.qubes-os.org/t/razer-book-13-2020-rz09-0357x/15751)
