### ISSUE TITLE
Qubes won't resume from suspend

### ISSUE THREAD

**Issue by BenjaminMickler** [QubesOS/qubes-issues#7968]
### Qubes OS release
4.1.1

### Brief summary
I am unable to resume my computer after suspending it. I have an installation on an external SSD, plugged in with USB. I have a Dell Inspiron 3185. I upgraded from 4GB to 16GB RAM.

### Steps to reproduce
1. Boot Qubes OS.
2. Suspend via username in top right corner of panel

### Expected behavior
The computer should lock and suspend, then resume when I close/open the lid or press the power button.

### Actual behavior
The computer locks and suspends a few seconds later. When I press the power button the first time, the light on the SSD remains off but I can hear a quiet clicking noise from the computer (no HDD inside). The screen remains off. I wait for about 2 minutes then try pressing the power button again. After the second press the clicking noise stops and the screen remains blank. When I press the power button for the third time, the computer boots.

**Comment by BenjaminMickler** [comment]
I updated my BIOS and enabled the firmware TPM. The first time I tried to suspend it failed ([log.txt](https://github.com/QubesOS/qubes-issues/files/10341236/log.txt)). The second time it suspended and when I pressed the power button the first time the screen briefly flickered.

**Comment by marmarek** [comment]
In the log I see `Domain 'sys-net': qrexec not connected` error. Was your sys-net still starting at this time, or is it broken for some reason? What if you wait some more after system startup and only then attempt to suspend?

**Comment by BenjaminMickler** [comment]
sys-net was probably still starting

**Comment by BenjaminMickler** [comment]
I have since reinstalled Qubes OS and am still getting the same problem (crashes when I try to resume after suspending). I booted from the external SSD on another computer and suspending works just fine. I have tried adding the `mem_sleep_default=deep` kernel option and it does nothing.

**Comment by BenjaminMickler** [comment]
The ability to suspend my laptop is critical for me as I am at school and it is unrealistic to shut it down between classes. I'm going to use Fedora for the time being because it seems that this problem is not quick or easy to solve and you don't have much time. I'm happy to help you solve this issue if you get around to it and if the problem is fixed I would love to make QubesOS my daily driver.
