### ISSUE TITLE
Ubuntu Focal build fails

### ISSUE THREAD

**Issue by Rot127** [QubesOS/qubes-issues#7973]
### Qubes OS release

R 4.1

### Brief summary

The Ubuntu Focal template build fails with:

```
....
Removing 'local diversion of /sbin/initctl to /sbin/initctl.distrib'
INFO: Attempting to kill any processes still running in '/home/user/qubes-builder/qubes-src/linux-template-builder/mnt' before un-mounting
INFO: umount /home/user/qubes-builder/qubes-src/linux-template-builder/mnt/sys
INFO: Attempting to kill any processes still running in '/home/user/qubes-builder/qubes-src/linux-template-builder/mnt' before un-mounting
INFO: umount /home/user/qubes-builder/qubes-src/linux-template-builder/mnt/run
make[1]: *** [Makefile:69: rootimg-build] Error 1
```

### Steps to reproduce

- Follow https://github.com/Qubes-Community/Contents/blob/master/docs/building/building-archlinux-template.md
- In `make template` step the build fails.

### Expected behavior

The build succeeds.

### Actual behavior

`make[1]: *** [Makefile:69: rootimg-build] Error 1`

**Comment by GammaSQ** [comment]
Same issue, tried this with 3 fresh VMs now. There isn't any information the logs or stdout as far as I can tell. Happy to look at whatever logs may be helpful.

in the setup script, there are two options for ubuntu, `focal` and `focal+desktop`. I didn't find any mention what the `+desktop` part was, so I only tried to build `focal`.

build-VM has 400-4000MB memory, 30GB storage, 2vcpus

The last few lines in `build-logs template-focal.log`:

```
[.... other packages that are already newest version]
xauth is already the newest version (1:1.1-0ubuntu1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Removing 'local diversion of /sbin/initctl to /sbin/initctl.distrib'
INFO: Attempting to kill any processes still running in '/home/user/qubes-builder/qubes-src/linux-template-builder/mnt' before un-mounting
INFO: umount /home/user/qubes-builder/qubes-src/linux-template-builder/mnt/sys
INFO: Attempting to kill any processes still running in '/home/user/qubes-builder/qubes-src/linux-template-builder/mnt' before un-mounting
INFO: umount /home/user/qubes-builder/qubes-src/linux-template-builder/mnt/run
make[1]: *** [Makefile:69: rootimg-build] Error 1
```

**Comment by GammaSQ** [comment]
The PR didn't change the main problem - Ubuntu build still fails. Not sure if I should open an new Issue for this? Build fails with:

```
E: Package 'linux-image-amd64' has no installation candidate
Removing 'local diversion of /sbin/initctl to /sbin/initctl.distrib'
INFO: Attempting to kill any processes still running in '/home/user/qubes-builder/qubes-src/linux-template-builder/mnt' before un-mounting
INFO: umount /home/user/qubes-builder/qubes-src/linux-template-builder/mnt/tmp/qubes_repo
INFO: Attempting to kill any processes still running in '/home/user/qubes-builder/qubes-src/linux-template-builder/mnt' before un-mounting
INFO: umount /home/user/qubes-builder/qubes-src/linux-template-builder/mnt/sys
make[1]: *** [Makefile:70: rootimg-build] Error 100
```

**Comment by unman** [comment]
Builds for me - I'll try to see what this problem is.

**Comment by unman** [comment]
The PR fixed the main problem,but introduced a new one.
You can fix it iright now by editing template_qubuntu/vars.sh, line 57 and changing
linux-image-amd64 to linux-image-generic.
PR on way

**Comment by GammaSQ** [comment]
Thanks for the fast response and keeping the build-process up to date! Can confirm build completes.

**Comment by andrewdavidwong** [comment]
> The PR fixed the main problem,but introduced a new one.

Reopening this issue due to the new problem.
