### ISSUE TITLE
Bad error message when failing to create a reflink pool

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#7981]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

R4.1

### Brief summary

Bad error message when failing to create a reflink pool.  Note that `/mnt/test` is an empty mount point.

```
[user@dom0 ~]$ qvm-pool add --verbose --option dir_path=/mnt/test --option revisions_to_keep=1 test_reflink file_reflink
qvm-pool: error: Failed to add pool test-reflink: Got empty response from qubesd. See journalctl in dom0 for details.
```

The dom0 journal contains:

```
permission denied for call b'admin.pool.Add+b'file_reflink' (b'dom0' → b'dom0') with payload of 37 bytes
```

I probably botched the call somehow, but (a) this is not a helpful error message and (b) dom0 can do anything, so “permission denied” is clearly not the actual problem.

### Steps to reproduce

Run `qvm-pool add --verbose --option dir_path=/mnt/test --option revisions_to_keep=1 test_reflink file_reflink` in dom0.

### Expected behavior

Either success or a helpful error message.

### Actual behavior

A bogus error message.

**Comment by rustybird** [comment]
> ### Steps to reproduce
> 
> Run `qvm-pool add --verbose --option dir_path=/mnt/test --option revisions_to_keep=1 test_reflink file_reflink` in dom0.

Permission denied comes from https://github.com/QubesOS/qubes-core-admin/blob/v4.1.30/qubes/api/admin.py#L685 (because the driver name is  `file-reflink` with a dash).
