### ISSUE TITLE
Black screen after full disk description after editing sys-usb settings

### ISSUE THREAD

**Issue by joeitu** [QubesOS/qubes-issues#7995]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

I think it is latest

### Brief summary

Trying to make an ThinkPad USB-C dock station work with my L380 ThinkPad laptop ( running qubes ), I have edited the sys-usb setting. 
After adding all the available devices to the sys-usb setting and click apply, qubes shot-down directly. 
Now it boot correctly, but after decrypting my disk I get a black screen instead of the login screen 

### Steps to reproduce
Connect a USB-C ThinkPad dock to a L380 ThinkPad ( not sure if relevant ) 
Shut down sys-usb VM 
Right-click on sys-usb VM and open `Settings`
Go to the `application` tab
select all the devices on the left side panel and click on the `>` button to add them to the right panel
click `apply`

### Expected behavior

Qubes show me a error or keep running normally

### Actual behavior

Qubes shut down after clicking the 'apply' button
On boot, after I enter my full disk encryption password and once the decryption loading is finished, Qubes show me a black screen instead of a login screen.

**Comment by andrewdavidwong** [comment]
@marmarek, is there anything actionable for the Qubes devs here? If not, should this be documented in the troubleshooting section?

**Comment by marmarek** [comment]
Well, the system behaved exactly as requested: gave sys-usb graphics card, taking it away from dom0. It means dom0 no longer has graphics card, so cannot display anything.
Troubleshooting this case is already described in https://www.qubes-os.org/doc/autostart-troubleshooting/

**Comment by andrewdavidwong** [comment]
> Well, the system behaved exactly as requested: gave sys-usb graphics card, taking it away from dom0. It means dom0 no longer has graphics card, so cannot display anything. Troubleshooting this case is already described in https://www.qubes-os.org/doc/autostart-troubleshooting/

Understood. I commented on https://github.com/QubesOS/qubes-issues/issues/7996 with some thoughts about additional things Qubes could do in this scenario. Sounds like this particular issue should be closed as "not a bug."

**Comment by andrewdavidwong** [comment]
Closing as "not a bug" (the reported behavior is not a bug and is already working as intended). If anyone believes this is a mistake, please leave a comment, and we'll be happy to take another look. Thank you.

**Comment by romeogregory** [comment]
Thank you bro, you saved my laptop :p
