### ISSUE TITLE
 Building app-shutdown-idle (debian) for bookworm fails

### ISSUE THREAD

**Issue by unman** [QubesOS/qubes-issues#7999]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
4.1

### Brief summary
As per title

### Steps to reproduce
Configure Qubes builder for bookworm template.
`make qubes-vm`

### Expected behavior
Packages will be built for bookworm

### Actual behavior
Build app-shutdown-idle fails on tests:
Each test fails - "Passing coroutines is forbidden, use tasks explicitly."
Tests rerun - OK
BUT:
```
----------------------------------------------------------------------
Ran 6 tests in 58.061s

OK
dh_auto_test: error: pybuild --test -i python{version} -p "3.11 3.10" returned exit code 13
make: *** [debian/rules:23: build] Error 25
dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2
make[2]: *** [/home/user/qubes-builder/qubes-src/builder-debian//Makefile-legacy.debian:56: dist-package] Error 2
make[1]: *** [Makefile.generic:197: packages] Error 1
make: *** [Makefile:265: app-shutdown-idle-vm] Error 1
```

**Comment by marmarek** [comment]
Are you sure you use the most recent version? This was fixed in https://github.com/QubesOS/qubes-app-shutdown-idle/pull/21 already.

**Comment by unman** [comment]
I ran make get-sources -let me look in to this.

**Comment by unman** [comment]
All looks good,closing.
