### ISSUE TITLE
Fedora 37 Nautilus Move/Copy to VM dialog is shown for the duration of transmission

### ISSUE THREAD

**Issue by b90g** [QubesOS/qubes-issues#8006]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

4.1

### Brief summary

When i click on a file and i want to move/copy it to another vm the right click menu is shown until the file is fully transmitted on top of everything on every workspace, even dom0 windows are hidden behind.

### Steps to reproduce

Open Fedora37 file manager Nautilus and select a rather large file where you can see it takes some time and chose to transmit it to any other VM

### Expected behavior

the right click menu disappears and  i just select the target vm in a dom0 windows.

### Actual behavior

the right click menu persists until the file is transmitted

**Comment by noskb** [comment]
I sent a PR, but it looks like the package containing it hasn't shipped yet.
https://github.com/QubesOS/qubes-core-agent-linux/pull/398

**Comment by marmarek** [comment]
The update with this PR is already in stable repo: https://github.com/QubesOS/updates-status/issues/3476
