### ISSUE TITLE
Consider using less ambiguous headings in qube settings interface

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#8012]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### The problem you're addressing (if any)

In #8002, a user commented:

> Also it is strange that I don't have terminal in sys-net ![image](https://user-images.githubusercontent.com/10381464/216366806-32678867-007f-499b-aedf-cb9ef6090d24.png)

Is it possible that the word "Available" makes some people think those are the things that are supposed to be *available* in the App Menu?

### The solution you'd like

Perhaps it might be clearer to use more explicit headings for these lists that state the actual effect, like "Shown in App Menu" and "Not shown in App Menu."

(And similarly for everywhere else this pattern appears, like on the Devices tab.)

### The value to a user, and who that user might be

Potentially less confusion from novice users.

**Comment by marmarta** [comment]
I like this idea a lot! Will do.

**Comment by andrewdavidwong** [comment]
> (And similarly for everywhere else this pattern appears, like on the Devices tab.)

Do you think it should also be changed here?
