### ISSUE TITLE
contrib.qubes-os.org certificate has expired

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#8018]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Brief summary

```
Your connection is not private
Attackers might be trying to steal your information from contrib.qubes-os.org (for example, passwords, messages, or credit cards). Learn more
NET::ERR_CERT_DATE_INVALID
```

Originally reported here:

- https://forum.qubes-os.org/t/qubes-contribution-website-cert/16700
- https://forum.qubes-os.org/t/debian-11-update-issue/16688/

FYI @marmarek @fepitre @woju

**Comment by marmarek** [comment]
Fixed, thanks.
