### ISSUE TITLE
No help text or man page for `qvm-console-dispvm`

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#8019]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

4.1.1

### Brief summary

There's no help text or man page for `qvm-console-dispvm`.

### Steps to reproduce

In dom0:

```
$ qvm-console-dispvm --help
Invalid qube name --help
$ qvm-console-dispvm -h
Invalid qube name -h
$ man qvm-console-dispvm
No manual entry for qvm-console-dispvm
```

### Expected behavior

Help text and a man page.

### Actual behavior

Neither.

**Comment by unman** [comment]
There is, of course, help available on calling `qvm-console-dispvm`

**Comment by andrewdavidwong** [comment]
> There is, of course, help available on calling `qvm-console-dispvm`

I'm not comfortable with executing a command in dom0 without first having some idea of what it will do. Having to execute a command in order to get the help text feels a bit shooting first and asking questions later. Also, since not every command works this way, it's not a reliable approach. Some commands will just immediately perform an action (potentially an irreversible action that you don't want).

**Comment by DemiMarie** [comment]
> Some commands will just immediately perform an action (potentially an irreversible action that you don't want).

Are there any such commands in dom0?  There really should not be.

**Comment by andrewdavidwong** [comment]
> > Some commands will just immediately perform an action (potentially an irreversible action that you don't want).
> 
> 
> 
> Are there any such commands in dom0?  There really should not be.

`qubes-dom0-update`, for example, and potentially any non-Qubes command.

**Comment by DemiMarie** [comment]
> > > Some commands will just immediately perform an action (potentially an irreversible action that you don't want).
> > 
> > 
> > Are there any such commands in dom0?  There really should not be.
> 
> `qubes-dom0-update`, for example, and potentially any non-Qubes command.

`qubes-dom0-update` gives you a prompt and the default is to cancel.

**Comment by unman** [comment]
> `qubes-dom0-update` gives you a prompt and the default is to cancel.
> 
But it has performed significant actions first, before it gets to the
"prompt" stage.

**Comment by andrewdavidwong** [comment]
> But it has performed significant actions first, before it gets to the "prompt" stage.

Yes, exactly.

> `qubes-dom0-update` gives you a prompt and the default is to cancel.

I think you're getting caught up on the specifics of one example and missing the point. The point really isn't whether, as a contingent matter of fact, there happen to be any such commands in dom0 *right now*. The point is that even experienced Linux users can't know exactly what a novel command will do from its name alone. If they try to find out what the command does by checking for help text and a man page and come up empty-handed, they shouldn't then be required to take a gamble and execute the command blindly in the hope that it will finally reveal its secrets (such as its basic function). It's just bad practice.
