### ISSUE TITLE
qubes-global-config window is too big

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#8021]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

R4.2

### Brief summary

It is so big, it doesn't fit on 1920x1080 screen - it takes almost full screen width, but it's so tall that button fall outside of the screen. And it refuses to resize to smaller (but you can make it even bigger...).

### Steps to reproduce

1. Launch qubes-global-config
2. Observe you've got 1800x1200 window.
3. Wonder how to click off-screen "ok".

### Expected behavior

1. It fits on the screen
2. Independently of the above, it's possible to resize down to rather small size (below 1024x768?).

When resizing, explanation texts should wrap (currently most are a single line) to allow narrower window, and show horizontal scrollbar when necessary (currently even with such tall window, some tabs do have a scrollbar, which is okay).

### Actual behavior

See summary above.

**Comment by marmarta** [comment]
fixed by https://github.com/QubesOS/qubes-desktop-linux-manager/pull/145
