### ISSUE TITLE
No help text or man page for `qvm-move` and `qvm-copy`

### ISSUE THREAD

**Issue by unman** [QubesOS/qubes-issues#8023]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
4.1

### Brief summary
As title

### Steps to reproduce
`man qvm-copy`
`qvm-copy -h` 

### Expected behavior
Help or man page

### Actual behavior
Help is available only from `qvm-move/copy` with no parameters

**Comment by andrewdavidwong** [comment]
I don't think this issue should be closed by https://github.com/QubesOS/qubes-core-agent-linux/pull/408, since that PR adds only `--help` text and not a man page. There should be both, so this issue should remain open until the man page is also added.

**Comment by alimirjamali** [comment]
PR submitted.

Both command support `-h` and `--help` at the moment. A manual for `qvm-copy` existed. It was used as the template for `qvm-move`.
