### ISSUE TITLE
Audio mixer (pavucontrol) should control usb-c headsets

### ISSUE THREAD

**Issue by MaikoID** [QubesOS/qubes-issues#8025]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
4.1.1 (R4.1)

### Brief summary
Audio mixer ignores the usb-c headset that is added to one of the qubes.

qvm-usb
sys-usb:2-3    OnePlus_Technology_BE02T_20160406.1          personal

### Steps to reproduce
While using a usb-c headset;
Add it to one of the qubes.
Headset is working on the qubes, both playback and recording.
Audio mixer doesn't see the headset. Also, changing the system volumes doesnt have any effect.

### Expected behavior
That Audio mixer controls everyone of the audio devices available.

### Actual behavior
The audio mixer pavucontrol don't see the headset, hence, it doesn't control its sound. The only workaround is control the volume through the app using it when possible.

**Comment by DemiMarie** [comment]
You need to run pavucontrol from the VM that is providing the audio.

**Comment by andrewdavidwong** [comment]
> The audio mixer pavucontrol don't see the headset, hence, it doesn't control its sound. The only workaround is control the volume through the app using it when possible.

> You need to run pavucontrol from the VM that is providing the audio.

Sounds like this might be a UX issue with developer intentions differing from user expectations. Maybe what we need is some way to indicate this to the user.

**Comment by MaikoID** [comment]
> You need to run pavucontrol from the VM that is providing the audio.

Thanks for answering, I did that, I installed pavucontrol on my Debian template and controlled it on my qubes,  it kind of works but in a strange way.. every time a new audio is played the volume go back to 100% making it unusable, any thoughts on that?
