### ISSUE TITLE
R.4.1.2-rc1: odd behavior when putting in encryption password with USB keyboard...

### ISSUE THREAD

**Issue by GSF1200S** [QubesOS/qubes-issues#8031]
### Qubes OS release
4.1.2-rc1

### Brief summary
If usbcore.authorized_default=1, I have no issue.

If I have set rd.qubes.dom0_usb=<BDF> and usbcore.authorized_default=0, the plymouth Qubes unlock screen will not show dots as I enter each character of my encryption password. However _input is happening_ and if I blindly type the password and hit enter, it will proceed to boot _without getting rid of the text box or showing the loading bar_. 

If I instead hit escape, the command line shows and I can enter my password with characters being registered as asterisks like it's supposed to. However, if I leave it like this, the boot process will complete, the login manager will pop up momentarily, and then the screen will flash and go green/pink with a complete lock. This is 100% reproducible for me.

If I instead hit escape twice- that is go to the command line with escape and then back to plymouth with escape again- it registers character input as dots like it should, boots to the login manager, does not freeze, and works fine from here on out. I can also hit escape, put in the password/enter, then hit escape again to go back to plymouth and again it works completely fine.

### Steps to reproduce

As above.

### Expected behavior

The password input should work- and display characters as they are inputted- without needing to escape plymouth.

### Actual behavior

As above.

As this is during boot and before the partition is decrypted, I'm unsure what info I could provide. Also despite the hardlock as described above, I don't think this is too bad an issue- quickly hitting escape twice is a really easy workaround. This bug might be confusing or catastrophic though for someone who doesn't know to try escape, thinks their password isn't being put in, etc.

**Comment by marmarek** [comment]
What USB devices do you have in your system? Maybe some one of them (besides keyboard) is somehow related to boot prompt?
I'd recommend doing three boots and each time save `sudo journalctl -b` output to a file:
 - with `usbcore.authorized_default=1`
 - with `usbcore.authorized_default=0` and pressing ESC twice
 - with `usbcore.authorized_default=0` and not pressing ESC (in case of system freeze, reboot afterwards and retrieve log with `sudo journalctl -b -1`)

Then compare those three. If you are comfortable with that, you can share all three here (be aware it will include at least list of qubes you have set to autostart).
