### ISSUE TITLE
Change of keyboard layouts with Capslock/Shift+Capslock (`shift_caps_switch` in `setxkbmap`) breaks all the time

### ISSUE THREAD

**Issue by jamke** [QubesOS/qubes-issues#8035]
### Qubes OS release
R4.1.1.

### Brief summary
Switching 2 keyboard layouts with Capslock for the first layout and Shift+Capslock for the second one (`shift_caps_switch` group in `setxkbmap`) is not working properly and breaks many times a day.

### Steps to reproduce
- During system installation add a second layout and set layout switch hotkey to Capslock for first layout and Shift+Capslock for the second one (`shift_caps_switch` group in `setxkbmap`)
- Use the system normally.

Note: Also settings this mode after installation with a single English layout has the same results.

### Expected behavior
Layout switch works.

### Actual behavior
After some time layout switch stops working completely. Very often and very annoying.
The way to temporary fix the issue is to press capslock and shift+capslock several times in some order, to exit some kind of wrong state of Qubes OS keyboard layout scripts. But soon the layout switching gets broken again.

### More
R4.0 worked fine, so this bug is a 100% **regression**.

**Comment by andrewdavidwong** [comment]
#6517 wasn't mentioned here, but it appears to be related.

**Comment by jamke** [comment]
> #6517 wasn't mentioned here, but it appears to be related.

I provided feedback there before, it can be related, thank you.
On the other hand, it seems to be a different bug, because the combination is not one-button one, so I made a separate issue.

**Comment by jamke** [comment]
> Not an Xfce user, but I recall that there are bugs in using setxkbmap of late. Have you checked to see if this is Xfce version, rather than Qubes?

Thanks for reply. I am using the layout switching settings installed by the installation process of the system, as I expected it to be the proper or at least the most expected way. Managing of layouts by XFCE is disabled in XFCE settings (`Use system defaults` is checked).
On previous Qubes OS instances I also had the same issue, and I tried:
- using XFCE layouts (not recommended approach, I think), 
- use `localectl` to regenerate xorg config (saw it being recommended in docs or on github somewhere)
and nothing helped.

While `shift_caps_switch` worked properly on R4.0, on R4.1 it is such a daily pain, that it should be considered unusable...

**Comment by jamke** [comment]
> Have you checked to see if this is Xfce version, rather than Qubes?

If there is a way to make checks you mentioned - please tell, I will try them.

**Comment by jamke** [comment]
> * use `localectl` to regenerate xorg config (saw it being recommended in docs or on github somewhere)

This is what I was talking about: https://www.qubes-os.org/doc/hardware-troubleshooting/#keyboard-layout-settings-not-behaving-correctly

**Comment by kalkin** [comment]
I have a similar issue. I'm using localetctl to setup switching between us/ru when pressing both `Shift` keys. Sometimes it works sometimes the switch between layouts is not forwarded to all VMs. Also a big issue is that Xscreensaver doesn't show the layout currently used.

**Comment by jamke** [comment]
> Also a big issue is that Xscreensaver doesn't show the layout currently used.

You can use this script to overcome this limitation of `xscreensaver`: https://forum.qubes-os.org/t/force-xscreensaver-to-show-itself-on-specific-display/18200/13

Have you somehow fixed the issue this layout toggle?
I still have the issue and dream to fix it somehow.

**Comment by jamke** [comment]
I will try to modify `qvm_start_daemon.py` locally in `dom0` to get more information about what is happening and what is wrong, because I have layout switch problem every day.

**Comment by jamke** [comment]
I found out that in my situation, when I use 2 layouts (lets call them `us` and `AA`) and a `shift_caps_switch` for switching **the problem is that `XKLAVIER_ALLOW_SECONDARY` is not fired when it should be**.

The situation during the problem happening:
1. In some qube I have active layout `AA`, I press capslock once, or multiple times to switch to `us` but it does nothing. And `/usr/bin/qubesdb-read /keyboard-layout` always shows: `AA++grp:shift_caps_switch` and actually types chars from `AA`. So, `qubes-keymap.sh` works properly, it's just that qubesdb does not have changed layout.
2. In `dom0` it also type `AA` chars, and not `us` chars, so the effective layout it `AA`.
3. I checked  `xev -root -event property` in `dom0` and NOTHING is fired when I press capslock. That's the reason!
4. hen I pressed shift+capslock I see finally `XKLAVIER_ALLOW_SECONDARY` event.

So, why `XKLAVIER_ALLOW_SECONDARY`?
So, I think the problem is that `XKLAVIER_ALLOW_SECONDARY` it supposed to be fired only on **change** of layout and something (libxklavier?) in `dom0` mistakenly thinks that I am trying to set layout to the same one (and not change it).
Is it possible to replace this event with something better, maybe something that is reliably called on any layout shortcut change event (even if the layout stays the same like `us` -> `us`)?

**Comment by jamke** [comment]
As a temporary work-around - I can bind `capslock` and `shift+capslock` to global shortcuts and change the layout manually using `xbk-switch`, but in this case I need to somehow fire `XKLAVIER_ALLOW_SECONDARY` event, so the Qubes OS script will propagate layout inside qubes.

**Is there a way to fire `XKLAVIER_ALLOW_SECONDARY` manually?**

I tried it without manual fire (and rely on automatic firing), it works but also breaks at some moment. Because the problem is with this event firing mechanism gets confused all the time and does not work reliably and properly.

**Comment by kalkin** [comment]
> > Also a big issue is that Xscreensaver doesn't show the layout currently used.
> 
> You can use this script to overcome this limitation of `xscreensaver`: [forum.qubes-os.org/t/force-xscreensaver-to-show-itself-on-specific-display/18200/13](https://forum.qubes-os.org/t/force-xscreensaver-to-show-itself-on-specific-display/18200/13)

I just glanced over it, it looks like you suggest having a script switching the layout when xscreensaver is locked? This might work. Thanks.

> Have you somehow fixed the issue this layout toggle?
Nop. I also have not debugged this topic any further (too little time, too much code to write...)

> So, I think the problem is that XKLAVIER_ALLOW_SECONDARY it supposed to be fired only on change of layout and something (libxklavier?) in dom0 mistakenly thinks that I am trying to set layout to the same one (and not change it).

Nice work debugging this issue! Have you already discovered https://github.com/QubesOS/qubes-core-admin-client/blob/0106eacf9e3a7ee7e166ad43163198befc8e6009/qubesadmin/tools/qvm_start_daemon.py#L191 ? May be this can help you on your quest.

**Comment by jamke** [comment]
OK, now I can 100% reproduce 2 different bugs related to this issue.

Good news is that I managed to workaround the issue by modification of `/usr/lib/python3.8/site-packages/qubesadmin/tools/qvm_start_daemon.py` in my system.

@marmarek  @strugee @DemiMarie maybe you can help me to understand, why Qubes OS R4.1 is propagating ALL xkb options inside the target qubes? Including shortcuts for switching keyboard layout. I mean the whole point is that xkb inside the qube IS NOT changing keyboard layout itself, isn't it?
Because currently it breaks keyboard layout switch all the time. But if I block propagation of options (making layout unchangeable inside the qube by itself) everything works for me quite well.

So, maybe stripping options that are related to the shortcuts of layout switching should be added to `qvm_start_daemon.py` out of the box.

**Comment by marmarek** [comment]
> I mean the whole point is that xkb inside the qube IS NOT changing keyboard layout itself, isn't it?

Right!

> So, maybe stripping options that are related to the shortcuts of layout switching should be added to `qvm_start_daemon.py` out of the box.

Yes, I think this is the right way to go.

**Comment by jamke** [comment]
This issue is not solved, because the provided code change https://github.com/QubesOS/qubes-core-admin-client/commit/fc08f4eb2738976606a76d3483ec1fb8a2b5212e addresses only `*_toggle` options, which is not a case for Capslock/Shift+Capslock (`shift_caps_switch`) as mentioned in this ticket. There are other options that does not end in `*_toggle`.

@andrewdavidwong please reopen.

I made a PR with more information about it, maybe it can really fix the issue (hopefully):
https://github.com/QubesOS/qubes-core-admin-client/pull/255

**Comment by andrewdavidwong** [comment]
Closing as resolved. If anyone believes this issue is not yet resolved, or if anyone is still affected by this issue, please leave a comment, and we'll be happy to reopen it. Thank you.
