### ISSUE TITLE
Qubes 4.1:  Add full-function python3-zstandard library to dom0

### ISSUE THREAD

**Issue by tasket** [QubesOS/qubes-issues#8036]
### The problem you're addressing (if any)
Qubes 4.1 dom0 lacks the 'python3-zstandard' library that would be useful to the Wyng backup [project.](https://github.com/tasket/wyng-backup)  Fedora 32 just missed getting this library, as it is present in the [Fedora 33 repo](https://rpm.pbone.net/info_idpl_80037832_distro_fedora33_com_python3-zstandard-0.15.2-1.fc33.x86_64.rpm.html).

The immediate impact of having to use the existing 'python3-zstd' library is no access to standard Python buffer protocols and therefore reduced performance.

### The solution you'd like
Make [python3-zstandard](https://github.com/indygreg/python-zstandard) available in dom0.

### The value to a user, and who that user might be
Backup user gets continued zstandard compression as an option when running Wyng on Qubes.  This means enhanced speed and compression ratios and possibly new features that utilize compression streams and dictionaries.

### Related
https://github.com/tasket/wyng-backup/issues/141
Issue #858

**Comment by andrewdavidwong** [comment]
Will this be automatically resolved when Qubes 4.2 is released with Fedora 37 in dom0?

**Comment by tasket** [comment]
Yes, it would be resolved that way.  I don't know how long that wait would be, so I'll leave it to Qubes devs to decide if that would be worth the effort.

**Comment by tasket** [comment]
I think this issue will be moot since R4.2 is already at rc1.
