### ISSUE TITLE
R4.1.2-rc1 installer fails when the installation target is a USB drive and the option to create `sys-usb` is selected

### ISSUE THREAD

**Issue by GWeck** [QubesOS/qubes-issues#8038]
### Qubes OS release

R4.1.2-rc1

### Brief summary
Installation of R4.1.2-rc1 aborts during phase 2 if the target disk is a USB-disk and default options are selected including the creation of the `sys-usb` qube. The resulting system cannot be successfully started because it cannot access the target disk.

### Steps to reproduce
Install R4.1.2-rc1 on a system in legacy BIOS mode (Intel processor and Intel graphics with plenty of space on the installation disk), selecting BTRFS file system, and no encryption. The Target disk is a USB-Disk.

For the second phase of the installation, just select the default options offered, including `sys-usb` qube, attaching the keyboard; selecting attaching the mouse or not makes no difference.

### Expected behavior
The resulting system should be usable like the one created from the R4.1.1 installer. 

### Actual behavior
Installation of R4.1.2-rc1 with default options runs through to nearly the end of phase 2. During the (final?) step "Qubes configuration" the screen suddenly turns black, without an error message. Booting the created system stops at the step `Reached Target System`, and after a timeout, enters emergency mode. Here, the system complains that `/dev/disk/by-uuid` and `/dev/qubes-dom0/swap00` do not exist.

This is caused by the installer offering to create and use the `sys-usb` qube, although the installation has a USB-disk as its target. If The option to create the `sys-usb` qube is deselected, the installation succeeds.

### Solution
The installer should not offer the option to create the `sys-usb` qube if the target disk is a USB-disk. Best to disable this option in this case, because it never can work. This would help users just trying to install Qubes without knowing the technical details.

**Comment by marmarek** [comment]
It should be already the case, theoretically, and it seems to work with default partitioning: https://openqa.qubes-os.org/tests/59586#step/firstboot/5
So, I guess it isn't correctly detected with btrfs.

**Comment by GWeck** [comment]
That's plausible - I have the knack to fall into every hole available. :grin:

**Comment by marmarek** [comment]
That's very useful skill ;)

Anyway, it seems it isn't it, with btrfs sys-usb seems to be disabled correctly: https://openqa.qubes-os.org/tests/60304#step/firstboot/8

I can also try with no encryption...

**Comment by marmarek** [comment]
How you did "BTRFS file system, and no encryption"? Did you added partitions manually? For me, if I select automatic btrfs, and then try to disable encryption, I get "cannot remove non-leaf device 'luks-sda3'" error and it resets back to empty partitions list.

**Comment by brendanhoar** [comment]
I wonder if the type of usb bridge chipset and its capabilities matter in terms of how the installer treats the device? E.g. usb mass storage (bulk) vs USB Attached SCSI (UAS)?

B

**Comment by marmarek** [comment]
Unlikely, but not impossible.

**Comment by marmarek** [comment]
Here is how the check is done: https://github.com/QubesOS/qubes-anaconda-addon/blob/main/org_qubes_os_initial_setup/utils.py#L77-L103

**Comment by marmarek** [comment]
> I can also try with no encryption...

[BTRFS with no encryption](https://openqa.qubes-os.org/tests/60344#step/install_partitioning_btrfs_unencrypted/18) works fine too...
What exactly have you chosen during installation?

**Comment by GWeck** [comment]
When in the target selection, I at first disabled encryption, then selected manual partitioning, and there, for the `/` mount point, I selected BTRFS, checking that the encryption option was still turned off. The two other mount points were just standard selections: `/boot` as a standard partition with ext4 and size of 1 GiB, and `swap` with default parameters.

Before creating these partitions, I removed the corresponding partitions from an earlier test with the help of the installer.

The USB device is a SAMSUNG portable SSD T5 with 512 GB, which I use for all these tests since R4.0. Qubes sees this device as a USB block device. There's one more partition on this device, formatted as ext4, which I use for backups and did not touch during the installation.

I'll do some more tests with different selections of options.

**Comment by GWeck** [comment]
I checked now the following combinations:

- manual partitioning with BTRFS, no encryption
- manual partitioning with LVM thin pool, no encryption
- automatic partitioning with encryption
- automatic partitioning, no encryption

All show the same behavior, i.e. the creation of `sys-usb` is enabled. That looks like a problem with this USB disk device. But, on the other hand, the SAMSUNG Portable SSD T5 is a rather common device showing no particular, uncommon properties.

I am somewhat at a loss here. If I could provide more information, please tell me and I'll try to provide it.

**Comment by rustybird** [comment]
Not sure if that's what's going on but [this](https://github.com/QubesOS/qubes-anaconda-addon/blob/v4.1.10/org_qubes_os_initial_setup/ks/qubes.py#L95-L100) seems like it could miss an USB device if at any point in traversing the chain there *is* a `slaves` subdirectory but it's empty.

**Comment by rustybird** [comment]
I've reproduced this with a USB Mass Storage device. The problem was that it didn't have the [`ID_USB_INTERFACES`](https://github.com/QubesOS/qubes-anaconda-addon/blob/v4.1.10/org_qubes_os_initial_setup/ks/qubes.py#L110) udev property:

    $ grep -i usb /run/udev/data/b8:2  # looking at /dev/sda2 here
    S:disk/by-path/pci-0000:00:1a.0-usb-0:1.2:1.0-scsi-0:0:0:0-part2
    E:ID_PATH=pci-0000:00:1a.0-usb-0:1.2:1.0-scsi-0:0:0:0
    E:ID_PATH_TAG=pci-0000_00_1a_0-usb-0_1_2_1_0-scsi-0_0_0_0

How about also matching `ID_PATH` against a `-usb-` substring?

**Comment by marmarek** [comment]
Interesting, what happened to all the other properties? I have a lot more of them, including `ID_BUS=usb`, and all the `ID_USB_*`

Anyway, I made a modification to check also parent devices (see PR linked above), can you test it on your case? (the utils.py script is rather standalone, you can run `started_from_usb()` function from it directly - it should check if anything that is _mounted_ is on USB disk).

**Comment by GWeck** [comment]
I checked now with two other devices:

- a Toshiba USB stick under legacy BIOS, using BTRFS

- a WesternDigital Passport HDD under UEFI, also using BTRFS

Both are correctly recognized as USB devices, and the option to use the `sys-usb` qube is disabled.

So it's definitively a matter of the USB device properties, and the corrections of @marmarek should solve the issue. I'll test agin as soon as they are published.

**Comment by rustybird** [comment]
> Interesting, what happened to all the other properties? I have a lot more of them, including `ID_BUS=usb`, and all the `ID_USB_*`

In a fc37 sys-usb they're all there, for the same drive. It's not due to the kernel (tested with the same version), and if anything's preventing the udev `usb_id` builtin from running it's not `/usr/lib/udev/rules/*-qubes-*.rules` (tested with those files moved out of the way in R4.1 dom0). I'll try an R4.2 alpha once it has fc37 in dom0.

> Anyway, I made a modification to check also parent devices (see PR linked above), can you test it on your case?

That fixed it!

**Comment by GWeck** [comment]
The installer of R4.2 correctly determines the target USB disk as a USB device and does not allow the creation of  `sys-usb`.
