### ISSUE TITLE
R4.1.2-rc1 displays wrong version number

### ISSUE THREAD

**Issue by GWeck** [QubesOS/qubes-issues#8039]
### Qubes OS release
R4.1.2-rc1

### Brief summary
The version number is still displayed as R4.1.1 at several locations.

### Steps to reproduce
Install the system and/oder ask Qube Manager for the current version.

### Expected behavior
Qubes R4.1.2-rc1 should display its version number as 4.1.2 everywhere.

### Actual behavior
At least the selection screen of phase 2 of the installation and the version displayed from the Qube Manager still show 4.1.1 as the version.

**Comment by marmarek** [comment]
I believe it's fixed with https://github.com/QubesOS/updates-status/issues/3560

**Comment by andrewdavidwong** [comment]
> I believe it's fixed with [QubesOS/updates-status#3560](https://github.com/QubesOS/updates-status/issues/3560)

As reported in #8059, the wrong version number is also on the initial setup screen. Does this also fix that?
