### ISSUE TITLE
Audio "randomly" stops working

### ISSUE THREAD

**Issue by x41j** [QubesOS/qubes-issues#8040]
### Qubes OS release

4.1.1 (R4.1)

### Brief summary

Audio output and audio input sometimes suddenly stop working after working just fine. When launching `pavucontrol` in dom0, I can see the related volume meters moving, but can't hear any audio, regardless of the used output device. Output and input can fail independently of each other.

### Steps to reproduce

Unclear, unfortunately. It seems to be related to *some* sort of audio changes, but I'm unsure what exactly it is. I think it's related to new audio streams (happens e.g. after pausing / opening a new YouTube video). It might also be related to plugging in / out audio devices or attaching the microphone to a VM, but I'm not sure.

I'm using an AMD Thinkpad. No audio related changes have been made to the default Qubes installation.

On rare occasions (<= 5%) one of these steps will fix the issue:

- Change the output port (e.g. from speaker to headphones; `pavucontrol` -> Output Devices / Input Devices)
- Disable and enable the Profile (`pavucontrol` -> Configuration)
- Restart pulseaudio (using `pulseaudio -k` or `systemctl --user restart pulseaudio` in dom0)

But most of the times it doesn't seem to change anything and only a reboot will fix it.

### Expected behavior

Audio continues to work.

### Actual behavior

Audio doesn't work. Unfortunately it is extremely unreliable and I can't rely on using Qubes for e.g. joining audio conferences because input or output will fail 60% of the times.

---

I'm happy to help debugging this if you can provide me with commands to run before/after the issue or other things to take note of.

**Comment by marmarek** [comment]
Which kernel version do you have in dom0? There was an issue like this with 5.17.x-6.1.1 kernels.

**Comment by andrewdavidwong** [comment]
> Should we close this in favor of #7634?

Sure, if it's a duplicate.

**Comment by andrewdavidwong** [comment]
This appears to be a [duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If anyone believes this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.
