### ISSUE TITLE
Improve UX of favorites in app menu

### ISSUE THREAD

**Issue by marmarta** [QubesOS/qubes-issues#8043]
### The problem you're addressing (if any)

Proposal: put favorites on top, make them default. 

Reason: favorites is probably the main thing people will use, because users tend to use the same applications over and over again.

**Comment by unman** [comment]
The KDE menu options have favorites, and "Recent Applications", sortable
by "Recently used" or "Often used".

**Comment by marmarek** [comment]
done?
