### ISSUE TITLE
Delay on accessing SMB share from Nautilus in Fedora 37

### ISSUE THREAD

**Issue by GWeck** [QubesOS/qubes-issues#8052]
### Qubes OS release

R4.1.1 fully updated with Fedora 37 fully updated

### Brief summary
Accessing an SMB share from Nautilus under Fedora 37 shows a spinning wheel for some time. Only after clicking around several times, access to the share is granted.

### Steps to reproduce
Provide an SMB share on some other computer (in my case, a Windows 7 system). Then, from an AppVM based on a Fedora 37 template, try to access this share from Nautilus. 

### Expected behavior
The share should be opened immediately like it is when using an AppVM based on Fedora 36.

### Actual behavior
A spinning wheel is displayed. The share is displayed, but clicking on it shows a window with the message `... is opened`, but no access is given. Only after clicking several times on Nautilus, possibly on the spinning wheel, the share is opened and accessible.

This happens only with SMB. Access via FTP to a NAS is granted immediately.

**Comment by rustybird** [comment]
If it's a variation on #7921, [disabling OpenGL](https://github.com/QubesOS/qubes-issues/issues/7921#issuecomment-1409499825) might help:

    nautilus --quit && GDK_DEBUG=gl-disable nautilus

**Comment by GWeck** [comment]
Disabling OpenGL seems to help for the current start of Nautilus. After restarting Nautilus or after a restart of the AppVM, the delay occurs again.

Is there a way to disable OpenGL permanently for Nautilus?

**Comment by rustybird** [comment]
I've disabled OpenGL permanently for all GTK 4 applications by writing

    export GDK_DEBUG=gl-disable

to a new file with a `.sh` extension in `/etc/profile.d/` on my TemplateVMs. It doesn't seem to have caused any [rendering bugs](https://github.com/QubesOS/qubes-issues/issues/7921#issuecomment-1409532131) so far, but then again I don't use GTK 4 stuff all that much.

**Comment by GWeck** [comment]
I am afraid: It did not work. I created such a shell script in my Fedora 37 TemplateVM, but the AppVM based on this template still shows the delays. Setting execute permission for this script also had no effect.

**Comment by rustybird** [comment]
Ah okay, `/etc/profile.d/` is only used if the GTK 4 app is launched from a shell, e.g. in a terminal.

I don't know what would be the proper place to add an environment variable so that it's picked up by the `qubes.StartApp` service (application launcher / Qubes Domains menu).

**Comment by rustybird** [comment]
Found it: https://www.freedesktop.org/software/systemd/man/environment.d.html

    mkdir -p /etc/environment.d
    echo GDK_DEBUG=gl-disable >/etc/environment.d/whatever.conf

**Comment by GWeck** [comment]
That has done the trick: After creating such a `.conf` file in `/etc/environment.d/`, there are no more delays.

Thanks a lot! I'll keep checking.

**Comment by GWeck** [comment]
In Qubes R4.2, this correction is even more necessary, because the spinning wheel cannot be stopped anymore by clicking around.

**Comment by marmarek** [comment]
[GTK issue about the spinner performance](https://gitlab.gnome.org/GNOME/gtk/-/issues/408) has another workaround: `GDK_RENDERING=image`. I'm not sure which one is better. @DemiMarie ?

I consider enabling one of those workarounds by default, but I'd like to get some feedback if there aren't any serious downsides first. Anybody (preferably who use many GTK-based apps) wants to try using it for some time? 

For nautilus specifically, I can patch it to disable spinner on network locations panel.

**Comment by rustybird** [comment]
> [GTK issue about the spinner performance](https://gitlab.gnome.org/GNOME/gtk/-/issues/408) has another workaround: `GDK_RENDERING=image`

That one's gone: https://gitlab.gnome.org/GNOME/gtk/-/commit/c5fc841285f9ab7939e7f1a01146780b47c4be3b#07166cc4807eabcff0ee1a581d4f7e902eba5e74_218_197

**Comment by GWeck** [comment]
Installing the packages nautilus and nautilus-extensions version 43.2-4 solves the problem for both Qubes R4.1 and r4.2. Thanks a lot!
