### ISSUE TITLE
Q4.2 weekly iso 2023-02-19 fails at debian template installation

### ISSUE THREAD

**Issue by tlaurion** [QubesOS/qubes-issues#8055]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
Weekly 4.2 detached signed builds

### Brief summary
qubes-template-debian-11-4.1.0-202212030203.noarc.rpm fails at importing data

### Steps to reproduce
Q4.2 2023-02-19 weekly build iso launched through Heads 
media-scan /dev/sda1

Selecting latest kernel option, selecting repo from iso
Install with default option

### Expected behavior
Install success

### Actual behavior
Second stage Install fails at :
![signal-2023-02-20-162446](https://user-images.githubusercontent.com/827570/220200905-f29ed1d9-b803-45d4-bfa0-33ec4782e6ca.jpeg)

**Comment by marmarek** [comment]
How large is the installation target?

**Comment by tlaurion** [comment]
Q4.2 installer does the right thing on default install, taking free space do mind its own business:

**Comment by marmarek** [comment]
Do you have that test install still? Can you extract journal from it (about the time of that failure)?

**Comment by tlaurion** [comment]
Side effect of https://github.com/QubesOS/qubes-issues/issues/8056.

There was 10 GB free inside of /dev/sda1. It was shrinked and used to be passed to the 200gb of free space to create installation. Not sure why debian template failed, installation was wiped. But I consider it to be a side effect of #8054. This doesn't happen when selecting USB boot with same ISO which passes detached signature validation. 

Closing for now
