### ISSUE TITLE
Q4.2 2023-02-19 ISO doesn't pass inst.repo (still inst.stage2) through grub option

### ISSUE THREAD

**Issue by tlaurion** [QubesOS/qubes-issues#8056]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
First Q4.2 detached signed weekly build at https://qubes.notset.fr/iso/Qubes-4.2.202302191645-x86_64.iso

### Brief summary
doesn't contain proper inst.repo passing through grub config  (still inst.stage2) as seen per
![signal-2023-02-20-152812_002](https://user-images.githubusercontent.com/827570/220201776-5aed8e59-2319-46ef-b486-26e74fc8b9d1.jpeg)

### Steps to reproduce
media-scan /dev/sda1
containing iso iso.asc

See 
![signal-2023-02-20-152952](https://user-images.githubusercontent.com/827570/220201902-51125aef-b264-4631-984f-fcee4bc79194.jpeg)
![signal-2023-02-20-153009](https://user-images.githubusercontent.com/827570/220201904-52a8021c-9286-472b-a4f1-8074c50ca566.jpeg)
![signal-2023-02-20-153045](https://user-images.githubusercontent.com/827570/220201906-29f4dacd-70e0-40a2-97aa-a86b177981f4.jpeg)

### Expected behavior
Not having to manually re-select iso from within installer, having grub pass proper anaconda settings

### Actual behavior
having to manually re-select iso from within installer

**Comment by tlaurion** [comment]
@fepitre : wasn't it supposed to be inside of the ISO

**Comment by marmarek** [comment]
Which grub.cfg Heads parse? There are two of them - EFI (EFI/BOOT/grub.cfg) and non-EFI (boot/grub2/grub.cfg).

**Comment by marmarek** [comment]
I see only one of them has inst.repo, the other still uses inst.stage2. Will be fixed in the next weekly build.

**Comment by tlaurion** [comment]
@marmarek boot/grub2/grub.cfg

**Comment by marmarek** [comment]
Hmm, but this one should be the correct one. Looking at the screenshot above, I see entries are duplicated. Maybe it reads both of them?

**Comment by marmarek** [comment]
Can you try the other one? You chosen 9, so try 10.

**Comment by tlaurion** [comment]
10 works. OK. Haven't realized heads was parsing both, will open bug to remove duplicates.

**Comment by tlaurion** [comment]
Duplicate entries have to be because entries were different: only unique options are presented to user. 
Next ISO should function correctly if entries are unique as expected.
