### ISSUE TITLE
Improve language in Qubes Global Config

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#8057]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

4.2

### Brief description

The language in [`qubes_config/global_config.glade`](https://github.com/QubesOS/qubes-desktop-linux-manager/blob/33f95081ca6a1d9a0efa05449be4b080f40f06ea/qubes_config/global_config.glade) could use a copy editing pass in order to improve spelling, punctuation, grammar, usage, mechanics, and style.

(Edit: Updated issue to reflect what my PR actually improves.)

**Comment by DemiMarie** [comment]
@andrewdavidwong I’m more than a bit confused here.  It looks like other places also treat “Qube” as a proper noun.

**Comment by andrewdavidwong** [comment]
> @andrewdavidwong I’m more than a bit confused here. It looks like other places also treat “Qube” as a proper noun.

Those are also incorrect. Please either cite them here or open other issues(s) for them. 

Quoting from the [link](https://www.qubes-os.org/doc/glossary/#qube) provided above:

> ## qube
> 
> A secure compartment in Qubes OS. Currently, qubes are implemented as Xen
> [VMs](#vm), but Qubes OS is independent of its underlying compartmentalization
> technology. VMs could be replaced with a different technology, and qubes would
> still be called "qubes."
> 
> * **Important:** The term "qube" is a common noun and should follow the
>   capitalization rules of common nouns. For example, "I have three qubes" is
>   correct, while "I have three Qubes" is incorrect.
> 
> * Note that starting a sentence with the plural of "qube" (i.e., "Qubes...")
>   can be ambiguous, since it may not be clear whether the referent is a
>   plurality of qubes or [Qubes OS](#qubes-os). You may wish to rephrase
>   sentences in order to avoid this ambiguity.
> 
> * Example usage: "In Qubes OS, you do your banking in your 'banking' qube and
>   your web surfing in your 'untrusted' qube. That way, if your 'untrusted' qube
>   is compromised, your banking activities will remain secure."
> 
> * Historical note: The term "qube" was originally invented as an alternative to
>   "VM" intended to make it easier for less technical users to understand Qubes
>   OS and learn how to use it.

If there's still something confusing about this, please let me know so that I can clarify the glossary entry.

**Comment by unman** [comment]
On Wed, Feb 22, 2023 at 01:20:43AM -0800, Andrew David Wong wrote:
> > @andrewdavidwong I???m more than a bit confused here. It looks like other places also treat ???Qube??? as a proper noun.
> 
[quote]
Those are also incorrect. Please either cite them here or open other issues(s) for them. 
[/quote]
If you generalise this one it would, I think, be better.
There are many dialogues in QM that use "Qube" - easily fixable.
Is it OK to retain Qube as the first word in this case? - e.g in the title
"Qube Shutdown Confirmation" - I cant think of a sensible alternative
except removing the word altogether.

**Comment by andrewdavidwong** [comment]
> If you generalise this one it would, I think, be better.

Happy to, but I'd also like to encourage others to list the specific instances they see in order to make them easier to (and hence more likely to be) fixed.

> Is it OK to retain Qube as the first word in this case? - e.g in the title "Qube Shutdown Confirmation"

Yes, certainly. The word should still be capitalized at the beginnings of sentences, the beginnings of sentence-case headings, in title-case headings, and anywhere else common nouns would normally be capitalized.

(A mental shortcut is to replace the word "qube" with another common noun like "compartment" or "container," then ask yourself whether you'd capitalize it in that context.)

**Comment by andrewdavidwong** [comment]
I've come to realize that it isn't just about the word "qube." There is inconsistent capitalization of other words too. For example:

![2023-03-04_16-00](https://user-images.githubusercontent.com/10417133/222934450-208ab0c5-a3b9-4d91-a815-7f2b61d72174.png)

So, I'm going to generalize this issue and see if I can open a PR to fix these.
