### ISSUE TITLE
Installation image doesn't boot in legacy mode on some systems

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#8058]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

R4.2

### Brief summary

Weekly build doesn't boot in legacy mode on some systems, it does work in UEFI mode on the same system.

### Steps to reproduce

1. Get weekly ISO
2. Switch boot mode to legacy (only)
3. Try to boot installer

### Expected behavior

Installer starts

### Actual behavior

System reset before showing grub menu.
It affects only some systems. SeaBIOS (either in openqa, or as a coreboot payload) works fine, but Thinkpad P52 or  HP EliteBook 840 G4 does not.

### Additional context

There are several changes in the installation image compared to R4.1:
- gpt partition table
- grub2 instead of isolinux

(both inherited from Fedora 37)

Reported by @GWeck at https://forum.qubes-os.org/t/qubes-os-4-2-signed-weekly-builds/16929/4

**Comment by marmarek** [comment]
The same issue affects Fedora Workstation Live 37, at least on that Thinkpad.

**Comment by marmarek** [comment]
Installation ISO with MBR partition table (but still using grub2 for legacy, nothing else changed) works just fine. And then installed system does not boot, I guess that's also because of GPT. A this point, it's pretty clear it's indeed GPT to blame, even though in theory it should work (the boot sector is populated with legacy boot code).
It's this change in Fedora: https://www.fedoraproject.org/wiki/Changes/GPTforBIOSbyDefault
I'm going to revert the whole thing.

**Comment by marmarek** [comment]
The closest upstream issue about the same thing: https://bugzilla.redhat.com/show_bug.cgi?id=2140385

**Comment by marmarek** [comment]
Additionally, GPT on legacy is incompatible with some versions of Heads. Not because of GPT itself, but because anaconda creates "BIOS boot" as the first partition (which is correct thing to do to boot legacy with GPT), but Heads expects the first partition to be /boot.

**Comment by rustybird** [comment]
That must also make Heads incompatible with > 2 TiB drives: Even the R4.1.0 installer automatically uses GPT in this case, and creates the BIOS Boot partition.

**Comment by marmarek** [comment]
> That must also make Heads incompatible with > 2 TiB drives: Even the R4.1.0 installer automatically uses GPT in this case, and creates the BIOS Boot partition.

This only means you need newer Heads, the issue applies only to older versions.

**Comment by GWeck** [comment]
I checked now with the installation file `Qubes-4.2.202303010603-x86_64.iso`. Installation could be started and configured from legacy BIOS on my HP EliteBook 840 G4. So it works now. Thanks a lot! (I did not really start the installation, because then I would have lost my current test system.)

**Comment by GWeck** [comment]
Installation media for R4.1.2-rc2 is o.k., too.
