### ISSUE TITLE
Qubes Canary 034 published with Qubes Canary 033 information

### ISSUE THREAD

**Issue by lubellier** [QubesOS/qubes-issues#8068]
### Qubes OS release
4.1

### Brief summary
The [published Qubes Canary 034](https://www.qubes-os.org/news/2023/03/02/canary-034/) is not the same as the [committed Qubes Canary 034](https://github.com/QubesOS/qubes-secpack/blob/main/canaries/canary-034-2023.txt).

### Steps to reproduce
Read the [published Qubes Canary 034](https://www.qubes-os.org/news/2023/03/02/canary-034/).

### Expected behavior
Qubes Canary 034 with 01-mar- 2023 date and `0000000000000000000318ff864e5cd9bc1fe1883911695a6c9a295203732b4b` blockchain id.

### Actual behavior
Qubes Canary 034 with 04-dec-2022 date and `00000000000000000000955f2976b1fbff0d0c47c262ea3ae6410e43f8218fb7` blockchain id.

**Comment by andrewdavidwong** [comment]
Ah, that's my mistake. Thank you for reporting this.

**Comment by andrewdavidwong** [comment]
To be clear: This was just me being dumb and forgetting to copy/paste the new canary text after substituting "033" for "034" in the announcement text and rewriting the announcement portion. It has nothing to do with the original canary file in the [Qubes security pack (qubes-secpack)](https://www.qubes-os.org/security/pack/) or the signatures on that file, which everyone is always encouraged to verify. :)
