### ISSUE TITLE
Omit version numbers from default disposable template names

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#8071]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### The problem you're addressing (if any)

Suppose the user has the following setup:

```
fedora-36
fedora-36-dvm (based on fedora-36)
```

Now, suppose Fedora 36 reaches EOL, so the user installs Fedora 37. The user now has:

```
fedora-36
fedora-36-dvm (based on fedora-36)
fedora-37
```

Of course, the user also wants to switch the disposable template to the new template, so the user does so and uninstalls the no-longer-needed Fedora 36 template. The user now has:

```
fedora-36-dvm (based on fedora-37)
fedora-37
```

**Problem:** The name `fedora-36-dvm` is now misleading, because it contains `fedora-36` when it's actually based on `fedora-37`.

### The solution you'd like

As @marmarek suggested in https://github.com/QubesOS/qubes-doc/pull/1297#issuecomment-1454343087, simply refrain from putting version numbers in default disposable template names. Instead of names like `fedora-36-dvm`, name them something like:

```
disposable-template
default-disposable-template
fedora-disposable-template
fedora-dvm
default-dvm
dvm-fedora
dvm-default
```

### The value to a user, and who that user might be

When [upgrading templates to avoid EOL](https://www.qubes-os.org/doc/how-to-update/#upgrading-to-avoid-eol), users will be able to perform the [switch everything to the new/upgraded template](https://www.qubes-os.org/doc/templates/#switching) step more easily.

**Comment by GWeck** [comment]
I personally would prefer something like `default-dvm` and `fedora-dvm` because these shorter names would fit better into the columns of the Qube Manager.
