### ISSUE TITLE
R4.2: Packages occasionally fail to install in dom0 with `qrexec-policy-daemon` complaining about an unexpected file

### ISSUE THREAD

**Issue by proudmuslim-dev** [QubesOS/qubes-issues#8072]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

R4.2 (alpha)

### Brief summary

When attempting to install a package (in this case `plasma-workspace`), qrexec-policy-daemon complains about the updateVM sending an unexpected file and the update fails.

### Steps to reproduce

* Download the latest ISO from https://qubes.notset.fr/iso/ (`Qubes-4.2.202303010603-x86_64.iso` at the time of writing)
* Install Qubes OS normally, but only choose Fedora templates and uncheck the box for sys-usb 
    * Note: The latter half of that shouldn't change anything, but I'm just writing down what I did for the record's sake
* Attempt to install a package from dom0; I ran `sudo qubes-dom0-update plasma-workspace`

### Expected behavior

Package installs with no issues

### Actual behavior

Package fails to install, with the following error(s) received from checking `qrexec-policy-daemon`'s status:

```
Mar 04 19:33:46 dom0 qubes.ReceiveUpdates+-sys-firewall[11931]: Domain sys-firewall sent unexpected file
Mar 04 19:33:46 dom0 qrexec-policy-daemon[11929]: Domain sys-firewall sent unexpected file
```

Some odd behavior I want to note: while the `plasma-workspace` package throws this error every time I try to install it (even if I pass `--clean`), smaller packages like neofetch only throw it sometimes, and they seem to start doing it after `plasma-workspace` makes it throw the error for the first time, if that makes sense.

I'd also like to note that I initially ran into this issue when I was tinkering with the GUI domain, and so I assumed that the issue was caused by something I had inadvertently done. I reinstalled and the error persisted, at which point I decided to open this issue

**Comment by proudmuslim-dev** [comment]
I should also state that journalctl provides nothing of use

**Comment by marmarek** [comment]
Which version of qubes-core-dom0-linux do you have? Similar issue was fixed in [4.2.5](https://github.com/QubesOS/updates-status/issues/3574)

**Comment by proudmuslim-dev** [comment]
Just checked, it's 4.2.4

**Comment by proudmuslim-dev** [comment]
Upgraded to 4.2.5 via the testing repos and the issue appears to be resolved @marmarek

**Comment by proudmuslim-dev** [comment]
Messed around for a little bit, it's been working flawlessly- I'm closing this issue now if that's alright, thank you for your help :)

![2023-03-04_21-14](https://user-images.githubusercontent.com/69869443/222942939-8889ca60-d117-411d-94e9-ed3b9fc7e078.png)
