### ISSUE TITLE
Backup restore finishes with error: `failed to decrypt [...]: b'scrypt: Passphrase is incorrect`

### ISSUE THREAD

**Issue by akkuladezeit** [QubesOS/qubes-issues#8083]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
Qubes Release 4.1.1

### Brief summary
Trying to backup and restore some Applications VM from an NVME to an HDD(destination)

### Steps to reproduce
1. Start gui to Create a Backup
2. Select VMs (in my Case 2 VMs with  Finaly 5gb
3. Select Location in dom0 (second HDD)
4. enter password 
5. Start backup and wait for finish
6. Start restore gui 
7. select file from dom0 ( second HDD) 
8. enter password
9. Check "Test restore to verify Backup..."
10. starte restore

Error Massagea After a While a error is displayed "b'scrypt passphrase is incorrect" -> picuture

![image](https://user-images.githubusercontent.com/10156867/223824447-24a9ea00-0819-4868-858d-ce6093e5ca83.jpeg)

### Expected behavior
Backup and verify the Backup in restore Should work without error 

### Actual behavior
Verify of backup and restoring is Not Working

**Comment by andrewdavidwong** [comment]
This appears to be a [duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) of #4493 and/or #6227. If so, please comment on the appropriate existing issue instead. If anyone believes this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.
