### ISSUE TITLE
DispVM not picking correct default app to open file

### ISSUE THREAD

**Issue by ClaraCrazy** [QubesOS/qubes-issues#8089]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

R4.1 (dom0 testing, templates testing)

### Brief summary

Got a client in my disp template, set it as default for the filetype its supposed to handle, shut down the template and set "open in dispvm" as default on all other qubes for this file. Double-click it, dispvm launches, and... firefox? The interesting thing is that once firefox "downloaded" it to some place in the dispvm, I can launch the file just fine. I'm not sure if im doing something wrong or where firefox comes to play in this. [The forum had something similar](https://forum.qubes-os.org/t/qvm-open-in-dvm-in-application-other-than-firefox/7945), but that was resolved and from what I can tell, its different.

If im just missing something, I apologize.

### Steps to reproduce

- Get IcedTea java client into dispvm template
- set jnlp file to open with it
- "Open in dispvm" a .jnlp file from any qube

### Expected behavior

- File runs in correct app right away

### Actual behavior

- file goes through firefox first, before running in its expected application

-----
<details>
<summary>Unrelated, unsure how to handle</summary>
while trying to debug this issue I noticed that "open in dispvm" is available in dispvm templates which will create a "forkbomb". Please let me know whether to open another issue for this / how to handle this, as I believe this option should not be available in these templates
</details>

**Comment by GWeck** [comment]
I have the same effect whenever I try to open a file whose app was installed as an application running in a Fedora VM under Wine, e.g. Excel. Instead of Excel, Firefox opens, and if Firefox is set up correctly, it then will open the target app, e.g. Excel.

No drama, but somewhat annoying. In this scenario, only Wine applications behave that way, any other work as expected.

**Comment by unman** [comment]
It would hep if you said *how* you set the client as default, and what
file type you specified.
Also, how are you sourcing those .jnlp files?
Could you provide an example?

In many cases like this, the file type *as seen in the disposable* is not
what you think it is.

**Comment by ClaraCrazy** [comment]
> It would hep if you said *how* you set the client as default, and what
> file type you specified.
> Also, how are you sourcing those .jnlp files?
> Could you provide an example?
> 
> In many cases like this, the file type *as seen in the disposable* is not
> what you think it is.
> 

- Nautilus is used to set as default
- It is a jnlp, as you correctly mention yourself
- I cannot, as it is company files. They are connectwise control clients which I am unable to share. Why they use an outdated tech on linux is what im unsure of, however thats something to open an issue over at their place

**Comment by ClaraCrazy** [comment]
> I have the same effect whenever I try to open a file whose app was installed as an application running in a Fedora VM under Wine, e.g. Excel. Instead of Excel, Firefox opens, and if Firefox is set up correctly, it then will open the target app, e.g. Excel.
> 
> No drama, but somewhat annoying. In this scenario, only Wine applications behave that way, any other work as expected.

interesting, sadly not the case for me. IcedTea installs via dnf and is a regular package, albeit legacy tech at this point, which shouldnt be used anymore. Hence the dispvm among other reasons

but yes, I agree. No drama, just annoying
