### ISSUE TITLE
qubes-dom0-update: Unable to detect release version (use '--releasever' to specify release version)

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#8092]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

4.1

### Brief summary

Executing `qubes-dom0-update` starts a terminal in the update qube that prints `Unable to detect release version (use '--releasever' to specify release version)`, then proceeds to update.

### Steps to reproduce

Execute `qubes-dom0-update` in dom0.

### Expected behavior

The system is able to detect its own release version.

### Actual behavior

An xterm window opens in the update qube. At the top, `Unable to detect release version (use '--releasever' to specify release version)` is printed. The update then appears to proceed normally, but I can't confirm that.

### Related thread

https://forum.qubes-os.org/t/question-on-qubes-dom0-update/17361/

**Comment by unman** [comment]
This is a spurious warning (certainly with Debian updateVM) and I
thought it had been reported before.
The update does proceed normally.

**Comment by unman** [comment]
I was thinking of #7229

**Comment by andrewdavidwong** [comment]
> This is a spurious warning (certainly with Debian updateVM) and I thought it had been reported before. The update does proceed normally.

> I was thinking of #7229

Thank you. I, too, thought it had already been reported, but that issue didn't turn up in my search because it failed to include the full warning message. I'll now close this as a [duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) of #7229. If anyone believes this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.
