### ISSUE TITLE
promote weekly iso builds on https://www.qubes-os.org/doc/testing/

### ISSUE THREAD

**Issue by h01ger** [QubesOS/qubes-issues#8106]
### The problem you're addressing (if any)

qubes 4.2 images for testing are hard to find and are also useful for new users, to see if their hardware, which might not work with qubes 4.1, works with 4.2

### The solution you'd like

add a link to (currently) https://qubes.notset.fr/iso/ on https://www.qubes-os.org/doc/testing/

### The value to a user, and who that user might be

a.) see problem description :) 
b.) experienced qubes users who want to help testing the next release

**Comment by andrewdavidwong** [comment]
I've added an entry to this list (https://github.com/QubesOS/qubes-doc/commit/eee9a0742045bdcaa0a1140e1851cc02eee2ddda). Is this what we want? Do we want to something more?

I considered calling them "[Frédéric's](https://www.qubes-os.org/team/#fr%C3%A9d%C3%A9ric-pierret) weekly builds," but I didn't want people to spam @fepitre (even more than usual) with questions and problems they encounter while using the ISOs simply because his name was the one they saw next to the link. :)

**Comment by fepitre** [comment]
Please wait a little bit because there is some changes on going. I've setup a new build infra similar to official one and contrib one, to build ISO. They will be built in the same workflow that official one and they will have a dedicated is signing key. Stay tuned.

**Comment by andrewdavidwong** [comment]
> Please wait a little bit because there is some changes on going. I've setup a new build infra similar to official one and contrib one, to build ISO. They will be built in the same workflow that official one and they will have a dedicated signing key. Stay tuned.

Okay, reverting commit.

**Comment by unman** [comment]
Users will see this and, unless there is a string health warning, grab
them on the basis that "latest is best".
I think that "not for production" is not strong enough and is unclear.
As I cannot see the proposed text, this may already be covered.
I would suggest - "weekly builds, for testing only", and some explanation
of *why* they may be wanted, and *what the issues may be".

**Comment by marmarek** [comment]
FWIW, those are not random cloud CI builds anymore, those use dedicated trusted builder, with similar architecture as the official one. It's just maintained by another core team member, not me.

The not for production use relates mostly to R4.2 not being stable supported release yet (for example, we don't provide security patches timely for it yet).

**Comment by fepitre** [comment]
As of today, new ISOs for 4.2 can be found through https://github.com/fepitre/updates-status-iso/issues. ISO are built like @marmarek said, in a dedicated build machine like how the official ones are done. They can be downloaded at https://qubes.notset.fr/iso-testing/ and I've uploaded the dedicated signing key https://qubes.notset.fr/iso-testing/qubes-weekly-builds-signing-key.asc

**Comment by fepitre** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

The fingerprint for Qubes OS R4.2 Weekly Builds Signing Key is: 9B7E61D3BB70C4B1335CE5B67B72A119CCCA57BB
-----BEGIN PGP SIGNATURE-----

iQIyBAEBCAAdFiEEn6ZLkvlecGvyjiymSEAQtc3FduIFAmQjWAgACgkQSEAQtc3F
duIP1Q/4/TZXL/vIhp8jyg+MzM/AqV1cy6Jh5E9nchFPpN0nJgh1vTtrb87ttSSa
6OkZviXgu+UOEtIWdK4b6BM9O08c4f/JM31FsVmUqEl39wW9cd5to6cGl9Sbo2af
1TytegS0M63O+6yr0uKtbwlbVt5e/1cRcquxWAFbEHLoUNye1n7mfJyi+40Y9IR2
RSP6UCMzFtYRv/NY8Z+OF9UeHQZyECWspCsZ3jFblQrl9E84nwB9fPV2TC7j1BZR
EwaH91+wiPATKrwV+LkEnu+joYtBQCxJOvUTjBVbR0JbAfzpI9XVp+/Ix23/7YHm
ixR1a8No1AlFNk5gLDjEsXEk8j6V2XjRDMigyASy20qJOdMVGcPVEsAQM3z8jEst
7YdOqXAEdD2eWLcjnCo8NIDFTjjUc1RfxwWmdElEZZqZfNXobV0/SqLecvGjysu5
wQq7If+yb1iOv0w4GnAAkZQfz51EdMwKJL88lsOb1os5qqsomDM6DAvND5V3mrgk
+WTXSZGEMMll/0NeOZiFcVEO+gm7jq409DoNTroOBBaDNIjeqg7uLhxaDNbzSeWF
ijvTG2qBiJqg54c1QurdHIhw2nJ7j8wo+8agD/q6Wzb2x/a03jDVSQ0nr0+mNz79
3OrGUKnjtnqMYvtazVzcPKq5J5O7b0ymoZicMqkVzwDppZhnCQ==
=4+8f
-----END PGP SIGNATURE-----

**Comment by andrewdavidwong** [comment]
@fepitre, does this mean that I should go ahead and list your signed weekly builds on the [testing](https://www.qubes-os.org/doc/testing/) page and close out this issue now?

**Comment by fepitre** [comment]
> 

Yes please. And especially, I'm referencing testing page inside issues like here: https://github.com/fepitre/updates-status-iso/issues/55.
