### ISSUE TITLE
Security flaw in how dom0 is perceived

### ISSUE THREAD

**Issue by ghost** [QubesOS/qubes-issues#8107]
### Qubes OS release
Every

### Brief summary
It often happens that passwords are stored in plain text in dom0 "because dom0 is ultimately secure, and if it gets compromised it's game over anyway" . This for example appears in the yubikey configuration documentation, but is certainly used elsewhere in the security implementation of Qubes OS. This is wrong: one could have a Qubes OS computer which is empty and we don' t care about, in particular we might set a very easy user password and LUKS passphrase, and yet we might use as yubikey password some string which must not be compromised (because we might also use it for our email account etc). In this case, compromising dom0 doesn't matter but compromising the yubikey password does, and we better save this encrypted in dom0! My point is: in some use-cases we might not care about exposing dom0, and yet care about keeping some of our passwords secure. Therefore, the idea of pasting everything plain-text in dom0 under the assumption that when it gets compromised then we have nothing else to loose, is flawed!

**Comment by andrewdavidwong** [comment]
> [...] one could have a Qubes OS computer which is empty and we don't care about [...]

> In this case, compromising dom0 doesn't matter [...]

> My point is: in some use-cases we might not care about exposing dom0 [...]

IMHO, we simply don't support such use cases. Qubes OS is a security-oriented operating system, so it would make sense that it's intended only for use cases where its own security actually matters, and use cases that invalidate this fundamental assumption are simply out-of-scope.
