### ISSUE TITLE
Improve X2APIC compatibility with modern AMD platform

### ISSUE THREAD

**Issue by neowutran** [QubesOS/qubes-issues#8111]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

R4.2/R4.1

### Brief summary

With recent AMD platform, it is required to manually append the string "x2apic=false" in the boot command line of xen. 
Without that, the system won't start. 

A patch for the xen hypervisor have been suggested in that mailing list https://lists.xenproject.org/archives/html/xen-devel/2023-03/msg01434.html
It should improve the situation a bit. 
I am compiling it, will report later to confirm if it indeed improve the situation

**Comment by neowutran** [comment]
( To keep this issue up to date, I answered in the mailing list. This patch improve the situation (no need to append "x2apic=false" or others workaround in most bios configuration), but as noted by elliott, it does not completly solve the issue )

**Comment by neowutran** [comment]
A fix have been published by the xen project 

https://lists.xenproject.org/archives/html/xen-devel/2023-11/msg02373.html 

https://github.com/xen-project/xen/commit/e3c409d59ac87ccdf97b8c7708c81efa8069cb31

From what I understood it will be backported officially to xen 4.17. 
So we can wait for it to be backported officially or backport it ourself. 

I will probably soon send a pull request with my backport of this patch

**Comment by DemiMarie** [comment]
@neowutran That is amazing!

(FYI, your email client or server seems to be sending broken emails that either have lots of NUL bytes or trick `lore.kernel.org` into displaying `\0` repeated a lot.  It seems that `Content-Disposition` got split over two lines.)

**Comment by neowutran** [comment]
:) 

(thanks, it was indeed an encoding issue with my mail client, it should be fixed for the futures emails. But there is definitely a bug in lore.kernel.org. Do you known where I can sent them a bug report ?  )

**Comment by DemiMarie** [comment]
@neowutran https://lore.kernel.org uses <https://public-inbox.org>, so that’s where I would send the bug report.
