### ISSUE TITLE
Nautilus often hangs after start: Possible Regression in actual version v43.3-1?

### ISSUE THREAD

**Issue by umbratic** [QubesOS/qubes-issues#8115]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
Qubes OS 4.1.2 (R4.1), Fedora-37, fully updated

### Brief summary
Same as #7921 (closed).  But actual Nautilus version is 43.3-1.

After downgrading Nautilus from 43.3-1 to 43.2-4 the problem seems to have disappeared. Could this be a regression?

### Steps to reproduce
Launch Nautilus a couple of times. 

### Expected behavior
As in previous versions.

### Actual behavior
Often (not always) Nautilus locks up, no files shown, the spinner rotates indefinitely, high CPU load.

**Comment by mfc** [comment]
upgrade to latest `nautilus-43.3-4` should fix (just landed in stable), was an upstream regression (see linked issues/commits).

**Comment by andrewdavidwong** [comment]
Closing as resolved. If anyone believes this issue is not yet resolved, or if anyone is still affected by this issue, please leave a comment, and we'll be happy to reopen it. Thank you.
