### ISSUE TITLE
Error when attempting to create default Whonix disposable template: `Data failed to compile: No matching sls found for 'qvm-whonix-ws-dvm' in env 'base'`

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#8118]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

4.1

### Brief summary

Following the official instructions for creating a default Whonix disposable template results in an error.

### Steps to reproduce

Following the instructions here:

https://www.whonix.org/wiki/Qubes/Disposables#Create_a_Whonix_%E2%84%A2_Default_Disposable_Template_based_on_Whonix-Workstation_%E2%84%A2

1. Update Qubes-Whonix ™.
2. Open a dom0 terminal: Qubes App Launcher (blue/grey "Q") → System Tools → Xfce Terminal
3. Create whonix-ws-16-dvm Disposable Template.
   ```
   sudo qubesctl state.sls qvm.whonix-ws-dvm
   ```

### Expected behavior

Disposable template is created.

### Actual behavior

In dom0:

```
$ sudo qubesctl state.sls qvm-whonix-ws-dvm
local:
    Data failed to compile:
----------
    No matching sls found for 'qvm-whonix-ws-dvm' in env 'base'
DOM0 configuration failed, not continuing

```

CC: @adrelanos

**Comment by marmarek** [comment]
> `$ sudo qubesctl state.sls qvm-whonix-ws-dvm`

This command has a typo: `qvm-` vs `qvm.`.

**Comment by andrewdavidwong** [comment]
Ah, my mistake. Thank you. It didn't occur to me that this error message could be from a typo in the command. Also, I suppose a decade of `qvm-` muscle memory is hard to unlearn.
