### ISSUE TITLE
builderv2: `iso-full-online.ks` defined in `builder-devel.yml` does not exist

### ISSUE THREAD

**Issue by peakunshift** [QubesOS/qubes-issues#8122]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### The problem you're addressing (if any)
The README of `qubes-builderv2` project explains that we can use the provided development `builder-devel.yml` configuration file under `example-configs` folder as a `builder.yml` starting point. This file defines `conf/iso-full-online.ks` for the kickstart to build the iso, but this file does not exist.

### The solution you'd like
Use or rename `iso-online.ks` instead that exists in the `conf` folder (and update it if necessary), or find a way to use something similar to [`qubes-release-configs`](https://github.com/QubesOS/qubes-release-configs) and [`qubes-installer-qubes-os`](https://github.com/QubesOS/qubes-installer-qubes-os) repositories that defines config files for legacy builder.

### The value to a user, and who that user might be
For anyone starting to use the builverv2, being able to build the stable and testing release of QubesOS easily by following the README instructions.

**Comment by fepitre** [comment]
It's a matter of updating values. We have changed lot of things recently. We have not changed it every where in the documentation or examples.

**Comment by peakunshift** [comment]
I understand, I opened a PR to fix this: https://github.com/QubesOS/qubes-builderv2/pull/37.
