### ISSUE TITLE
Attaching a USB device to a qube results in admin messages about unrelated audio qube

### ISSUE THREAD

**Issue by neowutran** [QubesOS/qubes-issues#8123]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

R4.2.

probably R4.1 too 

### Brief summary / Steps to reproduce

Informations about USB devices are being sent to the audiovm. 

Example: 
We have 3 qubes:
- "sys-audio" -> the audiovm
- "sys-usb" -> manage the device "DeviceX"
- "qubeY" -> random qube

the user use the device manager gui in dom0 to attach the device named "DeviceX" to a qube named "qubeY". 
"sys-audio" will receive a notification of that event.  

### Expected behavior

audiovms have no reason to receive any kind of informations about usb devices

### Actual behavior

audiovms receive informations about usb devices

**Comment by unman** [comment]
What template are you using for the audio?
What form does the "notification of that event" take?

**Comment by neowutran** [comment]
I am using a fedora 37 template. 

notification of that event: 
- dom0 popup displaying "Denied: admin.vm.device.usb.Available from sys-audio to sys-usb"
- dom0 popup displaying "Failed: admin.Events from sys-audio to dom0"
