### ISSUE TITLE
Improve turning on services: ask to also enable in template

### ISSUE THREAD

**Issue by unman** [QubesOS/qubes-issues#8124]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### The problem you're addressing (if any)
The services pane rubric says "Selected services will be turned on".
This is not true, and may be confusing - this quote from qubes-users:
```
My expectation was that when selected in the "services" tab, qubesrc (or
any other instance) will just start the corresponding service in the VM.

```

### The solution you'd like
The rubric should make it clear that the service must be enabled in the template.

### The value to a user, and who that user might be
Clarity to all users.

**Comment by marmarta** [comment]
That sounds like it would be better to check when enabling services and automatically enable them if not enabled in template. It is an automatic step, so I think we should be doing it, not putting it on the user.

**Comment by marmarta** [comment]
Ok, after a check: all supported service work without needing that secondary enable, and manual describes those. The only case where this should be needed is if user manually put down a service that's not supported (as in Qubes' supported service) by the template. Not sure if clarifying that won't be more confusing...

**Comment by andrewdavidwong** [comment]
> That sounds like it would be better to check when enabling services and automatically enable them if not enabled in template. It is an automatic step, so I think we should be doing it, not putting it on the user.

I don't have the background knowledge to fully understand @unman's [reply](https://groups.google.com/g/qubes-users/c/cxvc6z3ZOV0/m/6LR-uHnPAgAJ) in the linked thread, but I gather that there are certain benefits to the "two-switch" model and that it is intentionally designed this way. Your proposal to automatically enable services in the template sounds like it would effectively change this to a "one-switch" model. Therefore, it sounds like you might inadvertently be proposing a much bigger change (with much broader ramifications) than you think you are, but I could be mistaken.

> Ok, after a check: all supported service work without needing that secondary enable, and manual describes those. The only case where this should be needed is if user manually put down a service that's not supported (as in Qubes' supported service) by the template. Not sure if clarifying that won't be more confusing...

Interesting. In the linked thread, @unman and Ron (the one who started the thread) both seem to agree that the system currently has a "two-switch" model, regardless of whether the service is a Qubes-supported service or not. By contrast, you seem to be saying that the system currently has a "one-switch" model for Qubes-supported services and a "two-switch" model for non-Qubes-supported services.

It sounds like everyone should first come to an agreement on how the system currently works before attempting to make any decisions about how to change it.

**Comment by marmarek** [comment]
> Interesting. In the linked thread, @unman and Ron (the one who started the thread) both seem to agree that the system currently has a "two-switch" model, regardless of whether the service is a Qubes-supported service or not. By contrast, you seem to be saying that the system currently has a "one-switch" model for Qubes-supported services and a "two-switch" model for non-Qubes-supported services.

There is a set of supported services, those can be selected from a drop-down in the settings, and those are also documented in the [`qvm-service` man page](https://dev.qubes-os.org/projects/core-admin-client/en/latest/manpages/qvm-service.html). For supported services, it's enough to simply *enable* them in the qube settings.

You can also *add* support for other services (be it systemd service of something else). For systemd services, we have it documented at https://www.qubes-os.org/doc/qubes-service/. After you *add* new service (which is a change in the template), then you can *enable* it the qube settings (custom services are not listed in the drop-down, so you need to choose "custom" and type its name manually).

**Comment by marmarta** [comment]
So now I think the question is how to improve the wording on Services tab to make it clearer it applies to supported services. I could add more info in the add custom box, e.g.:

Current:
"Name of the service:"

New:
"Name of the service:
Custom services may need to be enabled in the template separately."

**Comment by unman** [comment]
On Tue, May 16, 2023 at 04:22:04PM -0700, Andrew David Wong wrote:
> > That sounds like it would be better to check when enabling services and automatically enable them if not enabled in template. It is an automatic step, so I think we should be doing it, not putting it on the user.
> 
> I don't have the background knowledge to fully understand @unman's [reply](https://groups.google.com/g/qubes-users/c/cxvc6z3ZOV0/m/6LR-uHnPAgAJ) in the linked thread, but I gather that there are certain benefits to the "two-switch" model and that it is intentionally designed this way. Your proposal to automatically enable services in the template sounds like it would effectively change this to a "one-switch" model. Therefore, it sounds like you might inadvertently be proposing a much bigger change (with much broader ramifications) than you think you are, but I could be mistaken.
> 
> > Ok, after a check: all supported service work without needing that secondary enable, and manual describes those. The only case where this should be needed is if user manually put down a service that's not supported (as in Qubes' supported service) by the template. Not sure if clarifying that won't be more confusing...
> 
> Interesting. In the linked thread, @unman and Ron (the one who started the thread) both seem to agree that the system currently has a "two-switch" model, regardless of whether the service is a Qubes-supported service or not. By contrast, you seem to be saying that the system currently has a "one-switch" model for Qubes-supported services and a "two-switch" model for non-Qubes-supported services.
> 
> It sounds like everyone should first come to an agreement on how the system currently works before attempting to make any decisions about how to change it.

In that thread you link, we were talking about a very specific case.
By default the supported services are enabled in the template. All that
is required to make them work is to make sure that they are enabled in
the qube - qvm-features, qvm-service, or GUI - some are by default,
some require selection.

IF the service is disabled (in systemctl terms) in the template, then it
is not true that it will work JUST BY flipping the switch in the qube.

How might this happen? Well you might want to make sure that NONE of
the qubes using a specific template can run CUPS. Then you might want to
disable the cups service in the template.
In that circumstance cups will feature in a qube GUI as an available
service but enabling it will do absolutely nothing.

It's in this sense that we were discussing a "two-switch" model: enabled
in the template, AND turned on in the qube.
I don't think there is any disagreement about this: for most users, (who
wont be fiddling in the templates), the issue will never arise.

The idea of making service enabling an automatic step is good.

**Comment by marmarek** [comment]
> How might this happen? Well you might want to make sure that NONE of the qubes using a specific template can run CUPS.

For this specific case, this is changed in R4.2, by _not_ starting CUPS by default (#5179). It will run only when explicitly enabled via qvm-service.
