### ISSUE TITLE
RTL8821CE WIFI Controller crashes sys-net

### ISSUE THREAD

**Issue by hadmut** [QubesOS/qubes-issues#8126]
Hi, 
some time ago I have installed QubesOS 4.1 on a HP notebook, but didn't do much with that particular machine. Now I went through upgrading the machine, dom0, templates, VMs and downloaded the fedora-37 image. After setting sys-net to use fedora-37 instead of fedora-34  (not sure, whether this or upgrading dom0 was the reason), sys-net didn't run anymore. When starting, it ran for some seconds, and then shut itself down again, error message that the manager can't connect to the VM. 

For unknown (i.e. not obvious) reasons, sys-net repeatedly crashed some seconds after booting, while the underlying fedora-37 template itself boots well. The console log did not reveal any reason. Even switching back to fedora-34 did not help. But when using debian-11 instead, it showed that there is a kernel crash right after loading the rtl88 driver.  A Null pointer exception. 

After removing the RTL8821CE Wifi Controller PCIe device from the device list, sys-net worked normally again with both, debian-11 and fedora-37 as underlying templates (but of course, ethernet only, no Wifi). 

So there is currently a problem with this Wifi chip causing sys-net to not boot, and thus not having network access to download patches. 

regards

**Comment by pasajeros** [comment]
I have this problem as well on my Lenovo IdeaPad laptop.

**Comment by ProGamer2508-0** [comment]
HI. I too have the same problem, but this issue is a copy of another older issue which also concerns 4.2 (basically the same hardware and the same poorly made driver that doesn't work. It's not a hardware problem in truth, but of the driver that QubesOS still keeps in its database)

**Comment by ProGamer2508-0** [comment]
#8471

**Comment by ProGamer2508-0** [comment]
before creating a new post on this issue you should always check if there is a post similar to the problem encountered

**Comment by ProGamer2508-0** [comment]
anyway... this problem hasn't been solved for years. see the post I mentioned to see how much is ignored

**Comment by ProGamer2508-0** [comment]
> see the post I mentioned to see how much is ignored

from the dev I mean

**Comment by ProGamer2508-0** [comment]
in the post there are also problems that arise from this problem (for example that at the time of installation, sys-usb is not created... and that it cannot be created in normal ways in post-installation)

**Comment by ProGamer2508-0** [comment]
> @ProGamer2508-0: Please refrain from making multiple separate comments on an issue in quick succession. Instead, you can use the edit function to add to a comment that was made recently.

Sorry. I got used to writing messages like this. from this moment on I will write in the issues in the way you said
