### ISSUE TITLE
Updater misses restarting disposable sys-usb/sys-firewall

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#8133]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

R4.2

### Brief summary

After updating a template that's used for disposable sys-usb/sys-firewall, those qubes are not proposed to be restarted.

### Steps to reproduce

1. Run updater, select the template used for a disposable sys-usb.
2. After the update, see list of VMs proposed to update.

### Expected behavior

sys-usb and sys-firewall is included.

### Actual behavior

They are not, but for example sys-net is (if it isn't disposable).
The trick is that disposable sys-usb (or any other disposable qube) has an AppVM as a template (for example fedora-37-dvm) and only that AppVM has a TemplateVM as the template. So, there is an extra indirection.

BTW, I tried this in GUI, but I guess the same applies to CLI.

**Comment by DemiMarie** [comment]
Also assigning to @marmarta as the domains widget has the same problem.

**Comment by marmarek** [comment]
> Also assigning to @marmarta as the domains widget has the same problem.

No, the bug is about different functionality (unrelated to domains widget really).
