### ISSUE TITLE
Display Keyboard Layout on Screensaver and Login Screen

### ISSUE THREAD

**Issue by im7mortal** [QubesOS/qubes-issues#8135]
### The problem

Many users who use multiple keyboard layouts, often face difficulties when entering passwords. As strong passwords are encouraged, it's common for users to make mistakes when typing them. While users can typically correct their mistakes after a few tries, the process can be frustrating and time-consuming.

The problem is exacerbated when a non-default keyboard layout is active, causing the user to enter incorrect characters without realizing it. **Users then have to blindly switch layouts** using shortcuts to try again.

![20230411_111917](https://user-images.githubusercontent.com/5336231/231149736-206ec676-6a47-4b5d-be96-a2ffde7ff7aa.jpg)

This morning I had one of these situations I had 6 attempts before I could login back.

![20230411_111934](https://user-images.githubusercontent.com/5336231/231149780-b975de08-af12-46f4-a622-ab05ca8bad49.jpg)

### The solution you'd like
In other operating systems, such as Ubuntu Linux and Windows, users can see the current keyboard layout in the system tray and even switch between layouts directly. Implementing a similar feature would provide users with a clear indication of their active keyboard layout, helping to prevent login errors and improve the overall user experience.
![20230411_111902](https://user-images.githubusercontent.com/5336231/231149760-61ad2014-136b-4310-ac68-9c498decd469.jpg)

### The value to a user, and who that user might be
By introducing a visible keyboard layout indicator and the ability to switch layouts directly from the login screen, users who work with multiple layouts would experience a smoother and more efficient login process. This feature would be particularly beneficial for non-native English speakers and users who frequently switch between different keyboard layouts. By reducing the number of failed login attempts and improving the overall experience, this enhancement would make the system more user-friendly and accessible to a wider range of users.

**Comment by andrewdavidwong** [comment]
This appears to be a [duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If anyone believes this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.
