### ISSUE TITLE
Salt can exit with status 0 even when it clearly failed

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#8146]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

R4.1

### Brief summary

Sometimes Salt will experience a JSON rendering error but exit with status 0.

### Steps to reproduce

This does not reproduce reliably, but the following is a log snippet from when it did (with timestamps removed):

    calling 'state.highstate'...
    output: fedora-36:
    output: [WARNING ] top_file_merging_strategy is set to 'merge' and multiple top files were found. Merging order is not deterministic, it may be desirable to either set top_file_merging_strategy to 'same' or use the 'env_order' configuration parameter to specify the merging order.
    output: [ERROR   ] JSON Render failed for:
    output: Traceback (most recent call last):
    output:   File "/var/tmp/.root_dd8a91_salt/salt-call", line 27, in <module>
    output:   File "/var/tmp/.root_dd8a91_salt/pyall/salt/scripts.py", line 441, in salt_call
    output:   File "/var/tmp/.root_dd8a91_salt/pyall/salt/cli/call.py", line 50, in run
    output:   File "/var/tmp/.root_dd8a91_salt/pyall/salt/cli/caller.py", line 95, in run
    output:   File "/var/tmp/.root_dd8a91_salt/pyall/salt/cli/caller.py", line 202, in call
    output:   File "/var/tmp/.root_dd8a91_salt/pyall/salt/loader/lazy.py", line 149, in __call__
    output:   File "/var/tmp/.root_dd8a91_salt/pyall/salt/loader/lazy.py", line 1228, in run
    output:   File "/var/tmp/.root_dd8a91_salt/pyall/salt/loader/lazy.py", line 1243, in _run_as
    output:   File "/var/tmp/.root_dd8a91_salt/pyall/salt/executors/direct_call.py", line 10, in execute
    output:   File "/var/tmp/.root_dd8a91_salt/pyall/salt/loader/lazy.py", line 149, in __call__
    output:   File "/var/tmp/.root_dd8a91_salt/pyall/salt/loader/lazy.py", line 1228, in run
    output:   File "/var/tmp/.root_dd8a91_salt/pyall/salt/loader/lazy.py", line 1243, in _run_as
    output:   File "/var/tmp/.root_dd8a91_salt/pyall/salt/modules/state.py", line 2305, in pkg
    output:   File "/var/tmp/.root_dd8a91_salt/pyall/salt/modules/state.py", line 103, in _set_retcode
    output:   File "/var/tmp/.root_dd8a91_salt/pyall/salt/loader/context.py", line 78, in __getitem__
    output:   File "/var/tmp/.root_dd8a91_salt/pyall/salt/loader/lazy.py", line 336, in __getitem__
    output:   File "/var/tmp/.root_dd8a91_salt/pyall/salt/utils/lazy.py", line 105, in __getitem__
    output: KeyError: 'state.check_result'
    output: [ERROR   ] Expecting value: line 1 column 1 (char 0)
    exit code: 0

### Expected behavior

Non-zero exit code

### Actual behavior

Zero exit code

**Comment by lkubb** [comment]
This should finally be fixed in the next major Salt release (`3007.0`) with the inclusion of https://github.com/saltstack/salt/pull/64542 (among some other `salt-ssh` fixes, most of which are also found in `3006.5`).

**Comment by DemiMarie** [comment]
Can these fixes be backported to the version Qubes OS uses?

**Comment by marmarek** [comment]
It's about salt version in the template for default-mgmt-dvm, it will come there eventually via relevant distribution. In fact, 3006.5 is already in testing repo for fc38+.

**Comment by DemiMarie** [comment]
To avoid confusion: dom0 won’t get a new Salt as Fedora 37 is end of life, but dom0 doesn’t use salt-ssh, so it isn’t affected.
