### ISSUE TITLE
Qubes Global Settings fails to open in `sys-gui` (GUI domain)

### ISSUE THREAD

**Issue by isaaccatron** [QubesOS/qubes-issues#8152]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
Qubes R4.1.2
All related Qubes templates are up to date

### Brief summary
I was wanting to change the keybinds for my interqube copying and pasting but when I went to change the setting in Qubes Global Settings I got an error.

### Steps to reproduce

1. Install Sys-GUI through normal methods
2. Open Qubes Global Settings

### Expected behavior
Be able to open Qubes Global Settings and edit settings

### Actual behavior
Prints out error
`Attribute Error: 'int' object has no attribute at line 33 of file /usr/bin/qubes-global-settings`

**Comment by marmarta** [comment]
I tried to test it a couple of times, and can't reproduce this (the linked PR is sadly, a mistake). Could you try to run qubes-global-settings in console and paste the traceback?

**Comment by marmarta** [comment]
Never mind, asking is the best way to reproduce a bug :D Fix on its way.
