### ISSUE TITLE
Changing VM network via Qube Manager context menu crashes Qube Manager

### ISSUE THREAD

**Issue by lesliesmith** [QubesOS/qubes-issues#8156]
### Brief summary
Changing VM network via Qube Manager context menu crashes Qube Manager if netVM isn't running.

### Steps to reproduce
1. Start a DispVM or any appVM dependent on sys-firewall for netVM.
2. Start Qube Manager.
3. Change DispVM's network from sys-firewall to none with Qube Manager context menu.
4. Shutdown sys-firewall.
3. Change DispVM's network from none to default (sys-firewall) Qube Manager. 

### Expected behavior

1. Network setting for DispVM will change to sys-firewall.
1. Sys-firewall will automatically start.

Or less preferred expected response:
An error message will popup explaining the sys-firewall must be started to change netVM to sys-firewall.

### Actual behavior

1. Network setting for DispVM does not change to sys-firewall.
2. Qube Manager crashes and disappears from screen.

### Additional context

After updating templates while browsing in DispVM, I wanted to restart sys-net and sys-usb, which is easy enough to do by shutting down sys-firewall and restarting sys-net and sys-usb.  If  am willing to shutdown the DispVM then I can do that and then shutdown sys-firewall and restart sys-net and sys-usb.  If I start a new DispVM then sys-firewall starts up automatically.  

If I am not willing to shutdown the DispVM then simply changing the network to none allows me to preserve what I am doing and also shutdown sys-firewall and restart sys-net and sys-usb.  And if I start another appVM or dispVM sys-firewall will automatically be started and I can change my DispVM network back to default (sys-firewall) via Qube Manager context menu and it works with no crashing.  

Only when I didn't realize that sys-firewall hadn't been restarted did I see this issue.  

journalctl entries (edited)

    Apr 27 14:01:01 dom0 run-parts[74217]: (/etc/cron.hourly) finished 0anacron
    Apr 27 14:08:25 dom0 qubesd[3479]: socket.send() raised exception.
    Apr 27 14:08:25 dom0 qubesd[3479]: socket.send() raised exception.
    Apr 27 14:08:25 dom0 qubesd[3479]: socket.send() raised exception.
    Apr 27 14:08:25 dom0 qubesd[3479]: socket.send() raised exception.
    Apr 27 14:08:25 dom0 qubesd[3479]: socket.send() raised exception.
    Apr 27 14:08:25 dom0 qubesd[3479]: socket.send() raised exception.
    Apr 27 14:08:25 dom0 qubesd[3479]: socket.send() raised exception.
    Apr 27 14:08:25 dom0 qubesd[3479]: socket.send() raised exception.
    Apr 27 14:08:25 dom0 qubesd[3479]: socket.send() raised exception.
    Apr 27 14:08:25 dom0 qubesd[3479]: socket.send() raised exception.
    Apr 27 14:08:25 dom0 python3[74241]: Traceback (most recent call last):
                                       File "/usr/lib/python3.8/site-packages/qubesmanager/qube_manager.py", line 898, in change_network
                                         delattr(info.vm, 'netvm')
                                       File "/usr/lib/python3.8/site-packages/qubesadmin/base.py", line 389, in __delattr__
                                         self.qubesd_call(
                                       File "/usr/lib/python3.8/site-packages/qubesadmin/base.py", line 76, in qubesd_call
                                         return self.app.qubesd_call(dest, method, arg, payload,
                                       File "/usr/lib/python3.8/site-packages/qubesadmin/app.py", line 765, in qubesd_call
                                         return self._parse_qubesd_response(return_data)
                                       File "/usr/lib/python3.8/site-packages/qubesadmin/base.py", line 111, in _parse_qubesd_response
                                         raise exc_class(format_string, *args)
                                     qubesadmin.exc.QubesVMNotStartedError: Cannot dynamically attach to stopped NetVM: 
         <DispVM at 0x722ebdbad820 name='sys-firewall' qid=7 auto_cleanup=False autostart=True backup_timestamp=1682288203 debug=False default_user=user dispid=8966 dns=IP.AD.DRESS.1 IP.AD.DRESS.2 gateway=IP.AD.DRESS.6 gateway6=None icon=servicevm-green include_in_backups=True installed_by_rpm=False ip=IP.AD.DRESS.6 ip6=None kernel=5.15.103-1.fc32 keyboard_layout=us++ klass=DispVM label=green mac=MA:CA:DD:RE:SS:00 maxmem=4000 memory=500 provides_network=True qrexec_timeout=60 shutdown_timeout=60 start_time=None stubdom_mem=None stubdom_xid=-1 updateable=False uuid=UUID vcpus=2 virt_mode=pvh visible_gateway=IP.AD.DRESS.24 visible_gateway6=None visible_ip=IP.AD.DRESS.6 visible_ip6=None visible_netmask=255.255.255.255 xid=-1 audiovm=dom0 default_dispvm=fed-37-dvm guivm=dom0 kernelopts= management_dispvm=default-mgmt-dvm netvm=sys-net template=fed-37-dvm>
    Apr 27 14:08:25 dom0 kernel: audit: type=1701 audit(1682629705.997:1287): auid=1000 uid=1000 gid=1001 ses=3 pid=74241 comm="qubes-qube-mana" exe="/usr/bin/python3.8" sig=6 res=1
    Apr 27 14:08:25 dom0 audit[74241]: ANOM_ABEND auid=1000 uid=1000 gid=1001 ses=3 pid=74241 comm="qubes-qube-mana" exe="/usr/bin/python3.8" sig=6 res=1
    Apr 27 14:08:26 dom0 audit: BPF prog-id=56 op=LOAD
    Apr 27 14:08:26 dom0 audit: BPF prog-id=57 op=LOAD
    Apr 27 14:08:26 dom0 audit: BPF prog-id=58 op=LOAD
    Apr 27 14:08:26 dom0 kernel: audit: type=1334 audit(1682629706.017:1288): prog-id=56 op=LOAD
    Apr 27 14:08:26 dom0 kernel: audit: type=1334 audit(1682629706.017:1289): prog-id=57 op=LOAD
    Apr 27 14:08:26 dom0 kernel: audit: type=1334 audit(1682629706.017:1290): prog-id=58 op=LOAD
    Apr 27 14:08:26 dom0 systemd[1]: Started Process Core Dump (PID 74263/UID 0).
    Apr 27 14:08:26 dom0 kernel: audit: type=1130 audit(1682629706.019:1291): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-coredump@5-74263-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
    Apr 27 14:08:26 dom0 audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-coredump@5-74263-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
    Apr 27 14:08:26 dom0 systemd-coredump[74266]: Process 74241 (qubes-qube-mana) of user 1000 dumped core.
                                              
                                              Stack trace of thread 74241:
                                              #0  0x00007e8fc59377d5 raise (libc.so.6 + 0x3c7d5)
                                              #1  0x00007e8fc5920895 abort (libc.so.6 + 0x25895)
                                              #2  0x00007e8fc4010a7f _ZNK14QMessageLogger5fatalEPKcz (libQt5Core.so.5 + 0x91a7f)
                                              #3  0x00007e8fc4557bf2 _Z15pyqt5_err_printv.cold (QtCore.so + 0xbdbf2)
                                              #4  0x00007e8fc46bcbdd _ZN13PyQtSlotProxy7unislotEPPv (QtCore.so + 0x222bdd)
                                              #5  0x00007e8fc46bd767 _ZN13PyQtSlotProxy11qt_metacallEN11QMetaObject4CallEiPPv (QtCore.so + 0x223767)
                                              #6  0x00007e8fc4208bb8 _Z10doActivateILb0EEvP7QObjectiPPv (libQt5Core.so.5 + 0x289bb8)
                                              #7  0x00007e8fc10c2876 _ZN7QAction9triggeredEb (libQt5Widgets.so.5 + 0x16b876)
                                              #8  0x00007e8fc10c5161 _ZN7QAction8activateENS_11ActionEventE (libQt5Widgets.so.5 + 0x16e161)
                                              #9  0x00007e8fc1242d3a _ZN12QMenuPrivate19activateCausedStackERK7QVectorI8QPointerI7QWidgetEEP7QActionNS7_11ActionEventEb (libQt5Widgets.so.5 + 0x2ebd3a)
                                              #10 0x00007e8fc124a3a2 _ZN12QMenuPrivate14activateActionEP7QActionNS0_11ActionEventEb (libQt5Widgets.so.5 + 0x2f33a2)
                                              #11 0x00007e8fc18cf7db _ZN8sipQMenu17mouseReleaseEventEP11QMouseEvent (QtWidgets.so + 0x2d27db)
                                              #12 0x00007e8fc110a36e _ZN7QWidget5eventEP6QEvent (libQt5Widgets.so.5 + 0x1b336e)
                                              #13 0x00007e8fc18cedbb _ZN8sipQMenu5eventEP6QEvent (QtWidgets.so + 0x2d1dbb)
                                              #14 0x00007e8fc10c9063 _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent (libQt5Widgets.so.5 + 0x172063)
                                              #15 0x00007e8fc10ce891 _ZN12QApplication6notifyEP7QObjectP6QEvent (libQt5Widgets.so.5 + 0x177891)
                                              #16 0x00007e8fc177cc36 _ZN15sipQApplication6notifyEP7QObjectP6QEvent (QtWidgets.so + 0x17fc36)
                                              #17 0x00007e8fc41d9ee0 _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent (libQt5Core.so.5 + 0x25aee0)
                                              #18 0x00007e8fc10cd78a _ZN19QApplicationPrivate14sendMouseEventEP7QWidgetP11QMouseEventS1_S1_PS1_R8QPointerIS0_Ebb (libQt5Widgets.so.5 + 0x17678a)
                                              #19 0x00007e8fc112398f _ZN13QWidgetWindow16handleMouseEventEP11QMouseEvent (libQt5Widgets.so.5 + 0x1cc98f)
                                              #20 0x00007e8fc1125dde _ZN13QWidgetWindow5eventEP6QEvent (libQt5Widgets.so.5 + 0x1cedde)
                                              #21 0x00007e8fc10c9063 _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent (libQt5Widgets.so.5 + 0x172063)
                                              #22 0x00007e8fc177cc36 _ZN15sipQApplication6notifyEP7QObjectP6QEvent (QtWidgets.so + 0x17fc36)
                                              #23 0x00007e8fc41d9ee0 _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent (libQt5Core.so.5 + 0x25aee0)
                                              #24 0x00007e8fc0b1219b _ZN22QGuiApplicationPrivate17processMouseEventEPN29QWindowSystemInterfacePrivate10MouseEventE (libQt5Gui.so.5 + 0x12419b)
                                              #25 0x00007e8fc0af414b _ZN22QWindowSystemInterface22sendWindowSystemEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Gui.so.5 + 0x10614b)
                                              #26 0x00007e8fbf5d2c8e _ZL17xcbSourceDispatchP8_GSourcePFiPvES1_ (libQt5XcbQpa.so.5 + 0x65c8e)
                                              #27 0x00007e8fc390078f g_main_context_dispatch (libglib-2.0.so.0 + 0x5278f)
                                              #28 0x00007e8fc3900b18 g_main_context_iterate.constprop.0 (libglib-2.0.so.0 + 0x52b18)
                                              #29 0x00007e8fc3900be3 g_main_context_iteration (libglib-2.0.so.0 + 0x52be3)
                                              #30 0x00007e8fc4225aa3 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2a6aa3)
                                              #31 0x00007e8fc41d883b _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5 + 0x25983b)
                                              #32 0x00007e8fc1247e88 _ZN5QMenu4execERK6QPointP7QAction (libQt5Widgets.so.5 + 0x2f0e88)
                                              #33 0x00007e8fc18ce222 meth_QMenu_exec_ (QtWidgets.so + 0x2d1222)
                                              #34 0x00007e8fc56e3eab cfunction_call_varargs (libpython3.8.so.1.0 + 0x123eab)
                                              #35 0x00007e8fc56d42d1 _PyObject_MakeTpCall (libpython3.8.so.1.0 + 0x1142d1)
                                              #36 0x00007e8fc56d10ad _PyEval_EvalFrameDefault (libpython3.8.so.1.0 + 0x1110ad)
                                              #37 0x00007e8fc56d9df7 function_code_fastcall (libpython3.8.so.1.0 + 0x119df7)
                                              #38 0x00007e8fc56e26cb method_vectorcall (libpython3.8.so.1.0 + 0x1226cb)
                                              #39 0x00007e8fc56e2984 PyVectorcall_Call (libpython3.8.so.1.0 + 0x122984)
                                              #40 0x00007e8fc46bc4e5 _ZNK8PyQtSlot4callEP7_objectS1_ (QtCore.so + 0x2224e5)
                                              #41 0x00007e8fc46bc918 _ZNK8PyQtSlot6invokeEPPvP7_objectS0_b (QtCore.so + 0x222918)
                                              #42 0x00007e8fc46bcad0 _ZNK8PyQtSlot6invokeEPPvP7_objectS0_ (QtCore.so + 0x222ad0)
                                              #43 0x00007e8fc46bf1fd _ZL18qt_metacall_workerP17_sipSimpleWrapperP11_typeobjectP11_sipTypeDefN11QMetaObject4CallEiPPv.isra.0 (QtCore.so + 0x2251fd)
                                              #44 0x00007e8fc46bf2f6 _Z27qpycore_qobject_qt_metacallP17_sipSimpleWrapperP11_sipTypeDefN11QMetaObject4CallEiPPv (QtCore.so + 0x2252f6)
                                              #45 0x00007e8fc4208bb8 _Z10doActivateILb0EEvP7QObjectiPPv (libQt5Core.so.5 + 0x289bb8)
                                              #46 0x00007e8fc10efd59 _ZN7QWidget26customContextMenuRequestedERK6QPoint (libQt5Widgets.so.5 + 0x198d59)
                                              #47 0x00007e8fc110b0f5 _ZN7QWidget5eventEP6QEvent (libQt5Widgets.so.5 + 0x1b40f5)
                                              #48 0x00007e8fc11b33a2 _ZN6QFrame5eventEP6QEvent (libQt5Widgets.so.5 + 0x25c3a2)
                                              #49 0x00007e8fc196512b _ZN13sipQTableView13viewportEventEP6QEvent (QtWidgets.so + 0x36812b)
                                              #50 0x00007e8fc41d9c4e _ZN23QCoreApplicationPrivate29sendThroughObjectEventFiltersEP7QObjectP6QEvent (libQt5Core.so.5 + 0x25ac4e)
                                              #51 0x00007e8fc10c9052 _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent (libQt5Widgets.so.5 + 0x172052)
                                              #52 0x00007e8fc10cf4ab _ZN12QApplication6notifyEP7QObjectP6QEvent (libQt5Widgets.so.5 + 0x1784ab)
                                              #53 0x00007e8fc177cc36 _ZN15sipQApplication6notifyEP7QObjectP6QEvent (QtWidgets.so + 0x17fc36)
                                              #54 0x00007e8fc41d9ee0 _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent (libQt5Core.so.5 + 0x25aee0)
                                              #55 0x00007e8fc11235a9 _ZN13QWidgetWindow16handleMouseEventEP11QMouseEvent (libQt5Widgets.so.5 + 0x1cc5a9)
                                              #56 0x00007e8fc1125dde _ZN13QWidgetWindow5eventEP6QEvent (libQt5Widgets.so.5 + 0x1cedde)
                                              #57 0x00007e8fc10c9063 _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent (libQt5Widgets.so.5 + 0x172063)
                                              #58 0x00007e8fc177cc36 _ZN15sipQApplication6notifyEP7QObjectP6QEvent (QtWidgets.so + 0x17fc36)
                                              #59 0x00007e8fc41d9ee0 _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent (libQt5Core.so.5 + 0x25aee0)
                                              #60 0x00007e8fc0b1219b _ZN22QGuiApplicationPrivate17processMouseEventEPN29QWindowSystemInterfacePrivate10MouseEventE (libQt5Gui.so.5 + 0x12419b)
                                              #61 0x00007e8fc0af414b _ZN22QWindowSystemInterface22sendWindowSystemEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Gui.so.5 + 0x10614b)
                                              #62 0x00007e8fbf5d2c8e _ZL17xcbSourceDispatchP8_GSourcePFiPvES1_ (libQt5XcbQpa.so.5 + 0x65c8e)
                                              #63 0x00007e8fc390078f g_main_context_dispatch (libglib-2.0.so.0 + 0x5278f)
                                              
                                              Stack trace of thread 74245:
                                              #0  0x00007e8fc55ade92 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xfe92)
                                              #1  0x00007e8fbc65e20b util_queue_thread_func (iris_dri.so + 0x49d20b)
                                              #2  0x00007e8fbc65dccb impl_thrd_routine (iris_dri.so + 0x49cccb)
                                              #3  0x00007e8fc55a7432 start_thread (libpthread.so.0 + 0x9432)
                                              #4  0x00007e8fc59fc6d3 __clone (libc.so.6 + 0x1016d3)
                                              
                                              Stack trace of thread 74243:
                                              #0  0x00007e8fc59f186f __poll (libc.so.6 + 0xf686f)
                                              #1  0x00007e8fc3900aae g_main_context_iterate.constprop.0 (libglib-2.0.so.0 + 0x52aae)
                                              #2  0x00007e8fc3900be3 g_main_context_iteration (libglib-2.0.so.0 + 0x52be3)
                                              #3  0x00007e8fc4225aa3 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2a6aa3)
                                              #4  0x00007e8fc41d883b _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5 + 0x25983b)
                                              #5  0x00007e8fc4044417 _ZN7QThread4execEv (libQt5Core.so.5 + 0xc5417)
                                              #6  0x00007e8fbedea51b _ZN22QDBusConnectionManager3runEv (libQt5DBus.so.5 + 0x1951b)
                                              #7  0x00007e8fc4045680 _ZN14QThreadPrivate5startEPv (libQt5Core.so.5 + 0xc6680)
                                              #8  0x00007e8fc55a7432 start_thread (libpthread.so.0 + 0x9432)
                                              #9  0x00007e8fc59fc6d3 __clone (libc.so.6 + 0x1016d3)
                                              
                                              Stack trace of thread 74248:
                                              #0  0x00007e8fc55ade92 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xfe92)
                                              #1  0x00007e8fbc65e20b util_queue_thread_func (iris_dri.so + 0x49d20b)
                                              #2  0x00007e8fbc65dccb impl_thrd_routine (iris_dri.so + 0x49cccb)
                                              #3  0x00007e8fc55a7432 start_thread (libpthread.so.0 + 0x9432)
                                              #4  0x00007e8fc59fc6d3 __clone (libc.so.6 + 0x1016d3)
                                              
                                              Stack trace of thread 74247:
                                              #0  0x00007e8fc55ade92 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xfe92)
                                              #1  0x00007e8fbc65e20b util_queue_thread_func (iris_dri.so + 0x49d20b)
                                              #2  0x00007e8fbc65dccb impl_thrd_routine (iris_dri.so + 0x49cccb)
                                              #3  0x00007e8fc55a7432 start_thread (libpthread.so.0 + 0x9432)
                                              #4  0x00007e8fc59fc6d3 __clone (libc.so.6 + 0x1016d3)
                                              
                                              Stack trace of thread 74246:
                                              #0  0x00007e8fc55ade92 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xfe92)
                                              #1  0x00007e8fbc65e20b util_queue_thread_func (iris_dri.so + 0x49d20b)
                                              #2  0x00007e8fbc65dccb impl_thrd_routine (iris_dri.so + 0x49cccb)
                                              #3  0x00007e8fc55a7432 start_thread (libpthread.so.0 + 0x9432)
                                              #4  0x00007e8fc59fc6d3 __clone (libc.so.6 + 0x1016d3)
                                              
                                              Stack trace of thread 74242:
                                              #0  0x00007e8fc59f186f __poll (libc.so.6 + 0xf686f)
                                              #1  0x00007e8fc04fc38a _xcb_conn_wait (libxcb.so.1 + 0xd38a)
                                              #2  0x00007e8fc04fe71a xcb_wait_for_event (libxcb.so.1 + 0xf71a)
                                              #3  0x00007e8fbf5d1c68 _ZN14QXcbEventQueue3runEv (libQt5XcbQpa.so.5 + 0x64c68)
                                              #4  0x00007e8fc4045680 _ZN14QThreadPrivate5startEPv (libQt5Core.so.5 + 0xc6680)
                                              #5  0x00007e8fc55a7432 start_thread (libpthread.so.0 + 0x9432)
                                              #6  0x00007e8fc59fc6d3 __clone (libc.so.6 + 0x1016d3) 
    Apr 27 14:08:26 dom0 systemd[1]: systemd-coredump@5-74263-0.service: Succeeded.
    Apr 27 14:08:26 dom0 kernel: audit: type=1131 audit(1682629706.522:1292): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-coredump@5-74263-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
    Apr 27 14:08:26 dom0 audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-coredump@5-74263-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
    Apr 27 14:08:26 dom0 audit: BPF prog-id=58 op=UNLOAD
    Apr 27 14:08:26 dom0 kernel: audit: type=1334 audit(1682629706.564:1293): prog-id=58 op=UNLOAD
    Apr 27 14:08:26 dom0 kernel: audit: type=1334 audit(1682629706.564:1294): prog-id=57 op=UNLOAD
    Apr 27 14:08:26 dom0 kernel: audit: type=1334 audit(1682629706.564:1295): prog-id=56 op=UNLOAD
    Apr 27 14:08:26 dom0 audit: BPF prog-id=57 op=UNLOAD
    Apr 27 14:08:26 dom0 audit: BPF prog-id=56 op=UNLOAD
    Apr 27 14:33:47 dom0 qrexec-policy-daemon[3485]: qrexec: qubes.GetDate+: disp1741 -> @default: allowed to dom0

I also noticed that changing VM network from none to default (sys-firewall) via Qube Manager settings gets the following error (edited) when sys-firewall isn't started:  

    ERROR: Basic tab:
    Cannot dynamically attach to stopped NetVM: 
    <DispVM at 0x722ebdbad820 name='sys-firewall' qid=7 auto_cleanup=False autostart=True backup_timestamp=1682288203 debug=False default_user=user dispid=8966 dns=ip.ad.dress.1 ip.ad.dress.2 gateway=ip.ad.dress.6 gateway6=None icon=servicevm-green include_in_backups=True installed_by_rpm=False ip=ip.ad.dress.6 ip6=None kernel=5.15.103-1.fc32 keyboard_layout=us++ klass=DispVM label=green mac=MA:CA:DD:RE:SS:00 maxmem=4000 memory=500 provides_network=True qrexec_timeout=60 shutdown_timeout=60 start_time=None stubdom_mem=None stubdom_xid=-1 updateable=False uuid=UUID vcpus=2 virt_mode=pvh visible_gateway=ip.ad.dress.24 visible_gateway6=None visible_ip=ip.ad.dress.6 visible_ip6=None visible_netmask=255.255.255.255 xid=-1 audiovm=dom0 default_dispvm=fed-37-dvm guivm=dom0 kernelopts= management_dispvm=default-mgmt-dvm netvm=sys-net template=fed-37-dvm>

### Slightly related non-duplicate issues

[4.1 RC1: "Qubes Domains": Add net-vm-selection #7044 ](https://github.com/QubesOS/qubes-issues/issues/7044)

[Communicate to user that disposable is missing updates after its parent template has been updated but that restarting disposable will reset its state #7779 ](https://github.com/QubesOS/qubes-issues/issues/7779)

[4.0 - Cannot change netvm where existing netvm is not running #6493 ](https://github.com/QubesOS/qubes-issues/issues/6493)

**Comment by lesliesmith** [comment]
Found another related non-duplicate issue

[4.0 - Cannot change netvm where existing netvm is not running #6493 ](https://github.com/QubesOS/qubes-issues/issues/6493)

**Comment by marmarta** [comment]
Found it - actually asking "hey we need to start the netvm" worked there for a while... except in the case of default_netvm. Nice catch :D
