### ISSUE TITLE
[R4.2] KDE should use new qubes menu

### ISSUE THREAD

**Issue by Augsch123** [QubesOS/qubes-issues#8159]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

R4.2

### Brief summary

The KDE Application launcher will crash if I install KDE plasma latest ( 5.27 atm ) and kde-settings-qubes 5.12.

### Steps to reproduce

1. Install KDE by running 
```
sudo qubes-dom0-update apper breeze-icon-theme colord-kde dolphin kcm_systemd kde-runtime kde-settings-pulseaudio kde-style-breeze kdelibs kdeplasma-addons kdialog khelpcenter khotkeys kinfocenter kmenuedit kmix konsole5 kscreen ksysguard kwin phonon-qt5-backend-gstreamer plasma-breeze plasma-desktop plasma-desktop-doc plasma-pa plasma-user-manager plasma-workspace polkit-kde qt5-qdbusviewer sddm sddm-breeze sddm-kcm sni-qt
```
2. Logout and log back in, and find that the launcher is working well.
3. Install kde-settings-qubes.
4. Logout and log back in, and the launcher crashes.
5. Remove kde-settings-qubes.
6. Logout and log back in, and the launcher crashes.
7. Fully reinstall KDE by running 
```
sudo qubes-dom0-update --action=reinstall apper breeze-icon-theme colord-kde dolphin kcm_systemd kde-runtime kde-settings-pulseaudio kde-style-breeze kdelibs kdeplasma-addons kdialog khelpcenter khotkeys kinfocenter kmenuedit kmix konsole5 kscreen ksysguard kwin phonon-qt5-backend-gstreamer plasma-breeze plasma-desktop plasma-desktop-doc plasma-pa plasma-user-manager plasma-workspace polkit-kde qt5-qdbusviewer sddm sddm-breeze sddm-kcm sni-qt
```
8. Logout and log back in, and find that the launcher is working well.

**I repeated step 3 to 8 two times, and this issue is reproducible.**

### Expected behavior

The launcher shouldn't crash.

### Actual behavior

It crashed with following messages:
```
Sorry! there was an error loading Application launcher.

file:///usr/share/plasma/plasmoids/org.kde.plasma.kickoff/contents/ui/Kickoff.qml:157:34: Type FullRepresentation unavailable

file:///usr/share/plasma/plasmoids/org.kde.plasma.kickoff/contents/ui/FullRepresentation.qml:43:5: KickoffButton is not a type
```

**Comment by marmarek** [comment]
As noted in the duplicate issue: the fix here is not to make the old menu customization work (it was quite invasive), but adjust the startup setup to replace KDE native menu with the new qubes menu.
