### ISSUE TITLE
renaming template repopulates applications-list

### ISSUE THREAD

**Issue by GammaSQ** [QubesOS/qubes-issues#8168]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
4.1

### Brief summary
When a template had changes to it's application list  (e.g. "run Terminal" instead of 'XTerm') and gets renamed, the changes disappear.

### Steps to reproduce
tested with fedora-37-minimal:
`qvm-template install fedora-37-minimal` in dom0
do some rearranging in the "Applications" tab of that template's settings. (switch some from "selected" to "available" and vice versa) Apply/Ok
[optional: start template, maybe install some stuff]
open settings again and rename template.
...changes to applications are gone. The "Applications" tab in that template's settings shows initial configuration.

### Expected behavior
renaming template retains other template settings, such as Applications.

### Actual behavior
Applications change

Doesn't seem to apply to AppVMs

**Comment by unman** [comment]
This is why there is a prominent warning on the rename dialog - "all other
changes will be discarded".
Did you miss that?

**Comment by marmarek** [comment]
I don't think that's the issue, see "apply/ok" in steps to reproduce, that should save the changes.

**Comment by GammaSQ** [comment]
Just reproduced by renaming an "old" template. (i.e. there wasn't a change to its Applications recently. After renaming, the Applications-list is back to defaults.)

Happy to provide details if this does not reproduce.
(e.g. I generally only touch copies of rpm-templates to keep pristine versions around.)
