### ISSUE TITLE
Debian-based VM doesn't work as ClockVM by default

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#8173]
### Qubes OS release

`4.1.2`

### Brief summary

Qubes is difficult to recover from wrong system time.

`sudo qvm-sync-clock` is confusing and doesn't fix dom0 or VM clocks.

### Impact

Why does it matter? If system time is too far off it breaks TLS (https websites), Tor, system upgrades and more.

### Steps to reproduce

Set the wrong time just for the sake of reproducing this issue. This is to take the same perspective as the user would have. Obviously nobody is shooting their own feet on purpose. But this is a situation a user might find itself in. (Clock might be wrong by factory default, prior other operating system, user mistake or hardware clock issue.)

1. set a wrong time in dom0 `sudo date --utc --set "Fri 04 May 2023 01:16:10 PM UTC"`
2. `sudo hwclock --utc --systohc`
3. reboot (or at least restart sys-net (actually ClockVM))

Now try to fix the issue. From a user's perspective.

5. Try to fix in dom0 `sudo qvm-sync-clock`.
6. Alternatively try to fix dom0 clock by using GNU date (or any other mechanism).

### Expected behavior

* `qvm-sync-clock` fixes the dom0 clock.
* Newly started VMs have the correct time.
* ClockVM should have a mechanism to fix its own time even if it is far off.

### Actual behavior

* `qvm-sync-clock` sets the dom0 to the incorrect (outdated, slow) time, which it gets from ClockVM. Technically speaking, dom0 `/usr/bin/qvm-sync-clock`  simply calls the ClockVMs `/etc/qubes-rpc/qubes.GetDate`, which still has the wrong time which then dom0 uses.
* Newly started VMs the an incorrect time.
  * If just manually fixed using GNU date, then newly started VMs will get the correct time of a while. Except, until...
  * After `qvm-sync-clock` was automatically run (it seems to be periodically run), it will set again the wrong time from ClockVM.
* dom0 clock will be periodically (whenever `qvm-sync-clock` automatically runs in dom0) be reverted to the wrong clock coming from ClockVM.
* Highly confusing and took me a while to debug.

### Workaround

1. Shutdown all VMs. (Or at least ClockVM, most likely the default sys-net.)
2. Correct the time in dom0.
3. Restart VMs.
4. Done.

**Comment by marmarek** [comment]
ClockVM (sys-net by default) should run standard NTP client (depending on distribution, it could be systemd-timesyncd, chrony or something else). What template your ClockVM uses? Is any of those services running there?

**Comment by adrelanos** [comment]
Also even if the standard time sync daemon was running inside ClockVM (such as NTP, systemd-timesyncd, chrony), would it be able to fix the clock if it is far off?

**Comment by marmarek** [comment]
> Also even if the standard time sync daemon was running inside ClockVM (such as NTP, systemd-timesyncd, chrony), would it be able to fix the clock if it is far off?

Yes, it should.

**Comment by marmarek** [comment]
So, it seems systemd-timesyncd service (or whatever is the default NTP client in Debian) is missing in the default template.
