### ISSUE TITLE
Notifications from xfce4-notifyd in a VM have normal decorations

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#8181]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

R4.2

### Brief summary

The notification lacks override-redirect flag, so the window has normal decorations, and also grabs focus.
https://openqa.qubes-os.org/tests/72214/video?filename=video.ogv&t=434.00

### Steps to reproduce

1. Install fedora-38-xfce template.
2. Create and an AppVM based on it.
3. Execute `notify-send test`

### Expected behavior

Normal notification, not grabbing the focus.

### Actual behavior

A notification window with fully-decorations shows up, and depending on window manager settings, it grabs focus too.

Part of https://github.com/QubesOS/qubes-issues/issues/8069.
This is not the case for Fedora 37 template.

**Comment by Geblaat** [comment]
I just noticed this in the standard Fedora 38 template on R4.1

**Comment by marmarek** [comment]
Do you see any errors in `/var/log/qubes/guid.NAME.log` in dom0 (with `NAME` replaced with the actual qube name)?

**Comment by rustybird** [comment]
xfce4-notifyd 0.8.0+ (fc38 has 0.8.2) [stopped enabling override-redirect](https://gitlab.xfce.org/apps/xfce4-notifyd/-/commit/59e6bfa860174cfb266ebc2a75ca2c523a466ccb) on notification windows by default. It's now relying on `_MOTIF_WM_HINTS` to tell the window manager not to decorate the window. But 0.8.1+ [added a hidden setting](https://gitlab.xfce.org/apps/xfce4-notifyd/-/commit/a226b7e69df9c8ff5005f1c70c5d908a235cfaba) to re-enable override-redirect.

**Comment by rustybird** [comment]
No idea why what's up with the input focus stealing though. Plain old `WM_HINTS` is declaring that the notification window doesn't want input focus, and the GUI protocol *should* already be able to forward that information to dom0.

**Comment by marmarek** [comment]
Thanks @rustybird for finding this out! I guess we simply need to enable this setting, the gui daemon already has specific provision to not put any window above the screenlocker.

**Comment by andrewdavidwong** [comment]
Since this issue has the "Release 4.1 updates" milestone and was resolved against that milestone, the fix *should* be coming to 4.1 too.

**Comment by verygreen** [comment]
Any idea what package would contain it? I enabled testing repo and there's no core-agent in the updates list, even though evidently one was generated for 4.2 branch,.

This bug makes fedora38 tempates unusable unfortunately (in all cases tha generate notifications, anyway)

**Comment by rustybird** [comment]
> Any idea what package would contain it? I enabled testing repo and there's no core-agent in the updates list

It's not yet [in R4.1](https://github.com/QubesOS/qubes-core-agent-linux/commits/release4.1). @marmarek

> This bug makes fedora38 tempates unusable unfortunately

If it's urgent, you could save [this file](https://raw.githubusercontent.com/QubesOS/qubes-core-agent-linux/main/misc/xfce4-notifyd.xml) to `/etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfce4-notifyd.xml` in the template.

**Comment by verygreen** [comment]
aha, thanks! That helped immensely
