### ISSUE TITLE
Add libpam-systemd as qubes-gui-agent's dependency

### ISSUE THREAD

**Issue by Augsch123** [QubesOS/qubes-issues#8189]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

R4.2

### Brief summary

Upgrade qubes-gui-agent to 4.2.2-1 in a debian-11-minimal template makes the qubes-gui-agent systemd service fail to start. 

Installing libpam-systemd fixes the problem.

More details: https://forum.qubes-os.org/t/r4-2-debian-11-minimal-templates-gui-agent-crash/18462

### Steps to reproduce

1. `qvm-template install debian-11-minimal`.
2. In debian-11-minimal, `sudo apt upgrade`
3. Reboot debian-11-minimal.

### Expected behavior

The gui agent service runs fine.

### Actual behavior

It failed.

**Comment by unman** [comment]
Compare #7689
