### ISSUE TITLE
Audio is severely distorted unless audio mixer is open

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#8194]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

R4.2

### Brief summary

Playing audio from Fedora (pulseaudio), Ubuntu (pipewire) or Windows (pulseaudio in stubdomain) is severely distorted.

### Steps to reproduce

Try to play audio on R4.2, since it looks to be hardware-related, it's on HP EliteBook 1030, with 12th gen Intel CPU.

### Expected behavior

Proper audio.

### Actual behavior

Audio severely distorted, if mixes is not open. There are a few seconds of okay audio after closing the mixer.

Pulseaudio in dom0 logs this (once, unsure if related):
```
May 11 19:47:17 dom0 pulseaudio[5511]: ALSA woke us up to read new data from the device, but there was actually nothing to read.
May 11 19:47:17 dom0 pulseaudio[5511]: Most likely this is a bug in the ALSA driver 'snd_soc_skl_hda_dsp'. Please report this issue to the ALSA developers.
May 11 19:47:17 dom0 pulseaudio[5511]: We were woken up with POLLIN set -- however a subsequent snd_pcm_avail() returned 0 or another value < min_avail.
```

Additionally, when mixer is opened, pacat logs this:
```
Stream device alsa_input.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__hw_sofhdadsp_6__source resumed.Stream device alsa_input.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__hw_sofhdadsp_6__source resumed.
```
and few seconds after it's closed (when the sound breaks again):
```
Stream device alsa_input.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__hw_sofhdadsp_6__source suspended.Stream device alsa_input.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__hw_sofhdadsp_6__source suspended.
```
But note the above is about `alsa_input`, while playback is about `alsa_output`.

For a VM with Pipewire, there is some more logs:
Pipewire (in Ubuntu) logs a lot of `mod.qubes-audio: Underrun: asked to read 8192 bytes, but only 0 available` and pacat log is full of `Stream uncork` (without matching `cork`).

**Comment by na--** [comment]
Related issues: https://github.com/QubesOS/qubes-issues/issues/7966, https://github.com/QubesOS/qubes-issues/issues/7634

**Comment by marmarek** [comment]
Indeed it looks like a duplicate of https://github.com/QubesOS/qubes-issues/issues/7634 (at least its initial description and also the re-open reason).

**Comment by andrewdavidwong** [comment]
This appears to be a [duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If anyone believes this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.
