### ISSUE TITLE
Allow dots in qube names

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#8199]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### The problem you're addressing (if any)

Currently allowed characters in qube names are: `a-zA-Z0-9_-`. Before Qubes 4.0, dot used to be allowed and that was useful thing.

### The solution you'd like

Allow dots in qube names again.

### The value to a user, and who that user might be

Easier to apply own naming convention to qube names.

Related: https://github.com/QubesOS/qubes-issues/issues/2422

**Comment by DemiMarie** [comment]
Should a leading `.` be allowed?

**Comment by marmarek** [comment]
Probably no.

**Comment by alimirjamali** [comment]
Notes: [Patch](https://github.com/QubesOS/qubes-core-admin/pull/606) and Unit test for #7234 should be changed to adapt with this change.
