### ISSUE TITLE
Installation image of Windows 10 22H2 doesn't detect disk

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#8203]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

R4.2

### Brief summary

Installing Windows 10 from old installation image (2018-ish) works, but new one doesn't detect target disk.

### Steps to reproduce

1. Fetch Window 10 22H2 installation image.
2. Try to install Windows VM

### Expected behavior

Installer starts and detects target disk.

### Actual behavior

Installer starts, but doesn't see the disk and asks for drivers.

**Comment by marmarek** [comment]
It seems it was a broken ISO image. Freshly downloaded one worked just fine.

For the record:
1. the broken one: SHA256: c3a8afe21dea04b7b96b11da4f791f7c9ba7a6ae9a437112e4d037d84e2923d8, Win10_22H2_EnglishInternational_x64.iso, size 6113187840
2. the working one: SHA256: c3a8afe21dea04b7b96b11da4f791f7c9ba7a6ae9a437112e4d037d84e2923d8, Win10_22H2_EnglishInternational_x64.iso, size 6113187840

**Comment by andrewdavidwong** [comment]
Closed as "not a bug" (the reported behavior is not a bug and is already working as intended). If anyone believes this is a mistake, please leave a comment, and we'll be happy to take another look. Thank you.
