### ISSUE TITLE
Ubuntu VM fails to start applications on first attempt

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#8205]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

R4.2

### Brief summary

When starting an application in a Ubuntu jammy VM that wasn't running already, the VM is started, but the application is not. Starting an application in already running VM works fine.

### Steps to reproduce

1. Ensure you have a Ubuntu jammy-based VM that is not running.
2. Call `qvm-run VMNAME gnome-terminal`

### Expected behavior

VM starts and gnome-terminal opens up.

### Actual behavior

VM starts, but no application is started. `qvm-run` hangs. It seems to hang on the `qubes.WaitForSession` call.
On the process tree, under `qubes.WaitForSession` I see:
```
systemctl --machine=user@.host --user --wait --quiet is-system-running
```

**Comment by GWeck** [comment]
I observed a similar behavior with jammy on Qubes R4.1, and also for debian bookworm on R4.1. Might have the same cause????

**Comment by marmarek** [comment]
> I observed a similar behavior with jammy on Qubes R4.1, and also for debian bookworm on R4.1. Might have the same cause????

Very likely.

**Comment by fepitre** [comment]
Tested fix https://github.com/QubesOS/qubes-core-agent-linux/pull/426 on R4.2 on:
- Debian 11
- Debian 12 XFCE
- Fedora 37
- Ubuntu Jammy
- Fedora 38 XFCE

**Comment by maltesl** [comment]
I can confirm that this issue is also present on R4.1 with Debian bookworm, and that https://github.com/QubesOS/qubes-core-agent-linux/pull/426/commits/41e64583e79415bce8d774028fdd0483651c934b fixes it. However it seems like that patch was only applied to the R4.2 branch. Can it also be applied to R4.1?
