### ISSUE TITLE
Blocking in-progress connections via qubes-firewall stopped working when using flowtables

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#8212]
## Observation

openQA test in scenario qubesos-4.2-pull-requests-x86_64-system_tests_network@64bit fails in
[VmNetworking_fedora-37](https://openqa.qubes-os.org/tests/73634/modules/VmNetworking_fedora-37/steps/5)

```
# timestamp 2023-05-14T02:39:01.312788
Traceback (most recent call last):
  File "/usr/lib64/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/qubes/tests/integ/network.py", line 396, in test_031_firewall_dynamic_block
    self.assertEqual(stdout, b"line1\n")
AssertionError: b'line1\nline2\n' != b'line1\n'
```

## Test suite description

Tests if blocking a connection via qvm-firewall also blocks those already established.
The test is in this PR: https://github.com/QubesOS/qubes-core-admin/pull/536

## Reproducible

Fails since (at least) Build [2023050602-4.2](https://openqa.qubes-os.org/tests/72962)

## Expected result

Last good: [2023050503-4.2](https://openqa.qubes-os.org/tests/72922) (or more recent)

## Further details

Always latest result in this scenario: [latest](https://openqa.qubes-os.org/tests/latest?arch=x86_64&distri=qubesos&flavor=pull-requests&machine=64bit&test=system_tests_network&version=4.2)

It seems with flowtables, there is  an extra entry in conntrack - with addresses reversed and an `[OFFLOAD]` tag. This one is not removed by the qubes-firewall service.

**Comment by DemiMarie** [comment]
https://bugzilla.netfilter.org/show_bug.cgi?id=1680

**Comment by marmarek** [comment]
Any workarounds? Like flushing all of the flowtables maybe? Or maybe such entries are supposed to be removed with nft?

**Comment by DemiMarie** [comment]
Simplest workaround would be to delete the flowtable, flush the conntrack entries, and finally recreate the flowtable.  This is likely slow compared to just deleting a conntrack entry, but removing firewall rules is not a fast path so it should not matter.

**Comment by DemiMarie** [comment]
This was fixed in Linux 6.3.  I am currently checking if the patches can be backported to stable, in which case the problem should go away without any action on our part.

**Comment by marmarek** [comment]
> This was fixed in Linux 6.3. I am currently checking if the patches can be backported to stable, in which case the problem should go away without any action on our part.

Ok, please check. If the patch is easy to backport but for some reason upstream doesn't want to, we can consider carrying backport ourselves (please point at the commit then). But in that case we may want to consider workaround in qubes-firewall service anyway, for the case of custom or in-vm kernels.

**Comment by DemiMarie** [comment]
This commit has been backported to all supported stable kernel trees except 4.14, which I don’t think Qubes supports.

**Comment by DemiMarie** [comment]
I’m closing this as “not our bug”, inasmuch as this is a Linux kernel bug that will be fixed when kernels including the relevant patch are released and therefore no action is required from the Qubes team.
