### ISSUE TITLE
Do not install the PipeWire agent on Ubuntu<22.10 or Debian<12

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#8213]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

R4.2

### Brief summary

Using pipewire agent in Ubuntu jammy, results in a constantly flowing data even if nothing is playing.

### Steps to reproduce

1. Build and install Ubuntu jammy template
2. Work around #8193 (`qvm-service --enable VMNAME pipewire`)
3. Check `journalctl --user` in VM and `pactl list sink-inputs` in dom0

### Expected behavior

Both streams (input and output) are corked.

### Actual behavior

The playback stream is not corked.
Furthermore, the pipewire agent is trying to read audio-input stream (and due to #7656 it results in a lot of `Underrun: asked to read 8192 bytes, but only 0 available` messages).

The issue doesn't appear to affect Fedora 38.

**Comment by marmarek** [comment]
It might be that some process in Ubuntu template connected to pipewire is keeping the streams active, but I'm not sure how to check that. Stopping `pipewire-pulse` service/socket does not help.

**Comment by marmarek** [comment]
`pw-cli dump`: https://gist.github.com/marmarek/ba1a2f4369e579660e86c8ea7ff7cd87

**Comment by DemiMarie** [comment]
[PipeWire is not supported on Ubuntu 22.04][1] and per discussions in \#pipewire at OFTC PipeWire is not supportable on that OS.  Therefore, the Ubuntu 22.04 (and below) templates should not install PipeWire at all.

[1]: https://bugs.launchpad.net/ubuntu/+bug/1990081/comments/1

**Comment by marmarek** [comment]
Fixed in https://github.com/QubesOS/qubes-meta-packages/pull/62
