### ISSUE TITLE
Qubes-OS 4.1.2 freeze/stutter/stops at random times when a specific usb-mouse is used

### ISSUE THREAD

**Issue by loneicewolf** [QubesOS/qubes-issues#8214]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

- Qubes-OS 4.1.2 

### Brief summary

***

*  ⚠️  First Words ⚠️ 
This will maybe not be the most "perfect" bug/report issue, I write this mainly because of 2 reasons:
1. I had this problem for quite a while, and even *stopped* using Qubes temporarily.
2. I stumbled upon a workaround/solution, and that was for me **simply speaking** just to use another kind of usb mouse. (Details is typed later, below)

***

to write this to be short, easy to read and "clean" I will first type what I did before I stumbled upon a "workaround" or "solution" to this:

- https://github.com/QubesOS/qubes-issues/issues?q=lagg
- https://github.com/QubesOS/qubes-issues/issues?q=stutter
- https://github.com/QubesOS/qubes-issues/issues?q=freeze
- https://github.com/QubesOS/qubes-issues/issues?q=delay
- https://github.com/QubesOS/qubes-issues/issues?q=slow

**I did find these**
- https://github.com/QubesOS/qubes-issues/issues/8145
- https://github.com/QubesOS/qubes-issues/issues/8088

Where one suggested that one should try to install `kernel-latest` (**I assume, this is in UEFI-Installations?** as I do not really know any way to "install kernel-latest" (at least not via gui which, I think he in the link(s) above suggested)).

I thought of trying this, but I stumbled upon the (workaround, or solution) by accident, specifically - I unplugged my razer mouse(which is, a trinity-moba, it has buttons(re programmable) on the (swappable)sides of it.) so it basically can act as a keyboard. This brought me to the theory/thought that - maybe this Qubes release specifically (*because it worked before*) is probably getting confused on the Razer Mouse. Maybe about "Is it a keyboard OR a mouse?", it *kind of* is both.

⚠️ Note, this is just a thought. Why did I write it if I am not sure ? I want to make it easier to nail down what causes this.

### Steps to reproduce
when making this issue I **assumed** I was not alone, so:
insert a Razer Mouse ( trinity-moba ) in the latest Qubes, and it will begin after a few seconds, to cause lag. What kind of lag? well, freezes, stutters, delays, in.. Everything?  keyboard types, mouse movements, even **audio**.

Unplugging the razer mouse **immediately removes the stuttering, the audio works flawless, everything is as smooth as other qubes releases**.

### Expected behavior
No freeze/lag when using a razer mouse (trinity moba)
**Just like the other, previous Qubes Releases** where `both` of the usb hardware(mouse,...) worked.

### Actual behavior
freezing **seconds** after a razer mouse (trinity moba) is inserted in any usb port.

## ⚠️ Last Words
As this is my first issue here, I have tried to follow all the guidelines, I am sleep deprived when writing this (so please point out any confusing words or phrases) I just wanted to write this; the best I could, for others who might have this as well. It can be a good thing to try, to swap USB equipment(maybe, keyboard? for me it was a usb mouse anyway)

Thanks, and have a Great continuing day!

`Will. `

**Comment by loneicewolf** [comment]
### some notes & further contribution related questions

***

### If I can help:
If I can be helpful/useful in any way, tell me that directly, what I mean by that is, for example including but not lim. to the below:

- run any script/tool/command (and I suppose paste the output of it) 
- provide any logs, or more details
- re-write/summarize the whole previous post(s)
- provide more docs/things I tried/and searched for; and/or any site I might did find useful at the time

**and No rush by the way, I myself know bug "hunting" and narrowing down takes time, not to mention you guys work on other more vital areas, and so on.** (`this is also the very reason I post this reply`)

❤️ take care! Wishes from Sweden!

**Comment by RichardStr** [comment]
I have the same problem with 4.2 (fresh installation)

Interesting here is, that restart sys-usb fixes the issue for some time.

**Comment by loneicewolf** [comment]
> I have the same problem with 4.2 (fresh installation)
> 
> Interesting here is, that restart sys-usb fixes the issue for some time.


Hey! Thanks for the reply,  nice to know that..
- I am not alone(simply of __not__ being alone) 
- I am not alone(as in this issue was worth making after all, as in it wasn't just on my end)

**I'll watch this closely, ping/contact me** if any questions or update appears.

**Comment by RichardStr** [comment]
I solve this issue completely with raising inital memory from default 400mb to 600mb and vpcu to 3.

Seems it is a performance / ressource issue.

**Comment by loneicewolf** [comment]
> I solve this issue completely with raising inital memory from default 400mb to 600mb and vpcu to 3 on sys-usb qube.
> 
> Seems it is a performance / ressource issue in my case. I hope it helps. ;)

Thanks for replying! will try it on my end and see if it works.

**Comment by loneicewolf** [comment]
tested it and it didn't work at my end but I maybe did something wrong, will reinstall **yes. I will try to re install** and re try that trick :)

**Comment by loneicewolf** [comment]
## Update: 
It didn't work for me;

**Comment by loneicewolf** [comment]
Still relevant, +2023 September.

**Comment by marmarek** [comment]
can you check kernel messages in sys-usb? Open terminal there and call `sudo dmesg`. Especially see if you see a ton of `control queue full` messages. If so, it's the same issue as https://github.com/QubesOS/qubes-issues/issues/7953

**Comment by loneicewolf** [comment]
> can you check kernel messages in sys-usb? Open terminal there and call `sudo dmesg`. Especially see if you see a ton of `control queue full` messages. If so, it's the same issue as #7953

Hi! will do when I come home! :)
