### ISSUE TITLE
make iso : fails with No packages defined by templates.spec, syntax error?

### ISSUE THREAD

**Issue by mylostone** [QubesOS/qubes-issues#8223]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

4.1

### Brief summary
I have been attempting to build the qubes iso using qubes-builder (not qubes-builderv2). I have successfully built the step using "make qubes".

While running "make iso" i sget the following error:
<pre>
+ echo '--> Copying template fc37 RPM...'
--> Copying template fc37 RPM...
++ MAKEFLAGS=
++ make -s -C qubes-src/linux-template-builder DIST=fc37 template-name
+ export TEMPLATE_NAME=fedora-37
+ TEMPLATE_NAME=fedora-37
+ make -f Makefile.generic PACKAGE_SET=vm DIST=fc37 COMPONENT=linux-template-builder USE_DIST_BUILD_TOOLS=0 UPDATE_REPO=/home/user/dev/github.com/QubesOS/qubes-builder.git/qubes-src/installer-qubes-os/yum/qubes-dom0 update-repo
make[1]: Entering directory '/home/user/dev/github.com/QubesOS/qubes-builder.git'
packages=
No packages defined by templates.spec, syntax error?
make[1]: *** [/home/user/dev/github.com/QubesOS/qubes-builder.git/qubes-src/builder-rpm/Makefile.rpmbuilder:178: update-repo-do] Error 1
make[1]: Leaving directory '/home/user/dev/github.com/QubesOS/qubes-builder.git'
make: *** [Makefile:555: iso.copy-template-rpms.fc37] Error 2
[user@qubes-builder qubes-builder.git]$ 

</pre>

### Steps to reproduce

occurs each time I run "make iso"

### Expected behavior

iso builds correctly

### Actual behavior

"make iso" fails as per error message above

**Comment by marmarek** [comment]
When have you fetched the sources? I fixed very similar issue very recently: https://github.com/QubesOS/qubes-builder-rpm/commit/cabde507acab6c4eff7041d41e7ed0cd6920a1d7
