### ISSUE TITLE
[4.2-weekly] Contents of screen somtimes revealed when screensaver is active

### ISSUE THREAD

**Issue by eloquence** [QubesOS/qubes-issues#8225]
### Qubes OS release

Qubes-4.2.202305221524-x86_64.iso

### Brief summary

A recent Qubes OS 4.2 weekly sometimes reveals the contents of the screen behind the XScreenSaver dialog, even before the user has entered their password. This behavior was observed on a Lenovo T480.

### Steps to reproduce

1. Wait for screensaver to become active
2. Press any key

### Expected behavior

Only password dialog is visible

### Actual behavior

Previous screen contents are visible behind password dialog

**Comment by andrewdavidwong** [comment]
Similar report (but about external monitors): #4394

**Comment by marmarek** [comment]
This should be fixed with https://github.com/QubesOS/updates-status/issues/3758. I'll close it for now, but please leave a comment if that still happens with that update installed.

**Comment by eloquence** [comment]
I'm no longer seeing the issue on 4.2RC1 :)

**Comment by 3nprob** [comment]
Observations: This occurs more frequently when using a particular (cheap, unpowered) HDMI switch or when connecting the machine directly to display, but very rarely on laptop if no external displays are connected and less commonly on a separate HDMI switch with external power. When using the HDMI switch I can almost always at least see the unlocked desktop briefly flash by on wake even when not resulting in the persistent-background effect.

So to summarize roughly:
- Laptop, no external displays: Rare if ever
- Laptop, external display by direct HDMI: Occasionally
- Workstation, direct HDMI: Occasionally
- Workstation, unpowered HDMI switch: Frequently
- Workstation, powered HDMI switch: Rarely

Makes me suspect some form of race conditions with display outputs getting connected/disconnected on display wake in locked state.

Sometimes I get the impression that the different sides of the HDMI link "talk past each other" with detecting/triggering display signal on/off with a couple of rounds of on/off before it settles (sometimes resulting in undesired "off" requiring a display or switch input or power cycle). That by itself may not be Qubes-specific but could be a contributing factor.

**Comment by jmynes** [comment]
I am having this same problem on multiple devices, but today I finally got a video of it from my 4x monitor desktop.
This is a workstation that I use multiple days a week, and has an uptime of about 50 days.
Unfortunately, I do not have a plausible root cause yet.

This is about the third or fourth time I've seen this, and I think the second machine. I suspect this has only been in instances where I am using an external display(s), but I am not certain. However, this is the first time I caught it in the moment, and remembered to record a video:
https://github.com/user-attachments/assets/27fb1543-f726-47aa-8a46-1381572befd5

I am on fully updated QubesOS 4.2.4, and in this case, I came back to my desk in the morning to find my workstation in this state, without any input from me or anyone else overnight

**Comment by ddevz** [comment]
Ok, here are logs of having the same symptom.  Note that this is a 4.2 system that is not entirely up to date.  I dont need specific help with this, I'm posting this in case this information can help solve other peoples problems.

Setup:  hit control-alt-delete to lock the screen.  The screen just flashes once.  I wonder why it didn't log out.  Then I realize it did and its the "display the desktop behind the lockscreen" problem.  I log back in and go after logs to help out:

**ps aux:**
`user     3118299  4.8  0.7 924976 115708 ?       Sl   11:44   0:02 xfwm4 --display :0.0 --sm-client-id `{some ID number}

notice that it's been running for 2 muinites (which seems about the amount of time it would have taken me to log in and do ps aux in dom0), and that gives us a timestamp of the event happening at 11:44 (with error of around +/- 60 seconds)

**sudo Journalctl:**
```
Jun 02 11:44:42 dom0 xscreensaver-auth[3118381]: PAM unable to dlopen(/usr/lib64/security/pam_sss.so): /usr/lib64/security/pam_sss.so: cannot open shared object file: No such file or directory
Jun 02 11:44:42 dom0 xscreensaver-auth[3118381]: PAM adding faulty module: /usr/lib64/security/pam_sss.so
```

**.xsession-errors:**
```
1780418671.669086 Cork requested and playback vchan empty. Draining playback stream.
1780418671.711784 Playback vchan empty and playback stream drained. Corking playback stream.
Property "/general/LockCommand" does not exist on channel "xfce4-session".

(xfwm4:1692938): Gdk-WARNING **: 11:44:35.046: The program 'xfwm4' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadRegion (invalid Region parameter)'.
  (Details: serial 24771767776 error_code 140 request_code 138 (XFIXES) minor_code 15)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)

(xfwm4:3118299): dbind-WARNING **: 11:44:35.413: Couldn't connect to accessibility bus: Failed to connect to socket /root/.cache/at-spi/bus_0.0: Permission denied
Property "/general/LockCommand" does not exist on channel "xfce4-session".
Property "/general/LockCommand" does not exist on channel "xfce4-session".
```
