### ISSUE TITLE
fedora-38 template missing package, qubes-snapd-helper

### ISSUE THREAD

**Issue by jimi3** [QubesOS/qubes-issues#8231]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
4.1.2 (R4.1)
### Brief summary
qubes-snapd-helper is missing from fedora-38 template
### Steps to reproduce
sudo dnf install qubes-snapd-helper
### Expected behavior
qubes-snapd-helper found and installed

### Actual behavior
[user@fedora-38 ~]$ sudo dnf install snapd qubes-snapd-helper
Last metadata expiration check: 0:00:06 ago on Sat May 27 08:37:05 2023.
No match for argument: qubes-snapd-helper
Error: Unable to find a match: qubes-snapd-helper

**Comment by rustybird** [comment]
@jimi3 Try again, it should be there now: https://github.com/QubesOS/updates-status/issues/3002#issuecomment-1565554163

**Comment by jimi3** [comment]
Yes, thanks it is working now!
