### ISSUE TITLE
dom0 update has broken mireage-firewall boot causing a crash

### ISSUE THREAD

**Issue by bluesteal** [QubesOS/qubes-issues#8243]
Getting an error when trying to boot mirage-firewall; it launches at first, and then it crashes due to an error. The log file shows
the following error:

Fatal error: exception Xs_protocol.Error("EACCES")
Raised at Xs_protocol.response in file "dunivers/ocaml-xenstore/client_lwt/xs_client_lwt.ml", line 318, characters 13-50
Called from Lwt.Sequential_composition.bind.create_result_promise_and_callback_if_deferred.callback in file "duniverse/lwt/src/core/lwt.ml", line 1849
Solo5: solo5_exit(2) called

The race condition could be in the mirage-xen code, when the mirage-fw uplink is up, mirage-fw tries to write its configuration, but the backend part (the sys-net side may not be ready). The suggested patch to mirage-net-xen is to wait a bit for the backend

Please see the following links:

https://forum.qubes-os.org/t/internal-error-libxenlight/18891/31

https://github.com/mirage/qubes-mirage-firewall/issues/177

**Comment by bluesteal** [comment]
This appears to be an issue within the mirage-net-xen package.

**Comment by DemiMarie** [comment]
Closing as “not our bug“ (the Qubes project is not responsible for the software causing this bug).

**Comment by bluesteal** [comment]
This is a mirageOS package?

**Comment by DemiMarie** [comment]
> This is a mirageOS package?

Please report this on the mirageOS issue tracker.

**Comment by bluesteal** [comment]
How do you determine this is not the result of a dom0 update?
