### ISSUE TITLE
Incorrect message when renaming of qube fails

### ISSUE THREAD

**Issue by verygreen** [QubesOS/qubes-issues#8256]
### Qubes OS release
4.1.2

### Brief summary
When renaming a qube (e.g. template) failes because there's disp vm running, a message is printed that outlines the failure.
This message lists the qube name three times where clearly one of those occurrences is supposed to list the new desired name.

![Screenshot_2023-06-12_00-16-18](https://github.com/QubesOS/qubes-issues/assets/625925/a5946356-1737-4ef3-824e-61d52a84f9ce)

### Steps to reproduce
Tename a template that has a dispvm running

**Comment by verygreen** [comment]
The somewhat trivial fix is here:
https://github.com/QubesOS/qubes-manager/pull/349

though I guess it does not like my lack of signature?

**Comment by andrewdavidwong** [comment]
> though I guess it does not like my lack of signature?

Would you mind generating a key and using it to sign your code? Instructions are provided here:

https://www.qubes-os.org/doc/code-signing/

**Comment by verygreen** [comment]
I signed the commit, but it's still unhappy.

**Comment by andrewdavidwong** [comment]
> I signed the commit, but it's still unhappy.

Hmm, did you upload your key to one of the approved keyservers?

**Comment by verygreen** [comment]
there are references to "A key server", in that code signing document, but no instructions how to do it or what those servers are.

**Comment by andrewdavidwong** [comment]
It's in this section:

https://www.qubes-os.org/doc/code-signing/#upload-the-key

**Comment by verygreen** [comment]
sorry, somehow missed it. Should be all good now.

**Comment by verygreen** [comment]
ha, "Great,", now it failed CI seemingly due to unrelated failure to fetch some fedora updates or some such. is there a way to retrigger the test?

**Comment by DemiMarie** [comment]
Don’t worry @verygreen, it isn’t your fault :smile:.  I just issued a command that will cause all the failed runs to be retried.

**Comment by marmarta** [comment]
This should have been closed.
