### ISSUE TITLE
dom0 update has broken mireage-firewall boot causing a crasha

### ISSUE THREAD

**Issue by bluesteal** [QubesOS/qubes-issues#8262]
In reference to https://github.com/QubesOS/qubes-issues/issues/8243

How can you determine this is a mirageOS issue and not a QubesOS issue?

**Comment by andrewdavidwong** [comment]
Duplicate of #8243

**Comment by andrewdavidwong** [comment]
Please do not open a new issue to ask a question about an existing issue.

**Comment by bluesteal** [comment]
that issue has been marked as closed but hasn't been resolved.

**Comment by andrewdavidwong** [comment]
> that issue has been marked as closed but hasn't been resolved.

That's still not a good reason to open a duplicate. Make your case on that issue and accept the outcome decided there. Don't spam the issue tracker just because you disagree with the devs.
