### ISSUE TITLE
Qubes 4.1 Crash

### ISSUE THREAD

**Issue by bluesteal** [QubesOS/qubes-issues#8263]
Getting a regularly occurring crash resulting in a RSOD (Red Screen Of Death) and an error message:

systemd uninitialized urandom read crash

**Comment by andrewdavidwong** [comment]
You need to provide a lot more information before this issue can be considered valid.

1. Stop deleting the issue template on all of your issues. Fill it out instead.
2. Provide your hardware information (HCL report plus any other relevant info).
3. List all significant ways your installation differs from a default installation (i.e., changes or customizations you've made).

After you've editing this issue to meet these standards, we'll take another look and consider reopening it. Do not open a duplicate.
