### ISSUE TITLE
Kloak

### ISSUE THREAD

**Issue by bluesteal** [QubesOS/qubes-issues#8265]
Is there any plan to implement Kloak for use in sys-usb or sys-whonix-ws?

Installing and using Kloak with Qubes-Whonix

Installation and use of Kloak.

**Comment by andrewdavidwong** [comment]
Please note that the issue tracker (qubes-issues) is not intended to be a place for fielding questions. Instead, we have other [venues meant for asking questions, asking for help, and having discussions](https://www.qubes-os.org/support/). (By contrast, the issue tracker is more of a technical tool intended to support our developers in their work.) Thank you for your understanding!
