### ISSUE TITLE
v4.2 - XScreenSaver & XScreenSaver Settings not opening window

### ISSUE THREAD

**Issue by andrew-drogalis** [QubesOS/qubes-issues#8266]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
v4.2

### Brief summary
XScreenSaver & XScreenSaver Settings not opening window in Dom0. 

### Steps to reproduce
Click XScreenSaver or XScreenSaver Settings from System Settings Menu

### Expected behavior
Opens Screensaver settings window as in v4.1.2.

### Actual behavior
If typing "xscreensaver" in the dom0 terminal it says the task is already running and the window is open. Nothing appears on the screen.

**Comment by andrew-drogalis** [comment]
![xscreensaver_snip](https://github.com/QubesOS/qubes-issues/assets/108765079/a87463ff-25d9-4985-8672-17137f73c67e)

I killed the running program and attempted to restart. This is the error from that attempt.

**Comment by marmarek** [comment]
Calling `xscreensaver` isn't supposed to open any dialog, it is a background process that is responsible for actual screen locking.

But indeed `xscreensaver-settings` (that is also connected to the appropriate menu entry) seems to be broken, it fails with:
`Unable to retrieve object 'manual' from class template for type 'XScreenSaverDialog' while building 'XscreenSaverDialog'`.

**Comment by m4teh** [comment]
Getting the same thing here.
Additionally - does it also take a couple of seconds for your lock screens to transition to the black background? It seems to "freeze" on the unlocked environment before going black. Q4.1 it locked black immediately.

**Comment by euidzero** [comment]
Not sure this is related but here on 4.2rc2 (migrated from 4.1), with no gui-vm, xcreensaver does not present the login prompt anymore after locking the screen. I can only see the cursor. Trying to blindly enter the password does not work.
The only solution to login is to kill xscreensaver from a tty.

**Comment by rapenne-s** [comment]
I confirm the error still exists in 4.2-RC3

**Comment by rapenne-s** [comment]
@m4teh see #8473 for explanations about the delay

**Comment by euidzero** [comment]
Xscreensaver is coredumping here. See attached file.

[xscreensaver-segfault.txt](https://github.com/QubesOS/qubes-issues/files/12513818/xscreensaver-segfault.txt)

**Comment by euidzero** [comment]
BTW : xscreensaver-auth: 15:24:56.11:   "xscreensaver-auth" must be setuid root.

**Comment by euidzero** [comment]
At least the segfault is fixed there  : https://bodhi.fedoraproject.org/updates/FEDORA-2023-bb3dc15711

**Comment by marmarek** [comment]
> But still xscreesaver-auth is segfaulting for me.

What desktop environment you use? Default Xfce or something else?
Can you run `/usr/libexec/xscreensaver/xscreensaver-auth --verbose` and provide the output (it should show the password prompt but without blanking the screen)?

**Comment by euidzero** [comment]
Running the default xfce.

xscreensaver-auth: 10:28:47.64: pwnam: couldn't get password of "XXX"
xscreensaver-auth: 10:28:47.64: running as user "XXX"
xscreensaver-auth: 10:28:47.65: PAM: pam_start ("xscreensaver", "XXX", ...) ==> 0 (Success)
xscreensaver-auth: 10:28:47.65:   pam_set_item (p, PAM_TTY, ":0.0") ==> 0 (Success)
xscreensaver-auth: 10:28:47.65:   pam_authenticate (...) ...
xscreensaver-auth: 10:28:47.92:     pam_conversation (ECHO_OFF="Password: ") ...
xscreensaver-auth: 10:28:48.26: mouse is at 2823,507 on monitor 4 2560x1440+1920+0 "DP-1-1"
xscreensaver-auth: 10:28:48.26: theme: default
Aborted (core dumped)

**Comment by marmarek** [comment]
The `xscreensaver-auth` failure looks unrelated to the original issue reported here. Looking at its source code, it uses `abort()` if loading a font fails. Sadly more diagnostic messages around there are not compiled in by default.

Maybe something went wrong during update from R4.1 and fonts are not configured? Check `/etc/xscreensaver/XScreenSaver.ad - there should be various entries like `*Dialog.headingFont`, `*Dialog.bodyFont` etc with values like `sans-serif 14` (not a long string like `-*-helvetica-...`). If you don't have it there, or have the long names, check for `.rpmnew` files in that directory and copy them over matching files without `.rpmnew` (if you have modified any of them manually, you may need to re-apply the changes). And then call `sudo update-xscreensaver-hacks`.

**Comment by euidzero** [comment]
Indeed /etc/xscreensaver/XScreenSaver.ad was not  correctly updated (old fonts used) during the migration to 4.2 (question is why ?). But no recent `.rpmnew` files there.

I moved away `/etc/xscreensaver` completely then force reinstall of all `xscreensaver-*-6.06-3.fc37.x86_64` and  xscreensaver-auth is no more segfaulting.

Thanks.

**Comment by rapenne-s** [comment]
I confirm this works fine now!
