### ISSUE TITLE
Use Linux diskseq in qvm-block

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#8268]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### The problem you're addressing (if any)

qvm-block is racy: it is possible for the GUI to show stale information, which can cause the wrong device to be attached if a device is destroyed and its `/dev` node reused at just the wrong time.  This cannot be triggered by an attacker, so it is not a vulnerability.

### The solution you'd like

Use Linux’s diskseq feature to prevent that.

### The value to a user, and who that user might be

All users who use `qvm-block` will benefit from more reliable device handling.

**Comment by marmarek** [comment]
While this race theoretically might happen, it is rather unlikely without user's intentional action (like unplugging the device while clicking attach). On the other hand, implementing something like this would make persistent attachments even harder if not impossible (https://github.com/QubesOS/qubes-issues/issues/8268). So, this idea is more a regression than improvement.

**Comment by DemiMarie** [comment]
Did you mean #3437?  If so, that issue shows that current approach is too fragile to be very useful in practice.  A much more robust solution would be for the backend to expose multiple characteristics of the device, such as diskseq, `/dev` node, disk UUID, partition UUID, PCIe/USB/etc path, partition UUID (if applicable), backing file of a loop device (if applicable), and more.  The Admin API would then pick a device that matched some combination of these fields and (provided there was exactly one match) inform the backend of the `/dev` node and diskseq of the device chosen.

**Comment by marmarek** [comment]
The solution might involve (or not) some of the parts you propose, but as part of a larger devices rework, not just adding on top of the current qvm-block (see my earlier comment why).
