### ISSUE TITLE
qubes-global-config does not saves default_dispvm set to none

### ISSUE THREAD

**Issue by Asterium01** [QubesOS/qubes-issues#8271]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
4.2.0-rc1

### Brief summary
When I try to delete default-dvm, I get an error:
```
This qube cannot be removed. It is used used as:
- Global property default_dispvm
…
```
In the qubes-global-config settings, default_disp is set to NONE.

### Steps to reproduce
1) Set default dispvm to none in qubes-global-config, and manually remove the default disp template from all cubes. 
2) Try to remove default-dvm

### Expected behavior
Qube default-dvm must be removed without obstruction.

### Actual behavior
There is no way to delete it. Was able to change the default_dispvm with qubes-prefs default_dispvm , but if you try to delete this cube in the future you will get a notice that this cube is not only assigned to global property, it is also the default_dispvm for dom0.

**Comment by Asterium01** [comment]
If you set default_dispvm in qubes-global-config to NONE and then check qubes-prefs, it still specifies default_dispvm as default-dvm. Apparently qubes-global-config does not pass the new value.

**Comment by marmarta** [comment]
Interesting, I can't reproduce it. Could you try running `qubes-global-config` in dom0 console and see if there are any errors? Also, are you using a guivm?

**Comment by Asterium01** [comment]
> Interesting, I can't reproduce it. Could you try running `qubes-global-config` in dom0 console and see if there are any errors? Also, are you using a guivm?

Right now I do not have access to qubes 4.2. I used a clean installation of qubes os without sys-gui(guivm).

Try to set default_dispvm to None in qubes-global-config, you can also set it to any other qube (instead of None) and then check in qubes-prefs and qvm-prefs the new value. I don't know why, but in my case the default_dispvm value only changed for dom0.
If I change the value through the console using qubes-prefs to globally change default_dispvm or qvm-prefs for one qube, everything works fine.
