### ISSUE TITLE
Legacy Qubes Builder error when building 4.2 templates

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#8272]
```
/home/user/qubes-builder/qubes-src/builder-debian//prepare-chroot-debian: line 193: /home/user/qubes-builder/qubes-src/builder-debian/keys/qubes-debian-r4.2.asc: No such file or directory
make[1]: *** [/home/user/qubes-builder/qubes-src/builder-debian//Makefile-legacy.debian:28: /home/user/qubes-builder/chroot-vm-bookworm/home/user/.prepared_base] Error 1
make: *** [Makefile:265: core-vchan-xen-vm] Error 1
```

**Comment by adrelanos** [comment]
Not sure I should make a different bug report for other Qubes R4.2 Debian bookworm build bug reports.

During `make qubes-vm`:

```
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
OK
Hit:1 https://deb.debian.org/debian bookworm InRelease                                    
Get:2 https://deb.qubes-os.org/r4.2/vm bookworm InRelease [2513 B]      
Err:2 https://deb.qubes-os.org/r4.2/vm bookworm InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 5BB71C441BCB10FE
Get:3 https://deb.debian.org/debian bookworm/main Sources [9628 kB]
Get:4 https://deb.qubes-os.org/r4.2/vm bookworm-testing InRelease [2542 B]
Err:4 https://deb.qubes-os.org/r4.2/vm bookworm-testing InRelease 
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 5BB71C441BCB10FE
Get:5 https://deb.debian.org/debian bookworm/main Translation-en [6076 kB]
Reading package lists... Done                                                                                                                                                                
W: GPG error: https://deb.qubes-os.org/r4.2/vm bookworm InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 5BB71C441BCB10FE
E: The repository 'https://deb.qubes-os.org/r4.2/vm bookworm InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: GPG error: https://deb.qubes-os.org/r4.2/vm bookworm-testing InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 5BB71C441BCB10FE
E: The repository 'https://deb.qubes-os.org/r4.2/vm bookworm-testing InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
make[1]: *** [/home/user/qubes-builder/qubes-src/builder-debian//Makefile-legacy.debian:28: /home/user/qubes-builder/chroot-vm-bookworm/home/user/.prepared_base] Error 100
make: *** [Makefile:265: core-vchan-xen-vm] Error 1
```

**Comment by andrewdavidwong** [comment]
> Not sure I should make a different bug report for other Qubes R4.2 Debian bookworm build bug reports.

If you think it's the same bug, then a single issue is fine; otherwise, a separate issue is preferred. If you're not sure, it's fine to wait for a diagnosis or another dev opinion.

**Comment by fepitre** [comment]
It fails with legacy builder because we tend to support only R4.2 with only new qubes-builder which has the keys: https://github.com/QubesOS/qubes-builderv2/tree/main/qubesbuilder/plugins/chroot_deb/keys. I would let Marek decides the strategy but I'm very inclined to stop using legacy builder for R4.2 because every thing works correctly with it and this is how we build template for R4.2. We don't use legacy builder for any part of R4.2.

**Comment by marmarek** [comment]
Generally, it should be possible to build R4.2 templates and packages with legacy builder (even if not used for official builds anymore), so this issue is valid.

**Comment by fepitre** [comment]
In that case we should improve sharing keys as already discussed because they are duplicates in many places now. What do you think?

**Comment by adrelanos** [comment]
I am not requesting legacy builder to support building R4.2 templates. I just wasn't aware of builderv2. If the latter works fine, that's most than fine with me.

**Comment by andrewdavidwong** [comment]
It sounds like this is still a legitimate bug (as Marek said), but one that doesn't affect you, since you're happy to use Qubes Builder v2. I suppose we should leave this open, then (at least until legacy builder support ends), though it's unclear, now, whether there's any demand for a fix (i.e., whether there's anyone out there who cares about using the legacy builder to build 4.2 templates). Setting priority to "minor" for now.
