### ISSUE TITLE
Editing cells in LibreOffice calc is laggy

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#8281]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

R4.1

### Brief summary

Editing spreadsheet cell directly in the cell has noticeable lag between keypress and showing the effect. Edit field above the spreadsheet doesn't have this problem.

### Steps to reproduce

1. Open LibreOffice Calc
2. Create new spreadsheet
3. Click any cell
4. Enter some characters

### Expected behavior

They appear immediately.

### Actual behavior

They appear with noticeable (but small) delay.
Editing cell by clicking on it and then clicking on the edit field at the top doesn't have this issue.

The issue happens at least in Fedora 37 (libreoffice-7.4.6.2-2.fc37.x86_64) and Ubuntu 22.04 (libreoffice 1:7.3.7-0ubuntu0.22.04.3) templates. I have _not_ verified how it behave outside of Qubes (might be a good first step in diagnosis).

**Comment by 1cho1ce** [comment]
Seems like the same problem as discussed here:
https://forum.qubes-os.org/t/100-cpu-with-every-scroll-in-libreoffice/8027
With a fix from Rudd-O:

> Here is the real fix. Put this in /etc/profile.d/libreoffice_kf5.sh in your template qube:
> 
> export SAL_USE_VCLPLUGIN=kf5
> 
> Then install the following package in your template qube:
> 
> dnf install -y libreoffice-kf5
> 
> Stop your template qube and your application qube. Start your application qube and open up LibreOffice. It should run almost as fast as it used to.

**Comment by marmarek** [comment]
Thanks for linking this. It seems to help indeed. But I hate to install 200MB of extra packages just to fix a regression in a single application...

**Comment by DemiMarie** [comment]
If Qubes defaulted to KDE apps instead of XFCE apps, would the bloat go away @marmarek?

**Comment by marmarek** [comment]
Maybe? But that would be even more inconsistent than it is now

**Comment by TNTBOMBOM** [comment]
Based on Whonix's past experience (and I believe it still holds true), XFCE has consistently exhibited lower resource usage compared to KDE (if that is what matters in this context):

https://forums.whonix.org/t/whonix-xfce-development/6213/9

https://forums.whonix.org/t/user-poll-xfce-vs-kde-kde-deprecation-considered/6235/9

But I have observed this behavior with multiple software applications, not just LibreOffice. At the time, I attributed it to my older PC not being equipped with high-end technology.

**Comment by DemiMarie** [comment]
I’m pretty sure this is a combination of an upstream LibreOffice bug and a Cairo bug.  In the meantime, we could conflict with the `libreoffice-gtk3` and `libreoffice-gtk4` packages, causing LibreOffice to fall back to the `gen` plugin (ugly) or the `kf5` plugin.

**Comment by top-cmyk** [comment]
Affects 4.2

**Comment by top-cmyk** [comment]
Discussions elsewhere indicate this may be an upstream bug in LibreOffice

**Comment by besendorf** [comment]
Using kf5 solved this for me. Until this is fixed I would think it makes sense to include it by default. That would make the experience for new Qubes Users way better.

**Comment by DemiMarie** [comment]
For me kf6 and gtk3 are not laggy, but gtk4 crashes.
