### ISSUE TITLE
`lvcreate` syntax change (?) breaks lvm_thin code in e.g. fc38 development environment

### ISSUE THREAD

**Issue by rustybird** [QubesOS/qubes-issues#8282]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

n/a

### Steps to reproduce

    $ rpm -qf `which lvcreate`
    lvm2-2.03.18-2.fc38.x86_64
    $ cd qubes-core-admin && ./run-tests qubes.tests.storage_lvm/TC_00_ThinPool

### Expected behavior

Test suite succeeds

### Actual behavior

Several test failures where `lvcreate` complains about [lvm_thin's use of the `--snapshot` option](https://github.com/QubesOS/qubes-core-admin/blob/v4.2.11/qubes/storage/lvm.py#L769-L773):

    ======================================================================
    ERROR: qubes.tests.storage_lvm/TC_00_ThinPool/test_007_resize_running
    ----------------------------------------------------------------------
    [...]
      File "/home/user/qubes-core-admin/qubes/storage/lvm.py", line 655, in _snapshot
        await qubes_lvm_coro(cmd, self.log)
      File "/home/user/qubes-core-admin/qubes/storage/lvm.py", line 835, in qubes_lvm_coro
        return _process_lvm_output(p.returncode, out, err, log)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/user/qubes-core-admin/qubes/storage/lvm.py", line 812, in _process_lvm_output
        raise qubes.storage.StoragePoolException(err)
    qubes.storage.StoragePoolException:   Command does not accept option: --snapshot.

**Comment by DemiMarie** [comment]
This is an lvm2 bug.  I filed [Red Hat bug #2216286](https://bugzilla.redhat.com/show_bug.cgi?id=2216286) for it.  Qubes OS needs a patched lvm2 for security reasons and so is not impacted.

**Comment by andrewdavidwong** [comment]
@rustybird, could you please clarify what you mean by "Qubes Release: `n/a`"? Is this not a bug in Qubes OS?

@DemiMarie, could you please clarify what you mean by "Qubes OS needs a patched lvm2 for security reasons and so is not impacted"? Does this bug not affect Qubes OS?

**Comment by rustybird** [comment]
Yes, only tests. (There was a possibility of it affecting an actual Qubes OS release in case we ever need to backport a new LVM package to dom0 for some reason - but that should be all good now because they already fixed the problem upstream thanks to @DemiMarie's bug report.)
