### ISSUE TITLE
debian-12 shows spurious IBus notification and a tray icon

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#8286]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

R4.2 (R4.1 too?)

### Brief summary

Qube based on debian-12 template shows on startup IBus Notification "Keymap changes do not work in Plasma Wayland at present. Please use systemsettings5 instead.". There is also ibus tray icon for every qube based on this template.

### Steps to reproduce

1. Install debian-12 template (applies at least to https://github.com/QubesOS/updates-status/issues/3787)
2. Create and start any AppVM based on it

### Expected behavior

No notifications, just starts. And also no tray icon by default (maybe only when IBus was explicitly enabled? not sure).

### Actual behavior

https://openqa.qubes-os.org/tests/75766#step/startup/12

**Comment by adrelanos** [comment]
Confirmed for R4.2.

Never seen this in R4.1.

**Comment by TNTBOMBOM** [comment]
![ibus](https://github.com/QubesOS/qubes-issues/assets/11895339/94653b54-9fbc-4e03-b5ee-2a25f90f435b)

Why its there in the first place? (not in debian default official packages)
