### ISSUE TITLE
notify-send as root doesn't work on fedora-38-xfce

### ISSUE THREAD

**Issue by rapenne-s** [QubesOS/qubes-issues#8289]
### Qubes OS release

Qubes OS 4.1

### Brief summary

The following test is proposed in a [documentation enhancement](https://github.com/QubesOS/qubes-doc/pull/1283), and should work: `sudo notify-send "$(hostname): Test notify-send OK" --icon=network-idle`

However, for me it fails with the message `Failed to execute child process “dbus-launch” (No such file or directory)` and exit code 1.

It works fine with debian-11

### Steps to reproduce

Start a qube using fedora-38-xfce and run `sudo notify-send "$(hostname): Test notify-send OK" --icon=network-idle` in a terminal.

### Expected behavior

It should display a popup message.

### Actual behavior

There is no popup message, but instead the command is failing.

**Comment by bojavou** [comment]
I'm also seeing this on Fedora 37 and 36. Had to go all the way back to 35 to get my VPN qube working.

**Comment by DemiMarie** [comment]
@bojavou better to just drop the notify-send call
