### ISSUE TITLE
Qubes-provided kernels ship binaries depending on older versions of libraries than template provides

### ISSUE THREAD

**Issue by logoerthiner1** [QubesOS/qubes-issues#8290]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

R4.1

template vm fedora 38

### Brief summary

I am using dkms to compile kernel modules under fedora 38 template vm when I see these output

```
Signing module /var/lib/dkms/foo/bar.ko
/lib/modules/6.1.12-1.qubes.fc32.x86_64/build/scripts/sign-file: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory
```

This is when I find out that fedora 38 does not provide libcrypto.so.1.1 by default.

```
$ ldd `which openssl`
	linux-vdso.so.1 (0x00007ffc9cdc2000)
	libssl.so.3 => /lib64/libssl.so.3 (0x0000768ffa72e000)
	libcrypto.so.3 => /lib64/libcrypto.so.3 (0x0000768ffa200000)
	libc.so.6 => /lib64/libc.so.6 (0x0000768ffa022000)
	libz.so.1 => /lib64/libz.so.1 (0x0000768ffa714000)
	/lib64/ld-linux-x86-64.so.2 (0x0000768ffa8d4000)
$ ldd /lib/modules/6.1.12-1.qubes.fc32.x86_64/build/scripts/sign-file
	linux-vdso.so.1 (0x00007ffde71a2000)
	libcrypto.so.1.1 => not found
	libc.so.6 => /lib64/libc.so.6 (0x0000714a4c848000)
	/lib64/ld-linux-x86-64.so.2 (0x0000714a4ca35000)
```

In brief the `sign-file` binary provided by qubes os are compiled under fedora 32 and it depends on `libcrypto.so.1.1`; but fedora 38 does not have this any more, instead it only have `libcrypto.so.3`

Actually libcrypto is merely one of the libraries and the problem may be widerand not that easy to solve. Even worse the dynamic library depended by binaries under /lib/modules/6.1.12-1.qubes.fc32.x86_64 may need to be served elsewhere as the template vm can be of any distro, from fedora to debian and from earlier version to later version.

Afaik for example binaries compiled against libc 2.34 afterwards is not compatible with earlier libc binaries. I am not sure whether different distro are compatible with libraries but sometimes this can be a bigger problem though.

### Steps to reproduce

1. Use fedora 38 template vm
2. Execute `/lib/modules/$(uname -r)/build/scripts/sign-file`

### Expected behavior

The binary runs.

### Actual behavior

The binary complains that `libcrypto.so.1.1` does not exist

**Comment by marmarek** [comment]
> Afaik for example binaries compiled against libc 2.34 afterwards is not compatible with earlier libc binaries. 

This one fortunately works in a good direction - binaries linked with older libc will work with latter version. And "thanks" to dom0 usually being the older one, it's okay.

But for the other libraries, indeed it may not work this way. The solution might be to simply not ship those binaries at all. The example you provided should be easy to avoid (the modules are signed with an ephemeral key that isn't included in the headers, so you can simply skip modules signing with similar end result). For others, the sources are included too, so removing the binaries should result in rebuilding them when you try to build modules.

**Comment by logoerthiner1** [comment]
I suspect whether newer template vm always provide openssl-devel and *-devel when dkms installs and runs. Therefore some confusing binary compilation failure may be expected at that time.

The solution I would expect is like redirect the binaries into something like `/lib/modules/vers/sysroot/lib64/ld-linux-x86-64.so.2 --library-path /lib/modules/vers/sysroot/usr/lib` and put all the required library from fedora 32 into the xvdd.

**Comment by marmarek** [comment]
> The solution I would expect is like redirect the binaries into something like `/lib/modules/vers/sysroot/lib64/ld-linux-x86-64.so.2 --library-path /lib/modules/vers/sysroot/usr/lib` and put all the required library from fedora 32 into the xvdd.

I don't like it at all, it's a waste of space for rather niche case.
In any case, you can also use [kernel from your VM](https://wwwpreview.qubes-os.org/doc/managing-vm-kernels/#using-kernel-installed-in-the-vm) which should be friendlier if you want to build modules in that VM.
