### ISSUE TITLE
GUI Domain: `AttributeError: 'int' object has no attribute 'isdigit' at line 33 of file /usr/bin/qubes-global-settings.`

### ISSUE THREAD

**Issue by Morribyte** [QubesOS/qubes-issues#8294]
### Qubes OS release: 
4.2

### Brief summary:
Hi there, I'm the same person who submitted #8154 . Thanks to your updates, I was able to successfully launch into GUI domain. Also, as a sidenote, due to this issue I can't really access the internet without any of my VMs it'll be pretty tough to grab and upload any logs as I am currently typing on my Windows PC.

Got into Sys-gui domain after restarting the PC after finishing the command but when I logged in an error popped up that said something to the effect of "An error occurred, please report it." but it didn't have any links to any logs or any other such information I could use.

Interestingly, when I was opening Qubes Global settings from the Qubes Manager I was able to open it up. But the error at the top right saying "Error occurred, please report" pops up at the same time. It seems like no matter which Qubes setup/GUI tool I click on, it errors in some way and then works depending on where I activate it and/or it just works intermittently.

I will do my best to get whatever information y'all need though. Thanks so much!

### Steps to reproduce

I haven't reinstalled Qubes to try to see if it's replicable, BUT the steps I took were:

1. Turned on PC and log in.
2. Ran Qubes updater. Saw that the salt package was updated and made sure that went through.
3. Finished the install of sys-gui successfully.
4. Logged out as instructed and logged back in to an empty desktop. 
5. Restarted PC again just in case, and logged back in. This time it got through. 
6. Error pops up saying "Error occurred" as I described in the brief summary section.
7. Opened the "start" menu to launch up file manager so I could see if there were any logs and where they might be. Problem is, only "sys-gui" shows up on the start menu, no other VMs.
8. Tried to open Qubes Global Settings to see if there was anything there I could check out to see if I could fix it. Upon opening, it says "Whoops. A critical error has occurred. This is most likely a bug in Qubes Manager." 

AttributeError: 'int' object has no attribute 'isdigit'
at line 33
of file /usr/bin/qubes-global-settings.

### Expected behavior: 

Launch into sys-gui without any errors popping up, allowing me to see all of my VMs and open up the qubes global settings manager.

### Actual behavior

Pretty much the exact opposite of the expected behavior. It just errors out. Also, when I open the Qubes manager that shows the VMs, it does show Dom0. I figure that's probably what it's supposed to do, but I figured i'd mention it just in case.

**Comment by andrewdavidwong** [comment]
[Every issue must be about a single, actionable thing.](https://www.qubes-os.org/doc/issue-tracking/#every-issue-must-be-about-a-single-actionable-thing) Therefore, I'm amending this issue to be about the Qubes Global Settings / Qube Manager bug described in your steps to reproduce. If there are separate bugs, please open separate issues for them. However, please note two things:

1. You've already opened two issues about the same general problem. That's okay *so long as they're genuinely about separate things*. Sometimes we don't know whether they are until later. That's okay. Just try to avoid opening [duplicate issues](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) if you can avoid it. Comment on the appropriate existing issue instead.

2. Please keep in mind that the issue tracker (`qubes-issues`) is not intended to serve as a help desk or tech support center. Instead, we've set up other [venues where you can ask for help and support, ask questions, and have discussions](https://www.qubes-os.org/support/). (By contrast, the issue tracker is more of a technical tool intended to support our developers in their work.) Thank you for your understanding!

**Comment by andrewdavidwong** [comment]
Actually, it looks like there's already an existing issue for this: https://github.com/QubesOS/qubes-issues/issues/8152

This appears to be a [duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If anyone believes this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Comment by Morribyte** [comment]
> [Every issue must be about a single, actionable thing.](https://www.qubes-os.org/doc/issue-tracking/#every-issue-must-be-about-a-single-actionable-thing) Therefore, I'm amending this issue to be about the Qubes Global Settings / Qube Manager bug described in your steps to reproduce. If there are separate bugs, please open separate issues for them. However, please note two things:
> 
> 1. You've already opened two issues about the same general problem. That's okay _so long as they're genuinely about separate things_. Sometimes we don't know whether they are until later. That's okay. Just try to avoid opening [duplicate issues](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) if you can avoid it. Comment on the appropriate existing issue instead.
> 2. Please keep in mind that the issue tracker (`qubes-issues`) is not intended to serve as a help desk or tech support center. Instead, we've set up other [venues where you can ask for help and support, ask questions, and have discussions](https://www.qubes-os.org/support/). (By contrast, the issue tracker is more of a technical tool intended to support our developers in their work.) Thank you for your understanding!

Hi there. Sorry about the confusion. I've taken note on what you've said and will be more diligent in the future. Thanks for being patient!

The only reason I put them together was because I thought it was caused by the same issue. Looking back I can see why I should still put them separately because I can't be sure. My thinking was that, because the VMs aren't showing up in Qubes Manager (that is, look like they weren't installed) while using GUI domain, that it would cause the errors when you bring up Qubes config menus that called the name of VMs that weren't visible on the list.  And since I had no way to look at the logs, I couldn't investigate properly. I should've considered opening two issues or just submitting one for now and waiting -- you're right about that.
