### ISSUE TITLE
qubes-u2f unable to be installed due to unavailable python3-u2flib-host dependency

### ISSUE THREAD

**Issue by ddd** [QubesOS/qubes-issues#8298]
### Qubes OS release

4.2.0-rc1

### Brief summary

`qubes-u2f` is unable to be installed on `debian-11` and `fedora-38` templates due to unavailable `python3-u2flib-host` dependency. This library has since been **[deprecated](https://github.com/Yubico/python-u2flib-host)** and replaced by [python-fido2](https://github.com/Yubico/python-fido2).

See also: #5501

### Steps to reproduce

Debian 11
`sudo apt install qubes-u2f`

Fedora 38
`sudo dnf install qubes-u2f`

### Expected behavior

The `qubes-u2f` package is able to be installed without any issues.

### Actual behavior

Debian 11
```
user@debian-11:~$ sudo apt install qubes-u2f
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 qubes-u2f : Depends: python3-u2flib-host but it is not installable
E: Unable to correct problems, you have held broken packages.
```

Fedora 38
```
[user@fedora-38 ~]$ sudo dnf install qubes-u2f
Fedora 38 - x86_64 - Updates                    2.2 kB/s | 5.9 kB     00:02    
Error: 
 Problem: conflicting requests
  - nothing provides python3-u2flib-host needed by qubes-u2f-1.2.10-1.fc38.noarch from qubes-vm-r4.2-current
(try to add '--skip-broken' to skip uninstallable packages)
```

**Comment by andrewdavidwong** [comment]
Looks like this has happened before: #4467.

**Comment by marmarek** [comment]
qubes-u2f (now renamed to qubes-ctap) do not depends on python3-u2flib-host anymore.
