### ISSUE TITLE
PS/2 touchpad broken in 4.2.0-rc1

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#8301]
### Qubes OS release

`4.2.0-rc1`

### Brief summary

PS/2  touchpad broken.

### Steps to reproduce

Install Qubes `4.2.0-rc1` and try using the touchpad.

### Expected behavior

Functional touchpad.

### Actual behavior

Broken touchpad.

### Additional information

Was functional in Qubes `R4.1`.

Using USBVM. (This was OK in `R4.1` too.)

But the touchpad is not an internal USB touchpad. It much be PS/2. This is because it was functional in Qubes `R4.1` previously too, because it was functional along with the internal keyboard while USBVM was shutdown (while USB connected mice was dysfunctional as expected when USBVM is shutdown).

### Debugging

How to debug this?

journalctl doesn't show any error related to `touchpad`, `pad`, `touch`, `mouse`, `mice`.
Neither xorg log showing any errors.
`xinput` doesn't show the device.

Have any changes been made in Qubes `R4.2` which might result in the disabling of the internal PS/2 touchpad?

**Comment by adrelanos** [comment]
Qubes dom0 testing updates fixed this issue.

Why it happened or how it was fixed, I don't know.

**Comment by andrewdavidwong** [comment]
Closing as resolved. If anyone believes this issue is not yet resolved, or if anyone is still affected by this issue, please leave a comment, and we'll be happy to reopen it. Thank you.
