### ISSUE TITLE
Heads needs testers with external programmers 

### ISSUE THREAD

**Issue by tlaurion** [QubesOS/qubes-issues#8302]
Please become an official pull request tester?

https://forum.qubes-os.org/t/heads-needs-testers-with-external-programmers/19564

Heads is in rolling release scheme for the moment.
If you are running a maximized board version for a platform, you can safely upgrade internally after downloading ROM for your platform directly from pull request's green checkmark, clicking on your platform flavor and downloading the ROM from artifacts.
 
# Do not flash pull request related ROMs unless you have an external programmer!!!!

Official documentation is here to follow https://osresearch.net/Updating

Thanks for your help and hoping to see you interact in pull requests over https://github.com/osresearch/heads/pulls and over the QubesOS forum!

EDIT: at the time of writing this, testers are needed on
- https://github.com/osresearch/heads/pull/1398
- https://github.com/osresearch/heads/pull/1419

**Comment by andrewdavidwong** [comment]
`qubes-issues` is not an appropriate place for announcements or requests for testers. Please see our [issue tracking guidelines](https://www.qubes-os.org/doc/issue-tracking/). I see that you already posted this on the forum, which is a suitable place. You may also send this to the [`qubes-users` mailing list](https://www.qubes-os.org/support/), if you wish. Thank you for your understanding.
