### ISSUE TITLE
Intermittent network uplink failures

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#8305]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

R4.2

### Brief summary

In certain qubes, network uplink will often fail (`qubes-network-uplink@eth0.service` fails to start).  `systemctl status qubes-network-uplink@eth0.service` reveals `RTNETLINK answers: File exists`, which turns out to be from the `ip address add` calls.  Using `ip address replace` fixes the problem; patch coming.

### Steps to reproduce

Start a Fedora 38-based qube with `sys-whonix` as its NetVM.

### Expected behavior

Network uplink works.

### Actual behavior

Network uplink fails.

**Comment by marmarek** [comment]
How can it happen? Is `qubes-network-uplink@eth0.service` started twice for the same interface in some cases? In such case, is just using `ip addr replace` enough? The `setup-ip` script does few other things too.

**Comment by DemiMarie** [comment]
> How can it happen? Is `qubes-network-uplink@eth0.service` started twice for the same interface in some cases? In such case, is just using `ip addr replace` enough? The `setup-ip` script does few other things too.

I’m not sure.  I wonder if addresses are automatically configured by netfront.

**Comment by marmarek** [comment]
On Fri, Jun 30, 2023 at 02:50:02PM -0700, Demi Marie Obenour wrote:
> I’m not sure.  I wonder if addresses are automatically configured by netfront.

They are not.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab

**Comment by marmarek** [comment]
I have an idea how this could happen:
1. Interface gets attached (or VM started)
2. `setup-ip` starts
2. At this very moment interface gets detached and attached again (unlikely when point 1 was manual attach, but maybe possible close to VM startup?)
3. `setup-ip` started in point 2 configures new interface and completes
4. udev schedules another `setup-ip` call

This is just speculation, I have no idea (not even a hint) if this is what really happens (a bit unlikely, as it requires _two_ changes to the interface in a short time). But in this case, I don't think any amount of systemd or udev magic would help, specially as the interface theoretically could disappear in the middle of `setup-ip` execution. So, making `setup-ip` idempotent sounds like a good plan.
