### ISSUE TITLE
KeePassXC Split Icons

### ISSUE THREAD

**Issue by ElliotKillick** [QubesOS/qubes-issues#8306]
### The problem you're addressing (if any)

KeePassXC entries have no icons in an air-gapped `vault` qube.

### The solution you'd like

A system should be set up to securely download and give icons to KeepassXC similar to what Qubes does for app menus. KeePassXC can privately fetch favicons with DuckDuckGo's service so perhaps we could use that. KeePassXC [doesn't support plugins](https://keepassxc.org/docs/) so a small patch would probably have to be created to make KeePassXC get icons from a qrexec service (maybe some pluggable version of it could get upstreamed?).

### The value to a user, and who that user might be

Allowing users to have favicons in their KeepassXC databases without having to give their `vault` qube network access.

**Comment by ddd** [comment]
correct me if i'm wrong here, but wouldn't this add unnecessary attack surface and also enable a malicious keepassxc binary to exfiltrate data? I don't see the value in adding such a feature.

**Comment by ElliotKillick** [comment]
@ddd That's a valid concern. My hope was that DDG's private favicon fetching API could avoid most of that but an MITM attacker just counting requests would still be a loophole.

Similar to what is already done for the app menu, I think some users would like having icons here too. However, there's no fully secure way of implementing it due to the MITM possibility so I'm closing...

**Comment by andrewdavidwong** [comment]
Closed as "won't do." If anyone has a new reason for why this should be done, please leave a comment, and we'll be happy to take another look. Thank you.
