### ISSUE TITLE
The new application menu does not respond to the mouse cursor

### ISSUE THREAD

**Issue by Asterium01** [QubesOS/qubes-issues#8313]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Brief summary
The first time you open the application menu, when you hover your mouse over Qube, its submenu is not displayed.

https://github.com/QubesOS/qubes-issues/assets/132194182/0f2a7836-31a2-4382-a498-0fb3b793760e

### Expected behavior
The submenu should be displayed when you hover the mouse cursor

### Actual behavior
The submenu is not displayed immediately. You have to go to other menu categories first or click on Qube about five times for the submenu to display.

**Comment by marmarta** [comment]
does it happen after each reboot? Will this also happen if you run `systemctl --user stop qubes-app-menu` and click on the menu? (it will take a second to show after that)
