### ISSUE TITLE
/usr/sbin/policy-rc.d file exists which prevents daemons from (re-)starting during package upgrades

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#8316]
### Qubes OS release

R4.2

### Brief summary

File `/usr/sbin/policy-rc.d` file exists and prevents daemons from (re-)starting during package upgrades.

### Steps to reproduce

1. install Qubes R4.2
2. Install whonix-gw-16 template from qubes-templates-community-testing repository
3. `ls -la /usr/sbin/policy-rc.d`

### Expected behavior

No such message and service restarted.

### Actual behavior

During upgrades:

> /usr/sbin/policy-rc.d returned 101, not running 'restart qubes-whonix-network.service qubes-whonix-postinit.service qubes-whonix-qubes-updates-proxy-enable-maybe.service qubes-whonix-redirect-9050.service qubes-whonix-redirect-9050.socket qubes-whonix-remote-support.service qubes-whonix-sysinit.service qubes-whonix-torified-updates-proxy-check.service'

### Additional information

    cat /usr/sbin/policy-rc.d

> exit 101

Does Qubes builder or a Qubes package create file `/usr/sbin/policy-rc.d`? 

Whonix doesn't create file `/usr/sbin/policy-rc.d` as this isn't needed and I highly discourage it.

A Qubes user reported message `/usr/sbin/policy-rc.d returned 101, not running 'start qubes-qrexec-agent.service'
` here: https://forum.qubes-os.org/t/4-1beta-upgrade-stage1-errors/5227/4

Therefore this is most likely a general Qubes issue. Not caused by Whonix.

Affects Qubes-Whonix: yes

### Related tickets

* https://github.com/QubesOS/qubes-issues/issues/2238

**Comment by marmarek** [comment]
> File `/usr/sbin/policy-rc.d` file exists and prevents daemons from (re-)starting during package upgrades.

It is meant to exist only during template build, and should be removed at the end. I just checked official debian-12 template and indeed the file is left there, so something went wrong during the build.

**Comment by unman** [comment]
On Mon, Jul 03, 2023 at 05:59:40AM -0700, Marek Marczykowski-Górecki wrote:
> > File `/usr/sbin/policy-rc.d` file exists and prevents daemons from (re-)starting during package upgrades.
> 
> It is meant to exist only during template build, and should be removed at the end. I just checked official debian-12 template and indeed the file is left there, so something went wrong during the build.
> 
It was not present in the 20290423 testing template for 4.1

**Comment by marmarek** [comment]
The PR above seems to fix it for builderv2.

**Comment by adrelanos** [comment]
Will this be applied when building new templates?
(Planning to build new Qubes-Whonix templates today.)

Should this be fixed in already uploaded templates?

**Comment by marmarek** [comment]
New templates will have the fix included. Existing templates will not be fixed.
