### ISSUE TITLE
Recovering from “Application is missing in template!” is not intuitive or trivial

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#8318]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

R4.2-rc1 but R4.1 is also impacted

### Brief summary

If I get “Application missing in template!”, getting rid of it is difficult.

### Steps to reproduce

Try to fix “Application missing in template!”.

### Expected behavior

It is easy.

### Actual behavior

It is hard.  One must move it the items from “selected” to “available”, press “Apply”, and then force a refresh of available applications.  This is also needed to recover from #8317.

**Comment by marmarek** [comment]
> ### Expected behavior
> 
> It is easy.

What exactly would you expect? I don't think removing the entry, the same way as you remove any other entry on the "selected" list is "hard". Especially, I don't think the "force refresh" step is needed (there might be a bug like this in R4.1 times, though).

**Comment by DemiMarie** [comment]
> > ### Expected behavior
> > It is easy.
> 
> What exactly would you expect? I don't think removing the entry, the same way as you remove any other entry on the "selected" list is "hard". Especially, I don't think the "force refresh" step is needed (there might be a bug like this in R4.1 times, though).

My expectation is that if I move the entry from the “selected” list, it would disappear (and not come back).  That is indeed what happens, so closing.
