### ISSUE TITLE
Add apparmor package to debian-minimal (since its in the official debian)

### ISSUE THREAD

**Issue by TNTBOMBOM** [QubesOS/qubes-issues#8331]
### Qubes OS release

4.2

### Brief summary

apparmor should be added and activated by default, as this is the official behavior of debian since debian 10

https://wiki.debian.org/AppArmor/Progress#Enabling_AppArmor_by_default

### Actual behavior

![apparmornotthere cleaned](https://github.com/QubesOS/qubes-issues/assets/11895339/3f05f4e0-a124-4f2d-9e4d-58690e9ade14)

### Note

I dont expect minimal to be less secure than what the original distro is offering.

**Comment by marmarek** [comment]
That's not the purpose of [minimal template](https://www.qubes-os.org/doc/templates/minimal/). It should be as minimal as possible, excluding any packages not vital for it starting.

If you want Debian template that is close to the upstream one, use non-minimal template.

**Comment by andrewdavidwong** [comment]
Closed as "not a bug" (the reported behavior is not a bug and is already working as intended). If anyone believes this is a mistake, please leave a comment, and we'll be happy to take another look. Thank you.
