### ISSUE TITLE
IBus Notification: Keymap changes does not work in plasma wayland at present

### ISSUE THREAD

**Issue by TNTBOMBOM** [QubesOS/qubes-issues#8336]
### Qubes OS release

4.2

### Brief summary

A sudden notification i got out of nowhere saying: 

`IBus Notification: Keymap changes does not work in plasma wayland at present. Please use systemsettings5 instead.`

![ibusissue](https://github.com/QubesOS/qubes-issues/assets/11895339/46829e3c-401a-4028-9cbe-70ed57eb4821)

### Steps to reproduce

Sadly i couldnt reproduce this nor i know what caused it.

### Notes

My qubes is based on xfce, didnt use or install anything related to KDE plasma.

**Comment by TNTBOMBOM** [comment]
closing as duplicate of #8286

**Comment by andrewdavidwong** [comment]
This appears to be a [duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If anyone believes this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Comment by wlorbetski** [comment]
i am having this same issue also

**Comment by andrewdavidwong** [comment]
@wlorbetski: This issue was closed as a duplicate of another issue. Unless you have reason to believe that it is not really a duplicate, please comment on the other issue instead.
