### ISSUE TITLE
Open Collective widgets appear to be cut off on Qubes website

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#8338]
The Qubes OS Project receives donations through an entity called Open Collective (among other donation methods). Open Collective provides us with this JavaScript widget, which shows who has donated to our project via Open Collective:

https://opencollective.com/qubes-os/banner.js

We have chosen to embed this widget on the following pages of our website:

- https://www.qubes-os.org/donate/#thank-you
- https://www.qubes-os.org/partners/#our-supporters 

Until sometime recently, the widget looked normal. However, now it appears to be cut off:

![screenshot-www qubes-os org-2023 07 08-04_27_47](https://github.com/QubesOS/qubes-issues/assets/10417133/c2441b09-9c17-43c3-9e9d-a3493ed8f576)

- I don't have a screenshot of how it's supposed to look, sorry.
- I don't know when this started happening. I just noticed it for the first time now.
- I checked with Google Chrome, but I'm not sure if it appears differently in other browsers.
- I don't know whether this is a problem on our end or Open Collective's end. As far as I know, nothing has changed on our end that would affect this widget, but I could be wrong, as I don't know much about JavaScript.

**Comment by alimirjamali** [comment]
@andrewdavidwong Is this still broken? I just checked with Chrome and Firefox. Both look fine.

![oc](https://github.com/user-attachments/assets/d883c394-1168-44e0-8a22-635a922efe38)
