### ISSUE TITLE
Linux 6.4.2 crashes sys-net on NovaCustom NV41 with Intel Killer Wi-Fi

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#8339]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

R4.2 (4.1 likely too)

### Brief summary

Booting sys-net with Linux 6.4.2 results in it being killed by the hypervisor.

### Steps to reproduce

1. Install 6.4.2 kernel (https://github.com/QubesOS/qubes-linux-kernel/pull/791)
2. Switch sys-net to it.

### Expected behavior

sys-net boots and works normally.

### Actual behavior

![2023-07-09-023343_1024x768_scrot](https://github.com/QubesOS/qubes-issues/assets/726704/ef516c82-728f-40d3-a7ad-d100d3966854)

It is very likely (faulting address matches) issue described in https://lore.kernel.org/xen-devel/3a8f54cf631e0342b144935950c853d1884a7eac.1680752649.git-series.marmarek@invisiblethingslab.com/. This patch should also fix it, but:
 - there is some more work needed for it to be accepted upstream
 - it's rather invasive change and may not be suitable for R4.1 backport

Anyway, since the problem started to happen with 6.4 kernel, it is some Linux change that made it a problem also when MSI-X is not supported. Which is suspicious, since all registers on this page are related MSI-X.

Looking at Linux commits between 6.3 and 6.4, this likely is the cause: https://git.kernel.org/linus/70582b826365d27b0be2c7cd0ebe85d01b438d2b

**Comment by marmarek** [comment]
FYI @wessel-novacustom (no action needed from you, just letting you know about issue detected early by automatic tests)

**Comment by wessel-novacustom** [comment]
@marmarek Thanks for the update
