### ISSUE TITLE
Notification popup missing/undefined icon

### ISSUE THREAD

**Issue by TNTBOMBOM** [QubesOS/qubes-issues#8341]
### Qubes OS release

4.2

### Brief summary

When i get a notification from some websites like youtube, i get a missing icon (for x/close i think)

### Steps to reproduce

Get a notification from youtube

### Expected behavior

Nice looking icon representing what it should look like

### Actual behavior

(Browser tested is chrome on debian)

![wrongcharacters cleaned](https://github.com/QubesOS/qubes-issues/assets/11895339/3e2888b5-23b4-4471-b105-cebf48425e92)

**Comment by andrewdavidwong** [comment]
Is this an in-browser notification? If so, could it be that you're missing a package in the template on which this qube is based?

**Comment by TNTBOMBOM** [comment]
ah so this is template (internal) issue not qubes/dom0 xfce notification issue? 

If sure this is only happening due to template issue feel free to close this ticket as it can be caused by flatpak or so which need investigation unrelated to qubes.

**Comment by andrewdavidwong** [comment]
> ah so this is template (internal) issue not qubes/dom0 xfce notification issue?

Well, I don't know, because I don't know where the notification is or what kind of notification it is, but that would be my guess. The screenshot doesn't help me to identify it, as I can't tell what kind of window it appears in. Does the notification have a colored border corresponding to that qube's color label?

**Comment by andrewdavidwong** [comment]
> If sure this is only happening due to template issue feel free to close this ticket as it can be caused by flatpak or so which need investigation unrelated to qubes.

The "Activate" and "Settings" buttons strongly suggest that it isn't a dom0 notification, so yeah, I think it's safe to close this.

Closing as "not our bug" (the Qubes OS Project does not develop the software that is causing this bug). If anyone believes this resolution is a mistake, please leave a comment, and we'll be happy to take another look. Thank you.

Related FAQ: [Why don’t you fix upstream bugs that affect Qubes OS?](https://www.qubes-os.org/faq/#why-dont-you-fix-upstream-bugs-that-affect-qubes-os)
