### ISSUE TITLE
Qubes-Whonix: enable zsh by default

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#8343]
Non-Qubes-Whonix uses `zsh` by default for new builds since Whonix 17.
([ticket](https://forums.whonix.org/t/change-default-shell-from-bash-to-zsh-by-default/14792/125))

This currently does not work for Qubes-Whonix builds.

Enabling zsh by default is implemented in the `dist-base-files` package [debian/dist-base-files.postinst](https://github.com/Kicksecure/dist-base-files/blob/master/debian/dist-base-files.postinst) during user creation "`adduser`".

However, by the time the `dist-base-files` package is being installed, user `user` was already created by Qubes builder (v2). Therefore user `user` with the new default shell cannot be created. This didn't matter in the past but now that the default shell was changed in Whonix, this matters.

`chsh` (change shell) cannot be used from Debian maintainer scripts either. (apt-get permission denied)

How could this be implemented in the Qubes build process?

- `qubes-template-whonix` could set variable `USER_OPTS` (which seems already used by `qubes-builder-debian`). Don't know if that would work already at this point?
- `qubes-template-whonix` could set variable that requests Qubes builder to skip user creation, if that is even possible and not break too much?

To preview how zsh runs in Qubes-Whonix in the current testing images of Qubes-Whonix 17 simply run `zsh`.

**Comment by marmarek** [comment]
> `chsh` (change shell) cannot be used from Debian maintainer scripts either. (apt-get permission denied)

Can you give more details why? maintainer scripts are running as root, so it should be able to use `chsh` to change the shell.

**Comment by adrelanos** [comment]
While trying to reproduce this to show the exact error message, I failed 
to reproduce it, which is good.

Maybe Debian fixed this in Debian bookworm.

I'll retest this method in the next image build. I hope it works since 
that would be a simple solution.

**Comment by adrelanos** [comment]
Didn't happen for upgrades. No such issue anymore.

(But there are other zsh integration related issues which are unrelated to this.)

**Comment by adrelanos** [comment]
The issue I originally described is actually a non-issue.

However, the goal of `Qubes-Whonix: enable zsh by default` isn't accomplished yet either.

The issue of using `chsh` is that this happens for new builds as well as for existing builds, speak users that upgrade. The the latter, this causes confusion. Due to non-existence of file [`/etc/skel/.zshrc`](https://github.com/Kicksecure/desktop-config-dist/blob/master/etc/skel/.zshrc) (from `/etc/skel`), the zsh new user module pops up.

https://forums.whonix.org/t/change-default-shell-from-bash-to-zsh-by-default/14792/37

Potential solutions:

* A) Run `chsh` only during build of Qubes-Whonix. Can I detect from inside a Debian maintainer postinst script that the script is currently running during a Qubes builder v2 build? I guess that would be the best.
* B) A systemd unit that creates an empty `/home/user/.zshrc` early enough at boot. Not a great solution. Not compatible with multi-user setups. Not a very clean solution. Not great to write into user's home folders.

**Comment by andrewdavidwong** [comment]
I'm having trouble understanding this issue. It seems to be phrased in terms of an enhancement request ("Qubes-Whonix: enable zsh by default" -- something that would be an improvement over the status quo), but it was filed as a bug report. If it's a bug, then the issue should be framed in terms of the problem, not what we assume the correct solution to that problem is (because sometimes we're wrong about the optimal solution or a better solution is possible that we didn't consider at first). After reading through everything in this issue, I'm still not sure which way it should go, as I can't seem to grasp what the actual problem is that we're trying to solve. Is it just this part?

> Due to non-existence of file [`/etc/skel/.zshrc`](https://github.com/Kicksecure/desktop-config-dist/blob/master/etc/skel/.zshrc) (from `/etc/skel`), the zsh new user module pops up.

**Comment by DemiMarie** [comment]
@adrelanos I strongly suspect `/etc/skel/.zshrc` not existing is by design: lots of zsh’s options are very much intended to be customized by the end-user, and zsh with an empty `.zshrc` does not have many of its famous usability features enabled.

**Comment by marmarek** [comment]
> * A) Run `chsh` only during build of Qubes-Whonix. Can I detect from inside a Debian maintainer postinst script that the script is currently running during a Qubes builder v2 build? I guess that would be the best.

Is it installed late enough that qubes packages are installed already? If so, you can use the standard marker file (`/usr/share/qubes/marker-vm`).

**Comment by adrelanos** [comment]
> @adrelanos I strongly suspect `/etc/skel/.zshrc` not existing is by design: lots of zsh’s options are very much intended to be customized by the end-user, and zsh with an empty `.zshrc` does not have many of its famous usability features enabled.

A default configuration has been developed. References:

* configuration files: https://github.com/Kicksecure/desktop-config-dist/tree/master/etc/zsh
* discussion: https://forums.whonix.org/t/change-default-shell-from-bash-to-zsh-by-default/14792

**Comment by adrelanos** [comment]
> > * A) Run `chsh` only during build of Qubes-Whonix. Can I detect from inside a Debian maintainer postinst script that the script is currently running during a Qubes builder v2 build? I guess that would be the best.
> 
> Is it installed late enough that qubes packages are installed already? If so, you can use the standard marker file (`/usr/share/qubes/marker-vm`).

I am aware of `/usr/share/qubes/marker-vm` and using it sometimes. This file is about Qubes yes/no.

However, here my question is a a bit different. It has one more detail.

Am I inside the Qubes Template _build process_ yes/no? Is there an environment variable for this?

In theory, `ischroot` might be an option but that could catch too many unwanted, unforeseeable cases.

I checked qubes-builder-v2 and qubes-template-debian source code and didn't find any suitable environment variable being `export`ed. I'll send a pull request to suggest this.

**Comment by adrelanos** [comment]
https://github.com/QubesOS/qubes-builderv2/pull/59

**Comment by marmarek** [comment]
> Am I inside the Qubes Template _build process_ yes/no? Is there an environment variable for this?

TBH, I'm not sure if that's a good idea in principle. This means fresh build will behave differently than updating template installed earlier. This requires more steps on update, surprising behaviors and also makes testing harder (because you can arrive at the same version but have different "default" configuration).

Can't you create some flag file to not do chsh again? For example `/var/lib/whonix/chsh-done` or similar.

As for the missing config, that would affect also users having Whonix qubes created already and switching them from Whonix template 16 to 17. Unfortunately, I don't see any better option than some startup script that copies the config into user home on boot (again, likely with a flag file, in user home this time, to not copy it again; or simply don't override it if already exists).

**Comment by adrelanos** [comment]
> > Am I inside the Qubes Template _build process_ yes/no? Is there an environment variable for this?
> 
> TBH, I'm not sure if that's a good idea in principle. This means fresh build will behave differently than updating template installed earlier. This requires more steps on update, surprising behaviors and also makes testing harder (because you can arrive at the same version but have different "default" configuration).

Good point.

> Can't you create some flag file to not do chsh again? For example `/var/lib/whonix/chsh-done` or similar.

(This wouldn't work for the case of "make this only for new builds, don't do it for existing builds". But as you mentioned above, that is to be avoided anyhow.

The "do this only once" code already exists and is functional. So either way the migration to change to zsh by default will only be done once and from there, user customization is respected.)

> As for the missing config, that would affect also users having Whonix qubes created already and switching them from Whonix template 16 to 17.

> Unfortunately, I don't see any better option than some startup script that copies the config into user home on boot (again, likely with a flag file, in user home this time, to not copy it again; or simply don't override it if already exists).

Alright. I will work on this solution.

Thank you for your feedback!

**Comment by adrelanos** [comment]
Fixed.

https://forums.whonix.org/t/change-default-shell-from-bash-to-zsh-by-default/14792/132
