### ISSUE TITLE
contrib-repo not available for fedora 38

### ISSUE THREAD

**Issue by rwiesbach** [QubesOS/qubes-issues#8353]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
4.1.x

### Brief summary
https://contrib.qubes-os.org/yum/r4.1/current/vm/
does not host a fc38 directory, so contrib packages like qubes-tunnel are not available for fedora 38

### Steps to reproduce
sudo dnf install qubes-repo-contrib
sudo dnf install qubes-tunnel
(or with --enablerepo=qubes-contrib-vm-r4.1-current-testing)

### Expected behavior
qubes-tunnel is installed 

### Actual behavior
Errors during downloading metadata for repository 'qubes-contrib-vm-r4.1-current':
  - Status code: 404 for https://contrib.qubes-os.org/yum/r4.1/current/vm/fc38/repodata/repomd.xml (IP: 127.0.0.1)
Error: Failed to download metadata for repo 'qubes-contrib-vm-r4.1-current': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
Qubes OS Contrib Repository for VM (updates-tes 9.9 kB/s | 3.0 kB     00:00    
Qubes OS Contrib Repository for VM (updates-tes 4.3 kB/s | 3.2 kB     00:00    
Ignoring repositories: qubes-contrib-vm-r4.1-current
No match for argument: qubes-tunnel
Error: Unable to find a match: qubes-tunnel

**Comment by andrewdavidwong** [comment]
Also reported on the forum:

https://forum.qubes-os.org/t/qubes-contrib-repo-need-to-be-updated-for-fedora-38/19895/

**Comment by fepitre** [comment]
I'm aware of that, I'll manage that in the next days while I also setup contrib repo for 4.2.

Lun 17 juil 2023, à 19:34, Andrew David Wong a écrit :

**Comment by fepitre** [comment]
Contrib repos are already available for current-testing. I've pushed stable components to current and repo is now available.
