### ISSUE TITLE
Black screen after start since dom0 update (now kernel 6.1.35)

### ISSUE THREAD

**Issue by Singermichael** [QubesOS/qubes-issues#8354]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

Qubes 4.1.2, Xen 4.14.5, Kernel 5.15.103-1. Qubes with sys-gui extension. Intel(R) Core(TM) i7-4810MQ CPU @ 2.80GHz.

### Brief summary

I made the update for dom0 and the templates on July 11. After the reboot the bootloader appears. Then the screen goes dark briefly, then shuts down for a moment. So far quite normal. But the problem is, the screen now remains permanently off and the option to enter the hard disk password does not appear.

### Steps to reproduce

Start the computer or select Xen 4.14.5 with Linux 6.1.35 in the boot loader - then you have the problem. If you select Xen 4.14.5 with Linux 5.15.103 instead, the system boots normally.

### Expected behavior

System starts normally.

**Comment by rznde** [comment]
I noticed that you mentioned that you're using sys-gui. I was able to reproduce the issue using sys-gui-gpu on similar hardware. I found a workaround by modifying the sys-gui-gpu kernel options. I removed "nopat" and "iommu=soft."

`qvm-prefs sys-gui-gpu kernelopts 'swiotlb=8192 root=/dev/mapper/dmroot ro console=hvc0 xen_scrub_pages=0'`

After making this change, I successfully booted "sys-gui-gpu" with the 6.x.x kernel.

**Comment by Singermichael** [comment]
Thank you, Gustavo. But in the dom0 terminal I get the response: "No such domain." I never set up a sys-gui domain manually. I remember that I clicked a checkbox for a sys-gui extension when I installed Qubes 4.1 with the graphical installer.
