### ISSUE TITLE
Add a CLI option to updater GUI to immediately start updating selected VMs

### ISSUE THREAD

**Issue by marmarta** [QubesOS/qubes-issues#8355]
### The problem you're addressing (if any)

There are multiple ways we do updates in different GUI tools: updater widget runs `qubes-update-gui`, while manager uses either `qubes-dom0-update` or `qubes.InstallUpdatesGUI` service. It would be much easier to have a simple unified way to do this.

### The solution you'd like

it would be good to have a command-line option to run updates for selected qubes in the `qubes-update-gui`, e.g. `--qube` that accepts one or more qube names. Updater started with this option should start updating selected qubes immediately.

### The value to a user, and who that user might be

Improved error reporting and more consistent system behavior.

references https://github.com/QubesOS/qubes-issues/issues/8117

**Comment by andrewdavidwong** [comment]
> There are multiple ways we do updates in different GUI tools: updater widget runs `qubes-update-gui`, while manager uses either `qubes-dom0-update` or `qubes.InstallUpdatesGUI` service. It would be much easier to have a simple unified way to do this.

That's #6635, isn't it?



> it would be good to have a command-line option to run updates for selected qubes in the `qubes-update-gui`, e.g. `--qube` that accepts one or more qube names. Updater started with this option should start updating selected qubes immediately.

Hm, I don't see how this addresses the problem. Introducing a new command-line tool option doesn't affect users who update via either of the GUI methods.

Maybe the unstated part is that, once this new command-line option is implemented, you plan to use it behind the scenes in order to implement #6635?

Or is there something else I'm missing?

**Comment by andrewdavidwong** [comment]
> Add a CLI option to updater GUI [...]

I could be wrong, but this sounds like an oxymoron to me, because GUIs don't have CLI options.

**Comment by marmarta** [comment]
> Oh wait, I think I'm starting to get it now. It's a CLI option for starting the GUI and running it in a certain mode.

yeah, exactly - it would be nice for starting updates from e.g. qube manager
