### ISSUE TITLE
Application windows do not remain in the foreground and on all workspaces 

### ISSUE THREAD

**Issue by ichabod-c** [QubesOS/qubes-issues#8357]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

Qubes release 4.1.2

### Brief summary

When one selects the mode: "Always on top" or "Always on Visible Workspace," on the window of an application (e.g., the small Skype window), it changes mode immediately but after one or two workspace changes, clicking on some application, it returns as before. 

### Steps to reproduce

Read above

### Expected behavior

Once the modes described above are selected, application windows should remain fixed in the foreground or be present on all workspaces until the "Same as Other Windows" or "Only Visible on This Workspace" options are selected.

### Actual behavior

Read Brief summary

**Comment by meithecatte** [comment]
Can't reproduce with a terminal window in a VM based on `debian-11`. Is the Skype window the only one you can reproduce this with, or does our setup differ somehow?

**Comment by ichabod-c** [comment]
> Can't reproduce with a terminal window in a VM based on `debian-11`. Is the Skype window the only one you can reproduce this with, or does our setup differ somehow?

I did not change any settings. I simply installed Skype on fedora-38. 
However, I encountered the problem initially with Skype. For the other apps ( e.g. terminal and brave) it seems to work correctly.
