### ISSUE TITLE
Network connection via lan cable does not work for network card "QualcommAtherosKillerE2400"

### ISSUE THREAD

**Issue by ichabod-c** [QubesOS/qubes-issues#8358]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

Qubes release 4.1.2

### Brief summary

The network card is displayed correctly by sys-net, but cannot connect to the Internet.

![Screenshot_2023-07-14_18-10-09](https://github.com/QubesOS/qubes-issues/assets/38102919/21a1328c-8b98-4f0b-98c3-0c5e5ab20bf1)

### Steps to reproduce

Try connecting to the Internet with this network card, or this hardware (see above).

### Expected behavior

Connect to the internet by default via network cable.

### Actual behavior

Read Brief summary.

**Comment by zpc0** [comment]
Possibily related?
#7052

**Comment by ichabod-c** [comment]
> Possibily related? #7052
Definitely yes.

**Comment by andrewdavidwong** [comment]
This appears to have been closed as a [duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If anyone believes this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.
