### ISSUE TITLE
Include qubes (or their "Settings" entries) with no app shortcuts in app menu search results

### ISSUE THREAD

**Issue by TNTBOMBOM** [QubesOS/qubes-issues#8359]
### Qubes OS release

4.2

### Steps to reproduce

- Move out any application from app menu for your template
- Go to Qubes application menu 
- Search for the name of the template

### Expected behavior

Do not hide or remove the template entirely, but make it appear as if you are opening the Qubes app menu and manually navigating to a template without any added applications (displaying the template name and settings).

![searchdoesntshow2](https://github.com/QubesOS/qubes-issues/assets/11895339/cc277470-cf70-452e-8699-6f830b758230)

### Actual behavior

No template will show up:

![searchdoesntshow](https://github.com/QubesOS/qubes-issues/assets/11895339/45f34c5e-4ffc-4779-a7b3-fa648cc4a2ef)

**Comment by marmarek** [comment]
The search is about applications specifically, not any objects. But this sounds like a useful feature request. Alternatively, similar "fix" would be to considering "settings" entry in the search results too.

**Comment by deeplow** [comment]
I just came across this issue. When having lots of qubes, search is often the only practical way look a qube up. And if we want to go to it's settings we can't go through search.

@marmarta they may be worth adding to the menu revision project.

**Comment by andrewdavidwong** [comment]
> When having lots of qubes, search is often the only practical way look a qube up.

You can search in the Qube Manager rather than the app menu.

**Comment by deeplow** [comment]
> You can search in the Qube Manager rather than the app menu, and that does allow you to easily open the settings of any qube returned in the search results.

That's true, but at the same time she settings are needed to access relatively frequently. And my impression is that the Qube Manager is only for more powerful / bulk actions. At least that's how I use (I rarely open it).

Maybe that's just my usage. Feel free to close if the impression is that this is a niche need (which I don't think it is).

**Comment by deeplow** [comment]
One way to tackle this could be to keep the same right-side panel structure (with the settings and network state).

![wnix](https://github.com/QubesOS/qubes-issues/assets/47065258/cecf7104-f734-4fe6-8229-5ed719cbe61e)

 This way, the first result (**Any Qube**) would have normal results (without the settings), but once the user hovered over the specific qube they'd see the settings.

**Comment by andrewdavidwong** [comment]
> That's true, but at the same time she settings are needed to access relatively frequently.

Well, that's a matter of personal habits. I wouldn't be surprised if many users don't have to access qube settings frequently once they initially set things up the way they need.

> And my impression is that the Qube Manager is only for more powerful / bulk actions. At least that's how I use (I rarely open it).

That's also a matter of personal habits. Personally, I always have it open, like a dashboard.

Personally, I would rather see the feature requested in this issue be an **option** that can be turned on or off, maybe something like `[x] Show qubes without shortcuts in the app menu`. I would hate for my menu to be cluttered up with every qube in the system with no way to opt out. In general, there really need to be ways *not* to have to see every single qube in the system all the time in every interface. Many qubes exist only as part of the internal machinery required to make the system work. Always having them mixed in with the user's own qubes makes it frustrating to find and organize one's own apps and data (related: https://github.com/QubesOS/qubes-issues/issues/8663).

**Comment by marmarta** [comment]
So, my current idea is to add life cycle buttons and settings to search, but, to avoid inconsistencies and weird keyboard nav behavior, to move settings to the bottom of the app list (both in search and in normal view), to be grouped with lifecycle buttons.
