### ISSUE TITLE
Non-default option to sort all running qubes to the top of the app menu

### ISSUE THREAD

**Issue by TNTBOMBOM** [QubesOS/qubes-issues#8360]
### The problem you're addressing (if any)

Qubes, by design, will have many Qubes (VMs). Therefore, it would be nice to see only the active ones on top. (They are nicely highlighted in bold However, scrolling down to find the bold ones can be time-consuming).

### The solution you'd like

![letopenedappvmtop](https://github.com/QubesOS/qubes-issues/assets/11895339/10102256-b127-4bf3-99a2-151f9fb47fff)

### The value to a user, and who that user might be

Enhancing user usability.

**Comment by marmarek** [comment]
Related to https://github.com/QubesOS/qubes-issues/issues/7768

I don't think it's a good idea to have this mode by default, it breaks sorting - you'd need to check two areas when looking for some specific name. But it sounds like a useful optional feature.

**Comment by TNTBOMBOM** [comment]
> it breaks sorting

To be honest, I don't know which mechanism is used to sort the VMs in the Qubes Application Menu. If its alphabetical order, you can see the image with the letter "I" (i2p) at the top, whereas the letter "D" is in the middle (bottom in the image, not in reality). If its sorting from old to new or new to old, that's not the case either. and, if its active and inactive status also not...

Nevertheless i hope this feature can help users in easy sorting to their VMs when they open the menu (as plus to the search functionality)

**Comment by andrewdavidwong** [comment]
I wonder if it's doing case-sensitive sorting or something.

**Comment by marmarta** [comment]
oh, yeah, it was supposed to be alphabetical. I might have forgotten about capital letters being a thing....

**Comment by marmarta** [comment]
but generally, yeah, I would like at some point to implement more filtering and sorting options. It is a good idea to have this possibility.
