### ISSUE TITLE
Raw disk backup of Qubes EFI is unbootable

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#8363]
### Qubes OS release

R4.1 and R4.2

### Brief summary

When making a raw disk backup from a Qubes installed to an internal hard drive to an external hard drive, the external hard drive is unbootable.

raw disk backup means a backup using `dd` or 1 to 1 exact copy.

### Steps to reproduce

1. install Qubes normally on a computer that only support EFI booting on the internal harddrive
2. reboot
3. brief test that Qubes is working normally (yes)
4. shutdown Qubes
5. boot from an external drive, boot a live DVD or live USB such as Debian Live
6. perform a raw disk backup from the internal disk to the external disk
7. unplug that disk and try to boot from it in a different computer (or the same Qubes computer)

([example instructions for raw disk backups](https://www.kicksecure.com/wiki/Raw_Disk_Backup))

### Expected behavior

The raw disk backup of Qubes is bootable.

### Actual behavior

The raw disk backup of Qubes is unbootable.

### Additional information

According to my research that might be because of missing entries in the EFI firmware's NVRAM which is stored on the motherboard. Unfortunately, the EFI boot process doesn't seem by default to be self-contained on 1 harddrive but require extra settings stored outside harddrives on the motherboard (EFI NVRAM).

Using `grub2-install` with options `--removable` / `--force-extra-removable` during Qubes installation might help?

> [--removable](https://manpages.debian.org/bookworm/grub2-common/grub-install.8.en.html#removable)
> the installation device is removable. This option is only available on EFI.

> [--force-extra-removable](https://manpages.debian.org/bookworm/grub2-common/grub-install.8.en.html#force~2)
> force installation to the removable media path also. This option is only available on EFI.

Qubes does not have good support for multiboot support anyhow:

* https://github.com/QubesOS/qubes-issues/issues/8351
* https://www.qubes-os.org/faq/#can-i-install-qubes-os-together-with-other-operating-system-dual-bootmulti-boot
* It's "patches welcome". (And that's okay.)

This ticket is not a feature request to improve multiboot support. Why do I mention this? Because otherwise, when considering options `--removable` / `--force-extra-removable` one *might* argue "but that breaks mutliboot support". I would argue that being able to boot a raw disk backup of Qubes is more important than mutliboot support.

[Why do I like full raw disk backups? See this link.](https://forum.qubes-os.org/t/how-do-you-organize-your-backups/3986/16?u=adrelanos)

Manually updating the NVRAM can be challenging:

* It's vendor dependent because of many different EFI BIOS versions.
* Some BIOS don't even have such an option.
* Might require booting into an operating system installed on USB and running console commands to fix it.
* Difficult, impossible for far most users to do or even to find instructions for it.

Qubes with legacy BIOS booting as far as I remember didn't have this issue. However, never notebooks sometimes (or often, dunno) don't even support legacy BIOS booting anymore. Therefore "use legacy BIOS booting" is a non-solution. Also not a good long term solution in either case because of Qubes planned Secure Boot support.

This bug might also make Qubes "non-portable". Meaning, Qubes installed to an external drive such as a USB SSD might be bootable on the computer where it was installed but unbootable when attempting to boot the same Qubes USB SSD on another computer. I didn't test this very part mentioned in this very chapter. Anaconda by Fedora might be using `grub2-install` with options `--removable` / `--force-extra-removable` already when installing to external devices (USB) instead of internal harddrive.

Where is the Qubes code which defines bootloader / grub2 / EFI installation? Or is this currently all done by upstream's Anaconda?

**Comment by adrelanos** [comment]
EFI fallback bootloader file `/boot/efi/EFI/BOOT/bootx64.efi` does not exist on Qubes.

* https://superuser.com/questions/1756758/what-does-grub-installs-removable-flag-do
* https://www.rodsbooks.com/efi-bootloaders/principles.html

**Comment by andrewdavidwong** [comment]
Is this a Qubes-specific bug, or is it just how most EFI OS installations work? Honest question; I have no idea. For example, if we tried the same steps with baremetal Fedora or Debian (or even Windows), would those boot from the external drive without a problem?

**Comment by adrelanos** [comment]
I am not sure. And if it was the case, I would argue it doesn't matter for a few reasons:

* There are a ton of already reported, long standing open issues related to Qubes Backup (issues creating the backup, issues restoring the backup, slow backup creating, unnoticed missing VMs, backup horror stories).
* Qubes dom0 updates have a history of breaking networking and/or booting. Therefore I consider these risky.
* For these reasons, Qubes needs this feature more than let's say Debian stable which can be easily backed up with reliable standard tools and doesn't break after upgrades.
* Qubes can do better than others.

A raw disk backup can be fast, reliable and if easily bootable, even easily testable.

In a a lucky, easy case, this issue might be fixable by appending `--removable` in a source code file at the right place.

Qubes used to have a Live USB in the past. Dunno if that was bootable in different computers. Therefore there's a chance, Qubes developers already know how to implement this.

**Comment by adrelanos** [comment]
Another reason to implement this is to resolve many boot related issues.

A Google search for:

> "/boot/efi/EFI/BOOT/bootx64.efi" "Qubes"

Shows that many users have broken boot due to broken EFI firmware.

Quote Qubes troubleshooting 
[Boot device not recognized after installing](https://www.qubes-os.org/doc/uefi-troubleshooting/#boot-device-not-recognized-after-installing):

> `/boot/efi/EFI/BOOT/BOOTX64.efi`

Also considering the many users who give up at the point, don't post in forums or are unable to apply these troubleshooting steps.

This also... Not great...

> Some firmware will not recognize the default Qubes EFI configuration. As such, it will have to be manually edited to be bootable. This will need to be done after every kernel and Xen update to ensure you use the most recently installed versions.

Therefore Qubes by default switching to be the "fallback loader" would squash two issues at once. (Qubes boot issues and bootable raw backups)

**Comment by andrewdavidwong** [comment]
> * There are a ton of already reported, long standing open issues related to Qubes Backup (issues creating the backup, issues restoring the backup, slow backup creating, unnoticed missing VMs, backup horror stories).

Yes, but the Qubes backup system nonetheless works reliably for many users. I suspect that most of those bugs are due to some combination of (1) unsupported/faulty hardware, (2) non-standard installations (e.g., dom0 tinkering), and (3) user error. I'm not suggesting the bugs aren't important or shouldn't be fixed. Rather, I'm challenging the insinuation that raw disk backups *must* be supported because *no* decent Qubes backup option currently exists, which is false. Just because you don't like it or are having problems with it doesn't mean it's not working for others.

> Qubes dom0 updates have a history of breaking networking and/or booting. Therefore I consider these risky.

That has happened to me, too, but I think the last time it happened was many years ago, and it was more common back when I was on less well-supported hardware. Anyway, it's *always* a good idea to back up important data before significant system changes, and this isn't Qubes-specific.

> For these reasons, Qubes needs this feature more than let's say Debian stable which can be easily backed up with reliable standard tools and doesn't break after upgrades.

I'm not saying that supporting this wouldn't have value, but I think you're overstating the necessity of it (perhaps based on your own unique experience with Qubes).

> Qubes can do better than others.

True, but in that case it would be an enhancement rather than a bug.

> Qubes used to have a Live USB in the past. Dunno if that was bootable in different computers. Therefore there's a chance, Qubes developers already know how to implement this.

Yes, it was, and the reason the "live" version no longer exists, IIUC, is because you're supposed to be able to just install Qubes onto an external drive and achieve the same effect (or close enough, in practical terms, for common use cases like testing a Qubes OS installation on various machines). [I say "supposed to" because I haven't tried it myself recently.] So, *if* there is a regression in functionality here that was supposed to have been supported all along, then that might be a sufficient reason to consider this a bug. I leave that to @marmarek's judgment.

**Comment by adrelanos** [comment]
Based on https://forum.qubes-os.org/t/grubx64-efi-does-not-exist/18144/4

Copy files from /boot/efi/EFI/qubes/ to /boot/efi/EFI/BOOT/

```
sudo cp -r /boot/efi/EFI/qubes/* /boot/efi/EFI/BOOT/
```

Change filename grubx64.efi → BOOTX64.efi.

```
sudo mv /boot/efi/EFI/BOOT/grubx64.efi /boot/efi/EFI/BOOT/BOOTX64.efi
```

Change filename grub.cfg → BOOTX64.cfg

```
sudo mv /boot/efi/EFI/BOOT/grub.cfg /boot/efi/EFI/BOOT/BOOTX64.cfg
```

Works for me.

----

Based on that, the `/etc/kernel/postinst.d` hook folder could be utilized for automatically creating the EFI fallback bootloader file.


File:

`/etc/kernel/postinst.d/zzz-50-efi-default-bootloader`

Content:

```
#!/bin/sh

set -e

if [ "$1" = "configure" ]; then
    if [ -d "/boot/efi/EFI/qubes" ]; then
        cp -r /boot/efi/EFI/qubes/* /boot/efi/EFI/BOOT/
        mv /boot/efi/EFI/BOOT/grubx64.efi /boot/efi/EFI/BOOT/BOOTX64.efi
        mv /boot/efi/EFI/BOOT/grub.cfg /boot/efi/EFI/BOOT/BOOTX64.cfg
    fi
fi

exit 0
```

File naming reasoning:

On Debian unfortunately there is a imo badly named file `/etc/kernel/postinst.d/zz-update-grub`. For the script to run after `zz-update-grub`, it needs to start for example with `zzz`.

Status:

Not yet tested. Please let me know if this looks conceivable. Happy to test and send a pull request.

**Comment by marmarek** [comment]
Thanks to #7985 , grub.cfg on EFI partition no longer needs to be updated. So, it should be okay to do that just once, not on every kernel update. In fact, we may add/adjust a package with grub in this fallback path, so it will be as easy as just installing one more package.
