### ISSUE TITLE
qubes-vm-update exited with code 1, even though no apparent errors happened

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#8364]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

R4.2

### Brief summary

See title.

### Steps to reproduce

1. Build the tool from this PR: https://github.com/QubesOS/qubes-core-admin-linux/pull/134
2. `qubes-vm-update --max-concurrency=1 --templates --show-output`

### Expected behavior

When update succeed and exit with code 0

### Actual behavior

Update succeeded, but exit code was 1.
Full output (ignore salt output at beginning): https://openqa.qubes-os.org/tests/77504/file/update2-qubesctl-upgrade.log

**Comment by marmarek** [comment]
BTW, that run includes some extra plugins basically doing `apt-get install ...` / `dnf install ...`. But looking at the log, I don't think that's relevant for the issue reported here.

**Comment by marmarek** [comment]
PEBKAC

**Comment by jamke** [comment]
I think this issue should be removed from any milestone.
