### ISSUE TITLE
I3 random freeze with NVIDIA driver.

### ISSUE THREAD

**Issue by kiraoverflow** [QubesOS/qubes-issues#8370]
### Qubes OS version: 4.1.2
---

### Affected component(s): GUI
---

### Steps to reproduce the behavior:
The behavior cannot be reproduced because it happen randomly without regards of the apps runnings.

### Actual behavior:
Cursor cannot be moved, keyboard not responding, switching to an other tty is not possible.

General notes:
This issue happens on my integrated and discrete gpu (RTX 3060 laptop).
I know that because at first I though my gpu driver was the problem so i installed the NVIDIA driver and disabled nouveau, but the same freeze occurs after a few minutes.

Everything work fine on XFCE.

Anything else I could check when it happens again?

**Comment by andrewdavidwong** [comment]
> Qubes OS version: 6.1

Doesn't exist yet. :)

Guessing you meant 4.1?

**Comment by meithecatte** [comment]
Is this reproducible on i3 on a mainstream distro?

**Comment by kiraoverflow** [comment]
@andrewdavidwong yes my bad I meant 4.1.2.
@meithecatte Yes I had  Debian 11 running on the same laptop with i3 just fine.
