### ISSUE TITLE
`lxc`, `waydroid` not installable / `qubes-kernel-vm-support` has unnecessary dependency on `busybox`

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#8377]
### Qubes OS release

R4.2

### Brief summary

Attempting to install `lxc` or `waydroid` results in removal of of `qubes-kernel-vm-support`.

### Steps to reproduce

    sudo apt install lxc

Or.

Install `waydroid`.

### Expected behavior

No such issue.

### Actual behavior

https://forums.whonix.org/uploads/default/original/2X/1/17836bcc73cb49eb38f84da9dfea5a6915f23f7d.png

### References

* https://forums.whonix.org/t/note-installing-waydroid-will-remove-busybox-which-is-a-dep-to-kicksecure-dependencies-cli/16910
* https://www.kicksecure.com/wiki/Waydroid

### Additional information

Does  `qubes-kernel-vm-support` really need to depend on `busybox`?

Would `Depends: busybox | busybox-static` be an acceptable alternative?

**Comment by marmarek** [comment]
> Would `Depends: busybox | busybox-static` be an acceptable alternative?

I'm okay with this change, but I'm confused why it's necessary. `busybox-static` has `Provides: busybox`, so it shouldn't matter, no?

**Comment by marmarek** [comment]
In fact, the very similar issue was motivation of including that `Provides: busybox` - https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=375568.

**Comment by marmarek** [comment]
I just checked on my debian-12 system, the `Provides: busybox` does seem to work as expected:
```
user@d12test3:~$ dpkg -l qubes-kernel-vm-support
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                    Version        Architecture Description
+++-=======================-==============-============-=======================>
ii  qubes-kernel-vm-support 4.2.11+deb12u1 amd64        Qubes VM kernel and ini>
user@d12test3:~$ sudo apt install lxc
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  arch-test binutils binutils-common binutils-x86-64-linux-gnu busybox-static
  cloud-image-utils debootstrap distro-info fakechroot genisoimage libbinutils
  libctf-nobfd0 libctf0 libdistro-info-perl libdpkg-perl libfakechroot
  libfile-fcntllock-perl libgprofng0 liblxc-common liblxc1 libpam-cgfs
  libsubid4 lxc-templates lxcfs mmdebstrap rsync uidmap uuid-runtime wget
Suggested packages:
  binutils-doc mtools squid-deb-proxy-client ubuntu-archive-keyring shunit2
  wodim cdrkit-doc debian-keyring gcc | c-compiler bzr btrfs-progs python3-lxc
  qemu-user-static apt-transport-tor dpkg-dev genext2fs perl-doc qemu-user
  squashfs-tools-ng openssh-server python3-braceexpand
The following packages will be REMOVED:
  busybox
The following NEW packages will be installed:
  arch-test binutils binutils-common binutils-x86-64-linux-gnu busybox-static
  cloud-image-utils debootstrap distro-info fakechroot genisoimage libbinutils
  libctf-nobfd0 libctf0 libdistro-info-perl libdpkg-perl libfakechroot
  libfile-fcntllock-perl libgprofng0 liblxc-common liblxc1 libpam-cgfs
  libsubid4 lxc lxc-templates lxcfs mmdebstrap rsync uidmap uuid-runtime wget
0 upgraded, 30 newly installed, 1 to remove and 7 not upgraded.
Need to get 14.6 MB of archives.
After this operation, 77.8 MB of additional disk space will be used.
```
As you can see, only `busybox` is going to be removed, but not `qubes-kernel-vm-support`. Same happens on Whonix Workstation 17.

So, I cannot reproduce the issue.

**Comment by DemiMarie** [comment]
Is this issue specific to Debian oldstable/Whonix 16?

**Comment by adrelanos** [comment]
> Is this issue specific to Debian oldstable/Whonix 16?

Could be.

> So, I cannot reproduce the issue.

Confirmed for Whonix 17.

**Comment by marmarek** [comment]
Since Whonix 16 is EOL, this isn't relevant anymore.
