### ISSUE TITLE
Qube Manager: Enable the "restart qube" button for named disposables

### ISSUE THREAD

**Issue by TNTBOMBOM** [QubesOS/qubes-issues#8382]
### The problem, solution, and the value you're addressing

When there are template upgrades that the dispVMs are based on, users need to restart those running dispVMs (if they are in use) to inherit the upgrades. However, since manually turning off sys-usb will disable all USBs until it's turned on again (using internal pad), a useful feature would be if Qubes Manager supported a restart button for the dispVMs (currently it doesn't).

**Comment by bzillacodes** [comment]
A simple manual workaround is running something like $ `qvm-shutdown --wait sys-usb; sleep 10; qvm-start sys-usb` in dom0.

Running without the sleep seemed to fail re-initializing the USB pci device on my end.
