### ISSUE TITLE
Num lock state not restored after reboot

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#8383]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

4.1

### Brief summary

Enabling num lock and setting the option to remember this setting doesn't work. Num lock is off again after rebooting dom0.

### Steps to reproduce

1. Settings > Keyboard > Enable "Restore num lock state on startup".
2. Press the Num Lock key to enable it.
3. Reboot dom0.

### Expected behavior

Num lock is enabled.

### Actual behavior

Num lock is not enabled.

**Comment by alimirjamali** [comment]
> . Enabling num lock and setting the option to remember this setting doesn't work. Num lock is off again after rebooting dom0.

I just tried to reproduce this issue. The XFCE settings in dom0 is properly stored at `~/.config/xfce4/xfconf/xfce-perchannel-xml/keyboards.xml`. And it works well (but of course only after login back to XFCE).

Perhaps user wants this for LUKS unlock prior to login? Or for Display Manager login?
