### ISSUE TITLE
Libreoffice configured as default editor for text/plain

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#8385]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

R4.2, possibly R4.1 too

### Brief summary

Plain text files are opened in LibreOffice Writer, which is an overkill for the simple file format. Simpler editors are installed (depending on the template and its flavor - gnome-text-editor, gedit, mousepad), but they are not set as default for text/plain.

### Steps to reproduce

`xdg-mime query default text/plain`
Or simply open a .txt file from a file manager (or using xdg-open).

### Expected behavior

File opens in a simple text editor, default one for given distribution.
In gnome template flavor (the default one): gnome-text-editor or gedit
In xfce template flavor: mousepad

### Actual behavior

File opens in LibreOffice Writer.

### Additional context

This issue needs some explanation regarding https://www.qubes-os.org/faq/#what-is-qubes-attitude-toward-changing-guest-distros.

For Debian template, the consensus based on IRC discussion is that Debian does not define default applications for file types at all, and it is a long standing upstream issue. Even properly tracking it upstream is problematic, as the file configuring which applications open what (`/usr/share/applications/mimeapps.list`) doesn't exist, so the (hypothetical) issue cannot be assigned to any package (admittedly, this is rather lame excuse...). The result is that default application is chosen more or less at random (in practice depends on lexicographic sorting applications...) from the installed applications.

For Fedora template, the intended default is configured (mimeapps.list does exist and points at `org.gnome.gedit.desktop`), but for some reason, it isn't respected by `xdg-mime` in qubes template.

This is similar issue to https://github.com/QubesOS/qubes-issues/issues/4195 or https://github.com/QubesOS/qubes-issues/issues/3148

**Comment by h01ger** [comment]
someone else than me on irc:

foo.txt opens in gedit in my debian 11 at least
this happens if you haven't set XDG_CURRENT_DESKTOP=gnome

$ xdg-mime query default text/plain; (unset XDG_CURRENT_DESKTOP; xdg-mime query default text/plain)
org.gnome.gedit.desktop
libreoffice-writer.desktop
