### ISSUE TITLE
`sys-net` fails to start with `Got empty response from dom0`

### ISSUE THREAD

**Issue by gbeliako** [QubesOS/qubes-issues#8386]
### Qubes OS release
4.1.2
### Brief summary
restart VM from qubes manager. icon appears yellow, but further action such as shutdown or force kill does not work as ERROR: domain powered off.

using qvm-start vm:
"Got empty response from dom0. See journalctl for details."
[journalctl1.txt](https://github.com/QubesOS/qubes-issues/files/12229332/journalctl1.txt)
[journalctl.txt](https://github.com/QubesOS/qubes-issues/files/12229329/journalctl.txt)
[xen-console-log.txt](https://github.com/QubesOS/qubes-issues/files/12229271/xen-console-log.txt)

### Steps to reproduce
Not consistent, appears to be random.

**Comment by DemiMarie** [comment]
> It seems you have two netvms (sys-net and sys-net1) trying to use the same device. This won't work, you need to choose one.

“Got empty response from dom0” is a terrible error message.  Users should not need to go through dom0 logs to see what went wrong.

**Comment by gbeliako** [comment]
Yes, it's uninformative message. 
however, sys-net1 has nothing to do with it. The VM was created after sys-net failed to start. This has also happened with other PVH appvms without any hardware passthru.
