### ISSUE TITLE
fedora-38 template has gnome-control-center (GNOME Settings) that does not open.

### ISSUE THREAD

**Issue by jamke** [QubesOS/qubes-issues#8393]
### Qubes OS release
R4.1

### Brief summary
Default full fedora-38 template has gnome-control-center (GNOME Settings) that does not open.

### Steps to reproduce
* Install fedora-38 template.
* Create qube based on this template.
* Try to run `gnome-control-center` inside this qube or open "qubes: Settings" via Qubes OS menu for this qube.

### Expected behavior
GNOME Settings are shown that allow to change font size and etc. 
Both ways of opening settings work.

### Actual behavior
Nothing happens. Terminal has not output.

**Comment by TNTBOMBOM** [comment]
I think having anything related to gnome is just a bug, but i dont have surety about it.

**Comment by jamke** [comment]
> I think having anything related to gnome is just a bug, but i dont have surety about it.

Well, for KDE starting from ~ Fedora 36 it is possible to install almost everything without KDE desktop environment itself. I mean, even save/open dialogs can be changed to ones from KDE without installation of `plasma-desktop`. Before that was not a case, e.g. for Fedora 25-35.

So, maybe it is possible to avoid gnome stuff in the template that is full or gtk-based applications, too. But I do not know.
