### ISSUE TITLE
Qubes-4.2.0-RC1 invalid GPT partition table - not bootable on UEFI only system [regression from 4.1]

### ISSUE THREAD

**Issue by edwintorok** [QubesOS/qubes-issues#8395]
### Qubes OS release

4.2.0-RC1

### Brief summary

Tried the following, all of which resulted in unbootable USB installation media:
* verified the download checksum and signatures using instructions from Qubes website, all valid
* use dd from the Qubes install guide:`sudo dd if=Downloads/Qubes-R4.2.0-rc1-x86_64.iso of=/dev/disk/by-id/usb-SanDisk_Ultra_4C530000101218104270-0:0 bs=1048576 status=progress conv=fsync`
* `sudo wipefs -a /dev/disk/by-id/usb-SanDisk_Ultra_4C530000101218104270-0:0`, retry `dd`
* use FedoraMediaWriter instead of `dd`
* I verified that I have UEFI secureboot disabled
* enable CSM support in the BIOS, this allows selecting the drive, but results in an error message about inserting a valid boot media and retrying

I looked at the image with `gdisk`, and it only has a MBR partition table, and there is *no* valid GPT partition table (see below for 'Actual behavior').

Workaround: `gdisk /dev/disk/by-id/usb....` then answer 'y' to creating GPT, and use 'w' to write out the modified GPT partition table (possibly confirming once again). Now the drive is bootable and I can install Qubes.

This seems to be a regression from 4.1 which has a valid GPT partition table, and also if I look at a Linux distro like Fedora 38 that one has a valid GPT table in the .iso too. IIUC a valid GPT partition table is needed for UEFI boot to work.

### Steps to reproduce

```
gdisk --version
GPT fdisk (gdisk) version 1.0.9
```
`gdisk -l Downloads/Qubes-R4.2.0-rc1-x86_64.iso`

### Expected behavior

```
Partition table scan:
  MBR: protective
  BSD: not present
  APM: not present
  GPT: present

Found valid GPT with protective MBR; using GPT.
Disk /dev/sdd: 240254976 sectors, 114.6 GiB
Model: Ultra           
Sector size (logical/physical): 512/512 bytes
Disk identifier (GUID): A466FAFF-1FD1-412F-B145-C20D5A7E43C9
Partition table holds up to 128 entries
Main partition table begins at sector 2 and ends at sector 33
First usable sector is 34, last usable sector is 240254942
Partitions will be aligned on 64-sector boundaries
Total free space is 227634017 sectors (108.5 GiB)

Number  Start (sector)    End (sector)  Size       Code  Name
   1              64        12611263   6.0 GiB     8300  Linux filesystem
   2        12611264        12620955   4.7 MiB     EF00  EFI system partition
```

### Actual behavior

```
***************************************************************
Found invalid GPT and valid MBR; converting MBR to GPT format
in memory. 
***************************************************************

Disk Downloads/Qubes-R4.2.0-rc1-x86_64.iso: 12621556 sectors, 6.0 GiB
Sector size (logical): 512 bytes
Disk identifier (GUID): 2010CB5B-3425-4AA0-A319-077EA11C684B
Partition table holds up to 128 entries
Main partition table begins at sector 2 and ends at sector 33
First usable sector is 34, last usable sector is 12621522
Partitions will be aligned on 64-sector boundaries
Total free space is 597 sectors (298.5 KiB)

Number  Start (sector)    End (sector)  Size       Code  Name
   1              64        12611263   6.0 GiB     8300  Linux filesystem
   2        12611264        12620955   4.7 MiB     EF00  EFI system partition

```

For comparison here is `gdisk -l` output on Qubes 4.1 and Fedora 38:
```
gdisk -l Downloads/Qubes-R4.1.2-x86_64.iso
GPT fdisk (gdisk) version 1.0.9

Partition table scan:
  MBR: MBR only
  BSD: not present
  APM: not present
  GPT: present

Found valid MBR and GPT. Which do you want to use?
 1 - MBR
 2 - GPT
 3 - Create blank GPT
```

```
gdisk -l Downloads/Fedora-Workstation-Live-x86_64-37-1.7.iso 
GPT fdisk (gdisk) version 1.0.9

Partition table scan:
  MBR: protective
  BSD: not present
  APM: not present
  GPT: present

Found valid GPT with protective MBR; using GPT.
Disk Downloads/Fedora-Workstation-Live-x86_64-37-1.7.iso: 3979244 sectors, 1.9 GiB
Sector size (logical): 512 bytes
Disk identifier (GUID): AC25D109-653F-46D5-99C3-9890086BA449
Partition table holds up to 248 entries
Main partition table begins at sector 2 and ends at sector 63
First usable sector is 64, last usable sector is 3979180
Partitions will be aligned on 4-sector boundaries
Total free space is 1 sectors (512 bytes)

Number  Start (sector)    End (sector)  Size       Code  Name
   1              64         3958231   1.9 GiB     0700  ISO9660
   2         3958232         3978579   9.9 MiB     EF00  Appended2
   3         3978580         3979179   300.0 KiB   0700  Gap1
```

**Comment by bzillacodes** [comment]
With my UEFI only system, CSM disabled, secure boot enabled, custom efi enrolled. Getting pass the grub menu didn't work with R4.2.0-rc1.

grub errors such as: 
- you need to load a kernel first
- shim_lock protocol not found

**Comment by edwintorok** [comment]
@bzillacodes : I think Qubes doesn't support secure boot (see https://www.qubes-os.org/faq/#is-secure-boot-supported), but that is unrelated to this bug, try disabling secure boot after applying the 'gdisk' workaround, does that result in a bootable Qubes installer?

**Comment by TNTBOMBOM** [comment]
> enable CSM support in the BIOS

Isnt this mainly for old operating systems which doesnt support UEFI? wonder why enabling it for qubes. 

But for GPT well it should be the default instead of MBR, but dunno why if thats the case.

**Comment by marmarek** [comment]
@edwintorok have you tried plain dd too? Maybe FedoraMediaWriter does some post-processing that is specific to plain Fedora layout...

**Comment by edwintorok** [comment]
Yes, I tried plain 'dd', that doesn't work either. Also you can run 'gdisk' on the .iso file directly and it will tell you that the GPT partition table there is not valid.
In fact `wipefs` agrees that there are no `gpt` signatures in the `.iso` too, and there was before:
```
wipefs Downloads/Qubes-R4.2.0-rc1-x86_64.iso 
DEVICE                      OFFSET TYPE    UUID                   LABEL
Qubes-R4.2.0-rc1-x86_64.iso 0x8001 iso9660 2023-06-02-19-20-40-00 QUBES-R4-2-0-RC1-X86-64
Qubes-R4.2.0-rc1-x86_64.iso 0x1fe  dos  

wipefs Downloads/Qubes-R4.1.2-x86_64.iso 
DEVICE                  OFFSET      TYPE    UUID                   LABEL
Qubes-R4.1.2-x86_64.iso 0x8001      iso9660 2023-03-13-04-21-55-00 QUBES-R4-1-2-X86-64
Qubes-R4.1.2-x86_64.iso 0x1fe       dos                            
Qubes-R4.1.2-x86_64.iso 0x200       gpt                            
Qubes-R4.1.2-x86_64.iso 0x16f8ffe00 gpt 
```

Maybe some build flags for the ISO changed between 4.1.2 and 4.2.0rc1?

**Comment by marmarek** [comment]
Interestingly, OVMF seems to have no issues with that: https://openqa.qubes-os.org/tests/75065. And based on (lack of) other reports, some real systems too.

But indeed, it seems to be broken.
