### ISSUE TITLE
sys-whonix should use tinyproxy using socks instead of transparent proxying

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#8398]
@DemiMarie https://github.com/QubesOS/qubes-issues/issues/8388#issuecomment-1666591662

> I noticed that tinyproxy is _not_ connected to use Tor as a SOCKS5 proxy, and instead relies on the transparent proxying. This seems more fragile than using the SOCKS proxy. Would that help?

Generally a good idea. Could simplify Whonix firewall rules.

**Comment by adrelanos** [comment]
As per Qubes implementation, `/lib/systemd/system/qubes-updates-proxy.service` runs:

    ExecStart=/usr/lib/qubes/tinyproxy-wrapper -d -c /etc/tinyproxy/tinyproxy-updates.conf

For Qubes-Whonix to use tinyproxy with socks, tinyproxy has to be told somehow to use socks.

* I don't see a command line option for tinyproxy to configure a socks proxy.
* `tinyproxy.conf` supports [`Upstream`](https://manpages.debian.org/bookworm/tinyproxy/tinyproxy.conf.5.en.html#Upstream) `socks5`.

But how would I carry the Qubes-Whonix specific diff to add this configuration option to the config? Ideally, I would avoid shipping a full copy of `/etc/tinyproxy/tinyproxy-updates.conf` to avoid code duplication and the file getting outdated over time.

I can think of many hacks such as a systemd drop-in that uses `ExecStartPre` to append the socks configuration to `/etc/tinyproxy/tinyproxy-updates.conf`. (Doing this only once after boot.)

Do you see any more robust / clean ways to accomplish this?

**Comment by DemiMarie** [comment]
> As per Qubes implementation, `/lib/systemd/system/qubes-updates-proxy.service` runs:
> 
> ```
> ExecStart=/usr/lib/qubes/tinyproxy-wrapper -d -c /etc/tinyproxy/tinyproxy-updates.conf
> ```
> 
> For Qubes-Whonix to use tinyproxy with socks, tinyproxy has to be told somehow to use socks.
> 
> * I don't see a command line option for tinyproxy to configure a socks proxy.
> * `tinyproxy.conf` supports [`Upstream`](https://manpages.debian.org/bookworm/tinyproxy/tinyproxy.conf.5.en.html#Upstream) `socks5`.
> 
> But how would I carry the Qubes-Whonix specific diff to add this configuration option to the config? Ideally, I would avoid shipping a full copy of `/etc/tinyproxy/tinyproxy-updates.conf` to avoid code duplication and the file getting outdated over time.

The last time the file changed was in 2020, so I don’t think this is a significant problem.  tinyproxy going away entirely is far more likely IMO, as it is a nontrivial amount of C attack surface that can be replaced by a trivial SOCKS5 proxy.  At that point all Whonix will need to do is have Tor listen on the TCP port the updates proxy services expect, after which everything will just work.

**Comment by adrelanos** [comment]
Ok.

So unless there's better suggestions or there's no strong opinions on

* A) duplicating `/etc/tinyproxy/tinyproxy-updates.conf` (adding a Qubes-Whonix specific version) versus
* B) the `ExecStartPre` based hack I described above,

I'll probably implement B) soonish.

(I'll make sure to append a nice comment which explains the mechanism and rationale.)

**Comment by adrelanos** [comment]
tinxyproxy config (IP, port needs adjustment) would need something similar to this:

> upstream socks5 username:password@46.166.186.212:1080

**Comment by adrelanos** [comment]
Working on this now.

Am I right, that Qubes UpdatesProxy is nowadays fully over qrexec, no more network based connections. Hence, no iptables / nftables rules are needed to specifically handle it?

**Comment by marmarek** [comment]
Yes, only qrexec, and then connection to localhost

**Comment by adrelanos** [comment]
This has been implemented and is now in the Whonix testers repository.

related:
https://forums.whonix.org/t/use-tinyproxy-socks-proxy-support-once-available-in-qubes-whonix-gateway/18665
