### ISSUE TITLE
Print update output in descending (old to new) rather than ascending (new to old) order

### ISSUE THREAD

**Issue by TNTBOMBOM** [QubesOS/qubes-issues#8413]
### The problem you're addressing (if any)

![descendant](https://github.com/QubesOS/qubes-issues/assets/11895339/881d570d-4d24-4cde-88bf-b3f214a96686)

### The solution and value to a user you'd like

Make the results like this: 

old: xxx            |  scrollbar will go from up to down.
new:xxx           v 

The eyes will move along with the scrollbar, starting from the top where the update command was executed and going downwards until the upgrade is finished. This way, it's more comfortable for the eyes to maintain parallel reading with the scrollbar movement.

**Comment by jamke** [comment]
@andrewdavidwong 
After title modification the information that all that was written about `qubesctl` got lost.

**Comment by marmarek** [comment]
This is standard output from salt, not specific to qubesctl (which is just a wrapper around salt). If anything, that would be a feature request to salt. But since we are moving to own updater in place of salt, I don't think such change is worth doing.

**Comment by adrelanos** [comment]
Does Qubes plan to fully deprecate use of salt or only use of salt in the updater?

**Comment by marmarek** [comment]
> Does Qubes plan to fully deprecate use of salt or only use of salt in the updater?

only in updater
