### ISSUE TITLE
Thunderbird may crash on Fedora 38

### ISSUE THREAD

**Issue by GWeck** [QubesOS/qubes-issues#8416]
### Qubes OS release
R4.1.2 and R4.2.0-rc1

### Brief summary
If you try to import a calendar into Thunderbird on Fedora 38 or add a new action for processing a mail attachment, Thunderbird will pause for some seconds and then crash without giving an error message. Under Fedora37, these functions will work correctly.

### Steps to reproduce
These crashes occur when an “Open/Browse files” dialog is invoked. This is caused by an incompatibility between Fedora 38 which uses a new version of the library gdk-pixbuf 2.42.8 whereas Thunderbird 102, the version coming with Fedora 38, seems to use an older version of this library. In gdkpixbuf 2.42.8, the support for PNG and JPEG is built in (it’s linked statically, and not as shared libraries like it was the case in 2.42.4).

### Expected behavior
Thunderbird should perform these operations as it does under Fedora 37.

### Actual behavior
This also means that the shared libraries to be able to load such files are not generated nor installed by Guix at all anymore. For further information, see [Missing shared libraries for gdk-pixbuf break non-Guix applications on foreign distros](https://issues.guix.gnu.org/63853).

The reason for this incompatibility is this change in the gtk library structure that has been implemented in Fedora 38, but not in Fedora 37 and Thunderbird 102. Hopefully, the upcoming Thunderbird 115 will incorporate this change and thus be compatible again - but this version of Thunderbird is only scheduled for Fedora 39.

Until then, a workaround is to install an additional template: just vanilla Fedora 37. Before performing one of the crashing operations, connect the Thunderbird AppVM temporarily to this template, execute the operation, and assign it back. Fortunately, standard operations like sending and receiving mail are not affected.

As this is an upstream problem of Fedora, Qubes is not expected to do anything about it. It is mentioned here just to provide users affected by it to show a temporary fix, which Qubes luckily provides.

**Comment by GWeck** [comment]
**Update:** Under [https://koji.fedoraproject.org/koji/packageinfo?packageID=39 ](https://koji.fedoraproject.org/koji/packageinfo?packageID=39 ) there is now a link to an rpm package for Thunderbird 115 under Fedora 38. This is probably needed because Thunderbird 102 will reach EOL at the end of August, while Fedora 38 will then still be valid. I have no idea, however, if/when this package will be included in the standard Fedora repositories.

On my system, I could install this version without any problem, using `sudo dnf --allowerasing`, and it used my profile. (**But before installing this version 115, make a backup of your profile to be able to revert to version 102!**)

The crash on selecting the directory containing a calendar file for import still occurs with this version. So the upstream problem rests with Mozilla and still is not fixed with version 115 of Thunderbird.

**Comment by andrewdavidwong** [comment]
> As this is an upstream problem of Fedora, Qubes is not expected to do anything about it. It is mentioned here just to provide users affected by it to show a temporary fix, which Qubes luckily provides.

Thanks for the explanation! Closing as "not our bug" (the Qubes OS Project does not develop the software that is causing this bug). If anyone believes this resolution is a mistake, please leave a comment, and we'll be happy to take another look. Thank you.

Related FAQ: [Why don’t you fix upstream bugs that affect Qubes OS?](https://www.qubes-os.org/faq/#why-dont-you-fix-upstream-bugs-that-affect-qubes-os)
