### ISSUE TITLE
Missing explanation about installing qubes-template rpm

### ISSUE THREAD

**Issue by Neuro-NX** [QubesOS/qubes-issues#8417]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

4.1

### Brief summary

There is no information on how to proceed after selecting the option, 'Do not configure anything' from the aneconda post-installation screen.

As there is no netvm yet, the user must first install the 'default-template' from an rpm file, prior to running the salt formulas and setting the default  `qubes-prefs` values.

I found the rpm in `/var/lib/qubes/template-packages` after noticing it was referenced in `/usr/share/anaconda/post-scripts/30-qubes-templates.ks`.

Many users will not be aware that the post-install screen is 'anaconda', and so will not have the intuition to perform a search related to that keyword. As such, it should be explicitly stated in the documentation as to the path of the rpm file.

Reason for using option:
I am wanting to automate configuration of QubesOS using my own salt states/formulas. So instead of checking/unchecking options (depending on the machine) to create qubes etc. I would prefer to only have to select the one option, and setup everything myself.

### Expected behavior

Provide a notice in the [documentation](https://www.qubes-os.org/doc/installation-guide/#post-installation) that 'default-template' must be installed first using ~~dnf~~ `qvm-template`, and state where to locate the rpm file. Additionally, the version may be old and likely requires upgrading to the newer template.

Seeing as it is an option for advanced users, it stands to reason that it should be referenced in the [Advanced topics](https://www.qubes-os.org/doc/#advanced-topics) section, either as a seperate page or under 'How to install software in dom0'.

### Actual behavior

No information is provided in the [documentation](https://www.qubes-os.org/doc/installation-guide/#post-installation) on how to install the initial default template, seeing as "No UpdateVM is set".

**Comment by marmarek** [comment]
> must be installed first using `dnf`

While this will work (at least for now), it's better to use `qvm-template` tool for that (it can work on local files too).



> No information is provided in the [documentation](https://www.qubes-os.org/doc/installation-guide/#post-installation).

IMO this isn't the right place for such details - the "installation guide" is about the easy path, while the "do not configure anything" option is for very advanced users (and is clearly marked as such). But it may be a place to link into wherever advanced setup will become documented.

**Comment by Neuro-NX** [comment]
> > must be installed first using `dnf`
> 
> While this will work (at least for now), it's better to use `qvm-template` tool for that (it can work on local files too).

Yep, I didn't think of doing that. I ran `qvm-template install /var/lib/qubes/template-packages/qubes-template-x.rpm` and it worked.

> > No information is provided in the [documentation](https://www.qubes-os.org/doc/installation-guide/#post-installation).
> 
> IMO this isn't the right place for such details - the "installation guide" is about the easy path, while the "do not configure anything" option is for very advanced users (and is clearly marked as such). But it may be a place to link into wherever advanced setup will become documented.

Agreed.

I will close the post seeing as there is nothing else to add.
