### ISSUE TITLE
Qubes Update tool gets stuck open, then opens by itself after reboot

### ISSUE THREAD

**Issue by jimi3** [QubesOS/qubes-issues#8418]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

4.1
The Qubes Update GUI the one that pops up when the yellow Star in system tray notifies about updates, seems to get stuck when in opened state and a shutdown occurs. On next boot it will pop up on desktop even if there are no updates or were no updates before shutdown.
Clicking the window off will not prevent it from showing up on next boot.
Something though must reset this behavior since this is now the second time on this install that this is happening.

### Steps to reproduce
Can't test, i already got it

### Expected behavior
To not pop up on desktop on reboots and stay shut down and only pop up when i click on updates notification in system tray

### Actual behavior
Keeps popping up on each reboot

**Comment by bzillacodes** [comment]
Questions for diagnosis:
- was it a clean or dirty shutdown
- which qube was being updated during the shutdown (was it dom0 or a domU)
- which install was used and was dom0 updated prior to such situation occuring (were testing or stable branches used)

**Comment by jimi3** [comment]
clean
none
cannot with 100% accuracy say if there was a Dom0 update prior to this annoyance 
testing Branch, forgot to add this, though as i said i had this happening many Months ago for the first time

**Comment by bzillacodes** [comment]
I think the potential issue here, under one of the shutdown menus, from memory I think `Applications Menu -> Shutdown (I think the bottom of page) -> (some sort of prompt to remember current desktop applications)` which could be what's causing it to open after each reboot.

I think this is actually a feature of xfce itself, not qubes, and can be disabled/ existing startup configs removed somewhere within one of the dom0 xfce based applications.

**Comment by jimi3** [comment]
Tray (name) > Log out > Shutdown (Save Session for Future Logins remains checked) is the way i shut down. If this is what you are talking about, having the updater Window closed before shutdowns does not prevent it from being reopened on next boot.

**Comment by bzillacodes** [comment]
> having the updater Window closed before shutdowns does not prevent it from being reopened on next boot.

It's possible and seems like only the first shutdown is considered as the "application autostart" feature in this case. But I haven't fully tested such case.

Does the GUI for `Qubes Update` just hang or can it be accessed/shutdown?

**Comment by jimi3** [comment]
Not able to follow this thought, this Q machine has been running for a very long time now. I do shutdowns regularly / daily more then just one. 
I can just press X or cancel to close the updater gui window anytime without a problem.

**Comment by bzillacodes** [comment]
Try `Qubes Desktop Menu -> System Tools -> Session and Startup -> Saved Session (remove the default saved session)` and disable the prompt that automatically saves the session on logout.

Then perform a reboot and see if the issue persists.

**Comment by marmarek** [comment]
The old updater doesn't exist in R4.2 anymore.
