### ISSUE TITLE
Missing "unssupported hardware" detection in installer

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#8421]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

R4.2

### Brief summary

The installer used to check for required hardware features like VT-x, VT-d, etc. This feature got lost when updating to newer anaconda version.

### Steps to reproduce

Try to install R4.2 on unsupported hardware

### Expected behavior

A warning message about it.

### Actual behavior

No message.

**Comment by andrewdavidwong** [comment]
Is this a duplicate of #8345?

**Comment by marmarek** [comment]
Yes, it  is.
