### ISSUE TITLE
Installer fails to boot from USB stick with with ISO file on it

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#8422]
## Observation

openQA test in scenario qubesos-4.2-install-iso-x86_64-install_iso_file@64bit fails in
[install_iso_file](https://openqa.qubes-os.org/tests/79920/modules/install_iso_file/steps/81)

```
dracut-initqueue: timeout
```
(see screenshots above for more details)

## Test suite description

Test booting from an ISO file placed on an USB stick, as a file, not block-copied (dd). This boot mode is used by Heads, and allows verifying file signature before booting the installer.

## Reproducible

Fails since (at least) Build [4.2.202307232032](https://openqa.qubes-os.org/tests/77999)

## Expected result

Last good: [4.2.202307170636](https://openqa.qubes-os.org/tests/77657) (or more recent)

## Further details

Always latest result in this scenario: [latest](https://openqa.qubes-os.org/tests/latest?arch=x86_64&distri=qubesos&flavor=install-iso&machine=64bit&test=install_iso_file&version=4.2)

**Comment by marmarek** [comment]
Test code is at https://github.com/QubesOS/openqa-tests-qubesos/blob/main/tests/install_iso_file.pm - this more or less shows reproduction steps.

## Findings so far

The device containing ISO file is properly mounted at `/run/initramfs/isoscan`. The right ISO file is correctly connected to `/dev/loop0`. But, waiting for the device still timed out.

It seems udev does not notice loop device being connected. By watching `udevadm monitor`, I get "change" events when detaching loop device (`losetup -d /dev/loop0`), but I get no events when connecting it. Running the same in R4.2 dom0 (same udev and kernel version) does produce events in both cases, so something is different about the installer's initramfs environment.
The attach event usually is monitored by udev via inotify (with debug logging, correctly handled event starts with `loop0: Inotify event: 8 for /dev/loop0`). The watch is set via `OPTIONS+="watch"` in `/lib/udev/rules.d/60-block.rules`. And by looking at `/run/udev/watch` it seems to be present (`b7:0` symlink to `14` - which I assume is an inotify watch number). But udev is not notified about the change.
Then, looking at udevd via `strace`, the inotify watch seems to be registered properly, watching for `IN_CLOSE_WRITE` event. But then, watching `losetup` with `strace`, it opens the loop device with `O_RDONLY`, and only `IN_CLOSE_NOWRITE` inotify event is produced. This seems to be related to the `/run/initramfs/isoscan` being mounted read-only - `losetup` tries to open the iso file with `O_RDWR` and it fails with `EROFS (Read-only file system)`. It then opens the file with `O_RDONLY` which works. After that, the loop device is opened with `O_RDONLY` too. When instructing losetup to attach some writable file to the loop device, the device is opened with `O_RDWR`, and udev properly see the event.

## How to fix

There are several options:
1. Modify initramfs scripts to mount `/run-initramfs/isoscan` read-write (will not work with really read-only devices).
2. Modify udevd to watch for `IN_CLOSE_NOWRITE` too (likely a bad idea).
3. Modify losetup to always open loop device `O_RDWR`, even when configuring loop device as read-only (`LO_FLAGS_READ_ONLY`).
4. Manually call `udevadm trigger ...` after `losetup` call (only a workaround).

**Comment by DemiMarie** [comment]
Does Linux produce some sort of “a new block device showed up” uevent?

**Comment by marmarek** [comment]
This is not a new block device, it's existing /dev/loop0 reconfigured. And no, it seems no uevent is generated then.

**Comment by marmarek** [comment]
Reported an util-linux issue about this: https://github.com/util-linux/util-linux/issues/2434

**Comment by andrewdavidwong** [comment]
> Test booting from an ISO file placed on an USB stick, as a file, not block-copied (dd). This boot mode is used by Heads, and allows verifying file signature before booting the installer.

It's worth noting (for anyone reading this issue who might not already be aware) that the old `dd` method already/also allows for (re-)verifying the installer on the boot media, as we have documented here:

https://www.qubes-os.org/security/verifying-signatures/#how-to-re-verify-installation-media-after-writing

**Comment by marmarek** [comment]
@tlaurion https://openqa.qubes-os.org/tests/80558/asset/iso/Qubes-4.2.202308242042-x86_64.iso includes PR linked to this issue, and according to openQA, it should be better now. It does _not_ include kernel config changes yet.

**Comment by tlaurion** [comment]
@marmarek will wait for build with kernel changes. Soon?

**Comment by tlaurion** [comment]
@marmarek issue resolved.
Thanks and don't hesitate to ping me when iso containing kernel changes for coreboot tables are in.
