### ISSUE TITLE
builderv2 should run git commands locally

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#8427]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### The problem you're addressing (if any)

builderv2 uses an executor to run git commands, which risks corruption if the repository is concurrently being used by someone else.  Git has built-in locking to prevent this, but the executor bypasses that locking.

### The solution you'd like

The default builderv2 configuration should not use any executor to run git commands, and instead run git commands just like builderv1 did.

### The value to a user, and who that user might be

Developers will benefit from faster source updates and lower chance of repository corruption.

**Comment by fepitre** [comment]
I've not managed to get the locking mechanism to block our operations so unless you find a specific case where it can be leveraged in our workflow, please add details. I've worked on adding run of `git` directly into artifacts sources directory that would prevent normally change in component directory inodes.
