### ISSUE TITLE
Fedora 38 template update fails with `State 'pkg.uptodate' was not found in SLS 'update.qubes-vm'`

### ISSUE THREAD

**Issue by Middenvaus** [QubesOS/qubes-issues#8437]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
4.1

### Brief summary
Immediately after the start of updating the fedor 38 template, the update is interrupted with an error, but I can update manually via dnf without problems.
![image_2023-08-19_14-51-47](https://github.com/QubesOS/qubes-issues/assets/142319829/a3f2fe85-1143-4d1b-a4ef-63d366c5ba44)

### Steps to reproduce
Start update via qui-updates

**Comment by andrewdavidwong** [comment]
(@Middenvaus, future tip: It's better to post text than images, as some people participate via plain-text email and won't be able to see your images. This applies doubly when it's just an image of plain text in the first place, as in this case.)

**Comment by Middenvaus** [comment]
> (@Middenvaus, future tip: It's better to post text than images, as some people participate via plain-text email and won't be able to see your images. This applies doubly when it's just an image of plain text in the first place, as in this case. Also, plain text is searchable, whereas text in images is not.)

I did not know what you need from the text of this error. so I decided to send a screenshot

**Comment by andrewdavidwong** [comment]
> I did not know what you need from the text of this error. so I decided to send a screenshot

It's fine to copy and paste the whole text if you're not sure. In this case, it's not that long. (If it's too long, you can either hide it in a `<details>` toggle or attach a log file.)

**Comment by unman** [comment]
I can update Fedora-38 without any issue - please provide more
information.
Is this clean template?
Any new packages installed?
Does issue affect other templates? Which?
What is management_dispvm, and what is Template used by that qube?

**Comment by Middenvaus** [comment]
> I can update Fedora-38 without any issue - please provide more information. Is this clean template? Any new packages installed? Does issue affect other templates? Which? What is management_dispvm, and what is Template used by that qube?

No, its not clean template.
It has many apps installed. 
No, it does not affect other templates.
On the fedora-38 I set management_dispvm to whonix-ws-16-dvm because due to another error, I could not update the template at all via qui-update.


Now I will try to set the default value of management_dispvm

**Comment by Middenvaus** [comment]
After this changes all work

**Comment by andrewdavidwong** [comment]
This issue has been closed as "not a bug" (the reported behavior is not a bug and is already working as intended). If anyone believes this is a mistake, please leave a comment, and we'll be happy to take another look. Thank you.
