### ISSUE TITLE
After selecting the "Edit in disposable" option on a file in Thunar, a disposable (based on Fedora 38) starts then immediately shuts down

### ISSUE THREAD

**Issue by Middenvaus** [QubesOS/qubes-issues#8438]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
4.1

### Brief summary
I can’t change a file in disposable vm of fedora 38. When I open file editing in disposable vm through the context menu of the Thunar file manager, the vm first starts and then immediately turns off

### Steps to reproduce
Try to change the file in disposable vm fedora 38 through the context menu of the file manager

**Comment by andrewdavidwong** [comment]
What kind of file is it, and which app are you expecting to handle it in the disposable?

**Comment by unman** [comment]
Also, please say if you have made any changes to the policies.
Helpful too if you confirm that this is working for other qubes.
In the qube where you see this issue (which one?) please confirm what
disposable is set in qvm-prefs default_dispvm

**Comment by Middenvaus** [comment]
> What kind of file is it, and which app are you expecting to handle it in the disposable?

I tried opening the pdf in fedora vm and whonix vm temporary disp. Everything works oddly enough, although before that the temporary display vm immediately closed when you tried to open a file in it. Perhaps I opened those files in it that are not assigned to a standard application for viewing them

**Comment by Middenvaus** [comment]
> Also, please say if you have made any changes to the policies. Helpful too if you confirm that this is working for other qubes. In the qube where you see this issue (which one?) please confirm what disposable is set in qvm-prefs default_dispvm

No, I didn't make any policy changes.

**Comment by unman** [comment]
On Sat, Aug 26, 2023 at 01:57:27AM -0700, Middenvaus wrote:
> > What kind of file is it, and which app are you expecting to handle it in the disposable?
> 
> I tried opening the pdf in fedora vm and whonix vm temporary disp. Everything works oddly enough, although before that the temporary display vm immediately closed when you tried to open a file in it. Perhaps I opened those files in it that are not assigned to a standard application for viewing them
> 
Yes, if there is not default application set, then the qube will close,
without any informative explanation.

**Comment by Middenvaus** [comment]
> On Sat, Aug 26, 2023 at 01:57:27AM -0700, Middenvaus wrote: > What kind of file is it, and which app are you expecting to handle it in the disposable? I tried opening the pdf in fedora vm and whonix vm temporary disp. Everything works oddly enough, although before that the temporary display vm immediately closed when you tried to open a file in it. Perhaps I opened those files in it that are not assigned to a standard application for viewing them
> Yes, if there is not default application set, then the qube will close, without any informative explanation.

Thanks for you help. I'm closing the issue

**Comment by andrewdavidwong** [comment]
This issue has been closed as "not a bug" (the reported behavior is not a bug and is already working as intended). If anyone believes this is a mistake, please leave a comment, and we'll be happy to take another look. Thank you.
