### ISSUE TITLE
Wi-Fi firmware missing from default templates on 4.2.0-rc2 ISO

### ISSUE THREAD

**Issue by SiGraphics** [QubesOS/qubes-issues#8452]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

Qubes-4.2.202308270121-x86_64.iso

### Brief summary

WiFi AX200 card recognized via "lspci" command, but wireless not available with either Fedora or Debian disposable template.

### Steps to reproduce

1) Install R4.2 Weekly build dated Aug-2023 03:34 with (a) Disposable Fedora or (b) Disposable Debian template
2) Attempt to connect to WiFi, but WiFi not available in either case

### Expected behavior

WiFi works

### Actual behavior

WiFi doesn't work
Unable to test LAN connection

**Comment by andrewdavidwong** [comment]
Possible related/duplicate issue: #5615

**Comment by SiGraphics** [comment]
Just tried with 4.2.0-rc2 and same issue. In addition, non-disposable debian template has no AX200-related WiFi access.

**Comment by andrewdavidwong** [comment]
> wireless not available with either Fedora or Debian disposable template.

> In addition, non-disposable debian template has no AX200-related WiFi access.

Can you clarify what you mean by this? Are you saying that a non-disposable sys-net based on a Fedora template *does* work?

**Comment by SurFlurer** [comment]
Do you have firmware-iwlwifi installed in your debian template?

**Comment by SiGraphics** [comment]
On 4.2.0-rc2:

Disposable Debian does not have WiFi with AX200
Disposable Fedora does not have WiFi with AX200
Debian does not have WiFi with AX200
Have not tried Fedora

Intel wireless drivers missing in 4.2.0-rc2

**Comment by marmarek** [comment]
> Disposable Debian does not have WiFi with AX200
> Disposable Fedora does not have WiFi with AX200

What specifically do you mean here? What `cat /etc/os-release` in sys-net specifically shows?

**Comment by SiGraphics** [comment]
I don't have wired LAN access, so I removed 4.2.0-rc2. Using 4.2.0-rc2 for sys-XYZ I have no wireless using either the disposable Fedora template, nor the disposable Debian template, nor the persistent Debian template. I did not try the persistent Fedora template as I expected the same as the previous three (of four) options.

If desired I can reload 4.2.0-rc2 again. If so, please let me know exactly what you'd like to see and I'll do that.

**Comment by marmarek** [comment]
If you can, it would be useful to have full boot log from sys-net using either Fedora (preferably) or Debian - you can get it with `sudo journalctl -b > some-file.txt` in sys-net. For this information, disposable or not should not matter, at least in theory...

**Comment by marmarek** [comment]
One more idea: try choosing "kernel-latest" option when starting the installer (it's still in grub menu).
There might be mismatch between firmware version provided by Debian/Fedora and firmware version required by the kernel.

**Comment by SiGraphics** [comment]
I did try the kernel-latest too, when using persistent Debian, but still no WiFi. For all four tests in the sys-net directory /lib/firmware none of the intel files are present (iwlwifi-XYZ). Given my results, any fresh 4.2.0-rc2 install will show the same.

**Comment by Kenny606** [comment]
> One more idea: try choosing "kernel-latest" option when starting the installer (it's still in grub menu). There might be mismatch between firmware version provided by Debian/Fedora and firmware version required by the kernel.

I'm seeing the same problem with 4.2.0-RC2 My machine has an Intel AX201 I tried both Debian and Fedora. 
I attempted a reinstall this morning with the latest Kernel option but no cigar.
My Ethernet adapter is working, I updated all templates but no change there either.

HOWEVER I just installed the "Fedora-38" template from itl-testing and made that my default template, spun up sys-net and sys-firewall and bang my wifi is working. Hopefully that's of some help to the Dev's and any users following this bug.
Hopefully it's of some help.

**Comment by DemiMarie** [comment]
I’m upgrading this to “blocker”.  It makes no sense to ship a release that has broken internet access for a large portion of users.

**Comment by rustybird** [comment]
The relevant missing packages in the xfce template flavor are `iwlwifi-dvm-firmware` and/or `iwlwifi-mvm-firmware`. (They're [here](https://mirrors.kernel.org/fedora/updates/38/Everything/x86_64/Packages/i/), for people who want to get them out of band. Don't forget to verify with `rpm -K`.) But the template should probably just come with the whole `@hardware-support` package group, like the gnome flavor.

`cryptsetup` is another notable absence, btw.

**Comment by jonhermansen** [comment]
Just wanted to confirm that I had this same issue in RC2, and it's fixed on RC3. Thank you!
