### ISSUE TITLE
builderv2: option to leave executor not cleaned up only on failure

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#8456]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### The problem you're addressing (if any)

When command completes, by default builderv2 cleans up the execution environment (docker, dispvm etc) right away. This includes cases of failures too, making it difficult to diagnose what failed (logs are not always enough, for example to fix patch that failed to apply). There is `executor:options:clean=false` option, but it disables cleanup always, also in the successful case, which causes accumulation of build environments.

### The solution you'd like

An option similar to `executor:options:clean=false` but to apply only to failed executions.

### The value to a user, and who that user might be

Easier debugging failed builds.

**Comment by fepitre** [comment]
It has been implemented with  `clean-on-error` option.
