### ISSUE TITLE
`90-default.policy` not upgraded after in-place upgrade from 4.1 to 4.2

### ISSUE THREAD

**Issue by Szewcson** [QubesOS/qubes-issues#8458]
### Qubes OS release
4.1 -> 4.2

### Brief summary

Today i preformed in-place dist upgrade of Qubes. During upgrade I realized that my 90-default.policy file was not upgraded (probably for a long time) since I saw many popups about blocking qubes.SyncAppMenus during template upgrade and runing post script.

### Steps to reproduce

Start upgrade in OS with old 90-default.policy file

### Expected behavior

Everything run smooth and default policies are upgraded in first stages of dist upgrade.

### Actual behavior
Default polices are not upgraded and  blocks qubes.SyncAppMenus calls

**Comment by andrewdavidwong** [comment]
Sounds like a potential 4.2 blocker (if not unique to one user). Provisionally increasing priority. Devs, feel free to knock it back down if not really a blocker.

**Comment by marmarek** [comment]
Have you modified that file (even though there is a comment at the top to not do that)? I think RPM skips updating config file only if it was modified by the user.
Anyway, I'll adjust packaging to always update those default policies.

**Comment by Szewcson** [comment]
Yes, I probably modified it long time ago. My bad.

**Comment by Szewcson** [comment]
I have found in Qubes Os Global Config two more policies fielst that are some lefovers, and Qubes Os Global Config reporting them as manual changes (and for those I'm sure that I not touch them before upgrade):
```
30-qubesctl-salt
qubes.UpdatesProxy
```
