### ISSUE TITLE
Error message about missing NetVM; sys-net cannot be started

### ISSUE THREAD

**Issue by code9n** [QubesOS/qubes-issues#8461]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

4.2 rc1

### Brief summary

A fresh install of Qubes 4.2 rc1 on two different Lenovo T430 i7 3520M works but you get a message to the effect of:

'There is no net vm'.   

There is a net vm in the Qubes manager but you can't start it, it just stops again automatically if you try.

In the 'devices' tab of the Qubes settings manager both Ethernet and Wireless NICs appear to be present in the 'selected' box.

### Steps to reproduce

Completely install a fresh Qubes 4.2 rc1 on a Lenovo T430 or T430s.  All defaults followed.

### Expected behavior

There should be a functioning net vm and you should have network connectivity.

### Actual behavior

There is a complete install that appears correct in all matters except for the 'no net vm created' issue described.

**Comment by andrewdavidwong** [comment]
Can you try Qubes 4.2.0-rc2?

**Comment by code9n** [comment]
Yes it looks like the same issue, sorry about that.  I'll try rc2 and comment on #8242 if and as appropriate.
  Closing this issue.

**Comment by andrewdavidwong** [comment]
This appears to be a [duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If anyone believes this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Comment by andrewdavidwong** [comment]
Duplicate of #8242

**Comment by code9n** [comment]
I don't know if this is the same issue as #8242 or not but hopefully it is useful.

###Qubes OS release

4.2 rc2

###Brief summary


On fresh default install of 4.2 rc2 onto a Lenovo T430 the install is all good except you get this message:

['/usr/bin/qvm-start', 'sys-firewall'] failed:
stdout:""
stderr: "Start failed: internal error libxenlight failed to create new domain 'sys-
firewall', see /var/log/libvirt/libxl/libxl-driver.log for details

at the end of the install. 

The only running vm is dom0.

Then when you try to start either sys-usb, sys-net or sys-firewall they open and start then immediately shut down.  Leaving no network access so no updating.

sys-usb and sys-firewall are dvms but sys-net is from a template (default - fedora 38)

###Steps to reproduce

Make a default install of Qubes 4.2 rc2 (the same thing happened in rc1).  Reboot.

###Expected behavior

These vms should persist and provide network access.

###Actual behavior

These vms start then once started immediately stop themselves.


I have not tried  @syntheticdrek 's comment in #8242 because the net-vm was not disposable.

**Comment by code9n** [comment]
This is fixed in 4.2 rc3.
