### ISSUE TITLE
Qubes R4.2.0-rc2 cannot be installed on legacy BIOS system

### ISSUE THREAD

**Issue by GWeck** [QubesOS/qubes-issues#8462]
### Qubes OS release
R4.2.0-rc2

### Brief summary
The installation media is not seen on a system with legacy BIOS only. 

### Steps to reproduce
Boot the R4.2.0-rc2 installation media copied with Rufus 3.22 from the iso-File using DD-mode. The iso-file was checked for correctness using the hashes provided.

### Expected behavior
Installation should proceed as with R4.2.0-rc1.

### Actual behavior
The system does not see the installation media if only legacy BIOS is enabled, so installation cannot start. If UEFI is enabled on such a system, installation proceeds as a UEFI installation, which may be inappropriate on multi-boot systems set up with legacy BIOS. The installer offers no disk setup for legacy BIOS in this case.
(Tested on a HP EliteBook 840G4 with a USB SSD Samsung T5 Portable, which was successfully used for previous tests.)

**Comment by SurFlurer** [comment]
Possibly because fedora 37 dropped legacy bios support on new installation: https://fedoraproject.org/wiki/Changes/DeprecateLegacyBIOS

**Comment by GWeck** [comment]
> Possibly because fedora 37 dropped legacy bios support on new installation

Following Fedora in this respect would cause severe problems for Qubes users depending on legacy BIOS, especially on older laptops. Anyhow, rc1 uses Fedora 37 and still is able to support legacy BIOS. The problem here seems to me to be the return of an earlier problem with some pre-rc1 iso-files.

**Comment by marmarek** [comment]
The theory is that only boot sector in MBR should matter, and we have grub2 installed there, and there is also "protective MBR partition table". But I guess this might be yet another case of some BIOSes trying to be smart and try to look further...
@GWeck can you try editing this MBR partition table (`fdisk -t dos` ?) and marking the partition as bootable? Maybe it will be enough for this BIOS...

**Comment by GWeck** [comment]
@andrewdavidwong It looks just the same, although I did not follow it up that far. On the HP system, the installation media is invisible in legacy BIOS mode, and if UEFI is enabled, the installer tries to force an EFI installation. On my other system, the installer can be started, like it was then.

@marmarek Modifying the partition table with `fdisk -t dos` destroys the structure of the installation media and just shows an empty USB stick in my partitioning tool (MiniTool Partition Wizard on Windows). On the HP system, the installation media stays invisible in legacy BIOS mode, and on the other system, trying to boot enters Grub rescue mode.

For your information, here is the installation media layout for R4.2.0-rc1 which works:

![Inst_Media_R4 2 0-rc1](https://github.com/QubesOS/qubes-issues/assets/22047384/e3bdb023-6764-4a77-9c40-3455dbad25fa)

and here for R4.2.0-rc2 which does not work:

![Inst_Media_R4 2 0-rc2](https://github.com/QubesOS/qubes-issues/assets/22047384/3c4b50e4-c369-4996-9e6a-05517f3d187d)

So the HP legacy BIOS simply does not regard the GPT EFI system partition as bootable. The remedy might be, just as it was in #8058, to return to the media structure used in R4.1.2.

**Comment by marmarek** [comment]
@GWeck can you check https://openqa.qubes-os.org/tests/81264/asset/iso/Qubes-4.2.202309020507-x86_64.iso ? It includes the PR listed above.

**Comment by GWeck** [comment]
I checked on both of my systems, and on both the installer could be loaded. On the HP laptop, I successfully installed Qubes R4.2 (and it came up even in German :heart:! So the problem seems to be fixed.

For your reference, here is the installer's layout, as my tool sees it, which is quite what is to be expected on my system:

![Qubes-4 2 202309020507](https://github.com/QubesOS/qubes-issues/assets/22047384/6ca63caa-425d-4bbe-a820-c854e941bcb4)

**Comment by GWeck** [comment]
I checked R4.2.0-rc3. The installation went o.k. on my HP Laptop.
