### ISSUE TITLE
boot loop and/or boot lock on qubes boot screen

### ISSUE THREAD

**Issue by grumpybears** [QubesOS/qubes-issues#8468]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
Qubes 4.2 RC2

### Brief summary
I installed RC2 on a fresh SSD on a Librem 14 laptop.  I used the automatic partitioning of the SSD.  After the install finishes, it goes to a black screen and does not reboot.  

### Steps to reproduce
When I force the reboot, the blue Qubes screen loads.  At the screen one of two things happen:

1. If no keys are pressed, after the countdown, the laptop reboots, with no errors or warnings that I can see.  If I do nothing, it continues this pattern.
2. If I press a key on the Qubes boot screen, the computer freezes.

### Expected behavior
Qubes boots

### Actual behavior
Boot loop or freeze on Qubes boot screen

**Comment by csarn** [comment]
This is not exactly the same behaviour, but quite similar to my issue: #8464

**Comment by grumpybears** [comment]
> This is not exactly the same behavior, but quite similar to my issue: #8464

I tried these steps, and while it does fix the reboot loop, it still freezes after the countdown assuming I did it correctly.

**Comment by grumpybears** [comment]
RC3 resolved my boot issue.

**Comment by andrewdavidwong** [comment]
Closing as resolved. If anyone believes this issue is not yet resolved, or if anyone is still affected by this issue, please leave a comment, and we'll be happy to reopen it. Thank you.
