### ISSUE TITLE
Qubes Global Settings crashes when trying to open it

### ISSUE THREAD

**Issue by catalyst1987** [QubesOS/qubes-issues#8469]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
4.1.2

### Brief summary
When trying to open up the Qubes Global Settings option, I get an error and it closes.  

The error I get is:

"Whoops.  A critical error has occurred.  This is most likely a bug in Qubes Manager.  

QubesException: Cannot detect enabled dom0 update repositories
at line 11
of file /usr/bin/qubes-global-settings."

### Steps to reproduce
Open the Qubes Global Settings option either from the menu drop down in xfce or directly from the Qubes Manager.  

### Expected behavior
It will open without crashing

### Actual behavior
It crashes with an error

**Comment by marmarta** [comment]
This was fixed and also global settings were deprecated.
