### ISSUE TITLE
Sway in X11 drops the letter “c”

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#8474]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

R4.2

### Brief summary

Under certain conditions, pressing the letter “c” seems to have no effect.

### Steps to reproduce

Run Sway in an X11 window (via wlroots’s X11 backend).  Use it for a while and run various types of applications.

### Expected behavior

The “c” key keeps working.

### Actual behavior

The “c” key stops working.

**Comment by marmarek** [comment]
Are you sure it's Qubes issue? Based on the description it sounds rather unlikely (I'd guess it's either wlroots or Sway issue).

**Comment by DemiMarie** [comment]
Could also be a foot or tmux issue, though those are even less likely IMO.

**Comment by DemiMarie** [comment]
I’m inclined to agree with @marmarek that this is probably <https://github.com/QubesOS/qubes-issues/labels/R%3A%20upstream%20issue>.
