### ISSUE TITLE
NV41 laptop not going into standby mode

### ISSUE THREAD

**Issue by UndeadDevel** [QubesOS/qubes-issues#8483]
### Qubes OS release
4.1.2

### Brief summary
First advertised as supporting standby, it unfortunately does not actually seem to work right now. Supported power states are listed as S0, S1, S5 in dmesg and /sys/power/mem_sleep has the options s2idle (default) and shallow, both of which don't work. I also tried adding a specific line to Grub as suggested in the docs, but to no avail. When using 'shallow' it seems to go into standby, but immediately comes out again and never actually fully shuts off the fans...after that the system needs to be (soft) rebooted to get WiFi working again. With 's2idle' the system will turn off the display and keyboard backlight but then get stuck, requiring a hard reboot to become usable again.

### Steps to reproduce
Try to enter standby with the NV41.

### Expected behavior
Enters standby and comes out again without issues.

### Actual behavior
Never fully enters standby and either requires hard reboot or soft reboot to become fully functional again.

**Comment by marmarek** [comment]
Check if S3 is enabled in the firmware settings (AFAIK it should be by default if you bought it with Qubes OS, but maybe for some reason it isn't on your system). If you don't have this option, verify if you have [firmware version 1.6.0](https://docs.dasharo.com/variants/novacustom_nv4x_adl/releases/) (again, it should be the default for device bought with Qubes OS).

**Comment by UndeadDevel** [comment]
Thank you for the reply. I apologize as I should have been more precise: I bought the Heads-variant of this model from Nitrokey, so it does not run "normal" coreboot and I suppose this variant of the NV41 is technically not Qubes-certified. It was still advertised by NitroKey as supporting S3 standby, however.

I messaged NK support and they say they are working on a firmware update that will fix this (hopefully).

**Comment by UndeadDevel** [comment]
Solved with latest NitroKey Heads (2.4).
