### ISSUE TITLE
Connecting a display (DisplayPort via USB-C) opens display managers in all running domUs

### ISSUE THREAD

**Issue by b90g** [QubesOS/qubes-issues#8485]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
rc2 *but updated, equal to rc3 i guess

### Brief summary

When connecting Displays (1x DisplayPort via USB-C with HDMI adapter & 1x HDMI nativ) the Displaymanager in all running DomU start and offer me how to arrange my Displayconfig

### Steps to reproduce

Run 4.2rc2+ and connect a display

### Expected behavior

Displaymanager in Dom0 starts

### Actual behavior

Displaymanagers in all runnning DomU starts

**Comment by Jauchi** [comment]
Hello!

I can reproduce this too, but I have a workaround.
In `Advanced` in the `Display` configuration for dom0:
* Configure the screens to your liking
* Add a profile
* Enable `Configure new displays when connected`
* Enable `Automatically enable profiles when new display is connected

For reference, these are my settings: ![display](https://github.com/QubesOS/qubes-issues/assets/17363382/be05a854-ebc3-418c-8fc3-bfe6781edf9f)
After connecting the displays again, I do not get any popups in any DomUs.

**Comment by marmarek** [comment]
[qubes-core-agent v4.2.27](https://github.com/QubesOS/updates-status/issues/4240) fixes the issue, simply install the updates.
