### ISSUE TITLE
Some R4.1 firewall scripts do not work after upgrading to R4.2

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#8487]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

R4.2

### Brief summary

As a consequence of https://github.com/QubesOS/qubes-issues/issues/5031, most custom firewall scripts are broken after upgrade. Example at https://github.com/tasket/Qubes-vpn-support/issues/72

### Steps to reproduce

1. Have R4.1 with some custom firewall rules
2. Upgrade (either in-place, or reinstall + backup&restore) to R4.2

### Expected behavior

Functional setup. Old rules that use `iptables` remain functional.
`iptables` wrapper creates nft rules already, all that is missing is not overruling their effect.
While I understand it might be tricky in some cases due to interaction between different tables, but maybe at least simpler cases (like allowing specific incoming connections, or allowing inter-qube connections) can be not broken?

### Actual behavior

Many firewall rules do not work anymore. For example rules allowing some traffic in `INPUT` or `FORWARD` chains.
This is a major issue, especially since the `nft` syntax is very different from `iptables` and not well known yet. And most online guides instruct how to use `iptables`, not `nft` (and our own documentation definitely isn't and wont be enough to cover missing cases).

**Comment by DemiMarie** [comment]
There are a few options here:

1. Revert to using `iptables` instead of `nftables`.  This is undesirable because `iptables` is deprecated and might stop working in a future distribution version.
2. Use table and chain names that make `iptables-nft` work.  I will test if this is possible.
3. Close this as “can’t fix”.

**Comment by dylangerdaly** [comment]
Can we please bump the priority of this issue? It currently breaks all/any VPN usage on Qubes 4.2, this is a pretty important daily usage for Qubes imo

**Comment by DemiMarie** [comment]
@dylangerdaly I will see if this can be fixed, but in the long term the VPN code needs to be rewritten to use `nftables` instead of `iptables`.

**Comment by dylangerdaly** [comment]
Ah okay, fair enough, I can take a look over the weekend at porting it

-------- Original Message --------

**Comment by 3hhh** [comment]
There's `iptables-translate` and `ip6tables-translate` for the migration, see the respective manpages for further details.

**Comment by DemiMarie** [comment]
Should this be <https://github.com/QubesOS/qubes-issues/labels/R%3A%20declined>?  I agree that it is a legitimate bug, but I don’t know any way to fix it without reverting to the obsolete iptables syntax :cry:.

**Comment by unman** [comment]
It should be declined, cant fix.

Scripts or programs that rely on features that have been removed or
obsoleted in an update are cant fix.
It's up to users to rewrite their scripts etc to use whatever is
available in later releases. The move to nftables has been signposted
for years.
