### ISSUE TITLE
4.2-RC2 Fedora-38-xfce template not upgrading

### ISSUE THREAD

**Issue by JPL1** [QubesOS/qubes-issues#8496]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
4.2-rc2

### Brief summary
Updating Fedora template using Qubes Update - metadata cannot be found. No problem with Debian-12 template

### Actual behavior

Updating fedora-38-xfce

Errors during downloading metadata for repository 'qubes-contrib-vm-r4.2-current':
  - Status code: 404 for https://contrib.qubes-os.org/yum/r4.2/current/vm/fc38/repodata/repomd.xml (IP: 127.0.0.1)
Failed to download metadata for repo 'qubes-contrib-vm-r4.2-current': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried

**Comment by DemiMarie** [comment]
Looks like the contrib repos are missing for R4.2.  @fepitre can you take a look?

**Comment by pasyn** [comment]
Same as issue #8599.
qubes-contrib is not available yet. Use qubes-contrib-testing instead.

**Comment by kennethrrosen** [comment]
> Same as issue #8599. qubes-contrib is not available yet. Use qubes-contrib-testing instead.

Can confirm https://github.com/QubesOS/qubes-issues/issues/8599#issuecomment-1763441588

**Comment by fepitre** [comment]
It is solved.
