### ISSUE TITLE
Sys-Firewall - DNS request to root-servers on bootup

### ISSUE THREAD

**Issue by akkuladezeit** [QubesOS/qubes-issues#8501]
### Qubes OS release
4.1.2

### Brief summary
The Sys-Firewall vm tries to Access all Root DNS Server directly ignoring the configured local dns.

### Steps to reproduce
Log Traffic on UPD 53 at Firewall connected to Qubes-PC

In my Case any non local dns requests are blocked..

### Expected behavior
Sys-Firewall using DNS Ip form DHCP

### Actual behavior
Qubes try to access a-m .Root-servers.net for DNS request on Port 53 udp 

Is This behaviour intended?

**Comment by akkuladezeit** [comment]
Its not Happens Every bootup of Sys-net / sys-Firewall... 

Maybe some stuff from clock-Sync? Oder dom0 Update ?

**Comment by DemiMarie** [comment]
This is likely `systemd-resolved`.

**Comment by alimirjamali** [comment]
> This is likely `systemd-resolved`.

Yep. It is the default `systemd-resolved` behaviour. Documented [here](https://www.freedesktop.org/software/systemd/man/latest/resolved.conf.html#FallbackDNS=) in Freedesktop reference. The hard-coded root DNS servers are [here](https://github.com/systemd/systemd/blob/main/meson_options.txt#L358-L360). i.e. Google and Cloudflare root DNS servers at the moment. And [here](https://github.com/systemd/systemd/issues/494#issuecomment-118958955) Lennart Poettering defends the current behaviour.

There are many ways to deal with this issue. Just document it? Deliver a `resolved` config similar to [this one](https://github.com/QubesOS/qubes-core-agent-linux/blob/main/vm-systemd/30_resolved-no-mdns-or-llmnr.conf) which is provided via qubes-core-agent-linux and set `FallbackDNS=`?
