### ISSUE TITLE
[Request] Install i3 with QubesOS Install

### ISSUE THREAD

**Issue by hbednar** [QubesOS/qubes-issues#8509]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### The problem you're addressing (if any)

At the moment i3 window manager is supported but only if you decide to manually configure it.
Also, this may not be obvious unless you go looking through the documentation.

### The solution you'd like

Can you add it to the initial install process either alongside or instead of Xfce if possible

### The value to a user, and who that user might be

Anyone who wants an alternative to Xfce.
Users of i3 who haven't looked through the documentation.
Users of i3 who don't have the confidence or knowledge to configure i3 in QubesOS.

**Comment by marmarek** [comment]
I don't think that's a good idea for several reasons, including:
 - space on the installation image (it's way too big already)
 - i3 requires some tinkering anyway, users who are not confident enough to install one extra package will most likely be lost in i3 anyway
 - i3 isn't regularly tested, so proposing it as one of default configurations is not an option (read - automated tests are prerequisite to propose something as default config)

**Comment by hbednar** [comment]
As an alternative is there anyway users can be given a lighter install option. 
This may also help with the ISO size.

> i3 requires some tinkering anyway, users who are not confident enough to install one extra package will most likely be lost in i3 anyway

I think tinkering is almost part of i3 and window managers but, installing a new environment in Qubes OS may be different.

**Comment by andrewdavidwong** [comment]
Closing as "won't do." If anyone has a new reason for why this should be done, please leave a comment, and we'll be happy to take another look. Thank you.
