### ISSUE TITLE
Different values for `menu-items` and `default-menu-items` are not preserved when cloning templates

### ISSUE THREAD

**Issue by gonzalo-bulnes** [QubesOS/qubes-issues#8518]
- [x] Read [How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

R4.1 up-to-date (Not tested on previous releases.)

### Brief summary

_Submitting this issue on behalf of **SteveC** in the Qubes OS forum._ ([context](https://forum.qubes-os.org/t/a-clone-is-not-an-exact-copy-shouldnt-it-be/20958/5))

When cloning a template whose `menu-items` and `default-menu-items` are different (see below), the `menu-items` don't seem correctly set on the clone.

### Steps to reproduce

1) Find (or create) a template whose `menu-items` and `default-menu-items` are different.  `default-menu-items` cannot be empty.  Check using `qvm-features`.
2) Clone it with `qvm-clone <existing template> <new template>`
3) Run `qvm-features` on the new qube to show `menu-items` and `default-menu-items`.

### Expected behavior

The clone's `menu-items` match the originsl `menu-items`, and the clone's `default-menu-items` match the original `default-menu-items`.

### Actual behavior

Both `menu-items` and `default-menu-items` are set to whatever the original qube had for `default-menu-items`.

### Additional observations

Note: If default-menu-items is empty/unset the clone operation correctly copies the `menu-items` (which is probably why no one ever noticed this before).

Note: Whoever works this please ensure there isn’t a similar problem for AppVMs (both dispvm templates and ‘normal’ AppVMs) and for named disposables.

**Comment by rapenne-s** [comment]
I can reproduce it as well on 4.2-RC3

**Comment by rapenne-s** [comment]
works for me now :ok_hand:
