### ISSUE TITLE
Split GPG doesn't work with sops 3.8.0

### ISSUE THREAD

**Issue by james-callahan** [QubesOS/qubes-issues#8523]
### Qubes OS release

4.1

### Brief summary

The `sops` tool is used to work with encrypted json/yaml.
They recently had a new release (3.8.0) that starts passing the arguments to gpg: `--no-default-keyring` and `--homedir /home/user/.gnupg`.
These arguments are not handled correctly by split gpg.
  - `--no-default-keyring` is handled [here](https://github.com/QubesOS/qubes-app-linux-split-gpg/blob/ef64f62a882a2e62f31c06ab5e02cbe7e0dd1643/gpg-client-wrapper#L39-L40)
    That comment may be incorrect.
  - `--homedir` isn't handled at all, and it fails with `qubes-gpg-client: unrecognized option '--homedir'`

Issue also filed with sops at https://github.com/getsops/sops/issues/1294

### Steps to reproduce

`sops -d mysopfile.yaml`

Or alternatively:

`gpg --no-default-keyring --homedir /home/user/.gnupg -d a_gpg_encrypted_file.gpg`

### Expected behavior

Decryption of the file/secret using my key in my vault qube.

### Actual behavior

Attempts to decrypt in my current qube (because of the `--no-default-keyring`)

**Comment by DemiMarie** [comment]
At what point do we release split-gpg2 and deprecate split-gpg1?

**Comment by marmarek** [comment]
> At what point do we release split-gpg2 and deprecate split-gpg1?

The package is available in R4.2 (stable) repos for a long time already. We can add it to R4.1 too. The main missing part is documentation how to use it.

**Comment by marmarek** [comment]
@james-callahan back to your issue, options for selecting which keyring to use are fundamentally incompatible with split-gpgv1 (the one you use), as the client qube has no visibility into where the keyring actually is stored, and should not have control over it. The option combination used by `sops` here looks weird - it adds `--no-default-keyring`, but does not specify any other keyring (so, no keyring should be used at all? decryption would fail then...). And then it specifies explicitly `--homedir`, to the value that is in fact the default one already.

Split-gpg2 takes another approach, which should be much more compatible with various options. If you want to try, take a look at readme in https://github.com/qubesos/qubes-app-linux-split-gpg2/. The package will be in [testing repository](https://www.qubes-os.org/doc/how-to-install-software/#testing-repositories) in a few minutes, so you don't need to build it yourself.

**Comment by andrewdavidwong** [comment]
So, is this a "won't fix" because it affects only Split GPG v1, or what?

**Comment by DemiMarie** [comment]
I think it is more of a “can’t fix” due to how Split GPG v1 works.

**Comment by andrewdavidwong** [comment]
> I think it is more of a “can’t fix” due to how Split GPG v1 works.

Okay, but "can't" implies "won't." :)

**Comment by andrewdavidwong** [comment]
Closing as "won't fix." If anyone has a new reason for why this should be done, please leave a comment, and we'll be happy to take another look. Thank you.
