### ISSUE TITLE
man-db.service slowing down boot time of Whonix-16 VMs

### ISSUE THREAD

**Issue by UndeadDevel** [QubesOS/qubes-issues#8524]
### Qubes OS release
4.1.2

### Brief summary
I've noticed that man-db.service regularly shows up in `systemd-analyse blame` as the first or second item, taking between 700 and 900 ms and thus significantly slowing down the boot of both workstation and gateway Whonix 16 VMs (both for DVMs as well as the anon-whonix AppVM).

Curiously I also had one boot where this wasn't the case, but in all the others I've checked it was.

### Steps to reproduce
Happens on almost every boot, both for sys-whonix and the workstation VMs. Check with `systemd-analyse blame`.

### Expected behavior
man-db.service doesn't slow down boot significantly.

### Actual behavior
man-db.service regularly appears as top item in systemd-analyse blame.

**Comment by adrelanos** [comment]
Can you reproduce this in a Debian bookworm VM?

**Comment by UndeadDevel** [comment]
> Can you reproduce this in a Debian bookworm VM?

No, have not seen this in regular debian-12 VMs, only in whonix VMs, both sys-whonix and the workstations, e.g. the current one:
```
805ms man-db.service
776ms sdwdate-pre.service
387ms dev-xvdc1.device
384ms sdwdate.service
384ms qubes-network-uplink.service
375ms dev-mapper-dmroot.device
328ms qubes-whonix-postinit.service
305ms logrotate.service
218ms systemd-journald.service
197ms systemd-modules-load.service
195ms whonix-firewall.service
192ms systemd-udev-trigger.service
173ms systemd-remount-fs.service
137ms qubes-mount-dirs.service
122ms systemd-journal-flush.service
112ms qubes-rootfs-resize.service
108ms user@1000.service
 98ms qubes-network-uplink@eth0.service
 88ms tb-updater-dispvm.service
 84ms xen.service
 83ms qubes-misc-post.service
 77ms dev-hugepages.mount
 76ms dev-mqueue.mount
 75ms sys-kernel-debug.mount
 74ms sys-kernel-tracing.mount
 72ms systemd-logind.service
 70ms anon-ws-disable-stacked-tor_autogen_port_9150.socket
 69ms sysfsutils.service
 68ms anon-ws-disable-stacked-tor_autogen_port_9151.socket
 68ms wpa_supplicant.service
 65ms legacy-dist.service
 61ms apparmor.service
 61ms xendriverdomain.service
 55ms systemd-random-seed.service
 50ms bootclockrandomization.service
 47ms systemd-udevd.service
 41ms qubes-sysinit.service
 33ms dev-xvdb.device
 28ms systemd-sysctl.service
 26ms dev-xvdc1-swap.service
 26ms xendomains.service
 23ms msgcollector.service
 23ms dist-skel-first-boot.service
 23ms rsyslog.service
 22ms qubes-meminfo-writer.service
 22ms e2scrub_reap.service
 21ms systemd-tmpfiles-setup-dev.service
 21ms qubes-db.service
 20ms modprobe@fuse.service
 19ms anon-ws-disable-stacked-tor.service
 18ms remove-system-map.service
```

**Comment by adrelanos** [comment]
man-db doesn't seem to be useful in App Qubes anyhow.

It would be good if Qubes shipped a systemd drop-in to disable

/lib/systemd/system/man-db.service

in App Qubes.

**Comment by UndeadDevel** [comment]
> man-db doesn't seem to be useful in App Qubes anyhow.

Indeed. Doing a quick search I see people on a manjaro forum, arch forum and askubuntu.com also complaining about man-db.service slowing down their boot (throughout the last years, not right now), so it seems a common issue that crops up occasionally. I agree that this service should just be disabled for AppVMs; unfortunately I don't think it's safe to try to disable it for Whonix DVMs, right? IIRC I'm supposed to never start whonix-ws-16-dvm.

**Comment by adrelanos** [comment]
I don't have safety concerns here.

**Comment by UndeadDevel** [comment]
> I don't have safety concerns here.

Okay, so I could do `systemctl --user mask man-db.service` in `whonix-ws-16-dvm` and it won't impact anonymity?

I've also discovered that this issue is more Qubes-specific after all: it reappeared for me, probably due to a recent update of the templates. So it seems that it (so far) regularly reappears when updating the templates via the GUI updater. The fix is the same: start the templates manually and let them run for a minute, then shut them down and the issue is gone for subsequent Whonix AppVM and DVM starts. Maybe the updater should let templates "simmer" for ~10 seconds after updating before shutting them down? It could be that this is basically an updater bug.

**Comment by marmarek** [comment]
> Maybe the updater should let templates "simmer" for ~10 seconds after updating before shutting them down?

That's a reasonable idea. In practice it should wait for the `man-db.service` to complete, not just 10s.

As for disabling, I see there is `man-db.timer` that is set "daily", so theoretically it isn't just after an update. Maybe this timer (not the service itself) should be limited to start only in template/standalone in qubes?

**Comment by adrelanos** [comment]
UndeadDevel:
>> I don't have safety concerns here.
> 
> Okay, so I could do `systemctl --user mask man-db.service` in `whonix-ws-16-dvm` and it won't impact anonymity?

I don't have safety concerns here.

**Comment by adrelanos** [comment]
> As for disabling, I see there is `man-db.timer` that is set "daily", so theoretically it isn't just after an update. Maybe this timer (not the service itself) should be limited to start only in template/standalone in qubes?

Yes.

**Comment by UndeadDevel** [comment]
> As for disabling, I see there is man-db.timer that is set "daily", so theoretically it isn't just after an update.

You're right; the issue reappeared today without any whonix updates in between. Limiting the timer to template / standalone sounds good; `systemctl status man-db.service` shows that it was triggered by the timer.

Unfortunately my command to disable the service only for disposables doesn't work (unlike with tracker3 for other DVMs, where it did), so I'll just have to live with it until this is fixed or maybe it will disappear when I switch to 4.2.
