### ISSUE TITLE
u2f/ctap: write a tool for managing key handles

### ISSUE THREAD

**Issue by woju** [QubesOS/qubes-issues#8533]
Right now user can't set the policy, because there is nowhere to get the key handle from.

One of the options would be to have a qrexec call to dom0 to set the policy automatically (or with confirmation). A simpler to implement one would be to extract the handle from syslog.

**Comment by ben-grande** [comment]
Is this fixed with `policy.RegisterArgument +u2f.Authenticate`?

**Comment by DemiMarie** [comment]
@ben-grande yup, this was fixed long ago (I think before R4.0).
