### ISSUE TITLE
Virtual DNS Fails with manual sys-net restart

### ISSUE THREAD

**Issue by andrew-drogalis** [QubesOS/qubes-issues#8535]
### Qubes OS release
V4.2 rc3

### Brief summary

Using Debian Disposable templates, the virtual DNS in all qubes doesn't work once the sys-net & sys-firewall are manually restarted.

Once an update occurs in the template and the new qubes update restart process takes place, the error is fixed and it works normally.

### Steps to reproduce
In sys-net & sys-firewall with a disposable Debian template, shut down both qubes and restart. The DNS request will fail in the sys-firewall.

### Expected behavior
DNS requests work as expected with a manual sys-net & sys-firewall restart.

### Actual behavior
DNS requests fail with, "site's DNS address cannot be found."

**Comment by DTsdem** [comment]
I have observed and recreated the same behavior with Qubes 4.1.2 and Fedora 38. When I start the VMs manually, I have no DNS resolution. If I start the last VM in the chain and the dependent VMs from Qubes are started in quick succession, then DNS resolution works.

**Comment by andrew-drogalis** [comment]
This affects Debian minimal templates as well.

**Comment by zatoa** [comment]
I had something that lead me to this GH Issue. It might not be the same but problem or cause though. I am quite new to Qubes and still learning how everything works, I started messing around installing stuff on the fedora template, without realising I had managed to fill up the 10gb default storage. As this is the template used for everything by default it caused a problem.

Everything still worked fine for me except dns :) 

After cleaning up my template and increasing the size slightly all is well.. I'm wondering if its a good idea to have a couple templates one for the sys-* stuff that doesn't really get messed with and another template which is used for dumping software onto. Or perhaps I just need to be aware and keep on top of storage. I wonder what everyone else is doing in regards to splitting up templates.

Anyway, thanks for this great OS, only installed it a few days ago and I can already see this as my daily driver :)

**Comment by andrewdavidwong** [comment]
@zatoa: Welcome to the Qubes community. :)

> I'm wondering if its a good idea to have a couple templates one for the sys-* stuff that doesn't really get messed with and another template which is used for dumping software onto. Or perhaps I just need to be aware and keep on top of storage. I wonder what everyone else is doing in regards to splitting up templates.

It would be better to post this part on the [forum](https://forum.qubes-os.org/) instead (see [issue tracking](https://www.qubes-os.org/doc/issue-tracking/) and [help, support, mailing lists, and forum](https://www.qubes-os.org/support/)).

**Comment by andrew-drogalis** [comment]
Does anyone on the Qubes Team have a simple work around for this? Some command in sys-net to turn the virtual DNS daemon on after start? 

I keep running into this issue and need to restart multiple times before the virtual DNS syncs to sys-firewall.

**Comment by andrew-drogalis** [comment]
I believe this has been resolved. If anyone has the issue still, please comment, otherwise I will close.
