### ISSUE TITLE
Devices widget: Label recently-connected devices as "NEW"

### ISSUE THREAD

**Issue by jamke** [QubesOS/qubes-issues#8543]
### The problem you're addressing (if any)

Search for new devices in the devices widget can be easy and reliable.
Currently it is not easy and the chance of mistake, selection of wrong device, is high.

This can lead to a security leak in case the USB device is a USB-Ethernet connector or other network device connected to vault or any offline qube by mistake.

**The most common user case:**
* User inserts USB device in USB slot
* User opens devices widget
* User manually search among devices (block or not) for the new just-inserted device.

**This user case has 2 problems:**
1. User has to manually  search though the list reading everything
2. The chance of mistake, selection of wrong device, is high.

### The solution you'd like

How about showing some label or icon "NEW" near device name in the list that
* was not show in the previous time widget was open, and
* was inserted in the last, let's say, 10 minutes.

The device should stay NEW after being shown for the first time for some small time like a minute to prevent it from loosing NEW icon after opening the widget menu fast twice.

Also connecting device to any qube should instantly make the device not NEW.

## The value to a user, and who that user might be

It should cover the most common case: user inserts device (block device or not) and tries to connect it somewhere. He will instantly find the connected device. And no spoofing is possible if the system can process events of connections and disconnections.

When I think about it, I do not know why isn't it a case in all OSes yet.

**Comment by alimirjamali** [comment]
I am working on this. Bellow is the screenshot of the patch (so far).

I have to decide if the 10 minute timeout is OK or is too much. I personally prefer it to be shorter. And also decide if the timeout has to be configurable; perhaps by adding a special feature key to the host.

![NEW_DEVICE](https://github.com/QubesOS/qubes-issues/assets/5407317/be62ddf8-fe81-49f9-9090-b8c82711eb40)

**Comment by jamke** [comment]
Thank you for addressing my proposal! I was not expecting it to be implemented anytime soon, nice surprise.

About timeout choosing problem, and your opinion that 10 minutes can be too big. I kind of agree and have another idea.

How about having small timeout like 1 minute - show NEW red label and after 1 minute just show time if was connected for the last time, something like 3 min ago, or 5 hours ago and so on? The color should be more neutral obviously, like gray.
The devices that were available from the boot can be marked since boot or have nothing.
The gray color will make it look not dragging attention too much and everything would be informative and great.
