### ISSUE TITLE
builderv2 does not ensure that git submodules are populated during build

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#8548]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

R4.2

### Brief summary

The v2 builder does not ensure that the git submodules are populated during the build.  This breaks anything that uses Meson subprojects, which requires that the submodules be present for the code to build.

### Steps to reproduce

Try to build https://github.com/QubesOS/qubes-gui-agent-wayland.git (branch `for-review`) with builderv2 for Debian bookworm.

### Expected behavior

Succeeds

### Actual behavior

Fails because `subprojects/wlroots` is empty at the time that actual `meson configure` command is run.  Meson requires that subprojects be located in sub-folders of `subprojects/` and Debian has no wlroots 0.16 package.

**Comment by marmarek** [comment]
I don't think that's the issue you really see. Take a look at `artifacts/source/gui-agent-wayland/subprojects/wlroots`, is it empty too? In fact, I think you don't need to list submodules in `.qubesbuilder` at all (it's necessary if you'd use upstream tarball, not automatic one from git sources).

**Comment by DemiMarie** [comment]
> I don't think that's the issue you really see. Take a look at `artifacts/source/gui-agent-wayland/subprojects/wlroots`, is it empty too?

Yup.

> In fact, I think you don't need to list submodules in `.qubesbuilder` at all (it's necessary if you'd use upstream tarball, not automatic one from git sources).

Oops!  I have a script that does cross-VM git pushes (very useful for local development), but that requires disabling git fetching (which would fail), and that script didn’t call `git submodule update --init --recursive`.  PEBKAC.
