### ISSUE TITLE
Qubes Update tool immediately crashes when launched

### ISSUE THREAD

**Issue by andrew-drogalis** [QubesOS/qubes-issues#8549]
### Qubes OS release
V4.2 rc3

### Brief summary
Clicking on the Qubes Update Tool in the menu cause the Qubes Update Dialog to flash and then crash.

### Steps to reproduce
Click the Qubes Update Tool in the Qubes Menu.

### Expected behavior
Qubes Update Tool opens as normal.

### Actual behavior
A crash occurs causing the dialog to close.

**Comment by andrew-drogalis** [comment]
Checking for updates works fine and clicking the update icon in the system tray works fine. Only an error with the manual click in start menu.

**Comment by Szewcson** [comment]
It start to happening after today's dom0 update.

**Comment by marmarek** [comment]
Can you start `qubes-update-gui` from a terminal and show the result?

**Comment by Szewcson** [comment]
Same result, no logs in console.

**Comment by noskb** [comment]
[This commit](https://github.com/QubesOS/qubes-desktop-linux-manager/pull/170/commits/8a6e5ea8fd6fe61580830ef0e6ed0bfe6053329f#diff-60a0fd34bff9c057b9962a160d4feefcdc78100a8f1980f1ddfec3443f8ab5faR61-R62) seems to have caused the updater to exit if none of the qubes marked as available for updating. So it should open when marked manually:
`qvm-features dom0 updates-available 1`

**Comment by andrewdavidwong** [comment]
Here is a forum post containing a workaround that others report works for them:

https://github.com/QubesOS/qubes-issues/issues/8549
