### ISSUE TITLE
/etc/login.defs configuration error on dist-upgrade to debian 12 bookworm

### ISSUE THREAD

**Issue by p1llule** [QubesOS/qubes-issues#8559]
### Qubes OS release
4.1

### Brief summary
Upon upgrading my debian templates to bookworm I noticed theses errors :

> configuration error - unknow item 'NONEXISTENT' (notify administrator)
> configuration error - unknow item 'PREVENT_NO_AUTH' (notify administrator)

I do not know why since its seems valid and documented entries.

A side effect is that If you rely on the command 'groupmems', eg by using the following idiom to target the default user on salt :

`{% set user = salt.cmd.run('groupmems -l -g qubes') %}`

Then your files will not compile anymore.

### Steps to reproduce

Upgrade to bookworm.

$ groupmems -lg qubes

### Expected behavior

No 'configuration errors'.

### Actual behavior

'Configuration errors' affecting numerous core commands.

**Comment by p1llule** [comment]
Debian seems aware of the bug:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1038861

**Comment by p1llule** [comment]
I grepped in the qubes's Salt formulas and the idiom :

`{% set user = salt.cmd.run('groupmems -l -g qubes') %}` 

seems to not be used anymore.

So since:
1. Qubes does not rely on this anymore
2. The bug is upstream to debian and shadow-maint

It seems it is not a qubes problem. ;)

by the way if another user rely on this for its formulas, a simple fix is to update to this:

`{% set user = salt.cmd.run('groupmems -l -g qubes 2> /dev/null ') %}`

Or to drop it totally and to hardcode to 'user'. Commentaries on the question will be appreciated.

**Comment by andrewdavidwong** [comment]
> So since:
> 
> 1. Qubes does not rely on this anymore
> 2. The bug is upstream to debian and shadow-maint
> 
> It seems it is not a qubes problem. ;)

Thank you for performing this diagnosis and providing this information. Closing as "not our bug" (the Qubes OS Project does not develop the software that is causing this bug). If anyone believes this resolution is a mistake, please leave a comment, and we'll be happy to take another look. Thank you.
