### ISSUE TITLE
ISO download issue

### ISSUE THREAD

**Issue by mdziczkowski** [QubesOS/qubes-issues#8563]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

R4.2.0-rc3-x86_64

### Brief summary

I tryed to download the ISO from the official website using the `wget` command.

The download started normally, but after some time it got suddenly interrupted with the `(Connection reset by peer)` error.

**NOTICE** I do not exclude that it may be a temporary issue, but for any case I decided to let you knw about it.

### Steps to reproduce

Try to download the ISO using 'wget'

### Expected behavior

Normal download

### Actual behavior

As described

### NOTICES

1. Following `wget` parameters are in effect:
- `--continue` - to resume interrupted download
- `--ignore-length` - to ignore length related issues

2. Because the download was multiple times interrupted thru the error and I had manually resumed it, the previously downloaded parts were marked thru the "+" character

3. Mentioned times in timestamps are meant in the CEST timezone

## Console logs

```
wget https://ftp.qubes-os.org/iso/Qubes-R4.2.0-rc3-x86_64.iso
--2023-10-03 18:09:06--  https://ftp.qubes-os.org/iso/Qubes-R4.2.0-rc3-x86_64.iso
Resolving ftp.qubes-os.org (ftp.qubes-os.org)... 147.75.102.29, 2604:1380:4601:c500::1
Connecting to ftp.qubes-os.org (ftp.qubes-os.org)|147.75.102.29|:443... connected.
HTTP request sent, awaiting response... 206 Partial Content
Length: 6320017408 (5,9G), 1699517853 (1,6G) remaining [application/octet-stream]
The sizes do not match (local 4620499555) -- retrieving.

--2023-10-03 18:09:07--  https://ftp.qubes-os.org/iso/Qubes-R4.2.0-rc3-x86_64.iso
Connecting to ftp.qubes-os.org (ftp.qubes-os.org)|147.75.102.29|:443... connected.
HTTP request sent, awaiting response... 206 Partial Content
Length: 6320017408 (5,9G), 1699517853 (1,6G) remaining [application/octet-stream]
Saving to: ‘ftp.qubes-os.org/iso/Qubes-R4.2.0-rc3-x86_64.iso’

83% [+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++=========>                 ] 5.290.817.776 1,16MB/s   in 5m 5s  

2023-10-03 18:14:12 (2,10 MB/s) - Read error at byte 5290817776/6320017408 (Connection reset by peer).
```

**Comment by alimirjamali** [comment]
@mdziczkowski Did you manage to download the ISO? It should have been a temporal Network issue which might not be relevant anymore and is solved by now.

Please also note that you could always use `wget --continue` to resume partial downloads.

**Comment by mdziczkowski** [comment]
Do

> @mdziczkowski Did you manage to download the ISO? It should have been a temporal Network issue which might not be relevant anymore and is solved by now.
> 
> Please also note that you could always use `wget --continue` to resume partial downloads.

Download test in progress

**Comment by mdziczkowski** [comment]
it seem it's partially working. It would be a good idea if more people could check it as well that more data could become collected to solve this issue 😉

**Comment by alimirjamali** [comment]
@mdziczkowski Thank you very much for the feedback. Please be assured that both the Qubes OS core team as well as 3rd party individuals will monitor the health of download/update mirrors and improve them as much as possible.

@andrewdavidwong I believe this issue could be closed for the time as solved since it appears to be fixed. Issue No. #9396 has more technical details on monitoring and improving the health of download/update mirrors.

I will make a PR to improve the documentation and mention the possibility of using `--continue` option for wget to mitigate against temporal network issues. Since some issues might be related to network nods between Qubes OS infrastructure and user which are beyond control of Qubes OS project.

**Comment by mdziczkowski** [comment]
I would like to propose to keep it open because there is more monitoring required and there is a possibility that the issue could temporary have fixed itself and that it may re-occur

**Comment by alimirjamali** [comment]
I removed my assignment from this issue since it is more suited for people who are managing the Qubes infrastructure.

Related issues for follow-ups: #5458, #9396

**Comment by marmarek** [comment]
I don't think this one is actionable on our side - we have no influence over reliability of internet connection of future users. There are several mirrors available exactly to allow mitigating some of the issues.
