### ISSUE TITLE
Salt install package via UpdateVM uses repos from host not from vm

### ISSUE THREAD

**Issue by feskehau** [QubesOS/qubes-issues#8566]
### Qubes OS release
Qubes OS 4.2-rc3

### Brief summary
Installing a package through salt, in a qube that is isolated and does not have a NetVM uses repositories from dom0.

dom0 - Fedora 37.
UpdateVM (sys-firewall) - Fedora 38
Qube to install package in (template-sys-usb-crypt) - Fedora 38

Update tool tries to fetch the relevant package from Fedora 37 and Qubes Host repos. 

### Steps to reproduce
Install Qubes 4.2-rc3.
Clone fedora-38-minimal to a isolated TemplateVM without NetVM.
Use salt to install package, ex qubes-usb-proxy.
Install fails.

**install.sls**
```
$ cat install.sls 
installed:
  pkg.installed:
    - pkgs:
      - qubes-usb-proxy
[root@dom0 sys-usb-crypt]# 
```

**Salt install uses the wrong repos**
```
$ sudo qubesctl --target template-sys-usb-crypt state.sls sys-usb-crypt.install saltenv=user
[WARNING ] 'version' argument will be ignored for multiple package targets
[ERROR   ] Command 'systemd-run' failed with return code: 1
[ERROR   ] stdout: Running scope as unit: run-redc12793c16a47368f2a45a8dc83471c.scope
Using sys-firewall as UpdateVM to download updates for Dom0; this may take some time...
0 files removed
Fedora 37 - x86_64                               26 MB/s |  82 MB     00:03    
Fedora 37 - x86_64 - Updates                     24 MB/s |  40 MB     00:01    
Qubes Host Repository (updates)                 4.6 MB/s | 2.7 MB     00:00
No match for argument: qubes-usb-proxy
Error: Unable to find a match: qubes-usb-proxy
<Redacted output>
```

### Expected behavior
Expected the update tool through UpdateVM to use the recieving Qubes repos (Fedora 38 and Qubes VM repositories). 

### Actual behavior
Install fails since it to fetch the relevant package from incorrect repos, Fedora 37 and Qubes Host repos.

**Comment by marmarek** [comment]
You need also `--skip-dom0` option, otherwise `state.sls` is applied to dom0 and to VMs specified in --targets option.
Alternatively, more elegant option is to create sys-usb-crypt.top file and use that:
```
base:
  template-sys-usb-crypt:
  - sys-usb-crypt.install
```
`qubesctl top.enable sys-usb-crypt.top`

**Comment by feskehau** [comment]
Thanks:) To me that was quite a surprise that setting targets did not exclude dom0.
