### ISSUE TITLE
Firefox does not start on 4.2-rc3 after upgrading template

### ISSUE THREAD

**Issue by feskehau** [QubesOS/qubes-issues#8571]
### Qubes OS release
4.2-rc3

### Brief summary
As of October 6th:
Firefox on Fedora-38-xfce does not start when selecting from app menu, works if started directly in VM terminal with command `$ firefox`. Noticed earlier today, had to reinstall to verify.

Suspect its the dbus or .desktop change:
https://src.fedoraproject.org/rpms/firefox/c/b85953896b4c0099084baa03c64ecd4aeb52d0c9?branch=rawhide
```
1121 1121 | %changelog
1122 | +             * Fri Oct 06 2023 Alessandro Astone <ales.astone@gmail.com> - 118.0.1-7
1123 | +             - Don't include -x11 and -wayland desktop files in the main package (rhbz#2242523)
1124 | +
1122 1125 | * Fri Oct 6 2023 Martin Stransky <stransky@redhat.com>- 118.0.1-6
1123 1126 | - Removed DBusActivatable flag from desktop file as it crashes KDE (rhbz#2242454).
```

Invalid bus name firefox:
```
[user@dom0 ~]$ sudo qvm-run -q -a -p --service -- personal qubes.StartApp+firefox
Traceback (most recent call last):
  File "/etc/qubes-rpc/qubes.StartApp", line 39, in <module>
    main(sys.argv)
  File "/etc/qubes-rpc/qubes.StartApp", line 33, in main
    launch(os.path.join(raw_volume, f))
  File "/usr/lib/python3.11/site-packages/qubesagent/xdg.py", line 106, in launch
    proxy = bus.get_object(service_id, object_path)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/dbus/bus.py", line 237, in get_object
    return self.ProxyObjectClass(self, bus_name, object_path,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/dbus/proxies.py", line 241, in __init__
    _dbus_bindings.validate_bus_name(bus_name)
ValueError: Invalid bus name 'firefox': must contain '.'
```

### Steps to reproduce
1. Install Qubes 4.2-rc3
2. Upgrade dom0 and all templates
3. Try starting firefox using app menu
4. Firefox wont work

### Expected behavior
Expected firefox to start.

### Actual behavior
VM boots, firefox does not start.
If vm already booted, firefox does not start.

**Comment by marmarek** [comment]
In fact the changelog entries you cited are about _fix_ for this issue. Unfortunately, the version 118.0.1-6 or 118.0.1-7 isn't in the repository yet. It's still building: https://koji.fedoraproject.org/koji/buildinfo?buildID=2302654

Fedora bug report: https://bugzilla.redhat.com/show_bug.cgi?id=2242454
Workaround in Qubes: https://github.com/QubesOS/qubes-core-agent-linux/pull/463

**Comment by GWeck** [comment]
Thias also happens with qubes based on Fedora 38 under Qubes R4.1.2. Qubes based on Fedora 37 still start Firefox correctly via the menu.

**Comment by rustybird** [comment]
Repost [from the forum](https://forum.qubes-os.org/t/last-template-fedora38-update-broke-firefox/21283/8):

> To fix the launcher problem right now, people can remove the line `DBusActivatable=true` in `/usr/share/applications/firefox.desktop` on their Fedora TemplateVM.
