### ISSUE TITLE
Shutting down or rebooting dom0 while VMs are paused takes a very long time

### ISSUE THREAD

**Issue by UndeadDevel** [QubesOS/qubes-issues#8580]
### Qubes OS release
4.1.2

### Brief summary
When shutting down or rebooting QubesOS while some VMs are paused, the process hangs for a long time (first there is a stop job running for the full 3 mins and then dracut hangs because it can't umount old-root), so shutdown/reboot take >3 mins longer than usual.

If I unpause all VMs beforehand this doesn't happen. I have added autostart commands that will unpause relevant VMs automatically on shut down / reboot / logout etc and that fixes the problem, but I feel like this should be handled by the OS. The best solution would probably be to kill paused VMs shortly after shut down or reboot is triggered. The alternative is to unpause and qvm-shutdown them, but that may not be desired security-wise. It could also be that the real issue lies somewhere else and paused VMs during shutdown merely trigger it, I suppose.

### Steps to reproduce
Pause some VMs and then shut down.

### Expected behavior
System shuts down normally

### Actual behavior
Hangs twice and takes >3 mins longer than usual to shut down

### Related issues ###

may be related to #5987

**Comment by UndeadDevel** [comment]
Still an issue on Q4.2rc5. I solve it by adding triggers in startup menu to unpause my DVMs on restart / shutdown / logout etc.

**Comment by alimirjamali** [comment]
This is easy. `QubesVM.shutdown` function could check via `is_paused` function if the qube is paused and un-pause it prior to shutdown. It will need a small unittest. I will work on it.
