### ISSUE TITLE
`features.check_with_netvm()` checks the subject's features instead of netvm's features

### ISSUE THREAD

**Issue by 1cho1ce** [QubesOS/qubes-issues#8584]
### Qubes OS release

R4.2

### Brief summary

As described in doc:
https://dev.qubes-os.org/projects/core-admin/en/latest/qubes-features.html?highlight=check_with_netvm#qubes.features.Features.check_with_netvm
```
check_with_netvm(feature, default=<object object>)
    Check if the subject’s netvm has the specified feature.
```
`check_with_netvm()` should check the feature of subject's netvm but in fact it checks subject's feature.
Or maybe I'm misunderstanding the purpose of `check_with_netvm()`?

### Steps to reproduce

1. Add this debug print:
```
        print("DBG_check_with_netvm", self, self.netvm, \
              self.features.get('ipv6', False), \
              self.features.check_with_netvm('ipv6', False), \
              self.netvm.features.get('ipv6', False) if self.netvm is not None else None, \
              self.netvm.features.check_with_netvm('ipv6', False) if self.netvm is not None else None)
```
here:
https://github.com/QubesOS/qubes-core-admin/blob/main/qubes/vm/mix/net.py#L248
2. Create test qube `test-vm` connected to netvm without IPv6 enabled (for example `sys-firewall`) and enable IPv6 for `test-vm`:
`qvm-features test-vm ipv6 1`
3. Reboot and check the debug output.

### Expected behavior

`self.features.check_with_netvm()` should check the features of `sys-firewall`
Expected output:
`DBG_check_with_netvm test-vm sys-firewall 1 False False False`

### Actual behavior

`self.features.check_with_netvm()` checks the features of `test-vm`
Actual output:
`DBG_check_with_netvm test-vm sys-firewall 1 1 False False`

**Comment by 1cho1ce** [comment]
Based on source code it's searching for the feature of this starting domain and all its netvms upstream.
I guess the right description for this function would be something like:

> Check if the subject or any of the subject’s upstream netvm has the specified feature.

**Comment by marmarek** [comment]
Yes, those check_with_* functions are meant to find in a feature with fallback to specific direction (template, netvm). Indeed the documentation is wrong here.
