### ISSUE TITLE
Copy to Other VM does not work in Nautilus with files that come from Recents

### ISSUE THREAD

**Issue by marmarta** [QubesOS/qubes-issues#8589]
### Qubes OS release
r4.1 (probably 4.2 too)

### Brief summary

Copy to Other VM does not work in Nautilus with files that come from Recents

### Steps to reproduce

Open nautilus, open Recents tab, select a file, right click -> Copy to Other VM - > result: nothing happens

### Expected behavior
Qubes RPC policy window appears.

### Actual behavior
Nothing happens. journalctl log:
```
Oct 10 16:25:46 developmentn nautilus[77800]: Traceback (most recent call last):
Oct 10 16:25:46 developmentn nautilus[77800]:   File "/usr/share/nautilus-python/extensions/qvm_copy_nautilus.py", line 36, i>
Oct 10 16:25:46 developmentn nautilus[77800]:     pid = GLib.spawn_async(cmd)[0]
Oct 10 16:25:46 developmentn nautilus[77800]:           ^^^^^^^^^^^^^^^^^^^^^
Oct 10 16:25:46 developmentn nautilus[77800]: TypeError: gi._gi.spawn_async: first argument must be a sequence of strings
```

Looks like the cmd object there has None instead of actual file path.

**Comment by alimirjamali** [comment]
PR Submitted

Review priority: low

I will make a PR for `qvm_convert_img_nautilus.py` and `qvm_convert_pdf_nautilus.py` shortly. It might be necessary to deal with Network files (e.g. `smb://`) in the future.
