### ISSUE TITLE
New Qubes Manager template update window doesnt show details

### ISSUE THREAD

**Issue by TNTBOMBOM** [QubesOS/qubes-issues#8591]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

4.2

### Steps to reproduce/Actual behavior

- Open Qubes Manager
- Go to any template
- Press on the update button
- There is no details:

![details?](https://github.com/QubesOS/qubes-issues/assets/11895339/35e924f0-2b54-4133-b7b8-948a62f54af9)

- Nor asking me if i want to continue or not

### Expected behavior

- The system should display the progress of the update process. If there's an error or a package hash mismatch, the user should be notified.

- Security downside: If the template updates/upgrades by default using '-y' to accept the installation of new updates without asking for a 'yes/no' confirmation, it might be a usability improvement, but it compromises security. If a malicious package with a mismatched hash is encountered and '-y' is used, the system will automatically accept and install the package.

Displaying the process and asking for confirmation are essential. While it might be possible to provide an optional setting where users can have this and use "-y", it should not be the default and/or no way around it from the GUI window.

**Comment by marmarek** [comment]
The messages are included in that area after given template finishes the update. We may include live preview of the messages at later time (https://github.com/QubesOS/qubes-issues/issues/8564), but there is no plans for making it interactive (that's strictly anti-goal of this tool - see #7443).

> * If a malicious package with a mismatched hash is encountered and '-y' is used, the system will automatically accept and install the package.

No, it will not. `-y` does not bypass integrity checks (if you mean apt, then either `--force-yes` or `--allow-unauthenticated` would be needed for that).

Generally, the default update tool is meant to provide as simple experience as possible. If you want to carefully review packages list and accept (or reject) some, you are free to use `apt upgrade` or whichever other command you like directly.

**Comment by andrewdavidwong** [comment]
Related forum thread: https://forum.qubes-os.org/t/r4-2-r4-not-a-friend-of-new-updater-regarding-dom0/21675/
