### ISSUE TITLE
Open dom0 widgets prevent keyboard multimedia keys from working

### ISSUE THREAD

**Issue by palainp** [QubesOS/qubes-issues#8596]
### Qubes OS release

Qubes 4.1 & 4.2-rc3

### Brief summary & Steps to reproduce

Left click on a dom0 panel widget (Qubes Devices, Qubes Domains, Updates, Clipboard, etc.) and leave the list opened, will deny usage of multimedia keys (screen brightness ajustment, volume control, etc.),  on my laptop (Hp Elitebook).
It does not when I left click on the network widget (I didn't tried with another AppVM controlled panel widget)

### Expected behavior

I can use the multimedia keys (e.g. change the brightness or volume).

### Actual behavior

I have to close the roll list of the widget before being able to use multimedia keys.

**Comment by palainp** [comment]
After a quick test it was already present on 4.1.

**Comment by andrewdavidwong** [comment]
This is similar to #3898.

**Comment by DemiMarie** [comment]
This will be switched by switching to Wayland in dom0/GUI qube (and not before).

**Comment by marmarek** [comment]
> This is similar to #3898. I'm guessing the diagnosis and resolution will be the same, but I'll wait for a dev opinion.

Yes, that's how Xfce (intentionally or not) behaves, nothing Qubes-specific here.

**Comment by andrewdavidwong** [comment]
Closing as "not our bug" (the Qubes OS Project does not develop the software that is causing this bug). If anyone believes this resolution is a mistake, please leave a comment, and we'll be happy to take another look. Thank you.

Related FAQ: [Why don’t you fix upstream bugs that affect Qubes OS?](https://www.qubes-os.org/faq/#why-dont-you-fix-upstream-bugs-that-affect-qubes-os)
