### ISSUE TITLE
Qubes Manager crtical error when updating initial memory of appVM

### ISSUE THREAD

**Issue by kennethrrosen** [QubesOS/qubes-issues#8598]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
4.2.0-rc3

### Brief summary
Changing initial memory in fedora-38 AppVM throws an error.

### Steps to reproduce
Attempt t change initial memory in qubes settings of an appVM

### Expected behavior
Changes are applied.

### Actual behavior
```
Whoops. A critical error has occurred. This is most likely a bug in Qubes Manager.

TypeError: disconnect() failed between 'currentIndexChanged' and all its connections
at line 295
of file /usr/lib/python3.11/site-packages/qubesmanager/settings.py.

----
line: self.netVM.currentIndexChanged.disconnect()
func: apply
line no.: 295
file: /usr/lib/python3.11/site-packages/qubesmanager/settings.py
```

**Comment by andrewdavidwong** [comment]
> Changing initial memory in upgraded-in-place fedora-38 AppVM throws an error.

AppVMs cannot be upgraded in-place. Did you mean "template"?

**Comment by kennethrrosen** [comment]
Updated. These are fedora-38 appvms, updated in-place from fedora-37. There's a separate issue on updating templates here: https://github.com/QubesOS/qubes-issues/issues/8599

**Comment by andrewdavidwong** [comment]
As mentioned, AppVMs cannot be upgraded or updated in-place. There is nothing to upgrade or update, since each AppVM gets its root filesystem from its template:

https://www.qubes-os.org/doc/templates/

Rather, it sounds like these AppVMs are based on a *template* that was upgraded in-place from Fedora 37 to 38.

**Comment by kennethrrosen** [comment]
Right, apologies. early morning

**Comment by kennethrrosen** [comment]
I have not experienced this since 4.2.0. If someone else has, please reopen.
