### ISSUE TITLE
Tor Browser Downloader on Whonix-16 WS fails for TB 13.0

### ISSUE THREAD

**Issue by UndeadDevel** [QubesOS/qubes-issues#8602]
### Qubes OS release
4.1.2
Whonix-16 (Qubes-whonix)

### Brief summary
While dispVMs or anon-whonix have no problem downloading the latest TB update (13.0), the template (whonix-ws-16) TB Downloader app fails after saying "Yes" to "Download now?", right after trying to download the gpg signature, with the following error:
```
ERROR: Failed to download: https://www.torproject.org/dist/torbrowser/13.0/tor-browser-linux64-13.0_ALL.tar.xz.asc 
Possible reasons:

- Internet connectivity issue. 
- The download server is down. 
- File size exceeded (endless data attack triggered). 
- Tor Browser Downloader (by Whonix developers) has been broken due to upstream changes. 
Recommendations:
https://www.whonix.org/wiki/Tor_Browser#download_failure 
(Debugging information: curl_status_message: [22] - [HTTP page not retrieved. The requested url was not found or returned another error with the HTTP error code being 400 or above. This return code only appears if -f, --fail is used.])
```

This error comes immediately, so it's not a connectivity issue IMO, as everything before then (including fetching the new version number etc.) works fine and fast. Maybe with the new major version of TB the URL pattern has changed?

### Steps to reproduce
use tor browser downloader app to update TB

### Expected behavior
updates TB

### Actual behavior
fails to update TB...won't even fetch the signature

**Comment by resulin** [comment]
This is a Whonix issue, not a Qubes issue: http://forums.dds6qkxpwdeubwucdiaord2xgbbeyds25rbsgr73tbfpqpt4a6vjwsyd.onion/t/tor-browser-integration/11912/64

It's already fixed but I don't know if it reached all repositories yet.

@andrewdavidwong

**Comment by adrelanos** [comment]
This was resolved by upstream package upgrades as per linked forum discussion.

https://forums.whonix.org/t/tb-updater-is-broken-again-after-13-0-update-is-available/17285

In case there's still issues, not sure we want to keep this ticket open or close.

**Comment by UndeadDevel** [comment]
Confirmed fixed for me, thanks.
