### ISSUE TITLE
Qube failed to start

### ISSUE THREAD

**Issue by grnklod** [QubesOS/qubes-issues#8603]
### Qubes OS release

R4.2

### Brief summary

I've started a new Whonix disposable qube by launching Tor Browser but it failed to start.
Seems like it hung for some reason but there is no related info in logs.
Maybe it has happened because of this:
https://github.com/QubesOS/qubes-issues/issues/7956
Disposable qube is from whonix-ws-17-dvm disposable template based on whonix-workstation-17 template with latest updates and Tor Browser 13 using kernel 6.5.6-2.qubes.fc37.x86_64 with default initial memory 400 MB and 2 VCPUs.
Dom0 has latest updates but is using kernel 6.4.13-1.qubes.fc37.x86_64.

I think this is the second time it happened but I'm not sure and I couldn't reproduce it.

[guest-disp6708.log](https://github.com/QubesOS/qubes-issues/files/12891836/guest-disp6708.log)
[journalctl-disp6708.log](https://github.com/QubesOS/qubes-issues/files/12891837/journalctl-disp6708.log)

**Comment by marmarek** [comment]
What if you increase initial memory? Do you see it using CPU (for example via domains widget) when it's hanging?

**Comment by grnklod** [comment]
I've tried to reproduce it for around 20 times but it didn't happen anymore. Maybe it happened because of some factors like if I started it when system was on high load or it needed to free some memory for it but couldn't.
I'll try to reproduce it some more.

**Comment by grnklod** [comment]
It happened again with Whonix disposable. I've checked the qube RAM/CPU usage and it stayed at 400 MB 99% CPU the entry time until shutdown.
The system wasn't on high CPU or disk load but I had multiple qubes running so entry RAM was used and memory balancing should've been used.
This time it hung earlier but still no relevant info (for me at least):
[guest-disp5413.log](https://github.com/QubesOS/qubes-issues/files/12908821/guest-disp5413.log)
[journalctl-disp5413.log](https://github.com/QubesOS/qubes-issues/files/12908822/journalctl-disp5413.log)
I'll increase initial memory to 800 MB and see if it'll happen again.

**Comment by grnklod** [comment]
This issue happened again but this time it happened for newly created AppVM based on debian-11 template at first start. It had default 400 MB initial memory as well.
After changing Whonix disposables initial memory to 800 MB this issue didn't happen with them anymore.
It seems that there is an issue that happens only at first VM start after creation if there is not enough initial memory.

**Comment by grnklod** [comment]
I've returned the qubes initial memory to 400 MB quite some time ago and didn't have this issue anymore.
I guess this can be closed as fixed / can't reproduce.
