### ISSUE TITLE
fedora-38 template fails to download

### ISSUE THREAD

**Issue by nathandyer** [QubesOS/qubes-issues#8607]
### Qubes OS release

Qubes 4.1.2, fresh install (with dom0 updates applied, running the default 6.1.43-1-fc32 kernel)

### Brief summary

When I try to download the fedora-38 template, using `sudo qvm-template install fedora-38` (or `sudo qubes-dom-update qubes-template-fedora-38`) from a dom0 Terminal, I receive an error that says:

```
Error: `qubes-template-fedora-38-0:4.0.6-202308241045` download failed
```

(plus some errors above as it attempts to download, notably "Error canonicalizing file: failed to fill whole buffer")

If I repeat the process using other templates (such as `fedora-36`, or `fedora-38-minimal`) it works fine.

### Steps to reproduce

Attempt to download the fedora-38 template with `sudo qvm-template install fedora-38`

### Expected behavior

The template downloads without error.

### Actual behavior

The template fails to download, with the error described above.

**Comment by zenmonkeykstop** [comment]
(Dunno if it's relevant, but the latest (August) fedora-38 package is not present on the kernel.org mirror.)

**Comment by nathandyer** [comment]
I tried again this morning, and everything seems to be OK. The fedora-38 package is now present on the kernel.org mirror. I suspect this was a timing issue more than anything, so closing for now.
