### ISSUE TITLE
Improve qvm-ls options to avoid parsing

### ISSUE THREAD

**Issue by ben-grande** [QubesOS/qubes-issues#8614]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### The problem you're addressing (if any)

Currently, it is lacking some things that `qvm-check` has such as qube class (--template), state ( --paused, --running).

I don't want to duplicate the tools but I believe the following options fits better on qvm-ls:
* --class DispVM|StandaloneVM|AppVM|TemplateVM
* --state Running|Paused
* --no-tags TAG
* --service SERVICE=True/on/False/off
* --features FEATURE=value

This list can be improved, there are countless options.

Currently developers have to parse this information by using `--no-spinner --raw-data` and grep/awk or parse via another language for the qubes class and it's state.
To avoid printing a qube that has a tag, currently I have to `qvm-ls --tags TAG` and then get this output and separate it in multiple `--exclude` options: `qvm-ls --all --exclude QUBE1 --exclude QUBE2 --exclude QUBE3`.

### The solution you'd like

I would like for more use of `--raw-list` with extra option instead of parsing `--raw-data`.
Any disadvantages besides making the `qubesadmin/tools/qvm_ls.py` bigger?

### The value to a user, and who that user might be

Easy way to get a list of qubes with certain characteristics without parsing.

**Comment by alimirjamali** [comment]
It appears that by pure chance, I have already written most of it. It is in [my personal repo](https://github.com/alimirjamali/personal-qubesos/tree/main/qubes-core-admin-client-tt#qvm-ls-tt-tweaks). There are some other features:

- Unix like wildcard support for VM selection (not only for `qvm-ls` but for almost all `qvm-*` utilities).
- Filter option for `--label LABEL,...`
- Filter option for `--based-on TemplateVM,...`
- `--connects-width NETVM`
- `--servicevm <yes|no|both>`
- `--internal <yes|no|both>`
- `--sort COLUMN` option' `--reverse`, `--ignore-case` sub-options
- `--updates-available` to filter to TemplateVMs and StandaloneVMs pending for update

plus some other tweaks I might have forgotten to document.

I always wondered if it is only me who considers them necessary.

**Comment by ben-grande** [comment]
It is not only you.

You miss merging upstream 100% of the PRs that you don't make.

Wayne Gretzky, Michael Scott, Ben.

Please open PRs when you can if you want.

I did not look at your code, but option naming has to change.

--connects-with is not intuitive, there are a lot of types of connections
one qube can make to another such as audiovm and guivm. A better option has
to have netvm as part of the name.

But all of this can be discussed once a PR reaches the Qubes repos.

**Comment by ben-grande** [comment]
Last mail hid the last paragraphs.


connects-with is not intuitive, there are a lot of types of connections

one qube can make to another such as audiovm and guivm. A better option has
to have netvm as part of the name. But all of this can be discussed once a
PR reaches the Qubes repos.
