### ISSUE TITLE
qvm-prefs does not hide defaults if key is specified

### ISSUE THREAD

**Issue by ben-grande** [QubesOS/qubes-issues#8615]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

R4.1

### Brief summary

When specifying `--hide-default` it conflicts with the key specified, printing incorrect information.

### Steps to reproduce

Try to see if qube netvm is set to default or not (the netvm of this qube is the default):
```sh
qvm-prefs QUBE | grep "^netvm\s\+D\s\+" # exit 0 - prints the whole line
qvm-prefs QUBE | grep "^netvm\s\+D\s\+" | awk '{print $3}' # exit 0 - prints netvm but does not fail on pipes depeding on shell options
qvm-prefs --hide-default QUBE | grep netvm   # exit 1 - prints nothing, expected
qvm-prefs --hide-default QUBE netvm  # exit 0 - prints netvm, should not print
qvm-prefs QUBE netvm # exit 0 - prints netvm, this is okay
```
So... how can one know that the netvm of a qube is using the default value for netvm without parsing the output?

### Expected behavior

```sh
qvm-prefs --hide-default QUBE netvm
```
Should fail if netvm is the default.

### Actual behavior

```sh
qvm-prefs --hide-default QUBE netvm
```
Prints the netvm name, even though it is the default value.

**Comment by alimirjamali** [comment]
PR submitted

**Comment by alimirjamali** [comment]
> Does that mean this also affects 4.2?

Yes. It does. But it is a minor issue
