### ISSUE TITLE
`qubes-dist-upgrade`'s stage2 cannot be restarted after a failure due to non-idempotent font package installation command

### ISSUE THREAD

**Issue by biergaizi** [QubesOS/qubes-issues#8617]
### Qubes OS release
4.1, 4.2

### Brief summary

When attempting to upgrade to Qubes 4.2 using `qubes-dist-upgrade`, if a failure occurs in Stage 2 after `qubes-dom0-update $dnf_opts google-noto-sans-fonts google-noto-serif-fonts` has already been successfully executed, Stage 2 cannot be restarted because `qubes0-dom-update` attempts to install these packages which are already installed. This causes a failure, so the restarted stage 2 upgrade never passes beyond this command.

I discovered and was seriously confused by this trivial problem in the middle of troubleshooting an unrelated upgrade problem that prevents the upgrade of `qubes-release`, much time was wasted.

### Steps to reproduce

1. Run ` qubes-dist-upgrade -r ` on Qubes 4.1
2. Make sure to intentionally cause the package `qubes-release` fails to install in some ways, right after `google-noto-sans-fonts google-noto-serif-fonts` are successfully installed.

### Expected behavior

Rerun `qubes-dist-upgrade -r` after failure to install  `qubes-release` should trigger another attempt to install  `qubes-release`.

### Actual behavior

 `qubes-dist-upgrade -r` is unable to retry `qubes-release` installation, because the previously successful command  `qubes-dom0-update $dnf_opts google-noto-sans-fonts google-noto-serif-fonts` is now failing to rerun the second time because they've already been installed, with the following error messages:

```
# qubes-dist-upgrade -r
WARNING: /!\ MAKE SURE YOU HAVE MADE A BACKUP OF ALL YOUR VMs AND dom0 DATA /!\
-> Launch upgrade process? [y/N] y
---> (STAGE 2) Upgrading 'qubes-release'...
Using sys-firewall as UpdateVM to download updates for Dom0; this may take some time...
Qubes OS Repository for Dom0                                              0.0  B/s |   0  B     00:00    
Errors during downloading metadata for repository 'qubes-dom0-cached':
  - Curl error (37): Couldn't read a file:// file for file:///var/lib/qubes/updates/repodata/repomd.xml [Couldn't open file /var/lib/qubes/updates/repodata/repomd.xml]
Error: Failed to download metadata for repo 'qubes-dom0-cached': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
```

I could reproduce the same problem by manually running the command in question in a shell (I used `echo` to print the variable ` $dnf_opts`):

    qubes-dom0-update --best --allowerasing --enablerepo=qubes-dom0-current-testing google-noto-sans-fonts google-noto-serif-fonts

To allow the upgrade to continue, I used following workaround by making this change:

```patch
-        qubes-dom0-update $dnf_opts google-noto-sans-fonts google-noto-serif-fonts
+        qubes-dom0-update --action=reinstall $dnf_opts google-noto-sans-fonts google-noto-serif-fonts
```

But it's not safe to upstream, as this causes the opposite problem - `--action=reinstall` fails if the packages were not originally installed. With the root cause clear, a better workaround for users for now would be deleting `google-noto-sans-fonts google-noto-serif-fonts` via dnf.

### Notes

In my case, the particular errors I encountered during the original upgrade were:

```
[root@dom0 ~]# qubes-dist-upgrade -r
WARNING: /!\ MAKE SURE YOU HAVE MADE A BACKUP OF ALL YOUR VMs AND dom0 DATA /!\
-> Launch upgrade process? [y/N] y
---> (STAGE 2) Upgrading 'qubes-release'...
Using sys-firewall as UpdateVM to download updates for Dom0; this may take some time...
Qubes OS Repository for Dom0                                              2.9 MB/s | 3.0 kB     00:00    
Qubes OS Repository for Dom0                                              470 kB/s | 2.2 kB     00:00    
Dependencies resolved.
==========================================================================================================
 Package                         Architecture   Version                   Repository                 Size
==========================================================================================================
Installing:
 google-noto-sans-fonts          noarch         20181223-7.fc32           qubes-dom0-cached         8.5 M
 google-noto-serif-fonts         noarch         20181223-7.fc32           qubes-dom0-cached         9.8 M

Transaction Summary
==========================================================================================================
Install  2 Packages

Total size: 18 M
Installed size: 73 M
Is this ok [y/N]: y
Downloading Packages:
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                  1/1 
  Installing       : google-noto-serif-fonts-20181223-7.fc32.noarch                                   1/2 
  Installing       : google-noto-sans-fonts-20181223-7.fc32.noarch                                    2/2 
  Running scriptlet: google-noto-sans-fonts-20181223-7.fc32.noarch                                    2/2 
  Verifying        : google-noto-sans-fonts-20181223-7.fc32.noarch                                    1/2 
  Verifying        : google-noto-serif-fonts-20181223-7.fc32.noarch                                   2/2 

Installed:
  google-noto-sans-fonts-20181223-7.fc32.noarch       google-noto-serif-fonts-20181223-7.fc32.noarch      

Complete!
Using sys-firewall as UpdateVM to download updates for Dom0; this may take some time...
*** ERROR while receiving updates:
Error canonicalizing /var/tmp/qubes-updates-tmpzgvfbkal.UNTRUSTED/qubes-release-4.2-0.3.fc32.noarch.rpm
--> if you want to use packages that were downloaded correctly, use dnf directly now
--> otherwise, you can use --clean to remove left-over packages
```

Reading the systemd log revealed that:

```
qrexec-policy-daemon[107193]: Error canonicalizing file: No key available!
qrexec-policy-daemon[107193]: Error canonicalizing /var/tmp/qubes-updates-tmpzgvfbkal.UNTRUSTED/qubes-release-4.2-0.3.fc32.noarch.rpm
qubes.ReceiveUpdates+-sys-firewall[107195]: Error canonicalizing /var/tmp/qubes-updates-tmpzgvfbkal.UNTRUSTED/qubes-release-4.2-0.3.fc32.noarch.rpm
```

For some reason, the Qubes 4.2 keys were missing. I don't know if this was caused by my own mistake (incomplete stage1?) or a bug. The workaround is to run:

    rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-qubes-4.2-primary

But I also noticed that this is the same problem as [posted by Qubes forum user szz9pza](https://forum.qubes-os.org/t/qubes-os-4-2-0-rc2-is-available-for-testing/20635/24), so perhaps it was not just a coincidence? Should a separate issue be created for this?

**Comment by andrewdavidwong** [comment]
> Reading the systemd log revealed that:
> 
> ```
> qrexec-policy-daemon[107193]: Error canonicalizing file: No key available!
> qrexec-policy-daemon[107193]: Error canonicalizing /var/tmp/qubes-updates-tmpzgvfbkal.UNTRUSTED/qubes-release-4.2-0.3.fc32.noarch.rpm
> qubes.ReceiveUpdates+-sys-firewall[107195]: Error canonicalizing /var/tmp/qubes-updates-tmpzgvfbkal.UNTRUSTED/qubes-release-4.2-0.3.fc32.noarch.rpm
> ```
> 
> For some reason, the Qubes 4.2 keys were missing. I don't know if this was caused by my own mistake (incomplete stage1?) or a bug. The workaround is to run:
> 
> ```
> rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-qubes-4.2-primary
> ```
> 
> But I also noticed that this is the same problem as [posted by Qubes forum user szz9pza](https://forum.qubes-os.org/t/qubes-os-4-2-0-rc2-is-available-for-testing/20635/24), so perhaps it was not just a coincidence? Should a separate issue be created for this?

Yeah, it seems like that should probably be a separate issue.
