### ISSUE TITLE
Disposable VMs should inherit the netVM from the AppVM which created it

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#862]
**Reported by marmarek on 28 May 2014 23:54 UTC**
https://groups.google.com/d/msg/qubes-users/PR8SZcxicas/UL7qpurFxssJ

Migrated-From: https://wiki.qubes-os.org/ticket/862

**Comment by qjoo** [comment]
I'm still getting a networked dispvm even after creating it from a offline appvm? (in 3.0-rc1)

**Comment by marmarek** [comment]
On Sun, May 03, 2015 at 04:22:46AM -0700, qjoo wrote:
> I'm still getting a networked dispvm even after creating it from a
> offline appvm? (in 3.0-rc1)

Are you sure that the DispVM really have network access? Indeed I see
'eth0' there in such case, but it isn't connected anywhere.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?
