### ISSUE TITLE
Builderv2 can't build linux kernel because lacking qubes-kernel-vm-support in chroot

### ISSUE THREAD

**Issue by Augsch123** [QubesOS/qubes-issues#8620]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

R4.2

### Brief summary

I'm trying to use builderv2 and Qubes executor to build linux-kernel-latest package. But the `build` stage fails because lack of 
dependency: `[executor:qubes:disp2844] output: No matching package to install: 'qubes-kernel-vm-support'`.

I met similar things before when using the legacy builder. My workaround used to be manually adding qubes repos to chroot environment's dnf repo list. But I can't continue using the workaround, because with Qubes executor, the chroot is established inside a disposable qube.

### Steps to reproduce

1. Setup qubes builderv2 and make it use Qubes executor according to README in builderv2's repo.
2. Copy example-configs/qubes-os-r4.2-dom0.yml to be builder.yml.
3. Run `./qb -d host-fc37 -c linux-kernel-latest package fetch`
4. Install `rpm-build` and `rpmdevtools` in `qubes-builder-dvm`'s template ( fedora-38 in my case ), because these packages are needed to process the spec files of the kernel, but are not mentioned by the README ( possibly a doc bug )
5. Run `./qb -d host-fc37 -c linux-kernel-latest package prep`
6. Run `./qb -d host-fc37 -c linux-kernel-latest package build`

### Expected behavior
The kernel gets built.

### Actual behavior

```
...
 [executor:qubes:disp2844] output: fedora                                          2.6 kB/s | 6.3 kB     00:02
 [executor:qubes:disp2844] output: updates                                          14 kB/s | 6.2 kB     00:00
 [executor:qubes:disp2844] output: builder-local                                   2.9 MB/s | 3.0 kB     00:00
 [executor:qubes:disp2844] output: Package coreutils-9.1-8.fc37.x86_64 is already installed.
 [executor:qubes:disp2844] output: No matching package to install: 'qubes-kernel-vm-support'
 [executor:qubes:disp2844] output: Not all dependencies satisfied
 [executor:qubes:disp2844] output: Error: Some packages could not be found.
...
```

**Comment by rustybird** [comment]
Take a look at builder v2's `use-qubes-repo` configuration:

https://github.com/QubesOS/qubes-builderv2/blob/b2108667/README.md?plain=1#L699
https://github.com/QubesOS/qubes-builderv2/blob/b2108667/example-configs/builder-devel.yml#L17

> I met similar things before when using the legacy builder. My workaround used to be manually adding qubes repos to chroot environment's dnf repo list.

builder v1 has `USE_QUBES_REPO_VERSION` and `USE_QUBES_REPO_TESTING` make variables for this.

**Comment by Augsch123** [comment]
Thanks @rustybird , I'll close this as this is in fact not a bug.
