### ISSUE TITLE
Missing dependencies to qubes-builder and qubes-infrastructure-mirrors for minimal templates

### ISSUE THREAD

**Issue by ben-grande** [QubesOS/qubes-issues#8624]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

R4.1
Minimal template.
No install recommends / No weak deps.

### Brief summary

Related:
- https://github.com/QubesOS/qubes-infrastructure-mirrors/issues/2
- https://github.com/QubesOS/qubes-issues/issues/8439#issuecomment-1685314203

Although some issues were opened about this, it was not actionable. I want it to change, I can do the commit, just need instructions and please read the questions at the bottom.

Non builtin modules for mirrors:
- aiohttp *
- jinja2 *
- lxml
- setuptools *

Only lxml (python3-lxml) is missing, the others are not listed as dependencies for the mirrors in specific but will be installed when installing [qubes-builderv2#dependencies](https://github.com/QubesOS/qubes-builderv2#dependencies), but they probably should be listed on the mirrors README if it is ever created.

Non builtin modules missing for builder:
- click

Only click (python3-click) is missing.

### Steps to reproduce

Not all modules are listed ot be installed on [qubes-builderv2#dependencies](https://github.com/QubesOS/qubes-builderv2#dependencies).

Try to build mkmetalink and builder.

### Expected behavior

Works to build mkmetalink and builder.

### Actual behavior

Fails to build mkmetalink and builder.

### Contribution

Can I create a mirrors readme and add all the dependencies for it there?

Can I change the builder readme to reference the mirrors to get the correct dependency list to avoid code duplication?

- This is a bug of minimal templates? No, it is a missing dependency, not a package suggestion in debian packaging terms.
- Is it a dependency of the project? Yes.
- Am I requiring the listing of qubes specific packages such as qubes-core-agent-networking, qubes-core-agent-passwordless-root? No. I am only requiring for the missing dependencies for the build to be listed.

**Comment by DemiMarie** [comment]
> Can I create a mirrors readme and add all the dependencies for it there?

Sure, or they can be part of the main `README.md`.  I don’t have a strong opinion there.

> Can I change the builder readme to reference the mirrors to get the correct dependency list to avoid code duplication?
> 
> * This is a bug of minimal templates? No, it is a missing dependency, not a package suggestion in debian packaging terms.
> * Is it a dependency of the project? Yes.
> * Am I requiring the listing of qubes specific packages such as qubes-core-agent-networking, qubes-core-agent-passwordless-root? No. I am only requiring for the missing dependencies for the build to be listed.

I recommend just making a PR for review.
