### ISSUE TITLE
I cant upgrade 2 or more templates at one time with the new GUI upgrade window

### ISSUE THREAD

**Issue by TNTBOMBOM** [QubesOS/qubes-issues#8627]
### Qubes OS release

4.2

### Brief summary

Well before i was able to upgrade multiple templates at one time, each template will has its own upgrading window, but current new GUI window doesnt accept multiple templates upgrade.

### Steps to reproduce

Open two templates and press the upgrade button in the Qubes Manager for each one. You'll find that only the first template will be able to receive the upgrade. If you press the upgrade button for the second template, it will only show you that the first template is in the upgrading process.

### Expected behavior

Upgrading multiple templates in parallel/same time.

### Actual behavior

Not happening.

**Comment by SolarSorcerer** [comment]
I've also observed the issue you're mentioning. To provide a bit of clarity, when you initiate an update using the button within the Qube Manager, it specifically updates only the selected Qube. In contrast, clicking the update icon in the XFCE tray launches the Qubes Updater application, where you have the option to choose multiple Qubes for updating. To streamline this process, it might be more efficient to either eliminate the individual update button in the Qube Manager or adjust its function so that it directs to the Qubes Updater with the particular Qube pre-selected for an update.

**Comment by andrewdavidwong** [comment]
> I've also observed the issue you're mentioning. To provide a bit of clarity, when you initiate an update using the button within the Qube Manager, it specifically updates only the selected Qube. In contrast, clicking the update icon in the XFCE tray launches the Qubes Updater application, where you have the option to choose multiple Qubes for updating. To streamline this process, it might be more efficient to either eliminate the individual update button in the Qube Manager or adjust its function so that it directs to the Qubes Updater with the particular Qube pre-selected for an update.

That's exactly what https://github.com/QubesOS/qubes-issues/issues/6635 is about. It was closed as completed a while back, but it sounds like it may not have been implemented correctly.

-----

This appears to be a [duplicate](https://www.qubes-os.org/doc/issue-tracking/#new-issues-should-not-be-duplicates-of-existing-issues) of an existing issue. If so, please comment on the appropriate existing issue instead. If anyone believes this is not really a duplicate, please leave a comment briefly explaining why. We'll be happy to take another look and, if appropriate, reopen this issue. Thank you.

**Comment by marmarek** [comment]
It can be done if you select multiple templates (with holding ctrl, for example).

**Comment by TNTBOMBOM** [comment]
> It can be done if you select multiple templates (with holding ctrl, for example).

Yeah but if user pressed upgrade button on one template, he cant involve any more after that, how do you solve this? 

(user wont figure out that he should use ctrl+selecting multiple templates then pressing the upgrade button by holy spirit)
