### ISSUE TITLE
Fullscreen is causing out of memory and freeze in dom0

### ISSUE THREAD

**Issue by grnklod** [QubesOS/qubes-issues#8640]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

R4.2

### Brief summary

Watching videos in qube with Firefox window in fullscreen can cause OOM in dom0 which can lead to Xorg kill or complete dom0 freeze.
It happens to me randomly while watching some youtube videos and I don't know what caused this, maybe it was some buffering or something. When the issue happens the RSS memory consumption of Xorg process `/usr/bin/X -core -noreset :0 -seat seat0 -auth /run/lightdm/root/:0 -nolisten tcp vt1 -novtswitch` is increasing without a stop while the tab with video playing is open but if I switch to next open tab in the same window the consumed memory will be released but will begin increasing again if I switch back to tab with video. If I exit the fullscreen mode and enter back this fixes the issue.
I can't reproduce this reliably but it happens much more frequently if I use invidious to watch youtube videos.

The above issue is about uncontrollable increase of memory usage until the dom0 is out of memory but there is also a way to controllable cause dom0 out of memory issue:

### Steps to reproduce

1. Create AppVM based on debian-12 template with firefox-esr.
2. Start firefox in this qube and open some youtube video using invidious for example use this link:
https://yewtu.be/watch?v=_UxndcxIngw
3. Open task manager in dom0.
4. Switch firefox window to fullscreen mode and start playing the video.
5. Now start to skip the video playing time by clicking at some time point on slider.
6. Alt+Tab to task manager in dom0 and observe large increase in Xorg process memory usage after each time skip and if you continue to skip time it'll cause out of memory in dom0.

Related topic on forum:
https://forum.qubes-os.org/t/dom0-crashes-and-abrupt-logouts-traced-to-oom-killer/21609

**Comment by grnklod** [comment]
With disabled display compositing in dom0 Window Manager Tweaks -> Compositor the issue is not happening.

**Comment by marmarek** [comment]
Which kernel version in dom0? And which version of the qubes-core-dom0 package?

**Comment by grnklod** [comment]
Some more logs, this time when oom-killer is called in dom0 instead of complete dom0 freeze.
dom0 journalctl:
[dom0_journalctl_qubes-guid_invoked_oom-killer.log](https://github.com/QubesOS/qubes-issues/files/13079096/dom0_journalctl_qubes-guid_invoked_oom-killer.log)
guid log wen oom-killer started, ending with:
```
shmimage for 0x5c001dc(remote 0x140002b), x: 0, y: 0, w: 1024, h: 512
  do_shm_update for 0x5c001dc(remote 0x140002b), after border calc: x=0, y=0, w=1024, h=512
xside: win 0x5c001dc(0x140002b) type=4 button=1 x=892, y=966
xside: win 0x5c001dc(0x140002b) type=5 button=1 x=984, y=934
shmimage for 0x5c001dc(remote 0x140002b), x: 0, y: 0, w: 1920, h: 512
  do_shm_update for 0x5c001dc(remote 0x140002b), after border calc: x=0, y=0, w=1920, h=512
Obtained 9 stack frames.
XIO:  fatal IO error 104 (Connection reset by peer) on X server ":0.0"
      after 14592 requests (14480 known processed) with 0 events remaining.
Obtained 12 stack frames.
```
[guid.tstvid.oom-killer.log.tar.gz](https://github.com/QubesOS/qubes-issues/files/13079142/guid.tstvid.oom-killer.log.tar.gz)
guid log when I login after oom-killer:
[guid.tstvid.oom-killer-after.log](https://github.com/QubesOS/qubes-issues/files/13079158/guid.tstvid.oom-killer-after.log)



> Which kernel version in dom0? And which version of the qubes-core-dom0 package?
```
[user@dom0 ~]$ uname -r
6.1.57-1.qubes.fc37.x86_64
[user@dom0 ~]$ dnf list installed | grep qubes-core-dom0
qubes-core-dom0.noarch                            4.2.18-1.fc37                     @qubes-dom0-cached
qubes-core-dom0-linux.x86_64                      4.2.14-1.fc37                     @qubes-dom0-cached
qubes-core-dom0-linux-kernel-install.x86_64       4.2.14-1.fc37                     @qubes-dom0-cached
```

**Comment by grnklod** [comment]
I've tried kernel 6.5.8-1.qubes.fc37.x86_64 in dom0 and it has the same issue.
VM kernel was 6.5.8-1.qubes.fc37.x86_64 as well.

**Comment by grnklod** [comment]
Now I've discovered an even worse problem.
If I scroll any web page using mouse or keyboard in fullscreen mode then I have the same issue with large memory consumption and possible dom0 freeze or OOM Xorg kill.
I've tested this in debian-12 with firefox-esr and chromium so this issue exists for chromium as well as firefox.
It seems that Xorg is freeing up the temporary consumed memory after some fixed time interval (around 5 seconds) and if you scroll the web page fast enough during this time interval for it to consume all the dom0 memory so Xorg won't make it in time to free up the used memory then it'll cause OOM.

**Comment by grnklod** [comment]
This problem exist for any GUI window in fullscreen and it's not just an issue with browsers. E.g. if you open dom0 terminal in fullscreen and open Task Manager then Alt+Tab between these two windows repeatedly you'll see the increase in Xorg memory usage to the point that it can cause OOM if you do it quickly enough.

**Comment by marmarek** [comment]
I cannot reproduce the issue neither with dom0 terminal nor with firefox. Maybe it's hardware-specific, for example to some GPU driver? What GPU do you have?

What I tried:
1. Ensure compositing is enabled in window manager tweaks.
2. Open task manager
3. Open dom0 terminal, right click on title bar and go full screen
4. Quickly switch between them
5. Observe Xorg memory usage (for me RSS stayed about 100MB)

Similarly I tried with Firefox ESR in debian-12, playing a video on yewtu.be, in fullscreen (first click fullscreen in the player, and then make the window really fullscreen via title bar menu).

**Comment by grnklod** [comment]
> I cannot reproduce the issue neither with dom0 terminal nor with firefox. Maybe it's hardware-specific, for example to some GPU driver? What GPU do you have?

Maybe it's hardware-specific. I'm using Intel i7-12700H integrated GPU:
```
00:02.0 VGA compatible controller [0300]: Intel Corporation Alder Lake-P GT2 [Iris Xe Graphics] [8086:46a6] (rev 0c)
	Kernel driver in use: i915
	Kernel modules: i915
```
Here's a video as an example of how it looks in my system:

https://github.com/QubesOS/qubes-issues/assets/147809665/ed9b80af-4799-414f-80a4-89e34196162d

**Comment by grnklod** [comment]
Maybe related:
https://bugs.freedesktop.org/show_bug.cgi?id=99807
I've checked with:
`sudo watch -n 1 'grep i915 /proc/2483/maps | wc -l'`
and
`sudo watch -n 1 'pmap -x 2483 | tail -n+2 | sort -n -r -k2 | head -n118 | column -c160'`
And each Alt+Tab generates ~12 `i915 (deleted)` mappings with 9000 KB size which are reclaimed every 10 seconds.

Based on comment in freedesktop bug report:
> The mappings are still in use, when their usage count drops to zero then they are reclaimed.

These deleted mappings are still used by some process (or some process didn't free them cleanly?).
I don't know if it's Qubes related or not. Is there a way to trace the source of these mappings?

**Comment by grnklod** [comment]
I've tried to boot into Qubes OS without Xen like this:
https://github.com/QubesOS/qubes-issues/issues/8574#issuecomment-1751814746
And the issue persists so this issue shouldn't be related to Xen.

I've also tried this Fedora 37 Xfce Live image:
https://download.fedoraproject.org/pub/fedora/linux/releases/37/Spins/x86_64/iso/Fedora-Xfce-Live-x86_64-37-1.7.iso
And it doesn't have this issue.

I've also tried to use `/usr/bin/Xorg` instead of `/usr/bin/X-wrapper-qubes` for a test but it didn't help.

I think this issue should be related to Qubes OS but I don't know how can I trace the issue.

**Comment by grnklod** [comment]
I've installed Fedora 37 Xfce and updated it for a test with the same kernel 6.5.10 and latest packages as in Qubes OS and I don't have this issue there as well.

**Comment by DemiMarie** [comment]
I suspect that this is an XFWM4 bug fixed in a newer version that Qubes OS has not packaged yet.

**Comment by grnklod** [comment]
> I suspect that this is an XFWM4 bug fixed in a newer version that Qubes OS has not packaged yet.

Qubes OS has xfwm4 4.16.1-3 and Fedora 37 has xfwm4 4.16.1-6, based on the changelog and sources the only change between them is the addition of `-DSHOW_POSITION` CFLAG:
https://packages.fedoraproject.org/pkgs/xfwm4/xfwm4/fedora-37.html
https://src.fedoraproject.org/rpms/xfwm4/commits/rawhide
I don't think this would change anything regarding this issue.

**Comment by noskb** [comment]
Perhaps you have configured your system to use the intel DDX driver instead of modesetting? I can reproduce the problem after switching to the intel DDX driver.

**Comment by grnklod** [comment]
> Perhaps you have configured your system to use the intel DDX driver instead of modesetting? I can reproduce the problem after switching to the intel DDX driver.

I have default driver configuration:
```
[user@dom0 ~]$ cat /etc/X11/xorg.conf.d/20-intel.conf 
Section "Device"
    Identifier  "Intel Graphics"
    Driver      "intel"
    Option      "Backlight"  "intel_backlight"
EndSection
```

**Comment by grnklod** [comment]
> That’s the Intel DDX driver, which is known to have problems.

You're right! Removing this config fixed the issue.
I've totally forgot that I've changed it when trying to configure the backlight.
Sorry for the distraction.
