### ISSUE TITLE
Document the switch from iptables to nftables before releasing R4.2

### ISSUE THREAD

**Issue by SvenSemmler** [QubesOS/qubes-issues#8641]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release (if applicable)

R4.2

### Brief summary

From the release notes:

DomU firewalls have completely switched to nftables. Users should add their custom rules to the custom-input and custom-forward chains. ([#5031](https://github.com/QubesOS/qubes-issues/issues/5031), [#6062](https://github.com/QubesOS/qubes-issues/issues/6062)).

It's probably not a good idea to release R4.2 without explicit documentation about the switch and it's consequences. This has lead some RC testers to conclude the ["firewall is leaking" and get very heated in claiming security issues](https://forum.qubes-os.org/t/21125). Technically this is all addressed in the release notes and in pointing out that the firewall is not intended to be relied on to prevent [data leaks](https://www.qubes-os.org/doc/data-leaks/). There is also some [community effort by the same reporter](https://forum.qubes-os.org/t/21612) to start documentation. 

BUT it is easy to see that this will lead to more users being frustrated unless they are explicitly warned in the release notes and announcement and pointed to a documentation page on how to deal with it.

**Comment by andrewdavidwong** [comment]
I think @rapenne-s may be planning to work on this (or something closely-related). Just wanted to flag it here to avoid duplication of effort.

**Comment by rapenne-s** [comment]
I started reworking the Firewall documentation. However, I'll be missing a piece of information to finish it (see #8629 ).

**Comment by andrewdavidwong** [comment]
> I think @rapenne-s may be planning to work on this (or something closely related). Just wanted to flag it here to avoid duplication of effort.

There is now an open PR: https://github.com/QubesOS/qubes-doc/pull/1344

**Comment by UndeadDevel** [comment]
That PR has been merged, so it seems this is completed.
