### ISSUE TITLE
Salt: can't set multiple `menu-items` using `qvm.vm`

### ISSUE THREAD

**Issue by r-cheologist** [QubesOS/qubes-issues#8645]
### Qubes OS release
4.1.2

### Brief summary
Using the following `salt` formula does not work for multiple targeted entries in an app VMs application menue:

```salt
configure app VM:
  qvm.vm:
    - name: myapp
    - present:
      - template: debian-12-minimal
      - label: red
    - features:
      - set:
        - menu-items:
          - qubes-open-file-manager.desktop
          - qubes-run-terminal.desktop
 ```

### Steps to reproduce
Include above in your `salt` setup for `dom0` and run `qubesctl --targets=dom0 state.highstate`.

### Expected behavior
Both entries should appear in `myapp`s application menu.

### Actual behavior
Two entries show up in the application menu, but they read `Application missing in template! (['qubes-open-file-manager.desktop',)` and `Application missing in template! ('qubes-run-terminal.desktop'])`.

Apparently list processing is not working in this context.

With a single entry (no list) the feature setting works just fine.

**Comment by ben-grande** [comment]
Try:
```yaml
 - set:
  - menu-items: "qubes-open-file-manager.desktop qubes-run-terminal.desktop"
```

**Comment by r-cheologist** [comment]
Thanks. That does work indeed. The [documentation](https://github.com/QubesOS/qubes-mgmt-salt-dom0-qvm#id16) is at best confusing, if not misleading...

**Comment by ben-grande** [comment]
> @ben-grande : is there a feature that makes a given `*desktop` file autostart upon starting the VM?

Unspecific to qubes.

Symlink `/usr/share/applications/wanted.desktop` to 
`~/.config/autostart/wanted.desktop`.

**Comment by r-cheologist** [comment]
That I was aware of. Thank you. No qubes-specificity then.
