### ISSUE TITLE
qrexec-policy-graph does not report all services

### ISSUE THREAD

**Issue by ben-grande** [QubesOS/qubes-issues#8648]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

R4.1

### Brief summary

Discussed on the [devel mailing list](https://www.mail-archive.com/qubes-devel@googlegroups.com/msg05325.html)

Policy Graph does not report all services.

### Steps to reproduce

Set a custom RPC service and put a policy in place
```sh
qrexec-policy-graph --include-ask --source SOURCE --target TARGET
qrexec-policy-graph --include-ask --source SOURCE --service SERVICE
```

### Expected behavior

Prints the rule for the configured service

### Actual behavior

Does not print the rule for the configured service.

**Comment by ben-grande** [comment]
@marmarek 

If the policy has the argument `*`, the service can only be referenced to qrexec-policy-graph without an argument, although the call would otherwise be allowed.

----

Policy:
```
qusal.GitInit * @anyvm @default ask target=sys-git default_target=sys-git
```

```
$ qrexec-policy-graph --include-ask --source dev --service qusal.GitInit
digraph g {
  "dev" -> "sys-git" [label="qusal.GitInit" color=red];
}

$ qrexec-policy-graph --include-ask --source dev --service qusal.GitInit+qusal
digraph g {
}
```

-------

And if I add the policy rule with an argument:
```
qusal.GitInit +qusal @anyvm @default ask target=sys-git default_target=sys-git
```
And run the graph tool:
```
$ qrexec-policy-graph --include-ask --source dev --service qusal.GitInit+qusal
digraph g {
  "dev" -> "sys-git" [label="qusal.GitInit" color=red];
}
```

But if the only policy rule for that service has an argument:
```
qusal.GitInit +qusal @anyvm @default ask target=sys-git default_target=sys-git
```

It will print the service with or without argument:
```
$ qrexec-policy-graph --include-ask --source dev --service qusal.GitInit
digraph g {
  "dev" -> "sys-git" [label="qusal.GitInit" color=red];
}

$ qrexec-policy-graph --include-ask --source dev --service qusal.GitInit+qusal
digraph g {
  "dev" -> "sys-git" [label="qusal.GitInit" color=red];
}
```

----

Because of these edge cases, I think is a bug:

- not to print the rule when policy arg is `*` and graph tool service arg is `+arg`;
- to print the rule when policy arg is solely `+arg` and the graph tool service arg is not given;

Does printing the argument breaks compatibility?
Would probably break if the parser only expects one line per rule:

For the case when only the services `qusal.GitInit+qusal` and `qusal.GitInit+test` are in place:
```
{
  "dev" -> "sys-git" [label="qusal.GitInit+qusal" color=red];
  "dev" -> "sys-git" [label="qusal.GitInit+test" color=red];
}
```

For the case when the services `qusal.GitInit`, `qusal.GitInit+qusal` and `qusal.GitInit+test` are in place:
```
## user policy
qusal.GitInit +qusal dev @default allow target=sys-git
qusal.GitInit +test dev @default allow target=sys-git
## package policy
qusal.GitInit * @anyvm @default ask target=sys-git default_target=sys-git
```

Graph output:
```
{
  "dev" -> "sys-git" [label="qusal.GitInit" color=red];
  "dev" -> "sys-git" [label="qusal.GitInit+qusal" color=red];
  "dev" -> "sys-git" [label="qusal.GitInit+test" color=red];
}
```

Is this last output confusing?

**Comment by marmarek** [comment]
The output should be compatible with `dot` tool. If it's happy about multiple lines with same source/target, then we can print it this way. Otherwise, for the purpose of this tool IMO better to coalesce all allowed arguments into a single line regardless of the argument and consider the argument only when explicitly requested with --service option.

**Comment by ben-grande** [comment]
> The output should be compatible with `dot` tool. If it's happy about multiple lines with same source/target, then we can print it this way.

It is compatible. Tested now with graphviz and visualized the svg image.
It adds a line/connection for each service+arg combination.

> Otherwise, for the purpose of this tool IMO better to coalesce all allowed arguments into a single line regardless of the argument and consider the argument only when explicitly requested with --service option.

From the examples I gave above:

> Because of these edge cases, I think is a bug:
>
>1. not to print the rule when policy arg is * and graph tool service arg is +arg;
> 2. to print the rule when policy arg is solely +arg and the graph tool service arg is not given;

Should `1` and `2` be fixed?
