### ISSUE TITLE
r.4.2-rc4 will not boot/install due to missing kernel error

### ISSUE THREAD

**Issue by froeb** [QubesOS/qubes-issues#8650]
Greetings,

I have a Lenovo thinkpad P15 gen2, currrently with Windows 11 installed.
I am trying to install Qubes 4.2 RC4 on it, using an Scandisk 64GB USB stick that has been prepared with the latest Ventoy 1.0.96 (https://www.ventoy.net/en/index.html) where i have copied the latest (rd4) qubes 4.2 rc.

With rc4, regardless which of the four grub menu option i choose, i get the message:
"
error: shim.. lock protocl not found.
error: you need to load the kernel first
error: you need to load the kernel first [sic!]

Press any key to cotinue...
"

Btw, i also tried various other programs to create bootable USB sticks from your ISO files, including the latest rufus program which you seem to recomend. None of them were able to bring me at least to the grub menu, so using ventoy was giving me the best experience so far with rc 4 but still far from helpfull.

I hope that helps.
All the best and good luck
Kai
PS: I first send this message to the google user group but only later found that i should post it here instead. I also saw mention that i should use a template, but i found nothing like a questionary, so i am using this freefrmat version trying to provide as many useful information as possibl.e

**Comment by marmarek** [comment]
This looks like you have "secure boot" feature enabled, you need to disable it first.

Anyway, take a look at https://www.qubes-os.org/support/, "updates-status" is definitely wrong place to ask for help.

**Comment by andrewdavidwong** [comment]
Based on our [issue tracking guidelines](https://www.qubes-os.org/doc/issue-tracking/), this does not appear to be suitable for `qubes-issues`. We ask that you please post this on the [Qubes Forum or `qubes-users` mailing list](https://www.qubes-os.org/support/) instead. If, after reading our [issue tracking guidelines](https://www.qubes-os.org/doc/issue-tracking/), you believe we are mistaken, please leave a brief comment explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.
