### ISSUE TITLE
The direction of the cursor guided by the touchpad and/or touchscreen does not change when the screen rotation changes

### ISSUE THREAD

**Issue by pawelsu8** [QubesOS/qubes-issues#8651]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
4.2-rc4

### Brief summary

Laptop: Thinkpad P50 with touch screen

When I change the screen orientation by 90 degrees then I would like to be able to operate the screen with touchscreen and touchpad / trackpoint.
Unfortunately, the touchpad, touchscreen and trackpoint are not aware of the screen rotation. Touchpad, trackpoint behaves as if the screen is not rotated 90 degrees at all. Touchscreen functions strangely and touching a field on the screen causes the mouse to click on a completely different part of the screen. The problem does not occur when using a USB mouse.

### Expected behavior

The touchpad should "rotate" its navigation direction according to the type of screen rotation used. When working in the field, I would like to be able to rotate the screen 90-degrees in the qubes setting, then physically turn the laptop and use the "horizontal" touchpad.

**Comment by DemiMarie** [comment]
I’m pretty sure this is not a Qubes bug.

**Comment by andrewdavidwong** [comment]
> I’m pretty sure this is not a Qubes bug.

Closing as "not our bug" (the Qubes OS Project does not develop the software that is causing this bug). If anyone believes this resolution is a mistake, please leave a comment, and we'll be happy to take another look. Thank you.

Related FAQ: [Why don’t you fix upstream bugs that affect Qubes OS?](https://www.qubes-os.org/faq/#why-dont-you-fix-upstream-bugs-that-affect-qubes-os)
