### ISSUE TITLE
man page of qrexec-client-vm is HTML

### ISSUE THREAD

**Issue by emanruse** [QubesOS/qubes-issues#8654]
### Qubes OS release

4.1.2

### Brief summary

Them man page of `qrexec-client-vm` displays HTML code.

### Steps to reproduce

```
man qrexec-client-vm
```

### Expected behavior

Properly formatted man document.

### Actual behavior

Some HTML doc is displayed as plaintext.

**Comment by alimirjamali** [comment]
This appears to be fixed in the [PR](https://github.com/QubesOS/qubes-core-qrexec/commit/de25326d41b1abf519e9a30c5760d56a1c816b3a) for #7041 and could be closed.
