### ISSUE TITLE
Support for multiple DispVMs

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#866]
**Reported by joanna on 2 Jun 2014 12:46 UTC**
See:

https://groups.google.com/forum/#!topic/qubes-devel/uQJL7I70GQs

Migrated-From: https://wiki.qubes-os.org/ticket/866

**Comment by marmarek** [comment]
In principle it will be possible to start an AppVM in "disposable" mode - which means changes to its private image (in addition to root image as in normal AppVM) will be discarded after VM shutdown. Technically any AppVM can be used for that, but practically it makes sense to have dedicated "DispVM template" AppVMs (as currently fedora-xx-dvm).

More discussion here:
https://groups.google.com/d/msgid/qubes-devel/20160517124118.GK25975%40mail-itl

**Comment by marmarek** [comment]
@woju where should be a code to make use of the DispVM? It would:

1. Create new DispVM
2. Start it
3. Call a service
4. Cleanup when service finished

IOW equivalent of `/usr/lib/qubes/qfile-daemon-dvm` tool.
The main usage would be when someone call an RPC service with `$dispvm:sth` target, but sometimes it is also useful to start new DispVM manually (from dom0 menu for example).

Should it be new `qvm-start-dispvm` tool? Option to some existing one (`qvm-run`?)? Function somewhere in the core (where?), connected to existing or a new tool?

**Comment by woju** [comment]
Some function in core, preferably a method of AppVM class
(get_dispvm()?). And CLI tool also. If you have to run a service there,
that would probably be qvm-run.

-- 
pozdrawiam / best regards       _.-._
Wojtek Porczyk               .-^'   '^-.
Invisible Things Lab         |'-.-^-.-'|
                             |  |   |  |
 I do not fear computers,    |  '-.-'  |
 I fear lack of them.        '-._ :  ,-'
    -- Isaac Asimov             `^-^-_>

**Comment by marmarek** [comment]
So `vm.get_dispvm()` would return DispVM based on this VM? Already running?
Generally I'm not so sure whether it should be in any *VM class, as it create new VM instance. And even worse - may need to reload `qubes.xml` to cleanup it later. Slightly more detailed content of this function:

1. Create new DispVM (create object, add to `app.domains`)
2. `dispvm.create_on_disk()`
3. `app.save()`
4. `dispvm.start()`
5. `dispvm.run_service(..., wait=True)` (or something)
6.  Possibly reload `qubes.xml` if changed in the meantime
6. `dispvm.force_shutdown()`
7. `dispvm.remove_from_disk()`
8. `del app.domains[dispvm]`
9. `app.save()`

**Comment by andrewdavidwong** [comment]
Workaround provided by by @unman:
https://groups.google.com/d/msg/qubes-users/2uN9ybLTqHQ/XMy6d5UkDwAJ
