### ISSUE TITLE
Treat "Qube Settings" app menu shortcut like all other shortcuts (allow it to be deselected)

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#8660]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### The problem you're addressing (if any)

In a qube's settings, in the "Applications" tab, there is a list of all available shortcuts, including "Run qube," which is a Qubes OS function, not an application. I can use this list to control exactly which shortcuts will appear in the app menu, with one very special exception: The "Qube Settings" shortcut does not appear anywhere in this list, and I cannot decide not to have it in my qube's shortcuts. It is forced there for every qube, whether I want it or not. In fact, I would prefer not to have it present for some qubes, since every additional shortcut I have to look through adds to my cognitive load when trying to find what I want. Moreover, I don't even need the shortcut, since I can always use the Qube Manager or the Qubes Domains widget to access a qube's settings.

### The solution you'd like

Simply treat the "Qube Settings" shortcut the same as every other shortcut: Put it in the Applications list, have it selected by default, and allow users to decide whether they want to deselect it. We already have the "Start qube" entry there, so it's not as though Qubes OS shortcuts (as opposed to in-qube application shortcuts) don't belong in this list.

### The value to a user, and who that user might be

Not only is this more internally consistent; it also gives the user more freedom of choice without compromising any functionality, since removing the shortcut requires an opt-out action, and there are always multiple ways to get back to the qube's settings to restore the shortcut in the future.

### Related issue

https://github.com/QubesOS/qubes-issues/issues/5447 is about always sorting the "Qube Settings" shortcut to the top of the list in the app menu, whereas this issue is about treating the "Qube Settings" shortcut like we do every other shortcut (i.e., treating all shortcuts equally and consistently), which will, consequently, allow the user the decide whether to show or hide it.

**Comment by marmarek** [comment]
The new menu has a different layout where I think it isn't applicable anymore. Specifically, "settings" entry is in separate section, not mixed with qube's applications (see screenshots in https://github.com/QubesOS/qubes-desktop-linux-menu).

**Comment by marmarta** [comment]
Also the .desktop files are left like they were (full names and all) there for compatibility or if someone prefers to use another menu, so I think it's fine as it is - you can use a menu editor if you use a different menu.

**Comment by andrewdavidwong** [comment]
> The new menu has a different layout where I think it isn't applicable anymore. Specifically, "settings" entry is in separate section, not mixed with qube's applications (see screenshots in https://github.com/QubesOS/qubes-desktop-linux-menu).

This does solve most of the problem for the new app menu, but I forgot to mention that this also affects the Application Finder. I'm not sure if that's also changed for 4.2. In 4.1, searching for a qube by name always brings up the Qube Settings for that qube.

> Also the .desktop files are left like they were (full names and all) there for compatibility or if someone prefers to use another menu, so I think it's fine as it is - you can use a menu editor if you use a different menu.

Sorry, I don't understand. Are you saying that the user can/should simply rename/remove the Qube Settings `.desktop` file if they don't want it? If it's that easy, then that would work for me, personally. However, I have to confess that I don't know what a menu editor is or how to use one. I could learn, but the inconsistent treatment and forced presence of "Qubes Settings" does make it seem more like a problem caused by Qubes OS than merely a matter of personal preference.

**Comment by andrewdavidwong** [comment]
Ah, okay, so I'm told that the new app menu will be able to do exactly what the Application Finder does in 4.1 (actually a bit better), so, for me, the new app menu will completely obviate the need for this issue. Therefore, I'm closing this as "won't do." However, I don't pretend that my use case is the same as everyone else's, so if anyone believes that this issue should be reopened for some reason, please simply leave a comment saying so. Thank you.
