### ISSUE TITLE
Option to show only "user" qubes in Qube Manager (toggle to hide template, service, disposable template, and mgmt qubes)

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#8663]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### The problem you're addressing (if any)

Sometimes, I just want to have an overview of all the qubes that contain my apps and data: The ones I actually use to manage my digital life. When I'm doing this, I don't want to see templates, service qubes, disposable templates, or any other qubes that exist only to make Qubes OS work. The purpose of Qubes OS is to protect the user's digital life, not be the focus of it. In a far-future ideal scenario, Qubes OS would quietly work in the background, and users would not have to pay attention to the internal machinery if they don't want to. Today, that's not realistic, but that doesn't mean the internal machinery has to be front-and-center all the time.

### The solution you'd like

Essentially, I want to be able to say to the Qube Manager, "Show me all of my stuff," and it will show me all of my qubes like `family`, `health`, `finances`, `email`, `work`, and so on. It will (temporarily) hide all qubes like `debian-12`, `debian-12-minimal`, `default-mgmt-dvm`, `sys-net`, `sys-firewall`, and so on. I definitely want to be able to see the latter group sometimes (maybe even most of the time!), but sometimes I want to figuratively "clear my desk" and take stock of everything in my digital life, and that's hard to do when components of the internal machinery are intermixed with aspects of my digital life. When I'm trying to plan, organize, and tend to my digital life, and the list looks like `...family, fedora-38, football...`, the Qubes-specific VMs are a cognitive burden that I have to mentally filter out. I'd like the option to have the GUI take over some of that filtering burden. I'm imagining this as a button that can be pressed to toggle the filter on and off, but I leave the implementation to the UX experts. :)

### The value to a user, and who that user might be

Users who want to be able to see their digital life in Qubes OS will be able to see exactly that, without bits of the supporting internal machinery getting in the way.

### Related issues

The following issues are somewhat similar to but distinct from this one:

- https://github.com/QubesOS/qubes-issues/issues/8042
- https://github.com/QubesOS/qubes-issues/issues/4005

**Comment by alimirjamali** [comment]
It this technically `AppVMs` + `StandaloneVMs`? If yes, easy to implement.

**Comment by alimirjamali** [comment]
> I don't think so, because disposable templates are app qubes.

Technically they could be excluded easily.

**Comment by alimirjamali** [comment]
PR Submitted

I personally do not like the text for ToolTip. Please advise on better wording.

Review priority: low

https://github.com/user-attachments/assets/7da3adb0-c39c-4d84-8ad3-ebe4cb83b1fd
