### ISSUE TITLE
qvm-prefs claims property doesn't exist when trying to set it to an invalid value

### ISSUE THREAD

**Issue by no-usernames-left** [QubesOS/qubes-issues#8666]
### Qubes OS release

4.1.2

### Brief summary

`qvm-prefs` can list properties and their values when invoked without arguments. With one argument of `updatevm`, it reads the value.

When both `updatevm` and the name of a qube are specified, it claims `updatevm` doesn't exist.

### Steps to reproduce

```
[user@dom0 ~]$ qubes-prefs updatevm
fedora-37-dvm
[user@dom0 ~]$ qubes-prefs updatevm whonix-16-dvm
usage: qubes-prefs [--verbose] [--quiet] [--help] [--help-properties] [--hide-default] [--get] [--set] [--default]
                   [PROPERTY] [VALUE]
qubes-prefs: error: no such property: 'updatevm'
[user@dom0 ~]$
```

### Expected behavior

Something like `qubes-prefs: error: no such domain: whonix-16-dvm`

### Actual behavior

`qubes-prefs: error: no such property: 'updatevm'` (which is not the case)

**Comment by jamke** [comment]
Can you please update Expected behavior and Actual behavior sections? Because it is not that clear what you mean.
