### ISSUE TITLE
Provide option to install only Whonix template (not Fedora or Debian)

### ISSUE THREAD

**Issue by 911432** [QubesOS/qubes-issues#8668]
### The problem you're addressing (if any)
I do not want to use Debian or Fadora as a template in Qubes OS, but only Whonix.
![3043b3bce10b68e959dc06b0c13675ced6e45a090c047b78210c0dd82a4870bb~2](https://github.com/QubesOS/qubes-issues/assets/30204381/5af6aa47-5542-4b91-9d4c-c3bd647a5705)

However, I can only select and install Whonix 16 in Qubes OS, but I cannot use Disposable:Whonix-ws-16-dvm after installation.

### The solution you'd like
So, I hope that you can use the Tor browser for one-time use by simply selecting and installing Whonix.

### The value to a user, and who that user might be
Use only the templates you need.

**Comment by jamke** [comment]
What should be used as a template for `sys-net` or `sys-usb` in this case?

**Comment by andrewdavidwong** [comment]
I'm guessing that this will be a "won't do," but let's see what the devs think. Whonix probably doesn't have what it would need to serve as `sys-net`. If it did, then, in theory, I suppose one could still have `sys-net` and `sys-whonix` as separate qubes both based on Whonix templates (possibly the same one).

**Comment by unman** [comment]
You are right, Whonix does not provide the firmware requirements to act
as sys-net, or the infrastructure to provide Network Manager.
I doubt that they would want to do this, but that's a question for them.

As it stands at present there is nothing actionable by Qubes. If Whonix
*did* want to pursue this, and add the necessary packages,  then it would
be relatively simple to add an option for Whonix only installs, (like
choosing Debian only).
Also, this would be privileging a Community template not maintained
by Qubes to the status of Qubes maintained templates. I wouldn't be happy
abut this.

There is nothing for Qubes to do at present.

I'm more intrigued by OP's claim that "I can only install Whonix on
Qubes OS, but I cannot use Disposable:whonix-ws-16-dvm."

**Comment by andrewdavidwong** [comment]
> Also, this would be privileging a Community template not maintained by Qubes to the status of Qubes maintained templates.

That is already sort of the case with Whonix templates in some ways. Whonix is already included in the installer and can be selected, so it's not immediately obvious to me that allowing *non*-Whonix templates to be *de*selected would thereby make Whonix officially-maintained (not that I'm advocating for this).

> I'm more intrigued by OP's claim that "I can only install Whonix on Qubes OS, but I cannot use Disposable:whonix-ws-16-dvm."

In the interest of keeping [every issue about a single, actionable thing](https://www.qubes-os.org/doc/issue-tracking/#every-issue-must-be-about-a-single-actionable-thing), I suggest that be taken elsewhere (i.e., a separate issue, or perhaps better yet, the forum or qubes-users).

> That said, we should probably be using Kicksecure for `sys-net`, `sys-firewall`, etc.

Feel free to open a separate issue for that. The first step would probably be the creation of a Kicksecure template.

**Comment by adrelanos** [comment]
Qubes-Whonix maintainer here.

I don't use Fedora much. (Can't be familiar with too many things at once.) But even I am not trying to keep only Kicksecure and Qubes-Whonix installed. I also keep the Debian and Fedora Template just in case and for comparison.

For developers it's difficult to support use cases which they themselves do not use. So fixing this use case in the installer might not be feature that is easy to support, test, etc.

> You are right, Whonix does not provide the firmware requirements to act as sys-net, or the infrastructure to provide Network Manager.

Yes. Qubes-Whonix isn't designed to act as clearnet Net qube in Qubes.

> I doubt that they would want to do this, but that's a question for them.

Confirmed.

Unless there's a strong rationale why Whonix should be able to act as sys-net and/or request from Qubes team (which I guess is very unlikely), this is `won't do`.

> That said, we should probably be using Kicksecure for `sys-net`, `sys-firewall`, etc.

This might also align with the goal of the issue creator?

As for a Kicksecure Template, help is wanted and welcome. As Kicksecure maintainer, I am not ready to receive everyone's Qubes sys-net, sys-firewall, sys-usb issues.

Qubes might one day decide to harden the inside of VMs. Related:

* https://github.com/QubesOS/qubes-issues/issues/1885
* https://github.com/QubesOS/qubes-issues/issues/2238

Or fork Debian, Fedora:

* https://github.com/QubesOS/qubes-issues/issues/8730

And/or use a Kicksecure Template / fork / alternative.

related, distro-morphed Debian into Kicksecure but not Template yet at time of writing:
https://www.kicksecure.com/wiki/Qubes
