### ISSUE TITLE
4.2-rc4 post install script stalls

### ISSUE THREAD

**Issue by GammaSQ** [QubesOS/qubes-issues#8675]
### Brief summary
Installing Qubes 4.2 on a new laptop with automatic disk layout.
Post-install script will remain on "installing fedora-38-xfce-template" indefinitely. (left it over night) Spinner is animated, mouse can be moved, but can be freezed/crashed by clicking around in the help-menu or opening tty consoles.

### Steps to reproduce
?
Install Qubes 4.2. and hope to get unlucky I guess.

### Expected behavior
Installation succeeds without a problem.

### Actual behavior
Doesn't.

After the installation stalled, I selected "don't configure anything" and used dom0 terminal to run post install tasks manually. (side-note: A far too undocumented option, I pull up the code of `qubes-anaconda-addon` as manual)
It turns out, when installing fedora-38-xfce, qubes runs out of storage. The Qubes Disk Space Monitor reports 'varlibqubes / data' as being totally full. It seems 20GB is simply not enough space.

the exact error-message is:

     $ sudo qvm-template install --nogpgcheck /var/lib/qubes/template-packages/qubes-template-fedora-38-xfce-4.2.0-202310110257.noarch.rpm
    Installing template 'fedora-38-xfce'...
    tar: ./var/lib/qubes/vm-templates/fedora-38-xfce/root.img.part.02: Wrote only 7168 of 10240 bytes
    tar: ./var/lib/qubes/vm-templates/fedora-38-xfce/root.img.part.03: Cannot write: No space left on device
    tar: ./var/lib/qubes/vm-templates/fedora-38-xfce/root.img.part.04: Cannot write: No space left on device
    tar: ./var/lib/qubes/vm-templates/fedora-38-xfce/vm-whitelisted-appmenus.list: Cannot write: No space left on device
    tar: ./var/lib/qubes/vm-templates/fedora-38-xfce/whitelisted-appmenus.list: Cannot write: No space left on device
    tar: Exiting with failure status due to previous errors
    ERROR: Failed to extract fedora-38-xfce template
    
Possible typing mistakes, had to manually copy.

P.S.: The scripts initially stalled during debian-12-xfce installation, at which point I rebooted. After that, it always got to installing fedora-38-xfce before "freezing"

**Comment by GammaSQ** [comment]
Probably connected:
https://github.com/QubesOS/qubes-issues/issues/7416
https://github.com/QubesOS/qubes-issues/issues/7184
I want to emphasize I didn't touch the lvm-/partition-layout. Before installing fedora-template manually I ran `dnf clean all` and `qubesctl saltutil.clear_cache`. According to the taskbar storage-helper varlibqubes was 83.6% full before starting to install fedora.

after running

    sudo lvextend -L 30G qubes_dom0/root
    sudo lvextend -L 35G qubes_dom0/root-pool
    sudo resize2fs /dev/mapper/qubes_dom0-root

and a restart for some reason, fedora installed fine. varlibqubes went up to 22.6GB usage.

**Comment by marmarek** [comment]
If you used kernel-latest option, the freeze it's most likely #8575. Try with default kernel (6.1 one).
As for the space usage, interrupted install likely left some files in /var/tmp, if you remove them, there should be more than enough space in default install to finish installation.

**Comment by GammaSQ** [comment]
Thanks! I was indeed trying the kernel-latest option and there are things left over in the /var/tmp directory. Since it all works now, I won't reinstall the system but am happy to provide further diagnostics.

**Comment by DemiMarie** [comment]
@GammaSQ: Ick, that is obviously a problem.  Looks like a very broken system to me.  I agree that a reinstall is the best option, but be sure to back up everything first if possible.

**Comment by marmarek** [comment]
The original bug seems to be caused by (already fixed https://github.com/QubesOS/qubes-issues/issues/8575). Further improvement to qvm-template is tracked separately: https://github.com/QubesOS/qubes-issues/issues/8876
