### ISSUE TITLE
[4.2] When "restart" option is set in updater, VMs should be restarted without addtional user selection

### ISSUE THREAD

**Issue by eloquence** [QubesOS/qubes-issues#8686]
### The problem you're addressing
4.2 RC4:
After updating multiple templates, including `fedora-38-xfce` used for system VMs, the updater GUI looks like this to me:

![updater with system VMs not selected](https://github.com/QubesOS/qubes-issues/assets/213636/a7ff8ffc-01cb-4d97-8e02-5015ab243c0c)

In other words, I still have to manually select the system VMs to ensure they are restarted.

This is the case even though the "restart system VMs by default" option is set:

![updater with restart system VM preference set](https://github.com/QubesOS/qubes-issues/assets/213636/0e724513-7c7a-4e7c-a2ae-f6df8de391d5)
 

### The solution you'd like

If a template has been "updated successfully" and it's used for a system VM, that system VM should be pre-selected to be restarted. For example, on my system, `fedora-38-xfce` is used as the template for `sys-net`.

### The value to a user

Ensure that restarts are performed when expected without the user having to make additional selections. This is likely of interest to any user who cares enough to examine or set the "Restart" option.

**Comment by eloquence** [comment]
(I wasn't sure if the current behavior is a bug or if it's working as expected, hence filed as `enhancement`.)

**Comment by andrewdavidwong** [comment]
> (I wasn't sure if the current behavior is a bug or if it's working as expected, hence filed as `enhancement`.)

Thanks! To me, it looks like a bug, because the option already exists, but it isn't doing what it says on the tin.

**Comment by marmarek** [comment]
In fact, in the template selection page, there is a checkbox at the bottom to choose whether to do the restart or not - enabling it will do just what you'd want - make all the relevant qubes selected for restart.

**Comment by marmarek** [comment]
I mean the checkbox in the main window (barely visible on the second screenshot, below the settings dialog)

**Comment by eloquence** [comment]
OK - when I click that checkbox on the opening dialog the VMs are selected for being restarted in the final step.

I think what's confusing here is that the preference says that the VMs will be restarted "by default" -- but then an additional check is required to ensure they're actually restarted.

Would it be perhaps simpler to not have the checkbox on the opening dialog, and instead honor the preferences that are set for setting the default selection on the final step? That would still enable users to not restart VMs by un-selecting them on the last step, or by changing their updater preferences.

**Comment by eloquence** [comment]
For context, on the SecureDrop Workstation, our [built-in updater](https://workstation.securedrop.org/en/stable/journalist/starting_client.html#performing-updates) automatically restarts system VMs as part of the update process. This is a decision we made to ensure that time-sensitive updates are immediately applied.

To switch to the official updater, it would be useful if there was a configuration that always performs VM reboots by default, without the user having to tick an additional box. That way we don't have to instruct the users to also check a particular checkbox in the UI every time they run updates. Does that make sense?
