### ISSUE TITLE
Remove space and upper-case letters from qubes-manager configuration directory

### ISSUE THREAD

**Issue by ben-grande** [QubesOS/qubes-issues#8694]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### The problem you're addressing (if any)

Currently it is in `~/.config/The Qubes Project/qubes-qube-manager.conf`.

Try in your system to see that spaces and upper-case is not common:
```sh
ls -a ~/
ls -a ~/.config
```

Because the file name  contains spaces, shellscripts trip on it unless specially treated.

### The solution you'd like

No spaces or upper-case in qubes configuration files and directories.
Take a look at a list of [configuration files and directories that are very common and don't contain spaces](https://wiki.archlinux.org/title/XDG_Base_Directory).

One application I know use files with spaces is VirtualBox.

### The value to a user, and who that user might be

Every developer that has to parse dom0 files through the shell.

**Comment by ben-grande** [comment]
- [Settings dir set by Organization Name](https://github.com/QubesOS/qubes-manager/blob/444542ada14f11a0484ea46f3be23d45c92d8aea/qubesmanager/utils.py#L511), [also here](https://github.com/QubesOS/qubes-manager/blob/444542ada14f11a0484ea46f3be23d45c92d8aea/qubesmanager/utils.py#L551)

- [Settings function](https://github.com/QubesOS/qubes-manager/blob/444542ada14f11a0484ea46f3be23d45c92d8aea/qubesmanager/qube_manager.py#L711)

- [How to access the configuration directly (QSettings)](https://doc.qt.io/qtforpython-5/PySide2/QtCore/QSettings.html#accessing-ini-and-plist-files-directly).

The proposal is to change:
```python3
self.manager_settings = QSettings(self)
```
to
```python3
## BaseDirectory needs to be explictly imported on Fedora but not on Debian
import xdg.BaseDirectory
...
settings_file = xdg.BaseDirectory.xdg_config_home + "/qubes/qube-manager.conf"
self.manager_settings = QSettings(settings_file, QSettings.NativeFormat)
```

I don't know how Qubes migrate configuration files when they change paths of if it is required in this case. I would appreciate guidance for migration.

**Comment by alimirjamali** [comment]
PR Submitted
Selecting a unified config path and config file scheme is kinda a major decision. I selected `xdg_config_home/qubes-os`. Please let me know if you agree
cc. @marmarek @marmarta
