### ISSUE TITLE
Renaming `sys-whonix` results in `Denied whonix.NewStatus+status from dispXXXX to sys-whonix` (sdwdate-gui)

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#8695]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

4.1

### Brief summary

Renaming `sys-whonix` causes a problem with `whonix.NewStatus`.

### Steps to reproduce

1. Rename `sys-whonix`.
2. Start a disposable based on the default Whonix Workstation disposable template.

### Expected behavior

No errors.

### Actual behavior

Dom0 notification:

```
Denied whonix.NewStatus+status from dispXXXX to sys-whonix
```

(Note: At this point, no VM with the name `sys-whonix` exists in the system.)

### Additional information

All of this is after renaming `sys-whonix` to `newname-sys-whonix`:

- `newname-sys-whonix` still has the `anon-gateway` tag.
- `dispXXXX` has the `anon-vm` tag.
- `qvm-features newname-sys-whonix` doesn't show `whonix-default-gw`. Not sure if it did before the rename.
- `qvm-features newname-sys-whonix whonix-default-gw` does nothing. Not sure if it's supposed to.

### Related issues

https://github.com/QubesOS/qubes-issues/issues/7276

CC: @adrelanos

**Comment by adrelanos** [comment]
related:

* https://github.com/QubesOS/qubes-issues/issues/8490

maybe some others:

* https://github.com/QubesOS/qubes-issues/issues?q=is%3Aissue+is%3Aopen+rename+in%3Atitle

my prefered solution to fix all of these:

* "do it the way VirtualBox does" [1]: https://github.com/QubesOS/qubes-issues/issues/6948

----

[1] Or any similar virtualizer that supports: `self-contained VMs`  = `file system` + `settings`.

**Comment by adrelanos** [comment]
Low.

No security impact.

Usability issue only.

**Comment by qtipbera** [comment]
Affects 4.2
