### ISSUE TITLE
Some XFCE panel items have tooltips in the wrong position depending on the position of the panel

### ISSUE THREAD

**Issue by emanruse** [QubesOS/qubes-issues#8698]
### Qubes OS release

4.1.2

### Brief summary

The tooltips shown when hovering over certain panel items always show downwards relative to mouse pointer. This makes it impossible to see them if the panel is moved to the lower part of workspace.

### Steps to reproduce

1. Move the panel to the lower part of workspace
2. Hover on some of its items (window bars, launchers, clock)

### Expected behavior

The tooltips should be positioned in way making them always visible.

### Actual behavior

The tooltips of some elements are always positioned downwards from mouse pointer.

**Comment by marmarta** [comment]
It seems like it doesn't happen on qubes 4.3, at least I couldn't reproduce it with single or double monitors.

**Comment by emanruse** [comment]
Thank you.
I confirm in 4.3 it seems fixed.
