### ISSUE TITLE
Have "Include in backups by default" off by default for DispVMs

### ISSUE THREAD

**Issue by emanruse** [QubesOS/qubes-issues#8705]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### The problem you're addressing (if any)

Currently, "Include in backups by default" is enabled for any qube one creates, including DispVMs.

### The solution you'd like

DispVMs with random names are not meant to be backed up, so it is better to have this setting off by default for them.

Perhaps named disposables may be backed up just as a structure with settings, not as content, so it needs to be decided how to proceed with them.

### The value to a user, and who that user might be

This may prevent accidental mistakes, e.g. backing up some running disposables along with other qubes.

**Comment by rustybird** [comment]
> DispVMs with random names are not meant to be backed up

> named disposables may be backed up just as a structure with settings, not as content

That's exactly how it works already :)

**Comment by rustybird** [comment]
> If one backs up all VMs, that would also backup the dispXXXX ones, rightF

Since they have `include_in_backups=False` by default, they are not automatically selected for backup. The user would have to override this like with any other `include_in_backups=False` VMs by explicitly selecting them (for whatever reason, e.g. to back up their ad-hoc firewall configuration or something).

**Comment by rustybird** [comment]
Yes.

**Comment by rustybird** [comment]
> Yes.

If you're wondering about the backup GUI's buggy size estimation for (running) named DisposableVM, that's part of #5699. The `qvm-backup` CLI correctly estimates their size at 0.

**Comment by unman** [comment]
> We need serious improvement in documentation for so many things.

The documentation is a community effort. Please help us improve it by
submitting a pull request.
https://www.qubes-os.org/doc/how-to-edit-the-documentation/
