### ISSUE TITLE
Qubes 4.2 logged out when key combination is pressed (not the intended log-out one)

### ISSUE THREAD

**Issue by deeplow** [QubesOS/qubes-issues#8710]
### Qubes OS release
4.2-rc4 (though I enabled current-testing at some point and then disabled it. Package versions [here](https://github.com/QubesOS/qubes-issues/files/13362781/packages.txt))

### Brief summary
Random log out while using the system (into light-dm)

### Steps to reproduce
It just happened out of the blue. I even looked into the XFCE keyboard shortcuts but nothing triggers this log out

### Expected behavior
No random log outs

### Actual behavior
Logged out randomly

### Additional Information

It randomly logged out at `09:19:50` and I logged back in at `09:19:51`. I guess the following journalctl lines can be relevant:

```
# journalctl -r
Nov 15 09:19:51 dom0 sudo[34521]:     user : TTY=pts/1 ; PWD=/home/user ; USER=root ; COMMAND=/usr/bin/journalctl -r
Nov 15 09:19:50 dom0 audit[34521]: USER_CMD pid=34521 uid=1000 auid=1000 ses=5 msg='cwd="/home/user" cmd=6A6F75726E616C63746C202D72 exe="/usr/bin/sudo" terminal=pts/1 res=success'
Nov 15 09:19:50 dom0 audit[34521]: USER_ACCT pid=34521 uid=1000 auid=1000 ses=5 msg='op=PAM:accounting grantors=pam_unix,pam_localuser acct="user" exe="/usr/bin/sudo" hostname=? addr=? terminal=/dev/pts/1 res=succ>
Nov 15 09:19:50 dom0 sudo[34521]: PAM adding faulty module: /usr/lib64/security/pam_sss.so
Nov 15 09:19:50 dom0 sudo[34521]: PAM unable to dlopen(/usr/lib64/security/pam_sss.so): /usr/lib64/security/pam_sss.so: cannot open shared object file: No such file or directory
Nov 15 09:19:40 dom0 audit: BPF prog-id=163 op=UNLOAD
```

**Comment by renehoj** [comment]
I have also had this happen 3 times now, every time it happened I was using the global clipboard shortcut keys.

**Comment by marmarek** [comment]
Is it by a chance after a installing updates but before rebooting? And does the keyboard behave funny (Alt+F2 switching to tty2 instead of showing Application Finder)? Just found today that `systemctl daemon-reexec` (called as part of glibc update that landed in Fedora today) switches something about keyboard mode.

**Comment by deeplow** [comment]
> Is it by a chance after a installing updates but before rebooting? 

Yes, I think that's the case. I updated it this morning at 09:09:41and haven't rebooted since. 

>  And does the keyboard behave funny (Alt+F2 switching to tty2 instead of showing Application Finder)? 
I don't know exactly if that was the key combination I pressed but at some point I did switch to a tty accidentally. But I tried doing Alt+F2 and that didn't happen now.

As I was writing this, it just happened again and I can confirm this is random logout is keyboard-triggered. I was trying to switch workspaces in XFCE (Ctrl + Alt + ->) or something and it showed a tty. After I switched back to tty1 to see my desktop, it logged me out.

So I guess  the `pam_sss.so: cannot open shared object file` is an entirely different issue that just happens to show up when lightdm is used. Is this correct? (not even sure what the consequence of that is)

**Comment by marmarek** [comment]
> So I guess the `pam_sss.so: cannot open shared object file` is an entirely different issue that just happens to show up when lightdm is used. Is this correct? (not even sure what the consequence of that is)

Yes, that's unrelated (#8595 )

**Comment by marmarek** [comment]
Ok, I can kinda reliably reproduce the issue too, and I suspect this glibc update is to blame. I have a procedure that previously did not result in logout and now it does result in logout.

The procedure:
1. Wait for the cat to enter the keyboard.

**Comment by marmarek** [comment]
But, it happens only after `systemctl daemon-reexec`, until this lightdm restart. Hmm...

**Comment by marmarek** [comment]
And I don't see any traces of anything crashing in the Xfce session. According to logs, looks like clean logout.

**Comment by renehoj** [comment]
I don't know if the glibc update is a different issue, it did happen to me today as well, but I have been experiencing a similar issue for some time now.

Someone else mentions the same thing here, and that was back in RC3: https://forum.qubes-os.org/t/qubes-update-and-unexpected-logout-by-keystroke/20992

**Comment by marmarek** [comment]
Could it be as simple as Ctrl+C that killed X server?

**Comment by renehoj** [comment]
I'm not able to reproduce the crash, I've tried all the key combinations.

I think I've been using Ctrl+V or Ctrl+Shirt+V some of the times it happened, because I can see then content of the clipboard in tty1 when I shut down the system, as if I had pasted it into the terminal.

It happens very rarely, maybe once a month, but it always seems to be when I use the copy or paste shortcut.

**Comment by Minimalist73** [comment]
This happened to me earlier today after I updated everything, but I thought I did it by accident because I was typing quickly at the same time. I haven't been able to reproduce it since.

**Comment by Minimalist73** [comment]
I found the following in my logs from today, I never log out of my session so I'm sure that's when it happened:

```
dom0 audit[4514]: ANOM_ABEND auid=1000 uid=1000 gid=1000 ses=2 pid=4514 comm="xss-lock" exe="/usr/bin/xss-lock" sig=5 res=1
dom0 at-spi2-registryd[4833]: X connection to :0 broken (explicit kill or server shutdown).
dom0 kernel: traps: xss-lock[4514] trap int3 ip:7575b8664e71 sp:7ffc8174a420 error:0 in libglib-2.0.so.0.7400.7[7575b8624000+93000]
dom0 kernel: audit: type=1701 audit(1700039853.387:927): auid=1000 uid=1000 gid=1000 ses=2 pid=4514 comm="xss-lock" exe="/usr/bin/xss-lock" sig=5 res=1
dom0 systemd[4433]: dbus-:1.6-org.a11y.atspi.Registry@0.service: Main process exited, code=exited, status=1/FAILURE
dom0 systemd[4433]: dbus-:1.6-org.a11y.atspi.Registry@0.service: Failed with result 'exit-code'.
dom0 systemd[4433]: dbus-:1.6-org.a11y.atspi.Registry@0.service: Consumed 1.701s CPU time.
dom0 systemd[4433]: dbus-:1.2-org.freedesktop.Notifications@0.service: Main process exited, code=exited, status=1/FAILURE
dom0 systemd[4433]: dbus-:1.2-org.freedesktop.Notifications@0.service: Failed with result 'exit-code'.
dom0 systemd[4433]: dbus-:1.2-org.freedesktop.Notifications@0.service: Consumed 1.388s CPU time.
dom0 widget-wrapper[51723]: xhost:  unable to open display ":0"
dom0 widget-wrapper[51725]: xhost:  unable to open display ":0"
dom0 widget-wrapper[51724]: xhost:  unable to open display ":0"
dom0 widget-wrapper[51721]: xhost:  unable to open display ":0"
dom0 widget-wrapper[51722]: xhost:  unable to open display ":0"
dom0 widget-wrapper[4703]: exiting with 0
dom0 widget-wrapper[4701]: exiting with 0
dom0 widget-wrapper[4710]: exiting with 0
dom0 widget-wrapper[4707]: exiting with 0
dom0 widget-wrapper[4697]: exiting with 0
dom0 pulseaudio[4636]: Disabling timer-based scheduling because running inside a VM.
dom0 systemd[4433]: qubes-widget@qui-domains.service: Consumed 8.280s CPU time.
dom0 audit[4376]: USER_LOGOUT pid=4376 uid=0 auid=1000 ses=2 msg='op=logout id=1000 exe="/usr/sbin/lightdm" hostname=dom0 addr=? terminal=/dev/tty1 res=success'
dom0 kernel: audit: type=1113 audit(1700039853.704:928): pid=4376 uid=0 auid=1000 ses=2 msg='op=logout id=1000 exe="/usr/sbin/lightdm" hostname=dom0 addr=? terminal=/dev/tty1 res=success'
dom0 lightdm[4376]: pam_unix(lightdm:session): session closed for user User
dom0 audit[4376]: USER_END pid=4376 uid=0 auid=1000 ses=2 msg='op=PAM:session_close grantors=pam_selinux,pam_loginuid,pam_selinux,pam_keyinit,pam_namespace,pam_keyinit,pam_limits,pam_systemd,pam_unix,pam_lastlog,pam_umask,pam_lastlog acct="User" exe="/usr/sbin/lightdm" hostname=? addr=? terminal=:0 res=success'
dom0 kernel: audit: type=1106 audit(1700039853.715:929): pid=4376 uid=0 auid=1000 ses=2 msg='op=PAM:session_close grantors=pam_selinux,pam_loginuid,pam_selinux,pam_keyinit,pam_namespace,pam_keyinit,pam_limits,pam_systemd,pam_unix,pam_lastlog,pam_umask,pam_lastlog acct="User" exe="/usr/sbin/lightdm" hostname=? addr=? terminal=:0 res=success'
dom0 audit[4376]: CRED_DISP pid=4376 uid=0 auid=1000 ses=2 msg='op=PAM:setcred grantors=pam_localuser,pam_unix acct="User" exe="/usr/sbin/lightdm" hostname=? addr=? terminal=:0 res=success'
dom0 kernel: audit: type=1104 audit(1700039853.717:930): pid=4376 uid=0 auid=1000 ses=2 msg='op=PAM:setcred grantors=pam_localuser,pam_unix acct="User" exe="/usr/sbin/lightdm" hostname=? addr=? terminal=:0 res=success'
dom0 systemd-logind[2882]: Session 2 logged out. Waiting for processes to exit.
```

**Comment by noskb** [comment]
I can reliably reproduce it by pressing ctrl+shift+c after  `sudo qubes-dom0-update --action=reinstall glibc`  on my side.

**Comment by marmarek** [comment]
`strace` confirms that after `systemctl daemon-reexec` ctrl+c (or ctrl+shift+c) sends SIGINT to the X server.

**Comment by DemiMarie** [comment]
@marmarek That looks like a systemd bug.  Very strange.

**Comment by marmarek** [comment]
> @marmarek That looks like a systemd bug. Very strange.

Yes, it does. I'm collecting data for the bug report.

**Comment by marmarek** [comment]
https://github.com/systemd/systemd/issues/30046

**Comment by UndeadDevel** [comment]
Good thing one of the first things I did with the new Qubes install was change the hotkeys to `Ctrl+Super+C/V` :smile: (Firefox inspector and some other stuff is on Ctrl+Shift+C, which is why I did it).

Just for anyone wondering: have not seen this issue at all, so using `Super` instead of `Shift` seems safe from this bug.

**Comment by marmarek** [comment]
Fixed upstream, now lets get it into Fedora: https://bugzilla.redhat.com/show_bug.cgi?id=2249991

**Comment by DemiMarie** [comment]
@marmarek time to make a PR to Fedora’s src-git?  Fedora 39 just came out, and I don’t know if upstream maintainers are that interested in support for a distro that is EOL in a less than a month.

**Comment by UndeadDevel** [comment]
Haven't seen this yet on Q4.2rc5, but I've had what seemed like a similar issue: at some point pressing `Alt+F3` (or other F-keys from 2 to 4, haven't tried others) would open a tty (like pressing `Ctrl+Alt+Fx` normally does. Was pretty annoying as the Application Launcher is bound to `Alt+F3`, but after reboot it went away and hasn't returned...

Mentioning this here because it seems like it involves the `Ctrl` key both times in weird ways.

**Comment by marmarek** [comment]
Fixed with Fedora update not long after last my comment.
