### ISSUE TITLE
Upgrade to 4.2 fails because of a leftover from 4.0

### ISSUE THREAD

**Issue by v6ak** [QubesOS/qubes-issues#8715]
### Qubes OS release

4.1

### Brief summary

It seems that this package is some leftover from 4.0 (as there is `fc25` in the package name), which causes failure when upgrading to 4.2. The package can be probably safely removed. There are some more fc25 leftovers, but they don't seem to cause such issues. (Well, I'll see.)

### Steps to reproduce

1. Install 4.0
2. Upgrade to 4.1
3. Upgrade to 4.2 (RC)

### Expected behavior

Upgrade passes

### Actual behavior

Stage 3 fails with this error message:

```
Running transaction test
Error: Transaction test error:
  file /usr/share/doc/python-systemd/NEWS from install of python3-systemd-235-1.fc37.x86_64 conflicts with file from package python2-systemd-234-5.1.fc25.x86_64
  file /usr/share/doc/python-systemd/README.md from install of python3-systemd-235-1.fc37.x86_64 conflicts with file from package python2-systemd-234-5.1.fc25.x86_64
```

**Comment by michaelschefczyk** [comment]
Faced the same issue. After typing:

sudo dnf remove python2-systemd

Stage 3 did complete without issues.
