### ISSUE TITLE
Qubes R4.2-rc4 does not work with UEFI boot

### ISSUE THREAD

**Issue by feskehau** [QubesOS/qubes-issues#8717]
### Qubes OS release
Qubes OS R4.2-rc4 installer
Lenovo T14 Gen1 (4k screen + Nivideacard)

### Brief summary
Unable to get the installer to boot using UEFI.
Legacy mode does boot
UEFI only does not boot
UEFI with CSM support does not boot

Tried different methods of creating the usb: dd, gnome disk util, fedora media writer ++
Tried different usb sticks.
Fedora 39 usb boots with only UEFI, so my assumption is that this is a Qubes issue.

Manually created a bootable UEFI USB and copied over files from ISO works. In Fedora 39 (grub2-install is patched, se bottom https://bugzilla.redhat.com/show_bug.cgi?id=1917213)
 - Create GPT, partition entire disk as EFI with FAT32.
 - Mount and create boot directory
 - grub-install --target=x86_64-efi --removable --boot-directory=/mnt/boot --efi-directory=/mnt --force
 - Copy over files from ISO, except i386 boot files.
 - Works!

### Steps to reproduce
dd iso to usb, try and boot from USB with Legacy disabled.

### Expected behavior
GRUB should be presented on screen.

### Actual behavior
Lenovo refuses to boot USB and asks me to find another boot option.

BTW I'm not able to install Qubes OS regardless of boot method. It hangs before Anaconda starts. This guide: https://www.qubes-os.org/doc/uefi-troubleshooting/ mentions `EFI/BOOT/BOOTX64.cfg `which is nowhere to be found on rc3 or rc4 ISO.  Did not check older. Think it might be related to UEFI not working? Also would be nice to get a update to that guide in case the file is now gone on purpouse...

**Comment by feskehau** [comment]
A BIOS update from Lenovo actually changed this. And Qubes does boot using EFI. Still thinks it is strange that it worked with Fedora but not Qubes. Leaving it up to the Qubes Team to decide if this can be closed.

Should I create a new issue for the aging EFI documentation?

**Comment by feskehau** [comment]
If Fedora boots on UEFI without the updated BIOS and Qubes does not, I still think there is an issue with the ISO, but my issue is resolved.

**Comment by aevin111** [comment]
I have a similar problem.

I tried creating a 4.2-rc4 USB installer using Rufus 4.3 in DD mode on Windows 11 Pro 23H2. Usually, I'd see "BIOS or UEFI" as the target system, but now the only target system was "UEFI (non-CSM)" for 4.2-rc4.

After creating the USB installer, I tried to boot into the installer but did not see the bootable USB drive. After that, I wiped the USB clean and then created a 4.2-rc4 USB on Linux using the dd command and got the same result.

To check, I created a 4.1.2 USB installer using Rufus 4.3 in DD mode on Windows 11 and I was able to install Qubes on my laptop.

I can only use UEFI. I do not have the option to use BIOS/Legacy boot.

**Comment by marmarek** [comment]
> but now the only target system was "UEFI (non-CSM)" for 4.2-rc4.

So, does this target work?

**Comment by aevin111** [comment]
> > but now the only target system was "UEFI (non-CSM)" for 4.2-rc4.
> 
> So, does this target work?

Nope, I couldn't find the USB installer as a boot option when I was about to install 4.2-rc4 on my laptop. I used Rufus 4.3 and did not have any other options for the target system other than that. Usually, I'd see "UEFI or BIOS" on Rufus as the default. I tried using Rufus 4.2 and received the same result. Using the dd command on Linux yielded the same result.

In comparison, I made a 4.1.2 USB installer using Rufus 4.3 and was able to boot and install Qubes.

**Comment by iinta** [comment]
I have problem which might be related to this,  

I downloaded the same **ISO   Qubes OS R4.2-rc4 installer**
Writed the usb stick according to **user install quide.**
_$ sudo dd if=Qubes-RX-x86_64.iso of=/dev/sdY status=progress bs=1048576 conv=fsync_

Booted the stick, but the lapdance **boots only to Grub.** I have old Toshiba company manufactured Dynabook 10th gen intel. 
Currently i am running other(4.1)  Qubes version which works fine including installer.

I cant update my computer bios to verify the other user guide fix to the problem (all these new MBR and bios UEFI things not common for all users).

From my perspective these operating system installers which are indeed ment for end users(aka consumers) 
should work instantly without any extra play,  "ok this is unix not microsoft but still coudnt the bonus hassle be removed...."

Well going to try write again installation media cos i noticed other dd quide also on your site (writing these usb installers  always such a hassle with finding right programs dunno if THE proxy makes it easier FYI) 

Anyhow I followed exatly the install quide from  the www site(Side note had usb proxy trouble with mounting, not all standard sticks work, separate issue other version).

**Comment by marmarek** [comment]
@iinta can you check with R4.2.0-rc2 installer? It used a bit different partition layout, maybe that one was better?

**Comment by iinta** [comment]
sure i could but just cant see the R4.2.0-rc2 download link anywhere and dunno which of the release numbers it is you are refering.
if you provide the link or the number i`ll give it a shot, i`m late with this install anyhow before use.

**Comment by iinta** [comment]
Do you want me to test install that old rc2 iso? Even thou latest weekly
install worked.

**Comment by marmarek** [comment]
I'm a bit confused, can you clarify what work and what does not?
Does R4.2.0-rc4 work for you?
Does recent 4.2 weekly build work for you?

**Comment by iinta** [comment]
the r.4.2.0-rc4 download from qubes-os download page  R4.2.0-rc4  did not work, only booted to grub(black screen) and  did not load install boot screen with options.

the weekly compile 4.2 rc4 (with numbers) installed ok like it should. and yes weekly work, using it currently

**Comment by marmarek** [comment]
@aevin111 does recent weekly build work for you? if not, does 4.2.0-rc2 work?

**Comment by aevin111** [comment]
> @aevin111 does recent weekly build work for you? if not, does 4.2.0-rc2 work?

I will test 4.2.0-rc2 this weekend. 

As for the weekly builds, I'm not sure where to find it on the official site.

**Comment by marmarek** [comment]
> As for the weekly builds, I'm not sure where to find it on the official site.

https://forum.qubes-os.org/t/qubes-os-4-2-signed-weekly-builds/16929
https://qubes.notset.fr/iso-testing/
