### ISSUE TITLE
`qvm-copy` in terminal shows incorrectly the size of successfully copied data

### ISSUE THREAD

**Issue by jamke** [QubesOS/qubes-issues#8722]
### Qubes OS release
R4.1 (R4.2?)

### Brief summary
When file copied with `qvm-copy` from terminal, it never properly shows the final result right. E.g.:
```
$ qvm-copy test.txt
sent 36/37 KB
```
Why 36 out of 37, should user be afraid that 1KiB was lost? I know they should not, but it looks like a bug for sure.

### Steps to reproduce
`qvm-copy` any file.

### Expected behavior
`sent X/X KiB`

### Actual behavior
`sent Y/X KB`
where Y < X.

**Comment by jamke** [comment]
I have this for ages, so used to ignore this problem and was not expecting it to be fixed recently.
The version in my case 4.1.45, thank you for information, I will update the template for this qube and check again.

**Comment by rustybird** [comment]
If your sender side is Debian 11 bullseye on R4.1, the progress will still be wrong (but in a different way) after updating at the moment: https://github.com/QubesOS/qubes-core-agent-linux/pull/465#issuecomment-1823156652

**Comment by jamke** [comment]
Thank you @rustybird. I have fedora template, just updated it and it is fixed. I was 1 version before fix.
It is kind of funny, that I had this bug for years and reported just after it was fixed in stable just recently.
