### ISSUE TITLE
Kernel update sets smt=off when smt=on is set

### ISSUE THREAD

**Issue by renehoj** [QubesOS/qubes-issues#8737]
### Brief summary
Kernel updates forcefully disable smt, even if you have set the smt=on option.

This becomes a problem with features like cpupools, if you are expecting all cores to be usable. Cpupools with credit(1) scheduler seems to crash xen, if the pools are using all the cores and smt gets disabled.

### Steps to reproduce
Set smt=on in /etc/default/grub
Update the kernel with the Qubes OS update tool.

### Expected behavior
The system remains configured with smt=on

### Actual behavior
The last line in /etc/default/grub set smt=off, and the system is no longer configured with smt=on

**Comment by marmarek** [comment]
The `smt=on` configuration is not supported. You can read more in https://github.com/QubesOS/qubes-secpack/blob/master/QSBs/qsb-043-2018.txt

That said, if you really want to use unsupported `smt=on` configuration, you are aware of the risks and accept them, set `smt=on` on a separate line, leaving the line with `smt=off` in the file too.

**Comment by DemiMarie** [comment]
In case anyone is wondering what would be needed to enable `smt=on` again, the answer is a secrets-free hypervisor.  Patches for Xen would be appreciated.

**Comment by DemiMarie** [comment]
Also, Xen crashing is a separate bug; please report that to xen-devel.
