### ISSUE TITLE
Request to make Qubes a paid OS

### ISSUE THREAD

**Issue by evil-user** [QubesOS/qubes-issues#8739]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### The problem you're addressing (if any)

Sorry i dont know if this is right place to discuss but i advocate for Better Budget for Qubes Project , better payment and work life balance for Qubes Developers and Volunteers and better innovation for Qubes by dedicated Research . I like Qubes project but i strongly feel people should pay for good work done by this project.

### The solution you'd like

We should stop people like freeloaders , qubes is an expensive project and i feel if people really need good security they should pay. I will pay if i use Qubes. Maybe Devs can provide a stripped down os as basic with full featured os as paid os in worst case. In best case i would like to see Qubes adopt a model like Grsecurity.

### The value to a user, and who that user might be

User might be better protected from highly sophisticated attacks which are constantly evolving. The budget of qubes is very small compared to bad guys out there.

**Comment by DemiMarie** [comment]
Qubes OS is and will remain free and open source software.  I will not speak for the other developers, but for me, making Qubes OS paid would defeat much of its purpose.
