### ISSUE TITLE
Clearnet networking issues in Qubes 4.2rc5 especially for restricted qubes (tor works reliably)

### ISSUE THREAD

**Issue by UndeadDevel** [QubesOS/qubes-issues#8741]
### Qubes OS release
4.2rc5

### Brief summary
During installation in phase 2 the installer hung on the network setup step and I had to do a hard shutdown (may be related to #4494); upon booting again it resumed and completed successfully (there was one error about `/usr/sbin/lvcreate` failing with `stderr: Logical volume vm-pool already exists in Volume group qubes_dom0` message, which I just clicked "OK" on, as it just means storage had been set up already the first time in phase 2).
When logging into QubesOS, dom0 updates and updates for the templates worked, but took a long time. When I later went through the settings in the Global Config app and changed dom0 to `sys-whonix` (update qube), dom0 updates / installing packages there still worked, but template updates were broken. Setting the template updateVM to `sys-whonix` fixes this, but still with much lower speed (expected, as it's tor), which is why I suspect that when they were all updating earlier they were using `sys-whonix` as well, because normally I have a very fast connection (clearnet) and even big updates happen quickly, which was not the case for the first updates I did there; hence I suspect that clearnet networking was broken from the start.

Another thing I noticed was that AppVMs based on the new standard templates (e.g. `debian-12-xfce`) can successfully ping (ICMP, e.g. `ping 8.8.8.8`) via clearnet, but DNS or TCP fails to get an answer. AppVMs based on the gnome version of `debian-12` (restored from backup) are completely cut off, however (not even ping gets through).

This is still on NV41 (laptop).

Edit: now split into two issues, the other being #8752 

This is issue is about an apparent firewall bug for network-restricted qubes (only certain domains allowed), which can be quickly resolved using `qvm-firewall -r $qubename`, but reappears often.

### Steps to reproduce
~~Do a fresh install of Qubes 4.2rc5 with USB ISO (`dd` method from docs).
Check networking (though problem may be related to the installer hanging on the network setup step).~~
1. Set up network restricted qube with e.g. only the following allowed in the firewall rules (GUI):
```
0   accept  api.github.com 
1   accept  avatars.githubusercontent.com
2   accept  github.com 
3   accept  github.githubassets.com
4   accept  gitlab.com
5   accept  s3.amazonaws.com
6   accept  about.gitlab.com
7   accept  gitlab.xfce.org
```
2. Observe that pretty soon web connectivity will break and can be fixed with `qvm-firewall -r $qubename`.
3. (also observe that for most of these cases the IP of Github didn't change)

### Expected behavior
~~No hanging of installer and networking works, both clearnet and tor.
If installer hangs and needs hard reboot to resolve, then either complete setup normally (verification of completed steps or redo them) or tell user to reinstall from the beginning.~~
No breaks in web connectivity

### Actual behavior
~~Only tor networking works; installer completed upon booting again (but maybe this is fine, if problem turns out unrelated to that).~~
Frequent breaks in web connectivity, especially for GitHub.

**Comment by UndeadDevel** [comment]
Okay, this will be the issue for number two in my previous comment; I'll open an issue for number one once I can more reliably reproduce it, as it doesn't happen often. 
I'll add that it seems this issue is worst for network restricted qubes, such as this "Github-web" qube I'm writing this message in, which only allows `github.com`, `avatars.githubusercontent.com` and `github.githubassets.com` in the firewall settings (my proxy solution that worked on Q4.1 was iptables based and so doesn't work anymore on Q4.2). While doing the following on this page within 5 minutes I had to reset networking by setting the netVM to None and back twice: edited a comment, edited the title, wrote this new comment.

**Comment by UndeadDevel** [comment]
Okay I think I've confirmed that it's not dynamic load balancers, as it also happens when the IP of GitHub used by this Firefox stays the same. Github really seems to be the worst...it happens here sometimes every minute; in other restricted qubes I'm sitting pretty with my firewall restrictions without issue.

Also I've not encountered this again for non-restricted qubes.

**Comment by UndeadDevel** [comment]
Update: still occurs when using `fedora-38-xfce` instead of `debian-12-xfce` both for `sys-net` and `sys-firewall` as I've already seen in the beginning; also I've been looking at my connections a bit and I've noticed that usually, when there are still open connections from the VM to some server, the issue won't crop up, but if all connections are either done or reset then it may crop up...doing `qvm-firewall -r qubename` usually fixes the issue if I wait for a few seconds, though sometimes I need to do it twice.

**Comment by marmarek** [comment]
> doing `qvm-firewall -r qubename` usually fixes the issue

This sounds like it is about load balancers after all. You mentioned github as one example and in fact it does use such load balancer (I just checked - I get 140.82.121.4 or 140.82.121.3 depending on when I try, at least in my location). What may be making the issue a bit harder to diagnose, is various DNS caching (by the web browser, by systemd-resolved, etc). So, if you check with `dig` for example, it doesn't mean Firefox will use the same IP (it might have some other cached).

**Comment by UndeadDevel** [comment]
I must admit, several aspects of this issue do seem to indicate load balancing being the cause...the argument against it is my observation of IP as per firefox Network console (I leave it open and check the IP of github.com via the tool tip); but perhaps it simply doesn't update the tool tip properly? Or maybe in those cases where it seemed like the IP address didn't change before vs. after fixing the issue, I got switched twice by the load balancer? I'll observe it a bit more and hopefully soon will have a proper sys-proxy again. If I have additional insights I'll report.

**Comment by marmarek** [comment]
For github specifically, they [publish all IP ranges they use](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/about-githubs-ip-addresses), so you can use that in the firewall.

**Comment by UndeadDevel** [comment]
Okay I just confirmed that the Firefox Network console does not update its IP address tool tips unless its reloaded, so that explains why I haven't seen the changes in many cases. Thanks for the tip with the IP ranges btw., so far it works quite well!

As the overwhelmingly likely explanation then is indeed load balancers and that's a known problem with the standard functionality I will close this again.
