### ISSUE TITLE
Q4.2 Global Config GUI UI String issues

### ISSUE THREAD

**Issue by UndeadDevel** [QubesOS/qubes-issues#8743]
### Qubes OS release
4.2

### Brief summary
The Global Config app displays raw HTML tags in some text and tool tips, e.g. (non exhaustive):
- on the "Updates" page tool tips for question boxes for "Enable all testing updates" and "Whonix update proxy" contain raw `<b>` and `<tt>` tags, respectively
- on the "File Access" page the label for "Default policy" has a raw `<a>` tag with the `href` visible
- on the "Split GPG" page the header label has a raw `<a>` tag with the `href` visible

Other UI String issue(s):
- superfluous quotation mark at the end of the "Dom0 update proxy" tooltip in the "Updates" section.
- the `href` in the warning section on the page "URL Handling" leads to the doc landing page, which is not specific to that issue

### Steps to reproduce
Check new Global Config GUI app

### Expected behavior
polished UI Strings

### Actual behavior
raw html tags in some places, superfluous characters and non-specific doc links

**Comment by UndeadDevel** [comment]
A related one I just noticed: superfluous quotation mark at the end of the "Dom0 update proxy" tooltip in the "Updates" section.

**Comment by UndeadDevel** [comment]
Related [forum post](https://forum.qubes-os.org/t/qubes-users-minor-bugs-in-qubes-managers-global-config/23896) from another user:
>I just discovered the "Global Config" in Quebes manager.
I found some minor bugs:
In "Split GPG" the "learn more" hyperlink is displayed as text. I found no way to copy that text.
The link in "URL Handling" is a link, but it leads to a very generic documentation page that says nothing about "URL Handling".
When I had a DVM open viewing some page I could not close the dialog until I stopped that DVM. Rather confusing for beginners...
Kind regards,
Ulrich

**Comment by UndeadDevel** [comment]
>These seem like different problems from the current issue (and from each other). Would you mind opening separate issues for these?

Well my first additional comment was already not about HTML tags, so I've now generalized this issue to be about bad UI strings in the Global Config app, which includes HTML tags and other Strings, including the first 2/3 issues mentioned by the poster on the forum; I've added these all to the OP now and opened #8878 for the third issue he reported (I can reproduce it).

**Comment by alimirjamali** [comment]
PR Submitted

The below item is already fixed in [this patch](https://github.com/QubesOS/qubes-desktop-linux-manager/commit/1ce7306e719d8910052fd2b789a7b36189ffb2e3).
> * on the "Updates" page tool tips for question boxes for "Enable all testing updates" and "Whonix update proxy" contain raw `<b>` and `<tt>` tags, respectively
