### ISSUE TITLE
networked qubes other than sys-net often without web connectivity after sys-net start

### ISSUE THREAD

**Issue by UndeadDevel** [QubesOS/qubes-issues#8752]
### Qubes OS release
Qubes 4.2rc5

### Brief summary (updated)
On ~~some~~ most (not all) boots of `sys-net` both WiFi and Ethernet (NV41 with AX201 WiFi and standard integrated ethernet port) does not work properly right away; it will find and connect to the network and sys-net will have full connectivity (doing a `curl www.google.com` gives normal return in a `sys-net` terminal), but no other qube, including `sys-firewall`, will have normal web access (e.g. `sys-firewall` then starts pushing notifications about not being able to resolve my firewall rules for some qubes); `sys-firewall` does still get pings through to `8.8.8.8`, but doing `curl www.google.com` hangs. Both the AX201 Intel WiFi 6 card as well as the ethernet adapter is the same as what I used under Qubes 4.1.2, where there had been no issues; I tried with the debian template that `sys-net` was using in Qubes 4.1, but it seems worse, i.e. happens more often with it; currently both `sys-net` and `sys-firewall` are using a 4.2 `debian-12-xfce` template.
<details>
 <summary>(Edit: not sure if relevant, as ethernet also affected and sys-net has full network access)`sudo dmesg` in `sys-net` reports:</summary>

```
[    3.464343] iwlwifi 0000:00:06.0: Detected crf-id 0x1300504, cnv-id 0x80400 wfpm id 0x80000030
[    3.491708] iwlwifi 0000:00:06.0: PCI dev 51f0/0074, rev=0x370, rfid=0x10a100
[    3.492052] iwlwifi 0000:00:06.0: Direct firmware load for iwlwifi-so-a0-hr-b0-83.ucode failed with error -2
[    3.492101] iwlwifi 0000:00:06.0: Direct firmware load for iwlwifi-so-a0-hr-b0-82.ucode failed with error -2
[    3.492129] iwlwifi 0000:00:06.0: Direct firmware load for iwlwifi-so-a0-hr-b0-81.ucode failed with error -2
[    3.492156] iwlwifi 0000:00:06.0: Direct firmware load for iwlwifi-so-a0-hr-b0-80.ucode failed with error -2
[    3.492185] iwlwifi 0000:00:06.0: Direct firmware load for iwlwifi-so-a0-hr-b0-79.ucode failed with error -2
[    3.492211] iwlwifi 0000:00:06.0: Direct firmware load for iwlwifi-so-a0-hr-b0-78.ucode failed with error -2
[    3.492238] iwlwifi 0000:00:06.0: Direct firmware load for iwlwifi-so-a0-hr-b0-77.ucode failed with error -2
[    3.492265] iwlwifi 0000:00:06.0: Direct firmware load for iwlwifi-so-a0-hr-b0-76.ucode failed with error -2
[    3.492292] iwlwifi 0000:00:06.0: Direct firmware load for iwlwifi-so-a0-hr-b0-75.ucode failed with error -2
[    3.492319] iwlwifi 0000:00:06.0: Direct firmware load for iwlwifi-so-a0-hr-b0-74.ucode failed with error -2
[    3.492346] iwlwifi 0000:00:06.0: Direct firmware load for iwlwifi-so-a0-hr-b0-73.ucode failed with error -2
[    3.501541] iwlwifi 0000:00:06.0: api flags index 2 larger than supported by driver
[    3.501563] iwlwifi 0000:00:06.0: TLV_FW_FSEQ_VERSION: FSEQ Version: 0.0.2.36
[    3.501805] iwlwifi 0000:00:06.0: loaded firmware version 72.daa05125.0 so-a0-hr-b0-72.ucode op_mode iwlmvm
[...]
[    3.818457] iwlwifi 0000:00:06.0: Detected Intel(R) Wi-Fi 6 AX201 160MHz, REV=0x370
```

So it fails at first but then manages to load the firmware.

Dom0 `sudo dmesg` says regarding that network controller:
```
43.856657] pciback 0000:00:14.3: xen-pciback: Driver tried to write to a read-only configuration space field at offset 0x48, size 2. This may be harmless, but if you have problems with your device:
               1) see permissive attribute in sysfs
               2) report problems to the xen-devel mailing list along with details of your device obtained from lspci.
```
</details>

So this seems like another firewall issue, which I suppose is to be expected given the significant changes to firewalling between 4.1.2 and 4.2.
What fixes it most of the time is reconnecting (i.e. cable out and in again for ethernet, or "flipping the switch" - software via `nmcli` - for WiFi).
Confirmed now that using a fresh, `debian-12-xfce`-based `sys-net` with standard configuration also produces this issue.

### Steps to reproduce
~~1. NV41 with AX201 running Qubes 4.2rc5
2. boot up and try to use WiFi to connect to the web
(3. if that works without issue try restarting `sys-net` until issue appears)~~
1. NV41 with Qubes 4.2rc5
2. Boot up and try to access the web from any non-`sys-net` VM using either WiFi or ethernet
(3. If there are no issues, restart `sys-net` until issue appears)

### Expected behavior
No problems, as in Qubes 4.1.2

### Actual behavior
~~Sometimes the WiFi will connect to the AP, but there's no internet access. Turning WiFi off and on again in the Network Manager usually fixes the problem.~~
No web connectivity for any qube except sys-net

**Comment by UndeadDevel** [comment]
Updated the OP. What may be contributing to this issue is the fact that I always start `sys-net` with disabled WiFi (via config) and disconnected ethernet...will test more with a different config and report back.

**Comment by UndeadDevel** [comment]
I've confirmed that even in a standard configuration with a fresh `debian-12-xfce`-based `sys-net` and WiFi always on from boot this problem persists, so it seems it's another firewall issue, as both WiFi and ethernet are affected, `sys-net` does have full web connectivity, but `sys-firewall` and other qubes connected to `sys-firewall` do not.

**Comment by DemiMarie** [comment]
I wonder if there are any tests for Debian-based `sys-net`.  If not, that should probably be fixed.

**Comment by UndeadDevel** [comment]
> I wonder if there are any tests for Debian-based sys-net. If not, that should probably be fixed.
Indeed, but do note that this issue is almost certainly `sys-firewall`-related as I've discovered, less `sys-net`-related. In fact, I just re-tested with a `fedora-38-xfce`-based `sys-net` and the issue persists. Now I'm testing with a `fedora-38-xfce`-based `sys-firewall`, as in my earlier tests with fedora I was still confused between this issue and the [other firewall issue](https://github.com/QubesOS/qubes-issues/issues/8741)...so far actually it does not crop up, but potentially yet another issue does (*sigh*)...I'll test more over the following days to see what's what.

**Comment by neoniobium** [comment]
I had precisely this also happen to me frequently on `Qubes 4.1`.

**Comment by UndeadDevel** [comment]
@neoniobium did you upgrade to Qubes 4.2 now and it disappeared? Strangely I had no such issue on 4.1, but it doesn't seem to go away on 4.2 :(

**Comment by neoniobium** [comment]
Yes did a complete reinstall, not just an upgrade, however. For the last few days I did not experience this issue. Nevertheless I have only done something like 10 boots until now.

On `4.1` I had this happen in approximately in 1 out of 5 boots.  

If I notice a this happen to me on `4.2` I will comment on this issues I try to debug it.

**Comment by DemiMarie** [comment]
Is this with Debian 11 sys-net?  Debian 11 is not tested at all with R4.2.

**Comment by UndeadDevel** [comment]
> Is this with Debian 11 sys-net? Debian 11 is not tested at all with R4.2.

No, I've seen it with `sys-net` based on Debian 12 (xfce), Fedora-38 (xfce) and a Debian-12 template (gnome) from 4.1 (when used on 4.2; on 4.1 this issue didn't exist for me).

When the issue occurs I can see that `sys-net` has full web access (`curl www.google.com` returns the expected content immediately), but no other VM does, including disposables whose netVM I set directly to `sys-net`. What reliably fixes the issue is to turn WiFi off and on again (in `sys-net` NetworkManager) or unplug / replug the ethernet cable (also managed by `sys-net` NetworkManager).

**Comment by neoniobium** [comment]
> > @neoniobium did you upgrade to Qubes 4.2 now and it disappeared? Strangely I had no such issue on 4.1, but it doesn't seem to go away on 4.2 :(
> 
> Yes did a complete reinstall, not just an upgrade, however. For the last few days I did not experience this issue. Nevertheless I have only done something like 10 boots until now.
> 
> On `4.1` I had this happen in approximately in 1 out of 5 boots.
> 
> If I notice a this happen to me on `4.2` I will comment on this issues I try to debug it.

I have this happened to me for the first time on `Q4.2` today. Suspiciously it happened after I changed all `sys-vms` templates from `debian-12-xfce` to templates based on `debian-12-minimal`.

**Comment by neoniobium** [comment]
> I have this happened to me for the first time on `Q4.2` today. Suspiciously it happened after I changed all `sys-vms` templates from `debian-12-xfce` to templates based on `debian-12-minimal`.

At least for me increasing the `firewall` VMs `memory` to `400` solved the issues for one week now. I can reproduce the issue if the decrease the `memory` again.

**Comment by UndeadDevel** [comment]
>At least for me increasing the firewall VMs memory to 400 solved the issues for one week now. I can reproduce the issue if the decrease the memory again.

Interesting, but that doesn't seem to be the cause for me, as my `sys-firewall` already has 1 GB of RAM.

**Comment by UndeadDevel** [comment]
Haven't seen this issue at all when using a different WiFi AP for a while...other computers didn't have this issue with the prior (problematic) one, however, including a bare metal Fedora PC. I'll keep reporting when it shows up again for a different AP for my Qubes machine.

**Comment by UndeadDevel** [comment]
Cannot currently reproduce the issue anymore, even at the old (previously problematic) AP; haven't seen it in 2 or 3 months even though it used to happen pretty frequently...maybe some update fixed it.

Closing for now; will re-open if it re-occurs.
