### ISSUE TITLE
`qvm-run --all` does not autostart qubes

### ISSUE THREAD

**Issue by UndeadDevel** [QubesOS/qubes-issues#8755]
### Qubes OS release
4.2rc5

### Brief summary
When using `qvm-run` with the `--all` option it will not autostart all qubes (or rather all qubes that have not been excluded with `--exclude`). This is probably intended, but it would be nice if the help and man page included this information, as both currently state that `-a` is the implicit default. Even when using `-a` explicitly together with `--all` it will not autostart any qubes.

### Steps to reproduce
1. `qvm-run -a --all -- ls -a` while some qubes are halted
2. observe that no qube is started

### Expected behavior
Either it autostarts all non-excluded qubes or (probably better) the man page and help text are updated to reflect the actual behavior.

I suppose ideally the `-a` option would be implicit in those cases when `--all` is not used, and possible to use explicitly if the `--all` option is used. This should also be reflected in the documentation.

### Actual behavior
`-a` option is always disabled when `--all` option is used, even if `-a` is specified explicitly

**Comment by marmarek** [comment]
> but it would be nice if the help and man page included this information,

The help text literally says:
```
  --all                 run command on all running qubes
```

**Comment by UndeadDevel** [comment]
Oops my bad, I actually missed that (I was tired when looking over help options); the man page, however, says:
> Run the command on all qubes. You can use --exclude to limit the qubes set. Command is never run on the dom0.

So "all qubes" (and then there's a grammatical mistake at the end, as it should be "never run on dom0", without the definite article).
