### ISSUE TITLE
Displays settings opened for all running qubes when external monitor is connected

### ISSUE THREAD

**Issue by UndeadDevel** [QubesOS/qubes-issues#8756]
### Qubes OS release
4.2rc5

### Brief summary
I think I saw someone report this on forum, but I couldn't find an issue for it; anyway, now it happens on my machine, too:
Connecting an external monitor used to only open "Displays" settings for dom0 in Q4.1.2, but now it opens them for all running qubes, which makes a mess on that workspace.

### Steps to reproduce
NV41 laptop: connect external monitor to HDMI port (seems to happen only for the first time connecting a monitor per session)

### Expected behavior
only opens "Displays" settings for dom0 as on Q4.1.2

### Actual behavior
opens "Displays" settings for all running qubes

**Comment by DemiMarie** [comment]
For me it does not open display settings for _any_ monitor (System76 Darter Pro 8).

**Comment by UndeadDevel** [comment]
Curiously, now that I tried it again it was different: it didn't open any settings, but still took about 15 seconds of screens flickering to allow me to use the monitor. I was then able to manually open the "Displays" settings via the hotkey. On 4.1.2 it always quickly and reliably started outputting on both monitors in mirror mode and popped up the settings in dom0 for switching modes automatically.

I'll test it more and report back.

**Comment by marmarek** [comment]
I can reproduce the issue.
