### ISSUE TITLE
PipeWire module should be a driver

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#8770]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### The problem you're addressing (if any)

The PipeWire module needs to be a PipeWire driver so that it can work around scheduling problems in Xen VMs.

### The solution you'd like

Make the PipeWire module a PipeWire driver.

1. [ ] Use a timer to drive the graph.
2. [ ] If playback is active, use playback to drive the graph.
3. [ ] If recording is active (#8764) use recording to drive the graph.
4. [ ] If recording is active, implement rate matching on playback.

### The value to a user, and who that user might be

Users who use the PipeWire module for audio (which is the default in Debian 12+ and Fedora VMs) will have better audio.

**Comment by neowutran** [comment]
I am having an issue that seems similar or identical ? : 
 
I have 2 computers with QubesOS on it. Both use a audiovm with pipewire. 

On my most powerful computer I have no issues at all with sound.
On the second computer (a intel NUC), the sound recorded by the microphone is un-usable (too bad quality to understand anything ). 
This issue only appeared when I switched from pulseaudio to pipewire in my audiovm 

(The recording hardware is the same, connected by JACK).

**Comment by marmarek** [comment]
Implemented in https://github.com/QubesOS/qubes-gui-agent-linux/pull/205 ?

**Comment by DemiMarie** [comment]
yup!
