### ISSUE TITLE
Persistent warnings about runaway Lua forks when using new updater on fedora templates

### ISSUE THREAD

**Issue by UndeadDevel** [QubesOS/qubes-issues#8771]
### Qubes OS release
4.2rc5

### Brief summary
Happens consistently for `fedora-38-xfce` and `fedora-38`, but not for the `debian-12`(+`-xfce`) templates:
```
Updating fedora-38-xfce
b'warning: runaway fork() in Lua script\n'
b'warning: runaway fork() in Lua script\n'
b'warning: runaway fork() in Lua script\n'
b'warning: runaway fork() in Lua script\n'
b'warning: /etc/java/java-17-openjdk/java-17-openjdk-17.0.9.0.9-1.fc38.x86_64/conf/security/java.security created as /etc/java/java-17-openjdk/java-17-openjdk-17.0.9.0.9-1.fc38.x86_64/conf/security/java.security.rpmnew\nwarning: /etc/java/java-17-openjdk/java-17-openjdk-17.0.9.0.9-1.fc38.x86_64/conf/security/nss.fips.cfg created as /etc/java/java-17-openjdk/java-17-openjdk-17.0.9.0.9-1.fc38.x86_64/conf/security/nss.fips.cfg.rpmnew\nwarning: /etc/java/java-17-openjdk/java-17-openjdk-17.0.9.0.9-1.fc38.x86_64/lib/security/public_suffix_list.dat created as /etc/java/java-17-openjdk/java-17-openjdk-17.0.9.0.9-1.fc38.x86_64/lib/security/public_suffix_list.dat.rpmnew\n'
b'warning: runaway fork() in Lua script\n'
b"/bin/kdumpctl: line 1270: grubby: command not found\nkdump: kernel 6.6.6-100.fc38.x86_64 doesn't exist\n"
b'warning: runaway fork() in Lua script\n'
b'warning: runaway fork() in Lua script\n'
```

### Steps to reproduce
Update either of the standard fedora-38 templates using the new GUI updater and observe output after clicking on the template name.

### Expected behavior
No persistent warnings in standard configuration (I'm referring to the `warning: runaway fork() in Lua script` parts of the above log).

### Actual behavior
Persistent warnings on every update even though I haven't messed with the update mechanism at all.

**Comment by UndeadDevel** [comment]
More user reports: https://forum.qubes-os.org/t/qubes-users-updating-fedora-38-bwarning-runaway-fork-in-lua-script-n/24469

**Comment by DemiMarie** [comment]
I think this is just a bug in RPM, and they are already workin a fix.  If so, this would be <https://github.com/QubesOS/qubes-issues/labels/R%3A%20upstream%20issue>, but I don’t want to close this issue myself.  @marmarek @andrewdavidwong what do you think?

**Comment by UndeadDevel** [comment]
It seems this was fixed upstream by now as I'm not seeing any such warnings anymore.
