### ISSUE TITLE
No microcode updates on kernels other than 6.6.x

### ISSUE THREAD

**Issue by 3hhh** [QubesOS/qubes-issues#8772]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
4.1

### Brief summary
After the [most recent QSB](https://github.com/QubesOS/qubes-secpack/blob/master/QSBs/qsb-098-2023.txt) I checked whether microcode was loaded on my `5.10.200-1` kernel and noticed that it wasn't.

### Steps to reproduce
1. Boot an affected kernel.
2. Check `sudo dmesg | grep microcode`

### Expected behavior

Shows some output about `early update` or so.

### Actual behavior

Shows nothing on my system.

### Additional notes

It's a T530 with i7-3720QM running heads. A firmware update is definitely installed at `/lib/firmware/intel-ucode/06-3a-09`.

**Comment by 3hhh** [comment]
Hm ok according to `iucode-tool -l /lib/firmware/intel-ucode/06-3a-09` and `cat /proc/cpuinfo` the update was applied or there's no update needed or possible.

I'd nonetheless have expected some entry in `dmesg` about that though?

**Comment by marmarek** [comment]
> I'd nonetheless have expected some entry in `dmesg` about that though?

No, it's isn't Linux loading the microcode. Xen does it. You can find relevant message in `xl dmesg`.

**Comment by 3hhh** [comment]
On 12/16/23 11:48, Marek Marczykowski-Górecki wrote:
>> I'd nonetheless have expected some entry in `dmesg` about that though?
> 
> No, it's isn't Linux loading the microcode. Xen does it. You can find relevant message in `xl dmesg`.

Thanks for the clarification!

`xl dmesg` however doesn't show any related information with regards to microcode updates either.

So while I agree that my initial assessment is likely incorrect, Xen behaviour at least on my machine is rather weird and unhelpful nonetheless.

**Comment by marmarek** [comment]
> Hm ok according to `iucode-tool -l /lib/firmware/intel-ucode/06-3a-09` and `cat /proc/cpuinfo` the update was applied or there's no update needed or possible.

If you see no message about applying the update, apparently it wasn't needed (already using latest version).
