### ISSUE TITLE
libvchan_is_open() isn’t realtime-safe

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#8787]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

R4.2

### Brief summary

`libvchan_is_open()` isn’t realtime-safe, as it calls `xc_evtchn_status` which ultimately calls `pthread_mutex_lock()`.

### Steps to reproduce

Single-step through `libvchan_is_open()` in GDB.

### Expected behavior

No locking functions called.

### Actual behavior

Locking functions called.

Simplest fix is likely to call the raw kernel ioctl instead of the Xen API function.

**Comment by marmarek** [comment]
> Simplest fix is likely to call the raw kernel ioctl instead of the Xen API function.

Nope, `xc_evtchn_status` is one (the only?) event channel operation that doesn't have direct ioctl interface, it goes through privcmd, and the libxenctrl does require locking to access it in its current implementation (IIUC to allocate hypercall bounce buffer).
While I'd like to have ioctl for this operation, your proposed simple change unfortunately isn't that simple.

Anyway, if you don't call `libvchan_is_open()` from different threads at the same time, you won't ever wait on that lock, so I don't think it's any practical issue.

**Comment by DemiMarie** [comment]
> > Simplest fix is likely to call the raw kernel ioctl instead of the Xen API function.
> 
> Nope, `xc_evtchn_status` is one (the only?) event channel operation that doesn't have direct ioctl interface, it goes through privcmd, and the libxenctrl does require locking to access it in its current implementation (IIUC to allocate hypercall bounce buffer). While I'd like to have ioctl for this operation, your proposed simple change unfortunately isn't that simple.

Allocating memory isn’t realtime safe either.  The standard solution is to use a caller-supplied preallocated buffer.

> Anyway, if you don't call `libvchan_is_open()` from different threads at the same time, you won't ever wait on that lock, so I don't think it's any practical issue.

Is this a process-wide lock?  I’m not sure I can guarantee this.

**Comment by marmarek** [comment]
> Allocating memory isn’t realtime safe either. The standard solution is to use a caller-supplied preallocated buffer.

It seems to have a pool of buffers (in fact the lock is guarding just taking pre-allocated buffer from the pool), so even allocation will happen rarely.

Anyway, I highly doubt this is causing any issues in your context.
