### ISSUE TITLE
Whitespace in policy file name (Policy Editor)

### ISSUE THREAD

**Issue by johnnyboy-3** [QubesOS/qubes-issues#8795]
### Qubes OS release
R4.2

### Brief summary
When using whitespaces in the policy editor as new policy file name, the Policy Editor won't save and prints an error message.

### Steps to reproduce
1. Open Qubes Policy Editor
2. File -> New -> "test file" (without ")
3. qubes.Filecopy * work @dispvm allow
4. Save Changes

### Expected behavior
Policy file saved to disk.

### Actual behavior
An error occured while trying to save the policy file: Internal error. See /var/log/qubes/policy-admin.log in dom0 for details.

```
2023-12-27 15:22:44,628 policy.Replace+test file (dom0): exception
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/qrexec/tools/qubes_policy_admin.py", line 53, in main
    response = admin.handle_request(service_name, argument, payload)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/qrexec/policy/admin.py", line 90, in handle_request
    assert all(char in RPCNAME_ALLOWED_CHARSET for char in arg)
AssertionError
```

### Suggested Solution
Don't allow whitespaces when at step #2.
Not tested: And don't allow other characters as well that could potentially break (injection wise ; + ( ) ' " { } * # $()  `` ... )

**Comment by alimirjamali** [comment]
> ### Qubes OS release
> 
> R4.2
> ### Brief summary
> 
> When using whitespaces in the policy editor as new policy file name, the Policy Editor won't save and prints an error message.
> ### Steps to reproduce
> 
>     1. Open Qubes Policy Editor
> 
>     2. File -> New -> "test file" (without ")
> 
>     3. qubes.Filecopy * work @dispvm allow
> 
>     4. Save Changes
> 
> 
> ### Expected behavior
> 
> Policy file saved to disk.
> ### Actual behavior
> 
> An error occured while trying to save the policy file: Internal error. See /var/log/qubes/policy-admin.log in dom0 for details.
> 
> ```
> 2023-12-27 15:22:44,628 policy.Replace+test file (dom0): exception
> Traceback (most recent call last):
>   File "/usr/lib/python3.11/site-packages/qrexec/tools/qubes_policy_admin.py", line 53, in main
>     response = admin.handle_request(service_name, argument, payload)
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.11/site-packages/qrexec/policy/admin.py", line 90, in handle_request
>     assert all(char in RPCNAME_ALLOWED_CHARSET for char in arg)
> AssertionError
> ```
> 
> ### Suggested Solution
> 
> Don't allow whitespaces when at step #2. Not tested: And don't allow other characters as well that could potentially break (injection wise ; + ( ) ' " { } * # $() `` ... )

[By design](https://github.com/QubesOS/qubes-core-qrexec/blob/main/qrexec/__init__.py#L48-L50) it only allows letters, numbers, plus sign, minus sign, dot and underline. I personally preferred if it forced letters and numbers for the 1st character (but that is another issue).

> Don't allow whitespaces when at step #2

Having said that, you are right about the above point. It is relatively easy to fix. I will work on it.

**Comment by alimirjamali** [comment]
I personally preferred this to happen at the time of entering the filename (rather at saving time). But let's keep this simple and patch only one repository. User can copy/paste their draft policy.

![policy](https://github.com/user-attachments/assets/80923a83-770f-427e-a9f2-7beaa3f8642f)

**Comment by alimirjamali** [comment]
It is more complex. It appears that we have two non-conforming logic to validate policy file names:

1. One in `qubes-core-qrexec`. [Here](https://github.com/QubesOS/qubes-core-qrexec/blob/main/qrexec/policy/admin.py#L90) and [here](https://github.com/QubesOS/qubes-core-qrexec/blob/main/qrexec/__init__.py#L48-L50).
2. One in `qubes-desktop-linux-manager` [here](https://github.com/QubesOS/qubes-desktop-linux-manager/blob/main/qubes_config/policy_editor/policy_editor.py#L408-L414).

@marmarek any suggestion?

**Comment by ben-grande** [comment]
> p.s. Regex for the 2nd case should be r'^[\w-]+$'. But the discrepancy remains.

I'm not marmarek but I suggest to use the same method on both files to avoid having such discrepancies.

The correct method I commented on your PR:

https://github.com/QubesOS/qubes-core-qrexec/pull/176#issuecomment-2371057337
