### ISSUE TITLE
No network after upgrade to 4.2

### ISSUE THREAD

**Issue by 3hhh** [QubesOS/qubes-issues#8799]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
4.2

### Brief summary
After upgrading from 4.1 to 4.2 no network was available in netvms based on `debian-12`. `fedora-38` worked.

### Steps to reproduce
1. Upgrade as per upgrade instructions.
2. Use `debian-12` templates for `sys-net` and `sys-fw`.

### Expected behavior
Works.

### Actual behavior
Doesn't work.

### Root cause

```
root@debian-12:/home/user# systemctl status xendriverdomain.service
× xendriverdomain.service - Xen driver domain device daemon
     Loaded: loaded (/etc/systemd/system/xendriverdomain.service; enabled; preset: enabled)
     Active: failed (Result: exit-code) since Thu 2023-12-28 14:19:07 CET; 1min 29s ago
    Process: 695 ExecStart=/usr/sbin/xl devd (code=exited, status=127)
        CPU: 1ms

Dec 28 14:19:07 debian-12 systemd[1]: Starting xendriverdomain.service - Xen driver domain device daemon...
Dec 28 14:19:07 debian-12 xl[695]: ERROR:  Unable to execute /usr/lib/xen-4.17/bin/xl
Dec 28 14:19:07 debian-12 systemd[1]: xendriverdomain.service: Control process exited, code=exited, status=127/n/a
Dec 28 14:19:07 debian-12 systemd[1]: xendriverdomain.service: Failed with result 'exit-code'.
Dec 28 14:19:07 debian-12 systemd[1]: Failed to start xendriverdomain.service - Xen driver domain device daemon.
```

### Fix

Install missing `xen-utils-4.17` in `debian-12`.

**Comment by 3hhh** [comment]
`xen-utils-4.14` was installed, but `xen-utils-4.17` required.

**Comment by marmarek** [comment]
> `xen-utils-4.14` was installed, but `xen-utils-4.17` required.

`xen-utils-4.14` is supposed to work too, if `xen-utils-guest` is installed too. Do you have it?

**Comment by 3hhh** [comment]
On 12/30/23 12:16, Marek Marczykowski-Górecki wrote:
>> `xen-utils-4.14` was installed, but `xen-utils-4.17` required.
> 
> `xen-utils-4.14` is supposed to work too, if `xen-utils-guest` is installed too. Do you have it?

***@***.***:/home/user# dpkg -l|grep xen-util
ii  xen-utils-4.14                          4.14.6-4+deb12u1                        amd64        XEN administrative tools
ii  xen-utils-4.17                          4.17.2+76-ge1f9cb16e2-1~deb12u1         amd64        Xen administrative tools
ii  xen-utils-common                        4.17.2+76-ge1f9cb16e2-1~deb12u1         amd64        Xen administrative tools - common files
ii  xen-utils-guest                         4.14.6-4+deb12u1                        amd64        Xen administrative tools - guest files

(4.17 was manually installed by me as the fix.)

Btw other affected user: https://forum.qubes-os.org/t/networking-broken-in-debian-based-templates-after-r4-2-upgrade/23144/9

**Comment by trizzosk** [comment]
Fix did not worked for me, since both packages were already installed.

Only fedora-38/39 templates works for sys-firewall and several sys-vpn machines (I use multiple VPNs each in separate appvm providing network to other appvms). Also - fedora-38-xfce does not work for sys-firewall and sys-vpn.
