### ISSUE TITLE
Gnome on dom0

### ISSUE THREAD

**Issue by coderedshark** [QubesOS/qubes-issues#8801]
Hi there,

I've been using qubes os for some time now and wanted to know if you're still working on getting gnome working on dom0 or if this is still considered an option. I think it would increase usability for less technically advanced users and I know there have been discussions about this in the past, which however didn't lead to success. If this would still be an option, I would like to know what exactly the requirements for this would be, because I would very much like to support this project in making this work. At the moment I have a somewhat hacky version of qubes which runs gnome, but there are still some features missing.

**Comment by DemiMarie** [comment]
Duplicate of #1806
