### ISSUE TITLE
run default terminal instead of xterm while executing qubes-dom0-update

### ISSUE THREAD

**Issue by Middenvaus** [QubesOS/qubes-issues#8804]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### The problem you're addressing (if any)
Due to small font size in xterm by default I will prefere in future using xfce4-terminal

### The solution you'd like

For example, we can set bigger xterm default font size in qubes-dom0-update bash script or use xfce4-terminal for dom0 update operation

**Comment by marmarek** [comment]
This separate terminal window in qubes-dom0-update is completely gone in R4.2, so it doesn't apply anymore.

**Comment by DemiMarie** [comment]
Should this be reopened to be about `qvm-console-dispvm`?  That also uses xterm, and it is still present in R4.2.
