### ISSUE TITLE
Craete New Qube fields should be keyboard-searchable

### ISSUE THREAD

**Issue by GammaSQ** [QubesOS/qubes-issues#8819]
### Qubes OS release

4.2

### Brief summary

when adding a new qube via the GUI-tool, a lot of options are available in drop-down-menus. In earlier versions, these menus could be used with the keyboard (i.e. navigate to the menu via tab => start typing => option matching typed characters is selected)

### Steps to reproduce
open Create New Qube GUI.
enter random chars as name.
hit tab. [label should appear selected]
hit `y`

### Expected behavior
`yellow` label should be selected.

### Actual behavior
`red` stays selected.

the same issue is present for all other fields.
It is likely an issue with global config editor as well, however, just when I wanted to check: https://github.com/QubesOS/qubes-issues/issues/8818

**Comment by UndeadDevel** [comment]
This seems more like an enhancement request, but in any case, it's related to #8747
