### ISSUE TITLE
Include keyword search in new app menu search

### ISSUE THREAD

**Issue by UndeadDevel** [QubesOS/qubes-issues#8826]
### The problem you're addressing (if any)
Since 4.2 I'm largely using the new App Menu to launch applications instead of Xfce's Application Finder, but the latter still has some advantages (see also #8662), one of which is that it searches not just the app names, but also app keywords (defined in the app's desktop file).

### The solution you'd like
Search the `Keywords` of applications (from their desktop files) as well as the `Name`s when doing a search in the new App Menu.

### The value to a user, and who that user might be
- Is more consistent with Application Finder, which some will also use or have used on 4.1 and prior.
- Gives more flexibility to both the packager and user as the name is more constrained than keywords are

**Comment by UndeadDevel** [comment]
I don't think this is actually fixed...

I see:
```
rpm -qa qubes-desktop-linux-menu
qubes-desktop-linux-menu-1.2.0-1.fc37.noarch
```

Correct me if I'm wrong, but that version (from `current-testing`) should include this fix; however, after updating the app shortcuts for a DVM template as well as a named DVM I have, where there is, under `/usr/local/share/applications` the file `ytfzf.desktop` with content:
```
[Desktop Entry]
Type=Application
Name=YouTube FzF
Comment=Watch YouTube videos without a browser
Icon=mpv
Exec=gnome-terminal --title=YTFzF --geometry=211x29 -- ytfzf -lts -T mpv --ytdl-pref='ba+bv[height<=?1080][dynamic_range=?SDR]/b[height<=?1080][dynamic_range=?SDR]' %U
Terminal=true
Categories=AudioVideo;Audio;Video;Player;TV;
Keywords=youtube;ytfzf;yt-dlp;
```
searching in the app menu for `ytfz` shows no results, even though it should due to above desktop file, which has the `ytfzf` keyword...the dom0 Xfce Application Finder does show the correct entry when I search for `ytfz` with it.

Requesting for this to be re-opened.

**Comment by marmarek** [comment]
The updated menu searches for keywords too, try for example "explorer", it should find Thunar in dom0.
The issue you see if that keywords from apps in qubes are not retrieved as they weren't relevant before.

**Comment by UndeadDevel** [comment]
>The updated menu searches for keywords too, try for example "explorer", it should find Thunar in dom0.
The issue you see if that keywords from apps in qubes are not retrieved as they weren't relevant before.

Point taken; can confirm that keyword search works for dom0 apps.

However, users aren't supposed to be launching lots of dom0 apps anyway; this might be a miscommunication then, I should have been more clear. What this issue was supposed to be about is exactly the keywords of desktop files in TemplateVMs and AppVMs, as those are for the apps that get used. Basically preserve the search space that the Xfce Application Finder has (which does find apps from AppVMs via their desktop file keywords), as I've indicated in the OP.
