### ISSUE TITLE
Double-clicking items in the "Applications" tab list should move them to the other list

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#8836]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### The problem you're addressing (if any)

1. Go into a qube's settings.
2. Go to "Applications" tab.
3. Double-click an item in the list.
4. Nothing happens.

### The solution you'd like

Double clicking should do something. I think it should move that item to the other list (i.e., from "Available" to "Selected" or vice versa).

### The value to a user, and who that user might be

More intuitive UX, like the way most other software behaves.

**Comment by alimirjamali** [comment]
Related: #4248

**Comment by alimirjamali** [comment]
PR Submitted. I will work on #4248 next. This should give users some relief while #6366 is being worked on.

**Comment by alimirjamali** [comment]
Drag &Drop is also ready. I would like to wait for the result of this PR review before submitting the DND patch. This is to avoid over-cluttering the review pipeline. And it appears that #4248 is not exactly about DND within VM Settings App Tab.

Please also inform me if the double click -> move-to-other-side and DND should be implemented for devices tab or not.
