### ISSUE TITLE
Element flatpak eats user data in `fedora-39-xfce`

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#8839]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

R4.2

### Brief summary

Qubes based on `fedora-39-xfce` don’t have any implementation of `org.freedesktop.portal.Secret` on the user D-Bus instance. 
 Without a working implementation of this service, the Element flatpak eats user data.  This is a partially a bug in Element or the flatpak, but it is still something Qubes OS should work around.

### Steps to reproduce

Switch the template of a qube running the Element flatpak from `fedora-38` to `fedora-39-xfce`.

### Expected behavior

Element still works.

### Actual behavior

Element can’t access any of its secrets, preventing it from accessing encrypted messages or connecting to the server. 
 Subsequent starts of Element cause Element to delete its own storage.

**Comment by marmarek** [comment]
FWIW, Fedora 39 templates are still in testing.

**Comment by marmarek** [comment]
This is upstream issue at https://github.com/flatpak/xdg-desktop-portal/pull/1199. The fix is already committed, and should be part of 1.18.2. So, maybe it's just a matter of installing updates (and also, rebuilding the template before pushing it to the sable repo)?

**Comment by marmarek** [comment]
That upstream fix is about most portals but not about the secrets one...

**Comment by DemiMarie** [comment]
> This is upstream issue at [flatpak/xdg-desktop-portal#1199](https://github.com/flatpak/xdg-desktop-portal/pull/1199). The fix is already committed, and should be part of 1.18.2. So, maybe it's just a matter of installing updates (and also, rebuilding the template before pushing it to the stable repo)?

Nope, Fedora 39 has 1.18.2 already.  The reason this does not work is that `xdg-desktop-portal-gtk` doesn’t provide the secret portal.  `gnome-keyring` does, but `gnome-keyring` has `UseIn=gnome`, and Qubes OS does not (and, IMO, should not) claim to be GNOME.

I recommend unconditionally using `gnome-keyring` for the secret portal.  I’m not aware of any other implementations, and even if they existed I don’t know if we should use them.  The reason is that changing the template a VM is based on must not cause existing secrets to be inaccessible if we can at all help it.
