### ISSUE TITLE
rework qubes-logo-icon to eliminate blurred edges

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#884]
**Reported by woju on 11 Jul 2014 19:33 UTC**
Currently icons are generated from 256x256 svg and look blurry.

Migrated-From: https://wiki.qubes-os.org/ticket/884

**Comment by comradekingu** [comment]
@marmarek Link to or image of offending icon?

**Comment by marmarek** [comment]
@woju do you remember what it was about? AFAIR it was about launcher icon in KDE.
If that's the case - take a look at https://github.com/QubesOS/qubes-artwork/tree/master/icons/scalable/places
And output for example here: https://github.com/QubesOS/qubes-artwork/tree/master/icons/32x32/places

**Comment by ttasket** [comment]
I noticed the bitmapped launcher logo gets rather blocky when expanding the taskbar panel. I changed it to one of those scalable svgs you referenced, Marek, and it looks great now.

**Comment by unman** [comment]
@andrewdavidwong I believe this issue is resolved in 3.2, and can be closed.
