### ISSUE TITLE
Change Builder dispvm configuration to be dom0

### ISSUE THREAD

**Issue by ben-grande** [QubesOS/qubes-issues#8842]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### The problem you're addressing (if any)

Currently, I use a different name for `dispvm`, so I have to update the `builder.yml` always.
```
example-configs/builder-devel.yml:253:#    dispvm: "qubes-builder-dvm"
example-configs/qubes-os-main.yml:189:    dispvm: "qubes-builder-dvm"
example-configs/qubes-os-r4.2-dom0.yml:31:    dispvm: "qubes-builder-dvm"
example-configs/qubes-os-r4.2.yml:189:    dispvm: "qubes-builder-dvm"
```

### The solution you'd like

Always use `dispvm: dom0`, it will use the property `default_dispvm` of the Qubes Builder qube to find the disposable template.

It is already instructed to set the `default_dispvm` in the [README](https://github.com/QubesOS/qubes-builderv2/?tab=readme-ov-file#qubes-executor).

The policy has to change from
```
admin.vm.CreateDisposable * work-qubesos dvm-qubes-builder allow target=dom0
```

to
```
admin.vm.CreateDisposable * work-qubesos dom0 allow
```

and `executor:dispvm` to `dom0`.

The policy I have to change anyway because the source qube is not `work-qubesos` for me, but that is on Dom0 and the change is made once and deployed with salt, while on the DomU builder, after I update the repository, I have to edit the example-configs again and again.

### The value to a user, and who that user might be

Users that use a different name for the qubes builder dvm will not have to edit the `builder.yml`.

----

I can PR the change if this request is accepted.

**Comment by ben-grande** [comment]
I saw last related commit was https://github.com/QubesOS/qubes-builderv2/commit/5d1bd989a52f5dc8900888fafec2da919306610f, which was part of the PR https://github.com/QubesOS/qubes-builderv2/pull/38.

Can the dispvm option be set to dom0 so default_dispvm of the qube is used? If the user wants to target a different dvm, they only have to change the setting from Dom0 policy and qvm-prefs, much easier to keep up than editing example-configs.

**Comment by marmarek** [comment]
> I have to edit the example-configs again and again.

Not really, you can have `builder.yml` with:
```
include:
- example-configs/qubes-os-r4.2.yml

executor:
  type: qubes
  options:
    dispvm: "whatever-you-like"
```

**Comment by ben-grande** [comment]
> Not really, you can have `builder.yml` with:

That helps a lot, my old way was to replace the file with the examples... but this still requires a change in DomU when the setting, in my opinion, should be controlled by Dom0 to allow less modifications of the builder.yml.

Of course advanced users can use different executors for different stages, but a simple setup would avoid changing the builder configuration in DomU and the policy in Dom0.

If you disagree with the changes proposed in https://github.com/QubesOS/qubes-builderv2/pull/83, I will close this issue and the PR.
