### ISSUE TITLE
Enabling "security-testing" repo in new Global Config app breaks most dom0 updates and ability to install most packages

### ISSUE THREAD

**Issue by UndeadDevel** [QubesOS/qubes-issues#8857]
### Qubes OS release
4.2

### Brief summary
When choosing the "Enable security-related testing updates only" option in the new Global Config app, section "Updates", almost no updates are actually received and packages, such as `qubes-repo-contrib` cannot be found.

If this is not intended behavior then it seems a pretty severe bug; when putting the selection back to "Enable stable updates only" and updating dom0, I received more than a dozen updates and was able to install `qubes-repo-contrib`. Therefore, my intention, which was to be ahead of the curve in keeping my system up to date with security-related updates while still receiving all updates for other packages, actually backfired and left my system behind with many packages, including ones that are presumably security related, such as `xen`, `xen-hypervisor`, `xen-libs`, `qubes-core-dom0`, `qubes-utils` etc...

After thinking about it more, this may be the intended behavior, as that option may be intended only for that one repo instead of what I thought, namely that it will install all stable packages and additionally security-related ones before they become stable, in which case I ask to change this issue to an enhancement request (the user should be told that this option should only be enabled temporarily for specific updates, not left as a permanent choice; alternatively, the behavior that I assumed and described above should be implemented).

### Steps to reproduce
1. Enable the option "Enable security-related testing updates only" option in the new Global Config app, section "Updates"
2. try to install e.g. `qubes-repo-contrib`

### Expected behavior
Enabling that option keeps access to stable repo open, but prefers packages in security-testing for those packages that are present in both repos.

### Actual behavior
Enabling that option breaks regular dom0 updates and ability to install common packages.

**Comment by Augsch123** [comment]
I can confirm that enabling "security-testing" repo in new Global Config app indeed disables [qubes-dom0-current] repo in `/etc/yum.repos.d/qubes-dom0.repo`.

I think this is a bug rather than intended behavior.

**Comment by GammaSQ** [comment]
This update should be published to "security-testing" as well.
I unwittingly had my update policy on "security-testing" and just found out about this bug and solution, because updates started to fail.

**Comment by marmarek** [comment]
A newer update _is_ published to security-testing already: https://github.com/QubesOS/updates-status/issues/4662

**Comment by GammaSQ** [comment]
Hm. What I know for sure is that I didn't get stable release updates until I manually enabled "stable" in the global settings. I confirmed before updating that in `/etc/yum.repos.d/qubes-dom0.repo` the `[qubes-dom0-current]` section hat `enabled = 0` set.

Updating from stable fixed this and now both `[qubes-dom0-current]` and `[qubes-dom0-securit-testing]` show `enabled = 1`

**Comment by marmarek** [comment]
The update fixes the configuration tool, but does not change the repository configuration - this will happen only after you open settings and save them again.
