### ISSUE TITLE
`qvm-run` of yubikey solution not returning anything when screen locked

### ISSUE THREAD

**Issue by UndeadDevel** [QubesOS/qubes-issues#8859]
### Qubes OS release
4.2

### Brief summary
I'm trying to set up my NK3 to unlock the screen just like the Yubikey solution from the docs. I installed `qubes-yubikey-dom0` and modified the `yk-auth` script to use NK commands instead of YK ones. The commands work when running them from a dom0 terminal or by calling a script with them, both as user and as root, without the screen being locked, but not when using them as part of the solution (during locked screen).

In fact, modifying the `yk-auth` script to just do `response=$(qvm-run -p sys-usb "ls /home/user/");echo $response > /home/user/result`, then locking and unlocking the screen, shows nothing (just a newline character) in the result file, while the same command running from a terminal will list the folders in user home of sys-usb.

The `yk-auth` script is definitely called, though; putting `exit 0` as the only thing will unlock the screen when I press `Enter`.

Posting as a bug and not in forum as a support request, because I don't see how this should work with a Yubikey if nothing is returned from commands using `qvm-run` while the screen is locked, so that component seems to be broken.

### Steps to reproduce
1. Set up the `qubes-yubikey-dom0` app and modify the script to return anything at all from sys-usb (I don't have a YubiKey to test the original functionality, but it's probably also broken)
2. Lock the screen
3. Press enter
4. Check the return

### Expected behavior
`qvm-run` works as when the screen isn't locked

### Actual behavior
Doesn't work.

**Comment by marmarek** [comment]
This might be about access to `/run/qubesd.sock` when called from xscreensaver (AFAIR it may drop auxiliary groups, so the `qubes` group). And if that's the case, it would affect yubikey script too.

Try adding this at the top of the script:
```
if ! [ -w /run/qubesd.sock ] && [ -z "$YKAUTH_REXEC" ]; then
	exec sg qubes "YKAUTH_REXEC=1 $0 $*"
fi
```

**Comment by UndeadDevel** [comment]
Perfect! Now it works :+1: 

I'll leave to you to close unless you want me to try to whip up a PR for this myself.

I may also create a new module and doc for my solution with the NitroKey3, but probably next week or so.

Thanks!
