### ISSUE TITLE
Support UUIDs in the Admin API

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#8862]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### The problem you're addressing (if any)

VM names can be reused.

### The solution you'd like

Allow UUIDs to be passed instead in the Admin API

### The value to a user, and who that user might be

See also #8510.

**Comment by alimirjamali** [comment]
Is `qvm-ls` updated yet to utilize this new feature and provide UUID column? Or anyone is planning to work on it?

**Comment by alimirjamali** [comment]
I submitted the PR (since I did not find any related open PR). I wonder if similar functionality should be added to `qvm-check` and other utilities. Theoretically if this is added to `qubesadmin.tools` argument parser, all commands could support uuid:<UUID> for vm selection.
