### ISSUE TITLE
fresh R4.2 installation, can't paste from Qubes Clipboard into destination qube

### ISSUE THREAD

**Issue by mfc** [QubesOS/qubes-issues#8866]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

fresh R4.2

### Brief summary

cant paste Qubes clipboard. i can copy into Qubes clipboard (and see notification). pasting Qube clipboard into a qube doesn't work. i tried changing the shortcut keys but it is the same.

looking at Qubes Policy Editor for the clipboard, the policy is: `qubes.ClipboardPaste * @anyvm @anyvm ask`. however the white-space / tabs looks wrong, i don't know if that is affecting it:

![policy-editor](https://github.com/QubesOS/qubes-issues/assets/1958481/c91eb6da-c936-43f2-a629-38506e9660c2)

### Steps to reproduce

copy some text locally in a qube, use shortcuts to copy to Qubes clipboard, receive notification of successful copy, use shortcut to past from Qubes clipboard, receive no notification nor text in destination qube.

### Expected behavior

Qubes clipboard pastes into destination qube.

### Actual behavior

Qubes clipboard does not paste into destination qube.

### similar

it is probably this issue: https://github.com/QubesOS/qubes-issues/issues/8497 as i am using USB keyboard, investigating

**Comment by mfc** [comment]
something strange is that the default policy is allow (as stated in Global Config -> Clipboard) but the policy says `ask`...

**Comment by ben-grande** [comment]
Space or tabs are stripped, that is not the problem. The resolution `ask` is also ok.

On Dom0:

`sudo journalctl -fu qubes-qrexec-policy-daemon`

If it is policy syntax error, the error will appear when trying to paste.

**Comment by mfc** [comment]
running that says: 

`qubes-qrexec-policy-daemon.service: Main process exited, code=dumped, status=11/SEGV`
`qubes-qrexec-policy-daemon.service: Failed with result 'core-dump'`

timestamp from yesterday, no further timestamps...

( i'm having different segfault issue with fresh R4.2, dunno if related: https://github.com/QubesOS/qubes-issues/issues/8865 )

**Comment by mfc** [comment]
did reboot and it's working as expected.... closing for now.
