### ISSUE TITLE
Qube Manager: Replace "IP" with "IP Address" in column title

### ISSUE THREAD

**Issue by emanruse** [QubesOS/qubes-issues#8872]
### Qubes OS release

4.1.x
4.2.0

### Brief summary

Qube Manager shows "IP" instead of "IP Address" in column title.

[IP address](https://en.wikipedia.org/wiki/Ip_address) is not the same as [IP](https://en.wikipedia.org/wiki/Internet_Protocol) and using colloquialism in UI design is inappropriate.

### Steps to reproduce

Run Qube Manager.

### Expected behavior

Use the correct term - IP Address.

### Actual behavior

Incorrect term - IP.

**Comment by alimirjamali** [comment]
PR submitted. Low priority for review
