### ISSUE TITLE
New Global Config app not closing if disposable in which doc link was opened is still running

### ISSUE THREAD

**Issue by UndeadDevel** [QubesOS/qubes-issues#8878]
### Qubes OS release
4.2

### Brief summary
When clicking on doc links in the new Global Config app, e.g. the link to "online documentation" on the "URL Handling" page, a new DVM will open with firefox to display the linked doc page. However, this will block finishing interactions with the app, as it will not close on "OK" or "Cancel" button presses until that DVM has shut down again.

### Steps to reproduce
1. In new Global Config app click on the "online documentation" link on the "URL Handling" page
2. try to close the Global Config app

### Expected behavior
app doesn't block due to opened doc links

### Actual behavior
app blocks due to opened doc links

**Comment by alimirjamali** [comment]
@UndeadDevel 
I created a patch for this and discussed it in detail on [forum](https://forum.qubes-os.org/t/github-issue-8878-new-global-config-app-not-closing-if-disposable-in-which-doc-link-was-opened-is-still-running/27114) . Hopefully this could be sent as a pull request after being tested for few days.

<details>
<summary>Patch</summary>
```diff
diff --git a/qubes_config/global_config/global_config.py b/qubes_config/global_config/global_config.py
index 078df78..447daa0 100644
--- a/qubes_config/global_config/global_config.py
+++ b/qubes_config/global_config/global_config.py
@@ -469,6 +469,11 @@ class GlobalConfig(Gtk.Application):
             page.reset()
 
     def _quit(self, _widget=None):
+        ''' Hide the main Window '''
+        self.main_window.hide()
+        while Gtk.events_pending():
+            Gtk.main_iteration()
+        ''' Then wait for disposable helper threads to finish '''
         self.quit()
 
     def _ok(self, widget):
@@ -479,6 +484,9 @@ class GlobalConfig(Gtk.Application):
         can_quit = self.verify_changes()
         if not can_quit:
             return True
+        self.main_window.hide()
+        while Gtk.events_pending():
+            Gtk.main_iteration()
         self.quit()
         return False
```
</details>

**Comment by alimirjamali** [comment]
I submitted a patch. The solution hides the main Gtk Window while the program waits for DisposableVM subprocess threads to close.
