### ISSUE TITLE
qfile-agent disk quota exceeded when trying to copy large directory to dom0

### ISSUE THREAD

**Issue by ben-grande** [QubesOS/qubes-issues#8880]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

R4.2

### Brief summary

Trying to copy a large directory to dom0 fails.

Related:
- https://github.com/QubesOS/qubes-issues/issues/3633#issuecomment-1900624266
- https://github.com/QubesOS/qubes-issues/issues/6889

### Steps to reproduce

Clone a big repository, such as https://github.com/git/git, it is ~294M

Try to copy it to dom0
> ```
> qvm-run -p  --localcmd="/usr/libexec/qubes/qfile-dom0-unpacker user /home/user/QubesIncoming/some-vm" some-vm /usr/lib/qubes/qfile-agent /home/user/file-or-dir-to-copy
> ``` 

Error message:
```
qfile-agent: Fatal error: File copy: "Disk quota exceeded; Last file: git/t/chainlint/chain-break-continue.expect" (error type: Disk quota exceeded)
```

But dom0 has enough size... or which filesystem should I check to expand?

### Expected behavior

At least notify which filesystem needs to be expanded.

### Actual behavior

Fails with `Disk quota exceeded`.

**Comment by marmarek** [comment]
There is size limit and file count limit by default. You can change them via env variables (`UPDATES_MAX_BYTES`, `UPDATES_MAX_FILES`). You can also set to zero to disable the limit, but be careful to not run out of space in dom0...

**Comment by ben-grande** [comment]
Thanks, maximum number of files were the problem.

- https://github.com/QubesOS/qubes-issues/issues/8882
