### ISSUE TITLE
 Expose all available prefs in qube GUI settings

### ISSUE THREAD

**Issue by emanruse** [QubesOS/qubes-issues#8890]
### The problem you're addressing (if any)

Not all qube preferences, seen through `qvm-prefs`, are visible in the GUI settings.

### The solution you'd like

Expose all available prefs in qube GUI settings (e.g. audiovm) and make them visible in Qube Manager columns.

### The value to a user, and who that user might be

Easier control of the currently hidden preferences through GUI.

**Comment by marmarta** [comment]
This is by design. At some level of complexity, we leave config in CLI-only. Things that are unlikely to be changed by a reasonable user in most cases usually don't go to GUI, because it makes GUI harder to use and more confusing.
