### ISSUE TITLE
Enabling "security-related testing updates only" might inhibit stable updates

### ISSUE THREAD

**Issue by pirateland** [QubesOS/qubes-issues#8899]
### Qubes OS release
4.2

### Brief summary
I was missing (important security?) stable updates (xen, linux, qubes, etc) on my 4.2 fresh install (of unknown 4.2 RC) where I set dom0 updates to "Enable security-related testing updates only" in the Qubes Global Config -> Updates. Setting it back to "Enable stable updates only" suddenly gave me a heap of updates (see log at the bottom).

### Long story
On my fresh 4.2 install (can't remember the RC), I enabled "Enable security-related testing updates only" shortly after installation in the Qubes Global Config (as the description besides it says this means stable **and** security testing updates). I updated my dom0 regularly, and also got dom0 updates semi-regularly. I did not notice something was wrong until I had a file conflict on updating dom0. Waiting for a few days did not solve the issue, and the issue tracker and the forum had no other posts with an issue like this.   
With the help of marmarek [over on the forum](https://forum.qubes-os.org/t/qubes-4-2-updating-fails-due-to-file-conflict/24043/5), I tried clearing/refreshing the cache, however that did not change my problem with the file conflict.  
While trying to figure out how this was happening, I went to the Global Config to see if I changed anything, and noticed something strange: my version under "this device" was still listed as 4.2.0-alpha. I then went ahead to "Updates" and saw I changed the setting mentioned at the beginning. When I switched that option back to "Enable stable updates only". Suddenly I got a lot of updates (update log below), including seemingly important ones like kernel, Xen, or qubes utils. My qubes version is also now listed as R4.2.0.  

### Steps to reproduce (speculation)
I don't know whether this is reproducable with an up-to-date system, or if this was just because of some error in my installation RC. If it still would be an issue, I guess you could:
- Set Qubes Global Config -> Updates -> Dom0 updates to "Enable security-related testing updates only"
- Wait for a stable update (which maybe didn't go through security-testing beforehand?)
- Update dom0

### Expected behavior
- dom0 updates to new package version

### Actual behavior (speculation)
- no updates

### Notes
Please tell me if there's anything useful to gather from this machine, as I assume I need to (sadly) do a clean re-install due to potentially being vulnerable for quite some time.  
[forum post](https://forum.qubes-os.org/t/qubes-4-2-updating-fails-due-to-file-conflict/24043/1)  
[update log](https://gist.github.com/pirateland/38f0a8f4948f56f6a1a3bb9f2368a06c)

**Comment by UndeadDevel** [comment]
Duplicate of #8857

**Comment by pirateland** [comment]
Thanks for pointing that out  @UndeadDevel. Closing!
