### ISSUE TITLE
Show qube life cycle buttons, e.g. "Start qube", in new app menu search results

### ISSUE THREAD

**Issue by UndeadDevel** [QubesOS/qubes-issues#8904]
### Qubes OS release
4.2

### Brief summary
The standard "Start qube" application, when selected as an application for a qube in the qube settings, still won't show up in the new application menu, but will in the old (Xfce) Application Finder.
Edit: this appears to be intentional, as the new app menu's qube list does have a "Start qube" button, just not the search results. I therefore request that section be added to the search results.
Edit2: the Qube settings app, which works via the search in the Application Finder, is also useful to have; it's present in the new App Menu in the qubes list, but not via the search.

### Steps to reproduce
1. Include the "Start qube" app in a qube's applications and optionally refresh applications for that qube (probably not necessary)
2. Try to find it in the new application menu and Application Finder

### Expected behavior
Shows up in both the new app menu and the Application Finder.

### Actual behavior
Only shows up in the Application Finder.

### Benefit of implementing
Increases productivity, especially for those using the new app menu with a keyboard primarily.

**Comment by marmarek** [comment]
When you browser the menu, the "start qube" button is at the bottom of applications list. But indeed it doesn't show up in search results, related to https://github.com/QubesOS/qubes-issues/issues/8359

**Comment by UndeadDevel** [comment]
I see, yes, but, as you point out, this section doesn't pop up in the search results, which are a far more quick and convenient way to launch qubes-related things than the qube list, at least when using the menu primarily with the keyboard.

So I gather that this behavior is intended then, at least for now. I request this be converted to an enhancement request then, or #8359 generalized to include the request to always display that section for qubes in the search results (probably best to leave them separate, though, IMHO).

**Comment by UndeadDevel** [comment]
The "start qube" entry also can't be added to favorites it seems (`qubes-desktop-linux-menu-1.2.0-1.fc37.noarch`)...

What about the following idea: introduce keywords to search, e.g. if the first search word character is `!` then what follows (until a `Space`) is a keyword and will be ignored as a search term, but can be used to modify the search results. Once that's implemented, one could add certain keywords, e.g.:

`!start` --- will search only the qubes list, not the applications; starts the qube whose name follows when `Enter` is pressed while a valid qube is selected (the "valid qube" could be a generically generated entry representing the start qube action); e.g. putting `!start per` or `!sta per` would lead to an autogenerated list entry "Start personal qube" popping up and being selected (assuming no other qube names start with "per") and pressing `Enter` would execute that, i.e. start up the personal qube.
`!pause` --- same as `!start` only with pausing that qube
`!shutdown` --- same as `!start` only with shutting down that qube
`!restart` --- same as `!start` only with restarting that qube
`!settings` --- same as `!start` only with opening the settings of that qube

etc...

**Comment by marmarta** [comment]
> The "start qube" entry also can't be added to favorites it seems (`qubes-desktop-linux-menu-1.2.0-1.fc37.noarch`)...
> 
> What about the following idea: introduce keywords to search, e.g. if the first search word character is `!` then what follows (until a `Space`) is a keyword and will be ignored as a search term, but can be used to modify the search results. Once that's implemented, one could add certain keywords, e.g.:
> 
> `!start` --- will search only the qubes list, not the applications; starts the qube whose name follows when `Enter` is pressed while a valid qube is selected (the "valid qube" could be a generically generated entry representing the start qube action); e.g. putting `!start per` or `!sta per` would lead to an autogenerated list entry "Start personal qube" popping up and being selected (assuming no other qube names start with "per") and pressing `Enter` would execute that, i.e. start up the personal qube. `!pause` --- same as `!start` only with pausing that qube `!shutdown` --- same as `!start` only with shutting down that qube `!restart` --- same as `!start` only with restarting that qube `!settings` --- same as `!start` only with opening the settings of that qube
> 
> etc...

I generally like it, but it's not exactly a simple thing to do and, much more complicatedly, to communicate to users. So I think I'd push it down the priority list, while adding start/stop shortcuts to search is somewhat easier.
