### ISSUE TITLE
(4.1) Whonix 17 templates don't have a whonix apt update channel configured by default

### ISSUE THREAD

**Issue by rocodes** [QubesOS/qubes-issues#8906]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
4.1

### Brief summary
`/etc/apt/sources.list.d/derivative.list` is not present by default in either the (4.1) workstation-17 or gateway-17 template in the community-testing repo. 

### Steps to reproduce
`qvm-template install --enablerepo=qubes-templates-community-testing whonix-17-gateway whonix-17-workstation`, then inspect `/etc/apt/sources.list.d/`  on both templates

### Expected behavior
I would expect `derivative.list` to be present and configured to receive whonix apt updates from stable channel by default. (If this is intentional, perhaps this can be explicitly documented?)

### Actual behavior
`derivative.list` absent (configurable via `repository-dist --enable`)

### Comments
Sorry, this may be more a Whonix question than a Qubes question (cc @adrelanos)

**Comment by marmarek** [comment]
Comparing build logs, I see:
- R4.1: `DERIVATIVE_APT_REPOSITORY_OPTS=''`
- R4.2: `DERIVATIVE_APT_REPOSITORY_OPTS='stable'`

looking where is that set

**Comment by marmarek** [comment]
I think it was set in `builder.conf` in qubes-template-whonix repo, removed at https://github.com/Whonix/qubes-template-whonix/commit/405057aa75d85034266e244763ce14c9dbcc94b0
`DERIVATIVE_APT_REPOSITORY_OPTS` looks to be the only (relevant) option missing in https://github.com/QubesOS/qubes-template-configs/blob/master/R4.1/templates-community/whonix-17.conf, so I'll simply add it there.

**Comment by rocodes** [comment]
Thank you @marmarek, lightning speed :)
