### ISSUE TITLE
cpufreq=dom0-kernel not working

### ISSUE THREAD

**Issue by alibrs8531** [QubesOS/qubes-issues#8907]
### Qubes OS release
4.1.2
4.2
4.0.3

### Brief summary
intel-pstate is off with cpufreq=dom0-kernel boot option. cat /sys/devices/system/cpu/intel_pstate/status shows it is off and I can't turn it on. cpupower also finds no cpufreq driver to use. I have tried this with older Qubes releases too like 4.0.3 version.

### Steps to reproduce
add cpufreq=dom0-kernel boot option and trying to change  /sys/devices/system/cpu/intel_pstate/status from off to active or on but getting error

### Expected behavior
Being able to turn on intel-pstate with cpufreq=dom0-kernel or using cpufreq drivers with cpupower

### Actual behavior
With cpufreq=dom0-kernel after changing /sys/devices/system/cpu/intel_pstate/status to active or on i get this error writing:  /sys/devices/system/cpu/intel_pstate/status no such device.

**Comment by DemiMarie** [comment]
`cpufreq=dom0-kernel` is deprecated in Xen and known to be broken IIUC.

**Comment by marmarek** [comment]
Yes, and besides that, it isn't configuration we use nor support in Qubes OS.

**Comment by alibrs8531** [comment]
> Yes, and besides that, it isn't configuration we use nor support in Qubes OS.

What do you mean by it isn't a configuration we use?

**Comment by marmarek** [comment]
> What do you mean by it isn't a configuration we use?

None of the qubes tools add `cpufreq=dom0-kernel` option, nor is it recommended in qubes documentation.

**Comment by alibrs8531** [comment]
> `cpufreq=dom0-kernel` is deprecated in Xen and known to be broken IIUC.

Why was it deprecated?

**Comment by DemiMarie** [comment]
> > `cpufreq=dom0-kernel` is deprecated in Xen and known to be broken IIUC.
> 
> Why was it deprecated?

Only Xen has knowledge of overall system load.

**Comment by alibrs8531** [comment]
> > > `cpufreq=dom0-kernel` is deprecated in Xen and known to be broken IIUC.
> > 
> > 
> > Why was it deprecated?
> 
> Only Xen has knowledge of overall system load.
Can't it pass that info to dom0 or are there limitations?

**Comment by marmarek** [comment]
It isn't static info, it's info about system state in a particular moment and it changes in time. Yes, theoretically it could various different things, but it would be rather inefficient (and so - it doesn't). Anyway, that's offtopic on qubes issue tracker, it's more of a question to Xen developers.
