### ISSUE TITLE
Consider providing repomd.xml hash over https

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#891]
**Reported by marmarek on 4 Sep 2014 20:30 UTC**
https://groups.google.com/d/topic/qubes-devel/39k347Du_D4/discussion

This will make MITM attack at least harder. Currently (unsigned metadata downloaded over plain http) makes MITM attack trivial and user will not even get any error message when someone subvert the connection. Making it HTTPS at least will give some error message when someone will try to keep you away from updates.

Migrated-From: https://wiki.qubes-os.org/ticket/891

**Comment by marmarek** [comment]
Alternatively we can use signed metadata (same as Debian uses by default). This will also help with implementing updates-freeze attack detection. Details here:
https://groups.google.com/d/msgid/qubes-devel/5520B680.5030701%40whonix.org

**Comment by axon-qubes** [comment]
Just doing a routine check: Is it still correct that @rootkovska is assigned to this issue?

**Comment by marmarek** [comment]
No.

**Comment by andrewdavidwong** [comment]
@marmarek: Is there any special reason that `yum.qubes-os.org` and `deb.qubes-os.org` use HTTP instead of HTTPS in repo definitions by default? Should we switch them all to HTTPS?

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.

**Comment by indolering** [comment]
So it looks like this got bogged down in trying to setup a SS certificate and hard code the public key into some script.  It's just repo meta-data, hacking a cert authority and performing a MITM attack [probably requires more skill](https://en.wikipedia.org/wiki/Comodo_Group#Certificate_hacking) than waiting for an un-patched flaw to drop.
