### ISSUE TITLE
Kernel updates broken if booting from USB drive with sys-usb?

### ISSUE THREAD

**Issue by no-usernames-left** [QubesOS/qubes-issues#8911]
### Qubes OS release
R4.2.0

### Brief summary
I’m using Qubes on a very beefy machine but which unfortunately cannot boot from NVMe due to the lack of a NVMe EFI driver. (Yes, I know this can often be [hacked into place and reflashed](https://winraid.level1techs.com/t/howto-get-full-nvme-support-for-all-systems-with-an-ami-uefi-bios/30901), but I’d really rather not go there.) The machine has a small USB flash drive inserted (which will never be removed when the machine is running) and an NVMe drive in a PCIe slot.

I installed R4.2.0 (non-RC) with custom (non-Blivet) partitioning, placing `/boot` and `/boot/efi` on two separate partitions on the USB drive, and the LUKS volume with LVM etc on the NVMe.

Installation went perfectly, and the box came up as expected upon rebooting at the end of installation. (As an aside, Debian, Fedora, and Whonix templates were all selected, and I set the default to `debian-12`; the second-boot template installation step was resulting in a Python exception because it ran out of space. This is probably a separate bug; I worked around it by making the root LV 40 GB instead of the default of 20 GB.)

I then enabled `sys-usb` via `sudo qubesctl state.sls qvm.usb-keyboard` and rebooted.

If it makes a difference, I installed with `kernel-latest`; `sys-net`, `sys-firewall`, and `sys-usb` are all disposable and running on a clone of `debian-12-minimal` with [the requisite packages](https://www.qubes-os.org/doc/templates/minimal/#debian) installed.

I notice now that the boot drive, being USB, is attached to `sys-usb` and thus `dom0` cannot see it… and thus likely can’t update it either. This will prevent kernel (and grub) updates from being applied, no?

### Steps to reproduce
1. Install Qubes with `/boot` and `/boot/efi` on a USB flash drive, and the rest of the system on a non-USB device
2. `sys-usb` via `sudo qubesctl state.sls qvm.usb-keyboard`

### Expected behavior
`dom0` can install kernel updates etc

### Actual behavior
I don't think it can (sadness)

**Comment by marmarek** [comment]
> I notice now that the boot drive, being USB, is attached to `sys-usb` and thus `dom0` cannot see it… and thus likely can’t update it either. This will prevent kernel (and grub) updates from being applied, no?

Yes, and also sys-usb will be able to mess with your boot files. Neither is great. Maybe you have some alternative, for example non-USB SD card reader that you can boot from (some laptops can do that)? or a small SATA disk you can boot from instead of the USB?

**Comment by marmarek** [comment]
> Interestingly enough, this same configuration worked perfectly on R4.1; is it possible to get it working on R4.2?

Depends how you define "worked". If you used sys-usb, then no, updating /boot or /boot/efi on that USB did not work.

> `sys-usb` has no network connection and is disposable, so I consider the residual risk acceptable for my usecase.

Well, that boot USB stick is not disposable. and as you said always connected. If something (other usb stick plugged in?) compromises sys-usb, it can persist on your usb stick now...

Anyway, if you are not concerned about something on USB compromising your boot files, I guess you can simply copy /boot into that USB after each update. I don't see any configuration to make it automatically, but maybe you can add some startup script to do that at each boot or such?

**Comment by marmarek** [comment]
> If I physically add another USB controller at this point for the sole purpose of the boot drive, it would be directly connected to `dom0`, no? There's no magic to scrape new USB controllers and attach them to `sys-usb` after `qvm.usb-keyboard` is invoked, correct?

Yes, that should work.
