### ISSUE TITLE
Enable Wi-Fi 7 Functionality

### ISSUE THREAD

**Issue by SiGraphics** [QubesOS/qubes-issues#8913]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release (if applicable)

4.2.0 latest kernel (6.6+)

### Brief summary

Wi-Fi 7 wireless cards are available, e.g., Intel BE200 & Qualcomm QCNCM865, and have been supported since the Linux 6.5+ kernel, but the drivers to make them functional in Qubes OS have not been placed into the sys-net > /lib/firmware directory.

**Comment by marmarek** [comment]
That's up to the distribution (template) you use for your sys-net. For recent devices you may want Fedora as Debian usually has older versions.
