### ISSUE TITLE
Debian testing template

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#8916]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### The problem you're addressing (if any)

It takes some time between a new Debian version coming out and the corresponding template being released.

### The solution you'd like

Have a Debian testing template that is always tested, so that when testing becomes stable, Qubes OS is ready.

### The value to a user, and who that user might be

Debian users will benefit from quicker updates when a new template comes out.

**Comment by marmarek** [comment]
I'm not sure about building actual template, as changes in development version may quickly make it obsolete (and I'd rather not rebuild template weekly or so). But packages for Debian testing are already in the current-testing repository.

**Comment by DemiMarie** [comment]
> I'm not sure about building actual template, as changes in development version may quickly make it obsolete (and I'd rather not rebuild template weekly or so).

Is this because building a template is expensive?  The main goal is to get test coverage on the next stable _before_ is actually stable.  Also, your comment is equally applicable to Arch or Gentoo 🙂.

**Comment by marmarek** [comment]
> The main goal is to get test coverage on the next stable _before_ is actually stable.

For that, we start preparing template before the release, but after feature freeze. That's exactly the time for fixing bugs, and we can help that by (at least) providing bug reports.
