### ISSUE TITLE
Fedora Rawhide template

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#8917]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### The problem you're addressing (if any)

It can take some time after a new Fedora release for a Fedora template to come out.

### The solution you'd like

Have a Rawhide template that is used for testing, so that Qubes OS is ready before the next Fedora is released.

### The value to a user, and who that user might be

Faster support for new Fedora releases.

**Comment by marmarek** [comment]
Similar comment as in #8916 - I don't like the idea of pre-built template, but I guess packages for rawhide would be okay.

**Comment by DemiMarie** [comment]
Does preparation start when feature freeze happens?  If so, I think this is also <https://github.com/QubesOS/qubes-issues/issues/labels/R%3A%20declined>.

**Comment by marmarek** [comment]
Yes. In fact, for Fedora 40 the time is about right now (F40 mass rebuild is already in progress) and so I did added building f40 packages already.
