### ISSUE TITLE
Continuously test Linux git HEAD

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#8919]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release (if applicable)

R4.2

### Brief summary

Continuously list Linus’s tree, so that frequent kernel updates are easy and regressions are caught before upstream releases a new version.

**Comment by marmarek** [comment]
This may be acceptable only if fully automatic. I'm afraid it isn't realistic - we don't have much Linux patches, but even the few we have sometimes need to be rebased. If that happens more than once during release cycle of given Linux version, it's wasted time.
Another consideration is dealing with not necessarily qubes-specific issues - any failure needs to be analyzed, bugs that affects broad spectrum of configuration likely will be detected by others too, which means our time looking at the results (even just to decide whether that's an actual issue or some false-positive) is wasted. From my experience from bisecting Linux, various crashes between releases happen quite often.
And also, I'm not sure what test frequency you have in mind, but I'm against burning too much power just for the sake of testing something that isn't going to be shipped to users anyway.

I have agreed to more consistent testing -rc kernels (which is exactly their purpose), not frequent testing development branches (those may be still okay for targeted cases - for example to test some specific upcoming feature before it lands in released kernel).

**Comment by DemiMarie** [comment]
> I have agreed to more consistent testing -rc kernels (which is exactly their purpose), not frequent testing development branches (those may be still okay for targeted cases - for example to test some specific upcoming feature before it lands in released kernel).

Sorry, that was a misunderstanding.
