### ISSUE TITLE
qvm-connect-tcp fails if qube doesn't have qubes-core-agent-passwordless-root

### ISSUE THREAD

**Issue by ben-grande** [QubesOS/qubes-issues#8923]
### Qubes OS release

R4.2

### Brief summary

Using `qvm-connect-tcp` to bind a port above `1023` doesn't require root, but the script calls `sudo socat` anyway.

https://github.com/QubesOS/qubes-core-agent-linux/blob/afaf948a6fba5d2c87378525a67cd163b479bb87/network/qvm-connect-tcp#L35

### Steps to reproduce

Uninstall `qubes-core-agent-passwordless-root` in the template.

Running this command:
```sh
qvm-connect-tcp ::8000
```

Is equivalent to this command:
```sh
socat \
  TCP-LISTEN:8000,reuseaddr,fork \
  EXEC:"qrexec-client-vm '' qubes.ConnectTCP+8000" &
```

### Expected behavior

Do not fail to bind in case port is above `1023`.

### Actual behavior

Fails to bind independently of port number because user doesn't have root access.

----------

Fix:
```sh
sudo=""
if test "$LOCALPORT" -le 1023; then
  sudo="sudo"
fi
$sudo socat TCP-LISTEN:"$LOCALPORT",reuseaddr,fork EXEC:"qrexec-client-vm \'$DOMAIN\' qubes.ConnectTCP+$PORT" &
```

**Comment by DemiMarie** [comment]
Simpler solution (for R4.2 at least) is to specify `user='root'` in the in-VM service configuration.

**Comment by marmarek** [comment]
> Simpler solution (for R4.2 at least) is to specify `user='root'` in the in-VM service configuration.

Nope, the issue is at the "local" site, not remote.

**Comment by DemiMarie** [comment]
> > Simpler solution (for R4.2 at least) is to specify `user='root'` in the in-VM service configuration.
> 
> Nope, the issue is at the "local" site, not remote.

Whoops, sorry!
