### ISSUE TITLE
Restore from a backup should not use dom0 disk io

### ISSUE THREAD

**Issue by logoerthiner1** [QubesOS/qubes-issues#8924]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### The problem you're addressing (if any)

Backup restore utility in R4.0~R4.2 is using dom0 disk io as is discussed here

https://forum.qubes-os.org/t/probably-implementation-oversight-in-backup-restorer-for-years-inefficient-restore/24137

### The solution you'd like

Store the temporary file in tmpfs

### The value to a user, and who that user might be

All user of backup restore who suffer from slow disk io will probably get a 3x faster restore

**Comment by DemiMarie** [comment]
To elaborate on the SSD recommendation: Achieving good performance on spinning hard drives is only possible if the I/O is strictly sequential, or very close to it.  Virtualized environments, however, do not produce sequential I/O, so performance is usually bad.

HDDs should be reserved for backup and archival workloads, which _do_ have strictly sequential I/O.  This is where the phrase “Disk is the new tape” comes from.
