### ISSUE TITLE
`qvm-copy .` fails with confusing message

### ISSUE THREAD

**Issue by logoerthiner1** [QubesOS/qubes-issues#8927]
`qvm-copy .` fails with confusing message

[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

R4.2

### Brief summary

https://forum.qubes-os.org/t/my-first-days-with-qubes-r4-2-rc1-install/19674
issue 22

```
[user@disp9154 a]$ qvm-copy .
qfile-agent: Fatal error: File copy: "Invalid or incomplete multibyte or wide character; Last file: ." (error type: Invalid or incomplete multibyte or wide character)
```

### Steps to reproduce

1. run `qvm-copy .` in vm in any dir

### Expected behavior

copy happens

### Actual behavior

copy gives this confusing error

**Comment by marmarek** [comment]
@DemiMarie looks like the qfile-agent sends file names not accepted by qfile-unpacker in this case. Maybe the initial "." (or final?) entry should not be sent in this case?

**Comment by DemiMarie** [comment]
@marmarek Doing that is easy, but is it really _useful_?  In most cases I suspect the user actually wanted to do something like `(cd .. && qvm-copy "$NAME_OF_DIRECTORY")` instead.  `qvm-copy .` is strictly equivalent to `(shopt -s nullglob && qvm-copy -- * .[!.]* ..?*)`, which I suspect is not what the user actually intended.  It also has no equivalent in any GUI tools.

I think two more useful options would be:

1. Fail with a useful error message:

   ```
   $ qvm-copy .
   Refusing to copy '.' or '..'.  If you meant to copy "$PWD", run qvm-copy "$DIRECTORY" from the parent directory.
   ```

   GNU `rm` does something similar:

   ```
   $ rm . -rf
   Refusing to copy '.' or '..' directory: skipping '.'
   ```

2. Get the current directory, `chdir()` to its parent, and then copy the directory we just left.

@logoerthiner1 @marmarta do you have any opinions here?

**Comment by jamke** [comment]
> 1. GNU `rm` does something similar:

Well, but `cp` do allow to copy `.`. Whilst `rm` removes directory, so it is obviously not a good idea to do that with the CURRENT directory. But copying should be fine.

On the other hand, `mv` does not work for `.`, so I think that the idea of @DemiMarie about refusing to work with `.` is fine, too.
