### ISSUE TITLE
`qvm-prefs -D SOMEVM template` fails with confusing error

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#8928]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

R4.2

### Brief summary

`qvm-prefs -D SOMEVM template` fails with the confusing error message `Cannot unset template`.  This does not make sense because a default template is set, meaning that I am asking Qubes OS to set the template to whatever the default TemplateVM is.  For `qvm-refs SOMEVM template ''` the error message would be correct.

### Steps to reproduce

See above.

### Expected behavior

Operation should succeed, or the error should explain why the operation is not allowed.

### Actual behavior

Confusing error message.

**Comment by marmarek** [comment]
Template property is not allowed to have "default" value (as in - "D" flag in qvm-prefs, meaning _automatically_ following whatever the default is). Theoretically, `qvm-prefs -D SOMEVM template` could set the template to whatever is the default value _right now_. That would be convenient for the user, I think, but on the other hand, it would be inconsistent (as it won't follow future changes to the default template property).
I'm not sure whether it's better to improve the error message, or implement the alternative behavior from above... @marmarta any opinion?

**Comment by marmarta** [comment]
I'd improve the error message, otherwise it does get inconsistent. (and, if possible, I would put in the error message something like "You cannot set the template value to `default`. Did you mean to set the template to `fedora-foo`, which is the default template? y/N"?

**Comment by alimirjamali** [comment]
I submitted a PR to propose a change to error message which hopefully could be a good compromise.

Review priority: Low
