### ISSUE TITLE
Invalid signature error when updating Arch Linux template

### ISSUE THREAD

**Issue by SaswatPadhi** [QubesOS/qubes-issues#8932]
### Qubes OS release

R4.2

### Brief summary

```console
[root@arch ~]# pacman -Syu
error: qubes-r4.2-current: signature from "Qubes OS 4.2 Archlinux Packages Signing Key" is invalid
:: Synchronizing package databases...
 qubes-r4.2-current downloading...
 core downloading...
 extra downloading...
 multilib downloading...
error: qubes-r4.2-current: signature from "Qubes OS 4.2 Archlinux Packages Signing Key" is invalid
error: failed to synchronize all databases (unexpected error)
```

### Expected behavior

Template updates successfully.

**Comment by DemiMarie** [comment]
Do you need to run `pacman-key --init && pacman-key --populate`?  The template that you install doesn’t have a Pacman root key, as anyone with that key can forge packages Pacman will trust.

**Comment by SaswatPadhi** [comment]
Yup, reran those again today, but no change.

I have been using the template for about a month now, but this particular issue just appeared today.

The only other issue that I used to see, which is probably unrelated, is already reported in #8875.

**Comment by SaswatPadhi** [comment]
Here's what I have found out so far:

Arch wiki has a section on this particular error: https://wiki.archlinux.org/title/Pacman/Package_signing#Invalid_signature_errors.
- Double checked that the system time in the TemplateVM was correct.
- Cleared the entire cache
- Removed /etc/pacman.d/gnupg and ran the `pacman-key` commands that @DemiMarie and the wiki suggest. I see the following error in the output:

```
==> Appending keys from qubesos-vm.gpg...
gpg: error reading key: No public key
```

But anyway, resetting keys does not fix the issue.

---

The workaround suggested in https://forum.manjaro.org/t/root-tip-how-to-mitigate-and-prevent-gpgme-error-when-syncing-your-system/84700 works for me -- in /etc/pacman.conf, change

```
SigLevel    = Required DatabaseOptional
```

to

```
SigLevel    = Required DatabaseNever
```

**Comment by DemiMarie** [comment]
> ==> Appending keys from qubesos-vm.gpg...
> gpg: error reading key: No public key

This seems like the actual cause of the problem.

**Comment by SaswatPadhi** [comment]
Any idea how we could fix this? I tried `pacman-key --import` on https://github.com/QubesOS/qubes-meta-packages/blob/main/repos/qubes-repo-archlinux-key.asc but it didn't fix anything.

**Comment by DemiMarie** [comment]
@SaswatPadhi What is in `qubesos-vm.gpg`?

**Comment by SaswatPadhi** [comment]
This file: https://github.com/QubesOS/qubes-meta-packages/blob/e21794f2b04e8c340fc1b2f38a707cbede46e007/repos/qubes-repo-archlinux-key.asc

Installed by https://github.com/QubesOS/qubes-meta-packages/blob/e21794f2b04e8c340fc1b2f38a707cbede46e007/archlinux/PKGBUILD.in#L33

**Comment by DemiMarie** [comment]
@SaswatPadhi Try replacing it with the binary version (`gpg2 --dearmor` will give it to you).

**Comment by SaswatPadhi** [comment]
No change, unfortunately. The same error persists.
I moved the text file and checked that `gpg2 --dearmor` indeed generated a binary there.

**Comment by marmarek** [comment]
FWIW I fetched https://archlinux.qubes-os.org/r4.2/current/vm/archlinux/pkgs/qubes-r4.2-current.db (together with .sig) manually  and checked the signature, looks good...

**Comment by SaswatPadhi** [comment]
Thanks for looking into this @marmarek.

I tried the following:
```console
[root@arch sync]# timedatectl status
               Local time: Mon 2024-02-19 02:07:46 UTC
           Universal time: Mon 2024-02-19 02:07:46 UTC
                 RTC time: Mon 2024-02-19 02:07:46
                Time zone: UTC (UTC, +0000)
System clock synchronized: no
              NTP service: inactive
          RTC in local TZ: no

[root@arch sync]# file qubes-r4.2-current.db.sig 
qubes-r4.2-current.db.sig: PGP signature Signature (old)

[root@arch sync]# cat qubes-r4.2-current.db.sig 
-----BEGIN PGP SIGNATURE-----

iHUEABYKAB0WIQTlABwdSb6RKd7sBihMYnAUbEY9kAUCZVLxDwAKCRBMYnAUbEY9
kCCNAQCHcy1Xd0Nhw+DTkW3p6AOAV4Csdt8MssEz40P5BZNlxQD+JcVfbeqd31zo
NdRRpst/yDLT4V0f0dmnQRqKueCUQwI=
=+kj+
-----END PGP SIGNATURE-----

[root@arch sync]# gpg --homedir /etc/pacman.d/gnupg --verify qubes-r4.2-current.db.sig
gpg: WARNING: unsafe permissions on homedir '/etc/pacman.d/gnupg'
gpg: assuming signed data in 'qubes-r4.2-current.db'
gpg: Signature made Tue 14 Nov 2023 04:01:19 AM UTC
gpg:                using EDDSA key E5001C1D49BE9129DEEC06284C6270146C463D90
gpg: BAD signature from "Qubes OS 4.2 Archlinux Packages Signing Key" [full]
```

Am I doing something wrong here? Why do I get a `BAD signature`?

**Comment by marmarek** [comment]
Interesting, that's not how `qubes-r4.2-current.db.sig` file looks on https://archlinux.qubes-os.org/r4.2/current/vm/archlinux/pkgs/ right now. 

> ```
> gpg: Signature made Tue 14 Nov 2023 04:01:19 AM UTC
> ```

Looks rather old (but also, should be valid back then too, given matching `qubes-r4.2-current.db`).

**Comment by SaswatPadhi** [comment]
Wow, apparently I just had to delete the old `sync` files!

I ran `rm -rf /var/lib/pacman/sync` and then `pacman -Syyu` ran without any signature errors.
I still get the pulseaudio error from #8875, but the signature error is gone!

`pacman-key --populate` still gives me:
```
==> Appending keys from qubesos-vm.gpg...
gpg: error reading key: No public key
```
but system updates are no longer blocked.

**Comment by SaswatPadhi** [comment]
This fix seems to work on all of my arch TemplateVMs.
But, I'm not sure if there's a better (safer) way via `pacman` to remove the `sync` directory -- even `pacman -Scc` doesn't do it.

Thank you @marmarek and @DemiMarie.
Please feel free to close this as a `not our bug` since it doesn't look specific to Qubes OS.
