### ISSUE TITLE
transactional dom0 updates

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#8933]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### The problem you're addressing (if any)

Incomplete dom0 updates can leave the system unbootable, especially if they happen during a major version upgrade.

### The solution you'd like

dom0 updates should be transactional, as is implemented using the `transactional-update` tool on openSUSE.

### The value to a user, and who that user might be

All users will benefit from more reliable updates.

**Comment by marmarek** [comment]
> Incomplete dom0 updates can leave the system unbootable, especially if they happen during a major version upgrade.

The qubes-dist-upgrade tool already makes dom0 snapshot before updating. I don't think it's worth spending time improving it further (complex work, to solve very rare issue). At some point, when dom0 will be smaller, we may ship it as an image and do A/B updates.
