### ISSUE TITLE
Release Qubes OS 4.2.1

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#8935]
Qubes 4.1 is scheduled to reach EOL on 2024-06-18. I think we should aim to release Qubes 4.2.1 approximately three months before that on 2024-03-18. This way, we can announce Qubes 4.2.1 at the same time as the "approaching EOL" notice for 4.1. It will soften the blow and be a good "last chance" for all users still on 4.1 to upgrade with a recent ISO and plenty of time to spare.

- [x] Update references to included templates (installer, Salt, etc.)
- [x] Build new ISO
- [x] Test new ISO
- [x] Upload ISO to mirrors
- [x] Announce

**Comment by Trat8547** [comment]
Hi. I'm new to Qubes development, but I'm willing to help in what is needed to get ready for 4.2.1's release. Haven't been able to use QubesOS due to a kernel bug for the past few months now that should be patched in 4.2.1.

**Comment by marmarek** [comment]
@andrewdavidwong I'm building 4.2.1-rc1 now. Where do we announce it? Just the forum?
Since it's basically R4.2.0 + updates, we don't have much testing. I'd go with final 4.2.1 release on 25th or so (slightly more than a week for testing), of course if no blocking issue is found.
