### ISSUE TITLE
Make it easier to use Bluetooth audio devices

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#8944]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

R4.2

### Brief summary

Using Bluetooth audio devices is too difficult.  There are too many ways to try doing it, and not all of the ones that work are reasonably secure.

### Steps to reproduce

Try to use Bluetooth headphones with Qubes OS.

### Expected behavior

There is a single recommended way to do it, and doing it that way is easy.  Ideally, it should not even require opening a command-line window.

### Actual behavior

It’s hard and there are lots of ways to go wrong.

**Comment by DemiMarie** [comment]
For the record: if I had to do this, I would:

1. Create a sys-bluetooth qube.  This must _not_ be a disposable VM as it needs to store Bluetooth pairing state.
2. Attach the Bluetooth controller to sys-bluetooth.
3. Use sys-bluetooth as AudioVM.

This is still pretty bad.  Switching from Bluetooth to internal audio and back is still way too hard, for example.

**Comment by jamke** [comment]
Totally related:

Proper guide on how to use sys-audio (AudioVM) must be created - Community Guides - Qubes OS Forum
https://forum.qubes-os.org/t/proper-guide-on-how-to-use-sys-audio-audiovm-must-be-created/16851

Audio qube - Community Guides - Qubes OS Forum
https://forum.qubes-os.org/t/audio-qube/20685

**Comment by jamke** [comment]
The whole hard thing is `sys-audio`. Switching is also related to to switching audio qube.

I love the concept of audio qube. Nontheless, it still requires further work for being a reliable solution and allowing on-fly switching. Like changing net qube, nothing should break after its changes.
