### ISSUE TITLE
Consider implementing persistent VM custom config setting

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#895]
**Reported by marmarek on 4 Sep 2014 22:15 UTC**
Currently the only (easy) way to use custom Xen config is to provide --custom-config option to qvm-start '''every time'''. Alternatively one can edit qubes.xml, which isn't easy at all.

Perhaps the better idea is to provide some persistent way to set config file, or simply use `custom.conf` in VM directory if exists. But it will require clear UI indication that most of VM settings will be ignored in that case (memory size, kernel, netvm etc).

Migrated-From: https://wiki.qubes-os.org/ticket/895

**Comment by axon-qubes** [comment]
Just doing a routine check: Is it still correct that @rootkovska is assigned to this issue?

**Comment by marmarek** [comment]
No. That must be some bug in ticket migration script.

**Comment by woju** [comment]
fixed as side effect of #1798
