### ISSUE TITLE
Multi-user support

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#8958]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### The problem you're addressing (if any)

Qubes OS only supports a single user.  This is fine for most cases but not for others.

### The solution you'd like

Support multiple user accounts.  By default, the first account created will be an administrator account and have full access, while others will only have limited access.

Obviously, this depends on (at least):

- [ ] #8957

### The value to a user, and who that user might be

This is valuable for the same reasons that multi-user support in general is valuable.

**Comment by DemiMarie** [comment]
Not particularly.  It’s more that Qubes OS is closer to being able to support this feature.  There are still lots of prerequisite features needed first.  And no, you don’t seem to be targeting me specifically.

**Comment by marmarek** [comment]
This is not something we plan (or at least in this shape) anytime soon.
