### ISSUE TITLE
Guest account

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#8959]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### The problem you're addressing (if any)

Someone wants to be able to demonstrate Qubes OS to someone without worrying about any persistant state being stored after that someone logs out.  Or someone decides to use Qubes OS for a computer at a public library.

### The solution you'd like

A guest account with very limited privileges and no ability to persist data.

Depends on at least:

- [x] #8958 
- [ ] #8957 

### The value to a user, and who that user might be

See above.

**Comment by jamke** [comment]
Maybe LiveUSB is better for this purpose.

Guest accounts is a bad thing for security and privacy, even in GNU/Linux, it should be disabled the first thing on any OS.

**Comment by DemiMarie** [comment]
@jamke This is explicitly for demo purposes and would be disabled by default.

**Comment by marmarek** [comment]
This is not something we plan (or at least in this shape) anytime soon.
