### ISSUE TITLE
Consider disabling fedora update repo in Dom0 by default

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#898]
**Reported by joanna on 8 Sep 2014 08:36 UTC**
Normally there is no reason to keep Dom0 software up to date, security-wise. Just setting enabled=0 in the repo file might be cleaner.

Migrated-From: https://wiki.qubes-os.org/ticket/898

**Comment by esote** [comment]
@marmarek @andrewdavidwong I tend to agree it should not be disabled by default. Maybe this makes sense once the version is EOL (like Fedora 25 is currently) -- but for 4.1 with Fedora 29 (#4225) depending on when it's released we may still be getting regular Fedora updates with bug fixes. If we disable updates in that case, it would put the onus on us to not only maintain the Qubes repo but also watch for potentially-critical updates from Fedora.

**Comment by andrewdavidwong** [comment]
> Even once dom0 is separated from the GUI, there still may be critical non-GUI updates (ie cryptsetup, etc.).

Agreed. Closing as "won't do." If anyone has a new reason for why this should be done, please leave a comment, and we'll be happy to take another look. Thank you.
