### ISSUE TITLE
"default-kernel" global property doesn't validate if the kernel exists

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#8992]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

R4.2 (likely R4.1 too)

### Brief summary

Setting `default-kernel` to invalid value prevents starting any qube. qubesd should refuse to set invalid value.

### Steps to reproduce

`qubes-prefs default-kernel xxx`

### Expected behavior

`xxx` value is refused

### Actual behavior

Value is accepted and no qube can start due to non-existing kernel.

**Comment by alimirjamali** [comment]
It appears that the readily available `property-pre-set:kernel` event and `on_property_pre_set_kernel` of [QubesVM](https://github.com/QubesOS/qubes-core-admin/blob/main/qubes/vm/qubesvm.py#L1040-L1060)  could not be reused here.

Doing it at `qubes-core-admin-client` will not be a proper fix?

**Comment by marmarek** [comment]
> Doing it at `qubes-core-admin-client` level will not be a proper fix?

No, it should be done on the backend side.

> It appears that the readily available `property-pre-set:kernel` event and `on_property_pre_set_kernel` of [QubesVM](https://github.com/QubesOS/qubes-core-admin/blob/main/qubes/vm/qubesvm.py#L1040-L1060) could not be reused here.

I think it can be extracted to a helper function, and then connected to a `property-pre-set:default_kernel` event on the app object.

**Comment by alimirjamali** [comment]
> I think it can be extracted to a helper function, and then connected to a `property-pre-set:default_kernel` event on the app object.

Ok. It is done at Daemon level.

PS Submitted

Review priority: low
