### ISSUE TITLE
Allow navigating new App Menu with keyboard right away (apart from search)

### ISSUE THREAD

**Issue by UndeadDevel** [QubesOS/qubes-issues#9006]
### The problem you're addressing (if any)
When the new App menu is opened, either via the mouse or a keyboard shortcut (see #9005), it is not keyboard navigable right away, except when using the search. In order for it to become keyboard navigable one has to either start using the search and then navigate out of it or mouse over the qubes list (and then remove the mouse due to #8789). One can also fix this with a little hack, see [my script](https://gist.github.com/UndeadDevel/8501e82a534e5daa2ac60e36945167b9).

### The solution you'd like
Pre-select the top item of the qubes list, so that the app menu is immediately keyboard navigable when not using the search.

### The value to a user, and who that user might be
Users who primarily use the keyboard will be able to make better use of the new App Menu.

**Comment by UndeadDevel** [comment]
> FWIW, I just tried it on 4.2, and keyboard navigation seems to work only sometimes. For example:
     1. Open App Menu. Move around with arrow keys successfully.
     2. Close App Menu.
     3. Open App Menu again. Arrow keys do nothing now.

Can confirm. After fully updating the system (only security-testing, not testing repo enabled, however), then trying to update the menu only with `sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing qubes-desktop-linux-menu` so it's at the latest version (which yielded 'Nothing to do', so it seems there is no newer version in the testing repo), and rebooting and then opening the App Menu via mouse click, it is keyboard navigable right away the first time, but not after closing it and again opening it...repeating this later a few times showed that most of the time the issue could be reproduced (with 1 exception, where the menu was again keyboard navigable right away).

**Comment by andrewdavidwong** [comment]
Reopening due to #10039.

**Comment by parulin** [comment]
>     1. Open App Menu. Move around with arrow keys successfully.
> 
>     2. Close App Menu.
> 
>     3. Open App Menu again. Arrow keys do nothing now.

I can't reproduce on R4.3

**Comment by ben-grande** [comment]
I can reproduce the issue that made this one be reopened (when mouse is selecting an item). Steps for reproduction: https://github.com/QubesOS/qubes-issues/issues/10039#issue-3209016515. It seems that when the mouse on top of an item, you can't move the selection with the cursor. If you move to some blank space or outside the app menu such as the status bar, it works again.

**Comment by parulin** [comment]
Okay, steps to reproduce:

1. open the app menu
2. hover on something with the mouse
3. try to use an arrow, the focus moves very quickly to the next item before coming back under the mouse.
