### ISSUE TITLE
qubes-bugreport tool

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#901]
**Reported by woju on 18 Sep 2014 15:28 UTC**
On Thu, Sep 18, 2014 at 03:08:08PM +0000, Hakisho Nukama wrote:

> Maybe we need some _separate_ qubes-generate-report tool, that is
> collecting all information useful for debugging
> problems from appvms and dom0.

https://groups.google.com/forum/#!topic/qubes-users/KUwfPI7Ma1Q

Migrated-From: https://wiki.qubes-os.org/ticket/901

**Comment by Jeeppler** [comment]
Is there any specification or description around how such a tool should look like? Should it just be a CLI (command line) tool which generates debug information in a text/xml file, which then can be send via email or how should it look like?

**Comment by marmarek** [comment]
Yes, something like this. It should collect:
 - package versions:`rpm -qa qubes-*`
 - related VMs info (for network problems - all NetVMs and ProxyVMs): `qvm-prefs VMNAME`
 - package versions installed in those VMs: `qvm-run -p VMNAME 'rpm -qa qubes-*'` (or `dpkg -l qubes-*`)
 - related logs from `/var/log/qubes`

I think it should write the file in selected VM (similar to `qubes-hcl-report` tool) for being attached to an email, or github issue. Later we may integrate it into Qubes Manager. The file should be easily readable for normal user, to check if no private data is being leaked.

**Comment by Jeeppler** [comment]
The tool syntax could be something like: `qubes-bug-report SRC-VMNAME REPORT-VMNAME --net` 
the `--net` to report network problems. SRC-VMNAME is the VM, which has issues. REPORT-VMNAME is the which the report should be send to.

**Comment by marmarek** [comment]
I'd prefer to have `--dest-vm REPORT-VMNAME` (or some other option name), because later when integrating into Qubes Manager we may want to save the reportin initially in dom0, give it to the user for review and only then send to some VM.
Other than that, it's ok

**Comment by Jeeppler** [comment]
In which language and version would you write this tool? Python 2.7+, Python 3+, Bash?

**Comment by marmarek** [comment]
Preferably python, either version (in case of 3, it would be first qubes
tool in python3, but that isn't anything bad).

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by Jeeppler** [comment]
Each qube has the following logs:

- guid.VMNAME
- pacat.VMNAME
- qubesdb.VMNAME
- qrexec.VMNAME

which one would you like to see in the bug-report? Do you want to have all information from the logs or do you want to have specific parts?

**Comment by marmarek** [comment]
All of them should be a good default. Those logs are from the most recent
VM run, so should not be that big.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by Jeeppler** [comment]
Okay, I created the script. The output format is Markdown.
In which repository shall a commit (upload) the script?

**Comment by marmarek** [comment]
I think it can go to https://github.com/qubesos/qubes-core-admin, into qvm-tools directory.

**Comment by Jeeppler** [comment]
I created a pull request. Please review the tool. The tool is written in python3. 

If you want to test it, just use `qubes-dom0-update python3` in Qubes 3.1 to install Python 3.3 in Dom0. 

If you have any concerns or if there are any issues please let me know, I will change the script.
The script should work with Fedora, Debian and Archlinux scripts.

I added a `-p` option which only prints the report to the console.
