### ISSUE TITLE
Archlinux now provide newer pulseaudio then qubes-vm-pulseaudio dependencies

### ISSUE THREAD

**Issue by Szewcson** [QubesOS/qubes-issues#9018]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
4.2

### Brief summary
Can't update arch template due qubes dependency issue

### Steps to reproduce
Execute `pacman -Syu` on qubes archlinux template

### Expected behavior
Update will succeed 

### Actual behavior
`error: failed to prepare transaction (could not satisfy dependencies)
:: unable to satisfy dependency 'pulseaudio<=16.99.1' required by qubes-vm-pulseaudio
`

**Comment by Szewcson** [comment]
Also it looks like just ignoring that pkg is not a workaround due to other changes.

**Comment by Szewcson** [comment]
Sorry. Now I found the original issue. Can close as a dup of: `https://github.com/QubesOS/qubes-issues/issues/8875`

**Comment by lubellier** [comment]
@andrewdavidwong please could you close this issue with the duplicate tag? Thanks.
