### ISSUE TITLE
New Updater does not restart non-system qubes despite UI suggesting that should happen

### ISSUE THREAD

**Issue by UndeadDevel** [QubesOS/qubes-issues#9024]
### Qubes OS release
4.2

### Brief summary
When non-system qubes are selected in the "post-update list" of the new GUI Updater for restarting, they will be shut down but not restarted. Since I'm not seeing anything in the logs and the final message states that "All qubes have been successfully restarted / shut down", I'm inclined to think that this is intended behavior. In that case this would be a UI bug; if it's not intended, i.e. those qubes are supposed to actually restart then it would be a program logic bug / other bug.

Occurs regardless of the setting to automatically restart app qubes and regardless of setting an AppVM to "provides networking".

### Steps to reproduce

1. Start updater and update templates of running AppVMs
2. Select those for restarting if not already selected
3. Observe that they are shut down, but not restarted

### Expected behavior
Either UI says that only selected system qubes will be restarted or other qubes (except unnamed DVMs) are also restarted.

### Actual behavior
UI suggests that all selected qubes would be restarted, but only selected system qubes are restarted.

![updater_restart_issue](https://github.com/QubesOS/qubes-issues/assets/30495439/73e1d883-6074-4bfb-b201-cee7d5874233)

**Comment by unman** [comment]
In your summary you refer to " AppVMs or named DVMs" - do you find that
system qubes, like sys-net restart?
I havent noticed this lack.

**Comment by UndeadDevel** [comment]
> In your summary you refer to " AppVMs or named DVMs" - do you find that
system qubes, like sys-net restart?
I havent noticed this lack.

Yes, system qubes restart as expected.

**Comment by UndeadDevel** [comment]
> Isn't sys-net a named disposable in the default installation?

Good point! I've updated the title and OP as well as included a screenshot to make the point about the UI definitely suggesting that a restart would occur. I've also tested if setting the "provides networking" flag on an AppVM changes the behavior: it doesn't.

**Comment by piotrbartman** [comment]
Such behavior is intentional, but I agree that what is communicated is different. To summarize, we have:
1. Standalones are left in the state they were in.
2. Templates are being shut down.
3. AppVMs with the name "sys-*" are being restarted.
4. The rest of the AppVMs are being shut down.
The reason for this is that there's no point in restarting AppVMs in the background without restarting the applications themselves.

My proposal is as follows: add a feature that allows marking AppVMs we want to restart (because, for example, they have autostart applications/services) and change the message on the button. Anyone feel free to suggest some ideas on how to communicate this better.

**Comment by UndeadDevel** [comment]
> My proposal is as follows: add a feature that allows marking AppVMs we want to restart (because, for example, they have autostart applications/services) and change the message on the button. Anyone feel free to suggest some ideas on how to communicate this better.

If this means changing the behavior from "checkmark means the AppVM will shut down" to "checkmark means the AppVM will restart" then I agree. With that change there wouldn't need to be any modification of the UI Strings, either.

There is little point in shutting down AppVMs without restarting them, since usually there will be stuff running that needs to be shut down properly or work that needs to be saved etc.. Ideally there would be a check, e.g. for open windows and notification that informs about it, with the program waiting until all windows are closed (for an example implementation see [my little scripts](https://gist.github.com/UndeadDevel/82e5f61c9a5065ab9fc5d23a74ae5045)). If the user has taken care of that, then the AppVM may as well be restarted; if the user hasn't, then shutting it down is not desired, either.
