### ISSUE TITLE
builderv2: implement artifacts cleanup command

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#9026]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### The problem you're addressing (if any)

The artifacts directory in builderv2 grows over time, and cleaning up may not be trivial.

### The solution you'd like

A command that removes all files that are not necessary anymore, which includes:
 - [ ] old build artifacts (`component/...` for versions older than the current one)
 - [ ] old distfiles (not referenced by the current `.qubesbuilder` file for the current version) - this is especially relevant for old kernel tarballs, as they are quite big
 - [ ] old template packages
 - [ ] old packages in `repository/`
 - [ ] old packages in `repository-publish/` (this one should be configurable, including how many old version should be kept - see `repomanage` command)
- [ ] old templates in `templates/rpm/`
- [ ] old logs (older than configurable number of days?)
- [ ] unused temporary files (`tmp/` dir)

### The value to a user, and who that user might be

Less disk space needed to use qubes-builderv2.

**Comment by marmarek** [comment]
@fepitre keeping last X version is broken, it sorts versions as strings, so when you have 1.7, 1.8, 1.9, 1.10, it will _remove_ 1.10...

**Comment by fepitre** [comment]
I switched to LooseVersion. `dnf` says it should be pulled by Python directly:
```
$ dnf repoquery --requires python3-looseversion
Last metadata expiration check: 0:01:44 ago on Mon Sep 16 17:31:38 2024.
python(abi) = 3.12
```

**Comment by marmarek** [comment]
> $ dnf repoquery --requires python3-looseversion
> Last metadata expiration check: 0:01:44 ago on Mon Sep 16 17:31:38 2024.
> python(abi) = 3.12

No, this means python3-looseversion needs python 3.12. The python3-looseversion seems to be required by salt, but not anything else installed in the vm. Futhermore, it isn't available in (standard) Debian (we add it via our repos, but requiring it would break running on non-qubes debian).

**Comment by fepitre** [comment]
> > $ dnf repoquery --requires python3-looseversion
> > Last metadata expiration check: 0:01:44 ago on Mon Sep 16 17:31:38 2024.
> > python(abi) = 3.12
> 
> No, this means python3-looseversion needs python 3.12. The python3-looseversion seems to be required by salt, but not anything else installed in the vm. Futhermore, it isn't available in (standard) Debian (we add it via our repos, but requiring it would break running on non-qubes debian).

What can be done? Add version semver parsing into our code?

**Comment by marmarek** [comment]
Looks like we already have adjusted version parsing in component.py, you can use that instead of 3rdparty library.

**Comment by fepitre** [comment]
> component

Oh yes! I completely forgot...

**Comment by fepitre** [comment]
@marmarek is there anything else remaining not implemented?
