### ISSUE TITLE
qubes-vm-update --restart reboots AppVMs even when update is unsuccessful

### ISSUE THREAD

**Issue by rocodes** [QubesOS/qubes-issues#9031]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

4.2

### Brief summary

`qubes-vm-update --restart` reboots running AppVM (and template) even if updates to the appVM's template are not successful

### Steps to reproduce

Start an AppVM, then start its template. Create circumstances that will force a template update error (eg by disconnecting the network, or configuring an invalid package repo in the template), then run `qubes-vm-update --show-output --restart` and watch the template update fail with nonzero exit code.

### Expected behavior
Running AppVM does not reboot because update on its template was not completed successfully. (Same expectation of template).

### Actual behavior
Template reboots, running AppVM reboots

**Comment by unman** [comment]
Interesting because #9024 suggests that AppVMs are shut down but not
restarted when templates are updated, when using the GUI.
There is a rash of issues recently about the new updater
