### ISSUE TITLE
Make sending service descriptor to socket qrexec service opt-out

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#9036]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### The problem you're addressing (if any)

Currently, when making a some existing service available via qrexec, one needs to make a wrapper - either make a [socket service](https://www.qubes-os.org/doc/qrexec-socket-services/) that strips the initial part (connection metadata) and then passthrough data to the actual service. Or make an executable service that connects to a socket and then passthrough the data (this is how many services are done now, using `socat`).

### The solution you'd like

- [x] Add new `skip-service-descriptor=1` option support to qrexec-agent to RPC config (`/etc/qubes/rpc-config/*`) - when set, qrexec should skip sending service descriptor and go for the actual data directly.
- [x] Do the same in qrexec-daemon
- [x] Add tests
- [ ] Update documentation. Preferably, document it in qubes-doc too (currently it's documented only in a `/etc/qubes/rpc-config/README`)

### The value to a user, and who that user might be

Ease using qrexec to connect existing services.

**Comment by ben-grande** [comment]
>  Update documentation. Preferably, document it in qubes-doc too (currently it's documented only in a /etc/qubes/rpc-config/README)

I can document this in [rpc-config/README](https://github.com/QubesOS/qubes-core-qrexec/tree/main/qubes-rpc-config), as it seems very outdated.

But just to know if I got everything right:

Format:

- Key and value must be separated by an `=` (equal sign), they may also be separated by spaces or tabs between the equal sign. e.g `key=value`, `key = value`;
- Boolean values accept `0`, `1`, `true` and `false`;
- String values must be enclosed by `'` (single quotes), e.g. `'str'`.

Keys:

- `user` (str/int) can be a literal name or UID;
- `wait-for-session` (bool);
- `skip-service-descriptor` (bool).

**Comment by ben-grande** [comment]
I am not sure if `user` was changed to `force-user`. Is this correct?

**Comment by ben-grande** [comment]
> > > Update documentation. Preferably, document it in qubes-doc too (currently it's documented only in a /etc/qubes/rpc-config/README)
> > 
> > 
> > I can document this in [rpc-config/README](https://github.com/QubesOS/qubes-core-qrexec/tree/main/qubes-rpc-config), as it seems very outdated.
> 
> It is, want to make a PR?

Yes, I want to help.
