### ISSUE TITLE
Simulataneous updates limit set in GUI does not work for the current update

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#9039]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

R4.2

### Brief summary

Setting limit how many qubes should be updated in parallel doesn't work

### Steps to reproduce

1. Open updater GUI (from the widget)
2. Click settings icon
3. Change the limit, for example from 1 to 4
4. Click "save and close"
5. Start the update

### Expected behavior

4 templates are updated in parallel (after dom0)

### Actual behavior

Only one template (old limit) is updated in parallel. When opening settings window again (still during update), old limit value is shown.

**Comment by UndeadDevel** [comment]
It works for multiple templates when no limit at all is set, though there's another aspect to this issue:

Standalones are not updated simultaneously with templates, but rather the updater first updates templates and only then starts the standalone(s) for updating.

**Comment by piotrbartman** [comment]
> It works for multiple templates when no limit at all is set, though there's another aspect to this issue:
> 
> Standalones are not updated simultaneously with templates, but rather the updater first updates templates and only then starts the standalone(s) for updating.

This is the default behavior of `qubes-vm-update`, which has the following update order:

1. AdminVM
2. TemplateVMs
3. Rest VMs
