### ISSUE TITLE
Enabling IPv6 breaks updates and whonix

### ISSUE THREAD

**Issue by viq** [QubesOS/qubes-issues#9042]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

QubesOS 4.2

### Brief summary

Enabling IPv6 in system breaks at the very least updates and whonix.

### Steps to reproduce

`qvm-prefs sys-net ip6 1`

### Expected behavior

Everything works as usual.

### Actual behavior

1. Updates break, because the tinyproxy starts seeing connections comming from `::1`. Adding
```
Allow ::1
```
fixes this issue.
2. `sys-whonix` either stops being able to connect to Tor, or all the built in tools fail to detect it's been connected. Updates don't work (I didn't yet put in the fix mentioned above), `anon-whonix` is not able to connect to anything (so it's not a case of "tools don't detect connection, but things still work").

**Comment by viq** [comment]
Ah, at least the first part is a duplicate of #9025

**Comment by chatcannon** [comment]
The second part looks like a duplicate of https://github.com/QubesOS/qubes-issues/issues/8169 which is an upstream issue with Whonix.

You can run `qvm-features sys-whonix ipv6 ''` to disable IPv6 for Whonix while leaving it enabled for your other qubes.

**Comment by viq** [comment]
Ah, indeed. Closing as duplicate of #9025 and #8169.
