### ISSUE TITLE
Latest fedora-39-minimal build is gigantic

### ISSUE THREAD

**Issue by rustybird** [QubesOS/qubes-issues#9043]
### Qubes OS release

R4.2

### Brief summary

Something has gone wrong with the latest fedora-39-minimal template build, version 4.2.0-202403091939. Compared to the previous version 4.2.0-202311171650, it's huge - larger than the xfce and gnome flavors.

From the directory listing at https://yum.qubes-os.org/r4.2/templates-itl-testing/rpm/ :

<pre>
qubes-template-fedora-39-4.2.0-202311171459.noa..> 17-Nov-2023 16:11          1505135316
qubes-template-fedora-39-4.2.0-202403091939.noa..> 10-Mar-2024 00:00          1576074532
qubes-template-fedora-39-minimal-4.2.0-20231117..> 17-Nov-2023 17:42           817275935
<b>qubes-template-fedora-39-minimal-4.2.0-20240309..> 09-Mar-2024 22:19          1984717932</b>
qubes-template-fedora-39-xfce-4.2.0-20231117132..> 17-Nov-2023 14:48          1568548279
qubes-template-fedora-39-xfce-4.2.0-20240310010..> 10-Mar-2024 02:39          1625402808
</pre>

I noticed because `qubes-run-terminal` unexpectedly popped up a `gnome-terminal` instead of an `xterm`.

**Comment by zpc0** [comment]
See my commit. Just simple mistake.
