### ISSUE TITLE
Generate DispVM savefile immediately after template update

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#905]
**Reported by joanna on 1 Oct 2014 11:38 UTC**
... instead on first time the user wants to use it.

Migrated-From: https://wiki.qubes-os.org/ticket/905

**Comment by marmarek** [comment]
As savefile generation is much faster now, it isn't such a big issue now.

**Comment by woju** [comment]
@marmarek @andrewdavidwong 
Shouldn't this be closed as wontfix since we are dropping savefiles?
