### ISSUE TITLE
Use re2c for TOML lexer

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#9051]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### The problem you're addressing (if any)

The TOML parser in qrexec uses a hand-written lexer that cannot handle all of TOML.  Extending support to all of TOML would be extremely difficult, as the lexer is written by hand and is therefore difficult to extend.

### The solution you'd like

Use a lexer generated by re2c.  re2c is already a transitive build dependency of systemd (via Meson and Ninja), so using it does not increase the risk of supply-chain attacks.

### The value to a user, and who that user might be

Users will be able to use more of TOML syntax.  Developers will have a code base that they can extend without fear.

This is https://github.com/QubesOS/qubes-issues/labels/P%3A%20minor for two reasons:

1. Configuration files are primarily shipped by Qubes OS developers, rather than by end users.
2. No changes to the parser are currently required.

**Comment by marmarek** [comment]
I don't think we need this issue until some more of TOML syntax is needed there (which currently is not the case, and rather unlikely to happen in the future).
