### ISSUE TITLE
Template repo onion mirrors are out of sync for over a week

### ISSUE THREAD

**Issue by Solomon1732** [QubesOS/qubes-issues#9053]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
R4.1

### Brief summary
Whenever I try to install Fedora 39, Fedora 39-xfce, or Fedora 39 minimal, then I get the following error: `Error canonicalizing file: failed to fill whole buffer`.

I am opening the bug report after being advised [in the Qubes Forum](https://forum.qubes-os.org/t/cant-install-fedora-39-templates-on-r4-1/25234/3).
### Steps to reproduce
1. Open the terminal in dom0.
2. Type `sudoedit /etc/qubes/repo-templates/qubes-templates.repo`.
3. Switch to the onion mirrors and comment out the clearnet ones.
4. Write `qvm-template install fedora-39` or `fedora-39-xfce` or `fedora-39-minimal`
5. It tries to download the template, fails with `Error canonicalizing file: failed to fill whole buffer`, retries a few times with the same error, and ultimately fails to download.

### Expected behavior
Download the desired Fedora templates.

### Actual behavior
It fails to download them. I updated all templates and dom0 before trying to install it. It also failed when I tried to install it before at some point in the last few weeks.

### Further details
I am writing this after I successfully moved my Whonix 16 templates to Whonix 17. I used qvm-template install for both the Fedora and the Whonix templates. I have plenty of space on my harddrive.

It fails after it retries to download it a few times. Each time it fails with this error.

As advised in the Qubes Forum link hereinabove, I tried to comment `metalink` and uncomment `baseurl` in `/etc/qubes/repo-templates/qubes-templates.repo`. It also fails when I use the onion mirrors. Note: I downloaded Whonix 17 templates through the onion mirrors. I don't know why Fedora 39 fails through these same mirror links.

Edit: It turns out only the onion mirrors for Qubes templates are out of sync. It's odd since for Whonix 17 templates it was fine. Not for Fedora 39 ones. For those it's been out of sync for over a week. Thus, I changed the issue title. I also updated the steps to reproduce hereinabove.

**Comment by unman** [comment]
I do not think that the onion repository is any more syncing templates for 4.1

**Comment by unman** [comment]
Indeed.
I believe that repos are still updated for 4.1.

**Comment by Solomon1732** [comment]
Closing since extended security support has ended for 4.1: https://www.qubes-os.org/news/2024/08/01/extended-security-support-for-qubes-os-4-1-has-ended/
