### ISSUE TITLE
Can't install CTAP/U2F proxy on Debian 12 nor Fedora 39 despite current-testing repos being enabled

### ISSUE THREAD

**Issue by xyhhx** [QubesOS/qubes-issues#9055]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

R4.1.2

### Brief summary

I can't install `qubes-ctap` on my Debian 12 nor Fedora 39 templates, and I can't install `qubes-u2f` on Fedora 39, despite current-testing repos being enabled

### Steps to reproduce

- Enable testing repos are enabled
- In a Fedora 39 based template:
  - Run `sudo dnf install -y qubes-ctap`
  - Try again with `qubes-u2f`
  - Observe that no packages are found
- In a Debian 12 based template:
  - Run `sudo apt install -y qubes-ctap`
  - Observe that no packages are found

### Expected behavior

The `qubes-ctap` package should be installed

**Comment by marmarek** [comment]
The qubes-ctap package is (kinda intentionally) held in current-testing repository for R4.1. It is in the current (aka stable) for R4.2.

**Comment by xyhhx** [comment]
Yeah I do have testing repos enabled, at least 

![Screenshot_2024-03-25_16-22-35](https://github.com/QubesOS/qubes-issues/assets/105510262/63355821-e96d-43f3-a20b-651c7083ddd1)

**Comment by marmarek** [comment]
But this is about _template_ repositories, not package repositories inside the template. See https://www.qubes-os.org/doc/how-to-install-software/#testing-repositories

**Comment by xyhhx** [comment]
Oh, got it. You're right I didn't have those repos enabled :sweat_smile: 

> The qubes-ctap package is (kinda intentionally) held in current-testing repository for R4.1

How unstable is it? Is there somewhere I can track its progress?

**Comment by marmarek** [comment]
> How unstable is it? Is there somewhere I can track its progress?

It's stable. But it has subtle differences compared to U2F version, so a surprise update for R4.1 users (that have the old version configured already) may have some unintended side effects.

**Comment by xyhhx** [comment]
Sweet, thanks
