### ISSUE TITLE
qubes-vm-update does nothing when targetting dom0

### ISSUE THREAD

**Issue by deeplow** [QubesOS/qubes-issues#9058]
### Qubes OS release
4.2

### Brief summary
`qubes-vm-update --targets dom0` does nothing

### Steps to reproduce
1. `qubes-vm-update --targets dom0`

### Expected behavior
Consistent behavior with `qubes-update-gui --targets dom0`, which seems to be to try to update dom0 even if there are no updates.

### Actual behavior
Exits immediately.

**Comment by marmarek** [comment]
Well, dom0 is not a normal VM...

Anyway, @piotrbartman what do you think about it?

**Comment by piotrbartman** [comment]
`qubes-vm-update` is intended to update non-admin vms. I agree this is confusing so I propose two alternative solutions:
1. print warning if user try to use `qubes-vm-update` to update dom0
2. run dom0 updater from `qubes-vm-update`

**Comment by marmarek** [comment]
At some point, I'd like a nice progress bar for dom0 updates too ;) which probably will be easiest to do by calling dom0 updates via `qubes-vm-update` tool too. But for now, IMO just a warning would be okay too.
