### ISSUE TITLE
Help text in policy editor is wrapped to too wide size

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#9060]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

R4.2

### Brief summary

When opening policy editor in a smaller window, the right side of help text is cut

### Steps to reproduce

1. Open policy editor
2. Make the window smaller

### Expected behavior

Either help text wraps to a smaller width, or help text area remains at the size of minimal text wrap width

### Actual behavior

Help text wraps until some minimal width is reached and then right side of it is cut.

![policy-editor-crop](https://github.com/QubesOS/qubes-issues/assets/726704/d670ae82-585c-4a07-b5ff-74f5a9b9b143)

**Comment by alimirjamali** [comment]
Ok. I had time to take a look at the Glade file and the code.

The current `width-request` for `source_window` is current set to [1000 pixels](https://github.com/QubesOS/qubes-desktop-linux-manager/blob/main/qubes_config/policy_editor.glade#L105-L106). And [500 pixels](https://github.com/QubesOS/qubes-desktop-linux-manager/blob/main/qubes_config/policy_editor.glade#L155-L156) for `help_window`. The total is 1500 pixels (excluding window border) which is above 1366 pixel width of common displays and above 1024 pixel of OpenQA test. Reducing the former to 800 pixel and the latter to 450 pixel makes it look good on 1366 pixel width displays. But most probably not on Open QA. We simply have too much data to display.

The current `height-request` for `main_window` is currently set at [800 pixels](https://github.com/QubesOS/qubes-desktop-linux-manager/blob/main/qubes_config/policy_editor.glade#L42-L43).  This is why the "Quit, Save Changes" and "Save and Exit" buttons do not show on 1366x768 displays as well as Open QA 1024x768 virtual display test. I suggest reducing it to 700 pixel as it looks good. This would also enable maximizing on the mentioned displays.

My other findings
- Adding 10 pixel `border-width` to help_viewport makes it look very nice.
- Maximizing on launch might be a good idea. As the program packs a lot of information and launching it maximized makes it comfortable. User could still un-maximize or resize the window.

Please let me know which points could be agreed, rejected or amended. So I could submit the pull-request. Here is the screen snapshot of program after launch with the applied changes (so far):

![policy_editor](https://github.com/QubesOS/qubes-issues/assets/5407317/1d34e95b-035f-4f4a-99be-0cdf2f807497)
