### ISSUE TITLE
Add RAM free/used/pressure and total CPU usage indicators to the Qubes Domains applet

### ISSUE THREAD

**Issue by bi0shacker001** [QubesOS/qubes-issues#9063]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### The problem you're addressing (if any)

The current amount of information provided doesn't help in determining total system load, which is important when attempting to make decisions on whether or not starting a new qube is acceptable, or if a qube can safely be provided more resources

### The solution you'd like

The basic solution would be:
To add at least a "free" memory indicator (meaning, memory not currently allocated to a VM/dom0), and a total CPU usage indicator to give an idea of total system load.
The ideal solution would be:
Adding a macos-style memory-pressure indicator (in the style of how istats menu provides one), to determine how much ram VMs actively WANT right now, as memory ballooning may make this somewhat difficult to determine

### The value to a user, and who that user might be

Users will have an easier time determining whether a VM itself is starved for resources, or if the system itself is overloaded, when lag or freezes occurs. It will also help users determine if the system is likely to be overwhelmed if they, say, open their development qube while continuing their current behavior.

While this information may be useful to all users of slower systems, or who have a large number of qubes, it will mostly be useful for users who run a lot of qubes, or have multiple high-resource qubes which may potentially load a system.

### Completion criteria checklist

(This section is for developer use only. Please do not modify it.)

**Comment by unman** [comment]
I think it is an extension of 8368 and a duplicate of 7735 for the CPU
monitor.
I would close this on that basis, with references in the other issues.

**Comment by bi0shacker001** [comment]
Neither of those would address my desire for a simple numerical indicator (I believe my request is simpler to implement), but I did miss them in my search, and can recognize that we're asking for thebsame thing to be implemented in different ways

**Comment by unman** [comment]
I think the discussion as to what form the indicator should take is best
covered in existing issues.
Thanks for your suggestion here.

**Comment by bi0shacker001** [comment]
Closing as duplicate of #7735 
Relevant, non-duplicate ticket exists as #8368
