### ISSUE TITLE
If told to open files in a disposable VM, Thunderbird crashes when attaching a file

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#9065]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

R4.2

### Brief summary

See title

### Steps to reproduce

See title

### Expected behavior

No crash

### Actual behavior

Crash because GTK cannot load a pixmap.

**Comment by marmarek** [comment]
Which template and TB version? I see a [test failure](https://openqa.qubes-os.org/tests/94390#step/TC_20_DispVM_fedora-39-xfce/4) on fedora-39-xfce this week, but it [passed](https://openqa.qubes-os.org/tests/94194#step/TC_20_DispVM_fedora-39-xfce/4) last week.

**Comment by DemiMarie** [comment]
Fedora 39, `thunderbird-115.9.0-1.fc39.x86_64`

**Comment by DemiMarie** [comment]
Simpler reproducer:

```
$ f=/usr/share/icons/Adwaita/16x16/places/folder-download.png
$ xdg-mime query filetype "$f"
image/png
$ XDG_DATA_DIRS=/usr/share/qubes/mime-override xdg-mime query filetype "$f"
application/octet-stream
```

The latter is wrong.

**Comment by DemiMarie** [comment]
Nevermind, the latter command is wrong.

**Comment by GWeck** [comment]
This may be related to the closed upstream issue described in [ Thunderbird may crash on Fedora 38 #8416 ](https://github.com/QubesOS/qubes-issues/issues/8416). Thunderbird will crash if it tries to open a file under Fedora 38/39.
