### ISSUE TITLE
Unable to install `qubes-mgmt-salt-vm-connector` in `debian-12-minimal`

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#9068]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

4.2

### Brief summary

Attempting to install `qubes-mgmt-salt-vm-connector` in `debian-12-minimal` without testing repos enabled fails because it depends on a package that is still in testing.

### Steps to reproduce

1. Install the `debian-12-minimal` template.
2. In the template, try to install `qubes-mgmt-salt-vm-connector`.

### Expected behavior

Package installs successfully. (This was the case with `debian-11-minimal` on Qubes 4.1.)

### Actual behavior

```
# apt install qubes-mgmt-salt-vm-connector
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 salt-common : Depends: python3-looseversion but it is not installable
               Recommends: python3-croniter but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by unman** [comment]
As of 20240509 the install completes as expected.
This issue can be closed.
