### ISSUE TITLE
Updater tool hangs where User Interaction required

### ISSUE THREAD

**Issue by unman** [QubesOS/qubes-issues#9072]
### Qubes OS release
4.2 Updated

### Brief summary
When updating a template where the update requires user interaction, the update hangs.

### Steps to reproduce
In a Debian template make changes to default settings for any package - e.g Qubes repo.list
Attempt to update template

### Expected behavior
Interaction in apt process will be passed up to Update tool.

### Actual behavior
Update hangs - progress shows interaction dialog

**Comment by marmarek** [comment]
@piotrbartman see duplicate I just reported, I can reproduce the issue too.
