### ISSUE TITLE
`qubes-vm-update` does not show progress bar for `Debian-minimal` templates 

### ISSUE THREAD

**Issue by neoniobium** [QubesOS/qubes-issues#9080]
### Qubes OS release

`Q4.2`

### Brief summary

When updating a `debian-12-minimal` template or a template cloned from it `qubes-vm-update` does not show the updates progress for those templates. `Debian-xfce` and `Fedora-xfce` are not effected.  

### Steps to reproduce

Run `qubes-vm-update --templates` in `dom0` with at least one a `debian-12-minimal` template or a template cloned for it installed. 

### Expected behavior

Progress bar and update status in % for all templates are shown in the terminal.

### Actual behavior

No progress bar and update status remains at 0% until the update finishes for all `debian-12-minimal` templates. However the update still succeeds.

**Comment by marmarek** [comment]
That's a side effect of minimal template being minimal. On Debian the updater needs extra package to be installed to get update progress - `python3-apt`. But, you should still see some APT output if you click on the template name, and you can estimate progress based on that...
