### ISSUE TITLE
Implement the best security practices for Qubes Forum (TLS 1.3 is not enabled..)

### ISSUE THREAD

**Issue by TNTBOMBOM** [QubesOS/qubes-issues#9087]
### Brief summary

Qubes should prioritize the security of its visitors by implementing the best security practices.

### Actual behavior

**DNS**

- No DNSSEC: 
https://www.hardenize.com/report/forum.qubes-os.org/1712182148#domain_dnssec

**TLS**

- No TLS 1.3 
- Not all the best ciphers used for TLS 1.2

https://www.hardenize.com/report/forum.qubes-os.org/1712182148#www_tls
https://www.ssllabs.com/ssltest/analyze.html?d=forum.qubes-os.org

- No HSTS: 

https://www.hardenize.com/report/forum.qubes-os.org/1712182148#www_hsts
https://www.ssllabs.com/ssltest/analyze.html?d=forum.qubes-os.org

**Headers**

- No Permissions-Policy Header used:

https://securityheaders.com/?q=forum.qubes-os.org&followRedirects=on 

### Expected behavior

https://www.hardenize.com/report/forums.whonix.org/1712195472#www_tls

https://securityheaders.com/?q=forums.whonix.org&followRedirects=on

**Comment by unman** [comment]
Qubes does not control the discourse hosting, as has been said before.
It would  be better to raise your concerns directly with
discoursehosting.net or perhaps indirectly in the Forum in the
feedback section.
There's nothing for Qubes to do here.

**Comment by DemiMarie** [comment]
nevermind, saw the other comment only after posting, oops.

**Comment by DemiMarie** [comment]
> Qubes does not control the discourse hosting, as has been said before. It would be better to raise your concerns directly with discoursehosting.net or perhaps indirectly in the Forum in the feedback section. There's nothing for Qubes to do here.

What about DNSSEC?
