### ISSUE TITLE
crond never starts in AppVMs

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#909]
**Reported by cprise on 28 Oct 2014 11:33 UTC**
The crond.service is never started when an AppVM boots up, and changing its status to 'enabled' with systemctl in the templateVM has no effect.

I haven't yet tested this with regular Fedora; Thinking it may be some side-effect of the way Qubes uses systemd.

See discussion https://groups.google.com/forum/#!topic/qubes-users/vVw1kZ1ph_A

Migrated-From: https://wiki.qubes-os.org/ticket/909

**Comment by adrelanos** [comment]
Could you please explain the rationale behind why crond does not run by default in any VM?

**Comment by marmarek** [comment]
In most cases none of crond started scripts makes sense in AppVM because changes in root filesystem are discarded. Like updatedb, mandb, prelink etc. And in most cases are harmful for performance (imagine 10 AppVMs running updatedb at the same time).
So instead of manually disabling dozen of them, disable cron as the whole, allowing to enable it if someone really needs.
Systemd timers are not affected by this.

**Comment by adrelanos** [comment]
Makes sense. Thank you!

What about anacron? Would not the same apply to it?

**Comment by marmarek** [comment]
> What about anacron? Would not the same apply to it?

Yes, exactly. But it is started from `crond` (in `cron.hourly`), so both are covered.

**Comment by adrelanos** [comment]
Are you sure anacron is not called from other places also?

apt-file list anacron

Relevant excerpt.

anacron: /etc/init.d/anacron
anacron: /etc/init/anacron.conf

anacron: /lib/systemd/system/anacron-resume.service
anacron: /lib/systemd/system/anacron.service
anacron: /usr/lib/pm-utils/power.d/anacron
anacron: /usr/lib/pm-utils/sleep.d/95anacron

I've just installed the anacron package and checked 'sudo service
anacron status' - and it's running announcing to run /etc/cron[...].

**Comment by marmarek** [comment]
Ah, so my comment applies only to Fedora then. I think it would be good idea to start in conditionally on `crond` qvm-service (similar to Fedora) and add to `crond` description in `qvm-service`. Any reason to give it a separate entry?

**Comment by adrelanos** [comment]
Would you like to reopen or do you prefer me to open a new ticket?

> Any
> reason to give it a separate entry?

Not that I can see. I think for such highly special needs, the user
should set it up that way manually and we should keep the default
simple. A single entry.

**Comment by marmarek** [comment]
> Would you like to reopen or do you prefer me to open a new ticket?

Since this was for R2.0, better new one.

**Comment by adrelanos** [comment]
Created https://github.com/QubesOS/qubes-issues/issues/2109 for it.
