### ISSUE TITLE
builderv2: clarify log and error messages

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#9092]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### The problem you're addressing (if any)

Builder log messages have executor-related prefix, but no information what is actually being done (which stage, which component etc)
The failure message has a python traceback, but the actual error also often doesn't include the critical details like what stage or component.

### The solution you'd like

Change the log prefix to include "what" (component, dist, stage) is done instead of "where" (executor). Log the executor info at the start of a stage, and also on failure (slightly related to https://github.com/QubesOS/qubes-issues/issues/9086).

### The value to a user, and who that user might be

Developers will have it easier to see what is currently being built.

### Completion criteria checklist

(This section is for developer use only. Please do not modify it.)

- [ ] Change the log format (maybe consider it an option?)
- [ ] Update example output in documentation, if any

**Comment by marmarta** [comment]
I'd also love for the non-actually-breaking messages to be not in red! It's kind of confusing for someone who does not actually understand how the builder works.

**Comment by marmarta** [comment]
Another proposal: maybe `debug: false` should be default? As I think is in most tools?
