### ISSUE TITLE
Opening app menu via keyboard shortcut opens it under the cursor

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#9093]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

4.2

### Brief summary

Opening app menu via keyboard shortcut opens it under the cursor instead of the normal location.

### Steps to reproduce

Assign app menu to a keyboard shortcut. Press that keyboard shortcut.

### Expected behavior

App menu opens in same location as if you had clicked the button to open it.

### Actual behavior

App menu opens under cursor, e.g., in the middle of the screen, unattached from panel.

**Comment by rustybird** [comment]
I thought the current behavior was intentional, isn't it convenient for mouse users?

https://github.com/QubesOS/qubes-desktop-linux-menu/blob/v1.1.5/qubes_menu/qubes-menu.glade#L8

**Comment by bi0shacker001** [comment]
> I thought the current behavior was intentional, isn't it convenient for mouse users?
> 
> https://github.com/QubesOS/qubes-desktop-linux-menu/blob/v1.1.5/qubes_menu/qubes-menu.glade#L8

That behavior is one of the primary reasons I wouldn't run qubes if I were forced into xfce. Even if it's convenient for mouse users, it's a huge PITA for keyboard-shortcut users (pressing enter will select whatever is under the mouse cursor, not the first option, which breaks pseudo-autocomplete, for instance)

**Comment by alimirjamali** [comment]
The current default position is set to `mouse` in the Glade file:

https://github.com/QubesOS/qubes-desktop-linux-menu/blob/main/qubes_menu/qubes-menu.glade#L8

A new command line option could be added to set the position (e.g. `--position POSITION`). Default could be `mouse` to keep the existing behaviour. User could set the position to `top-left`, `center`, ...

**Comment by alimirjamali** [comment]
Another approach could be depending on a `feature` to set the menu position. Just like how `app_page` feature is currently used to set the default Tab/Page.

Both approaches are easy to implement.

@marmarta Is it OK to add a command line option or feature to allow users to set the Appmenu position? (rather than at mouse position). I can work on it.

**Comment by alimirjamali** [comment]
Choices of icons and text for `Qubes Menu Settings`:

![menu_position1](https://github.com/user-attachments/assets/3dce5c60-c4ef-4d5d-b285-639a4888a9b2)

![menu_position2](https://github.com/user-attachments/assets/64ecd7b6-aeb9-4073-8cb6-b7cfcf3d8aac)

**Comment by alimirjamali** [comment]
PR Submitted

Review priority: Low

I will work on the relevant unittests if the change is good.

**Comment by alimirjamali** [comment]
This needs a final touch. Currently assigning `qubes-app-menu` to Super/Start key will open the Appmenu. But pressing it again does not hide it (it closes it and reopens it).

**Comment by alimirjamali** [comment]
> What do "left," "right," and "center" mean? My expectation of "normal" behavior would be for the app menu to be attached to the button on the panel that opens it.

Left, right or center of the screen. Or under the current mouse position. Since the menu height is set to (around) screen height, there is no need to set the vertical position. I assume most users will use either `left` or `mouse` options.

Attaching the Appmenu to the exact position of the button on the panel is much harder than it sounds. It requires a real Xfce plugin (work in progress for #2136).

> This sounds familiar, but I can't find an issue for it. I suggest opening a separate issue for it (unless you can find an existing one).

Yes. Exactly.

**Comment by alimirjamali** [comment]
> My menu currently takes up only about half of my screen height.

Oh. I see. Now that I look again at [code](https://github.com/QubesOS/qubes-desktop-linux-menu/blob/main/qubes_menu/appmenu.py#L208-L212), the 0.9x resize only downsizes the menu, not expand it.

So the positions could be Top-Left, Top-Right, Bottom-Left, Bottom-right and mouse position. Now that I reconsider it, adding option for centring menu vertically or horizontally is useless. Hope everyone agrees with it.
