### ISSUE TITLE
Attaching some USB devices to qubes fails

### ISSUE THREAD

**Issue by swamba** [QubesOS/qubes-issues#9104]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

4.1.2

### Brief summary

After upgrading qubes-usb-proxy to version 1.2.0-1 then some USB devices fail to attach. In my experience then if the USB id is of the form 1-1.4.0.1 (or similar) then it fails, if it is of the form 3-2 then it succeeds.

### Steps to reproduce

Attach a USB device that gets a USB id of form x-y.z.i.k and try to attach it to a qube.

### Expected behavior

The device is attached to a specific qube

### Actual behavior

An error pops up saying "Attaching device xxxx to $qube failed. Error: QubesExceptio - Device attached failed"

I traced this down to a failed regex in file usb-export (qubes-app-linux-usb-proxy repo) on line 89

if ! [[ "$busid" =~ ^[0-9]+-[0-9]+$ ]]; then

This handles USB ids x-y and x-y.z.i.k differently.

**Comment by patrickhener** [comment]
I have the same issue and can confirm that commenting the lines that got lost in the pull request will indeed fix the issue.
