### ISSUE TITLE
Ability in Dracut Emergency Shell to set with `localectl` the Keymap

### ISSUE THREAD

**Issue by Ricky-Tigg** [QubesOS/qubes-issues#9109]
### The problem you're addressing

Ability in _Dracut Emergency Shell_ to set the `keymap` accordingly to the keyboard

Hello. Being redirected to Emergency mode, it seems logical to seek to acquire the `/run/initramfs/rdsosreport.txt` file. So, as stated as the instruction, we compile <kbd>ctrl</kbd> + <kbd>D</kbd> in order to enter the said Shell – its name is omitted. As a result, the prompt displayed is `sh-5.2`. I suspected for reason the latter of being GNU bash. So I executed `help`, a Bash built-in command; it turns out to indeed be GNU bash. Armed with this knowledge, all that remains is to list the supported commands, by pressing <kbd>tab</kbd> twice.

Here though, what matters in terms of being in position to acquire this file or investigating for troubleshooting purposes is that `localectl` is missing. Certainly, there are some things in life that are guaranteed to exist: death, taxes, the default _system locale_ and default _VC keymap_ for UNIX, respectively `LANG=en_US.UTF-8` and `us`.

In such a mode, you may be like me trapped, this `keymap` does not match your keyboard, which results in the printing of characters which do not correspond to the keys pressed. Due to this defect, we find ourselves in the position of not being able to resolve this limitation in such a Shell.

It would be unusual to have to exhibit those keyboard layouts:

![keyboard layout en_US 0](https://github.com/QubesOS/qubes-issues/assets/26058215/37042144-1faa-4177-81bd-c6a7a831fa05)

![keyboard layout en_US 1](https://github.com/QubesOS/qubes-issues/assets/26058215/29a411df-c94e-4ab4-b06c-b5967e689b3e)

for example, either on a separate monitor or as printed on paper. An attempt to modify manually in directory `/etc`, related files _locale.conf_ (if existing) and _vconsole.conf_ would not seem to be aviable option.

### The solution you'd like

Instead, the introduction of `localectl` into the _Dracut Emergency Shell_ would be all what is needed.

### The value to a user, and who that user might be

- _value_ | Getting out of the blocking situation of not being able to define the appropriate `keymap`, thus allowing a task to be accomplished.
- _who_ | User led to Emergency mode and having to deal in Dracut Emergency Shell – GNU bash.

**Comment by unman** [comment]
https://github.com/dracutdevs/dracut/issues/1826
