### ISSUE TITLE
qubes-updates-proxy: Start request repeated too quickly

### ISSUE THREAD

**Issue by kaie** [QubesOS/qubes-issues#9110]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
4.2

### Brief summary
qubes-updates-proxy fails to start in sys-net.

systemctl status qubes-updates-proxy
reports:
```
sys-net systemd[1]: qubes-updates-proxy.service: Start request repeated too quickly.
sys-net systemd[1]: qubes-updates-proxy.service: Failed with result 'start-limit-hit'.
sys-net systemd[1]: Failed to start qubes-updates-proxy.service - Qubes updates proxy (tinyproxy).
```

### Steps to reproduce
Shut down all VMs.
Start up sys-net, either directly or indirectly.
Try to update a qube, which fails.
Open a terminal in sys-net and check systemctl, the above service has failed to start.

I can manually work around the issue, after sys-net has started, by running this command:
systemctl start qubes-updates-proxy

### Additional notes

I originally mentioned my update problems in issue #9025 and claimed it had to with the template that sys-net was based on.
That was an incorrect statement, I had incorrectly concluded that, I got misled during my various attempts to resolve that issue on my system.

The new issue I'm reporting happens regardless of the template used for sys-net, I tried both debian-12-xfce and fedora-39-xfce.

**Comment by marmarek** [comment]
Can you check earlier logs why it failed initially? You can get it with `sudo journalctl b -u qubes-updates-proxy` in sys-net.

**Comment by kaie** [comment]
I guess you meant "-b -u" (not "b -u")

Apr 12 16:26:23 sys-net systemd[1]: Started qubes-updates-proxy.service - Qubes updates proxy (tinyproxy).
Apr 12 16:26:23 sys-net tinyproxy-wrapper[680]: Found tinyproxy at /usr/bin/tinyproxy
Apr 12 16:26:23 sys-net tinyproxy[680]: Initializing tinyproxy ...
Apr 12 16:26:23 sys-net tinyproxy-wrapper[680]: WARNING: obsolete config item on line 14
Apr 12 16:26:23 sys-net tinyproxy-wrapper[680]: WARNING: obsolete config item on line 15
Apr 12 16:26:23 sys-net tinyproxy-wrapper[680]: WARNING: obsolete config item on line 16
Apr 12 16:26:23 sys-net tinyproxy-wrapper[680]: WARNING: obsolete config item on line 17
Apr 12 16:26:23 sys-net tinyproxy[680]: Reloading config file
Apr 12 16:26:23 sys-net tinyproxy[680]: Reloading config file finished
Apr 12 16:26:25 sys-net tinyproxy[680]: Shutting down.
Apr 12 16:26:25 sys-net tinyproxy-wrapper[885]: Found tinyproxy at /usr/bin/tinyproxy
Apr 12 16:26:25 sys-net tinyproxy-wrapper[885]: WARNING: obsolete config item on line 14
Apr 12 16:26:25 sys-net tinyproxy-wrapper[885]: WARNING: obsolete config item on line 15
Apr 12 16:26:25 sys-net tinyproxy-wrapper[885]: WARNING: obsolete config item on line 16
Apr 12 16:26:25 sys-net tinyproxy-wrapper[885]: WARNING: obsolete config item on line 17
Apr 12 16:26:25 sys-net tinyproxy[885]: Initializing tinyproxy ...
Apr 12 16:26:25 sys-net tinyproxy[885]: Reloading config file
Apr 12 16:26:25 sys-net tinyproxy[885]: Reloading config file finished
Apr 12 16:26:25 sys-net systemd[1]: Stopping qubes-updates-proxy.service - Qubes updates proxy (tinyproxy)...
Apr 12 16:26:25 sys-net systemd[1]: qubes-updates-proxy.service: Deactivated successfully.
Apr 12 16:26:25 sys-net systemd[1]: Stopped qubes-updates-proxy.service - Qubes updates proxy (tinyproxy).
Apr 12 16:26:25 sys-net systemd[1]: Started qubes-updates-proxy.service - Qubes updates proxy (tinyproxy).
Apr 12 16:26:27 sys-net systemd[1]: Stopping qubes-updates-proxy.service - Qubes updates proxy (tinyproxy)...
Apr 12 16:26:27 sys-net tinyproxy[885]: Shutting down.
Apr 12 16:26:27 sys-net systemd[1]: qubes-updates-proxy.service: Deactivated successfully.
Apr 12 16:26:27 sys-net systemd[1]: Stopped qubes-updates-proxy.service - Qubes updates proxy (tinyproxy).
Apr 12 16:26:27 sys-net systemd[1]: Started qubes-updates-proxy.service - Qubes updates proxy (tinyproxy).
Apr 12 16:26:27 sys-net tinyproxy-wrapper[1146]: Found tinyproxy at /usr/bin/tinyproxy
Apr 12 16:26:27 sys-net tinyproxy-wrapper[1146]: WARNING: obsolete config item on line 14
Apr 12 16:26:27 sys-net tinyproxy-wrapper[1146]: WARNING: obsolete config item on line 15
Apr 12 16:26:27 sys-net tinyproxy-wrapper[1146]: WARNING: obsolete config item on line 16
Apr 12 16:26:27 sys-net tinyproxy-wrapper[1146]: WARNING: obsolete config item on line 17
Apr 12 16:26:27 sys-net tinyproxy[1146]: Initializing tinyproxy ...
Apr 12 16:26:27 sys-net tinyproxy[1146]: Reloading config file
Apr 12 16:26:27 sys-net tinyproxy[1146]: Reloading config file finished
Apr 12 16:26:27 sys-net tinyproxy[1146]: Shutting down.
Apr 12 16:26:27 sys-net systemd[1]: Stopping qubes-updates-proxy.service - Qubes updates proxy (tinyproxy)...
Apr 12 16:26:27 sys-net systemd[1]: qubes-updates-proxy.service: Deactivated successfully.
Apr 12 16:26:27 sys-net systemd[1]: Stopped qubes-updates-proxy.service - Qubes updates proxy (tinyproxy).
Apr 12 16:26:27 sys-net systemd[1]: Started qubes-updates-proxy.service - Qubes updates proxy (tinyproxy).
Apr 12 16:26:27 sys-net tinyproxy-wrapper[1222]: Found tinyproxy at /usr/bin/tinyproxy
Apr 12 16:26:27 sys-net tinyproxy-wrapper[1222]: WARNING: obsolete config item on line 14
Apr 12 16:26:27 sys-net tinyproxy-wrapper[1222]: WARNING: obsolete config item on line 15
Apr 12 16:26:27 sys-net tinyproxy-wrapper[1222]: WARNING: obsolete config item on line 16
Apr 12 16:26:27 sys-net tinyproxy-wrapper[1222]: WARNING: obsolete config item on line 17
Apr 12 16:26:27 sys-net tinyproxy[1222]: Initializing tinyproxy ...
Apr 12 16:26:27 sys-net tinyproxy[1222]: Reloading config file
Apr 12 16:26:27 sys-net tinyproxy[1222]: Reloading config file finished
Apr 12 16:26:29 sys-net systemd[1]: Stopping qubes-updates-proxy.service - Qubes updates proxy (tinyproxy)...
Apr 12 16:26:29 sys-net tinyproxy[1222]: Shutting down.
Apr 12 16:26:29 sys-net systemd[1]: qubes-updates-proxy.service: Deactivated successfully.
Apr 12 16:26:29 sys-net systemd[1]: Stopped qubes-updates-proxy.service - Qubes updates proxy (tinyproxy).
Apr 12 16:26:29 sys-net systemd[1]: Started qubes-updates-proxy.service - Qubes updates proxy (tinyproxy).
Apr 12 16:26:29 sys-net tinyproxy-wrapper[1282]: Found tinyproxy at /usr/bin/tinyproxy
Apr 12 16:26:29 sys-net tinyproxy-wrapper[1282]: WARNING: obsolete config item on line 14
Apr 12 16:26:29 sys-net tinyproxy-wrapper[1282]: WARNING: obsolete config item on line 15
Apr 12 16:26:29 sys-net tinyproxy-wrapper[1282]: WARNING: obsolete config item on line 16
Apr 12 16:26:29 sys-net tinyproxy-wrapper[1282]: WARNING: obsolete config item on line 17
Apr 12 16:26:29 sys-net tinyproxy[1282]: Initializing tinyproxy ...
Apr 12 16:26:29 sys-net tinyproxy[1282]: Reloading config file
Apr 12 16:26:29 sys-net tinyproxy[1282]: Reloading config file finished
Apr 12 16:26:29 sys-net tinyproxy[1282]: Shutting down.
Apr 12 16:26:29 sys-net systemd[1]: Stopping qubes-updates-proxy.service - Qubes updates proxy (tinyproxy)...
Apr 12 16:26:29 sys-net systemd[1]: qubes-updates-proxy.service: Deactivated successfully.
Apr 12 16:26:29 sys-net systemd[1]: Stopped qubes-updates-proxy.service - Qubes updates proxy (tinyproxy).
Apr 12 16:26:29 sys-net systemd[1]: qubes-updates-proxy.service: Start request repeated too quickly.
Apr 12 16:26:29 sys-net systemd[1]: qubes-updates-proxy.service: Failed with result 'start-limit-hit'.
Apr 12 16:26:29 sys-net systemd[1]: Failed to start qubes-updates-proxy.service - Qubes updates proxy (tinyproxy).

**Comment by kaie** [comment]
I think the lines 14-17 it complains about are:

MinSpareServers 2
MaxSpareServers 10
StartServers 2
MaxRequestsPerChild 0

**Comment by kaie** [comment]
I think the above log isn't helpful to understand the reason for the restart.
Looking at other log items I see:

Apr 12 16:26:24 sys-net systemd[1]: tinyproxy.service - Tinyproxy lightweight HTTP Proxy was skipped because of an unmet condition check (ConditionPathExists=/var/run/qubes-service/tinyproxy).

Should that maybe check for tinyproxy.pid ?
I'll try to change file /usr/lib/systemd/system/tinyproxy.service.d/30_not_needed_in_qubes_by_default.conf
which contains that condition

**Comment by kaie** [comment]
Hmm, not sure my theory is right.

The existing script looks for something in /var/run/qubes-service/ 
I don't have any entries named tinyproxy in that directory.

The pid file I had suggested to check for is in
/var/run/tinyproxy-updates/tinyproxy.pid
(and this was just a wild guess, I'm just reporting what file with a name containing the word "tinyproxy" I can find in /var/run

**Comment by marmarek** [comment]
tinyproxy.service is a different thing than qubes-updates-proxy.service. Do you see any other log entries? Maybe NetworkManager is quickly changing settings (updates proxy is reloaded on each IP change)

**Comment by doublehelix24** [comment]
I can confirm @kaie's findings: When my laptop is connected to LAN and Wifi at the same time then the updates proxy is down.
Restarting qubes-updates-proxy in sys-net fixes it.

**Comment by bzcanli** [comment]
I have too many vlans connected via ethernet. I can confirm that is the reason "start-limit-hit" on qubes-updates-proxy.service . I modified  sys-net (where my qubes-updates-proxy.service is running) /lib/systemd/system/qubes-updates-proxy.service file. Added StartLimitBurst=0 under [Service]. It solved for me. Ref: https://www.suse.com/support/kb/doc/?id=000019750
