### ISSUE TITLE
`qvm-run --localcmd` is inconsistent with `qrexec-client -l`

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#9113]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

R4.2

### Brief summary

`qrexec-client` parses the argument to `-l` as a qrexec command, whereas the argument to `qvm-run --localcmd=` is passed straight to the shell.

### Steps to reproduce

`qvm-run '--localcmd=QUBESRPC SERVICE+ARG remote_domain name requested_target'`

### Expected behavior

Runs `SERVICE+ARG` as if it was an RPC command

### Actual behavior

`QUBESRPC: command not found`

**Comment by marmarek** [comment]
Nobody promises they would behave the same, and in fact they can't when `qvm-run` is called outside of dom0, as `qrexec-client` is not there at all.

**Comment by DemiMarie** [comment]
> Nobody promises they would behave the same, and in fact they can't when `qvm-run` is called outside of dom0, as `qrexec-client` is not there at all.

I see.

The motivation for this report is that `qvm-console-dispvm` (which is dom0-only) currently emulates a qrexec call to dom0.  I was hoping to use something like the following to avoid this:

```sh
qrexec-client -Tkd "$DISPVM" \
   -l "QUBESRPC admin.vm.Console dom0 name $QREXEC_REQUESTED_TARGET" \
  "DEFAULT:QUBESRPC qubes.ShowInTerminal dom0"
```

However, the proposed change would also cause problems.  Specifically, it would make the guest and host behaviors inconsistent with each other, and would break any use of nontrivial shell features (such as pipes or conditionals) when running in a guest.  So I agree that this should not be implemented as-is, even though the ability of `qrexec-client` to execute local qrexec commands is quite intriguing.
