### ISSUE TITLE
Qubes testing repo key in Fedora templates not trusted by default

### ISSUE THREAD

**Issue by Geblaat** [QubesOS/qubes-issues#9122]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
R4.2
`Fedora-39` template and F`edora-39-xfce` template.

### Brief summary
The GPG key for qubes-vm-r4.2-security-testing (mayble also current-testing and unstable) is not trusted by default it seems. 
DNF asks the user to trust the key.
This was not the case with Fedora-38 template and older on R4.1.

### Steps to reproduce
Execute `sudo dnf update --enablerepo=qubes-vm-r4.2-security-testing`
Fedora 39 - x86_64 - Updates                     12 kB/s |  23 kB     00:01    
Qubes OS Repository for VM (security-testing)    88  B/s | 833  B     00:09    
Qubes OS Repository for VM (security-testing)   1.5 MB/s | 2.4 kB     00:00    
Importing GPG key 0x8E34D89F:
 Userid     : "Qubes OS Release 4.2 Signing Key"
 Fingerprint: 9C88 4DF3 F810 64A5 69A4 A9FA E022 E58F 8E34 D89F
 From       : /etc/pki/rpm-gpg/RPM-GPG-KEY-qubes-4.2-primary

### Expected behavior
Key is trusted by default, user does not have to verify this himself.

### Actual behavior
User has to verify the key himself.

**Comment by marmarek** [comment]
That's standard, expected dnf behavior. Key (from a local file, as the message shows) is imported on first use. If you use GUI updater, you won't see this message - that's likely why you haven't noticed it before.
