### ISSUE TITLE
Can't shutdown qube if it has AudioVM property set to itself

### ISSUE THREAD

**Issue by ben-grande** [QubesOS/qubes-issues#9127]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

R4.2

### Brief summary

I understand that the qui-domains widget can't shutdown/restart a qube if it is a netvm or audiovm because there are qubes connected to them. But if the `audiovm` is itself, it is connected to itself and should be able to shutdown. But it can't shutdown via the widget.

### Steps to reproduce

1. Set the property `audiovm` of a qube to itself
2. Try to shutdown using the qui-domains widget in the system tray
3. Fail with warning message.

### Expected behavior

Shutdown qube.

### Actual behavior

> The following error occurred while attempting to shut down qube disp-sys-usb:
>    There are running VMs using this VM as AudioVM: disp-sys-usb

**Comment by alimirjamali** [comment]
There is a workaround for that. If the Audio Hardware is provided by dom0 (e.g. Intel ICH PCI), set the `audiovm` property for _sys-audio_ to dom0. If the Audio Hardware is provided by _sys-usb_ (e.g. an External audio interface), set the audiovm property for _sys-audio_ to _sys-usb_.

Consider the following logic for the above config: `sys-audio` depends on dom0 or sys-usb for its function. So they must had been started before it.

**Comment by ben-grande** [comment]
I want to update that the issue is not only from the widget, it also occurs on the command-line with `qvm-shutdown disp-sys-usb`.

> There is a workaround for that. If the Audio Hardware is provided by dom0 (e.g. Intel ICH PCI), set the `audiovm` property for _sys-audio_ to dom0. If the Audio Hardware is provided by _sys-usb_ (e.g. an External audio interface), set the audiovm property for _sys-audio_ to _sys-usb_.
> 
> Consider the following logic for the above config: `sys-audio` depends on dom0 or sys-usb for its function. So they must had been started before it.

I am aware that I can do that, but then it is 3 steps, removing the preference, shutting down and setting the preference again. The issue was opened so it can be fixed.

**Comment by alimirjamali** [comment]
The bug could be easily solved by changing line 28 of `/usr/lib/python3.11/site-packages/qubes/ext/audio.py` (originally a part of [qubes-core-admin](https://github.com/QubesOS/qubes-core-admin/blob/release4.2/qubes/ext/audio.py#L28-L29) repository from:

```
            if getattr(domain, 'audiovm', None) and domain.audiovm == vm:
                yield domain
```

to

```
            if getattr(domain, 'audiovm', None) and domain.audiovm == vm and domain != vm :
                yield domain
```

A reset will be necessary.

**Comment by ben-grande** [comment]
Thanks. @alimirjamali do you plan to open a PR or should I do?

> A reset will be necessary.

A reboot is necessary?

**Comment by alimirjamali** [comment]
> Thanks. @alimirjamali do you plan to open a PR or should I do?

Since I use  the `audiovm=dom0` workaround myself, I personally do not see a necessity to do that. I appreciate if you could do it.

> A reboot is necessary?

Yes. If you observe the `/usr/lib/python3.11/site-packages/qubes/ext/__pycache__/` directory, you will see the compiled `audiovm.cpython-*-pyc` files. Unlike general perception, python is not always an interpreted language. Libraries are compiled for acceleration purposes. But this only happens on import. I did not go deep enough to see when and which service imports `audio.py` to inform you of the exact service you have to restart.

**Comment by ben-grande** [comment]
I took too long, thanks @marmarek. I tested @alimirjamali version before I saw your commit and it works and I suppose your solution is faster as it doesn't need to run `getattr()` for that case.

**Comment by ben-grande** [comment]
PR does not appear to be linked yet, only commit to your own repo, therefore linking it.

https://github.com/QubesOS/qubes-core-admin/pull/584
