### ISSUE TITLE
Not getting the `Caps Lock?` message when entering XScreenSaver password with Caps Lock enabled

### ISSUE THREAD

**Issue by emanruse** [QubesOS/qubes-issues#9132]
### The problem you're addressing (if any)

The screen unlocker dialog of XFCE provides no visual feedback about Caps Lock being pressed.

### The solution you'd like

Provide CapsLock visual clue for XFCE screen unlocker.

### The value to a user, and who that user might be

Less failed screen unlock attempts.

### Completion criteria checklist

(This section is for developer use only. Please do not modify it.)

**Comment by alimirjamali** [comment]
> My expectation is to have the "Caps Lock?" while typing, not after pressing Enter. This would prevent authentication error rather than inform about it post-factum.

This is something within the hands of the original XscreenSaver upstream developer (Jamie Zawinski). Qubes OS specific patches to it are limited to logos and minor changes. A grave change such as this might break it entirely (in its future updates which might include important security patches).
