### ISSUE TITLE
Fedora-39-based `sys-net` does not start `qubes-updates-proxy`

### ISSUE THREAD

**Issue by GWeck** [QubesOS/qubes-issues#9151]
### Qubes OS release

R4.2.1

### Brief summary

If `sys-net` is based on Fedora-39, the service `qubes-updates-proxy` is started after booting Qubes, stops, and fails on its automatic restart.

### Steps to reproduce

Boot Qubes R4.2.1.

### Expected behavior

The service should run normally, and template updates should work.

### Actual behavior

After booting, open a terminal in Fedora-39-based `sys-net`, and enter `sudo systemctl status qubes-updates-proxy`.  The following log is shown:

~~~
[user@NB001WK ~]$ sudo systemctl status qubes-updates-proxy
× qubes-updates-proxy.service - Qubes updates proxy (tinyproxy)
     Loaded: loaded (/usr/lib/systemd/system/qubes-updates-proxy.service; enabled; preset: enabled)
    Drop-In: /usr/lib/systemd/system/service.d
             ??10-timeout-abort.conf
     Active: failed (Result: start-limit-hit) since Wed 2024-04-24 15:18:23 CEST; 31s ago
   Duration: 182ms
    Process: 771 ExecStart=/usr/lib/qubes/tinyproxy-wrapper -d -c /etc/tinyproxy/tinyproxy-updates.conf (code=exited, status=0/SUCCESS)
   Main PID: 771 (code=exited, status=0/SUCCESS)
        CPU: 13ms

Apr 24 15:18:23 sys-net systemd[1]: Started qubes-updates-proxy.service - Qubes updates proxy (tinyproxy).
Apr 24 15:18:23 sys-net tinyproxy-wrapper[771]: Found tinyproxy at /usr/bin/tinyproxy
Apr 24 15:18:23 sys-net systemd[1]: Stopping qubes-updates-proxy.service - Qubes updates proxy (tinyproxy)...
Apr 24 15:18:23 sys-net systemd[1]: qubes-updates-proxy.service: Deactivated successfully.
Apr 24 15:18:23 sys-net systemd[1]: Stopped qubes-updates-proxy.service - Qubes updates proxy (tinyproxy).
Apr 24 15:18:23 sys-net systemd[1]: qubes-updates-proxy.service: Start request repeated too quickly.
Apr 24 15:18:23 sys-net systemd[1]: qubes-updates-proxy.service: Failed with result 'start-limit-hit'.
Apr 24 15:18:23 sys-net systemd[1]: Failed to start qubes-updates-proxy.service - Qubes updates proxy (tinyproxy).
~~~

Any attempt to update a template will fail with `[Proxy CONNECT aborted]`. Restarting the service will succeed, and then template updates will work normally.

This behavior has occurred since a few days, probably after the last updates to Fedora-39.

**Comment by marmarek** [comment]
Can you check unfiltered `journalctl` output for more details about the failure reason?

**Comment by Murdock01** [comment]
Looks like the qubes-updates-proxy service is activated in every qube.
Test:
- create new qube from template debian-12-xfce (qubes-updates-proxy is NOT explicitely added as service in that qube)
- start terminal in that new created qube
- check qubes-updates-proxy service status

sudo systemctl status qubes-updates-proxy
○ qubes-updates-proxy.service - Qubes updates proxy (tinyproxy)
     Loaded: loaded (/lib/systemd/system/qubes-updates-proxy.service; enabled; >
     Active: inactive (dead)
  Condition: start condition failed at Thu 2024-04-25 08:55:16 CEST; 23s ago
             └─ ConditionPathExists=|/var/run/qubes-service/qubes-updates-proxy>

Apr 25 08:55:16 test systemd[1]: qubes-updates-proxy.service - Qubes updates pr>
lines 1-7/7 (END)

So in my understanding, during start it exists multiple trys to start that service, it the service explicitly added.
Same behaviour with fedora-39-xfce based qubes.

**Comment by GWeck** [comment]
The problems occur only when `sys-net` is used after booting Qubes. Stopping and restarting the VM leads to a working proxy.

> Can you check unfiltered `journalctl` output for more details about the failure reason

Here are 3 files:

- [Journalctl.txt](https://github.com/QubesOS/qubes-issues/files/15107913/Journalctl.txt) is the log of trying (unsuccessfully) to start `qubes-updates-proxy` when `sys-net` starts during Qubes boot..
- [After_Restart.txt](https://github.com/QubesOS/qubes-issues/files/15107912/After_Restart.txt) shows the status of `qubes-updates-proxy` after restarting `sys-net`.
- [Journalctl2.txt](https://github.com/QubesOS/qubes-issues/files/15107911/Journalctl2.txt) is the log of starting `qubes-updates-proxy` during the restart of `sys-net`.

**Comment by Murdock01** [comment]
On my system a simple restart of sys-net does not start properly qubes-updates-proxy.
I must manually restart the qubes-updates-proxy via
`sudo systemctl restart qubes-updates-proxy`
The service is restarted and 
`systemctl status qubes-updates-proxy`
looks normal after that manual restart.

**Comment by tvondra** [comment]
I think I ran into this issue today, after switching sys-net from fedora-38-xfce to fedora-39-xfce. Updating any template fails with this:

```
Updating fedora-39-xfce
Install requirements
Refreshing package info
Errors during downloading metadata for repository 'fedora':
  - Curl error (56): Failure when receiving data from the peer for https://mirrors.fedoraproject.org/metalink?repo=fedora-39&arch=x86_64 [Proxy CONNECT aborted]
Failed to download metadata for repo 'fedora': Cannot prepare internal mirrorlist: Curl error (56): Failure when receiving data from the peer for https://mirrors.fedoraproject.org/metalink?repo=fedora-39&arch=x86_64 [Proxy CONNECT aborted]
``` 

and restarting the sys-net VM, or the qubes-updates-proxy did not help at all.

journalctl on sys-net however shows this, which I did not see mentioned here:

```
Jun 12 19:18:29 sys-net qrexec-agent[1085]: 2024-06-12 19:18:29.792 qrexec-agent[1085]: qrexec-agent-data.c:242:handle_new_process_common: failed to spawn process
Jun 12 19:18:29 sys-net qrexec-agent[1085]: 2024-06-12 19:18:29.792 qrexec-agent[1085]: exec.c:751:find_qrexec_service: Refusing to execute executable service /etc/qubes-rpc/qubes.UpdatesPr>
Jun 12 19:18:29 sys-net qrexec-agent[1083]: 2024-06-12 19:18:29.673 qrexec-agent[1083]: qrexec-agent-data.c:242:handle_new_process_common: failed to spawn process
Jun 12 19:18:29 sys-net qrexec-agent[1083]: 2024-06-12 19:18:29.673 qrexec-agent[1083]: exec.c:751:find_qrexec_service: Refusing to execute executable service /etc/qubes-rpc/qubes.UpdatesPr>
Jun 12 19:18:29 sys-net qrexec-agent[1081]: 2024-06-12 19:18:29.537 qrexec-agent[1081]: qrexec-agent-data.c:242:handle_new_process_common: failed to spawn process
Jun 12 19:18:29 sys-net qrexec-agent[1081]: 2024-06-12 19:18:29.537 qrexec-agent[1081]: exec.c:751:find_qrexec_service: Refusing to execute executable service /etc/qubes-rpc/qubes.UpdatesPr>
```
The timestamps match the attempted template update. I have not found the reason for this, but switching sys-net to fedora-40-xfce resolved the issue for me for now.

**Comment by marmarek** [comment]
@tvondra That's a different issue, lets move to #9299

**Comment by GWeck** [comment]
Closing the issue as the bug does not appear any longer in this form.
