### ISSUE TITLE
Add option to start qube without waiting on netvm

### ISSUE THREAD

**Issue by zaz** [QubesOS/qubes-issues#9156]
### The problem

When starting a domain, you must wait for its netvm to be started before startup of that domain is initiated.  Furthermore, it seems there is no way to start a VM without starting its netvm unless you set the netvm to none, start the VM, and then reset the netvm.

### The solution you'd like

Allow `qvm-start --no-wait-for-net-vm domain` and `qvm-start --no-start-net-vm domain`

I believe this will require a change in [qubes-core-admin qvm_start.py](https://github.com/QubesOS/qubes-core-admin-client/blob/e54eb38ce634af66d9f8213bb70a0c2282841e96/qubesadmin/tools/qvm_start.py) and in [the backend in def start](https://github.com/QubesOS/qubes-core-admin/blob/ba8bc65520b36899043d63a115ad43efdf83fe74/qubes/vm/qubesvm.py#L1180).

### The value to a user

This will allow the user a way to start a VM without starting its netvm (perhaps for security purposes) and it may allow an improvement in startup time if we use `--no-wait-for-net-vm` on initial startup.

Furthermore, some laptops experience a delay of a minute or so in starting the netvm due to firmware issues.

### Completion criteria checklist

(This section is for developer use only. Please do not modify it.)

**Comment by marmarek** [comment]
You can't start a VM that has network interface but that network interface backend (netvm) is not running, the VM will not start at all.
If you want to start a VM without network, set netvm to none, as you proposed already.

**Comment by zaz** [comment]
Thank you!

What technically stops this (other than the code I linked to above)?  If I poweroff a netvm, the VMs that use it continue to run fine, just without internet.  What makes it impossible to start a VM without its netvm?

**Comment by marmarek** [comment]
Shutting down netvm kinda disconnects it from the qube, you could say `qvm-ls` listing it as still attached is a bit inaccurate then.
