### ISSUE TITLE
qrexec-fork-server ignores RPC config

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#9161]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

R4.2

### Brief summary

When `qrexec-fork-server` is in use, socket-based services do not respect `skip-service-descriptor=true` in the service config, it always sends the descriptor. In fact, `strace` shows the config file is not loaded at all.

### Steps to reproduce

This uses a TCP-based service (#9037).

1. `ln -s /dev/tcp/127.0.0.1/1234 /etc/qubes-rpc/test.service`
2. `echo skip-service-descriptor=true > /etc/qubes/rpc-config/test.service`
3. `socat TCP-LISTEN:1234,fork -`
4. Try to use the service

Alternatively:
1. Take https://github.com/QubesOS/qubes-core-agent-linux/pull/495
5. Try to use `qubes.ConnectTCP` or `qubes.UpdatesProxy`

### Expected behavior

Only data sent by the service caller is sent

### Actual behavior

Service descriptor is sent first, confusing the service.

**Comment by marmarek** [comment]
@DemiMarie

**Comment by marmarek** [comment]
FWIW my test included also https://github.com/QubesOS/qubes-core-qrexec/pull/137

**Comment by DemiMarie** [comment]
This _does not_ reproduce in the test harness: the descriptor _is not_ sent if `skip-service-descriptor = true` is in the config file, and _is_ sent otherwise.

**Comment by marmarek** [comment]
Is the test about dom0 service or domU service? Here the failure is in a domU (via qrexec-fork-server).
I can confirm it works as expected in dom0.

**Comment by DemiMarie** [comment]
The test runs qrexec-agent but does _not_ run qrexec-fork-server.  In fact I believe qrexec-fork-server has no tests at all, outside of openQA.

**Comment by marmarek** [comment]
I don't think it matters, it's the same code, just in a different process.
Anyway, I tried without fork server, and it doesn't work either - strace says the config is not loaded at all. And also, without fork server SELinux denies the connection...

**Comment by DemiMarie** [comment]
> I don't think it matters, it's the same code, just in a different process. Anyway, I tried without fork server, and it doesn't work either - strace says the config is not loaded at all. And also, without fork server SELinux denies the connection...

It’s not the same code: [`qrexec-agent` loads the service config](https://github.com/QubesOS/qubes-core-qrexec/blob/652b8f59084735968f9e74f0aa97b6709e861da2/agent/qrexec-agent.c#L596-L601) and [`qrexec-fork-server` does not](https://github.com/QubesOS/qubes-core-qrexec/blob/652b8f59084735968f9e74f0aa97b6709e861da2/agent/qrexec-fork-server.c#L93-L99).  This made sense back when the service config was only used for `wait-for-session=1`, which the fork server doesn’t care about.  Now that the service config is much more heavily used it is far more problematic.

**Comment by marmarek** [comment]
Should socket services (including TCP) skip using fork server then (and adjust SELinux policy to allow that)?

**Comment by marmarek** [comment]
> Anyway, I tried without fork server, and it doesn't work either - strace says the config is not loaded at all.

Not true, with SELinux disabled as a workaround it does work.

**Comment by DemiMarie** [comment]
> Should socket services (including TCP) skip using fork server then (and adjust SELinux policy to allow that)?

That’s the simplest fix.  I’m inclined to go with it for a few reasons:

1. The fork server adds (a tiny amount of) overhead, and socket-based services are meant to be fast.
2. We don’t honor the username for socket-based services anyway, _except_ if the fork server is in use.  That means that `user` and `root` work, but other users don’t, which is inconsistent and confusing.  It would be much clearer to unconditionally ignore the username in this case.  This is _theoretically_ a breaking change, but only in what is (IMO) a pathological case (`AF_UNIX` server that must be called not as root).
3. We have no unit tests for the fork server (part of #9163) so I would really not prefer to make it any more complex than it needs to be.
