### ISSUE TITLE
Create new qube: Template has network by default

### ISSUE THREAD

**Issue by deeplow** [QubesOS/qubes-issues#9174]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### The problem you're addressing (if any)

When we create a new template qube (e.g. via clone), this is what the  settings look like when one clicks on the template tab (notice the **network** part)

<img src="https://github.com/QubesOS/qubes-issues/assets/47065258/71f15200-3caf-4aeb-b76a-908a1089c86c" width=500 >

### The solution you'd like
When clicking the template tab `No network connection` should be the default option. This probably is not the case due to the network connection being "saved" from the previous (default) tab which are app qubes.

### The value to a user, and who that user might be
Foot-shooting prevention.

### Completion criteria checklist

(This section is for developer use only. Please do not modify it.)

**Comment by marmarek** [comment]
> The answer is at GUI level

Yes, the GUI needs to show accurate info before creating the qube.

**Comment by alimirjamali** [comment]
PR for sub-task 1 is submitted.

Review priority: low

It changes the ComboBoxes for Template &  Networking to (none) if you select TemplateVM in the 1st combo box. It also locks the Template ComboBox to (none) if TemplateVM is selected. They are reverted to their default value if user selects another type. Here is the video:


https://github.com/user-attachments/assets/01b2e575-e0b8-4959-adf3-0043adc98f66

**Comment by marmarek** [comment]
I don't think locking is appropriate, it's a valid choice to make network-connected template if one really wants that (for example it's kinda-necessary for Windows to be able to install updates there).

Anyway, for the old create qube dialog, I would prefer to simply remove it. Focus on the new one.

**Comment by alimirjamali** [comment]
> I don't think locking is appropriate, it's a valid choice to make network-connected template if one really wants that (for example it's kinda-necessary for Windows to be able to install updates there).

Locking is done only for the middle ComboBox (the `Template:` ComboBox). Not for Networking.

> Anyway, for the old create qube dialog, I would prefer to simply remove it (and make qubes manager use the new one). Focus on the new one.

Sure. Will be done soon.

**Comment by marmarek** [comment]
> Locking is done only for the middle ComboBox (the `Template:` ComboBox). Not for Networking.

Ah, okay, makes sense.
