### ISSUE TITLE
Default app qubes (work, personal, untrusted) have hardcoded netvm (instead of default)

### ISSUE THREAD

**Issue by deeplow** [QubesOS/qubes-issues#9175]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
4.2.1 (tried on fresh install)

### Brief summary
Default app qubes like `work` have `sys-firewall` [set as the default netvm](https://github.com/QubesOS/qubes-mgmt-salt-dom0-virtual-machines/blob/main/qvm/work.sls#L29). This means that if the user wants to set a VPN qube as the default netvm, the default VMs will not take in this new setting, potentially leading to opsec mistakes.

### Steps to reproduce
1. Be on a fresh install
2. Inspect network settings for app qubes (work, personal, untrusted)

### Expected behavior
Net qube is set to `sys-firewall (default)` for those app qubes.

### Actual behavior
Net qube is set to `sys-firewall` instead of `sys-firewall (default)`

**Comment by alimirjamali** [comment]
The salt sates for the mentioned VMs set the default NetVM to sys-firewall ([personal](https://github.com/QubesOS/qubes-mgmt-salt-dom0-virtual-machines/blob/v4.2.14/qvm/personal.sls#L28-L29), [untrusted](https://github.com/QubesOS/qubes-mgmt-salt-dom0-virtual-machines/blob/v4.2.14/qvm/untrusted.sls#L29), [work](https://github.com/QubesOS/qubes-mgmt-salt-dom0-virtual-machines/blob/v4.2.14/qvm/work.sls#L28-L29)).
