### ISSUE TITLE
`nogui` in policy file

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#9180]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### The problem you're addressing (if any)

qrexec supports `nogui:` to disable GUI forwarding, but this isn’t exposed via qrexec policy.  It is possible to achieve this via a malformed username but that’s a bug (#9154).

### The solution you'd like

Support `nogui=true` in policy.

### The value to a user, and who that user might be

Be able to specify `nogui` in policy without relying on a hack that will break in the future.

### Completion criteria checklist

(This section is for developer use only. Please do not modify it.)

**Comment by marmarek** [comment]
No, for qrexec services the "nogui" is actually the default. The proper way to achieve the opposite is `wait-for-session=0` in the service config.

**Comment by marmarek** [comment]
> qrexec supports `nogui:` to disable GUI forwarding

And also, this is completely _not_ what this thing does. It's about waiting for the GUI session to startup (or not).

**Comment by DemiMarie** [comment]
> No, for qrexec services the "nogui" is actually the default. The proper way to achieve the opposite is `wait-for-session=1` in the service config.

Does this mean that exposing `nogui:` via the `qvm-run` CLI but _not_ via policy is intentional?

**Comment by marmarek** [comment]
The `qvm-run` for an arbitrary command (without `--service`) without `--no-gui` uses a service that has `wait-for-session=1`.

**Comment by DemiMarie** [comment]
Looks like the Windows agent [does care if `nogui:` is used](https://github.com/QubesOS/qubes-windows-utils/blob/f50e3c72f384445cc984e2a059bf6112abf57877/src/exec.c#L599-L600), and this could actually matter for e.g. RPC services running as a Windows service account (which cannot log in interactively, IIUC).

**Comment by DemiMarie** [comment]
> No, for qrexec services the "nogui" is actually the default. The proper way to achieve the opposite is `wait-for-session=1` in the service config.

Default on Linux but not on Windows.

**Comment by marmarek** [comment]
Still, environment in which service is executed is up to the executing VM and its configuration, not the policy. Please do not reopen this ticket again (nor create new equivalent).

**Comment by DemiMarie** [comment]
> Still, environment in which service is executed is up to the executing VM and its configuration, not the policy.

I see.  Does that mean that `nogui:` having an affect on Windows that cannot be achieved in any other way is a Windows agent limitation that needs to be fixed in Qubes Windows Tools?

**Comment by marmarek** [comment]
Yes. At some point.

**Comment by DemiMarie** [comment]
I filed #9198 for that.
