### ISSUE TITLE
no networking in in-place-upgraded fedora-38-minimal

### ISSUE THREAD

**Issue by legobeat** [QubesOS/qubes-issues#9187]
### Qubes OS release
4.2.1 (upgraded from 4.1)

### Brief summary

After performing an [in-place upgrade](https://www.qubes-os.org/doc/templates/fedora/in-place-upgrade/) of TemplateVM `fedora-36-minimal` to Fedora 38, AppVMs using the resulting `fedora-38-minimal` do not have working networking.

Other templates have been upgraded fine, including standard `fedora-36` to `fedora-38`.

### Steps to reproduce

Follow [in-place upgrade instructions](https://www.qubes-os.org/doc/templates/fedora/in-place-upgrade/) to upgrade `fedora-36-minimal` to Fedora 38.

### Expected behavior

Working networking and assigned IP address.

### Actual behavior

No networking or IP address:
```
$ ip addr

1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: enX0: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether 00:16:3e:5e:6c:00 brd ff:ff:ff:ff:ff:ff
```

Note the interface name `enX0`, which differs from the `eth0` of working qubes.
This can be seen in dmesg:

```
[    2.687029] xen_netfront: Initialising Xen virtual ethernet driver
[    2.699907] xen_netfront: backend supports XDP headroom
[    2.699932] vif vif-0: bouncing transmitted data to zeroed pages
[    2.739628] EXT4-fs (xvdb): mounted filesystem xxxx r/w with ordered data mode. Quota mode: none.
[    2.776251] audit: type=1334 audit(1714624330.233:10): prog-id=24 op=LOAD
[    2.898102] vif vif-0 enX0: renamed from eth0
[    2.973632] intel_rapl_msr: PL4 support detected.
```

**Comment by marmarek** [comment]
Minimal template is expected to not have networking, unless you install extra packages, see https://www.qubes-os.org/doc/templates/minimal/

**Comment by legobeat** [comment]
> Minimal template is expected to not have networking, unless you install extra packages, see https://www.qubes-os.org/doc/templates/minimal/

Ah, right. I guess I didn't expect to redo that on an in-place upgrade where networking has already been enabled and previously working - but thanks.

Maybe a docs improvement could be to link to that page from the in-place-upgrade page with a note for minimal templates.
