### ISSUE TITLE
qui-devices: Missing bus and device information and option for attaching specific partitions

### ISSUE THREAD

**Issue by emanruse** [QubesOS/qubes-issues#9189]
### Qubes OS release

4.2.1

### Brief summary

The old qui-devices showed BDF info about devices (which was good) and there was the option for attaching an individual partition through the UI ("slightly more secure" as per doc). In the new version, these are both removed.

### Steps to reproduce

Run qui-devices.

### Expected behavior

- Display bus and device info.
- Have the option to attach only a specific partition.

### Actual behavior

None of the above exist any more.

**Comment by UndeadDevel** [comment]
Isn't this fixed now with the PR that closed #9164?
