### ISSUE TITLE
Template state is confusing after upgrade to 4.2

### ISSUE THREAD

**Issue by kord1e** [QubesOS/qubes-issues#9204]
### Qubes OS release

4.2.0, just upgraded from 4.1

### Brief summary

After upgrading system to 4.2.0, template info is still showing older version.

### Steps to reproduce

1. debian-12 and fedora-39 templates exist on the system, they have been upgraded in-place from previous versions.
2. System was upgraded to 4.2.0, all stages were executed

### Expected behavior

Templates should be up-to-date... because they were upgraded during the system upgrade? 

### Actual behavior

Qubes template manager shows these templates as "upgradable" and the following information is shown by `qvm-template info`

```
$ qvm-template info fedora-39
Installed Templates
Name          :  fedora-39
Epoch         :  0
Version       :  4.0.6
Release       :  202205270243
Size          :  18.7 GiB
Repository    :  qubes-templates-itl
Buildtime     :  2022-05-27 03:11:26
Install time  :  2022-06-29 16:35:26
URL           :  http://www.qubes-os.org
License       :  GPL
Summary       :  Qubes template for fedora-36
Description   :  Qubes template for fedora-36
                  
Available Templates
Name         :  fedora-39
Epoch        :  0
Version      :  4.2.0
Release      :  202403091939
Size         :  1.5 GiB
Repository   :  qubes-templates-itl
Buildtime    :  2024-03-09 23:36:00
URL          :  http://www.qubes-os.org
License      :  GPLv3+
Summary      :  Qubes OS template for fedora-39
Description  :  Qubes OS template for fedora-39.
```
```
$ qvm-template info debian-12
Installed Templates
Name          :  debian-12
Epoch         :  0
Version       :  4.0.6
Release       :  202201171556
Size          :  15.9 GiB
Repository    :  @commandline
Buildtime     :  2022-01-17 16:33:58
Install time  :  2022-01-30 15:50:02
URL           :  http://www.qubes-os.org
License       :  GPL
Summary       :  Qubes template for debian-11
Description   :  Qubes template for debian-11
                  
Available Templates
Name         :  debian-12
Epoch        :  0
Version      :  4.2.0
Release      :  202308072102
Size         :  1.4 GiB
Repository   :  qubes-templates-itl
Buildtime    :  2023-08-07 21:44:00
URL          :  http://www.qubes-os.org
License      :  GPLv3+
Summary      :  Qubes OS template for debian-12
Description  :  Qubes OS template for debian-12.
```

**Comment by kord1e** [comment]
> This works as expected, `qvm-template info` shows what template was installed not what later happened to it. Similarly, it doesn't include all the modifications you make there (like installing extra applications, or even just installing updates inside the template).

Ok, but this is confusing because the template should be up to date, it was even "upgraded" by the 4.2.0 system upgrade. But it is still shown as "upgradable" and it's shown that there is another template available with the same name.

**Comment by marmarek** [comment]
It lists other "Available Templates" if you want to install a fresh one. There is no "upgradable" or similar word in the output.
