### ISSUE TITLE
`qubes-dom0-update --refresh --check-only` fails when using Whonix

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#9212]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

R4.2 with all testing updates enabled.

### Brief summary

The GUI update tool cannot update dom0, complaining about a bad GPG signature on the metadata.  `qubes-dom0-update` works, as does the `update.qubes-dom0` Salt state.

### Steps to reproduce

Update dom0 via the GUI.

### Expected behavior

Works

### Actual behavior

Fails

**Comment by marmarek** [comment]
Please be more specific - provide exact error message you got

**Comment by DemiMarie** [comment]
```
Updating dom0...
dom0 does not support in-progress update information.
Using sys-whonix as UpdateVM to download updates for Dom0; this may take some time...
Checking for dom0 updates...
Importing GPG key 0x8E34D89F:
 Userid     : "Qubes OS Release 4.2 Signing Key"
 Fingerprint: 9C88 4DF3 F810 64A5 69A4 A9FA E022 E58F 8E34 D89F
 From       : /var/lib/qubes/dom0-updates/etc/pki/rpm-gpg/RPM-GPG-KEY-qubes-4.2-primary
Error: Failed to download metadata for repo 'qubes-dom0-current': repomd.xml GPG signature verification error: Bad GPG signature
Failed to check for dom0 updates
```

**Comment by marmarek** [comment]
Does it happen every time, or was it one time network glitch?
I cannot reproduce it. And also, the GUI updater literally calls `qubes-dom0-update`, so it's weird one works for you but not the other.
Do you have any usual configuration?

**Comment by DemiMarie** [comment]
The bug reproduced twice, but I think this may have been a combination of Tor being slow to start and truncated downloads being mishandled.

**Comment by DemiMarie** [comment]
Happened a third time today.  Maybe some flag passed to `qubes-dom0-update` causes problems?

**Comment by DemiMarie** [comment]
I managed to reproduce this without the GUI.  `sudo qubes-dom0-update` works, while `qubes-dom0-update --check-only` fails with the error mentioned in the initial report.

**Comment by DemiMarie** [comment]
> Does it happen every time, or was it one time network glitch? I cannot reproduce it. And also, the GUI updater literally calls `qubes-dom0-update`, so it's weird one works for you but not the other.

Can you try `qubes-dom0-update --refresh --check-only` when updating over Tor?

**Comment by DemiMarie** [comment]
I’m not sure why this didn’t cause a problem for other people, but I do have a fix.
