### ISSUE TITLE
Enable creation of private volumes in separate pools for newly created qubes.

### ISSUE THREAD

**Issue by fepitre** [QubesOS/qubes-issues#9215]
### The problem you're addressing (if any)
Currently, in Qubes OS, there's no straightforward method for users to easily create a private volume for a qube in a separate pool from its root volume provided by a template qube. This can be cumbersome for users who require isolation of their data or wish to manage storage resources more efficiently (e.g. build machines that have multiple disks).

### The solution you'd like
Introduce a feature or enhancement that enables users to easily create private volumes for qubes in separate pools from their template qubes' root volumes. This could involve an intuitive user interface within the Qubes Manager or additional options during the qube creation process to specify storage pool preferences for private volumes. Add an option to have default pool used for private volumes. In such approach, we could have templates being installed in the primary storage and each time we create a new qube, it would create its private volume in the selected default pool.

### The value to a user, and who that user might be
- **Efficient Resource Management**: Users who wish to manage storage resources more efficiently by segregating root volumes from private volumes will find this feature valuable.
- **Simplified Workflow**: This enhancement will streamline the process of setting up qubes with private volumes, reducing the complexity for both new and experienced Qubes OS users.

### Completion criteria checklist
- [ ] Add additional options (managed with `qubes-prefs`) to support set of default pool for creation of private volumes.
- [ ] Design and implement UI changes or additional options in the Qube Manager to support set of default pool for creation of private volumes.
- [ ] Update documentation and user guides to include instructions on utilizing this new feature.

**Comment by marmarek** [comment]
App qube always has root volume in the same pool as its template. Other volumes can be easily chosen with a "qvm-create -P" switch, or in the "advanced" section in the "create new qube" window. So, the functionality you request already exists. Am I missing something?

**Comment by fepitre** [comment]
Yes, I would love to have default pool for template and a default pool to be chosen only for private volumes. As of now, I don't think this is possible. There is only a default pool choice in that case, all the RPMs you install goes there. This is not suitable if you want to keep installed templates in, say `vm-pool` and having all the created qube having there private volume into say `build-pool`.

**Comment by fepitre** [comment]
I have really in mind the usage of QubesExecutor where I would like to have by default correct separation of disk usage.

**Comment by rustybird** [comment]
Does `qubes-prefs default_pool_private` work for the QubesExecutor use case? Or is it "too global", maybe you only want to configure the default for private volumes of AppVMs that are based on a specific template?

**Comment by fepitre** [comment]
> Does `qubes-prefs default_pool_private` work for the QubesExecutor use case? Or is it "too global", maybe you only want to configure the default for private volumes of AppVMs that are based on a specific template?

I think per-template or maybe per-dispvm-template could be very useful.

**Comment by marmarek** [comment]
you can simply have dispvm-template in specific pool, then dispvms based on that template are in the same pool too

**Comment by fepitre** [comment]
> you can simply have dispvm-template in specific pool, then dispvms based on that template are in the same pool too

The problem is that if the disk dies (like I'm experimenting), I would just need to change the pool and not redoing the setup of the failed VM.

**Comment by marmarek** [comment]
I'm not sure if I understand, but here you mean changing the pool, which is #9216 , not here

**Comment by fepitre** [comment]
> you can simply have dispvm-template in specific pool, then dispvms based on that template are in the same pool too

I don't want to have the dispvm template, say `builder-dvm` (in `vm-pool`) in the same pool than its dispvm based on it (in `build-pool`).

**Comment by marmarek** [comment]
> I don't want to have the dispvm template, say `builder-dvm` (in `vm-pool`) in the same pool than its dispvm based on it (in `build-pool`).

I see. Then it's not going to work. Storage template (root volume from template to its app qubes, private volume from disposable template to its disposable qubes) works by copy-on-write, and those must be in the same pool to work. So, if you want them to be in a different pool, then I guess the proper label for this issue is `R: declined`

**Comment by rustybird** [comment]
@fepitre I'd just keep a pristine `builder-dvm-orig` stashed away in `vm-pool`, and clone that to `builder-dvm` in `build-pool` as needed (whenever the latter pool has to be recreated).

**Comment by fepitre** [comment]
> > I don't want to have the dispvm template, say `builder-dvm` (in `vm-pool`) in the same pool than its dispvm based on it (in `build-pool`).
> 
> I see. Then it's not going to work. Storage template (root volume from template to its app qubes, private volume from disposable template to its disposable qubes) works by copy-on-write, and those must be in the same pool to work. So, if you want them to be in a different pool, then I guess the proper label for this issue is `R: declined`

I really don't understand why it's hard to have one volume being ephemeral root on one pool (supposedly it's not going to do a lot of IO in `vm-pool`) with a private volume in another pool?

**Comment by fepitre** [comment]
> @fepitre I'd just keep a `builder-dvm-orig` stashed away in `vm-pool` and clone that to `builder-dvm` in `build-pool` as needed (whenever the latter pool has to be recreated). Although that might take a while if there's a substantial amount of data in the 'private' volume of `builder-dvm-orig`...

This is the thing I'm already doing not only for that build template but other stuff because I had so much drives that died with the copied template on the pool which has a lot of I/O.

**Comment by marmarek** [comment]
> I really don't understand why it's hard to have one volume being ephemeral root on one pool (supposedly it's not going to do a lot of IO in `vm-pool`) with a private volume in another pool? And this by default for this given template or given dispvm-template.

There is no issue with having root volume in one pool and private in another (see https://github.com/QubesOS/qubes-issues/issues/9215#issuecomment-2105650702). But there **is** issue with having disaposable template's private volume in one volume while its dispvm's private volume in another.

**Comment by fepitre** [comment]
> > I really don't understand why it's hard to have one volume being ephemeral root on one pool (supposedly it's not going to do a lot of IO in `vm-pool`) with a private volume in another pool? And this by default for this given template or given dispvm-template.
> 
> There is no issue with having root volume in one pool and private in another (see [#9215 (comment)](https://github.com/QubesOS/qubes-issues/issues/9215#issuecomment-2105650702)). But there **is** issue with having disaposable template's private volume in one volume while its dispvm's private volume in another.

Ok but why ? We just provide to the VM a secondary volume being elsewhere and mounted as `/rw`. What am I missing?

**Comment by marmarek** [comment]
Private volume of a disposable qube is a _snapshot_ of a private volume of its disposable template. It is not an independent fresh disk. That's why changes in /home, /rw etc made in disposable template are visible in its disposable qubes.
See https://www.qubes-os.org/doc/templates/#inheritance-and-persistence

**Comment by marmarek** [comment]
> I want to have all the private volumes of a dispvm derived from `builder-dvm` being in a dedicated pool.

You can do this by having private volume of `builder-dvm` in this "dedicated pool"

**Comment by fepitre** [comment]
Ok so I'll close this issue and find another way to have it working in all the cases I have.
