### ISSUE TITLE
Change output format of qvm-ls to something sane

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#923]
**Reported by woju on 12 Nov 2014 14:28 UTC**
1. Let's get rid of the ASCII art table anyway. It contributes nothing. Compare it to `xl list`, `virsh list` etc.

2. Make flags field for boolean (and close to boolean) attributes, like internal, include in backups and even running.

3. Let user choose freely from available columns (in addition to current switches like -n). Cf. `ps -o`. Let him/her(/it in case of software) choose even arbitrary variables aka properties. It's really easier than it sounds.

4. Introduce simple filters like "templates", "only running", "HVM" etc. (vm.__class__.__name__ == ...)

Migrated-From: https://wiki.qubes-os.org/ticket/923

**Comment by kalkin** [comment]
Some time ago i wrote a zsh function which shows a nicer human readable output. Maybe it will inspire someone to solve it similar in python
```
▶ dom0            Running  Yes  Admin  n/a          black   19677MB
▶ foo             Running              *firewallvm  orange  4096MB
▶ emacs           Running              *firewallvm  orange  2048MB
▶ firewallvm      Running       Proxy  netvm        green   3000MB
◍ bar             Transient            *firewallvm  blue    4096MB
■ private         Halted               *firewallvm  green   4000MB
▶ media           Running              firewallvm   yellow  2048MB
▶ netvm           Running       Net    n/a          red     300MB
▶ news            Running              *firewallvm  green   4000MB
▶ zum             Running              *firewallvm  green   4000MB
▶ skype           Running              *firewallvm  green   1024MB
```

**Comment by marmarek** [comment]
@woju can you paste output from the core3 qvm-ls?
-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by woju** [comment]
```
NAME                          STATUS   LABEL      TEMPLATE                     NETVM
dom0                          0rU----- -          -                            -
testvm                        a------- red        fedora-21                    -
fedora-21                     t-U----- black      -                            -
```

Actually we can close this, because it was fixed long ago in core3 branch.

**Comment by marmarek** [comment]
Just to make sure: besides this fancy `STATUS` column, is it possible to get something human-readable? With VM type ("AppVM", "TemplateVM" etc), status ("running"), ...

**Comment by woju** [comment]
On Mon, Oct 12, 2015 at 04:02:00PM -0700, Marek Marczykowski-Górecki wrote:
> Just to make sure: besides this fancy `STATUS` column, is it possible
> to get something human-readable? With VM type ("AppVM", "TemplateVM"
> etc), status ("running"), ...

No, it is not at the moment. But it can be, if it is needed.
