### ISSUE TITLE
dom0: 6.6.x kernel panics during boot on Lenovo ThinkPad X1 Carbon Gen 10 Intel 

### ISSUE THREAD

**Issue by sidhussmann** [QubesOS/qubes-issues#9252]
### Qubes OS release

R4.2

### Brief summary

When booting Qubes with a 6.6.x kernel, dom0 panics most of the times:

![kernel-panic](https://github.com/QubesOS/qubes-issues/assets/37871887/5e46e860-73e8-4985-b28e-c9cdb909c137)

I can reproduce this with the following kernels:

- `6.6.9-1`
- `6.6.25-1`
- `6.6.29-1`

With the following kernel, the kernel panic never happens:

- `6.1.75-1`

#### System information

Brand: LENOVO
Model: 21CBCTO1WW

CPU: 12th Gen Intel(R) Core(TM) i7-1270P
Chipset: Intel Corporation Device [8086:4621] (rev 02)
Graphics: Intel Corporation Alder Lake-P GT2 [Iris Xe Graphics] [8086:46a6] (rev 0c) (prog-if 00 [VGA controller])

RAM: 32433 Mb

QubesOS version: R4.2.1
BIOS: N3AET79W (1.44 )
Kernel: 6.1.75-1
Xen: unknown

#### Possibly related:

I noticed the following issues: #9177 and #9082. However, they look unrelated to me.

### Steps to reproduce

Boot Qubes OS with a 6.6.x kernel.

### Expected behavior

Qubes OS boots successfully.

### Actual behavior

Qubes OS panics during boot.

**Comment by marmarek** [comment]
Do you use USB keyboard? This looks like you don't have `rd.qubes.hide_all_usb` on the kernel cmdline.

Anyway, the panic is still an issue somewhere.

**Comment by marmarek** [comment]
FWIW this is kinda similar hardware to the certified NV41PZ, and it works fine there. It's probably related to some firmware difference. Especially I see Intel ME related functions on the traceback, and I guess Lenovo has more ME features enabled than NovaCustom.

**Comment by sidhussmann** [comment]
> Do you use USB keyboard? 

Yes. However, removing all external USB devices still yields a kernel panic with the 6.6.29 kernel. 

> This looks like you don't have `rd.qubes.hide_all_usb` on the kernel cmdline.

Adding `rd.qubes.hide_all_usb` to `GRUB_CMDLINE_LINUX` in `/etc/default/grub` with a `sudo grub2-mkconfig -o /boot/grub2/grub.cfg` also yields a dom0 kernel panic with the 6.6.29 kernel. 

Additionally, with `rd.qubes.hide_all_usb` and on the 6.1.75 kernel, `sys-usb` fails to start (also without any external usb devices attached).

**Comment by marmarek** [comment]
> also yields a dom0 kernel panic with the 6.6.29 kernel.

Is it the same one? If so (and there is no more interleaving USB-related message), maybe it isn't related to USB after all and it's just a coincidence it happened at this time?

**Comment by sidhussmann** [comment]
> > also yields a dom0 kernel panic with the 6.6.29 kernel.
> 
> Is it the same one? If so (and there is no more interleaving USB-related message), maybe it isn't related to USB after all and it's just a coincidence it happened at this time?

It's hard to tell as it seldom shows the log output of the kernel panic as seen in the issue description. I assume there is no other way to access the log output if my computer doesn't have a physical RS-232 connector, right?

**Comment by marmarek** [comment]
you can remove "quiet" and "rhgb" from the kernel cmdline, and also add "noreboot" to xen options - it should improve chances of catching the message on the screen

As for the serial console, there are options, see https://github.com/QubesOS/qubes-issues/issues/6834#issuecomment-1296221396 for example. Another option I use is a serial PCIe card in M.2 form factor, but those are not easy to get.

**Comment by apparatius** [comment]
> As for the serial console, there are options, see [#6834 (comment)](https://github.com/QubesOS/qubes-issues/issues/6834#issuecomment-1296221396) for example. Another option I use is a serial PCIe card in M.2 form factor, but those are not easy to get.

There is also an option to use Thunderbolt-PCIe adapter with PCIe-Serial card:
https://egpu.io/best-egpu-buyers-guide/#tb3-enclosures

**Comment by sidhussmann** [comment]
I created a new `sys-usb` qube with `sudo qubesctl state.sls qvm.sys-usb` and added `rd.qubes.hide_all_usb` to the kernel cmdline. This fixes starting `sys-usb` on the 6.1.75 kernel.

> you can remove "quiet" and "rhgb" from the kernel cmdline, and also add "noreboot" to xen options - it should improve chances of catching the message on the screen

With these options, the kernel panic (6.6.29) yields framebuffer glitches, so the output is harder to read:

![kernel-panic](https://github.com/QubesOS/qubes-issues/assets/37871887/506d14ee-f25b-4895-860e-90a9da87ebb7)

I then noticed that the panic happens during auto-start of `sys-usb`, `sys-net`, `sys-firewall`, and `vault`. I then disabled auto-start of these qubes. Out of 3 times, 2 times dom0 would start the desktop but freeze after a few seconds. One time, I was able to do a `qvm-start sys-usb` and the freeze would happen at the subsequent `qvm-start sys-net`.

FWIW, the panic also happens with `kernel-latest` -> `6.8.8`

> As for the serial console, there are options, see [#6834 (comment)](https://github.com/QubesOS/qubes-issues/issues/6834#issuecomment-1296221396) for example. Another option I use is a serial PCIe card in M.2 form factor, but those are not easy to get.

I will try this option next.

**Comment by sidhussmann** [comment]
Attaching an external display helped me with reading the log output during the panic. It turns out that I had the following PCI device attached to `sys-net`:

- `00:14.3 Network controller: Intel Corporation Alder Lake-P PCH CNVi WiFi (rev 01)`
- `00:16.0 Communication controller: Intel Corporation Alder Lake PCH HECI Controller (rev 01)`

Removing device `00:16.0` fixed the problem for me. I haven't experienced a kernel panic with 6.6.29 after several reboots.

Thank you @marmarek for your help!

**Comment by ddxor** [comment]
I experienced this behaviour also.

Updating to the latest `kernel-latest kernel-latest-qubes-vm` packages got me past this.

To do so:

1. When your boot gets stuck, press CTRL+ALT+F2 to get to a TTY shell.
2. Log in.
3. Start `sys-net`, `sys-firewall` and connect to WiFi to install the updates:

```
qvm-start sys-net
qvm-start sys-firewall
qvm-run --pass-io sys-net "nmcli device wifi connect 'MyWifiName' password 'MyWifiPassword'
sudo qubes-dom0-update kernel-latest kernel-latest-qubes-vm
sudo reboot
```
