### ISSUE TITLE
statistics page on qubes-os.org is not updated since 9th may

### ISSUE THREAD

**Issue by tarsa** [QubesOS/qubes-issues#9258]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

n/a

### Brief summary

statistics on https://www.qubes-os.org/statistics/ are outdated. should show recent statistics, but data shown is from 9th may.

### Steps to reproduce

go to https://www.qubes-os.org/statistics/ and see that chart on https://tools.qubes-os.org/counter/stats.png is outdated

### Expected behavior

page https://www.qubes-os.org/statistics/ should show fresh statistics

### Actual behavior

statistics shown are:
![stats](https://github.com/QubesOS/qubes-issues/assets/1282159/9ff9370f-7d2c-4158-9a64-87a73e5f529c)

**Comment by marmarek** [comment]
Fixed, thanks
