### ISSUE TITLE
qubes-builderv2 fails to build jammy-minimal with `no space left on device` error

### ISSUE THREAD

**Issue by GammaSQ** [QubesOS/qubes-issues#9264]
### Qubes OS release
4.2

### Brief summary
Using the `ubuntu.yml` config, edited to only build the minimal-template, the command `./qb template build` quits with:

```
Running template stage: build
08:50:03,870 [executor:docker:594361f90b27] Executing 'sudo mkdir -p -- /builder /builder/build /builder/plugins /builder/distfiles&&sudo chown -R -- user:user /builder&&make -C /builder/plugins/template prepare build-rpm'.
08:50:36,261 [executor:docker:594361f90b27] Error response from daemon: write /builder/build/qubeized_images/jammy-minimal/root.img: no space left on device
Error: jammy-minimal: Failed to build template.
```

### Steps to reproduce
I'm missing documentation on how to build ubuntu with the new qubes-builderv2, user-error is likely.

1. copy `ubuntu.yml` to qubes-builderv2 root path as `builder.yml`. Open `builder.yml` to edit:
  * add key-ids of all maintainers to the git section.
  * export all maintainer-keys in `[key-id].asc` format, add their path to `builder.yml` as:
    ```
    gpg-client: 'gpg'
    
    key-dirs:
      - /home/user/qubes-builderv2/artifacts/keys
    ```
  * comment all template-configs not related to jammy-minimal
2. Clone `quber-builder-debin` to `artifacts/components/builder-debian`
3. Run `docker build -f dockerfiles/debian.Dockerfile -t qubes-builder-debian artifacts/components/builder-debian`
4. Run `./qb package fetch`, `./qb package prep`, `./qb package build`, `./qb template fetch` (apparently does nothing), `./qb template prep`, `./qb template build`

### Expected behavior
A jammy-minimal template is built

### Actual behavior
Fails with error `no space left on device`.

### Additional information
I'm building minimal because during `./qb package prep` installation of `qubes-vm-recommended` because some packages are uninstallable. (It takes ~2h to get to this point, I'll have a closer look if it's requested.)

I had to guess how to build the `qubes-builder-debian` image and suspect something went wrong there. The helper-script seems to only address fedora images.

The VM this is running on is a standalone, based on a vanilla fedora-39 template. It has 50GB storage, increased from 30GB when I first ran into this error, docker pruned and rebuilt several times. I don't think it has anything to do with the VM running out of storage.

**Comment by apparatius** [comment]
Did you only increase system storage? Increase private storage as well.

**Comment by mattsalves** [comment]
### Steps to Resolve Space Issue in qubes-builderv2

1. **Increase Storage**: Ensure you've expanded both system and private storage adequately.

2. **Check Docker settings**: Verify Docker is configured to use the increased storage.

3. **Review qubes-builder-debian build**: Double-check for errors or misconfigurations.

4. **Verify configuration files**: Ensure builder.yml and Dockerfiles are accurately configured.

5. **Resolve uninstallable packages**: Investigate and fix any dependency issues.

6. **Monitor disk usage**: Identify and address any excessive space usage.

7. **Start with a clean environment**: Begin the build process with a fresh setup to avoid any lingering issues.

**Comment by fepitre** [comment]
This is clearly a space issue with `/var/lib/docker` and your `artifacts_dir` location. Please note that when building template, you have to manipulate big raw image and here at least 20GB.

**Comment by GammaSQ** [comment]
Thanks, I overlooked increasing the root storage, going from 30GB to 50GB fixed the issue.

For future reference: `artifacts_dir` was and is the local `/home/user/qubes_builderv2/artifacts` path and should be located in the private volume.

Can be closed.
