### ISSUE TITLE
Let Named Disposables be based on Templates directly

### ISSUE THREAD

**Issue by deeplow** [QubesOS/qubes-issues#9266]
### The problem you're addressing (if any)
If we want disposable which does not differ from the template, we currently have to create an intermediate `app qube` (e.g. `some-qube-dvm`), which feels unnecessary and overly complex.

**Note**: I feel like this discussion must have already happened somewhere, but I couldn't find anything on it. 

### The solution you'd like
Allowing templates to also be disposable qube templates, inheriting the root file system from the template but having a new and volatile `/rw` (as expected).

### The value to a user, and who that user might be
- **General**: not needing extra qubes which suite no purpose.
- **specific to my situation** (for context): I am populating some disposables on boot via qubes services. However I don't want these services on the `-dvm` parents because otherwise they would contaminate the disposables. So the `-dvm` app qubes end up playing an awkward role in the system of existing, but not serving any purpose and actually potentially leading to issues if anyone plays around with them.

### Completion criteria checklist

(This section is for developer use only. Please do not modify it.)

**Comment by marmarek** [comment]
This is a bit more complicated than this. Disk inheritance is a property of the qube type. Disposable qube inherits private (/rw) disk from its template (the app qube being disposable template). Having disposable qube seeing private disk of the template (the actual template, not disposable template) is undesirable. Additionally, having private disk of disposable qube starting completely clean means mkfs etc at each disposable startup, which adds a few seconds to every disposable startup.

The first problem is likely solvable (but then the disk inheritance rules will be even harder to understand...). But the second problem will remain. Generally we'd like to make disposable startup faster, not slower...

**Comment by rustybird** [comment]
> having private disk of disposable qube starting completely clean means mkfs etc at each disposable startup, which adds a few seconds to every disposable startup.

A few seconds is what I would have guessed too, but it's about an order of magnitude less on my system:

    $ qvm-create -t fedora-40-xfce --prop template_for_dispvms=True -l red benchmark-dvm
    $ qvm-run -p --dispvm benchmark-dvm 'systemd-analyze blame | grep qubes-mount-dirs'
     405ms qubes-mount-dirs.service

And that's not just for initialization of the private volume. It includes time spent on mounting.

Also, it might be a little bit faster on the storage driver side (before VM startup) to create an empty volume than to snapshot an existing one.

**Comment by alimirjamali** [comment]
### The value to a user, and who that user might be
This would allow easy development of tools similar to dnf-automatic or Apt Unattended timers to run `upgrades-status-notify` in DispVMs based on  templates in background via timers. No more `Maybe` in Qubes Updater GUI. No more stale update status for less used templates. No more depending on update-check service in AppVMs.

Creating dedicated Disposable private volumes for all templates at the time of installation (or 1st DispVM run) should be possible. Storage is cheap and private volumes are mostly sparse storage with a skeleton.
