### ISSUE TITLE
Zenity takes too long to launch (aborts on Fedora Minimal) due to GTK trying EGL

### ISSUE THREAD

**Issue by ben-grande** [QubesOS/qubes-issues#9268]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

R4.2, Fedora 39.

### Brief summary

Fedora 39 zenity takes too long to launch, it tests for hardware accelaration that are not present.

Ideally, these applications should be patched or an environment variable should be set to skip trying hardware acceleration when it is not available.

References:

- https://github.com/QubesOS/qubes-issues/issues/8115
- https://github.com/QubesOS/qubes-issues/issues/7921

### Steps to reproduce

- On Fedora Minimal with zenity installed:
```sh
$ time zenity --question --title "title" --text "text" --timeout 1
libEGL warning: DRI2: failed to authenticate
MESA: error: ZINK: failed to choose pdev
libEGL warning: egl: failed to create dri2 screen
MESA: error: ZINK: failed to choose pdev
glx: failed to create drisw screen
failed to load driver: zink

real    0m4.298s
user    0m0.515s
sys     0m0.266s
```

- On Debian Minimal with zenity installed:
```
$ time zenity --question --title "title" --text "text" --timeout 1

(zenity:1089022): Gdk-CRITICAL **: gdk_atom_intern: assertion 'atom_name != NULL' failed

(zenity:1089022): Gdk-CRITICAL **: gdk_atom_intern: assertion 'atom_name != NULL' failed

(zenity:1089022): dbind-WARNING **: AT-SPI: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files

real    0m1.873s
user    0m0.086s
sys     0m0.020s
```

- Timeout = 1
- Realtime = real - timeout
- Fedora real time: `3.298s`
- Debian real time: `0.873s`

### Expected behavior

GTK apps do not try hardware acceleration.

### Actual behavior

GTK apps keeps trying hardware acceleration, taking much longer to launch applications.

**Comment by DemiMarie** [comment]
There are a couple of options here:

1. Force GTK to use the deprecated Cairo renderer (`GSK_RENDERER=cairo`).  This is not supported and is known to mis-renderer certain applications.  It is also likely to go away in GTK5.
2. Force Mesa to use llvmpipe.

**Comment by ben-grande** [comment]
Thanks Demi!

I did not find how to force mesa to use llvmpipe, but I found [LIBGL_ALWAYS_SOFTWARE](https://docs.mesa3d.org/envvars.html#envvar-LIBGL_ALWAYS_SOFTWARE):

```sh
$ export LIBGL_ALWAYS_SOFTWARE=0; time zenity --question --title "title" --text "text" --timeout 1
libEGL warning: DRI2: failed to authenticate
MESA: error: ZINK: failed to choose pdev
libEGL warning: egl: failed to create dri2 screen
MESA: error: ZINK: failed to choose pdev
glx: failed to create drisw screen
failed to load driver: zink

real    0m5.136s
user    0m0.474s
sys     0m0.250s
```
```sh
$ export LIBGL_ALWAYS_SOFTWARE=1; time zenity --question --title "title" --text "text" --timeout 1

real    0m3.611s
user    0m0.344s
sys     0m0.219s
```

If you set it to true, it "uses" software rendering but does not try to detect it apparently. There is also [RUSTICL_ENABLE](https://docs.mesa3d.org/envvars.html#envvar-RUSTICL_ENABLE) and [GALLIUM_DRIVER](https://docs.mesa3d.org/envvars.html#envvar-GALLIUM_DRIVER) that has the option `llvmpipe`, but I did not get results that matter.

**Comment by ben-grande** [comment]
My Fedora qube stopped split-gpg2 from working due to a recent upgrade in zenity.

As the `split-gpg2` package calls zenity, it breaks when zenity breaks. Can the priority be bumped?

```sh
$ dnf list installed zenity
Installed Packages
zenity.x86_64                        4.0.1-2.fc40                        @fedora
$ zenity --question --title title --text text
libEGL warning: DRI2: failed to authenticate
MESA: error: ZINK: failed to choose pdev
libEGL warning: egl: failed to create dri2 screen
Couldn't open libGLESv2.so.2: libGLESv2.so.2: cannot open shared object file: No such file or directory
Aborted (core dumped)
```

Using what Demi recommended above (`GSK_RENDERER=cairo`) works to render the dialog:
```sh
$ env GSK_RENDERER=cairo zenity --question --title title --text text
libEGL warning: DRI2: failed to authenticate
MESA: error: ZINK: failed to choose pdev
libEGL warning: egl: failed to create dri2 screen
```

But it is still checks for graphics acceleration which can make the dialog slow:
```
$ time env GSK_RENDERER=cairo LIBGL_ALWAYS_SOFTWARE=1 zenity --question --title title --text text  --timeout 1

real    0m2.256s
user    0m0.238s
sys     0m0.070s
$ time env GSK_RENDERER=cairo zenity --question --title title --text text  --timeout 1
libEGL warning: DRI2: failed to authenticate
MESA: error: ZINK: failed to choose pdev
libEGL warning: egl: failed to create dri2 screen

real    0m2.778s
user    0m0.363s
sys     0m0.144s
```

**Comment by ben-grande** [comment]
Oh, and it is not possible to switch to a Debian qube as the split-gpg2 server because them it breaks when Fedora is the client. A gpg2 client cannot be newer than the gpg-agent server, it breaks. The client emits a warning, but it should be an error, anyway, this is a GPG bug just to explain why it can't be a Debian gpg server.

**Comment by ben-grande** [comment]
Modifying [splitgpg2/__init__.py](https://github.com/QubesOS/qubes-app-linux-split-gpg2/blob/f121711039c8ba0c9dd54b4bf1a7b09d9c741912/splitgpg2/__init__.py#L607) to use:
```python3
        if subprocess.call(['env', 'GSK_RENDERER=cairo', 'zenity', '--question', '--title', short_msg,
                            '--text', question, '--timeout', '30']) != 0:
```

works in the meantime, but as per [Demi's comment](https://github.com/QubesOS/qubes-issues/issues/9268#issuecomment-2138435274), it is not future-proof.

**Comment by DemiMarie** [comment]
@ben-grande can you report this to Fedora?  That looks like a missing dependency, which indicates a packaging bug.

In the future, I think we should move away from Zenity and towards XDG notifications.

**Comment by ben-grande** [comment]
> In the future, I think we should move away from Zenity and towards XDG notifications.

Zenity is used on Qubes many times as an interactive dialog rather than a notification that can be dismissed. Although XDG notifications supports specific actions, they are still notifications, not dialogs.

@DemiMarie Does it make sense to add to the file [qubes-gui-agent-linux/appvm-scripts/etc/profile.d/qubes-gui.sh](https://github.com/QubesOS/qubes-gui-agent-linux/blob/main/appvm-scripts/etc/profile.d/qubes-gui.sh) the following:
```sh
export GSK_RENDERER=cairo LIBGL_ALWAYS_SOFTWARE=1
```

**Comment by zpc0** [comment]
> True, my template is based on Fedora minimal and doesn't have `libglvnd-gles` installed. The Full Fedora has it installed, but nothing ever requires, recommends or suggests it:
> 
> ```shell
> [user@disp3784 ~]$ rpm -q --whatrequires libglvnd-gles
> no package requires libglvnd-gles
> [user@disp3784 ~]$ rpm -q --whatprovides libglvnd-gles
> libglvnd-gles-1.7.0-4.fc40.x86_64
> [user@disp3784 ~]$ rpm -q --whatrecommends libglvnd-gles
> no package recommends libglvnd-gles
> [user@disp3784 ~]$ rpm -q --whatsuggests libglvnd-gles
> no package suggests libglvnd-gles
> ```

```
[user@disp ~]$ rpm -q --whatrequires libGLES
webkit2gtk4.1-2.44.2-2.fc40.x86_64
```

It seems some package specs use outdated package names `libGLES` `mesa-libGLES` etc...

**Comment by ben-grande** [comment]
@zpc0 I suggest creating an issue on Fedora Bugzilla to fix this second packaging bug. Maybe link to the [issue I opened](https://bugzilla.redhat.com/show_bug.cgi?id=2292635).

**Comment by zpc0** [comment]
> @zpc0 I suggest creating an issue on Fedora Bugzilla to fix this second packaging bug. Maybe link to the [issue I opened](https://bugzilla.redhat.com/show_bug.cgi?id=2292635).

Thank you for suggestion.
I'm currently searching the root cause of this issue, because both zenity and gnome-console are broken. So I suspect that this is not only zenity packaging problem.

I found that downgrading `mesa-libEGL` fixes the problem...
