### ISSUE TITLE
jammy-minimal installation results in "symlink not found for multi-part image" error

### ISSUE THREAD

**Issue by GammaSQ** [QubesOS/qubes-issues#9269]
### Qubes OS release
4.2

### Brief summary

Installing a self-built jammy-minimal template results in an error message suggesting to update qvm-template, but its already up to date.

### Steps to reproduce

I had a previous issue with building this template and it's possible I made some mistakes: https://github.com/QubesOS/qubes-issues/issues/9264

After the build finished, I copied the rpm to dom0 and executed `qvm-template --nogpgcheck  jammy-minimal-4.2.0-202405261844.noarch.rpm`

### Expected behavior

template installed

### Actual behavior

```
$ qvm-template install jammy-minimal-4.2.0-202405261844.noarch.rpm --nogpgcheck
Installing template 'jammy-minimal'...
jammy-minimal: Importing data
Traceback (most recent call last):
  File "/usr/bin/qvm-template-postprocess", line 5, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.11/site-packages/qubesadmin/tools/qvm_template_postprocess.py", line 449, in main
    loop.run_until_complete(post_install(args))
  File "/usr/lib64/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/qubesadmin/tools/qvm_template_postprocess.py", line 314, in post_install
    import_root_img(vm, args.dir)
  File "/usr/lib/python3.11/site-packages/qubesadmin/tools/qvm_template_postprocess.py", line 102, in import_root_img
    raise qubesadmin.exc.QubesException(
qubesadmin.exc.QubesException: template.rpm symlink not found for multi-part image, using up-to-date `qvm-template install ...` should help
ERROR: Command '['qvm-template-postprocess', '--really', '--no-installed-by-rpm', 'post-install', 'jammy-minimal', '/var/tmp/tmp153elua3/var/lib/qubes/vm-templates/jammy-minimal']' returned non-zero exit status 1.
```

In theory, the rpm should be signed, but I couldn't figure out how to produce a keyring `qvm-template` would accept. `qvm-template` is provided by `qubes-core-admin-client-4.2.13-1.fc37`, provided from normal release repository.

**Comment by marmarek** [comment]
Duplidate of https://github.com/QubesOS/qubes-issues/issues/9246
