### ISSUE TITLE
Building standard jammy template misses `qubes-vm-recommended` during build stage

### ISSUE THREAD

**Issue by GammaSQ** [QubesOS/qubes-issues#9270]
### Qubes OS release

4.2

### Brief summary

Building `jammy` or `jammy-standard` using `qubes-builderv2` fails, apparently, due to inability to install `qubes-vm-recommended`.

### Steps to reproduce

Follow `qubes-builderv2` instructions for docker based build environment. Copy `example-configs/ubuntu.yml` to `builder.yml`, edit and add all maintainer-keys (why?), details here: https://github.com/QubesOS/qubes-issues/issues/9264 (just keep `jammy-standard` instead of `jammy-minimal` in the `builder.yml` config)

### Expected behavior

`./qb template fetch prep build` produces an `.rpm`

### Actual behavior

Fails during the `build`stage while trying to install some packages:

Same issue with building `jammy` (with gnome)

Original error, as far as I can tell:
```
10:12:47,049 [executor:docker:b1f442ef72a6] output: + /usr/sbin/chroot /builder/mnt apt-get -o Dpkg::Options::=--force-confnew --yes -o Acquire::Retries=3 -o Dpkg::Options::=--force-unsafe-io --download-only install qubes-vm-dependencies qubes-vm-recommended
10:12:47,078 [executor:docker:b1f442ef72a6] output: Reading package lists...
10:12:47,312 [executor:docker:b1f442ef72a6] output: Building dependency tree...
10:12:47,313 [executor:docker:b1f442ef72a6] output: Reading state information...
10:12:47,415 [executor:docker:b1f442ef72a6] output: Some packages could not be installed. This may mean that you have
10:12:47,415 [executor:docker:b1f442ef72a6] output: requested an impossible situation or if you are using the unstable
10:12:47,415 [executor:docker:b1f442ef72a6] output: distribution that some required packages have not yet been created
10:12:47,415 [executor:docker:b1f442ef72a6] output: or been moved out of Incoming.
10:12:47,415 [executor:docker:b1f442ef72a6] output: The following information may help to resolve the situation:
10:12:47,415 [executor:docker:b1f442ef72a6] output: 
10:12:47,415 [executor:docker:b1f442ef72a6] output: The following packages have unmet dependencies:
10:12:47,532 [executor:docker:b1f442ef72a6] output:  qubes-vm-recommended : Depends: qubes-core-agent-dom0-updates but it is not going to be installed
10:12:47,533 [executor:docker:b1f442ef72a6] output:                         Depends: qubes-mgmt-salt-vm-connector but it is not installable
10:12:47,533 [executor:docker:b1f442ef72a6] output:                         Depends: fwupd-qubes-vm but it is not installable
10:12:47,536 [executor:docker:b1f442ef72a6] output: E: Unable to correct problems, you have held broken packages.
```

Building `jammy-minimal`, which presumably doesn't require `qubes-vm-recommended`, builds just fine. It's unlikely to be related, but `jammy-minimal` still fails to install: https://github.com/QubesOS/qubes-issues/issues/9269

**Comment by marmarek** [comment]
Thanks for the report, see if the linked PR fixes it for you.

**Comment by GammaSQ** [comment]
There seems to be another dependency issue during `./qb package prep`:

```
13:38:57,135 [executor:docker:6360445fccc9] output: Traceback (most recent call last):
13:38:57,135 [executor:docker:6360445fccc9] output:   File "/builder/plugins/source/salt/yaml-dumper", line 32, in <module>
13:38:57,136 [executor:docker:6360445fccc9] output:     import yaml
13:38:57,136 [executor:docker:6360445fccc9] output: ModuleNotFoundError: No module named 'yaml'
```
The host machine has `python3-yaml` installed and I can import `yaml` in a `python` prompt.

I've run a fresh dependency install and executed the test.

**Comment by marmarek** [comment]
Looks to be missing in debian dockerfile, I've pushed a fix to the same PR (requires rebuilding docker)

**Comment by GammaSQ** [comment]
Fixed it, thx! Hope it gets merged soon.
