### ISSUE TITLE
Qubesbuilder2 - cannot build arch packages using qubes executor

### ISSUE THREAD

**Issue by unman** [QubesOS/qubes-issues#9277]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
4.2

### Brief summary
Using Qubes executor, packages for arch cannot be built.

### Steps to reproduce
1. git clone qubes-builderv2
2. cd  qubes-builderv2
3. cp example-configs/archlinux.yml builder.yml
4. Edit builder.yml to remove cache section
5. Change executor to qubes, dispvm
6. ./qb package fetch prep build

### Expected behavior
Packages will be built

### Actual behavior
Fetch and Prep succeed as expected.
Build fails with this error:
```
[executor:qubes:disp7927] Executing '/usr/bin/qvm-run-vm -- disp7927 env -- VERBOSE=1 DEBUG=1 BACKEND_VMM=xen DIST=archlinux PACKAGE_SET=vm bash -c 'sudo cp /builder/plugins/chroot_archlinux/conf/makepkg-x86_64.conf /usr/local/share/devtools/makepkg.conf.d/qubes-x86_64.conf && sudo /builder/plugins/chroot_archlinux/scripts/generate-pacman /builder/plugins/chroot_archlinux/conf/pacman.conf.j2 /usr/local/share/devtools/pacman.conf.d/qubes-x86_64.conf && sudo rm -rf /etc/pacman.d/gnupg/private-keys-v1.d && sudo pacman-key --init && sudo pacman-key --populate && sudo mkdir -p /builder/cache/qubes-x86_64 && sudo mkarchroot -C /usr/local/share/devtools/pacman.conf.d/qubes-x86_64.conf -M /builder/plugins/chroot_archlinux/conf/makepkg-x86_64.conf /builder/cache/qubes-x86_64/root base-devel && sudo /builder/plugins/chroot_archlinux/scripts/generate-pacman /builder/plugins/chroot_archlinux/conf/pacman.conf.j2 /usr/local/share/devtools/pacman.conf.d/qubes-x86_64.conf --enable-builder-local && sudo /builder/plugins/build_archlinux/scripts/update-local-repo.sh /builder/cache/qubes-x86_64/root /builder/repository && mv /builder/distfiles/vmm-xen/xen-4.17.4.tar.gz /builder/vmm-xen && mv /builder/distfiles/vmm-xen/xen-4.17.4.tar.gz.sig /builder/vmm-xen && cd /builder/vmm-xen && sudo qubes-x86_64-build -r /builder/cache --  -d /builder/repository:/builder/repository --  --syncdeps --noconfirm --skipinteg''.
13:56:23,630 [executor:qubes:disp7927] output: /usr/bin/cp: cannot create regular file '/usr/local/share/devtools/makepkg.conf.d/qubes-x86_64.conf': No such file or directory
```

I think this is not the same as #9193, as there OP says "I indeed didn't created manually the file "qubes-x86_64-build" in the dispvm", and they seemed to be able to get further in the build process.
It seems that this is an undocumented requirement that is not performed automatically.
Incidentally, what executor is used when building the arch packages?

**Comment by fepitre** [comment]
This is a duplicate. See https://github.com/QubesOS/qubes-issues/issues/9193#issuecomment-2097915406. It is required to setup ArchLinux tools. This is merely a problem of documentation here. Qubes executor is used to build ArchLinux packages.
