### ISSUE TITLE
Some error during install results in no Qubes/VMs starting when type is HVM

### ISSUE THREAD

**Issue by docelic** [QubesOS/qubes-issues#9281]
(The issue is *not* related to Intel 13th gen; but text is preserved just for reference.
The issue ended up being something wrong during install; a reinstallation helped.)

### Qubes OS release

4.2.1

### Brief summary

After clean installation of Qubes 4.2.1 on Intel i9 13th gen, HVM qubes (including `sys-net`) fail to start with:

```
libxl: libxl_dm.c:2857:stubdom_xswait_cb: Domain 15:Stubdom 16 for 15 startup: startup timed out
libxl: libxl_create.c:1975:domcreate_devmodel_started: Domain 15:device model did not start: -9
```

This must be related to software because I did have some earlier version of Qubes running fine on this same machine as well as on Intel NUC 13th gen.

It happens on HVM-type qubes; other work fine. Also it is not related to PCI; for test I removed all assigned devices from a HVM qube before attempting to start it.

An error similar/identical to this has already been reported in https://github.com/QubesOS/qubes-issues/issues/9150, but according to authoritative comment on it, that bug was related to (old) AMD processors and is not related to Intel.

### Steps to reproduce

1. Install Qubes 4.2.1 on 13th gen Intel i9-13980HX (possibly others). (Issue #9150 also mentions Intel NUC 13th gen)
2. Install will succeed and machine will reboot to finish installing templates etc.
3. The error about `sys-net` qube will show up
4. Same error happens on automatic start as well as on manual attempts

### Expected behavior

1. `sys-net` and any other HVM qubes to start normally
2. Other qubes depending on them to start normally

### Actual behavior

1. HVM qubes cannot start
2. Dependent qubes cannot start

### Other info

Seems at least partially related problem was also reported in https://forum.qubes-os.org/t/no-qubes-vms-boot-after-latest-updates/26033

Thanks.

**Comment by docelic** [comment]
Possibly expected, but mentioning just for reference, the recipe mentioned in #9150, which was one of those lines:
```
GRUB_CMDLINE_XEN_DEFAULT="$GRUB_CMDLINE_XEN_DEFAULT spec-ctrl=ibpb-entry=no-pv"
GRUB_CMDLINE_XEN_DEFAULT="$GRUB_CMDLINE_XEN_DEFAULT spec-ctrl=ibpb-entry=no-hvm"
```
Does not make a difference in this case.

**Comment by marmarek** [comment]
> GRUB_CMDLINE_XEN_DEFAULT="$GRUB_CMDLINE_XEN_DEFAULT spec-ctrl=ibpb-entry=no-pv"
> GRUB_CMDLINE_XEN_DEFAULT="$GRUB_CMDLINE_XEN_DEFAULT spec-ctrl=ibpb-entry=no-hvm"

Don't do this, it has severe security consequences. Just in case, I've added even bolder warning on top of the other issue...

**Comment by docelic** [comment]
> > GRUB_CMDLINE_XEN_DEFAULT="$GRUB_CMDLINE_XEN_DEFAULT spec-ctrl=ibpb-entry=no-pv"
> > GRUB_CMDLINE_XEN_DEFAULT="$GRUB_CMDLINE_XEN_DEFAULT spec-ctrl=ibpb-entry=no-hvm"
> 
> Don't do this, it has severe security consequences. Just in case, I've added even bolder warning on top of the other issue...

Yes, this was to test as much as I could about the issue.

**Comment by docelic** [comment]
> See what you have in /var/log/xen/console/guest-sys-net-dm.log after failed startup.

1. It reaches up to running `qemu -sandbox ...`

2. Then it displays messages:

```
qemu: -chardev socket,server,nowait,path=/tmp/qemu.qmp,id=m2: short-form boolean option 'server' deprecated
Please use server=on instead
qemu: -chardev socket,server,nowait,path=/tmp/qemu.qmp,id=m2: short-form boolean option 'nowait' deprecated
Please use wait=off instead
qemu: -append only allowed with -kernel option
```

3. Then it enters the loop testing for `[ ! -e /tmp/qemu.qmp ]; sleep 0.1`

4. And near the end (at 30 seconds timeout) it prints:
```
pcifront pci-0: Rescanning PCI Frontend Bus 0000:00
pcifront pci-0: Rescanning PCI Frontend Bus 0000:00
```

**Comment by docelic** [comment]
On another attempt it printed more information after "Rescanning ...":

```
pci_bus 0000:00: busn_res: [bus 00-ff] is released
--------[ cut here ]--------
sysfs group 'power' not found for kobject '0000:00'
WARNING: CPU: 0 PID: 10 at ...
CPU: 0 PID: 10 Comm: xenwatch Tainted: G        T 5.10.200-xen-stubdom #1
<followed by contents of registers>
```

**Comment by docelic** [comment]
Messages about the PCI bus seem to appear only if there are PCI devices assigned to the qube.
But the behavior is the same whether there are PCI devices or not -- it fails to start and reaches the timeout.

**Comment by marmarek** [comment]
> qemu: -append only allowed with -kernel option

This is the problem. Something got wrong with the qube's kernel - which one you have set to sys-net? What happens if you change it in qube settings?

**Comment by docelic** [comment]
A potentially interesting observation which I identified just now is that, if I take this disk to another machine (a 6th gen Intel), it fails with the same errors.

The only specific of this new installation that I can think of is that it is installed on an USB disk (so `sys-usb` wasn't separated).

So the issue is either related to USB disk, or something got installed/setup incorrectly during the installation itself?

I will follow up on your question about the kernel shortly.

**Comment by docelic** [comment]
I tried changing `sys-net` template to Fedora or Debian and the error was the same.

Kernel selected was "default (6.6.21-1.fc37)". The other options were/are:

1. 6.6.21-1.fc37
2. (provided by qube)

If I choose the first one, behavior is the same.
If I choose the second one, I the qube starts and shows a `grub>` prompt.

**Comment by docelic** [comment]
I think I see the issue -- during installation I chose Debian to be the default template.
And the `sys-net` qube was indeed created (automatically by Qubes, based on my choice) using the Debian template.
But looking in the direction you pointed at, the kernel seems to have been left at "6.6.21-1.fc37".
Changing the template to Fedora didn't help for some reason (even though the kernel should have been found?).
But changing the template back to Debian and choosing kernel "(provided by qube)" did work.

**Comment by docelic** [comment]
Hm, with `sys-net` running and connected to the network I tried to create a test qube to test the outbound connection.
The qube was created as PVH based on (default) Debian template.
But the kernel was again "6.6.21-1.fc37" which made it fail to start.
And if I changed it to kernel "(provided by qube)" it said: `virt_mode PVH require kernel to be set`.

**Comment by docelic** [comment]
But interestingly `sys-firewall` does start after `sys-net` even though it has kernel set to "default (6.6.21-1.fc37)" and template "default-dvm" (which in turn uses template "debian-12-xfce").

**Comment by marmarek** [comment]
Kernel version with "fc" in name is okay for Debian qubes too. I think the issue you observe is that something went wrong when it was installed and some file is missing. Since you got a configuration where network works, try installing updates - it will pull in 6.6.29. Version itself probably doesn't matter, but maybe its installation will not be missing anything.

As for other your points:


> With Fedora and kernel "(provided by qube)" it showed the `grub> ` prompt as mentioned above

This is not expected, the option should also work - but it's another issue.

> And when I changed it to kernel "(provided by qube)" it said: `virt_mode PVH require kernel to be set`.

This is expected (in the current version) - the "provided by qube" option isn't compatible (yet) with PVH.

**Comment by docelic** [comment]
I reinstalled and things seem to be working as expected.
Strange. Thanks & apologies for using your time for this.
