### ISSUE TITLE
Missing r4.2 Archlinux packages

### ISSUE THREAD

**Issue by drGrove** [QubesOS/qubes-issues#9287]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
4.2.1

### Brief summary
QubesOS r4.2 Archlinux repo is missing multiple releases
[Arch Repo](https://archlinux.qubes-os.org/r4.2/current/vm/archlinux/pkgs/)

[qubes-vm-core-4.2.29-1](https://archlinux.qubes-os.org/r4.2/current/vm/archlinux/pkgs/qubes-vm-core-4.2.29-1-x86_64.pkg.tar.zst)
[Latest version v4.2.33](https://github.com/QubesOS/qubes-core-agent-linux/releases/tag/v4.2.33)

### Steps to reproduce
1. Install Archlinux Template from Community Repo using GUI
2. Start template
3. Run `pacman -Ss qubes-vm-core`

### Expected behavior
Shows qubes-vm-core 4.2.29-1 as latest and installed

### Actual behavior
Should show 4.2.33-1

**Comment by marmarek** [comment]
4.2.33 is (intentionally) still in testing repository (see https://github.com/QubesOS/updates-status/issues/4687), so it's expected to not show up in the stable one.

**Comment by marmarek** [comment]
If you want to help, enable testing repository install it, use for a bit and leave feedback in a linked issue (simple reactions like :+1: or :-1:  are appreciated, but in case of problems, a proper issue would be helpful too)
