### ISSUE TITLE
Absolute coordinates are not working for deskhop (or device not registered as touchscreen)

### ISSUE THREAD

**Issue by techge** [QubesOS/qubes-issues#9292]
### Qubes OS release

R4.2

### Brief summary

I'd like to use [deskhop](https://github.com/hrvach/deskhop), a device to use only one pair of keyboard and mouse for two systems without switching (keeping the hid registered on both systems simultaneously, but only sending commands to one at a time). The keyboard part is working fine, the mouse buttons and wheel are working fine. But the mouse movements are not.

I already figured that it is probably related to the deskhop is using absolute coordinates for mouse movements instead of relative movements (see [this discussion](https://github.com/hrvach/deskhop/issues/98) as well). As [support for touchscreens](https://github.com/QubesOS/qubes-issues/issues/2281) exists in qubes and as those use absolute coordinates as well, I guess the problem is that qubes is not aware that a device that registered as a mouse is using absolute coordinates as well.

I already set the qubes-rpc policy to ask for touchscreen devices, but I was never asked. This is why I think qubes is not aware, that there is a touchscreen like device.

How could this issue be addressed to let deskhop working in qubes? I'd be fine with changing the way deskhop works, if necessary. But ideally it would work out-of-the-box, of course.

**Comment by techge** [comment]
By adding `--tablet` to `/etc/qubes-rpc/qubes.InputMouse` I got it working. So the issue is really only the fact that deskhop uses technology usually seen in tablets/touchscreens, but registering as a mouse. On the bright side: the needed functionality is luckily implemented in qubes.

As I guess that qubes is not changing this behaviour out of security considerations, I am going to see, how I can get it working by changing the firmware of deshkop instead.

**Comment by marmarek** [comment]
A better approach is to add udev rule in sys-usb (?) that classify this device as a touchscreen. See https://github.com/QubesOS/qubes-app-linux-input-proxy/blob/main/qubes-rpc/qubes-input-trigger#L39-L42 for list of considered variables.

**Comment by marmarek** [comment]
something like this:
```
ACTION!="remove", ENV{ID_VENDOR}=="xxxx", ENV{ID_MODEL}=="xxxx", ENV{ID_INPUT_MOUSE}=="1" ENV{ID_INPUT_TABLET}="1"
```
(fill in vendor and model)

**Comment by techge** [comment]
Thanks a lot, good idea!

For future reference (if anybody finds this), I needed to adapt the example above:

```
$ sudo cat /etc/udev/rules.d/10-deskhop.rules
ACTION!="remove", ENV{ID_VENDOR_ID}=="xxxx", ENV{ID_MODEL_ID}=="xxxx", ENV{ID_INPUT_MOUSE}=="1", ENV{ID_INPUT_TABLET}="1"
```
But honestly, I needed to try around a lot, maybe I did something wrong at the beginning. The differences are little, beside a colon and `_ID` added to vendor and model id :shrug:
