### ISSUE TITLE
qubes.UpdatesProxy fails with "Refusing to execute executable service" error

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#9299]
_Originally posted by @tvondra in https://github.com/QubesOS/qubes-issues/issues/9151#issuecomment-2163584199:_

I think I ran into this issue today, after switching sys-net from fedora-38-xfce to fedora-39-xfce. Updating any template fails with this:

```
Updating fedora-39-xfce
Install requirements
Refreshing package info
Errors during downloading metadata for repository 'fedora':
  - Curl error (56): Failure when receiving data from the peer for https://mirrors.fedoraproject.org/metalink?repo=fedora-39&arch=x86_64 [Proxy CONNECT aborted]
Failed to download metadata for repo 'fedora': Cannot prepare internal mirrorlist: Curl error (56): Failure when receiving data from the peer for https://mirrors.fedoraproject.org/metalink?repo=fedora-39&arch=x86_64 [Proxy CONNECT aborted]
``` 

and restarting the sys-net VM, or the qubes-updates-proxy did not help at all.

journalctl on sys-net however shows this, which I did not see mentioned here:

```
Jun 12 19:18:29 sys-net qrexec-agent[1085]: 2024-06-12 19:18:29.792 qrexec-agent[1085]: qrexec-agent-data.c:242:handle_new_process_common: failed to spawn process
Jun 12 19:18:29 sys-net qrexec-agent[1085]: 2024-06-12 19:18:29.792 qrexec-agent[1085]: exec.c:751:find_qrexec_service: Refusing to execute executable service /etc/qubes-rpc/qubes.UpdatesPr>
Jun 12 19:18:29 sys-net qrexec-agent[1083]: 2024-06-12 19:18:29.673 qrexec-agent[1083]: qrexec-agent-data.c:242:handle_new_process_common: failed to spawn process
Jun 12 19:18:29 sys-net qrexec-agent[1083]: 2024-06-12 19:18:29.673 qrexec-agent[1083]: exec.c:751:find_qrexec_service: Refusing to execute executable service /etc/qubes-rpc/qubes.UpdatesPr>
Jun 12 19:18:29 sys-net qrexec-agent[1081]: 2024-06-12 19:18:29.537 qrexec-agent[1081]: qrexec-agent-data.c:242:handle_new_process_common: failed to spawn process
Jun 12 19:18:29 sys-net qrexec-agent[1081]: 2024-06-12 19:18:29.537 qrexec-agent[1081]: exec.c:751:find_qrexec_service: Refusing to execute executable service /etc/qubes-rpc/qubes.UpdatesPr>
```
The timestamps match the attempted template update. I have not found the reason for this, but switching sys-net to fedora-40-xfce resolved the issue for me for now.

**Comment by marmarek** [comment]
Can you check what you have in `/etc/qubes-rpc/qubes.UpdatesProxy` ? It should be a symlink to `/dev/tcp/127.0.0.1/8082`. Maybe you have some modified version and it got created as .rpmnew file or such?

**Comment by tvondra** [comment]
Interesting. In sys-net (running fedora-40-xfce) I see just this:

```
lrwxrwxrwx. 1 root root   23 May  9 02:00 qubes.UpdatesProxy -> /dev/tcp/127.0.0.1/8082
```

but in the fedora-39-xfce template I see this:

```
-rwxr-xr-x. 1 root root   37 Apr 10 22:32 qubes.UpdatesProxy
lrwxrwxrwx. 1 root root   23 May  9 02:00 qubes.UpdatesProxy.rpmnew -> /dev/tcp/127.0.0.1/8082
```

So yeah, there is a .rpmnew, but I really don't recall ever touching these files. But I see the `qubes.UpdatesProxy` contains this:

```
exec socat STDIO TCP4:127.0.0.1:8082
```

Could this be due to the fix to force IPv4?

**Comment by marmarek** [comment]
Very likely. Move `qubes.UpdatesProxy.rpmnew` over to `qubes.UpdatesProxy`.

**Comment by tvondra** [comment]
Yes, moving .rpmnew over to the original file fixed this and sys-net became usable with the f39 template for me. I'll keep using the f40 one anyway, I just wanted to test this.

**Comment by alimirjamali** [comment]
> > Could this be due to the fix to force IPv4?
> 
> Very likely.
> 
> Move `qubes.UpdatesProxy.rpmnew` over to `qubes.UpdatesProxy`.

I just realized about the broken qubes.UpdateProxy and checked the templates. All Fedora templates (fedora-39-xfce, fedora-39-minimal, fedora-40-xfce, fedora-40-minimal) had the rpmnew ones and needed manually overwrite the old socat solution with the new symlink. Is it normal?
