### ISSUE TITLE
Allow the gui-daemon background color to be configurable

### ISSUE THREAD

**Issue by Euwiiwueir** [QubesOS/qubes-issues#9304]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### The problem you're addressing (if any)

This is an outgrowth of this forum thread:

https://forum.qubes-os.org/t/suppressing-the-white-flash/26829

I've filed this as an enhancement but it's a mitigation of a usability bug that affects some proportion of users.

**Context:**

When VM window content is not immediately available to dom0's X, but something must be displayed in the dom0 passthrough window for that VM window, the `gui-daemon` falls back to filling this unavailable content with a hardcoded background color.

Examples:
1. A domU window is resized on dom0 and hasn't yet been redrawn by the VM.
2. The user switches to another workspace which triggers redraws of domU windows placed on that workspace and the passthrough windows are displayed before the redrawn domU content is available. (I am supposing here this is the event flow.)

This display of the hardcoded background color is usually quite transient, milliseconds, but is briefly visible to the user.

**Problem:**

The background color is hardcoded to white. If the user is running a dark color theme on their desktop, a window's brief flash of bright white is visually uncomfortable, especially if it happens frequently. Especially especially if the window is large or full-screen.

In my own workflow I switch between workspaces very frequently, which means quite frequent white flashes.

### The solution you'd like

Allow the `gui-daemon` background color to be black instead of white. I patched my `gui-daemon` to use black and for me it's been a complete mitigation of this usability issue. Users who run a bright desktop theme probably would prefer the current white, though. Therefore the background color should probably be configurable.

marmarek outlines the shape of that work [here](https://forum.qubes-os.org/t/suppressing-the-white-flash/26829/10):
> I guess it has to do with “background pixel”:
> 
> https://github.com/QubesOS/qubes-gui-daemon/blob/main/gui-daemon/xside.c#L332
> 
> If somebody wants to play with it, it should be quite easy to change it and see if it helps. For example there is similar `BlackPixel` function. Making it configurable should also be possible, but it’s going to be a bit more work (add config option to gui-daemon, fetch it from the config file there, and then add support for setting this option via features in core-admin-client).
> 

My instinct is that an option of black or white is good enough; allowing the color to be an arbitrary hue perhaps grants this issue more attention than it deserves. Also, the implementation is simpler. But I defer to others.

The majority of the work of the implementation will be the plumbing to propagate the color choice to `gui-daemon/xside.c`.

### The value to a user, and who that user might be

Better usability/comfort for users like me who use dark styling.

### Completion criteria checklist

(This section is for developer use only. Please do not modify it.)

**Comment by Euwiiwueir** [comment]
A couple related issues:

1. https://github.com/QubesOS/qubes-issues/issues/2391

2. https://github.com/QubesOS/qubes-issues/issues/2846

(1) I think is probably the same underlying issue I'm describing, though for me the choice (or absence) of a compositor does not materially help.

(2) Is distinct but similar.

**Comment by Euwiiwueir** [comment]
Lastly, I'm willing to implement this myself if the proposed solution sounds ok.

**Comment by marmarek** [comment]
> Allow the `gui-daemon` background color to be black instead of white.

Sounds good

**Comment by Euwiiwueir** [comment]
PRs submitted.

**Comment by Euwiiwueir** [comment]
Thanks for accepting the patch. I'm really pleased to have this fixed.

**Comment by Euwiiwueir** [comment]
Is it in the cards this patch could make its way to r4.2? I can maintain my own patched 4.2 rpms until 4.3, but I am curious.

**Comment by Atrate** [comment]
I would also gladly see this backported to r4.2, it's especially annoying with gui-emulated standalones.

@Euwiiwueir for the future, once the patch lands, how would a user configure this to be black?

**Comment by Euwiiwueir** [comment]
Should be just this:

```
# Substitute your actual guivm if not dom0
[user@dom0 ~]$ qvm-features dom0 gui-default-window-background-color black
```
Then restart the `qubes-guid` processes for each VM. (Simplest: restart the VMs, or reboot.)
