### ISSUE TITLE
Increase or remove limit on number of block devices per qube (current limit: 26)

### ISSUE THREAD

**Issue by 3hhh** [QubesOS/qubes-issues#9311]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

4.1, 4.2

### Brief summary

Attaching or creating more than 26 block devices to/in a VM fails.

The root cause appears to be a kernel limitation to handle any device higher than `/dev/xvdz`.
It starts with `/dev/xvda` and ends with `/dev/xvdz` resulting in 26 block devices (`/dev/xvda` to `/dev/xvdc` are used by Qubes OS, so 23 remain for the user).

And yes, this tends to happen in practice with lots of loop devices.

### Steps to reproduce

Attach more than 26 block devices to a VM or create loop devices inside a VM (I tested with debian-12 template).

### Expected behavior

Works.

### Actual behavior

Fails.

**Comment by rustybird** [comment]
It's possible to have way more than 26, but the frontend device currently has to be specified manually:

    qvm-block attach -o frontend-dev=xvdabc ...

Without an explicit `frontend-dev` option it doesn't work because Qubes OS tooling only tries to find a free one up until xvdz: https://github.com/QubesOS/qubes-core-admin/blob/v4.3.0/qubes/ext/block.py#L44-L46

Not sure what's the exact limit - xvdzzz is too high and xen-blkfront complains about not being able to fit it into the block device's minor number.

**Comment by rustybird** [comment]
Just making it work without an explicit `frontend-dev` option.

**Comment by alimirjamali** [comment]
> Just making it work without an explicit `frontend-dev` option.

This would add 676 new possibilities but I find this solution ugly:
```
AVAILABLE_FRONTENDS =  AVAILABLE_FRONTENDS + ['xvd'+c+d for c in string.ascii_lowercase for d in string.ascii_lowercase]
```

I emphasize Marek's note:
> `# TODO: get this from libvirt driver?`

@rustybird I have been looking at libvirt's [Python API](https://libvirt-python.readthedocs.io/) and [other documentation](https://libvirt.gitlab.io/libvirt-appdev-guide-python/). I did not manage to find how to query backend Xen (or QEMU) limit of this. Had you any success?

**Comment by rustybird** [comment]
There might not be a limit that can be queried from libvirt (at least not an accurate one), as it will happily attempt to use some already out-of-range names like xvdzzz and even xvdzzzz.

> This would add 676 new possibilities but I find this solution ugly:

I just noticed there's also a another `AVAILABLE_FRONTENDS` definition in `qubes.storage.Storage`: https://github.com/QubesOS/qubes-core-admin/blob/v4.3.0/qubes/storage/__init__.py#L497

**Comment by alimirjamali** [comment]
Just found [this](https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/5/html/virtualization/sect-virtualization-virtualization_limitations-xen_limitations) in the Redhat docs:

> A limit of 254 para-virtualized block devices per host exists. The total number of block devices attached to guests cannot exceed 254. 

Have not found a total limit per all guests.

**Comment by 3hhh** [comment]
I tried to patch the aforementioned two files, but unfortunately attaching block devices still fails at `/dev/xvde`, i.e. `xvde` to `xvdh` are never created.

**Comment by alimirjamali** [comment]
I just tested a patch. I successfully managed to attach 48 block devices from dom0 to a PVH qube. Here is the patch:

<details>
<summary>Initial patch to increase number of block devices per qube</summary>

```diff
diff --git a/qubes/ext/block.py b/qubes/ext/block.py
index 3a3eb1e5..46f80240 100644
--- a/qubes/ext/block.py
+++ b/qubes/ext/block.py
@@ -44,6 +44,7 @@ mode_re = re.compile(r"\A[rw]\Z")
 # TODO: get this from libvirt driver?
 AVAILABLE_FRONTENDS = ['xvd'+c for c in
                        string.ascii_lowercase[8:]+string.ascii_lowercase[:8]]
+AVAILABLE_FRONTENDS += ['xvda'+c for c in string.ascii_lowercase]
 
 SYSTEM_DISKS = ('xvda', 'xvdb', 'xvdc')
 # xvdd is considered system disk only if vm.kernel is set
diff --git a/qubes/storage/__init__.py b/qubes/storage/__init__.py
index b1464ab6..3a8e5494 100644
--- a/qubes/storage/__init__.py
+++ b/qubes/storage/__init__.py
@@ -495,6 +495,7 @@ class Storage:
     '''
 
     AVAILABLE_FRONTENDS = {'xvd' + c for c in string.ascii_lowercase}
+    AVAILABLE_FRONTENDS = AVAILABLE_FRONTENDS.union({'xvda' + c for c in string.ascii_lowercase})
 
     def __init__(self, vm):
         #: Domain for which we manage storage
```
</details>

And here is the script to automate creation of 48 virtual block devices and attaching them to untrusted qube:
<details>
<summary>Block device creation and attaching automation</summary>

```bash
#!/bin/sh

for i in {1..48}
do
[ ! -f block${i}.bin ] && dd if=/dev/zero of=block${i}.bin bs=512 count=10
sudo losetup --show /dev/loop100${i} block${i}.bin
qvm-block --verbose attach untrusted dom0:loop100${i} 
sleep 1
done
```
</details>

I believe that we are on the correct path. We have to increase the number and improve the patch until we break something. Then we could find out the exact number of possible devices. I will continue the work tomorrow.

![block](https://github.com/QubesOS/qubes-issues/assets/5407317/682f4379-8cd1-4aec-8913-a9c365e88233)

**Comment by 3hhh** [comment]
Qubes OS treats `/dev/xvda` to `xvdh` in a special way: Apparently those devices are hidden from tools such as `qvm-block ls`, which caused issues with my test code.
That's likely why they are added to the list of available devices in the end.

Anyway I submitted a PR, which works for me.
Feel free to review or comment on it there @alimirjamali. Thanks for your support!
