### ISSUE TITLE
BuilderV2 should support macros with scripts relative to source dir

### ISSUE THREAD

**Issue by ben-grande** [QubesOS/qubes-issues#9312]
### The problem you're addressing (if any)

I have macros in my RPM spec:
```
%define file_roots     %(./scripts/spec-get.sh @PROJECT@ file_roots)
```

The `./qb package fetch` fails as the scripts in `qubesbuilder/plugins/source_rpm/scripts`, such as `query-spec`, are run from the main git repository instead of the artifact source dir.

### The solution you'd like

Change directory to `source_dir` and change the `spec_file` to be relative to `source_dir`.

### The value to a user, and who that user might be

Developers can use the Qubes Builder V2 with macros that calls scripts in the git repository of the artifact instead of having to hardcode values to the SPEC file.

### Completion criteria checklist

- [ ] RPM spec with macro with scripts with relative paths works from the source directory of the artifact.

**Comment by marmarek** [comment]
> `%define file_roots %(./scripts/spec-get.sh @PROJECT@ file_roots)`

This doesn't look like a valid thing to do in a RPM spec file. RPM macros are expanded before extracting sources, so you can't really assume extracted sources present (even if that could be a case when using builderv2 specifically). If you want to refer to a source file referenced in a spec (via `SourceN:` header), RPM provides a path to them in `%{_sourcedir}`.

**Comment by ben-grande** [comment]
> > `%define file_roots %(./scripts/spec-get.sh @PROJECT@ file_roots)`
> 
> This doesn't look like a valid thing to do in a RPM spec file. RPM macros are expanded before extracting sources, so you can't really assume extracted sources present (even if that could be a case when using builderv2 specifically). If you want to refer to a source file referenced in a spec (via `SourceN:` header), RPM provides a path to them in `%{_sourcedir}`.

I don't use `Source0` for this to be applicable, but anyway, I tried:

If I use:

```spec
%define file_roots %(%{_sourcedir}/scripts/spec-get.sh ansible project)
Name: %{project}
Source0: %{project}-%{version}.tar.gz

%prep
%setup -q
```

I get:
```sh
output: + rpm -q --define 'dist .fc37' --qf '%{name}-%{version}-%{release}\n' --specfile qusal-ansible.spec
output: sh: line 1: /home/user/rpmbuild/SOURCES/scripts/spec-get.sh: No such file or directory
output: error: line 30: Empty tag: Name:
output: error: query of specfile qusal-ansible.spec failed, can't parse
```

I see the default `%{_sourcedir}` of `~/rpmbuild/SOURCES`, because [query-spec](https://github.com/QubesOS/qubes-builderv2/blob/main/qubesbuilder/plugins/source_rpm/scripts/query-spec) is run before sources are unpacked? It doesn't matter that hte path is wrong (missing the project name after SOURCES, it still is using the wrong source directory).

This is why I think `cd`ing to the `artifacts/sources/<project>` is better.

**Comment by marmarek** [comment]
It isn't really a matter what is "better". Spec file can't reference files that are not included in the package. Especially, the build stage takes only src.rpm and needs to build without other auxiliary files. For example `mock --rebuild (srpm)` needs to work. builderv2 should produce and build spec-compliant src.rpm packages, and I refuse to add workarounds for non-spec compliant packages.

The tarball is extracted in `%prep` section, the spec is parsed earlier, before that happens. The only way you can make some extra scripts available to the spec parsing stage is to name them explicitly in some `SourceN` header and then reference via `%{_sourcedir}`. Note the sources dir structure is flat, it puts all the referenced files into a common directory, so it will be `%{_sourcedir}/get-spec.sh` in this case. But also, AFAIK calling auxiliary scripts during spec parse stage is something that rpm upstream discourages...

What might be an builderv2 issue is not setting `_sourcedir` in query-spec script. But still, relying on external scripts for basic package info feels weird at least, if it is valid thing to do at all...

**Comment by ben-grande** [comment]
Thank you for the detailed explanation, I will remove the dynamic generation from my spec file.
