### ISSUE TITLE
Could you upload your PGP key to keys.openpgp.org?

### ISSUE THREAD

**Issue by elvis-hrvat** [QubesOS/qubes-issues#9330]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### The problem you're addressing (if any)
Securely Validate Qubes ISOs

### The solution you'd like

I need QMSK uploaded to keys.openpgp.org

### The value to a user, and who that user might be
QMSK can be obtained by recv-key when keyserver is set to keys.openpgp.org in gpg.conf
Uploading keys to keys.openpgp.org is relatively secure as it verifies the owner of the email address.
It is also chosen as the default key server for Mozilla Thunderbird.

### Completion criteria checklist

(This section is for developer use only. Please do not modify it.)

**Comment by marmarek** [comment]
Those keys are not email-signing keys, and they (intentionally) do not have email address attached. And also since those are not email keys, what Thunderbird does is rather irrelevant... Take a look at https://www.qubes-os.org/security/verifying-signatures/ how to get and verify them.
