### ISSUE TITLE
Qubes Update GUI broken since qubes-core-dom0-linux v4.2.25

### ISSUE THREAD

**Issue by Minimalist73** [QubesOS/qubes-issues#9341]
### Qubes OS release
4.2.2-rc1

### Brief summary
Since the last current-testing update of qubes-core-dom0-linux to v4.2.25 the updater stopped working completely.
When starting the update after selecting a few qubes, the bar goes to 100% without doing anything else and marks all selected qubes to status "In progress" in red.
Downgrading to v4.2.23 makes the updater work again.

### Steps to reproduce
- Update to qubes-core-dom0-linux v4.2.25 from the testing repository
- Open Qubes Update GUI
- Select a few random qubes and start the update

### Expected behavior
GUI Updater start the qubes and do the upgrades for each of them.

### Actual behavior
Goes to 100% instantly and does nothing else. 
No logs in debug is provided.

**Comment by marmarek** [comment]
Looks like a missing dependency, this should only go together with updated GUI (not built for R4.2 yet).
