### ISSUE TITLE
Minimal templates are missing `distro-info-data` package by default

### ISSUE THREAD

**Issue by TNTBOMBOM** [QubesOS/qubes-issues#9343]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

4.2.2-rc1

### Brief summary

The notification is wrong in two ways: 

- The names that the notification mention is for StandaloneVMs, not templates.
- The StandaloneVMs are upgraded to latest stable debian (internal upgrade from debian 11 to 12).

### Steps to reproduce

Create StandaloneVM from an old debian, upgrade it internally. 

### Expected behavior

- Should differentiate between Templates and StandaloneVMs (nomenclature correction).
- Should either understand that the StandaloneVM upgraded already OR ignore it since its a StandaloneVM not a template (because this is wont be a Qubes issue to solve anymore if its outdated).

### Screenshot

![standalonewrong](https://github.com/QubesOS/qubes-issues/assets/11895339/03e47829-a13e-4fab-9462-a00f1b06da19)

**Comment by alimirjamali** [comment]
> * The StandaloneVMs are upgraded to latest stable debian (internal upgrade from debian 11 to 12).

What is the version of `qubes-desktop-linux-manager` on your system (use dnf info to find it)? There was a recent fix in v4.2.24 for that notification. The notification might go away if you restart your system or restart the qui-updates service via this command:
```
systemctl --user restart qubes-widget@qui-updates.service
```

> * The names that the notification mention is for StandaloneVMs, not templates.
That is correct. The text `Install new templates with Template Manager` could be changed to something like _Install new templates with Template Manager_ `or do in-place release upgrade of the outdated qubes`. But I am not in a position to suggest the exact wording of it. It is just a suggestion.

**Comment by TNTBOMBOM** [comment]
> There was a recent fix in v4.2.24 for that notification.

Im already on 4.2.24

> The notification might go away if you restart your system or restart the qui-updates service via this command:

Didnt went away, im pretty sure the scenario im in is not defined by the `qui-updates` tool to know it. I see it either ignoring StandalonVMs or implement sanity to know the internals of the StandaloneVMs packages status.

**Comment by alimirjamali** [comment]
What is the output of this command in the StandaloneVM:
```
grep SUPPORT_END /etc/os-release
```
And output of this command in dom0:
```
qvm-features VMNAME os-eol
```

**Comment by TNTBOMBOM** [comment]
> grep SUPPORT_END /etc/os-release

```
[user ~]% grep SUPPORT_END /etc/os-release
zsh: exit 1     grep --color=auto SUPPORT_END /etc/os-release
[user ~]% cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
[user ~]% 
```

> `qvm-features VMNAME os-eol`

No output.

**Comment by alimirjamali** [comment]
Thanks. Very useful information. Now we know that we are dealing with a standalone which does not provide `SUPPORT_END` data. 

Just to double check, the standalone VM name is not `debian-11`? [These](https://github.com/QubesOS/qubes-desktop-linux-manager/blob/main/qui/eol.json#L16C2-L16C11) are the hard-coded template/standalone VM names which will always show the unsupported popup.

**Comment by TNTBOMBOM** [comment]
> Just to double check, the standalone VM name is not `debian-11`?

Nope its not debian-11.


> [These](https://github.com/QubesOS/qubes-desktop-linux-manager/blob/main/qui/eol.json#L17) are the hard-coded template/standalone VM names which will always show the unsupported popup.

I see, but its not getting the OS reading from `/etc/os-release` within StandaloneVM, somewhere else where debian 11 still mentioned.

**Comment by marmarek** [comment]
> > `qvm-features VMNAME os-eol`
> 
> No output.

Is this template using repositories for R4.2? debian-11 wasn't supported on R4.2, so it's likely a template imported from R4.1 and as such it won't tell the EOL date. If that's the case, the notification about unsupported template is almost accurate, as [R4.1 indeed is EOL already](https://www.qubes-os.org/news/2024/06/18/qubes-os-4-1-has-reached-end-of-life-extended-security-support-continues-until-2024-07-31/)

**Comment by TNTBOMBOM** [comment]
> Yes. What is the output of `qvm-features VMNAME template-name`

debian-11-minimal

> so it's likely a template imported from R4.1

Yep

> the notification about unsupported template is almost accurate

Hmm.. not sure how much accurate it is e.g: 

- Not a template
- Not debian 11 anymore, it has been upgraded to debian 12 (internally)
- Not installed from qubes repository, so there is nothing qubes can do except a within VM upgrade (which is what has been done), meaning the error almost useless if its not talking about upgrading the internals. Unless a suggestion should be like backup the VM data and shift it to a newly created qube/VM based on the latest version of x (can be debian or fedora..etc).

**Comment by alimirjamali** [comment]
> Debian 11 hasn't reached EOL yet anyway.

The EOL for Debian 11 is set to 1st July in the JSON file. This could be changed to 31 August which is its real EOL date. But I guess the change will reach the main stream too late to be available to the end users.


> debian-11-minimal

@TNTBOMBOM could you unset or change that feature? Something like:
```
qvm-features --unset VMNAME template-name
```
or
```
qvm-features --unset VMNAME template-name debian-12-minimal
```
Then restart the updates widget and see if the notification goes away.

**Comment by marmarek** [comment]
> > so it's likely a template imported from R4.1
> 
> Yep

Is it updated to R4.2 repositories? Check `/etc/apt/sources.list.d/qubes-r4.list` - does it have "r4.2" or "r4.1" in URLs?

**Comment by alimirjamali** [comment]
> Is it updated to R4.2 repositories? Check `/etc/apt/sources.list.d/qubes-r4.list` - does it have "r4.2" or "r4.1" in URLs?

The 10-qubes-core-agent-features.sh should set the correct os-eol post upgrade?

**Comment by marmarek** [comment]
> I see. The 10-qubes-core-agent-features.sh should set the correct os-eol post upgrade, using `/usr/share/distro-info/debian.csv` file.

Well, not if the template is still using R4.1 qubes packages...

**Comment by TNTBOMBOM** [comment]
> @TNTBOMBOM could you unset or change that feature? Something like:
> 
> ```
> qvm-features --unset VMNAME template-name
> ```

This trick made it, and notification went away.

> Is it updated to R4.2 repositories? Check `/etc/apt/sources.list.d/qubes-r4.list` - does it have "r4.2" or "r4.1" in URLs?

Yes its r4.2: 

```
user@host:~# cat /etc/apt/sources.list.d/qubes-r4.list
# Main qubes updates repository
deb [arch=amd64 signed-by=/usr/share/keyrings/qubes-archive-keyring-4.2.gpg ] https://deb.qubes-os.org/r4.2/vm bookworm main
```

**Comment by alimirjamali** [comment]
> This trick made it, the notification went away.

Would you please run this:
```
/etc/qubes/post-install.d/10-qubes-core-agent-features.sh
```

Then tell us the output of this command in dom0:
```
qvm-features VMNAME os-eol
```

**Comment by TNTBOMBOM** [comment]
> Then tell us the output of this command in dom0:

No output shown.

**Comment by alimirjamali** [comment]
> No output shown.

Interesting. One last question. What is the version of qubes-core-agent on the standalone VM. You could find it it via:
```
apt info qubes-core-agent
```

**Comment by TNTBOMBOM** [comment]
> ```
> apt info qubes-core-agent
> ```

```
[user ~]%  apt info qubes-core-agent
Package: qubes-core-agent
Version: 4.2.35-1+deb12u1
```

> > `/etc/qubes/post-install.d/10-qubes-core-agent-features.sh`
> 
> This on its own is not enough, there is "commit" action in the last file. Better run the whole `/etc/qubes-rpc/qubes.PostInstall` (either this way from within a qube, or from dom0 via `qvm-run -u root --service QUBE_NAME qubes.PostInstall`).

Done both, no output for 

`qvm-features VMNAME os-eol`

Actually what i have discovered is that this feature doesnt show anything for debian minimal even installed freshly, so this is not an issue of previous debians not showing any output but even new one (only minimal, full/standard does show an output).

So to reproduce is easy: 

- Get debian-minimal
- Check output for eol
- Which part is missing?

**Comment by marmarek** [comment]
> (only minimal, full/standard does show an output).

:facepalm: Even though you said it several times, we missed this part...
The EOL date is retrieved using `distro-info-data` package, and I guess this package is not installed in minimal template...

**Comment by TNTBOMBOM** [comment]
> and I guess this package is not installed in minimal template...

```
user@host:~$ apt policy distro-info-data 
distro-info-data:
  Installed: (none)
  Candidate: 0.58+deb12u2
  Version table:
     0.58+deb12u2 500
        500 https://deb.debian.org/debian bookworm/main amd64 Packages
user@host:~$ 

```

**Comment by smcgu** [comment]
For folks like me that have been performing in-place upgrades for a while, I don't think this package ever gets installed automatically. I had to go through my minimal Debian and Fedora templates to install this package. If I had not found this GitHub issue, I am not sure if I would have figured out how to "fix" my existing templates to silence the unsupported operating system warning.

Also, solely installing the package did not appear to update the template's qvm-features. I had to manually update `os-version` and `os-eol` for each of the templates.

Would it be possible to do one or more of the following:

- Mark the `distro-info-data` package as a dependency of a core qubes package that is installed in minimal templates, such as the `qubes-core-agent`
- Add a step/note to the in-place template upgrade documentation regarding `distro-info-data`
- Enhance the `qubes-core-agent` tool to check for the presence of `distro-info-data` either directly in the template or indirectly through an expected template qube feature value (e.g., distro-info-availabe)

Finally, I want to acknowledge upfront that this is a diminishing "problem" as users perform fresh installs of templates or Qubes OS.

**Comment by smcgu** [comment]
It looks like `distro-info-data` was added as a dependency for `qubes-core-agent` in https://github.com/QubesOS/qubes-core-agent-linux/commit/d5f3304d118481d73ba0acb3523cc52de5f9823a in July. I am not sure why I had to manually install `distro-info-data`, as `apt` and `dnf` should have handled this.
