### ISSUE TITLE
"Boot qubes from CD-ROM" shouldnt show the same qube as an option

### ISSUE THREAD

**Issue by TNTBOMBOM** [QubesOS/qubes-issues#9344]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

4.2.2-rc1

### Steps to reproduce

- Create an empty/not based on a template StandaloneVM.
- Go to qube settings for the created qube.
- Advanced.
- Boot qubes from CD-ROM.
- The same created qube will be shown as an option to choose the .iso image from -> thats impossible, because its fresh VM.

**Comment by alimirjamali** [comment]
> * The same created qube will be shown as an option to choose the .iso image from -> thats impossible, because its fresh VM.

Makes sense. PR Submitted.
