### ISSUE TITLE
No tag pointing at 4958721216160e785c5095c4a7de3574eccbb646

### ISSUE THREAD

**Issue by arhabd** [QubesOS/qubes-issues#9345]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
r4.2

### Brief summary
cant build Qubes locally

seems like same issue as on https://github.com/QubesOS/qubes-issues/issues/6243
but diffrent commit

### Steps to reproduce
follow README.me located at https://github.com/QubesOS/qubes-builderv2
then when trying to run qb using the following command line you will see it fails
`
qubes-builderv2$ sudo ./qb --builder-conf example-configs/builder-devel.yml package fetch
Running stage: fetch
22:28:14,575 [executor:docker:4fb1f45070bf] Executing 'sudo mkdir -p -- /builder /builder/build /builder/plugins /builder/distfiles&&sudo chown -R -- user:user /builder&&cd /builder&&/builder/plugins/fetch/scripts/get-and-verify-source.py https://github.com/fepitre/qubes-builder-rpm.git /builder/builder-rpm /builder/keyring /builder/plugins/fetch/keys --git-branch builderv2 --minimum-distinct-maintainers 1 --maintainer 9FA64B92F95E706BF28E2CA6484010B5CDC576E2 --maintainer 77EEEF6D0386962AEA8CF84A9B8273F80AC219E6'.
22:28:45,398 [executor:docker:4fb1f45070bf] output: --> Verifying tags...
22:28:45,399 [executor:docker:4fb1f45070bf] output: ---> No tag pointing at 4958721216160e785c5095c4a7de3574eccbb646
22:28:45,399 [executor:docker:4fb1f45070bf] output: ---> 4958721216160e785c5095c4a7de3574eccbb646 is a commit signed by a trusted key. Did the signer forget to add a tag?
Error: Failed to run 'sudo mkdir -p -- /builder /builder/build /builder/plugins /builder/distfiles&&sudo chown -R -- user:user /builder&&cd /builder&&/builder/plugins/fetch/scripts/get-and-verify-source.py https://github.com/fepitre/qubes-builder-rpm.git /builder/builder-rpm /builder/keyring /builder/plugins/fetch/keys --git-branch builderv2 --minimum-distinct-maintainers 1 --maintainer 9FA64B92F95E706BF28E2CA6484010B5CDC576E2 --maintainer 77EEEF6D0386962AEA8CF84A9B8273F80AC219E6' (status=1).
Traceback (most recent call last):
  File "/home/toor/Downloads/qubes-builderv2/qubesbuilder/cli/cli_base.py", line 65, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/click/core.py", line 1719, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/click/decorators.py", line 45, in new_func
    return f(get_current_context().obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/toor/Downloads/qubes-builderv2/qubesbuilder/cli/cli_package.py", line 62, in fetch
    _component_stage(
  File "/home/toor/Downloads/qubes-builderv2/qubesbuilder/cli/cli_package.py", line 40, in _component_stage
    p.run(stage=stage_name)
  File "/home/toor/Downloads/qubes-builderv2/qubesbuilder/plugins/fetch/__init__.py", line 184, in run
    executor.run(cmd, copy_in, copy_out, environment=self.environment)
  File "/home/toor/Downloads/qubes-builderv2/qubesbuilder/executors/container.py", line 258, in run
    raise ExecutorError(
qubesbuilder.executors.ExecutorError: Failed to run 'sudo mkdir -p -- /builder /builder/build /builder/plugins /builder/distfiles&&sudo chown -R -- user:user /builder&&cd /builder&&/builder/plugins/fetch/scripts/get-and-verify-source.py https://github.com/fepitre/qubes-builder-rpm.git /builder/builder-rpm /builder/keyring /builder/plugins/fetch/keys --git-branch builderv2 --minimum-distinct-maintainers 1 --maintainer 9FA64B92F95E706BF28E2CA6484010B5CDC576E2 --maintainer 77EEEF6D0386962AEA8CF84A9B8273F80AC219E6' (status=1).
`

### Expected behavior
ISO gets built without issue

### Actual behavior
Fails and cant proceed with build

**Comment by arhabd** [comment]
wow github do not like terminal output

**Comment by arhabd** [comment]
better formated terminal output https://pb.envs.net/?dbb595b77b3fdb1d#9s4i1fq7zAgRmn9LZC5ms3w6jhZh3of6qegadXmb5mtL

**Comment by marmarek** [comment]
`example-configs/builder-devel.yml` is mostly for developing builder itself. The README recommends using `example-configs/qubes-os-r4.2.yml`.

@fepitre maybe describe this config better, or even remove it from this dir completely? This is not the first person falling into this trap...

**Comment by arhabd** [comment]
> `example-configs/builder-devel.yml` is mostly for developing builder itself. The README recommends using `example-configs/qubes-os-r4.2.yml`.
> 
> @fepitre maybe describe this config better, or even remove it from this dir completely? This is not the first person falling into this trap...

the problem i face when trying to use qubes-os-r4.2.yml is i dont have qrexec-client-vm i want to build on a non qubes os system i found that builder-devel.yml did not face this issue this is why i used it

**Comment by marmarek** [comment]
You don't need it, it's just a matter of choosing "docker" executor instead of "qubes" one.

Anyway, lets do something else. There is a better guide for builderv2 in review, you can see it at https://github.com/QubesOS/qubes-doc/blob/60eea1c6dc1f55d54f011e4d5c6c169ac822b436/developer/building/qubes-builder-v2.md
I hope this will make things easier :)

**Comment by arhabd** [comment]
ok thank you
