### ISSUE TITLE
"Change Disk Password" tool isn't Qubes branded and isn't grouped with the other Qubes tools

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#9348]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

4.2

### Brief summary

The new "Change Disk Password" tool isn't Qubes branded and isn't grouped with the other Qubes tools, so it looks like it's not a Qubes tool, but it actually is:

https://github.com/QubesOS/qubes-disk-password-gui

### Steps to reproduce

1. Open app menu.
2. Click on gear icon.
3. Hover over "System Settings."
4. Select "Change Disk Password."

### Expected behavior

Since it's a Qubes tool, it should follow Qubes branding and be grouped with the other Qubes tools under "Qubes Tools." All other Qubes tools have an icon in "Qubes blue" color, and almost all of them have "Qubes" somewhere in the name.

### Actual behavior

The tool looks like it comes from Xfce or Fedora. That's what I thought at first when reading https://github.com/QubesOS/qubes-issues/issues/9346 and finding the tool in my own system. I was about to reply that it didn't appear to be a Qubes tool when I saw [the repo](https://github.com/QubesOS/qubes-disk-password-gui). That's the only reason I knew it was a Qubes tool.

**Comment by alimirjamali** [comment]
The culprit is [this line](https://github.com/QubesOS/qubes-desktop-linux-menu/blob/main/qubes_menu/settings_page.py#L101).

@kennethrrosen Do you accept the above improvement? It should be 
```
`qubes` in ..... \
or `disk_password_gui` in ....
```
And then menu should be restarted to check if the change works well.

Then its [AppMenu icon](https://github.com/QubesOS/qubes-disk-password-gui/blob/master/desktop_files/disk_password_gui.desktop#L4) should be changed from the old black lock to the modern unified blue one.

Finally it has to be decided if the [window icon](https://github.com/QubesOS/qubes-disk-password-gui/blame/master/disk_password_gui/disk_password_gui.glade#L9) of the actual running program should be also changed or left to be the black lock. I prefer it to remain the black lock. I guess Marmarta will advise you on the proper one in the PR comments.

p.s.

> I'd also note that "Qubes Policy Editor," "Qubes Menu Settings," and "Qubes Template Switcher" also reside under "System Tools" rather than "Qubes Tools"

They look fine on my DE. I am using XFCE. Maybe you are using KDE?

**Comment by kennethrrosen** [comment]
@alimirjamali like this?

```
 return 'qubes' in row.app_info.entry_name
            or 'disk_password_gui' in row.app_info.entry_name
```

I'm using XFCE, and since I can recall the policy editor, menu settings, and template switcher have always appeared for me under system tools. It seemed the desktop files were the culprits, but I'm usually wrong about these things.

**Comment by alimirjamali** [comment]
> @alimirjamali like this?

Yes. Exactly. Just test the change by modifying the `/usr/lib/python3.11/site-packages/qubes_menu/settings_page.py` and restarting the App Menu.

**Comment by kennethrrosen** [comment]
The answer seems simply to change the /usr/share/applications/disk_password_gui.desktop to qubes_disk_password_gui

**Comment by marmarek** [comment]
> isn't grouped with the other Qubes tools

I don't think it should be. Those groups are about the function of the tool, not its origin. Changing disk passphrase is a standard "system settings" action, there is nothing Qubes-specific in it.

**Comment by kennethrrosen** [comment]
> > isn't grouped with the other Qubes tools
> 
> I don't think it should be. Those groups are about the function of the tool, not its origin. Changing disk passphrase is a standard "system settings" action, there is nothing Qubes-specific in it.

Point taken. This is fair, but among community members there are always questions regarding how to change the LUKS password, something a newcomer to Linux or Qubes associates with the security granted by the OS (granted, disk encryption is not Qubes-specific). A few threads from over the years:

https://forum.qubes-os.org/t/investigating-how-to-change-luks-possible-past-luks-weakness/18071

https://forum.qubes-os.org/t/changing-password/17000

https://forum.qubes-os.org/t/can-i-change-encryption-passphrase-and-user-password/9599

https://forum.qubes-os.org/t/way-to-change-or-remove-the-disk-encryption-key/5342

https://forum.qubes-os.org/t/change-luks-disk-password/587

Perhaps a simple forum and listserv and social announcement could raise the necessary awareness without grouping within Qubes Tools.

**Comment by marmarek** [comment]
> there are always questions regarding how to change the LUKS password

That's exactly why this tool was created, as apparently it isn't functionality present in standard xfce (and in fact many other desktop environments)...

**Comment by kennethrrosen** [comment]
> > there are always questions regarding how to change the LUKS password
> 
> That's exactly why this tool was created, as apparently it isn't functionality present in standard xfce (and in fact many other desktop environments)...

It is no doubt a very welcome tool!

**Comment by marmarta** [comment]
> Hmm, okay. I had assumed that this was an oversight, but it sounds like this might be intentional after all. Is the lack of Qubes branding also intentional?

yeah, the idea was that it has nothing to do with Qubes-specific stuff. 

Also, I would guess that with menu search being now the default the discoverability is better...
