### ISSUE TITLE
GUI updater incorrectly states dom0 does not support in-progress update information

### ISSUE THREAD

**Issue by unman** [QubesOS/qubes-issues#9355]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
4.2

### Brief summary
As title

### Steps to reproduce
Use GUI updater to update dom0
Select dom0 line
Observe output

### Expected behavior
Message will be accurate

### Actual behavior
Output states that dom0 does not support in-progress update information
Output DOES provide in-progress update information for dom0

**Comment by marmarta** [comment]
sounds perfect!
