### ISSUE TITLE
Strange issue with custom DNS (dnscrypt-based) after moving to 4.2

### ISSUE THREAD

**Issue by oddgirl** [QubesOS/qubes-issues#9357]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

4.2 fresh install, fully updated

### Brief summary
I am trying to run custom DNS for my VPN qubes, most systems work as expected however, DNS just refuses to work

Iptraf-ng based observation suggests that something, somewhere sends ICMP unreachable for port 53 

### Steps to reproduce

Configure a setup that goes like 

[app-vm]-[dedicated cloned firewall vm]-[VPN-vm WITH DNSCRYPT]-internet

verify that it works okay without DNS crypt.

Try redirecting forwarded packets on port 53 to DNS crypt in the firewall VM (which worked in Qubes 3.2, 4.0 and 4.1)

### Expected behavior

DNS to work through DNS crypt

### Actual behavior

DNS times out

Iptraf NG suggests odd behavior related to ICMP

Behavior is as follows: 

**in app vm**

nslookup arghebar.com 8.8.8.8

Now, in firewall and VPN VM iptraf is running and hence we observe:

**in firewall VM**

 │ UDP (58 bytes) from 10.137.0.10:46229 to 8.8.8.8:53 on vif16.0                                                                                                │
│ UDP (58 bytes) from 10.137.0.33:46229 to 8.8.8.8:53 on eth0                                                                                                   │
│ **ICMP dest unrch (host comm denied) (86 bytes) from 8.8.8.8 to 10.137.0.33 on eth0**                                                                             │
│ **ICMP dest unrch (host comm denied) (86 bytes) from 8.8.8.8 to 10.137.0.10 on vif16.0**    

**in VPN vm**
 │ IUDP (58 bytes) from 10.137.0.33:60285 to 8.8.8.8:53 on vif15.0                                                       │
│ ICMP dest unrch (host comm denied) (86 bytes) from 8.8.8.8 to 10.137.0.33 on vif15.0                                                                               
│ UDP (58 bytes) from 10.137.0.33:60285 to 8.8.8.8:53 on vif15.0                                                       │
│ ICMP dest unrch (host comm denied) (86 bytes) from 8.8.8.8 to 10.137.0.33 on vif15.0                                                                            
│ ICMP dest unrch (host comm denied) (86 bytes) from 8.8.8.8 to 10.137.0.33 on vif15.0 

Which is extremely odd 

Everything worked extraordinarily well on older qubes 

P.S.: obviously I've overriden "classic" Qubes nat-to-NS to point to my DNS crypt in the VPN vm machine 

In VPN vm rules are:

Chain PREROUTING (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         
  120  7529 DNAT       udp  --  *      *       10.137.0.33          0.0.0.0/0            udp dpt:53 to:127.0.0.1:53

And, like I said it used to work ?

**Comment by ben-grande** [comment]
This is a support question, please refer to other venues.
Apparently you are using iptables, qubes switched to nftables.

**Comment by oddgirl** [comment]
> This is a support question, please refer to other venues. Apparently you are using iptables, qubes switched to nftables.

Ah well... thanks for prompt reply.
Yeah, I know of nftables but usually (9 times out of 10) backwards compat works.

Also (and I guess I should edit issue to reflect, maybe?) the problem seems to affect all services, not just DNS.

e.g. running say shadowsocks socks proxy in the VPN VM listening on the VIF interface does not allow VMs directly connected to it to connect to socks proxy, regardless of which NFT rules I try.
Observed symptoms are same - "out of the blue" ICMP unreachable in iptraf.

Anyway, not sure where to even go from here or what causes those "unreachable" responses, I'll go bother the forums maybe. Oh well :(
