### ISSUE TITLE
qvm-open-in-(d)vm behaviour with directories

### ISSUE THREAD

**Issue by alimirjamali** [QubesOS/qubes-issues#9360]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
R4.2

### Brief summary
According to a user on [forum](https://forum.qubes-os.org/t/qvm-open-in-vm-does-not-work-with-directories/27703):
```
However, qvm-open-in-vm does not work correctly when I’m giving it a directory.
```

User tries to open a directory in a disposable and got confused, expecting it to be copied to Disposable and be opened in File Manager.

### Steps to reproduce
- Run `qvm-open-in-dvm DIRECTORY`
- A DispVM is spawned
- It shuts down immediately

### Expected behavior
Either show an error message if the target is not a regular file; or copy the entire directory to destination VM and open it in Thunar (or applicable File Manager)

### Actual behavior
Confusion

**Comment by unman** [comment]
Since both manpage and help state that these apply to files, the
"expected behavior" is misplaced. If anything I favor the first option -
error message - what about all those other possible targets that
wont work?

**Comment by alimirjamali** [comment]
> what about all those other possible targets that wont work?

The patch I submitted exactly does that. Clear error message on targets that won't work (directories, symlink, ...). But we have to consider that this tool is also used to open URLs. So it had to be allowed in the conditions.
