### ISSUE TITLE
`qubes-gpg-sign` unavailable for Fedora 40

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#9379]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

R4.2

### Brief summary

`
`qubes-gpg-sign` is unavailable for Fedora 40.

### Steps to reproduce

Try to install `qubes-gpg-sign` in a Fedora 40 template.

### Expected behavior

Works

### Actual behavior

Fails because the package didn’t get built.

**Comment by marmarek** [comment]
Package built

**Comment by DemiMarie** [comment]
> I'm guessing that `qubes-gpg-sign` is related to <https://github.com/QubesOS/qubes-issues/labels/C%3A%20split-gpg2>. If that's incorrect, please let me know.

Nope, they are completely separate.  split-gpg2 exposes the gpg-agent protocol, whereas `qubes-gpg-sign` exposes only one function: signing data provided on stdin with the key whose fingerprint is in the service argument.
