### ISSUE TITLE
No network in Kali-core template after update at the end of july

### ISSUE THREAD

**Issue by neowutran** [QubesOS/qubes-issues#9392]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
R4.2

### Brief summary
A kali update broke how QubesOS configure its guest VM. 
For example, network is not configured properly 

### Steps to reproduce
Update a kali-core template. 
Start a guest VM based on kali-core

### Expected behavior
Kali-core  VM have a network access

### Actual behavior
Kali-core VM have no IP address configured. 

Two issues with workaround: 
1: Kali have moved the binary /sbin/ip that is required here: https://github.com/QubesOS/qubes-core-agent-linux/blob/main/network/setup-ip 
2: Kali is unhappy about a missing .hushlogin file and display a banner that broke the way QubesOS communicate with it's guest vm. Need to  "touch .hushlogin" for "user" and "root"

(forum reference: https://forum.qubes-os.org/t/kali-core-community-template-has-broken-networking-now-workaround/28027/4)

**Comment by labanskoller** [comment]
The dependency on "/sbin/ip" seems to have been fixed. I've confirmed networking to work again in `qubes-core-agent-networking` version `4.2.37-1+deb12u1`.
