### ISSUE TITLE
qubes-manager 4.2.8-1 reveals IP address of a non-networked vm

### ISSUE THREAD

**Issue by unman** [QubesOS/qubes-issues#9398]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
4.2.2

### Brief summary
As title
Reported in Forum by ephile

### Steps to reproduce
Have qube with netvm 'none' - can have qubes-core-networking installed, or not.
Open Qubes Manager
Right-Click -> Clone
RightClick -> Template

### Expected behavior
A cloned, non-networked, vm (e.g., the vault qube) will not display an IP address (10.137.0.x) in the Qubes Manager. 
Likewise for a non-networked qube when setting a new template.

### Actual behavior

The IP address of the non-networked qube is displayed in the GUI. However, there is no IP address listed after qvm-ls -n, nor is there a networked interface created within the qube (only the lo interface).

If one changes the template in the GUI via Right-click -> Settings -> Template, then future modifications via Right-click -> Template will no longer reveal the IP.

**Comment by alimirjamali** [comment]
PR Submitted

Small fix (only one line) for a minor cosmetic issue.
Review priority: low
