### ISSUE TITLE
Separate pools for `root` and `private` by default

### ISSUE THREAD

**Issue by alimirjamali** [QubesOS/qubes-issues#9424]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### The problem you're addressing (if any)
Qubes R4.2 (and R4.3) come with the single `varlibqubes` pool by default at the moment. Both of the legacy Qubes Manager and the Qubes Desktop Manager `Create New Qube` dialogues allow user to select a single pool for both private and root volumes. It is only possible to select separate pools via CLI tools.

### The solution you'd like
Having separate pools have the following benefits:
1. User could have a fast NVMe SLC/MLC/TLC storage for root volume for faster boot times. And a QLC SATA storage for private volume with cheaper cost/GiB.
2. If BTRFS is implemented, Deduplication is mostly logical for root volumes (no one want multiple allocation of the same binary in different templates).
3. Again with BTRFS, root and private could be individual subvolumes which would allow easier snapshots of pools individually.

### The value to a user, and who that user might be
Cost benefit to users in most cases
Faster machines if user has more than one storage drive.
Flexibility

### Completion criteria checklist

(This section is for developer use only. Please do not modify it.)

**Comment by marmarek** [comment]
> Qubes R4.2 (and R4.3) come with the single `varlibqubes` pool by default at the moment

That's not fully accurate. With the default LVM setup, it's a separate `vm-pool`. But still the same for "root" and "private" volumes.

Anyway, the scenario you describe sounds like highly customized one.  If you want, you can already select default pool for different volumes (see `qubes-prefs`, specifically `default_pool_*` properties). But also, for template-based qubes, the root pool is always the one where template's root volume reside, regardless where private volume is. So, the setup you describe is already possibly by simply having templates in one pool (their private volume will be also there, but it's mostly empty and rarely used so shouldn't matter that much) and AppVMs in another.

**Comment by alimirjamali** [comment]
> If you want, you can already select default pool for different volumes (see `qubes-prefs`, specifically `default_pool_*` properties).

I admit I did not know about the above. But still adding separate pool selection to GUI tools might be a good idea. I could implement it for both old PyQt based and PyGTK based Managers. If it is a good idea.

**Comment by marmarta** [comment]
I'm not sure if this should be exposed in the GUI? This is a pretty advanced configuration option, I would hazard a guess that people who want to do this are comfortable with CLI - and I'm not sure if exposing it in GUI won't be confusing for people who do not understand what this does?

**Comment by marmarta** [comment]
Yeah, the more I think of it the more I feel like "configuring pools manually" should be something we don't really encourage that much, especially as it's so easy to hurt yourself if you run out of disk space in a pool.

**Comment by alimirjamali** [comment]
Now that I reconsider it (after learning about `default_pool_*`), it would be something very few people would need (or like).

Closing issue as not planned
