### ISSUE TITLE
Qubes OS Updater: additional update check after n days does not work

### ISSUE THREAD

**Issue by rapenne-s** [QubesOS/qubes-issues#9427]
### Qubes OS release

R4.2.2

### Brief summary

The Qubes OS Updater GUI have a feature named "additional update check" to look for updates after n days in case a template is never used. This does not seem to work.

### Steps to reproduce

Have a template VM used by a qube, do not start the qube within n days, wait for the qubes os updater GUI to show up, the qube should never be selected for update.

### Expected behavior

qubes with a "last checked" date older than n days should automatically be checked for update.

### Actual behavior

templates can be left forever without updates

the screenshot was taken 2024-08-21 and there should be an attempt to update qubes after **5** days per the configuration

![extra_check](https://github.com/user-attachments/assets/91781246-005b-4a96-b7d6-14453d27bb35)

**Comment by alimirjamali** [comment]
PR Submitted

Review priority: Medium

**Comment by alimirjamali** [comment]
Related: #8511

**Comment by rapenne-s** [comment]
https://github.com/alimirjamali/qubes-desktop-linux-manager/commit/82a35ba87f1c8b3d16b1c47e0587c4a61089c305 fixes the problem, although I did not try the test as I do not know how to run them. I applied the one line change manually in dom0 :(
