### ISSUE TITLE
Dom0 update log visible during update

### ISSUE THREAD

**Issue by mileswentdown** [QubesOS/qubes-issues#9428]
### Qubes OS release

Qubes R4.2.2

### Brief summary

After two months of not updating dom0 I updated dom0 despite the update utility stating that there is no available update. While I was doing that I noticed that the update log was visible during the update happening (which is not the expected behavior).

### Steps to reproduce

- Skip update check (the system should state that there are no updates available despite that being false).
- Try to update dom0 anyways.
- Check the log during the update process for unusual behavior (specified later).

### Expected behavior

Dom0 update log absolutely silent during the update except for the usual message "Dom0 does not support in-progress update information [...]" 

### Actual behavior

Update log visible in real time during the update.

**Comment by ben-grande** [comment]
Duplicate and can be closed, fix did not reach stable branch yet. Please check open and closed issues next time.

- https://github.com/QubesOS/qubes-issues/issues/9355
