### ISSUE TITLE
crond running in dom0

### ISSUE THREAD

**Issue by 3hhh** [QubesOS/qubes-issues#9439]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
4.2

### Brief summary
crond runs in dom0

### Steps to reproduce
`systemctl status crond` in dom0

### Expected behavior
Not running.

### Actual behavior
Running.

**Comment by marmarek** [comment]
Why exactly do you expect it not running? It is a normal service that executes periodic system tasks, so it should be running.

**Comment by rustybird** [comment]
There's even some Qubes OS specific stuff in `/etc/cron.*/`

**Comment by 3hhh** [comment]
On 9/4/24 10:57, Marek Marczykowski-Górecki wrote:
> Why exactly do you expect it not running? It is a normal service that executes periodic system tasks, so it should be running.

Argh, I had confused it with cups, which I hadn't expected to be running, but it's not so it's all fine. Sorry for the fuzz, my bad...
