### ISSUE TITLE
consider adding RPC based unattended upgrades mechanism

### ISSUE THREAD

**Issue by evq** [QubesOS/qubes-issues#9448]
### The problem you're addressing (if any)

currently afaict all updates are handled through `vmupdate` which involves injecting the agent into the running VM. the agent is installed in dom0 but contains code that is specific to each templatevm distribution. in the general case, this makes it slightly more difficult to add support for new distributions since changes need to be coordinated across dom0 and the new templatevm.  with the `qubes.InstallUpdatesGUI` mechanism, it was previously easy for a new templatevm ( or end user ) to override the updates behavior.

### The solution you'd like

consider adding an RPC based unattended upgrades mechanism, e.g. `qubes.InstallUpdates`. this could write it's logs to `/var/log/qubes/qubes-update` to conform to current expectations around the `vmupdate` agent.

this could simply be a fallback for distributions where the agent is unsupported or it could be the primary target whose default implementation simply launches the injected agent. the latter allows for potential end user customization.

### The value to a user, and who that user might be

1. user of community templatevms which currently do not support updates

- currently updates appear to be supported for fedora, debian, and arch whereas gentoo, guix ( wip ), and nixos ( wip ) are not supported. adding an RPC based mechanism will make it easier to add support.

2. user / organization who wants to customize update behavior
- user who installs nix package manager on debian and wants these to be updated in addition to their apt packages
- user who has AUR packages installed via yay and wants those to be updated 
- an organization using QubesOS as a base for a secure workstation who has custom update needs ( e.g. software with a built-in updater, etc. )

### Completion criteria checklist

(This section is for developer use only. Please do not modify it.)

**Comment by marmarek** [comment]
See https://github.com/QubesOS/qubes-issues/issues/7992#issuecomment-2344636061 for explanation why not.
