### ISSUE TITLE
Chromium has no web access when the AppVM is connected to a Standalone VPN AppVM. All other connectivity within the AppVM work fine (eg Firefox, apt etc). 

### ISSUE THREAD

**Issue by ghost** [QubesOS/qubes-issues#9455]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Brief summary

Chromium has no web access when the AppVM is connected to a Standalone VPN AppVM. All other connectivity within the AppVM work fine (eg Firefox, apt etc). 

### Steps to reproduce
Create AppVM containing Chromium.

Connect said AppVM to a Standalone VPN AppVM.

Launch the AppVM connected to the VPN AppVM.

Launch Chromium.

Launch Firefox.

### Expected behavior
Chromium has web access

### Actual behavior

Chromium has no web access

**Comment by TNTBOMBOM** [comment]
very difficult to reproduce, not much details on steps given, user even deleted his github account seems to be..
