### ISSUE TITLE
COSMIC support

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#9461]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### The problem you're addressing (if any)

For users coming from macOS, GNOME provides a familiar UX but is not a good fit for Qubes OS.  Other desktops are a better fit for Qubes OS but do not provide as familiar a UX.

### The solution you'd like

Support the COSMIC desktop environment once it is ready.

### The value to a user, and who that user might be

Users, such as journalists, who come from macOS will have a desktop environment with a familiar UX.

### Completion criteria checklist

(This section is for developer use only. Please do not modify it.)

**Comment by marmarek** [comment]
> once it is ready.

Lets think about this one only when it will be clear this will actually be a good fit. The thing that exists right now is not.

**Comment by Ganwtrs** [comment]
COSMIC Epoch 1 has released on Pop!_OS, it will be ready really soon. COSMIC has a really good security culture so far; it is written in a memory safe language, and even though Qubes OS does not support Wayland, COSMIC's Wayland support shows that they care about security

**Comment by Ganwtrs** [comment]
COSMIC also has a tiling window manager mode, which could be especially useful to see the color coded qube borders

**Comment by allddd** [comment]
@marmarek any chance this could be revisited? i've been using cosmic for a while now and haven't run into any issues. since it supports both floating and tiling by default, i think it'd be a great fit.
