### ISSUE TITLE
UEFI boot of guests doesn’t work at all

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#9472]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

R4.2

### Brief summary

UEFI guests doesn’t work at all.  The guest spins at 100% CPU without even initializing the QEMU-emulated display.

### Steps to reproduce

Put an HVM guest in UEFI mode and start it:

```shell-session
$ qvm-prefs SOMEVM virt-mode hvm
$ qvm-prefs SOMEVM kernel ''
$ qvm-prefs SOMEVM debug True
$ qvm-features SOMEVM uefi 1
$ qvm-start SOMEVM
```

### Expected behavior

SOMEVM starts, or at least displays something in the QEMU emulated display.

### Actual behavior

SOMEVM hangs at 100% CPU without even initializing the emulated display.

This may be because there is no `edk2-ovmf-xen` package installed on the host.

**Comment by TNTBOMBOM** [comment]
Even though i have installed qubes on my pc with UEFI mode, templates are not using UEFI but instead on legacy boot. weird..
