### ISSUE TITLE
nouveau crashing dom0 on `kernel-latest`

### ISSUE THREAD

**Issue by SaswatPadhi** [QubesOS/qubes-issues#9480]
### Qubes OS release

R4.2

### Brief summary

I upgraded my `kernel-latest` package that installed 6.10.10 in dom0. After rebooting the system appears frozen.

I had 6.10.3 installed and upon booting with this old kernel, the system works as expected. In the old boot logs, I see that nouveau is crashing. Not sure if this has been reported and fixed upstream already.

### Steps to reproduce

1. Install `kernel-latest` and `kernel-latest-qubes-vm` in dom0
2. Reboot

### Expected behavior

System boots and lightdm shows up

### Actual behavior

System freezes halfway through the boot process

**Comment by marmarek** [comment]
Looks similar to https://gitlab.freedesktop.org/drm/nouveau/-/issues/388
