### ISSUE TITLE
NovaCustom V54  sys-net not starting 

### ISSUE THREAD

**Issue by nestire** [QubesOS/qubes-issues#9493]
### Qubes OS release
Qubes 4.2.3
Dasharo 0.9.0

### Brief summary
After default install with fedora-40 as template sys-net fails to start the libxl-driver.log shows:
```
libxl: libxl_dm.c:2857:stubdom_xswait_cb: Domain 2:Stubdom 3 for 2 startup: timed out
libxl: libxl_create.c:1975:domcreate_devmodel_started: Domain 2:device model did not start: -9
```

dmesg in dom0 shows a bunch of: 

```
[Firmware Bug]: CPU 1: APIC ID mismatch. CPUID: 0x0001 APIC 0x0021
[Firmware Bug]: CPU 1: APIC ID mismatch. Firmware: 0x0010 APIC 0x0021
```

they differ in the Hex value 

thats maybe related. 

unfortunately sys-usb does also not start so i can't get the complete log  in a easy way 

### Steps to reproduce
Default install Qubes 4.2.3 on a V54 with Dasharo 0.9.0 

### Expected behavior
works

### Actual behavior
Does not start

**Comment by marmarek** [comment]
> dmesg in dom0 shows a bunch of:
> 
> ```
> [Firmware Bug]: CPU 1: APIC ID mismatch. CPUID: 0x0001 APIC 0x0021
> [Firmware Bug]: CPU 1: APIC ID mismatch. Firmware: 0x0010 APIC 0x0021
> ```

That's unrelated to this issue. See https://lore.kernel.org/xen-devel/20240405123434.24822-3-jgross@suse.com/

> libxl: libxl_dm.c:2857:stubdom_xswait_cb: Domain 2:Stubdom 3 for 2 startup: timed out
> libxl: libxl_create.c:1975:domcreate_devmodel_started: Domain 2:device model did not start: -9

Some more info from the stubdom log (/var/log/xen/console/guest-sys-net-dm.log) would be useful. But my guess is that system time was wrong (way in the past) during installation - unfortunately, installer fails to install some files if their time is in the future (package time in the future compared to system time). The easiest solution is to set correct system time and reinstall.
If my guess is correct, this is duplicate of https://github.com/QubesOS/qubes-issues/issues/9440

**Comment by nestire** [comment]
thx indeed setting the correct time before install fixed it. so closing this as duplicate #9440
