### ISSUE TITLE
nm-applet invisible in Xfce

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#954]
NetworkManager applet is invisible in Xfce on R3. On KDE it works just fine.
The process is running and applet is enabled:
```
[user@netvm ~]$ gsettings get org.gnome.nm-applet show-applet
true
```
To workaround this problem one can disable and enable the applet:
```
gsettings set org.gnome.nm-applet show-applet false
gsettings set org.gnome.nm-applet show-applet true
```

Packages versions:
network-manager-applet-0.9.10.2-1.fc21.x86_64
qubes-gui-vm-3.0.1-1.fc21.x86_64

**Comment by v6ak** [comment]
Is it still true? I use XFCE, but I've not encountered that issue. But I've XFCE+KDE installation, so it might have caused the difference.

**Comment by cfcs** [comment]
I have this problem every now and then, although it seems to have disappeared over the past few weeks. I'm running `R2`. The icon reappears in the system tray if an (any) X application is started in the netvm, for example by starting `gnome-terminal` from the menu.

**Comment by marmarek** [comment]
The problem on R2 when icon reappear when any X application is started is not related to the problem reported here and is already fixed in R3.
Actually I didn't seen  the R3 problem for a few weeks. Maybe some Fedora update fixed this? I'm closing it now. If someone is able to reproduce, we can always reopen the issue.
