### ISSUE TITLE
Typo in exception handling

### ISSUE THREAD

**Issue by Luni2000** [QubesOS/qubes-issues#9545]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
R4.2.3

### Brief summary
In the file "/usr/lib/python3.11/site-packages/qubesusbproxy/core3ext.py" in line 648 santizied_stderr should be sanitized_stderr.

### Steps to reproduce
throw any exception while attaching a usb device

### Expected behavior
print an actual error message

### Actual behavior
print the stacktrace for that typo

**Comment by alimirjamali** [comment]
> In the file "/usr/lib/python3.11/site-packages/qubesusbproxy/core3ext.py" in line 648 santizied_stderr should be sanitized_stderr.

Thanks for the bug report

PR submitted

**Comment by marmarek** [comment]
This is fixed in https://github.com/QubesOS/qubes-app-linux-usb-proxy/commit/631c210 ( https://github.com/QubesOS/updates-status/issues/5229 )
