### ISSUE TITLE
Usb not attaching to appvms

### ISSUE THREAD

**Issue by gamtospitisou** [QubesOS/qubes-issues#9546]
### Qubes OS release

Bug present in qubes 4.2.3

### Brief summary
A usb will not attach to an appvm and will sometimes throw an error and sometimes nothing.
![IMG20241025164125](https://github.com/user-attachments/assets/65e054f9-f1cf-4c89-9e5e-bd845a6bba5f)

### Steps to reproduce
Attach a usb to an appvm and check with `lsblk` if it is attached.

### Expected behavior
The usb should be attached and fully recognised.

### Actual behavior
The usb fails to attach and sometimes throws an error.

Here are 2 support questions which are without solution.

https://forum.qubes-os.org/t/what-does-thi-error-mean/29810
https://forum.qubes-os.org/t/what-happened-to-attaching-usb-to-qubes/29293

**Comment by gamtospitisou** [comment]
I found why it was doing it, i recently reinstalled qubes and clicked install with latest kernel. I now reinstalled normally and it worked for me. I guess there is a problem with the kernel.

**Comment by gamtospitisou** [comment]
6.6.48-1.fc37 is the only kernel tgat works.
6.6.54-1.fc37 and 6.10.10-1.fc37 and 6.11.2-1.fc37 all dont work. Any update because 6.6.48 is outdated.

**Comment by marmarek** [comment]
> 6.6.48-1.fc37 is the only kernel tgat works.
> 6.6.54-1.fc37

This is _very_ useful information. Between those two commits there is just one change in usbip: https://github.com/torvalds/linux/commit/73ec94aac593ef4bac3a864365f0433b8266225b. Based on the description it's plausible it fixes a similar issue as https://github.com/QubesOS/qubes-linux-kernel/pull/504 did. And testing revealed that the latter patch does cause the issue (6.6.54 without "0001-usbip-tweak-clear-halt-with-simple-reset.patch" works just fine). So, I'll revert it and if the original issue comes back, we'll need to find an alternative solution.
