### ISSUE TITLE
NetworkManager does not work in ProxyVM/AppVM based on Debian 7 template

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#955]
On Debian 7, when NetworkManager is enabled in ProxyVM/AppVM (`qvm-service VMNAME -e network-manager`), startup scripts prepare static configuration for eth0 based on Qubes settings (via
xenstore/qubesdb). It is created by `setup-ip` script and the output file is `/etc/NetworkManager/system-connections/qubes-uplink-eth0`. Apparently NetworkManager in Debian 7 does not understand this file:
```
Apr 12 00:14:54 localhost NetworkManager[1495]:    keyfile: parsing qubes-uplink-eth0 ...
Apr 12 00:14:54 localhost NetworkManager[1495]: Unknown setting 'ethernet'
Apr 12 00:14:54 localhost NetworkManager[1495]: Invalid setting name 'ethernet'
Apr 12 00:14:54 localhost NetworkManager[1495]: read_ip4_addresses: ignoring invalid IPv4 address item ''
Apr 12 00:14:54 localhost NetworkManager[1495]:    keyfile:     error: invalid or missing connection property 'addresses'
```
And tries to configure eth0 using DHCP...

The same file works on Debian 8. It looks like this:
```
[802-3-ethernet]
duplex=full

[ethernet]
mac-address=00:16:3e:5e:6c:30

[connection]
id=VM uplink eth0
uuid=de85f79b-8c3d-405f-a652-cb4c10b4f9ef
type=802-3-ethernet

[ipv6]
method=ignore

[ipv4]
method=manual
may-fail=false
dns=10.137.1.1;10.137.1.254
address1=10.137.1.50/32,10.137.1.1
```

**Comment by marmarek** [comment]
@nrgaway, can you look at this? Or should we ignore the issue since jessie is now stable?

**Comment by nrgaway** [comment]
I was thinking as labelling it won't fix since Jessie is now stable.
Within a few weeks Whonix will also be moved over to Jessie and I will add
support for stretch
