### ISSUE TITLE
The Impact of Kernel Updates on Hyper-Threading Behavior

### ISSUE THREAD

**Issue by vzvva** [QubesOS/qubes-issues#9550]
Hi,

I chose to enable hyper-threading for better performance, according to this text [1]. However, every time the dom0 kernel is updated, a line is appended to the last line of this file [2]. The user expects the configuration to remain unchanged, but each time this line [3] is appended to the grub file, the "`smt=`" line repeats three times, and the last line disables hyper-threading.

[1] https://www.qubes-os.org/news/2018/09/02/qsb-43/
[2] `/etc/default/grub`
[3] `GRUB_CMDLINE_XEN_DEFAULT="$GRUB_CMDLINE_XEN_DEFAULT smt=off"`

**Comment by marmarek** [comment]
To avoid re-disabling hyperthreading, you can comment out the existing `smt=off` instead of changing it.
Anyway, we do not guarantee system security if you decide to do so (as explained in that QSB doc).

**Comment by vzvva** [comment]
Thanks, I will try it.
My laptop is slow and i need to enable it.
