### ISSUE TITLE
qvm-copy-to-vm failing

### ISSUE THREAD

**Issue by hedgehogdrfrink** [QubesOS/qubes-issues#9555]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
4.2.1 

### Brief summary
unable to use qvm-copy-to-vm commands, throws the following error as an example,

qvm-copy-to-vm sys-usb /home/user/Downloads/barbet-ap2a.240805.005-factory-231e0672.zip /home/user/
qubes-fs-tree-check: Refusing to copy unsafe symbolic link "/home/user//.librewolf/md32lpwd.default-default/lock"

[user@android-qube Downloads]$ touch anything
[user@android-qube Downloads]$ qvm-copy-to-vm sys-usb anything /home/user/
qubes-fs-tree-check: Refusing to copy unsafe symbolic link "/home/user//.librewolf/md32lpwd.default-default/lock"

### Steps to reproduce
pretty much try transferring anything with qubes to another vm. This used to work when I setup a windows qube before.

### Expected behavior

copy the file to another qube.

### Actual behavior

errors out with the error shown above.

**Comment by alimirjamali** [comment]
> qvm-copy-to-vm sys-usb /home/user/Downloads/barbet-ap2a.240805.005-factory-231e0672.zip /home/user/
> [user@android-qube Downloads]$ qvm-copy-to-vm sys-usb anything /home/user/

Please try `man qvm-copy` or `man qvm-copy-to-vm` in one of your AppVMs. You are not using it right (Are you trying to copy a file to a destination directory within sys-usb?)? It always copies to `/home/user/QubesIncoming/<SOURCE_VM_NAME>`.  The way that you are using it, it tries to copy both <anything> AND everything within </home/user/*> to sys-usb

**Comment by hedgehogdrfrink** [comment]
I've always used qvm-copy-to-vm [Destination vm] [source-file-path] [destination vm file path] successfully before in the past, first time I ran into this issue though that was setting up a windows qube with dom0 looking at the man page,

Thank you,

was able to use qvm-copy successfully.
