### ISSUE TITLE
AntiEvilMaid install proxy workaround

### ISSUE THREAD

**Issue by david415** [QubesOS/qubes-issues#956]
I doubt many people will have this weird problem...
My netvm is connect via ethernet switch to a tor/http proxy... so if I'm going to install new package with yum I have to use my local http proxy.

When I followed the instruction here:
https://www.qubes-os.org/wiki/AntiEvilMaid/

I initially had trouble with this command:
  sudo qubes-dom0-update anti-evil-maid 

The workaround is easy. Simply add the http_proxy environment variable to /etc/profile.d/proxy.sh like this:
  export http_proxy=http://192.168.1.1:8080
  export https_proxy=http://192.168.1.1:8080

Perhaps the user docs should be updated with this info?

**Comment by marmarek** [comment]
The standard way to configure yum should also be enough - add proxy=...
to /etc/yum.conf in dom0.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by marmarek** [comment]
Standard way of configuring proxy in package manager is enough (/etc/yum.conf),
nothing Qubes specific needed.
