### ISSUE TITLE
`qubes-vm-update` doesn't print an error when arguments are bad

### ISSUE THREAD

**Issue by RandyTheOtter** [QubesOS/qubes-issues#9565]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

4.2.3

### Brief summary

If you run `qubes-vm-update` with nonexistent target, it will not print out any error message. This is annoying when there are plenty of targets and you don't know which one causes it.

### Steps to reproduce

`qubes-vm-update --targets=whatever`

### Expected behavior

return 64, print something like: `error: target 'whatever' not found`

### Actual behavior

return 64

**Comment by alimirjamali** [comment]
PR Submitted

Review priority: Low
