### ISSUE TITLE
Qubes install problem - incompatibility?

### ISSUE THREAD

**Issue by simonepsp** [QubesOS/qubes-issues#957]
Hi,
I'm trying to install Qubes on my Lenovo Thinkpad T410i but I have some problems...
I can't see install GUI and every line in verbose log seems overlying. Then the screen becomes black :\

Here's a photo:
![730409119_14501465833834466310](https://cloud.githubusercontent.com/assets/11884948/7212297/d4eb8692-e564-11e4-8788-603b0ae95854.jpg)

Booting it with a different kernel doesn't change result.
I've also tried to boot install setup in "Basic graphic mode" but screen remains black.

:( What can I do?
Thanks

**Comment by marmarek** [comment]
Try asking on qubes-users mailing list - there is the right place for seeking for help. Maybe someone have similar hardware, or had similar problem.
Also send there more readable photo...
