### ISSUE TITLE
`_NET_WM_NAME` & `_NET_WM_ICON_NAME` support

### ISSUE THREAD

**Issue by alimirjamali** [QubesOS/qubes-issues#9571]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### The problem you're addressing (if any)

The GUI daemon doesn’t support [`_NET_WM_NAME` & `_NET_WM_ICON_NAME`].

### The solution you'd like

The GUI daemon could support `_NET_WM_NAME` & `_NET_WM_ICON_NAME`. As [recommended](https://specifications.freedesktop.org/wm-spec/1.3/ar01s05.html) by EWMH.

### The value to a user, and who that user might be
Utilities such as `wmctrl -l` do not show the Qube window titles within GUIVM at the moment. For automation and easier parsing. Setting the mentioned properties is easy.

### Completion criteria checklist

(This section is for developer use only. Please do not modify it.)

**Comment by 3hhh** [comment]
Fyi: Some WMs [deliberately lie](https://github.com/qtile/qtile/blob/85019ec00030c20a090ec66b86c32ebc701fbbe5/libqtile/resources/default_config.py#L219-L227) about `_NET_WM_NAME` as some UI toolkit devs (Java) decided to block them.
