### ISSUE TITLE
Creation of a new StandaloneVM/TemplateVM fails during the cloning process

### ISSUE THREAD

**Issue by Minimalist73** [QubesOS/qubes-issues#9574]
### Qubes OS release
r4.2.3

### Brief summary
When creating a new StandaloneVM or TemplateVM that involves cloning, the creation fails with an error and prevents the new qube from being created.
Creating a qube of type AppVM works fine.
```
ERROR: TypeError('QubesBase.clone_vm() takes 3 positional arguments but 4 positional arguments (and 1 keyword-only argument) were given')
```

### Steps to reproduce
- Open the qube creation menu (new or old, it doesn't matter)
- Select Type: StandaloneVM or TemplateVM
- Select template to clone
- Network to default
- Create qube and get error

### Expected behavior
StandaloneVM or TemplateVM is created.

### Actual behavior
Ends in error and doesn't create anything.

**Comment by gunduzc** [comment]
I have the exact same problem and I am able to reproduce this with a fresh QubesOS install.

**Comment by TommyTran732** [comment]
Making AppVMs work now but TemplateVMs are still broken
