### ISSUE TITLE
kali-core templates (and debian-12 based kali-rolling) broken qubes dependencies

### ISSUE THREAD

**Issue by thedeadliestcatch** [QubesOS/qubes-issues#9577]
### Qubes OS release
4.2.x

### Brief summary

This is a caveat emptor to users of the kali-core template, as well as those building kali templates from the stable debian-12 templates (not community).

At the moment, kali packages have introduced a set of upgrade dependencies that conflict with all the qubes packages (including core-agent, etc).

Unfortunately this does not only manifest with `dist-upgrade`, it will occur when installing any meta packages for tools. The result is an inoperable template, as qrexec will fail, along everything else (the entire stack of Qubes VM packages is removed).

### Steps to reproduce

1. Install kali-core, or prepare kali-rolling based off debian-12-xfce.
2. Update APT package index
3. Attempt to install upgrades or any meta package (ex. kali-tools-*).

### Expected behavior

A functional template with the Qubes VM packages intact.

### Actual behavior

Doom.

**Comment by Nurmagoz** [comment]
Did you use in-vm kernel (debian kernel) or qubes kernel for the template? if you use qubes kernel it wont work because its not compatible with debian testing which is what kali based on (a hint of why its not working but i didnt test that myself).
