### ISSUE TITLE
XRandR reports 0mm display size

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#9578]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

R4.2

### Brief summary

Qubes OS trips [this warning from winit](https://github.com/rust-windowing/winit/blob/74958ecc6f5ee195d8fe214b3f66875fc6cefa99/src/platform_impl/linux/x11/util/randr.rs#L23-L27):

```rust
    // See http://xpra.org/trac/ticket/728 for more information.
    if width_mm == 0 || height_mm == 0 {
        warn!("XRandR reported that the display's 0mm in size, which is certifiably insane");
        return 1.0;
    }
```

This means that the display size is zero, which is obviously nonsense.

### Steps to reproduce

Run `xrandr`.  I get the following:

```
$ xrandr
Screen 0: minimum 64 x 64, current 1920 x 1080, maximum 32767 x 32767
DUMMY0 connected primary 1920x1080+0+0 0mm x 0mm
   QB1920x1080   46.10*+
DUMMY1 disconnected
DUMMY2 disconnected
DUMMY3 disconnected
DUMMY4 disconnected
DUMMY5 disconnected
DUMMY6 disconnected
DUMMY7 disconnected
DUMMY8 disconnected
DUMMY9 disconnected
DUMMY10 disconnected
DUMMY11 disconnected
DUMMY12 disconnected
DUMMY13 disconnected
DUMMY14 disconnected
DUMMY15 disconnected
```

### Expected behavior

Display size is accurate (outside Whonix), or at least non-zero.

### Actual behavior

Display size is zero.

**Comment by alimirjamali** [comment]
The two `width_mm_atom` and `height_mm_atom` are [currently](https://github.com/QubesOS/qubes-gui-agent-linux/blob/main/xf86-video-dummy/src/dummy_driver.c#L103-L112) set to 0 in dummy driver. Hard coding them to a reference display size is not ideal. I guess a protocol bump should allow vmside to query the actual size from the xside.

**Comment by marmarek** [comment]
Not necessarily. [`qubes.SetMonitorLayout`](https://github.com/QubesOS/qubes-gui-agent-linux/blob/main/appvm-scripts/usrbin/qubes-set-monitor-layout) service should set appropriate size, when it receives it from dom0 (or gui domain). I guess it doesn't get it for some reason.

**Comment by alimirjamali** [comment]
The [unittests](https://github.com/QubesOS/qubes-core-admin-client/blob/main/qubesadmin/tests/tools/qvm_start_daemon.py#L495-L496) for `qvm_start_daemon.py` makes it evident. The `w_mm` and `h_mm` is calculated only for hidpi screens. Overall very easy to fix. [This](https://github.com/QubesOS/qubes-core-admin-client/blob/main/qubesadmin/tools/qvm_start_daemon.py#L418-L420) else case should be fixed and unittests should be readjusted. Could I select **96DPI** for non-hidpi screens? Arch Wiki mentions it as the most common non-hidpi resolution.
