### ISSUE TITLE
LVM pool can’t activate LVs with activationskip flag

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#9579]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

R4.3 git main but probably affects R4.2 too

### Brief summary

The LVM pool does not pass the `--ignoreactivationskip` flag to `lvchange --activate=y`, so volumes with the activation skip flag cannot be activated.

### Steps to reproduce

Set the “activation skip” flag on an LV.

### Expected behavior

Everything works since QubesOS/qubes-core-admin@6dffbf9363a5539d89fccdc007ef7fd199ccb5c2

### Actual behavior

Activation does not work.

**Comment by marmarek** [comment]
Did you hit this issue somewhere? How have you arrived at such situation? Volumes we care about are created with `--setactivationskip=n` already.

**Comment by marmarek** [comment]
> Correct, but what if there is a volume that does not have this flag?

It means somebody has removed it, probably intentionally. We shouldn't override this.
