### ISSUE TITLE
Qubes OS 4.2.3 iso stucks during boot before installation process

### ISSUE THREAD

**Issue by Maltstar** [QubesOS/qubes-issues#9590]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
4.2.3

### Brief summary
When booting with Qubes OS 4.2.3 iso from USB drive, boot process gets stuck and the installation process is not started.
This happens on every installation entry on the boot menu:

-  "Install Qubes OS R4.2.3"
-  "test media and install Qubes OS R4.2.3"
-  "Throubleshooting - verbose boot  and Install Qubes OS R4.2.3"
- "Install Qubes OS R4.2.3 using kernel-latest (6.10.10-1.qubes.fc37)"

The previous version of Qubes OS was working perfectly.
I am using a ZOTAC GeForce GTX 1060 AMP as graphic card I don´t know if it might be related.

### Steps to reproduce

1. Download the iso for Qubes OS 4.2.3 
2. Flash the iso on an usb drive
3. Boot on usb drive

### Expected behavior
Qubes OS installer is started after choosing an install option on the boot menu

### Actual behavior
Qubes OS installer is not started and the boot process get stuck.
screenshot with verbose boot:
![boot_process_stuck_in_verbose](https://github.com/user-attachments/assets/d1d58ccc-4acd-4f8e-91f7-ec6d6a59e8aa)

screenshot with other boot options:
![boot_process_stuck](https://github.com/user-attachments/assets/94633c95-c06a-44a0-a8df-a377a05170f1)

**Comment by tokideveloper** [comment]
> ### Steps to reproduce
> 
>     1. Download the iso for Qubes OS 4.2.3

Did you verify at least the checksum (or even better: the PGP signature) of the downloaded ISO?

>     2. Flash the iso on an usb drive

Did you re-verify the image on the USB drive after flashing? [In the past](https://github.com/QubesOS/qubes-issues/issues/4840#issuecomment-869116013), I ran into similar problems, because I didn't.

>     3. Boot on usb drive

**Comment by Maltstar** [comment]
Yes I verified the checksum as well as the signed key.
I just run a test to compare the iso and the usb drive using 
```bash
sudo cmp -n `stat -c '%s' Qubes-R4.2.3-x86_64.iso` Qubes-R4.2.3-x86_64.iso /dev/sda
```
then
```bash
echo "$?"
```
I got 
`0`  which means the iso and the flle flashed on the iso are the same.

So what could be the problem with the iso?

**Comment by marmarek** [comment]
This may be related to https://forum.qubes-os.org/t/not-booting-with-linux-6-6-48-but-still-booting-with-6-6-42/29421/19
The fix should be available in few days (hopefully Linux 6.6.63 will have it, but it hasn't been released yet)

**Comment by Maltstar** [comment]
ok, should I try to build the iso with qubes builder using the last working kernel with Nvdia GPU (6.6-42) or should I wait for the 6.6.63?
What about a new downloadable iso for Qubes OS with the path, is it foreseen?

**Comment by marmarek** [comment]
https://lore.kernel.org/stable/cbd45b90-668a-4a2e-abb0-66b43b49ce94@gmail.com/T/#t - looks like we can expect 6.6.63 in about 2 days

**Comment by Maltstar** [comment]
Thank you for the update.  So when the 6.6.63 is available, should I wait for an official release of  the Qubes OS iso or should I use qubes builder and configure it to build the iso with 6.6.63?

**Comment by marmarek** [comment]
we have weekly builds at https://qubes.notset.fr/iso-testing/ - next ISO there after 6.6.63 release will have it already

**Comment by Maltstar** [comment]
Super thank you!!!

**Comment by ejose19** [comment]
@Maltstar you can also try [Qubes 4.2.2](https://mirrors.edge.kernel.org/qubes/iso/Qubes-R4.2.2-x86_64.torrent) which includes an older kernel.

**Comment by marmarek** [comment]
https://qubes.notset.fr/iso-testing/Qubes-4.2.202411231736-x86_64.iso has kernel 6.6.63

**Comment by Maltstar** [comment]
ok thank you. I will tested it out and let you know.

**Comment by Maltstar** [comment]
The new kernel solved the problem. The iso can be installed without problems on machine with Nvidia Graphic cards.
Thanks again for your support.
Long live Qubes OS, its team and community!!
