### ISSUE TITLE
Wayland (Plasma): menu opens as a decorated window, at the center of the screen 

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#9600]
## Observation

openQA test in scenario qubesos-4.3-update-x86_64-system_tests_kde_gui_interactive@64bit fails in
[simple_gui_apps](https://openqa.qubes-os.org/tests/119284/modules/simple_gui_apps/steps/4)

## Test suite description
Basic installation and interaction with KDE

## Reproducible

Fails since (at least) Build [2024082022-4.3](https://openqa.qubes-os.org/tests/109978)

## Expected result

Last good: [2024082004-4.3](https://openqa.qubes-os.org/tests/109622) (or more recent)

## Further details

Always latest result in this scenario: [latest](https://openqa.qubes-os.org/tests/latest?arch=x86_64&distri=qubesos&flavor=update&machine=64bit&test=system_tests_kde_gui_interactive&version=4.3)

**Comment by alimirjamali** [comment]
What happens if the Appmenu is launched with `LIBDECOR_FORCE_CSD=1`?

**Comment by marmarek** [comment]
I don't think it uses libdecor, it's GTK. Anyway, I tried, it doesn't help.

**Comment by marmarek** [comment]
There are two (possibly separate, but related) issues:
- decoration
- position

**Comment by marmarek** [comment]
And BTW, setting the position in the menu settings, for example to "top left" doesn't work either.
