### ISSUE TITLE
Qubes Manager/ Firewall: Allow rules for ports

### ISSUE THREAD

**Issue by fowlslegs** [QubesOS/qubes-issues#961]
It would be nice to have the ability to only allow traffic to flow through certain ports from the Qubes Firewall menu. Rules could be a combination of port + (domain or ip address (range))--while either side of the + could be a wildcard.

**Comment by marmarek** [comment]
I'm assigning milestone 3.1 for now, but in practice I think it would be much easier to implement it in Qubes 4.x (so not this year...), because current firewall rules generator (and config format) is really limited and will be rewritten in Qubes 4.0 anyway.

**Comment by marmarek** [comment]
I've read your description again. It is exactly how firewall rules are working there. You can use `*` in address field (which is one of examples in drop down menu there).
