### ISSUE TITLE
Menu does not honor `NoDisplay=true`

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#9611]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

R4.3, likely R4.2 too

### Brief summary

desktop files with `NoDisplay=true` should not be displayed in the menu

### Steps to reproduce

Find a desktop file with `NoDisplay=true`, for example `gpk-prefs.desktop`
See if it's visible in the menu

### Expected behavior

No entry

https://specifications.freedesktop.org/desktop-entry-spec/latest/recognized-keys.html
> NoDisplay means "this application exists, but don't display it in the menus". This can be useful to e.g. associate this application with MIME types, so that it gets launched from a file manager (or other apps), without having a menu entry for it (there are tons of good reasons for this, including e.g. the netscape -remote, or kfmclient openURL kind of stuff). 

### Actual behavior

It's included

**Comment by alimirjamali** [comment]
Notes: Appmenu extractor was fixed during the patch for [#1348](
https://github.com/QubesOS/qubes-issues/issues/1348#issuecomment-149543161) to ignore .desktop files with `NoDisplay=true` entries. But it does not work for such desktop files native to GUIVM (or dom0).

**Comment by alimirjamali** [comment]
PR Submitted (just two lines)

Review priority: low
