### ISSUE TITLE
Qubes update tool: Summary for Fedora templates not alphabetically sorted

### ISSUE THREAD

**Issue by Geblaat** [QubesOS/qubes-issues#9617]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
R4.2.3

### Brief summary
When using Qubes Update tool with Fedora based templates, the summary at the end with list of updated/installed packages is not in alphabetical order, which makes it harder to read and see what is updated. When running DNF inside the template instead of using Qubes Update, the order **is** alphabetical, so this seems to be a bug in Qubes Update.
In addition to that, Qubes update does show the updated packages in alphabetical order for Debian based templates.

### Steps to reproduce
Use Qubes Update tool to update Fedora based templates

### Expected behavior
Summary at the end with list of updated/installed packages should be listed in alphabetical order to make it easier to glance through and see what is updated.

### Actual behavior
The list is not in alphabetical order.

**Comment by alimirjamali** [comment]
Observation:

Update summary of both GUI & CLI updaters for all Distros/Package managers is printed via `_print_changes` [function](https://github.com/QubesOS/qubes-core-admin-linux/blob/main/vmupdate/agent/source/common/package_manager.py#L215-L243) of PackageManager class of the `core-admin-linux` vmupdate. Sorting installed, updated and removed packages is harmless and easy. I will do it and test it for few updates and submit the PR.
