### ISSUE TITLE
Kernel 6.12.x built with qubes-builderv2 cannot boot when used for qubes

### ISSUE THREAD

**Issue by Minimalist73** [QubesOS/qubes-issues#9631]
### Qubes OS release
r4.2.3 (r4.3 too I would guess)

### Brief summary
When building one of the 6.12 kernel versions with qubes-builderv2, the kernel won't boot when used for qubes.
libxl immediately displays an error message.
libxl-driver.log contains the following:
```
xc: panic: xg_dom_bzimageloader.c:761: xc_dom_probe_bzimage_kernel unable to XZ decompress kernel: Invalid kernel
xc: panic: xg_dom_core.c:689: xc_dom_find_loader: no loader found: Invalid kernel
libxl: libxl_dom.c:571:libxl__build_dom: xc_dom_parse_image failed
libxl: libxl_create.c:1716:domcreate_rebuild_done: Domain 58:cannot (re-)build domain: -3
```

### Steps to reproduce
- Build kernel 6.12.x using qubes-builderv2 (https://github.com/QubesOS/qubes-linux-kernel/pull/1038)
- Move the .rpm files to dom0 and install them
- Start any qube
- Get boot errors

### Expected behavior
qubes boot just like any previous kernel version.

### Actual behavior
qubes don't boot and shows an error.

**Comment by marmarek** [comment]
This is already fixed in https://github.com/QubesOS/qubes-vmm-xen/pull/194/commits/d63e9a9d64835758c82775693e4f3d3315d7c978 (R4.3). It will get backported to R4.2 before 6.12 kernel hits R4.2 repos.

**Comment by marmarek** [comment]
https://github.com/QubesOS/updates-status/issues/5317 contains the backported patch.
