### ISSUE TITLE
`kernel-6.6.64-1.qubes.fc37.x86_64` prevents any VM from starting

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#9638]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

R4.2

### Brief summary

After installing `kernel-1000:6.6.64-1.qubes.fc37.x86_64`, no VM starts.  Setting the default kernel to `6.6.64-1.fc37` allows VMs to start normally.  The VMs fail to boot before printing even a single line to the kernel log.

### Steps to reproduce

See above.

### Expected behavior

VMs start.

### Actual behavior

VMs do not start.

**Comment by marmarek** [comment]
> I believe this is closely related to #9631.

I doubt it, that one is failing when unpacking the kernel, but here it crashes later.

**Comment by marmarek** [comment]
Fixed in 6.6.65.
