### ISSUE TITLE
Security critical bug: input is often directed to a window that is not focused, esp. w/ text editors

### ISSUE THREAD

**Issue by fowlslegs** [QubesOS/qubes-issues#964]
Sometimes I will switch windows and possibly virtual desktops and the old window will receive my keyboard input. This even happens if the windows are in different domUs! Switching to another window then coming back to the one I actually wanted focused usually works on the first try, but sometimes, the bug is persistent and you need to do this a couple times. Emacs and gVim are especially prone to "stealing" input from other windows.

If I were entering a password into a more secure VM and a lesser secure VM were to receive the input, that could potentially be catastrophic.

**Comment by marmarek** [comment]
This is duplicate of #738. Also are you sure that this happens between windows of the different VMs? Our tests on the original issue confirmed the bug is only between windows of the same VM. Can you give step by step reproduction of such case?

**Comment by fowlslegs** [comment]
I don't think this happens between domUs actually. I can't reproduce it at least. I think my memory of it happening may be mistaken. You can close this issue. Apologies.
