### ISSUE TITLE
Whonix templates broken after update

### ISSUE THREAD

**Issue by Szewcson** [QubesOS/qubes-issues#9642]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
Qubes OS 4.2, Whonix 0:4.2.0-202412081147

### Brief summary
After updating both whonix templates they stop to updating and lacks apps.

### Steps to reproduce
Update whonix templates to latest version, then try to update apps using qubes updater.

### Expected behavior
Everything work.

### Actual behavior
Templates are broken.

**Comment by marmarek** [comment]
Fix is already here: https://github.com/QubesOS/qubes-builderv2/pull/164
