### ISSUE TITLE
KMix tray popup unusable when 5+ domUs open

### ISSUE THREAD

**Issue by nvesely** [QubesOS/qubes-issues#966]
I guess KDE never prepared for 10+ input devices because the tray popup menu of KMix cuts off on the end of the screen. I disabled "capture streams," so now there is only a master mic volume (which is fine for 99% of mic use cases), but if I run 10+ VMs now I get the same problem, where I can't see the rightmost sliders.

Maybe a newer Fedora will have a KMix w/ a bar or something on the bottom to scroll back and forth across device sliders? I could also see not, just because who on a normal machine has 10+ audio I/O devices? You shouldn't spend your time fixing it, but maybe a community member or KDE wants to?

**Comment by marmarek** [comment]
Actually those should not be "audio I/O devices", but "audio applications" (playing and recording), which is thinkable on "normal" system.
I'm afraid that newer Fedora (21) will not solve anything, because KDE version is the same. Maybe Fedora 22?

**Comment by fowlslegs** [comment]
>Actually those should not be "audio I/O devices", but "audio applications" (playing and recording), which is thinkable on "normal" system.

You're right--written late.

>I'm afraid that newer Fedora (21) will not solve anything, because KDE version is the same. Maybe Fedora 22?

Have you considered skipping Fedora 21 release and moving straight to 22 for Qubes 3.X? I know Qubes 3.0 is supposed to ship with Fedora 20 still.

**Comment by marmarek** [comment]
On Sat, Apr 25, 2015 at 03:07:13PM -0700, Noah Vesely wrote:
> >I'm afraid that newer Fedora (21) will not solve anything, because KDE version is the same. Maybe Fedora 22?
> 
> Have you considered skipping Fedora 21 release and moving straight to 22 for Qubes 3.X? I know Qubes 3.0 is supposed to ship with Fedora 20 still.

Yes. 3.0 will have dom0 based on Fedora 20, but we will upgrade to
newer Fedora in 3.1. If Fedora 22 will release and usable at that time,
it is a good idea to skip 21.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by fowlslegs** [comment]
>If Fedora 22 will be released and usable at that time, it is a good idea to skip 21.

Sounds good. 22 release date is May 26th, so that should give the Fedora team a couple months to work out initial release bugs before 3.1.

**Comment by unman** [comment]
@andrewdavidwong In current KDE in 4.0 the mix stacks vertically, with a scrollbar, so this issue does not arise. (I assume from reading that in Fedora 20 the mixer showed inputs side by side.)
Please close.
