### ISSUE TITLE
Apper warns you haven't updated in months when you have

### ISSUE THREAD

**Issue by nvesely** [QubesOS/qubes-issues#968]
I normally use qubes-dom0-update, but sometimes I launch the updaters from Qubes Manager. Apper, for dom0, always warns you haven't updated in a month+ even though you have.

**Comment by marmarek** [comment]
PackageKit (used by Apper) checks for network connection before updating a cache, and it there is no network connection (dom0 have never network access) it simply do nothing.
In previous PackageKit version there was an option to disable this check, but it was removed (hughsie/PackageKit@fe1b2d25d70fd6cc041acf6546c655ddb247c3f3). Currently the only way I've found to force PackageKit to refresh its cache is to create dummy network interface in dom0...

**Comment by adrelanos** [comment]
GUI Upgrading is actually very hard to get right. Security, usability and reasonable bug freeness is difficult to archive in the absence of any mature GUI upgrading tools. We have recently discussed this with respect to Qubes at the Whonix tracker [but the discussion applies to any Linux distribution]. Now it seems stalled. Read more:
https://phabricator.whonix.org/T373

**Comment by marmarek** [comment]
As a stopgap, it would make sense to simply start a terminal with `qubes-dom0-update` instead of Apper.

**Comment by adrelanos** [comment]
(For reference only.)

> As a stopgap, it would make sense to simply start a terminal with qubes-dom0-update instead of Apper.

Seems like you created `Launch dom0 updates as qubes-dom0-update in terminal emulator ` (https://github.com/QubesOS/qubes-issues/issues/1378) for it.

**Comment by marmarek** [comment]
Yes, so moving this one to some later milestone.

**Comment by marmarta** [comment]
This was solved as in https://github.com/QubesOS/qubes-issues/issues/1378
