### ISSUE TITLE
Debian repository errors

### ISSUE THREAD

**Issue by fowlslegs** [QubesOS/qubes-issues#972]
I'm getting the following error with apt-get update since the repo update yesterday:

    W: Failed to fetch http://deb.qubes-os.org/r2/vm/dists/jessie/main/source/Sources  Hash Sum mismatch

    W: Failed to fetch http://deb.qubes-os.org/r2/vm/dists/jessie/main/binary-amd64/Packages  Hash Sum mismatch

    E: Some index files failed to download. They have been ignored, or old ones used instead.

    http://deb.qubes-os.org/r2/vm/dists/jessie/main/binary-amd64/Packages

These files are blank, but I checked jessie/Release and then ran `{md5,sha1,sha256}sum /dev/null` and it looked like you had put in the right strings. I also skimmed https://wiki.debian.org/RepositoryFormat to see if I could find a problem with this file or something else (and to learn a bit about deb repos), but everything seemed correct.

**Comment by marmarek** [comment]
Fixed
