### ISSUE TITLE
Too small memory assignment for DispVM

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#973]
Currently when new DispVM is started, it gets amount of memory set for `TEMPLATENAME-dvm` VM, which is by default 400MB. It can happen that DispVM savefile requires somehow more memory - the exact number is reported during savefile creation, by `qvm-create-default-dvm`.  DispVM should get that much memory instead of static 400MB.

This is known to be happening for DispVMs based on fedora-20-x64 template after in-place upgrade from R2 to R3.0-rc1.
The workaround is to increase initial memory for `TEMPLATENAME-dvm` VM.

**Comment by Zrubi** [comment]
It seems to be affected by the dom0 kernel as well.
Just tested the 3.19 kernel, and the new f-21 template based DVM was not started because this issue.
