### ISSUE TITLE
[3.0-RC1] Can't resume paused VM

### ISSUE THREAD

**Issue by v6ak** [QubesOS/qubes-issues#981]
Steps to reproduce:

0. Run Qubes VM manager
1. Start an AppVM
2. Pause the VM
3. Start/resume the VM

Expected result: The VM is resumed.

Actual result:

    ----
    line: assert not vm.is_running()
    func: action_resumevm_triggered
    line no.: 973
    file: /usr/lib64/python2.7/site-packages/qubesmanager/main.py

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-manager-2.0.41-1` has been pushed to the `r2` stable repository for dom0.
To install this update, please use the standard update command:
```
sudo qubes-dom0-update
```
Or update dom0 via Qubes Manager.

[builder-github]: https://github.com/QubesOS/qubes-builder-github
