### ISSUE TITLE
Graphical update of Fedora 21 template reports no updates available

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#982]
Update of Fedora 21 template started from Qubes Manager reports no updates available, while at the same time `yum update` properly download and install updates.

**Comment by marmarek** [comment]
Graphical update uses PackageKit, which loads default (for given distribution) backend. In case of Fedora 21 it is hawkey, dnf - new libraries, forked from yum. Apparently when called from PackageKit, it doesn't load global settings - especially proxy (checking via `strace` it doesn't load any configuration other than `/etc/yum.repos.d`).
Until this will be fixed upstream, GUI updates will not work.

BTW dnf uses its own configuration file `/etc/dnf/dnf.conf` and ignores `/etc/yum.conf`. Also it doesn't support including other config files. So proxy needs to be set directly in `/etc/dnf/dnf.conf`. In case of Qubes it should be done by `/usr/lib/qubes/init/misc-post.sh` in addition to `/etc/yum.conf.d/qubes-proxy.conf`.

**Comment by marmarek** [comment]
https://lists.fedoraproject.org/pipermail/devel/2015-January/205966.html

**Comment by marmarek** [comment]
[Proposed workaround](https://groups.google.com/d/msgid/qubes-users/ee3676f0-27fa-4b50-a4d5-dbb67eb9d351%40googlegroups.com):
> I chose to change qubes-manager to call "gnome-terminal -e 'yum 
> distro-sync'" instead of gpk-update-viewer as a short-term fix, since I'm 
> currently using another tool that only works with yum and I know there are 
> more changes to package management in Fedora 22.  If this is indeed a 
> problem that will affect everyone upgrading from Fedora 20, please consider 
> fixing it somehow so that they don't all waste time on the same 
> troubleshooting.  (I haven't checked if there's a fix in the official 
> Fedora 21 template.)

**Comment by mfc** [comment]
does the workaround work? if so I would recommend pushing it out for the final Release 3.0 (rather than 3.1), as it would be weird for there to be feature depreciation between R2.0 and R3.0 in this regard.

**Comment by marmarek** [comment]
PackageKit fix: https://github.com/hughsie/PackageKit/commit/d1a429092bfb6a029dbfb40f2a8dd613bf93525e

No idea when it will land in Fedora.

**Comment by marmarek** [comment]
Fedora 21 is EOL and PackageKit is fixed in Fedora 23 (and probably 22)
