### ISSUE TITLE
qubes-dom0-updates fails always after one fail

### ISSUE THREAD

**Issue by v6ak** [QubesOS/qubes-issues#987]
Since /var/lib/qubes/updates/errors is not automatically deleted, qubes-dom0-updates gives up if there was a problem in the past. See https://github.com/abeluck/qubes-core/commit/a680976f1e48664c543272c2f4ce6ef08b024c50#diff-c2fc1ccc6b7d0d54b8baa948e60180d3R90 .

Workaround: run `sudo rm /var/lib/qubes/updates/errors` in Dom0 and try again.

I think /var/lib/qubes/updates/errors (and maybe some other files) should be automatically cleaned:
1. before qubes-dom0-update – in order to handle suddenly stopped update process correctly
2. after qubes-dom0-update – in order to clean unneeded files as soon as possible

Maybe some files should be moved to /tmp.

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-dom0-linux-2.0.31-1.fc20` has been pushed to the `r2` stable repository for dom0.
To install this update, please use the standard update command:
```
sudo qubes-dom0-update
```
Or update dom0 via Qubes Manager.

[builder-github]: https://github.com/QubesOS/qubes-builder-github
