### ISSUE TITLE
Debian page of User Docs incorrect.

### ISSUE THREAD

**Issue by MichaelJ3** [QubesOS/qubes-issues#991]
https://www.qubes-os.org/doc/Templates/Debian/

Docs give following command which returns an error for package unavailable:
[user@dom0 ~]$ sudo qubes-dom0-update qubes-template-debian-7

Actual command that works:
[user@dom0 ~]$ sudo qubes-dom0-update --enablerepo=qubes-templates-community qubes-template-debian-7-x64

..for debian 8
[user@dom0 ~]$ sudo qubes-dom0-update --enablerepo=qubes-templates-community qubes-template-debian-8-x64

**Comment by Trozz** [comment]
I would imagine that Debian is coming to the main repo's as it is now identified as a "supported" image, however it still does not appear to be there

**Comment by marmarek** [comment]
Yes, it will be there, under new name (without "-x64"). In few days...

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by marmarek** [comment]
New debian templates uploaded.
