### ISSUE TITLE
Ability to automatically attach some drives to PVMs 

### ISSUE THREAD

**Issue by v6ak** [QubesOS/qubes-issues#992]
I'd like to be able to add multiple R/W images to my AppVMs. This is currently possible for HVMs, but not for PVMs.

Usage examples:
- SSD + HDD combination
- multiple FSs with different settings (e.g. long-commit FS or non-journaling FS for some special purposes where persistence is not so critical – cache, logs)

This may require a custom fstab or at least a simple startup script that mounts the extra filesystem.

Related discussion: https://groups.google.com/forum/#!topic/qubes-users/vPUlrNNX3vc

**Comment by marmarek** [comment]
qvm-block (and other qvm-device) in Qubes 4.0 support `--persistent` option, which is exactly for this purpose.
