### ISSUE TITLE
libvirtd crash

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#995]
Sometimes libvirtd crashes with:

```
libvirtd: libxl_internal.h:2784: libxl__ctx_unlock: Assertion `!r' failed
```

It is automatically restarted, so impact is rather small, but Qubes Manager is unusable after that (because it doesn't reconnect to libvirtd), see #990.
I know no reliable way to reproduce, but running DispVM tests often triggers this issue.

**Comment by unman** [comment]
@andrewdavidwong We have been unable to reproduce this issue in 3.2
