### ISSUE TITLE
Backup progress miscalculated when compression is enabled

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#997]
Backup progress shows progress as "size of output written"/"total size of selected VMs". When compression is enabled, this is obviously wrong, because at the end "size of output written" is not the same as original size.

This may be not easy to fix (while preserving frequent enough progress updates), because the first step applies the compression (tar -cz...) and we don't have direct progress reporting there. So the most obvious fix would mean that progress would be updated only when going to the next VM.

**Comment by v6ak** [comment]
Maybe adding some process that counts all the bytes and stores the value somewhere would help. I mean something like this:

    tar -c | watch-progress /tmp/progressfile | gzip

As far as I remember, `dd` can do this (it prints statistics when USR1 signal is received), but writing a custom simple proxy might be easier.

(I don't care about this issue much, so I won't send a patch. I just wanted to share an idea of a hopefully easy fix.)

**Comment by marmarek** [comment]
Backup tool monitor all the process involved in backup creation, so when
changed from "tar -c --use-compression-program=gzip" to "tar | something
| gzip" it means two additional processes to watch. I'm not saying it
isn't possible, just more work than it may look as. And while this has
"minor" priority...

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by axon-qubes** [comment]
This seems *very* minor, IMHO. I would be surprised if many people even notice this, and among those who do notice it, I would be surprised if any were bothered by it. All I observed is that my backups seem to finish sooner than expected, which is actually rather nice. :P

**Comment by unman** [comment]
@andrewdavidwong Confirmed issue still arises in 3.2 milestone, but it is, as you say, minor in extreme

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 recently reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
