### ISSUE TITLE
Bring back qvm-img-converter

### ISSUE THREAD

**Issue by rootkovska** [QubesOS/qubes-issues#999]
Currently missing in 3.0, needed e.g. for wallpapers conversion before they could be copied to Dom0.

**Comment by marmarek** [comment]
It wasn't migrated to github, but fortunately I had some old checkout. Uploaded to current-testing.

**Comment by rootkovska** [comment]
Can we pls have it in 3.2 installed by default? It's very useful e.g. for ppl setting up custom wallpapers... (before we get #215 implemented by someone...)
